@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:config.fs_dwh_database_name.adoc[]" as config.fs_dwh_database_name << FN >> {
  --
}

entity "puml-link:dhw:sqldb:config.parameter.adoc[]" as config.Parameter << U >> {
  - **Parameter_name** : (varchar(100))
  - **sub_Parameter** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:docs.antorapage_objectbyschema.adoc[]" as docs.AntoraPage_ObjectBySchema << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.antorapage_objectbytype.adoc[]" as docs.AntoraPage_ObjectByType << V >> {
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectcolumnproperty_forupdate.adoc[]" as property.RepoObjectColumnProperty_ForUpdate << V >> {
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty_forupdate.adoc[]" as property.RepoObjectProperty_ForUpdate << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo_sys.usp_addorupdateextendedproperty.adoc[]" as repo_sys.usp_AddOrUpdateExtendedProperty << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo_sys.usp_dropextendedproperty_in_dwh.adoc[]" as repo_sys.usp_DropExtendedProperty_in_dwh << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo_sys.usp_dropextendedproperty_level_0.adoc[]" as repo_sys.usp_dropextendedproperty_level_0 << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo_sys.usp_dropextendedproperty_level_1.adoc[]" as repo_sys.usp_dropextendedproperty_level_1 << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo_sys.usp_dropextendedproperty_level_2.adoc[]" as repo_sys.usp_dropextendedproperty_level_2 << P >> {
  --
}

config.fs_dwh_database_name <.. repo_sys.usp_AddOrUpdateExtendedProperty
config.fs_dwh_database_name <.. repo_sys.usp_dropextendedproperty_level_1
config.fs_dwh_database_name <.. repo_sys.usp_dropextendedproperty_level_2
config.fs_dwh_database_name <.. docs.AntoraPage_ObjectByType
config.fs_dwh_database_name <.. docs.AntoraPage_ObjectBySchema
config.fs_dwh_database_name <.. property.RepoObjectColumnProperty_ForUpdate
config.fs_dwh_database_name <.. property.RepoObjectProperty_ForUpdate
config.fs_dwh_database_name <.. repo_sys.usp_DropExtendedProperty_in_dwh
config.fs_dwh_database_name <.. repo_sys.usp_dropextendedproperty_level_0
config.Parameter <.. config.fs_dwh_database_name
@enduml

