@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity "puml-link:config.fs_dwh_database_name.adoc[prefix=..]" as config.fs_dwh_database_name << FN >> {
  --
}

entity "puml-link:config.fs_get_parameter_value.adoc[prefix=..]" as config.fs_get_parameter_value << FN >> {
  --
}

entity "puml-link:config.ftv_dwh_database.adoc[prefix=..]" as config.ftv_dwh_database << IF >> {
  --
}

entity "puml-link:config.ftv_get_parameter_value.adoc[prefix=..]" as config.ftv_get_parameter_value << IF >> {
  --
}

entity "puml-link:config.Parameter.adoc[prefix=..]" as config.Parameter << U >> {
  - **Parameter_name** : (varchar(100))
  - **sub_Parameter** : (nvarchar(128))
  --
}

entity "puml-link:config.usp_init_parameter.adoc[prefix=..]" as config.usp_init_parameter << P >> {
  --
}

entity "puml-link:config.usp_parameter_set.adoc[prefix=..]" as config.usp_parameter_set << P >> {
  --
}

entity "puml-link:docs.usp_AntoraExport_DocSnippet.adoc[prefix=..]" as docs.usp_AntoraExport_DocSnippet << P >> {
  --
}

entity "puml-link:docs.usp_AntoraExport_ObjectPageTemplate.adoc[prefix=..]" as docs.usp_AntoraExport_ObjectPageTemplate << P >> {
  --
}

entity "puml-link:property.PropertyName_RepoObject.adoc[prefix=..]" as property.PropertyName_RepoObject << V >> {
  **property_name** : (nvarchar(128))
  --
}

entity "puml-link:property.PropertyName_RepoObjectColumn.adoc[prefix=..]" as property.PropertyName_RepoObjectColumn << V >> {
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:property.RepoObjectColumnProperty_InheritanceType_InheritanceDefinition.adoc[prefix=..]" as property.RepoObjectColumnProperty_InheritanceType_InheritanceDefinition << V >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:property.RepoObjectProperty_InheritanceType_InheritanceDefinition.adoc[prefix=..]" as property.RepoObjectProperty_InheritanceType_InheritanceDefinition << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:repo.usp_persistence_set.adoc[prefix=..]" as repo.usp_persistence_set << P >> {
  --
}

config.Parameter <.. config.fs_dwh_database_name
config.Parameter <.. config.fs_get_parameter_value
config.Parameter <.. config.ftv_dwh_database
config.Parameter <.. config.ftv_get_parameter_value
config.Parameter <.. config.usp_init_parameter
config.Parameter <.. config.usp_parameter_set
config.Parameter <.. repo.usp_persistence_set
config.Parameter <.. property.PropertyName_RepoObject
config.Parameter <.. property.PropertyName_RepoObjectColumn
config.Parameter <.. property.RepoObjectProperty_InheritanceType_InheritanceDefinition
config.Parameter <.. property.RepoObjectColumnProperty_InheritanceType_InheritanceDefinition
config.Parameter <.. docs.usp_AntoraExport_ObjectPageTemplate
config.Parameter <.. docs.usp_AntoraExport_DocSnippet
footer
to view a reduced diagram in original size and to be able to click on the links:
open the diagram in a new tab via the Context menu.
end footer

@enduml

