@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity "[[{site-url}/{page-component-name}/{page-component-version}/{page-module}/config.usp_connect_database.html config.usp_connect_database]]" as config.usp_connect_database << P >> {
  --
}

entity "[[{site-url}/{page-component-name}/{page-component-version}/{page-module}/config.usp_init_parameter.html config.usp_init_parameter]]" as config.usp_init_parameter << P >> {
  --
}

entity "[[{site-url}/{page-component-name}/{page-component-version}/{page-module}/config.usp_parameter_set.html config.usp_parameter_set]]" as config.usp_parameter_set << P >> {
  --
}

entity "[[{site-url}/{page-component-name}/{page-component-version}/{page-module}/configT.usp_init_spt_values.html configT.usp_init_spt_values]]" as configT.usp_init_spt_values << P >> {
  --
}

config.usp_init_parameter <.. config.usp_connect_database
config.usp_parameter_set <.. config.usp_connect_database
configT.usp_init_spt_values <.. config.usp_connect_database
footer
to view a reduced diagram in original size and to be able to click on the links:
open the diagram in a new tab via the Context menu.
end footer

@enduml

