@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity "[[{site-url}/{page-component-name}/current/{page-module}/docs.AntoraIndexSemanticgroupPatterndatatype.html docs.AntoraIndexSemanticgroupPatterndatatype]]" as docs.AntoraIndexSemanticgroupPatterndatatype << V >> {
  **IndexSemanticGroup** : (nvarchar(512))
  **IndexPatternColumnDatatype** : (nvarchar(4000))
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/docs.fs_cleanStringForLabel.html docs.fs_cleanStringForLabel]]" as docs.fs_cleanStringForLabel << FN >> {
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/docs.RepoObject_ColumnList.html docs.RepoObject_ColumnList]]" as docs.RepoObject_ColumnList << V >> {
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/docs.RepoObject_IndexList.html docs.RepoObject_IndexList]]" as docs.RepoObject_IndexList << V >> {
  **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/docs.RepoObject_MeasureList.html docs.RepoObject_MeasureList]]" as docs.RepoObject_MeasureList << V >> {
  --
}

docs.fs_cleanStringForLabel <.. docs.RepoObject_ColumnList
docs.fs_cleanStringForLabel <.. docs.AntoraIndexSemanticgroupPatterndatatype
docs.fs_cleanStringForLabel <.. docs.RepoObject_MeasureList
docs.fs_cleanStringForLabel <.. docs.RepoObject_IndexList
footer
to view a reduced diagram in original size and to be able to click on the links:
open the diagram in a new tab via the Context menu.
end footer

@enduml

