@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity "[[{site-url}/{page-component-name}/current/{page-module}/docs.AntoraNavListPage_by_type.html docs.AntoraNavListPage_by_type]]" as docs.AntoraNavListPage_by_type << V >> {
  **type** : (nvarchar(128))
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/docs.AntoraNavListRepoObject_by_schema.html docs.AntoraNavListRepoObject_by_schema]]" as docs.AntoraNavListRepoObject_by_schema << V >> {
  - **RepoObject_schema_name** : (nvarchar(128))
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/docs.AntoraNavListRepoObject_by_schema_type.html docs.AntoraNavListRepoObject_by_schema_type]]" as docs.AntoraNavListRepoObject_by_schema_type << V >> {
  - **RepoObject_schema_name** : (nvarchar(128))
  **type** : (char(2))
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/docs.AntoraNavListRepoObject_by_type.html docs.AntoraNavListRepoObject_by_type]]" as docs.AntoraNavListRepoObject_by_type << V >> {
  **type** : (char(2))
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/docs.RepoObject_OutputFilter.html docs.RepoObject_OutputFilter]]" as docs.RepoObject_OutputFilter << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/docs.RepoObject_Plantuml_Entity.html docs.RepoObject_Plantuml_Entity]]" as docs.RepoObject_Plantuml_Entity << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/docs.Unit_1_union.html docs.Unit_1_union]]" as docs.Unit_1_union << V >> {
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/docs.usp_AntoraExport_ObjectPage.html docs.usp_AntoraExport_ObjectPage]]" as docs.usp_AntoraExport_ObjectPage << P >> {
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/docs.usp_AntoraExport_ObjectPartialProperties.html docs.usp_AntoraExport_ObjectPartialProperties]]" as docs.usp_AntoraExport_ObjectPartialProperties << P >> {
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/docs.usp_AntoraExport_ObjectPuml.html docs.usp_AntoraExport_ObjectPuml]]" as docs.usp_AntoraExport_ObjectPuml << P >> {
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/repo.RepoObject_gross.html repo.RepoObject_gross]]" as repo.RepoObject_gross << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

docs.RepoObject_OutputFilter <.. docs.usp_AntoraExport_ObjectPartialProperties
docs.RepoObject_OutputFilter <.. docs.usp_AntoraExport_ObjectPage
docs.RepoObject_OutputFilter <.. docs.AntoraNavListRepoObject_by_type
docs.RepoObject_OutputFilter <.. docs.AntoraNavListRepoObject_by_schema
docs.RepoObject_OutputFilter <.. docs.AntoraNavListRepoObject_by_schema_type
docs.RepoObject_OutputFilter <.. docs.RepoObject_Plantuml_Entity
docs.RepoObject_OutputFilter <.. docs.usp_AntoraExport_ObjectPuml
docs.RepoObject_OutputFilter <.. docs.AntoraNavListPage_by_type
docs.RepoObject_OutputFilter <.. docs.Unit_1_union
repo.RepoObject_gross <.. docs.RepoObject_OutputFilter
footer
to view a reduced diagram in original size and to be able to click on the links:
open the diagram in a new tab via the Context menu.
end footer

@enduml

