left to right direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity docs.obsolet_RepoObject_Plantuml_ColRefList << V >> {
  * **RepoObject_guid** : uniqueidentifier
  --
}

entity reference.obsolet_ftv_RepoObject_ReferencedReferencing << IF >> {
  --
}

entity reference.RepoObjectColumn_reference_T << U >> {
  **referenced_RepoObjectColumn_guid** : uniqueidentifier
  **referencing_RepoObjectColumn_guid** : uniqueidentifier
  --
}

entity repo.RepoObject << U >> {
  * **RepoObject_guid** : uniqueidentifier
  --
}

reference.obsolet_ftv_RepoObject_ReferencedReferencing <.. docs.obsolet_RepoObject_Plantuml_ColRefList
reference.RepoObjectColumn_reference_T <.. docs.obsolet_RepoObject_Plantuml_ColRefList
repo.RepoObject <.. docs.obsolet_RepoObject_Plantuml_ColRefList
