@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity "[[{site-url}/{page-component-name}/current/{page-module}/docs.RepoObject_Adoc.html docs.RepoObject_Adoc]]" as docs.RepoObject_Adoc << V >> {
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/property.ExtendedProperty_Repo2Sys_level1.html property.ExtendedProperty_Repo2Sys_level1]]" as property.ExtendedProperty_Repo2Sys_level1 << V >> {
  - **level0type** : (nvarchar(6))
  - **level0name** : (nvarchar(128))
  **level1type** : (varchar(9))
  - **level1name** : (nvarchar(128))
  - **property_name** : (nvarchar(128))
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/property.ExtendedProperty_Repo2Sys_level2_RepoObject.html property.ExtendedProperty_Repo2Sys_level2_RepoObject]]" as property.ExtendedProperty_Repo2Sys_level2_RepoObject << V >> {
  - **level0type** : (nvarchar(6))
  - **level0name** : (nvarchar(128))
  **level1type** : (varchar(9))
  - **level1name** : (nvarchar(128))
  **level2type** : (varchar(10))
  - **level2name** : (nvarchar(128))
  - **property_name** : (nvarchar(128))
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/property.fs_get_RepoObjectProperty_nvarchar.html property.fs_get_RepoObjectProperty_nvarchar]]" as property.fs_get_RepoObjectProperty_nvarchar << FN >> {
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/property.PropertyName_RepoObject.html property.PropertyName_RepoObject]]" as property.PropertyName_RepoObject << V >> {
  **property_name** : (nvarchar(128))
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/property.RepoObjectProperty.html property.RepoObjectProperty]]" as property.RepoObjectProperty << U >> {
  - **RepoObjectProperty_id** : (int)
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/property.RepoObjectProperty_ForUpdate.html property.RepoObjectProperty_ForUpdate]]" as property.RepoObjectProperty_ForUpdate << V >> {
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/property.RepoObjectProperty_InheritanceType_InheritanceDefinition.html property.RepoObjectProperty_InheritanceType_InheritanceDefinition]]" as property.RepoObjectProperty_InheritanceType_InheritanceDefinition << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/property.RepoObjectProperty_sys_repo.html property.RepoObjectProperty_sys_repo]]" as property.RepoObjectProperty_sys_repo << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **property_name** : (sysname)
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/property.usp_RepoObject_Inheritance.html property.usp_RepoObject_Inheritance]]" as property.usp_RepoObject_Inheritance << P >> {
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/property.usp_RepoObjectProperty_collect.html property.usp_RepoObjectProperty_collect]]" as property.usp_RepoObjectProperty_collect << P >> {
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/property.usp_RepoObjectProperty_set.html property.usp_RepoObjectProperty_set]]" as property.usp_RepoObjectProperty_set << P >> {
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/property.usp_sync_ExtendedProperties_Sys2Repo_InsertUpdate.html property.usp_sync_ExtendedProperties_Sys2Repo_InsertUpdate]]" as property.usp_sync_ExtendedProperties_Sys2Repo_InsertUpdate << P >> {
  --
}

property.RepoObjectProperty <.. property.RepoObjectProperty_sys_repo
property.RepoObjectProperty <.. property.ExtendedProperty_Repo2Sys_level1
property.RepoObjectProperty <.. property.ExtendedProperty_Repo2Sys_level2_RepoObject
property.RepoObjectProperty <.. property.usp_sync_ExtendedProperties_Sys2Repo_InsertUpdate
property.RepoObjectProperty <.. property.PropertyName_RepoObject
property.RepoObjectProperty <.. property.usp_RepoObject_Inheritance
property.RepoObjectProperty <.. property.RepoObjectProperty_InheritanceType_InheritanceDefinition
property.RepoObjectProperty <.. property.fs_get_RepoObjectProperty_nvarchar
property.RepoObjectProperty <.. docs.RepoObject_Adoc
property.RepoObjectProperty <.. property.usp_RepoObjectProperty_set
property.RepoObjectProperty <.. property.usp_RepoObjectProperty_collect
property.RepoObjectProperty <.. property.RepoObjectProperty_ForUpdate
footer
to view a reduced diagram in original size and to be able to click on the links:
open the diagram in a new tab via the Context menu.
end footer

@enduml

