left to right direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity reference.ftv_RepoObject_ColumReferenceRepoObject << IF >> {
  --
}

entity reference.RepoObjectColumn_reference_union << V >> {
  --
}

entity reference.RepoObjectColumn_RelationScript << V >> {
  --
}

entity repo.RepoObjectColumn << U >> {
  * **RepoObjectColumn_guid** : uniqueidentifier
  --
}

reference.RepoObjectColumn_reference_union <.. reference.RepoObjectColumn_RelationScript
reference.RepoObjectColumn_RelationScript <.. reference.ftv_RepoObject_ColumReferenceRepoObject
repo.RepoObjectColumn <.. reference.RepoObjectColumn_RelationScript
