@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity "[[{site-url}/{page-component-name}/current/{page-module}/docs.fs_cleanStringForAnchorId.html docs.fs_cleanStringForAnchorId]]" as docs.fs_cleanStringForAnchorId << FN >> {
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/reference.RepoObjectColumn_ReferencedList.html reference.RepoObjectColumn_ReferencedList]]" as reference.RepoObjectColumn_ReferencedList << V >> {
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/reference.RepoObjectColumn_ReferencingReferenced.html reference.RepoObjectColumn_ReferencingReferenced]]" as reference.RepoObjectColumn_ReferencingReferenced << V >> {
  - **Referenced_guid** : (uniqueidentifier)
  - **Referencing_guid** : (uniqueidentifier)
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/repo.RepoObjectColumn_gross2.html repo.RepoObjectColumn_gross2]]" as repo.RepoObjectColumn_gross2 << V >> {
  --
}

docs.fs_cleanStringForAnchorId <.. reference.RepoObjectColumn_ReferencedList
reference.RepoObjectColumn_ReferencedList <.. repo.RepoObjectColumn_gross2
reference.RepoObjectColumn_ReferencingReferenced <.. reference.RepoObjectColumn_ReferencedList
footer
to view a reduced diagram in original size and to be able to click on the links:
open the diagram in a new tab via the Context menu.
end footer

@enduml

