left to right direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity reference.RepoObject_reference << V >> {
  **referenced_RepoObject_guid** : uniqueidentifier
  **referencing_RepoObject_guid** : uniqueidentifier
  --
}

entity reference.RepoObject_reference_T << U >> {
  **referenced_RepoObject_guid** : uniqueidentifier
  **referencing_RepoObject_guid** : uniqueidentifier
  --
}

entity reference.RepoObject_reference_union << V >> {
  **referenced_RepoObject_guid** : uniqueidentifier
  **referencing_RepoObject_guid** : uniqueidentifier
  --
}

entity reference.usp_PERSIST_RepoObject_reference_T << P >> {
  --
}

reference.RepoObject_reference <.. reference.usp_PERSIST_RepoObject_reference_T
reference.RepoObject_reference <.. reference.RepoObject_reference_T
reference.RepoObject_reference_union <.. reference.RepoObject_reference
