@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity "puml-link:config.fs_get_parameter_value.adoc[prefix=..]" as config.fs_get_parameter_value << FN >> {
  --
}

entity "puml-link:reference.additional_Reference.adoc[prefix=..]" as reference.additional_Reference << U >> {
  - **Id** : (int)
  --
}

entity "puml-link:reference.additional_Reference_guid.adoc[prefix=..]" as reference.additional_Reference_guid << V >> {
  --
}

entity "puml-link:reference.RepoObject_ExternalReferencedList.adoc[prefix=..]" as reference.RepoObject_ExternalReferencedList << V >> {
  --
}

entity "puml-link:reference.RepoObject_ExternalReferencingList.adoc[prefix=..]" as reference.RepoObject_ExternalReferencingList << V >> {
  --
}

entity "puml-link:reference.RepoObject_reference_additional_internal.adoc[prefix=..]" as reference.RepoObject_reference_additional_internal << V >> {
  --
}

entity "puml-link:reference.RepoObjectColumn_reference_additional_internal.adoc[prefix=..]" as reference.RepoObjectColumn_reference_additional_internal << V >> {
  --
}

entity "puml-link:repo.RepoObject.adoc[prefix=..]" as repo.RepoObject << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:repo.RepoObjectColumn.adoc[prefix=..]" as repo.RepoObjectColumn << U >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  --
}

config.fs_get_parameter_value <.. reference.additional_Reference_guid
reference.additional_Reference <.. reference.additional_Reference_guid
reference.additional_Reference_guid <.. reference.RepoObject_ExternalReferencedList
reference.additional_Reference_guid <.. reference.RepoObject_ExternalReferencingList
reference.additional_Reference_guid <.. reference.RepoObject_reference_additional_internal
reference.additional_Reference_guid <.. reference.RepoObjectColumn_reference_additional_internal
repo.RepoObject <.. reference.additional_Reference_guid
repo.RepoObjectColumn <.. reference.additional_Reference_guid
footer
to view a reduced diagram in original size and to be able to click on the links:
open the diagram in a new tab via the Context menu.
end footer

@enduml

