@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity "[[{site-url}/{page-component-name}/current/{page-module}/repo.Index_ColumList.html repo.Index_ColumList]]" as repo.Index_ColumList << V >> {
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/repo.Index_IndexPattern.html repo.Index_IndexPattern]]" as repo.Index_IndexPattern << V >> {
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing.html repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing]]" as repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing << V >> {
  - **index_guid** : (uniqueidentifier)
  - **index_column_id** : (int)
  **RowNumberInReferencing** : (bigint)
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/repo.IndexColumn_union.html repo.IndexColumn_union]]" as repo.IndexColumn_union << V >> {
  **index_guid** : (uniqueidentifier)
  - **index_column_id** : (int)
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/repo.IndexColumn_union_T.html repo.IndexColumn_union_T]]" as repo.IndexColumn_union_T << U >> {
  **index_guid** : (uniqueidentifier)
  - **index_column_id** : (int)
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/repo.RepoObjectColumn_gross2.html repo.RepoObjectColumn_gross2]]" as repo.RepoObjectColumn_gross2 << V >> {
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/repo.usp_PERSIST_IndexColumn_union_T.html repo.usp_PERSIST_IndexColumn_union_T]]" as repo.usp_PERSIST_IndexColumn_union_T << P >> {
  --
}

repo.IndexColumn_union <.. repo.IndexColumn_union_T
repo.IndexColumn_union_T <.. repo.Index_ColumList
repo.IndexColumn_union_T <.. repo.RepoObjectColumn_gross2
repo.IndexColumn_union_T <.. repo.usp_PERSIST_IndexColumn_union_T
repo.IndexColumn_union_T <.. repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing
repo.IndexColumn_union_T <.. repo.Index_IndexPattern
footer
to view a reduced diagram in original size and to be able to click on the links:
open the diagram in a new tab via the Context menu.
end footer

@enduml

