left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity configT.type << V >> {
  **type** : nvarchar(128)
  --
}

entity docs.RepoObject_OutputFilter << V >> {
  * **RepoObject_guid** : uniqueidentifier
  --
}

entity docs.RepoObject_Plantuml << V >> {
  * **RepoObject_guid** : uniqueidentifier
  --
}

entity property.fs_get_RepoObjectProperty_nvarchar << FN >> {
  --
}

entity reference.Persistence << V >> {
  --
}

entity reference.RepoObject_QueryPlan << U >> {
  * **RepoObject_guid** : uniqueidentifier
  --
}

entity reference.RepoObject_reference_persistence_target_as_source << V >> {
  --
}

entity reference.RepoObject_ReferenceTree_0_30 << V >> {
  **RepoObject_guid** : uniqueidentifier
  **Referencing_guid** : uniqueidentifier
  **Referenced_guid** : uniqueidentifier
  --
}

entity reference.RepoObject_ReferenceTree_30_0 << V >> {
  **RepoObject_guid** : uniqueidentifier
  **Referencing_guid** : uniqueidentifier
  **Referenced_guid** : uniqueidentifier
  --
}

entity reference.RepoObject_ReferenceTree_referenced << V >> {
  **RepoObject_guid** : uniqueidentifier
  **Referenced_Depth** : int
  **Referencing_Depth** : int
  **Referenced_guid** : uniqueidentifier
  **Referencing_guid** : uniqueidentifier
  --
}

entity reference.RepoObject_ReferenceTree_referenced_30_0 << V >> {
  * **RepoObject_guid** : uniqueidentifier
  **Referenced_guid** : uniqueidentifier
  --
}

entity reference.RepoObject_ReferenceTree_referencing << V >> {
  **RepoObject_guid** : uniqueidentifier
  **Referenced_Depth** : int
  **Referencing_Depth** : int
  **Referenced_guid** : uniqueidentifier
  **Referencing_guid** : uniqueidentifier
  --
}

entity reference.RepoObject_ReferenceTree_referencing_0_30 << V >> {
  * **RepoObject_guid** : uniqueidentifier
  **Referencing_guid** : uniqueidentifier
  --
}

entity reference.RepoObject_ReferencingReferenced << V >> {
  * **Referenced_guid** : uniqueidentifier
  * **Referencing_guid** : uniqueidentifier
  --
}

entity reference.usp_RepoObject_update_SysObjectQueryPlan << P >> {
  --
}

entity reference.usp_RepoObjectSource_FirstResultSet << P >> {
  --
}

entity reference.usp_RepoObjectSource_QueryPlan << P >> {
  --
}

entity repo.Index_gross << V >> {
  * **index_guid** : uniqueidentifier
  --
}

entity repo.Index_Settings << U >> {
  * **index_guid** : uniqueidentifier
  --
}

entity repo.Index_virtual_ForUpdate << V >> {
  * **index_guid** : uniqueidentifier
  --
}

entity repo.RepoObject << U >> {
  * **RepoObject_guid** : uniqueidentifier
  --
}

entity repo.RepoObject_gross << V >> {
  * **RepoObject_guid** : uniqueidentifier
  --
}

entity repo.RepoObject_gross2 << V >> {
  --
}

entity repo.RepoObject_persistence << U >> {
  * **target_RepoObject_guid** : uniqueidentifier
  --
}

entity repo.RepoObject_SqlCreateTable << V >> {
  * **RepoObject_guid** : uniqueidentifier
  --
}

entity ssas.model_json_31_tables_T << U >> {
  * **databasename** : nvarchar(128)
  **tables_name** : nvarchar(128)
  --
}

entity ssas.model_json_3161_tables_descriptions_StrAgg << V >> {
  --
}

entity uspgenerator.GeneratorUspStep_Persistence << V >> {
  * **usp_id** : int
  --
}

entity uspgenerator.GeneratorUspStep_Persistence_IsInactive_setpoint << V >> {
  * **usp_id** : int
  --
}

entity uspgenerator.usp_GeneratorUsp_insert_update_persistence << P >> {
  --
}

entity workflow.WorkflowStep_S << V >> {
  * **Workflow_id** : int
  **Procedure_RepoObject_guid** : uniqueidentifier
  --
}

configT.type <.. repo.RepoObject_gross
property.fs_get_RepoObjectProperty_nvarchar <.. repo.RepoObject_gross
reference.RepoObject_QueryPlan <.. repo.RepoObject_gross
reference.RepoObject_ReferencingReferenced <.. repo.RepoObject_gross
repo.Index_Settings <.. repo.RepoObject_gross
repo.RepoObject <.. repo.RepoObject_gross
repo.RepoObject_gross <.. repo.RepoObject_SqlCreateTable
repo.RepoObject_gross <.. uspgenerator.GeneratorUspStep_Persistence_IsInactive_setpoint
repo.RepoObject_gross <.. uspgenerator.GeneratorUspStep_Persistence
repo.RepoObject_gross <.. repo.Index_gross
repo.RepoObject_gross <.. reference.usp_RepoObjectSource_QueryPlan
repo.RepoObject_gross <.. reference.usp_RepoObjectSource_FirstResultSet
repo.RepoObject_gross <.. reference.usp_RepoObject_update_SysObjectQueryPlan
repo.RepoObject_gross <.. uspgenerator.usp_GeneratorUsp_insert_update_persistence
repo.RepoObject_gross <.. docs.RepoObject_OutputFilter
repo.RepoObject_gross <.. docs.RepoObject_Plantuml
repo.RepoObject_gross <.. repo.Index_virtual_ForUpdate
repo.RepoObject_gross <.. reference.RepoObject_ReferenceTree_referenced
repo.RepoObject_gross <.. reference.RepoObject_ReferenceTree_referencing
repo.RepoObject_gross <.. reference.RepoObject_ReferenceTree_referenced_30_0
repo.RepoObject_gross <.. reference.RepoObject_ReferenceTree_referencing_0_30
repo.RepoObject_gross <.. reference.RepoObject_ReferenceTree_0_30
repo.RepoObject_gross <.. reference.RepoObject_ReferenceTree_30_0
repo.RepoObject_gross <.. reference.Persistence
repo.RepoObject_gross <.. reference.RepoObject_reference_persistence_target_as_source
repo.RepoObject_gross <.. workflow.WorkflowStep_S
repo.RepoObject_gross <.. repo.RepoObject_gross2
repo.RepoObject_persistence <.. repo.RepoObject_gross
ssas.model_json_31_tables_T <.. repo.RepoObject_gross
ssas.model_json_3161_tables_descriptions_StrAgg <.. repo.RepoObject_gross
