@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity "[[{site-url}/{page-component-name}/{page-component-version}/{page-module}/docs.fs_cleanStringForAnchorId.html docs.fs_cleanStringForAnchorId]]" as docs.fs_cleanStringForAnchorId << FN >> {
  --
}

entity "[[{site-url}/{page-component-name}/{page-component-version}/{page-module}/docs.RepoObject_IndexList.html docs.RepoObject_IndexList]]" as docs.RepoObject_IndexList << V >> {
  **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "[[{site-url}/{page-component-name}/{page-component-version}/{page-module}/repo.ForeignKey_gross.html repo.ForeignKey_gross]]" as repo.ForeignKey_gross << V >> {
  **ForeignKey_guid** : (uniqueidentifier)
  --
}

entity "[[{site-url}/{page-component-name}/{page-component-version}/{page-module}/repo.ForeignKey_Indexes_union_T.html repo.ForeignKey_Indexes_union_T]]" as repo.ForeignKey_Indexes_union_T << U >> {
  **ForeignKey_guid** : (uniqueidentifier)
  --
}

entity "[[{site-url}/{page-component-name}/{page-component-version}/{page-module}/repo.Index_gross.html repo.Index_gross]]" as repo.Index_gross << V >> {
  - **index_guid** : (uniqueidentifier)
  --
}

docs.fs_cleanStringForAnchorId <.. repo.ForeignKey_gross
repo.ForeignKey_gross <.. docs.RepoObject_IndexList
repo.ForeignKey_Indexes_union_T <.. repo.ForeignKey_gross
repo.Index_gross <.. repo.ForeignKey_gross
footer
to view a reduced diagram in original size and to be able to click on the links:
open the diagram in a new tab via the Context menu.
end footer

@enduml

