left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity config.fs_get_parameter_value << FN >> {
  --
}

entity configT.type_level1type_level2type << V >> {
  **type** : nvarchar(128)
  --
}

entity logs.usp_ExecutionLog_insert << P >> {
  --
}

entity reference.RepoObjectSource_virtual << U >> {
  * **RepoObject_guid** : uniqueidentifier
  * **Source_RepoObject_guid** : uniqueidentifier
  --
}

entity repo.RepoObject << U >> {
  * **RepoObject_guid** : uniqueidentifier
  --
}

entity repo.RepoObject_persistence << U >> {
  * **target_RepoObject_guid** : uniqueidentifier
  --
}

entity repo.RepoObject_RequiredRepoObjectMerge << V >> {
  * **RepoObject_guid** : uniqueidentifier
  --
}

entity repo.SysObject_RepoObject_via_guid << V >> {
  --
}

entity repo.SysObject_RepoObject_via_name << V >> {
  --
}

entity repo.usp_sync_guid << P >> {
  --
}

entity repo.usp_sync_guid_RepoObject << P >> {
  --
}

entity repo_sys.SysObject << V >> {
  --
}

entity repo_sys.usp_AddOrUpdateExtendedProperty << P >> {
  --
}

config.fs_get_parameter_value <.. repo.usp_sync_guid_RepoObject
configT.type_level1type_level2type <.. repo.usp_sync_guid_RepoObject
logs.usp_ExecutionLog_insert <.. repo.usp_sync_guid_RepoObject
reference.RepoObjectSource_virtual <.. repo.usp_sync_guid_RepoObject
repo.RepoObject <.. repo.usp_sync_guid_RepoObject
repo.RepoObject_persistence <.. repo.usp_sync_guid_RepoObject
repo.RepoObject_RequiredRepoObjectMerge <.. repo.usp_sync_guid_RepoObject
repo.SysObject_RepoObject_via_guid <.. repo.usp_sync_guid_RepoObject
repo.SysObject_RepoObject_via_name <.. repo.usp_sync_guid_RepoObject
repo.usp_sync_guid_RepoObject <.. repo.usp_sync_guid
repo_sys.SysObject <.. repo.usp_sync_guid_RepoObject
repo_sys.usp_AddOrUpdateExtendedProperty <.. repo.usp_sync_guid_RepoObject
