@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity "puml-link:docs.AntoraIndexSemanticgroupPatterndatatype.adoc[prefix=..]" as docs.AntoraIndexSemanticgroupPatterndatatype << V >> {
  **IndexSemanticGroup** : (nvarchar(512))
  **IndexPatternColumnDatatype** : (nvarchar(4000))
  --
}

entity "puml-link:docs.RepoObject_IndexList.adoc[prefix=..]" as docs.RepoObject_IndexList << V >> {
  **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:repo.ForeignKey_gross.adoc[prefix=..]" as repo.ForeignKey_gross << V >> {
  **ForeignKey_guid** : (uniqueidentifier)
  --
}

entity "puml-link:repo.ForeignKey_Indexes.adoc[prefix=..]" as repo.ForeignKey_Indexes << V >> {
  **ForeignKey_guid** : (uniqueidentifier)
  --
}

entity "puml-link:repo.ForeignKey_virtual_Indexes.adoc[prefix=..]" as repo.ForeignKey_virtual_Indexes << V >> {
  - **ForeignKey_guid** : (uniqueidentifier)
  --
}

entity "puml-link:repo.Index_ColumList_T.adoc[prefix=..]" as repo.Index_ColumList_T << U >> {
  - **index_guid** : (uniqueidentifier)
  --
}

entity "puml-link:repo.Index_gross.adoc[prefix=..]" as repo.Index_gross << V >> {
  - **index_guid** : (uniqueidentifier)
  --
}

entity "puml-link:repo.Index_Settings.adoc[prefix=..]" as repo.Index_Settings << U >> {
  - **index_guid** : (uniqueidentifier)
  --
}

entity "puml-link:repo.Index_union.adoc[prefix=..]" as repo.Index_union << V >> {
  **index_guid** : (uniqueidentifier)
  --
}

entity "puml-link:repo.RepoObject_gross.adoc[prefix=..]" as repo.RepoObject_gross << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:repo.RepoObject_SqlCreateTable.adoc[prefix=..]" as repo.RepoObject_SqlCreateTable << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:repo.usp_Index_finish.adoc[prefix=..]" as repo.usp_Index_finish << P >> {
  --
}

entity "puml-link:repo.usp_index_inheritance.adoc[prefix=..]" as repo.usp_index_inheritance << P >> {
  --
}

entity "puml-link:repo.usp_Index_virtual_set.adoc[prefix=..]" as repo.usp_Index_virtual_set << P >> {
  --
}

repo.Index_ColumList_T <.. repo.Index_gross
repo.Index_gross <.. repo.usp_Index_virtual_set
repo.Index_gross <.. repo.RepoObject_SqlCreateTable
repo.Index_gross <.. repo.usp_index_inheritance
repo.Index_gross <.. repo.ForeignKey_Indexes
repo.Index_gross <.. repo.ForeignKey_virtual_Indexes
repo.Index_gross <.. repo.usp_Index_finish
repo.Index_gross <.. docs.RepoObject_IndexList
repo.Index_gross <.. docs.AntoraIndexSemanticgroupPatterndatatype
repo.Index_gross <.. repo.ForeignKey_gross
repo.Index_Settings <.. repo.Index_gross
repo.Index_union <.. repo.Index_gross
repo.RepoObject_gross <.. repo.Index_gross
footer
to view a reduced diagram in original size and to be able to click on the links:
open the diagram in a new tab via the Context menu.
end footer

@enduml

