@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity "[[{site-url}/{page-component-name}/current/{page-module}/reference.RepoObjectColumn_reference_SqlModules.html reference.RepoObjectColumn_reference_SqlModules]]" as reference.RepoObjectColumn_reference_SqlModules << V >> {
  **referencing_id** : (int)
  **referencing_minor_id** : (int)
  **referenced_id** : (int)
  **referenced_minor_id** : (int)
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/sqlparse.RepoObject_SqlModules_71_reference_ExpliciteTableAlias.html sqlparse.RepoObject_SqlModules_71_reference_ExpliciteTableAlias]]" as sqlparse.RepoObject_SqlModules_71_reference_ExpliciteTableAlias << V >> {
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/sqlparse.RepoObject_SqlModules_72_reference_NoTableAlias.html sqlparse.RepoObject_SqlModules_72_reference_NoTableAlias]]" as sqlparse.RepoObject_SqlModules_72_reference_NoTableAlias << V >> {
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/sqlparse.RepoObject_SqlModules_79_reference_union.html sqlparse.RepoObject_SqlModules_79_reference_union]]" as sqlparse.RepoObject_SqlModules_79_reference_union << V >> {
  --
}

sqlparse.RepoObject_SqlModules_71_reference_ExpliciteTableAlias <.. sqlparse.RepoObject_SqlModules_79_reference_union
sqlparse.RepoObject_SqlModules_72_reference_NoTableAlias <.. sqlparse.RepoObject_SqlModules_79_reference_union
sqlparse.RepoObject_SqlModules_79_reference_union <.. reference.RepoObjectColumn_reference_SqlModules
footer
to view a reduced diagram in original size and to be able to click on the links:
open the diagram in a new tab via the Context menu.
end footer

@enduml

