@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssas.model_json_313211_tables_partitions_posdot.adoc[]" as ssas.model_json_313211_tables_partitions_PosDot << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_3132111_tables_partitions_part123.adoc[]" as ssas.model_json_3132111_tables_partitions_Part123 << V >> {
  --
}

ssas.model_json_313211_tables_partitions_PosDot <.. ssas.model_json_3132111_tables_partitions_Part123footer The diagram is interactive and contains links.
@enduml

