@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis.usp_import.adoc[]" as ssis.usp_import << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_package_tgt.adoc[]" as ssis.usp_PERSIST_Package_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packageconnection_tgt.adoc[]" as ssis.usp_PERSIST_PackageConnection_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packageflow_tgt.adoc[]" as ssis.usp_PERSIST_PackageFlow_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packageparameter_tgt.adoc[]" as ssis.usp_PERSIST_PackageParameter_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packagetask_dft_component_input_externalmetadatacolumn_tgt.adoc[]" as ssis.usp_PERSIST_PackageTask_Dft_Component_input_externalMetadataColumn_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packagetask_dft_component_input_inputcolumn_tgt.adoc[]" as ssis.usp_PERSIST_PackageTask_Dft_Component_input_inputColumn_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packagetask_dft_component_input_tgt.adoc[]" as ssis.usp_PERSIST_PackageTask_Dft_Component_input_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packagetask_dft_component_output_externalmetadatacolumn_tgt.adoc[]" as ssis.usp_PERSIST_PackageTask_Dft_Component_output_externalMetadataColumn_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packagetask_dft_component_output_outputcolumn_tgt.adoc[]" as ssis.usp_PERSIST_PackageTask_Dft_Component_output_outputColumn_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packagetask_dft_component_output_tgt.adoc[]" as ssis.usp_PERSIST_PackageTask_Dft_Component_output_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packagetask_dft_component_tgt.adoc[]" as ssis.usp_PERSIST_PackageTask_Dft_Component_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packagetask_sql_parameter_tgt.adoc[]" as ssis.usp_PERSIST_PackageTask_Sql_Parameter_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packagetask_tgt.adoc[]" as ssis.usp_PERSIST_PackageTask_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packagevariable_tgt.adoc[]" as ssis.usp_PERSIST_PackageVariable_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_projectconnection_tgt.adoc[]" as ssis.usp_PERSIST_ProjectConnection_tgt << P >> {
  --
}

ssis.usp_PERSIST_Package_tgt <.. ssis.usp_import
ssis.usp_PERSIST_PackageConnection_tgt <.. ssis.usp_import
ssis.usp_PERSIST_PackageFlow_tgt <.. ssis.usp_import
ssis.usp_PERSIST_PackageParameter_tgt <.. ssis.usp_import
ssis.usp_PERSIST_PackageTask_Dft_Component_input_externalMetadataColumn_tgt <.. ssis.usp_import
ssis.usp_PERSIST_PackageTask_Dft_Component_input_inputColumn_tgt <.. ssis.usp_import
ssis.usp_PERSIST_PackageTask_Dft_Component_input_tgt <.. ssis.usp_import
ssis.usp_PERSIST_PackageTask_Dft_Component_output_externalMetadataColumn_tgt <.. ssis.usp_import
ssis.usp_PERSIST_PackageTask_Dft_Component_output_outputColumn_tgt <.. ssis.usp_import
ssis.usp_PERSIST_PackageTask_Dft_Component_output_tgt <.. ssis.usp_import
ssis.usp_PERSIST_PackageTask_Dft_Component_tgt <.. ssis.usp_import
ssis.usp_PERSIST_PackageTask_Sql_Parameter_tgt <.. ssis.usp_import
ssis.usp_PERSIST_PackageTask_tgt <.. ssis.usp_import
ssis.usp_PERSIST_PackageVariable_tgt <.. ssis.usp_import
ssis.usp_PERSIST_ProjectConnection_tgt <.. ssis.usp_importfooter The diagram is interactive and contains links.
@enduml

