@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity "[[{site-url}/{page-component-name}/{page-component-version}/{page-module}/repo_sys.ExtendedProperties.html repo_sys.ExtendedProperties]]" as repo_sys.ExtendedProperties << V >> {
  --
}

entity "[[{site-url}/{page-component-name}/{page-component-version}/{page-module}/repo_sys.Index_unique.html repo_sys.Index_unique]]" as repo_sys.Index_unique << V >> {
  --
}

entity "[[{site-url}/{page-component-name}/{page-component-version}/{page-module}/repo_sys.IndexColumn_unique.html repo_sys.IndexColumn_unique]]" as repo_sys.IndexColumn_unique << V >> {
  --
}

entity "[[{site-url}/{page-component-name}/{page-component-version}/{page-module}/sys_dwh.indexes.html sys_dwh.indexes]]" as sys_dwh.indexes << SN >> {
  --
}

sys_dwh.indexes <.. repo_sys.Index_unique
sys_dwh.indexes <.. repo_sys.ExtendedProperties
sys_dwh.indexes <.. repo_sys.IndexColumn_unique
footer
to view a reduced diagram in original size and to be able to click on the links:
open the diagram in a new tab via the Context menu.
end footer

@enduml

