left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity repo.RepoObject_gross << V >> {
  * **RepoObject_guid** : uniqueidentifier
  --
}

entity workflow.usp_PERSIST_WorkflowStep << P >> {
  --
}

entity workflow.Workflow << U >> {
  * **id** : int
  --
}

entity workflow.WorkflowStep << U >> {
  * **id** : int
  --
}

entity workflow.WorkflowStep_S << V >> {
  * **Workflow_id** : int
  **Procedure_RepoObject_guid** : uniqueidentifier
  --
}

repo.RepoObject_gross <.. workflow.WorkflowStep_S
workflow.Workflow <.. workflow.WorkflowStep_S
workflow.WorkflowStep_S <.. workflow.WorkflowStep
workflow.WorkflowStep_S <.. workflow.usp_PERSIST_WorkflowStep
