left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity workflow.Biml_Package << V >> {
  --
}

entity workflow.Workflow << U >> {
  * **id** : int
  --
}

entity workflow.Workflow_ProcedureDependency << V >> {
  --
}

entity workflow.Workflow_ProcedureDependency_all << V >> {
  --
}

entity workflow.Workflow_UspList << V >> {
  --
}

entity workflow.WorkflowStep_active << V >> {
  --
}

entity workflow.WorkflowStep_ForUpdate << V >> {
  --
}

entity workflow.WorkflowStep_S << V >> {
  * **Workflow_id** : int
  **Procedure_RepoObject_guid** : uniqueidentifier
  --
}

workflow.Workflow <.. workflow.WorkflowStep_active
workflow.Workflow <.. workflow.Workflow_ProcedureDependency
workflow.Workflow <.. workflow.Workflow_UspList
workflow.Workflow <.. workflow.WorkflowStep_S
workflow.Workflow <.. workflow.Workflow_ProcedureDependency_all
workflow.Workflow <.. workflow.WorkflowStep_ForUpdate
workflow.Workflow <.. workflow.Biml_Package
