'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity "[[{site-url}/{page-component-name}/{page-component-version}/{page-module}/ssas.model_json_3141_tables_hierarchies_levels.html ssas.model_json_3141_tables_hierarchies_levels]]" as ssas.model_json_3141_tables_hierarchies_levels << V >> {
  - **databasename** : (nvarchar(128))
  **tables_name** : (nvarchar(500))
  **tables_hierarchies_name** : (nvarchar(500))
  **tables_hierarchies_levels_name** : (nvarchar(500))
  --
}

