@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:dbeaver.datasources.adoc[]" as dbeaver.DataSources << U >> {
  - **id** : (int)
  --
}

entity "puml-link:dhw:sqldb:dbeaver.datasources_dbschematable.adoc[]" as dbeaver.DataSources_DbSchemaTable << V >> {
  --
}

entity "puml-link:dhw:sqldb:dbeaver.datasources_dbschematable_constraint.adoc[]" as dbeaver.DataSources_DbSchemaTable_constraint << V >> {
  --
}

dbeaver.DataSources <.. dbeaver.DataSources_DbSchemaTable
dbeaver.DataSources_DbSchemaTable <.. dbeaver.DataSources_DbSchemaTable_constraintfooter The diagram is interactive and contains links.
@enduml

