'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity config.Parameter << U >> {
  * **Parameter_name** : varchar(100)
  * **sub_Parameter** : nvarchar(128)
  --
}

entity property.PropertyName_RepoObjectColumn << V >> {
  * **property_name** : nvarchar(128)
  --
}

entity property.RepoObjectColumnProperty << U >> {
  * **RepoObjectColumnProperty_id** : int
  --
}

entity property.RepoObjectColumnProperty_InheritanceType_InheritanceDefinition << V >> {
  * **RepoObjectColumn_guid** : uniqueidentifier
  * **property_name** : nvarchar(128)
  --
}

entity property.RepoObjectColumnProperty_InheritanceType_resulting_InheritanceDefinition << V >> {
  * **RepoObjectColumn_guid** : uniqueidentifier
  * **property_name** : nvarchar(128)
  --
}

entity repo.RepoObject << U >> {
  * **RepoObject_guid** : uniqueidentifier
  --
}

entity repo.RepoObject_SSAS_src << V >> {
  * **RepoObject_guid** : uniqueidentifier
  --
}

entity repo.RepoObject_SSAS_tgt << V >> {
  * **RepoObject_guid** : uniqueidentifier
  --
}

entity repo.RepoObjectColumn << U >> {
  * **RepoObjectColumn_guid** : uniqueidentifier
  --
}

entity repo.RepoObjectColumn_SSAS_src << V >> {
  * **RepoObjectColumn_guid** : uniqueidentifier
  --
}

entity repo.RepoObjectColumn_SSAS_tgt << V >> {
  * **RepoObjectColumn_guid** : uniqueidentifier
  --
}

entity ssas.model_json << U >> {
  * **databasename** : nvarchar(128)
  --
}

entity ssas.model_json_10 << V >> {
  * **databasename** : nvarchar(128)
  --
}

entity ssas.model_json_20 << V >> {
  * **databasename** : nvarchar(128)
  --
}

entity ssas.model_json_31_tables << V >> {
  * **databasename** : nvarchar(128)
  **tables_name** : nvarchar(128)
  --
}

entity ssas.model_json_31_tables_T << U >> {
  * **databasename** : nvarchar(128)
  **tables_name** : nvarchar(128)
  --
}

entity ssas.model_json_311_tables_columns << V >> {
  * **databasename** : nvarchar(128)
  * **tables_name** : nvarchar(128)
  **tables_columns_name** : nvarchar(128)
  --
}

entity ssas.model_json_311_tables_columns_T << U >> {
  * **databasename** : nvarchar(128)
  * **tables_name** : nvarchar(128)
  **tables_columns_name** : nvarchar(128)
  --
}

config.Parameter <.. property.PropertyName_RepoObjectColumn
config.Parameter <.. property.RepoObjectColumnProperty_InheritanceType_InheritanceDefinition
property.PropertyName_RepoObjectColumn <.. property.RepoObjectColumnProperty_InheritanceType_InheritanceDefinition
property.RepoObjectColumnProperty <.. property.RepoObjectColumnProperty_InheritanceType_InheritanceDefinition
property.RepoObjectColumnProperty <.. property.PropertyName_RepoObjectColumn
property.RepoObjectColumnProperty_InheritanceType_InheritanceDefinition <.. property.RepoObjectColumnProperty_InheritanceType_resulting_InheritanceDefinition
repo.RepoObject <.. repo.RepoObject_SSAS_tgt
repo.RepoObject_SSAS_src <.. repo.RepoObject_SSAS_tgt
repo.RepoObject_SSAS_tgt <.. repo.RepoObject
repo.RepoObject_SSAS_tgt <.. repo.RepoObjectColumn_SSAS_tgt
repo.RepoObjectColumn <.. repo.RepoObjectColumn_SSAS_tgt
repo.RepoObjectColumn <.. property.RepoObjectColumnProperty_InheritanceType_InheritanceDefinition
repo.RepoObjectColumn_SSAS_src <.. repo.RepoObjectColumn_SSAS_tgt
repo.RepoObjectColumn_SSAS_tgt <.. repo.RepoObjectColumn
repo.RepoObjectColumn_SSAS_tgt <.. repo.RepoObject_SSAS_tgt
ssas.model_json <.. ssas.model_json_10
ssas.model_json_10 <.. ssas.model_json_20
ssas.model_json_20 <.. ssas.model_json_31_tables
ssas.model_json_31_tables <.. ssas.model_json_31_tables_T
ssas.model_json_31_tables_T <.. ssas.model_json_311_tables_columns
ssas.model_json_31_tables_T <.. repo.RepoObject_SSAS_src
ssas.model_json_311_tables_columns <.. ssas.model_json_311_tables_columns_T
ssas.model_json_311_tables_columns_T <.. repo.RepoObjectColumn_SSAS_src
