@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity "puml-link:config.ftv_dwh_database.adoc[prefix=..]" as config.ftv_dwh_database << IF >> {
  --
}

entity "puml-link:config.Parameter.adoc[prefix=..]" as config.Parameter << U >> {
  - **Parameter_name** : (varchar(100))
  - **sub_Parameter** : (nvarchar(128))
  --
}

entity "puml-link:configT.spt_values.adoc[prefix=..]" as configT.spt_values << U >> {
  --
}

entity "puml-link:configT.type.adoc[prefix=..]" as configT.type << V >> {
  **type** : (nvarchar(128))
  --
}

entity "puml-link:configT.type_level1type_level2type.adoc[prefix=..]" as configT.type_level1type_level2type << V >> {
  **type** : (nvarchar(128))
  --
}

entity "puml-link:logs.ExecutionLog.adoc[prefix=..]" as logs.ExecutionLog << U >> {
  --
}

entity "puml-link:logs.usp_ExecutionLog_insert.adoc[prefix=..]" as logs.usp_ExecutionLog_insert << P >> {
  --
}

entity "puml-link:property.ExtendedProperty_Repo2Sys_level0.adoc[prefix=..]" as property.ExtendedProperty_Repo2Sys_level0 << V >> {
  --
}

entity "puml-link:property.ExtendedProperty_Repo2Sys_level1.adoc[prefix=..]" as property.ExtendedProperty_Repo2Sys_level1 << V >> {
  - **level0type** : (nvarchar(6))
  - **level0name** : (nvarchar(128))
  **level1type** : (varchar(9))
  - **level1name** : (nvarchar(128))
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:property.ExtendedProperty_Repo2Sys_level2_RepoObject.adoc[prefix=..]" as property.ExtendedProperty_Repo2Sys_level2_RepoObject << V >> {
  - **level0type** : (nvarchar(6))
  - **level0name** : (nvarchar(128))
  **level1type** : (varchar(9))
  - **level1name** : (nvarchar(128))
  **level2type** : (varchar(10))
  - **level2name** : (nvarchar(128))
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:property.ExtendedProperty_Repo2Sys_level2_RepoObjectColumn.adoc[prefix=..]" as property.ExtendedProperty_Repo2Sys_level2_RepoObjectColumn << V >> {
  - **level0type** : (nvarchar(6))
  - **level0name** : (nvarchar(128))
  **level1type** : (varchar(9))
  - **level1name** : (nvarchar(128))
  - **level2type** : (nvarchar(6))
  - **level2name** : (nvarchar(128))
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:property.ExtendedProperty_Repo2Sys_level2_Union.adoc[prefix=..]" as property.ExtendedProperty_Repo2Sys_level2_Union << V >> {
  - **level0type** : (nvarchar(6))
  - **level0name** : (nvarchar(128))
  **level1type** : (varchar(9))
  - **level1name** : (nvarchar(128))
  **level2type** : (nvarchar(10))
  - **level2name** : (nvarchar(128))
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:property.RepoObjectColumnProperty.adoc[prefix=..]" as property.RepoObjectColumnProperty << U >> {
  - **RepoObjectColumnProperty_id** : (int)
  --
}

entity "puml-link:property.RepoObjectProperty.adoc[prefix=..]" as property.RepoObjectProperty << U >> {
  - **RepoObjectProperty_id** : (int)
  --
}

entity "puml-link:property.usp_sync_ExtendedProperties_Repo2Sys_Delete.adoc[prefix=..]" as property.usp_sync_ExtendedProperties_Repo2Sys_Delete << P >> {
  --
}

entity "puml-link:repo.RepoObject.adoc[prefix=..]" as repo.RepoObject << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:repo.RepoObject_SSAS_src.adoc[prefix=..]" as repo.RepoObject_SSAS_src << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:repo.RepoObject_SSAS_tgt.adoc[prefix=..]" as repo.RepoObject_SSAS_tgt << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:repo.RepoObjectColumn.adoc[prefix=..]" as repo.RepoObjectColumn << U >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  --
}

entity "puml-link:repo.RepoObjectColumn_SSAS_src.adoc[prefix=..]" as repo.RepoObjectColumn_SSAS_src << V >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  --
}

entity "puml-link:repo.RepoObjectColumn_SSAS_tgt.adoc[prefix=..]" as repo.RepoObjectColumn_SSAS_tgt << V >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  --
}

entity "puml-link:repo.RepoSchema.adoc[prefix=..]" as repo.RepoSchema << U >> {
  - **RepoSchema_guid** : (uniqueidentifier)
  --
}

entity "puml-link:repo.RepoSchema_ssas_src.adoc[prefix=..]" as repo.RepoSchema_ssas_src << V >> {
  - **RepoSchema_name** : (nvarchar(128))
  --
}

entity "puml-link:repo.RepoSchema_ssas_tgt.adoc[prefix=..]" as repo.RepoSchema_ssas_tgt << V >> {
  - **RepoSchema_name** : (nvarchar(128))
  --
}

entity "puml-link:repo_sys.ExtendedProperties.adoc[prefix=..]" as repo_sys.ExtendedProperties << V >> {
  --
}

entity "puml-link:repo_sys.ExtendedProperties_ParameterForAddUpdateDrop.adoc[prefix=..]" as repo_sys.ExtendedProperties_ParameterForAddUpdateDrop << V >> {
  --
}

entity "puml-link:ssas.model_json.adoc[prefix=..]" as ssas.model_json << U >> {
  - **databasename** : (nvarchar(128))
  --
}

entity "puml-link:ssas.model_json_10.adoc[prefix=..]" as ssas.model_json_10 << V >> {
  - **databasename** : (nvarchar(128))
  --
}

entity "puml-link:ssas.model_json_20.adoc[prefix=..]" as ssas.model_json_20 << V >> {
  - **databasename** : (nvarchar(128))
  --
}

entity "puml-link:ssas.model_json_201_descriptions_multiline.adoc[prefix=..]" as ssas.model_json_201_descriptions_multiline << V >> {
  --
}

entity "puml-link:ssas.model_json_2011_descriptions_StrAgg.adoc[prefix=..]" as ssas.model_json_2011_descriptions_StrAgg << V >> {
  --
}

entity "puml-link:ssas.model_json_31_tables.adoc[prefix=..]" as ssas.model_json_31_tables << V >> {
  - **databasename** : (nvarchar(128))
  **tables_name** : (nvarchar(128))
  --
}

entity "puml-link:ssas.model_json_31_tables_T.adoc[prefix=..]" as ssas.model_json_31_tables_T << U >> {
  - **databasename** : (nvarchar(128))
  **tables_name** : (nvarchar(128))
  --
}

entity "puml-link:ssas.model_json_311_tables_columns.adoc[prefix=..]" as ssas.model_json_311_tables_columns << V >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  **tables_columns_name** : (nvarchar(128))
  --
}

entity "puml-link:ssas.model_json_311_tables_columns_T.adoc[prefix=..]" as ssas.model_json_311_tables_columns_T << U >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  **tables_columns_name** : (nvarchar(128))
  --
}

entity "puml-link:sys_dwh.columns.adoc[prefix=..]" as sys_dwh.columns << SN >> {
  --
}

entity "puml-link:sys_dwh.extended_properties.adoc[prefix=..]" as sys_dwh.extended_properties << SN >> {
  --
}

entity "puml-link:sys_dwh.indexes.adoc[prefix=..]" as sys_dwh.indexes << SN >> {
  --
}

entity "puml-link:sys_dwh.objects.adoc[prefix=..]" as sys_dwh.objects << SN >> {
  --
}

entity "puml-link:sys_dwh.parameters.adoc[prefix=..]" as sys_dwh.parameters << SN >> {
  --
}

entity "puml-link:sys_dwh.schemas.adoc[prefix=..]" as sys_dwh.schemas << SN >> {
  --
}

config.ftv_dwh_database <.. repo_sys.ExtendedProperties
config.Parameter <.. config.ftv_dwh_database
configT.spt_values <.. configT.type
configT.spt_values <.. configT.type
configT.type <.. configT.type_level1type_level2type
configT.type <.. configT.type_level1type_level2type
configT.type_level1type_level2type <.. property.ExtendedProperty_Repo2Sys_level2_RepoObject
configT.type_level1type_level2type <.. property.ExtendedProperty_Repo2Sys_level2_RepoObjectColumn
configT.type_level1type_level2type <.. repo_sys.ExtendedProperties_ParameterForAddUpdateDrop
configT.type_level1type_level2type <.. property.ExtendedProperty_Repo2Sys_level1
logs.ExecutionLog <.. logs.usp_ExecutionLog_insert
logs.usp_ExecutionLog_insert <.. property.usp_sync_ExtendedProperties_Repo2Sys_Delete
property.ExtendedProperty_Repo2Sys_level0 <.. property.usp_sync_ExtendedProperties_Repo2Sys_Delete
property.ExtendedProperty_Repo2Sys_level1 <.. property.usp_sync_ExtendedProperties_Repo2Sys_Delete
property.ExtendedProperty_Repo2Sys_level2_RepoObject <.. property.ExtendedProperty_Repo2Sys_level2_Union
property.ExtendedProperty_Repo2Sys_level2_RepoObjectColumn <.. property.ExtendedProperty_Repo2Sys_level2_Union
property.ExtendedProperty_Repo2Sys_level2_Union <.. property.usp_sync_ExtendedProperties_Repo2Sys_Delete
property.RepoObjectColumnProperty <.. property.ExtendedProperty_Repo2Sys_level2_RepoObjectColumn
property.RepoObjectProperty <.. property.ExtendedProperty_Repo2Sys_level2_RepoObject
property.RepoObjectProperty <.. property.ExtendedProperty_Repo2Sys_level1
repo.RepoObject <.. property.ExtendedProperty_Repo2Sys_level1
repo.RepoObject <.. property.ExtendedProperty_Repo2Sys_level2_RepoObject
repo.RepoObject <.. property.ExtendedProperty_Repo2Sys_level2_RepoObjectColumn
repo.RepoObject <.. repo.RepoObject_SSAS_tgt
repo.RepoObject_SSAS_src <.. repo.RepoObject_SSAS_tgt
repo.RepoObject_SSAS_tgt <.. repo.RepoObject
repo.RepoObject_SSAS_tgt <.. repo.RepoObjectColumn_SSAS_tgt
repo.RepoObject_SSAS_tgt <.. repo.RepoObjectColumn_SSAS_tgt
repo.RepoObjectColumn <.. repo.RepoObjectColumn_SSAS_tgt
repo.RepoObjectColumn <.. repo.RepoObjectColumn_SSAS_tgt
repo.RepoObjectColumn <.. property.ExtendedProperty_Repo2Sys_level2_RepoObjectColumn
repo.RepoObjectColumn_SSAS_src <.. repo.RepoObjectColumn_SSAS_tgt
repo.RepoObjectColumn_SSAS_src <.. repo.RepoObjectColumn_SSAS_tgt
repo.RepoObjectColumn_SSAS_tgt <.. repo.RepoObjectColumn
repo.RepoObjectColumn_SSAS_tgt <.. repo.RepoObject_SSAS_tgt
repo.RepoSchema <.. repo.RepoSchema_ssas_tgt
repo.RepoSchema <.. property.ExtendedProperty_Repo2Sys_level0
repo.RepoSchema_ssas_src <.. repo.RepoSchema_ssas_tgt
repo.RepoSchema_ssas_tgt <.. repo.RepoSchema
repo_sys.ExtendedProperties <.. repo_sys.ExtendedProperties_ParameterForAddUpdateDrop
repo_sys.ExtendedProperties_ParameterForAddUpdateDrop <.. property.usp_sync_ExtendedProperties_Repo2Sys_Delete
ssas.model_json <.. ssas.model_json_10
ssas.model_json_10 <.. ssas.model_json_20
ssas.model_json_20 <.. repo.RepoSchema_ssas_src
ssas.model_json_20 <.. ssas.model_json_31_tables
ssas.model_json_20 <.. ssas.model_json_201_descriptions_multiline
ssas.model_json_201_descriptions_multiline <.. ssas.model_json_2011_descriptions_StrAgg
ssas.model_json_2011_descriptions_StrAgg <.. repo.RepoSchema_ssas_src
ssas.model_json_31_tables <.. ssas.model_json_31_tables_T
ssas.model_json_31_tables_T <.. repo.RepoObject_SSAS_src
ssas.model_json_31_tables_T <.. ssas.model_json_311_tables_columns
ssas.model_json_31_tables_T <.. ssas.model_json_311_tables_columns
ssas.model_json_311_tables_columns <.. ssas.model_json_311_tables_columns_T
ssas.model_json_311_tables_columns <.. ssas.model_json_311_tables_columns_T
ssas.model_json_311_tables_columns_T <.. repo.RepoObjectColumn_SSAS_src
ssas.model_json_311_tables_columns_T <.. repo.RepoObjectColumn_SSAS_src
sys_dwh.columns <.. repo_sys.ExtendedProperties
sys_dwh.extended_properties <.. repo_sys.ExtendedProperties
sys_dwh.indexes <.. repo_sys.ExtendedProperties
sys_dwh.objects <.. repo_sys.ExtendedProperties
sys_dwh.objects <.. repo_sys.ExtendedProperties_ParameterForAddUpdateDrop
sys_dwh.parameters <.. repo_sys.ExtendedProperties
sys_dwh.schemas <.. repo_sys.ExtendedProperties
footer
to view a reduced diagram in original size and to be able to click on the links:
open the diagram in a new tab via the Context menu.
end footer

@enduml

