@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity "puml-link:config.fs_get_parameter_value.adoc[prefix=..]" as config.fs_get_parameter_value << FN >> {
  --
}

entity "puml-link:config.ftv_dwh_database.adoc[prefix=..]" as config.ftv_dwh_database << IF >> {
  --
}

entity "puml-link:config.Parameter.adoc[prefix=..]" as config.Parameter << U >> {
  - **Parameter_name** : (varchar(100))
  - **sub_Parameter** : (nvarchar(128))
  --
}

entity "puml-link:configT.spt_values.adoc[prefix=..]" as configT.spt_values << U >> {
  --
}

entity "puml-link:configT.type.adoc[prefix=..]" as configT.type << V >> {
  **type** : (nvarchar(128))
  --
}

entity "puml-link:logs.ExecutionLog.adoc[prefix=..]" as logs.ExecutionLog << U >> {
  --
}

entity "puml-link:logs.usp_ExecutionLog_insert.adoc[prefix=..]" as logs.usp_ExecutionLog_insert << P >> {
  --
}

entity "puml-link:property.fs_get_RepoObjectProperty_nvarchar.adoc[prefix=..]" as property.fs_get_RepoObjectProperty_nvarchar << FN >> {
  --
}

entity "puml-link:property.RepoObjectProperty.adoc[prefix=..]" as property.RepoObjectProperty << U >> {
  - **RepoObjectProperty_id** : (int)
  --
}

entity "puml-link:reference.additional_Reference.adoc[prefix=..]" as reference.additional_Reference << U >> {
  - **Id** : (int)
  --
}

entity "puml-link:reference.additional_Reference_guid.adoc[prefix=..]" as reference.additional_Reference_guid << V >> {
  --
}

entity "puml-link:reference.RepoObject_QueryPlan.adoc[prefix=..]" as reference.RepoObject_QueryPlan << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:reference.RepoObject_reference.adoc[prefix=..]" as reference.RepoObject_reference << V >> {
  **referenced_RepoObject_guid** : (uniqueidentifier)
  **referencing_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:reference.RepoObject_reference_additional_internal.adoc[prefix=..]" as reference.RepoObject_reference_additional_internal << V >> {
  --
}

entity "puml-link:reference.RepoObject_reference_persistence.adoc[prefix=..]" as reference.RepoObject_reference_persistence << V >> {
  **referenced_RepoObject_guid** : (uniqueidentifier)
  - **referencing_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:reference.RepoObject_reference_persistence_target_as_source.adoc[prefix=..]" as reference.RepoObject_reference_persistence_target_as_source << V >> {
  --
}

entity "puml-link:reference.RepoObject_reference_SqlExpressionDependencies.adoc[prefix=..]" as reference.RepoObject_reference_SqlExpressionDependencies << V >> {
  **referenced_RepoObject_guid** : (uniqueidentifier)
  **referencing_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:reference.RepoObject_reference_T.adoc[prefix=..]" as reference.RepoObject_reference_T << U >> {
  **referenced_RepoObject_guid** : (uniqueidentifier)
  **referencing_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:reference.RepoObject_reference_union.adoc[prefix=..]" as reference.RepoObject_reference_union << V >> {
  **referenced_RepoObject_guid** : (uniqueidentifier)
  **referencing_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:reference.RepoObject_reference_virtual.adoc[prefix=..]" as reference.RepoObject_reference_virtual << V >> {
  --
}

entity "puml-link:reference.RepoObject_ReferencingReferenced.adoc[prefix=..]" as reference.RepoObject_ReferencingReferenced << V >> {
  - **Referenced_guid** : (uniqueidentifier)
  - **Referencing_guid** : (uniqueidentifier)
  --
}

entity "puml-link:reference.RepoObjectSource_FirstResultSet.adoc[prefix=..]" as reference.RepoObjectSource_FirstResultSet << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **column_ordinal** : (int)
  --
}

entity "puml-link:reference.RepoObjectSource_virtual.adoc[prefix=..]" as reference.RepoObjectSource_virtual << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **Source_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:reference.usp_RepoObjectSource_FirstResultSet.adoc[prefix=..]" as reference.usp_RepoObjectSource_FirstResultSet << P >> {
  --
}

entity "puml-link:repo.Index_Settings.adoc[prefix=..]" as repo.Index_Settings << U >> {
  - **index_guid** : (uniqueidentifier)
  --
}

entity "puml-link:repo.RepoObject.adoc[prefix=..]" as repo.RepoObject << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:repo.RepoObject_gross.adoc[prefix=..]" as repo.RepoObject_gross << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:repo.RepoObject_persistence.adoc[prefix=..]" as repo.RepoObject_persistence << U >> {
  - **target_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:repo.RepoObject_SSAS_src.adoc[prefix=..]" as repo.RepoObject_SSAS_src << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:repo.RepoObject_SSAS_tgt.adoc[prefix=..]" as repo.RepoObject_SSAS_tgt << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:repo.RepoObjectColumn.adoc[prefix=..]" as repo.RepoObjectColumn << U >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  --
}

entity "puml-link:repo.RepoObjectColumn_SSAS_src.adoc[prefix=..]" as repo.RepoObjectColumn_SSAS_src << V >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  --
}

entity "puml-link:repo.RepoObjectColumn_SSAS_tgt.adoc[prefix=..]" as repo.RepoObjectColumn_SSAS_tgt << V >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  --
}

entity "puml-link:repo.SysColumn_RepoObjectColumn_via_name.adoc[prefix=..]" as repo.SysColumn_RepoObjectColumn_via_name << V >> {
  --
}

entity "puml-link:repo.SysObject_RepoObject_via_name.adoc[prefix=..]" as repo.SysObject_RepoObject_via_name << V >> {
  --
}

entity "puml-link:repo_sys.ExtendedProperties.adoc[prefix=..]" as repo_sys.ExtendedProperties << V >> {
  --
}

entity "puml-link:repo_sys.sql_expression_dependencies.adoc[prefix=..]" as repo_sys.sql_expression_dependencies << V >> {
  --
}

entity "puml-link:repo_sys.SysColumn.adoc[prefix=..]" as repo_sys.SysColumn << V >> {
  --
}

entity "puml-link:repo_sys.SysObject.adoc[prefix=..]" as repo_sys.SysObject << V >> {
  --
}

entity "puml-link:ssas.model_json.adoc[prefix=..]" as ssas.model_json << U >> {
  - **databasename** : (nvarchar(128))
  --
}

entity "puml-link:ssas.model_json_10.adoc[prefix=..]" as ssas.model_json_10 << V >> {
  - **databasename** : (nvarchar(128))
  --
}

entity "puml-link:ssas.model_json_20.adoc[prefix=..]" as ssas.model_json_20 << V >> {
  - **databasename** : (nvarchar(128))
  --
}

entity "puml-link:ssas.model_json_31_tables.adoc[prefix=..]" as ssas.model_json_31_tables << V >> {
  - **databasename** : (nvarchar(128))
  **tables_name** : (nvarchar(128))
  --
}

entity "puml-link:ssas.model_json_31_tables_T.adoc[prefix=..]" as ssas.model_json_31_tables_T << U >> {
  - **databasename** : (nvarchar(128))
  **tables_name** : (nvarchar(128))
  --
}

entity "puml-link:ssas.model_json_311_tables_columns.adoc[prefix=..]" as ssas.model_json_311_tables_columns << V >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  **tables_columns_name** : (nvarchar(128))
  --
}

entity "puml-link:ssas.model_json_311_tables_columns_T.adoc[prefix=..]" as ssas.model_json_311_tables_columns_T << U >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  **tables_columns_name** : (nvarchar(128))
  --
}

entity "puml-link:ssas.model_json_316_tables_descriptions_multiline.adoc[prefix=..]" as ssas.model_json_316_tables_descriptions_multiline << V >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  --
}

entity "puml-link:ssas.model_json_3161_tables_descriptions_StrAgg.adoc[prefix=..]" as ssas.model_json_3161_tables_descriptions_StrAgg << V >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  --
}

entity "puml-link:sys_dwh.columns.adoc[prefix=..]" as sys_dwh.columns << SN >> {
  --
}

entity "puml-link:sys_dwh.computed_columns.adoc[prefix=..]" as sys_dwh.computed_columns << SN >> {
  --
}

entity "puml-link:sys_dwh.default_constraints.adoc[prefix=..]" as sys_dwh.default_constraints << SN >> {
  --
}

entity "puml-link:sys_dwh.extended_properties.adoc[prefix=..]" as sys_dwh.extended_properties << SN >> {
  --
}

entity "puml-link:sys_dwh.identity_columns.adoc[prefix=..]" as sys_dwh.identity_columns << SN >> {
  --
}

entity "puml-link:sys_dwh.indexes.adoc[prefix=..]" as sys_dwh.indexes << SN >> {
  --
}

entity "puml-link:sys_dwh.objects.adoc[prefix=..]" as sys_dwh.objects << SN >> {
  --
}

entity "puml-link:sys_dwh.parameters.adoc[prefix=..]" as sys_dwh.parameters << SN >> {
  --
}

entity "puml-link:sys_dwh.schemas.adoc[prefix=..]" as sys_dwh.schemas << SN >> {
  --
}

entity "puml-link:sys_dwh.sql_expression_dependencies.adoc[prefix=..]" as sys_dwh.sql_expression_dependencies << SN >> {
  --
}

entity "puml-link:sys_dwh.sql_modules.adoc[prefix=..]" as sys_dwh.sql_modules << SN >> {
  --
}

entity "puml-link:sys_dwh.tables.adoc[prefix=..]" as sys_dwh.tables << SN >> {
  --
}

entity "puml-link:sys_dwh.types.adoc[prefix=..]" as sys_dwh.types << SN >> {
  --
}

config.fs_get_parameter_value <.. reference.additional_Reference_guid
config.ftv_dwh_database <.. repo_sys.sql_expression_dependencies
config.ftv_dwh_database <.. repo_sys.SysColumn
config.ftv_dwh_database <.. repo_sys.ExtendedProperties
config.ftv_dwh_database <.. repo_sys.ExtendedProperties
config.Parameter <.. config.fs_get_parameter_value
config.Parameter <.. config.ftv_dwh_database
configT.spt_values <.. configT.type
configT.type <.. repo.RepoObject_gross
logs.ExecutionLog <.. logs.usp_ExecutionLog_insert
logs.usp_ExecutionLog_insert <.. reference.usp_RepoObjectSource_FirstResultSet
property.fs_get_RepoObjectProperty_nvarchar <.. repo.RepoObject_gross
property.RepoObjectProperty <.. property.fs_get_RepoObjectProperty_nvarchar
reference.additional_Reference <.. reference.additional_Reference_guid
reference.additional_Reference_guid <.. reference.RepoObject_reference_additional_internal
reference.RepoObject_QueryPlan <.. repo.RepoObject_gross
reference.RepoObject_reference <.. reference.RepoObject_reference_T
reference.RepoObject_reference_additional_internal <.. reference.RepoObject_reference_union
reference.RepoObject_reference_persistence <.. reference.RepoObject_reference_union
reference.RepoObject_reference_persistence_target_as_source <.. reference.RepoObject_reference_union
reference.RepoObject_reference_SqlExpressionDependencies <.. reference.RepoObject_reference_union
reference.RepoObject_reference_SqlExpressionDependencies <.. reference.RepoObject_reference_persistence_target_as_source
reference.RepoObject_reference_T <.. reference.RepoObject_ReferencingReferenced
reference.RepoObject_reference_union <.. reference.RepoObject_reference
reference.RepoObject_reference_virtual <.. reference.RepoObject_reference_union
reference.RepoObject_ReferencingReferenced <.. repo.RepoObject_gross
reference.RepoObjectSource_FirstResultSet <.. reference.usp_RepoObjectSource_FirstResultSet
reference.RepoObjectSource_virtual <.. reference.RepoObject_reference_virtual
repo.Index_Settings <.. repo.RepoObject_gross
repo.RepoObject <.. repo.RepoObject_gross
repo.RepoObject <.. reference.usp_RepoObjectSource_FirstResultSet
repo.RepoObject <.. repo.RepoObject_SSAS_tgt
repo.RepoObject <.. reference.RepoObject_reference_virtual
repo.RepoObject <.. reference.RepoObject_reference_persistence
repo.RepoObject <.. reference.additional_Reference_guid
repo.RepoObject <.. repo.SysObject_RepoObject_via_name
repo.RepoObject <.. repo.SysColumn_RepoObjectColumn_via_name
repo.RepoObject_gross <.. reference.RepoObject_reference_persistence_target_as_source
repo.RepoObject_gross <.. reference.usp_RepoObjectSource_FirstResultSet
repo.RepoObject_persistence <.. repo.RepoObject_gross
repo.RepoObject_persistence <.. reference.RepoObject_reference_persistence
repo.RepoObject_SSAS_src <.. repo.RepoObject_SSAS_tgt
repo.RepoObject_SSAS_tgt <.. repo.RepoObject
repo.RepoObject_SSAS_tgt <.. repo.RepoObjectColumn_SSAS_tgt
repo.RepoObjectColumn <.. repo.RepoObjectColumn_SSAS_tgt
repo.RepoObjectColumn <.. repo.SysColumn_RepoObjectColumn_via_name
repo.RepoObjectColumn <.. reference.additional_Reference_guid
repo.RepoObjectColumn_SSAS_src <.. repo.RepoObjectColumn_SSAS_tgt
repo.RepoObjectColumn_SSAS_tgt <.. repo.RepoObjectColumn
repo.RepoObjectColumn_SSAS_tgt <.. repo.RepoObject_SSAS_tgt
repo.SysColumn_RepoObjectColumn_via_name <.. repo_sys.sql_expression_dependencies
repo.SysObject_RepoObject_via_name <.. repo_sys.sql_expression_dependencies
repo_sys.ExtendedProperties <.. repo_sys.SysColumn
repo_sys.ExtendedProperties <.. repo_sys.SysObject
repo_sys.sql_expression_dependencies <.. reference.RepoObject_reference_SqlExpressionDependencies
repo_sys.SysColumn <.. repo.SysColumn_RepoObjectColumn_via_name
repo_sys.SysObject <.. repo.SysObject_RepoObject_via_name
repo_sys.SysObject <.. repo_sys.SysColumn
ssas.model_json <.. ssas.model_json_10
ssas.model_json_10 <.. ssas.model_json_20
ssas.model_json_20 <.. ssas.model_json_31_tables
ssas.model_json_31_tables <.. ssas.model_json_31_tables_T
ssas.model_json_31_tables_T <.. repo.RepoObject_gross
ssas.model_json_31_tables_T <.. repo.RepoObject_SSAS_src
ssas.model_json_31_tables_T <.. ssas.model_json_316_tables_descriptions_multiline
ssas.model_json_31_tables_T <.. ssas.model_json_311_tables_columns
ssas.model_json_311_tables_columns <.. ssas.model_json_311_tables_columns_T
ssas.model_json_311_tables_columns_T <.. repo.RepoObjectColumn_SSAS_src
ssas.model_json_316_tables_descriptions_multiline <.. ssas.model_json_3161_tables_descriptions_StrAgg
ssas.model_json_3161_tables_descriptions_StrAgg <.. repo.RepoObject_gross
sys_dwh.columns <.. repo_sys.SysColumn
sys_dwh.columns <.. repo_sys.ExtendedProperties
sys_dwh.columns <.. repo_sys.ExtendedProperties
sys_dwh.computed_columns <.. repo_sys.SysColumn
sys_dwh.default_constraints <.. repo_sys.SysColumn
sys_dwh.extended_properties <.. repo_sys.ExtendedProperties
sys_dwh.extended_properties <.. repo_sys.ExtendedProperties
sys_dwh.identity_columns <.. repo_sys.SysColumn
sys_dwh.indexes <.. repo_sys.ExtendedProperties
sys_dwh.indexes <.. repo_sys.ExtendedProperties
sys_dwh.objects <.. repo_sys.ExtendedProperties
sys_dwh.objects <.. repo_sys.ExtendedProperties
sys_dwh.objects <.. repo_sys.SysObject
sys_dwh.parameters <.. repo_sys.ExtendedProperties
sys_dwh.parameters <.. repo_sys.ExtendedProperties
sys_dwh.schemas <.. repo_sys.ExtendedProperties
sys_dwh.schemas <.. repo_sys.ExtendedProperties
sys_dwh.schemas <.. repo_sys.SysObject
sys_dwh.sql_expression_dependencies <.. repo_sys.sql_expression_dependencies
sys_dwh.sql_modules <.. repo_sys.SysObject
sys_dwh.tables <.. repo_sys.SysObject
sys_dwh.types <.. repo_sys.SysColumn
footer
to view a reduced diagram in original size and to be able to click on the links:
open the diagram in a new tab via the Context menu.
end footer

@enduml

