@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:configT.SsasDmv_ExplicitDataType.adoc[]" as configT.SsasDmv_ExplicitDataType << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.ForeignKey_ssas_IndexPattern_old.adoc[]" as repo.ForeignKey_ssas_IndexPattern_old << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.TMSCHEMA_COLUMNS.adoc[]" as ssas.TMSCHEMA_COLUMNS << U >> {
  - **databasename** : (nvarchar(128))
  - **ID** : (numeric(20, 0))
  --
}

entity "puml-link:dhw:sqldb:ssas.TMSCHEMA_COLUMNS_T.adoc[]" as ssas.TMSCHEMA_COLUMNS_T << U >> {
  - **databasename** : (nvarchar(128))
  - **ID** : (numeric(20, 0))
  --
}

entity "puml-link:dhw:sqldb:ssas.TMSCHEMA_RELATIONSHIPS.adoc[]" as ssas.TMSCHEMA_RELATIONSHIPS << U >> {
  - **databasename** : (nvarchar(128))
  - **ID** : (numeric(20, 0))
  --
}

entity "puml-link:dhw:sqldb:ssas.TMSCHEMA_RELATIONSHIPS_T.adoc[]" as ssas.TMSCHEMA_RELATIONSHIPS_T << U >> {
  - **databasename** : (nvarchar(128))
  - **ID** : (numeric(20, 0))
  --
}

entity "puml-link:dhw:sqldb:ssas.TMSCHEMA_TABLES.adoc[]" as ssas.TMSCHEMA_TABLES << U >> {
  - **databasename** : (nvarchar(128))
  - **ID** : (numeric(20, 0))
  --
}

entity "puml-link:dhw:sqldb:ssas.TMSCHEMA_TABLES_T.adoc[]" as ssas.TMSCHEMA_TABLES_T << U >> {
  - **databasename** : (nvarchar(128))
  - **ID** : (numeric(20, 0))
  --
}

configT.SsasDmv_ExplicitDataType <.. repo.ForeignKey_ssas_IndexPattern_old
ssas.TMSCHEMA_COLUMNS <.. ssas.TMSCHEMA_COLUMNS_T
ssas.TMSCHEMA_COLUMNS_T <.. repo.ForeignKey_ssas_IndexPattern_old
ssas.TMSCHEMA_RELATIONSHIPS <.. ssas.TMSCHEMA_RELATIONSHIPS_T
ssas.TMSCHEMA_RELATIONSHIPS_T <.. repo.ForeignKey_ssas_IndexPattern_old
ssas.TMSCHEMA_TABLES <.. ssas.TMSCHEMA_TABLES_T
ssas.TMSCHEMA_TABLES_T <.. repo.ForeignKey_ssas_IndexPattern_old
@enduml

