@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity "[[{site-url}/{page-component-name}/current/{page-module}/config.fs_get_parameter_value.html config.fs_get_parameter_value]]" as config.fs_get_parameter_value << FN >> {
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/config.ftv_dwh_database.html config.ftv_dwh_database]]" as config.ftv_dwh_database << IF >> {
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/config.Parameter.html config.Parameter]]" as config.Parameter << U >> {
  - **Parameter_name** : (varchar(100))
  - **sub_Parameter** : (nvarchar(128))
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/configT.spt_values.html configT.spt_values]]" as configT.spt_values << U >> {
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/configT.type.html configT.type]]" as configT.type << V >> {
  **type** : (nvarchar(128))
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/logs.ExecutionLog.html logs.ExecutionLog]]" as logs.ExecutionLog << U >> {
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/logs.usp_ExecutionLog_insert.html logs.usp_ExecutionLog_insert]]" as logs.usp_ExecutionLog_insert << P >> {
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/property.fs_get_RepoObjectProperty_nvarchar.html property.fs_get_RepoObjectProperty_nvarchar]]" as property.fs_get_RepoObjectProperty_nvarchar << FN >> {
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/property.RepoObjectProperty.html property.RepoObjectProperty]]" as property.RepoObjectProperty << U >> {
  - **RepoObjectProperty_id** : (int)
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/reference.additional_Reference.html reference.additional_Reference]]" as reference.additional_Reference << U >> {
  - **Id** : (int)
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/reference.additional_Reference_guid.html reference.additional_Reference_guid]]" as reference.additional_Reference_guid << V >> {
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/reference.RepoObject_QueryPlan.html reference.RepoObject_QueryPlan]]" as reference.RepoObject_QueryPlan << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/reference.RepoObject_reference.html reference.RepoObject_reference]]" as reference.RepoObject_reference << V >> {
  **referenced_RepoObject_guid** : (uniqueidentifier)
  **referencing_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/reference.RepoObject_reference_additional_internal.html reference.RepoObject_reference_additional_internal]]" as reference.RepoObject_reference_additional_internal << V >> {
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/reference.RepoObject_reference_persistence.html reference.RepoObject_reference_persistence]]" as reference.RepoObject_reference_persistence << V >> {
  **referenced_RepoObject_guid** : (uniqueidentifier)
  - **referencing_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/reference.RepoObject_reference_persistence_target_as_source.html reference.RepoObject_reference_persistence_target_as_source]]" as reference.RepoObject_reference_persistence_target_as_source << V >> {
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/reference.RepoObject_reference_SqlExpressionDependencies.html reference.RepoObject_reference_SqlExpressionDependencies]]" as reference.RepoObject_reference_SqlExpressionDependencies << V >> {
  **referenced_RepoObject_guid** : (uniqueidentifier)
  **referencing_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/reference.RepoObject_reference_T.html reference.RepoObject_reference_T]]" as reference.RepoObject_reference_T << U >> {
  **referenced_RepoObject_guid** : (uniqueidentifier)
  **referencing_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/reference.RepoObject_reference_union.html reference.RepoObject_reference_union]]" as reference.RepoObject_reference_union << V >> {
  **referenced_RepoObject_guid** : (uniqueidentifier)
  **referencing_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/reference.RepoObject_reference_virtual.html reference.RepoObject_reference_virtual]]" as reference.RepoObject_reference_virtual << V >> {
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/reference.RepoObject_ReferencingReferenced.html reference.RepoObject_ReferencingReferenced]]" as reference.RepoObject_ReferencingReferenced << V >> {
  - **Referenced_guid** : (uniqueidentifier)
  - **Referencing_guid** : (uniqueidentifier)
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/reference.RepoObjectSource_virtual.html reference.RepoObjectSource_virtual]]" as reference.RepoObjectSource_virtual << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **Source_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/repo.ForeignKey_Indexes.html repo.ForeignKey_Indexes]]" as repo.ForeignKey_Indexes << V >> {
  **ForeignKey_guid** : (uniqueidentifier)
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/repo.ForeignKey_Indexes_union.html repo.ForeignKey_Indexes_union]]" as repo.ForeignKey_Indexes_union << V >> {
  **ForeignKey_guid** : (uniqueidentifier)
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/repo.ForeignKey_Indexes_union_T.html repo.ForeignKey_Indexes_union_T]]" as repo.ForeignKey_Indexes_union_T << U >> {
  **ForeignKey_guid** : (uniqueidentifier)
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/repo.ForeignKey_IndexPattern.html repo.ForeignKey_IndexPattern]]" as repo.ForeignKey_IndexPattern << V >> {
  - **constraint_object_id** : (int)
  **ForeignKey_guid** : (uniqueidentifier)
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/repo.ForeignKey_ssas_Indexes.html repo.ForeignKey_ssas_Indexes]]" as repo.ForeignKey_ssas_Indexes << V >> {
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/repo.ForeignKey_ssas_IndexPattern.html repo.ForeignKey_ssas_IndexPattern]]" as repo.ForeignKey_ssas_IndexPattern << V >> {
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/repo.ForeignKey_virtual.html repo.ForeignKey_virtual]]" as repo.ForeignKey_virtual << U >> {
  - **ForeignKey_guid** : (uniqueidentifier)
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/repo.ForeignKey_virtual_Indexes.html repo.ForeignKey_virtual_Indexes]]" as repo.ForeignKey_virtual_Indexes << V >> {
  - **ForeignKey_guid** : (uniqueidentifier)
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/repo.Index_ColumList.html repo.Index_ColumList]]" as repo.Index_ColumList << V >> {
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/repo.Index_ColumList_T.html repo.Index_ColumList_T]]" as repo.Index_ColumList_T << U >> {
  - **index_guid** : (uniqueidentifier)
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/repo.Index_gross.html repo.Index_gross]]" as repo.Index_gross << V >> {
  - **index_guid** : (uniqueidentifier)
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/repo.Index_IndexPattern.html repo.Index_IndexPattern]]" as repo.Index_IndexPattern << V >> {
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/repo.Index_Settings.html repo.Index_Settings]]" as repo.Index_Settings << U >> {
  - **index_guid** : (uniqueidentifier)
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/repo.Index_ssas.html repo.Index_ssas]]" as repo.Index_ssas << V >> {
  - **databasename** : (nvarchar(128))
  **index_name** : (nvarchar(450))
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/repo.Index_ssas_IndexPatternColumnGuid.html repo.Index_ssas_IndexPatternColumnGuid]]" as repo.Index_ssas_IndexPatternColumnGuid << V >> {
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/repo.Index_ssas_T.html repo.Index_ssas_T]]" as repo.Index_ssas_T << U >> {
  - **databasename** : (nvarchar(128))
  **index_name** : (nvarchar(450))
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/repo.Index_union.html repo.Index_union]]" as repo.Index_union << V >> {
  **index_guid** : (uniqueidentifier)
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/repo.Index_unique_IndexPatternColumnGuid.html repo.Index_unique_IndexPatternColumnGuid]]" as repo.Index_unique_IndexPatternColumnGuid << V >> {
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/repo.Index_virtual.html repo.Index_virtual]]" as repo.Index_virtual << U >> {
  - **index_guid** : (uniqueidentifier)
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/repo.Index_virtual_IndexPatternColumnGuid.html repo.Index_virtual_IndexPatternColumnGuid]]" as repo.Index_virtual_IndexPatternColumnGuid << V >> {
  - **index_guid** : (uniqueidentifier)
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/repo.IndexColumn_ssas.html repo.IndexColumn_ssas]]" as repo.IndexColumn_ssas << V >> {
  - **index_guid** : (uniqueidentifier)
  - **index_column_id** : (int)
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/repo.IndexColumn_ssas_gross.html repo.IndexColumn_ssas_gross]]" as repo.IndexColumn_ssas_gross << V >> {
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/repo.IndexColumn_ssas_T.html repo.IndexColumn_ssas_T]]" as repo.IndexColumn_ssas_T << U >> {
  - **index_guid** : (uniqueidentifier)
  - **index_column_id** : (int)
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/repo.IndexColumn_union.html repo.IndexColumn_union]]" as repo.IndexColumn_union << V >> {
  **index_guid** : (uniqueidentifier)
  - **index_column_id** : (int)
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/repo.IndexColumn_union_T.html repo.IndexColumn_union_T]]" as repo.IndexColumn_union_T << U >> {
  **index_guid** : (uniqueidentifier)
  - **index_column_id** : (int)
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/repo.IndexColumn_virtual.html repo.IndexColumn_virtual]]" as repo.IndexColumn_virtual << U >> {
  - **index_guid** : (uniqueidentifier)
  - **index_column_id** : (int)
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/repo.IndexColumn_virtual_gross.html repo.IndexColumn_virtual_gross]]" as repo.IndexColumn_virtual_gross << V >> {
  - **index_column_id** : (int)
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/repo.RepoObject.html repo.RepoObject]]" as repo.RepoObject << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/repo.RepoObject_gross.html repo.RepoObject_gross]]" as repo.RepoObject_gross << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/repo.RepoObject_persistence.html repo.RepoObject_persistence]]" as repo.RepoObject_persistence << U >> {
  - **target_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/repo.RepoObject_SSAS_src.html repo.RepoObject_SSAS_src]]" as repo.RepoObject_SSAS_src << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/repo.RepoObject_SSAS_tgt.html repo.RepoObject_SSAS_tgt]]" as repo.RepoObject_SSAS_tgt << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/repo.RepoObjectColumn.html repo.RepoObjectColumn]]" as repo.RepoObjectColumn << U >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/repo.RepoObjectColumn_SSAS_src.html repo.RepoObjectColumn_SSAS_src]]" as repo.RepoObjectColumn_SSAS_src << V >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/repo.RepoObjectColumn_SSAS_tgt.html repo.RepoObjectColumn_SSAS_tgt]]" as repo.RepoObjectColumn_SSAS_tgt << V >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/repo.SysColumn_RepoObjectColumn_via_name.html repo.SysColumn_RepoObjectColumn_via_name]]" as repo.SysColumn_RepoObjectColumn_via_name << V >> {
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/repo.SysObject_RepoObject_via_name.html repo.SysObject_RepoObject_via_name]]" as repo.SysObject_RepoObject_via_name << V >> {
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/repo.usp_Index_finish.html repo.usp_Index_finish]]" as repo.usp_Index_finish << P >> {
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/repo.usp_Index_ForeignKey.html repo.usp_Index_ForeignKey]]" as repo.usp_Index_ForeignKey << P >> {
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/repo.usp_Index_Settings.html repo.usp_Index_Settings]]" as repo.usp_Index_Settings << P >> {
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/repo.usp_Index_virtual_set.html repo.usp_Index_virtual_set]]" as repo.usp_Index_virtual_set << P >> {
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/repo.usp_PERSIST_ForeignKey_Indexes_union_T.html repo.usp_PERSIST_ForeignKey_Indexes_union_T]]" as repo.usp_PERSIST_ForeignKey_Indexes_union_T << P >> {
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/repo.usp_PERSIST_Index_ColumList_T.html repo.usp_PERSIST_Index_ColumList_T]]" as repo.usp_PERSIST_Index_ColumList_T << P >> {
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/repo.usp_PERSIST_IndexColumn_union_T.html repo.usp_PERSIST_IndexColumn_union_T]]" as repo.usp_PERSIST_IndexColumn_union_T << P >> {
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/repo_sys.ExtendedProperties.html repo_sys.ExtendedProperties]]" as repo_sys.ExtendedProperties << V >> {
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/repo_sys.ForeignKey.html repo_sys.ForeignKey]]" as repo_sys.ForeignKey << V >> {
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/repo_sys.ForeignKeyColumn.html repo_sys.ForeignKeyColumn]]" as repo_sys.ForeignKeyColumn << V >> {
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/repo_sys.Index_unique.html repo_sys.Index_unique]]" as repo_sys.Index_unique << V >> {
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/repo_sys.IndexColumn_unique.html repo_sys.IndexColumn_unique]]" as repo_sys.IndexColumn_unique << V >> {
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/repo_sys.sql_expression_dependencies.html repo_sys.sql_expression_dependencies]]" as repo_sys.sql_expression_dependencies << V >> {
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/repo_sys.SysColumn.html repo_sys.SysColumn]]" as repo_sys.SysColumn << V >> {
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/repo_sys.SysObject.html repo_sys.SysObject]]" as repo_sys.SysObject << V >> {
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/ssas.IndexColumn_from_IsKey.html ssas.IndexColumn_from_IsKey]]" as ssas.IndexColumn_from_IsKey << V >> {
  - **databasename** : (nvarchar(128))
  - **TableName** : (nvarchar(128))
  - **tables_columns_name** : (nvarchar(128))
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/ssas.IndexColumn_from_IsUnique.html ssas.IndexColumn_from_IsUnique]]" as ssas.IndexColumn_from_IsUnique << V >> {
  - **databasename** : (nvarchar(128))
  - **TableName** : (nvarchar(128))
  - **tables_columns_name** : (nvarchar(128))
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/ssas.IndexColumn_from_Relationship.html ssas.IndexColumn_from_Relationship]]" as ssas.IndexColumn_from_Relationship << V >> {
  - **databasename** : (nvarchar(128))
  - **TableName** : (nvarchar(128))
  - **tables_columns_name** : (nvarchar(128))
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/ssas.IndexColumn_union.html ssas.IndexColumn_union]]" as ssas.IndexColumn_union << V >> {
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/ssas.model_json.html ssas.model_json]]" as ssas.model_json << U >> {
  - **databasename** : (nvarchar(128))
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/ssas.model_json_10.html ssas.model_json_10]]" as ssas.model_json_10 << V >> {
  - **databasename** : (nvarchar(128))
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/ssas.model_json_20.html ssas.model_json_20]]" as ssas.model_json_20 << V >> {
  - **databasename** : (nvarchar(128))
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/ssas.model_json_31_tables.html ssas.model_json_31_tables]]" as ssas.model_json_31_tables << V >> {
  - **databasename** : (nvarchar(128))
  **tables_name** : (nvarchar(128))
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/ssas.model_json_31_tables_T.html ssas.model_json_31_tables_T]]" as ssas.model_json_31_tables_T << U >> {
  - **databasename** : (nvarchar(128))
  **tables_name** : (nvarchar(128))
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/ssas.model_json_311_tables_columns.html ssas.model_json_311_tables_columns]]" as ssas.model_json_311_tables_columns << V >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  **tables_columns_name** : (nvarchar(128))
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/ssas.model_json_311_tables_columns_T.html ssas.model_json_311_tables_columns_T]]" as ssas.model_json_311_tables_columns_T << U >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  **tables_columns_name** : (nvarchar(128))
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/ssas.model_json_316_tables_descriptions_multiline.html ssas.model_json_316_tables_descriptions_multiline]]" as ssas.model_json_316_tables_descriptions_multiline << V >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/ssas.model_json_3161_tables_descriptions_StrAgg.html ssas.model_json_3161_tables_descriptions_StrAgg]]" as ssas.model_json_3161_tables_descriptions_StrAgg << V >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/ssas.model_json_32_relationships.html ssas.model_json_32_relationships]]" as ssas.model_json_32_relationships << V >> {
  - **databasename** : (nvarchar(128))
  **relationships_name** : (nvarchar(500))
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/ssas.model_json_32_relationships_T.html ssas.model_json_32_relationships_T]]" as ssas.model_json_32_relationships_T << U >> {
  - **ForeignKey_guid** : (uniqueidentifier)
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/sys_dwh.columns.html sys_dwh.columns]]" as sys_dwh.columns << SN >> {
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/sys_dwh.computed_columns.html sys_dwh.computed_columns]]" as sys_dwh.computed_columns << SN >> {
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/sys_dwh.default_constraints.html sys_dwh.default_constraints]]" as sys_dwh.default_constraints << SN >> {
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/sys_dwh.extended_properties.html sys_dwh.extended_properties]]" as sys_dwh.extended_properties << SN >> {
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/sys_dwh.foreign_key_columns.html sys_dwh.foreign_key_columns]]" as sys_dwh.foreign_key_columns << SN >> {
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/sys_dwh.foreign_keys.html sys_dwh.foreign_keys]]" as sys_dwh.foreign_keys << SN >> {
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/sys_dwh.identity_columns.html sys_dwh.identity_columns]]" as sys_dwh.identity_columns << SN >> {
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/sys_dwh.index_columns.html sys_dwh.index_columns]]" as sys_dwh.index_columns << SN >> {
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/sys_dwh.indexes.html sys_dwh.indexes]]" as sys_dwh.indexes << SN >> {
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/sys_dwh.objects.html sys_dwh.objects]]" as sys_dwh.objects << SN >> {
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/sys_dwh.parameters.html sys_dwh.parameters]]" as sys_dwh.parameters << SN >> {
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/sys_dwh.schemas.html sys_dwh.schemas]]" as sys_dwh.schemas << SN >> {
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/sys_dwh.sql_expression_dependencies.html sys_dwh.sql_expression_dependencies]]" as sys_dwh.sql_expression_dependencies << SN >> {
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/sys_dwh.sql_modules.html sys_dwh.sql_modules]]" as sys_dwh.sql_modules << SN >> {
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/sys_dwh.tables.html sys_dwh.tables]]" as sys_dwh.tables << SN >> {
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/sys_dwh.types.html sys_dwh.types]]" as sys_dwh.types << SN >> {
  --
}

config.fs_get_parameter_value <.. reference.additional_Reference_guid
config.fs_get_parameter_value <.. reference.additional_Reference_guid
config.fs_get_parameter_value <.. reference.additional_Reference_guid
config.ftv_dwh_database <.. repo_sys.sql_expression_dependencies
config.ftv_dwh_database <.. repo_sys.sql_expression_dependencies
config.ftv_dwh_database <.. repo_sys.sql_expression_dependencies
config.ftv_dwh_database <.. repo_sys.ExtendedProperties
config.ftv_dwh_database <.. repo_sys.SysColumn
config.Parameter <.. config.fs_get_parameter_value
config.Parameter <.. config.fs_get_parameter_value
config.Parameter <.. config.fs_get_parameter_value
config.Parameter <.. config.ftv_dwh_database
configT.spt_values <.. configT.type
configT.spt_values <.. configT.type
configT.spt_values <.. configT.type
configT.type <.. repo.RepoObject_gross
configT.type <.. repo.RepoObject_gross
configT.type <.. repo.RepoObject_gross
logs.ExecutionLog <.. logs.usp_ExecutionLog_insert
logs.usp_ExecutionLog_insert <.. repo.usp_Index_virtual_set
logs.usp_ExecutionLog_insert <.. repo.usp_Index_finish
logs.usp_ExecutionLog_insert <.. repo.usp_PERSIST_ForeignKey_Indexes_union_T
logs.usp_ExecutionLog_insert <.. repo.usp_Index_ForeignKey
logs.usp_ExecutionLog_insert <.. repo.usp_Index_Settings
logs.usp_ExecutionLog_insert <.. repo.usp_PERSIST_Index_ColumList_T
logs.usp_ExecutionLog_insert <.. repo.usp_PERSIST_IndexColumn_union_T
property.fs_get_RepoObjectProperty_nvarchar <.. repo.RepoObject_gross
property.fs_get_RepoObjectProperty_nvarchar <.. repo.RepoObject_gross
property.fs_get_RepoObjectProperty_nvarchar <.. repo.RepoObject_gross
property.RepoObjectProperty <.. property.fs_get_RepoObjectProperty_nvarchar
property.RepoObjectProperty <.. property.fs_get_RepoObjectProperty_nvarchar
property.RepoObjectProperty <.. property.fs_get_RepoObjectProperty_nvarchar
reference.additional_Reference <.. reference.additional_Reference_guid
reference.additional_Reference <.. reference.additional_Reference_guid
reference.additional_Reference <.. reference.additional_Reference_guid
reference.additional_Reference_guid <.. reference.RepoObject_reference_additional_internal
reference.additional_Reference_guid <.. reference.RepoObject_reference_additional_internal
reference.additional_Reference_guid <.. reference.RepoObject_reference_additional_internal
reference.RepoObject_QueryPlan <.. repo.RepoObject_gross
reference.RepoObject_QueryPlan <.. repo.RepoObject_gross
reference.RepoObject_QueryPlan <.. repo.RepoObject_gross
reference.RepoObject_reference <.. reference.RepoObject_reference_T
reference.RepoObject_reference <.. reference.RepoObject_reference_T
reference.RepoObject_reference <.. reference.RepoObject_reference_T
reference.RepoObject_reference_additional_internal <.. reference.RepoObject_reference_union
reference.RepoObject_reference_additional_internal <.. reference.RepoObject_reference_union
reference.RepoObject_reference_additional_internal <.. reference.RepoObject_reference_union
reference.RepoObject_reference_persistence <.. reference.RepoObject_reference_union
reference.RepoObject_reference_persistence <.. reference.RepoObject_reference_union
reference.RepoObject_reference_persistence <.. reference.RepoObject_reference_union
reference.RepoObject_reference_persistence_target_as_source <.. reference.RepoObject_reference_union
reference.RepoObject_reference_persistence_target_as_source <.. reference.RepoObject_reference_union
reference.RepoObject_reference_persistence_target_as_source <.. reference.RepoObject_reference_union
reference.RepoObject_reference_SqlExpressionDependencies <.. reference.RepoObject_reference_union
reference.RepoObject_reference_SqlExpressionDependencies <.. reference.RepoObject_reference_union
reference.RepoObject_reference_SqlExpressionDependencies <.. reference.RepoObject_reference_union
reference.RepoObject_reference_SqlExpressionDependencies <.. reference.RepoObject_reference_persistence_target_as_source
reference.RepoObject_reference_SqlExpressionDependencies <.. reference.RepoObject_reference_persistence_target_as_source
reference.RepoObject_reference_SqlExpressionDependencies <.. reference.RepoObject_reference_persistence_target_as_source
reference.RepoObject_reference_T <.. reference.RepoObject_ReferencingReferenced
reference.RepoObject_reference_T <.. reference.RepoObject_ReferencingReferenced
reference.RepoObject_reference_T <.. reference.RepoObject_ReferencingReferenced
reference.RepoObject_reference_union <.. reference.RepoObject_reference
reference.RepoObject_reference_union <.. reference.RepoObject_reference
reference.RepoObject_reference_union <.. reference.RepoObject_reference
reference.RepoObject_reference_virtual <.. reference.RepoObject_reference_union
reference.RepoObject_reference_virtual <.. reference.RepoObject_reference_union
reference.RepoObject_reference_virtual <.. reference.RepoObject_reference_union
reference.RepoObject_ReferencingReferenced <.. repo.RepoObject_gross
reference.RepoObject_ReferencingReferenced <.. repo.RepoObject_gross
reference.RepoObject_ReferencingReferenced <.. repo.RepoObject_gross
reference.RepoObjectSource_virtual <.. reference.RepoObject_reference_virtual
reference.RepoObjectSource_virtual <.. reference.RepoObject_reference_virtual
reference.RepoObjectSource_virtual <.. reference.RepoObject_reference_virtual
repo.ForeignKey_Indexes <.. repo.ForeignKey_Indexes_union
repo.ForeignKey_Indexes <.. repo.usp_Index_ForeignKey
repo.ForeignKey_Indexes_union <.. repo.usp_PERSIST_ForeignKey_Indexes_union_T
repo.ForeignKey_Indexes_union <.. repo.ForeignKey_Indexes_union_T
repo.ForeignKey_Indexes_union <.. repo.ForeignKey_Indexes_union_T
repo.ForeignKey_Indexes_union_T <.. repo.usp_Index_finish
repo.ForeignKey_Indexes_union_T <.. repo.usp_PERSIST_ForeignKey_Indexes_union_T
repo.ForeignKey_IndexPattern <.. repo.ForeignKey_Indexes
repo.ForeignKey_ssas_Indexes <.. repo.ForeignKey_Indexes_union
repo.ForeignKey_ssas_IndexPattern <.. repo.ForeignKey_ssas_Indexes
repo.ForeignKey_virtual <.. repo.ForeignKey_virtual_Indexes
repo.ForeignKey_virtual_Indexes <.. repo.ForeignKey_Indexes_union
repo.Index_ColumList <.. repo.usp_PERSIST_Index_ColumList_T
repo.Index_ColumList <.. repo.Index_ColumList_T
repo.Index_ColumList <.. repo.Index_ColumList_T
repo.Index_ColumList <.. repo.Index_ColumList_T
repo.Index_ColumList <.. repo.Index_ColumList_T
repo.Index_ColumList_T <.. repo.Index_gross
repo.Index_ColumList_T <.. repo.Index_gross
repo.Index_ColumList_T <.. repo.Index_gross
repo.Index_ColumList_T <.. repo.usp_PERSIST_Index_ColumList_T
repo.Index_gross <.. repo.usp_Index_virtual_set
repo.Index_gross <.. repo.ForeignKey_Indexes
repo.Index_gross <.. repo.usp_Index_finish
repo.Index_gross <.. repo.ForeignKey_virtual_Indexes
repo.Index_IndexPattern <.. repo.usp_Index_Settings
repo.Index_Settings <.. repo.Index_gross
repo.Index_Settings <.. repo.Index_gross
repo.Index_Settings <.. repo.Index_gross
repo.Index_Settings <.. repo.usp_Index_Settings
repo.Index_Settings <.. repo.usp_Index_virtual_set
repo.Index_Settings <.. repo.usp_Index_finish
repo.Index_Settings <.. repo.RepoObject_gross
repo.Index_Settings <.. repo.RepoObject_gross
repo.Index_Settings <.. repo.RepoObject_gross
repo.Index_ssas <.. repo.Index_ssas_T
repo.Index_ssas_IndexPatternColumnGuid <.. repo.Index_union
repo.Index_ssas_T <.. repo.IndexColumn_ssas
repo.Index_ssas_T <.. repo.Index_union
repo.Index_ssas_T <.. repo.Index_ssas_IndexPatternColumnGuid
repo.Index_ssas_T <.. repo.ForeignKey_ssas_Indexes
repo.Index_ssas_T <.. repo.IndexColumn_ssas_gross
repo.Index_union <.. repo.Index_gross
repo.Index_union <.. repo.Index_gross
repo.Index_union <.. repo.Index_gross
repo.Index_union <.. repo.usp_Index_finish
repo.Index_unique_IndexPatternColumnGuid <.. repo.Index_union
repo.Index_virtual <.. repo.Index_union
repo.Index_virtual <.. repo.usp_Index_virtual_set
repo.Index_virtual <.. repo.usp_Index_finish
repo.Index_virtual <.. repo.Index_virtual_IndexPatternColumnGuid
repo.Index_virtual <.. repo.IndexColumn_virtual_gross
repo.Index_virtual_IndexPatternColumnGuid <.. repo.Index_union
repo.IndexColumn_ssas <.. repo.IndexColumn_ssas_T
repo.IndexColumn_ssas_gross <.. repo.IndexColumn_union
repo.IndexColumn_ssas_T <.. repo.Index_ssas_IndexPatternColumnGuid
repo.IndexColumn_ssas_T <.. repo.IndexColumn_ssas_gross
repo.IndexColumn_union <.. repo.IndexColumn_union_T
repo.IndexColumn_union <.. repo.usp_PERSIST_IndexColumn_union_T
repo.IndexColumn_union_T <.. repo.usp_PERSIST_IndexColumn_union_T
repo.IndexColumn_union_T <.. repo.Index_ColumList
repo.IndexColumn_union_T <.. repo.Index_IndexPattern
repo.IndexColumn_virtual <.. repo.Index_virtual_IndexPatternColumnGuid
repo.IndexColumn_virtual <.. repo.IndexColumn_virtual_gross
repo.IndexColumn_virtual <.. repo.usp_Index_virtual_set
repo.IndexColumn_virtual <.. repo.usp_Index_finish
repo.IndexColumn_virtual_gross <.. repo.IndexColumn_union
repo.RepoObject <.. reference.RepoObject_reference_virtual
repo.RepoObject <.. reference.RepoObject_reference_virtual
repo.RepoObject <.. reference.RepoObject_reference_virtual
repo.RepoObject <.. reference.RepoObject_reference_persistence
repo.RepoObject <.. reference.RepoObject_reference_persistence
repo.RepoObject <.. reference.RepoObject_reference_persistence
repo.RepoObject <.. reference.additional_Reference_guid
repo.RepoObject <.. reference.additional_Reference_guid
repo.RepoObject <.. reference.additional_Reference_guid
repo.RepoObject <.. repo_sys.Index_unique
repo.RepoObject <.. repo.RepoObject_gross
repo.RepoObject <.. repo.RepoObject_gross
repo.RepoObject <.. repo.RepoObject_gross
repo.RepoObject <.. repo_sys.ForeignKey
repo.RepoObject <.. repo.RepoObject_SSAS_tgt
repo.RepoObject <.. repo.RepoObject_SSAS_tgt
repo.RepoObject <.. repo.IndexColumn_virtual_gross
repo.RepoObject <.. repo.usp_Index_virtual_set
repo.RepoObject <.. repo.usp_Index_finish
repo.RepoObject <.. repo.IndexColumn_ssas_gross
repo.RepoObject <.. repo.SysObject_RepoObject_via_name
repo.RepoObject <.. repo.SysObject_RepoObject_via_name
repo.RepoObject <.. repo.SysColumn_RepoObjectColumn_via_name
repo.RepoObject <.. repo.SysColumn_RepoObjectColumn_via_name
repo.RepoObject_gross <.. reference.RepoObject_reference_persistence_target_as_source
repo.RepoObject_gross <.. reference.RepoObject_reference_persistence_target_as_source
repo.RepoObject_gross <.. reference.RepoObject_reference_persistence_target_as_source
repo.RepoObject_gross <.. repo.Index_gross
repo.RepoObject_gross <.. repo.Index_gross
repo.RepoObject_gross <.. repo.Index_gross
repo.RepoObject_persistence <.. reference.RepoObject_reference_persistence
repo.RepoObject_persistence <.. reference.RepoObject_reference_persistence
repo.RepoObject_persistence <.. reference.RepoObject_reference_persistence
repo.RepoObject_persistence <.. repo.usp_Index_finish
repo.RepoObject_persistence <.. repo.RepoObject_gross
repo.RepoObject_persistence <.. repo.RepoObject_gross
repo.RepoObject_persistence <.. repo.RepoObject_gross
repo.RepoObject_SSAS_src <.. repo.RepoObject_SSAS_tgt
repo.RepoObject_SSAS_src <.. repo.RepoObject_SSAS_tgt
repo.RepoObject_SSAS_tgt <.. repo.RepoObjectColumn_SSAS_tgt
repo.RepoObject_SSAS_tgt <.. repo.RepoObject
repo.RepoObject_SSAS_tgt <.. repo.RepoObject
repo.RepoObjectColumn <.. reference.additional_Reference_guid
repo.RepoObjectColumn <.. reference.additional_Reference_guid
repo.RepoObjectColumn <.. reference.additional_Reference_guid
repo.RepoObjectColumn <.. repo.usp_Index_virtual_set
repo.RepoObjectColumn <.. repo.RepoObjectColumn_SSAS_tgt
repo.RepoObjectColumn <.. repo.IndexColumn_virtual_gross
repo.RepoObjectColumn <.. repo.SysColumn_RepoObjectColumn_via_name
repo.RepoObjectColumn <.. repo.SysColumn_RepoObjectColumn_via_name
repo.RepoObjectColumn <.. repo.IndexColumn_ssas_gross
repo.RepoObjectColumn_SSAS_src <.. repo.RepoObjectColumn_SSAS_tgt
repo.RepoObjectColumn_SSAS_tgt <.. repo.RepoObject_SSAS_tgt
repo.RepoObjectColumn_SSAS_tgt <.. repo.RepoObject_SSAS_tgt
repo.RepoObjectColumn_SSAS_tgt <.. repo.RepoObjectColumn
repo.SysColumn_RepoObjectColumn_via_name <.. repo_sys.sql_expression_dependencies
repo.SysColumn_RepoObjectColumn_via_name <.. repo_sys.sql_expression_dependencies
repo.SysColumn_RepoObjectColumn_via_name <.. repo_sys.sql_expression_dependencies
repo.SysColumn_RepoObjectColumn_via_name <.. repo_sys.IndexColumn_unique
repo.SysColumn_RepoObjectColumn_via_name <.. repo_sys.IndexColumn_unique
repo.SysObject_RepoObject_via_name <.. repo_sys.sql_expression_dependencies
repo.SysObject_RepoObject_via_name <.. repo_sys.sql_expression_dependencies
repo.SysObject_RepoObject_via_name <.. repo_sys.sql_expression_dependencies
repo.SysObject_RepoObject_via_name <.. repo_sys.IndexColumn_unique
repo.SysObject_RepoObject_via_name <.. repo_sys.IndexColumn_unique
repo.usp_Index_finish <.. repo.usp_Index_ForeignKey
repo.usp_Index_Settings <.. repo.usp_Index_finish
repo.usp_Index_virtual_set <.. repo.usp_Index_ForeignKey
repo.usp_PERSIST_ForeignKey_Indexes_union_T <.. repo.usp_Index_ForeignKey
repo.usp_PERSIST_Index_ColumList_T <.. repo.usp_Index_finish
repo.usp_PERSIST_IndexColumn_union_T <.. repo.usp_Index_finish
repo_sys.ExtendedProperties <.. repo_sys.SysColumn
repo_sys.ExtendedProperties <.. repo_sys.SysObject
repo_sys.ForeignKey <.. repo_sys.ForeignKeyColumn
repo_sys.ForeignKey <.. repo.ForeignKey_IndexPattern
repo_sys.ForeignKeyColumn <.. repo.ForeignKey_IndexPattern
repo_sys.Index_unique <.. repo.Index_union
repo_sys.IndexColumn_unique <.. repo.IndexColumn_union
repo_sys.IndexColumn_unique <.. repo.Index_unique_IndexPatternColumnGuid
repo_sys.sql_expression_dependencies <.. reference.RepoObject_reference_SqlExpressionDependencies
repo_sys.sql_expression_dependencies <.. reference.RepoObject_reference_SqlExpressionDependencies
repo_sys.sql_expression_dependencies <.. reference.RepoObject_reference_SqlExpressionDependencies
repo_sys.SysColumn <.. repo_sys.ForeignKeyColumn
repo_sys.SysColumn <.. repo.SysColumn_RepoObjectColumn_via_name
repo_sys.SysColumn <.. repo.SysColumn_RepoObjectColumn_via_name
repo_sys.SysObject <.. repo.SysObject_RepoObject_via_name
repo_sys.SysObject <.. repo.SysObject_RepoObject_via_name
repo_sys.SysObject <.. repo_sys.SysColumn
ssas.IndexColumn_from_IsKey <.. ssas.IndexColumn_union
ssas.IndexColumn_from_IsUnique <.. ssas.IndexColumn_union
ssas.IndexColumn_from_Relationship <.. ssas.IndexColumn_union
ssas.IndexColumn_union <.. repo.IndexColumn_ssas
ssas.IndexColumn_union <.. repo.Index_ssas
ssas.model_json <.. ssas.model_json_10
ssas.model_json <.. ssas.model_json_10
ssas.model_json <.. ssas.model_json_10
ssas.model_json_10 <.. ssas.model_json_20
ssas.model_json_10 <.. ssas.model_json_20
ssas.model_json_10 <.. ssas.model_json_20
ssas.model_json_20 <.. ssas.model_json_32_relationships
ssas.model_json_20 <.. ssas.model_json_31_tables
ssas.model_json_20 <.. ssas.model_json_31_tables
ssas.model_json_20 <.. ssas.model_json_31_tables
ssas.model_json_31_tables <.. ssas.model_json_31_tables_T
ssas.model_json_31_tables <.. ssas.model_json_31_tables_T
ssas.model_json_31_tables <.. ssas.model_json_31_tables_T
ssas.model_json_31_tables_T <.. ssas.model_json_316_tables_descriptions_multiline
ssas.model_json_31_tables_T <.. ssas.model_json_316_tables_descriptions_multiline
ssas.model_json_31_tables_T <.. ssas.model_json_316_tables_descriptions_multiline
ssas.model_json_31_tables_T <.. ssas.model_json_311_tables_columns
ssas.model_json_31_tables_T <.. ssas.model_json_311_tables_columns
ssas.model_json_31_tables_T <.. repo.ForeignKey_ssas_IndexPattern
ssas.model_json_31_tables_T <.. repo.RepoObject_SSAS_src
ssas.model_json_31_tables_T <.. repo.RepoObject_SSAS_src
ssas.model_json_31_tables_T <.. repo.RepoObject_gross
ssas.model_json_31_tables_T <.. repo.RepoObject_gross
ssas.model_json_31_tables_T <.. repo.RepoObject_gross
ssas.model_json_311_tables_columns <.. ssas.model_json_311_tables_columns_T
ssas.model_json_311_tables_columns <.. ssas.model_json_311_tables_columns_T
ssas.model_json_311_tables_columns_T <.. ssas.IndexColumn_from_IsKey
ssas.model_json_311_tables_columns_T <.. ssas.IndexColumn_from_Relationship
ssas.model_json_311_tables_columns_T <.. ssas.IndexColumn_from_IsUnique
ssas.model_json_311_tables_columns_T <.. repo.RepoObjectColumn_SSAS_src
ssas.model_json_311_tables_columns_T <.. repo.ForeignKey_ssas_IndexPattern
ssas.model_json_316_tables_descriptions_multiline <.. ssas.model_json_3161_tables_descriptions_StrAgg
ssas.model_json_316_tables_descriptions_multiline <.. ssas.model_json_3161_tables_descriptions_StrAgg
ssas.model_json_316_tables_descriptions_multiline <.. ssas.model_json_3161_tables_descriptions_StrAgg
ssas.model_json_3161_tables_descriptions_StrAgg <.. repo.RepoObject_gross
ssas.model_json_3161_tables_descriptions_StrAgg <.. repo.RepoObject_gross
ssas.model_json_3161_tables_descriptions_StrAgg <.. repo.RepoObject_gross
ssas.model_json_32_relationships <.. ssas.model_json_32_relationships_T
ssas.model_json_32_relationships_T <.. ssas.IndexColumn_from_Relationship
ssas.model_json_32_relationships_T <.. repo.ForeignKey_ssas_IndexPattern
sys_dwh.columns <.. repo_sys.ExtendedProperties
sys_dwh.columns <.. repo_sys.SysColumn
sys_dwh.computed_columns <.. repo_sys.SysColumn
sys_dwh.default_constraints <.. repo_sys.SysColumn
sys_dwh.extended_properties <.. repo_sys.ExtendedProperties
sys_dwh.foreign_key_columns <.. repo_sys.ForeignKeyColumn
sys_dwh.foreign_keys <.. repo_sys.ForeignKey
sys_dwh.identity_columns <.. repo_sys.SysColumn
sys_dwh.index_columns <.. repo_sys.IndexColumn_unique
sys_dwh.index_columns <.. repo_sys.IndexColumn_unique
sys_dwh.indexes <.. repo_sys.IndexColumn_unique
sys_dwh.indexes <.. repo_sys.IndexColumn_unique
sys_dwh.indexes <.. repo_sys.Index_unique
sys_dwh.indexes <.. repo_sys.ExtendedProperties
sys_dwh.objects <.. repo_sys.ExtendedProperties
sys_dwh.objects <.. repo_sys.SysObject
sys_dwh.parameters <.. repo_sys.ExtendedProperties
sys_dwh.schemas <.. repo_sys.ExtendedProperties
sys_dwh.schemas <.. repo_sys.SysObject
sys_dwh.sql_expression_dependencies <.. repo_sys.sql_expression_dependencies
sys_dwh.sql_expression_dependencies <.. repo_sys.sql_expression_dependencies
sys_dwh.sql_expression_dependencies <.. repo_sys.sql_expression_dependencies
sys_dwh.sql_modules <.. repo_sys.SysObject
sys_dwh.tables <.. repo_sys.SysObject
sys_dwh.types <.. repo_sys.SysColumn
footer
to view a reduced diagram in original size and to be able to click on the links:
open the diagram in a new tab via the Context menu.
end footer

@enduml

