@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity "puml-link:config.ftv_dwh_database.adoc[prefix=..]" as config.ftv_dwh_database << IF >> {
  --
}

entity "puml-link:config.Parameter.adoc[prefix=..]" as config.Parameter << U >> {
  - **Parameter_name** : (varchar(100))
  - **sub_Parameter** : (nvarchar(128))
  --
}

entity "puml-link:configT.spt_values.adoc[prefix=..]" as configT.spt_values << U >> {
  --
}

entity "puml-link:configT.type.adoc[prefix=..]" as configT.type << V >> {
  **type** : (nvarchar(128))
  --
}

entity "puml-link:configT.type_level1type_level2type.adoc[prefix=..]" as configT.type_level1type_level2type << V >> {
  **type** : (nvarchar(128))
  --
}

entity "puml-link:repo_sys.ExtendedProperties.adoc[prefix=..]" as repo_sys.ExtendedProperties << V >> {
  --
}

entity "puml-link:repo_sys.ExtendedProperties_ParameterForAddUpdateDrop.adoc[prefix=..]" as repo_sys.ExtendedProperties_ParameterForAddUpdateDrop << V >> {
  --
}

entity "puml-link:sys_dwh.columns.adoc[prefix=..]" as sys_dwh.columns << SN >> {
  --
}

entity "puml-link:sys_dwh.extended_properties.adoc[prefix=..]" as sys_dwh.extended_properties << SN >> {
  --
}

entity "puml-link:sys_dwh.indexes.adoc[prefix=..]" as sys_dwh.indexes << SN >> {
  --
}

entity "puml-link:sys_dwh.objects.adoc[prefix=..]" as sys_dwh.objects << SN >> {
  --
}

entity "puml-link:sys_dwh.parameters.adoc[prefix=..]" as sys_dwh.parameters << SN >> {
  --
}

entity "puml-link:sys_dwh.schemas.adoc[prefix=..]" as sys_dwh.schemas << SN >> {
  --
}

config.ftv_dwh_database <.. repo_sys.ExtendedProperties
config.Parameter <.. config.ftv_dwh_database
configT.spt_values <.. configT.type
configT.type <.. configT.type_level1type_level2type
configT.type_level1type_level2type <.. repo_sys.ExtendedProperties_ParameterForAddUpdateDrop
repo_sys.ExtendedProperties <.. repo_sys.ExtendedProperties_ParameterForAddUpdateDrop
sys_dwh.columns <.. repo_sys.ExtendedProperties
sys_dwh.extended_properties <.. repo_sys.ExtendedProperties
sys_dwh.indexes <.. repo_sys.ExtendedProperties
sys_dwh.objects <.. repo_sys.ExtendedProperties
sys_dwh.objects <.. repo_sys.ExtendedProperties_ParameterForAddUpdateDrop
sys_dwh.parameters <.. repo_sys.ExtendedProperties
sys_dwh.schemas <.. repo_sys.ExtendedProperties
footer
to view a reduced diagram in original size and to be able to click on the links:
open the diagram in a new tab via the Context menu.
end footer

@enduml

