@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity "[[{site-url}/{page-component-name}/current/{page-module}/configT.SsasDmv_ExplicitDataType.html configT.SsasDmv_ExplicitDataType]]" as configT.SsasDmv_ExplicitDataType << V >> {
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/repo.ForeignKey_ssas_Indexes_old.html repo.ForeignKey_ssas_Indexes_old]]" as repo.ForeignKey_ssas_Indexes_old << V >> {
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/repo.ForeignKey_ssas_IndexPattern_old.html repo.ForeignKey_ssas_IndexPattern_old]]" as repo.ForeignKey_ssas_IndexPattern_old << V >> {
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/repo.Index_ssas.html repo.Index_ssas]]" as repo.Index_ssas << V >> {
  - **databasename** : (nvarchar(128))
  **index_name** : (nvarchar(450))
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/repo.Index_ssas_T.html repo.Index_ssas_T]]" as repo.Index_ssas_T << U >> {
  - **databasename** : (nvarchar(128))
  **index_name** : (nvarchar(450))
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/ssas.IndexColumn_from_IsKey.html ssas.IndexColumn_from_IsKey]]" as ssas.IndexColumn_from_IsKey << V >> {
  - **databasename** : (nvarchar(128))
  - **TableName** : (nvarchar(128))
  - **tables_columns_name** : (nvarchar(128))
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/ssas.IndexColumn_from_IsUnique.html ssas.IndexColumn_from_IsUnique]]" as ssas.IndexColumn_from_IsUnique << V >> {
  - **databasename** : (nvarchar(128))
  - **TableName** : (nvarchar(128))
  - **tables_columns_name** : (nvarchar(128))
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/ssas.IndexColumn_from_Relationship.html ssas.IndexColumn_from_Relationship]]" as ssas.IndexColumn_from_Relationship << V >> {
  - **databasename** : (nvarchar(128))
  - **TableName** : (nvarchar(128))
  - **tables_columns_name** : (nvarchar(128))
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/ssas.IndexColumn_union.html ssas.IndexColumn_union]]" as ssas.IndexColumn_union << V >> {
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/ssas.model_json.html ssas.model_json]]" as ssas.model_json << U >> {
  - **databasename** : (nvarchar(128))
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/ssas.model_json_10.html ssas.model_json_10]]" as ssas.model_json_10 << V >> {
  - **databasename** : (nvarchar(128))
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/ssas.model_json_20.html ssas.model_json_20]]" as ssas.model_json_20 << V >> {
  - **databasename** : (nvarchar(128))
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/ssas.model_json_31_tables.html ssas.model_json_31_tables]]" as ssas.model_json_31_tables << V >> {
  - **databasename** : (nvarchar(128))
  **tables_name** : (nvarchar(128))
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/ssas.model_json_31_tables_T.html ssas.model_json_31_tables_T]]" as ssas.model_json_31_tables_T << U >> {
  - **databasename** : (nvarchar(128))
  **tables_name** : (nvarchar(128))
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/ssas.model_json_311_tables_columns.html ssas.model_json_311_tables_columns]]" as ssas.model_json_311_tables_columns << V >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  **tables_columns_name** : (nvarchar(128))
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/ssas.model_json_311_tables_columns_T.html ssas.model_json_311_tables_columns_T]]" as ssas.model_json_311_tables_columns_T << U >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  **tables_columns_name** : (nvarchar(128))
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/ssas.model_json_32_relationships.html ssas.model_json_32_relationships]]" as ssas.model_json_32_relationships << V >> {
  - **databasename** : (nvarchar(128))
  **relationships_name** : (nvarchar(500))
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/ssas.model_json_32_relationships_T.html ssas.model_json_32_relationships_T]]" as ssas.model_json_32_relationships_T << U >> {
  - **ForeignKey_guid** : (uniqueidentifier)
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/ssas.TMSCHEMA_COLUMNS.html ssas.TMSCHEMA_COLUMNS]]" as ssas.TMSCHEMA_COLUMNS << U >> {
  - **databasename** : (nvarchar(128))
  - **ID** : (numeric(20, 0))
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/ssas.TMSCHEMA_COLUMNS_T.html ssas.TMSCHEMA_COLUMNS_T]]" as ssas.TMSCHEMA_COLUMNS_T << U >> {
  - **databasename** : (nvarchar(128))
  - **ID** : (numeric(20, 0))
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/ssas.TMSCHEMA_RELATIONSHIPS.html ssas.TMSCHEMA_RELATIONSHIPS]]" as ssas.TMSCHEMA_RELATIONSHIPS << U >> {
  - **databasename** : (nvarchar(128))
  - **ID** : (numeric(20, 0))
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/ssas.TMSCHEMA_RELATIONSHIPS_T.html ssas.TMSCHEMA_RELATIONSHIPS_T]]" as ssas.TMSCHEMA_RELATIONSHIPS_T << U >> {
  - **databasename** : (nvarchar(128))
  - **ID** : (numeric(20, 0))
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/ssas.TMSCHEMA_TABLES.html ssas.TMSCHEMA_TABLES]]" as ssas.TMSCHEMA_TABLES << U >> {
  - **databasename** : (nvarchar(128))
  - **ID** : (numeric(20, 0))
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/ssas.TMSCHEMA_TABLES_T.html ssas.TMSCHEMA_TABLES_T]]" as ssas.TMSCHEMA_TABLES_T << U >> {
  - **databasename** : (nvarchar(128))
  - **ID** : (numeric(20, 0))
  --
}

configT.SsasDmv_ExplicitDataType <.. repo.ForeignKey_ssas_IndexPattern_old
repo.ForeignKey_ssas_IndexPattern_old <.. repo.ForeignKey_ssas_Indexes_old
repo.Index_ssas <.. repo.Index_ssas_T
repo.Index_ssas_T <.. repo.ForeignKey_ssas_Indexes_old
ssas.IndexColumn_from_IsKey <.. ssas.IndexColumn_union
ssas.IndexColumn_from_IsUnique <.. ssas.IndexColumn_union
ssas.IndexColumn_from_Relationship <.. ssas.IndexColumn_union
ssas.IndexColumn_union <.. repo.Index_ssas
ssas.model_json <.. ssas.model_json_10
ssas.model_json_10 <.. ssas.model_json_20
ssas.model_json_20 <.. ssas.model_json_32_relationships
ssas.model_json_20 <.. ssas.model_json_31_tables
ssas.model_json_20 <.. ssas.model_json_31_tables
ssas.model_json_20 <.. ssas.model_json_31_tables
ssas.model_json_31_tables <.. ssas.model_json_31_tables_T
ssas.model_json_31_tables <.. ssas.model_json_31_tables_T
ssas.model_json_31_tables <.. ssas.model_json_31_tables_T
ssas.model_json_31_tables_T <.. ssas.model_json_311_tables_columns
ssas.model_json_31_tables_T <.. ssas.model_json_311_tables_columns
ssas.model_json_31_tables_T <.. ssas.model_json_311_tables_columns
ssas.model_json_311_tables_columns <.. ssas.model_json_311_tables_columns_T
ssas.model_json_311_tables_columns <.. ssas.model_json_311_tables_columns_T
ssas.model_json_311_tables_columns <.. ssas.model_json_311_tables_columns_T
ssas.model_json_311_tables_columns_T <.. ssas.IndexColumn_from_IsUnique
ssas.model_json_311_tables_columns_T <.. ssas.IndexColumn_from_IsKey
ssas.model_json_311_tables_columns_T <.. ssas.IndexColumn_from_Relationship
ssas.model_json_32_relationships <.. ssas.model_json_32_relationships_T
ssas.model_json_32_relationships_T <.. ssas.IndexColumn_from_Relationship
ssas.TMSCHEMA_COLUMNS <.. ssas.TMSCHEMA_COLUMNS_T
ssas.TMSCHEMA_COLUMNS_T <.. repo.ForeignKey_ssas_IndexPattern_old
ssas.TMSCHEMA_RELATIONSHIPS <.. ssas.TMSCHEMA_RELATIONSHIPS_T
ssas.TMSCHEMA_RELATIONSHIPS_T <.. repo.ForeignKey_ssas_IndexPattern_old
ssas.TMSCHEMA_TABLES <.. ssas.TMSCHEMA_TABLES_T
ssas.TMSCHEMA_TABLES_T <.. repo.ForeignKey_ssas_IndexPattern_old
footer
to view a reduced diagram in original size and to be able to click on the links:
open the diagram in a new tab via the Context menu.
end footer

@enduml

