@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity "puml-link:config.fs_dwh_database_name.adoc[prefix=..]" as config.fs_dwh_database_name << FN >> {
  --
}

entity "puml-link:config.Parameter.adoc[prefix=..]" as config.Parameter << U >> {
  - **Parameter_name** : (varchar(100))
  - **sub_Parameter** : (nvarchar(128))
  --
}

entity "puml-link:configT.spt_values.adoc[prefix=..]" as configT.spt_values << U >> {
  --
}

entity "puml-link:configT.type.adoc[prefix=..]" as configT.type << V >> {
  **type** : (nvarchar(128))
  --
}

entity "puml-link:configT.type_level1type_level2type.adoc[prefix=..]" as configT.type_level1type_level2type << V >> {
  **type** : (nvarchar(128))
  --
}

entity "puml-link:repo_sys.usp_dropextendedproperty_level_2.adoc[prefix=..]" as repo_sys.usp_dropextendedproperty_level_2 << P >> {
  --
}

entity "puml-link:sys_self.ExtendedProperties.adoc[prefix=..]" as sys_self.ExtendedProperties << V >> {
  --
}

entity "puml-link:sys_self.ExtendedProperties_ParameterForAddUpdateDrop.adoc[prefix=..]" as sys_self.ExtendedProperties_ParameterForAddUpdateDrop << V >> {
  --
}

config.fs_dwh_database_name <.. repo_sys.usp_dropextendedproperty_level_2
config.Parameter <.. config.fs_dwh_database_name
configT.spt_values <.. configT.type
configT.type <.. configT.type_level1type_level2type
configT.type_level1type_level2type <.. sys_self.ExtendedProperties_ParameterForAddUpdateDrop
sys_self.ExtendedProperties <.. sys_self.ExtendedProperties_ParameterForAddUpdateDrop
sys_self.ExtendedProperties_ParameterForAddUpdateDrop <.. repo_sys.usp_dropextendedproperty_level_2
footer
to view a reduced diagram in original size and to be able to click on the links:
open the diagram in a new tab via the Context menu.
end footer

@enduml

