'Left to right direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity config.fs_dwh_database_name << FN >> {
  --
}

entity config.fs_get_parameter_value << FN >> {
  --
}

entity config.ftv_dwh_database << IF >> {
  --
}

entity config.ftv_get_parameter_value << IF >> {
  --
}

entity config.Parameter << U >> {
  * **Parameter_name** : varchar(100)
  * **sub_Parameter** : nvarchar(128)
  --
}

entity configT.spt_values << U >> {
  --
}

entity configT.type << V >> {
  **type** : nvarchar(128)
  --
}

entity configT.type_level1type_level2type << V >> {
  **type** : nvarchar(128)
  --
}

entity logs.ExecutionLog << U >> {
  --
}

entity logs.usp_ExecutionLog_insert << P >> {
  --
}

entity reference.RepoObjectColumnSource_virtual << U >> {
  * **RepoObjectColumn_guid** : uniqueidentifier
  * **Source_RepoObjectColumn_guid** : uniqueidentifier
  --
}

entity reference.RepoObjectSource_virtual << U >> {
  * **RepoObject_guid** : uniqueidentifier
  * **Source_RepoObject_guid** : uniqueidentifier
  --
}

entity repo.IndexColumn_virtual << U >> {
  * **index_guid** : uniqueidentifier
  * **index_column_id** : int
  --
}

entity repo.RepoObject << U >> {
  * **RepoObject_guid** : uniqueidentifier
  --
}

entity repo.RepoObject_persistence << U >> {
  * **target_RepoObject_guid** : uniqueidentifier
  --
}

entity repo.RepoObject_RequiredRepoObjectMerge << V >> {
  * **RepoObject_guid** : uniqueidentifier
  --
}

entity repo.RepoObjectColumn << U >> {
  * **RepoObjectColumn_guid** : uniqueidentifier
  --
}

entity repo.RepoObjectColumn_HistValidColums_setpoint << V >> {
  * **RepoObject_guid** : uniqueidentifier
  **RepoObjectColumn_name** : sysname
  --
}

entity repo.RepoObjectColumn_RequiredRepoObjectColumnMerge << V >> {
  --
}

entity repo.RepoSchema << U >> {
  * **RepoSchema_guid** : uniqueidentifier
  --
}

entity repo.SysColumn_RepoObjectColumn_via_guid << V >> {
  --
}

entity repo.SysColumn_RepoObjectColumn_via_name << V >> {
  --
}

entity repo.SysObject_RepoObject_via_guid << V >> {
  --
}

entity repo.SysObject_RepoObject_via_name << V >> {
  --
}

entity repo.SysSchema_RepoSchema_via_guid << V >> {
  --
}

entity repo.SysSchema_RepoSchema_via_name << V >> {
  --
}

entity repo.usp_sync_guid << P >> {
  --
}

entity repo.usp_sync_guid_RepoObject << P >> {
  --
}

entity repo.usp_sync_guid_RepoObjectColumn << P >> {
  --
}

entity repo.usp_sync_guid_RepoSchema << P >> {
  --
}

entity repo_sys.ExtendedProperties << V >> {
  --
}

entity repo_sys.SysColumn << V >> {
  --
}

entity repo_sys.SysObject << V >> {
  --
}

entity repo_sys.SysSchema << V >> {
  --
}

entity repo_sys.usp_AddOrUpdateExtendedProperty << P >> {
  --
}

entity sys_dwh.columns << SN >> {
  --
}

entity sys_dwh.computed_columns << SN >> {
  --
}

entity sys_dwh.default_constraints << SN >> {
  --
}

entity sys_dwh.extended_properties << SN >> {
  --
}

entity sys_dwh.identity_columns << SN >> {
  --
}

entity sys_dwh.indexes << SN >> {
  --
}

entity sys_dwh.objects << SN >> {
  --
}

entity sys_dwh.parameters << SN >> {
  --
}

entity sys_dwh.schemas << SN >> {
  --
}

entity sys_dwh.sql_modules << SN >> {
  --
}

entity sys_dwh.tables << SN >> {
  --
}

entity sys_dwh.types << SN >> {
  --
}

config.fs_dwh_database_name <.. repo_sys.usp_AddOrUpdateExtendedProperty
config.fs_get_parameter_value <.. repo.usp_sync_guid_RepoObjectColumn
config.fs_get_parameter_value <.. repo.usp_sync_guid_RepoObject
config.fs_get_parameter_value <.. repo.usp_sync_guid_RepoSchema
config.ftv_dwh_database <.. repo_sys.SysColumn
config.ftv_dwh_database <.. repo_sys.ExtendedProperties
config.ftv_get_parameter_value <.. repo.RepoObjectColumn_HistValidColums_setpoint
config.Parameter <.. config.ftv_dwh_database
config.Parameter <.. config.ftv_get_parameter_value
config.Parameter <.. config.fs_get_parameter_value
config.Parameter <.. config.fs_dwh_database_name
configT.spt_values <.. configT.type
configT.type <.. configT.type_level1type_level2type
configT.type_level1type_level2type <.. repo.usp_sync_guid_RepoObjectColumn
configT.type_level1type_level2type <.. repo.usp_sync_guid_RepoObject
logs.ExecutionLog <.. logs.usp_ExecutionLog_insert
logs.usp_ExecutionLog_insert <.. repo.usp_sync_guid_RepoObject
logs.usp_ExecutionLog_insert <.. repo.usp_sync_guid_RepoObjectColumn
logs.usp_ExecutionLog_insert <.. repo.usp_sync_guid
logs.usp_ExecutionLog_insert <.. repo.usp_sync_guid_RepoSchema
reference.RepoObjectColumnSource_virtual <.. repo.usp_sync_guid_RepoObjectColumn
reference.RepoObjectSource_virtual <.. repo.usp_sync_guid_RepoObject
repo.IndexColumn_virtual <.. repo.usp_sync_guid_RepoObjectColumn
repo.RepoObject <.. repo.SysColumn_RepoObjectColumn_via_name
repo.RepoObject <.. repo.SysColumn_RepoObjectColumn_via_guid
repo.RepoObject <.. repo.SysObject_RepoObject_via_guid
repo.RepoObject <.. repo.SysObject_RepoObject_via_name
repo.RepoObject <.. repo.usp_sync_guid_RepoObject
repo.RepoObject <.. repo.usp_sync_guid_RepoObjectColumn
repo.RepoObject <.. repo.RepoObject_RequiredRepoObjectMerge
repo.RepoObject_persistence <.. repo.RepoObjectColumn_HistValidColums_setpoint
repo.RepoObject_persistence <.. repo.usp_sync_guid_RepoObject
repo.RepoObject_persistence <.. repo.usp_sync_guid_RepoObjectColumn
repo.RepoObject_RequiredRepoObjectMerge <.. repo.usp_sync_guid_RepoObject
repo.RepoObjectColumn <.. repo.RepoObjectColumn_RequiredRepoObjectColumnMerge
repo.RepoObjectColumn <.. repo.usp_sync_guid_RepoObjectColumn
repo.RepoObjectColumn <.. repo.SysColumn_RepoObjectColumn_via_guid
repo.RepoObjectColumn <.. repo.SysColumn_RepoObjectColumn_via_name
repo.RepoObjectColumn_HistValidColums_setpoint <.. repo.usp_sync_guid_RepoObjectColumn
repo.RepoObjectColumn_RequiredRepoObjectColumnMerge <.. repo.usp_sync_guid_RepoObjectColumn
repo.RepoSchema <.. repo.SysSchema_RepoSchema_via_guid
repo.RepoSchema <.. repo.SysSchema_RepoSchema_via_name
repo.RepoSchema <.. repo.usp_sync_guid_RepoSchema
repo.SysColumn_RepoObjectColumn_via_guid <.. repo.usp_sync_guid_RepoObjectColumn
repo.SysColumn_RepoObjectColumn_via_name <.. repo.usp_sync_guid_RepoObjectColumn
repo.SysObject_RepoObject_via_guid <.. repo.usp_sync_guid_RepoObject
repo.SysObject_RepoObject_via_name <.. repo.usp_sync_guid_RepoObject
repo.SysSchema_RepoSchema_via_guid <.. repo.usp_sync_guid_RepoSchema
repo.SysSchema_RepoSchema_via_name <.. repo.usp_sync_guid_RepoSchema
repo.usp_sync_guid_RepoObject <.. repo.usp_sync_guid
repo.usp_sync_guid_RepoObjectColumn <.. repo.usp_sync_guid
repo.usp_sync_guid_RepoSchema <.. repo.usp_sync_guid
repo_sys.ExtendedProperties <.. repo_sys.SysColumn
repo_sys.ExtendedProperties <.. repo_sys.SysSchema
repo_sys.ExtendedProperties <.. repo_sys.SysObject
repo_sys.SysColumn <.. repo.SysColumn_RepoObjectColumn_via_guid
repo_sys.SysColumn <.. repo.usp_sync_guid_RepoObjectColumn
repo_sys.SysColumn <.. repo.SysColumn_RepoObjectColumn_via_name
repo_sys.SysObject <.. repo.SysObject_RepoObject_via_name
repo_sys.SysObject <.. repo.SysObject_RepoObject_via_guid
repo_sys.SysObject <.. repo.usp_sync_guid_RepoObject
repo_sys.SysObject <.. repo_sys.SysColumn
repo_sys.SysSchema <.. repo.SysSchema_RepoSchema_via_name
repo_sys.SysSchema <.. repo.usp_sync_guid_RepoSchema
repo_sys.SysSchema <.. repo.SysSchema_RepoSchema_via_guid
repo_sys.usp_AddOrUpdateExtendedProperty <.. repo.usp_sync_guid_RepoObjectColumn
repo_sys.usp_AddOrUpdateExtendedProperty <.. repo.usp_sync_guid_RepoSchema
repo_sys.usp_AddOrUpdateExtendedProperty <.. repo.usp_sync_guid_RepoObject
sys_dwh.columns <.. repo_sys.ExtendedProperties
sys_dwh.columns <.. repo_sys.SysColumn
sys_dwh.computed_columns <.. repo_sys.SysColumn
sys_dwh.default_constraints <.. repo_sys.SysColumn
sys_dwh.extended_properties <.. repo_sys.ExtendedProperties
sys_dwh.identity_columns <.. repo_sys.SysColumn
sys_dwh.indexes <.. repo_sys.ExtendedProperties
sys_dwh.objects <.. repo_sys.SysObject
sys_dwh.objects <.. repo_sys.ExtendedProperties
sys_dwh.parameters <.. repo_sys.ExtendedProperties
sys_dwh.schemas <.. repo_sys.ExtendedProperties
sys_dwh.schemas <.. repo_sys.SysObject
sys_dwh.schemas <.. repo_sys.SysSchema
sys_dwh.sql_modules <.. repo_sys.SysObject
sys_dwh.tables <.. repo_sys.SysObject
sys_dwh.types <.. repo_sys.SysColumn
