'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity repo.RepoObject << U >> {
  * **RepoObject_guid** : uniqueidentifier
  --
}

entity repo.RepoObject_SSAS_src << V >> {
  * **RepoObject_guid** : uniqueidentifier
  --
}

entity repo.RepoObject_SSAS_tgt << V >> {
  * **RepoObject_guid** : uniqueidentifier
  --
}

entity repo.RepoObjectColumn << U >> {
  * **RepoObjectColumn_guid** : uniqueidentifier
  --
}

entity repo.RepoObjectColumn_SSAS_src << V >> {
  * **RepoObjectColumn_guid** : uniqueidentifier
  --
}

entity repo.RepoObjectColumn_SSAS_tgt << V >> {
  * **RepoObjectColumn_guid** : uniqueidentifier
  --
}

entity sqlparse.RepoObject_SqlModules << U >> {
  * **RepoObject_guid** : uniqueidentifier
  --
}

entity sqlparse.RepoObject_SqlModules_10_statement << V >> {
  * **RepoObject_guid** : uniqueidentifier
  --
}

entity ssas.model_json << U >> {
  * **databasename** : nvarchar(128)
  --
}

entity ssas.model_json_10 << V >> {
  * **databasename** : nvarchar(128)
  --
}

entity ssas.model_json_20 << V >> {
  * **databasename** : nvarchar(128)
  --
}

entity ssas.model_json_31_tables << V >> {
  * **databasename** : nvarchar(128)
  **tables_name** : nvarchar(128)
  --
}

entity ssas.model_json_31_tables_T << U >> {
  * **databasename** : nvarchar(128)
  **tables_name** : nvarchar(128)
  --
}

entity ssas.model_json_311_tables_columns << V >> {
  * **databasename** : nvarchar(128)
  * **tables_name** : nvarchar(128)
  **tables_columns_name** : nvarchar(128)
  --
}

entity ssas.model_json_311_tables_columns_T << U >> {
  * **databasename** : nvarchar(128)
  * **tables_name** : nvarchar(128)
  **tables_columns_name** : nvarchar(128)
  --
}

repo.RepoObject <.. repo.RepoObject_SSAS_tgt
repo.RepoObject <.. sqlparse.RepoObject_SqlModules_10_statement
repo.RepoObject_SSAS_src <.. repo.RepoObject_SSAS_tgt
repo.RepoObject_SSAS_tgt <.. repo.RepoObject
repo.RepoObject_SSAS_tgt <.. repo.RepoObjectColumn_SSAS_tgt
repo.RepoObjectColumn <.. repo.RepoObjectColumn_SSAS_tgt
repo.RepoObjectColumn_SSAS_src <.. repo.RepoObjectColumn_SSAS_tgt
repo.RepoObjectColumn_SSAS_tgt <.. repo.RepoObjectColumn
repo.RepoObjectColumn_SSAS_tgt <.. repo.RepoObject_SSAS_tgt
sqlparse.RepoObject_SqlModules <.. sqlparse.RepoObject_SqlModules_10_statement
ssas.model_json <.. ssas.model_json_10
ssas.model_json_10 <.. ssas.model_json_20
ssas.model_json_20 <.. ssas.model_json_31_tables
ssas.model_json_31_tables <.. ssas.model_json_31_tables_T
ssas.model_json_31_tables_T <.. ssas.model_json_311_tables_columns
ssas.model_json_31_tables_T <.. repo.RepoObject_SSAS_src
ssas.model_json_311_tables_columns <.. ssas.model_json_311_tables_columns_T
ssas.model_json_311_tables_columns_T <.. repo.RepoObjectColumn_SSAS_src
