'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity ssas.model_json << U >> {
  * **databasename** : nvarchar(128)
  --
}

entity ssas.model_json_10 << V >> {
  * **databasename** : nvarchar(128)
  --
}

entity ssas.model_json_20 << V >> {
  * **databasename** : nvarchar(128)
  --
}

entity ssas.model_json_35_roles << V >> {
  * **databasename** : nvarchar(128)
  **roles_name** : nvarchar(500)
  --
}

entity ssas.model_json_351_roles_members << V >> {
  * **databasename** : nvarchar(128)
  **roles_name** : nvarchar(500)
  **roles_members_memberId** : nvarchar(500)
  --
}

ssas.model_json <.. ssas.model_json_10
ssas.model_json_10 <.. ssas.model_json_20
ssas.model_json_20 <.. ssas.model_json_35_roles
ssas.model_json_35_roles <.. ssas.model_json_351_roles_members
