@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity "[[{site-url}/{page-component-name}/current/{page-module}/uspgenerator.ftv_GeneratorUspStep_sql.html uspgenerator.ftv_GeneratorUspStep_sql]]" as uspgenerator.ftv_GeneratorUspStep_sql << IF >> {
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/uspgenerator.ftv_GeneratorUspStep_tree.html uspgenerator.ftv_GeneratorUspStep_tree]]" as uspgenerator.ftv_GeneratorUspStep_tree << IF >> {
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/uspgenerator.GeneratorUsp.html uspgenerator.GeneratorUsp]]" as uspgenerator.GeneratorUsp << U >> {
  - **id** : (int)
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/uspgenerator.GeneratorUsp_StepList.html uspgenerator.GeneratorUsp_StepList]]" as uspgenerator.GeneratorUsp_StepList << V >> {
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/uspgenerator.GeneratorUspStep.html uspgenerator.GeneratorUspStep]]" as uspgenerator.GeneratorUspStep << U >> {
  - **id** : (int)
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/uspgenerator.GeneratorUspStep_Sql.html uspgenerator.GeneratorUspStep_Sql]]" as uspgenerator.GeneratorUspStep_Sql << V >> {
  - **usp_id** : (int)
  **Number** : (int)
  --
}

uspgenerator.ftv_GeneratorUspStep_sql <.. uspgenerator.GeneratorUspStep_Sql
uspgenerator.ftv_GeneratorUspStep_tree <.. uspgenerator.GeneratorUspStep_Sql
uspgenerator.GeneratorUsp <.. uspgenerator.GeneratorUspStep_Sql
uspgenerator.GeneratorUspStep <.. uspgenerator.GeneratorUspStep_Sql
uspgenerator.GeneratorUspStep <.. uspgenerator.ftv_GeneratorUspStep_tree
uspgenerator.GeneratorUspStep <.. uspgenerator.ftv_GeneratorUspStep_sql
uspgenerator.GeneratorUspStep_Sql <.. uspgenerator.GeneratorUsp_StepList
footer
to view a reduced diagram in original size and to be able to click on the links:
open the diagram in a new tab via the Context menu.
end footer

@enduml

