@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity "[[{site-url}/{page-component-name}/current/{page-module}/config.fs_get_parameter_value.html config.fs_get_parameter_value]]" as config.fs_get_parameter_value << FN >> {
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/config.ftv_dwh_database.html config.ftv_dwh_database]]" as config.ftv_dwh_database << IF >> {
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/config.Parameter.html config.Parameter]]" as config.Parameter << U >> {
  - **Parameter_name** : (varchar(100))
  - **sub_Parameter** : (nvarchar(128))
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/configT.spt_values.html configT.spt_values]]" as configT.spt_values << U >> {
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/configT.type.html configT.type]]" as configT.type << V >> {
  **type** : (nvarchar(128))
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/property.fs_get_RepoObjectProperty_nvarchar.html property.fs_get_RepoObjectProperty_nvarchar]]" as property.fs_get_RepoObjectProperty_nvarchar << FN >> {
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/property.RepoObjectProperty.html property.RepoObjectProperty]]" as property.RepoObjectProperty << U >> {
  - **RepoObjectProperty_id** : (int)
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/reference.additional_Reference.html reference.additional_Reference]]" as reference.additional_Reference << U >> {
  - **Id** : (int)
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/reference.additional_Reference_guid.html reference.additional_Reference_guid]]" as reference.additional_Reference_guid << V >> {
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/reference.Persistence.html reference.Persistence]]" as reference.Persistence << V >> {
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/reference.RepoObject_QueryPlan.html reference.RepoObject_QueryPlan]]" as reference.RepoObject_QueryPlan << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/reference.RepoObject_reference.html reference.RepoObject_reference]]" as reference.RepoObject_reference << V >> {
  **referenced_RepoObject_guid** : (uniqueidentifier)
  **referencing_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/reference.RepoObject_reference_additional_internal.html reference.RepoObject_reference_additional_internal]]" as reference.RepoObject_reference_additional_internal << V >> {
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/reference.RepoObject_reference_persistence.html reference.RepoObject_reference_persistence]]" as reference.RepoObject_reference_persistence << V >> {
  **referenced_RepoObject_guid** : (uniqueidentifier)
  - **referencing_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/reference.RepoObject_reference_persistence_target_as_source.html reference.RepoObject_reference_persistence_target_as_source]]" as reference.RepoObject_reference_persistence_target_as_source << V >> {
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/reference.RepoObject_reference_SqlExpressionDependencies.html reference.RepoObject_reference_SqlExpressionDependencies]]" as reference.RepoObject_reference_SqlExpressionDependencies << V >> {
  **referenced_RepoObject_guid** : (uniqueidentifier)
  **referencing_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/reference.RepoObject_reference_T.html reference.RepoObject_reference_T]]" as reference.RepoObject_reference_T << U >> {
  **referenced_RepoObject_guid** : (uniqueidentifier)
  **referencing_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/reference.RepoObject_reference_union.html reference.RepoObject_reference_union]]" as reference.RepoObject_reference_union << V >> {
  **referenced_RepoObject_guid** : (uniqueidentifier)
  **referencing_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/reference.RepoObject_reference_virtual.html reference.RepoObject_reference_virtual]]" as reference.RepoObject_reference_virtual << V >> {
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/reference.RepoObject_ReferenceTree.html reference.RepoObject_ReferenceTree]]" as reference.RepoObject_ReferenceTree << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  **Referenced_Depth** : (int)
  **Referencing_Depth** : (int)
  - **Referenced_guid** : (uniqueidentifier)
  - **Referencing_guid** : (uniqueidentifier)
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/reference.RepoObject_ReferencingReferenced.html reference.RepoObject_ReferencingReferenced]]" as reference.RepoObject_ReferencingReferenced << V >> {
  - **Referenced_guid** : (uniqueidentifier)
  - **Referencing_guid** : (uniqueidentifier)
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/reference.RepoObjectSource_virtual.html reference.RepoObjectSource_virtual]]" as reference.RepoObjectSource_virtual << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **Source_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/repo.Index_Settings.html repo.Index_Settings]]" as repo.Index_Settings << U >> {
  - **index_guid** : (uniqueidentifier)
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/repo.RepoObject.html repo.RepoObject]]" as repo.RepoObject << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/repo.RepoObject_gross.html repo.RepoObject_gross]]" as repo.RepoObject_gross << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/repo.RepoObject_persistence.html repo.RepoObject_persistence]]" as repo.RepoObject_persistence << U >> {
  - **target_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/repo.RepoObject_SSAS_src.html repo.RepoObject_SSAS_src]]" as repo.RepoObject_SSAS_src << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/repo.RepoObject_SSAS_tgt.html repo.RepoObject_SSAS_tgt]]" as repo.RepoObject_SSAS_tgt << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/repo.RepoObjectColumn.html repo.RepoObjectColumn]]" as repo.RepoObjectColumn << U >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/repo.RepoObjectColumn_SSAS_src.html repo.RepoObjectColumn_SSAS_src]]" as repo.RepoObjectColumn_SSAS_src << V >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/repo.RepoObjectColumn_SSAS_tgt.html repo.RepoObjectColumn_SSAS_tgt]]" as repo.RepoObjectColumn_SSAS_tgt << V >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/repo.SysColumn_RepoObjectColumn_via_name.html repo.SysColumn_RepoObjectColumn_via_name]]" as repo.SysColumn_RepoObjectColumn_via_name << V >> {
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/repo.SysObject_RepoObject_via_name.html repo.SysObject_RepoObject_via_name]]" as repo.SysObject_RepoObject_via_name << V >> {
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/repo_sys.ExtendedProperties.html repo_sys.ExtendedProperties]]" as repo_sys.ExtendedProperties << V >> {
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/repo_sys.sql_expression_dependencies.html repo_sys.sql_expression_dependencies]]" as repo_sys.sql_expression_dependencies << V >> {
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/repo_sys.SysColumn.html repo_sys.SysColumn]]" as repo_sys.SysColumn << V >> {
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/repo_sys.SysObject.html repo_sys.SysObject]]" as repo_sys.SysObject << V >> {
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/ssas.model_json.html ssas.model_json]]" as ssas.model_json << U >> {
  - **databasename** : (nvarchar(128))
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/ssas.model_json_10.html ssas.model_json_10]]" as ssas.model_json_10 << V >> {
  - **databasename** : (nvarchar(128))
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/ssas.model_json_20.html ssas.model_json_20]]" as ssas.model_json_20 << V >> {
  - **databasename** : (nvarchar(128))
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/ssas.model_json_31_tables.html ssas.model_json_31_tables]]" as ssas.model_json_31_tables << V >> {
  - **databasename** : (nvarchar(128))
  **tables_name** : (nvarchar(128))
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/ssas.model_json_31_tables_T.html ssas.model_json_31_tables_T]]" as ssas.model_json_31_tables_T << U >> {
  - **databasename** : (nvarchar(128))
  **tables_name** : (nvarchar(128))
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/ssas.model_json_311_tables_columns.html ssas.model_json_311_tables_columns]]" as ssas.model_json_311_tables_columns << V >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  **tables_columns_name** : (nvarchar(128))
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/ssas.model_json_311_tables_columns_T.html ssas.model_json_311_tables_columns_T]]" as ssas.model_json_311_tables_columns_T << U >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  **tables_columns_name** : (nvarchar(128))
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/ssas.model_json_316_tables_descriptions_multiline.html ssas.model_json_316_tables_descriptions_multiline]]" as ssas.model_json_316_tables_descriptions_multiline << V >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/ssas.model_json_3161_tables_descriptions_StrAgg.html ssas.model_json_3161_tables_descriptions_StrAgg]]" as ssas.model_json_3161_tables_descriptions_StrAgg << V >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/sys_dwh.columns.html sys_dwh.columns]]" as sys_dwh.columns << SN >> {
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/sys_dwh.computed_columns.html sys_dwh.computed_columns]]" as sys_dwh.computed_columns << SN >> {
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/sys_dwh.default_constraints.html sys_dwh.default_constraints]]" as sys_dwh.default_constraints << SN >> {
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/sys_dwh.extended_properties.html sys_dwh.extended_properties]]" as sys_dwh.extended_properties << SN >> {
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/sys_dwh.identity_columns.html sys_dwh.identity_columns]]" as sys_dwh.identity_columns << SN >> {
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/sys_dwh.indexes.html sys_dwh.indexes]]" as sys_dwh.indexes << SN >> {
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/sys_dwh.objects.html sys_dwh.objects]]" as sys_dwh.objects << SN >> {
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/sys_dwh.parameters.html sys_dwh.parameters]]" as sys_dwh.parameters << SN >> {
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/sys_dwh.schemas.html sys_dwh.schemas]]" as sys_dwh.schemas << SN >> {
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/sys_dwh.sql_expression_dependencies.html sys_dwh.sql_expression_dependencies]]" as sys_dwh.sql_expression_dependencies << SN >> {
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/sys_dwh.sql_modules.html sys_dwh.sql_modules]]" as sys_dwh.sql_modules << SN >> {
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/sys_dwh.tables.html sys_dwh.tables]]" as sys_dwh.tables << SN >> {
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/sys_dwh.types.html sys_dwh.types]]" as sys_dwh.types << SN >> {
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/workflow.ProcedureDependency.html workflow.ProcedureDependency]]" as workflow.ProcedureDependency << U >> {
  - **id** : (int)
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/workflow.ProcedureDependency_input_PersistenceDependency.html workflow.ProcedureDependency_input_PersistenceDependency]]" as workflow.ProcedureDependency_input_PersistenceDependency << V >> {
  **referenced_Procedure_RepoObject_guid** : (uniqueidentifier)
  **referencing_Procedure_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/workflow.ProcedureDependency_input_PersistenceDependency_S.html workflow.ProcedureDependency_input_PersistenceDependency_S]]" as workflow.ProcedureDependency_input_PersistenceDependency_S << V >> {
  **referenced_Procedure_RepoObject_guid** : (uniqueidentifier)
  **referencing_Procedure_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/workflow.Workflow.html workflow.Workflow]]" as workflow.Workflow << U >> {
  - **id** : (int)
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/workflow.Workflow_ProcedureDependency.html workflow.Workflow_ProcedureDependency]]" as workflow.Workflow_ProcedureDependency << V >> {
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/workflow.Workflow_ProcedureDependency_T.html workflow.Workflow_ProcedureDependency_T]]" as workflow.Workflow_ProcedureDependency_T << U >> {
  - **Workflow_id** : (int)
  - **referenced_Procedure_RepoObject_guid** : (uniqueidentifier)
  - **referencing_Procedure_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/workflow.Workflow_ProcedureDependency_T_active.html workflow.Workflow_ProcedureDependency_T_active]]" as workflow.Workflow_ProcedureDependency_T_active << V >> {
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/workflow.Workflow_ProcedureDependency_T_NotInSortorder.html workflow.Workflow_ProcedureDependency_T_NotInSortorder]]" as workflow.Workflow_ProcedureDependency_T_NotInSortorder << V >> {
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/workflow.WorkflowStep.html workflow.WorkflowStep]]" as workflow.WorkflowStep << U >> {
  - **id** : (int)
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/workflow.WorkflowStep_active.html workflow.WorkflowStep_active]]" as workflow.WorkflowStep_active << V >> {
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/workflow.WorkflowStep_S.html workflow.WorkflowStep_S]]" as workflow.WorkflowStep_S << V >> {
  - **Workflow_id** : (int)
  **Procedure_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/workflow.WorkflowStep_Sortorder.html workflow.WorkflowStep_Sortorder]]" as workflow.WorkflowStep_Sortorder << U >> {
  - **Workflow_id** : (int)
  - **Procedure_RepoObject_guid** : (uniqueidentifier)
  --
}

config.fs_get_parameter_value <.. reference.additional_Reference_guid
config.ftv_dwh_database <.. repo_sys.sql_expression_dependencies
config.ftv_dwh_database <.. repo_sys.ExtendedProperties
config.ftv_dwh_database <.. repo_sys.ExtendedProperties
config.ftv_dwh_database <.. repo_sys.SysColumn
config.Parameter <.. config.fs_get_parameter_value
config.Parameter <.. config.ftv_dwh_database
configT.spt_values <.. configT.type
configT.type <.. repo.RepoObject_gross
property.fs_get_RepoObjectProperty_nvarchar <.. repo.RepoObject_gross
property.RepoObjectProperty <.. property.fs_get_RepoObjectProperty_nvarchar
reference.additional_Reference <.. reference.additional_Reference_guid
reference.additional_Reference_guid <.. reference.RepoObject_reference_additional_internal
reference.Persistence <.. workflow.ProcedureDependency_input_PersistenceDependency_S
reference.RepoObject_QueryPlan <.. repo.RepoObject_gross
reference.RepoObject_reference <.. reference.RepoObject_reference_T
reference.RepoObject_reference_additional_internal <.. reference.RepoObject_reference_union
reference.RepoObject_reference_persistence <.. reference.RepoObject_reference_union
reference.RepoObject_reference_persistence_target_as_source <.. reference.RepoObject_reference_union
reference.RepoObject_reference_SqlExpressionDependencies <.. reference.RepoObject_reference_union
reference.RepoObject_reference_SqlExpressionDependencies <.. reference.RepoObject_reference_persistence_target_as_source
reference.RepoObject_reference_T <.. reference.RepoObject_ReferencingReferenced
reference.RepoObject_reference_union <.. reference.RepoObject_reference
reference.RepoObject_reference_virtual <.. reference.RepoObject_reference_union
reference.RepoObject_ReferenceTree <.. reference.Persistence
reference.RepoObject_ReferencingReferenced <.. repo.RepoObject_gross
reference.RepoObjectSource_virtual <.. reference.RepoObject_reference_virtual
repo.Index_Settings <.. repo.RepoObject_gross
repo.RepoObject <.. repo.RepoObject_SSAS_tgt
repo.RepoObject <.. reference.RepoObject_reference_virtual
repo.RepoObject <.. reference.RepoObject_reference_persistence
repo.RepoObject <.. reference.additional_Reference_guid
repo.RepoObject <.. repo.SysColumn_RepoObjectColumn_via_name
repo.RepoObject <.. repo.SysObject_RepoObject_via_name
repo.RepoObject <.. repo.RepoObject_gross
repo.RepoObject_gross <.. reference.Persistence
repo.RepoObject_gross <.. reference.RepoObject_reference_persistence_target_as_source
repo.RepoObject_gross <.. workflow.WorkflowStep_S
repo.RepoObject_persistence <.. reference.RepoObject_reference_persistence
repo.RepoObject_persistence <.. repo.RepoObject_gross
repo.RepoObject_SSAS_src <.. repo.RepoObject_SSAS_tgt
repo.RepoObject_SSAS_tgt <.. repo.RepoObject
repo.RepoObject_SSAS_tgt <.. repo.RepoObjectColumn_SSAS_tgt
repo.RepoObjectColumn <.. repo.RepoObjectColumn_SSAS_tgt
repo.RepoObjectColumn <.. repo.SysColumn_RepoObjectColumn_via_name
repo.RepoObjectColumn <.. reference.additional_Reference_guid
repo.RepoObjectColumn_SSAS_src <.. repo.RepoObjectColumn_SSAS_tgt
repo.RepoObjectColumn_SSAS_tgt <.. repo.RepoObjectColumn
repo.RepoObjectColumn_SSAS_tgt <.. repo.RepoObject_SSAS_tgt
repo.SysColumn_RepoObjectColumn_via_name <.. repo_sys.sql_expression_dependencies
repo.SysObject_RepoObject_via_name <.. repo_sys.sql_expression_dependencies
repo_sys.ExtendedProperties <.. repo_sys.SysColumn
repo_sys.ExtendedProperties <.. repo_sys.SysObject
repo_sys.sql_expression_dependencies <.. reference.RepoObject_reference_SqlExpressionDependencies
repo_sys.SysColumn <.. repo.SysColumn_RepoObjectColumn_via_name
repo_sys.SysObject <.. repo.SysObject_RepoObject_via_name
repo_sys.SysObject <.. repo_sys.SysColumn
ssas.model_json <.. ssas.model_json_10
ssas.model_json_10 <.. ssas.model_json_20
ssas.model_json_20 <.. ssas.model_json_31_tables
ssas.model_json_31_tables <.. ssas.model_json_31_tables_T
ssas.model_json_31_tables_T <.. repo.RepoObject_SSAS_src
ssas.model_json_31_tables_T <.. ssas.model_json_316_tables_descriptions_multiline
ssas.model_json_31_tables_T <.. ssas.model_json_311_tables_columns
ssas.model_json_31_tables_T <.. repo.RepoObject_gross
ssas.model_json_311_tables_columns <.. ssas.model_json_311_tables_columns_T
ssas.model_json_311_tables_columns_T <.. repo.RepoObjectColumn_SSAS_src
ssas.model_json_316_tables_descriptions_multiline <.. ssas.model_json_3161_tables_descriptions_StrAgg
ssas.model_json_3161_tables_descriptions_StrAgg <.. repo.RepoObject_gross
sys_dwh.columns <.. repo_sys.SysColumn
sys_dwh.columns <.. repo_sys.ExtendedProperties
sys_dwh.columns <.. repo_sys.ExtendedProperties
sys_dwh.computed_columns <.. repo_sys.SysColumn
sys_dwh.default_constraints <.. repo_sys.SysColumn
sys_dwh.extended_properties <.. repo_sys.ExtendedProperties
sys_dwh.extended_properties <.. repo_sys.ExtendedProperties
sys_dwh.identity_columns <.. repo_sys.SysColumn
sys_dwh.indexes <.. repo_sys.ExtendedProperties
sys_dwh.indexes <.. repo_sys.ExtendedProperties
sys_dwh.objects <.. repo_sys.ExtendedProperties
sys_dwh.objects <.. repo_sys.ExtendedProperties
sys_dwh.objects <.. repo_sys.SysObject
sys_dwh.parameters <.. repo_sys.ExtendedProperties
sys_dwh.parameters <.. repo_sys.ExtendedProperties
sys_dwh.schemas <.. repo_sys.ExtendedProperties
sys_dwh.schemas <.. repo_sys.ExtendedProperties
sys_dwh.schemas <.. repo_sys.SysObject
sys_dwh.sql_expression_dependencies <.. repo_sys.sql_expression_dependencies
sys_dwh.sql_modules <.. repo_sys.SysObject
sys_dwh.tables <.. repo_sys.SysObject
sys_dwh.types <.. repo_sys.SysColumn
workflow.ProcedureDependency <.. workflow.ProcedureDependency_input_PersistenceDependency
workflow.ProcedureDependency <.. workflow.Workflow_ProcedureDependency
workflow.ProcedureDependency_input_PersistenceDependency <.. workflow.ProcedureDependency
workflow.ProcedureDependency_input_PersistenceDependency_S <.. workflow.ProcedureDependency_input_PersistenceDependency
workflow.Workflow <.. workflow.WorkflowStep_S
workflow.Workflow <.. workflow.Workflow_ProcedureDependency
workflow.Workflow <.. workflow.WorkflowStep_active
workflow.Workflow_ProcedureDependency <.. workflow.Workflow_ProcedureDependency_T
workflow.Workflow_ProcedureDependency_T <.. workflow.Workflow_ProcedureDependency_T_active
workflow.Workflow_ProcedureDependency_T_active <.. workflow.Workflow_ProcedureDependency_T_NotInSortorder
workflow.WorkflowStep <.. workflow.WorkflowStep_active
workflow.WorkflowStep_active <.. workflow.Workflow_ProcedureDependency
workflow.WorkflowStep_active <.. workflow.Workflow_ProcedureDependency_T_active
workflow.WorkflowStep_S <.. workflow.WorkflowStep
workflow.WorkflowStep_Sortorder <.. workflow.Workflow_ProcedureDependency_T_NotInSortorder
footer
to view a reduced diagram in original size and to be able to click on the links:
open the diagram in a new tab via the Context menu.
end footer

@enduml

