'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:dbeaver.datasources_dbschematable_constraint.adoc[]" as dbeaver.DataSources_DbSchemaTable_constraint << V >> {
  BulkColumn : (varchar(max))
  - id : (int)
  is_json : (int)
  - key : (nvarchar(4000))
  - type : (tinyint)
  value : (nvarchar(max))
  - VirtualModel_database : (nvarchar(4000))
  VirtualModel_database_json : (nvarchar(max))
  VirtualModel_json : (nvarchar(max))
  - VirtualModel_key : (nvarchar(4000))
  - VirtualModel_schema : (nvarchar(4000))
  VirtualModel_schema_json : (nvarchar(max))
  VirtualModel_table : (nvarchar(500))
  VirtualModel_table_constraint_attributes_json : (nvarchar(max))
  VirtualModel_table_constraint_type : (nvarchar(max))
  VirtualModel_table_constraints_json : (nvarchar(max))
  VirtualModel_table_json : (nvarchar(max))
  VirtualModels : (nvarchar(max))
  --
}

