'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity docs.RepoObject_ColumnList << V >> {
  --
  AntoraColumnDetails : nvarchar(max)
  AntoraNonPkColumnTableRows : nvarchar(max)
  AntoraPkColumnTableRows : nvarchar(max)
  PlantumlIndexColumns : nvarchar(max)
  PlantumlNonPkEntityColumns : nvarchar(max)
  PlantumlNonPkHiddenEntityColumns : nvarchar(max)
  PlantumlNonPkIndexColumns : nvarchar(max)
  PlantumlPkEntityColumns : nvarchar(max)
  * RepoObject_guid : uniqueidentifier
  --
}

