'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity "puml-link:logs.ftv_ExecutionLog_puml_tree.adoc[prefix=..]" as logs.ftv_ExecutionLog_puml_tree << IF >> {
  --
  Depth : (int)
  duration_current_execution_guid : (int)
  execution_instance_guid : (uniqueidentifier)
  id : (bigint)
  parent_execution_log_id : (bigint)
  - PlantUmlTree : (nvarchar(4000))
  - PlantUmlTreeTable : (nvarchar(4000))
  proc_name : (nvarchar(128))
  proc_schema_name : (nvarchar(128))
  step_id : (int)
  --
  --
}

