'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:repo_sys.RepoObjectReferencing.adoc[]" as repo_sys.RepoObjectReferencing << V >> {
  --
  has_different_sys_names : (bit)
  - is_caller_dependent : (bit)
  is_repo_managed : (bit)
  referencing_class : (tinyint)
  referencing_class_desc : (nvarchar(60))
  referencing_entity_name : (sysname)
  - referencing_id : (int)
  referencing_schema_name : (sysname)
  - RepoObject_fullname : (nvarchar(261))
  - RepoObject_guid : (uniqueidentifier)
  - SysObject_fullname : (nvarchar(261))
  SysObject_id : (int)
  SysObject_modify_date : (datetime)
  SysObject_type : (char(2))
  --
  --
}

