'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:repo.SysSchema_RepoSchema_via_name.adoc[]" as repo.SysSchema_RepoSchema_via_name << V >> {
  --
  is_RepoSchema_name_uniqueidentifier : (int)
  is_SysSchema_name_uniqueidentifier : (int)
  RepoSchema_guid : (uniqueidentifier)
  RepoSchema_is_SysSchema_missing : (bit)
  RepoSchema_name : (nvarchar(128))
  RepoSchema_SysSchema_id : (int)
  RepoSchema_SysSchema_name : (nvarchar(128))
  - SysSchema_id : (int)
  - SysSchema_name : (sysname)
  SysSchema_RepoSchema_guid : (uniqueidentifier)
  --
  --
}

