'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:repo.sysobject_repoobject_via_guid.adoc[]" as repo.SysObject_RepoObject_via_guid << V >> {
  --
  history_table_guid : (uniqueidentifier)
  history_table_id : (int)
  is_external : (bit)
  is_repo_managed : (bit)
  is_RepoObject_name_uniqueidentifier : (int)
  is_ssas : (bit)
  is_SysObject_name_uniqueidentifier : (int)
  - modify_date : (datetime)
  - parent_object_id : (int)
  Repo_history_table_guid : (uniqueidentifier)
  Repo_temporal_type : (tinyint)
  RepoObject_guid : (uniqueidentifier)
  RepoObject_is_SysObject_missing : (bit)
  RepoObject_name : (nvarchar(128))
  RepoObject_schema_name : (nvarchar(128))
  RepoObject_SysObject_id : (int)
  RepoObject_SysObject_modify_date : (datetime)
  RepoObject_SysObject_name : (nvarchar(128))
  RepoObject_SysObject_parent_object_id : (int)
  RepoObject_SysObject_schema_name : (nvarchar(128))
  RepoObject_SysObject_type : (char(2))
  RepoObject_type : (char(2))
  - SysObject_id : (int)
  - SysObject_name : (sysname)
  SysObject_RepoObject_guid : (uniqueidentifier)
  SysObject_schema_name : (sysname)
  SysObject_type : (char(2))
  SysObject_type_desc : (nvarchar(60))
  temporal_type : (tinyint)
  --
  --
}

