'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity "[[{site-url}/{page-component-name}/{page-component-version}/{page-module}/repo.SysColumn_RepoObjectColumn_via_name.html repo.SysColumn_RepoObjectColumn_via_name]]" as repo.SysColumn_RepoObjectColumn_via_name << V >> {
  --
  default_definition : (nvarchar(max))
  default_is_system_named : (bit)
  default_name : (sysname)
  definition : (nvarchar(max))
  generated_always_type : (tinyint)
  graph_type : (int)
  has_different_sys_names : (bit)
  increment_value : (sql_variant)
  - is_computed : (bit)
  - is_identity : (bit)
  is_nullable : (bit)
  is_persisted : (bit)
  is_query_plan_expression : (bit)
  is_repo_managed : (bit)
  is_RepoObjectColumn_name_uniqueidentifier : (int)
  is_SysObjectColumn_missing : (bit)
  is_SysObjectColumn_name_uniqueidentifier : (int)
  persistence_source_RepoObjectColumn_guid : (uniqueidentifier)
  Referencing_Count : (int)
  Repo_default_definition : (nvarchar(max))
  Repo_default_is_system_named : (bit)
  Repo_default_name : (nvarchar(128))
  Repo_definition : (nvarchar(max))
  Repo_generated_always_type : (tinyint)
  Repo_graph_type : (int)
  Repo_increment_value : (sql_variant)
  Repo_is_computed : (bit)
  Repo_is_identity : (bit)
  Repo_is_nullable : (bit)
  Repo_is_persisted : (bit)
  Repo_seed_value : (sql_variant)
  Repo_user_type_fullname : (nvarchar(128))
  Repo_user_type_name : (nvarchar(128))
  Repo_uses_database_collation : (bit)
  RepoObject_fullname : (nvarchar(261))
  RepoObject_guid : (uniqueidentifier)
  RepoObjectColumn_guid : (uniqueidentifier)
  RepoObjectColumn_name : (nvarchar(128))
  RowNumberOverName : (bigint)
  seed_value : (sql_variant)
  - SysObject_column_id : (int)
  SysObject_column_name : (sysname)
  SysObject_fullname : (nvarchar(261))
  - SysObject_id : (int)
  SysObject_name : (nvarchar(128))
  SysObject_RepoObject_guid : (uniqueidentifier)
  SysObject_RepoObjectColumn_guid : (uniqueidentifier)
  SysObject_schema_name : (nvarchar(128))
  SysObject_type : (char(2))
  SysObjectColumn_column_id : (int)
  SysObjectColumn_name : (nvarchar(128))
  user_type_fullname : (nvarchar(182))
  user_type_name : (sysname)
  uses_database_collation : (bit)
  --
  --
}

