'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:repo.measures_union.adoc[]" as repo.Measures_union << V >> {
  Description : (nvarchar(max))
  Expression : (nvarchar(max))
  is_ssas : (bit)
  - Measure_guid : (uniqueidentifier)
  measures_description : (nvarchar(max))
  measures_description_ja : (nvarchar(max))
  measures_displayFolder : (nvarchar(500))
  measures_expression : (nvarchar(max))
  measures_expression_ja : (nvarchar(max))
  measures_formatString : (nvarchar(500))
  measures_fullname : (nvarchar(517))
  - measures_fullname2 : (nvarchar(638))
  measures_isHidden : (bit)
  - measures_name : (nvarchar(500))
  - RepoObject_fullname2 : (nvarchar(257))
  RepoObject_guid : (uniqueidentifier)
  RepoObject_name : (nvarchar(128))
  - RepoSchema_name : (nvarchar(128))
  --
}

