'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity "[[{site-url}/{page-component-name}/current/{page-module}/sqlparse.RepoObject_SqlModules_39_object.html sqlparse.RepoObject_SqlModules_39_object]]" as sqlparse.RepoObject_SqlModules_39_object << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
  has_GroupBy : (int)
  is_1_create : (int)
  is_2_view : (int)
  is_3_Identifier : (int)
  is_4_as : (int)
  is_5_select : (int)
  is_6_Identifier : (int)
  is_6_IdentifierList : (int)
  is_7_from : (int)
  is_7_IdentifierList : (int)
  is_8_IdentifierList : (int)
  is_create_view_Identifier_as_select : (int)
  is_select_IdentifierList_from : (int)
  is_union : (int)
  Min_RowNumber_From : (bigint)
  Min_RowNumber_GroupBy : (bigint)
  Min_RowNumber_IdentifierList : (bigint)
  Min_RowNumber_Where : (bigint)
  SysObject_fullname : (nvarchar(261))
  --
  --
}

