'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity sqlparse.ftv_sqlparse_children_pivot << IF >> {
  --
  child0_children : nvarchar(4000)
  child0_class : nvarchar(4000)
  child0_is_group : nvarchar(4000)
  child0_is_keyword : nvarchar(4000)
  child0_normalized : nvarchar(4000)
  child1_children : nvarchar(4000)
  child1_class : nvarchar(4000)
  child1_is_group : nvarchar(4000)
  child1_is_keyword : nvarchar(4000)
  child1_normalized : nvarchar(4000)
  child2_children : nvarchar(4000)
  child2_class : nvarchar(4000)
  child2_is_group : nvarchar(4000)
  child2_is_keyword : nvarchar(4000)
  child2_normalized : nvarchar(4000)
  child3_children : nvarchar(4000)
  child3_class : nvarchar(4000)
  child3_is_group : nvarchar(4000)
  child3_is_keyword : nvarchar(4000)
  child3_normalized : nvarchar(4000)
  child4_children : nvarchar(4000)
  child4_class : nvarchar(4000)
  child4_is_group : nvarchar(4000)
  child4_is_keyword : nvarchar(4000)
  child4_normalized : nvarchar(4000)
  --
}

