'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity "puml-link:ssas.model_json_3122_tables_measures_expressions_multiline.adoc[prefix=..]" as ssas.model_json_3122_tables_measures_expressions_multiline << V >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  - **tables_measures_name** : (nvarchar(500))
  --
  - Key : (nvarchar(4000))
  - Measure_guid : (uniqueidentifier)
  - RepoObject_guid : (uniqueidentifier)
  - Type : (tinyint)
  Value : (nvarchar(max))
  --
  --
}

