'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity "puml-link:ssas.TMSCHEMA_RELATIONSHIPS.adoc[prefix=..]" as ssas.TMSCHEMA_RELATIONSHIPS << U >> {
  - **databasename** : (nvarchar(128))
  - **ID** : (numeric(20, 0))
  --
  - CrossFilteringBehavior : (bigint)
  - FromCardinality : (bigint)
  - FromColumnID : (numeric(20, 0))
  - FromTableID : (numeric(20, 0))
  - IsActive : (bit)
  - JoinOnDateBehavior : (bigint)
  - ModelID : (numeric(20, 0))
  - ModifiedTime : (datetime)
  - Name : (nvarchar(max))
  RefreshedTime : (datetime)
  RelationshipStorage2ID : (numeric(20, 0))
  RelationshipStorageID : (numeric(20, 0))
  - RelyOnReferentialIntegrity : (bit)
  - SecurityFilteringBehavior : (bigint)
  - State : (bigint)
  - ToCardinality : (bigint)
  - ToColumnID : (numeric(20, 0))
  - ToTableID : (numeric(20, 0))
  - Type : (bigint)
  --
  --
}

