'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity "puml-link:ssas.TMSCHEMA_KPIS.adoc[prefix=..]" as ssas.TMSCHEMA_KPIS << U >> {
  - **databasename** : (nvarchar(128))
  - **ID** : (numeric(20, 0))
  --
  Description : (nvarchar(max))
  - MeasureID : (numeric(20, 0))
  - ModifiedTime : (datetime)
  StatusDescription : (nvarchar(max))
  StatusExpression : (nvarchar(max))
  StatusGraphic : (nvarchar(max))
  TargetDescription : (nvarchar(max))
  TargetExpression : (nvarchar(max))
  TargetFormatString : (nvarchar(max))
  TrendDescription : (nvarchar(max))
  TrendExpression : (nvarchar(max))
  TrendGraphic : (nvarchar(max))
  --
  --
}

