'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis_t.tblcontrolflow_src.adoc[]" as ssis_t.TblControlFlow_src << V >> {
  DelayValidationPropertyValue : (nvarchar(max))
  DFTQuery : (xml)
  ExecPkgTaskQry : (xml)
  ExpressionValue : (nvarchar(max))
  - IsDisabled : (nvarchar(max))
  - RowID : (int)
  ScriptTaskQry : (xml)
  SqlTaskQry : (xml)
  TaskDescription : (nvarchar(max))
  TaskName : (nvarchar(max))
  TaskPath : (varchar(max))
  TaskType : (nvarchar(max))
  --
}

