= [configT].[SsasDmvTableImport]

== existing_properties

// tag::existing_properties[]
:ExistsProperty--antorareferencinglist:
:ExistsProperty--description:
:ExistsProperty--exampleusage:
:ExistsProperty--is_repo_managed:
:ExistsProperty--is_ssas:
:ExistsProperty--ms_description:
:ExistsProperty--sql_modules_definition:
:ExistsProperty--FK:
:ExistsProperty--Columns:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
CFE6A70A-8A06-EC11-8515-A81E8446D5B0
// end::RepoObject_guid[]

== SysObject_type

// tag::SysObject_type[]
V 
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
view
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
925962375
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2021-09-05 12:09:09
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]
[#column-DmvTableName]
=== DmvTableName

[cols="d,8m,m,m,m,d"]
|===
|
|DmvTableName
|nvarchar(128)
|NULL
|
|
|===

.Referencing Columns
--
* xref:configT.SsasDmvTableImport_DmvColumnList.adoc#column-DmvTableName[+configT.SsasDmvTableImport_DmvColumnList.DmvTableName+]
--


[#column-isActive]
=== isActive

[cols="d,8m,m,m,m,d"]
|===
|
|isActive
|bit
|NULL
|
|
|===


// end::AntoraColumnDetails[]

== AntoraMeasureDetails

// tag::AntoraMeasureDetails[]

// end::AntoraMeasureDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]


// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]
|
|<<column-DmvTableName>>
|nvarchar(128)
|NULL
|
|

|
|<<column-isActive>>
|bit
|NULL
|
|

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

// end::AntoraIndexList[]

== AntoraParameterList

// tag::AntoraParameterList[]

// end::AntoraParameterList[]

== Other tags

source: property.RepoObjectProperty_cross As rop_cross


=== AdocUspSteps

// tag::adocuspsteps[]

// end::adocuspsteps[]


=== AntoraReferencedList

// tag::antorareferencedlist[]

// end::antorareferencedlist[]


=== AntoraReferencingList

// tag::antorareferencinglist[]
* xref:configT.SsasDmvTableImport_DmvColumnList.adoc[]
// end::antorareferencinglist[]


=== Description

// tag::description[]

obsolet

defines, which SSAS DMV tables should be imported
// end::description[]


=== exampleUsage

// tag::exampleusage[]

Merge config.SsasDmvTableImport As tgt
Using configT.SsasDmvTableImport As src
On tgt.DmvTableName = src.DmvTableName
When Matched And tgt.isActive <> src.isActive
    Then Update Set
             isActive = src.isActive
When Not Matched By Target
    Then Insert
         (
             DmvTableName
           , isActive
         )
         Values
             (
                 src.DmvTableName
               , src.isActive
             );
// end::exampleusage[]


=== exampleUsage_2

// tag::exampleusage_2[]

// end::exampleusage_2[]


=== exampleUsage_3

// tag::exampleusage_3[]

// end::exampleusage_3[]


=== exampleUsage_4

// tag::exampleusage_4[]

// end::exampleusage_4[]


=== exampleUsage_5

// tag::exampleusage_5[]

// end::exampleusage_5[]


=== exampleWrong_Usage

// tag::examplewrong_usage[]

// end::examplewrong_usage[]


=== has_execution_plan_issue

// tag::has_execution_plan_issue[]

// end::has_execution_plan_issue[]


=== has_get_referenced_issue

// tag::has_get_referenced_issue[]

// end::has_get_referenced_issue[]


=== has_history

// tag::has_history[]

// end::has_history[]


=== has_history_columns

// tag::has_history_columns[]

// end::has_history_columns[]


=== InheritanceType

// tag::inheritancetype[]

// end::inheritancetype[]


=== is_persistence

// tag::is_persistence[]

// end::is_persistence[]


=== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]

// end::is_persistence_check_duplicate_per_pk[]


=== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]

// end::is_persistence_check_for_empty_source[]


=== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]

// end::is_persistence_delete_changed[]


=== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]

// end::is_persistence_delete_missing[]


=== is_persistence_insert

// tag::is_persistence_insert[]

// end::is_persistence_insert[]


=== is_persistence_truncate

// tag::is_persistence_truncate[]

// end::is_persistence_truncate[]


=== is_persistence_update_changed

// tag::is_persistence_update_changed[]

// end::is_persistence_update_changed[]


=== is_repo_managed

// tag::is_repo_managed[]
0
// end::is_repo_managed[]


=== is_ssas

// tag::is_ssas[]
0
// end::is_ssas[]


=== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


=== MS_Description

// tag::ms_description[]

obsolet

defines, which SSAS DMV tables should be imported
// end::ms_description[]


=== persistence_source_RepoObject_fullname

// tag::persistence_source_repoobject_fullname[]

// end::persistence_source_repoobject_fullname[]


=== persistence_source_RepoObject_fullname2

// tag::persistence_source_repoobject_fullname2[]

// end::persistence_source_repoobject_fullname2[]


=== persistence_source_RepoObject_guid

// tag::persistence_source_repoobject_guid[]

// end::persistence_source_repoobject_guid[]


=== persistence_source_RepoObject_xref

// tag::persistence_source_repoobject_xref[]

// end::persistence_source_repoobject_xref[]


=== pk_index_guid

// tag::pk_index_guid[]

// end::pk_index_guid[]


=== pk_IndexPatternColumnDatatype

// tag::pk_indexpatterncolumndatatype[]

// end::pk_indexpatterncolumndatatype[]


=== pk_IndexPatternColumnName

// tag::pk_indexpatterncolumnname[]

// end::pk_indexpatterncolumnname[]


=== pk_IndexSemanticGroup

// tag::pk_indexsemanticgroup[]

// end::pk_indexsemanticgroup[]


=== ReferencedObjectList

// tag::referencedobjectlist[]

// end::referencedobjectlist[]


=== usp_persistence_RepoObject_guid

// tag::usp_persistence_repoobject_guid[]

// end::usp_persistence_repoobject_guid[]


=== UspExamples

// tag::uspexamples[]

// end::uspexamples[]


=== UspParameters

// tag::uspparameters[]

// end::uspparameters[]

== Boolean Attributes

source: property.RepoObjectProperty WHERE property_int = 1

// tag::boolean_attributes[]

// end::boolean_attributes[]

== sql_modules_definition

// tag::sql_modules_definition[]
[%collapsible]
=======
[source,sql]
----


/*
<<property_start>>MS_Description
obsolet

defines, which SSAS DMV tables should be imported
<<property_end>>

<<property_start>>exampleUsage
Merge config.SsasDmvTableImport As tgt
Using configT.SsasDmvTableImport As src
On tgt.DmvTableName = src.DmvTableName
When Matched And tgt.isActive <> src.isActive
    Then Update Set
             isActive = src.isActive
When Not Matched By Target
    Then Insert
         (
             DmvTableName
           , isActive
         )
         Values
             (
                 src.DmvTableName
               , src.isActive
             );
<<property_end>>
*/
CREATE   View [configT].[SsasDmvTableImport]
As
--
Select
    DmvTableName = Cast('TMSCHEMA_ANNOTATIONS' As NVarchar(128))
  , isActive     = Cast(1 As Bit)
Union All
Select
    DmvTableName = Cast('TMSCHEMA_ATTRIBUTE_HIERARCHIES' As NVarchar(128))
  , isActive     = Cast(1 As Bit)
Union All
--import issues
Select
    DmvTableName = Cast('TMSCHEMA_CALCULATION_ITEMS' As NVarchar(128))
  , isActive     = Cast(0 As Bit)
Union All
--import issues
Select
    DmvTableName = Cast('TMSCHEMA_CALCULATION_GROUPS' As NVarchar(128))
  , isActive     = Cast(0 As Bit)
Union All
--type conversion required
--CStr([RefreshedTime]) as [RefreshedTime]
Select
    DmvTableName = Cast('TMSCHEMA_COLUMNS' As NVarchar(128))
  , isActive     = Cast(1 As Bit)
Union All
Select
    DmvTableName = Cast('TMSCHEMA_COLUMN_PERMISSIONS' As NVarchar(128))
  , isActive     = Cast(1 As Bit)
Union All
Select
    DmvTableName = Cast('TMSCHEMA_CULTURES' As NVarchar(128))
  , isActive     = Cast(1 As Bit)
Union All
Select
    DmvTableName = Cast('TMSCHEMA_DATA_SOURCES' As NVarchar(128))
  , isActive     = Cast(1 As Bit)
Union All
Select
    DmvTableName = Cast('TMSCHEMA_DETAIL_ROWS_DEFINITIONS' As NVarchar(128))
  , isActive     = Cast(1 As Bit)
Union All
Select
    DmvTableName = Cast('TMSCHEMA_EXPRESSIONS' As NVarchar(128))
  , isActive     = Cast(1 As Bit)
Union All
--import issues
Select
    DmvTableName = Cast('TMSCHEMA_FORMAT_STRING_DEFINITIONS' As NVarchar(128))
  , isActive     = Cast(0 As Bit)
Union All
Select
    DmvTableName = Cast('TMSCHEMA_EXTENDED_PROPERTIES' As NVarchar(128))
  , isActive     = Cast(1 As Bit)
Union All
Select
    DmvTableName = Cast('TMSCHEMA_HIERARCHIES' As NVarchar(128))
  , isActive     = Cast(1 As Bit)
Union All
Select
    DmvTableName = Cast('TMSCHEMA_KPIS' As NVarchar(128))
  , isActive     = Cast(1 As Bit)
Union All
Select
    DmvTableName = Cast('TMSCHEMA_LEVELS' As NVarchar(128))
  , isActive     = Cast(1 As Bit)
Union All
Select
    DmvTableName = Cast('TMSCHEMA_MEASURES' As NVarchar(128))
  , isActive     = Cast(1 As Bit)
Union All
Select
    DmvTableName = Cast('TMSCHEMA_MODEL' As NVarchar(128))
  , isActive     = Cast(1 As Bit)
Union All
Select
    DmvTableName = Cast('TMSCHEMA_OBJECT_TRANSLATIONS' As NVarchar(128))
  , isActive     = Cast(1 As Bit)
Union All
Select
    DmvTableName = Cast('TMSCHEMA_PARTITIONS' As NVarchar(128))
  , isActive     = Cast(1 As Bit)
Union All
Select
    DmvTableName = Cast('TMSCHEMA_PERSPECTIVE_COLUMNS' As NVarchar(128))
  , isActive     = Cast(1 As Bit)
Union All
Select
    DmvTableName = Cast('TMSCHEMA_PERSPECTIVE_HIERARCHIES' As NVarchar(128))
  , isActive     = Cast(1 As Bit)
Union All
Select
    DmvTableName = Cast('TMSCHEMA_PERSPECTIVE_MEASURES' As NVarchar(128))
  , isActive     = Cast(1 As Bit)
Union All
Select
    DmvTableName = Cast('TMSCHEMA_PERSPECTIVE_TABLES' As NVarchar(128))
  , isActive     = Cast(1 As Bit)
Union All
Select
    DmvTableName = Cast('TMSCHEMA_PERSPECTIVES' As NVarchar(128))
  , isActive     = Cast(1 As Bit)
Union All
--import issues
Select
    DmvTableName = Cast('TMSCHEMA_QUERY_GROUPS' As NVarchar(128))
  , isActive     = Cast(0 As Bit)
Union All
Select
    DmvTableName = Cast('TMSCHEMA_RELATIONSHIPS' As NVarchar(128))
  , isActive     = Cast(1 As Bit)
Union All
Select
    DmvTableName = Cast('TMSCHEMA_ROLE_MEMBERSHIPS' As NVarchar(128))
  , isActive     = Cast(1 As Bit)
Union All
Select
    DmvTableName = Cast('TMSCHEMA_ROLES' As NVarchar(128))
  , isActive     = Cast(1 As Bit)
Union All
Select
    DmvTableName = Cast('TMSCHEMA_TABLES' As NVarchar(128))
  , isActive     = Cast(1 As Bit)
Union All
Select
    DmvTableName = Cast('TMSCHEMA_TABLE_PERMISSIONS' As NVarchar(128))
  , isActive     = Cast(1 As Bit)
Union All
Select
    DmvTableName = Cast('TMSCHEMA_VARIATIONS' As NVarchar(128))
  , isActive     = Cast(1 As Bit)

----
=======
// end::sql_modules_definition[]


