= [docs].[RepoObject_Adoc]

== existing_properties

// tag::existing_properties[]
:ExistsProperty--antorareferencedlist:
:ExistsProperty--antorareferencinglist:
:ExistsProperty--is_repo_managed:
:ExistsProperty--is_ssas:
:ExistsProperty--ms_description:
:ExistsProperty--referencedobjectlist:
:ExistsProperty--sql_modules_definition:
:ExistsProperty--FK:
:ExistsProperty--AntoraIndexList:
:ExistsProperty--Columns:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
D5E0B563-4291-EB11-84F2-A81E8446D5B0
// end::RepoObject_guid[]

== SysObject_type

// tag::SysObject_type[]
V 
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
view
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
1892917815
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2021-09-05 12:03:15
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]
[#column-AdocContent]
=== AdocContent

[cols="d,m,m,m,m,d"]
|===
|
|AdocContent
|nvarchar(max)
|NOT NULL
|
|
|===

.Referencing Columns
--
* xref:docs.RepoObject_Adoc_T.adoc#column-AdocContent[+docs.RepoObject_Adoc_T.AdocContent+]
--


[#column-is_DocsOutput]
=== is_DocsOutput

[cols="d,m,m,m,m,d"]
|===
|
|is_DocsOutput
|int
|NULL
|
|
|===

.Referenced Columns
--
* xref:repo.RepoObject_gross2.adoc#column-is_DocsOutput[+repo.RepoObject_gross2.is_DocsOutput+]
--

.Referencing Columns
--
* xref:docs.RepoObject_Adoc_T.adoc#column-is_DocsOutput[+docs.RepoObject_Adoc_T.is_DocsOutput+]
--


[#column-PropertyCount]
=== PropertyCount

[cols="d,m,m,m,m,d"]
|===
|
|PropertyCount
|int
|NULL
|
|
|===

.Referencing Columns
--
* xref:docs.RepoObject_Adoc_T.adoc#column-PropertyCount[+docs.RepoObject_Adoc_T.PropertyCount+]
--


[#column-RepoObject_fullname]
=== RepoObject_fullname

[cols="d,m,m,m,m,d"]
|===
|
|RepoObject_fullname
|nvarchar(261)
|NULL
|
|
|===

.Referencing Columns
--
* xref:docs.RepoObject_Adoc_T.adoc#column-RepoObject_fullname[+docs.RepoObject_Adoc_T.RepoObject_fullname+]
--


[#column-RepoObject_fullname2]
=== RepoObject_fullname2

[cols="d,m,m,m,m,d"]
|===
|
|RepoObject_fullname2
|nvarchar(257)
|NULL
|
|
|===

.Referencing Columns
--
* xref:docs.RepoObject_Adoc_T.adoc#column-RepoObject_fullname2[+docs.RepoObject_Adoc_T.RepoObject_fullname2+]
--


[#column-RepoObject_guid]
=== RepoObject_guid

[cols="d,m,m,m,m,d"]
|===
|
|RepoObject_guid
|uniqueidentifier
|NOT NULL
|
|
|===

.Referenced Columns
--
* xref:repo.RepoObject_gross2.adoc#column-RepoObject_guid[+repo.RepoObject_gross2.RepoObject_guid+]
--

.Referencing Columns
--
* xref:docs.RepoObject_Adoc_T.adoc#column-RepoObject_guid[+docs.RepoObject_Adoc_T.RepoObject_guid+]
--


[#column-RepoObject_schema_name]
=== RepoObject_schema_name

[cols="d,m,m,m,m,d"]
|===
|
|RepoObject_schema_name
|nvarchar(128)
|NULL
|
|
|===

.Referencing Columns
--
* xref:docs.RepoObject_Adoc_T.adoc#column-RepoObject_schema_name[+docs.RepoObject_Adoc_T.RepoObject_schema_name+]
--


[#column-SysObject_fullname]
=== SysObject_fullname

[cols="d,m,m,m,m,d"]
|===
|
|SysObject_fullname
|nvarchar(261)
|NULL
|
|
|===

.Referencing Columns
--
* xref:docs.RepoObject_Adoc_T.adoc#column-SysObject_fullname[+docs.RepoObject_Adoc_T.SysObject_fullname+]
--


[#column-SysObject_fullname2]
=== SysObject_fullname2

[cols="d,m,m,m,m,d"]
|===
|
|SysObject_fullname2
|nvarchar(257)
|NULL
|
|
|===

.Referencing Columns
--
* xref:docs.RepoObject_Adoc_T.adoc#column-SysObject_fullname2[+docs.RepoObject_Adoc_T.SysObject_fullname2+]
--


[#column-SysObject_schema_name]
=== SysObject_schema_name

[cols="d,m,m,m,m,d"]
|===
|
|SysObject_schema_name
|nvarchar(128)
|NULL
|
|
|===

.Referencing Columns
--
* xref:docs.RepoObject_Adoc_T.adoc#column-SysObject_schema_name[+docs.RepoObject_Adoc_T.SysObject_schema_name+]
--


[#column-SysObject_type]
=== SysObject_type

[cols="d,m,m,m,m,d"]
|===
|
|SysObject_type
|char(2)
|NULL
|
|
|===

.Referencing Columns
--
* xref:docs.RepoObject_Adoc_T.adoc#column-SysObject_type[+docs.RepoObject_Adoc_T.SysObject_type+]
--


[#column-SysObject_type_name]
=== SysObject_type_name

[cols="d,m,m,m,m,d"]
|===
|
|SysObject_type_name
|nvarchar(128)
|NULL
|
|
|===

.Referencing Columns
--
* xref:docs.RepoObject_Adoc_T.adoc#column-SysObject_type_name[+docs.RepoObject_Adoc_T.SysObject_type_name+]
--


// end::AntoraColumnDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]












// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]
|
|<<column-AdocContent>>
|nvarchar(max)
|NOT NULL
|
|

|
|<<column-is_DocsOutput>>
|int
|NULL
|
|

|
|<<column-PropertyCount>>
|int
|NULL
|
|

|
|<<column-RepoObject_fullname>>
|nvarchar(261)
|NULL
|
|

|
|<<column-RepoObject_fullname2>>
|nvarchar(257)
|NULL
|
|

|
|<<column-RepoObject_guid>>
|uniqueidentifier
|NOT NULL
|
|

|
|<<column-RepoObject_schema_name>>
|nvarchar(128)
|NULL
|
|

|
|<<column-SysObject_fullname>>
|nvarchar(261)
|NULL
|
|

|
|<<column-SysObject_fullname2>>
|nvarchar(257)
|NULL
|
|

|
|<<column-SysObject_schema_name>>
|nvarchar(128)
|NULL
|
|

|
|<<column-SysObject_type>>
|char(2)
|NULL
|
|

|
|<<column-SysObject_type_name>>
|nvarchar(128)
|NULL
|
|

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

[#index-idx_RepoObject_Adoc_1]
=== idx_RepoObject_Adoc++__++1

* IndexSemanticGroup: xref:other/IndexSemanticGroup.adoc#_repoobject_guid[RepoObject_guid]
+
--
* <<column-RepoObject_guid>>; uniqueidentifier
--
* PK, Unique, Real: 0, 0, 0

// end::AntoraIndexList[]

== AntoraParameterList

// tag::AntoraParameterList[]

// end::AntoraParameterList[]

== Other tags

source: property.RepoObjectProperty_cross As rop_cross


=== AdocUspSteps

// tag::adocuspsteps[]

// end::adocuspsteps[]


=== AntoraReferencedList

// tag::antorareferencedlist[]
* xref:docs.RepoObject_ColumnList_T.adoc[]
* xref:docs.RepoObject_IndexList_T.adoc[]
* xref:docs.RepoObject_ParameterList.adoc[]
* xref:property.RepoObjectProperty.adoc[]
* xref:property.RepoObjectProperty_cross.adoc[]
* xref:repo.RepoObject_gross2.adoc[]
// end::antorareferencedlist[]


=== AntoraReferencingList

// tag::antorareferencinglist[]
* xref:docs.RepoObject_Adoc_T.adoc[]
* xref:docs.usp_PERSIST_RepoObject_Adoc_T.adoc[]
// end::antorareferencinglist[]


=== exampleUsage

// tag::exampleusage[]

// end::exampleusage[]


=== exampleUsage_2

// tag::exampleusage_2[]

// end::exampleusage_2[]


=== exampleUsage_3

// tag::exampleusage_3[]

// end::exampleusage_3[]


=== exampleUsage_4

// tag::exampleusage_4[]

// end::exampleusage_4[]


=== exampleUsage_5

// tag::exampleusage_5[]

// end::exampleusage_5[]


=== exampleWrong_Usage

// tag::examplewrong_usage[]

// end::examplewrong_usage[]


=== has_execution_plan_issue

// tag::has_execution_plan_issue[]

// end::has_execution_plan_issue[]


=== has_get_referenced_issue

// tag::has_get_referenced_issue[]

// end::has_get_referenced_issue[]


=== has_history

// tag::has_history[]

// end::has_history[]


=== has_history_columns

// tag::has_history_columns[]

// end::has_history_columns[]


=== is_persistence

// tag::is_persistence[]

// end::is_persistence[]


=== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]

// end::is_persistence_check_duplicate_per_pk[]


=== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]

// end::is_persistence_check_for_empty_source[]


=== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]

// end::is_persistence_delete_changed[]


=== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]

// end::is_persistence_delete_missing[]


=== is_persistence_insert

// tag::is_persistence_insert[]

// end::is_persistence_insert[]


=== is_persistence_truncate

// tag::is_persistence_truncate[]

// end::is_persistence_truncate[]


=== is_persistence_update_changed

// tag::is_persistence_update_changed[]

// end::is_persistence_update_changed[]


=== is_repo_managed

// tag::is_repo_managed[]
0
// end::is_repo_managed[]


=== is_ssas

// tag::is_ssas[]
0
// end::is_ssas[]


=== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


=== MS_Description

// tag::ms_description[]

`AdocContent` is the content of a page to be used by Antora as partial.

The view xref:docs.RepoObject_Adoc.adoc[] will persisted into xref:docs.RepoObject_Adoc_T.adoc[] +
and later exported for Antora by xref:docs.usp_PERSIST_RepoObject_Adoc_T.adoc[]

One document per RepoObject is generated, it contains all information (but not diagrams) which is used by Antora. 

All Parts of the documentations are tagged, Antora can reference the content using this tags.

* any per RepoObject existing properties in xref:property.RepoObjectProperty.adoc[] are extracted as separate tags
* some specific additional tags are extracted from other sources (some lists, some content from xref:repo.RepoObject_gross.adoc[])
* a special entry per exported tag is created: `':ExistsProperty--' + Lower ( rop.property_name ) + ':'` which can be used to check the existence of a tag entry

To use additional content in Antora documentation first try to include new properties into xref:property.RepoObjectProperty.adoc[]
// end::ms_description[]


=== persistence_source_RepoObject_fullname

// tag::persistence_source_repoobject_fullname[]

// end::persistence_source_repoobject_fullname[]


=== persistence_source_RepoObject_fullname2

// tag::persistence_source_repoobject_fullname2[]

// end::persistence_source_repoobject_fullname2[]


=== persistence_source_RepoObject_guid

// tag::persistence_source_repoobject_guid[]

// end::persistence_source_repoobject_guid[]


=== persistence_source_RepoObject_xref

// tag::persistence_source_repoobject_xref[]

// end::persistence_source_repoobject_xref[]


=== pk_index_guid

// tag::pk_index_guid[]

// end::pk_index_guid[]


=== pk_IndexPatternColumnDatatype

// tag::pk_indexpatterncolumndatatype[]

// end::pk_indexpatterncolumndatatype[]


=== pk_IndexPatternColumnName

// tag::pk_indexpatterncolumnname[]

// end::pk_indexpatterncolumnname[]


=== pk_IndexSemanticGroup

// tag::pk_indexsemanticgroup[]

// end::pk_indexsemanticgroup[]


=== ReferencedObjectList

// tag::referencedobjectlist[]
* [docs].[RepoObject_ColumnList_T]
* [docs].[RepoObject_IndexList_T]
* [docs].[RepoObject_ParameterList]
* [property].[RepoObjectProperty]
* [property].[RepoObjectProperty_cross]
* [repo].[RepoObject_gross2]
// end::referencedobjectlist[]


=== usp_persistence_RepoObject_guid

// tag::usp_persistence_repoobject_guid[]

// end::usp_persistence_repoobject_guid[]


=== UspExamples

// tag::uspexamples[]

// end::uspexamples[]


=== UspParameters

// tag::uspparameters[]

// end::uspparameters[]

== Boolean Attributes

source: property.RepoObjectProperty WHERE property_int = 1

// tag::boolean_attributes[]

// end::boolean_attributes[]

== sql_modules_definition

// tag::sql_modules_definition[]
[%collapsible]
=======
[source,sql]
----


/*
<<property_start>>MS_Description
`AdocContent` is the content of a page to be used by Antora as partial.

The view xref:docs.RepoObject_Adoc.adoc[] will persisted into xref:docs.RepoObject_Adoc_T.adoc[] +
and later exported for Antora by xref:docs.usp_PERSIST_RepoObject_Adoc_T.adoc[]

One document per RepoObject is generated, it contains all information (but not diagrams) which is used by Antora. 

All Parts of the documentations are tagged, Antora can reference the content using this tags.

* any per RepoObject existing properties in xref:property.RepoObjectProperty.adoc[] are extracted as separate tags
* some specific additional tags are extracted from other sources (some lists, some content from xref:repo.RepoObject_gross.adoc[])
* a special entry per exported tag is created: `':ExistsProperty--' + Lower ( rop.property_name ) + ':'` which can be used to check the existence of a tag entry

To use additional content in Antora documentation first try to include new properties into xref:property.RepoObjectProperty.adoc[]
<<property_end>>
*/
CREATE View [docs].[RepoObject_Adoc]
As
Select
    ro.RepoObject_guid
  , is_DocsOutput          = Max ( ro.is_DocsOutput )
  , RepoObject_fullname    = Max ( ro.RepoObject_fullname )
  , RepoObject_fullname2   = Max ( ro.RepoObject_fullname2 )
  , RepoObject_schema_name = Max ( ro.RepoObject_schema_name )
  , SysObject_fullname     = Max ( ro.SysObject_fullname )
  , SysObject_fullname2    = Max ( ro.SysObject_fullname2 )
  , SysObject_schema_name  = Max ( ro.SysObject_schema_name )
  , SysObject_type         = Max ( ro.SysObject_type )
  , SysObject_type_name    = Max ( ro.SysObject_type_name )
  , AdocContent            =
  --
  Concat (
             '= '
           , Max ( ro.SysObject_fullname )
           , Char ( 13 )
           , Char ( 10 )
           --
           , Char ( 13 )
           , Char ( 10 )
           , '== existing_properties'
           , Char ( 13 )
           , Char ( 10 )
           , Char ( 13 )
           , Char ( 10 )
           , '// tag::existing_properties[]'
           , Char ( 13 )
           , Char ( 10 )
           , String_Agg (
                            Concat (
                                       Cast('' As NVarchar(Max))
                                     , Case
                                           When Not rop.property_value Is Null
                                               Then
                                               ':ExistsProperty--' + Lower ( rop.property_name ) + ':' + Char ( 13 )
                                               + Char ( 10 )
                                           Else
                                               ''
                                       End
                                   )
                          , ''
                        ) Within Group(Order By
                                           rop_cross.property_name)
           , Case
                 When Max ( ro.sql_modules_antora ) <> ''
                     Then
                     ':ExistsProperty--sql_modules_definition:' + Char ( 13 ) + Char ( 10 )
             End
           , Case
                 When Max ( ro.SysObject_type ) In
                 ( 'U', 'V' )
                     Then
                     ':ExistsProperty--FK:' + Char ( 13 ) + Char ( 10 )
             End
           , Case
                 When Max ( ilist.AntoraIndexList ) <> ''
                     Then
                     ':ExistsProperty--AntoraIndexList:' + Char ( 13 ) + Char ( 10 )
             End
           , Case
                 When Max ( parlist.AntoraParameterList ) <> ''
                     Then
                     ':ExistsProperty--AntoraParameterList:' + Char ( 13 ) + Char ( 10 )
             End
           , Case
                 When Max ( ro.SysObject_type ) In
                 ( 'U', 'V', 'IF' )
                     Then
                     ':ExistsProperty--Columns:' + Char ( 13 ) + Char ( 10 )
             End
           , '// end::existing_properties[]'
           , Char ( 13 )
           , Char ( 10 )
           --
           , Char ( 13 )
           , Char ( 10 )
           , '== RepoObject_guid'
           , Char ( 13 )
           , Char ( 10 )
           , Char ( 13 )
           , Char ( 10 )
           , '// tag::RepoObject_guid[]'
           , Char ( 13 )
           , Char ( 10 )
           , ro.RepoObject_guid
           , Char ( 13 )
           , Char ( 10 )
           , '// end::RepoObject_guid[]'
           , Char ( 13 )
           , Char ( 10 )
           --
           , Char ( 13 )
           , Char ( 10 )
           , '== SysObject_type'
           , Char ( 13 )
           , Char ( 10 )
           , Char ( 13 )
           , Char ( 10 )
           , '// tag::SysObject_type[]'
           , Char ( 13 )
           , Char ( 10 )
           , Max ( ro.SysObject_type )
           , Char ( 13 )
           , Char ( 10 )
           , '// end::SysObject_type[]'
           , Char ( 13 )
           , Char ( 10 )
           --
           , Char ( 13 )
           , Char ( 10 )
           , '== SysObject_type_name'
           , Char ( 13 )
           , Char ( 10 )
           , Char ( 13 )
           , Char ( 10 )
           , '// tag::SysObject_type_name[]'
           , Char ( 13 )
           , Char ( 10 )
           , Max ( ro.SysObject_type_name )
           , Char ( 13 )
           , Char ( 10 )
           , '// end::SysObject_type_name[]'
           , Char ( 13 )
           , Char ( 10 )
           --
           , Char ( 13 )
           , Char ( 10 )
           , '== SysObject_id'
           , Char ( 13 )
           , Char ( 10 )
           , Char ( 13 )
           , Char ( 10 )
           , '// tag::SysObject_id[]'
           , Char ( 13 )
           , Char ( 10 )
           , Max ( ro.SysObject_id )
           , Char ( 13 )
           , Char ( 10 )
           , '// end::SysObject_id[]'
           , Char ( 13 )
           , Char ( 10 )
           --
           , Char ( 13 )
           , Char ( 10 )
           , '== SysObject_modify_date'
           , Char ( 13 )
           , Char ( 10 )
           , Char ( 13 )
           , Char ( 10 )
           , '// tag::SysObject_modify_date[]'
           , Char ( 13 )
           , Char ( 10 )
           , Convert ( NVarchar(20), Max ( ro.SysObject_modify_date ), 120 )
           , Char ( 13 )
           , Char ( 10 )
           , '// end::SysObject_modify_date[]'
           , Char ( 13 )
           , Char ( 10 )
           --
           , Char ( 13 )
           , Char ( 10 )
           , '== AntoraColumnDetails'
           , Char ( 13 )
           , Char ( 10 )
           , Char ( 13 )
           , Char ( 10 )
           , '// tag::AntoraColumnDetails[]'
           , Char ( 13 )
           , Char ( 10 )
           , Max ( clist.AntoraColumnDetails )
           , Char ( 13 )
           , Char ( 10 )
           , '// end::AntoraColumnDetails[]'
           , Char ( 13 )
           , Char ( 10 )
           --
           , Char ( 13 )
           , Char ( 10 )
           , '== AntoraPkColumnTableRows'
           , Char ( 13 )
           , Char ( 10 )
           , Char ( 13 )
           , Char ( 10 )
           , '// tag::AntoraPkColumnTableRows[]'
           , Char ( 13 )
           , Char ( 10 )
           , Max ( clist.AntoraPkColumnTableRows )
           , Char ( 13 )
           , Char ( 10 )
           , '// end::AntoraPkColumnTableRows[]'
           , Char ( 13 )
           , Char ( 10 )
           --
           , Char ( 13 )
           , Char ( 10 )
           , '== AntoraNonPkColumnTableRows'
           , Char ( 13 )
           , Char ( 10 )
           , Char ( 13 )
           , Char ( 10 )
           , '// tag::AntoraNonPkColumnTableRows[]'
           , Char ( 13 )
           , Char ( 10 )
           , Max ( clist.AntoraNonPkColumnTableRows )
           , Char ( 13 )
           , Char ( 10 )
           , '// end::AntoraNonPkColumnTableRows[]'
           , Char ( 13 )
           , Char ( 10 )
           --
           , Char ( 13 )
           , Char ( 10 )
           , '== AntoraIndexList'
           , Char ( 13 )
           , Char ( 10 )
           , Char ( 13 )
           , Char ( 10 )
           , '// tag::AntoraIndexList[]'
           , Char ( 13 )
           , Char ( 10 )
           , Max ( ilist.AntoraIndexList )
           , Char ( 13 )
           , Char ( 10 )
           , '// end::AntoraIndexList[]'
           , Char ( 13 )
           , Char ( 10 )
           --
           , Char ( 13 )
           , Char ( 10 )
           , '== AntoraParameterList'
           , Char ( 13 )
           , Char ( 10 )
           , Char ( 13 )
           , Char ( 10 )
           , '// tag::AntoraParameterList[]'
           , Char ( 13 )
           , Char ( 10 )
           , Max ( parlist.AntoraParameterList )
           , Char ( 13 )
           , Char ( 10 )
           , '// end::AntoraParameterList[]'
           , Char ( 13 )
           , Char ( 10 )
           , Char ( 13 )
           , Char ( 10 )
           , '== Other tags'
           , Char ( 13 )
           , Char ( 10 )
           , Char ( 13 )
           , Char ( 10 )
           , 'source: property.RepoObjectProperty_cross As rop_cross'
           , Char ( 13 )
           , Char ( 10 )
           , Char ( 13 )
           , Char ( 10 )
           , String_Agg (
                            Concat (
                                       Cast('' As NVarchar(Max))
                                     , Char ( 13 )
                                     , Char ( 10 )
                                     , '=== '
                                     , rop_cross.property_name Collate Database_Default
                                     , Char ( 13 )
                                     , Char ( 10 )
                                     , Char ( 13 )
                                     , Char ( 10 )
                                     , '// tag::'
                                     , Lower ( rop_cross.property_name ) Collate Database_Default
                                     , '[]'
                                     , Char ( 13 )
                                     , Char ( 10 )
                                     , rop.property_value Collate Database_Default
                                     , Char ( 13 )
                                     , Char ( 10 )
                                     , '// end::'
                                     , Lower ( rop_cross.property_name ) Collate Database_Default
                                     , '[]'
                                     , Char ( 13 )
                                     , Char ( 10 )
                                   )
                          , Char ( 13 ) + Char ( 10 )
                        ) Within Group(Order By
                                           rop_cross.property_name)
           , Char ( 13 )
           , Char ( 10 )
           , '== Boolean Attributes'
           , Char ( 13 )
           , Char ( 10 )
           , Char ( 13 )
           , Char ( 10 )
           , 'source: property.RepoObjectProperty WHERE property_int = 1'
           , Char ( 13 )
           , Char ( 10 )
           , Char ( 13 )
           , Char ( 10 )
           , '// tag::boolean_attributes[]'
           , Char ( 13 )
           , Char ( 10 )
           , String_Agg (
                            Concat (
                                       Cast('' As NVarchar(Max))
                                     , Case
                                           When rop.property_int = 1
                                               Then
                                               ':' + Lower ( rop.property_name ) + ':' + Char ( 13 ) + Char ( 10 )
                                           Else
                                               ''
                                       End
                                   )
                          , ''
                        ) Within Group(Order By
                                           rop_cross.property_name)
           , Char ( 13 )
           , Char ( 10 )
           , '// end::boolean_attributes[]'
           , Char ( 13 )
           , Char ( 10 )
           --
           , Char ( 13 )
           , Char ( 10 )
           , '== sql_modules_definition'
           , Char ( 13 )
           , Char ( 10 )
           , Char ( 13 )
           , Char ( 10 )
           , '// tag::sql_modules_definition[]'
           , Char ( 13 )
           , Char ( 10 )
           , '[%collapsible]'
           , Char ( 13 )
           , Char ( 10 )
           , '======='
           , Char ( 13 )
           , Char ( 10 )
           , '[source,sql]'
           , Char ( 13 )
           , Char ( 10 )
           , '----'
           , Char ( 13 )
           , Char ( 10 )
           , Max ( ro.sql_modules_antora )
           , Char ( 13 )
           , Char ( 10 )
           , '----'
           , Char ( 13 )
           , Char ( 10 )
           , '======='
           , Char ( 13 )
           , Char ( 10 )
           , '// end::sql_modules_definition[]'
           , Char ( 13 )
           , Char ( 10 )
           --
           , Char ( 13 )
           , Char ( 10 )
         )
  , PropertyCount          = Count ( Distinct rop.property_name )
From
    repo.RepoObject_gross2                As ro
    Left Join
        property.RepoObjectProperty_cross As rop_cross
            On
            rop_cross.RepoObject_guid = ro.RepoObject_guid

    Left Join
        property.RepoObjectProperty       As rop
            On
            rop.RepoObject_guid       = rop_cross.RepoObject_guid
            And rop.property_name     = rop_cross.property_name
    --AND NOT rop.[property_nvarchar] IS NULL

    Left Join
        docs.RepoObject_ColumnList_T      As clist
            On
            clist.RepoObject_guid     = ro.RepoObject_guid

    Left Join
        docs.RepoObject_IndexList_T       As ilist
            On
            ilist.RepoObject_guid     = ro.RepoObject_guid

    Left Join
        docs.RepoObject_ParameterList     As parlist
            On
            parlist.RepoObject_guid   = ro.RepoObject_guid
Group By
    ro.RepoObject_guid

----
=======
// end::sql_modules_definition[]


