// tag::HeaderFullDisplayName[]
= docs.RepoObject_MeasureList
// end::HeaderFullDisplayName[]

== existing_properties

// tag::existing_properties[]
:ExistsProperty--antorareferencedlist:
:ExistsProperty--antorareferencinglist:
:ExistsProperty--is_repo_managed:
:ExistsProperty--is_ssas:
:ExistsProperty--pk_index_guid:
:ExistsProperty--pk_indexpatterncolumndatatype:
:ExistsProperty--pk_indexpatterncolumnname:
:ExistsProperty--referencedobjectlist:
:ExistsProperty--sql_modules_definition:
:ExistsProperty--FK:
:ExistsProperty--AntoraIndexList:
:ExistsProperty--Columns:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
72E1C56A-C111-EC11-8519-A81E8446D5B0
// end::RepoObject_guid[]

== RepoObject_FullDisplayName2

// tag::RepoObject_FullDisplayName2[]
docs.RepoObject_MeasureList
// end::RepoObject_FullDisplayName2[]

== SysObject_type

// tag::SysObject_type[]
V 
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
view
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
1171535257
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2021-11-03 09:13:44
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]
[discrete]
== _


[#column-repoobjectunderlineguid]
=== RepoObject_guid

[cols="d,8m,m,m,m,d"]
|===
|1
|*RepoObject_guid*
|uniqueidentifier
|NULL
|
|
|===

.Referenced Columns
--
* xref:repo.measures_union.adoc#column-repoobjectunderlineguid[+repo.Measures_union.RepoObject_guid+]
--


[#column-culturesunderlinename]
=== cultures_name

[cols="d,8m,m,m,m,d"]
|===
|2
|*cultures_name*
|nvarchar(10)
|NULL
|
|
|===

.Referenced Columns
--
* xref:docs.repoobject_outputfilter_t.adoc#column-culturesunderlinename[+docs.RepoObject_OutputFilter_T.cultures_name+]
--


[#column-antorameasuredetails]
=== AntoraMeasureDetails

[cols="d,8m,m,m,m,d"]
|===
|
|AntoraMeasureDetails
|nvarchar(max)
|NULL
|
|
|===


[#column-isunderlineexternal]
=== is_external

[cols="d,8m,m,m,m,d"]
|===
|
|is_external
|tinyint
|NULL
|
|
|===

.Referenced Columns
--
* xref:docs.repoobject_outputfilter_t.adoc#column-isunderlineexternal[+docs.RepoObject_OutputFilter_T.is_external+]
--


[#column-plantumlmeasures]
=== PlantumlMeasures

[cols="d,8m,m,m,m,d"]
|===
|
|PlantumlMeasures
|nvarchar(max)
|NULL
|
|
|===


// end::AntoraColumnDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]
|1
|*<<column-repoobjectunderlineguid>>*
|uniqueidentifier
|NULL
|
|

|2
|*<<column-culturesunderlinename>>*
|nvarchar(10)
|NULL
|
|




// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]


|
|<<column-antorameasuredetails>>
|nvarchar(max)
|NULL
|
|

|
|<<column-isunderlineexternal>>
|tinyint
|NULL
|
|

|
|<<column-plantumlmeasures>>
|nvarchar(max)
|NULL
|
|

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

[#index-pkunderlinerepoobjectunderlinemeasurelist]
=== PK_RepoObject_MeasureList

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-RepoObject_guid>>; uniqueidentifier
* <<column-cultures_name>>; nvarchar(10)
--
* PK, Unique, Real: 1, 1, 0


[#index-idxunderlinerepoobjectunderlinemeasurelistunderlineunderline2]
=== idx_RepoObject_MeasureList++__++2

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-cultures_name>>; nvarchar(10)
--
* PK, Unique, Real: 0, 0, 0

// end::AntoraIndexList[]

== AntoraMeasureDetails

// tag::AntoraMeasureDetails[]

// end::AntoraMeasureDetails[]

== AntoraParameterList

// tag::AntoraParameterList[]

// end::AntoraParameterList[]

== AntoraXrefCulturesList

// tag::AntoraXrefCulturesList[]
* xref:dhw:sqldb:docs.repoobject_measurelist.adoc[] - 
// end::AntoraXrefCulturesList[]

== cultures_count

// tag::cultures_count[]
1
// end::cultures_count[]

== Other tags

source: property.RepoObjectProperty_cross As rop_cross


=== additional_reference_csv

// tag::additional_reference_csv[]

// end::additional_reference_csv[]


=== AdocUspSteps

// tag::adocuspsteps[]

// end::adocuspsteps[]


=== AntoraReferencedList

// tag::antorareferencedlist[]
* xref:docs.fs_cleanstringforanchorid.adoc[]
* xref:docs.fs_cleanstringforheader.adoc[]
* xref:docs.fs_cleanstringforpuml.adoc[]
* xref:docs.repoobject_outputfilter_t.adoc[]
* xref:repo.measures_union.adoc[]
* xref:ssas.measures_translation_displayfolder_union.adoc[]
// end::antorareferencedlist[]


=== AntoraReferencingList

// tag::antorareferencinglist[]
* xref:docs.repoobject_adoc.adoc[]
* xref:docs.repoobject_plantuml_entity.adoc[]
// end::antorareferencinglist[]


=== Description

// tag::description[]

// end::description[]


=== ExampleUsage

// tag::exampleusage[]

// end::exampleusage[]


=== exampleUsage_2

// tag::exampleusage_2[]

// end::exampleusage_2[]


=== exampleUsage_3

// tag::exampleusage_3[]

// end::exampleusage_3[]


=== exampleUsage_4

// tag::exampleusage_4[]

// end::exampleusage_4[]


=== exampleUsage_5

// tag::exampleusage_5[]

// end::exampleusage_5[]


=== exampleWrong_Usage

// tag::examplewrong_usage[]

// end::examplewrong_usage[]


=== has_execution_plan_issue

// tag::has_execution_plan_issue[]

// end::has_execution_plan_issue[]


=== has_get_referenced_issue

// tag::has_get_referenced_issue[]

// end::has_get_referenced_issue[]


=== has_history

// tag::has_history[]

// end::has_history[]


=== has_history_columns

// tag::has_history_columns[]

// end::has_history_columns[]


=== InheritanceType

// tag::inheritancetype[]

// end::inheritancetype[]


=== is_persistence

// tag::is_persistence[]

// end::is_persistence[]


=== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]

// end::is_persistence_check_duplicate_per_pk[]


=== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]

// end::is_persistence_check_for_empty_source[]


=== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]

// end::is_persistence_delete_changed[]


=== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]

// end::is_persistence_delete_missing[]


=== is_persistence_insert

// tag::is_persistence_insert[]

// end::is_persistence_insert[]


=== is_persistence_truncate

// tag::is_persistence_truncate[]

// end::is_persistence_truncate[]


=== is_persistence_update_changed

// tag::is_persistence_update_changed[]

// end::is_persistence_update_changed[]


=== is_repo_managed

// tag::is_repo_managed[]
0
// end::is_repo_managed[]


=== is_ssas

// tag::is_ssas[]
0
// end::is_ssas[]


=== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


=== MS_Description

// tag::ms_description[]

// end::ms_description[]


=== persistence_source_RepoObject_fullname

// tag::persistence_source_repoobject_fullname[]

// end::persistence_source_repoobject_fullname[]


=== persistence_source_RepoObject_fullname2

// tag::persistence_source_repoobject_fullname2[]

// end::persistence_source_repoobject_fullname2[]


=== persistence_source_RepoObject_guid

// tag::persistence_source_repoobject_guid[]

// end::persistence_source_repoobject_guid[]


=== persistence_source_RepoObject_xref

// tag::persistence_source_repoobject_xref[]

// end::persistence_source_repoobject_xref[]


=== pk_index_guid

// tag::pk_index_guid[]
2C9EA450-0722-EC11-8524-A81E8446D5B0
// end::pk_index_guid[]


=== pk_IndexPatternColumnDatatype

// tag::pk_indexpatterncolumndatatype[]
uniqueidentifier,nvarchar(10)
// end::pk_indexpatterncolumndatatype[]


=== pk_IndexPatternColumnName

// tag::pk_indexpatterncolumnname[]
RepoObject_guid,cultures_name
// end::pk_indexpatterncolumnname[]


=== pk_IndexSemanticGroup

// tag::pk_indexsemanticgroup[]

// end::pk_indexsemanticgroup[]


=== ReferencedObjectList

// tag::referencedobjectlist[]
* [docs].[fs_cleanStringForAnchorId]
* [docs].[fs_cleanStringForHeader]
* [docs].[fs_cleanStringForPuml]
* [docs].[RepoObject_OutputFilter_T]
* [repo].[Measures_union]
* [ssas].[Measures_translation_displayfolder_union]
// end::referencedobjectlist[]


=== usp_persistence_RepoObject_guid

// tag::usp_persistence_repoobject_guid[]

// end::usp_persistence_repoobject_guid[]


=== UspExamples

// tag::uspexamples[]

// end::uspexamples[]


=== uspgenerator_usp_id

// tag::uspgenerator_usp_id[]

// end::uspgenerator_usp_id[]


=== UspParameters

// tag::uspparameters[]

// end::uspparameters[]

== Boolean Attributes

source: property.RepoObjectProperty WHERE property_int = 1

// tag::boolean_attributes[]

// end::boolean_attributes[]

== sql_modules_definition

// tag::sql_modules_definition[]
[%collapsible]
=======
[source,sql,numbered]
----

CREATE View docs.RepoObject_MeasureList
As
Select
    rom.RepoObject_guid
  , rof.cultures_name
  , is_external          = Max ( Cast(rof.is_external As TinyInt))
  , AntoraMeasureDetails =
  --
  String_Agg (
                 Concat (
                            --we need to convert to first argument nvarchar(max) to avoid the limit of 8000 byte
                            Cast('' As NVarchar(Max))
                          , Iif(transl.is_displayfolder = 1
                              , Concat (
                                           '[discrete]'
                                         , Char ( 13 ) + Char ( 10 )
                                         , '== '
                                         , docs.fs_cleanStringForHeader ( IsNull (
                                                                                     transl.displayfolder_DisplayName
                                                                                   , '_'
                                                                                 )
                                                                        )
                                         , Char ( 13 ) + Char ( 10 )
                                         , Char ( 13 ) + Char ( 10 )
                                       )
                              , Concat (
                                           '[#measure-'
                                         , docs.fs_cleanStringForAnchorId ( transl.Measure_DisplayName )
                                         , ']'
                                         , Char ( 13 ) + Char ( 10 )
                                         , '=== '
                                         , docs.fs_cleanStringForHeader ( transl.Measure_DisplayName )
                                         , Char ( 13 ) + Char ( 10 )
                                         , Char ( 13 ) + Char ( 10 )
                                         --, Case
                                         --      When transl.displayfolder_DisplayName <> ''
                                         --          Then
                                         --          Concat (
                                         --                     '.DisplayFolder: '
                                         --                   , Char ( 13 ) + Char ( 10 )
                                         --                   , '--'
                                         --                   , Char ( 13 ) + Char ( 10 )
                                         --                   , transl.displayfolder_DisplayName
                                         --                   , Char ( 13 ) + Char ( 10 )
                                         --                   , '--'
                                         --                   , Char ( 13 ) + Char ( 10 )
                                         --                   , Char ( 13 ) + Char ( 10 )
                                         --                 )
                                         --  End
                                         , Case
                                               When rom.Description <> ''
                                                   Then
                                                   Concat (
                                                              '.Description'
                                                            , Char ( 13 ) + Char ( 10 )
                                                            , '--'
                                                            , Char ( 13 ) + Char ( 10 )
                                                            , rom.Description
                                                            , Char ( 13 ) + Char ( 10 )
                                                            , '--'
                                                            , Char ( 13 ) + Char ( 10 )
                                                            --add additional line to get more space
                                                            , '{empty} +'
                                                            , Char ( 13 ) + Char ( 10 )
                                                            , Char ( 13 ) + Char ( 10 )
                                                          )
                                           End
                                         , Case
                                               When rom.Expression <> ''
                                                   Then
                                                   Concat (
                                                              '.Expression'
                                                            , Char ( 13 ) + Char ( 10 )
                                                            , '....'
                                                            , Char ( 13 ) + Char ( 10 )
                                                            , rom.Expression
                                                            , Char ( 13 ) + Char ( 10 )
                                                            , '....'
                                                            , Char ( 13 ) + Char ( 10 )
                                                            , Char ( 13 ) + Char ( 10 )
                                                          )
                                           End
                                       )
                          --
                          )
                        )
               , Char ( 13 ) + Char ( 10 )
             ) Within Group(Order By
                                transl.displayfolder_DisplayName
                              , transl.is_displayfolder Desc
                              , transl.Measure_DisplayName)
  , PlantumlMeasures     =
  --
  String_Agg (
                 Concat (
                            Cast('' As NVarchar(Max))
                          , Iif(transl.is_displayfolder = 1
                              , Iif(transl.displayfolder_DisplayName <> ''
                                  , Concat (
                                               '  **'
                                             , docs.fs_cleanStringForPuml ( transl.displayfolder_DisplayName )
                                             , '**'
                                             , Char ( 13 ) + Char ( 10 )
                                           )
                                  , Null)
                              , Concat (
                                           '  ~ '
                                         , Iif(rom.measures_isHidden = 1, '<color:gray>', Null)
                                         , docs.fs_cleanStringForPuml ( transl.Measure_DisplayName )
                                         , Iif(rom.measures_isHidden = 1, ' (hidden)', Null)
                                         , Iif(rom.measures_isHidden = 1, '</color>', Null)
                                         , Char ( 13 ) + Char ( 10 )
                                       )
                          --
                          )
                        )
               , ''
             ) Within Group(Order By
                                transl.displayfolder_DisplayName
                              , transl.is_displayfolder Desc
                              , transl.Measure_DisplayName)
From
    repo.Measures_union                               As rom
    Left Outer Join
        docs.RepoObject_OutputFilter_T                As rof
            On
            rom.RepoObject_guid        = rof.RepoObject_guid

    Left Join
        ssas.Measures_translation_displayfolder_union As transl
            On
            transl.Measure_guid        = rom.Measure_guid
            And transl.cultures_name   = rof.cultures_name
            And transl.RepoObject_name = rof.RepoObject_name
Group By
    rom.RepoObject_guid
  , rof.cultures_name

----
=======
// end::sql_modules_definition[]


