// tag::HeaderFullDisplayName[]
= docs.RepoObject_ColumnList
// end::HeaderFullDisplayName[]

== existing_properties

// tag::existing_properties[]
:ExistsProperty--antorareferencedlist:
:ExistsProperty--antorareferencinglist:
:ExistsProperty--is_repo_managed:
:ExistsProperty--is_ssas:
:ExistsProperty--referencedobjectlist:
:ExistsProperty--sql_modules_definition:
:ExistsProperty--FK:
:ExistsProperty--AntoraIndexList:
:ExistsProperty--Columns:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
9F8B79D5-B993-EB11-84F2-A81E8446D5B0
// end::RepoObject_guid[]

== RepoObject_FullDisplayName2

// tag::RepoObject_FullDisplayName2[]
docs.RepoObject_ColumnList
// end::RepoObject_FullDisplayName2[]

== SysObject_type

// tag::SysObject_type[]
V 
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
view
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
1060914851
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2021-10-04 23:21:04
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]
[#column-antoracolumndetails]
=== antoracolumndetails

[cols="d,8m,m,m,m,d"]
|===
|
|AntoraColumnDetails
|nvarchar(max)
|NULL
|
|
|===

.Referencing Columns
--
* xref:docs.repoobject_columnlist_t.adoc#column-antoracolumndetails[+docs.RepoObject_ColumnList_T.AntoraColumnDetails+]
--


[#column-antoranonpkcolumntablerows]
=== antoranonpkcolumntablerows

[cols="d,8m,m,m,m,d"]
|===
|
|AntoraNonPkColumnTableRows
|nvarchar(max)
|NULL
|
|
|===

.Referencing Columns
--
* xref:docs.repoobject_columnlist_t.adoc#column-antoranonpkcolumntablerows[+docs.RepoObject_ColumnList_T.AntoraNonPkColumnTableRows+]
--


[#column-antorapkcolumntablerows]
=== antorapkcolumntablerows

[cols="d,8m,m,m,m,d"]
|===
|
|AntoraPkColumnTableRows
|nvarchar(max)
|NULL
|
|
|===

.Referencing Columns
--
* xref:docs.repoobject_columnlist_t.adoc#column-antorapkcolumntablerows[+docs.RepoObject_ColumnList_T.AntoraPkColumnTableRows+]
--


[#column-cultures_name]
=== cultures_name

[cols="d,8m,m,m,m,d"]
|===
|
|cultures_name
|nvarchar(10)
|NOT NULL
|
|
|===

.Referenced Columns
--
* xref:docs.repoobject_outputfilter_t.adoc#column-cultures_name[+docs.RepoObject_OutputFilter_T.cultures_name+]
--

.Referencing Columns
--
* xref:docs.repoobject_columnlist_t.adoc#column-cultures_name[+docs.RepoObject_ColumnList_T.cultures_name+]
--


[#column-is_external]
=== is_external

[cols="d,8m,m,m,m,d"]
|===
|
|is_external
|tinyint
|NULL
|
|
|===

.Referenced Columns
--
* xref:docs.repoobject_outputfilter_t.adoc#column-is_external[+docs.RepoObject_OutputFilter_T.is_external+]
* xref:repo.repoobjectcolumn_gross2.adoc#column-is_external[+repo.RepoObjectColumn_gross2.is_external+]
--

.Referencing Columns
--
* xref:docs.repoobject_columnlist_t.adoc#column-is_external[+docs.RepoObject_ColumnList_T.is_external+]
--


[#column-plantumlindexcolumns]
=== plantumlindexcolumns

[cols="d,8m,m,m,m,d"]
|===
|
|PlantumlIndexColumns
|nvarchar(max)
|NULL
|
|
|===

.Referencing Columns
--
* xref:docs.repoobject_columnlist_t.adoc#column-plantumlindexcolumns[+docs.RepoObject_ColumnList_T.PlantumlIndexColumns+]
--


[#column-plantumlnonpkentitycolumns]
=== plantumlnonpkentitycolumns

[cols="d,8m,m,m,m,d"]
|===
|
|PlantumlNonPkEntityColumns
|nvarchar(max)
|NULL
|
|
|===

.Referencing Columns
--
* xref:docs.repoobject_columnlist_t.adoc#column-plantumlnonpkentitycolumns[+docs.RepoObject_ColumnList_T.PlantumlNonPkEntityColumns+]
--


[#column-plantumlnonpkhiddenentitycolumns]
=== plantumlnonpkhiddenentitycolumns

[cols="d,8m,m,m,m,d"]
|===
|
|PlantumlNonPkHiddenEntityColumns
|nvarchar(max)
|NULL
|
|
|===

.Referencing Columns
--
* xref:docs.repoobject_columnlist_t.adoc#column-plantumlnonpkhiddenentitycolumns[+docs.RepoObject_ColumnList_T.PlantumlNonPkHiddenEntityColumns+]
--


[#column-plantumlnonpkindexcolumns]
=== plantumlnonpkindexcolumns

[cols="d,8m,m,m,m,d"]
|===
|
|PlantumlNonPkIndexColumns
|nvarchar(max)
|NULL
|
|
|===

.Referencing Columns
--
* xref:docs.repoobject_columnlist_t.adoc#column-plantumlnonpkindexcolumns[+docs.RepoObject_ColumnList_T.PlantumlNonPkIndexColumns+]
--


[#column-plantumlpkentitycolumns]
=== plantumlpkentitycolumns

[cols="d,8m,m,m,m,d"]
|===
|
|PlantumlPkEntityColumns
|nvarchar(max)
|NULL
|
|
|===

.Referencing Columns
--
* xref:docs.repoobject_columnlist_t.adoc#column-plantumlpkentitycolumns[+docs.RepoObject_ColumnList_T.PlantumlPkEntityColumns+]
--


[#column-repoobject_guid]
=== repoobject_guid

[cols="d,8m,m,m,m,d"]
|===
|
|RepoObject_guid
|uniqueidentifier
|NOT NULL
|
|
|===

.Referenced Columns
--
* xref:docs.repoobject_outputfilter_t.adoc#column-repoobject_guid[+docs.RepoObject_OutputFilter_T.RepoObject_guid+]
--

.Referencing Columns
--
* xref:docs.repoobject_columnlist_t.adoc#column-repoobject_guid[+docs.RepoObject_ColumnList_T.RepoObject_guid+]
--


// end::AntoraColumnDetails[]

== AntoraMeasureDetails

// tag::AntoraMeasureDetails[]

// end::AntoraMeasureDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]











// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]
|
|<<column-antoracolumndetails>>
|nvarchar(max)
|NULL
|
|

|
|<<column-antoranonpkcolumntablerows>>
|nvarchar(max)
|NULL
|
|

|
|<<column-antorapkcolumntablerows>>
|nvarchar(max)
|NULL
|
|

|
|<<column-cultures_name>>
|nvarchar(10)
|NOT NULL
|
|

|
|<<column-is_external>>
|tinyint
|NULL
|
|

|
|<<column-plantumlindexcolumns>>
|nvarchar(max)
|NULL
|
|

|
|<<column-plantumlnonpkentitycolumns>>
|nvarchar(max)
|NULL
|
|

|
|<<column-plantumlnonpkhiddenentitycolumns>>
|nvarchar(max)
|NULL
|
|

|
|<<column-plantumlnonpkindexcolumns>>
|nvarchar(max)
|NULL
|
|

|
|<<column-plantumlpkentitycolumns>>
|nvarchar(max)
|NULL
|
|

|
|<<column-repoobject_guid>>
|uniqueidentifier
|NOT NULL
|
|

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

[#index-idx_repoobject_columnlist2x_1]
=== idx_repoobject_columnlist++__++1

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#openingbracketnoblankgroupclosingbracket[no_group]
+
--
* <<column-RepoObject_guid>>; uniqueidentifier
--
* PK, Unique, Real: 0, 0, 0


[#index-idx_repoobject_columnlist2x_2]
=== idx_repoobject_columnlist++__++2

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#openingbracketnoblankgroupclosingbracket[no_group]
+
--
* <<column-RepoObject_guid>>; uniqueidentifier
* <<column-cultures_name>>; nvarchar(10)
--
* PK, Unique, Real: 0, 0, 0

// end::AntoraIndexList[]

== AntoraParameterList

// tag::AntoraParameterList[]

// end::AntoraParameterList[]

== Other tags

source: property.RepoObjectProperty_cross As rop_cross


=== additional_reference_csv

// tag::additional_reference_csv[]

// end::additional_reference_csv[]


=== AdocUspSteps

// tag::adocuspsteps[]

// end::adocuspsteps[]


=== AntoraReferencedList

// tag::antorareferencedlist[]
* xref:docs.fs_cleanstringforanchorid.adoc[]
* xref:docs.fs_cleanstringforlabel.adoc[]
* xref:docs.fs_cleanstringforpuml.adoc[]
* xref:docs.repoobject_outputfilter_t.adoc[]
* xref:repo.repoobjectcolumn_gross2.adoc[]
* xref:ssas.repoobjectcolumn_translation_t.adoc[]
// end::antorareferencedlist[]


=== AntoraReferencingList

// tag::antorareferencinglist[]
* xref:docs.repoobject_columnlist_t.adoc[]
* xref:docs.usp_persist_repoobject_columnlist_t.adoc[]
// end::antorareferencinglist[]


=== Description

// tag::description[]

// end::description[]


=== exampleUsage

// tag::exampleusage[]

// end::exampleusage[]


=== exampleUsage_2

// tag::exampleusage_2[]

// end::exampleusage_2[]


=== exampleUsage_3

// tag::exampleusage_3[]

// end::exampleusage_3[]


=== exampleUsage_4

// tag::exampleusage_4[]

// end::exampleusage_4[]


=== exampleUsage_5

// tag::exampleusage_5[]

// end::exampleusage_5[]


=== exampleWrong_Usage

// tag::examplewrong_usage[]

// end::examplewrong_usage[]


=== has_execution_plan_issue

// tag::has_execution_plan_issue[]

// end::has_execution_plan_issue[]


=== has_get_referenced_issue

// tag::has_get_referenced_issue[]

// end::has_get_referenced_issue[]


=== has_history

// tag::has_history[]

// end::has_history[]


=== has_history_columns

// tag::has_history_columns[]

// end::has_history_columns[]


=== InheritanceType

// tag::inheritancetype[]

// end::inheritancetype[]


=== is_persistence

// tag::is_persistence[]

// end::is_persistence[]


=== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]

// end::is_persistence_check_duplicate_per_pk[]


=== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]

// end::is_persistence_check_for_empty_source[]


=== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]

// end::is_persistence_delete_changed[]


=== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]

// end::is_persistence_delete_missing[]


=== is_persistence_insert

// tag::is_persistence_insert[]

// end::is_persistence_insert[]


=== is_persistence_truncate

// tag::is_persistence_truncate[]

// end::is_persistence_truncate[]


=== is_persistence_update_changed

// tag::is_persistence_update_changed[]

// end::is_persistence_update_changed[]


=== is_repo_managed

// tag::is_repo_managed[]
0
// end::is_repo_managed[]


=== is_ssas

// tag::is_ssas[]
0
// end::is_ssas[]


=== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


=== MS_Description

// tag::ms_description[]

// end::ms_description[]


=== persistence_source_RepoObject_fullname

// tag::persistence_source_repoobject_fullname[]

// end::persistence_source_repoobject_fullname[]


=== persistence_source_RepoObject_fullname2

// tag::persistence_source_repoobject_fullname2[]

// end::persistence_source_repoobject_fullname2[]


=== persistence_source_RepoObject_guid

// tag::persistence_source_repoobject_guid[]

// end::persistence_source_repoobject_guid[]


=== persistence_source_RepoObject_xref

// tag::persistence_source_repoobject_xref[]

// end::persistence_source_repoobject_xref[]


=== pk_index_guid

// tag::pk_index_guid[]

// end::pk_index_guid[]


=== pk_IndexPatternColumnDatatype

// tag::pk_indexpatterncolumndatatype[]

// end::pk_indexpatterncolumndatatype[]


=== pk_IndexPatternColumnName

// tag::pk_indexpatterncolumnname[]

// end::pk_indexpatterncolumnname[]


=== pk_IndexSemanticGroup

// tag::pk_indexsemanticgroup[]

// end::pk_indexsemanticgroup[]


=== ReferencedObjectList

// tag::referencedobjectlist[]
* [docs].[fs_cleanStringForAnchorId]
* [docs].[fs_cleanStringForLabel]
* [docs].[fs_cleanStringForPuml]
* [docs].[RepoObject_OutputFilter_T]
* [repo].[RepoObjectColumn_gross2]
* [ssas].[RepoObjectColumn_translation_T]
// end::referencedobjectlist[]


=== usp_persistence_RepoObject_guid

// tag::usp_persistence_repoobject_guid[]

// end::usp_persistence_repoobject_guid[]


=== UspExamples

// tag::uspexamples[]

// end::uspexamples[]


=== uspgenerator_usp_id

// tag::uspgenerator_usp_id[]

// end::uspgenerator_usp_id[]


=== UspParameters

// tag::uspparameters[]

// end::uspparameters[]

== Boolean Attributes

source: property.RepoObjectProperty WHERE property_int = 1

// tag::boolean_attributes[]

// end::boolean_attributes[]

== sql_modules_definition

// tag::sql_modules_definition[]
[%collapsible]
=======
[source,sql]
----

/*
alternative columns sort order for documentation:
- PK
- columns by name
*/
CREATE View docs.RepoObject_ColumnList
As
Select
    rof.RepoObject_guid
  , rof.cultures_name
  , is_external                      = Max ( Cast(rof.is_external As TinyInt))
  , AntoraColumnDetails              =
  --
  String_Agg (
                 Concat (
                            --we need to convert to first argument nvarchar(max) to avoid the limit of 8000 byte
                            Cast('' As NVarchar(Max))
                          , '[#column-'
                          --, '[id=column-'
                          --, '[[column-' --deprecated
                          , docs.fs_cleanStringForAnchorId ( transl.RepoObjectColumn_DisplayName )
                          --, ']]'
                          , ']'
                          , Char ( 13 ) + Char ( 10 )
                          , '=== '
                          --, transl.RepoObjectColumn_DisplayName
                          , docs.fs_cleanStringForLabel ( transl.RepoObjectColumn_DisplayName )
                          , Char ( 13 ) + Char ( 10 )
                          , Char ( 13 ) + Char ( 10 )
                          , '[cols="d,8m,m,m,m,d"]'
                          , Char ( 13 ) + Char ( 10 )
                          , '|==='
                          , Char ( 13 ) + Char ( 10 )
                          , Concat (
                                       '|'
                                     , roc.index_column_id
                                     , Char ( 13 ) + Char ( 10 )
                                     , '|'
                                     , Iif(roc.is_index_primary_key = 1, '*', '')
                                     , transl.RepoObjectColumn_DisplayName
                                     , Iif(roc.is_index_primary_key = 1, '*', '')
                                     , Char ( 13 ) + Char ( 10 )
                                     , '|'
                                     , roc.Repo_user_type_fullname
                                     , Char ( 13 ) + Char ( 10 )
                                     , '|'
                                     , Iif(roc.Repo_is_nullable = 0, 'NOT NULL', 'NULL')
                                     , Char ( 13 ) + Char ( 10 )
                                     , '|'
                                     , Iif(roc.Repo_is_identity = 1
                                         , '(' + Cast(roc.Repo_seed_value As NVarchar(4000)) + ','
                                           + Cast(roc.Repo_increment_value As NVarchar(4000)) + ')'
                                         , Null)
                                     , Char ( 13 ) + Char ( 10 )
                                     , '|'
                                     , Iif(roc.Repo_is_computed = 1
                                           , Iif(roc.Repo_is_persisted = 1, 'Persisted', 'Calc')
                                           , Null)
                                     , Char ( 13 ) + Char ( 10 )
                                   )
                          , '|==='
                          , Char ( 13 ) + Char ( 10 )
                          , Char ( 13 ) + Char ( 10 )
                          , Case
                                When roc.Description <> ''
                                    Then
                                    Concat (
                                               '.Description'
                                             , Char ( 13 ) + Char ( 10 )
                                             , '--'
                                             , Char ( 13 ) + Char ( 10 )
                                             , roc.Description
                                             , Char ( 13 ) + Char ( 10 )
                                             , '--'
                                             , Char ( 13 ) + Char ( 10 )
                                             --add additional line to get more space
                                             , '{empty} +'
                                             , Char ( 13 ) + Char ( 10 )
                                             , Char ( 13 ) + Char ( 10 )
                                           )
                            End
                          , Case
                                When roc.Repo_default_definition <> ''
                                    Then
                                    Concat (
                                               '.Default: '
                                             , roc.Repo_default_name
                                             , Char ( 13 ) + Char ( 10 )
                                             , '....'
                                             , Char ( 13 ) + Char ( 10 )
                                             , roc.Repo_default_definition
                                             , Char ( 13 ) + Char ( 10 )
                                             , '....'
                                             , Char ( 13 ) + Char ( 10 )
                                             , Char ( 13 ) + Char ( 10 )
                                           )
                            End
                          , Case
                                When roc.Repo_definition <> ''
                                    Then
                                    Concat (
                                               '.Definition'
                                             , Iif(roc.Repo_is_persisted = 1, ' (PERSISTED)', Null)
                                             , Char ( 13 ) + Char ( 10 )
                                             , '....'
                                             , Char ( 13 ) + Char ( 10 )
                                             , roc.Repo_definition
                                             , Char ( 13 ) + Char ( 10 )
                                             , '....'
                                             , Char ( 13 ) + Char ( 10 )
                                             , Char ( 13 ) + Char ( 10 )
                                           )
                            End
                          , Case
                                When roc.has_get_referenced_issue = 1
                                    Then
                                    Concat (
                                               '.has_get_referenced_issue'
                                             , Char ( 13 ) + Char ( 10 )
                                             , '....'
                                             , Char ( 13 ) + Char ( 10 )
                                             , roc.has_get_referenced_issue
                                             , Char ( 13 ) + Char ( 10 )
                                             , '....'
                                             , Char ( 13 ) + Char ( 10 )
                                             , Char ( 13 ) + Char ( 10 )
                                           )
                            End
                          , Case
                                When roc.AntoraReferencedColumnList <> ''
                                    Then
                                    Concat (
                                               '.Referenced Columns'
                                             , Char ( 13 ) + Char ( 10 )
                                             , '--'
                                             , Char ( 13 ) + Char ( 10 )
                                             , roc.AntoraReferencedColumnList
                                             , Char ( 13 ) + Char ( 10 )
                                             , '--'
                                             , Char ( 13 ) + Char ( 10 )
                                             , Char ( 13 ) + Char ( 10 )
                                           )
                            End
                          , Case
                                When roc.AntoraReferencingColumnList <> ''
                                    Then
                                    Concat (
                                               '.Referencing Columns'
                                             , Char ( 13 ) + Char ( 10 )
                                             , '--'
                                             , Char ( 13 ) + Char ( 10 )
                                             , roc.AntoraReferencingColumnList
                                             , Char ( 13 ) + Char ( 10 )
                                             , '--'
                                             , Char ( 13 ) + Char ( 10 )
                                             , Char ( 13 ) + Char ( 10 )
                                           )
                            End
                        )
               , Char ( 13 ) + Char ( 10 )
             ) Within Group(Order By
                                roc.is_index_primary_key Desc
                              , roc.tabcol_IsHidden
                              , roc.index_column_id
                              , roc.Repo_is_computed
                              , transl.RepoObjectColumn_DisplayName)
  , AntoraPkColumnTableRows          =
  --
  String_Agg (
                 Concat (
                            --we need to convert to first argument nvarchar(max) to avoid the limit of 8000 byte
                            Cast('' As NVarchar(Max))
                          , Case
                                When roc.is_index_primary_key = 1
                                    Then
                                    Concat (
                                               '|'
                                             , roc.index_column_id
                                             , Char ( 13 ) + Char ( 10 )
                                             , '|'
                                             , '*'
                                             , '<<column-'
                                             , docs.fs_cleanStringForAnchorId ( transl.RepoObjectColumn_DisplayName )
                                             , '>>'
                                             , '*'
                                             , Char ( 13 ) + Char ( 10 )
                                             , '|'
                                             , roc.Repo_user_type_fullname
                                             , Char ( 13 ) + Char ( 10 )
                                             , '|'
                                             , Iif(roc.Repo_is_nullable = 0, 'NOT NULL', 'NULL')
                                             , Char ( 13 ) + Char ( 10 )
                                             , '|'
                                             , Iif(roc.Repo_is_identity = 1
                                                 , '(' + Cast(roc.Repo_seed_value As NVarchar(4000)) + ','
                                                   + Cast(roc.Repo_increment_value As NVarchar(4000)) + ')'
                                                 , Null)
                                             , Char ( 13 ) + Char ( 10 )
                                             , '|'
                                             , Iif(roc.Repo_is_computed = 1
                                                   , Iif(roc.Repo_is_persisted = 1, 'Persisted', 'Calc')
                                                   , Null)
                                             , Char ( 13 ) + Char ( 10 )
                                           )
                            End
                        )
               , Char ( 13 ) + Char ( 10 )
             ) Within Group(Order By
                                roc.is_index_primary_key Desc
                              , roc.tabcol_IsHidden
                              , roc.index_column_id
                              , roc.Repo_is_computed
                              , transl.RepoObjectColumn_DisplayName)
  , AntoraNonPkColumnTableRows       =
  --
  String_Agg (
                 Concat (
                            --we need to convert to first argument nvarchar(max) to avoid the limit of 8000 byte
                            Cast('' As NVarchar(Max))
                          , Case
                                When IsNull ( roc.is_index_primary_key, 0 ) = 0
                                    Then
                                    Concat (
                                               '|'
                                             --, roc.[index_column_id]
                                             , Char ( 13 ) + Char ( 10 )
                                             , '|'
                                             , '<<column-'
                                             , docs.fs_cleanStringForAnchorId ( transl.RepoObjectColumn_DisplayName )
                                             , '>>'
                                             , Char ( 13 ) + Char ( 10 )
                                             , '|'
                                             , roc.Repo_user_type_fullname
                                             , Char ( 13 ) + Char ( 10 )
                                             , '|'
                                             , Iif(roc.Repo_is_nullable = 0, 'NOT NULL', 'NULL')
                                             , Char ( 13 ) + Char ( 10 )
                                             , '|'
                                             , Iif(roc.Repo_is_identity = 1
                                                 , '(' + Cast(roc.Repo_seed_value As NVarchar(4000)) + ','
                                                   + Cast(roc.Repo_increment_value As NVarchar(4000)) + ')'
                                                 , Null)
                                             , Char ( 13 ) + Char ( 10 )
                                             , '|'
                                             , Iif(roc.Repo_is_computed = 1
                                                   , Iif(roc.Repo_is_persisted = 1, 'Persisted', 'Calc')
                                                   , Null)
                                             , Char ( 13 ) + Char ( 10 )
                                           )
                            End
                        )
               , Char ( 13 ) + Char ( 10 )
             ) Within Group(Order By
                                roc.is_index_primary_key Desc
                              , roc.tabcol_IsHidden
                              , roc.index_column_id
                              , roc.Repo_is_computed
                              , transl.RepoObjectColumn_DisplayName)
  , PlantumlPkEntityColumns          =
  --
  String_Agg (
                 Concat (
                            Cast('' As NVarchar(Max))
                          , Case
                                When roc.is_index_primary_key = 1
                                    Then
                                    Concat (
                                               '  '
                                             , Case
                                                   When roc.Repo_is_computed = 1
                                                       Then
                                                       --rhombus or triangle
                                                       Iif(roc.Repo_is_persisted = 1, '# ', '~ ')
                                                   Else
                                                       -- '- ' to identify mandatory attributes, but not for calculated columns,
                                                       -- to avoid a mix '- #' or '- ~'
                                                       Iif(roc.Repo_is_nullable = 0, '- ', Null)
                                               End
                                             , Iif(roc.tabcol_IsHidden = 1, '<color:gray>', Null)
                                             --PK in bold
                                             , '**'
                                             , docs.fs_cleanStringForPuml ( transl.RepoObjectColumn_DisplayName )
                                             , '**'
                                             --we add () to get a puml "method" to get unique icons
                                             , ' : (' + roc.Repo_user_type_fullname + ')'
                                             , Iif(roc.tabcol_IsHidden = 1, ' (hidden)', Null)
                                             --, CASE 
                                             -- WHEN roc.[Repo_is_computed] = 1
                                             --  THEN ' <<calc' + IIF(roc.[Repo_is_persisted] = 1, ' (Persisted)', '') + '>>'
                                             -- END
                                             , Iif(roc.tabcol_IsHidden = 1, '</color>', Null)
                                             , Char ( 13 ) + Char ( 10 )
                                           )
                            End
                        )
               , ''
             ) Within Group(Order By
                                roc.is_index_primary_key Desc
                              , roc.tabcol_IsHidden
                              , roc.index_column_id
                              , roc.Repo_is_computed
                              , transl.RepoObjectColumn_DisplayName)
  , PlantumlNonPkEntityColumns       =
  --
  String_Agg (
                 Concat (
                            Cast('' As NVarchar(Max))
                          , Case
                                When IsNull ( roc.is_index_primary_key, 0 ) = 0
                                     And roc.tabcol_IsHidden = 0
                                    Then
                                    Concat (
                                               '  '
                                             , Case
                                                   When roc.Repo_is_computed = 1
                                                       Then
                                                       --rhombus or triangle
                                                       Iif(roc.Repo_is_persisted = 1, '# ', '~ ')
                                                   Else
                                                       -- '- ' to identify mandatory attributes, but not for calculated columns,
                                                       -- to avoid a mix '- #' or '- ~'
                                                       Iif(roc.Repo_is_nullable = 0, '- ', Null)
                                               End
                                             , Iif(roc.tabcol_IsHidden = 1, '<color:gray>', Null)
                                             , docs.fs_cleanStringForPuml ( transl.RepoObjectColumn_DisplayName )
                                             --we add () to get a puml "method" to get unique icons
                                             , ' : (' + roc.Repo_user_type_fullname + ')'
                                             , Iif(roc.tabcol_IsHidden = 1, ' (hidden)', Null)
                                             --, CASE 
                                             -- WHEN roc.[Repo_is_computed] = 1
                                             --  THEN ' <<calc' + IIF(roc.[Repo_is_persisted] = 1, ' (Persisted)', '') + '>>'
                                             -- END
                                             , Iif(roc.tabcol_IsHidden = 1, '</color>', Null)
                                             , Char ( 13 ) + Char ( 10 )
                                           )
                            End
                        )
               , ''
             ) Within Group(Order By
                                roc.is_index_primary_key Desc
                              , roc.tabcol_IsHidden
                              , roc.index_column_id
                              , roc.Repo_is_computed
                              , transl.RepoObjectColumn_DisplayName)
  , PlantumlNonPkIndexColumns        =
  --
  String_Agg (
                 Concat (
                            Cast('' As NVarchar(Max))
                          , Case
                                When IsNull ( roc.is_index_primary_key, 0 ) = 0
                                     And roc.isAnyIndexColumn = 1
                                    Then
                                    Concat (
                                               '  '
                                             , Case
                                                   When roc.Repo_is_computed = 1
                                                       Then
                                                       --rhombus or triangle
                                                       Iif(roc.Repo_is_persisted = 1, '# ', '~ ')
                                                   Else
                                                       -- '- ' to identify mandatory attributes, but not for calculated columns,
                                                       -- to avoid a mix '- #' or '- ~'
                                                       Iif(roc.Repo_is_nullable = 0, '- ', Null)
                                               End
                                             , Iif(roc.tabcol_IsHidden = 1, '<color:gray>', Null)
                                             , docs.fs_cleanStringForPuml ( transl.RepoObjectColumn_DisplayName )
                                             --we add () to get a puml "method" to get unique icons
                                             , ' : (' + roc.Repo_user_type_fullname + ')'
                                             , Iif(roc.tabcol_IsHidden = 1, ' (hidden)', Null)
                                             --, CASE 
                                             -- WHEN roc.[Repo_is_computed] = 1
                                             --  THEN ' <<calc' + IIF(roc.[Repo_is_persisted] = 1, ' (Persisted)', '') + '>>'
                                             -- END
                                             , Iif(roc.tabcol_IsHidden = 1, '</color>', Null)
                                             , Char ( 13 ) + Char ( 10 )
                                           )
                            End
                        )
               , ''
             ) Within Group(Order By
                                roc.is_index_primary_key Desc
                              , roc.tabcol_IsHidden
                              , roc.index_column_id
                              , roc.Repo_is_computed
                              , transl.RepoObjectColumn_DisplayName)
  , PlantumlNonPkHiddenEntityColumns =
  --
  String_Agg (
                 Concat (
                            Cast('' As NVarchar(Max))
                          , Case
                                When IsNull ( roc.is_index_primary_key, 0 ) = 0
                                     And roc.tabcol_IsHidden = 1
                                    Then
                                    Concat (
                                               '  '
                                             , Case
                                                   When roc.Repo_is_computed = 1
                                                       Then
                                                       --rhombus or triangle
                                                       Iif(roc.Repo_is_persisted = 1, '# ', '~ ')
                                                   Else
                                                       -- '- ' to identify mandatory attributes, but not for calculated columns,
                                                       -- to avoid a mix '- #' or '- ~'
                                                       Iif(roc.Repo_is_nullable = 0, '- ', Null)
                                               End
                                             , Iif(roc.tabcol_IsHidden = 1, '<color:gray>', Null)
                                             , docs.fs_cleanStringForPuml ( transl.RepoObjectColumn_DisplayName )
                                             --we add () to get a puml "method" to get unique icons
                                             , ' : (' + roc.Repo_user_type_fullname + ')'
                                             , Iif(roc.tabcol_IsHidden = 1, ' (hidden)', Null)
                                             --, CASE 
                                             -- WHEN roc.[Repo_is_computed] = 1
                                             --  THEN ' <<calc' + IIF(roc.[Repo_is_persisted] = 1, ' (Persisted)', '') + '>>'
                                             -- END
                                             , Iif(roc.tabcol_IsHidden = 1, '</color>', Null)
                                             , Char ( 13 ) + Char ( 10 )
                                           )
                            End
                        )
               , ''
             ) Within Group(Order By
                                roc.is_index_primary_key Desc
                              , roc.tabcol_IsHidden
                              , roc.index_column_id
                              , roc.Repo_is_computed
                              , transl.RepoObjectColumn_DisplayName)
  , PlantumlIndexColumns             =
  --
  String_Agg (
                 Concat (
                            Cast('' As NVarchar(Max))
                          , Case
                                When roc.isAnyIndexColumn = 1
                                    Then
                                    Concat (
                                               '  '
                                             , Case
                                                   When roc.Repo_is_computed = 1
                                                       Then
                                                       --rhombus or triangle
                                                       Iif(roc.Repo_is_persisted = 1, '# ', '~ ')
                                                   Else
                                                       -- '- ' to identify mandatory attributes, but not for calculated columns,
                                                       -- to avoid a mix '- #' or '- ~'
                                                       Iif(roc.Repo_is_nullable = 0, '- ', Null)
                                               End
                                             , Iif(roc.tabcol_IsHidden = 1, '<color:gray>', Null)
                                             , docs.fs_cleanStringForPuml ( transl.RepoObjectColumn_DisplayName )
                                             --we add () to get a puml "method" to get unique icons
                                             , ' : (' + roc.Repo_user_type_fullname + ')'
                                             , Iif(roc.tabcol_IsHidden = 1, ' (hidden)', Null)
                                             --, CASE 
                                             -- WHEN roc.[Repo_is_computed] = 1
                                             --  THEN ' <<calc' + IIF(roc.[Repo_is_persisted] = 1, ' (Persisted)', '') + '>>'
                                             -- END
                                             , Iif(roc.tabcol_IsHidden = 1, '</color>', Null)
                                             , Char ( 13 ) + Char ( 10 )
                                           )
                            End
                        )
               , ''
             ) Within Group(Order By
                                roc.is_index_primary_key Desc
                              , roc.tabcol_IsHidden
                              , roc.index_column_id
                              , roc.Repo_is_computed
                              , transl.RepoObjectColumn_DisplayName)
From
    docs.RepoObject_OutputFilter_T          As rof
    Left Join
        repo.RepoObjectColumn_gross2        As roc
            On
            roc.RepoObject_guid          = rof.RepoObject_guid

    Left Join
        ssas.RepoObjectColumn_translation_T As transl
            On
            transl.RepoObjectColumn_guid = roc.RepoObjectColumn_guid
            And transl.cultures_name     = rof.cultures_name
Where
    --not [is_query_plan_expression], these are not real columms
    roc.is_query_plan_expression Is Null
    --And roc.is_external         = 0
    --we need the datatype, or it should be computed
    And
    (
        Not roc.Repo_user_type_fullname Is Null
        Or roc.Repo_is_computed = 1
        Or rof.is_external      = 1
    )
----exclude system columns like 'RowNumber-2662979B-1795-4F74-8F37-6A1BA8059B61'
----all they have ssas_Type = 3
--And Not roc.ssas_Type = 3
Group By
    rof.RepoObject_guid
  , rof.cultures_name

----
=======
// end::sql_modules_definition[]


