// tag::HeaderFullDisplayName[]
= docs.ssis_DftTaskComponentList
// end::HeaderFullDisplayName[]

== existing_properties

// tag::existing_properties[]
:ExistsProperty--antorareferencedlist:
:ExistsProperty--antorareferencinglist:
:ExistsProperty--is_repo_managed:
:ExistsProperty--is_ssas:
:ExistsProperty--referencedobjectlist:
:ExistsProperty--sql_modules_definition:
:ExistsProperty--FK:
:ExistsProperty--Columns:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
6ADDD159-FC3E-EC11-852D-A81E8446D5B0
// end::RepoObject_guid[]

== RepoObject_FullDisplayName2

// tag::RepoObject_FullDisplayName2[]
docs.ssis_DftTaskComponentList
// end::RepoObject_FullDisplayName2[]

== SysObject_type

// tag::SysObject_type[]
V 
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
view
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
318676233
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2021-11-08 17:41:26
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]
[discrete]
== _


[#column-antoramodule]
=== AntoraModule

[cols="d,8m,m,m,m,d"]
|===
|
|AntoraModule
|varchar(50)
|NOT NULL
|
|
|===

.Referenced Columns
--
* xref:ssis.packagetask_dft_component.adoc#column-antoramodule[+ssis.PackageTask_Dft_Component.AntoraModule+]
--


[#column-dfttaskcomponentlist]
=== DftTaskComponentList

[cols="d,8m,m,m,m,d"]
|===
|
|DftTaskComponentList
|nvarchar(max)
|NULL
|
|
|===


[#column-packagename]
=== PackageName

[cols="d,8m,m,m,m,d"]
|===
|
|PackageName
|varchar(200)
|NOT NULL
|
|
|===

.Referenced Columns
--
* xref:ssis.packagetask_dft_component.adoc#column-packagename[+ssis.PackageTask_Dft_Component.PackageName+]
--


[#column-taskpath]
=== TaskPath

[cols="d,8m,m,m,m,d"]
|===
|
|TaskPath
|varchar(8000)
|NOT NULL
|
|
|===

.Referenced Columns
--
* xref:ssis.packagetask_dft_component.adoc#column-taskpath[+ssis.PackageTask_Dft_Component.TaskPath+]
--


// end::AntoraColumnDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]




// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]
|
|<<column-antoramodule>>
|varchar(50)
|NOT NULL
|
|

|
|<<column-dfttaskcomponentlist>>
|nvarchar(max)
|NULL
|
|

|
|<<column-packagename>>
|varchar(200)
|NOT NULL
|
|

|
|<<column-taskpath>>
|varchar(8000)
|NOT NULL
|
|

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

// end::AntoraIndexList[]

== AntoraMeasureDetails

// tag::AntoraMeasureDetails[]

// end::AntoraMeasureDetails[]

== AntoraParameterList

// tag::AntoraParameterList[]

// end::AntoraParameterList[]

== AntoraXrefCulturesList

// tag::AntoraXrefCulturesList[]
* xref:dhw:sqldb:docs.ssis_dfttaskcomponentlist.adoc[] - 
// end::AntoraXrefCulturesList[]

== cultures_count

// tag::cultures_count[]
1
// end::cultures_count[]

== Other tags

source: property.RepoObjectProperty_cross As rop_cross


=== additional_reference_csv

// tag::additional_reference_csv[]

// end::additional_reference_csv[]


=== AdocUspSteps

// tag::adocuspsteps[]

// end::adocuspsteps[]


=== AntoraReferencedList

// tag::antorareferencedlist[]
* xref:docs.fs_cleanstringforanchorid.adoc[]
* xref:docs.fs_cleanstringforheader.adoc[]
* xref:docs.ssis_dfttaskcomponentinputlist.adoc[]
* xref:docs.ssis_dfttaskcomponentoutputlist.adoc[]
* xref:docs.ssis_pumlpartialdftcomponent.adoc[]
* xref:ssis.packagetask_dft_component.adoc[]
// end::antorareferencedlist[]


=== AntoraReferencingList

// tag::antorareferencinglist[]
* xref:docs.ssis_task.adoc[]
* xref:docs.ssis_tasklist.adoc[]
// end::antorareferencinglist[]


=== Description

// tag::description[]

// end::description[]


=== ExampleUsage

// tag::exampleusage[]

// end::exampleusage[]


=== exampleUsage_2

// tag::exampleusage_2[]

// end::exampleusage_2[]


=== exampleUsage_3

// tag::exampleusage_3[]

// end::exampleusage_3[]


=== exampleUsage_4

// tag::exampleusage_4[]

// end::exampleusage_4[]


=== exampleUsage_5

// tag::exampleusage_5[]

// end::exampleusage_5[]


=== exampleWrong_Usage

// tag::examplewrong_usage[]

// end::examplewrong_usage[]


=== has_execution_plan_issue

// tag::has_execution_plan_issue[]

// end::has_execution_plan_issue[]


=== has_get_referenced_issue

// tag::has_get_referenced_issue[]

// end::has_get_referenced_issue[]


=== has_history

// tag::has_history[]

// end::has_history[]


=== has_history_columns

// tag::has_history_columns[]

// end::has_history_columns[]


=== InheritanceType

// tag::inheritancetype[]

// end::inheritancetype[]


=== is_persistence

// tag::is_persistence[]

// end::is_persistence[]


=== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]

// end::is_persistence_check_duplicate_per_pk[]


=== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]

// end::is_persistence_check_for_empty_source[]


=== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]

// end::is_persistence_delete_changed[]


=== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]

// end::is_persistence_delete_missing[]


=== is_persistence_insert

// tag::is_persistence_insert[]

// end::is_persistence_insert[]


=== is_persistence_truncate

// tag::is_persistence_truncate[]

// end::is_persistence_truncate[]


=== is_persistence_update_changed

// tag::is_persistence_update_changed[]

// end::is_persistence_update_changed[]


=== is_repo_managed

// tag::is_repo_managed[]
0
// end::is_repo_managed[]


=== is_ssas

// tag::is_ssas[]
0
// end::is_ssas[]


=== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


=== MS_Description

// tag::ms_description[]

// end::ms_description[]


=== persistence_source_RepoObject_fullname

// tag::persistence_source_repoobject_fullname[]

// end::persistence_source_repoobject_fullname[]


=== persistence_source_RepoObject_fullname2

// tag::persistence_source_repoobject_fullname2[]

// end::persistence_source_repoobject_fullname2[]


=== persistence_source_RepoObject_guid

// tag::persistence_source_repoobject_guid[]

// end::persistence_source_repoobject_guid[]


=== persistence_source_RepoObject_xref

// tag::persistence_source_repoobject_xref[]

// end::persistence_source_repoobject_xref[]


=== pk_index_guid

// tag::pk_index_guid[]

// end::pk_index_guid[]


=== pk_IndexPatternColumnDatatype

// tag::pk_indexpatterncolumndatatype[]

// end::pk_indexpatterncolumndatatype[]


=== pk_IndexPatternColumnName

// tag::pk_indexpatterncolumnname[]

// end::pk_indexpatterncolumnname[]


=== pk_IndexSemanticGroup

// tag::pk_indexsemanticgroup[]

// end::pk_indexsemanticgroup[]


=== ReferencedObjectList

// tag::referencedobjectlist[]
* [docs].[fs_cleanStringForAnchorId]
* [docs].[fs_cleanStringForHeader]
* [docs].[ssis_DftTaskComponentInputList]
* [docs].[ssis_DftTaskComponentOutputList]
* [docs].[ssis_PumlPartialDftComponent]
* [ssis].[PackageTask_Dft_Component]
// end::referencedobjectlist[]


=== usp_persistence_RepoObject_guid

// tag::usp_persistence_repoobject_guid[]

// end::usp_persistence_repoobject_guid[]


=== UspExamples

// tag::uspexamples[]

// end::uspexamples[]


=== uspgenerator_usp_id

// tag::uspgenerator_usp_id[]

// end::uspgenerator_usp_id[]


=== UspParameters

// tag::uspparameters[]

// end::uspparameters[]

== Boolean Attributes

source: property.RepoObjectProperty WHERE property_int = 1

// tag::boolean_attributes[]

// end::boolean_attributes[]

== sql_modules_definition

// tag::sql_modules_definition[]
[%collapsible]
=======
[source,sql,numbered]
----
CREATE View [docs].[ssis_DftTaskComponentList]
As
Select
    T1.AntoraModule
  , T1.PackageName
  , T1.TaskPath
  , DftTaskComponentList =
  --
  String_Agg (
                 Concat (
                            Cast(N'' As NVarchar(Max))
                          , '[#dftcomponent-'
                          , docs.fs_cleanStringForAnchorId ( T1.Component_refId )
                          , ']'
                          , Char ( 13 ) + Char ( 10 )
                          , '==== '
                          , docs.fs_cleanStringForHeader ( T1.Component_name )
                          , Char ( 13 ) + Char ( 10 ) + Char ( 13 ) + Char ( 10 )

                          ----begin collapsible
                          --, '.' + docs.fs_cleanStringForHeader ( T1.Component_name ) + Char ( 13 ) + Char ( 10 )
                          --, '[%collapsible]' + Char ( 13 ) + Char ( 10 )
                          --, '======' + Char ( 13 ) + Char ( 10 )

                          --table start
                          , '[cols="1,4l"]' + Char ( 13 ) + Char ( 10 )
                          , '|===' + Char ( 13 ) + Char ( 10 )
                          , Char ( 13 ) + Char ( 10 )

                          --table content
                          , '|' + 'Component refId' + Char ( 13 ) + Char ( 10 ) + '|' + T1.Component_refId
                            + Char ( 13 ) + Char ( 10 ) + Char ( 13 ) + Char ( 10 )
                          , '|' + 'componentClassID' + Char ( 13 ) + Char ( 10 ) + '|' + T1.Component_componentClassID
                            + Char ( 13 ) + Char ( 10 ) + Char ( 13 ) + Char ( 10 )
                          , '|' + 'description' + Char ( 13 ) + Char ( 10 ) + '|' + T1.Component_description
                            + Char ( 13 ) + Char ( 10 ) + Char ( 13 ) + Char ( 10 )
                          , '|' + 'ContactInfo' + Char ( 13 ) + Char ( 10 ) + '|' + T1.Component_ContactInfo
                            + Char ( 13 ) + Char ( 10 ) + Char ( 13 ) + Char ( 10 )
                          , '|' + 'CommandTimeout' + Char ( 13 ) + Char ( 10 ) + '|'
                            + Cast(T1.Component_CommandTimeout As NVarchar(50)) + Char ( 13 ) + Char ( 10 )
                            + Char ( 13 ) + Char ( 10 )
                          , Iif(T1.Component_OpenRowset <> ''
                              , '|' + 'OpenRowset' + Char ( 13 ) + Char ( 10 ) + '|' + T1.Component_OpenRowset
                                + Char ( 13 ) + Char ( 10 ) + Char ( 13 ) + Char ( 10 )
                              , '')
                          , Iif(T1.Component_OpenRowsetVariable <> ''
                              , '|' + 'OpenRowsetVariable' + Char ( 13 ) + Char ( 10 ) + '|'
                                + T1.Component_OpenRowsetVariable + Char ( 13 ) + Char ( 10 ) + Char ( 13 )
                                + Char ( 10 )
                              , '')
                          , Iif(T1.Component_SqlCommand <> ''
                              , '|' + 'SqlCommand' + Char ( 13 ) + Char ( 10 ) + '|' + T1.Component_SqlCommand
                                + Char ( 13 ) + Char ( 10 ) + Char ( 13 ) + Char ( 10 )
                              , '')
                          , Iif(T1.Component_SqlCommandVariable <> ''
                              , '|' + 'SqlCommandVariable' + Char ( 13 ) + Char ( 10 ) + '|'
                                + T1.Component_SqlCommandVariable + Char ( 13 ) + Char ( 10 ) + Char ( 13 )
                                + Char ( 10 )
                              , '')
                          , Iif(T1.Component_DefaultCodePage <> 0
                              , '|' + 'DefaultCodePage' + Char ( 13 ) + Char ( 10 ) + '|'
                                + Cast(T1.Component_DefaultCodePage As Varchar(10)) + Char ( 13 ) + Char ( 10 )
                                + Char ( 13 ) + Char ( 10 )
                              , '')
                          , Iif(T1.Component_AlwaysUseDefaultCodePage <> ''
                              , '|' + 'AlwaysUseDefaultCodePage' + Char ( 13 ) + Char ( 10 ) + '|'
                                + T1.Component_AlwaysUseDefaultCodePage + Char ( 13 ) + Char ( 10 ) + Char ( 13 )
                                + Char ( 10 )
                              , '')
                          , Iif(T1.Component_ParameterMapping <> ''
                              , '|' + 'ParameterMapping' + Char ( 13 ) + Char ( 10 ) + '|'
                                + T1.Component_ParameterMapping + Char ( 13 ) + Char ( 10 ) + Char ( 13 ) + Char ( 10 )
                              , '')
                          , Iif(Not T1.Component_FastLoadKeepIdentity Is Null
                              , '|' + 'FastLoadKeepIdentity' + Char ( 13 ) + Char ( 10 ) + '|'
                                + Cast(T1.Component_FastLoadKeepIdentity As Varchar(10)) + Char ( 13 ) + Char ( 10 )
                                + Char ( 13 ) + Char ( 10 )
                              , '')
                          , Iif(Not T1.Component_FastLoadKeepNulls Is Null
                              , '|' + 'FastLoadKeepNulls' + Char ( 13 ) + Char ( 10 ) + '|'
                                + Cast(T1.Component_FastLoadKeepNulls As Varchar(10)) + Char ( 13 ) + Char ( 10 )
                                + Char ( 13 ) + Char ( 10 )
                              , '')
                          , Iif(T1.Component_FastLoadOptions <> ''
                              , '|' + 'FastLoadOptions' + Char ( 13 ) + Char ( 10 ) + '|'
                                + T1.Component_FastLoadOptions + Char ( 13 ) + Char ( 10 ) + Char ( 13 ) + Char ( 10 )
                              , '')
                          , Iif(Not T1.Component_FastLoadMaxInsertCommitSize Is Null
                              , '|' + 'FastLoadMaxInsertCommitSize' + Char ( 13 ) + Char ( 10 ) + '|'
                                + Cast(T1.Component_FastLoadMaxInsertCommitSize As Varchar(10)) + Char ( 13 )
                                + Char ( 10 ) + Char ( 13 ) + Char ( 10 )
                              , '')
                          , Iif(T1.Component_VariableName <> ''
                              , '|' + 'VariableName' + Char ( 13 ) + Char ( 10 ) + '|' + T1.Component_VariableName
                                + Char ( 13 ) + Char ( 10 ) + Char ( 13 ) + Char ( 10 )
                              , '')
                          , Iif(T1.Component_Connection_refId <> ''
                              , '|' + 'Connection_refId' + Char ( 13 ) + Char ( 10 ) + '|'
                                + T1.Component_Connection_refId + Char ( 13 ) + Char ( 10 ) + Char ( 13 ) + Char ( 10 )
                              , '')
                          , Iif(T1.Component_connectionManagerID <> ''
                              , '|' + 'connectionManagerID' + Char ( 13 ) + Char ( 10 ) + '|'
                                + T1.Component_connectionManagerID + Char ( 13 ) + Char ( 10 ) + Char ( 13 )
                                + Char ( 10 )
                              , '')
                          , Iif(T1.Component_connectionManagerRefId <> ''
                              , '|' + 'connectionManagerRefId +' + Char ( 13 ) + Char ( 10 ) + ' <<connection-'
                                + docs.fs_cleanStringForAnchorId ( T1.Component_ConnectionManagerName ) + '>>'
                                + Char ( 13 ) + Char ( 10 ) + '|' + T1.Component_connectionManagerRefId + Char ( 13 )
                                + Char ( 10 ) + Char ( 13 ) + Char ( 10 )
                              , '')
                          , Iif(T1.Component_Connection_name <> ''
                              , '|' + 'Connection_name' + Char ( 13 ) + Char ( 10 ) + '|'
                                + T1.Component_Connection_name + Char ( 13 ) + Char ( 10 ) + Char ( 13 ) + Char ( 10 )
                              , '')
                          , Iif(T1.Component_IsSortedProperty <> ''
                              , '|' + 'IsSortedProperty' + Char ( 13 ) + Char ( 10 ) + '|'
                                + T1.Component_IsSortedProperty + Char ( 13 ) + Char ( 10 ) + Char ( 13 ) + Char ( 10 )
                              , '')

                          --table end
                          , '|===' + Char ( 13 ) + Char ( 10 )
                          , Char ( 13 ) + Char ( 10 ) + T3.DftTaskComponentInputList + Char ( 13 ) + Char ( 10 )
                          , Char ( 13 ) + Char ( 10 ) + T4.DftTaskComponentOutputList + Char ( 13 ) + Char ( 10 )

                          ----end collapsible
                          --, '======' + Char ( 13 ) + Char ( 10 )
                        )
               , Char ( 13 ) + Char ( 10 )
             ) Within Group(Order By
                                T1.Component_refId)
From
    ssis.PackageTask_Dft_Component           As T1
    Left Join
        docs.ssis_PumlPartialDftComponent    As T2
            On
            T2.AntoraModule        = T1.AntoraModule
            And T2.PackageName     = T1.PackageName
            And T2.TaskPath        = T1.TaskPath
            And T2.Component_refId = T1.Component_refId

    Left Join
        docs.ssis_DftTaskComponentInputList  As T3
            On
            T3.AntoraModule        = T1.AntoraModule
            And T3.PackageName     = T1.PackageName
            And T3.TaskPath        = T1.TaskPath
            And T3.Component_refId = T1.Component_refId

    Left Join
        docs.ssis_DftTaskComponentOutputList As T4
            On
            T4.AntoraModule        = T1.AntoraModule
            And T4.PackageName     = T1.PackageName
            And T4.TaskPath        = T1.TaskPath
            And T4.Component_refId = T1.Component_refId
Group By
    T1.AntoraModule
  , T1.PackageName
  , T1.TaskPath

----
=======
// end::sql_modules_definition[]


