// tag::HeaderFullDisplayName[]
= docs.ssis_Adoc
// end::HeaderFullDisplayName[]

== existing_properties

// tag::existing_properties[]
:ExistsProperty--antorareferencedlist:
:ExistsProperty--antorareferencinglist:
:ExistsProperty--is_repo_managed:
:ExistsProperty--is_ssas:
:ExistsProperty--pk_index_guid:
:ExistsProperty--pk_indexpatterncolumndatatype:
:ExistsProperty--pk_indexpatterncolumnname:
:ExistsProperty--referencedobjectlist:
:ExistsProperty--sql_modules_definition:
:ExistsProperty--FK:
:ExistsProperty--AntoraIndexList:
:ExistsProperty--Columns:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
849A07F7-C23C-EC11-852D-A81E8446D5B0
// end::RepoObject_guid[]

== RepoObject_FullDisplayName2

// tag::RepoObject_FullDisplayName2[]
docs.ssis_Adoc
// end::RepoObject_FullDisplayName2[]

== SysObject_type

// tag::SysObject_type[]
V 
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
view
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
1602156803
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2021-11-07 10:35:20
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]
[discrete]
== _


[#column-antoramodule]
=== AntoraModule

[cols="d,8m,m,m,m,d"]
|===
|1
|*AntoraModule*
|varchar(50)
|NOT NULL
|
|
|===

.Referenced Columns
--
* xref:ssis.package.adoc#column-antoramodule[+ssis.Package.AntoraModule+]
--

.Referencing Columns
--
* xref:docs.ssis_adoc_t.adoc#column-antoramodule[+docs.ssis_Adoc_T.AntoraModule+]
--


[#column-packagebasename]
=== PackageBasename

[cols="d,8m,m,m,m,d"]
|===
|2
|*PackageBasename*
|varchar(8000)
|NULL
|
|
|===

.Description
--
(replace([PackageName],'.dtsx',''))
--
{empty} +

.Referenced Columns
--
* xref:ssis.package.adoc#column-packagebasename[+ssis.Package.PackageBasename+]
--

.Referencing Columns
--
* xref:docs.ssis_adoc_t.adoc#column-packagebasename[+docs.ssis_Adoc_T.PackageBasename+]
--


[#column-adoccontent]
=== AdocContent

[cols="d,8m,m,m,m,d"]
|===
|
|AdocContent
|nvarchar(max)
|NOT NULL
|
|
|===

.Referencing Columns
--
* xref:docs.ssis_adoc_t.adoc#column-adoccontent[+docs.ssis_Adoc_T.AdocContent+]
--


// end::AntoraColumnDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]
|1
|*<<column-antoramodule>>*
|varchar(50)
|NOT NULL
|
|

|2
|*<<column-packagebasename>>*
|varchar(8000)
|NULL
|
|


// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]


|
|<<column-adoccontent>>
|nvarchar(max)
|NOT NULL
|
|

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

[#index-pkunderlinessisunderlineadoc]
=== PK_ssis_Adoc

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-AntoraModule>>; varchar(50)
* <<column-PackageBasename>>; varchar(8000)
--
* PK, Unique, Real: 1, 1, 0


[#index-idxunderlinessisunderlineadocunderlineunderline2]
=== idx_ssis_Adoc++__++2

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-AntoraModule>>; varchar(50)
--
* PK, Unique, Real: 0, 0, 0

// end::AntoraIndexList[]

== AntoraMeasureDetails

// tag::AntoraMeasureDetails[]

// end::AntoraMeasureDetails[]

== AntoraParameterList

// tag::AntoraParameterList[]

// end::AntoraParameterList[]

== AntoraXrefCulturesList

// tag::AntoraXrefCulturesList[]
* xref:dhw:sqldb:docs.ssis_adoc.adoc[] - 
// end::AntoraXrefCulturesList[]

== cultures_count

// tag::cultures_count[]
1
// end::cultures_count[]

== Other tags

source: property.RepoObjectProperty_cross As rop_cross


=== additional_reference_csv

// tag::additional_reference_csv[]

// end::additional_reference_csv[]


=== AdocUspSteps

// tag::adocuspsteps[]

// end::adocuspsteps[]


=== AntoraReferencedList

// tag::antorareferencedlist[]
* xref:docs.ssis_connectionlist.adoc[]
* xref:docs.ssis_generallist.adoc[]
* xref:docs.ssis_parameterlist.adoc[]
* xref:docs.ssis_projectconnectionlist.adoc[]
* xref:docs.ssis_pumlpackage.adoc[]
* xref:docs.ssis_tasklist.adoc[]
* xref:docs.ssis_variablelist.adoc[]
* xref:ssis.package.adoc[]
// end::antorareferencedlist[]


=== AntoraReferencingList

// tag::antorareferencinglist[]
* xref:docs.ssis_adoc_t.adoc[]
* xref:docs.usp_persist_ssis_adoc_t.adoc[]
// end::antorareferencinglist[]


=== Description

// tag::description[]

// end::description[]


=== ExampleUsage

// tag::exampleusage[]

// end::exampleusage[]


=== exampleUsage_2

// tag::exampleusage_2[]

// end::exampleusage_2[]


=== exampleUsage_3

// tag::exampleusage_3[]

// end::exampleusage_3[]


=== exampleUsage_4

// tag::exampleusage_4[]

// end::exampleusage_4[]


=== exampleUsage_5

// tag::exampleusage_5[]

// end::exampleusage_5[]


=== exampleWrong_Usage

// tag::examplewrong_usage[]

// end::examplewrong_usage[]


=== has_execution_plan_issue

// tag::has_execution_plan_issue[]

// end::has_execution_plan_issue[]


=== has_get_referenced_issue

// tag::has_get_referenced_issue[]

// end::has_get_referenced_issue[]


=== has_history

// tag::has_history[]

// end::has_history[]


=== has_history_columns

// tag::has_history_columns[]

// end::has_history_columns[]


=== InheritanceType

// tag::inheritancetype[]

// end::inheritancetype[]


=== is_persistence

// tag::is_persistence[]

// end::is_persistence[]


=== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]

// end::is_persistence_check_duplicate_per_pk[]


=== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]

// end::is_persistence_check_for_empty_source[]


=== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]

// end::is_persistence_delete_changed[]


=== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]

// end::is_persistence_delete_missing[]


=== is_persistence_insert

// tag::is_persistence_insert[]

// end::is_persistence_insert[]


=== is_persistence_truncate

// tag::is_persistence_truncate[]

// end::is_persistence_truncate[]


=== is_persistence_update_changed

// tag::is_persistence_update_changed[]

// end::is_persistence_update_changed[]


=== is_repo_managed

// tag::is_repo_managed[]
0
// end::is_repo_managed[]


=== is_ssas

// tag::is_ssas[]
0
// end::is_ssas[]


=== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


=== MS_Description

// tag::ms_description[]

// end::ms_description[]


=== persistence_source_RepoObject_fullname

// tag::persistence_source_repoobject_fullname[]

// end::persistence_source_repoobject_fullname[]


=== persistence_source_RepoObject_fullname2

// tag::persistence_source_repoobject_fullname2[]

// end::persistence_source_repoobject_fullname2[]


=== persistence_source_RepoObject_guid

// tag::persistence_source_repoobject_guid[]

// end::persistence_source_repoobject_guid[]


=== persistence_source_RepoObject_xref

// tag::persistence_source_repoobject_xref[]

// end::persistence_source_repoobject_xref[]


=== pk_index_guid

// tag::pk_index_guid[]
883D459B-533F-EC11-852D-A81E8446D5B0
// end::pk_index_guid[]


=== pk_IndexPatternColumnDatatype

// tag::pk_indexpatterncolumndatatype[]
varchar(50),varchar(8000)
// end::pk_indexpatterncolumndatatype[]


=== pk_IndexPatternColumnName

// tag::pk_indexpatterncolumnname[]
AntoraModule,PackageBasename
// end::pk_indexpatterncolumnname[]


=== pk_IndexSemanticGroup

// tag::pk_indexsemanticgroup[]

// end::pk_indexsemanticgroup[]


=== ReferencedObjectList

// tag::referencedobjectlist[]
* [docs].[ssis_ConnectionList]
* [docs].[ssis_GeneralList]
* [docs].[ssis_ParameterList]
* [docs].[ssis_ProjectConnectionList]
* [docs].[ssis_PumlPackage]
* [docs].[ssis_TaskList]
* [docs].[ssis_VariableList]
* [ssis].[Package]
// end::referencedobjectlist[]


=== usp_persistence_RepoObject_guid

// tag::usp_persistence_repoobject_guid[]

// end::usp_persistence_repoobject_guid[]


=== UspExamples

// tag::uspexamples[]

// end::uspexamples[]


=== uspgenerator_usp_id

// tag::uspgenerator_usp_id[]

// end::uspgenerator_usp_id[]


=== UspParameters

// tag::uspparameters[]

// end::uspparameters[]

== Boolean Attributes

source: property.RepoObjectProperty WHERE property_int = 1

// tag::boolean_attributes[]

// end::boolean_attributes[]

== sql_modules_definition

// tag::sql_modules_definition[]
[%collapsible]
=======
[source,sql,numbered]
----
CREATE View docs.ssis_Adoc
As
Select
    p.AntoraModule
  , p.PackageBasename
  --,[PackageName]
  --,[PackageDTSID]
  --,[PackageCreationDate]
  --,[PackageCreatorComputerName]
  --,[PackageCreatorName]
  --,[PackageDescription]
  --,[PackageLastModifiedProductVersion]
  --,[PackageLocaleID]
  --,[PackageObjectName]
  --,[PackagePath]
  --,[PackageProtectionLevel]
  --,[PackageProtectionLevelName]
  --,[PackageVersionGUID]
  --,[ProjectPath]
  --,[RowID]
  , AdocContent =
  --
  Concat (
             ''
           , '// tag::HeaderFullDisplayName[]'
           , Char ( 13 ) + Char ( 10 )
           , '= ' + p.PackageName
           , Char ( 13 ) + Char ( 10 )
           , '// end::HeaderFullDisplayName[]'
           , Char ( 13 ) + Char ( 10 )

           --
           --
           , Char ( 13 ) + Char ( 10 )
           , '== GeneralList'
           , Char ( 13 ) + Char ( 10 )
           , Char ( 13 ) + Char ( 10 )
           , '// tag::GeneralList[]'
           , Char ( 13 ) + Char ( 10 )
           , gl.GeneralList
           , Char ( 13 ) + Char ( 10 )
           , '// end::GeneralList[]'
           , Char ( 13 ) + Char ( 10 )
           --
           --
           , Char ( 13 ) + Char ( 10 )
           , '== PumlPackageControlFlows'
           , Char ( 13 ) + Char ( 10 )
           , Char ( 13 ) + Char ( 10 )
           , '// tag::PumlPackageControlFlows[]'
           , Char ( 13 ) + Char ( 10 )
           , '[plantuml, ssis-{docname}, svg, subs=macros]'
           , Char ( 13 ) + Char ( 10 )
           , '....'
           , Char ( 13 ) + Char ( 10 )
           , puml.PumlPackageControlFlows
           , Char ( 13 ) + Char ( 10 )
           , '....'
           , Char ( 13 ) + Char ( 10 )
           , '// end::PumlPackageControlFlows[]'
           , Char ( 13 ) + Char ( 10 )
           --
           --
           , Char ( 13 ) + Char ( 10 )
           , '== ConnectionList'
           , Char ( 13 ) + Char ( 10 )
           , Char ( 13 ) + Char ( 10 )
           , '// tag::ConnectionList[]'
           , Char ( 13 ) + Char ( 10 )
           , cl.ConnectionList
           , Char ( 13 ) + Char ( 10 )
           , '// end::ConnectionList[]'
           , Char ( 13 ) + Char ( 10 )
           --
           --
           , Char ( 13 ) + Char ( 10 )
           , '== ProjectConnectionList'
           , Char ( 13 ) + Char ( 10 )
           , Char ( 13 ) + Char ( 10 )
           , '// tag::ProjectConnectionList[]'
           , Char ( 13 ) + Char ( 10 )
           , pcl.ProjectConnectionList
           , Char ( 13 ) + Char ( 10 )
           , '// end::ProjectConnectionList[]'
           , Char ( 13 ) + Char ( 10 )
           --
           --
           , Char ( 13 ) + Char ( 10 )
           , '== ParameterList'
           , Char ( 13 ) + Char ( 10 )
           , Char ( 13 ) + Char ( 10 )
           , '// tag::ParameterList[]'
           , Char ( 13 ) + Char ( 10 )
           , pl.ParameterList
           , Char ( 13 ) + Char ( 10 )
           , '// end::ParameterList[]'
           , Char ( 13 ) + Char ( 10 )
           --
           --
           , Char ( 13 ) + Char ( 10 )
           , '== VariableList'
           , Char ( 13 ) + Char ( 10 )
           , Char ( 13 ) + Char ( 10 )
           , '// tag::VariableList[]'
           , Char ( 13 ) + Char ( 10 )
           , vl.VariableList
           , Char ( 13 ) + Char ( 10 )
           , '// end::VariableList[]'
           , Char ( 13 ) + Char ( 10 )
           --
           --
           , Char ( 13 ) + Char ( 10 )
           , '== TaskList'
           , Char ( 13 ) + Char ( 10 )
           , Char ( 13 ) + Char ( 10 )
           , '// tag::TaskList[]'
           , Char ( 13 ) + Char ( 10 )
           , tl.TaskList
           , Char ( 13 ) + Char ( 10 )
           , '// end::TaskList[]'
           , Char ( 13 ) + Char ( 10 )

           --
           --
           --
           --
           , Char ( 13 ) + Char ( 10 )
           , '== PackageDTSID'
           , Char ( 13 ) + Char ( 10 )
           , Char ( 13 ) + Char ( 10 )
           , '// tag::PackageDTSID[]'
           , Char ( 13 ) + Char ( 10 )
           , p.PackageDTSID
           , Char ( 13 ) + Char ( 10 )
           , '// end::PackageDTSID[]'
           , Char ( 13 ) + Char ( 10 )
           --
           , Char ( 13 ) + Char ( 10 )
           , '== PackageCreationDate'
           , Char ( 13 ) + Char ( 10 )
           , Char ( 13 ) + Char ( 10 )
           , '// tag::PackageCreationDate[]'
           , Char ( 13 ) + Char ( 10 )
           , p.PackageCreationDate
           , Char ( 13 ) + Char ( 10 )
           , '// end::PackageCreationDate[]'
           , Char ( 13 ) + Char ( 10 )

           --
           , Char ( 13 ) + Char ( 10 )
           , '== PackageCreatorComputerName'
           , Char ( 13 ) + Char ( 10 )
           , Char ( 13 ) + Char ( 10 )
           , '// tag::PackageCreatorComputerName[]'
           , Char ( 13 ) + Char ( 10 )
           , p.PackageCreatorComputerName
           , Char ( 13 ) + Char ( 10 )
           , '// end::PackageCreatorComputerName[]'
           , Char ( 13 ) + Char ( 10 )

           --
           , Char ( 13 ) + Char ( 10 )
           , '== PackageCreatorName'
           , Char ( 13 ) + Char ( 10 )
           , Char ( 13 ) + Char ( 10 )
           , '// tag::PackageCreatorName[]'
           , Char ( 13 ) + Char ( 10 )
           , p.PackageCreatorName
           , Char ( 13 ) + Char ( 10 )
           , '// end::PackageCreatorName[]'
           , Char ( 13 ) + Char ( 10 )

           --
           , Char ( 13 ) + Char ( 10 )
           , '== PackageDescription'
           , Char ( 13 ) + Char ( 10 )
           , Char ( 13 ) + Char ( 10 )
           , '// tag::PackageDescription[]'
           , Char ( 13 ) + Char ( 10 )
           , p.PackageDescription
           , Char ( 13 ) + Char ( 10 )
           , '// end::PackageDescription[]'
           , Char ( 13 ) + Char ( 10 )

           --
           , Char ( 13 ) + Char ( 10 )
           , '== PackageLastModifiedProductVersion'
           , Char ( 13 ) + Char ( 10 )
           , Char ( 13 ) + Char ( 10 )
           , '// tag::PackageLastModifiedProductVersion[]'
           , Char ( 13 ) + Char ( 10 )
           , p.PackageLastModifiedProductVersion
           , Char ( 13 ) + Char ( 10 )
           , '// end::PackageLastModifiedProductVersion[]'
           , Char ( 13 ) + Char ( 10 )

           --
           , Char ( 13 ) + Char ( 10 )
           , '== PackageLocaleID'
           , Char ( 13 ) + Char ( 10 )
           , Char ( 13 ) + Char ( 10 )
           , '// tag::PackageLocaleID[]'
           , Char ( 13 ) + Char ( 10 )
           , p.PackageLocaleID
           , Char ( 13 ) + Char ( 10 )
           , '// end::PackageLocaleID[]'
           , Char ( 13 ) + Char ( 10 )

           --
           , Char ( 13 ) + Char ( 10 )
           , '== PackageObjectName'
           , Char ( 13 ) + Char ( 10 )
           , Char ( 13 ) + Char ( 10 )
           , '// tag::PackageObjectName[]'
           , Char ( 13 ) + Char ( 10 )
           , p.PackageObjectName
           , Char ( 13 ) + Char ( 10 )
           , '// end::PackageObjectName[]'
           , Char ( 13 ) + Char ( 10 )

           --
           , Char ( 13 ) + Char ( 10 )
           , '== PackagePath'
           , Char ( 13 ) + Char ( 10 )
           , Char ( 13 ) + Char ( 10 )
           , '// tag::PackagePath[]'
           , Char ( 13 ) + Char ( 10 )
           , p.PackagePath
           , Char ( 13 ) + Char ( 10 )
           , '// end::PackagePath[]'
           , Char ( 13 ) + Char ( 10 )

           --
           , Char ( 13 ) + Char ( 10 )
           , '== PackageProtectionLevel'
           , Char ( 13 ) + Char ( 10 )
           , Char ( 13 ) + Char ( 10 )
           , '// tag::PackageProtectionLevel[]'
           , Char ( 13 ) + Char ( 10 )
           , p.PackageProtectionLevel
           , Char ( 13 ) + Char ( 10 )
           , '// end::PackageProtectionLevel[]'
           , Char ( 13 ) + Char ( 10 )

           --
           , Char ( 13 ) + Char ( 10 )
           , '== PackageProtectionLevelName'
           , Char ( 13 ) + Char ( 10 )
           , Char ( 13 ) + Char ( 10 )
           , '// tag::PackageProtectionLevelName[]'
           , Char ( 13 ) + Char ( 10 )
           , p.PackageProtectionLevelName
           , Char ( 13 ) + Char ( 10 )
           , '// end::PackageProtectionLevelName[]'
           , Char ( 13 ) + Char ( 10 )

           --
           , Char ( 13 ) + Char ( 10 )
           , '== PackageVersionGUID'
           , Char ( 13 ) + Char ( 10 )
           , Char ( 13 ) + Char ( 10 )
           , '// tag::PackageVersionGUID[]'
           , Char ( 13 ) + Char ( 10 )
           , p.PackageVersionGUID
           , Char ( 13 ) + Char ( 10 )
           , '// end::PackageVersionGUID[]'
           , Char ( 13 ) + Char ( 10 )

           --
           , Char ( 13 ) + Char ( 10 )
           , '== ProjectPath'
           , Char ( 13 ) + Char ( 10 )
           , Char ( 13 ) + Char ( 10 )
           , '// tag::ProjectPath[]'
           , Char ( 13 ) + Char ( 10 )
           , p.ProjectPath
           , Char ( 13 ) + Char ( 10 )
           , '// end::ProjectPath[]'
           , Char ( 13 ) + Char ( 10 )
         )
From
    ssis.Package                        As p
    Left Join
        docs.ssis_GeneralList           As gl
            On
            gl.AntoraModule      = p.AntoraModule
            And gl.PackageName   = p.PackageName

    Left Join
        docs.ssis_ConnectionList        As cl
            On
            cl.AntoraModule      = p.AntoraModule
            And cl.PackageName   = p.PackageName

    Left Join
        docs.ssis_ProjectConnectionList As pcl
            On
            pcl.AntoraModule     = p.AntoraModule

    Left Join
        docs.ssis_ParameterList         As pl
            On
            pl.AntoraModule      = p.AntoraModule
            And pl.PackageName   = p.PackageName

    Left Join
        docs.ssis_VariableList          As vl
            On
            vl.AntoraModule      = p.AntoraModule
            And vl.PackageName   = p.PackageName

    Left Join
        docs.ssis_TaskList              As tl
            On
            tl.AntoraModule      = p.AntoraModule
            And tl.PackageName   = p.PackageName

    Left Join
        docs.ssis_PumlPackage           As puml
            On
            puml.AntoraModule    = p.AntoraModule
            And puml.PackageName = p.PackageName

----
=======
// end::sql_modules_definition[]


