= [docs].[ftv_RepoObject_Reference_PlantUml_EntityRefList]

== existing_properties

// tag::existing_properties[]
:ExistsProperty--antorareferencedlist:
:ExistsProperty--antorareferencinglist:
:ExistsProperty--exampleusage:
:ExistsProperty--is_repo_managed:
:ExistsProperty--is_ssas:
:ExistsProperty--ms_description:
:ExistsProperty--referencedobjectlist:
:ExistsProperty--sql_modules_definition:
:ExistsProperty--AntoraParameterList:
:ExistsProperty--Columns:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
2BE63ABF-9395-EB11-84F4-A81E8446D5B0
// end::RepoObject_guid[]

== SysObject_type

// tag::SysObject_type[]
IF
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
inline function
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
660913426
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2021-09-04 20:02:39
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]
[#column-PumlEntityList]
=== PumlEntityList

[cols="d,8m,m,m,m,d"]
|===
|
|PumlEntityList
|nvarchar(max)
|NULL
|
|
|===


[#column-PumlEntityOnlyPkList]
=== PumlEntityOnlyPkList

[cols="d,8m,m,m,m,d"]
|===
|
|PumlEntityOnlyPkList
|nvarchar(max)
|NULL
|
|
|===


[#column-Referenced_Depth]
=== Referenced_Depth

[cols="d,8m,m,m,m,d"]
|===
|
|Referenced_Depth
|int
|NULL
|
|
|===


[#column-Referencing_Depth]
=== Referencing_Depth

[cols="d,8m,m,m,m,d"]
|===
|
|Referencing_Depth
|int
|NULL
|
|
|===


[#column-ro_guid]
=== ro_guid

[cols="d,8m,m,m,m,d"]
|===
|
|ro_guid
|uniqueidentifier
|NULL
|
|
|===


// end::AntoraColumnDetails[]

== AntoraMeasureDetails

// tag::AntoraMeasureDetails[]

// end::AntoraMeasureDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]





// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]
|
|<<column-PumlEntityList>>
|nvarchar(max)
|NULL
|
|

|
|<<column-PumlEntityOnlyPkList>>
|nvarchar(max)
|NULL
|
|

|
|<<column-Referenced_Depth>>
|int
|NULL
|
|

|
|<<column-Referencing_Depth>>
|int
|NULL
|
|

|
|<<column-ro_guid>>
|uniqueidentifier
|NULL
|
|

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

// end::AntoraIndexList[]

== AntoraParameterList

// tag::AntoraParameterList[]
* @RepoObject_guid (uniqueidentifier)
* @Referenced_Depth (int)
* @Referencing_Depth (int)
// end::AntoraParameterList[]

== Other tags

source: property.RepoObjectProperty_cross As rop_cross


=== AdocUspSteps

// tag::adocuspsteps[]

// end::adocuspsteps[]


=== AntoraReferencedList

// tag::antorareferencedlist[]
* xref:docs.RepoObject_Plantuml_Entity_T.adoc[]
* xref:reference.RepoObject_ReferenceTree.adoc[]
* xref:repo.RepoObject.adoc[]
// end::antorareferencedlist[]


=== AntoraReferencingList

// tag::antorareferencinglist[]
* xref:docs.RepoObject_Plantuml.adoc[]
// end::antorareferencinglist[]


=== exampleUsage

// tag::exampleusage[]

SELECT
    ro.RepoObject_guid
  , ro.RepoObject_fullname2
  , ro_p.PumlEntityList
FROM
    repo.RepoObject                                                                                   ro
    CROSS APPLY [docs].[ftv_RepoObject_Reference_PlantUml_EntityRefList] ( ro.RepoObject_guid, 1, 1 ) ro_p
ORDER BY
    ro.RepoObject_fullname2;
// end::exampleusage[]


=== exampleUsage_2

// tag::exampleusage_2[]

// end::exampleusage_2[]


=== exampleUsage_3

// tag::exampleusage_3[]

// end::exampleusage_3[]


=== exampleUsage_4

// tag::exampleusage_4[]

// end::exampleusage_4[]


=== exampleUsage_5

// tag::exampleusage_5[]

// end::exampleusage_5[]


=== exampleWrong_Usage

// tag::examplewrong_usage[]

// end::examplewrong_usage[]


=== has_execution_plan_issue

// tag::has_execution_plan_issue[]

// end::has_execution_plan_issue[]


=== has_get_referenced_issue

// tag::has_get_referenced_issue[]

// end::has_get_referenced_issue[]


=== has_history

// tag::has_history[]

// end::has_history[]


=== has_history_columns

// tag::has_history_columns[]

// end::has_history_columns[]


=== is_persistence

// tag::is_persistence[]

// end::is_persistence[]


=== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]

// end::is_persistence_check_duplicate_per_pk[]


=== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]

// end::is_persistence_check_for_empty_source[]


=== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]

// end::is_persistence_delete_changed[]


=== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]

// end::is_persistence_delete_missing[]


=== is_persistence_insert

// tag::is_persistence_insert[]

// end::is_persistence_insert[]


=== is_persistence_truncate

// tag::is_persistence_truncate[]

// end::is_persistence_truncate[]


=== is_persistence_update_changed

// tag::is_persistence_update_changed[]

// end::is_persistence_update_changed[]


=== is_repo_managed

// tag::is_repo_managed[]
0
// end::is_repo_managed[]


=== is_ssas

// tag::is_ssas[]
0
// end::is_ssas[]


=== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


=== MS_Description

// tag::ms_description[]

PlantUML for all entities to be included into the reference diagram, defined by  @Referenced_Depth and @Referencing_Depth +

relations between these entities are generated in +
xref:sqldb:docs.RepoObject_Plantuml_ObjectRefList_1_1.adoc[], xref:sqldb:docs.RepoObject_Plantuml_ObjectRefList_0_30.adoc[], xref:sqldb:docs.RepoObject_Plantuml_ObjectRefList_30_0.adoc[] 
// end::ms_description[]


=== persistence_source_RepoObject_fullname

// tag::persistence_source_repoobject_fullname[]

// end::persistence_source_repoobject_fullname[]


=== persistence_source_RepoObject_fullname2

// tag::persistence_source_repoobject_fullname2[]

// end::persistence_source_repoobject_fullname2[]


=== persistence_source_RepoObject_guid

// tag::persistence_source_repoobject_guid[]

// end::persistence_source_repoobject_guid[]


=== persistence_source_RepoObject_xref

// tag::persistence_source_repoobject_xref[]

// end::persistence_source_repoobject_xref[]


=== pk_index_guid

// tag::pk_index_guid[]

// end::pk_index_guid[]


=== pk_IndexPatternColumnDatatype

// tag::pk_indexpatterncolumndatatype[]

// end::pk_indexpatterncolumndatatype[]


=== pk_IndexPatternColumnName

// tag::pk_indexpatterncolumnname[]

// end::pk_indexpatterncolumnname[]


=== pk_IndexSemanticGroup

// tag::pk_indexsemanticgroup[]

// end::pk_indexsemanticgroup[]


=== ReferencedObjectList

// tag::referencedobjectlist[]
* [docs].[RepoObject_Plantuml_Entity_T]
* [reference].[RepoObject_ReferenceTree]
* [repo].[RepoObject]
// end::referencedobjectlist[]


=== usp_persistence_RepoObject_guid

// tag::usp_persistence_repoobject_guid[]

// end::usp_persistence_repoobject_guid[]


=== UspExamples

// tag::uspexamples[]

// end::uspexamples[]


=== UspParameters

// tag::uspparameters[]

// end::uspparameters[]

== Boolean Attributes

source: property.RepoObjectProperty WHERE property_int = 1

// tag::boolean_attributes[]

// end::boolean_attributes[]

== sql_modules_definition

// tag::sql_modules_definition[]
[%collapsible]
=======
[source,sql]
----

/*
<<property_start>>MS_Description
PlantUML for all entities to be included into the reference diagram, defined by  @Referenced_Depth and @Referencing_Depth +

relations between these entities are generated in +
xref:sqldb:docs.RepoObject_Plantuml_ObjectRefList_1_1.adoc[], xref:sqldb:docs.RepoObject_Plantuml_ObjectRefList_0_30.adoc[], xref:sqldb:docs.RepoObject_Plantuml_ObjectRefList_30_0.adoc[] 
<<property_end>>

<<property_start>>exampleUsage
SELECT
    ro.RepoObject_guid
  , ro.RepoObject_fullname2
  , ro_p.PumlEntityList
FROM
    repo.RepoObject                                                                                   ro
    CROSS APPLY [docs].[ftv_RepoObject_Reference_PlantUml_EntityRefList] ( ro.RepoObject_guid, 1, 1 ) ro_p
ORDER BY
    ro.RepoObject_fullname2;
<<property_end>>


Msg 8624, Level 16, State 1, Line 19
Internal Query Processor Error: The query processor could not produce a query plan. For more information, contact Customer Support Services.

=> we need to persist [repo].[RepoObject_referenced_level_T] and [repo].[RepoObject_referencing_level_T]

remember to persist the source before:

EXEC [repo].[usp_PERSIST_RepoObject_referenced_level_T]
EXEC [repo].[usp_PERSIST_RepoObject_referencing_level_T]
EXEC [docs].[usp_PERSIST_RepoObject_Plantuml_Entity_T]

check:

SELECT * from [docs].[ftv_RepoObject_Reference_PlantUml_EntityRefList]('69CE8EB8-5F62-EB11-84DC-A81E8446D5B0', 1, 1)

*/
CREATE Function docs.ftv_RepoObject_Reference_PlantUml_EntityRefList
(
    @RepoObject_guid   UniqueIdentifier
  , @Referenced_Depth  Int = 1
  , @Referencing_Depth Int = 1
)
Returns Table
As
Return
(
    With
    ro
    As
        (
        Select
            ro_guid        = @RepoObject_guid
          , Node_guid      = @RepoObject_guid
          , Node_fullname2 = RepoObject_fullname2
        From
            repo.RepoObject
        Where
            RepoObject_guid = @RepoObject_guid
        Union
        --referenced objects
        Select
            RepoObject_guid
          , Referenced_guid
          , referenced_fullname2
        From
            reference.RepoObject_ReferenceTree
        Where
            RepoObject_guid       = @RepoObject_guid
            And Referenced_Depth  <= @Referenced_Depth
            And Referencing_Depth <= @Referencing_Depth
            And Referencing_Depth = 0
        Union
        --referencing objects
        Select
            RepoObject_guid
          , Referencing_guid
          , referencing_fullname2
        From
            reference.RepoObject_ReferenceTree
        Where
            RepoObject_guid       = @RepoObject_guid
            And Referencing_Depth <= @Referencing_Depth
            And Referenced_Depth  = 0

        ----referenced objects
        --Select
        --    [RepoObject_guid]
        --  , [Referenced_guid]
        --  , [Referenced_fullname2]
        --From
        --    [reference].[RepoObject_ReferenceTree_30_0_T]
        --Where
        --    [RepoObject_guid]      = @RepoObject_guid
        --    And [Referenced_Depth] <= @Referenced_Depth
        --Union
        ----referencing objects
        --Select
        --    [RepoObject_guid]
        --  , [Referencing_guid]
        --  , [Referencing_fullname2]
        --From
        --    [reference].[RepoObject_ReferenceTree_0_30_T]
        --Where
        --    [RepoObject_guid]       = @RepoObject_guid
        --    And [Referencing_Depth] <= @Referencing_Depth
        ----
        ----old logic, based on graph tables:
        --Union
        --Select
        --    StartingNode_guid
        --  , LastNode_guid
        --  , LastNode_fullname2
        --From
        --    [reference].RepoObject_referenced_level_T
        --Where
        --    StartingNode_guid    = @RepoObject_guid
        --    And referenced_level <= @Referenced_Depth
        --Union
        --Select
        --    StartingNode_guid
        --  , LastNode_guid
        --  , LastNode_fullname2
        --From
        --    [reference].RepoObject_referencing_level_T
        --Where
        --    StartingNode_guid     = @RepoObject_guid
        --    And referencing_level <= @Referencing_Depth
        )
    Select
        ro.ro_guid
      , Referenced_Depth     = @Referenced_Depth
      , Referencing_Depth    = @Referencing_Depth
      , PumlEntityList       = String_Agg ( rop.RepoObject_Puml, Char ( 13 ) + Char ( 10 )) Within Group(Order By
                                                                                                             ro.Node_fullname2)
      , PumlEntityOnlyPkList = String_Agg ( rop.RepoObject_PumlOnlyPK, Char ( 13 ) + Char ( 10 )) Within Group(Order By
                                                                                                                   ro.Node_fullname2)
    From
        ro
        Inner Join
            docs.RepoObject_Plantuml_Entity_T As rop
                On
                rop.RepoObject_guid = ro.Node_guid
    Group By
        ro.ro_guid
);
----
=======
// end::sql_modules_definition[]


