// tag::HeaderFullDisplayName[]
= docs.RepoObject_Adoc
// end::HeaderFullDisplayName[]

== existing_properties

// tag::existing_properties[]
:ExistsProperty--antorareferencedlist:
:ExistsProperty--antorareferencinglist:
:ExistsProperty--description:
:ExistsProperty--is_repo_managed:
:ExistsProperty--is_ssas:
:ExistsProperty--referencedobjectlist:
:ExistsProperty--sql_modules_definition:
:ExistsProperty--FK:
:ExistsProperty--AntoraIndexList:
:ExistsProperty--Columns:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
D5E0B563-4291-EB11-84F2-A81E8446D5B0
// end::RepoObject_guid[]

== RepoObject_FullDisplayName2

// tag::RepoObject_FullDisplayName2[]
docs.RepoObject_Adoc
// end::RepoObject_FullDisplayName2[]

== SysObject_type

// tag::SysObject_type[]
V 
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
view
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
1892917815
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2021-11-03 19:28:34
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]
[discrete]
== _


[#column-adoccontent]
=== AdocContent

[cols="d,8m,m,m,m,d"]
|===
|
|AdocContent
|nvarchar(max)
|NOT NULL
|
|
|===

.Referencing Columns
--
* xref:docs.repoobject_adoc_t.adoc#column-adoccontent[+docs.RepoObject_Adoc_T.AdocContent+]
--


[#column-culturesunderlinename]
=== cultures_name

[cols="d,8m,m,m,m,d"]
|===
|
|cultures_name
|nvarchar(10)
|NOT NULL
|
|
|===

.Referenced Columns
--
* xref:docs.repoobject_outputfilter_t.adoc#column-culturesunderlinename[+docs.RepoObject_OutputFilter_T.cultures_name+]
--

.Referencing Columns
--
* xref:docs.repoobject_adoc_t.adoc#column-culturesunderlinename[+docs.RepoObject_Adoc_T.cultures_name+]
--


[#column-isunderlinedocsoutput]
=== is_DocsOutput

[cols="d,8m,m,m,m,d"]
|===
|
|is_DocsOutput
|int
|NULL
|
|
|===

.Referenced Columns
--
* xref:docs.repoobject_outputfilter_t.adoc#column-isunderlinedocsoutput[+docs.RepoObject_OutputFilter_T.is_DocsOutput+]
* xref:repo.repoobject_gross.adoc#column-isunderlinedocsoutput[+repo.RepoObject_gross.is_DocsOutput+]
--

.Referencing Columns
--
* xref:docs.repoobject_adoc_t.adoc#column-isunderlinedocsoutput[+docs.RepoObject_Adoc_T.is_DocsOutput+]
--


[#column-propertycount]
=== PropertyCount

[cols="d,8m,m,m,m,d"]
|===
|
|PropertyCount
|int
|NULL
|
|
|===

.Referencing Columns
--
* xref:docs.repoobject_adoc_t.adoc#column-propertycount[+docs.RepoObject_Adoc_T.PropertyCount+]
--


[#column-repoobjectunderlinedisplayname]
=== RepoObject_DisplayName

[cols="d,8m,m,m,m,d"]
|===
|
|RepoObject_DisplayName
|nvarchar(128)
|NULL
|
|
|===

.Referencing Columns
--
* xref:docs.repoobject_adoc_t.adoc#column-repoobjectunderlinedisplayname[+docs.RepoObject_Adoc_T.RepoObject_DisplayName+]
--


[#column-repoobjectunderlinefulldisplayname2]
=== RepoObject_FullDisplayName2

[cols="d,8m,m,m,m,d"]
|===
|
|RepoObject_FullDisplayName2
|nvarchar(257)
|NULL
|
|
|===

.Referencing Columns
--
* xref:docs.repoobject_adoc_t.adoc#column-repoobjectunderlinefulldisplayname2[+docs.RepoObject_Adoc_T.RepoObject_FullDisplayName2+]
--


[#column-repoobjectunderlinefullname]
=== RepoObject_fullname

[cols="d,8m,m,m,m,d"]
|===
|
|RepoObject_fullname
|nvarchar(261)
|NULL
|
|
|===

.Referencing Columns
--
* xref:docs.repoobject_adoc_t.adoc#column-repoobjectunderlinefullname[+docs.RepoObject_Adoc_T.RepoObject_fullname+]
--


[#column-repoobjectunderlinefullname2]
=== RepoObject_fullname2

[cols="d,8m,m,m,m,d"]
|===
|
|RepoObject_fullname2
|nvarchar(257)
|NULL
|
|
|===

.Referencing Columns
--
* xref:docs.repoobject_adoc_t.adoc#column-repoobjectunderlinefullname2[+docs.RepoObject_Adoc_T.RepoObject_fullname2+]
--


[#column-repoobjectunderlineguid]
=== RepoObject_guid

[cols="d,8m,m,m,m,d"]
|===
|
|RepoObject_guid
|uniqueidentifier
|NOT NULL
|
|
|===

.Referenced Columns
--
* xref:docs.repoobject_outputfilter_t.adoc#column-repoobjectunderlineguid[+docs.RepoObject_OutputFilter_T.RepoObject_guid+]
--

.Referencing Columns
--
* xref:docs.repoobject_adoc_t.adoc#column-repoobjectunderlineguid[+docs.RepoObject_Adoc_T.RepoObject_guid+]
--


[#column-repoobjectunderlineschemaunderlinename]
=== RepoObject_schema_name

[cols="d,8m,m,m,m,d"]
|===
|
|RepoObject_schema_name
|nvarchar(128)
|NULL
|
|
|===

.Referencing Columns
--
* xref:docs.repoobject_adoc_t.adoc#column-repoobjectunderlineschemaunderlinename[+docs.RepoObject_Adoc_T.RepoObject_schema_name+]
--


[#column-repoobjectunderlinetranslation]
=== RepoObject_translation

[cols="d,8m,m,m,m,d"]
|===
|
|RepoObject_translation
|nvarchar(128)
|NULL
|
|
|===

.Referencing Columns
--
* xref:docs.repoobject_adoc_t.adoc#column-repoobjectunderlinetranslation[+docs.RepoObject_Adoc_T.RepoObject_translation+]
--


[#column-sysobjectunderlinefullname]
=== SysObject_fullname

[cols="d,8m,m,m,m,d"]
|===
|
|SysObject_fullname
|nvarchar(261)
|NULL
|
|
|===

.Referencing Columns
--
* xref:docs.repoobject_adoc_t.adoc#column-sysobjectunderlinefullname[+docs.RepoObject_Adoc_T.SysObject_fullname+]
--


[#column-sysobjectunderlinefullname2]
=== SysObject_fullname2

[cols="d,8m,m,m,m,d"]
|===
|
|SysObject_fullname2
|nvarchar(257)
|NULL
|
|
|===

.Referencing Columns
--
* xref:docs.repoobject_adoc_t.adoc#column-sysobjectunderlinefullname2[+docs.RepoObject_Adoc_T.SysObject_fullname2+]
--


[#column-sysobjectunderlineschemaunderlinename]
=== SysObject_schema_name

[cols="d,8m,m,m,m,d"]
|===
|
|SysObject_schema_name
|nvarchar(128)
|NULL
|
|
|===

.Referencing Columns
--
* xref:docs.repoobject_adoc_t.adoc#column-sysobjectunderlineschemaunderlinename[+docs.RepoObject_Adoc_T.SysObject_schema_name+]
--


[#column-sysobjectunderlinetype]
=== SysObject_type

[cols="d,8m,m,m,m,d"]
|===
|
|SysObject_type
|char(2)
|NULL
|
|
|===

.Referencing Columns
--
* xref:docs.repoobject_adoc_t.adoc#column-sysobjectunderlinetype[+docs.RepoObject_Adoc_T.SysObject_type+]
--


[#column-sysobjectunderlinetypeunderlinename]
=== SysObject_type_name

[cols="d,8m,m,m,m,d"]
|===
|
|SysObject_type_name
|nvarchar(128)
|NULL
|
|
|===

.Referencing Columns
--
* xref:docs.repoobject_adoc_t.adoc#column-sysobjectunderlinetypeunderlinename[+docs.RepoObject_Adoc_T.SysObject_type_name+]
--


// end::AntoraColumnDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]
















// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]
|
|<<column-adoccontent>>
|nvarchar(max)
|NOT NULL
|
|

|
|<<column-culturesunderlinename>>
|nvarchar(10)
|NOT NULL
|
|

|
|<<column-isunderlinedocsoutput>>
|int
|NULL
|
|

|
|<<column-propertycount>>
|int
|NULL
|
|

|
|<<column-repoobjectunderlinedisplayname>>
|nvarchar(128)
|NULL
|
|

|
|<<column-repoobjectunderlinefulldisplayname2>>
|nvarchar(257)
|NULL
|
|

|
|<<column-repoobjectunderlinefullname>>
|nvarchar(261)
|NULL
|
|

|
|<<column-repoobjectunderlinefullname2>>
|nvarchar(257)
|NULL
|
|

|
|<<column-repoobjectunderlineguid>>
|uniqueidentifier
|NOT NULL
|
|

|
|<<column-repoobjectunderlineschemaunderlinename>>
|nvarchar(128)
|NULL
|
|

|
|<<column-repoobjectunderlinetranslation>>
|nvarchar(128)
|NULL
|
|

|
|<<column-sysobjectunderlinefullname>>
|nvarchar(261)
|NULL
|
|

|
|<<column-sysobjectunderlinefullname2>>
|nvarchar(257)
|NULL
|
|

|
|<<column-sysobjectunderlineschemaunderlinename>>
|nvarchar(128)
|NULL
|
|

|
|<<column-sysobjectunderlinetype>>
|char(2)
|NULL
|
|

|
|<<column-sysobjectunderlinetypeunderlinename>>
|nvarchar(128)
|NULL
|
|

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

[#index-idxunderlinerepoobjectunderlineadocunderlineunderline1]
=== idx_RepoObject_Adoc++__++1

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-RepoObject_guid>>; uniqueidentifier
* <<column-cultures_name>>; nvarchar(10)
--
* PK, Unique, Real: 0, 0, 0


[#index-idxunderlinerepoobjectunderlineadocunderlineunderline2]
=== idx_RepoObject_Adoc++__++2

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-RepoObject_guid>>; uniqueidentifier
--
* PK, Unique, Real: 0, 0, 0

// end::AntoraIndexList[]

== AntoraMeasureDetails

// tag::AntoraMeasureDetails[]

// end::AntoraMeasureDetails[]

== AntoraParameterList

// tag::AntoraParameterList[]

// end::AntoraParameterList[]

== AntoraXrefCulturesList

// tag::AntoraXrefCulturesList[]
* xref:dhw:sqldb:docs.repoobject_adoc.adoc[] - 
// end::AntoraXrefCulturesList[]

== cultures_count

// tag::cultures_count[]
1
// end::cultures_count[]

== Other tags

source: property.RepoObjectProperty_cross As rop_cross


=== additional_reference_csv

// tag::additional_reference_csv[]

// end::additional_reference_csv[]


=== AdocUspSteps

// tag::adocuspsteps[]

// end::adocuspsteps[]


=== AntoraReferencedList

// tag::antorareferencedlist[]
* xref:docs.repoobject_antoraxrefcultureslist.adoc[]
* xref:docs.repoobject_columnlist_t.adoc[]
* xref:docs.repoobject_indexlist_t.adoc[]
* xref:docs.repoobject_measurelist.adoc[]
* xref:docs.repoobject_outputfilter_t.adoc[]
* xref:docs.repoobject_parameterlist.adoc[]
* xref:property.repoobjectproperty.adoc[]
* xref:property.repoobjectproperty_cross.adoc[]
* xref:repo.repoobject_gross.adoc[]
* xref:repo.repoobject_sat2_t.adoc[]
// end::antorareferencedlist[]


=== AntoraReferencingList

// tag::antorareferencinglist[]
* xref:docs.repoobject_adoc_t.adoc[]
* xref:docs.usp_persist_repoobject_adoc_t.adoc[]
// end::antorareferencinglist[]


=== Description

// tag::description[]

`AdocContent` is the content of a page to be used by Antora as partial.

The view xref:docs.repoobject_adoc.adoc[] will persisted into xref:docs.repoobject_adoc_t.adoc[] +
and later exported for Antora by xref:docs.usp_persist_repoobject_adoc_t.adoc[]

One document per RepoObject is generated, it contains all information (but not diagrams) which is used by Antora. 

All Parts of the documentations are tagged, Antora can reference the content using this tags.

* any per RepoObject existing properties in xref:property.repoobjectproperty.adoc[] are extracted as separate tags
* some specific additional tags are extracted from other sources (some lists, some content from xref:repo.repoobject_gross.adoc[])
* a special entry per exported tag is created: `':ExistsProperty--' + Lower ( rop.property_name ) + ':'` which can be used to check the existence of a tag entry

To use additional content in Antora documentation first try to include new properties into xref:property.repoobjectproperty.adoc[]
// end::description[]


=== ExampleUsage

// tag::exampleusage[]

// end::exampleusage[]


=== exampleUsage_2

// tag::exampleusage_2[]

// end::exampleusage_2[]


=== exampleUsage_3

// tag::exampleusage_3[]

// end::exampleusage_3[]


=== exampleUsage_4

// tag::exampleusage_4[]

// end::exampleusage_4[]


=== exampleUsage_5

// tag::exampleusage_5[]

// end::exampleusage_5[]


=== exampleWrong_Usage

// tag::examplewrong_usage[]

// end::examplewrong_usage[]


=== has_execution_plan_issue

// tag::has_execution_plan_issue[]

// end::has_execution_plan_issue[]


=== has_get_referenced_issue

// tag::has_get_referenced_issue[]

// end::has_get_referenced_issue[]


=== has_history

// tag::has_history[]

// end::has_history[]


=== has_history_columns

// tag::has_history_columns[]

// end::has_history_columns[]


=== InheritanceType

// tag::inheritancetype[]

// end::inheritancetype[]


=== is_persistence

// tag::is_persistence[]

// end::is_persistence[]


=== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]

// end::is_persistence_check_duplicate_per_pk[]


=== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]

// end::is_persistence_check_for_empty_source[]


=== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]

// end::is_persistence_delete_changed[]


=== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]

// end::is_persistence_delete_missing[]


=== is_persistence_insert

// tag::is_persistence_insert[]

// end::is_persistence_insert[]


=== is_persistence_truncate

// tag::is_persistence_truncate[]

// end::is_persistence_truncate[]


=== is_persistence_update_changed

// tag::is_persistence_update_changed[]

// end::is_persistence_update_changed[]


=== is_repo_managed

// tag::is_repo_managed[]
0
// end::is_repo_managed[]


=== is_ssas

// tag::is_ssas[]
0
// end::is_ssas[]


=== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


=== MS_Description

// tag::ms_description[]

// end::ms_description[]


=== persistence_source_RepoObject_fullname

// tag::persistence_source_repoobject_fullname[]

// end::persistence_source_repoobject_fullname[]


=== persistence_source_RepoObject_fullname2

// tag::persistence_source_repoobject_fullname2[]

// end::persistence_source_repoobject_fullname2[]


=== persistence_source_RepoObject_guid

// tag::persistence_source_repoobject_guid[]

// end::persistence_source_repoobject_guid[]


=== persistence_source_RepoObject_xref

// tag::persistence_source_repoobject_xref[]

// end::persistence_source_repoobject_xref[]


=== pk_index_guid

// tag::pk_index_guid[]

// end::pk_index_guid[]


=== pk_IndexPatternColumnDatatype

// tag::pk_indexpatterncolumndatatype[]

// end::pk_indexpatterncolumndatatype[]


=== pk_IndexPatternColumnName

// tag::pk_indexpatterncolumnname[]

// end::pk_indexpatterncolumnname[]


=== pk_IndexSemanticGroup

// tag::pk_indexsemanticgroup[]

// end::pk_indexsemanticgroup[]


=== ReferencedObjectList

// tag::referencedobjectlist[]
* [docs].[RepoObject_AntoraXrefCulturesList]
* [docs].[RepoObject_ColumnList_T]
* [docs].[RepoObject_IndexList_T]
* [docs].[RepoObject_MeasureList]
* [docs].[RepoObject_OutputFilter_T]
* [docs].[RepoObject_ParameterList]
* [property].[RepoObjectProperty]
* [property].[RepoObjectProperty_cross]
* [repo].[RepoObject_gross]
* [repo].[RepoObject_sat2_T]
// end::referencedobjectlist[]


=== usp_persistence_RepoObject_guid

// tag::usp_persistence_repoobject_guid[]

// end::usp_persistence_repoobject_guid[]


=== UspExamples

// tag::uspexamples[]

// end::uspexamples[]


=== uspgenerator_usp_id

// tag::uspgenerator_usp_id[]

// end::uspgenerator_usp_id[]


=== UspParameters

// tag::uspparameters[]

// end::uspparameters[]

== Boolean Attributes

source: property.RepoObjectProperty WHERE property_int = 1

// tag::boolean_attributes[]

// end::boolean_attributes[]

== sql_modules_definition

// tag::sql_modules_definition[]
[%collapsible]
=======
[source,sql,numbered]
----


/*
<<property_start>>Description
`AdocContent` is the content of a page to be used by Antora as partial.

The view xref:docs.repoobject_adoc.adoc[] will persisted into xref:docs.repoobject_adoc_t.adoc[] +
and later exported for Antora by xref:docs.usp_persist_repoobject_adoc_t.adoc[]

One document per RepoObject is generated, it contains all information (but not diagrams) which is used by Antora. 

All Parts of the documentations are tagged, Antora can reference the content using this tags.

* any per RepoObject existing properties in xref:property.repoobjectproperty.adoc[] are extracted as separate tags
* some specific additional tags are extracted from other sources (some lists, some content from xref:repo.repoobject_gross.adoc[])
* a special entry per exported tag is created: `':ExistsProperty--' + Lower ( rop.property_name ) + ':'` which can be used to check the existence of a tag entry

To use additional content in Antora documentation first try to include new properties into xref:property.repoobjectproperty.adoc[]
<<property_end>>
*/
CREATE View [docs].[RepoObject_Adoc]
As
Select
    rof.RepoObject_guid
  , rof.cultures_name
  , is_DocsOutput               = Max ( rof.is_DocsOutput )
  , RepoObject_fullname         = Max ( rof.RepoObject_fullname )
  , RepoObject_fullname2        = Max ( rof.RepoObject_fullname2 )
  , RepoObject_FullDisplayName2 = Max ( rof.RepoObject_FullDisplayName2 )
  , RepoObject_DisplayName      = Max ( rof.RepoObject_DisplayName )
  , RepoObject_translation      = Max ( rof.RepoObject_translation )
  , RepoObject_schema_name      = Max ( rof.RepoObject_schema_name )
  , SysObject_fullname          = Max ( ro.SysObject_fullname )
  , SysObject_fullname2         = Max ( ro.SysObject_fullname2 )
  , SysObject_schema_name       = Max ( ro.SysObject_schema_name )
  , SysObject_type              = Max ( rof.SysObject_type )
  , SysObject_type_name         = Max ( rof.SysObject_type_name )
  , AdocContent                 =
  --
  Concat (
             ''
           --, '= '
           ----, Max ( ro.SysObject_fullname )
           --, Max ( rof.RepoObject_fullname )
           --, Char ( 13 ) + Char ( 10 )
           --
           --, Char ( 13 ) + Char ( 10 )
           --, '== HeaderFullDisplayName'
           --, Char ( 13 ) + Char ( 10 )
           --, Char ( 13 ) + Char ( 10 )
           , '// tag::HeaderFullDisplayName[]'
           , Char ( 13 ) + Char ( 10 )
           , '= ' + Max ( rof.RepoObject_FullDisplayName2 )
           , Char ( 13 ) + Char ( 10 )
           , '// end::HeaderFullDisplayName[]'
           , Char ( 13 ) + Char ( 10 )

           --
           , Char ( 13 ) + Char ( 10 )
           , '== existing_properties'
           , Char ( 13 ) + Char ( 10 )
           , Char ( 13 ) + Char ( 10 )
           , '// tag::existing_properties[]'
           , Char ( 13 ) + Char ( 10 )
           , String_Agg (
                            Concat (
                                       Cast('' As NVarchar(Max))
                                     , Case
                                           When Not rop.property_value Is Null
                                               Then
                                               ':ExistsProperty--' + Lower ( rop.property_name ) + ':' + Char ( 13 )
                                               + Char ( 10 )
                                           Else
                                               ''
                                       End
                                   )
                          , ''
                        ) Within Group(Order By
                                           rop_cross.property_name)
           , Case
                 When Max ( ros2.sql_modules_antora ) <> ''
                     Then
                     ':ExistsProperty--sql_modules_definition:' + Char ( 13 ) + Char ( 10 )
             End
           , Case
                 When Max ( ro.SysObject_type ) In
                 ( 'U', 'V' )
                     Then
                     ':ExistsProperty--FK:' + Char ( 13 ) + Char ( 10 )
             End
           , Case
                 When Max ( ilist.AntoraIndexList ) <> ''
                     Then
                     ':ExistsProperty--AntoraIndexList:' + Char ( 13 ) + Char ( 10 )
             End
           , Case
                 When Max ( parlist.AntoraParameterList ) <> ''
                     Then
                     ':ExistsProperty--AntoraParameterList:' + Char ( 13 ) + Char ( 10 )
             End
           , Case
                 --When Max ( ro.SysObject_type ) In
                 --( 'U', 'V', 'IF' )
                 When Max ( clist.AntoraColumnDetails ) <> ''
                     Then
                     ':ExistsProperty--Columns:' + Char ( 13 ) + Char ( 10 )
             End
           , Case
                 When Max ( mlist.AntoraMeasureDetails ) <> ''
                     Then
                     ':ExistsProperty--Measures:' + Char ( 13 ) + Char ( 10 )
             End
           , '// end::existing_properties[]'
           , Char ( 13 ) + Char ( 10 )
           --
           , Char ( 13 ) + Char ( 10 )
           , '== RepoObject_guid'
           , Char ( 13 ) + Char ( 10 )
           , Char ( 13 ) + Char ( 10 )
           , '// tag::RepoObject_guid[]'
           , Char ( 13 ) + Char ( 10 )
           , rof.RepoObject_guid
           , Char ( 13 ) + Char ( 10 )
           , '// end::RepoObject_guid[]'
           , Char ( 13 ) + Char ( 10 )
           --
           , Char ( 13 ) + Char ( 10 )
           , '== RepoObject_FullDisplayName2'
           , Char ( 13 ) + Char ( 10 )
           , Char ( 13 ) + Char ( 10 )
           , '// tag::RepoObject_FullDisplayName2[]'
           , Char ( 13 ) + Char ( 10 )
           , Max ( rof.RepoObject_FullDisplayName2 )
           , Char ( 13 ) + Char ( 10 )
           , '// end::RepoObject_FullDisplayName2[]'
           , Char ( 13 ) + Char ( 10 )
           --
           , Char ( 13 ) + Char ( 10 )
           , '== SysObject_type'
           , Char ( 13 ) + Char ( 10 )
           , Char ( 13 ) + Char ( 10 )
           , '// tag::SysObject_type[]'
           , Char ( 13 ) + Char ( 10 )
           , Max ( rof.SysObject_type )
           , Char ( 13 ) + Char ( 10 )
           , '// end::SysObject_type[]'
           , Char ( 13 ) + Char ( 10 )
           --
           , Char ( 13 ) + Char ( 10 )
           , '== SysObject_type_name'
           , Char ( 13 ) + Char ( 10 )
           , Char ( 13 ) + Char ( 10 )
           , '// tag::SysObject_type_name[]'
           , Char ( 13 ) + Char ( 10 )
           , Max ( rof.SysObject_type_name )
           , Char ( 13 ) + Char ( 10 )
           , '// end::SysObject_type_name[]'
           , Char ( 13 ) + Char ( 10 )
           --
           , Char ( 13 ) + Char ( 10 )
           , '== SysObject_id'
           , Char ( 13 ) + Char ( 10 )
           , Char ( 13 ) + Char ( 10 )
           , '// tag::SysObject_id[]'
           , Char ( 13 ) + Char ( 10 )
           , Max ( ro.SysObject_id )
           , Char ( 13 ) + Char ( 10 )
           , '// end::SysObject_id[]'
           , Char ( 13 ) + Char ( 10 )
           --
           , Char ( 13 ) + Char ( 10 )
           , '== SysObject_modify_date'
           , Char ( 13 ) + Char ( 10 )
           , Char ( 13 ) + Char ( 10 )
           , '// tag::SysObject_modify_date[]'
           , Char ( 13 ) + Char ( 10 )
           , Convert ( NVarchar(20), Max ( ro.SysObject_modify_date ), 120 )
           , Char ( 13 ) + Char ( 10 )
           , '// end::SysObject_modify_date[]'
           , Char ( 13 ) + Char ( 10 )

           --
           , Char ( 13 ) + Char ( 10 )
           , '== AntoraColumnDetails'
           , Char ( 13 ) + Char ( 10 )
           , Char ( 13 ) + Char ( 10 )
           , '// tag::AntoraColumnDetails[]'
           , Char ( 13 ) + Char ( 10 )
           , Max ( clist.AntoraColumnDetails )
           , Char ( 13 ) + Char ( 10 )
           , '// end::AntoraColumnDetails[]'
           , Char ( 13 ) + Char ( 10 )
           --
           , Char ( 13 ) + Char ( 10 )
           , '== AntoraPkColumnTableRows'
           , Char ( 13 ) + Char ( 10 )
           , Char ( 13 ) + Char ( 10 )
           , '// tag::AntoraPkColumnTableRows[]'
           , Char ( 13 ) + Char ( 10 )
           , Max ( clist.AntoraPkColumnTableRows )
           , Char ( 13 ) + Char ( 10 )
           , '// end::AntoraPkColumnTableRows[]'
           , Char ( 13 ) + Char ( 10 )
           --
           , Char ( 13 ) + Char ( 10 )
           , '== AntoraNonPkColumnTableRows'
           , Char ( 13 ) + Char ( 10 )
           , Char ( 13 ) + Char ( 10 )
           , '// tag::AntoraNonPkColumnTableRows[]'
           , Char ( 13 ) + Char ( 10 )
           , Max ( clist.AntoraNonPkColumnTableRows )
           , Char ( 13 ) + Char ( 10 )
           , '// end::AntoraNonPkColumnTableRows[]'
           , Char ( 13 ) + Char ( 10 )

           --
           , Char ( 13 ) + Char ( 10 )
           , '== AntoraIndexList'
           , Char ( 13 ) + Char ( 10 )
           , Char ( 13 ) + Char ( 10 )
           , '// tag::AntoraIndexList[]'
           , Char ( 13 ) + Char ( 10 )
           , Max ( ilist.AntoraIndexList )
           , Char ( 13 ) + Char ( 10 )
           , '// end::AntoraIndexList[]'
           , Char ( 13 ) + Char ( 10 )

           --
           , Char ( 13 ) + Char ( 10 )
           , '== AntoraMeasureDetails'
           , Char ( 13 ) + Char ( 10 )
           , Char ( 13 ) + Char ( 10 )
           , '// tag::AntoraMeasureDetails[]'
           , Char ( 13 ) + Char ( 10 )
           , Max ( mlist.AntoraMeasureDetails )
           , Char ( 13 ) + Char ( 10 )
           , '// end::AntoraMeasureDetails[]'
           , Char ( 13 ) + Char ( 10 )

           --
           , Char ( 13 ) + Char ( 10 )
           , '== AntoraParameterList'
           , Char ( 13 ) + Char ( 10 )
           , Char ( 13 ) + Char ( 10 )
           , '// tag::AntoraParameterList[]'
           , Char ( 13 ) + Char ( 10 )
           , Max ( parlist.AntoraParameterList )
           , Char ( 13 ) + Char ( 10 )
           , '// end::AntoraParameterList[]'
           , Char ( 13 ) + Char ( 10 )

           --
           , Char ( 13 ) + Char ( 10 )
           , '== AntoraXrefCulturesList'
           , Char ( 13 ) + Char ( 10 )
           , Char ( 13 ) + Char ( 10 )
           , '// tag::AntoraXrefCulturesList[]'
           , Char ( 13 ) + Char ( 10 )
           , Max ( axlist.AntoraXrefCulturesList )
           , Char ( 13 ) + Char ( 10 )
           , '// end::AntoraXrefCulturesList[]'
           , Char ( 13 ) + Char ( 10 )
           --
           , Char ( 13 ) + Char ( 10 )
           , '== cultures_count'
           , Char ( 13 ) + Char ( 10 )
           , Char ( 13 ) + Char ( 10 )
           , '// tag::cultures_count[]'
           , Char ( 13 ) + Char ( 10 )
           , Max ( axlist.cultures_count )
           , Char ( 13 ) + Char ( 10 )
           , '// end::cultures_count[]'
           , Char ( 13 ) + Char ( 10 )

           --
           , Char ( 13 ) + Char ( 10 )
           , '== Other tags'
           , Char ( 13 ) + Char ( 10 )
           , Char ( 13 ) + Char ( 10 )
           , 'source: property.RepoObjectProperty_cross As rop_cross'
           , Char ( 13 ) + Char ( 10 )
           , Char ( 13 ) + Char ( 10 )
           , String_Agg (
                            Concat (
                                       Cast('' As NVarchar(Max))
                                     , Char ( 13 ) + Char ( 10 )
                                     , '=== '
                                     , rop_cross.property_name Collate Database_Default
                                     , Char ( 13 ) + Char ( 10 )
                                     , Char ( 13 ) + Char ( 10 )
                                     , '// tag::'
                                     , Lower ( rop_cross.property_name ) Collate Database_Default
                                     , '[]'
                                     , Char ( 13 ) + Char ( 10 )
                                     , rop.property_value Collate Database_Default
                                     , Char ( 13 ) + Char ( 10 )
                                     , '// end::'
                                     , Lower ( rop_cross.property_name ) Collate Database_Default
                                     , '[]'
                                     , Char ( 13 ) + Char ( 10 )
                                   )
                          , Char ( 13 ) + Char ( 10 )
                        ) Within Group(Order By
                                           rop_cross.property_name)
           , Char ( 13 ) + Char ( 10 )
           , '== Boolean Attributes'
           , Char ( 13 ) + Char ( 10 )
           , Char ( 13 ) + Char ( 10 )
           , 'source: property.RepoObjectProperty WHERE property_int = 1'
           , Char ( 13 ) + Char ( 10 )
           , Char ( 13 ) + Char ( 10 )
           , '// tag::boolean_attributes[]'
           , Char ( 13 ) + Char ( 10 )
           , String_Agg (
                            Concat (
                                       Cast('' As NVarchar(Max))
                                     , Case
                                           When rop.property_int = 1
                                               Then
                                               ':' + Lower ( rop.property_name ) + ':' + Char ( 13 ) + Char ( 10 )
                                           Else
                                               ''
                                       End
                                   )
                          , ''
                        ) Within Group(Order By
                                           rop_cross.property_name)
           , Char ( 13 ) + Char ( 10 )
           , '// end::boolean_attributes[]'
           , Char ( 13 ) + Char ( 10 )
           --
           , Char ( 13 ) + Char ( 10 )
           , '== sql_modules_definition'
           , Char ( 13 ) + Char ( 10 )
           , Char ( 13 ) + Char ( 10 )
           , '// tag::sql_modules_definition[]'
           , Char ( 13 ) + Char ( 10 )
           , '[%collapsible]'
           , Char ( 13 ) + Char ( 10 )
           , '======='
           , Char ( 13 ) + Char ( 10 )
           , '[source,sql,numbered]'
           , Char ( 13 ) + Char ( 10 )
           , '----'
           , Char ( 13 ) + Char ( 10 )
           , Max ( ros2.sql_modules_antora )
           , Char ( 13 ) + Char ( 10 )
           , '----'
           , Char ( 13 ) + Char ( 10 )
           , '======='
           , Char ( 13 ) + Char ( 10 )
           , '// end::sql_modules_definition[]'
           , Char ( 13 ) + Char ( 10 )
           --
           , Char ( 13 ) + Char ( 10 )
         )
  , PropertyCount               = Count ( Distinct rop.property_name )
From
    docs.RepoObject_OutputFilter_T             As rof
    Left Join
        repo.RepoObject_gross                  As ro
            On
            ro.RepoObject_guid        = rof.RepoObject_guid

    Left Join
        repo.RepoObject_sat2_T                 As ros2
            On
            ros2.RepoObject_guid      = rof.RepoObject_guid

    Left Join
        property.RepoObjectProperty_cross      As rop_cross
            On
            rop_cross.RepoObject_guid = rof.RepoObject_guid

    Left Join
        property.RepoObjectProperty            As rop
            On
            rop.RepoObject_guid       = rop_cross.RepoObject_guid
            And rop.property_name     = rop_cross.property_name
    --AND NOT rop.[property_nvarchar] IS NULL

    Left Join
        docs.RepoObject_ColumnList_T           As clist
            On
            clist.RepoObject_guid     = ro.RepoObject_guid
            And clist.cultures_name   = rof.cultures_name

    Left Join
        docs.RepoObject_IndexList_T            As ilist
            On
            ilist.RepoObject_guid     = ro.RepoObject_guid
            And ilist.cultures_name   = rof.cultures_name

    Left Join
        docs.RepoObject_MeasureList            As mlist
            On
            mlist.RepoObject_guid     = ro.RepoObject_guid
            And mlist.cultures_name   = rof.cultures_name

    Left Join
        docs.RepoObject_ParameterList          As parlist
            On
            parlist.RepoObject_guid   = ro.RepoObject_guid

    Left Join
        docs.RepoObject_AntoraXrefCulturesList As axlist
            On
            axlist.RepoObject_guid    = ro.RepoObject_guid
Group By
    rof.RepoObject_guid
  , rof.cultures_name
Having
    Max ( Cast(rof.is_external As Int)) = 0

----
=======
// end::sql_modules_definition[]


