// tag::HeaderFullDisplayName[]
= docs.usp_AntoraExport
// end::HeaderFullDisplayName[]

== existing_properties

// tag::existing_properties[]
:ExistsProperty--adocuspsteps:
:ExistsProperty--antorareferencedlist:
:ExistsProperty--description:
:ExistsProperty--exampleusage:
:ExistsProperty--is_repo_managed:
:ExistsProperty--is_ssas:
:ExistsProperty--ms_description:
:ExistsProperty--referencedobjectlist:
:ExistsProperty--uspgenerator_usp_id:
:ExistsProperty--sql_modules_definition:
:ExistsProperty--AntoraParameterList:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
C51B7592-0397-EB11-84F4-A81E8446D5B0
// end::RepoObject_guid[]

== RepoObject_FullDisplayName2

// tag::RepoObject_FullDisplayName2[]
docs.usp_AntoraExport
// end::RepoObject_FullDisplayName2[]

== SysObject_type

// tag::SysObject_type[]
P 
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
stored procedure
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
749245724
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2021-11-07 17:28:32
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]

// end::AntoraColumnDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]

// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

// end::AntoraIndexList[]

== AntoraMeasureDetails

// tag::AntoraMeasureDetails[]

// end::AntoraMeasureDetails[]

== AntoraParameterList

// tag::AntoraParameterList[]
* @execution_instance_guid (uniqueidentifier)
* @ssis_execution_id (bigint)
* @sub_execution_id (int)
* @parent_execution_log_id (bigint)
// end::AntoraParameterList[]

== AntoraXrefCulturesList

// tag::AntoraXrefCulturesList[]
* xref:dhw:sqldb:docs.usp_antoraexport.adoc[] - 
// end::AntoraXrefCulturesList[]

== cultures_count

// tag::cultures_count[]
1
// end::cultures_count[]

== Other tags

source: property.RepoObjectProperty_cross As rop_cross


=== additional_reference_csv

// tag::additional_reference_csv[]

// end::additional_reference_csv[]


=== AdocUspSteps

// tag::adocuspsteps[]
.Steps in [docs].[usp_AntoraExport]
[cols="d,15a,d"]
|===
|Number|Name (Action, Source, Target)|Parent

|210
|
*declare variables*



.Statement
[%collapsible]
=====
[source,sql,numbered]
----
DECLARE @command NVARCHAR(4000)
DECLARE @cultures_name NVARCHAR(10)
Declare @AntoraModule Varchar(50)


----
=====

|


|300
|
*check Parameter AntoraDeleteFilesInModuleFolders*

* `IF [config].[fs_get_parameter_value]('AntoraDeleteFilesInModuleFolders','') = 1`
* [config].[Parameter]


.Statement
[%collapsible]
=====
[source,sql,numbered]
----
[config].[fs_get_parameter_value]('AntoraDeleteFilesInModuleFolders','') = 1
----
=====

|


|310
|
*Delete Files but not folder in AntoraModule pages and partials - by cultures_name*

* I


.Statement
[%collapsible]
=====
[source,sql,numbered]
----
Declare module_cursor Cursor Local Fast_Forward For
Select
    cultures_name
From
    docs.culture
Order By
    cultures_name

Open module_cursor

Fetch Next From module_cursor
Into
    @cultures_name

While @@Fetch_Status = 0
Begin

    /*
FORFILES /p "D:\Repos\gitlab\DataHandwerk\dhw-antora-sqldb\docs\modules\sqldb\partials" /s /m *.* /c "cmd /c if @isdir==FALSE del @path"
*/
    Set @command
        = N'FORFILES /p "'
          --
          --
          + docs.fs_AntoraModuleFolder ( @cultures_name )
          + '\partials'
          --
          + N'" /s /m *.* /c "cmd /c if @isdir==FALSE del @path"'

    Print @command

    --Execute the BCP command
    Exec sys.xp_cmdshell @command, no_output

    Set @command
        = N'FORFILES /p "'
          --
          --
          + docs.fs_AntoraModuleFolder ( @cultures_name )
          + '\pages'
          --
          + N'" /s /m *.* /c "cmd /c if @isdir==FALSE del @path"'

    Print @command

    --Execute the BCP command
    Exec sys.xp_cmdshell @command, no_output

    Fetch Next From module_cursor
    Into
        @cultures_name
End

Close module_cursor
Deallocate module_cursor
----
=====

|300


|320
|
*Delete Files but not folder in AntoraModule pages and partials - by SSIS AntoraModule*

* I


.Statement
[%collapsible]
=====
[source,sql,numbered]
----
Declare module_cursor Cursor Local Fast_Forward For
Select
    AntoraModule
From
    ssis.Project
Order By
    AntoraModule

Open module_cursor

Fetch Next From module_cursor
Into
    @AntoraModule

While @@Fetch_Status = 0
Begin

    /*
FORFILES /p "D:\Repos\gitlab\DataHandwerk\dhw-antora-sqldb\docs\modules\sqldb\partials" /s /m *.* /c "cmd /c if @isdir==FALSE del @path"
*/
    Set @command = N'FORFILES /p "'
                   --
                   --
                   + config.fs_get_parameter_value ( 'AntoraComponentFolder', '' ) + '\modules\' + @AntoraModule
                   --
                   + '\partials'
                   --
                   + N'" /s /m *.* /c "cmd /c if @isdir==FALSE del @path"'

    Print @command

    --Execute the BCP command
    Exec sys.xp_cmdshell @command, no_output

    Set @command = N'FORFILES /p "'
                   --
                   --
                   + config.fs_get_parameter_value ( 'AntoraComponentFolder', '' ) + '\modules\' + @AntoraModule
                   --
                   + '\pages'
                   --
                   + N'" /s /m *.* /c "cmd /c if @isdir==FALSE del @path"'

    Print @command

    --Execute the BCP command
    Exec sys.xp_cmdshell @command, no_output

    Fetch Next From module_cursor
    Into
        @AntoraModule
End

Close module_cursor
Deallocate module_cursor
----
=====

|300


|350
|
*[docs].[usp_AntoraExport_DocSnippet]*

* `EXEC [docs].[usp_AntoraExport_DocSnippet]`


.Statement
[%collapsible]
=====
[source,sql,numbered]
----
[docs].[usp_AntoraExport_DocSnippet]
----
=====

|


|400
|
*[docs].[usp_PERSIST_RepoObject_OutputFilter_T]*

* `EXEC [docs].[usp_PERSIST_RepoObject_OutputFilter_T]`


.Statement
[%collapsible]
=====
[source,sql,numbered]
----
[docs].[usp_PERSIST_RepoObject_OutputFilter_T]
----
=====

|


|440
|
*[docs].[usp_AntoraExport_ObjectNavigation]*

* `EXEC [docs].[usp_AntoraExport_ObjectNavigation]`


.Statement
[%collapsible]
=====
[source,sql,numbered]
----
[docs].[usp_AntoraExport_ObjectNavigation]
----
=====

|


|500
|
*[docs].[usp_AntoraExport_ObjectPage]*

* `EXEC [docs].[usp_AntoraExport_ObjectPage]`


.Statement
[%collapsible]
=====
[source,sql,numbered]
----
[docs].[usp_AntoraExport_ObjectPage]
----
=====

|


|600
|
*[docs].[usp_AntoraExport_ObjectPageTemplate]*

* `EXEC [docs].[usp_AntoraExport_ObjectPageTemplate]`


.Statement
[%collapsible]
=====
[source,sql,numbered]
----
[docs].[usp_AntoraExport_ObjectPageTemplate]
----
=====

|


|750
|
*[docs].[usp_AntoraExport_ObjectPartialProperties]*

* `EXEC [docs].[usp_AntoraExport_ObjectPartialProperties]`


.Statement
[%collapsible]
=====
[source,sql,numbered]
----
[docs].[usp_AntoraExport_ObjectPartialProperties]
----
=====

|


|800
|
*[docs].[usp_AntoraExport_ObjectPuml]*

* `EXEC [docs].[usp_AntoraExport_ObjectPuml]`


.Statement
[%collapsible]
=====
[source,sql,numbered]
----
[docs].[usp_AntoraExport_ObjectPuml]
----
=====

|


|910
|
*[docs].[usp_AntoraExport_Page_IndexSemanticGroup]*

* `EXEC [docs].[usp_AntoraExport_Page_IndexSemanticGroup]`


.Statement
[%collapsible]
=====
[source,sql,numbered]
----
[docs].[usp_AntoraExport_Page_IndexSemanticGroup]
----
=====

|


|920
|
*[docs].[usp_AntoraExport_ObjectRefCyclic]*

* `EXEC [docs].[usp_AntoraExport_ObjectRefCyclic]`


.Statement
[%collapsible]
=====
[source,sql,numbered]
----
[docs].[usp_AntoraExport_ObjectRefCyclic]
----
=====

|


|1440
|
*[docs].[usp_AntoraExport_SsisNavigation]*

* `EXEC [docs].[usp_AntoraExport_SsisNavigation]`


.Statement
[%collapsible]
=====
[source,sql,numbered]
----
[docs].[usp_AntoraExport_SsisNavigation]
----
=====

|


|1500
|
*[docs].[usp_AntoraExport_SsisPage]*

* `EXEC [docs].[usp_AntoraExport_SsisPage]`


.Statement
[%collapsible]
=====
[source,sql,numbered]
----
[docs].[usp_AntoraExport_SsisPage]
----
=====

|


|1600
|
*[docs].[usp_AntoraExport_SsisPageTemplate]*

* `EXEC [docs].[usp_AntoraExport_SsisPageTemplate]`


.Statement
[%collapsible]
=====
[source,sql,numbered]
----
[docs].[usp_AntoraExport_SsisPageTemplate]
----
=====

|


|1750
|
*[docs].[usp_AntoraExport_SsisPartialProperties]*

* `EXEC [docs].[usp_AntoraExport_SsisPartialProperties]`


.Statement
[%collapsible]
=====
[source,sql,numbered]
----
[docs].[usp_AntoraExport_SsisPartialProperties]
----
=====

|


|1800
|
*[docs].[usp_AntoraExport_SsisPuml]*

* `EXEC [docs].[usp_AntoraExport_SsisPuml]`


.Statement
[%collapsible]
=====
[source,sql,numbered]
----
[docs].[usp_AntoraExport_SsisPuml]
----
=====

|

|===

// end::adocuspsteps[]


=== AntoraReferencedList

// tag::antorareferencedlist[]
* xref:config.fs_get_parameter_value.adoc[]
* xref:docs.culture.adoc[]
* xref:docs.fs_antoramodulefolder.adoc[]
* xref:docs.usp_antoraexport_docsnippet.adoc[]
* xref:docs.usp_antoraexport_objectnavigation.adoc[]
* xref:docs.usp_antoraexport_objectpage.adoc[]
* xref:docs.usp_antoraexport_objectpagetemplate.adoc[]
* xref:docs.usp_antoraexport_objectpartialproperties.adoc[]
* xref:docs.usp_antoraexport_objectpuml.adoc[]
* xref:docs.usp_antoraexport_objectrefcyclic.adoc[]
* xref:docs.usp_antoraexport_page_indexsemanticgroup.adoc[]
* xref:docs.usp_antoraexport_ssisnavigation.adoc[]
* xref:docs.usp_antoraexport_ssispage.adoc[]
* xref:docs.usp_antoraexport_ssispagetemplate.adoc[]
* xref:docs.usp_antoraexport_ssispartialproperties.adoc[]
* xref:docs.usp_antoraexport_ssispuml.adoc[]
* xref:docs.usp_persist_repoobject_outputfilter_t.adoc[]
* xref:logs.usp_executionlog_insert.adoc[]
* xref:ssis.project.adoc[]
// end::antorareferencedlist[]


=== AntoraReferencingList

// tag::antorareferencinglist[]

// end::antorareferencinglist[]


=== Description

// tag::description[]
include::sqldb:partial$description/docs.usp_antoraexport.adoc[]

// end::description[]


=== ExampleUsage

// tag::exampleusage[]
--ensure consistent and existing repository guid before sql parsing:
--call repo.usp_sync_guid (quick and minimal) or repo.usp_main (takes more time)
Exec repo.usp_sync_guid;

--use sqlparser to parse sql definitions for views and import parsing results
--for example in the folder containing the sqlparser.py call
--py sqlparser.py --server localhost\sql2019 --database dhw_mydatabase

--persist sql parsing results:
Exec sqlparse.usp_sqlparse

--ensure consistent repository after sql parsing:
Exec repo.usp_main;

--export Antora documentation sources
Exec docs.usp_AntoraExport;
// end::exampleusage[]


=== exampleUsage_2

// tag::exampleusage_2[]

// end::exampleusage_2[]


=== exampleUsage_3

// tag::exampleusage_3[]

// end::exampleusage_3[]


=== exampleUsage_4

// tag::exampleusage_4[]

// end::exampleusage_4[]


=== exampleUsage_5

// tag::exampleusage_5[]

// end::exampleusage_5[]


=== exampleWrong_Usage

// tag::examplewrong_usage[]

// end::examplewrong_usage[]


=== has_execution_plan_issue

// tag::has_execution_plan_issue[]

// end::has_execution_plan_issue[]


=== has_get_referenced_issue

// tag::has_get_referenced_issue[]

// end::has_get_referenced_issue[]


=== has_history

// tag::has_history[]

// end::has_history[]


=== has_history_columns

// tag::has_history_columns[]

// end::has_history_columns[]


=== InheritanceType

// tag::inheritancetype[]

// end::inheritancetype[]


=== is_persistence

// tag::is_persistence[]

// end::is_persistence[]


=== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]

// end::is_persistence_check_duplicate_per_pk[]


=== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]

// end::is_persistence_check_for_empty_source[]


=== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]

// end::is_persistence_delete_changed[]


=== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]

// end::is_persistence_delete_missing[]


=== is_persistence_insert

// tag::is_persistence_insert[]

// end::is_persistence_insert[]


=== is_persistence_truncate

// tag::is_persistence_truncate[]

// end::is_persistence_truncate[]


=== is_persistence_update_changed

// tag::is_persistence_update_changed[]

// end::is_persistence_update_changed[]


=== is_repo_managed

// tag::is_repo_managed[]
0
// end::is_repo_managed[]


=== is_ssas

// tag::is_ssas[]
0
// end::is_ssas[]


=== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


=== MS_Description

// tag::ms_description[]
include::sqldb:partial$description/docs.usp_antoraexport.adoc[]

// end::ms_description[]


=== persistence_source_RepoObject_fullname

// tag::persistence_source_repoobject_fullname[]

// end::persistence_source_repoobject_fullname[]


=== persistence_source_RepoObject_fullname2

// tag::persistence_source_repoobject_fullname2[]

// end::persistence_source_repoobject_fullname2[]


=== persistence_source_RepoObject_guid

// tag::persistence_source_repoobject_guid[]

// end::persistence_source_repoobject_guid[]


=== persistence_source_RepoObject_xref

// tag::persistence_source_repoobject_xref[]

// end::persistence_source_repoobject_xref[]


=== pk_index_guid

// tag::pk_index_guid[]

// end::pk_index_guid[]


=== pk_IndexPatternColumnDatatype

// tag::pk_indexpatterncolumndatatype[]

// end::pk_indexpatterncolumndatatype[]


=== pk_IndexPatternColumnName

// tag::pk_indexpatterncolumnname[]

// end::pk_indexpatterncolumnname[]


=== pk_IndexSemanticGroup

// tag::pk_indexsemanticgroup[]

// end::pk_indexsemanticgroup[]


=== ReferencedObjectList

// tag::referencedobjectlist[]
* [config].[fs_get_parameter_value]
* [docs].[Culture]
* [docs].[fs_AntoraModuleFolder]
* [docs].[usp_AntoraExport_DocSnippet]
* [docs].[usp_AntoraExport_ObjectNavigation]
* [docs].[usp_AntoraExport_ObjectPage]
* [docs].[usp_AntoraExport_ObjectPageTemplate]
* [docs].[usp_AntoraExport_ObjectPartialProperties]
* [docs].[usp_AntoraExport_ObjectPuml]
* [docs].[usp_AntoraExport_ObjectRefCyclic]
* [docs].[usp_AntoraExport_Page_IndexSemanticGroup]
* [docs].[usp_AntoraExport_SsisNavigation]
* [docs].[usp_AntoraExport_SsisPage]
* [docs].[usp_AntoraExport_SsisPageTemplate]
* [docs].[usp_AntoraExport_SsisPartialProperties]
* [docs].[usp_AntoraExport_SsisPuml]
* [docs].[usp_PERSIST_RepoObject_OutputFilter_T]
* [logs].[usp_ExecutionLog_insert]
* [ssis].[Project]
// end::referencedobjectlist[]


=== usp_persistence_RepoObject_guid

// tag::usp_persistence_repoobject_guid[]

// end::usp_persistence_repoobject_guid[]


=== UspExamples

// tag::uspexamples[]

// end::uspexamples[]


=== uspgenerator_usp_id

// tag::uspgenerator_usp_id[]
27
// end::uspgenerator_usp_id[]


=== UspParameters

// tag::uspparameters[]

// end::uspparameters[]

== Boolean Attributes

source: property.RepoObjectProperty WHERE property_int = 1

// tag::boolean_attributes[]

// end::boolean_attributes[]

== sql_modules_definition

// tag::sql_modules_definition[]
[%collapsible]
=======
[source,sql,numbered]
----
/*
code of this procedure is managed in the dhw repository. Do not modify manually.
Use [uspgenerator].[GeneratorUsp], [uspgenerator].[GeneratorUspParameter], [uspgenerator].[GeneratorUspStep], [uspgenerator].[GeneratorUsp_SqlUsp]
*/
CREATE   PROCEDURE [docs].[usp_AntoraExport]
----keep the code between logging parameters and "START" unchanged!
---- parameters, used for logging; you don't need to care about them, but you can use them, wenn calling from SSIS or in your workflow to log the context of the procedure call
  @execution_instance_guid UNIQUEIDENTIFIER = NULL --SSIS system variable ExecutionInstanceGUID could be used, any other unique guid is also fine. If NULL, then NEWID() is used to create one
, @ssis_execution_id BIGINT = NULL --only SSIS system variable ServerExecutionID should be used, or any other consistent number system, do not mix different number systems
, @sub_execution_id INT = NULL --in case you log some sub_executions, for example in SSIS loops or sub packages
, @parent_execution_log_id BIGINT = NULL --in case a sup procedure is called, the @current_execution_log_id of the parent procedure should be propagated here. It allowes call stack analyzing
AS
BEGIN
DECLARE
 --
   @current_execution_log_id BIGINT --this variable should be filled only once per procedure call, it contains the first logging call for the step 'start'.
 , @current_execution_guid UNIQUEIDENTIFIER = NEWID() --a unique guid for any procedure call. It should be propagated to sub procedures using "@parent_execution_log_id = @current_execution_log_id"
 , @source_object NVARCHAR(261) = NULL --use it like '[schema].[object]', this allows data flow vizualizatiuon (include square brackets)
 , @target_object NVARCHAR(261) = NULL --use it like '[schema].[object]', this allows data flow vizualizatiuon (include square brackets)
 , @proc_id INT = @@procid
 , @proc_schema_name NVARCHAR(128) = OBJECT_SCHEMA_NAME(@@procid) --schema ande name of the current procedure should be automatically logged
 , @proc_name NVARCHAR(128) = OBJECT_NAME(@@procid)               --schema ande name of the current procedure should be automatically logged
 , @event_info NVARCHAR(MAX)
 , @step_id INT = 0
 , @step_name NVARCHAR(1000) = NULL
 , @rows INT

--[event_info] get's only the information about the "outer" calling process
--wenn the procedure calls sub procedures, the [event_info] will not change
SET @event_info = (
  SELECT TOP 1 [event_info]
  FROM sys.dm_exec_input_buffer(@@spid, CURRENT_REQUEST_ID())
  ORDER BY [event_info]
  )

IF @execution_instance_guid IS NULL
 SET @execution_instance_guid = NEWID();
--
--SET @rows = @@ROWCOUNT;
SET @step_id = @step_id + 1
SET @step_name = 'start'
SET @source_object = NULL
SET @target_object = NULL

EXEC logs.usp_ExecutionLog_insert
 --these parameters should be the same for all logging execution
   @execution_instance_guid = @execution_instance_guid
 , @ssis_execution_id = @ssis_execution_id
 , @sub_execution_id = @sub_execution_id
 , @parent_execution_log_id = @parent_execution_log_id
 , @current_execution_guid = @current_execution_guid
 , @proc_id = @proc_id
 , @proc_schema_name = @proc_schema_name
 , @proc_name = @proc_name
 , @event_info = @event_info
 --the following parameters are individual for each call
 , @step_id = @step_id --@step_id should be incremented before each call
 , @step_name = @step_name --assign individual step names for each call
 --only the "start" step should return the log id into @current_execution_log_id
 --all other calls should not overwrite @current_execution_log_id
 , @execution_log_id = @current_execution_log_id OUTPUT
----you can log the content of your own parameters, do this only in the start-step
----data type is sql_variant

--
PRINT '[docs].[usp_AntoraExport]'
--keep the code between logging parameters and "START" unchanged!
--
----START
--
----- start here with your own code
--
/*{"ReportUspStep":[{"Number":210,"Name":"declare variables","has_logging":0,"is_condition":0,"is_inactive":0,"is_SubProcedure":0}]}*/
PRINT CONCAT('usp_id;Number;Parent_Number: ',27,';',210,';',NULL);

DECLARE @command NVARCHAR(4000)
DECLARE @cultures_name NVARCHAR(10)
Declare @AntoraModule Varchar(50)



/*{"ReportUspStep":[{"Number":300,"Name":"check Parameter AntoraDeleteFilesInModuleFolders","has_logging":0,"is_condition":1,"is_inactive":0,"is_SubProcedure":0,"log_source_object":"[config].[Parameter]"}]}*/
IF [config].[fs_get_parameter_value]('AntoraDeleteFilesInModuleFolders','') = 1

/*{"ReportUspStep":[{"Number":310,"Parent_Number":300,"Name":"Delete Files but not folder in AntoraModule pages and partials - by cultures_name","has_logging":1,"is_condition":0,"is_inactive":0,"is_SubProcedure":0,"log_flag_InsertUpdateDelete":"I"}]}*/
BEGIN
PRINT CONCAT('usp_id;Number;Parent_Number: ',27,';',310,';',300);

Declare module_cursor Cursor Local Fast_Forward For
Select
    cultures_name
From
    docs.culture
Order By
    cultures_name

Open module_cursor

Fetch Next From module_cursor
Into
    @cultures_name

While @@Fetch_Status = 0
Begin

    /*
FORFILES /p "D:\Repos\gitlab\DataHandwerk\dhw-antora-sqldb\docs\modules\sqldb\partials" /s /m *.* /c "cmd /c if @isdir==FALSE del @path"
*/
    Set @command
        = N'FORFILES /p "'
          --
          --
          + docs.fs_AntoraModuleFolder ( @cultures_name )
          + '\partials'
          --
          + N'" /s /m *.* /c "cmd /c if @isdir==FALSE del @path"'

    Print @command

    --Execute the BCP command
    Exec sys.xp_cmdshell @command, no_output

    Set @command
        = N'FORFILES /p "'
          --
          --
          + docs.fs_AntoraModuleFolder ( @cultures_name )
          + '\pages'
          --
          + N'" /s /m *.* /c "cmd /c if @isdir==FALSE del @path"'

    Print @command

    --Execute the BCP command
    Exec sys.xp_cmdshell @command, no_output

    Fetch Next From module_cursor
    Into
        @cultures_name
End

Close module_cursor
Deallocate module_cursor

-- Logging START --
SET @rows = @@ROWCOUNT
SET @step_id = @step_id + 1
SET @step_name = 'Delete Files but not folder in AntoraModule pages and partials - by cultures_name'
SET @source_object = NULL
SET @target_object = NULL

EXEC logs.usp_ExecutionLog_insert 
 @execution_instance_guid = @execution_instance_guid
 , @ssis_execution_id = @ssis_execution_id
 , @sub_execution_id = @sub_execution_id
 , @parent_execution_log_id = @parent_execution_log_id
 , @current_execution_guid = @current_execution_guid
 , @proc_id = @proc_id
 , @proc_schema_name = @proc_schema_name
 , @proc_name = @proc_name
 , @event_info = @event_info
 , @step_id = @step_id
 , @step_name = @step_name
 , @source_object = @source_object
 , @target_object = @target_object
 , @inserted = @rows
-- Logging END --
END;

/*{"ReportUspStep":[{"Number":320,"Parent_Number":300,"Name":"Delete Files but not folder in AntoraModule pages and partials - by SSIS AntoraModule","has_logging":1,"is_condition":0,"is_inactive":0,"is_SubProcedure":0,"log_flag_InsertUpdateDelete":"I"}]}*/
ELSE
BEGIN
PRINT CONCAT('usp_id;Number;Parent_Number: ',27,';',320,';',300);

Declare module_cursor Cursor Local Fast_Forward For
Select
    AntoraModule
From
    ssis.Project
Order By
    AntoraModule

Open module_cursor

Fetch Next From module_cursor
Into
    @AntoraModule

While @@Fetch_Status = 0
Begin

    /*
FORFILES /p "D:\Repos\gitlab\DataHandwerk\dhw-antora-sqldb\docs\modules\sqldb\partials" /s /m *.* /c "cmd /c if @isdir==FALSE del @path"
*/
    Set @command = N'FORFILES /p "'
                   --
                   --
                   + config.fs_get_parameter_value ( 'AntoraComponentFolder', '' ) + '\modules\' + @AntoraModule
                   --
                   + '\partials'
                   --
                   + N'" /s /m *.* /c "cmd /c if @isdir==FALSE del @path"'

    Print @command

    --Execute the BCP command
    Exec sys.xp_cmdshell @command, no_output

    Set @command = N'FORFILES /p "'
                   --
                   --
                   + config.fs_get_parameter_value ( 'AntoraComponentFolder', '' ) + '\modules\' + @AntoraModule
                   --
                   + '\pages'
                   --
                   + N'" /s /m *.* /c "cmd /c if @isdir==FALSE del @path"'

    Print @command

    --Execute the BCP command
    Exec sys.xp_cmdshell @command, no_output

    Fetch Next From module_cursor
    Into
        @AntoraModule
End

Close module_cursor
Deallocate module_cursor

-- Logging START --
SET @rows = @@ROWCOUNT
SET @step_id = @step_id + 1
SET @step_name = 'Delete Files but not folder in AntoraModule pages and partials - by SSIS AntoraModule'
SET @source_object = NULL
SET @target_object = NULL

EXEC logs.usp_ExecutionLog_insert 
 @execution_instance_guid = @execution_instance_guid
 , @ssis_execution_id = @ssis_execution_id
 , @sub_execution_id = @sub_execution_id
 , @parent_execution_log_id = @parent_execution_log_id
 , @current_execution_guid = @current_execution_guid
 , @proc_id = @proc_id
 , @proc_schema_name = @proc_schema_name
 , @proc_name = @proc_name
 , @event_info = @event_info
 , @step_id = @step_id
 , @step_name = @step_name
 , @source_object = @source_object
 , @target_object = @target_object
 , @inserted = @rows
-- Logging END --
END;

/*{"ReportUspStep":[{"Number":350,"Name":"[docs].[usp_AntoraExport_DocSnippet]","has_logging":1,"is_condition":0,"is_inactive":0,"is_SubProcedure":1}]}*/
EXEC [docs].[usp_AntoraExport_DocSnippet]
--add your own parameters
--logging parameters
 @execution_instance_guid = @execution_instance_guid
 , @ssis_execution_id = @ssis_execution_id
 , @sub_execution_id = @sub_execution_id
 , @parent_execution_log_id = @current_execution_log_id


/*{"ReportUspStep":[{"Number":400,"Name":"[docs].[usp_PERSIST_RepoObject_OutputFilter_T]","has_logging":1,"is_condition":0,"is_inactive":0,"is_SubProcedure":1}]}*/
EXEC [docs].[usp_PERSIST_RepoObject_OutputFilter_T]
--add your own parameters
--logging parameters
 @execution_instance_guid = @execution_instance_guid
 , @ssis_execution_id = @ssis_execution_id
 , @sub_execution_id = @sub_execution_id
 , @parent_execution_log_id = @current_execution_log_id


/*{"ReportUspStep":[{"Number":440,"Name":"[docs].[usp_AntoraExport_ObjectNavigation]","has_logging":1,"is_condition":0,"is_inactive":0,"is_SubProcedure":1}]}*/
EXEC [docs].[usp_AntoraExport_ObjectNavigation]
--add your own parameters
--logging parameters
 @execution_instance_guid = @execution_instance_guid
 , @ssis_execution_id = @ssis_execution_id
 , @sub_execution_id = @sub_execution_id
 , @parent_execution_log_id = @current_execution_log_id


/*{"ReportUspStep":[{"Number":500,"Name":"[docs].[usp_AntoraExport_ObjectPage]","has_logging":1,"is_condition":0,"is_inactive":0,"is_SubProcedure":1}]}*/
EXEC [docs].[usp_AntoraExport_ObjectPage]
--add your own parameters
--logging parameters
 @execution_instance_guid = @execution_instance_guid
 , @ssis_execution_id = @ssis_execution_id
 , @sub_execution_id = @sub_execution_id
 , @parent_execution_log_id = @current_execution_log_id


/*{"ReportUspStep":[{"Number":600,"Name":"[docs].[usp_AntoraExport_ObjectPageTemplate]","has_logging":1,"is_condition":0,"is_inactive":0,"is_SubProcedure":1}]}*/
EXEC [docs].[usp_AntoraExport_ObjectPageTemplate]
--add your own parameters
--logging parameters
 @execution_instance_guid = @execution_instance_guid
 , @ssis_execution_id = @ssis_execution_id
 , @sub_execution_id = @sub_execution_id
 , @parent_execution_log_id = @current_execution_log_id


/*{"ReportUspStep":[{"Number":750,"Name":"[docs].[usp_AntoraExport_ObjectPartialProperties]","has_logging":1,"is_condition":0,"is_inactive":0,"is_SubProcedure":1}]}*/
EXEC [docs].[usp_AntoraExport_ObjectPartialProperties]
--add your own parameters
--logging parameters
 @execution_instance_guid = @execution_instance_guid
 , @ssis_execution_id = @ssis_execution_id
 , @sub_execution_id = @sub_execution_id
 , @parent_execution_log_id = @current_execution_log_id


/*{"ReportUspStep":[{"Number":800,"Name":"[docs].[usp_AntoraExport_ObjectPuml]","has_logging":1,"is_condition":0,"is_inactive":0,"is_SubProcedure":1}]}*/
EXEC [docs].[usp_AntoraExport_ObjectPuml]
--add your own parameters
--logging parameters
 @execution_instance_guid = @execution_instance_guid
 , @ssis_execution_id = @ssis_execution_id
 , @sub_execution_id = @sub_execution_id
 , @parent_execution_log_id = @current_execution_log_id


/*{"ReportUspStep":[{"Number":910,"Name":"[docs].[usp_AntoraExport_Page_IndexSemanticGroup]","has_logging":1,"is_condition":0,"is_inactive":0,"is_SubProcedure":1}]}*/
EXEC [docs].[usp_AntoraExport_Page_IndexSemanticGroup]
--add your own parameters
--logging parameters
 @execution_instance_guid = @execution_instance_guid
 , @ssis_execution_id = @ssis_execution_id
 , @sub_execution_id = @sub_execution_id
 , @parent_execution_log_id = @current_execution_log_id


/*{"ReportUspStep":[{"Number":920,"Name":"[docs].[usp_AntoraExport_ObjectRefCyclic]","has_logging":1,"is_condition":0,"is_inactive":0,"is_SubProcedure":1}]}*/
EXEC [docs].[usp_AntoraExport_ObjectRefCyclic]
--add your own parameters
--logging parameters
 @execution_instance_guid = @execution_instance_guid
 , @ssis_execution_id = @ssis_execution_id
 , @sub_execution_id = @sub_execution_id
 , @parent_execution_log_id = @current_execution_log_id


/*{"ReportUspStep":[{"Number":1440,"Name":"[docs].[usp_AntoraExport_SsisNavigation]","has_logging":1,"is_condition":0,"is_inactive":0,"is_SubProcedure":1}]}*/
EXEC [docs].[usp_AntoraExport_SsisNavigation]
--add your own parameters
--logging parameters
 @execution_instance_guid = @execution_instance_guid
 , @ssis_execution_id = @ssis_execution_id
 , @sub_execution_id = @sub_execution_id
 , @parent_execution_log_id = @current_execution_log_id


/*{"ReportUspStep":[{"Number":1500,"Name":"[docs].[usp_AntoraExport_SsisPage]","has_logging":1,"is_condition":0,"is_inactive":0,"is_SubProcedure":1}]}*/
EXEC [docs].[usp_AntoraExport_SsisPage]
--add your own parameters
--logging parameters
 @execution_instance_guid = @execution_instance_guid
 , @ssis_execution_id = @ssis_execution_id
 , @sub_execution_id = @sub_execution_id
 , @parent_execution_log_id = @current_execution_log_id


/*{"ReportUspStep":[{"Number":1600,"Name":"[docs].[usp_AntoraExport_SsisPageTemplate]","has_logging":1,"is_condition":0,"is_inactive":0,"is_SubProcedure":1}]}*/
EXEC [docs].[usp_AntoraExport_SsisPageTemplate]
--add your own parameters
--logging parameters
 @execution_instance_guid = @execution_instance_guid
 , @ssis_execution_id = @ssis_execution_id
 , @sub_execution_id = @sub_execution_id
 , @parent_execution_log_id = @current_execution_log_id


/*{"ReportUspStep":[{"Number":1750,"Name":"[docs].[usp_AntoraExport_SsisPartialProperties]","has_logging":1,"is_condition":0,"is_inactive":0,"is_SubProcedure":1}]}*/
EXEC [docs].[usp_AntoraExport_SsisPartialProperties]
--add your own parameters
--logging parameters
 @execution_instance_guid = @execution_instance_guid
 , @ssis_execution_id = @ssis_execution_id
 , @sub_execution_id = @sub_execution_id
 , @parent_execution_log_id = @current_execution_log_id


/*{"ReportUspStep":[{"Number":1800,"Name":"[docs].[usp_AntoraExport_SsisPuml]","has_logging":1,"is_condition":0,"is_inactive":0,"is_SubProcedure":1}]}*/
EXEC [docs].[usp_AntoraExport_SsisPuml]
--add your own parameters
--logging parameters
 @execution_instance_guid = @execution_instance_guid
 , @ssis_execution_id = @ssis_execution_id
 , @sub_execution_id = @sub_execution_id
 , @parent_execution_log_id = @current_execution_log_id


--
--finish your own code here
--keep the code between "END" and the end of the procedure unchanged!
--
--END
--
--SET @rows = @@ROWCOUNT
SET @step_id = @step_id + 1
SET @step_name = 'end'
SET @source_object = NULL
SET @target_object = NULL

EXEC logs.usp_ExecutionLog_insert
   @execution_instance_guid = @execution_instance_guid
 , @ssis_execution_id = @ssis_execution_id
 , @sub_execution_id = @sub_execution_id
 , @parent_execution_log_id = @parent_execution_log_id
 , @current_execution_guid = @current_execution_guid
 , @proc_id = @proc_id
 , @proc_schema_name = @proc_schema_name
 , @proc_name = @proc_name
 , @event_info = @event_info
 , @step_id = @step_id
 , @step_name = @step_name
 , @source_object = @source_object
 , @target_object = @target_object

END


----
=======
// end::sql_modules_definition[]


