// tag::HeaderFullDisplayName[]
= property.RepoObjectProperty_Collect_source_ROGross
// end::HeaderFullDisplayName[]

== existing_properties

// tag::existing_properties[]
:ExistsProperty--antorareferencedlist:
:ExistsProperty--antorareferencinglist:
:ExistsProperty--is_repo_managed:
:ExistsProperty--is_ssas:
:ExistsProperty--pk_index_guid:
:ExistsProperty--pk_indexpatterncolumndatatype:
:ExistsProperty--pk_indexpatterncolumnname:
:ExistsProperty--referencedobjectlist:
:ExistsProperty--sql_modules_definition:
:ExistsProperty--FK:
:ExistsProperty--AntoraIndexList:
:ExistsProperty--Columns:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
B6FE9885-EA9D-EB11-84F6-A81E8446D5B0
// end::RepoObject_guid[]

== RepoObject_FullDisplayName2

// tag::RepoObject_FullDisplayName2[]
property.RepoObjectProperty_Collect_source_ROGross
// end::RepoObject_FullDisplayName2[]

== SysObject_type

// tag::SysObject_type[]
V 
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
view
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
1364915934
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2021-10-04 13:46:08
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]
[discrete]
== _


[#column-repoobjectunderlineguid]
=== RepoObject_guid

[cols="d,8m,m,m,m,d"]
|===
|1
|*RepoObject_guid*
|uniqueidentifier
|NOT NULL
|
|
|===

.Referenced Columns
--
* xref:repo.repoobject_gross.adoc#column-repoobjectunderlineguid[+repo.RepoObject_gross.RepoObject_guid+]
--


[#column-propertyunderlinename]
=== property_name

[cols="d,8m,m,m,m,d"]
|===
|2
|*property_name*
|varchar(39)
|NOT NULL
|
|
|===


[#column-propertyunderlinevalue]
=== property_value

[cols="d,8m,m,m,m,d"]
|===
|
|property_value
|nvarchar(max)
|NULL
|
|
|===


// end::AntoraColumnDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]
|1
|*<<column-repoobjectunderlineguid>>*
|uniqueidentifier
|NOT NULL
|
|

|2
|*<<column-propertyunderlinename>>*
|varchar(39)
|NOT NULL
|
|


// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]


|
|<<column-propertyunderlinevalue>>
|nvarchar(max)
|NULL
|
|

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

[#index-pkunderlinerepoobjectpropertyunderlinecollectunderlinesourceunderlinerogross]
=== PK_RepoObjectProperty_Collect_source_ROGross

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-RepoObject_guid>>; uniqueidentifier
* <<column-property_name>>; varchar(39)
--
* PK, Unique, Real: 1, 1, 0


[#index-idxunderlinerepoobjectpropertyunderlinecollectunderlinesourceunderlinerogrossunderlineunderline2]
=== idx_RepoObjectProperty_Collect_source_ROGross++__++2

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-RepoObject_guid>>; uniqueidentifier
--
* PK, Unique, Real: 0, 0, 0

// end::AntoraIndexList[]

== AntoraMeasureDetails

// tag::AntoraMeasureDetails[]

// end::AntoraMeasureDetails[]

== AntoraParameterList

// tag::AntoraParameterList[]

// end::AntoraParameterList[]

== AntoraXrefCulturesList

// tag::AntoraXrefCulturesList[]
* xref:dhw:sqldb:property.repoobjectproperty_collect_source_rogross.adoc[] - 
// end::AntoraXrefCulturesList[]

== cultures_count

// tag::cultures_count[]
1
// end::cultures_count[]

== Other tags

source: property.RepoObjectProperty_cross As rop_cross


=== additional_reference_csv

// tag::additional_reference_csv[]

// end::additional_reference_csv[]


=== AdocUspSteps

// tag::adocuspsteps[]

// end::adocuspsteps[]


=== AntoraReferencedList

// tag::antorareferencedlist[]
* xref:repo.repoobject_gross.adoc[]
* xref:repo.repoobject_sat2_t.adoc[]
// end::antorareferencedlist[]


=== AntoraReferencingList

// tag::antorareferencinglist[]
* xref:property.usp_repoobjectproperty_collect.adoc[]
// end::antorareferencinglist[]


=== Description

// tag::description[]

// end::description[]


=== ExampleUsage

// tag::exampleusage[]

// end::exampleusage[]


=== exampleUsage_2

// tag::exampleusage_2[]

// end::exampleusage_2[]


=== exampleUsage_3

// tag::exampleusage_3[]

// end::exampleusage_3[]


=== exampleUsage_4

// tag::exampleusage_4[]

// end::exampleusage_4[]


=== exampleUsage_5

// tag::exampleusage_5[]

// end::exampleusage_5[]


=== exampleWrong_Usage

// tag::examplewrong_usage[]

// end::examplewrong_usage[]


=== has_execution_plan_issue

// tag::has_execution_plan_issue[]

// end::has_execution_plan_issue[]


=== has_get_referenced_issue

// tag::has_get_referenced_issue[]

// end::has_get_referenced_issue[]


=== has_history

// tag::has_history[]

// end::has_history[]


=== has_history_columns

// tag::has_history_columns[]

// end::has_history_columns[]


=== InheritanceType

// tag::inheritancetype[]

// end::inheritancetype[]


=== is_persistence

// tag::is_persistence[]

// end::is_persistence[]


=== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]

// end::is_persistence_check_duplicate_per_pk[]


=== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]

// end::is_persistence_check_for_empty_source[]


=== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]

// end::is_persistence_delete_changed[]


=== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]

// end::is_persistence_delete_missing[]


=== is_persistence_insert

// tag::is_persistence_insert[]

// end::is_persistence_insert[]


=== is_persistence_truncate

// tag::is_persistence_truncate[]

// end::is_persistence_truncate[]


=== is_persistence_update_changed

// tag::is_persistence_update_changed[]

// end::is_persistence_update_changed[]


=== is_repo_managed

// tag::is_repo_managed[]
0
// end::is_repo_managed[]


=== is_ssas

// tag::is_ssas[]
0
// end::is_ssas[]


=== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


=== MS_Description

// tag::ms_description[]

// end::ms_description[]


=== persistence_source_RepoObject_fullname

// tag::persistence_source_repoobject_fullname[]

// end::persistence_source_repoobject_fullname[]


=== persistence_source_RepoObject_fullname2

// tag::persistence_source_repoobject_fullname2[]

// end::persistence_source_repoobject_fullname2[]


=== persistence_source_RepoObject_guid

// tag::persistence_source_repoobject_guid[]

// end::persistence_source_repoobject_guid[]


=== persistence_source_RepoObject_xref

// tag::persistence_source_repoobject_xref[]

// end::persistence_source_repoobject_xref[]


=== pk_index_guid

// tag::pk_index_guid[]
0E77EB3A-5F9F-EB11-84F8-A81E8446D5B0
// end::pk_index_guid[]


=== pk_IndexPatternColumnDatatype

// tag::pk_indexpatterncolumndatatype[]
uniqueidentifier,varchar(39)
// end::pk_indexpatterncolumndatatype[]


=== pk_IndexPatternColumnName

// tag::pk_indexpatterncolumnname[]
RepoObject_guid,property_name
// end::pk_indexpatterncolumnname[]


=== pk_IndexSemanticGroup

// tag::pk_indexsemanticgroup[]

// end::pk_indexsemanticgroup[]


=== ReferencedObjectList

// tag::referencedobjectlist[]
* [repo].[RepoObject_gross]
* [repo].[RepoObject_sat2_T]
// end::referencedobjectlist[]


=== usp_persistence_RepoObject_guid

// tag::usp_persistence_repoobject_guid[]

// end::usp_persistence_repoobject_guid[]


=== UspExamples

// tag::uspexamples[]

// end::uspexamples[]


=== uspgenerator_usp_id

// tag::uspgenerator_usp_id[]

// end::uspgenerator_usp_id[]


=== UspParameters

// tag::uspparameters[]

// end::uspparameters[]

== Boolean Attributes

source: property.RepoObjectProperty WHERE property_int = 1

// tag::boolean_attributes[]

// end::boolean_attributes[]

== sql_modules_definition

// tag::sql_modules_definition[]
[%collapsible]
=======
[source,sql,numbered]
----

CREATE View property.RepoObjectProperty_Collect_source_ROGross
As
Select
    ro.RepoObject_guid
  , property_name  = p_names.property_name
  , property_value =
  --
  Case p_names.property_name
      When 'pk_index_guid'
          Then
          Cast(ro.pk_index_guid As NVarchar(Max))
      When 'pk_IndexPatternColumnDatatype'
          Then
          Cast(ro.pk_IndexPatternColumnDatatype As NVarchar(Max))
      When 'pk_IndexPatternColumnName'
          Then
          Cast(ro.pk_IndexPatternColumnName As NVarchar(Max))
      When 'pk_IndexSemanticGroup'
          Then
          Cast(ro.pk_IndexSemanticGroup As NVarchar(Max))
      When 'is_repo_managed'
          Then
          Cast(IsNull ( ro.is_repo_managed, 0 ) As NVarchar(Max))
      When 'is_ssas'
          Then
          Cast(IsNull ( ro.is_ssas, 0 ) As NVarchar(Max))
      When 'Description'
          Then
          Cast(ro.Description As NVarchar(Max))
      When 'uspgenerator_usp_id'
          Then
          Cast(ro.uspgenerator_usp_id As NVarchar(Max))
      When 'usp_persistence_RepoObject_guid'
          Then
          Cast(ro.usp_persistence_RepoObject_guid As NVarchar(Max))
      When 'persistence_source_RepoObject_guid'
          Then
          Cast(ro.persistence_source_RepoObject_guid As NVarchar(Max))
      When 'persistence_source_RepoObject_fullname'
          Then
          Cast(ro.persistence_source_RepoObject_fullname As NVarchar(Max))
      When 'persistence_source_RepoObject_fullname2'
          Then
          Cast(ro.persistence_source_RepoObject_fullname2 As NVarchar(Max))
      When 'persistence_source_RepoObject_xref'
          Then
          Cast(ro.persistence_source_RepoObject_xref As NVarchar(Max))
      When 'has_history'
          Then
          Cast(ro.has_history As NVarchar(Max))
      When 'has_history_columns'
          Then
          Cast(ro.has_history_columns As NVarchar(Max))
      When 'is_persistence'
          Then
          Cast(ro.is_persistence As NVarchar(Max))
      When 'is_persistence_check_duplicate_per_pk'
          Then
          Cast(ro.is_persistence_check_duplicate_per_pk As NVarchar(Max))
      When 'is_persistence_check_for_empty_source'
          Then
          Cast(ro.is_persistence_check_for_empty_source As NVarchar(Max))
      When 'is_persistence_delete_missing'
          Then
          Cast(ro.is_persistence_delete_missing As NVarchar(Max))
      When 'is_persistence_delete_changed'
          Then
          Cast(ro.is_persistence_delete_changed As NVarchar(Max))
      When 'is_persistence_insert'
          Then
          Cast(ro.is_persistence_insert As NVarchar(Max))
      When 'is_persistence_truncate'
          Then
          Cast(ro.is_persistence_truncate As NVarchar(Max))
      When 'is_persistence_update_changed'
          Then
          Cast(ro.is_persistence_update_changed As NVarchar(Max))
      When 'history_schema_name'
          Then
          Cast(ro.history_schema_name As NVarchar(Max))
      When 'history_table_name'
          Then
          Cast(ro.history_table_name As NVarchar(Max))
      When 'Inheritance_StringAggSeparatorSql'
          Then
          Cast(ro.Inheritance_StringAggSeparatorSql As NVarchar(Max))
      When 'InheritanceDefinition'
          Then
          Cast(ro.InheritanceDefinition As NVarchar(Max))
      When 'InheritanceType'
          Then
          Cast(ro.InheritanceType As NVarchar(Max))
      When 'AntoraReferencedList'
          Then
          Cast(ros2.AntoraReferencedList As NVarchar(Max))
      When 'AntoraReferencingList'
          Then
          Cast(ros2.AntoraReferencingList As NVarchar(Max))
      --When 'AntoraExternalReferencedList'
      --    Then
      --    Cast(ro.AntoraExternalReferencedList As NVarchar(Max))
      --When 'AntoraExternalReferencingList'
      --    Then
      --    Cast(ro.AntoraExternalReferencingList As NVarchar(Max))
      When 'has_execution_plan_issue'
          Then
          Cast(ro.has_execution_plan_issue As NVarchar(Max))
      When 'has_get_referenced_issue'
          Then
          Cast(ro.has_get_referenced_issue As NVarchar(Max))
  End
From
    repo.RepoObject_gross      As ro
    Left Join
        repo.RepoObject_sat2_T As ros2
            On
            ros2.RepoObject_guid = ro.RepoObject_guid

    --ensure all these property_name are included in the resulting view per RepoObject
    Cross Join
    (
        Values
            ( 'pk_index_guid' )
          , ( 'pk_IndexPatternColumnDatatype' )
          , ( 'pk_IndexPatternColumnName' )
          , ( 'pk_IndexSemanticGroup' )
          , ( 'is_repo_managed' )
          , ( 'is_ssas' )
          , ( 'Description' )
          , ( 'uspgenerator_usp_id' )
          , ( 'usp_persistence_RepoObject_guid' )
          , ( 'persistence_source_RepoObject_guid' )
          , ( 'persistence_source_RepoObject_fullname' )
          , ( 'persistence_source_RepoObject_fullname2' )
          , ( 'persistence_source_RepoObject_xref' )
          , ( 'has_history' )
          , ( 'has_history_columns' )
          , ( 'is_persistence' )
          , ( 'is_persistence_check_duplicate_per_pk' )
          , ( 'is_persistence_check_for_empty_source' )
          , ( 'is_persistence_delete_missing' )
          , ( 'is_persistence_delete_changed' )
          , ( 'is_persistence_insert' )
          , ( 'is_persistence_truncate' )
          , ( 'is_persistence_update_changed' )
          , ( 'history_schema_name' )
          , ( 'history_table_name' )
          , ( 'Inheritance_StringAggSeparatorSql' )
          , ( 'InheritanceDefinition' )
          , ( 'InheritanceType' )
          , ( 'AntoraReferencedList' )
          , ( 'AntoraReferencingList' )
          --, ( 'AntoraExternalReferencedList' )
          --, ( 'AntoraExternalReferencingList' )
          , ( 'has_execution_plan_issue' )
          , ( 'has_get_referenced_issue' )
    )                          As p_names ( property_name )
Where
    Not ro.RepoObject_guid Is Null

----
=======
// end::sql_modules_definition[]


