= [reference].[usp_RepoObjectColumnSource_virtual_set]

== existing_properties

// tag::existing_properties[]
:ExistsProperty--antorareferencedlist:
:ExistsProperty--exampleusage:
:ExistsProperty--is_repo_managed:
:ExistsProperty--is_ssas:
:ExistsProperty--ms_description:
:ExistsProperty--referencedobjectlist:
:ExistsProperty--sql_modules_definition:
:ExistsProperty--AntoraParameterList:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
7D9A3468-7DA6-EB11-84FB-A81E8446D5B0
// end::RepoObject_guid[]

== SysObject_type

// tag::SysObject_type[]
P 
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
stored procedure
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
1583344705
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2021-08-29 11:34:01
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]

// end::AntoraColumnDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]

// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

// end::AntoraIndexList[]

== AntoraParameterList

// tag::AntoraParameterList[]
* @RepoObjectColumn_guid (uniqueidentifier)
* @RepoObjectColumn_fullname (nvarchar(520))
* @RepoObjectColumn_fullname2 (nvarchar(386))
* @Source_RepoObjectColumn_guid (uniqueidentifier)
* @Source_RepoObjectColumn_fullname (nvarchar(520))
* @Source_RepoObjectColumn_fullname2 (nvarchar(386))
// end::AntoraParameterList[]

== Other tags

source: property.RepoObjectProperty_cross As rop_cross


=== AdocUspSteps

// tag::adocuspsteps[]

// end::adocuspsteps[]


=== AntoraReferencedList

// tag::antorareferencedlist[]
* xref:reference.RepoObjectColumnSource_virtual.adoc[]
* xref:repo.RepoObjectColumn.adoc[]
* xref:repo.RepoObjectColumn_gross.adoc[]
// end::antorareferencedlist[]


=== AntoraReferencingList

// tag::antorareferencinglist[]

// end::antorareferencinglist[]


=== exampleUsage

// tag::exampleusage[]

EXEC reference.usp_RepoObjectColumnSource_virtual_set
    @RepoObjectColumn_fullname2 = 'SchemaName.ObjectName.ColumnName'
  , @Source_RepoObjectColumn_fullname2 = 'SourceSchemaName.SourceObjectName.SourceColumnName';

EXEC reference.usp_RepoObjectColumnSource_virtual_set
    @RepoObjectColumn_fullname = '[SchemaName].[ObjectName].[ColumnName]'
  , @Source_RepoObjectColumn_fullname = '[SourceSchemaName].[SourceObjectName].[SourceColumnName]';
// end::exampleusage[]


=== exampleUsage_2

// tag::exampleusage_2[]

// end::exampleusage_2[]


=== exampleUsage_3

// tag::exampleusage_3[]

// end::exampleusage_3[]


=== exampleUsage_4

// tag::exampleusage_4[]

// end::exampleusage_4[]


=== exampleUsage_5

// tag::exampleusage_5[]

// end::exampleusage_5[]


=== exampleWrong_Usage

// tag::examplewrong_usage[]

// end::examplewrong_usage[]


=== has_execution_plan_issue

// tag::has_execution_plan_issue[]

// end::has_execution_plan_issue[]


=== has_get_referenced_issue

// tag::has_get_referenced_issue[]

// end::has_get_referenced_issue[]


=== has_history

// tag::has_history[]

// end::has_history[]


=== has_history_columns

// tag::has_history_columns[]

// end::has_history_columns[]


=== is_persistence

// tag::is_persistence[]

// end::is_persistence[]


=== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]

// end::is_persistence_check_duplicate_per_pk[]


=== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]

// end::is_persistence_check_for_empty_source[]


=== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]

// end::is_persistence_delete_changed[]


=== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]

// end::is_persistence_delete_missing[]


=== is_persistence_insert

// tag::is_persistence_insert[]

// end::is_persistence_insert[]


=== is_persistence_truncate

// tag::is_persistence_truncate[]

// end::is_persistence_truncate[]


=== is_persistence_update_changed

// tag::is_persistence_update_changed[]

// end::is_persistence_update_changed[]


=== is_repo_managed

// tag::is_repo_managed[]
0
// end::is_repo_managed[]


=== is_ssas

// tag::is_ssas[]
0
// end::is_ssas[]


=== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


=== MS_Description

// tag::ms_description[]

insert entries into xref:sqldb:reference.RepoObjectColumnSource_virtual.adoc[], using guid, fullname or fullname2
// end::ms_description[]


=== persistence_source_RepoObject_fullname

// tag::persistence_source_repoobject_fullname[]

// end::persistence_source_repoobject_fullname[]


=== persistence_source_RepoObject_fullname2

// tag::persistence_source_repoobject_fullname2[]

// end::persistence_source_repoobject_fullname2[]


=== persistence_source_RepoObject_guid

// tag::persistence_source_repoobject_guid[]

// end::persistence_source_repoobject_guid[]


=== persistence_source_RepoObject_xref

// tag::persistence_source_repoobject_xref[]

// end::persistence_source_repoobject_xref[]


=== pk_index_guid

// tag::pk_index_guid[]

// end::pk_index_guid[]


=== pk_IndexPatternColumnDatatype

// tag::pk_indexpatterncolumndatatype[]

// end::pk_indexpatterncolumndatatype[]


=== pk_IndexPatternColumnName

// tag::pk_indexpatterncolumnname[]

// end::pk_indexpatterncolumnname[]


=== pk_IndexSemanticGroup

// tag::pk_indexsemanticgroup[]

// end::pk_indexsemanticgroup[]


=== ReferencedObjectList

// tag::referencedobjectlist[]
* [reference].[RepoObjectColumnSource_virtual]
* [repo].[RepoObjectColumn]
* [repo].[RepoObjectColumn_gross]
// end::referencedobjectlist[]


=== usp_persistence_RepoObject_guid

// tag::usp_persistence_repoobject_guid[]

// end::usp_persistence_repoobject_guid[]


=== UspExamples

// tag::uspexamples[]

// end::uspexamples[]


=== UspParameters

// tag::uspparameters[]

// end::uspparameters[]

== Boolean Attributes

source: property.RepoObjectProperty WHERE property_int = 1

// tag::boolean_attributes[]

// end::boolean_attributes[]

== sql_modules_definition

// tag::sql_modules_definition[]
[%collapsible]
=======
[source,sql]
----

/*
<<property_start>>MS_Description 
insert entries into xref:sqldb:reference.RepoObjectColumnSource_virtual.adoc[], using guid, fullname or fullname2
<<property_end>> 

<<property_start>>exampleUsage
EXEC reference.usp_RepoObjectColumnSource_virtual_set
    @RepoObjectColumn_fullname2 = 'SchemaName.ObjectName.ColumnName'
  , @Source_RepoObjectColumn_fullname2 = 'SourceSchemaName.SourceObjectName.SourceColumnName';

EXEC reference.usp_RepoObjectColumnSource_virtual_set
    @RepoObjectColumn_fullname = '[SchemaName].[ObjectName].[ColumnName]'
  , @Source_RepoObjectColumn_fullname = '[SourceSchemaName].[SourceObjectName].[SourceColumnName]';
<<property_end>>
*/
CREATE Procedure reference.usp_RepoObjectColumnSource_virtual_set
    --
    @RepoObjectColumn_guid             UniqueIdentifier = Null --if @RepoObjectColumn_guid is NULL, then @RepoObjectColumn_fullname or @RepoObjectColumn_fullname2 are used
  , @RepoObjectColumn_fullname         NVarchar(520)    = Null --can be used to define @RepoObjectColumn_guid; use '[SchemaName].[ObjectName].[ColumnName]'
  , @RepoObjectColumn_fullname2        NVarchar(386)    = Null --can be used to define @RepoObjectColumn_guid; use 'SchemaName.ObjectName.ColumnName'
  , @Source_RepoObjectColumn_guid      UniqueIdentifier = Null --if @Source_RepoObjectColumn_guid is NULL, then @Source_RepoObjectColumn_fullname or @Source_RepoObjectColumn_fullname2 are used
  , @Source_RepoObjectColumn_fullname  NVarchar(520)    = Null --can be used to define @Source_RepoObjectColumn_guid; use '[SchemaName].[ObjectName].[ColumnName]'
  , @Source_RepoObjectColumn_fullname2 NVarchar(386)    = Null --can be used to define @Source_RepoObjectColumn_guid; use 'SchemaName.ObjectName.ColumnName'
As
Begin
    Declare @step_name NVarchar(1000) = Null;

    If @RepoObjectColumn_guid Is Null
        Set @RepoObjectColumn_guid =
    (
        Select
            roc.RepoObjectColumn_guid
        From
            repo.RepoObjectColumn_gross As roc
        Where
            roc.RepoObjectColumn_fullname = @RepoObjectColumn_fullname
    )   ;

    If @RepoObjectColumn_guid Is Null
        Set @RepoObjectColumn_guid =
    (
        Select
            roc.RepoObjectColumn_guid
        From
            repo.RepoObjectColumn_gross As roc
        Where
            roc.RepoObjectColumn_fullname2 = @RepoObjectColumn_fullname2
    )   ;

    --check existence of @RepoObjectColumn_guid
    If Not Exists
    (
        Select
            1
        From
            repo.RepoObjectColumn
        Where
            RepoObjectColumn_guid = @RepoObjectColumn_guid
    )
    Begin
        Set @step_name
            = Concat (
                         'RepoObjectColumn_guid does not exist;'
                       , @RepoObjectColumn_guid
                       , ';'
                       , @RepoObjectColumn_fullname
                       , ';'
                       , @RepoObjectColumn_fullname2
                     );

        Throw 51001, @step_name, 1;
    End;

    If @Source_RepoObjectColumn_guid Is Null
        Set @Source_RepoObjectColumn_guid =
    (
        Select
            roc.RepoObjectColumn_guid
        From
            repo.RepoObjectColumn_gross As roc
        Where
            roc.RepoObjectColumn_fullname = @Source_RepoObjectColumn_fullname
    )   ;

    If @Source_RepoObjectColumn_guid Is Null
        Set @Source_RepoObjectColumn_guid =
    (
        Select
            roc.RepoObjectColumn_guid
        From
            repo.RepoObjectColumn_gross As roc
        Where
            roc.RepoObjectColumn_fullname2 = @Source_RepoObjectColumn_fullname2
    )   ;

    --check existence of @RepoObjectColumn_guid
    If Not Exists
    (
        Select
            1
        From
            repo.RepoObjectColumn
        Where
            RepoObjectColumn_guid = @Source_RepoObjectColumn_guid
    )
    Begin
        Set @step_name
            = Concat (
                         'Source_RepoObjectColumn_guid does not exist;'
                       , @Source_RepoObjectColumn_guid
                       , ';'
                       , @Source_RepoObjectColumn_fullname
                       , ';'
                       , @Source_RepoObjectColumn_fullname2
                     );

        Throw 51002, @step_name, 1;
    End;

    If Not Exists
    (
        Select
            1
        From
            reference.RepoObjectColumnSource_virtual
        Where
            RepoObjectColumn_guid            = @RepoObjectColumn_guid
            And Source_RepoObjectColumn_guid = @Source_RepoObjectColumn_guid
    )
        Insert Into reference.RepoObjectColumnSource_virtual
        Values
            (
                @RepoObjectColumn_guid
              , @Source_RepoObjectColumn_guid
            );
End;
----
=======
// end::sql_modules_definition[]


