// tag::HeaderFullDisplayName[]
= repo.RepoObject_SqlCreateTable
// end::HeaderFullDisplayName[]

== existing_properties

// tag::existing_properties[]
:ExistsProperty--antorareferencedlist:
:ExistsProperty--antorareferencinglist:
:ExistsProperty--exampleusage:
:ExistsProperty--is_repo_managed:
:ExistsProperty--is_ssas:
:ExistsProperty--pk_index_guid:
:ExistsProperty--pk_indexpatterncolumndatatype:
:ExistsProperty--pk_indexpatterncolumnname:
:ExistsProperty--referencedobjectlist:
:ExistsProperty--sql_modules_definition:
:ExistsProperty--FK:
:ExistsProperty--AntoraIndexList:
:ExistsProperty--Columns:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
7990291C-9D61-EB11-84DC-A81E8446D5B0
// end::RepoObject_guid[]

== RepoObject_FullDisplayName2

// tag::RepoObject_FullDisplayName2[]
repo.RepoObject_SqlCreateTable
// end::RepoObject_FullDisplayName2[]

== SysObject_type

// tag::SysObject_type[]
V 
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
view
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
1844917644
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2021-10-02 13:23:34
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]
[#column-repoobject_guid]
=== repoobject_guid

[cols="d,8m,m,m,m,d"]
|===
|1
|*RepoObject_guid*
|uniqueidentifier
|NOT NULL
|
|
|===


[#column-conlist]
=== conlist

[cols="d,8m,m,m,m,d"]
|===
|
|ConList
|nvarchar(max)
|NULL
|
|
|===


[#column-dbmltable]
=== dbmltable

[cols="d,8m,m,m,m,d"]
|===
|
|DbmlTable
|nvarchar(max)
|NOT NULL
|
|
|===


[#column-persistence_source_repoobject_fullname]
=== persistence_source_repoobject_fullname

[cols="d,8m,m,m,m,d"]
|===
|
|persistence_source_RepoObject_fullname
|nvarchar(261)
|NULL
|
|
|===


[#column-persistence_source_repoobject_guid]
=== persistence_source_repoobject_guid

[cols="d,8m,m,m,m,d"]
|===
|
|persistence_source_RepoObject_guid
|uniqueidentifier
|NULL
|
|
|===


[#column-persistence_source_sysobject_fullname]
=== persistence_source_sysobject_fullname

[cols="d,8m,m,m,m,d"]
|===
|
|persistence_source_SysObject_fullname
|nvarchar(261)
|NULL
|
|
|===


[#column-repoobject_fullname]
=== repoobject_fullname

[cols="d,8m,m,m,m,d"]
|===
|
|RepoObject_fullname
|nvarchar(261)
|NOT NULL
|
|
|===


[#column-sqlcreatetable]
=== sqlcreatetable

[cols="d,8m,m,m,m,d"]
|===
|
|SqlCreateTable
|nvarchar(max)
|NOT NULL
|
|
|===


// end::AntoraColumnDetails[]

== AntoraMeasureDetails

// tag::AntoraMeasureDetails[]

// end::AntoraMeasureDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]
|1
|*<<column-repoobject_guid>>*
|uniqueidentifier
|NOT NULL
|
|








// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]

|
|<<column-conlist>>
|nvarchar(max)
|NULL
|
|

|
|<<column-dbmltable>>
|nvarchar(max)
|NOT NULL
|
|

|
|<<column-persistence_source_repoobject_fullname>>
|nvarchar(261)
|NULL
|
|

|
|<<column-persistence_source_repoobject_guid>>
|uniqueidentifier
|NULL
|
|

|
|<<column-persistence_source_sysobject_fullname>>
|nvarchar(261)
|NULL
|
|

|
|<<column-repoobject_fullname>>
|nvarchar(261)
|NOT NULL
|
|

|
|<<column-sqlcreatetable>>
|nvarchar(max)
|NOT NULL
|
|

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

[#index-pk_repoobject_sqlcreatetable]
=== pk_repoobject_sqlcreatetable

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#openingbracketnoblankgroupclosingbracket[no_group]
+
--
* <<column-RepoObject_guid>>; uniqueidentifier
--
* PK, Unique, Real: 1, 1, 0

// end::AntoraIndexList[]

== AntoraParameterList

// tag::AntoraParameterList[]

// end::AntoraParameterList[]

== Other tags

source: property.RepoObjectProperty_cross As rop_cross


=== additional_reference_csv

// tag::additional_reference_csv[]

// end::additional_reference_csv[]


=== AdocUspSteps

// tag::adocuspsteps[]

// end::adocuspsteps[]


=== AntoraReferencedList

// tag::antorareferencedlist[]
* xref:config.ftv_dwh_database.adoc[]
* xref:config.ftv_get_parameter_value.adoc[]
* xref:repo.index_gross.adoc[]
* xref:repo.index_sqlconstraint_pkuq.adoc[]
* xref:repo.repoobject.adoc[]
* xref:repo.repoobject_columnlist.adoc[]
* xref:repo.repoobject_gross.adoc[]
* xref:repo.repoobjectcolumn.adoc[]
// end::antorareferencedlist[]


=== AntoraReferencingList

// tag::antorareferencinglist[]
* xref:reference.ftv_repoobject_columreferencerepoobject.adoc[]
// end::antorareferencinglist[]


=== Description

// tag::description[]

// end::description[]


=== exampleUsage

// tag::exampleusage[]

--get sql code CREATE OR ALTER TABLE for persistence tables
Select
    RepoObject_guid
  , RepoObject_fullname
  , SqlCreateTable
--, DbmlTable
--, ConList
--, persistence_source_RepoObject_fullname
--, persistence_source_RepoObject_guid
--, persistence_source_SysObject_fullname
From
    dhw_self.repo.RepoObject_SqlCreateTable
Where
    Not persistence_source_RepoObject_guid Is Null
Order By
    RepoObject_fullname;
// end::exampleusage[]


=== exampleUsage_2

// tag::exampleusage_2[]

// end::exampleusage_2[]


=== exampleUsage_3

// tag::exampleusage_3[]

// end::exampleusage_3[]


=== exampleUsage_4

// tag::exampleusage_4[]

// end::exampleusage_4[]


=== exampleUsage_5

// tag::exampleusage_5[]

// end::exampleusage_5[]


=== exampleWrong_Usage

// tag::examplewrong_usage[]

// end::examplewrong_usage[]


=== has_execution_plan_issue

// tag::has_execution_plan_issue[]

// end::has_execution_plan_issue[]


=== has_get_referenced_issue

// tag::has_get_referenced_issue[]

// end::has_get_referenced_issue[]


=== has_history

// tag::has_history[]

// end::has_history[]


=== has_history_columns

// tag::has_history_columns[]

// end::has_history_columns[]


=== InheritanceType

// tag::inheritancetype[]

// end::inheritancetype[]


=== is_persistence

// tag::is_persistence[]

// end::is_persistence[]


=== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]

// end::is_persistence_check_duplicate_per_pk[]


=== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]

// end::is_persistence_check_for_empty_source[]


=== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]

// end::is_persistence_delete_changed[]


=== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]

// end::is_persistence_delete_missing[]


=== is_persistence_insert

// tag::is_persistence_insert[]

// end::is_persistence_insert[]


=== is_persistence_truncate

// tag::is_persistence_truncate[]

// end::is_persistence_truncate[]


=== is_persistence_update_changed

// tag::is_persistence_update_changed[]

// end::is_persistence_update_changed[]


=== is_repo_managed

// tag::is_repo_managed[]
0
// end::is_repo_managed[]


=== is_ssas

// tag::is_ssas[]
0
// end::is_ssas[]


=== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


=== MS_Description

// tag::ms_description[]

// end::ms_description[]


=== persistence_source_RepoObject_fullname

// tag::persistence_source_repoobject_fullname[]

// end::persistence_source_repoobject_fullname[]


=== persistence_source_RepoObject_fullname2

// tag::persistence_source_repoobject_fullname2[]

// end::persistence_source_repoobject_fullname2[]


=== persistence_source_RepoObject_guid

// tag::persistence_source_repoobject_guid[]

// end::persistence_source_repoobject_guid[]


=== persistence_source_RepoObject_xref

// tag::persistence_source_repoobject_xref[]

// end::persistence_source_repoobject_xref[]


=== pk_index_guid

// tag::pk_index_guid[]
662DB2AA-0F96-EB11-84F4-A81E8446D5B0
// end::pk_index_guid[]


=== pk_IndexPatternColumnDatatype

// tag::pk_indexpatterncolumndatatype[]
uniqueidentifier
// end::pk_indexpatterncolumndatatype[]


=== pk_IndexPatternColumnName

// tag::pk_indexpatterncolumnname[]
RepoObject_guid
// end::pk_indexpatterncolumnname[]


=== pk_IndexSemanticGroup

// tag::pk_indexsemanticgroup[]

// end::pk_indexsemanticgroup[]


=== ReferencedObjectList

// tag::referencedobjectlist[]
* [config].[ftv_dwh_database]
* [config].[ftv_get_parameter_value]
* [repo].[Index_gross]
* [repo].[Index_SqlConstraint_PkUq]
* [repo].[RepoObject]
* [repo].[RepoObject_ColumnList]
* [repo].[RepoObject_gross]
* [repo].[RepoObjectColumn]
// end::referencedobjectlist[]


=== usp_persistence_RepoObject_guid

// tag::usp_persistence_repoobject_guid[]

// end::usp_persistence_repoobject_guid[]


=== UspExamples

// tag::uspexamples[]

// end::uspexamples[]


=== uspgenerator_usp_id

// tag::uspgenerator_usp_id[]

// end::uspgenerator_usp_id[]


=== UspParameters

// tag::uspparameters[]

// end::uspparameters[]

== Boolean Attributes

source: property.RepoObjectProperty WHERE property_int = 1

// tag::boolean_attributes[]

// end::boolean_attributes[]

== sql_modules_definition

// tag::sql_modules_definition[]
[%collapsible]
=======
[source,sql]
----


/*
<<property_start>>exampleUsage
--get sql code CREATE OR ALTER TABLE for persistence tables
Select
    RepoObject_guid
  , RepoObject_fullname
  , SqlCreateTable
--, DbmlTable
--, ConList
--, persistence_source_RepoObject_fullname
--, persistence_source_RepoObject_guid
--, persistence_source_SysObject_fullname
From
    dhw_self.repo.RepoObject_SqlCreateTable
Where
    Not persistence_source_RepoObject_guid Is Null
Order By
    RepoObject_fullname;
<<property_end>>

*/
CREATE View [repo].[RepoObject_SqlCreateTable]
As
Select
    ro.RepoObject_guid
  , DbmlTable      = Concat (
                                'Table '
                              , QuoteName ( ro.RepoObject_fullname, '"' )
                              , '{'
                              , Char ( 13 )
                              , Char ( 10 )
                              , ColList.DbmlColumnList
                              --note: 'string to add notes'
                              , Case
                                    When Not ro.Description Is Null
                                        Then
                                        Char ( 13 ) + Char ( 10 ) + 'Note: ''''''' + Char ( 13 ) + Char ( 10 )
                                        + Replace ( Replace ( ro.Description, '\', '\\' ), '''''''', '\''''''' )
                                        + Char ( 13 ) + Char ( 10 ) + ''''''''
                                    Else
                                        Null
                                End
                              --optional Settings [setting1: value1, setting2: value2, setting3, setting4]
                              , Char ( 13 )
                              , Char ( 10 )
                              , Case
                                    When Not IndexList.DbmlIndexList Is Null
                                        Then
                                        Char ( 13 ) + Char ( 10 ) + 'indexes {' + Char ( 13 ) + Char ( 10 )
                                        + IndexList.DbmlIndexList + Char ( 13 ) + Char ( 10 ) + '}' + Char ( 13 )
                                        + Char ( 10 )
                                    Else
                                        Null
                                End
                              , '}'
                              , Char ( 13 )
                              , Char ( 10 )
                            )
  , ro.RepoObject_fullname
  , SqlCreateTable = Concat (
                                'USE  ['
                              , dwhdb.dwh_database_name
                              , ']'
                              , Char ( 13 ) + Char ( 10 )
                              , 'GO'
                              , Char ( 13 ) + Char ( 10 )
                              , 'CREATE TABLE '
                              , ro.RepoObject_fullname
                              , ' ('
                              , Char ( 13 )
                              , Char ( 10 )
                              , ColList.CreateColumnList
                              , Case
                                    When Exists
                                         (
                                             Select
                                                 1
                                             From
                                                 repo.Index_SqlConstraint_PkUq As ConList
                                             Where
                                                 ConList.parent_RepoObject_guid = ro.RepoObject_guid
                                         )
                                        Then
                                        ','
                                    Else
                                        Null
                                End
                              --CONSTRAINT PK, FK, depending on some settings
                              , ConList.ConList
                              --PERIOD FOR SYSTEM_TIME ([ValidFrom], [ValidTo])
                              , Case
                                    When Exists
                                         (
                                             Select
                                                 1
                                             From
                                                 repo.RepoObjectColumn As roc
                                             Where
                                                 roc.RepoObject_guid                = ro.RepoObject_guid
                                                 And roc.Repo_generated_always_type = 1
                                         )
                                         And Exists
                                             (
                                                 Select
                                                     1
                                                 From
                                                     repo.RepoObjectColumn As roc
                                                 Where
                                                     roc.RepoObject_guid                = ro.RepoObject_guid
                                                     And roc.Repo_generated_always_type = 2
                                             )
                                        Then
                                        Concat (
                                                   ', PERIOD FOR SYSTEM_TIME ('
                                                 , QuoteName ((
                                                                  Select
                                                                      Top ( 1 )
                                                                      roc.RepoObjectColumn_name
                                                                  From
                                                                      repo.RepoObjectColumn As roc
                                                                  Where
                                                                      roc.RepoObject_guid                = ro.RepoObject_guid
                                                                      And roc.Repo_generated_always_type = 1
                                                                  Order By
                                                                      RepoObjectColumn_name
                                                              )
                                                             )
                                                 , ', '
                                                 , QuoteName ((
                                                                  Select
                                                                      Top ( 1 )
                                                                      roc.RepoObjectColumn_name
                                                                  From
                                                                      repo.RepoObjectColumn As roc
                                                                  Where
                                                                      roc.RepoObject_guid                = ro.RepoObject_guid
                                                                      And roc.Repo_generated_always_type = 2
                                                                  Order By
                                                                      RepoObjectColumn_name
                                                              )
                                                             )
                                                 , ')'
                                                 , Char ( 13 )
                                                 , Char ( 10 )
                                               )
                                    Else
                                        Null
                                End
                              , ')'
                              --WITH
                              --(
                              --SYSTEM_VERSIONING = ON ( HISTORY_TABLE = [Application].[Cities_Archive] )
                              --)
                              , Case ro.Repo_temporal_type
                                    When 2
                                        Then
                                        Concat (
                                                   Char ( 13 )
                                                 , Char ( 10 )
                                                 , 'WITH'
                                                 , Char ( 13 )
                                                 , Char ( 10 )
                                                 , '('
                                                 , Char ( 13 )
                                                 , Char ( 10 )
                                                 , 'SYSTEM_VERSIONING = ON ( HISTORY_TABLE = '
                                                 --, '[Application].[Cities_Archive]'
                                                 , Coalesce (
                                                                ro_hist.RepoObject_fullname
                                                              , Concat (
                                                                           QuoteName ( IsNull (
                                                                                                  Hist_Table_schema.Parameter_value_result
                                                                                                , ro.RepoObject_schema_name
                                                                                              )
                                                                                     )
                                                                         , '.'
                                                                         , QuoteName ( Concat (
                                                                                                  ro.RepoObject_name
                                                                                                , Hist_Table_name_suffix.Parameter_value_result
                                                                                              )
                                                                                     )
                                                                       )
                                                            )
                                                 , ' )'
                                                 , Char ( 13 )
                                                 , Char ( 10 )
                                                 , ')'
                                                 , Char ( 13 )
                                                 , Char ( 10 )
                                               )
                                    Else
                                        Null
                                End
                            )
  --ConstraintList
  , ConList.ConList
  , ro.persistence_source_RepoObject_fullname
  , ro.persistence_source_RepoObject_guid
  , ro.persistence_source_SysObject_fullname
From
    repo.RepoObject_gross                                                 As ro
    --column list should exist, otherwise CREATE statement will be invalid
    Inner Join
        repo.RepoObject_ColumnList                                        As ColList
            On
            ColList.RepoObject_guid = ro.RepoObject_guid

    Left Join
    (
        Select
            Con.parent_RepoObject_guid
          , ConList = String_Agg (
                                     Concat (
                                                --we need to convert to first argument nvarchar(max) to avoid the limit of 8000 byte
                                                Cast(' ' As NVarchar(Max)), Con.SqlConstraint, Char ( 13 ), Char ( 10 )
                                            )
                                   , ','
                                 )
        From
            repo.Index_SqlConstraint_PkUq As Con
        Group By
            Con.parent_RepoObject_guid
    )                                                                     As ConList
        On
        ConList.parent_RepoObject_guid = ro.RepoObject_guid

    Left Join
    (
        Select
            i.parent_RepoObject_guid
          , DbmlIndexList = String_Agg (
                                           Concat (
                                                      --we need to convert to first argument nvarchar(max) to avoid the limit of 8000 byte
                                                      Cast(' ' As NVarchar(Max))
                                                    , '('
                                                    , i.DbmlIndexColumnList
                                                    , ') '
                                                    , '['
                                                    , Case
                                                          --this doesn't work. but we define pk in DbmlColumnList
                                                          When i.is_index_primary_key = 1
                                                              Then
                                                              'pk'
                                                          When i.is_index_unique = 1
                                                              Then
                                                              'unique'
                                                          Else
                                                              'name:''' + i.index_name + ''''
                                                      End
                                                    , ']'
                                                  )
                                         , Char ( 13 ) + Char ( 10 )
                                       ) Within Group(Order By
                                                          i.RowNumber_PkPerParentObject)
        From
            repo.Index_gross As i
        Where
            i.is_index_primary_key = 0
            And
            (
                i.is_index_unique  = 1
                Or i.is_index_real = 1
            )
        Group By
            i.parent_RepoObject_guid
    )                                                                     As IndexList
        On
        IndexList.parent_RepoObject_guid = ro.RepoObject_guid

    Left Join
        repo.RepoObject                                                   As ro_hist
            On
            ro_hist.RepoObject_guid = ro.Repo_history_table_guid
    Cross Join config.ftv_get_parameter_value ( 'Hist_Table_schema', '' ) As Hist_Table_schema
    Cross Join config.ftv_get_parameter_value ( 'Hist_Table_name_suffix', '' ) As Hist_Table_name_suffix
    Cross Join config.ftv_dwh_database () As dwhdb

----
=======
// end::sql_modules_definition[]


