= [repo].[RepoObject_ColumnList]

== existing_properties

// tag::existing_properties[]
:ExistsProperty--antorareferencedlist:
:ExistsProperty--antorareferencinglist:
:ExistsProperty--is_repo_managed:
:ExistsProperty--is_ssas:
:ExistsProperty--referencedobjectlist:
:ExistsProperty--sql_modules_definition:
:ExistsProperty--FK:
:ExistsProperty--AntoraIndexList:
:ExistsProperty--Columns:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
6F90291C-9D61-EB11-84DC-A81E8446D5B0
// end::RepoObject_guid[]

== SysObject_type

// tag::SysObject_type[]
V 
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
view
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
1124915079
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2021-08-29 11:31:29
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]
[#column-CreateColumnList]
=== CreateColumnList

[cols="d,8m,m,m,m,d"]
|===
|
|CreateColumnList
|nvarchar(max)
|NULL
|
|
|===

.Referencing Columns
--
* xref:repo.RepoObject_gross2.adoc#column-CreateColumnList[+repo.RepoObject_gross2.CreateColumnList+]
--


[#column-DbmlColumnList]
=== DbmlColumnList

[cols="d,8m,m,m,m,d"]
|===
|
|DbmlColumnList
|nvarchar(max)
|NULL
|
|
|===

.Referencing Columns
--
* xref:repo.RepoObject_gross2.adoc#column-DbmlColumnList[+repo.RepoObject_gross2.DbmlColumnList+]
--


[#column-PersistenceCompareColumnList]
=== PersistenceCompareColumnList

[cols="d,8m,m,m,m,d"]
|===
|
|PersistenceCompareColumnList
|nvarchar(max)
|NULL
|
|
|===

.Referencing Columns
--
* xref:repo.RepoObject_gross2.adoc#column-PersistenceCompareColumnList[+repo.RepoObject_gross2.PersistenceCompareColumnList+]
--


[#column-PersistenceInsertColumnList]
=== PersistenceInsertColumnList

[cols="d,8m,m,m,m,d"]
|===
|
|PersistenceInsertColumnList
|nvarchar(max)
|NULL
|
|
|===

.Referencing Columns
--
* xref:repo.RepoObject_gross2.adoc#column-PersistenceInsertColumnList[+repo.RepoObject_gross2.PersistenceInsertColumnList+]
--


[#column-PersistenceUpdateColumnList]
=== PersistenceUpdateColumnList

[cols="d,8m,m,m,m,d"]
|===
|
|PersistenceUpdateColumnList
|nvarchar(max)
|NULL
|
|
|===

.Referencing Columns
--
* xref:repo.RepoObject_gross2.adoc#column-PersistenceUpdateColumnList[+repo.RepoObject_gross2.PersistenceUpdateColumnList+]
--


[#column-RepoObject_guid]
=== RepoObject_guid

[cols="d,8m,m,m,m,d"]
|===
|
|RepoObject_guid
|uniqueidentifier
|NOT NULL
|
|
|===

.Referenced Columns
--
* xref:repo.RepoObjectColumn_gross2.adoc#column-RepoObject_guid[+repo.RepoObjectColumn_gross2.RepoObject_guid+]
--


[#column-RepoObjectColumn_fullname]
=== RepoObjectColumn_fullname

[cols="d,8m,m,m,m,d"]
|===
|
|RepoObjectColumn_fullname
|nvarchar(520)
|NULL
|
|
|===


// end::AntoraColumnDetails[]

== AntoraMeasureDetails

// tag::AntoraMeasureDetails[]

// end::AntoraMeasureDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]







// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]
|
|<<column-CreateColumnList>>
|nvarchar(max)
|NULL
|
|

|
|<<column-DbmlColumnList>>
|nvarchar(max)
|NULL
|
|

|
|<<column-PersistenceCompareColumnList>>
|nvarchar(max)
|NULL
|
|

|
|<<column-PersistenceInsertColumnList>>
|nvarchar(max)
|NULL
|
|

|
|<<column-PersistenceUpdateColumnList>>
|nvarchar(max)
|NULL
|
|

|
|<<column-RepoObject_guid>>
|uniqueidentifier
|NOT NULL
|
|

|
|<<column-RepoObjectColumn_fullname>>
|nvarchar(520)
|NULL
|
|

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

[#index-idx_RepoObject_ColumnList2x_1]
=== idx_RepoObject_ColumnList++__++1

* IndexSemanticGroup: xref:other/IndexSemanticGroup.adoc#openingbracketnoblankgroupclosingbracket[no_group]
+
--
* <<column-RepoObject_guid>>; uniqueidentifier
--
* PK, Unique, Real: 0, 0, 0

// end::AntoraIndexList[]

== AntoraParameterList

// tag::AntoraParameterList[]

// end::AntoraParameterList[]

== Other tags

source: property.RepoObjectProperty_cross As rop_cross


=== AdocUspSteps

// tag::adocuspsteps[]

// end::adocuspsteps[]


=== AntoraReferencedList

// tag::antorareferencedlist[]
* xref:repo.RepoObjectColumn_gross2.adoc[]
// end::antorareferencedlist[]


=== AntoraReferencingList

// tag::antorareferencinglist[]
* xref:repo.RepoObject_gross2.adoc[]
* xref:repo.RepoObject_SqlCreateTable.adoc[]
// end::antorareferencinglist[]


=== Description

// tag::description[]

// end::description[]


=== exampleUsage

// tag::exampleusage[]

// end::exampleusage[]


=== exampleUsage_2

// tag::exampleusage_2[]

// end::exampleusage_2[]


=== exampleUsage_3

// tag::exampleusage_3[]

// end::exampleusage_3[]


=== exampleUsage_4

// tag::exampleusage_4[]

// end::exampleusage_4[]


=== exampleUsage_5

// tag::exampleusage_5[]

// end::exampleusage_5[]


=== exampleWrong_Usage

// tag::examplewrong_usage[]

// end::examplewrong_usage[]


=== has_execution_plan_issue

// tag::has_execution_plan_issue[]

// end::has_execution_plan_issue[]


=== has_get_referenced_issue

// tag::has_get_referenced_issue[]

// end::has_get_referenced_issue[]


=== has_history

// tag::has_history[]

// end::has_history[]


=== has_history_columns

// tag::has_history_columns[]

// end::has_history_columns[]


=== InheritanceType

// tag::inheritancetype[]

// end::inheritancetype[]


=== is_persistence

// tag::is_persistence[]

// end::is_persistence[]


=== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]

// end::is_persistence_check_duplicate_per_pk[]


=== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]

// end::is_persistence_check_for_empty_source[]


=== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]

// end::is_persistence_delete_changed[]


=== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]

// end::is_persistence_delete_missing[]


=== is_persistence_insert

// tag::is_persistence_insert[]

// end::is_persistence_insert[]


=== is_persistence_truncate

// tag::is_persistence_truncate[]

// end::is_persistence_truncate[]


=== is_persistence_update_changed

// tag::is_persistence_update_changed[]

// end::is_persistence_update_changed[]


=== is_repo_managed

// tag::is_repo_managed[]
0
// end::is_repo_managed[]


=== is_ssas

// tag::is_ssas[]
0
// end::is_ssas[]


=== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


=== MS_Description

// tag::ms_description[]

// end::ms_description[]


=== persistence_source_RepoObject_fullname

// tag::persistence_source_repoobject_fullname[]

// end::persistence_source_repoobject_fullname[]


=== persistence_source_RepoObject_fullname2

// tag::persistence_source_repoobject_fullname2[]

// end::persistence_source_repoobject_fullname2[]


=== persistence_source_RepoObject_guid

// tag::persistence_source_repoobject_guid[]

// end::persistence_source_repoobject_guid[]


=== persistence_source_RepoObject_xref

// tag::persistence_source_repoobject_xref[]

// end::persistence_source_repoobject_xref[]


=== pk_index_guid

// tag::pk_index_guid[]

// end::pk_index_guid[]


=== pk_IndexPatternColumnDatatype

// tag::pk_indexpatterncolumndatatype[]

// end::pk_indexpatterncolumndatatype[]


=== pk_IndexPatternColumnName

// tag::pk_indexpatterncolumnname[]

// end::pk_indexpatterncolumnname[]


=== pk_IndexSemanticGroup

// tag::pk_indexsemanticgroup[]

// end::pk_indexsemanticgroup[]


=== ReferencedObjectList

// tag::referencedobjectlist[]
* [repo].[RepoObjectColumn_gross2]
// end::referencedobjectlist[]


=== usp_persistence_RepoObject_guid

// tag::usp_persistence_repoobject_guid[]

// end::usp_persistence_repoobject_guid[]


=== UspExamples

// tag::uspexamples[]

// end::uspexamples[]


=== UspParameters

// tag::uspparameters[]

// end::uspparameters[]

== Boolean Attributes

source: property.RepoObjectProperty WHERE property_int = 1

// tag::boolean_attributes[]

// end::boolean_attributes[]

== sql_modules_definition

// tag::sql_modules_definition[]
[%collapsible]
=======
[source,sql]
----


CREATE View [repo].[RepoObject_ColumnList]
As
Select
    roc.RepoObject_guid
  , CreateColumnList             =
  --
  String_Agg (
                 Concat (
                            --we need to convert to first argument nvarchar(max) to avoid the limit of 8000 byte
                            Cast('' As NVarchar(Max))
                          , QuoteName ( roc.RepoObjectColumn_name )
                          , ' '
                          , Case roc.Repo_is_computed
                                When 1
                                    Then
                                    Concat (   'AS '
                                             , roc.Repo_definition
                                             , Case
                                                   When roc.Repo_is_persisted = 1
                                                       Then
                                                       ' PERSISTED'
                                               End
                                           )
                                Else
                                    Concat (
                                               roc.Repo_user_type_fullname
                                             --CONSTRAINT
                                             --DEFAULT
                                             , Case
                                                   When roc.Repo_default_name <> ''
                                                        And IsNull ( roc.Repo_default_is_system_named, 0 ) = 0
                                                       Then
                                                       Concat ( ' CONSTRAINT ', roc.Repo_default_name )
                                               End
                                             --
                                             , Case
                                                   When roc.Repo_default_definition <> ''
                                                       Then
                                                       Concat ( ' DEFAULT ', roc.Repo_default_definition )
                                               End
                                             --temporal table columns
                                             , Case roc.Repo_generated_always_type
                                                   When 1
                                                       Then
                                                       ' GENERATED ALWAYS AS ROW START'
                                                   When 2
                                                       Then
                                                       ' GENERATED ALWAYS AS ROW END'
                                               End
                                             --IDENTITY
                                             --, CASE roc.Repo_is_identity
                                             -- WHEN 1
                                             --  THEN ' IDENTITY ' + CASE 
                                             --    WHEN NOT roc.[Repo_seed_value] IS NULL
                                             --     AND NOT roc.[Repo_increment_value] IS NULL
                                             --     THEN CONCAT (
                                             --       '('
                                             --       , CAST(roc.[Repo_seed_value] AS NVARCHAR(max))
                                             --       , ', '
                                             --       , CAST(roc.[Repo_increment_value] AS NVARCHAR(max))
                                             --       , ')'
                                             --       )
                                             --    END
                                             -- END
                                             , Case roc.Repo_is_identity
                                                   When 1
                                                       Then
                                                       Concat (
                                                                  ' IDENTITY ('
                                                                , IsNull (
                                                                             Cast(roc.Repo_seed_value As NVarchar(Max))
                                                                           , '1'
                                                                         )
                                                                , ', '
                                                                , IsNull (
                                                                             Cast(roc.Repo_increment_value As NVarchar(Max))
                                                                           , '1'
                                                                         )
                                                                , ')'
                                                              )
                                               End
                                             , Case
                                                   When roc.Repo_is_nullable = 0
                                                        Or roc.Repo_generated_always_type >= 1
                                                       Then
                                                       ' NOT'
                                               End
                                             , ' NULL '
                                           )
                            End
                          , Char ( 13 )
                          , Char ( 10 )
                        )
               , ', '
             ) Within Group(Order By
                                roc.RepoObjectColumn_column_id)
  , DbmlColumnList               =
  --
  String_Agg (
                 Concat (
                            --we need to convert to first argument nvarchar(max) to avoid the limit of 8000 byte
                            Cast('' As NVarchar(Max))
                          , QuoteName ( roc.RepoObjectColumn_name, '"' )
                          , ' '
                          , roc.Repo_user_type_fullname
                          , ' '
                          , '['
                          --null or not null
                          , Case
                                When roc.Repo_is_nullable = 0
                                     Or roc.Repo_generated_always_type >= 1
                                    Then
                                    'not'
                            End
                          , ' null'
                          --primary key or pk
                          , Case
                                When roc.is_index_primary_key = 1
                                    Then
                                    ', pk'
                            End
                          --unique
                          --default: some_value
                          --Attention: 
                          --number value starts blank: default: 123 or default: 123.456
                          --string value starts with single quotes: default: 'some string value'
                          --expression value is wrapped with parenthesis: default: `now() - interval '5 days'`
                          --boolean (true/false/null): default: false or default: null
                          --
                          , Case
                                When roc.Repo_default_definition <> ''
                                    Then
                                    Concat ( ', default: ', QuoteName ( roc.Repo_default_definition, '`' ))
                            End
                          --increment
                          , Case roc.Repo_is_identity
                                When 1
                                    Then
                                    ', increment'
                            End
                          --note: 'string to add notes'
                          , Case
                                When Not roc.Description Is Null
                                    Then
                                    ', Note: ''''''' + Char ( 13 ) + Char ( 10 )
                                    + Replace ( Replace ( roc.Description, '\', '\\' ), '''''''', '\''''''' )
                                    + Char ( 13 ) + Char ( 10 ) + ''''''''
                            End
                          , ']'
                        )
               , Char ( 13 ) + Char ( 10 )
             ) Within Group(Order By
                                roc.RepoObjectColumn_column_id)
  , PersistenceCompareColumnList =
  --
  Stuff (
            String_Agg (
                           Concat (
                                      --we need to convert to first argument nvarchar(max) to avoid the limit of 8000 byte
                                      Cast('' As NVarchar(Max))
                                    , ''
                                    , Case
                                          When
                                    --source should exists
                                    Not roc.persistence_source_RepoObjectColumn_guid Is Null
                                    And IsNull ( roc.is_persistence_no_include, 0 ) = 0
                                    And IsNull ( roc.is_persistence_no_check, 0 ) = 0
                                    And IsNull ( roc.is_query_plan_expression, 0 ) = 0
                                    And roc.Repo_generated_always_type = 0
                                    And roc.Repo_is_computed = 0
                                    And roc.Repo_is_identity = 0
                                    --do not compare PK
                                    --issue: if the source column is marked as PK but the target column is not marked as PK, then this column is included
                                    --to avoid this we would need to analyze also the source column properties
                                    --or we could set [is_persistence_no_check] = 1
                                    And roc.is_index_primary_key Is Null
                                              Then
                                              Concat (
                                                         'OR T.'
                                                       , QuoteName ( roc.RepoObjectColumn_name )
                                                       , ' <> S.'
                                                       , QuoteName ( roc.RepoObjectColumn_name )
                                                       , Case
                                                             When roc.Repo_is_nullable = 1
                                                                 Then
                                                                 Concat (
                                                                            ' OR (S.'
                                                                          , QuoteName ( roc.RepoObjectColumn_name )
                                                                          , ' IS NULL AND NOT T.'
                                                                          , QuoteName ( roc.RepoObjectColumn_name )
                                                                          , ' IS NULL)'
                                                                          , ' OR (NOT S.'
                                                                          , QuoteName ( roc.RepoObjectColumn_name )
                                                                          , ' IS NULL AND T.'
                                                                          , QuoteName ( roc.RepoObjectColumn_name )
                                                                          , ' IS NULL)'
                                                                        )
                                                         End
                                                       , Char ( 13 )
                                                       , Char ( 10 )
                                                     )
                                      End
                                  )
                         , ''
                       ) Within Group(Order By
                                          roc.RepoObjectColumn_column_id)
          , 1
          , 3
          , '   '
        )
  , PersistenceInsertColumnList  =
  --
  Stuff (
            String_Agg (
                           Concat (
                                      --we need to convert to first argument nvarchar(max) to avoid the limit of 8000 byte
                                      Cast('' As NVarchar(Max))
                                    , ''
                                    , Case
                                          When
                                    --source should exists
                                    Not roc.persistence_source_RepoObjectColumn_guid Is Null
                                    And IsNull ( roc.is_persistence_no_include, 0 ) = 0
                                    And IsNull ( roc.is_query_plan_expression, 0 ) = 0
                                    And roc.Repo_generated_always_type = 0
                                    And roc.Repo_is_computed = 0
                                    And roc.Repo_is_identity = 0
                                              Then
                                              Concat (
                                                         ', '
                                                       , QuoteName ( roc.RepoObjectColumn_name )
                                                       , Char ( 13 )
                                                       , Char ( 10 )
                                                     )
                                      End
                                  )
                         , ''
                       ) Within Group(Order By
                                          roc.RepoObjectColumn_column_id)
          , 1
          , 2
          , '  '
        )
  , PersistenceUpdateColumnList  =
  --
  Stuff (
            String_Agg (
                           Concat (
                                      --we need to convert to first argument nvarchar(max) to avoid the limit of 8000 byte
                                      Cast('' As NVarchar(Max))
                                    , ''
                                    , Case
                                          When
                                    --source should exists
                                    Not roc.persistence_source_RepoObjectColumn_guid Is Null
                                    And IsNull ( roc.is_persistence_no_include, 0 ) = 0
                                    And IsNull ( roc.is_persistence_no_check, 0 ) = 0
                                    And IsNull ( roc.is_query_plan_expression, 0 ) = 0
                                    And roc.Repo_generated_always_type = 0
                                    And roc.Repo_is_computed = 0
                                    And roc.Repo_is_identity = 0
                                              Then
                                              Concat (
                                                         ', T.'
                                                       , QuoteName ( roc.RepoObjectColumn_name )
                                                       , ' = S.'
                                                       , QuoteName ( roc.RepoObjectColumn_name )
                                                       , Char ( 13 )
                                                       , Char ( 10 )
                                                     )
                                      End
                                  )
                         , ''
                       ) Within Group(Order By
                                          roc.RepoObjectColumn_column_id)
          , 1
          , 2
          , '  '
        )
  , RepoObjectColumn_fullname    = Max ( roc.RepoObjectColumn_fullname )
From
    repo.RepoObjectColumn_gross2 As roc
Where
    --not [is_query_plan_expression], these are not real columms
    roc.is_query_plan_expression Is Null
    --we need the datatype, or it should be computed
    And
    (
        Not roc.Repo_user_type_fullname Is Null
        Or roc.Repo_is_computed = 1
    )
Group By
    roc.RepoObject_guid

----
=======
// end::sql_modules_definition[]


