// tag::HeaderFullDisplayName[]
= repo_sys.drop_all_extendedproperty_sql
// end::HeaderFullDisplayName[]

== existing_properties

// tag::existing_properties[]
:ExistsProperty--description:
:ExistsProperty--is_repo_managed:
:ExistsProperty--is_ssas:
:ExistsProperty--sql_modules_definition:
:ExistsProperty--FK:
:ExistsProperty--Columns:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
853EFD10-0222-EC11-8524-A81E8446D5B0
// end::RepoObject_guid[]

== RepoObject_FullDisplayName2

// tag::RepoObject_FullDisplayName2[]
repo_sys.drop_all_extendedproperty_sql
// end::RepoObject_FullDisplayName2[]

== SysObject_type

// tag::SysObject_type[]
V 
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
view
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
729105688
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2021-10-02 13:05:34
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]
[discrete]
== _


[#column-tsql]
=== Tsql

[cols="d,8m,m,m,m,d"]
|===
|
|Tsql
|nvarchar(4000)
|NULL
|
|
|===


// end::AntoraColumnDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]

// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]
|
|<<column-tsql>>
|nvarchar(4000)
|NULL
|
|

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

// end::AntoraIndexList[]

== AntoraMeasureDetails

// tag::AntoraMeasureDetails[]

// end::AntoraMeasureDetails[]

== AntoraParameterList

// tag::AntoraParameterList[]

// end::AntoraParameterList[]

== AntoraXrefCulturesList

// tag::AntoraXrefCulturesList[]
* xref:dhw:sqldb:repo_sys.drop_all_extendedproperty_sql.adoc[] - 
// end::AntoraXrefCulturesList[]

== cultures_count

// tag::cultures_count[]
1
// end::cultures_count[]

== Other tags

source: property.RepoObjectProperty_cross As rop_cross


=== additional_reference_csv

// tag::additional_reference_csv[]

// end::additional_reference_csv[]


=== AdocUspSteps

// tag::adocuspsteps[]

// end::adocuspsteps[]


=== AntoraReferencedList

// tag::antorareferencedlist[]

// end::antorareferencedlist[]


=== AntoraReferencingList

// tag::antorareferencinglist[]

// end::antorareferencinglist[]


=== Description

// tag::description[]

This view generates tsql to drop all extended properties

based on https://stackoverflow.com/questions/12368448/drop-all-extended-properties-on-sql-server/17853448[]

orignal description of the script:

This script will generate calls to sp_dropextendedproperty for every extended property that exists in your database.

Actually, a caveat: I don't promise that it will catch each and every extended property that exists, but I'm confident it will catch most of them!

It is based on this: +
http://blog.hongens.nl/2010/02/25/drop-all-extended-properties-in-a-mssql-database/[] +
by Angelo Hongens.

Also had lots of help from this: +
http://www.sqlservercentral.com/articles/Metadata/72609/[] +
by Adam Aspin

Adam actually provides a script at that link to do something very similar +
but when I ran it I got an error:

....
Msg 468, Level 16, State 9, Line 78
Cannot resolve the collation conflict between "Latin1_General_100_CS_AS" and "Latin1_General_CI_AS" in the equal to operation.
....

So I put together this version instead. 

Use at your own risk.

Jamie Thomson
2012-03-25
// end::description[]


=== ExampleUsage

// tag::exampleusage[]

// end::exampleusage[]


=== exampleUsage_2

// tag::exampleusage_2[]

// end::exampleusage_2[]


=== exampleUsage_3

// tag::exampleusage_3[]

// end::exampleusage_3[]


=== exampleUsage_4

// tag::exampleusage_4[]

// end::exampleusage_4[]


=== exampleUsage_5

// tag::exampleusage_5[]

// end::exampleusage_5[]


=== exampleWrong_Usage

// tag::examplewrong_usage[]

// end::examplewrong_usage[]


=== has_execution_plan_issue

// tag::has_execution_plan_issue[]

// end::has_execution_plan_issue[]


=== has_get_referenced_issue

// tag::has_get_referenced_issue[]

// end::has_get_referenced_issue[]


=== has_history

// tag::has_history[]

// end::has_history[]


=== has_history_columns

// tag::has_history_columns[]

// end::has_history_columns[]


=== InheritanceType

// tag::inheritancetype[]

// end::inheritancetype[]


=== is_persistence

// tag::is_persistence[]

// end::is_persistence[]


=== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]

// end::is_persistence_check_duplicate_per_pk[]


=== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]

// end::is_persistence_check_for_empty_source[]


=== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]

// end::is_persistence_delete_changed[]


=== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]

// end::is_persistence_delete_missing[]


=== is_persistence_insert

// tag::is_persistence_insert[]

// end::is_persistence_insert[]


=== is_persistence_truncate

// tag::is_persistence_truncate[]

// end::is_persistence_truncate[]


=== is_persistence_update_changed

// tag::is_persistence_update_changed[]

// end::is_persistence_update_changed[]


=== is_repo_managed

// tag::is_repo_managed[]
0
// end::is_repo_managed[]


=== is_ssas

// tag::is_ssas[]
0
// end::is_ssas[]


=== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


=== MS_Description

// tag::ms_description[]

// end::ms_description[]


=== persistence_source_RepoObject_fullname

// tag::persistence_source_repoobject_fullname[]

// end::persistence_source_repoobject_fullname[]


=== persistence_source_RepoObject_fullname2

// tag::persistence_source_repoobject_fullname2[]

// end::persistence_source_repoobject_fullname2[]


=== persistence_source_RepoObject_guid

// tag::persistence_source_repoobject_guid[]

// end::persistence_source_repoobject_guid[]


=== persistence_source_RepoObject_xref

// tag::persistence_source_repoobject_xref[]

// end::persistence_source_repoobject_xref[]


=== pk_index_guid

// tag::pk_index_guid[]

// end::pk_index_guid[]


=== pk_IndexPatternColumnDatatype

// tag::pk_indexpatterncolumndatatype[]

// end::pk_indexpatterncolumndatatype[]


=== pk_IndexPatternColumnName

// tag::pk_indexpatterncolumnname[]

// end::pk_indexpatterncolumnname[]


=== pk_IndexSemanticGroup

// tag::pk_indexsemanticgroup[]

// end::pk_indexsemanticgroup[]


=== ReferencedObjectList

// tag::referencedobjectlist[]

// end::referencedobjectlist[]


=== usp_persistence_RepoObject_guid

// tag::usp_persistence_repoobject_guid[]

// end::usp_persistence_repoobject_guid[]


=== UspExamples

// tag::uspexamples[]

// end::uspexamples[]


=== uspgenerator_usp_id

// tag::uspgenerator_usp_id[]

// end::uspgenerator_usp_id[]


=== UspParameters

// tag::uspparameters[]

// end::uspparameters[]

== Boolean Attributes

source: property.RepoObjectProperty WHERE property_int = 1

// tag::boolean_attributes[]

// end::boolean_attributes[]

== sql_modules_definition

// tag::sql_modules_definition[]
[%collapsible]
=======
[source,sql,numbered]
----


/*
<<property_start>>Description
This view generates tsql to drop all extended properties

based on https://stackoverflow.com/questions/12368448/drop-all-extended-properties-on-sql-server/17853448[]

orignal description of the script:

This script will generate calls to sp_dropextendedproperty for every extended property that exists in your database.

Actually, a caveat: I don't promise that it will catch each and every extended property that exists, but I'm confident it will catch most of them!

It is based on this: +
http://blog.hongens.nl/2010/02/25/drop-all-extended-properties-in-a-mssql-database/[] +
by Angelo Hongens.

Also had lots of help from this: +
http://www.sqlservercentral.com/articles/Metadata/72609/[] +
by Adam Aspin

Adam actually provides a script at that link to do something very similar +
but when I ran it I got an error:

....
Msg 468, Level 16, State 9, Line 78
Cannot resolve the collation conflict between "Latin1_General_100_CS_AS" and "Latin1_General_CI_AS" in the equal to operation.
....

So I put together this version instead. 

Use at your own risk.

Jamie Thomson
2012-03-25
<<property_end>>
<<property_start>>exampleUsage
--check existing ep
Select
    xp.class
  , xp.class_desc
  , xp.major_id
  , xp.minor_id
  , xp.name
  , xp.value
  , Object_Name ( xp.major_id )
From
    sys.extended_properties As xp

--create tsqp to drop them
Select
    Tsql
From
    repo_sys.drop_all_extendedproperty_sql<<property_end>>

*/
CREATE View [repo_sys].[drop_all_extendedproperty_sql]
As
Select
    Tsql = 'EXEC repo_sys.usp_DropExtendedProperty_in_self
@name = ''' + xp.name + '''
,@level0type = ''schema''
,@level0name = ''' + Object_Schema_Name ( xp.major_id ) + '''
,@level1type = ''table''
,@level1name = ''' + Object_Name ( xp.major_id ) + ''''
From
    sys.extended_properties As xp
    Join
        sys.tables          As t
            On
            xp.major_id = t.object_id
Where
    xp.class_desc   = 'OBJECT_OR_COLUMN'
    And xp.minor_id = 0
Union
--columns
Select
    'EXEC repo_sys.usp_DropExtendedProperty_in_self
@name = ''' + sys.extended_properties.name + '''
,@level0type = ''schema''
,@level0name = ''' + Object_Schema_Name ( extended_properties.major_id ) + '''
,@level1type = ''' + Case so.type
                         When 'u'
                             Then
                             'table'
                         When 'v'
                             Then
                             'view'
                     End + '''
,@level1name = ''' + Object_Name ( extended_properties.major_id ) + '''
,@level2type = ''column''
,@level2name = ''' + columns.name + ''''
From
    sys.extended_properties
    Join
        sys.columns
            On
            columns.object_id     = extended_properties.major_id
            And columns.column_id = extended_properties.minor_id

    Join
        sys.objects As so
            On
            columns.object_id     = so.object_id
Where
    extended_properties.class_desc   = 'OBJECT_OR_COLUMN'
    And extended_properties.minor_id > 0
    And so.type In
        ( 'u', 'v' )
Union
--check constraints
Select
    'EXEC repo_sys.usp_DropExtendedProperty_in_self
@name = ''' + xp.name + '''
,@level0type = ''schema''
,@level0name = ''' + Object_Schema_Name ( xp.major_id ) + '''
,@level1type = ''table''
,@level1name = ''' + Object_Name ( cc.parent_object_id ) + '''
,@level2type = ''constraint''
,@level2name = ''' + cc.name + ''''
From
    sys.extended_properties   As xp
    Join
        sys.check_constraints As cc
            On
            xp.major_id = cc.object_id
Union
--check constraints
Select
    'EXEC repo_sys.usp_DropExtendedProperty_in_self
@name = ''' + xp.name + '''
,@level0type = ''schema''
,@level0name = ''' + Object_Schema_Name ( xp.major_id ) + '''
,@level1type = ''table''
,@level1name = ''' + Object_Name ( cc.parent_object_id ) + '''
,@level2type = ''constraint''
,@level2name = ''' + cc.name + ''''
From
    sys.extended_properties     As xp
    Join
        sys.default_constraints As cc
            On
            xp.major_id = cc.object_id
Union
--views
Select
    'EXEC repo_sys.usp_DropExtendedProperty_in_self
@name = ''' + xp.name + '''
,@level0type = ''schema''
,@level0name = ''' + Object_Schema_Name ( xp.major_id ) + '''
,@level1type = ''view''
,@level1name = ''' + Object_Name ( xp.major_id ) + ''''
From
    sys.extended_properties As xp
    Join
        sys.views           As t
            On
            xp.major_id = t.object_id
Where
    xp.class_desc   = 'OBJECT_OR_COLUMN'
    And xp.minor_id = 0
Union
--sprocs
Select
    'EXEC repo_sys.usp_DropExtendedProperty_in_self
@name = ''' + xp.name + '''
,@level0type = ''schema''
,@level0name = ''' + Object_Schema_Name ( xp.major_id ) + '''
,@level1type = ''procedure''
,@level1name = ''' + Object_Name ( xp.major_id ) + ''''
From
    sys.extended_properties As xp
    Join
        sys.procedures      As t
            On
            xp.major_id = t.object_id
Where
    xp.class_desc   = 'OBJECT_OR_COLUMN'
    And xp.minor_id = 0
Union
--FKs
Select
    'EXEC repo_sys.usp_DropExtendedProperty_in_self
@name = ''' + xp.name + '''
,@level0type = ''schema''
,@level0name = ''' + Object_Schema_Name ( xp.major_id ) + '''
,@level1type = ''table''
,@level1name = ''' + Object_Name ( cc.parent_object_id ) + '''
,@level2type = ''constraint''
,@level2name = ''' + cc.name + ''''
From
    sys.extended_properties As xp
    Join
        sys.foreign_keys    As cc
            On
            xp.major_id = cc.object_id
Union
--PKs
Select
    'EXEC repo_sys.usp_DropExtendedProperty_in_self @level0type = N''SCHEMA'', @level0name = [' + SCH.name
    + '], @level1type = ''TABLE'', @level1name = [' + TBL.name + '] , @level2type = ''CONSTRAINT'', @level2name = ['
    + SKC.name + '] ,@name = ''' + Replace ( Cast(SEP.name As NVarchar(300)), '''', '''''' ) + ''''
From
    sys.tables      As TBL
    Inner Join
        sys.schemas As SCH
            On
            TBL.schema_id = SCH.schema_id

    Inner Join
        sys.extended_properties As SEP
        Inner Join
            sys.key_constraints As SKC
                On
                SEP.major_id = SKC.object_id
            On
            TBL.object_id = SKC.parent_object_id
Where
    SKC.type_desc = N'PRIMARY_KEY_CONSTRAINT'
Union
--Table triggers
Select
    'EXEC repo_sys.usp_DropExtendedProperty_in_self @level0type = N''SCHEMA'', @level0name = [' + SCH.name
    + '], @level1type = ''TABLE'', @level1name = [' + TBL.name + '] , @level2type = ''TRIGGER'', @level2name = ['
    + TRG.name + '] ,@name = ''' + Replace ( Cast(SEP.name As NVarchar(300)), '''', '''''' ) + ''''
From
    sys.tables                  As TBL
    Inner Join
        sys.triggers            As TRG
            On
            TBL.object_id = TRG.parent_id

    Inner Join
        sys.extended_properties As SEP
            On
            TRG.object_id = SEP.major_id

    Inner Join
        sys.schemas             As SCH
            On
            TBL.schema_id = SCH.schema_id
Union
--UDF params
Select
    'EXEC repo_sys.usp_DropExtendedProperty_in_self @level0type = N''SCHEMA'', @level0name = [' + SCH.name
    + '], @level1type = ''FUNCTION'', @level1name = [' + OBJ.name + '] , @level2type = ''PARAMETER'', @level2name = ['
    + PRM.name + '] ,@name = ''' + Replace ( Cast(SEP.name As NVarchar(300)), '''', '''''' ) + ''''
From
    sys.extended_properties As SEP
    Inner Join
        sys.objects         As OBJ
            On
            SEP.major_id     = OBJ.object_id

    Inner Join
        sys.schemas         As SCH
            On
            OBJ.schema_id    = SCH.schema_id

    Inner Join
        sys.parameters      As PRM
            On
            SEP.major_id     = PRM.object_id
            And SEP.minor_id = PRM.parameter_id
Where
    SEP.class_desc = N'PARAMETER'
    And OBJ.type In
        ( 'FN', 'IF', 'TF' )
Union
--sp params
Select
    'EXEC repo_sys.usp_DropExtendedProperty_in_self @level0type = N''SCHEMA'', @level0name = [' + SCH.name
    + '], @level1type = ''PROCEDURE'', @level1name = [' + SPR.name + '] , @level2type = ''PARAMETER'', @level2name = ['
    + PRM.name + '] ,@name = ''' + Replace ( Cast(SEP.name As NVarchar(300)), '''', '''''' ) + ''''
From
    sys.extended_properties As SEP
    Inner Join
        sys.procedures      As SPR
            On
            SEP.major_id     = SPR.object_id

    Inner Join
        sys.schemas         As SCH
            On
            SPR.schema_id    = SCH.schema_id

    Inner Join
        sys.parameters      As PRM
            On
            SEP.major_id     = PRM.object_id
            And SEP.minor_id = PRM.parameter_id
Where
    SEP.class_desc = N'PARAMETER'
Union
--DB
Select
    'EXEC repo_sys.usp_DropExtendedProperty_in_self @name = '''
    + Replace ( Cast(SEP.name As NVarchar(300)), '''', '''''' ) + ''''
From
    sys.extended_properties As SEP
Where
    SEP.class_desc = N'DATABASE'
Union
--schema
Select
    'EXEC repo_sys.usp_DropExtendedProperty_in_self @level0type = N''SCHEMA'', @level0name = [' + SCH.name
    + '] ,@name = ''' + Replace ( Cast(SEP.name As NVarchar(300)), '''', '''''' ) + ''''
From
    sys.extended_properties As SEP
    Inner Join
        sys.schemas         As SCH
            On
            SEP.major_id = SCH.schema_id
Where
    SEP.class_desc = N'SCHEMA'
Union
--DATABASE_FILE
Select
    'EXEC repo_sys.usp_DropExtendedProperty_in_self @level0type = N''FILEGROUP'', @level0name = [' + DSP.name
    + '], @level1type = ''LOGICAL FILE NAME'', @level1name = ' + DBF.name + ' ,@name = '''
    + Replace ( Cast(SEP.name As NVarchar(300)), '''', '''''' ) + ''''
From
    sys.extended_properties As SEP
    Inner Join
        sys.database_files  As DBF
            On
            SEP.major_id      = DBF.file_id

    Inner Join
        sys.data_spaces     As DSP
            On
            DBF.data_space_id = DSP.data_space_id
Where
    SEP.class_desc = N'DATABASE_FILE'
Union
--filegroup
Select
    'EXEC repo_sys.usp_DropExtendedProperty_in_self @level0type = N''FILEGROUP'', @level0name = [' + DSP.name
    + '] ,@name = ''' + Replace ( Cast(SEP.name As NVarchar(300)), '''', '''''' ) + ''''
From
    sys.extended_properties As SEP
    Inner Join
        sys.data_spaces     As DSP
            On
            SEP.major_id = DSP.data_space_id
Where
    DSP.type_desc = 'ROWS_FILEGROUP'
Union
-- INDEX
Select
    'EXEC repo_sys.usp_DropExtendedProperty_in_self
@name = ''' + sys.extended_properties.name + '''
,@level0type = ''schema''
,@level0name = ''' + Object_Schema_Name ( extended_properties.major_id )
    + '''
,@level1type = ''table''
,@level1name = ''' + Object_Name ( extended_properties.major_id ) + '''
,@level2type = ''index''
,@level2name = ''' + indexes.name + ''''
From
    sys.extended_properties
    Join
        sys.indexes
            On
            indexes.object_id    = extended_properties.major_id
            And indexes.index_id = extended_properties.minor_id
Where
    extended_properties.class_desc   = 'INDEX'
    And extended_properties.minor_id > 0

----
=======
// end::sql_modules_definition[]


