// tag::HeaderFullDisplayName[]
= ssis_t.TblControlFlow_src
// end::HeaderFullDisplayName[]

== existing_properties

// tag::existing_properties[]
:ExistsProperty--antorareferencedlist:
:ExistsProperty--antorareferencinglist:
:ExistsProperty--is_repo_managed:
:ExistsProperty--is_ssas:
:ExistsProperty--referencedobjectlist:
:ExistsProperty--sql_modules_definition:
:ExistsProperty--FK:
:ExistsProperty--Columns:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
7F64FBE4-113B-EC11-852C-A81E8446D5B0
// end::RepoObject_guid[]

== RepoObject_FullDisplayName2

// tag::RepoObject_FullDisplayName2[]
ssis_t.TblControlFlow_src
// end::RepoObject_FullDisplayName2[]

== SysObject_type

// tag::SysObject_type[]
V 
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
view
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
290152129
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2021-11-01 13:46:40
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]
[discrete]
== _


[#column-delayvalidationpropertyvalue]
=== DelayValidationPropertyValue

[cols="d,8m,m,m,m,d"]
|===
|
|DelayValidationPropertyValue
|nvarchar(max)
|NULL
|
|
|===


[#column-dftquery]
=== DFTQuery

[cols="d,8m,m,m,m,d"]
|===
|
|DFTQuery
|xml
|NULL
|
|
|===


[#column-execpkgtaskqry]
=== ExecPkgTaskQry

[cols="d,8m,m,m,m,d"]
|===
|
|ExecPkgTaskQry
|xml
|NULL
|
|
|===


[#column-expressionvalue]
=== ExpressionValue

[cols="d,8m,m,m,m,d"]
|===
|
|ExpressionValue
|nvarchar(max)
|NULL
|
|
|===


[#column-isdisabled]
=== IsDisabled

[cols="d,8m,m,m,m,d"]
|===
|
|IsDisabled
|nvarchar(max)
|NOT NULL
|
|
|===


[#column-rowid]
=== RowID

[cols="d,8m,m,m,m,d"]
|===
|
|RowID
|int
|NOT NULL
|
|
|===


[#column-scripttaskqry]
=== ScriptTaskQry

[cols="d,8m,m,m,m,d"]
|===
|
|ScriptTaskQry
|xml
|NULL
|
|
|===


[#column-sqltaskqry]
=== SqlTaskQry

[cols="d,8m,m,m,m,d"]
|===
|
|SqlTaskQry
|xml
|NULL
|
|
|===


[#column-taskdescription]
=== TaskDescription

[cols="d,8m,m,m,m,d"]
|===
|
|TaskDescription
|nvarchar(max)
|NULL
|
|
|===


[#column-taskname]
=== TaskName

[cols="d,8m,m,m,m,d"]
|===
|
|TaskName
|nvarchar(max)
|NULL
|
|
|===


[#column-taskpath]
=== TaskPath

[cols="d,8m,m,m,m,d"]
|===
|
|TaskPath
|varchar(max)
|NULL
|
|
|===


[#column-tasktype]
=== TaskType

[cols="d,8m,m,m,m,d"]
|===
|
|TaskType
|nvarchar(max)
|NULL
|
|
|===


// end::AntoraColumnDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]












// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]
|
|<<column-delayvalidationpropertyvalue>>
|nvarchar(max)
|NULL
|
|

|
|<<column-dftquery>>
|xml
|NULL
|
|

|
|<<column-execpkgtaskqry>>
|xml
|NULL
|
|

|
|<<column-expressionvalue>>
|nvarchar(max)
|NULL
|
|

|
|<<column-isdisabled>>
|nvarchar(max)
|NOT NULL
|
|

|
|<<column-rowid>>
|int
|NOT NULL
|
|

|
|<<column-scripttaskqry>>
|xml
|NULL
|
|

|
|<<column-sqltaskqry>>
|xml
|NULL
|
|

|
|<<column-taskdescription>>
|nvarchar(max)
|NULL
|
|

|
|<<column-taskname>>
|nvarchar(max)
|NULL
|
|

|
|<<column-taskpath>>
|varchar(max)
|NULL
|
|

|
|<<column-tasktype>>
|nvarchar(max)
|NULL
|
|

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

// end::AntoraIndexList[]

== AntoraMeasureDetails

// tag::AntoraMeasureDetails[]

// end::AntoraMeasureDetails[]

== AntoraParameterList

// tag::AntoraParameterList[]

// end::AntoraParameterList[]

== AntoraXrefCulturesList

// tag::AntoraXrefCulturesList[]
* xref:dhw:sqldb:ssis_t.tblcontrolflow_src.adoc[] - 
// end::AntoraXrefCulturesList[]

== cultures_count

// tag::cultures_count[]
1
// end::cultures_count[]

== Other tags

source: property.RepoObjectProperty_cross As rop_cross


=== additional_reference_csv

// tag::additional_reference_csv[]

// end::additional_reference_csv[]


=== AdocUspSteps

// tag::adocuspsteps[]

// end::adocuspsteps[]


=== AntoraReferencedList

// tag::antorareferencedlist[]
* xref:ssis_t.pkgstats.adoc[]
// end::antorareferencedlist[]


=== AntoraReferencingList

// tag::antorareferencinglist[]
* xref:ssis_t.usp_getpackagedetails.adoc[]
// end::antorareferencinglist[]


=== Description

// tag::description[]

// end::description[]


=== ExampleUsage

// tag::exampleusage[]

// end::exampleusage[]


=== exampleUsage_2

// tag::exampleusage_2[]

// end::exampleusage_2[]


=== exampleUsage_3

// tag::exampleusage_3[]

// end::exampleusage_3[]


=== exampleUsage_4

// tag::exampleusage_4[]

// end::exampleusage_4[]


=== exampleUsage_5

// tag::exampleusage_5[]

// end::exampleusage_5[]


=== exampleWrong_Usage

// tag::examplewrong_usage[]

// end::examplewrong_usage[]


=== has_execution_plan_issue

// tag::has_execution_plan_issue[]

// end::has_execution_plan_issue[]


=== has_get_referenced_issue

// tag::has_get_referenced_issue[]

// end::has_get_referenced_issue[]


=== has_history

// tag::has_history[]

// end::has_history[]


=== has_history_columns

// tag::has_history_columns[]

// end::has_history_columns[]


=== InheritanceType

// tag::inheritancetype[]

// end::inheritancetype[]


=== is_persistence

// tag::is_persistence[]

// end::is_persistence[]


=== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]

// end::is_persistence_check_duplicate_per_pk[]


=== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]

// end::is_persistence_check_for_empty_source[]


=== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]

// end::is_persistence_delete_changed[]


=== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]

// end::is_persistence_delete_missing[]


=== is_persistence_insert

// tag::is_persistence_insert[]

// end::is_persistence_insert[]


=== is_persistence_truncate

// tag::is_persistence_truncate[]

// end::is_persistence_truncate[]


=== is_persistence_update_changed

// tag::is_persistence_update_changed[]

// end::is_persistence_update_changed[]


=== is_repo_managed

// tag::is_repo_managed[]
0
// end::is_repo_managed[]


=== is_ssas

// tag::is_ssas[]
0
// end::is_ssas[]


=== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


=== MS_Description

// tag::ms_description[]

// end::ms_description[]


=== persistence_source_RepoObject_fullname

// tag::persistence_source_repoobject_fullname[]

// end::persistence_source_repoobject_fullname[]


=== persistence_source_RepoObject_fullname2

// tag::persistence_source_repoobject_fullname2[]

// end::persistence_source_repoobject_fullname2[]


=== persistence_source_RepoObject_guid

// tag::persistence_source_repoobject_guid[]

// end::persistence_source_repoobject_guid[]


=== persistence_source_RepoObject_xref

// tag::persistence_source_repoobject_xref[]

// end::persistence_source_repoobject_xref[]


=== pk_index_guid

// tag::pk_index_guid[]

// end::pk_index_guid[]


=== pk_IndexPatternColumnDatatype

// tag::pk_indexpatterncolumndatatype[]

// end::pk_indexpatterncolumndatatype[]


=== pk_IndexPatternColumnName

// tag::pk_indexpatterncolumnname[]

// end::pk_indexpatterncolumnname[]


=== pk_IndexSemanticGroup

// tag::pk_indexsemanticgroup[]

// end::pk_indexsemanticgroup[]


=== ReferencedObjectList

// tag::referencedobjectlist[]
* [ssis_t].[pkgStats]
// end::referencedobjectlist[]


=== usp_persistence_RepoObject_guid

// tag::usp_persistence_repoobject_guid[]

// end::usp_persistence_repoobject_guid[]


=== UspExamples

// tag::uspexamples[]

// end::uspexamples[]


=== uspgenerator_usp_id

// tag::uspgenerator_usp_id[]

// end::uspgenerator_usp_id[]


=== UspParameters

// tag::uspparameters[]

// end::uspparameters[]

== Boolean Attributes

source: property.RepoObjectProperty WHERE property_int = 1

// tag::boolean_attributes[]

// end::boolean_attributes[]

== sql_modules_definition

// tag::sql_modules_definition[]
[%collapsible]
=======
[source,sql,numbered]
----

CREATE VIEW [ssis_t].[TblControlFlow_src]
As
With
CTE_CFLevel
As
    (
    Select
        pkg.RowID
      --, DFTQuery                           = cfnodes.x.query ( '.' ).query ( 'declare namespace DTS="www.microsoft.com/SqlServer/Dts";
      --          ./DTS:Executable[@DTS:ExecutableType=''SSIS.Pipeline.3'']/DTS:ObjectData/pipeline/components/component' )

      ---- https://docs.microsoft.com/en-us/openspecs/sql_data_portability/ms-dtsx2/bdf1b5fe-d2e2-4fb9-892c-02c50b865e40
      , DFTQuery_1                   = cfnodes.x.query ( '.' ).query ( 'declare namespace DTS="www.microsoft.com/SqlServer/Dts";
                    ./DTS:Executable[@DTS:ExecutableType=''SSIS.Pipeline'']/DTS:ObjectData/pipeline/components/component' )
      , DFTQuery_2                   = cfnodes.x.query ( '.' ).query ( 'declare namespace DTS="www.microsoft.com/SqlServer/Dts";
                    ./DTS:Executable[@DTS:ExecutableType=''SSIS.Pipeline.3'']/DTS:ObjectData/pipeline/components/component' )
      , DFTQuery_3                   = cfnodes.x.query ( '.' ).query ( 'declare namespace DTS="www.microsoft.com/SqlServer/Dts";
                    ./DTS:Executable[@DTS:ExecutableType=''STOCK:SSIS.Pipeline'']/DTS:ObjectData/pipeline/components/component' )
      , DFTQuery_4                   = cfnodes.x.query ( '.' ).query ( 'declare namespace DTS="www.microsoft.com/SqlServer/Dts";
                    ./DTS:Executable[@DTS:ExecutableType=''Microsoft.Pipeline'']/DTS:ObjectData/pipeline/components/component' )
      , exist_DFTQuery_1             = cfnodes.x.query ( '.' ).exist ( 'declare namespace DTS="www.microsoft.com/SqlServer/Dts";
                    ./DTS:Executable[@DTS:ExecutableType=''SSIS.Pipeline'']/DTS:ObjectData/pipeline/components/component' )
      , exist_DFTQuery_2             = cfnodes.x.query ( '.' ).exist ( 'declare namespace DTS="www.microsoft.com/SqlServer/Dts";
                    ./DTS:Executable[@DTS:ExecutableType=''SSIS.Pipeline.3'']/DTS:ObjectData/pipeline/components/component' )
      , exist_DFTQuery_3             = cfnodes.x.query ( '.' ).exist ( 'declare namespace DTS="www.microsoft.com/SqlServer/Dts";
                    ./DTS:Executable[@DTS:ExecutableType=''STOCK:SSIS.Pipeline'']/DTS:ObjectData/pipeline/components/component' )
      , exist_DFTQuery_4             = cfnodes.x.query ( '.' ).exist ( 'declare namespace DTS="www.microsoft.com/SqlServer/Dts";
                    ./DTS:Executable[@DTS:ExecutableType=''Microsoft.Pipeline'']/DTS:ObjectData/pipeline/components/component' )
      , TaskPath                     = cfnodes.x.value (
                                                           'declare namespace p1="www.microsoft.com/SqlServer/Dts";./@p1:refId[1]'
                                                         , 'varchar(max)'
                                                       )
      , TaskName                     = cfnodes.x.value (
                                                           'declare namespace p1="www.microsoft.com/SqlServer/Dts";./@p1:ObjectName[1]'
                                                         , 'nvarchar(max)'
                                                       )
      , TaskDescription              = cfnodes.x.value (
                                                           'declare namespace p1="www.microsoft.com/SqlServer/Dts";./@p1:Description'
                                                         , 'nvarchar(max)'
                                                       )
      , TaskType                     = cfnodes.x.value (
                                                           'declare namespace p1="www.microsoft.com/SqlServer/Dts";./@p1:ExecutableType'
                                                         , 'nvarchar(max)'
                                                       )
      , DelayValidationPropertyValue = cfnodes.x.value (
                                                           'declare namespace p1="www.microsoft.com/SqlServer/Dts";./@p1:DelayValidation'
                                                         , 'nvarchar(max)'
                                                       )
      , IsDisabled                   = IsNull (
                                                  cfnodes.x.value (
                                                                      'declare namespace p1="www.microsoft.com/SqlServer/Dts";./@p1:Disabled'
                                                                    , 'nvarchar(max)'
                                                                  )
                                                , 'False'
                                              )
      , ForloopEvalExpression        = 'EvalExpression = '
                                       + cfnodes.x.value (
                                                             'declare namespace p1="www.microsoft.com/SqlServer/Dts";./@p1:EvalExpression'
                                                           , 'nvarchar(max)'
                                                         )
      --, SqlTaskQry                         = cfnodes.x.query ( '.' ).query ( 'declare namespace DTS="www.microsoft.com/SqlServer/Dts";
      --          ./DTS:Executable[@DTS:ExecutableType=''Microsoft.SqlServer.Dts.Tasks.ExecuteSQLTask.ExecuteSQLTask, Microsoft.SqlServer.SQLTask, Version=11.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91'']/DTS:ObjectData/*' )

      ---- https://docs.microsoft.com/en-us/openspecs/sql_data_portability/ms-dtsx2/80af8760-5b6d-4dfd-8a63-cf14bb090fbd
      , SqlTaskQry_1                 = cfnodes.x.query ( '.' ).query ( 'declare namespace DTS="www.microsoft.com/SqlServer/Dts";
                    ./DTS:Executable[@DTS:ExecutableType=''Microsoft.SqlServer.Dts.Tasks.ExecuteSQLTask.ExecuteSQLTask, Microsoft.SqlServer.SQLTask, Version=11.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91'']/DTS:ObjectData/*' )
      , SqlTaskQry_2                 = cfnodes.x.query ( '.' ).query ( 'declare namespace DTS="www.microsoft.com/SqlServer/Dts";
                    ./DTS:Executable[@DTS:ExecutableType=''STOCK:SQLTask'']/DTS:ObjectData/*' )
      , SqlTaskQry_3                 = cfnodes.x.query ( '.' ).query ( 'declare namespace DTS="www.microsoft.com/SqlServer/Dts";
                    ./DTS:Executable[@DTS:ExecutableType=''Microsoft.ExecuteSQLTask'']/DTS:ObjectData/*' )
      , exist_SqlTaskQry_1           = cfnodes.x.query ( '.' ).exist ( 'declare namespace DTS="www.microsoft.com/SqlServer/Dts";
                    ./DTS:Executable[@DTS:ExecutableType=''Microsoft.SqlServer.Dts.Tasks.ExecuteSQLTask.ExecuteSQLTask, Microsoft.SqlServer.SQLTask, Version=11.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91'']/DTS:ObjectData/*' )
      , exist_SqlTaskQry_2           = cfnodes.x.query ( '.' ).exist ( 'declare namespace DTS="www.microsoft.com/SqlServer/Dts";
                    ./DTS:Executable[@DTS:ExecutableType=''STOCK:SQLTask'']/DTS:ObjectData/*' )
      , exist_SqlTaskQry_3           = cfnodes.x.query ( '.' ).exist ( 'declare namespace DTS="www.microsoft.com/SqlServer/Dts";
                    ./DTS:Executable[@DTS:ExecutableType=''Microsoft.ExecuteSQLTask'']/DTS:ObjectData/*' )
      --
      --, ExecPkgTaskQry                     = cfnodes.x.query ( '.' ).query ( 'declare namespace DTS="www.microsoft.com/SqlServer/Dts";
      --              ./DTS:Executable[@DTS:ExecutableType=''SSIS.ExecutePackageTask.3'']/*' )

      ---- https://docs.microsoft.com/en-us/openspecs/sql_data_portability/ms-dtsx2/f71e8e17-aa69-4ce8-8fc6-d2e0fef99059
      , ExecPkgTaskQry_1             = cfnodes.x.query ( '.' ).query ( 'declare namespace DTS="www.microsoft.com/SqlServer/Dts";
                    ./DTS:Executable[@DTS:ExecutableType=''SSIS.ExecutePackageTask'']/*' )
      , ExecPkgTaskQry_2             = cfnodes.x.query ( '.' ).query ( 'declare namespace DTS="www.microsoft.com/SqlServer/Dts";
                    ./DTS:Executable[@DTS:ExecutableType=''SSIS.ExecutePackageTask.3'']/*' )
      , ExecPkgTaskQry_3             = cfnodes.x.query ( '.' ).query ( 'declare namespace DTS="www.microsoft.com/SqlServer/Dts";
                    ./DTS:Executable[@DTS:ExecutableType=''STOCK:ExecutePackageTask'']/*' )
      , ExecPkgTaskQry_4             = cfnodes.x.query ( '.' ).query ( 'declare namespace DTS="www.microsoft.com/SqlServer/Dts";
                    ./DTS:Executable[@DTS:ExecutableType=''Microsoft.ExecutePackageTask'']/*' )
      , exist_ExecPkgTaskQry_1       = cfnodes.x.query ( '.' ).exist ( 'declare namespace DTS="www.microsoft.com/SqlServer/Dts";
                    ./DTS:Executable[@DTS:ExecutableType=''SSIS.ExecutePackageTask'']/*' )
      , exist_ExecPkgTaskQry_2       = cfnodes.x.query ( '.' ).exist ( 'declare namespace DTS="www.microsoft.com/SqlServer/Dts";
                    ./DTS:Executable[@DTS:ExecutableType=''SSIS.ExecutePackageTask.3'']/*' )
      , exist_ExecPkgTaskQry_3       = cfnodes.x.query ( '.' ).exist ( 'declare namespace DTS="www.microsoft.com/SqlServer/Dts";
                    ./DTS:Executable[@DTS:ExecutableType=''STOCK:ExecutePackageTask'']/*' )
      , exist_ExecPkgTaskQry_4       = cfnodes.x.query ( '.' ).exist ( 'declare namespace DTS="www.microsoft.com/SqlServer/Dts";
                    ./DTS:Executable[@DTS:ExecutableType=''Microsoft.ExecutePackageTask'']/*' )

      ---- https://docs.microsoft.com/en-us/openspecs/sql_data_portability/ms-dtsx2/93ef6e19-9c22-4dd1-b6b1-ae7d9c43a490
      ---- error in documentation, the right value is 'Microsoft.ScriptTask' but not 'Microsoft:ScriptTask'
      , ScriptTaskQry_1              = cfnodes.x.query ( '.' ).query ( 'declare namespace DTS="www.microsoft.com/SqlServer/Dts";
                    ./DTS:Executable[@DTS:ExecutableType=''Microsoft.SqlServer.Dts.Tasks.ScriptTask.ScriptTask, Microsoft.SqlServer.ScriptTask, Version=11.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91'']/DTS:ObjectData/ScriptProject/*' )
      , ScriptTaskQry_2              = cfnodes.x.query ( '.' ).query ( 'declare namespace DTS="www.microsoft.com/SqlServer/Dts";
                    ./DTS:Executable[@DTS:ExecutableType=''STOCK:ScriptTask'']/DTS:ObjectData/ScriptProject/*' )
      , ScriptTaskQry_3              = cfnodes.x.query ( '.' ).query ( 'declare namespace DTS="www.microsoft.com/SqlServer/Dts";
                    ./DTS:Executable[@DTS:ExecutableType=''Microsoft.ScriptTask'']/DTS:ObjectData/ScriptProject/*' )
      , exist_ScriptTaskQry_1        = cfnodes.x.query ( '.' ).exist ( 'declare namespace DTS="www.microsoft.com/SqlServer/Dts";
                    ./DTS:Executable[@DTS:ExecutableType=''Microsoft.SqlServer.Dts.Tasks.ScriptTask.ScriptTask, Microsoft.SqlServer.ScriptTask, Version=11.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91'']/DTS:ObjectData/ScriptProject/*' )
      , exist_ScriptTaskQry_2        = cfnodes.x.query ( '.' ).exist ( 'declare namespace DTS="www.microsoft.com/SqlServer/Dts";
                    ./DTS:Executable[@DTS:ExecutableType=''STOCK:ScriptTask'']/DTS:ObjectData/ScriptProject/*' )
      , exist_ScriptTaskQry_3        = cfnodes.x.query ( '.' ).exist ( 'declare namespace DTS="www.microsoft.com/SqlServer/Dts";
                    ./DTS:Executable[@DTS:ExecutableType=''Microsoft.ScriptTask'']/DTS:ObjectData/ScriptProject/*' )
    From
        ssis_t.pkgStats                                                                                                                   As pkg
        Cross Apply pkg.PackageXML.nodes ( 'declare namespace DTS="www.microsoft.com/SqlServer/Dts";//DTS:Executable/DTS:Executables/*' ) As cfnodes(x)
    )
--Insert Into ssis.TblControlFlowDetails
--(
--    RowID
--  , TaskPath
--  , TaskName
--  , TaskTypeDescription
--  , TaskType
--  , DelayValidationPropertyValue
--  , DFTQuery
--  , SqlTaskQry
--  , ExecPkgTaskQry
--  , ScriptTaskQry
--  , IsDisabled
--  , ExpressionValue
--)
Select
    CTE_CFLevel.RowID
  , CTE_CFLevel.TaskPath
  , CTE_CFLevel.TaskName
  , CTE_CFLevel.TaskDescription
  , CTE_CFLevel.TaskType
  , CTE_CFLevel.DelayValidationPropertyValue
  --, CTE_CFLevel.DFTQuery
  , DFTQuery        = Case
                          When CTE_CFLevel.exist_DFTQuery_1 = 1
                              Then
                              CTE_CFLevel.DFTQuery_1
                          When CTE_CFLevel.exist_DFTQuery_2 = 1
                              Then
                              CTE_CFLevel.DFTQuery_2
                          When CTE_CFLevel.exist_DFTQuery_3 = 1
                              Then
                              CTE_CFLevel.DFTQuery_3
                          When CTE_CFLevel.exist_DFTQuery_4 = 1
                              Then
                              CTE_CFLevel.DFTQuery_4
                      End
  --, CTE_CFLevel.SqlTaskQry
  , SqlTaskQry      = Case
                          When CTE_CFLevel.exist_SqlTaskQry_1 = 1
                              Then
                              CTE_CFLevel.SqlTaskQry_1
                          When CTE_CFLevel.exist_SqlTaskQry_2 = 1
                              Then
                              CTE_CFLevel.SqlTaskQry_2
                          When CTE_CFLevel.exist_SqlTaskQry_3 = 1
                              Then
                              CTE_CFLevel.SqlTaskQry_3
                      End
  --, CTE_CFLevel.ExecPkgTaskQry
  , ExecPkgTaskQry  = Case
                          When CTE_CFLevel.exist_ExecPkgTaskQry_1 = 1
                              Then
                              CTE_CFLevel.ExecPkgTaskQry_1
                          When CTE_CFLevel.exist_ExecPkgTaskQry_2 = 1
                              Then
                              CTE_CFLevel.ExecPkgTaskQry_2
                          When CTE_CFLevel.exist_ExecPkgTaskQry_3 = 1
                              Then
                              CTE_CFLevel.ExecPkgTaskQry_3
                          When CTE_CFLevel.exist_ExecPkgTaskQry_4 = 1
                              Then
                              CTE_CFLevel.ExecPkgTaskQry_4
                      End
  --, CTE_CFLevel.ScriptTaskQry
  , ScriptTaskQry   = Case
                          When CTE_CFLevel.exist_ScriptTaskQry_1 = 1
                              Then
                              CTE_CFLevel.ScriptTaskQry_1
                          When CTE_CFLevel.exist_ScriptTaskQry_2 = 1
                              Then
                              CTE_CFLevel.ScriptTaskQry_2
                          When CTE_CFLevel.exist_ScriptTaskQry_3 = 1
                              Then
                              CTE_CFLevel.ScriptTaskQry_3
                      End
  , CTE_CFLevel.IsDisabled
  , ExpressionValue = CTE_CFLevel.ForloopEvalExpression
From
    CTE_CFLevel;
----
=======
// end::sql_modules_definition[]


