'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:logs.executionlog.adoc[]" as logs.ExecutionLog << U >> {
  --
  created_dt : (datetime)
  current_execution_guid : (uniqueidentifier)
  deleted : (int)
  event_info : (nvarchar(max))
  - execution_instance_guid : (uniqueidentifier)
  - id : (bigint)
  info_01 : (nvarchar(4000))
  info_02 : (nvarchar(4000))
  info_03 : (nvarchar(4000))
  info_04 : (nvarchar(4000))
  info_05 : (nvarchar(4000))
  info_06 : (nvarchar(4000))
  info_07 : (nvarchar(4000))
  info_08 : (nvarchar(4000))
  info_09 : (nvarchar(4000))
  inserted : (int)
  parameter_01 : (nvarchar(4000))
  parameter_02 : (nvarchar(4000))
  parameter_03 : (nvarchar(4000))
  parameter_04 : (nvarchar(4000))
  parameter_05 : (nvarchar(4000))
  parameter_06 : (nvarchar(4000))
  parameter_07 : (nvarchar(4000))
  parameter_08 : (nvarchar(4000))
  parameter_09 : (nvarchar(4000))
  parameter_10 : (nvarchar(4000))
  parameter_11 : (nvarchar(4000))
  parameter_12 : (nvarchar(4000))
  parameter_13 : (nvarchar(4000))
  parameter_14 : (nvarchar(4000))
  parameter_15 : (nvarchar(4000))
  parameter_16 : (nvarchar(4000))
  parameter_17 : (nvarchar(4000))
  parameter_18 : (nvarchar(4000))
  parameter_19 : (nvarchar(4000))
  parameter_20 : (nvarchar(4000))
  parent_execution_log_id : (bigint)
  proc_id : (int)
  proc_name : (nvarchar(128))
  proc_schema_name : (nvarchar(128))
  source_object : (nvarchar(261))
  ssis_execution_id : (bigint)
  step_id : (int)
  step_name : (nvarchar(1000))
  sub_execution_id : (int)
  target_object : (nvarchar(261))
  updated : (int)
  ~ proc_fullname : (nvarchar(517))
  --
}

