'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:logs.executionlog_parent.adoc[]" as logs.ExecutionLog_parent << V >> {
  --
  - id : (bigint)
  parent_created_dt : (datetime)
  parent_current_execution_guid : (uniqueidentifier)
  parent_execution_log_id : (bigint)
  parent_parameter_01 : (nvarchar(4000))
  parent_parameter_02 : (nvarchar(4000))
  parent_parameter_03 : (nvarchar(4000))
  parent_parameter_04 : (nvarchar(4000))
  parent_parameter_05 : (nvarchar(4000))
  parent_parameter_06 : (nvarchar(4000))
  parent_parameter_07 : (nvarchar(4000))
  parent_parameter_08 : (nvarchar(4000))
  parent_parameter_09 : (nvarchar(4000))
  parent_parameter_10 : (nvarchar(4000))
  parent_parameter_11 : (nvarchar(4000))
  parent_parameter_12 : (nvarchar(4000))
  parent_parameter_13 : (nvarchar(4000))
  parent_parameter_14 : (nvarchar(4000))
  parent_parameter_15 : (nvarchar(4000))
  parent_parameter_16 : (nvarchar(4000))
  parent_parameter_17 : (nvarchar(4000))
  parent_parameter_18 : (nvarchar(4000))
  parent_parameter_19 : (nvarchar(4000))
  parent_parameter_20 : (nvarchar(4000))
  parent_proc_fullname : (nvarchar(517))
  parent_proc_id : (int)
  parent_proc_name : (nvarchar(128))
  parent_proc_schema_name : (nvarchar(128))
  parent_step_id : (int)
  parent_step_name : (nvarchar(1000))
  --
}

