'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:reference.RepoObject_reference_T_bidirectional.adoc[]" as reference.RepoObject_reference_T_bidirectional << V >> {
  --
  referenced_entity_name : (nvarchar(128))
  - referenced_fullname : (nvarchar(261))
  - referenced_fullname2 : (nvarchar(257))
  referenced_is_persistence : (bit)
  - referenced_RepoObject_guid : (uniqueidentifier)
  referenced_schema_name : (nvarchar(128))
  referenced_source_RepoObject_guid : (uniqueidentifier)
  referenced_type : (char(2))
  referencing_entity_name : (nvarchar(128))
  - referencing_fullname : (nvarchar(261))
  - referencing_fullname2 : (nvarchar(257))
  referencing_is_persistence : (bit)
  - referencing_RepoObject_guid : (uniqueidentifier)
  referencing_schema_name : (nvarchar(128))
  referencing_source_RepoObject_guid : (uniqueidentifier)
  referencing_type : (varchar(2))
  --
}

