'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:reference.RepoObject_ReferencedReferencing.adoc[]" as reference.RepoObject_ReferencedReferencing << V >> {
  --
  - referenced_AntoraXref : (nvarchar(max))
  referenced_external_AntoraComponent : (nvarchar(128))
  referenced_external_AntoraModule : (nvarchar(128))
  - Referenced_fullname : (nvarchar(261))
  - Referenced_fullname2 : (nvarchar(257))
  - Referenced_guid : (uniqueidentifier)
  referenced_is_DocsOutput : (int)
  - referenced_is_external : (bit)
  Referenced_type : (char(2))
  - referencing_AntoraXref : (nvarchar(max))
  referencing_external_AntoraComponent : (nvarchar(128))
  referencing_external_AntoraModule : (nvarchar(128))
  - Referencing_fullname : (nvarchar(261))
  - Referencing_fullname2 : (nvarchar(257))
  - Referencing_guid : (uniqueidentifier)
  referencing_is_DocsOutput : (int)
  - referencing_is_external : (bit)
  Referencing_type : (varchar(2))
  --
}

