'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:sqlparse.RepoObject_SqlModules_21_statement_children_helper.adoc[]" as sqlparse.RepoObject_SqlModules_21_statement_children_helper << V >> {
  --
  children : (nvarchar(max))
  class : (nvarchar(500))
  - is_1_create : (int)
  - is_2_view : (int)
  - is_3_Identifier : (int)
  - is_4_as : (int)
  - is_5_select : (int)
  - is_6_Identifier : (int)
  - is_6_IdentifierList : (int)
  - is_7_from : (int)
  - is_7_IdentifierList : (int)
  - is_8_IdentifierList : (int)
  is_group : (bit)
  is_keyword : (bit)
  is_whitespace : (bit)
  - json_key : (nvarchar(4000))
  normalized : (nvarchar(max))
  - RepoObject_guid : (uniqueidentifier)
  RowNumber_per_Object : (bigint)
  SysObject_fullname : (nvarchar(261))
  --
}

