'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity sqlparse.RepoObject_SqlModules_43_from_Identifier << V >> {
  --
  alias : (nvarchar(max))
  class : (nvarchar(500))
  - json_key : (nvarchar(4000))
  lag_normalized_wo_nolock : (nvarchar(max))
  name : (nvarchar(max))
  name_charindex_dot : (bigint)
  name_PostDot : (nvarchar(max))
  name_PreDot : (nvarchar(max))
  - RepoObject_guid : (uniqueidentifier)
  RowNumber_per_Object : (bigint)
  SysObject_fullname : (nvarchar(261))
  T1_identifier_alias : (nvarchar(max))
  --
}

