'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssas.model_json_312_tables_measures_T.adoc[]" as ssas.model_json_312_tables_measures_T << U >> {
  - **Measure_guid** : (uniqueidentifier)
  --
  - databasename : (nvarchar(128))
  - RepoObject_guid : (uniqueidentifier)
  tables_measures_description : (nvarchar(max))
  tables_measures_description_ja : (nvarchar(max))
  tables_measures_displayFolder : (nvarchar(500))
  tables_measures_expression : (nvarchar(max))
  tables_measures_expression_ja : (nvarchar(max))
  tables_measures_formatString : (nvarchar(500))
  tables_measures_isHidden : (bit)
  tables_measures_name : (nvarchar(500))
  - tables_name : (nvarchar(128))
  --
}

