'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity ssas.TMSCHEMA_COLUMNS << U >> {
  - **databasename** : (nvarchar(128))
  - **ID** : (numeric(20, 0))
  --
  - Alignment : (bigint)
  - AttributeHierarchyID : (numeric(20, 0))
  ColumnOriginID : (numeric(20, 0))
  - ColumnStorageID : (numeric(20, 0))
  DataCategory : (nvarchar(max))
  Description : (nvarchar(max))
  DisplayFolder : (nvarchar(max))
  - DisplayOrdinal : (int)
  ErrorMessage : (nvarchar(max))
  - ExplicitDataType : (bigint)
  - ExplicitName : (nvarchar(max))
  Expression : (nvarchar(max))
  FormatString : (nvarchar(max))
  - InferredDataType : (bigint)
  InferredName : (nvarchar(max))
  - IsAvailableInMDX : (bit)
  - IsDefaultImage : (bit)
  - IsDefaultLabel : (bit)
  - IsHidden : (bit)
  - IsKey : (bit)
  - IsNullable : (bit)
  - IsUnique : (bit)
  - KeepUniqueRows : (bit)
  - ModifiedTime : (datetime)
  RefreshedTime : (nvarchar(max))
  SortByColumnID : (numeric(20, 0))
  SourceColumn : (nvarchar(max))
  SourceProviderType : (nvarchar(max))
  - State : (bigint)
  - StructureModifiedTime : (datetime)
  - SummarizeBy : (bigint)
  - SystemFlags : (bigint)
  - TableDetailPosition : (int)
  - TableID : (numeric(20, 0))
  - Type : (bigint)
  --
}

