'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:workflow.workflow_proceduredependency_t_bidirectional_t.adoc[]" as workflow.Workflow_ProcedureDependency_T_bidirectional_T << U >> {
  - **Workflow_id** : (int)
  - **referenced_Procedure_RepoObject_guid** : (uniqueidentifier)
  - **referencing_Procedure_RepoObject_guid** : (uniqueidentifier)
  --
  - is_inactive : (bit)
  - referenced_RepoObject_fullname : (nvarchar(261))
  - referencing_RepoObject_fullname : (nvarchar(261))
  --
}

