@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity "puml-link:docs.ssas_PumlRelation.adoc[prefix=..]" as docs.ssas_PumlRelation << V >> {
- idx_ssas_PumlRelation__1

..
referenced_ObjectName; nvarchar(128)
--
- idx_ssas_PumlRelation__2

..
referencing_ObjectName; nvarchar(128)
--
- idx_ssas_PumlRelation__3

..
referenced_IndexPatternColumnName; nvarchar(128)
--
- idx_ssas_PumlRelation__4

..
referencing_IndexPatternColumnName; nvarchar(128)
--
- idx_ssas_PumlRelation__5

..
referenced_ColumnName; nvarchar(128)
--
- idx_ssas_PumlRelation__6

..
referencing_ColumnName; nvarchar(128)
--
- idx_ssas_PumlRelation__7

..
ForeignKey_guid; uniqueidentifier
--
- idx_ssas_PumlRelation__8

..
SchemaName; nvarchar(128)
relationships_name; nvarchar(500)
--
- idx_ssas_PumlRelation__9

..
SchemaName; nvarchar(128)
}


footer
to view a reduced diagram in original size and to be able to click on the links:
open the diagram in a new tab via the Context menu.
end footer

@enduml

