@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:reference.repoobject_reference_persistence.adoc[]" as reference.RepoObject_reference_persistence << V >> {
- **PK_RepoObject_reference_persistence**

..
referenced_RepoObject_guid; uniqueidentifier
referencing_RepoObject_guid; uniqueidentifier
--
- idx_RepoObject_reference_persistence__2

..
referencing_schema_name; nvarchar(128)
referencing_entity_name; nvarchar(128)
--
- idx_RepoObject_reference_persistence__3

..
referenced_schema_name; nvarchar(128)
referenced_entity_name; nvarchar(128)
--
- idx_RepoObject_reference_persistence__4

..
referencing_RepoObject_guid; uniqueidentifier
}

footer The diagram is interactive and contains links.
@enduml

