Left to right direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity reference.Match_RepoObject_referenced_UspPersistence << V >> {
- **PK_Match_RepoObject_referenced_UspPersistence**

..
FirstNode; uniqueidentifier
LastNode; uniqueidentifier
--
- idx_Match_RepoObject_referenced_UspPersistence__2

..
FirstNode_schema_name; nvarchar(128)
--
- idx_Match_RepoObject_referenced_UspPersistence__3

..
LastNode_schema_name; nvarchar(128)
}


