@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity "puml-link:reference.RepoObjectColumn_reference_FirstResultSet.adoc[prefix=..]" as reference.RepoObjectColumn_reference_FirstResultSet << V >> {
- idx_RepoObjectColumn_reference_FirstResultSet__1

..
referencing_schema_name; nvarchar(128)
referencing_entity_name; nvarchar(128)
--
- idx_RepoObjectColumn_reference_FirstResultSet__2

..
referencing_RepoObject_guid; uniqueidentifier
--
- idx_RepoObjectColumn_reference_FirstResultSet__3

..
referencing_RepoObjectColumn_guid; uniqueidentifier
--
- idx_RepoObjectColumn_reference_FirstResultSet__4

..
referenced_RepoObjectColumn_guid; uniqueidentifier
--
- idx_RepoObjectColumn_reference_FirstResultSet__5

..
referenced_RepoObject_guid; uniqueidentifier
}


footer
to view a reduced diagram in original size and to be able to click on the links:
open the diagram in a new tab via the Context menu.
end footer

@enduml

