@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:repo.repoobjectcolumn_requiredrepoobjectcolumnmerge.adoc[]" as repo.RepoObjectColumn_RequiredRepoObjectColumnMerge << V >> {
- idx_RepoObjectColumn_RequiredRepoObjectColumnMerge__1

..
RepoObjectColumn_guid; uniqueidentifier
--
- idx_RepoObjectColumn_RequiredRepoObjectColumnMerge__2

..
roc2_RepoObjectColumn_guid; uniqueidentifier
--
- idx_RepoObjectColumn_RequiredRepoObjectColumnMerge__3

..
roc2_RepoObjectColumn_guid; uniqueidentifier
SysObjectColumn_name; nvarchar(128)
--
- idx_RepoObjectColumn_RequiredRepoObjectColumnMerge__4

..
RepoObjectColumn_guid; uniqueidentifier
roc2_SysObjectColumn_name; nvarchar(128)
--
- idx_RepoObjectColumn_RequiredRepoObjectColumnMerge__5

..
RepoObject_guid; uniqueidentifier
RepoObjectColumn_name; nvarchar(128)
--
- idx_RepoObjectColumn_RequiredRepoObjectColumnMerge__6

..
roc2_RepoObjectColumn_name; nvarchar(128)
--
- idx_RepoObjectColumn_RequiredRepoObjectColumnMerge__7

..
RepoObject_guid; uniqueidentifier
}


@enduml

