@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:repo_sys.sql_expression_dependencies.adoc[]" as repo_sys.sql_expression_dependencies << V >> {
- idx_sql_expression_dependencies__1

..
referencing_RepoObject_guid; uniqueidentifier
--
- idx_sql_expression_dependencies__2

..
referenced_RepoObject_guid; uniqueidentifier
--
- idx_sql_expression_dependencies__3

..
referenced_RepoObjectColumn_guid; uniqueidentifier
--
- idx_sql_expression_dependencies__4

..
referencing_RepoObjectColumn_guid; uniqueidentifier
}


@enduml

