@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:repo.repoobjectcolumn_external_tgt.adoc[]" as repo.RepoObjectColumn_external_tgt << V >> {
- **PK_RepoObjectColumn_external_tgt**

..
RepoObjectColumn_guid; uniqueidentifier
--
- UK_RepoObjectColumn_external_tgt__2

..
RepoObjectColumn_guid; uniqueidentifier
SysObjectColumn_name; nvarchar(128)
--
- UK_RepoObjectColumn_external_tgt__3

..
RepoObject_guid; uniqueidentifier
RepoObjectColumn_name; nvarchar(128)
--
- idx_RepoObjectColumn_external_tgt__4

..
RepoObject_guid; uniqueidentifier
--
- idx_RepoObjectColumn_external_tgt__5

..
RepoObjectColumn_name; nvarchar(128)
--
- idx_RepoObjectColumn_external_tgt__6

..
SysObjectColumn_name; nvarchar(128)
}

footer The diagram is interactive and contains links.
@enduml

