@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:repo.measures.adoc[]" as repo.Measures << V >> {
- idx_Measures__1

..
Measure_guid; uniqueidentifier
--
- idx_Measures__2
"ssas_table_measure"
..
RepoSchema_name; nvarchar(128)
RepoObject_name; nvarchar(128)
measures_name; nvarchar(500)
--
- idx_Measures__3

..
RepoSchema_name; nvarchar(128)
RepoObject_name; nvarchar(128)
--
- idx_Measures__4

..
RepoSchema_name; nvarchar(128)
}

footer The diagram is interactive and contains links.
@enduml

