@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssas.repoobjectcolumn_translation.adoc[]" as ssas.RepoObjectColumn_translation << V >> {
- **PK_RepoObjectColumn_translation**

..
RepoObjectColumn_guid; uniqueidentifier
cultures_name; nvarchar(10)
--
- idx_RepoObjectColumn_translation__2

..
RepoObjectColumn_guid; uniqueidentifier
--
- idx_RepoObjectColumn_translation__3

..
databasename; nvarchar(128)
tables_name; nvarchar(128)
tables_columns_name; nvarchar(128)
--
- idx_RepoObjectColumn_translation__4

..
databasename; nvarchar(128)
tables_name; nvarchar(128)
--
- idx_RepoObjectColumn_translation__5

..
databasename; nvarchar(128)
--
- idx_RepoObjectColumn_translation__6

..
cultures_translations_model_name; nvarchar(500)
}


@enduml

