@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:workflow.Workflow_ProcedureDependency_T_NotInSortorder_check.adoc[]" as workflow.Workflow_ProcedureDependency_T_NotInSortorder_check << V >> {
- idx_Workflow_ProcedureDependency_T_NotInSortorder_check__1

..
Workflow_id; int
referenced_Procedure_RepoObject_guid; uniqueidentifier
referencing_Procedure_RepoObject_guid; uniqueidentifier
--
- idx_Workflow_ProcedureDependency_T_NotInSortorder_check__2

..
Workflow_id; int
--
- idx_Workflow_ProcedureDependency_T_NotInSortorder_check__3

..
referenced_Procedure_RepoObject_guid; uniqueidentifier
referencing_Procedure_RepoObject_guid; uniqueidentifier
--
- idx_Workflow_ProcedureDependency_T_NotInSortorder_check__4

..
referenced_Procedure_RepoObject_guid; uniqueidentifier
--
- idx_Workflow_ProcedureDependency_T_NotInSortorder_check__5

..
referencing_Procedure_RepoObject_guid; uniqueidentifier
}


@enduml

