@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:workflow.ProcedureDependency_gross.adoc[]" as workflow.ProcedureDependency_gross << V >> {
- idx_ProcedureDependency_gross__1

..
referenced_RepoObject_schema_name; nvarchar(128)
--
- idx_ProcedureDependency_gross__2

..
referencing_RepoObject_schema_name; nvarchar(128)
--
- idx_ProcedureDependency_gross__3

..
id; int
--
- idx_ProcedureDependency_gross__4

..
referenced_Procedure_RepoObject_guid; uniqueidentifier
referencing_Procedure_RepoObject_guid; uniqueidentifier
--
- idx_ProcedureDependency_gross__5

..
referenced_Procedure_RepoObject_guid; uniqueidentifier
--
- idx_ProcedureDependency_gross__6

..
referencing_Procedure_RepoObject_guid; uniqueidentifier
}


@enduml

