'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity docs.RepoObject_ColumnList_T {
  * **RepoObject_guid** : uniqueidentifier
  --
}

entity docs.fs_cleanStringForPuml << FN >> {
  --
}

entity docs.ftv_RepoObject_Reference_PlantUml_EntityRefList << IF >> {
  --
}

entity docs.ObjectRefCyclic << V >> {
  --
}

entity docs.ObjectRefCyclic_EntityList << V >> {
  --
}

entity docs.ObjectRefCyclic_ObjectRefList << V >> {
  --
}

entity docs.RepoObject_Adoc << V >> {
  --
}

entity docs.RepoObject_Adoc_T << U >> {
  * **RepoObject_guid** : uniqueidentifier
  --
}

entity docs.RepoObject_ColumnList << V >> {
  --
}

entity docs.RepoObject_IndexList << V >> {
  **RepoObject_guid** : uniqueidentifier
  --
}

entity docs.RepoObject_IndexList_T << U >> {
  **RepoObject_guid** : uniqueidentifier
  --
}

entity docs.RepoObject_Plantuml << V >> {
  * **RepoObject_guid** : uniqueidentifier
  --
}

entity docs.RepoObject_Plantuml_ColRefList_1_1 << V >> {
  --
}

entity docs.RepoObject_Plantuml_Entity << V >> {
  * **RepoObject_guid** : uniqueidentifier
  --
}

entity docs.RepoObject_Plantuml_Entity_T << U >> {
  * **RepoObject_guid** : uniqueidentifier
  --
}

entity docs.RepoObject_PlantUml_FkRefList << V >> {
  --
}

entity docs.RepoObject_Plantuml_ObjectRefList_0_30 << V >> {
  * **RepoObject_guid** : uniqueidentifier
  --
}

entity docs.RepoObject_Plantuml_ObjectRefList_1_1 << V >> {
  --
}

entity docs.RepoObject_Plantuml_ObjectRefList_30_0 << V >> {
  * **RepoObject_guid** : uniqueidentifier
  --
}

entity docs.RepoObject_PlantUml_PumlEntityFkList << V >> {
  **RepoObject_guid** : uniqueidentifier
  --
}

entity docs.RepoObject_Plantuml_T << U >> {
  * **RepoObject_guid** : uniqueidentifier
  --
}

entity docs.Schema_EntityList << V >> {
  --
}

entity docs.Schema_PlantUml_FkRefList << V >> {
  --
}

entity docs.Schema_puml << V >> {
  --
}

entity docs.Schema_SsasRelationList << V >> {
  --
}

entity docs.ssas_PumlRelation << V >> {
  --
}

entity docs.usp_AntoraExport << P >> {
  --
}

entity docs.usp_AntoraExport_ObjectPartialProperties << P >> {
  --
}

entity docs.usp_AntoraExport_ObjectPuml << P >> {
  --
}

entity docs.usp_PERSIST_RepoObject_Adoc_T << P >> {
  --
}

entity docs.usp_PERSIST_RepoObject_ColumnList_T << P >> {
  --
}

entity docs.usp_PERSIST_RepoObject_IndexList_T << P >> {
  --
}

entity docs.usp_PERSIST_RepoObject_Plantuml_Entity_T << P >> {
  --
}

entity docs.usp_PERSIST_RepoObject_Plantuml_T << P >> {
  --
}

docs.fs_cleanStringForPuml <.. docs.RepoObject_ColumnList
docs.fs_cleanStringForPuml <.. docs.RepoObject_Plantuml_Entity
docs.fs_cleanStringForPuml <.. docs.RepoObject_IndexList
docs.fs_cleanStringForPuml <.. docs.RepoObject_PlantUml_FkRefList
docs.fs_cleanStringForPuml <.. docs.RepoObject_Plantuml_ObjectRefList_0_30
docs.fs_cleanStringForPuml <.. docs.RepoObject_Plantuml_ObjectRefList_30_0
docs.fs_cleanStringForPuml <.. docs.RepoObject_Plantuml_ObjectRefList_1_1
docs.fs_cleanStringForPuml <.. docs.RepoObject_Plantuml_ColRefList_1_1
docs.fs_cleanStringForPuml <.. docs.ObjectRefCyclic_ObjectRefList
docs.fs_cleanStringForPuml <.. docs.ssas_PumlRelation
docs.fs_cleanStringForPuml <.. docs.Schema_PlantUml_FkRefList
docs.ftv_RepoObject_Reference_PlantUml_EntityRefList <.. docs.RepoObject_Plantuml
docs.ObjectRefCyclic_EntityList <.. docs.ObjectRefCyclic
docs.ObjectRefCyclic_ObjectRefList <.. docs.ObjectRefCyclic
docs.RepoObject_Adoc <.. docs.RepoObject_Adoc_T
docs.RepoObject_Adoc <.. docs.usp_PERSIST_RepoObject_Adoc_T
docs.REpoObject_Adoc_T <.. docs.usp_PERSIST_RepoObject_Adoc_T
docs.RepoObject_ColumnList <.. docs.85AC3586-9B83-4474-AF3D-ED54F04062CA
docs.RepoObject_ColumnList <.. docs.usp_PERSIST_RepoObject_ColumnList_T
docs.RepoObject_IndexList <.. docs.RepoObject_IndexList_T
docs.RepoObject_IndexList <.. docs.usp_PERSIST_RepoObject_IndexList_T
docs.RepoObject_IndexList_T <.. docs.RepoObject_Adoc
docs.RepoObject_IndexList_T <.. docs.RepoObject_Plantuml_Entity
docs.RepoObject_IndexList_T <.. docs.usp_PERSIST_RepoObject_IndexList_T
docs.RepoObject_Plantuml <.. docs.RepoObject_Plantuml_T
docs.RepoObject_Plantuml <.. docs.RepoObject_Plantuml_T
docs.RepoObject_Plantuml <.. docs.RepoObject_Plantuml_T
docs.RepoObject_Plantuml <.. docs.RepoObject_Plantuml_T
docs.RepoObject_Plantuml <.. docs.RepoObject_Plantuml_T
docs.RepoObject_Plantuml <.. docs.usp_PERSIST_RepoObject_Plantuml_T
docs.RepoObject_Plantuml <.. docs.usp_PERSIST_RepoObject_Plantuml_T
docs.RepoObject_Plantuml <.. docs.usp_PERSIST_RepoObject_Plantuml_T
docs.RepoObject_Plantuml <.. docs.usp_PERSIST_RepoObject_Plantuml_T
docs.RepoObject_Plantuml <.. docs.usp_PERSIST_RepoObject_Plantuml_T
docs.RepoObject_Plantuml_ColRefList_1_1 <.. docs.RepoObject_Plantuml
docs.RepoObject_Plantuml_Entity <.. docs.RepoObject_Plantuml_Entity_T
docs.RepoObject_Plantuml_Entity <.. docs.usp_PERSIST_RepoObject_Plantuml_Entity_T
docs.RepoObject_Plantuml_Entity_T <.. docs.usp_PERSIST_RepoObject_Plantuml_Entity_T
docs.RepoObject_Plantuml_Entity_T <.. docs.ftv_RepoObject_Reference_PlantUml_EntityRefList
docs.RepoObject_Plantuml_Entity_T <.. docs.RepoObject_PlantUml_PumlEntityFkList
docs.RepoObject_Plantuml_Entity_T <.. docs.ObjectRefCyclic_EntityList
docs.RepoObject_Plantuml_Entity_T <.. docs.Schema_EntityList
docs.RepoObject_PlantUml_FkRefList <.. docs.RepoObject_Plantuml
docs.RepoObject_Plantuml_ObjectRefList_0_30 <.. docs.RepoObject_Plantuml
docs.RepoObject_Plantuml_ObjectRefList_1_1 <.. docs.RepoObject_Plantuml
docs.RepoObject_Plantuml_ObjectRefList_30_0 <.. docs.RepoObject_Plantuml
docs.RepoObject_PlantUml_PumlEntityFkList <.. docs.RepoObject_Plantuml
docs.RepoObject_Plantuml_T <.. docs.usp_PERSIST_RepoObject_Plantuml_T
docs.RepoObject_Plantuml_T <.. docs.usp_PERSIST_RepoObject_Plantuml_T
docs.RepoObject_Plantuml_T <.. docs.usp_PERSIST_RepoObject_Plantuml_T
docs.RepoObject_Plantuml_T <.. docs.usp_PERSIST_RepoObject_Plantuml_T
docs.RepoObject_Plantuml_T <.. docs.usp_PERSIST_RepoObject_Plantuml_T
docs.Schema_EntityList <.. docs.Schema_puml
docs.Schema_PlantUml_FkRefList <.. docs.Schema_puml
docs.Schema_SsasRelationList <.. docs.Schema_puml
docs.ssas_PumlRelation <.. docs.Schema_SsasRelationList
docs.usp_AntoraExport_ObjectPartialProperties <.. docs.usp_AntoraExport
docs.usp_AntoraExport_ObjectPartialProperties <.. docs.usp_AntoraExport
docs.usp_AntoraExport_ObjectPuml <.. docs.usp_AntoraExport
docs.usp_PERSIST_RepoObject_Adoc_T <.. docs.usp_AntoraExport_ObjectPartialProperties
docs.usp_PERSIST_RepoObject_ColumnList_T <.. docs.usp_AntoraExport_ObjectPartialProperties
docs.usp_PERSIST_RepoObject_IndexList_T <.. docs.usp_AntoraExport_ObjectPartialProperties
docs.usp_PERSIST_RepoObject_Plantuml_Entity_T <.. docs.usp_AntoraExport_ObjectPuml
docs.usp_PERSIST_RepoObject_Plantuml_T <.. docs.usp_AntoraExport_ObjectPuml
docs.usp_PERSIST_RepoObject_Plantuml_T <.. docs.usp_AntoraExport_ObjectPuml
docs.usp_PERSIST_RepoObject_Plantuml_T <.. docs.usp_AntoraExport_ObjectPuml
docs.usp_PERSIST_RepoObject_Plantuml_T <.. docs.usp_AntoraExport_ObjectPuml
docs.usp_PERSIST_RepoObject_Plantuml_T <.. docs.usp_AntoraExport_ObjectPuml
