@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity "[[{site-url}/{page-component-name}/current/{page-module}/docs.ObjectRefCyclic.html docs.ObjectRefCyclic]]" as docs.ObjectRefCyclic << V >> {
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/docs.ObjectRefCyclic_EntityList.html docs.ObjectRefCyclic_EntityList]]" as docs.ObjectRefCyclic_EntityList << V >> {
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/docs.ObjectRefCyclic_ObjectRefList.html docs.ObjectRefCyclic_ObjectRefList]]" as docs.ObjectRefCyclic_ObjectRefList << V >> {
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/reference.ReferenceTree_cyclic_ref_PersistenceUsp.html reference.ReferenceTree_cyclic_ref_PersistenceUsp]]" as reference.ReferenceTree_cyclic_ref_PersistenceUsp << V >> {
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/reference.ReferenceTree_cyclic_union.html reference.ReferenceTree_cyclic_union]]" as reference.ReferenceTree_cyclic_union << V >> {
  --
}

docs.ObjectRefCyclic_EntityList <.. docs.ObjectRefCyclic
docs.ObjectRefCyclic_ObjectRefList <.. docs.ObjectRefCyclic
reference.ReferenceTree_cyclic_ref_PersistenceUsp <.. reference.ReferenceTree_cyclic_union
reference.ReferenceTree_cyclic_union <.. docs.ObjectRefCyclic_EntityList
reference.ReferenceTree_cyclic_union <.. docs.ObjectRefCyclic_ObjectRefList
footer
to view a reduced diagram in original size and to be able to click on the links:
open the diagram in a new tab via the Context menu.
end footer

@enduml

