@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity "puml-link:repo.RepoObjectColumn_HistValidColums_setpoint.adoc[prefix=..]" as repo.RepoObjectColumn_HistValidColums_setpoint << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  **RepoObjectColumn_name** : (sysname)
  --
}

entity "puml-link:repo.usp_main.adoc[prefix=..]" as repo.usp_main << P >> {
  --
}

entity "puml-link:repo.usp_persistence_set.adoc[prefix=..]" as repo.usp_persistence_set << P >> {
  --
}

entity "puml-link:repo.usp_sync_guid.adoc[prefix=..]" as repo.usp_sync_guid << P >> {
  --
}

entity "puml-link:repo.usp_sync_guid_RepoObjectColumn.adoc[prefix=..]" as repo.usp_sync_guid_RepoObjectColumn << P >> {
  --
}

repo.RepoObjectColumn_HistValidColums_setpoint <.. repo.usp_sync_guid_RepoObjectColumn
repo.usp_sync_guid <.. repo.usp_persistence_set
repo.usp_sync_guid <.. repo.usp_main
repo.usp_sync_guid_RepoObjectColumn <.. repo.usp_sync_guid
footer
to view a reduced diagram in original size and to be able to click on the links:
open the diagram in a new tab via the Context menu.
end footer

@enduml

