@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssas.model_json_35_roles.adoc[]" as ssas.model_json_35_roles << V >> {
  - **databasename** : (nvarchar(128))
  **roles_name** : (nvarchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_351_roles_members.adoc[]" as ssas.model_json_351_roles_members << V >> {
  - **databasename** : (nvarchar(128))
  **roles_name** : (nvarchar(500))
  **roles_members_memberId** : (nvarchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_352_roles_tablePermissions.adoc[]" as ssas.model_json_352_roles_tablePermissions << V >> {
  - **databasename** : (nvarchar(128))
  **roles_name** : (nvarchar(500))
  **roles_tablePermissions_name** : (nvarchar(500))
  --
}

ssas.model_json_35_roles <.. ssas.model_json_351_roles_members
ssas.model_json_35_roles <.. ssas.model_json_352_roles_tablePermissions
@enduml

