@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity "[[{site-url}/{page-component-name}/{page-component-version}/{page-module}/dmdocs.unit.html dmdocs.unit]]" as dmdocs.unit << V >> {
  --
}

entity "[[{site-url}/{page-component-name}/{page-component-version}/{page-module}/docs.AntoraNavListPage_by_schema.html docs.AntoraNavListPage_by_schema]]" as docs.AntoraNavListPage_by_schema << V >> {
  - **RepoObject_schema_name** : (nvarchar(128))
  --
}

entity "[[{site-url}/{page-component-name}/{page-component-version}/{page-module}/docs.Schema_puml.html docs.Schema_puml]]" as docs.Schema_puml << V >> {
  --
}

entity "[[{site-url}/{page-component-name}/{page-component-version}/{page-module}/docs.Unit_1_union.html docs.Unit_1_union]]" as docs.Unit_1_union << V >> {
  --
}

entity "[[{site-url}/{page-component-name}/{page-component-version}/{page-module}/docs.Unit_2.html docs.Unit_2]]" as docs.Unit_2 << V >> {
  --
}

entity "[[{site-url}/{page-component-name}/{page-component-version}/{page-module}/docs.Unit_3.html docs.Unit_3]]" as docs.Unit_3 << V >> {
  --
}

entity "[[{site-url}/{page-component-name}/{page-component-version}/{page-module}/docs.usp_AntoraExport.html docs.usp_AntoraExport]]" as docs.usp_AntoraExport << P >> {
  --
}

entity "[[{site-url}/{page-component-name}/{page-component-version}/{page-module}/docs.usp_AntoraExport_ObjectPuml.html docs.usp_AntoraExport_ObjectPuml]]" as docs.usp_AntoraExport_ObjectPuml << P >> {
  --
}

entity "[[{site-url}/{page-component-name}/{page-component-version}/{page-module}/property.ExtendedProperty_Repo2Sys_level0.html property.ExtendedProperty_Repo2Sys_level0]]" as property.ExtendedProperty_Repo2Sys_level0 << V >> {
  --
}

entity "[[{site-url}/{page-component-name}/{page-component-version}/{page-module}/property.usp_sync_ExtendedProperties_Repo2Sys_Delete.html property.usp_sync_ExtendedProperties_Repo2Sys_Delete]]" as property.usp_sync_ExtendedProperties_Repo2Sys_Delete << P >> {
  --
}

entity "[[{site-url}/{page-component-name}/{page-component-version}/{page-module}/property.usp_sync_ExtendedProperties_Repo2Sys_InsertUpdate.html property.usp_sync_ExtendedProperties_Repo2Sys_InsertUpdate]]" as property.usp_sync_ExtendedProperties_Repo2Sys_InsertUpdate << P >> {
  --
}

entity "[[{site-url}/{page-component-name}/{page-component-version}/{page-module}/property.usp_sync_ExtendedProperties_Sys2Repo_InsertUpdate.html property.usp_sync_ExtendedProperties_Sys2Repo_InsertUpdate]]" as property.usp_sync_ExtendedProperties_Sys2Repo_InsertUpdate << P >> {
  --
}

entity "[[{site-url}/{page-component-name}/{page-component-version}/{page-module}/repo.RepoSchema.html repo.RepoSchema]]" as repo.RepoSchema << U >> {
  - **RepoSchema_guid** : (uniqueidentifier)
  --
}

entity "[[{site-url}/{page-component-name}/{page-component-version}/{page-module}/repo.RepoSchema_ssas_src.html repo.RepoSchema_ssas_src]]" as repo.RepoSchema_ssas_src << V >> {
  - **RepoSchema_name** : (nvarchar(128))
  --
}

entity "[[{site-url}/{page-component-name}/{page-component-version}/{page-module}/repo.RepoSchema_ssas_tgt.html repo.RepoSchema_ssas_tgt]]" as repo.RepoSchema_ssas_tgt << V >> {
  - **RepoSchema_name** : (nvarchar(128))
  --
}

entity "[[{site-url}/{page-component-name}/{page-component-version}/{page-module}/repo.SysSchema_RepoSchema_via_guid.html repo.SysSchema_RepoSchema_via_guid]]" as repo.SysSchema_RepoSchema_via_guid << V >> {
  --
}

entity "[[{site-url}/{page-component-name}/{page-component-version}/{page-module}/repo.SysSchema_RepoSchema_via_name.html repo.SysSchema_RepoSchema_via_name]]" as repo.SysSchema_RepoSchema_via_name << V >> {
  --
}

entity "[[{site-url}/{page-component-name}/{page-component-version}/{page-module}/repo.usp_main.html repo.usp_main]]" as repo.usp_main << P >> {
  --
}

entity "[[{site-url}/{page-component-name}/{page-component-version}/{page-module}/repo.usp_PERSIST_RepoSchema_ssas_tgt.html repo.usp_PERSIST_RepoSchema_ssas_tgt]]" as repo.usp_PERSIST_RepoSchema_ssas_tgt << P >> {
  --
}

entity "[[{site-url}/{page-component-name}/{page-component-version}/{page-module}/repo.usp_persistence_set.html repo.usp_persistence_set]]" as repo.usp_persistence_set << P >> {
  --
}

entity "[[{site-url}/{page-component-name}/{page-component-version}/{page-module}/repo.usp_sync_guid.html repo.usp_sync_guid]]" as repo.usp_sync_guid << P >> {
  --
}

entity "[[{site-url}/{page-component-name}/{page-component-version}/{page-module}/repo.usp_sync_guid_RepoSchema.html repo.usp_sync_guid_RepoSchema]]" as repo.usp_sync_guid_RepoSchema << P >> {
  --
}

entity "[[{site-url}/{page-component-name}/{page-component-version}/{page-module}/repo.usp_sync_guid_ssas.html repo.usp_sync_guid_ssas]]" as repo.usp_sync_guid_ssas << P >> {
  --
}

entity "[[{site-url}/{page-component-name}/{page-component-version}/{page-module}/ssas.model_json_2011_descriptions_StrAgg.html ssas.model_json_2011_descriptions_StrAgg]]" as ssas.model_json_2011_descriptions_StrAgg << V >> {
  --
}

docs.Unit_1_union <.. docs.Unit_2
docs.Unit_2 <.. docs.Unit_3
docs.Unit_3 <.. dmdocs.unit
docs.usp_AntoraExport_ObjectPuml <.. docs.usp_AntoraExport
property.ExtendedProperty_Repo2Sys_level0 <.. property.usp_sync_ExtendedProperties_Repo2Sys_InsertUpdate
property.ExtendedProperty_Repo2Sys_level0 <.. property.usp_sync_ExtendedProperties_Repo2Sys_Delete
repo.RepoSchema <.. property.usp_sync_ExtendedProperties_Sys2Repo_InsertUpdate
repo.RepoSchema <.. docs.usp_AntoraExport_ObjectPuml
repo.RepoSchema <.. docs.AntoraNavListPage_by_schema
repo.RepoSchema <.. repo.SysSchema_RepoSchema_via_guid
repo.RepoSchema <.. repo.SysSchema_RepoSchema_via_name
repo.RepoSchema <.. repo.usp_sync_guid_RepoSchema
repo.RepoSchema <.. property.ExtendedProperty_Repo2Sys_level0
repo.RepoSchema <.. repo.RepoSchema_ssas_tgt
repo.RepoSchema <.. docs.Schema_puml
repo.RepoSchema <.. docs.Unit_1_union
repo.RepoSchema_ssas_src <.. repo.RepoSchema_ssas_tgt
repo.RepoSchema_ssas_src <.. repo.usp_PERSIST_RepoSchema_ssas_tgt
repo.RepoSchema_ssas_tgt <.. repo.RepoSchema
repo.RepoSchema_ssas_tgt <.. repo.usp_PERSIST_RepoSchema_ssas_tgt
repo.SysSchema_RepoSchema_via_guid <.. repo.usp_sync_guid_RepoSchema
repo.SysSchema_RepoSchema_via_name <.. repo.usp_sync_guid_RepoSchema
repo.usp_PERSIST_RepoSchema_ssas_tgt <.. repo.usp_sync_guid_ssas
repo.usp_sync_guid <.. repo.usp_persistence_set
repo.usp_sync_guid <.. repo.usp_main
repo.usp_sync_guid_RepoSchema <.. repo.usp_sync_guid
repo.usp_sync_guid_ssas <.. repo.usp_main
ssas.model_json_2011_descriptions_StrAgg <.. repo.RepoSchema_ssas_src
footer
to view a reduced diagram in original size and to be able to click on the links:
open the diagram in a new tab via the Context menu.
end footer

@enduml

