@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity "puml-link:dmdocs.unit.adoc[prefix=..]" as dmdocs.unit << V >> {
  --
}

entity "puml-link:docs.AntoraNavListPage_by_schema.adoc[prefix=..]" as docs.AntoraNavListPage_by_schema << V >> {
  - **RepoObject_schema_name** : (nvarchar(128))
  --
}

entity "puml-link:docs.Schema_puml.adoc[prefix=..]" as docs.Schema_puml << V >> {
  --
}

entity "puml-link:docs.Unit_1_union.adoc[prefix=..]" as docs.Unit_1_union << V >> {
  --
}

entity "puml-link:docs.Unit_2.adoc[prefix=..]" as docs.Unit_2 << V >> {
  --
}

entity "puml-link:docs.Unit_3.adoc[prefix=..]" as docs.Unit_3 << V >> {
  --
}

entity "puml-link:docs.usp_AntoraExport.adoc[prefix=..]" as docs.usp_AntoraExport << P >> {
  --
}

entity "puml-link:docs.usp_AntoraExport_ObjectPuml.adoc[prefix=..]" as docs.usp_AntoraExport_ObjectPuml << P >> {
  --
}

entity "puml-link:property.ExtendedProperty_Repo2Sys_level0.adoc[prefix=..]" as property.ExtendedProperty_Repo2Sys_level0 << V >> {
  --
}

entity "puml-link:property.usp_sync_ExtendedProperties_Repo2Sys_Delete.adoc[prefix=..]" as property.usp_sync_ExtendedProperties_Repo2Sys_Delete << P >> {
  --
}

entity "puml-link:property.usp_sync_ExtendedProperties_Repo2Sys_InsertUpdate.adoc[prefix=..]" as property.usp_sync_ExtendedProperties_Repo2Sys_InsertUpdate << P >> {
  --
}

entity "puml-link:property.usp_sync_ExtendedProperties_Sys2Repo_InsertUpdate.adoc[prefix=..]" as property.usp_sync_ExtendedProperties_Sys2Repo_InsertUpdate << P >> {
  --
}

entity "puml-link:repo.RepoSchema.adoc[prefix=..]" as repo.RepoSchema << U >> {
  - **RepoSchema_guid** : (uniqueidentifier)
  --
}

entity "puml-link:repo.RepoSchema_ssas_src.adoc[prefix=..]" as repo.RepoSchema_ssas_src << V >> {
  - **RepoSchema_name** : (nvarchar(128))
  --
}

entity "puml-link:repo.RepoSchema_ssas_tgt.adoc[prefix=..]" as repo.RepoSchema_ssas_tgt << V >> {
  - **RepoSchema_name** : (nvarchar(128))
  --
}

entity "puml-link:repo.SysSchema_RepoSchema_via_guid.adoc[prefix=..]" as repo.SysSchema_RepoSchema_via_guid << V >> {
  --
}

entity "puml-link:repo.SysSchema_RepoSchema_via_name.adoc[prefix=..]" as repo.SysSchema_RepoSchema_via_name << V >> {
  --
}

entity "puml-link:repo.usp_main.adoc[prefix=..]" as repo.usp_main << P >> {
  --
}

entity "puml-link:repo.usp_PERSIST_RepoSchema_ssas_tgt.adoc[prefix=..]" as repo.usp_PERSIST_RepoSchema_ssas_tgt << P >> {
  --
}

entity "puml-link:repo.usp_persistence_set.adoc[prefix=..]" as repo.usp_persistence_set << P >> {
  --
}

entity "puml-link:repo.usp_sync_guid.adoc[prefix=..]" as repo.usp_sync_guid << P >> {
  --
}

entity "puml-link:repo.usp_sync_guid_RepoSchema.adoc[prefix=..]" as repo.usp_sync_guid_RepoSchema << P >> {
  --
}

entity "puml-link:repo.usp_sync_guid_ssas.adoc[prefix=..]" as repo.usp_sync_guid_ssas << P >> {
  --
}

entity "puml-link:ssas.model_json_201_descriptions_multiline.adoc[prefix=..]" as ssas.model_json_201_descriptions_multiline << V >> {
  --
}

entity "puml-link:ssas.model_json_2011_descriptions_StrAgg.adoc[prefix=..]" as ssas.model_json_2011_descriptions_StrAgg << V >> {
  --
}

docs.Unit_1_union <.. docs.Unit_2
docs.Unit_2 <.. docs.Unit_3
docs.Unit_3 <.. dmdocs.unit
docs.usp_AntoraExport_ObjectPuml <.. docs.usp_AntoraExport
property.ExtendedProperty_Repo2Sys_level0 <.. property.usp_sync_ExtendedProperties_Repo2Sys_InsertUpdate
property.ExtendedProperty_Repo2Sys_level0 <.. property.usp_sync_ExtendedProperties_Repo2Sys_Delete
repo.RepoSchema <.. property.usp_sync_ExtendedProperties_Sys2Repo_InsertUpdate
repo.RepoSchema <.. docs.usp_AntoraExport_ObjectPuml
repo.RepoSchema <.. docs.AntoraNavListPage_by_schema
repo.RepoSchema <.. repo.SysSchema_RepoSchema_via_guid
repo.RepoSchema <.. repo.SysSchema_RepoSchema_via_name
repo.RepoSchema <.. repo.usp_sync_guid_RepoSchema
repo.RepoSchema <.. property.ExtendedProperty_Repo2Sys_level0
repo.RepoSchema <.. repo.RepoSchema_ssas_tgt
repo.RepoSchema <.. docs.Schema_puml
repo.RepoSchema <.. docs.Unit_1_union
repo.RepoSchema_ssas_src <.. repo.RepoSchema_ssas_tgt
repo.RepoSchema_ssas_src <.. repo.usp_PERSIST_RepoSchema_ssas_tgt
repo.RepoSchema_ssas_tgt <.. repo.RepoSchema
repo.RepoSchema_ssas_tgt <.. repo.usp_PERSIST_RepoSchema_ssas_tgt
repo.SysSchema_RepoSchema_via_guid <.. repo.usp_sync_guid_RepoSchema
repo.SysSchema_RepoSchema_via_name <.. repo.usp_sync_guid_RepoSchema
repo.usp_PERSIST_RepoSchema_ssas_tgt <.. repo.usp_sync_guid_ssas
repo.usp_sync_guid <.. repo.usp_persistence_set
repo.usp_sync_guid <.. repo.usp_main
repo.usp_sync_guid_RepoSchema <.. repo.usp_sync_guid
repo.usp_sync_guid_ssas <.. repo.usp_main
ssas.model_json_201_descriptions_multiline <.. ssas.model_json_2011_descriptions_StrAgg
ssas.model_json_2011_descriptions_StrAgg <.. repo.RepoSchema_ssas_src
footer
to view a reduced diagram in original size and to be able to click on the links:
open the diagram in a new tab via the Context menu.
end footer

@enduml

