'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity docs.RepoObject_ColumnList_T {
  * **RepoObject_guid** : uniqueidentifier
  --
}

entity docs.RepoObject_Adoc << V >> {
  --
}

entity docs.RepoObject_Adoc_T << U >> {
  * **RepoObject_guid** : uniqueidentifier
  --
}

entity docs.RepoObject_ColumnList << V >> {
  --
}

entity docs.RepoObject_Plantuml << V >> {
  * **RepoObject_guid** : uniqueidentifier
  --
}

entity docs.RepoObject_Plantuml_ColRefList_1_1 << V >> {
  --
}

entity docs.RepoObject_Plantuml_T << U >> {
  * **RepoObject_guid** : uniqueidentifier
  --
}

entity docs.usp_AntoraExport << P >> {
  --
}

entity docs.usp_AntoraExport_ObjectPartialProperties << P >> {
  --
}

entity docs.usp_AntoraExport_ObjectPuml << P >> {
  --
}

entity docs.usp_PERSIST_RepoObject_Adoc_T << P >> {
  --
}

entity docs.usp_PERSIST_RepoObject_ColumnList_T << P >> {
  --
}

entity docs.usp_PERSIST_RepoObject_Plantuml_T << P >> {
  --
}

entity graph.RepoObjectColumn_S << V >> {
  * **RepoObjectColumn_guid** : uniqueidentifier
  --
}

entity property.RepoObjectColumnProperty_ForUpdate << V >> {
  * **RepoObjectColumnProperty_id** : int
  --
}

entity property.RepoObjectProperty_Collect_source_ROGross << V >> {
  * **RepoObject_guid** : uniqueidentifier
  * **property_name** : varchar(39)
  --
}

entity property.usp_RepoObjectProperty_collect << P >> {
  --
}

entity reference.ftv_RepoObject_ColumReferenceRepoObject << IF >> {
  --
}

entity reference.ftv_RepoObject_DbmlColumnRelation << IF >> {
  --
}

entity reference.ftv_RepoObjectColumn_ReferenceTree << IF >> {
  --
}

entity reference.RepoObjectColumn_reference << V >> {
  **referenced_RepoObjectColumn_guid** : uniqueidentifier
  **referencing_RepoObjectColumn_guid** : uniqueidentifier
  --
}

entity reference.RepoObjectColumn_reference_BySamePredecessors << V >> {
  --
}

entity reference.RepoObjectColumn_reference_FirstResultSet << V >> {
  --
}

entity reference.RepoObjectColumn_reference_QueryPlan << V >> {
  **referencing_id** : int
  **referencing_minor_id** : int
  **referenced_id** : int
  **referenced_minor_id** : int
  --
}

entity reference.RepoObjectColumn_reference_T << U >> {
  **referenced_RepoObjectColumn_guid** : uniqueidentifier
  **referencing_RepoObjectColumn_guid** : uniqueidentifier
  --
}

entity reference.RepoObjectColumn_reference_union << V >> {
  --
}

entity reference.RepoObjectColumn_reference_virtual << V >> {
  --
}

entity reference.RepoObjectColumn_ReferencedList << V >> {
  --
}

entity reference.RepoObjectColumn_ReferenceTree << V >> {
  --
}

entity reference.RepoObjectColumn_ReferencingList << V >> {
  --
}

entity reference.RepoObjectColumn_ReferencingReferenced << V >> {
  * **Referenced_guid** : uniqueidentifier
  * **Referencing_guid** : uniqueidentifier
  --
}

entity reference.RepoObjectColumn_RelationScript << V >> {
  --
}

entity reference.SysObjectColumn_QueryPlanExpression << V >> {
  --
}

entity reference.usp_PERSIST_RepoObjectColumn_reference_T << P >> {
  --
}

entity reference.usp_RepoObjectColumnSource_virtual_set << P >> {
  --
}

entity reference.usp_RepoObjectSource_QueryPlan << P >> {
  --
}

entity repo.check_IndexColumn_virtual_referenced_setpoint << V >> {
  * **index_guid** : uniqueidentifier
  * **index_column_id** : int
  --
}

entity repo.Index_referencing_IndexPatternColumnGuid << V >> {
  **source_index_guid** : uniqueidentifier
  **referencing_RepoObject_guid** : uniqueidentifier
  --
}

entity repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing << V >> {
  **index_guid** : uniqueidentifier
  * **index_column_id** : int
  **RowNumberInReferencing** : bigint
  --
}

entity repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_check << V >> {
  --
}

entity repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T << U >> {
  **index_guid** : uniqueidentifier
  * **index_column_id** : int
  **RowNumberInReferencing** : bigint
  --
}

entity repo.IndexColumn_virtual_referenced_setpoint << V >> {
  * **index_guid** : uniqueidentifier
  * **index_column_id** : int
  --
}

entity repo.IndexReferencedReferencing_HasFullColumnsInReferencing << V >> {
  --
}

entity repo.RepoObject_ColumnList << V >> {
  --
}

entity repo.RepoObject_gross2 << V >> {
  --
}

entity repo.RepoObject_SqlCreateTable << V >> {
  * **RepoObject_guid** : uniqueidentifier
  --
}

entity repo.RepoObjectColumn_gross << V >> {
  * **RepoObjectColumn_guid** : uniqueidentifier
  --
}

entity repo.RepoObjectColumn_gross2 << V >> {
  --
}

entity repo.RepoObjectColumn_MissingSource_TypeV << V >> {
  * **RepoObjectColumn_guid** : uniqueidentifier
  --
}

entity repo.usp_index_inheritance << P >> {
  --
}

entity repo.usp_main << P >> {
  --
}

entity repo.usp_PERSIST_IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T << P >> {
  --
}

entity repo.usp_persistence_set << P >> {
  --
}

entity repo.usp_sync_guid << P >> {
  --
}

entity repo.usp_sync_guid_RepoObjectColumn << P >> {
  --
}

entity ssas.model_json_3111_tables_columns_descriptions_multiline << V >> {
  --
}

entity ssas.model_json_31111_tables_columns_descriptions_StrAgg << V >> {
  --
}

entity uspgenerator.GeneratorUspStep_Persistence << V >> {
  * **usp_id** : int
  --
}

entity uspgenerator.usp_GeneratorUsp_insert_update_persistence << P >> {
  --
}

docs.RepoObject_Adoc <.. docs.RepoObject_Adoc_T
docs.RepoObject_Adoc <.. docs.usp_PERSIST_RepoObject_Adoc_T
docs.REpoObject_Adoc_T <.. docs.usp_PERSIST_RepoObject_Adoc_T
docs.RepoObject_ColumnList <.. docs.85AC3586-9B83-4474-AF3D-ED54F04062CA
docs.RepoObject_ColumnList <.. docs.usp_PERSIST_RepoObject_ColumnList_T
docs.RepoObject_Plantuml <.. docs.RepoObject_Plantuml_T
docs.RepoObject_Plantuml <.. docs.usp_PERSIST_RepoObject_Plantuml_T
docs.RepoObject_Plantuml_ColRefList_1_1 <.. docs.RepoObject_Plantuml
docs.RepoObject_Plantuml_T <.. docs.usp_PERSIST_RepoObject_Plantuml_T
docs.usp_AntoraExport_ObjectPartialProperties <.. docs.usp_AntoraExport
docs.usp_AntoraExport_ObjectPuml <.. docs.usp_AntoraExport
docs.usp_PERSIST_RepoObject_Adoc_T <.. docs.usp_AntoraExport_ObjectPartialProperties
docs.usp_PERSIST_RepoObject_ColumnList_T <.. docs.usp_AntoraExport_ObjectPartialProperties
docs.usp_PERSIST_RepoObject_Plantuml_T <.. docs.usp_AntoraExport_ObjectPuml
property.RepoObjectProperty_Collect_source_ROGross <.. property.usp_RepoObjectProperty_collect
property.usp_RepoObjectProperty_collect <.. docs.usp_AntoraExport
reference.ftv_RepoObjectColumn_ReferenceTree <.. reference.RepoObjectColumn_ReferenceTree
reference.RepoObjectColumn_reference <.. reference.RepoObjectColumn_reference_T
reference.RepoObjectColumn_reference <.. reference.usp_PERSIST_RepoObjectColumn_reference_T
reference.RepoObjectColumn_reference_FirstResultSet <.. reference.RepoObjectColumn_reference_BySamePredecessors
reference.RepoObjectColumn_reference_QueryPlan <.. reference.SysObjectColumn_QueryPlanExpression
reference.RepoObjectColumn_reference_T <.. repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing
reference.RepoObjectColumn_reference_T <.. repo.RepoObjectColumn_MissingSource_TypeV
reference.RepoObjectColumn_reference_T <.. reference.RepoObjectColumn_RelationScript
reference.RepoObjectColumn_reference_T <.. reference.RepoObjectColumn_ReferencingReferenced
reference.RepoObjectColumn_reference_T <.. reference.usp_PERSIST_RepoObjectColumn_reference_T
reference.RepoObjectColumn_reference_T <.. docs.RepoObject_Plantuml_ColRefList_1_1
reference.RepoObjectColumn_reference_union <.. reference.RepoObjectColumn_reference
reference.RepoObjectColumn_reference_virtual <.. reference.RepoObjectColumn_reference_union
reference.RepoObjectColumn_ReferencedList <.. repo.RepoObjectColumn_gross2
reference.RepoObjectColumn_ReferenceTree <.. reference.ftv_RepoObject_ColumReferenceRepoObject
reference.RepoObjectColumn_ReferencingList <.. repo.RepoObjectColumn_gross2
reference.RepoObjectColumn_ReferencingReferenced <.. reference.ftv_RepoObjectColumn_ReferenceTree
reference.RepoObjectColumn_ReferencingReferenced <.. reference.ftv_RepoObject_DbmlColumnRelation
reference.RepoObjectColumn_ReferencingReferenced <.. reference.RepoObjectColumn_ReferencedList
reference.RepoObjectColumn_ReferencingReferenced <.. reference.RepoObjectColumn_ReferencingList
reference.RepoObjectColumn_RelationScript <.. reference.ftv_RepoObject_ColumReferenceRepoObject
reference.SysObjectColumn_QueryPlanExpression <.. reference.usp_RepoObjectSource_QueryPlan
reference.usp_PERSIST_RepoObjectColumn_reference_T <.. repo.usp_main
reference.usp_RepoObjectSource_QueryPlan <.. repo.usp_main
repo.Index_referencing_IndexPatternColumnGuid <.. repo.IndexReferencedReferencing_HasFullColumnsInReferencing
repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing <.. repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T
repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing <.. repo.usp_PERSIST_IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T
repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T <.. repo.Index_referencing_IndexPatternColumnGuid
repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T <.. repo.usp_PERSIST_IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T
repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T <.. repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_check
repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T <.. repo.IndexColumn_virtual_referenced_setpoint
repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T <.. repo.IndexReferencedReferencing_HasFullColumnsInReferencing
repo.IndexColumn_virtual_referenced_setpoint <.. repo.check_IndexColumn_virtual_referenced_setpoint
repo.IndexColumn_virtual_referenced_setpoint <.. repo.usp_index_inheritance
repo.IndexReferencedReferencing_HasFullColumnsInReferencing <.. repo.usp_index_inheritance
repo.RepoObject_ColumnList <.. repo.RepoObject_SqlCreateTable
repo.RepoObject_ColumnList <.. repo.RepoObject_gross2
repo.RepoObject_gross2 <.. uspgenerator.GeneratorUspStep_Persistence
repo.RepoObject_gross2 <.. docs.RepoObject_Adoc
repo.RepoObject_gross2 <.. property.RepoObjectProperty_Collect_source_ROGross
repo.RepoObject_SqlCreateTable <.. reference.ftv_RepoObject_ColumReferenceRepoObject
repo.RepoObjectColumn_gross <.. reference.RepoObjectColumn_reference_FirstResultSet
repo.RepoObjectColumn_gross <.. reference.RepoObjectColumn_reference_QueryPlan
repo.RepoObjectColumn_gross <.. repo.usp_sync_guid_RepoObjectColumn
repo.RepoObjectColumn_gross <.. graph.RepoObjectColumn_S
repo.RepoObjectColumn_gross <.. property.RepoObjectColumnProperty_ForUpdate
repo.RepoObjectColumn_gross <.. reference.RepoObjectColumn_reference_virtual
repo.RepoObjectColumn_gross <.. reference.usp_RepoObjectColumnSource_virtual_set
repo.RepoObjectColumn_gross <.. repo.RepoObjectColumn_gross2
repo.RepoObjectColumn_gross2 <.. repo.RepoObject_ColumnList
repo.RepoObjectColumn_gross2 <.. docs.RepoObject_ColumnList
repo.usp_index_inheritance <.. repo.usp_main
repo.usp_PERSIST_IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T <.. repo.usp_index_inheritance
repo.usp_sync_guid <.. repo.usp_persistence_set
repo.usp_sync_guid <.. repo.usp_main
repo.usp_sync_guid_RepoObjectColumn <.. repo.usp_sync_guid
ssas.model_json_3111_tables_columns_descriptions_multiline <.. ssas.model_json_31111_tables_columns_descriptions_StrAgg
ssas.model_json_31111_tables_columns_descriptions_StrAgg <.. repo.RepoObjectColumn_gross
uspgenerator.GeneratorUspStep_Persistence <.. uspgenerator.usp_GeneratorUsp_insert_update_persistence
uspgenerator.usp_GeneratorUsp_insert_update_persistence <.. repo.usp_main
