'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity workflow.Biml_Package << V >> {
  --
}

entity workflow.Biml_PrecedenceConstraints << V >> {
  --
}

entity workflow.Biml_Project << V >> {
  --
}

entity workflow.Biml_Task << V >> {
  --
}

entity workflow.usp_PERSIST_Workflow_ProcedureDependency_T << P >> {
  --
}

entity workflow.usp_PERSIST_Workflow_ProcedureDependency_T_bidirectional_T << P >> {
  --
}

entity workflow.usp_workflow << P >> {
  --
}

entity workflow.Workflow_ProcedureDependency << V >> {
  --
}

entity workflow.Workflow_ProcedureDependency_T << U >> {
  * **Workflow_id** : int
  * **referenced_Procedure_RepoObject_guid** : uniqueidentifier
  * **referencing_Procedure_RepoObject_guid** : uniqueidentifier
  --
}

entity workflow.Workflow_ProcedureDependency_T_active << V >> {
  --
}

entity workflow.Workflow_ProcedureDependency_T_bidirectional << V >> {
  * **Workflow_id** : int
  * **referenced_Procedure_RepoObject_guid** : uniqueidentifier
  * **referencing_Procedure_RepoObject_guid** : uniqueidentifier
  --
}

entity workflow.Workflow_ProcedureDependency_T_bidirectional_T << U >> {
  * **Workflow_id** : int
  * **referenced_Procedure_RepoObject_guid** : uniqueidentifier
  * **referencing_Procedure_RepoObject_guid** : uniqueidentifier
  --
}

entity workflow.Workflow_ProcedureDependency_T_NotInSortorder << V >> {
  --
}

entity workflow.Workflow_ProcedureDependency_T_NotInSortorder_check << V >> {
  --
}

entity workflow.Workflow_ProcedureDependency_T_redundant << V >> {
  --
}

entity workflow.Workflow_ProcedureDependency_T_TaskName << V >> {
  --
}

entity workflow.Workflow_ProcedureDependency_wo_redundant << V >> {
  --
}

workflow.Biml_Package <.. workflow.Biml_Project
workflow.Biml_PrecedenceConstraints <.. workflow.Biml_Task
workflow.Biml_Task <.. workflow.Biml_Package
workflow.usp_PERSIST_Workflow_ProcedureDependency_T <.. workflow.usp_workflow
workflow.usp_PERSIST_Workflow_ProcedureDependency_T_bidirectional_T <.. workflow.usp_workflow
workflow.Workflow_ProcedureDependency <.. workflow.Workflow_ProcedureDependency_T
workflow.Workflow_ProcedureDependency <.. workflow.usp_PERSIST_Workflow_ProcedureDependency_T
workflow.Workflow_ProcedureDependency_T <.. workflow.usp_workflow
workflow.Workflow_ProcedureDependency_T <.. workflow.usp_PERSIST_Workflow_ProcedureDependency_T
workflow.Workflow_ProcedureDependency_T <.. workflow.Workflow_ProcedureDependency_T_active
workflow.Workflow_ProcedureDependency_T <.. workflow.Workflow_ProcedureDependency_T_bidirectional
workflow.Workflow_ProcedureDependency_T_active <.. workflow.Workflow_ProcedureDependency_T_redundant
workflow.Workflow_ProcedureDependency_T_active <.. workflow.Workflow_ProcedureDependency_T_TaskName
workflow.Workflow_ProcedureDependency_T_active <.. workflow.Workflow_ProcedureDependency_T_NotInSortorder
workflow.Workflow_ProcedureDependency_T_bidirectional <.. workflow.Workflow_ProcedureDependency_T_bidirectional_T
workflow.Workflow_ProcedureDependency_T_bidirectional <.. workflow.usp_PERSIST_Workflow_ProcedureDependency_T_bidirectional_T
workflow.Workflow_ProcedureDependency_T_bidirectional_T <.. workflow.usp_PERSIST_Workflow_ProcedureDependency_T_bidirectional_T
workflow.Workflow_ProcedureDependency_T_NotInSortorder <.. workflow.usp_workflow
workflow.Workflow_ProcedureDependency_T_NotInSortorder <.. workflow.Workflow_ProcedureDependency_T_NotInSortorder_check
workflow.Workflow_ProcedureDependency_T_redundant <.. workflow.usp_workflow
workflow.Workflow_ProcedureDependency_T_redundant <.. workflow.Workflow_ProcedureDependency_wo_redundant
workflow.Workflow_ProcedureDependency_T_TaskName <.. workflow.Biml_PrecedenceConstraints
