@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity "[[{site-url}/{page-component-name}/{page-component-version}/{page-module}/workflow.Biml_Package.html workflow.Biml_Package]]" as workflow.Biml_Package << V >> {
  --
}

entity "[[{site-url}/{page-component-name}/{page-component-version}/{page-module}/workflow.Biml_PrecedenceConstraints.html workflow.Biml_PrecedenceConstraints]]" as workflow.Biml_PrecedenceConstraints << V >> {
  --
}

entity "[[{site-url}/{page-component-name}/{page-component-version}/{page-module}/workflow.Biml_Project.html workflow.Biml_Project]]" as workflow.Biml_Project << V >> {
  --
}

entity "[[{site-url}/{page-component-name}/{page-component-version}/{page-module}/workflow.Biml_Task.html workflow.Biml_Task]]" as workflow.Biml_Task << V >> {
  --
}

entity "[[{site-url}/{page-component-name}/{page-component-version}/{page-module}/workflow.usp_PERSIST_Workflow_ProcedureDependency_T.html workflow.usp_PERSIST_Workflow_ProcedureDependency_T]]" as workflow.usp_PERSIST_Workflow_ProcedureDependency_T << P >> {
  --
}

entity "[[{site-url}/{page-component-name}/{page-component-version}/{page-module}/workflow.usp_PERSIST_Workflow_ProcedureDependency_T_bidirectional_T.html workflow.usp_PERSIST_Workflow_ProcedureDependency_T_bidirectional_T]]" as workflow.usp_PERSIST_Workflow_ProcedureDependency_T_bidirectional_T << P >> {
  --
}

entity "[[{site-url}/{page-component-name}/{page-component-version}/{page-module}/workflow.usp_PERSIST_WorkflowStep.html workflow.usp_PERSIST_WorkflowStep]]" as workflow.usp_PERSIST_WorkflowStep << P >> {
  --
}

entity "[[{site-url}/{page-component-name}/{page-component-version}/{page-module}/workflow.usp_workflow.html workflow.usp_workflow]]" as workflow.usp_workflow << P >> {
  --
}

entity "[[{site-url}/{page-component-name}/{page-component-version}/{page-module}/workflow.Workflow_ProcedureDependency.html workflow.Workflow_ProcedureDependency]]" as workflow.Workflow_ProcedureDependency << V >> {
  --
}

entity "[[{site-url}/{page-component-name}/{page-component-version}/{page-module}/workflow.Workflow_ProcedureDependency_all.html workflow.Workflow_ProcedureDependency_all]]" as workflow.Workflow_ProcedureDependency_all << V >> {
  --
}

entity "[[{site-url}/{page-component-name}/{page-component-version}/{page-module}/workflow.Workflow_ProcedureDependency_T.html workflow.Workflow_ProcedureDependency_T]]" as workflow.Workflow_ProcedureDependency_T << U >> {
  - **Workflow_id** : (int)
  - **referenced_Procedure_RepoObject_guid** : (uniqueidentifier)
  - **referencing_Procedure_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "[[{site-url}/{page-component-name}/{page-component-version}/{page-module}/workflow.Workflow_ProcedureDependency_T_active.html workflow.Workflow_ProcedureDependency_T_active]]" as workflow.Workflow_ProcedureDependency_T_active << V >> {
  --
}

entity "[[{site-url}/{page-component-name}/{page-component-version}/{page-module}/workflow.Workflow_ProcedureDependency_T_bidirectional.html workflow.Workflow_ProcedureDependency_T_bidirectional]]" as workflow.Workflow_ProcedureDependency_T_bidirectional << V >> {
  - **Workflow_id** : (int)
  - **referenced_Procedure_RepoObject_guid** : (uniqueidentifier)
  - **referencing_Procedure_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "[[{site-url}/{page-component-name}/{page-component-version}/{page-module}/workflow.Workflow_ProcedureDependency_T_bidirectional_T.html workflow.Workflow_ProcedureDependency_T_bidirectional_T]]" as workflow.Workflow_ProcedureDependency_T_bidirectional_T << U >> {
  - **Workflow_id** : (int)
  - **referenced_Procedure_RepoObject_guid** : (uniqueidentifier)
  - **referencing_Procedure_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "[[{site-url}/{page-component-name}/{page-component-version}/{page-module}/workflow.Workflow_ProcedureDependency_T_NotInSortorder.html workflow.Workflow_ProcedureDependency_T_NotInSortorder]]" as workflow.Workflow_ProcedureDependency_T_NotInSortorder << V >> {
  --
}

entity "[[{site-url}/{page-component-name}/{page-component-version}/{page-module}/workflow.Workflow_ProcedureDependency_T_NotInSortorder_check.html workflow.Workflow_ProcedureDependency_T_NotInSortorder_check]]" as workflow.Workflow_ProcedureDependency_T_NotInSortorder_check << V >> {
  --
}

entity "[[{site-url}/{page-component-name}/{page-component-version}/{page-module}/workflow.Workflow_ProcedureDependency_T_redundant.html workflow.Workflow_ProcedureDependency_T_redundant]]" as workflow.Workflow_ProcedureDependency_T_redundant << V >> {
  --
}

entity "[[{site-url}/{page-component-name}/{page-component-version}/{page-module}/workflow.Workflow_ProcedureDependency_T_TaskName.html workflow.Workflow_ProcedureDependency_T_TaskName]]" as workflow.Workflow_ProcedureDependency_T_TaskName << V >> {
  --
}

entity "[[{site-url}/{page-component-name}/{page-component-version}/{page-module}/workflow.Workflow_ProcedureDependency_wo_redundant.html workflow.Workflow_ProcedureDependency_wo_redundant]]" as workflow.Workflow_ProcedureDependency_wo_redundant << V >> {
  --
}

entity "[[{site-url}/{page-component-name}/{page-component-version}/{page-module}/workflow.WorkflowStep.html workflow.WorkflowStep]]" as workflow.WorkflowStep << U >> {
  - **id** : (int)
  --
}

entity "[[{site-url}/{page-component-name}/{page-component-version}/{page-module}/workflow.WorkflowStep_active.html workflow.WorkflowStep_active]]" as workflow.WorkflowStep_active << V >> {
  --
}

entity "[[{site-url}/{page-component-name}/{page-component-version}/{page-module}/workflow.WorkflowStep_ForUpdate.html workflow.WorkflowStep_ForUpdate]]" as workflow.WorkflowStep_ForUpdate << V >> {
  --
}

entity "[[{site-url}/{page-component-name}/{page-component-version}/{page-module}/workflow.WorkflowStep_S.html workflow.WorkflowStep_S]]" as workflow.WorkflowStep_S << V >> {
  - **Workflow_id** : (int)
  **Procedure_RepoObject_guid** : (uniqueidentifier)
  --
}

workflow.Biml_Package <.. workflow.Biml_Project
workflow.Biml_PrecedenceConstraints <.. workflow.Biml_Task
workflow.Biml_Task <.. workflow.Biml_Package
workflow.usp_PERSIST_Workflow_ProcedureDependency_T <.. workflow.usp_workflow
workflow.usp_PERSIST_Workflow_ProcedureDependency_T_bidirectional_T <.. workflow.usp_workflow
workflow.usp_PERSIST_WorkflowStep <.. workflow.usp_workflow
workflow.Workflow_ProcedureDependency <.. workflow.Workflow_ProcedureDependency_T
workflow.Workflow_ProcedureDependency <.. workflow.usp_PERSIST_Workflow_ProcedureDependency_T
workflow.Workflow_ProcedureDependency_all <.. workflow.Workflow_ProcedureDependency_wo_redundant
workflow.Workflow_ProcedureDependency_T <.. workflow.usp_workflow
workflow.Workflow_ProcedureDependency_T <.. workflow.usp_PERSIST_Workflow_ProcedureDependency_T
workflow.Workflow_ProcedureDependency_T <.. workflow.Workflow_ProcedureDependency_T_active
workflow.Workflow_ProcedureDependency_T <.. workflow.Workflow_ProcedureDependency_T_bidirectional
workflow.Workflow_ProcedureDependency_T_active <.. workflow.Workflow_ProcedureDependency_T_redundant
workflow.Workflow_ProcedureDependency_T_active <.. workflow.Workflow_ProcedureDependency_T_TaskName
workflow.Workflow_ProcedureDependency_T_active <.. workflow.Workflow_ProcedureDependency_T_NotInSortorder
workflow.Workflow_ProcedureDependency_T_bidirectional <.. workflow.Workflow_ProcedureDependency_T_bidirectional_T
workflow.Workflow_ProcedureDependency_T_bidirectional <.. workflow.usp_PERSIST_Workflow_ProcedureDependency_T_bidirectional_T
workflow.Workflow_ProcedureDependency_T_bidirectional_T <.. workflow.usp_PERSIST_Workflow_ProcedureDependency_T_bidirectional_T
workflow.Workflow_ProcedureDependency_T_NotInSortorder <.. workflow.usp_workflow
workflow.Workflow_ProcedureDependency_T_NotInSortorder <.. workflow.Workflow_ProcedureDependency_T_NotInSortorder_check
workflow.Workflow_ProcedureDependency_T_redundant <.. workflow.usp_workflow
workflow.Workflow_ProcedureDependency_T_redundant <.. workflow.Workflow_ProcedureDependency_wo_redundant
workflow.Workflow_ProcedureDependency_T_TaskName <.. workflow.Biml_PrecedenceConstraints
workflow.WorkflowStep <.. workflow.WorkflowStep_active
workflow.WorkflowStep <.. workflow.usp_PERSIST_WorkflowStep
workflow.WorkflowStep <.. workflow.WorkflowStep_ForUpdate
workflow.WorkflowStep_active <.. workflow.usp_workflow
workflow.WorkflowStep_active <.. workflow.Workflow_ProcedureDependency_all
workflow.WorkflowStep_active <.. workflow.Biml_Task
workflow.WorkflowStep_active <.. workflow.Workflow_ProcedureDependency
workflow.WorkflowStep_active <.. workflow.Workflow_ProcedureDependency_T_active
workflow.WorkflowStep_S <.. workflow.WorkflowStep
workflow.WorkflowStep_S <.. workflow.usp_PERSIST_WorkflowStep
footer
to view a reduced diagram in original size and to be able to click on the links:
open the diagram in a new tab via the Context menu.
end footer

@enduml

