@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity "puml-link:workflow.Biml_Package.adoc[prefix=..]" as workflow.Biml_Package << V >> {
  --
}

entity "puml-link:workflow.Biml_PrecedenceConstraints.adoc[prefix=..]" as workflow.Biml_PrecedenceConstraints << V >> {
  --
}

entity "puml-link:workflow.Biml_Project.adoc[prefix=..]" as workflow.Biml_Project << V >> {
  --
}

entity "puml-link:workflow.Biml_Task.adoc[prefix=..]" as workflow.Biml_Task << V >> {
  --
}

entity "puml-link:workflow.usp_PERSIST_Workflow_ProcedureDependency_T.adoc[prefix=..]" as workflow.usp_PERSIST_Workflow_ProcedureDependency_T << P >> {
  --
}

entity "puml-link:workflow.usp_PERSIST_Workflow_ProcedureDependency_T_bidirectional_T.adoc[prefix=..]" as workflow.usp_PERSIST_Workflow_ProcedureDependency_T_bidirectional_T << P >> {
  --
}

entity "puml-link:workflow.usp_PERSIST_WorkflowStep.adoc[prefix=..]" as workflow.usp_PERSIST_WorkflowStep << P >> {
  --
}

entity "puml-link:workflow.usp_workflow.adoc[prefix=..]" as workflow.usp_workflow << P >> {
  --
}

entity "puml-link:workflow.Workflow.adoc[prefix=..]" as workflow.Workflow << U >> {
  - **id** : (int)
  --
}

entity "puml-link:workflow.Workflow_ProcedureDependency.adoc[prefix=..]" as workflow.Workflow_ProcedureDependency << V >> {
  --
}

entity "puml-link:workflow.Workflow_ProcedureDependency_all.adoc[prefix=..]" as workflow.Workflow_ProcedureDependency_all << V >> {
  --
}

entity "puml-link:workflow.Workflow_ProcedureDependency_T.adoc[prefix=..]" as workflow.Workflow_ProcedureDependency_T << U >> {
  - **Workflow_id** : (int)
  - **referenced_Procedure_RepoObject_guid** : (uniqueidentifier)
  - **referencing_Procedure_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:workflow.Workflow_ProcedureDependency_T_active.adoc[prefix=..]" as workflow.Workflow_ProcedureDependency_T_active << V >> {
  --
}

entity "puml-link:workflow.Workflow_ProcedureDependency_T_bidirectional.adoc[prefix=..]" as workflow.Workflow_ProcedureDependency_T_bidirectional << V >> {
  - **Workflow_id** : (int)
  - **referenced_Procedure_RepoObject_guid** : (uniqueidentifier)
  - **referencing_Procedure_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:workflow.Workflow_ProcedureDependency_T_bidirectional_T.adoc[prefix=..]" as workflow.Workflow_ProcedureDependency_T_bidirectional_T << U >> {
  - **Workflow_id** : (int)
  - **referenced_Procedure_RepoObject_guid** : (uniqueidentifier)
  - **referencing_Procedure_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:workflow.Workflow_ProcedureDependency_T_NotInSortorder.adoc[prefix=..]" as workflow.Workflow_ProcedureDependency_T_NotInSortorder << V >> {
  --
}

entity "puml-link:workflow.Workflow_ProcedureDependency_T_NotInSortorder_check.adoc[prefix=..]" as workflow.Workflow_ProcedureDependency_T_NotInSortorder_check << V >> {
  --
}

entity "puml-link:workflow.Workflow_ProcedureDependency_T_redundant.adoc[prefix=..]" as workflow.Workflow_ProcedureDependency_T_redundant << V >> {
  --
}

entity "puml-link:workflow.Workflow_ProcedureDependency_T_TaskName.adoc[prefix=..]" as workflow.Workflow_ProcedureDependency_T_TaskName << V >> {
  --
}

entity "puml-link:workflow.Workflow_ProcedureDependency_wo_redundant.adoc[prefix=..]" as workflow.Workflow_ProcedureDependency_wo_redundant << V >> {
  --
}

entity "puml-link:workflow.Workflow_SqlUsp.adoc[prefix=..]" as workflow.Workflow_SqlUsp << V >> {
  --
}

entity "puml-link:workflow.Workflow_UspList.adoc[prefix=..]" as workflow.Workflow_UspList << V >> {
  --
}

entity "puml-link:workflow.WorkflowStep.adoc[prefix=..]" as workflow.WorkflowStep << U >> {
  - **id** : (int)
  --
}

entity "puml-link:workflow.WorkflowStep_active.adoc[prefix=..]" as workflow.WorkflowStep_active << V >> {
  --
}

entity "puml-link:workflow.WorkflowStep_ForUpdate.adoc[prefix=..]" as workflow.WorkflowStep_ForUpdate << V >> {
  --
}

entity "puml-link:workflow.WorkflowStep_S.adoc[prefix=..]" as workflow.WorkflowStep_S << V >> {
  - **Workflow_id** : (int)
  **Procedure_RepoObject_guid** : (uniqueidentifier)
  --
}

workflow.Biml_Package <.. workflow.Biml_Project
workflow.Biml_PrecedenceConstraints <.. workflow.Biml_Task
workflow.Biml_Task <.. workflow.Biml_Package
workflow.usp_PERSIST_Workflow_ProcedureDependency_T <.. workflow.usp_workflow
workflow.usp_PERSIST_Workflow_ProcedureDependency_T_bidirectional_T <.. workflow.usp_workflow
workflow.usp_PERSIST_WorkflowStep <.. workflow.usp_workflow
workflow.Workflow <.. workflow.WorkflowStep_active
workflow.Workflow <.. workflow.WorkflowStep_S
workflow.Workflow <.. workflow.Workflow_ProcedureDependency_all
workflow.Workflow <.. workflow.WorkflowStep_ForUpdate
workflow.Workflow <.. workflow.Biml_Package
workflow.Workflow <.. workflow.Workflow_ProcedureDependency
workflow.Workflow <.. workflow.Workflow_UspList
workflow.Workflow_ProcedureDependency <.. workflow.Workflow_ProcedureDependency_T
workflow.Workflow_ProcedureDependency <.. workflow.usp_PERSIST_Workflow_ProcedureDependency_T
workflow.Workflow_ProcedureDependency_all <.. workflow.Workflow_ProcedureDependency_wo_redundant
workflow.Workflow_ProcedureDependency_T <.. workflow.usp_workflow
workflow.Workflow_ProcedureDependency_T <.. workflow.usp_PERSIST_Workflow_ProcedureDependency_T
workflow.Workflow_ProcedureDependency_T <.. workflow.Workflow_ProcedureDependency_T_active
workflow.Workflow_ProcedureDependency_T <.. workflow.Workflow_ProcedureDependency_T_bidirectional
workflow.Workflow_ProcedureDependency_T_active <.. workflow.Workflow_ProcedureDependency_T_redundant
workflow.Workflow_ProcedureDependency_T_active <.. workflow.Workflow_ProcedureDependency_T_TaskName
workflow.Workflow_ProcedureDependency_T_active <.. workflow.Workflow_ProcedureDependency_T_NotInSortorder
workflow.Workflow_ProcedureDependency_T_bidirectional <.. workflow.Workflow_ProcedureDependency_T_bidirectional_T
workflow.Workflow_ProcedureDependency_T_bidirectional <.. workflow.usp_PERSIST_Workflow_ProcedureDependency_T_bidirectional_T
workflow.Workflow_ProcedureDependency_T_bidirectional_T <.. workflow.usp_PERSIST_Workflow_ProcedureDependency_T_bidirectional_T
workflow.Workflow_ProcedureDependency_T_NotInSortorder <.. workflow.usp_workflow
workflow.Workflow_ProcedureDependency_T_NotInSortorder <.. workflow.Workflow_ProcedureDependency_T_NotInSortorder_check
workflow.Workflow_ProcedureDependency_T_redundant <.. workflow.usp_workflow
workflow.Workflow_ProcedureDependency_T_redundant <.. workflow.Workflow_ProcedureDependency_wo_redundant
workflow.Workflow_ProcedureDependency_T_TaskName <.. workflow.Biml_PrecedenceConstraints
workflow.Workflow_UspList <.. workflow.Workflow_SqlUsp
workflow.WorkflowStep <.. workflow.WorkflowStep_active
workflow.WorkflowStep <.. workflow.usp_PERSIST_WorkflowStep
workflow.WorkflowStep <.. workflow.WorkflowStep_ForUpdate
workflow.WorkflowStep_active <.. workflow.usp_workflow
workflow.WorkflowStep_active <.. workflow.Workflow_ProcedureDependency_all
workflow.WorkflowStep_active <.. workflow.Biml_Task
workflow.WorkflowStep_active <.. workflow.Workflow_ProcedureDependency
workflow.WorkflowStep_active <.. workflow.Workflow_ProcedureDependency_T_active
workflow.WorkflowStep_S <.. workflow.WorkflowStep
workflow.WorkflowStep_S <.. workflow.usp_PERSIST_WorkflowStep
footer
to view a reduced diagram in original size and to be able to click on the links:
open the diagram in a new tab via the Context menu.
end footer

@enduml

