// tag::HeaderFullDisplayName[]
= configT.SsasDmvTableImport_ImportSql - V
// end::HeaderFullDisplayName[]

== existing_properties

// tag::existing_properties[]

:ExistsProperty--antorareferencedlist:
:ExistsProperty--description:
:ExistsProperty--is_repo_managed:
:ExistsProperty--is_ssas:
:ExistsProperty--referencedobjectlist:
:ExistsProperty--sql_modules_definition:
:ExistsProperty--FK:
:ExistsProperty--AntoraIndexList:
:ExistsProperty--Columns:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
DAE6A70A-8A06-EC11-8515-A81E8446D5B0
// end::RepoObject_guid[]

== RepoObject_FullDisplayName2

// tag::RepoObject_FullDisplayName2[]
configT.SsasDmvTableImport_ImportSql
// end::RepoObject_FullDisplayName2[]

== SysObject_type

// tag::SysObject_type[]
V 
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
view
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
1197963344
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2021-10-03 16:16:35
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]
[discrete]
== _


[#column-databasename]
=== databasename

[cols="d,8a,m,m,m"]
|===
|
|databasename
|nvarchar(128)
|NOT NULL
|
|===

.Referenced Columns
--
* xref:config.ssasdatabasename.adoc#column-databasename[+config.SsasDatabasename.databasename+]
--


[#column-deleteinsertsql]
=== DeleteInsertSql

[cols="d,8a,m,m,m"]
|===
|
|DeleteInsertSql
|nvarchar(4000)
|NOT NULL
|
|===


[#column-execpersistsql]
=== ExecPersistSql

[cols="d,8a,m,m,m"]
|===
|
|ExecPersistSql
|nvarchar(161)
|NOT NULL
|
|===


[#column-isactive]
=== isActive

[cols="d,8a,m,m,m"]
|===
|
|isActive
|bit
|NOT NULL
|
|===

.Referenced Columns
--
* xref:config.ssasdatabasename.adoc#column-isactive[+config.SsasDatabasename.isActive+]
--


[#column-iscurrentimport]
=== isCurrentImport

[cols="d,8a,m,m,m"]
|===
|
|isCurrentImport
|bit
|NOT NULL
|
|===

.Referenced Columns
--
* xref:config.ssasdatabasename.adoc#column-iscurrentimport[+config.SsasDatabasename.isCurrentImport+]
--


[#column-linkedserver]
=== LinkedServer

[cols="d,8a,m,m,m"]
|===
|
|LinkedServer
|nvarchar(128)
|NOT NULL
|
|===

.Referenced Columns
--
* xref:config.ssasdatabasename.adoc#column-linkedserver[+config.SsasDatabasename.LinkedServer+]
--


[#column-truncatesql]
=== truncateSql

[cols="d,8a,m,m,m"]
|===
|
|truncateSql
|nvarchar(156)
|NOT NULL
|
|===


// end::AntoraColumnDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]







// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]
|
|<<column-databasename>>
|nvarchar(128)
|NOT NULL
|

|
|<<column-deleteinsertsql>>
|nvarchar(4000)
|NOT NULL
|

|
|<<column-execpersistsql>>
|nvarchar(161)
|NOT NULL
|

|
|<<column-isactive>>
|bit
|NOT NULL
|

|
|<<column-iscurrentimport>>
|bit
|NOT NULL
|

|
|<<column-linkedserver>>
|nvarchar(128)
|NOT NULL
|

|
|<<column-truncatesql>>
|nvarchar(156)
|NOT NULL
|

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

[#index-idxunderlinessasdmvtableimportunderlineimportsqlunderlineunderline1]
=== idx_SsasDmvTableImport_ImportSql++__++1

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-databasename>>; nvarchar(128)
--
* PK, Unique, Real: 0, 0, 0

// end::AntoraIndexList[]

== AntoraMeasureDetails

// tag::AntoraMeasureDetails[]

// end::AntoraMeasureDetails[]

== AntoraMeasureDescriptions



== AntoraParameterList

// tag::AntoraParameterList[]

// end::AntoraParameterList[]

== AntoraXrefCulturesList

// tag::AntoraXrefCulturesList[]
* xref:dhw:sqldb:configt.ssasdmvtableimport_importsql.adoc[] - 
// end::AntoraXrefCulturesList[]

== cultures_count

// tag::cultures_count[]
1
// end::cultures_count[]

== Other tags

source: property.RepoObjectProperty_cross As rop_cross


=== additional_reference_csv

// tag::additional_reference_csv[]

// end::additional_reference_csv[]


=== AdocUspSteps

// tag::adocuspsteps[]

// end::adocuspsteps[]


=== AntoraReferencedList

// tag::antorareferencedlist[]
* xref:dhw:sqldb:config.ssasdatabasename.adoc[]
* xref:dhw:sqldb:configt.ssasdmvtableimport_dmvcolumnlist.adoc[]
// end::antorareferencedlist[]


=== AntoraReferencingList

// tag::antorareferencinglist[]

// end::antorareferencinglist[]


=== Description

// tag::description[]

obsolet

* we could truncate once and import all
* or we could use the [isCurrentImport] and loop through aktive databasename and import them one by one

todo:

* ExecPersistSql only, if persistence exists
// end::description[]


=== exampleUsage

// tag::exampleusage[]

// end::exampleusage[]


=== exampleUsage_2

// tag::exampleusage_2[]

// end::exampleusage_2[]


=== exampleUsage_3

// tag::exampleusage_3[]

// end::exampleusage_3[]


=== exampleUsage_4

// tag::exampleusage_4[]

// end::exampleusage_4[]


=== exampleUsage_5

// tag::exampleusage_5[]

// end::exampleusage_5[]


=== exampleWrong_Usage

// tag::examplewrong_usage[]

// end::examplewrong_usage[]


=== has_execution_plan_issue

// tag::has_execution_plan_issue[]

// end::has_execution_plan_issue[]


=== has_get_referenced_issue

// tag::has_get_referenced_issue[]

// end::has_get_referenced_issue[]


=== has_history

// tag::has_history[]

// end::has_history[]


=== has_history_columns

// tag::has_history_columns[]

// end::has_history_columns[]


=== InheritanceType

// tag::inheritancetype[]

// end::inheritancetype[]


=== is_persistence

// tag::is_persistence[]

// end::is_persistence[]


=== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]

// end::is_persistence_check_duplicate_per_pk[]


=== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]

// end::is_persistence_check_for_empty_source[]


=== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]

// end::is_persistence_delete_changed[]


=== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]

// end::is_persistence_delete_missing[]


=== is_persistence_insert

// tag::is_persistence_insert[]

// end::is_persistence_insert[]


=== is_persistence_truncate

// tag::is_persistence_truncate[]

// end::is_persistence_truncate[]


=== is_persistence_update_changed

// tag::is_persistence_update_changed[]

// end::is_persistence_update_changed[]


=== is_repo_managed

// tag::is_repo_managed[]
0
// end::is_repo_managed[]


=== is_ssas

// tag::is_ssas[]
0
// end::is_ssas[]


=== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


=== MS_Description

// tag::ms_description[]

// end::ms_description[]


=== persistence_source_RepoObject_fullname

// tag::persistence_source_repoobject_fullname[]

// end::persistence_source_repoobject_fullname[]


=== persistence_source_RepoObject_fullname2

// tag::persistence_source_repoobject_fullname2[]

// end::persistence_source_repoobject_fullname2[]


=== persistence_source_RepoObject_guid

// tag::persistence_source_repoobject_guid[]

// end::persistence_source_repoobject_guid[]


=== persistence_source_RepoObject_xref

// tag::persistence_source_repoobject_xref[]

// end::persistence_source_repoobject_xref[]


=== pk_index_guid

// tag::pk_index_guid[]

// end::pk_index_guid[]


=== pk_IndexPatternColumnDatatype

// tag::pk_indexpatterncolumndatatype[]

// end::pk_indexpatterncolumndatatype[]


=== pk_IndexPatternColumnName

// tag::pk_indexpatterncolumnname[]

// end::pk_indexpatterncolumnname[]


=== pk_IndexSemanticGroup

// tag::pk_indexsemanticgroup[]

// end::pk_indexsemanticgroup[]


=== ReferencedObjectList

// tag::referencedobjectlist[]
* [config].[SsasDatabasename]
* [configT].[SsasDmvTableImport_DmvColumnList]
// end::referencedobjectlist[]


=== usp_persistence_RepoObject_guid

// tag::usp_persistence_repoobject_guid[]

// end::usp_persistence_repoobject_guid[]


=== UspExamples

// tag::uspexamples[]

// end::uspexamples[]


=== uspgenerator_usp_id

// tag::uspgenerator_usp_id[]

// end::uspgenerator_usp_id[]


=== UspParameters

// tag::uspparameters[]

// end::uspparameters[]

== Boolean Attributes

source: property.RepoObjectProperty WHERE property_int = 1

// tag::boolean_attributes[]


// end::boolean_attributes[]

== PlantUML diagrams

=== PlantUML Entity

// tag::puml_entity[]
[plantuml, entity-{docname}, svg, subs=macros]
....
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:configt.ssasdmvtableimport_importsql.adoc[]" as configT.SsasDmvTableImport_ImportSql << V >> {
  - databasename : (nvarchar(128))
  - DeleteInsertSql : (nvarchar(4000))
  - ExecPersistSql : (nvarchar(161))
  - isActive : (bit)
  - isCurrentImport : (bit)
  - LinkedServer : (nvarchar(128))
  - truncateSql : (nvarchar(156))
  --
}
....

// end::puml_entity[]

=== PlantUML Entity 1 1 FK

// tag::puml_entity_1_1_fk[]
[plantuml, entity_1_1_fk-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:configt.ssasdmvtableimport_importsql.adoc[]" as configT.SsasDmvTableImport_ImportSql << V >> {
- idx_SsasDmvTableImport_ImportSql__1

..
databasename; nvarchar(128)
}



footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_fk[]

=== PlantUML 1 1 ObjectRef

// tag::puml_entity_1_1_objectref[]
[plantuml, entity_1_1_objectref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:config.ssasdatabasename.adoc[]" as config.SsasDatabasename << U >> {
  - **databasename** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:configt.ssasdmvtableimport_dmvcolumnlist.adoc[]" as configT.SsasDmvTableImport_DmvColumnList << V >> {
  --
}

entity "puml-link:dhw:sqldb:configt.ssasdmvtableimport_importsql.adoc[]" as configT.SsasDmvTableImport_ImportSql << V >> {
  --
}

config.SsasDatabasename <.. configT.SsasDmvTableImport_ImportSql
configT.SsasDmvTableImport_DmvColumnList <.. configT.SsasDmvTableImport_ImportSql

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_objectref[]

=== PlantUML 30 0 ObjectRef

// tag::puml_entity_30_0_objectref[]
[plantuml, entity_30_0_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:config.ssasdatabasename.adoc[]" as config.SsasDatabasename << U >> {
  - **databasename** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:configt.ssasdmvtableimport.adoc[]" as configT.SsasDmvTableImport << V >> {
  --
}

entity "puml-link:dhw:sqldb:configt.ssasdmvtableimport_dmvcolumnlist.adoc[]" as configT.SsasDmvTableImport_DmvColumnList << V >> {
  --
}

entity "puml-link:dhw:sqldb:configt.ssasdmvtableimport_importsql.adoc[]" as configT.SsasDmvTableImport_ImportSql << V >> {
  --
}

config.SsasDatabasename <.. configT.SsasDmvTableImport_ImportSql
configT.SsasDmvTableImport <.. configT.SsasDmvTableImport_DmvColumnList
configT.SsasDmvTableImport_DmvColumnList <.. configT.SsasDmvTableImport_ImportSql

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_30_0_objectref[]

=== PlantUML 0 30 ObjectRef

// tag::puml_entity_0_30_objectref[]
[plantuml, entity_0_30_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:configt.ssasdmvtableimport_importsql.adoc[]" as configT.SsasDmvTableImport_ImportSql << V >> {
  --
}



footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_0_30_objectref[]

=== PlantUML 1 1 ColumnRef

// tag::puml_entity_1_1_colref[]
[plantuml, entity_1_1_colref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:config.ssasdatabasename.adoc[]" as config.SsasDatabasename << U >> {
  - **databasename** : (nvarchar(128))
  - isActive : (bit)
  - isCurrentImport : (bit)
  - LinkedServer : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:configt.ssasdmvtableimport_dmvcolumnlist.adoc[]" as configT.SsasDmvTableImport_DmvColumnList << V >> {
  DmvColumnList : (nvarchar(4000))
  DmvTableName : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:configt.ssasdmvtableimport_importsql.adoc[]" as configT.SsasDmvTableImport_ImportSql << V >> {
  - databasename : (nvarchar(128))
  - DeleteInsertSql : (nvarchar(4000))
  - ExecPersistSql : (nvarchar(161))
  - isActive : (bit)
  - isCurrentImport : (bit)
  - LinkedServer : (nvarchar(128))
  - truncateSql : (nvarchar(156))
  --
}

config.SsasDatabasename <.. configT.SsasDmvTableImport_ImportSql
configT.SsasDmvTableImport_DmvColumnList <.. configT.SsasDmvTableImport_ImportSql
"config.SsasDatabasename::databasename" <-- "configT.SsasDmvTableImport_ImportSql::databasename"
"config.SsasDatabasename::isActive" <-- "configT.SsasDmvTableImport_ImportSql::isActive"
"config.SsasDatabasename::isCurrentImport" <-- "configT.SsasDmvTableImport_ImportSql::isCurrentImport"
"config.SsasDatabasename::LinkedServer" <-- "configT.SsasDmvTableImport_ImportSql::LinkedServer"

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_colref[]


== sql_modules_definition

// tag::sql_modules_definition[]
[%collapsible]
=======
[source,sql,numbered,indent=0]
----

/*
<<property_start>>Description
obsolet

* we could truncate once and import all
* or we could use the [isCurrentImport] and loop through aktive databasename and import them one by one

todo:

* ExecPersistSql only, if persistence exists
<<property_end>>
*/
CREATE   View [configT].[SsasDmvTableImport_ImportSql]
As
Select
    T2.databasename
  , T2.LinkedServer
  , T2.isActive
  , T2.isCurrentImport
  , DeleteInsertSql = Concat (
                                 'DELETE '
                               , Char ( 13 ) + Char ( 10 )
                               , 'ssas.'
                               , T1.DmvTableName
                               , Char ( 13 ) + Char ( 10 )
                               , 'WHERE databasename = ''' + T2.databasename + ''''
                               , Char ( 13 ) + Char ( 10 )
                               , 'GO'
                               , Char ( 13 ) + Char ( 10 )
                               , Char ( 13 ) + Char ( 10 )
                               , 'Insert Into '
                               , Char ( 13 ) + Char ( 10 )
                               , 'ssas.'
                               , T1.DmvTableName
                               , Char ( 13 ) + Char ( 10 )
                               , '('
                               , Char ( 13 ) + Char ( 10 )
                               , 'databasename'
                               , Char ( 13 ) + Char ( 10 )
                               , ', '
                               , T1.DmvColumnList
                               , Char ( 13 ) + Char ( 10 )
                               , ')'
                               , Char ( 13 ) + Char ( 10 )
                               , 'Select'
                               , Char ( 13 ) + Char ( 10 )
                               , '''' + T2.databasename + ''''
                               , Char ( 13 ) + Char ( 10 )
                               , ', '
                               , T1.DmvColumnList
                               , Char ( 13 ) + Char ( 10 )
                               , 'From'
                               , Char ( 13 ) + Char ( 10 )
                               , 'OpenQuery'
                               , Char ( 13 ) + Char ( 10 )
                               , '( '
                               , T2.LinkedServer
                               , ', '
                               , Char ( 13 ) + Char ( 10 )
                               , '''Select '
                               , Char ( 13 ) + Char ( 10 )
                               , '  '
                               , T1.DmvColumnList
                               , Char ( 13 ) + Char ( 10 )
                               , 'From $SYSTEM.'
                               , T1.DmvTableName
                               , ''''
                               , Char ( 13 ) + Char ( 10 )
                               , ')'
                               , Char ( 13 ) + Char ( 10 )
                               , 'GO'
                               , Char ( 13 ) + Char ( 10 )
                             )
  , ExecPersistSql     = Concat (
                                 'EXECUTE '
                               , 'ssas.usp_PERSIST_'
                               , T1.DmvTableName
                               , '_T'
                               , Char ( 13 ) + Char ( 10 )
                               , 'GO'
                               , Char ( 13 ) + Char ( 10 )
                             )
  , truncateSql     = Concat (
                                 'TRUNCATE TABLE '
                               , Char ( 13 ) + Char ( 10 )
                               , 'ssas.'
                               , T1.DmvTableName
                               , Char ( 13 ) + Char ( 10 )
                               , 'GO'
                               , Char ( 13 ) + Char ( 10 )
                             )
From
    configT.SsasDmvTableImport_DmvColumnList As T1
    --there could be more than one isActive database
    Cross Join config.SsasDatabasename       As T2
Where
    T2.isActive = 1

----
=======
// end::sql_modules_definition[]


