// tag::HeaderFullDisplayName[]
= configT.type_level1type_level2type - V
// end::HeaderFullDisplayName[]

== existing_properties

// tag::existing_properties[]

:ExistsProperty--antorareferencedlist:
:ExistsProperty--antorareferencinglist:
:ExistsProperty--description:
:ExistsProperty--is_repo_managed:
:ExistsProperty--is_ssas:
:ExistsProperty--pk_index_guid:
:ExistsProperty--pk_indexpatterncolumndatatype:
:ExistsProperty--pk_indexpatterncolumnname:
:ExistsProperty--referencedobjectlist:
:ExistsProperty--sql_modules_definition:
:ExistsProperty--FK:
:ExistsProperty--AntoraIndexList:
:ExistsProperty--Columns:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
DB8F291C-9D61-EB11-84DC-A81E8446D5B0
// end::RepoObject_guid[]

== RepoObject_FullDisplayName2

// tag::RepoObject_FullDisplayName2[]
configT.type_level1type_level2type
// end::RepoObject_FullDisplayName2[]

== SysObject_type

// tag::SysObject_type[]
V 
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
view
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
18099105
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2021-10-02 13:23:34
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]
[discrete]
== _


[#column-type]
=== type

[cols="d,8a,m,m,m"]
|===
|1
|*type*
|nvarchar(128)
|NULL
|
|===


[#column-level1type]
=== level1type

[cols="d,8a,m,m,m"]
|===
|
|level1type
|varchar(9)
|NULL
|
|===

.Referencing Columns
--
* xref:property.extendedproperty_repo2sys_level1.adoc#column-level1type[+property.ExtendedProperty_Repo2Sys_level1.level1type+]
* xref:property.extendedproperty_repo2sys_level2_repoobject.adoc#column-level1type[+property.ExtendedProperty_Repo2Sys_level2_RepoObject.level1type+]
* xref:property.extendedproperty_repo2sys_level2_repoobjectcolumn.adoc#column-level1type[+property.ExtendedProperty_Repo2Sys_level2_RepoObjectColumn.level1type+]
* xref:repo_sys.extendedproperties_parameterforaddupdatedrop.adoc#column-typeunderlinelevel1type[+repo_sys.ExtendedProperties_ParameterForAddUpdateDrop.type_level1type+]
* xref:sys_self.extendedproperties_parameterforaddupdatedrop.adoc#column-typeunderlinelevel1type[+sys_self.ExtendedProperties_ParameterForAddUpdateDrop.type_level1type+]
--


[#column-level2type]
=== level2type

[cols="d,8a,m,m,m"]
|===
|
|level2type
|varchar(10)
|NULL
|
|===

.Referencing Columns
--
* xref:property.extendedproperty_repo2sys_level1.adoc#column-level2type[+property.ExtendedProperty_Repo2Sys_level1.level2type+]
* xref:property.extendedproperty_repo2sys_level2_repoobject.adoc#column-level2type[+property.ExtendedProperty_Repo2Sys_level2_RepoObject.level2type+]
* xref:repo_sys.extendedproperties_parameterforaddupdatedrop.adoc#column-typeunderlinelevel2type[+repo_sys.ExtendedProperties_ParameterForAddUpdateDrop.type_level2type+]
* xref:sys_self.extendedproperties_parameterforaddupdatedrop.adoc#column-typeunderlinelevel2type[+sys_self.ExtendedProperties_ParameterForAddUpdateDrop.type_level2type+]
--


[#column-typeunderlinedesc]
=== type_desc

[cols="d,8a,m,m,m"]
|===
|
|type_desc
|nvarchar(128)
|NULL
|
|===

.Referenced Columns
--
* xref:configt.type.adoc#column-typeunderlinedesc[+configT.type.type_desc+]
--


// end::AntoraColumnDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]
|1
|*<<column-type>>*
|nvarchar(128)
|NULL
|




// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]

|
|<<column-level1type>>
|varchar(9)
|NULL
|

|
|<<column-level2type>>
|varchar(10)
|NULL
|

|
|<<column-typeunderlinedesc>>
|nvarchar(128)
|NULL
|

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

[#index-pkunderlinetypeunderlinelevel1typeunderlinelevel2type]
=== PK_type_level1type_level2type

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-type>>; nvarchar(128)
--
* PK, Unique, Real: 1, 1, 0

// end::AntoraIndexList[]

== AntoraMeasureDetails

// tag::AntoraMeasureDetails[]

// end::AntoraMeasureDetails[]

== AntoraMeasureDescriptions



== AntoraParameterList

// tag::AntoraParameterList[]

// end::AntoraParameterList[]

== AntoraXrefCulturesList

// tag::AntoraXrefCulturesList[]
* xref:dhw:sqldb:configt.type_level1type_level2type.adoc[] - 
// end::AntoraXrefCulturesList[]

== cultures_count

// tag::cultures_count[]
1
// end::cultures_count[]

== Other tags

source: property.RepoObjectProperty_cross As rop_cross


=== additional_reference_csv

// tag::additional_reference_csv[]

// end::additional_reference_csv[]


=== AdocUspSteps

// tag::adocuspsteps[]

// end::adocuspsteps[]


=== AntoraReferencedList

// tag::antorareferencedlist[]
* xref:dhw:sqldb:configt.type.adoc[]
// end::antorareferencedlist[]


=== AntoraReferencingList

// tag::antorareferencinglist[]
* xref:dhw:sqldb:property.extendedproperty_repo2sys_level1.adoc[]
* xref:dhw:sqldb:property.extendedproperty_repo2sys_level2_repoobject.adoc[]
* xref:dhw:sqldb:property.extendedproperty_repo2sys_level2_repoobjectcolumn.adoc[]
* xref:dhw:sqldb:repo.usp_sync_guid_repoobject.adoc[]
* xref:dhw:sqldb:repo.usp_sync_guid_repoobjectcolumn.adoc[]
* xref:dhw:sqldb:repo_sys.extendedproperties_parameterforaddupdatedrop.adoc[]
* xref:dhw:sqldb:sys_self.extendedproperties_parameterforaddupdatedrop.adoc[]
// end::antorareferencinglist[]


=== Description

// tag::description[]

Mappping from xref:configt.type.adoc[] (used in [type] in system catalog views)
to `level1type` (used in sp_addextendedproperty, sp_updateextendedproperty) 
// end::description[]


=== exampleUsage

// tag::exampleusage[]

// end::exampleusage[]


=== exampleUsage_2

// tag::exampleusage_2[]

// end::exampleusage_2[]


=== exampleUsage_3

// tag::exampleusage_3[]

// end::exampleusage_3[]


=== exampleUsage_4

// tag::exampleusage_4[]

// end::exampleusage_4[]


=== exampleUsage_5

// tag::exampleusage_5[]

// end::exampleusage_5[]


=== exampleWrong_Usage

// tag::examplewrong_usage[]

// end::examplewrong_usage[]


=== has_execution_plan_issue

// tag::has_execution_plan_issue[]

// end::has_execution_plan_issue[]


=== has_get_referenced_issue

// tag::has_get_referenced_issue[]

// end::has_get_referenced_issue[]


=== has_history

// tag::has_history[]

// end::has_history[]


=== has_history_columns

// tag::has_history_columns[]

// end::has_history_columns[]


=== InheritanceType

// tag::inheritancetype[]

// end::inheritancetype[]


=== is_persistence

// tag::is_persistence[]

// end::is_persistence[]


=== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]

// end::is_persistence_check_duplicate_per_pk[]


=== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]

// end::is_persistence_check_for_empty_source[]


=== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]

// end::is_persistence_delete_changed[]


=== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]

// end::is_persistence_delete_missing[]


=== is_persistence_insert

// tag::is_persistence_insert[]

// end::is_persistence_insert[]


=== is_persistence_truncate

// tag::is_persistence_truncate[]

// end::is_persistence_truncate[]


=== is_persistence_update_changed

// tag::is_persistence_update_changed[]

// end::is_persistence_update_changed[]


=== is_repo_managed

// tag::is_repo_managed[]
0
// end::is_repo_managed[]


=== is_ssas

// tag::is_ssas[]
0
// end::is_ssas[]


=== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


=== MS_Description

// tag::ms_description[]

// end::ms_description[]


=== persistence_source_RepoObject_fullname

// tag::persistence_source_repoobject_fullname[]

// end::persistence_source_repoobject_fullname[]


=== persistence_source_RepoObject_fullname2

// tag::persistence_source_repoobject_fullname2[]

// end::persistence_source_repoobject_fullname2[]


=== persistence_source_RepoObject_guid

// tag::persistence_source_repoobject_guid[]

// end::persistence_source_repoobject_guid[]


=== persistence_source_RepoObject_xref

// tag::persistence_source_repoobject_xref[]

// end::persistence_source_repoobject_xref[]


=== pk_index_guid

// tag::pk_index_guid[]
E6D9F960-0F9E-EB11-84F6-A81E8446D5B0
// end::pk_index_guid[]


=== pk_IndexPatternColumnDatatype

// tag::pk_indexpatterncolumndatatype[]
nvarchar(128)
// end::pk_indexpatterncolumndatatype[]


=== pk_IndexPatternColumnName

// tag::pk_indexpatterncolumnname[]
type
// end::pk_indexpatterncolumnname[]


=== pk_IndexSemanticGroup

// tag::pk_indexsemanticgroup[]

// end::pk_indexsemanticgroup[]


=== ReferencedObjectList

// tag::referencedobjectlist[]
* [configT].[type]
// end::referencedobjectlist[]


=== usp_persistence_RepoObject_guid

// tag::usp_persistence_repoobject_guid[]

// end::usp_persistence_repoobject_guid[]


=== UspExamples

// tag::uspexamples[]

// end::uspexamples[]


=== uspgenerator_usp_id

// tag::uspgenerator_usp_id[]

// end::uspgenerator_usp_id[]


=== UspParameters

// tag::uspparameters[]

// end::uspparameters[]

== Boolean Attributes

source: property.RepoObjectProperty WHERE property_int = 1

// tag::boolean_attributes[]


// end::boolean_attributes[]

== PlantUML diagrams

=== PlantUML Entity

// tag::puml_entity[]
[plantuml, entity-{docname}, svg, subs=macros]
....
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:configt.type_level1type_level2type.adoc[]" as configT.type_level1type_level2type << V >> {
  **type** : (nvarchar(128))
  level1type : (varchar(9))
  level2type : (varchar(10))
  type_desc : (nvarchar(128))
  --
}
....

// end::puml_entity[]

=== PlantUML Entity 1 1 FK

// tag::puml_entity_1_1_fk[]
[plantuml, entity_1_1_fk-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:configt.type_level1type_level2type.adoc[]" as configT.type_level1type_level2type << V >> {
- **PK_type_level1type_level2type**

..
type; nvarchar(128)
}



footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_fk[]

=== PlantUML 1 1 ObjectRef

// tag::puml_entity_1_1_objectref[]
[plantuml, entity_1_1_objectref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:configt.type.adoc[]" as configT.type << V >> {
  **type** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:configt.type_level1type_level2type.adoc[]" as configT.type_level1type_level2type << V >> {
  **type** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.extendedproperty_repo2sys_level1.adoc[]" as property.ExtendedProperty_Repo2Sys_level1 << V >> {
  - **level0type** : (nvarchar(6))
  - **level0name** : (nvarchar(128))
  **level1type** : (varchar(9))
  - **level1name** : (nvarchar(128))
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.extendedproperty_repo2sys_level2_repoobject.adoc[]" as property.ExtendedProperty_Repo2Sys_level2_RepoObject << V >> {
  - **level0type** : (nvarchar(6))
  - **level0name** : (nvarchar(128))
  **level1type** : (varchar(9))
  - **level1name** : (nvarchar(128))
  **level2type** : (varchar(10))
  - **level2name** : (nvarchar(128))
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.extendedproperty_repo2sys_level2_repoobjectcolumn.adoc[]" as property.ExtendedProperty_Repo2Sys_level2_RepoObjectColumn << V >> {
  - **level0type** : (nvarchar(6))
  - **level0name** : (nvarchar(128))
  **level1type** : (varchar(9))
  - **level1name** : (nvarchar(128))
  - **level2type** : (nvarchar(6))
  - **level2name** : (nvarchar(128))
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:repo.usp_sync_guid_repoobject.adoc[]" as repo.usp_sync_guid_RepoObject << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_sync_guid_repoobjectcolumn.adoc[]" as repo.usp_sync_guid_RepoObjectColumn << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo_sys.extendedproperties_parameterforaddupdatedrop.adoc[]" as repo_sys.ExtendedProperties_ParameterForAddUpdateDrop << V >> {
  --
}

entity "puml-link:dhw:sqldb:sys_self.extendedproperties_parameterforaddupdatedrop.adoc[]" as sys_self.ExtendedProperties_ParameterForAddUpdateDrop << V >> {
  --
}

configT.type <.. configT.type_level1type_level2type
configT.type_level1type_level2type <.. sys_self.ExtendedProperties_ParameterForAddUpdateDrop
configT.type_level1type_level2type <.. repo_sys.ExtendedProperties_ParameterForAddUpdateDrop
configT.type_level1type_level2type <.. repo.usp_sync_guid_RepoObject
configT.type_level1type_level2type <.. repo.usp_sync_guid_RepoObjectColumn
configT.type_level1type_level2type <.. property.ExtendedProperty_Repo2Sys_level1
configT.type_level1type_level2type <.. property.ExtendedProperty_Repo2Sys_level2_RepoObject
configT.type_level1type_level2type <.. property.ExtendedProperty_Repo2Sys_level2_RepoObjectColumn

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_objectref[]

=== PlantUML 30 0 ObjectRef

// tag::puml_entity_30_0_objectref[]
[plantuml, entity_30_0_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:configt.spt_values.adoc[]" as configT.spt_values << U >> {
  --
}

entity "puml-link:dhw:sqldb:configt.type.adoc[]" as configT.type << V >> {
  **type** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:configt.type_level1type_level2type.adoc[]" as configT.type_level1type_level2type << V >> {
  **type** : (nvarchar(128))
  --
}

configT.spt_values <.. configT.type
configT.type <.. configT.type_level1type_level2type

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_30_0_objectref[]

=== PlantUML 0 30 ObjectRef

// tag::puml_entity_0_30_objectref[]
[plantuml, entity_0_30_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:configt.type_level1type_level2type.adoc[]" as configT.type_level1type_level2type << V >> {
  **type** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.extendedproperty_repo2sys_level1.adoc[]" as property.ExtendedProperty_Repo2Sys_level1 << V >> {
  - **level0type** : (nvarchar(6))
  - **level0name** : (nvarchar(128))
  **level1type** : (varchar(9))
  - **level1name** : (nvarchar(128))
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.extendedproperty_repo2sys_level2_repoobject.adoc[]" as property.ExtendedProperty_Repo2Sys_level2_RepoObject << V >> {
  - **level0type** : (nvarchar(6))
  - **level0name** : (nvarchar(128))
  **level1type** : (varchar(9))
  - **level1name** : (nvarchar(128))
  **level2type** : (varchar(10))
  - **level2name** : (nvarchar(128))
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.extendedproperty_repo2sys_level2_repoobjectcolumn.adoc[]" as property.ExtendedProperty_Repo2Sys_level2_RepoObjectColumn << V >> {
  - **level0type** : (nvarchar(6))
  - **level0name** : (nvarchar(128))
  **level1type** : (varchar(9))
  - **level1name** : (nvarchar(128))
  - **level2type** : (nvarchar(6))
  - **level2name** : (nvarchar(128))
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.extendedproperty_repo2sys_level2_union.adoc[]" as property.ExtendedProperty_Repo2Sys_level2_Union << V >> {
  - **level0type** : (nvarchar(6))
  - **level0name** : (nvarchar(128))
  **level1type** : (varchar(9))
  - **level1name** : (nvarchar(128))
  **level2type** : (nvarchar(10))
  - **level2name** : (nvarchar(128))
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.usp_sync_extendedproperties_repo2sys_delete.adoc[]" as property.usp_sync_ExtendedProperties_Repo2Sys_Delete << P >> {
  --
}

entity "puml-link:dhw:sqldb:property.usp_sync_extendedproperties_repo2sys_insertupdate.adoc[]" as property.usp_sync_ExtendedProperties_Repo2Sys_InsertUpdate << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_main.adoc[]" as repo.usp_main << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_persistence_set.adoc[]" as repo.usp_persistence_set << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_sync_guid.adoc[]" as repo.usp_sync_guid << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_sync_guid_repoobject.adoc[]" as repo.usp_sync_guid_RepoObject << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_sync_guid_repoobjectcolumn.adoc[]" as repo.usp_sync_guid_RepoObjectColumn << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo_sys.extendedproperties_parameterforaddupdatedrop.adoc[]" as repo_sys.ExtendedProperties_ParameterForAddUpdateDrop << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo_sys.usp_dropextendedproperty_level_0.adoc[]" as repo_sys.usp_dropextendedproperty_level_0 << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo_sys.usp_dropextendedproperty_level_1.adoc[]" as repo_sys.usp_dropextendedproperty_level_1 << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo_sys.usp_dropextendedproperty_level_2.adoc[]" as repo_sys.usp_dropextendedproperty_level_2 << P >> {
  --
}

entity "puml-link:dhw:sqldb:sys_self.extendedproperties_parameterforaddupdatedrop.adoc[]" as sys_self.ExtendedProperties_ParameterForAddUpdateDrop << V >> {
  --
}

entity "puml-link:dhw:sqldb:sys_self.usp_dropextendedproperty_level_1.adoc[]" as sys_self.usp_dropextendedproperty_level_1 << P >> {
  --
}

entity "puml-link:dhw:sqldb:sys_self.usp_dropextendedproperty_level_2.adoc[]" as sys_self.usp_dropextendedproperty_level_2 << P >> {
  --
}

configT.type_level1type_level2type <.. property.ExtendedProperty_Repo2Sys_level2_RepoObjectColumn
configT.type_level1type_level2type <.. property.ExtendedProperty_Repo2Sys_level2_RepoObject
configT.type_level1type_level2type <.. property.ExtendedProperty_Repo2Sys_level1
configT.type_level1type_level2type <.. repo.usp_sync_guid_RepoObjectColumn
configT.type_level1type_level2type <.. repo.usp_sync_guid_RepoObject
configT.type_level1type_level2type <.. repo_sys.ExtendedProperties_ParameterForAddUpdateDrop
configT.type_level1type_level2type <.. sys_self.ExtendedProperties_ParameterForAddUpdateDrop
property.ExtendedProperty_Repo2Sys_level1 <.. property.usp_sync_ExtendedProperties_Repo2Sys_Delete
property.ExtendedProperty_Repo2Sys_level1 <.. property.usp_sync_ExtendedProperties_Repo2Sys_InsertUpdate
property.ExtendedProperty_Repo2Sys_level2_RepoObject <.. property.ExtendedProperty_Repo2Sys_level2_Union
property.ExtendedProperty_Repo2Sys_level2_RepoObjectColumn <.. property.ExtendedProperty_Repo2Sys_level2_Union
property.ExtendedProperty_Repo2Sys_level2_Union <.. property.usp_sync_ExtendedProperties_Repo2Sys_Delete
property.ExtendedProperty_Repo2Sys_level2_Union <.. property.usp_sync_ExtendedProperties_Repo2Sys_InsertUpdate
repo.usp_sync_guid <.. repo.usp_persistence_set
repo.usp_sync_guid <.. repo.usp_main
repo.usp_sync_guid_RepoObject <.. repo.usp_sync_guid
repo.usp_sync_guid_RepoObjectColumn <.. repo.usp_sync_guid
repo_sys.ExtendedProperties_ParameterForAddUpdateDrop <.. repo_sys.usp_dropextendedproperty_level_0
repo_sys.ExtendedProperties_ParameterForAddUpdateDrop <.. property.usp_sync_ExtendedProperties_Repo2Sys_Delete
repo_sys.ExtendedProperties_ParameterForAddUpdateDrop <.. property.usp_sync_ExtendedProperties_Repo2Sys_InsertUpdate
repo_sys.ExtendedProperties_ParameterForAddUpdateDrop <.. repo_sys.usp_dropextendedproperty_level_1
sys_self.ExtendedProperties_ParameterForAddUpdateDrop <.. sys_self.usp_dropextendedproperty_level_2
sys_self.ExtendedProperties_ParameterForAddUpdateDrop <.. sys_self.usp_dropextendedproperty_level_1
sys_self.ExtendedProperties_ParameterForAddUpdateDrop <.. repo_sys.usp_dropextendedproperty_level_2

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_0_30_objectref[]

=== PlantUML 1 1 ColumnRef

// tag::puml_entity_1_1_colref[]
[plantuml, entity_1_1_colref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:configt.type.adoc[]" as configT.type << V >> {
  **type** : (nvarchar(128))
  - is_DocsOutput : (int)
  type_desc : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:configt.type_level1type_level2type.adoc[]" as configT.type_level1type_level2type << V >> {
  **type** : (nvarchar(128))
  level1type : (varchar(9))
  level2type : (varchar(10))
  type_desc : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.extendedproperty_repo2sys_level1.adoc[]" as property.ExtendedProperty_Repo2Sys_level1 << V >> {
  - **level0type** : (nvarchar(6))
  - **level0name** : (nvarchar(128))
  **level1type** : (varchar(9))
  - **level1name** : (nvarchar(128))
  - **property_name** : (nvarchar(128))
  level2name : (varchar(128))
  level2type : (varchar(10))
  property_value : (nvarchar(4000))
  - RepoObject_guid : (uniqueidentifier)
  - RepoObject_type : (char(2))
  --
}

entity "puml-link:dhw:sqldb:property.extendedproperty_repo2sys_level2_repoobject.adoc[]" as property.ExtendedProperty_Repo2Sys_level2_RepoObject << V >> {
  - **level0type** : (nvarchar(6))
  - **level0name** : (nvarchar(128))
  **level1type** : (varchar(9))
  - **level1name** : (nvarchar(128))
  **level2type** : (varchar(10))
  - **level2name** : (nvarchar(128))
  - **property_name** : (nvarchar(128))
  - parent_RepoObject_guid : (uniqueidentifier)
  - parent_RepoObject_type : (char(2))
  property_value : (nvarchar(4000))
  - RepoObject_guid : (uniqueidentifier)
  - RepoObject_type : (char(2))
  --
}

entity "puml-link:dhw:sqldb:property.extendedproperty_repo2sys_level2_repoobjectcolumn.adoc[]" as property.ExtendedProperty_Repo2Sys_level2_RepoObjectColumn << V >> {
  - **level0type** : (nvarchar(6))
  - **level0name** : (nvarchar(128))
  **level1type** : (varchar(9))
  - **level1name** : (nvarchar(128))
  - **level2type** : (nvarchar(6))
  - **level2name** : (nvarchar(128))
  - **property_name** : (nvarchar(128))
  - parent_RepoObject_guid : (uniqueidentifier)
  - parent_RepoObject_type : (char(2))
  property_value : (nvarchar(4000))
  Repo_user_type_fullname : (nvarchar(128))
  - RepoObjectColumn_guid : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.usp_sync_guid_repoobject.adoc[]" as repo.usp_sync_guid_RepoObject << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_sync_guid_repoobjectcolumn.adoc[]" as repo.usp_sync_guid_RepoObjectColumn << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo_sys.extendedproperties_parameterforaddupdatedrop.adoc[]" as repo_sys.ExtendedProperties_ParameterForAddUpdateDrop << V >> {
  - class : (tinyint)
  class_desc : (nvarchar(60))
  level0name : (nvarchar(128))
  - level0type : (varchar(6))
  level1name : (nvarchar(128))
  level1type : (varchar(9))
  level2name : (nvarchar(128))
  level2type : (varchar(10))
  - minor_id : (int)
  - property_name : (sysname)
  property_value : (sql_variant)
  type : (char(2))
  type_level1type : (varchar(9))
  type_level2type : (varchar(10))
  --
}

entity "puml-link:dhw:sqldb:sys_self.extendedproperties_parameterforaddupdatedrop.adoc[]" as sys_self.ExtendedProperties_ParameterForAddUpdateDrop << V >> {
  - class : (tinyint)
  class_desc : (nvarchar(60))
  level0name : (nvarchar(128))
  - level0type : (varchar(6))
  level1name : (nvarchar(128))
  level1type : (varchar(9))
  level2name : (nvarchar(128))
  level2type : (varchar(10))
  - minor_id : (int)
  - property_name : (sysname)
  property_value : (sql_variant)
  type : (char(2))
  type_level1type : (varchar(9))
  type_level2type : (varchar(10))
  --
}

configT.type <.. configT.type_level1type_level2type
configT.type_level1type_level2type <.. sys_self.ExtendedProperties_ParameterForAddUpdateDrop
configT.type_level1type_level2type <.. repo_sys.ExtendedProperties_ParameterForAddUpdateDrop
configT.type_level1type_level2type <.. repo.usp_sync_guid_RepoObject
configT.type_level1type_level2type <.. repo.usp_sync_guid_RepoObjectColumn
configT.type_level1type_level2type <.. property.ExtendedProperty_Repo2Sys_level1
configT.type_level1type_level2type <.. property.ExtendedProperty_Repo2Sys_level2_RepoObject
configT.type_level1type_level2type <.. property.ExtendedProperty_Repo2Sys_level2_RepoObjectColumn
"configT.type::type_desc" <-- "configT.type_level1type_level2type::type_desc"
"configT.type_level1type_level2type::level1type" <-- "sys_self.ExtendedProperties_ParameterForAddUpdateDrop::type_level1type"
"configT.type_level1type_level2type::level1type" <-- "repo_sys.ExtendedProperties_ParameterForAddUpdateDrop::type_level1type"
"configT.type_level1type_level2type::level1type" <-- "property.ExtendedProperty_Repo2Sys_level1::level1type"
"configT.type_level1type_level2type::level1type" <-- "property.ExtendedProperty_Repo2Sys_level2_RepoObject::level1type"
"configT.type_level1type_level2type::level1type" <-- "property.ExtendedProperty_Repo2Sys_level2_RepoObjectColumn::level1type"
"configT.type_level1type_level2type::level2type" <-- "property.ExtendedProperty_Repo2Sys_level2_RepoObject::level2type"
"configT.type_level1type_level2type::level2type" <-- "property.ExtendedProperty_Repo2Sys_level1::level2type"
"configT.type_level1type_level2type::level2type" <-- "repo_sys.ExtendedProperties_ParameterForAddUpdateDrop::type_level2type"
"configT.type_level1type_level2type::level2type" <-- "sys_self.ExtendedProperties_ParameterForAddUpdateDrop::type_level2type"

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_colref[]


== sql_modules_definition

// tag::sql_modules_definition[]
[%collapsible]
=======
[source,sql,numbered,indent=0]
----



/*
<<property_start>>Description
Mappping from xref:configt.type.adoc[] (used in [type] in system catalog views)
to `level1type` (used in sp_addextendedproperty, sp_updateextendedproperty) 
<<property_end>>
*/
CREATE View [configT].[type_level1type_level2type]
--WITH SCHEMABINDING
As
--
Select
    type
  , type_desc
  , level1type = Case
                     When type = 'AF'
                         Then
                         'AGGREGATE'
                     --When [type] = 'D '
                     --Then 'DEFAULT'
                     When type In
                     ( 'FN', 'FS', 'FT', 'IF', 'IS', 'TF' )
                         Then
                         'FUNCTION'
                     --WHEN [type] = 'V ' THEN 'LOGICAL FILE NAME'
                     When type In
                     ( 'P ', 'PC', 'RF', 'X ' )
                         Then
                         'PROCEDURE'
                     When type = 'SQ'
                         Then
                         'QUEUE'
                     When type = 'R '
                         Then
                         'RULE'
                     When type = 'SN'
                         Then
                         'SYNONYM'
                     When type = 'U '
                         Then
                         'TABLE'
                     --WHEN [type] = 'V ' THEN 'TABLE_TYPE'
                     --WHEN [type] = 'V ' THEN 'TYPE'
                     When type = 'V '
                         Then
                         'VIEW'
                     --WHEN [type] = 'V ' THEN 'XML SCHEMA COLLECTION'
                 End
  , level2type = Case type
                     When 'C'
                         Then
                         'CONSTRAINT' --CHECK_CONSTRAINT
                     When 'D'
                         Then
                         'CONSTRAINT' --DEFAULT_CONSTRAINT
                     When 'EC'
                         Then
                         'CONSTRAINT' --EDGE_CONSTRAINT
                     When 'F'
                         Then
                         'CONSTRAINT' --FOREIGN_KEY_CONSTRAINT
                     When 'PK'
                         Then
                         'CONSTRAINT' --PRIMARY_KEY_CONSTRAINT
                     When 'UQ'
                         Then
                         'CONSTRAINT' --UNIQUE_CONSTRAINT
                 End
From
    configT.type
----
=======
// end::sql_modules_definition[]


