// tag::HeaderFullDisplayName[]
= config.fs_get_parameter_value - FN
// end::HeaderFullDisplayName[]

== existing_properties

// tag::existing_properties[]

:ExistsProperty--antorareferencedlist:
:ExistsProperty--antorareferencinglist:
:ExistsProperty--is_repo_managed:
:ExistsProperty--is_ssas:
:ExistsProperty--referencedobjectlist:
:ExistsProperty--sql_modules_definition:
:ExistsProperty--AntoraParameterList:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
E98F291C-9D61-EB11-84DC-A81E8446D5B0
// end::RepoObject_guid[]

== RepoObject_FullDisplayName2

// tag::RepoObject_FullDisplayName2[]
config.fs_get_parameter_value
// end::RepoObject_FullDisplayName2[]

== SysObject_type

// tag::SysObject_type[]
FN
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
scalar function
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
1592392742
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2021-09-02 14:54:17
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]

// end::AntoraColumnDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]

// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

// end::AntoraIndexList[]

== AntoraMeasureDetails

// tag::AntoraMeasureDetails[]

// end::AntoraMeasureDetails[]

== AntoraMeasureDescriptions



== AntoraParameterList

// tag::AntoraParameterList[]
*  (nvarchar(max))
* @Parameter_name (varchar(100))
* @sub_Parameter (nvarchar(128))
// end::AntoraParameterList[]

== AntoraXrefCulturesList

// tag::AntoraXrefCulturesList[]
* xref:dhw:sqldb:config.fs_get_parameter_value.adoc[] - 
// end::AntoraXrefCulturesList[]

== cultures_count

// tag::cultures_count[]
1
// end::cultures_count[]

== Other tags

source: property.RepoObjectProperty_cross As rop_cross


=== additional_reference_csv

// tag::additional_reference_csv[]

// end::additional_reference_csv[]


=== AdocUspSteps

// tag::adocuspsteps[]

// end::adocuspsteps[]


=== AntoraReferencedList

// tag::antorareferencedlist[]
* xref:dhw:sqldb:config.parameter.adoc[]
// end::antorareferencedlist[]


=== AntoraReferencingList

// tag::antorareferencinglist[]
* xref:dhw:sqldb:config.usp_extract_dacpac.adoc[]
* xref:dhw:sqldb:docs.fs_antoramodulefolder.adoc[]
* xref:dhw:sqldb:docs.ftv_repoobject_antoraxref.adoc[]
* xref:dhw:sqldb:docs.usp_antoraexport.adoc[]
* xref:dhw:sqldb:docs.usp_antoraexport_ssisnavigation.adoc[]
* xref:dhw:sqldb:docs.usp_antoraexport_ssispage.adoc[]
* xref:dhw:sqldb:docs.usp_antoraexport_ssispagetemplate.adoc[]
* xref:dhw:sqldb:docs.usp_antoraexport_ssispartialscontent.adoc[]
* xref:dhw:sqldb:property.repoobjectcolumnproperty_forupdate.adoc[]
* xref:dhw:sqldb:property.repoobjectproperty_forupdate.adoc[]
* xref:dhw:sqldb:repo.usp_main.adoc[]
* xref:dhw:sqldb:repo.usp_repoobjectcolumn_update_repoobjectcolumn_column_id.adoc[]
* xref:dhw:sqldb:repo.usp_sync_guid_repoobject.adoc[]
* xref:dhw:sqldb:repo.usp_sync_guid_repoobject_ssas.adoc[]
* xref:dhw:sqldb:repo.usp_sync_guid_repoobjectcolumn.adoc[]
* xref:dhw:sqldb:repo.usp_sync_guid_repoobjectcolumn_ssas.adoc[]
* xref:dhw:sqldb:repo.usp_sync_guid_reposchema.adoc[]
* xref:dhw:sqldb:repo.usp_sync_guid_reposchema_ssas.adoc[]
// end::antorareferencinglist[]


=== Description

// tag::description[]

// end::description[]


=== exampleUsage

// tag::exampleusage[]

// end::exampleusage[]


=== exampleUsage_2

// tag::exampleusage_2[]

// end::exampleusage_2[]


=== exampleUsage_3

// tag::exampleusage_3[]

// end::exampleusage_3[]


=== exampleUsage_4

// tag::exampleusage_4[]

// end::exampleusage_4[]


=== exampleUsage_5

// tag::exampleusage_5[]

// end::exampleusage_5[]


=== exampleWrong_Usage

// tag::examplewrong_usage[]

// end::examplewrong_usage[]


=== has_execution_plan_issue

// tag::has_execution_plan_issue[]

// end::has_execution_plan_issue[]


=== has_get_referenced_issue

// tag::has_get_referenced_issue[]

// end::has_get_referenced_issue[]


=== has_history

// tag::has_history[]

// end::has_history[]


=== has_history_columns

// tag::has_history_columns[]

// end::has_history_columns[]


=== InheritanceType

// tag::inheritancetype[]

// end::inheritancetype[]


=== is_persistence

// tag::is_persistence[]

// end::is_persistence[]


=== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]

// end::is_persistence_check_duplicate_per_pk[]


=== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]

// end::is_persistence_check_for_empty_source[]


=== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]

// end::is_persistence_delete_changed[]


=== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]

// end::is_persistence_delete_missing[]


=== is_persistence_insert

// tag::is_persistence_insert[]

// end::is_persistence_insert[]


=== is_persistence_truncate

// tag::is_persistence_truncate[]

// end::is_persistence_truncate[]


=== is_persistence_update_changed

// tag::is_persistence_update_changed[]

// end::is_persistence_update_changed[]


=== is_repo_managed

// tag::is_repo_managed[]
0
// end::is_repo_managed[]


=== is_ssas

// tag::is_ssas[]
0
// end::is_ssas[]


=== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


=== MS_Description

// tag::ms_description[]

// end::ms_description[]


=== persistence_source_RepoObject_fullname

// tag::persistence_source_repoobject_fullname[]

// end::persistence_source_repoobject_fullname[]


=== persistence_source_RepoObject_fullname2

// tag::persistence_source_repoobject_fullname2[]

// end::persistence_source_repoobject_fullname2[]


=== persistence_source_RepoObject_guid

// tag::persistence_source_repoobject_guid[]

// end::persistence_source_repoobject_guid[]


=== persistence_source_RepoObject_xref

// tag::persistence_source_repoobject_xref[]

// end::persistence_source_repoobject_xref[]


=== pk_index_guid

// tag::pk_index_guid[]

// end::pk_index_guid[]


=== pk_IndexPatternColumnDatatype

// tag::pk_indexpatterncolumndatatype[]

// end::pk_indexpatterncolumndatatype[]


=== pk_IndexPatternColumnName

// tag::pk_indexpatterncolumnname[]

// end::pk_indexpatterncolumnname[]


=== pk_IndexSemanticGroup

// tag::pk_indexsemanticgroup[]

// end::pk_indexsemanticgroup[]


=== ReferencedObjectList

// tag::referencedobjectlist[]
* [config].[Parameter]
// end::referencedobjectlist[]


=== usp_persistence_RepoObject_guid

// tag::usp_persistence_repoobject_guid[]

// end::usp_persistence_repoobject_guid[]


=== UspExamples

// tag::uspexamples[]

// end::uspexamples[]


=== uspgenerator_usp_id

// tag::uspgenerator_usp_id[]

// end::uspgenerator_usp_id[]


=== UspParameters

// tag::uspparameters[]

// end::uspparameters[]

== Boolean Attributes

source: property.RepoObjectProperty WHERE property_int = 1

// tag::boolean_attributes[]


// end::boolean_attributes[]

== PlantUML diagrams

=== PlantUML Entity

// tag::puml_entity[]
[plantuml, entity-{docname}, svg, subs=macros]
....
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:config.fs_get_parameter_value.adoc[]" as config.fs_get_parameter_value << FN >> {
  --
}
....

// end::puml_entity[]

=== PlantUML Entity 1 1 FK

// tag::puml_entity_1_1_fk[]
[plantuml, entity_1_1_fk-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}





footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_fk[]

=== PlantUML 1 1 ObjectRef

// tag::puml_entity_1_1_objectref[]
[plantuml, entity_1_1_objectref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:config.fs_get_parameter_value.adoc[]" as config.fs_get_parameter_value << FN >> {
  --
}

entity "puml-link:dhw:sqldb:config.parameter.adoc[]" as config.Parameter << U >> {
  - **Parameter_name** : (varchar(100))
  - **sub_Parameter** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:config.usp_extract_dacpac.adoc[]" as config.usp_extract_dacpac << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.fs_antoramodulefolder.adoc[]" as docs.fs_AntoraModuleFolder << FN >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ftv_repoobject_antoraxref.adoc[]" as docs.ftv_RepoObject_AntoraXref << IF >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport.adoc[]" as docs.usp_AntoraExport << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_ssisnavigation.adoc[]" as docs.usp_AntoraExport_SsisNavigation << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_ssispage.adoc[]" as docs.usp_AntoraExport_SsisPage << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_ssispagetemplate.adoc[]" as docs.usp_AntoraExport_SsisPageTemplate << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_ssispartialscontent.adoc[]" as docs.usp_AntoraExport_SsisPartialsContent << P >> {
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectcolumnproperty_forupdate.adoc[]" as property.RepoObjectColumnProperty_ForUpdate << V >> {
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty_forupdate.adoc[]" as property.RepoObjectProperty_ForUpdate << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_main.adoc[]" as repo.usp_main << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_repoobjectcolumn_update_repoobjectcolumn_column_id.adoc[]" as repo.usp_RepoObjectColumn_update_RepoObjectColumn_column_id << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_sync_guid_repoobject.adoc[]" as repo.usp_sync_guid_RepoObject << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_sync_guid_repoobject_ssas.adoc[]" as repo.usp_sync_guid_RepoObject_ssas << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_sync_guid_repoobjectcolumn.adoc[]" as repo.usp_sync_guid_RepoObjectColumn << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_sync_guid_repoobjectcolumn_ssas.adoc[]" as repo.usp_sync_guid_RepoObjectColumn_ssas << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_sync_guid_reposchema.adoc[]" as repo.usp_sync_guid_RepoSchema << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_sync_guid_reposchema_ssas.adoc[]" as repo.usp_sync_guid_RepoSchema_ssas << P >> {
  --
}

config.fs_get_parameter_value <.. config.usp_extract_dacpac
config.fs_get_parameter_value <.. docs.fs_AntoraModuleFolder
config.fs_get_parameter_value <.. docs.ftv_RepoObject_AntoraXref
config.fs_get_parameter_value <.. docs.usp_AntoraExport
config.fs_get_parameter_value <.. docs.usp_AntoraExport_SsisNavigation
config.fs_get_parameter_value <.. docs.usp_AntoraExport_SsisPage
config.fs_get_parameter_value <.. docs.usp_AntoraExport_SsisPageTemplate
config.fs_get_parameter_value <.. docs.usp_AntoraExport_SsisPartialsContent
config.fs_get_parameter_value <.. property.RepoObjectColumnProperty_ForUpdate
config.fs_get_parameter_value <.. property.RepoObjectProperty_ForUpdate
config.fs_get_parameter_value <.. repo.usp_main
config.fs_get_parameter_value <.. repo.usp_RepoObjectColumn_update_RepoObjectColumn_column_id
config.fs_get_parameter_value <.. repo.usp_sync_guid_RepoObject
config.fs_get_parameter_value <.. repo.usp_sync_guid_RepoObject_ssas
config.fs_get_parameter_value <.. repo.usp_sync_guid_RepoObjectColumn
config.fs_get_parameter_value <.. repo.usp_sync_guid_RepoObjectColumn_ssas
config.fs_get_parameter_value <.. repo.usp_sync_guid_RepoSchema
config.fs_get_parameter_value <.. repo.usp_sync_guid_RepoSchema_ssas
config.Parameter <.. config.fs_get_parameter_value

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_objectref[]

=== PlantUML 30 0 ObjectRef

// tag::puml_entity_30_0_objectref[]
[plantuml, entity_30_0_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:config.fs_get_parameter_value.adoc[]" as config.fs_get_parameter_value << FN >> {
  --
}

entity "puml-link:dhw:sqldb:config.parameter.adoc[]" as config.Parameter << U >> {
  - **Parameter_name** : (varchar(100))
  - **sub_Parameter** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:configt.parameter_default.adoc[]" as configT.Parameter_default << V >> {
  - **Parameter_name** : (varchar(52))
  - **sub_Parameter** : (nvarchar(26))
  --
}

config.Parameter <.. config.fs_get_parameter_value
configT.Parameter_default <.. config.Parameter

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_30_0_objectref[]

=== PlantUML 0 30 ObjectRef

// tag::puml_entity_0_30_objectref[]
[plantuml, entity_0_30_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:config.fs_get_parameter_value.adoc[]" as config.fs_get_parameter_value << FN >> {
  --
}

entity "puml-link:dhw:sqldb:config.usp_extract_dacpac.adoc[]" as config.usp_extract_dacpac << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.fs_antoramodulefolder.adoc[]" as docs.fs_AntoraModuleFolder << FN >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ftv_repoobject_antoraxref.adoc[]" as docs.ftv_RepoObject_AntoraXref << IF >> {
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_adoc.adoc[]" as docs.RepoObject_Adoc << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_adoc_t.adoc[]" as docs.RepoObject_Adoc_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_antoraxrefcultureslist.adoc[]" as docs.RepoObject_AntoraXrefCulturesList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport.adoc[]" as docs.usp_AntoraExport << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_docsnippet.adoc[]" as docs.usp_AntoraExport_DocSnippet << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_objectnavigation.adoc[]" as docs.usp_AntoraExport_ObjectNavigation << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_objectpage.adoc[]" as docs.usp_AntoraExport_ObjectPage << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_objectpagetemplate.adoc[]" as docs.usp_AntoraExport_ObjectPageTemplate << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_objectpartialscontent.adoc[]" as docs.usp_AntoraExport_ObjectPartialsContent << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_objectrefcyclic.adoc[]" as docs.usp_AntoraExport_ObjectRefCyclic << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_page_indexsemanticgroup.adoc[]" as docs.usp_AntoraExport_Page_IndexSemanticGroup << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_ssisnavigation.adoc[]" as docs.usp_AntoraExport_SsisNavigation << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_ssispage.adoc[]" as docs.usp_AntoraExport_SsisPage << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_ssispagetemplate.adoc[]" as docs.usp_AntoraExport_SsisPageTemplate << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_ssispartialscontent.adoc[]" as docs.usp_AntoraExport_SsisPartialsContent << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_repoobject_adoc_t.adoc[]" as docs.usp_PERSIST_RepoObject_Adoc_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectcolumnproperty_forupdate.adoc[]" as property.RepoObjectColumnProperty_ForUpdate << V >> {
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty_forupdate.adoc[]" as property.RepoObjectProperty_ForUpdate << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_main.adoc[]" as repo.usp_main << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_persistence_set.adoc[]" as repo.usp_persistence_set << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_repoobjectcolumn_update_repoobjectcolumn_column_id.adoc[]" as repo.usp_RepoObjectColumn_update_RepoObjectColumn_column_id << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_sync_guid.adoc[]" as repo.usp_sync_guid << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_sync_guid_repoobject.adoc[]" as repo.usp_sync_guid_RepoObject << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_sync_guid_repoobject_ssas.adoc[]" as repo.usp_sync_guid_RepoObject_ssas << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_sync_guid_repoobjectcolumn.adoc[]" as repo.usp_sync_guid_RepoObjectColumn << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_sync_guid_repoobjectcolumn_ssas.adoc[]" as repo.usp_sync_guid_RepoObjectColumn_ssas << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_sync_guid_reposchema.adoc[]" as repo.usp_sync_guid_RepoSchema << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_sync_guid_reposchema_ssas.adoc[]" as repo.usp_sync_guid_RepoSchema_ssas << P >> {
  --
}

config.fs_get_parameter_value <.. config.usp_extract_dacpac
config.fs_get_parameter_value <.. docs.fs_AntoraModuleFolder
config.fs_get_parameter_value <.. docs.ftv_RepoObject_AntoraXref
config.fs_get_parameter_value <.. docs.usp_AntoraExport
config.fs_get_parameter_value <.. docs.usp_AntoraExport_SsisNavigation
config.fs_get_parameter_value <.. docs.usp_AntoraExport_SsisPage
config.fs_get_parameter_value <.. docs.usp_AntoraExport_SsisPageTemplate
config.fs_get_parameter_value <.. docs.usp_AntoraExport_SsisPartialsContent
config.fs_get_parameter_value <.. property.RepoObjectColumnProperty_ForUpdate
config.fs_get_parameter_value <.. property.RepoObjectProperty_ForUpdate
config.fs_get_parameter_value <.. repo.usp_main
config.fs_get_parameter_value <.. repo.usp_RepoObjectColumn_update_RepoObjectColumn_column_id
config.fs_get_parameter_value <.. repo.usp_sync_guid_RepoObject
config.fs_get_parameter_value <.. repo.usp_sync_guid_RepoObject_ssas
config.fs_get_parameter_value <.. repo.usp_sync_guid_RepoObjectColumn
config.fs_get_parameter_value <.. repo.usp_sync_guid_RepoObjectColumn_ssas
config.fs_get_parameter_value <.. repo.usp_sync_guid_RepoSchema
config.fs_get_parameter_value <.. repo.usp_sync_guid_RepoSchema_ssas
docs.fs_AntoraModuleFolder <.. docs.usp_AntoraExport
docs.fs_AntoraModuleFolder <.. docs.usp_AntoraExport_DocSnippet
docs.fs_AntoraModuleFolder <.. docs.usp_AntoraExport_ObjectNavigation
docs.fs_AntoraModuleFolder <.. docs.usp_AntoraExport_ObjectPage
docs.fs_AntoraModuleFolder <.. docs.usp_AntoraExport_ObjectPageTemplate
docs.fs_AntoraModuleFolder <.. docs.usp_AntoraExport_ObjectPartialsContent
docs.fs_AntoraModuleFolder <.. docs.usp_AntoraExport_ObjectRefCyclic
docs.fs_AntoraModuleFolder <.. docs.usp_AntoraExport_Page_IndexSemanticGroup
docs.ftv_RepoObject_AntoraXref <.. docs.RepoObject_AntoraXrefCulturesList
docs.RepoObject_Adoc <.. docs.RepoObject_Adoc_T
docs.RepoObject_Adoc <.. docs.usp_PERSIST_RepoObject_Adoc_T
docs.REpoObject_Adoc_T <.. docs.usp_PERSIST_RepoObject_Adoc_T
docs.RepoObject_AntoraXrefCulturesList <.. docs.RepoObject_Adoc
docs.usp_AntoraExport_ObjectNavigation <.. docs.usp_AntoraExport
docs.usp_AntoraExport_ObjectPage <.. docs.usp_AntoraExport
docs.usp_AntoraExport_ObjectPageTemplate <.. docs.usp_AntoraExport
docs.usp_AntoraExport_ObjectPartialsContent <.. docs.usp_AntoraExport
docs.usp_AntoraExport_ObjectRefCyclic <.. docs.usp_AntoraExport
docs.usp_AntoraExport_Page_IndexSemanticGroup <.. docs.usp_AntoraExport
docs.usp_AntoraExport_SsisNavigation <.. docs.usp_AntoraExport
docs.usp_AntoraExport_SsisPage <.. docs.usp_AntoraExport
docs.usp_AntoraExport_SsisPageTemplate <.. docs.usp_AntoraExport
docs.usp_AntoraExport_SsisPartialsContent <.. docs.usp_AntoraExport
docs.usp_PERSIST_RepoObject_Adoc_T <.. docs.usp_AntoraExport_ObjectPartialsContent
repo.usp_RepoObjectColumn_update_RepoObjectColumn_column_id <.. repo.usp_main
repo.usp_sync_guid <.. repo.usp_main
repo.usp_sync_guid <.. repo.usp_persistence_set
repo.usp_sync_guid_RepoObject <.. repo.usp_sync_guid
repo.usp_sync_guid_RepoObjectColumn <.. repo.usp_sync_guid
repo.usp_sync_guid_RepoSchema <.. repo.usp_sync_guid

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_0_30_objectref[]

=== PlantUML 1 1 ColumnRef

// tag::puml_entity_1_1_colref[]
[plantuml, entity_1_1_colref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:config.fs_get_parameter_value.adoc[]" as config.fs_get_parameter_value << FN >> {
  --
}

entity "puml-link:dhw:sqldb:config.parameter.adoc[]" as config.Parameter << U >> {
  - **Parameter_name** : (varchar(100))
  - **sub_Parameter** : (nvarchar(128))
  Parameter_default_value : (nvarchar(max))
  Parameter_desciption : (nvarchar(1000))
  Parameter_value : (nvarchar(max))
  ~ Parameter_value_result : (nvarchar(max))
  ~ Parameter_value_result_date : (date)
  ~ Parameter_value_result_datetime : (datetime)
  ~ Parameter_value_result_int : (int)
  --
}

entity "puml-link:dhw:sqldb:config.usp_extract_dacpac.adoc[]" as config.usp_extract_dacpac << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.fs_antoramodulefolder.adoc[]" as docs.fs_AntoraModuleFolder << FN >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ftv_repoobject_antoraxref.adoc[]" as docs.ftv_RepoObject_AntoraXref << IF >> {
  AntoraXrefComponentModule : (nvarchar(max))
  AntoraXrefModule : (nvarchar(max))
  cultures_name : (nvarchar(10))
  RepoObject_guid : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport.adoc[]" as docs.usp_AntoraExport << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_ssisnavigation.adoc[]" as docs.usp_AntoraExport_SsisNavigation << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_ssispage.adoc[]" as docs.usp_AntoraExport_SsisPage << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_ssispagetemplate.adoc[]" as docs.usp_AntoraExport_SsisPageTemplate << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_ssispartialscontent.adoc[]" as docs.usp_AntoraExport_SsisPartialsContent << P >> {
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectcolumnproperty_forupdate.adoc[]" as property.RepoObjectColumnProperty_ForUpdate << V >> {
  AntoraComponent : (nvarchar(max))
  AntoraModule : (nvarchar(max))
  dwh_database : (nvarchar(128))
  inheritance : (tinyint)
  InheritanceDefinition : (nvarchar(4000))
  InheritanceType : (tinyint)
  - property_name : (nvarchar(128))
  - property_value : (nvarchar(max))
  repo_database : (nvarchar(128))
  Repo_user_type_fullname : (nvarchar(128))
  - RepoObject_fullname : (nvarchar(261))
  - RepoObject_fullname2 : (nvarchar(257))
  - RepoObject_guid : (uniqueidentifier)
  - RepoObject_name : (nvarchar(128))
  - RepoObject_schema_name : (nvarchar(128))
  - RepoObject_type : (char(2))
  - RepoObjectColumn_fullname : (nvarchar(520))
  - RepoObjectColumn_fullname2 : (nvarchar(386))
  - RepoObjectColumn_guid : (uniqueidentifier)
  - RepoObjectColumn_name : (nvarchar(128))
  - RepoObjectColumnProperty_id : (int)
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty_forupdate.adoc[]" as property.RepoObjectProperty_ForUpdate << V >> {
  AntoraComponent : (nvarchar(max))
  AntoraModule : (nvarchar(max))
  dwh_database : (nvarchar(128))
  inheritance : (tinyint)
  - property_name : (nvarchar(128))
  property_value : (nvarchar(max))
  repo_database : (nvarchar(128))
  - RepoObject_fullname : (nvarchar(261))
  - RepoObject_fullname2 : (nvarchar(257))
  - RepoObject_guid : (uniqueidentifier)
  - RepoObject_name : (nvarchar(128))
  - RepoObject_schema_name : (nvarchar(128))
  - RepoObject_type : (char(2))
  - RepoObjectProperty_id : (int)
  - tsql_comment_tag : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:repo.usp_main.adoc[]" as repo.usp_main << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_repoobjectcolumn_update_repoobjectcolumn_column_id.adoc[]" as repo.usp_RepoObjectColumn_update_RepoObjectColumn_column_id << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_sync_guid_repoobject.adoc[]" as repo.usp_sync_guid_RepoObject << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_sync_guid_repoobject_ssas.adoc[]" as repo.usp_sync_guid_RepoObject_ssas << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_sync_guid_repoobjectcolumn.adoc[]" as repo.usp_sync_guid_RepoObjectColumn << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_sync_guid_repoobjectcolumn_ssas.adoc[]" as repo.usp_sync_guid_RepoObjectColumn_ssas << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_sync_guid_reposchema.adoc[]" as repo.usp_sync_guid_RepoSchema << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_sync_guid_reposchema_ssas.adoc[]" as repo.usp_sync_guid_RepoSchema_ssas << P >> {
  --
}

config.fs_get_parameter_value <.. config.usp_extract_dacpac
config.fs_get_parameter_value <.. docs.fs_AntoraModuleFolder
config.fs_get_parameter_value <.. docs.ftv_RepoObject_AntoraXref
config.fs_get_parameter_value <.. docs.usp_AntoraExport
config.fs_get_parameter_value <.. docs.usp_AntoraExport_SsisNavigation
config.fs_get_parameter_value <.. docs.usp_AntoraExport_SsisPage
config.fs_get_parameter_value <.. docs.usp_AntoraExport_SsisPageTemplate
config.fs_get_parameter_value <.. docs.usp_AntoraExport_SsisPartialsContent
config.fs_get_parameter_value <.. property.RepoObjectColumnProperty_ForUpdate
config.fs_get_parameter_value <.. property.RepoObjectProperty_ForUpdate
config.fs_get_parameter_value <.. repo.usp_main
config.fs_get_parameter_value <.. repo.usp_RepoObjectColumn_update_RepoObjectColumn_column_id
config.fs_get_parameter_value <.. repo.usp_sync_guid_RepoObject
config.fs_get_parameter_value <.. repo.usp_sync_guid_RepoObject_ssas
config.fs_get_parameter_value <.. repo.usp_sync_guid_RepoObjectColumn
config.fs_get_parameter_value <.. repo.usp_sync_guid_RepoObjectColumn_ssas
config.fs_get_parameter_value <.. repo.usp_sync_guid_RepoSchema
config.fs_get_parameter_value <.. repo.usp_sync_guid_RepoSchema_ssas
config.Parameter <.. config.fs_get_parameter_value


footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_colref[]


== sql_modules_definition

// tag::sql_modules_definition[]
[%collapsible]
=======
[source,sql,numbered,indent=0]
----

CREATE Function config.fs_get_parameter_value
(
    @Parameter_name Varchar(100)
  , @sub_Parameter  NVarchar(128) = N''
)
Returns NVarchar(Max)
As
Begin
    Return
    (
        Select
            Parameter_value_result
        From
            config.Parameter
        Where
            Parameter_name    = @Parameter_name
            And sub_Parameter = @sub_Parameter
    );
End;
----
=======
// end::sql_modules_definition[]


