// tag::HeaderFullDisplayName[]
= configT.SsasDmvTableImport - V
// end::HeaderFullDisplayName[]

== existing_properties

// tag::existing_properties[]

:ExistsProperty--antorareferencinglist:
:ExistsProperty--description:
:ExistsProperty--exampleusage:
:ExistsProperty--is_repo_managed:
:ExistsProperty--is_ssas:
:ExistsProperty--sql_modules_definition:
:ExistsProperty--FK:
:ExistsProperty--Columns:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
CFE6A70A-8A06-EC11-8515-A81E8446D5B0
// end::RepoObject_guid[]

== RepoObject_FullDisplayName2

// tag::RepoObject_FullDisplayName2[]
configT.SsasDmvTableImport
// end::RepoObject_FullDisplayName2[]

== SysObject_type

// tag::SysObject_type[]
V 
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
view
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
925962375
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2021-10-02 13:23:34
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]
[discrete]
== _


[#column-dmvtablename]
=== DmvTableName

[cols="d,8a,m,m,m"]
|===
|
|DmvTableName
|nvarchar(128)
|NULL
|
|===

.Referencing Columns
--
* xref:configt.ssasdmvtableimport_dmvcolumnlist.adoc#column-dmvtablename[+configT.SsasDmvTableImport_DmvColumnList.DmvTableName+]
--


[#column-isactive]
=== isActive

[cols="d,8a,m,m,m"]
|===
|
|isActive
|bit
|NULL
|
|===


// end::AntoraColumnDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]


// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]
|
|<<column-dmvtablename>>
|nvarchar(128)
|NULL
|

|
|<<column-isactive>>
|bit
|NULL
|

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

// end::AntoraIndexList[]

== AntoraMeasureDetails

// tag::AntoraMeasureDetails[]

// end::AntoraMeasureDetails[]

== AntoraMeasureDescriptions



== AntoraParameterList

// tag::AntoraParameterList[]

// end::AntoraParameterList[]

== AntoraXrefCulturesList

// tag::AntoraXrefCulturesList[]
* xref:dhw:sqldb:configt.ssasdmvtableimport.adoc[] - 
// end::AntoraXrefCulturesList[]

== cultures_count

// tag::cultures_count[]
1
// end::cultures_count[]

== Other tags

source: property.RepoObjectProperty_cross As rop_cross


=== additional_reference_csv

// tag::additional_reference_csv[]

// end::additional_reference_csv[]


=== AdocUspSteps

// tag::adocuspsteps[]

// end::adocuspsteps[]


=== AntoraReferencedList

// tag::antorareferencedlist[]

// end::antorareferencedlist[]


=== AntoraReferencingList

// tag::antorareferencinglist[]
* xref:dhw:sqldb:configt.ssasdmvtableimport_dmvcolumnlist.adoc[]
// end::antorareferencinglist[]


=== Description

// tag::description[]

obsolet

defines, which SSAS DMV tables should be imported
// end::description[]


=== exampleUsage

// tag::exampleusage[]

Merge config.SsasDmvTableImport As tgt
Using configT.SsasDmvTableImport As src
On tgt.DmvTableName = src.DmvTableName
When Matched And tgt.isActive <> src.isActive
    Then Update Set
             isActive = src.isActive
When Not Matched By Target
    Then Insert
         (
             DmvTableName
           , isActive
         )
         Values
             (
                 src.DmvTableName
               , src.isActive
             );
// end::exampleusage[]


=== exampleUsage_2

// tag::exampleusage_2[]

// end::exampleusage_2[]


=== exampleUsage_3

// tag::exampleusage_3[]

// end::exampleusage_3[]


=== exampleUsage_4

// tag::exampleusage_4[]

// end::exampleusage_4[]


=== exampleUsage_5

// tag::exampleusage_5[]

// end::exampleusage_5[]


=== exampleWrong_Usage

// tag::examplewrong_usage[]

// end::examplewrong_usage[]


=== has_execution_plan_issue

// tag::has_execution_plan_issue[]

// end::has_execution_plan_issue[]


=== has_get_referenced_issue

// tag::has_get_referenced_issue[]

// end::has_get_referenced_issue[]


=== has_history

// tag::has_history[]

// end::has_history[]


=== has_history_columns

// tag::has_history_columns[]

// end::has_history_columns[]


=== InheritanceType

// tag::inheritancetype[]

// end::inheritancetype[]


=== is_persistence

// tag::is_persistence[]

// end::is_persistence[]


=== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]

// end::is_persistence_check_duplicate_per_pk[]


=== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]

// end::is_persistence_check_for_empty_source[]


=== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]

// end::is_persistence_delete_changed[]


=== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]

// end::is_persistence_delete_missing[]


=== is_persistence_insert

// tag::is_persistence_insert[]

// end::is_persistence_insert[]


=== is_persistence_truncate

// tag::is_persistence_truncate[]

// end::is_persistence_truncate[]


=== is_persistence_update_changed

// tag::is_persistence_update_changed[]

// end::is_persistence_update_changed[]


=== is_repo_managed

// tag::is_repo_managed[]
0
// end::is_repo_managed[]


=== is_ssas

// tag::is_ssas[]
0
// end::is_ssas[]


=== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


=== MS_Description

// tag::ms_description[]

// end::ms_description[]


=== persistence_source_RepoObject_fullname

// tag::persistence_source_repoobject_fullname[]

// end::persistence_source_repoobject_fullname[]


=== persistence_source_RepoObject_fullname2

// tag::persistence_source_repoobject_fullname2[]

// end::persistence_source_repoobject_fullname2[]


=== persistence_source_RepoObject_guid

// tag::persistence_source_repoobject_guid[]

// end::persistence_source_repoobject_guid[]


=== persistence_source_RepoObject_xref

// tag::persistence_source_repoobject_xref[]

// end::persistence_source_repoobject_xref[]


=== pk_index_guid

// tag::pk_index_guid[]

// end::pk_index_guid[]


=== pk_IndexPatternColumnDatatype

// tag::pk_indexpatterncolumndatatype[]

// end::pk_indexpatterncolumndatatype[]


=== pk_IndexPatternColumnName

// tag::pk_indexpatterncolumnname[]

// end::pk_indexpatterncolumnname[]


=== pk_IndexSemanticGroup

// tag::pk_indexsemanticgroup[]

// end::pk_indexsemanticgroup[]


=== ReferencedObjectList

// tag::referencedobjectlist[]

// end::referencedobjectlist[]


=== usp_persistence_RepoObject_guid

// tag::usp_persistence_repoobject_guid[]

// end::usp_persistence_repoobject_guid[]


=== UspExamples

// tag::uspexamples[]

// end::uspexamples[]


=== uspgenerator_usp_id

// tag::uspgenerator_usp_id[]

// end::uspgenerator_usp_id[]


=== UspParameters

// tag::uspparameters[]

// end::uspparameters[]

== Boolean Attributes

source: property.RepoObjectProperty WHERE property_int = 1

// tag::boolean_attributes[]


// end::boolean_attributes[]

== PlantUML diagrams

=== PlantUML Entity

// tag::puml_entity[]
[plantuml, entity-{docname}, svg, subs=macros]
....
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:configt.ssasdmvtableimport.adoc[]" as configT.SsasDmvTableImport << V >> {
  DmvTableName : (nvarchar(128))
  isActive : (bit)
  --
}
....

// end::puml_entity[]

=== PlantUML Entity 1 1 FK

// tag::puml_entity_1_1_fk[]
[plantuml, entity_1_1_fk-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:configt.ssasdmvtableimport.adoc[]" as configT.SsasDmvTableImport << V >> {

}



footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_fk[]

=== PlantUML 1 1 ObjectRef

// tag::puml_entity_1_1_objectref[]
[plantuml, entity_1_1_objectref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:configt.ssasdmvtableimport.adoc[]" as configT.SsasDmvTableImport << V >> {
  --
}

entity "puml-link:dhw:sqldb:configt.ssasdmvtableimport_dmvcolumnlist.adoc[]" as configT.SsasDmvTableImport_DmvColumnList << V >> {
  --
}

configT.SsasDmvTableImport <.. configT.SsasDmvTableImport_DmvColumnList

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_objectref[]

=== PlantUML 30 0 ObjectRef

// tag::puml_entity_30_0_objectref[]
[plantuml, entity_30_0_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:configt.ssasdmvtableimport.adoc[]" as configT.SsasDmvTableImport << V >> {
  --
}



footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_30_0_objectref[]

=== PlantUML 0 30 ObjectRef

// tag::puml_entity_0_30_objectref[]
[plantuml, entity_0_30_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:configt.ssasdmvtableimport.adoc[]" as configT.SsasDmvTableImport << V >> {
  --
}

entity "puml-link:dhw:sqldb:configt.ssasdmvtableimport_dmvcolumnlist.adoc[]" as configT.SsasDmvTableImport_DmvColumnList << V >> {
  --
}

entity "puml-link:dhw:sqldb:configt.ssasdmvtableimport_importsql.adoc[]" as configT.SsasDmvTableImport_ImportSql << V >> {
  --
}

configT.SsasDmvTableImport <.. configT.SsasDmvTableImport_DmvColumnList
configT.SsasDmvTableImport_DmvColumnList <.. configT.SsasDmvTableImport_ImportSql

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_0_30_objectref[]

=== PlantUML 1 1 ColumnRef

// tag::puml_entity_1_1_colref[]
[plantuml, entity_1_1_colref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:configt.ssasdmvtableimport.adoc[]" as configT.SsasDmvTableImport << V >> {
  DmvTableName : (nvarchar(128))
  isActive : (bit)
  --
}

entity "puml-link:dhw:sqldb:configt.ssasdmvtableimport_dmvcolumnlist.adoc[]" as configT.SsasDmvTableImport_DmvColumnList << V >> {
  DmvColumnList : (nvarchar(max))
  DmvTableName : (nvarchar(128))
  --
}

configT.SsasDmvTableImport <.. configT.SsasDmvTableImport_DmvColumnList
"configT.SsasDmvTableImport::DmvTableName" <-- "configT.SsasDmvTableImport_DmvColumnList::DmvTableName"

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_colref[]


== sql_modules_definition

// tag::sql_modules_definition[]
[%collapsible]
=======
[source,sql,numbered,indent=0]
----


/*
<<property_start>>Description
obsolet

defines, which SSAS DMV tables should be imported
<<property_end>>

<<property_start>>exampleUsage
Merge config.SsasDmvTableImport As tgt
Using configT.SsasDmvTableImport As src
On tgt.DmvTableName = src.DmvTableName
When Matched And tgt.isActive <> src.isActive
    Then Update Set
             isActive = src.isActive
When Not Matched By Target
    Then Insert
         (
             DmvTableName
           , isActive
         )
         Values
             (
                 src.DmvTableName
               , src.isActive
             );
<<property_end>>
*/
CREATE   View [configT].[SsasDmvTableImport]
As
--
Select
    DmvTableName = Cast('TMSCHEMA_ANNOTATIONS' As NVarchar(128))
  , isActive     = Cast(1 As Bit)
Union All
Select
    DmvTableName = Cast('TMSCHEMA_ATTRIBUTE_HIERARCHIES' As NVarchar(128))
  , isActive     = Cast(1 As Bit)
Union All
--import issues
Select
    DmvTableName = Cast('TMSCHEMA_CALCULATION_ITEMS' As NVarchar(128))
  , isActive     = Cast(0 As Bit)
Union All
--import issues
Select
    DmvTableName = Cast('TMSCHEMA_CALCULATION_GROUPS' As NVarchar(128))
  , isActive     = Cast(0 As Bit)
Union All
--type conversion required
--CStr([RefreshedTime]) as [RefreshedTime]
Select
    DmvTableName = Cast('TMSCHEMA_COLUMNS' As NVarchar(128))
  , isActive     = Cast(1 As Bit)
Union All
Select
    DmvTableName = Cast('TMSCHEMA_COLUMN_PERMISSIONS' As NVarchar(128))
  , isActive     = Cast(1 As Bit)
Union All
Select
    DmvTableName = Cast('TMSCHEMA_CULTURES' As NVarchar(128))
  , isActive     = Cast(1 As Bit)
Union All
Select
    DmvTableName = Cast('TMSCHEMA_DATA_SOURCES' As NVarchar(128))
  , isActive     = Cast(1 As Bit)
Union All
Select
    DmvTableName = Cast('TMSCHEMA_DETAIL_ROWS_DEFINITIONS' As NVarchar(128))
  , isActive     = Cast(1 As Bit)
Union All
Select
    DmvTableName = Cast('TMSCHEMA_EXPRESSIONS' As NVarchar(128))
  , isActive     = Cast(1 As Bit)
Union All
--import issues
Select
    DmvTableName = Cast('TMSCHEMA_FORMAT_STRING_DEFINITIONS' As NVarchar(128))
  , isActive     = Cast(0 As Bit)
Union All
Select
    DmvTableName = Cast('TMSCHEMA_EXTENDED_PROPERTIES' As NVarchar(128))
  , isActive     = Cast(1 As Bit)
Union All
Select
    DmvTableName = Cast('TMSCHEMA_HIERARCHIES' As NVarchar(128))
  , isActive     = Cast(1 As Bit)
Union All
Select
    DmvTableName = Cast('TMSCHEMA_KPIS' As NVarchar(128))
  , isActive     = Cast(1 As Bit)
Union All
Select
    DmvTableName = Cast('TMSCHEMA_LEVELS' As NVarchar(128))
  , isActive     = Cast(1 As Bit)
Union All
Select
    DmvTableName = Cast('TMSCHEMA_MEASURES' As NVarchar(128))
  , isActive     = Cast(1 As Bit)
Union All
Select
    DmvTableName = Cast('TMSCHEMA_MODEL' As NVarchar(128))
  , isActive     = Cast(1 As Bit)
Union All
Select
    DmvTableName = Cast('TMSCHEMA_OBJECT_TRANSLATIONS' As NVarchar(128))
  , isActive     = Cast(1 As Bit)
Union All
Select
    DmvTableName = Cast('TMSCHEMA_PARTITIONS' As NVarchar(128))
  , isActive     = Cast(1 As Bit)
Union All
Select
    DmvTableName = Cast('TMSCHEMA_PERSPECTIVE_COLUMNS' As NVarchar(128))
  , isActive     = Cast(1 As Bit)
Union All
Select
    DmvTableName = Cast('TMSCHEMA_PERSPECTIVE_HIERARCHIES' As NVarchar(128))
  , isActive     = Cast(1 As Bit)
Union All
Select
    DmvTableName = Cast('TMSCHEMA_PERSPECTIVE_MEASURES' As NVarchar(128))
  , isActive     = Cast(1 As Bit)
Union All
Select
    DmvTableName = Cast('TMSCHEMA_PERSPECTIVE_TABLES' As NVarchar(128))
  , isActive     = Cast(1 As Bit)
Union All
Select
    DmvTableName = Cast('TMSCHEMA_PERSPECTIVES' As NVarchar(128))
  , isActive     = Cast(1 As Bit)
Union All
--import issues
Select
    DmvTableName = Cast('TMSCHEMA_QUERY_GROUPS' As NVarchar(128))
  , isActive     = Cast(0 As Bit)
Union All
Select
    DmvTableName = Cast('TMSCHEMA_RELATIONSHIPS' As NVarchar(128))
  , isActive     = Cast(1 As Bit)
Union All
Select
    DmvTableName = Cast('TMSCHEMA_ROLE_MEMBERSHIPS' As NVarchar(128))
  , isActive     = Cast(1 As Bit)
Union All
Select
    DmvTableName = Cast('TMSCHEMA_ROLES' As NVarchar(128))
  , isActive     = Cast(1 As Bit)
Union All
Select
    DmvTableName = Cast('TMSCHEMA_TABLES' As NVarchar(128))
  , isActive     = Cast(1 As Bit)
Union All
Select
    DmvTableName = Cast('TMSCHEMA_TABLE_PERMISSIONS' As NVarchar(128))
  , isActive     = Cast(1 As Bit)
Union All
Select
    DmvTableName = Cast('TMSCHEMA_VARIATIONS' As NVarchar(128))
  , isActive     = Cast(1 As Bit)
----
=======
// end::sql_modules_definition[]


