// tag::HeaderFullDisplayName[]
= dbeaver.DataSources_DbSchemaTable - V
// end::HeaderFullDisplayName[]

== existing_properties

// tag::existing_properties[]

:ExistsProperty--antorareferencedlist:
:ExistsProperty--antorareferencinglist:
:ExistsProperty--is_repo_managed:
:ExistsProperty--is_ssas:
:ExistsProperty--referencedobjectlist:
:ExistsProperty--sql_modules_definition:
:ExistsProperty--FK:
:ExistsProperty--Columns:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
97BE898F-9381-EB11-84E9-A81E8446D5B0
// end::RepoObject_guid[]

== RepoObject_FullDisplayName2

// tag::RepoObject_FullDisplayName2[]
dbeaver.DataSources_DbSchemaTable
// end::RepoObject_FullDisplayName2[]

== SysObject_type

// tag::SysObject_type[]
V 
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
view
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
1732201221
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2021-08-17 18:49:49
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]
[discrete]
== _


[#column-bulkcolumn]
=== BulkColumn

[cols="d,8a,m,m,m"]
|===
|
|BulkColumn
|varchar(max)
|NULL
|
|===

.Referencing Columns
--
* xref:dbeaver.datasources_dbschematable_constraint.adoc#column-bulkcolumn[+dbeaver.DataSources_DbSchemaTable_constraint.BulkColumn+]
* xref:dbeaver.datasources_dbschematable_fk.adoc#column-bulkcolumn[+dbeaver.DataSources_DbSchemaTable_FK.BulkColumn+]
--


[#column-id]
=== id

[cols="d,8a,m,m,m"]
|===
|
|id
|int
|NOT NULL
|
|===

.Referencing Columns
--
* xref:dbeaver.datasources_dbschematable_constraint.adoc#column-id[+dbeaver.DataSources_DbSchemaTable_constraint.id+]
* xref:dbeaver.datasources_dbschematable_fk.adoc#column-id[+dbeaver.DataSources_DbSchemaTable_FK.id+]
--


[#column-isunderlinejson]
=== is_json

[cols="d,8a,m,m,m"]
|===
|
|is_json
|int
|NULL
|
|===

.Referencing Columns
--
* xref:dbeaver.datasources_dbschematable_constraint.adoc#column-isunderlinejson[+dbeaver.DataSources_DbSchemaTable_constraint.is_json+]
* xref:dbeaver.datasources_dbschematable_fk.adoc#column-isunderlinejson[+dbeaver.DataSources_DbSchemaTable_FK.is_json+]
--


[#column-virtualmodelunderlinedatabase]
=== VirtualModel_database

[cols="d,8a,m,m,m"]
|===
|
|VirtualModel_database
|nvarchar(4000)
|NOT NULL
|
|===

.Referencing Columns
--
* xref:dbeaver.datasources_dbschematable_constraint.adoc#column-virtualmodelunderlinedatabase[+dbeaver.DataSources_DbSchemaTable_constraint.VirtualModel_database+]
* xref:dbeaver.datasources_dbschematable_fk.adoc#column-virtualmodelunderlinedatabase[+dbeaver.DataSources_DbSchemaTable_FK.VirtualModel_database+]
--


[#column-virtualmodelunderlinedatabaseunderlinejson]
=== VirtualModel_database_json

[cols="d,8a,m,m,m"]
|===
|
|VirtualModel_database_json
|nvarchar(max)
|NULL
|
|===

.Referencing Columns
--
* xref:dbeaver.datasources_dbschematable_constraint.adoc#column-virtualmodelunderlinedatabaseunderlinejson[+dbeaver.DataSources_DbSchemaTable_constraint.VirtualModel_database_json+]
* xref:dbeaver.datasources_dbschematable_fk.adoc#column-virtualmodelunderlinedatabaseunderlinejson[+dbeaver.DataSources_DbSchemaTable_FK.VirtualModel_database_json+]
--


[#column-virtualmodelunderlinejson]
=== VirtualModel_json

[cols="d,8a,m,m,m"]
|===
|
|VirtualModel_json
|nvarchar(max)
|NULL
|
|===

.Referencing Columns
--
* xref:dbeaver.datasources_dbschematable_constraint.adoc#column-virtualmodelunderlinejson[+dbeaver.DataSources_DbSchemaTable_constraint.VirtualModel_json+]
* xref:dbeaver.datasources_dbschematable_fk.adoc#column-virtualmodelunderlinejson[+dbeaver.DataSources_DbSchemaTable_FK.VirtualModel_json+]
--


[#column-virtualmodelunderlinekey]
=== VirtualModel_key

[cols="d,8a,m,m,m"]
|===
|
|VirtualModel_key
|nvarchar(4000)
|NOT NULL
|
|===

.Referencing Columns
--
* xref:dbeaver.datasources_dbschematable_constraint.adoc#column-virtualmodelunderlinekey[+dbeaver.DataSources_DbSchemaTable_constraint.VirtualModel_key+]
* xref:dbeaver.datasources_dbschematable_fk.adoc#column-virtualmodelunderlinekey[+dbeaver.DataSources_DbSchemaTable_FK.VirtualModel_key+]
--


[#column-virtualmodelunderlineschema]
=== VirtualModel_schema

[cols="d,8a,m,m,m"]
|===
|
|VirtualModel_schema
|nvarchar(4000)
|NOT NULL
|
|===

.Referencing Columns
--
* xref:dbeaver.datasources_dbschematable_constraint.adoc#column-virtualmodelunderlineschema[+dbeaver.DataSources_DbSchemaTable_constraint.VirtualModel_schema+]
* xref:dbeaver.datasources_dbschematable_fk.adoc#column-virtualmodelunderlineschema[+dbeaver.DataSources_DbSchemaTable_FK.VirtualModel_schema+]
--


[#column-virtualmodelunderlineschemaunderlinejson]
=== VirtualModel_schema_json

[cols="d,8a,m,m,m"]
|===
|
|VirtualModel_schema_json
|nvarchar(max)
|NULL
|
|===

.Referencing Columns
--
* xref:dbeaver.datasources_dbschematable_constraint.adoc#column-virtualmodelunderlineschemaunderlinejson[+dbeaver.DataSources_DbSchemaTable_constraint.VirtualModel_schema_json+]
* xref:dbeaver.datasources_dbschematable_fk.adoc#column-virtualmodelunderlineschemaunderlinejson[+dbeaver.DataSources_DbSchemaTable_FK.VirtualModel_schema_json+]
--


[#column-virtualmodelunderlinetable]
=== VirtualModel_table

[cols="d,8a,m,m,m"]
|===
|
|VirtualModel_table
|nvarchar(500)
|NULL
|
|===

.Referencing Columns
--
* xref:dbeaver.datasources_dbschematable_constraint.adoc#column-virtualmodelunderlinetable[+dbeaver.DataSources_DbSchemaTable_constraint.VirtualModel_table+]
* xref:dbeaver.datasources_dbschematable_fk.adoc#column-virtualmodelunderlinetable[+dbeaver.DataSources_DbSchemaTable_FK.VirtualModel_table+]
--


[#column-virtualmodelunderlinetableunderlineconstraintsunderlinejson]
=== VirtualModel_table_constraints_json

[cols="d,8a,m,m,m"]
|===
|
|VirtualModel_table_constraints_json
|nvarchar(max)
|NULL
|
|===

.Referencing Columns
--
* xref:dbeaver.datasources_dbschematable_constraint.adoc#column-virtualmodelunderlinetableunderlineconstraintsunderlinejson[+dbeaver.DataSources_DbSchemaTable_constraint.VirtualModel_table_constraints_json+]
--


[#column-virtualmodelunderlinetableunderlinefkunderlinejson]
=== VirtualModel_table_FK_json

[cols="d,8a,m,m,m"]
|===
|
|VirtualModel_table_FK_json
|nvarchar(max)
|NULL
|
|===

.Referencing Columns
--
* xref:dbeaver.datasources_dbschematable_fk.adoc#column-virtualmodelunderlinetableunderlinefkunderlinejson[+dbeaver.DataSources_DbSchemaTable_FK.VirtualModel_table_FK_json+]
--


[#column-virtualmodelunderlinetableunderlinejson]
=== VirtualModel_table_json

[cols="d,8a,m,m,m"]
|===
|
|VirtualModel_table_json
|nvarchar(max)
|NULL
|
|===

.Referencing Columns
--
* xref:dbeaver.datasources_dbschematable_constraint.adoc#column-virtualmodelunderlinetableunderlinejson[+dbeaver.DataSources_DbSchemaTable_constraint.VirtualModel_table_json+]
* xref:dbeaver.datasources_dbschematable_fk.adoc#column-virtualmodelunderlinetableunderlinejson[+dbeaver.DataSources_DbSchemaTable_FK.VirtualModel_table_json+]
--


[#column-virtualmodelunderlinetableunderlinepropertiesunderlinejson]
=== VirtualModel_table_properties_json

[cols="d,8a,m,m,m"]
|===
|
|VirtualModel_table_properties_json
|nvarchar(max)
|NULL
|
|===


[#column-virtualmodels]
=== VirtualModels

[cols="d,8a,m,m,m"]
|===
|
|VirtualModels
|nvarchar(max)
|NULL
|
|===

.Referencing Columns
--
* xref:dbeaver.datasources_dbschematable_constraint.adoc#column-virtualmodels[+dbeaver.DataSources_DbSchemaTable_constraint.VirtualModels+]
* xref:dbeaver.datasources_dbschematable_fk.adoc#column-virtualmodels[+dbeaver.DataSources_DbSchemaTable_FK.VirtualModels+]
--


// end::AntoraColumnDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]















// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]
|
|<<column-bulkcolumn>>
|varchar(max)
|NULL
|

|
|<<column-id>>
|int
|NOT NULL
|

|
|<<column-isunderlinejson>>
|int
|NULL
|

|
|<<column-virtualmodelunderlinedatabase>>
|nvarchar(4000)
|NOT NULL
|

|
|<<column-virtualmodelunderlinedatabaseunderlinejson>>
|nvarchar(max)
|NULL
|

|
|<<column-virtualmodelunderlinejson>>
|nvarchar(max)
|NULL
|

|
|<<column-virtualmodelunderlinekey>>
|nvarchar(4000)
|NOT NULL
|

|
|<<column-virtualmodelunderlineschema>>
|nvarchar(4000)
|NOT NULL
|

|
|<<column-virtualmodelunderlineschemaunderlinejson>>
|nvarchar(max)
|NULL
|

|
|<<column-virtualmodelunderlinetable>>
|nvarchar(500)
|NULL
|

|
|<<column-virtualmodelunderlinetableunderlineconstraintsunderlinejson>>
|nvarchar(max)
|NULL
|

|
|<<column-virtualmodelunderlinetableunderlinefkunderlinejson>>
|nvarchar(max)
|NULL
|

|
|<<column-virtualmodelunderlinetableunderlinejson>>
|nvarchar(max)
|NULL
|

|
|<<column-virtualmodelunderlinetableunderlinepropertiesunderlinejson>>
|nvarchar(max)
|NULL
|

|
|<<column-virtualmodels>>
|nvarchar(max)
|NULL
|

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

// end::AntoraIndexList[]

== AntoraMeasureDetails

// tag::AntoraMeasureDetails[]

// end::AntoraMeasureDetails[]

== AntoraMeasureDescriptions



== AntoraParameterList

// tag::AntoraParameterList[]

// end::AntoraParameterList[]

== AntoraXrefCulturesList

// tag::AntoraXrefCulturesList[]
* xref:dhw:sqldb:dbeaver.datasources_dbschematable.adoc[] - 
// end::AntoraXrefCulturesList[]

== cultures_count

// tag::cultures_count[]
1
// end::cultures_count[]

== Other tags

source: property.RepoObjectProperty_cross As rop_cross


=== additional_reference_csv

// tag::additional_reference_csv[]

// end::additional_reference_csv[]


=== AdocUspSteps

// tag::adocuspsteps[]

// end::adocuspsteps[]


=== AntoraReferencedList

// tag::antorareferencedlist[]
* xref:dhw:sqldb:dbeaver.datasources.adoc[]
// end::antorareferencedlist[]


=== AntoraReferencingList

// tag::antorareferencinglist[]
* xref:dhw:sqldb:dbeaver.datasources_dbschematable_constraint.adoc[]
* xref:dhw:sqldb:dbeaver.datasources_dbschematable_fk.adoc[]
// end::antorareferencinglist[]


=== Description

// tag::description[]

// end::description[]


=== exampleUsage

// tag::exampleusage[]

// end::exampleusage[]


=== exampleUsage_2

// tag::exampleusage_2[]

// end::exampleusage_2[]


=== exampleUsage_3

// tag::exampleusage_3[]

// end::exampleusage_3[]


=== exampleUsage_4

// tag::exampleusage_4[]

// end::exampleusage_4[]


=== exampleUsage_5

// tag::exampleusage_5[]

// end::exampleusage_5[]


=== exampleWrong_Usage

// tag::examplewrong_usage[]

// end::examplewrong_usage[]


=== has_execution_plan_issue

// tag::has_execution_plan_issue[]

// end::has_execution_plan_issue[]


=== has_get_referenced_issue

// tag::has_get_referenced_issue[]

// end::has_get_referenced_issue[]


=== has_history

// tag::has_history[]

// end::has_history[]


=== has_history_columns

// tag::has_history_columns[]

// end::has_history_columns[]


=== InheritanceType

// tag::inheritancetype[]

// end::inheritancetype[]


=== is_persistence

// tag::is_persistence[]

// end::is_persistence[]


=== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]

// end::is_persistence_check_duplicate_per_pk[]


=== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]

// end::is_persistence_check_for_empty_source[]


=== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]

// end::is_persistence_delete_changed[]


=== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]

// end::is_persistence_delete_missing[]


=== is_persistence_insert

// tag::is_persistence_insert[]

// end::is_persistence_insert[]


=== is_persistence_truncate

// tag::is_persistence_truncate[]

// end::is_persistence_truncate[]


=== is_persistence_update_changed

// tag::is_persistence_update_changed[]

// end::is_persistence_update_changed[]


=== is_repo_managed

// tag::is_repo_managed[]
0
// end::is_repo_managed[]


=== is_ssas

// tag::is_ssas[]
0
// end::is_ssas[]


=== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


=== MS_Description

// tag::ms_description[]

// end::ms_description[]


=== persistence_source_RepoObject_fullname

// tag::persistence_source_repoobject_fullname[]

// end::persistence_source_repoobject_fullname[]


=== persistence_source_RepoObject_fullname2

// tag::persistence_source_repoobject_fullname2[]

// end::persistence_source_repoobject_fullname2[]


=== persistence_source_RepoObject_guid

// tag::persistence_source_repoobject_guid[]

// end::persistence_source_repoobject_guid[]


=== persistence_source_RepoObject_xref

// tag::persistence_source_repoobject_xref[]

// end::persistence_source_repoobject_xref[]


=== pk_index_guid

// tag::pk_index_guid[]

// end::pk_index_guid[]


=== pk_IndexPatternColumnDatatype

// tag::pk_indexpatterncolumndatatype[]

// end::pk_indexpatterncolumndatatype[]


=== pk_IndexPatternColumnName

// tag::pk_indexpatterncolumnname[]

// end::pk_indexpatterncolumnname[]


=== pk_IndexSemanticGroup

// tag::pk_indexsemanticgroup[]

// end::pk_indexsemanticgroup[]


=== ReferencedObjectList

// tag::referencedobjectlist[]
* [dbeaver].[DataSources]
// end::referencedobjectlist[]


=== usp_persistence_RepoObject_guid

// tag::usp_persistence_repoobject_guid[]

// end::usp_persistence_repoobject_guid[]


=== UspExamples

// tag::uspexamples[]

// end::uspexamples[]


=== uspgenerator_usp_id

// tag::uspgenerator_usp_id[]

// end::uspgenerator_usp_id[]


=== UspParameters

// tag::uspparameters[]

// end::uspparameters[]

== Boolean Attributes

source: property.RepoObjectProperty WHERE property_int = 1

// tag::boolean_attributes[]


// end::boolean_attributes[]

== PlantUML diagrams

=== PlantUML Entity

// tag::puml_entity[]
[plantuml, entity-{docname}, svg, subs=macros]
....
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:dbeaver.datasources_dbschematable.adoc[]" as dbeaver.DataSources_DbSchemaTable << V >> {
  BulkColumn : (varchar(max))
  - id : (int)
  is_json : (int)
  - VirtualModel_database : (nvarchar(4000))
  VirtualModel_database_json : (nvarchar(max))
  VirtualModel_json : (nvarchar(max))
  - VirtualModel_key : (nvarchar(4000))
  - VirtualModel_schema : (nvarchar(4000))
  VirtualModel_schema_json : (nvarchar(max))
  VirtualModel_table : (nvarchar(500))
  VirtualModel_table_constraints_json : (nvarchar(max))
  VirtualModel_table_FK_json : (nvarchar(max))
  VirtualModel_table_json : (nvarchar(max))
  VirtualModel_table_properties_json : (nvarchar(max))
  VirtualModels : (nvarchar(max))
  --
}
....

// end::puml_entity[]

=== PlantUML Entity 1 1 FK

// tag::puml_entity_1_1_fk[]
[plantuml, entity_1_1_fk-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:dbeaver.datasources_dbschematable.adoc[]" as dbeaver.DataSources_DbSchemaTable << V >> {

}



footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_fk[]

=== PlantUML 1 1 ObjectRef

// tag::puml_entity_1_1_objectref[]
[plantuml, entity_1_1_objectref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:dbeaver.datasources.adoc[]" as dbeaver.DataSources << U >> {
  - **id** : (int)
  --
}

entity "puml-link:dhw:sqldb:dbeaver.datasources_dbschematable.adoc[]" as dbeaver.DataSources_DbSchemaTable << V >> {
  --
}

entity "puml-link:dhw:sqldb:dbeaver.datasources_dbschematable_constraint.adoc[]" as dbeaver.DataSources_DbSchemaTable_constraint << V >> {
  --
}

entity "puml-link:dhw:sqldb:dbeaver.datasources_dbschematable_fk.adoc[]" as dbeaver.DataSources_DbSchemaTable_FK << V >> {
  --
}

dbeaver.DataSources <.. dbeaver.DataSources_DbSchemaTable
dbeaver.DataSources_DbSchemaTable <.. dbeaver.DataSources_DbSchemaTable_constraint
dbeaver.DataSources_DbSchemaTable <.. dbeaver.DataSources_DbSchemaTable_FK

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_objectref[]

=== PlantUML 30 0 ObjectRef

// tag::puml_entity_30_0_objectref[]
[plantuml, entity_30_0_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:dbeaver.datasources.adoc[]" as dbeaver.DataSources << U >> {
  - **id** : (int)
  --
}

entity "puml-link:dhw:sqldb:dbeaver.datasources_dbschematable.adoc[]" as dbeaver.DataSources_DbSchemaTable << V >> {
  --
}

dbeaver.DataSources <.. dbeaver.DataSources_DbSchemaTable

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_30_0_objectref[]

=== PlantUML 0 30 ObjectRef

// tag::puml_entity_0_30_objectref[]
[plantuml, entity_0_30_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:dbeaver.datasources_dbschematable.adoc[]" as dbeaver.DataSources_DbSchemaTable << V >> {
  --
}

entity "puml-link:dhw:sqldb:dbeaver.datasources_dbschematable_constraint.adoc[]" as dbeaver.DataSources_DbSchemaTable_constraint << V >> {
  --
}

entity "puml-link:dhw:sqldb:dbeaver.datasources_dbschematable_fk.adoc[]" as dbeaver.DataSources_DbSchemaTable_FK << V >> {
  --
}

dbeaver.DataSources_DbSchemaTable <.. dbeaver.DataSources_DbSchemaTable_FK
dbeaver.DataSources_DbSchemaTable <.. dbeaver.DataSources_DbSchemaTable_constraint

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_0_30_objectref[]

=== PlantUML 1 1 ColumnRef

// tag::puml_entity_1_1_colref[]
[plantuml, entity_1_1_colref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:dbeaver.datasources.adoc[]" as dbeaver.DataSources << U >> {
  - **id** : (int)
  BulkColumn : (varchar(max))
  ~ is_json : (int)
  --
}

entity "puml-link:dhw:sqldb:dbeaver.datasources_dbschematable.adoc[]" as dbeaver.DataSources_DbSchemaTable << V >> {
  BulkColumn : (varchar(max))
  - id : (int)
  is_json : (int)
  - VirtualModel_database : (nvarchar(4000))
  VirtualModel_database_json : (nvarchar(max))
  VirtualModel_json : (nvarchar(max))
  - VirtualModel_key : (nvarchar(4000))
  - VirtualModel_schema : (nvarchar(4000))
  VirtualModel_schema_json : (nvarchar(max))
  VirtualModel_table : (nvarchar(500))
  VirtualModel_table_constraints_json : (nvarchar(max))
  VirtualModel_table_FK_json : (nvarchar(max))
  VirtualModel_table_json : (nvarchar(max))
  VirtualModel_table_properties_json : (nvarchar(max))
  VirtualModels : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:dbeaver.datasources_dbschematable_constraint.adoc[]" as dbeaver.DataSources_DbSchemaTable_constraint << V >> {
  BulkColumn : (varchar(max))
  - id : (int)
  is_json : (int)
  - key : (nvarchar(4000))
  - type : (tinyint)
  value : (nvarchar(max))
  - VirtualModel_database : (nvarchar(4000))
  VirtualModel_database_json : (nvarchar(max))
  VirtualModel_json : (nvarchar(max))
  - VirtualModel_key : (nvarchar(4000))
  - VirtualModel_schema : (nvarchar(4000))
  VirtualModel_schema_json : (nvarchar(max))
  VirtualModel_table : (nvarchar(500))
  VirtualModel_table_constraint_attributes_json : (nvarchar(max))
  VirtualModel_table_constraint_type : (nvarchar(max))
  VirtualModel_table_constraints_json : (nvarchar(max))
  VirtualModel_table_json : (nvarchar(max))
  VirtualModels : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:dbeaver.datasources_dbschematable_fk.adoc[]" as dbeaver.DataSources_DbSchemaTable_FK << V >> {
  BulkColumn : (varchar(max))
  - id : (int)
  is_json : (int)
  - key : (nvarchar(4000))
  - type : (tinyint)
  value : (nvarchar(max))
  - VirtualModel_database : (nvarchar(4000))
  VirtualModel_database_json : (nvarchar(max))
  VirtualModel_json : (nvarchar(max))
  - VirtualModel_key : (nvarchar(4000))
  - VirtualModel_schema : (nvarchar(4000))
  VirtualModel_schema_json : (nvarchar(max))
  VirtualModel_table : (nvarchar(500))
  VirtualModel_table_FK_attributes_json : (nvarchar(max))
  VirtualModel_table_FK_constraint : (nvarchar(500))
  VirtualModel_table_FK_entity : (nvarchar(500))
  VirtualModel_table_FK_json : (nvarchar(max))
  VirtualModel_table_json : (nvarchar(max))
  VirtualModels : (nvarchar(max))
  --
}

dbeaver.DataSources <.. dbeaver.DataSources_DbSchemaTable
dbeaver.DataSources_DbSchemaTable <.. dbeaver.DataSources_DbSchemaTable_constraint
dbeaver.DataSources_DbSchemaTable <.. dbeaver.DataSources_DbSchemaTable_FK
"dbeaver.DataSources_DbSchemaTable::BulkColumn" <-- "dbeaver.DataSources_DbSchemaTable_constraint::BulkColumn"
"dbeaver.DataSources_DbSchemaTable::BulkColumn" <-- "dbeaver.DataSources_DbSchemaTable_FK::BulkColumn"
"dbeaver.DataSources_DbSchemaTable::id" <-- "dbeaver.DataSources_DbSchemaTable_FK::id"
"dbeaver.DataSources_DbSchemaTable::id" <-- "dbeaver.DataSources_DbSchemaTable_constraint::id"
"dbeaver.DataSources_DbSchemaTable::is_json" <-- "dbeaver.DataSources_DbSchemaTable_constraint::is_json"
"dbeaver.DataSources_DbSchemaTable::is_json" <-- "dbeaver.DataSources_DbSchemaTable_FK::is_json"
"dbeaver.DataSources_DbSchemaTable::VirtualModel_database" <-- "dbeaver.DataSources_DbSchemaTable_constraint::VirtualModel_database"
"dbeaver.DataSources_DbSchemaTable::VirtualModel_database" <-- "dbeaver.DataSources_DbSchemaTable_FK::VirtualModel_database"
"dbeaver.DataSources_DbSchemaTable::VirtualModel_database_json" <-- "dbeaver.DataSources_DbSchemaTable_constraint::VirtualModel_database_json"
"dbeaver.DataSources_DbSchemaTable::VirtualModel_database_json" <-- "dbeaver.DataSources_DbSchemaTable_FK::VirtualModel_database_json"
"dbeaver.DataSources_DbSchemaTable::VirtualModel_json" <-- "dbeaver.DataSources_DbSchemaTable_constraint::VirtualModel_json"
"dbeaver.DataSources_DbSchemaTable::VirtualModel_json" <-- "dbeaver.DataSources_DbSchemaTable_FK::VirtualModel_json"
"dbeaver.DataSources_DbSchemaTable::VirtualModel_key" <-- "dbeaver.DataSources_DbSchemaTable_constraint::VirtualModel_key"
"dbeaver.DataSources_DbSchemaTable::VirtualModel_key" <-- "dbeaver.DataSources_DbSchemaTable_FK::VirtualModel_key"
"dbeaver.DataSources_DbSchemaTable::VirtualModel_schema" <-- "dbeaver.DataSources_DbSchemaTable_FK::VirtualModel_schema"
"dbeaver.DataSources_DbSchemaTable::VirtualModel_schema" <-- "dbeaver.DataSources_DbSchemaTable_constraint::VirtualModel_schema"
"dbeaver.DataSources_DbSchemaTable::VirtualModel_schema_json" <-- "dbeaver.DataSources_DbSchemaTable_constraint::VirtualModel_schema_json"
"dbeaver.DataSources_DbSchemaTable::VirtualModel_schema_json" <-- "dbeaver.DataSources_DbSchemaTable_FK::VirtualModel_schema_json"
"dbeaver.DataSources_DbSchemaTable::VirtualModel_table" <-- "dbeaver.DataSources_DbSchemaTable_FK::VirtualModel_table"
"dbeaver.DataSources_DbSchemaTable::VirtualModel_table" <-- "dbeaver.DataSources_DbSchemaTable_constraint::VirtualModel_table"
"dbeaver.DataSources_DbSchemaTable::VirtualModel_table_constraints_json" <-- "dbeaver.DataSources_DbSchemaTable_constraint::VirtualModel_table_constraints_json"
"dbeaver.DataSources_DbSchemaTable::VirtualModel_table_FK_json" <-- "dbeaver.DataSources_DbSchemaTable_FK::VirtualModel_table_FK_json"
"dbeaver.DataSources_DbSchemaTable::VirtualModel_table_json" <-- "dbeaver.DataSources_DbSchemaTable_FK::VirtualModel_table_json"
"dbeaver.DataSources_DbSchemaTable::VirtualModel_table_json" <-- "dbeaver.DataSources_DbSchemaTable_constraint::VirtualModel_table_json"
"dbeaver.DataSources_DbSchemaTable::VirtualModels" <-- "dbeaver.DataSources_DbSchemaTable_FK::VirtualModels"
"dbeaver.DataSources_DbSchemaTable::VirtualModels" <-- "dbeaver.DataSources_DbSchemaTable_constraint::VirtualModels"

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_colref[]


== sql_modules_definition

// tag::sql_modules_definition[]
[%collapsible]
=======
[source,sql,numbered,indent=0]
----

CREATE View dbeaver.DataSources_DbSchemaTable
As
Select
    --
    j1.*
  , j2.*
  , VirtualModel_key           = j3.[Key]
  , VirtualModel_json          = j3.Value
  , VirtualModel_database      = j4.[Key]
  , VirtualModel_database_json = j4.Value
  , VirtualModel_schema        = j5.[Key]
  , VirtualModel_schema_json   = j5.Value
  , VirtualModel_table         = Substring ( j6.[Key], 2, 500 )
  , VirtualModel_table_json    = j6.Value
  , j7.*
From
    dbeaver.DataSources As j1
    Cross Apply
    OpenJson ( j1.BulkColumn )
    With
    (
        VirtualModels NVarchar ( Max ) N'$."virtual-models"' As Json
    )                   As j2
    Cross Apply OpenJson ( j2.VirtualModels ) As j3
    Cross Apply OpenJson ( j3.Value ) As j4
    Cross Apply OpenJson ( j4.Value ) As j5
    Cross Apply OpenJson ( j5.Value ) As j6
    Cross Apply
    OpenJson ( j6.Value )
    With
    (
        VirtualModel_table_constraints_json NVarchar ( Max ) N'$.constraints' As Json
      , VirtualModel_table_FK_json NVarchar ( Max ) N'$."foreign-keys"' As Json
      , VirtualModel_table_properties_json NVarchar ( Max ) N'$.properties' As Json
    ) As j7
Where
    j1.is_json = 1
----
=======
// end::sql_modules_definition[]


