// tag::HeaderFullDisplayName[]
= docs.usp_AntoraExport - P
// end::HeaderFullDisplayName[]

== existing_properties

// tag::existing_properties[]

:ExistsProperty--adocuspsteps:
:ExistsProperty--antorareferencedlist:
:ExistsProperty--exampleusage:
:ExistsProperty--is_repo_managed:
:ExistsProperty--is_ssas:
:ExistsProperty--referencedobjectlist:
:ExistsProperty--uspgenerator_usp_id:
:ExistsProperty--uspparameters:
:ExistsProperty--sql_modules_definition:
:ExistsProperty--AntoraParameterList:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
C51B7592-0397-EB11-84F4-A81E8446D5B0
// end::RepoObject_guid[]

== RepoObject_FullDisplayName2

// tag::RepoObject_FullDisplayName2[]
docs.usp_AntoraExport
// end::RepoObject_FullDisplayName2[]

== SysObject_type

// tag::SysObject_type[]
P 
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
stored procedure
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
749245724
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2022-09-05 18:23:32
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]

// end::AntoraColumnDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]

// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

// end::AntoraIndexList[]

== AntoraMeasureDetails

// tag::AntoraMeasureDetails[]

// end::AntoraMeasureDetails[]

== AntoraMeasureDescriptions



== AntoraParameterList

// tag::AntoraParameterList[]
* @isExecuteCommand (bit)
* @execution_instance_guid (uniqueidentifier)
* @ssis_execution_id (bigint)
* @sub_execution_id (int)
* @parent_execution_log_id (bigint)
// end::AntoraParameterList[]

== AntoraXrefCulturesList

// tag::AntoraXrefCulturesList[]
* xref:dhw:sqldb:docs.usp_antoraexport.adoc[] - 
// end::AntoraXrefCulturesList[]

== cultures_count

// tag::cultures_count[]
1
// end::cultures_count[]

== Other tags

source: property.RepoObjectProperty_cross As rop_cross


=== additional_reference_csv

// tag::additional_reference_csv[]

// end::additional_reference_csv[]


=== AdocUspSteps

// tag::adocuspsteps[]
.Steps in [docs].[usp_AntoraExport]
[cols="d,15a,d"]
|===
|Number|Name (Action, Source, Target)|Parent

|210
|
*declare variables*



.Statement
[%collapsible]
=====
[source,sql,numbered]
----
DECLARE @command NVARCHAR(4000)
DECLARE @cultures_name NVARCHAR(10)
Declare @AntoraModule Varchar(50)


----
=====

|


|220
|
*Truncate Table [docs].[command]*



.Statement
[%collapsible]
=====
[source,sql,numbered]
----
Truncate Table [docs].[command]

----
=====

|


|300
|
*check Parameter AntoraDeleteFilesInModuleFolders*

* `IF [config].[fs_get_parameter_value]('AntoraDeleteFilesInModuleFolders','') = 1`
* [config].[Parameter]


.Statement
[%collapsible]
=====
[source,sql,numbered]
----
[config].[fs_get_parameter_value]('AntoraDeleteFilesInModuleFolders','') = 1
----
=====

|


|310
|
*Delete Files but not folder in AntoraModule pages and partials - by cultures_name*

* I


.Statement
[%collapsible]
=====
[source,sql,numbered]
----
Declare module_cursor Cursor Local Fast_Forward For
Select
    cultures_name
From
    docs.culture
Order By
    cultures_name

Open module_cursor

Fetch Next From module_cursor
Into
    @cultures_name

While @@Fetch_Status = 0
Begin

    /*
FORFILES /p "D:\Repos\gitlab\DataHandwerk\dhw-antora-sqldb\docs\modules\sqldb\partials" /s /m *.* /c "cmd /c if @isdir==FALSE del @path"
*/
    Set @command
        = N'FORFILES /p "'
          --
          --
          + docs.fs_AntoraModuleFolder ( @cultures_name )
          + '\partials'
          --
          + N'" /s /m *.* /c "cmd /c if @isdir==FALSE del @path"'

    Print @command
    
    INSERT Into [docs].[command]
    (command)
    VALUES(@command)

    ----Execute the BCP command
    --Exec sys.xp_cmdshell @command, no_output

    Set @command
        = N'FORFILES /p "'
          --
          --
          + docs.fs_AntoraModuleFolder ( @cultures_name )
          + '\pages'
          --
          + N'" /s /m *.* /c "cmd /c if @isdir==FALSE del @path"'

    Print @command

    INSERT Into [docs].[command]
    (command)
    VALUES(@command)

    ----Execute the BCP command
    --Exec sys.xp_cmdshell @command, no_output

    Fetch Next From module_cursor
    Into
        @cultures_name
End

Close module_cursor
Deallocate module_cursor
----
=====

|300


|320
|
*Delete Files but not folder in AntoraModule pages and partials - by SSIS AntoraModule*

* I


.Statement
[%collapsible]
=====
[source,sql,numbered]
----
Declare module_cursor Cursor Local Fast_Forward For
Select
    AntoraModule
From
    ssis.Project
Order By
    AntoraModule

Open module_cursor

Fetch Next From module_cursor
Into
    @AntoraModule

While @@Fetch_Status = 0
Begin

    /*
FORFILES /p "D:\Repos\gitlab\DataHandwerk\dhw-antora-sqldb\docs\modules\sqldb\partials" /s /m *.* /c "cmd /c if @isdir==FALSE del @path"
*/
    Set @command = N'FORFILES /p "'
                   --
                   --
                   + config.fs_get_parameter_value ( 'AntoraComponentFolder', '' ) + '\modules\' + @AntoraModule
                   --
                   + '\partials'
                   --
                   + N'" /s /m *.* /c "cmd /c if @isdir==FALSE del @path"'

    Print @command

    INSERT Into [docs].[command]
    (command)
    VALUES(@command)

    ----Execute the BCP command
    --Exec sys.xp_cmdshell @command, no_output

    Set @command = N'FORFILES /p "'
                   --
                   --
                   + config.fs_get_parameter_value ( 'AntoraComponentFolder', '' ) + '\modules\' + @AntoraModule
                   --
                   + '\pages'
                   --
                   + N'" /s /m *.* /c "cmd /c if @isdir==FALSE del @path"'

    Print @command

    INSERT Into [docs].[command]
    (command)
    VALUES(@command)

    ----Execute the BCP command
    --Exec sys.xp_cmdshell @command, no_output

    Fetch Next From module_cursor
    Into
        @AntoraModule
End

Close module_cursor
Deallocate module_cursor
----
=====

|310


|400
|
*[docs].[usp_PERSIST_RepoObject_OutputFilter_T]*

* `EXEC [docs].[usp_PERSIST_RepoObject_OutputFilter_T]`


.Statement
[%collapsible]
=====
[source,sql,numbered]
----
[docs].[usp_PERSIST_RepoObject_OutputFilter_T]
----
=====

|


|440
|
*[docs].[usp_AntoraExport_ObjectNavigation]*

* `EXEC [docs].[usp_AntoraExport_ObjectNavigation]`


.Statement
[%collapsible]
=====
[source,sql,numbered]
----
[docs].[usp_AntoraExport_ObjectNavigation]
----
=====

|


|500
|
*[docs].[usp_AntoraExport_ObjectPage]*

* `EXEC [docs].[usp_AntoraExport_ObjectPage]`


.Statement
[%collapsible]
=====
[source,sql,numbered]
----
[docs].[usp_AntoraExport_ObjectPage]
----
=====

|


|600
|
*[docs].[usp_AntoraExport_ObjectPageTemplate]*

* `EXEC [docs].[usp_AntoraExport_ObjectPageTemplate]`


.Statement
[%collapsible]
=====
[source,sql,numbered]
----
[docs].[usp_AntoraExport_ObjectPageTemplate]
----
=====

|


|800
|
*[docs].[usp_AntoraExport_ObjectPuml]*

* `EXEC [docs].[usp_AntoraExport_ObjectPuml]`


.Statement
[%collapsible]
=====
[source,sql,numbered]
----
[docs].[usp_AntoraExport_ObjectPuml]
----
=====

|


|850
|
*[docs].[usp_AntoraExport_ObjectPartialsContent]*

* `EXEC [docs].[usp_AntoraExport_ObjectPartialsContent]`


.Statement
[%collapsible]
=====
[source,sql,numbered]
----
[docs].[usp_AntoraExport_ObjectPartialsContent]
----
=====

|


|910
|
*[docs].[usp_AntoraExport_Page_IndexSemanticGroup]*

* `EXEC [docs].[usp_AntoraExport_Page_IndexSemanticGroup]`


.Statement
[%collapsible]
=====
[source,sql,numbered]
----
[docs].[usp_AntoraExport_Page_IndexSemanticGroup]
----
=====

|


|920
|
*[docs].[usp_AntoraExport_ObjectRefCyclic]*

* `EXEC [docs].[usp_AntoraExport_ObjectRefCyclic]`


.Statement
[%collapsible]
=====
[source,sql,numbered]
----
[docs].[usp_AntoraExport_ObjectRefCyclic]
----
=====

|


|1440
|
*[docs].[usp_AntoraExport_SsisNavigation]*

* `EXEC [docs].[usp_AntoraExport_SsisNavigation]`


.Statement
[%collapsible]
=====
[source,sql,numbered]
----
[docs].[usp_AntoraExport_SsisNavigation]
----
=====

|


|1500
|
*[docs].[usp_AntoraExport_SsisPage]*

* `EXEC [docs].[usp_AntoraExport_SsisPage]`


.Statement
[%collapsible]
=====
[source,sql,numbered]
----
[docs].[usp_AntoraExport_SsisPage]
----
=====

|


|1600
|
*[docs].[usp_AntoraExport_SsisPageTemplate]*

* `EXEC [docs].[usp_AntoraExport_SsisPageTemplate]`


.Statement
[%collapsible]
=====
[source,sql,numbered]
----
[docs].[usp_AntoraExport_SsisPageTemplate]
----
=====

|


|1800
|
*[docs].[usp_AntoraExport_SsisPuml]*

* `EXEC [docs].[usp_AntoraExport_SsisPuml]`


.Statement
[%collapsible]
=====
[source,sql,numbered]
----
[docs].[usp_AntoraExport_SsisPuml]
----
=====

|


|1850
|
*[docs].[usp_AntoraExport_SsisPartialsContent]*

* `EXEC [docs].[usp_AntoraExport_SsisPartialsContent]`


.Statement
[%collapsible]
=====
[source,sql,numbered]
----
[docs].[usp_AntoraExport_SsisPartialsContent]
----
=====

|


|2000
|
*INSERT Into [docs].[command] empty line*

* I


.Statement
[%collapsible]
=====
[source,sql,numbered]
----
    Set @command
        = N''
    INSERT Into [docs].[command]
    (command)
    VALUES(@command)

----
=====

|


|3000
|
*check Parameter isExecuteCommand*

* `IF @isExecuteCommand = 1`
* [config].[Parameter]


.Statement
[%collapsible]
=====
[source,sql,numbered]
----
@isExecuteCommand = 1
----
=====

|


|3010
|
*Execute commands, collected in [docs].[command], using "Exec sys.xp_cmdshell"*

* I


.Statement
[%collapsible]
=====
[source,sql,numbered]
----
Declare command_cursor Cursor Local Fast_Forward For
Select
    command
From
    docs.command
Order By
    id

Open command_cursor

Fetch Next From command_cursor
Into
    @command

While @@Fetch_Status = 0
Begin

    Print @command

    --Execute the BCP command
    Exec sys.xp_cmdshell @command, no_output

    Fetch Next From command_cursor
    Into
        @command
End

Close command_cursor
Deallocate command_cursor
----
=====

|3000

|===

// end::adocuspsteps[]


=== AntoraReferencedList

// tag::antorareferencedlist[]
* xref:dhw:sqldb:config.fs_get_parameter_value.adoc[]
* xref:dhw:sqldb:docs.command.adoc[]
* xref:dhw:sqldb:docs.culture.adoc[]
* xref:dhw:sqldb:docs.fs_antoramodulefolder.adoc[]
* xref:dhw:sqldb:docs.usp_antoraexport_objectnavigation.adoc[]
* xref:dhw:sqldb:docs.usp_antoraexport_objectpage.adoc[]
* xref:dhw:sqldb:docs.usp_antoraexport_objectpagetemplate.adoc[]
* xref:dhw:sqldb:docs.usp_antoraexport_objectpartialscontent.adoc[]
* xref:dhw:sqldb:docs.usp_antoraexport_objectpuml.adoc[]
* xref:dhw:sqldb:docs.usp_antoraexport_objectrefcyclic.adoc[]
* xref:dhw:sqldb:docs.usp_antoraexport_page_indexsemanticgroup.adoc[]
* xref:dhw:sqldb:docs.usp_antoraexport_ssisnavigation.adoc[]
* xref:dhw:sqldb:docs.usp_antoraexport_ssispage.adoc[]
* xref:dhw:sqldb:docs.usp_antoraexport_ssispagetemplate.adoc[]
* xref:dhw:sqldb:docs.usp_antoraexport_ssispartialscontent.adoc[]
* xref:dhw:sqldb:docs.usp_antoraexport_ssispuml.adoc[]
* xref:dhw:sqldb:docs.usp_persist_repoobject_outputfilter_t.adoc[]
* xref:dhw:sqldb:logs.usp_executionlog_insert.adoc[]
* xref:dhw:sqldb:ssis.project.adoc[]
// end::antorareferencedlist[]


=== AntoraReferencingList

// tag::antorareferencinglist[]

// end::antorareferencinglist[]


=== Description

// tag::description[]

// end::description[]


=== exampleUsage

// tag::exampleusage[]
--ensure consistent and existing repository guid before sql parsing:
--call repo.usp_sync_guid (quick and minimal) or repo.usp_main (takes more time)
Exec repo.usp_sync_guid;

--use sqlparser to parse sql definitions for views and import parsing results
--for example in the folder containing the sqlparser.py call
--py sqlparser.py --server localhost\sql2019 --database dhw_mydatabase

--persist sql parsing results:
Exec sqlparse.usp_sqlparse

--ensure consistent repository after sql parsing:
Exec repo.usp_main;

--export Antora documentation sources
Exec docs.usp_AntoraExport;
// end::exampleusage[]


=== exampleUsage_2

// tag::exampleusage_2[]

// end::exampleusage_2[]


=== exampleUsage_3

// tag::exampleusage_3[]

// end::exampleusage_3[]


=== exampleUsage_4

// tag::exampleusage_4[]

// end::exampleusage_4[]


=== exampleUsage_5

// tag::exampleusage_5[]

// end::exampleusage_5[]


=== exampleWrong_Usage

// tag::examplewrong_usage[]

// end::examplewrong_usage[]


=== has_execution_plan_issue

// tag::has_execution_plan_issue[]

// end::has_execution_plan_issue[]


=== has_get_referenced_issue

// tag::has_get_referenced_issue[]

// end::has_get_referenced_issue[]


=== has_history

// tag::has_history[]

// end::has_history[]


=== has_history_columns

// tag::has_history_columns[]

// end::has_history_columns[]


=== InheritanceType

// tag::inheritancetype[]

// end::inheritancetype[]


=== is_persistence

// tag::is_persistence[]

// end::is_persistence[]


=== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]

// end::is_persistence_check_duplicate_per_pk[]


=== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]

// end::is_persistence_check_for_empty_source[]


=== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]

// end::is_persistence_delete_changed[]


=== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]

// end::is_persistence_delete_missing[]


=== is_persistence_insert

// tag::is_persistence_insert[]

// end::is_persistence_insert[]


=== is_persistence_truncate

// tag::is_persistence_truncate[]

// end::is_persistence_truncate[]


=== is_persistence_update_changed

// tag::is_persistence_update_changed[]

// end::is_persistence_update_changed[]


=== is_repo_managed

// tag::is_repo_managed[]
0
// end::is_repo_managed[]


=== is_ssas

// tag::is_ssas[]
0
// end::is_ssas[]


=== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


=== MS_Description

// tag::ms_description[]

// end::ms_description[]


=== persistence_source_RepoObject_fullname

// tag::persistence_source_repoobject_fullname[]

// end::persistence_source_repoobject_fullname[]


=== persistence_source_RepoObject_fullname2

// tag::persistence_source_repoobject_fullname2[]

// end::persistence_source_repoobject_fullname2[]


=== persistence_source_RepoObject_guid

// tag::persistence_source_repoobject_guid[]

// end::persistence_source_repoobject_guid[]


=== persistence_source_RepoObject_xref

// tag::persistence_source_repoobject_xref[]

// end::persistence_source_repoobject_xref[]


=== pk_index_guid

// tag::pk_index_guid[]

// end::pk_index_guid[]


=== pk_IndexPatternColumnDatatype

// tag::pk_indexpatterncolumndatatype[]

// end::pk_indexpatterncolumndatatype[]


=== pk_IndexPatternColumnName

// tag::pk_indexpatterncolumnname[]

// end::pk_indexpatterncolumnname[]


=== pk_IndexSemanticGroup

// tag::pk_indexsemanticgroup[]

// end::pk_indexsemanticgroup[]


=== ReferencedObjectList

// tag::referencedobjectlist[]
* [config].[fs_get_parameter_value]
* [docs].[command]
* [docs].[Culture]
* [docs].[fs_AntoraModuleFolder]
* [docs].[usp_AntoraExport_ObjectNavigation]
* [docs].[usp_AntoraExport_ObjectPage]
* [docs].[usp_AntoraExport_ObjectPageTemplate]
* [docs].[usp_AntoraExport_ObjectPartialsContent]
* [docs].[usp_AntoraExport_ObjectPuml]
* [docs].[usp_AntoraExport_ObjectRefCyclic]
* [docs].[usp_AntoraExport_Page_IndexSemanticGroup]
* [docs].[usp_AntoraExport_SsisNavigation]
* [docs].[usp_AntoraExport_SsisPage]
* [docs].[usp_AntoraExport_SsisPageTemplate]
* [docs].[usp_AntoraExport_SsisPartialsContent]
* [docs].[usp_AntoraExport_SsisPuml]
* [docs].[usp_PERSIST_RepoObject_OutputFilter_T]
* [logs].[usp_ExecutionLog_insert]
* [ssis].[Project]
// end::referencedobjectlist[]


=== usp_persistence_RepoObject_guid

// tag::usp_persistence_repoobject_guid[]

// end::usp_persistence_repoobject_guid[]


=== UspExamples

// tag::uspexamples[]

// end::uspexamples[]


=== uspgenerator_usp_id

// tag::uspgenerator_usp_id[]
27
// end::uspgenerator_usp_id[]


=== UspParameters

// tag::uspparameters[]
@isExecuteCommand BIT = 0 /* specify whether the commands, collected in [docs].[command], should be executed using "Exec sys.xp_cmdshell" */
// end::uspparameters[]

== Boolean Attributes

source: property.RepoObjectProperty WHERE property_int = 1

// tag::boolean_attributes[]


// end::boolean_attributes[]

== PlantUML diagrams

=== PlantUML Entity

// tag::puml_entity[]
[plantuml, entity-{docname}, svg, subs=macros]
....
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:docs.usp_antoraexport.adoc[]" as docs.usp_AntoraExport << P >> {
  --
}
....

// end::puml_entity[]

=== PlantUML Entity 1 1 FK

// tag::puml_entity_1_1_fk[]
[plantuml, entity_1_1_fk-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}





footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_fk[]

=== PlantUML 1 1 ObjectRef

// tag::puml_entity_1_1_objectref[]
[plantuml, entity_1_1_objectref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:config.fs_get_parameter_value.adoc[]" as config.fs_get_parameter_value << FN >> {
  --
}

entity "puml-link:dhw:sqldb:docs.command.adoc[]" as docs.command << U >> {
  - **id** : (int)
  --
}

entity "puml-link:dhw:sqldb:docs.culture.adoc[]" as docs.Culture << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.fs_antoramodulefolder.adoc[]" as docs.fs_AntoraModuleFolder << FN >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport.adoc[]" as docs.usp_AntoraExport << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_objectnavigation.adoc[]" as docs.usp_AntoraExport_ObjectNavigation << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_objectpage.adoc[]" as docs.usp_AntoraExport_ObjectPage << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_objectpagetemplate.adoc[]" as docs.usp_AntoraExport_ObjectPageTemplate << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_objectpartialscontent.adoc[]" as docs.usp_AntoraExport_ObjectPartialsContent << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_objectpuml.adoc[]" as docs.usp_AntoraExport_ObjectPuml << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_objectrefcyclic.adoc[]" as docs.usp_AntoraExport_ObjectRefCyclic << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_page_indexsemanticgroup.adoc[]" as docs.usp_AntoraExport_Page_IndexSemanticGroup << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_ssisnavigation.adoc[]" as docs.usp_AntoraExport_SsisNavigation << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_ssispage.adoc[]" as docs.usp_AntoraExport_SsisPage << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_ssispagetemplate.adoc[]" as docs.usp_AntoraExport_SsisPageTemplate << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_ssispartialscontent.adoc[]" as docs.usp_AntoraExport_SsisPartialsContent << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_ssispuml.adoc[]" as docs.usp_AntoraExport_SsisPuml << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_repoobject_outputfilter_t.adoc[]" as docs.usp_PERSIST_RepoObject_OutputFilter_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:logs.usp_executionlog_insert.adoc[]" as logs.usp_ExecutionLog_insert << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.project.adoc[]" as ssis.Project << U >> {
  - **AntoraModule** : (varchar(50))
  --
}

config.fs_get_parameter_value <.. docs.usp_AntoraExport
docs.command <.. docs.usp_AntoraExport
docs.culture <.. docs.usp_AntoraExport
docs.fs_AntoraModuleFolder <.. docs.usp_AntoraExport
docs.usp_AntoraExport_ObjectNavigation <.. docs.usp_AntoraExport
docs.usp_AntoraExport_ObjectPage <.. docs.usp_AntoraExport
docs.usp_AntoraExport_ObjectPageTemplate <.. docs.usp_AntoraExport
docs.usp_AntoraExport_ObjectPartialsContent <.. docs.usp_AntoraExport
docs.usp_AntoraExport_ObjectPuml <.. docs.usp_AntoraExport
docs.usp_AntoraExport_ObjectRefCyclic <.. docs.usp_AntoraExport
docs.usp_AntoraExport_Page_IndexSemanticGroup <.. docs.usp_AntoraExport
docs.usp_AntoraExport_SsisNavigation <.. docs.usp_AntoraExport
docs.usp_AntoraExport_SsisPage <.. docs.usp_AntoraExport
docs.usp_AntoraExport_SsisPageTemplate <.. docs.usp_AntoraExport
docs.usp_AntoraExport_SsisPartialsContent <.. docs.usp_AntoraExport
docs.usp_AntoraExport_SsisPuml <.. docs.usp_AntoraExport
docs.usp_PERSIST_RepoObject_OutputFilter_T <.. docs.usp_AntoraExport
logs.usp_ExecutionLog_insert <.. docs.usp_AntoraExport
ssis.Project <.. docs.usp_AntoraExport

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_objectref[]

=== PlantUML 30 0 ObjectRef

// tag::puml_entity_30_0_objectref[]
[plantuml, entity_30_0_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:config.fs_get_parameter_value.adoc[]" as config.fs_get_parameter_value << FN >> {
  --
}

entity "puml-link:dhw:sqldb:config.ftv_dwh_database.adoc[]" as config.ftv_dwh_database << IF >> {
  --
}

entity "puml-link:dhw:sqldb:config.ftv_get_parameter_value.adoc[]" as config.ftv_get_parameter_value << IF >> {
  --
}

entity "puml-link:dhw:sqldb:config.parameter.adoc[]" as config.Parameter << U >> {
  - **Parameter_name** : (varchar(100))
  - **sub_Parameter** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:configt.join_type.adoc[]" as configT.join_type << V >> {
  - **join_type** : (varchar(16))
  --
}

entity "puml-link:dhw:sqldb:configt.parameter_default.adoc[]" as configT.Parameter_default << V >> {
  - **Parameter_name** : (varchar(52))
  - **sub_Parameter** : (nvarchar(26))
  --
}

entity "puml-link:dhw:sqldb:configt.spt_values.adoc[]" as configT.spt_values << U >> {
  --
}

entity "puml-link:dhw:sqldb:configt.type.adoc[]" as configT.type << V >> {
  **type** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:docs.antoranavlistpage_by_type.adoc[]" as docs.AntoraNavListPage_by_type << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.antoranavlistrepoobject_by_schema.adoc[]" as docs.AntoraNavListRepoObject_by_schema << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.antoranavlistrepoobject_by_schema_type.adoc[]" as docs.AntoraNavListRepoObject_by_schema_type << V >> {
  - **RepoObject_schema_name** : (nvarchar(128))
  **type** : (char(2))
  --
}

entity "puml-link:dhw:sqldb:docs.antoranavlistrepoobject_by_type.adoc[]" as docs.AntoraNavListRepoObject_by_type << V >> {
  **type** : (char(2))
  --
}

entity "puml-link:dhw:sqldb:docs.command.adoc[]" as docs.command << U >> {
  - **id** : (int)
  --
}

entity "puml-link:dhw:sqldb:docs.culture.adoc[]" as docs.Culture << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.fs_antoramodulefolder.adoc[]" as docs.fs_AntoraModuleFolder << FN >> {
  --
}

entity "puml-link:dhw:sqldb:docs.fs_cleanstringforanchorid.adoc[]" as docs.fs_cleanStringForAnchorId << FN >> {
  --
}

entity "puml-link:dhw:sqldb:docs.fs_cleanstringforfilename.adoc[]" as docs.fs_cleanStringForFilename << FN >> {
  --
}

entity "puml-link:dhw:sqldb:docs.fs_cleanstringforheader.adoc[]" as docs.fs_cleanStringForHeader << FN >> {
  --
}

entity "puml-link:dhw:sqldb:docs.fs_cleanstringforpuml.adoc[]" as docs.fs_cleanStringForPuml << FN >> {
  --
}

entity "puml-link:dhw:sqldb:docs.fs_pumlheaderlefttoright.adoc[]" as docs.fs_PumlHeaderLeftToRight << FN >> {
  --
}

entity "puml-link:dhw:sqldb:docs.fs_pumlheadertoptobottom.adoc[]" as docs.fs_PumlHeaderTopToBottom << FN >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ftv_repoobject_antoraxref.adoc[]" as docs.ftv_RepoObject_AntoraXref << IF >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ftv_repoobject_reference_plantuml_entityreflist.adoc[]" as docs.ftv_RepoObject_Reference_PlantUml_EntityRefList << IF >> {
  --
}

entity "puml-link:dhw:sqldb:docs.measure_measurepropertylist.adoc[]" as docs.Measure_MeasurePropertyList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_adoc.adoc[]" as docs.RepoObject_Adoc << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_adoc_t.adoc[]" as docs.RepoObject_Adoc_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_antoraxrefcultureslist.adoc[]" as docs.RepoObject_AntoraXrefCulturesList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_columnlist.adoc[]" as docs.RepoObject_ColumnList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_columnlist_t.adoc[]" as docs.RepoObject_ColumnList_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_indexlist.adoc[]" as docs.RepoObject_IndexList << V >> {
  **RepoObject_guid** : (uniqueidentifier)
  **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_indexlist_t.adoc[]" as docs.RepoObject_IndexList_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_measuredescriptionlist.adoc[]" as docs.RepoObject_MeasureDescriptionList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_measurelist.adoc[]" as docs.RepoObject_MeasureList << V >> {
  **RepoObject_guid** : (uniqueidentifier)
  **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_outputfilter.adoc[]" as docs.RepoObject_OutputFilter << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_outputfilter_t.adoc[]" as docs.RepoObject_OutputFilter_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_outputfilter_t_gross.adoc[]" as docs.RepoObject_OutputFilter_T_gross << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_parameterlist.adoc[]" as docs.RepoObject_ParameterList << V >> {
  **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml.adoc[]" as docs.RepoObject_Plantuml << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_colreflist_1_1.adoc[]" as docs.RepoObject_Plantuml_ColRefList_1_1 << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_entity.adoc[]" as docs.RepoObject_Plantuml_Entity << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_entity_t.adoc[]" as docs.RepoObject_Plantuml_Entity_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_fkreflist.adoc[]" as docs.RepoObject_PlantUml_FkRefList << V >> {
  **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_objectreflist_0_30.adoc[]" as docs.RepoObject_Plantuml_ObjectRefList_0_30 << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_objectreflist_1_1.adoc[]" as docs.RepoObject_Plantuml_ObjectRefList_1_1 << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_objectreflist_30_0.adoc[]" as docs.RepoObject_Plantuml_ObjectRefList_30_0 << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_pumlentityfklist.adoc[]" as docs.RepoObject_PlantUml_PumlEntityFkList << V >> {
  **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_t.adoc[]" as docs.RepoObject_Plantuml_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_adoc.adoc[]" as docs.ssis_Adoc << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageBasename** : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_adoc_t.adoc[]" as docs.ssis_Adoc_T << U >> {
  - **AntoraModule** : (varchar(50))
  - **PackageBasename** : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_dfttaskcomponentinputcolumnlist.adoc[]" as docs.ssis_DftTaskComponentInputColumnList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_dfttaskcomponentinputlist.adoc[]" as docs.ssis_DftTaskComponentInputList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_dfttaskcomponentlist.adoc[]" as docs.ssis_DftTaskComponentList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_dfttaskcomponentoutputcolumnlist.adoc[]" as docs.ssis_DftTaskComponentOutputColumnList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_dfttaskcomponentoutputlist.adoc[]" as docs.ssis_DftTaskComponentOutputList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_generallist.adoc[]" as docs.ssis_GeneralList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_navlist_package.adoc[]" as docs.ssis_navlist_package << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_packageconnectionlist.adoc[]" as docs.ssis_PackageConnectionList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_parameterlist.adoc[]" as docs.ssis_ParameterList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_projectconnectionlist.adoc[]" as docs.ssis_ProjectConnectionList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_pumldfttask.adoc[]" as docs.ssis_PumlDftTask << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_pumlpackage.adoc[]" as docs.ssis_PumlPackage << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_pumlpartialcontrolflows.adoc[]" as docs.ssis_PumlPartialControlFlows << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_pumlpartialdataflow.adoc[]" as docs.ssis_PumlPartialDataFlow << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_pumlpartialdftcomponent.adoc[]" as docs.ssis_PumlPartialDftComponent << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_pumlpartialtaskcomponent.adoc[]" as docs.ssis_PumlPartialTaskComponent << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_sqltaskparameterinnertable.adoc[]" as docs.ssis_SqlTaskParameterInnerTable << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_tasklist.adoc[]" as docs.ssis_TaskList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_variablelist.adoc[]" as docs.ssis_VariableList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport.adoc[]" as docs.usp_AntoraExport << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_objectnavigation.adoc[]" as docs.usp_AntoraExport_ObjectNavigation << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_objectpage.adoc[]" as docs.usp_AntoraExport_ObjectPage << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_objectpagetemplate.adoc[]" as docs.usp_AntoraExport_ObjectPageTemplate << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_objectpartialscontent.adoc[]" as docs.usp_AntoraExport_ObjectPartialsContent << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_objectpuml.adoc[]" as docs.usp_AntoraExport_ObjectPuml << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_objectrefcyclic.adoc[]" as docs.usp_AntoraExport_ObjectRefCyclic << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_page_indexsemanticgroup.adoc[]" as docs.usp_AntoraExport_Page_IndexSemanticGroup << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_ssisnavigation.adoc[]" as docs.usp_AntoraExport_SsisNavigation << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_ssispage.adoc[]" as docs.usp_AntoraExport_SsisPage << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_ssispagetemplate.adoc[]" as docs.usp_AntoraExport_SsisPageTemplate << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_ssispartialscontent.adoc[]" as docs.usp_AntoraExport_SsisPartialsContent << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_ssispuml.adoc[]" as docs.usp_AntoraExport_SsisPuml << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_repoobject_adoc_t.adoc[]" as docs.usp_PERSIST_RepoObject_Adoc_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_repoobject_columnlist_t.adoc[]" as docs.usp_PERSIST_RepoObject_ColumnList_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_repoobject_indexlist_t.adoc[]" as docs.usp_PERSIST_RepoObject_IndexList_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_repoobject_outputfilter_t.adoc[]" as docs.usp_PERSIST_RepoObject_OutputFilter_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_repoobject_plantuml_entity_t.adoc[]" as docs.usp_PERSIST_RepoObject_Plantuml_Entity_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_repoobject_plantuml_t.adoc[]" as docs.usp_PERSIST_RepoObject_Plantuml_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_ssis_adoc_t.adoc[]" as docs.usp_PERSIST_ssis_Adoc_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:logs.executionlog.adoc[]" as logs.ExecutionLog << U >> {
  - **id** : (bigint)
  --
}

entity "puml-link:dhw:sqldb:logs.usp_executionlog_insert.adoc[]" as logs.usp_ExecutionLog_insert << P >> {
  --
}

entity "puml-link:dhw:sqldb:property.external_repoobjectcolumnproperty.adoc[]" as property.external_RepoObjectColumnProperty << U >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.external_repoobjectproperty.adoc[]" as property.external_RepoObjectProperty << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.fs_get_repoobjectcolumnproperty_nvarchar.adoc[]" as property.fs_get_RepoObjectColumnProperty_nvarchar << FN >> {
  --
}

entity "puml-link:dhw:sqldb:property.fs_get_repoobjectproperty_nvarchar.adoc[]" as property.fs_get_RepoObjectProperty_nvarchar << FN >> {
  --
}

entity "puml-link:dhw:sqldb:property.measureproperty.adoc[]" as property.MeasureProperty << U >> {
  - **Measure_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.propertyname_measure.adoc[]" as property.PropertyName_Measure << V >> {
  **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.propertyname_measure_t.adoc[]" as property.PropertyName_Measure_T << U >> {
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.propertyname_repoobject.adoc[]" as property.PropertyName_RepoObject << V >> {
  **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.propertyname_repoobject_t.adoc[]" as property.PropertyName_RepoObject_T << U >> {
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectcolumnproperty.adoc[]" as property.RepoObjectColumnProperty << U >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectcolumnproperty_external_src.adoc[]" as property.RepoObjectColumnProperty_external_src << V >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectcolumnproperty_external_tgt.adoc[]" as property.RepoObjectColumnProperty_external_tgt << V >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty.adoc[]" as property.RepoObjectProperty << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty_cross.adoc[]" as property.RepoObjectProperty_cross << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty_external_src.adoc[]" as property.RepoObjectProperty_external_src << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty_external_tgt.adoc[]" as property.RepoObjectProperty_external_tgt << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty_selectedpropertyname_split.adoc[]" as property.RepoObjectProperty_SelectedPropertyName_split << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference.adoc[]" as reference.additional_Reference << U >> {
  # **tik_hash_c** : (nvarchar(32))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_database.adoc[]" as reference.additional_Reference_database << V >> {
  - **AntoraComponent** : (nvarchar(128))
  - **AntoraModule** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_database_t.adoc[]" as reference.additional_Reference_database_T << U >> {
  - **AntoraComponent** : (nvarchar(128))
  - **AntoraModule** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_from_properties_src.adoc[]" as reference.additional_Reference_from_properties_src << V >> {
  **referenced_AntoraComponent** : (nvarchar(max))
  **referenced_AntoraModule** : (nvarchar(max))
  **referenced_Schema** : (nvarchar(max))
  **referenced_Object** : (nvarchar(max))
  **referenced_Column** : (nvarchar(max))
  **referencing_AntoraComponent** : (nvarchar(max))
  **referencing_AntoraModule** : (nvarchar(max))
  **referencing_Schema** : (nvarchar(max))
  **referencing_Object** : (nvarchar(max))
  **referencing_Column** : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_from_properties_tgt.adoc[]" as reference.additional_Reference_from_properties_tgt << V >> {
  - **referenced_AntoraComponent** : (nvarchar(128))
  - **referenced_AntoraModule** : (nvarchar(128))
  - **referenced_Schema** : (nvarchar(128))
  - **referenced_Object** : (nvarchar(128))
  **referenced_Column** : (nvarchar(128))
  - **referencing_AntoraComponent** : (nvarchar(128))
  - **referencing_AntoraModule** : (nvarchar(128))
  - **referencing_Schema** : (nvarchar(128))
  - **referencing_Object** : (nvarchar(128))
  **referencing_Column** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_from_ssas_src.adoc[]" as reference.additional_Reference_from_ssas_src << V >> {
  **referenced_AntoraComponent** : (nvarchar(128))
  **referenced_AntoraModule** : (nvarchar(128))
  **referenced_Schema** : (nvarchar(max))
  **referenced_Object** : (nvarchar(max))
  **referenced_Column** : (nvarchar(500))
  **referencing_AntoraComponent** : (nvarchar(max))
  **referencing_AntoraModule** : (nvarchar(max))
  - **referencing_Schema** : (nvarchar(128))
  - **referencing_Object** : (nvarchar(128))
  **referencing_Column** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_from_ssas_tgt.adoc[]" as reference.additional_Reference_from_ssas_tgt << V >> {
  - **referenced_AntoraComponent** : (nvarchar(128))
  - **referenced_AntoraModule** : (nvarchar(128))
  - **referenced_Schema** : (nvarchar(128))
  - **referenced_Object** : (nvarchar(128))
  **referenced_Column** : (nvarchar(128))
  - **referencing_AntoraComponent** : (nvarchar(128))
  - **referencing_AntoraModule** : (nvarchar(128))
  - **referencing_Schema** : (nvarchar(128))
  - **referencing_Object** : (nvarchar(128))
  **referencing_Column** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_guid.adoc[]" as reference.additional_Reference_guid << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_is_external.adoc[]" as reference.additional_Reference_is_external << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_object.adoc[]" as reference.additional_Reference_Object << V >> {
  - **AntoraComponent** : (nvarchar(128))
  - **AntoraModule** : (nvarchar(128))
  - **SchemaName** : (nvarchar(128))
  - **ObjectName** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_object_t.adoc[]" as reference.additional_Reference_Object_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_objectcolumn.adoc[]" as reference.additional_Reference_ObjectColumn << V >> {
  - **AntoraComponent** : (nvarchar(128))
  - **AntoraModule** : (nvarchar(128))
  - **SchemaName** : (nvarchar(128))
  - **ObjectName** : (nvarchar(128))
  **ColumnName** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_objectcolumn_t.adoc[]" as reference.additional_Reference_ObjectColumn_T << U >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_wo_columns_from_properties_src.adoc[]" as reference.additional_Reference_wo_columns_from_properties_src << V >> {
  **referenced_AntoraComponent** : (nvarchar(max))
  **referenced_AntoraModule** : (nvarchar(max))
  **referenced_Schema** : (nvarchar(max))
  **referenced_Object** : (nvarchar(max))
  **referencing_AntoraComponent** : (nvarchar(max))
  **referencing_AntoraModule** : (nvarchar(max))
  **referencing_Schema** : (nvarchar(max))
  **referencing_Object** : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_wo_columns_from_properties_tgt.adoc[]" as reference.additional_Reference_wo_columns_from_properties_tgt << V >> {
  - **referenced_AntoraComponent** : (nvarchar(128))
  - **referenced_AntoraModule** : (nvarchar(128))
  - **referenced_Schema** : (nvarchar(128))
  - **referenced_Object** : (nvarchar(128))
  - **referencing_AntoraComponent** : (nvarchar(128))
  - **referencing_AntoraModule** : (nvarchar(128))
  - **referencing_Schema** : (nvarchar(128))
  - **referencing_Object** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_queryplan.adoc[]" as reference.RepoObject_QueryPlan << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_reference.adoc[]" as reference.RepoObject_reference << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_reference_additional.adoc[]" as reference.RepoObject_reference_additional << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_reference_persistence.adoc[]" as reference.RepoObject_reference_persistence << V >> {
  **referenced_RepoObject_guid** : (uniqueidentifier)
  - **referencing_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_reference_persistence_target_as_source.adoc[]" as reference.RepoObject_reference_persistence_target_as_source << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_reference_persistence_target_as_source_explicit.adoc[]" as reference.RepoObject_reference_persistence_target_as_source_explicit << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_reference_sqlexpressiondependencies.adoc[]" as reference.RepoObject_reference_SqlExpressionDependencies << V >> {
  **referenced_RepoObject_guid** : (uniqueidentifier)
  **referencing_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_reference_t.adoc[]" as reference.RepoObject_reference_T << U >> {
  - **referenced_RepoObject_guid** : (uniqueidentifier)
  - **referencing_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_reference_union.adoc[]" as reference.RepoObject_reference_union << V >> {
  **referenced_RepoObject_guid** : (uniqueidentifier)
  **referencing_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_reference_virtual.adoc[]" as reference.RepoObject_reference_virtual << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_referencedlist.adoc[]" as reference.RepoObject_ReferencedList << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_referencedreferencing.adoc[]" as reference.RepoObject_ReferencedReferencing << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_referencetree.adoc[]" as reference.RepoObject_ReferenceTree << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  **Referenced_Depth** : (int)
  **Referencing_Depth** : (int)
  - **Referenced_guid** : (uniqueidentifier)
  - **Referencing_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_referencinglist.adoc[]" as reference.RepoObject_ReferencingList << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_reference.adoc[]" as reference.RepoObjectColumn_reference << V >> {
  **referenced_RepoObjectColumn_guid** : (uniqueidentifier)
  **referencing_RepoObjectColumn_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_reference_additional.adoc[]" as reference.RepoObjectColumn_reference_additional << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_reference_persistence.adoc[]" as reference.RepoObjectColumn_reference_Persistence << V >> {
  **referencing_id** : (int)
  **referencing_minor_id** : (int)
  **referenced_id** : (int)
  **referenced_minor_id** : (int)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_reference_sqlexpressiondependencies.adoc[]" as reference.RepoObjectColumn_reference_SqlExpressionDependencies << V >> {
  - **referencing_id** : (int)
  - **referencing_minor_id** : (int)
  **referenced_id** : (int)
  - **referenced_minor_id** : (int)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_reference_sqlmodules.adoc[]" as reference.RepoObjectColumn_reference_SqlModules << V >> {
  **referencing_id** : (int)
  **referencing_minor_id** : (int)
  **referenced_id** : (int)
  **referenced_minor_id** : (int)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_reference_t.adoc[]" as reference.RepoObjectColumn_reference_T << U >> {
  - **referenced_RepoObjectColumn_guid** : (uniqueidentifier)
  - **referencing_RepoObjectColumn_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_reference_union.adoc[]" as reference.RepoObjectColumn_reference_union << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_reference_virtual.adoc[]" as reference.RepoObjectColumn_reference_virtual << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_referencedlist.adoc[]" as reference.RepoObjectColumn_ReferencedList << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_referencedreferencing.adoc[]" as reference.RepoObjectColumn_ReferencedReferencing << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_referencinglist.adoc[]" as reference.RepoObjectColumn_ReferencingList << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumnsource_virtual.adoc[]" as reference.RepoObjectColumnSource_virtual << U >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  - **Source_RepoObjectColumn_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectsource_virtual.adoc[]" as reference.RepoObjectSource_virtual << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **Source_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.foreignkey_gross.adoc[]" as repo.ForeignKey_gross << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.foreignkey_indexes.adoc[]" as repo.ForeignKey_Indexes << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.foreignkey_indexes_union.adoc[]" as repo.ForeignKey_Indexes_union << V >> {
  **ForeignKey_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.foreignkey_indexes_union_t.adoc[]" as repo.ForeignKey_Indexes_union_T << U >> {
  **ForeignKey_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.foreignkey_indexpattern.adoc[]" as repo.ForeignKey_IndexPattern << V >> {
  - **constraint_object_id** : (int)
  **ForeignKey_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.foreignkey_ssas_indexes.adoc[]" as repo.ForeignKey_ssas_Indexes << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.foreignkey_ssas_indexpattern.adoc[]" as repo.ForeignKey_ssas_IndexPattern << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.foreignkey_virtual.adoc[]" as repo.ForeignKey_virtual << U >> {
  - **ForeignKey_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.foreignkey_virtual_indexes.adoc[]" as repo.ForeignKey_virtual_Indexes << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.index_columlist.adoc[]" as repo.Index_ColumList << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.index_columlist_t.adoc[]" as repo.Index_ColumList_T << U >> {
  - **index_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.index_gross.adoc[]" as repo.Index_gross << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.index_settings.adoc[]" as repo.Index_Settings << U >> {
  - **index_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.index_ssas.adoc[]" as repo.Index_ssas << V >> {
  - **databasename** : (nvarchar(128))
  **index_name** : (nvarchar(450))
  --
}

entity "puml-link:dhw:sqldb:repo.index_ssas_indexpatterncolumnguid.adoc[]" as repo.Index_ssas_IndexPatternColumnGuid << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.index_ssas_t.adoc[]" as repo.Index_ssas_T << U >> {
  - **databasename** : (nvarchar(128))
  - **index_name** : (nvarchar(450))
  --
}

entity "puml-link:dhw:sqldb:repo.index_union.adoc[]" as repo.Index_union << V >> {
  **index_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.index_unique_indexpatterncolumnguid.adoc[]" as repo.Index_unique_IndexPatternColumnGuid << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.index_virtual.adoc[]" as repo.Index_virtual << U >> {
  - **index_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.index_virtual_indexpatterncolumnguid.adoc[]" as repo.Index_virtual_IndexPatternColumnGuid << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.indexcolumn_ssas.adoc[]" as repo.IndexColumn_ssas << V >> {
  - **index_guid** : (uniqueidentifier)
  - **index_column_id** : (int)
  --
}

entity "puml-link:dhw:sqldb:repo.indexcolumn_ssas_gross.adoc[]" as repo.IndexColumn_ssas_gross << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.indexcolumn_ssas_t.adoc[]" as repo.IndexColumn_ssas_T << U >> {
  - **index_guid** : (uniqueidentifier)
  - **index_column_id** : (int)
  --
}

entity "puml-link:dhw:sqldb:repo.indexcolumn_union.adoc[]" as repo.IndexColumn_union << V >> {
  **index_guid** : (uniqueidentifier)
  - **index_column_id** : (int)
  --
}

entity "puml-link:dhw:sqldb:repo.indexcolumn_union_t.adoc[]" as repo.IndexColumn_union_T << U >> {
  - **index_guid** : (uniqueidentifier)
  - **index_column_id** : (int)
  --
}

entity "puml-link:dhw:sqldb:repo.indexcolumn_virtual.adoc[]" as repo.IndexColumn_virtual << U >> {
  - **index_guid** : (uniqueidentifier)
  - **index_column_id** : (int)
  --
}

entity "puml-link:dhw:sqldb:repo.indexcolumn_virtual_gross.adoc[]" as repo.IndexColumn_virtual_gross << V >> {
  - **index_column_id** : (int)
  --
}

entity "puml-link:dhw:sqldb:repo.measure.adoc[]" as repo.Measure << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.measure_union.adoc[]" as repo.Measure_union << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject.adoc[]" as repo.RepoObject << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_columnlist.adoc[]" as repo.RepoObject_ColumnList << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_external_src.adoc[]" as repo.RepoObject_external_src << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_external_tgt.adoc[]" as repo.RepoObject_external_tgt << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_gross.adoc[]" as repo.RepoObject_gross << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_gross_persistence.adoc[]" as repo.RepoObject_gross_persistence << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_persistence.adoc[]" as repo.RepoObject_persistence << U >> {
  - **target_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_related_fk_union.adoc[]" as repo.RepoObject_related_FK_union << V >> {
  **RepoObject_guid** : (uniqueidentifier)
  **included_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_sat2.adoc[]" as repo.RepoObject_sat2 << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_sat2_t.adoc[]" as repo.RepoObject_sat2_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_ssas_src.adoc[]" as repo.RepoObject_SSAS_src << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_ssas_tgt.adoc[]" as repo.RepoObject_SSAS_tgt << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn.adoc[]" as repo.RepoObjectColumn << U >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn_external_src.adoc[]" as repo.RepoObjectColumn_external_src << V >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn_external_tgt.adoc[]" as repo.RepoObjectColumn_external_tgt << V >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn_gross.adoc[]" as repo.RepoObjectColumn_gross << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn_gross2.adoc[]" as repo.RepoObjectColumn_gross2 << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn_ssas_src.adoc[]" as repo.RepoObjectColumn_SSAS_src << V >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn_ssas_tgt.adoc[]" as repo.RepoObjectColumn_SSAS_tgt << V >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.reposchema.adoc[]" as repo.RepoSchema << U >> {
  - **RepoSchema_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.reposchema_ssas_src.adoc[]" as repo.RepoSchema_ssas_src << V >> {
  - **RepoSchema_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:repo.reposchema_ssas_tgt.adoc[]" as repo.RepoSchema_ssas_tgt << V >> {
  - **RepoSchema_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.syscolumn_repoobjectcolumn_via_name.adoc[]" as repo.SysColumn_RepoObjectColumn_via_name << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.sysobject_repoobject_via_name.adoc[]" as repo.SysObject_RepoObject_via_name << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo_sys.extendedproperties.adoc[]" as repo_sys.ExtendedProperties << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo_sys.foreignkey.adoc[]" as repo_sys.ForeignKey << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo_sys.foreignkeycolumn.adoc[]" as repo_sys.ForeignKeyColumn << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo_sys.index_unique.adoc[]" as repo_sys.Index_unique << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo_sys.indexcolumn_unique.adoc[]" as repo_sys.IndexColumn_unique << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo_sys.parameters.adoc[]" as repo_sys.parameters << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo_sys.sql_expression_dependencies.adoc[]" as repo_sys.sql_expression_dependencies << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo_sys.syscolumn.adoc[]" as repo_sys.SysColumn << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo_sys.sysobject.adoc[]" as repo_sys.SysObject << V >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.ftv_sqlparse.adoc[]" as sqlparse.ftv_sqlparse << IF >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.ftv_sqlparse_children_pivot.adoc[]" as sqlparse.ftv_sqlparse_children_pivot << IF >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.ftv_sqlparse_with_some_children.adoc[]" as sqlparse.ftv_sqlparse_with_some_children << IF >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules.adoc[]" as sqlparse.RepoObject_SqlModules << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_10_statement.adoc[]" as sqlparse.RepoObject_SqlModules_10_statement << V >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_20_statement_children.adoc[]" as sqlparse.RepoObject_SqlModules_20_statement_children << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **json_key** : (nvarchar(4000))
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_21_statement_children_helper.adoc[]" as sqlparse.RepoObject_SqlModules_21_statement_children_helper << V >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_22_identifier_alias_as.adoc[]" as sqlparse.RepoObject_SqlModules_22_identifier_alias_AS << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **json_key** : (nvarchar(4000))
  **RowNumber** : (bigint)
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_24_identifierlist_children.adoc[]" as sqlparse.RepoObject_SqlModules_24_IdentifierList_children << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **json_key** : (nvarchar(4000))
  - **T2_json_key** : (nvarchar(4000))
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_25_identifierlist_children_identifiersplit.adoc[]" as sqlparse.RepoObject_SqlModules_25_IdentifierList_children_IdentifierSplit << V >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_26_identifierlist_children_identifiersplit_quotename.adoc[]" as sqlparse.RepoObject_SqlModules_26_IdentifierList_children_IdentifierSplit_QuoteName << V >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_29_1_object_is_union.adoc[]" as sqlparse.RepoObject_SqlModules_29_1_object_is_union << V >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_29_2_object_is_groupby.adoc[]" as sqlparse.RepoObject_SqlModules_29_2_object_is_GroupBy << V >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_31_object.adoc[]" as sqlparse.RepoObject_SqlModules_31_object << V >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_32_objectclass.adoc[]" as sqlparse.RepoObject_SqlModules_32_ObjectClass << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  **class** : (nvarchar(500))
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_33_objectnormalized.adoc[]" as sqlparse.RepoObject_SqlModules_33_ObjectNormalized << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  **normalized** : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_39_object.adoc[]" as sqlparse.RepoObject_SqlModules_39_object << V >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_41_from.adoc[]" as sqlparse.RepoObject_SqlModules_41_from << V >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_41_from_t.adoc[]" as sqlparse.RepoObject_SqlModules_41_from_T << U >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_42_from_identifier.adoc[]" as sqlparse.RepoObject_SqlModules_42_from_Identifier << V >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_43_from_identifier.adoc[]" as sqlparse.RepoObject_SqlModules_43_from_Identifier << V >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_44_from_identifier_quotename.adoc[]" as sqlparse.RepoObject_SqlModules_44_from_Identifier_QuoteName << V >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_51_identitfier.adoc[]" as sqlparse.RepoObject_SqlModules_51_Identitfier << V >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_52_identitfier_quotename.adoc[]" as sqlparse.RepoObject_SqlModules_52_Identitfier_QuoteName << V >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_61_selectidentifier_union.adoc[]" as sqlparse.RepoObject_SqlModules_61_SelectIdentifier_Union << V >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_61_selectidentifier_union_t.adoc[]" as sqlparse.RepoObject_SqlModules_61_SelectIdentifier_Union_T << U >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_71_reference_explicitetablealias.adoc[]" as sqlparse.RepoObject_SqlModules_71_reference_ExpliciteTableAlias << V >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_72_reference_notablealias.adoc[]" as sqlparse.RepoObject_SqlModules_72_reference_NoTableAlias << V >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_79_reference_union.adoc[]" as sqlparse.RepoObject_SqlModules_79_reference_union << V >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_repo_sys.adoc[]" as sqlparse.RepoObject_SqlModules_Repo_Sys << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.additional_reference_step1.adoc[]" as ssas.additional_Reference_step1 << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.indexcolumn_from_iskey.adoc[]" as ssas.IndexColumn_from_IsKey << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.indexcolumn_from_isunique.adoc[]" as ssas.IndexColumn_from_IsUnique << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.indexcolumn_from_relationship.adoc[]" as ssas.IndexColumn_from_Relationship << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.indexcolumn_union.adoc[]" as ssas.IndexColumn_union << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.measure_translation.adoc[]" as ssas.Measure_translation << V >> {
  - **Measure_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  **RepoObject_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.measure_translation_displayfolder_union.adoc[]" as ssas.Measure_translation_displayfolder_union << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.measure_translation_t.adoc[]" as ssas.Measure_translation_T << U >> {
  - **Measure_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  - **RepoObject_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json.adoc[]" as ssas.model_json << U >> {
  - **databasename** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_10.adoc[]" as ssas.model_json_10 << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_20.adoc[]" as ssas.model_json_20 << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_201_descriptions_multiline.adoc[]" as ssas.model_json_201_descriptions_multiline << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_2011_descriptions_stragg.adoc[]" as ssas.model_json_2011_descriptions_StrAgg << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31_tables.adoc[]" as ssas.model_json_31_tables << V >> {
  - **databasename** : (nvarchar(128))
  **tables_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31_tables_t.adoc[]" as ssas.model_json_31_tables_T << U >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_311_tables_columns.adoc[]" as ssas.model_json_311_tables_columns << V >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  **tables_columns_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_311_tables_columns_t.adoc[]" as ssas.model_json_311_tables_columns_T << U >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  - **tables_columns_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_3111_tables_columns_descriptions_multiline.adoc[]" as ssas.model_json_3111_tables_columns_descriptions_multiline << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31111_tables_columns_descriptions_stragg.adoc[]" as ssas.model_json_31111_tables_columns_descriptions_StrAgg << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_3112_tables_columns_expressions_multiline.adoc[]" as ssas.model_json_3112_tables_columns_expressions_multiline << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31121_tables_columns_expressions_stragg.adoc[]" as ssas.model_json_31121_tables_columns_expressions_StrAgg << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_312_tables_measures.adoc[]" as ssas.model_json_312_tables_measures << V >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  **tables_measures_name** : (nvarchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_312_tables_measures_t.adoc[]" as ssas.model_json_312_tables_measures_T << U >> {
  - **Measure_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_3121_tables_columns_descriptions_multiline.adoc[]" as ssas.model_json_3121_tables_columns_descriptions_multiline << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31211_tables_columns_descriptions_stragg.adoc[]" as ssas.model_json_31211_tables_columns_descriptions_StrAgg << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_3122_tables_measures_expressions_multiline.adoc[]" as ssas.model_json_3122_tables_measures_expressions_multiline << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31221_tables_measures_expressions_stragg.adoc[]" as ssas.model_json_31221_tables_measures_expressions_StrAgg << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_313_tables_partitions.adoc[]" as ssas.model_json_313_tables_partitions << V >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  **tables_partitions_name** : (nvarchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_3131_tables_partitions_source.adoc[]" as ssas.model_json_3131_tables_partitions_source << V >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  **tables_partitions_name** : (nvarchar(500))
  **tables_partitions_source_name** : (nvarchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31311_tables_partitions_source_posfrom.adoc[]" as ssas.model_json_31311_tables_partitions_source_PosFrom << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_313111_tables_partitions_source_stringfrom.adoc[]" as ssas.model_json_313111_tables_partitions_source_StringFrom << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_3131111_tables_partitions_source_posdot.adoc[]" as ssas.model_json_3131111_tables_partitions_source_PosDot << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31311111_tables_partitions_source_part123.adoc[]" as ssas.model_json_31311111_tables_partitions_source_Part123 << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_316_tables_descriptions_multiline.adoc[]" as ssas.model_json_316_tables_descriptions_multiline << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_3161_tables_descriptions_stragg.adoc[]" as ssas.model_json_3161_tables_descriptions_StrAgg << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_32_relationships.adoc[]" as ssas.model_json_32_relationships << V >> {
  - **databasename** : (nvarchar(128))
  **relationships_name** : (nvarchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_32_relationships_t.adoc[]" as ssas.model_json_32_relationships_T << U >> {
  - **ForeignKey_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_33_datasources.adoc[]" as ssas.model_json_33_dataSources << V >> {
  - **databasename** : (nvarchar(128))
  **dataSources_name** : (nvarchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_33_datasources_t.adoc[]" as ssas.model_json_33_dataSources_T << U >> {
  - **databasename** : (nvarchar(128))
  - **dataSources_name** : (nvarchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_34_cultures.adoc[]" as ssas.model_json_34_cultures << V >> {
  - **databasename** : (nvarchar(128))
  **cultures_name** : (nvarchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_341_cultures_translations.adoc[]" as ssas.model_json_341_cultures_translations << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_3411_cultures_translations_model.adoc[]" as ssas.model_json_3411_cultures_translations_model << V >> {
  - **databasename** : (nvarchar(128))
  **cultures_name** : (nvarchar(500))
  **cultures_translations_model_name** : (nvarchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_3411_cultures_translations_model_t.adoc[]" as ssas.model_json_3411_cultures_translations_model_T << U >> {
  - **databasename** : (nvarchar(128))
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_34111_cultures_translations_model_tables.adoc[]" as ssas.model_json_34111_cultures_translations_model_tables << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_341111_cultures_translations_model_tables_columns.adoc[]" as ssas.model_json_341111_cultures_translations_model_tables_columns << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_341113_cultures_translations_model_tables_measures.adoc[]" as ssas.model_json_341113_cultures_translations_model_tables_measures << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.repoobjectcolumn_translation.adoc[]" as ssas.RepoObjectColumn_translation << V >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:ssas.repoobjectcolumn_translation_displayfolder_union.adoc[]" as ssas.RepoObjectColumn_translation_displayfolder_union << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.repoobjectcolumn_translation_t.adoc[]" as ssas.RepoObjectColumn_translation_T << U >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:ssis.antoramodule_tgt_filter.adoc[]" as ssis.AntoraModule_tgt_filter << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.package.adoc[]" as ssis.Package << U >> {
  - **AntoraModule** : (varchar(50))
  - **PackageName** : (varchar(200))
  --
}

entity "puml-link:dhw:sqldb:ssis.package_src.adoc[]" as ssis.Package_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  --
}

entity "puml-link:dhw:sqldb:ssis.package_tgt.adoc[]" as ssis.Package_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  - **PackageName** : (varchar(200))
  --
}

entity "puml-link:dhw:sqldb:ssis.packageconnection.adoc[]" as ssis.PackageConnection << U >> {
  - **AntoraModule** : (varchar(50))
  - **PackageName** : (varchar(200))
  - **ConnectionManagerID** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:ssis.packageconnection_src.adoc[]" as ssis.PackageConnection_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **ConnectionManagerID** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:ssis.packageconnection_tgt.adoc[]" as ssis.PackageConnection_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  - **PackageName** : (varchar(200))
  - **ConnectionManagerID** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:ssis.packageflow.adoc[]" as ssis.PackageFlow << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.packageflow_src.adoc[]" as ssis.PackageFlow_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **TaskFrom** : (varchar(2000))
  **Taskto** : (varchar(2000))
  --
}

entity "puml-link:dhw:sqldb:ssis.packageflow_tgt.adoc[]" as ssis.PackageFlow_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  - **PackageName** : (varchar(200))
  - **TaskFrom** : (varchar(2000))
  - **Taskto** : (varchar(2000))
  --
}

entity "puml-link:dhw:sqldb:ssis.packageparameter.adoc[]" as ssis.PackageParameter << U >> {
  - **AntoraModule** : (varchar(50))
  - **PackageName** : (varchar(200))
  - **ParameterName** : (varchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssis.packageparameter_src.adoc[]" as ssis.PackageParameter_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **ParameterName** : (varchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssis.packageparameter_tgt.adoc[]" as ssis.PackageParameter_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  - **PackageName** : (varchar(200))
  - **ParameterName** : (varchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask.adoc[]" as ssis.PackageTask << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component.adoc[]" as ssis.PackageTask_Dft_Component << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_input.adoc[]" as ssis.PackageTask_Dft_Component_input << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_input_externalmetadatacolumn.adoc[]" as ssis.PackageTask_Dft_Component_input_externalMetadataColumn << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_input_externalmetadatacolumn_src.adoc[]" as ssis.PackageTask_Dft_Component_input_externalMetadataColumn_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Column_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_input_externalmetadatacolumn_tgt.adoc[]" as ssis.PackageTask_Dft_Component_input_externalMetadataColumn_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Column_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_input_inputcolumn.adoc[]" as ssis.PackageTask_Dft_Component_input_inputColumn << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_input_inputcolumn_src.adoc[]" as ssis.PackageTask_Dft_Component_input_inputColumn_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Column_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_input_inputcolumn_tgt.adoc[]" as ssis.PackageTask_Dft_Component_input_inputColumn_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Column_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_input_src.adoc[]" as ssis.PackageTask_Dft_Component_input_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **input_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_input_tgt.adoc[]" as ssis.PackageTask_Dft_Component_input_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **input_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_output.adoc[]" as ssis.PackageTask_Dft_Component_output << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_output_outputcolumn.adoc[]" as ssis.PackageTask_Dft_Component_output_outputcolumn << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_output_outputcolumn_src.adoc[]" as ssis.PackageTask_Dft_Component_output_outputcolumn_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Column_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_output_outputcolumn_tgt.adoc[]" as ssis.PackageTask_Dft_Component_output_outputColumn_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Column_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_output_src.adoc[]" as ssis.PackageTask_Dft_Component_output_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **output_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_output_tgt.adoc[]" as ssis.PackageTask_Dft_Component_output_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **output_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_src.adoc[]" as ssis.PackageTask_Dft_Component_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Component_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_tgt.adoc[]" as ssis.PackageTask_Dft_Component_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Component_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_levellaglead.adoc[]" as ssis.PackageTask_LevelLagLead << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_sql_parameter.adoc[]" as ssis.PackageTask_Sql_Parameter << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_sql_parameter_src.adoc[]" as ssis.PackageTask_Sql_Parameter_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **TaskPath** : (varchar(8000))
  **ParameterBindingSequence** : (varchar(1000))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_sql_parameter_tgt.adoc[]" as ssis.PackageTask_Sql_Parameter_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  - **PackageName** : (varchar(200))
  - **TaskPath** : (varchar(8000))
  - **ParameterBindingSequence** : (varchar(1000))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_src.adoc[]" as ssis.PackageTask_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **TaskPath** : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_tgt.adoc[]" as ssis.PackageTask_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  - **PackageName** : (varchar(200))
  - **TaskPath** : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagevariable.adoc[]" as ssis.PackageVariable << U >> {
  - **AntoraModule** : (varchar(50))
  - **PackageName** : (varchar(200))
  - **VariableName** : (varchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagevariable_src.adoc[]" as ssis.PackageVariable_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **VariableName** : (varchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagevariable_tgt.adoc[]" as ssis.PackageVariable_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  - **PackageName** : (varchar(200))
  - **VariableName** : (varchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssis.project.adoc[]" as ssis.Project << U >> {
  - **AntoraModule** : (varchar(50))
  --
}

entity "puml-link:dhw:sqldb:ssis.projectconnection.adoc[]" as ssis.ProjectConnection << U >> {
  - **AntoraModule** : (varchar(50))
  - **ConnectionManagerID** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:ssis.projectconnection_src.adoc[]" as ssis.ProjectConnection_src << V >> {
  - **AntoraModule** : (varchar(50))
  **ConnectionManagerID** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:ssis.projectconnection_tgt.adoc[]" as ssis.ProjectConnection_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  - **ConnectionManagerID** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.pkgstats.adoc[]" as ssis_t.pkgStats << U >> {
  - **RowID** : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.projectconnection.adoc[]" as ssis_t.ProjectConnection << U >> {
  - **RowID** : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tblconnection.adoc[]" as ssis_t.TblConnection << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tblcontrolflow.adoc[]" as ssis_t.TblControlFlow << U >> {
  - **ControlFlowDetailsRowID** : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tblparameter.adoc[]" as ssis_t.TblParameter << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tblprecedenceconstraint.adoc[]" as ssis_t.TblPrecedenceConstraint << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tblprojectconnection.adoc[]" as ssis_t.TblProjectConnection << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_dft_component.adoc[]" as ssis_t.TblTask_Dft_Component << U >> {
  - **DftComponentId** : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_dft_component_inputs_externalmetadatacolumn_src.adoc[]" as ssis_t.TblTask_Dft_Component_inputs_externalMetadataColumn_src << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_dft_component_inputs_inputcolumn_src.adoc[]" as ssis_t.TblTask_Dft_Component_inputs_inputColumn_src << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_dft_component_inputs_src.adoc[]" as ssis_t.TblTask_Dft_Component_inputs_src << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_dft_component_outputs_outputcolumn_src.adoc[]" as ssis_t.TblTask_Dft_Component_outputs_outputColumn_src << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_dft_component_outputs_src.adoc[]" as ssis_t.TblTask_Dft_Component_outputs_src << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_executepackage.adoc[]" as ssis_t.TblTask_ExecutePackage << U >> {
  - **ControlFlowDetailsRowID** : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_script.adoc[]" as ssis_t.TblTask_Script << U >> {
  - **ControlFlowDetailsRowID** : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_sql.adoc[]" as ssis_t.TblTask_Sql << U >> {
  - **ControlFlowDetailsRowID** : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_sql_parameter.adoc[]" as ssis_t.TblTask_Sql_Parameter << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tblvariable.adoc[]" as ssis_t.TblVariable << U >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.columns.adoc[]" as sys_dwh.columns << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.computed_columns.adoc[]" as sys_dwh.computed_columns << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.default_constraints.adoc[]" as sys_dwh.default_constraints << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.extended_properties.adoc[]" as sys_dwh.extended_properties << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.foreign_key_columns.adoc[]" as sys_dwh.foreign_key_columns << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.foreign_keys.adoc[]" as sys_dwh.foreign_keys << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.identity_columns.adoc[]" as sys_dwh.identity_columns << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.index_columns.adoc[]" as sys_dwh.index_columns << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.indexes.adoc[]" as sys_dwh.indexes << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.objects.adoc[]" as sys_dwh.objects << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.parameters.adoc[]" as sys_dwh.parameters << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.schemas.adoc[]" as sys_dwh.schemas << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.sql_expression_dependencies.adoc[]" as sys_dwh.sql_expression_dependencies << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.sql_modules.adoc[]" as sys_dwh.sql_modules << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.tables.adoc[]" as sys_dwh.tables << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.types.adoc[]" as sys_dwh.types << SN >> {
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.generatorusp.adoc[]" as uspgenerator.GeneratorUsp << U >> {
  - **id** : (int)
  --
}

config.fs_get_parameter_value <.. docs.fs_AntoraModuleFolder
config.fs_get_parameter_value <.. docs.ftv_RepoObject_AntoraXref
config.fs_get_parameter_value <.. docs.usp_AntoraExport
config.fs_get_parameter_value <.. docs.usp_AntoraExport_SsisNavigation
config.fs_get_parameter_value <.. docs.usp_AntoraExport_SsisPage
config.fs_get_parameter_value <.. docs.usp_AntoraExport_SsisPageTemplate
config.fs_get_parameter_value <.. docs.usp_AntoraExport_SsisPartialsContent
config.ftv_dwh_database <.. repo_sys.ExtendedProperties
config.ftv_dwh_database <.. repo_sys.sql_expression_dependencies
config.ftv_dwh_database <.. repo_sys.SysColumn
config.ftv_get_parameter_value <.. docs.fs_PumlHeaderLeftToRight
config.ftv_get_parameter_value <.. docs.fs_PumlHeaderTopToBottom
config.ftv_get_parameter_value <.. docs.RepoObject_Plantuml
config.ftv_get_parameter_value <.. docs.ssis_PumlDftTask
config.ftv_get_parameter_value <.. docs.ssis_PumlPackage
config.ftv_get_parameter_value <.. reference.additional_Reference_is_external
config.ftv_get_parameter_value <.. repo.RepoObject_ColumnList
config.ftv_get_parameter_value <.. repo.RepoObject_external_src
config.ftv_get_parameter_value <.. repo.RepoObject_gross
config.ftv_get_parameter_value <.. ssas.additional_Reference_step1
config.Parameter <.. config.fs_get_parameter_value
config.Parameter <.. config.ftv_dwh_database
config.Parameter <.. config.ftv_get_parameter_value
config.Parameter <.. docs.usp_AntoraExport_ObjectPageTemplate
config.Parameter <.. docs.usp_AntoraExport_SsisPageTemplate
config.Parameter <.. property.PropertyName_RepoObject
configT.join_type <.. sqlparse.RepoObject_SqlModules_41_from
configT.Parameter_default <.. config.Parameter
configT.spt_values <.. configT.type
configT.type <.. docs.AntoraNavListPage_by_type
configT.type <.. reference.RepoObject_ReferencedReferencing
configT.type <.. repo.RepoObject_gross
configT.type <.. repo.RepoObject_gross_persistence
docs.AntoraNavListPage_by_type <.. docs.usp_AntoraExport_ObjectNavigation
docs.AntoraNavListRepoObject_by_schema <.. docs.usp_AntoraExport_ObjectNavigation
docs.AntoraNavListRepoObject_by_schema_type <.. docs.usp_AntoraExport_ObjectNavigation
docs.AntoraNavListRepoObject_by_type <.. docs.usp_AntoraExport_ObjectNavigation
docs.command <.. docs.usp_AntoraExport
docs.command <.. docs.usp_AntoraExport_ObjectNavigation
docs.command <.. docs.usp_AntoraExport_ObjectPage
docs.command <.. docs.usp_AntoraExport_ObjectPageTemplate
docs.command <.. docs.usp_AntoraExport_ObjectPartialsContent
docs.command <.. docs.usp_AntoraExport_ObjectRefCyclic
docs.command <.. docs.usp_AntoraExport_Page_IndexSemanticGroup
docs.command <.. docs.usp_AntoraExport_SsisNavigation
docs.command <.. docs.usp_AntoraExport_SsisPage
docs.command <.. docs.usp_AntoraExport_SsisPageTemplate
docs.command <.. docs.usp_AntoraExport_SsisPartialsContent
docs.Culture <.. docs.RepoObject_OutputFilter
docs.culture <.. docs.usp_AntoraExport
docs.culture <.. docs.usp_AntoraExport_ObjectNavigation
docs.culture <.. docs.usp_AntoraExport_ObjectPageTemplate
docs.culture <.. docs.usp_AntoraExport_ObjectRefCyclic
docs.Culture <.. docs.usp_AntoraExport_Page_IndexSemanticGroup
docs.Culture <.. ssas.Measure_translation
docs.Culture <.. ssas.RepoObjectColumn_translation
docs.fs_AntoraModuleFolder <.. docs.usp_AntoraExport
docs.fs_AntoraModuleFolder <.. docs.usp_AntoraExport_ObjectNavigation
docs.fs_AntoraModuleFolder <.. docs.usp_AntoraExport_ObjectPage
docs.fs_AntoraModuleFolder <.. docs.usp_AntoraExport_ObjectPageTemplate
docs.fs_AntoraModuleFolder <.. docs.usp_AntoraExport_ObjectPartialsContent
docs.fs_AntoraModuleFolder <.. docs.usp_AntoraExport_ObjectRefCyclic
docs.fs_AntoraModuleFolder <.. docs.usp_AntoraExport_Page_IndexSemanticGroup
docs.fs_cleanStringForAnchorId <.. docs.RepoObject_ColumnList
docs.fs_cleanStringForAnchorId <.. docs.RepoObject_IndexList
docs.fs_cleanStringForAnchorId <.. docs.RepoObject_MeasureDescriptionList
docs.fs_cleanStringForAnchorId <.. docs.RepoObject_MeasureList
docs.fs_cleanStringForAnchorId <.. docs.ssis_DftTaskComponentInputColumnList
docs.fs_cleanStringForAnchorId <.. docs.ssis_DftTaskComponentInputList
docs.fs_cleanStringForAnchorId <.. docs.ssis_DftTaskComponentList
docs.fs_cleanStringForAnchorId <.. docs.ssis_DftTaskComponentOutputColumnList
docs.fs_cleanStringForAnchorId <.. docs.ssis_DftTaskComponentOutputList
docs.fs_cleanStringForAnchorId <.. docs.ssis_PackageConnectionList
docs.fs_cleanStringForAnchorId <.. docs.ssis_ParameterList
docs.fs_cleanStringForAnchorId <.. docs.ssis_ProjectConnectionList
docs.fs_cleanStringForAnchorId <.. docs.ssis_PumlPartialControlFlows
docs.fs_cleanStringForAnchorId <.. docs.ssis_PumlPartialDataFlow
docs.fs_cleanStringForAnchorId <.. docs.ssis_PumlPartialDftComponent
docs.fs_cleanStringForAnchorId <.. docs.ssis_PumlPartialTaskComponent
docs.fs_cleanStringForAnchorId <.. docs.ssis_TaskList
docs.fs_cleanStringForAnchorId <.. docs.ssis_VariableList
docs.fs_cleanStringForAnchorId <.. reference.RepoObjectColumn_ReferencedReferencing
docs.fs_cleanStringForAnchorId <.. repo.ForeignKey_gross
docs.fs_cleanStringForFilename <.. docs.AntoraNavListPage_by_type
docs.fs_cleanStringForFilename <.. docs.AntoraNavListRepoObject_by_schema
docs.fs_cleanStringForFilename <.. docs.AntoraNavListRepoObject_by_schema_type
docs.fs_cleanStringForFilename <.. docs.AntoraNavListRepoObject_by_type
docs.fs_cleanStringForFilename <.. docs.ftv_RepoObject_AntoraXref
docs.fs_cleanStringForFilename <.. docs.RepoObject_OutputFilter
docs.fs_cleanStringForFilename <.. docs.RepoObject_OutputFilter_T_gross
docs.fs_cleanStringForFilename <.. docs.ssis_navlist_package
docs.fs_cleanStringForFilename <.. docs.ssis_PackageConnectionList
docs.fs_cleanStringForFilename <.. docs.ssis_PumlPartialDftComponent
docs.fs_cleanStringForFilename <.. docs.ssis_PumlPartialTaskComponent
docs.fs_cleanStringForFilename <.. docs.ssis_TaskList
docs.fs_cleanStringForFilename <.. docs.usp_AntoraExport_ObjectNavigation
docs.fs_cleanStringForFilename <.. docs.usp_AntoraExport_ObjectPage
docs.fs_cleanStringForFilename <.. docs.usp_AntoraExport_ObjectPartialsContent
docs.fs_cleanStringForFilename <.. docs.usp_AntoraExport_SsisPage
docs.fs_cleanStringForFilename <.. docs.usp_AntoraExport_SsisPartialsContent
docs.fs_cleanStringForFilename <.. reference.RepoObject_ReferencedReferencing
docs.fs_cleanStringForFilename <.. reference.RepoObjectColumn_ReferencedReferencing
docs.fs_cleanStringForFilename <.. repo.ForeignKey_gross
docs.fs_cleanStringForFilename <.. repo.RepoObject_gross
docs.fs_cleanStringForFilename <.. repo.RepoObject_gross_persistence
docs.fs_cleanStringForHeader <.. docs.RepoObject_ColumnList
docs.fs_cleanStringForHeader <.. docs.RepoObject_IndexList
docs.fs_cleanStringForHeader <.. docs.RepoObject_MeasureDescriptionList
docs.fs_cleanStringForHeader <.. docs.RepoObject_MeasureList
docs.fs_cleanStringForHeader <.. docs.ssis_DftTaskComponentInputColumnList
docs.fs_cleanStringForHeader <.. docs.ssis_DftTaskComponentInputList
docs.fs_cleanStringForHeader <.. docs.ssis_DftTaskComponentList
docs.fs_cleanStringForHeader <.. docs.ssis_DftTaskComponentOutputColumnList
docs.fs_cleanStringForHeader <.. docs.ssis_DftTaskComponentOutputList
docs.fs_cleanStringForHeader <.. docs.ssis_PackageConnectionList
docs.fs_cleanStringForHeader <.. docs.ssis_ParameterList
docs.fs_cleanStringForHeader <.. docs.ssis_ProjectConnectionList
docs.fs_cleanStringForHeader <.. docs.ssis_TaskList
docs.fs_cleanStringForHeader <.. docs.ssis_VariableList
docs.fs_cleanStringForPuml <.. docs.RepoObject_ColumnList
docs.fs_cleanStringForPuml <.. docs.RepoObject_IndexList
docs.fs_cleanStringForPuml <.. docs.RepoObject_MeasureList
docs.fs_cleanStringForPuml <.. docs.RepoObject_OutputFilter
docs.fs_cleanStringForPuml <.. docs.RepoObject_Plantuml_ColRefList_1_1
docs.fs_cleanStringForPuml <.. docs.RepoObject_PlantUml_FkRefList
docs.fs_PumlHeaderLeftToRight <.. docs.RepoObject_Plantuml
docs.fs_PumlHeaderTopToBottom <.. docs.RepoObject_Adoc
docs.fs_PumlHeaderTopToBottom <.. docs.RepoObject_Plantuml
docs.ftv_RepoObject_AntoraXref <.. docs.RepoObject_AntoraXrefCulturesList
docs.ftv_RepoObject_Reference_PlantUml_EntityRefList <.. docs.RepoObject_Plantuml
docs.Measure_MeasurePropertyList <.. docs.RepoObject_MeasureList
docs.RepoObject_Adoc <.. docs.RepoObject_Adoc_T
docs.RepoObject_Adoc <.. docs.usp_PERSIST_RepoObject_Adoc_T
docs.REpoObject_Adoc_T <.. docs.usp_PERSIST_RepoObject_Adoc_T
docs.RepoObject_AntoraXrefCulturesList <.. docs.RepoObject_Adoc
docs.RepoObject_ColumnList <.. docs.RepoObject_ColumnList_T
docs.RepoObject_ColumnList <.. docs.usp_PERSIST_RepoObject_ColumnList_T
docs.RepoObject_ColumnList_T <.. docs.RepoObject_Adoc
docs.RepoObject_ColumnList_T <.. docs.RepoObject_Plantuml_Entity
docs.RepoObject_ColumnList_T <.. docs.usp_PERSIST_RepoObject_ColumnList_T
docs.RepoObject_IndexList <.. docs.RepoObject_IndexList_T
docs.RepoObject_IndexList <.. docs.usp_PERSIST_RepoObject_IndexList_T
docs.RepoObject_IndexList_T <.. docs.RepoObject_Adoc
docs.RepoObject_IndexList_T <.. docs.RepoObject_Plantuml_Entity
docs.RepoObject_IndexList_T <.. docs.usp_PERSIST_RepoObject_IndexList_T
docs.RepoObject_MeasureDescriptionList <.. docs.RepoObject_Adoc
docs.RepoObject_MeasureList <.. docs.RepoObject_Adoc
docs.RepoObject_MeasureList <.. docs.RepoObject_Plantuml_Entity
docs.RepoObject_OutputFilter <.. docs.RepoObject_OutputFilter_T
docs.RepoObject_OutputFilter <.. docs.usp_PERSIST_RepoObject_OutputFilter_T
docs.RepoObject_OutputFilter_T <.. docs.AntoraNavListPage_by_type
docs.RepoObject_OutputFilter_T <.. docs.AntoraNavListRepoObject_by_schema
docs.RepoObject_OutputFilter_T <.. docs.AntoraNavListRepoObject_by_schema_type
docs.RepoObject_OutputFilter_T <.. docs.AntoraNavListRepoObject_by_type
docs.RepoObject_OutputFilter_T <.. docs.RepoObject_AntoraXrefCulturesList
docs.RepoObject_OutputFilter_T <.. docs.RepoObject_ColumnList
docs.RepoObject_OutputFilter_T <.. docs.RepoObject_IndexList
docs.RepoObject_OutputFilter_T <.. docs.RepoObject_OutputFilter_T_gross
docs.RepoObject_OutputFilter_T <.. docs.RepoObject_Plantuml
docs.RepoObject_OutputFilter_T <.. docs.RepoObject_Plantuml_ColRefList_1_1
docs.RepoObject_OutputFilter_T <.. docs.RepoObject_Plantuml_Entity
docs.RepoObject_OutputFilter_T <.. docs.usp_AntoraExport_ObjectPage
docs.RepoObject_OutputFilter_T <.. docs.usp_AntoraExport_ObjectPartialsContent
docs.RepoObject_OutputFilter_T <.. docs.usp_PERSIST_RepoObject_OutputFilter_T
docs.RepoObject_OutputFilter_T_gross <.. docs.RepoObject_Adoc
docs.RepoObject_OutputFilter_T_gross <.. docs.RepoObject_MeasureDescriptionList
docs.RepoObject_OutputFilter_T_gross <.. docs.RepoObject_MeasureList
docs.RepoObject_ParameterList <.. docs.RepoObject_Adoc
docs.RepoObject_Plantuml <.. docs.RepoObject_Plantuml_T
docs.RepoObject_Plantuml <.. docs.usp_PERSIST_RepoObject_Plantuml_T
docs.RepoObject_Plantuml_ColRefList_1_1 <.. docs.RepoObject_Plantuml
docs.RepoObject_Plantuml_Entity <.. docs.RepoObject_Plantuml_Entity_T
docs.RepoObject_Plantuml_Entity <.. docs.usp_PERSIST_RepoObject_Plantuml_Entity_T
docs.RepoObject_Plantuml_Entity_T <.. docs.ftv_RepoObject_Reference_PlantUml_EntityRefList
docs.RepoObject_Plantuml_Entity_T <.. docs.RepoObject_Adoc
docs.RepoObject_Plantuml_Entity_T <.. docs.RepoObject_PlantUml_PumlEntityFkList
docs.RepoObject_Plantuml_Entity_T <.. docs.usp_PERSIST_RepoObject_Plantuml_Entity_T
docs.RepoObject_PlantUml_FkRefList <.. docs.RepoObject_Plantuml
docs.RepoObject_Plantuml_ObjectRefList_0_30 <.. docs.RepoObject_Plantuml
docs.RepoObject_Plantuml_ObjectRefList_1_1 <.. docs.RepoObject_Plantuml
docs.RepoObject_Plantuml_ObjectRefList_30_0 <.. docs.RepoObject_Plantuml
docs.RepoObject_PlantUml_PumlEntityFkList <.. docs.RepoObject_Plantuml
docs.RepoObject_Plantuml_T <.. docs.RepoObject_Adoc
docs.RepoObject_Plantuml_T <.. docs.usp_PERSIST_RepoObject_Plantuml_T
docs.ssis_Adoc <.. docs.ssis_Adoc_T
docs.ssis_Adoc <.. docs.usp_PERSIST_ssis_Adoc_T
docs.ssis_Adoc_T <.. docs.usp_AntoraExport_SsisPartialsContent
docs.ssis_Adoc_T <.. docs.usp_PERSIST_ssis_Adoc_T
docs.ssis_DftTaskComponentInputColumnList <.. docs.ssis_DftTaskComponentInputList
docs.ssis_DftTaskComponentInputList <.. docs.ssis_DftTaskComponentList
docs.ssis_DftTaskComponentList <.. docs.ssis_TaskList
docs.ssis_DftTaskComponentOutputColumnList <.. docs.ssis_DftTaskComponentOutputList
docs.ssis_DftTaskComponentOutputList <.. docs.ssis_DftTaskComponentList
docs.ssis_GeneralList <.. docs.ssis_Adoc
docs.ssis_navlist_package <.. docs.usp_AntoraExport_SsisNavigation
docs.ssis_PackageConnectionList <.. docs.ssis_Adoc
docs.ssis_ParameterList <.. docs.ssis_Adoc
docs.ssis_ProjectConnectionList <.. docs.ssis_Adoc
docs.ssis_PumlDftTask <.. docs.ssis_TaskList
docs.ssis_PumlPackage <.. docs.ssis_Adoc
docs.ssis_PumlPartialControlFlows <.. docs.ssis_PumlPackage
docs.ssis_PumlPartialDataFlow <.. docs.ssis_PumlDftTask
docs.ssis_PumlPartialDftComponent <.. docs.ssis_DftTaskComponentList
docs.ssis_PumlPartialDftComponent <.. docs.ssis_PumlDftTask
docs.ssis_PumlPartialTaskComponent <.. docs.ssis_PumlPackage
docs.ssis_SqlTaskParameterInnerTable <.. docs.ssis_TaskList
docs.ssis_TaskList <.. docs.ssis_Adoc
docs.ssis_VariableList <.. docs.ssis_Adoc
docs.usp_AntoraExport_ObjectNavigation <.. docs.usp_AntoraExport
docs.usp_AntoraExport_ObjectPage <.. docs.usp_AntoraExport
docs.usp_AntoraExport_ObjectPageTemplate <.. docs.usp_AntoraExport
docs.usp_AntoraExport_ObjectPartialsContent <.. docs.usp_AntoraExport
docs.usp_AntoraExport_ObjectPuml <.. docs.usp_AntoraExport
docs.usp_AntoraExport_ObjectRefCyclic <.. docs.usp_AntoraExport
docs.usp_AntoraExport_Page_IndexSemanticGroup <.. docs.usp_AntoraExport
docs.usp_AntoraExport_SsisNavigation <.. docs.usp_AntoraExport
docs.usp_AntoraExport_SsisPage <.. docs.usp_AntoraExport
docs.usp_AntoraExport_SsisPageTemplate <.. docs.usp_AntoraExport
docs.usp_AntoraExport_SsisPartialsContent <.. docs.usp_AntoraExport
docs.usp_AntoraExport_SsisPuml <.. docs.usp_AntoraExport
docs.usp_PERSIST_RepoObject_Adoc_T <.. docs.usp_AntoraExport_ObjectPartialsContent
docs.usp_PERSIST_RepoObject_ColumnList_T <.. docs.usp_AntoraExport_ObjectPartialsContent
docs.usp_PERSIST_RepoObject_IndexList_T <.. docs.usp_AntoraExport_ObjectPartialsContent
docs.usp_PERSIST_RepoObject_OutputFilter_T <.. docs.usp_AntoraExport
docs.usp_PERSIST_RepoObject_Plantuml_Entity_T <.. docs.usp_AntoraExport_ObjectPuml
docs.usp_PERSIST_RepoObject_Plantuml_T <.. docs.usp_AntoraExport_ObjectPuml
docs.usp_PERSIST_ssis_Adoc_T <.. docs.usp_AntoraExport_SsisPartialsContent
logs.ExecutionLog <.. logs.usp_ExecutionLog_insert
logs.usp_ExecutionLog_insert <.. docs.usp_AntoraExport
logs.usp_ExecutionLog_insert <.. docs.usp_AntoraExport_ObjectNavigation
logs.usp_ExecutionLog_insert <.. docs.usp_AntoraExport_ObjectPage
logs.usp_ExecutionLog_insert <.. docs.usp_AntoraExport_ObjectPageTemplate
logs.usp_ExecutionLog_insert <.. docs.usp_AntoraExport_ObjectPartialsContent
logs.usp_ExecutionLog_insert <.. docs.usp_AntoraExport_ObjectPuml
logs.usp_ExecutionLog_insert <.. docs.usp_AntoraExport_ObjectRefCyclic
logs.usp_ExecutionLog_insert <.. docs.usp_AntoraExport_Page_IndexSemanticGroup
logs.usp_ExecutionLog_insert <.. docs.usp_AntoraExport_SsisNavigation
logs.usp_ExecutionLog_insert <.. docs.usp_AntoraExport_SsisPage
logs.usp_ExecutionLog_insert <.. docs.usp_AntoraExport_SsisPageTemplate
logs.usp_ExecutionLog_insert <.. docs.usp_AntoraExport_SsisPartialsContent
logs.usp_ExecutionLog_insert <.. docs.usp_AntoraExport_SsisPuml
logs.usp_ExecutionLog_insert <.. docs.usp_PERSIST_RepoObject_Adoc_T
logs.usp_ExecutionLog_insert <.. docs.usp_PERSIST_RepoObject_ColumnList_T
logs.usp_ExecutionLog_insert <.. docs.usp_PERSIST_RepoObject_IndexList_T
logs.usp_ExecutionLog_insert <.. docs.usp_PERSIST_RepoObject_OutputFilter_T
logs.usp_ExecutionLog_insert <.. docs.usp_PERSIST_RepoObject_Plantuml_Entity_T
logs.usp_ExecutionLog_insert <.. docs.usp_PERSIST_RepoObject_Plantuml_T
logs.usp_ExecutionLog_insert <.. docs.usp_PERSIST_ssis_Adoc_T
property.external_RepoObjectColumnProperty <.. property.RepoObjectColumnProperty_external_src
property.external_RepoObjectProperty <.. property.RepoObjectProperty_external_src
property.fs_get_RepoObjectColumnProperty_nvarchar <.. repo.RepoObjectColumn_gross
property.fs_get_RepoObjectProperty_nvarchar <.. repo.RepoObject_gross
property.MeasureProperty <.. docs.Measure_MeasurePropertyList
property.MeasureProperty <.. property.PropertyName_Measure
property.PropertyName_Measure <.. property.PropertyName_Measure_T
property.PropertyName_Measure_T <.. docs.Measure_MeasurePropertyList
property.PropertyName_RepoObject <.. property.PropertyName_RepoObject_T
property.PropertyName_RepoObject <.. property.RepoObjectProperty_cross
property.PropertyName_RepoObject_T <.. property.RepoObjectColumnProperty_external_tgt
property.PropertyName_RepoObject_T <.. property.RepoObjectProperty_external_tgt
property.RepoObjectColumnProperty <.. property.fs_get_RepoObjectColumnProperty_nvarchar
property.RepoObjectColumnProperty_external_src <.. property.RepoObjectColumnProperty_external_tgt
property.RepoObjectColumnProperty_external_tgt <.. property.RepoObjectColumnProperty
property.RepoObjectProperty <.. docs.RepoObject_Adoc
property.RepoObjectProperty <.. property.fs_get_RepoObjectProperty_nvarchar
property.RepoObjectProperty <.. property.PropertyName_RepoObject
property.RepoObjectProperty <.. property.RepoObjectProperty_SelectedPropertyName_split
property.RepoObjectProperty_cross <.. docs.RepoObject_Adoc
property.RepoObjectProperty_external_src <.. property.RepoObjectProperty_external_tgt
property.RepoObjectProperty_external_tgt <.. property.RepoObjectProperty
property.RepoObjectProperty_SelectedPropertyName_split <.. reference.additional_Reference_from_properties_src
property.RepoObjectProperty_SelectedPropertyName_split <.. reference.additional_Reference_wo_columns_from_properties_src
reference.additional_Reference <.. reference.additional_Reference_guid
reference.additional_Reference <.. reference.additional_Reference_is_external
reference.additional_Reference_database <.. reference.additional_Reference_database_T
reference.additional_Reference_database_T <.. repo.RepoObject_gross
reference.additional_Reference_from_properties_src <.. reference.additional_Reference_from_properties_tgt
reference.additional_Reference_from_properties_tgt <.. reference.additional_Reference
reference.additional_Reference_from_ssas_src <.. reference.additional_Reference_from_ssas_tgt
reference.additional_Reference_from_ssas_tgt <.. reference.additional_Reference
reference.additional_Reference_guid <.. reference.RepoObject_reference_additional
reference.additional_Reference_guid <.. reference.RepoObjectColumn_reference_additional
reference.additional_Reference_is_external <.. reference.additional_Reference_database
reference.additional_Reference_is_external <.. reference.additional_Reference_Object
reference.additional_Reference_is_external <.. reference.additional_Reference_ObjectColumn
reference.additional_Reference_Object <.. reference.additional_Reference_Object_T
reference.additional_Reference_Object_T <.. repo.RepoObject_external_src
reference.additional_Reference_Object_T <.. repo.RepoObjectColumn_external_src
reference.additional_Reference_ObjectColumn <.. reference.additional_Reference_ObjectColumn_T
reference.additional_Reference_ObjectColumn_T <.. repo.RepoObjectColumn_external_src
reference.additional_Reference_wo_columns_from_properties_src <.. reference.additional_Reference_wo_columns_from_properties_tgt
reference.additional_Reference_wo_columns_from_properties_tgt <.. reference.additional_Reference
reference.RepoObject_QueryPlan <.. repo.RepoObject_gross
reference.RepoObject_reference <.. reference.RepoObject_reference_T
reference.RepoObject_reference_additional <.. reference.RepoObject_reference_union
reference.RepoObject_reference_persistence <.. reference.RepoObject_reference_union
reference.RepoObject_reference_persistence_target_as_source <.. reference.RepoObject_reference
reference.RepoObject_reference_persistence_target_as_source <.. reference.RepoObject_reference_union
reference.RepoObject_reference_persistence_target_as_source_explicit <.. reference.RepoObject_reference
reference.RepoObject_reference_persistence_target_as_source_explicit <.. reference.RepoObject_reference_union
reference.RepoObject_reference_SqlExpressionDependencies <.. reference.RepoObject_reference_persistence_target_as_source
reference.RepoObject_reference_SqlExpressionDependencies <.. reference.RepoObject_reference_persistence_target_as_source_explicit
reference.RepoObject_reference_SqlExpressionDependencies <.. reference.RepoObject_reference_union
reference.RepoObject_reference_T <.. docs.RepoObject_Plantuml_ObjectRefList_0_30
reference.RepoObject_reference_T <.. docs.RepoObject_Plantuml_ObjectRefList_1_1
reference.RepoObject_reference_T <.. docs.RepoObject_Plantuml_ObjectRefList_30_0
reference.RepoObject_reference_T <.. reference.RepoObject_ReferencedReferencing
reference.RepoObject_reference_T <.. reference.RepoObjectColumn_reference_additional
reference.RepoObject_reference_T <.. reference.RepoObjectColumn_reference_SqlExpressionDependencies
reference.RepoObject_reference_T <.. reference.RepoObjectColumn_reference_virtual
reference.RepoObject_reference_union <.. reference.RepoObject_reference
reference.RepoObject_reference_virtual <.. reference.RepoObject_reference_union
reference.RepoObject_ReferencedList <.. repo.RepoObject_sat2
reference.RepoObject_ReferencedReferencing <.. reference.RepoObject_ReferencedList
reference.RepoObject_ReferencedReferencing <.. reference.RepoObject_ReferencingList
reference.RepoObject_ReferencedReferencing <.. repo.RepoObject_gross
reference.RepoObject_ReferenceTree <.. docs.ftv_RepoObject_Reference_PlantUml_EntityRefList
reference.RepoObject_ReferenceTree <.. docs.RepoObject_Plantuml_ObjectRefList_0_30
reference.RepoObject_ReferenceTree <.. docs.RepoObject_Plantuml_ObjectRefList_30_0
reference.RepoObject_ReferencingList <.. repo.RepoObject_sat2
reference.RepoObjectColumn_reference <.. reference.RepoObjectColumn_reference_T
reference.RepoObjectColumn_reference_additional <.. reference.RepoObjectColumn_reference_union
reference.RepoObjectColumn_reference_Persistence <.. reference.RepoObjectColumn_reference_union
reference.RepoObjectColumn_reference_SqlExpressionDependencies <.. reference.RepoObjectColumn_reference_union
reference.RepoObjectColumn_reference_SqlModules <.. reference.RepoObjectColumn_reference_union
reference.RepoObjectColumn_reference_T <.. docs.RepoObject_Plantuml_ColRefList_1_1
reference.RepoObjectColumn_reference_T <.. reference.RepoObjectColumn_ReferencedReferencing
reference.RepoObjectColumn_reference_union <.. reference.RepoObjectColumn_reference
reference.RepoObjectColumn_reference_virtual <.. reference.RepoObjectColumn_reference_union
reference.RepoObjectColumn_ReferencedList <.. repo.RepoObjectColumn_gross2
reference.RepoObjectColumn_ReferencedReferencing <.. reference.RepoObjectColumn_ReferencedList
reference.RepoObjectColumn_ReferencedReferencing <.. reference.RepoObjectColumn_ReferencingList
reference.RepoObjectColumn_ReferencingList <.. repo.RepoObjectColumn_gross2
reference.RepoObjectColumnSource_virtual <.. reference.RepoObjectColumn_reference_virtual
reference.RepoObjectSource_virtual <.. reference.RepoObject_reference_virtual
repo.ForeignKey_gross <.. docs.RepoObject_IndexList
repo.ForeignKey_Indexes <.. repo.ForeignKey_Indexes_union
repo.ForeignKey_Indexes_union <.. repo.ForeignKey_Indexes_union_T
repo.ForeignKey_Indexes_union_T <.. docs.RepoObject_PlantUml_FkRefList
repo.ForeignKey_Indexes_union_T <.. repo.ForeignKey_gross
repo.ForeignKey_Indexes_union_T <.. repo.RepoObject_related_FK_union
repo.ForeignKey_IndexPattern <.. repo.ForeignKey_Indexes
repo.ForeignKey_ssas_Indexes <.. repo.ForeignKey_Indexes_union
repo.ForeignKey_ssas_IndexPattern <.. repo.ForeignKey_ssas_Indexes
repo.ForeignKey_virtual <.. repo.ForeignKey_virtual_Indexes
repo.ForeignKey_virtual_Indexes <.. repo.ForeignKey_Indexes_union
repo.Index_ColumList <.. repo.Index_ColumList_T
repo.Index_ColumList_T <.. repo.Index_gross
repo.Index_gross <.. docs.RepoObject_IndexList
repo.Index_gross <.. repo.ForeignKey_gross
repo.Index_gross <.. repo.ForeignKey_Indexes
repo.Index_gross <.. repo.ForeignKey_virtual_Indexes
repo.Index_Settings <.. repo.Index_gross
repo.Index_Settings <.. repo.RepoObject_gross
repo.Index_ssas <.. repo.Index_ssas_T
repo.Index_ssas_IndexPatternColumnGuid <.. repo.Index_union
repo.Index_ssas_T <.. repo.ForeignKey_ssas_Indexes
repo.Index_ssas_T <.. repo.Index_ssas_IndexPatternColumnGuid
repo.Index_ssas_T <.. repo.Index_union
repo.Index_ssas_T <.. repo.IndexColumn_ssas
repo.Index_ssas_T <.. repo.IndexColumn_ssas_gross
repo.Index_union <.. repo.Index_gross
repo.Index_unique_IndexPatternColumnGuid <.. repo.Index_union
repo.Index_virtual <.. repo.Index_union
repo.Index_virtual <.. repo.Index_virtual_IndexPatternColumnGuid
repo.Index_virtual <.. repo.IndexColumn_virtual_gross
repo.Index_virtual_IndexPatternColumnGuid <.. repo.Index_union
repo.IndexColumn_ssas <.. repo.IndexColumn_ssas_T
repo.IndexColumn_ssas_gross <.. repo.IndexColumn_union
repo.IndexColumn_ssas_T <.. repo.Index_ssas_IndexPatternColumnGuid
repo.IndexColumn_ssas_T <.. repo.IndexColumn_ssas_gross
repo.IndexColumn_union <.. repo.IndexColumn_union_T
repo.IndexColumn_union_T <.. repo.Index_ColumList
repo.IndexColumn_union_T <.. repo.RepoObjectColumn_gross2
repo.IndexColumn_virtual <.. repo.Index_virtual_IndexPatternColumnGuid
repo.IndexColumn_virtual <.. repo.IndexColumn_virtual_gross
repo.IndexColumn_virtual_gross <.. repo.IndexColumn_union
repo.Measure <.. docs.Measure_MeasurePropertyList
repo.Measure <.. repo.Measure_union
repo.Measure_union <.. docs.RepoObject_MeasureDescriptionList
repo.Measure_union <.. docs.RepoObject_MeasureList
repo.Measure_union <.. ssas.Measure_translation
repo.RepoObject <.. docs.ftv_RepoObject_AntoraXref
repo.RepoObject <.. docs.ftv_RepoObject_Reference_PlantUml_EntityRefList
repo.RepoObject <.. docs.RepoObject_Plantuml_ObjectRefList_1_1
repo.RepoObject <.. property.RepoObjectColumnProperty_external_tgt
repo.RepoObject <.. property.RepoObjectProperty_cross
repo.RepoObject <.. property.RepoObjectProperty_external_tgt
repo.RepoObject <.. reference.additional_Reference_guid
repo.RepoObject <.. reference.RepoObject_reference_persistence
repo.RepoObject <.. reference.RepoObject_reference_persistence_target_as_source_explicit
repo.RepoObject <.. reference.RepoObject_reference_SqlExpressionDependencies
repo.RepoObject <.. reference.RepoObject_reference_virtual
repo.RepoObject <.. reference.RepoObjectColumn_reference_Persistence
repo.RepoObject <.. reference.RepoObjectColumn_reference_SqlModules
repo.RepoObject <.. repo.IndexColumn_ssas_gross
repo.RepoObject <.. repo.IndexColumn_virtual_gross
repo.RepoObject <.. repo.RepoObject_external_src
repo.RepoObject <.. repo.RepoObject_gross
repo.RepoObject <.. repo.RepoObject_gross_persistence
repo.RepoObject <.. repo.RepoObject_related_FK_union
repo.RepoObject <.. repo.RepoObjectColumn_external_src
repo.RepoObject <.. repo.RepoObjectColumn_gross
repo.RepoObject <.. repo.SysColumn_RepoObjectColumn_via_name
repo.RepoObject <.. repo.SysObject_RepoObject_via_name
repo.RepoObject <.. repo_sys.ForeignKey
repo.RepoObject <.. repo_sys.Index_unique
repo.RepoObject <.. sqlparse.RepoObject_SqlModules_10_statement
repo.RepoObject <.. sqlparse.RepoObject_SqlModules_39_object
repo.RepoObject <.. sqlparse.RepoObject_SqlModules_71_reference_ExpliciteTableAlias
repo.RepoObject <.. sqlparse.RepoObject_SqlModules_72_reference_NoTableAlias
repo.RepoObject <.. sqlparse.RepoObject_SqlModules_Repo_Sys
repo.RepoObject_ColumnList <.. repo.RepoObject_sat2
repo.RepoObject_external_src <.. repo.RepoObject_external_tgt
repo.RepoObject_external_tgt <.. repo.RepoObject
repo.RepoObject_external_tgt <.. repo.RepoObjectColumn_external_tgt
repo.RepoObject_gross <.. docs.RepoObject_Adoc
repo.RepoObject_gross <.. docs.RepoObject_OutputFilter
repo.RepoObject_gross <.. docs.RepoObject_Plantuml
repo.RepoObject_gross <.. repo.Index_gross
repo.RepoObject_gross <.. repo.RepoObject_sat2
repo.RepoObject_gross_persistence <.. reference.RepoObject_reference_persistence_target_as_source
repo.RepoObject_persistence <.. reference.RepoObject_reference_persistence
repo.RepoObject_persistence <.. reference.RepoObject_reference_persistence_target_as_source_explicit
repo.RepoObject_persistence <.. reference.RepoObjectColumn_reference_Persistence
repo.RepoObject_persistence <.. repo.RepoObject_ColumnList
repo.RepoObject_persistence <.. repo.RepoObject_gross
repo.RepoObject_persistence <.. repo.RepoObject_gross_persistence
repo.RepoObject_persistence <.. repo.RepoObjectColumn_gross
repo.RepoObject_related_FK_union <.. docs.RepoObject_PlantUml_FkRefList
repo.RepoObject_related_FK_union <.. docs.RepoObject_PlantUml_PumlEntityFkList
repo.RepoObject_sat2 <.. repo.RepoObject_sat2_T
repo.RepoObject_sat2_T <.. docs.RepoObject_Adoc
repo.RepoObject_SSAS_src <.. repo.RepoObject_SSAS_tgt
repo.RepoObject_SSAS_tgt <.. repo.RepoObject
repo.RepoObject_SSAS_tgt <.. repo.RepoObjectColumn_SSAS_tgt
repo.RepoObjectColumn <.. property.RepoObjectColumnProperty_external_tgt
repo.RepoObjectColumn <.. reference.additional_Reference_guid
repo.RepoObjectColumn <.. reference.RepoObjectColumn_reference_Persistence
repo.RepoObjectColumn <.. reference.RepoObjectColumn_reference_SqlModules
repo.RepoObjectColumn <.. repo.IndexColumn_ssas_gross
repo.RepoObjectColumn <.. repo.IndexColumn_virtual_gross
repo.RepoObjectColumn <.. repo.RepoObjectColumn_gross
repo.RepoObjectColumn <.. repo.RepoObjectColumn_gross2
repo.RepoObjectColumn <.. repo.SysColumn_RepoObjectColumn_via_name
repo.RepoObjectColumn <.. sqlparse.RepoObject_SqlModules_71_reference_ExpliciteTableAlias
repo.RepoObjectColumn <.. sqlparse.RepoObject_SqlModules_72_reference_NoTableAlias
repo.RepoObjectColumn_external_src <.. repo.RepoObjectColumn_external_tgt
repo.RepoObjectColumn_external_tgt <.. repo.RepoObjectColumn
repo.RepoObjectColumn_gross <.. reference.RepoObjectColumn_reference_virtual
repo.RepoObjectColumn_gross <.. repo.RepoObjectColumn_gross2
repo.RepoObjectColumn_gross <.. ssas.RepoObjectColumn_translation
repo.RepoObjectColumn_gross2 <.. docs.RepoObject_ColumnList
repo.RepoObjectColumn_gross2 <.. repo.RepoObject_ColumnList
repo.RepoObjectColumn_SSAS_src <.. repo.RepoObjectColumn_SSAS_tgt
repo.RepoObjectColumn_SSAS_tgt <.. repo.RepoObjectColumn
repo.RepoSchema <.. repo.Measure
repo.RepoSchema <.. repo.RepoObject_SSAS_src
repo.RepoSchema_ssas_src <.. repo.RepoSchema_ssas_tgt
repo.RepoSchema_ssas_tgt <.. repo.RepoSchema
repo.SysColumn_RepoObjectColumn_via_name <.. repo_sys.IndexColumn_unique
repo.SysColumn_RepoObjectColumn_via_name <.. repo_sys.sql_expression_dependencies
repo.SysObject_RepoObject_via_name <.. repo_sys.IndexColumn_unique
repo.SysObject_RepoObject_via_name <.. repo_sys.sql_expression_dependencies
repo_sys.ExtendedProperties <.. repo_sys.SysColumn
repo_sys.ExtendedProperties <.. repo_sys.SysObject
repo_sys.ForeignKey <.. repo.ForeignKey_IndexPattern
repo_sys.ForeignKey <.. repo_sys.ForeignKeyColumn
repo_sys.ForeignKeyColumn <.. repo.ForeignKey_IndexPattern
repo_sys.Index_unique <.. repo.Index_union
repo_sys.IndexColumn_unique <.. repo.Index_unique_IndexPatternColumnGuid
repo_sys.IndexColumn_unique <.. repo.IndexColumn_union
repo_sys.parameters <.. docs.RepoObject_ParameterList
repo_sys.sql_expression_dependencies <.. reference.RepoObject_reference_SqlExpressionDependencies
repo_sys.sql_expression_dependencies <.. reference.RepoObjectColumn_reference_SqlExpressionDependencies
repo_sys.SysColumn <.. repo.SysColumn_RepoObjectColumn_via_name
repo_sys.SysColumn <.. repo_sys.ForeignKeyColumn
repo_sys.SysObject <.. repo.SysObject_RepoObject_via_name
repo_sys.SysObject <.. repo_sys.parameters
repo_sys.SysObject <.. repo_sys.SysColumn
repo_sys.SysObject <.. sqlparse.RepoObject_SqlModules_Repo_Sys
sqlparse.ftv_sqlparse <.. sqlparse.RepoObject_SqlModules_22_identifier_alias_AS
sqlparse.ftv_sqlparse_children_pivot <.. sqlparse.RepoObject_SqlModules_25_IdentifierList_children_IdentifierSplit
sqlparse.ftv_sqlparse_with_some_children <.. sqlparse.RepoObject_SqlModules_20_statement_children
sqlparse.ftv_sqlparse_with_some_children <.. sqlparse.RepoObject_SqlModules_24_IdentifierList_children
sqlparse.RepoObject_SqlModules <.. sqlparse.RepoObject_SqlModules_10_statement
sqlparse.RepoObject_SqlModules <.. sqlparse.RepoObject_SqlModules_39_object
sqlparse.RepoObject_SqlModules <.. sqlparse.RepoObject_SqlModules_Repo_Sys
sqlparse.RepoObject_SqlModules_10_statement <.. sqlparse.RepoObject_SqlModules_20_statement_children
sqlparse.RepoObject_SqlModules_20_statement_children <.. sqlparse.RepoObject_SqlModules_21_statement_children_helper
sqlparse.RepoObject_SqlModules_20_statement_children <.. sqlparse.RepoObject_SqlModules_22_identifier_alias_AS
sqlparse.RepoObject_SqlModules_20_statement_children <.. sqlparse.RepoObject_SqlModules_24_IdentifierList_children
sqlparse.RepoObject_SqlModules_20_statement_children <.. sqlparse.RepoObject_SqlModules_29_1_object_is_union
sqlparse.RepoObject_SqlModules_20_statement_children <.. sqlparse.RepoObject_SqlModules_29_2_object_is_GroupBy
sqlparse.RepoObject_SqlModules_20_statement_children <.. sqlparse.RepoObject_SqlModules_32_ObjectClass
sqlparse.RepoObject_SqlModules_20_statement_children <.. sqlparse.RepoObject_SqlModules_33_ObjectNormalized
sqlparse.RepoObject_SqlModules_20_statement_children <.. sqlparse.RepoObject_SqlModules_41_from
sqlparse.RepoObject_SqlModules_20_statement_children <.. sqlparse.RepoObject_SqlModules_51_Identitfier
sqlparse.RepoObject_SqlModules_21_statement_children_helper <.. sqlparse.RepoObject_SqlModules_31_object
sqlparse.RepoObject_SqlModules_22_identifier_alias_AS <.. sqlparse.RepoObject_SqlModules_41_from
sqlparse.RepoObject_SqlModules_24_IdentifierList_children <.. sqlparse.RepoObject_SqlModules_25_IdentifierList_children_IdentifierSplit
sqlparse.RepoObject_SqlModules_25_IdentifierList_children_IdentifierSplit <.. sqlparse.RepoObject_SqlModules_26_IdentifierList_children_IdentifierSplit_QuoteName
sqlparse.RepoObject_SqlModules_26_IdentifierList_children_IdentifierSplit_QuoteName <.. sqlparse.RepoObject_SqlModules_61_SelectIdentifier_Union
sqlparse.RepoObject_SqlModules_29_1_object_is_union <.. sqlparse.RepoObject_SqlModules_39_object
sqlparse.RepoObject_SqlModules_29_1_object_is_union <.. sqlparse.RepoObject_SqlModules_42_from_Identifier
sqlparse.RepoObject_SqlModules_29_2_object_is_GroupBy <.. sqlparse.RepoObject_SqlModules_39_object
sqlparse.RepoObject_SqlModules_31_object <.. sqlparse.RepoObject_SqlModules_39_object
sqlparse.RepoObject_SqlModules_32_ObjectClass <.. sqlparse.RepoObject_SqlModules_39_object
sqlparse.RepoObject_SqlModules_33_ObjectNormalized <.. sqlparse.RepoObject_SqlModules_39_object
sqlparse.RepoObject_SqlModules_39_object <.. sqlparse.RepoObject_SqlModules_41_from
sqlparse.RepoObject_SqlModules_39_object <.. sqlparse.RepoObject_SqlModules_61_SelectIdentifier_Union
sqlparse.RepoObject_SqlModules_41_from <.. sqlparse.RepoObject_SqlModules_41_from_T
sqlparse.RepoObject_SqlModules_41_from_T <.. sqlparse.RepoObject_SqlModules_42_from_Identifier
sqlparse.RepoObject_SqlModules_42_from_Identifier <.. sqlparse.RepoObject_SqlModules_43_from_Identifier
sqlparse.RepoObject_SqlModules_43_from_Identifier <.. sqlparse.RepoObject_SqlModules_44_from_Identifier_QuoteName
sqlparse.RepoObject_SqlModules_44_from_Identifier_QuoteName <.. sqlparse.RepoObject_SqlModules_71_reference_ExpliciteTableAlias
sqlparse.RepoObject_SqlModules_44_from_Identifier_QuoteName <.. sqlparse.RepoObject_SqlModules_72_reference_NoTableAlias
sqlparse.RepoObject_SqlModules_51_Identitfier <.. sqlparse.RepoObject_SqlModules_52_Identitfier_QuoteName
sqlparse.RepoObject_SqlModules_52_Identitfier_QuoteName <.. sqlparse.RepoObject_SqlModules_61_SelectIdentifier_Union
sqlparse.RepoObject_SqlModules_61_SelectIdentifier_Union <.. sqlparse.RepoObject_SqlModules_61_SelectIdentifier_Union_T
sqlparse.RepoObject_SqlModules_61_SelectIdentifier_Union_T <.. sqlparse.RepoObject_SqlModules_71_reference_ExpliciteTableAlias
sqlparse.RepoObject_SqlModules_61_SelectIdentifier_Union_T <.. sqlparse.RepoObject_SqlModules_72_reference_NoTableAlias
sqlparse.RepoObject_SqlModules_71_reference_ExpliciteTableAlias <.. sqlparse.RepoObject_SqlModules_79_reference_union
sqlparse.RepoObject_SqlModules_72_reference_NoTableAlias <.. sqlparse.RepoObject_SqlModules_79_reference_union
sqlparse.RepoObject_SqlModules_79_reference_union <.. reference.RepoObjectColumn_reference_SqlModules
sqlparse.RepoObject_SqlModules_Repo_Sys <.. repo.RepoObject_sat2
ssas.additional_Reference_step1 <.. reference.additional_Reference_from_ssas_src
ssas.IndexColumn_from_IsKey <.. ssas.IndexColumn_union
ssas.IndexColumn_from_IsUnique <.. ssas.IndexColumn_union
ssas.IndexColumn_from_Relationship <.. ssas.IndexColumn_union
ssas.IndexColumn_union <.. repo.Index_ssas
ssas.IndexColumn_union <.. repo.IndexColumn_ssas
ssas.Measure_translation <.. ssas.Measure_translation_T
ssas.Measure_translation_displayfolder_union <.. docs.RepoObject_MeasureList
ssas.Measure_translation_T <.. docs.RepoObject_MeasureDescriptionList
ssas.Measure_translation_T <.. ssas.Measure_translation_displayfolder_union
ssas.model_json <.. ssas.model_json_10
ssas.model_json_10 <.. ssas.model_json_20
ssas.model_json_20 <.. repo.RepoSchema_ssas_src
ssas.model_json_20 <.. ssas.model_json_201_descriptions_multiline
ssas.model_json_20 <.. ssas.model_json_31_tables
ssas.model_json_20 <.. ssas.model_json_32_relationships
ssas.model_json_20 <.. ssas.model_json_33_dataSources
ssas.model_json_20 <.. ssas.model_json_34_cultures
ssas.model_json_201_descriptions_multiline <.. ssas.model_json_2011_descriptions_StrAgg
ssas.model_json_2011_descriptions_StrAgg <.. repo.RepoSchema_ssas_src
ssas.model_json_31_tables <.. ssas.model_json_31_tables_T
ssas.model_json_31_tables_T <.. repo.ForeignKey_ssas_IndexPattern
ssas.model_json_31_tables_T <.. repo.RepoObject_gross
ssas.model_json_31_tables_T <.. repo.RepoObject_SSAS_src
ssas.model_json_31_tables_T <.. ssas.model_json_311_tables_columns
ssas.model_json_31_tables_T <.. ssas.model_json_312_tables_measures
ssas.model_json_31_tables_T <.. ssas.model_json_313_tables_partitions
ssas.model_json_31_tables_T <.. ssas.model_json_316_tables_descriptions_multiline
ssas.model_json_311_tables_columns <.. ssas.model_json_311_tables_columns_T
ssas.model_json_311_tables_columns_T <.. repo.ForeignKey_ssas_IndexPattern
ssas.model_json_311_tables_columns_T <.. repo.RepoObjectColumn_gross
ssas.model_json_311_tables_columns_T <.. repo.RepoObjectColumn_SSAS_src
ssas.model_json_311_tables_columns_T <.. ssas.additional_Reference_step1
ssas.model_json_311_tables_columns_T <.. ssas.IndexColumn_from_IsKey
ssas.model_json_311_tables_columns_T <.. ssas.IndexColumn_from_IsUnique
ssas.model_json_311_tables_columns_T <.. ssas.IndexColumn_from_Relationship
ssas.model_json_311_tables_columns_T <.. ssas.model_json_3111_tables_columns_descriptions_multiline
ssas.model_json_311_tables_columns_T <.. ssas.model_json_3112_tables_columns_expressions_multiline
ssas.model_json_311_tables_columns_T <.. ssas.RepoObjectColumn_translation
ssas.model_json_3111_tables_columns_descriptions_multiline <.. ssas.model_json_31111_tables_columns_descriptions_StrAgg
ssas.model_json_31111_tables_columns_descriptions_StrAgg <.. repo.RepoObjectColumn_gross
ssas.model_json_3112_tables_columns_expressions_multiline <.. ssas.model_json_31121_tables_columns_expressions_StrAgg
ssas.model_json_31121_tables_columns_expressions_StrAgg <.. repo.RepoObjectColumn_gross
ssas.model_json_312_tables_measures <.. ssas.model_json_312_tables_measures_T
ssas.model_json_312_tables_measures_T <.. repo.Measure
ssas.model_json_312_tables_measures_T <.. ssas.model_json_3121_tables_columns_descriptions_multiline
ssas.model_json_312_tables_measures_T <.. ssas.model_json_3122_tables_measures_expressions_multiline
ssas.model_json_3121_tables_columns_descriptions_multiline <.. ssas.model_json_31211_tables_columns_descriptions_StrAgg
ssas.model_json_31211_tables_columns_descriptions_StrAgg <.. repo.Measure
ssas.model_json_3122_tables_measures_expressions_multiline <.. ssas.model_json_31221_tables_measures_expressions_StrAgg
ssas.model_json_31221_tables_measures_expressions_StrAgg <.. repo.Measure
ssas.model_json_313_tables_partitions <.. ssas.model_json_3131_tables_partitions_source
ssas.model_json_3131_tables_partitions_source <.. ssas.model_json_31311_tables_partitions_source_PosFrom
ssas.model_json_31311_tables_partitions_source_PosFrom <.. ssas.model_json_313111_tables_partitions_source_StringFrom
ssas.model_json_313111_tables_partitions_source_StringFrom <.. ssas.model_json_3131111_tables_partitions_source_PosDot
ssas.model_json_3131111_tables_partitions_source_PosDot <.. ssas.model_json_31311111_tables_partitions_source_Part123
ssas.model_json_31311111_tables_partitions_source_Part123 <.. ssas.additional_Reference_step1
ssas.model_json_316_tables_descriptions_multiline <.. ssas.model_json_3161_tables_descriptions_StrAgg
ssas.model_json_3161_tables_descriptions_StrAgg <.. repo.RepoObject_gross
ssas.model_json_32_relationships <.. ssas.model_json_32_relationships_T
ssas.model_json_32_relationships_T <.. repo.ForeignKey_ssas_IndexPattern
ssas.model_json_32_relationships_T <.. ssas.IndexColumn_from_Relationship
ssas.model_json_33_dataSources <.. ssas.model_json_33_dataSources_T
ssas.model_json_33_dataSources_T <.. ssas.additional_Reference_step1
ssas.model_json_34_cultures <.. ssas.model_json_341_cultures_translations
ssas.model_json_341_cultures_translations <.. ssas.model_json_3411_cultures_translations_model
ssas.model_json_3411_cultures_translations_model <.. ssas.model_json_3411_cultures_translations_model_T
ssas.model_json_3411_cultures_translations_model_T <.. docs.Culture
ssas.model_json_3411_cultures_translations_model_T <.. docs.RepoObject_OutputFilter
ssas.model_json_3411_cultures_translations_model_T <.. ssas.model_json_34111_cultures_translations_model_tables
ssas.model_json_34111_cultures_translations_model_tables <.. docs.RepoObject_OutputFilter
ssas.model_json_34111_cultures_translations_model_tables <.. ssas.model_json_341111_cultures_translations_model_tables_columns
ssas.model_json_34111_cultures_translations_model_tables <.. ssas.model_json_341113_cultures_translations_model_tables_measures
ssas.model_json_341111_cultures_translations_model_tables_columns <.. ssas.RepoObjectColumn_translation
ssas.model_json_341113_cultures_translations_model_tables_measures <.. ssas.Measure_translation
ssas.RepoObjectColumn_translation <.. ssas.RepoObjectColumn_translation_T
ssas.RepoObjectColumn_translation_displayfolder_union <.. docs.RepoObject_ColumnList
ssas.RepoObjectColumn_translation_T <.. docs.RepoObject_Plantuml_ColRefList_1_1
ssas.RepoObjectColumn_translation_T <.. ssas.RepoObjectColumn_translation_displayfolder_union
ssis.AntoraModule_tgt_filter <.. ssis.Package_tgt
ssis.AntoraModule_tgt_filter <.. ssis.PackageConnection_tgt
ssis.AntoraModule_tgt_filter <.. ssis.PackageFlow_tgt
ssis.AntoraModule_tgt_filter <.. ssis.PackageParameter_tgt
ssis.AntoraModule_tgt_filter <.. ssis.PackageTask_Dft_Component_input_externalMetadataColumn_tgt
ssis.AntoraModule_tgt_filter <.. ssis.PackageTask_Dft_Component_input_inputColumn_tgt
ssis.AntoraModule_tgt_filter <.. ssis.PackageTask_Dft_Component_input_tgt
ssis.AntoraModule_tgt_filter <.. ssis.PackageTask_Dft_Component_output_outputcolumn_tgt
ssis.AntoraModule_tgt_filter <.. ssis.PackageTask_Dft_Component_output_tgt
ssis.AntoraModule_tgt_filter <.. ssis.PackageTask_Dft_Component_tgt
ssis.AntoraModule_tgt_filter <.. ssis.PackageTask_Sql_Parameter_tgt
ssis.AntoraModule_tgt_filter <.. ssis.PackageTask_tgt
ssis.AntoraModule_tgt_filter <.. ssis.PackageVariable_tgt
ssis.AntoraModule_tgt_filter <.. ssis.ProjectConnection_tgt
ssis.Package <.. docs.ssis_Adoc
ssis.Package <.. docs.ssis_GeneralList
ssis.Package <.. docs.ssis_navlist_package
ssis.Package <.. docs.usp_AntoraExport_SsisPage
ssis.Package_src <.. ssis.AntoraModule_tgt_filter
ssis.Package_src <.. ssis.Package_tgt
ssis.Package_src <.. ssis.PackageConnection_src
ssis.Package_src <.. ssis.PackageFlow_src
ssis.Package_src <.. ssis.PackageParameter_src
ssis.Package_src <.. ssis.PackageTask_Dft_Component_input_externalMetadataColumn_src
ssis.Package_src <.. ssis.PackageTask_Dft_Component_input_inputColumn_src
ssis.Package_src <.. ssis.PackageTask_Dft_Component_input_src
ssis.Package_src <.. ssis.PackageTask_Dft_Component_output_outputcolumn_src
ssis.Package_src <.. ssis.PackageTask_Dft_Component_output_src
ssis.Package_src <.. ssis.PackageTask_Dft_Component_src
ssis.Package_src <.. ssis.PackageTask_Sql_Parameter_src
ssis.Package_src <.. ssis.PackageTask_src
ssis.Package_src <.. ssis.PackageVariable_src
ssis.Package_tgt <.. ssis.Package
ssis.PackageConnection <.. docs.ssis_PackageConnectionList
ssis.PackageConnection <.. docs.ssis_TaskList
ssis.PackageConnection_src <.. ssis.PackageConnection_tgt
ssis.PackageConnection_tgt <.. ssis.PackageConnection
ssis.PackageFlow <.. docs.ssis_PumlPartialControlFlows
ssis.PackageFlow <.. docs.ssis_PumlPartialDataFlow
ssis.PackageFlow_src <.. ssis.PackageFlow_tgt
ssis.PackageFlow_tgt <.. ssis.PackageFlow
ssis.PackageParameter <.. docs.ssis_ParameterList
ssis.PackageParameter_src <.. ssis.PackageParameter_tgt
ssis.PackageParameter_tgt <.. ssis.PackageParameter
ssis.PackageTask <.. docs.ssis_TaskList
ssis.PackageTask <.. ssis.PackageTask_LevelLagLead
ssis.PackageTask_Dft_Component <.. docs.ssis_DftTaskComponentList
ssis.PackageTask_Dft_Component <.. docs.ssis_PumlDftTask
ssis.PackageTask_Dft_Component <.. docs.ssis_PumlPartialDftComponent
ssis.PackageTask_Dft_Component_input <.. docs.ssis_DftTaskComponentInputList
ssis.PackageTask_Dft_Component_input_externalMetadataColumn <.. docs.ssis_DftTaskComponentInputColumnList
ssis.PackageTask_Dft_Component_input_externalMetadataColumn <.. docs.ssis_DftTaskComponentOutputColumnList
ssis.PackageTask_Dft_Component_input_externalMetadataColumn_src <.. ssis.PackageTask_Dft_Component_input_externalMetadataColumn_tgt
ssis.PackageTask_Dft_Component_input_externalMetadataColumn_tgt <.. ssis.PackageTask_Dft_Component_input_externalMetadataColumn
ssis.PackageTask_Dft_Component_input_inputColumn <.. docs.ssis_DftTaskComponentInputColumnList
ssis.PackageTask_Dft_Component_input_inputColumn_src <.. ssis.PackageTask_Dft_Component_input_inputColumn_tgt
ssis.PackageTask_Dft_Component_input_inputColumn_tgt <.. ssis.PackageTask_Dft_Component_input_inputColumn
ssis.PackageTask_Dft_Component_input_src <.. ssis.PackageTask_Dft_Component_input_tgt
ssis.PackageTask_Dft_Component_input_tgt <.. ssis.PackageTask_Dft_Component_input
ssis.PackageTask_Dft_Component_output <.. docs.ssis_DftTaskComponentOutputList
ssis.PackageTask_Dft_Component_output_outputcolumn <.. docs.ssis_DftTaskComponentOutputColumnList
ssis.PackageTask_Dft_Component_output_outputcolumn_src <.. ssis.PackageTask_Dft_Component_output_outputcolumn_tgt
ssis.PackageTask_Dft_Component_output_outputcolumn_tgt <.. ssis.PackageTask_Dft_Component_output_outputcolumn
ssis.PackageTask_Dft_Component_output_src <.. ssis.PackageTask_Dft_Component_output_tgt
ssis.PackageTask_Dft_Component_output_tgt <.. ssis.PackageTask_Dft_Component_output
ssis.PackageTask_Dft_Component_src <.. ssis.PackageTask_Dft_Component_tgt
ssis.PackageTask_Dft_Component_tgt <.. ssis.PackageTask_Dft_Component
ssis.PackageTask_LevelLagLead <.. docs.ssis_PumlPartialTaskComponent
ssis.PackageTask_Sql_Parameter <.. docs.ssis_SqlTaskParameterInnerTable
ssis.PackageTask_Sql_Parameter_src <.. ssis.PackageTask_Sql_Parameter_tgt
ssis.PackageTask_Sql_Parameter_tgt <.. ssis.PackageTask_Sql_Parameter
ssis.PackageTask_src <.. ssis.PackageTask_tgt
ssis.PackageTask_tgt <.. ssis.PackageTask
ssis.PackageVariable <.. docs.ssis_VariableList
ssis.PackageVariable_src <.. ssis.PackageVariable_tgt
ssis.PackageVariable_tgt <.. ssis.PackageVariable
ssis.Project <.. docs.usp_AntoraExport
ssis.Project <.. docs.usp_AntoraExport_SsisPageTemplate
ssis.Project <.. ssis.Package_src
ssis.Project <.. ssis.ProjectConnection_src
ssis.ProjectConnection <.. docs.ssis_ProjectConnectionList
ssis.ProjectConnection <.. docs.ssis_TaskList
ssis.ProjectConnection_src <.. ssis.ProjectConnection_tgt
ssis.ProjectConnection_tgt <.. ssis.ProjectConnection
ssis_t.pkgStats <.. ssis.Package_src
ssis_t.ProjectConnection <.. ssis.ProjectConnection_src
ssis_t.TblConnection <.. ssis.PackageConnection_src
ssis_t.TblControlFlow <.. ssis.PackageTask_Dft_Component_input_externalMetadataColumn_src
ssis_t.TblControlFlow <.. ssis.PackageTask_Dft_Component_input_inputColumn_src
ssis_t.TblControlFlow <.. ssis.PackageTask_Dft_Component_input_src
ssis_t.TblControlFlow <.. ssis.PackageTask_Dft_Component_output_outputcolumn_src
ssis_t.TblControlFlow <.. ssis.PackageTask_Dft_Component_output_src
ssis_t.TblControlFlow <.. ssis.PackageTask_Dft_Component_src
ssis_t.TblControlFlow <.. ssis.PackageTask_Sql_Parameter_src
ssis_t.TblControlFlow <.. ssis.PackageTask_src
ssis_t.TblParameter <.. ssis.PackageParameter_src
ssis_t.TblPrecedenceConstraint <.. ssis.PackageFlow_src
ssis_t.TblProjectConnection <.. ssis.ProjectConnection_src
ssis_t.TblTask_Dft_Component <.. ssis.PackageTask_Dft_Component_src
ssis_t.TblTask_Dft_Component <.. ssis_t.TblTask_Dft_Component_inputs_externalMetadataColumn_src
ssis_t.TblTask_Dft_Component <.. ssis_t.TblTask_Dft_Component_inputs_inputColumn_src
ssis_t.TblTask_Dft_Component <.. ssis_t.TblTask_Dft_Component_inputs_src
ssis_t.TblTask_Dft_Component <.. ssis_t.TblTask_Dft_Component_outputs_outputColumn_src
ssis_t.TblTask_Dft_Component <.. ssis_t.TblTask_Dft_Component_outputs_src
ssis_t.TblTask_Dft_Component_inputs_externalMetadataColumn_src <.. ssis.PackageTask_Dft_Component_input_externalMetadataColumn_src
ssis_t.TblTask_Dft_Component_inputs_inputColumn_src <.. ssis.PackageTask_Dft_Component_input_inputColumn_src
ssis_t.TblTask_Dft_Component_inputs_src <.. ssis.PackageTask_Dft_Component_input_src
ssis_t.TblTask_Dft_Component_outputs_outputColumn_src <.. ssis.PackageTask_Dft_Component_output_outputcolumn_src
ssis_t.TblTask_Dft_Component_outputs_src <.. ssis.PackageTask_Dft_Component_output_src
ssis_t.TblTask_ExecutePackage <.. ssis.PackageTask_src
ssis_t.TblTask_Script <.. ssis.PackageTask_src
ssis_t.TblTask_Sql <.. ssis.PackageTask_src
ssis_t.TblTask_Sql_Parameter <.. ssis.PackageTask_Sql_Parameter_src
ssis_t.TblVariable <.. ssis.PackageVariable_src
sys_dwh.columns <.. repo_sys.ExtendedProperties
sys_dwh.columns <.. repo_sys.SysColumn
sys_dwh.computed_columns <.. repo_sys.SysColumn
sys_dwh.default_constraints <.. repo_sys.SysColumn
sys_dwh.extended_properties <.. repo_sys.ExtendedProperties
sys_dwh.foreign_key_columns <.. repo_sys.ForeignKeyColumn
sys_dwh.foreign_keys <.. repo_sys.ForeignKey
sys_dwh.identity_columns <.. repo_sys.SysColumn
sys_dwh.index_columns <.. repo_sys.IndexColumn_unique
sys_dwh.indexes <.. repo_sys.ExtendedProperties
sys_dwh.indexes <.. repo_sys.Index_unique
sys_dwh.indexes <.. repo_sys.IndexColumn_unique
sys_dwh.objects <.. repo_sys.ExtendedProperties
sys_dwh.objects <.. repo_sys.SysObject
sys_dwh.parameters <.. repo_sys.ExtendedProperties
sys_dwh.parameters <.. repo_sys.parameters
sys_dwh.schemas <.. repo_sys.ExtendedProperties
sys_dwh.schemas <.. repo_sys.SysObject
sys_dwh.sql_expression_dependencies <.. repo_sys.sql_expression_dependencies
sys_dwh.sql_modules <.. repo_sys.SysObject
sys_dwh.tables <.. repo_sys.SysObject
sys_dwh.types <.. repo_sys.parameters
sys_dwh.types <.. repo_sys.SysColumn
uspgenerator.GeneratorUsp <.. repo.RepoObject_gross

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_30_0_objectref[]

=== PlantUML 0 30 ObjectRef

// tag::puml_entity_0_30_objectref[]
[plantuml, entity_0_30_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:docs.usp_antoraexport.adoc[]" as docs.usp_AntoraExport << P >> {
  --
}



footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_0_30_objectref[]

=== PlantUML 1 1 ColumnRef

// tag::puml_entity_1_1_colref[]
[plantuml, entity_1_1_colref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:config.fs_get_parameter_value.adoc[]" as config.fs_get_parameter_value << FN >> {
  --
}

entity "puml-link:dhw:sqldb:docs.command.adoc[]" as docs.command << U >> {
  - **id** : (int)
  - command : (nvarchar(4000))
  --
}

entity "puml-link:dhw:sqldb:docs.culture.adoc[]" as docs.Culture << V >> {
  - cultures_name : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.fs_antoramodulefolder.adoc[]" as docs.fs_AntoraModuleFolder << FN >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport.adoc[]" as docs.usp_AntoraExport << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_objectnavigation.adoc[]" as docs.usp_AntoraExport_ObjectNavigation << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_objectpage.adoc[]" as docs.usp_AntoraExport_ObjectPage << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_objectpagetemplate.adoc[]" as docs.usp_AntoraExport_ObjectPageTemplate << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_objectpartialscontent.adoc[]" as docs.usp_AntoraExport_ObjectPartialsContent << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_objectpuml.adoc[]" as docs.usp_AntoraExport_ObjectPuml << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_objectrefcyclic.adoc[]" as docs.usp_AntoraExport_ObjectRefCyclic << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_page_indexsemanticgroup.adoc[]" as docs.usp_AntoraExport_Page_IndexSemanticGroup << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_ssisnavigation.adoc[]" as docs.usp_AntoraExport_SsisNavigation << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_ssispage.adoc[]" as docs.usp_AntoraExport_SsisPage << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_ssispagetemplate.adoc[]" as docs.usp_AntoraExport_SsisPageTemplate << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_ssispartialscontent.adoc[]" as docs.usp_AntoraExport_SsisPartialsContent << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_ssispuml.adoc[]" as docs.usp_AntoraExport_SsisPuml << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_repoobject_outputfilter_t.adoc[]" as docs.usp_PERSIST_RepoObject_OutputFilter_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:logs.usp_executionlog_insert.adoc[]" as logs.usp_ExecutionLog_insert << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.project.adoc[]" as ssis.Project << U >> {
  - **AntoraModule** : (varchar(50))
  ProjectPath : (varchar(8000))
  ~ sql_import : (varchar(8000))
  --
}

config.fs_get_parameter_value <.. docs.usp_AntoraExport
docs.command <.. docs.usp_AntoraExport
docs.culture <.. docs.usp_AntoraExport
docs.fs_AntoraModuleFolder <.. docs.usp_AntoraExport
docs.usp_AntoraExport_ObjectNavigation <.. docs.usp_AntoraExport
docs.usp_AntoraExport_ObjectPage <.. docs.usp_AntoraExport
docs.usp_AntoraExport_ObjectPageTemplate <.. docs.usp_AntoraExport
docs.usp_AntoraExport_ObjectPartialsContent <.. docs.usp_AntoraExport
docs.usp_AntoraExport_ObjectPuml <.. docs.usp_AntoraExport
docs.usp_AntoraExport_ObjectRefCyclic <.. docs.usp_AntoraExport
docs.usp_AntoraExport_Page_IndexSemanticGroup <.. docs.usp_AntoraExport
docs.usp_AntoraExport_SsisNavigation <.. docs.usp_AntoraExport
docs.usp_AntoraExport_SsisPage <.. docs.usp_AntoraExport
docs.usp_AntoraExport_SsisPageTemplate <.. docs.usp_AntoraExport
docs.usp_AntoraExport_SsisPartialsContent <.. docs.usp_AntoraExport
docs.usp_AntoraExport_SsisPuml <.. docs.usp_AntoraExport
docs.usp_PERSIST_RepoObject_OutputFilter_T <.. docs.usp_AntoraExport
logs.usp_ExecutionLog_insert <.. docs.usp_AntoraExport
ssis.Project <.. docs.usp_AntoraExport


footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_colref[]


== sql_modules_definition

// tag::sql_modules_definition[]
[%collapsible]
=======
[source,sql,numbered,indent=0]
----
/*
code of this procedure is managed in the dhw repository. Do not modify manually.
Use [uspgenerator].[GeneratorUsp], [uspgenerator].[GeneratorUspParameter], [uspgenerator].[GeneratorUspStep], [uspgenerator].[GeneratorUsp_SqlUsp]
*/
CREATE   PROCEDURE [docs].[usp_AntoraExport]
@isExecuteCommand BIT = 0 /* specify whether the commands, collected in [docs].[command], should be executed using "Exec sys.xp_cmdshell" */
,
----keep the code between logging parameters and "START" unchanged!
---- parameters, used for logging; you don't need to care about them, but you can use them, wenn calling from SSIS or in your workflow to log the context of the procedure call
  @execution_instance_guid UNIQUEIDENTIFIER = NULL --SSIS system variable ExecutionInstanceGUID could be used, any other unique guid is also fine. If NULL, then NEWID() is used to create one
, @ssis_execution_id BIGINT = NULL --only SSIS system variable ServerExecutionID should be used, or any other consistent number system, do not mix different number systems
, @sub_execution_id INT = NULL --in case you log some sub_executions, for example in SSIS loops or sub packages
, @parent_execution_log_id BIGINT = NULL --in case a sup procedure is called, the @current_execution_log_id of the parent procedure should be propagated here. It allowes call stack analyzing

AS
BEGIN
DECLARE
 --
   @current_execution_log_id BIGINT --this variable should be filled only once per procedure call, it contains the first logging call for the step 'start'.
 , @current_execution_guid UNIQUEIDENTIFIER = NEWID() --a unique guid for any procedure call. It should be propagated to sub procedures using "@parent_execution_log_id = @current_execution_log_id"
 , @source_object NVARCHAR(261) = NULL --use it like '[schema].[object]', this allows data flow vizualizatiuon (include square brackets)
 , @target_object NVARCHAR(261) = NULL --use it like '[schema].[object]', this allows data flow vizualizatiuon (include square brackets)
 , @proc_id INT = @@procid
 , @proc_schema_name NVARCHAR(128) = OBJECT_SCHEMA_NAME(@@procid) --schema ande name of the current procedure should be automatically logged
 , @proc_name NVARCHAR(128) = OBJECT_NAME(@@procid)               --schema ande name of the current procedure should be automatically logged
 , @event_info NVARCHAR(MAX)
 , @step_id INT = 0
 , @step_name NVARCHAR(1000) = NULL
 , @rows INT

--[event_info] get's only the information about the "outer" calling process
--wenn the procedure calls sub procedures, the [event_info] will not change
SET @event_info = (
  SELECT TOP 1 [event_info]
  FROM sys.dm_exec_input_buffer(@@spid, CURRENT_REQUEST_ID())
  ORDER BY [event_info]
  )

IF @execution_instance_guid IS NULL
 SET @execution_instance_guid = NEWID();
--
--SET @rows = @@ROWCOUNT;
SET @step_id = @step_id + 1
SET @step_name = 'start'
SET @source_object = NULL
SET @target_object = NULL

EXEC logs.usp_ExecutionLog_insert
 --these parameters should be the same for all logging execution
   @execution_instance_guid = @execution_instance_guid
 , @ssis_execution_id = @ssis_execution_id
 , @sub_execution_id = @sub_execution_id
 , @parent_execution_log_id = @parent_execution_log_id
 , @current_execution_guid = @current_execution_guid
 , @proc_id = @proc_id
 , @proc_schema_name = @proc_schema_name
 , @proc_name = @proc_name
 , @event_info = @event_info
 --the following parameters are individual for each call
 , @step_id = @step_id --@step_id should be incremented before each call
 , @step_name = @step_name --assign individual step names for each call
 --only the "start" step should return the log id into @current_execution_log_id
 --all other calls should not overwrite @current_execution_log_id
 , @execution_log_id = @current_execution_log_id OUTPUT
----you can log the content of your own parameters, do this only in the start-step
----data type is sql_variant
 , @parameter_01 = @isExecuteCommand
--
PRINT '[docs].[usp_AntoraExport]'
--keep the code between logging parameters and "START" unchanged!
--
----START
--
----- start here with your own code
--
/*{"ReportUspStep":[{"Number":210,"Name":"declare variables","has_logging":0,"is_condition":0,"is_inactive":0,"is_SubProcedure":0}]}*/
PRINT CONCAT('usp_id;Number;Parent_Number: ',27,';',210,';',NULL);

DECLARE @command NVARCHAR(4000)
DECLARE @cultures_name NVARCHAR(10)
Declare @AntoraModule Varchar(50)



/*{"ReportUspStep":[{"Number":220,"Name":"Truncate Table [docs].[command]","has_logging":0,"is_condition":0,"is_inactive":0,"is_SubProcedure":0}]}*/
PRINT CONCAT('usp_id;Number;Parent_Number: ',27,';',220,';',NULL);

Truncate Table [docs].[command]


/*{"ReportUspStep":[{"Number":300,"Name":"check Parameter AntoraDeleteFilesInModuleFolders","has_logging":0,"is_condition":1,"is_inactive":0,"is_SubProcedure":0,"log_source_object":"[config].[Parameter]"}]}*/
IF [config].[fs_get_parameter_value]('AntoraDeleteFilesInModuleFolders','') = 1

/*{"ReportUspStep":[{"Number":310,"Parent_Number":300,"Name":"Delete Files but not folder in AntoraModule pages and partials - by cultures_name","has_logging":1,"is_condition":0,"is_inactive":0,"is_SubProcedure":0,"log_flag_InsertUpdateDelete":"I"}]}*/
BEGIN
PRINT CONCAT('usp_id;Number;Parent_Number: ',27,';',310,';',300);

Declare module_cursor Cursor Local Fast_Forward For
Select
    cultures_name
From
    docs.culture
Order By
    cultures_name

Open module_cursor

Fetch Next From module_cursor
Into
    @cultures_name

While @@Fetch_Status = 0
Begin

    /*
FORFILES /p "D:\Repos\gitlab\DataHandwerk\dhw-antora-sqldb\docs\modules\sqldb\partials" /s /m *.* /c "cmd /c if @isdir==FALSE del @path"
*/
    Set @command
        = N'FORFILES /p "'
          --
          --
          + docs.fs_AntoraModuleFolder ( @cultures_name )
          + '\partials'
          --
          + N'" /s /m *.* /c "cmd /c if @isdir==FALSE del @path"'

    Print @command
    
    INSERT Into [docs].[command]
    (command)
    VALUES(@command)

    ----Execute the BCP command
    --Exec sys.xp_cmdshell @command, no_output

    Set @command
        = N'FORFILES /p "'
          --
          --
          + docs.fs_AntoraModuleFolder ( @cultures_name )
          + '\pages'
          --
          + N'" /s /m *.* /c "cmd /c if @isdir==FALSE del @path"'

    Print @command

    INSERT Into [docs].[command]
    (command)
    VALUES(@command)

    ----Execute the BCP command
    --Exec sys.xp_cmdshell @command, no_output

    Fetch Next From module_cursor
    Into
        @cultures_name
End

Close module_cursor
Deallocate module_cursor

-- Logging START --
SET @rows = @@ROWCOUNT
SET @step_id = @step_id + 1
SET @step_name = 'Delete Files but not folder in AntoraModule pages and partials - by cultures_name'
SET @source_object = NULL
SET @target_object = NULL

EXEC logs.usp_ExecutionLog_insert 
 @execution_instance_guid = @execution_instance_guid
 , @ssis_execution_id = @ssis_execution_id
 , @sub_execution_id = @sub_execution_id
 , @parent_execution_log_id = @parent_execution_log_id
 , @current_execution_guid = @current_execution_guid
 , @proc_id = @proc_id
 , @proc_schema_name = @proc_schema_name
 , @proc_name = @proc_name
 , @event_info = @event_info
 , @step_id = @step_id
 , @step_name = @step_name
 , @source_object = @source_object
 , @target_object = @target_object
 , @inserted = @rows
-- Logging END --

/*{"ReportUspStep":[{"Number":320,"Parent_Number":310,"Name":"Delete Files but not folder in AntoraModule pages and partials - by SSIS AntoraModule","has_logging":1,"is_condition":0,"is_inactive":0,"is_SubProcedure":0,"log_flag_InsertUpdateDelete":"I"}]}*/
PRINT CONCAT('usp_id;Number;Parent_Number: ',27,';',320,';',310);

Declare module_cursor Cursor Local Fast_Forward For
Select
    AntoraModule
From
    ssis.Project
Order By
    AntoraModule

Open module_cursor

Fetch Next From module_cursor
Into
    @AntoraModule

While @@Fetch_Status = 0
Begin

    /*
FORFILES /p "D:\Repos\gitlab\DataHandwerk\dhw-antora-sqldb\docs\modules\sqldb\partials" /s /m *.* /c "cmd /c if @isdir==FALSE del @path"
*/
    Set @command = N'FORFILES /p "'
                   --
                   --
                   + config.fs_get_parameter_value ( 'AntoraComponentFolder', '' ) + '\modules\' + @AntoraModule
                   --
                   + '\partials'
                   --
                   + N'" /s /m *.* /c "cmd /c if @isdir==FALSE del @path"'

    Print @command

    INSERT Into [docs].[command]
    (command)
    VALUES(@command)

    ----Execute the BCP command
    --Exec sys.xp_cmdshell @command, no_output

    Set @command = N'FORFILES /p "'
                   --
                   --
                   + config.fs_get_parameter_value ( 'AntoraComponentFolder', '' ) + '\modules\' + @AntoraModule
                   --
                   + '\pages'
                   --
                   + N'" /s /m *.* /c "cmd /c if @isdir==FALSE del @path"'

    Print @command

    INSERT Into [docs].[command]
    (command)
    VALUES(@command)

    ----Execute the BCP command
    --Exec sys.xp_cmdshell @command, no_output

    Fetch Next From module_cursor
    Into
        @AntoraModule
End

Close module_cursor
Deallocate module_cursor

-- Logging START --
SET @rows = @@ROWCOUNT
SET @step_id = @step_id + 1
SET @step_name = 'Delete Files but not folder in AntoraModule pages and partials - by SSIS AntoraModule'
SET @source_object = NULL
SET @target_object = NULL

EXEC logs.usp_ExecutionLog_insert 
 @execution_instance_guid = @execution_instance_guid
 , @ssis_execution_id = @ssis_execution_id
 , @sub_execution_id = @sub_execution_id
 , @parent_execution_log_id = @parent_execution_log_id
 , @current_execution_guid = @current_execution_guid
 , @proc_id = @proc_id
 , @proc_schema_name = @proc_schema_name
 , @proc_name = @proc_name
 , @event_info = @event_info
 , @step_id = @step_id
 , @step_name = @step_name
 , @source_object = @source_object
 , @target_object = @target_object
 , @inserted = @rows
-- Logging END --
END;

/*{"ReportUspStep":[{"Number":400,"Name":"[docs].[usp_PERSIST_RepoObject_OutputFilter_T]","has_logging":1,"is_condition":0,"is_inactive":0,"is_SubProcedure":1}]}*/
EXEC [docs].[usp_PERSIST_RepoObject_OutputFilter_T]
--add your own parameters
--logging parameters
 @execution_instance_guid = @execution_instance_guid
 , @ssis_execution_id = @ssis_execution_id
 , @sub_execution_id = @sub_execution_id
 , @parent_execution_log_id = @current_execution_log_id


/*{"ReportUspStep":[{"Number":440,"Name":"[docs].[usp_AntoraExport_ObjectNavigation]","has_logging":1,"is_condition":0,"is_inactive":0,"is_SubProcedure":1}]}*/
EXEC [docs].[usp_AntoraExport_ObjectNavigation]
--add your own parameters
--logging parameters
 @execution_instance_guid = @execution_instance_guid
 , @ssis_execution_id = @ssis_execution_id
 , @sub_execution_id = @sub_execution_id
 , @parent_execution_log_id = @current_execution_log_id


/*{"ReportUspStep":[{"Number":500,"Name":"[docs].[usp_AntoraExport_ObjectPage]","has_logging":1,"is_condition":0,"is_inactive":0,"is_SubProcedure":1}]}*/
EXEC [docs].[usp_AntoraExport_ObjectPage]
--add your own parameters
--logging parameters
 @execution_instance_guid = @execution_instance_guid
 , @ssis_execution_id = @ssis_execution_id
 , @sub_execution_id = @sub_execution_id
 , @parent_execution_log_id = @current_execution_log_id


/*{"ReportUspStep":[{"Number":600,"Name":"[docs].[usp_AntoraExport_ObjectPageTemplate]","has_logging":1,"is_condition":0,"is_inactive":0,"is_SubProcedure":1}]}*/
EXEC [docs].[usp_AntoraExport_ObjectPageTemplate]
--add your own parameters
--logging parameters
 @execution_instance_guid = @execution_instance_guid
 , @ssis_execution_id = @ssis_execution_id
 , @sub_execution_id = @sub_execution_id
 , @parent_execution_log_id = @current_execution_log_id


/*{"ReportUspStep":[{"Number":800,"Name":"[docs].[usp_AntoraExport_ObjectPuml]","has_logging":1,"is_condition":0,"is_inactive":0,"is_SubProcedure":1}]}*/
EXEC [docs].[usp_AntoraExport_ObjectPuml]
--add your own parameters
--logging parameters
 @execution_instance_guid = @execution_instance_guid
 , @ssis_execution_id = @ssis_execution_id
 , @sub_execution_id = @sub_execution_id
 , @parent_execution_log_id = @current_execution_log_id


/*{"ReportUspStep":[{"Number":850,"Name":"[docs].[usp_AntoraExport_ObjectPartialsContent]","has_logging":1,"is_condition":0,"is_inactive":0,"is_SubProcedure":1}]}*/
EXEC [docs].[usp_AntoraExport_ObjectPartialsContent]
--add your own parameters
--logging parameters
 @execution_instance_guid = @execution_instance_guid
 , @ssis_execution_id = @ssis_execution_id
 , @sub_execution_id = @sub_execution_id
 , @parent_execution_log_id = @current_execution_log_id


/*{"ReportUspStep":[{"Number":910,"Name":"[docs].[usp_AntoraExport_Page_IndexSemanticGroup]","has_logging":1,"is_condition":0,"is_inactive":0,"is_SubProcedure":1}]}*/
EXEC [docs].[usp_AntoraExport_Page_IndexSemanticGroup]
--add your own parameters
--logging parameters
 @execution_instance_guid = @execution_instance_guid
 , @ssis_execution_id = @ssis_execution_id
 , @sub_execution_id = @sub_execution_id
 , @parent_execution_log_id = @current_execution_log_id


/*{"ReportUspStep":[{"Number":920,"Name":"[docs].[usp_AntoraExport_ObjectRefCyclic]","has_logging":1,"is_condition":0,"is_inactive":0,"is_SubProcedure":1}]}*/
EXEC [docs].[usp_AntoraExport_ObjectRefCyclic]
--add your own parameters
--logging parameters
 @execution_instance_guid = @execution_instance_guid
 , @ssis_execution_id = @ssis_execution_id
 , @sub_execution_id = @sub_execution_id
 , @parent_execution_log_id = @current_execution_log_id


/*{"ReportUspStep":[{"Number":1440,"Name":"[docs].[usp_AntoraExport_SsisNavigation]","has_logging":1,"is_condition":0,"is_inactive":0,"is_SubProcedure":1}]}*/
EXEC [docs].[usp_AntoraExport_SsisNavigation]
--add your own parameters
--logging parameters
 @execution_instance_guid = @execution_instance_guid
 , @ssis_execution_id = @ssis_execution_id
 , @sub_execution_id = @sub_execution_id
 , @parent_execution_log_id = @current_execution_log_id


/*{"ReportUspStep":[{"Number":1500,"Name":"[docs].[usp_AntoraExport_SsisPage]","has_logging":1,"is_condition":0,"is_inactive":0,"is_SubProcedure":1}]}*/
EXEC [docs].[usp_AntoraExport_SsisPage]
--add your own parameters
--logging parameters
 @execution_instance_guid = @execution_instance_guid
 , @ssis_execution_id = @ssis_execution_id
 , @sub_execution_id = @sub_execution_id
 , @parent_execution_log_id = @current_execution_log_id


/*{"ReportUspStep":[{"Number":1600,"Name":"[docs].[usp_AntoraExport_SsisPageTemplate]","has_logging":1,"is_condition":0,"is_inactive":0,"is_SubProcedure":1}]}*/
EXEC [docs].[usp_AntoraExport_SsisPageTemplate]
--add your own parameters
--logging parameters
 @execution_instance_guid = @execution_instance_guid
 , @ssis_execution_id = @ssis_execution_id
 , @sub_execution_id = @sub_execution_id
 , @parent_execution_log_id = @current_execution_log_id


/*{"ReportUspStep":[{"Number":1800,"Name":"[docs].[usp_AntoraExport_SsisPuml]","has_logging":1,"is_condition":0,"is_inactive":0,"is_SubProcedure":1}]}*/
EXEC [docs].[usp_AntoraExport_SsisPuml]
--add your own parameters
--logging parameters
 @execution_instance_guid = @execution_instance_guid
 , @ssis_execution_id = @ssis_execution_id
 , @sub_execution_id = @sub_execution_id
 , @parent_execution_log_id = @current_execution_log_id


/*{"ReportUspStep":[{"Number":1850,"Name":"[docs].[usp_AntoraExport_SsisPartialsContent]","has_logging":1,"is_condition":0,"is_inactive":0,"is_SubProcedure":1}]}*/
EXEC [docs].[usp_AntoraExport_SsisPartialsContent]
--add your own parameters
--logging parameters
 @execution_instance_guid = @execution_instance_guid
 , @ssis_execution_id = @ssis_execution_id
 , @sub_execution_id = @sub_execution_id
 , @parent_execution_log_id = @current_execution_log_id


/*{"ReportUspStep":[{"Number":2000,"Name":"INSERT Into [docs].[command] empty line","has_logging":1,"is_condition":0,"is_inactive":0,"is_SubProcedure":0,"log_flag_InsertUpdateDelete":"I"}]}*/
PRINT CONCAT('usp_id;Number;Parent_Number: ',27,';',2000,';',NULL);

    Set @command
        = N''
    INSERT Into [docs].[command]
    (command)
    VALUES(@command)


-- Logging START --
SET @rows = @@ROWCOUNT
SET @step_id = @step_id + 1
SET @step_name = 'INSERT Into [docs].[command] empty line'
SET @source_object = NULL
SET @target_object = NULL

EXEC logs.usp_ExecutionLog_insert 
 @execution_instance_guid = @execution_instance_guid
 , @ssis_execution_id = @ssis_execution_id
 , @sub_execution_id = @sub_execution_id
 , @parent_execution_log_id = @parent_execution_log_id
 , @current_execution_guid = @current_execution_guid
 , @proc_id = @proc_id
 , @proc_schema_name = @proc_schema_name
 , @proc_name = @proc_name
 , @event_info = @event_info
 , @step_id = @step_id
 , @step_name = @step_name
 , @source_object = @source_object
 , @target_object = @target_object
 , @inserted = @rows
-- Logging END --

/*{"ReportUspStep":[{"Number":3000,"Name":"check Parameter isExecuteCommand","has_logging":0,"is_condition":1,"is_inactive":0,"is_SubProcedure":0,"log_source_object":"[config].[Parameter]"}]}*/
IF @isExecuteCommand = 1

/*{"ReportUspStep":[{"Number":3010,"Parent_Number":3000,"Name":"Execute commands, collected in [docs].[command], using \"Exec sys.xp_cmdshell\"","has_logging":1,"is_condition":0,"is_inactive":0,"is_SubProcedure":0,"log_flag_InsertUpdateDelete":"I"}]}*/
BEGIN
PRINT CONCAT('usp_id;Number;Parent_Number: ',27,';',3010,';',3000);

Declare command_cursor Cursor Local Fast_Forward For
Select
    command
From
    docs.command
Order By
    id

Open command_cursor

Fetch Next From command_cursor
Into
    @command

While @@Fetch_Status = 0
Begin

    Print @command

    --Execute the BCP command
    Exec sys.xp_cmdshell @command, no_output

    Fetch Next From command_cursor
    Into
        @command
End

Close command_cursor
Deallocate command_cursor

-- Logging START --
SET @rows = @@ROWCOUNT
SET @step_id = @step_id + 1
SET @step_name = 'Execute commands, collected in [docs].[command], using "Exec sys.xp_cmdshell"'
SET @source_object = NULL
SET @target_object = NULL

EXEC logs.usp_ExecutionLog_insert 
 @execution_instance_guid = @execution_instance_guid
 , @ssis_execution_id = @ssis_execution_id
 , @sub_execution_id = @sub_execution_id
 , @parent_execution_log_id = @parent_execution_log_id
 , @current_execution_guid = @current_execution_guid
 , @proc_id = @proc_id
 , @proc_schema_name = @proc_schema_name
 , @proc_name = @proc_name
 , @event_info = @event_info
 , @step_id = @step_id
 , @step_name = @step_name
 , @source_object = @source_object
 , @target_object = @target_object
 , @inserted = @rows
-- Logging END --
END;

--
--finish your own code here
--keep the code between "END" and the end of the procedure unchanged!
--
--END
--
--SET @rows = @@ROWCOUNT
SET @step_id = @step_id + 1
SET @step_name = 'end'
SET @source_object = NULL
SET @target_object = NULL

EXEC logs.usp_ExecutionLog_insert
   @execution_instance_guid = @execution_instance_guid
 , @ssis_execution_id = @ssis_execution_id
 , @sub_execution_id = @sub_execution_id
 , @parent_execution_log_id = @parent_execution_log_id
 , @current_execution_guid = @current_execution_guid
 , @proc_id = @proc_id
 , @proc_schema_name = @proc_schema_name
 , @proc_name = @proc_name
 , @event_info = @event_info
 , @step_id = @step_id
 , @step_name = @step_name
 , @source_object = @source_object
 , @target_object = @target_object

END


----
=======
// end::sql_modules_definition[]


