// tag::HeaderFullDisplayName[]
= docs.Unit_3 - V
// end::HeaderFullDisplayName[]

== existing_properties

// tag::existing_properties[]

:ExistsProperty--antorareferencedlist:
:ExistsProperty--antorareferencinglist:
:ExistsProperty--is_repo_managed:
:ExistsProperty--is_ssas:
:ExistsProperty--referencedobjectlist:
:ExistsProperty--sql_modules_definition:
:ExistsProperty--FK:
:ExistsProperty--Columns:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
E5F27B65-9D0F-EC11-8518-A81E8446D5B0
// end::RepoObject_guid[]

== RepoObject_FullDisplayName2

// tag::RepoObject_FullDisplayName2[]
docs.Unit_3
// end::RepoObject_FullDisplayName2[]

== SysObject_type

// tag::SysObject_type[]
V 
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
view
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
1155535200
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2021-11-16 11:50:23
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]
[discrete]
== _


[#column-antoracomponent]
=== AntoraComponent

[cols="d,8a,m,m,m"]
|===
|
|AntoraComponent
|nvarchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:docs.unit_2.adoc#column-antoracomponent[+docs.Unit_2.AntoraComponent+]
--

.Referencing Columns
--
* xref:dmdocs.unit.adoc#column-antoracomponent[+dmdocs.unit.AntoraComponent+]
--


[#column-antoramodule]
=== AntoraModule

[cols="d,8a,m,m,m"]
|===
|
|AntoraModule
|nvarchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:docs.unit_2.adoc#column-antoramodule[+docs.Unit_2.AntoraModule+]
--

.Referencing Columns
--
* xref:dmdocs.unit.adoc#column-antoramodule[+dmdocs.unit.AntoraModule+]
--


[#column-antorapage]
=== AntoraPage

[cols="d,8a,m,m,m"]
|===
|
|AntoraPage
|nvarchar(4000)
|NULL
|
|===

.Referenced Columns
--
* xref:docs.unit_2.adoc#column-antorapage[+docs.Unit_2.AntoraPage+]
--

.Referencing Columns
--
* xref:dmdocs.unit.adoc#column-antorapage[+dmdocs.unit.AntoraPage+]
--


[#column-antorasectionid]
=== AntoraSectionId

[cols="d,8a,m,m,m"]
|===
|
|AntoraSectionId
|nvarchar(4000)
|NULL
|
|===

.Referenced Columns
--
* xref:docs.unit_2.adoc#column-antorasectionid[+docs.Unit_2.AntoraSectionId+]
--

.Referencing Columns
--
* xref:dmdocs.unit.adoc#column-antorasectionid[+dmdocs.unit.AntoraSectionId+]
--


[#column-antorasiteurl]
=== AntoraSiteUrl

[cols="d,8a,m,m,m"]
|===
|
|AntoraSiteUrl
|nvarchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:docs.unit_2.adoc#column-antorasiteurl[+docs.Unit_2.AntoraSiteUrl+]
--

.Referencing Columns
--
* xref:dmdocs.unit.adoc#column-antorasiteurl[+dmdocs.unit.AntoraSiteUrl+]
--


[#column-antoraversion]
=== AntoraVersion

[cols="d,8a,m,m,m"]
|===
|
|AntoraVersion
|nvarchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:docs.unit_2.adoc#column-antoraversion[+docs.Unit_2.AntoraVersion+]
--

.Referencing Columns
--
* xref:dmdocs.unit.adoc#column-antoraversion[+dmdocs.unit.AntoraVersion+]
--


[#column-objectunderlinefullname2]
=== Object_fullname2

[cols="d,8a,m,m,m"]
|===
|
|Object_fullname2
|nvarchar(257)
|NULL
|
|===

.Referenced Columns
--
* xref:docs.unit_2.adoc#column-objectunderlinefullname2[+docs.Unit_2.Object_fullname2+]
--

.Referencing Columns
--
* xref:dmdocs.unit.adoc#column-objectunderlinefullname2[+dmdocs.unit.Object_fullname2+]
--


[#column-objectunderlinetype]
=== Object_Type

[cols="d,8a,m,m,m"]
|===
|
|Object_Type
|varchar(2)
|NULL
|
|===

.Referenced Columns
--
* xref:docs.unit_2.adoc#column-objectunderlinetype[+docs.Unit_2.Object_Type+]
--

.Referencing Columns
--
* xref:dmdocs.unit.adoc#column-objectunderlinetype[+dmdocs.unit.Object_Type+]
--


[#column-unitunderlinecolummname]
=== Unit_ColummName

[cols="d,8a,m,m,m"]
|===
|
|Unit_ColummName
|nvarchar(128)
|NULL
|
|===

.Referenced Columns
--
* xref:docs.unit_2.adoc#column-unitunderlinecolummname[+docs.Unit_2.Unit_ColummName+]
--

.Referencing Columns
--
* xref:dmdocs.unit.adoc#column-unitunderlinecolummname[+dmdocs.unit.Unit_ColummName+]
--


[#column-unitunderlinedescription]
=== Unit_Description

[cols="d,8a,m,m,m"]
|===
|
|Unit_Description
|nvarchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:docs.unit_2.adoc#column-unitunderlinedescription[+docs.Unit_2.Unit_Description+]
--

.Referencing Columns
--
* xref:dmdocs.unit.adoc#column-unitunderlinedescription[+dmdocs.unit.Unit_Description+]
--


[#column-unitunderlinedisplayfolder]
=== Unit_DisplayFolder

[cols="d,8a,m,m,m"]
|===
|
|Unit_DisplayFolder
|nvarchar(500)
|NULL
|
|===

.Referenced Columns
--
* xref:docs.unit_2.adoc#column-unitunderlinedisplayfolder[+docs.Unit_2.Unit_DisplayFolder+]
--

.Referencing Columns
--
* xref:dmdocs.unit.adoc#column-unitunderlinedisplayfolder[+dmdocs.unit.Unit_DisplayFolder+]
--


[#column-unitunderlineexpression]
=== Unit_Expression

[cols="d,8a,m,m,m"]
|===
|
|Unit_Expression
|nvarchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:docs.unit_2.adoc#column-unitunderlineexpression[+docs.Unit_2.Unit_Expression+]
--

.Referencing Columns
--
* xref:dmdocs.unit.adoc#column-unitunderlineexpression[+dmdocs.unit.Unit_Expression+]
--


[#column-unitunderlineformatstring]
=== Unit_FormatString

[cols="d,8a,m,m,m"]
|===
|
|Unit_FormatString
|nvarchar(500)
|NULL
|
|===

.Referenced Columns
--
* xref:docs.unit_2.adoc#column-unitunderlineformatstring[+docs.Unit_2.Unit_FormatString+]
--

.Referencing Columns
--
* xref:dmdocs.unit.adoc#column-unitunderlineformatstring[+dmdocs.unit.Unit_FormatString+]
--


[#column-unitunderlinefullname2]
=== Unit_fullname2

[cols="d,8a,m,m,m"]
|===
|
|Unit_fullname2
|nvarchar(638)
|NOT NULL
|
|===

.Referenced Columns
--
* xref:docs.unit_2.adoc#column-unitunderlinefullname2[+docs.Unit_2.Unit_fullname2+]
--

.Referencing Columns
--
* xref:dmdocs.unit.adoc#column-unitunderlinefullname2[+dmdocs.unit.Unit_fullname2+]
--


[#column-unitunderlineguid]
=== Unit_guid

[cols="d,8a,m,m,m"]
|===
|
|Unit_guid
|uniqueidentifier
|NOT NULL
|
|===

.Referenced Columns
--
* xref:docs.unit_2.adoc#column-unitunderlineguid[+docs.Unit_2.Unit_guid+]
--

.Referencing Columns
--
* xref:dmdocs.unit.adoc#column-unitunderlineguid[+dmdocs.unit.Unit_guid+]
--


[#column-unitunderlineishidden]
=== Unit_isHidden

[cols="d,8a,m,m,m"]
|===
|
|Unit_isHidden
|bit
|NULL
|
|===

.Referenced Columns
--
* xref:docs.unit_2.adoc#column-unitunderlineishidden[+docs.Unit_2.Unit_isHidden+]
--

.Referencing Columns
--
* xref:dmdocs.unit.adoc#column-unitunderlineishidden[+dmdocs.unit.Unit_isHidden+]
--


[#column-unitunderlineiskey]
=== Unit_IsKey

[cols="d,8a,m,m,m"]
|===
|
|Unit_IsKey
|bit
|NULL
|
|===

.Referenced Columns
--
* xref:docs.unit_2.adoc#column-unitunderlineiskey[+docs.Unit_2.Unit_IsKey+]
--

.Referencing Columns
--
* xref:dmdocs.unit.adoc#column-unitunderlineiskey[+dmdocs.unit.Unit_IsKey+]
--


[#column-unitunderlineisssas]
=== Unit_IsSsas

[cols="d,8a,m,m,m"]
|===
|
|Unit_IsSsas
|bit
|NULL
|
|===

.Referenced Columns
--
* xref:docs.unit_2.adoc#column-unitunderlineisssas[+docs.Unit_2.Unit_IsSsas+]
--

.Referencing Columns
--
* xref:dmdocs.unit.adoc#column-unitunderlineisssas[+dmdocs.unit.Unit_IsSsas+]
--


[#column-unitunderlineisunique]
=== Unit_IsUnique

[cols="d,8a,m,m,m"]
|===
|
|Unit_IsUnique
|bit
|NULL
|
|===

.Referenced Columns
--
* xref:docs.unit_2.adoc#column-unitunderlineisunique[+docs.Unit_2.Unit_IsUnique+]
--

.Referencing Columns
--
* xref:dmdocs.unit.adoc#column-unitunderlineisunique[+dmdocs.unit.Unit_IsUnique+]
--


[#column-unitunderlinemetatype]
=== Unit_Metatype

[cols="d,8a,m,m,m"]
|===
|
|Unit_Metatype
|varchar(7)
|NOT NULL
|
|===

.Referenced Columns
--
* xref:docs.unit_2.adoc#column-unitunderlinemetatype[+docs.Unit_2.Unit_Metatype+]
--

.Referencing Columns
--
* xref:dmdocs.unit.adoc#column-unitunderlinemetatype[+dmdocs.unit.Unit_Metatype+]
--


[#column-unitunderlinename]
=== Unit_Name

[cols="d,8a,m,m,m"]
|===
|
|Unit_Name
|nvarchar(500)
|NOT NULL
|
|===

.Referenced Columns
--
* xref:docs.unit_2.adoc#column-unitunderlinename[+docs.Unit_2.Unit_Name+]
--

.Referencing Columns
--
* xref:dmdocs.unit.adoc#column-unitunderlinename[+dmdocs.unit.Unit_Name+]
--


[#column-unitunderlineobjectname]
=== Unit_ObjectName

[cols="d,8a,m,m,m"]
|===
|
|Unit_ObjectName
|nvarchar(128)
|NULL
|
|===

.Referenced Columns
--
* xref:docs.unit_2.adoc#column-unitunderlineobjectname[+docs.Unit_2.Unit_ObjectName+]
--

.Referencing Columns
--
* xref:dmdocs.unit.adoc#column-unitunderlineobjectname[+dmdocs.unit.Unit_ObjectName+]
--


[#column-unitunderlineschema]
=== Unit_Schema

[cols="d,8a,m,m,m"]
|===
|
|Unit_Schema
|nvarchar(128)
|NOT NULL
|
|===

.Referenced Columns
--
* xref:docs.unit_2.adoc#column-unitunderlineschema[+docs.Unit_2.Unit_Schema+]
--

.Referencing Columns
--
* xref:dmdocs.unit.adoc#column-unitunderlineschema[+dmdocs.unit.Unit_Schema+]
--


[#column-unitunderlinesummarizeby]
=== Unit_SummarizeBy

[cols="d,8a,m,m,m"]
|===
|
|Unit_SummarizeBy
|nvarchar(500)
|NULL
|
|===

.Referenced Columns
--
* xref:docs.unit_2.adoc#column-unitunderlinesummarizeby[+docs.Unit_2.Unit_SummarizeBy+]
--

.Referencing Columns
--
* xref:dmdocs.unit.adoc#column-unitunderlinesummarizeby[+dmdocs.unit.Unit_SummarizeBy+]
--


[#column-unitunderlinetypename]
=== Unit_TypeName

[cols="d,8a,m,m,m"]
|===
|
|Unit_TypeName
|nvarchar(128)
|NULL
|
|===

.Referenced Columns
--
* xref:docs.unit_2.adoc#column-unitunderlinetypename[+docs.Unit_2.Unit_TypeName+]
--

.Referencing Columns
--
* xref:dmdocs.unit.adoc#column-unitunderlinetypename[+dmdocs.unit.Unit_TypeName+]
--


[#column-unitunderlineurl]
=== Unit_Url

[cols="d,8a,m,m,m"]
|===
|
|Unit_Url
|nvarchar(max)
|NOT NULL
|
|===

.Referencing Columns
--
* xref:dmdocs.unit.adoc#column-unitunderlineurl[+dmdocs.unit.Unit_Url+]
--


// end::AntoraColumnDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]


























// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]
|
|<<column-antoracomponent>>
|nvarchar(max)
|NULL
|

|
|<<column-antoramodule>>
|nvarchar(max)
|NULL
|

|
|<<column-antorapage>>
|nvarchar(4000)
|NULL
|

|
|<<column-antorasectionid>>
|nvarchar(4000)
|NULL
|

|
|<<column-antorasiteurl>>
|nvarchar(max)
|NULL
|

|
|<<column-antoraversion>>
|nvarchar(max)
|NULL
|

|
|<<column-objectunderlinefullname2>>
|nvarchar(257)
|NULL
|

|
|<<column-objectunderlinetype>>
|varchar(2)
|NULL
|

|
|<<column-unitunderlinecolummname>>
|nvarchar(128)
|NULL
|

|
|<<column-unitunderlinedescription>>
|nvarchar(max)
|NULL
|

|
|<<column-unitunderlinedisplayfolder>>
|nvarchar(500)
|NULL
|

|
|<<column-unitunderlineexpression>>
|nvarchar(max)
|NULL
|

|
|<<column-unitunderlineformatstring>>
|nvarchar(500)
|NULL
|

|
|<<column-unitunderlinefullname2>>
|nvarchar(638)
|NOT NULL
|

|
|<<column-unitunderlineguid>>
|uniqueidentifier
|NOT NULL
|

|
|<<column-unitunderlineishidden>>
|bit
|NULL
|

|
|<<column-unitunderlineiskey>>
|bit
|NULL
|

|
|<<column-unitunderlineisssas>>
|bit
|NULL
|

|
|<<column-unitunderlineisunique>>
|bit
|NULL
|

|
|<<column-unitunderlinemetatype>>
|varchar(7)
|NOT NULL
|

|
|<<column-unitunderlinename>>
|nvarchar(500)
|NOT NULL
|

|
|<<column-unitunderlineobjectname>>
|nvarchar(128)
|NULL
|

|
|<<column-unitunderlineschema>>
|nvarchar(128)
|NOT NULL
|

|
|<<column-unitunderlinesummarizeby>>
|nvarchar(500)
|NULL
|

|
|<<column-unitunderlinetypename>>
|nvarchar(128)
|NULL
|

|
|<<column-unitunderlineurl>>
|nvarchar(max)
|NOT NULL
|

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

// end::AntoraIndexList[]

== AntoraMeasureDetails

// tag::AntoraMeasureDetails[]

// end::AntoraMeasureDetails[]

== AntoraMeasureDescriptions



== AntoraParameterList

// tag::AntoraParameterList[]

// end::AntoraParameterList[]

== AntoraXrefCulturesList

// tag::AntoraXrefCulturesList[]
* xref:dhw:sqldb:docs.unit_3.adoc[] - 
// end::AntoraXrefCulturesList[]

== cultures_count

// tag::cultures_count[]
1
// end::cultures_count[]

== Other tags

source: property.RepoObjectProperty_cross As rop_cross


=== additional_reference_csv

// tag::additional_reference_csv[]

// end::additional_reference_csv[]


=== AdocUspSteps

// tag::adocuspsteps[]

// end::adocuspsteps[]


=== AntoraReferencedList

// tag::antorareferencedlist[]
* xref:dhw:sqldb:docs.unit_2.adoc[]
// end::antorareferencedlist[]


=== AntoraReferencingList

// tag::antorareferencinglist[]
* xref:dhw:sqldb:dmdocs.unit.adoc[]
// end::antorareferencinglist[]


=== Description

// tag::description[]

// end::description[]


=== exampleUsage

// tag::exampleusage[]

// end::exampleusage[]


=== exampleUsage_2

// tag::exampleusage_2[]

// end::exampleusage_2[]


=== exampleUsage_3

// tag::exampleusage_3[]

// end::exampleusage_3[]


=== exampleUsage_4

// tag::exampleusage_4[]

// end::exampleusage_4[]


=== exampleUsage_5

// tag::exampleusage_5[]

// end::exampleusage_5[]


=== exampleWrong_Usage

// tag::examplewrong_usage[]

// end::examplewrong_usage[]


=== has_execution_plan_issue

// tag::has_execution_plan_issue[]

// end::has_execution_plan_issue[]


=== has_get_referenced_issue

// tag::has_get_referenced_issue[]

// end::has_get_referenced_issue[]


=== has_history

// tag::has_history[]

// end::has_history[]


=== has_history_columns

// tag::has_history_columns[]

// end::has_history_columns[]


=== InheritanceType

// tag::inheritancetype[]

// end::inheritancetype[]


=== is_persistence

// tag::is_persistence[]

// end::is_persistence[]


=== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]

// end::is_persistence_check_duplicate_per_pk[]


=== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]

// end::is_persistence_check_for_empty_source[]


=== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]

// end::is_persistence_delete_changed[]


=== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]

// end::is_persistence_delete_missing[]


=== is_persistence_insert

// tag::is_persistence_insert[]

// end::is_persistence_insert[]


=== is_persistence_truncate

// tag::is_persistence_truncate[]

// end::is_persistence_truncate[]


=== is_persistence_update_changed

// tag::is_persistence_update_changed[]

// end::is_persistence_update_changed[]


=== is_repo_managed

// tag::is_repo_managed[]
0
// end::is_repo_managed[]


=== is_ssas

// tag::is_ssas[]
0
// end::is_ssas[]


=== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


=== MS_Description

// tag::ms_description[]

// end::ms_description[]


=== persistence_source_RepoObject_fullname

// tag::persistence_source_repoobject_fullname[]

// end::persistence_source_repoobject_fullname[]


=== persistence_source_RepoObject_fullname2

// tag::persistence_source_repoobject_fullname2[]

// end::persistence_source_repoobject_fullname2[]


=== persistence_source_RepoObject_guid

// tag::persistence_source_repoobject_guid[]

// end::persistence_source_repoobject_guid[]


=== persistence_source_RepoObject_xref

// tag::persistence_source_repoobject_xref[]

// end::persistence_source_repoobject_xref[]


=== pk_index_guid

// tag::pk_index_guid[]

// end::pk_index_guid[]


=== pk_IndexPatternColumnDatatype

// tag::pk_indexpatterncolumndatatype[]

// end::pk_indexpatterncolumndatatype[]


=== pk_IndexPatternColumnName

// tag::pk_indexpatterncolumnname[]

// end::pk_indexpatterncolumnname[]


=== pk_IndexSemanticGroup

// tag::pk_indexsemanticgroup[]

// end::pk_indexsemanticgroup[]


=== ReferencedObjectList

// tag::referencedobjectlist[]
* [docs].[Unit_2]
// end::referencedobjectlist[]


=== usp_persistence_RepoObject_guid

// tag::usp_persistence_repoobject_guid[]

// end::usp_persistence_repoobject_guid[]


=== UspExamples

// tag::uspexamples[]

// end::uspexamples[]


=== uspgenerator_usp_id

// tag::uspgenerator_usp_id[]

// end::uspgenerator_usp_id[]


=== UspParameters

// tag::uspparameters[]

// end::uspparameters[]

== Boolean Attributes

source: property.RepoObjectProperty WHERE property_int = 1

// tag::boolean_attributes[]


// end::boolean_attributes[]

== PlantUML diagrams

=== PlantUML Entity

// tag::puml_entity[]
[plantuml, entity-{docname}, svg, subs=macros]
....
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:docs.unit_3.adoc[]" as docs.Unit_3 << V >> {
  AntoraComponent : (nvarchar(max))
  AntoraModule : (nvarchar(max))
  AntoraPage : (nvarchar(4000))
  AntoraSectionId : (nvarchar(4000))
  AntoraSiteUrl : (nvarchar(max))
  AntoraVersion : (nvarchar(max))
  Object_fullname2 : (nvarchar(257))
  Object_Type : (varchar(2))
  Unit_ColummName : (nvarchar(128))
  Unit_Description : (nvarchar(max))
  Unit_DisplayFolder : (nvarchar(500))
  Unit_Expression : (nvarchar(max))
  Unit_FormatString : (nvarchar(500))
  - Unit_fullname2 : (nvarchar(638))
  - Unit_guid : (uniqueidentifier)
  Unit_isHidden : (bit)
  Unit_IsKey : (bit)
  Unit_IsSsas : (bit)
  Unit_IsUnique : (bit)
  - Unit_Metatype : (varchar(7))
  - Unit_Name : (nvarchar(500))
  Unit_ObjectName : (nvarchar(128))
  - Unit_Schema : (nvarchar(128))
  Unit_SummarizeBy : (nvarchar(500))
  Unit_TypeName : (nvarchar(128))
  - Unit_Url : (nvarchar(max))
  --
}
....

// end::puml_entity[]

=== PlantUML Entity 1 1 FK

// tag::puml_entity_1_1_fk[]
[plantuml, entity_1_1_fk-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:docs.unit_3.adoc[]" as docs.Unit_3 << V >> {

}



footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_fk[]

=== PlantUML 1 1 ObjectRef

// tag::puml_entity_1_1_objectref[]
[plantuml, entity_1_1_objectref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:dmdocs.unit.adoc[]" as dmdocs.unit << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.unit_2.adoc[]" as docs.Unit_2 << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.unit_3.adoc[]" as docs.Unit_3 << V >> {
  --
}

docs.Unit_2 <.. docs.Unit_3
docs.Unit_3 <.. dmdocs.unit

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_objectref[]

=== PlantUML 30 0 ObjectRef

// tag::puml_entity_30_0_objectref[]
[plantuml, entity_30_0_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:config.ftv_dwh_database.adoc[]" as config.ftv_dwh_database << IF >> {
  --
}

entity "puml-link:dhw:sqldb:config.ftv_get_parameter_value.adoc[]" as config.ftv_get_parameter_value << IF >> {
  --
}

entity "puml-link:dhw:sqldb:config.parameter.adoc[]" as config.Parameter << U >> {
  - **Parameter_name** : (varchar(100))
  - **sub_Parameter** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:configt.parameter_default.adoc[]" as configT.Parameter_default << V >> {
  - **Parameter_name** : (varchar(52))
  - **sub_Parameter** : (nvarchar(26))
  --
}

entity "puml-link:dhw:sqldb:configt.spt_values.adoc[]" as configT.spt_values << U >> {
  --
}

entity "puml-link:dhw:sqldb:configt.type.adoc[]" as configT.type << V >> {
  **type** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:docs.culture.adoc[]" as docs.Culture << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.fs_cleanstringforanchorid.adoc[]" as docs.fs_cleanStringForAnchorId << FN >> {
  --
}

entity "puml-link:dhw:sqldb:docs.fs_cleanstringforfilename.adoc[]" as docs.fs_cleanStringForFilename << FN >> {
  --
}

entity "puml-link:dhw:sqldb:docs.fs_cleanstringforpuml.adoc[]" as docs.fs_cleanStringForPuml << FN >> {
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_outputfilter.adoc[]" as docs.RepoObject_OutputFilter << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_outputfilter_t.adoc[]" as docs.RepoObject_OutputFilter_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.unit_1_union.adoc[]" as docs.Unit_1_union << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.unit_2.adoc[]" as docs.Unit_2 << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.unit_3.adoc[]" as docs.Unit_3 << V >> {
  --
}

entity "puml-link:dhw:sqldb:property.external_repoobjectcolumnproperty.adoc[]" as property.external_RepoObjectColumnProperty << U >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.external_repoobjectproperty.adoc[]" as property.external_RepoObjectProperty << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.fs_get_repoobjectcolumnproperty_nvarchar.adoc[]" as property.fs_get_RepoObjectColumnProperty_nvarchar << FN >> {
  --
}

entity "puml-link:dhw:sqldb:property.fs_get_repoobjectproperty_nvarchar.adoc[]" as property.fs_get_RepoObjectProperty_nvarchar << FN >> {
  --
}

entity "puml-link:dhw:sqldb:property.propertyname_repoobject.adoc[]" as property.PropertyName_RepoObject << V >> {
  **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.propertyname_repoobject_t.adoc[]" as property.PropertyName_RepoObject_T << U >> {
  **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectcolumnproperty.adoc[]" as property.RepoObjectColumnProperty << U >> {
  - **RepoObjectColumnProperty_id** : (int)
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectcolumnproperty_external_src.adoc[]" as property.RepoObjectColumnProperty_external_src << V >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectcolumnproperty_external_tgt.adoc[]" as property.RepoObjectColumnProperty_external_tgt << V >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty.adoc[]" as property.RepoObjectProperty << U >> {
  - **RepoObjectProperty_id** : (int)
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty_external_src.adoc[]" as property.RepoObjectProperty_external_src << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty_external_tgt.adoc[]" as property.RepoObjectProperty_external_tgt << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty_selectedpropertyname_split.adoc[]" as property.RepoObjectProperty_SelectedPropertyName_split << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference.adoc[]" as reference.additional_Reference << U >> {
  - **Id** : (int)
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_database.adoc[]" as reference.additional_Reference_database << V >> {
  - **AntoraComponent** : (nvarchar(128))
  - **AntoraModule** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_database_t.adoc[]" as reference.additional_Reference_database_T << U >> {
  - **AntoraComponent** : (nvarchar(128))
  - **AntoraModule** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_from_properties_src.adoc[]" as reference.additional_Reference_from_properties_src << V >> {
  **referenced_AntoraComponent** : (nvarchar(max))
  **referenced_AntoraModule** : (nvarchar(max))
  **referenced_Schema** : (nvarchar(max))
  **referenced_Object** : (nvarchar(max))
  **referenced_Column** : (nvarchar(max))
  **referencing_AntoraComponent** : (nvarchar(max))
  **referencing_AntoraModule** : (nvarchar(max))
  **referencing_Schema** : (nvarchar(max))
  **referencing_Object** : (nvarchar(max))
  **referencing_Column** : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_from_properties_tgt.adoc[]" as reference.additional_Reference_from_properties_tgt << V >> {
  **referenced_AntoraComponent** : (nvarchar(max))
  **referenced_AntoraModule** : (nvarchar(max))
  **referenced_Schema** : (nvarchar(max))
  **referenced_Object** : (nvarchar(max))
  **referenced_Column** : (nvarchar(max))
  **referencing_AntoraComponent** : (nvarchar(max))
  **referencing_AntoraModule** : (nvarchar(max))
  **referencing_Schema** : (nvarchar(max))
  **referencing_Object** : (nvarchar(max))
  **referencing_Column** : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_from_ssas_src.adoc[]" as reference.additional_Reference_from_ssas_src << V >> {
  **referenced_AntoraComponent** : (nvarchar(128))
  **referenced_AntoraModule** : (nvarchar(128))
  **referenced_Schema** : (nvarchar(max))
  **referenced_Object** : (nvarchar(max))
  **referenced_Column** : (nvarchar(500))
  **referencing_AntoraComponent** : (nvarchar(max))
  **referencing_AntoraModule** : (nvarchar(max))
  - **referencing_Schema** : (nvarchar(128))
  - **referencing_Object** : (nvarchar(128))
  **referencing_Column** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_from_ssas_tgt.adoc[]" as reference.additional_Reference_from_ssas_tgt << V >> {
  **referenced_AntoraComponent** : (nvarchar(128))
  **referenced_AntoraModule** : (nvarchar(128))
  **referenced_Schema** : (nvarchar(max))
  **referenced_Object** : (nvarchar(max))
  **referenced_Column** : (nvarchar(500))
  **referencing_AntoraComponent** : (nvarchar(max))
  **referencing_AntoraModule** : (nvarchar(max))
  - **referencing_Schema** : (nvarchar(128))
  - **referencing_Object** : (nvarchar(128))
  **referencing_Column** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_guid.adoc[]" as reference.additional_Reference_guid << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_is_external.adoc[]" as reference.additional_Reference_is_external << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_object.adoc[]" as reference.additional_Reference_Object << V >> {
  - **AntoraComponent** : (nvarchar(128))
  - **AntoraModule** : (nvarchar(128))
  - **SchemaName** : (nvarchar(128))
  - **ObjectName** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_object_t.adoc[]" as reference.additional_Reference_Object_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_objectcolumn.adoc[]" as reference.additional_Reference_ObjectColumn << V >> {
  - **AntoraComponent** : (nvarchar(128))
  - **AntoraModule** : (nvarchar(128))
  - **SchemaName** : (nvarchar(128))
  - **ObjectName** : (nvarchar(128))
  **ColumnName** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_objectcolumn_t.adoc[]" as reference.additional_Reference_ObjectColumn_T << U >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_wo_columns_from_properties_src.adoc[]" as reference.additional_Reference_wo_columns_from_properties_src << V >> {
  **referenced_AntoraComponent** : (nvarchar(max))
  **referenced_AntoraModule** : (nvarchar(max))
  **referenced_Schema** : (nvarchar(max))
  **referenced_Object** : (nvarchar(max))
  **referencing_AntoraComponent** : (nvarchar(max))
  **referencing_AntoraModule** : (nvarchar(max))
  **referencing_Schema** : (nvarchar(max))
  **referencing_Object** : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_wo_columns_from_properties_tgt.adoc[]" as reference.additional_Reference_wo_columns_from_properties_tgt << V >> {
  **referenced_AntoraComponent** : (nvarchar(max))
  **referenced_AntoraModule** : (nvarchar(max))
  **referenced_Schema** : (nvarchar(max))
  **referenced_Object** : (nvarchar(max))
  **referencing_AntoraComponent** : (nvarchar(max))
  **referencing_AntoraModule** : (nvarchar(max))
  **referencing_Schema** : (nvarchar(max))
  **referencing_Object** : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_queryplan.adoc[]" as reference.RepoObject_QueryPlan << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_reference.adoc[]" as reference.RepoObject_reference << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_reference_additional.adoc[]" as reference.RepoObject_reference_additional << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_reference_persistence.adoc[]" as reference.RepoObject_reference_persistence << V >> {
  **referenced_RepoObject_guid** : (uniqueidentifier)
  - **referencing_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_reference_persistence_target_as_source.adoc[]" as reference.RepoObject_reference_persistence_target_as_source << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_reference_sqlexpressiondependencies.adoc[]" as reference.RepoObject_reference_SqlExpressionDependencies << V >> {
  **referenced_RepoObject_guid** : (uniqueidentifier)
  **referencing_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_reference_t.adoc[]" as reference.RepoObject_reference_T << U >> {
  **referenced_RepoObject_guid** : (uniqueidentifier)
  **referencing_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_reference_union.adoc[]" as reference.RepoObject_reference_union << V >> {
  **referenced_RepoObject_guid** : (uniqueidentifier)
  **referencing_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_reference_virtual.adoc[]" as reference.RepoObject_reference_virtual << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_referencedreferencing.adoc[]" as reference.RepoObject_ReferencedReferencing << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectsource_virtual.adoc[]" as reference.RepoObjectSource_virtual << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **Source_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.index_settings.adoc[]" as repo.Index_Settings << U >> {
  - **index_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.measure.adoc[]" as repo.Measure << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject.adoc[]" as repo.RepoObject << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_external_src.adoc[]" as repo.RepoObject_external_src << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_external_tgt.adoc[]" as repo.RepoObject_external_tgt << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_gross.adoc[]" as repo.RepoObject_gross << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_gross_persistence.adoc[]" as repo.RepoObject_gross_persistence << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_persistence.adoc[]" as repo.RepoObject_persistence << U >> {
  - **target_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_ssas_src.adoc[]" as repo.RepoObject_SSAS_src << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_ssas_tgt.adoc[]" as repo.RepoObject_SSAS_tgt << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn.adoc[]" as repo.RepoObjectColumn << U >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn_external_src.adoc[]" as repo.RepoObjectColumn_external_src << V >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn_external_tgt.adoc[]" as repo.RepoObjectColumn_external_tgt << V >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn_gross.adoc[]" as repo.RepoObjectColumn_gross << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn_ssas_src.adoc[]" as repo.RepoObjectColumn_SSAS_src << V >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn_ssas_tgt.adoc[]" as repo.RepoObjectColumn_SSAS_tgt << V >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.reposchema.adoc[]" as repo.RepoSchema << U >> {
  - **RepoSchema_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.reposchema_ssas_src.adoc[]" as repo.RepoSchema_ssas_src << V >> {
  - **RepoSchema_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:repo.reposchema_ssas_tgt.adoc[]" as repo.RepoSchema_ssas_tgt << V >> {
  - **RepoSchema_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.syscolumn_repoobjectcolumn_via_name.adoc[]" as repo.SysColumn_RepoObjectColumn_via_name << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.sysobject_repoobject_via_name.adoc[]" as repo.SysObject_RepoObject_via_name << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo_sys.extendedproperties.adoc[]" as repo_sys.ExtendedProperties << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo_sys.sql_expression_dependencies.adoc[]" as repo_sys.sql_expression_dependencies << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo_sys.syscolumn.adoc[]" as repo_sys.SysColumn << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo_sys.sysobject.adoc[]" as repo_sys.SysObject << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.additional_reference_step1.adoc[]" as ssas.additional_Reference_step1 << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json.adoc[]" as ssas.model_json << U >> {
  - **databasename** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_10.adoc[]" as ssas.model_json_10 << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_20.adoc[]" as ssas.model_json_20 << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_201_descriptions_multiline.adoc[]" as ssas.model_json_201_descriptions_multiline << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_2011_descriptions_stragg.adoc[]" as ssas.model_json_2011_descriptions_StrAgg << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31_tables.adoc[]" as ssas.model_json_31_tables << V >> {
  - **databasename** : (nvarchar(128))
  **tables_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31_tables_t.adoc[]" as ssas.model_json_31_tables_T << U >> {
  - **databasename** : (nvarchar(128))
  **tables_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_311_tables_columns.adoc[]" as ssas.model_json_311_tables_columns << V >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  **tables_columns_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_311_tables_columns_t.adoc[]" as ssas.model_json_311_tables_columns_T << U >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  **tables_columns_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_3111_tables_columns_descriptions_multiline.adoc[]" as ssas.model_json_3111_tables_columns_descriptions_multiline << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31111_tables_columns_descriptions_stragg.adoc[]" as ssas.model_json_31111_tables_columns_descriptions_StrAgg << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_3112_tables_columns_expressions_multiline.adoc[]" as ssas.model_json_3112_tables_columns_expressions_multiline << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31121_tables_columns_expressions_stragg.adoc[]" as ssas.model_json_31121_tables_columns_expressions_StrAgg << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_312_tables_measures.adoc[]" as ssas.model_json_312_tables_measures << V >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  **tables_measures_name** : (nvarchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_312_tables_measures_t.adoc[]" as ssas.model_json_312_tables_measures_T << U >> {
  - **Measure_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_3121_tables_columns_descriptions_multiline.adoc[]" as ssas.model_json_3121_tables_columns_descriptions_multiline << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31211_tables_columns_descriptions_stragg.adoc[]" as ssas.model_json_31211_tables_columns_descriptions_StrAgg << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_3122_tables_measures_expressions_multiline.adoc[]" as ssas.model_json_3122_tables_measures_expressions_multiline << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31221_tables_measures_expressions_stragg.adoc[]" as ssas.model_json_31221_tables_measures_expressions_StrAgg << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_313_tables_partitions.adoc[]" as ssas.model_json_313_tables_partitions << V >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  **tables_partitions_name** : (nvarchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_3131_tables_partitions_source.adoc[]" as ssas.model_json_3131_tables_partitions_source << V >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  **tables_partitions_name** : (nvarchar(500))
  **tables_partitions_source_name** : (nvarchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31311_tables_partitions_source_posfrom.adoc[]" as ssas.model_json_31311_tables_partitions_source_PosFrom << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_313111_tables_partitions_source_stringfrom.adoc[]" as ssas.model_json_313111_tables_partitions_source_StringFrom << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_3131111_tables_partitions_source_posdot.adoc[]" as ssas.model_json_3131111_tables_partitions_source_PosDot << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31311111_tables_partitions_source_part123.adoc[]" as ssas.model_json_31311111_tables_partitions_source_Part123 << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_316_tables_descriptions_multiline.adoc[]" as ssas.model_json_316_tables_descriptions_multiline << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_3161_tables_descriptions_stragg.adoc[]" as ssas.model_json_3161_tables_descriptions_StrAgg << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_33_datasources.adoc[]" as ssas.model_json_33_dataSources << V >> {
  - **databasename** : (nvarchar(128))
  **dataSources_name** : (nvarchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_33_datasources_t.adoc[]" as ssas.model_json_33_dataSources_T << U >> {
  - **databasename** : (nvarchar(128))
  **dataSources_name** : (nvarchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_34_cultures.adoc[]" as ssas.model_json_34_cultures << V >> {
  - **databasename** : (nvarchar(128))
  **cultures_name** : (nvarchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_341_cultures_translations.adoc[]" as ssas.model_json_341_cultures_translations << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_3411_cultures_translations_model.adoc[]" as ssas.model_json_3411_cultures_translations_model << V >> {
  - **databasename** : (nvarchar(128))
  **cultures_name** : (nvarchar(500))
  **cultures_translations_model_name** : (nvarchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_3411_cultures_translations_model_t.adoc[]" as ssas.model_json_3411_cultures_translations_model_T << U >> {
  - **databasename** : (nvarchar(128))
  **cultures_name** : (nvarchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_34111_cultures_translations_model_tables.adoc[]" as ssas.model_json_34111_cultures_translations_model_tables << V >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.columns.adoc[]" as sys_dwh.columns << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.computed_columns.adoc[]" as sys_dwh.computed_columns << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.default_constraints.adoc[]" as sys_dwh.default_constraints << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.extended_properties.adoc[]" as sys_dwh.extended_properties << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.identity_columns.adoc[]" as sys_dwh.identity_columns << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.indexes.adoc[]" as sys_dwh.indexes << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.objects.adoc[]" as sys_dwh.objects << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.parameters.adoc[]" as sys_dwh.parameters << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.schemas.adoc[]" as sys_dwh.schemas << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.sql_expression_dependencies.adoc[]" as sys_dwh.sql_expression_dependencies << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.sql_modules.adoc[]" as sys_dwh.sql_modules << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.tables.adoc[]" as sys_dwh.tables << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.types.adoc[]" as sys_dwh.types << SN >> {
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.generatorusp.adoc[]" as uspgenerator.GeneratorUsp << U >> {
  - **id** : (int)
  --
}

config.ftv_dwh_database <.. repo_sys.sql_expression_dependencies
config.ftv_dwh_database <.. repo_sys.SysColumn
config.ftv_dwh_database <.. repo_sys.ExtendedProperties
config.ftv_get_parameter_value <.. repo.RepoObject_external_src
config.ftv_get_parameter_value <.. docs.Unit_2
config.ftv_get_parameter_value <.. repo.RepoObject_gross
config.ftv_get_parameter_value <.. reference.additional_Reference_is_external
config.ftv_get_parameter_value <.. ssas.additional_Reference_step1
config.Parameter <.. property.PropertyName_RepoObject
config.Parameter <.. config.ftv_dwh_database
config.Parameter <.. config.ftv_get_parameter_value
configT.Parameter_default <.. config.Parameter
configT.spt_values <.. configT.type
configT.type <.. reference.RepoObject_ReferencedReferencing
configT.type <.. repo.RepoObject_gross_persistence
configT.type <.. repo.RepoObject_gross
docs.Culture <.. docs.RepoObject_OutputFilter
docs.fs_cleanStringForAnchorId <.. docs.Unit_2
docs.fs_cleanStringForFilename <.. repo.RepoObject_gross_persistence
docs.fs_cleanStringForFilename <.. reference.RepoObject_ReferencedReferencing
docs.fs_cleanStringForFilename <.. repo.RepoObject_gross
docs.fs_cleanStringForFilename <.. docs.RepoObject_OutputFilter
docs.fs_cleanStringForPuml <.. docs.RepoObject_OutputFilter
docs.RepoObject_OutputFilter <.. docs.RepoObject_OutputFilter_T
docs.RepoObject_OutputFilter_T <.. docs.Unit_1_union
docs.Unit_1_union <.. docs.Unit_2
docs.Unit_2 <.. docs.Unit_3
property.external_RepoObjectColumnProperty <.. property.RepoObjectColumnProperty_external_src
property.external_RepoObjectProperty <.. property.RepoObjectProperty_external_src
property.fs_get_RepoObjectColumnProperty_nvarchar <.. repo.RepoObjectColumn_gross
property.fs_get_RepoObjectProperty_nvarchar <.. repo.RepoObject_gross
property.PropertyName_RepoObject <.. property.PropertyName_RepoObject_T
property.PropertyName_RepoObject_T <.. property.RepoObjectColumnProperty_external_tgt
property.PropertyName_RepoObject_T <.. property.RepoObjectProperty_external_tgt
property.RepoObjectColumnProperty <.. property.fs_get_RepoObjectColumnProperty_nvarchar
property.RepoObjectColumnProperty_external_src <.. property.RepoObjectColumnProperty_external_tgt
property.RepoObjectColumnProperty_external_tgt <.. property.RepoObjectColumnProperty
property.RepoObjectProperty <.. property.fs_get_RepoObjectProperty_nvarchar
property.RepoObjectProperty <.. property.RepoObjectProperty_SelectedPropertyName_split
property.RepoObjectProperty <.. property.PropertyName_RepoObject
property.RepoObjectProperty_external_src <.. property.RepoObjectProperty_external_tgt
property.RepoObjectProperty_external_tgt <.. property.RepoObjectProperty
property.RepoObjectProperty_SelectedPropertyName_split <.. reference.additional_Reference_from_properties_src
property.RepoObjectProperty_SelectedPropertyName_split <.. reference.additional_Reference_wo_columns_from_properties_src
reference.additional_Reference <.. reference.additional_Reference_guid
reference.additional_Reference <.. reference.additional_Reference_is_external
reference.additional_Reference_database <.. reference.additional_Reference_database_T
reference.additional_Reference_database_T <.. repo.RepoObject_gross
reference.additional_Reference_from_properties_src <.. reference.additional_Reference_from_properties_tgt
reference.additional_Reference_from_properties_tgt <.. reference.additional_Reference
reference.additional_Reference_from_ssas_src <.. reference.additional_Reference_from_ssas_tgt
reference.additional_Reference_from_ssas_tgt <.. reference.additional_Reference
reference.additional_Reference_guid <.. reference.RepoObject_reference_additional
reference.additional_Reference_is_external <.. reference.additional_Reference_ObjectColumn
reference.additional_Reference_is_external <.. reference.additional_Reference_database
reference.additional_Reference_is_external <.. reference.additional_Reference_Object
reference.additional_Reference_Object <.. reference.additional_Reference_Object_T
reference.additional_Reference_Object_T <.. repo.RepoObject_external_src
reference.additional_Reference_Object_T <.. repo.RepoObjectColumn_external_src
reference.additional_Reference_ObjectColumn <.. reference.additional_Reference_ObjectColumn_T
reference.additional_Reference_ObjectColumn_T <.. repo.RepoObjectColumn_external_src
reference.additional_Reference_wo_columns_from_properties_src <.. reference.additional_Reference_wo_columns_from_properties_tgt
reference.additional_Reference_wo_columns_from_properties_tgt <.. reference.additional_Reference
reference.RepoObject_QueryPlan <.. repo.RepoObject_gross
reference.RepoObject_reference <.. reference.RepoObject_reference_T
reference.RepoObject_reference_additional <.. reference.RepoObject_reference_union
reference.RepoObject_reference_persistence <.. reference.RepoObject_reference_union
reference.RepoObject_reference_persistence_target_as_source <.. reference.RepoObject_reference_union
reference.RepoObject_reference_persistence_target_as_source <.. reference.RepoObject_reference
reference.RepoObject_reference_SqlExpressionDependencies <.. reference.RepoObject_reference_union
reference.RepoObject_reference_SqlExpressionDependencies <.. reference.RepoObject_reference_persistence_target_as_source
reference.RepoObject_reference_T <.. reference.RepoObject_ReferencedReferencing
reference.RepoObject_reference_union <.. reference.RepoObject_reference
reference.RepoObject_reference_virtual <.. reference.RepoObject_reference_union
reference.RepoObject_ReferencedReferencing <.. repo.RepoObject_gross
reference.RepoObjectSource_virtual <.. reference.RepoObject_reference_virtual
repo.Index_Settings <.. repo.RepoObject_gross
repo.Measure <.. docs.Unit_1_union
repo.RepoObject <.. reference.RepoObject_reference_persistence
repo.RepoObject <.. repo.SysColumn_RepoObjectColumn_via_name
repo.RepoObject <.. repo.SysObject_RepoObject_via_name
repo.RepoObject <.. repo.RepoObject_gross_persistence
repo.RepoObject <.. repo.RepoObjectColumn_external_src
repo.RepoObject <.. property.RepoObjectColumnProperty_external_tgt
repo.RepoObject <.. property.RepoObjectProperty_external_tgt
repo.RepoObject <.. reference.RepoObject_reference_SqlExpressionDependencies
repo.RepoObject <.. repo.RepoObjectColumn_gross
repo.RepoObject <.. repo.RepoObject_gross
repo.RepoObject <.. reference.additional_Reference_guid
repo.RepoObject <.. reference.RepoObject_reference_virtual
repo.RepoObject <.. repo.RepoObject_external_src
repo.RepoObject_external_src <.. repo.RepoObject_external_tgt
repo.RepoObject_external_tgt <.. repo.RepoObject
repo.RepoObject_external_tgt <.. repo.RepoObjectColumn_external_tgt
repo.RepoObject_gross <.. docs.RepoObject_OutputFilter
repo.RepoObject_gross <.. docs.Unit_1_union
repo.RepoObject_gross_persistence <.. reference.RepoObject_reference_persistence_target_as_source
repo.RepoObject_persistence <.. repo.RepoObject_gross_persistence
repo.RepoObject_persistence <.. repo.RepoObject_gross
repo.RepoObject_persistence <.. repo.RepoObjectColumn_gross
repo.RepoObject_persistence <.. reference.RepoObject_reference_persistence
repo.RepoObject_SSAS_src <.. repo.RepoObject_SSAS_tgt
repo.RepoObject_SSAS_tgt <.. repo.RepoObjectColumn_SSAS_tgt
repo.RepoObject_SSAS_tgt <.. repo.RepoObject
repo.RepoObjectColumn <.. property.RepoObjectColumnProperty_external_tgt
repo.RepoObjectColumn <.. reference.additional_Reference_guid
repo.RepoObjectColumn <.. repo.RepoObjectColumn_gross
repo.RepoObjectColumn <.. repo.SysColumn_RepoObjectColumn_via_name
repo.RepoObjectColumn_external_src <.. repo.RepoObjectColumn_external_tgt
repo.RepoObjectColumn_external_tgt <.. repo.RepoObjectColumn
repo.RepoObjectColumn_gross <.. docs.Unit_1_union
repo.RepoObjectColumn_SSAS_src <.. repo.RepoObjectColumn_SSAS_tgt
repo.RepoObjectColumn_SSAS_tgt <.. repo.RepoObjectColumn
repo.RepoSchema <.. repo.Measure
repo.RepoSchema <.. repo.RepoObject_SSAS_src
repo.RepoSchema <.. docs.Unit_1_union
repo.RepoSchema_ssas_src <.. repo.RepoSchema_ssas_tgt
repo.RepoSchema_ssas_tgt <.. repo.RepoSchema
repo.SysColumn_RepoObjectColumn_via_name <.. repo_sys.sql_expression_dependencies
repo.SysObject_RepoObject_via_name <.. repo_sys.sql_expression_dependencies
repo_sys.ExtendedProperties <.. repo_sys.SysObject
repo_sys.ExtendedProperties <.. repo_sys.SysColumn
repo_sys.sql_expression_dependencies <.. reference.RepoObject_reference_SqlExpressionDependencies
repo_sys.SysColumn <.. repo.SysColumn_RepoObjectColumn_via_name
repo_sys.SysObject <.. repo.SysObject_RepoObject_via_name
repo_sys.SysObject <.. repo_sys.SysColumn
ssas.additional_Reference_step1 <.. reference.additional_Reference_from_ssas_src
ssas.model_json <.. ssas.model_json_10
ssas.model_json_10 <.. ssas.model_json_20
ssas.model_json_20 <.. repo.RepoSchema_ssas_src
ssas.model_json_20 <.. ssas.model_json_34_cultures
ssas.model_json_20 <.. ssas.model_json_201_descriptions_multiline
ssas.model_json_20 <.. ssas.model_json_33_dataSources
ssas.model_json_20 <.. ssas.model_json_31_tables
ssas.model_json_201_descriptions_multiline <.. ssas.model_json_2011_descriptions_StrAgg
ssas.model_json_2011_descriptions_StrAgg <.. repo.RepoSchema_ssas_src
ssas.model_json_31_tables <.. ssas.model_json_31_tables_T
ssas.model_json_31_tables_T <.. repo.RepoObject_SSAS_src
ssas.model_json_31_tables_T <.. ssas.model_json_311_tables_columns
ssas.model_json_31_tables_T <.. ssas.model_json_312_tables_measures
ssas.model_json_31_tables_T <.. ssas.model_json_316_tables_descriptions_multiline
ssas.model_json_31_tables_T <.. repo.RepoObject_gross
ssas.model_json_31_tables_T <.. ssas.model_json_313_tables_partitions
ssas.model_json_311_tables_columns <.. ssas.model_json_311_tables_columns_T
ssas.model_json_311_tables_columns_T <.. repo.RepoObjectColumn_gross
ssas.model_json_311_tables_columns_T <.. ssas.model_json_3112_tables_columns_expressions_multiline
ssas.model_json_311_tables_columns_T <.. ssas.model_json_3111_tables_columns_descriptions_multiline
ssas.model_json_311_tables_columns_T <.. repo.RepoObjectColumn_SSAS_src
ssas.model_json_311_tables_columns_T <.. ssas.additional_Reference_step1
ssas.model_json_3111_tables_columns_descriptions_multiline <.. ssas.model_json_31111_tables_columns_descriptions_StrAgg
ssas.model_json_31111_tables_columns_descriptions_StrAgg <.. repo.RepoObjectColumn_gross
ssas.model_json_3112_tables_columns_expressions_multiline <.. ssas.model_json_31121_tables_columns_expressions_StrAgg
ssas.model_json_31121_tables_columns_expressions_StrAgg <.. repo.RepoObjectColumn_gross
ssas.model_json_312_tables_measures <.. ssas.model_json_312_tables_measures_T
ssas.model_json_312_tables_measures_T <.. ssas.model_json_3122_tables_measures_expressions_multiline
ssas.model_json_312_tables_measures_T <.. repo.Measure
ssas.model_json_312_tables_measures_T <.. ssas.model_json_3121_tables_columns_descriptions_multiline
ssas.model_json_3121_tables_columns_descriptions_multiline <.. ssas.model_json_31211_tables_columns_descriptions_StrAgg
ssas.model_json_31211_tables_columns_descriptions_StrAgg <.. repo.Measure
ssas.model_json_3122_tables_measures_expressions_multiline <.. ssas.model_json_31221_tables_measures_expressions_StrAgg
ssas.model_json_31221_tables_measures_expressions_StrAgg <.. repo.Measure
ssas.model_json_313_tables_partitions <.. ssas.model_json_3131_tables_partitions_source
ssas.model_json_3131_tables_partitions_source <.. ssas.model_json_31311_tables_partitions_source_PosFrom
ssas.model_json_31311_tables_partitions_source_PosFrom <.. ssas.model_json_313111_tables_partitions_source_StringFrom
ssas.model_json_313111_tables_partitions_source_StringFrom <.. ssas.model_json_3131111_tables_partitions_source_PosDot
ssas.model_json_3131111_tables_partitions_source_PosDot <.. ssas.model_json_31311111_tables_partitions_source_Part123
ssas.model_json_31311111_tables_partitions_source_Part123 <.. ssas.additional_Reference_step1
ssas.model_json_316_tables_descriptions_multiline <.. ssas.model_json_3161_tables_descriptions_StrAgg
ssas.model_json_3161_tables_descriptions_StrAgg <.. repo.RepoObject_gross
ssas.model_json_33_dataSources <.. ssas.model_json_33_dataSources_T
ssas.model_json_33_dataSources_T <.. ssas.additional_Reference_step1
ssas.model_json_34_cultures <.. ssas.model_json_341_cultures_translations
ssas.model_json_341_cultures_translations <.. ssas.model_json_3411_cultures_translations_model
ssas.model_json_3411_cultures_translations_model <.. ssas.model_json_3411_cultures_translations_model_T
ssas.model_json_3411_cultures_translations_model_T <.. docs.RepoObject_OutputFilter
ssas.model_json_3411_cultures_translations_model_T <.. docs.Culture
ssas.model_json_3411_cultures_translations_model_T <.. ssas.model_json_34111_cultures_translations_model_tables
ssas.model_json_34111_cultures_translations_model_tables <.. docs.RepoObject_OutputFilter
sys_dwh.columns <.. repo_sys.SysColumn
sys_dwh.columns <.. repo_sys.ExtendedProperties
sys_dwh.computed_columns <.. repo_sys.SysColumn
sys_dwh.default_constraints <.. repo_sys.SysColumn
sys_dwh.extended_properties <.. repo_sys.ExtendedProperties
sys_dwh.identity_columns <.. repo_sys.SysColumn
sys_dwh.indexes <.. repo_sys.ExtendedProperties
sys_dwh.objects <.. repo_sys.ExtendedProperties
sys_dwh.objects <.. repo_sys.SysObject
sys_dwh.parameters <.. repo_sys.ExtendedProperties
sys_dwh.schemas <.. repo_sys.SysObject
sys_dwh.schemas <.. repo_sys.ExtendedProperties
sys_dwh.sql_expression_dependencies <.. repo_sys.sql_expression_dependencies
sys_dwh.sql_modules <.. repo_sys.SysObject
sys_dwh.tables <.. repo_sys.SysObject
sys_dwh.types <.. repo_sys.SysColumn
uspgenerator.GeneratorUsp <.. repo.RepoObject_gross

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_30_0_objectref[]

=== PlantUML 0 30 ObjectRef

// tag::puml_entity_0_30_objectref[]
[plantuml, entity_0_30_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:dmdocs.unit.adoc[]" as dmdocs.unit << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.unit_3.adoc[]" as docs.Unit_3 << V >> {
  --
}

docs.Unit_3 <.. dmdocs.unit

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_0_30_objectref[]

=== PlantUML 1 1 ColumnRef

// tag::puml_entity_1_1_colref[]
[plantuml, entity_1_1_colref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:dmdocs.unit.adoc[]" as dmdocs.unit << V >> {
  AntoraComponent : (nvarchar(max))
  AntoraModule : (nvarchar(max))
  AntoraPage : (nvarchar(4000))
  AntoraSectionId : (nvarchar(4000))
  AntoraSiteUrl : (nvarchar(max))
  AntoraVersion : (nvarchar(max))
  Object_fullname2 : (nvarchar(257))
  Object_Type : (varchar(2))
  Unit_ColummName : (nvarchar(128))
  Unit_Description : (nvarchar(max))
  Unit_DisplayFolder : (nvarchar(500))
  Unit_Expression : (nvarchar(max))
  Unit_FormatString : (nvarchar(500))
  - Unit_fullname2 : (nvarchar(638))
  - Unit_guid : (uniqueidentifier)
  Unit_isHidden : (bit)
  Unit_IsKey : (bit)
  Unit_IsSsas : (bit)
  Unit_IsUnique : (bit)
  - Unit_Metatype : (varchar(7))
  - Unit_Name : (nvarchar(500))
  Unit_ObjectName : (nvarchar(128))
  - Unit_Schema : (nvarchar(128))
  Unit_SummarizeBy : (nvarchar(500))
  Unit_TypeName : (nvarchar(128))
  - Unit_Url : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:docs.unit_2.adoc[]" as docs.Unit_2 << V >> {
  AntoraComponent : (nvarchar(max))
  AntoraModule : (nvarchar(max))
  AntoraPage : (nvarchar(4000))
  AntoraSectionId : (nvarchar(4000))
  AntoraSiteUrl : (nvarchar(max))
  AntoraVersion : (nvarchar(max))
  Object_fullname2 : (nvarchar(257))
  Object_Type : (varchar(2))
  Unit_ColummName : (nvarchar(128))
  Unit_Description : (nvarchar(max))
  Unit_DisplayFolder : (nvarchar(500))
  Unit_Expression : (nvarchar(max))
  Unit_FormatString : (nvarchar(500))
  - Unit_fullname2 : (nvarchar(638))
  - Unit_guid : (uniqueidentifier)
  Unit_isHidden : (bit)
  Unit_IsKey : (bit)
  Unit_IsSsas : (bit)
  Unit_IsUnique : (bit)
  - Unit_Metatype : (varchar(7))
  - Unit_Name : (nvarchar(500))
  Unit_ObjectName : (nvarchar(128))
  - Unit_Schema : (nvarchar(128))
  Unit_SummarizeBy : (nvarchar(500))
  Unit_TypeName : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:docs.unit_3.adoc[]" as docs.Unit_3 << V >> {
  AntoraComponent : (nvarchar(max))
  AntoraModule : (nvarchar(max))
  AntoraPage : (nvarchar(4000))
  AntoraSectionId : (nvarchar(4000))
  AntoraSiteUrl : (nvarchar(max))
  AntoraVersion : (nvarchar(max))
  Object_fullname2 : (nvarchar(257))
  Object_Type : (varchar(2))
  Unit_ColummName : (nvarchar(128))
  Unit_Description : (nvarchar(max))
  Unit_DisplayFolder : (nvarchar(500))
  Unit_Expression : (nvarchar(max))
  Unit_FormatString : (nvarchar(500))
  - Unit_fullname2 : (nvarchar(638))
  - Unit_guid : (uniqueidentifier)
  Unit_isHidden : (bit)
  Unit_IsKey : (bit)
  Unit_IsSsas : (bit)
  Unit_IsUnique : (bit)
  - Unit_Metatype : (varchar(7))
  - Unit_Name : (nvarchar(500))
  Unit_ObjectName : (nvarchar(128))
  - Unit_Schema : (nvarchar(128))
  Unit_SummarizeBy : (nvarchar(500))
  Unit_TypeName : (nvarchar(128))
  - Unit_Url : (nvarchar(max))
  --
}

docs.Unit_2 <.. docs.Unit_3
docs.Unit_3 <.. dmdocs.unit
"docs.Unit_2::AntoraComponent" <-- "docs.Unit_3::AntoraComponent"
"docs.Unit_2::AntoraModule" <-- "docs.Unit_3::AntoraModule"
"docs.Unit_2::AntoraPage" <-- "docs.Unit_3::AntoraPage"
"docs.Unit_2::AntoraSectionId" <-- "docs.Unit_3::AntoraSectionId"
"docs.Unit_2::AntoraSiteUrl" <-- "docs.Unit_3::AntoraSiteUrl"
"docs.Unit_2::AntoraVersion" <-- "docs.Unit_3::AntoraVersion"
"docs.Unit_2::Object_fullname2" <-- "docs.Unit_3::Object_fullname2"
"docs.Unit_2::Object_Type" <-- "docs.Unit_3::Object_Type"
"docs.Unit_2::Unit_ColummName" <-- "docs.Unit_3::Unit_ColummName"
"docs.Unit_2::Unit_Description" <-- "docs.Unit_3::Unit_Description"
"docs.Unit_2::Unit_DisplayFolder" <-- "docs.Unit_3::Unit_DisplayFolder"
"docs.Unit_2::Unit_Expression" <-- "docs.Unit_3::Unit_Expression"
"docs.Unit_2::Unit_FormatString" <-- "docs.Unit_3::Unit_FormatString"
"docs.Unit_2::Unit_fullname2" <-- "docs.Unit_3::Unit_fullname2"
"docs.Unit_2::Unit_guid" <-- "docs.Unit_3::Unit_guid"
"docs.Unit_2::Unit_isHidden" <-- "docs.Unit_3::Unit_isHidden"
"docs.Unit_2::Unit_IsKey" <-- "docs.Unit_3::Unit_IsKey"
"docs.Unit_2::Unit_IsSsas" <-- "docs.Unit_3::Unit_IsSsas"
"docs.Unit_2::Unit_IsUnique" <-- "docs.Unit_3::Unit_IsUnique"
"docs.Unit_2::Unit_Metatype" <-- "docs.Unit_3::Unit_Metatype"
"docs.Unit_2::Unit_Name" <-- "docs.Unit_3::Unit_Name"
"docs.Unit_2::Unit_ObjectName" <-- "docs.Unit_3::Unit_ObjectName"
"docs.Unit_2::Unit_Schema" <-- "docs.Unit_3::Unit_Schema"
"docs.Unit_2::Unit_SummarizeBy" <-- "docs.Unit_3::Unit_SummarizeBy"
"docs.Unit_2::Unit_TypeName" <-- "docs.Unit_3::Unit_TypeName"
"docs.Unit_3::AntoraComponent" <-- "dmdocs.unit::AntoraComponent"
"docs.Unit_3::AntoraModule" <-- "dmdocs.unit::AntoraModule"
"docs.Unit_3::AntoraPage" <-- "dmdocs.unit::AntoraPage"
"docs.Unit_3::AntoraSectionId" <-- "dmdocs.unit::AntoraSectionId"
"docs.Unit_3::AntoraSiteUrl" <-- "dmdocs.unit::AntoraSiteUrl"
"docs.Unit_3::AntoraVersion" <-- "dmdocs.unit::AntoraVersion"
"docs.Unit_3::Object_fullname2" <-- "dmdocs.unit::Object_fullname2"
"docs.Unit_3::Object_Type" <-- "dmdocs.unit::Object_Type"
"docs.Unit_3::Unit_ColummName" <-- "dmdocs.unit::Unit_ColummName"
"docs.Unit_3::Unit_Description" <-- "dmdocs.unit::Unit_Description"
"docs.Unit_3::Unit_DisplayFolder" <-- "dmdocs.unit::Unit_DisplayFolder"
"docs.Unit_3::Unit_Expression" <-- "dmdocs.unit::Unit_Expression"
"docs.Unit_3::Unit_FormatString" <-- "dmdocs.unit::Unit_FormatString"
"docs.Unit_3::Unit_fullname2" <-- "dmdocs.unit::Unit_fullname2"
"docs.Unit_3::Unit_guid" <-- "dmdocs.unit::Unit_guid"
"docs.Unit_3::Unit_isHidden" <-- "dmdocs.unit::Unit_isHidden"
"docs.Unit_3::Unit_IsKey" <-- "dmdocs.unit::Unit_IsKey"
"docs.Unit_3::Unit_IsSsas" <-- "dmdocs.unit::Unit_IsSsas"
"docs.Unit_3::Unit_IsUnique" <-- "dmdocs.unit::Unit_IsUnique"
"docs.Unit_3::Unit_Metatype" <-- "dmdocs.unit::Unit_Metatype"
"docs.Unit_3::Unit_Name" <-- "dmdocs.unit::Unit_Name"
"docs.Unit_3::Unit_ObjectName" <-- "dmdocs.unit::Unit_ObjectName"
"docs.Unit_3::Unit_Schema" <-- "dmdocs.unit::Unit_Schema"
"docs.Unit_3::Unit_SummarizeBy" <-- "dmdocs.unit::Unit_SummarizeBy"
"docs.Unit_3::Unit_TypeName" <-- "dmdocs.unit::Unit_TypeName"
"docs.Unit_3::Unit_Url" <-- "dmdocs.unit::Unit_Url"

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_colref[]


== sql_modules_definition

// tag::sql_modules_definition[]
[%collapsible]
=======
[source,sql,numbered,indent=0]
----

CREATE View docs.Unit_3
As
Select
    Unit_guid
  , Unit_Metatype
  , Unit_Schema
  , Unit_ObjectName
  , Unit_ColummName
  , Unit_Name
  , Unit_fullname2
  , Unit_TypeName
  , Unit_isHidden
  , Unit_IsSsas
  , Unit_Description
  , Unit_DisplayFolder
  , Unit_Expression
  , Unit_FormatString
  , Unit_IsKey
  , Unit_IsUnique
  , Unit_SummarizeBy
  , Object_fullname2
  , Object_Type
  , AntoraSiteUrl
  , AntoraComponent
  , AntoraVersion
  , AntoraModule
  , AntoraPage
  , AntoraSectionId
  --file:///D:/Repos/GitHub/DataHandwerk/datahandwerk.github.io/local/dhw/0.1.0/sqldb/repo.RepoObject.html#column-InheritanceType
  , Unit_Url = Concat (
                          AntoraSiteUrl
                        , '/' + AntoraComponent
                        , '/' + AntoraVersion
                        , '/' + AntoraModule
                        , '/' + AntoraPage + '.html'
                        , '#' + AntoraSectionId
                      )
From
    docs.Unit_2

----
=======
// end::sql_modules_definition[]


