// tag::HeaderFullDisplayName[]
= docs.Schema_puml - V
// end::HeaderFullDisplayName[]

== existing_properties

// tag::existing_properties[]

:ExistsProperty--antorareferencedlist:
:ExistsProperty--antorareferencinglist:
:ExistsProperty--is_repo_managed:
:ExistsProperty--is_ssas:
:ExistsProperty--pk_index_guid:
:ExistsProperty--pk_indexpatterncolumndatatype:
:ExistsProperty--pk_indexpatterncolumnname:
:ExistsProperty--referencedobjectlist:
:ExistsProperty--sql_modules_definition:
:ExistsProperty--FK:
:ExistsProperty--AntoraIndexList:
:ExistsProperty--Columns:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
0B60D8EE-E90A-EC11-8516-A81E8446D5B0
// end::RepoObject_guid[]

== RepoObject_FullDisplayName2

// tag::RepoObject_FullDisplayName2[]
docs.Schema_puml
// end::RepoObject_FullDisplayName2[]

== SysObject_type

// tag::SysObject_type[]
V 
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
view
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
775009842
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2021-11-10 09:58:43
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]
[discrete]
== _


[#column-reposchemaunderlineguid]
=== RepoSchema_guid

[cols="d,8a,m,m,m"]
|===
|1
|*RepoSchema_guid*
|uniqueidentifier
|NOT NULL
|
|===

.Referenced Columns
--
* xref:repo.reposchema.adoc#column-reposchemaunderlineguid[+repo.RepoSchema.RepoSchema_guid+]
--


[#column-culturesunderlinename]
=== cultures_name

[cols="d,8a,m,m,m"]
|===
|2
|*cultures_name*
|nvarchar(10)
|NULL
|
|===


[#column-isunderlinessas]
=== is_ssas

[cols="d,8a,m,m,m"]
|===
|
|is_ssas
|bit
|NOT NULL
|
|===

.Referenced Columns
--
* xref:repo.reposchema.adoc#column-isunderlinessas[+repo.RepoSchema.is_ssas+]
--


[#column-pumlschemaer]
=== PumlSchemaEr

[cols="d,8a,m,m,m"]
|===
|
|PumlSchemaEr
|nvarchar(max)
|NOT NULL
|
|===


[#column-pumlschemaindexer]
=== PumlSchemaIndexEr

[cols="d,8a,m,m,m"]
|===
|
|PumlSchemaIndexEr
|nvarchar(max)
|NOT NULL
|
|===


[#column-pumlschemassaser]
=== PumlSchemaSsasEr

[cols="d,8a,m,m,m"]
|===
|
|PumlSchemaSsasEr
|nvarchar(max)
|NULL
|
|===


[#column-reposchemaunderlinename]
=== RepoSchema_name

[cols="d,8a,m,m,m"]
|===
|
|RepoSchema_name
|nvarchar(128)
|NOT NULL
|
|===

.Referenced Columns
--
* xref:repo.reposchema.adoc#column-reposchemaunderlinename[+repo.RepoSchema.RepoSchema_name+]
--


// end::AntoraColumnDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]
|1
|*<<column-reposchemaunderlineguid>>*
|uniqueidentifier
|NOT NULL
|

|2
|*<<column-culturesunderlinename>>*
|nvarchar(10)
|NULL
|






// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]


|
|<<column-isunderlinessas>>
|bit
|NOT NULL
|

|
|<<column-pumlschemaer>>
|nvarchar(max)
|NOT NULL
|

|
|<<column-pumlschemaindexer>>
|nvarchar(max)
|NOT NULL
|

|
|<<column-pumlschemassaser>>
|nvarchar(max)
|NULL
|

|
|<<column-reposchemaunderlinename>>
|nvarchar(128)
|NOT NULL
|

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

[#index-pkunderlineschemaunderlinepuml]
=== PK_Schema_puml

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-RepoSchema_guid>>; uniqueidentifier
* <<column-cultures_name>>; nvarchar(10)
--
* PK, Unique, Real: 1, 1, 0


[#index-idxunderlineschemaunderlinepumlunderlineunderline1]
=== idx_Schema_puml++__++1

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-RepoSchema_guid>>; uniqueidentifier
--
* PK, Unique, Real: 0, 0, 0


[#index-idxunderlineschemaunderlinepumlunderlineunderline2]
=== idx_Schema_puml++__++2

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-RepoSchema_name>>; nvarchar(128)
--
* PK, Unique, Real: 0, 0, 0

// end::AntoraIndexList[]

== AntoraMeasureDetails

// tag::AntoraMeasureDetails[]

// end::AntoraMeasureDetails[]

== AntoraMeasureDescriptions



== AntoraParameterList

// tag::AntoraParameterList[]

// end::AntoraParameterList[]

== AntoraXrefCulturesList

// tag::AntoraXrefCulturesList[]
* xref:dhw:sqldb:docs.schema_puml.adoc[] - 
// end::AntoraXrefCulturesList[]

== cultures_count

// tag::cultures_count[]
1
// end::cultures_count[]

== Other tags

source: property.RepoObjectProperty_cross As rop_cross


=== additional_reference_csv

// tag::additional_reference_csv[]

// end::additional_reference_csv[]


=== AdocUspSteps

// tag::adocuspsteps[]

// end::adocuspsteps[]


=== AntoraReferencedList

// tag::antorareferencedlist[]
* xref:dhw:sqldb:config.ftv_get_parameter_value.adoc[]
* xref:dhw:sqldb:docs.fs_pumlheaderlefttoright.adoc[]
* xref:dhw:sqldb:docs.repoobject_outputfilter_t.adoc[]
* xref:dhw:sqldb:docs.schema_entitylist.adoc[]
* xref:dhw:sqldb:docs.schema_pumlpartial_fkreflist.adoc[]
* xref:dhw:sqldb:docs.schema_ssasrelationlist.adoc[]
* xref:dhw:sqldb:repo.reposchema.adoc[]
// end::antorareferencedlist[]


=== AntoraReferencingList

// tag::antorareferencinglist[]
* xref:dhw:sqldb:docs.antoranavlistpage_by_schema.adoc[]
// end::antorareferencinglist[]


=== Description

// tag::description[]

// end::description[]


=== exampleUsage

// tag::exampleusage[]

// end::exampleusage[]


=== exampleUsage_2

// tag::exampleusage_2[]

// end::exampleusage_2[]


=== exampleUsage_3

// tag::exampleusage_3[]

// end::exampleusage_3[]


=== exampleUsage_4

// tag::exampleusage_4[]

// end::exampleusage_4[]


=== exampleUsage_5

// tag::exampleusage_5[]

// end::exampleusage_5[]


=== exampleWrong_Usage

// tag::examplewrong_usage[]

// end::examplewrong_usage[]


=== has_execution_plan_issue

// tag::has_execution_plan_issue[]

// end::has_execution_plan_issue[]


=== has_get_referenced_issue

// tag::has_get_referenced_issue[]

// end::has_get_referenced_issue[]


=== has_history

// tag::has_history[]

// end::has_history[]


=== has_history_columns

// tag::has_history_columns[]

// end::has_history_columns[]


=== InheritanceType

// tag::inheritancetype[]

// end::inheritancetype[]


=== is_persistence

// tag::is_persistence[]

// end::is_persistence[]


=== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]

// end::is_persistence_check_duplicate_per_pk[]


=== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]

// end::is_persistence_check_for_empty_source[]


=== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]

// end::is_persistence_delete_changed[]


=== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]

// end::is_persistence_delete_missing[]


=== is_persistence_insert

// tag::is_persistence_insert[]

// end::is_persistence_insert[]


=== is_persistence_truncate

// tag::is_persistence_truncate[]

// end::is_persistence_truncate[]


=== is_persistence_update_changed

// tag::is_persistence_update_changed[]

// end::is_persistence_update_changed[]


=== is_repo_managed

// tag::is_repo_managed[]
0
// end::is_repo_managed[]


=== is_ssas

// tag::is_ssas[]
0
// end::is_ssas[]


=== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


=== MS_Description

// tag::ms_description[]

// end::ms_description[]


=== persistence_source_RepoObject_fullname

// tag::persistence_source_repoobject_fullname[]

// end::persistence_source_repoobject_fullname[]


=== persistence_source_RepoObject_fullname2

// tag::persistence_source_repoobject_fullname2[]

// end::persistence_source_repoobject_fullname2[]


=== persistence_source_RepoObject_guid

// tag::persistence_source_repoobject_guid[]

// end::persistence_source_repoobject_guid[]


=== persistence_source_RepoObject_xref

// tag::persistence_source_repoobject_xref[]

// end::persistence_source_repoobject_xref[]


=== pk_index_guid

// tag::pk_index_guid[]
016803A0-0822-EC11-8524-A81E8446D5B0
// end::pk_index_guid[]


=== pk_IndexPatternColumnDatatype

// tag::pk_indexpatterncolumndatatype[]
uniqueidentifier,nvarchar(10)
// end::pk_indexpatterncolumndatatype[]


=== pk_IndexPatternColumnName

// tag::pk_indexpatterncolumnname[]
RepoSchema_guid,cultures_name
// end::pk_indexpatterncolumnname[]


=== pk_IndexSemanticGroup

// tag::pk_indexsemanticgroup[]

// end::pk_indexsemanticgroup[]


=== ReferencedObjectList

// tag::referencedobjectlist[]
* [config].[ftv_get_parameter_value]
* [docs].[fs_PumlHeaderLeftToRight]
* [docs].[RepoObject_OutputFilter_T]
* [docs].[Schema_EntityList]
* [docs].[Schema_PumlPartial_FkRefList]
* [docs].[Schema_SsasRelationList]
* [repo].[RepoSchema]
// end::referencedobjectlist[]


=== usp_persistence_RepoObject_guid

// tag::usp_persistence_repoobject_guid[]

// end::usp_persistence_repoobject_guid[]


=== UspExamples

// tag::uspexamples[]

// end::uspexamples[]


=== uspgenerator_usp_id

// tag::uspgenerator_usp_id[]

// end::uspgenerator_usp_id[]


=== UspParameters

// tag::uspparameters[]

// end::uspparameters[]

== Boolean Attributes

source: property.RepoObjectProperty WHERE property_int = 1

// tag::boolean_attributes[]


// end::boolean_attributes[]

== PlantUML diagrams

=== PlantUML Entity

// tag::puml_entity[]
[plantuml, entity-{docname}, svg, subs=macros]
....
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:docs.schema_puml.adoc[]" as docs.Schema_puml << V >> {
  - **RepoSchema_guid** : (uniqueidentifier)
  **cultures_name** : (nvarchar(10))
  - is_ssas : (bit)
  - PumlSchemaEr : (nvarchar(max))
  - PumlSchemaIndexEr : (nvarchar(max))
  PumlSchemaSsasEr : (nvarchar(max))
  - RepoSchema_name : (nvarchar(128))
  --
}
....

// end::puml_entity[]

=== PlantUML Entity 1 1 FK

// tag::puml_entity_1_1_fk[]
[plantuml, entity_1_1_fk-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:docs.schema_puml.adoc[]" as docs.Schema_puml << V >> {
- **PK_Schema_puml**

..
RepoSchema_guid; uniqueidentifier
cultures_name; nvarchar(10)
--
- idx_Schema_puml__1

..
RepoSchema_guid; uniqueidentifier
--
- idx_Schema_puml__2

..
RepoSchema_name; nvarchar(128)
}



footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_fk[]

=== PlantUML 1 1 ObjectRef

// tag::puml_entity_1_1_objectref[]
[plantuml, entity_1_1_objectref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:config.ftv_get_parameter_value.adoc[]" as config.ftv_get_parameter_value << IF >> {
  --
}

entity "puml-link:dhw:sqldb:docs.antoranavlistpage_by_schema.adoc[]" as docs.AntoraNavListPage_by_schema << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.fs_pumlheaderlefttoright.adoc[]" as docs.fs_PumlHeaderLeftToRight << FN >> {
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_outputfilter_t.adoc[]" as docs.RepoObject_OutputFilter_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.schema_entitylist.adoc[]" as docs.Schema_EntityList << V >> {
  - **RepoObject_schema_name** : (nvarchar(128))
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.schema_puml.adoc[]" as docs.Schema_puml << V >> {
  - **RepoSchema_guid** : (uniqueidentifier)
  **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.schema_pumlpartial_fkreflist.adoc[]" as docs.Schema_PumlPartial_FkRefList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.schema_ssasrelationlist.adoc[]" as docs.Schema_SsasRelationList << V >> {
  - **SchemaName** : (nvarchar(128))
  **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:repo.reposchema.adoc[]" as repo.RepoSchema << U >> {
  - **RepoSchema_guid** : (uniqueidentifier)
  --
}

config.ftv_get_parameter_value <.. docs.Schema_puml
docs.fs_PumlHeaderLeftToRight <.. docs.Schema_puml
docs.RepoObject_OutputFilter_T <.. docs.Schema_puml
docs.Schema_EntityList <.. docs.Schema_puml
docs.Schema_puml <.. docs.AntoraNavListPage_by_schema
docs.Schema_PumlPartial_FkRefList <.. docs.Schema_puml
docs.Schema_SsasRelationList <.. docs.Schema_puml
repo.RepoSchema <.. docs.Schema_puml

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_objectref[]

=== PlantUML 30 0 ObjectRef

// tag::puml_entity_30_0_objectref[]
[plantuml, entity_30_0_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:config.ftv_dwh_database.adoc[]" as config.ftv_dwh_database << IF >> {
  --
}

entity "puml-link:dhw:sqldb:config.ftv_get_parameter_value.adoc[]" as config.ftv_get_parameter_value << IF >> {
  --
}

entity "puml-link:dhw:sqldb:config.parameter.adoc[]" as config.Parameter << U >> {
  - **Parameter_name** : (varchar(100))
  - **sub_Parameter** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:configt.join_type.adoc[]" as configT.join_type << V >> {
  - **join_type** : (varchar(16))
  --
}

entity "puml-link:dhw:sqldb:configt.parameter_default.adoc[]" as configT.Parameter_default << V >> {
  - **Parameter_name** : (varchar(52))
  - **sub_Parameter** : (nvarchar(26))
  --
}

entity "puml-link:dhw:sqldb:configt.spt_values.adoc[]" as configT.spt_values << U >> {
  --
}

entity "puml-link:dhw:sqldb:configt.type.adoc[]" as configT.type << V >> {
  **type** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:docs.culture.adoc[]" as docs.Culture << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.fs_cleanstringforanchorid.adoc[]" as docs.fs_cleanStringForAnchorId << FN >> {
  --
}

entity "puml-link:dhw:sqldb:docs.fs_cleanstringforfilename.adoc[]" as docs.fs_cleanStringForFilename << FN >> {
  --
}

entity "puml-link:dhw:sqldb:docs.fs_cleanstringforheader.adoc[]" as docs.fs_cleanStringForHeader << FN >> {
  --
}

entity "puml-link:dhw:sqldb:docs.fs_cleanstringforpuml.adoc[]" as docs.fs_cleanStringForPuml << FN >> {
  --
}

entity "puml-link:dhw:sqldb:docs.fs_pumlheaderlefttoright.adoc[]" as docs.fs_PumlHeaderLeftToRight << FN >> {
  --
}

entity "puml-link:dhw:sqldb:docs.measure_measurepropertylist.adoc[]" as docs.Measure_MeasurePropertyList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_columnlist.adoc[]" as docs.RepoObject_ColumnList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_columnlist_t.adoc[]" as docs.RepoObject_ColumnList_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_indexlist.adoc[]" as docs.RepoObject_IndexList << V >> {
  **RepoObject_guid** : (uniqueidentifier)
  **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_indexlist_t.adoc[]" as docs.RepoObject_IndexList_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_measurelist.adoc[]" as docs.RepoObject_MeasureList << V >> {
  **RepoObject_guid** : (uniqueidentifier)
  **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_outputfilter.adoc[]" as docs.RepoObject_OutputFilter << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_outputfilter_t.adoc[]" as docs.RepoObject_OutputFilter_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_outputfilter_t_gross.adoc[]" as docs.RepoObject_OutputFilter_T_gross << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_entity.adoc[]" as docs.RepoObject_Plantuml_Entity << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_entity_t.adoc[]" as docs.RepoObject_Plantuml_Entity_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.schema_entitylist.adoc[]" as docs.Schema_EntityList << V >> {
  - **RepoObject_schema_name** : (nvarchar(128))
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.schema_puml.adoc[]" as docs.Schema_puml << V >> {
  - **RepoSchema_guid** : (uniqueidentifier)
  **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.schema_pumlpartial_fkreflist.adoc[]" as docs.Schema_PumlPartial_FkRefList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.schema_ssasrelationlist.adoc[]" as docs.Schema_SsasRelationList << V >> {
  - **SchemaName** : (nvarchar(128))
  **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.ssas_pumlrelation.adoc[]" as docs.ssas_PumlRelation << V >> {
  --
}

entity "puml-link:dhw:sqldb:property.external_repoobjectcolumnproperty.adoc[]" as property.external_RepoObjectColumnProperty << U >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.external_repoobjectproperty.adoc[]" as property.external_RepoObjectProperty << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.fs_get_repoobjectcolumnproperty_nvarchar.adoc[]" as property.fs_get_RepoObjectColumnProperty_nvarchar << FN >> {
  --
}

entity "puml-link:dhw:sqldb:property.fs_get_repoobjectproperty_nvarchar.adoc[]" as property.fs_get_RepoObjectProperty_nvarchar << FN >> {
  --
}

entity "puml-link:dhw:sqldb:property.measureproperty.adoc[]" as property.MeasureProperty << U >> {
  - **Measure_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.propertyname_measure.adoc[]" as property.PropertyName_Measure << V >> {
  **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.propertyname_measure_t.adoc[]" as property.PropertyName_Measure_T << U >> {
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.propertyname_repoobject.adoc[]" as property.PropertyName_RepoObject << V >> {
  **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.propertyname_repoobject_t.adoc[]" as property.PropertyName_RepoObject_T << U >> {
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectcolumnproperty.adoc[]" as property.RepoObjectColumnProperty << U >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectcolumnproperty_external_src.adoc[]" as property.RepoObjectColumnProperty_external_src << V >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectcolumnproperty_external_tgt.adoc[]" as property.RepoObjectColumnProperty_external_tgt << V >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty.adoc[]" as property.RepoObjectProperty << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty_external_src.adoc[]" as property.RepoObjectProperty_external_src << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty_external_tgt.adoc[]" as property.RepoObjectProperty_external_tgt << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty_selectedpropertyname_split.adoc[]" as property.RepoObjectProperty_SelectedPropertyName_split << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference.adoc[]" as reference.additional_Reference << U >> {
  # **tik_hash_c** : (nvarchar(32))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_database.adoc[]" as reference.additional_Reference_database << V >> {
  - **AntoraComponent** : (nvarchar(128))
  - **AntoraModule** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_database_t.adoc[]" as reference.additional_Reference_database_T << U >> {
  - **AntoraComponent** : (nvarchar(128))
  - **AntoraModule** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_from_properties_src.adoc[]" as reference.additional_Reference_from_properties_src << V >> {
  **referenced_AntoraComponent** : (nvarchar(max))
  **referenced_AntoraModule** : (nvarchar(max))
  **referenced_Schema** : (nvarchar(max))
  **referenced_Object** : (nvarchar(max))
  **referenced_Column** : (nvarchar(max))
  **referencing_AntoraComponent** : (nvarchar(max))
  **referencing_AntoraModule** : (nvarchar(max))
  **referencing_Schema** : (nvarchar(max))
  **referencing_Object** : (nvarchar(max))
  **referencing_Column** : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_from_properties_tgt.adoc[]" as reference.additional_Reference_from_properties_tgt << V >> {
  - **referenced_AntoraComponent** : (nvarchar(128))
  - **referenced_AntoraModule** : (nvarchar(128))
  - **referenced_Schema** : (nvarchar(128))
  - **referenced_Object** : (nvarchar(128))
  **referenced_Column** : (nvarchar(128))
  - **referencing_AntoraComponent** : (nvarchar(128))
  - **referencing_AntoraModule** : (nvarchar(128))
  - **referencing_Schema** : (nvarchar(128))
  - **referencing_Object** : (nvarchar(128))
  **referencing_Column** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_from_ssas_src.adoc[]" as reference.additional_Reference_from_ssas_src << V >> {
  **referenced_AntoraComponent** : (nvarchar(128))
  **referenced_AntoraModule** : (nvarchar(128))
  **referenced_Schema** : (nvarchar(max))
  **referenced_Object** : (nvarchar(max))
  **referenced_Column** : (nvarchar(500))
  **referencing_AntoraComponent** : (nvarchar(max))
  **referencing_AntoraModule** : (nvarchar(max))
  - **referencing_Schema** : (nvarchar(128))
  - **referencing_Object** : (nvarchar(128))
  **referencing_Column** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_from_ssas_tgt.adoc[]" as reference.additional_Reference_from_ssas_tgt << V >> {
  - **referenced_AntoraComponent** : (nvarchar(128))
  - **referenced_AntoraModule** : (nvarchar(128))
  - **referenced_Schema** : (nvarchar(128))
  - **referenced_Object** : (nvarchar(128))
  **referenced_Column** : (nvarchar(128))
  - **referencing_AntoraComponent** : (nvarchar(128))
  - **referencing_AntoraModule** : (nvarchar(128))
  - **referencing_Schema** : (nvarchar(128))
  - **referencing_Object** : (nvarchar(128))
  **referencing_Column** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_guid.adoc[]" as reference.additional_Reference_guid << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_is_external.adoc[]" as reference.additional_Reference_is_external << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_object.adoc[]" as reference.additional_Reference_Object << V >> {
  - **AntoraComponent** : (nvarchar(128))
  - **AntoraModule** : (nvarchar(128))
  - **SchemaName** : (nvarchar(128))
  - **ObjectName** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_object_t.adoc[]" as reference.additional_Reference_Object_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_objectcolumn.adoc[]" as reference.additional_Reference_ObjectColumn << V >> {
  - **AntoraComponent** : (nvarchar(128))
  - **AntoraModule** : (nvarchar(128))
  - **SchemaName** : (nvarchar(128))
  - **ObjectName** : (nvarchar(128))
  **ColumnName** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_objectcolumn_t.adoc[]" as reference.additional_Reference_ObjectColumn_T << U >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_wo_columns_from_properties_src.adoc[]" as reference.additional_Reference_wo_columns_from_properties_src << V >> {
  **referenced_AntoraComponent** : (nvarchar(max))
  **referenced_AntoraModule** : (nvarchar(max))
  **referenced_Schema** : (nvarchar(max))
  **referenced_Object** : (nvarchar(max))
  **referencing_AntoraComponent** : (nvarchar(max))
  **referencing_AntoraModule** : (nvarchar(max))
  **referencing_Schema** : (nvarchar(max))
  **referencing_Object** : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_wo_columns_from_properties_tgt.adoc[]" as reference.additional_Reference_wo_columns_from_properties_tgt << V >> {
  - **referenced_AntoraComponent** : (nvarchar(128))
  - **referenced_AntoraModule** : (nvarchar(128))
  - **referenced_Schema** : (nvarchar(128))
  - **referenced_Object** : (nvarchar(128))
  - **referencing_AntoraComponent** : (nvarchar(128))
  - **referencing_AntoraModule** : (nvarchar(128))
  - **referencing_Schema** : (nvarchar(128))
  - **referencing_Object** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_queryplan.adoc[]" as reference.RepoObject_QueryPlan << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_reference.adoc[]" as reference.RepoObject_reference << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_reference_additional.adoc[]" as reference.RepoObject_reference_additional << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_reference_persistence.adoc[]" as reference.RepoObject_reference_persistence << V >> {
  **referenced_RepoObject_guid** : (uniqueidentifier)
  - **referencing_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_reference_persistence_target_as_source.adoc[]" as reference.RepoObject_reference_persistence_target_as_source << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_reference_persistence_target_as_source_explicit.adoc[]" as reference.RepoObject_reference_persistence_target_as_source_explicit << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_reference_sqlexpressiondependencies.adoc[]" as reference.RepoObject_reference_SqlExpressionDependencies << V >> {
  **referenced_RepoObject_guid** : (uniqueidentifier)
  **referencing_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_reference_t.adoc[]" as reference.RepoObject_reference_T << U >> {
  - **referenced_RepoObject_guid** : (uniqueidentifier)
  - **referencing_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_reference_union.adoc[]" as reference.RepoObject_reference_union << V >> {
  **referenced_RepoObject_guid** : (uniqueidentifier)
  **referencing_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_reference_virtual.adoc[]" as reference.RepoObject_reference_virtual << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_referencedreferencing.adoc[]" as reference.RepoObject_ReferencedReferencing << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_reference.adoc[]" as reference.RepoObjectColumn_reference << V >> {
  **referenced_RepoObjectColumn_guid** : (uniqueidentifier)
  **referencing_RepoObjectColumn_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_reference_additional.adoc[]" as reference.RepoObjectColumn_reference_additional << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_reference_persistence.adoc[]" as reference.RepoObjectColumn_reference_Persistence << V >> {
  **referencing_id** : (int)
  **referencing_minor_id** : (int)
  **referenced_id** : (int)
  **referenced_minor_id** : (int)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_reference_sqlexpressiondependencies.adoc[]" as reference.RepoObjectColumn_reference_SqlExpressionDependencies << V >> {
  - **referencing_id** : (int)
  - **referencing_minor_id** : (int)
  **referenced_id** : (int)
  - **referenced_minor_id** : (int)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_reference_sqlmodules.adoc[]" as reference.RepoObjectColumn_reference_SqlModules << V >> {
  **referencing_id** : (int)
  **referencing_minor_id** : (int)
  **referenced_id** : (int)
  **referenced_minor_id** : (int)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_reference_t.adoc[]" as reference.RepoObjectColumn_reference_T << U >> {
  - **referenced_RepoObjectColumn_guid** : (uniqueidentifier)
  - **referencing_RepoObjectColumn_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_reference_union.adoc[]" as reference.RepoObjectColumn_reference_union << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_reference_virtual.adoc[]" as reference.RepoObjectColumn_reference_virtual << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_referencedlist.adoc[]" as reference.RepoObjectColumn_ReferencedList << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_referencedreferencing.adoc[]" as reference.RepoObjectColumn_ReferencedReferencing << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_referencinglist.adoc[]" as reference.RepoObjectColumn_ReferencingList << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumnsource_virtual.adoc[]" as reference.RepoObjectColumnSource_virtual << U >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  - **Source_RepoObjectColumn_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectsource_virtual.adoc[]" as reference.RepoObjectSource_virtual << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **Source_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.foreignkey_gross.adoc[]" as repo.ForeignKey_gross << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.foreignkey_indexes.adoc[]" as repo.ForeignKey_Indexes << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.foreignkey_indexes_union.adoc[]" as repo.ForeignKey_Indexes_union << V >> {
  **ForeignKey_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.foreignkey_indexes_union_t.adoc[]" as repo.ForeignKey_Indexes_union_T << U >> {
  **ForeignKey_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.foreignkey_indexpattern.adoc[]" as repo.ForeignKey_IndexPattern << V >> {
  - **constraint_object_id** : (int)
  **ForeignKey_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.foreignkey_ssas_indexes.adoc[]" as repo.ForeignKey_ssas_Indexes << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.foreignkey_ssas_indexpattern.adoc[]" as repo.ForeignKey_ssas_IndexPattern << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.foreignkey_virtual.adoc[]" as repo.ForeignKey_virtual << U >> {
  - **ForeignKey_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.foreignkey_virtual_indexes.adoc[]" as repo.ForeignKey_virtual_Indexes << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.index_columlist.adoc[]" as repo.Index_ColumList << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.index_columlist_t.adoc[]" as repo.Index_ColumList_T << U >> {
  - **index_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.index_gross.adoc[]" as repo.Index_gross << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.index_settings.adoc[]" as repo.Index_Settings << U >> {
  - **index_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.index_ssas.adoc[]" as repo.Index_ssas << V >> {
  - **databasename** : (nvarchar(128))
  **index_name** : (nvarchar(450))
  --
}

entity "puml-link:dhw:sqldb:repo.index_ssas_indexpatterncolumnguid.adoc[]" as repo.Index_ssas_IndexPatternColumnGuid << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.index_ssas_t.adoc[]" as repo.Index_ssas_T << U >> {
  - **databasename** : (nvarchar(128))
  - **index_name** : (nvarchar(450))
  --
}

entity "puml-link:dhw:sqldb:repo.index_union.adoc[]" as repo.Index_union << V >> {
  **index_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.index_unique_indexpatterncolumnguid.adoc[]" as repo.Index_unique_IndexPatternColumnGuid << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.index_virtual.adoc[]" as repo.Index_virtual << U >> {
  - **index_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.index_virtual_indexpatterncolumnguid.adoc[]" as repo.Index_virtual_IndexPatternColumnGuid << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.indexcolumn_ssas.adoc[]" as repo.IndexColumn_ssas << V >> {
  - **index_guid** : (uniqueidentifier)
  - **index_column_id** : (int)
  --
}

entity "puml-link:dhw:sqldb:repo.indexcolumn_ssas_gross.adoc[]" as repo.IndexColumn_ssas_gross << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.indexcolumn_ssas_t.adoc[]" as repo.IndexColumn_ssas_T << U >> {
  - **index_guid** : (uniqueidentifier)
  - **index_column_id** : (int)
  --
}

entity "puml-link:dhw:sqldb:repo.indexcolumn_union.adoc[]" as repo.IndexColumn_union << V >> {
  **index_guid** : (uniqueidentifier)
  - **index_column_id** : (int)
  --
}

entity "puml-link:dhw:sqldb:repo.indexcolumn_union_t.adoc[]" as repo.IndexColumn_union_T << U >> {
  - **index_guid** : (uniqueidentifier)
  - **index_column_id** : (int)
  --
}

entity "puml-link:dhw:sqldb:repo.indexcolumn_virtual.adoc[]" as repo.IndexColumn_virtual << U >> {
  - **index_guid** : (uniqueidentifier)
  - **index_column_id** : (int)
  --
}

entity "puml-link:dhw:sqldb:repo.indexcolumn_virtual_gross.adoc[]" as repo.IndexColumn_virtual_gross << V >> {
  - **index_column_id** : (int)
  --
}

entity "puml-link:dhw:sqldb:repo.measure.adoc[]" as repo.Measure << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.measure_union.adoc[]" as repo.Measure_union << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject.adoc[]" as repo.RepoObject << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_external_src.adoc[]" as repo.RepoObject_external_src << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_external_tgt.adoc[]" as repo.RepoObject_external_tgt << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_gross.adoc[]" as repo.RepoObject_gross << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_gross_persistence.adoc[]" as repo.RepoObject_gross_persistence << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_persistence.adoc[]" as repo.RepoObject_persistence << U >> {
  - **target_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_ssas_src.adoc[]" as repo.RepoObject_SSAS_src << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_ssas_tgt.adoc[]" as repo.RepoObject_SSAS_tgt << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn.adoc[]" as repo.RepoObjectColumn << U >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn_external_src.adoc[]" as repo.RepoObjectColumn_external_src << V >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn_external_tgt.adoc[]" as repo.RepoObjectColumn_external_tgt << V >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn_gross.adoc[]" as repo.RepoObjectColumn_gross << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn_gross2.adoc[]" as repo.RepoObjectColumn_gross2 << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn_ssas_src.adoc[]" as repo.RepoObjectColumn_SSAS_src << V >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn_ssas_tgt.adoc[]" as repo.RepoObjectColumn_SSAS_tgt << V >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.reposchema.adoc[]" as repo.RepoSchema << U >> {
  - **RepoSchema_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.reposchema_ssas_src.adoc[]" as repo.RepoSchema_ssas_src << V >> {
  - **RepoSchema_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:repo.reposchema_ssas_tgt.adoc[]" as repo.RepoSchema_ssas_tgt << V >> {
  - **RepoSchema_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.syscolumn_repoobjectcolumn_via_name.adoc[]" as repo.SysColumn_RepoObjectColumn_via_name << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.sysobject_repoobject_via_name.adoc[]" as repo.SysObject_RepoObject_via_name << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo_sys.extendedproperties.adoc[]" as repo_sys.ExtendedProperties << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo_sys.foreignkey.adoc[]" as repo_sys.ForeignKey << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo_sys.foreignkeycolumn.adoc[]" as repo_sys.ForeignKeyColumn << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo_sys.index_unique.adoc[]" as repo_sys.Index_unique << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo_sys.indexcolumn_unique.adoc[]" as repo_sys.IndexColumn_unique << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo_sys.sql_expression_dependencies.adoc[]" as repo_sys.sql_expression_dependencies << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo_sys.syscolumn.adoc[]" as repo_sys.SysColumn << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo_sys.sysobject.adoc[]" as repo_sys.SysObject << V >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.ftv_sqlparse.adoc[]" as sqlparse.ftv_sqlparse << IF >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.ftv_sqlparse_children_pivot.adoc[]" as sqlparse.ftv_sqlparse_children_pivot << IF >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.ftv_sqlparse_with_some_children.adoc[]" as sqlparse.ftv_sqlparse_with_some_children << IF >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules.adoc[]" as sqlparse.RepoObject_SqlModules << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_10_statement.adoc[]" as sqlparse.RepoObject_SqlModules_10_statement << V >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_20_statement_children.adoc[]" as sqlparse.RepoObject_SqlModules_20_statement_children << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **json_key** : (nvarchar(4000))
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_21_statement_children_helper.adoc[]" as sqlparse.RepoObject_SqlModules_21_statement_children_helper << V >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_22_identifier_alias_as.adoc[]" as sqlparse.RepoObject_SqlModules_22_identifier_alias_AS << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **json_key** : (nvarchar(4000))
  **RowNumber** : (bigint)
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_24_identifierlist_children.adoc[]" as sqlparse.RepoObject_SqlModules_24_IdentifierList_children << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **json_key** : (nvarchar(4000))
  - **T2_json_key** : (nvarchar(4000))
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_25_identifierlist_children_identifiersplit.adoc[]" as sqlparse.RepoObject_SqlModules_25_IdentifierList_children_IdentifierSplit << V >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_26_identifierlist_children_identifiersplit_quotename.adoc[]" as sqlparse.RepoObject_SqlModules_26_IdentifierList_children_IdentifierSplit_QuoteName << V >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_29_1_object_is_union.adoc[]" as sqlparse.RepoObject_SqlModules_29_1_object_is_union << V >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_29_2_object_is_groupby.adoc[]" as sqlparse.RepoObject_SqlModules_29_2_object_is_GroupBy << V >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_31_object.adoc[]" as sqlparse.RepoObject_SqlModules_31_object << V >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_32_objectclass.adoc[]" as sqlparse.RepoObject_SqlModules_32_ObjectClass << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  **class** : (nvarchar(500))
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_33_objectnormalized.adoc[]" as sqlparse.RepoObject_SqlModules_33_ObjectNormalized << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  **normalized** : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_39_object.adoc[]" as sqlparse.RepoObject_SqlModules_39_object << V >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_41_from.adoc[]" as sqlparse.RepoObject_SqlModules_41_from << V >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_41_from_t.adoc[]" as sqlparse.RepoObject_SqlModules_41_from_T << U >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_42_from_identifier.adoc[]" as sqlparse.RepoObject_SqlModules_42_from_Identifier << V >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_43_from_identifier.adoc[]" as sqlparse.RepoObject_SqlModules_43_from_Identifier << V >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_44_from_identifier_quotename.adoc[]" as sqlparse.RepoObject_SqlModules_44_from_Identifier_QuoteName << V >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_51_identitfier.adoc[]" as sqlparse.RepoObject_SqlModules_51_Identitfier << V >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_52_identitfier_quotename.adoc[]" as sqlparse.RepoObject_SqlModules_52_Identitfier_QuoteName << V >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_61_selectidentifier_union.adoc[]" as sqlparse.RepoObject_SqlModules_61_SelectIdentifier_Union << V >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_61_selectidentifier_union_t.adoc[]" as sqlparse.RepoObject_SqlModules_61_SelectIdentifier_Union_T << U >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_71_reference_explicitetablealias.adoc[]" as sqlparse.RepoObject_SqlModules_71_reference_ExpliciteTableAlias << V >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_72_reference_notablealias.adoc[]" as sqlparse.RepoObject_SqlModules_72_reference_NoTableAlias << V >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_79_reference_union.adoc[]" as sqlparse.RepoObject_SqlModules_79_reference_union << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.additional_reference_step1.adoc[]" as ssas.additional_Reference_step1 << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.indexcolumn_from_iskey.adoc[]" as ssas.IndexColumn_from_IsKey << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.indexcolumn_from_isunique.adoc[]" as ssas.IndexColumn_from_IsUnique << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.indexcolumn_from_relationship.adoc[]" as ssas.IndexColumn_from_Relationship << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.indexcolumn_union.adoc[]" as ssas.IndexColumn_union << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.measure_translation.adoc[]" as ssas.Measure_translation << V >> {
  - **Measure_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  **RepoObject_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.measure_translation_displayfolder_union.adoc[]" as ssas.Measure_translation_displayfolder_union << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.measure_translation_t.adoc[]" as ssas.Measure_translation_T << U >> {
  - **Measure_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  - **RepoObject_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json.adoc[]" as ssas.model_json << U >> {
  - **databasename** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_10.adoc[]" as ssas.model_json_10 << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_20.adoc[]" as ssas.model_json_20 << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_201_descriptions_multiline.adoc[]" as ssas.model_json_201_descriptions_multiline << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_2011_descriptions_stragg.adoc[]" as ssas.model_json_2011_descriptions_StrAgg << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31_tables.adoc[]" as ssas.model_json_31_tables << V >> {
  - **databasename** : (nvarchar(128))
  **tables_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31_tables_t.adoc[]" as ssas.model_json_31_tables_T << U >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_311_tables_columns.adoc[]" as ssas.model_json_311_tables_columns << V >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  **tables_columns_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_311_tables_columns_t.adoc[]" as ssas.model_json_311_tables_columns_T << U >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  - **tables_columns_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_3111_tables_columns_descriptions_multiline.adoc[]" as ssas.model_json_3111_tables_columns_descriptions_multiline << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31111_tables_columns_descriptions_stragg.adoc[]" as ssas.model_json_31111_tables_columns_descriptions_StrAgg << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_3112_tables_columns_expressions_multiline.adoc[]" as ssas.model_json_3112_tables_columns_expressions_multiline << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31121_tables_columns_expressions_stragg.adoc[]" as ssas.model_json_31121_tables_columns_expressions_StrAgg << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_312_tables_measures.adoc[]" as ssas.model_json_312_tables_measures << V >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  **tables_measures_name** : (nvarchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_312_tables_measures_t.adoc[]" as ssas.model_json_312_tables_measures_T << U >> {
  - **Measure_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_3121_tables_columns_descriptions_multiline.adoc[]" as ssas.model_json_3121_tables_columns_descriptions_multiline << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31211_tables_columns_descriptions_stragg.adoc[]" as ssas.model_json_31211_tables_columns_descriptions_StrAgg << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_3122_tables_measures_expressions_multiline.adoc[]" as ssas.model_json_3122_tables_measures_expressions_multiline << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31221_tables_measures_expressions_stragg.adoc[]" as ssas.model_json_31221_tables_measures_expressions_StrAgg << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_313_tables_partitions.adoc[]" as ssas.model_json_313_tables_partitions << V >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  **tables_partitions_name** : (nvarchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_3131_tables_partitions_source.adoc[]" as ssas.model_json_3131_tables_partitions_source << V >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  **tables_partitions_name** : (nvarchar(500))
  **tables_partitions_source_name** : (nvarchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31311_tables_partitions_source_posfrom.adoc[]" as ssas.model_json_31311_tables_partitions_source_PosFrom << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_313111_tables_partitions_source_stringfrom.adoc[]" as ssas.model_json_313111_tables_partitions_source_StringFrom << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_3131111_tables_partitions_source_posdot.adoc[]" as ssas.model_json_3131111_tables_partitions_source_PosDot << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31311111_tables_partitions_source_part123.adoc[]" as ssas.model_json_31311111_tables_partitions_source_Part123 << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_316_tables_descriptions_multiline.adoc[]" as ssas.model_json_316_tables_descriptions_multiline << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_3161_tables_descriptions_stragg.adoc[]" as ssas.model_json_3161_tables_descriptions_StrAgg << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_32_relationships.adoc[]" as ssas.model_json_32_relationships << V >> {
  - **databasename** : (nvarchar(128))
  **relationships_name** : (nvarchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_32_relationships_t.adoc[]" as ssas.model_json_32_relationships_T << U >> {
  - **ForeignKey_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_33_datasources.adoc[]" as ssas.model_json_33_dataSources << V >> {
  - **databasename** : (nvarchar(128))
  **dataSources_name** : (nvarchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_33_datasources_t.adoc[]" as ssas.model_json_33_dataSources_T << U >> {
  - **databasename** : (nvarchar(128))
  - **dataSources_name** : (nvarchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_34_cultures.adoc[]" as ssas.model_json_34_cultures << V >> {
  - **databasename** : (nvarchar(128))
  **cultures_name** : (nvarchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_341_cultures_translations.adoc[]" as ssas.model_json_341_cultures_translations << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_3411_cultures_translations_model.adoc[]" as ssas.model_json_3411_cultures_translations_model << V >> {
  - **databasename** : (nvarchar(128))
  **cultures_name** : (nvarchar(500))
  **cultures_translations_model_name** : (nvarchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_3411_cultures_translations_model_t.adoc[]" as ssas.model_json_3411_cultures_translations_model_T << U >> {
  - **databasename** : (nvarchar(128))
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_34111_cultures_translations_model_tables.adoc[]" as ssas.model_json_34111_cultures_translations_model_tables << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_341111_cultures_translations_model_tables_columns.adoc[]" as ssas.model_json_341111_cultures_translations_model_tables_columns << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_341113_cultures_translations_model_tables_measures.adoc[]" as ssas.model_json_341113_cultures_translations_model_tables_measures << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.repoobjectcolumn_translation.adoc[]" as ssas.RepoObjectColumn_translation << V >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:ssas.repoobjectcolumn_translation_displayfolder_union.adoc[]" as ssas.RepoObjectColumn_translation_displayfolder_union << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.repoobjectcolumn_translation_t.adoc[]" as ssas.RepoObjectColumn_translation_T << U >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.columns.adoc[]" as sys_dwh.columns << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.computed_columns.adoc[]" as sys_dwh.computed_columns << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.default_constraints.adoc[]" as sys_dwh.default_constraints << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.extended_properties.adoc[]" as sys_dwh.extended_properties << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.foreign_key_columns.adoc[]" as sys_dwh.foreign_key_columns << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.foreign_keys.adoc[]" as sys_dwh.foreign_keys << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.identity_columns.adoc[]" as sys_dwh.identity_columns << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.index_columns.adoc[]" as sys_dwh.index_columns << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.indexes.adoc[]" as sys_dwh.indexes << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.objects.adoc[]" as sys_dwh.objects << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.parameters.adoc[]" as sys_dwh.parameters << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.schemas.adoc[]" as sys_dwh.schemas << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.sql_expression_dependencies.adoc[]" as sys_dwh.sql_expression_dependencies << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.sql_modules.adoc[]" as sys_dwh.sql_modules << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.tables.adoc[]" as sys_dwh.tables << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.types.adoc[]" as sys_dwh.types << SN >> {
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.generatorusp.adoc[]" as uspgenerator.GeneratorUsp << U >> {
  - **id** : (int)
  --
}

config.ftv_dwh_database <.. repo_sys.SysColumn
config.ftv_dwh_database <.. repo_sys.sql_expression_dependencies
config.ftv_dwh_database <.. repo_sys.ExtendedProperties
config.ftv_get_parameter_value <.. repo.RepoObject_external_src
config.ftv_get_parameter_value <.. repo.RepoObject_gross
config.ftv_get_parameter_value <.. docs.fs_PumlHeaderLeftToRight
config.ftv_get_parameter_value <.. docs.Schema_puml
config.ftv_get_parameter_value <.. ssas.additional_Reference_step1
config.ftv_get_parameter_value <.. reference.additional_Reference_is_external
config.Parameter <.. config.ftv_dwh_database
config.Parameter <.. property.PropertyName_RepoObject
config.Parameter <.. config.ftv_get_parameter_value
configT.join_type <.. sqlparse.RepoObject_SqlModules_41_from
configT.Parameter_default <.. config.Parameter
configT.spt_values <.. configT.type
configT.type <.. repo.RepoObject_gross_persistence
configT.type <.. reference.RepoObject_ReferencedReferencing
configT.type <.. repo.RepoObject_gross
docs.Culture <.. ssas.Measure_translation
docs.Culture <.. ssas.RepoObjectColumn_translation
docs.Culture <.. docs.RepoObject_OutputFilter
docs.fs_cleanStringForAnchorId <.. reference.RepoObjectColumn_ReferencedReferencing
docs.fs_cleanStringForAnchorId <.. docs.RepoObject_ColumnList
docs.fs_cleanStringForAnchorId <.. docs.RepoObject_IndexList
docs.fs_cleanStringForAnchorId <.. repo.ForeignKey_gross
docs.fs_cleanStringForAnchorId <.. docs.RepoObject_MeasureList
docs.fs_cleanStringForFilename <.. repo.RepoObject_gross
docs.fs_cleanStringForFilename <.. reference.RepoObject_ReferencedReferencing
docs.fs_cleanStringForFilename <.. repo.ForeignKey_gross
docs.fs_cleanStringForFilename <.. docs.RepoObject_OutputFilter
docs.fs_cleanStringForFilename <.. reference.RepoObjectColumn_ReferencedReferencing
docs.fs_cleanStringForFilename <.. repo.RepoObject_gross_persistence
docs.fs_cleanStringForFilename <.. docs.RepoObject_OutputFilter_T_gross
docs.fs_cleanStringForHeader <.. docs.RepoObject_MeasureList
docs.fs_cleanStringForHeader <.. docs.RepoObject_ColumnList
docs.fs_cleanStringForHeader <.. docs.RepoObject_IndexList
docs.fs_cleanStringForPuml <.. docs.RepoObject_OutputFilter
docs.fs_cleanStringForPuml <.. docs.Schema_PumlPartial_FkRefList
docs.fs_cleanStringForPuml <.. docs.RepoObject_MeasureList
docs.fs_cleanStringForPuml <.. docs.RepoObject_ColumnList
docs.fs_cleanStringForPuml <.. docs.RepoObject_IndexList
docs.fs_cleanStringForPuml <.. docs.ssas_PumlRelation
docs.fs_PumlHeaderLeftToRight <.. docs.Schema_puml
docs.Measure_MeasurePropertyList <.. docs.RepoObject_MeasureList
docs.RepoObject_ColumnList <.. docs.RepoObject_ColumnList_T
docs.RepoObject_ColumnList_T <.. docs.RepoObject_Plantuml_Entity
docs.RepoObject_IndexList <.. docs.RepoObject_IndexList_T
docs.RepoObject_IndexList_T <.. docs.RepoObject_Plantuml_Entity
docs.RepoObject_MeasureList <.. docs.RepoObject_Plantuml_Entity
docs.RepoObject_OutputFilter <.. docs.RepoObject_OutputFilter_T
docs.RepoObject_OutputFilter_T <.. docs.RepoObject_ColumnList
docs.RepoObject_OutputFilter_T <.. docs.RepoObject_Plantuml_Entity
docs.RepoObject_OutputFilter_T <.. docs.RepoObject_OutputFilter_T_gross
docs.RepoObject_OutputFilter_T <.. docs.RepoObject_IndexList
docs.RepoObject_OutputFilter_T <.. docs.Schema_SsasRelationList
docs.RepoObject_OutputFilter_T <.. docs.Schema_puml
docs.RepoObject_OutputFilter_T_gross <.. docs.RepoObject_MeasureList
docs.RepoObject_Plantuml_Entity <.. docs.RepoObject_Plantuml_Entity_T
docs.RepoObject_Plantuml_Entity_T <.. docs.Schema_EntityList
docs.Schema_EntityList <.. docs.Schema_puml
docs.Schema_PumlPartial_FkRefList <.. docs.Schema_puml
docs.Schema_SsasRelationList <.. docs.Schema_puml
docs.ssas_PumlRelation <.. docs.Schema_SsasRelationList
property.external_RepoObjectColumnProperty <.. property.RepoObjectColumnProperty_external_src
property.external_RepoObjectProperty <.. property.RepoObjectProperty_external_src
property.fs_get_RepoObjectColumnProperty_nvarchar <.. repo.RepoObjectColumn_gross
property.fs_get_RepoObjectProperty_nvarchar <.. repo.RepoObject_gross
property.MeasureProperty <.. docs.Measure_MeasurePropertyList
property.MeasureProperty <.. property.PropertyName_Measure
property.PropertyName_Measure <.. property.PropertyName_Measure_T
property.PropertyName_Measure_T <.. docs.Measure_MeasurePropertyList
property.PropertyName_RepoObject <.. property.PropertyName_RepoObject_T
property.PropertyName_RepoObject_T <.. property.RepoObjectColumnProperty_external_tgt
property.PropertyName_RepoObject_T <.. property.RepoObjectProperty_external_tgt
property.RepoObjectColumnProperty <.. property.fs_get_RepoObjectColumnProperty_nvarchar
property.RepoObjectColumnProperty_external_src <.. property.RepoObjectColumnProperty_external_tgt
property.RepoObjectColumnProperty_external_tgt <.. property.RepoObjectColumnProperty
property.RepoObjectProperty <.. property.fs_get_RepoObjectProperty_nvarchar
property.RepoObjectProperty <.. property.RepoObjectProperty_SelectedPropertyName_split
property.RepoObjectProperty <.. property.PropertyName_RepoObject
property.RepoObjectProperty_external_src <.. property.RepoObjectProperty_external_tgt
property.RepoObjectProperty_external_tgt <.. property.RepoObjectProperty
property.RepoObjectProperty_SelectedPropertyName_split <.. reference.additional_Reference_wo_columns_from_properties_src
property.RepoObjectProperty_SelectedPropertyName_split <.. reference.additional_Reference_from_properties_src
reference.additional_Reference <.. reference.additional_Reference_guid
reference.additional_Reference <.. reference.additional_Reference_is_external
reference.additional_Reference_database <.. reference.additional_Reference_database_T
reference.additional_Reference_database_T <.. repo.RepoObject_gross
reference.additional_Reference_from_properties_src <.. reference.additional_Reference_from_properties_tgt
reference.additional_Reference_from_properties_tgt <.. reference.additional_Reference
reference.additional_Reference_from_ssas_src <.. reference.additional_Reference_from_ssas_tgt
reference.additional_Reference_from_ssas_tgt <.. reference.additional_Reference
reference.additional_Reference_guid <.. reference.RepoObject_reference_additional
reference.additional_Reference_guid <.. reference.RepoObjectColumn_reference_additional
reference.additional_Reference_is_external <.. reference.additional_Reference_ObjectColumn
reference.additional_Reference_is_external <.. reference.additional_Reference_database
reference.additional_Reference_is_external <.. reference.additional_Reference_Object
reference.additional_Reference_Object <.. reference.additional_Reference_Object_T
reference.additional_Reference_Object_T <.. repo.RepoObject_external_src
reference.additional_Reference_Object_T <.. repo.RepoObjectColumn_external_src
reference.additional_Reference_ObjectColumn <.. reference.additional_Reference_ObjectColumn_T
reference.additional_Reference_ObjectColumn_T <.. repo.RepoObjectColumn_external_src
reference.additional_Reference_wo_columns_from_properties_src <.. reference.additional_Reference_wo_columns_from_properties_tgt
reference.additional_Reference_wo_columns_from_properties_tgt <.. reference.additional_Reference
reference.RepoObject_QueryPlan <.. repo.RepoObject_gross
reference.RepoObject_reference <.. reference.RepoObject_reference_T
reference.RepoObject_reference_additional <.. reference.RepoObject_reference_union
reference.RepoObject_reference_persistence <.. reference.RepoObject_reference_union
reference.RepoObject_reference_persistence_target_as_source <.. reference.RepoObject_reference
reference.RepoObject_reference_persistence_target_as_source <.. reference.RepoObject_reference_union
reference.RepoObject_reference_persistence_target_as_source_explicit <.. reference.RepoObject_reference_union
reference.RepoObject_reference_persistence_target_as_source_explicit <.. reference.RepoObject_reference
reference.RepoObject_reference_SqlExpressionDependencies <.. reference.RepoObject_reference_persistence_target_as_source_explicit
reference.RepoObject_reference_SqlExpressionDependencies <.. reference.RepoObject_reference_persistence_target_as_source
reference.RepoObject_reference_SqlExpressionDependencies <.. reference.RepoObject_reference_union
reference.RepoObject_reference_T <.. reference.RepoObject_ReferencedReferencing
reference.RepoObject_reference_T <.. reference.RepoObjectColumn_reference_SqlExpressionDependencies
reference.RepoObject_reference_T <.. reference.RepoObjectColumn_reference_virtual
reference.RepoObject_reference_T <.. reference.RepoObjectColumn_reference_additional
reference.RepoObject_reference_union <.. reference.RepoObject_reference
reference.RepoObject_reference_virtual <.. reference.RepoObject_reference_union
reference.RepoObject_ReferencedReferencing <.. repo.RepoObject_gross
reference.RepoObjectColumn_reference <.. reference.RepoObjectColumn_reference_T
reference.RepoObjectColumn_reference_additional <.. reference.RepoObjectColumn_reference_union
reference.RepoObjectColumn_reference_Persistence <.. reference.RepoObjectColumn_reference_union
reference.RepoObjectColumn_reference_SqlExpressionDependencies <.. reference.RepoObjectColumn_reference_union
reference.RepoObjectColumn_reference_SqlModules <.. reference.RepoObjectColumn_reference_union
reference.RepoObjectColumn_reference_T <.. reference.RepoObjectColumn_ReferencedReferencing
reference.RepoObjectColumn_reference_union <.. reference.RepoObjectColumn_reference
reference.RepoObjectColumn_reference_virtual <.. reference.RepoObjectColumn_reference_union
reference.RepoObjectColumn_ReferencedList <.. repo.RepoObjectColumn_gross2
reference.RepoObjectColumn_ReferencedReferencing <.. reference.RepoObjectColumn_ReferencingList
reference.RepoObjectColumn_ReferencedReferencing <.. reference.RepoObjectColumn_ReferencedList
reference.RepoObjectColumn_ReferencingList <.. repo.RepoObjectColumn_gross2
reference.RepoObjectColumnSource_virtual <.. reference.RepoObjectColumn_reference_virtual
reference.RepoObjectSource_virtual <.. reference.RepoObject_reference_virtual
repo.ForeignKey_gross <.. docs.RepoObject_IndexList
repo.ForeignKey_Indexes <.. repo.ForeignKey_Indexes_union
repo.ForeignKey_Indexes_union <.. repo.ForeignKey_Indexes_union_T
repo.ForeignKey_Indexes_union_T <.. repo.ForeignKey_gross
repo.ForeignKey_Indexes_union_T <.. docs.Schema_PumlPartial_FkRefList
repo.ForeignKey_IndexPattern <.. repo.ForeignKey_Indexes
repo.ForeignKey_ssas_Indexes <.. repo.ForeignKey_Indexes_union
repo.ForeignKey_ssas_IndexPattern <.. docs.ssas_PumlRelation
repo.ForeignKey_ssas_IndexPattern <.. repo.ForeignKey_ssas_Indexes
repo.ForeignKey_virtual <.. repo.ForeignKey_virtual_Indexes
repo.ForeignKey_virtual_Indexes <.. repo.ForeignKey_Indexes_union
repo.Index_ColumList <.. repo.Index_ColumList_T
repo.Index_ColumList_T <.. repo.Index_gross
repo.Index_gross <.. repo.ForeignKey_virtual_Indexes
repo.Index_gross <.. repo.ForeignKey_Indexes
repo.Index_gross <.. docs.RepoObject_IndexList
repo.Index_gross <.. repo.ForeignKey_gross
repo.Index_Settings <.. repo.RepoObject_gross
repo.Index_Settings <.. repo.Index_gross
repo.Index_ssas <.. repo.Index_ssas_T
repo.Index_ssas_IndexPatternColumnGuid <.. repo.Index_union
repo.Index_ssas_T <.. repo.Index_union
repo.Index_ssas_T <.. repo.IndexColumn_ssas
repo.Index_ssas_T <.. repo.IndexColumn_ssas_gross
repo.Index_ssas_T <.. repo.ForeignKey_ssas_Indexes
repo.Index_ssas_T <.. repo.Index_ssas_IndexPatternColumnGuid
repo.Index_union <.. repo.Index_gross
repo.Index_unique_IndexPatternColumnGuid <.. repo.Index_union
repo.Index_virtual <.. repo.IndexColumn_virtual_gross
repo.Index_virtual <.. repo.Index_union
repo.Index_virtual <.. repo.Index_virtual_IndexPatternColumnGuid
repo.Index_virtual_IndexPatternColumnGuid <.. repo.Index_union
repo.IndexColumn_ssas <.. repo.IndexColumn_ssas_T
repo.IndexColumn_ssas_gross <.. repo.IndexColumn_union
repo.IndexColumn_ssas_T <.. repo.Index_ssas_IndexPatternColumnGuid
repo.IndexColumn_ssas_T <.. repo.IndexColumn_ssas_gross
repo.IndexColumn_union <.. repo.IndexColumn_union_T
repo.IndexColumn_union_T <.. repo.Index_ColumList
repo.IndexColumn_union_T <.. repo.RepoObjectColumn_gross2
repo.IndexColumn_virtual <.. repo.Index_virtual_IndexPatternColumnGuid
repo.IndexColumn_virtual <.. repo.IndexColumn_virtual_gross
repo.IndexColumn_virtual_gross <.. repo.IndexColumn_union
repo.Measure <.. docs.Measure_MeasurePropertyList
repo.Measure <.. repo.Measure_union
repo.Measure_union <.. ssas.Measure_translation
repo.Measure_union <.. docs.RepoObject_MeasureList
repo.RepoObject <.. reference.RepoObject_reference_persistence
repo.RepoObject <.. repo.SysObject_RepoObject_via_name
repo.RepoObject <.. repo.SysColumn_RepoObjectColumn_via_name
repo.RepoObject <.. repo_sys.Index_unique
repo.RepoObject <.. reference.RepoObjectColumn_reference_Persistence
repo.RepoObject <.. repo.IndexColumn_virtual_gross
repo.RepoObject <.. sqlparse.RepoObject_SqlModules_10_statement
repo.RepoObject <.. sqlparse.RepoObject_SqlModules_39_object
repo.RepoObject <.. repo.RepoObject_gross_persistence
repo.RepoObject <.. reference.RepoObject_reference_persistence_target_as_source_explicit
repo.RepoObject <.. property.RepoObjectProperty_external_tgt
repo.RepoObject <.. repo.IndexColumn_ssas_gross
repo.RepoObject <.. property.RepoObjectColumnProperty_external_tgt
repo.RepoObject <.. repo.RepoObjectColumn_external_src
repo.RepoObject <.. repo.RepoObject_external_src
repo.RepoObject <.. reference.RepoObject_reference_virtual
repo.RepoObject <.. reference.additional_Reference_guid
repo.RepoObject <.. reference.RepoObject_reference_SqlExpressionDependencies
repo.RepoObject <.. repo.RepoObjectColumn_gross
repo.RepoObject <.. repo.RepoObject_gross
repo.RepoObject <.. sqlparse.RepoObject_SqlModules_72_reference_NoTableAlias
repo.RepoObject <.. sqlparse.RepoObject_SqlModules_71_reference_ExpliciteTableAlias
repo.RepoObject <.. repo_sys.ForeignKey
repo.RepoObject <.. reference.RepoObjectColumn_reference_SqlModules
repo.RepoObject_external_src <.. repo.RepoObject_external_tgt
repo.RepoObject_external_tgt <.. repo.RepoObject
repo.RepoObject_external_tgt <.. repo.RepoObjectColumn_external_tgt
repo.RepoObject_gross <.. repo.Index_gross
repo.RepoObject_gross <.. docs.RepoObject_OutputFilter
repo.RepoObject_gross_persistence <.. reference.RepoObject_reference_persistence_target_as_source
repo.RepoObject_persistence <.. repo.RepoObject_gross
repo.RepoObject_persistence <.. repo.RepoObject_gross_persistence
repo.RepoObject_persistence <.. reference.RepoObject_reference_persistence_target_as_source_explicit
repo.RepoObject_persistence <.. reference.RepoObject_reference_persistence
repo.RepoObject_persistence <.. repo.RepoObjectColumn_gross
repo.RepoObject_persistence <.. reference.RepoObjectColumn_reference_Persistence
repo.RepoObject_SSAS_src <.. repo.RepoObject_SSAS_tgt
repo.RepoObject_SSAS_tgt <.. repo.RepoObjectColumn_SSAS_tgt
repo.RepoObject_SSAS_tgt <.. repo.RepoObject
repo.RepoObjectColumn <.. repo.SysColumn_RepoObjectColumn_via_name
repo.RepoObjectColumn <.. repo.RepoObjectColumn_gross
repo.RepoObjectColumn <.. sqlparse.RepoObject_SqlModules_71_reference_ExpliciteTableAlias
repo.RepoObjectColumn <.. repo.IndexColumn_virtual_gross
repo.RepoObjectColumn <.. reference.RepoObjectColumn_reference_Persistence
repo.RepoObjectColumn <.. repo.IndexColumn_ssas_gross
repo.RepoObjectColumn <.. reference.RepoObjectColumn_reference_SqlModules
repo.RepoObjectColumn <.. sqlparse.RepoObject_SqlModules_72_reference_NoTableAlias
repo.RepoObjectColumn <.. reference.additional_Reference_guid
repo.RepoObjectColumn <.. repo.RepoObjectColumn_gross2
repo.RepoObjectColumn <.. property.RepoObjectColumnProperty_external_tgt
repo.RepoObjectColumn_external_src <.. repo.RepoObjectColumn_external_tgt
repo.RepoObjectColumn_external_tgt <.. repo.RepoObjectColumn
repo.RepoObjectColumn_gross <.. ssas.RepoObjectColumn_translation
repo.RepoObjectColumn_gross <.. repo.RepoObjectColumn_gross2
repo.RepoObjectColumn_gross <.. reference.RepoObjectColumn_reference_virtual
repo.RepoObjectColumn_gross2 <.. docs.RepoObject_ColumnList
repo.RepoObjectColumn_SSAS_src <.. repo.RepoObjectColumn_SSAS_tgt
repo.RepoObjectColumn_SSAS_tgt <.. repo.RepoObjectColumn
repo.RepoSchema <.. docs.Schema_puml
repo.RepoSchema <.. repo.Measure
repo.RepoSchema <.. repo.RepoObject_SSAS_src
repo.RepoSchema_ssas_src <.. repo.RepoSchema_ssas_tgt
repo.RepoSchema_ssas_tgt <.. repo.RepoSchema
repo.SysColumn_RepoObjectColumn_via_name <.. repo_sys.sql_expression_dependencies
repo.SysColumn_RepoObjectColumn_via_name <.. repo_sys.IndexColumn_unique
repo.SysObject_RepoObject_via_name <.. repo_sys.sql_expression_dependencies
repo.SysObject_RepoObject_via_name <.. repo_sys.IndexColumn_unique
repo_sys.ExtendedProperties <.. repo_sys.SysObject
repo_sys.ExtendedProperties <.. repo_sys.SysColumn
repo_sys.ForeignKey <.. repo_sys.ForeignKeyColumn
repo_sys.ForeignKey <.. repo.ForeignKey_IndexPattern
repo_sys.ForeignKeyColumn <.. repo.ForeignKey_IndexPattern
repo_sys.Index_unique <.. repo.Index_union
repo_sys.IndexColumn_unique <.. repo.IndexColumn_union
repo_sys.IndexColumn_unique <.. repo.Index_unique_IndexPatternColumnGuid
repo_sys.sql_expression_dependencies <.. reference.RepoObjectColumn_reference_SqlExpressionDependencies
repo_sys.sql_expression_dependencies <.. reference.RepoObject_reference_SqlExpressionDependencies
repo_sys.SysColumn <.. repo.SysColumn_RepoObjectColumn_via_name
repo_sys.SysColumn <.. repo_sys.ForeignKeyColumn
repo_sys.SysObject <.. repo_sys.SysColumn
repo_sys.SysObject <.. repo.SysObject_RepoObject_via_name
sqlparse.ftv_sqlparse <.. sqlparse.RepoObject_SqlModules_22_identifier_alias_AS
sqlparse.ftv_sqlparse_children_pivot <.. sqlparse.RepoObject_SqlModules_25_IdentifierList_children_IdentifierSplit
sqlparse.ftv_sqlparse_with_some_children <.. sqlparse.RepoObject_SqlModules_24_IdentifierList_children
sqlparse.ftv_sqlparse_with_some_children <.. sqlparse.RepoObject_SqlModules_20_statement_children
sqlparse.RepoObject_SqlModules <.. sqlparse.RepoObject_SqlModules_39_object
sqlparse.RepoObject_SqlModules <.. sqlparse.RepoObject_SqlModules_10_statement
sqlparse.RepoObject_SqlModules_10_statement <.. sqlparse.RepoObject_SqlModules_20_statement_children
sqlparse.RepoObject_SqlModules_20_statement_children <.. sqlparse.RepoObject_SqlModules_32_ObjectClass
sqlparse.RepoObject_SqlModules_20_statement_children <.. sqlparse.RepoObject_SqlModules_29_2_object_is_GroupBy
sqlparse.RepoObject_SqlModules_20_statement_children <.. sqlparse.RepoObject_SqlModules_21_statement_children_helper
sqlparse.RepoObject_SqlModules_20_statement_children <.. sqlparse.RepoObject_SqlModules_29_1_object_is_union
sqlparse.RepoObject_SqlModules_20_statement_children <.. sqlparse.RepoObject_SqlModules_51_Identitfier
sqlparse.RepoObject_SqlModules_20_statement_children <.. sqlparse.RepoObject_SqlModules_33_ObjectNormalized
sqlparse.RepoObject_SqlModules_20_statement_children <.. sqlparse.RepoObject_SqlModules_22_identifier_alias_AS
sqlparse.RepoObject_SqlModules_20_statement_children <.. sqlparse.RepoObject_SqlModules_24_IdentifierList_children
sqlparse.RepoObject_SqlModules_20_statement_children <.. sqlparse.RepoObject_SqlModules_41_from
sqlparse.RepoObject_SqlModules_21_statement_children_helper <.. sqlparse.RepoObject_SqlModules_31_object
sqlparse.RepoObject_SqlModules_22_identifier_alias_AS <.. sqlparse.RepoObject_SqlModules_41_from
sqlparse.RepoObject_SqlModules_24_IdentifierList_children <.. sqlparse.RepoObject_SqlModules_25_IdentifierList_children_IdentifierSplit
sqlparse.RepoObject_SqlModules_25_IdentifierList_children_IdentifierSplit <.. sqlparse.RepoObject_SqlModules_26_IdentifierList_children_IdentifierSplit_QuoteName
sqlparse.RepoObject_SqlModules_26_IdentifierList_children_IdentifierSplit_QuoteName <.. sqlparse.RepoObject_SqlModules_61_SelectIdentifier_Union
sqlparse.RepoObject_SqlModules_29_1_object_is_union <.. sqlparse.RepoObject_SqlModules_42_from_Identifier
sqlparse.RepoObject_SqlModules_29_1_object_is_union <.. sqlparse.RepoObject_SqlModules_39_object
sqlparse.RepoObject_SqlModules_29_2_object_is_GroupBy <.. sqlparse.RepoObject_SqlModules_39_object
sqlparse.RepoObject_SqlModules_31_object <.. sqlparse.RepoObject_SqlModules_39_object
sqlparse.RepoObject_SqlModules_32_ObjectClass <.. sqlparse.RepoObject_SqlModules_39_object
sqlparse.RepoObject_SqlModules_33_ObjectNormalized <.. sqlparse.RepoObject_SqlModules_39_object
sqlparse.RepoObject_SqlModules_39_object <.. sqlparse.RepoObject_SqlModules_61_SelectIdentifier_Union
sqlparse.RepoObject_SqlModules_39_object <.. sqlparse.RepoObject_SqlModules_41_from
sqlparse.RepoObject_SqlModules_41_from <.. sqlparse.RepoObject_SqlModules_41_from_T
sqlparse.RepoObject_SqlModules_41_from_T <.. sqlparse.RepoObject_SqlModules_42_from_Identifier
sqlparse.RepoObject_SqlModules_42_from_Identifier <.. sqlparse.RepoObject_SqlModules_43_from_Identifier
sqlparse.RepoObject_SqlModules_43_from_Identifier <.. sqlparse.RepoObject_SqlModules_44_from_Identifier_QuoteName
sqlparse.RepoObject_SqlModules_44_from_Identifier_QuoteName <.. sqlparse.RepoObject_SqlModules_71_reference_ExpliciteTableAlias
sqlparse.RepoObject_SqlModules_44_from_Identifier_QuoteName <.. sqlparse.RepoObject_SqlModules_72_reference_NoTableAlias
sqlparse.RepoObject_SqlModules_51_Identitfier <.. sqlparse.RepoObject_SqlModules_52_Identitfier_QuoteName
sqlparse.RepoObject_SqlModules_52_Identitfier_QuoteName <.. sqlparse.RepoObject_SqlModules_61_SelectIdentifier_Union
sqlparse.RepoObject_SqlModules_61_SelectIdentifier_Union <.. sqlparse.RepoObject_SqlModules_61_SelectIdentifier_Union_T
sqlparse.RepoObject_SqlModules_61_SelectIdentifier_Union_T <.. sqlparse.RepoObject_SqlModules_71_reference_ExpliciteTableAlias
sqlparse.RepoObject_SqlModules_61_SelectIdentifier_Union_T <.. sqlparse.RepoObject_SqlModules_72_reference_NoTableAlias
sqlparse.RepoObject_SqlModules_71_reference_ExpliciteTableAlias <.. sqlparse.RepoObject_SqlModules_79_reference_union
sqlparse.RepoObject_SqlModules_72_reference_NoTableAlias <.. sqlparse.RepoObject_SqlModules_79_reference_union
sqlparse.RepoObject_SqlModules_79_reference_union <.. reference.RepoObjectColumn_reference_SqlModules
ssas.additional_Reference_step1 <.. reference.additional_Reference_from_ssas_src
ssas.IndexColumn_from_IsKey <.. ssas.IndexColumn_union
ssas.IndexColumn_from_IsUnique <.. ssas.IndexColumn_union
ssas.IndexColumn_from_Relationship <.. ssas.IndexColumn_union
ssas.IndexColumn_union <.. repo.IndexColumn_ssas
ssas.IndexColumn_union <.. repo.Index_ssas
ssas.Measure_translation <.. ssas.Measure_translation_T
ssas.Measure_translation_displayfolder_union <.. docs.RepoObject_MeasureList
ssas.Measure_translation_T <.. ssas.Measure_translation_displayfolder_union
ssas.model_json <.. ssas.model_json_10
ssas.model_json_10 <.. ssas.model_json_20
ssas.model_json_20 <.. repo.RepoSchema_ssas_src
ssas.model_json_20 <.. ssas.model_json_33_dataSources
ssas.model_json_20 <.. ssas.model_json_31_tables
ssas.model_json_20 <.. ssas.model_json_201_descriptions_multiline
ssas.model_json_20 <.. ssas.model_json_32_relationships
ssas.model_json_20 <.. ssas.model_json_34_cultures
ssas.model_json_201_descriptions_multiline <.. ssas.model_json_2011_descriptions_StrAgg
ssas.model_json_2011_descriptions_StrAgg <.. repo.RepoSchema_ssas_src
ssas.model_json_31_tables <.. ssas.model_json_31_tables_T
ssas.model_json_31_tables_T <.. repo.RepoObject_gross
ssas.model_json_31_tables_T <.. repo.ForeignKey_ssas_IndexPattern
ssas.model_json_31_tables_T <.. ssas.model_json_312_tables_measures
ssas.model_json_31_tables_T <.. ssas.model_json_316_tables_descriptions_multiline
ssas.model_json_31_tables_T <.. ssas.model_json_313_tables_partitions
ssas.model_json_31_tables_T <.. ssas.model_json_311_tables_columns
ssas.model_json_31_tables_T <.. repo.RepoObject_SSAS_src
ssas.model_json_311_tables_columns <.. ssas.model_json_311_tables_columns_T
ssas.model_json_311_tables_columns_T <.. repo.RepoObjectColumn_SSAS_src
ssas.model_json_311_tables_columns_T <.. ssas.RepoObjectColumn_translation
ssas.model_json_311_tables_columns_T <.. repo.ForeignKey_ssas_IndexPattern
ssas.model_json_311_tables_columns_T <.. ssas.model_json_3111_tables_columns_descriptions_multiline
ssas.model_json_311_tables_columns_T <.. ssas.model_json_3112_tables_columns_expressions_multiline
ssas.model_json_311_tables_columns_T <.. ssas.additional_Reference_step1
ssas.model_json_311_tables_columns_T <.. ssas.IndexColumn_from_IsUnique
ssas.model_json_311_tables_columns_T <.. repo.RepoObjectColumn_gross
ssas.model_json_311_tables_columns_T <.. ssas.IndexColumn_from_Relationship
ssas.model_json_311_tables_columns_T <.. ssas.IndexColumn_from_IsKey
ssas.model_json_3111_tables_columns_descriptions_multiline <.. ssas.model_json_31111_tables_columns_descriptions_StrAgg
ssas.model_json_31111_tables_columns_descriptions_StrAgg <.. repo.RepoObjectColumn_gross
ssas.model_json_3112_tables_columns_expressions_multiline <.. ssas.model_json_31121_tables_columns_expressions_StrAgg
ssas.model_json_31121_tables_columns_expressions_StrAgg <.. repo.RepoObjectColumn_gross
ssas.model_json_312_tables_measures <.. ssas.model_json_312_tables_measures_T
ssas.model_json_312_tables_measures_T <.. ssas.model_json_3122_tables_measures_expressions_multiline
ssas.model_json_312_tables_measures_T <.. ssas.model_json_3121_tables_columns_descriptions_multiline
ssas.model_json_312_tables_measures_T <.. repo.Measure
ssas.model_json_3121_tables_columns_descriptions_multiline <.. ssas.model_json_31211_tables_columns_descriptions_StrAgg
ssas.model_json_31211_tables_columns_descriptions_StrAgg <.. repo.Measure
ssas.model_json_3122_tables_measures_expressions_multiline <.. ssas.model_json_31221_tables_measures_expressions_StrAgg
ssas.model_json_31221_tables_measures_expressions_StrAgg <.. repo.Measure
ssas.model_json_313_tables_partitions <.. ssas.model_json_3131_tables_partitions_source
ssas.model_json_3131_tables_partitions_source <.. ssas.model_json_31311_tables_partitions_source_PosFrom
ssas.model_json_31311_tables_partitions_source_PosFrom <.. ssas.model_json_313111_tables_partitions_source_StringFrom
ssas.model_json_313111_tables_partitions_source_StringFrom <.. ssas.model_json_3131111_tables_partitions_source_PosDot
ssas.model_json_3131111_tables_partitions_source_PosDot <.. ssas.model_json_31311111_tables_partitions_source_Part123
ssas.model_json_31311111_tables_partitions_source_Part123 <.. ssas.additional_Reference_step1
ssas.model_json_316_tables_descriptions_multiline <.. ssas.model_json_3161_tables_descriptions_StrAgg
ssas.model_json_3161_tables_descriptions_StrAgg <.. repo.RepoObject_gross
ssas.model_json_32_relationships <.. ssas.model_json_32_relationships_T
ssas.model_json_32_relationships_T <.. repo.ForeignKey_ssas_IndexPattern
ssas.model_json_32_relationships_T <.. ssas.IndexColumn_from_Relationship
ssas.model_json_33_dataSources <.. ssas.model_json_33_dataSources_T
ssas.model_json_33_dataSources_T <.. ssas.additional_Reference_step1
ssas.model_json_34_cultures <.. ssas.model_json_341_cultures_translations
ssas.model_json_341_cultures_translations <.. ssas.model_json_3411_cultures_translations_model
ssas.model_json_3411_cultures_translations_model <.. ssas.model_json_3411_cultures_translations_model_T
ssas.model_json_3411_cultures_translations_model_T <.. docs.RepoObject_OutputFilter
ssas.model_json_3411_cultures_translations_model_T <.. docs.Culture
ssas.model_json_3411_cultures_translations_model_T <.. ssas.model_json_34111_cultures_translations_model_tables
ssas.model_json_34111_cultures_translations_model_tables <.. docs.RepoObject_OutputFilter
ssas.model_json_34111_cultures_translations_model_tables <.. ssas.model_json_341111_cultures_translations_model_tables_columns
ssas.model_json_34111_cultures_translations_model_tables <.. ssas.model_json_341113_cultures_translations_model_tables_measures
ssas.model_json_341111_cultures_translations_model_tables_columns <.. ssas.RepoObjectColumn_translation
ssas.model_json_341113_cultures_translations_model_tables_measures <.. ssas.Measure_translation
ssas.RepoObjectColumn_translation <.. ssas.RepoObjectColumn_translation_T
ssas.RepoObjectColumn_translation_displayfolder_union <.. docs.RepoObject_ColumnList
ssas.RepoObjectColumn_translation_T <.. ssas.RepoObjectColumn_translation_displayfolder_union
sys_dwh.columns <.. repo_sys.ExtendedProperties
sys_dwh.columns <.. repo_sys.SysColumn
sys_dwh.computed_columns <.. repo_sys.SysColumn
sys_dwh.default_constraints <.. repo_sys.SysColumn
sys_dwh.extended_properties <.. repo_sys.ExtendedProperties
sys_dwh.foreign_key_columns <.. repo_sys.ForeignKeyColumn
sys_dwh.foreign_keys <.. repo_sys.ForeignKey
sys_dwh.identity_columns <.. repo_sys.SysColumn
sys_dwh.index_columns <.. repo_sys.IndexColumn_unique
sys_dwh.indexes <.. repo_sys.Index_unique
sys_dwh.indexes <.. repo_sys.IndexColumn_unique
sys_dwh.indexes <.. repo_sys.ExtendedProperties
sys_dwh.objects <.. repo_sys.ExtendedProperties
sys_dwh.objects <.. repo_sys.SysObject
sys_dwh.parameters <.. repo_sys.ExtendedProperties
sys_dwh.schemas <.. repo_sys.ExtendedProperties
sys_dwh.schemas <.. repo_sys.SysObject
sys_dwh.sql_expression_dependencies <.. repo_sys.sql_expression_dependencies
sys_dwh.sql_modules <.. repo_sys.SysObject
sys_dwh.tables <.. repo_sys.SysObject
sys_dwh.types <.. repo_sys.SysColumn
uspgenerator.GeneratorUsp <.. repo.RepoObject_gross

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_30_0_objectref[]

=== PlantUML 0 30 ObjectRef

// tag::puml_entity_0_30_objectref[]
[plantuml, entity_0_30_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:docs.antoranavlistpage_by_schema.adoc[]" as docs.AntoraNavListPage_by_schema << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.schema_puml.adoc[]" as docs.Schema_puml << V >> {
  - **RepoSchema_guid** : (uniqueidentifier)
  **cultures_name** : (nvarchar(10))
  --
}

docs.Schema_puml <.. docs.AntoraNavListPage_by_schema

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_0_30_objectref[]

=== PlantUML 1 1 ColumnRef

// tag::puml_entity_1_1_colref[]
[plantuml, entity_1_1_colref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:config.ftv_get_parameter_value.adoc[]" as config.ftv_get_parameter_value << IF >> {
  Parameter_value_result : (nvarchar(max))
  Parameter_value_result_date : (date)
  Parameter_value_result_datetime : (datetime)
  Parameter_value_result_int : (int)
  --
}

entity "puml-link:dhw:sqldb:docs.antoranavlistpage_by_schema.adoc[]" as docs.AntoraNavListPage_by_schema << V >> {
  cultures_name : (nvarchar(10))
  - nav_list : (nvarchar(max))
  - RepoObject_schema_name : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:docs.fs_pumlheaderlefttoright.adoc[]" as docs.fs_PumlHeaderLeftToRight << FN >> {
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_outputfilter_t.adoc[]" as docs.RepoObject_OutputFilter_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  AntoraComponent : (nvarchar(max))
  AntoraModule : (nvarchar(max))
  external_AntoraComponent : (nvarchar(128))
  external_AntoraModule : (nvarchar(128))
  external_DatabaseName : (nvarchar(128))
  is_DocsOutput : (int)
  - is_external : (bit)
  - is_ssas : (bit)
  - PumlEntityTopDefault : (nvarchar(max))
  - PumlEntityTopWorkaround : (nvarchar(max))
  RepoObject_DisplayName : (nvarchar(128))
  RepoObject_FullDisplayName2 : (nvarchar(257))
  - RepoObject_fullname : (nvarchar(261))
  - RepoObject_fullname2 : (nvarchar(257))
  - RepoObject_name : (nvarchar(128))
  - RepoObject_schema_name : (nvarchar(128))
  RepoObject_translation : (nvarchar(128))
  SysObject_type : (char(2))
  SysObject_type_name : (nvarchar(128))
  tables_isHidden : (bit)
  --
}

entity "puml-link:dhw:sqldb:docs.schema_entitylist.adoc[]" as docs.Schema_EntityList << V >> {
  - **RepoObject_schema_name** : (nvarchar(128))
  - **cultures_name** : (nvarchar(10))
  EntityList_Puml : (nvarchar(max))
  EntityList_PumlOnlyIndex : (nvarchar(max))
  EntityList_PumlOnlyPK : (nvarchar(max))
  EntityList_PumlOnlyPkOrIndex : (nvarchar(max))
  EntityList_PumlOnlyPkOrIndexOrMeasure : (nvarchar(max))
  EntityList_PumlOnlyPkOrNotHidden : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:docs.schema_puml.adoc[]" as docs.Schema_puml << V >> {
  - **RepoSchema_guid** : (uniqueidentifier)
  **cultures_name** : (nvarchar(10))
  - is_ssas : (bit)
  - PumlSchemaEr : (nvarchar(max))
  - PumlSchemaIndexEr : (nvarchar(max))
  PumlSchemaSsasEr : (nvarchar(max))
  - RepoSchema_name : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:docs.schema_pumlpartial_fkreflist.adoc[]" as docs.Schema_PumlPartial_FkRefList << V >> {
  cultures_name : (nvarchar(10))
  PumlPartial_FkRefList : (nvarchar(max))
  SchemaName : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:docs.schema_ssasrelationlist.adoc[]" as docs.Schema_SsasRelationList << V >> {
  - **SchemaName** : (nvarchar(128))
  **cultures_name** : (nvarchar(10))
  SsasRelationList_PumlRelation : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:repo.reposchema.adoc[]" as repo.RepoSchema << U >> {
  - **RepoSchema_guid** : (uniqueidentifier)
  - is_ssas : (bit)
  is_SysSchema_missing : (bit)
  - MeasuresRepoObjekt_guid : (uniqueidentifier)
  RepoSchema_description : (nvarchar(4000))
  - RepoSchema_name : (nvarchar(128))
  SysSchema_id : (int)
  - SysSchema_name : (nvarchar(128))
  ~ has_different_sys_names : (bit)
  # is_RepoSchema_name_uniqueidentifier : (int)
  # is_SysSchema_name_uniqueidentifier : (int)
  # MeasuresRepoObjekt_name : (varchar(9))
  --
}

config.ftv_get_parameter_value <.. docs.Schema_puml
docs.fs_PumlHeaderLeftToRight <.. docs.Schema_puml
docs.RepoObject_OutputFilter_T <.. docs.Schema_puml
docs.Schema_EntityList <.. docs.Schema_puml
docs.Schema_puml <.. docs.AntoraNavListPage_by_schema
docs.Schema_PumlPartial_FkRefList <.. docs.Schema_puml
docs.Schema_SsasRelationList <.. docs.Schema_puml
repo.RepoSchema <.. docs.Schema_puml
"repo.RepoSchema::is_ssas" <-- "docs.Schema_puml::is_ssas"
"repo.RepoSchema::RepoSchema_guid" <-- "docs.Schema_puml::RepoSchema_guid"
"repo.RepoSchema::RepoSchema_name" <-- "docs.Schema_puml::RepoSchema_name"

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_colref[]


== sql_modules_definition

// tag::sql_modules_definition[]
[%collapsible]
=======
[source,sql,numbered,indent=0]
----

/*
all objects of a schema

currently only usable: PumlSchemaSsasEr
because in ssas tabular there are no composed keys in relations
*/
CREATE View docs.Schema_puml
As
Select
    rs.RepoSchema_guid
  , schema_culture.cultures_name
  , rs.RepoSchema_name
  , rs.is_ssas
  --todo, how to draw relations between composed keys?
  , PumlSchemaEr      =
  --
  Concat (
             '@startuml' + Char ( 13 ) + Char ( 10 )
           , docs.fs_PumlHeaderLeftToRight ()
           , sel.EntityList_PumlOnlyPkOrIndex
           , Char ( 13 ) + Char ( 10 )
           , Char ( 13 ) + Char ( 10 )
           ----we still need an idea, how to show releations containing composite keys
           --, ssas_rl.SsasRelationList_PumlRelation
           --, Char ( 13 ) + Char ( 10 )
           --, Char ( 13 ) + Char ( 10 )
           , Char ( 13 ) + Char ( 10 ) + Char ( 13 ) + Char ( 10 ) + puml_footer.Parameter_value_result + Char ( 13 )
             + Char ( 10 )
           , Char ( 13 ) + Char ( 10 ) + '@enduml' + Char ( 13 ) + Char ( 10 )
         )
  --it doesn't look very nice, we need wait for a solution to draw PumlSchemaEr
  , PumlSchemaIndexEr =
  --
  Concat (
             '@startuml' + Char ( 13 ) + Char ( 10 )
           , docs.fs_PumlHeaderLeftToRight ()
           , sel.EntityList_PumlOnlyIndex
           , Char ( 13 ) + Char ( 10 )
           , Char ( 13 ) + Char ( 10 )
           , fklist.PumlPartial_FkRefList
           , Char ( 13 ) + Char ( 10 )
           , Char ( 13 ) + Char ( 10 ) + Char ( 13 ) + Char ( 10 ) + puml_footer.Parameter_value_result + Char ( 13 )
             + Char ( 10 )
           , Char ( 13 ) + Char ( 10 ) + '@enduml' + Char ( 13 ) + Char ( 10 )
         )
  , PumlSchemaSsasEr  =
  --
  Case
      When rs.is_ssas = 1
          Then
          Concat (
                     '@startuml' + Char ( 13 ) + Char ( 10 )
                   , docs.fs_PumlHeaderLeftToRight ()
                   , sel.EntityList_PumlOnlyPkOrIndexOrMeasure
                   , Char ( 13 ) + Char ( 10 )
                   , Char ( 13 ) + Char ( 10 )
                   , ssas_rl.SsasRelationList_PumlRelation
                   , Char ( 13 ) + Char ( 10 )
                   , Char ( 13 ) + Char ( 10 ) + Char ( 13 ) + Char ( 10 ) + puml_footer.Parameter_value_result
                     + Char ( 13 ) + Char ( 10 )
                   , Char ( 13 ) + Char ( 10 ) + '@enduml' + Char ( 13 ) + Char ( 10 )
                 )
  End
From
    repo.RepoSchema                                                          As rs
    Left Join
    (
        Select
            Distinct
            RepoObject_schema_name
          , cultures_name
        From
            docs.RepoObject_OutputFilter_T
        Where
            is_ssas = 1
    )                                                                        As schema_culture
        On
        schema_culture.RepoObject_schema_name = rs.RepoSchema_name

    Left Join
        docs.Schema_EntityList                                               As sel
            On
            sel.RepoObject_schema_name = schema_culture.RepoObject_schema_name
            And sel.cultures_name = schema_culture.cultures_name

    Left Join
        docs.Schema_PumlPartial_FkRefList                                    As fklist
            On
            fklist.SchemaName = schema_culture.RepoObject_schema_name
            And fklist.cultures_name = schema_culture.cultures_name

    Left Join
        docs.Schema_SsasRelationList                                         As ssas_rl
            On
            ssas_rl.SchemaName = schema_culture.RepoObject_schema_name
            And ssas_rl.cultures_name = schema_culture.cultures_name
    Cross Join config.ftv_get_parameter_value ( 'puml_skinparam_class', '' ) As skin
    Cross Join config.ftv_get_parameter_value ( 'puml_footer', 'interactive' ) As puml_footer
Where
    Not schema_culture.cultures_name Is Null

----
=======
// end::sql_modules_definition[]


