// tag::HeaderFullDisplayName[]
= docs.usp_AntoraExport_SsisPartialsContent - P
// end::HeaderFullDisplayName[]

== existing_properties

// tag::existing_properties[]

:ExistsProperty--adocuspsteps:
:ExistsProperty--antorareferencedlist:
:ExistsProperty--antorareferencinglist:
:ExistsProperty--exampleusage:
:ExistsProperty--is_repo_managed:
:ExistsProperty--is_ssas:
:ExistsProperty--referencedobjectlist:
:ExistsProperty--uspgenerator_usp_id:
:ExistsProperty--uspparameters:
:ExistsProperty--sql_modules_definition:
:ExistsProperty--AntoraParameterList:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
86DC9176-B547-EC11-8530-A81E8446D5B0
// end::RepoObject_guid[]

== RepoObject_FullDisplayName2

// tag::RepoObject_FullDisplayName2[]
docs.usp_AntoraExport_SsisPartialsContent
// end::RepoObject_FullDisplayName2[]

== SysObject_type

// tag::SysObject_type[]
P 
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
stored procedure
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
1614680850
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2022-01-23 17:32:24
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]

// end::AntoraColumnDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]

// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

// end::AntoraIndexList[]

== AntoraMeasureDetails

// tag::AntoraMeasureDetails[]

// end::AntoraMeasureDetails[]

== AntoraMeasureDescriptions



== AntoraParameterList

// tag::AntoraParameterList[]
* @isTrustedConnection (bit)
* @userName (nvarchar(250))
* @password (nvarchar(250))
* @execution_instance_guid (uniqueidentifier)
* @ssis_execution_id (bigint)
* @sub_execution_id (int)
* @parent_execution_log_id (bigint)
// end::AntoraParameterList[]

== AntoraXrefCulturesList

// tag::AntoraXrefCulturesList[]
* xref:dhw:sqldb:docs.usp_antoraexport_ssispartialscontent.adoc[] - 
// end::AntoraXrefCulturesList[]

== cultures_count

// tag::cultures_count[]
1
// end::cultures_count[]

== Other tags

source: property.RepoObjectProperty_cross As rop_cross


=== additional_reference_csv

// tag::additional_reference_csv[]

// end::additional_reference_csv[]


=== AdocUspSteps

// tag::adocuspsteps[]
.Steps in [docs].[usp_AntoraExport_SsisPartialsContent]
[cols="d,15a,d"]
|===
|Number|Name (Action, Source, Target)|Parent

|110
|
*configure database connection*



.Statement
[%collapsible]
=====
[source,sql,numbered]
----
DECLARE @instanceName NVARCHAR(500) = @@servername --example: 'ACER-F17\SQL2019', '.\SQL2019', localhost\SQL2019
DECLARE @databaseName NVARCHAR(128) = DB_NAME()
DECLARE @TrustedUserPassword NVARCHAR(1000)

IF @isTrustedConnection = 1
 SET @TrustedUserPassword = ' -T'
ELSE
 SET @TrustedUserPassword = ' -U ' + @userName + ' -P ' + @password
----
=====

|


|210
|
*declare variables*



.Statement
[%collapsible]
=====
[source,sql,numbered]
----
Declare @command NVarchar(4000)
Declare @AntoraModule Varchar(50)
Declare @PackageBasename Varchar(200)

----
=====

|


|330
|
*[docs].[usp_PERSIST_ssis_Adoc_T]*

* `EXEC [docs].[usp_PERSIST_ssis_Adoc_T]`


.Statement
[%collapsible]
=====
[source,sql,numbered]
----
[docs].[usp_PERSIST_ssis_Adoc_T]
----
=====

|


|410
|
*export FROM [docs].[ssis_Adoc_T]*

* u
* [docs].[RepoObject_Adoc_T]


.Statement
[%collapsible]
=====
[source,sql,numbered]
----
Declare p_cursor Cursor Local Fast_Forward For
Select
    AntoraModule
  , PackageBasename
From
    docs.ssis_Adoc_T
Order By
    AntoraModule
  , PackageBasename

Open p_cursor

Fetch Next From p_cursor
Into
    @AntoraModule
  , @PackageBasename

While @@Fetch_Status = 0
Begin
    Set @command = 'bcp "SELECT [AdocContent] FROM [docs].[ssis_Adoc_T] WITH (READUNCOMMITTED) where '
                   --
                   + '[AntoraModule] = '
                   --
                   + '''' + @AntoraModule + ''''
                   --
                   + ' AND '
                   --
                   + '[PackageBasename] = '
                   --
                   + '''' + @PackageBasename + ''''
                   --
                   + '" queryout "'
                   --
                   + config.fs_get_parameter_value ( 'AntoraComponentFolder', '' ) + '\modules\' + @AntoraModule
                   --
                   + '\partials\content\' + docs.fs_cleanStringForFilename ( @PackageBasename ) + '.adoc"'
                   --
                   + ' -S ' + @instanceName
                   --
                   + ' -d ' + @databaseName
                   --
                   + ' -c -C 65001'
                   --
                   + @TrustedUserPassword

    Print @command

    --Execute the BCP command
    Exec sys.xp_cmdshell @command, no_output

    Fetch Next From p_cursor
    Into
        @AntoraModule
      , @PackageBasename
End

Close p_cursor
Deallocate p_cursor
----
=====

|

|===

// end::adocuspsteps[]


=== AntoraReferencedList

// tag::antorareferencedlist[]
* xref:dhw:sqldb:config.fs_get_parameter_value.adoc[]
* xref:dhw:sqldb:docs.fs_cleanstringforfilename.adoc[]
* xref:dhw:sqldb:docs.ssis_adoc_t.adoc[]
* xref:dhw:sqldb:docs.usp_persist_ssis_adoc_t.adoc[]
* xref:dhw:sqldb:logs.usp_executionlog_insert.adoc[]
// end::antorareferencedlist[]


=== AntoraReferencingList

// tag::antorareferencinglist[]
* xref:dhw:sqldb:docs.usp_antoraexport.adoc[]
// end::antorareferencinglist[]


=== Description

// tag::description[]

// end::description[]


=== exampleUsage

// tag::exampleusage[]
EXEC [docs].[usp_AntoraExport_SsisPartialsContent]
// end::exampleusage[]


=== exampleUsage_2

// tag::exampleusage_2[]

// end::exampleusage_2[]


=== exampleUsage_3

// tag::exampleusage_3[]

// end::exampleusage_3[]


=== exampleUsage_4

// tag::exampleusage_4[]

// end::exampleusage_4[]


=== exampleUsage_5

// tag::exampleusage_5[]

// end::exampleusage_5[]


=== exampleWrong_Usage

// tag::examplewrong_usage[]

// end::examplewrong_usage[]


=== has_execution_plan_issue

// tag::has_execution_plan_issue[]

// end::has_execution_plan_issue[]


=== has_get_referenced_issue

// tag::has_get_referenced_issue[]

// end::has_get_referenced_issue[]


=== has_history

// tag::has_history[]

// end::has_history[]


=== has_history_columns

// tag::has_history_columns[]

// end::has_history_columns[]


=== InheritanceType

// tag::inheritancetype[]

// end::inheritancetype[]


=== is_persistence

// tag::is_persistence[]

// end::is_persistence[]


=== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]

// end::is_persistence_check_duplicate_per_pk[]


=== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]

// end::is_persistence_check_for_empty_source[]


=== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]

// end::is_persistence_delete_changed[]


=== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]

// end::is_persistence_delete_missing[]


=== is_persistence_insert

// tag::is_persistence_insert[]

// end::is_persistence_insert[]


=== is_persistence_truncate

// tag::is_persistence_truncate[]

// end::is_persistence_truncate[]


=== is_persistence_update_changed

// tag::is_persistence_update_changed[]

// end::is_persistence_update_changed[]


=== is_repo_managed

// tag::is_repo_managed[]
0
// end::is_repo_managed[]


=== is_ssas

// tag::is_ssas[]
0
// end::is_ssas[]


=== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


=== MS_Description

// tag::ms_description[]

// end::ms_description[]


=== persistence_source_RepoObject_fullname

// tag::persistence_source_repoobject_fullname[]

// end::persistence_source_repoobject_fullname[]


=== persistence_source_RepoObject_fullname2

// tag::persistence_source_repoobject_fullname2[]

// end::persistence_source_repoobject_fullname2[]


=== persistence_source_RepoObject_guid

// tag::persistence_source_repoobject_guid[]

// end::persistence_source_repoobject_guid[]


=== persistence_source_RepoObject_xref

// tag::persistence_source_repoobject_xref[]

// end::persistence_source_repoobject_xref[]


=== pk_index_guid

// tag::pk_index_guid[]

// end::pk_index_guid[]


=== pk_IndexPatternColumnDatatype

// tag::pk_indexpatterncolumndatatype[]

// end::pk_indexpatterncolumndatatype[]


=== pk_IndexPatternColumnName

// tag::pk_indexpatterncolumnname[]

// end::pk_indexpatterncolumnname[]


=== pk_IndexSemanticGroup

// tag::pk_indexsemanticgroup[]

// end::pk_indexsemanticgroup[]


=== ReferencedObjectList

// tag::referencedobjectlist[]
* [config].[fs_get_parameter_value]
* [docs].[fs_cleanStringForFilename]
* [docs].[ssis_Adoc_T]
* [docs].[usp_PERSIST_ssis_Adoc_T]
* [logs].[usp_ExecutionLog_insert]
// end::referencedobjectlist[]


=== usp_persistence_RepoObject_guid

// tag::usp_persistence_repoobject_guid[]

// end::usp_persistence_repoobject_guid[]


=== UspExamples

// tag::uspexamples[]

// end::uspexamples[]


=== uspgenerator_usp_id

// tag::uspgenerator_usp_id[]
126
// end::uspgenerator_usp_id[]


=== UspParameters

// tag::uspparameters[]
@isTrustedConnection BIT = 1 /* specify whether you are connecting to the SQL instance with a trusted connection (Windows Authentication) or not */
,@userName NVARCHAR(250) = 'loginName' /* If isTrustedConnection is set to 0 then you will need to add username and password for connecting to the SQL Server instance */
,@password NVARCHAR(250) = 'password'
// end::uspparameters[]

== Boolean Attributes

source: property.RepoObjectProperty WHERE property_int = 1

// tag::boolean_attributes[]


// end::boolean_attributes[]

== PlantUML diagrams

=== PlantUML Entity

// tag::puml_entity[]
[plantuml, entity-{docname}, svg, subs=macros]
....
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:docs.usp_antoraexport_ssispartialscontent.adoc[]" as docs.usp_AntoraExport_SsisPartialsContent << P >> {
  --
}
....

// end::puml_entity[]

=== PlantUML Entity 1 1 FK

// tag::puml_entity_1_1_fk[]
[plantuml, entity_1_1_fk-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}





footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_fk[]

=== PlantUML 1 1 ObjectRef

// tag::puml_entity_1_1_objectref[]
[plantuml, entity_1_1_objectref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:config.fs_get_parameter_value.adoc[]" as config.fs_get_parameter_value << FN >> {
  --
}

entity "puml-link:dhw:sqldb:docs.fs_cleanstringforfilename.adoc[]" as docs.fs_cleanStringForFilename << FN >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_adoc_t.adoc[]" as docs.ssis_Adoc_T << U >> {
  - **AntoraModule** : (varchar(50))
  - **PackageBasename** : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport.adoc[]" as docs.usp_AntoraExport << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_ssispartialscontent.adoc[]" as docs.usp_AntoraExport_SsisPartialsContent << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_ssis_adoc_t.adoc[]" as docs.usp_PERSIST_ssis_Adoc_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:logs.usp_executionlog_insert.adoc[]" as logs.usp_ExecutionLog_insert << P >> {
  --
}

config.fs_get_parameter_value <.. docs.usp_AntoraExport_SsisPartialsContent
docs.fs_cleanStringForFilename <.. docs.usp_AntoraExport_SsisPartialsContent
docs.ssis_Adoc_T <.. docs.usp_AntoraExport_SsisPartialsContent
docs.usp_AntoraExport_SsisPartialsContent <.. docs.usp_AntoraExport
docs.usp_PERSIST_ssis_Adoc_T <.. docs.usp_AntoraExport_SsisPartialsContent
logs.usp_ExecutionLog_insert <.. docs.usp_AntoraExport_SsisPartialsContent

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_objectref[]

=== PlantUML 30 0 ObjectRef

// tag::puml_entity_30_0_objectref[]
[plantuml, entity_30_0_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:config.fs_get_parameter_value.adoc[]" as config.fs_get_parameter_value << FN >> {
  --
}

entity "puml-link:dhw:sqldb:config.ftv_get_parameter_value.adoc[]" as config.ftv_get_parameter_value << IF >> {
  --
}

entity "puml-link:dhw:sqldb:config.parameter.adoc[]" as config.Parameter << U >> {
  - **Parameter_name** : (varchar(100))
  - **sub_Parameter** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:configt.parameter_default.adoc[]" as configT.Parameter_default << V >> {
  - **Parameter_name** : (varchar(52))
  - **sub_Parameter** : (nvarchar(26))
  --
}

entity "puml-link:dhw:sqldb:docs.fs_cleanstringforanchorid.adoc[]" as docs.fs_cleanStringForAnchorId << FN >> {
  --
}

entity "puml-link:dhw:sqldb:docs.fs_cleanstringforfilename.adoc[]" as docs.fs_cleanStringForFilename << FN >> {
  --
}

entity "puml-link:dhw:sqldb:docs.fs_cleanstringforheader.adoc[]" as docs.fs_cleanStringForHeader << FN >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_adoc.adoc[]" as docs.ssis_Adoc << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageBasename** : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_adoc_t.adoc[]" as docs.ssis_Adoc_T << U >> {
  - **AntoraModule** : (varchar(50))
  - **PackageBasename** : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_dfttaskcomponentinputcolumnlist.adoc[]" as docs.ssis_DftTaskComponentInputColumnList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_dfttaskcomponentinputlist.adoc[]" as docs.ssis_DftTaskComponentInputList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_dfttaskcomponentlist.adoc[]" as docs.ssis_DftTaskComponentList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_dfttaskcomponentoutputcolumnlist.adoc[]" as docs.ssis_DftTaskComponentOutputColumnList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_dfttaskcomponentoutputlist.adoc[]" as docs.ssis_DftTaskComponentOutputList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_generallist.adoc[]" as docs.ssis_GeneralList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_packageconnectionlist.adoc[]" as docs.ssis_PackageConnectionList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_parameterlist.adoc[]" as docs.ssis_ParameterList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_projectconnectionlist.adoc[]" as docs.ssis_ProjectConnectionList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_pumldfttask.adoc[]" as docs.ssis_PumlDftTask << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_pumlpackage.adoc[]" as docs.ssis_PumlPackage << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_pumlpartialcontrolflows.adoc[]" as docs.ssis_PumlPartialControlFlows << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_pumlpartialdataflow.adoc[]" as docs.ssis_PumlPartialDataFlow << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_pumlpartialdftcomponent.adoc[]" as docs.ssis_PumlPartialDftComponent << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_pumlpartialtaskcomponent.adoc[]" as docs.ssis_PumlPartialTaskComponent << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_sqltaskparameterinnertable.adoc[]" as docs.ssis_SqlTaskParameterInnerTable << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_tasklist.adoc[]" as docs.ssis_TaskList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_variablelist.adoc[]" as docs.ssis_VariableList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_ssispartialscontent.adoc[]" as docs.usp_AntoraExport_SsisPartialsContent << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_ssis_adoc_t.adoc[]" as docs.usp_PERSIST_ssis_Adoc_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:logs.executionlog.adoc[]" as logs.ExecutionLog << U >> {
  - **id** : (bigint)
  --
}

entity "puml-link:dhw:sqldb:logs.usp_executionlog_insert.adoc[]" as logs.usp_ExecutionLog_insert << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.antoramodule_tgt_filter.adoc[]" as ssis.AntoraModule_tgt_filter << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.package.adoc[]" as ssis.Package << U >> {
  - **AntoraModule** : (varchar(50))
  - **PackageName** : (varchar(200))
  --
}

entity "puml-link:dhw:sqldb:ssis.package_src.adoc[]" as ssis.Package_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  --
}

entity "puml-link:dhw:sqldb:ssis.package_tgt.adoc[]" as ssis.Package_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  - **PackageName** : (varchar(200))
  --
}

entity "puml-link:dhw:sqldb:ssis.packageconnection.adoc[]" as ssis.PackageConnection << U >> {
  - **AntoraModule** : (varchar(50))
  - **PackageName** : (varchar(200))
  - **ConnectionManagerID** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:ssis.packageconnection_src.adoc[]" as ssis.PackageConnection_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **ConnectionManagerID** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:ssis.packageconnection_tgt.adoc[]" as ssis.PackageConnection_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  - **PackageName** : (varchar(200))
  - **ConnectionManagerID** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:ssis.packageflow.adoc[]" as ssis.PackageFlow << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.packageflow_src.adoc[]" as ssis.PackageFlow_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **TaskFrom** : (varchar(2000))
  **Taskto** : (varchar(2000))
  --
}

entity "puml-link:dhw:sqldb:ssis.packageflow_tgt.adoc[]" as ssis.PackageFlow_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  - **PackageName** : (varchar(200))
  - **TaskFrom** : (varchar(2000))
  - **Taskto** : (varchar(2000))
  --
}

entity "puml-link:dhw:sqldb:ssis.packageparameter.adoc[]" as ssis.PackageParameter << U >> {
  - **AntoraModule** : (varchar(50))
  - **PackageName** : (varchar(200))
  - **ParameterName** : (varchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssis.packageparameter_src.adoc[]" as ssis.PackageParameter_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **ParameterName** : (varchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssis.packageparameter_tgt.adoc[]" as ssis.PackageParameter_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  - **PackageName** : (varchar(200))
  - **ParameterName** : (varchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask.adoc[]" as ssis.PackageTask << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component.adoc[]" as ssis.PackageTask_Dft_Component << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_input.adoc[]" as ssis.PackageTask_Dft_Component_input << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_input_externalmetadatacolumn.adoc[]" as ssis.PackageTask_Dft_Component_input_externalMetadataColumn << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_input_externalmetadatacolumn_src.adoc[]" as ssis.PackageTask_Dft_Component_input_externalMetadataColumn_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Column_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_input_externalmetadatacolumn_tgt.adoc[]" as ssis.PackageTask_Dft_Component_input_externalMetadataColumn_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Column_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_input_inputcolumn.adoc[]" as ssis.PackageTask_Dft_Component_input_inputColumn << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_input_inputcolumn_src.adoc[]" as ssis.PackageTask_Dft_Component_input_inputColumn_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Column_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_input_inputcolumn_tgt.adoc[]" as ssis.PackageTask_Dft_Component_input_inputColumn_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Column_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_input_src.adoc[]" as ssis.PackageTask_Dft_Component_input_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **input_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_input_tgt.adoc[]" as ssis.PackageTask_Dft_Component_input_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **input_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_output.adoc[]" as ssis.PackageTask_Dft_Component_output << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_output_outputcolumn.adoc[]" as ssis.PackageTask_Dft_Component_output_outputcolumn << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_output_outputcolumn_src.adoc[]" as ssis.PackageTask_Dft_Component_output_outputcolumn_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Column_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_output_outputcolumn_tgt.adoc[]" as ssis.PackageTask_Dft_Component_output_outputColumn_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Column_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_output_src.adoc[]" as ssis.PackageTask_Dft_Component_output_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **output_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_output_tgt.adoc[]" as ssis.PackageTask_Dft_Component_output_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **output_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_src.adoc[]" as ssis.PackageTask_Dft_Component_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Component_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_tgt.adoc[]" as ssis.PackageTask_Dft_Component_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Component_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_levellaglead.adoc[]" as ssis.PackageTask_LevelLagLead << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_sql_parameter.adoc[]" as ssis.PackageTask_Sql_Parameter << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_sql_parameter_src.adoc[]" as ssis.PackageTask_Sql_Parameter_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **TaskPath** : (varchar(8000))
  **ParameterBindingSequence** : (varchar(1000))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_sql_parameter_tgt.adoc[]" as ssis.PackageTask_Sql_Parameter_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  - **PackageName** : (varchar(200))
  - **TaskPath** : (varchar(8000))
  - **ParameterBindingSequence** : (varchar(1000))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_src.adoc[]" as ssis.PackageTask_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **TaskPath** : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_tgt.adoc[]" as ssis.PackageTask_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  - **PackageName** : (varchar(200))
  - **TaskPath** : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagevariable.adoc[]" as ssis.PackageVariable << U >> {
  - **AntoraModule** : (varchar(50))
  - **PackageName** : (varchar(200))
  - **VariableName** : (varchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagevariable_src.adoc[]" as ssis.PackageVariable_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **VariableName** : (varchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagevariable_tgt.adoc[]" as ssis.PackageVariable_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  - **PackageName** : (varchar(200))
  - **VariableName** : (varchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssis.project.adoc[]" as ssis.Project << U >> {
  - **AntoraModule** : (varchar(50))
  --
}

entity "puml-link:dhw:sqldb:ssis.projectconnection.adoc[]" as ssis.ProjectConnection << U >> {
  - **AntoraModule** : (varchar(50))
  - **ConnectionManagerID** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:ssis.projectconnection_src.adoc[]" as ssis.ProjectConnection_src << V >> {
  - **AntoraModule** : (varchar(50))
  **ConnectionManagerID** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:ssis.projectconnection_tgt.adoc[]" as ssis.ProjectConnection_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  - **ConnectionManagerID** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.pkgstats.adoc[]" as ssis_t.pkgStats << U >> {
  - **RowID** : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.projectconnection.adoc[]" as ssis_t.ProjectConnection << U >> {
  - **RowID** : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tblconnection.adoc[]" as ssis_t.TblConnection << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tblcontrolflow.adoc[]" as ssis_t.TblControlFlow << U >> {
  - **ControlFlowDetailsRowID** : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tblparameter.adoc[]" as ssis_t.TblParameter << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tblprecedenceconstraint.adoc[]" as ssis_t.TblPrecedenceConstraint << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tblprojectconnection.adoc[]" as ssis_t.TblProjectConnection << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_dft_component.adoc[]" as ssis_t.TblTask_Dft_Component << U >> {
  - **DftComponentId** : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_dft_component_inputs_externalmetadatacolumn_src.adoc[]" as ssis_t.TblTask_Dft_Component_inputs_externalMetadataColumn_src << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_dft_component_inputs_inputcolumn_src.adoc[]" as ssis_t.TblTask_Dft_Component_inputs_inputColumn_src << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_dft_component_inputs_src.adoc[]" as ssis_t.TblTask_Dft_Component_inputs_src << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_dft_component_outputs_outputcolumn_src.adoc[]" as ssis_t.TblTask_Dft_Component_outputs_outputColumn_src << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_dft_component_outputs_src.adoc[]" as ssis_t.TblTask_Dft_Component_outputs_src << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_executepackage.adoc[]" as ssis_t.TblTask_ExecutePackage << U >> {
  - **ControlFlowDetailsRowID** : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_script.adoc[]" as ssis_t.TblTask_Script << U >> {
  - **ControlFlowDetailsRowID** : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_sql.adoc[]" as ssis_t.TblTask_Sql << U >> {
  - **ControlFlowDetailsRowID** : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_sql_parameter.adoc[]" as ssis_t.TblTask_Sql_Parameter << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tblvariable.adoc[]" as ssis_t.TblVariable << U >> {
  --
}

config.fs_get_parameter_value <.. docs.usp_AntoraExport_SsisPartialsContent
config.ftv_get_parameter_value <.. docs.ssis_PumlDftTask
config.ftv_get_parameter_value <.. docs.ssis_PumlPackage
config.Parameter <.. config.fs_get_parameter_value
config.Parameter <.. config.ftv_get_parameter_value
configT.Parameter_default <.. config.Parameter
docs.fs_cleanStringForAnchorId <.. docs.ssis_DftTaskComponentInputList
docs.fs_cleanStringForAnchorId <.. docs.ssis_DftTaskComponentInputColumnList
docs.fs_cleanStringForAnchorId <.. docs.ssis_DftTaskComponentOutputColumnList
docs.fs_cleanStringForAnchorId <.. docs.ssis_DftTaskComponentOutputList
docs.fs_cleanStringForAnchorId <.. docs.ssis_VariableList
docs.fs_cleanStringForAnchorId <.. docs.ssis_TaskList
docs.fs_cleanStringForAnchorId <.. docs.ssis_ParameterList
docs.fs_cleanStringForAnchorId <.. docs.ssis_PackageConnectionList
docs.fs_cleanStringForAnchorId <.. docs.ssis_DftTaskComponentList
docs.fs_cleanStringForAnchorId <.. docs.ssis_PumlPartialDftComponent
docs.fs_cleanStringForAnchorId <.. docs.ssis_PumlPartialDataFlow
docs.fs_cleanStringForAnchorId <.. docs.ssis_PumlPartialTaskComponent
docs.fs_cleanStringForAnchorId <.. docs.ssis_ProjectConnectionList
docs.fs_cleanStringForAnchorId <.. docs.ssis_PumlPartialControlFlows
docs.fs_cleanStringForFilename <.. docs.usp_AntoraExport_SsisPartialsContent
docs.fs_cleanStringForFilename <.. docs.ssis_PumlPartialDftComponent
docs.fs_cleanStringForFilename <.. docs.ssis_PumlPartialTaskComponent
docs.fs_cleanStringForFilename <.. docs.ssis_TaskList
docs.fs_cleanStringForFilename <.. docs.ssis_PackageConnectionList
docs.fs_cleanStringForHeader <.. docs.ssis_VariableList
docs.fs_cleanStringForHeader <.. docs.ssis_TaskList
docs.fs_cleanStringForHeader <.. docs.ssis_ParameterList
docs.fs_cleanStringForHeader <.. docs.ssis_PackageConnectionList
docs.fs_cleanStringForHeader <.. docs.ssis_DftTaskComponentList
docs.fs_cleanStringForHeader <.. docs.ssis_DftTaskComponentInputList
docs.fs_cleanStringForHeader <.. docs.ssis_DftTaskComponentInputColumnList
docs.fs_cleanStringForHeader <.. docs.ssis_DftTaskComponentOutputColumnList
docs.fs_cleanStringForHeader <.. docs.ssis_ProjectConnectionList
docs.fs_cleanStringForHeader <.. docs.ssis_DftTaskComponentOutputList
docs.ssis_Adoc <.. docs.ssis_Adoc_T
docs.ssis_Adoc <.. docs.usp_PERSIST_ssis_Adoc_T
docs.ssis_Adoc_T <.. docs.usp_PERSIST_ssis_Adoc_T
docs.ssis_Adoc_T <.. docs.usp_AntoraExport_SsisPartialsContent
docs.ssis_DftTaskComponentInputColumnList <.. docs.ssis_DftTaskComponentInputList
docs.ssis_DftTaskComponentInputList <.. docs.ssis_DftTaskComponentList
docs.ssis_DftTaskComponentList <.. docs.ssis_TaskList
docs.ssis_DftTaskComponentOutputColumnList <.. docs.ssis_DftTaskComponentOutputList
docs.ssis_DftTaskComponentOutputList <.. docs.ssis_DftTaskComponentList
docs.ssis_GeneralList <.. docs.ssis_Adoc
docs.ssis_PackageConnectionList <.. docs.ssis_Adoc
docs.ssis_ParameterList <.. docs.ssis_Adoc
docs.ssis_ProjectConnectionList <.. docs.ssis_Adoc
docs.ssis_PumlDftTask <.. docs.ssis_TaskList
docs.ssis_PumlPackage <.. docs.ssis_Adoc
docs.ssis_PumlPartialControlFlows <.. docs.ssis_PumlPackage
docs.ssis_PumlPartialDataFlow <.. docs.ssis_PumlDftTask
docs.ssis_PumlPartialDftComponent <.. docs.ssis_DftTaskComponentList
docs.ssis_PumlPartialDftComponent <.. docs.ssis_PumlDftTask
docs.ssis_PumlPartialTaskComponent <.. docs.ssis_PumlPackage
docs.ssis_SqlTaskParameterInnerTable <.. docs.ssis_TaskList
docs.ssis_TaskList <.. docs.ssis_Adoc
docs.ssis_VariableList <.. docs.ssis_Adoc
docs.usp_PERSIST_ssis_Adoc_T <.. docs.usp_AntoraExport_SsisPartialsContent
logs.ExecutionLog <.. logs.usp_ExecutionLog_insert
logs.usp_ExecutionLog_insert <.. docs.usp_AntoraExport_SsisPartialsContent
logs.usp_ExecutionLog_insert <.. docs.usp_PERSIST_ssis_Adoc_T
ssis.AntoraModule_tgt_filter <.. ssis.PackageTask_Dft_Component_input_inputColumn_tgt
ssis.AntoraModule_tgt_filter <.. ssis.PackageTask_Dft_Component_input_tgt
ssis.AntoraModule_tgt_filter <.. ssis.PackageTask_Dft_Component_output_outputcolumn_tgt
ssis.AntoraModule_tgt_filter <.. ssis.ProjectConnection_tgt
ssis.AntoraModule_tgt_filter <.. ssis.PackageTask_Dft_Component_tgt
ssis.AntoraModule_tgt_filter <.. ssis.PackageTask_Dft_Component_input_externalMetadataColumn_tgt
ssis.AntoraModule_tgt_filter <.. ssis.Package_tgt
ssis.AntoraModule_tgt_filter <.. ssis.PackageConnection_tgt
ssis.AntoraModule_tgt_filter <.. ssis.PackageFlow_tgt
ssis.AntoraModule_tgt_filter <.. ssis.PackageTask_Sql_Parameter_tgt
ssis.AntoraModule_tgt_filter <.. ssis.PackageParameter_tgt
ssis.AntoraModule_tgt_filter <.. ssis.PackageTask_tgt
ssis.AntoraModule_tgt_filter <.. ssis.PackageVariable_tgt
ssis.AntoraModule_tgt_filter <.. ssis.PackageTask_Dft_Component_output_tgt
ssis.Package <.. docs.ssis_Adoc
ssis.Package <.. docs.ssis_GeneralList
ssis.Package_src <.. ssis.Package_tgt
ssis.Package_src <.. ssis.PackageConnection_src
ssis.Package_src <.. ssis.PackageParameter_src
ssis.Package_src <.. ssis.PackageFlow_src
ssis.Package_src <.. ssis.AntoraModule_tgt_filter
ssis.Package_src <.. ssis.PackageTask_Dft_Component_input_externalMetadataColumn_src
ssis.Package_src <.. ssis.PackageTask_Sql_Parameter_src
ssis.Package_src <.. ssis.PackageTask_src
ssis.Package_src <.. ssis.PackageTask_Dft_Component_src
ssis.Package_src <.. ssis.PackageVariable_src
ssis.Package_src <.. ssis.PackageTask_Dft_Component_input_inputColumn_src
ssis.Package_src <.. ssis.PackageTask_Dft_Component_output_outputcolumn_src
ssis.Package_src <.. ssis.PackageTask_Dft_Component_input_src
ssis.Package_src <.. ssis.PackageTask_Dft_Component_output_src
ssis.Package_tgt <.. ssis.Package
ssis.PackageConnection <.. docs.ssis_TaskList
ssis.PackageConnection <.. docs.ssis_PackageConnectionList
ssis.PackageConnection_src <.. ssis.PackageConnection_tgt
ssis.PackageConnection_tgt <.. ssis.PackageConnection
ssis.PackageFlow <.. docs.ssis_PumlPartialControlFlows
ssis.PackageFlow <.. docs.ssis_PumlPartialDataFlow
ssis.PackageFlow_src <.. ssis.PackageFlow_tgt
ssis.PackageFlow_tgt <.. ssis.PackageFlow
ssis.PackageParameter <.. docs.ssis_ParameterList
ssis.PackageParameter_src <.. ssis.PackageParameter_tgt
ssis.PackageParameter_tgt <.. ssis.PackageParameter
ssis.PackageTask <.. ssis.PackageTask_LevelLagLead
ssis.PackageTask <.. docs.ssis_TaskList
ssis.PackageTask_Dft_Component <.. docs.ssis_DftTaskComponentList
ssis.PackageTask_Dft_Component <.. docs.ssis_PumlDftTask
ssis.PackageTask_Dft_Component <.. docs.ssis_PumlPartialDftComponent
ssis.PackageTask_Dft_Component_input <.. docs.ssis_DftTaskComponentInputList
ssis.PackageTask_Dft_Component_input_externalMetadataColumn <.. docs.ssis_DftTaskComponentOutputColumnList
ssis.PackageTask_Dft_Component_input_externalMetadataColumn <.. docs.ssis_DftTaskComponentInputColumnList
ssis.PackageTask_Dft_Component_input_externalMetadataColumn_src <.. ssis.PackageTask_Dft_Component_input_externalMetadataColumn_tgt
ssis.PackageTask_Dft_Component_input_externalMetadataColumn_tgt <.. ssis.PackageTask_Dft_Component_input_externalMetadataColumn
ssis.PackageTask_Dft_Component_input_inputColumn <.. docs.ssis_DftTaskComponentInputColumnList
ssis.PackageTask_Dft_Component_input_inputColumn_src <.. ssis.PackageTask_Dft_Component_input_inputColumn_tgt
ssis.PackageTask_Dft_Component_input_inputColumn_tgt <.. ssis.PackageTask_Dft_Component_input_inputColumn
ssis.PackageTask_Dft_Component_input_src <.. ssis.PackageTask_Dft_Component_input_tgt
ssis.PackageTask_Dft_Component_input_tgt <.. ssis.PackageTask_Dft_Component_input
ssis.PackageTask_Dft_Component_output <.. docs.ssis_DftTaskComponentOutputList
ssis.PackageTask_Dft_Component_output_outputcolumn <.. docs.ssis_DftTaskComponentOutputColumnList
ssis.PackageTask_Dft_Component_output_outputcolumn_src <.. ssis.PackageTask_Dft_Component_output_outputcolumn_tgt
ssis.PackageTask_Dft_Component_output_outputcolumn_tgt <.. ssis.PackageTask_Dft_Component_output_outputcolumn
ssis.PackageTask_Dft_Component_output_src <.. ssis.PackageTask_Dft_Component_output_tgt
ssis.PackageTask_Dft_Component_output_tgt <.. ssis.PackageTask_Dft_Component_output
ssis.PackageTask_Dft_Component_src <.. ssis.PackageTask_Dft_Component_tgt
ssis.PackageTask_Dft_Component_tgt <.. ssis.PackageTask_Dft_Component
ssis.PackageTask_LevelLagLead <.. docs.ssis_PumlPartialTaskComponent
ssis.PackageTask_Sql_Parameter <.. docs.ssis_SqlTaskParameterInnerTable
ssis.PackageTask_Sql_Parameter_src <.. ssis.PackageTask_Sql_Parameter_tgt
ssis.PackageTask_Sql_Parameter_tgt <.. ssis.PackageTask_Sql_Parameter
ssis.PackageTask_src <.. ssis.PackageTask_tgt
ssis.PackageTask_tgt <.. ssis.PackageTask
ssis.PackageVariable <.. docs.ssis_VariableList
ssis.PackageVariable_src <.. ssis.PackageVariable_tgt
ssis.PackageVariable_tgt <.. ssis.PackageVariable
ssis.Project <.. ssis.Package_src
ssis.Project <.. ssis.ProjectConnection_src
ssis.ProjectConnection <.. docs.ssis_ProjectConnectionList
ssis.ProjectConnection <.. docs.ssis_TaskList
ssis.ProjectConnection_src <.. ssis.ProjectConnection_tgt
ssis.ProjectConnection_tgt <.. ssis.ProjectConnection
ssis_t.pkgStats <.. ssis.Package_src
ssis_t.ProjectConnection <.. ssis.ProjectConnection_src
ssis_t.TblConnection <.. ssis.PackageConnection_src
ssis_t.TblControlFlow <.. ssis.PackageTask_Sql_Parameter_src
ssis_t.TblControlFlow <.. ssis.PackageTask_src
ssis_t.TblControlFlow <.. ssis.PackageTask_Dft_Component_src
ssis_t.TblControlFlow <.. ssis.PackageTask_Dft_Component_output_outputcolumn_src
ssis_t.TblControlFlow <.. ssis.PackageTask_Dft_Component_input_src
ssis_t.TblControlFlow <.. ssis.PackageTask_Dft_Component_output_src
ssis_t.TblControlFlow <.. ssis.PackageTask_Dft_Component_input_inputColumn_src
ssis_t.TblControlFlow <.. ssis.PackageTask_Dft_Component_input_externalMetadataColumn_src
ssis_t.TblParameter <.. ssis.PackageParameter_src
ssis_t.TblPrecedenceConstraint <.. ssis.PackageFlow_src
ssis_t.TblProjectConnection <.. ssis.ProjectConnection_src
ssis_t.TblTask_Dft_Component <.. ssis_t.TblTask_Dft_Component_outputs_outputColumn_src
ssis_t.TblTask_Dft_Component <.. ssis.PackageTask_Dft_Component_src
ssis_t.TblTask_Dft_Component <.. ssis_t.TblTask_Dft_Component_inputs_src
ssis_t.TblTask_Dft_Component <.. ssis_t.TblTask_Dft_Component_outputs_src
ssis_t.TblTask_Dft_Component <.. ssis_t.TblTask_Dft_Component_inputs_inputColumn_src
ssis_t.TblTask_Dft_Component <.. ssis_t.TblTask_Dft_Component_inputs_externalMetadataColumn_src
ssis_t.TblTask_Dft_Component_inputs_externalMetadataColumn_src <.. ssis.PackageTask_Dft_Component_input_externalMetadataColumn_src
ssis_t.TblTask_Dft_Component_inputs_inputColumn_src <.. ssis.PackageTask_Dft_Component_input_inputColumn_src
ssis_t.TblTask_Dft_Component_inputs_src <.. ssis.PackageTask_Dft_Component_input_src
ssis_t.TblTask_Dft_Component_outputs_outputColumn_src <.. ssis.PackageTask_Dft_Component_output_outputcolumn_src
ssis_t.TblTask_Dft_Component_outputs_src <.. ssis.PackageTask_Dft_Component_output_src
ssis_t.TblTask_ExecutePackage <.. ssis.PackageTask_src
ssis_t.TblTask_Script <.. ssis.PackageTask_src
ssis_t.TblTask_Sql <.. ssis.PackageTask_src
ssis_t.TblTask_Sql_Parameter <.. ssis.PackageTask_Sql_Parameter_src
ssis_t.TblVariable <.. ssis.PackageVariable_src

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_30_0_objectref[]

=== PlantUML 0 30 ObjectRef

// tag::puml_entity_0_30_objectref[]
[plantuml, entity_0_30_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:docs.usp_antoraexport.adoc[]" as docs.usp_AntoraExport << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_ssispartialscontent.adoc[]" as docs.usp_AntoraExport_SsisPartialsContent << P >> {
  --
}

docs.usp_AntoraExport_SsisPartialsContent <.. docs.usp_AntoraExport

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_0_30_objectref[]

=== PlantUML 1 1 ColumnRef

// tag::puml_entity_1_1_colref[]
[plantuml, entity_1_1_colref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:config.fs_get_parameter_value.adoc[]" as config.fs_get_parameter_value << FN >> {
  --
}

entity "puml-link:dhw:sqldb:docs.fs_cleanstringforfilename.adoc[]" as docs.fs_cleanStringForFilename << FN >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_adoc_t.adoc[]" as docs.ssis_Adoc_T << U >> {
  - **AntoraModule** : (varchar(50))
  - **PackageBasename** : (varchar(8000))
  - AdocContent : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport.adoc[]" as docs.usp_AntoraExport << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_ssispartialscontent.adoc[]" as docs.usp_AntoraExport_SsisPartialsContent << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_ssis_adoc_t.adoc[]" as docs.usp_PERSIST_ssis_Adoc_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:logs.usp_executionlog_insert.adoc[]" as logs.usp_ExecutionLog_insert << P >> {
  --
}

config.fs_get_parameter_value <.. docs.usp_AntoraExport_SsisPartialsContent
docs.fs_cleanStringForFilename <.. docs.usp_AntoraExport_SsisPartialsContent
docs.ssis_Adoc_T <.. docs.usp_AntoraExport_SsisPartialsContent
docs.usp_AntoraExport_SsisPartialsContent <.. docs.usp_AntoraExport
docs.usp_PERSIST_ssis_Adoc_T <.. docs.usp_AntoraExport_SsisPartialsContent
logs.usp_ExecutionLog_insert <.. docs.usp_AntoraExport_SsisPartialsContent


footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_colref[]


== sql_modules_definition

// tag::sql_modules_definition[]
[%collapsible]
=======
[source,sql,numbered,indent=0]
----
/*
code of this procedure is managed in the dhw repository. Do not modify manually.
Use [uspgenerator].[GeneratorUsp], [uspgenerator].[GeneratorUspParameter], [uspgenerator].[GeneratorUspStep], [uspgenerator].[GeneratorUsp_SqlUsp]
*/
CREATE   PROCEDURE [docs].[usp_AntoraExport_SsisPartialsContent]
@isTrustedConnection BIT = 1 /* specify whether you are connecting to the SQL instance with a trusted connection (Windows Authentication) or not */
,@userName NVARCHAR(250) = 'loginName' /* If isTrustedConnection is set to 0 then you will need to add username and password for connecting to the SQL Server instance */
,@password NVARCHAR(250) = 'password'
,
----keep the code between logging parameters and "START" unchanged!
---- parameters, used for logging; you don't need to care about them, but you can use them, wenn calling from SSIS or in your workflow to log the context of the procedure call
  @execution_instance_guid UNIQUEIDENTIFIER = NULL --SSIS system variable ExecutionInstanceGUID could be used, any other unique guid is also fine. If NULL, then NEWID() is used to create one
, @ssis_execution_id BIGINT = NULL --only SSIS system variable ServerExecutionID should be used, or any other consistent number system, do not mix different number systems
, @sub_execution_id INT = NULL --in case you log some sub_executions, for example in SSIS loops or sub packages
, @parent_execution_log_id BIGINT = NULL --in case a sup procedure is called, the @current_execution_log_id of the parent procedure should be propagated here. It allowes call stack analyzing

AS
BEGIN
DECLARE
 --
   @current_execution_log_id BIGINT --this variable should be filled only once per procedure call, it contains the first logging call for the step 'start'.
 , @current_execution_guid UNIQUEIDENTIFIER = NEWID() --a unique guid for any procedure call. It should be propagated to sub procedures using "@parent_execution_log_id = @current_execution_log_id"
 , @source_object NVARCHAR(261) = NULL --use it like '[schema].[object]', this allows data flow vizualizatiuon (include square brackets)
 , @target_object NVARCHAR(261) = NULL --use it like '[schema].[object]', this allows data flow vizualizatiuon (include square brackets)
 , @proc_id INT = @@procid
 , @proc_schema_name NVARCHAR(128) = OBJECT_SCHEMA_NAME(@@procid) --schema ande name of the current procedure should be automatically logged
 , @proc_name NVARCHAR(128) = OBJECT_NAME(@@procid)               --schema ande name of the current procedure should be automatically logged
 , @event_info NVARCHAR(MAX)
 , @step_id INT = 0
 , @step_name NVARCHAR(1000) = NULL
 , @rows INT

--[event_info] get's only the information about the "outer" calling process
--wenn the procedure calls sub procedures, the [event_info] will not change
SET @event_info = (
  SELECT TOP 1 [event_info]
  FROM sys.dm_exec_input_buffer(@@spid, CURRENT_REQUEST_ID())
  ORDER BY [event_info]
  )

IF @execution_instance_guid IS NULL
 SET @execution_instance_guid = NEWID();
--
--SET @rows = @@ROWCOUNT;
SET @step_id = @step_id + 1
SET @step_name = 'start'
SET @source_object = NULL
SET @target_object = NULL

EXEC logs.usp_ExecutionLog_insert
 --these parameters should be the same for all logging execution
   @execution_instance_guid = @execution_instance_guid
 , @ssis_execution_id = @ssis_execution_id
 , @sub_execution_id = @sub_execution_id
 , @parent_execution_log_id = @parent_execution_log_id
 , @current_execution_guid = @current_execution_guid
 , @proc_id = @proc_id
 , @proc_schema_name = @proc_schema_name
 , @proc_name = @proc_name
 , @event_info = @event_info
 --the following parameters are individual for each call
 , @step_id = @step_id --@step_id should be incremented before each call
 , @step_name = @step_name --assign individual step names for each call
 --only the "start" step should return the log id into @current_execution_log_id
 --all other calls should not overwrite @current_execution_log_id
 , @execution_log_id = @current_execution_log_id OUTPUT
----you can log the content of your own parameters, do this only in the start-step
----data type is sql_variant
 , @parameter_01 = @isTrustedConnection
 , @parameter_02 = @userName
 , @parameter_03 = @password
--
PRINT '[docs].[usp_AntoraExport_SsisPartialsContent]'
--keep the code between logging parameters and "START" unchanged!
--
----START
--
----- start here with your own code
--
/*{"ReportUspStep":[{"Number":110,"Name":"configure database connection","has_logging":0,"is_condition":0,"is_inactive":0,"is_SubProcedure":0}]}*/
PRINT CONCAT('usp_id;Number;Parent_Number: ',126,';',110,';',NULL);

DECLARE @instanceName NVARCHAR(500) = @@servername --example: 'ACER-F17\SQL2019', '.\SQL2019', localhost\SQL2019
DECLARE @databaseName NVARCHAR(128) = DB_NAME()
DECLARE @TrustedUserPassword NVARCHAR(1000)

IF @isTrustedConnection = 1
 SET @TrustedUserPassword = ' -T'
ELSE
 SET @TrustedUserPassword = ' -U ' + @userName + ' -P ' + @password

/*{"ReportUspStep":[{"Number":210,"Name":"declare variables","has_logging":0,"is_condition":0,"is_inactive":0,"is_SubProcedure":0}]}*/
PRINT CONCAT('usp_id;Number;Parent_Number: ',126,';',210,';',NULL);

Declare @command NVarchar(4000)
Declare @AntoraModule Varchar(50)
Declare @PackageBasename Varchar(200)


/*{"ReportUspStep":[{"Number":330,"Name":"[docs].[usp_PERSIST_ssis_Adoc_T]","has_logging":1,"is_condition":0,"is_inactive":0,"is_SubProcedure":1}]}*/
EXEC [docs].[usp_PERSIST_ssis_Adoc_T]
--add your own parameters
--logging parameters
 @execution_instance_guid = @execution_instance_guid
 , @ssis_execution_id = @ssis_execution_id
 , @sub_execution_id = @sub_execution_id
 , @parent_execution_log_id = @current_execution_log_id


/*{"ReportUspStep":[{"Number":410,"Name":"export FROM [docs].[ssis_Adoc_T]","has_logging":1,"is_condition":0,"is_inactive":0,"is_SubProcedure":0,"log_source_object":"[docs].[RepoObject_Adoc_T]","log_flag_InsertUpdateDelete":"u"}]}*/
PRINT CONCAT('usp_id;Number;Parent_Number: ',126,';',410,';',NULL);

Declare p_cursor Cursor Local Fast_Forward For
Select
    AntoraModule
  , PackageBasename
From
    docs.ssis_Adoc_T
Order By
    AntoraModule
  , PackageBasename

Open p_cursor

Fetch Next From p_cursor
Into
    @AntoraModule
  , @PackageBasename

While @@Fetch_Status = 0
Begin
    Set @command = 'bcp "SELECT [AdocContent] FROM [docs].[ssis_Adoc_T] WITH (READUNCOMMITTED) where '
                   --
                   + '[AntoraModule] = '
                   --
                   + '''' + @AntoraModule + ''''
                   --
                   + ' AND '
                   --
                   + '[PackageBasename] = '
                   --
                   + '''' + @PackageBasename + ''''
                   --
                   + '" queryout "'
                   --
                   + config.fs_get_parameter_value ( 'AntoraComponentFolder', '' ) + '\modules\' + @AntoraModule
                   --
                   + '\partials\content\' + docs.fs_cleanStringForFilename ( @PackageBasename ) + '.adoc"'
                   --
                   + ' -S ' + @instanceName
                   --
                   + ' -d ' + @databaseName
                   --
                   + ' -c -C 65001'
                   --
                   + @TrustedUserPassword

    Print @command

    --Execute the BCP command
    Exec sys.xp_cmdshell @command, no_output

    Fetch Next From p_cursor
    Into
        @AntoraModule
      , @PackageBasename
End

Close p_cursor
Deallocate p_cursor

-- Logging START --
SET @rows = @@ROWCOUNT
SET @step_id = @step_id + 1
SET @step_name = 'export FROM [docs].[ssis_Adoc_T]'
SET @source_object = '[docs].[RepoObject_Adoc_T]'
SET @target_object = NULL

EXEC logs.usp_ExecutionLog_insert 
 @execution_instance_guid = @execution_instance_guid
 , @ssis_execution_id = @ssis_execution_id
 , @sub_execution_id = @sub_execution_id
 , @parent_execution_log_id = @parent_execution_log_id
 , @current_execution_guid = @current_execution_guid
 , @proc_id = @proc_id
 , @proc_schema_name = @proc_schema_name
 , @proc_name = @proc_name
 , @event_info = @event_info
 , @step_id = @step_id
 , @step_name = @step_name
 , @source_object = @source_object
 , @target_object = @target_object
 , @updated = @rows
-- Logging END --

--
--finish your own code here
--keep the code between "END" and the end of the procedure unchanged!
--
--END
--
--SET @rows = @@ROWCOUNT
SET @step_id = @step_id + 1
SET @step_name = 'end'
SET @source_object = NULL
SET @target_object = NULL

EXEC logs.usp_ExecutionLog_insert
   @execution_instance_guid = @execution_instance_guid
 , @ssis_execution_id = @ssis_execution_id
 , @sub_execution_id = @sub_execution_id
 , @parent_execution_log_id = @parent_execution_log_id
 , @current_execution_guid = @current_execution_guid
 , @proc_id = @proc_id
 , @proc_schema_name = @proc_schema_name
 , @proc_name = @proc_name
 , @event_info = @event_info
 , @step_id = @step_id
 , @step_name = @step_name
 , @source_object = @source_object
 , @target_object = @target_object

END


----
=======
// end::sql_modules_definition[]


