// tag::HeaderFullDisplayName[]
= docs.ssis_DftTaskComponentList - V
// end::HeaderFullDisplayName[]

== existing_properties

// tag::existing_properties[]

:ExistsProperty--antorareferencedlist:
:ExistsProperty--antorareferencinglist:
:ExistsProperty--is_repo_managed:
:ExistsProperty--is_ssas:
:ExistsProperty--referencedobjectlist:
:ExistsProperty--sql_modules_definition:
:ExistsProperty--FK:
:ExistsProperty--Columns:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
6ADDD159-FC3E-EC11-852D-A81E8446D5B0
// end::RepoObject_guid[]

== RepoObject_FullDisplayName2

// tag::RepoObject_FullDisplayName2[]
docs.ssis_DftTaskComponentList
// end::RepoObject_FullDisplayName2[]

== SysObject_type

// tag::SysObject_type[]
V 
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
view
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
318676233
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2021-11-08 17:41:26
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]
[discrete]
== _


[#column-antoramodule]
=== AntoraModule

[cols="d,8a,m,m,m"]
|===
|
|AntoraModule
|varchar(50)
|NOT NULL
|
|===

.Referenced Columns
--
* xref:ssis.packagetask_dft_component.adoc#column-antoramodule[+ssis.PackageTask_Dft_Component.AntoraModule+]
--


[#column-dfttaskcomponentlist]
=== DftTaskComponentList

[cols="d,8a,m,m,m"]
|===
|
|DftTaskComponentList
|nvarchar(max)
|NULL
|
|===


[#column-packagename]
=== PackageName

[cols="d,8a,m,m,m"]
|===
|
|PackageName
|varchar(200)
|NOT NULL
|
|===

.Referenced Columns
--
* xref:ssis.packagetask_dft_component.adoc#column-packagename[+ssis.PackageTask_Dft_Component.PackageName+]
--


[#column-taskpath]
=== TaskPath

[cols="d,8a,m,m,m"]
|===
|
|TaskPath
|varchar(8000)
|NOT NULL
|
|===

.Referenced Columns
--
* xref:ssis.packagetask_dft_component.adoc#column-taskpath[+ssis.PackageTask_Dft_Component.TaskPath+]
--


// end::AntoraColumnDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]




// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]
|
|<<column-antoramodule>>
|varchar(50)
|NOT NULL
|

|
|<<column-dfttaskcomponentlist>>
|nvarchar(max)
|NULL
|

|
|<<column-packagename>>
|varchar(200)
|NOT NULL
|

|
|<<column-taskpath>>
|varchar(8000)
|NOT NULL
|

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

// end::AntoraIndexList[]

== AntoraMeasureDetails

// tag::AntoraMeasureDetails[]

// end::AntoraMeasureDetails[]

== AntoraMeasureDescriptions



== AntoraParameterList

// tag::AntoraParameterList[]

// end::AntoraParameterList[]

== AntoraXrefCulturesList

// tag::AntoraXrefCulturesList[]
* xref:dhw:sqldb:docs.ssis_dfttaskcomponentlist.adoc[] - 
// end::AntoraXrefCulturesList[]

== cultures_count

// tag::cultures_count[]
1
// end::cultures_count[]

== Other tags

source: property.RepoObjectProperty_cross As rop_cross


=== additional_reference_csv

// tag::additional_reference_csv[]

// end::additional_reference_csv[]


=== AdocUspSteps

// tag::adocuspsteps[]

// end::adocuspsteps[]


=== AntoraReferencedList

// tag::antorareferencedlist[]
* xref:dhw:sqldb:docs.fs_cleanstringforanchorid.adoc[]
* xref:dhw:sqldb:docs.fs_cleanstringforheader.adoc[]
* xref:dhw:sqldb:docs.ssis_dfttaskcomponentinputlist.adoc[]
* xref:dhw:sqldb:docs.ssis_dfttaskcomponentoutputlist.adoc[]
* xref:dhw:sqldb:docs.ssis_pumlpartialdftcomponent.adoc[]
* xref:dhw:sqldb:ssis.packagetask_dft_component.adoc[]
// end::antorareferencedlist[]


=== AntoraReferencingList

// tag::antorareferencinglist[]
* xref:dhw:sqldb:docs.ssis_task.adoc[]
* xref:dhw:sqldb:docs.ssis_tasklist.adoc[]
// end::antorareferencinglist[]


=== Description

// tag::description[]

// end::description[]


=== exampleUsage

// tag::exampleusage[]

// end::exampleusage[]


=== exampleUsage_2

// tag::exampleusage_2[]

// end::exampleusage_2[]


=== exampleUsage_3

// tag::exampleusage_3[]

// end::exampleusage_3[]


=== exampleUsage_4

// tag::exampleusage_4[]

// end::exampleusage_4[]


=== exampleUsage_5

// tag::exampleusage_5[]

// end::exampleusage_5[]


=== exampleWrong_Usage

// tag::examplewrong_usage[]

// end::examplewrong_usage[]


=== has_execution_plan_issue

// tag::has_execution_plan_issue[]

// end::has_execution_plan_issue[]


=== has_get_referenced_issue

// tag::has_get_referenced_issue[]

// end::has_get_referenced_issue[]


=== has_history

// tag::has_history[]

// end::has_history[]


=== has_history_columns

// tag::has_history_columns[]

// end::has_history_columns[]


=== InheritanceType

// tag::inheritancetype[]

// end::inheritancetype[]


=== is_persistence

// tag::is_persistence[]

// end::is_persistence[]


=== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]

// end::is_persistence_check_duplicate_per_pk[]


=== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]

// end::is_persistence_check_for_empty_source[]


=== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]

// end::is_persistence_delete_changed[]


=== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]

// end::is_persistence_delete_missing[]


=== is_persistence_insert

// tag::is_persistence_insert[]

// end::is_persistence_insert[]


=== is_persistence_truncate

// tag::is_persistence_truncate[]

// end::is_persistence_truncate[]


=== is_persistence_update_changed

// tag::is_persistence_update_changed[]

// end::is_persistence_update_changed[]


=== is_repo_managed

// tag::is_repo_managed[]
0
// end::is_repo_managed[]


=== is_ssas

// tag::is_ssas[]
0
// end::is_ssas[]


=== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


=== MS_Description

// tag::ms_description[]

// end::ms_description[]


=== persistence_source_RepoObject_fullname

// tag::persistence_source_repoobject_fullname[]

// end::persistence_source_repoobject_fullname[]


=== persistence_source_RepoObject_fullname2

// tag::persistence_source_repoobject_fullname2[]

// end::persistence_source_repoobject_fullname2[]


=== persistence_source_RepoObject_guid

// tag::persistence_source_repoobject_guid[]

// end::persistence_source_repoobject_guid[]


=== persistence_source_RepoObject_xref

// tag::persistence_source_repoobject_xref[]

// end::persistence_source_repoobject_xref[]


=== pk_index_guid

// tag::pk_index_guid[]

// end::pk_index_guid[]


=== pk_IndexPatternColumnDatatype

// tag::pk_indexpatterncolumndatatype[]

// end::pk_indexpatterncolumndatatype[]


=== pk_IndexPatternColumnName

// tag::pk_indexpatterncolumnname[]

// end::pk_indexpatterncolumnname[]


=== pk_IndexSemanticGroup

// tag::pk_indexsemanticgroup[]

// end::pk_indexsemanticgroup[]


=== ReferencedObjectList

// tag::referencedobjectlist[]
* [docs].[fs_cleanStringForAnchorId]
* [docs].[fs_cleanStringForHeader]
* [docs].[ssis_DftTaskComponentInputList]
* [docs].[ssis_DftTaskComponentOutputList]
* [docs].[ssis_PumlPartialDftComponent]
* [ssis].[PackageTask_Dft_Component]
// end::referencedobjectlist[]


=== usp_persistence_RepoObject_guid

// tag::usp_persistence_repoobject_guid[]

// end::usp_persistence_repoobject_guid[]


=== UspExamples

// tag::uspexamples[]

// end::uspexamples[]


=== uspgenerator_usp_id

// tag::uspgenerator_usp_id[]

// end::uspgenerator_usp_id[]


=== UspParameters

// tag::uspparameters[]

// end::uspparameters[]

== Boolean Attributes

source: property.RepoObjectProperty WHERE property_int = 1

// tag::boolean_attributes[]


// end::boolean_attributes[]

== PlantUML diagrams

=== PlantUML Entity

// tag::puml_entity[]
[plantuml, entity-{docname}, svg, subs=macros]
....
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:docs.ssis_dfttaskcomponentlist.adoc[]" as docs.ssis_DftTaskComponentList << V >> {
  - AntoraModule : (varchar(50))
  DftTaskComponentList : (nvarchar(max))
  - PackageName : (varchar(200))
  - TaskPath : (varchar(8000))
  --
}
....

// end::puml_entity[]

=== PlantUML Entity 1 1 FK

// tag::puml_entity_1_1_fk[]
[plantuml, entity_1_1_fk-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:docs.ssis_dfttaskcomponentlist.adoc[]" as docs.ssis_DftTaskComponentList << V >> {

}



footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_fk[]

=== PlantUML 1 1 ObjectRef

// tag::puml_entity_1_1_objectref[]
[plantuml, entity_1_1_objectref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:docs.fs_cleanstringforanchorid.adoc[]" as docs.fs_cleanStringForAnchorId << FN >> {
  --
}

entity "puml-link:dhw:sqldb:docs.fs_cleanstringforheader.adoc[]" as docs.fs_cleanStringForHeader << FN >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_dfttaskcomponentinputlist.adoc[]" as docs.ssis_DftTaskComponentInputList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_dfttaskcomponentlist.adoc[]" as docs.ssis_DftTaskComponentList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_dfttaskcomponentoutputlist.adoc[]" as docs.ssis_DftTaskComponentOutputList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_pumlpartialdftcomponent.adoc[]" as docs.ssis_PumlPartialDftComponent << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_task.adoc[]" as docs.ssis_Task << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_tasklist.adoc[]" as docs.ssis_TaskList << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component.adoc[]" as ssis.PackageTask_Dft_Component << U >> {
  --
}

docs.fs_cleanStringForAnchorId <.. docs.ssis_DftTaskComponentList
docs.fs_cleanStringForHeader <.. docs.ssis_DftTaskComponentList
docs.ssis_DftTaskComponentInputList <.. docs.ssis_DftTaskComponentList
docs.ssis_DftTaskComponentList <.. docs.ssis_TaskList
docs.ssis_DftTaskComponentList <.. docs.ssis_Task
docs.ssis_DftTaskComponentOutputList <.. docs.ssis_DftTaskComponentList
docs.ssis_PumlPartialDftComponent <.. docs.ssis_DftTaskComponentList
ssis.PackageTask_Dft_Component <.. docs.ssis_DftTaskComponentList

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_objectref[]

=== PlantUML 30 0 ObjectRef

// tag::puml_entity_30_0_objectref[]
[plantuml, entity_30_0_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:docs.fs_cleanstringforanchorid.adoc[]" as docs.fs_cleanStringForAnchorId << FN >> {
  --
}

entity "puml-link:dhw:sqldb:docs.fs_cleanstringforfilename.adoc[]" as docs.fs_cleanStringForFilename << FN >> {
  --
}

entity "puml-link:dhw:sqldb:docs.fs_cleanstringforheader.adoc[]" as docs.fs_cleanStringForHeader << FN >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_dfttaskcomponentinputcolumnlist.adoc[]" as docs.ssis_DftTaskComponentInputColumnList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_dfttaskcomponentinputlist.adoc[]" as docs.ssis_DftTaskComponentInputList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_dfttaskcomponentlist.adoc[]" as docs.ssis_DftTaskComponentList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_dfttaskcomponentoutputcolumnlist.adoc[]" as docs.ssis_DftTaskComponentOutputColumnList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_dfttaskcomponentoutputlist.adoc[]" as docs.ssis_DftTaskComponentOutputList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_pumlpartialdftcomponent.adoc[]" as docs.ssis_PumlPartialDftComponent << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.antoramodule_tgt_filter.adoc[]" as ssis.AntoraModule_tgt_filter << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.package_src.adoc[]" as ssis.Package_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component.adoc[]" as ssis.PackageTask_Dft_Component << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_input.adoc[]" as ssis.PackageTask_Dft_Component_input << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_input_externalmetadatacolumn.adoc[]" as ssis.PackageTask_Dft_Component_input_externalMetadataColumn << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_input_externalmetadatacolumn_src.adoc[]" as ssis.PackageTask_Dft_Component_input_externalMetadataColumn_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Column_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_input_externalmetadatacolumn_tgt.adoc[]" as ssis.PackageTask_Dft_Component_input_externalMetadataColumn_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Column_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_input_inputcolumn.adoc[]" as ssis.PackageTask_Dft_Component_input_inputColumn << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_input_inputcolumn_src.adoc[]" as ssis.PackageTask_Dft_Component_input_inputColumn_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Column_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_input_inputcolumn_tgt.adoc[]" as ssis.PackageTask_Dft_Component_input_inputColumn_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Column_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_input_src.adoc[]" as ssis.PackageTask_Dft_Component_input_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **input_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_input_tgt.adoc[]" as ssis.PackageTask_Dft_Component_input_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **input_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_output.adoc[]" as ssis.PackageTask_Dft_Component_output << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_output_outputcolumn.adoc[]" as ssis.PackageTask_Dft_Component_output_outputcolumn << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_output_outputcolumn_src.adoc[]" as ssis.PackageTask_Dft_Component_output_outputcolumn_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Column_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_output_outputcolumn_tgt.adoc[]" as ssis.PackageTask_Dft_Component_output_outputColumn_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Column_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_output_src.adoc[]" as ssis.PackageTask_Dft_Component_output_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **output_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_output_tgt.adoc[]" as ssis.PackageTask_Dft_Component_output_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **output_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_src.adoc[]" as ssis.PackageTask_Dft_Component_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Component_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_tgt.adoc[]" as ssis.PackageTask_Dft_Component_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Component_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.project.adoc[]" as ssis.Project << U >> {
  - **AntoraModule** : (varchar(50))
  --
}

entity "puml-link:dhw:sqldb:ssis_t.pkgstats.adoc[]" as ssis_t.pkgStats << U >> {
  - **RowID** : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tblcontrolflow.adoc[]" as ssis_t.TblControlFlow << U >> {
  - **ControlFlowDetailsRowID** : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_dft_component.adoc[]" as ssis_t.TblTask_Dft_Component << U >> {
  - **DftComponentId** : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_dft_component_inputs_externalmetadatacolumn_src.adoc[]" as ssis_t.TblTask_Dft_Component_inputs_externalMetadataColumn_src << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_dft_component_inputs_inputcolumn_src.adoc[]" as ssis_t.TblTask_Dft_Component_inputs_inputColumn_src << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_dft_component_inputs_src.adoc[]" as ssis_t.TblTask_Dft_Component_inputs_src << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_dft_component_outputs_outputcolumn_src.adoc[]" as ssis_t.TblTask_Dft_Component_outputs_outputColumn_src << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_dft_component_outputs_src.adoc[]" as ssis_t.TblTask_Dft_Component_outputs_src << V >> {
  --
}

docs.fs_cleanStringForAnchorId <.. docs.ssis_PumlPartialDftComponent
docs.fs_cleanStringForAnchorId <.. docs.ssis_DftTaskComponentOutputColumnList
docs.fs_cleanStringForAnchorId <.. docs.ssis_DftTaskComponentInputColumnList
docs.fs_cleanStringForAnchorId <.. docs.ssis_DftTaskComponentInputList
docs.fs_cleanStringForAnchorId <.. docs.ssis_DftTaskComponentList
docs.fs_cleanStringForAnchorId <.. docs.ssis_DftTaskComponentOutputList
docs.fs_cleanStringForFilename <.. docs.ssis_PumlPartialDftComponent
docs.fs_cleanStringForHeader <.. docs.ssis_DftTaskComponentOutputList
docs.fs_cleanStringForHeader <.. docs.ssis_DftTaskComponentOutputColumnList
docs.fs_cleanStringForHeader <.. docs.ssis_DftTaskComponentList
docs.fs_cleanStringForHeader <.. docs.ssis_DftTaskComponentInputColumnList
docs.fs_cleanStringForHeader <.. docs.ssis_DftTaskComponentInputList
docs.ssis_DftTaskComponentInputColumnList <.. docs.ssis_DftTaskComponentInputList
docs.ssis_DftTaskComponentInputList <.. docs.ssis_DftTaskComponentList
docs.ssis_DftTaskComponentOutputColumnList <.. docs.ssis_DftTaskComponentOutputList
docs.ssis_DftTaskComponentOutputList <.. docs.ssis_DftTaskComponentList
docs.ssis_PumlPartialDftComponent <.. docs.ssis_DftTaskComponentList
ssis.AntoraModule_tgt_filter <.. ssis.PackageTask_Dft_Component_output_tgt
ssis.AntoraModule_tgt_filter <.. ssis.PackageTask_Dft_Component_tgt
ssis.AntoraModule_tgt_filter <.. ssis.PackageTask_Dft_Component_input_inputColumn_tgt
ssis.AntoraModule_tgt_filter <.. ssis.PackageTask_Dft_Component_output_outputcolumn_tgt
ssis.AntoraModule_tgt_filter <.. ssis.PackageTask_Dft_Component_input_tgt
ssis.AntoraModule_tgt_filter <.. ssis.PackageTask_Dft_Component_input_externalMetadataColumn_tgt
ssis.Package_src <.. ssis.AntoraModule_tgt_filter
ssis.Package_src <.. ssis.PackageTask_Dft_Component_src
ssis.Package_src <.. ssis.PackageTask_Dft_Component_input_src
ssis.Package_src <.. ssis.PackageTask_Dft_Component_output_src
ssis.Package_src <.. ssis.PackageTask_Dft_Component_output_outputcolumn_src
ssis.Package_src <.. ssis.PackageTask_Dft_Component_input_inputColumn_src
ssis.Package_src <.. ssis.PackageTask_Dft_Component_input_externalMetadataColumn_src
ssis.PackageTask_Dft_Component <.. docs.ssis_DftTaskComponentList
ssis.PackageTask_Dft_Component <.. docs.ssis_PumlPartialDftComponent
ssis.PackageTask_Dft_Component_input <.. docs.ssis_DftTaskComponentInputList
ssis.PackageTask_Dft_Component_input_externalMetadataColumn <.. docs.ssis_DftTaskComponentOutputColumnList
ssis.PackageTask_Dft_Component_input_externalMetadataColumn <.. docs.ssis_DftTaskComponentInputColumnList
ssis.PackageTask_Dft_Component_input_externalMetadataColumn_src <.. ssis.PackageTask_Dft_Component_input_externalMetadataColumn_tgt
ssis.PackageTask_Dft_Component_input_externalMetadataColumn_tgt <.. ssis.PackageTask_Dft_Component_input_externalMetadataColumn
ssis.PackageTask_Dft_Component_input_inputColumn <.. docs.ssis_DftTaskComponentInputColumnList
ssis.PackageTask_Dft_Component_input_inputColumn_src <.. ssis.PackageTask_Dft_Component_input_inputColumn_tgt
ssis.PackageTask_Dft_Component_input_inputColumn_tgt <.. ssis.PackageTask_Dft_Component_input_inputColumn
ssis.PackageTask_Dft_Component_input_src <.. ssis.PackageTask_Dft_Component_input_tgt
ssis.PackageTask_Dft_Component_input_tgt <.. ssis.PackageTask_Dft_Component_input
ssis.PackageTask_Dft_Component_output <.. docs.ssis_DftTaskComponentOutputList
ssis.PackageTask_Dft_Component_output_outputcolumn <.. docs.ssis_DftTaskComponentOutputColumnList
ssis.PackageTask_Dft_Component_output_outputcolumn_src <.. ssis.PackageTask_Dft_Component_output_outputcolumn_tgt
ssis.PackageTask_Dft_Component_output_outputcolumn_tgt <.. ssis.PackageTask_Dft_Component_output_outputcolumn
ssis.PackageTask_Dft_Component_output_src <.. ssis.PackageTask_Dft_Component_output_tgt
ssis.PackageTask_Dft_Component_output_tgt <.. ssis.PackageTask_Dft_Component_output
ssis.PackageTask_Dft_Component_src <.. ssis.PackageTask_Dft_Component_tgt
ssis.PackageTask_Dft_Component_tgt <.. ssis.PackageTask_Dft_Component
ssis.Project <.. ssis.Package_src
ssis_t.pkgStats <.. ssis.Package_src
ssis_t.TblControlFlow <.. ssis.PackageTask_Dft_Component_src
ssis_t.TblControlFlow <.. ssis.PackageTask_Dft_Component_input_src
ssis_t.TblControlFlow <.. ssis.PackageTask_Dft_Component_output_src
ssis_t.TblControlFlow <.. ssis.PackageTask_Dft_Component_output_outputcolumn_src
ssis_t.TblControlFlow <.. ssis.PackageTask_Dft_Component_input_inputColumn_src
ssis_t.TblControlFlow <.. ssis.PackageTask_Dft_Component_input_externalMetadataColumn_src
ssis_t.TblTask_Dft_Component <.. ssis.PackageTask_Dft_Component_src
ssis_t.TblTask_Dft_Component <.. ssis_t.TblTask_Dft_Component_outputs_src
ssis_t.TblTask_Dft_Component <.. ssis_t.TblTask_Dft_Component_inputs_src
ssis_t.TblTask_Dft_Component <.. ssis_t.TblTask_Dft_Component_inputs_externalMetadataColumn_src
ssis_t.TblTask_Dft_Component <.. ssis_t.TblTask_Dft_Component_inputs_inputColumn_src
ssis_t.TblTask_Dft_Component <.. ssis_t.TblTask_Dft_Component_outputs_outputColumn_src
ssis_t.TblTask_Dft_Component_inputs_externalMetadataColumn_src <.. ssis.PackageTask_Dft_Component_input_externalMetadataColumn_src
ssis_t.TblTask_Dft_Component_inputs_inputColumn_src <.. ssis.PackageTask_Dft_Component_input_inputColumn_src
ssis_t.TblTask_Dft_Component_inputs_src <.. ssis.PackageTask_Dft_Component_input_src
ssis_t.TblTask_Dft_Component_outputs_outputColumn_src <.. ssis.PackageTask_Dft_Component_output_outputcolumn_src
ssis_t.TblTask_Dft_Component_outputs_src <.. ssis.PackageTask_Dft_Component_output_src

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_30_0_objectref[]

=== PlantUML 0 30 ObjectRef

// tag::puml_entity_0_30_objectref[]
[plantuml, entity_0_30_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:docs.ssis_adoc.adoc[]" as docs.ssis_Adoc << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageBasename** : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_adoc_t.adoc[]" as docs.ssis_Adoc_T << U >> {
  - **AntoraModule** : (varchar(50))
  **PackageBasename** : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_dfttaskcomponentlist.adoc[]" as docs.ssis_DftTaskComponentList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_task.adoc[]" as docs.ssis_Task << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_tasklist.adoc[]" as docs.ssis_TaskList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport.adoc[]" as docs.usp_AntoraExport << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_ssispartialscontent.adoc[]" as docs.usp_AntoraExport_SsisPartialsContent << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_ssis_adoc_t.adoc[]" as docs.usp_PERSIST_ssis_Adoc_T << P >> {
  --
}

docs.ssis_Adoc <.. docs.usp_PERSIST_ssis_Adoc_T
docs.ssis_Adoc <.. docs.ssis_Adoc_T
docs.ssis_Adoc_T <.. docs.usp_AntoraExport_SsisPartialsContent
docs.ssis_Adoc_T <.. docs.usp_PERSIST_ssis_Adoc_T
docs.ssis_DftTaskComponentList <.. docs.ssis_TaskList
docs.ssis_DftTaskComponentList <.. docs.ssis_Task
docs.ssis_TaskList <.. docs.ssis_Adoc
docs.usp_AntoraExport_SsisPartialsContent <.. docs.usp_AntoraExport
docs.usp_PERSIST_ssis_Adoc_T <.. docs.usp_AntoraExport_SsisPartialsContent

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_0_30_objectref[]

=== PlantUML 1 1 ColumnRef

// tag::puml_entity_1_1_colref[]
[plantuml, entity_1_1_colref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:docs.fs_cleanstringforanchorid.adoc[]" as docs.fs_cleanStringForAnchorId << FN >> {
  --
}

entity "puml-link:dhw:sqldb:docs.fs_cleanstringforheader.adoc[]" as docs.fs_cleanStringForHeader << FN >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_dfttaskcomponentinputlist.adoc[]" as docs.ssis_DftTaskComponentInputList << V >> {
  - AntoraModule : (varchar(50))
  Component_refId : (varchar(max))
  DftTaskComponentInputList : (nvarchar(max))
  PackageName : (varchar(200))
  TaskPath : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_dfttaskcomponentlist.adoc[]" as docs.ssis_DftTaskComponentList << V >> {
  - AntoraModule : (varchar(50))
  DftTaskComponentList : (nvarchar(max))
  - PackageName : (varchar(200))
  - TaskPath : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_dfttaskcomponentoutputlist.adoc[]" as docs.ssis_DftTaskComponentOutputList << V >> {
  - AntoraModule : (varchar(50))
  Component_refId : (varchar(max))
  DftTaskComponentOutputList : (nvarchar(max))
  PackageName : (varchar(200))
  TaskPath : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_pumlpartialdftcomponent.adoc[]" as docs.ssis_PumlPartialDftComponent << V >> {
  - AntoraModule : (varchar(50))
  - Component_name : (varchar(max))
  - Component_refId : (varchar(max))
  - PackageName : (varchar(200))
  PumlPartialDftComponent : (nvarchar(max))
  - TaskPath : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_task.adoc[]" as docs.ssis_Task << V >> {
  AdocFilename : (nvarchar(4000))
  - AntoraModule : (varchar(50))
  - PackageName : (varchar(200))
  - TaskContent : (nvarchar(max))
  - TaskPath : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_tasklist.adoc[]" as docs.ssis_TaskList << V >> {
  - AntoraModule : (varchar(50))
  - PackageName : (varchar(200))
  TaskList : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component.adoc[]" as ssis.PackageTask_Dft_Component << U >> {
  - AntoraModule : (varchar(50))
  Component_AccessMode : (varchar(max))
  Component_AlwaysUseDefaultCodePage : (varchar(max))
  Component_CommandTimeout : (int)
  Component_componentClassID : (varchar(max))
  Component_Connection_description : (varchar(max))
  Component_Connection_name : (varchar(max))
  Component_Connection_refId : (varchar(max))
  Component_connectionManagerID : (varchar(max))
  Component_connectionManagerRefId : (varchar(max))
  Component_ContactInfo : (varchar(max))
  Component_DefaultCodePage : (int)
  Component_description : (varchar(max))
  Component_FastLoadKeepIdentity : (bit)
  Component_FastLoadKeepNulls : (bit)
  Component_FastLoadMaxInsertCommitSize : (int)
  Component_FastLoadOptions : (varchar(max))
  Component_IsSortedProperty : (varchar(10))
  - Component_name : (varchar(max))
  Component_OpenRowset : (varchar(max))
  Component_OpenRowsetVariable : (varchar(max))
  Component_ParameterMapping : (varchar(max))
  - Component_refId : (varchar(max))
  Component_SqlCommand : (varchar(max))
  Component_SqlCommandVariable : (varchar(max))
  Component_VariableName : (varchar(max))
  - ControlFlowDetailsRowID : (int)
  - PackageName : (varchar(200))
  - TaskPath : (varchar(8000))
  ~ Component_ConnectionManagerName : (varchar(max))
  # PackageBasename : (varchar(8000))
  --
}

docs.fs_cleanStringForAnchorId <.. docs.ssis_DftTaskComponentList
docs.fs_cleanStringForHeader <.. docs.ssis_DftTaskComponentList
docs.ssis_DftTaskComponentInputList <.. docs.ssis_DftTaskComponentList
docs.ssis_DftTaskComponentList <.. docs.ssis_TaskList
docs.ssis_DftTaskComponentList <.. docs.ssis_Task
docs.ssis_DftTaskComponentOutputList <.. docs.ssis_DftTaskComponentList
docs.ssis_PumlPartialDftComponent <.. docs.ssis_DftTaskComponentList
ssis.PackageTask_Dft_Component <.. docs.ssis_DftTaskComponentList
"ssis.PackageTask_Dft_Component::AntoraModule" <-- "docs.ssis_DftTaskComponentList::AntoraModule"
"ssis.PackageTask_Dft_Component::PackageName" <-- "docs.ssis_DftTaskComponentList::PackageName"
"ssis.PackageTask_Dft_Component::TaskPath" <-- "docs.ssis_DftTaskComponentList::TaskPath"

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_colref[]


== sql_modules_definition

// tag::sql_modules_definition[]
[%collapsible]
=======
[source,sql,numbered,indent=0]
----
CREATE View [docs].[ssis_DftTaskComponentList]
As
Select
    T1.AntoraModule
  , T1.PackageName
  , T1.TaskPath
  , DftTaskComponentList =
  --
  String_Agg (
                 Concat (
                            Cast(N'' As NVarchar(Max))
                          , '[#dftcomponent-'
                          , docs.fs_cleanStringForAnchorId ( T1.Component_refId )
                          , ']'
                          , Char ( 13 ) + Char ( 10 )
                          , '==== '
                          , docs.fs_cleanStringForHeader ( T1.Component_name )
                          , Char ( 13 ) + Char ( 10 ) + Char ( 13 ) + Char ( 10 )

                          ----begin collapsible
                          --, '.' + docs.fs_cleanStringForHeader ( T1.Component_name ) + Char ( 13 ) + Char ( 10 )
                          --, '[%collapsible]' + Char ( 13 ) + Char ( 10 )
                          --, '======' + Char ( 13 ) + Char ( 10 )

                          --table start
                          , '[cols="1,4l"]' + Char ( 13 ) + Char ( 10 )
                          , '|===' + Char ( 13 ) + Char ( 10 )
                          , Char ( 13 ) + Char ( 10 )

                          --table content
                          , '|' + 'Component refId' + Char ( 13 ) + Char ( 10 ) + '|' + T1.Component_refId
                            + Char ( 13 ) + Char ( 10 ) + Char ( 13 ) + Char ( 10 )
                          , '|' + 'componentClassID' + Char ( 13 ) + Char ( 10 ) + '|' + T1.Component_componentClassID
                            + Char ( 13 ) + Char ( 10 ) + Char ( 13 ) + Char ( 10 )
                          , '|' + 'description' + Char ( 13 ) + Char ( 10 ) + '|' + T1.Component_description
                            + Char ( 13 ) + Char ( 10 ) + Char ( 13 ) + Char ( 10 )
                          , '|' + 'ContactInfo' + Char ( 13 ) + Char ( 10 ) + '|' + T1.Component_ContactInfo
                            + Char ( 13 ) + Char ( 10 ) + Char ( 13 ) + Char ( 10 )
                          , '|' + 'CommandTimeout' + Char ( 13 ) + Char ( 10 ) + '|'
                            + Cast(T1.Component_CommandTimeout As NVarchar(50)) + Char ( 13 ) + Char ( 10 )
                            + Char ( 13 ) + Char ( 10 )
                          , Iif(T1.Component_OpenRowset <> ''
                              , '|' + 'OpenRowset' + Char ( 13 ) + Char ( 10 ) + '|' + T1.Component_OpenRowset
                                + Char ( 13 ) + Char ( 10 ) + Char ( 13 ) + Char ( 10 )
                              , '')
                          , Iif(T1.Component_OpenRowsetVariable <> ''
                              , '|' + 'OpenRowsetVariable' + Char ( 13 ) + Char ( 10 ) + '|'
                                + T1.Component_OpenRowsetVariable + Char ( 13 ) + Char ( 10 ) + Char ( 13 )
                                + Char ( 10 )
                              , '')
                          , Iif(T1.Component_SqlCommand <> ''
                              , '|' + 'SqlCommand' + Char ( 13 ) + Char ( 10 ) + '|' + T1.Component_SqlCommand
                                + Char ( 13 ) + Char ( 10 ) + Char ( 13 ) + Char ( 10 )
                              , '')
                          , Iif(T1.Component_SqlCommandVariable <> ''
                              , '|' + 'SqlCommandVariable' + Char ( 13 ) + Char ( 10 ) + '|'
                                + T1.Component_SqlCommandVariable + Char ( 13 ) + Char ( 10 ) + Char ( 13 )
                                + Char ( 10 )
                              , '')
                          , Iif(T1.Component_DefaultCodePage <> 0
                              , '|' + 'DefaultCodePage' + Char ( 13 ) + Char ( 10 ) + '|'
                                + Cast(T1.Component_DefaultCodePage As Varchar(10)) + Char ( 13 ) + Char ( 10 )
                                + Char ( 13 ) + Char ( 10 )
                              , '')
                          , Iif(T1.Component_AlwaysUseDefaultCodePage <> ''
                              , '|' + 'AlwaysUseDefaultCodePage' + Char ( 13 ) + Char ( 10 ) + '|'
                                + T1.Component_AlwaysUseDefaultCodePage + Char ( 13 ) + Char ( 10 ) + Char ( 13 )
                                + Char ( 10 )
                              , '')
                          , Iif(T1.Component_ParameterMapping <> ''
                              , '|' + 'ParameterMapping' + Char ( 13 ) + Char ( 10 ) + '|'
                                + T1.Component_ParameterMapping + Char ( 13 ) + Char ( 10 ) + Char ( 13 ) + Char ( 10 )
                              , '')
                          , Iif(Not T1.Component_FastLoadKeepIdentity Is Null
                              , '|' + 'FastLoadKeepIdentity' + Char ( 13 ) + Char ( 10 ) + '|'
                                + Cast(T1.Component_FastLoadKeepIdentity As Varchar(10)) + Char ( 13 ) + Char ( 10 )
                                + Char ( 13 ) + Char ( 10 )
                              , '')
                          , Iif(Not T1.Component_FastLoadKeepNulls Is Null
                              , '|' + 'FastLoadKeepNulls' + Char ( 13 ) + Char ( 10 ) + '|'
                                + Cast(T1.Component_FastLoadKeepNulls As Varchar(10)) + Char ( 13 ) + Char ( 10 )
                                + Char ( 13 ) + Char ( 10 )
                              , '')
                          , Iif(T1.Component_FastLoadOptions <> ''
                              , '|' + 'FastLoadOptions' + Char ( 13 ) + Char ( 10 ) + '|'
                                + T1.Component_FastLoadOptions + Char ( 13 ) + Char ( 10 ) + Char ( 13 ) + Char ( 10 )
                              , '')
                          , Iif(Not T1.Component_FastLoadMaxInsertCommitSize Is Null
                              , '|' + 'FastLoadMaxInsertCommitSize' + Char ( 13 ) + Char ( 10 ) + '|'
                                + Cast(T1.Component_FastLoadMaxInsertCommitSize As Varchar(10)) + Char ( 13 )
                                + Char ( 10 ) + Char ( 13 ) + Char ( 10 )
                              , '')
                          , Iif(T1.Component_VariableName <> ''
                              , '|' + 'VariableName' + Char ( 13 ) + Char ( 10 ) + '|' + T1.Component_VariableName
                                + Char ( 13 ) + Char ( 10 ) + Char ( 13 ) + Char ( 10 )
                              , '')
                          , Iif(T1.Component_Connection_refId <> ''
                              , '|' + 'Connection_refId' + Char ( 13 ) + Char ( 10 ) + '|'
                                + T1.Component_Connection_refId + Char ( 13 ) + Char ( 10 ) + Char ( 13 ) + Char ( 10 )
                              , '')
                          , Iif(T1.Component_connectionManagerID <> ''
                              , '|' + 'connectionManagerID' + Char ( 13 ) + Char ( 10 ) + '|'
                                + T1.Component_connectionManagerID + Char ( 13 ) + Char ( 10 ) + Char ( 13 )
                                + Char ( 10 )
                              , '')
                          , Iif(T1.Component_connectionManagerRefId <> ''
                              , '|' + 'connectionManagerRefId +' + Char ( 13 ) + Char ( 10 ) + ' <<connection-'
                                + docs.fs_cleanStringForAnchorId ( T1.Component_ConnectionManagerName ) + '>>'
                                + Char ( 13 ) + Char ( 10 ) + '|' + T1.Component_connectionManagerRefId + Char ( 13 )
                                + Char ( 10 ) + Char ( 13 ) + Char ( 10 )
                              , '')
                          , Iif(T1.Component_Connection_name <> ''
                              , '|' + 'Connection_name' + Char ( 13 ) + Char ( 10 ) + '|'
                                + T1.Component_Connection_name + Char ( 13 ) + Char ( 10 ) + Char ( 13 ) + Char ( 10 )
                              , '')
                          , Iif(T1.Component_IsSortedProperty <> ''
                              , '|' + 'IsSortedProperty' + Char ( 13 ) + Char ( 10 ) + '|'
                                + T1.Component_IsSortedProperty + Char ( 13 ) + Char ( 10 ) + Char ( 13 ) + Char ( 10 )
                              , '')

                          --table end
                          , '|===' + Char ( 13 ) + Char ( 10 )
                          , Char ( 13 ) + Char ( 10 ) + T3.DftTaskComponentInputList + Char ( 13 ) + Char ( 10 )
                          , Char ( 13 ) + Char ( 10 ) + T4.DftTaskComponentOutputList + Char ( 13 ) + Char ( 10 )

                          ----end collapsible
                          --, '======' + Char ( 13 ) + Char ( 10 )
                        )
               , Char ( 13 ) + Char ( 10 )
             ) Within Group(Order By
                                T1.Component_refId)
From
    ssis.PackageTask_Dft_Component           As T1
    Left Join
        docs.ssis_PumlPartialDftComponent    As T2
            On
            T2.AntoraModule        = T1.AntoraModule
            And T2.PackageName     = T1.PackageName
            And T2.TaskPath        = T1.TaskPath
            And T2.Component_refId = T1.Component_refId

    Left Join
        docs.ssis_DftTaskComponentInputList  As T3
            On
            T3.AntoraModule        = T1.AntoraModule
            And T3.PackageName     = T1.PackageName
            And T3.TaskPath        = T1.TaskPath
            And T3.Component_refId = T1.Component_refId

    Left Join
        docs.ssis_DftTaskComponentOutputList As T4
            On
            T4.AntoraModule        = T1.AntoraModule
            And T4.PackageName     = T1.PackageName
            And T4.TaskPath        = T1.TaskPath
            And T4.Component_refId = T1.Component_refId
Group By
    T1.AntoraModule
  , T1.PackageName
  , T1.TaskPath

----
=======
// end::sql_modules_definition[]


