// tag::HeaderFullDisplayName[]
= docs.RepoObject_OutputFilter_T - U
// end::HeaderFullDisplayName[]

== existing_properties

// tag::existing_properties[]

:ExistsProperty--antorareferencedlist:
:ExistsProperty--antorareferencinglist:
:ExistsProperty--has_history:
:ExistsProperty--has_history_columns:
:ExistsProperty--inheritancetype:
:ExistsProperty--is_persistence:
:ExistsProperty--is_persistence_check_duplicate_per_pk:
:ExistsProperty--is_persistence_check_for_empty_source:
:ExistsProperty--is_persistence_delete_changed:
:ExistsProperty--is_persistence_delete_missing:
:ExistsProperty--is_persistence_insert:
:ExistsProperty--is_persistence_truncate:
:ExistsProperty--is_persistence_update_changed:
:ExistsProperty--is_repo_managed:
:ExistsProperty--is_ssas:
:ExistsProperty--persistence_source_repoobject_fullname:
:ExistsProperty--persistence_source_repoobject_fullname2:
:ExistsProperty--persistence_source_repoobject_guid:
:ExistsProperty--persistence_source_repoobject_xref:
:ExistsProperty--pk_index_guid:
:ExistsProperty--pk_indexpatterncolumndatatype:
:ExistsProperty--pk_indexpatterncolumnname:
:ExistsProperty--referencedobjectlist:
:ExistsProperty--usp_persistence_repoobject_guid:
:ExistsProperty--FK:
:ExistsProperty--AntoraIndexList:
:ExistsProperty--Columns:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
16EBFF08-7824-EC11-8526-A81E8446D5B0
// end::RepoObject_guid[]

== RepoObject_FullDisplayName2

// tag::RepoObject_FullDisplayName2[]
docs.RepoObject_OutputFilter_T
// end::RepoObject_FullDisplayName2[]

== SysObject_type

// tag::SysObject_type[]
U 
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
user table
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
21627170
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2022-01-23 14:10:08
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]
[discrete]
== _


[#column-repoobjectunderlineguid]
=== RepoObject_guid

[cols="d,8a,m,m,m"]
|===
|1
|*RepoObject_guid*
|uniqueidentifier
|NOT NULL
|
|===

.Referenced Columns
--
* xref:docs.repoobject_outputfilter.adoc#column-repoobjectunderlineguid[+docs.RepoObject_OutputFilter.RepoObject_guid+]
--

.Referencing Columns
--
* xref:docs.repoobject_antoraxrefcultureslist.adoc#column-repoobjectunderlineguid[+docs.RepoObject_AntoraXrefCulturesList.RepoObject_guid+]
* xref:docs.repoobject_columnlist.adoc#column-repoobjectunderlineguid[+docs.RepoObject_ColumnList.RepoObject_guid+]
* xref:docs.repoobject_outputfilter_t_gross.adoc#column-repoobjectunderlineguid[+docs.RepoObject_OutputFilter_T_gross.RepoObject_guid+]
* xref:docs.repoobject_plantuml_colreflist_1_1.adoc#column-repoobjectunderlineguid[+docs.RepoObject_Plantuml_ColRefList_1_1.RepoObject_guid+]
* xref:docs.repoobject_plantuml_entity.adoc#column-repoobjectunderlineguid[+docs.RepoObject_Plantuml_Entity.RepoObject_guid+]
--


[#column-culturesunderlinename]
=== cultures_name

[cols="d,8a,m,m,m"]
|===
|2
|*cultures_name*
|nvarchar(10)
|NOT NULL
|
|===

.Referenced Columns
--
* xref:docs.repoobject_outputfilter.adoc#column-culturesunderlinename[+docs.RepoObject_OutputFilter.cultures_name+]
--

.Referencing Columns
--
* xref:docs.antoranavlistpage_by_schema.adoc#column-culturesunderlinename[+docs.AntoraNavListPage_by_schema.cultures_name+]
* xref:docs.antoranavlistrepoobject_by_schema.adoc#column-culturesunderlinename[+docs.AntoraNavListRepoObject_by_schema.cultures_name+]
* xref:docs.antoranavlistrepoobject_by_schema_type.adoc#column-culturesunderlinename[+docs.AntoraNavListRepoObject_by_schema_type.cultures_name+]
* xref:docs.antoranavlistrepoobject_by_type.adoc#column-culturesunderlinename[+docs.AntoraNavListRepoObject_by_type.cultures_name+]
* xref:docs.indexsemanticgrouppatterndatatype.adoc#column-culturesunderlinename[+docs.IndexSemanticgroupPatterndatatype.cultures_name+]
* xref:docs.repoobject_columnlist.adoc#column-culturesunderlinename[+docs.RepoObject_ColumnList.cultures_name+]
* xref:docs.repoobject_indexlist.adoc#column-culturesunderlinename[+docs.RepoObject_IndexList.cultures_name+]
* xref:docs.repoobject_outputfilter_t_gross.adoc#column-culturesunderlinename[+docs.RepoObject_OutputFilter_T_gross.cultures_name+]
* xref:docs.repoobject_plantuml.adoc#column-culturesunderlinename[+docs.RepoObject_Plantuml.cultures_name+]
* xref:docs.repoobject_plantuml_colreflist_1_1.adoc#column-culturesunderlinename[+docs.RepoObject_Plantuml_ColRefList_1_1.cultures_name+]
* xref:docs.repoobject_plantuml_entity.adoc#column-culturesunderlinename[+docs.RepoObject_Plantuml_Entity.cultures_name+]
--


[#column-antoracomponent]
=== AntoraComponent

[cols="d,8a,m,m,m"]
|===
|
|AntoraComponent
|nvarchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:docs.repoobject_outputfilter.adoc#column-antoracomponent[+docs.RepoObject_OutputFilter.AntoraComponent+]
--

.Referencing Columns
--
* xref:docs.repoobject_outputfilter_t_gross.adoc#column-antoracomponent[+docs.RepoObject_OutputFilter_T_gross.AntoraComponent+]
--


[#column-antoramodule]
=== AntoraModule

[cols="d,8a,m,m,m"]
|===
|
|AntoraModule
|nvarchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:docs.repoobject_outputfilter.adoc#column-antoramodule[+docs.RepoObject_OutputFilter.AntoraModule+]
--

.Referencing Columns
--
* xref:docs.repoobject_outputfilter_t_gross.adoc#column-antoramodule[+docs.RepoObject_OutputFilter_T_gross.AntoraModule+]
--


[#column-externalunderlineantoracomponent]
=== external_AntoraComponent

[cols="d,8a,m,m,m"]
|===
|
|external_AntoraComponent
|nvarchar(128)
|NULL
|
|===

.Referenced Columns
--
* xref:docs.repoobject_outputfilter.adoc#column-externalunderlineantoracomponent[+docs.RepoObject_OutputFilter.external_AntoraComponent+]
--

.Referencing Columns
--
* xref:docs.repoobject_outputfilter_t_gross.adoc#column-externalunderlineantoracomponent[+docs.RepoObject_OutputFilter_T_gross.external_AntoraComponent+]
--


[#column-externalunderlineantoramodule]
=== external_AntoraModule

[cols="d,8a,m,m,m"]
|===
|
|external_AntoraModule
|nvarchar(128)
|NULL
|
|===

.Referenced Columns
--
* xref:docs.repoobject_outputfilter.adoc#column-externalunderlineantoramodule[+docs.RepoObject_OutputFilter.external_AntoraModule+]
--

.Referencing Columns
--
* xref:docs.repoobject_outputfilter_t_gross.adoc#column-externalunderlineantoramodule[+docs.RepoObject_OutputFilter_T_gross.external_AntoraModule+]
--


[#column-externalunderlinedatabasename]
=== external_DatabaseName

[cols="d,8a,m,m,m"]
|===
|
|external_DatabaseName
|nvarchar(128)
|NULL
|
|===

.Referenced Columns
--
* xref:docs.repoobject_outputfilter.adoc#column-externalunderlinedatabasename[+docs.RepoObject_OutputFilter.external_DatabaseName+]
--

.Referencing Columns
--
* xref:docs.repoobject_outputfilter_t_gross.adoc#column-externalunderlinedatabasename[+docs.RepoObject_OutputFilter_T_gross.external_DatabaseName+]
--


[#column-isunderlinedocsoutput]
=== is_DocsOutput

[cols="d,8a,m,m,m"]
|===
|
|is_DocsOutput
|int
|NULL
|
|===

.Referenced Columns
--
* xref:docs.repoobject_outputfilter.adoc#column-isunderlinedocsoutput[+docs.RepoObject_OutputFilter.is_DocsOutput+]
--

.Referencing Columns
--
* xref:docs.repoobject_outputfilter_t_gross.adoc#column-isunderlinedocsoutput[+docs.RepoObject_OutputFilter_T_gross.is_DocsOutput+]
--


[#column-isunderlineexternal]
=== is_external

[cols="d,8a,m,m,m"]
|===
|
|is_external
|bit
|NOT NULL
|
|===

.Referenced Columns
--
* xref:docs.repoobject_outputfilter.adoc#column-isunderlineexternal[+docs.RepoObject_OutputFilter.is_external+]
--

.Referencing Columns
--
* xref:docs.repoobject_columnlist.adoc#column-isunderlineexternal[+docs.RepoObject_ColumnList.is_external+]
* xref:docs.repoobject_outputfilter_t_gross.adoc#column-isunderlineexternal[+docs.RepoObject_OutputFilter_T_gross.is_external+]
--


[#column-isunderlinessas]
=== is_ssas

[cols="d,8a,m,m,m"]
|===
|
|is_ssas
|bit
|NOT NULL
|
|===

.Referenced Columns
--
* xref:docs.repoobject_outputfilter.adoc#column-isunderlinessas[+docs.RepoObject_OutputFilter.is_ssas+]
--

.Referencing Columns
--
* xref:docs.antoranavlistrepoobject_by_schema.adoc#column-isunderlinessas[+docs.AntoraNavListRepoObject_by_schema.is_ssas+]
* xref:docs.repoobject_outputfilter_t_gross.adoc#column-isunderlinessas[+docs.RepoObject_OutputFilter_T_gross.is_ssas+]
--


[#column-pumlentitytopdefault]
=== PumlEntityTopDefault

[cols="d,8a,m,m,m"]
|===
|
|PumlEntityTopDefault
|nvarchar(max)
|NOT NULL
|
|===

.Referenced Columns
--
* xref:docs.repoobject_outputfilter.adoc#column-pumlentitytopdefault[+docs.RepoObject_OutputFilter.PumlEntityTopDefault+]
--

.Referencing Columns
--
* xref:docs.repoobject_outputfilter_t_gross.adoc#column-pumlentitytopdefault[+docs.RepoObject_OutputFilter_T_gross.PumlEntityTopDefault+]
--


[#column-pumlentitytopworkaround]
=== PumlEntityTopWorkaround

[cols="d,8a,m,m,m"]
|===
|
|PumlEntityTopWorkaround
|nvarchar(max)
|NOT NULL
|
|===

.Referenced Columns
--
* xref:docs.repoobject_outputfilter.adoc#column-pumlentitytopworkaround[+docs.RepoObject_OutputFilter.PumlEntityTopWorkaround+]
--

.Referencing Columns
--
* xref:docs.repoobject_outputfilter_t_gross.adoc#column-pumlentitytopworkaround[+docs.RepoObject_OutputFilter_T_gross.PumlEntityTopWorkaround+]
--


[#column-repoobjectunderlinedisplayname]
=== RepoObject_DisplayName

[cols="d,8a,m,m,m"]
|===
|
|RepoObject_DisplayName
|nvarchar(128)
|NULL
|
|===

.Referenced Columns
--
* xref:docs.repoobject_outputfilter.adoc#column-repoobjectunderlinedisplayname[+docs.RepoObject_OutputFilter.RepoObject_DisplayName+]
--

.Referencing Columns
--
* xref:docs.repoobject_outputfilter_t_gross.adoc#column-repoobjectunderlinedisplayname[+docs.RepoObject_OutputFilter_T_gross.RepoObject_DisplayName+]
--


[#column-repoobjectunderlinefulldisplayname2]
=== RepoObject_FullDisplayName2

[cols="d,8a,m,m,m"]
|===
|
|RepoObject_FullDisplayName2
|nvarchar(257)
|NULL
|
|===

.Referenced Columns
--
* xref:docs.repoobject_outputfilter.adoc#column-repoobjectunderlinefulldisplayname2[+docs.RepoObject_OutputFilter.RepoObject_FullDisplayName2+]
--

.Referencing Columns
--
* xref:docs.repoobject_outputfilter_t_gross.adoc#column-repoobjectunderlinefulldisplayname2[+docs.RepoObject_OutputFilter_T_gross.RepoObject_FullDisplayName2+]
--


[#column-repoobjectunderlinefullname]
=== RepoObject_fullname

[cols="d,8a,m,m,m"]
|===
|
|RepoObject_fullname
|nvarchar(261)
|NOT NULL
|
|===

.Description
--
(concat('[',[RepoObject_schema_name],'].[',[RepoObject_name],']'))
--
{empty} +

.Referenced Columns
--
* xref:docs.repoobject_outputfilter.adoc#column-repoobjectunderlinefullname[+docs.RepoObject_OutputFilter.RepoObject_fullname+]
--

.Referencing Columns
--
* xref:docs.repoobject_outputfilter_t_gross.adoc#column-repoobjectunderlinefullname[+docs.RepoObject_OutputFilter_T_gross.RepoObject_fullname+]
--


[#column-repoobjectunderlinefullname2]
=== RepoObject_fullname2

[cols="d,8a,m,m,m"]
|===
|
|RepoObject_fullname2
|nvarchar(257)
|NOT NULL
|
|===

.Description
--
(concat([RepoObject_schema_name],'.',[RepoObject_name]))
--
{empty} +

.Referenced Columns
--
* xref:docs.repoobject_outputfilter.adoc#column-repoobjectunderlinefullname2[+docs.RepoObject_OutputFilter.RepoObject_fullname2+]
--

.Referencing Columns
--
* xref:docs.repoobject_outputfilter_t_gross.adoc#column-repoobjectunderlinefullname2[+docs.RepoObject_OutputFilter_T_gross.RepoObject_fullname2+]
* xref:docs.repoobject_plantuml_entity.adoc#column-repoobjectunderlinefullname2[+docs.RepoObject_Plantuml_Entity.RepoObject_fullname2+]
--


[#column-repoobjectunderlinename]
=== RepoObject_name

[cols="d,8a,m,m,m"]
|===
|
|RepoObject_name
|nvarchar(128)
|NOT NULL
|
|===

.Referenced Columns
--
* xref:docs.repoobject_outputfilter.adoc#column-repoobjectunderlinename[+docs.RepoObject_OutputFilter.RepoObject_name+]
--

.Referencing Columns
--
* xref:docs.repoobject_outputfilter_t_gross.adoc#column-repoobjectunderlinename[+docs.RepoObject_OutputFilter_T_gross.RepoObject_name+]
--


[#column-repoobjectunderlineschemaunderlinename]
=== RepoObject_schema_name

[cols="d,8a,m,m,m"]
|===
|
|RepoObject_schema_name
|nvarchar(128)
|NOT NULL
|
|===

.Referenced Columns
--
* xref:docs.repoobject_outputfilter.adoc#column-repoobjectunderlineschemaunderlinename[+docs.RepoObject_OutputFilter.RepoObject_schema_name+]
--

.Referencing Columns
--
* xref:docs.antoranavlistrepoobject_by_schema.adoc#column-repoobjectunderlineschemaunderlinename[+docs.AntoraNavListRepoObject_by_schema.RepoObject_schema_name+]
* xref:docs.antoranavlistrepoobject_by_schema_type.adoc#column-repoobjectunderlineschemaunderlinename[+docs.AntoraNavListRepoObject_by_schema_type.RepoObject_schema_name+]
* xref:docs.repoobject_outputfilter_t_gross.adoc#column-repoobjectunderlineschemaunderlinename[+docs.RepoObject_OutputFilter_T_gross.RepoObject_schema_name+]
* xref:docs.repoobject_plantuml_entity.adoc#column-repoobjectunderlineschemaunderlinename[+docs.RepoObject_Plantuml_Entity.RepoObject_schema_name+]
--


[#column-repoobjectunderlinetranslation]
=== RepoObject_translation

[cols="d,8a,m,m,m"]
|===
|
|RepoObject_translation
|nvarchar(128)
|NULL
|
|===

.Referenced Columns
--
* xref:docs.repoobject_outputfilter.adoc#column-repoobjectunderlinetranslation[+docs.RepoObject_OutputFilter.RepoObject_translation+]
--

.Referencing Columns
--
* xref:docs.repoobject_outputfilter_t_gross.adoc#column-repoobjectunderlinetranslation[+docs.RepoObject_OutputFilter_T_gross.RepoObject_translation+]
--


[#column-sysobjectunderlinetype]
=== SysObject_type

[cols="d,8a,m,m,m"]
|===
|
|SysObject_type
|char(2)
|NULL
|
|===

.Referenced Columns
--
* xref:docs.repoobject_outputfilter.adoc#column-sysobjectunderlinetype[+docs.RepoObject_OutputFilter.SysObject_type+]
--

.Referencing Columns
--
* xref:docs.repoobject_outputfilter_t_gross.adoc#column-sysobjectunderlinetype[+docs.RepoObject_OutputFilter_T_gross.SysObject_type+]
--


[#column-sysobjectunderlinetypeunderlinename]
=== SysObject_type_name

[cols="d,8a,m,m,m"]
|===
|
|SysObject_type_name
|nvarchar(128)
|NULL
|
|===

.Referenced Columns
--
* xref:docs.repoobject_outputfilter.adoc#column-sysobjectunderlinetypeunderlinename[+docs.RepoObject_OutputFilter.SysObject_type_name+]
--

.Referencing Columns
--
* xref:docs.antoranavlistrepoobject_by_schema_type.adoc#column-typeunderlinename[+docs.AntoraNavListRepoObject_by_schema_type.type_name+]
* xref:docs.antoranavlistrepoobject_by_type.adoc#column-typeunderlinename[+docs.AntoraNavListRepoObject_by_type.type_name+]
* xref:docs.repoobject_outputfilter_t_gross.adoc#column-sysobjectunderlinetypeunderlinename[+docs.RepoObject_OutputFilter_T_gross.SysObject_type_name+]
--


[#column-tablesunderlineishidden]
=== tables_isHidden

[cols="d,8a,m,m,m"]
|===
|
|tables_isHidden
|bit
|NULL
|
|===

.Referenced Columns
--
* xref:docs.repoobject_outputfilter.adoc#column-tablesunderlineishidden[+docs.RepoObject_OutputFilter.tables_isHidden+]
--

.Referencing Columns
--
* xref:docs.repoobject_outputfilter_t_gross.adoc#column-tablesunderlineishidden[+docs.RepoObject_OutputFilter_T_gross.tables_isHidden+]
--


// end::AntoraColumnDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]
|1
|*<<column-repoobjectunderlineguid>>*
|uniqueidentifier
|NOT NULL
|

|2
|*<<column-culturesunderlinename>>*
|nvarchar(10)
|NOT NULL
|





















// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]


|
|<<column-antoracomponent>>
|nvarchar(max)
|NULL
|

|
|<<column-antoramodule>>
|nvarchar(max)
|NULL
|

|
|<<column-externalunderlineantoracomponent>>
|nvarchar(128)
|NULL
|

|
|<<column-externalunderlineantoramodule>>
|nvarchar(128)
|NULL
|

|
|<<column-externalunderlinedatabasename>>
|nvarchar(128)
|NULL
|

|
|<<column-isunderlinedocsoutput>>
|int
|NULL
|

|
|<<column-isunderlineexternal>>
|bit
|NOT NULL
|

|
|<<column-isunderlinessas>>
|bit
|NOT NULL
|

|
|<<column-pumlentitytopdefault>>
|nvarchar(max)
|NOT NULL
|

|
|<<column-pumlentitytopworkaround>>
|nvarchar(max)
|NOT NULL
|

|
|<<column-repoobjectunderlinedisplayname>>
|nvarchar(128)
|NULL
|

|
|<<column-repoobjectunderlinefulldisplayname2>>
|nvarchar(257)
|NULL
|

|
|<<column-repoobjectunderlinefullname>>
|nvarchar(261)
|NOT NULL
|

|
|<<column-repoobjectunderlinefullname2>>
|nvarchar(257)
|NOT NULL
|

|
|<<column-repoobjectunderlinename>>
|nvarchar(128)
|NOT NULL
|

|
|<<column-repoobjectunderlineschemaunderlinename>>
|nvarchar(128)
|NOT NULL
|

|
|<<column-repoobjectunderlinetranslation>>
|nvarchar(128)
|NULL
|

|
|<<column-sysobjectunderlinetype>>
|char(2)
|NULL
|

|
|<<column-sysobjectunderlinetypeunderlinename>>
|nvarchar(128)
|NULL
|

|
|<<column-tablesunderlineishidden>>
|bit
|NULL
|

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

[#index-pkunderlinerepoobjectunderlineoutputfilterunderlinet]
=== PK_RepoObject_OutputFilter_T

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-RepoObject_guid>>; uniqueidentifier
* <<column-cultures_name>>; nvarchar(10)
--
* PK, Unique, Real: 1, 1, 1


[#index-idxunderlinerepoobjectunderlineoutputfilterunderlinetunderlineunderline1]
=== idx_RepoObject_OutputFilter_T++__++1

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-RepoObject_schema_name>>; nvarchar(128)
* <<column-RepoObject_name>>; nvarchar(128)
--
* PK, Unique, Real: 0, 0, 0


[#index-idxunderlinerepoobjectunderlineoutputfilterunderlinetunderlineunderline2]
=== idx_RepoObject_OutputFilter_T++__++2

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-RepoObject_guid>>; uniqueidentifier
--
* PK, Unique, Real: 0, 0, 0


[#index-idxunderlinerepoobjectunderlineoutputfilterunderlinetunderlineunderline3]
=== idx_RepoObject_OutputFilter_T++__++3

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-AntoraComponent>>; nvarchar(max)
--
* PK, Unique, Real: 0, 0, 0

// end::AntoraIndexList[]

== AntoraMeasureDetails

// tag::AntoraMeasureDetails[]

// end::AntoraMeasureDetails[]

== AntoraMeasureDescriptions



== AntoraParameterList

// tag::AntoraParameterList[]

// end::AntoraParameterList[]

== AntoraXrefCulturesList

// tag::AntoraXrefCulturesList[]
* xref:dhw:sqldb:docs.repoobject_outputfilter_t.adoc[] - 
// end::AntoraXrefCulturesList[]

== cultures_count

// tag::cultures_count[]
1
// end::cultures_count[]

== Other tags

source: property.RepoObjectProperty_cross As rop_cross


=== additional_reference_csv

// tag::additional_reference_csv[]

// end::additional_reference_csv[]


=== AdocUspSteps

// tag::adocuspsteps[]

// end::adocuspsteps[]


=== AntoraReferencedList

// tag::antorareferencedlist[]
* xref:dhw:sqldb:docs.repoobject_outputfilter.adoc[]
// end::antorareferencedlist[]


=== AntoraReferencingList

// tag::antorareferencinglist[]
* xref:dhw:sqldb:docs.antoranavlistpage_by_schema.adoc[]
* xref:dhw:sqldb:docs.antoranavlistpage_by_type.adoc[]
* xref:dhw:sqldb:docs.antoranavlistrepoobject_by_schema.adoc[]
* xref:dhw:sqldb:docs.antoranavlistrepoobject_by_schema_type.adoc[]
* xref:dhw:sqldb:docs.antoranavlistrepoobject_by_type.adoc[]
* xref:dhw:sqldb:docs.indexsemanticgrouppatterndatatype.adoc[]
* xref:dhw:sqldb:docs.repoobject_antoraxrefcultureslist.adoc[]
* xref:dhw:sqldb:docs.repoobject_columnlist.adoc[]
* xref:dhw:sqldb:docs.repoobject_indexlist.adoc[]
* xref:dhw:sqldb:docs.repoobject_outputfilter_t_gross.adoc[]
* xref:dhw:sqldb:docs.repoobject_plantuml.adoc[]
* xref:dhw:sqldb:docs.repoobject_plantuml_colreflist_1_1.adoc[]
* xref:dhw:sqldb:docs.repoobject_plantuml_entity.adoc[]
* xref:dhw:sqldb:docs.schema_puml.adoc[]
* xref:dhw:sqldb:docs.schema_ssasrelationlist.adoc[]
* xref:dhw:sqldb:docs.unit_1_union.adoc[]
* xref:dhw:sqldb:docs.usp_antoraexport_objectpage.adoc[]
* xref:dhw:sqldb:docs.usp_antoraexport_objectpartialscontent.adoc[]
* xref:dhw:sqldb:docs.usp_persist_repoobject_outputfilter_t.adoc[]
// end::antorareferencinglist[]


=== Description

// tag::description[]

// end::description[]


=== exampleUsage

// tag::exampleusage[]

// end::exampleusage[]


=== exampleUsage_2

// tag::exampleusage_2[]

// end::exampleusage_2[]


=== exampleUsage_3

// tag::exampleusage_3[]

// end::exampleusage_3[]


=== exampleUsage_4

// tag::exampleusage_4[]

// end::exampleusage_4[]


=== exampleUsage_5

// tag::exampleusage_5[]

// end::exampleusage_5[]


=== exampleWrong_Usage

// tag::examplewrong_usage[]

// end::examplewrong_usage[]


=== has_execution_plan_issue

// tag::has_execution_plan_issue[]

// end::has_execution_plan_issue[]


=== has_get_referenced_issue

// tag::has_get_referenced_issue[]

// end::has_get_referenced_issue[]


=== has_history

// tag::has_history[]
0
// end::has_history[]


=== has_history_columns

// tag::has_history_columns[]
0
// end::has_history_columns[]


=== InheritanceType

// tag::inheritancetype[]
13
// end::inheritancetype[]


=== is_persistence

// tag::is_persistence[]
1
// end::is_persistence[]


=== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]
0
// end::is_persistence_check_duplicate_per_pk[]


=== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]
0
// end::is_persistence_check_for_empty_source[]


=== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]
0
// end::is_persistence_delete_changed[]


=== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]
0
// end::is_persistence_delete_missing[]


=== is_persistence_insert

// tag::is_persistence_insert[]
1
// end::is_persistence_insert[]


=== is_persistence_truncate

// tag::is_persistence_truncate[]
1
// end::is_persistence_truncate[]


=== is_persistence_update_changed

// tag::is_persistence_update_changed[]
0
// end::is_persistence_update_changed[]


=== is_repo_managed

// tag::is_repo_managed[]
0
// end::is_repo_managed[]


=== is_ssas

// tag::is_ssas[]
0
// end::is_ssas[]


=== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


=== MS_Description

// tag::ms_description[]

// end::ms_description[]


=== persistence_source_RepoObject_fullname

// tag::persistence_source_repoobject_fullname[]
[docs].[RepoObject_OutputFilter]
// end::persistence_source_repoobject_fullname[]


=== persistence_source_RepoObject_fullname2

// tag::persistence_source_repoobject_fullname2[]
docs.RepoObject_OutputFilter
// end::persistence_source_repoobject_fullname2[]


=== persistence_source_RepoObject_guid

// tag::persistence_source_repoobject_guid[]
ED5BF6C2-0593-EB11-84F2-A81E8446D5B0
// end::persistence_source_repoobject_guid[]


=== persistence_source_RepoObject_xref

// tag::persistence_source_repoobject_xref[]
xref:docs.repoobject_outputfilter.adoc[]
// end::persistence_source_repoobject_xref[]


=== pk_index_guid

// tag::pk_index_guid[]
6AD1CE74-7B24-EC11-8526-A81E8446D5B0
// end::pk_index_guid[]


=== pk_IndexPatternColumnDatatype

// tag::pk_indexpatterncolumndatatype[]
uniqueidentifier,nvarchar(10)
// end::pk_indexpatterncolumndatatype[]


=== pk_IndexPatternColumnName

// tag::pk_indexpatterncolumnname[]
RepoObject_guid,cultures_name
// end::pk_indexpatterncolumnname[]


=== pk_IndexSemanticGroup

// tag::pk_indexsemanticgroup[]

// end::pk_indexsemanticgroup[]


=== ReferencedObjectList

// tag::referencedobjectlist[]
* [docs].[RepoObject_OutputFilter]
// end::referencedobjectlist[]


=== usp_persistence_RepoObject_guid

// tag::usp_persistence_repoobject_guid[]
32B208BD-7D24-EC11-8526-A81E8446D5B0
// end::usp_persistence_repoobject_guid[]


=== UspExamples

// tag::uspexamples[]

// end::uspexamples[]


=== uspgenerator_usp_id

// tag::uspgenerator_usp_id[]

// end::uspgenerator_usp_id[]


=== UspParameters

// tag::uspparameters[]

// end::uspparameters[]

== Boolean Attributes

source: property.RepoObjectProperty WHERE property_int = 1

// tag::boolean_attributes[]

:is_persistence:
:is_persistence_insert:
:is_persistence_truncate:

// end::boolean_attributes[]

== PlantUML diagrams

=== PlantUML Entity

// tag::puml_entity[]
[plantuml, entity-{docname}, svg, subs=macros]
....
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:docs.repoobject_outputfilter_t.adoc[]" as docs.RepoObject_OutputFilter_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  AntoraComponent : (nvarchar(max))
  AntoraModule : (nvarchar(max))
  external_AntoraComponent : (nvarchar(128))
  external_AntoraModule : (nvarchar(128))
  external_DatabaseName : (nvarchar(128))
  is_DocsOutput : (int)
  - is_external : (bit)
  - is_ssas : (bit)
  - PumlEntityTopDefault : (nvarchar(max))
  - PumlEntityTopWorkaround : (nvarchar(max))
  RepoObject_DisplayName : (nvarchar(128))
  RepoObject_FullDisplayName2 : (nvarchar(257))
  - RepoObject_fullname : (nvarchar(261))
  - RepoObject_fullname2 : (nvarchar(257))
  - RepoObject_name : (nvarchar(128))
  - RepoObject_schema_name : (nvarchar(128))
  RepoObject_translation : (nvarchar(128))
  SysObject_type : (char(2))
  SysObject_type_name : (nvarchar(128))
  tables_isHidden : (bit)
  --
}
....

// end::puml_entity[]

=== PlantUML Entity 1 1 FK

// tag::puml_entity_1_1_fk[]
[plantuml, entity_1_1_fk-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:docs.repoobject_outputfilter_t.adoc[]" as docs.RepoObject_OutputFilter_T << U >> {
**PK_RepoObject_OutputFilter_T**

..
RepoObject_guid; uniqueidentifier
cultures_name; nvarchar(10)
--
- idx_RepoObject_OutputFilter_T__1

..
RepoObject_schema_name; nvarchar(128)
RepoObject_name; nvarchar(128)
--
- idx_RepoObject_OutputFilter_T__2

..
RepoObject_guid; uniqueidentifier
--
- idx_RepoObject_OutputFilter_T__3

..
AntoraComponent; nvarchar(max)
}



footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_fk[]

=== PlantUML 1 1 ObjectRef

// tag::puml_entity_1_1_objectref[]
[plantuml, entity_1_1_objectref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:docs.antoranavlistpage_by_schema.adoc[]" as docs.AntoraNavListPage_by_schema << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.antoranavlistpage_by_type.adoc[]" as docs.AntoraNavListPage_by_type << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.antoranavlistrepoobject_by_schema.adoc[]" as docs.AntoraNavListRepoObject_by_schema << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.antoranavlistrepoobject_by_schema_type.adoc[]" as docs.AntoraNavListRepoObject_by_schema_type << V >> {
  - **RepoObject_schema_name** : (nvarchar(128))
  **type** : (char(2))
  --
}

entity "puml-link:dhw:sqldb:docs.antoranavlistrepoobject_by_type.adoc[]" as docs.AntoraNavListRepoObject_by_type << V >> {
  **type** : (char(2))
  --
}

entity "puml-link:dhw:sqldb:docs.indexsemanticgrouppatterndatatype.adoc[]" as docs.IndexSemanticgroupPatterndatatype << V >> {
  **IndexSemanticGroup** : (nvarchar(512))
  **IndexPatternColumnDatatype** : (nvarchar(4000))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_antoraxrefcultureslist.adoc[]" as docs.RepoObject_AntoraXrefCulturesList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_columnlist.adoc[]" as docs.RepoObject_ColumnList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_indexlist.adoc[]" as docs.RepoObject_IndexList << V >> {
  **RepoObject_guid** : (uniqueidentifier)
  **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_outputfilter.adoc[]" as docs.RepoObject_OutputFilter << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_outputfilter_t.adoc[]" as docs.RepoObject_OutputFilter_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_outputfilter_t_gross.adoc[]" as docs.RepoObject_OutputFilter_T_gross << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml.adoc[]" as docs.RepoObject_Plantuml << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_colreflist_1_1.adoc[]" as docs.RepoObject_Plantuml_ColRefList_1_1 << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_entity.adoc[]" as docs.RepoObject_Plantuml_Entity << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.schema_puml.adoc[]" as docs.Schema_puml << V >> {
  - **RepoSchema_guid** : (uniqueidentifier)
  **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.schema_ssasrelationlist.adoc[]" as docs.Schema_SsasRelationList << V >> {
  - **SchemaName** : (nvarchar(128))
  **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.unit_1_union.adoc[]" as docs.Unit_1_union << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_objectpage.adoc[]" as docs.usp_AntoraExport_ObjectPage << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_objectpartialscontent.adoc[]" as docs.usp_AntoraExport_ObjectPartialsContent << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_repoobject_outputfilter_t.adoc[]" as docs.usp_PERSIST_RepoObject_OutputFilter_T << P >> {
  --
}

docs.RepoObject_OutputFilter <.. docs.RepoObject_OutputFilter_T
docs.RepoObject_OutputFilter_T <.. docs.usp_AntoraExport_ObjectPage
docs.RepoObject_OutputFilter_T <.. docs.RepoObject_ColumnList
docs.RepoObject_OutputFilter_T <.. docs.AntoraNavListRepoObject_by_schema_type
docs.RepoObject_OutputFilter_T <.. docs.AntoraNavListRepoObject_by_schema
docs.RepoObject_OutputFilter_T <.. docs.AntoraNavListRepoObject_by_type
docs.RepoObject_OutputFilter_T <.. docs.Unit_1_union
docs.RepoObject_OutputFilter_T <.. docs.usp_PERSIST_RepoObject_OutputFilter_T
docs.RepoObject_OutputFilter_T <.. docs.Schema_SsasRelationList
docs.RepoObject_OutputFilter_T <.. docs.RepoObject_AntoraXrefCulturesList
docs.RepoObject_OutputFilter_T <.. docs.usp_AntoraExport_ObjectPartialsContent
docs.RepoObject_OutputFilter_T <.. docs.RepoObject_OutputFilter_T_gross
docs.RepoObject_OutputFilter_T <.. docs.Schema_puml
docs.RepoObject_OutputFilter_T <.. docs.RepoObject_Plantuml_ColRefList_1_1
docs.RepoObject_OutputFilter_T <.. docs.AntoraNavListPage_by_schema
docs.RepoObject_OutputFilter_T <.. docs.IndexSemanticgroupPatterndatatype
docs.RepoObject_OutputFilter_T <.. docs.AntoraNavListPage_by_type
docs.RepoObject_OutputFilter_T <.. docs.RepoObject_IndexList
docs.RepoObject_OutputFilter_T <.. docs.RepoObject_Plantuml
docs.RepoObject_OutputFilter_T <.. docs.RepoObject_Plantuml_Entity

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_objectref[]

=== PlantUML 30 0 ObjectRef

// tag::puml_entity_30_0_objectref[]
[plantuml, entity_30_0_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:config.ftv_dwh_database.adoc[]" as config.ftv_dwh_database << IF >> {
  --
}

entity "puml-link:dhw:sqldb:config.ftv_get_parameter_value.adoc[]" as config.ftv_get_parameter_value << IF >> {
  --
}

entity "puml-link:dhw:sqldb:config.parameter.adoc[]" as config.Parameter << U >> {
  - **Parameter_name** : (varchar(100))
  - **sub_Parameter** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:configt.parameter_default.adoc[]" as configT.Parameter_default << V >> {
  - **Parameter_name** : (varchar(52))
  - **sub_Parameter** : (nvarchar(26))
  --
}

entity "puml-link:dhw:sqldb:configt.spt_values.adoc[]" as configT.spt_values << U >> {
  --
}

entity "puml-link:dhw:sqldb:configt.type.adoc[]" as configT.type << V >> {
  **type** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:docs.culture.adoc[]" as docs.Culture << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.fs_cleanstringforfilename.adoc[]" as docs.fs_cleanStringForFilename << FN >> {
  --
}

entity "puml-link:dhw:sqldb:docs.fs_cleanstringforpuml.adoc[]" as docs.fs_cleanStringForPuml << FN >> {
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_outputfilter.adoc[]" as docs.RepoObject_OutputFilter << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_outputfilter_t.adoc[]" as docs.RepoObject_OutputFilter_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:property.external_repoobjectproperty.adoc[]" as property.external_RepoObjectProperty << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.fs_get_repoobjectproperty_nvarchar.adoc[]" as property.fs_get_RepoObjectProperty_nvarchar << FN >> {
  --
}

entity "puml-link:dhw:sqldb:property.propertyname_repoobject.adoc[]" as property.PropertyName_RepoObject << V >> {
  **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.propertyname_repoobject_t.adoc[]" as property.PropertyName_RepoObject_T << U >> {
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty.adoc[]" as property.RepoObjectProperty << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty_external_src.adoc[]" as property.RepoObjectProperty_external_src << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty_external_tgt.adoc[]" as property.RepoObjectProperty_external_tgt << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty_selectedpropertyname_split.adoc[]" as property.RepoObjectProperty_SelectedPropertyName_split << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference.adoc[]" as reference.additional_Reference << U >> {
  # **tik_hash_c** : (nvarchar(32))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_database.adoc[]" as reference.additional_Reference_database << V >> {
  - **AntoraComponent** : (nvarchar(128))
  - **AntoraModule** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_database_t.adoc[]" as reference.additional_Reference_database_T << U >> {
  - **AntoraComponent** : (nvarchar(128))
  - **AntoraModule** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_from_properties_src.adoc[]" as reference.additional_Reference_from_properties_src << V >> {
  **referenced_AntoraComponent** : (nvarchar(max))
  **referenced_AntoraModule** : (nvarchar(max))
  **referenced_Schema** : (nvarchar(max))
  **referenced_Object** : (nvarchar(max))
  **referenced_Column** : (nvarchar(max))
  **referencing_AntoraComponent** : (nvarchar(max))
  **referencing_AntoraModule** : (nvarchar(max))
  **referencing_Schema** : (nvarchar(max))
  **referencing_Object** : (nvarchar(max))
  **referencing_Column** : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_from_properties_tgt.adoc[]" as reference.additional_Reference_from_properties_tgt << V >> {
  - **referenced_AntoraComponent** : (nvarchar(128))
  - **referenced_AntoraModule** : (nvarchar(128))
  - **referenced_Schema** : (nvarchar(128))
  - **referenced_Object** : (nvarchar(128))
  **referenced_Column** : (nvarchar(128))
  - **referencing_AntoraComponent** : (nvarchar(128))
  - **referencing_AntoraModule** : (nvarchar(128))
  - **referencing_Schema** : (nvarchar(128))
  - **referencing_Object** : (nvarchar(128))
  **referencing_Column** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_from_ssas_src.adoc[]" as reference.additional_Reference_from_ssas_src << V >> {
  **referenced_AntoraComponent** : (nvarchar(128))
  **referenced_AntoraModule** : (nvarchar(128))
  **referenced_Schema** : (nvarchar(max))
  **referenced_Object** : (nvarchar(max))
  **referenced_Column** : (nvarchar(500))
  **referencing_AntoraComponent** : (nvarchar(max))
  **referencing_AntoraModule** : (nvarchar(max))
  - **referencing_Schema** : (nvarchar(128))
  - **referencing_Object** : (nvarchar(128))
  **referencing_Column** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_from_ssas_tgt.adoc[]" as reference.additional_Reference_from_ssas_tgt << V >> {
  - **referenced_AntoraComponent** : (nvarchar(128))
  - **referenced_AntoraModule** : (nvarchar(128))
  - **referenced_Schema** : (nvarchar(128))
  - **referenced_Object** : (nvarchar(128))
  **referenced_Column** : (nvarchar(128))
  - **referencing_AntoraComponent** : (nvarchar(128))
  - **referencing_AntoraModule** : (nvarchar(128))
  - **referencing_Schema** : (nvarchar(128))
  - **referencing_Object** : (nvarchar(128))
  **referencing_Column** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_guid.adoc[]" as reference.additional_Reference_guid << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_is_external.adoc[]" as reference.additional_Reference_is_external << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_object.adoc[]" as reference.additional_Reference_Object << V >> {
  - **AntoraComponent** : (nvarchar(128))
  - **AntoraModule** : (nvarchar(128))
  - **SchemaName** : (nvarchar(128))
  - **ObjectName** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_object_t.adoc[]" as reference.additional_Reference_Object_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_objectcolumn.adoc[]" as reference.additional_Reference_ObjectColumn << V >> {
  - **AntoraComponent** : (nvarchar(128))
  - **AntoraModule** : (nvarchar(128))
  - **SchemaName** : (nvarchar(128))
  - **ObjectName** : (nvarchar(128))
  **ColumnName** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_objectcolumn_t.adoc[]" as reference.additional_Reference_ObjectColumn_T << U >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_wo_columns_from_properties_src.adoc[]" as reference.additional_Reference_wo_columns_from_properties_src << V >> {
  **referenced_AntoraComponent** : (nvarchar(max))
  **referenced_AntoraModule** : (nvarchar(max))
  **referenced_Schema** : (nvarchar(max))
  **referenced_Object** : (nvarchar(max))
  **referencing_AntoraComponent** : (nvarchar(max))
  **referencing_AntoraModule** : (nvarchar(max))
  **referencing_Schema** : (nvarchar(max))
  **referencing_Object** : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_wo_columns_from_properties_tgt.adoc[]" as reference.additional_Reference_wo_columns_from_properties_tgt << V >> {
  - **referenced_AntoraComponent** : (nvarchar(128))
  - **referenced_AntoraModule** : (nvarchar(128))
  - **referenced_Schema** : (nvarchar(128))
  - **referenced_Object** : (nvarchar(128))
  - **referencing_AntoraComponent** : (nvarchar(128))
  - **referencing_AntoraModule** : (nvarchar(128))
  - **referencing_Schema** : (nvarchar(128))
  - **referencing_Object** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_queryplan.adoc[]" as reference.RepoObject_QueryPlan << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_reference.adoc[]" as reference.RepoObject_reference << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_reference_additional.adoc[]" as reference.RepoObject_reference_additional << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_reference_persistence.adoc[]" as reference.RepoObject_reference_persistence << V >> {
  **referenced_RepoObject_guid** : (uniqueidentifier)
  - **referencing_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_reference_persistence_target_as_source.adoc[]" as reference.RepoObject_reference_persistence_target_as_source << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_reference_persistence_target_as_source_explicit.adoc[]" as reference.RepoObject_reference_persistence_target_as_source_explicit << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_reference_sqlexpressiondependencies.adoc[]" as reference.RepoObject_reference_SqlExpressionDependencies << V >> {
  **referenced_RepoObject_guid** : (uniqueidentifier)
  **referencing_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_reference_t.adoc[]" as reference.RepoObject_reference_T << U >> {
  - **referenced_RepoObject_guid** : (uniqueidentifier)
  - **referencing_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_reference_union.adoc[]" as reference.RepoObject_reference_union << V >> {
  **referenced_RepoObject_guid** : (uniqueidentifier)
  **referencing_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_reference_virtual.adoc[]" as reference.RepoObject_reference_virtual << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_referencedreferencing.adoc[]" as reference.RepoObject_ReferencedReferencing << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectsource_virtual.adoc[]" as reference.RepoObjectSource_virtual << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **Source_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.index_settings.adoc[]" as repo.Index_Settings << U >> {
  - **index_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject.adoc[]" as repo.RepoObject << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_external_src.adoc[]" as repo.RepoObject_external_src << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_external_tgt.adoc[]" as repo.RepoObject_external_tgt << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_gross.adoc[]" as repo.RepoObject_gross << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_gross_persistence.adoc[]" as repo.RepoObject_gross_persistence << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_persistence.adoc[]" as repo.RepoObject_persistence << U >> {
  - **target_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_ssas_src.adoc[]" as repo.RepoObject_SSAS_src << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_ssas_tgt.adoc[]" as repo.RepoObject_SSAS_tgt << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn.adoc[]" as repo.RepoObjectColumn << U >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn_external_src.adoc[]" as repo.RepoObjectColumn_external_src << V >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn_external_tgt.adoc[]" as repo.RepoObjectColumn_external_tgt << V >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn_ssas_src.adoc[]" as repo.RepoObjectColumn_SSAS_src << V >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn_ssas_tgt.adoc[]" as repo.RepoObjectColumn_SSAS_tgt << V >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.reposchema.adoc[]" as repo.RepoSchema << U >> {
  - **RepoSchema_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.reposchema_ssas_src.adoc[]" as repo.RepoSchema_ssas_src << V >> {
  - **RepoSchema_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:repo.reposchema_ssas_tgt.adoc[]" as repo.RepoSchema_ssas_tgt << V >> {
  - **RepoSchema_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.syscolumn_repoobjectcolumn_via_name.adoc[]" as repo.SysColumn_RepoObjectColumn_via_name << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.sysobject_repoobject_via_name.adoc[]" as repo.SysObject_RepoObject_via_name << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo_sys.extendedproperties.adoc[]" as repo_sys.ExtendedProperties << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo_sys.sql_expression_dependencies.adoc[]" as repo_sys.sql_expression_dependencies << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo_sys.syscolumn.adoc[]" as repo_sys.SysColumn << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo_sys.sysobject.adoc[]" as repo_sys.SysObject << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.additional_reference_step1.adoc[]" as ssas.additional_Reference_step1 << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json.adoc[]" as ssas.model_json << U >> {
  - **databasename** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_10.adoc[]" as ssas.model_json_10 << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_20.adoc[]" as ssas.model_json_20 << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_201_descriptions_multiline.adoc[]" as ssas.model_json_201_descriptions_multiline << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_2011_descriptions_stragg.adoc[]" as ssas.model_json_2011_descriptions_StrAgg << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31_tables.adoc[]" as ssas.model_json_31_tables << V >> {
  - **databasename** : (nvarchar(128))
  **tables_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31_tables_t.adoc[]" as ssas.model_json_31_tables_T << U >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_311_tables_columns.adoc[]" as ssas.model_json_311_tables_columns << V >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  **tables_columns_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_311_tables_columns_t.adoc[]" as ssas.model_json_311_tables_columns_T << U >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  - **tables_columns_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_313_tables_partitions.adoc[]" as ssas.model_json_313_tables_partitions << V >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  **tables_partitions_name** : (nvarchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_3131_tables_partitions_source.adoc[]" as ssas.model_json_3131_tables_partitions_source << V >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  **tables_partitions_name** : (nvarchar(500))
  **tables_partitions_source_name** : (nvarchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31311_tables_partitions_source_posfrom.adoc[]" as ssas.model_json_31311_tables_partitions_source_PosFrom << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_313111_tables_partitions_source_stringfrom.adoc[]" as ssas.model_json_313111_tables_partitions_source_StringFrom << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_3131111_tables_partitions_source_posdot.adoc[]" as ssas.model_json_3131111_tables_partitions_source_PosDot << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31311111_tables_partitions_source_part123.adoc[]" as ssas.model_json_31311111_tables_partitions_source_Part123 << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_316_tables_descriptions_multiline.adoc[]" as ssas.model_json_316_tables_descriptions_multiline << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_3161_tables_descriptions_stragg.adoc[]" as ssas.model_json_3161_tables_descriptions_StrAgg << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_33_datasources.adoc[]" as ssas.model_json_33_dataSources << V >> {
  - **databasename** : (nvarchar(128))
  **dataSources_name** : (nvarchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_33_datasources_t.adoc[]" as ssas.model_json_33_dataSources_T << U >> {
  - **databasename** : (nvarchar(128))
  - **dataSources_name** : (nvarchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_34_cultures.adoc[]" as ssas.model_json_34_cultures << V >> {
  - **databasename** : (nvarchar(128))
  **cultures_name** : (nvarchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_341_cultures_translations.adoc[]" as ssas.model_json_341_cultures_translations << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_3411_cultures_translations_model.adoc[]" as ssas.model_json_3411_cultures_translations_model << V >> {
  - **databasename** : (nvarchar(128))
  **cultures_name** : (nvarchar(500))
  **cultures_translations_model_name** : (nvarchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_3411_cultures_translations_model_t.adoc[]" as ssas.model_json_3411_cultures_translations_model_T << U >> {
  - **databasename** : (nvarchar(128))
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_34111_cultures_translations_model_tables.adoc[]" as ssas.model_json_34111_cultures_translations_model_tables << V >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.columns.adoc[]" as sys_dwh.columns << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.computed_columns.adoc[]" as sys_dwh.computed_columns << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.default_constraints.adoc[]" as sys_dwh.default_constraints << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.extended_properties.adoc[]" as sys_dwh.extended_properties << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.identity_columns.adoc[]" as sys_dwh.identity_columns << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.indexes.adoc[]" as sys_dwh.indexes << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.objects.adoc[]" as sys_dwh.objects << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.parameters.adoc[]" as sys_dwh.parameters << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.schemas.adoc[]" as sys_dwh.schemas << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.sql_expression_dependencies.adoc[]" as sys_dwh.sql_expression_dependencies << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.sql_modules.adoc[]" as sys_dwh.sql_modules << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.tables.adoc[]" as sys_dwh.tables << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.types.adoc[]" as sys_dwh.types << SN >> {
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.generatorusp.adoc[]" as uspgenerator.GeneratorUsp << U >> {
  - **id** : (int)
  --
}

config.ftv_dwh_database <.. repo_sys.sql_expression_dependencies
config.ftv_dwh_database <.. repo_sys.SysColumn
config.ftv_dwh_database <.. repo_sys.ExtendedProperties
config.ftv_get_parameter_value <.. repo.RepoObject_external_src
config.ftv_get_parameter_value <.. reference.additional_Reference_is_external
config.ftv_get_parameter_value <.. ssas.additional_Reference_step1
config.ftv_get_parameter_value <.. repo.RepoObject_gross
config.Parameter <.. config.ftv_dwh_database
config.Parameter <.. property.PropertyName_RepoObject
config.Parameter <.. config.ftv_get_parameter_value
configT.Parameter_default <.. config.Parameter
configT.spt_values <.. configT.type
configT.type <.. repo.RepoObject_gross_persistence
configT.type <.. reference.RepoObject_ReferencedReferencing
configT.type <.. repo.RepoObject_gross
docs.Culture <.. docs.RepoObject_OutputFilter
docs.fs_cleanStringForFilename <.. repo.RepoObject_gross
docs.fs_cleanStringForFilename <.. repo.RepoObject_gross_persistence
docs.fs_cleanStringForFilename <.. docs.RepoObject_OutputFilter
docs.fs_cleanStringForFilename <.. reference.RepoObject_ReferencedReferencing
docs.fs_cleanStringForPuml <.. docs.RepoObject_OutputFilter
docs.RepoObject_OutputFilter <.. docs.RepoObject_OutputFilter_T
property.external_RepoObjectProperty <.. property.RepoObjectProperty_external_src
property.fs_get_RepoObjectProperty_nvarchar <.. repo.RepoObject_gross
property.PropertyName_RepoObject <.. property.PropertyName_RepoObject_T
property.PropertyName_RepoObject_T <.. property.RepoObjectProperty_external_tgt
property.RepoObjectProperty <.. property.PropertyName_RepoObject
property.RepoObjectProperty <.. property.RepoObjectProperty_SelectedPropertyName_split
property.RepoObjectProperty <.. property.fs_get_RepoObjectProperty_nvarchar
property.RepoObjectProperty_external_src <.. property.RepoObjectProperty_external_tgt
property.RepoObjectProperty_external_tgt <.. property.RepoObjectProperty
property.RepoObjectProperty_SelectedPropertyName_split <.. reference.additional_Reference_wo_columns_from_properties_src
property.RepoObjectProperty_SelectedPropertyName_split <.. reference.additional_Reference_from_properties_src
reference.additional_Reference <.. reference.additional_Reference_guid
reference.additional_Reference <.. reference.additional_Reference_is_external
reference.additional_Reference_database <.. reference.additional_Reference_database_T
reference.additional_Reference_database_T <.. repo.RepoObject_gross
reference.additional_Reference_from_properties_src <.. reference.additional_Reference_from_properties_tgt
reference.additional_Reference_from_properties_tgt <.. reference.additional_Reference
reference.additional_Reference_from_ssas_src <.. reference.additional_Reference_from_ssas_tgt
reference.additional_Reference_from_ssas_tgt <.. reference.additional_Reference
reference.additional_Reference_guid <.. reference.RepoObject_reference_additional
reference.additional_Reference_is_external <.. reference.additional_Reference_ObjectColumn
reference.additional_Reference_is_external <.. reference.additional_Reference_database
reference.additional_Reference_is_external <.. reference.additional_Reference_Object
reference.additional_Reference_Object <.. reference.additional_Reference_Object_T
reference.additional_Reference_Object_T <.. repo.RepoObject_external_src
reference.additional_Reference_Object_T <.. repo.RepoObjectColumn_external_src
reference.additional_Reference_ObjectColumn <.. reference.additional_Reference_ObjectColumn_T
reference.additional_Reference_ObjectColumn_T <.. repo.RepoObjectColumn_external_src
reference.additional_Reference_wo_columns_from_properties_src <.. reference.additional_Reference_wo_columns_from_properties_tgt
reference.additional_Reference_wo_columns_from_properties_tgt <.. reference.additional_Reference
reference.RepoObject_QueryPlan <.. repo.RepoObject_gross
reference.RepoObject_reference <.. reference.RepoObject_reference_T
reference.RepoObject_reference_additional <.. reference.RepoObject_reference_union
reference.RepoObject_reference_persistence <.. reference.RepoObject_reference_union
reference.RepoObject_reference_persistence_target_as_source <.. reference.RepoObject_reference
reference.RepoObject_reference_persistence_target_as_source <.. reference.RepoObject_reference_union
reference.RepoObject_reference_persistence_target_as_source_explicit <.. reference.RepoObject_reference
reference.RepoObject_reference_persistence_target_as_source_explicit <.. reference.RepoObject_reference_union
reference.RepoObject_reference_SqlExpressionDependencies <.. reference.RepoObject_reference_persistence_target_as_source_explicit
reference.RepoObject_reference_SqlExpressionDependencies <.. reference.RepoObject_reference_union
reference.RepoObject_reference_SqlExpressionDependencies <.. reference.RepoObject_reference_persistence_target_as_source
reference.RepoObject_reference_T <.. reference.RepoObject_ReferencedReferencing
reference.RepoObject_reference_union <.. reference.RepoObject_reference
reference.RepoObject_reference_virtual <.. reference.RepoObject_reference_union
reference.RepoObject_ReferencedReferencing <.. repo.RepoObject_gross
reference.RepoObjectSource_virtual <.. reference.RepoObject_reference_virtual
repo.Index_Settings <.. repo.RepoObject_gross
repo.RepoObject <.. reference.RepoObject_reference_persistence
repo.RepoObject <.. repo.SysColumn_RepoObjectColumn_via_name
repo.RepoObject <.. repo.SysObject_RepoObject_via_name
repo.RepoObject <.. repo.RepoObjectColumn_external_src
repo.RepoObject <.. property.RepoObjectProperty_external_tgt
repo.RepoObject <.. reference.RepoObject_reference_persistence_target_as_source_explicit
repo.RepoObject <.. repo.RepoObject_gross_persistence
repo.RepoObject <.. repo.RepoObject_external_src
repo.RepoObject <.. reference.RepoObject_reference_virtual
repo.RepoObject <.. reference.additional_Reference_guid
repo.RepoObject <.. reference.RepoObject_reference_SqlExpressionDependencies
repo.RepoObject <.. repo.RepoObject_gross
repo.RepoObject_external_src <.. repo.RepoObject_external_tgt
repo.RepoObject_external_tgt <.. repo.RepoObject
repo.RepoObject_external_tgt <.. repo.RepoObjectColumn_external_tgt
repo.RepoObject_gross <.. docs.RepoObject_OutputFilter
repo.RepoObject_gross_persistence <.. reference.RepoObject_reference_persistence_target_as_source
repo.RepoObject_persistence <.. reference.RepoObject_reference_persistence
repo.RepoObject_persistence <.. reference.RepoObject_reference_persistence_target_as_source_explicit
repo.RepoObject_persistence <.. repo.RepoObject_gross_persistence
repo.RepoObject_persistence <.. repo.RepoObject_gross
repo.RepoObject_SSAS_src <.. repo.RepoObject_SSAS_tgt
repo.RepoObject_SSAS_tgt <.. repo.RepoObjectColumn_SSAS_tgt
repo.RepoObject_SSAS_tgt <.. repo.RepoObject
repo.RepoObjectColumn <.. repo.SysColumn_RepoObjectColumn_via_name
repo.RepoObjectColumn <.. reference.additional_Reference_guid
repo.RepoObjectColumn_external_src <.. repo.RepoObjectColumn_external_tgt
repo.RepoObjectColumn_external_tgt <.. repo.RepoObjectColumn
repo.RepoObjectColumn_SSAS_src <.. repo.RepoObjectColumn_SSAS_tgt
repo.RepoObjectColumn_SSAS_tgt <.. repo.RepoObjectColumn
repo.RepoSchema <.. repo.RepoObject_SSAS_src
repo.RepoSchema_ssas_src <.. repo.RepoSchema_ssas_tgt
repo.RepoSchema_ssas_tgt <.. repo.RepoSchema
repo.SysColumn_RepoObjectColumn_via_name <.. repo_sys.sql_expression_dependencies
repo.SysObject_RepoObject_via_name <.. repo_sys.sql_expression_dependencies
repo_sys.ExtendedProperties <.. repo_sys.SysObject
repo_sys.ExtendedProperties <.. repo_sys.SysColumn
repo_sys.sql_expression_dependencies <.. reference.RepoObject_reference_SqlExpressionDependencies
repo_sys.SysColumn <.. repo.SysColumn_RepoObjectColumn_via_name
repo_sys.SysObject <.. repo.SysObject_RepoObject_via_name
repo_sys.SysObject <.. repo_sys.SysColumn
ssas.additional_Reference_step1 <.. reference.additional_Reference_from_ssas_src
ssas.model_json <.. ssas.model_json_10
ssas.model_json_10 <.. ssas.model_json_20
ssas.model_json_20 <.. repo.RepoSchema_ssas_src
ssas.model_json_20 <.. ssas.model_json_33_dataSources
ssas.model_json_20 <.. ssas.model_json_31_tables
ssas.model_json_20 <.. ssas.model_json_201_descriptions_multiline
ssas.model_json_20 <.. ssas.model_json_34_cultures
ssas.model_json_201_descriptions_multiline <.. ssas.model_json_2011_descriptions_StrAgg
ssas.model_json_2011_descriptions_StrAgg <.. repo.RepoSchema_ssas_src
ssas.model_json_31_tables <.. ssas.model_json_31_tables_T
ssas.model_json_31_tables_T <.. repo.RepoObject_gross
ssas.model_json_31_tables_T <.. ssas.model_json_316_tables_descriptions_multiline
ssas.model_json_31_tables_T <.. ssas.model_json_313_tables_partitions
ssas.model_json_31_tables_T <.. repo.RepoObject_SSAS_src
ssas.model_json_31_tables_T <.. ssas.model_json_311_tables_columns
ssas.model_json_311_tables_columns <.. ssas.model_json_311_tables_columns_T
ssas.model_json_311_tables_columns_T <.. repo.RepoObjectColumn_SSAS_src
ssas.model_json_311_tables_columns_T <.. ssas.additional_Reference_step1
ssas.model_json_313_tables_partitions <.. ssas.model_json_3131_tables_partitions_source
ssas.model_json_3131_tables_partitions_source <.. ssas.model_json_31311_tables_partitions_source_PosFrom
ssas.model_json_31311_tables_partitions_source_PosFrom <.. ssas.model_json_313111_tables_partitions_source_StringFrom
ssas.model_json_313111_tables_partitions_source_StringFrom <.. ssas.model_json_3131111_tables_partitions_source_PosDot
ssas.model_json_3131111_tables_partitions_source_PosDot <.. ssas.model_json_31311111_tables_partitions_source_Part123
ssas.model_json_31311111_tables_partitions_source_Part123 <.. ssas.additional_Reference_step1
ssas.model_json_316_tables_descriptions_multiline <.. ssas.model_json_3161_tables_descriptions_StrAgg
ssas.model_json_3161_tables_descriptions_StrAgg <.. repo.RepoObject_gross
ssas.model_json_33_dataSources <.. ssas.model_json_33_dataSources_T
ssas.model_json_33_dataSources_T <.. ssas.additional_Reference_step1
ssas.model_json_34_cultures <.. ssas.model_json_341_cultures_translations
ssas.model_json_341_cultures_translations <.. ssas.model_json_3411_cultures_translations_model
ssas.model_json_3411_cultures_translations_model <.. ssas.model_json_3411_cultures_translations_model_T
ssas.model_json_3411_cultures_translations_model_T <.. ssas.model_json_34111_cultures_translations_model_tables
ssas.model_json_3411_cultures_translations_model_T <.. docs.Culture
ssas.model_json_3411_cultures_translations_model_T <.. docs.RepoObject_OutputFilter
ssas.model_json_34111_cultures_translations_model_tables <.. docs.RepoObject_OutputFilter
sys_dwh.columns <.. repo_sys.ExtendedProperties
sys_dwh.columns <.. repo_sys.SysColumn
sys_dwh.computed_columns <.. repo_sys.SysColumn
sys_dwh.default_constraints <.. repo_sys.SysColumn
sys_dwh.extended_properties <.. repo_sys.ExtendedProperties
sys_dwh.identity_columns <.. repo_sys.SysColumn
sys_dwh.indexes <.. repo_sys.ExtendedProperties
sys_dwh.objects <.. repo_sys.ExtendedProperties
sys_dwh.objects <.. repo_sys.SysObject
sys_dwh.parameters <.. repo_sys.ExtendedProperties
sys_dwh.schemas <.. repo_sys.ExtendedProperties
sys_dwh.schemas <.. repo_sys.SysObject
sys_dwh.sql_expression_dependencies <.. repo_sys.sql_expression_dependencies
sys_dwh.sql_modules <.. repo_sys.SysObject
sys_dwh.tables <.. repo_sys.SysObject
sys_dwh.types <.. repo_sys.SysColumn
uspgenerator.GeneratorUsp <.. repo.RepoObject_gross

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_30_0_objectref[]

=== PlantUML 0 30 ObjectRef

// tag::puml_entity_0_30_objectref[]
[plantuml, entity_0_30_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:dmdocs.unit.adoc[]" as dmdocs.unit << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.antoranavlistpage_by_schema.adoc[]" as docs.AntoraNavListPage_by_schema << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.antoranavlistpage_by_type.adoc[]" as docs.AntoraNavListPage_by_type << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.antoranavlistrepoobject_by_schema.adoc[]" as docs.AntoraNavListRepoObject_by_schema << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.antoranavlistrepoobject_by_schema_type.adoc[]" as docs.AntoraNavListRepoObject_by_schema_type << V >> {
  - **RepoObject_schema_name** : (nvarchar(128))
  **type** : (char(2))
  --
}

entity "puml-link:dhw:sqldb:docs.antoranavlistrepoobject_by_type.adoc[]" as docs.AntoraNavListRepoObject_by_type << V >> {
  **type** : (char(2))
  --
}

entity "puml-link:dhw:sqldb:docs.antorapage_indexsemanticgroup.adoc[]" as docs.AntoraPage_IndexSemanticGroup << V >> {
  - **page_content** : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:docs.antorapage_objectbyschema.adoc[]" as docs.AntoraPage_ObjectBySchema << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.antorapage_objectbytype.adoc[]" as docs.AntoraPage_ObjectByType << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ftv_repoobject_reference_plantuml_entityreflist.adoc[]" as docs.ftv_RepoObject_Reference_PlantUml_EntityRefList << IF >> {
  --
}

entity "puml-link:dhw:sqldb:docs.indexsemanticgroup.adoc[]" as docs.IndexSemanticgroup << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.indexsemanticgrouppatterndatatype.adoc[]" as docs.IndexSemanticgroupPatterndatatype << V >> {
  **IndexSemanticGroup** : (nvarchar(512))
  **IndexPatternColumnDatatype** : (nvarchar(4000))
  --
}

entity "puml-link:dhw:sqldb:docs.objectrefcyclic.adoc[]" as docs.ObjectRefCyclic << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.objectrefcyclic_entitylist.adoc[]" as docs.ObjectRefCyclic_EntityList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_adoc.adoc[]" as docs.RepoObject_Adoc << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_adoc_t.adoc[]" as docs.RepoObject_Adoc_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_antoraxrefcultureslist.adoc[]" as docs.RepoObject_AntoraXrefCulturesList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_columnlist.adoc[]" as docs.RepoObject_ColumnList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_columnlist_t.adoc[]" as docs.RepoObject_ColumnList_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_indexlist.adoc[]" as docs.RepoObject_IndexList << V >> {
  **RepoObject_guid** : (uniqueidentifier)
  **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_indexlist_t.adoc[]" as docs.RepoObject_IndexList_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_measuredescriptionlist.adoc[]" as docs.RepoObject_MeasureDescriptionList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_measurelist.adoc[]" as docs.RepoObject_MeasureList << V >> {
  **RepoObject_guid** : (uniqueidentifier)
  **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_outputfilter_t.adoc[]" as docs.RepoObject_OutputFilter_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_outputfilter_t_gross.adoc[]" as docs.RepoObject_OutputFilter_T_gross << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml.adoc[]" as docs.RepoObject_Plantuml << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_colreflist_1_1.adoc[]" as docs.RepoObject_Plantuml_ColRefList_1_1 << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_entity.adoc[]" as docs.RepoObject_Plantuml_Entity << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_entity_t.adoc[]" as docs.RepoObject_Plantuml_Entity_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_pumlentityfklist.adoc[]" as docs.RepoObject_PlantUml_PumlEntityFkList << V >> {
  **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_t.adoc[]" as docs.RepoObject_Plantuml_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.schema_entitylist.adoc[]" as docs.Schema_EntityList << V >> {
  - **RepoObject_schema_name** : (nvarchar(128))
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.schema_puml.adoc[]" as docs.Schema_puml << V >> {
  - **RepoSchema_guid** : (uniqueidentifier)
  **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.schema_ssasrelationlist.adoc[]" as docs.Schema_SsasRelationList << V >> {
  - **SchemaName** : (nvarchar(128))
  **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.unit_1_union.adoc[]" as docs.Unit_1_union << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.unit_2.adoc[]" as docs.Unit_2 << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.unit_3.adoc[]" as docs.Unit_3 << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport.adoc[]" as docs.usp_AntoraExport << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_objectnavigation.adoc[]" as docs.usp_AntoraExport_ObjectNavigation << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_objectpage.adoc[]" as docs.usp_AntoraExport_ObjectPage << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_objectpartialscontent.adoc[]" as docs.usp_AntoraExport_ObjectPartialsContent << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_objectpuml.adoc[]" as docs.usp_AntoraExport_ObjectPuml << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_repoobject_adoc_t.adoc[]" as docs.usp_PERSIST_RepoObject_Adoc_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_repoobject_columnlist_t.adoc[]" as docs.usp_PERSIST_RepoObject_ColumnList_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_repoobject_indexlist_t.adoc[]" as docs.usp_PERSIST_RepoObject_IndexList_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_repoobject_outputfilter_t.adoc[]" as docs.usp_PERSIST_RepoObject_OutputFilter_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_repoobject_plantuml_entity_t.adoc[]" as docs.usp_PERSIST_RepoObject_Plantuml_Entity_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_repoobject_plantuml_t.adoc[]" as docs.usp_PERSIST_RepoObject_Plantuml_T << P >> {
  --
}

docs.AntoraNavListPage_by_type <.. docs.usp_AntoraExport_ObjectNavigation
docs.AntoraNavListRepoObject_by_schema <.. docs.AntoraPage_ObjectBySchema
docs.AntoraNavListRepoObject_by_schema <.. docs.usp_AntoraExport_ObjectNavigation
docs.AntoraNavListRepoObject_by_schema_type <.. docs.usp_AntoraExport_ObjectNavigation
docs.AntoraNavListRepoObject_by_type <.. docs.AntoraPage_ObjectByType
docs.AntoraNavListRepoObject_by_type <.. docs.usp_AntoraExport_ObjectNavigation
docs.ftv_RepoObject_Reference_PlantUml_EntityRefList <.. docs.RepoObject_Plantuml
docs.IndexSemanticgroup <.. docs.AntoraPage_IndexSemanticGroup
docs.IndexSemanticgroupPatterndatatype <.. docs.IndexSemanticgroup
docs.ObjectRefCyclic_EntityList <.. docs.ObjectRefCyclic
docs.RepoObject_Adoc <.. docs.usp_PERSIST_RepoObject_Adoc_T
docs.RepoObject_Adoc <.. docs.RepoObject_Adoc_T
docs.REpoObject_Adoc_T <.. docs.usp_PERSIST_RepoObject_Adoc_T
docs.RepoObject_AntoraXrefCulturesList <.. docs.RepoObject_Adoc
docs.RepoObject_ColumnList <.. docs.RepoObject_ColumnList_T
docs.RepoObject_ColumnList <.. docs.usp_PERSIST_RepoObject_ColumnList_T
docs.RepoObject_ColumnList_T <.. docs.RepoObject_Plantuml_Entity
docs.RepoObject_ColumnList_T <.. docs.usp_PERSIST_RepoObject_ColumnList_T
docs.RepoObject_ColumnList_T <.. docs.RepoObject_Adoc
docs.RepoObject_IndexList <.. docs.RepoObject_IndexList_T
docs.RepoObject_IndexList <.. docs.usp_PERSIST_RepoObject_IndexList_T
docs.RepoObject_IndexList_T <.. docs.usp_PERSIST_RepoObject_IndexList_T
docs.RepoObject_IndexList_T <.. docs.RepoObject_Plantuml_Entity
docs.RepoObject_IndexList_T <.. docs.RepoObject_Adoc
docs.RepoObject_MeasureDescriptionList <.. docs.RepoObject_Adoc
docs.RepoObject_MeasureList <.. docs.RepoObject_Plantuml_Entity
docs.RepoObject_MeasureList <.. docs.RepoObject_Adoc
docs.RepoObject_OutputFilter_T <.. docs.RepoObject_OutputFilter_T_gross
docs.RepoObject_OutputFilter_T <.. docs.usp_AntoraExport_ObjectPartialsContent
docs.RepoObject_OutputFilter_T <.. docs.RepoObject_AntoraXrefCulturesList
docs.RepoObject_OutputFilter_T <.. docs.usp_PERSIST_RepoObject_OutputFilter_T
docs.RepoObject_OutputFilter_T <.. docs.Unit_1_union
docs.RepoObject_OutputFilter_T <.. docs.Schema_SsasRelationList
docs.RepoObject_OutputFilter_T <.. docs.Schema_puml
docs.RepoObject_OutputFilter_T <.. docs.RepoObject_Plantuml_ColRefList_1_1
docs.RepoObject_OutputFilter_T <.. docs.AntoraNavListPage_by_schema
docs.RepoObject_OutputFilter_T <.. docs.IndexSemanticgroupPatterndatatype
docs.RepoObject_OutputFilter_T <.. docs.AntoraNavListPage_by_type
docs.RepoObject_OutputFilter_T <.. docs.RepoObject_IndexList
docs.RepoObject_OutputFilter_T <.. docs.RepoObject_Plantuml
docs.RepoObject_OutputFilter_T <.. docs.RepoObject_Plantuml_Entity
docs.RepoObject_OutputFilter_T <.. docs.RepoObject_ColumnList
docs.RepoObject_OutputFilter_T <.. docs.AntoraNavListRepoObject_by_schema_type
docs.RepoObject_OutputFilter_T <.. docs.AntoraNavListRepoObject_by_schema
docs.RepoObject_OutputFilter_T <.. docs.AntoraNavListRepoObject_by_type
docs.RepoObject_OutputFilter_T <.. docs.usp_AntoraExport_ObjectPage
docs.RepoObject_OutputFilter_T_gross <.. docs.RepoObject_MeasureDescriptionList
docs.RepoObject_OutputFilter_T_gross <.. docs.RepoObject_MeasureList
docs.RepoObject_OutputFilter_T_gross <.. docs.RepoObject_Adoc
docs.RepoObject_Plantuml <.. docs.usp_PERSIST_RepoObject_Plantuml_T
docs.RepoObject_Plantuml <.. docs.RepoObject_Plantuml_T
docs.RepoObject_Plantuml_ColRefList_1_1 <.. docs.RepoObject_Plantuml
docs.RepoObject_Plantuml_Entity <.. docs.usp_PERSIST_RepoObject_Plantuml_Entity_T
docs.RepoObject_Plantuml_Entity <.. docs.RepoObject_Plantuml_Entity_T
docs.RepoObject_Plantuml_Entity_T <.. docs.RepoObject_Adoc
docs.RepoObject_Plantuml_Entity_T <.. docs.usp_PERSIST_RepoObject_Plantuml_Entity_T
docs.RepoObject_Plantuml_Entity_T <.. docs.ftv_RepoObject_Reference_PlantUml_EntityRefList
docs.RepoObject_Plantuml_Entity_T <.. docs.RepoObject_PlantUml_PumlEntityFkList
docs.RepoObject_Plantuml_Entity_T <.. docs.ObjectRefCyclic_EntityList
docs.RepoObject_Plantuml_Entity_T <.. docs.Schema_EntityList
docs.RepoObject_PlantUml_PumlEntityFkList <.. docs.RepoObject_Plantuml
docs.RepoObject_Plantuml_T <.. docs.RepoObject_Adoc
docs.RepoObject_Plantuml_T <.. docs.usp_PERSIST_RepoObject_Plantuml_T
docs.Schema_EntityList <.. docs.Schema_puml
docs.Schema_puml <.. docs.AntoraNavListPage_by_schema
docs.Schema_SsasRelationList <.. docs.Schema_puml
docs.Unit_1_union <.. docs.Unit_2
docs.Unit_2 <.. docs.Unit_3
docs.Unit_3 <.. dmdocs.unit
docs.usp_AntoraExport_ObjectNavigation <.. docs.usp_AntoraExport
docs.usp_AntoraExport_ObjectPage <.. docs.usp_AntoraExport
docs.usp_AntoraExport_ObjectPartialsContent <.. docs.usp_AntoraExport
docs.usp_AntoraExport_ObjectPuml <.. docs.usp_AntoraExport
docs.usp_PERSIST_RepoObject_Adoc_T <.. docs.usp_AntoraExport_ObjectPartialsContent
docs.usp_PERSIST_RepoObject_ColumnList_T <.. docs.usp_AntoraExport_ObjectPartialsContent
docs.usp_PERSIST_RepoObject_IndexList_T <.. docs.usp_AntoraExport_ObjectPartialsContent
docs.usp_PERSIST_RepoObject_OutputFilter_T <.. docs.usp_AntoraExport
docs.usp_PERSIST_RepoObject_Plantuml_Entity_T <.. docs.usp_AntoraExport_ObjectPuml
docs.usp_PERSIST_RepoObject_Plantuml_T <.. docs.usp_AntoraExport_ObjectPuml

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_0_30_objectref[]

=== PlantUML 1 1 ColumnRef

// tag::puml_entity_1_1_colref[]
[plantuml, entity_1_1_colref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:docs.antoranavlistpage_by_schema.adoc[]" as docs.AntoraNavListPage_by_schema << V >> {
  cultures_name : (nvarchar(10))
  - nav_list : (nvarchar(max))
  - RepoObject_schema_name : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:docs.antoranavlistpage_by_type.adoc[]" as docs.AntoraNavListPage_by_type << V >> {
  - nav_list : (nvarchar(4000))
  type : (nvarchar(128))
  type_desc : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:docs.antoranavlistrepoobject_by_schema.adoc[]" as docs.AntoraNavListRepoObject_by_schema << V >> {
  - cultures_name : (nvarchar(10))
  is_ssas : (tinyint)
  nav_list : (nvarchar(max))
  - RepoObject_schema_name : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:docs.antoranavlistrepoobject_by_schema_type.adoc[]" as docs.AntoraNavListRepoObject_by_schema_type << V >> {
  - **RepoObject_schema_name** : (nvarchar(128))
  **type** : (char(2))
  - cultures_name : (nvarchar(10))
  nav_list : (nvarchar(max))
  type_name : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:docs.antoranavlistrepoobject_by_type.adoc[]" as docs.AntoraNavListRepoObject_by_type << V >> {
  **type** : (char(2))
  - cultures_name : (nvarchar(10))
  nav_list : (nvarchar(max))
  type_name : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:docs.indexsemanticgrouppatterndatatype.adoc[]" as docs.IndexSemanticgroupPatterndatatype << V >> {
  **IndexSemanticGroup** : (nvarchar(512))
  **IndexPatternColumnDatatype** : (nvarchar(4000))
  AntoraIndexSemanticgroupPatterndatatype : (nvarchar(max))
  cultures_name : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_antoraxrefcultureslist.adoc[]" as docs.RepoObject_AntoraXrefCulturesList << V >> {
  AntoraXrefCulturesList : (nvarchar(max))
  cultures_count : (int)
  - RepoObject_guid : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_columnlist.adoc[]" as docs.RepoObject_ColumnList << V >> {
  AntoraColumnDetails : (nvarchar(max))
  AntoraNonPkColumnTableRows : (nvarchar(max))
  AntoraPkColumnTableRows : (nvarchar(max))
  - cultures_name : (nvarchar(10))
  is_external : (tinyint)
  PlantumlAllEntityColumns : (nvarchar(max))
  PlantumlIndexColumns : (nvarchar(max))
  PlantumlNonPkEntityColumns : (nvarchar(max))
  PlantumlNonPkHiddenEntityColumns : (nvarchar(max))
  PlantumlNonPkIndexColumns : (nvarchar(max))
  PlantumlPkEntityColumns : (nvarchar(max))
  - RepoObject_guid : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_indexlist.adoc[]" as docs.RepoObject_IndexList << V >> {
  **RepoObject_guid** : (uniqueidentifier)
  **cultures_name** : (nvarchar(10))
  AntoraIndexList : (nvarchar(max))
  PumlIndexList : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_outputfilter.adoc[]" as docs.RepoObject_OutputFilter << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  AntoraComponent : (nvarchar(max))
  AntoraModule : (nvarchar(max))
  external_AntoraComponent : (nvarchar(128))
  external_AntoraModule : (nvarchar(128))
  external_DatabaseName : (nvarchar(128))
  is_DocsOutput : (int)
  - is_external : (bit)
  - is_ssas : (bit)
  - PumlEntityTopDefault : (nvarchar(max))
  - PumlEntityTopWorkaround : (nvarchar(max))
  RepoObject_DisplayName : (nvarchar(128))
  RepoObject_FullDisplayName2 : (nvarchar(257))
  - RepoObject_fullname : (nvarchar(261))
  - RepoObject_fullname2 : (nvarchar(257))
  - RepoObject_name : (nvarchar(128))
  - RepoObject_schema_name : (nvarchar(128))
  RepoObject_translation : (nvarchar(128))
  SysObject_type : (char(2))
  SysObject_type_name : (nvarchar(128))
  tables_isHidden : (bit)
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_outputfilter_t.adoc[]" as docs.RepoObject_OutputFilter_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  AntoraComponent : (nvarchar(max))
  AntoraModule : (nvarchar(max))
  external_AntoraComponent : (nvarchar(128))
  external_AntoraModule : (nvarchar(128))
  external_DatabaseName : (nvarchar(128))
  is_DocsOutput : (int)
  - is_external : (bit)
  - is_ssas : (bit)
  - PumlEntityTopDefault : (nvarchar(max))
  - PumlEntityTopWorkaround : (nvarchar(max))
  RepoObject_DisplayName : (nvarchar(128))
  RepoObject_FullDisplayName2 : (nvarchar(257))
  - RepoObject_fullname : (nvarchar(261))
  - RepoObject_fullname2 : (nvarchar(257))
  - RepoObject_name : (nvarchar(128))
  - RepoObject_schema_name : (nvarchar(128))
  RepoObject_translation : (nvarchar(128))
  SysObject_type : (char(2))
  SysObject_type_name : (nvarchar(128))
  tables_isHidden : (bit)
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_outputfilter_t_gross.adoc[]" as docs.RepoObject_OutputFilter_T_gross << V >> {
  AntoraComponent : (nvarchar(max))
  AntoraModule : (nvarchar(max))
  - cultures_name : (nvarchar(10))
  external_AntoraComponent : (nvarchar(128))
  external_AntoraModule : (nvarchar(128))
  external_DatabaseName : (nvarchar(128))
  FilenameRelatedMeasures : (nvarchar(4000))
  is_DocsOutput : (int)
  - is_external : (bit)
  - is_ssas : (bit)
  - PumlEntityTopDefault : (nvarchar(max))
  - PumlEntityTopWorkaround : (nvarchar(max))
  RepoObject_DisplayName : (nvarchar(128))
  RepoObject_FullDisplayName2 : (nvarchar(257))
  - RepoObject_fullname : (nvarchar(261))
  - RepoObject_fullname2 : (nvarchar(257))
  - RepoObject_guid : (uniqueidentifier)
  - RepoObject_name : (nvarchar(128))
  - RepoObject_schema_name : (nvarchar(128))
  RepoObject_translation : (nvarchar(128))
  SysObject_type : (char(2))
  SysObject_type_name : (nvarchar(128))
  tables_isHidden : (bit)
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml.adoc[]" as docs.RepoObject_Plantuml << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  **cultures_name** : (nvarchar(10))
  ColRefList : (nvarchar(max))
  ObjectRefList : (nvarchar(max))
  ObjectRefList_0_30 : (nvarchar(max))
  ObjectRefList_30_0 : (nvarchar(max))
  - PlantumlEntity_0_30_ObjectRef : (nvarchar(max))
  - PlantumlEntity_1_1_ColRef : (nvarchar(max))
  - PlantumlEntity_1_1_FkRef : (nvarchar(max))
  - PlantumlEntity_1_1_ObjectRef : (nvarchar(max))
  - PlantumlEntity_30_0_ObjectRef : (nvarchar(max))
  PumlEntityList : (nvarchar(max))
  PumlEntityList_0_30 : (nvarchar(max))
  PumlEntityList_30_0 : (nvarchar(max))
  - RepoObject_fullname2 : (nvarchar(257))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_colreflist_1_1.adoc[]" as docs.RepoObject_Plantuml_ColRefList_1_1 << V >> {
  ColRefList : (nvarchar(max))
  - cultures_name : (nvarchar(10))
  - RepoObject_guid : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_entity.adoc[]" as docs.RepoObject_Plantuml_Entity << V >> {
  - cultures_name : (nvarchar(10))
  - RepoObject_fullname2 : (nvarchar(257))
  - RepoObject_guid : (uniqueidentifier)
  - RepoObject_Puml : (nvarchar(max))
  - RepoObject_PumlOnlyIndex : (nvarchar(max))
  - RepoObject_PumlOnlyPK : (nvarchar(max))
  - RepoObject_PumlOnlyPkOrIndex : (nvarchar(max))
  - RepoObject_PumlOnlyPkOrIndexOrMeasure : (nvarchar(max))
  - RepoObject_PumlOnlyPkOrNotHidden : (nvarchar(max))
  - RepoObject_schema_name : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:docs.schema_puml.adoc[]" as docs.Schema_puml << V >> {
  - **RepoSchema_guid** : (uniqueidentifier)
  **cultures_name** : (nvarchar(10))
  - is_ssas : (bit)
  - PumlSchemaEr : (nvarchar(max))
  - PumlSchemaIndexEr : (nvarchar(max))
  PumlSchemaSsasEr : (nvarchar(max))
  - RepoSchema_name : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:docs.schema_ssasrelationlist.adoc[]" as docs.Schema_SsasRelationList << V >> {
  - **SchemaName** : (nvarchar(128))
  **cultures_name** : (nvarchar(10))
  SsasRelationList_PumlRelation : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:docs.unit_1_union.adoc[]" as docs.Unit_1_union << V >> {
  Object_fullname2 : (nvarchar(257))
  Object_Type : (varchar(2))
  Unit_ColummName : (nvarchar(128))
  Unit_Description : (nvarchar(max))
  Unit_DisplayFolder : (nvarchar(500))
  Unit_Expression : (nvarchar(max))
  Unit_FormatString : (nvarchar(500))
  - Unit_fullname2 : (nvarchar(638))
  - Unit_guid : (uniqueidentifier)
  Unit_isHidden : (bit)
  Unit_IsKey : (bit)
  Unit_IsSsas : (bit)
  Unit_IsUnique : (bit)
  - Unit_Metatype : (varchar(7))
  - Unit_Name : (nvarchar(500))
  Unit_ObjectName : (nvarchar(128))
  - Unit_Schema : (nvarchar(128))
  Unit_SummarizeBy : (nvarchar(500))
  Unit_TypeName : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_objectpage.adoc[]" as docs.usp_AntoraExport_ObjectPage << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_objectpartialscontent.adoc[]" as docs.usp_AntoraExport_ObjectPartialsContent << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_repoobject_outputfilter_t.adoc[]" as docs.usp_PERSIST_RepoObject_OutputFilter_T << P >> {
  --
}

docs.RepoObject_OutputFilter <.. docs.RepoObject_OutputFilter_T
docs.RepoObject_OutputFilter_T <.. docs.usp_AntoraExport_ObjectPage
docs.RepoObject_OutputFilter_T <.. docs.RepoObject_ColumnList
docs.RepoObject_OutputFilter_T <.. docs.AntoraNavListRepoObject_by_schema_type
docs.RepoObject_OutputFilter_T <.. docs.AntoraNavListRepoObject_by_schema
docs.RepoObject_OutputFilter_T <.. docs.AntoraNavListRepoObject_by_type
docs.RepoObject_OutputFilter_T <.. docs.Unit_1_union
docs.RepoObject_OutputFilter_T <.. docs.usp_PERSIST_RepoObject_OutputFilter_T
docs.RepoObject_OutputFilter_T <.. docs.Schema_SsasRelationList
docs.RepoObject_OutputFilter_T <.. docs.RepoObject_AntoraXrefCulturesList
docs.RepoObject_OutputFilter_T <.. docs.usp_AntoraExport_ObjectPartialsContent
docs.RepoObject_OutputFilter_T <.. docs.RepoObject_OutputFilter_T_gross
docs.RepoObject_OutputFilter_T <.. docs.Schema_puml
docs.RepoObject_OutputFilter_T <.. docs.RepoObject_Plantuml_ColRefList_1_1
docs.RepoObject_OutputFilter_T <.. docs.AntoraNavListPage_by_schema
docs.RepoObject_OutputFilter_T <.. docs.IndexSemanticgroupPatterndatatype
docs.RepoObject_OutputFilter_T <.. docs.AntoraNavListPage_by_type
docs.RepoObject_OutputFilter_T <.. docs.RepoObject_IndexList
docs.RepoObject_OutputFilter_T <.. docs.RepoObject_Plantuml
docs.RepoObject_OutputFilter_T <.. docs.RepoObject_Plantuml_Entity
"docs.RepoObject_OutputFilter::AntoraComponent" <-- "docs.RepoObject_OutputFilter_T::AntoraComponent"
"docs.RepoObject_OutputFilter::AntoraModule" <-- "docs.RepoObject_OutputFilter_T::AntoraModule"
"docs.RepoObject_OutputFilter::cultures_name" <-- "docs.RepoObject_OutputFilter_T::cultures_name"
"docs.RepoObject_OutputFilter::external_AntoraComponent" <-- "docs.RepoObject_OutputFilter_T::external_AntoraComponent"
"docs.RepoObject_OutputFilter::external_AntoraModule" <-- "docs.RepoObject_OutputFilter_T::external_AntoraModule"
"docs.RepoObject_OutputFilter::external_DatabaseName" <-- "docs.RepoObject_OutputFilter_T::external_DatabaseName"
"docs.RepoObject_OutputFilter::is_DocsOutput" <-- "docs.RepoObject_OutputFilter_T::is_DocsOutput"
"docs.RepoObject_OutputFilter::is_external" <-- "docs.RepoObject_OutputFilter_T::is_external"
"docs.RepoObject_OutputFilter::is_ssas" <-- "docs.RepoObject_OutputFilter_T::is_ssas"
"docs.RepoObject_OutputFilter::PumlEntityTopDefault" <-- "docs.RepoObject_OutputFilter_T::PumlEntityTopDefault"
"docs.RepoObject_OutputFilter::PumlEntityTopWorkaround" <-- "docs.RepoObject_OutputFilter_T::PumlEntityTopWorkaround"
"docs.RepoObject_OutputFilter::RepoObject_DisplayName" <-- "docs.RepoObject_OutputFilter_T::RepoObject_DisplayName"
"docs.RepoObject_OutputFilter::RepoObject_FullDisplayName2" <-- "docs.RepoObject_OutputFilter_T::RepoObject_FullDisplayName2"
"docs.RepoObject_OutputFilter::RepoObject_fullname" <-- "docs.RepoObject_OutputFilter_T::RepoObject_fullname"
"docs.RepoObject_OutputFilter::RepoObject_fullname2" <-- "docs.RepoObject_OutputFilter_T::RepoObject_fullname2"
"docs.RepoObject_OutputFilter::RepoObject_guid" <-- "docs.RepoObject_OutputFilter_T::RepoObject_guid"
"docs.RepoObject_OutputFilter::RepoObject_name" <-- "docs.RepoObject_OutputFilter_T::RepoObject_name"
"docs.RepoObject_OutputFilter::RepoObject_schema_name" <-- "docs.RepoObject_OutputFilter_T::RepoObject_schema_name"
"docs.RepoObject_OutputFilter::RepoObject_translation" <-- "docs.RepoObject_OutputFilter_T::RepoObject_translation"
"docs.RepoObject_OutputFilter::SysObject_type" <-- "docs.RepoObject_OutputFilter_T::SysObject_type"
"docs.RepoObject_OutputFilter::SysObject_type_name" <-- "docs.RepoObject_OutputFilter_T::SysObject_type_name"
"docs.RepoObject_OutputFilter::tables_isHidden" <-- "docs.RepoObject_OutputFilter_T::tables_isHidden"
"docs.RepoObject_OutputFilter_T::AntoraComponent" <-- "docs.RepoObject_OutputFilter_T_gross::AntoraComponent"
"docs.RepoObject_OutputFilter_T::AntoraModule" <-- "docs.RepoObject_OutputFilter_T_gross::AntoraModule"
"docs.RepoObject_OutputFilter_T::cultures_name" <-- "docs.RepoObject_OutputFilter_T_gross::cultures_name"
"docs.RepoObject_OutputFilter_T::cultures_name" <-- "docs.AntoraNavListRepoObject_by_schema_type::cultures_name"
"docs.RepoObject_OutputFilter_T::cultures_name" <-- "docs.AntoraNavListRepoObject_by_type::cultures_name"
"docs.RepoObject_OutputFilter_T::cultures_name" <-- "docs.RepoObject_Plantuml_ColRefList_1_1::cultures_name"
"docs.RepoObject_OutputFilter_T::cultures_name" <-- "docs.RepoObject_Plantuml_Entity::cultures_name"
"docs.RepoObject_OutputFilter_T::cultures_name" <-- "docs.RepoObject_Plantuml::cultures_name"
"docs.RepoObject_OutputFilter_T::cultures_name" <-- "docs.RepoObject_IndexList::cultures_name"
"docs.RepoObject_OutputFilter_T::cultures_name" <-- "docs.AntoraNavListPage_by_schema::cultures_name"
"docs.RepoObject_OutputFilter_T::cultures_name" <-- "docs.AntoraNavListRepoObject_by_schema::cultures_name"
"docs.RepoObject_OutputFilter_T::cultures_name" <-- "docs.RepoObject_ColumnList::cultures_name"
"docs.RepoObject_OutputFilter_T::cultures_name" <-- "docs.IndexSemanticgroupPatterndatatype::cultures_name"
"docs.RepoObject_OutputFilter_T::external_AntoraComponent" <-- "docs.RepoObject_OutputFilter_T_gross::external_AntoraComponent"
"docs.RepoObject_OutputFilter_T::external_AntoraModule" <-- "docs.RepoObject_OutputFilter_T_gross::external_AntoraModule"
"docs.RepoObject_OutputFilter_T::external_DatabaseName" <-- "docs.RepoObject_OutputFilter_T_gross::external_DatabaseName"
"docs.RepoObject_OutputFilter_T::is_DocsOutput" <-- "docs.RepoObject_OutputFilter_T_gross::is_DocsOutput"
"docs.RepoObject_OutputFilter_T::is_external" <-- "docs.RepoObject_OutputFilter_T_gross::is_external"
"docs.RepoObject_OutputFilter_T::is_external" <-- "docs.RepoObject_ColumnList::is_external"
"docs.RepoObject_OutputFilter_T::is_ssas" <-- "docs.AntoraNavListRepoObject_by_schema::is_ssas"
"docs.RepoObject_OutputFilter_T::is_ssas" <-- "docs.RepoObject_OutputFilter_T_gross::is_ssas"
"docs.RepoObject_OutputFilter_T::PumlEntityTopDefault" <-- "docs.RepoObject_OutputFilter_T_gross::PumlEntityTopDefault"
"docs.RepoObject_OutputFilter_T::PumlEntityTopWorkaround" <-- "docs.RepoObject_OutputFilter_T_gross::PumlEntityTopWorkaround"
"docs.RepoObject_OutputFilter_T::RepoObject_DisplayName" <-- "docs.RepoObject_OutputFilter_T_gross::RepoObject_DisplayName"
"docs.RepoObject_OutputFilter_T::RepoObject_FullDisplayName2" <-- "docs.RepoObject_OutputFilter_T_gross::RepoObject_FullDisplayName2"
"docs.RepoObject_OutputFilter_T::RepoObject_fullname" <-- "docs.RepoObject_OutputFilter_T_gross::RepoObject_fullname"
"docs.RepoObject_OutputFilter_T::RepoObject_fullname2" <-- "docs.RepoObject_OutputFilter_T_gross::RepoObject_fullname2"
"docs.RepoObject_OutputFilter_T::RepoObject_fullname2" <-- "docs.RepoObject_Plantuml_Entity::RepoObject_fullname2"
"docs.RepoObject_OutputFilter_T::RepoObject_guid" <-- "docs.RepoObject_Plantuml_ColRefList_1_1::RepoObject_guid"
"docs.RepoObject_OutputFilter_T::RepoObject_guid" <-- "docs.RepoObject_Plantuml_Entity::RepoObject_guid"
"docs.RepoObject_OutputFilter_T::RepoObject_guid" <-- "docs.RepoObject_ColumnList::RepoObject_guid"
"docs.RepoObject_OutputFilter_T::RepoObject_guid" <-- "docs.RepoObject_OutputFilter_T_gross::RepoObject_guid"
"docs.RepoObject_OutputFilter_T::RepoObject_guid" <-- "docs.RepoObject_AntoraXrefCulturesList::RepoObject_guid"
"docs.RepoObject_OutputFilter_T::RepoObject_name" <-- "docs.RepoObject_OutputFilter_T_gross::RepoObject_name"
"docs.RepoObject_OutputFilter_T::RepoObject_schema_name" <-- "docs.RepoObject_OutputFilter_T_gross::RepoObject_schema_name"
"docs.RepoObject_OutputFilter_T::RepoObject_schema_name" <-- "docs.AntoraNavListRepoObject_by_schema::RepoObject_schema_name"
"docs.RepoObject_OutputFilter_T::RepoObject_schema_name" <-- "docs.AntoraNavListRepoObject_by_schema_type::RepoObject_schema_name"
"docs.RepoObject_OutputFilter_T::RepoObject_schema_name" <-- "docs.RepoObject_Plantuml_Entity::RepoObject_schema_name"
"docs.RepoObject_OutputFilter_T::RepoObject_translation" <-- "docs.RepoObject_OutputFilter_T_gross::RepoObject_translation"
"docs.RepoObject_OutputFilter_T::SysObject_type" <-- "docs.RepoObject_OutputFilter_T_gross::SysObject_type"
"docs.RepoObject_OutputFilter_T::SysObject_type_name" <-- "docs.RepoObject_OutputFilter_T_gross::SysObject_type_name"
"docs.RepoObject_OutputFilter_T::SysObject_type_name" <-- "docs.AntoraNavListRepoObject_by_schema_type::type_name"
"docs.RepoObject_OutputFilter_T::SysObject_type_name" <-- "docs.AntoraNavListRepoObject_by_type::type_name"
"docs.RepoObject_OutputFilter_T::tables_isHidden" <-- "docs.RepoObject_OutputFilter_T_gross::tables_isHidden"

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_colref[]


== sql_modules_definition

// tag::sql_modules_definition[]
[%collapsible]
=======
[source,sql,numbered,indent=0]
----

----
=======
// end::sql_modules_definition[]


