// tag::HeaderFullDisplayName[]
= logs.ExecutionLog - U
// end::HeaderFullDisplayName[]

== existing_properties

// tag::existing_properties[]

:ExistsProperty--antorareferencinglist:
:ExistsProperty--is_repo_managed:
:ExistsProperty--is_ssas:
:ExistsProperty--pk_index_guid:
:ExistsProperty--pk_indexpatterncolumndatatype:
:ExistsProperty--pk_indexpatterncolumnname:
:ExistsProperty--FK:
:ExistsProperty--AntoraIndexList:
:ExistsProperty--Columns:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
1C90291C-9D61-EB11-84DC-A81E8446D5B0
// end::RepoObject_guid[]

== RepoObject_FullDisplayName2

// tag::RepoObject_FullDisplayName2[]
logs.ExecutionLog
// end::RepoObject_FullDisplayName2[]

== SysObject_type

// tag::SysObject_type[]
U 
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
user table
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
1064390861
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2022-06-30 17:24:34
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]
[discrete]
== _


[#column-id]
=== id

[cols="d,8a,m,m,m"]
|===
|1
|*id*
|bigint
|NOT NULL
|(1,1)
|===

.Referencing Columns
--
* xref:logs.executionlog_gross.adoc#column-id[+logs.ExecutionLog_gross.id+]
* xref:logs.executionlog_parent.adoc#column-id[+logs.ExecutionLog_parent.id+]
* xref:logs.executionlog_puml_sequence_start_stop.adoc#column-id[+logs.ExecutionLog_puml_Sequence_start_stop.id+]
--


[#column-createdunderlinedt]
=== created_dt

[cols="d,8a,m,m,m"]
|===
|
|created_dt
|datetime
|NULL
|
|===

.Referencing Columns
--
* xref:logs.executionlog_gross.adoc#column-createdunderlinedt[+logs.ExecutionLog_gross.created_dt+]
* xref:logs.executionlog_parent.adoc#column-parentunderlinecreatedunderlinedt[+logs.ExecutionLog_parent.parent_created_dt+]
* xref:logs.executionlog_puml_sequence_start_stop.adoc#column-createdunderlinedt[+logs.ExecutionLog_puml_Sequence_start_stop.created_dt+]
--


[#column-currentunderlineexecutionunderlineguid]
=== current_execution_guid

[cols="d,8a,m,m,m"]
|===
|
|current_execution_guid
|uniqueidentifier
|NULL
|
|===

.Referencing Columns
--
* xref:logs.executionlog_gross.adoc#column-currentunderlineexecutionunderlineguid[+logs.ExecutionLog_gross.current_execution_guid+]
* xref:logs.executionlog_parent.adoc#column-parentunderlinecurrentunderlineexecutionunderlineguid[+logs.ExecutionLog_parent.parent_current_execution_guid+]
--


[#column-deleted]
=== deleted

[cols="d,8a,m,m,m"]
|===
|
|deleted
|int
|NULL
|
|===

.Referencing Columns
--
* xref:logs.executionlog_gross.adoc#column-deleted[+logs.ExecutionLog_gross.deleted+]
--


[#column-eventunderlineinfo]
=== event_info

[cols="d,8a,m,m,m"]
|===
|
|event_info
|nvarchar(max)
|NULL
|
|===

.Referencing Columns
--
* xref:logs.executionlog_gross.adoc#column-eventunderlineinfo[+logs.ExecutionLog_gross.event_info+]
--


[#column-executionunderlineinstanceunderlineguid]
=== execution_instance_guid

[cols="d,8a,m,m,m"]
|===
|
|execution_instance_guid
|uniqueidentifier
|NOT NULL
|
|===

.Referencing Columns
--
* xref:logs.executionlog_gross.adoc#column-executionunderlineinstanceunderlineguid[+logs.ExecutionLog_gross.execution_instance_guid+]
* xref:logs.executionlog_puml_sequence_start_stop.adoc#column-executionunderlineinstanceunderlineguid[+logs.ExecutionLog_puml_Sequence_start_stop.execution_instance_guid+]
--


[#column-infounderline01]
=== info_01

[cols="d,8a,m,m,m"]
|===
|
|info_01
|nvarchar(4000)
|NULL
|
|===

.Referencing Columns
--
* xref:logs.executionlog_gross.adoc#column-infounderline01[+logs.ExecutionLog_gross.info_01+]
--


[#column-infounderline02]
=== info_02

[cols="d,8a,m,m,m"]
|===
|
|info_02
|nvarchar(4000)
|NULL
|
|===

.Referencing Columns
--
* xref:logs.executionlog_gross.adoc#column-infounderline02[+logs.ExecutionLog_gross.info_02+]
--


[#column-infounderline03]
=== info_03

[cols="d,8a,m,m,m"]
|===
|
|info_03
|nvarchar(4000)
|NULL
|
|===

.Referencing Columns
--
* xref:logs.executionlog_gross.adoc#column-infounderline03[+logs.ExecutionLog_gross.info_03+]
--


[#column-infounderline04]
=== info_04

[cols="d,8a,m,m,m"]
|===
|
|info_04
|nvarchar(4000)
|NULL
|
|===

.Referencing Columns
--
* xref:logs.executionlog_gross.adoc#column-infounderline04[+logs.ExecutionLog_gross.info_04+]
--


[#column-infounderline05]
=== info_05

[cols="d,8a,m,m,m"]
|===
|
|info_05
|nvarchar(4000)
|NULL
|
|===

.Referencing Columns
--
* xref:logs.executionlog_gross.adoc#column-infounderline05[+logs.ExecutionLog_gross.info_05+]
--


[#column-infounderline06]
=== info_06

[cols="d,8a,m,m,m"]
|===
|
|info_06
|nvarchar(4000)
|NULL
|
|===

.Referencing Columns
--
* xref:logs.executionlog_gross.adoc#column-infounderline06[+logs.ExecutionLog_gross.info_06+]
--


[#column-infounderline07]
=== info_07

[cols="d,8a,m,m,m"]
|===
|
|info_07
|nvarchar(4000)
|NULL
|
|===

.Referencing Columns
--
* xref:logs.executionlog_gross.adoc#column-infounderline07[+logs.ExecutionLog_gross.info_07+]
--


[#column-infounderline08]
=== info_08

[cols="d,8a,m,m,m"]
|===
|
|info_08
|nvarchar(4000)
|NULL
|
|===

.Referencing Columns
--
* xref:logs.executionlog_gross.adoc#column-infounderline08[+logs.ExecutionLog_gross.info_08+]
--


[#column-infounderline09]
=== info_09

[cols="d,8a,m,m,m"]
|===
|
|info_09
|nvarchar(4000)
|NULL
|
|===

.Referencing Columns
--
* xref:logs.executionlog_gross.adoc#column-infounderline09[+logs.ExecutionLog_gross.info_09+]
--


[#column-inserted]
=== inserted

[cols="d,8a,m,m,m"]
|===
|
|inserted
|int
|NULL
|
|===

.Referencing Columns
--
* xref:logs.executionlog_gross.adoc#column-inserted[+logs.ExecutionLog_gross.inserted+]
--


[#column-parameterunderline01]
=== parameter_01

[cols="d,8a,m,m,m"]
|===
|
|parameter_01
|nvarchar(4000)
|NULL
|
|===

.Referencing Columns
--
* xref:logs.executionlog_gross.adoc#column-parameterunderline01[+logs.ExecutionLog_gross.parameter_01+]
* xref:logs.executionlog_parent.adoc#column-parentunderlineparameterunderline01[+logs.ExecutionLog_parent.parent_parameter_01+]
--


[#column-parameterunderline02]
=== parameter_02

[cols="d,8a,m,m,m"]
|===
|
|parameter_02
|nvarchar(4000)
|NULL
|
|===

.Referencing Columns
--
* xref:logs.executionlog_gross.adoc#column-parameterunderline02[+logs.ExecutionLog_gross.parameter_02+]
* xref:logs.executionlog_parent.adoc#column-parentunderlineparameterunderline02[+logs.ExecutionLog_parent.parent_parameter_02+]
--


[#column-parameterunderline03]
=== parameter_03

[cols="d,8a,m,m,m"]
|===
|
|parameter_03
|nvarchar(4000)
|NULL
|
|===

.Referencing Columns
--
* xref:logs.executionlog_gross.adoc#column-parameterunderline03[+logs.ExecutionLog_gross.parameter_03+]
* xref:logs.executionlog_parent.adoc#column-parentunderlineparameterunderline03[+logs.ExecutionLog_parent.parent_parameter_03+]
--


[#column-parameterunderline04]
=== parameter_04

[cols="d,8a,m,m,m"]
|===
|
|parameter_04
|nvarchar(4000)
|NULL
|
|===

.Referencing Columns
--
* xref:logs.executionlog_gross.adoc#column-parameterunderline04[+logs.ExecutionLog_gross.parameter_04+]
* xref:logs.executionlog_parent.adoc#column-parentunderlineparameterunderline04[+logs.ExecutionLog_parent.parent_parameter_04+]
--


[#column-parameterunderline05]
=== parameter_05

[cols="d,8a,m,m,m"]
|===
|
|parameter_05
|nvarchar(4000)
|NULL
|
|===

.Referencing Columns
--
* xref:logs.executionlog_gross.adoc#column-parameterunderline05[+logs.ExecutionLog_gross.parameter_05+]
* xref:logs.executionlog_parent.adoc#column-parentunderlineparameterunderline05[+logs.ExecutionLog_parent.parent_parameter_05+]
--


[#column-parameterunderline06]
=== parameter_06

[cols="d,8a,m,m,m"]
|===
|
|parameter_06
|nvarchar(4000)
|NULL
|
|===

.Referencing Columns
--
* xref:logs.executionlog_gross.adoc#column-parameterunderline06[+logs.ExecutionLog_gross.parameter_06+]
* xref:logs.executionlog_parent.adoc#column-parentunderlineparameterunderline06[+logs.ExecutionLog_parent.parent_parameter_06+]
--


[#column-parameterunderline07]
=== parameter_07

[cols="d,8a,m,m,m"]
|===
|
|parameter_07
|nvarchar(4000)
|NULL
|
|===

.Referencing Columns
--
* xref:logs.executionlog_gross.adoc#column-parameterunderline07[+logs.ExecutionLog_gross.parameter_07+]
* xref:logs.executionlog_parent.adoc#column-parentunderlineparameterunderline07[+logs.ExecutionLog_parent.parent_parameter_07+]
--


[#column-parameterunderline08]
=== parameter_08

[cols="d,8a,m,m,m"]
|===
|
|parameter_08
|nvarchar(4000)
|NULL
|
|===

.Referencing Columns
--
* xref:logs.executionlog_gross.adoc#column-parameterunderline08[+logs.ExecutionLog_gross.parameter_08+]
* xref:logs.executionlog_parent.adoc#column-parentunderlineparameterunderline08[+logs.ExecutionLog_parent.parent_parameter_08+]
--


[#column-parameterunderline09]
=== parameter_09

[cols="d,8a,m,m,m"]
|===
|
|parameter_09
|nvarchar(4000)
|NULL
|
|===

.Referencing Columns
--
* xref:logs.executionlog_gross.adoc#column-parameterunderline09[+logs.ExecutionLog_gross.parameter_09+]
* xref:logs.executionlog_parent.adoc#column-parentunderlineparameterunderline09[+logs.ExecutionLog_parent.parent_parameter_09+]
--


[#column-parameterunderline10]
=== parameter_10

[cols="d,8a,m,m,m"]
|===
|
|parameter_10
|nvarchar(4000)
|NULL
|
|===

.Referencing Columns
--
* xref:logs.executionlog_gross.adoc#column-parameterunderline10[+logs.ExecutionLog_gross.parameter_10+]
* xref:logs.executionlog_parent.adoc#column-parentunderlineparameterunderline10[+logs.ExecutionLog_parent.parent_parameter_10+]
--


[#column-parameterunderline11]
=== parameter_11

[cols="d,8a,m,m,m"]
|===
|
|parameter_11
|nvarchar(4000)
|NULL
|
|===

.Referencing Columns
--
* xref:logs.executionlog_gross.adoc#column-parameterunderline11[+logs.ExecutionLog_gross.parameter_11+]
* xref:logs.executionlog_parent.adoc#column-parentunderlineparameterunderline11[+logs.ExecutionLog_parent.parent_parameter_11+]
--


[#column-parameterunderline12]
=== parameter_12

[cols="d,8a,m,m,m"]
|===
|
|parameter_12
|nvarchar(4000)
|NULL
|
|===

.Referencing Columns
--
* xref:logs.executionlog_gross.adoc#column-parameterunderline12[+logs.ExecutionLog_gross.parameter_12+]
* xref:logs.executionlog_parent.adoc#column-parentunderlineparameterunderline12[+logs.ExecutionLog_parent.parent_parameter_12+]
--


[#column-parameterunderline13]
=== parameter_13

[cols="d,8a,m,m,m"]
|===
|
|parameter_13
|nvarchar(4000)
|NULL
|
|===

.Referencing Columns
--
* xref:logs.executionlog_gross.adoc#column-parameterunderline13[+logs.ExecutionLog_gross.parameter_13+]
* xref:logs.executionlog_parent.adoc#column-parentunderlineparameterunderline13[+logs.ExecutionLog_parent.parent_parameter_13+]
--


[#column-parameterunderline14]
=== parameter_14

[cols="d,8a,m,m,m"]
|===
|
|parameter_14
|nvarchar(4000)
|NULL
|
|===

.Referencing Columns
--
* xref:logs.executionlog_gross.adoc#column-parameterunderline14[+logs.ExecutionLog_gross.parameter_14+]
* xref:logs.executionlog_parent.adoc#column-parentunderlineparameterunderline14[+logs.ExecutionLog_parent.parent_parameter_14+]
--


[#column-parameterunderline15]
=== parameter_15

[cols="d,8a,m,m,m"]
|===
|
|parameter_15
|nvarchar(4000)
|NULL
|
|===

.Referencing Columns
--
* xref:logs.executionlog_gross.adoc#column-parameterunderline15[+logs.ExecutionLog_gross.parameter_15+]
* xref:logs.executionlog_parent.adoc#column-parentunderlineparameterunderline15[+logs.ExecutionLog_parent.parent_parameter_15+]
--


[#column-parameterunderline16]
=== parameter_16

[cols="d,8a,m,m,m"]
|===
|
|parameter_16
|nvarchar(4000)
|NULL
|
|===

.Referencing Columns
--
* xref:logs.executionlog_gross.adoc#column-parameterunderline16[+logs.ExecutionLog_gross.parameter_16+]
* xref:logs.executionlog_parent.adoc#column-parentunderlineparameterunderline16[+logs.ExecutionLog_parent.parent_parameter_16+]
--


[#column-parameterunderline17]
=== parameter_17

[cols="d,8a,m,m,m"]
|===
|
|parameter_17
|nvarchar(4000)
|NULL
|
|===

.Referencing Columns
--
* xref:logs.executionlog_gross.adoc#column-parameterunderline17[+logs.ExecutionLog_gross.parameter_17+]
* xref:logs.executionlog_parent.adoc#column-parentunderlineparameterunderline17[+logs.ExecutionLog_parent.parent_parameter_17+]
--


[#column-parameterunderline18]
=== parameter_18

[cols="d,8a,m,m,m"]
|===
|
|parameter_18
|nvarchar(4000)
|NULL
|
|===

.Referencing Columns
--
* xref:logs.executionlog_gross.adoc#column-parameterunderline18[+logs.ExecutionLog_gross.parameter_18+]
* xref:logs.executionlog_parent.adoc#column-parentunderlineparameterunderline18[+logs.ExecutionLog_parent.parent_parameter_18+]
--


[#column-parameterunderline19]
=== parameter_19

[cols="d,8a,m,m,m"]
|===
|
|parameter_19
|nvarchar(4000)
|NULL
|
|===

.Referencing Columns
--
* xref:logs.executionlog_gross.adoc#column-parameterunderline19[+logs.ExecutionLog_gross.parameter_19+]
* xref:logs.executionlog_parent.adoc#column-parentunderlineparameterunderline19[+logs.ExecutionLog_parent.parent_parameter_19+]
--


[#column-parameterunderline20]
=== parameter_20

[cols="d,8a,m,m,m"]
|===
|
|parameter_20
|nvarchar(4000)
|NULL
|
|===

.Referencing Columns
--
* xref:logs.executionlog_gross.adoc#column-parameterunderline20[+logs.ExecutionLog_gross.parameter_20+]
* xref:logs.executionlog_parent.adoc#column-parentunderlineparameterunderline20[+logs.ExecutionLog_parent.parent_parameter_20+]
--


[#column-parentunderlineexecutionunderlinelogunderlineid]
=== parent_execution_log_id

[cols="d,8a,m,m,m"]
|===
|
|parent_execution_log_id
|bigint
|NULL
|
|===

.Referencing Columns
--
* xref:logs.executionlog_gross.adoc#column-parentunderlineexecutionunderlinelogunderlineid[+logs.ExecutionLog_gross.parent_execution_log_id+]
* xref:logs.executionlog_parent.adoc#column-parentunderlineexecutionunderlinelogunderlineid[+logs.ExecutionLog_parent.parent_execution_log_id+]
--


[#column-procunderlineid]
=== proc_id

[cols="d,8a,m,m,m"]
|===
|
|proc_id
|int
|NULL
|
|===

.Referencing Columns
--
* xref:logs.executionlog_gross.adoc#column-procunderlineid[+logs.ExecutionLog_gross.proc_id+]
* xref:logs.executionlog_parent.adoc#column-parentunderlineprocunderlineid[+logs.ExecutionLog_parent.parent_proc_id+]
--


[#column-procunderlinename]
=== proc_name

[cols="d,8a,m,m,m"]
|===
|
|proc_name
|nvarchar(128)
|NULL
|
|===

.Referencing Columns
--
* xref:logs.executionlog_gross.adoc#column-procunderlinename[+logs.ExecutionLog_gross.proc_name+]
* xref:logs.executionlog_parent.adoc#column-parentunderlineprocunderlinename[+logs.ExecutionLog_parent.parent_proc_name+]
--


[#column-procunderlineschemaunderlinename]
=== proc_schema_name

[cols="d,8a,m,m,m"]
|===
|
|proc_schema_name
|nvarchar(128)
|NULL
|
|===

.Referencing Columns
--
* xref:logs.executionlog_gross.adoc#column-procunderlineschemaunderlinename[+logs.ExecutionLog_gross.proc_schema_name+]
* xref:logs.executionlog_parent.adoc#column-parentunderlineprocunderlineschemaunderlinename[+logs.ExecutionLog_parent.parent_proc_schema_name+]
--


[#column-sourceunderlineobject]
=== source_object

[cols="d,8a,m,m,m"]
|===
|
|source_object
|nvarchar(261)
|NULL
|
|===

.Referencing Columns
--
* xref:logs.executionlog_gross.adoc#column-sourceunderlineobject[+logs.ExecutionLog_gross.source_object+]
--


[#column-ssisunderlineexecutionunderlineid]
=== ssis_execution_id

[cols="d,8a,m,m,m"]
|===
|
|ssis_execution_id
|bigint
|NULL
|
|===

.Referencing Columns
--
* xref:logs.executionlog_gross.adoc#column-ssisunderlineexecutionunderlineid[+logs.ExecutionLog_gross.ssis_execution_id+]
--


[#column-stepunderlineid]
=== step_id

[cols="d,8a,m,m,m"]
|===
|
|step_id
|int
|NULL
|
|===

.Referencing Columns
--
* xref:logs.executionlog_gross.adoc#column-stepunderlineid[+logs.ExecutionLog_gross.step_id+]
* xref:logs.executionlog_parent.adoc#column-parentunderlinestepunderlineid[+logs.ExecutionLog_parent.parent_step_id+]
--


[#column-stepunderlinename]
=== step_name

[cols="d,8a,m,m,m"]
|===
|
|step_name
|nvarchar(1000)
|NULL
|
|===

.Referencing Columns
--
* xref:logs.executionlog_gross.adoc#column-stepunderlinename[+logs.ExecutionLog_gross.step_name+]
* xref:logs.executionlog_parent.adoc#column-parentunderlinestepunderlinename[+logs.ExecutionLog_parent.parent_step_name+]
--


[#column-subunderlineexecutionunderlineid]
=== sub_execution_id

[cols="d,8a,m,m,m"]
|===
|
|sub_execution_id
|int
|NULL
|
|===

.Referencing Columns
--
* xref:logs.executionlog_gross.adoc#column-subunderlineexecutionunderlineid[+logs.ExecutionLog_gross.sub_execution_id+]
--


[#column-targetunderlineobject]
=== target_object

[cols="d,8a,m,m,m"]
|===
|
|target_object
|nvarchar(261)
|NULL
|
|===

.Referencing Columns
--
* xref:logs.executionlog_gross.adoc#column-targetunderlineobject[+logs.ExecutionLog_gross.target_object+]
--


[#column-updated]
=== updated

[cols="d,8a,m,m,m"]
|===
|
|updated
|int
|NULL
|
|===

.Referencing Columns
--
* xref:logs.executionlog_gross.adoc#column-updated[+logs.ExecutionLog_gross.updated+]
--


// end::AntoraColumnDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]
|1
|*<<column-id>>*
|bigint
|NOT NULL
|(1,1)















































// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]

|
|<<column-createdunderlinedt>>
|datetime
|NULL
|

|
|<<column-currentunderlineexecutionunderlineguid>>
|uniqueidentifier
|NULL
|

|
|<<column-deleted>>
|int
|NULL
|

|
|<<column-eventunderlineinfo>>
|nvarchar(max)
|NULL
|

|
|<<column-executionunderlineinstanceunderlineguid>>
|uniqueidentifier
|NOT NULL
|

|
|<<column-infounderline01>>
|nvarchar(4000)
|NULL
|

|
|<<column-infounderline02>>
|nvarchar(4000)
|NULL
|

|
|<<column-infounderline03>>
|nvarchar(4000)
|NULL
|

|
|<<column-infounderline04>>
|nvarchar(4000)
|NULL
|

|
|<<column-infounderline05>>
|nvarchar(4000)
|NULL
|

|
|<<column-infounderline06>>
|nvarchar(4000)
|NULL
|

|
|<<column-infounderline07>>
|nvarchar(4000)
|NULL
|

|
|<<column-infounderline08>>
|nvarchar(4000)
|NULL
|

|
|<<column-infounderline09>>
|nvarchar(4000)
|NULL
|

|
|<<column-inserted>>
|int
|NULL
|

|
|<<column-parameterunderline01>>
|nvarchar(4000)
|NULL
|

|
|<<column-parameterunderline02>>
|nvarchar(4000)
|NULL
|

|
|<<column-parameterunderline03>>
|nvarchar(4000)
|NULL
|

|
|<<column-parameterunderline04>>
|nvarchar(4000)
|NULL
|

|
|<<column-parameterunderline05>>
|nvarchar(4000)
|NULL
|

|
|<<column-parameterunderline06>>
|nvarchar(4000)
|NULL
|

|
|<<column-parameterunderline07>>
|nvarchar(4000)
|NULL
|

|
|<<column-parameterunderline08>>
|nvarchar(4000)
|NULL
|

|
|<<column-parameterunderline09>>
|nvarchar(4000)
|NULL
|

|
|<<column-parameterunderline10>>
|nvarchar(4000)
|NULL
|

|
|<<column-parameterunderline11>>
|nvarchar(4000)
|NULL
|

|
|<<column-parameterunderline12>>
|nvarchar(4000)
|NULL
|

|
|<<column-parameterunderline13>>
|nvarchar(4000)
|NULL
|

|
|<<column-parameterunderline14>>
|nvarchar(4000)
|NULL
|

|
|<<column-parameterunderline15>>
|nvarchar(4000)
|NULL
|

|
|<<column-parameterunderline16>>
|nvarchar(4000)
|NULL
|

|
|<<column-parameterunderline17>>
|nvarchar(4000)
|NULL
|

|
|<<column-parameterunderline18>>
|nvarchar(4000)
|NULL
|

|
|<<column-parameterunderline19>>
|nvarchar(4000)
|NULL
|

|
|<<column-parameterunderline20>>
|nvarchar(4000)
|NULL
|

|
|<<column-parentunderlineexecutionunderlinelogunderlineid>>
|bigint
|NULL
|

|
|<<column-procunderlineid>>
|int
|NULL
|

|
|<<column-procunderlinename>>
|nvarchar(128)
|NULL
|

|
|<<column-procunderlineschemaunderlinename>>
|nvarchar(128)
|NULL
|

|
|<<column-sourceunderlineobject>>
|nvarchar(261)
|NULL
|

|
|<<column-ssisunderlineexecutionunderlineid>>
|bigint
|NULL
|

|
|<<column-stepunderlineid>>
|int
|NULL
|

|
|<<column-stepunderlinename>>
|nvarchar(1000)
|NULL
|

|
|<<column-subunderlineexecutionunderlineid>>
|int
|NULL
|

|
|<<column-targetunderlineobject>>
|nvarchar(261)
|NULL
|

|
|<<column-updated>>
|int
|NULL
|

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

[#index-pkunderlineexecutionlog]
=== PK_ExecutionLog

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-id>>; bigint
--
* PK, Unique, Real: 1, 1, 1

// end::AntoraIndexList[]

== AntoraMeasureDetails

// tag::AntoraMeasureDetails[]

// end::AntoraMeasureDetails[]

== AntoraMeasureDescriptions



== AntoraParameterList

// tag::AntoraParameterList[]

// end::AntoraParameterList[]

== AntoraXrefCulturesList

// tag::AntoraXrefCulturesList[]
* xref:dhw:sqldb:logs.executionlog.adoc[] - 
// end::AntoraXrefCulturesList[]

== cultures_count

// tag::cultures_count[]
1
// end::cultures_count[]

== Other tags

source: property.RepoObjectProperty_cross As rop_cross


=== additional_reference_csv

// tag::additional_reference_csv[]

// end::additional_reference_csv[]


=== AdocUspSteps

// tag::adocuspsteps[]

// end::adocuspsteps[]


=== AntoraReferencedList

// tag::antorareferencedlist[]

// end::antorareferencedlist[]


=== AntoraReferencingList

// tag::antorareferencinglist[]
* xref:dhw:sqldb:logs.executionlog_gross.adoc[]
* xref:dhw:sqldb:logs.executionlog_parent.adoc[]
* xref:dhw:sqldb:logs.executionlog_puml_sequence_start_stop.adoc[]
* xref:dhw:sqldb:logs.usp_executionlog_insert.adoc[]
// end::antorareferencinglist[]


=== Description

// tag::description[]

// end::description[]


=== exampleUsage

// tag::exampleusage[]

// end::exampleusage[]


=== exampleUsage_2

// tag::exampleusage_2[]

// end::exampleusage_2[]


=== exampleUsage_3

// tag::exampleusage_3[]

// end::exampleusage_3[]


=== exampleUsage_4

// tag::exampleusage_4[]

// end::exampleusage_4[]


=== exampleUsage_5

// tag::exampleusage_5[]

// end::exampleusage_5[]


=== exampleWrong_Usage

// tag::examplewrong_usage[]

// end::examplewrong_usage[]


=== has_execution_plan_issue

// tag::has_execution_plan_issue[]

// end::has_execution_plan_issue[]


=== has_get_referenced_issue

// tag::has_get_referenced_issue[]

// end::has_get_referenced_issue[]


=== has_history

// tag::has_history[]

// end::has_history[]


=== has_history_columns

// tag::has_history_columns[]

// end::has_history_columns[]


=== InheritanceType

// tag::inheritancetype[]

// end::inheritancetype[]


=== is_persistence

// tag::is_persistence[]

// end::is_persistence[]


=== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]

// end::is_persistence_check_duplicate_per_pk[]


=== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]

// end::is_persistence_check_for_empty_source[]


=== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]

// end::is_persistence_delete_changed[]


=== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]

// end::is_persistence_delete_missing[]


=== is_persistence_insert

// tag::is_persistence_insert[]

// end::is_persistence_insert[]


=== is_persistence_truncate

// tag::is_persistence_truncate[]

// end::is_persistence_truncate[]


=== is_persistence_update_changed

// tag::is_persistence_update_changed[]

// end::is_persistence_update_changed[]


=== is_repo_managed

// tag::is_repo_managed[]
0
// end::is_repo_managed[]


=== is_ssas

// tag::is_ssas[]
0
// end::is_ssas[]


=== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


=== MS_Description

// tag::ms_description[]

// end::ms_description[]


=== persistence_source_RepoObject_fullname

// tag::persistence_source_repoobject_fullname[]

// end::persistence_source_repoobject_fullname[]


=== persistence_source_RepoObject_fullname2

// tag::persistence_source_repoobject_fullname2[]

// end::persistence_source_repoobject_fullname2[]


=== persistence_source_RepoObject_guid

// tag::persistence_source_repoobject_guid[]

// end::persistence_source_repoobject_guid[]


=== persistence_source_RepoObject_xref

// tag::persistence_source_repoobject_xref[]

// end::persistence_source_repoobject_xref[]


=== pk_index_guid

// tag::pk_index_guid[]
EF1EA651-464D-EC11-8531-A81E8446D5B0
// end::pk_index_guid[]


=== pk_IndexPatternColumnDatatype

// tag::pk_indexpatterncolumndatatype[]
bigint
// end::pk_indexpatterncolumndatatype[]


=== pk_IndexPatternColumnName

// tag::pk_indexpatterncolumnname[]
id
// end::pk_indexpatterncolumnname[]


=== pk_IndexSemanticGroup

// tag::pk_indexsemanticgroup[]

// end::pk_indexsemanticgroup[]


=== ReferencedObjectList

// tag::referencedobjectlist[]

// end::referencedobjectlist[]


=== usp_persistence_RepoObject_guid

// tag::usp_persistence_repoobject_guid[]

// end::usp_persistence_repoobject_guid[]


=== UspExamples

// tag::uspexamples[]

// end::uspexamples[]


=== uspgenerator_usp_id

// tag::uspgenerator_usp_id[]

// end::uspgenerator_usp_id[]


=== UspParameters

// tag::uspparameters[]

// end::uspparameters[]

== Boolean Attributes

source: property.RepoObjectProperty WHERE property_int = 1

// tag::boolean_attributes[]


// end::boolean_attributes[]

== PlantUML diagrams

=== PlantUML Entity

// tag::puml_entity[]
[plantuml, entity-{docname}, svg, subs=macros]
....
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:logs.executionlog.adoc[]" as logs.ExecutionLog << U >> {
  - **id** : (bigint)
  created_dt : (datetime)
  current_execution_guid : (uniqueidentifier)
  deleted : (int)
  event_info : (nvarchar(max))
  - execution_instance_guid : (uniqueidentifier)
  info_01 : (nvarchar(4000))
  info_02 : (nvarchar(4000))
  info_03 : (nvarchar(4000))
  info_04 : (nvarchar(4000))
  info_05 : (nvarchar(4000))
  info_06 : (nvarchar(4000))
  info_07 : (nvarchar(4000))
  info_08 : (nvarchar(4000))
  info_09 : (nvarchar(4000))
  inserted : (int)
  parameter_01 : (nvarchar(4000))
  parameter_02 : (nvarchar(4000))
  parameter_03 : (nvarchar(4000))
  parameter_04 : (nvarchar(4000))
  parameter_05 : (nvarchar(4000))
  parameter_06 : (nvarchar(4000))
  parameter_07 : (nvarchar(4000))
  parameter_08 : (nvarchar(4000))
  parameter_09 : (nvarchar(4000))
  parameter_10 : (nvarchar(4000))
  parameter_11 : (nvarchar(4000))
  parameter_12 : (nvarchar(4000))
  parameter_13 : (nvarchar(4000))
  parameter_14 : (nvarchar(4000))
  parameter_15 : (nvarchar(4000))
  parameter_16 : (nvarchar(4000))
  parameter_17 : (nvarchar(4000))
  parameter_18 : (nvarchar(4000))
  parameter_19 : (nvarchar(4000))
  parameter_20 : (nvarchar(4000))
  parent_execution_log_id : (bigint)
  proc_id : (int)
  proc_name : (nvarchar(128))
  proc_schema_name : (nvarchar(128))
  source_object : (nvarchar(261))
  ssis_execution_id : (bigint)
  step_id : (int)
  step_name : (nvarchar(1000))
  sub_execution_id : (int)
  target_object : (nvarchar(261))
  updated : (int)
  --
}
....

// end::puml_entity[]

=== PlantUML Entity 1 1 FK

// tag::puml_entity_1_1_fk[]
[plantuml, entity_1_1_fk-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:logs.executionlog.adoc[]" as logs.ExecutionLog << U >> {
**PK_ExecutionLog**

..
id; bigint
}



footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_fk[]

=== PlantUML 1 1 ObjectRef

// tag::puml_entity_1_1_objectref[]
[plantuml, entity_1_1_objectref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:logs.executionlog.adoc[]" as logs.ExecutionLog << U >> {
  - **id** : (bigint)
  --
}

entity "puml-link:dhw:sqldb:logs.executionlog_gross.adoc[]" as logs.ExecutionLog_gross << V >> {
  --
}

entity "puml-link:dhw:sqldb:logs.executionlog_parent.adoc[]" as logs.ExecutionLog_parent << V >> {
  --
}

entity "puml-link:dhw:sqldb:logs.executionlog_puml_sequence_start_stop.adoc[]" as logs.ExecutionLog_puml_Sequence_start_stop << V >> {
  --
}

entity "puml-link:dhw:sqldb:logs.usp_executionlog_insert.adoc[]" as logs.usp_ExecutionLog_insert << P >> {
  --
}

logs.ExecutionLog <.. logs.ExecutionLog_gross
logs.ExecutionLog <.. logs.ExecutionLog_parent
logs.ExecutionLog <.. logs.ExecutionLog_puml_Sequence_start_stop
logs.ExecutionLog <.. logs.usp_ExecutionLog_insert

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_objectref[]

=== PlantUML 30 0 ObjectRef

// tag::puml_entity_30_0_objectref[]
[plantuml, entity_30_0_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:logs.executionlog.adoc[]" as logs.ExecutionLog << U >> {
  - **id** : (bigint)
  --
}



footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_30_0_objectref[]

=== PlantUML 0 30 ObjectRef

// tag::puml_entity_0_30_objectref[]
[plantuml, entity_0_30_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:docs.usp_antoraexport.adoc[]" as docs.usp_AntoraExport << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_docsnippet.adoc[]" as docs.usp_AntoraExport_DocSnippet << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_objectnavigation.adoc[]" as docs.usp_AntoraExport_ObjectNavigation << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_objectpage.adoc[]" as docs.usp_AntoraExport_ObjectPage << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_objectpagetemplate.adoc[]" as docs.usp_AntoraExport_ObjectPageTemplate << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_objectpartialscontent.adoc[]" as docs.usp_AntoraExport_ObjectPartialsContent << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_objectpuml.adoc[]" as docs.usp_AntoraExport_ObjectPuml << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_objectrefcyclic.adoc[]" as docs.usp_AntoraExport_ObjectRefCyclic << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_page_indexsemanticgroup.adoc[]" as docs.usp_AntoraExport_Page_IndexSemanticGroup << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_ssisnavigation.adoc[]" as docs.usp_AntoraExport_SsisNavigation << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_ssispage.adoc[]" as docs.usp_AntoraExport_SsisPage << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_ssispagetemplate.adoc[]" as docs.usp_AntoraExport_SsisPageTemplate << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_ssispartialscontent.adoc[]" as docs.usp_AntoraExport_SsisPartialsContent << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_ssispuml.adoc[]" as docs.usp_AntoraExport_SsisPuml << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_repoobject_adoc_t.adoc[]" as docs.usp_PERSIST_RepoObject_Adoc_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_repoobject_columnlist_t.adoc[]" as docs.usp_PERSIST_RepoObject_ColumnList_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_repoobject_indexlist_t.adoc[]" as docs.usp_PERSIST_RepoObject_IndexList_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_repoobject_outputfilter_t.adoc[]" as docs.usp_PERSIST_RepoObject_OutputFilter_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_repoobject_plantuml_entity_t.adoc[]" as docs.usp_PERSIST_RepoObject_Plantuml_Entity_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_repoobject_plantuml_t.adoc[]" as docs.usp_PERSIST_RepoObject_Plantuml_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_ssis_adoc_t.adoc[]" as docs.usp_PERSIST_ssis_Adoc_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:logs.executionlog.adoc[]" as logs.ExecutionLog << U >> {
  - **id** : (bigint)
  --
}

entity "puml-link:dhw:sqldb:logs.executionlog_gross.adoc[]" as logs.ExecutionLog_gross << V >> {
  --
}

entity "puml-link:dhw:sqldb:logs.executionlog_parent.adoc[]" as logs.ExecutionLog_parent << V >> {
  --
}

entity "puml-link:dhw:sqldb:logs.executionlog_puml_sequence_start_stop.adoc[]" as logs.ExecutionLog_puml_Sequence_start_stop << V >> {
  --
}

entity "puml-link:dhw:sqldb:logs.ftv_executionlog_puml_sequence_start_stop_per_execution.adoc[]" as logs.ftv_ExecutionLog_puml_sequence_start_stop_per_execution << IF >> {
  --
}

entity "puml-link:dhw:sqldb:logs.ftv_executionlog_puml_tree.adoc[]" as logs.ftv_ExecutionLog_puml_tree << IF >> {
  --
}

entity "puml-link:dhw:sqldb:logs.ftv_executionlog_puml_tree_per_execution.adoc[]" as logs.ftv_ExecutionLog_puml_tree_per_execution << IF >> {
  --
}

entity "puml-link:dhw:sqldb:logs.usp_executionlog_insert.adoc[]" as logs.usp_ExecutionLog_insert << P >> {
  --
}

entity "puml-link:dhw:sqldb:property.usp_external_property_import.adoc[]" as property.usp_external_property_import << P >> {
  --
}

entity "puml-link:dhw:sqldb:property.usp_external_repoobjectproperty.adoc[]" as property.usp_external_RepoObjectProperty << P >> {
  --
}

entity "puml-link:dhw:sqldb:property.usp_persist_propertyname_measure_t.adoc[]" as property.usp_PERSIST_PropertyName_Measure_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:property.usp_persist_propertyname_repoobject_t.adoc[]" as property.usp_PERSIST_PropertyName_RepoObject_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:property.usp_persist_propertyname_repoobjectcolumn_t.adoc[]" as property.usp_PERSIST_PropertyName_RepoObjectColumn_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:property.usp_persist_repoobjectcolumnproperty_external_tgt.adoc[]" as property.usp_PERSIST_RepoObjectColumnProperty_external_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:property.usp_persist_repoobjectproperty_external_tgt.adoc[]" as property.usp_PERSIST_RepoObjectProperty_external_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:property.usp_repoobject_inheritance.adoc[]" as property.usp_RepoObject_Inheritance << P >> {
  --
}

entity "puml-link:dhw:sqldb:property.usp_repoobjectcolumn_inheritance.adoc[]" as property.usp_RepoObjectColumn_Inheritance << P >> {
  --
}

entity "puml-link:dhw:sqldb:property.usp_repoobjectproperty_collect.adoc[]" as property.usp_RepoObjectProperty_collect << P >> {
  --
}

entity "puml-link:dhw:sqldb:property.usp_sync_extendedproperties_repo2sys_delete.adoc[]" as property.usp_sync_ExtendedProperties_Repo2Sys_Delete << P >> {
  --
}

entity "puml-link:dhw:sqldb:property.usp_sync_extendedproperties_repo2sys_insertupdate.adoc[]" as property.usp_sync_ExtendedProperties_Repo2Sys_InsertUpdate << P >> {
  --
}

entity "puml-link:dhw:sqldb:property.usp_sync_extendedproperties_sys2repo_insertupdate.adoc[]" as property.usp_sync_ExtendedProperties_Sys2Repo_InsertUpdate << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_additional_reference.adoc[]" as reference.usp_additional_Reference << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_persist_additional_reference_database_t.adoc[]" as reference.usp_PERSIST_additional_Reference_database_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_persist_additional_reference_from_properties_tgt.adoc[]" as reference.usp_PERSIST_additional_Reference_from_properties_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_persist_additional_reference_from_ssas_tgt.adoc[]" as reference.usp_PERSIST_additional_Reference_from_ssas_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_persist_additional_reference_object_t.adoc[]" as reference.usp_PERSIST_additional_Reference_Object_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_persist_additional_reference_objectcolumn_t.adoc[]" as reference.usp_PERSIST_additional_Reference_ObjectColumn_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_persist_additional_reference_wo_columns_from_properties_tgt.adoc[]" as reference.usp_PERSIST_additional_Reference_wo_columns_from_properties_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_persist_repoobject_reference_t.adoc[]" as reference.usp_PERSIST_RepoObject_reference_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_persist_repoobject_referencetree_0_30_t.adoc[]" as reference.usp_PERSIST_RepoObject_ReferenceTree_0_30_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_persist_repoobject_referencetree_30_0_t.adoc[]" as reference.usp_PERSIST_RepoObject_ReferenceTree_30_0_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_persist_repoobjectcolumn_reference_t.adoc[]" as reference.usp_PERSIST_RepoObjectColumn_reference_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_repoobject_referencetree.adoc[]" as reference.usp_RepoObject_ReferenceTree << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_repoobject_referencetree_insert.adoc[]" as reference.usp_RepoObject_ReferenceTree_insert << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_repoobject_update_sysobjectqueryplan.adoc[]" as reference.usp_RepoObject_update_SysObjectQueryPlan << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_repoobjectsource_firstresultset.adoc[]" as reference.usp_RepoObjectSource_FirstResultSet << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_repoobjectsource_queryplan.adoc[]" as reference.usp_RepoObjectSource_QueryPlan << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_update_referencing_count.adoc[]" as reference.usp_update_Referencing_Count << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_index_finish.adoc[]" as repo.usp_Index_finish << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_index_foreignkey.adoc[]" as repo.usp_Index_ForeignKey << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_index_inheritance.adoc[]" as repo.usp_index_inheritance << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_index_settings.adoc[]" as repo.usp_Index_Settings << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_index_virtual_set.adoc[]" as repo.usp_Index_virtual_set << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_main.adoc[]" as repo.usp_main << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_persist_foreignkey_indexes_union_t.adoc[]" as repo.usp_PERSIST_ForeignKey_Indexes_union_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_persist_index_columlist_t.adoc[]" as repo.usp_PERSIST_Index_ColumList_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_persist_index_ssas_t.adoc[]" as repo.usp_PERSIST_Index_ssas_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_persist_indexcolumn_referencedreferencing_hasfullcolumnsinreferencing_t.adoc[]" as repo.usp_PERSIST_IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_persist_indexcolumn_ssas_t.adoc[]" as repo.usp_PERSIST_IndexColumn_ssas_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_persist_indexcolumn_union_t.adoc[]" as repo.usp_PERSIST_IndexColumn_union_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_persist_repoobject_external_tgt.adoc[]" as repo.usp_PERSIST_RepoObject_external_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_persist_repoobject_sat2_t.adoc[]" as repo.usp_PERSIST_RepoObject_sat2_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_persist_repoobject_ssas_tgt.adoc[]" as repo.usp_PERSIST_RepoObject_SSAS_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_persist_repoobjectcolumn_external_tgt.adoc[]" as repo.usp_PERSIST_RepoObjectColumn_external_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_persist_repoobjectcolumn_ssas_tgt.adoc[]" as repo.usp_PERSIST_RepoObjectColumn_SSAS_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_persist_reposchema_ssas_tgt.adoc[]" as repo.usp_PERSIST_RepoSchema_ssas_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_persistence_delete.adoc[]" as repo.usp_persistence_delete << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_persistence_set.adoc[]" as repo.usp_persistence_set << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_repoobjectcolumn_update_repoobjectcolumn_column_id.adoc[]" as repo.usp_RepoObjectColumn_update_RepoObjectColumn_column_id << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_sync_guid.adoc[]" as repo.usp_sync_guid << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_sync_guid_repoobject.adoc[]" as repo.usp_sync_guid_RepoObject << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_sync_guid_repoobject_ssas.adoc[]" as repo.usp_sync_guid_RepoObject_ssas << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_sync_guid_repoobjectcolumn.adoc[]" as repo.usp_sync_guid_RepoObjectColumn << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_sync_guid_repoobjectcolumn_ssas.adoc[]" as repo.usp_sync_guid_RepoObjectColumn_ssas << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_sync_guid_reposchema.adoc[]" as repo.usp_sync_guid_RepoSchema << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_sync_guid_reposchema_ssas.adoc[]" as repo.usp_sync_guid_RepoSchema_ssas << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_sync_guid_ssas.adoc[]" as repo.usp_sync_guid_ssas << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_update_referencing_count.adoc[]" as repo.usp_update_Referencing_Count << P >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.usp_persist_repoobject_sqlmodules_41_from_t.adoc[]" as sqlparse.usp_PERSIST_RepoObject_SqlModules_41_from_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.usp_persist_repoobject_sqlmodules_61_selectidentifier_union_t.adoc[]" as sqlparse.usp_PERSIST_RepoObject_SqlModules_61_SelectIdentifier_Union_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.usp_sqlparse.adoc[]" as sqlparse.usp_sqlparse << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.usp_persist_measure_translation_t.adoc[]" as ssas.usp_PERSIST_Measure_translation_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.usp_persist_model_json_31_tables_t.adoc[]" as ssas.usp_PERSIST_model_json_31_tables_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.usp_persist_model_json_311_tables_columns_t.adoc[]" as ssas.usp_PERSIST_model_json_311_tables_columns_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.usp_persist_model_json_312_tables_measures_t.adoc[]" as ssas.usp_PERSIST_model_json_312_tables_measures_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.usp_persist_model_json_32_relationships_t.adoc[]" as ssas.usp_PERSIST_model_json_32_relationships_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.usp_persist_model_json_33_datasources_t.adoc[]" as ssas.usp_PERSIST_model_json_33_dataSources_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.usp_persist_model_json_3411_cultures_translations_model_t.adoc[]" as ssas.usp_PERSIST_model_json_3411_cultures_translations_model_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.usp_persist_repoobjectcolumn_translation_t.adoc[]" as ssas.usp_PERSIST_RepoObjectColumn_translation_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_import.adoc[]" as ssis.usp_import << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_package_tgt.adoc[]" as ssis.usp_PERSIST_Package_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packageconnection_tgt.adoc[]" as ssis.usp_PERSIST_PackageConnection_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packageflow_tgt.adoc[]" as ssis.usp_PERSIST_PackageFlow_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packageparameter_tgt.adoc[]" as ssis.usp_PERSIST_PackageParameter_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packagetask_dft_component_input_externalmetadatacolumn_tgt.adoc[]" as ssis.usp_PERSIST_PackageTask_Dft_Component_input_externalMetadataColumn_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packagetask_dft_component_input_inputcolumn_tgt.adoc[]" as ssis.usp_PERSIST_PackageTask_Dft_Component_input_inputColumn_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packagetask_dft_component_input_tgt.adoc[]" as ssis.usp_PERSIST_PackageTask_Dft_Component_input_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packagetask_dft_component_output_externalmetadatacolumn_tgt.adoc[]" as ssis.usp_PERSIST_PackageTask_Dft_Component_output_externalMetadataColumn_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packagetask_dft_component_output_outputcolumn_tgt.adoc[]" as ssis.usp_PERSIST_PackageTask_Dft_Component_output_outputColumn_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packagetask_dft_component_output_tgt.adoc[]" as ssis.usp_PERSIST_PackageTask_Dft_Component_output_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packagetask_dft_component_tgt.adoc[]" as ssis.usp_PERSIST_PackageTask_Dft_Component_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packagetask_sql_parameter_tgt.adoc[]" as ssis.usp_PERSIST_PackageTask_Sql_Parameter_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packagetask_tgt.adoc[]" as ssis.usp_PERSIST_PackageTask_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packagevariable_tgt.adoc[]" as ssis.usp_PERSIST_PackageVariable_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_projectconnection_tgt.adoc[]" as ssis.usp_PERSIST_ProjectConnection_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.usp_copy_procedure.adoc[]" as uspgenerator.usp_copy_procedure << P >> {
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.usp_generatorusp_insert_update_persistence.adoc[]" as uspgenerator.usp_GeneratorUsp_insert_update_persistence << P >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.usp_persist_proceduredependency_persistencedependency_tgt.adoc[]" as workflow.usp_PERSIST_ProcedureDependency_PersistenceDependency_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.usp_persist_workflow_proceduredependency_t.adoc[]" as workflow.usp_PERSIST_Workflow_ProcedureDependency_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.usp_persist_workflow_proceduredependency_t_bidirectional_t.adoc[]" as workflow.usp_PERSIST_Workflow_ProcedureDependency_T_bidirectional_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.usp_persist_workflowstep.adoc[]" as workflow.usp_PERSIST_WorkflowStep << P >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.usp_workflow.adoc[]" as workflow.usp_workflow << P >> {
  --
}

docs.usp_AntoraExport_ObjectNavigation <.. docs.usp_AntoraExport
docs.usp_AntoraExport_ObjectPage <.. docs.usp_AntoraExport
docs.usp_AntoraExport_ObjectPageTemplate <.. docs.usp_AntoraExport
docs.usp_AntoraExport_ObjectPartialsContent <.. docs.usp_AntoraExport
docs.usp_AntoraExport_ObjectPuml <.. docs.usp_AntoraExport
docs.usp_AntoraExport_ObjectRefCyclic <.. docs.usp_AntoraExport
docs.usp_AntoraExport_Page_IndexSemanticGroup <.. docs.usp_AntoraExport
docs.usp_AntoraExport_SsisNavigation <.. docs.usp_AntoraExport
docs.usp_AntoraExport_SsisPage <.. docs.usp_AntoraExport
docs.usp_AntoraExport_SsisPageTemplate <.. docs.usp_AntoraExport
docs.usp_AntoraExport_SsisPartialsContent <.. docs.usp_AntoraExport
docs.usp_AntoraExport_SsisPuml <.. docs.usp_AntoraExport
docs.usp_PERSIST_RepoObject_Adoc_T <.. docs.usp_AntoraExport_ObjectPartialsContent
docs.usp_PERSIST_RepoObject_ColumnList_T <.. docs.usp_AntoraExport_ObjectPartialsContent
docs.usp_PERSIST_RepoObject_IndexList_T <.. docs.usp_AntoraExport_ObjectPartialsContent
docs.usp_PERSIST_RepoObject_OutputFilter_T <.. docs.usp_AntoraExport
docs.usp_PERSIST_RepoObject_Plantuml_Entity_T <.. docs.usp_AntoraExport_ObjectPuml
docs.usp_PERSIST_RepoObject_Plantuml_T <.. docs.usp_AntoraExport_ObjectPuml
docs.usp_PERSIST_ssis_Adoc_T <.. docs.usp_AntoraExport_SsisPartialsContent
logs.ExecutionLog <.. logs.ExecutionLog_gross
logs.ExecutionLog <.. logs.ExecutionLog_parent
logs.ExecutionLog <.. logs.ExecutionLog_puml_Sequence_start_stop
logs.ExecutionLog <.. logs.usp_ExecutionLog_insert
logs.ExecutionLog_gross <.. logs.ftv_ExecutionLog_puml_tree
logs.ExecutionLog_parent <.. logs.ExecutionLog_puml_Sequence_start_stop
logs.ExecutionLog_puml_Sequence_start_stop <.. logs.ftv_ExecutionLog_puml_sequence_start_stop_per_execution
logs.ftv_ExecutionLog_puml_tree <.. logs.ftv_ExecutionLog_puml_tree_per_execution
logs.usp_ExecutionLog_insert <.. docs.usp_AntoraExport
logs.usp_ExecutionLog_insert <.. docs.usp_AntoraExport_DocSnippet
logs.usp_ExecutionLog_insert <.. docs.usp_AntoraExport_ObjectNavigation
logs.usp_ExecutionLog_insert <.. docs.usp_AntoraExport_ObjectPage
logs.usp_ExecutionLog_insert <.. docs.usp_AntoraExport_ObjectPageTemplate
logs.usp_ExecutionLog_insert <.. docs.usp_AntoraExport_ObjectPartialsContent
logs.usp_ExecutionLog_insert <.. docs.usp_AntoraExport_ObjectPuml
logs.usp_ExecutionLog_insert <.. docs.usp_AntoraExport_ObjectRefCyclic
logs.usp_ExecutionLog_insert <.. docs.usp_AntoraExport_Page_IndexSemanticGroup
logs.usp_ExecutionLog_insert <.. docs.usp_AntoraExport_SsisNavigation
logs.usp_ExecutionLog_insert <.. docs.usp_AntoraExport_SsisPage
logs.usp_ExecutionLog_insert <.. docs.usp_AntoraExport_SsisPageTemplate
logs.usp_ExecutionLog_insert <.. docs.usp_AntoraExport_SsisPartialsContent
logs.usp_ExecutionLog_insert <.. docs.usp_AntoraExport_SsisPuml
logs.usp_ExecutionLog_insert <.. docs.usp_PERSIST_RepoObject_Adoc_T
logs.usp_ExecutionLog_insert <.. docs.usp_PERSIST_RepoObject_ColumnList_T
logs.usp_ExecutionLog_insert <.. docs.usp_PERSIST_RepoObject_IndexList_T
logs.usp_ExecutionLog_insert <.. docs.usp_PERSIST_RepoObject_OutputFilter_T
logs.usp_ExecutionLog_insert <.. docs.usp_PERSIST_RepoObject_Plantuml_Entity_T
logs.usp_ExecutionLog_insert <.. docs.usp_PERSIST_RepoObject_Plantuml_T
logs.usp_ExecutionLog_insert <.. docs.usp_PERSIST_ssis_Adoc_T
logs.usp_ExecutionLog_insert <.. property.usp_external_property_import
logs.usp_ExecutionLog_insert <.. property.usp_PERSIST_PropertyName_Measure_T
logs.usp_ExecutionLog_insert <.. property.usp_PERSIST_PropertyName_RepoObject_T
logs.usp_ExecutionLog_insert <.. property.usp_PERSIST_PropertyName_RepoObjectColumn_T
logs.usp_ExecutionLog_insert <.. property.usp_PERSIST_RepoObjectColumnProperty_external_tgt
logs.usp_ExecutionLog_insert <.. property.usp_PERSIST_RepoObjectProperty_external_tgt
logs.usp_ExecutionLog_insert <.. property.usp_RepoObject_Inheritance
logs.usp_ExecutionLog_insert <.. property.usp_RepoObjectColumn_Inheritance
logs.usp_ExecutionLog_insert <.. property.usp_RepoObjectProperty_collect
logs.usp_ExecutionLog_insert <.. property.usp_sync_ExtendedProperties_Repo2Sys_Delete
logs.usp_ExecutionLog_insert <.. property.usp_sync_ExtendedProperties_Repo2Sys_InsertUpdate
logs.usp_ExecutionLog_insert <.. property.usp_sync_ExtendedProperties_Sys2Repo_InsertUpdate
logs.usp_ExecutionLog_insert <.. reference.usp_additional_Reference
logs.usp_ExecutionLog_insert <.. reference.usp_PERSIST_additional_Reference_database_T
logs.usp_ExecutionLog_insert <.. reference.usp_PERSIST_additional_Reference_from_properties_tgt
logs.usp_ExecutionLog_insert <.. reference.usp_PERSIST_additional_Reference_from_ssas_tgt
logs.usp_ExecutionLog_insert <.. reference.usp_PERSIST_additional_Reference_Object_T
logs.usp_ExecutionLog_insert <.. reference.usp_PERSIST_additional_Reference_ObjectColumn_T
logs.usp_ExecutionLog_insert <.. reference.usp_PERSIST_additional_Reference_wo_columns_from_properties_tgt
logs.usp_ExecutionLog_insert <.. reference.usp_PERSIST_RepoObject_reference_T
logs.usp_ExecutionLog_insert <.. reference.usp_PERSIST_RepoObject_ReferenceTree_0_30_T
logs.usp_ExecutionLog_insert <.. reference.usp_PERSIST_RepoObject_ReferenceTree_30_0_T
logs.usp_ExecutionLog_insert <.. reference.usp_PERSIST_RepoObjectColumn_reference_T
logs.usp_ExecutionLog_insert <.. reference.usp_RepoObject_ReferenceTree
logs.usp_ExecutionLog_insert <.. reference.usp_RepoObject_ReferenceTree_insert
logs.usp_ExecutionLog_insert <.. reference.usp_RepoObject_update_SysObjectQueryPlan
logs.usp_ExecutionLog_insert <.. reference.usp_RepoObjectSource_FirstResultSet
logs.usp_ExecutionLog_insert <.. reference.usp_RepoObjectSource_QueryPlan
logs.usp_ExecutionLog_insert <.. reference.usp_update_Referencing_Count
logs.usp_ExecutionLog_insert <.. repo.usp_Index_finish
logs.usp_ExecutionLog_insert <.. repo.usp_Index_ForeignKey
logs.usp_ExecutionLog_insert <.. repo.usp_index_inheritance
logs.usp_ExecutionLog_insert <.. repo.usp_Index_Settings
logs.usp_ExecutionLog_insert <.. repo.usp_Index_virtual_set
logs.usp_ExecutionLog_insert <.. repo.usp_main
logs.usp_ExecutionLog_insert <.. repo.usp_PERSIST_ForeignKey_Indexes_union_T
logs.usp_ExecutionLog_insert <.. repo.usp_PERSIST_Index_ColumList_T
logs.usp_ExecutionLog_insert <.. repo.usp_PERSIST_Index_ssas_T
logs.usp_ExecutionLog_insert <.. repo.usp_PERSIST_IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T
logs.usp_ExecutionLog_insert <.. repo.usp_PERSIST_IndexColumn_ssas_T
logs.usp_ExecutionLog_insert <.. repo.usp_PERSIST_IndexColumn_union_T
logs.usp_ExecutionLog_insert <.. repo.usp_PERSIST_RepoObject_external_tgt
logs.usp_ExecutionLog_insert <.. repo.usp_PERSIST_RepoObject_sat2_T
logs.usp_ExecutionLog_insert <.. repo.usp_PERSIST_RepoObject_SSAS_tgt
logs.usp_ExecutionLog_insert <.. repo.usp_PERSIST_RepoObjectColumn_external_tgt
logs.usp_ExecutionLog_insert <.. repo.usp_PERSIST_RepoObjectColumn_SSAS_tgt
logs.usp_ExecutionLog_insert <.. repo.usp_PERSIST_RepoSchema_ssas_tgt
logs.usp_ExecutionLog_insert <.. repo.usp_persistence_delete
logs.usp_ExecutionLog_insert <.. repo.usp_persistence_set
logs.usp_ExecutionLog_insert <.. repo.usp_RepoObjectColumn_update_RepoObjectColumn_column_id
logs.usp_ExecutionLog_insert <.. repo.usp_sync_guid
logs.usp_ExecutionLog_insert <.. repo.usp_sync_guid_RepoObject
logs.usp_ExecutionLog_insert <.. repo.usp_sync_guid_RepoObject_ssas
logs.usp_ExecutionLog_insert <.. repo.usp_sync_guid_RepoObjectColumn
logs.usp_ExecutionLog_insert <.. repo.usp_sync_guid_RepoObjectColumn_ssas
logs.usp_ExecutionLog_insert <.. repo.usp_sync_guid_RepoSchema
logs.usp_ExecutionLog_insert <.. repo.usp_sync_guid_RepoSchema_ssas
logs.usp_ExecutionLog_insert <.. repo.usp_sync_guid_ssas
logs.usp_ExecutionLog_insert <.. repo.usp_update_Referencing_Count
logs.usp_ExecutionLog_insert <.. sqlparse.usp_PERSIST_RepoObject_SqlModules_41_from_T
logs.usp_ExecutionLog_insert <.. sqlparse.usp_PERSIST_RepoObject_SqlModules_61_SelectIdentifier_Union_T
logs.usp_ExecutionLog_insert <.. sqlparse.usp_sqlparse
logs.usp_ExecutionLog_insert <.. ssas.usp_PERSIST_Measure_translation_T
logs.usp_ExecutionLog_insert <.. ssas.usp_PERSIST_model_json_31_tables_T
logs.usp_ExecutionLog_insert <.. ssas.usp_PERSIST_model_json_311_tables_columns_T
logs.usp_ExecutionLog_insert <.. ssas.usp_PERSIST_model_json_312_tables_measures_T
logs.usp_ExecutionLog_insert <.. ssas.usp_PERSIST_model_json_32_relationships_T
logs.usp_ExecutionLog_insert <.. ssas.usp_PERSIST_model_json_33_dataSources_T
logs.usp_ExecutionLog_insert <.. ssas.usp_PERSIST_model_json_3411_cultures_translations_model_T
logs.usp_ExecutionLog_insert <.. ssas.usp_PERSIST_RepoObjectColumn_translation_T
logs.usp_ExecutionLog_insert <.. ssis.usp_PERSIST_Package_tgt
logs.usp_ExecutionLog_insert <.. ssis.usp_PERSIST_PackageConnection_tgt
logs.usp_ExecutionLog_insert <.. ssis.usp_PERSIST_PackageFlow_tgt
logs.usp_ExecutionLog_insert <.. ssis.usp_PERSIST_PackageParameter_tgt
logs.usp_ExecutionLog_insert <.. ssis.usp_PERSIST_PackageTask_Dft_Component_input_externalMetadataColumn_tgt
logs.usp_ExecutionLog_insert <.. ssis.usp_PERSIST_PackageTask_Dft_Component_input_inputColumn_tgt
logs.usp_ExecutionLog_insert <.. ssis.usp_PERSIST_PackageTask_Dft_Component_input_tgt
logs.usp_ExecutionLog_insert <.. ssis.usp_PERSIST_PackageTask_Dft_Component_output_externalMetadataColumn_tgt
logs.usp_ExecutionLog_insert <.. ssis.usp_PERSIST_PackageTask_Dft_Component_output_outputColumn_tgt
logs.usp_ExecutionLog_insert <.. ssis.usp_PERSIST_PackageTask_Dft_Component_output_tgt
logs.usp_ExecutionLog_insert <.. ssis.usp_PERSIST_PackageTask_Dft_Component_tgt
logs.usp_ExecutionLog_insert <.. ssis.usp_PERSIST_PackageTask_Sql_Parameter_tgt
logs.usp_ExecutionLog_insert <.. ssis.usp_PERSIST_PackageTask_tgt
logs.usp_ExecutionLog_insert <.. ssis.usp_PERSIST_PackageVariable_tgt
logs.usp_ExecutionLog_insert <.. ssis.usp_PERSIST_ProjectConnection_tgt
logs.usp_ExecutionLog_insert <.. uspgenerator.usp_copy_procedure
logs.usp_ExecutionLog_insert <.. uspgenerator.usp_GeneratorUsp_insert_update_persistence
logs.usp_ExecutionLog_insert <.. workflow.usp_PERSIST_ProcedureDependency_PersistenceDependency_tgt
logs.usp_ExecutionLog_insert <.. workflow.usp_PERSIST_Workflow_ProcedureDependency_T
logs.usp_ExecutionLog_insert <.. workflow.usp_PERSIST_Workflow_ProcedureDependency_T_bidirectional_T
logs.usp_ExecutionLog_insert <.. workflow.usp_PERSIST_WorkflowStep
logs.usp_ExecutionLog_insert <.. workflow.usp_workflow
property.usp_external_property_import <.. repo.usp_main
property.usp_PERSIST_PropertyName_Measure_T <.. repo.usp_main
property.usp_PERSIST_PropertyName_RepoObject_T <.. property.usp_RepoObject_Inheritance
property.usp_PERSIST_PropertyName_RepoObjectColumn_T <.. property.usp_RepoObjectColumn_Inheritance
property.usp_PERSIST_RepoObjectColumnProperty_external_tgt <.. property.usp_external_property_import
property.usp_PERSIST_RepoObjectColumnProperty_external_tgt <.. property.usp_external_RepoObjectProperty
property.usp_PERSIST_RepoObjectProperty_external_tgt <.. property.usp_external_property_import
property.usp_PERSIST_RepoObjectProperty_external_tgt <.. property.usp_external_RepoObjectProperty
property.usp_RepoObject_Inheritance <.. repo.usp_main
property.usp_RepoObjectColumn_Inheritance <.. repo.usp_main
property.usp_RepoObjectProperty_collect <.. property.usp_RepoObject_Inheritance
property.usp_RepoObjectProperty_collect <.. repo.usp_main
reference.usp_additional_Reference <.. property.usp_external_property_import
reference.usp_additional_Reference <.. repo.usp_main
reference.usp_PERSIST_additional_Reference_database_T <.. reference.usp_additional_Reference
reference.usp_PERSIST_additional_Reference_from_properties_tgt <.. repo.usp_main
reference.usp_PERSIST_additional_Reference_from_ssas_tgt <.. repo.usp_main
reference.usp_PERSIST_additional_Reference_Object_T <.. reference.usp_additional_Reference
reference.usp_PERSIST_additional_Reference_ObjectColumn_T <.. reference.usp_additional_Reference
reference.usp_PERSIST_additional_Reference_wo_columns_from_properties_tgt <.. repo.usp_main
reference.usp_PERSIST_RepoObject_reference_T <.. repo.usp_main
reference.usp_PERSIST_RepoObject_ReferenceTree_0_30_T <.. reference.usp_RepoObject_ReferenceTree
reference.usp_PERSIST_RepoObject_ReferenceTree_30_0_T <.. reference.usp_RepoObject_ReferenceTree
reference.usp_PERSIST_RepoObjectColumn_reference_T <.. repo.usp_main
reference.usp_RepoObject_ReferenceTree_insert <.. repo.usp_main
reference.usp_RepoObject_update_SysObjectQueryPlan <.. repo.usp_main
reference.usp_RepoObjectSource_FirstResultSet <.. repo.usp_main
reference.usp_RepoObjectSource_QueryPlan <.. repo.usp_main
reference.usp_update_Referencing_Count <.. repo.usp_main
repo.usp_Index_finish <.. repo.usp_Index_ForeignKey
repo.usp_Index_finish <.. repo.usp_index_inheritance
repo.usp_Index_ForeignKey <.. repo.usp_main
repo.usp_index_inheritance <.. repo.usp_main
repo.usp_Index_Settings <.. repo.usp_Index_finish
repo.usp_Index_virtual_set <.. repo.usp_Index_ForeignKey
repo.usp_PERSIST_ForeignKey_Indexes_union_T <.. repo.usp_Index_ForeignKey
repo.usp_PERSIST_Index_ColumList_T <.. repo.usp_Index_finish
repo.usp_PERSIST_Index_ssas_T <.. repo.usp_sync_guid_ssas
repo.usp_PERSIST_IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T <.. repo.usp_index_inheritance
repo.usp_PERSIST_IndexColumn_ssas_T <.. repo.usp_sync_guid_ssas
repo.usp_PERSIST_IndexColumn_union_T <.. repo.usp_Index_finish
repo.usp_PERSIST_RepoObject_external_tgt <.. reference.usp_additional_Reference
repo.usp_PERSIST_RepoObject_sat2_T <.. repo.usp_main
repo.usp_PERSIST_RepoObject_SSAS_tgt <.. repo.usp_sync_guid_ssas
repo.usp_PERSIST_RepoObjectColumn_external_tgt <.. reference.usp_additional_Reference
repo.usp_PERSIST_RepoObjectColumn_SSAS_tgt <.. repo.usp_sync_guid_ssas
repo.usp_PERSIST_RepoSchema_ssas_tgt <.. repo.usp_sync_guid_ssas
repo.usp_RepoObjectColumn_update_RepoObjectColumn_column_id <.. repo.usp_main
repo.usp_sync_guid <.. repo.usp_main
repo.usp_sync_guid <.. repo.usp_persistence_set
repo.usp_sync_guid_RepoObject <.. repo.usp_sync_guid
repo.usp_sync_guid_RepoObjectColumn <.. repo.usp_sync_guid
repo.usp_sync_guid_RepoSchema <.. repo.usp_sync_guid
repo.usp_sync_guid_ssas <.. repo.usp_main
sqlparse.usp_PERSIST_RepoObject_SqlModules_41_from_T <.. sqlparse.usp_sqlparse
sqlparse.usp_PERSIST_RepoObject_SqlModules_61_SelectIdentifier_Union_T <.. sqlparse.usp_sqlparse
ssas.usp_PERSIST_Measure_translation_T <.. repo.usp_sync_guid_ssas
ssas.usp_PERSIST_model_json_31_tables_T <.. repo.usp_sync_guid_ssas
ssas.usp_PERSIST_model_json_311_tables_columns_T <.. repo.usp_sync_guid_ssas
ssas.usp_PERSIST_model_json_312_tables_measures_T <.. repo.usp_sync_guid_ssas
ssas.usp_PERSIST_model_json_32_relationships_T <.. repo.usp_sync_guid_ssas
ssas.usp_PERSIST_model_json_33_dataSources_T <.. repo.usp_sync_guid_ssas
ssas.usp_PERSIST_model_json_3411_cultures_translations_model_T <.. repo.usp_sync_guid_ssas
ssas.usp_PERSIST_RepoObjectColumn_translation_T <.. repo.usp_main
ssis.usp_PERSIST_Package_tgt <.. ssis.usp_import
ssis.usp_PERSIST_PackageConnection_tgt <.. ssis.usp_import
ssis.usp_PERSIST_PackageFlow_tgt <.. ssis.usp_import
ssis.usp_PERSIST_PackageParameter_tgt <.. ssis.usp_import
ssis.usp_PERSIST_PackageTask_Dft_Component_input_externalMetadataColumn_tgt <.. ssis.usp_import
ssis.usp_PERSIST_PackageTask_Dft_Component_input_inputColumn_tgt <.. ssis.usp_import
ssis.usp_PERSIST_PackageTask_Dft_Component_input_tgt <.. ssis.usp_import
ssis.usp_PERSIST_PackageTask_Dft_Component_output_externalMetadataColumn_tgt <.. ssis.usp_import
ssis.usp_PERSIST_PackageTask_Dft_Component_output_outputColumn_tgt <.. ssis.usp_import
ssis.usp_PERSIST_PackageTask_Dft_Component_output_tgt <.. ssis.usp_import
ssis.usp_PERSIST_PackageTask_Dft_Component_tgt <.. ssis.usp_import
ssis.usp_PERSIST_PackageTask_Sql_Parameter_tgt <.. ssis.usp_import
ssis.usp_PERSIST_PackageTask_tgt <.. ssis.usp_import
ssis.usp_PERSIST_PackageVariable_tgt <.. ssis.usp_import
ssis.usp_PERSIST_ProjectConnection_tgt <.. ssis.usp_import
uspgenerator.usp_GeneratorUsp_insert_update_persistence <.. repo.usp_main
workflow.usp_PERSIST_ProcedureDependency_PersistenceDependency_tgt <.. workflow.usp_workflow
workflow.usp_PERSIST_Workflow_ProcedureDependency_T <.. workflow.usp_workflow
workflow.usp_PERSIST_Workflow_ProcedureDependency_T_bidirectional_T <.. workflow.usp_workflow
workflow.usp_PERSIST_WorkflowStep <.. workflow.usp_workflow

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_0_30_objectref[]

=== PlantUML 1 1 ColumnRef

// tag::puml_entity_1_1_colref[]
[plantuml, entity_1_1_colref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:logs.executionlog.adoc[]" as logs.ExecutionLog << U >> {
  - **id** : (bigint)
  created_dt : (datetime)
  current_execution_guid : (uniqueidentifier)
  deleted : (int)
  event_info : (nvarchar(max))
  - execution_instance_guid : (uniqueidentifier)
  info_01 : (nvarchar(4000))
  info_02 : (nvarchar(4000))
  info_03 : (nvarchar(4000))
  info_04 : (nvarchar(4000))
  info_05 : (nvarchar(4000))
  info_06 : (nvarchar(4000))
  info_07 : (nvarchar(4000))
  info_08 : (nvarchar(4000))
  info_09 : (nvarchar(4000))
  inserted : (int)
  parameter_01 : (nvarchar(4000))
  parameter_02 : (nvarchar(4000))
  parameter_03 : (nvarchar(4000))
  parameter_04 : (nvarchar(4000))
  parameter_05 : (nvarchar(4000))
  parameter_06 : (nvarchar(4000))
  parameter_07 : (nvarchar(4000))
  parameter_08 : (nvarchar(4000))
  parameter_09 : (nvarchar(4000))
  parameter_10 : (nvarchar(4000))
  parameter_11 : (nvarchar(4000))
  parameter_12 : (nvarchar(4000))
  parameter_13 : (nvarchar(4000))
  parameter_14 : (nvarchar(4000))
  parameter_15 : (nvarchar(4000))
  parameter_16 : (nvarchar(4000))
  parameter_17 : (nvarchar(4000))
  parameter_18 : (nvarchar(4000))
  parameter_19 : (nvarchar(4000))
  parameter_20 : (nvarchar(4000))
  parent_execution_log_id : (bigint)
  proc_id : (int)
  proc_name : (nvarchar(128))
  proc_schema_name : (nvarchar(128))
  source_object : (nvarchar(261))
  ssis_execution_id : (bigint)
  step_id : (int)
  step_name : (nvarchar(1000))
  sub_execution_id : (int)
  target_object : (nvarchar(261))
  updated : (int)
  --
}

entity "puml-link:dhw:sqldb:logs.executionlog_gross.adoc[]" as logs.ExecutionLog_gross << V >> {
  created_dt : (datetime)
  created_dt_max_execution_instance_guid : (datetime)
  created_dt_min_execution_instance_guid : (datetime)
  current_execution_guid : (uniqueidentifier)
  deleted : (int)
  duration_current_execution_guid : (int)
  duration_execution_instance_guid : (int)
  duration_step : (int)
  event_info : (nvarchar(max))
  - execution_instance_guid : (uniqueidentifier)
  - id : (bigint)
  info_01 : (nvarchar(4000))
  info_02 : (nvarchar(4000))
  info_03 : (nvarchar(4000))
  info_04 : (nvarchar(4000))
  info_05 : (nvarchar(4000))
  info_06 : (nvarchar(4000))
  info_07 : (nvarchar(4000))
  info_08 : (nvarchar(4000))
  info_09 : (nvarchar(4000))
  inserted : (int)
  parameter_01 : (nvarchar(4000))
  parameter_02 : (nvarchar(4000))
  parameter_03 : (nvarchar(4000))
  parameter_04 : (nvarchar(4000))
  parameter_05 : (nvarchar(4000))
  parameter_06 : (nvarchar(4000))
  parameter_07 : (nvarchar(4000))
  parameter_08 : (nvarchar(4000))
  parameter_09 : (nvarchar(4000))
  parameter_10 : (nvarchar(4000))
  parameter_11 : (nvarchar(4000))
  parameter_12 : (nvarchar(4000))
  parameter_13 : (nvarchar(4000))
  parameter_14 : (nvarchar(4000))
  parameter_15 : (nvarchar(4000))
  parameter_16 : (nvarchar(4000))
  parameter_17 : (nvarchar(4000))
  parameter_18 : (nvarchar(4000))
  parameter_19 : (nvarchar(4000))
  parameter_20 : (nvarchar(4000))
  parent_execution_log_id : (bigint)
  proc_id : (int)
  proc_name : (nvarchar(128))
  proc_schema_name : (nvarchar(128))
  - puml_Sequence : (nvarchar(1550))
  source_object : (nvarchar(261))
  ssis_execution_id : (bigint)
  step_id : (int)
  step_name : (nvarchar(1000))
  sub_execution_id : (int)
  target_object : (nvarchar(261))
  updated : (int)
  --
}

entity "puml-link:dhw:sqldb:logs.executionlog_parent.adoc[]" as logs.ExecutionLog_parent << V >> {
  - id : (bigint)
  parent_created_dt : (datetime)
  parent_current_execution_guid : (uniqueidentifier)
  parent_execution_log_id : (bigint)
  parent_parameter_01 : (nvarchar(4000))
  parent_parameter_02 : (nvarchar(4000))
  parent_parameter_03 : (nvarchar(4000))
  parent_parameter_04 : (nvarchar(4000))
  parent_parameter_05 : (nvarchar(4000))
  parent_parameter_06 : (nvarchar(4000))
  parent_parameter_07 : (nvarchar(4000))
  parent_parameter_08 : (nvarchar(4000))
  parent_parameter_09 : (nvarchar(4000))
  parent_parameter_10 : (nvarchar(4000))
  parent_parameter_11 : (nvarchar(4000))
  parent_parameter_12 : (nvarchar(4000))
  parent_parameter_13 : (nvarchar(4000))
  parent_parameter_14 : (nvarchar(4000))
  parent_parameter_15 : (nvarchar(4000))
  parent_parameter_16 : (nvarchar(4000))
  parent_parameter_17 : (nvarchar(4000))
  parent_parameter_18 : (nvarchar(4000))
  parent_parameter_19 : (nvarchar(4000))
  parent_parameter_20 : (nvarchar(4000))
  - parent_proc_fullname : (nvarchar(517))
  parent_proc_id : (int)
  parent_proc_name : (nvarchar(128))
  parent_proc_schema_name : (nvarchar(128))
  parent_step_id : (int)
  parent_step_name : (nvarchar(1000))
  --
}

entity "puml-link:dhw:sqldb:logs.executionlog_puml_sequence_start_stop.adoc[]" as logs.ExecutionLog_puml_Sequence_start_stop << V >> {
  created_dt : (datetime)
  - execution_instance_guid : (uniqueidentifier)
  - id : (bigint)
  parent_proc_fullname : (nvarchar(517))
  - proc_fullname : (nvarchar(517))
  - puml_Sequence_start_stop : (nvarchar(1574))
  --
}

entity "puml-link:dhw:sqldb:logs.usp_executionlog_insert.adoc[]" as logs.usp_ExecutionLog_insert << P >> {
  --
}

logs.ExecutionLog <.. logs.ExecutionLog_gross
logs.ExecutionLog <.. logs.ExecutionLog_parent
logs.ExecutionLog <.. logs.ExecutionLog_puml_Sequence_start_stop
logs.ExecutionLog <.. logs.usp_ExecutionLog_insert
"logs.ExecutionLog::created_dt" <-- "logs.ExecutionLog_gross::created_dt"
"logs.ExecutionLog::created_dt" <-- "logs.ExecutionLog_parent::parent_created_dt"
"logs.ExecutionLog::created_dt" <-- "logs.ExecutionLog_puml_Sequence_start_stop::created_dt"
"logs.ExecutionLog::current_execution_guid" <-- "logs.ExecutionLog_gross::current_execution_guid"
"logs.ExecutionLog::current_execution_guid" <-- "logs.ExecutionLog_parent::parent_current_execution_guid"
"logs.ExecutionLog::deleted" <-- "logs.ExecutionLog_gross::deleted"
"logs.ExecutionLog::event_info" <-- "logs.ExecutionLog_gross::event_info"
"logs.ExecutionLog::execution_instance_guid" <-- "logs.ExecutionLog_gross::execution_instance_guid"
"logs.ExecutionLog::execution_instance_guid" <-- "logs.ExecutionLog_puml_Sequence_start_stop::execution_instance_guid"
"logs.ExecutionLog::id" <-- "logs.ExecutionLog_gross::id"
"logs.ExecutionLog::id" <-- "logs.ExecutionLog_parent::id"
"logs.ExecutionLog::id" <-- "logs.ExecutionLog_puml_Sequence_start_stop::id"
"logs.ExecutionLog::info_01" <-- "logs.ExecutionLog_gross::info_01"
"logs.ExecutionLog::info_02" <-- "logs.ExecutionLog_gross::info_02"
"logs.ExecutionLog::info_03" <-- "logs.ExecutionLog_gross::info_03"
"logs.ExecutionLog::info_04" <-- "logs.ExecutionLog_gross::info_04"
"logs.ExecutionLog::info_05" <-- "logs.ExecutionLog_gross::info_05"
"logs.ExecutionLog::info_06" <-- "logs.ExecutionLog_gross::info_06"
"logs.ExecutionLog::info_07" <-- "logs.ExecutionLog_gross::info_07"
"logs.ExecutionLog::info_08" <-- "logs.ExecutionLog_gross::info_08"
"logs.ExecutionLog::info_09" <-- "logs.ExecutionLog_gross::info_09"
"logs.ExecutionLog::inserted" <-- "logs.ExecutionLog_gross::inserted"
"logs.ExecutionLog::parameter_01" <-- "logs.ExecutionLog_gross::parameter_01"
"logs.ExecutionLog::parameter_01" <-- "logs.ExecutionLog_parent::parent_parameter_01"
"logs.ExecutionLog::parameter_02" <-- "logs.ExecutionLog_gross::parameter_02"
"logs.ExecutionLog::parameter_02" <-- "logs.ExecutionLog_parent::parent_parameter_02"
"logs.ExecutionLog::parameter_03" <-- "logs.ExecutionLog_gross::parameter_03"
"logs.ExecutionLog::parameter_03" <-- "logs.ExecutionLog_parent::parent_parameter_03"
"logs.ExecutionLog::parameter_04" <-- "logs.ExecutionLog_gross::parameter_04"
"logs.ExecutionLog::parameter_04" <-- "logs.ExecutionLog_parent::parent_parameter_04"
"logs.ExecutionLog::parameter_05" <-- "logs.ExecutionLog_gross::parameter_05"
"logs.ExecutionLog::parameter_05" <-- "logs.ExecutionLog_parent::parent_parameter_05"
"logs.ExecutionLog::parameter_06" <-- "logs.ExecutionLog_gross::parameter_06"
"logs.ExecutionLog::parameter_06" <-- "logs.ExecutionLog_parent::parent_parameter_06"
"logs.ExecutionLog::parameter_07" <-- "logs.ExecutionLog_gross::parameter_07"
"logs.ExecutionLog::parameter_07" <-- "logs.ExecutionLog_parent::parent_parameter_07"
"logs.ExecutionLog::parameter_08" <-- "logs.ExecutionLog_gross::parameter_08"
"logs.ExecutionLog::parameter_08" <-- "logs.ExecutionLog_parent::parent_parameter_08"
"logs.ExecutionLog::parameter_09" <-- "logs.ExecutionLog_gross::parameter_09"
"logs.ExecutionLog::parameter_09" <-- "logs.ExecutionLog_parent::parent_parameter_09"
"logs.ExecutionLog::parameter_10" <-- "logs.ExecutionLog_gross::parameter_10"
"logs.ExecutionLog::parameter_10" <-- "logs.ExecutionLog_parent::parent_parameter_10"
"logs.ExecutionLog::parameter_11" <-- "logs.ExecutionLog_gross::parameter_11"
"logs.ExecutionLog::parameter_11" <-- "logs.ExecutionLog_parent::parent_parameter_11"
"logs.ExecutionLog::parameter_12" <-- "logs.ExecutionLog_gross::parameter_12"
"logs.ExecutionLog::parameter_12" <-- "logs.ExecutionLog_parent::parent_parameter_12"
"logs.ExecutionLog::parameter_13" <-- "logs.ExecutionLog_gross::parameter_13"
"logs.ExecutionLog::parameter_13" <-- "logs.ExecutionLog_parent::parent_parameter_13"
"logs.ExecutionLog::parameter_14" <-- "logs.ExecutionLog_gross::parameter_14"
"logs.ExecutionLog::parameter_14" <-- "logs.ExecutionLog_parent::parent_parameter_14"
"logs.ExecutionLog::parameter_15" <-- "logs.ExecutionLog_gross::parameter_15"
"logs.ExecutionLog::parameter_15" <-- "logs.ExecutionLog_parent::parent_parameter_15"
"logs.ExecutionLog::parameter_16" <-- "logs.ExecutionLog_gross::parameter_16"
"logs.ExecutionLog::parameter_16" <-- "logs.ExecutionLog_parent::parent_parameter_16"
"logs.ExecutionLog::parameter_17" <-- "logs.ExecutionLog_gross::parameter_17"
"logs.ExecutionLog::parameter_17" <-- "logs.ExecutionLog_parent::parent_parameter_17"
"logs.ExecutionLog::parameter_18" <-- "logs.ExecutionLog_gross::parameter_18"
"logs.ExecutionLog::parameter_18" <-- "logs.ExecutionLog_parent::parent_parameter_18"
"logs.ExecutionLog::parameter_19" <-- "logs.ExecutionLog_gross::parameter_19"
"logs.ExecutionLog::parameter_19" <-- "logs.ExecutionLog_parent::parent_parameter_19"
"logs.ExecutionLog::parameter_20" <-- "logs.ExecutionLog_gross::parameter_20"
"logs.ExecutionLog::parameter_20" <-- "logs.ExecutionLog_parent::parent_parameter_20"
"logs.ExecutionLog::parent_execution_log_id" <-- "logs.ExecutionLog_gross::parent_execution_log_id"
"logs.ExecutionLog::parent_execution_log_id" <-- "logs.ExecutionLog_parent::parent_execution_log_id"
"logs.ExecutionLog::proc_id" <-- "logs.ExecutionLog_gross::proc_id"
"logs.ExecutionLog::proc_id" <-- "logs.ExecutionLog_parent::parent_proc_id"
"logs.ExecutionLog::proc_name" <-- "logs.ExecutionLog_gross::proc_name"
"logs.ExecutionLog::proc_name" <-- "logs.ExecutionLog_parent::parent_proc_name"
"logs.ExecutionLog::proc_schema_name" <-- "logs.ExecutionLog_gross::proc_schema_name"
"logs.ExecutionLog::proc_schema_name" <-- "logs.ExecutionLog_parent::parent_proc_schema_name"
"logs.ExecutionLog::source_object" <-- "logs.ExecutionLog_gross::source_object"
"logs.ExecutionLog::ssis_execution_id" <-- "logs.ExecutionLog_gross::ssis_execution_id"
"logs.ExecutionLog::step_id" <-- "logs.ExecutionLog_gross::step_id"
"logs.ExecutionLog::step_id" <-- "logs.ExecutionLog_parent::parent_step_id"
"logs.ExecutionLog::step_name" <-- "logs.ExecutionLog_gross::step_name"
"logs.ExecutionLog::step_name" <-- "logs.ExecutionLog_parent::parent_step_name"
"logs.ExecutionLog::sub_execution_id" <-- "logs.ExecutionLog_gross::sub_execution_id"
"logs.ExecutionLog::target_object" <-- "logs.ExecutionLog_gross::target_object"
"logs.ExecutionLog::updated" <-- "logs.ExecutionLog_gross::updated"

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_colref[]


== sql_modules_definition

// tag::sql_modules_definition[]
[%collapsible]
=======
[source,sql,numbered,indent=0]
----

----
=======
// end::sql_modules_definition[]


