// tag::HeaderFullDisplayName[]
= logs.ftv_ExecutionLog_puml_tree - IF
// end::HeaderFullDisplayName[]

== existing_properties

// tag::existing_properties[]

:ExistsProperty--antorareferencedlist:
:ExistsProperty--antorareferencinglist:
:ExistsProperty--description:
:ExistsProperty--exampleusage:
:ExistsProperty--is_repo_managed:
:ExistsProperty--is_ssas:
:ExistsProperty--referencedobjectlist:
:ExistsProperty--sql_modules_definition:
:ExistsProperty--AntoraParameterList:
:ExistsProperty--Columns:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
FBAFBA8C-AD72-EB11-84E3-A81E8446D5B0
// end::RepoObject_guid[]

== RepoObject_FullDisplayName2

// tag::RepoObject_FullDisplayName2[]
logs.ftv_ExecutionLog_puml_tree
// end::RepoObject_FullDisplayName2[]

== SysObject_type

// tag::SysObject_type[]
IF
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
inline function
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
1255675521
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2021-10-02 13:23:34
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]
[discrete]
== _


[#column-depth]
=== Depth

[cols="d,8a,m,m,m"]
|===
|
|Depth
|int
|NULL
|
|===


[#column-durationunderlinecurrentunderlineexecutionunderlineguid]
=== duration_current_execution_guid

[cols="d,8a,m,m,m"]
|===
|
|duration_current_execution_guid
|int
|NULL
|
|===


[#column-executionunderlineinstanceunderlineguid]
=== execution_instance_guid

[cols="d,8a,m,m,m"]
|===
|
|execution_instance_guid
|uniqueidentifier
|NULL
|
|===


[#column-id]
=== id

[cols="d,8a,m,m,m"]
|===
|
|id
|bigint
|NULL
|
|===


[#column-parentunderlineexecutionunderlinelogunderlineid]
=== parent_execution_log_id

[cols="d,8a,m,m,m"]
|===
|
|parent_execution_log_id
|bigint
|NULL
|
|===


[#column-plantumltree]
=== PlantUmlTree

[cols="d,8a,m,m,m"]
|===
|
|PlantUmlTree
|nvarchar(4000)
|NOT NULL
|
|===


[#column-plantumltreetable]
=== PlantUmlTreeTable

[cols="d,8a,m,m,m"]
|===
|
|PlantUmlTreeTable
|nvarchar(4000)
|NOT NULL
|
|===


[#column-procunderlinename]
=== proc_name

[cols="d,8a,m,m,m"]
|===
|
|proc_name
|nvarchar(128)
|NULL
|
|===


[#column-procunderlineschemaunderlinename]
=== proc_schema_name

[cols="d,8a,m,m,m"]
|===
|
|proc_schema_name
|nvarchar(128)
|NULL
|
|===


[#column-stepunderlineid]
=== step_id

[cols="d,8a,m,m,m"]
|===
|
|step_id
|int
|NULL
|
|===


// end::AntoraColumnDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]










// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]
|
|<<column-depth>>
|int
|NULL
|

|
|<<column-durationunderlinecurrentunderlineexecutionunderlineguid>>
|int
|NULL
|

|
|<<column-executionunderlineinstanceunderlineguid>>
|uniqueidentifier
|NULL
|

|
|<<column-id>>
|bigint
|NULL
|

|
|<<column-parentunderlineexecutionunderlinelogunderlineid>>
|bigint
|NULL
|

|
|<<column-plantumltree>>
|nvarchar(4000)
|NOT NULL
|

|
|<<column-plantumltreetable>>
|nvarchar(4000)
|NOT NULL
|

|
|<<column-procunderlinename>>
|nvarchar(128)
|NULL
|

|
|<<column-procunderlineschemaunderlinename>>
|nvarchar(128)
|NULL
|

|
|<<column-stepunderlineid>>
|int
|NULL
|

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

// end::AntoraIndexList[]

== AntoraMeasureDetails

// tag::AntoraMeasureDetails[]

// end::AntoraMeasureDetails[]

== AntoraMeasureDescriptions



== AntoraParameterList

// tag::AntoraParameterList[]
* @execution_instance_guid (uniqueidentifier)
* @parent_execution_log_id (int)
// end::AntoraParameterList[]

== AntoraXrefCulturesList

// tag::AntoraXrefCulturesList[]
* xref:dhw:sqldb:logs.ftv_executionlog_puml_tree.adoc[] - 
// end::AntoraXrefCulturesList[]

== cultures_count

// tag::cultures_count[]
1
// end::cultures_count[]

== Other tags

source: property.RepoObjectProperty_cross As rop_cross


=== additional_reference_csv

// tag::additional_reference_csv[]

// end::additional_reference_csv[]


=== AdocUspSteps

// tag::adocuspsteps[]

// end::adocuspsteps[]


=== AntoraReferencedList

// tag::antorareferencedlist[]
* xref:dhw:sqldb:logs.executionlog_gross.adoc[]
// end::antorareferencedlist[]


=== AntoraReferencingList

// tag::antorareferencinglist[]
* xref:dhw:sqldb:logs.ftv_executionlog_puml_tree_per_execution.adoc[]
// end::antorareferencinglist[]


=== Description

// tag::description[]

* xref:sqldb:logs.ftv_executionlog_puml_tree.adoc[] uses xref:sqldb:logs.executionlog.adoc[] to create PlantUML code for procedure execution
* Only procedure calls are considered, not "normal code".
** PlantUmlTree
+
[code,plantuml]
------
@startsalt
{
{T
'Procedure  <1>
+ [repo].[usp_main]
++ [repo].[usp_sync_guid]
+++ [repo].[usp_sync_guid_RepoSchema]
+++ [repo].[usp_sync_guid_RepoObject]
++++ [graph].[usp_PERSIST_RepoObject]
+++ [repo].[usp_sync_guid_RepoObjectColumn]
++++ [graph].[usp_PERSIST_RepoObjectColumn]
++ [reference].[usp_update_Referencing_Count]
++ [repo].[usp_index_inheritance]
+++ [repo].[usp_PERSIST_IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T]
+++ [repo].[usp_Index_finish]
++++ [repo].[usp_Index_Settings]
++++ [graph].[usp_PERSIST_Index]
++ [repo].[usp_Index_ForeignKey]
+++ [repo].[usp_PERSIST_ForeignKey_Indexes_union_T]
+++ [repo].[usp_Index_finish]
++++ [repo].[usp_Index_Settings]
++++ [graph].[usp_PERSIST_Index]
++ [repo].[usp_RepoObjectColumn_update_RepoObjectColumn_column_id]
++ [uspgenerator].[usp_GeneratorUsp_insert_update_persistence]
++ [property].[usp_RepoObject_Inheritance]
++ [property].[usp_RepoObjectColumn_Inheritance]
} <1>
}
@endsalt
------
<1> you need to add header and footer around the generated code, which contains only the lines starting with '+' 
** PlantUmlTreeTable
+
[code,plantuml]
------
@startsalt
{
{T
Procedure  |  Duration <1>
+ [repo].[usp_main]  |  243
++ [repo].[usp_sync_guid]  |  12
+++ [repo].[usp_sync_guid_RepoSchema]  |  0
+++ [repo].[usp_sync_guid_RepoObject]  |  3
++++ [graph].[usp_PERSIST_RepoObject]  |  0
+++ [repo].[usp_sync_guid_RepoObjectColumn]  |  4
++++ [graph].[usp_PERSIST_RepoObjectColumn]  |  0
++ [reference].[usp_update_Referencing_Count]  |  13
++ [repo].[usp_index_inheritance]  |  31
+++ [repo].[usp_PERSIST_IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T]  |  12
+++ [repo].[usp_Index_finish]  |  8
++++ [repo].[usp_Index_Settings]  |  1
++++ [graph].[usp_PERSIST_Index]  |  0
++ [repo].[usp_Index_ForeignKey]  |  9
+++ [repo].[usp_PERSIST_ForeignKey_Indexes_union_T]  |  1
+++ [repo].[usp_Index_finish]  |  1
++++ [repo].[usp_Index_Settings]  |  1
++++ [graph].[usp_PERSIST_Index]  |  0
++ [repo].[usp_RepoObjectColumn_update_RepoObjectColumn_column_id]  |  1
++ [uspgenerator].[usp_GeneratorUsp_insert_update_persistence]  |  53
++ [property].[usp_RepoObject_Inheritance]  |  3
++ [property].[usp_RepoObjectColumn_Inheritance]  |  30
} <1>
}
@endsalt
------
<1> you need to add header and footer around the generated code, which contains only the lines starting with '+' 

results:

[plantuml, dhw-treeTable-ExecutionLog-usp_main, svg]
....
@startsalt
{
{T
Procedure  |  Duration <1>
+ [repo].[usp_main]  |  243
++ [repo].[usp_sync_guid]  |  12
+++ [repo].[usp_sync_guid_RepoSchema]  |  0
+++ [repo].[usp_sync_guid_RepoObject]  |  3
++++ [graph].[usp_PERSIST_RepoObject]  |  0
+++ [repo].[usp_sync_guid_RepoObjectColumn]  |  4
++++ [graph].[usp_PERSIST_RepoObjectColumn]  |  0
++ [reference].[usp_update_Referencing_Count]  |  13
++ [repo].[usp_index_inheritance]  |  31
+++ [repo].[usp_PERSIST_IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T]  |  12
+++ [repo].[usp_Index_finish]  |  8
++++ [repo].[usp_Index_Settings]  |  1
++++ [graph].[usp_PERSIST_Index]  |  0
++ [repo].[usp_Index_ForeignKey]  |  9
+++ [repo].[usp_PERSIST_ForeignKey_Indexes_union_T]  |  1
+++ [repo].[usp_Index_finish]  |  1
++++ [repo].[usp_Index_Settings]  |  1
++++ [graph].[usp_PERSIST_Index]  |  0
++ [repo].[usp_RepoObjectColumn_update_RepoObjectColumn_column_id]  |  1
++ [uspgenerator].[usp_GeneratorUsp_insert_update_persistence]  |  53
++ [property].[usp_RepoObject_Inheritance]  |  3
++ [property].[usp_RepoObjectColumn_Inheritance]  |  30
}
}
@endsalt
....
// end::description[]


=== exampleUsage

// tag::exampleusage[]

--get all puml for all executions

Select
    execution_instance_guid
  , id
  , parent_execution_log_id
  , Depth
  , proc_schema_name
  , proc_name
  , step_id
  , duration__current_execution_guid
  , PlantUmlTree
  , PlantUmlTreeTable
From
    logs.ftv_ExecutionLog_puml_tree ( Default, Default )
Order By
    id;

--get the puml for a specific execution

Select
    *
From
    logs.ftv_ExecutionLog_puml_tree ( '069F29D0-829E-4D2B-BAE9-9D032DA1FF22', Default )
Order By
    id;
// end::exampleusage[]


=== exampleUsage_2

// tag::exampleusage_2[]

// end::exampleusage_2[]


=== exampleUsage_3

// tag::exampleusage_3[]

// end::exampleusage_3[]


=== exampleUsage_4

// tag::exampleusage_4[]

// end::exampleusage_4[]


=== exampleUsage_5

// tag::exampleusage_5[]

// end::exampleusage_5[]


=== exampleWrong_Usage

// tag::examplewrong_usage[]

// end::examplewrong_usage[]


=== has_execution_plan_issue

// tag::has_execution_plan_issue[]

// end::has_execution_plan_issue[]


=== has_get_referenced_issue

// tag::has_get_referenced_issue[]

// end::has_get_referenced_issue[]


=== has_history

// tag::has_history[]

// end::has_history[]


=== has_history_columns

// tag::has_history_columns[]

// end::has_history_columns[]


=== InheritanceType

// tag::inheritancetype[]

// end::inheritancetype[]


=== is_persistence

// tag::is_persistence[]

// end::is_persistence[]


=== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]

// end::is_persistence_check_duplicate_per_pk[]


=== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]

// end::is_persistence_check_for_empty_source[]


=== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]

// end::is_persistence_delete_changed[]


=== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]

// end::is_persistence_delete_missing[]


=== is_persistence_insert

// tag::is_persistence_insert[]

// end::is_persistence_insert[]


=== is_persistence_truncate

// tag::is_persistence_truncate[]

// end::is_persistence_truncate[]


=== is_persistence_update_changed

// tag::is_persistence_update_changed[]

// end::is_persistence_update_changed[]


=== is_repo_managed

// tag::is_repo_managed[]
0
// end::is_repo_managed[]


=== is_ssas

// tag::is_ssas[]
0
// end::is_ssas[]


=== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


=== MS_Description

// tag::ms_description[]

// end::ms_description[]


=== persistence_source_RepoObject_fullname

// tag::persistence_source_repoobject_fullname[]

// end::persistence_source_repoobject_fullname[]


=== persistence_source_RepoObject_fullname2

// tag::persistence_source_repoobject_fullname2[]

// end::persistence_source_repoobject_fullname2[]


=== persistence_source_RepoObject_guid

// tag::persistence_source_repoobject_guid[]

// end::persistence_source_repoobject_guid[]


=== persistence_source_RepoObject_xref

// tag::persistence_source_repoobject_xref[]

// end::persistence_source_repoobject_xref[]


=== pk_index_guid

// tag::pk_index_guid[]

// end::pk_index_guid[]


=== pk_IndexPatternColumnDatatype

// tag::pk_indexpatterncolumndatatype[]

// end::pk_indexpatterncolumndatatype[]


=== pk_IndexPatternColumnName

// tag::pk_indexpatterncolumnname[]

// end::pk_indexpatterncolumnname[]


=== pk_IndexSemanticGroup

// tag::pk_indexsemanticgroup[]

// end::pk_indexsemanticgroup[]


=== ReferencedObjectList

// tag::referencedobjectlist[]
* [logs].[ExecutionLog_gross]
// end::referencedobjectlist[]


=== usp_persistence_RepoObject_guid

// tag::usp_persistence_repoobject_guid[]

// end::usp_persistence_repoobject_guid[]


=== UspExamples

// tag::uspexamples[]

// end::uspexamples[]


=== uspgenerator_usp_id

// tag::uspgenerator_usp_id[]

// end::uspgenerator_usp_id[]


=== UspParameters

// tag::uspparameters[]

// end::uspparameters[]

== Boolean Attributes

source: property.RepoObjectProperty WHERE property_int = 1

// tag::boolean_attributes[]


// end::boolean_attributes[]

== PlantUML diagrams

=== PlantUML Entity

// tag::puml_entity[]
[plantuml, entity-{docname}, svg, subs=macros]
....
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:logs.ftv_executionlog_puml_tree.adoc[]" as logs.ftv_ExecutionLog_puml_tree << IF >> {
  Depth : (int)
  duration_current_execution_guid : (int)
  execution_instance_guid : (uniqueidentifier)
  id : (bigint)
  parent_execution_log_id : (bigint)
  - PlantUmlTree : (nvarchar(4000))
  - PlantUmlTreeTable : (nvarchar(4000))
  proc_name : (nvarchar(128))
  proc_schema_name : (nvarchar(128))
  step_id : (int)
  --
}
....

// end::puml_entity[]

=== PlantUML Entity 1 1 FK

// tag::puml_entity_1_1_fk[]
[plantuml, entity_1_1_fk-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}





footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_fk[]

=== PlantUML 1 1 ObjectRef

// tag::puml_entity_1_1_objectref[]
[plantuml, entity_1_1_objectref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:logs.executionlog_gross.adoc[]" as logs.ExecutionLog_gross << V >> {
  --
}

entity "puml-link:dhw:sqldb:logs.ftv_executionlog_puml_tree.adoc[]" as logs.ftv_ExecutionLog_puml_tree << IF >> {
  --
}

entity "puml-link:dhw:sqldb:logs.ftv_executionlog_puml_tree_per_execution.adoc[]" as logs.ftv_ExecutionLog_puml_tree_per_execution << IF >> {
  --
}

logs.ExecutionLog_gross <.. logs.ftv_ExecutionLog_puml_tree
logs.ftv_ExecutionLog_puml_tree <.. logs.ftv_ExecutionLog_puml_tree_per_execution

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_objectref[]

=== PlantUML 30 0 ObjectRef

// tag::puml_entity_30_0_objectref[]
[plantuml, entity_30_0_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:logs.executionlog.adoc[]" as logs.ExecutionLog << U >> {
  - **id** : (bigint)
  --
}

entity "puml-link:dhw:sqldb:logs.executionlog_gross.adoc[]" as logs.ExecutionLog_gross << V >> {
  --
}

entity "puml-link:dhw:sqldb:logs.ftv_executionlog_puml_tree.adoc[]" as logs.ftv_ExecutionLog_puml_tree << IF >> {
  --
}

logs.ExecutionLog <.. logs.ExecutionLog_gross
logs.ExecutionLog_gross <.. logs.ftv_ExecutionLog_puml_tree

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_30_0_objectref[]

=== PlantUML 0 30 ObjectRef

// tag::puml_entity_0_30_objectref[]
[plantuml, entity_0_30_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:logs.ftv_executionlog_puml_tree.adoc[]" as logs.ftv_ExecutionLog_puml_tree << IF >> {
  --
}

entity "puml-link:dhw:sqldb:logs.ftv_executionlog_puml_tree_per_execution.adoc[]" as logs.ftv_ExecutionLog_puml_tree_per_execution << IF >> {
  --
}

logs.ftv_ExecutionLog_puml_tree <.. logs.ftv_ExecutionLog_puml_tree_per_execution

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_0_30_objectref[]

=== PlantUML 1 1 ColumnRef

// tag::puml_entity_1_1_colref[]
[plantuml, entity_1_1_colref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:logs.executionlog_gross.adoc[]" as logs.ExecutionLog_gross << V >> {
  created_dt : (datetime)
  created_dt_max_execution_instance_guid : (datetime)
  created_dt_min_execution_instance_guid : (datetime)
  current_execution_guid : (uniqueidentifier)
  deleted : (int)
  duration_current_execution_guid : (int)
  duration_execution_instance_guid : (int)
  duration_step : (int)
  event_info : (nvarchar(max))
  - execution_instance_guid : (uniqueidentifier)
  - id : (bigint)
  info_01 : (nvarchar(4000))
  info_02 : (nvarchar(4000))
  info_03 : (nvarchar(4000))
  info_04 : (nvarchar(4000))
  info_05 : (nvarchar(4000))
  info_06 : (nvarchar(4000))
  info_07 : (nvarchar(4000))
  info_08 : (nvarchar(4000))
  info_09 : (nvarchar(4000))
  inserted : (int)
  parameter_01 : (nvarchar(4000))
  parameter_02 : (nvarchar(4000))
  parameter_03 : (nvarchar(4000))
  parameter_04 : (nvarchar(4000))
  parameter_05 : (nvarchar(4000))
  parameter_06 : (nvarchar(4000))
  parameter_07 : (nvarchar(4000))
  parameter_08 : (nvarchar(4000))
  parameter_09 : (nvarchar(4000))
  parameter_10 : (nvarchar(4000))
  parameter_11 : (nvarchar(4000))
  parameter_12 : (nvarchar(4000))
  parameter_13 : (nvarchar(4000))
  parameter_14 : (nvarchar(4000))
  parameter_15 : (nvarchar(4000))
  parameter_16 : (nvarchar(4000))
  parameter_17 : (nvarchar(4000))
  parameter_18 : (nvarchar(4000))
  parameter_19 : (nvarchar(4000))
  parameter_20 : (nvarchar(4000))
  parent_execution_log_id : (bigint)
  proc_id : (int)
  proc_name : (nvarchar(128))
  proc_schema_name : (nvarchar(128))
  - puml_Sequence : (nvarchar(1550))
  source_object : (nvarchar(261))
  ssis_execution_id : (bigint)
  step_id : (int)
  step_name : (nvarchar(1000))
  sub_execution_id : (int)
  target_object : (nvarchar(261))
  updated : (int)
  --
}

entity "puml-link:dhw:sqldb:logs.ftv_executionlog_puml_tree.adoc[]" as logs.ftv_ExecutionLog_puml_tree << IF >> {
  Depth : (int)
  duration_current_execution_guid : (int)
  execution_instance_guid : (uniqueidentifier)
  id : (bigint)
  parent_execution_log_id : (bigint)
  - PlantUmlTree : (nvarchar(4000))
  - PlantUmlTreeTable : (nvarchar(4000))
  proc_name : (nvarchar(128))
  proc_schema_name : (nvarchar(128))
  step_id : (int)
  --
}

entity "puml-link:dhw:sqldb:logs.ftv_executionlog_puml_tree_per_execution.adoc[]" as logs.ftv_ExecutionLog_puml_tree_per_execution << IF >> {
  - ProcedurePumlTree : (nvarchar(max))
  - ProcedurePumlTreeTable : (nvarchar(max))
  --
}

logs.ExecutionLog_gross <.. logs.ftv_ExecutionLog_puml_tree
logs.ftv_ExecutionLog_puml_tree <.. logs.ftv_ExecutionLog_puml_tree_per_execution


footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_colref[]


== sql_modules_definition

// tag::sql_modules_definition[]
[%collapsible]
=======
[source,sql,numbered,indent=0]
----

/*
<<property_start>>Description 
* xref:sqldb:logs.ftv_executionlog_puml_tree.adoc[] uses xref:sqldb:logs.executionlog.adoc[] to create PlantUML code for procedure execution
* Only procedure calls are considered, not "normal code".
** PlantUmlTree
+
[code,plantuml]
------
@startsalt
{
{T
'Procedure  <1>
+ [repo].[usp_main]
++ [repo].[usp_sync_guid]
+++ [repo].[usp_sync_guid_RepoSchema]
+++ [repo].[usp_sync_guid_RepoObject]
++++ [graph].[usp_PERSIST_RepoObject]
+++ [repo].[usp_sync_guid_RepoObjectColumn]
++++ [graph].[usp_PERSIST_RepoObjectColumn]
++ [reference].[usp_update_Referencing_Count]
++ [repo].[usp_index_inheritance]
+++ [repo].[usp_PERSIST_IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T]
+++ [repo].[usp_Index_finish]
++++ [repo].[usp_Index_Settings]
++++ [graph].[usp_PERSIST_Index]
++ [repo].[usp_Index_ForeignKey]
+++ [repo].[usp_PERSIST_ForeignKey_Indexes_union_T]
+++ [repo].[usp_Index_finish]
++++ [repo].[usp_Index_Settings]
++++ [graph].[usp_PERSIST_Index]
++ [repo].[usp_RepoObjectColumn_update_RepoObjectColumn_column_id]
++ [uspgenerator].[usp_GeneratorUsp_insert_update_persistence]
++ [property].[usp_RepoObject_Inheritance]
++ [property].[usp_RepoObjectColumn_Inheritance]
} <1>
}
@endsalt
------
<1> you need to add header and footer around the generated code, which contains only the lines starting with '+' 
** PlantUmlTreeTable
+
[code,plantuml]
------
@startsalt
{
{T
Procedure  |  Duration <1>
+ [repo].[usp_main]  |  243
++ [repo].[usp_sync_guid]  |  12
+++ [repo].[usp_sync_guid_RepoSchema]  |  0
+++ [repo].[usp_sync_guid_RepoObject]  |  3
++++ [graph].[usp_PERSIST_RepoObject]  |  0
+++ [repo].[usp_sync_guid_RepoObjectColumn]  |  4
++++ [graph].[usp_PERSIST_RepoObjectColumn]  |  0
++ [reference].[usp_update_Referencing_Count]  |  13
++ [repo].[usp_index_inheritance]  |  31
+++ [repo].[usp_PERSIST_IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T]  |  12
+++ [repo].[usp_Index_finish]  |  8
++++ [repo].[usp_Index_Settings]  |  1
++++ [graph].[usp_PERSIST_Index]  |  0
++ [repo].[usp_Index_ForeignKey]  |  9
+++ [repo].[usp_PERSIST_ForeignKey_Indexes_union_T]  |  1
+++ [repo].[usp_Index_finish]  |  1
++++ [repo].[usp_Index_Settings]  |  1
++++ [graph].[usp_PERSIST_Index]  |  0
++ [repo].[usp_RepoObjectColumn_update_RepoObjectColumn_column_id]  |  1
++ [uspgenerator].[usp_GeneratorUsp_insert_update_persistence]  |  53
++ [property].[usp_RepoObject_Inheritance]  |  3
++ [property].[usp_RepoObjectColumn_Inheritance]  |  30
} <1>
}
@endsalt
------
<1> you need to add header and footer around the generated code, which contains only the lines starting with '+' 

results:

[plantuml, dhw-treeTable-ExecutionLog-usp_main, svg]
....
@startsalt
{
{T
Procedure  |  Duration <1>
+ [repo].[usp_main]  |  243
++ [repo].[usp_sync_guid]  |  12
+++ [repo].[usp_sync_guid_RepoSchema]  |  0
+++ [repo].[usp_sync_guid_RepoObject]  |  3
++++ [graph].[usp_PERSIST_RepoObject]  |  0
+++ [repo].[usp_sync_guid_RepoObjectColumn]  |  4
++++ [graph].[usp_PERSIST_RepoObjectColumn]  |  0
++ [reference].[usp_update_Referencing_Count]  |  13
++ [repo].[usp_index_inheritance]  |  31
+++ [repo].[usp_PERSIST_IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T]  |  12
+++ [repo].[usp_Index_finish]  |  8
++++ [repo].[usp_Index_Settings]  |  1
++++ [graph].[usp_PERSIST_Index]  |  0
++ [repo].[usp_Index_ForeignKey]  |  9
+++ [repo].[usp_PERSIST_ForeignKey_Indexes_union_T]  |  1
+++ [repo].[usp_Index_finish]  |  1
++++ [repo].[usp_Index_Settings]  |  1
++++ [graph].[usp_PERSIST_Index]  |  0
++ [repo].[usp_RepoObjectColumn_update_RepoObjectColumn_column_id]  |  1
++ [uspgenerator].[usp_GeneratorUsp_insert_update_persistence]  |  53
++ [property].[usp_RepoObject_Inheritance]  |  3
++ [property].[usp_RepoObjectColumn_Inheritance]  |  30
}
}
@endsalt
....
<<property_end>> 

<<property_start>>exampleUsage 
--get all puml for all executions

Select
    execution_instance_guid
  , id
  , parent_execution_log_id
  , Depth
  , proc_schema_name
  , proc_name
  , step_id
  , duration__current_execution_guid
  , PlantUmlTree
  , PlantUmlTreeTable
From
    logs.ftv_ExecutionLog_puml_tree ( Default, Default )
Order By
    id;

--get the puml for a specific execution

Select
    *
From
    logs.ftv_ExecutionLog_puml_tree ( '069F29D0-829E-4D2B-BAE9-9D032DA1FF22', Default )
Order By
    id;
<<property_end>> 
*/
CREATE Function [logs].[ftv_ExecutionLog_puml_tree]
(
    @execution_instance_guid UniqueIdentifier = Null
  , @parent_execution_log_id Int              = Null
)
Returns Table
As
Return
(
    With
    tree
    As
        --tree is recursive to solve parent child hierarchies
        (
        Select
            execution_instance_guid
          , id
          , parent_execution_log_id
          , 1                               As Depth
          , proc_schema_name
          , proc_name
          , step_id
          , duration_current_execution_guid
        From
            logs.ExecutionLog_gross
        Where
            (
                id                      = @parent_execution_log_id
                Or @parent_execution_log_id Is Null
                   And parent_execution_log_id Is Null
            )
            And
            (
                execution_instance_guid = @execution_instance_guid
                Or @execution_instance_guid Is Null
            )
            And step_id                 = 1
        Union All
        Select
            child.execution_instance_guid
          , child.id
          , child.parent_execution_log_id
          , parent.Depth + 1
          , child.proc_schema_name
          , child.proc_name
          , child.step_id
          , child.duration_current_execution_guid
        From
            logs.ExecutionLog_gross As child
            Inner Join
                tree                As parent
                    On
                    child.parent_execution_log_id = parent.id
        Where
            --
            child.execution_instance_guid = parent.execution_instance_guid
            And child.step_id             = 1
        )
    Select
        *
      , PlantUmlTree      = Concat (
                                       Replicate ( '+', Depth )
                                     , ' '
                                     , QuoteName ( proc_schema_name )
                                     , '.'
                                     , QuoteName ( proc_name )
                                   )
      , PlantUmlTreeTable = Concat (
                                       Replicate ( '+', Depth )
                                     , ' '
                                     , QuoteName ( proc_schema_name )
                                     , '.'
                                     , QuoteName ( proc_name )
                                     , '  |  '
                                     , duration_current_execution_guid
                                   )
    From
        tree
);
----
=======
// end::sql_modules_definition[]


