// tag::HeaderFullDisplayName[]
= logs.ExecutionLog_gross - V
// end::HeaderFullDisplayName[]

== existing_properties

// tag::existing_properties[]

:ExistsProperty--antorareferencedlist:
:ExistsProperty--antorareferencinglist:
:ExistsProperty--exampleusage:
:ExistsProperty--is_repo_managed:
:ExistsProperty--is_ssas:
:ExistsProperty--referencedobjectlist:
:ExistsProperty--sql_modules_definition:
:ExistsProperty--FK:
:ExistsProperty--AntoraIndexList:
:ExistsProperty--Columns:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
BB90291C-9D61-EB11-84DC-A81E8446D5B0
// end::RepoObject_guid[]

== RepoObject_FullDisplayName2

// tag::RepoObject_FullDisplayName2[]
logs.ExecutionLog_gross
// end::RepoObject_FullDisplayName2[]

== SysObject_type

// tag::SysObject_type[]
V 
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
view
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
2069582411
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2022-06-30 17:01:04
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]
[discrete]
== _


[#column-createdunderlinedt]
=== created_dt

[cols="d,8a,m,m,m"]
|===
|
|created_dt
|datetime
|NULL
|
|===

.Referenced Columns
--
* xref:logs.executionlog.adoc#column-createdunderlinedt[+logs.ExecutionLog.created_dt+]
--


[#column-createdunderlinedtunderlinemaxunderlineexecutionunderlineinstanceunderlineguid]
=== created_dt_max_execution_instance_guid

[cols="d,8a,m,m,m"]
|===
|
|created_dt_max_execution_instance_guid
|datetime
|NULL
|
|===


[#column-createdunderlinedtunderlineminunderlineexecutionunderlineinstanceunderlineguid]
=== created_dt_min_execution_instance_guid

[cols="d,8a,m,m,m"]
|===
|
|created_dt_min_execution_instance_guid
|datetime
|NULL
|
|===


[#column-currentunderlineexecutionunderlineguid]
=== current_execution_guid

[cols="d,8a,m,m,m"]
|===
|
|current_execution_guid
|uniqueidentifier
|NULL
|
|===

.Referenced Columns
--
* xref:logs.executionlog.adoc#column-currentunderlineexecutionunderlineguid[+logs.ExecutionLog.current_execution_guid+]
--


[#column-deleted]
=== deleted

[cols="d,8a,m,m,m"]
|===
|
|deleted
|int
|NULL
|
|===

.Referenced Columns
--
* xref:logs.executionlog.adoc#column-deleted[+logs.ExecutionLog.deleted+]
--


[#column-durationunderlinecurrentunderlineexecutionunderlineguid]
=== duration_current_execution_guid

[cols="d,8a,m,m,m"]
|===
|
|duration_current_execution_guid
|int
|NULL
|
|===


[#column-durationunderlineexecutionunderlineinstanceunderlineguid]
=== duration_execution_instance_guid

[cols="d,8a,m,m,m"]
|===
|
|duration_execution_instance_guid
|int
|NULL
|
|===


[#column-durationunderlinestep]
=== duration_step

[cols="d,8a,m,m,m"]
|===
|
|duration_step
|int
|NULL
|
|===


[#column-eventunderlineinfo]
=== event_info

[cols="d,8a,m,m,m"]
|===
|
|event_info
|nvarchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:logs.executionlog.adoc#column-eventunderlineinfo[+logs.ExecutionLog.event_info+]
--


[#column-executionunderlineinstanceunderlineguid]
=== execution_instance_guid

[cols="d,8a,m,m,m"]
|===
|
|execution_instance_guid
|uniqueidentifier
|NOT NULL
|
|===

.Referenced Columns
--
* xref:logs.executionlog.adoc#column-executionunderlineinstanceunderlineguid[+logs.ExecutionLog.execution_instance_guid+]
--


[#column-id]
=== id

[cols="d,8a,m,m,m"]
|===
|
|id
|bigint
|NOT NULL
|
|===

.Referenced Columns
--
* xref:logs.executionlog.adoc#column-id[+logs.ExecutionLog.id+]
--


[#column-infounderline01]
=== info_01

[cols="d,8a,m,m,m"]
|===
|
|info_01
|nvarchar(4000)
|NULL
|
|===

.Referenced Columns
--
* xref:logs.executionlog.adoc#column-infounderline01[+logs.ExecutionLog.info_01+]
--


[#column-infounderline02]
=== info_02

[cols="d,8a,m,m,m"]
|===
|
|info_02
|nvarchar(4000)
|NULL
|
|===

.Referenced Columns
--
* xref:logs.executionlog.adoc#column-infounderline02[+logs.ExecutionLog.info_02+]
--


[#column-infounderline03]
=== info_03

[cols="d,8a,m,m,m"]
|===
|
|info_03
|nvarchar(4000)
|NULL
|
|===

.Referenced Columns
--
* xref:logs.executionlog.adoc#column-infounderline03[+logs.ExecutionLog.info_03+]
--


[#column-infounderline04]
=== info_04

[cols="d,8a,m,m,m"]
|===
|
|info_04
|nvarchar(4000)
|NULL
|
|===

.Referenced Columns
--
* xref:logs.executionlog.adoc#column-infounderline04[+logs.ExecutionLog.info_04+]
--


[#column-infounderline05]
=== info_05

[cols="d,8a,m,m,m"]
|===
|
|info_05
|nvarchar(4000)
|NULL
|
|===

.Referenced Columns
--
* xref:logs.executionlog.adoc#column-infounderline05[+logs.ExecutionLog.info_05+]
--


[#column-infounderline06]
=== info_06

[cols="d,8a,m,m,m"]
|===
|
|info_06
|nvarchar(4000)
|NULL
|
|===

.Referenced Columns
--
* xref:logs.executionlog.adoc#column-infounderline06[+logs.ExecutionLog.info_06+]
--


[#column-infounderline07]
=== info_07

[cols="d,8a,m,m,m"]
|===
|
|info_07
|nvarchar(4000)
|NULL
|
|===

.Referenced Columns
--
* xref:logs.executionlog.adoc#column-infounderline07[+logs.ExecutionLog.info_07+]
--


[#column-infounderline08]
=== info_08

[cols="d,8a,m,m,m"]
|===
|
|info_08
|nvarchar(4000)
|NULL
|
|===

.Referenced Columns
--
* xref:logs.executionlog.adoc#column-infounderline08[+logs.ExecutionLog.info_08+]
--


[#column-infounderline09]
=== info_09

[cols="d,8a,m,m,m"]
|===
|
|info_09
|nvarchar(4000)
|NULL
|
|===

.Referenced Columns
--
* xref:logs.executionlog.adoc#column-infounderline09[+logs.ExecutionLog.info_09+]
--


[#column-inserted]
=== inserted

[cols="d,8a,m,m,m"]
|===
|
|inserted
|int
|NULL
|
|===

.Referenced Columns
--
* xref:logs.executionlog.adoc#column-inserted[+logs.ExecutionLog.inserted+]
--


[#column-parameterunderline01]
=== parameter_01

[cols="d,8a,m,m,m"]
|===
|
|parameter_01
|nvarchar(4000)
|NULL
|
|===

.Referenced Columns
--
* xref:logs.executionlog.adoc#column-parameterunderline01[+logs.ExecutionLog.parameter_01+]
--


[#column-parameterunderline02]
=== parameter_02

[cols="d,8a,m,m,m"]
|===
|
|parameter_02
|nvarchar(4000)
|NULL
|
|===

.Referenced Columns
--
* xref:logs.executionlog.adoc#column-parameterunderline02[+logs.ExecutionLog.parameter_02+]
--


[#column-parameterunderline03]
=== parameter_03

[cols="d,8a,m,m,m"]
|===
|
|parameter_03
|nvarchar(4000)
|NULL
|
|===

.Referenced Columns
--
* xref:logs.executionlog.adoc#column-parameterunderline03[+logs.ExecutionLog.parameter_03+]
--


[#column-parameterunderline04]
=== parameter_04

[cols="d,8a,m,m,m"]
|===
|
|parameter_04
|nvarchar(4000)
|NULL
|
|===

.Referenced Columns
--
* xref:logs.executionlog.adoc#column-parameterunderline04[+logs.ExecutionLog.parameter_04+]
--


[#column-parameterunderline05]
=== parameter_05

[cols="d,8a,m,m,m"]
|===
|
|parameter_05
|nvarchar(4000)
|NULL
|
|===

.Referenced Columns
--
* xref:logs.executionlog.adoc#column-parameterunderline05[+logs.ExecutionLog.parameter_05+]
--


[#column-parameterunderline06]
=== parameter_06

[cols="d,8a,m,m,m"]
|===
|
|parameter_06
|nvarchar(4000)
|NULL
|
|===

.Referenced Columns
--
* xref:logs.executionlog.adoc#column-parameterunderline06[+logs.ExecutionLog.parameter_06+]
--


[#column-parameterunderline07]
=== parameter_07

[cols="d,8a,m,m,m"]
|===
|
|parameter_07
|nvarchar(4000)
|NULL
|
|===

.Referenced Columns
--
* xref:logs.executionlog.adoc#column-parameterunderline07[+logs.ExecutionLog.parameter_07+]
--


[#column-parameterunderline08]
=== parameter_08

[cols="d,8a,m,m,m"]
|===
|
|parameter_08
|nvarchar(4000)
|NULL
|
|===

.Referenced Columns
--
* xref:logs.executionlog.adoc#column-parameterunderline08[+logs.ExecutionLog.parameter_08+]
--


[#column-parameterunderline09]
=== parameter_09

[cols="d,8a,m,m,m"]
|===
|
|parameter_09
|nvarchar(4000)
|NULL
|
|===

.Referenced Columns
--
* xref:logs.executionlog.adoc#column-parameterunderline09[+logs.ExecutionLog.parameter_09+]
--


[#column-parameterunderline10]
=== parameter_10

[cols="d,8a,m,m,m"]
|===
|
|parameter_10
|nvarchar(4000)
|NULL
|
|===

.Referenced Columns
--
* xref:logs.executionlog.adoc#column-parameterunderline10[+logs.ExecutionLog.parameter_10+]
--


[#column-parameterunderline11]
=== parameter_11

[cols="d,8a,m,m,m"]
|===
|
|parameter_11
|nvarchar(4000)
|NULL
|
|===

.Referenced Columns
--
* xref:logs.executionlog.adoc#column-parameterunderline11[+logs.ExecutionLog.parameter_11+]
--


[#column-parameterunderline12]
=== parameter_12

[cols="d,8a,m,m,m"]
|===
|
|parameter_12
|nvarchar(4000)
|NULL
|
|===

.Referenced Columns
--
* xref:logs.executionlog.adoc#column-parameterunderline12[+logs.ExecutionLog.parameter_12+]
--


[#column-parameterunderline13]
=== parameter_13

[cols="d,8a,m,m,m"]
|===
|
|parameter_13
|nvarchar(4000)
|NULL
|
|===

.Referenced Columns
--
* xref:logs.executionlog.adoc#column-parameterunderline13[+logs.ExecutionLog.parameter_13+]
--


[#column-parameterunderline14]
=== parameter_14

[cols="d,8a,m,m,m"]
|===
|
|parameter_14
|nvarchar(4000)
|NULL
|
|===

.Referenced Columns
--
* xref:logs.executionlog.adoc#column-parameterunderline14[+logs.ExecutionLog.parameter_14+]
--


[#column-parameterunderline15]
=== parameter_15

[cols="d,8a,m,m,m"]
|===
|
|parameter_15
|nvarchar(4000)
|NULL
|
|===

.Referenced Columns
--
* xref:logs.executionlog.adoc#column-parameterunderline15[+logs.ExecutionLog.parameter_15+]
--


[#column-parameterunderline16]
=== parameter_16

[cols="d,8a,m,m,m"]
|===
|
|parameter_16
|nvarchar(4000)
|NULL
|
|===

.Referenced Columns
--
* xref:logs.executionlog.adoc#column-parameterunderline16[+logs.ExecutionLog.parameter_16+]
--


[#column-parameterunderline17]
=== parameter_17

[cols="d,8a,m,m,m"]
|===
|
|parameter_17
|nvarchar(4000)
|NULL
|
|===

.Referenced Columns
--
* xref:logs.executionlog.adoc#column-parameterunderline17[+logs.ExecutionLog.parameter_17+]
--


[#column-parameterunderline18]
=== parameter_18

[cols="d,8a,m,m,m"]
|===
|
|parameter_18
|nvarchar(4000)
|NULL
|
|===

.Referenced Columns
--
* xref:logs.executionlog.adoc#column-parameterunderline18[+logs.ExecutionLog.parameter_18+]
--


[#column-parameterunderline19]
=== parameter_19

[cols="d,8a,m,m,m"]
|===
|
|parameter_19
|nvarchar(4000)
|NULL
|
|===

.Referenced Columns
--
* xref:logs.executionlog.adoc#column-parameterunderline19[+logs.ExecutionLog.parameter_19+]
--


[#column-parameterunderline20]
=== parameter_20

[cols="d,8a,m,m,m"]
|===
|
|parameter_20
|nvarchar(4000)
|NULL
|
|===

.Referenced Columns
--
* xref:logs.executionlog.adoc#column-parameterunderline20[+logs.ExecutionLog.parameter_20+]
--


[#column-parentunderlineexecutionunderlinelogunderlineid]
=== parent_execution_log_id

[cols="d,8a,m,m,m"]
|===
|
|parent_execution_log_id
|bigint
|NULL
|
|===

.Referenced Columns
--
* xref:logs.executionlog.adoc#column-parentunderlineexecutionunderlinelogunderlineid[+logs.ExecutionLog.parent_execution_log_id+]
--


[#column-procunderlineid]
=== proc_id

[cols="d,8a,m,m,m"]
|===
|
|proc_id
|int
|NULL
|
|===

.Referenced Columns
--
* xref:logs.executionlog.adoc#column-procunderlineid[+logs.ExecutionLog.proc_id+]
--


[#column-procunderlinename]
=== proc_name

[cols="d,8a,m,m,m"]
|===
|
|proc_name
|nvarchar(128)
|NULL
|
|===

.Referenced Columns
--
* xref:logs.executionlog.adoc#column-procunderlinename[+logs.ExecutionLog.proc_name+]
--


[#column-procunderlineschemaunderlinename]
=== proc_schema_name

[cols="d,8a,m,m,m"]
|===
|
|proc_schema_name
|nvarchar(128)
|NULL
|
|===

.Referenced Columns
--
* xref:logs.executionlog.adoc#column-procunderlineschemaunderlinename[+logs.ExecutionLog.proc_schema_name+]
--


[#column-pumlunderlinesequence]
=== puml_Sequence

[cols="d,8a,m,m,m"]
|===
|
|puml_Sequence
|nvarchar(1550)
|NOT NULL
|
|===


[#column-sourceunderlineobject]
=== source_object

[cols="d,8a,m,m,m"]
|===
|
|source_object
|nvarchar(261)
|NULL
|
|===

.Referenced Columns
--
* xref:logs.executionlog.adoc#column-sourceunderlineobject[+logs.ExecutionLog.source_object+]
--


[#column-ssisunderlineexecutionunderlineid]
=== ssis_execution_id

[cols="d,8a,m,m,m"]
|===
|
|ssis_execution_id
|bigint
|NULL
|
|===

.Referenced Columns
--
* xref:logs.executionlog.adoc#column-ssisunderlineexecutionunderlineid[+logs.ExecutionLog.ssis_execution_id+]
--


[#column-stepunderlineid]
=== step_id

[cols="d,8a,m,m,m"]
|===
|
|step_id
|int
|NULL
|
|===

.Referenced Columns
--
* xref:logs.executionlog.adoc#column-stepunderlineid[+logs.ExecutionLog.step_id+]
--


[#column-stepunderlinename]
=== step_name

[cols="d,8a,m,m,m"]
|===
|
|step_name
|nvarchar(1000)
|NULL
|
|===

.Referenced Columns
--
* xref:logs.executionlog.adoc#column-stepunderlinename[+logs.ExecutionLog.step_name+]
--


[#column-subunderlineexecutionunderlineid]
=== sub_execution_id

[cols="d,8a,m,m,m"]
|===
|
|sub_execution_id
|int
|NULL
|
|===

.Referenced Columns
--
* xref:logs.executionlog.adoc#column-subunderlineexecutionunderlineid[+logs.ExecutionLog.sub_execution_id+]
--


[#column-targetunderlineobject]
=== target_object

[cols="d,8a,m,m,m"]
|===
|
|target_object
|nvarchar(261)
|NULL
|
|===

.Referenced Columns
--
* xref:logs.executionlog.adoc#column-targetunderlineobject[+logs.ExecutionLog.target_object+]
--


[#column-updated]
=== updated

[cols="d,8a,m,m,m"]
|===
|
|updated
|int
|NULL
|
|===

.Referenced Columns
--
* xref:logs.executionlog.adoc#column-updated[+logs.ExecutionLog.updated+]
--


// end::AntoraColumnDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]





















































// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]
|
|<<column-createdunderlinedt>>
|datetime
|NULL
|

|
|<<column-createdunderlinedtunderlinemaxunderlineexecutionunderlineinstanceunderlineguid>>
|datetime
|NULL
|

|
|<<column-createdunderlinedtunderlineminunderlineexecutionunderlineinstanceunderlineguid>>
|datetime
|NULL
|

|
|<<column-currentunderlineexecutionunderlineguid>>
|uniqueidentifier
|NULL
|

|
|<<column-deleted>>
|int
|NULL
|

|
|<<column-durationunderlinecurrentunderlineexecutionunderlineguid>>
|int
|NULL
|

|
|<<column-durationunderlineexecutionunderlineinstanceunderlineguid>>
|int
|NULL
|

|
|<<column-durationunderlinestep>>
|int
|NULL
|

|
|<<column-eventunderlineinfo>>
|nvarchar(max)
|NULL
|

|
|<<column-executionunderlineinstanceunderlineguid>>
|uniqueidentifier
|NOT NULL
|

|
|<<column-id>>
|bigint
|NOT NULL
|

|
|<<column-infounderline01>>
|nvarchar(4000)
|NULL
|

|
|<<column-infounderline02>>
|nvarchar(4000)
|NULL
|

|
|<<column-infounderline03>>
|nvarchar(4000)
|NULL
|

|
|<<column-infounderline04>>
|nvarchar(4000)
|NULL
|

|
|<<column-infounderline05>>
|nvarchar(4000)
|NULL
|

|
|<<column-infounderline06>>
|nvarchar(4000)
|NULL
|

|
|<<column-infounderline07>>
|nvarchar(4000)
|NULL
|

|
|<<column-infounderline08>>
|nvarchar(4000)
|NULL
|

|
|<<column-infounderline09>>
|nvarchar(4000)
|NULL
|

|
|<<column-inserted>>
|int
|NULL
|

|
|<<column-parameterunderline01>>
|nvarchar(4000)
|NULL
|

|
|<<column-parameterunderline02>>
|nvarchar(4000)
|NULL
|

|
|<<column-parameterunderline03>>
|nvarchar(4000)
|NULL
|

|
|<<column-parameterunderline04>>
|nvarchar(4000)
|NULL
|

|
|<<column-parameterunderline05>>
|nvarchar(4000)
|NULL
|

|
|<<column-parameterunderline06>>
|nvarchar(4000)
|NULL
|

|
|<<column-parameterunderline07>>
|nvarchar(4000)
|NULL
|

|
|<<column-parameterunderline08>>
|nvarchar(4000)
|NULL
|

|
|<<column-parameterunderline09>>
|nvarchar(4000)
|NULL
|

|
|<<column-parameterunderline10>>
|nvarchar(4000)
|NULL
|

|
|<<column-parameterunderline11>>
|nvarchar(4000)
|NULL
|

|
|<<column-parameterunderline12>>
|nvarchar(4000)
|NULL
|

|
|<<column-parameterunderline13>>
|nvarchar(4000)
|NULL
|

|
|<<column-parameterunderline14>>
|nvarchar(4000)
|NULL
|

|
|<<column-parameterunderline15>>
|nvarchar(4000)
|NULL
|

|
|<<column-parameterunderline16>>
|nvarchar(4000)
|NULL
|

|
|<<column-parameterunderline17>>
|nvarchar(4000)
|NULL
|

|
|<<column-parameterunderline18>>
|nvarchar(4000)
|NULL
|

|
|<<column-parameterunderline19>>
|nvarchar(4000)
|NULL
|

|
|<<column-parameterunderline20>>
|nvarchar(4000)
|NULL
|

|
|<<column-parentunderlineexecutionunderlinelogunderlineid>>
|bigint
|NULL
|

|
|<<column-procunderlineid>>
|int
|NULL
|

|
|<<column-procunderlinename>>
|nvarchar(128)
|NULL
|

|
|<<column-procunderlineschemaunderlinename>>
|nvarchar(128)
|NULL
|

|
|<<column-pumlunderlinesequence>>
|nvarchar(1550)
|NOT NULL
|

|
|<<column-sourceunderlineobject>>
|nvarchar(261)
|NULL
|

|
|<<column-ssisunderlineexecutionunderlineid>>
|bigint
|NULL
|

|
|<<column-stepunderlineid>>
|int
|NULL
|

|
|<<column-stepunderlinename>>
|nvarchar(1000)
|NULL
|

|
|<<column-subunderlineexecutionunderlineid>>
|int
|NULL
|

|
|<<column-targetunderlineobject>>
|nvarchar(261)
|NULL
|

|
|<<column-updated>>
|int
|NULL
|

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

[#index-idxunderlineexecutionlogunderlinegrossunderlineunderline1]
=== idx_ExecutionLog_gross++__++1

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-id>>; bigint
--
* PK, Unique, Real: 0, 0, 0

// end::AntoraIndexList[]

== AntoraMeasureDetails

// tag::AntoraMeasureDetails[]

// end::AntoraMeasureDetails[]

== AntoraMeasureDescriptions



== AntoraParameterList

// tag::AntoraParameterList[]

// end::AntoraParameterList[]

== AntoraXrefCulturesList

// tag::AntoraXrefCulturesList[]
* xref:dhw:sqldb:logs.executionlog_gross.adoc[] - 
// end::AntoraXrefCulturesList[]

== cultures_count

// tag::cultures_count[]
1
// end::cultures_count[]

== Other tags

source: property.RepoObjectProperty_cross As rop_cross


=== additional_reference_csv

// tag::additional_reference_csv[]

// end::additional_reference_csv[]


=== AdocUspSteps

// tag::adocuspsteps[]

// end::adocuspsteps[]


=== AntoraReferencedList

// tag::antorareferencedlist[]
* xref:dhw:sqldb:logs.executionlog.adoc[]
// end::antorareferencedlist[]


=== AntoraReferencingList

// tag::antorareferencinglist[]
* xref:dhw:sqldb:logs.ftv_executionlog_puml_tree.adoc[]
// end::antorareferencinglist[]


=== Description

// tag::description[]

// end::description[]


=== exampleUsage

// tag::exampleusage[]

--get detailed PlantUML sequence diagram
--you could add skinparam to modify it, for example
--skinparam maxmessagesize 250

Select
    id
  , puml_Sequence
  , execution_instance_guid
  , parent_execution_log_id
  , proc_schema_name
  , proc_name
  , step_id
  , step_name
  , created_dt
  , source_object
  , target_object
  , inserted
  , updated
  , deleted
From
    logs.ExecutionLog_gross
Where
    id
Between 33386 And 33404
Order By
    id;
// end::exampleusage[]


=== exampleUsage_2

// tag::exampleusage_2[]

// end::exampleusage_2[]


=== exampleUsage_3

// tag::exampleusage_3[]

// end::exampleusage_3[]


=== exampleUsage_4

// tag::exampleusage_4[]

// end::exampleusage_4[]


=== exampleUsage_5

// tag::exampleusage_5[]

// end::exampleusage_5[]


=== exampleWrong_Usage

// tag::examplewrong_usage[]

// end::examplewrong_usage[]


=== has_execution_plan_issue

// tag::has_execution_plan_issue[]

// end::has_execution_plan_issue[]


=== has_get_referenced_issue

// tag::has_get_referenced_issue[]

// end::has_get_referenced_issue[]


=== has_history

// tag::has_history[]

// end::has_history[]


=== has_history_columns

// tag::has_history_columns[]

// end::has_history_columns[]


=== InheritanceType

// tag::inheritancetype[]

// end::inheritancetype[]


=== is_persistence

// tag::is_persistence[]

// end::is_persistence[]


=== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]

// end::is_persistence_check_duplicate_per_pk[]


=== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]

// end::is_persistence_check_for_empty_source[]


=== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]

// end::is_persistence_delete_changed[]


=== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]

// end::is_persistence_delete_missing[]


=== is_persistence_insert

// tag::is_persistence_insert[]

// end::is_persistence_insert[]


=== is_persistence_truncate

// tag::is_persistence_truncate[]

// end::is_persistence_truncate[]


=== is_persistence_update_changed

// tag::is_persistence_update_changed[]

// end::is_persistence_update_changed[]


=== is_repo_managed

// tag::is_repo_managed[]
0
// end::is_repo_managed[]


=== is_ssas

// tag::is_ssas[]
0
// end::is_ssas[]


=== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


=== MS_Description

// tag::ms_description[]

// end::ms_description[]


=== persistence_source_RepoObject_fullname

// tag::persistence_source_repoobject_fullname[]

// end::persistence_source_repoobject_fullname[]


=== persistence_source_RepoObject_fullname2

// tag::persistence_source_repoobject_fullname2[]

// end::persistence_source_repoobject_fullname2[]


=== persistence_source_RepoObject_guid

// tag::persistence_source_repoobject_guid[]

// end::persistence_source_repoobject_guid[]


=== persistence_source_RepoObject_xref

// tag::persistence_source_repoobject_xref[]

// end::persistence_source_repoobject_xref[]


=== pk_index_guid

// tag::pk_index_guid[]

// end::pk_index_guid[]


=== pk_IndexPatternColumnDatatype

// tag::pk_indexpatterncolumndatatype[]

// end::pk_indexpatterncolumndatatype[]


=== pk_IndexPatternColumnName

// tag::pk_indexpatterncolumnname[]

// end::pk_indexpatterncolumnname[]


=== pk_IndexSemanticGroup

// tag::pk_indexsemanticgroup[]

// end::pk_indexsemanticgroup[]


=== ReferencedObjectList

// tag::referencedobjectlist[]
* [logs].[ExecutionLog]
// end::referencedobjectlist[]


=== usp_persistence_RepoObject_guid

// tag::usp_persistence_repoobject_guid[]

// end::usp_persistence_repoobject_guid[]


=== UspExamples

// tag::uspexamples[]

// end::uspexamples[]


=== uspgenerator_usp_id

// tag::uspgenerator_usp_id[]

// end::uspgenerator_usp_id[]


=== UspParameters

// tag::uspparameters[]

// end::uspparameters[]

== Boolean Attributes

source: property.RepoObjectProperty WHERE property_int = 1

// tag::boolean_attributes[]


// end::boolean_attributes[]

== PlantUML diagrams

=== PlantUML Entity

// tag::puml_entity[]
[plantuml, entity-{docname}, svg, subs=macros]
....
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:logs.executionlog_gross.adoc[]" as logs.ExecutionLog_gross << V >> {
  created_dt : (datetime)
  created_dt_max_execution_instance_guid : (datetime)
  created_dt_min_execution_instance_guid : (datetime)
  current_execution_guid : (uniqueidentifier)
  deleted : (int)
  duration_current_execution_guid : (int)
  duration_execution_instance_guid : (int)
  duration_step : (int)
  event_info : (nvarchar(max))
  - execution_instance_guid : (uniqueidentifier)
  - id : (bigint)
  info_01 : (nvarchar(4000))
  info_02 : (nvarchar(4000))
  info_03 : (nvarchar(4000))
  info_04 : (nvarchar(4000))
  info_05 : (nvarchar(4000))
  info_06 : (nvarchar(4000))
  info_07 : (nvarchar(4000))
  info_08 : (nvarchar(4000))
  info_09 : (nvarchar(4000))
  inserted : (int)
  parameter_01 : (nvarchar(4000))
  parameter_02 : (nvarchar(4000))
  parameter_03 : (nvarchar(4000))
  parameter_04 : (nvarchar(4000))
  parameter_05 : (nvarchar(4000))
  parameter_06 : (nvarchar(4000))
  parameter_07 : (nvarchar(4000))
  parameter_08 : (nvarchar(4000))
  parameter_09 : (nvarchar(4000))
  parameter_10 : (nvarchar(4000))
  parameter_11 : (nvarchar(4000))
  parameter_12 : (nvarchar(4000))
  parameter_13 : (nvarchar(4000))
  parameter_14 : (nvarchar(4000))
  parameter_15 : (nvarchar(4000))
  parameter_16 : (nvarchar(4000))
  parameter_17 : (nvarchar(4000))
  parameter_18 : (nvarchar(4000))
  parameter_19 : (nvarchar(4000))
  parameter_20 : (nvarchar(4000))
  parent_execution_log_id : (bigint)
  proc_id : (int)
  proc_name : (nvarchar(128))
  proc_schema_name : (nvarchar(128))
  - puml_Sequence : (nvarchar(1550))
  source_object : (nvarchar(261))
  ssis_execution_id : (bigint)
  step_id : (int)
  step_name : (nvarchar(1000))
  sub_execution_id : (int)
  target_object : (nvarchar(261))
  updated : (int)
  --
}
....

// end::puml_entity[]

=== PlantUML Entity 1 1 FK

// tag::puml_entity_1_1_fk[]
[plantuml, entity_1_1_fk-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:logs.executionlog_gross.adoc[]" as logs.ExecutionLog_gross << V >> {
- idx_ExecutionLog_gross__1

..
id; bigint
}



footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_fk[]

=== PlantUML 1 1 ObjectRef

// tag::puml_entity_1_1_objectref[]
[plantuml, entity_1_1_objectref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:logs.executionlog.adoc[]" as logs.ExecutionLog << U >> {
  - **id** : (bigint)
  --
}

entity "puml-link:dhw:sqldb:logs.executionlog_gross.adoc[]" as logs.ExecutionLog_gross << V >> {
  --
}

entity "puml-link:dhw:sqldb:logs.ftv_executionlog_puml_tree.adoc[]" as logs.ftv_ExecutionLog_puml_tree << IF >> {
  --
}

logs.ExecutionLog <.. logs.ExecutionLog_gross
logs.ExecutionLog_gross <.. logs.ftv_ExecutionLog_puml_tree

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_objectref[]

=== PlantUML 30 0 ObjectRef

// tag::puml_entity_30_0_objectref[]
[plantuml, entity_30_0_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:logs.executionlog.adoc[]" as logs.ExecutionLog << U >> {
  - **id** : (bigint)
  --
}

entity "puml-link:dhw:sqldb:logs.executionlog_gross.adoc[]" as logs.ExecutionLog_gross << V >> {
  --
}

logs.ExecutionLog <.. logs.ExecutionLog_gross

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_30_0_objectref[]

=== PlantUML 0 30 ObjectRef

// tag::puml_entity_0_30_objectref[]
[plantuml, entity_0_30_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:logs.executionlog_gross.adoc[]" as logs.ExecutionLog_gross << V >> {
  --
}

entity "puml-link:dhw:sqldb:logs.ftv_executionlog_puml_tree.adoc[]" as logs.ftv_ExecutionLog_puml_tree << IF >> {
  --
}

entity "puml-link:dhw:sqldb:logs.ftv_executionlog_puml_tree_per_execution.adoc[]" as logs.ftv_ExecutionLog_puml_tree_per_execution << IF >> {
  --
}

logs.ExecutionLog_gross <.. logs.ftv_ExecutionLog_puml_tree
logs.ftv_ExecutionLog_puml_tree <.. logs.ftv_ExecutionLog_puml_tree_per_execution

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_0_30_objectref[]

=== PlantUML 1 1 ColumnRef

// tag::puml_entity_1_1_colref[]
[plantuml, entity_1_1_colref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:logs.executionlog.adoc[]" as logs.ExecutionLog << U >> {
  - **id** : (bigint)
  created_dt : (datetime)
  current_execution_guid : (uniqueidentifier)
  deleted : (int)
  event_info : (nvarchar(max))
  - execution_instance_guid : (uniqueidentifier)
  info_01 : (nvarchar(4000))
  info_02 : (nvarchar(4000))
  info_03 : (nvarchar(4000))
  info_04 : (nvarchar(4000))
  info_05 : (nvarchar(4000))
  info_06 : (nvarchar(4000))
  info_07 : (nvarchar(4000))
  info_08 : (nvarchar(4000))
  info_09 : (nvarchar(4000))
  inserted : (int)
  parameter_01 : (nvarchar(4000))
  parameter_02 : (nvarchar(4000))
  parameter_03 : (nvarchar(4000))
  parameter_04 : (nvarchar(4000))
  parameter_05 : (nvarchar(4000))
  parameter_06 : (nvarchar(4000))
  parameter_07 : (nvarchar(4000))
  parameter_08 : (nvarchar(4000))
  parameter_09 : (nvarchar(4000))
  parameter_10 : (nvarchar(4000))
  parameter_11 : (nvarchar(4000))
  parameter_12 : (nvarchar(4000))
  parameter_13 : (nvarchar(4000))
  parameter_14 : (nvarchar(4000))
  parameter_15 : (nvarchar(4000))
  parameter_16 : (nvarchar(4000))
  parameter_17 : (nvarchar(4000))
  parameter_18 : (nvarchar(4000))
  parameter_19 : (nvarchar(4000))
  parameter_20 : (nvarchar(4000))
  parent_execution_log_id : (bigint)
  proc_id : (int)
  proc_name : (nvarchar(128))
  proc_schema_name : (nvarchar(128))
  source_object : (nvarchar(261))
  ssis_execution_id : (bigint)
  step_id : (int)
  step_name : (nvarchar(1000))
  sub_execution_id : (int)
  target_object : (nvarchar(261))
  updated : (int)
  --
}

entity "puml-link:dhw:sqldb:logs.executionlog_gross.adoc[]" as logs.ExecutionLog_gross << V >> {
  created_dt : (datetime)
  created_dt_max_execution_instance_guid : (datetime)
  created_dt_min_execution_instance_guid : (datetime)
  current_execution_guid : (uniqueidentifier)
  deleted : (int)
  duration_current_execution_guid : (int)
  duration_execution_instance_guid : (int)
  duration_step : (int)
  event_info : (nvarchar(max))
  - execution_instance_guid : (uniqueidentifier)
  - id : (bigint)
  info_01 : (nvarchar(4000))
  info_02 : (nvarchar(4000))
  info_03 : (nvarchar(4000))
  info_04 : (nvarchar(4000))
  info_05 : (nvarchar(4000))
  info_06 : (nvarchar(4000))
  info_07 : (nvarchar(4000))
  info_08 : (nvarchar(4000))
  info_09 : (nvarchar(4000))
  inserted : (int)
  parameter_01 : (nvarchar(4000))
  parameter_02 : (nvarchar(4000))
  parameter_03 : (nvarchar(4000))
  parameter_04 : (nvarchar(4000))
  parameter_05 : (nvarchar(4000))
  parameter_06 : (nvarchar(4000))
  parameter_07 : (nvarchar(4000))
  parameter_08 : (nvarchar(4000))
  parameter_09 : (nvarchar(4000))
  parameter_10 : (nvarchar(4000))
  parameter_11 : (nvarchar(4000))
  parameter_12 : (nvarchar(4000))
  parameter_13 : (nvarchar(4000))
  parameter_14 : (nvarchar(4000))
  parameter_15 : (nvarchar(4000))
  parameter_16 : (nvarchar(4000))
  parameter_17 : (nvarchar(4000))
  parameter_18 : (nvarchar(4000))
  parameter_19 : (nvarchar(4000))
  parameter_20 : (nvarchar(4000))
  parent_execution_log_id : (bigint)
  proc_id : (int)
  proc_name : (nvarchar(128))
  proc_schema_name : (nvarchar(128))
  - puml_Sequence : (nvarchar(1550))
  source_object : (nvarchar(261))
  ssis_execution_id : (bigint)
  step_id : (int)
  step_name : (nvarchar(1000))
  sub_execution_id : (int)
  target_object : (nvarchar(261))
  updated : (int)
  --
}

entity "puml-link:dhw:sqldb:logs.ftv_executionlog_puml_tree.adoc[]" as logs.ftv_ExecutionLog_puml_tree << IF >> {
  Depth : (int)
  duration_current_execution_guid : (int)
  execution_instance_guid : (uniqueidentifier)
  id : (bigint)
  parent_execution_log_id : (bigint)
  - PlantUmlTree : (nvarchar(4000))
  - PlantUmlTreeTable : (nvarchar(4000))
  proc_name : (nvarchar(128))
  proc_schema_name : (nvarchar(128))
  step_id : (int)
  --
}

logs.ExecutionLog <.. logs.ExecutionLog_gross
logs.ExecutionLog_gross <.. logs.ftv_ExecutionLog_puml_tree
"logs.ExecutionLog::created_dt" <-- "logs.ExecutionLog_gross::created_dt"
"logs.ExecutionLog::current_execution_guid" <-- "logs.ExecutionLog_gross::current_execution_guid"
"logs.ExecutionLog::deleted" <-- "logs.ExecutionLog_gross::deleted"
"logs.ExecutionLog::event_info" <-- "logs.ExecutionLog_gross::event_info"
"logs.ExecutionLog::execution_instance_guid" <-- "logs.ExecutionLog_gross::execution_instance_guid"
"logs.ExecutionLog::id" <-- "logs.ExecutionLog_gross::id"
"logs.ExecutionLog::info_01" <-- "logs.ExecutionLog_gross::info_01"
"logs.ExecutionLog::info_02" <-- "logs.ExecutionLog_gross::info_02"
"logs.ExecutionLog::info_03" <-- "logs.ExecutionLog_gross::info_03"
"logs.ExecutionLog::info_04" <-- "logs.ExecutionLog_gross::info_04"
"logs.ExecutionLog::info_05" <-- "logs.ExecutionLog_gross::info_05"
"logs.ExecutionLog::info_06" <-- "logs.ExecutionLog_gross::info_06"
"logs.ExecutionLog::info_07" <-- "logs.ExecutionLog_gross::info_07"
"logs.ExecutionLog::info_08" <-- "logs.ExecutionLog_gross::info_08"
"logs.ExecutionLog::info_09" <-- "logs.ExecutionLog_gross::info_09"
"logs.ExecutionLog::inserted" <-- "logs.ExecutionLog_gross::inserted"
"logs.ExecutionLog::parameter_01" <-- "logs.ExecutionLog_gross::parameter_01"
"logs.ExecutionLog::parameter_02" <-- "logs.ExecutionLog_gross::parameter_02"
"logs.ExecutionLog::parameter_03" <-- "logs.ExecutionLog_gross::parameter_03"
"logs.ExecutionLog::parameter_04" <-- "logs.ExecutionLog_gross::parameter_04"
"logs.ExecutionLog::parameter_05" <-- "logs.ExecutionLog_gross::parameter_05"
"logs.ExecutionLog::parameter_06" <-- "logs.ExecutionLog_gross::parameter_06"
"logs.ExecutionLog::parameter_07" <-- "logs.ExecutionLog_gross::parameter_07"
"logs.ExecutionLog::parameter_08" <-- "logs.ExecutionLog_gross::parameter_08"
"logs.ExecutionLog::parameter_09" <-- "logs.ExecutionLog_gross::parameter_09"
"logs.ExecutionLog::parameter_10" <-- "logs.ExecutionLog_gross::parameter_10"
"logs.ExecutionLog::parameter_11" <-- "logs.ExecutionLog_gross::parameter_11"
"logs.ExecutionLog::parameter_12" <-- "logs.ExecutionLog_gross::parameter_12"
"logs.ExecutionLog::parameter_13" <-- "logs.ExecutionLog_gross::parameter_13"
"logs.ExecutionLog::parameter_14" <-- "logs.ExecutionLog_gross::parameter_14"
"logs.ExecutionLog::parameter_15" <-- "logs.ExecutionLog_gross::parameter_15"
"logs.ExecutionLog::parameter_16" <-- "logs.ExecutionLog_gross::parameter_16"
"logs.ExecutionLog::parameter_17" <-- "logs.ExecutionLog_gross::parameter_17"
"logs.ExecutionLog::parameter_18" <-- "logs.ExecutionLog_gross::parameter_18"
"logs.ExecutionLog::parameter_19" <-- "logs.ExecutionLog_gross::parameter_19"
"logs.ExecutionLog::parameter_20" <-- "logs.ExecutionLog_gross::parameter_20"
"logs.ExecutionLog::parent_execution_log_id" <-- "logs.ExecutionLog_gross::parent_execution_log_id"
"logs.ExecutionLog::proc_id" <-- "logs.ExecutionLog_gross::proc_id"
"logs.ExecutionLog::proc_name" <-- "logs.ExecutionLog_gross::proc_name"
"logs.ExecutionLog::proc_schema_name" <-- "logs.ExecutionLog_gross::proc_schema_name"
"logs.ExecutionLog::source_object" <-- "logs.ExecutionLog_gross::source_object"
"logs.ExecutionLog::ssis_execution_id" <-- "logs.ExecutionLog_gross::ssis_execution_id"
"logs.ExecutionLog::step_id" <-- "logs.ExecutionLog_gross::step_id"
"logs.ExecutionLog::step_name" <-- "logs.ExecutionLog_gross::step_name"
"logs.ExecutionLog::sub_execution_id" <-- "logs.ExecutionLog_gross::sub_execution_id"
"logs.ExecutionLog::target_object" <-- "logs.ExecutionLog_gross::target_object"
"logs.ExecutionLog::updated" <-- "logs.ExecutionLog_gross::updated"

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_colref[]


== sql_modules_definition

// tag::sql_modules_definition[]
[%collapsible]
=======
[source,sql,numbered,indent=0]
----



/*
<<property_start>>exampleUsage 
--get detailed PlantUML sequence diagram
--you could add skinparam to modify it, for example
--skinparam maxmessagesize 250

Select
    id
  , puml_Sequence
  , execution_instance_guid
  , parent_execution_log_id
  , proc_schema_name
  , proc_name
  , step_id
  , step_name
  , created_dt
  , source_object
  , target_object
  , inserted
  , updated
  , deleted
From
    logs.ExecutionLog_gross
Where
    id
Between 33386 And 33404
Order By
    id;
<<property_end>> 
*/
CREATE View [logs].[ExecutionLog_gross]
As
Select
    id
  , parent_execution_log_id
  , duration_current_execution_guid         = DateDiff (
                                                           ss
                                                         , Min ( created_dt ) Over ( Partition By current_execution_guid )
                                                         , Max ( created_dt ) Over ( Partition By current_execution_guid )
                                                       )
  , duration_execution_instance_guid        = DateDiff (
                                                           ss
                                                         , Min ( created_dt ) Over ( Partition By execution_instance_guid )
                                                         , Max ( created_dt ) Over ( Partition By execution_instance_guid )
                                                       )
  , duration_step                           = Iif(Not step_name In ( 'start', 'end' )
                        , DateDiff ( ss, Lag ( created_dt ) Over ( Order By id ), created_dt )
                        , Null)
  , created_dt
  , proc_schema_name
  , proc_name
  , step_id
  , step_name
  , inserted
  , updated
  , deleted
  , source_object
  , target_object
  , execution_instance_guid
  , ssis_execution_id
  , sub_execution_id
  , current_execution_guid
  , proc_id
  , info_01
  , info_02
  , info_03
  , info_04
  , info_05
  , info_06
  , info_07
  , info_08
  , info_09
  , event_info
  , parameter_01
  , parameter_02
  , parameter_03
  , parameter_04
  , parameter_05
  , parameter_06
  , parameter_07
  , parameter_08
  , parameter_09
  , parameter_10
  , parameter_11
  , parameter_12
  , parameter_13
  , parameter_14
  , parameter_15
  , parameter_16
  , parameter_17
  , parameter_18
  , parameter_19
  , parameter_20
  --
  , created_dt_min_execution_instance_guid = Min ( created_dt ) Over ( Partition By execution_instance_guid )
  , created_dt_max_execution_instance_guid = Max ( created_dt ) Over ( Partition By execution_instance_guid )
  --
  , puml_Sequence                           = --
  --combine the result with
  --skinparam maxmessagesize 250
  Case
      When source_object Is Null
           And target_object Is Null
          Then
          Concat (
                     Char ( 13 ) + Char ( 10 )
                   , '== '
                   , concat(quotename([proc_schema_name]),'.',quotename([proc_name])) --proc_fullname
                   , ' - '
                   , step_name
                   , ' =='
                   , Char ( 13 ) + Char ( 10 )
                   , Char ( 13 ) + Char ( 10 )
                 )
      Else
          Concat (
                     --
                     Case
                         When Not source_object Is Null
                             Then
                             QuoteName ( source_object, '"' )
                     End
                   , Case
                         When Not inserted Is Null
                             Then
                             Case
                                 When source_object Is Null
                                     Then
                                     '?-> '
                                 Else
                                     ' -> '
                             End
                         When Not updated Is Null
                             Then
                             Case
                                 When source_object Is Null
                                     Then
                                     '?->o '
                                 Else
                                     ' ->O '
                             End
                         When Not deleted Is Null
                             Then
                             Case
                                 When source_object Is Null
                                     Then
                                     '?->x '
                                 Else
                                     ' ->x '
                             End
                         Else
                             Case
                                 When source_object Is Null
                                     Then
                                     '?--> '
                                 Else
                                     ' --> '
                             End
                     End
                   , Case
                         When Not target_object Is Null
                             Then
                             QuoteName ( target_object, '"' )
                     End
                   --
                   --, ' : ' , QUOTENAME([step_name] , '"')
                   , ' : '
                   , step_name
                   , Char ( 13 ) + Char ( 10 )
                   -- "r" - rectangle note
                   , 'rnote right:'
                   , Coalesce ( inserted, updated, deleted )
                 --
                 )
  End
From
    logs.ExecutionLog

----
=======
// end::sql_modules_definition[]


