// tag::HeaderFullDisplayName[]
= logs.ExecutionLog_parent - V
// end::HeaderFullDisplayName[]

== existing_properties

// tag::existing_properties[]

:ExistsProperty--antorareferencedlist:
:ExistsProperty--antorareferencinglist:
:ExistsProperty--is_repo_managed:
:ExistsProperty--is_ssas:
:ExistsProperty--referencedobjectlist:
:ExistsProperty--sql_modules_definition:
:ExistsProperty--FK:
:ExistsProperty--AntoraIndexList:
:ExistsProperty--Columns:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
BD90291C-9D61-EB11-84DC-A81E8446D5B0
// end::RepoObject_guid[]

== RepoObject_FullDisplayName2

// tag::RepoObject_FullDisplayName2[]
logs.ExecutionLog_parent
// end::RepoObject_FullDisplayName2[]

== SysObject_type

// tag::SysObject_type[]
V 
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
view
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
2085582468
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2021-08-17 18:49:49
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]
[discrete]
== _


[#column-id]
=== id

[cols="d,8a,m,m,m"]
|===
|
|id
|bigint
|NOT NULL
|
|===

.Referenced Columns
--
* xref:logs.executionlog.adoc#column-id[+logs.ExecutionLog.id+]
--


[#column-parentunderlinecreatedunderlinedt]
=== parent_created_dt

[cols="d,8a,m,m,m"]
|===
|
|parent_created_dt
|datetime
|NULL
|
|===

.Referenced Columns
--
* xref:logs.executionlog.adoc#column-createdunderlinedt[+logs.ExecutionLog.created_dt+]
--


[#column-parentunderlinecurrentunderlineexecutionunderlineguid]
=== parent_current_execution_guid

[cols="d,8a,m,m,m"]
|===
|
|parent_current_execution_guid
|uniqueidentifier
|NULL
|
|===

.Referenced Columns
--
* xref:logs.executionlog.adoc#column-currentunderlineexecutionunderlineguid[+logs.ExecutionLog.current_execution_guid+]
--


[#column-parentunderlineexecutionunderlinelogunderlineid]
=== parent_execution_log_id

[cols="d,8a,m,m,m"]
|===
|
|parent_execution_log_id
|bigint
|NULL
|
|===

.Referenced Columns
--
* xref:logs.executionlog.adoc#column-parentunderlineexecutionunderlinelogunderlineid[+logs.ExecutionLog.parent_execution_log_id+]
--


[#column-parentunderlineparameterunderline01]
=== parent_parameter_01

[cols="d,8a,m,m,m"]
|===
|
|parent_parameter_01
|nvarchar(4000)
|NULL
|
|===

.Referenced Columns
--
* xref:logs.executionlog.adoc#column-parameterunderline01[+logs.ExecutionLog.parameter_01+]
--


[#column-parentunderlineparameterunderline02]
=== parent_parameter_02

[cols="d,8a,m,m,m"]
|===
|
|parent_parameter_02
|nvarchar(4000)
|NULL
|
|===

.Referenced Columns
--
* xref:logs.executionlog.adoc#column-parameterunderline02[+logs.ExecutionLog.parameter_02+]
--


[#column-parentunderlineparameterunderline03]
=== parent_parameter_03

[cols="d,8a,m,m,m"]
|===
|
|parent_parameter_03
|nvarchar(4000)
|NULL
|
|===

.Referenced Columns
--
* xref:logs.executionlog.adoc#column-parameterunderline03[+logs.ExecutionLog.parameter_03+]
--


[#column-parentunderlineparameterunderline04]
=== parent_parameter_04

[cols="d,8a,m,m,m"]
|===
|
|parent_parameter_04
|nvarchar(4000)
|NULL
|
|===

.Referenced Columns
--
* xref:logs.executionlog.adoc#column-parameterunderline04[+logs.ExecutionLog.parameter_04+]
--


[#column-parentunderlineparameterunderline05]
=== parent_parameter_05

[cols="d,8a,m,m,m"]
|===
|
|parent_parameter_05
|nvarchar(4000)
|NULL
|
|===

.Referenced Columns
--
* xref:logs.executionlog.adoc#column-parameterunderline05[+logs.ExecutionLog.parameter_05+]
--


[#column-parentunderlineparameterunderline06]
=== parent_parameter_06

[cols="d,8a,m,m,m"]
|===
|
|parent_parameter_06
|nvarchar(4000)
|NULL
|
|===

.Referenced Columns
--
* xref:logs.executionlog.adoc#column-parameterunderline06[+logs.ExecutionLog.parameter_06+]
--


[#column-parentunderlineparameterunderline07]
=== parent_parameter_07

[cols="d,8a,m,m,m"]
|===
|
|parent_parameter_07
|nvarchar(4000)
|NULL
|
|===

.Referenced Columns
--
* xref:logs.executionlog.adoc#column-parameterunderline07[+logs.ExecutionLog.parameter_07+]
--


[#column-parentunderlineparameterunderline08]
=== parent_parameter_08

[cols="d,8a,m,m,m"]
|===
|
|parent_parameter_08
|nvarchar(4000)
|NULL
|
|===

.Referenced Columns
--
* xref:logs.executionlog.adoc#column-parameterunderline08[+logs.ExecutionLog.parameter_08+]
--


[#column-parentunderlineparameterunderline09]
=== parent_parameter_09

[cols="d,8a,m,m,m"]
|===
|
|parent_parameter_09
|nvarchar(4000)
|NULL
|
|===

.Referenced Columns
--
* xref:logs.executionlog.adoc#column-parameterunderline09[+logs.ExecutionLog.parameter_09+]
--


[#column-parentunderlineparameterunderline10]
=== parent_parameter_10

[cols="d,8a,m,m,m"]
|===
|
|parent_parameter_10
|nvarchar(4000)
|NULL
|
|===

.Referenced Columns
--
* xref:logs.executionlog.adoc#column-parameterunderline10[+logs.ExecutionLog.parameter_10+]
--


[#column-parentunderlineparameterunderline11]
=== parent_parameter_11

[cols="d,8a,m,m,m"]
|===
|
|parent_parameter_11
|nvarchar(4000)
|NULL
|
|===

.Referenced Columns
--
* xref:logs.executionlog.adoc#column-parameterunderline11[+logs.ExecutionLog.parameter_11+]
--


[#column-parentunderlineparameterunderline12]
=== parent_parameter_12

[cols="d,8a,m,m,m"]
|===
|
|parent_parameter_12
|nvarchar(4000)
|NULL
|
|===

.Referenced Columns
--
* xref:logs.executionlog.adoc#column-parameterunderline12[+logs.ExecutionLog.parameter_12+]
--


[#column-parentunderlineparameterunderline13]
=== parent_parameter_13

[cols="d,8a,m,m,m"]
|===
|
|parent_parameter_13
|nvarchar(4000)
|NULL
|
|===

.Referenced Columns
--
* xref:logs.executionlog.adoc#column-parameterunderline13[+logs.ExecutionLog.parameter_13+]
--


[#column-parentunderlineparameterunderline14]
=== parent_parameter_14

[cols="d,8a,m,m,m"]
|===
|
|parent_parameter_14
|nvarchar(4000)
|NULL
|
|===

.Referenced Columns
--
* xref:logs.executionlog.adoc#column-parameterunderline14[+logs.ExecutionLog.parameter_14+]
--


[#column-parentunderlineparameterunderline15]
=== parent_parameter_15

[cols="d,8a,m,m,m"]
|===
|
|parent_parameter_15
|nvarchar(4000)
|NULL
|
|===

.Referenced Columns
--
* xref:logs.executionlog.adoc#column-parameterunderline15[+logs.ExecutionLog.parameter_15+]
--


[#column-parentunderlineparameterunderline16]
=== parent_parameter_16

[cols="d,8a,m,m,m"]
|===
|
|parent_parameter_16
|nvarchar(4000)
|NULL
|
|===

.Referenced Columns
--
* xref:logs.executionlog.adoc#column-parameterunderline16[+logs.ExecutionLog.parameter_16+]
--


[#column-parentunderlineparameterunderline17]
=== parent_parameter_17

[cols="d,8a,m,m,m"]
|===
|
|parent_parameter_17
|nvarchar(4000)
|NULL
|
|===

.Referenced Columns
--
* xref:logs.executionlog.adoc#column-parameterunderline17[+logs.ExecutionLog.parameter_17+]
--


[#column-parentunderlineparameterunderline18]
=== parent_parameter_18

[cols="d,8a,m,m,m"]
|===
|
|parent_parameter_18
|nvarchar(4000)
|NULL
|
|===

.Referenced Columns
--
* xref:logs.executionlog.adoc#column-parameterunderline18[+logs.ExecutionLog.parameter_18+]
--


[#column-parentunderlineparameterunderline19]
=== parent_parameter_19

[cols="d,8a,m,m,m"]
|===
|
|parent_parameter_19
|nvarchar(4000)
|NULL
|
|===

.Referenced Columns
--
* xref:logs.executionlog.adoc#column-parameterunderline19[+logs.ExecutionLog.parameter_19+]
--


[#column-parentunderlineparameterunderline20]
=== parent_parameter_20

[cols="d,8a,m,m,m"]
|===
|
|parent_parameter_20
|nvarchar(4000)
|NULL
|
|===

.Referenced Columns
--
* xref:logs.executionlog.adoc#column-parameterunderline20[+logs.ExecutionLog.parameter_20+]
--


[#column-parentunderlineprocunderlinefullname]
=== parent_proc_fullname

[cols="d,8a,m,m,m"]
|===
|
|parent_proc_fullname
|nvarchar(517)
|NULL
|
|===

.Description
--
(concat(quotename([proc_schema_name]),'.',quotename([proc_name])))
--
{empty} +

.Referenced Columns
--
* xref:logs.executionlog.adoc#column-procunderlinefullname[+logs.ExecutionLog.proc_fullname+]
--

.Referencing Columns
--
* xref:logs.executionlog_puml_sequence_start_stop.adoc#column-parentunderlineprocunderlinefullname[+logs.ExecutionLog_puml_Sequence_start_stop.parent_proc_fullname+]
--


[#column-parentunderlineprocunderlineid]
=== parent_proc_id

[cols="d,8a,m,m,m"]
|===
|
|parent_proc_id
|int
|NULL
|
|===

.Referenced Columns
--
* xref:logs.executionlog.adoc#column-procunderlineid[+logs.ExecutionLog.proc_id+]
--


[#column-parentunderlineprocunderlinename]
=== parent_proc_name

[cols="d,8a,m,m,m"]
|===
|
|parent_proc_name
|nvarchar(128)
|NULL
|
|===

.Referenced Columns
--
* xref:logs.executionlog.adoc#column-procunderlinename[+logs.ExecutionLog.proc_name+]
--


[#column-parentunderlineprocunderlineschemaunderlinename]
=== parent_proc_schema_name

[cols="d,8a,m,m,m"]
|===
|
|parent_proc_schema_name
|nvarchar(128)
|NULL
|
|===

.Referenced Columns
--
* xref:logs.executionlog.adoc#column-procunderlineschemaunderlinename[+logs.ExecutionLog.proc_schema_name+]
--


[#column-parentunderlinestepunderlineid]
=== parent_step_id

[cols="d,8a,m,m,m"]
|===
|
|parent_step_id
|int
|NULL
|
|===

.Referenced Columns
--
* xref:logs.executionlog.adoc#column-stepunderlineid[+logs.ExecutionLog.step_id+]
--


[#column-parentunderlinestepunderlinename]
=== parent_step_name

[cols="d,8a,m,m,m"]
|===
|
|parent_step_name
|nvarchar(1000)
|NULL
|
|===

.Referenced Columns
--
* xref:logs.executionlog.adoc#column-stepunderlinename[+logs.ExecutionLog.step_name+]
--


// end::AntoraColumnDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]






























// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]
|
|<<column-id>>
|bigint
|NOT NULL
|

|
|<<column-parentunderlinecreatedunderlinedt>>
|datetime
|NULL
|

|
|<<column-parentunderlinecurrentunderlineexecutionunderlineguid>>
|uniqueidentifier
|NULL
|

|
|<<column-parentunderlineexecutionunderlinelogunderlineid>>
|bigint
|NULL
|

|
|<<column-parentunderlineparameterunderline01>>
|nvarchar(4000)
|NULL
|

|
|<<column-parentunderlineparameterunderline02>>
|nvarchar(4000)
|NULL
|

|
|<<column-parentunderlineparameterunderline03>>
|nvarchar(4000)
|NULL
|

|
|<<column-parentunderlineparameterunderline04>>
|nvarchar(4000)
|NULL
|

|
|<<column-parentunderlineparameterunderline05>>
|nvarchar(4000)
|NULL
|

|
|<<column-parentunderlineparameterunderline06>>
|nvarchar(4000)
|NULL
|

|
|<<column-parentunderlineparameterunderline07>>
|nvarchar(4000)
|NULL
|

|
|<<column-parentunderlineparameterunderline08>>
|nvarchar(4000)
|NULL
|

|
|<<column-parentunderlineparameterunderline09>>
|nvarchar(4000)
|NULL
|

|
|<<column-parentunderlineparameterunderline10>>
|nvarchar(4000)
|NULL
|

|
|<<column-parentunderlineparameterunderline11>>
|nvarchar(4000)
|NULL
|

|
|<<column-parentunderlineparameterunderline12>>
|nvarchar(4000)
|NULL
|

|
|<<column-parentunderlineparameterunderline13>>
|nvarchar(4000)
|NULL
|

|
|<<column-parentunderlineparameterunderline14>>
|nvarchar(4000)
|NULL
|

|
|<<column-parentunderlineparameterunderline15>>
|nvarchar(4000)
|NULL
|

|
|<<column-parentunderlineparameterunderline16>>
|nvarchar(4000)
|NULL
|

|
|<<column-parentunderlineparameterunderline17>>
|nvarchar(4000)
|NULL
|

|
|<<column-parentunderlineparameterunderline18>>
|nvarchar(4000)
|NULL
|

|
|<<column-parentunderlineparameterunderline19>>
|nvarchar(4000)
|NULL
|

|
|<<column-parentunderlineparameterunderline20>>
|nvarchar(4000)
|NULL
|

|
|<<column-parentunderlineprocunderlinefullname>>
|nvarchar(517)
|NULL
|

|
|<<column-parentunderlineprocunderlineid>>
|int
|NULL
|

|
|<<column-parentunderlineprocunderlinename>>
|nvarchar(128)
|NULL
|

|
|<<column-parentunderlineprocunderlineschemaunderlinename>>
|nvarchar(128)
|NULL
|

|
|<<column-parentunderlinestepunderlineid>>
|int
|NULL
|

|
|<<column-parentunderlinestepunderlinename>>
|nvarchar(1000)
|NULL
|

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

[#index-idxunderlineexecutionlogunderlineparentunderlineunderline1]
=== idx_ExecutionLog_parent++__++1

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-id>>; bigint
--
* PK, Unique, Real: 0, 0, 0

// end::AntoraIndexList[]

== AntoraMeasureDetails

// tag::AntoraMeasureDetails[]

// end::AntoraMeasureDetails[]

== AntoraMeasureDescriptions



== AntoraParameterList

// tag::AntoraParameterList[]

// end::AntoraParameterList[]

== AntoraXrefCulturesList

// tag::AntoraXrefCulturesList[]
* xref:dhw:sqldb:logs.executionlog_parent.adoc[] - 
// end::AntoraXrefCulturesList[]

== cultures_count

// tag::cultures_count[]
1
// end::cultures_count[]

== Other tags

source: property.RepoObjectProperty_cross As rop_cross


=== additional_reference_csv

// tag::additional_reference_csv[]

// end::additional_reference_csv[]


=== AdocUspSteps

// tag::adocuspsteps[]

// end::adocuspsteps[]


=== AntoraReferencedList

// tag::antorareferencedlist[]
* xref:dhw:sqldb:logs.executionlog.adoc[]
// end::antorareferencedlist[]


=== AntoraReferencingList

// tag::antorareferencinglist[]
* xref:dhw:sqldb:logs.executionlog_puml_sequence_start_stop.adoc[]
// end::antorareferencinglist[]


=== Description

// tag::description[]

// end::description[]


=== exampleUsage

// tag::exampleusage[]

// end::exampleusage[]


=== exampleUsage_2

// tag::exampleusage_2[]

// end::exampleusage_2[]


=== exampleUsage_3

// tag::exampleusage_3[]

// end::exampleusage_3[]


=== exampleUsage_4

// tag::exampleusage_4[]

// end::exampleusage_4[]


=== exampleUsage_5

// tag::exampleusage_5[]

// end::exampleusage_5[]


=== exampleWrong_Usage

// tag::examplewrong_usage[]

// end::examplewrong_usage[]


=== has_execution_plan_issue

// tag::has_execution_plan_issue[]

// end::has_execution_plan_issue[]


=== has_get_referenced_issue

// tag::has_get_referenced_issue[]

// end::has_get_referenced_issue[]


=== has_history

// tag::has_history[]

// end::has_history[]


=== has_history_columns

// tag::has_history_columns[]

// end::has_history_columns[]


=== InheritanceType

// tag::inheritancetype[]

// end::inheritancetype[]


=== is_persistence

// tag::is_persistence[]

// end::is_persistence[]


=== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]

// end::is_persistence_check_duplicate_per_pk[]


=== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]

// end::is_persistence_check_for_empty_source[]


=== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]

// end::is_persistence_delete_changed[]


=== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]

// end::is_persistence_delete_missing[]


=== is_persistence_insert

// tag::is_persistence_insert[]

// end::is_persistence_insert[]


=== is_persistence_truncate

// tag::is_persistence_truncate[]

// end::is_persistence_truncate[]


=== is_persistence_update_changed

// tag::is_persistence_update_changed[]

// end::is_persistence_update_changed[]


=== is_repo_managed

// tag::is_repo_managed[]
0
// end::is_repo_managed[]


=== is_ssas

// tag::is_ssas[]
0
// end::is_ssas[]


=== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


=== MS_Description

// tag::ms_description[]

// end::ms_description[]


=== persistence_source_RepoObject_fullname

// tag::persistence_source_repoobject_fullname[]

// end::persistence_source_repoobject_fullname[]


=== persistence_source_RepoObject_fullname2

// tag::persistence_source_repoobject_fullname2[]

// end::persistence_source_repoobject_fullname2[]


=== persistence_source_RepoObject_guid

// tag::persistence_source_repoobject_guid[]

// end::persistence_source_repoobject_guid[]


=== persistence_source_RepoObject_xref

// tag::persistence_source_repoobject_xref[]

// end::persistence_source_repoobject_xref[]


=== pk_index_guid

// tag::pk_index_guid[]

// end::pk_index_guid[]


=== pk_IndexPatternColumnDatatype

// tag::pk_indexpatterncolumndatatype[]

// end::pk_indexpatterncolumndatatype[]


=== pk_IndexPatternColumnName

// tag::pk_indexpatterncolumnname[]

// end::pk_indexpatterncolumnname[]


=== pk_IndexSemanticGroup

// tag::pk_indexsemanticgroup[]

// end::pk_indexsemanticgroup[]


=== ReferencedObjectList

// tag::referencedobjectlist[]
* [logs].[ExecutionLog]
// end::referencedobjectlist[]


=== usp_persistence_RepoObject_guid

// tag::usp_persistence_repoobject_guid[]

// end::usp_persistence_repoobject_guid[]


=== UspExamples

// tag::uspexamples[]

// end::uspexamples[]


=== uspgenerator_usp_id

// tag::uspgenerator_usp_id[]

// end::uspgenerator_usp_id[]


=== UspParameters

// tag::uspparameters[]

// end::uspparameters[]

== Boolean Attributes

source: property.RepoObjectProperty WHERE property_int = 1

// tag::boolean_attributes[]


// end::boolean_attributes[]

== PlantUML diagrams

=== PlantUML Entity

// tag::puml_entity[]
[plantuml, entity-{docname}, svg, subs=macros]
....
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:logs.executionlog_parent.adoc[]" as logs.ExecutionLog_parent << V >> {
  - id : (bigint)
  parent_created_dt : (datetime)
  parent_current_execution_guid : (uniqueidentifier)
  parent_execution_log_id : (bigint)
  parent_parameter_01 : (nvarchar(4000))
  parent_parameter_02 : (nvarchar(4000))
  parent_parameter_03 : (nvarchar(4000))
  parent_parameter_04 : (nvarchar(4000))
  parent_parameter_05 : (nvarchar(4000))
  parent_parameter_06 : (nvarchar(4000))
  parent_parameter_07 : (nvarchar(4000))
  parent_parameter_08 : (nvarchar(4000))
  parent_parameter_09 : (nvarchar(4000))
  parent_parameter_10 : (nvarchar(4000))
  parent_parameter_11 : (nvarchar(4000))
  parent_parameter_12 : (nvarchar(4000))
  parent_parameter_13 : (nvarchar(4000))
  parent_parameter_14 : (nvarchar(4000))
  parent_parameter_15 : (nvarchar(4000))
  parent_parameter_16 : (nvarchar(4000))
  parent_parameter_17 : (nvarchar(4000))
  parent_parameter_18 : (nvarchar(4000))
  parent_parameter_19 : (nvarchar(4000))
  parent_parameter_20 : (nvarchar(4000))
  parent_proc_fullname : (nvarchar(517))
  parent_proc_id : (int)
  parent_proc_name : (nvarchar(128))
  parent_proc_schema_name : (nvarchar(128))
  parent_step_id : (int)
  parent_step_name : (nvarchar(1000))
  --
}
....

// end::puml_entity[]

=== PlantUML Entity 1 1 FK

// tag::puml_entity_1_1_fk[]
[plantuml, entity_1_1_fk-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:logs.executionlog_parent.adoc[]" as logs.ExecutionLog_parent << V >> {
- idx_ExecutionLog_parent__1

..
id; bigint
}



footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_fk[]

=== PlantUML 1 1 ObjectRef

// tag::puml_entity_1_1_objectref[]
[plantuml, entity_1_1_objectref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:logs.executionlog.adoc[]" as logs.ExecutionLog << U >> {
  - **id** : (bigint)
  --
}

entity "puml-link:dhw:sqldb:logs.executionlog_parent.adoc[]" as logs.ExecutionLog_parent << V >> {
  --
}

entity "puml-link:dhw:sqldb:logs.executionlog_puml_sequence_start_stop.adoc[]" as logs.ExecutionLog_puml_Sequence_start_stop << V >> {
  --
}

logs.ExecutionLog <.. logs.ExecutionLog_parent
logs.ExecutionLog_parent <.. logs.ExecutionLog_puml_Sequence_start_stop

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_objectref[]

=== PlantUML 30 0 ObjectRef

// tag::puml_entity_30_0_objectref[]
[plantuml, entity_30_0_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:logs.executionlog.adoc[]" as logs.ExecutionLog << U >> {
  - **id** : (bigint)
  --
}

entity "puml-link:dhw:sqldb:logs.executionlog_parent.adoc[]" as logs.ExecutionLog_parent << V >> {
  --
}

logs.ExecutionLog <.. logs.ExecutionLog_parent

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_30_0_objectref[]

=== PlantUML 0 30 ObjectRef

// tag::puml_entity_0_30_objectref[]
[plantuml, entity_0_30_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:logs.executionlog_parent.adoc[]" as logs.ExecutionLog_parent << V >> {
  --
}

entity "puml-link:dhw:sqldb:logs.executionlog_puml_sequence_start_stop.adoc[]" as logs.ExecutionLog_puml_Sequence_start_stop << V >> {
  --
}

entity "puml-link:dhw:sqldb:logs.ftv_executionlog_puml_sequence_start_stop_per_execution.adoc[]" as logs.ftv_ExecutionLog_puml_sequence_start_stop_per_execution << IF >> {
  --
}

logs.ExecutionLog_parent <.. logs.ExecutionLog_puml_Sequence_start_stop
logs.ExecutionLog_puml_Sequence_start_stop <.. logs.ftv_ExecutionLog_puml_sequence_start_stop_per_execution

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_0_30_objectref[]

=== PlantUML 1 1 ColumnRef

// tag::puml_entity_1_1_colref[]
[plantuml, entity_1_1_colref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:logs.executionlog.adoc[]" as logs.ExecutionLog << U >> {
  - **id** : (bigint)
  created_dt : (datetime)
  current_execution_guid : (uniqueidentifier)
  deleted : (int)
  event_info : (nvarchar(max))
  - execution_instance_guid : (uniqueidentifier)
  info_01 : (nvarchar(4000))
  info_02 : (nvarchar(4000))
  info_03 : (nvarchar(4000))
  info_04 : (nvarchar(4000))
  info_05 : (nvarchar(4000))
  info_06 : (nvarchar(4000))
  info_07 : (nvarchar(4000))
  info_08 : (nvarchar(4000))
  info_09 : (nvarchar(4000))
  inserted : (int)
  parameter_01 : (nvarchar(4000))
  parameter_02 : (nvarchar(4000))
  parameter_03 : (nvarchar(4000))
  parameter_04 : (nvarchar(4000))
  parameter_05 : (nvarchar(4000))
  parameter_06 : (nvarchar(4000))
  parameter_07 : (nvarchar(4000))
  parameter_08 : (nvarchar(4000))
  parameter_09 : (nvarchar(4000))
  parameter_10 : (nvarchar(4000))
  parameter_11 : (nvarchar(4000))
  parameter_12 : (nvarchar(4000))
  parameter_13 : (nvarchar(4000))
  parameter_14 : (nvarchar(4000))
  parameter_15 : (nvarchar(4000))
  parameter_16 : (nvarchar(4000))
  parameter_17 : (nvarchar(4000))
  parameter_18 : (nvarchar(4000))
  parameter_19 : (nvarchar(4000))
  parameter_20 : (nvarchar(4000))
  parent_execution_log_id : (bigint)
  proc_id : (int)
  proc_name : (nvarchar(128))
  proc_schema_name : (nvarchar(128))
  source_object : (nvarchar(261))
  ssis_execution_id : (bigint)
  step_id : (int)
  step_name : (nvarchar(1000))
  sub_execution_id : (int)
  target_object : (nvarchar(261))
  updated : (int)
  ~ proc_fullname : (nvarchar(517))
  --
}

entity "puml-link:dhw:sqldb:logs.executionlog_parent.adoc[]" as logs.ExecutionLog_parent << V >> {
  - id : (bigint)
  parent_created_dt : (datetime)
  parent_current_execution_guid : (uniqueidentifier)
  parent_execution_log_id : (bigint)
  parent_parameter_01 : (nvarchar(4000))
  parent_parameter_02 : (nvarchar(4000))
  parent_parameter_03 : (nvarchar(4000))
  parent_parameter_04 : (nvarchar(4000))
  parent_parameter_05 : (nvarchar(4000))
  parent_parameter_06 : (nvarchar(4000))
  parent_parameter_07 : (nvarchar(4000))
  parent_parameter_08 : (nvarchar(4000))
  parent_parameter_09 : (nvarchar(4000))
  parent_parameter_10 : (nvarchar(4000))
  parent_parameter_11 : (nvarchar(4000))
  parent_parameter_12 : (nvarchar(4000))
  parent_parameter_13 : (nvarchar(4000))
  parent_parameter_14 : (nvarchar(4000))
  parent_parameter_15 : (nvarchar(4000))
  parent_parameter_16 : (nvarchar(4000))
  parent_parameter_17 : (nvarchar(4000))
  parent_parameter_18 : (nvarchar(4000))
  parent_parameter_19 : (nvarchar(4000))
  parent_parameter_20 : (nvarchar(4000))
  parent_proc_fullname : (nvarchar(517))
  parent_proc_id : (int)
  parent_proc_name : (nvarchar(128))
  parent_proc_schema_name : (nvarchar(128))
  parent_step_id : (int)
  parent_step_name : (nvarchar(1000))
  --
}

entity "puml-link:dhw:sqldb:logs.executionlog_puml_sequence_start_stop.adoc[]" as logs.ExecutionLog_puml_Sequence_start_stop << V >> {
  created_dt : (datetime)
  - execution_instance_guid : (uniqueidentifier)
  - id : (bigint)
  parent_proc_fullname : (nvarchar(517))
  - proc_fullname : (nvarchar(517))
  - puml_Sequence_start_stop : (nvarchar(1574))
  --
}

logs.ExecutionLog <.. logs.ExecutionLog_parent
logs.ExecutionLog_parent <.. logs.ExecutionLog_puml_Sequence_start_stop
"logs.ExecutionLog::created_dt" <-- "logs.ExecutionLog_parent::parent_created_dt"
"logs.ExecutionLog::current_execution_guid" <-- "logs.ExecutionLog_parent::parent_current_execution_guid"
"logs.ExecutionLog::id" <-- "logs.ExecutionLog_parent::id"
"logs.ExecutionLog::parameter_01" <-- "logs.ExecutionLog_parent::parent_parameter_01"
"logs.ExecutionLog::parameter_02" <-- "logs.ExecutionLog_parent::parent_parameter_02"
"logs.ExecutionLog::parameter_03" <-- "logs.ExecutionLog_parent::parent_parameter_03"
"logs.ExecutionLog::parameter_04" <-- "logs.ExecutionLog_parent::parent_parameter_04"
"logs.ExecutionLog::parameter_05" <-- "logs.ExecutionLog_parent::parent_parameter_05"
"logs.ExecutionLog::parameter_06" <-- "logs.ExecutionLog_parent::parent_parameter_06"
"logs.ExecutionLog::parameter_07" <-- "logs.ExecutionLog_parent::parent_parameter_07"
"logs.ExecutionLog::parameter_08" <-- "logs.ExecutionLog_parent::parent_parameter_08"
"logs.ExecutionLog::parameter_09" <-- "logs.ExecutionLog_parent::parent_parameter_09"
"logs.ExecutionLog::parameter_10" <-- "logs.ExecutionLog_parent::parent_parameter_10"
"logs.ExecutionLog::parameter_11" <-- "logs.ExecutionLog_parent::parent_parameter_11"
"logs.ExecutionLog::parameter_12" <-- "logs.ExecutionLog_parent::parent_parameter_12"
"logs.ExecutionLog::parameter_13" <-- "logs.ExecutionLog_parent::parent_parameter_13"
"logs.ExecutionLog::parameter_14" <-- "logs.ExecutionLog_parent::parent_parameter_14"
"logs.ExecutionLog::parameter_15" <-- "logs.ExecutionLog_parent::parent_parameter_15"
"logs.ExecutionLog::parameter_16" <-- "logs.ExecutionLog_parent::parent_parameter_16"
"logs.ExecutionLog::parameter_17" <-- "logs.ExecutionLog_parent::parent_parameter_17"
"logs.ExecutionLog::parameter_18" <-- "logs.ExecutionLog_parent::parent_parameter_18"
"logs.ExecutionLog::parameter_19" <-- "logs.ExecutionLog_parent::parent_parameter_19"
"logs.ExecutionLog::parameter_20" <-- "logs.ExecutionLog_parent::parent_parameter_20"
"logs.ExecutionLog::parent_execution_log_id" <-- "logs.ExecutionLog_parent::parent_execution_log_id"
"logs.ExecutionLog::proc_fullname" <-- "logs.ExecutionLog_parent::parent_proc_fullname"
"logs.ExecutionLog::proc_id" <-- "logs.ExecutionLog_parent::parent_proc_id"
"logs.ExecutionLog::proc_name" <-- "logs.ExecutionLog_parent::parent_proc_name"
"logs.ExecutionLog::proc_schema_name" <-- "logs.ExecutionLog_parent::parent_proc_schema_name"
"logs.ExecutionLog::step_id" <-- "logs.ExecutionLog_parent::parent_step_id"
"logs.ExecutionLog::step_name" <-- "logs.ExecutionLog_parent::parent_step_name"
"logs.ExecutionLog_parent::parent_proc_fullname" <-- "logs.ExecutionLog_puml_Sequence_start_stop::parent_proc_fullname"

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_colref[]


== sql_modules_definition

// tag::sql_modules_definition[]
[%collapsible]
=======
[source,sql,numbered,indent=0]
----

CREATE View logs.ExecutionLog_parent
As
Select
    T1.id
  , T1.parent_execution_log_id
  , parent_current_execution_guid = parent.current_execution_guid
  , parent_proc_id                = parent.proc_id
  , parent_proc_schema_name       = parent.proc_schema_name
  , parent_proc_name              = parent.proc_name
  , parent_step_id                = parent.step_id
  , parent_step_name              = parent.step_name
  , parent_created_dt             = parent.created_dt
  , parent_parameter_01           = parent.parameter_01
  , parent_parameter_02           = parent.parameter_02
  , parent_parameter_03           = parent.parameter_03
  , parent_parameter_04           = parent.parameter_04
  , parent_parameter_05           = parent.parameter_05
  , parent_parameter_06           = parent.parameter_06
  , parent_parameter_07           = parent.parameter_07
  , parent_parameter_08           = parent.parameter_08
  , parent_parameter_09           = parent.parameter_09
  , parent_parameter_10           = parent.parameter_10
  , parent_parameter_11           = parent.parameter_11
  , parent_parameter_12           = parent.parameter_12
  , parent_parameter_13           = parent.parameter_13
  , parent_parameter_14           = parent.parameter_14
  , parent_parameter_15           = parent.parameter_15
  , parent_parameter_16           = parent.parameter_16
  , parent_parameter_17           = parent.parameter_17
  , parent_parameter_18           = parent.parameter_18
  , parent_parameter_19           = parent.parameter_19
  , parent_parameter_20           = parent.parameter_20
  , parent_proc_fullname          = parent.proc_fullname
From
    logs.ExecutionLog     As T1
    Left Join
        logs.ExecutionLog As parent
            On
            parent.id = T1.parent_execution_log_id
Where
    Not parent.id Is Null
----
=======
// end::sql_modules_definition[]


