// tag::HeaderFullDisplayName[]
= property.RepoObjectProperty_InheritanceType_InheritanceDefinition - V
// end::HeaderFullDisplayName[]

== existing_properties

// tag::existing_properties[]

:ExistsProperty--antorareferencedlist:
:ExistsProperty--antorareferencinglist:
:ExistsProperty--is_repo_managed:
:ExistsProperty--is_ssas:
:ExistsProperty--pk_index_guid:
:ExistsProperty--pk_indexpatterncolumndatatype:
:ExistsProperty--pk_indexpatterncolumnname:
:ExistsProperty--referencedobjectlist:
:ExistsProperty--sql_modules_definition:
:ExistsProperty--FK:
:ExistsProperty--AntoraIndexList:
:ExistsProperty--Columns:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
64B33A4A-426D-EB11-84E2-A81E8446D5B0
// end::RepoObject_guid[]

== RepoObject_FullDisplayName2

// tag::RepoObject_FullDisplayName2[]
property.RepoObjectProperty_InheritanceType_InheritanceDefinition
// end::RepoObject_FullDisplayName2[]

== SysObject_type

// tag::SysObject_type[]
V 
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
view
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
292912115
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2021-09-13 23:31:37
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]
[discrete]
== _


[#column-repoobjectunderlineguid]
=== RepoObject_guid

[cols="d,8a,m,m,m"]
|===
|1
|*RepoObject_guid*
|uniqueidentifier
|NOT NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject.adoc#column-repoobjectunderlineguid[+repo.RepoObject.RepoObject_guid+]
--

.Referencing Columns
--
* xref:property.repoobjectproperty_inheritancetype_resulting_inheritancedefinition.adoc#column-repoobjectunderlineguid[+property.RepoObjectProperty_InheritanceType_resulting_InheritanceDefinition.RepoObject_guid+]
--


[#column-propertyunderlinename]
=== property_name

[cols="d,8a,m,m,m"]
|===
|2
|*property_name*
|nvarchar(128)
|NOT NULL
|
|===

.Referenced Columns
--
* xref:property.propertyname_repoobject_t.adoc#column-propertyunderlinename[+property.PropertyName_RepoObject_T.property_name+]
--

.Referencing Columns
--
* xref:property.repoobjectproperty_inheritancetype_resulting_inheritancedefinition.adoc#column-propertyunderlinename[+property.RepoObjectProperty_InheritanceType_resulting_InheritanceDefinition.property_name+]
--


[#column-inheritanceunderlinesourceunderlinefullname]
=== Inheritance_Source_fullname

[cols="d,8a,m,m,m"]
|===
|
|Inheritance_Source_fullname
|nvarchar(261)
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject.adoc#column-inheritanceunderlinesourceunderlinefullname[+repo.RepoObject.Inheritance_Source_fullname+]
--

.Referencing Columns
--
* xref:property.repoobjectproperty_inheritancetype_resulting_inheritancedefinition.adoc#column-inheritanceunderlinesourceunderlinefullname[+property.RepoObjectProperty_InheritanceType_resulting_InheritanceDefinition.Inheritance_Source_fullname+]
--


[#column-inheritanceunderlinestringaggseparatorsql]
=== Inheritance_StringAggSeparatorSql

[cols="d,8a,m,m,m"]
|===
|
|Inheritance_StringAggSeparatorSql
|nvarchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject.adoc#column-inheritanceunderlinestringaggseparatorsql[+repo.RepoObject.Inheritance_StringAggSeparatorSql+]
--

.Referencing Columns
--
* xref:property.repoobjectproperty_inheritancetype_resulting_inheritancedefinition.adoc#column-inheritanceunderlinestringaggseparatorsql[+property.RepoObjectProperty_InheritanceType_resulting_InheritanceDefinition.Inheritance_StringAggSeparatorSql+]
--


[#column-inheritancedefinition]
=== InheritanceDefinition

[cols="d,8a,m,m,m"]
|===
|
|InheritanceDefinition
|nvarchar(max)
|NULL
|
|===

.Referencing Columns
--
* xref:property.repoobjectproperty_inheritancetype_resulting_inheritancedefinition.adoc#column-inheritancedefinition[+property.RepoObjectProperty_InheritanceType_resulting_InheritanceDefinition.InheritanceDefinition+]
--


[#column-inheritancetype]
=== InheritanceType

[cols="d,8a,m,m,m"]
|===
|
|InheritanceType
|int
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject.adoc#column-inheritancetype[+repo.RepoObject.InheritanceType+]
--

.Referencing Columns
--
* xref:property.repoobjectproperty_inheritancetype_resulting_inheritancedefinition.adoc#column-inheritancetype[+property.RepoObjectProperty_InheritanceType_resulting_InheritanceDefinition.InheritanceType+]
--


[#column-parunderlineinheritanceunderlinestringaggseparatorsql]
=== par_Inheritance_StringAggSeparatorSql

[cols="d,8a,m,m,m"]
|===
|
|par_Inheritance_StringAggSeparatorSql
|nvarchar(max)
|NULL
|
|===

.Description
--
(coalesce([Parameter_value],[Parameter_default_value]))
--
{empty} +

.Referenced Columns
--
* xref:config.parameter.adoc#column-parameterunderlinevalueunderlineresult[+config.Parameter.Parameter_value_result+]
--


[#column-parunderlineinheritancedefintion]
=== par_InheritanceDefintion

[cols="d,8a,m,m,m"]
|===
|
|par_InheritanceDefintion
|nvarchar(max)
|NULL
|
|===

.Description
--
(coalesce([Parameter_value],[Parameter_default_value]))
--
{empty} +

.Referenced Columns
--
* xref:config.parameter.adoc#column-parameterunderlinevalueunderlineresult[+config.Parameter.Parameter_value_result+]
--


[#column-parunderlineinheritancetype]
=== par_InheritanceType

[cols="d,8a,m,m,m"]
|===
|
|par_InheritanceType
|int
|NULL
|
|===

.Description
--
(TRY_CAST(left(coalesce([Parameter_value],[Parameter_default_value]),(4000)) AS [int]))
--
{empty} +

.Referenced Columns
--
* xref:config.parameter.adoc#column-parameterunderlinevalueunderlineresultunderlineint[+config.Parameter.Parameter_value_result_int+]
--


[#column-propertyunderlinevalue]
=== property_value

[cols="d,8a,m,m,m"]
|===
|
|property_value
|nvarchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:property.repoobjectproperty.adoc#column-propertyunderlinevalue[+property.RepoObjectProperty.property_value+]
--

.Referencing Columns
--
* xref:property.repoobjectproperty_inheritancetype_resulting_inheritancedefinition.adoc#column-propertyunderlinevalue[+property.RepoObjectProperty_InheritanceType_resulting_InheritanceDefinition.property_value+]
--


[#column-repoobjectunderlinefullname]
=== RepoObject_fullname

[cols="d,8a,m,m,m"]
|===
|
|RepoObject_fullname
|nvarchar(261)
|NOT NULL
|
|===

.Description
--
(concat('[',[RepoObject_schema_name],'].[',[RepoObject_name],']'))
--
{empty} +

.Referenced Columns
--
* xref:repo.repoobject.adoc#column-repoobjectunderlinefullname[+repo.RepoObject.RepoObject_fullname+]
--

.Referencing Columns
--
* xref:property.repoobjectproperty_inheritancetype_resulting_inheritancedefinition.adoc#column-repoobjectunderlinefullname[+property.RepoObjectProperty_InheritanceType_resulting_InheritanceDefinition.RepoObject_fullname+]
--


[#column-repoobjectunderlinetype]
=== RepoObject_type

[cols="d,8a,m,m,m"]
|===
|
|RepoObject_type
|char(2)
|NOT NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject.adoc#column-repoobjectunderlinetype[+repo.RepoObject.RepoObject_type+]
--

.Referencing Columns
--
* xref:property.repoobjectproperty_inheritancetype_resulting_inheritancedefinition.adoc#column-repoobjectunderlinetype[+property.RepoObjectProperty_InheritanceType_resulting_InheritanceDefinition.RepoObject_type+]
--


[#column-rounderlineinheritanceunderlinestringaggseparatorsql]
=== ro_Inheritance_StringAggSeparatorSql

[cols="d,8a,m,m,m"]
|===
|
|ro_Inheritance_StringAggSeparatorSql
|nvarchar(4000)
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject.adoc#column-inheritanceunderlinestringaggseparatorsql[+repo.RepoObject.Inheritance_StringAggSeparatorSql+]
--


[#column-rounderlineinheritancedefinition]
=== ro_InheritanceDefinition

[cols="d,8a,m,m,m"]
|===
|
|ro_InheritanceDefinition
|nvarchar(4000)
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject.adoc#column-inheritancedefinition[+repo.RepoObject.InheritanceDefinition+]
--


[#column-rounderlineinheritancetype]
=== ro_InheritanceType

[cols="d,8a,m,m,m"]
|===
|
|ro_InheritanceType
|tinyint
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject.adoc#column-inheritancetype[+repo.RepoObject.InheritanceType+]
--


[#column-subunderlineinheritanceunderlinestringaggseparatorsql]
=== sub_Inheritance_StringAggSeparatorSql

[cols="d,8a,m,m,m"]
|===
|
|sub_Inheritance_StringAggSeparatorSql
|nvarchar(max)
|NULL
|
|===

.Description
--
(coalesce([Parameter_value],[Parameter_default_value]))
--
{empty} +

.Referenced Columns
--
* xref:config.parameter.adoc#column-parameterunderlinevalueunderlineresult[+config.Parameter.Parameter_value_result+]
--


[#column-subunderlineinheritancedefintion]
=== sub_InheritanceDefintion

[cols="d,8a,m,m,m"]
|===
|
|sub_InheritanceDefintion
|nvarchar(max)
|NULL
|
|===

.Description
--
(coalesce([Parameter_value],[Parameter_default_value]))
--
{empty} +

.Referenced Columns
--
* xref:config.parameter.adoc#column-parameterunderlinevalueunderlineresult[+config.Parameter.Parameter_value_result+]
--


[#column-subunderlineinheritancetype]
=== sub_InheritanceType

[cols="d,8a,m,m,m"]
|===
|
|sub_InheritanceType
|int
|NULL
|
|===

.Description
--
(TRY_CAST(left(coalesce([Parameter_value],[Parameter_default_value]),(4000)) AS [int]))
--
{empty} +

.Referenced Columns
--
* xref:config.parameter.adoc#column-parameterunderlinevalueunderlineresultunderlineint[+config.Parameter.Parameter_value_result_int+]
--


// end::AntoraColumnDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]
|1
|*<<column-repoobjectunderlineguid>>*
|uniqueidentifier
|NOT NULL
|

|2
|*<<column-propertyunderlinename>>*
|nvarchar(128)
|NOT NULL
|

















// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]


|
|<<column-inheritanceunderlinesourceunderlinefullname>>
|nvarchar(261)
|NULL
|

|
|<<column-inheritanceunderlinestringaggseparatorsql>>
|nvarchar(max)
|NULL
|

|
|<<column-inheritancedefinition>>
|nvarchar(max)
|NULL
|

|
|<<column-inheritancetype>>
|int
|NULL
|

|
|<<column-parunderlineinheritanceunderlinestringaggseparatorsql>>
|nvarchar(max)
|NULL
|

|
|<<column-parunderlineinheritancedefintion>>
|nvarchar(max)
|NULL
|

|
|<<column-parunderlineinheritancetype>>
|int
|NULL
|

|
|<<column-propertyunderlinevalue>>
|nvarchar(max)
|NULL
|

|
|<<column-repoobjectunderlinefullname>>
|nvarchar(261)
|NOT NULL
|

|
|<<column-repoobjectunderlinetype>>
|char(2)
|NOT NULL
|

|
|<<column-rounderlineinheritanceunderlinestringaggseparatorsql>>
|nvarchar(4000)
|NULL
|

|
|<<column-rounderlineinheritancedefinition>>
|nvarchar(4000)
|NULL
|

|
|<<column-rounderlineinheritancetype>>
|tinyint
|NULL
|

|
|<<column-subunderlineinheritanceunderlinestringaggseparatorsql>>
|nvarchar(max)
|NULL
|

|
|<<column-subunderlineinheritancedefintion>>
|nvarchar(max)
|NULL
|

|
|<<column-subunderlineinheritancetype>>
|int
|NULL
|

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

[#index-pkunderlinerepoobjectpropertyunderlineinheritancetypeunderlineinheritancedefinition]
=== PK_RepoObjectProperty_InheritanceType_InheritanceDefinition

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-RepoObject_guid>>; uniqueidentifier
* <<column-property_name>>; nvarchar(128)
--
* PK, Unique, Real: 1, 1, 0


[#index-idxunderlinerepoobjectpropertyunderlineinheritancetypeunderlineinheritancedefinitionunderlineunderline2]
=== idx_RepoObjectProperty_InheritanceType_InheritanceDefinition++__++2

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-RepoObject_guid>>; uniqueidentifier
--
* PK, Unique, Real: 0, 0, 0


[#index-idxunderlinerepoobjectpropertyunderlineinheritancetypeunderlineinheritancedefinitionunderlineunderline3]
=== idx_RepoObjectProperty_InheritanceType_InheritanceDefinition++__++3

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-property_name>>; nvarchar(128)
--
* PK, Unique, Real: 0, 0, 0

// end::AntoraIndexList[]

== AntoraMeasureDetails

// tag::AntoraMeasureDetails[]

// end::AntoraMeasureDetails[]

== AntoraMeasureDescriptions



== AntoraParameterList

// tag::AntoraParameterList[]

// end::AntoraParameterList[]

== AntoraXrefCulturesList

// tag::AntoraXrefCulturesList[]
* xref:dhw:sqldb:property.repoobjectproperty_inheritancetype_inheritancedefinition.adoc[] - 
// end::AntoraXrefCulturesList[]

== cultures_count

// tag::cultures_count[]
1
// end::cultures_count[]

== Other tags

source: property.RepoObjectProperty_cross As rop_cross


=== additional_reference_csv

// tag::additional_reference_csv[]

// end::additional_reference_csv[]


=== AdocUspSteps

// tag::adocuspsteps[]

// end::adocuspsteps[]


=== AntoraReferencedList

// tag::antorareferencedlist[]
* xref:dhw:sqldb:config.parameter.adoc[]
* xref:dhw:sqldb:property.propertyname_repoobject_t.adoc[]
* xref:dhw:sqldb:property.repoobjectproperty.adoc[]
* xref:dhw:sqldb:repo.repoobject.adoc[]
// end::antorareferencedlist[]


=== AntoraReferencingList

// tag::antorareferencinglist[]
* xref:dhw:sqldb:property.repoobjectproperty_inheritancetype_resulting_inheritancedefinition.adoc[]
// end::antorareferencinglist[]


=== Description

// tag::description[]

// end::description[]


=== exampleUsage

// tag::exampleusage[]

// end::exampleusage[]


=== exampleUsage_2

// tag::exampleusage_2[]

// end::exampleusage_2[]


=== exampleUsage_3

// tag::exampleusage_3[]

// end::exampleusage_3[]


=== exampleUsage_4

// tag::exampleusage_4[]

// end::exampleusage_4[]


=== exampleUsage_5

// tag::exampleusage_5[]

// end::exampleusage_5[]


=== exampleWrong_Usage

// tag::examplewrong_usage[]

// end::examplewrong_usage[]


=== has_execution_plan_issue

// tag::has_execution_plan_issue[]

// end::has_execution_plan_issue[]


=== has_get_referenced_issue

// tag::has_get_referenced_issue[]

// end::has_get_referenced_issue[]


=== has_history

// tag::has_history[]

// end::has_history[]


=== has_history_columns

// tag::has_history_columns[]

// end::has_history_columns[]


=== InheritanceType

// tag::inheritancetype[]

// end::inheritancetype[]


=== is_persistence

// tag::is_persistence[]

// end::is_persistence[]


=== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]

// end::is_persistence_check_duplicate_per_pk[]


=== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]

// end::is_persistence_check_for_empty_source[]


=== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]

// end::is_persistence_delete_changed[]


=== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]

// end::is_persistence_delete_missing[]


=== is_persistence_insert

// tag::is_persistence_insert[]

// end::is_persistence_insert[]


=== is_persistence_truncate

// tag::is_persistence_truncate[]

// end::is_persistence_truncate[]


=== is_persistence_update_changed

// tag::is_persistence_update_changed[]

// end::is_persistence_update_changed[]


=== is_repo_managed

// tag::is_repo_managed[]
0
// end::is_repo_managed[]


=== is_ssas

// tag::is_ssas[]
0
// end::is_ssas[]


=== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


=== MS_Description

// tag::ms_description[]

// end::ms_description[]


=== persistence_source_RepoObject_fullname

// tag::persistence_source_repoobject_fullname[]

// end::persistence_source_repoobject_fullname[]


=== persistence_source_RepoObject_fullname2

// tag::persistence_source_repoobject_fullname2[]

// end::persistence_source_repoobject_fullname2[]


=== persistence_source_RepoObject_guid

// tag::persistence_source_repoobject_guid[]

// end::persistence_source_repoobject_guid[]


=== persistence_source_RepoObject_xref

// tag::persistence_source_repoobject_xref[]

// end::persistence_source_repoobject_xref[]


=== pk_index_guid

// tag::pk_index_guid[]
9C1492C1-0B96-EB11-84F4-A81E8446D5B0
// end::pk_index_guid[]


=== pk_IndexPatternColumnDatatype

// tag::pk_indexpatterncolumndatatype[]
uniqueidentifier,nvarchar(128)
// end::pk_indexpatterncolumndatatype[]


=== pk_IndexPatternColumnName

// tag::pk_indexpatterncolumnname[]
RepoObject_guid,property_name
// end::pk_indexpatterncolumnname[]


=== pk_IndexSemanticGroup

// tag::pk_indexsemanticgroup[]

// end::pk_indexsemanticgroup[]


=== ReferencedObjectList

// tag::referencedobjectlist[]
* [config].[Parameter]
* [property].[PropertyName_RepoObject_T]
* [property].[RepoObjectProperty]
* [repo].[RepoObject]
// end::referencedobjectlist[]


=== usp_persistence_RepoObject_guid

// tag::usp_persistence_repoobject_guid[]

// end::usp_persistence_repoobject_guid[]


=== UspExamples

// tag::uspexamples[]

// end::uspexamples[]


=== uspgenerator_usp_id

// tag::uspgenerator_usp_id[]

// end::uspgenerator_usp_id[]


=== UspParameters

// tag::uspparameters[]

// end::uspparameters[]

== Boolean Attributes

source: property.RepoObjectProperty WHERE property_int = 1

// tag::boolean_attributes[]


// end::boolean_attributes[]

== PlantUML diagrams

=== PlantUML Entity

// tag::puml_entity[]
[plantuml, entity-{docname}, svg, subs=macros]
....
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:property.repoobjectproperty_inheritancetype_inheritancedefinition.adoc[]" as property.RepoObjectProperty_InheritanceType_InheritanceDefinition << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  Inheritance_Source_fullname : (nvarchar(261))
  Inheritance_StringAggSeparatorSql : (nvarchar(max))
  InheritanceDefinition : (nvarchar(max))
  InheritanceType : (int)
  par_Inheritance_StringAggSeparatorSql : (nvarchar(max))
  par_InheritanceDefintion : (nvarchar(max))
  par_InheritanceType : (int)
  property_value : (nvarchar(max))
  - RepoObject_fullname : (nvarchar(261))
  - RepoObject_type : (char(2))
  ro_Inheritance_StringAggSeparatorSql : (nvarchar(4000))
  ro_InheritanceDefinition : (nvarchar(4000))
  ro_InheritanceType : (tinyint)
  sub_Inheritance_StringAggSeparatorSql : (nvarchar(max))
  sub_InheritanceDefintion : (nvarchar(max))
  sub_InheritanceType : (int)
  --
}
....

// end::puml_entity[]

=== PlantUML Entity 1 1 FK

// tag::puml_entity_1_1_fk[]
[plantuml, entity_1_1_fk-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:property.repoobjectproperty_inheritancetype_inheritancedefinition.adoc[]" as property.RepoObjectProperty_InheritanceType_InheritanceDefinition << V >> {
- **PK_RepoObjectProperty_InheritanceType_InheritanceDefinition**

..
RepoObject_guid; uniqueidentifier
property_name; nvarchar(128)
--
- idx_RepoObjectProperty_InheritanceType_InheritanceDefinition__2

..
RepoObject_guid; uniqueidentifier
--
- idx_RepoObjectProperty_InheritanceType_InheritanceDefinition__3

..
property_name; nvarchar(128)
}



footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_fk[]

=== PlantUML 1 1 ObjectRef

// tag::puml_entity_1_1_objectref[]
[plantuml, entity_1_1_objectref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:config.parameter.adoc[]" as config.Parameter << U >> {
  - **Parameter_name** : (varchar(100))
  - **sub_Parameter** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.propertyname_repoobject_t.adoc[]" as property.PropertyName_RepoObject_T << U >> {
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty.adoc[]" as property.RepoObjectProperty << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty_inheritancetype_inheritancedefinition.adoc[]" as property.RepoObjectProperty_InheritanceType_InheritanceDefinition << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty_inheritancetype_resulting_inheritancedefinition.adoc[]" as property.RepoObjectProperty_InheritanceType_resulting_InheritanceDefinition << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject.adoc[]" as repo.RepoObject << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

config.Parameter <.. property.RepoObjectProperty_InheritanceType_InheritanceDefinition
property.PropertyName_RepoObject_T <.. property.RepoObjectProperty_InheritanceType_InheritanceDefinition
property.RepoObjectProperty <.. property.RepoObjectProperty_InheritanceType_InheritanceDefinition
property.RepoObjectProperty_InheritanceType_InheritanceDefinition <.. property.RepoObjectProperty_InheritanceType_resulting_InheritanceDefinition
repo.RepoObject <.. property.RepoObjectProperty_InheritanceType_InheritanceDefinition

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_objectref[]

=== PlantUML 30 0 ObjectRef

// tag::puml_entity_30_0_objectref[]
[plantuml, entity_30_0_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:config.ftv_get_parameter_value.adoc[]" as config.ftv_get_parameter_value << IF >> {
  --
}

entity "puml-link:dhw:sqldb:config.parameter.adoc[]" as config.Parameter << U >> {
  - **Parameter_name** : (varchar(100))
  - **sub_Parameter** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:configt.parameter_default.adoc[]" as configT.Parameter_default << V >> {
  - **Parameter_name** : (varchar(52))
  - **sub_Parameter** : (nvarchar(26))
  --
}

entity "puml-link:dhw:sqldb:property.external_repoobjectproperty.adoc[]" as property.external_RepoObjectProperty << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.propertyname_repoobject.adoc[]" as property.PropertyName_RepoObject << V >> {
  **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.propertyname_repoobject_t.adoc[]" as property.PropertyName_RepoObject_T << U >> {
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty.adoc[]" as property.RepoObjectProperty << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty_external_src.adoc[]" as property.RepoObjectProperty_external_src << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty_external_tgt.adoc[]" as property.RepoObjectProperty_external_tgt << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty_inheritancetype_inheritancedefinition.adoc[]" as property.RepoObjectProperty_InheritanceType_InheritanceDefinition << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty_selectedpropertyname_split.adoc[]" as property.RepoObjectProperty_SelectedPropertyName_split << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference.adoc[]" as reference.additional_Reference << U >> {
  # **tik_hash_c** : (nvarchar(32))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_from_properties_src.adoc[]" as reference.additional_Reference_from_properties_src << V >> {
  **referenced_AntoraComponent** : (nvarchar(max))
  **referenced_AntoraModule** : (nvarchar(max))
  **referenced_Schema** : (nvarchar(max))
  **referenced_Object** : (nvarchar(max))
  **referenced_Column** : (nvarchar(max))
  **referencing_AntoraComponent** : (nvarchar(max))
  **referencing_AntoraModule** : (nvarchar(max))
  **referencing_Schema** : (nvarchar(max))
  **referencing_Object** : (nvarchar(max))
  **referencing_Column** : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_from_properties_tgt.adoc[]" as reference.additional_Reference_from_properties_tgt << V >> {
  - **referenced_AntoraComponent** : (nvarchar(128))
  - **referenced_AntoraModule** : (nvarchar(128))
  - **referenced_Schema** : (nvarchar(128))
  - **referenced_Object** : (nvarchar(128))
  **referenced_Column** : (nvarchar(128))
  - **referencing_AntoraComponent** : (nvarchar(128))
  - **referencing_AntoraModule** : (nvarchar(128))
  - **referencing_Schema** : (nvarchar(128))
  - **referencing_Object** : (nvarchar(128))
  **referencing_Column** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_from_ssas_src.adoc[]" as reference.additional_Reference_from_ssas_src << V >> {
  **referenced_AntoraComponent** : (nvarchar(128))
  **referenced_AntoraModule** : (nvarchar(128))
  **referenced_Schema** : (nvarchar(max))
  **referenced_Object** : (nvarchar(max))
  **referenced_Column** : (nvarchar(500))
  **referencing_AntoraComponent** : (nvarchar(max))
  **referencing_AntoraModule** : (nvarchar(max))
  - **referencing_Schema** : (nvarchar(128))
  - **referencing_Object** : (nvarchar(128))
  **referencing_Column** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_from_ssas_tgt.adoc[]" as reference.additional_Reference_from_ssas_tgt << V >> {
  - **referenced_AntoraComponent** : (nvarchar(128))
  - **referenced_AntoraModule** : (nvarchar(128))
  - **referenced_Schema** : (nvarchar(128))
  - **referenced_Object** : (nvarchar(128))
  **referenced_Column** : (nvarchar(128))
  - **referencing_AntoraComponent** : (nvarchar(128))
  - **referencing_AntoraModule** : (nvarchar(128))
  - **referencing_Schema** : (nvarchar(128))
  - **referencing_Object** : (nvarchar(128))
  **referencing_Column** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_is_external.adoc[]" as reference.additional_Reference_is_external << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_object.adoc[]" as reference.additional_Reference_Object << V >> {
  - **AntoraComponent** : (nvarchar(128))
  - **AntoraModule** : (nvarchar(128))
  - **SchemaName** : (nvarchar(128))
  - **ObjectName** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_object_t.adoc[]" as reference.additional_Reference_Object_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_wo_columns_from_properties_src.adoc[]" as reference.additional_Reference_wo_columns_from_properties_src << V >> {
  **referenced_AntoraComponent** : (nvarchar(max))
  **referenced_AntoraModule** : (nvarchar(max))
  **referenced_Schema** : (nvarchar(max))
  **referenced_Object** : (nvarchar(max))
  **referencing_AntoraComponent** : (nvarchar(max))
  **referencing_AntoraModule** : (nvarchar(max))
  **referencing_Schema** : (nvarchar(max))
  **referencing_Object** : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_wo_columns_from_properties_tgt.adoc[]" as reference.additional_Reference_wo_columns_from_properties_tgt << V >> {
  - **referenced_AntoraComponent** : (nvarchar(128))
  - **referenced_AntoraModule** : (nvarchar(128))
  - **referenced_Schema** : (nvarchar(128))
  - **referenced_Object** : (nvarchar(128))
  - **referencing_AntoraComponent** : (nvarchar(128))
  - **referencing_AntoraModule** : (nvarchar(128))
  - **referencing_Schema** : (nvarchar(128))
  - **referencing_Object** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject.adoc[]" as repo.RepoObject << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_external_src.adoc[]" as repo.RepoObject_external_src << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_external_tgt.adoc[]" as repo.RepoObject_external_tgt << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_ssas_src.adoc[]" as repo.RepoObject_SSAS_src << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_ssas_tgt.adoc[]" as repo.RepoObject_SSAS_tgt << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.reposchema.adoc[]" as repo.RepoSchema << U >> {
  - **RepoSchema_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.reposchema_ssas_src.adoc[]" as repo.RepoSchema_ssas_src << V >> {
  - **RepoSchema_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:repo.reposchema_ssas_tgt.adoc[]" as repo.RepoSchema_ssas_tgt << V >> {
  - **RepoSchema_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:ssas.additional_reference_step1.adoc[]" as ssas.additional_Reference_step1 << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json.adoc[]" as ssas.model_json << U >> {
  - **databasename** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_10.adoc[]" as ssas.model_json_10 << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_20.adoc[]" as ssas.model_json_20 << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_201_descriptions_multiline.adoc[]" as ssas.model_json_201_descriptions_multiline << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_2011_descriptions_stragg.adoc[]" as ssas.model_json_2011_descriptions_StrAgg << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31_tables.adoc[]" as ssas.model_json_31_tables << V >> {
  - **databasename** : (nvarchar(128))
  **tables_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31_tables_t.adoc[]" as ssas.model_json_31_tables_T << U >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_311_tables_columns.adoc[]" as ssas.model_json_311_tables_columns << V >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  **tables_columns_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_311_tables_columns_t.adoc[]" as ssas.model_json_311_tables_columns_T << U >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  - **tables_columns_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_313_tables_partitions.adoc[]" as ssas.model_json_313_tables_partitions << V >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  **tables_partitions_name** : (nvarchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_3131_tables_partitions_source.adoc[]" as ssas.model_json_3131_tables_partitions_source << V >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  **tables_partitions_name** : (nvarchar(500))
  **tables_partitions_source_name** : (nvarchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31311_tables_partitions_source_posfrom.adoc[]" as ssas.model_json_31311_tables_partitions_source_PosFrom << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_313111_tables_partitions_source_stringfrom.adoc[]" as ssas.model_json_313111_tables_partitions_source_StringFrom << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_3131111_tables_partitions_source_posdot.adoc[]" as ssas.model_json_3131111_tables_partitions_source_PosDot << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31311111_tables_partitions_source_part123.adoc[]" as ssas.model_json_31311111_tables_partitions_source_Part123 << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_33_datasources.adoc[]" as ssas.model_json_33_dataSources << V >> {
  - **databasename** : (nvarchar(128))
  **dataSources_name** : (nvarchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_33_datasources_t.adoc[]" as ssas.model_json_33_dataSources_T << U >> {
  - **databasename** : (nvarchar(128))
  - **dataSources_name** : (nvarchar(500))
  --
}

config.ftv_get_parameter_value <.. ssas.additional_Reference_step1
config.ftv_get_parameter_value <.. reference.additional_Reference_is_external
config.ftv_get_parameter_value <.. repo.RepoObject_external_src
config.Parameter <.. property.RepoObjectProperty_InheritanceType_InheritanceDefinition
config.Parameter <.. config.ftv_get_parameter_value
config.Parameter <.. property.PropertyName_RepoObject
configT.Parameter_default <.. config.Parameter
property.external_RepoObjectProperty <.. property.RepoObjectProperty_external_src
property.PropertyName_RepoObject <.. property.PropertyName_RepoObject_T
property.PropertyName_RepoObject_T <.. property.RepoObjectProperty_InheritanceType_InheritanceDefinition
property.PropertyName_RepoObject_T <.. property.RepoObjectProperty_external_tgt
property.RepoObjectProperty <.. property.RepoObjectProperty_InheritanceType_InheritanceDefinition
property.RepoObjectProperty <.. property.PropertyName_RepoObject
property.RepoObjectProperty <.. property.RepoObjectProperty_SelectedPropertyName_split
property.RepoObjectProperty_external_src <.. property.RepoObjectProperty_external_tgt
property.RepoObjectProperty_external_tgt <.. property.RepoObjectProperty
property.RepoObjectProperty_SelectedPropertyName_split <.. reference.additional_Reference_wo_columns_from_properties_src
property.RepoObjectProperty_SelectedPropertyName_split <.. reference.additional_Reference_from_properties_src
reference.additional_Reference <.. reference.additional_Reference_is_external
reference.additional_Reference_from_properties_src <.. reference.additional_Reference_from_properties_tgt
reference.additional_Reference_from_properties_tgt <.. reference.additional_Reference
reference.additional_Reference_from_ssas_src <.. reference.additional_Reference_from_ssas_tgt
reference.additional_Reference_from_ssas_tgt <.. reference.additional_Reference
reference.additional_Reference_is_external <.. reference.additional_Reference_Object
reference.additional_Reference_Object <.. reference.additional_Reference_Object_T
reference.additional_Reference_Object_T <.. repo.RepoObject_external_src
reference.additional_Reference_wo_columns_from_properties_src <.. reference.additional_Reference_wo_columns_from_properties_tgt
reference.additional_Reference_wo_columns_from_properties_tgt <.. reference.additional_Reference
repo.RepoObject <.. property.RepoObjectProperty_external_tgt
repo.RepoObject <.. repo.RepoObject_external_src
repo.RepoObject <.. property.RepoObjectProperty_InheritanceType_InheritanceDefinition
repo.RepoObject_external_src <.. repo.RepoObject_external_tgt
repo.RepoObject_external_tgt <.. repo.RepoObject
repo.RepoObject_SSAS_src <.. repo.RepoObject_SSAS_tgt
repo.RepoObject_SSAS_tgt <.. repo.RepoObject
repo.RepoSchema <.. repo.RepoObject_SSAS_src
repo.RepoSchema_ssas_src <.. repo.RepoSchema_ssas_tgt
repo.RepoSchema_ssas_tgt <.. repo.RepoSchema
ssas.additional_Reference_step1 <.. reference.additional_Reference_from_ssas_src
ssas.model_json <.. ssas.model_json_10
ssas.model_json_10 <.. ssas.model_json_20
ssas.model_json_20 <.. repo.RepoSchema_ssas_src
ssas.model_json_20 <.. ssas.model_json_33_dataSources
ssas.model_json_20 <.. ssas.model_json_31_tables
ssas.model_json_20 <.. ssas.model_json_201_descriptions_multiline
ssas.model_json_201_descriptions_multiline <.. ssas.model_json_2011_descriptions_StrAgg
ssas.model_json_2011_descriptions_StrAgg <.. repo.RepoSchema_ssas_src
ssas.model_json_31_tables <.. ssas.model_json_31_tables_T
ssas.model_json_31_tables_T <.. ssas.model_json_313_tables_partitions
ssas.model_json_31_tables_T <.. ssas.model_json_311_tables_columns
ssas.model_json_31_tables_T <.. repo.RepoObject_SSAS_src
ssas.model_json_311_tables_columns <.. ssas.model_json_311_tables_columns_T
ssas.model_json_311_tables_columns_T <.. ssas.additional_Reference_step1
ssas.model_json_313_tables_partitions <.. ssas.model_json_3131_tables_partitions_source
ssas.model_json_3131_tables_partitions_source <.. ssas.model_json_31311_tables_partitions_source_PosFrom
ssas.model_json_31311_tables_partitions_source_PosFrom <.. ssas.model_json_313111_tables_partitions_source_StringFrom
ssas.model_json_313111_tables_partitions_source_StringFrom <.. ssas.model_json_3131111_tables_partitions_source_PosDot
ssas.model_json_3131111_tables_partitions_source_PosDot <.. ssas.model_json_31311111_tables_partitions_source_Part123
ssas.model_json_31311111_tables_partitions_source_Part123 <.. ssas.additional_Reference_step1
ssas.model_json_33_dataSources <.. ssas.model_json_33_dataSources_T
ssas.model_json_33_dataSources_T <.. ssas.additional_Reference_step1

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_30_0_objectref[]

=== PlantUML 0 30 ObjectRef

// tag::puml_entity_0_30_objectref[]
[plantuml, entity_0_30_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:property.repoobjectproperty_inheritancetype_inheritancedefinition.adoc[]" as property.RepoObjectProperty_InheritanceType_InheritanceDefinition << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty_inheritancetype_resulting_inheritancedefinition.adoc[]" as property.RepoObjectProperty_InheritanceType_resulting_InheritanceDefinition << V >> {
  --
}

entity "puml-link:dhw:sqldb:property.usp_repoobject_inheritance.adoc[]" as property.usp_RepoObject_Inheritance << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_main.adoc[]" as repo.usp_main << P >> {
  --
}

property.RepoObjectProperty_InheritanceType_InheritanceDefinition <.. property.RepoObjectProperty_InheritanceType_resulting_InheritanceDefinition
property.RepoObjectProperty_InheritanceType_resulting_InheritanceDefinition <.. property.usp_RepoObject_Inheritance
property.usp_RepoObject_Inheritance <.. repo.usp_main

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_0_30_objectref[]

=== PlantUML 1 1 ColumnRef

// tag::puml_entity_1_1_colref[]
[plantuml, entity_1_1_colref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:config.parameter.adoc[]" as config.Parameter << U >> {
  - **Parameter_name** : (varchar(100))
  - **sub_Parameter** : (nvarchar(128))
  Parameter_default_value : (nvarchar(max))
  Parameter_desciption : (nvarchar(1000))
  Parameter_value : (nvarchar(max))
  ~ Parameter_value_result : (nvarchar(max))
  ~ Parameter_value_result_date : (date)
  ~ Parameter_value_result_datetime : (datetime)
  ~ Parameter_value_result_int : (int)
  --
}

entity "puml-link:dhw:sqldb:property.propertyname_repoobject_t.adoc[]" as property.PropertyName_RepoObject_T << U >> {
  - **property_name** : (nvarchar(128))
  - has_inheritance : (bit)
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty.adoc[]" as property.RepoObjectProperty << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  inheritance : (tinyint)
  property_value : (nvarchar(max))
  - RepoObjectProperty_id : (int)
  ~ property_bigint : (bigint)
  ~ property_float : (float)
  ~ property_int : (int)
  ~ property_money : (money)
  ~ property_real : (real)
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty_inheritancetype_inheritancedefinition.adoc[]" as property.RepoObjectProperty_InheritanceType_InheritanceDefinition << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  Inheritance_Source_fullname : (nvarchar(261))
  Inheritance_StringAggSeparatorSql : (nvarchar(max))
  InheritanceDefinition : (nvarchar(max))
  InheritanceType : (int)
  par_Inheritance_StringAggSeparatorSql : (nvarchar(max))
  par_InheritanceDefintion : (nvarchar(max))
  par_InheritanceType : (int)
  property_value : (nvarchar(max))
  - RepoObject_fullname : (nvarchar(261))
  - RepoObject_type : (char(2))
  ro_Inheritance_StringAggSeparatorSql : (nvarchar(4000))
  ro_InheritanceDefinition : (nvarchar(4000))
  ro_InheritanceType : (tinyint)
  sub_Inheritance_StringAggSeparatorSql : (nvarchar(max))
  sub_InheritanceDefintion : (nvarchar(max))
  sub_InheritanceType : (int)
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty_inheritancetype_resulting_inheritancedefinition.adoc[]" as property.RepoObjectProperty_InheritanceType_resulting_InheritanceDefinition << V >> {
  Inheritance_Source_fullname : (nvarchar(261))
  Inheritance_StringAggSeparatorSql : (nvarchar(max))
  InheritanceDefinition : (nvarchar(max))
  InheritanceType : (int)
  - is_force_inherit_empty_source : (int)
  - is_StringAggAllSources : (int)
  - property_name : (nvarchar(128))
  property_value : (nvarchar(max))
  - RepoObject_fullname : (nvarchar(261))
  - RepoObject_guid : (uniqueidentifier)
  - RepoObject_type : (char(2))
  resulting_InheritanceDefinition : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject.adoc[]" as repo.RepoObject << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  external_AntoraComponent : (nvarchar(128))
  external_AntoraModule : (nvarchar(128))
  has_execution_plan_issue : (bit)
  has_get_referenced_issue : (bit)
  indent_sql_modules_definition : (tinyint)
  Inheritance_Source_fullname : (nvarchar(261))
  Inheritance_StringAggSeparatorSql : (nvarchar(4000))
  InheritanceDefinition : (nvarchar(4000))
  InheritanceType : (tinyint)
  - is_DocsExclude : (bit)
  - is_external : (bit)
  is_repo_managed : (bit)
  is_required_ObjectMerge : (bit)
  - is_ssas : (bit)
  is_SysObject_missing : (bit)
  - modify_dt : (datetime)
  pk_index_guid : (uniqueidentifier)
  pk_IndexPatternColumnName_new : (nvarchar(4000))
  Repo_history_table_guid : (uniqueidentifier)
  Repo_temporal_type : (tinyint)
  - RepoObject_name : (nvarchar(128))
  RepoObject_Referencing_Count : (int)
  - RepoObject_schema_name : (nvarchar(128))
  - RepoObject_type : (char(2))
  SysObject_id : (int)
  SysObject_modify_date : (datetime)
  - SysObject_name : (nvarchar(128))
  - SysObject_parent_object_id : (int)
  - SysObject_schema_name : (nvarchar(128))
  SysObject_type : (char(2))
  ~ has_different_sys_names : (bit)
  # is_RepoObject_name_uniqueidentifier : (int)
  # is_SysObject_name_uniqueidentifier : (int)
  ~ node_id : (bigint)
  # RepoObject_fullname : (nvarchar(261))
  # RepoObject_fullname2 : (nvarchar(257))
  # SysObject_fullname : (nvarchar(261))
  # SysObject_fullname2 : (nvarchar(257))
  ~ SysObject_query_sql : (nvarchar(406))
  ~ usp_persistence_fullname : (nvarchar(273))
  # usp_persistence_fullname2 : (nvarchar(269))
  # usp_persistence_name : (nvarchar(140))
  --
}

config.Parameter <.. property.RepoObjectProperty_InheritanceType_InheritanceDefinition
property.PropertyName_RepoObject_T <.. property.RepoObjectProperty_InheritanceType_InheritanceDefinition
property.RepoObjectProperty <.. property.RepoObjectProperty_InheritanceType_InheritanceDefinition
property.RepoObjectProperty_InheritanceType_InheritanceDefinition <.. property.RepoObjectProperty_InheritanceType_resulting_InheritanceDefinition
repo.RepoObject <.. property.RepoObjectProperty_InheritanceType_InheritanceDefinition
"config.Parameter::Parameter_value_result" <-- "property.RepoObjectProperty_InheritanceType_InheritanceDefinition::par_Inheritance_StringAggSeparatorSql"
"config.Parameter::Parameter_value_result" <-- "property.RepoObjectProperty_InheritanceType_InheritanceDefinition::sub_Inheritance_StringAggSeparatorSql"
"config.Parameter::Parameter_value_result" <-- "property.RepoObjectProperty_InheritanceType_InheritanceDefinition::sub_InheritanceDefintion"
"config.Parameter::Parameter_value_result" <-- "property.RepoObjectProperty_InheritanceType_InheritanceDefinition::par_InheritanceDefintion"
"config.Parameter::Parameter_value_result_int" <-- "property.RepoObjectProperty_InheritanceType_InheritanceDefinition::sub_InheritanceType"
"config.Parameter::Parameter_value_result_int" <-- "property.RepoObjectProperty_InheritanceType_InheritanceDefinition::par_InheritanceType"
"property.PropertyName_RepoObject_T::property_name" <-- "property.RepoObjectProperty_InheritanceType_InheritanceDefinition::property_name"
"property.RepoObjectProperty::property_value" <-- "property.RepoObjectProperty_InheritanceType_InheritanceDefinition::property_value"
"property.RepoObjectProperty_InheritanceType_InheritanceDefinition::Inheritance_Source_fullname" <-- "property.RepoObjectProperty_InheritanceType_resulting_InheritanceDefinition::Inheritance_Source_fullname"
"property.RepoObjectProperty_InheritanceType_InheritanceDefinition::Inheritance_StringAggSeparatorSql" <-- "property.RepoObjectProperty_InheritanceType_resulting_InheritanceDefinition::Inheritance_StringAggSeparatorSql"
"property.RepoObjectProperty_InheritanceType_InheritanceDefinition::InheritanceDefinition" <-- "property.RepoObjectProperty_InheritanceType_resulting_InheritanceDefinition::InheritanceDefinition"
"property.RepoObjectProperty_InheritanceType_InheritanceDefinition::InheritanceType" <-- "property.RepoObjectProperty_InheritanceType_resulting_InheritanceDefinition::InheritanceType"
"property.RepoObjectProperty_InheritanceType_InheritanceDefinition::property_name" <-- "property.RepoObjectProperty_InheritanceType_resulting_InheritanceDefinition::property_name"
"property.RepoObjectProperty_InheritanceType_InheritanceDefinition::property_value" <-- "property.RepoObjectProperty_InheritanceType_resulting_InheritanceDefinition::property_value"
"property.RepoObjectProperty_InheritanceType_InheritanceDefinition::RepoObject_fullname" <-- "property.RepoObjectProperty_InheritanceType_resulting_InheritanceDefinition::RepoObject_fullname"
"property.RepoObjectProperty_InheritanceType_InheritanceDefinition::RepoObject_guid" <-- "property.RepoObjectProperty_InheritanceType_resulting_InheritanceDefinition::RepoObject_guid"
"property.RepoObjectProperty_InheritanceType_InheritanceDefinition::RepoObject_type" <-- "property.RepoObjectProperty_InheritanceType_resulting_InheritanceDefinition::RepoObject_type"
"repo.RepoObject::Inheritance_Source_fullname" <-- "property.RepoObjectProperty_InheritanceType_InheritanceDefinition::Inheritance_Source_fullname"
"repo.RepoObject::Inheritance_StringAggSeparatorSql" <-- "property.RepoObjectProperty_InheritanceType_InheritanceDefinition::Inheritance_StringAggSeparatorSql"
"repo.RepoObject::Inheritance_StringAggSeparatorSql" <-- "property.RepoObjectProperty_InheritanceType_InheritanceDefinition::ro_Inheritance_StringAggSeparatorSql"
"repo.RepoObject::InheritanceDefinition" <-- "property.RepoObjectProperty_InheritanceType_InheritanceDefinition::ro_InheritanceDefinition"
"repo.RepoObject::InheritanceType" <-- "property.RepoObjectProperty_InheritanceType_InheritanceDefinition::InheritanceType"
"repo.RepoObject::InheritanceType" <-- "property.RepoObjectProperty_InheritanceType_InheritanceDefinition::ro_InheritanceType"
"repo.RepoObject::RepoObject_fullname" <-- "property.RepoObjectProperty_InheritanceType_InheritanceDefinition::RepoObject_fullname"
"repo.RepoObject::RepoObject_guid" <-- "property.RepoObjectProperty_InheritanceType_InheritanceDefinition::RepoObject_guid"
"repo.RepoObject::RepoObject_type" <-- "property.RepoObjectProperty_InheritanceType_InheritanceDefinition::RepoObject_type"

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_colref[]


== sql_modules_definition

// tag::sql_modules_definition[]
[%collapsible]
=======
[source,sql,numbered,indent=0]
----

CREATE View property.RepoObjectProperty_InheritanceType_InheritanceDefinition
As
Select
    --
    ro.RepoObject_guid
  , pn.property_name
  , rop.property_value
  , Inheritance_StringAggSeparatorSql     = Coalesce (
                                                         ro.Inheritance_StringAggSeparatorSql
                                                       , par_sub_sep.Parameter_value_result
                                                       , par_sep.Parameter_value_result
                                                     )
  , InheritanceDefinition                 = Coalesce (
                                                         ro.InheritanceDefinition
                                                       , par_sub_def.Parameter_value_result
                                                       , par_def.Parameter_value_result
                                                     )
  , ro.Inheritance_Source_fullname
  , InheritanceType                       = Coalesce ( ro.InheritanceType, par_sub.Parameter_value_result_int, par.Parameter_value_result_int )
  , ro.RepoObject_fullname
  , ro.RepoObject_type
  , ro_InheritanceType                    = ro.InheritanceType
  , sub_InheritanceType                   = par_sub.Parameter_value_result_int
  , par_InheritanceType                   = par.Parameter_value_result_int
  , ro_InheritanceDefinition              = ro.InheritanceDefinition
  , sub_InheritanceDefintion              = par_sub_def.Parameter_value_result
  , par_InheritanceDefintion              = par_def.Parameter_value_result
  , ro_Inheritance_StringAggSeparatorSql  = ro.Inheritance_StringAggSeparatorSql
  , sub_Inheritance_StringAggSeparatorSql = par_sub_sep.Parameter_value_result
  , par_Inheritance_StringAggSeparatorSql = par_sep.Parameter_value_result
From
    repo.RepoObject                               As ro
    Cross Join property.PropertyName_RepoObject_T As pn
    Left Join
        property.RepoObjectProperty As rop
            On
            rop.RepoObject_guid           = ro.RepoObject_guid
            And rop.property_name         = pn.property_name

    Left Join
        config.Parameter            As par_sub
            On
            par_sub.Parameter_name        = 'InheritanceType_object'
            And par_sub.sub_Parameter     = pn.property_name

    Left Join
        config.Parameter            As par
            On
            par.Parameter_name            = 'InheritanceType_object'
            And par.sub_Parameter         = ''

    Left Join
        config.Parameter            As par_sub_def
            On
            par_sub_def.Parameter_name    = 'InheritanceDefinition_object'
            And par_sub_def.sub_Parameter = pn.property_name

    Left Join
        config.Parameter            As par_def
            On
            par_def.Parameter_name        = 'InheritanceDefinition_object'
            And par_def.sub_Parameter     = ''

    Left Join
        config.Parameter            As par_sub_sep
            On
            par_sub_sep.Parameter_name    = 'Inheritance_StringAggSeparatorSql_object'
            And par_sub_sep.sub_Parameter = pn.property_name

    Left Join
        config.Parameter            As par_sep
            On
            par_sep.Parameter_name        = 'Inheritance_StringAggSeparatorSql_object'
            And par_sep.sub_Parameter     = ''
Where
    pn.has_inheritance = 1

----
=======
// end::sql_modules_definition[]


