// tag::HeaderFullDisplayName[]
= reference.RepoObject_ReferenceTree - U
// end::HeaderFullDisplayName[]

== existing_properties

// tag::existing_properties[]

:ExistsProperty--antorareferencinglist:
:ExistsProperty--has_get_referenced_issue:
:ExistsProperty--is_repo_managed:
:ExistsProperty--is_ssas:
:ExistsProperty--pk_index_guid:
:ExistsProperty--pk_indexpatterncolumndatatype:
:ExistsProperty--pk_indexpatterncolumnname:
:ExistsProperty--referencedobjectlist:
:ExistsProperty--FK:
:ExistsProperty--AntoraIndexList:
:ExistsProperty--Columns:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
0BDF2FE1-AE7A-EB11-84E5-A81E8446D5B0
// end::RepoObject_guid[]

== RepoObject_FullDisplayName2

// tag::RepoObject_FullDisplayName2[]
reference.RepoObject_ReferenceTree
// end::RepoObject_FullDisplayName2[]

== SysObject_type

// tag::SysObject_type[]
U 
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
user table
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
179531723
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2022-01-23 14:10:15
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]
[discrete]
== _


[#column-repoobjectunderlineguid]
=== RepoObject_guid

[cols="d,8a,m,m,m"]
|===
|1
|*RepoObject_guid*
|uniqueidentifier
|NOT NULL
|
|===

.has_get_referenced_issue
....
1
....

.Referencing Columns
--
* xref:reference.repoobject_referencetree_cyclic.adoc#column-repoobjectunderlineguid[+reference.RepoObject_ReferenceTree_cyclic.RepoObject_guid+]
--


[#column-referencedunderlinedepth]
=== Referenced_Depth

[cols="d,8a,m,m,m"]
|===
|2
|*Referenced_Depth*
|int
|NULL
|
|===

.has_get_referenced_issue
....
1
....

.Referencing Columns
--
* xref:reference.repoobject_referencetree_cyclic.adoc#column-referencedunderlinedepthunderline30underline0[+reference.RepoObject_ReferenceTree_cyclic.Referenced_Depth_30_0+]
* xref:reference.repoobject_referencetree_cyclic.adoc#column-referencedunderlinedepthunderline0underline30[+reference.RepoObject_ReferenceTree_cyclic.Referenced_Depth_0_30+]
--


[#column-referencingunderlinedepth]
=== Referencing_Depth

[cols="d,8a,m,m,m"]
|===
|3
|*Referencing_Depth*
|int
|NULL
|
|===

.has_get_referenced_issue
....
1
....

.Referencing Columns
--
* xref:reference.repoobject_referencetree_cyclic.adoc#column-referencingunderlinedepthunderline30underline0[+reference.RepoObject_ReferenceTree_cyclic.Referencing_Depth_30_0+]
* xref:reference.repoobject_referencetree_cyclic.adoc#column-referencingunderlinedepthunderline0underline30[+reference.RepoObject_ReferenceTree_cyclic.Referencing_Depth_0_30+]
--


[#column-referencedunderlineguid]
=== Referenced_guid

[cols="d,8a,m,m,m"]
|===
|4
|*Referenced_guid*
|uniqueidentifier
|NOT NULL
|
|===

.has_get_referenced_issue
....
1
....

.Referencing Columns
--
* xref:reference.repoobject_referencetree_cyclic.adoc#column-referencedunderlineguid[+reference.RepoObject_ReferenceTree_cyclic.Referenced_guid+]
--


[#column-referencingunderlineguid]
=== Referencing_guid

[cols="d,8a,m,m,m"]
|===
|5
|*Referencing_guid*
|uniqueidentifier
|NOT NULL
|
|===

.has_get_referenced_issue
....
1
....

.Referencing Columns
--
* xref:reference.repoobject_referencetree_cyclic.adoc#column-referencingunderlineguid[+reference.RepoObject_ReferenceTree_cyclic.Referencing_guid+]
--


[#column-referencedunderlinefullname]
=== Referenced_fullname

[cols="d,8a,m,m,m"]
|===
|
|Referenced_fullname
|nvarchar(261)
|NULL
|
|===

.has_get_referenced_issue
....
1
....

.Referencing Columns
--
* xref:reference.repoobject_referencetree_cyclic.adoc#column-referencedunderlinefullname[+reference.RepoObject_ReferenceTree_cyclic.Referenced_fullname+]
--


[#column-referencedunderlinefullname2]
=== Referenced_fullname2

[cols="d,8a,m,m,m"]
|===
|
|Referenced_fullname2
|nvarchar(257)
|NULL
|
|===

.has_get_referenced_issue
....
1
....

.Referencing Columns
--
* xref:reference.repoobject_referencetree_cyclic.adoc#column-referencedunderlinefullname2[+reference.RepoObject_ReferenceTree_cyclic.Referenced_fullname2+]
--


[#column-referencedunderlinetype]
=== Referenced_type

[cols="d,8a,m,m,m"]
|===
|
|Referenced_type
|char(2)
|NULL
|
|===

.has_get_referenced_issue
....
1
....

.Referencing Columns
--
* xref:reference.repoobject_referencetree_cyclic.adoc#column-referencedunderlinetype[+reference.RepoObject_ReferenceTree_cyclic.Referenced_type+]
--


[#column-referencingunderlinefullname]
=== Referencing_fullname

[cols="d,8a,m,m,m"]
|===
|
|Referencing_fullname
|nvarchar(261)
|NULL
|
|===

.has_get_referenced_issue
....
1
....

.Referencing Columns
--
* xref:reference.repoobject_referencetree_cyclic.adoc#column-referencingunderlinefullname[+reference.RepoObject_ReferenceTree_cyclic.referencing_fullname+]
--


[#column-referencingunderlinefullname2]
=== Referencing_fullname2

[cols="d,8a,m,m,m"]
|===
|
|Referencing_fullname2
|nvarchar(257)
|NULL
|
|===

.has_get_referenced_issue
....
1
....

.Referencing Columns
--
* xref:reference.repoobject_referencetree_cyclic.adoc#column-referencingunderlinefullname2[+reference.RepoObject_ReferenceTree_cyclic.referencing_fullname2+]
--


[#column-referencingunderlinetype]
=== Referencing_type

[cols="d,8a,m,m,m"]
|===
|
|Referencing_type
|varchar(2)
|NULL
|
|===

.has_get_referenced_issue
....
1
....

.Referencing Columns
--
* xref:reference.repoobject_referencetree_cyclic.adoc#column-referencingunderlinetype[+reference.RepoObject_ReferenceTree_cyclic.referencing_type+]
--


// end::AntoraColumnDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]
|1
|*<<column-repoobjectunderlineguid>>*
|uniqueidentifier
|NOT NULL
|

|2
|*<<column-referencedunderlinedepth>>*
|int
|NULL
|

|3
|*<<column-referencingunderlinedepth>>*
|int
|NULL
|

|4
|*<<column-referencedunderlineguid>>*
|uniqueidentifier
|NOT NULL
|

|5
|*<<column-referencingunderlineguid>>*
|uniqueidentifier
|NOT NULL
|







// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]





|
|<<column-referencedunderlinefullname>>
|nvarchar(261)
|NULL
|

|
|<<column-referencedunderlinefullname2>>
|nvarchar(257)
|NULL
|

|
|<<column-referencedunderlinetype>>
|char(2)
|NULL
|

|
|<<column-referencingunderlinefullname>>
|nvarchar(261)
|NULL
|

|
|<<column-referencingunderlinefullname2>>
|nvarchar(257)
|NULL
|

|
|<<column-referencingunderlinetype>>
|varchar(2)
|NULL
|

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

[#index-pkunderlinerepoobjectunderlinereferencetree]
=== PK_RepoObject_ReferenceTree

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-RepoObject_guid>>; uniqueidentifier
* <<column-Referenced_Depth>>; int
* <<column-Referencing_Depth>>; int
* <<column-Referenced_guid>>; uniqueidentifier
* <<column-Referencing_guid>>; uniqueidentifier
--
* PK, Unique, Real: 1, 1, 0

// end::AntoraIndexList[]

== AntoraMeasureDetails

// tag::AntoraMeasureDetails[]

// end::AntoraMeasureDetails[]

== AntoraMeasureDescriptions



== AntoraParameterList

// tag::AntoraParameterList[]

// end::AntoraParameterList[]

== AntoraXrefCulturesList

// tag::AntoraXrefCulturesList[]
* xref:dhw:sqldb:reference.repoobject_referencetree.adoc[] - 
// end::AntoraXrefCulturesList[]

== cultures_count

// tag::cultures_count[]
1
// end::cultures_count[]

== Other tags

source: property.RepoObjectProperty_cross As rop_cross


=== additional_reference_csv

// tag::additional_reference_csv[]

// end::additional_reference_csv[]


=== AdocUspSteps

// tag::adocuspsteps[]

// end::adocuspsteps[]


=== AntoraReferencedList

// tag::antorareferencedlist[]

// end::antorareferencedlist[]


=== AntoraReferencingList

// tag::antorareferencinglist[]
* xref:dhw:sqldb:docs.ftv_repoobject_reference_plantuml_entityreflist.adoc[]
* xref:dhw:sqldb:docs.repoobject_plantuml_objectreflist_0_30.adoc[]
* xref:dhw:sqldb:docs.repoobject_plantuml_objectreflist_30_0.adoc[]
* xref:dhw:sqldb:reference.persistence.adoc[]
* xref:dhw:sqldb:reference.repoobject_referencetree_cyclic.adoc[]
* xref:dhw:sqldb:reference.usp_repoobject_referencetree_insert.adoc[]
// end::antorareferencinglist[]


=== Description

// tag::description[]

// end::description[]


=== exampleUsage

// tag::exampleusage[]

// end::exampleusage[]


=== exampleUsage_2

// tag::exampleusage_2[]

// end::exampleusage_2[]


=== exampleUsage_3

// tag::exampleusage_3[]

// end::exampleusage_3[]


=== exampleUsage_4

// tag::exampleusage_4[]

// end::exampleusage_4[]


=== exampleUsage_5

// tag::exampleusage_5[]

// end::exampleusage_5[]


=== exampleWrong_Usage

// tag::examplewrong_usage[]

// end::examplewrong_usage[]


=== has_execution_plan_issue

// tag::has_execution_plan_issue[]

// end::has_execution_plan_issue[]


=== has_get_referenced_issue

// tag::has_get_referenced_issue[]
1
// end::has_get_referenced_issue[]


=== has_history

// tag::has_history[]

// end::has_history[]


=== has_history_columns

// tag::has_history_columns[]

// end::has_history_columns[]


=== InheritanceType

// tag::inheritancetype[]

// end::inheritancetype[]


=== is_persistence

// tag::is_persistence[]

// end::is_persistence[]


=== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]

// end::is_persistence_check_duplicate_per_pk[]


=== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]

// end::is_persistence_check_for_empty_source[]


=== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]

// end::is_persistence_delete_changed[]


=== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]

// end::is_persistence_delete_missing[]


=== is_persistence_insert

// tag::is_persistence_insert[]

// end::is_persistence_insert[]


=== is_persistence_truncate

// tag::is_persistence_truncate[]

// end::is_persistence_truncate[]


=== is_persistence_update_changed

// tag::is_persistence_update_changed[]

// end::is_persistence_update_changed[]


=== is_repo_managed

// tag::is_repo_managed[]
0
// end::is_repo_managed[]


=== is_ssas

// tag::is_ssas[]
0
// end::is_ssas[]


=== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


=== MS_Description

// tag::ms_description[]

// end::ms_description[]


=== persistence_source_RepoObject_fullname

// tag::persistence_source_repoobject_fullname[]

// end::persistence_source_repoobject_fullname[]


=== persistence_source_RepoObject_fullname2

// tag::persistence_source_repoobject_fullname2[]

// end::persistence_source_repoobject_fullname2[]


=== persistence_source_RepoObject_guid

// tag::persistence_source_repoobject_guid[]

// end::persistence_source_repoobject_guid[]


=== persistence_source_RepoObject_xref

// tag::persistence_source_repoobject_xref[]

// end::persistence_source_repoobject_xref[]


=== pk_index_guid

// tag::pk_index_guid[]
751AFAF0-0E96-EB11-84F4-A81E8446D5B0
// end::pk_index_guid[]


=== pk_IndexPatternColumnDatatype

// tag::pk_indexpatterncolumndatatype[]
uniqueidentifier,int,int,uniqueidentifier,uniqueidentifier
// end::pk_indexpatterncolumndatatype[]


=== pk_IndexPatternColumnName

// tag::pk_indexpatterncolumnname[]
RepoObject_guid,Referenced_Depth,Referencing_Depth,Referenced_guid,Referencing_guid
// end::pk_indexpatterncolumnname[]


=== pk_IndexSemanticGroup

// tag::pk_indexsemanticgroup[]

// end::pk_indexsemanticgroup[]


=== ReferencedObjectList

// tag::referencedobjectlist[]
* [reference].[ftv_RepoObject_ReferenceTree]
* [repo].[RepoObject_gross]
// end::referencedobjectlist[]


=== usp_persistence_RepoObject_guid

// tag::usp_persistence_repoobject_guid[]

// end::usp_persistence_repoobject_guid[]


=== UspExamples

// tag::uspexamples[]

// end::uspexamples[]


=== uspgenerator_usp_id

// tag::uspgenerator_usp_id[]

// end::uspgenerator_usp_id[]


=== UspParameters

// tag::uspparameters[]

// end::uspparameters[]

== Boolean Attributes

source: property.RepoObjectProperty WHERE property_int = 1

// tag::boolean_attributes[]

:has_get_referenced_issue:

// end::boolean_attributes[]

== PlantUML diagrams

=== PlantUML Entity

// tag::puml_entity[]
[plantuml, entity-{docname}, svg, subs=macros]
....
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:reference.repoobject_referencetree.adoc[]" as reference.RepoObject_ReferenceTree << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  **Referenced_Depth** : (int)
  **Referencing_Depth** : (int)
  - **Referenced_guid** : (uniqueidentifier)
  - **Referencing_guid** : (uniqueidentifier)
  Referenced_fullname : (nvarchar(261))
  Referenced_fullname2 : (nvarchar(257))
  Referenced_type : (char(2))
  Referencing_fullname : (nvarchar(261))
  Referencing_fullname2 : (nvarchar(257))
  Referencing_type : (varchar(2))
  --
}
....

// end::puml_entity[]

=== PlantUML Entity 1 1 FK

// tag::puml_entity_1_1_fk[]
[plantuml, entity_1_1_fk-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:reference.repoobject_referencetree.adoc[]" as reference.RepoObject_ReferenceTree << U >> {
- **PK_RepoObject_ReferenceTree**

..
RepoObject_guid; uniqueidentifier
Referenced_Depth; int
Referencing_Depth; int
Referenced_guid; uniqueidentifier
Referencing_guid; uniqueidentifier
}



footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_fk[]

=== PlantUML 1 1 ObjectRef

// tag::puml_entity_1_1_objectref[]
[plantuml, entity_1_1_objectref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:docs.ftv_repoobject_reference_plantuml_entityreflist.adoc[]" as docs.ftv_RepoObject_Reference_PlantUml_EntityRefList << IF >> {
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_objectreflist_0_30.adoc[]" as docs.RepoObject_Plantuml_ObjectRefList_0_30 << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_objectreflist_30_0.adoc[]" as docs.RepoObject_Plantuml_ObjectRefList_30_0 << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.persistence.adoc[]" as reference.Persistence << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_referencetree.adoc[]" as reference.RepoObject_ReferenceTree << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  **Referenced_Depth** : (int)
  **Referencing_Depth** : (int)
  - **Referenced_guid** : (uniqueidentifier)
  - **Referencing_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_referencetree_cyclic.adoc[]" as reference.RepoObject_ReferenceTree_cyclic << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_repoobject_referencetree_insert.adoc[]" as reference.usp_RepoObject_ReferenceTree_insert << P >> {
  --
}

reference.RepoObject_ReferenceTree <.. docs.ftv_RepoObject_Reference_PlantUml_EntityRefList
reference.RepoObject_ReferenceTree <.. docs.RepoObject_Plantuml_ObjectRefList_0_30
reference.RepoObject_ReferenceTree <.. docs.RepoObject_Plantuml_ObjectRefList_30_0
reference.RepoObject_ReferenceTree <.. reference.Persistence
reference.RepoObject_ReferenceTree <.. reference.RepoObject_ReferenceTree_cyclic
reference.RepoObject_ReferenceTree <.. reference.usp_RepoObject_ReferenceTree_insert

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_objectref[]

=== PlantUML 30 0 ObjectRef

// tag::puml_entity_30_0_objectref[]
[plantuml, entity_30_0_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:reference.repoobject_referencetree.adoc[]" as reference.RepoObject_ReferenceTree << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  **Referenced_Depth** : (int)
  **Referencing_Depth** : (int)
  - **Referenced_guid** : (uniqueidentifier)
  - **Referencing_guid** : (uniqueidentifier)
  --
}



footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_30_0_objectref[]

=== PlantUML 0 30 ObjectRef

// tag::puml_entity_0_30_objectref[]
[plantuml, entity_0_30_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:docs.ftv_repoobject_reference_plantuml_entityreflist.adoc[]" as docs.ftv_RepoObject_Reference_PlantUml_EntityRefList << IF >> {
  --
}

entity "puml-link:dhw:sqldb:docs.objectrefcyclic.adoc[]" as docs.ObjectRefCyclic << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.objectrefcyclic_entitylist.adoc[]" as docs.ObjectRefCyclic_EntityList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.objectrefcyclic_objectreflist.adoc[]" as docs.ObjectRefCyclic_ObjectRefList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_adoc.adoc[]" as docs.RepoObject_Adoc << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_adoc_t.adoc[]" as docs.RepoObject_Adoc_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml.adoc[]" as docs.RepoObject_Plantuml << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_objectreflist_0_30.adoc[]" as docs.RepoObject_Plantuml_ObjectRefList_0_30 << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_objectreflist_30_0.adoc[]" as docs.RepoObject_Plantuml_ObjectRefList_30_0 << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_t.adoc[]" as docs.RepoObject_Plantuml_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport.adoc[]" as docs.usp_AntoraExport << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_objectpartialscontent.adoc[]" as docs.usp_AntoraExport_ObjectPartialsContent << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_objectpuml.adoc[]" as docs.usp_AntoraExport_ObjectPuml << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_repoobject_adoc_t.adoc[]" as docs.usp_PERSIST_RepoObject_Adoc_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_repoobject_plantuml_t.adoc[]" as docs.usp_PERSIST_RepoObject_Plantuml_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.persistence.adoc[]" as reference.Persistence << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.persistence_bidirectional.adoc[]" as reference.Persistence_bidirectional << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.referencetree_cyclic_ref_persistenceusp.adoc[]" as reference.ReferenceTree_cyclic_ref_PersistenceUsp << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.referencetree_cyclic_ref_primary.adoc[]" as reference.ReferenceTree_cyclic_ref_primary << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.referencetree_cyclic_union.adoc[]" as reference.ReferenceTree_cyclic_union << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_referencetree.adoc[]" as reference.RepoObject_ReferenceTree << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  **Referenced_Depth** : (int)
  **Referencing_Depth** : (int)
  - **Referenced_guid** : (uniqueidentifier)
  - **Referencing_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_referencetree_cyclic.adoc[]" as reference.RepoObject_ReferenceTree_cyclic << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_repoobject_referencetree_insert.adoc[]" as reference.usp_RepoObject_ReferenceTree_insert << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_main.adoc[]" as repo.usp_main << P >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.biml_package.adoc[]" as workflow.Biml_Package << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.biml_precedenceconstraints.adoc[]" as workflow.Biml_PrecedenceConstraints << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.biml_project.adoc[]" as workflow.Biml_Project << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.biml_task.adoc[]" as workflow.Biml_Task << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.proceduredependency.adoc[]" as workflow.ProcedureDependency << U >> {
  - **id** : (int)
  --
}

entity "puml-link:dhw:sqldb:workflow.proceduredependency_gross.adoc[]" as workflow.ProcedureDependency_gross << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.proceduredependency_input_persistencedependency.adoc[]" as workflow.ProcedureDependency_input_PersistenceDependency << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.proceduredependency_input_persistencedependency_s.adoc[]" as workflow.ProcedureDependency_input_PersistenceDependency_S << V >> {
  **referenced_Procedure_RepoObject_guid** : (uniqueidentifier)
  **referencing_Procedure_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:workflow.proceduredependency_persistencedependency_src.adoc[]" as workflow.ProcedureDependency_PersistenceDependency_src << V >> {
  **referenced_Procedure_RepoObject_guid** : (uniqueidentifier)
  **referencing_Procedure_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:workflow.proceduredependency_persistencedependency_tgt.adoc[]" as workflow.ProcedureDependency_PersistenceDependency_tgt << V >> {
  **referenced_Procedure_RepoObject_guid** : (uniqueidentifier)
  **referencing_Procedure_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:workflow.usp_persist_proceduredependency_persistencedependency_tgt.adoc[]" as workflow.usp_PERSIST_ProcedureDependency_PersistenceDependency_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.usp_persist_workflow_proceduredependency_t.adoc[]" as workflow.usp_PERSIST_Workflow_ProcedureDependency_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.usp_workflow.adoc[]" as workflow.usp_workflow << P >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.workflow_proceduredependency.adoc[]" as workflow.Workflow_ProcedureDependency << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.workflow_proceduredependency_all.adoc[]" as workflow.Workflow_ProcedureDependency_all << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.workflow_proceduredependency_t.adoc[]" as workflow.Workflow_ProcedureDependency_T << U >> {
  - **Workflow_id** : (int)
  - **referenced_Procedure_RepoObject_guid** : (uniqueidentifier)
  - **referencing_Procedure_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:workflow.workflow_proceduredependency_t_active.adoc[]" as workflow.Workflow_ProcedureDependency_T_active << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.workflow_proceduredependency_t_bidirectional.adoc[]" as workflow.Workflow_ProcedureDependency_T_bidirectional << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.workflow_proceduredependency_t_bidirectional_t.adoc[]" as workflow.Workflow_ProcedureDependency_T_bidirectional_T << U >> {
  - **Workflow_id** : (int)
  - **referenced_Procedure_RepoObject_guid** : (uniqueidentifier)
  - **referencing_Procedure_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:workflow.workflow_proceduredependency_t_notinsortorder.adoc[]" as workflow.Workflow_ProcedureDependency_T_NotInSortorder << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.workflow_proceduredependency_t_notinsortorder_check.adoc[]" as workflow.Workflow_ProcedureDependency_T_NotInSortorder_check << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.workflow_proceduredependency_t_redundant.adoc[]" as workflow.Workflow_ProcedureDependency_T_redundant << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.workflow_proceduredependency_t_taskname.adoc[]" as workflow.Workflow_ProcedureDependency_T_TaskName << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.workflow_proceduredependency_wo_redundant.adoc[]" as workflow.Workflow_ProcedureDependency_wo_redundant << V >> {
  --
}

docs.ftv_RepoObject_Reference_PlantUml_EntityRefList <.. docs.RepoObject_Plantuml
docs.ObjectRefCyclic_EntityList <.. docs.ObjectRefCyclic
docs.ObjectRefCyclic_ObjectRefList <.. docs.ObjectRefCyclic
docs.RepoObject_Adoc <.. docs.usp_PERSIST_RepoObject_Adoc_T
docs.RepoObject_Adoc <.. docs.RepoObject_Adoc_T
docs.REpoObject_Adoc_T <.. docs.usp_PERSIST_RepoObject_Adoc_T
docs.RepoObject_Plantuml <.. docs.RepoObject_Plantuml_T
docs.RepoObject_Plantuml <.. docs.usp_PERSIST_RepoObject_Plantuml_T
docs.RepoObject_Plantuml_ObjectRefList_0_30 <.. docs.RepoObject_Plantuml
docs.RepoObject_Plantuml_ObjectRefList_30_0 <.. docs.RepoObject_Plantuml
docs.RepoObject_Plantuml_T <.. docs.usp_PERSIST_RepoObject_Plantuml_T
docs.RepoObject_Plantuml_T <.. docs.RepoObject_Adoc
docs.usp_AntoraExport_ObjectPartialsContent <.. docs.usp_AntoraExport
docs.usp_AntoraExport_ObjectPuml <.. docs.usp_AntoraExport
docs.usp_PERSIST_RepoObject_Adoc_T <.. docs.usp_AntoraExport_ObjectPartialsContent
docs.usp_PERSIST_RepoObject_Plantuml_T <.. docs.usp_AntoraExport_ObjectPuml
reference.Persistence <.. workflow.ProcedureDependency_PersistenceDependency_src
reference.Persistence <.. workflow.ProcedureDependency_input_PersistenceDependency_S
reference.Persistence <.. reference.Persistence_bidirectional
reference.ReferenceTree_cyclic_ref_PersistenceUsp <.. reference.ReferenceTree_cyclic_union
reference.ReferenceTree_cyclic_ref_primary <.. reference.ReferenceTree_cyclic_union
reference.ReferenceTree_cyclic_ref_primary <.. reference.ReferenceTree_cyclic_ref_PersistenceUsp
reference.ReferenceTree_cyclic_union <.. docs.ObjectRefCyclic_ObjectRefList
reference.ReferenceTree_cyclic_union <.. docs.ObjectRefCyclic_EntityList
reference.RepoObject_ReferenceTree <.. docs.ftv_RepoObject_Reference_PlantUml_EntityRefList
reference.RepoObject_ReferenceTree <.. docs.RepoObject_Plantuml_ObjectRefList_0_30
reference.RepoObject_ReferenceTree <.. docs.RepoObject_Plantuml_ObjectRefList_30_0
reference.RepoObject_ReferenceTree <.. reference.Persistence
reference.RepoObject_ReferenceTree <.. reference.RepoObject_ReferenceTree_cyclic
reference.RepoObject_ReferenceTree <.. reference.usp_RepoObject_ReferenceTree_insert
reference.RepoObject_ReferenceTree_cyclic <.. reference.ReferenceTree_cyclic_ref_primary
reference.usp_RepoObject_ReferenceTree_insert <.. repo.usp_main
workflow.Biml_Package <.. workflow.Biml_Project
workflow.Biml_PrecedenceConstraints <.. workflow.Biml_Task
workflow.Biml_Task <.. workflow.Biml_Package
workflow.ProcedureDependency <.. workflow.ProcedureDependency_gross
workflow.ProcedureDependency <.. workflow.ProcedureDependency_input_PersistenceDependency
workflow.ProcedureDependency <.. workflow.Workflow_ProcedureDependency_all
workflow.ProcedureDependency <.. workflow.Workflow_ProcedureDependency
workflow.ProcedureDependency_PersistenceDependency_src <.. workflow.ProcedureDependency_PersistenceDependency_tgt
workflow.ProcedureDependency_PersistenceDependency_src <.. workflow.usp_PERSIST_ProcedureDependency_PersistenceDependency_tgt
workflow.ProcedureDependency_PersistenceDependency_tgt <.. workflow.ProcedureDependency
workflow.ProcedureDependency_PersistenceDependency_tgt <.. workflow.usp_PERSIST_ProcedureDependency_PersistenceDependency_tgt
workflow.usp_PERSIST_ProcedureDependency_PersistenceDependency_tgt <.. workflow.usp_workflow
workflow.usp_PERSIST_Workflow_ProcedureDependency_T <.. workflow.usp_workflow
workflow.Workflow_ProcedureDependency <.. workflow.Workflow_ProcedureDependency_T
workflow.Workflow_ProcedureDependency <.. workflow.usp_PERSIST_Workflow_ProcedureDependency_T
workflow.Workflow_ProcedureDependency_all <.. workflow.Workflow_ProcedureDependency_wo_redundant
workflow.Workflow_ProcedureDependency_T <.. workflow.usp_workflow
workflow.Workflow_ProcedureDependency_T <.. workflow.Workflow_ProcedureDependency_T_bidirectional
workflow.Workflow_ProcedureDependency_T <.. workflow.usp_PERSIST_Workflow_ProcedureDependency_T
workflow.Workflow_ProcedureDependency_T <.. workflow.Workflow_ProcedureDependency_T_active
workflow.Workflow_ProcedureDependency_T_active <.. workflow.Workflow_ProcedureDependency_T_TaskName
workflow.Workflow_ProcedureDependency_T_active <.. workflow.Workflow_ProcedureDependency_T_NotInSortorder
workflow.Workflow_ProcedureDependency_T_active <.. workflow.Workflow_ProcedureDependency_T_redundant
workflow.Workflow_ProcedureDependency_T_bidirectional <.. workflow.usp_workflow
workflow.Workflow_ProcedureDependency_T_bidirectional <.. workflow.Workflow_ProcedureDependency_T_bidirectional_T
workflow.Workflow_ProcedureDependency_T_NotInSortorder <.. workflow.usp_workflow
workflow.Workflow_ProcedureDependency_T_NotInSortorder <.. workflow.Workflow_ProcedureDependency_T_NotInSortorder_check
workflow.Workflow_ProcedureDependency_T_NotInSortorder_check <.. workflow.usp_workflow
workflow.Workflow_ProcedureDependency_T_redundant <.. workflow.Workflow_ProcedureDependency_wo_redundant
workflow.Workflow_ProcedureDependency_T_redundant <.. workflow.usp_workflow
workflow.Workflow_ProcedureDependency_T_TaskName <.. workflow.Biml_PrecedenceConstraints

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_0_30_objectref[]

=== PlantUML 1 1 ColumnRef

// tag::puml_entity_1_1_colref[]
[plantuml, entity_1_1_colref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:docs.ftv_repoobject_reference_plantuml_entityreflist.adoc[]" as docs.ftv_RepoObject_Reference_PlantUml_EntityRefList << IF >> {
  PumlEntityList : (nvarchar(max))
  PumlEntityOnlyPkList : (nvarchar(max))
  Referenced_Depth : (int)
  Referencing_Depth : (int)
  ro_guid : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_objectreflist_0_30.adoc[]" as docs.RepoObject_Plantuml_ObjectRefList_0_30 << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  ObjectRefList : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_objectreflist_30_0.adoc[]" as docs.RepoObject_Plantuml_ObjectRefList_30_0 << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  ObjectRefList : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:reference.persistence.adoc[]" as reference.Persistence << V >> {
  referenced_fullname : (nvarchar(261))
  referenced_RepoObject_guid : (uniqueidentifier)
  referenced_schema_name : (nvarchar(128))
  referenced_usp_persistence_name : (nvarchar(140))
  referenced_usp_persistence_RepoObject_guid : (uniqueidentifier)
  referencing_fullname : (nvarchar(261))
  referencing_RepoObject_guid : (uniqueidentifier)
  referencing_schema_name : (nvarchar(128))
  referencing_usp_persistence_name : (nvarchar(140))
  referencing_usp_persistence_RepoObject_guid : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_referencetree.adoc[]" as reference.RepoObject_ReferenceTree << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  **Referenced_Depth** : (int)
  **Referencing_Depth** : (int)
  - **Referenced_guid** : (uniqueidentifier)
  - **Referencing_guid** : (uniqueidentifier)
  Referenced_fullname : (nvarchar(261))
  Referenced_fullname2 : (nvarchar(257))
  Referenced_type : (char(2))
  Referencing_fullname : (nvarchar(261))
  Referencing_fullname2 : (nvarchar(257))
  Referencing_type : (varchar(2))
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_referencetree_cyclic.adoc[]" as reference.RepoObject_ReferenceTree_cyclic << V >> {
  Referenced_Depth_0_30 : (int)
  Referenced_Depth_30_0 : (int)
  Referenced_fullname : (nvarchar(261))
  Referenced_fullname2 : (nvarchar(257))
  - Referenced_guid : (uniqueidentifier)
  Referenced_type : (char(2))
  Referencing_Depth_0_30 : (int)
  Referencing_Depth_30_0 : (int)
  Referencing_fullname : (nvarchar(261))
  Referencing_fullname2 : (nvarchar(257))
  - Referencing_guid : (uniqueidentifier)
  Referencing_type : (varchar(2))
  - RepoObject_guid : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.usp_repoobject_referencetree_insert.adoc[]" as reference.usp_RepoObject_ReferenceTree_insert << P >> {
  --
}

reference.RepoObject_ReferenceTree <.. docs.ftv_RepoObject_Reference_PlantUml_EntityRefList
reference.RepoObject_ReferenceTree <.. docs.RepoObject_Plantuml_ObjectRefList_0_30
reference.RepoObject_ReferenceTree <.. docs.RepoObject_Plantuml_ObjectRefList_30_0
reference.RepoObject_ReferenceTree <.. reference.Persistence
reference.RepoObject_ReferenceTree <.. reference.RepoObject_ReferenceTree_cyclic
reference.RepoObject_ReferenceTree <.. reference.usp_RepoObject_ReferenceTree_insert
"reference.RepoObject_ReferenceTree::Referenced_Depth" <-- "reference.RepoObject_ReferenceTree_cyclic::Referenced_Depth_30_0"
"reference.RepoObject_ReferenceTree::Referenced_Depth" <-- "reference.RepoObject_ReferenceTree_cyclic::Referenced_Depth_0_30"
"reference.RepoObject_ReferenceTree::Referenced_fullname" <-- "reference.RepoObject_ReferenceTree_cyclic::Referenced_fullname"
"reference.RepoObject_ReferenceTree::Referenced_fullname2" <-- "reference.RepoObject_ReferenceTree_cyclic::Referenced_fullname2"
"reference.RepoObject_ReferenceTree::Referenced_guid" <-- "reference.RepoObject_ReferenceTree_cyclic::Referenced_guid"
"reference.RepoObject_ReferenceTree::Referenced_type" <-- "reference.RepoObject_ReferenceTree_cyclic::Referenced_type"
"reference.RepoObject_ReferenceTree::Referencing_Depth" <-- "reference.RepoObject_ReferenceTree_cyclic::Referencing_Depth_30_0"
"reference.RepoObject_ReferenceTree::Referencing_Depth" <-- "reference.RepoObject_ReferenceTree_cyclic::Referencing_Depth_0_30"
"reference.RepoObject_ReferenceTree::Referencing_fullname" <-- "reference.RepoObject_ReferenceTree_cyclic::Referencing_fullname"
"reference.RepoObject_ReferenceTree::Referencing_fullname2" <-- "reference.RepoObject_ReferenceTree_cyclic::Referencing_fullname2"
"reference.RepoObject_ReferenceTree::Referencing_guid" <-- "reference.RepoObject_ReferenceTree_cyclic::Referencing_guid"
"reference.RepoObject_ReferenceTree::Referencing_type" <-- "reference.RepoObject_ReferenceTree_cyclic::Referencing_type"
"reference.RepoObject_ReferenceTree::RepoObject_guid" <-- "reference.RepoObject_ReferenceTree_cyclic::RepoObject_guid"

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_colref[]


== sql_modules_definition

// tag::sql_modules_definition[]
[%collapsible]
=======
[source,sql,numbered,indent=0]
----

----
=======
// end::sql_modules_definition[]


