// tag::HeaderFullDisplayName[]
= reference.RepoObject_ReferenceTree_cyclic - V
// end::HeaderFullDisplayName[]

== existing_properties

// tag::existing_properties[]

:ExistsProperty--antorareferencedlist:
:ExistsProperty--antorareferencinglist:
:ExistsProperty--is_repo_managed:
:ExistsProperty--is_ssas:
:ExistsProperty--referencedobjectlist:
:ExistsProperty--sql_modules_definition:
:ExistsProperty--FK:
:ExistsProperty--AntoraIndexList:
:ExistsProperty--Columns:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
7DE72F09-C5FD-EB11-850F-A81E8446D5B0
// end::RepoObject_guid[]

== RepoObject_FullDisplayName2

// tag::RepoObject_FullDisplayName2[]
reference.RepoObject_ReferenceTree_cyclic
// end::RepoObject_FullDisplayName2[]

== SysObject_type

// tag::SysObject_type[]
V 
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
view
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
657437416
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2021-09-04 20:15:41
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]
[discrete]
== _


[#column-referencedunderlinedepthunderline0underline30]
=== Referenced_Depth_0_30

[cols="d,8a,m,m,m"]
|===
|
|Referenced_Depth_0_30
|int
|NULL
|
|===

.Referenced Columns
--
* xref:reference.repoobject_referencetree.adoc#column-referencedunderlinedepth[+reference.RepoObject_ReferenceTree.Referenced_Depth+]
--


[#column-referencedunderlinedepthunderline30underline0]
=== Referenced_Depth_30_0

[cols="d,8a,m,m,m"]
|===
|
|Referenced_Depth_30_0
|int
|NULL
|
|===

.Referenced Columns
--
* xref:reference.repoobject_referencetree.adoc#column-referencedunderlinedepth[+reference.RepoObject_ReferenceTree.Referenced_Depth+]
--


[#column-referencedunderlinefullname]
=== Referenced_fullname

[cols="d,8a,m,m,m"]
|===
|
|Referenced_fullname
|nvarchar(261)
|NULL
|
|===

.Referenced Columns
--
* xref:reference.repoobject_referencetree.adoc#column-referencedunderlinefullname[+reference.RepoObject_ReferenceTree.Referenced_fullname+]
--

.Referencing Columns
--
* xref:reference.referencetree_cyclic_ref_primary.adoc#column-referencedunderlinefullname[+reference.ReferenceTree_cyclic_ref_primary.Referenced_fullname+]
--


[#column-referencedunderlinefullname2]
=== Referenced_fullname2

[cols="d,8a,m,m,m"]
|===
|
|Referenced_fullname2
|nvarchar(257)
|NULL
|
|===

.Referenced Columns
--
* xref:reference.repoobject_referencetree.adoc#column-referencedunderlinefullname2[+reference.RepoObject_ReferenceTree.Referenced_fullname2+]
--

.Referencing Columns
--
* xref:reference.referencetree_cyclic_ref_primary.adoc#column-referencedunderlinefullname2[+reference.ReferenceTree_cyclic_ref_primary.Referenced_fullname2+]
--


[#column-referencedunderlineguid]
=== Referenced_guid

[cols="d,8a,m,m,m"]
|===
|
|Referenced_guid
|uniqueidentifier
|NOT NULL
|
|===

.Referenced Columns
--
* xref:reference.repoobject_referencetree.adoc#column-referencedunderlineguid[+reference.RepoObject_ReferenceTree.Referenced_guid+]
--

.Referencing Columns
--
* xref:reference.referencetree_cyclic_ref_primary.adoc#column-referencedunderlineguid[+reference.ReferenceTree_cyclic_ref_primary.Referenced_guid+]
--


[#column-referencedunderlinetype]
=== Referenced_type

[cols="d,8a,m,m,m"]
|===
|
|Referenced_type
|char(2)
|NULL
|
|===

.Referenced Columns
--
* xref:reference.repoobject_referencetree.adoc#column-referencedunderlinetype[+reference.RepoObject_ReferenceTree.Referenced_type+]
--

.Referencing Columns
--
* xref:reference.referencetree_cyclic_ref_primary.adoc#column-referencedunderlinetype[+reference.ReferenceTree_cyclic_ref_primary.Referenced_type+]
--


[#column-referencingunderlinedepthunderline0underline30]
=== Referencing_Depth_0_30

[cols="d,8a,m,m,m"]
|===
|
|Referencing_Depth_0_30
|int
|NULL
|
|===

.Referenced Columns
--
* xref:reference.repoobject_referencetree.adoc#column-referencingunderlinedepth[+reference.RepoObject_ReferenceTree.Referencing_Depth+]
--


[#column-referencingunderlinedepthunderline30underline0]
=== Referencing_Depth_30_0

[cols="d,8a,m,m,m"]
|===
|
|Referencing_Depth_30_0
|int
|NULL
|
|===

.Referenced Columns
--
* xref:reference.repoobject_referencetree.adoc#column-referencingunderlinedepth[+reference.RepoObject_ReferenceTree.Referencing_Depth+]
--


[#column-referencingunderlinefullname]
=== Referencing_fullname

[cols="d,8a,m,m,m"]
|===
|
|Referencing_fullname
|nvarchar(261)
|NULL
|
|===

.Referenced Columns
--
* xref:reference.repoobject_referencetree.adoc#column-referencingunderlinefullname[+reference.RepoObject_ReferenceTree.Referencing_fullname+]
--

.Referencing Columns
--
* xref:reference.referencetree_cyclic_ref_primary.adoc#column-referencingunderlinefullname[+reference.ReferenceTree_cyclic_ref_primary.Referencing_fullname+]
--


[#column-referencingunderlinefullname2]
=== Referencing_fullname2

[cols="d,8a,m,m,m"]
|===
|
|Referencing_fullname2
|nvarchar(257)
|NULL
|
|===

.Referenced Columns
--
* xref:reference.repoobject_referencetree.adoc#column-referencingunderlinefullname2[+reference.RepoObject_ReferenceTree.Referencing_fullname2+]
--

.Referencing Columns
--
* xref:reference.referencetree_cyclic_ref_primary.adoc#column-referencingunderlinefullname2[+reference.ReferenceTree_cyclic_ref_primary.Referencing_fullname2+]
--


[#column-referencingunderlineguid]
=== Referencing_guid

[cols="d,8a,m,m,m"]
|===
|
|Referencing_guid
|uniqueidentifier
|NOT NULL
|
|===

.Referenced Columns
--
* xref:reference.repoobject_referencetree.adoc#column-referencingunderlineguid[+reference.RepoObject_ReferenceTree.Referencing_guid+]
--

.Referencing Columns
--
* xref:reference.referencetree_cyclic_ref_primary.adoc#column-referencingunderlineguid[+reference.ReferenceTree_cyclic_ref_primary.Referencing_guid+]
--


[#column-referencingunderlinetype]
=== Referencing_type

[cols="d,8a,m,m,m"]
|===
|
|Referencing_type
|varchar(2)
|NULL
|
|===

.Referenced Columns
--
* xref:reference.repoobject_referencetree.adoc#column-referencingunderlinetype[+reference.RepoObject_ReferenceTree.Referencing_type+]
--

.Referencing Columns
--
* xref:reference.referencetree_cyclic_ref_primary.adoc#column-referencingunderlinetype[+reference.ReferenceTree_cyclic_ref_primary.Referencing_type+]
--


[#column-repoobjectunderlineguid]
=== RepoObject_guid

[cols="d,8a,m,m,m"]
|===
|
|RepoObject_guid
|uniqueidentifier
|NOT NULL
|
|===

.Referenced Columns
--
* xref:reference.repoobject_referencetree.adoc#column-repoobjectunderlineguid[+reference.RepoObject_ReferenceTree.RepoObject_guid+]
--


// end::AntoraColumnDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]













// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]
|
|<<column-referencedunderlinedepthunderline0underline30>>
|int
|NULL
|

|
|<<column-referencedunderlinedepthunderline30underline0>>
|int
|NULL
|

|
|<<column-referencedunderlinefullname>>
|nvarchar(261)
|NULL
|

|
|<<column-referencedunderlinefullname2>>
|nvarchar(257)
|NULL
|

|
|<<column-referencedunderlineguid>>
|uniqueidentifier
|NOT NULL
|

|
|<<column-referencedunderlinetype>>
|char(2)
|NULL
|

|
|<<column-referencingunderlinedepthunderline0underline30>>
|int
|NULL
|

|
|<<column-referencingunderlinedepthunderline30underline0>>
|int
|NULL
|

|
|<<column-referencingunderlinefullname>>
|nvarchar(261)
|NULL
|

|
|<<column-referencingunderlinefullname2>>
|nvarchar(257)
|NULL
|

|
|<<column-referencingunderlineguid>>
|uniqueidentifier
|NOT NULL
|

|
|<<column-referencingunderlinetype>>
|varchar(2)
|NULL
|

|
|<<column-repoobjectunderlineguid>>
|uniqueidentifier
|NOT NULL
|

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

[#index-idxunderlinerepoobjectunderlinereferencetreeunderlinecyclicunderlineunderline1]
=== idx_RepoObject_ReferenceTree_cyclic++__++1

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-RepoObject_guid>>; uniqueidentifier
* <<column-Referenced_Depth_30_0>>; int
* <<column-Referencing_Depth_30_0>>; int
* <<column-Referenced_guid>>; uniqueidentifier
* <<column-Referencing_guid>>; uniqueidentifier
--
* PK, Unique, Real: 0, 0, 0


[#index-idxunderlinerepoobjectunderlinereferencetreeunderlinecyclicunderlineunderline2]
=== idx_RepoObject_ReferenceTree_cyclic++__++2

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-Referenced_Depth_0_30>>; int
* <<column-Referencing_Depth_0_30>>; int
--
* PK, Unique, Real: 0, 0, 0

// end::AntoraIndexList[]

== AntoraMeasureDetails

// tag::AntoraMeasureDetails[]

// end::AntoraMeasureDetails[]

== AntoraMeasureDescriptions



== AntoraParameterList

// tag::AntoraParameterList[]

// end::AntoraParameterList[]

== AntoraXrefCulturesList

// tag::AntoraXrefCulturesList[]
* xref:dhw:sqldb:reference.repoobject_referencetree_cyclic.adoc[] - 
// end::AntoraXrefCulturesList[]

== cultures_count

// tag::cultures_count[]
1
// end::cultures_count[]

== Other tags

source: property.RepoObjectProperty_cross As rop_cross


=== additional_reference_csv

// tag::additional_reference_csv[]

// end::additional_reference_csv[]


=== AdocUspSteps

// tag::adocuspsteps[]

// end::adocuspsteps[]


=== AntoraReferencedList

// tag::antorareferencedlist[]
* xref:dhw:sqldb:reference.repoobject_referencetree.adoc[]
// end::antorareferencedlist[]


=== AntoraReferencingList

// tag::antorareferencinglist[]
* xref:dhw:sqldb:reference.referencetree_cyclic_ref_primary.adoc[]
// end::antorareferencinglist[]


=== Description

// tag::description[]

// end::description[]


=== exampleUsage

// tag::exampleusage[]

// end::exampleusage[]


=== exampleUsage_2

// tag::exampleusage_2[]

// end::exampleusage_2[]


=== exampleUsage_3

// tag::exampleusage_3[]

// end::exampleusage_3[]


=== exampleUsage_4

// tag::exampleusage_4[]

// end::exampleusage_4[]


=== exampleUsage_5

// tag::exampleusage_5[]

// end::exampleusage_5[]


=== exampleWrong_Usage

// tag::examplewrong_usage[]

// end::examplewrong_usage[]


=== has_execution_plan_issue

// tag::has_execution_plan_issue[]

// end::has_execution_plan_issue[]


=== has_get_referenced_issue

// tag::has_get_referenced_issue[]

// end::has_get_referenced_issue[]


=== has_history

// tag::has_history[]

// end::has_history[]


=== has_history_columns

// tag::has_history_columns[]

// end::has_history_columns[]


=== InheritanceType

// tag::inheritancetype[]

// end::inheritancetype[]


=== is_persistence

// tag::is_persistence[]

// end::is_persistence[]


=== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]

// end::is_persistence_check_duplicate_per_pk[]


=== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]

// end::is_persistence_check_for_empty_source[]


=== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]

// end::is_persistence_delete_changed[]


=== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]

// end::is_persistence_delete_missing[]


=== is_persistence_insert

// tag::is_persistence_insert[]

// end::is_persistence_insert[]


=== is_persistence_truncate

// tag::is_persistence_truncate[]

// end::is_persistence_truncate[]


=== is_persistence_update_changed

// tag::is_persistence_update_changed[]

// end::is_persistence_update_changed[]


=== is_repo_managed

// tag::is_repo_managed[]
0
// end::is_repo_managed[]


=== is_ssas

// tag::is_ssas[]
0
// end::is_ssas[]


=== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


=== MS_Description

// tag::ms_description[]

// end::ms_description[]


=== persistence_source_RepoObject_fullname

// tag::persistence_source_repoobject_fullname[]

// end::persistence_source_repoobject_fullname[]


=== persistence_source_RepoObject_fullname2

// tag::persistence_source_repoobject_fullname2[]

// end::persistence_source_repoobject_fullname2[]


=== persistence_source_RepoObject_guid

// tag::persistence_source_repoobject_guid[]

// end::persistence_source_repoobject_guid[]


=== persistence_source_RepoObject_xref

// tag::persistence_source_repoobject_xref[]

// end::persistence_source_repoobject_xref[]


=== pk_index_guid

// tag::pk_index_guid[]

// end::pk_index_guid[]


=== pk_IndexPatternColumnDatatype

// tag::pk_indexpatterncolumndatatype[]

// end::pk_indexpatterncolumndatatype[]


=== pk_IndexPatternColumnName

// tag::pk_indexpatterncolumnname[]

// end::pk_indexpatterncolumnname[]


=== pk_IndexSemanticGroup

// tag::pk_indexsemanticgroup[]

// end::pk_indexsemanticgroup[]


=== ReferencedObjectList

// tag::referencedobjectlist[]
* [reference].[RepoObject_ReferenceTree]
// end::referencedobjectlist[]


=== usp_persistence_RepoObject_guid

// tag::usp_persistence_repoobject_guid[]

// end::usp_persistence_repoobject_guid[]


=== UspExamples

// tag::uspexamples[]

// end::uspexamples[]


=== uspgenerator_usp_id

// tag::uspgenerator_usp_id[]

// end::uspgenerator_usp_id[]


=== UspParameters

// tag::uspparameters[]

// end::uspparameters[]

== Boolean Attributes

source: property.RepoObjectProperty WHERE property_int = 1

// tag::boolean_attributes[]


// end::boolean_attributes[]

== PlantUML diagrams

=== PlantUML Entity

// tag::puml_entity[]
[plantuml, entity-{docname}, svg, subs=macros]
....
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:reference.repoobject_referencetree_cyclic.adoc[]" as reference.RepoObject_ReferenceTree_cyclic << V >> {
  Referenced_Depth_0_30 : (int)
  Referenced_Depth_30_0 : (int)
  Referenced_fullname : (nvarchar(261))
  Referenced_fullname2 : (nvarchar(257))
  - Referenced_guid : (uniqueidentifier)
  Referenced_type : (char(2))
  Referencing_Depth_0_30 : (int)
  Referencing_Depth_30_0 : (int)
  Referencing_fullname : (nvarchar(261))
  Referencing_fullname2 : (nvarchar(257))
  - Referencing_guid : (uniqueidentifier)
  Referencing_type : (varchar(2))
  - RepoObject_guid : (uniqueidentifier)
  --
}
....

// end::puml_entity[]

=== PlantUML Entity 1 1 FK

// tag::puml_entity_1_1_fk[]
[plantuml, entity_1_1_fk-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:reference.repoobject_referencetree_cyclic.adoc[]" as reference.RepoObject_ReferenceTree_cyclic << V >> {
- idx_RepoObject_ReferenceTree_cyclic__1

..
RepoObject_guid; uniqueidentifier
Referenced_Depth_30_0; int
Referencing_Depth_30_0; int
Referenced_guid; uniqueidentifier
Referencing_guid; uniqueidentifier
--
- idx_RepoObject_ReferenceTree_cyclic__2

..
Referenced_Depth_0_30; int
Referencing_Depth_0_30; int
}



footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_fk[]

=== PlantUML 1 1 ObjectRef

// tag::puml_entity_1_1_objectref[]
[plantuml, entity_1_1_objectref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:reference.referencetree_cyclic_ref_primary.adoc[]" as reference.ReferenceTree_cyclic_ref_primary << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_referencetree.adoc[]" as reference.RepoObject_ReferenceTree << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  **Referenced_Depth** : (int)
  **Referencing_Depth** : (int)
  - **Referenced_guid** : (uniqueidentifier)
  - **Referencing_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_referencetree_cyclic.adoc[]" as reference.RepoObject_ReferenceTree_cyclic << V >> {
  --
}

reference.RepoObject_ReferenceTree <.. reference.RepoObject_ReferenceTree_cyclic
reference.RepoObject_ReferenceTree_cyclic <.. reference.ReferenceTree_cyclic_ref_primary

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_objectref[]

=== PlantUML 30 0 ObjectRef

// tag::puml_entity_30_0_objectref[]
[plantuml, entity_30_0_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:reference.repoobject_referencetree.adoc[]" as reference.RepoObject_ReferenceTree << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  **Referenced_Depth** : (int)
  **Referencing_Depth** : (int)
  - **Referenced_guid** : (uniqueidentifier)
  - **Referencing_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_referencetree_cyclic.adoc[]" as reference.RepoObject_ReferenceTree_cyclic << V >> {
  --
}

reference.RepoObject_ReferenceTree <.. reference.RepoObject_ReferenceTree_cyclic

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_30_0_objectref[]

=== PlantUML 0 30 ObjectRef

// tag::puml_entity_0_30_objectref[]
[plantuml, entity_0_30_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:docs.objectrefcyclic.adoc[]" as docs.ObjectRefCyclic << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.objectrefcyclic_entitylist.adoc[]" as docs.ObjectRefCyclic_EntityList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.objectrefcyclic_objectreflist.adoc[]" as docs.ObjectRefCyclic_ObjectRefList << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.referencetree_cyclic_ref_persistenceusp.adoc[]" as reference.ReferenceTree_cyclic_ref_PersistenceUsp << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.referencetree_cyclic_ref_primary.adoc[]" as reference.ReferenceTree_cyclic_ref_primary << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.referencetree_cyclic_union.adoc[]" as reference.ReferenceTree_cyclic_union << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_referencetree_cyclic.adoc[]" as reference.RepoObject_ReferenceTree_cyclic << V >> {
  --
}

docs.ObjectRefCyclic_EntityList <.. docs.ObjectRefCyclic
docs.ObjectRefCyclic_ObjectRefList <.. docs.ObjectRefCyclic
reference.ReferenceTree_cyclic_ref_PersistenceUsp <.. reference.ReferenceTree_cyclic_union
reference.ReferenceTree_cyclic_ref_primary <.. reference.ReferenceTree_cyclic_ref_PersistenceUsp
reference.ReferenceTree_cyclic_ref_primary <.. reference.ReferenceTree_cyclic_union
reference.ReferenceTree_cyclic_union <.. docs.ObjectRefCyclic_EntityList
reference.ReferenceTree_cyclic_union <.. docs.ObjectRefCyclic_ObjectRefList
reference.RepoObject_ReferenceTree_cyclic <.. reference.ReferenceTree_cyclic_ref_primary

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_0_30_objectref[]

=== PlantUML 1 1 ColumnRef

// tag::puml_entity_1_1_colref[]
[plantuml, entity_1_1_colref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:reference.referencetree_cyclic_ref_primary.adoc[]" as reference.ReferenceTree_cyclic_ref_primary << V >> {
  Referenced_fullname : (nvarchar(261))
  Referenced_fullname2 : (nvarchar(257))
  - Referenced_guid : (uniqueidentifier)
  Referenced_type : (char(2))
  Referencing_fullname : (nvarchar(261))
  Referencing_fullname2 : (nvarchar(257))
  - Referencing_guid : (uniqueidentifier)
  Referencing_type : (varchar(2))
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_referencetree.adoc[]" as reference.RepoObject_ReferenceTree << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  **Referenced_Depth** : (int)
  **Referencing_Depth** : (int)
  - **Referenced_guid** : (uniqueidentifier)
  - **Referencing_guid** : (uniqueidentifier)
  Referenced_fullname : (nvarchar(261))
  Referenced_fullname2 : (nvarchar(257))
  Referenced_type : (char(2))
  Referencing_fullname : (nvarchar(261))
  Referencing_fullname2 : (nvarchar(257))
  Referencing_type : (varchar(2))
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_referencetree_cyclic.adoc[]" as reference.RepoObject_ReferenceTree_cyclic << V >> {
  Referenced_Depth_0_30 : (int)
  Referenced_Depth_30_0 : (int)
  Referenced_fullname : (nvarchar(261))
  Referenced_fullname2 : (nvarchar(257))
  - Referenced_guid : (uniqueidentifier)
  Referenced_type : (char(2))
  Referencing_Depth_0_30 : (int)
  Referencing_Depth_30_0 : (int)
  Referencing_fullname : (nvarchar(261))
  Referencing_fullname2 : (nvarchar(257))
  - Referencing_guid : (uniqueidentifier)
  Referencing_type : (varchar(2))
  - RepoObject_guid : (uniqueidentifier)
  --
}

reference.RepoObject_ReferenceTree <.. reference.RepoObject_ReferenceTree_cyclic
reference.RepoObject_ReferenceTree_cyclic <.. reference.ReferenceTree_cyclic_ref_primary
"reference.RepoObject_ReferenceTree::Referenced_Depth" <-- "reference.RepoObject_ReferenceTree_cyclic::Referenced_Depth_30_0"
"reference.RepoObject_ReferenceTree::Referenced_Depth" <-- "reference.RepoObject_ReferenceTree_cyclic::Referenced_Depth_0_30"
"reference.RepoObject_ReferenceTree::Referenced_fullname" <-- "reference.RepoObject_ReferenceTree_cyclic::Referenced_fullname"
"reference.RepoObject_ReferenceTree::Referenced_fullname2" <-- "reference.RepoObject_ReferenceTree_cyclic::Referenced_fullname2"
"reference.RepoObject_ReferenceTree::Referenced_guid" <-- "reference.RepoObject_ReferenceTree_cyclic::Referenced_guid"
"reference.RepoObject_ReferenceTree::Referenced_type" <-- "reference.RepoObject_ReferenceTree_cyclic::Referenced_type"
"reference.RepoObject_ReferenceTree::Referencing_Depth" <-- "reference.RepoObject_ReferenceTree_cyclic::Referencing_Depth_30_0"
"reference.RepoObject_ReferenceTree::Referencing_Depth" <-- "reference.RepoObject_ReferenceTree_cyclic::Referencing_Depth_0_30"
"reference.RepoObject_ReferenceTree::Referencing_fullname" <-- "reference.RepoObject_ReferenceTree_cyclic::Referencing_fullname"
"reference.RepoObject_ReferenceTree::Referencing_fullname2" <-- "reference.RepoObject_ReferenceTree_cyclic::Referencing_fullname2"
"reference.RepoObject_ReferenceTree::Referencing_guid" <-- "reference.RepoObject_ReferenceTree_cyclic::Referencing_guid"
"reference.RepoObject_ReferenceTree::Referencing_type" <-- "reference.RepoObject_ReferenceTree_cyclic::Referencing_type"
"reference.RepoObject_ReferenceTree::RepoObject_guid" <-- "reference.RepoObject_ReferenceTree_cyclic::RepoObject_guid"
"reference.RepoObject_ReferenceTree_cyclic::Referenced_fullname" <-- "reference.ReferenceTree_cyclic_ref_primary::Referenced_fullname"
"reference.RepoObject_ReferenceTree_cyclic::Referenced_fullname2" <-- "reference.ReferenceTree_cyclic_ref_primary::Referenced_fullname2"
"reference.RepoObject_ReferenceTree_cyclic::Referenced_guid" <-- "reference.ReferenceTree_cyclic_ref_primary::Referenced_guid"
"reference.RepoObject_ReferenceTree_cyclic::Referenced_type" <-- "reference.ReferenceTree_cyclic_ref_primary::Referenced_type"
"reference.RepoObject_ReferenceTree_cyclic::referencing_fullname" <-- "reference.ReferenceTree_cyclic_ref_primary::Referencing_fullname"
"reference.RepoObject_ReferenceTree_cyclic::referencing_fullname2" <-- "reference.ReferenceTree_cyclic_ref_primary::Referencing_fullname2"
"reference.RepoObject_ReferenceTree_cyclic::Referencing_guid" <-- "reference.ReferenceTree_cyclic_ref_primary::Referencing_guid"
"reference.RepoObject_ReferenceTree_cyclic::referencing_type" <-- "reference.ReferenceTree_cyclic_ref_primary::Referencing_type"

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_colref[]


== sql_modules_definition

// tag::sql_modules_definition[]
[%collapsible]
=======
[source,sql,numbered,indent=0]
----

/*
cyclic references:

the same RepoObject_guid has the same references backward and forward: in _30_0 and in _0_30 +
this causes errors in PUML diagrams and in workflow generator

goals of this view:

* vizualisation in diagrams
* solving the issues in PUML reference diagrams and workflow generator
*/

CREATE View reference.RepoObject_ReferenceTree_cyclic
As
Select
    T1.RepoObject_guid
  , T1.Referenced_guid
  , Referenced_Depth_0_30  = T2.Referenced_Depth
  , Referenced_Depth_30_0  = T1.Referenced_Depth
  , T1.referenced_fullname
  , T1.referenced_fullname2
  , T1.referenced_type
  , T1.Referencing_guid
  , Referencing_Depth_0_30 = T2.Referencing_Depth
  , Referencing_Depth_30_0 = T1.Referencing_Depth
  , T1.referencing_fullname
  , T1.referencing_fullname2
  , T1.referencing_type
From
    reference.RepoObject_ReferenceTree     As T1
    Inner Join
        reference.RepoObject_ReferenceTree As T2
            On
            T1.RepoObject_guid       = T2.RepoObject_guid
            And T1.Referencing_guid  = T2.Referencing_guid
            And T1.Referenced_guid   = T2.Referenced_guid
            And T1.Referencing_Depth = 0
            And T2.Referenced_Depth  = 0

----
=======
// end::sql_modules_definition[]


