// tag::HeaderFullDisplayName[]
= reference.RepoObject_ReferencedReferencing - V
// end::HeaderFullDisplayName[]

== existing_properties

// tag::existing_properties[]

:ExistsProperty--antorareferencedlist:
:ExistsProperty--antorareferencinglist:
:ExistsProperty--is_repo_managed:
:ExistsProperty--is_ssas:
:ExistsProperty--referencedobjectlist:
:ExistsProperty--sql_modules_definition:
:ExistsProperty--FK:
:ExistsProperty--AntoraIndexList:
:ExistsProperty--Columns:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
414679B8-147C-EB11-84E6-A81E8446D5B0
// end::RepoObject_guid[]

== RepoObject_FullDisplayName2

// tag::RepoObject_FullDisplayName2[]
reference.RepoObject_ReferencedReferencing
// end::RepoObject_FullDisplayName2[]

== SysObject_type

// tag::SysObject_type[]
V 
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
view
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
1632060900
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2021-11-19 17:46:23
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]
[discrete]
== _


[#column-referencedunderlineantoraxref]
=== referenced_AntoraXref

[cols="d,8a,m,m,m"]
|===
|
|referenced_AntoraXref
|nvarchar(max)
|NOT NULL
|
|===


[#column-referencedunderlineexternalunderlineantoracomponent]
=== referenced_external_AntoraComponent

[cols="d,8a,m,m,m"]
|===
|
|referenced_external_AntoraComponent
|nvarchar(128)
|NULL
|
|===

.Referenced Columns
--
* xref:reference.repoobject_reference_t.adoc#column-referencedunderlineexternalunderlineantoracomponent[+reference.RepoObject_reference_T.referenced_external_AntoraComponent+]
--


[#column-referencedunderlineexternalunderlineantoramodule]
=== referenced_external_AntoraModule

[cols="d,8a,m,m,m"]
|===
|
|referenced_external_AntoraModule
|nvarchar(128)
|NULL
|
|===

.Referenced Columns
--
* xref:reference.repoobject_reference_t.adoc#column-referencedunderlineexternalunderlineantoramodule[+reference.RepoObject_reference_T.referenced_external_AntoraModule+]
--


[#column-referencedunderlinefullname]
=== Referenced_fullname

[cols="d,8a,m,m,m"]
|===
|
|Referenced_fullname
|nvarchar(261)
|NOT NULL
|
|===

.Description
--
(concat('[',[referenced_schema_name],'].[',[referenced_entity_name],']'))
--
{empty} +

.Referenced Columns
--
* xref:reference.repoobject_reference_t.adoc#column-referencedunderlinefullname[+reference.RepoObject_reference_T.referenced_fullname+]
--

.Referencing Columns
--
* xref:reference.repoobject_referencinglist.adoc#column-referencedunderlinefullname[+reference.RepoObject_ReferencingList.Referenced_fullname+]
--


[#column-referencedunderlinefullname2]
=== Referenced_fullname2

[cols="d,8a,m,m,m"]
|===
|
|Referenced_fullname2
|nvarchar(257)
|NOT NULL
|
|===

.Description
--
(concat([referenced_schema_name],'.',[referenced_entity_name]))
--
{empty} +

.Referenced Columns
--
* xref:reference.repoobject_reference_t.adoc#column-referencedunderlinefullname2[+reference.RepoObject_reference_T.referenced_fullname2+]
--


[#column-referencedunderlineguid]
=== Referenced_guid

[cols="d,8a,m,m,m"]
|===
|
|Referenced_guid
|uniqueidentifier
|NOT NULL
|
|===

.Referenced Columns
--
* xref:reference.repoobject_reference_t.adoc#column-referencedunderlinerepoobjectunderlineguid[+reference.RepoObject_reference_T.referenced_RepoObject_guid+]
--

.Referencing Columns
--
* xref:reference.repoobject_referencinglist.adoc#column-referencedunderlineguid[+reference.RepoObject_ReferencingList.Referenced_guid+]
--


[#column-referencedunderlineisunderlinedocsoutput]
=== referenced_is_DocsOutput

[cols="d,8a,m,m,m"]
|===
|
|referenced_is_DocsOutput
|int
|NULL
|
|===

.Referenced Columns
--
* xref:configt.type.adoc#column-isunderlinedocsoutput[+configT.type.is_DocsOutput+]
--


[#column-referencedunderlineisunderlineexternal]
=== referenced_is_external

[cols="d,8a,m,m,m"]
|===
|
|referenced_is_external
|bit
|NOT NULL
|
|===

.Referenced Columns
--
* xref:reference.repoobject_reference_t.adoc#column-referencedunderlineisunderlineexternal[+reference.RepoObject_reference_T.referenced_is_external+]
--


[#column-referencedunderlinetype]
=== Referenced_type

[cols="d,8a,m,m,m"]
|===
|
|Referenced_type
|char(2)
|NULL
|
|===

.Referenced Columns
--
* xref:reference.repoobject_reference_t.adoc#column-referencedunderlinetype[+reference.RepoObject_reference_T.referenced_type+]
--


[#column-referencingunderlineantoraxref]
=== referencing_AntoraXref

[cols="d,8a,m,m,m"]
|===
|
|referencing_AntoraXref
|nvarchar(max)
|NOT NULL
|
|===


[#column-referencingunderlineexternalunderlineantoracomponent]
=== referencing_external_AntoraComponent

[cols="d,8a,m,m,m"]
|===
|
|referencing_external_AntoraComponent
|nvarchar(128)
|NULL
|
|===

.Referenced Columns
--
* xref:reference.repoobject_reference_t.adoc#column-referencingunderlineexternalunderlineantoracomponent[+reference.RepoObject_reference_T.referencing_external_AntoraComponent+]
--


[#column-referencingunderlineexternalunderlineantoramodule]
=== referencing_external_AntoraModule

[cols="d,8a,m,m,m"]
|===
|
|referencing_external_AntoraModule
|nvarchar(128)
|NULL
|
|===

.Referenced Columns
--
* xref:reference.repoobject_reference_t.adoc#column-referencingunderlineexternalunderlineantoramodule[+reference.RepoObject_reference_T.referencing_external_AntoraModule+]
--


[#column-referencingunderlinefullname]
=== Referencing_fullname

[cols="d,8a,m,m,m"]
|===
|
|Referencing_fullname
|nvarchar(261)
|NOT NULL
|
|===

.Description
--
(concat('[',[referencing_schema_name],'].[',[referencing_entity_name],']'))
--
{empty} +

.Referenced Columns
--
* xref:reference.repoobject_reference_t.adoc#column-referencingunderlinefullname[+reference.RepoObject_reference_T.referencing_fullname+]
--

.Referencing Columns
--
* xref:reference.repoobject_referencedlist.adoc#column-referencingunderlinefullname[+reference.RepoObject_ReferencedList.Referencing_fullname+]
--


[#column-referencingunderlinefullname2]
=== Referencing_fullname2

[cols="d,8a,m,m,m"]
|===
|
|Referencing_fullname2
|nvarchar(257)
|NOT NULL
|
|===

.Description
--
(concat([referencing_schema_name],'.',[referencing_entity_name]))
--
{empty} +

.Referenced Columns
--
* xref:reference.repoobject_reference_t.adoc#column-referencingunderlinefullname2[+reference.RepoObject_reference_T.referencing_fullname2+]
--


[#column-referencingunderlineguid]
=== Referencing_guid

[cols="d,8a,m,m,m"]
|===
|
|Referencing_guid
|uniqueidentifier
|NOT NULL
|
|===

.Referenced Columns
--
* xref:reference.repoobject_reference_t.adoc#column-referencingunderlinerepoobjectunderlineguid[+reference.RepoObject_reference_T.referencing_RepoObject_guid+]
--

.Referencing Columns
--
* xref:reference.repoobject_referencedlist.adoc#column-referencingunderlineguid[+reference.RepoObject_ReferencedList.Referencing_guid+]
--


[#column-referencingunderlineisunderlinedocsoutput]
=== referencing_is_DocsOutput

[cols="d,8a,m,m,m"]
|===
|
|referencing_is_DocsOutput
|int
|NULL
|
|===

.Referenced Columns
--
* xref:configt.type.adoc#column-isunderlinedocsoutput[+configT.type.is_DocsOutput+]
--


[#column-referencingunderlineisunderlineexternal]
=== referencing_is_external

[cols="d,8a,m,m,m"]
|===
|
|referencing_is_external
|bit
|NOT NULL
|
|===

.Referenced Columns
--
* xref:reference.repoobject_reference_t.adoc#column-referencingunderlineisunderlineexternal[+reference.RepoObject_reference_T.referencing_is_external+]
--


[#column-referencingunderlinetype]
=== Referencing_type

[cols="d,8a,m,m,m"]
|===
|
|Referencing_type
|varchar(2)
|NULL
|
|===

.Referenced Columns
--
* xref:reference.repoobject_reference_t.adoc#column-referencingunderlinetype[+reference.RepoObject_reference_T.referencing_type+]
--


// end::AntoraColumnDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]


















// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]
|
|<<column-referencedunderlineantoraxref>>
|nvarchar(max)
|NOT NULL
|

|
|<<column-referencedunderlineexternalunderlineantoracomponent>>
|nvarchar(128)
|NULL
|

|
|<<column-referencedunderlineexternalunderlineantoramodule>>
|nvarchar(128)
|NULL
|

|
|<<column-referencedunderlinefullname>>
|nvarchar(261)
|NOT NULL
|

|
|<<column-referencedunderlinefullname2>>
|nvarchar(257)
|NOT NULL
|

|
|<<column-referencedunderlineguid>>
|uniqueidentifier
|NOT NULL
|

|
|<<column-referencedunderlineisunderlinedocsoutput>>
|int
|NULL
|

|
|<<column-referencedunderlineisunderlineexternal>>
|bit
|NOT NULL
|

|
|<<column-referencedunderlinetype>>
|char(2)
|NULL
|

|
|<<column-referencingunderlineantoraxref>>
|nvarchar(max)
|NOT NULL
|

|
|<<column-referencingunderlineexternalunderlineantoracomponent>>
|nvarchar(128)
|NULL
|

|
|<<column-referencingunderlineexternalunderlineantoramodule>>
|nvarchar(128)
|NULL
|

|
|<<column-referencingunderlinefullname>>
|nvarchar(261)
|NOT NULL
|

|
|<<column-referencingunderlinefullname2>>
|nvarchar(257)
|NOT NULL
|

|
|<<column-referencingunderlineguid>>
|uniqueidentifier
|NOT NULL
|

|
|<<column-referencingunderlineisunderlinedocsoutput>>
|int
|NULL
|

|
|<<column-referencingunderlineisunderlineexternal>>
|bit
|NOT NULL
|

|
|<<column-referencingunderlinetype>>
|varchar(2)
|NULL
|

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

[#index-idxunderlinerepoobjectunderlinereferencedreferencingunderlineunderline1]
=== idx_RepoObject_ReferencedReferencing++__++1

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-Referenced_guid>>; uniqueidentifier
* <<column-Referencing_guid>>; uniqueidentifier
--
* PK, Unique, Real: 0, 0, 0

// end::AntoraIndexList[]

== AntoraMeasureDetails

// tag::AntoraMeasureDetails[]

// end::AntoraMeasureDetails[]

== AntoraMeasureDescriptions



== AntoraParameterList

// tag::AntoraParameterList[]

// end::AntoraParameterList[]

== AntoraXrefCulturesList

// tag::AntoraXrefCulturesList[]
* xref:dhw:sqldb:reference.repoobject_referencedreferencing.adoc[] - 
// end::AntoraXrefCulturesList[]

== cultures_count

// tag::cultures_count[]
1
// end::cultures_count[]

== Other tags

source: property.RepoObjectProperty_cross As rop_cross


=== additional_reference_csv

// tag::additional_reference_csv[]

// end::additional_reference_csv[]


=== AdocUspSteps

// tag::adocuspsteps[]

// end::adocuspsteps[]


=== AntoraReferencedList

// tag::antorareferencedlist[]
* xref:dhw:sqldb:configt.type.adoc[]
* xref:dhw:sqldb:docs.fs_cleanstringforfilename.adoc[]
* xref:dhw:sqldb:reference.repoobject_reference_t.adoc[]
// end::antorareferencedlist[]


=== AntoraReferencingList

// tag::antorareferencinglist[]
* xref:dhw:sqldb:reference.ftv_repoobject_referencetree.adoc[]
* xref:dhw:sqldb:reference.ftv_repoobject_referencetree_referenced.adoc[]
* xref:dhw:sqldb:reference.ftv_repoobject_referencetree_referencing.adoc[]
* xref:dhw:sqldb:reference.ftv_repoobject_referencetree_via_fullname.adoc[]
* xref:dhw:sqldb:reference.repoobject_referencedlist.adoc[]
* xref:dhw:sqldb:reference.repoobject_referencinglist.adoc[]
* xref:dhw:sqldb:reference.usp_repoobject_referencetree_insert.adoc[]
* xref:dhw:sqldb:repo.repoobject_gross.adoc[]
// end::antorareferencinglist[]


=== Description

// tag::description[]

// end::description[]


=== exampleUsage

// tag::exampleusage[]

// end::exampleusage[]


=== exampleUsage_2

// tag::exampleusage_2[]

// end::exampleusage_2[]


=== exampleUsage_3

// tag::exampleusage_3[]

// end::exampleusage_3[]


=== exampleUsage_4

// tag::exampleusage_4[]

// end::exampleusage_4[]


=== exampleUsage_5

// tag::exampleusage_5[]

// end::exampleusage_5[]


=== exampleWrong_Usage

// tag::examplewrong_usage[]

// end::examplewrong_usage[]


=== has_execution_plan_issue

// tag::has_execution_plan_issue[]

// end::has_execution_plan_issue[]


=== has_get_referenced_issue

// tag::has_get_referenced_issue[]

// end::has_get_referenced_issue[]


=== has_history

// tag::has_history[]

// end::has_history[]


=== has_history_columns

// tag::has_history_columns[]

// end::has_history_columns[]


=== InheritanceType

// tag::inheritancetype[]

// end::inheritancetype[]


=== is_persistence

// tag::is_persistence[]

// end::is_persistence[]


=== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]

// end::is_persistence_check_duplicate_per_pk[]


=== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]

// end::is_persistence_check_for_empty_source[]


=== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]

// end::is_persistence_delete_changed[]


=== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]

// end::is_persistence_delete_missing[]


=== is_persistence_insert

// tag::is_persistence_insert[]

// end::is_persistence_insert[]


=== is_persistence_truncate

// tag::is_persistence_truncate[]

// end::is_persistence_truncate[]


=== is_persistence_update_changed

// tag::is_persistence_update_changed[]

// end::is_persistence_update_changed[]


=== is_repo_managed

// tag::is_repo_managed[]
0
// end::is_repo_managed[]


=== is_ssas

// tag::is_ssas[]
0
// end::is_ssas[]


=== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


=== MS_Description

// tag::ms_description[]

// end::ms_description[]


=== persistence_source_RepoObject_fullname

// tag::persistence_source_repoobject_fullname[]

// end::persistence_source_repoobject_fullname[]


=== persistence_source_RepoObject_fullname2

// tag::persistence_source_repoobject_fullname2[]

// end::persistence_source_repoobject_fullname2[]


=== persistence_source_RepoObject_guid

// tag::persistence_source_repoobject_guid[]

// end::persistence_source_repoobject_guid[]


=== persistence_source_RepoObject_xref

// tag::persistence_source_repoobject_xref[]

// end::persistence_source_repoobject_xref[]


=== pk_index_guid

// tag::pk_index_guid[]

// end::pk_index_guid[]


=== pk_IndexPatternColumnDatatype

// tag::pk_indexpatterncolumndatatype[]

// end::pk_indexpatterncolumndatatype[]


=== pk_IndexPatternColumnName

// tag::pk_indexpatterncolumnname[]

// end::pk_indexpatterncolumnname[]


=== pk_IndexSemanticGroup

// tag::pk_indexsemanticgroup[]

// end::pk_indexsemanticgroup[]


=== ReferencedObjectList

// tag::referencedobjectlist[]
* [configT].[type]
* [docs].[fs_cleanStringForFilename]
* [reference].[RepoObject_reference_T]
// end::referencedobjectlist[]


=== usp_persistence_RepoObject_guid

// tag::usp_persistence_repoobject_guid[]

// end::usp_persistence_repoobject_guid[]


=== UspExamples

// tag::uspexamples[]

// end::uspexamples[]


=== uspgenerator_usp_id

// tag::uspgenerator_usp_id[]

// end::uspgenerator_usp_id[]


=== UspParameters

// tag::uspparameters[]

// end::uspparameters[]

== Boolean Attributes

source: property.RepoObjectProperty WHERE property_int = 1

// tag::boolean_attributes[]


// end::boolean_attributes[]

== PlantUML diagrams

=== PlantUML Entity

// tag::puml_entity[]
[plantuml, entity-{docname}, svg, subs=macros]
....
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:reference.repoobject_referencedreferencing.adoc[]" as reference.RepoObject_ReferencedReferencing << V >> {
  - referenced_AntoraXref : (nvarchar(max))
  referenced_external_AntoraComponent : (nvarchar(128))
  referenced_external_AntoraModule : (nvarchar(128))
  - Referenced_fullname : (nvarchar(261))
  - Referenced_fullname2 : (nvarchar(257))
  - Referenced_guid : (uniqueidentifier)
  referenced_is_DocsOutput : (int)
  - referenced_is_external : (bit)
  Referenced_type : (char(2))
  - referencing_AntoraXref : (nvarchar(max))
  referencing_external_AntoraComponent : (nvarchar(128))
  referencing_external_AntoraModule : (nvarchar(128))
  - Referencing_fullname : (nvarchar(261))
  - Referencing_fullname2 : (nvarchar(257))
  - Referencing_guid : (uniqueidentifier)
  referencing_is_DocsOutput : (int)
  - referencing_is_external : (bit)
  Referencing_type : (varchar(2))
  --
}
....

// end::puml_entity[]

=== PlantUML Entity 1 1 FK

// tag::puml_entity_1_1_fk[]
[plantuml, entity_1_1_fk-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:reference.repoobject_referencedreferencing.adoc[]" as reference.RepoObject_ReferencedReferencing << V >> {
- idx_RepoObject_ReferencedReferencing__1

..
Referenced_guid; uniqueidentifier
Referencing_guid; uniqueidentifier
}



footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_fk[]

=== PlantUML 1 1 ObjectRef

// tag::puml_entity_1_1_objectref[]
[plantuml, entity_1_1_objectref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:configt.type.adoc[]" as configT.type << V >> {
  **type** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:docs.fs_cleanstringforfilename.adoc[]" as docs.fs_cleanStringForFilename << FN >> {
  --
}

entity "puml-link:dhw:sqldb:reference.ftv_repoobject_referencetree.adoc[]" as reference.ftv_RepoObject_ReferenceTree << IF >> {
  --
}

entity "puml-link:dhw:sqldb:reference.ftv_repoobject_referencetree_referenced.adoc[]" as reference.ftv_RepoObject_ReferenceTree_referenced << IF >> {
  --
}

entity "puml-link:dhw:sqldb:reference.ftv_repoobject_referencetree_referencing.adoc[]" as reference.ftv_RepoObject_ReferenceTree_referencing << IF >> {
  --
}

entity "puml-link:dhw:sqldb:reference.ftv_repoobject_referencetree_via_fullname.adoc[]" as reference.ftv_RepoObject_ReferenceTree_via_fullname << IF >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_reference_t.adoc[]" as reference.RepoObject_reference_T << U >> {
  - **referenced_RepoObject_guid** : (uniqueidentifier)
  - **referencing_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_referencedlist.adoc[]" as reference.RepoObject_ReferencedList << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_referencedreferencing.adoc[]" as reference.RepoObject_ReferencedReferencing << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_referencinglist.adoc[]" as reference.RepoObject_ReferencingList << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_repoobject_referencetree_insert.adoc[]" as reference.usp_RepoObject_ReferenceTree_insert << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_gross.adoc[]" as repo.RepoObject_gross << V >> {
  --
}

configT.type <.. reference.RepoObject_ReferencedReferencing
docs.fs_cleanStringForFilename <.. reference.RepoObject_ReferencedReferencing
reference.RepoObject_reference_T <.. reference.RepoObject_ReferencedReferencing
reference.RepoObject_ReferencedReferencing <.. reference.ftv_RepoObject_ReferenceTree
reference.RepoObject_ReferencedReferencing <.. reference.RepoObject_ReferencedList
reference.RepoObject_ReferencedReferencing <.. reference.ftv_RepoObject_ReferenceTree_via_fullname
reference.RepoObject_ReferencedReferencing <.. repo.RepoObject_gross
reference.RepoObject_ReferencedReferencing <.. reference.RepoObject_ReferencingList
reference.RepoObject_ReferencedReferencing <.. reference.ftv_RepoObject_ReferenceTree_referenced
reference.RepoObject_ReferencedReferencing <.. reference.ftv_RepoObject_ReferenceTree_referencing
reference.RepoObject_ReferencedReferencing <.. reference.usp_RepoObject_ReferenceTree_insert

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_objectref[]

=== PlantUML 30 0 ObjectRef

// tag::puml_entity_30_0_objectref[]
[plantuml, entity_30_0_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:config.ftv_dwh_database.adoc[]" as config.ftv_dwh_database << IF >> {
  --
}

entity "puml-link:dhw:sqldb:config.ftv_get_parameter_value.adoc[]" as config.ftv_get_parameter_value << IF >> {
  --
}

entity "puml-link:dhw:sqldb:config.parameter.adoc[]" as config.Parameter << U >> {
  - **Parameter_name** : (varchar(100))
  - **sub_Parameter** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:configt.parameter_default.adoc[]" as configT.Parameter_default << V >> {
  - **Parameter_name** : (varchar(52))
  - **sub_Parameter** : (nvarchar(26))
  --
}

entity "puml-link:dhw:sqldb:configt.spt_values.adoc[]" as configT.spt_values << U >> {
  --
}

entity "puml-link:dhw:sqldb:configt.type.adoc[]" as configT.type << V >> {
  **type** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:docs.fs_cleanstringforfilename.adoc[]" as docs.fs_cleanStringForFilename << FN >> {
  --
}

entity "puml-link:dhw:sqldb:property.external_repoobjectproperty.adoc[]" as property.external_RepoObjectProperty << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.propertyname_repoobject.adoc[]" as property.PropertyName_RepoObject << V >> {
  **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.propertyname_repoobject_t.adoc[]" as property.PropertyName_RepoObject_T << U >> {
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty.adoc[]" as property.RepoObjectProperty << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty_external_src.adoc[]" as property.RepoObjectProperty_external_src << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty_external_tgt.adoc[]" as property.RepoObjectProperty_external_tgt << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty_selectedpropertyname_split.adoc[]" as property.RepoObjectProperty_SelectedPropertyName_split << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference.adoc[]" as reference.additional_Reference << U >> {
  # **tik_hash_c** : (nvarchar(32))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_from_properties_src.adoc[]" as reference.additional_Reference_from_properties_src << V >> {
  **referenced_AntoraComponent** : (nvarchar(max))
  **referenced_AntoraModule** : (nvarchar(max))
  **referenced_Schema** : (nvarchar(max))
  **referenced_Object** : (nvarchar(max))
  **referenced_Column** : (nvarchar(max))
  **referencing_AntoraComponent** : (nvarchar(max))
  **referencing_AntoraModule** : (nvarchar(max))
  **referencing_Schema** : (nvarchar(max))
  **referencing_Object** : (nvarchar(max))
  **referencing_Column** : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_from_properties_tgt.adoc[]" as reference.additional_Reference_from_properties_tgt << V >> {
  - **referenced_AntoraComponent** : (nvarchar(128))
  - **referenced_AntoraModule** : (nvarchar(128))
  - **referenced_Schema** : (nvarchar(128))
  - **referenced_Object** : (nvarchar(128))
  **referenced_Column** : (nvarchar(128))
  - **referencing_AntoraComponent** : (nvarchar(128))
  - **referencing_AntoraModule** : (nvarchar(128))
  - **referencing_Schema** : (nvarchar(128))
  - **referencing_Object** : (nvarchar(128))
  **referencing_Column** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_from_ssas_src.adoc[]" as reference.additional_Reference_from_ssas_src << V >> {
  **referenced_AntoraComponent** : (nvarchar(128))
  **referenced_AntoraModule** : (nvarchar(128))
  **referenced_Schema** : (nvarchar(max))
  **referenced_Object** : (nvarchar(max))
  **referenced_Column** : (nvarchar(500))
  **referencing_AntoraComponent** : (nvarchar(max))
  **referencing_AntoraModule** : (nvarchar(max))
  - **referencing_Schema** : (nvarchar(128))
  - **referencing_Object** : (nvarchar(128))
  **referencing_Column** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_from_ssas_tgt.adoc[]" as reference.additional_Reference_from_ssas_tgt << V >> {
  - **referenced_AntoraComponent** : (nvarchar(128))
  - **referenced_AntoraModule** : (nvarchar(128))
  - **referenced_Schema** : (nvarchar(128))
  - **referenced_Object** : (nvarchar(128))
  **referenced_Column** : (nvarchar(128))
  - **referencing_AntoraComponent** : (nvarchar(128))
  - **referencing_AntoraModule** : (nvarchar(128))
  - **referencing_Schema** : (nvarchar(128))
  - **referencing_Object** : (nvarchar(128))
  **referencing_Column** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_guid.adoc[]" as reference.additional_Reference_guid << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_is_external.adoc[]" as reference.additional_Reference_is_external << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_object.adoc[]" as reference.additional_Reference_Object << V >> {
  - **AntoraComponent** : (nvarchar(128))
  - **AntoraModule** : (nvarchar(128))
  - **SchemaName** : (nvarchar(128))
  - **ObjectName** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_object_t.adoc[]" as reference.additional_Reference_Object_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_objectcolumn.adoc[]" as reference.additional_Reference_ObjectColumn << V >> {
  - **AntoraComponent** : (nvarchar(128))
  - **AntoraModule** : (nvarchar(128))
  - **SchemaName** : (nvarchar(128))
  - **ObjectName** : (nvarchar(128))
  **ColumnName** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_objectcolumn_t.adoc[]" as reference.additional_Reference_ObjectColumn_T << U >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_wo_columns_from_properties_src.adoc[]" as reference.additional_Reference_wo_columns_from_properties_src << V >> {
  **referenced_AntoraComponent** : (nvarchar(max))
  **referenced_AntoraModule** : (nvarchar(max))
  **referenced_Schema** : (nvarchar(max))
  **referenced_Object** : (nvarchar(max))
  **referencing_AntoraComponent** : (nvarchar(max))
  **referencing_AntoraModule** : (nvarchar(max))
  **referencing_Schema** : (nvarchar(max))
  **referencing_Object** : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_wo_columns_from_properties_tgt.adoc[]" as reference.additional_Reference_wo_columns_from_properties_tgt << V >> {
  - **referenced_AntoraComponent** : (nvarchar(128))
  - **referenced_AntoraModule** : (nvarchar(128))
  - **referenced_Schema** : (nvarchar(128))
  - **referenced_Object** : (nvarchar(128))
  - **referencing_AntoraComponent** : (nvarchar(128))
  - **referencing_AntoraModule** : (nvarchar(128))
  - **referencing_Schema** : (nvarchar(128))
  - **referencing_Object** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_reference.adoc[]" as reference.RepoObject_reference << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_reference_additional.adoc[]" as reference.RepoObject_reference_additional << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_reference_persistence.adoc[]" as reference.RepoObject_reference_persistence << V >> {
  **referenced_RepoObject_guid** : (uniqueidentifier)
  - **referencing_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_reference_persistence_target_as_source.adoc[]" as reference.RepoObject_reference_persistence_target_as_source << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_reference_persistence_target_as_source_explicit.adoc[]" as reference.RepoObject_reference_persistence_target_as_source_explicit << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_reference_sqlexpressiondependencies.adoc[]" as reference.RepoObject_reference_SqlExpressionDependencies << V >> {
  **referenced_RepoObject_guid** : (uniqueidentifier)
  **referencing_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_reference_t.adoc[]" as reference.RepoObject_reference_T << U >> {
  - **referenced_RepoObject_guid** : (uniqueidentifier)
  - **referencing_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_reference_union.adoc[]" as reference.RepoObject_reference_union << V >> {
  **referenced_RepoObject_guid** : (uniqueidentifier)
  **referencing_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_reference_virtual.adoc[]" as reference.RepoObject_reference_virtual << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_referencedreferencing.adoc[]" as reference.RepoObject_ReferencedReferencing << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectsource_virtual.adoc[]" as reference.RepoObjectSource_virtual << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **Source_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject.adoc[]" as repo.RepoObject << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_external_src.adoc[]" as repo.RepoObject_external_src << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_external_tgt.adoc[]" as repo.RepoObject_external_tgt << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_gross_persistence.adoc[]" as repo.RepoObject_gross_persistence << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_persistence.adoc[]" as repo.RepoObject_persistence << U >> {
  - **target_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_ssas_src.adoc[]" as repo.RepoObject_SSAS_src << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_ssas_tgt.adoc[]" as repo.RepoObject_SSAS_tgt << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn.adoc[]" as repo.RepoObjectColumn << U >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn_external_src.adoc[]" as repo.RepoObjectColumn_external_src << V >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn_external_tgt.adoc[]" as repo.RepoObjectColumn_external_tgt << V >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn_ssas_src.adoc[]" as repo.RepoObjectColumn_SSAS_src << V >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn_ssas_tgt.adoc[]" as repo.RepoObjectColumn_SSAS_tgt << V >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.reposchema.adoc[]" as repo.RepoSchema << U >> {
  - **RepoSchema_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.reposchema_ssas_src.adoc[]" as repo.RepoSchema_ssas_src << V >> {
  - **RepoSchema_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:repo.reposchema_ssas_tgt.adoc[]" as repo.RepoSchema_ssas_tgt << V >> {
  - **RepoSchema_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.syscolumn_repoobjectcolumn_via_name.adoc[]" as repo.SysColumn_RepoObjectColumn_via_name << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.sysobject_repoobject_via_name.adoc[]" as repo.SysObject_RepoObject_via_name << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo_sys.extendedproperties.adoc[]" as repo_sys.ExtendedProperties << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo_sys.sql_expression_dependencies.adoc[]" as repo_sys.sql_expression_dependencies << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo_sys.syscolumn.adoc[]" as repo_sys.SysColumn << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo_sys.sysobject.adoc[]" as repo_sys.SysObject << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.additional_reference_step1.adoc[]" as ssas.additional_Reference_step1 << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json.adoc[]" as ssas.model_json << U >> {
  - **databasename** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_10.adoc[]" as ssas.model_json_10 << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_20.adoc[]" as ssas.model_json_20 << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_201_descriptions_multiline.adoc[]" as ssas.model_json_201_descriptions_multiline << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_2011_descriptions_stragg.adoc[]" as ssas.model_json_2011_descriptions_StrAgg << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31_tables.adoc[]" as ssas.model_json_31_tables << V >> {
  - **databasename** : (nvarchar(128))
  **tables_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31_tables_t.adoc[]" as ssas.model_json_31_tables_T << U >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_311_tables_columns.adoc[]" as ssas.model_json_311_tables_columns << V >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  **tables_columns_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_311_tables_columns_t.adoc[]" as ssas.model_json_311_tables_columns_T << U >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  - **tables_columns_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_313_tables_partitions.adoc[]" as ssas.model_json_313_tables_partitions << V >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  **tables_partitions_name** : (nvarchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_3131_tables_partitions_source.adoc[]" as ssas.model_json_3131_tables_partitions_source << V >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  **tables_partitions_name** : (nvarchar(500))
  **tables_partitions_source_name** : (nvarchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31311_tables_partitions_source_posfrom.adoc[]" as ssas.model_json_31311_tables_partitions_source_PosFrom << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_313111_tables_partitions_source_stringfrom.adoc[]" as ssas.model_json_313111_tables_partitions_source_StringFrom << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_3131111_tables_partitions_source_posdot.adoc[]" as ssas.model_json_3131111_tables_partitions_source_PosDot << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31311111_tables_partitions_source_part123.adoc[]" as ssas.model_json_31311111_tables_partitions_source_Part123 << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_33_datasources.adoc[]" as ssas.model_json_33_dataSources << V >> {
  - **databasename** : (nvarchar(128))
  **dataSources_name** : (nvarchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_33_datasources_t.adoc[]" as ssas.model_json_33_dataSources_T << U >> {
  - **databasename** : (nvarchar(128))
  - **dataSources_name** : (nvarchar(500))
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.columns.adoc[]" as sys_dwh.columns << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.computed_columns.adoc[]" as sys_dwh.computed_columns << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.default_constraints.adoc[]" as sys_dwh.default_constraints << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.extended_properties.adoc[]" as sys_dwh.extended_properties << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.identity_columns.adoc[]" as sys_dwh.identity_columns << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.indexes.adoc[]" as sys_dwh.indexes << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.objects.adoc[]" as sys_dwh.objects << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.parameters.adoc[]" as sys_dwh.parameters << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.schemas.adoc[]" as sys_dwh.schemas << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.sql_expression_dependencies.adoc[]" as sys_dwh.sql_expression_dependencies << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.sql_modules.adoc[]" as sys_dwh.sql_modules << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.tables.adoc[]" as sys_dwh.tables << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.types.adoc[]" as sys_dwh.types << SN >> {
  --
}

config.ftv_dwh_database <.. repo_sys.ExtendedProperties
config.ftv_dwh_database <.. repo_sys.SysColumn
config.ftv_dwh_database <.. repo_sys.sql_expression_dependencies
config.ftv_get_parameter_value <.. repo.RepoObject_external_src
config.ftv_get_parameter_value <.. ssas.additional_Reference_step1
config.ftv_get_parameter_value <.. reference.additional_Reference_is_external
config.Parameter <.. config.ftv_dwh_database
config.Parameter <.. property.PropertyName_RepoObject
config.Parameter <.. config.ftv_get_parameter_value
configT.Parameter_default <.. config.Parameter
configT.spt_values <.. configT.type
configT.type <.. repo.RepoObject_gross_persistence
configT.type <.. reference.RepoObject_ReferencedReferencing
docs.fs_cleanStringForFilename <.. reference.RepoObject_ReferencedReferencing
docs.fs_cleanStringForFilename <.. repo.RepoObject_gross_persistence
property.external_RepoObjectProperty <.. property.RepoObjectProperty_external_src
property.PropertyName_RepoObject <.. property.PropertyName_RepoObject_T
property.PropertyName_RepoObject_T <.. property.RepoObjectProperty_external_tgt
property.RepoObjectProperty <.. property.PropertyName_RepoObject
property.RepoObjectProperty <.. property.RepoObjectProperty_SelectedPropertyName_split
property.RepoObjectProperty_external_src <.. property.RepoObjectProperty_external_tgt
property.RepoObjectProperty_external_tgt <.. property.RepoObjectProperty
property.RepoObjectProperty_SelectedPropertyName_split <.. reference.additional_Reference_wo_columns_from_properties_src
property.RepoObjectProperty_SelectedPropertyName_split <.. reference.additional_Reference_from_properties_src
reference.additional_Reference <.. reference.additional_Reference_guid
reference.additional_Reference <.. reference.additional_Reference_is_external
reference.additional_Reference_from_properties_src <.. reference.additional_Reference_from_properties_tgt
reference.additional_Reference_from_properties_tgt <.. reference.additional_Reference
reference.additional_Reference_from_ssas_src <.. reference.additional_Reference_from_ssas_tgt
reference.additional_Reference_from_ssas_tgt <.. reference.additional_Reference
reference.additional_Reference_guid <.. reference.RepoObject_reference_additional
reference.additional_Reference_is_external <.. reference.additional_Reference_ObjectColumn
reference.additional_Reference_is_external <.. reference.additional_Reference_Object
reference.additional_Reference_Object <.. reference.additional_Reference_Object_T
reference.additional_Reference_Object_T <.. repo.RepoObject_external_src
reference.additional_Reference_Object_T <.. repo.RepoObjectColumn_external_src
reference.additional_Reference_ObjectColumn <.. reference.additional_Reference_ObjectColumn_T
reference.additional_Reference_ObjectColumn_T <.. repo.RepoObjectColumn_external_src
reference.additional_Reference_wo_columns_from_properties_src <.. reference.additional_Reference_wo_columns_from_properties_tgt
reference.additional_Reference_wo_columns_from_properties_tgt <.. reference.additional_Reference
reference.RepoObject_reference <.. reference.RepoObject_reference_T
reference.RepoObject_reference_additional <.. reference.RepoObject_reference_union
reference.RepoObject_reference_persistence <.. reference.RepoObject_reference_union
reference.RepoObject_reference_persistence_target_as_source <.. reference.RepoObject_reference
reference.RepoObject_reference_persistence_target_as_source <.. reference.RepoObject_reference_union
reference.RepoObject_reference_persistence_target_as_source_explicit <.. reference.RepoObject_reference_union
reference.RepoObject_reference_persistence_target_as_source_explicit <.. reference.RepoObject_reference
reference.RepoObject_reference_SqlExpressionDependencies <.. reference.RepoObject_reference_persistence_target_as_source_explicit
reference.RepoObject_reference_SqlExpressionDependencies <.. reference.RepoObject_reference_persistence_target_as_source
reference.RepoObject_reference_SqlExpressionDependencies <.. reference.RepoObject_reference_union
reference.RepoObject_reference_T <.. reference.RepoObject_ReferencedReferencing
reference.RepoObject_reference_union <.. reference.RepoObject_reference
reference.RepoObject_reference_virtual <.. reference.RepoObject_reference_union
reference.RepoObjectSource_virtual <.. reference.RepoObject_reference_virtual
repo.RepoObject <.. reference.RepoObject_reference_persistence
repo.RepoObject <.. repo.SysObject_RepoObject_via_name
repo.RepoObject <.. repo.SysColumn_RepoObjectColumn_via_name
repo.RepoObject <.. reference.RepoObject_reference_persistence_target_as_source_explicit
repo.RepoObject <.. repo.RepoObject_gross_persistence
repo.RepoObject <.. repo.RepoObjectColumn_external_src
repo.RepoObject <.. property.RepoObjectProperty_external_tgt
repo.RepoObject <.. reference.additional_Reference_guid
repo.RepoObject <.. reference.RepoObject_reference_virtual
repo.RepoObject <.. repo.RepoObject_external_src
repo.RepoObject <.. reference.RepoObject_reference_SqlExpressionDependencies
repo.RepoObject_external_src <.. repo.RepoObject_external_tgt
repo.RepoObject_external_tgt <.. repo.RepoObject
repo.RepoObject_external_tgt <.. repo.RepoObjectColumn_external_tgt
repo.RepoObject_gross_persistence <.. reference.RepoObject_reference_persistence_target_as_source
repo.RepoObject_persistence <.. reference.RepoObject_reference_persistence
repo.RepoObject_persistence <.. reference.RepoObject_reference_persistence_target_as_source_explicit
repo.RepoObject_persistence <.. repo.RepoObject_gross_persistence
repo.RepoObject_SSAS_src <.. repo.RepoObject_SSAS_tgt
repo.RepoObject_SSAS_tgt <.. repo.RepoObjectColumn_SSAS_tgt
repo.RepoObject_SSAS_tgt <.. repo.RepoObject
repo.RepoObjectColumn <.. reference.additional_Reference_guid
repo.RepoObjectColumn <.. repo.SysColumn_RepoObjectColumn_via_name
repo.RepoObjectColumn_external_src <.. repo.RepoObjectColumn_external_tgt
repo.RepoObjectColumn_external_tgt <.. repo.RepoObjectColumn
repo.RepoObjectColumn_SSAS_src <.. repo.RepoObjectColumn_SSAS_tgt
repo.RepoObjectColumn_SSAS_tgt <.. repo.RepoObjectColumn
repo.RepoSchema <.. repo.RepoObject_SSAS_src
repo.RepoSchema_ssas_src <.. repo.RepoSchema_ssas_tgt
repo.RepoSchema_ssas_tgt <.. repo.RepoSchema
repo.SysColumn_RepoObjectColumn_via_name <.. repo_sys.sql_expression_dependencies
repo.SysObject_RepoObject_via_name <.. repo_sys.sql_expression_dependencies
repo_sys.ExtendedProperties <.. repo_sys.SysColumn
repo_sys.ExtendedProperties <.. repo_sys.SysObject
repo_sys.sql_expression_dependencies <.. reference.RepoObject_reference_SqlExpressionDependencies
repo_sys.SysColumn <.. repo.SysColumn_RepoObjectColumn_via_name
repo_sys.SysObject <.. repo_sys.SysColumn
repo_sys.SysObject <.. repo.SysObject_RepoObject_via_name
ssas.additional_Reference_step1 <.. reference.additional_Reference_from_ssas_src
ssas.model_json <.. ssas.model_json_10
ssas.model_json_10 <.. ssas.model_json_20
ssas.model_json_20 <.. repo.RepoSchema_ssas_src
ssas.model_json_20 <.. ssas.model_json_33_dataSources
ssas.model_json_20 <.. ssas.model_json_31_tables
ssas.model_json_20 <.. ssas.model_json_201_descriptions_multiline
ssas.model_json_201_descriptions_multiline <.. ssas.model_json_2011_descriptions_StrAgg
ssas.model_json_2011_descriptions_StrAgg <.. repo.RepoSchema_ssas_src
ssas.model_json_31_tables <.. ssas.model_json_31_tables_T
ssas.model_json_31_tables_T <.. ssas.model_json_313_tables_partitions
ssas.model_json_31_tables_T <.. ssas.model_json_311_tables_columns
ssas.model_json_31_tables_T <.. repo.RepoObject_SSAS_src
ssas.model_json_311_tables_columns <.. ssas.model_json_311_tables_columns_T
ssas.model_json_311_tables_columns_T <.. repo.RepoObjectColumn_SSAS_src
ssas.model_json_311_tables_columns_T <.. ssas.additional_Reference_step1
ssas.model_json_313_tables_partitions <.. ssas.model_json_3131_tables_partitions_source
ssas.model_json_3131_tables_partitions_source <.. ssas.model_json_31311_tables_partitions_source_PosFrom
ssas.model_json_31311_tables_partitions_source_PosFrom <.. ssas.model_json_313111_tables_partitions_source_StringFrom
ssas.model_json_313111_tables_partitions_source_StringFrom <.. ssas.model_json_3131111_tables_partitions_source_PosDot
ssas.model_json_3131111_tables_partitions_source_PosDot <.. ssas.model_json_31311111_tables_partitions_source_Part123
ssas.model_json_31311111_tables_partitions_source_Part123 <.. ssas.additional_Reference_step1
ssas.model_json_33_dataSources <.. ssas.model_json_33_dataSources_T
ssas.model_json_33_dataSources_T <.. ssas.additional_Reference_step1
sys_dwh.columns <.. repo_sys.SysColumn
sys_dwh.columns <.. repo_sys.ExtendedProperties
sys_dwh.computed_columns <.. repo_sys.SysColumn
sys_dwh.default_constraints <.. repo_sys.SysColumn
sys_dwh.extended_properties <.. repo_sys.ExtendedProperties
sys_dwh.identity_columns <.. repo_sys.SysColumn
sys_dwh.indexes <.. repo_sys.ExtendedProperties
sys_dwh.objects <.. repo_sys.SysObject
sys_dwh.objects <.. repo_sys.ExtendedProperties
sys_dwh.parameters <.. repo_sys.ExtendedProperties
sys_dwh.schemas <.. repo_sys.ExtendedProperties
sys_dwh.schemas <.. repo_sys.SysObject
sys_dwh.sql_expression_dependencies <.. repo_sys.sql_expression_dependencies
sys_dwh.sql_modules <.. repo_sys.SysObject
sys_dwh.tables <.. repo_sys.SysObject
sys_dwh.types <.. repo_sys.SysColumn

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_30_0_objectref[]

=== PlantUML 0 30 ObjectRef

// tag::puml_entity_0_30_objectref[]
[plantuml, entity_0_30_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:dmdocs.unit.adoc[]" as dmdocs.unit << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.antoranavlistpage_by_schema.adoc[]" as docs.AntoraNavListPage_by_schema << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.antoranavlistpage_by_type.adoc[]" as docs.AntoraNavListPage_by_type << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.antoranavlistrepoobject_by_schema.adoc[]" as docs.AntoraNavListRepoObject_by_schema << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.antoranavlistrepoobject_by_schema_type.adoc[]" as docs.AntoraNavListRepoObject_by_schema_type << V >> {
  - **RepoObject_schema_name** : (nvarchar(128))
  **type** : (char(2))
  --
}

entity "puml-link:dhw:sqldb:docs.antoranavlistrepoobject_by_type.adoc[]" as docs.AntoraNavListRepoObject_by_type << V >> {
  **type** : (char(2))
  --
}

entity "puml-link:dhw:sqldb:docs.antorapage_indexsemanticgroup.adoc[]" as docs.AntoraPage_IndexSemanticGroup << V >> {
  - **page_content** : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:docs.antorapage_objectbyschema.adoc[]" as docs.AntoraPage_ObjectBySchema << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.antorapage_objectbytype.adoc[]" as docs.AntoraPage_ObjectByType << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.foreignkey_relationscript.adoc[]" as docs.ForeignKey_RelationScript << V >> {
  **referenced_RepoObject_guid** : (uniqueidentifier)
  **referencing_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:docs.ftv_repoobject_reference_plantuml_entityreflist.adoc[]" as docs.ftv_RepoObject_Reference_PlantUml_EntityRefList << IF >> {
  --
}

entity "puml-link:dhw:sqldb:docs.indexsemanticgroup.adoc[]" as docs.IndexSemanticgroup << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.indexsemanticgrouppatterndatatype.adoc[]" as docs.IndexSemanticgroupPatterndatatype << V >> {
  **IndexSemanticGroup** : (nvarchar(512))
  **IndexPatternColumnDatatype** : (nvarchar(4000))
  --
}

entity "puml-link:dhw:sqldb:docs.objectrefcyclic.adoc[]" as docs.ObjectRefCyclic << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.objectrefcyclic_entitylist.adoc[]" as docs.ObjectRefCyclic_EntityList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_adoc.adoc[]" as docs.RepoObject_Adoc << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_adoc_t.adoc[]" as docs.RepoObject_Adoc_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_antoraxrefcultureslist.adoc[]" as docs.RepoObject_AntoraXrefCulturesList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_columnlist.adoc[]" as docs.RepoObject_ColumnList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_columnlist_t.adoc[]" as docs.RepoObject_ColumnList_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_indexlist.adoc[]" as docs.RepoObject_IndexList << V >> {
  **RepoObject_guid** : (uniqueidentifier)
  **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_indexlist_t.adoc[]" as docs.RepoObject_IndexList_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_measuredescriptionlist.adoc[]" as docs.RepoObject_MeasureDescriptionList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_measurelist.adoc[]" as docs.RepoObject_MeasureList << V >> {
  **RepoObject_guid** : (uniqueidentifier)
  **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_outputfilter.adoc[]" as docs.RepoObject_OutputFilter << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_outputfilter_t.adoc[]" as docs.RepoObject_OutputFilter_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_outputfilter_t_gross.adoc[]" as docs.RepoObject_OutputFilter_T_gross << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml.adoc[]" as docs.RepoObject_Plantuml << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_colreflist_1_1.adoc[]" as docs.RepoObject_Plantuml_ColRefList_1_1 << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_entity.adoc[]" as docs.RepoObject_Plantuml_Entity << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_entity_t.adoc[]" as docs.RepoObject_Plantuml_Entity_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_fkreflist.adoc[]" as docs.RepoObject_PlantUml_FkRefList << V >> {
  **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_pumlentityfklist.adoc[]" as docs.RepoObject_PlantUml_PumlEntityFkList << V >> {
  **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_t.adoc[]" as docs.RepoObject_Plantuml_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.schema_entitylist.adoc[]" as docs.Schema_EntityList << V >> {
  - **RepoObject_schema_name** : (nvarchar(128))
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.schema_puml.adoc[]" as docs.Schema_puml << V >> {
  - **RepoSchema_guid** : (uniqueidentifier)
  **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.schema_pumlpartial_fkreflist.adoc[]" as docs.Schema_PumlPartial_FkRefList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.schema_ssasrelationlist.adoc[]" as docs.Schema_SsasRelationList << V >> {
  - **SchemaName** : (nvarchar(128))
  **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.unit_1_union.adoc[]" as docs.Unit_1_union << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.unit_2.adoc[]" as docs.Unit_2 << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.unit_3.adoc[]" as docs.Unit_3 << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport.adoc[]" as docs.usp_AntoraExport << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_objectnavigation.adoc[]" as docs.usp_AntoraExport_ObjectNavigation << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_objectpage.adoc[]" as docs.usp_AntoraExport_ObjectPage << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_objectpartialscontent.adoc[]" as docs.usp_AntoraExport_ObjectPartialsContent << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_objectpuml.adoc[]" as docs.usp_AntoraExport_ObjectPuml << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_repoobject_adoc_t.adoc[]" as docs.usp_PERSIST_RepoObject_Adoc_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_repoobject_columnlist_t.adoc[]" as docs.usp_PERSIST_RepoObject_ColumnList_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_repoobject_indexlist_t.adoc[]" as docs.usp_PERSIST_RepoObject_IndexList_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_repoobject_outputfilter_t.adoc[]" as docs.usp_PERSIST_RepoObject_OutputFilter_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_repoobject_plantuml_entity_t.adoc[]" as docs.usp_PERSIST_RepoObject_Plantuml_Entity_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_repoobject_plantuml_t.adoc[]" as docs.usp_PERSIST_RepoObject_Plantuml_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty_collect_source_rogross.adoc[]" as property.RepoObjectProperty_Collect_source_ROGross << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **property_name** : (varchar(39))
  --
}

entity "puml-link:dhw:sqldb:property.usp_repoobject_inheritance.adoc[]" as property.usp_RepoObject_Inheritance << P >> {
  --
}

entity "puml-link:dhw:sqldb:property.usp_repoobjectproperty_collect.adoc[]" as property.usp_RepoObjectProperty_collect << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.ftv_repoobject_columreferencerepoobject.adoc[]" as reference.ftv_RepoObject_ColumReferenceRepoObject << IF >> {
  --
}

entity "puml-link:dhw:sqldb:reference.ftv_repoobject_referencetree.adoc[]" as reference.ftv_RepoObject_ReferenceTree << IF >> {
  --
}

entity "puml-link:dhw:sqldb:reference.ftv_repoobject_referencetree_referenced.adoc[]" as reference.ftv_RepoObject_ReferenceTree_referenced << IF >> {
  --
}

entity "puml-link:dhw:sqldb:reference.ftv_repoobject_referencetree_referencing.adoc[]" as reference.ftv_RepoObject_ReferenceTree_referencing << IF >> {
  --
}

entity "puml-link:dhw:sqldb:reference.ftv_repoobject_referencetree_via_fullname.adoc[]" as reference.ftv_RepoObject_ReferenceTree_via_fullname << IF >> {
  --
}

entity "puml-link:dhw:sqldb:reference.persistence.adoc[]" as reference.Persistence << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.persistence_bidirectional.adoc[]" as reference.Persistence_bidirectional << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_referencedlist.adoc[]" as reference.RepoObject_ReferencedList << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_referencedreferencing.adoc[]" as reference.RepoObject_ReferencedReferencing << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_referencetree_0_30.adoc[]" as reference.RepoObject_ReferenceTree_0_30 << V >> {
  **RepoObject_guid** : (uniqueidentifier)
  **Referencing_guid** : (uniqueidentifier)
  **Referenced_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_referencetree_0_30_t.adoc[]" as reference.RepoObject_ReferenceTree_0_30_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **Referencing_guid** : (uniqueidentifier)
  - **Referenced_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_referencetree_30_0.adoc[]" as reference.RepoObject_ReferenceTree_30_0 << V >> {
  **RepoObject_guid** : (uniqueidentifier)
  **Referencing_guid** : (uniqueidentifier)
  **Referenced_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_referencetree_30_0_t.adoc[]" as reference.RepoObject_ReferenceTree_30_0_T << U >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_referencetree_referenced.adoc[]" as reference.RepoObject_ReferenceTree_referenced << V >> {
  **RepoObject_guid** : (uniqueidentifier)
  **Referenced_Depth** : (int)
  **Referencing_Depth** : (int)
  **Referenced_guid** : (uniqueidentifier)
  **Referencing_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_referencetree_referenced_30_0.adoc[]" as reference.RepoObject_ReferenceTree_referenced_30_0 << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  **Referenced_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_referencetree_referencing.adoc[]" as reference.RepoObject_ReferenceTree_referencing << V >> {
  **RepoObject_guid** : (uniqueidentifier)
  **Referenced_Depth** : (int)
  **Referencing_Depth** : (int)
  **Referenced_guid** : (uniqueidentifier)
  **Referencing_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_referencetree_referencing_0_30.adoc[]" as reference.RepoObject_ReferenceTree_referencing_0_30 << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  **Referencing_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_referencinglist.adoc[]" as reference.RepoObject_ReferencingList << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_persist_repoobject_referencetree_0_30_t.adoc[]" as reference.usp_PERSIST_RepoObject_ReferenceTree_0_30_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_persist_repoobject_referencetree_30_0_t.adoc[]" as reference.usp_PERSIST_RepoObject_ReferenceTree_30_0_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_repoobject_referencetree.adoc[]" as reference.usp_RepoObject_ReferenceTree << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_repoobject_referencetree_insert.adoc[]" as reference.usp_RepoObject_ReferenceTree_insert << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_repoobject_update_sysobjectqueryplan.adoc[]" as reference.usp_RepoObject_update_SysObjectQueryPlan << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_repoobjectsource_firstresultset.adoc[]" as reference.usp_RepoObjectSource_FirstResultSet << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_repoobjectsource_queryplan.adoc[]" as reference.usp_RepoObjectSource_QueryPlan << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.foreignkey_gross.adoc[]" as repo.ForeignKey_gross << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.foreignkey_indexes.adoc[]" as repo.ForeignKey_Indexes << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.foreignkey_indexes_union.adoc[]" as repo.ForeignKey_Indexes_union << V >> {
  **ForeignKey_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.foreignkey_indexes_union_t.adoc[]" as repo.ForeignKey_Indexes_union_T << U >> {
  **ForeignKey_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.foreignkey_virtual_indexes.adoc[]" as repo.ForeignKey_virtual_Indexes << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.index_gross.adoc[]" as repo.Index_gross << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.index_virtual_forupdate.adoc[]" as repo.Index_virtual_ForUpdate << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_gross.adoc[]" as repo.RepoObject_gross << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_gross2.adoc[]" as repo.RepoObject_gross2 << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_related_fk_union.adoc[]" as repo.RepoObject_related_FK_union << V >> {
  **RepoObject_guid** : (uniqueidentifier)
  **included_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_sat2.adoc[]" as repo.RepoObject_sat2 << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_sat2_t.adoc[]" as repo.RepoObject_sat2_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_sqlcreatetable.adoc[]" as repo.RepoObject_SqlCreateTable << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.usp_index_finish.adoc[]" as repo.usp_Index_finish << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_index_foreignkey.adoc[]" as repo.usp_Index_ForeignKey << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_index_inheritance.adoc[]" as repo.usp_index_inheritance << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_index_virtual_set.adoc[]" as repo.usp_Index_virtual_set << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_main.adoc[]" as repo.usp_main << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_persist_foreignkey_indexes_union_t.adoc[]" as repo.usp_PERSIST_ForeignKey_Indexes_union_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_persist_repoobject_sat2_t.adoc[]" as repo.usp_PERSIST_RepoObject_sat2_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.generatoruspstep_persistence_isinactive_setpoint.adoc[]" as uspgenerator.GeneratorUspStep_Persistence_IsInactive_setpoint << V >> {
  - **usp_id** : (int)
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.generatoruspstep_persistence_src.adoc[]" as uspgenerator.GeneratorUspStep_Persistence_src << V >> {
  - **usp_id** : (int)
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.usp_generatorusp_insert_update_persistence.adoc[]" as uspgenerator.usp_GeneratorUsp_insert_update_persistence << P >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.biml_package.adoc[]" as workflow.Biml_Package << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.biml_precedenceconstraints.adoc[]" as workflow.Biml_PrecedenceConstraints << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.biml_project.adoc[]" as workflow.Biml_Project << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.biml_task.adoc[]" as workflow.Biml_Task << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.proceduredependency.adoc[]" as workflow.ProcedureDependency << U >> {
  - **id** : (int)
  --
}

entity "puml-link:dhw:sqldb:workflow.proceduredependency_gross.adoc[]" as workflow.ProcedureDependency_gross << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.proceduredependency_input_persistencedependency.adoc[]" as workflow.ProcedureDependency_input_PersistenceDependency << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.proceduredependency_input_persistencedependency_s.adoc[]" as workflow.ProcedureDependency_input_PersistenceDependency_S << V >> {
  **referenced_Procedure_RepoObject_guid** : (uniqueidentifier)
  **referencing_Procedure_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:workflow.proceduredependency_persistencedependency_src.adoc[]" as workflow.ProcedureDependency_PersistenceDependency_src << V >> {
  **referenced_Procedure_RepoObject_guid** : (uniqueidentifier)
  **referencing_Procedure_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:workflow.proceduredependency_persistencedependency_tgt.adoc[]" as workflow.ProcedureDependency_PersistenceDependency_tgt << V >> {
  - **referenced_Procedure_RepoObject_guid** : (uniqueidentifier)
  - **referencing_Procedure_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:workflow.usp_persist_proceduredependency_persistencedependency_tgt.adoc[]" as workflow.usp_PERSIST_ProcedureDependency_PersistenceDependency_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.usp_persist_workflow_proceduredependency_t.adoc[]" as workflow.usp_PERSIST_Workflow_ProcedureDependency_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.usp_persist_workflowstep.adoc[]" as workflow.usp_PERSIST_WorkflowStep << P >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.usp_workflow.adoc[]" as workflow.usp_workflow << P >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.workflow_proceduredependency.adoc[]" as workflow.Workflow_ProcedureDependency << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.workflow_proceduredependency_all.adoc[]" as workflow.Workflow_ProcedureDependency_all << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.workflow_proceduredependency_t.adoc[]" as workflow.Workflow_ProcedureDependency_T << U >> {
  - **Workflow_id** : (int)
  - **referenced_Procedure_RepoObject_guid** : (uniqueidentifier)
  - **referencing_Procedure_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:workflow.workflow_proceduredependency_t_active.adoc[]" as workflow.Workflow_ProcedureDependency_T_active << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.workflow_proceduredependency_t_bidirectional.adoc[]" as workflow.Workflow_ProcedureDependency_T_bidirectional << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.workflow_proceduredependency_t_bidirectional_t.adoc[]" as workflow.Workflow_ProcedureDependency_T_bidirectional_T << U >> {
  - **Workflow_id** : (int)
  - **referenced_Procedure_RepoObject_guid** : (uniqueidentifier)
  - **referencing_Procedure_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:workflow.workflow_proceduredependency_t_notinsortorder.adoc[]" as workflow.Workflow_ProcedureDependency_T_NotInSortorder << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.workflow_proceduredependency_t_notinsortorder_check.adoc[]" as workflow.Workflow_ProcedureDependency_T_NotInSortorder_check << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.workflow_proceduredependency_t_redundant.adoc[]" as workflow.Workflow_ProcedureDependency_T_redundant << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.workflow_proceduredependency_t_taskname.adoc[]" as workflow.Workflow_ProcedureDependency_T_TaskName << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.workflow_proceduredependency_wo_redundant.adoc[]" as workflow.Workflow_ProcedureDependency_wo_redundant << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.workflowstep.adoc[]" as workflow.WorkflowStep << U >> {
  - **id** : (int)
  --
}

entity "puml-link:dhw:sqldb:workflow.workflowstep_active.adoc[]" as workflow.WorkflowStep_active << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.workflowstep_forupdate.adoc[]" as workflow.WorkflowStep_ForUpdate << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.workflowstep_src.adoc[]" as workflow.WorkflowStep_src << V >> {
  - **Workflow_id** : (int)
  **Procedure_RepoObject_guid** : (uniqueidentifier)
  --
}

docs.AntoraNavListPage_by_type <.. docs.usp_AntoraExport_ObjectNavigation
docs.AntoraNavListRepoObject_by_schema <.. docs.AntoraPage_ObjectBySchema
docs.AntoraNavListRepoObject_by_schema <.. docs.usp_AntoraExport_ObjectNavigation
docs.AntoraNavListRepoObject_by_schema_type <.. docs.usp_AntoraExport_ObjectNavigation
docs.AntoraNavListRepoObject_by_type <.. docs.AntoraPage_ObjectByType
docs.AntoraNavListRepoObject_by_type <.. docs.usp_AntoraExport_ObjectNavigation
docs.ftv_RepoObject_Reference_PlantUml_EntityRefList <.. docs.RepoObject_Plantuml
docs.IndexSemanticgroup <.. docs.AntoraPage_IndexSemanticGroup
docs.IndexSemanticgroupPatterndatatype <.. docs.IndexSemanticgroup
docs.ObjectRefCyclic_EntityList <.. docs.ObjectRefCyclic
docs.RepoObject_Adoc <.. docs.RepoObject_Adoc_T
docs.RepoObject_Adoc <.. docs.usp_PERSIST_RepoObject_Adoc_T
docs.REpoObject_Adoc_T <.. docs.usp_PERSIST_RepoObject_Adoc_T
docs.RepoObject_AntoraXrefCulturesList <.. docs.RepoObject_Adoc
docs.RepoObject_ColumnList <.. docs.RepoObject_ColumnList_T
docs.RepoObject_ColumnList <.. docs.usp_PERSIST_RepoObject_ColumnList_T
docs.RepoObject_ColumnList_T <.. docs.RepoObject_Adoc
docs.RepoObject_ColumnList_T <.. docs.RepoObject_Plantuml_Entity
docs.RepoObject_ColumnList_T <.. docs.usp_PERSIST_RepoObject_ColumnList_T
docs.RepoObject_IndexList <.. docs.usp_PERSIST_RepoObject_IndexList_T
docs.RepoObject_IndexList <.. docs.RepoObject_IndexList_T
docs.RepoObject_IndexList_T <.. docs.usp_PERSIST_RepoObject_IndexList_T
docs.RepoObject_IndexList_T <.. docs.RepoObject_Plantuml_Entity
docs.RepoObject_IndexList_T <.. docs.RepoObject_Adoc
docs.RepoObject_MeasureDescriptionList <.. docs.RepoObject_Adoc
docs.RepoObject_MeasureList <.. docs.RepoObject_Adoc
docs.RepoObject_MeasureList <.. docs.RepoObject_Plantuml_Entity
docs.RepoObject_OutputFilter <.. docs.RepoObject_OutputFilter_T
docs.RepoObject_OutputFilter <.. docs.usp_PERSIST_RepoObject_OutputFilter_T
docs.RepoObject_OutputFilter_T <.. docs.RepoObject_OutputFilter_T_gross
docs.RepoObject_OutputFilter_T <.. docs.RepoObject_AntoraXrefCulturesList
docs.RepoObject_OutputFilter_T <.. docs.usp_AntoraExport_ObjectPartialsContent
docs.RepoObject_OutputFilter_T <.. docs.usp_AntoraExport_ObjectPage
docs.RepoObject_OutputFilter_T <.. docs.AntoraNavListRepoObject_by_type
docs.RepoObject_OutputFilter_T <.. docs.AntoraNavListRepoObject_by_schema
docs.RepoObject_OutputFilter_T <.. docs.AntoraNavListRepoObject_by_schema_type
docs.RepoObject_OutputFilter_T <.. docs.RepoObject_ColumnList
docs.RepoObject_OutputFilter_T <.. docs.RepoObject_Plantuml_Entity
docs.RepoObject_OutputFilter_T <.. docs.RepoObject_Plantuml
docs.RepoObject_OutputFilter_T <.. docs.RepoObject_IndexList
docs.RepoObject_OutputFilter_T <.. docs.AntoraNavListPage_by_type
docs.RepoObject_OutputFilter_T <.. docs.IndexSemanticgroupPatterndatatype
docs.RepoObject_OutputFilter_T <.. docs.AntoraNavListPage_by_schema
docs.RepoObject_OutputFilter_T <.. docs.RepoObject_Plantuml_ColRefList_1_1
docs.RepoObject_OutputFilter_T <.. docs.Schema_puml
docs.RepoObject_OutputFilter_T <.. docs.Schema_SsasRelationList
docs.RepoObject_OutputFilter_T <.. docs.Unit_1_union
docs.RepoObject_OutputFilter_T <.. docs.usp_PERSIST_RepoObject_OutputFilter_T
docs.RepoObject_OutputFilter_T_gross <.. docs.RepoObject_MeasureDescriptionList
docs.RepoObject_OutputFilter_T_gross <.. docs.RepoObject_Adoc
docs.RepoObject_OutputFilter_T_gross <.. docs.RepoObject_MeasureList
docs.RepoObject_Plantuml <.. docs.usp_PERSIST_RepoObject_Plantuml_T
docs.RepoObject_Plantuml <.. docs.RepoObject_Plantuml_T
docs.RepoObject_Plantuml_ColRefList_1_1 <.. docs.RepoObject_Plantuml
docs.RepoObject_Plantuml_Entity <.. docs.RepoObject_Plantuml_Entity_T
docs.RepoObject_Plantuml_Entity <.. docs.usp_PERSIST_RepoObject_Plantuml_Entity_T
docs.RepoObject_Plantuml_Entity_T <.. docs.RepoObject_Adoc
docs.RepoObject_Plantuml_Entity_T <.. docs.ObjectRefCyclic_EntityList
docs.RepoObject_Plantuml_Entity_T <.. docs.RepoObject_PlantUml_PumlEntityFkList
docs.RepoObject_Plantuml_Entity_T <.. docs.ftv_RepoObject_Reference_PlantUml_EntityRefList
docs.RepoObject_Plantuml_Entity_T <.. docs.usp_PERSIST_RepoObject_Plantuml_Entity_T
docs.RepoObject_Plantuml_Entity_T <.. docs.Schema_EntityList
docs.RepoObject_PlantUml_FkRefList <.. docs.RepoObject_Plantuml
docs.RepoObject_PlantUml_PumlEntityFkList <.. docs.RepoObject_Plantuml
docs.RepoObject_Plantuml_T <.. docs.RepoObject_Adoc
docs.RepoObject_Plantuml_T <.. docs.usp_PERSIST_RepoObject_Plantuml_T
docs.Schema_EntityList <.. docs.Schema_puml
docs.Schema_puml <.. docs.AntoraNavListPage_by_schema
docs.Schema_PumlPartial_FkRefList <.. docs.Schema_puml
docs.Schema_SsasRelationList <.. docs.Schema_puml
docs.Unit_1_union <.. docs.Unit_2
docs.Unit_2 <.. docs.Unit_3
docs.Unit_3 <.. dmdocs.unit
docs.usp_AntoraExport_ObjectNavigation <.. docs.usp_AntoraExport
docs.usp_AntoraExport_ObjectPage <.. docs.usp_AntoraExport
docs.usp_AntoraExport_ObjectPartialsContent <.. docs.usp_AntoraExport
docs.usp_AntoraExport_ObjectPuml <.. docs.usp_AntoraExport
docs.usp_PERSIST_RepoObject_Adoc_T <.. docs.usp_AntoraExport_ObjectPartialsContent
docs.usp_PERSIST_RepoObject_ColumnList_T <.. docs.usp_AntoraExport_ObjectPartialsContent
docs.usp_PERSIST_RepoObject_IndexList_T <.. docs.usp_AntoraExport_ObjectPartialsContent
docs.usp_PERSIST_RepoObject_OutputFilter_T <.. docs.usp_AntoraExport
docs.usp_PERSIST_RepoObject_Plantuml_Entity_T <.. docs.usp_AntoraExport_ObjectPuml
docs.usp_PERSIST_RepoObject_Plantuml_T <.. docs.usp_AntoraExport_ObjectPuml
property.RepoObjectProperty_Collect_source_ROGross <.. property.usp_RepoObjectProperty_collect
property.usp_RepoObject_Inheritance <.. repo.usp_main
property.usp_RepoObjectProperty_collect <.. repo.usp_main
property.usp_RepoObjectProperty_collect <.. property.usp_RepoObject_Inheritance
reference.ftv_RepoObject_ReferenceTree <.. reference.RepoObject_ReferenceTree_0_30
reference.ftv_RepoObject_ReferenceTree <.. reference.RepoObject_ReferenceTree_30_0
reference.ftv_RepoObject_ReferenceTree_referenced <.. reference.RepoObject_ReferenceTree_referenced_30_0
reference.ftv_RepoObject_ReferenceTree_referenced <.. reference.RepoObject_ReferenceTree_referenced
reference.ftv_RepoObject_ReferenceTree_referencing <.. reference.RepoObject_ReferenceTree_referencing_0_30
reference.ftv_RepoObject_ReferenceTree_referencing <.. reference.RepoObject_ReferenceTree_referencing
reference.Persistence <.. reference.Persistence_bidirectional
reference.Persistence <.. workflow.ProcedureDependency_input_PersistenceDependency_S
reference.Persistence <.. workflow.ProcedureDependency_PersistenceDependency_src
reference.RepoObject_ReferencedList <.. repo.RepoObject_sat2
reference.RepoObject_ReferencedList <.. repo.RepoObject_gross2
reference.RepoObject_ReferencedReferencing <.. reference.usp_RepoObject_ReferenceTree_insert
reference.RepoObject_ReferencedReferencing <.. reference.ftv_RepoObject_ReferenceTree_referencing
reference.RepoObject_ReferencedReferencing <.. reference.ftv_RepoObject_ReferenceTree_referenced
reference.RepoObject_ReferencedReferencing <.. reference.RepoObject_ReferencingList
reference.RepoObject_ReferencedReferencing <.. reference.RepoObject_ReferencedList
reference.RepoObject_ReferencedReferencing <.. reference.ftv_RepoObject_ReferenceTree
reference.RepoObject_ReferencedReferencing <.. reference.ftv_RepoObject_ReferenceTree_via_fullname
reference.RepoObject_ReferencedReferencing <.. repo.RepoObject_gross
reference.RepoObject_ReferenceTree_0_30 <.. reference.usp_PERSIST_RepoObject_ReferenceTree_0_30_T
reference.RepoObject_ReferenceTree_0_30 <.. reference.RepoObject_ReferenceTree_0_30_T
reference.RepoObject_ReferenceTree_0_30_T <.. reference.usp_PERSIST_RepoObject_ReferenceTree_0_30_T
reference.RepoObject_ReferenceTree_30_0 <.. reference.usp_PERSIST_RepoObject_ReferenceTree_30_0_T
reference.RepoObject_ReferenceTree_30_0 <.. reference.RepoObject_ReferenceTree_30_0_T
reference.RepoObject_ReferenceTree_30_0_T <.. reference.usp_PERSIST_RepoObject_ReferenceTree_30_0_T
reference.RepoObject_ReferencingList <.. repo.RepoObject_sat2
reference.RepoObject_ReferencingList <.. repo.RepoObject_gross2
reference.usp_PERSIST_RepoObject_ReferenceTree_0_30_T <.. reference.usp_RepoObject_ReferenceTree
reference.usp_PERSIST_RepoObject_ReferenceTree_30_0_T <.. reference.usp_RepoObject_ReferenceTree
reference.usp_RepoObject_ReferenceTree_insert <.. repo.usp_main
reference.usp_RepoObject_update_SysObjectQueryPlan <.. repo.usp_main
reference.usp_RepoObjectSource_FirstResultSet <.. repo.usp_main
reference.usp_RepoObjectSource_QueryPlan <.. repo.usp_main
repo.ForeignKey_gross <.. docs.RepoObject_IndexList
repo.ForeignKey_Indexes <.. repo.ForeignKey_Indexes_union
repo.ForeignKey_Indexes <.. repo.usp_Index_ForeignKey
repo.ForeignKey_Indexes_union <.. repo.usp_PERSIST_ForeignKey_Indexes_union_T
repo.ForeignKey_Indexes_union <.. repo.ForeignKey_Indexes_union_T
repo.ForeignKey_Indexes_union_T <.. repo.usp_Index_finish
repo.ForeignKey_Indexes_union_T <.. docs.Schema_PumlPartial_FkRefList
repo.ForeignKey_Indexes_union_T <.. repo.usp_PERSIST_ForeignKey_Indexes_union_T
repo.ForeignKey_Indexes_union_T <.. docs.RepoObject_PlantUml_FkRefList
repo.ForeignKey_Indexes_union_T <.. repo.RepoObject_related_FK_union
repo.ForeignKey_Indexes_union_T <.. repo.ForeignKey_gross
repo.ForeignKey_Indexes_union_T <.. docs.ForeignKey_RelationScript
repo.ForeignKey_virtual_Indexes <.. repo.ForeignKey_Indexes_union
repo.Index_gross <.. repo.usp_Index_finish
repo.Index_gross <.. docs.RepoObject_IndexList
repo.Index_gross <.. docs.IndexSemanticgroupPatterndatatype
repo.Index_gross <.. repo.ForeignKey_gross
repo.Index_gross <.. repo.RepoObject_SqlCreateTable
repo.Index_gross <.. repo.usp_index_inheritance
repo.Index_gross <.. repo.usp_Index_virtual_set
repo.Index_gross <.. repo.ForeignKey_Indexes
repo.Index_gross <.. repo.ForeignKey_virtual_Indexes
repo.Index_virtual_ForUpdate <.. repo.usp_index_inheritance
repo.RepoObject_gross <.. workflow.WorkflowStep_src
repo.RepoObject_gross <.. repo.RepoObject_gross2
repo.RepoObject_gross <.. docs.Unit_1_union
repo.RepoObject_gross <.. repo.RepoObject_sat2
repo.RepoObject_gross <.. reference.RepoObject_ReferenceTree_referenced
repo.RepoObject_gross <.. reference.RepoObject_ReferenceTree_referencing
repo.RepoObject_gross <.. property.RepoObjectProperty_Collect_source_ROGross
repo.RepoObject_gross <.. reference.RepoObject_ReferenceTree_referenced_30_0
repo.RepoObject_gross <.. reference.RepoObject_ReferenceTree_referencing_0_30
repo.RepoObject_gross <.. reference.RepoObject_ReferenceTree_0_30
repo.RepoObject_gross <.. reference.RepoObject_ReferenceTree_30_0
repo.RepoObject_gross <.. reference.Persistence
repo.RepoObject_gross <.. repo.RepoObject_SqlCreateTable
repo.RepoObject_gross <.. uspgenerator.GeneratorUspStep_Persistence_IsInactive_setpoint
repo.RepoObject_gross <.. uspgenerator.GeneratorUspStep_Persistence_src
repo.RepoObject_gross <.. repo.Index_gross
repo.RepoObject_gross <.. reference.usp_RepoObjectSource_QueryPlan
repo.RepoObject_gross <.. reference.usp_RepoObjectSource_FirstResultSet
repo.RepoObject_gross <.. reference.usp_RepoObject_update_SysObjectQueryPlan
repo.RepoObject_gross <.. uspgenerator.usp_GeneratorUsp_insert_update_persistence
repo.RepoObject_gross <.. docs.RepoObject_Adoc
repo.RepoObject_gross <.. docs.RepoObject_OutputFilter
repo.RepoObject_gross <.. docs.RepoObject_Plantuml
repo.RepoObject_gross <.. repo.Index_virtual_ForUpdate
repo.RepoObject_gross2 <.. uspgenerator.GeneratorUspStep_Persistence_src
repo.RepoObject_related_FK_union <.. docs.RepoObject_PlantUml_PumlEntityFkList
repo.RepoObject_related_FK_union <.. docs.RepoObject_PlantUml_FkRefList
repo.RepoObject_sat2 <.. repo.RepoObject_sat2_T
repo.RepoObject_sat2 <.. repo.usp_PERSIST_RepoObject_sat2_T
repo.RepoObject_sat2_T <.. repo.usp_PERSIST_RepoObject_sat2_T
repo.RepoObject_sat2_T <.. docs.RepoObject_Adoc
repo.RepoObject_sat2_T <.. property.RepoObjectProperty_Collect_source_ROGross
repo.RepoObject_SqlCreateTable <.. reference.ftv_RepoObject_ColumReferenceRepoObject
repo.usp_Index_finish <.. repo.usp_index_inheritance
repo.usp_Index_finish <.. repo.usp_Index_ForeignKey
repo.usp_Index_ForeignKey <.. repo.usp_main
repo.usp_index_inheritance <.. repo.usp_main
repo.usp_Index_virtual_set <.. repo.usp_Index_ForeignKey
repo.usp_PERSIST_ForeignKey_Indexes_union_T <.. repo.usp_Index_ForeignKey
repo.usp_PERSIST_RepoObject_sat2_T <.. repo.usp_main
uspgenerator.GeneratorUspStep_Persistence_IsInactive_setpoint <.. uspgenerator.usp_GeneratorUsp_insert_update_persistence
uspgenerator.GeneratorUspStep_Persistence_src <.. uspgenerator.usp_GeneratorUsp_insert_update_persistence
uspgenerator.usp_GeneratorUsp_insert_update_persistence <.. repo.usp_main
workflow.Biml_Package <.. workflow.Biml_Project
workflow.Biml_PrecedenceConstraints <.. workflow.Biml_Task
workflow.Biml_Task <.. workflow.Biml_Package
workflow.ProcedureDependency <.. workflow.Workflow_ProcedureDependency
workflow.ProcedureDependency <.. workflow.Workflow_ProcedureDependency_all
workflow.ProcedureDependency <.. workflow.ProcedureDependency_input_PersistenceDependency
workflow.ProcedureDependency <.. workflow.ProcedureDependency_gross
workflow.ProcedureDependency_PersistenceDependency_src <.. workflow.usp_PERSIST_ProcedureDependency_PersistenceDependency_tgt
workflow.ProcedureDependency_PersistenceDependency_src <.. workflow.ProcedureDependency_PersistenceDependency_tgt
workflow.ProcedureDependency_PersistenceDependency_tgt <.. workflow.usp_PERSIST_ProcedureDependency_PersistenceDependency_tgt
workflow.ProcedureDependency_PersistenceDependency_tgt <.. workflow.ProcedureDependency
workflow.usp_PERSIST_ProcedureDependency_PersistenceDependency_tgt <.. workflow.usp_workflow
workflow.usp_PERSIST_Workflow_ProcedureDependency_T <.. workflow.usp_workflow
workflow.usp_PERSIST_WorkflowStep <.. workflow.usp_workflow
workflow.Workflow_ProcedureDependency <.. workflow.Workflow_ProcedureDependency_T
workflow.Workflow_ProcedureDependency <.. workflow.usp_PERSIST_Workflow_ProcedureDependency_T
workflow.Workflow_ProcedureDependency_all <.. workflow.Workflow_ProcedureDependency_wo_redundant
workflow.Workflow_ProcedureDependency_T <.. workflow.usp_workflow
workflow.Workflow_ProcedureDependency_T <.. workflow.Workflow_ProcedureDependency_T_bidirectional
workflow.Workflow_ProcedureDependency_T <.. workflow.Workflow_ProcedureDependency_T_active
workflow.Workflow_ProcedureDependency_T <.. workflow.usp_PERSIST_Workflow_ProcedureDependency_T
workflow.Workflow_ProcedureDependency_T_active <.. workflow.Workflow_ProcedureDependency_T_NotInSortorder
workflow.Workflow_ProcedureDependency_T_active <.. workflow.Workflow_ProcedureDependency_T_TaskName
workflow.Workflow_ProcedureDependency_T_active <.. workflow.Workflow_ProcedureDependency_T_redundant
workflow.Workflow_ProcedureDependency_T_bidirectional <.. workflow.usp_workflow
workflow.Workflow_ProcedureDependency_T_bidirectional <.. workflow.Workflow_ProcedureDependency_T_bidirectional_T
workflow.Workflow_ProcedureDependency_T_NotInSortorder <.. workflow.usp_workflow
workflow.Workflow_ProcedureDependency_T_NotInSortorder <.. workflow.Workflow_ProcedureDependency_T_NotInSortorder_check
workflow.Workflow_ProcedureDependency_T_NotInSortorder_check <.. workflow.usp_workflow
workflow.Workflow_ProcedureDependency_T_redundant <.. workflow.Workflow_ProcedureDependency_wo_redundant
workflow.Workflow_ProcedureDependency_T_redundant <.. workflow.usp_workflow
workflow.Workflow_ProcedureDependency_T_TaskName <.. workflow.Biml_PrecedenceConstraints
workflow.WorkflowStep <.. workflow.WorkflowStep_active
workflow.WorkflowStep <.. workflow.usp_PERSIST_WorkflowStep
workflow.WorkflowStep <.. workflow.WorkflowStep_ForUpdate
workflow.WorkflowStep_active <.. workflow.Workflow_ProcedureDependency_T_active
workflow.WorkflowStep_active <.. workflow.Biml_Task
workflow.WorkflowStep_active <.. workflow.Workflow_ProcedureDependency
workflow.WorkflowStep_active <.. workflow.usp_workflow
workflow.WorkflowStep_active <.. workflow.Workflow_ProcedureDependency_all
workflow.WorkflowStep_src <.. workflow.WorkflowStep
workflow.WorkflowStep_src <.. workflow.usp_PERSIST_WorkflowStep

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_0_30_objectref[]

=== PlantUML 1 1 ColumnRef

// tag::puml_entity_1_1_colref[]
[plantuml, entity_1_1_colref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:configt.type.adoc[]" as configT.type << V >> {
  **type** : (nvarchar(128))
  - is_DocsOutput : (int)
  type_desc : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:docs.fs_cleanstringforfilename.adoc[]" as docs.fs_cleanStringForFilename << FN >> {
  --
}

entity "puml-link:dhw:sqldb:reference.ftv_repoobject_referencetree.adoc[]" as reference.ftv_RepoObject_ReferenceTree << IF >> {
  Referenced_Depth : (int)
  Referenced_fullname : (nvarchar(261))
  Referenced_fullname2 : (nvarchar(257))
  Referenced_guid : (uniqueidentifier)
  referenced_is_DocsOutput : (int)
  Referenced_type : (char(2))
  Referencing_Depth : (int)
  Referencing_fullname : (nvarchar(261))
  Referencing_fullname2 : (nvarchar(257))
  Referencing_guid : (uniqueidentifier)
  referencing_is_DocsOutput : (int)
  Referencing_type : (varchar(2))
  RepoObject_guid : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.ftv_repoobject_referencetree_referenced.adoc[]" as reference.ftv_RepoObject_ReferenceTree_referenced << IF >> {
  Referenced_Depth : (int)
  Referenced_fullname : (nvarchar(261))
  Referenced_fullname2 : (nvarchar(257))
  Referenced_guid : (uniqueidentifier)
  referenced_is_DocsOutput : (int)
  Referenced_type : (char(2))
  Referencing_Depth : (int)
  Referencing_fullname : (nvarchar(261))
  Referencing_fullname2 : (nvarchar(257))
  Referencing_guid : (uniqueidentifier)
  referencing_is_DocsOutput : (int)
  Referencing_type : (varchar(2))
  RepoObject_guid : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.ftv_repoobject_referencetree_referencing.adoc[]" as reference.ftv_RepoObject_ReferenceTree_referencing << IF >> {
  Referenced_Depth : (int)
  Referenced_fullname : (nvarchar(261))
  Referenced_fullname2 : (nvarchar(257))
  Referenced_guid : (uniqueidentifier)
  referenced_is_DocsOutput : (int)
  Referenced_type : (char(2))
  Referencing_Depth : (int)
  Referencing_fullname : (nvarchar(261))
  Referencing_fullname2 : (nvarchar(257))
  Referencing_guid : (uniqueidentifier)
  referencing_is_DocsOutput : (int)
  Referencing_type : (varchar(2))
  RepoObject_guid : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.ftv_repoobject_referencetree_via_fullname.adoc[]" as reference.ftv_RepoObject_ReferenceTree_via_fullname << IF >> {
  Referenced_Depth : (int)
  Referenced_fullname : (nvarchar(261))
  Referenced_fullname2 : (nvarchar(257))
  Referenced_guid : (uniqueidentifier)
  referenced_is_DocsOutput : (int)
  Referenced_type : (char(2))
  Referencing_Depth : (int)
  Referencing_fullname : (nvarchar(261))
  Referencing_fullname2 : (nvarchar(257))
  Referencing_guid : (uniqueidentifier)
  referencing_is_DocsOutput : (int)
  Referencing_type : (varchar(2))
  RepoObject_fullname : (nvarchar(261))
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_reference_t.adoc[]" as reference.RepoObject_reference_T << U >> {
  - **referenced_RepoObject_guid** : (uniqueidentifier)
  - **referencing_RepoObject_guid** : (uniqueidentifier)
  - is_ReversePersistenceViaView : (bit)
  referenced_entity_name : (nvarchar(128))
  referenced_external_AntoraComponent : (nvarchar(128))
  referenced_external_AntoraModule : (nvarchar(128))
  - referenced_is_external : (bit)
  - referenced_is_PersistenceSource : (bit)
  - referenced_is_PersistenceTarget : (bit)
  referenced_schema_name : (nvarchar(128))
  referenced_type : (char(2))
  referencing_entity_name : (nvarchar(128))
  referencing_external_AntoraComponent : (nvarchar(128))
  referencing_external_AntoraModule : (nvarchar(128))
  - referencing_is_external : (bit)
  - referencing_is_PersistenceTarget : (bit)
  - referencing_is_PersistenceUspSourceRef : (bit)
  referencing_is_PersistenceUspTargetRef : (bit)
  referencing_schema_name : (nvarchar(128))
  referencing_type : (varchar(2))
  ~ referenced_AntoraComponent : (nvarchar(max))
  ~ referenced_AntoraModule : (nvarchar(max))
  # referenced_fullname : (nvarchar(261))
  # referenced_fullname2 : (nvarchar(257))
  ~ referenced_puml_entity : (nvarchar(4000))
  ~ referencing_AntoraComponent : (nvarchar(max))
  ~ referencing_AntoraModule : (nvarchar(max))
  # referencing_fullname : (nvarchar(261))
  # referencing_fullname2 : (nvarchar(257))
  ~ referencing_puml_entity : (nvarchar(4000))
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_referencedlist.adoc[]" as reference.RepoObject_ReferencedList << V >> {
  AntoraReferencedList : (nvarchar(max))
  Referencing_fullname : (nvarchar(261))
  Referencing_fullname2 : (nvarchar(257))
  - Referencing_guid : (uniqueidentifier)
  Referencing_type : (varchar(2))
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_referencedreferencing.adoc[]" as reference.RepoObject_ReferencedReferencing << V >> {
  - referenced_AntoraXref : (nvarchar(max))
  referenced_external_AntoraComponent : (nvarchar(128))
  referenced_external_AntoraModule : (nvarchar(128))
  - Referenced_fullname : (nvarchar(261))
  - Referenced_fullname2 : (nvarchar(257))
  - Referenced_guid : (uniqueidentifier)
  referenced_is_DocsOutput : (int)
  - referenced_is_external : (bit)
  Referenced_type : (char(2))
  - referencing_AntoraXref : (nvarchar(max))
  referencing_external_AntoraComponent : (nvarchar(128))
  referencing_external_AntoraModule : (nvarchar(128))
  - Referencing_fullname : (nvarchar(261))
  - Referencing_fullname2 : (nvarchar(257))
  - Referencing_guid : (uniqueidentifier)
  referencing_is_DocsOutput : (int)
  - referencing_is_external : (bit)
  Referencing_type : (varchar(2))
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_referencinglist.adoc[]" as reference.RepoObject_ReferencingList << V >> {
  AntoraReferencingList : (nvarchar(max))
  Referenced_fullname : (nvarchar(261))
  Referenced_fullname2 : (nvarchar(257))
  - Referenced_guid : (uniqueidentifier)
  Referenced_type : (char(2))
  --
}

entity "puml-link:dhw:sqldb:reference.usp_repoobject_referencetree_insert.adoc[]" as reference.usp_RepoObject_ReferenceTree_insert << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_gross.adoc[]" as repo.RepoObject_gross << V >> {
  AntoraComponent : (nvarchar(max))
  AntoraModule : (nvarchar(max))
  Description : (nvarchar(max))
  ExecutionLogId_action : (char(1))
  external_AntoraComponent : (nvarchar(128))
  external_AntoraModule : (nvarchar(128))
  external_DatabaseName : (nvarchar(128))
  external_RepoDatabaseName : (nvarchar(128))
  has_different_sys_names : (bit)
  has_execution_plan_issue : (bit)
  has_get_referenced_issue : (bit)
  has_history : (bit)
  has_history_columns : (bit)
  history_schema_name : (nvarchar(128))
  history_table_name : (nvarchar(128))
  indent_sql_modules_definition : (tinyint)
  Inheritance_StringAggSeparatorSql : (nvarchar(4000))
  InheritanceDefinition : (nvarchar(4000))
  InheritanceType : (tinyint)
  - is_DocsExclude : (bit)
  is_DocsOutput : (int)
  - is_external : (bit)
  - is_in_reference : (int)
  is_persistence : (bit)
  is_persistence_check_duplicate_per_pk : (bit)
  is_persistence_check_for_empty_source : (bit)
  is_persistence_delete_changed : (bit)
  is_persistence_delete_missing : (bit)
  is_persistence_insert : (bit)
  is_persistence_persist_source : (bit)
  is_persistence_truncate : (bit)
  is_persistence_update_changed : (bit)
  is_repo_managed : (bit)
  - is_RepoObject_name_uniqueidentifier : (int)
  is_required_ObjectMerge : (bit)
  - is_ssas : (bit)
  is_SysObject_missing : (bit)
  - is_SysObject_name_uniqueidentifier : (int)
  - modify_dt : (datetime)
  node_id : (bigint)
  persistence_source_RepoObject_fullname : (nvarchar(261))
  persistence_source_RepoObject_fullname2 : (nvarchar(257))
  persistence_source_RepoObject_guid : (uniqueidentifier)
  persistence_source_RepoObject_xref : (nvarchar(4000))
  persistence_source_SysObject_fullname : (nvarchar(261))
  persistence_source_SysObject_fullname_or_tempsource : (nvarchar(261))
  persistence_source_SysObject_fullname2 : (nvarchar(257))
  persistence_source_SysObject_xref : (nvarchar(4000))
  pk_index_guid : (uniqueidentifier)
  pk_IndexPatternColumnDatatype : (nvarchar(4000))
  pk_IndexPatternColumnName : (nvarchar(4000))
  pk_IndexPatternColumnName_new : (nvarchar(4000))
  pk_IndexSemanticGroup : (nvarchar(512))
  postscript : (nvarchar(max))
  prescript : (nvarchar(max))
  Property_ms_description : (nvarchar(4000))
  Repo_history_table_guid : (uniqueidentifier)
  Repo_temporal_type : (tinyint)
  - RepoObject_fullname : (nvarchar(261))
  - RepoObject_fullname2 : (nvarchar(257))
  - RepoObject_guid : (uniqueidentifier)
  - RepoObject_name : (nvarchar(128))
  RepoObject_Referencing_Count : (int)
  - RepoObject_schema_name : (nvarchar(128))
  - RepoObject_type : (char(2))
  RepoObject_type_name : (nvarchar(128))
  - SysObject_fullname : (nvarchar(261))
  - SysObject_fullname2 : (nvarchar(257))
  SysObject_id : (int)
  SysObject_modify_date : (datetime)
  - SysObject_name : (nvarchar(128))
  - SysObject_parent_object_id : (int)
  SysObject_query_executed_dt : (datetime)
  SysObject_query_plan : (xml)
  - SysObject_query_sql : (nvarchar(406))
  - SysObject_schema_name : (nvarchar(128))
  SysObject_type : (char(2))
  SysObject_type_name : (nvarchar(128))
  tables_dataCategory : (nvarchar(500))
  tables_description : (nvarchar(max))
  tables_isHidden : (bit)
  temporal_type : (tinyint)
  - usp_persistence_name : (nvarchar(140))
  usp_persistence_RepoObject_guid : (uniqueidentifier)
  uspgenerator_usp_id : (int)
  --
}

configT.type <.. reference.RepoObject_ReferencedReferencing
docs.fs_cleanStringForFilename <.. reference.RepoObject_ReferencedReferencing
reference.RepoObject_reference_T <.. reference.RepoObject_ReferencedReferencing
reference.RepoObject_ReferencedReferencing <.. reference.ftv_RepoObject_ReferenceTree
reference.RepoObject_ReferencedReferencing <.. reference.RepoObject_ReferencedList
reference.RepoObject_ReferencedReferencing <.. reference.ftv_RepoObject_ReferenceTree_via_fullname
reference.RepoObject_ReferencedReferencing <.. repo.RepoObject_gross
reference.RepoObject_ReferencedReferencing <.. reference.RepoObject_ReferencingList
reference.RepoObject_ReferencedReferencing <.. reference.ftv_RepoObject_ReferenceTree_referenced
reference.RepoObject_ReferencedReferencing <.. reference.ftv_RepoObject_ReferenceTree_referencing
reference.RepoObject_ReferencedReferencing <.. reference.usp_RepoObject_ReferenceTree_insert
"configT.type::is_DocsOutput" <-- "reference.RepoObject_ReferencedReferencing::referencing_is_DocsOutput"
"configT.type::is_DocsOutput" <-- "reference.RepoObject_ReferencedReferencing::referenced_is_DocsOutput"
"reference.RepoObject_reference_T::referenced_external_AntoraComponent" <-- "reference.RepoObject_ReferencedReferencing::referenced_external_AntoraComponent"
"reference.RepoObject_reference_T::referenced_external_AntoraModule" <-- "reference.RepoObject_ReferencedReferencing::referenced_external_AntoraModule"
"reference.RepoObject_reference_T::referenced_fullname" <-- "reference.RepoObject_ReferencedReferencing::Referenced_fullname"
"reference.RepoObject_reference_T::referenced_fullname2" <-- "reference.RepoObject_ReferencedReferencing::Referenced_fullname2"
"reference.RepoObject_reference_T::referenced_is_external" <-- "reference.RepoObject_ReferencedReferencing::referenced_is_external"
"reference.RepoObject_reference_T::referenced_RepoObject_guid" <-- "reference.RepoObject_ReferencedReferencing::Referenced_guid"
"reference.RepoObject_reference_T::referenced_type" <-- "reference.RepoObject_ReferencedReferencing::Referenced_type"
"reference.RepoObject_reference_T::referencing_external_AntoraComponent" <-- "reference.RepoObject_ReferencedReferencing::referencing_external_AntoraComponent"
"reference.RepoObject_reference_T::referencing_external_AntoraModule" <-- "reference.RepoObject_ReferencedReferencing::referencing_external_AntoraModule"
"reference.RepoObject_reference_T::referencing_fullname" <-- "reference.RepoObject_ReferencedReferencing::Referencing_fullname"
"reference.RepoObject_reference_T::referencing_fullname2" <-- "reference.RepoObject_ReferencedReferencing::Referencing_fullname2"
"reference.RepoObject_reference_T::referencing_is_external" <-- "reference.RepoObject_ReferencedReferencing::referencing_is_external"
"reference.RepoObject_reference_T::referencing_RepoObject_guid" <-- "reference.RepoObject_ReferencedReferencing::Referencing_guid"
"reference.RepoObject_reference_T::referencing_type" <-- "reference.RepoObject_ReferencedReferencing::Referencing_type"
"reference.RepoObject_ReferencedReferencing::referenced_fullname" <-- "reference.RepoObject_ReferencingList::Referenced_fullname"
"reference.RepoObject_ReferencedReferencing::Referenced_guid" <-- "reference.RepoObject_ReferencingList::Referenced_guid"
"reference.RepoObject_ReferencedReferencing::referencing_fullname" <-- "reference.RepoObject_ReferencedList::Referencing_fullname"
"reference.RepoObject_ReferencedReferencing::Referencing_guid" <-- "reference.RepoObject_ReferencedList::Referencing_guid"

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_colref[]


== sql_modules_definition

// tag::sql_modules_definition[]
[%collapsible]
=======
[source,sql,numbered,indent=0]
----

/*
per referencing RepoObject all directly referenced RepoOobject are listed

can be used in both directions:

* get all referenced per referencing
* get all referencing per referenced

////
old logic:

uses graph tables

* [graph].[RepoObject]
* [graph].[ReferencedObject]

----
Select
    Object1.RepoObject_fullname  As Referencing_fullname
  , Object1.RepoObject_fullname2 As Referencing_fullname2
  , Object1.RepoObject_guid      As Referencing_guid
  , Object1.RepoObject_type      As Referencing_type
  , Object2.RepoObject_fullname  As Referenced_fullname
  , Object2.RepoObject_fullname2 As Referenced_fullname2
  , Object2.RepoObject_guid      As Referenced_guid
  , Object2.RepoObject_type      As Referenced_type
From
    graph.RepoObject As Object1
  , graph.ReferencedObject As referenced
  , graph.RepoObject As Object2
Where Match(
    Object1-(referenced)->Object2);
----
////

*/
CREATE View reference.RepoObject_ReferencedReferencing
As
Select
    T1.referenced_fullname
  , T1.referenced_fullname2
  , Referenced_guid           = T1.referenced_RepoObject_guid
  , referenced_is_DocsOutput  = typ1.is_DocsOutput
  , T1.referenced_type
  , T1.referenced_external_AntoraComponent
  , T1.referenced_external_AntoraModule
  , T1.referenced_is_external
  , referenced_AntoraXref     = Concat (
                                           --* xref:target-page-filename.adoc[link text]
                                           --we need to convert to first argument nvarchar(max) to avoid the limit of 8000 byte
                                           Cast('* xref:' As NVarchar(Max))
                                         --, T1.referenced_external_AntoraComponent + ':'
                                         --, T1.referenced_external_AntoraModule + ':'
                                         , T1.referenced_AntoraComponent + ':'
                                         , T1.referenced_AntoraModule + ':'
                                         , docs.fs_cleanStringForFilename ( T1.referenced_fullname2 )
                                         , '.adoc[]'
                                         , ' in xref:' + T1.referenced_external_AntoraComponent + ':'
                                           + T1.referenced_external_AntoraModule + ':' + 'nav/objects-by-schema.adoc[]'
                                       )
  , T1.referencing_fullname
  , T1.referencing_fullname2
  , Referencing_guid          = T1.referencing_RepoObject_guid
  , T1.referencing_type
  , T1.referencing_external_AntoraComponent
  , T1.referencing_external_AntoraModule
  , T1.referencing_is_external
  , referencing_is_DocsOutput = typ2.is_DocsOutput
  , referencing_AntoraXref    = Concat (
                                           --* xref:target-page-filename.adoc[link text]
                                           --we need to convert to first argument nvarchar(max) to avoid the limit of 8000 byte
                                           Cast('* xref:' As NVarchar(Max))
                                         --, T1.referencing_external_AntoraComponent + ':'
                                         --, T1.referencing_external_AntoraModule + ':'
                                         , T1.referencing_AntoraComponent + ':'
                                         , T1.referencing_AntoraModule + ':'
                                         , docs.fs_cleanStringForFilename ( T1.referencing_fullname2 )
                                         , '.adoc[]'
                                         , ' in xref:' + T1.referencing_external_AntoraComponent + ':'
                                           + T1.referencing_external_AntoraModule + ':' + 'nav/objects-by-schema.adoc[]'
                                       )
From
    reference.RepoObject_reference_T As T1
    Left Outer Join
        configT.type                 As typ1
            On
            typ1.type = T1.referenced_type

    Left Outer Join
        configT.type                 As typ2
            On
            typ2.type = T1.referencing_type

----
=======
// end::sql_modules_definition[]


