// tag::HeaderFullDisplayName[]
= reference.RepoObjectSource_FirstResultSet - U
// end::HeaderFullDisplayName[]

== existing_properties

// tag::existing_properties[]

:ExistsProperty--antorareferencinglist:
:ExistsProperty--is_repo_managed:
:ExistsProperty--is_ssas:
:ExistsProperty--pk_index_guid:
:ExistsProperty--pk_indexpatterncolumndatatype:
:ExistsProperty--pk_indexpatterncolumnname:
:ExistsProperty--FK:
:ExistsProperty--AntoraIndexList:
:ExistsProperty--Columns:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
2C90291C-9D61-EB11-84DC-A81E8446D5B0
// end::RepoObject_guid[]

== RepoObject_FullDisplayName2

// tag::RepoObject_FullDisplayName2[]
reference.RepoObjectSource_FirstResultSet
// end::RepoObject_FullDisplayName2[]

== SysObject_type

// tag::SysObject_type[]
U 
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
user table
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
805577908
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2022-01-23 14:10:15
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]
[discrete]
== _


[#column-repoobjectunderlineguid]
=== RepoObject_guid

[cols="d,8a,m,m,m"]
|===
|1
|*RepoObject_guid*
|uniqueidentifier
|NOT NULL
|
|===

.Referencing Columns
--
* xref:reference.repoobjectcolumn_reference_firstresultset.adoc#column-referencingunderlinerepoobjectunderlineguid[+reference.RepoObjectColumn_reference_FirstResultSet.referencing_RepoObject_guid+]
--


[#column-columnunderlineordinal]
=== column_ordinal

[cols="d,8a,m,m,m"]
|===
|2
|*column_ordinal*
|int
|NOT NULL
|
|===


[#column-createdunderlinedt]
=== created_dt

[cols="d,8a,m,m,m"]
|===
|
|created_dt
|datetime
|NOT NULL
|
|===


[#column-isunderlinehidden]
=== is_hidden

[cols="d,8a,m,m,m"]
|===
|
|is_hidden
|bit
|NULL
|
|===

.Referencing Columns
--
* xref:reference.repoobjectcolumn_reference_firstresultset.adoc#column-isunderlinehidden[+reference.RepoObjectColumn_reference_FirstResultSet.is_hidden+]
--


[#column-sourceunderlinecolumnunderlinename]
=== source_column_name

[cols="d,8a,m,m,m"]
|===
|
|source_column_name
|nvarchar(128)
|NULL
|
|===

.Referencing Columns
--
* xref:reference.repoobjectcolumn_reference_firstresultset.adoc#column-referencedunderlinecolumnunderlinename[+reference.RepoObjectColumn_reference_FirstResultSet.referenced_column_name+]
--


[#column-sourceunderlinedatabaseunderlinename]
=== source_database_name

[cols="d,8a,m,m,m"]
|===
|
|source_database_name
|nvarchar(128)
|NULL
|
|===


[#column-sourceunderlineschemaunderlinename]
=== source_schema_name

[cols="d,8a,m,m,m"]
|===
|
|source_schema_name
|nvarchar(128)
|NULL
|
|===

.Referencing Columns
--
* xref:reference.repoobjectcolumn_reference_firstresultset.adoc#column-referencedunderlineschemaunderlinename[+reference.RepoObjectColumn_reference_FirstResultSet.referenced_schema_name+]
--


[#column-sourceunderlineserverunderlinename]
=== source_server_name

[cols="d,8a,m,m,m"]
|===
|
|source_server_name
|nvarchar(128)
|NULL
|
|===


[#column-sourceunderlinetableunderlinename]
=== source_table_name

[cols="d,8a,m,m,m"]
|===
|
|source_table_name
|nvarchar(128)
|NULL
|
|===

.Referencing Columns
--
* xref:reference.repoobjectcolumn_reference_firstresultset.adoc#column-referencedunderlineentityunderlinename[+reference.RepoObjectColumn_reference_FirstResultSet.referenced_entity_name+]
--


[#column-systemunderlinetypeunderlineid]
=== system_type_id

[cols="d,8a,m,m,m"]
|===
|
|system_type_id
|int
|NULL
|
|===


[#column-systemunderlinetypeunderlinename]
=== system_type_name

[cols="d,8a,m,m,m"]
|===
|
|system_type_name
|nvarchar(128)
|NULL
|
|===


[#column-targetunderlinecolumnunderlinename]
=== target_column_name

[cols="d,8a,m,m,m"]
|===
|
|target_column_name
|nvarchar(128)
|NULL
|
|===

.Referencing Columns
--
* xref:reference.repoobjectcolumn_reference_firstresultset.adoc#column-referencingunderlinecolumnunderlinename[+reference.RepoObjectColumn_reference_FirstResultSet.referencing_column_name+]
--


// end::AntoraColumnDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]
|1
|*<<column-repoobjectunderlineguid>>*
|uniqueidentifier
|NOT NULL
|

|2
|*<<column-columnunderlineordinal>>*
|int
|NOT NULL
|











// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]


|
|<<column-createdunderlinedt>>
|datetime
|NOT NULL
|

|
|<<column-isunderlinehidden>>
|bit
|NULL
|

|
|<<column-sourceunderlinecolumnunderlinename>>
|nvarchar(128)
|NULL
|

|
|<<column-sourceunderlinedatabaseunderlinename>>
|nvarchar(128)
|NULL
|

|
|<<column-sourceunderlineschemaunderlinename>>
|nvarchar(128)
|NULL
|

|
|<<column-sourceunderlineserverunderlinename>>
|nvarchar(128)
|NULL
|

|
|<<column-sourceunderlinetableunderlinename>>
|nvarchar(128)
|NULL
|

|
|<<column-systemunderlinetypeunderlineid>>
|int
|NULL
|

|
|<<column-systemunderlinetypeunderlinename>>
|nvarchar(128)
|NULL
|

|
|<<column-targetunderlinecolumnunderlinename>>
|nvarchar(128)
|NULL
|

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

[#index-pkunderlinerepoobjectsourceunderlinefirstresultset]
=== PK_RepoObjectSource_FirstResultSet

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-RepoObject_guid>>; uniqueidentifier
* <<column-column_ordinal>>; int
--
* PK, Unique, Real: 1, 1, 1


[#index-idxunderlinerepoobjectsourceunderlinefirstresultsetunderlineunderline1]
=== idx_RepoObjectSource_FirstResultSet++__++1

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-RepoObject_guid>>; uniqueidentifier
--
* PK, Unique, Real: 0, 0, 0
* ++FK_RepoObjectSource_FirstResultSet__RepoObject++ +
referenced: xref:repo.repoobject.adoc[], xref:repo.repoobject.adoc#index-pkunderlinerepoobject[+PK_RepoObject+]
* is disabled

// end::AntoraIndexList[]

== AntoraMeasureDetails

// tag::AntoraMeasureDetails[]

// end::AntoraMeasureDetails[]

== AntoraMeasureDescriptions



== AntoraParameterList

// tag::AntoraParameterList[]

// end::AntoraParameterList[]

== AntoraXrefCulturesList

// tag::AntoraXrefCulturesList[]
* xref:dhw:sqldb:reference.repoobjectsource_firstresultset.adoc[] - 
// end::AntoraXrefCulturesList[]

== cultures_count

// tag::cultures_count[]
1
// end::cultures_count[]

== Other tags

source: property.RepoObjectProperty_cross As rop_cross


=== additional_reference_csv

// tag::additional_reference_csv[]

// end::additional_reference_csv[]


=== AdocUspSteps

// tag::adocuspsteps[]

// end::adocuspsteps[]


=== AntoraReferencedList

// tag::antorareferencedlist[]

// end::antorareferencedlist[]


=== AntoraReferencingList

// tag::antorareferencinglist[]
* xref:dhw:sqldb:reference.repoobjectcolumn_reference_firstresultset.adoc[]
* xref:dhw:sqldb:reference.usp_repoobjectsource_firstresultset.adoc[]
// end::antorareferencinglist[]


=== Description

// tag::description[]

// end::description[]


=== exampleUsage

// tag::exampleusage[]

// end::exampleusage[]


=== exampleUsage_2

// tag::exampleusage_2[]

// end::exampleusage_2[]


=== exampleUsage_3

// tag::exampleusage_3[]

// end::exampleusage_3[]


=== exampleUsage_4

// tag::exampleusage_4[]

// end::exampleusage_4[]


=== exampleUsage_5

// tag::exampleusage_5[]

// end::exampleusage_5[]


=== exampleWrong_Usage

// tag::examplewrong_usage[]

// end::examplewrong_usage[]


=== has_execution_plan_issue

// tag::has_execution_plan_issue[]

// end::has_execution_plan_issue[]


=== has_get_referenced_issue

// tag::has_get_referenced_issue[]

// end::has_get_referenced_issue[]


=== has_history

// tag::has_history[]

// end::has_history[]


=== has_history_columns

// tag::has_history_columns[]

// end::has_history_columns[]


=== InheritanceType

// tag::inheritancetype[]

// end::inheritancetype[]


=== is_persistence

// tag::is_persistence[]

// end::is_persistence[]


=== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]

// end::is_persistence_check_duplicate_per_pk[]


=== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]

// end::is_persistence_check_for_empty_source[]


=== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]

// end::is_persistence_delete_changed[]


=== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]

// end::is_persistence_delete_missing[]


=== is_persistence_insert

// tag::is_persistence_insert[]

// end::is_persistence_insert[]


=== is_persistence_truncate

// tag::is_persistence_truncate[]

// end::is_persistence_truncate[]


=== is_persistence_update_changed

// tag::is_persistence_update_changed[]

// end::is_persistence_update_changed[]


=== is_repo_managed

// tag::is_repo_managed[]
0
// end::is_repo_managed[]


=== is_ssas

// tag::is_ssas[]
0
// end::is_ssas[]


=== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


=== MS_Description

// tag::ms_description[]

// end::ms_description[]


=== persistence_source_RepoObject_fullname

// tag::persistence_source_repoobject_fullname[]

// end::persistence_source_repoobject_fullname[]


=== persistence_source_RepoObject_fullname2

// tag::persistence_source_repoobject_fullname2[]

// end::persistence_source_repoobject_fullname2[]


=== persistence_source_RepoObject_guid

// tag::persistence_source_repoobject_guid[]

// end::persistence_source_repoobject_guid[]


=== persistence_source_RepoObject_xref

// tag::persistence_source_repoobject_xref[]

// end::persistence_source_repoobject_xref[]


=== pk_index_guid

// tag::pk_index_guid[]
2E90291C-9D61-EB11-84DC-A81E8446D5B0
// end::pk_index_guid[]


=== pk_IndexPatternColumnDatatype

// tag::pk_indexpatterncolumndatatype[]
uniqueidentifier,int
// end::pk_indexpatterncolumndatatype[]


=== pk_IndexPatternColumnName

// tag::pk_indexpatterncolumnname[]
RepoObject_guid,column_ordinal
// end::pk_indexpatterncolumnname[]


=== pk_IndexSemanticGroup

// tag::pk_indexsemanticgroup[]

// end::pk_indexsemanticgroup[]


=== ReferencedObjectList

// tag::referencedobjectlist[]

// end::referencedobjectlist[]


=== usp_persistence_RepoObject_guid

// tag::usp_persistence_repoobject_guid[]

// end::usp_persistence_repoobject_guid[]


=== UspExamples

// tag::uspexamples[]

// end::uspexamples[]


=== uspgenerator_usp_id

// tag::uspgenerator_usp_id[]

// end::uspgenerator_usp_id[]


=== UspParameters

// tag::uspparameters[]

// end::uspparameters[]

== Boolean Attributes

source: property.RepoObjectProperty WHERE property_int = 1

// tag::boolean_attributes[]


// end::boolean_attributes[]

== PlantUML diagrams

=== PlantUML Entity

// tag::puml_entity[]
[plantuml, entity-{docname}, svg, subs=macros]
....
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:reference.repoobjectsource_firstresultset.adoc[]" as reference.RepoObjectSource_FirstResultSet << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **column_ordinal** : (int)
  - created_dt : (datetime)
  is_hidden : (bit)
  source_column_name : (nvarchar(128))
  source_database_name : (nvarchar(128))
  source_schema_name : (nvarchar(128))
  source_server_name : (nvarchar(128))
  source_table_name : (nvarchar(128))
  system_type_id : (int)
  system_type_name : (nvarchar(128))
  target_column_name : (nvarchar(128))
  --
}
....

// end::puml_entity[]

=== PlantUML Entity 1 1 FK

// tag::puml_entity_1_1_fk[]
[plantuml, entity_1_1_fk-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:reference.repoobjectsource_firstresultset.adoc[]" as reference.RepoObjectSource_FirstResultSet << U >> {
**PK_RepoObjectSource_FirstResultSet**

..
RepoObject_guid; uniqueidentifier
column_ordinal; int
--
- idx_RepoObjectSource_FirstResultSet__1

..
RepoObject_guid; uniqueidentifier
}

entity "puml-link:dhw:sqldb:repo.repoobject.adoc[]" as repo.RepoObject << U >> {
**PK_RepoObject**

..
RepoObject_guid; uniqueidentifier
--
UK_RepoObject__RepoNames

..
RepoObject_schema_name; nvarchar(128)
RepoObject_name; nvarchar(128)
--
UK_RepoObject__SysNames

..
SysObject_schema_name; nvarchar(128)
SysObject_name; nvarchar(128)
--
- idx_RepoObject__1

..
pk_index_guid; uniqueidentifier
}

"repo.RepoObject::PK_RepoObject" <-- "reference.RepoObjectSource_FirstResultSet::idx_RepoObjectSource_FirstResultSet__1"

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_fk[]

=== PlantUML 1 1 ObjectRef

// tag::puml_entity_1_1_objectref[]
[plantuml, entity_1_1_objectref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_reference_firstresultset.adoc[]" as reference.RepoObjectColumn_reference_FirstResultSet << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectsource_firstresultset.adoc[]" as reference.RepoObjectSource_FirstResultSet << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **column_ordinal** : (int)
  --
}

entity "puml-link:dhw:sqldb:reference.usp_repoobjectsource_firstresultset.adoc[]" as reference.usp_RepoObjectSource_FirstResultSet << P >> {
  --
}

reference.RepoObjectSource_FirstResultSet <.. reference.RepoObjectColumn_reference_FirstResultSet
reference.RepoObjectSource_FirstResultSet <.. reference.usp_RepoObjectSource_FirstResultSet

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_objectref[]

=== PlantUML 30 0 ObjectRef

// tag::puml_entity_30_0_objectref[]
[plantuml, entity_30_0_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:reference.repoobjectsource_firstresultset.adoc[]" as reference.RepoObjectSource_FirstResultSet << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **column_ordinal** : (int)
  --
}



footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_30_0_objectref[]

=== PlantUML 0 30 ObjectRef

// tag::puml_entity_0_30_objectref[]
[plantuml, entity_0_30_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_reference_bysamepredecessors.adoc[]" as reference.RepoObjectColumn_reference_BySamePredecessors << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_reference_firstresultset.adoc[]" as reference.RepoObjectColumn_reference_FirstResultSet << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectsource_firstresultset.adoc[]" as reference.RepoObjectSource_FirstResultSet << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **column_ordinal** : (int)
  --
}

entity "puml-link:dhw:sqldb:reference.usp_repoobjectsource_firstresultset.adoc[]" as reference.usp_RepoObjectSource_FirstResultSet << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_main.adoc[]" as repo.usp_main << P >> {
  --
}

reference.RepoObjectColumn_reference_FirstResultSet <.. reference.RepoObjectColumn_reference_BySamePredecessors
reference.RepoObjectSource_FirstResultSet <.. reference.RepoObjectColumn_reference_FirstResultSet
reference.RepoObjectSource_FirstResultSet <.. reference.usp_RepoObjectSource_FirstResultSet
reference.usp_RepoObjectSource_FirstResultSet <.. repo.usp_main

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_0_30_objectref[]

=== PlantUML 1 1 ColumnRef

// tag::puml_entity_1_1_colref[]
[plantuml, entity_1_1_colref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_reference_firstresultset.adoc[]" as reference.RepoObjectColumn_reference_FirstResultSet << V >> {
  - InformationSource : (varchar(37))
  is_hidden : (bit)
  is_referenced_object : (bit)
  is_referencing_object_equal_referenced_object : (bit)
  referenced_column_name : (nvarchar(128))
  referenced_entity_name : (nvarchar(128))
  referenced_id : (int)
  referenced_minor_id : (int)
  referenced_node_id : (bigint)
  referenced_RepoObject_guid : (uniqueidentifier)
  referenced_RepoObjectColumn_guid : (uniqueidentifier)
  referenced_schema_name : (nvarchar(128))
  referenced_type : (char(2))
  referencing_column_name : (nvarchar(128))
  - referencing_entity_name : (nvarchar(128))
  referencing_id : (int)
  referencing_minor_id : (int)
  referencing_node_id : (bigint)
  - referencing_RepoObject_guid : (uniqueidentifier)
  referencing_RepoObjectColumn_guid : (uniqueidentifier)
  - referencing_schema_name : (nvarchar(128))
  referencing_type : (char(2))
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectsource_firstresultset.adoc[]" as reference.RepoObjectSource_FirstResultSet << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **column_ordinal** : (int)
  - created_dt : (datetime)
  is_hidden : (bit)
  source_column_name : (nvarchar(128))
  source_database_name : (nvarchar(128))
  source_schema_name : (nvarchar(128))
  source_server_name : (nvarchar(128))
  source_table_name : (nvarchar(128))
  system_type_id : (int)
  system_type_name : (nvarchar(128))
  target_column_name : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:reference.usp_repoobjectsource_firstresultset.adoc[]" as reference.usp_RepoObjectSource_FirstResultSet << P >> {
  --
}

reference.RepoObjectSource_FirstResultSet <.. reference.RepoObjectColumn_reference_FirstResultSet
reference.RepoObjectSource_FirstResultSet <.. reference.usp_RepoObjectSource_FirstResultSet
"reference.RepoObjectSource_FirstResultSet::is_hidden" <-- "reference.RepoObjectColumn_reference_FirstResultSet::is_hidden"
"reference.RepoObjectSource_FirstResultSet::RepoObject_guid" <-- "reference.RepoObjectColumn_reference_FirstResultSet::referencing_RepoObject_guid"
"reference.RepoObjectSource_FirstResultSet::source_column_name" <-- "reference.RepoObjectColumn_reference_FirstResultSet::referenced_column_name"
"reference.RepoObjectSource_FirstResultSet::source_schema_name" <-- "reference.RepoObjectColumn_reference_FirstResultSet::referenced_schema_name"
"reference.RepoObjectSource_FirstResultSet::source_table_name" <-- "reference.RepoObjectColumn_reference_FirstResultSet::referenced_entity_name"
"reference.RepoObjectSource_FirstResultSet::target_column_name" <-- "reference.RepoObjectColumn_reference_FirstResultSet::referencing_column_name"

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_colref[]


== sql_modules_definition

// tag::sql_modules_definition[]
[%collapsible]
=======
[source,sql,numbered,indent=0]
----

----
=======
// end::sql_modules_definition[]


