// tag::HeaderFullDisplayName[]
= repo.RepoObject_persistence - U
// end::HeaderFullDisplayName[]

== existing_properties

// tag::existing_properties[]

:ExistsProperty--antorareferencinglist:
:ExistsProperty--is_repo_managed:
:ExistsProperty--is_ssas:
:ExistsProperty--pk_index_guid:
:ExistsProperty--pk_indexpatterncolumndatatype:
:ExistsProperty--pk_indexpatterncolumnname:
:ExistsProperty--FK:
:ExistsProperty--AntoraIndexList:
:ExistsProperty--Columns:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
4690291C-9D61-EB11-84DC-A81E8446D5B0
// end::RepoObject_guid[]

== RepoObject_FullDisplayName2

// tag::RepoObject_FullDisplayName2[]
repo.RepoObject_persistence
// end::RepoObject_FullDisplayName2[]

== SysObject_type

// tag::SysObject_type[]
U 
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
user table
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
157295670
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2022-09-05 18:17:58
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]
[discrete]
== _


[#column-targetunderlinerepoobjectunderlineguid]
=== target_RepoObject_guid

[cols="d,8a,m,m,m"]
|===
|1
|*target_RepoObject_guid*
|uniqueidentifier
|NOT NULL
|
|===

.Referencing Columns
--
* xref:reference.repoobject_reference_persistence.adoc#column-referencingunderlinerepoobjectunderlineguid[+reference.RepoObject_reference_persistence.referencing_RepoObject_guid+]
* xref:reference.repoobjectcolumn_reference_persistence.adoc#column-referencingunderlinerepoobjectunderlineguid[+reference.RepoObjectColumn_reference_Persistence.referencing_RepoObject_guid+]
* xref:repo.repoobject_persistence_column.adoc#column-targetunderlinerepoobjectunderlineguid[+repo.RepoObject_persistence_column.target_RepoObject_guid+]
* xref:repo.repoobject_persistence_forupdate.adoc#column-targetunderlinerepoobjectunderlineguid[+repo.RepoObject_persistence_ForUpdate.target_RepoObject_guid+]
* xref:repo.repoobject_persistence_nocomparebutupdate.adoc#column-targetunderlinerepoobjectunderlineguid[+repo.RepoObject_persistence_NoCompareButUpdate.target_RepoObject_guid+]
* xref:repo.repoobject_persistence_nocomparenoupdate.adoc#column-targetunderlinerepoobjectunderlineguid[+repo.RepoObject_persistence_NoCompareNoUpdate.target_RepoObject_guid+]
* xref:repo.repoobject_persistence_noinsert.adoc#column-targetunderlinerepoobjectunderlineguid[+repo.RepoObject_persistence_NoInsert.target_RepoObject_guid+]
* xref:repo.repoobject_persistence_objectnames.adoc#column-targetunderlinerepoobjectunderlineguid[+repo.RepoObject_persistence_ObjectNames.target_RepoObject_guid+]
* xref:repo.repoobject_persistence_source_ignore.adoc#column-targetunderlinerepoobjectunderlineguid[+repo.RepoObject_persistence_source_Ignore.target_RepoObject_guid+]
* xref:repo.repoobject_persistence_target_ignore.adoc#column-targetunderlinerepoobjectunderlineguid[+repo.RepoObject_persistence_target_Ignore.target_RepoObject_guid+]
* xref:repo.repoobjectcolumn_histvalidcolums_setpoint.adoc#column-repoobjectunderlineguid[+repo.RepoObjectColumn_HistValidColums_setpoint.RepoObject_guid+]
* xref:uspgenerator.generatorusp_check_persistence.adoc#column-targetunderlinerepoobjectunderlineguid[+uspgenerator.GeneratorUsp_check_persistence.target_RepoObject_guid+]
--


[#column-columnlistignore]
=== ColumnListIgnore

[cols="d,8a,m,m,m"]
|===
|
|ColumnListIgnore
|nvarchar(4000)
|NULL
|
|===

.Referencing Columns
--
* xref:repo.repoobject_persistence_forupdate.adoc#column-columnlistignore[+repo.RepoObject_persistence_ForUpdate.ColumnListIgnore+]
* xref:repo.repoobject_persistence_source_ignore.adoc#column-columnlistignore[+repo.RepoObject_persistence_source_Ignore.ColumnListIgnore+]
* xref:repo.repoobject_persistence_target_ignore.adoc#column-columnlistignore[+repo.RepoObject_persistence_target_Ignore.ColumnListIgnore+]
* xref:uspgenerator.generatorusp_check_persistence.adoc#column-columnlistignore[+uspgenerator.GeneratorUsp_check_persistence.ColumnListIgnore+]
--


[#column-columnlistnocomparebutupdate]
=== ColumnListNoCompareButUpdate

[cols="d,8a,m,m,m"]
|===
|
|ColumnListNoCompareButUpdate
|nvarchar(4000)
|NULL
|
|===

.Referencing Columns
--
* xref:repo.repoobject_persistence_forupdate.adoc#column-columnlistnocomparebutupdate[+repo.RepoObject_persistence_ForUpdate.ColumnListNoCompareButUpdate+]
* xref:repo.repoobject_persistence_nocomparebutupdate.adoc#column-columnlistnocomparebutupdate[+repo.RepoObject_persistence_NoCompareButUpdate.ColumnListNoCompareButUpdate+]
* xref:uspgenerator.generatorusp_check_persistence.adoc#column-columnlistnocomparebutupdate[+uspgenerator.GeneratorUsp_check_persistence.ColumnListNoCompareButUpdate+]
--


[#column-columnlistnocomparenoupdate]
=== ColumnListNoCompareNoUpdate

[cols="d,8a,m,m,m"]
|===
|
|ColumnListNoCompareNoUpdate
|nvarchar(4000)
|NULL
|
|===

.Referencing Columns
--
* xref:repo.repoobject_persistence_forupdate.adoc#column-columnlistnocomparenoupdate[+repo.RepoObject_persistence_ForUpdate.ColumnListNoCompareNoUpdate+]
* xref:repo.repoobject_persistence_nocomparenoupdate.adoc#column-columnlistnocomparenoupdate[+repo.RepoObject_persistence_NoCompareNoUpdate.ColumnListNoCompareNoUpdate+]
* xref:uspgenerator.generatorusp_check_persistence.adoc#column-columnlistnocomparenoupdate[+uspgenerator.GeneratorUsp_check_persistence.ColumnListNoCompareNoUpdate+]
--


[#column-columnlistnoinsert]
=== ColumnListNoInsert

[cols="d,8a,m,m,m"]
|===
|
|ColumnListNoInsert
|nvarchar(4000)
|NULL
|
|===

.Referencing Columns
--
* xref:repo.repoobject_persistence_forupdate.adoc#column-columnlistnoinsert[+repo.RepoObject_persistence_ForUpdate.ColumnListNoInsert+]
* xref:repo.repoobject_persistence_noinsert.adoc#column-columnlistnoinsert[+repo.RepoObject_persistence_NoInsert.ColumnListNoInsert+]
--


[#column-executionlogidunderlineaction]
=== ExecutionLogId_action

[cols="d,8a,m,m,m"]
|===
|
|ExecutionLogId_action
|char(1)
|NULL
|
|===

.Referencing Columns
--
* xref:repo.repoobject_gross.adoc#column-executionlogidunderlineaction[+repo.RepoObject_gross.ExecutionLogId_action+]
* xref:repo.repoobject_gross_persistence.adoc#column-executionlogidunderlineaction[+repo.RepoObject_gross_persistence.ExecutionLogId_action+]
--


[#column-finalunderlinetargetunderlinerepoobjectunderlinename]
=== final_target_RepoObject_name

[cols="d,8a,m,m,m"]
|===
|
|final_target_RepoObject_name
|nvarchar(128)
|NULL
|
|===


[#column-hasunderlinehistory]
=== has_history

[cols="d,8a,m,m,m"]
|===
|
|has_history

.Default: DF__RepoObjec__has_h__29AC2CE0
[source,sql]
----
((0))
----


|bit
|NOT NULL
|
|===

.Referencing Columns
--
* xref:repo.repoobject_gross.adoc#column-hasunderlinehistory[+repo.RepoObject_gross.has_history+]
* xref:repo.repoobject_gross_persistence.adoc#column-hasunderlinehistory[+repo.RepoObject_gross_persistence.has_history+]
* xref:repo.repoobject_persistence.adoc#column-temporalunderlinetype[+repo.RepoObject_persistence.temporal_type+]
* xref:repo.repoobject_persistence_column.adoc#column-hasunderlinehistory[+repo.RepoObject_persistence_column.has_history+]
* xref:repo.repoobject_persistence_forupdate.adoc#column-hasunderlinehistory[+repo.RepoObject_persistence_ForUpdate.has_history+]
* xref:repo.repoobject_persistence_objectnames.adoc#column-hasunderlinehistory[+repo.RepoObject_persistence_ObjectNames.has_history+]
* xref:uspgenerator.generatorusp_check_persistence.adoc#column-hasunderlinehistory[+uspgenerator.GeneratorUsp_check_persistence.has_history+]
--


[#column-hasunderlinehistoryunderlinecolumns]
=== has_history_columns

[cols="d,8a,m,m,m"]
|===
|
|has_history_columns

.Default: DF__RepoObjec__has_h__2AA05119
[source,sql]
----
((0))
----


|bit
|NOT NULL
|
|===

.Referencing Columns
--
* xref:repo.repoobject_gross.adoc#column-hasunderlinehistoryunderlinecolumns[+repo.RepoObject_gross.has_history_columns+]
* xref:repo.repoobject_gross_persistence.adoc#column-hasunderlinehistoryunderlinecolumns[+repo.RepoObject_gross_persistence.has_history_columns+]
* xref:repo.repoobject_persistence_column.adoc#column-hasunderlinehistoryunderlinecolumns[+repo.RepoObject_persistence_column.has_history_columns+]
* xref:repo.repoobject_persistence_forupdate.adoc#column-hasunderlinehistoryunderlinecolumns[+repo.RepoObject_persistence_ForUpdate.has_history_columns+]
* xref:repo.repoobject_persistence_objectnames.adoc#column-hasunderlinehistoryunderlinecolumns[+repo.RepoObject_persistence_ObjectNames.has_history_columns+]
* xref:uspgenerator.generatorusp_check_persistence.adoc#column-hasunderlinehistoryunderlinecolumns[+uspgenerator.GeneratorUsp_check_persistence.has_history_columns+]
--


[#column-historyunderlineschemaunderlinename]
=== history_schema_name

[cols="d,8a,m,m,m"]
|===
|
|history_schema_name
|nvarchar(128)
|NULL
|
|===

.Referencing Columns
--
* xref:repo.repoobject_gross.adoc#column-historyunderlineschemaunderlinename[+repo.RepoObject_gross.history_schema_name+]
* xref:repo.repoobject_gross_persistence.adoc#column-historyunderlineschemaunderlinename[+repo.RepoObject_gross_persistence.history_schema_name+]
* xref:repo.repoobject_persistence_column.adoc#column-historyunderlineschemaunderlinename[+repo.RepoObject_persistence_column.history_schema_name+]
* xref:repo.repoobject_persistence_forupdate.adoc#column-historyunderlineschemaunderlinename[+repo.RepoObject_persistence_ForUpdate.history_schema_name+]
* xref:repo.repoobject_persistence_objectnames.adoc#column-historyunderlineschemaunderlinename[+repo.RepoObject_persistence_ObjectNames.history_schema_name+]
* xref:uspgenerator.generatorusp_check_persistence.adoc#column-historyunderlineschemaunderlinename[+uspgenerator.GeneratorUsp_check_persistence.history_schema_name+]
--


[#column-historyunderlinetableunderlinename]
=== history_table_name

[cols="d,8a,m,m,m"]
|===
|
|history_table_name
|nvarchar(128)
|NULL
|
|===

.Referencing Columns
--
* xref:repo.repoobject_gross.adoc#column-historyunderlinetableunderlinename[+repo.RepoObject_gross.history_table_name+]
* xref:repo.repoobject_gross_persistence.adoc#column-historyunderlinetableunderlinename[+repo.RepoObject_gross_persistence.history_table_name+]
* xref:repo.repoobject_persistence_column.adoc#column-historyunderlinetableunderlinename[+repo.RepoObject_persistence_column.history_table_name+]
* xref:repo.repoobject_persistence_forupdate.adoc#column-historyunderlinetableunderlinename[+repo.RepoObject_persistence_ForUpdate.history_table_name+]
* xref:repo.repoobject_persistence_objectnames.adoc#column-historyunderlinetableunderlinename[+repo.RepoObject_persistence_ObjectNames.history_table_name+]
* xref:uspgenerator.generatorusp_check_persistence.adoc#column-historyunderlinetableunderlinename[+uspgenerator.GeneratorUsp_check_persistence.history_table_name+]
--


[#column-isunderlinepersistenceunderlinecheckunderlineduplicateunderlineperunderlinepk]
=== is_persistence_check_duplicate_per_pk

[cols="d,8a,m,m,m"]
|===
|
|is_persistence_check_duplicate_per_pk

.Default: DF_RepoObject_persistence_is_persistence_check_for_empty_source1
[source,sql]
----
((0))
----


|bit
|NOT NULL
|
|===

.Referencing Columns
--
* xref:repo.repoobject_gross.adoc#column-isunderlinepersistenceunderlinecheckunderlineduplicateunderlineperunderlinepk[+repo.RepoObject_gross.is_persistence_check_duplicate_per_pk+]
* xref:repo.repoobject_gross_persistence.adoc#column-isunderlinepersistenceunderlinecheckunderlineduplicateunderlineperunderlinepk[+repo.RepoObject_gross_persistence.is_persistence_check_duplicate_per_pk+]
* xref:repo.repoobject_persistence_forupdate.adoc#column-isunderlinepersistenceunderlinecheckunderlineduplicateunderlineperunderlinepk[+repo.RepoObject_persistence_ForUpdate.is_persistence_check_duplicate_per_pk+]
* xref:uspgenerator.generatorusp_check_persistence.adoc#column-isunderlinepersistenceunderlinecheckunderlineduplicateunderlineperunderlinepk[+uspgenerator.GeneratorUsp_check_persistence.is_persistence_check_duplicate_per_pk+]
--


[#column-isunderlinepersistenceunderlinecheckunderlineforunderlineemptyunderlinesource]
=== is_persistence_check_for_empty_source

[cols="d,8a,m,m,m"]
|===
|
|is_persistence_check_for_empty_source

.Default: DF__RepoObjec__is_hi__2B947552
[source,sql]
----
((0))
----


|bit
|NOT NULL
|
|===

.Referencing Columns
--
* xref:repo.repoobject_gross.adoc#column-isunderlinepersistenceunderlinecheckunderlineforunderlineemptyunderlinesource[+repo.RepoObject_gross.is_persistence_check_for_empty_source+]
* xref:repo.repoobject_gross_persistence.adoc#column-isunderlinepersistenceunderlinecheckunderlineforunderlineemptyunderlinesource[+repo.RepoObject_gross_persistence.is_persistence_check_for_empty_source+]
* xref:repo.repoobject_persistence_column.adoc#column-isunderlinepersistenceunderlinecheckunderlineforunderlineemptyunderlinesource[+repo.RepoObject_persistence_column.is_persistence_check_for_empty_source+]
* xref:repo.repoobject_persistence_forupdate.adoc#column-isunderlinepersistenceunderlinecheckunderlineforunderlineemptyunderlinesource[+repo.RepoObject_persistence_ForUpdate.is_persistence_check_for_empty_source+]
* xref:repo.repoobject_persistence_objectnames.adoc#column-isunderlinepersistenceunderlinecheckunderlineforunderlineemptyunderlinesource[+repo.RepoObject_persistence_ObjectNames.is_persistence_check_for_empty_source+]
* xref:uspgenerator.generatorusp_check_persistence.adoc#column-isunderlinepersistenceunderlinecheckunderlineforunderlineemptyunderlinesource[+uspgenerator.GeneratorUsp_check_persistence.is_persistence_check_for_empty_source+]
--


[#column-isunderlinepersistenceunderlinedeleteunderlinechanged]
=== is_persistence_delete_changed

[cols="d,8a,m,m,m"]
|===
|
|is_persistence_delete_changed

.Default: DF__RepoObjec__is_pe__2C88998B
[source,sql]
----
((0))
----


|bit
|NOT NULL
|
|===

.Referencing Columns
--
* xref:repo.repoobject_gross.adoc#column-isunderlinepersistenceunderlinedeleteunderlinechanged[+repo.RepoObject_gross.is_persistence_delete_changed+]
* xref:repo.repoobject_gross_persistence.adoc#column-isunderlinepersistenceunderlinedeleteunderlinechanged[+repo.RepoObject_gross_persistence.is_persistence_delete_changed+]
* xref:repo.repoobject_persistence_column.adoc#column-isunderlinepersistenceunderlinedeleteunderlinechanged[+repo.RepoObject_persistence_column.is_persistence_delete_changed+]
* xref:repo.repoobject_persistence_forupdate.adoc#column-isunderlinepersistenceunderlinedeleteunderlinechanged[+repo.RepoObject_persistence_ForUpdate.is_persistence_delete_changed+]
* xref:repo.repoobject_persistence_objectnames.adoc#column-isunderlinepersistenceunderlinedeleteunderlinechanged[+repo.RepoObject_persistence_ObjectNames.is_persistence_delete_changed+]
* xref:uspgenerator.generatorusp_check_persistence.adoc#column-isunderlinepersistenceunderlinedeleteunderlinechanged[+uspgenerator.GeneratorUsp_check_persistence.is_persistence_delete_changed+]
--


[#column-isunderlinepersistenceunderlinedeleteunderlinemissing]
=== is_persistence_delete_missing

[cols="d,8a,m,m,m"]
|===
|
|is_persistence_delete_missing

.Default: DF__RepoObjec__is_pe__2D7CBDC4
[source,sql]
----
((0))
----


|bit
|NOT NULL
|
|===

.Referencing Columns
--
* xref:repo.repoobject_gross.adoc#column-isunderlinepersistenceunderlinedeleteunderlinemissing[+repo.RepoObject_gross.is_persistence_delete_missing+]
* xref:repo.repoobject_gross_persistence.adoc#column-isunderlinepersistenceunderlinedeleteunderlinemissing[+repo.RepoObject_gross_persistence.is_persistence_delete_missing+]
* xref:repo.repoobject_persistence_column.adoc#column-isunderlinepersistenceunderlinedeleteunderlinemissing[+repo.RepoObject_persistence_column.is_persistence_delete_missing+]
* xref:repo.repoobject_persistence_forupdate.adoc#column-isunderlinepersistenceunderlinedeleteunderlinemissing[+repo.RepoObject_persistence_ForUpdate.is_persistence_delete_missing+]
* xref:repo.repoobject_persistence_objectnames.adoc#column-isunderlinepersistenceunderlinedeleteunderlinemissing[+repo.RepoObject_persistence_ObjectNames.is_persistence_delete_missing+]
* xref:uspgenerator.generatorusp_check_persistence.adoc#column-isunderlinepersistenceunderlinedeleteunderlinemissing[+uspgenerator.GeneratorUsp_check_persistence.is_persistence_delete_missing+]
--


[#column-isunderlinepersistenceunderlineinsert]
=== is_persistence_insert

[cols="d,8a,m,m,m"]
|===
|
|is_persistence_insert

.Default: DF__RepoObjec__is_pe__2E70E1FD
[source,sql]
----
((1))
----


|bit
|NOT NULL
|
|===

.Referencing Columns
--
* xref:repo.repoobject_gross.adoc#column-isunderlinepersistenceunderlineinsert[+repo.RepoObject_gross.is_persistence_insert+]
* xref:repo.repoobject_gross_persistence.adoc#column-isunderlinepersistenceunderlineinsert[+repo.RepoObject_gross_persistence.is_persistence_insert+]
* xref:repo.repoobject_persistence_column.adoc#column-isunderlinepersistenceunderlineinsert[+repo.RepoObject_persistence_column.is_persistence_insert+]
* xref:repo.repoobject_persistence_forupdate.adoc#column-isunderlinepersistenceunderlineinsert[+repo.RepoObject_persistence_ForUpdate.is_persistence_insert+]
* xref:repo.repoobject_persistence_objectnames.adoc#column-isunderlinepersistenceunderlineinsert[+repo.RepoObject_persistence_ObjectNames.is_persistence_insert+]
* xref:uspgenerator.generatorusp_check_persistence.adoc#column-isunderlinepersistenceunderlineinsert[+uspgenerator.GeneratorUsp_check_persistence.is_persistence_insert+]
--


[#column-isunderlinepersistenceunderlinepersistunderlinesource]
=== is_persistence_persist_source

[cols="d,8a,m,m,m"]
|===
|
|is_persistence_persist_source

.Default: DF_RepoObject_persistence_is_persistence_merge_update_changed1
[source,sql]
----
((0))
----


|bit
|NOT NULL
|
|===

.Referencing Columns
--
* xref:repo.repoobject_gross.adoc#column-isunderlinepersistenceunderlinepersistunderlinesource[+repo.RepoObject_gross.is_persistence_persist_source+]
* xref:repo.repoobject_gross_persistence.adoc#column-isunderlinepersistenceunderlinepersistunderlinesource[+repo.RepoObject_gross_persistence.is_persistence_persist_source+]
* xref:repo.repoobject_persistence_forupdate.adoc#column-isunderlinepersistenceunderlinepersistunderlinesource[+repo.RepoObject_persistence_ForUpdate.is_persistence_persist_source+]
* xref:uspgenerator.generatorusp_check_persistence.adoc#column-isunderlinepersistenceunderlinepersistunderlinesource[+uspgenerator.GeneratorUsp_check_persistence.is_persistence_persist_source+]
--


[#column-isunderlinepersistenceunderlinetruncate]
=== is_persistence_truncate

[cols="d,8a,m,m,m"]
|===
|
|is_persistence_truncate

.Default: DF__RepoObjec__is_pe__2F650636
[source,sql]
----
((1))
----


|bit
|NOT NULL
|
|===

.Referencing Columns
--
* xref:repo.repoobject_gross.adoc#column-isunderlinepersistenceunderlinetruncate[+repo.RepoObject_gross.is_persistence_truncate+]
* xref:repo.repoobject_gross_persistence.adoc#column-isunderlinepersistenceunderlinetruncate[+repo.RepoObject_gross_persistence.is_persistence_truncate+]
* xref:repo.repoobject_persistence_column.adoc#column-isunderlinepersistenceunderlinetruncate[+repo.RepoObject_persistence_column.is_persistence_truncate+]
* xref:repo.repoobject_persistence_forupdate.adoc#column-isunderlinepersistenceunderlinetruncate[+repo.RepoObject_persistence_ForUpdate.is_persistence_truncate+]
* xref:repo.repoobject_persistence_objectnames.adoc#column-isunderlinepersistenceunderlinetruncate[+repo.RepoObject_persistence_ObjectNames.is_persistence_truncate+]
* xref:uspgenerator.generatorusp_check_persistence.adoc#column-isunderlinepersistenceunderlinetruncate[+uspgenerator.GeneratorUsp_check_persistence.is_persistence_truncate+]
--


[#column-isunderlinepersistenceunderlineupdateunderlinechanged]
=== is_persistence_update_changed

[cols="d,8a,m,m,m"]
|===
|
|is_persistence_update_changed

.Default: DF__RepoObjec__is_pe__30592A6F
[source,sql]
----
((0))
----


|bit
|NOT NULL
|
|===

.Referencing Columns
--
* xref:repo.repoobject_gross.adoc#column-isunderlinepersistenceunderlineupdateunderlinechanged[+repo.RepoObject_gross.is_persistence_update_changed+]
* xref:repo.repoobject_gross_persistence.adoc#column-isunderlinepersistenceunderlineupdateunderlinechanged[+repo.RepoObject_gross_persistence.is_persistence_update_changed+]
* xref:repo.repoobject_persistence_column.adoc#column-isunderlinepersistenceunderlineupdateunderlinechanged[+repo.RepoObject_persistence_column.is_persistence_update_changed+]
* xref:repo.repoobject_persistence_forupdate.adoc#column-isunderlinepersistenceunderlineupdateunderlinechanged[+repo.RepoObject_persistence_ForUpdate.is_persistence_update_changed+]
* xref:repo.repoobject_persistence_objectnames.adoc#column-isunderlinepersistenceunderlineupdateunderlinechanged[+repo.RepoObject_persistence_ObjectNames.is_persistence_update_changed+]
* xref:uspgenerator.generatorusp_check_persistence.adoc#column-isunderlinepersistenceunderlineupdateunderlinechanged[+uspgenerator.GeneratorUsp_check_persistence.is_persistence_update_changed+]
--


[#column-postscript]
=== postscript

[cols="d,8a,m,m,m"]
|===
|
|postscript
|nvarchar(max)
|NULL
|
|===

.Referencing Columns
--
* xref:repo.repoobject_gross.adoc#column-postscript[+repo.RepoObject_gross.postscript+]
* xref:repo.repoobject_gross_persistence.adoc#column-postscript[+repo.RepoObject_gross_persistence.postscript+]
* xref:repo.repoobject_persistence_forupdate.adoc#column-postscript[+repo.RepoObject_persistence_ForUpdate.postscript+]
* xref:uspgenerator.generatorusp_check_persistence.adoc#column-postscript[+uspgenerator.GeneratorUsp_check_persistence.postscript+]
--


[#column-prescript]
=== prescript

[cols="d,8a,m,m,m"]
|===
|
|prescript
|nvarchar(max)
|NULL
|
|===

.Referencing Columns
--
* xref:repo.repoobject_gross.adoc#column-prescript[+repo.RepoObject_gross.prescript+]
* xref:repo.repoobject_gross_persistence.adoc#column-prescript[+repo.RepoObject_gross_persistence.prescript+]
* xref:repo.repoobject_persistence_forupdate.adoc#column-prescript[+repo.RepoObject_persistence_ForUpdate.prescript+]
* xref:uspgenerator.generatorusp_check_persistence.adoc#column-prescript[+uspgenerator.GeneratorUsp_check_persistence.prescript+]
--


[#column-sourceunderlinerepoobjectunderlineguid]
=== source_RepoObject_guid

[cols="d,8a,m,m,m"]
|===
|
|source_RepoObject_guid
|uniqueidentifier
|NULL
|
|===

.Referencing Columns
--
* xref:reference.repoobject_reference_persistence.adoc#column-referencedunderlinerepoobjectunderlineguid[+reference.RepoObject_reference_persistence.referenced_RepoObject_guid+]
* xref:reference.repoobject_reference_t_bidirectional.adoc#column-referencingunderlinesourceunderlinerepoobjectunderlineguid[+reference.RepoObject_reference_T_bidirectional.referencing_source_RepoObject_guid+]
* xref:reference.repoobject_reference_t_bidirectional.adoc#column-referencedunderlinesourceunderlinerepoobjectunderlineguid[+reference.RepoObject_reference_T_bidirectional.referenced_source_RepoObject_guid+]
* xref:reference.repoobjectcolumn_reference_persistence.adoc#column-referencedunderlinerepoobjectunderlineguid[+reference.RepoObjectColumn_reference_Persistence.referenced_RepoObject_guid+]
* xref:repo.repoobject_gross.adoc#column-persistenceunderlinesourceunderlinerepoobjectunderlineguid[+repo.RepoObject_gross.persistence_source_RepoObject_guid+]
* xref:repo.repoobject_gross_persistence.adoc#column-persistenceunderlinesourceunderlinerepoobjectunderlineguid[+repo.RepoObject_gross_persistence.persistence_source_RepoObject_guid+]
* xref:repo.repoobject_persistence_column.adoc#column-sourceunderlinerepoobjectunderlineguid[+repo.RepoObject_persistence_column.source_RepoObject_guid+]
* xref:repo.repoobject_persistence_forupdate.adoc#column-sourceunderlinerepoobjectunderlineguid[+repo.RepoObject_persistence_ForUpdate.source_RepoObject_guid+]
* xref:repo.repoobject_persistence_nocomparebutupdate.adoc#column-sourceunderlinerepoobjectunderlineguid[+repo.RepoObject_persistence_NoCompareButUpdate.source_RepoObject_guid+]
* xref:repo.repoobject_persistence_nocomparenoupdate.adoc#column-sourceunderlinerepoobjectunderlineguid[+repo.RepoObject_persistence_NoCompareNoUpdate.source_RepoObject_guid+]
* xref:repo.repoobject_persistence_noinsert.adoc#column-sourceunderlinerepoobjectunderlineguid[+repo.RepoObject_persistence_NoInsert.source_RepoObject_guid+]
* xref:repo.repoobject_persistence_objectnames.adoc#column-sourceunderlinerepoobjectunderlineguid[+repo.RepoObject_persistence_ObjectNames.source_RepoObject_guid+]
* xref:repo.repoobject_persistence_source_ignore.adoc#column-sourceunderlinerepoobjectunderlineguid[+repo.RepoObject_persistence_source_Ignore.source_RepoObject_guid+]
* xref:repo.repoobject_persistence_target_ignore.adoc#column-sourceunderlinerepoobjectunderlineguid[+repo.RepoObject_persistence_target_Ignore.source_RepoObject_guid+]
* xref:repo.repoobjectcolumn_gross.adoc#column-persistenceunderlinesourceunderlinerepoobjectunderlineguid[+repo.RepoObjectColumn_gross.persistence_source_RepoObject_guid+]
* xref:uspgenerator.generatorusp_check_persistence.adoc#column-sourceunderlinerepoobjectunderlineguid[+uspgenerator.GeneratorUsp_check_persistence.source_RepoObject_guid+]
--


[#column-sourceunderlinerepoobjectunderlinename]
=== source_RepoObject_name

[cols="d,8a,m,m,m"]
|===
|
|source_RepoObject_name
|nvarchar(128)
|NULL
|
|===

.Referencing Columns
--
* xref:repo.repoobject_persistence_forupdate.adoc#column-sourceunderlinerepoobjectunderlinename[+repo.RepoObject_persistence_ForUpdate.source_RepoObject_name+]
* xref:repo.repoobject_persistence_nocomparebutupdate.adoc#column-sourceunderlinerepoobjectunderlinename[+repo.RepoObject_persistence_NoCompareButUpdate.source_RepoObject_name+]
* xref:repo.repoobject_persistence_nocomparenoupdate.adoc#column-sourceunderlinerepoobjectunderlinename[+repo.RepoObject_persistence_NoCompareNoUpdate.source_RepoObject_name+]
* xref:repo.repoobject_persistence_noinsert.adoc#column-sourceunderlinerepoobjectunderlinename[+repo.RepoObject_persistence_NoInsert.source_RepoObject_name+]
* xref:repo.repoobject_persistence_source_ignore.adoc#column-sourceunderlinerepoobjectunderlinename[+repo.RepoObject_persistence_source_Ignore.source_RepoObject_name+]
* xref:repo.repoobject_persistence_target_ignore.adoc#column-sourceunderlinerepoobjectunderlinename[+repo.RepoObject_persistence_target_Ignore.source_RepoObject_name+]
* xref:uspgenerator.generatorusp_check_persistence.adoc#column-sourceunderlinerepoobjectunderlinename[+uspgenerator.GeneratorUsp_check_persistence.source_RepoObject_name+]
--


[#column-isunderlinepersistence]
=== is_persistence

[cols="d,8a,m,m,m"]
|===
|
|is_persistence

.Definition
[source,sql]
----
(CONVERT([bit],(1),(0)))
----


|bit
|NULL
|
|===

.Referencing Columns
--
* xref:reference.repoobject_reference_t_bidirectional.adoc#column-referencedunderlineisunderlinepersistence[+reference.RepoObject_reference_T_bidirectional.referenced_is_persistence+]
* xref:reference.repoobject_reference_t_bidirectional.adoc#column-referencingunderlineisunderlinepersistence[+reference.RepoObject_reference_T_bidirectional.referencing_is_persistence+]
* xref:repo.repoobject_gross.adoc#column-isunderlinepersistence[+repo.RepoObject_gross.is_persistence+]
* xref:repo.repoobject_gross_persistence.adoc#column-isunderlinepersistence[+repo.RepoObject_gross_persistence.is_persistence+]
* xref:repo.repoobject_persistence_column.adoc#column-isunderlinepersistence[+repo.RepoObject_persistence_column.is_persistence+]
* xref:repo.repoobject_persistence_objectnames.adoc#column-isunderlinepersistence[+repo.RepoObject_persistence_ObjectNames.is_persistence+]
* xref:uspgenerator.generatorusp_check_persistence.adoc#column-isunderlinepersistence[+uspgenerator.GeneratorUsp_check_persistence.is_persistence+]
--


[#column-temporalunderlinetype]
=== temporal_type

[cols="d,8a,m,m,m"]
|===
|
|temporal_type

.Definition
[source,sql]
----
(CONVERT([tinyint],case [has_history] when (1) then (2) else (0) end,(0)))
----


|tinyint
|NULL
|
|===

.Description
--
(CONVERT([tinyint],case [has_history] when (1) then (2) else (0) end))
--
{empty} +

.Referenced Columns
--
* xref:repo.repoobject_persistence.adoc#column-hasunderlinehistory[+repo.RepoObject_persistence.has_history+]
--

.Referencing Columns
--
* xref:repo.repoobject_gross.adoc#column-temporalunderlinetype[+repo.RepoObject_gross.temporal_type+]
* xref:repo.repoobject_gross_persistence.adoc#column-temporalunderlinetype[+repo.RepoObject_gross_persistence.temporal_type+]
* xref:uspgenerator.generatorusp_check_persistence.adoc#column-temporalunderlinetype[+uspgenerator.GeneratorUsp_check_persistence.temporal_type+]
--


// end::AntoraColumnDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]
|1
|*<<column-targetunderlinerepoobjectunderlineguid>>*
|uniqueidentifier
|NOT NULL
|

























// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]

|
|<<column-columnlistignore>>
|nvarchar(4000)
|NULL
|

|
|<<column-columnlistnocomparebutupdate>>
|nvarchar(4000)
|NULL
|

|
|<<column-columnlistnocomparenoupdate>>
|nvarchar(4000)
|NULL
|

|
|<<column-columnlistnoinsert>>
|nvarchar(4000)
|NULL
|

|
|<<column-executionlogidunderlineaction>>
|char(1)
|NULL
|

|
|<<column-finalunderlinetargetunderlinerepoobjectunderlinename>>
|nvarchar(128)
|NULL
|

|
|<<column-hasunderlinehistory>>

.Default: DF__RepoObjec__has_h__29AC2CE0
[source,sql]
----
((0))
----


|bit
|NOT NULL
|

|
|<<column-hasunderlinehistoryunderlinecolumns>>

.Default: DF__RepoObjec__has_h__2AA05119
[source,sql]
----
((0))
----


|bit
|NOT NULL
|

|
|<<column-historyunderlineschemaunderlinename>>
|nvarchar(128)
|NULL
|

|
|<<column-historyunderlinetableunderlinename>>
|nvarchar(128)
|NULL
|

|
|<<column-isunderlinepersistenceunderlinecheckunderlineduplicateunderlineperunderlinepk>>

.Default: DF_RepoObject_persistence_is_persistence_check_for_empty_source1
[source,sql]
----
((0))
----


|bit
|NOT NULL
|

|
|<<column-isunderlinepersistenceunderlinecheckunderlineforunderlineemptyunderlinesource>>

.Default: DF__RepoObjec__is_hi__2B947552
[source,sql]
----
((0))
----


|bit
|NOT NULL
|

|
|<<column-isunderlinepersistenceunderlinedeleteunderlinechanged>>

.Default: DF__RepoObjec__is_pe__2C88998B
[source,sql]
----
((0))
----


|bit
|NOT NULL
|

|
|<<column-isunderlinepersistenceunderlinedeleteunderlinemissing>>

.Default: DF__RepoObjec__is_pe__2D7CBDC4
[source,sql]
----
((0))
----


|bit
|NOT NULL
|

|
|<<column-isunderlinepersistenceunderlineinsert>>

.Default: DF__RepoObjec__is_pe__2E70E1FD
[source,sql]
----
((1))
----


|bit
|NOT NULL
|

|
|<<column-isunderlinepersistenceunderlinepersistunderlinesource>>

.Default: DF_RepoObject_persistence_is_persistence_merge_update_changed1
[source,sql]
----
((0))
----


|bit
|NOT NULL
|

|
|<<column-isunderlinepersistenceunderlinetruncate>>

.Default: DF__RepoObjec__is_pe__2F650636
[source,sql]
----
((1))
----


|bit
|NOT NULL
|

|
|<<column-isunderlinepersistenceunderlineupdateunderlinechanged>>

.Default: DF__RepoObjec__is_pe__30592A6F
[source,sql]
----
((0))
----


|bit
|NOT NULL
|

|
|<<column-postscript>>
|nvarchar(max)
|NULL
|

|
|<<column-prescript>>
|nvarchar(max)
|NULL
|

|
|<<column-sourceunderlinerepoobjectunderlineguid>>
|uniqueidentifier
|NULL
|

|
|<<column-sourceunderlinerepoobjectunderlinename>>
|nvarchar(128)
|NULL
|

|
|<<column-isunderlinepersistence>>

.Definition
[source,sql]
----
(CONVERT([bit],(1),(0)))
----


|bit
|NULL
|

|
|<<column-temporalunderlinetype>>

.Definition
[source,sql]
----
(CONVERT([tinyint],case [has_history] when (1) then (2) else (0) end,(0)))
----


|tinyint
|NULL
|

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

[#index-pkunderlinerepoobjectunderlinepersistence]
=== PK_RepoObject_persistence

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-target_RepoObject_guid>>; uniqueidentifier
--
* PK, Unique, Real: 1, 1, 1
* ++FK_RepoObject_persistence__RepoObject__target++ +
referenced: xref:repo.repoobject.adoc[], xref:repo.repoobject.adoc#index-pkunderlinerepoobject[+PK_RepoObject+]

// end::AntoraIndexList[]

== AntoraMeasureDetails

// tag::AntoraMeasureDetails[]

// end::AntoraMeasureDetails[]

== AntoraMeasureDescriptions



== AntoraParameterList

// tag::AntoraParameterList[]

// end::AntoraParameterList[]

== AntoraXrefCulturesList

// tag::AntoraXrefCulturesList[]
* xref:dhw:sqldb:repo.repoobject_persistence.adoc[] - 
// end::AntoraXrefCulturesList[]

== cultures_count

// tag::cultures_count[]
1
// end::cultures_count[]

== Other tags

source: property.RepoObjectProperty_cross As rop_cross


=== additional_reference_csv

// tag::additional_reference_csv[]

// end::additional_reference_csv[]


=== AdocUspSteps

// tag::adocuspsteps[]

// end::adocuspsteps[]


=== AntoraReferencedList

// tag::antorareferencedlist[]

// end::antorareferencedlist[]


=== AntoraReferencingList

// tag::antorareferencinglist[]
* xref:dhw:sqldb:reference.repoobject_reference_persistence.adoc[]
* xref:dhw:sqldb:reference.repoobject_reference_persistence_target_as_source_explicit.adoc[]
* xref:dhw:sqldb:reference.repoobject_reference_t_bidirectional.adoc[]
* xref:dhw:sqldb:reference.repoobjectcolumn_reference_persistence.adoc[]
* xref:dhw:sqldb:repo.repoobject__after_delete.adoc[]
* xref:dhw:sqldb:repo.repoobject_columnlist.adoc[]
* xref:dhw:sqldb:repo.repoobject_gross.adoc[]
* xref:dhw:sqldb:repo.repoobject_gross_persistence.adoc[]
* xref:dhw:sqldb:repo.repoobject_persistence_column.adoc[]
* xref:dhw:sqldb:repo.repoobject_persistence_forupdate.adoc[]
* xref:dhw:sqldb:repo.repoobject_persistence_nocomparebutupdate.adoc[]
* xref:dhw:sqldb:repo.repoobject_persistence_nocomparenoupdate.adoc[]
* xref:dhw:sqldb:repo.repoobject_persistence_noinsert.adoc[]
* xref:dhw:sqldb:repo.repoobject_persistence_objectnames.adoc[]
* xref:dhw:sqldb:repo.repoobject_persistence_source_ignore.adoc[]
* xref:dhw:sqldb:repo.repoobject_persistence_target_ignore.adoc[]
* xref:dhw:sqldb:repo.repoobjectcolumn_gross.adoc[]
* xref:dhw:sqldb:repo.repoobjectcolumn_histvalidcolums_setpoint.adoc[]
* xref:dhw:sqldb:repo.usp_index_finish.adoc[]
* xref:dhw:sqldb:repo.usp_main.adoc[]
* xref:dhw:sqldb:repo.usp_persistence_delete.adoc[]
* xref:dhw:sqldb:repo.usp_persistence_set.adoc[]
* xref:dhw:sqldb:repo.usp_sync_guid_repoobject.adoc[]
* xref:dhw:sqldb:repo.usp_sync_guid_repoobjectcolumn.adoc[]
* xref:dhw:sqldb:uspgenerator.generatorusp_check_persistence.adoc[]
// end::antorareferencinglist[]


=== Description

// tag::description[]

// end::description[]


=== exampleUsage

// tag::exampleusage[]

// end::exampleusage[]


=== exampleUsage_2

// tag::exampleusage_2[]

// end::exampleusage_2[]


=== exampleUsage_3

// tag::exampleusage_3[]

// end::exampleusage_3[]


=== exampleUsage_4

// tag::exampleusage_4[]

// end::exampleusage_4[]


=== exampleUsage_5

// tag::exampleusage_5[]

// end::exampleusage_5[]


=== exampleWrong_Usage

// tag::examplewrong_usage[]

// end::examplewrong_usage[]


=== has_execution_plan_issue

// tag::has_execution_plan_issue[]

// end::has_execution_plan_issue[]


=== has_get_referenced_issue

// tag::has_get_referenced_issue[]

// end::has_get_referenced_issue[]


=== has_history

// tag::has_history[]

// end::has_history[]


=== has_history_columns

// tag::has_history_columns[]

// end::has_history_columns[]


=== InheritanceType

// tag::inheritancetype[]

// end::inheritancetype[]


=== is_persistence

// tag::is_persistence[]

// end::is_persistence[]


=== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]

// end::is_persistence_check_duplicate_per_pk[]


=== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]

// end::is_persistence_check_for_empty_source[]


=== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]

// end::is_persistence_delete_changed[]


=== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]

// end::is_persistence_delete_missing[]


=== is_persistence_insert

// tag::is_persistence_insert[]

// end::is_persistence_insert[]


=== is_persistence_truncate

// tag::is_persistence_truncate[]

// end::is_persistence_truncate[]


=== is_persistence_update_changed

// tag::is_persistence_update_changed[]

// end::is_persistence_update_changed[]


=== is_repo_managed

// tag::is_repo_managed[]
0
// end::is_repo_managed[]


=== is_ssas

// tag::is_ssas[]
0
// end::is_ssas[]


=== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


=== MS_Description

// tag::ms_description[]

// end::ms_description[]


=== persistence_source_RepoObject_fullname

// tag::persistence_source_repoobject_fullname[]

// end::persistence_source_repoobject_fullname[]


=== persistence_source_RepoObject_fullname2

// tag::persistence_source_repoobject_fullname2[]

// end::persistence_source_repoobject_fullname2[]


=== persistence_source_RepoObject_guid

// tag::persistence_source_repoobject_guid[]

// end::persistence_source_repoobject_guid[]


=== persistence_source_RepoObject_xref

// tag::persistence_source_repoobject_xref[]

// end::persistence_source_repoobject_xref[]


=== pk_index_guid

// tag::pk_index_guid[]
4890291C-9D61-EB11-84DC-A81E8446D5B0
// end::pk_index_guid[]


=== pk_IndexPatternColumnDatatype

// tag::pk_indexpatterncolumndatatype[]
uniqueidentifier
// end::pk_indexpatterncolumndatatype[]


=== pk_IndexPatternColumnName

// tag::pk_indexpatterncolumnname[]
target_RepoObject_guid
// end::pk_indexpatterncolumnname[]


=== pk_IndexSemanticGroup

// tag::pk_indexsemanticgroup[]

// end::pk_indexsemanticgroup[]


=== ReferencedObjectList

// tag::referencedobjectlist[]

// end::referencedobjectlist[]


=== usp_persistence_RepoObject_guid

// tag::usp_persistence_repoobject_guid[]

// end::usp_persistence_repoobject_guid[]


=== UspExamples

// tag::uspexamples[]

// end::uspexamples[]


=== uspgenerator_usp_id

// tag::uspgenerator_usp_id[]

// end::uspgenerator_usp_id[]


=== UspParameters

// tag::uspparameters[]

// end::uspparameters[]

== Boolean Attributes

source: property.RepoObjectProperty WHERE property_int = 1

// tag::boolean_attributes[]


// end::boolean_attributes[]

== PlantUML diagrams

=== PlantUML Entity

// tag::puml_entity[]
[plantuml, entity-{docname}, svg, subs=macros]
....
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:repo.repoobject_persistence.adoc[]" as repo.RepoObject_persistence << U >> {
  - **target_RepoObject_guid** : (uniqueidentifier)
  ColumnListIgnore : (nvarchar(4000))
  ColumnListNoCompareButUpdate : (nvarchar(4000))
  ColumnListNoCompareNoUpdate : (nvarchar(4000))
  ColumnListNoInsert : (nvarchar(4000))
  ExecutionLogId_action : (char(1))
  final_target_RepoObject_name : (nvarchar(128))
  - has_history : (bit)
  - has_history_columns : (bit)
  history_schema_name : (nvarchar(128))
  history_table_name : (nvarchar(128))
  - is_persistence_check_duplicate_per_pk : (bit)
  - is_persistence_check_for_empty_source : (bit)
  - is_persistence_delete_changed : (bit)
  - is_persistence_delete_missing : (bit)
  - is_persistence_insert : (bit)
  - is_persistence_persist_source : (bit)
  - is_persistence_truncate : (bit)
  - is_persistence_update_changed : (bit)
  postscript : (nvarchar(max))
  prescript : (nvarchar(max))
  source_RepoObject_guid : (uniqueidentifier)
  source_RepoObject_name : (nvarchar(128))
  ~ is_persistence : (bit)
  ~ temporal_type : (tinyint)
  --
}
....

// end::puml_entity[]

=== PlantUML Entity 1 1 FK

// tag::puml_entity_1_1_fk[]
[plantuml, entity_1_1_fk-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:repo.repoobject.adoc[]" as repo.RepoObject << U >> {
**PK_RepoObject**

..
RepoObject_guid; uniqueidentifier
--
UK_RepoObject__RepoNames

..
RepoObject_schema_name; nvarchar(128)
RepoObject_name; nvarchar(128)
--
UK_RepoObject__SysNames

..
SysObject_schema_name; nvarchar(128)
SysObject_name; nvarchar(128)
--
- idx_RepoObject__1

..
pk_index_guid; uniqueidentifier
}

entity "puml-link:dhw:sqldb:repo.repoobject_persistence.adoc[]" as repo.RepoObject_persistence << U >> {
**PK_RepoObject_persistence**

..
target_RepoObject_guid; uniqueidentifier
}

"repo.RepoObject::PK_RepoObject" <-- "repo.RepoObject_persistence::PK_RepoObject_persistence"

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_fk[]

=== PlantUML 1 1 ObjectRef

// tag::puml_entity_1_1_objectref[]
[plantuml, entity_1_1_objectref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:reference.repoobject_reference_persistence.adoc[]" as reference.RepoObject_reference_persistence << V >> {
  **referenced_RepoObject_guid** : (uniqueidentifier)
  - **referencing_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_reference_persistence_target_as_source_explicit.adoc[]" as reference.RepoObject_reference_persistence_target_as_source_explicit << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_reference_t_bidirectional.adoc[]" as reference.RepoObject_reference_T_bidirectional << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_reference_persistence.adoc[]" as reference.RepoObjectColumn_reference_Persistence << V >> {
  **referencing_id** : (int)
  **referencing_minor_id** : (int)
  **referenced_id** : (int)
  **referenced_minor_id** : (int)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject__after_delete.adoc[]" as repo.RepoObject__after_delete << TR >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_columnlist.adoc[]" as repo.RepoObject_ColumnList << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_gross.adoc[]" as repo.RepoObject_gross << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_gross_persistence.adoc[]" as repo.RepoObject_gross_persistence << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_persistence.adoc[]" as repo.RepoObject_persistence << U >> {
  - **target_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_persistence_column.adoc[]" as repo.RepoObject_persistence_column << V >> {
  - **target_RepoObject_guid** : (uniqueidentifier)
  **RepoObjectColumn_guid_s** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_persistence_forupdate.adoc[]" as repo.RepoObject_persistence_ForUpdate << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_persistence_nocomparebutupdate.adoc[]" as repo.RepoObject_persistence_NoCompareButUpdate << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_persistence_nocomparenoupdate.adoc[]" as repo.RepoObject_persistence_NoCompareNoUpdate << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_persistence_noinsert.adoc[]" as repo.RepoObject_persistence_NoInsert << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_persistence_objectnames.adoc[]" as repo.RepoObject_persistence_ObjectNames << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_persistence_source_ignore.adoc[]" as repo.RepoObject_persistence_source_Ignore << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_persistence_target_ignore.adoc[]" as repo.RepoObject_persistence_target_Ignore << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn_gross.adoc[]" as repo.RepoObjectColumn_gross << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn_histvalidcolums_setpoint.adoc[]" as repo.RepoObjectColumn_HistValidColums_setpoint << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  **RepoObjectColumn_name** : (sysname)
  --
}

entity "puml-link:dhw:sqldb:repo.usp_index_finish.adoc[]" as repo.usp_Index_finish << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_main.adoc[]" as repo.usp_main << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_persistence_delete.adoc[]" as repo.usp_persistence_delete << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_persistence_set.adoc[]" as repo.usp_persistence_set << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_sync_guid_repoobject.adoc[]" as repo.usp_sync_guid_RepoObject << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_sync_guid_repoobjectcolumn.adoc[]" as repo.usp_sync_guid_RepoObjectColumn << P >> {
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.generatorusp_check_persistence.adoc[]" as uspgenerator.GeneratorUsp_check_persistence << V >> {
  --
}

repo.RepoObject_persistence <.. reference.RepoObject_reference_persistence
repo.RepoObject_persistence <.. reference.RepoObject_reference_persistence_target_as_source_explicit
repo.RepoObject_persistence <.. reference.RepoObject_reference_T_bidirectional
repo.RepoObject_persistence <.. reference.RepoObjectColumn_reference_Persistence
repo.RepoObject_persistence <.. repo.RepoObject__after_delete
repo.RepoObject_persistence <.. repo.RepoObject_ColumnList
repo.RepoObject_persistence <.. repo.RepoObject_gross
repo.RepoObject_persistence <.. repo.RepoObject_gross_persistence
repo.RepoObject_persistence <.. repo.RepoObject_persistence_column
repo.RepoObject_persistence <.. repo.RepoObject_persistence_ForUpdate
repo.RepoObject_persistence <.. repo.RepoObject_persistence_NoCompareButUpdate
repo.RepoObject_persistence <.. repo.RepoObject_persistence_NoCompareNoUpdate
repo.RepoObject_persistence <.. repo.RepoObject_persistence_NoInsert
repo.RepoObject_persistence <.. repo.RepoObject_persistence_ObjectNames
repo.RepoObject_persistence <.. repo.RepoObject_persistence_source_Ignore
repo.RepoObject_persistence <.. repo.RepoObject_persistence_target_Ignore
repo.RepoObject_persistence <.. repo.RepoObjectColumn_gross
repo.RepoObject_persistence <.. repo.RepoObjectColumn_HistValidColums_setpoint
repo.RepoObject_persistence <.. repo.usp_Index_finish
repo.RepoObject_persistence <.. repo.usp_main
repo.RepoObject_persistence <.. repo.usp_persistence_delete
repo.RepoObject_persistence <.. repo.usp_persistence_set
repo.RepoObject_persistence <.. repo.usp_sync_guid_RepoObject
repo.RepoObject_persistence <.. repo.usp_sync_guid_RepoObjectColumn
repo.RepoObject_persistence <.. uspgenerator.GeneratorUsp_check_persistence

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_objectref[]

=== PlantUML 30 0 ObjectRef

// tag::puml_entity_30_0_objectref[]
[plantuml, entity_30_0_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:repo.repoobject_persistence.adoc[]" as repo.RepoObject_persistence << U >> {
  - **target_RepoObject_guid** : (uniqueidentifier)
  --
}



footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_30_0_objectref[]

=== PlantUML 0 30 ObjectRef

// tag::puml_entity_0_30_objectref[]
[plantuml, entity_0_30_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:dmdocs.unit.adoc[]" as dmdocs.unit << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.antoranavlistpage_by_schema.adoc[]" as docs.AntoraNavListPage_by_schema << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.antoranavlistpage_by_type.adoc[]" as docs.AntoraNavListPage_by_type << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.antoranavlistrepoobject_by_schema.adoc[]" as docs.AntoraNavListRepoObject_by_schema << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.antoranavlistrepoobject_by_schema_type.adoc[]" as docs.AntoraNavListRepoObject_by_schema_type << V >> {
  - **RepoObject_schema_name** : (nvarchar(128))
  **type** : (char(2))
  --
}

entity "puml-link:dhw:sqldb:docs.antoranavlistrepoobject_by_type.adoc[]" as docs.AntoraNavListRepoObject_by_type << V >> {
  **type** : (char(2))
  --
}

entity "puml-link:dhw:sqldb:docs.antorapage_indexsemanticgroup.adoc[]" as docs.AntoraPage_IndexSemanticGroup << V >> {
  - **page_content** : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:docs.antorapage_objectbyschema.adoc[]" as docs.AntoraPage_ObjectBySchema << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.antorapage_objectbytype.adoc[]" as docs.AntoraPage_ObjectByType << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.foreignkey_relationscript.adoc[]" as docs.ForeignKey_RelationScript << V >> {
  **referenced_RepoObject_guid** : (uniqueidentifier)
  **referencing_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:docs.ftv_repoobject_reference_plantuml_entityreflist.adoc[]" as docs.ftv_RepoObject_Reference_PlantUml_EntityRefList << IF >> {
  --
}

entity "puml-link:dhw:sqldb:docs.indexsemanticgroup.adoc[]" as docs.IndexSemanticgroup << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.indexsemanticgrouppatterndatatype.adoc[]" as docs.IndexSemanticgroupPatterndatatype << V >> {
  **IndexSemanticGroup** : (nvarchar(512))
  **IndexPatternColumnDatatype** : (nvarchar(4000))
  --
}

entity "puml-link:dhw:sqldb:docs.objectrefcyclic.adoc[]" as docs.ObjectRefCyclic << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.objectrefcyclic_entitylist.adoc[]" as docs.ObjectRefCyclic_EntityList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.objectrefcyclic_objectreflist.adoc[]" as docs.ObjectRefCyclic_ObjectRefList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_adoc.adoc[]" as docs.RepoObject_Adoc << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_adoc_t.adoc[]" as docs.RepoObject_Adoc_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_antoraxrefcultureslist.adoc[]" as docs.RepoObject_AntoraXrefCulturesList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_columnlist.adoc[]" as docs.RepoObject_ColumnList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_columnlist_t.adoc[]" as docs.RepoObject_ColumnList_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_indexlist.adoc[]" as docs.RepoObject_IndexList << V >> {
  **RepoObject_guid** : (uniqueidentifier)
  **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_indexlist_t.adoc[]" as docs.RepoObject_IndexList_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_measuredescriptionlist.adoc[]" as docs.RepoObject_MeasureDescriptionList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_measurelist.adoc[]" as docs.RepoObject_MeasureList << V >> {
  **RepoObject_guid** : (uniqueidentifier)
  **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_outputfilter.adoc[]" as docs.RepoObject_OutputFilter << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_outputfilter_t.adoc[]" as docs.RepoObject_OutputFilter_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_outputfilter_t_gross.adoc[]" as docs.RepoObject_OutputFilter_T_gross << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml.adoc[]" as docs.RepoObject_Plantuml << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_colreflist_1_1.adoc[]" as docs.RepoObject_Plantuml_ColRefList_1_1 << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_entity.adoc[]" as docs.RepoObject_Plantuml_Entity << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_entity_t.adoc[]" as docs.RepoObject_Plantuml_Entity_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_fkreflist.adoc[]" as docs.RepoObject_PlantUml_FkRefList << V >> {
  **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_objectreflist_0_30.adoc[]" as docs.RepoObject_Plantuml_ObjectRefList_0_30 << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_objectreflist_1_1.adoc[]" as docs.RepoObject_Plantuml_ObjectRefList_1_1 << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_objectreflist_30_0.adoc[]" as docs.RepoObject_Plantuml_ObjectRefList_30_0 << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_pumlentityfklist.adoc[]" as docs.RepoObject_PlantUml_PumlEntityFkList << V >> {
  **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_t.adoc[]" as docs.RepoObject_Plantuml_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.schema_entitylist.adoc[]" as docs.Schema_EntityList << V >> {
  - **RepoObject_schema_name** : (nvarchar(128))
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.schema_puml.adoc[]" as docs.Schema_puml << V >> {
  - **RepoSchema_guid** : (uniqueidentifier)
  **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.schema_pumlpartial_fkreflist.adoc[]" as docs.Schema_PumlPartial_FkRefList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.schema_ssasrelationlist.adoc[]" as docs.Schema_SsasRelationList << V >> {
  - **SchemaName** : (nvarchar(128))
  **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.unit_1_union.adoc[]" as docs.Unit_1_union << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.unit_2.adoc[]" as docs.Unit_2 << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.unit_3.adoc[]" as docs.Unit_3 << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport.adoc[]" as docs.usp_AntoraExport << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_objectnavigation.adoc[]" as docs.usp_AntoraExport_ObjectNavigation << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_objectpage.adoc[]" as docs.usp_AntoraExport_ObjectPage << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_objectpartialscontent.adoc[]" as docs.usp_AntoraExport_ObjectPartialsContent << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_objectpuml.adoc[]" as docs.usp_AntoraExport_ObjectPuml << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_repoobject_adoc_t.adoc[]" as docs.usp_PERSIST_RepoObject_Adoc_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_repoobject_columnlist_t.adoc[]" as docs.usp_PERSIST_RepoObject_ColumnList_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_repoobject_indexlist_t.adoc[]" as docs.usp_PERSIST_RepoObject_IndexList_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_repoobject_outputfilter_t.adoc[]" as docs.usp_PERSIST_RepoObject_OutputFilter_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_repoobject_plantuml_entity_t.adoc[]" as docs.usp_PERSIST_RepoObject_Plantuml_Entity_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_repoobject_plantuml_t.adoc[]" as docs.usp_PERSIST_RepoObject_Plantuml_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:graph.repoobjectcolumn_s.adoc[]" as graph.RepoObjectColumn_S << V >> {
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectcolumnproperty_forupdate.adoc[]" as property.RepoObjectColumnProperty_ForUpdate << V >> {
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty_collect_source_rogross.adoc[]" as property.RepoObjectProperty_Collect_source_ROGross << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **property_name** : (varchar(39))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty_collect_source_uspgenerator.adoc[]" as property.RepoObjectProperty_Collect_source_uspgenerator << V >> {
  **RepoObject_guid** : (uniqueidentifier)
  - **property_name** : (varchar(14))
  --
}

entity "puml-link:dhw:sqldb:property.usp_repoobject_inheritance.adoc[]" as property.usp_RepoObject_Inheritance << P >> {
  --
}

entity "puml-link:dhw:sqldb:property.usp_repoobjectproperty_collect.adoc[]" as property.usp_RepoObjectProperty_collect << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.ftv_repoobject_columreferencerepoobject.adoc[]" as reference.ftv_RepoObject_ColumReferenceRepoObject << IF >> {
  --
}

entity "puml-link:dhw:sqldb:reference.ftv_repoobject_dbmlcolumnrelation.adoc[]" as reference.ftv_RepoObject_DbmlColumnRelation << IF >> {
  --
}

entity "puml-link:dhw:sqldb:reference.ftv_repoobject_referencetree.adoc[]" as reference.ftv_RepoObject_ReferenceTree << IF >> {
  --
}

entity "puml-link:dhw:sqldb:reference.ftv_repoobject_referencetree_referenced.adoc[]" as reference.ftv_RepoObject_ReferenceTree_referenced << IF >> {
  --
}

entity "puml-link:dhw:sqldb:reference.ftv_repoobject_referencetree_referencing.adoc[]" as reference.ftv_RepoObject_ReferenceTree_referencing << IF >> {
  --
}

entity "puml-link:dhw:sqldb:reference.ftv_repoobject_referencetree_via_fullname.adoc[]" as reference.ftv_RepoObject_ReferenceTree_via_fullname << IF >> {
  --
}

entity "puml-link:dhw:sqldb:reference.ftv_repoobjectcolumn_referencetree.adoc[]" as reference.ftv_RepoObjectColumn_ReferenceTree << IF >> {
  --
}

entity "puml-link:dhw:sqldb:reference.persistence.adoc[]" as reference.Persistence << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.persistence_bidirectional.adoc[]" as reference.Persistence_bidirectional << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.referencetree_cyclic_ref_persistenceusp.adoc[]" as reference.ReferenceTree_cyclic_ref_PersistenceUsp << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.referencetree_cyclic_union.adoc[]" as reference.ReferenceTree_cyclic_union << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_reference.adoc[]" as reference.RepoObject_reference << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_reference_persistence.adoc[]" as reference.RepoObject_reference_persistence << V >> {
  **referenced_RepoObject_guid** : (uniqueidentifier)
  - **referencing_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_reference_persistence_target_as_source.adoc[]" as reference.RepoObject_reference_persistence_target_as_source << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_reference_persistence_target_as_source_explicit.adoc[]" as reference.RepoObject_reference_persistence_target_as_source_explicit << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_reference_t.adoc[]" as reference.RepoObject_reference_T << U >> {
  - **referenced_RepoObject_guid** : (uniqueidentifier)
  - **referencing_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_reference_t_bidirectional.adoc[]" as reference.RepoObject_reference_T_bidirectional << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_reference_union.adoc[]" as reference.RepoObject_reference_union << V >> {
  **referenced_RepoObject_guid** : (uniqueidentifier)
  **referencing_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_referencedlist.adoc[]" as reference.RepoObject_ReferencedList << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_referencedreferencing.adoc[]" as reference.RepoObject_ReferencedReferencing << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_referencetree_0_30.adoc[]" as reference.RepoObject_ReferenceTree_0_30 << V >> {
  **RepoObject_guid** : (uniqueidentifier)
  **Referencing_guid** : (uniqueidentifier)
  **Referenced_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_referencetree_0_30_t.adoc[]" as reference.RepoObject_ReferenceTree_0_30_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **Referencing_guid** : (uniqueidentifier)
  - **Referenced_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_referencetree_30_0.adoc[]" as reference.RepoObject_ReferenceTree_30_0 << V >> {
  **RepoObject_guid** : (uniqueidentifier)
  **Referencing_guid** : (uniqueidentifier)
  **Referenced_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_referencetree_30_0_t.adoc[]" as reference.RepoObject_ReferenceTree_30_0_T << U >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_referencetree_referenced.adoc[]" as reference.RepoObject_ReferenceTree_referenced << V >> {
  **RepoObject_guid** : (uniqueidentifier)
  **Referenced_Depth** : (int)
  **Referencing_Depth** : (int)
  **Referenced_guid** : (uniqueidentifier)
  **Referencing_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_referencetree_referenced_30_0.adoc[]" as reference.RepoObject_ReferenceTree_referenced_30_0 << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  **Referenced_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_referencetree_referencing.adoc[]" as reference.RepoObject_ReferenceTree_referencing << V >> {
  **RepoObject_guid** : (uniqueidentifier)
  **Referenced_Depth** : (int)
  **Referencing_Depth** : (int)
  **Referenced_guid** : (uniqueidentifier)
  **Referencing_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_referencetree_referencing_0_30.adoc[]" as reference.RepoObject_ReferenceTree_referencing_0_30 << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  **Referencing_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_referencinglist.adoc[]" as reference.RepoObject_ReferencingList << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_reference.adoc[]" as reference.RepoObjectColumn_reference << V >> {
  **referenced_RepoObjectColumn_guid** : (uniqueidentifier)
  **referencing_RepoObjectColumn_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_reference_additional.adoc[]" as reference.RepoObjectColumn_reference_additional << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_reference_additional_internal.adoc[]" as reference.RepoObjectColumn_reference_additional_internal << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_reference_bysamepredecessors.adoc[]" as reference.RepoObjectColumn_reference_BySamePredecessors << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_reference_firstresultset.adoc[]" as reference.RepoObjectColumn_reference_FirstResultSet << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_reference_persistence.adoc[]" as reference.RepoObjectColumn_reference_Persistence << V >> {
  **referencing_id** : (int)
  **referencing_minor_id** : (int)
  **referenced_id** : (int)
  **referenced_minor_id** : (int)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_reference_queryplan.adoc[]" as reference.RepoObjectColumn_reference_QueryPlan << V >> {
  **referencing_id** : (int)
  **referencing_minor_id** : (int)
  **referenced_id** : (int)
  **referenced_minor_id** : (int)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_reference_sqlexpressiondependencies.adoc[]" as reference.RepoObjectColumn_reference_SqlExpressionDependencies << V >> {
  - **referencing_id** : (int)
  - **referencing_minor_id** : (int)
  **referenced_id** : (int)
  - **referenced_minor_id** : (int)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_reference_t.adoc[]" as reference.RepoObjectColumn_reference_T << U >> {
  - **referenced_RepoObjectColumn_guid** : (uniqueidentifier)
  - **referencing_RepoObjectColumn_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_reference_union.adoc[]" as reference.RepoObjectColumn_reference_union << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_reference_virtual.adoc[]" as reference.RepoObjectColumn_reference_virtual << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_referencedlist.adoc[]" as reference.RepoObjectColumn_ReferencedList << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_referencedreferencing.adoc[]" as reference.RepoObjectColumn_ReferencedReferencing << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_referencetree.adoc[]" as reference.RepoObjectColumn_ReferenceTree << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_referencinglist.adoc[]" as reference.RepoObjectColumn_ReferencingList << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_relationscript.adoc[]" as reference.RepoObjectColumn_RelationScript << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.sysobjectcolumn_queryplanexpression.adoc[]" as reference.SysObjectColumn_QueryPlanExpression << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_persist_repoobject_reference_t.adoc[]" as reference.usp_PERSIST_RepoObject_reference_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_persist_repoobject_referencetree_0_30_t.adoc[]" as reference.usp_PERSIST_RepoObject_ReferenceTree_0_30_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_persist_repoobject_referencetree_30_0_t.adoc[]" as reference.usp_PERSIST_RepoObject_ReferenceTree_30_0_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_persist_repoobjectcolumn_reference_t.adoc[]" as reference.usp_PERSIST_RepoObjectColumn_reference_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_repoobject_referencetree.adoc[]" as reference.usp_RepoObject_ReferenceTree << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_repoobject_referencetree_insert.adoc[]" as reference.usp_RepoObject_ReferenceTree_insert << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_repoobject_update_sysobjectqueryplan.adoc[]" as reference.usp_RepoObject_update_SysObjectQueryPlan << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_repoobjectcolumnsource_virtual_set.adoc[]" as reference.usp_RepoObjectColumnSource_virtual_set << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_repoobjectsource_firstresultset.adoc[]" as reference.usp_RepoObjectSource_FirstResultSet << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_repoobjectsource_queryplan.adoc[]" as reference.usp_RepoObjectSource_QueryPlan << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.check_indexcolumn_virtual_referenced_setpoint.adoc[]" as repo.check_IndexColumn_virtual_referenced_setpoint << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.foreignkey_gross.adoc[]" as repo.ForeignKey_gross << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.foreignkey_indexes.adoc[]" as repo.ForeignKey_Indexes << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.foreignkey_indexes_union.adoc[]" as repo.ForeignKey_Indexes_union << V >> {
  **ForeignKey_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.foreignkey_indexes_union_t.adoc[]" as repo.ForeignKey_Indexes_union_T << U >> {
  **ForeignKey_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.foreignkey_virtual_indexes.adoc[]" as repo.ForeignKey_virtual_Indexes << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.index_gross.adoc[]" as repo.Index_gross << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.index_referencing_indexpatterncolumnguid.adoc[]" as repo.Index_referencing_IndexPatternColumnGuid << V >> {
  **source_index_guid** : (uniqueidentifier)
  **referencing_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.index_virtual_forupdate.adoc[]" as repo.Index_virtual_ForUpdate << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.indexcolumn_referencedreferencing_hasfullcolumnsinreferencing.adoc[]" as repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing << V >> {
  - **index_guid** : (uniqueidentifier)
  - **index_column_id** : (int)
  **RowNumberInReferencing** : (bigint)
  --
}

entity "puml-link:dhw:sqldb:repo.indexcolumn_referencedreferencing_hasfullcolumnsinreferencing_check.adoc[]" as repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_check << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.indexcolumn_referencedreferencing_hasfullcolumnsinreferencing_t.adoc[]" as repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T << U >> {
  **index_guid** : (uniqueidentifier)
  - **index_column_id** : (int)
  **RowNumberInReferencing** : (bigint)
  --
}

entity "puml-link:dhw:sqldb:repo.indexcolumn_virtual_referenced_setpoint.adoc[]" as repo.IndexColumn_virtual_referenced_setpoint << V >> {
  - **index_guid** : (uniqueidentifier)
  - **index_column_id** : (int)
  --
}

entity "puml-link:dhw:sqldb:repo.indexreferencedreferencing.adoc[]" as repo.IndexReferencedReferencing << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.indexreferencedreferencing_hasfullcolumnsinreferencing.adoc[]" as repo.IndexReferencedReferencing_HasFullColumnsInReferencing << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject__after_delete.adoc[]" as repo.RepoObject__after_delete << TR >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_columnlist.adoc[]" as repo.RepoObject_ColumnList << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_gross.adoc[]" as repo.RepoObject_gross << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_gross_persistence.adoc[]" as repo.RepoObject_gross_persistence << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_gross2.adoc[]" as repo.RepoObject_gross2 << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_persistence.adoc[]" as repo.RepoObject_persistence << U >> {
  - **target_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_persistence_column.adoc[]" as repo.RepoObject_persistence_column << V >> {
  - **target_RepoObject_guid** : (uniqueidentifier)
  **RepoObjectColumn_guid_s** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_persistence_forupdate.adoc[]" as repo.RepoObject_persistence_ForUpdate << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_persistence_nocomparebutupdate.adoc[]" as repo.RepoObject_persistence_NoCompareButUpdate << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_persistence_nocomparenoupdate.adoc[]" as repo.RepoObject_persistence_NoCompareNoUpdate << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_persistence_noinsert.adoc[]" as repo.RepoObject_persistence_NoInsert << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_persistence_objectnames.adoc[]" as repo.RepoObject_persistence_ObjectNames << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_persistence_source_ignore.adoc[]" as repo.RepoObject_persistence_source_Ignore << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_persistence_sourcemismatch.adoc[]" as repo.RepoObject_persistence_SourceMismatch << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_persistence_target_ignore.adoc[]" as repo.RepoObject_persistence_target_Ignore << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_related_fk_union.adoc[]" as repo.RepoObject_related_FK_union << V >> {
  **RepoObject_guid** : (uniqueidentifier)
  **included_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_sat2.adoc[]" as repo.RepoObject_sat2 << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_sat2_t.adoc[]" as repo.RepoObject_sat2_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_sqlcreatetable.adoc[]" as repo.RepoObject_SqlCreateTable << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_wo_referencing.adoc[]" as repo.RepoObject_wo_referencing << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn_gross.adoc[]" as repo.RepoObjectColumn_gross << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn_gross2.adoc[]" as repo.RepoObjectColumn_gross2 << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn_histvalidcolums_setpoint.adoc[]" as repo.RepoObjectColumn_HistValidColums_setpoint << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  **RepoObjectColumn_name** : (sysname)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn_missingsource_typev.adoc[]" as repo.RepoObjectColumn_MissingSource_TypeV << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_index_finish.adoc[]" as repo.usp_Index_finish << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_index_foreignkey.adoc[]" as repo.usp_Index_ForeignKey << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_index_inheritance.adoc[]" as repo.usp_index_inheritance << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_index_virtual_set.adoc[]" as repo.usp_Index_virtual_set << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_main.adoc[]" as repo.usp_main << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_persist_foreignkey_indexes_union_t.adoc[]" as repo.usp_PERSIST_ForeignKey_Indexes_union_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_persist_indexcolumn_referencedreferencing_hasfullcolumnsinreferencing_t.adoc[]" as repo.usp_PERSIST_IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_persist_repoobject_sat2_t.adoc[]" as repo.usp_PERSIST_RepoObject_sat2_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_persistence_delete.adoc[]" as repo.usp_persistence_delete << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_persistence_set.adoc[]" as repo.usp_persistence_set << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_sync_guid.adoc[]" as repo.usp_sync_guid << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_sync_guid_repoobject.adoc[]" as repo.usp_sync_guid_RepoObject << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_sync_guid_repoobjectcolumn.adoc[]" as repo.usp_sync_guid_RepoObjectColumn << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.repoobjectcolumn_translation.adoc[]" as ssas.RepoObjectColumn_translation << V >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:ssas.repoobjectcolumn_translation_displayfolder_union.adoc[]" as ssas.RepoObjectColumn_translation_displayfolder_union << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.repoobjectcolumn_translation_t.adoc[]" as ssas.RepoObjectColumn_translation_T << U >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:ssas.usp_persist_repoobjectcolumn_translation_t.adoc[]" as ssas.usp_PERSIST_RepoObjectColumn_translation_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.generatorusp_check_persistence.adoc[]" as uspgenerator.GeneratorUsp_check_persistence << V >> {
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.generatorusp_sqlusp.adoc[]" as uspgenerator.GeneratorUsp_SqlUsp << V >> {
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.generatorusp_sqlviewpersistenceupdatecheck.adoc[]" as uspgenerator.GeneratorUsp_SqlViewPersistenceUpdateCheck << V >> {
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.generatoruspstep_persistence_isinactive_setpoint.adoc[]" as uspgenerator.GeneratorUspStep_Persistence_IsInactive_setpoint << V >> {
  - **usp_id** : (int)
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.generatoruspstep_persistence_src.adoc[]" as uspgenerator.GeneratorUspStep_Persistence_src << V >> {
  - **usp_id** : (int)
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.usp_generatorusp_insert_update_persistence.adoc[]" as uspgenerator.usp_GeneratorUsp_insert_update_persistence << P >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.biml_package.adoc[]" as workflow.Biml_Package << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.biml_precedenceconstraints.adoc[]" as workflow.Biml_PrecedenceConstraints << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.biml_project.adoc[]" as workflow.Biml_Project << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.biml_task.adoc[]" as workflow.Biml_Task << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.proceduredependency.adoc[]" as workflow.ProcedureDependency << U >> {
  - **id** : (int)
  --
}

entity "puml-link:dhw:sqldb:workflow.proceduredependency_gross.adoc[]" as workflow.ProcedureDependency_gross << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.proceduredependency_input_persistencedependency.adoc[]" as workflow.ProcedureDependency_input_PersistenceDependency << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.proceduredependency_input_persistencedependency_s.adoc[]" as workflow.ProcedureDependency_input_PersistenceDependency_S << V >> {
  **referenced_Procedure_RepoObject_guid** : (uniqueidentifier)
  **referencing_Procedure_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:workflow.proceduredependency_persistencedependency_src.adoc[]" as workflow.ProcedureDependency_PersistenceDependency_src << V >> {
  **referenced_Procedure_RepoObject_guid** : (uniqueidentifier)
  **referencing_Procedure_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:workflow.proceduredependency_persistencedependency_tgt.adoc[]" as workflow.ProcedureDependency_PersistenceDependency_tgt << V >> {
  - **referenced_Procedure_RepoObject_guid** : (uniqueidentifier)
  - **referencing_Procedure_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:workflow.usp_persist_proceduredependency_persistencedependency_tgt.adoc[]" as workflow.usp_PERSIST_ProcedureDependency_PersistenceDependency_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.usp_persist_workflow_proceduredependency_t.adoc[]" as workflow.usp_PERSIST_Workflow_ProcedureDependency_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.usp_persist_workflowstep.adoc[]" as workflow.usp_PERSIST_WorkflowStep << P >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.usp_workflow.adoc[]" as workflow.usp_workflow << P >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.workflow_proceduredependency.adoc[]" as workflow.Workflow_ProcedureDependency << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.workflow_proceduredependency_all.adoc[]" as workflow.Workflow_ProcedureDependency_all << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.workflow_proceduredependency_t.adoc[]" as workflow.Workflow_ProcedureDependency_T << U >> {
  - **Workflow_id** : (int)
  - **referenced_Procedure_RepoObject_guid** : (uniqueidentifier)
  - **referencing_Procedure_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:workflow.workflow_proceduredependency_t_active.adoc[]" as workflow.Workflow_ProcedureDependency_T_active << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.workflow_proceduredependency_t_bidirectional.adoc[]" as workflow.Workflow_ProcedureDependency_T_bidirectional << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.workflow_proceduredependency_t_bidirectional_t.adoc[]" as workflow.Workflow_ProcedureDependency_T_bidirectional_T << U >> {
  - **Workflow_id** : (int)
  - **referenced_Procedure_RepoObject_guid** : (uniqueidentifier)
  - **referencing_Procedure_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:workflow.workflow_proceduredependency_t_notinsortorder.adoc[]" as workflow.Workflow_ProcedureDependency_T_NotInSortorder << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.workflow_proceduredependency_t_notinsortorder_check.adoc[]" as workflow.Workflow_ProcedureDependency_T_NotInSortorder_check << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.workflow_proceduredependency_t_redundant.adoc[]" as workflow.Workflow_ProcedureDependency_T_redundant << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.workflow_proceduredependency_t_taskname.adoc[]" as workflow.Workflow_ProcedureDependency_T_TaskName << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.workflow_proceduredependency_wo_redundant.adoc[]" as workflow.Workflow_ProcedureDependency_wo_redundant << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.workflowstep.adoc[]" as workflow.WorkflowStep << U >> {
  - **id** : (int)
  --
}

entity "puml-link:dhw:sqldb:workflow.workflowstep_active.adoc[]" as workflow.WorkflowStep_active << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.workflowstep_forupdate.adoc[]" as workflow.WorkflowStep_ForUpdate << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.workflowstep_src.adoc[]" as workflow.WorkflowStep_src << V >> {
  - **Workflow_id** : (int)
  **Procedure_RepoObject_guid** : (uniqueidentifier)
  --
}

docs.AntoraNavListPage_by_type <.. docs.usp_AntoraExport_ObjectNavigation
docs.AntoraNavListRepoObject_by_schema <.. docs.AntoraPage_ObjectBySchema
docs.AntoraNavListRepoObject_by_schema <.. docs.usp_AntoraExport_ObjectNavigation
docs.AntoraNavListRepoObject_by_schema_type <.. docs.usp_AntoraExport_ObjectNavigation
docs.AntoraNavListRepoObject_by_type <.. docs.AntoraPage_ObjectByType
docs.AntoraNavListRepoObject_by_type <.. docs.usp_AntoraExport_ObjectNavigation
docs.ftv_RepoObject_Reference_PlantUml_EntityRefList <.. docs.RepoObject_Plantuml
docs.IndexSemanticgroup <.. docs.AntoraPage_IndexSemanticGroup
docs.IndexSemanticgroupPatterndatatype <.. docs.IndexSemanticgroup
docs.ObjectRefCyclic_EntityList <.. docs.ObjectRefCyclic
docs.ObjectRefCyclic_ObjectRefList <.. docs.ObjectRefCyclic
docs.RepoObject_Adoc <.. docs.RepoObject_Adoc_T
docs.RepoObject_Adoc <.. docs.usp_PERSIST_RepoObject_Adoc_T
docs.REpoObject_Adoc_T <.. docs.usp_PERSIST_RepoObject_Adoc_T
docs.RepoObject_AntoraXrefCulturesList <.. docs.RepoObject_Adoc
docs.RepoObject_ColumnList <.. docs.RepoObject_ColumnList_T
docs.RepoObject_ColumnList <.. docs.usp_PERSIST_RepoObject_ColumnList_T
docs.RepoObject_ColumnList_T <.. docs.RepoObject_Adoc
docs.RepoObject_ColumnList_T <.. docs.RepoObject_Plantuml_Entity
docs.RepoObject_ColumnList_T <.. docs.usp_PERSIST_RepoObject_ColumnList_T
docs.RepoObject_IndexList <.. docs.RepoObject_IndexList_T
docs.RepoObject_IndexList <.. docs.usp_PERSIST_RepoObject_IndexList_T
docs.RepoObject_IndexList_T <.. docs.RepoObject_Adoc
docs.RepoObject_IndexList_T <.. docs.RepoObject_Plantuml_Entity
docs.RepoObject_IndexList_T <.. docs.usp_PERSIST_RepoObject_IndexList_T
docs.RepoObject_MeasureDescriptionList <.. docs.RepoObject_Adoc
docs.RepoObject_MeasureList <.. docs.RepoObject_Adoc
docs.RepoObject_MeasureList <.. docs.RepoObject_Plantuml_Entity
docs.RepoObject_OutputFilter <.. docs.RepoObject_OutputFilter_T
docs.RepoObject_OutputFilter <.. docs.usp_PERSIST_RepoObject_OutputFilter_T
docs.RepoObject_OutputFilter_T <.. docs.AntoraNavListPage_by_schema
docs.RepoObject_OutputFilter_T <.. docs.AntoraNavListPage_by_type
docs.RepoObject_OutputFilter_T <.. docs.AntoraNavListRepoObject_by_schema
docs.RepoObject_OutputFilter_T <.. docs.AntoraNavListRepoObject_by_schema_type
docs.RepoObject_OutputFilter_T <.. docs.AntoraNavListRepoObject_by_type
docs.RepoObject_OutputFilter_T <.. docs.IndexSemanticgroupPatterndatatype
docs.RepoObject_OutputFilter_T <.. docs.RepoObject_AntoraXrefCulturesList
docs.RepoObject_OutputFilter_T <.. docs.RepoObject_ColumnList
docs.RepoObject_OutputFilter_T <.. docs.RepoObject_IndexList
docs.RepoObject_OutputFilter_T <.. docs.RepoObject_OutputFilter_T_gross
docs.RepoObject_OutputFilter_T <.. docs.RepoObject_Plantuml
docs.RepoObject_OutputFilter_T <.. docs.RepoObject_Plantuml_ColRefList_1_1
docs.RepoObject_OutputFilter_T <.. docs.RepoObject_Plantuml_Entity
docs.RepoObject_OutputFilter_T <.. docs.Schema_puml
docs.RepoObject_OutputFilter_T <.. docs.Schema_SsasRelationList
docs.RepoObject_OutputFilter_T <.. docs.Unit_1_union
docs.RepoObject_OutputFilter_T <.. docs.usp_AntoraExport_ObjectPage
docs.RepoObject_OutputFilter_T <.. docs.usp_AntoraExport_ObjectPartialsContent
docs.RepoObject_OutputFilter_T <.. docs.usp_PERSIST_RepoObject_OutputFilter_T
docs.RepoObject_OutputFilter_T_gross <.. docs.RepoObject_Adoc
docs.RepoObject_OutputFilter_T_gross <.. docs.RepoObject_MeasureDescriptionList
docs.RepoObject_OutputFilter_T_gross <.. docs.RepoObject_MeasureList
docs.RepoObject_Plantuml <.. docs.RepoObject_Plantuml_T
docs.RepoObject_Plantuml <.. docs.usp_PERSIST_RepoObject_Plantuml_T
docs.RepoObject_Plantuml_ColRefList_1_1 <.. docs.RepoObject_Plantuml
docs.RepoObject_Plantuml_Entity <.. docs.RepoObject_Plantuml_Entity_T
docs.RepoObject_Plantuml_Entity <.. docs.usp_PERSIST_RepoObject_Plantuml_Entity_T
docs.RepoObject_Plantuml_Entity_T <.. docs.ftv_RepoObject_Reference_PlantUml_EntityRefList
docs.RepoObject_Plantuml_Entity_T <.. docs.ObjectRefCyclic_EntityList
docs.RepoObject_Plantuml_Entity_T <.. docs.RepoObject_Adoc
docs.RepoObject_Plantuml_Entity_T <.. docs.RepoObject_PlantUml_PumlEntityFkList
docs.RepoObject_Plantuml_Entity_T <.. docs.Schema_EntityList
docs.RepoObject_Plantuml_Entity_T <.. docs.usp_PERSIST_RepoObject_Plantuml_Entity_T
docs.RepoObject_PlantUml_FkRefList <.. docs.RepoObject_Plantuml
docs.RepoObject_Plantuml_ObjectRefList_0_30 <.. docs.RepoObject_Plantuml
docs.RepoObject_Plantuml_ObjectRefList_1_1 <.. docs.RepoObject_Plantuml
docs.RepoObject_Plantuml_ObjectRefList_30_0 <.. docs.RepoObject_Plantuml
docs.RepoObject_PlantUml_PumlEntityFkList <.. docs.RepoObject_Plantuml
docs.RepoObject_Plantuml_T <.. docs.RepoObject_Adoc
docs.RepoObject_Plantuml_T <.. docs.usp_PERSIST_RepoObject_Plantuml_T
docs.Schema_EntityList <.. docs.Schema_puml
docs.Schema_puml <.. docs.AntoraNavListPage_by_schema
docs.Schema_PumlPartial_FkRefList <.. docs.Schema_puml
docs.Schema_SsasRelationList <.. docs.Schema_puml
docs.Unit_1_union <.. docs.Unit_2
docs.Unit_2 <.. docs.Unit_3
docs.Unit_3 <.. dmdocs.unit
docs.usp_AntoraExport_ObjectNavigation <.. docs.usp_AntoraExport
docs.usp_AntoraExport_ObjectPage <.. docs.usp_AntoraExport
docs.usp_AntoraExport_ObjectPartialsContent <.. docs.usp_AntoraExport
docs.usp_AntoraExport_ObjectPuml <.. docs.usp_AntoraExport
docs.usp_PERSIST_RepoObject_Adoc_T <.. docs.usp_AntoraExport_ObjectPartialsContent
docs.usp_PERSIST_RepoObject_ColumnList_T <.. docs.usp_AntoraExport_ObjectPartialsContent
docs.usp_PERSIST_RepoObject_IndexList_T <.. docs.usp_AntoraExport_ObjectPartialsContent
docs.usp_PERSIST_RepoObject_OutputFilter_T <.. docs.usp_AntoraExport
docs.usp_PERSIST_RepoObject_Plantuml_Entity_T <.. docs.usp_AntoraExport_ObjectPuml
docs.usp_PERSIST_RepoObject_Plantuml_T <.. docs.usp_AntoraExport_ObjectPuml
property.RepoObjectProperty_Collect_source_ROGross <.. property.usp_RepoObjectProperty_collect
property.RepoObjectProperty_Collect_source_uspgenerator <.. property.usp_RepoObjectProperty_collect
property.usp_RepoObject_Inheritance <.. repo.usp_main
property.usp_RepoObjectProperty_collect <.. property.usp_RepoObject_Inheritance
property.usp_RepoObjectProperty_collect <.. repo.usp_main
reference.ftv_RepoObject_ReferenceTree <.. reference.RepoObject_ReferenceTree_0_30
reference.ftv_RepoObject_ReferenceTree <.. reference.RepoObject_ReferenceTree_30_0
reference.ftv_RepoObject_ReferenceTree_referenced <.. reference.RepoObject_ReferenceTree_referenced
reference.ftv_RepoObject_ReferenceTree_referenced <.. reference.RepoObject_ReferenceTree_referenced_30_0
reference.ftv_RepoObject_ReferenceTree_referencing <.. reference.RepoObject_ReferenceTree_referencing
reference.ftv_RepoObject_ReferenceTree_referencing <.. reference.RepoObject_ReferenceTree_referencing_0_30
reference.ftv_RepoObjectColumn_ReferenceTree <.. reference.RepoObjectColumn_ReferenceTree
reference.Persistence <.. reference.Persistence_bidirectional
reference.Persistence <.. workflow.ProcedureDependency_input_PersistenceDependency_S
reference.Persistence <.. workflow.ProcedureDependency_PersistenceDependency_src
reference.ReferenceTree_cyclic_ref_PersistenceUsp <.. reference.ReferenceTree_cyclic_union
reference.ReferenceTree_cyclic_union <.. docs.ObjectRefCyclic_EntityList
reference.ReferenceTree_cyclic_union <.. docs.ObjectRefCyclic_ObjectRefList
reference.RepoObject_reference <.. reference.RepoObject_reference_T
reference.RepoObject_reference <.. reference.usp_PERSIST_RepoObject_reference_T
reference.RepoObject_reference_persistence <.. reference.RepoObject_reference_union
reference.RepoObject_reference_persistence <.. repo.usp_main
reference.RepoObject_reference_persistence_target_as_source <.. reference.RepoObject_reference
reference.RepoObject_reference_persistence_target_as_source <.. reference.RepoObject_reference_union
reference.RepoObject_reference_persistence_target_as_source <.. repo.usp_main
reference.RepoObject_reference_persistence_target_as_source_explicit <.. reference.RepoObject_reference
reference.RepoObject_reference_persistence_target_as_source_explicit <.. reference.RepoObject_reference_union
reference.RepoObject_reference_T <.. docs.RepoObject_Plantuml_ObjectRefList_0_30
reference.RepoObject_reference_T <.. docs.RepoObject_Plantuml_ObjectRefList_1_1
reference.RepoObject_reference_T <.. docs.RepoObject_Plantuml_ObjectRefList_30_0
reference.RepoObject_reference_T <.. reference.ReferenceTree_cyclic_ref_PersistenceUsp
reference.RepoObject_reference_T <.. reference.RepoObject_reference_T_bidirectional
reference.RepoObject_reference_T <.. reference.RepoObject_ReferencedReferencing
reference.RepoObject_reference_T <.. reference.RepoObjectColumn_reference_additional
reference.RepoObject_reference_T <.. reference.RepoObjectColumn_reference_additional_internal
reference.RepoObject_reference_T <.. reference.RepoObjectColumn_reference_BySamePredecessors
reference.RepoObject_reference_T <.. reference.RepoObjectColumn_reference_FirstResultSet
reference.RepoObject_reference_T <.. reference.RepoObjectColumn_reference_QueryPlan
reference.RepoObject_reference_T <.. reference.RepoObjectColumn_reference_SqlExpressionDependencies
reference.RepoObject_reference_T <.. reference.RepoObjectColumn_reference_virtual
reference.RepoObject_reference_T <.. reference.usp_PERSIST_RepoObject_reference_T
reference.RepoObject_reference_T <.. repo.IndexReferencedReferencing
reference.RepoObject_reference_T <.. repo.RepoObject_wo_referencing
reference.RepoObject_reference_T <.. repo.usp_main
reference.RepoObject_reference_union <.. reference.RepoObject_reference
reference.RepoObject_ReferencedList <.. repo.RepoObject_gross2
reference.RepoObject_ReferencedList <.. repo.RepoObject_sat2
reference.RepoObject_ReferencedReferencing <.. reference.ftv_RepoObject_ReferenceTree
reference.RepoObject_ReferencedReferencing <.. reference.ftv_RepoObject_ReferenceTree_referenced
reference.RepoObject_ReferencedReferencing <.. reference.ftv_RepoObject_ReferenceTree_referencing
reference.RepoObject_ReferencedReferencing <.. reference.ftv_RepoObject_ReferenceTree_via_fullname
reference.RepoObject_ReferencedReferencing <.. reference.RepoObject_ReferencedList
reference.RepoObject_ReferencedReferencing <.. reference.RepoObject_ReferencingList
reference.RepoObject_ReferencedReferencing <.. reference.usp_RepoObject_ReferenceTree_insert
reference.RepoObject_ReferencedReferencing <.. repo.RepoObject_gross
reference.RepoObject_ReferenceTree_0_30 <.. reference.RepoObject_ReferenceTree_0_30_T
reference.RepoObject_ReferenceTree_0_30 <.. reference.usp_PERSIST_RepoObject_ReferenceTree_0_30_T
reference.RepoObject_ReferenceTree_0_30_T <.. reference.usp_PERSIST_RepoObject_ReferenceTree_0_30_T
reference.RepoObject_ReferenceTree_30_0 <.. reference.RepoObject_ReferenceTree_30_0_T
reference.RepoObject_ReferenceTree_30_0 <.. reference.usp_PERSIST_RepoObject_ReferenceTree_30_0_T
reference.RepoObject_ReferenceTree_30_0_T <.. reference.usp_PERSIST_RepoObject_ReferenceTree_30_0_T
reference.RepoObject_ReferencingList <.. repo.RepoObject_gross2
reference.RepoObject_ReferencingList <.. repo.RepoObject_sat2
reference.RepoObjectColumn_reference <.. reference.RepoObjectColumn_reference_T
reference.RepoObjectColumn_reference <.. reference.usp_PERSIST_RepoObjectColumn_reference_T
reference.RepoObjectColumn_reference_additional <.. reference.RepoObjectColumn_reference_union
reference.RepoObjectColumn_reference_FirstResultSet <.. reference.RepoObjectColumn_reference_BySamePredecessors
reference.RepoObjectColumn_reference_Persistence <.. reference.RepoObjectColumn_reference_union
reference.RepoObjectColumn_reference_QueryPlan <.. reference.SysObjectColumn_QueryPlanExpression
reference.RepoObjectColumn_reference_SqlExpressionDependencies <.. reference.RepoObjectColumn_reference_union
reference.RepoObjectColumn_reference_T <.. docs.RepoObject_Plantuml_ColRefList_1_1
reference.RepoObjectColumn_reference_T <.. reference.RepoObjectColumn_ReferencedReferencing
reference.RepoObjectColumn_reference_T <.. reference.RepoObjectColumn_RelationScript
reference.RepoObjectColumn_reference_T <.. reference.usp_PERSIST_RepoObjectColumn_reference_T
reference.RepoObjectColumn_reference_T <.. repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing
reference.RepoObjectColumn_reference_T <.. repo.RepoObjectColumn_MissingSource_TypeV
reference.RepoObjectColumn_reference_union <.. reference.RepoObjectColumn_reference
reference.RepoObjectColumn_reference_virtual <.. reference.RepoObjectColumn_reference_union
reference.RepoObjectColumn_ReferencedList <.. repo.RepoObjectColumn_gross2
reference.RepoObjectColumn_ReferencedReferencing <.. reference.ftv_RepoObject_DbmlColumnRelation
reference.RepoObjectColumn_ReferencedReferencing <.. reference.ftv_RepoObjectColumn_ReferenceTree
reference.RepoObjectColumn_ReferencedReferencing <.. reference.RepoObjectColumn_ReferencedList
reference.RepoObjectColumn_ReferencedReferencing <.. reference.RepoObjectColumn_ReferencingList
reference.RepoObjectColumn_ReferenceTree <.. reference.ftv_RepoObject_ColumReferenceRepoObject
reference.RepoObjectColumn_ReferencingList <.. repo.RepoObjectColumn_gross2
reference.RepoObjectColumn_RelationScript <.. reference.ftv_RepoObject_ColumReferenceRepoObject
reference.SysObjectColumn_QueryPlanExpression <.. reference.usp_RepoObjectSource_QueryPlan
reference.usp_PERSIST_RepoObject_reference_T <.. repo.usp_main
reference.usp_PERSIST_RepoObject_ReferenceTree_0_30_T <.. reference.usp_RepoObject_ReferenceTree
reference.usp_PERSIST_RepoObject_ReferenceTree_30_0_T <.. reference.usp_RepoObject_ReferenceTree
reference.usp_PERSIST_RepoObjectColumn_reference_T <.. repo.usp_main
reference.usp_RepoObject_ReferenceTree_insert <.. repo.usp_main
reference.usp_RepoObject_update_SysObjectQueryPlan <.. repo.usp_main
reference.usp_RepoObjectSource_FirstResultSet <.. repo.usp_main
reference.usp_RepoObjectSource_QueryPlan <.. repo.usp_main
repo.ForeignKey_gross <.. docs.RepoObject_IndexList
repo.ForeignKey_Indexes <.. repo.ForeignKey_Indexes_union
repo.ForeignKey_Indexes <.. repo.usp_Index_ForeignKey
repo.ForeignKey_Indexes_union <.. repo.ForeignKey_Indexes_union_T
repo.ForeignKey_Indexes_union <.. repo.usp_PERSIST_ForeignKey_Indexes_union_T
repo.ForeignKey_Indexes_union_T <.. docs.ForeignKey_RelationScript
repo.ForeignKey_Indexes_union_T <.. docs.RepoObject_PlantUml_FkRefList
repo.ForeignKey_Indexes_union_T <.. docs.Schema_PumlPartial_FkRefList
repo.ForeignKey_Indexes_union_T <.. repo.ForeignKey_gross
repo.ForeignKey_Indexes_union_T <.. repo.RepoObject_related_FK_union
repo.ForeignKey_Indexes_union_T <.. repo.usp_Index_finish
repo.ForeignKey_Indexes_union_T <.. repo.usp_PERSIST_ForeignKey_Indexes_union_T
repo.ForeignKey_virtual_Indexes <.. repo.ForeignKey_Indexes_union
repo.Index_gross <.. docs.IndexSemanticgroupPatterndatatype
repo.Index_gross <.. docs.RepoObject_IndexList
repo.Index_gross <.. repo.ForeignKey_gross
repo.Index_gross <.. repo.ForeignKey_Indexes
repo.Index_gross <.. repo.ForeignKey_virtual_Indexes
repo.Index_gross <.. repo.RepoObject_SqlCreateTable
repo.Index_gross <.. repo.usp_Index_finish
repo.Index_gross <.. repo.usp_index_inheritance
repo.Index_gross <.. repo.usp_Index_virtual_set
repo.Index_referencing_IndexPatternColumnGuid <.. repo.IndexReferencedReferencing_HasFullColumnsInReferencing
repo.Index_virtual_ForUpdate <.. repo.usp_index_inheritance
repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing <.. repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T
repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing <.. repo.usp_PERSIST_IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T
repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T <.. repo.Index_referencing_IndexPatternColumnGuid
repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T <.. repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_check
repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T <.. repo.IndexColumn_virtual_referenced_setpoint
repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T <.. repo.IndexReferencedReferencing_HasFullColumnsInReferencing
repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T <.. repo.usp_PERSIST_IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T
repo.IndexColumn_virtual_referenced_setpoint <.. repo.check_IndexColumn_virtual_referenced_setpoint
repo.IndexColumn_virtual_referenced_setpoint <.. repo.usp_index_inheritance
repo.IndexReferencedReferencing <.. repo.IndexReferencedReferencing_HasFullColumnsInReferencing
repo.IndexReferencedReferencing_HasFullColumnsInReferencing <.. repo.usp_index_inheritance
repo.RepoObject_ColumnList <.. repo.RepoObject_gross2
repo.RepoObject_ColumnList <.. repo.RepoObject_sat2
repo.RepoObject_ColumnList <.. repo.RepoObject_SqlCreateTable
repo.RepoObject_gross <.. docs.RepoObject_Adoc
repo.RepoObject_gross <.. docs.RepoObject_OutputFilter
repo.RepoObject_gross <.. docs.RepoObject_Plantuml
repo.RepoObject_gross <.. docs.Unit_1_union
repo.RepoObject_gross <.. property.RepoObjectProperty_Collect_source_ROGross
repo.RepoObject_gross <.. reference.Persistence
repo.RepoObject_gross <.. reference.RepoObject_ReferenceTree_0_30
repo.RepoObject_gross <.. reference.RepoObject_ReferenceTree_30_0
repo.RepoObject_gross <.. reference.RepoObject_ReferenceTree_referenced
repo.RepoObject_gross <.. reference.RepoObject_ReferenceTree_referenced_30_0
repo.RepoObject_gross <.. reference.RepoObject_ReferenceTree_referencing
repo.RepoObject_gross <.. reference.RepoObject_ReferenceTree_referencing_0_30
repo.RepoObject_gross <.. reference.usp_RepoObject_update_SysObjectQueryPlan
repo.RepoObject_gross <.. reference.usp_RepoObjectSource_FirstResultSet
repo.RepoObject_gross <.. reference.usp_RepoObjectSource_QueryPlan
repo.RepoObject_gross <.. repo.Index_gross
repo.RepoObject_gross <.. repo.Index_virtual_ForUpdate
repo.RepoObject_gross <.. repo.RepoObject_gross2
repo.RepoObject_gross <.. repo.RepoObject_sat2
repo.RepoObject_gross <.. repo.RepoObject_SqlCreateTable
repo.RepoObject_gross <.. uspgenerator.GeneratorUsp_SqlViewPersistenceUpdateCheck
repo.RepoObject_gross <.. uspgenerator.GeneratorUspStep_Persistence_IsInactive_setpoint
repo.RepoObject_gross <.. uspgenerator.GeneratorUspStep_Persistence_src
repo.RepoObject_gross <.. uspgenerator.usp_GeneratorUsp_insert_update_persistence
repo.RepoObject_gross <.. workflow.WorkflowStep_src
repo.RepoObject_gross_persistence <.. reference.RepoObject_reference_persistence_target_as_source
repo.RepoObject_gross2 <.. uspgenerator.GeneratorUsp_SqlViewPersistenceUpdateCheck
repo.RepoObject_gross2 <.. uspgenerator.GeneratorUspStep_Persistence_src
repo.RepoObject_persistence <.. reference.RepoObject_reference_persistence
repo.RepoObject_persistence <.. reference.RepoObject_reference_persistence_target_as_source_explicit
repo.RepoObject_persistence <.. reference.RepoObject_reference_T_bidirectional
repo.RepoObject_persistence <.. reference.RepoObjectColumn_reference_Persistence
repo.RepoObject_persistence <.. repo.RepoObject__after_delete
repo.RepoObject_persistence <.. repo.RepoObject_ColumnList
repo.RepoObject_persistence <.. repo.RepoObject_gross
repo.RepoObject_persistence <.. repo.RepoObject_gross_persistence
repo.RepoObject_persistence <.. repo.RepoObject_persistence_column
repo.RepoObject_persistence <.. repo.RepoObject_persistence_ForUpdate
repo.RepoObject_persistence <.. repo.RepoObject_persistence_NoCompareButUpdate
repo.RepoObject_persistence <.. repo.RepoObject_persistence_NoCompareNoUpdate
repo.RepoObject_persistence <.. repo.RepoObject_persistence_NoInsert
repo.RepoObject_persistence <.. repo.RepoObject_persistence_ObjectNames
repo.RepoObject_persistence <.. repo.RepoObject_persistence_source_Ignore
repo.RepoObject_persistence <.. repo.RepoObject_persistence_target_Ignore
repo.RepoObject_persistence <.. repo.RepoObjectColumn_gross
repo.RepoObject_persistence <.. repo.RepoObjectColumn_HistValidColums_setpoint
repo.RepoObject_persistence <.. repo.usp_Index_finish
repo.RepoObject_persistence <.. repo.usp_main
repo.RepoObject_persistence <.. repo.usp_persistence_delete
repo.RepoObject_persistence <.. repo.usp_persistence_set
repo.RepoObject_persistence <.. repo.usp_sync_guid_RepoObject
repo.RepoObject_persistence <.. repo.usp_sync_guid_RepoObjectColumn
repo.RepoObject_persistence <.. uspgenerator.GeneratorUsp_check_persistence
repo.RepoObject_persistence_ForUpdate <.. repo.RepoObject_persistence_SourceMismatch
repo.RepoObject_persistence_NoCompareButUpdate <.. repo.usp_sync_guid_RepoObjectColumn
repo.RepoObject_persistence_NoCompareNoUpdate <.. repo.usp_sync_guid_RepoObjectColumn
repo.RepoObject_persistence_NoInsert <.. repo.usp_sync_guid_RepoObjectColumn
repo.RepoObject_persistence_source_Ignore <.. repo.usp_sync_guid_RepoObjectColumn
repo.RepoObject_persistence_target_Ignore <.. repo.usp_sync_guid_RepoObjectColumn
repo.RepoObject_related_FK_union <.. docs.RepoObject_PlantUml_FkRefList
repo.RepoObject_related_FK_union <.. docs.RepoObject_PlantUml_PumlEntityFkList
repo.RepoObject_sat2 <.. repo.RepoObject_sat2_T
repo.RepoObject_sat2 <.. repo.usp_PERSIST_RepoObject_sat2_T
repo.RepoObject_sat2_T <.. docs.RepoObject_Adoc
repo.RepoObject_sat2_T <.. property.RepoObjectProperty_Collect_source_ROGross
repo.RepoObject_sat2_T <.. repo.usp_PERSIST_RepoObject_sat2_T
repo.RepoObject_SqlCreateTable <.. reference.ftv_RepoObject_ColumReferenceRepoObject
repo.RepoObjectColumn_gross <.. docs.Unit_1_union
repo.RepoObjectColumn_gross <.. graph.RepoObjectColumn_S
repo.RepoObjectColumn_gross <.. property.RepoObjectColumnProperty_ForUpdate
repo.RepoObjectColumn_gross <.. reference.RepoObjectColumn_reference_FirstResultSet
repo.RepoObjectColumn_gross <.. reference.RepoObjectColumn_reference_QueryPlan
repo.RepoObjectColumn_gross <.. reference.RepoObjectColumn_reference_virtual
repo.RepoObjectColumn_gross <.. reference.usp_RepoObjectColumnSource_virtual_set
repo.RepoObjectColumn_gross <.. repo.RepoObjectColumn_gross2
repo.RepoObjectColumn_gross <.. repo.usp_sync_guid_RepoObjectColumn
repo.RepoObjectColumn_gross <.. ssas.RepoObjectColumn_translation
repo.RepoObjectColumn_gross2 <.. docs.RepoObject_ColumnList
repo.RepoObjectColumn_gross2 <.. repo.RepoObject_ColumnList
repo.RepoObjectColumn_gross2 <.. uspgenerator.usp_GeneratorUsp_insert_update_persistence
repo.RepoObjectColumn_HistValidColums_setpoint <.. repo.usp_sync_guid_RepoObjectColumn
repo.usp_Index_finish <.. repo.usp_Index_ForeignKey
repo.usp_Index_finish <.. repo.usp_index_inheritance
repo.usp_Index_ForeignKey <.. repo.usp_main
repo.usp_index_inheritance <.. repo.usp_main
repo.usp_Index_virtual_set <.. repo.usp_Index_ForeignKey
repo.usp_PERSIST_ForeignKey_Indexes_union_T <.. repo.usp_Index_ForeignKey
repo.usp_PERSIST_IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T <.. repo.usp_index_inheritance
repo.usp_PERSIST_RepoObject_sat2_T <.. repo.usp_main
repo.usp_sync_guid <.. repo.usp_main
repo.usp_sync_guid <.. repo.usp_persistence_set
repo.usp_sync_guid_RepoObject <.. repo.usp_sync_guid
repo.usp_sync_guid_RepoObjectColumn <.. repo.usp_sync_guid
ssas.RepoObjectColumn_translation <.. ssas.RepoObjectColumn_translation_T
ssas.RepoObjectColumn_translation <.. ssas.usp_PERSIST_RepoObjectColumn_translation_T
ssas.RepoObjectColumn_translation_displayfolder_union <.. docs.RepoObject_ColumnList
ssas.RepoObjectColumn_translation_T <.. docs.RepoObject_Plantuml_ColRefList_1_1
ssas.RepoObjectColumn_translation_T <.. ssas.RepoObjectColumn_translation_displayfolder_union
ssas.RepoObjectColumn_translation_T <.. ssas.usp_PERSIST_RepoObjectColumn_translation_T
ssas.usp_PERSIST_RepoObjectColumn_translation_T <.. repo.usp_main
uspgenerator.GeneratorUsp_SqlUsp <.. property.RepoObjectProperty_Collect_source_uspgenerator
uspgenerator.GeneratorUsp_SqlViewPersistenceUpdateCheck <.. uspgenerator.GeneratorUsp_SqlUsp
uspgenerator.GeneratorUspStep_Persistence_IsInactive_setpoint <.. uspgenerator.usp_GeneratorUsp_insert_update_persistence
uspgenerator.GeneratorUspStep_Persistence_src <.. uspgenerator.usp_GeneratorUsp_insert_update_persistence
uspgenerator.usp_GeneratorUsp_insert_update_persistence <.. repo.usp_main
workflow.Biml_Package <.. workflow.Biml_Project
workflow.Biml_PrecedenceConstraints <.. workflow.Biml_Task
workflow.Biml_Task <.. workflow.Biml_Package
workflow.ProcedureDependency <.. workflow.ProcedureDependency_gross
workflow.ProcedureDependency <.. workflow.ProcedureDependency_input_PersistenceDependency
workflow.ProcedureDependency <.. workflow.Workflow_ProcedureDependency
workflow.ProcedureDependency <.. workflow.Workflow_ProcedureDependency_all
workflow.ProcedureDependency_PersistenceDependency_src <.. workflow.ProcedureDependency_PersistenceDependency_tgt
workflow.ProcedureDependency_PersistenceDependency_src <.. workflow.usp_PERSIST_ProcedureDependency_PersistenceDependency_tgt
workflow.ProcedureDependency_PersistenceDependency_tgt <.. workflow.ProcedureDependency
workflow.ProcedureDependency_PersistenceDependency_tgt <.. workflow.usp_PERSIST_ProcedureDependency_PersistenceDependency_tgt
workflow.usp_PERSIST_ProcedureDependency_PersistenceDependency_tgt <.. workflow.usp_workflow
workflow.usp_PERSIST_Workflow_ProcedureDependency_T <.. workflow.usp_workflow
workflow.usp_PERSIST_WorkflowStep <.. workflow.usp_workflow
workflow.Workflow_ProcedureDependency <.. workflow.usp_PERSIST_Workflow_ProcedureDependency_T
workflow.Workflow_ProcedureDependency <.. workflow.Workflow_ProcedureDependency_T
workflow.Workflow_ProcedureDependency_all <.. workflow.Workflow_ProcedureDependency_wo_redundant
workflow.Workflow_ProcedureDependency_T <.. workflow.usp_PERSIST_Workflow_ProcedureDependency_T
workflow.Workflow_ProcedureDependency_T <.. workflow.usp_workflow
workflow.Workflow_ProcedureDependency_T <.. workflow.Workflow_ProcedureDependency_T_active
workflow.Workflow_ProcedureDependency_T <.. workflow.Workflow_ProcedureDependency_T_bidirectional
workflow.Workflow_ProcedureDependency_T_active <.. workflow.Workflow_ProcedureDependency_T_NotInSortorder
workflow.Workflow_ProcedureDependency_T_active <.. workflow.Workflow_ProcedureDependency_T_redundant
workflow.Workflow_ProcedureDependency_T_active <.. workflow.Workflow_ProcedureDependency_T_TaskName
workflow.Workflow_ProcedureDependency_T_bidirectional <.. workflow.usp_workflow
workflow.Workflow_ProcedureDependency_T_bidirectional <.. workflow.Workflow_ProcedureDependency_T_bidirectional_T
workflow.Workflow_ProcedureDependency_T_NotInSortorder <.. workflow.usp_workflow
workflow.Workflow_ProcedureDependency_T_NotInSortorder <.. workflow.Workflow_ProcedureDependency_T_NotInSortorder_check
workflow.Workflow_ProcedureDependency_T_NotInSortorder_check <.. workflow.usp_workflow
workflow.Workflow_ProcedureDependency_T_redundant <.. workflow.usp_workflow
workflow.Workflow_ProcedureDependency_T_redundant <.. workflow.Workflow_ProcedureDependency_wo_redundant
workflow.Workflow_ProcedureDependency_T_TaskName <.. workflow.Biml_PrecedenceConstraints
workflow.WorkflowStep <.. workflow.usp_PERSIST_WorkflowStep
workflow.WorkflowStep <.. workflow.WorkflowStep_active
workflow.WorkflowStep <.. workflow.WorkflowStep_ForUpdate
workflow.WorkflowStep_active <.. workflow.Biml_Task
workflow.WorkflowStep_active <.. workflow.usp_workflow
workflow.WorkflowStep_active <.. workflow.Workflow_ProcedureDependency
workflow.WorkflowStep_active <.. workflow.Workflow_ProcedureDependency_all
workflow.WorkflowStep_active <.. workflow.Workflow_ProcedureDependency_T_active
workflow.WorkflowStep_src <.. workflow.usp_PERSIST_WorkflowStep
workflow.WorkflowStep_src <.. workflow.WorkflowStep

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_0_30_objectref[]

=== PlantUML 1 1 ColumnRef

// tag::puml_entity_1_1_colref[]
[plantuml, entity_1_1_colref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:reference.repoobject_reference_persistence.adoc[]" as reference.RepoObject_reference_persistence << V >> {
  **referenced_RepoObject_guid** : (uniqueidentifier)
  - **referencing_RepoObject_guid** : (uniqueidentifier)
  - InformationSource : (varchar(27))
  - referenced_entity_name : (nvarchar(128))
  - referenced_fullname : (nvarchar(261))
  referenced_id : (int)
  - referenced_schema_name : (nvarchar(128))
  referenced_type : (char(2))
  - referencing_entity_name : (nvarchar(128))
  - referencing_fullname : (nvarchar(261))
  referencing_id : (int)
  - referencing_schema_name : (nvarchar(128))
  referencing_type : (varchar(2))
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_reference_persistence_target_as_source_explicit.adoc[]" as reference.RepoObject_reference_persistence_target_as_source_explicit << V >> {
  - InformationSource : (varchar(37))
  referenced_entity_name : (nvarchar(128))
  referenced_fullname : (nvarchar(517))
  - referenced_id : (int)
  referenced_RepoObject_guid : (uniqueidentifier)
  referenced_schema_name : (nvarchar(128))
  referenced_type : (char(2))
  referencing_entity_name : (nvarchar(128))
  referencing_fullname : (nvarchar(517))
  referencing_id : (int)
  referencing_RepoObject_guid : (uniqueidentifier)
  referencing_schema_name : (nvarchar(128))
  referencing_type : (char(2))
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_reference_t_bidirectional.adoc[]" as reference.RepoObject_reference_T_bidirectional << V >> {
  referenced_entity_name : (nvarchar(128))
  - referenced_fullname : (nvarchar(261))
  - referenced_fullname2 : (nvarchar(257))
  referenced_is_persistence : (bit)
  - referenced_RepoObject_guid : (uniqueidentifier)
  referenced_schema_name : (nvarchar(128))
  referenced_source_RepoObject_guid : (uniqueidentifier)
  referenced_type : (char(2))
  referencing_entity_name : (nvarchar(128))
  - referencing_fullname : (nvarchar(261))
  - referencing_fullname2 : (nvarchar(257))
  referencing_is_persistence : (bit)
  - referencing_RepoObject_guid : (uniqueidentifier)
  referencing_schema_name : (nvarchar(128))
  referencing_source_RepoObject_guid : (uniqueidentifier)
  referencing_type : (varchar(2))
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_reference_persistence.adoc[]" as reference.RepoObjectColumn_reference_Persistence << V >> {
  **referencing_id** : (int)
  **referencing_minor_id** : (int)
  **referenced_id** : (int)
  **referenced_minor_id** : (int)
  definition : (nvarchar(max))
  - InformationSource : (varchar(27))
  is_computed : (bit)
  is_referenced_object : (bit)
  is_referencing_object_equal_referenced_object : (bit)
  - referenced_column_name : (nvarchar(128))
  - referenced_entity_name : (nvarchar(128))
  referenced_node_id : (bigint)
  referenced_RepoObject_guid : (uniqueidentifier)
  - referenced_RepoObjectColumn_guid : (uniqueidentifier)
  - referenced_schema_name : (nvarchar(128))
  referenced_type : (char(2))
  - referencing_column_name : (nvarchar(128))
  - referencing_entity_name : (nvarchar(128))
  referencing_node_id : (bigint)
  - referencing_RepoObject_guid : (uniqueidentifier)
  - referencing_RepoObjectColumn_guid : (uniqueidentifier)
  - referencing_schema_name : (nvarchar(128))
  referencing_type : (char(2))
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject__after_delete.adoc[]" as repo.RepoObject__after_delete << TR >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_columnlist.adoc[]" as repo.RepoObject_ColumnList << V >> {
  - CreateColumnList : (nvarchar(max))
  - DbmlColumnList : (nvarchar(max))
  PersistenceCompareColumnList : (nvarchar(max))
  - PersistenceInsertColumnList : (nvarchar(max))
  - PersistenceInsertColumnListSource : (nvarchar(max))
  - PersistenceSrcTgtColumnList : (nvarchar(max))
  - PersistenceTempTableColumnList : (nvarchar(max))
  - PersistenceUpdateColumnList : (nvarchar(max))
  RepoObject_fullname : (nvarchar(261))
  - RepoObject_guid : (uniqueidentifier)
  - TemporalTableColumnList : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_gross.adoc[]" as repo.RepoObject_gross << V >> {
  AntoraComponent : (nvarchar(max))
  AntoraModule : (nvarchar(max))
  Description : (nvarchar(max))
  ExecutionLogId_action : (char(1))
  external_AntoraComponent : (nvarchar(128))
  external_AntoraModule : (nvarchar(128))
  external_DatabaseName : (nvarchar(128))
  external_RepoDatabaseName : (nvarchar(128))
  has_different_sys_names : (bit)
  has_execution_plan_issue : (bit)
  has_get_referenced_issue : (bit)
  has_history : (bit)
  has_history_columns : (bit)
  history_schema_name : (nvarchar(128))
  history_table_name : (nvarchar(128))
  indent_sql_modules_definition : (tinyint)
  Inheritance_StringAggSeparatorSql : (nvarchar(4000))
  InheritanceDefinition : (nvarchar(4000))
  InheritanceType : (tinyint)
  - is_DocsExclude : (bit)
  is_DocsOutput : (int)
  - is_external : (bit)
  - is_in_reference : (int)
  is_persistence : (bit)
  is_persistence_check_duplicate_per_pk : (bit)
  is_persistence_check_for_empty_source : (bit)
  is_persistence_delete_changed : (bit)
  is_persistence_delete_missing : (bit)
  is_persistence_insert : (bit)
  is_persistence_persist_source : (bit)
  is_persistence_truncate : (bit)
  is_persistence_update_changed : (bit)
  is_repo_managed : (bit)
  - is_RepoObject_name_uniqueidentifier : (int)
  is_required_ObjectMerge : (bit)
  - is_ssas : (bit)
  is_SysObject_missing : (bit)
  - is_SysObject_name_uniqueidentifier : (int)
  - modify_dt : (datetime)
  node_id : (bigint)
  persistence_source_RepoObject_fullname : (nvarchar(261))
  persistence_source_RepoObject_fullname2 : (nvarchar(257))
  persistence_source_RepoObject_guid : (uniqueidentifier)
  persistence_source_RepoObject_xref : (nvarchar(4000))
  persistence_source_SysObject_fullname : (nvarchar(261))
  persistence_source_SysObject_fullname_or_tempsource : (nvarchar(261))
  persistence_source_SysObject_fullname2 : (nvarchar(257))
  persistence_source_SysObject_xref : (nvarchar(4000))
  pk_index_guid : (uniqueidentifier)
  pk_IndexPatternColumnDatatype : (nvarchar(4000))
  pk_IndexPatternColumnName : (nvarchar(4000))
  pk_IndexPatternColumnName_new : (nvarchar(4000))
  pk_IndexSemanticGroup : (nvarchar(512))
  postscript : (nvarchar(max))
  prescript : (nvarchar(max))
  Property_ms_description : (nvarchar(4000))
  Repo_history_table_guid : (uniqueidentifier)
  Repo_temporal_type : (tinyint)
  - RepoObject_fullname : (nvarchar(261))
  - RepoObject_fullname2 : (nvarchar(257))
  - RepoObject_guid : (uniqueidentifier)
  - RepoObject_name : (nvarchar(128))
  RepoObject_Referencing_Count : (int)
  - RepoObject_schema_name : (nvarchar(128))
  - RepoObject_type : (char(2))
  RepoObject_type_name : (nvarchar(128))
  - SysObject_fullname : (nvarchar(261))
  - SysObject_fullname2 : (nvarchar(257))
  SysObject_id : (int)
  SysObject_modify_date : (datetime)
  - SysObject_name : (nvarchar(128))
  - SysObject_parent_object_id : (int)
  SysObject_query_executed_dt : (datetime)
  SysObject_query_plan : (xml)
  - SysObject_query_sql : (nvarchar(406))
  - SysObject_schema_name : (nvarchar(128))
  SysObject_type : (char(2))
  SysObject_type_name : (nvarchar(128))
  tables_dataCategory : (nvarchar(500))
  tables_description : (nvarchar(max))
  tables_isHidden : (bit)
  temporal_type : (tinyint)
  - usp_persistence_name : (nvarchar(140))
  usp_persistence_RepoObject_guid : (uniqueidentifier)
  uspgenerator_usp_id : (int)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_gross_persistence.adoc[]" as repo.RepoObject_gross_persistence << V >> {
  ExecutionLogId_action : (char(1))
  external_AntoraComponent : (nvarchar(128))
  external_AntoraModule : (nvarchar(128))
  has_different_sys_names : (bit)
  has_execution_plan_issue : (bit)
  has_get_referenced_issue : (bit)
  has_history : (bit)
  has_history_columns : (bit)
  history_schema_name : (nvarchar(128))
  history_table_name : (nvarchar(128))
  Inheritance_StringAggSeparatorSql : (nvarchar(4000))
  InheritanceDefinition : (nvarchar(4000))
  InheritanceType : (tinyint)
  - is_DocsExclude : (bit)
  is_DocsOutput : (int)
  - is_external : (bit)
  is_persistence : (bit)
  is_persistence_check_duplicate_per_pk : (bit)
  is_persistence_check_for_empty_source : (bit)
  is_persistence_delete_changed : (bit)
  is_persistence_delete_missing : (bit)
  is_persistence_insert : (bit)
  is_persistence_persist_source : (bit)
  is_persistence_truncate : (bit)
  is_persistence_update_changed : (bit)
  is_repo_managed : (bit)
  - is_RepoObject_name_uniqueidentifier : (int)
  is_required_ObjectMerge : (bit)
  - is_ssas : (bit)
  is_SysObject_missing : (bit)
  - is_SysObject_name_uniqueidentifier : (int)
  - modify_dt : (datetime)
  node_id : (bigint)
  persistence_source_RepoObject_fullname : (nvarchar(261))
  persistence_source_RepoObject_fullname2 : (nvarchar(257))
  persistence_source_RepoObject_guid : (uniqueidentifier)
  persistence_source_RepoObject_xref : (nvarchar(4000))
  persistence_source_SysObject_fullname : (nvarchar(261))
  persistence_source_SysObject_fullname_or_tempsource : (nvarchar(261))
  persistence_source_SysObject_fullname2 : (nvarchar(257))
  persistence_source_SysObject_xref : (nvarchar(4000))
  pk_index_guid : (uniqueidentifier)
  postscript : (nvarchar(max))
  prescript : (nvarchar(max))
  Repo_history_table_guid : (uniqueidentifier)
  Repo_temporal_type : (tinyint)
  - RepoObject_fullname : (nvarchar(261))
  - RepoObject_fullname2 : (nvarchar(257))
  - RepoObject_guid : (uniqueidentifier)
  - RepoObject_name : (nvarchar(128))
  RepoObject_Referencing_Count : (int)
  - RepoObject_schema_name : (nvarchar(128))
  - RepoObject_type : (char(2))
  RepoObject_type_name : (nvarchar(128))
  - SysObject_fullname : (nvarchar(261))
  - SysObject_fullname2 : (nvarchar(257))
  SysObject_id : (int)
  SysObject_modify_date : (datetime)
  - SysObject_name : (nvarchar(128))
  - SysObject_parent_object_id : (int)
  - SysObject_query_sql : (nvarchar(406))
  - SysObject_schema_name : (nvarchar(128))
  SysObject_type : (char(2))
  SysObject_type_name : (nvarchar(128))
  temporal_type : (tinyint)
  - usp_persistence_name : (nvarchar(140))
  usp_persistence_RepoObject_guid : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_persistence.adoc[]" as repo.RepoObject_persistence << U >> {
  - **target_RepoObject_guid** : (uniqueidentifier)
  ColumnListIgnore : (nvarchar(4000))
  ColumnListNoCompareButUpdate : (nvarchar(4000))
  ColumnListNoCompareNoUpdate : (nvarchar(4000))
  ColumnListNoInsert : (nvarchar(4000))
  ExecutionLogId_action : (char(1))
  final_target_RepoObject_name : (nvarchar(128))
  - has_history : (bit)
  - has_history_columns : (bit)
  history_schema_name : (nvarchar(128))
  history_table_name : (nvarchar(128))
  - is_persistence_check_duplicate_per_pk : (bit)
  - is_persistence_check_for_empty_source : (bit)
  - is_persistence_delete_changed : (bit)
  - is_persistence_delete_missing : (bit)
  - is_persistence_insert : (bit)
  - is_persistence_persist_source : (bit)
  - is_persistence_truncate : (bit)
  - is_persistence_update_changed : (bit)
  postscript : (nvarchar(max))
  prescript : (nvarchar(max))
  source_RepoObject_guid : (uniqueidentifier)
  source_RepoObject_name : (nvarchar(128))
  ~ is_persistence : (bit)
  ~ temporal_type : (tinyint)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_persistence_column.adoc[]" as repo.RepoObject_persistence_column << V >> {
  - **target_RepoObject_guid** : (uniqueidentifier)
  **RepoObjectColumn_guid_s** : (uniqueidentifier)
  - has_history : (bit)
  - has_history_columns : (bit)
  history_schema_name : (nvarchar(128))
  history_table_name : (nvarchar(128))
  is_persistence : (bit)
  - is_persistence_check_for_empty_source : (bit)
  - is_persistence_delete_changed : (bit)
  - is_persistence_delete_missing : (bit)
  - is_persistence_insert : (bit)
  - is_persistence_truncate : (bit)
  - is_persistence_update_changed : (bit)
  is_repo_managed_t : (bit)
  - RepoObject_name_t : (nvarchar(128))
  - RepoObject_schema_name_t : (nvarchar(128))
  - RepoObject_type_t : (char(2))
  RepoObjectColumn_name_t : (nvarchar(128))
  source_RepoObject_guid : (uniqueidentifier)
  SysObject_name_s : (nvarchar(128))
  SysObject_schema_name_s : (nvarchar(128))
  SysObject_type_s : (char(2))
  SysObjectColumn_name_s : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_persistence_forupdate.adoc[]" as repo.RepoObject_persistence_ForUpdate << V >> {
  ColumnListIgnore : (nvarchar(4000))
  ColumnListNoCompareButUpdate : (nvarchar(4000))
  ColumnListNoCompareNoUpdate : (nvarchar(4000))
  ColumnListNoInsert : (nvarchar(4000))
  default_source_RepoObject_name : (nvarchar(128))
  - has_history : (bit)
  - has_history_columns : (bit)
  history_schema_name : (nvarchar(128))
  history_table_name : (nvarchar(128))
  - is_persistence_check_duplicate_per_pk : (bit)
  - is_persistence_check_for_empty_source : (bit)
  - is_persistence_delete_changed : (bit)
  - is_persistence_delete_missing : (bit)
  - is_persistence_insert : (bit)
  - is_persistence_persist_source : (bit)
  - is_persistence_truncate : (bit)
  - is_persistence_update_changed : (bit)
  postscript : (nvarchar(max))
  prescript : (nvarchar(max))
  source_RepoObject_guid : (uniqueidentifier)
  source_RepoObject_name : (nvarchar(128))
  - target_name : (nvarchar(128))
  - target_RepoObject_fullname : (nvarchar(261))
  - target_RepoObject_fullname2 : (nvarchar(257))
  - target_RepoObject_guid : (uniqueidentifier)
  - target_schema : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_persistence_nocomparebutupdate.adoc[]" as repo.RepoObject_persistence_NoCompareButUpdate << V >> {
  ColumnListNoCompareButUpdate : (nvarchar(4000))
  - is_persistence_NoCompareButUpdate : (int)
  NoCompareButUpdate_Column : (nvarchar(4000))
  RepoObject_guid : (uniqueidentifier)
  RepoObjectColumn_guid : (uniqueidentifier)
  source_RepoObject_guid : (uniqueidentifier)
  source_RepoObject_name : (nvarchar(128))
  - target_RepoObject_guid : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_persistence_nocomparenoupdate.adoc[]" as repo.RepoObject_persistence_NoCompareNoUpdate << V >> {
  ColumnListNoCompareNoUpdate : (nvarchar(4000))
  - is_persistence_NoCompareNoUpdate : (int)
  NoCompareNoUpdate_Column : (nvarchar(4000))
  RepoObject_guid : (uniqueidentifier)
  RepoObjectColumn_guid : (uniqueidentifier)
  source_RepoObject_guid : (uniqueidentifier)
  source_RepoObject_name : (nvarchar(128))
  - target_RepoObject_guid : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_persistence_noinsert.adoc[]" as repo.RepoObject_persistence_NoInsert << V >> {
  ColumnListNoInsert : (nvarchar(4000))
  - is_persistence_NoInsert : (int)
  NoInsert_Column : (nvarchar(4000))
  RepoObject_guid : (uniqueidentifier)
  RepoObjectColumn_guid : (uniqueidentifier)
  source_RepoObject_guid : (uniqueidentifier)
  source_RepoObject_name : (nvarchar(128))
  - target_RepoObject_guid : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_persistence_objectnames.adoc[]" as repo.RepoObject_persistence_ObjectNames << V >> {
  - has_history : (bit)
  - has_history_columns : (bit)
  history_schema_name : (nvarchar(128))
  history_table_name : (nvarchar(128))
  is_persistence : (bit)
  - is_persistence_check_for_empty_source : (bit)
  - is_persistence_delete_changed : (bit)
  - is_persistence_delete_missing : (bit)
  - is_persistence_insert : (bit)
  - is_persistence_truncate : (bit)
  - is_persistence_update_changed : (bit)
  is_repo_managed_t : (bit)
  - RepoObject_name_t : (nvarchar(128))
  - RepoObject_schema_name_t : (nvarchar(128))
  - RepoObject_type_t : (char(2))
  source_RepoObject_guid : (uniqueidentifier)
  SysObject_name_s : (nvarchar(128))
  SysObject_schema_name_s : (nvarchar(128))
  SysObject_type_s : (char(2))
  - target_RepoObject_guid : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_persistence_source_ignore.adoc[]" as repo.RepoObject_persistence_source_Ignore << V >> {
  ColumnListIgnore : (nvarchar(4000))
  - is_persistence_Ignore : (int)
  NoCompareButUpdate_Column : (nvarchar(4000))
  RepoObject_guid : (uniqueidentifier)
  RepoObjectColumn_guid : (uniqueidentifier)
  source_RepoObject_guid : (uniqueidentifier)
  source_RepoObject_name : (nvarchar(128))
  - target_RepoObject_guid : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_persistence_target_ignore.adoc[]" as repo.RepoObject_persistence_target_Ignore << V >> {
  ColumnListIgnore : (nvarchar(4000))
  - is_persistence_Ignore : (int)
  NoCompareButUpdate_Column : (nvarchar(4000))
  RepoObject_guid : (uniqueidentifier)
  RepoObjectColumn_guid : (uniqueidentifier)
  source_RepoObject_guid : (uniqueidentifier)
  source_RepoObject_name : (nvarchar(128))
  - target_RepoObject_guid : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn_gross.adoc[]" as repo.RepoObjectColumn_gross << V >> {
  - Column_name : (nvarchar(128))
  Description : (nvarchar(max))
  has_different_sys_names : (bit)
  has_get_referenced_issue : (bit)
  Inheritance_StringAggSeparatorSql : (nvarchar(4000))
  InheritanceDefinition : (nvarchar(4000))
  InheritanceType : (tinyint)
  - is_external : (bit)
  is_persistence_Ignore : (bit)
  is_persistence_NoCompareButUpdate : (bit)
  is_persistence_NoCompareNoUpdate : (bit)
  is_persistence_NoInsert : (bit)
  is_query_plan_expression : (bit)
  is_repo_managed : (bit)
  - is_RepoObject_name_uniqueidentifier : (int)
  - is_RepoObjectColumn_name_uniqueidentifier : (int)
  is_required_ColumnMerge : (bit)
  - is_ssas : (bit)
  is_SysObject_missing : (bit)
  - is_SysObject_name_uniqueidentifier : (int)
  is_SysObjectColumn_missing : (bit)
  - is_SysObjectColumn_name_uniqueidentifier : (int)
  - modify_dt : (datetime)
  node_id : (bigint)
  persistence_source_RepoObject_guid : (uniqueidentifier)
  persistence_source_RepoObjectColumn_guid : (uniqueidentifier)
  pk_index_guid : (uniqueidentifier)
  Property_ms_description : (nvarchar(4000))
  Referencing_Count : (int)
  Repo_default_definition : (nvarchar(max))
  Repo_default_is_system_named : (bit)
  Repo_default_name : (nvarchar(128))
  Repo_definition : (nvarchar(max))
  - Repo_generated_always_type : (tinyint)
  Repo_graph_type : (int)
  Repo_increment_value : (sql_variant)
  - Repo_is_computed : (bit)
  - Repo_is_identity : (bit)
  Repo_is_nullable : (bit)
  Repo_is_persisted : (bit)
  Repo_seed_value : (sql_variant)
  Repo_user_type_fullname : (nvarchar(128))
  Repo_user_type_name : (nvarchar(128))
  Repo_uses_database_collation : (bit)
  - RepoObject_fullname : (nvarchar(261))
  - RepoObject_fullname2 : (nvarchar(257))
  - RepoObject_guid : (uniqueidentifier)
  - RepoObject_name : (nvarchar(128))
  RepoObject_Referencing_Count : (int)
  - RepoObject_schema_name : (nvarchar(128))
  - RepoObject_type : (char(2))
  RepoObjectColumn_column_id : (int)
  - RepoObjectColumn_fullname : (nvarchar(520))
  - RepoObjectColumn_fullname2 : (nvarchar(386))
  - RepoObjectColumn_guid : (uniqueidentifier)
  - RepoObjectColumn_name : (nvarchar(128))
  - SysObject_fullname : (nvarchar(261))
  - SysObject_fullname2 : (nvarchar(257))
  SysObject_id : (int)
  SysObject_modify_date : (datetime)
  - SysObject_name : (nvarchar(128))
  - SysObject_parent_object_id : (int)
  - SysObject_schema_name : (nvarchar(128))
  SysObject_type : (char(2))
  SysObjectColumn_column_id : (int)
  - SysObjectColumn_name : (nvarchar(128))
  tabcol_Description : (nvarchar(max))
  tabcol_DisplayFolder : (nvarchar(500))
  tabcol_Expression : (nvarchar(max))
  tabcol_FormatString : (nvarchar(500))
  - tabcol_IsHidden : (bit)
  - tabcol_IsKey : (bit)
  - tabcol_IsUnique : (bit)
  tabcol_SummarizeBy : (nvarchar(500))
  tabcol_Type : (nvarchar(500))
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn_histvalidcolums_setpoint.adoc[]" as repo.RepoObjectColumn_HistValidColums_setpoint << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  **RepoObjectColumn_name** : (sysname)
  - Repo_generated_always_type : (int)
  - Repo_is_nullable : (int)
  - Repo_user_type_fullname : (varchar(12))
  - Repo_user_type_name : (varchar(9))
  --
}

entity "puml-link:dhw:sqldb:repo.usp_index_finish.adoc[]" as repo.usp_Index_finish << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_main.adoc[]" as repo.usp_main << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_persistence_delete.adoc[]" as repo.usp_persistence_delete << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_persistence_set.adoc[]" as repo.usp_persistence_set << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_sync_guid_repoobject.adoc[]" as repo.usp_sync_guid_RepoObject << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_sync_guid_repoobjectcolumn.adoc[]" as repo.usp_sync_guid_RepoObjectColumn << P >> {
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.generatorusp_check_persistence.adoc[]" as uspgenerator.GeneratorUsp_check_persistence << V >> {
  ColumnListIgnore : (nvarchar(4000))
  ColumnListNoCompareButUpdate : (nvarchar(4000))
  ColumnListNoCompareNoUpdate : (nvarchar(4000))
  has_history : (bit)
  has_history_columns : (bit)
  - has_logging : (tinyint)
  history_schema_name : (nvarchar(128))
  history_table_name : (nvarchar(128))
  - id : (int)
  is_persistence : (bit)
  is_persistence_check_duplicate_per_pk : (bit)
  is_persistence_check_for_empty_source : (bit)
  is_persistence_delete_changed : (bit)
  is_persistence_delete_missing : (bit)
  is_persistence_insert : (bit)
  is_persistence_persist_source : (bit)
  is_persistence_truncate : (bit)
  is_persistence_update_changed : (bit)
  postscript : (nvarchar(max))
  prescript : (nvarchar(max))
  RepoObject_fullname : (nvarchar(261))
  RepoObject_guid : (uniqueidentifier)
  source_RepoObject_guid : (uniqueidentifier)
  source_RepoObject_name : (nvarchar(128))
  target_RepoObject_guid : (uniqueidentifier)
  temporal_type : (tinyint)
  usp_Description : (nvarchar(4000))
  usp_Examples : (nvarchar(4000))
  - usp_fullname : (nvarchar(261))
  - usp_name : (nvarchar(128))
  - usp_schema : (nvarchar(128))
  --
}

repo.RepoObject_persistence <.. reference.RepoObject_reference_persistence
repo.RepoObject_persistence <.. reference.RepoObject_reference_persistence_target_as_source_explicit
repo.RepoObject_persistence <.. reference.RepoObject_reference_T_bidirectional
repo.RepoObject_persistence <.. reference.RepoObjectColumn_reference_Persistence
repo.RepoObject_persistence <.. repo.RepoObject__after_delete
repo.RepoObject_persistence <.. repo.RepoObject_ColumnList
repo.RepoObject_persistence <.. repo.RepoObject_gross
repo.RepoObject_persistence <.. repo.RepoObject_gross_persistence
repo.RepoObject_persistence <.. repo.RepoObject_persistence_column
repo.RepoObject_persistence <.. repo.RepoObject_persistence_ForUpdate
repo.RepoObject_persistence <.. repo.RepoObject_persistence_NoCompareButUpdate
repo.RepoObject_persistence <.. repo.RepoObject_persistence_NoCompareNoUpdate
repo.RepoObject_persistence <.. repo.RepoObject_persistence_NoInsert
repo.RepoObject_persistence <.. repo.RepoObject_persistence_ObjectNames
repo.RepoObject_persistence <.. repo.RepoObject_persistence_source_Ignore
repo.RepoObject_persistence <.. repo.RepoObject_persistence_target_Ignore
repo.RepoObject_persistence <.. repo.RepoObjectColumn_gross
repo.RepoObject_persistence <.. repo.RepoObjectColumn_HistValidColums_setpoint
repo.RepoObject_persistence <.. repo.usp_Index_finish
repo.RepoObject_persistence <.. repo.usp_main
repo.RepoObject_persistence <.. repo.usp_persistence_delete
repo.RepoObject_persistence <.. repo.usp_persistence_set
repo.RepoObject_persistence <.. repo.usp_sync_guid_RepoObject
repo.RepoObject_persistence <.. repo.usp_sync_guid_RepoObjectColumn
repo.RepoObject_persistence <.. uspgenerator.GeneratorUsp_check_persistence
"repo.RepoObject_persistence::ColumnListIgnore" <-- "repo.RepoObject_persistence_ForUpdate::ColumnListIgnore"
"repo.RepoObject_persistence::ColumnListIgnore" <-- "repo.RepoObject_persistence_source_Ignore::ColumnListIgnore"
"repo.RepoObject_persistence::ColumnListIgnore" <-- "repo.RepoObject_persistence_target_Ignore::ColumnListIgnore"
"repo.RepoObject_persistence::ColumnListIgnore" <-- "uspgenerator.GeneratorUsp_check_persistence::ColumnListIgnore"
"repo.RepoObject_persistence::ColumnListNoCompareButUpdate" <-- "repo.RepoObject_persistence_ForUpdate::ColumnListNoCompareButUpdate"
"repo.RepoObject_persistence::ColumnListNoCompareButUpdate" <-- "repo.RepoObject_persistence_NoCompareButUpdate::ColumnListNoCompareButUpdate"
"repo.RepoObject_persistence::ColumnListNoCompareButUpdate" <-- "uspgenerator.GeneratorUsp_check_persistence::ColumnListNoCompareButUpdate"
"repo.RepoObject_persistence::ColumnListNoCompareNoUpdate" <-- "repo.RepoObject_persistence_ForUpdate::ColumnListNoCompareNoUpdate"
"repo.RepoObject_persistence::ColumnListNoCompareNoUpdate" <-- "repo.RepoObject_persistence_NoCompareNoUpdate::ColumnListNoCompareNoUpdate"
"repo.RepoObject_persistence::ColumnListNoCompareNoUpdate" <-- "uspgenerator.GeneratorUsp_check_persistence::ColumnListNoCompareNoUpdate"
"repo.RepoObject_persistence::ColumnListNoInsert" <-- "repo.RepoObject_persistence_ForUpdate::ColumnListNoInsert"
"repo.RepoObject_persistence::ColumnListNoInsert" <-- "repo.RepoObject_persistence_NoInsert::ColumnListNoInsert"
"repo.RepoObject_persistence::ExecutionLogId_action" <-- "repo.RepoObject_gross::ExecutionLogId_action"
"repo.RepoObject_persistence::ExecutionLogId_action" <-- "repo.RepoObject_gross_persistence::ExecutionLogId_action"
"repo.RepoObject_persistence::has_history" <-- "repo.RepoObject_gross::has_history"
"repo.RepoObject_persistence::has_history" <-- "repo.RepoObject_gross_persistence::has_history"
"repo.RepoObject_persistence::has_history" <-- "repo.RepoObject_persistence::temporal_type"
"repo.RepoObject_persistence::has_history" <-- "repo.RepoObject_persistence_column::has_history"
"repo.RepoObject_persistence::has_history" <-- "repo.RepoObject_persistence_ForUpdate::has_history"
"repo.RepoObject_persistence::has_history" <-- "repo.RepoObject_persistence_ObjectNames::has_history"
"repo.RepoObject_persistence::has_history" <-- "uspgenerator.GeneratorUsp_check_persistence::has_history"
"repo.RepoObject_persistence::has_history_columns" <-- "repo.RepoObject_gross::has_history_columns"
"repo.RepoObject_persistence::has_history_columns" <-- "repo.RepoObject_gross_persistence::has_history_columns"
"repo.RepoObject_persistence::has_history_columns" <-- "repo.RepoObject_persistence_column::has_history_columns"
"repo.RepoObject_persistence::has_history_columns" <-- "repo.RepoObject_persistence_ForUpdate::has_history_columns"
"repo.RepoObject_persistence::has_history_columns" <-- "repo.RepoObject_persistence_ObjectNames::has_history_columns"
"repo.RepoObject_persistence::has_history_columns" <-- "uspgenerator.GeneratorUsp_check_persistence::has_history_columns"
"repo.RepoObject_persistence::history_schema_name" <-- "repo.RepoObject_gross::history_schema_name"
"repo.RepoObject_persistence::history_schema_name" <-- "repo.RepoObject_gross_persistence::history_schema_name"
"repo.RepoObject_persistence::history_schema_name" <-- "repo.RepoObject_persistence_column::history_schema_name"
"repo.RepoObject_persistence::history_schema_name" <-- "repo.RepoObject_persistence_ForUpdate::history_schema_name"
"repo.RepoObject_persistence::history_schema_name" <-- "repo.RepoObject_persistence_ObjectNames::history_schema_name"
"repo.RepoObject_persistence::history_schema_name" <-- "uspgenerator.GeneratorUsp_check_persistence::history_schema_name"
"repo.RepoObject_persistence::history_table_name" <-- "repo.RepoObject_gross::history_table_name"
"repo.RepoObject_persistence::history_table_name" <-- "repo.RepoObject_gross_persistence::history_table_name"
"repo.RepoObject_persistence::history_table_name" <-- "repo.RepoObject_persistence_column::history_table_name"
"repo.RepoObject_persistence::history_table_name" <-- "repo.RepoObject_persistence_ForUpdate::history_table_name"
"repo.RepoObject_persistence::history_table_name" <-- "repo.RepoObject_persistence_ObjectNames::history_table_name"
"repo.RepoObject_persistence::history_table_name" <-- "uspgenerator.GeneratorUsp_check_persistence::history_table_name"
"repo.RepoObject_persistence::is_persistence" <-- "reference.RepoObject_reference_T_bidirectional::referenced_is_persistence"
"repo.RepoObject_persistence::is_persistence" <-- "reference.RepoObject_reference_T_bidirectional::referencing_is_persistence"
"repo.RepoObject_persistence::is_persistence" <-- "repo.RepoObject_gross::is_persistence"
"repo.RepoObject_persistence::is_persistence" <-- "repo.RepoObject_gross_persistence::is_persistence"
"repo.RepoObject_persistence::is_persistence" <-- "repo.RepoObject_persistence_column::is_persistence"
"repo.RepoObject_persistence::is_persistence" <-- "repo.RepoObject_persistence_ObjectNames::is_persistence"
"repo.RepoObject_persistence::is_persistence" <-- "uspgenerator.GeneratorUsp_check_persistence::is_persistence"
"repo.RepoObject_persistence::is_persistence_check_duplicate_per_pk" <-- "repo.RepoObject_gross::is_persistence_check_duplicate_per_pk"
"repo.RepoObject_persistence::is_persistence_check_duplicate_per_pk" <-- "repo.RepoObject_gross_persistence::is_persistence_check_duplicate_per_pk"
"repo.RepoObject_persistence::is_persistence_check_duplicate_per_pk" <-- "repo.RepoObject_persistence_ForUpdate::is_persistence_check_duplicate_per_pk"
"repo.RepoObject_persistence::is_persistence_check_duplicate_per_pk" <-- "uspgenerator.GeneratorUsp_check_persistence::is_persistence_check_duplicate_per_pk"
"repo.RepoObject_persistence::is_persistence_check_for_empty_source" <-- "repo.RepoObject_gross::is_persistence_check_for_empty_source"
"repo.RepoObject_persistence::is_persistence_check_for_empty_source" <-- "repo.RepoObject_gross_persistence::is_persistence_check_for_empty_source"
"repo.RepoObject_persistence::is_persistence_check_for_empty_source" <-- "repo.RepoObject_persistence_column::is_persistence_check_for_empty_source"
"repo.RepoObject_persistence::is_persistence_check_for_empty_source" <-- "repo.RepoObject_persistence_ForUpdate::is_persistence_check_for_empty_source"
"repo.RepoObject_persistence::is_persistence_check_for_empty_source" <-- "repo.RepoObject_persistence_ObjectNames::is_persistence_check_for_empty_source"
"repo.RepoObject_persistence::is_persistence_check_for_empty_source" <-- "uspgenerator.GeneratorUsp_check_persistence::is_persistence_check_for_empty_source"
"repo.RepoObject_persistence::is_persistence_delete_changed" <-- "repo.RepoObject_gross::is_persistence_delete_changed"
"repo.RepoObject_persistence::is_persistence_delete_changed" <-- "repo.RepoObject_gross_persistence::is_persistence_delete_changed"
"repo.RepoObject_persistence::is_persistence_delete_changed" <-- "repo.RepoObject_persistence_column::is_persistence_delete_changed"
"repo.RepoObject_persistence::is_persistence_delete_changed" <-- "repo.RepoObject_persistence_ForUpdate::is_persistence_delete_changed"
"repo.RepoObject_persistence::is_persistence_delete_changed" <-- "repo.RepoObject_persistence_ObjectNames::is_persistence_delete_changed"
"repo.RepoObject_persistence::is_persistence_delete_changed" <-- "uspgenerator.GeneratorUsp_check_persistence::is_persistence_delete_changed"
"repo.RepoObject_persistence::is_persistence_delete_missing" <-- "repo.RepoObject_gross::is_persistence_delete_missing"
"repo.RepoObject_persistence::is_persistence_delete_missing" <-- "repo.RepoObject_gross_persistence::is_persistence_delete_missing"
"repo.RepoObject_persistence::is_persistence_delete_missing" <-- "repo.RepoObject_persistence_column::is_persistence_delete_missing"
"repo.RepoObject_persistence::is_persistence_delete_missing" <-- "repo.RepoObject_persistence_ForUpdate::is_persistence_delete_missing"
"repo.RepoObject_persistence::is_persistence_delete_missing" <-- "repo.RepoObject_persistence_ObjectNames::is_persistence_delete_missing"
"repo.RepoObject_persistence::is_persistence_delete_missing" <-- "uspgenerator.GeneratorUsp_check_persistence::is_persistence_delete_missing"
"repo.RepoObject_persistence::is_persistence_insert" <-- "repo.RepoObject_gross::is_persistence_insert"
"repo.RepoObject_persistence::is_persistence_insert" <-- "repo.RepoObject_gross_persistence::is_persistence_insert"
"repo.RepoObject_persistence::is_persistence_insert" <-- "repo.RepoObject_persistence_column::is_persistence_insert"
"repo.RepoObject_persistence::is_persistence_insert" <-- "repo.RepoObject_persistence_ForUpdate::is_persistence_insert"
"repo.RepoObject_persistence::is_persistence_insert" <-- "repo.RepoObject_persistence_ObjectNames::is_persistence_insert"
"repo.RepoObject_persistence::is_persistence_insert" <-- "uspgenerator.GeneratorUsp_check_persistence::is_persistence_insert"
"repo.RepoObject_persistence::is_persistence_persist_source" <-- "repo.RepoObject_gross::is_persistence_persist_source"
"repo.RepoObject_persistence::is_persistence_persist_source" <-- "repo.RepoObject_gross_persistence::is_persistence_persist_source"
"repo.RepoObject_persistence::is_persistence_persist_source" <-- "repo.RepoObject_persistence_ForUpdate::is_persistence_persist_source"
"repo.RepoObject_persistence::is_persistence_persist_source" <-- "uspgenerator.GeneratorUsp_check_persistence::is_persistence_persist_source"
"repo.RepoObject_persistence::is_persistence_truncate" <-- "repo.RepoObject_gross::is_persistence_truncate"
"repo.RepoObject_persistence::is_persistence_truncate" <-- "repo.RepoObject_gross_persistence::is_persistence_truncate"
"repo.RepoObject_persistence::is_persistence_truncate" <-- "repo.RepoObject_persistence_column::is_persistence_truncate"
"repo.RepoObject_persistence::is_persistence_truncate" <-- "repo.RepoObject_persistence_ForUpdate::is_persistence_truncate"
"repo.RepoObject_persistence::is_persistence_truncate" <-- "repo.RepoObject_persistence_ObjectNames::is_persistence_truncate"
"repo.RepoObject_persistence::is_persistence_truncate" <-- "uspgenerator.GeneratorUsp_check_persistence::is_persistence_truncate"
"repo.RepoObject_persistence::is_persistence_update_changed" <-- "repo.RepoObject_gross::is_persistence_update_changed"
"repo.RepoObject_persistence::is_persistence_update_changed" <-- "repo.RepoObject_gross_persistence::is_persistence_update_changed"
"repo.RepoObject_persistence::is_persistence_update_changed" <-- "repo.RepoObject_persistence_column::is_persistence_update_changed"
"repo.RepoObject_persistence::is_persistence_update_changed" <-- "repo.RepoObject_persistence_ForUpdate::is_persistence_update_changed"
"repo.RepoObject_persistence::is_persistence_update_changed" <-- "repo.RepoObject_persistence_ObjectNames::is_persistence_update_changed"
"repo.RepoObject_persistence::is_persistence_update_changed" <-- "uspgenerator.GeneratorUsp_check_persistence::is_persistence_update_changed"
"repo.RepoObject_persistence::postscript" <-- "repo.RepoObject_gross::postscript"
"repo.RepoObject_persistence::postscript" <-- "repo.RepoObject_gross_persistence::postscript"
"repo.RepoObject_persistence::postscript" <-- "repo.RepoObject_persistence_ForUpdate::postscript"
"repo.RepoObject_persistence::postscript" <-- "uspgenerator.GeneratorUsp_check_persistence::postscript"
"repo.RepoObject_persistence::prescript" <-- "repo.RepoObject_gross::prescript"
"repo.RepoObject_persistence::prescript" <-- "repo.RepoObject_gross_persistence::prescript"
"repo.RepoObject_persistence::prescript" <-- "repo.RepoObject_persistence_ForUpdate::prescript"
"repo.RepoObject_persistence::prescript" <-- "uspgenerator.GeneratorUsp_check_persistence::prescript"
"repo.RepoObject_persistence::source_RepoObject_guid" <-- "reference.RepoObject_reference_persistence::referenced_RepoObject_guid"
"repo.RepoObject_persistence::source_RepoObject_guid" <-- "reference.RepoObject_reference_T_bidirectional::referenced_source_RepoObject_guid"
"repo.RepoObject_persistence::source_RepoObject_guid" <-- "reference.RepoObject_reference_T_bidirectional::referencing_source_RepoObject_guid"
"repo.RepoObject_persistence::source_RepoObject_guid" <-- "reference.RepoObjectColumn_reference_Persistence::referenced_RepoObject_guid"
"repo.RepoObject_persistence::source_RepoObject_guid" <-- "repo.RepoObject_gross::persistence_source_RepoObject_guid"
"repo.RepoObject_persistence::source_RepoObject_guid" <-- "repo.RepoObject_gross_persistence::persistence_source_RepoObject_guid"
"repo.RepoObject_persistence::source_RepoObject_guid" <-- "repo.RepoObject_persistence_column::source_RepoObject_guid"
"repo.RepoObject_persistence::source_RepoObject_guid" <-- "repo.RepoObject_persistence_ForUpdate::source_RepoObject_guid"
"repo.RepoObject_persistence::source_RepoObject_guid" <-- "repo.RepoObject_persistence_NoCompareButUpdate::source_RepoObject_guid"
"repo.RepoObject_persistence::source_RepoObject_guid" <-- "repo.RepoObject_persistence_NoCompareNoUpdate::source_RepoObject_guid"
"repo.RepoObject_persistence::source_RepoObject_guid" <-- "repo.RepoObject_persistence_NoInsert::source_RepoObject_guid"
"repo.RepoObject_persistence::source_RepoObject_guid" <-- "repo.RepoObject_persistence_ObjectNames::source_RepoObject_guid"
"repo.RepoObject_persistence::source_RepoObject_guid" <-- "repo.RepoObject_persistence_source_Ignore::source_RepoObject_guid"
"repo.RepoObject_persistence::source_RepoObject_guid" <-- "repo.RepoObject_persistence_target_Ignore::source_RepoObject_guid"
"repo.RepoObject_persistence::source_RepoObject_guid" <-- "repo.RepoObjectColumn_gross::persistence_source_RepoObject_guid"
"repo.RepoObject_persistence::source_RepoObject_guid" <-- "uspgenerator.GeneratorUsp_check_persistence::source_RepoObject_guid"
"repo.RepoObject_persistence::source_RepoObject_name" <-- "repo.RepoObject_persistence_ForUpdate::source_RepoObject_name"
"repo.RepoObject_persistence::source_RepoObject_name" <-- "repo.RepoObject_persistence_NoCompareButUpdate::source_RepoObject_name"
"repo.RepoObject_persistence::source_RepoObject_name" <-- "repo.RepoObject_persistence_NoCompareNoUpdate::source_RepoObject_name"
"repo.RepoObject_persistence::source_RepoObject_name" <-- "repo.RepoObject_persistence_NoInsert::source_RepoObject_name"
"repo.RepoObject_persistence::source_RepoObject_name" <-- "repo.RepoObject_persistence_source_Ignore::source_RepoObject_name"
"repo.RepoObject_persistence::source_RepoObject_name" <-- "repo.RepoObject_persistence_target_Ignore::source_RepoObject_name"
"repo.RepoObject_persistence::source_RepoObject_name" <-- "uspgenerator.GeneratorUsp_check_persistence::source_RepoObject_name"
"repo.RepoObject_persistence::target_RepoObject_guid" <-- "reference.RepoObject_reference_persistence::referencing_RepoObject_guid"
"repo.RepoObject_persistence::target_RepoObject_guid" <-- "reference.RepoObjectColumn_reference_Persistence::referencing_RepoObject_guid"
"repo.RepoObject_persistence::target_RepoObject_guid" <-- "repo.RepoObject_persistence_column::target_RepoObject_guid"
"repo.RepoObject_persistence::target_RepoObject_guid" <-- "repo.RepoObject_persistence_ForUpdate::target_RepoObject_guid"
"repo.RepoObject_persistence::target_RepoObject_guid" <-- "repo.RepoObject_persistence_NoCompareButUpdate::target_RepoObject_guid"
"repo.RepoObject_persistence::target_RepoObject_guid" <-- "repo.RepoObject_persistence_NoCompareNoUpdate::target_RepoObject_guid"
"repo.RepoObject_persistence::target_RepoObject_guid" <-- "repo.RepoObject_persistence_NoInsert::target_RepoObject_guid"
"repo.RepoObject_persistence::target_RepoObject_guid" <-- "repo.RepoObject_persistence_ObjectNames::target_RepoObject_guid"
"repo.RepoObject_persistence::target_RepoObject_guid" <-- "repo.RepoObject_persistence_source_Ignore::target_RepoObject_guid"
"repo.RepoObject_persistence::target_RepoObject_guid" <-- "repo.RepoObject_persistence_target_Ignore::target_RepoObject_guid"
"repo.RepoObject_persistence::target_RepoObject_guid" <-- "repo.RepoObjectColumn_HistValidColums_setpoint::RepoObject_guid"
"repo.RepoObject_persistence::target_RepoObject_guid" <-- "uspgenerator.GeneratorUsp_check_persistence::target_RepoObject_guid"
"repo.RepoObject_persistence::temporal_type" <-- "repo.RepoObject_gross::temporal_type"
"repo.RepoObject_persistence::temporal_type" <-- "repo.RepoObject_gross_persistence::temporal_type"
"repo.RepoObject_persistence::temporal_type" <-- "uspgenerator.GeneratorUsp_check_persistence::temporal_type"

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_colref[]


== sql_modules_definition

// tag::sql_modules_definition[]
[%collapsible]
=======
[source,sql,numbered,indent=0]
----

----
=======
// end::sql_modules_definition[]


