// tag::HeaderFullDisplayName[]
= repo.RepoObjectColumn_gross - V
// end::HeaderFullDisplayName[]

== existing_properties

// tag::existing_properties[]

:ExistsProperty--antorareferencedlist:
:ExistsProperty--antorareferencinglist:
:ExistsProperty--has_execution_plan_issue:
:ExistsProperty--is_repo_managed:
:ExistsProperty--is_ssas:
:ExistsProperty--referencedobjectlist:
:ExistsProperty--sql_modules_definition:
:ExistsProperty--FK:
:ExistsProperty--AntoraIndexList:
:ExistsProperty--Columns:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
6990291C-9D61-EB11-84DC-A81E8446D5B0
// end::RepoObject_guid[]

== RepoObject_FullDisplayName2

// tag::RepoObject_FullDisplayName2[]
repo.RepoObjectColumn_gross
// end::RepoObject_FullDisplayName2[]

== SysObject_type

// tag::SysObject_type[]
V 
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
view
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
1044914794
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2022-09-05 16:51:04
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]
[discrete]
== _


[#column-columnunderlinename]
=== Column_name

[cols="d,8a,m,m,m"]
|===
|
|Column_name
|nvarchar(128)
|NOT NULL
|
|===

.Description
--
(case when TRY_CAST([RepoObjectColumn_name] AS [uniqueidentifier]) IS NULL then [RepoObjectColumn_name] else [SysObjectColumn_name] end)
--
{empty} +

.Referenced Columns
--
* xref:repo.repoobjectcolumn.adoc#column-columnunderlinename[+repo.RepoObjectColumn.Column_name+]
--

.Referencing Columns
--
* xref:repo.repoobjectcolumn_gross2.adoc#column-columnunderlinename[+repo.RepoObjectColumn_gross2.Column_name+]
* xref:ssas.repoobjectcolumn_translation.adoc#column-columnunderlinename[+ssas.RepoObjectColumn_translation.Column_name+]
--


[#column-description]
=== Description

[cols="d,8a,m,m,m"]
|===
|
|Description
|nvarchar(max)
|NULL
|
|===

.Referencing Columns
--
* xref:repo.repoobjectcolumn_gross2.adoc#column-description[+repo.RepoObjectColumn_gross2.Description+]
--


[#column-hasunderlinedifferentunderlinesysunderlinenames]
=== has_different_sys_names

[cols="d,8a,m,m,m"]
|===
|
|has_different_sys_names
|bit
|NULL
|
|===

.Description
--
(CONVERT([bit],case when [RepoObjectColumn_name]<>[SysObjectColumn_name] then (1) else (0) end))
--
{empty} +

.Referenced Columns
--
* xref:repo.repoobjectcolumn.adoc#column-hasunderlinedifferentunderlinesysunderlinenames[+repo.RepoObjectColumn.has_different_sys_names+]
--

.Referencing Columns
--
* xref:repo.repoobjectcolumn_gross2.adoc#column-hasunderlinedifferentunderlinesysunderlinenames[+repo.RepoObjectColumn_gross2.has_different_sys_names+]
--


[#column-hasunderlinegetunderlinereferencedunderlineissue]
=== has_get_referenced_issue

[cols="d,8a,m,m,m"]
|===
|
|has_get_referenced_issue
|bit
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject.adoc#column-hasunderlinegetunderlinereferencedunderlineissue[+repo.RepoObject.has_get_referenced_issue+]
--

.Referencing Columns
--
* xref:repo.repoobjectcolumn_gross2.adoc#column-hasunderlinegetunderlinereferencedunderlineissue[+repo.RepoObjectColumn_gross2.has_get_referenced_issue+]
--


[#column-inheritanceunderlinestringaggseparatorsql]
=== Inheritance_StringAggSeparatorSql

[cols="d,8a,m,m,m"]
|===
|
|Inheritance_StringAggSeparatorSql
|nvarchar(4000)
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobjectcolumn.adoc#column-inheritanceunderlinestringaggseparatorsql[+repo.RepoObjectColumn.Inheritance_StringAggSeparatorSql+]
--

.Referencing Columns
--
* xref:repo.repoobjectcolumn_gross2.adoc#column-inheritanceunderlinestringaggseparatorsql[+repo.RepoObjectColumn_gross2.Inheritance_StringAggSeparatorSql+]
--


[#column-inheritancedefinition]
=== InheritanceDefinition

[cols="d,8a,m,m,m"]
|===
|
|InheritanceDefinition
|nvarchar(4000)
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobjectcolumn.adoc#column-inheritancedefinition[+repo.RepoObjectColumn.InheritanceDefinition+]
--

.Referencing Columns
--
* xref:property.repoobjectcolumnproperty_forupdate.adoc#column-inheritancedefinition[+property.RepoObjectColumnProperty_ForUpdate.InheritanceDefinition+]
* xref:repo.repoobjectcolumn_gross2.adoc#column-inheritancedefinition[+repo.RepoObjectColumn_gross2.InheritanceDefinition+]
--


[#column-inheritancetype]
=== InheritanceType

[cols="d,8a,m,m,m"]
|===
|
|InheritanceType
|tinyint
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobjectcolumn.adoc#column-inheritancetype[+repo.RepoObjectColumn.InheritanceType+]
--

.Referencing Columns
--
* xref:property.repoobjectcolumnproperty_forupdate.adoc#column-inheritancetype[+property.RepoObjectColumnProperty_ForUpdate.InheritanceType+]
* xref:repo.repoobjectcolumn_gross2.adoc#column-inheritancetype[+repo.RepoObjectColumn_gross2.InheritanceType+]
--


[#column-isunderlineexternal]
=== is_external

[cols="d,8a,m,m,m"]
|===
|
|is_external
|bit
|NOT NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject.adoc#column-isunderlineexternal[+repo.RepoObject.is_external+]
--

.Referencing Columns
--
* xref:repo.repoobjectcolumn_gross2.adoc#column-isunderlineexternal[+repo.RepoObjectColumn_gross2.is_external+]
--


[#column-isunderlinepersistenceunderlineignore]
=== is_persistence_Ignore

[cols="d,8a,m,m,m"]
|===
|
|is_persistence_Ignore
|bit
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobjectcolumn.adoc#column-isunderlinepersistenceunderlineignore[+repo.RepoObjectColumn.is_persistence_Ignore+]
--

.Referencing Columns
--
* xref:repo.repoobjectcolumn_gross2.adoc#column-isunderlinepersistenceunderlineignore[+repo.RepoObjectColumn_gross2.is_persistence_Ignore+]
--


[#column-isunderlinepersistenceunderlinenocomparebutupdate]
=== is_persistence_NoCompareButUpdate

[cols="d,8a,m,m,m"]
|===
|
|is_persistence_NoCompareButUpdate
|bit
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobjectcolumn.adoc#column-isunderlinepersistenceunderlinenocomparebutupdate[+repo.RepoObjectColumn.is_persistence_NoCompareButUpdate+]
--

.Referencing Columns
--
* xref:repo.repoobjectcolumn_gross2.adoc#column-isunderlinepersistenceunderlinenocomparebutupdate[+repo.RepoObjectColumn_gross2.is_persistence_NoCompareButUpdate+]
--


[#column-isunderlinepersistenceunderlinenocomparenoupdate]
=== is_persistence_NoCompareNoUpdate

[cols="d,8a,m,m,m"]
|===
|
|is_persistence_NoCompareNoUpdate
|bit
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobjectcolumn.adoc#column-isunderlinepersistenceunderlinenocomparenoupdate[+repo.RepoObjectColumn.is_persistence_NoCompareNoUpdate+]
--

.Referencing Columns
--
* xref:repo.repoobjectcolumn_gross2.adoc#column-isunderlinepersistenceunderlinenocomparenoupdate[+repo.RepoObjectColumn_gross2.is_persistence_NoCompareNoUpdate+]
--


[#column-isunderlinepersistenceunderlinenoinsert]
=== is_persistence_NoInsert

[cols="d,8a,m,m,m"]
|===
|
|is_persistence_NoInsert
|bit
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobjectcolumn.adoc#column-isunderlinepersistenceunderlinenoinsert[+repo.RepoObjectColumn.is_persistence_NoInsert+]
--

.Referencing Columns
--
* xref:repo.repoobjectcolumn_gross2.adoc#column-isunderlinepersistenceunderlinenoinsert[+repo.RepoObjectColumn_gross2.is_persistence_NoInsert+]
--


[#column-isunderlinequeryunderlineplanunderlineexpression]
=== is_query_plan_expression

[cols="d,8a,m,m,m"]
|===
|
|is_query_plan_expression
|bit
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobjectcolumn.adoc#column-isunderlinequeryunderlineplanunderlineexpression[+repo.RepoObjectColumn.is_query_plan_expression+]
--

.Referencing Columns
--
* xref:repo.repoobjectcolumn_gross2.adoc#column-isunderlinequeryunderlineplanunderlineexpression[+repo.RepoObjectColumn_gross2.is_query_plan_expression+]
--


[#column-isunderlinerepounderlinemanaged]
=== is_repo_managed

[cols="d,8a,m,m,m"]
|===
|
|is_repo_managed
|bit
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject.adoc#column-isunderlinerepounderlinemanaged[+repo.RepoObject.is_repo_managed+]
--

.Referencing Columns
--
* xref:repo.repoobjectcolumn_gross2.adoc#column-isunderlinerepounderlinemanaged[+repo.RepoObjectColumn_gross2.is_repo_managed+]
--


[#column-isunderlinerepoobjectunderlinenameunderlineuniqueidentifier]
=== is_RepoObject_name_uniqueidentifier

[cols="d,8a,m,m,m"]
|===
|
|is_RepoObject_name_uniqueidentifier
|int
|NOT NULL
|
|===

.Description
--
(case when TRY_CAST([RepoObject_name] AS [uniqueidentifier]) IS NULL then (0) else (1) end)
--
{empty} +

.Referenced Columns
--
* xref:repo.repoobject.adoc#column-isunderlinerepoobjectunderlinenameunderlineuniqueidentifier[+repo.RepoObject.is_RepoObject_name_uniqueidentifier+]
--

.Referencing Columns
--
* xref:repo.repoobjectcolumn_gross2.adoc#column-isunderlinerepoobjectunderlinenameunderlineuniqueidentifier[+repo.RepoObjectColumn_gross2.is_RepoObject_name_uniqueidentifier+]
--


[#column-isunderlinerepoobjectcolumnunderlinenameunderlineuniqueidentifier]
=== is_RepoObjectColumn_name_uniqueidentifier

[cols="d,8a,m,m,m"]
|===
|
|is_RepoObjectColumn_name_uniqueidentifier
|int
|NOT NULL
|
|===

.Description
--
(case when TRY_CAST([RepoObjectColumn_name] AS [uniqueidentifier]) IS NULL then (0) else (1) end)
--
{empty} +

.Referenced Columns
--
* xref:repo.repoobjectcolumn.adoc#column-isunderlinerepoobjectcolumnunderlinenameunderlineuniqueidentifier[+repo.RepoObjectColumn.is_RepoObjectColumn_name_uniqueidentifier+]
--

.Referencing Columns
--
* xref:repo.repoobjectcolumn_gross2.adoc#column-isunderlinerepoobjectcolumnunderlinenameunderlineuniqueidentifier[+repo.RepoObjectColumn_gross2.is_RepoObjectColumn_name_uniqueidentifier+]
--


[#column-isunderlinerequiredunderlinecolumnmerge]
=== is_required_ColumnMerge

[cols="d,8a,m,m,m"]
|===
|
|is_required_ColumnMerge
|bit
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobjectcolumn.adoc#column-isunderlinerequiredunderlinecolumnmerge[+repo.RepoObjectColumn.is_required_ColumnMerge+]
--

.Referencing Columns
--
* xref:repo.repoobjectcolumn_gross2.adoc#column-isunderlinerequiredunderlinecolumnmerge[+repo.RepoObjectColumn_gross2.is_required_ColumnMerge+]
--


[#column-isunderlinessas]
=== is_ssas

[cols="d,8a,m,m,m"]
|===
|
|is_ssas
|bit
|NOT NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject.adoc#column-isunderlinessas[+repo.RepoObject.is_ssas+]
--

.Referencing Columns
--
* xref:repo.repoobjectcolumn_gross2.adoc#column-isunderlinessas[+repo.RepoObjectColumn_gross2.is_ssas+]
--


[#column-isunderlinesysobjectunderlinemissing]
=== is_SysObject_missing

[cols="d,8a,m,m,m"]
|===
|
|is_SysObject_missing
|bit
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject.adoc#column-isunderlinesysobjectunderlinemissing[+repo.RepoObject.is_SysObject_missing+]
--

.Referencing Columns
--
* xref:repo.repoobjectcolumn_gross2.adoc#column-isunderlinesysobjectunderlinemissing[+repo.RepoObjectColumn_gross2.is_SysObject_missing+]
--


[#column-isunderlinesysobjectunderlinenameunderlineuniqueidentifier]
=== is_SysObject_name_uniqueidentifier

[cols="d,8a,m,m,m"]
|===
|
|is_SysObject_name_uniqueidentifier
|int
|NOT NULL
|
|===

.Description
--
(case when TRY_CAST([SysObject_name] AS [uniqueidentifier]) IS NULL then (0) else (1) end)
--
{empty} +

.Referenced Columns
--
* xref:repo.repoobject.adoc#column-isunderlinesysobjectunderlinenameunderlineuniqueidentifier[+repo.RepoObject.is_SysObject_name_uniqueidentifier+]
--

.Referencing Columns
--
* xref:repo.repoobjectcolumn_gross2.adoc#column-isunderlinesysobjectunderlinenameunderlineuniqueidentifier[+repo.RepoObjectColumn_gross2.is_SysObject_name_uniqueidentifier+]
--


[#column-isunderlinesysobjectcolumnunderlinemissing]
=== is_SysObjectColumn_missing

[cols="d,8a,m,m,m"]
|===
|
|is_SysObjectColumn_missing
|bit
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobjectcolumn.adoc#column-isunderlinesysobjectcolumnunderlinemissing[+repo.RepoObjectColumn.is_SysObjectColumn_missing+]
--

.Referencing Columns
--
* xref:repo.repoobjectcolumn_gross2.adoc#column-isunderlinesysobjectcolumnunderlinemissing[+repo.RepoObjectColumn_gross2.is_SysObjectColumn_missing+]
--


[#column-isunderlinesysobjectcolumnunderlinenameunderlineuniqueidentifier]
=== is_SysObjectColumn_name_uniqueidentifier

[cols="d,8a,m,m,m"]
|===
|
|is_SysObjectColumn_name_uniqueidentifier
|int
|NOT NULL
|
|===

.Description
--
(case when TRY_CAST([SysObjectColumn_name] AS [uniqueidentifier]) IS NULL then (0) else (1) end)
--
{empty} +

.Referenced Columns
--
* xref:repo.repoobjectcolumn.adoc#column-isunderlinesysobjectcolumnunderlinenameunderlineuniqueidentifier[+repo.RepoObjectColumn.is_SysObjectColumn_name_uniqueidentifier+]
--

.Referencing Columns
--
* xref:repo.repoobjectcolumn_gross2.adoc#column-isunderlinesysobjectcolumnunderlinenameunderlineuniqueidentifier[+repo.RepoObjectColumn_gross2.is_SysObjectColumn_name_uniqueidentifier+]
--


[#column-modifyunderlinedt]
=== modify_dt

[cols="d,8a,m,m,m"]
|===
|
|modify_dt
|datetime
|NOT NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject.adoc#column-modifyunderlinedt[+repo.RepoObject.modify_dt+]
--

.Referencing Columns
--
* xref:repo.repoobjectcolumn_gross2.adoc#column-modifyunderlinedt[+repo.RepoObjectColumn_gross2.modify_dt+]
--


[#column-nodeunderlineid]
=== node_id

[cols="d,8a,m,m,m"]
|===
|
|node_id
|bigint
|NULL
|
|===

.Description
--
(CONVERT([bigint],[SysObject_id])*(10000))
--
{empty} +

.Referenced Columns
--
* xref:repo.repoobject.adoc#column-nodeunderlineid[+repo.RepoObject.node_id+]
--

.Referencing Columns
--
* xref:reference.repoobjectcolumn_reference_virtual.adoc#column-referencingunderlinenodeunderlineid[+reference.RepoObjectColumn_reference_virtual.referencing_node_id+]
* xref:reference.repoobjectcolumn_reference_virtual.adoc#column-referencedunderlinenodeunderlineid[+reference.RepoObjectColumn_reference_virtual.referenced_node_id+]
* xref:repo.repoobjectcolumn_gross2.adoc#column-nodeunderlineid[+repo.RepoObjectColumn_gross2.node_id+]
--


[#column-persistenceunderlinesourceunderlinerepoobjectunderlineguid]
=== persistence_source_RepoObject_guid

[cols="d,8a,m,m,m"]
|===
|
|persistence_source_RepoObject_guid
|uniqueidentifier
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_persistence.adoc#column-sourceunderlinerepoobjectunderlineguid[+repo.RepoObject_persistence.source_RepoObject_guid+]
--

.Referencing Columns
--
* xref:repo.repoobjectcolumn_gross2.adoc#column-persistenceunderlinesourceunderlinerepoobjectunderlineguid[+repo.RepoObjectColumn_gross2.persistence_source_RepoObject_guid+]
--


[#column-persistenceunderlinesourceunderlinerepoobjectcolumnunderlineguid]
=== persistence_source_RepoObjectColumn_guid

[cols="d,8a,m,m,m"]
|===
|
|persistence_source_RepoObjectColumn_guid
|uniqueidentifier
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobjectcolumn.adoc#column-persistenceunderlinesourceunderlinerepoobjectcolumnunderlineguid[+repo.RepoObjectColumn.persistence_source_RepoObjectColumn_guid+]
--

.Referencing Columns
--
* xref:repo.repoobjectcolumn_gross2.adoc#column-persistenceunderlinesourceunderlinerepoobjectcolumnunderlineguid[+repo.RepoObjectColumn_gross2.persistence_source_RepoObjectColumn_guid+]
--


[#column-pkunderlineindexunderlineguid]
=== pk_index_guid

[cols="d,8a,m,m,m"]
|===
|
|pk_index_guid
|uniqueidentifier
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject.adoc#column-pkunderlineindexunderlineguid[+repo.RepoObject.pk_index_guid+]
--

.Referencing Columns
--
* xref:repo.repoobjectcolumn_gross2.adoc#column-pkunderlineindexunderlineguid[+repo.RepoObjectColumn_gross2.pk_index_guid+]
* xref:ssas.repoobjectcolumn_translation.adoc#column-pkunderlineindexunderlineguid[+ssas.RepoObjectColumn_translation.pk_index_guid+]
--


[#column-propertyunderlinemsunderlinedescription]
=== Property_ms_description

[cols="d,8a,m,m,m"]
|===
|
|Property_ms_description
|nvarchar(4000)
|NULL
|
|===

.Referencing Columns
--
* xref:repo.repoobjectcolumn_gross2.adoc#column-propertyunderlinemsunderlinedescription[+repo.RepoObjectColumn_gross2.Property_ms_description+]
--


[#column-referencingunderlinecount]
=== Referencing_Count

[cols="d,8a,m,m,m"]
|===
|
|Referencing_Count
|int
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobjectcolumn.adoc#column-referencingunderlinecount[+repo.RepoObjectColumn.Referencing_Count+]
--

.Referencing Columns
--
* xref:repo.repoobjectcolumn_gross2.adoc#column-referencingunderlinecount[+repo.RepoObjectColumn_gross2.Referencing_Count+]
--


[#column-repounderlinedefaultunderlinedefinition]
=== Repo_default_definition

[cols="d,8a,m,m,m"]
|===
|
|Repo_default_definition
|nvarchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobjectcolumn.adoc#column-repounderlinedefaultunderlinedefinition[+repo.RepoObjectColumn.Repo_default_definition+]
--

.Referencing Columns
--
* xref:repo.repoobjectcolumn_gross2.adoc#column-repounderlinedefaultunderlinedefinition[+repo.RepoObjectColumn_gross2.Repo_default_definition+]
--


[#column-repounderlinedefaultunderlineisunderlinesystemunderlinenamed]
=== Repo_default_is_system_named

[cols="d,8a,m,m,m"]
|===
|
|Repo_default_is_system_named
|bit
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobjectcolumn.adoc#column-repounderlinedefaultunderlineisunderlinesystemunderlinenamed[+repo.RepoObjectColumn.Repo_default_is_system_named+]
--

.Referencing Columns
--
* xref:repo.repoobjectcolumn_gross2.adoc#column-repounderlinedefaultunderlineisunderlinesystemunderlinenamed[+repo.RepoObjectColumn_gross2.Repo_default_is_system_named+]
--


[#column-repounderlinedefaultunderlinename]
=== Repo_default_name

[cols="d,8a,m,m,m"]
|===
|
|Repo_default_name
|nvarchar(128)
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobjectcolumn.adoc#column-repounderlinedefaultunderlinename[+repo.RepoObjectColumn.Repo_default_name+]
--

.Referencing Columns
--
* xref:repo.repoobjectcolumn_gross2.adoc#column-repounderlinedefaultunderlinename[+repo.RepoObjectColumn_gross2.Repo_default_name+]
--


[#column-repounderlinedefinition]
=== Repo_definition

[cols="d,8a,m,m,m"]
|===
|
|Repo_definition
|nvarchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobjectcolumn.adoc#column-repounderlinedefinition[+repo.RepoObjectColumn.Repo_definition+]
--

.Referencing Columns
--
* xref:repo.repoobjectcolumn_gross2.adoc#column-repounderlinedefinition[+repo.RepoObjectColumn_gross2.Repo_definition+]
--


[#column-repounderlinegeneratedunderlinealwaysunderlinetype]
=== Repo_generated_always_type

[cols="d,8a,m,m,m"]
|===
|
|Repo_generated_always_type
|tinyint
|NOT NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobjectcolumn.adoc#column-repounderlinegeneratedunderlinealwaysunderlinetype[+repo.RepoObjectColumn.Repo_generated_always_type+]
--

.Referencing Columns
--
* xref:repo.repoobjectcolumn_gross2.adoc#column-repounderlinegeneratedunderlinealwaysunderlinetype[+repo.RepoObjectColumn_gross2.Repo_generated_always_type+]
--


[#column-repounderlinegraphunderlinetype]
=== Repo_graph_type

[cols="d,8a,m,m,m"]
|===
|
|Repo_graph_type
|int
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobjectcolumn.adoc#column-repounderlinegraphunderlinetype[+repo.RepoObjectColumn.Repo_graph_type+]
--

.Referencing Columns
--
* xref:repo.repoobjectcolumn_gross2.adoc#column-repounderlinegraphunderlinetype[+repo.RepoObjectColumn_gross2.Repo_graph_type+]
--


[#column-repounderlineincrementunderlinevalue]
=== Repo_increment_value

[cols="d,8a,m,m,m"]
|===
|
|Repo_increment_value
|sql_variant
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobjectcolumn.adoc#column-repounderlineincrementunderlinevalue[+repo.RepoObjectColumn.Repo_increment_value+]
--

.Referencing Columns
--
* xref:repo.repoobjectcolumn_gross2.adoc#column-repounderlineincrementunderlinevalue[+repo.RepoObjectColumn_gross2.Repo_increment_value+]
--


[#column-repounderlineisunderlinecomputed]
=== Repo_is_computed

[cols="d,8a,m,m,m"]
|===
|
|Repo_is_computed
|bit
|NOT NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobjectcolumn.adoc#column-repounderlineisunderlinecomputed[+repo.RepoObjectColumn.Repo_is_computed+]
--

.Referencing Columns
--
* xref:repo.repoobjectcolumn_gross2.adoc#column-repounderlineisunderlinecomputed[+repo.RepoObjectColumn_gross2.Repo_is_computed+]
--


[#column-repounderlineisunderlineidentity]
=== Repo_is_identity

[cols="d,8a,m,m,m"]
|===
|
|Repo_is_identity
|bit
|NOT NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobjectcolumn.adoc#column-repounderlineisunderlineidentity[+repo.RepoObjectColumn.Repo_is_identity+]
--

.Referencing Columns
--
* xref:repo.repoobjectcolumn_gross2.adoc#column-repounderlineisunderlineidentity[+repo.RepoObjectColumn_gross2.Repo_is_identity+]
--


[#column-repounderlineisunderlinenullable]
=== Repo_is_nullable

[cols="d,8a,m,m,m"]
|===
|
|Repo_is_nullable
|bit
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobjectcolumn.adoc#column-repounderlineisunderlinenullable[+repo.RepoObjectColumn.Repo_is_nullable+]
--

.Referencing Columns
--
* xref:repo.repoobjectcolumn_gross2.adoc#column-repounderlineisunderlinenullable[+repo.RepoObjectColumn_gross2.Repo_is_nullable+]
--


[#column-repounderlineisunderlinepersisted]
=== Repo_is_persisted

[cols="d,8a,m,m,m"]
|===
|
|Repo_is_persisted
|bit
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobjectcolumn.adoc#column-repounderlineisunderlinepersisted[+repo.RepoObjectColumn.Repo_is_persisted+]
--

.Referencing Columns
--
* xref:repo.repoobjectcolumn_gross2.adoc#column-repounderlineisunderlinepersisted[+repo.RepoObjectColumn_gross2.Repo_is_persisted+]
--


[#column-repounderlineseedunderlinevalue]
=== Repo_seed_value

[cols="d,8a,m,m,m"]
|===
|
|Repo_seed_value
|sql_variant
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobjectcolumn.adoc#column-repounderlineseedunderlinevalue[+repo.RepoObjectColumn.Repo_seed_value+]
--

.Referencing Columns
--
* xref:repo.repoobjectcolumn_gross2.adoc#column-repounderlineseedunderlinevalue[+repo.RepoObjectColumn_gross2.Repo_seed_value+]
--


[#column-repounderlineuserunderlinetypeunderlinefullname]
=== Repo_user_type_fullname

[cols="d,8a,m,m,m"]
|===
|
|Repo_user_type_fullname
|nvarchar(128)
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobjectcolumn.adoc#column-repounderlineuserunderlinetypeunderlinefullname[+repo.RepoObjectColumn.Repo_user_type_fullname+]
--

.Referencing Columns
--
* xref:graph.repoobjectcolumn_s.adoc#column-repoobjectcolumnunderlinetype[+graph.RepoObjectColumn_S.RepoObjectColumn_type+]
* xref:property.repoobjectcolumnproperty_forupdate.adoc#column-repounderlineuserunderlinetypeunderlinefullname[+property.RepoObjectColumnProperty_ForUpdate.Repo_user_type_fullname+]
* xref:repo.repoobjectcolumn_gross2.adoc#column-repounderlineuserunderlinetypeunderlinefullname[+repo.RepoObjectColumn_gross2.Repo_user_type_fullname+]
--


[#column-repounderlineuserunderlinetypeunderlinename]
=== Repo_user_type_name

[cols="d,8a,m,m,m"]
|===
|
|Repo_user_type_name
|nvarchar(128)
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobjectcolumn.adoc#column-repounderlineuserunderlinetypeunderlinename[+repo.RepoObjectColumn.Repo_user_type_name+]
--

.Referencing Columns
--
* xref:repo.repoobjectcolumn_gross2.adoc#column-repounderlineuserunderlinetypeunderlinename[+repo.RepoObjectColumn_gross2.Repo_user_type_name+]
--


[#column-repounderlineusesunderlinedatabaseunderlinecollation]
=== Repo_uses_database_collation

[cols="d,8a,m,m,m"]
|===
|
|Repo_uses_database_collation
|bit
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobjectcolumn.adoc#column-repounderlineusesunderlinedatabaseunderlinecollation[+repo.RepoObjectColumn.Repo_uses_database_collation+]
--

.Referencing Columns
--
* xref:repo.repoobjectcolumn_gross2.adoc#column-repounderlineusesunderlinedatabaseunderlinecollation[+repo.RepoObjectColumn_gross2.Repo_uses_database_collation+]
--


[#column-repoobjectunderlinefullname]
=== RepoObject_fullname

[cols="d,8a,m,m,m"]
|===
|
|RepoObject_fullname
|nvarchar(261)
|NOT NULL
|
|===

.Description
--
(concat('[',[RepoObject_schema_name],'].[',[RepoObject_name],']'))
--
{empty} +

.Referenced Columns
--
* xref:repo.repoobject.adoc#column-repoobjectunderlinefullname[+repo.RepoObject.RepoObject_fullname+]
--

.Referencing Columns
--
* xref:graph.repoobjectcolumn_s.adoc#column-repoobjectunderlinefullname[+graph.RepoObjectColumn_S.RepoObject_fullname+]
* xref:property.repoobjectcolumnproperty_forupdate.adoc#column-repoobjectunderlinefullname[+property.RepoObjectColumnProperty_ForUpdate.RepoObject_fullname+]
* xref:repo.repoobjectcolumn_gross2.adoc#column-repoobjectunderlinefullname[+repo.RepoObjectColumn_gross2.RepoObject_fullname+]
--


[#column-repoobjectunderlinefullname2]
=== RepoObject_fullname2

[cols="d,8a,m,m,m"]
|===
|
|RepoObject_fullname2
|nvarchar(257)
|NOT NULL
|
|===

.Description
--
(concat([RepoObject_schema_name],'.',[RepoObject_name]))
--
{empty} +

.Referenced Columns
--
* xref:repo.repoobject.adoc#column-repoobjectunderlinefullname2[+repo.RepoObject.RepoObject_fullname2+]
--

.Referencing Columns
--
* xref:property.repoobjectcolumnproperty_forupdate.adoc#column-repoobjectunderlinefullname2[+property.RepoObjectColumnProperty_ForUpdate.RepoObject_fullname2+]
* xref:repo.repoobjectcolumn_gross2.adoc#column-repoobjectunderlinefullname2[+repo.RepoObjectColumn_gross2.RepoObject_fullname2+]
--


[#column-repoobjectunderlineguid]
=== RepoObject_guid

[cols="d,8a,m,m,m"]
|===
|
|RepoObject_guid
|uniqueidentifier
|NOT NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobjectcolumn.adoc#column-repoobjectunderlineguid[+repo.RepoObjectColumn.RepoObject_guid+]
--

.Referencing Columns
--
* xref:graph.repoobjectcolumn_s.adoc#column-repoobjectunderlineguid[+graph.RepoObjectColumn_S.RepoObject_guid+]
* xref:property.repoobjectcolumnproperty_forupdate.adoc#column-repoobjectunderlineguid[+property.RepoObjectColumnProperty_ForUpdate.RepoObject_guid+]
* xref:reference.repoobjectcolumn_reference_firstresultset.adoc#column-referencedunderlinerepoobjectunderlineguid[+reference.RepoObjectColumn_reference_FirstResultSet.referenced_RepoObject_guid+]
* xref:reference.repoobjectcolumn_reference_queryplan.adoc#column-referencedunderlinerepoobjectunderlineguid[+reference.RepoObjectColumn_reference_QueryPlan.referenced_RepoObject_guid+]
* xref:reference.repoobjectcolumn_reference_virtual.adoc#column-referencingunderlinerepoobjectunderlineguid[+reference.RepoObjectColumn_reference_virtual.referencing_RepoObject_guid+]
* xref:reference.repoobjectcolumn_reference_virtual.adoc#column-referencedunderlinerepoobjectunderlineguid[+reference.RepoObjectColumn_reference_virtual.referenced_RepoObject_guid+]
* xref:repo.repoobjectcolumn_gross2.adoc#column-repoobjectunderlineguid[+repo.RepoObjectColumn_gross2.RepoObject_guid+]
--


[#column-repoobjectunderlinename]
=== RepoObject_name

[cols="d,8a,m,m,m"]
|===
|
|RepoObject_name
|nvarchar(128)
|NOT NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject.adoc#column-repoobjectunderlinename[+repo.RepoObject.RepoObject_name+]
--

.Referencing Columns
--
* xref:property.repoobjectcolumnproperty_forupdate.adoc#column-repoobjectunderlinename[+property.RepoObjectColumnProperty_ForUpdate.RepoObject_name+]
* xref:repo.repoobjectcolumn_gross2.adoc#column-repoobjectunderlinename[+repo.RepoObjectColumn_gross2.RepoObject_name+]
* xref:ssas.repoobjectcolumn_translation.adoc#column-repoobjectunderlinename[+ssas.RepoObjectColumn_translation.RepoObject_name+]
--


[#column-repoobjectunderlinereferencingunderlinecount]
=== RepoObject_Referencing_Count

[cols="d,8a,m,m,m"]
|===
|
|RepoObject_Referencing_Count
|int
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject.adoc#column-repoobjectunderlinereferencingunderlinecount[+repo.RepoObject.RepoObject_Referencing_Count+]
--

.Referencing Columns
--
* xref:repo.repoobjectcolumn_gross2.adoc#column-repoobjectunderlinereferencingunderlinecount[+repo.RepoObjectColumn_gross2.RepoObject_Referencing_Count+]
--


[#column-repoobjectunderlineschemaunderlinename]
=== RepoObject_schema_name

[cols="d,8a,m,m,m"]
|===
|
|RepoObject_schema_name
|nvarchar(128)
|NOT NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject.adoc#column-repoobjectunderlineschemaunderlinename[+repo.RepoObject.RepoObject_schema_name+]
--

.Referencing Columns
--
* xref:property.repoobjectcolumnproperty_forupdate.adoc#column-repoobjectunderlineschemaunderlinename[+property.RepoObjectColumnProperty_ForUpdate.RepoObject_schema_name+]
* xref:repo.repoobjectcolumn_gross2.adoc#column-repoobjectunderlineschemaunderlinename[+repo.RepoObjectColumn_gross2.RepoObject_schema_name+]
* xref:ssas.repoobjectcolumn_translation.adoc#column-repoobjectunderlineschemaunderlinename[+ssas.RepoObjectColumn_translation.RepoObject_schema_name+]
--


[#column-repoobjectunderlinetype]
=== RepoObject_type

[cols="d,8a,m,m,m"]
|===
|
|RepoObject_type
|char(2)
|NOT NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject.adoc#column-repoobjectunderlinetype[+repo.RepoObject.RepoObject_type+]
--

.Referencing Columns
--
* xref:graph.repoobjectcolumn_s.adoc#column-repoobjectunderlinetype[+graph.RepoObjectColumn_S.RepoObject_type+]
* xref:property.repoobjectcolumnproperty_forupdate.adoc#column-repoobjectunderlinetype[+property.RepoObjectColumnProperty_ForUpdate.RepoObject_type+]
* xref:repo.repoobjectcolumn_gross2.adoc#column-repoobjectunderlinetype[+repo.RepoObjectColumn_gross2.RepoObject_type+]
--


[#column-repoobjectcolumnunderlinecolumnunderlineid]
=== RepoObjectColumn_column_id

[cols="d,8a,m,m,m"]
|===
|
|RepoObjectColumn_column_id
|int
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobjectcolumn.adoc#column-repoobjectcolumnunderlinecolumnunderlineid[+repo.RepoObjectColumn.RepoObjectColumn_column_id+]
--

.Referencing Columns
--
* xref:repo.repoobjectcolumn_gross2.adoc#column-repoobjectcolumnunderlinecolumnunderlineid[+repo.RepoObjectColumn_gross2.RepoObjectColumn_column_id+]
--


[#column-repoobjectcolumnunderlinefullname]
=== RepoObjectColumn_fullname

[cols="d,8a,m,m,m"]
|===
|
|RepoObjectColumn_fullname
|nvarchar(520)
|NOT NULL
|
|===

.Referencing Columns
--
* xref:graph.repoobjectcolumn_s.adoc#column-repoobjectcolumnunderlinefullname[+graph.RepoObjectColumn_S.RepoObjectColumn_fullname+]
* xref:property.repoobjectcolumnproperty_forupdate.adoc#column-repoobjectcolumnunderlinefullname[+property.RepoObjectColumnProperty_ForUpdate.RepoObjectColumn_fullname+]
* xref:repo.repoobjectcolumn_gross2.adoc#column-repoobjectcolumnunderlinefullname[+repo.RepoObjectColumn_gross2.RepoObjectColumn_fullname+]
--


[#column-repoobjectcolumnunderlinefullname2]
=== RepoObjectColumn_fullname2

[cols="d,8a,m,m,m"]
|===
|
|RepoObjectColumn_fullname2
|nvarchar(386)
|NOT NULL
|
|===

.Referencing Columns
--
* xref:property.repoobjectcolumnproperty_forupdate.adoc#column-repoobjectcolumnunderlinefullname2[+property.RepoObjectColumnProperty_ForUpdate.RepoObjectColumn_fullname2+]
* xref:repo.repoobjectcolumn_gross2.adoc#column-repoobjectcolumnunderlinefullname2[+repo.RepoObjectColumn_gross2.RepoObjectColumn_fullname2+]
--


[#column-repoobjectcolumnunderlineguid]
=== RepoObjectColumn_guid

[cols="d,8a,m,m,m"]
|===
|
|RepoObjectColumn_guid
|uniqueidentifier
|NOT NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobjectcolumn.adoc#column-repoobjectcolumnunderlineguid[+repo.RepoObjectColumn.RepoObjectColumn_guid+]
--

.Referencing Columns
--
* xref:graph.repoobjectcolumn_s.adoc#column-repoobjectcolumnunderlineguid[+graph.RepoObjectColumn_S.RepoObjectColumn_guid+]
* xref:reference.repoobjectcolumn_reference_firstresultset.adoc#column-referencingunderlinerepoobjectcolumnunderlineguid[+reference.RepoObjectColumn_reference_FirstResultSet.referencing_RepoObjectColumn_guid+]
* xref:reference.repoobjectcolumn_reference_firstresultset.adoc#column-referencedunderlinerepoobjectcolumnunderlineguid[+reference.RepoObjectColumn_reference_FirstResultSet.referenced_RepoObjectColumn_guid+]
* xref:reference.repoobjectcolumn_reference_queryplan.adoc#column-referencingunderlinerepoobjectcolumnunderlineguid[+reference.RepoObjectColumn_reference_QueryPlan.referencing_RepoObjectColumn_guid+]
* xref:reference.repoobjectcolumn_reference_queryplan.adoc#column-referencedunderlinerepoobjectcolumnunderlineguid[+reference.RepoObjectColumn_reference_QueryPlan.referenced_RepoObjectColumn_guid+]
* xref:reference.repoobjectcolumn_reference_virtual.adoc#column-referencingunderlinerepoobjectcolumnunderlineguid[+reference.RepoObjectColumn_reference_virtual.referencing_RepoObjectColumn_guid+]
* xref:reference.repoobjectcolumn_reference_virtual.adoc#column-referencedunderlinerepoobjectcolumnunderlineguid[+reference.RepoObjectColumn_reference_virtual.referenced_RepoObjectColumn_guid+]
* xref:repo.repoobjectcolumn_gross2.adoc#column-repoobjectcolumnunderlineguid[+repo.RepoObjectColumn_gross2.RepoObjectColumn_guid+]
* xref:ssas.repoobjectcolumn_translation.adoc#column-repoobjectcolumnunderlineguid[+ssas.RepoObjectColumn_translation.RepoObjectColumn_guid+]
--


[#column-repoobjectcolumnunderlinename]
=== RepoObjectColumn_name

[cols="d,8a,m,m,m"]
|===
|
|RepoObjectColumn_name
|nvarchar(128)
|NOT NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobjectcolumn.adoc#column-repoobjectcolumnunderlinename[+repo.RepoObjectColumn.RepoObjectColumn_name+]
--

.Referencing Columns
--
* xref:graph.repoobjectcolumn_s.adoc#column-repoobjectcolumnunderlinename[+graph.RepoObjectColumn_S.RepoObjectColumn_name+]
* xref:property.repoobjectcolumnproperty_forupdate.adoc#column-repoobjectcolumnunderlinename[+property.RepoObjectColumnProperty_ForUpdate.RepoObjectColumn_name+]
* xref:repo.repoobjectcolumn_gross2.adoc#column-repoobjectcolumnunderlinename[+repo.RepoObjectColumn_gross2.RepoObjectColumn_name+]
--


[#column-sysobjectunderlinefullname]
=== SysObject_fullname

[cols="d,8a,m,m,m"]
|===
|
|SysObject_fullname
|nvarchar(261)
|NOT NULL
|
|===

.Description
--
(concat('[',[SysObject_schema_name],'].[',[SysObject_name],']'))
--
{empty} +

.Referenced Columns
--
* xref:repo.repoobject.adoc#column-sysobjectunderlinefullname[+repo.RepoObject.SysObject_fullname+]
--

.Referencing Columns
--
* xref:repo.repoobjectcolumn_gross2.adoc#column-sysobjectunderlinefullname[+repo.RepoObjectColumn_gross2.SysObject_fullname+]
--


[#column-sysobjectunderlinefullname2]
=== SysObject_fullname2

[cols="d,8a,m,m,m"]
|===
|
|SysObject_fullname2
|nvarchar(257)
|NOT NULL
|
|===

.Description
--
(concat([SysObject_schema_name],'.',[SysObject_name]))
--
{empty} +

.Referenced Columns
--
* xref:repo.repoobject.adoc#column-sysobjectunderlinefullname2[+repo.RepoObject.SysObject_fullname2+]
--

.Referencing Columns
--
* xref:repo.repoobjectcolumn_gross2.adoc#column-sysobjectunderlinefullname2[+repo.RepoObjectColumn_gross2.SysObject_fullname2+]
--


[#column-sysobjectunderlineid]
=== SysObject_id

[cols="d,8a,m,m,m"]
|===
|
|SysObject_id
|int
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject.adoc#column-sysobjectunderlineid[+repo.RepoObject.SysObject_id+]
--

.Referencing Columns
--
* xref:reference.repoobjectcolumn_reference_firstresultset.adoc#column-referencedunderlineid[+reference.RepoObjectColumn_reference_FirstResultSet.referenced_id+]
* xref:reference.repoobjectcolumn_reference_queryplan.adoc#column-referencedunderlineid[+reference.RepoObjectColumn_reference_QueryPlan.referenced_id+]
* xref:reference.repoobjectcolumn_reference_virtual.adoc#column-referencedunderlineid[+reference.RepoObjectColumn_reference_virtual.referenced_id+]
* xref:reference.repoobjectcolumn_reference_virtual.adoc#column-referencingunderlineid[+reference.RepoObjectColumn_reference_virtual.referencing_id+]
* xref:repo.repoobjectcolumn_gross2.adoc#column-sysobjectunderlineid[+repo.RepoObjectColumn_gross2.SysObject_id+]
--


[#column-sysobjectunderlinemodifyunderlinedate]
=== SysObject_modify_date

[cols="d,8a,m,m,m"]
|===
|
|SysObject_modify_date
|datetime
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject.adoc#column-sysobjectunderlinemodifyunderlinedate[+repo.RepoObject.SysObject_modify_date+]
--

.Referencing Columns
--
* xref:repo.repoobjectcolumn_gross2.adoc#column-sysobjectunderlinemodifyunderlinedate[+repo.RepoObjectColumn_gross2.SysObject_modify_date+]
--


[#column-sysobjectunderlinename]
=== SysObject_name

[cols="d,8a,m,m,m"]
|===
|
|SysObject_name
|nvarchar(128)
|NOT NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject.adoc#column-sysobjectunderlinename[+repo.RepoObject.SysObject_name+]
--

.Referencing Columns
--
* xref:reference.repoobjectcolumn_reference_queryplan.adoc#column-referencedunderlineentityunderlinename[+reference.RepoObjectColumn_reference_QueryPlan.referenced_entity_name+]
* xref:reference.repoobjectcolumn_reference_virtual.adoc#column-referencingunderlineentityunderlinename[+reference.RepoObjectColumn_reference_virtual.referencing_entity_name+]
* xref:reference.repoobjectcolumn_reference_virtual.adoc#column-referencedunderlineentityunderlinename[+reference.RepoObjectColumn_reference_virtual.referenced_entity_name+]
* xref:repo.repoobjectcolumn_gross2.adoc#column-sysobjectunderlinename[+repo.RepoObjectColumn_gross2.SysObject_name+]
--


[#column-sysobjectunderlineparentunderlineobjectunderlineid]
=== SysObject_parent_object_id

[cols="d,8a,m,m,m"]
|===
|
|SysObject_parent_object_id
|int
|NOT NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject.adoc#column-sysobjectunderlineparentunderlineobjectunderlineid[+repo.RepoObject.SysObject_parent_object_id+]
--

.Referencing Columns
--
* xref:repo.repoobjectcolumn_gross2.adoc#column-sysobjectunderlineparentunderlineobjectunderlineid[+repo.RepoObjectColumn_gross2.SysObject_parent_object_id+]
--


[#column-sysobjectunderlineschemaunderlinename]
=== SysObject_schema_name

[cols="d,8a,m,m,m"]
|===
|
|SysObject_schema_name
|nvarchar(128)
|NOT NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject.adoc#column-sysobjectunderlineschemaunderlinename[+repo.RepoObject.SysObject_schema_name+]
--

.Referencing Columns
--
* xref:reference.repoobjectcolumn_reference_queryplan.adoc#column-referencedunderlineschemaunderlinename[+reference.RepoObjectColumn_reference_QueryPlan.referenced_schema_name+]
* xref:reference.repoobjectcolumn_reference_virtual.adoc#column-referencingunderlineschemaunderlinename[+reference.RepoObjectColumn_reference_virtual.referencing_schema_name+]
* xref:reference.repoobjectcolumn_reference_virtual.adoc#column-referencedunderlineschemaunderlinename[+reference.RepoObjectColumn_reference_virtual.referenced_schema_name+]
* xref:repo.repoobjectcolumn_gross2.adoc#column-sysobjectunderlineschemaunderlinename[+repo.RepoObjectColumn_gross2.SysObject_schema_name+]
--


[#column-sysobjectunderlinetype]
=== SysObject_type

[cols="d,8a,m,m,m"]
|===
|
|SysObject_type
|char(2)
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject.adoc#column-sysobjectunderlinetype[+repo.RepoObject.SysObject_type+]
--

.Referencing Columns
--
* xref:reference.repoobjectcolumn_reference_firstresultset.adoc#column-referencedunderlinetype[+reference.RepoObjectColumn_reference_FirstResultSet.referenced_type+]
* xref:reference.repoobjectcolumn_reference_queryplan.adoc#column-referencedunderlinetype[+reference.RepoObjectColumn_reference_QueryPlan.referenced_type+]
* xref:reference.repoobjectcolumn_reference_virtual.adoc#column-referencingunderlinetype[+reference.RepoObjectColumn_reference_virtual.referencing_type+]
* xref:reference.repoobjectcolumn_reference_virtual.adoc#column-referencedunderlinetype[+reference.RepoObjectColumn_reference_virtual.referenced_type+]
* xref:repo.repoobjectcolumn_gross2.adoc#column-sysobjectunderlinetype[+repo.RepoObjectColumn_gross2.SysObject_type+]
--


[#column-sysobjectcolumnunderlinecolumnunderlineid]
=== SysObjectColumn_column_id

[cols="d,8a,m,m,m"]
|===
|
|SysObjectColumn_column_id
|int
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobjectcolumn.adoc#column-sysobjectcolumnunderlinecolumnunderlineid[+repo.RepoObjectColumn.SysObjectColumn_column_id+]
--

.Referencing Columns
--
* xref:reference.repoobjectcolumn_reference_firstresultset.adoc#column-referencingunderlineminorunderlineid[+reference.RepoObjectColumn_reference_FirstResultSet.referencing_minor_id+]
* xref:reference.repoobjectcolumn_reference_firstresultset.adoc#column-referencedunderlineminorunderlineid[+reference.RepoObjectColumn_reference_FirstResultSet.referenced_minor_id+]
* xref:reference.repoobjectcolumn_reference_queryplan.adoc#column-referencingunderlineminorunderlineid[+reference.RepoObjectColumn_reference_QueryPlan.referencing_minor_id+]
* xref:reference.repoobjectcolumn_reference_queryplan.adoc#column-referencedunderlineminorunderlineid[+reference.RepoObjectColumn_reference_QueryPlan.referenced_minor_id+]
* xref:reference.repoobjectcolumn_reference_virtual.adoc#column-referencedunderlineminorunderlineid[+reference.RepoObjectColumn_reference_virtual.referenced_minor_id+]
* xref:reference.repoobjectcolumn_reference_virtual.adoc#column-referencingunderlineminorunderlineid[+reference.RepoObjectColumn_reference_virtual.referencing_minor_id+]
* xref:repo.repoobjectcolumn_gross2.adoc#column-sysobjectcolumnunderlinecolumnunderlineid[+repo.RepoObjectColumn_gross2.SysObjectColumn_column_id+]
--


[#column-sysobjectcolumnunderlinename]
=== SysObjectColumn_name

[cols="d,8a,m,m,m"]
|===
|
|SysObjectColumn_name
|nvarchar(128)
|NOT NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobjectcolumn.adoc#column-sysobjectcolumnunderlinename[+repo.RepoObjectColumn.SysObjectColumn_name+]
--

.Referencing Columns
--
* xref:reference.repoobjectcolumn_reference_virtual.adoc#column-referencingunderlinecolumnunderlinename[+reference.RepoObjectColumn_reference_virtual.referencing_column_name+]
* xref:reference.repoobjectcolumn_reference_virtual.adoc#column-referencedunderlinecolumnunderlinename[+reference.RepoObjectColumn_reference_virtual.referenced_column_name+]
* xref:repo.repoobjectcolumn_gross2.adoc#column-sysobjectcolumnunderlinename[+repo.RepoObjectColumn_gross2.SysObjectColumn_name+]
--


[#column-tabcolunderlinedescription]
=== tabcol_Description

[cols="d,8a,m,m,m"]
|===
|
|tabcol_Description
|nvarchar(max)
|NULL
|
|===

.Referencing Columns
--
* xref:repo.repoobjectcolumn_gross2.adoc#column-tabcolunderlinedescription[+repo.RepoObjectColumn_gross2.tabcol_Description+]
--


[#column-tabcolunderlinedisplayfolder]
=== tabcol_DisplayFolder

[cols="d,8a,m,m,m"]
|===
|
|tabcol_DisplayFolder
|nvarchar(500)
|NULL
|
|===

.Referenced Columns
--
* xref:ssas.model_json_311_tables_columns_t.adoc#column-tablesunderlinecolumnsunderlinedisplayfolder[+ssas.model_json_311_tables_columns_T.tables_columns_displayFolder+]
--

.Referencing Columns
--
* xref:repo.repoobjectcolumn_gross2.adoc#column-tabcolunderlinedisplayfolder[+repo.RepoObjectColumn_gross2.tabcol_DisplayFolder+]
--


[#column-tabcolunderlineexpression]
=== tabcol_Expression

[cols="d,8a,m,m,m"]
|===
|
|tabcol_Expression
|nvarchar(max)
|NULL
|
|===

.Referencing Columns
--
* xref:repo.repoobjectcolumn_gross2.adoc#column-tabcolunderlineexpression[+repo.RepoObjectColumn_gross2.tabcol_Expression+]
--


[#column-tabcolunderlineformatstring]
=== tabcol_FormatString

[cols="d,8a,m,m,m"]
|===
|
|tabcol_FormatString
|nvarchar(500)
|NULL
|
|===

.Referenced Columns
--
* xref:ssas.model_json_311_tables_columns_t.adoc#column-tablesunderlinecolumnsunderlineformatstring[+ssas.model_json_311_tables_columns_T.tables_columns_formatString+]
--

.Referencing Columns
--
* xref:repo.repoobjectcolumn_gross2.adoc#column-tabcolunderlineformatstring[+repo.RepoObjectColumn_gross2.tabcol_FormatString+]
--


[#column-tabcolunderlineishidden]
=== tabcol_IsHidden

[cols="d,8a,m,m,m"]
|===
|
|tabcol_IsHidden
|bit
|NOT NULL
|
|===

.Referencing Columns
--
* xref:repo.repoobjectcolumn_gross2.adoc#column-tabcolunderlineishidden[+repo.RepoObjectColumn_gross2.tabcol_IsHidden+]
* xref:ssas.repoobjectcolumn_translation.adoc#column-tabcolunderlineishidden[+ssas.RepoObjectColumn_translation.tabcol_IsHidden+]
--


[#column-tabcolunderlineiskey]
=== tabcol_IsKey

[cols="d,8a,m,m,m"]
|===
|
|tabcol_IsKey
|bit
|NOT NULL
|
|===

.Referencing Columns
--
* xref:repo.repoobjectcolumn_gross2.adoc#column-tabcolunderlineiskey[+repo.RepoObjectColumn_gross2.tabcol_IsKey+]
--


[#column-tabcolunderlineisunique]
=== tabcol_IsUnique

[cols="d,8a,m,m,m"]
|===
|
|tabcol_IsUnique
|bit
|NOT NULL
|
|===

.Referencing Columns
--
* xref:repo.repoobjectcolumn_gross2.adoc#column-tabcolunderlineisunique[+repo.RepoObjectColumn_gross2.tabcol_IsUnique+]
--


[#column-tabcolunderlinesummarizeby]
=== tabcol_SummarizeBy

[cols="d,8a,m,m,m"]
|===
|
|tabcol_SummarizeBy
|nvarchar(500)
|NULL
|
|===

.Referenced Columns
--
* xref:ssas.model_json_311_tables_columns_t.adoc#column-tablesunderlinecolumnsunderlinesummarizeby[+ssas.model_json_311_tables_columns_T.tables_columns_summarizeBy+]
--

.Referencing Columns
--
* xref:repo.repoobjectcolumn_gross2.adoc#column-tabcolunderlinesummarizeby[+repo.RepoObjectColumn_gross2.tabcol_SummarizeBy+]
--


[#column-tabcolunderlinetype]
=== tabcol_Type

[cols="d,8a,m,m,m"]
|===
|
|tabcol_Type
|nvarchar(500)
|NULL
|
|===

.Referenced Columns
--
* xref:ssas.model_json_311_tables_columns_t.adoc#column-tablesunderlinecolumnsunderlinetype[+ssas.model_json_311_tables_columns_T.tables_columns_type+]
--

.Referencing Columns
--
* xref:repo.repoobjectcolumn_gross2.adoc#column-tabcolunderlinetype[+repo.RepoObjectColumn_gross2.tabcol_Type+]
--


// end::AntoraColumnDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]











































































// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]
|
|<<column-columnunderlinename>>
|nvarchar(128)
|NOT NULL
|

|
|<<column-description>>
|nvarchar(max)
|NULL
|

|
|<<column-hasunderlinedifferentunderlinesysunderlinenames>>
|bit
|NULL
|

|
|<<column-hasunderlinegetunderlinereferencedunderlineissue>>
|bit
|NULL
|

|
|<<column-inheritanceunderlinestringaggseparatorsql>>
|nvarchar(4000)
|NULL
|

|
|<<column-inheritancedefinition>>
|nvarchar(4000)
|NULL
|

|
|<<column-inheritancetype>>
|tinyint
|NULL
|

|
|<<column-isunderlineexternal>>
|bit
|NOT NULL
|

|
|<<column-isunderlinepersistenceunderlineignore>>
|bit
|NULL
|

|
|<<column-isunderlinepersistenceunderlinenocomparebutupdate>>
|bit
|NULL
|

|
|<<column-isunderlinepersistenceunderlinenocomparenoupdate>>
|bit
|NULL
|

|
|<<column-isunderlinepersistenceunderlinenoinsert>>
|bit
|NULL
|

|
|<<column-isunderlinequeryunderlineplanunderlineexpression>>
|bit
|NULL
|

|
|<<column-isunderlinerepounderlinemanaged>>
|bit
|NULL
|

|
|<<column-isunderlinerepoobjectunderlinenameunderlineuniqueidentifier>>
|int
|NOT NULL
|

|
|<<column-isunderlinerepoobjectcolumnunderlinenameunderlineuniqueidentifier>>
|int
|NOT NULL
|

|
|<<column-isunderlinerequiredunderlinecolumnmerge>>
|bit
|NULL
|

|
|<<column-isunderlinessas>>
|bit
|NOT NULL
|

|
|<<column-isunderlinesysobjectunderlinemissing>>
|bit
|NULL
|

|
|<<column-isunderlinesysobjectunderlinenameunderlineuniqueidentifier>>
|int
|NOT NULL
|

|
|<<column-isunderlinesysobjectcolumnunderlinemissing>>
|bit
|NULL
|

|
|<<column-isunderlinesysobjectcolumnunderlinenameunderlineuniqueidentifier>>
|int
|NOT NULL
|

|
|<<column-modifyunderlinedt>>
|datetime
|NOT NULL
|

|
|<<column-nodeunderlineid>>
|bigint
|NULL
|

|
|<<column-persistenceunderlinesourceunderlinerepoobjectunderlineguid>>
|uniqueidentifier
|NULL
|

|
|<<column-persistenceunderlinesourceunderlinerepoobjectcolumnunderlineguid>>
|uniqueidentifier
|NULL
|

|
|<<column-pkunderlineindexunderlineguid>>
|uniqueidentifier
|NULL
|

|
|<<column-propertyunderlinemsunderlinedescription>>
|nvarchar(4000)
|NULL
|

|
|<<column-referencingunderlinecount>>
|int
|NULL
|

|
|<<column-repounderlinedefaultunderlinedefinition>>
|nvarchar(max)
|NULL
|

|
|<<column-repounderlinedefaultunderlineisunderlinesystemunderlinenamed>>
|bit
|NULL
|

|
|<<column-repounderlinedefaultunderlinename>>
|nvarchar(128)
|NULL
|

|
|<<column-repounderlinedefinition>>
|nvarchar(max)
|NULL
|

|
|<<column-repounderlinegeneratedunderlinealwaysunderlinetype>>
|tinyint
|NOT NULL
|

|
|<<column-repounderlinegraphunderlinetype>>
|int
|NULL
|

|
|<<column-repounderlineincrementunderlinevalue>>
|sql_variant
|NULL
|

|
|<<column-repounderlineisunderlinecomputed>>
|bit
|NOT NULL
|

|
|<<column-repounderlineisunderlineidentity>>
|bit
|NOT NULL
|

|
|<<column-repounderlineisunderlinenullable>>
|bit
|NULL
|

|
|<<column-repounderlineisunderlinepersisted>>
|bit
|NULL
|

|
|<<column-repounderlineseedunderlinevalue>>
|sql_variant
|NULL
|

|
|<<column-repounderlineuserunderlinetypeunderlinefullname>>
|nvarchar(128)
|NULL
|

|
|<<column-repounderlineuserunderlinetypeunderlinename>>
|nvarchar(128)
|NULL
|

|
|<<column-repounderlineusesunderlinedatabaseunderlinecollation>>
|bit
|NULL
|

|
|<<column-repoobjectunderlinefullname>>
|nvarchar(261)
|NOT NULL
|

|
|<<column-repoobjectunderlinefullname2>>
|nvarchar(257)
|NOT NULL
|

|
|<<column-repoobjectunderlineguid>>
|uniqueidentifier
|NOT NULL
|

|
|<<column-repoobjectunderlinename>>
|nvarchar(128)
|NOT NULL
|

|
|<<column-repoobjectunderlinereferencingunderlinecount>>
|int
|NULL
|

|
|<<column-repoobjectunderlineschemaunderlinename>>
|nvarchar(128)
|NOT NULL
|

|
|<<column-repoobjectunderlinetype>>
|char(2)
|NOT NULL
|

|
|<<column-repoobjectcolumnunderlinecolumnunderlineid>>
|int
|NULL
|

|
|<<column-repoobjectcolumnunderlinefullname>>
|nvarchar(520)
|NOT NULL
|

|
|<<column-repoobjectcolumnunderlinefullname2>>
|nvarchar(386)
|NOT NULL
|

|
|<<column-repoobjectcolumnunderlineguid>>
|uniqueidentifier
|NOT NULL
|

|
|<<column-repoobjectcolumnunderlinename>>
|nvarchar(128)
|NOT NULL
|

|
|<<column-sysobjectunderlinefullname>>
|nvarchar(261)
|NOT NULL
|

|
|<<column-sysobjectunderlinefullname2>>
|nvarchar(257)
|NOT NULL
|

|
|<<column-sysobjectunderlineid>>
|int
|NULL
|

|
|<<column-sysobjectunderlinemodifyunderlinedate>>
|datetime
|NULL
|

|
|<<column-sysobjectunderlinename>>
|nvarchar(128)
|NOT NULL
|

|
|<<column-sysobjectunderlineparentunderlineobjectunderlineid>>
|int
|NOT NULL
|

|
|<<column-sysobjectunderlineschemaunderlinename>>
|nvarchar(128)
|NOT NULL
|

|
|<<column-sysobjectunderlinetype>>
|char(2)
|NULL
|

|
|<<column-sysobjectcolumnunderlinecolumnunderlineid>>
|int
|NULL
|

|
|<<column-sysobjectcolumnunderlinename>>
|nvarchar(128)
|NOT NULL
|

|
|<<column-tabcolunderlinedescription>>
|nvarchar(max)
|NULL
|

|
|<<column-tabcolunderlinedisplayfolder>>
|nvarchar(500)
|NULL
|

|
|<<column-tabcolunderlineexpression>>
|nvarchar(max)
|NULL
|

|
|<<column-tabcolunderlineformatstring>>
|nvarchar(500)
|NULL
|

|
|<<column-tabcolunderlineishidden>>
|bit
|NOT NULL
|

|
|<<column-tabcolunderlineiskey>>
|bit
|NOT NULL
|

|
|<<column-tabcolunderlineisunique>>
|bit
|NOT NULL
|

|
|<<column-tabcolunderlinesummarizeby>>
|nvarchar(500)
|NULL
|

|
|<<column-tabcolunderlinetype>>
|nvarchar(500)
|NULL
|

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

[#index-idxunderlinerepoobjectcolumnunderlinegrossunderlineunderline1]
=== idx_RepoObjectColumn_gross++__++1

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-SysObject_schema_name>>; nvarchar(128)
* <<column-SysObject_name>>; nvarchar(128)
--
* PK, Unique, Real: 0, 0, 0


[#index-idxunderlinerepoobjectcolumnunderlinegrossunderlineunderline2]
=== idx_RepoObjectColumn_gross++__++2

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-RepoObject_schema_name>>; nvarchar(128)
* <<column-RepoObject_name>>; nvarchar(128)
--
* PK, Unique, Real: 0, 0, 0


[#index-idxunderlinerepoobjectcolumnunderlinegrossunderlineunderline3]
=== idx_RepoObjectColumn_gross++__++3

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-RepoObjectColumn_guid>>; uniqueidentifier
--
* PK, Unique, Real: 0, 0, 0


[#index-idxunderlinerepoobjectcolumnunderlinegrossunderlineunderline4]
=== idx_RepoObjectColumn_gross++__++4

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-RepoObjectColumn_guid>>; uniqueidentifier
* <<column-SysObjectColumn_name>>; nvarchar(128)
--
* PK, Unique, Real: 0, 0, 0


[#index-idxunderlinerepoobjectcolumnunderlinegrossunderlineunderline5]
=== idx_RepoObjectColumn_gross++__++5

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-RepoObject_guid>>; uniqueidentifier
* <<column-RepoObjectColumn_name>>; nvarchar(128)
--
* PK, Unique, Real: 0, 0, 0


[#index-idxunderlinerepoobjectcolumnunderlinegrossunderlineunderline6]
=== idx_RepoObjectColumn_gross++__++6

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-pk_index_guid>>; uniqueidentifier
--
* PK, Unique, Real: 0, 0, 0


[#index-idxunderlinerepoobjectcolumnunderlinegrossunderlineunderline7]
=== idx_RepoObjectColumn_gross++__++7

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-RepoObject_guid>>; uniqueidentifier
--
* PK, Unique, Real: 0, 0, 0

// end::AntoraIndexList[]

== AntoraMeasureDetails

// tag::AntoraMeasureDetails[]

// end::AntoraMeasureDetails[]

== AntoraMeasureDescriptions



== AntoraParameterList

// tag::AntoraParameterList[]

// end::AntoraParameterList[]

== AntoraXrefCulturesList

// tag::AntoraXrefCulturesList[]
* xref:dhw:sqldb:repo.repoobjectcolumn_gross.adoc[] - 
// end::AntoraXrefCulturesList[]

== cultures_count

// tag::cultures_count[]
1
// end::cultures_count[]

== Other tags

source: property.RepoObjectProperty_cross As rop_cross


=== additional_reference_csv

// tag::additional_reference_csv[]

// end::additional_reference_csv[]


=== AdocUspSteps

// tag::adocuspsteps[]

// end::adocuspsteps[]


=== AntoraReferencedList

// tag::antorareferencedlist[]
* xref:dhw:sqldb:property.fs_get_repoobjectcolumnproperty_nvarchar.adoc[]
* xref:dhw:sqldb:repo.repoobject.adoc[]
* xref:dhw:sqldb:repo.repoobject_persistence.adoc[]
* xref:dhw:sqldb:repo.repoobjectcolumn.adoc[]
* xref:dhw:sqldb:ssas.model_json_311_tables_columns_t.adoc[]
* xref:dhw:sqldb:ssas.model_json_31111_tables_columns_descriptions_stragg.adoc[]
* xref:dhw:sqldb:ssas.model_json_31121_tables_columns_expressions_stragg.adoc[]
// end::antorareferencedlist[]


=== AntoraReferencingList

// tag::antorareferencinglist[]
* xref:dhw:sqldb:docs.unit_1_union.adoc[]
* xref:dhw:sqldb:graph.repoobjectcolumn_s.adoc[]
* xref:dhw:sqldb:property.repoobjectcolumnproperty_forupdate.adoc[]
* xref:dhw:sqldb:reference.repoobjectcolumn_reference_firstresultset.adoc[]
* xref:dhw:sqldb:reference.repoobjectcolumn_reference_queryplan.adoc[]
* xref:dhw:sqldb:reference.repoobjectcolumn_reference_virtual.adoc[]
* xref:dhw:sqldb:reference.usp_repoobjectcolumnsource_virtual_set.adoc[]
* xref:dhw:sqldb:repo.repoobjectcolumn_gross2.adoc[]
* xref:dhw:sqldb:repo.usp_sync_guid_repoobjectcolumn.adoc[]
* xref:dhw:sqldb:ssas.repoobjectcolumn_translation.adoc[]
// end::antorareferencinglist[]


=== Description

// tag::description[]

// end::description[]


=== exampleUsage

// tag::exampleusage[]

// end::exampleusage[]


=== exampleUsage_2

// tag::exampleusage_2[]

// end::exampleusage_2[]


=== exampleUsage_3

// tag::exampleusage_3[]

// end::exampleusage_3[]


=== exampleUsage_4

// tag::exampleusage_4[]

// end::exampleusage_4[]


=== exampleUsage_5

// tag::exampleusage_5[]

// end::exampleusage_5[]


=== exampleWrong_Usage

// tag::examplewrong_usage[]

// end::examplewrong_usage[]


=== has_execution_plan_issue

// tag::has_execution_plan_issue[]
1
// end::has_execution_plan_issue[]


=== has_get_referenced_issue

// tag::has_get_referenced_issue[]

// end::has_get_referenced_issue[]


=== has_history

// tag::has_history[]

// end::has_history[]


=== has_history_columns

// tag::has_history_columns[]

// end::has_history_columns[]


=== InheritanceType

// tag::inheritancetype[]

// end::inheritancetype[]


=== is_persistence

// tag::is_persistence[]

// end::is_persistence[]


=== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]

// end::is_persistence_check_duplicate_per_pk[]


=== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]

// end::is_persistence_check_for_empty_source[]


=== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]

// end::is_persistence_delete_changed[]


=== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]

// end::is_persistence_delete_missing[]


=== is_persistence_insert

// tag::is_persistence_insert[]

// end::is_persistence_insert[]


=== is_persistence_truncate

// tag::is_persistence_truncate[]

// end::is_persistence_truncate[]


=== is_persistence_update_changed

// tag::is_persistence_update_changed[]

// end::is_persistence_update_changed[]


=== is_repo_managed

// tag::is_repo_managed[]
0
// end::is_repo_managed[]


=== is_ssas

// tag::is_ssas[]
0
// end::is_ssas[]


=== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


=== MS_Description

// tag::ms_description[]

// end::ms_description[]


=== persistence_source_RepoObject_fullname

// tag::persistence_source_repoobject_fullname[]

// end::persistence_source_repoobject_fullname[]


=== persistence_source_RepoObject_fullname2

// tag::persistence_source_repoobject_fullname2[]

// end::persistence_source_repoobject_fullname2[]


=== persistence_source_RepoObject_guid

// tag::persistence_source_repoobject_guid[]

// end::persistence_source_repoobject_guid[]


=== persistence_source_RepoObject_xref

// tag::persistence_source_repoobject_xref[]

// end::persistence_source_repoobject_xref[]


=== pk_index_guid

// tag::pk_index_guid[]

// end::pk_index_guid[]


=== pk_IndexPatternColumnDatatype

// tag::pk_indexpatterncolumndatatype[]

// end::pk_indexpatterncolumndatatype[]


=== pk_IndexPatternColumnName

// tag::pk_indexpatterncolumnname[]

// end::pk_indexpatterncolumnname[]


=== pk_IndexSemanticGroup

// tag::pk_indexsemanticgroup[]

// end::pk_indexsemanticgroup[]


=== ReferencedObjectList

// tag::referencedobjectlist[]
* [property].[fs_get_RepoObjectColumnProperty_nvarchar]
* [repo].[RepoObject]
* [repo].[RepoObject_persistence]
* [repo].[RepoObjectColumn]
* [ssas].[model_json_311_tables_columns_T]
* [ssas].[model_json_31111_tables_columns_descriptions_StrAgg]
* [ssas].[model_json_31121_tables_columns_expressions_StrAgg]
// end::referencedobjectlist[]


=== usp_persistence_RepoObject_guid

// tag::usp_persistence_repoobject_guid[]

// end::usp_persistence_repoobject_guid[]


=== UspExamples

// tag::uspexamples[]

// end::uspexamples[]


=== uspgenerator_usp_id

// tag::uspgenerator_usp_id[]

// end::uspgenerator_usp_id[]


=== UspParameters

// tag::uspparameters[]

// end::uspparameters[]

== Boolean Attributes

source: property.RepoObjectProperty WHERE property_int = 1

// tag::boolean_attributes[]

:has_execution_plan_issue:

// end::boolean_attributes[]

== PlantUML diagrams

=== PlantUML Entity

// tag::puml_entity[]
[plantuml, entity-{docname}, svg, subs=macros]
....
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:repo.repoobjectcolumn_gross.adoc[]" as repo.RepoObjectColumn_gross << V >> {
  - Column_name : (nvarchar(128))
  Description : (nvarchar(max))
  has_different_sys_names : (bit)
  has_get_referenced_issue : (bit)
  Inheritance_StringAggSeparatorSql : (nvarchar(4000))
  InheritanceDefinition : (nvarchar(4000))
  InheritanceType : (tinyint)
  - is_external : (bit)
  is_persistence_Ignore : (bit)
  is_persistence_NoCompareButUpdate : (bit)
  is_persistence_NoCompareNoUpdate : (bit)
  is_persistence_NoInsert : (bit)
  is_query_plan_expression : (bit)
  is_repo_managed : (bit)
  - is_RepoObject_name_uniqueidentifier : (int)
  - is_RepoObjectColumn_name_uniqueidentifier : (int)
  is_required_ColumnMerge : (bit)
  - is_ssas : (bit)
  is_SysObject_missing : (bit)
  - is_SysObject_name_uniqueidentifier : (int)
  is_SysObjectColumn_missing : (bit)
  - is_SysObjectColumn_name_uniqueidentifier : (int)
  - modify_dt : (datetime)
  node_id : (bigint)
  persistence_source_RepoObject_guid : (uniqueidentifier)
  persistence_source_RepoObjectColumn_guid : (uniqueidentifier)
  pk_index_guid : (uniqueidentifier)
  Property_ms_description : (nvarchar(4000))
  Referencing_Count : (int)
  Repo_default_definition : (nvarchar(max))
  Repo_default_is_system_named : (bit)
  Repo_default_name : (nvarchar(128))
  Repo_definition : (nvarchar(max))
  - Repo_generated_always_type : (tinyint)
  Repo_graph_type : (int)
  Repo_increment_value : (sql_variant)
  - Repo_is_computed : (bit)
  - Repo_is_identity : (bit)
  Repo_is_nullable : (bit)
  Repo_is_persisted : (bit)
  Repo_seed_value : (sql_variant)
  Repo_user_type_fullname : (nvarchar(128))
  Repo_user_type_name : (nvarchar(128))
  Repo_uses_database_collation : (bit)
  - RepoObject_fullname : (nvarchar(261))
  - RepoObject_fullname2 : (nvarchar(257))
  - RepoObject_guid : (uniqueidentifier)
  - RepoObject_name : (nvarchar(128))
  RepoObject_Referencing_Count : (int)
  - RepoObject_schema_name : (nvarchar(128))
  - RepoObject_type : (char(2))
  RepoObjectColumn_column_id : (int)
  - RepoObjectColumn_fullname : (nvarchar(520))
  - RepoObjectColumn_fullname2 : (nvarchar(386))
  - RepoObjectColumn_guid : (uniqueidentifier)
  - RepoObjectColumn_name : (nvarchar(128))
  - SysObject_fullname : (nvarchar(261))
  - SysObject_fullname2 : (nvarchar(257))
  SysObject_id : (int)
  SysObject_modify_date : (datetime)
  - SysObject_name : (nvarchar(128))
  - SysObject_parent_object_id : (int)
  - SysObject_schema_name : (nvarchar(128))
  SysObject_type : (char(2))
  SysObjectColumn_column_id : (int)
  - SysObjectColumn_name : (nvarchar(128))
  tabcol_Description : (nvarchar(max))
  tabcol_DisplayFolder : (nvarchar(500))
  tabcol_Expression : (nvarchar(max))
  tabcol_FormatString : (nvarchar(500))
  - tabcol_IsHidden : (bit)
  - tabcol_IsKey : (bit)
  - tabcol_IsUnique : (bit)
  tabcol_SummarizeBy : (nvarchar(500))
  tabcol_Type : (nvarchar(500))
  --
}
....

// end::puml_entity[]

=== PlantUML Entity 1 1 FK

// tag::puml_entity_1_1_fk[]
[plantuml, entity_1_1_fk-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:repo.repoobjectcolumn_gross.adoc[]" as repo.RepoObjectColumn_gross << V >> {
- idx_RepoObjectColumn_gross__1

..
SysObject_schema_name; nvarchar(128)
SysObject_name; nvarchar(128)
--
- idx_RepoObjectColumn_gross__2

..
RepoObject_schema_name; nvarchar(128)
RepoObject_name; nvarchar(128)
--
- idx_RepoObjectColumn_gross__3

..
RepoObjectColumn_guid; uniqueidentifier
--
- idx_RepoObjectColumn_gross__4

..
RepoObjectColumn_guid; uniqueidentifier
SysObjectColumn_name; nvarchar(128)
--
- idx_RepoObjectColumn_gross__5

..
RepoObject_guid; uniqueidentifier
RepoObjectColumn_name; nvarchar(128)
--
- idx_RepoObjectColumn_gross__6

..
pk_index_guid; uniqueidentifier
--
- idx_RepoObjectColumn_gross__7

..
RepoObject_guid; uniqueidentifier
}



footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_fk[]

=== PlantUML 1 1 ObjectRef

// tag::puml_entity_1_1_objectref[]
[plantuml, entity_1_1_objectref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:docs.unit_1_union.adoc[]" as docs.Unit_1_union << V >> {
  --
}

entity "puml-link:dhw:sqldb:graph.repoobjectcolumn_s.adoc[]" as graph.RepoObjectColumn_S << V >> {
  --
}

entity "puml-link:dhw:sqldb:property.fs_get_repoobjectcolumnproperty_nvarchar.adoc[]" as property.fs_get_RepoObjectColumnProperty_nvarchar << FN >> {
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectcolumnproperty_forupdate.adoc[]" as property.RepoObjectColumnProperty_ForUpdate << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_reference_firstresultset.adoc[]" as reference.RepoObjectColumn_reference_FirstResultSet << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_reference_queryplan.adoc[]" as reference.RepoObjectColumn_reference_QueryPlan << V >> {
  **referencing_id** : (int)
  **referencing_minor_id** : (int)
  **referenced_id** : (int)
  **referenced_minor_id** : (int)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_reference_virtual.adoc[]" as reference.RepoObjectColumn_reference_virtual << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_repoobjectcolumnsource_virtual_set.adoc[]" as reference.usp_RepoObjectColumnSource_virtual_set << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject.adoc[]" as repo.RepoObject << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_persistence.adoc[]" as repo.RepoObject_persistence << U >> {
  - **target_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn.adoc[]" as repo.RepoObjectColumn << U >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn_gross.adoc[]" as repo.RepoObjectColumn_gross << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn_gross2.adoc[]" as repo.RepoObjectColumn_gross2 << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_sync_guid_repoobjectcolumn.adoc[]" as repo.usp_sync_guid_RepoObjectColumn << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_311_tables_columns_t.adoc[]" as ssas.model_json_311_tables_columns_T << U >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  - **tables_columns_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31111_tables_columns_descriptions_stragg.adoc[]" as ssas.model_json_31111_tables_columns_descriptions_StrAgg << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31121_tables_columns_expressions_stragg.adoc[]" as ssas.model_json_31121_tables_columns_expressions_StrAgg << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.repoobjectcolumn_translation.adoc[]" as ssas.RepoObjectColumn_translation << V >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  --
}

property.fs_get_RepoObjectColumnProperty_nvarchar <.. repo.RepoObjectColumn_gross
repo.RepoObject <.. repo.RepoObjectColumn_gross
repo.RepoObject_persistence <.. repo.RepoObjectColumn_gross
repo.RepoObjectColumn <.. repo.RepoObjectColumn_gross
repo.RepoObjectColumn_gross <.. docs.Unit_1_union
repo.RepoObjectColumn_gross <.. graph.RepoObjectColumn_S
repo.RepoObjectColumn_gross <.. property.RepoObjectColumnProperty_ForUpdate
repo.RepoObjectColumn_gross <.. reference.RepoObjectColumn_reference_FirstResultSet
repo.RepoObjectColumn_gross <.. reference.RepoObjectColumn_reference_QueryPlan
repo.RepoObjectColumn_gross <.. reference.RepoObjectColumn_reference_virtual
repo.RepoObjectColumn_gross <.. reference.usp_RepoObjectColumnSource_virtual_set
repo.RepoObjectColumn_gross <.. repo.RepoObjectColumn_gross2
repo.RepoObjectColumn_gross <.. repo.usp_sync_guid_RepoObjectColumn
repo.RepoObjectColumn_gross <.. ssas.RepoObjectColumn_translation
ssas.model_json_311_tables_columns_T <.. repo.RepoObjectColumn_gross
ssas.model_json_31111_tables_columns_descriptions_StrAgg <.. repo.RepoObjectColumn_gross
ssas.model_json_31121_tables_columns_expressions_StrAgg <.. repo.RepoObjectColumn_gross

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_objectref[]

=== PlantUML 30 0 ObjectRef

// tag::puml_entity_30_0_objectref[]
[plantuml, entity_30_0_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:config.ftv_get_parameter_value.adoc[]" as config.ftv_get_parameter_value << IF >> {
  --
}

entity "puml-link:dhw:sqldb:config.parameter.adoc[]" as config.Parameter << U >> {
  - **Parameter_name** : (varchar(100))
  - **sub_Parameter** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:configt.parameter_default.adoc[]" as configT.Parameter_default << V >> {
  - **Parameter_name** : (varchar(52))
  - **sub_Parameter** : (nvarchar(26))
  --
}

entity "puml-link:dhw:sqldb:property.external_repoobjectcolumnproperty.adoc[]" as property.external_RepoObjectColumnProperty << U >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.external_repoobjectproperty.adoc[]" as property.external_RepoObjectProperty << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.fs_get_repoobjectcolumnproperty_nvarchar.adoc[]" as property.fs_get_RepoObjectColumnProperty_nvarchar << FN >> {
  --
}

entity "puml-link:dhw:sqldb:property.propertyname_repoobject.adoc[]" as property.PropertyName_RepoObject << V >> {
  **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.propertyname_repoobject_t.adoc[]" as property.PropertyName_RepoObject_T << U >> {
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectcolumnproperty.adoc[]" as property.RepoObjectColumnProperty << U >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectcolumnproperty_external_src.adoc[]" as property.RepoObjectColumnProperty_external_src << V >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectcolumnproperty_external_tgt.adoc[]" as property.RepoObjectColumnProperty_external_tgt << V >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty.adoc[]" as property.RepoObjectProperty << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty_external_src.adoc[]" as property.RepoObjectProperty_external_src << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty_external_tgt.adoc[]" as property.RepoObjectProperty_external_tgt << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty_selectedpropertyname_split.adoc[]" as property.RepoObjectProperty_SelectedPropertyName_split << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference.adoc[]" as reference.additional_Reference << U >> {
  # **tik_hash_c** : (nvarchar(32))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_from_properties_src.adoc[]" as reference.additional_Reference_from_properties_src << V >> {
  **referenced_AntoraComponent** : (nvarchar(max))
  **referenced_AntoraModule** : (nvarchar(max))
  **referenced_Schema** : (nvarchar(max))
  **referenced_Object** : (nvarchar(max))
  **referenced_Column** : (nvarchar(max))
  **referencing_AntoraComponent** : (nvarchar(max))
  **referencing_AntoraModule** : (nvarchar(max))
  **referencing_Schema** : (nvarchar(max))
  **referencing_Object** : (nvarchar(max))
  **referencing_Column** : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_from_properties_tgt.adoc[]" as reference.additional_Reference_from_properties_tgt << V >> {
  - **referenced_AntoraComponent** : (nvarchar(128))
  - **referenced_AntoraModule** : (nvarchar(128))
  - **referenced_Schema** : (nvarchar(128))
  - **referenced_Object** : (nvarchar(128))
  **referenced_Column** : (nvarchar(128))
  - **referencing_AntoraComponent** : (nvarchar(128))
  - **referencing_AntoraModule** : (nvarchar(128))
  - **referencing_Schema** : (nvarchar(128))
  - **referencing_Object** : (nvarchar(128))
  **referencing_Column** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_from_ssas_src.adoc[]" as reference.additional_Reference_from_ssas_src << V >> {
  **referenced_AntoraComponent** : (nvarchar(128))
  **referenced_AntoraModule** : (nvarchar(128))
  **referenced_Schema** : (nvarchar(max))
  **referenced_Object** : (nvarchar(max))
  **referenced_Column** : (nvarchar(500))
  **referencing_AntoraComponent** : (nvarchar(max))
  **referencing_AntoraModule** : (nvarchar(max))
  - **referencing_Schema** : (nvarchar(128))
  - **referencing_Object** : (nvarchar(128))
  **referencing_Column** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_from_ssas_tgt.adoc[]" as reference.additional_Reference_from_ssas_tgt << V >> {
  - **referenced_AntoraComponent** : (nvarchar(128))
  - **referenced_AntoraModule** : (nvarchar(128))
  - **referenced_Schema** : (nvarchar(128))
  - **referenced_Object** : (nvarchar(128))
  **referenced_Column** : (nvarchar(128))
  - **referencing_AntoraComponent** : (nvarchar(128))
  - **referencing_AntoraModule** : (nvarchar(128))
  - **referencing_Schema** : (nvarchar(128))
  - **referencing_Object** : (nvarchar(128))
  **referencing_Column** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_is_external.adoc[]" as reference.additional_Reference_is_external << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_object.adoc[]" as reference.additional_Reference_Object << V >> {
  - **AntoraComponent** : (nvarchar(128))
  - **AntoraModule** : (nvarchar(128))
  - **SchemaName** : (nvarchar(128))
  - **ObjectName** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_object_t.adoc[]" as reference.additional_Reference_Object_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_objectcolumn.adoc[]" as reference.additional_Reference_ObjectColumn << V >> {
  - **AntoraComponent** : (nvarchar(128))
  - **AntoraModule** : (nvarchar(128))
  - **SchemaName** : (nvarchar(128))
  - **ObjectName** : (nvarchar(128))
  **ColumnName** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_objectcolumn_t.adoc[]" as reference.additional_Reference_ObjectColumn_T << U >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_wo_columns_from_properties_src.adoc[]" as reference.additional_Reference_wo_columns_from_properties_src << V >> {
  **referenced_AntoraComponent** : (nvarchar(max))
  **referenced_AntoraModule** : (nvarchar(max))
  **referenced_Schema** : (nvarchar(max))
  **referenced_Object** : (nvarchar(max))
  **referencing_AntoraComponent** : (nvarchar(max))
  **referencing_AntoraModule** : (nvarchar(max))
  **referencing_Schema** : (nvarchar(max))
  **referencing_Object** : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_wo_columns_from_properties_tgt.adoc[]" as reference.additional_Reference_wo_columns_from_properties_tgt << V >> {
  - **referenced_AntoraComponent** : (nvarchar(128))
  - **referenced_AntoraModule** : (nvarchar(128))
  - **referenced_Schema** : (nvarchar(128))
  - **referenced_Object** : (nvarchar(128))
  - **referencing_AntoraComponent** : (nvarchar(128))
  - **referencing_AntoraModule** : (nvarchar(128))
  - **referencing_Schema** : (nvarchar(128))
  - **referencing_Object** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject.adoc[]" as repo.RepoObject << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_external_src.adoc[]" as repo.RepoObject_external_src << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_external_tgt.adoc[]" as repo.RepoObject_external_tgt << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_persistence.adoc[]" as repo.RepoObject_persistence << U >> {
  - **target_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_ssas_src.adoc[]" as repo.RepoObject_SSAS_src << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_ssas_tgt.adoc[]" as repo.RepoObject_SSAS_tgt << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn.adoc[]" as repo.RepoObjectColumn << U >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn_external_src.adoc[]" as repo.RepoObjectColumn_external_src << V >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn_external_tgt.adoc[]" as repo.RepoObjectColumn_external_tgt << V >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn_gross.adoc[]" as repo.RepoObjectColumn_gross << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn_ssas_src.adoc[]" as repo.RepoObjectColumn_SSAS_src << V >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn_ssas_tgt.adoc[]" as repo.RepoObjectColumn_SSAS_tgt << V >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.reposchema.adoc[]" as repo.RepoSchema << U >> {
  - **RepoSchema_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.reposchema_ssas_src.adoc[]" as repo.RepoSchema_ssas_src << V >> {
  - **RepoSchema_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:repo.reposchema_ssas_tgt.adoc[]" as repo.RepoSchema_ssas_tgt << V >> {
  - **RepoSchema_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:ssas.additional_reference_step1.adoc[]" as ssas.additional_Reference_step1 << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json.adoc[]" as ssas.model_json << U >> {
  - **databasename** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_10.adoc[]" as ssas.model_json_10 << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_20.adoc[]" as ssas.model_json_20 << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_201_descriptions_multiline.adoc[]" as ssas.model_json_201_descriptions_multiline << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_2011_descriptions_stragg.adoc[]" as ssas.model_json_2011_descriptions_StrAgg << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31_tables.adoc[]" as ssas.model_json_31_tables << V >> {
  - **databasename** : (nvarchar(128))
  **tables_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31_tables_t.adoc[]" as ssas.model_json_31_tables_T << U >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_311_tables_columns.adoc[]" as ssas.model_json_311_tables_columns << V >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  **tables_columns_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_311_tables_columns_t.adoc[]" as ssas.model_json_311_tables_columns_T << U >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  - **tables_columns_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_3111_tables_columns_descriptions_multiline.adoc[]" as ssas.model_json_3111_tables_columns_descriptions_multiline << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31111_tables_columns_descriptions_stragg.adoc[]" as ssas.model_json_31111_tables_columns_descriptions_StrAgg << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_3112_tables_columns_expressions_multiline.adoc[]" as ssas.model_json_3112_tables_columns_expressions_multiline << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31121_tables_columns_expressions_stragg.adoc[]" as ssas.model_json_31121_tables_columns_expressions_StrAgg << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_313_tables_partitions.adoc[]" as ssas.model_json_313_tables_partitions << V >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  **tables_partitions_name** : (nvarchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_3131_tables_partitions_source.adoc[]" as ssas.model_json_3131_tables_partitions_source << V >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  **tables_partitions_name** : (nvarchar(500))
  **tables_partitions_source_name** : (nvarchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31311_tables_partitions_source_posfrom.adoc[]" as ssas.model_json_31311_tables_partitions_source_PosFrom << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_313111_tables_partitions_source_stringfrom.adoc[]" as ssas.model_json_313111_tables_partitions_source_StringFrom << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_3131111_tables_partitions_source_posdot.adoc[]" as ssas.model_json_3131111_tables_partitions_source_PosDot << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31311111_tables_partitions_source_part123.adoc[]" as ssas.model_json_31311111_tables_partitions_source_Part123 << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_33_datasources.adoc[]" as ssas.model_json_33_dataSources << V >> {
  - **databasename** : (nvarchar(128))
  **dataSources_name** : (nvarchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_33_datasources_t.adoc[]" as ssas.model_json_33_dataSources_T << U >> {
  - **databasename** : (nvarchar(128))
  - **dataSources_name** : (nvarchar(500))
  --
}

config.ftv_get_parameter_value <.. reference.additional_Reference_is_external
config.ftv_get_parameter_value <.. repo.RepoObject_external_src
config.ftv_get_parameter_value <.. ssas.additional_Reference_step1
config.Parameter <.. config.ftv_get_parameter_value
config.Parameter <.. property.PropertyName_RepoObject
configT.Parameter_default <.. config.Parameter
property.external_RepoObjectColumnProperty <.. property.RepoObjectColumnProperty_external_src
property.external_RepoObjectProperty <.. property.RepoObjectProperty_external_src
property.fs_get_RepoObjectColumnProperty_nvarchar <.. repo.RepoObjectColumn_gross
property.PropertyName_RepoObject <.. property.PropertyName_RepoObject_T
property.PropertyName_RepoObject_T <.. property.RepoObjectColumnProperty_external_tgt
property.PropertyName_RepoObject_T <.. property.RepoObjectProperty_external_tgt
property.RepoObjectColumnProperty <.. property.fs_get_RepoObjectColumnProperty_nvarchar
property.RepoObjectColumnProperty_external_src <.. property.RepoObjectColumnProperty_external_tgt
property.RepoObjectColumnProperty_external_tgt <.. property.RepoObjectColumnProperty
property.RepoObjectProperty <.. property.PropertyName_RepoObject
property.RepoObjectProperty <.. property.RepoObjectProperty_SelectedPropertyName_split
property.RepoObjectProperty_external_src <.. property.RepoObjectProperty_external_tgt
property.RepoObjectProperty_external_tgt <.. property.RepoObjectProperty
property.RepoObjectProperty_SelectedPropertyName_split <.. reference.additional_Reference_from_properties_src
property.RepoObjectProperty_SelectedPropertyName_split <.. reference.additional_Reference_wo_columns_from_properties_src
reference.additional_Reference <.. reference.additional_Reference_is_external
reference.additional_Reference_from_properties_src <.. reference.additional_Reference_from_properties_tgt
reference.additional_Reference_from_properties_tgt <.. reference.additional_Reference
reference.additional_Reference_from_ssas_src <.. reference.additional_Reference_from_ssas_tgt
reference.additional_Reference_from_ssas_tgt <.. reference.additional_Reference
reference.additional_Reference_is_external <.. reference.additional_Reference_Object
reference.additional_Reference_is_external <.. reference.additional_Reference_ObjectColumn
reference.additional_Reference_Object <.. reference.additional_Reference_Object_T
reference.additional_Reference_Object_T <.. repo.RepoObject_external_src
reference.additional_Reference_Object_T <.. repo.RepoObjectColumn_external_src
reference.additional_Reference_ObjectColumn <.. reference.additional_Reference_ObjectColumn_T
reference.additional_Reference_ObjectColumn_T <.. repo.RepoObjectColumn_external_src
reference.additional_Reference_wo_columns_from_properties_src <.. reference.additional_Reference_wo_columns_from_properties_tgt
reference.additional_Reference_wo_columns_from_properties_tgt <.. reference.additional_Reference
repo.RepoObject <.. property.RepoObjectColumnProperty_external_tgt
repo.RepoObject <.. property.RepoObjectProperty_external_tgt
repo.RepoObject <.. repo.RepoObject_external_src
repo.RepoObject <.. repo.RepoObjectColumn_external_src
repo.RepoObject <.. repo.RepoObjectColumn_gross
repo.RepoObject_external_src <.. repo.RepoObject_external_tgt
repo.RepoObject_external_tgt <.. repo.RepoObject
repo.RepoObject_external_tgt <.. repo.RepoObjectColumn_external_tgt
repo.RepoObject_persistence <.. repo.RepoObjectColumn_gross
repo.RepoObject_SSAS_src <.. repo.RepoObject_SSAS_tgt
repo.RepoObject_SSAS_tgt <.. repo.RepoObject
repo.RepoObject_SSAS_tgt <.. repo.RepoObjectColumn_SSAS_tgt
repo.RepoObjectColumn <.. property.RepoObjectColumnProperty_external_tgt
repo.RepoObjectColumn <.. repo.RepoObjectColumn_gross
repo.RepoObjectColumn_external_src <.. repo.RepoObjectColumn_external_tgt
repo.RepoObjectColumn_external_tgt <.. repo.RepoObjectColumn
repo.RepoObjectColumn_SSAS_src <.. repo.RepoObjectColumn_SSAS_tgt
repo.RepoObjectColumn_SSAS_tgt <.. repo.RepoObjectColumn
repo.RepoSchema <.. repo.RepoObject_SSAS_src
repo.RepoSchema_ssas_src <.. repo.RepoSchema_ssas_tgt
repo.RepoSchema_ssas_tgt <.. repo.RepoSchema
ssas.additional_Reference_step1 <.. reference.additional_Reference_from_ssas_src
ssas.model_json <.. ssas.model_json_10
ssas.model_json_10 <.. ssas.model_json_20
ssas.model_json_20 <.. repo.RepoSchema_ssas_src
ssas.model_json_20 <.. ssas.model_json_201_descriptions_multiline
ssas.model_json_20 <.. ssas.model_json_31_tables
ssas.model_json_20 <.. ssas.model_json_33_dataSources
ssas.model_json_201_descriptions_multiline <.. ssas.model_json_2011_descriptions_StrAgg
ssas.model_json_2011_descriptions_StrAgg <.. repo.RepoSchema_ssas_src
ssas.model_json_31_tables <.. ssas.model_json_31_tables_T
ssas.model_json_31_tables_T <.. repo.RepoObject_SSAS_src
ssas.model_json_31_tables_T <.. ssas.model_json_311_tables_columns
ssas.model_json_31_tables_T <.. ssas.model_json_313_tables_partitions
ssas.model_json_311_tables_columns <.. ssas.model_json_311_tables_columns_T
ssas.model_json_311_tables_columns_T <.. repo.RepoObjectColumn_gross
ssas.model_json_311_tables_columns_T <.. repo.RepoObjectColumn_SSAS_src
ssas.model_json_311_tables_columns_T <.. ssas.additional_Reference_step1
ssas.model_json_311_tables_columns_T <.. ssas.model_json_3111_tables_columns_descriptions_multiline
ssas.model_json_311_tables_columns_T <.. ssas.model_json_3112_tables_columns_expressions_multiline
ssas.model_json_3111_tables_columns_descriptions_multiline <.. ssas.model_json_31111_tables_columns_descriptions_StrAgg
ssas.model_json_31111_tables_columns_descriptions_StrAgg <.. repo.RepoObjectColumn_gross
ssas.model_json_3112_tables_columns_expressions_multiline <.. ssas.model_json_31121_tables_columns_expressions_StrAgg
ssas.model_json_31121_tables_columns_expressions_StrAgg <.. repo.RepoObjectColumn_gross
ssas.model_json_313_tables_partitions <.. ssas.model_json_3131_tables_partitions_source
ssas.model_json_3131_tables_partitions_source <.. ssas.model_json_31311_tables_partitions_source_PosFrom
ssas.model_json_31311_tables_partitions_source_PosFrom <.. ssas.model_json_313111_tables_partitions_source_StringFrom
ssas.model_json_313111_tables_partitions_source_StringFrom <.. ssas.model_json_3131111_tables_partitions_source_PosDot
ssas.model_json_3131111_tables_partitions_source_PosDot <.. ssas.model_json_31311111_tables_partitions_source_Part123
ssas.model_json_31311111_tables_partitions_source_Part123 <.. ssas.additional_Reference_step1
ssas.model_json_33_dataSources <.. ssas.model_json_33_dataSources_T
ssas.model_json_33_dataSources_T <.. ssas.additional_Reference_step1

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_30_0_objectref[]

=== PlantUML 0 30 ObjectRef

// tag::puml_entity_0_30_objectref[]
[plantuml, entity_0_30_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:dmdocs.unit.adoc[]" as dmdocs.unit << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.antoranavlistpage_by_schema.adoc[]" as docs.AntoraNavListPage_by_schema << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ftv_repoobject_reference_plantuml_entityreflist.adoc[]" as docs.ftv_RepoObject_Reference_PlantUml_EntityRefList << IF >> {
  --
}

entity "puml-link:dhw:sqldb:docs.objectrefcyclic.adoc[]" as docs.ObjectRefCyclic << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.objectrefcyclic_entitylist.adoc[]" as docs.ObjectRefCyclic_EntityList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_adoc.adoc[]" as docs.RepoObject_Adoc << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_adoc_t.adoc[]" as docs.RepoObject_Adoc_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_columnlist.adoc[]" as docs.RepoObject_ColumnList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_columnlist_t.adoc[]" as docs.RepoObject_ColumnList_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml.adoc[]" as docs.RepoObject_Plantuml << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_colreflist_1_1.adoc[]" as docs.RepoObject_Plantuml_ColRefList_1_1 << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_entity.adoc[]" as docs.RepoObject_Plantuml_Entity << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_entity_t.adoc[]" as docs.RepoObject_Plantuml_Entity_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_pumlentityfklist.adoc[]" as docs.RepoObject_PlantUml_PumlEntityFkList << V >> {
  **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_t.adoc[]" as docs.RepoObject_Plantuml_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.schema_entitylist.adoc[]" as docs.Schema_EntityList << V >> {
  - **RepoObject_schema_name** : (nvarchar(128))
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.schema_puml.adoc[]" as docs.Schema_puml << V >> {
  - **RepoSchema_guid** : (uniqueidentifier)
  **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.unit_1_union.adoc[]" as docs.Unit_1_union << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.unit_2.adoc[]" as docs.Unit_2 << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.unit_3.adoc[]" as docs.Unit_3 << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport.adoc[]" as docs.usp_AntoraExport << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_objectpartialscontent.adoc[]" as docs.usp_AntoraExport_ObjectPartialsContent << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_objectpuml.adoc[]" as docs.usp_AntoraExport_ObjectPuml << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_repoobject_adoc_t.adoc[]" as docs.usp_PERSIST_RepoObject_Adoc_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_repoobject_columnlist_t.adoc[]" as docs.usp_PERSIST_RepoObject_ColumnList_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_repoobject_plantuml_entity_t.adoc[]" as docs.usp_PERSIST_RepoObject_Plantuml_Entity_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_repoobject_plantuml_t.adoc[]" as docs.usp_PERSIST_RepoObject_Plantuml_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:graph.repoobjectcolumn_s.adoc[]" as graph.RepoObjectColumn_S << V >> {
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectcolumnproperty_forupdate.adoc[]" as property.RepoObjectColumnProperty_ForUpdate << V >> {
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty_collect_source_rogross.adoc[]" as property.RepoObjectProperty_Collect_source_ROGross << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **property_name** : (varchar(39))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty_collect_source_uspgenerator.adoc[]" as property.RepoObjectProperty_Collect_source_uspgenerator << V >> {
  **RepoObject_guid** : (uniqueidentifier)
  - **property_name** : (varchar(14))
  --
}

entity "puml-link:dhw:sqldb:property.usp_repoobject_inheritance.adoc[]" as property.usp_RepoObject_Inheritance << P >> {
  --
}

entity "puml-link:dhw:sqldb:property.usp_repoobjectproperty_collect.adoc[]" as property.usp_RepoObjectProperty_collect << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.ftv_repoobject_columreferencerepoobject.adoc[]" as reference.ftv_RepoObject_ColumReferenceRepoObject << IF >> {
  --
}

entity "puml-link:dhw:sqldb:reference.ftv_repoobject_dbmlcolumnrelation.adoc[]" as reference.ftv_RepoObject_DbmlColumnRelation << IF >> {
  --
}

entity "puml-link:dhw:sqldb:reference.ftv_repoobjectcolumn_referencetree.adoc[]" as reference.ftv_RepoObjectColumn_ReferenceTree << IF >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_reference.adoc[]" as reference.RepoObjectColumn_reference << V >> {
  **referenced_RepoObjectColumn_guid** : (uniqueidentifier)
  **referencing_RepoObjectColumn_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_reference_bysamepredecessors.adoc[]" as reference.RepoObjectColumn_reference_BySamePredecessors << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_reference_firstresultset.adoc[]" as reference.RepoObjectColumn_reference_FirstResultSet << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_reference_queryplan.adoc[]" as reference.RepoObjectColumn_reference_QueryPlan << V >> {
  **referencing_id** : (int)
  **referencing_minor_id** : (int)
  **referenced_id** : (int)
  **referenced_minor_id** : (int)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_reference_t.adoc[]" as reference.RepoObjectColumn_reference_T << U >> {
  - **referenced_RepoObjectColumn_guid** : (uniqueidentifier)
  - **referencing_RepoObjectColumn_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_reference_union.adoc[]" as reference.RepoObjectColumn_reference_union << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_reference_virtual.adoc[]" as reference.RepoObjectColumn_reference_virtual << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_referencedlist.adoc[]" as reference.RepoObjectColumn_ReferencedList << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_referencedreferencing.adoc[]" as reference.RepoObjectColumn_ReferencedReferencing << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_referencetree.adoc[]" as reference.RepoObjectColumn_ReferenceTree << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_referencinglist.adoc[]" as reference.RepoObjectColumn_ReferencingList << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_relationscript.adoc[]" as reference.RepoObjectColumn_RelationScript << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.sysobjectcolumn_queryplanexpression.adoc[]" as reference.SysObjectColumn_QueryPlanExpression << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_persist_repoobjectcolumn_reference_t.adoc[]" as reference.usp_PERSIST_RepoObjectColumn_reference_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_repoobjectcolumnsource_virtual_set.adoc[]" as reference.usp_RepoObjectColumnSource_virtual_set << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_repoobjectsource_queryplan.adoc[]" as reference.usp_RepoObjectSource_QueryPlan << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.check_indexcolumn_virtual_referenced_setpoint.adoc[]" as repo.check_IndexColumn_virtual_referenced_setpoint << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.index_referencing_indexpatterncolumnguid.adoc[]" as repo.Index_referencing_IndexPatternColumnGuid << V >> {
  **source_index_guid** : (uniqueidentifier)
  **referencing_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.indexcolumn_referencedreferencing_hasfullcolumnsinreferencing.adoc[]" as repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing << V >> {
  - **index_guid** : (uniqueidentifier)
  - **index_column_id** : (int)
  **RowNumberInReferencing** : (bigint)
  --
}

entity "puml-link:dhw:sqldb:repo.indexcolumn_referencedreferencing_hasfullcolumnsinreferencing_check.adoc[]" as repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_check << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.indexcolumn_referencedreferencing_hasfullcolumnsinreferencing_t.adoc[]" as repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T << U >> {
  **index_guid** : (uniqueidentifier)
  - **index_column_id** : (int)
  **RowNumberInReferencing** : (bigint)
  --
}

entity "puml-link:dhw:sqldb:repo.indexcolumn_virtual_referenced_setpoint.adoc[]" as repo.IndexColumn_virtual_referenced_setpoint << V >> {
  - **index_guid** : (uniqueidentifier)
  - **index_column_id** : (int)
  --
}

entity "puml-link:dhw:sqldb:repo.indexreferencedreferencing_hasfullcolumnsinreferencing.adoc[]" as repo.IndexReferencedReferencing_HasFullColumnsInReferencing << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_columnlist.adoc[]" as repo.RepoObject_ColumnList << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_gross2.adoc[]" as repo.RepoObject_gross2 << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_sat2.adoc[]" as repo.RepoObject_sat2 << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_sat2_t.adoc[]" as repo.RepoObject_sat2_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_sqlcreatetable.adoc[]" as repo.RepoObject_SqlCreateTable << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn_gross.adoc[]" as repo.RepoObjectColumn_gross << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn_gross2.adoc[]" as repo.RepoObjectColumn_gross2 << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn_missingsource_typev.adoc[]" as repo.RepoObjectColumn_MissingSource_TypeV << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_index_inheritance.adoc[]" as repo.usp_index_inheritance << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_main.adoc[]" as repo.usp_main << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_persist_indexcolumn_referencedreferencing_hasfullcolumnsinreferencing_t.adoc[]" as repo.usp_PERSIST_IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_persist_repoobject_sat2_t.adoc[]" as repo.usp_PERSIST_RepoObject_sat2_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_persistence_set.adoc[]" as repo.usp_persistence_set << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_sync_guid.adoc[]" as repo.usp_sync_guid << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_sync_guid_repoobjectcolumn.adoc[]" as repo.usp_sync_guid_RepoObjectColumn << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.repoobjectcolumn_translation.adoc[]" as ssas.RepoObjectColumn_translation << V >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:ssas.repoobjectcolumn_translation_displayfolder_union.adoc[]" as ssas.RepoObjectColumn_translation_displayfolder_union << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.repoobjectcolumn_translation_t.adoc[]" as ssas.RepoObjectColumn_translation_T << U >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:ssas.usp_persist_repoobjectcolumn_translation_t.adoc[]" as ssas.usp_PERSIST_RepoObjectColumn_translation_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.generatorusp_sqlusp.adoc[]" as uspgenerator.GeneratorUsp_SqlUsp << V >> {
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.generatorusp_sqlviewpersistenceupdatecheck.adoc[]" as uspgenerator.GeneratorUsp_SqlViewPersistenceUpdateCheck << V >> {
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.generatoruspstep_persistence_src.adoc[]" as uspgenerator.GeneratorUspStep_Persistence_src << V >> {
  - **usp_id** : (int)
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.usp_generatorusp_insert_update_persistence.adoc[]" as uspgenerator.usp_GeneratorUsp_insert_update_persistence << P >> {
  --
}

docs.ftv_RepoObject_Reference_PlantUml_EntityRefList <.. docs.RepoObject_Plantuml
docs.ObjectRefCyclic_EntityList <.. docs.ObjectRefCyclic
docs.RepoObject_Adoc <.. docs.RepoObject_Adoc_T
docs.RepoObject_Adoc <.. docs.usp_PERSIST_RepoObject_Adoc_T
docs.REpoObject_Adoc_T <.. docs.usp_PERSIST_RepoObject_Adoc_T
docs.RepoObject_ColumnList <.. docs.RepoObject_ColumnList_T
docs.RepoObject_ColumnList <.. docs.usp_PERSIST_RepoObject_ColumnList_T
docs.RepoObject_ColumnList_T <.. docs.RepoObject_Adoc
docs.RepoObject_ColumnList_T <.. docs.RepoObject_Plantuml_Entity
docs.RepoObject_ColumnList_T <.. docs.usp_PERSIST_RepoObject_ColumnList_T
docs.RepoObject_Plantuml <.. docs.RepoObject_Plantuml_T
docs.RepoObject_Plantuml <.. docs.usp_PERSIST_RepoObject_Plantuml_T
docs.RepoObject_Plantuml_ColRefList_1_1 <.. docs.RepoObject_Plantuml
docs.RepoObject_Plantuml_Entity <.. docs.RepoObject_Plantuml_Entity_T
docs.RepoObject_Plantuml_Entity <.. docs.usp_PERSIST_RepoObject_Plantuml_Entity_T
docs.RepoObject_Plantuml_Entity_T <.. docs.ftv_RepoObject_Reference_PlantUml_EntityRefList
docs.RepoObject_Plantuml_Entity_T <.. docs.ObjectRefCyclic_EntityList
docs.RepoObject_Plantuml_Entity_T <.. docs.RepoObject_Adoc
docs.RepoObject_Plantuml_Entity_T <.. docs.RepoObject_PlantUml_PumlEntityFkList
docs.RepoObject_Plantuml_Entity_T <.. docs.Schema_EntityList
docs.RepoObject_Plantuml_Entity_T <.. docs.usp_PERSIST_RepoObject_Plantuml_Entity_T
docs.RepoObject_PlantUml_PumlEntityFkList <.. docs.RepoObject_Plantuml
docs.RepoObject_Plantuml_T <.. docs.RepoObject_Adoc
docs.RepoObject_Plantuml_T <.. docs.usp_PERSIST_RepoObject_Plantuml_T
docs.Schema_EntityList <.. docs.Schema_puml
docs.Schema_puml <.. docs.AntoraNavListPage_by_schema
docs.Unit_1_union <.. docs.Unit_2
docs.Unit_2 <.. docs.Unit_3
docs.Unit_3 <.. dmdocs.unit
docs.usp_AntoraExport_ObjectPartialsContent <.. docs.usp_AntoraExport
docs.usp_AntoraExport_ObjectPuml <.. docs.usp_AntoraExport
docs.usp_PERSIST_RepoObject_Adoc_T <.. docs.usp_AntoraExport_ObjectPartialsContent
docs.usp_PERSIST_RepoObject_ColumnList_T <.. docs.usp_AntoraExport_ObjectPartialsContent
docs.usp_PERSIST_RepoObject_Plantuml_Entity_T <.. docs.usp_AntoraExport_ObjectPuml
docs.usp_PERSIST_RepoObject_Plantuml_T <.. docs.usp_AntoraExport_ObjectPuml
property.RepoObjectProperty_Collect_source_ROGross <.. property.usp_RepoObjectProperty_collect
property.RepoObjectProperty_Collect_source_uspgenerator <.. property.usp_RepoObjectProperty_collect
property.usp_RepoObject_Inheritance <.. repo.usp_main
property.usp_RepoObjectProperty_collect <.. property.usp_RepoObject_Inheritance
property.usp_RepoObjectProperty_collect <.. repo.usp_main
reference.ftv_RepoObjectColumn_ReferenceTree <.. reference.RepoObjectColumn_ReferenceTree
reference.RepoObjectColumn_reference <.. reference.RepoObjectColumn_reference_T
reference.RepoObjectColumn_reference <.. reference.usp_PERSIST_RepoObjectColumn_reference_T
reference.RepoObjectColumn_reference_FirstResultSet <.. reference.RepoObjectColumn_reference_BySamePredecessors
reference.RepoObjectColumn_reference_QueryPlan <.. reference.SysObjectColumn_QueryPlanExpression
reference.RepoObjectColumn_reference_T <.. docs.RepoObject_Plantuml_ColRefList_1_1
reference.RepoObjectColumn_reference_T <.. reference.RepoObjectColumn_ReferencedReferencing
reference.RepoObjectColumn_reference_T <.. reference.RepoObjectColumn_RelationScript
reference.RepoObjectColumn_reference_T <.. reference.usp_PERSIST_RepoObjectColumn_reference_T
reference.RepoObjectColumn_reference_T <.. repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing
reference.RepoObjectColumn_reference_T <.. repo.RepoObjectColumn_MissingSource_TypeV
reference.RepoObjectColumn_reference_union <.. reference.RepoObjectColumn_reference
reference.RepoObjectColumn_reference_virtual <.. reference.RepoObjectColumn_reference_union
reference.RepoObjectColumn_ReferencedList <.. repo.RepoObjectColumn_gross2
reference.RepoObjectColumn_ReferencedReferencing <.. reference.ftv_RepoObject_DbmlColumnRelation
reference.RepoObjectColumn_ReferencedReferencing <.. reference.ftv_RepoObjectColumn_ReferenceTree
reference.RepoObjectColumn_ReferencedReferencing <.. reference.RepoObjectColumn_ReferencedList
reference.RepoObjectColumn_ReferencedReferencing <.. reference.RepoObjectColumn_ReferencingList
reference.RepoObjectColumn_ReferenceTree <.. reference.ftv_RepoObject_ColumReferenceRepoObject
reference.RepoObjectColumn_ReferencingList <.. repo.RepoObjectColumn_gross2
reference.RepoObjectColumn_RelationScript <.. reference.ftv_RepoObject_ColumReferenceRepoObject
reference.SysObjectColumn_QueryPlanExpression <.. reference.usp_RepoObjectSource_QueryPlan
reference.usp_PERSIST_RepoObjectColumn_reference_T <.. repo.usp_main
reference.usp_RepoObjectSource_QueryPlan <.. repo.usp_main
repo.Index_referencing_IndexPatternColumnGuid <.. repo.IndexReferencedReferencing_HasFullColumnsInReferencing
repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing <.. repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T
repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing <.. repo.usp_PERSIST_IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T
repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T <.. repo.Index_referencing_IndexPatternColumnGuid
repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T <.. repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_check
repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T <.. repo.IndexColumn_virtual_referenced_setpoint
repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T <.. repo.IndexReferencedReferencing_HasFullColumnsInReferencing
repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T <.. repo.usp_PERSIST_IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T
repo.IndexColumn_virtual_referenced_setpoint <.. repo.check_IndexColumn_virtual_referenced_setpoint
repo.IndexColumn_virtual_referenced_setpoint <.. repo.usp_index_inheritance
repo.IndexReferencedReferencing_HasFullColumnsInReferencing <.. repo.usp_index_inheritance
repo.RepoObject_ColumnList <.. repo.RepoObject_gross2
repo.RepoObject_ColumnList <.. repo.RepoObject_sat2
repo.RepoObject_ColumnList <.. repo.RepoObject_SqlCreateTable
repo.RepoObject_gross2 <.. uspgenerator.GeneratorUsp_SqlViewPersistenceUpdateCheck
repo.RepoObject_gross2 <.. uspgenerator.GeneratorUspStep_Persistence_src
repo.RepoObject_sat2 <.. repo.RepoObject_sat2_T
repo.RepoObject_sat2 <.. repo.usp_PERSIST_RepoObject_sat2_T
repo.RepoObject_sat2_T <.. docs.RepoObject_Adoc
repo.RepoObject_sat2_T <.. property.RepoObjectProperty_Collect_source_ROGross
repo.RepoObject_sat2_T <.. repo.usp_PERSIST_RepoObject_sat2_T
repo.RepoObject_SqlCreateTable <.. reference.ftv_RepoObject_ColumReferenceRepoObject
repo.RepoObjectColumn_gross <.. docs.Unit_1_union
repo.RepoObjectColumn_gross <.. graph.RepoObjectColumn_S
repo.RepoObjectColumn_gross <.. property.RepoObjectColumnProperty_ForUpdate
repo.RepoObjectColumn_gross <.. reference.RepoObjectColumn_reference_FirstResultSet
repo.RepoObjectColumn_gross <.. reference.RepoObjectColumn_reference_QueryPlan
repo.RepoObjectColumn_gross <.. reference.RepoObjectColumn_reference_virtual
repo.RepoObjectColumn_gross <.. reference.usp_RepoObjectColumnSource_virtual_set
repo.RepoObjectColumn_gross <.. repo.RepoObjectColumn_gross2
repo.RepoObjectColumn_gross <.. repo.usp_sync_guid_RepoObjectColumn
repo.RepoObjectColumn_gross <.. ssas.RepoObjectColumn_translation
repo.RepoObjectColumn_gross2 <.. docs.RepoObject_ColumnList
repo.RepoObjectColumn_gross2 <.. repo.RepoObject_ColumnList
repo.RepoObjectColumn_gross2 <.. uspgenerator.usp_GeneratorUsp_insert_update_persistence
repo.usp_index_inheritance <.. repo.usp_main
repo.usp_PERSIST_IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T <.. repo.usp_index_inheritance
repo.usp_PERSIST_RepoObject_sat2_T <.. repo.usp_main
repo.usp_sync_guid <.. repo.usp_main
repo.usp_sync_guid <.. repo.usp_persistence_set
repo.usp_sync_guid_RepoObjectColumn <.. repo.usp_sync_guid
ssas.RepoObjectColumn_translation <.. ssas.RepoObjectColumn_translation_T
ssas.RepoObjectColumn_translation <.. ssas.usp_PERSIST_RepoObjectColumn_translation_T
ssas.RepoObjectColumn_translation_displayfolder_union <.. docs.RepoObject_ColumnList
ssas.RepoObjectColumn_translation_T <.. docs.RepoObject_Plantuml_ColRefList_1_1
ssas.RepoObjectColumn_translation_T <.. ssas.RepoObjectColumn_translation_displayfolder_union
ssas.RepoObjectColumn_translation_T <.. ssas.usp_PERSIST_RepoObjectColumn_translation_T
ssas.usp_PERSIST_RepoObjectColumn_translation_T <.. repo.usp_main
uspgenerator.GeneratorUsp_SqlUsp <.. property.RepoObjectProperty_Collect_source_uspgenerator
uspgenerator.GeneratorUsp_SqlViewPersistenceUpdateCheck <.. uspgenerator.GeneratorUsp_SqlUsp
uspgenerator.GeneratorUspStep_Persistence_src <.. uspgenerator.usp_GeneratorUsp_insert_update_persistence
uspgenerator.usp_GeneratorUsp_insert_update_persistence <.. repo.usp_main

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_0_30_objectref[]

=== PlantUML 1 1 ColumnRef

// tag::puml_entity_1_1_colref[]
[plantuml, entity_1_1_colref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:docs.unit_1_union.adoc[]" as docs.Unit_1_union << V >> {
  Object_fullname2 : (nvarchar(257))
  Object_Type : (varchar(2))
  Unit_ColummName : (nvarchar(128))
  Unit_Description : (nvarchar(max))
  Unit_DisplayFolder : (nvarchar(500))
  Unit_Expression : (nvarchar(max))
  Unit_FormatString : (nvarchar(500))
  - Unit_fullname2 : (nvarchar(638))
  - Unit_guid : (uniqueidentifier)
  Unit_isHidden : (bit)
  Unit_IsKey : (bit)
  Unit_IsSsas : (bit)
  Unit_IsUnique : (bit)
  - Unit_Metatype : (varchar(7))
  - Unit_Name : (nvarchar(500))
  Unit_ObjectName : (nvarchar(128))
  - Unit_Schema : (nvarchar(128))
  Unit_SummarizeBy : (nvarchar(500))
  Unit_TypeName : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:graph.repoobjectcolumn_s.adoc[]" as graph.RepoObjectColumn_S << V >> {
  - RepoObject_fullname : (nvarchar(261))
  RepoObject_fullname2 : (nvarchar(257))
  - RepoObject_guid : (uniqueidentifier)
  - RepoObject_type : (char(2))
  - RepoObjectColumn_fullname : (nvarchar(520))
  RepoObjectColumn_fullname2 : (nvarchar(386))
  - RepoObjectColumn_guid : (uniqueidentifier)
  - RepoObjectColumn_name : (nvarchar(128))
  RepoObjectColumn_type : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.fs_get_repoobjectcolumnproperty_nvarchar.adoc[]" as property.fs_get_RepoObjectColumnProperty_nvarchar << FN >> {
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectcolumnproperty_forupdate.adoc[]" as property.RepoObjectColumnProperty_ForUpdate << V >> {
  AntoraComponent : (nvarchar(max))
  AntoraModule : (nvarchar(max))
  dwh_database : (nvarchar(128))
  inheritance : (tinyint)
  InheritanceDefinition : (nvarchar(4000))
  InheritanceType : (tinyint)
  - property_name : (nvarchar(128))
  - property_value : (nvarchar(max))
  repo_database : (nvarchar(128))
  Repo_user_type_fullname : (nvarchar(128))
  - RepoObject_fullname : (nvarchar(261))
  - RepoObject_fullname2 : (nvarchar(257))
  - RepoObject_guid : (uniqueidentifier)
  - RepoObject_name : (nvarchar(128))
  - RepoObject_schema_name : (nvarchar(128))
  - RepoObject_type : (char(2))
  - RepoObjectColumn_fullname : (nvarchar(520))
  - RepoObjectColumn_fullname2 : (nvarchar(386))
  - RepoObjectColumn_guid : (uniqueidentifier)
  - RepoObjectColumn_name : (nvarchar(128))
  - RepoObjectColumnProperty_id : (int)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_reference_firstresultset.adoc[]" as reference.RepoObjectColumn_reference_FirstResultSet << V >> {
  - InformationSource : (varchar(37))
  is_hidden : (bit)
  is_referenced_object : (bit)
  is_referencing_object_equal_referenced_object : (bit)
  referenced_column_name : (nvarchar(128))
  referenced_entity_name : (nvarchar(128))
  referenced_id : (int)
  referenced_minor_id : (int)
  referenced_node_id : (bigint)
  referenced_RepoObject_guid : (uniqueidentifier)
  referenced_RepoObjectColumn_guid : (uniqueidentifier)
  referenced_schema_name : (nvarchar(128))
  referenced_type : (char(2))
  referencing_column_name : (nvarchar(128))
  - referencing_entity_name : (nvarchar(128))
  referencing_id : (int)
  referencing_minor_id : (int)
  referencing_node_id : (bigint)
  - referencing_RepoObject_guid : (uniqueidentifier)
  referencing_RepoObjectColumn_guid : (uniqueidentifier)
  - referencing_schema_name : (nvarchar(128))
  referencing_type : (char(2))
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_reference_queryplan.adoc[]" as reference.RepoObjectColumn_reference_QueryPlan << V >> {
  **referencing_id** : (int)
  **referencing_minor_id** : (int)
  **referenced_id** : (int)
  **referenced_minor_id** : (int)
  definition : (nvarchar(max))
  - InformationSource : (varchar(10))
  is_computed : (bit)
  is_referenced_object : (bit)
  is_referencing_object_equal_referenced_object : (bit)
  is_source_column_name_expression : (bit)
  is_target_column_name_expression : (bit)
  referenced_column_name : (nvarchar(128))
  referenced_entity_name : (nvarchar(128))
  referenced_node_id : (bigint)
  referenced_RepoObject_guid : (uniqueidentifier)
  referenced_RepoObjectColumn_guid : (uniqueidentifier)
  referenced_schema_name : (nvarchar(128))
  referenced_type : (char(2))
  referencing_column_name : (nvarchar(128))
  - referencing_entity_name : (nvarchar(128))
  referencing_node_id : (bigint)
  - referencing_RepoObject_guid : (uniqueidentifier)
  referencing_RepoObjectColumn_guid : (uniqueidentifier)
  - referencing_schema_name : (nvarchar(128))
  referencing_type : (char(2))
  source_schema_name_quoted : (nvarchar(128))
  source_table_name_quoted : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_reference_virtual.adoc[]" as reference.RepoObjectColumn_reference_virtual << V >> {
  definition : (nvarchar(max))
  - InformationSource : (varchar(34))
  is_computed : (bit)
  is_referenced_object : (bit)
  is_referencing_object_equal_referenced_object : (bit)
  - referenced_column_name : (nvarchar(128))
  - referenced_entity_name : (nvarchar(128))
  referenced_id : (int)
  referenced_minor_id : (int)
  referenced_node_id : (bigint)
  - referenced_RepoObject_guid : (uniqueidentifier)
  - referenced_RepoObjectColumn_guid : (uniqueidentifier)
  - referenced_schema_name : (nvarchar(128))
  referenced_type : (char(2))
  - referencing_column_name : (nvarchar(128))
  - referencing_entity_name : (nvarchar(128))
  referencing_id : (int)
  referencing_minor_id : (int)
  referencing_node_id : (bigint)
  - referencing_RepoObject_guid : (uniqueidentifier)
  - referencing_RepoObjectColumn_guid : (uniqueidentifier)
  - referencing_schema_name : (nvarchar(128))
  referencing_type : (char(2))
  --
}

entity "puml-link:dhw:sqldb:reference.usp_repoobjectcolumnsource_virtual_set.adoc[]" as reference.usp_RepoObjectColumnSource_virtual_set << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject.adoc[]" as repo.RepoObject << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  external_AntoraComponent : (nvarchar(128))
  external_AntoraModule : (nvarchar(128))
  has_execution_plan_issue : (bit)
  has_get_referenced_issue : (bit)
  indent_sql_modules_definition : (tinyint)
  Inheritance_Source_fullname : (nvarchar(261))
  Inheritance_StringAggSeparatorSql : (nvarchar(4000))
  InheritanceDefinition : (nvarchar(4000))
  InheritanceType : (tinyint)
  - is_DocsExclude : (bit)
  - is_external : (bit)
  is_repo_managed : (bit)
  is_required_ObjectMerge : (bit)
  - is_ssas : (bit)
  is_SysObject_missing : (bit)
  - modify_dt : (datetime)
  pk_index_guid : (uniqueidentifier)
  pk_IndexPatternColumnName_new : (nvarchar(4000))
  Repo_history_table_guid : (uniqueidentifier)
  Repo_temporal_type : (tinyint)
  - RepoObject_name : (nvarchar(128))
  RepoObject_Referencing_Count : (int)
  - RepoObject_schema_name : (nvarchar(128))
  - RepoObject_type : (char(2))
  SysObject_id : (int)
  SysObject_modify_date : (datetime)
  - SysObject_name : (nvarchar(128))
  - SysObject_parent_object_id : (int)
  - SysObject_schema_name : (nvarchar(128))
  SysObject_type : (char(2))
  ~ has_different_sys_names : (bit)
  # is_RepoObject_name_uniqueidentifier : (int)
  # is_SysObject_name_uniqueidentifier : (int)
  ~ node_id : (bigint)
  # RepoObject_fullname : (nvarchar(261))
  # RepoObject_fullname2 : (nvarchar(257))
  # SysObject_fullname : (nvarchar(261))
  # SysObject_fullname2 : (nvarchar(257))
  ~ SysObject_query_sql : (nvarchar(406))
  ~ usp_persistence_fullname : (nvarchar(273))
  # usp_persistence_fullname2 : (nvarchar(269))
  # usp_persistence_name : (nvarchar(140))
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_persistence.adoc[]" as repo.RepoObject_persistence << U >> {
  - **target_RepoObject_guid** : (uniqueidentifier)
  ColumnListIgnore : (nvarchar(4000))
  ColumnListNoCompareButUpdate : (nvarchar(4000))
  ColumnListNoCompareNoUpdate : (nvarchar(4000))
  ColumnListNoInsert : (nvarchar(4000))
  ExecutionLogId_action : (char(1))
  final_target_RepoObject_name : (nvarchar(128))
  - has_history : (bit)
  - has_history_columns : (bit)
  history_schema_name : (nvarchar(128))
  history_table_name : (nvarchar(128))
  - is_persistence_check_duplicate_per_pk : (bit)
  - is_persistence_check_for_empty_source : (bit)
  - is_persistence_delete_changed : (bit)
  - is_persistence_delete_missing : (bit)
  - is_persistence_insert : (bit)
  - is_persistence_persist_source : (bit)
  - is_persistence_truncate : (bit)
  - is_persistence_update_changed : (bit)
  postscript : (nvarchar(max))
  prescript : (nvarchar(max))
  source_RepoObject_guid : (uniqueidentifier)
  source_RepoObject_name : (nvarchar(128))
  ~ is_persistence : (bit)
  ~ temporal_type : (tinyint)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn.adoc[]" as repo.RepoObjectColumn << U >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  Inheritance_StringAggSeparatorSql : (nvarchar(4000))
  InheritanceDefinition : (nvarchar(4000))
  InheritanceType : (tinyint)
  is_persistence_Ignore : (bit)
  is_persistence_NoCompareButUpdate : (bit)
  is_persistence_NoCompareNoUpdate : (bit)
  is_persistence_NoInsert : (bit)
  is_query_plan_expression : (bit)
  is_required_ColumnMerge : (bit)
  is_SysObjectColumn_missing : (bit)
  persistence_source_RepoObjectColumn_guid : (uniqueidentifier)
  Referencing_Count : (int)
  Repo_default_definition : (nvarchar(max))
  Repo_default_is_system_named : (bit)
  Repo_default_name : (nvarchar(128))
  Repo_definition : (nvarchar(max))
  - Repo_generated_always_type : (tinyint)
  Repo_graph_type : (int)
  Repo_increment_value : (sql_variant)
  - Repo_is_computed : (bit)
  - Repo_is_identity : (bit)
  Repo_is_nullable : (bit)
  Repo_is_persisted : (bit)
  Repo_seed_value : (sql_variant)
  Repo_user_type_fullname : (nvarchar(128))
  Repo_user_type_name : (nvarchar(128))
  Repo_uses_database_collation : (bit)
  - RepoObject_guid : (uniqueidentifier)
  RepoObjectColumn_column_id : (int)
  - RepoObjectColumn_name : (nvarchar(128))
  SysObjectColumn_column_id : (int)
  - SysObjectColumn_name : (nvarchar(128))
  # Column_name : (nvarchar(128))
  ~ has_different_sys_names : (bit)
  # is_RepoObjectColumn_name_uniqueidentifier : (int)
  # is_SysObjectColumn_name_uniqueidentifier : (int)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn_gross.adoc[]" as repo.RepoObjectColumn_gross << V >> {
  - Column_name : (nvarchar(128))
  Description : (nvarchar(max))
  has_different_sys_names : (bit)
  has_get_referenced_issue : (bit)
  Inheritance_StringAggSeparatorSql : (nvarchar(4000))
  InheritanceDefinition : (nvarchar(4000))
  InheritanceType : (tinyint)
  - is_external : (bit)
  is_persistence_Ignore : (bit)
  is_persistence_NoCompareButUpdate : (bit)
  is_persistence_NoCompareNoUpdate : (bit)
  is_persistence_NoInsert : (bit)
  is_query_plan_expression : (bit)
  is_repo_managed : (bit)
  - is_RepoObject_name_uniqueidentifier : (int)
  - is_RepoObjectColumn_name_uniqueidentifier : (int)
  is_required_ColumnMerge : (bit)
  - is_ssas : (bit)
  is_SysObject_missing : (bit)
  - is_SysObject_name_uniqueidentifier : (int)
  is_SysObjectColumn_missing : (bit)
  - is_SysObjectColumn_name_uniqueidentifier : (int)
  - modify_dt : (datetime)
  node_id : (bigint)
  persistence_source_RepoObject_guid : (uniqueidentifier)
  persistence_source_RepoObjectColumn_guid : (uniqueidentifier)
  pk_index_guid : (uniqueidentifier)
  Property_ms_description : (nvarchar(4000))
  Referencing_Count : (int)
  Repo_default_definition : (nvarchar(max))
  Repo_default_is_system_named : (bit)
  Repo_default_name : (nvarchar(128))
  Repo_definition : (nvarchar(max))
  - Repo_generated_always_type : (tinyint)
  Repo_graph_type : (int)
  Repo_increment_value : (sql_variant)
  - Repo_is_computed : (bit)
  - Repo_is_identity : (bit)
  Repo_is_nullable : (bit)
  Repo_is_persisted : (bit)
  Repo_seed_value : (sql_variant)
  Repo_user_type_fullname : (nvarchar(128))
  Repo_user_type_name : (nvarchar(128))
  Repo_uses_database_collation : (bit)
  - RepoObject_fullname : (nvarchar(261))
  - RepoObject_fullname2 : (nvarchar(257))
  - RepoObject_guid : (uniqueidentifier)
  - RepoObject_name : (nvarchar(128))
  RepoObject_Referencing_Count : (int)
  - RepoObject_schema_name : (nvarchar(128))
  - RepoObject_type : (char(2))
  RepoObjectColumn_column_id : (int)
  - RepoObjectColumn_fullname : (nvarchar(520))
  - RepoObjectColumn_fullname2 : (nvarchar(386))
  - RepoObjectColumn_guid : (uniqueidentifier)
  - RepoObjectColumn_name : (nvarchar(128))
  - SysObject_fullname : (nvarchar(261))
  - SysObject_fullname2 : (nvarchar(257))
  SysObject_id : (int)
  SysObject_modify_date : (datetime)
  - SysObject_name : (nvarchar(128))
  - SysObject_parent_object_id : (int)
  - SysObject_schema_name : (nvarchar(128))
  SysObject_type : (char(2))
  SysObjectColumn_column_id : (int)
  - SysObjectColumn_name : (nvarchar(128))
  tabcol_Description : (nvarchar(max))
  tabcol_DisplayFolder : (nvarchar(500))
  tabcol_Expression : (nvarchar(max))
  tabcol_FormatString : (nvarchar(500))
  - tabcol_IsHidden : (bit)
  - tabcol_IsKey : (bit)
  - tabcol_IsUnique : (bit)
  tabcol_SummarizeBy : (nvarchar(500))
  tabcol_Type : (nvarchar(500))
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn_gross2.adoc[]" as repo.RepoObjectColumn_gross2 << V >> {
  AntoraReferencedColumnList : (nvarchar(max))
  AntoraReferencingColumnList : (nvarchar(max))
  - Column_name : (nvarchar(128))
  Description : (nvarchar(max))
  has_different_sys_names : (bit)
  has_get_referenced_issue : (bit)
  index_column_id : (int)
  index_name : (nvarchar(450))
  Inheritance_StringAggSeparatorSql : (nvarchar(4000))
  InheritanceDefinition : (nvarchar(4000))
  InheritanceType : (tinyint)
  - is_external : (bit)
  is_index_primary_key : (bit)
  is_persistence_Ignore : (bit)
  is_persistence_NoCompareButUpdate : (bit)
  is_persistence_NoCompareNoUpdate : (bit)
  is_persistence_NoInsert : (bit)
  is_query_plan_expression : (bit)
  is_repo_managed : (bit)
  - is_RepoObject_name_uniqueidentifier : (int)
  - is_RepoObjectColumn_name_uniqueidentifier : (int)
  is_required_ColumnMerge : (bit)
  - is_ssas : (bit)
  is_SysObject_missing : (bit)
  - is_SysObject_name_uniqueidentifier : (int)
  is_SysObjectColumn_missing : (bit)
  - is_SysObjectColumn_name_uniqueidentifier : (int)
  isAnyIndexColumn : (int)
  - modify_dt : (datetime)
  node_id : (bigint)
  persistence_source_RepoObject_guid : (uniqueidentifier)
  persistence_source_RepoObject_guid_via_Column : (uniqueidentifier)
  persistence_source_RepoObjectColumn_guid : (uniqueidentifier)
  pk_index_guid : (uniqueidentifier)
  Property_ms_description : (nvarchar(4000))
  Referencing_Count : (int)
  Repo_default_definition : (nvarchar(max))
  Repo_default_is_system_named : (bit)
  Repo_default_name : (nvarchar(128))
  Repo_definition : (nvarchar(max))
  - Repo_generated_always_type : (tinyint)
  Repo_graph_type : (int)
  Repo_increment_value : (sql_variant)
  - Repo_is_computed : (bit)
  - Repo_is_identity : (bit)
  Repo_is_nullable : (bit)
  Repo_is_persisted : (bit)
  Repo_seed_value : (sql_variant)
  Repo_user_type_fullname : (nvarchar(128))
  Repo_user_type_name : (nvarchar(128))
  Repo_uses_database_collation : (bit)
  - RepoObject_fullname : (nvarchar(261))
  - RepoObject_fullname2 : (nvarchar(257))
  - RepoObject_guid : (uniqueidentifier)
  - RepoObject_name : (nvarchar(128))
  RepoObject_Referencing_Count : (int)
  - RepoObject_schema_name : (nvarchar(128))
  - RepoObject_type : (char(2))
  RepoObjectColumn_column_id : (int)
  - RepoObjectColumn_fullname : (nvarchar(520))
  - RepoObjectColumn_fullname2 : (nvarchar(386))
  - RepoObjectColumn_guid : (uniqueidentifier)
  - RepoObjectColumn_name : (nvarchar(128))
  - SysObject_fullname : (nvarchar(261))
  - SysObject_fullname2 : (nvarchar(257))
  SysObject_id : (int)
  SysObject_modify_date : (datetime)
  - SysObject_name : (nvarchar(128))
  - SysObject_parent_object_id : (int)
  - SysObject_schema_name : (nvarchar(128))
  SysObject_type : (char(2))
  SysObjectColumn_column_id : (int)
  - SysObjectColumn_name : (nvarchar(128))
  tabcol_Description : (nvarchar(max))
  tabcol_DisplayFolder : (nvarchar(500))
  tabcol_Expression : (nvarchar(max))
  tabcol_FormatString : (nvarchar(500))
  - tabcol_IsHidden : (bit)
  - tabcol_IsKey : (bit)
  - tabcol_IsUnique : (bit)
  tabcol_SummarizeBy : (nvarchar(500))
  tabcol_Type : (nvarchar(500))
  --
}

entity "puml-link:dhw:sqldb:repo.usp_sync_guid_repoobjectcolumn.adoc[]" as repo.usp_sync_guid_RepoObjectColumn << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_311_tables_columns_t.adoc[]" as ssas.model_json_311_tables_columns_T << U >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  - **tables_columns_name** : (nvarchar(128))
  - RepoObject_guid : (uniqueidentifier)
  - RepoObjectColumn_guid : (uniqueidentifier)
  tables_columns_dataType : (nvarchar(500))
  tables_columns_description : (nvarchar(max))
  tables_columns_description_ja : (nvarchar(max))
  tables_columns_displayFolder : (nvarchar(500))
  tables_columns_expression : (nvarchar(max))
  tables_columns_expression_ja : (nvarchar(max))
  tables_columns_formatString : (nvarchar(500))
  tables_columns_isDataTypeInferred : (bit)
  tables_columns_isHidden : (bit)
  tables_columns_isKey : (bit)
  tables_columns_isNameInferred : (bit)
  tables_columns_isNullable : (bit)
  tables_columns_isUnique : (bit)
  tables_columns_keepUniqueRows : (bit)
  tables_columns_sortByColumn : (nvarchar(500))
  tables_columns_sourceColumn : (nvarchar(500))
  tables_columns_sourceProviderType : (nvarchar(500))
  tables_columns_summarizeBy : (nvarchar(500))
  tables_columns_type : (nvarchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31111_tables_columns_descriptions_stragg.adoc[]" as ssas.model_json_31111_tables_columns_descriptions_StrAgg << V >> {
  - databasename : (nvarchar(128))
  descriptions_StrAgg : (nvarchar(max))
  - RepoObject_guid : (uniqueidentifier)
  - RepoObjectColumn_guid : (uniqueidentifier)
  - tables_columns_name : (nvarchar(128))
  - tables_name : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31121_tables_columns_expressions_stragg.adoc[]" as ssas.model_json_31121_tables_columns_expressions_StrAgg << V >> {
  - databasename : (nvarchar(128))
  expressions_StrAgg : (nvarchar(max))
  - RepoObject_guid : (uniqueidentifier)
  - RepoObjectColumn_guid : (uniqueidentifier)
  - tables_columns_name : (nvarchar(128))
  - tables_name : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.repoobjectcolumn_translation.adoc[]" as ssas.RepoObjectColumn_translation << V >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  - Column_name : (nvarchar(128))
  cultures_translations_model_name : (nvarchar(500))
  cultures_translations_model_tables_columns_name : (nvarchar(128))
  cultures_translations_model_tables_name : (nvarchar(128))
  databasename : (nvarchar(128))
  displayfolder_DisplayName : (nvarchar(512))
  displayfolder_translation : (nvarchar(512))
  pk_index_guid : (uniqueidentifier)
  - RepoObject_name : (nvarchar(128))
  - RepoObject_schema_name : (nvarchar(128))
  RepoObjectColumn_DisplayName : (nvarchar(128))
  RepoObjectColumn_translation : (nvarchar(128))
  - tabcol_IsHidden : (bit)
  tables_columns_displayFolder : (nvarchar(500))
  tables_columns_name : (nvarchar(128))
  tables_name : (nvarchar(128))
  --
}

property.fs_get_RepoObjectColumnProperty_nvarchar <.. repo.RepoObjectColumn_gross
repo.RepoObject <.. repo.RepoObjectColumn_gross
repo.RepoObject_persistence <.. repo.RepoObjectColumn_gross
repo.RepoObjectColumn <.. repo.RepoObjectColumn_gross
repo.RepoObjectColumn_gross <.. docs.Unit_1_union
repo.RepoObjectColumn_gross <.. graph.RepoObjectColumn_S
repo.RepoObjectColumn_gross <.. property.RepoObjectColumnProperty_ForUpdate
repo.RepoObjectColumn_gross <.. reference.RepoObjectColumn_reference_FirstResultSet
repo.RepoObjectColumn_gross <.. reference.RepoObjectColumn_reference_QueryPlan
repo.RepoObjectColumn_gross <.. reference.RepoObjectColumn_reference_virtual
repo.RepoObjectColumn_gross <.. reference.usp_RepoObjectColumnSource_virtual_set
repo.RepoObjectColumn_gross <.. repo.RepoObjectColumn_gross2
repo.RepoObjectColumn_gross <.. repo.usp_sync_guid_RepoObjectColumn
repo.RepoObjectColumn_gross <.. ssas.RepoObjectColumn_translation
ssas.model_json_311_tables_columns_T <.. repo.RepoObjectColumn_gross
ssas.model_json_31111_tables_columns_descriptions_StrAgg <.. repo.RepoObjectColumn_gross
ssas.model_json_31121_tables_columns_expressions_StrAgg <.. repo.RepoObjectColumn_gross
"repo.RepoObject::has_get_referenced_issue" <-- "repo.RepoObjectColumn_gross::has_get_referenced_issue"
"repo.RepoObject::is_external" <-- "repo.RepoObjectColumn_gross::is_external"
"repo.RepoObject::is_repo_managed" <-- "repo.RepoObjectColumn_gross::is_repo_managed"
"repo.RepoObject::is_RepoObject_name_uniqueidentifier" <-- "repo.RepoObjectColumn_gross::is_RepoObject_name_uniqueidentifier"
"repo.RepoObject::is_ssas" <-- "repo.RepoObjectColumn_gross::is_ssas"
"repo.RepoObject::is_SysObject_missing" <-- "repo.RepoObjectColumn_gross::is_SysObject_missing"
"repo.RepoObject::is_SysObject_name_uniqueidentifier" <-- "repo.RepoObjectColumn_gross::is_SysObject_name_uniqueidentifier"
"repo.RepoObject::modify_dt" <-- "repo.RepoObjectColumn_gross::modify_dt"
"repo.RepoObject::node_id" <-- "repo.RepoObjectColumn_gross::node_id"
"repo.RepoObject::pk_index_guid" <-- "repo.RepoObjectColumn_gross::pk_index_guid"
"repo.RepoObject::RepoObject_fullname" <-- "repo.RepoObjectColumn_gross::RepoObject_fullname"
"repo.RepoObject::RepoObject_fullname2" <-- "repo.RepoObjectColumn_gross::RepoObject_fullname2"
"repo.RepoObject::RepoObject_name" <-- "repo.RepoObjectColumn_gross::RepoObject_name"
"repo.RepoObject::RepoObject_Referencing_Count" <-- "repo.RepoObjectColumn_gross::RepoObject_Referencing_Count"
"repo.RepoObject::RepoObject_schema_name" <-- "repo.RepoObjectColumn_gross::RepoObject_schema_name"
"repo.RepoObject::RepoObject_type" <-- "repo.RepoObjectColumn_gross::RepoObject_type"
"repo.RepoObject::SysObject_fullname" <-- "repo.RepoObjectColumn_gross::SysObject_fullname"
"repo.RepoObject::SysObject_fullname2" <-- "repo.RepoObjectColumn_gross::SysObject_fullname2"
"repo.RepoObject::SysObject_id" <-- "repo.RepoObjectColumn_gross::SysObject_id"
"repo.RepoObject::SysObject_modify_date" <-- "repo.RepoObjectColumn_gross::SysObject_modify_date"
"repo.RepoObject::SysObject_name" <-- "repo.RepoObjectColumn_gross::SysObject_name"
"repo.RepoObject::SysObject_parent_object_id" <-- "repo.RepoObjectColumn_gross::SysObject_parent_object_id"
"repo.RepoObject::SysObject_schema_name" <-- "repo.RepoObjectColumn_gross::SysObject_schema_name"
"repo.RepoObject::SysObject_type" <-- "repo.RepoObjectColumn_gross::SysObject_type"
"repo.RepoObject_persistence::source_RepoObject_guid" <-- "repo.RepoObjectColumn_gross::persistence_source_RepoObject_guid"
"repo.RepoObjectColumn::Column_name" <-- "repo.RepoObjectColumn_gross::Column_name"
"repo.RepoObjectColumn::has_different_sys_names" <-- "repo.RepoObjectColumn_gross::has_different_sys_names"
"repo.RepoObjectColumn::Inheritance_StringAggSeparatorSql" <-- "repo.RepoObjectColumn_gross::Inheritance_StringAggSeparatorSql"
"repo.RepoObjectColumn::InheritanceDefinition" <-- "repo.RepoObjectColumn_gross::InheritanceDefinition"
"repo.RepoObjectColumn::InheritanceType" <-- "repo.RepoObjectColumn_gross::InheritanceType"
"repo.RepoObjectColumn::is_persistence_Ignore" <-- "repo.RepoObjectColumn_gross::is_persistence_Ignore"
"repo.RepoObjectColumn::is_persistence_NoCompareButUpdate" <-- "repo.RepoObjectColumn_gross::is_persistence_NoCompareButUpdate"
"repo.RepoObjectColumn::is_persistence_NoCompareNoUpdate" <-- "repo.RepoObjectColumn_gross::is_persistence_NoCompareNoUpdate"
"repo.RepoObjectColumn::is_persistence_NoInsert" <-- "repo.RepoObjectColumn_gross::is_persistence_NoInsert"
"repo.RepoObjectColumn::is_query_plan_expression" <-- "repo.RepoObjectColumn_gross::is_query_plan_expression"
"repo.RepoObjectColumn::is_RepoObjectColumn_name_uniqueidentifier" <-- "repo.RepoObjectColumn_gross::is_RepoObjectColumn_name_uniqueidentifier"
"repo.RepoObjectColumn::is_required_ColumnMerge" <-- "repo.RepoObjectColumn_gross::is_required_ColumnMerge"
"repo.RepoObjectColumn::is_SysObjectColumn_missing" <-- "repo.RepoObjectColumn_gross::is_SysObjectColumn_missing"
"repo.RepoObjectColumn::is_SysObjectColumn_name_uniqueidentifier" <-- "repo.RepoObjectColumn_gross::is_SysObjectColumn_name_uniqueidentifier"
"repo.RepoObjectColumn::persistence_source_RepoObjectColumn_guid" <-- "repo.RepoObjectColumn_gross::persistence_source_RepoObjectColumn_guid"
"repo.RepoObjectColumn::Referencing_Count" <-- "repo.RepoObjectColumn_gross::Referencing_Count"
"repo.RepoObjectColumn::Repo_default_definition" <-- "repo.RepoObjectColumn_gross::Repo_default_definition"
"repo.RepoObjectColumn::Repo_default_is_system_named" <-- "repo.RepoObjectColumn_gross::Repo_default_is_system_named"
"repo.RepoObjectColumn::Repo_default_name" <-- "repo.RepoObjectColumn_gross::Repo_default_name"
"repo.RepoObjectColumn::Repo_definition" <-- "repo.RepoObjectColumn_gross::Repo_definition"
"repo.RepoObjectColumn::Repo_generated_always_type" <-- "repo.RepoObjectColumn_gross::Repo_generated_always_type"
"repo.RepoObjectColumn::Repo_graph_type" <-- "repo.RepoObjectColumn_gross::Repo_graph_type"
"repo.RepoObjectColumn::Repo_increment_value" <-- "repo.RepoObjectColumn_gross::Repo_increment_value"
"repo.RepoObjectColumn::Repo_is_computed" <-- "repo.RepoObjectColumn_gross::Repo_is_computed"
"repo.RepoObjectColumn::Repo_is_identity" <-- "repo.RepoObjectColumn_gross::Repo_is_identity"
"repo.RepoObjectColumn::Repo_is_nullable" <-- "repo.RepoObjectColumn_gross::Repo_is_nullable"
"repo.RepoObjectColumn::Repo_is_persisted" <-- "repo.RepoObjectColumn_gross::Repo_is_persisted"
"repo.RepoObjectColumn::Repo_seed_value" <-- "repo.RepoObjectColumn_gross::Repo_seed_value"
"repo.RepoObjectColumn::Repo_user_type_fullname" <-- "repo.RepoObjectColumn_gross::Repo_user_type_fullname"
"repo.RepoObjectColumn::Repo_user_type_name" <-- "repo.RepoObjectColumn_gross::Repo_user_type_name"
"repo.RepoObjectColumn::Repo_uses_database_collation" <-- "repo.RepoObjectColumn_gross::Repo_uses_database_collation"
"repo.RepoObjectColumn::RepoObject_guid" <-- "repo.RepoObjectColumn_gross::RepoObject_guid"
"repo.RepoObjectColumn::RepoObjectColumn_column_id" <-- "repo.RepoObjectColumn_gross::RepoObjectColumn_column_id"
"repo.RepoObjectColumn::RepoObjectColumn_guid" <-- "repo.RepoObjectColumn_gross::RepoObjectColumn_guid"
"repo.RepoObjectColumn::RepoObjectColumn_name" <-- "repo.RepoObjectColumn_gross::RepoObjectColumn_name"
"repo.RepoObjectColumn::SysObjectColumn_column_id" <-- "repo.RepoObjectColumn_gross::SysObjectColumn_column_id"
"repo.RepoObjectColumn::SysObjectColumn_name" <-- "repo.RepoObjectColumn_gross::SysObjectColumn_name"
"repo.RepoObjectColumn_gross::Column_name" <-- "repo.RepoObjectColumn_gross2::Column_name"
"repo.RepoObjectColumn_gross::Column_name" <-- "ssas.RepoObjectColumn_translation::Column_name"
"repo.RepoObjectColumn_gross::Description" <-- "repo.RepoObjectColumn_gross2::Description"
"repo.RepoObjectColumn_gross::has_different_sys_names" <-- "repo.RepoObjectColumn_gross2::has_different_sys_names"
"repo.RepoObjectColumn_gross::has_get_referenced_issue" <-- "repo.RepoObjectColumn_gross2::has_get_referenced_issue"
"repo.RepoObjectColumn_gross::Inheritance_StringAggSeparatorSql" <-- "repo.RepoObjectColumn_gross2::Inheritance_StringAggSeparatorSql"
"repo.RepoObjectColumn_gross::InheritanceDefinition" <-- "property.RepoObjectColumnProperty_ForUpdate::InheritanceDefinition"
"repo.RepoObjectColumn_gross::InheritanceDefinition" <-- "repo.RepoObjectColumn_gross2::InheritanceDefinition"
"repo.RepoObjectColumn_gross::InheritanceType" <-- "property.RepoObjectColumnProperty_ForUpdate::InheritanceType"
"repo.RepoObjectColumn_gross::InheritanceType" <-- "repo.RepoObjectColumn_gross2::InheritanceType"
"repo.RepoObjectColumn_gross::is_external" <-- "repo.RepoObjectColumn_gross2::is_external"
"repo.RepoObjectColumn_gross::is_persistence_Ignore" <-- "repo.RepoObjectColumn_gross2::is_persistence_Ignore"
"repo.RepoObjectColumn_gross::is_persistence_NoCompareButUpdate" <-- "repo.RepoObjectColumn_gross2::is_persistence_NoCompareButUpdate"
"repo.RepoObjectColumn_gross::is_persistence_NoCompareNoUpdate" <-- "repo.RepoObjectColumn_gross2::is_persistence_NoCompareNoUpdate"
"repo.RepoObjectColumn_gross::is_persistence_NoInsert" <-- "repo.RepoObjectColumn_gross2::is_persistence_NoInsert"
"repo.RepoObjectColumn_gross::is_query_plan_expression" <-- "repo.RepoObjectColumn_gross2::is_query_plan_expression"
"repo.RepoObjectColumn_gross::is_repo_managed" <-- "repo.RepoObjectColumn_gross2::is_repo_managed"
"repo.RepoObjectColumn_gross::is_RepoObject_name_uniqueidentifier" <-- "repo.RepoObjectColumn_gross2::is_RepoObject_name_uniqueidentifier"
"repo.RepoObjectColumn_gross::is_RepoObjectColumn_name_uniqueidentifier" <-- "repo.RepoObjectColumn_gross2::is_RepoObjectColumn_name_uniqueidentifier"
"repo.RepoObjectColumn_gross::is_required_ColumnMerge" <-- "repo.RepoObjectColumn_gross2::is_required_ColumnMerge"
"repo.RepoObjectColumn_gross::is_ssas" <-- "repo.RepoObjectColumn_gross2::is_ssas"
"repo.RepoObjectColumn_gross::is_SysObject_missing" <-- "repo.RepoObjectColumn_gross2::is_SysObject_missing"
"repo.RepoObjectColumn_gross::is_SysObject_name_uniqueidentifier" <-- "repo.RepoObjectColumn_gross2::is_SysObject_name_uniqueidentifier"
"repo.RepoObjectColumn_gross::is_SysObjectColumn_missing" <-- "repo.RepoObjectColumn_gross2::is_SysObjectColumn_missing"
"repo.RepoObjectColumn_gross::is_SysObjectColumn_name_uniqueidentifier" <-- "repo.RepoObjectColumn_gross2::is_SysObjectColumn_name_uniqueidentifier"
"repo.RepoObjectColumn_gross::modify_dt" <-- "repo.RepoObjectColumn_gross2::modify_dt"
"repo.RepoObjectColumn_gross::node_id" <-- "reference.RepoObjectColumn_reference_virtual::referenced_node_id"
"repo.RepoObjectColumn_gross::node_id" <-- "reference.RepoObjectColumn_reference_virtual::referencing_node_id"
"repo.RepoObjectColumn_gross::node_id" <-- "repo.RepoObjectColumn_gross2::node_id"
"repo.RepoObjectColumn_gross::persistence_source_RepoObject_guid" <-- "repo.RepoObjectColumn_gross2::persistence_source_RepoObject_guid"
"repo.RepoObjectColumn_gross::persistence_source_RepoObjectColumn_guid" <-- "repo.RepoObjectColumn_gross2::persistence_source_RepoObjectColumn_guid"
"repo.RepoObjectColumn_gross::pk_index_guid" <-- "repo.RepoObjectColumn_gross2::pk_index_guid"
"repo.RepoObjectColumn_gross::pk_index_guid" <-- "ssas.RepoObjectColumn_translation::pk_index_guid"
"repo.RepoObjectColumn_gross::Property_ms_description" <-- "repo.RepoObjectColumn_gross2::Property_ms_description"
"repo.RepoObjectColumn_gross::Referencing_Count" <-- "repo.RepoObjectColumn_gross2::Referencing_Count"
"repo.RepoObjectColumn_gross::Repo_default_definition" <-- "repo.RepoObjectColumn_gross2::Repo_default_definition"
"repo.RepoObjectColumn_gross::Repo_default_is_system_named" <-- "repo.RepoObjectColumn_gross2::Repo_default_is_system_named"
"repo.RepoObjectColumn_gross::Repo_default_name" <-- "repo.RepoObjectColumn_gross2::Repo_default_name"
"repo.RepoObjectColumn_gross::Repo_definition" <-- "repo.RepoObjectColumn_gross2::Repo_definition"
"repo.RepoObjectColumn_gross::Repo_generated_always_type" <-- "repo.RepoObjectColumn_gross2::Repo_generated_always_type"
"repo.RepoObjectColumn_gross::Repo_graph_type" <-- "repo.RepoObjectColumn_gross2::Repo_graph_type"
"repo.RepoObjectColumn_gross::Repo_increment_value" <-- "repo.RepoObjectColumn_gross2::Repo_increment_value"
"repo.RepoObjectColumn_gross::Repo_is_computed" <-- "repo.RepoObjectColumn_gross2::Repo_is_computed"
"repo.RepoObjectColumn_gross::Repo_is_identity" <-- "repo.RepoObjectColumn_gross2::Repo_is_identity"
"repo.RepoObjectColumn_gross::Repo_is_nullable" <-- "repo.RepoObjectColumn_gross2::Repo_is_nullable"
"repo.RepoObjectColumn_gross::Repo_is_persisted" <-- "repo.RepoObjectColumn_gross2::Repo_is_persisted"
"repo.RepoObjectColumn_gross::Repo_seed_value" <-- "repo.RepoObjectColumn_gross2::Repo_seed_value"
"repo.RepoObjectColumn_gross::Repo_user_type_fullname" <-- "graph.RepoObjectColumn_S::RepoObjectColumn_type"
"repo.RepoObjectColumn_gross::Repo_user_type_fullname" <-- "property.RepoObjectColumnProperty_ForUpdate::Repo_user_type_fullname"
"repo.RepoObjectColumn_gross::Repo_user_type_fullname" <-- "repo.RepoObjectColumn_gross2::Repo_user_type_fullname"
"repo.RepoObjectColumn_gross::Repo_user_type_name" <-- "repo.RepoObjectColumn_gross2::Repo_user_type_name"
"repo.RepoObjectColumn_gross::Repo_uses_database_collation" <-- "repo.RepoObjectColumn_gross2::Repo_uses_database_collation"
"repo.RepoObjectColumn_gross::RepoObject_fullname" <-- "graph.RepoObjectColumn_S::RepoObject_fullname"
"repo.RepoObjectColumn_gross::RepoObject_fullname" <-- "property.RepoObjectColumnProperty_ForUpdate::RepoObject_fullname"
"repo.RepoObjectColumn_gross::RepoObject_fullname" <-- "repo.RepoObjectColumn_gross2::RepoObject_fullname"
"repo.RepoObjectColumn_gross::RepoObject_fullname2" <-- "property.RepoObjectColumnProperty_ForUpdate::RepoObject_fullname2"
"repo.RepoObjectColumn_gross::RepoObject_fullname2" <-- "repo.RepoObjectColumn_gross2::RepoObject_fullname2"
"repo.RepoObjectColumn_gross::RepoObject_guid" <-- "graph.RepoObjectColumn_S::RepoObject_guid"
"repo.RepoObjectColumn_gross::RepoObject_guid" <-- "property.RepoObjectColumnProperty_ForUpdate::RepoObject_guid"
"repo.RepoObjectColumn_gross::RepoObject_guid" <-- "reference.RepoObjectColumn_reference_FirstResultSet::referenced_RepoObject_guid"
"repo.RepoObjectColumn_gross::RepoObject_guid" <-- "reference.RepoObjectColumn_reference_QueryPlan::referenced_RepoObject_guid"
"repo.RepoObjectColumn_gross::RepoObject_guid" <-- "reference.RepoObjectColumn_reference_virtual::referenced_RepoObject_guid"
"repo.RepoObjectColumn_gross::RepoObject_guid" <-- "reference.RepoObjectColumn_reference_virtual::referencing_RepoObject_guid"
"repo.RepoObjectColumn_gross::RepoObject_guid" <-- "repo.RepoObjectColumn_gross2::RepoObject_guid"
"repo.RepoObjectColumn_gross::RepoObject_name" <-- "property.RepoObjectColumnProperty_ForUpdate::RepoObject_name"
"repo.RepoObjectColumn_gross::RepoObject_name" <-- "repo.RepoObjectColumn_gross2::RepoObject_name"
"repo.RepoObjectColumn_gross::RepoObject_name" <-- "ssas.RepoObjectColumn_translation::RepoObject_name"
"repo.RepoObjectColumn_gross::RepoObject_Referencing_Count" <-- "repo.RepoObjectColumn_gross2::RepoObject_Referencing_Count"
"repo.RepoObjectColumn_gross::RepoObject_schema_name" <-- "property.RepoObjectColumnProperty_ForUpdate::RepoObject_schema_name"
"repo.RepoObjectColumn_gross::RepoObject_schema_name" <-- "repo.RepoObjectColumn_gross2::RepoObject_schema_name"
"repo.RepoObjectColumn_gross::RepoObject_schema_name" <-- "ssas.RepoObjectColumn_translation::RepoObject_schema_name"
"repo.RepoObjectColumn_gross::RepoObject_type" <-- "graph.RepoObjectColumn_S::RepoObject_type"
"repo.RepoObjectColumn_gross::RepoObject_type" <-- "property.RepoObjectColumnProperty_ForUpdate::RepoObject_type"
"repo.RepoObjectColumn_gross::RepoObject_type" <-- "repo.RepoObjectColumn_gross2::RepoObject_type"
"repo.RepoObjectColumn_gross::RepoObjectColumn_column_id" <-- "repo.RepoObjectColumn_gross2::RepoObjectColumn_column_id"
"repo.RepoObjectColumn_gross::RepoObjectColumn_fullname" <-- "graph.RepoObjectColumn_S::RepoObjectColumn_fullname"
"repo.RepoObjectColumn_gross::RepoObjectColumn_fullname" <-- "property.RepoObjectColumnProperty_ForUpdate::RepoObjectColumn_fullname"
"repo.RepoObjectColumn_gross::RepoObjectColumn_fullname" <-- "repo.RepoObjectColumn_gross2::RepoObjectColumn_fullname"
"repo.RepoObjectColumn_gross::RepoObjectColumn_fullname2" <-- "property.RepoObjectColumnProperty_ForUpdate::RepoObjectColumn_fullname2"
"repo.RepoObjectColumn_gross::RepoObjectColumn_fullname2" <-- "repo.RepoObjectColumn_gross2::RepoObjectColumn_fullname2"
"repo.RepoObjectColumn_gross::RepoObjectColumn_guid" <-- "graph.RepoObjectColumn_S::RepoObjectColumn_guid"
"repo.RepoObjectColumn_gross::RepoObjectColumn_guid" <-- "reference.RepoObjectColumn_reference_FirstResultSet::referenced_RepoObjectColumn_guid"
"repo.RepoObjectColumn_gross::RepoObjectColumn_guid" <-- "reference.RepoObjectColumn_reference_FirstResultSet::referencing_RepoObjectColumn_guid"
"repo.RepoObjectColumn_gross::RepoObjectColumn_guid" <-- "reference.RepoObjectColumn_reference_QueryPlan::referenced_RepoObjectColumn_guid"
"repo.RepoObjectColumn_gross::RepoObjectColumn_guid" <-- "reference.RepoObjectColumn_reference_QueryPlan::referencing_RepoObjectColumn_guid"
"repo.RepoObjectColumn_gross::RepoObjectColumn_guid" <-- "reference.RepoObjectColumn_reference_virtual::referenced_RepoObjectColumn_guid"
"repo.RepoObjectColumn_gross::RepoObjectColumn_guid" <-- "reference.RepoObjectColumn_reference_virtual::referencing_RepoObjectColumn_guid"
"repo.RepoObjectColumn_gross::RepoObjectColumn_guid" <-- "repo.RepoObjectColumn_gross2::RepoObjectColumn_guid"
"repo.RepoObjectColumn_gross::RepoObjectColumn_guid" <-- "ssas.RepoObjectColumn_translation::RepoObjectColumn_guid"
"repo.RepoObjectColumn_gross::RepoObjectColumn_name" <-- "graph.RepoObjectColumn_S::RepoObjectColumn_name"
"repo.RepoObjectColumn_gross::RepoObjectColumn_name" <-- "property.RepoObjectColumnProperty_ForUpdate::RepoObjectColumn_name"
"repo.RepoObjectColumn_gross::RepoObjectColumn_name" <-- "repo.RepoObjectColumn_gross2::RepoObjectColumn_name"
"repo.RepoObjectColumn_gross::SysObject_fullname" <-- "repo.RepoObjectColumn_gross2::SysObject_fullname"
"repo.RepoObjectColumn_gross::SysObject_fullname2" <-- "repo.RepoObjectColumn_gross2::SysObject_fullname2"
"repo.RepoObjectColumn_gross::SysObject_id" <-- "reference.RepoObjectColumn_reference_FirstResultSet::referenced_id"
"repo.RepoObjectColumn_gross::SysObject_id" <-- "reference.RepoObjectColumn_reference_QueryPlan::referenced_id"
"repo.RepoObjectColumn_gross::SysObject_id" <-- "reference.RepoObjectColumn_reference_virtual::referenced_id"
"repo.RepoObjectColumn_gross::SysObject_id" <-- "reference.RepoObjectColumn_reference_virtual::referencing_id"
"repo.RepoObjectColumn_gross::SysObject_id" <-- "repo.RepoObjectColumn_gross2::SysObject_id"
"repo.RepoObjectColumn_gross::SysObject_modify_date" <-- "repo.RepoObjectColumn_gross2::SysObject_modify_date"
"repo.RepoObjectColumn_gross::SysObject_name" <-- "reference.RepoObjectColumn_reference_QueryPlan::referenced_entity_name"
"repo.RepoObjectColumn_gross::SysObject_name" <-- "reference.RepoObjectColumn_reference_virtual::referenced_entity_name"
"repo.RepoObjectColumn_gross::SysObject_name" <-- "reference.RepoObjectColumn_reference_virtual::referencing_entity_name"
"repo.RepoObjectColumn_gross::SysObject_name" <-- "repo.RepoObjectColumn_gross2::SysObject_name"
"repo.RepoObjectColumn_gross::SysObject_parent_object_id" <-- "repo.RepoObjectColumn_gross2::SysObject_parent_object_id"
"repo.RepoObjectColumn_gross::SysObject_schema_name" <-- "reference.RepoObjectColumn_reference_QueryPlan::referenced_schema_name"
"repo.RepoObjectColumn_gross::SysObject_schema_name" <-- "reference.RepoObjectColumn_reference_virtual::referenced_schema_name"
"repo.RepoObjectColumn_gross::SysObject_schema_name" <-- "reference.RepoObjectColumn_reference_virtual::referencing_schema_name"
"repo.RepoObjectColumn_gross::SysObject_schema_name" <-- "repo.RepoObjectColumn_gross2::SysObject_schema_name"
"repo.RepoObjectColumn_gross::SysObject_type" <-- "reference.RepoObjectColumn_reference_FirstResultSet::referenced_type"
"repo.RepoObjectColumn_gross::SysObject_type" <-- "reference.RepoObjectColumn_reference_QueryPlan::referenced_type"
"repo.RepoObjectColumn_gross::SysObject_type" <-- "reference.RepoObjectColumn_reference_virtual::referenced_type"
"repo.RepoObjectColumn_gross::SysObject_type" <-- "reference.RepoObjectColumn_reference_virtual::referencing_type"
"repo.RepoObjectColumn_gross::SysObject_type" <-- "repo.RepoObjectColumn_gross2::SysObject_type"
"repo.RepoObjectColumn_gross::SysObjectColumn_column_id" <-- "reference.RepoObjectColumn_reference_FirstResultSet::referenced_minor_id"
"repo.RepoObjectColumn_gross::SysObjectColumn_column_id" <-- "reference.RepoObjectColumn_reference_FirstResultSet::referencing_minor_id"
"repo.RepoObjectColumn_gross::SysObjectColumn_column_id" <-- "reference.RepoObjectColumn_reference_QueryPlan::referenced_minor_id"
"repo.RepoObjectColumn_gross::SysObjectColumn_column_id" <-- "reference.RepoObjectColumn_reference_QueryPlan::referencing_minor_id"
"repo.RepoObjectColumn_gross::SysObjectColumn_column_id" <-- "reference.RepoObjectColumn_reference_virtual::referenced_minor_id"
"repo.RepoObjectColumn_gross::SysObjectColumn_column_id" <-- "reference.RepoObjectColumn_reference_virtual::referencing_minor_id"
"repo.RepoObjectColumn_gross::SysObjectColumn_column_id" <-- "repo.RepoObjectColumn_gross2::SysObjectColumn_column_id"
"repo.RepoObjectColumn_gross::SysObjectColumn_name" <-- "reference.RepoObjectColumn_reference_virtual::referenced_column_name"
"repo.RepoObjectColumn_gross::SysObjectColumn_name" <-- "reference.RepoObjectColumn_reference_virtual::referencing_column_name"
"repo.RepoObjectColumn_gross::SysObjectColumn_name" <-- "repo.RepoObjectColumn_gross2::SysObjectColumn_name"
"repo.RepoObjectColumn_gross::tabcol_Description" <-- "repo.RepoObjectColumn_gross2::tabcol_Description"
"repo.RepoObjectColumn_gross::tabcol_DisplayFolder" <-- "repo.RepoObjectColumn_gross2::tabcol_DisplayFolder"
"repo.RepoObjectColumn_gross::tabcol_Expression" <-- "repo.RepoObjectColumn_gross2::tabcol_Expression"
"repo.RepoObjectColumn_gross::tabcol_FormatString" <-- "repo.RepoObjectColumn_gross2::tabcol_FormatString"
"repo.RepoObjectColumn_gross::tabcol_IsHidden" <-- "repo.RepoObjectColumn_gross2::tabcol_IsHidden"
"repo.RepoObjectColumn_gross::tabcol_IsHidden" <-- "ssas.RepoObjectColumn_translation::tabcol_IsHidden"
"repo.RepoObjectColumn_gross::tabcol_IsKey" <-- "repo.RepoObjectColumn_gross2::tabcol_IsKey"
"repo.RepoObjectColumn_gross::tabcol_IsUnique" <-- "repo.RepoObjectColumn_gross2::tabcol_IsUnique"
"repo.RepoObjectColumn_gross::tabcol_SummarizeBy" <-- "repo.RepoObjectColumn_gross2::tabcol_SummarizeBy"
"repo.RepoObjectColumn_gross::tabcol_Type" <-- "repo.RepoObjectColumn_gross2::tabcol_Type"
"ssas.model_json_311_tables_columns_T::tables_columns_displayFolder" <-- "repo.RepoObjectColumn_gross::tabcol_DisplayFolder"
"ssas.model_json_311_tables_columns_T::tables_columns_formatString" <-- "repo.RepoObjectColumn_gross::tabcol_FormatString"
"ssas.model_json_311_tables_columns_T::tables_columns_summarizeBy" <-- "repo.RepoObjectColumn_gross::tabcol_SummarizeBy"
"ssas.model_json_311_tables_columns_T::tables_columns_type" <-- "repo.RepoObjectColumn_gross::tabcol_Type"

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_colref[]


== sql_modules_definition

// tag::sql_modules_definition[]
[%collapsible]
=======
[source,sql,numbered,indent=0]
----


CREATE View [repo].[RepoObjectColumn_gross]
As
Select
    roc.RepoObjectColumn_guid
  , ro.RepoObject_fullname
  , RepoObjectColumn_fullname          = Concat ( ro.RepoObject_fullname, '.', QuoteName ( roc.RepoObjectColumn_name ))
  , roc.Column_name
  , roc.has_different_sys_names
  , roc.Inheritance_StringAggSeparatorSql
  , roc.InheritanceDefinition
  , roc.InheritanceType
  , roc.is_persistence_Ignore
  , roc.is_persistence_NoCompareButUpdate
  , roc.is_persistence_NoCompareNoUpdate
  , roc.is_persistence_NoInsert
  , roc.is_query_plan_expression
  , roc.is_RepoObjectColumn_name_uniqueidentifier
  , roc.is_required_ColumnMerge
  , roc.is_SysObjectColumn_missing
  , roc.is_SysObjectColumn_name_uniqueidentifier
  , persistence_source_RepoObject_guid = rop.source_RepoObject_guid
  , roc.persistence_source_RepoObjectColumn_guid
  , roc.Referencing_Count
  , roc.Repo_default_definition
  , roc.Repo_default_is_system_named
  , roc.Repo_default_name
  , roc.Repo_definition
  , roc.Repo_generated_always_type
  , roc.Repo_graph_type
  , roc.Repo_is_computed
  , roc.Repo_is_identity
  , roc.Repo_is_nullable
  , roc.Repo_is_persisted
  , roc.Repo_seed_value
  , roc.Repo_increment_value
  , roc.Repo_user_type_fullname
  , roc.Repo_user_type_name
  , roc.Repo_uses_database_collation
  , roc.RepoObject_guid
  , roc.RepoObjectColumn_column_id
  , RepoObjectColumn_fullname2         = Concat ( ro.RepoObject_fullname2, '.', roc.RepoObjectColumn_name )
  , roc.RepoObjectColumn_name
  , roc.SysObjectColumn_column_id
  , roc.SysObjectColumn_name
  , ro.has_get_referenced_issue
  , ro.is_repo_managed
  , ro.is_ssas
  , ro.is_external
  , ro.is_RepoObject_name_uniqueidentifier
  , ro.is_SysObject_missing
  , ro.is_SysObject_name_uniqueidentifier
  , ro.modify_dt
  , ro.node_id
  , ro.pk_index_guid
  , ro.RepoObject_fullname2
  , ro.RepoObject_name
  , ro.RepoObject_Referencing_Count
  , ro.RepoObject_schema_name
  , ro.RepoObject_type
  , ro.SysObject_fullname
  , ro.SysObject_fullname2
  , ro.SysObject_id
  , ro.SysObject_modify_date
  , ro.SysObject_name
  , ro.SysObject_schema_name
  , ro.SysObject_type
  , ro.SysObject_parent_object_id
  --based on ro.pk_index_guid
  --in other words: only, if the columns are part of the PK
  , Property_ms_description            = property.fs_get_RepoObjectColumnProperty_nvarchar (
                                                                                               roc.RepoObjectColumn_guid
                                                                                             , 'ms_description'
                                                                                           )
  --Attention, this will be written back into Property 'Description'
  --this could be an issue, if it will be changed in differen places, which should be the primary?
  , Description                        = Coalesce (
                                                      --keep existing Description
                                                      property.fs_get_RepoObjectColumnProperty_nvarchar (
                                                                                                            roc.RepoObjectColumn_guid
                                                                                                          , 'Description'
                                                                                                        )
                                                    , tabcol.tables_columns_description
                                                    , tabcol2.descriptions_StrAgg
                                                    , property.fs_get_RepoObjectColumnProperty_nvarchar (
                                                                                                            roc.RepoObjectColumn_guid
                                                                                                          , 'ms_description'
                                                                                                        )
                                                  )
  , tabcol_Description                 = Coalesce ( tabcol.tables_columns_description, tabcol2.descriptions_StrAgg )
  , tabcol_DisplayFolder               = tabcol.tables_columns_displayFolder
  , tabcol_Expression                  = Coalesce ( tabcol.tables_columns_expression, tabcol3.expressions_StrAgg )
  , tabcol_FormatString                = tabcol.tables_columns_formatString
  --required in String_Agg in next steps
  , tabcol_IsHidden                    = IsNull ( tabcol.tables_columns_isHidden, 0 )
  , tabcol_IsKey                       = IsNull ( tabcol.tables_columns_isKey, 0 )
  , tabcol_IsUnique                    = IsNull ( tabcol.tables_columns_isUnique, 0 )
  , tabcol_SummarizeBy                 = tabcol.tables_columns_summarizeBy
  , tabcol_Type                        = tabcol.tables_columns_type

--, ic.index_column_id
--, ic.index_name
--, ic.is_index_primary_key
--, isAnyIndexColumn           =
--  (
--      Select
--          Top 1
--          1
--      From
--          repo.IndexColumn_union As icu
--      Where
--          icu.RepoObjectColumn_guid = roc.RepoObjectColumn_guid
--  )
--, roc_referenced.AntoraReferencedColumnList
--, roc_referencing.AntoraReferencingColumnList
From
    repo.RepoObjectColumn                                        As roc
    Inner Join
        repo.RepoObject                                          As ro
            On
            roc.RepoObject_guid           = ro.RepoObject_guid

    Left Join
        repo.RepoObject_persistence                              As rop
            On
            roc.RepoObject_guid           = rop.target_RepoObject_guid

    Left Join
        ssas.model_json_311_tables_columns_T                     As tabcol
            On
            tabcol.RepoObjectColumn_guid  = roc.RepoObjectColumn_guid

    Left Join
        ssas.model_json_31111_tables_columns_descriptions_StrAgg As tabcol2
            On
            tabcol2.RepoObjectColumn_guid = roc.RepoObjectColumn_guid

    Left Join
        ssas.model_json_31121_tables_columns_expressions_StrAgg  As tabcol3
            On
            tabcol3.RepoObjectColumn_guid = roc.RepoObjectColumn_guid

--Left Join
--    ssas.TMSCHEMA_COLUMNS_T As ssascol
--        On
--        ssascol.RepoObjectColumn_guid = roc.RepoObjectColumn_guid

--Left Outer Join
--    repo.IndexColumn_union                     As ic
--        On
--        ic.index_guid                   = ro.pk_index_guid
--        And ic.RepoObjectColumn_guid    = roc.RepoObjectColumn_guid

--Left Join
--    reference.RepoObjectColumn_ReferencedList  As roc_referenced
--        On
--        roc_referenced.Referencing_guid = roc.RepoObjectColumn_guid

--Left Join
--    reference.RepoObjectColumn_ReferencingList As roc_referencing
--        On
--        roc_referencing.Referenced_guid = roc.RepoObjectColumn_guid

----
=======
// end::sql_modules_definition[]


