// tag::HeaderFullDisplayName[]
= repo_sys.SysColumn - V
// end::HeaderFullDisplayName[]

== existing_properties

// tag::existing_properties[]

:ExistsProperty--antorareferencedlist:
:ExistsProperty--antorareferencinglist:
:ExistsProperty--is_repo_managed:
:ExistsProperty--is_ssas:
:ExistsProperty--referencedobjectlist:
:ExistsProperty--sql_modules_definition:
:ExistsProperty--FK:
:ExistsProperty--Columns:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
5D90291C-9D61-EB11-84DC-A81E8446D5B0
// end::RepoObject_guid[]

== RepoObject_FullDisplayName2

// tag::RepoObject_FullDisplayName2[]
repo_sys.SysColumn
// end::RepoObject_FullDisplayName2[]

== SysObject_type

// tag::SysObject_type[]
V 
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
view
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
820913996
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2021-08-17 20:03:38
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]
[discrete]
== _


[#column-collationunderlinename]
=== collation_name

[cols="d,8a,m,m,m"]
|===
|
|collation_name
|sysname
|NULL
|
|===


[#column-columnunderlineencryptionunderlinekeyunderlinedatabaseunderlinename]
=== column_encryption_key_database_name

[cols="d,8a,m,m,m"]
|===
|
|column_encryption_key_database_name
|sysname
|NULL
|
|===


[#column-columnunderlineencryptionunderlinekeyunderlineid]
=== column_encryption_key_id

[cols="d,8a,m,m,m"]
|===
|
|column_encryption_key_id
|int
|NULL
|
|===


[#column-defaultunderlinedefinition]
=== default_definition

[cols="d,8a,m,m,m"]
|===
|
|default_definition
|nvarchar(max)
|NULL
|
|===

.Referencing Columns
--
* xref:repo.syscolumn_repoobjectcolumn_via_guid.adoc#column-defaultunderlinedefinition[+repo.SysColumn_RepoObjectColumn_via_guid.default_definition+]
* xref:repo.syscolumn_repoobjectcolumn_via_name.adoc#column-defaultunderlinedefinition[+repo.SysColumn_RepoObjectColumn_via_name.default_definition+]
--


[#column-defaultunderlineisunderlinesystemunderlinenamed]
=== default_is_system_named

[cols="d,8a,m,m,m"]
|===
|
|default_is_system_named
|bit
|NULL
|
|===

.Referencing Columns
--
* xref:repo.syscolumn_repoobjectcolumn_via_guid.adoc#column-defaultunderlineisunderlinesystemunderlinenamed[+repo.SysColumn_RepoObjectColumn_via_guid.default_is_system_named+]
* xref:repo.syscolumn_repoobjectcolumn_via_name.adoc#column-defaultunderlineisunderlinesystemunderlinenamed[+repo.SysColumn_RepoObjectColumn_via_name.default_is_system_named+]
--


[#column-defaultunderlinename]
=== default_name

[cols="d,8a,m,m,m"]
|===
|
|default_name
|sysname
|NULL
|
|===

.Referencing Columns
--
* xref:repo.syscolumn_repoobjectcolumn_via_guid.adoc#column-defaultunderlinename[+repo.SysColumn_RepoObjectColumn_via_guid.default_name+]
* xref:repo.syscolumn_repoobjectcolumn_via_name.adoc#column-defaultunderlinename[+repo.SysColumn_RepoObjectColumn_via_name.default_name+]
--


[#column-defaultunderlineobjectunderlineid]
=== default_object_id

[cols="d,8a,m,m,m"]
|===
|
|default_object_id
|int
|NOT NULL
|
|===


[#column-defaultunderlineparentunderlinecolumnunderlineid]
=== default_parent_column_id

[cols="d,8a,m,m,m"]
|===
|
|default_parent_column_id
|int
|NULL
|
|===


[#column-definition]
=== definition

[cols="d,8a,m,m,m"]
|===
|
|definition
|nvarchar(max)
|NULL
|
|===

.Referencing Columns
--
* xref:repo.syscolumn_repoobjectcolumn_via_guid.adoc#column-definition[+repo.SysColumn_RepoObjectColumn_via_guid.definition+]
* xref:repo.syscolumn_repoobjectcolumn_via_name.adoc#column-definition[+repo.SysColumn_RepoObjectColumn_via_name.definition+]
--


[#column-encryptionunderlinealgorithmunderlinename]
=== encryption_algorithm_name

[cols="d,8a,m,m,m"]
|===
|
|encryption_algorithm_name
|sysname
|NULL
|
|===


[#column-encryptionunderlinetype]
=== encryption_type

[cols="d,8a,m,m,m"]
|===
|
|encryption_type
|int
|NULL
|
|===


[#column-encryptionunderlinetypeunderlinedesc]
=== encryption_type_desc

[cols="d,8a,m,m,m"]
|===
|
|encryption_type_desc
|nvarchar(64)
|NULL
|
|===


[#column-generatedunderlinealwaysunderlinetype]
=== generated_always_type

[cols="d,8a,m,m,m"]
|===
|
|generated_always_type
|tinyint
|NULL
|
|===

.Referencing Columns
--
* xref:repo.syscolumn_repoobjectcolumn_via_guid.adoc#column-generatedunderlinealwaysunderlinetype[+repo.SysColumn_RepoObjectColumn_via_guid.generated_always_type+]
* xref:repo.syscolumn_repoobjectcolumn_via_name.adoc#column-generatedunderlinealwaysunderlinetype[+repo.SysColumn_RepoObjectColumn_via_name.generated_always_type+]
--


[#column-generatedunderlinealwaysunderlinetypeunderlinedesc]
=== generated_always_type_desc

[cols="d,8a,m,m,m"]
|===
|
|generated_always_type_desc
|nvarchar(60)
|NULL
|
|===


[#column-graphunderlinetype]
=== graph_type

[cols="d,8a,m,m,m"]
|===
|
|graph_type
|int
|NULL
|
|===

.Referencing Columns
--
* xref:repo.syscolumn_repoobjectcolumn_via_guid.adoc#column-graphunderlinetype[+repo.SysColumn_RepoObjectColumn_via_guid.graph_type+]
* xref:repo.syscolumn_repoobjectcolumn_via_name.adoc#column-graphunderlinetype[+repo.SysColumn_RepoObjectColumn_via_name.graph_type+]
--


[#column-graphunderlinetypeunderlinedesc]
=== graph_type_desc

[cols="d,8a,m,m,m"]
|===
|
|graph_type_desc
|nvarchar(60)
|NULL
|
|===


[#column-incrementunderlinevalue]
=== increment_value

[cols="d,8a,m,m,m"]
|===
|
|increment_value
|sql_variant
|NULL
|
|===

.Referencing Columns
--
* xref:repo.syscolumn_repoobjectcolumn_via_guid.adoc#column-incrementunderlinevalue[+repo.SysColumn_RepoObjectColumn_via_guid.increment_value+]
* xref:repo.syscolumn_repoobjectcolumn_via_name.adoc#column-incrementunderlinevalue[+repo.SysColumn_RepoObjectColumn_via_name.increment_value+]
--


[#column-isunderlineansiunderlinepadded]
=== is_ansi_padded

[cols="d,8a,m,m,m"]
|===
|
|is_ansi_padded
|bit
|NOT NULL
|
|===


[#column-isunderlinecolumnunderlineset]
=== is_column_set

[cols="d,8a,m,m,m"]
|===
|
|is_column_set
|bit
|NULL
|
|===


[#column-isunderlinecomputed]
=== is_computed

[cols="d,8a,m,m,m"]
|===
|
|is_computed
|bit
|NOT NULL
|
|===

.Referencing Columns
--
* xref:repo.syscolumn_repoobjectcolumn_via_guid.adoc#column-isunderlinecomputed[+repo.SysColumn_RepoObjectColumn_via_guid.is_computed+]
* xref:repo.syscolumn_repoobjectcolumn_via_name.adoc#column-isunderlinecomputed[+repo.SysColumn_RepoObjectColumn_via_name.is_computed+]
--


[#column-isunderlinedtsunderlinereplicated]
=== is_dts_replicated

[cols="d,8a,m,m,m"]
|===
|
|is_dts_replicated
|bit
|NULL
|
|===


[#column-isunderlinefilestream]
=== is_filestream

[cols="d,8a,m,m,m"]
|===
|
|is_filestream
|bit
|NOT NULL
|
|===


[#column-isunderlinehidden]
=== is_hidden

[cols="d,8a,m,m,m"]
|===
|
|is_hidden
|bit
|NULL
|
|===


[#column-isunderlineidentity]
=== is_identity

[cols="d,8a,m,m,m"]
|===
|
|is_identity
|bit
|NOT NULL
|
|===

.Referencing Columns
--
* xref:repo.syscolumn_repoobjectcolumn_via_guid.adoc#column-isunderlineidentity[+repo.SysColumn_RepoObjectColumn_via_guid.is_identity+]
* xref:repo.syscolumn_repoobjectcolumn_via_name.adoc#column-isunderlineidentity[+repo.SysColumn_RepoObjectColumn_via_name.is_identity+]
--


[#column-isunderlinemasked]
=== is_masked

[cols="d,8a,m,m,m"]
|===
|
|is_masked
|bit
|NOT NULL
|
|===


[#column-isunderlinemergeunderlinepublished]
=== is_merge_published

[cols="d,8a,m,m,m"]
|===
|
|is_merge_published
|bit
|NULL
|
|===


[#column-isunderlinenonunderlinesqlunderlinesubscribed]
=== is_non_sql_subscribed

[cols="d,8a,m,m,m"]
|===
|
|is_non_sql_subscribed
|bit
|NULL
|
|===


[#column-isunderlinenullable]
=== is_nullable

[cols="d,8a,m,m,m"]
|===
|
|is_nullable
|bit
|NULL
|
|===

.Referencing Columns
--
* xref:repo.syscolumn_repoobjectcolumn_via_guid.adoc#column-isunderlinenullable[+repo.SysColumn_RepoObjectColumn_via_guid.is_nullable+]
* xref:repo.syscolumn_repoobjectcolumn_via_name.adoc#column-isunderlinenullable[+repo.SysColumn_RepoObjectColumn_via_name.is_nullable+]
--


[#column-isunderlinepersisted]
=== is_persisted

[cols="d,8a,m,m,m"]
|===
|
|is_persisted
|bit
|NULL
|
|===

.Referencing Columns
--
* xref:repo.syscolumn_repoobjectcolumn_via_guid.adoc#column-isunderlinepersisted[+repo.SysColumn_RepoObjectColumn_via_guid.is_persisted+]
* xref:repo.syscolumn_repoobjectcolumn_via_name.adoc#column-isunderlinepersisted[+repo.SysColumn_RepoObjectColumn_via_name.is_persisted+]
--


[#column-isunderlinereplicated]
=== is_replicated

[cols="d,8a,m,m,m"]
|===
|
|is_replicated
|bit
|NULL
|
|===


[#column-isunderlinerowguidcol]
=== is_rowguidcol

[cols="d,8a,m,m,m"]
|===
|
|is_rowguidcol
|bit
|NOT NULL
|
|===


[#column-isunderlinesparse]
=== is_sparse

[cols="d,8a,m,m,m"]
|===
|
|is_sparse
|bit
|NULL
|
|===


[#column-isunderlinexmlunderlinedocument]
=== is_xml_document

[cols="d,8a,m,m,m"]
|===
|
|is_xml_document
|bit
|NOT NULL
|
|===


[#column-lastunderlinevalue]
=== last_value

[cols="d,8a,m,m,m"]
|===
|
|last_value
|sql_variant
|NULL
|
|===


[#column-maxunderlinelength]
=== max_length

[cols="d,8a,m,m,m"]
|===
|
|max_length
|smallint
|NOT NULL
|
|===


[#column-precision]
=== precision

[cols="d,8a,m,m,m"]
|===
|
|precision
|tinyint
|NOT NULL
|
|===


[#column-ruleunderlineobjectunderlineid]
=== rule_object_id

[cols="d,8a,m,m,m"]
|===
|
|rule_object_id
|int
|NOT NULL
|
|===


[#column-scale]
=== scale

[cols="d,8a,m,m,m"]
|===
|
|scale
|tinyint
|NOT NULL
|
|===


[#column-seedunderlinevalue]
=== seed_value

[cols="d,8a,m,m,m"]
|===
|
|seed_value
|sql_variant
|NULL
|
|===

.Referencing Columns
--
* xref:repo.syscolumn_repoobjectcolumn_via_guid.adoc#column-seedunderlinevalue[+repo.SysColumn_RepoObjectColumn_via_guid.seed_value+]
* xref:repo.syscolumn_repoobjectcolumn_via_name.adoc#column-seedunderlinevalue[+repo.SysColumn_RepoObjectColumn_via_name.seed_value+]
--


[#column-sysobjectunderlinecolumnunderlineid]
=== SysObject_column_id

[cols="d,8a,m,m,m"]
|===
|
|SysObject_column_id
|int
|NOT NULL
|
|===

.Referencing Columns
--
* xref:repo.syscolumn_repoobjectcolumn_via_guid.adoc#column-sysobjectunderlinecolumnunderlineid[+repo.SysColumn_RepoObjectColumn_via_guid.SysObject_column_id+]
* xref:repo.syscolumn_repoobjectcolumn_via_name.adoc#column-sysobjectunderlinecolumnunderlineid[+repo.SysColumn_RepoObjectColumn_via_name.SysObject_column_id+]
--


[#column-sysobjectunderlinecolumnunderlinename]
=== SysObject_column_name

[cols="d,8a,m,m,m"]
|===
|
|SysObject_column_name
|sysname
|NULL
|
|===

.Referencing Columns
--
* xref:repo.syscolumn_repoobjectcolumn_via_guid.adoc#column-sysobjectunderlinecolumnunderlinename[+repo.SysColumn_RepoObjectColumn_via_guid.SysObject_column_name+]
* xref:repo.syscolumn_repoobjectcolumn_via_name.adoc#column-sysobjectunderlinecolumnunderlinename[+repo.SysColumn_RepoObjectColumn_via_name.SysObject_column_name+]
* xref:repo_sys.foreignkeycolumn.adoc#column-referencingunderlinecolumnunderlinename[+repo_sys.ForeignKeyColumn.referencing_column_name+]
* xref:repo_sys.foreignkeycolumn.adoc#column-referencedunderlinecolumnunderlinename[+repo_sys.ForeignKeyColumn.referenced_column_name+]
--


[#column-sysobjectunderlinefullname]
=== SysObject_fullname

[cols="d,8a,m,m,m"]
|===
|
|SysObject_fullname
|nvarchar(517)
|NULL
|
|===


[#column-sysobjectunderlinefullname2]
=== SysObject_fullname2

[cols="d,8a,m,m,m"]
|===
|
|SysObject_fullname2
|nvarchar(257)
|NULL
|
|===


[#column-sysobjectunderlineid]
=== SysObject_id

[cols="d,8a,m,m,m"]
|===
|
|SysObject_id
|int
|NOT NULL
|
|===

.Referencing Columns
--
* xref:repo.syscolumn_repoobjectcolumn_via_guid.adoc#column-sysobjectunderlineid[+repo.SysColumn_RepoObjectColumn_via_guid.SysObject_id+]
* xref:repo.syscolumn_repoobjectcolumn_via_name.adoc#column-sysobjectunderlineid[+repo.SysColumn_RepoObjectColumn_via_name.SysObject_id+]
--


[#column-sysobjectunderlinename]
=== SysObject_name

[cols="d,8a,m,m,m"]
|===
|
|SysObject_name
|nvarchar(128)
|NULL
|
|===

.Referencing Columns
--
* xref:repo.syscolumn_repoobjectcolumn_via_guid.adoc#column-sysobjectunderlinename[+repo.SysColumn_RepoObjectColumn_via_guid.SysObject_name+]
* xref:repo.syscolumn_repoobjectcolumn_via_name.adoc#column-sysobjectunderlinename[+repo.SysColumn_RepoObjectColumn_via_name.SysObject_name+]
* xref:repo_sys.foreignkeycolumn.adoc#column-referencingunderlinename[+repo_sys.ForeignKeyColumn.referencing_name+]
* xref:repo_sys.foreignkeycolumn.adoc#column-referencedunderlinename[+repo_sys.ForeignKeyColumn.referenced_name+]
--


[#column-sysobjectunderlinerepoobjectunderlineguid]
=== SysObject_RepoObject_guid

[cols="d,8a,m,m,m"]
|===
|
|SysObject_RepoObject_guid
|uniqueidentifier
|NULL
|
|===

.Referencing Columns
--
* xref:repo.syscolumn_repoobjectcolumn_via_guid.adoc#column-sysobjectunderlinerepoobjectunderlineguid[+repo.SysColumn_RepoObjectColumn_via_guid.SysObject_RepoObject_guid+]
* xref:repo.syscolumn_repoobjectcolumn_via_name.adoc#column-sysobjectunderlinerepoobjectunderlineguid[+repo.SysColumn_RepoObjectColumn_via_name.SysObject_RepoObject_guid+]
* xref:repo_sys.foreignkeycolumn.adoc#column-referencingunderlinerepoobjectunderlineguid[+repo_sys.ForeignKeyColumn.referencing_RepoObject_guid+]
* xref:repo_sys.foreignkeycolumn.adoc#column-referencedunderlinerepoobjectunderlineguid[+repo_sys.ForeignKeyColumn.referenced_RepoObject_guid+]
--


[#column-sysobjectunderlinerepoobjectcolumnunderlineguid]
=== SysObject_RepoObjectColumn_guid

[cols="d,8a,m,m,m"]
|===
|
|SysObject_RepoObjectColumn_guid
|uniqueidentifier
|NULL
|
|===

.Referencing Columns
--
* xref:repo.syscolumn_repoobjectcolumn_via_guid.adoc#column-sysobjectunderlinerepoobjectcolumnunderlineguid[+repo.SysColumn_RepoObjectColumn_via_guid.SysObject_RepoObjectColumn_guid+]
* xref:repo.syscolumn_repoobjectcolumn_via_name.adoc#column-sysobjectunderlinerepoobjectcolumnunderlineguid[+repo.SysColumn_RepoObjectColumn_via_name.SysObject_RepoObjectColumn_guid+]
* xref:repo_sys.foreignkeycolumn.adoc#column-referencingunderlinerepoobjectcolumnunderlineguid[+repo_sys.ForeignKeyColumn.referencing_RepoObjectColumn_guid+]
* xref:repo_sys.foreignkeycolumn.adoc#column-referencedunderlinerepoobjectcolumnunderlineguid[+repo_sys.ForeignKeyColumn.referenced_RepoObjectColumn_guid+]
--


[#column-sysobjectunderlineschemaunderlinename]
=== SysObject_schema_name

[cols="d,8a,m,m,m"]
|===
|
|SysObject_schema_name
|nvarchar(128)
|NULL
|
|===

.Referencing Columns
--
* xref:repo.syscolumn_repoobjectcolumn_via_guid.adoc#column-sysobjectunderlineschemaunderlinename[+repo.SysColumn_RepoObjectColumn_via_guid.SysObject_schema_name+]
* xref:repo.syscolumn_repoobjectcolumn_via_name.adoc#column-sysobjectunderlineschemaunderlinename[+repo.SysColumn_RepoObjectColumn_via_name.SysObject_schema_name+]
* xref:repo_sys.foreignkeycolumn.adoc#column-referencingunderlineschemaunderlinename[+repo_sys.ForeignKeyColumn.referencing_schema_name+]
* xref:repo_sys.foreignkeycolumn.adoc#column-referencedunderlineschemaunderlinename[+repo_sys.ForeignKeyColumn.referenced_schema_name+]
--


[#column-sysobjectunderlinetype]
=== SysObject_type

[cols="d,8a,m,m,m"]
|===
|
|SysObject_type
|char(2)
|NULL
|
|===

.Referenced Columns
--
* xref:repo_sys.sysobject.adoc#column-type[+repo_sys.SysObject.type+]
--

.Referencing Columns
--
* xref:repo.syscolumn_repoobjectcolumn_via_guid.adoc#column-sysobjectunderlinetype[+repo.SysColumn_RepoObjectColumn_via_guid.SysObject_type+]
* xref:repo.syscolumn_repoobjectcolumn_via_name.adoc#column-sysobjectunderlinetype[+repo.SysColumn_RepoObjectColumn_via_name.SysObject_type+]
--


[#column-sysobjectunderlinetypeunderlinedesc]
=== SysObject_type_desc

[cols="d,8a,m,m,m"]
|===
|
|SysObject_type_desc
|nvarchar(60)
|NULL
|
|===

.Referenced Columns
--
* xref:repo_sys.sysobject.adoc#column-typeunderlinedesc[+repo_sys.SysObject.type_desc+]
--


[#column-systemunderlinetypeunderlineid]
=== system_type_id

[cols="d,8a,m,m,m"]
|===
|
|system_type_id
|tinyint
|NOT NULL
|
|===


[#column-userunderlinetypeunderlinefullname]
=== user_type_fullname

[cols="d,8a,m,m,m"]
|===
|
|user_type_fullname
|nvarchar(182)
|NULL
|
|===

.Referencing Columns
--
* xref:repo.syscolumn_repoobjectcolumn_via_guid.adoc#column-userunderlinetypeunderlinefullname[+repo.SysColumn_RepoObjectColumn_via_guid.user_type_fullname+]
* xref:repo.syscolumn_repoobjectcolumn_via_name.adoc#column-userunderlinetypeunderlinefullname[+repo.SysColumn_RepoObjectColumn_via_name.user_type_fullname+]
--


[#column-userunderlinetypeunderlineid]
=== user_type_id

[cols="d,8a,m,m,m"]
|===
|
|user_type_id
|int
|NOT NULL
|
|===


[#column-userunderlinetypeunderlinename]
=== user_type_name

[cols="d,8a,m,m,m"]
|===
|
|user_type_name
|sysname
|NULL
|
|===

.Referencing Columns
--
* xref:repo.syscolumn_repoobjectcolumn_via_guid.adoc#column-userunderlinetypeunderlinename[+repo.SysColumn_RepoObjectColumn_via_guid.user_type_name+]
* xref:repo.syscolumn_repoobjectcolumn_via_name.adoc#column-userunderlinetypeunderlinename[+repo.SysColumn_RepoObjectColumn_via_name.user_type_name+]
--


[#column-usesunderlinedatabaseunderlinecollation]
=== uses_database_collation

[cols="d,8a,m,m,m"]
|===
|
|uses_database_collation
|bit
|NULL
|
|===

.Referencing Columns
--
* xref:repo.syscolumn_repoobjectcolumn_via_guid.adoc#column-usesunderlinedatabaseunderlinecollation[+repo.SysColumn_RepoObjectColumn_via_guid.uses_database_collation+]
* xref:repo.syscolumn_repoobjectcolumn_via_name.adoc#column-usesunderlinedatabaseunderlinecollation[+repo.SysColumn_RepoObjectColumn_via_name.uses_database_collation+]
--


[#column-xmlunderlinecollectionunderlineid]
=== xml_collection_id

[cols="d,8a,m,m,m"]
|===
|
|xml_collection_id
|int
|NOT NULL
|
|===


// end::AntoraColumnDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]
























































// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]
|
|<<column-collationunderlinename>>
|sysname
|NULL
|

|
|<<column-columnunderlineencryptionunderlinekeyunderlinedatabaseunderlinename>>
|sysname
|NULL
|

|
|<<column-columnunderlineencryptionunderlinekeyunderlineid>>
|int
|NULL
|

|
|<<column-defaultunderlinedefinition>>
|nvarchar(max)
|NULL
|

|
|<<column-defaultunderlineisunderlinesystemunderlinenamed>>
|bit
|NULL
|

|
|<<column-defaultunderlinename>>
|sysname
|NULL
|

|
|<<column-defaultunderlineobjectunderlineid>>
|int
|NOT NULL
|

|
|<<column-defaultunderlineparentunderlinecolumnunderlineid>>
|int
|NULL
|

|
|<<column-definition>>
|nvarchar(max)
|NULL
|

|
|<<column-encryptionunderlinealgorithmunderlinename>>
|sysname
|NULL
|

|
|<<column-encryptionunderlinetype>>
|int
|NULL
|

|
|<<column-encryptionunderlinetypeunderlinedesc>>
|nvarchar(64)
|NULL
|

|
|<<column-generatedunderlinealwaysunderlinetype>>
|tinyint
|NULL
|

|
|<<column-generatedunderlinealwaysunderlinetypeunderlinedesc>>
|nvarchar(60)
|NULL
|

|
|<<column-graphunderlinetype>>
|int
|NULL
|

|
|<<column-graphunderlinetypeunderlinedesc>>
|nvarchar(60)
|NULL
|

|
|<<column-incrementunderlinevalue>>
|sql_variant
|NULL
|

|
|<<column-isunderlineansiunderlinepadded>>
|bit
|NOT NULL
|

|
|<<column-isunderlinecolumnunderlineset>>
|bit
|NULL
|

|
|<<column-isunderlinecomputed>>
|bit
|NOT NULL
|

|
|<<column-isunderlinedtsunderlinereplicated>>
|bit
|NULL
|

|
|<<column-isunderlinefilestream>>
|bit
|NOT NULL
|

|
|<<column-isunderlinehidden>>
|bit
|NULL
|

|
|<<column-isunderlineidentity>>
|bit
|NOT NULL
|

|
|<<column-isunderlinemasked>>
|bit
|NOT NULL
|

|
|<<column-isunderlinemergeunderlinepublished>>
|bit
|NULL
|

|
|<<column-isunderlinenonunderlinesqlunderlinesubscribed>>
|bit
|NULL
|

|
|<<column-isunderlinenullable>>
|bit
|NULL
|

|
|<<column-isunderlinepersisted>>
|bit
|NULL
|

|
|<<column-isunderlinereplicated>>
|bit
|NULL
|

|
|<<column-isunderlinerowguidcol>>
|bit
|NOT NULL
|

|
|<<column-isunderlinesparse>>
|bit
|NULL
|

|
|<<column-isunderlinexmlunderlinedocument>>
|bit
|NOT NULL
|

|
|<<column-lastunderlinevalue>>
|sql_variant
|NULL
|

|
|<<column-maxunderlinelength>>
|smallint
|NOT NULL
|

|
|<<column-precision>>
|tinyint
|NOT NULL
|

|
|<<column-ruleunderlineobjectunderlineid>>
|int
|NOT NULL
|

|
|<<column-scale>>
|tinyint
|NOT NULL
|

|
|<<column-seedunderlinevalue>>
|sql_variant
|NULL
|

|
|<<column-sysobjectunderlinecolumnunderlineid>>
|int
|NOT NULL
|

|
|<<column-sysobjectunderlinecolumnunderlinename>>
|sysname
|NULL
|

|
|<<column-sysobjectunderlinefullname>>
|nvarchar(517)
|NULL
|

|
|<<column-sysobjectunderlinefullname2>>
|nvarchar(257)
|NULL
|

|
|<<column-sysobjectunderlineid>>
|int
|NOT NULL
|

|
|<<column-sysobjectunderlinename>>
|nvarchar(128)
|NULL
|

|
|<<column-sysobjectunderlinerepoobjectunderlineguid>>
|uniqueidentifier
|NULL
|

|
|<<column-sysobjectunderlinerepoobjectcolumnunderlineguid>>
|uniqueidentifier
|NULL
|

|
|<<column-sysobjectunderlineschemaunderlinename>>
|nvarchar(128)
|NULL
|

|
|<<column-sysobjectunderlinetype>>
|char(2)
|NULL
|

|
|<<column-sysobjectunderlinetypeunderlinedesc>>
|nvarchar(60)
|NULL
|

|
|<<column-systemunderlinetypeunderlineid>>
|tinyint
|NOT NULL
|

|
|<<column-userunderlinetypeunderlinefullname>>
|nvarchar(182)
|NULL
|

|
|<<column-userunderlinetypeunderlineid>>
|int
|NOT NULL
|

|
|<<column-userunderlinetypeunderlinename>>
|sysname
|NULL
|

|
|<<column-usesunderlinedatabaseunderlinecollation>>
|bit
|NULL
|

|
|<<column-xmlunderlinecollectionunderlineid>>
|int
|NOT NULL
|

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

// end::AntoraIndexList[]

== AntoraMeasureDetails

// tag::AntoraMeasureDetails[]

// end::AntoraMeasureDetails[]

== AntoraMeasureDescriptions



== AntoraParameterList

// tag::AntoraParameterList[]

// end::AntoraParameterList[]

== AntoraXrefCulturesList

// tag::AntoraXrefCulturesList[]
* xref:dhw:sqldb:repo_sys.syscolumn.adoc[] - 
// end::AntoraXrefCulturesList[]

== cultures_count

// tag::cultures_count[]
1
// end::cultures_count[]

== Other tags

source: property.RepoObjectProperty_cross As rop_cross


=== additional_reference_csv

// tag::additional_reference_csv[]

// end::additional_reference_csv[]


=== AdocUspSteps

// tag::adocuspsteps[]

// end::adocuspsteps[]


=== AntoraReferencedList

// tag::antorareferencedlist[]
* xref:dhw:sqldb:config.ftv_dwh_database.adoc[]
* xref:dhw:sqldb:repo_sys.extendedproperties.adoc[]
* xref:dhw:sqldb:repo_sys.sysobject.adoc[]
* xref:dhw:sqldb:sys_dwh.columns.adoc[]
* xref:dhw:sqldb:sys_dwh.computed_columns.adoc[]
* xref:dhw:sqldb:sys_dwh.default_constraints.adoc[]
* xref:dhw:sqldb:sys_dwh.identity_columns.adoc[]
* xref:dhw:sqldb:sys_dwh.types.adoc[]
// end::antorareferencedlist[]


=== AntoraReferencingList

// tag::antorareferencinglist[]
* xref:dhw:sqldb:repo.syscolumn_repoobjectcolumn_via_guid.adoc[]
* xref:dhw:sqldb:repo.syscolumn_repoobjectcolumn_via_name.adoc[]
* xref:dhw:sqldb:repo.usp_sync_guid_repoobjectcolumn.adoc[]
* xref:dhw:sqldb:repo_sys.foreignkeycolumn.adoc[]
// end::antorareferencinglist[]


=== Description

// tag::description[]

// end::description[]


=== exampleUsage

// tag::exampleusage[]

// end::exampleusage[]


=== exampleUsage_2

// tag::exampleusage_2[]

// end::exampleusage_2[]


=== exampleUsage_3

// tag::exampleusage_3[]

// end::exampleusage_3[]


=== exampleUsage_4

// tag::exampleusage_4[]

// end::exampleusage_4[]


=== exampleUsage_5

// tag::exampleusage_5[]

// end::exampleusage_5[]


=== exampleWrong_Usage

// tag::examplewrong_usage[]

// end::examplewrong_usage[]


=== has_execution_plan_issue

// tag::has_execution_plan_issue[]

// end::has_execution_plan_issue[]


=== has_get_referenced_issue

// tag::has_get_referenced_issue[]

// end::has_get_referenced_issue[]


=== has_history

// tag::has_history[]

// end::has_history[]


=== has_history_columns

// tag::has_history_columns[]

// end::has_history_columns[]


=== InheritanceType

// tag::inheritancetype[]

// end::inheritancetype[]


=== is_persistence

// tag::is_persistence[]

// end::is_persistence[]


=== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]

// end::is_persistence_check_duplicate_per_pk[]


=== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]

// end::is_persistence_check_for_empty_source[]


=== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]

// end::is_persistence_delete_changed[]


=== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]

// end::is_persistence_delete_missing[]


=== is_persistence_insert

// tag::is_persistence_insert[]

// end::is_persistence_insert[]


=== is_persistence_truncate

// tag::is_persistence_truncate[]

// end::is_persistence_truncate[]


=== is_persistence_update_changed

// tag::is_persistence_update_changed[]

// end::is_persistence_update_changed[]


=== is_repo_managed

// tag::is_repo_managed[]
0
// end::is_repo_managed[]


=== is_ssas

// tag::is_ssas[]
0
// end::is_ssas[]


=== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


=== MS_Description

// tag::ms_description[]

// end::ms_description[]


=== persistence_source_RepoObject_fullname

// tag::persistence_source_repoobject_fullname[]

// end::persistence_source_repoobject_fullname[]


=== persistence_source_RepoObject_fullname2

// tag::persistence_source_repoobject_fullname2[]

// end::persistence_source_repoobject_fullname2[]


=== persistence_source_RepoObject_guid

// tag::persistence_source_repoobject_guid[]

// end::persistence_source_repoobject_guid[]


=== persistence_source_RepoObject_xref

// tag::persistence_source_repoobject_xref[]

// end::persistence_source_repoobject_xref[]


=== pk_index_guid

// tag::pk_index_guid[]

// end::pk_index_guid[]


=== pk_IndexPatternColumnDatatype

// tag::pk_indexpatterncolumndatatype[]

// end::pk_indexpatterncolumndatatype[]


=== pk_IndexPatternColumnName

// tag::pk_indexpatterncolumnname[]

// end::pk_indexpatterncolumnname[]


=== pk_IndexSemanticGroup

// tag::pk_indexsemanticgroup[]

// end::pk_indexsemanticgroup[]


=== ReferencedObjectList

// tag::referencedobjectlist[]
* [config].[ftv_dwh_database]
* [repo_sys].[ExtendedProperties]
* [repo_sys].[SysObject]
* [sys_dwh].[columns]
* [sys_dwh].[computed_columns]
* [sys_dwh].[default_constraints]
* [sys_dwh].[identity_columns]
* [sys_dwh].[types]
// end::referencedobjectlist[]


=== usp_persistence_RepoObject_guid

// tag::usp_persistence_repoobject_guid[]

// end::usp_persistence_repoobject_guid[]


=== UspExamples

// tag::uspexamples[]

// end::uspexamples[]


=== uspgenerator_usp_id

// tag::uspgenerator_usp_id[]

// end::uspgenerator_usp_id[]


=== UspParameters

// tag::uspparameters[]

// end::uspparameters[]

== Boolean Attributes

source: property.RepoObjectProperty WHERE property_int = 1

// tag::boolean_attributes[]


// end::boolean_attributes[]

== PlantUML diagrams

=== PlantUML Entity

// tag::puml_entity[]
[plantuml, entity-{docname}, svg, subs=macros]
....
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:repo_sys.syscolumn.adoc[]" as repo_sys.SysColumn << V >> {
  collation_name : (sysname)
  column_encryption_key_database_name : (sysname)
  column_encryption_key_id : (int)
  default_definition : (nvarchar(max))
  default_is_system_named : (bit)
  default_name : (sysname)
  - default_object_id : (int)
  default_parent_column_id : (int)
  definition : (nvarchar(max))
  encryption_algorithm_name : (sysname)
  encryption_type : (int)
  encryption_type_desc : (nvarchar(64))
  generated_always_type : (tinyint)
  generated_always_type_desc : (nvarchar(60))
  graph_type : (int)
  graph_type_desc : (nvarchar(60))
  increment_value : (sql_variant)
  - is_ansi_padded : (bit)
  is_column_set : (bit)
  - is_computed : (bit)
  is_dts_replicated : (bit)
  - is_filestream : (bit)
  is_hidden : (bit)
  - is_identity : (bit)
  - is_masked : (bit)
  is_merge_published : (bit)
  is_non_sql_subscribed : (bit)
  is_nullable : (bit)
  is_persisted : (bit)
  is_replicated : (bit)
  - is_rowguidcol : (bit)
  is_sparse : (bit)
  - is_xml_document : (bit)
  last_value : (sql_variant)
  - max_length : (smallint)
  - precision : (tinyint)
  - rule_object_id : (int)
  - scale : (tinyint)
  seed_value : (sql_variant)
  - SysObject_column_id : (int)
  SysObject_column_name : (sysname)
  SysObject_fullname : (nvarchar(517))
  SysObject_fullname2 : (nvarchar(257))
  - SysObject_id : (int)
  SysObject_name : (nvarchar(128))
  SysObject_RepoObject_guid : (uniqueidentifier)
  SysObject_RepoObjectColumn_guid : (uniqueidentifier)
  SysObject_schema_name : (nvarchar(128))
  SysObject_type : (char(2))
  SysObject_type_desc : (nvarchar(60))
  - system_type_id : (tinyint)
  user_type_fullname : (nvarchar(182))
  - user_type_id : (int)
  user_type_name : (sysname)
  uses_database_collation : (bit)
  - xml_collection_id : (int)
  --
}
....

// end::puml_entity[]

=== PlantUML Entity 1 1 FK

// tag::puml_entity_1_1_fk[]
[plantuml, entity_1_1_fk-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:repo_sys.syscolumn.adoc[]" as repo_sys.SysColumn << V >> {

}



footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_fk[]

=== PlantUML 1 1 ObjectRef

// tag::puml_entity_1_1_objectref[]
[plantuml, entity_1_1_objectref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:config.ftv_dwh_database.adoc[]" as config.ftv_dwh_database << IF >> {
  --
}

entity "puml-link:dhw:sqldb:repo.syscolumn_repoobjectcolumn_via_guid.adoc[]" as repo.SysColumn_RepoObjectColumn_via_guid << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.syscolumn_repoobjectcolumn_via_name.adoc[]" as repo.SysColumn_RepoObjectColumn_via_name << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_sync_guid_repoobjectcolumn.adoc[]" as repo.usp_sync_guid_RepoObjectColumn << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo_sys.extendedproperties.adoc[]" as repo_sys.ExtendedProperties << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo_sys.foreignkeycolumn.adoc[]" as repo_sys.ForeignKeyColumn << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo_sys.syscolumn.adoc[]" as repo_sys.SysColumn << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo_sys.sysobject.adoc[]" as repo_sys.SysObject << V >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.columns.adoc[]" as sys_dwh.columns << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.computed_columns.adoc[]" as sys_dwh.computed_columns << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.default_constraints.adoc[]" as sys_dwh.default_constraints << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.identity_columns.adoc[]" as sys_dwh.identity_columns << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.types.adoc[]" as sys_dwh.types << SN >> {
  --
}

config.ftv_dwh_database <.. repo_sys.SysColumn
repo_sys.ExtendedProperties <.. repo_sys.SysColumn
repo_sys.SysColumn <.. repo.SysColumn_RepoObjectColumn_via_guid
repo_sys.SysColumn <.. repo.SysColumn_RepoObjectColumn_via_name
repo_sys.SysColumn <.. repo.usp_sync_guid_RepoObjectColumn
repo_sys.SysColumn <.. repo_sys.ForeignKeyColumn
repo_sys.SysObject <.. repo_sys.SysColumn
sys_dwh.columns <.. repo_sys.SysColumn
sys_dwh.computed_columns <.. repo_sys.SysColumn
sys_dwh.default_constraints <.. repo_sys.SysColumn
sys_dwh.identity_columns <.. repo_sys.SysColumn
sys_dwh.types <.. repo_sys.SysColumn

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_objectref[]

=== PlantUML 30 0 ObjectRef

// tag::puml_entity_30_0_objectref[]
[plantuml, entity_30_0_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:config.ftv_dwh_database.adoc[]" as config.ftv_dwh_database << IF >> {
  --
}

entity "puml-link:dhw:sqldb:config.parameter.adoc[]" as config.Parameter << U >> {
  - **Parameter_name** : (varchar(100))
  - **sub_Parameter** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:configt.parameter_default.adoc[]" as configT.Parameter_default << V >> {
  - **Parameter_name** : (varchar(52))
  - **sub_Parameter** : (nvarchar(26))
  --
}

entity "puml-link:dhw:sqldb:repo_sys.extendedproperties.adoc[]" as repo_sys.ExtendedProperties << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo_sys.syscolumn.adoc[]" as repo_sys.SysColumn << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo_sys.sysobject.adoc[]" as repo_sys.SysObject << V >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.columns.adoc[]" as sys_dwh.columns << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.computed_columns.adoc[]" as sys_dwh.computed_columns << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.default_constraints.adoc[]" as sys_dwh.default_constraints << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.extended_properties.adoc[]" as sys_dwh.extended_properties << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.identity_columns.adoc[]" as sys_dwh.identity_columns << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.indexes.adoc[]" as sys_dwh.indexes << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.objects.adoc[]" as sys_dwh.objects << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.parameters.adoc[]" as sys_dwh.parameters << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.schemas.adoc[]" as sys_dwh.schemas << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.sql_modules.adoc[]" as sys_dwh.sql_modules << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.tables.adoc[]" as sys_dwh.tables << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.types.adoc[]" as sys_dwh.types << SN >> {
  --
}

config.ftv_dwh_database <.. repo_sys.ExtendedProperties
config.ftv_dwh_database <.. repo_sys.SysColumn
config.Parameter <.. config.ftv_dwh_database
configT.Parameter_default <.. config.Parameter
repo_sys.ExtendedProperties <.. repo_sys.SysObject
repo_sys.ExtendedProperties <.. repo_sys.SysColumn
repo_sys.SysObject <.. repo_sys.SysColumn
sys_dwh.columns <.. repo_sys.ExtendedProperties
sys_dwh.columns <.. repo_sys.SysColumn
sys_dwh.computed_columns <.. repo_sys.SysColumn
sys_dwh.default_constraints <.. repo_sys.SysColumn
sys_dwh.extended_properties <.. repo_sys.ExtendedProperties
sys_dwh.identity_columns <.. repo_sys.SysColumn
sys_dwh.indexes <.. repo_sys.ExtendedProperties
sys_dwh.objects <.. repo_sys.SysObject
sys_dwh.objects <.. repo_sys.ExtendedProperties
sys_dwh.parameters <.. repo_sys.ExtendedProperties
sys_dwh.schemas <.. repo_sys.ExtendedProperties
sys_dwh.schemas <.. repo_sys.SysObject
sys_dwh.sql_modules <.. repo_sys.SysObject
sys_dwh.tables <.. repo_sys.SysObject
sys_dwh.types <.. repo_sys.SysColumn

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_30_0_objectref[]

=== PlantUML 0 30 ObjectRef

// tag::puml_entity_0_30_objectref[]
[plantuml, entity_0_30_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:dmdocs.unit.adoc[]" as dmdocs.unit << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.antoranavlistpage_by_schema.adoc[]" as docs.AntoraNavListPage_by_schema << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.antoranavlistpage_by_type.adoc[]" as docs.AntoraNavListPage_by_type << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.antoranavlistrepoobject_by_schema.adoc[]" as docs.AntoraNavListRepoObject_by_schema << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.antoranavlistrepoobject_by_schema_type.adoc[]" as docs.AntoraNavListRepoObject_by_schema_type << V >> {
  - **RepoObject_schema_name** : (nvarchar(128))
  **type** : (char(2))
  --
}

entity "puml-link:dhw:sqldb:docs.antoranavlistrepoobject_by_type.adoc[]" as docs.AntoraNavListRepoObject_by_type << V >> {
  **type** : (char(2))
  --
}

entity "puml-link:dhw:sqldb:docs.antorapage_indexsemanticgroup.adoc[]" as docs.AntoraPage_IndexSemanticGroup << V >> {
  - **page_content** : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:docs.antorapage_objectbyschema.adoc[]" as docs.AntoraPage_ObjectBySchema << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.antorapage_objectbytype.adoc[]" as docs.AntoraPage_ObjectByType << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.foreignkey_relationscript.adoc[]" as docs.ForeignKey_RelationScript << V >> {
  **referenced_RepoObject_guid** : (uniqueidentifier)
  **referencing_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:docs.ftv_repoobject_reference_plantuml_entityreflist.adoc[]" as docs.ftv_RepoObject_Reference_PlantUml_EntityRefList << IF >> {
  --
}

entity "puml-link:dhw:sqldb:docs.indexsemanticgroup.adoc[]" as docs.IndexSemanticgroup << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.indexsemanticgrouppatterndatatype.adoc[]" as docs.IndexSemanticgroupPatterndatatype << V >> {
  **IndexSemanticGroup** : (nvarchar(512))
  **IndexPatternColumnDatatype** : (nvarchar(4000))
  --
}

entity "puml-link:dhw:sqldb:docs.objectrefcyclic.adoc[]" as docs.ObjectRefCyclic << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.objectrefcyclic_entitylist.adoc[]" as docs.ObjectRefCyclic_EntityList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.objectrefcyclic_objectreflist.adoc[]" as docs.ObjectRefCyclic_ObjectRefList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_adoc.adoc[]" as docs.RepoObject_Adoc << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_adoc_t.adoc[]" as docs.RepoObject_Adoc_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_antoraxrefcultureslist.adoc[]" as docs.RepoObject_AntoraXrefCulturesList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_columnlist.adoc[]" as docs.RepoObject_ColumnList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_columnlist_t.adoc[]" as docs.RepoObject_ColumnList_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_indexlist.adoc[]" as docs.RepoObject_IndexList << V >> {
  **RepoObject_guid** : (uniqueidentifier)
  **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_indexlist_t.adoc[]" as docs.RepoObject_IndexList_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_measuredescriptionlist.adoc[]" as docs.RepoObject_MeasureDescriptionList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_measurelist.adoc[]" as docs.RepoObject_MeasureList << V >> {
  **RepoObject_guid** : (uniqueidentifier)
  **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_outputfilter.adoc[]" as docs.RepoObject_OutputFilter << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_outputfilter_t.adoc[]" as docs.RepoObject_OutputFilter_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_outputfilter_t_gross.adoc[]" as docs.RepoObject_OutputFilter_T_gross << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml.adoc[]" as docs.RepoObject_Plantuml << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_colreflist_1_1.adoc[]" as docs.RepoObject_Plantuml_ColRefList_1_1 << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_entity.adoc[]" as docs.RepoObject_Plantuml_Entity << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_entity_t.adoc[]" as docs.RepoObject_Plantuml_Entity_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_fkreflist.adoc[]" as docs.RepoObject_PlantUml_FkRefList << V >> {
  **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_objectreflist_0_30.adoc[]" as docs.RepoObject_Plantuml_ObjectRefList_0_30 << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_objectreflist_1_1.adoc[]" as docs.RepoObject_Plantuml_ObjectRefList_1_1 << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_objectreflist_30_0.adoc[]" as docs.RepoObject_Plantuml_ObjectRefList_30_0 << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_pumlentityfklist.adoc[]" as docs.RepoObject_PlantUml_PumlEntityFkList << V >> {
  **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_t.adoc[]" as docs.RepoObject_Plantuml_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.schema_entitylist.adoc[]" as docs.Schema_EntityList << V >> {
  - **RepoObject_schema_name** : (nvarchar(128))
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.schema_puml.adoc[]" as docs.Schema_puml << V >> {
  - **RepoSchema_guid** : (uniqueidentifier)
  **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.schema_pumlpartial_fkreflist.adoc[]" as docs.Schema_PumlPartial_FkRefList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.schema_ssasrelationlist.adoc[]" as docs.Schema_SsasRelationList << V >> {
  - **SchemaName** : (nvarchar(128))
  **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.unit_1_union.adoc[]" as docs.Unit_1_union << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.unit_2.adoc[]" as docs.Unit_2 << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.unit_3.adoc[]" as docs.Unit_3 << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport.adoc[]" as docs.usp_AntoraExport << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_objectnavigation.adoc[]" as docs.usp_AntoraExport_ObjectNavigation << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_objectpage.adoc[]" as docs.usp_AntoraExport_ObjectPage << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_objectpartialscontent.adoc[]" as docs.usp_AntoraExport_ObjectPartialsContent << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_objectpuml.adoc[]" as docs.usp_AntoraExport_ObjectPuml << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_repoobject_adoc_t.adoc[]" as docs.usp_PERSIST_RepoObject_Adoc_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_repoobject_columnlist_t.adoc[]" as docs.usp_PERSIST_RepoObject_ColumnList_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_repoobject_indexlist_t.adoc[]" as docs.usp_PERSIST_RepoObject_IndexList_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_repoobject_outputfilter_t.adoc[]" as docs.usp_PERSIST_RepoObject_OutputFilter_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_repoobject_plantuml_entity_t.adoc[]" as docs.usp_PERSIST_RepoObject_Plantuml_Entity_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_repoobject_plantuml_t.adoc[]" as docs.usp_PERSIST_RepoObject_Plantuml_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty_collect_source_rogross.adoc[]" as property.RepoObjectProperty_Collect_source_ROGross << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **property_name** : (varchar(39))
  --
}

entity "puml-link:dhw:sqldb:property.usp_repoobject_inheritance.adoc[]" as property.usp_RepoObject_Inheritance << P >> {
  --
}

entity "puml-link:dhw:sqldb:property.usp_repoobjectproperty_collect.adoc[]" as property.usp_RepoObjectProperty_collect << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.ftv_repoobject_columreferencerepoobject.adoc[]" as reference.ftv_RepoObject_ColumReferenceRepoObject << IF >> {
  --
}

entity "puml-link:dhw:sqldb:reference.ftv_repoobject_dbmlcolumnrelation.adoc[]" as reference.ftv_RepoObject_DbmlColumnRelation << IF >> {
  --
}

entity "puml-link:dhw:sqldb:reference.ftv_repoobject_referencetree.adoc[]" as reference.ftv_RepoObject_ReferenceTree << IF >> {
  --
}

entity "puml-link:dhw:sqldb:reference.ftv_repoobject_referencetree_referenced.adoc[]" as reference.ftv_RepoObject_ReferenceTree_referenced << IF >> {
  --
}

entity "puml-link:dhw:sqldb:reference.ftv_repoobject_referencetree_referencing.adoc[]" as reference.ftv_RepoObject_ReferenceTree_referencing << IF >> {
  --
}

entity "puml-link:dhw:sqldb:reference.ftv_repoobject_referencetree_via_fullname.adoc[]" as reference.ftv_RepoObject_ReferenceTree_via_fullname << IF >> {
  --
}

entity "puml-link:dhw:sqldb:reference.ftv_repoobjectcolumn_referencetree.adoc[]" as reference.ftv_RepoObjectColumn_ReferenceTree << IF >> {
  --
}

entity "puml-link:dhw:sqldb:reference.persistence.adoc[]" as reference.Persistence << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.persistence_bidirectional.adoc[]" as reference.Persistence_bidirectional << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.referencetree_cyclic_ref_persistenceusp.adoc[]" as reference.ReferenceTree_cyclic_ref_PersistenceUsp << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.referencetree_cyclic_union.adoc[]" as reference.ReferenceTree_cyclic_union << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_reference.adoc[]" as reference.RepoObject_reference << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_reference_persistence_target_as_source.adoc[]" as reference.RepoObject_reference_persistence_target_as_source << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_reference_persistence_target_as_source_explicit.adoc[]" as reference.RepoObject_reference_persistence_target_as_source_explicit << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_reference_sqlexpressiondependencies.adoc[]" as reference.RepoObject_reference_SqlExpressionDependencies << V >> {
  **referenced_RepoObject_guid** : (uniqueidentifier)
  **referencing_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_reference_t.adoc[]" as reference.RepoObject_reference_T << U >> {
  - **referenced_RepoObject_guid** : (uniqueidentifier)
  - **referencing_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_reference_t_bidirectional.adoc[]" as reference.RepoObject_reference_T_bidirectional << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_reference_union.adoc[]" as reference.RepoObject_reference_union << V >> {
  **referenced_RepoObject_guid** : (uniqueidentifier)
  **referencing_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_referencedlist.adoc[]" as reference.RepoObject_ReferencedList << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_referencedreferencing.adoc[]" as reference.RepoObject_ReferencedReferencing << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_referencetree_0_30.adoc[]" as reference.RepoObject_ReferenceTree_0_30 << V >> {
  **RepoObject_guid** : (uniqueidentifier)
  **Referencing_guid** : (uniqueidentifier)
  **Referenced_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_referencetree_0_30_t.adoc[]" as reference.RepoObject_ReferenceTree_0_30_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **Referencing_guid** : (uniqueidentifier)
  - **Referenced_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_referencetree_30_0.adoc[]" as reference.RepoObject_ReferenceTree_30_0 << V >> {
  **RepoObject_guid** : (uniqueidentifier)
  **Referencing_guid** : (uniqueidentifier)
  **Referenced_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_referencetree_30_0_t.adoc[]" as reference.RepoObject_ReferenceTree_30_0_T << U >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_referencetree_referenced.adoc[]" as reference.RepoObject_ReferenceTree_referenced << V >> {
  **RepoObject_guid** : (uniqueidentifier)
  **Referenced_Depth** : (int)
  **Referencing_Depth** : (int)
  **Referenced_guid** : (uniqueidentifier)
  **Referencing_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_referencetree_referenced_30_0.adoc[]" as reference.RepoObject_ReferenceTree_referenced_30_0 << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  **Referenced_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_referencetree_referencing.adoc[]" as reference.RepoObject_ReferenceTree_referencing << V >> {
  **RepoObject_guid** : (uniqueidentifier)
  **Referenced_Depth** : (int)
  **Referencing_Depth** : (int)
  **Referenced_guid** : (uniqueidentifier)
  **Referencing_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_referencetree_referencing_0_30.adoc[]" as reference.RepoObject_ReferenceTree_referencing_0_30 << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  **Referencing_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_referencinglist.adoc[]" as reference.RepoObject_ReferencingList << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_reference.adoc[]" as reference.RepoObjectColumn_reference << V >> {
  **referenced_RepoObjectColumn_guid** : (uniqueidentifier)
  **referencing_RepoObjectColumn_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_reference_additional.adoc[]" as reference.RepoObjectColumn_reference_additional << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_reference_additional_internal.adoc[]" as reference.RepoObjectColumn_reference_additional_internal << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_reference_bysamepredecessors.adoc[]" as reference.RepoObjectColumn_reference_BySamePredecessors << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_reference_firstresultset.adoc[]" as reference.RepoObjectColumn_reference_FirstResultSet << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_reference_queryplan.adoc[]" as reference.RepoObjectColumn_reference_QueryPlan << V >> {
  **referencing_id** : (int)
  **referencing_minor_id** : (int)
  **referenced_id** : (int)
  **referenced_minor_id** : (int)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_reference_sqlexpressiondependencies.adoc[]" as reference.RepoObjectColumn_reference_SqlExpressionDependencies << V >> {
  - **referencing_id** : (int)
  - **referencing_minor_id** : (int)
  **referenced_id** : (int)
  - **referenced_minor_id** : (int)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_reference_t.adoc[]" as reference.RepoObjectColumn_reference_T << U >> {
  - **referenced_RepoObjectColumn_guid** : (uniqueidentifier)
  - **referencing_RepoObjectColumn_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_reference_union.adoc[]" as reference.RepoObjectColumn_reference_union << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_reference_virtual.adoc[]" as reference.RepoObjectColumn_reference_virtual << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_referencedlist.adoc[]" as reference.RepoObjectColumn_ReferencedList << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_referencedreferencing.adoc[]" as reference.RepoObjectColumn_ReferencedReferencing << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_referencetree.adoc[]" as reference.RepoObjectColumn_ReferenceTree << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_referencinglist.adoc[]" as reference.RepoObjectColumn_ReferencingList << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_relationscript.adoc[]" as reference.RepoObjectColumn_RelationScript << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.sysobjectcolumn_queryplanexpression.adoc[]" as reference.SysObjectColumn_QueryPlanExpression << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_persist_repoobject_reference_t.adoc[]" as reference.usp_PERSIST_RepoObject_reference_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_persist_repoobject_referencetree_0_30_t.adoc[]" as reference.usp_PERSIST_RepoObject_ReferenceTree_0_30_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_persist_repoobject_referencetree_30_0_t.adoc[]" as reference.usp_PERSIST_RepoObject_ReferenceTree_30_0_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_persist_repoobjectcolumn_reference_t.adoc[]" as reference.usp_PERSIST_RepoObjectColumn_reference_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_repoobject_referencetree.adoc[]" as reference.usp_RepoObject_ReferenceTree << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_repoobject_referencetree_insert.adoc[]" as reference.usp_RepoObject_ReferenceTree_insert << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_repoobject_update_sysobjectqueryplan.adoc[]" as reference.usp_RepoObject_update_SysObjectQueryPlan << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_repoobjectsource_firstresultset.adoc[]" as reference.usp_RepoObjectSource_FirstResultSet << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_repoobjectsource_queryplan.adoc[]" as reference.usp_RepoObjectSource_QueryPlan << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.check_indexcolumn_virtual_referenced_setpoint.adoc[]" as repo.check_IndexColumn_virtual_referenced_setpoint << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.foreignkey_gross.adoc[]" as repo.ForeignKey_gross << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.foreignkey_indexes.adoc[]" as repo.ForeignKey_Indexes << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.foreignkey_indexes_union.adoc[]" as repo.ForeignKey_Indexes_union << V >> {
  **ForeignKey_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.foreignkey_indexes_union_t.adoc[]" as repo.ForeignKey_Indexes_union_T << U >> {
  **ForeignKey_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.foreignkey_indexpattern.adoc[]" as repo.ForeignKey_IndexPattern << V >> {
  - **constraint_object_id** : (int)
  **ForeignKey_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.foreignkey_virtual_indexes.adoc[]" as repo.ForeignKey_virtual_Indexes << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.index_columlist.adoc[]" as repo.Index_ColumList << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.index_columlist_t.adoc[]" as repo.Index_ColumList_T << U >> {
  - **index_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.index_gross.adoc[]" as repo.Index_gross << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.index_indexpattern.adoc[]" as repo.Index_IndexPattern << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.index_referencing_indexpatterncolumnguid.adoc[]" as repo.Index_referencing_IndexPatternColumnGuid << V >> {
  **source_index_guid** : (uniqueidentifier)
  **referencing_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.index_settings_forupdate.adoc[]" as repo.Index_Settings_ForUpdate << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.index_sqlconstraint_pkuq.adoc[]" as repo.Index_SqlConstraint_PkUq << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.index_union.adoc[]" as repo.Index_union << V >> {
  **index_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.index_unique_indexpatterncolumnguid.adoc[]" as repo.Index_unique_IndexPatternColumnGuid << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.index_virtual_forupdate.adoc[]" as repo.Index_virtual_ForUpdate << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.indexcolumn_referencedreferencing_hasfullcolumnsinreferencing.adoc[]" as repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing << V >> {
  - **index_guid** : (uniqueidentifier)
  - **index_column_id** : (int)
  **RowNumberInReferencing** : (bigint)
  --
}

entity "puml-link:dhw:sqldb:repo.indexcolumn_referencedreferencing_hasfullcolumnsinreferencing_check.adoc[]" as repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_check << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.indexcolumn_referencedreferencing_hasfullcolumnsinreferencing_t.adoc[]" as repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T << U >> {
  **index_guid** : (uniqueidentifier)
  - **index_column_id** : (int)
  **RowNumberInReferencing** : (bigint)
  --
}

entity "puml-link:dhw:sqldb:repo.indexcolumn_union.adoc[]" as repo.IndexColumn_union << V >> {
  **index_guid** : (uniqueidentifier)
  - **index_column_id** : (int)
  --
}

entity "puml-link:dhw:sqldb:repo.indexcolumn_union_t.adoc[]" as repo.IndexColumn_union_T << U >> {
  - **index_guid** : (uniqueidentifier)
  - **index_column_id** : (int)
  --
}

entity "puml-link:dhw:sqldb:repo.indexcolumn_virtual_referenced_setpoint.adoc[]" as repo.IndexColumn_virtual_referenced_setpoint << V >> {
  - **index_guid** : (uniqueidentifier)
  - **index_column_id** : (int)
  --
}

entity "puml-link:dhw:sqldb:repo.indexreferencedreferencing.adoc[]" as repo.IndexReferencedReferencing << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.indexreferencedreferencing_hasfullcolumnsinreferencing.adoc[]" as repo.IndexReferencedReferencing_HasFullColumnsInReferencing << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_columnlist.adoc[]" as repo.RepoObject_ColumnList << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_gross.adoc[]" as repo.RepoObject_gross << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_gross2.adoc[]" as repo.RepoObject_gross2 << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_related_fk_union.adoc[]" as repo.RepoObject_related_FK_union << V >> {
  **RepoObject_guid** : (uniqueidentifier)
  **included_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_sat2.adoc[]" as repo.RepoObject_sat2 << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_sat2_t.adoc[]" as repo.RepoObject_sat2_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_sqlcreatetable.adoc[]" as repo.RepoObject_SqlCreateTable << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_wo_referencing.adoc[]" as repo.RepoObject_wo_referencing << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn_gross2.adoc[]" as repo.RepoObjectColumn_gross2 << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn_missingsource_typev.adoc[]" as repo.RepoObjectColumn_MissingSource_TypeV << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.syscolumn_repoobjectcolumn_via_guid.adoc[]" as repo.SysColumn_RepoObjectColumn_via_guid << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.syscolumn_repoobjectcolumn_via_name.adoc[]" as repo.SysColumn_RepoObjectColumn_via_name << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_index_finish.adoc[]" as repo.usp_Index_finish << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_index_foreignkey.adoc[]" as repo.usp_Index_ForeignKey << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_index_inheritance.adoc[]" as repo.usp_index_inheritance << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_index_settings.adoc[]" as repo.usp_Index_Settings << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_index_virtual_set.adoc[]" as repo.usp_Index_virtual_set << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_main.adoc[]" as repo.usp_main << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_persist_foreignkey_indexes_union_t.adoc[]" as repo.usp_PERSIST_ForeignKey_Indexes_union_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_persist_index_columlist_t.adoc[]" as repo.usp_PERSIST_Index_ColumList_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_persist_indexcolumn_referencedreferencing_hasfullcolumnsinreferencing_t.adoc[]" as repo.usp_PERSIST_IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_persist_indexcolumn_union_t.adoc[]" as repo.usp_PERSIST_IndexColumn_union_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_persist_repoobject_sat2_t.adoc[]" as repo.usp_PERSIST_RepoObject_sat2_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_persistence_set.adoc[]" as repo.usp_persistence_set << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_sync_guid.adoc[]" as repo.usp_sync_guid << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_sync_guid_repoobjectcolumn.adoc[]" as repo.usp_sync_guid_RepoObjectColumn << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo_sys.foreignkeycolumn.adoc[]" as repo_sys.ForeignKeyColumn << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo_sys.indexcolumn_unique.adoc[]" as repo_sys.IndexColumn_unique << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo_sys.sql_expression_dependencies.adoc[]" as repo_sys.sql_expression_dependencies << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo_sys.syscolumn.adoc[]" as repo_sys.SysColumn << V >> {
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.generatoruspstep_persistence_isinactive_setpoint.adoc[]" as uspgenerator.GeneratorUspStep_Persistence_IsInactive_setpoint << V >> {
  - **usp_id** : (int)
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.generatoruspstep_persistence_src.adoc[]" as uspgenerator.GeneratorUspStep_Persistence_src << V >> {
  - **usp_id** : (int)
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.usp_generatorusp_insert_update_persistence.adoc[]" as uspgenerator.usp_GeneratorUsp_insert_update_persistence << P >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.biml_package.adoc[]" as workflow.Biml_Package << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.biml_precedenceconstraints.adoc[]" as workflow.Biml_PrecedenceConstraints << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.biml_project.adoc[]" as workflow.Biml_Project << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.biml_task.adoc[]" as workflow.Biml_Task << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.proceduredependency.adoc[]" as workflow.ProcedureDependency << U >> {
  - **id** : (int)
  --
}

entity "puml-link:dhw:sqldb:workflow.proceduredependency_gross.adoc[]" as workflow.ProcedureDependency_gross << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.proceduredependency_input_persistencedependency.adoc[]" as workflow.ProcedureDependency_input_PersistenceDependency << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.proceduredependency_input_persistencedependency_s.adoc[]" as workflow.ProcedureDependency_input_PersistenceDependency_S << V >> {
  **referenced_Procedure_RepoObject_guid** : (uniqueidentifier)
  **referencing_Procedure_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:workflow.proceduredependency_persistencedependency_src.adoc[]" as workflow.ProcedureDependency_PersistenceDependency_src << V >> {
  **referenced_Procedure_RepoObject_guid** : (uniqueidentifier)
  **referencing_Procedure_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:workflow.proceduredependency_persistencedependency_tgt.adoc[]" as workflow.ProcedureDependency_PersistenceDependency_tgt << V >> {
  - **referenced_Procedure_RepoObject_guid** : (uniqueidentifier)
  - **referencing_Procedure_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:workflow.usp_persist_proceduredependency_persistencedependency_tgt.adoc[]" as workflow.usp_PERSIST_ProcedureDependency_PersistenceDependency_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.usp_persist_workflow_proceduredependency_t.adoc[]" as workflow.usp_PERSIST_Workflow_ProcedureDependency_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.usp_persist_workflowstep.adoc[]" as workflow.usp_PERSIST_WorkflowStep << P >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.usp_workflow.adoc[]" as workflow.usp_workflow << P >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.workflow_proceduredependency.adoc[]" as workflow.Workflow_ProcedureDependency << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.workflow_proceduredependency_all.adoc[]" as workflow.Workflow_ProcedureDependency_all << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.workflow_proceduredependency_t.adoc[]" as workflow.Workflow_ProcedureDependency_T << U >> {
  - **Workflow_id** : (int)
  - **referenced_Procedure_RepoObject_guid** : (uniqueidentifier)
  - **referencing_Procedure_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:workflow.workflow_proceduredependency_t_active.adoc[]" as workflow.Workflow_ProcedureDependency_T_active << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.workflow_proceduredependency_t_bidirectional.adoc[]" as workflow.Workflow_ProcedureDependency_T_bidirectional << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.workflow_proceduredependency_t_bidirectional_t.adoc[]" as workflow.Workflow_ProcedureDependency_T_bidirectional_T << U >> {
  - **Workflow_id** : (int)
  - **referenced_Procedure_RepoObject_guid** : (uniqueidentifier)
  - **referencing_Procedure_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:workflow.workflow_proceduredependency_t_notinsortorder.adoc[]" as workflow.Workflow_ProcedureDependency_T_NotInSortorder << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.workflow_proceduredependency_t_notinsortorder_check.adoc[]" as workflow.Workflow_ProcedureDependency_T_NotInSortorder_check << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.workflow_proceduredependency_t_redundant.adoc[]" as workflow.Workflow_ProcedureDependency_T_redundant << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.workflow_proceduredependency_t_taskname.adoc[]" as workflow.Workflow_ProcedureDependency_T_TaskName << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.workflow_proceduredependency_wo_redundant.adoc[]" as workflow.Workflow_ProcedureDependency_wo_redundant << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.workflowstep.adoc[]" as workflow.WorkflowStep << U >> {
  - **id** : (int)
  --
}

entity "puml-link:dhw:sqldb:workflow.workflowstep_active.adoc[]" as workflow.WorkflowStep_active << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.workflowstep_forupdate.adoc[]" as workflow.WorkflowStep_ForUpdate << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.workflowstep_src.adoc[]" as workflow.WorkflowStep_src << V >> {
  - **Workflow_id** : (int)
  **Procedure_RepoObject_guid** : (uniqueidentifier)
  --
}

docs.AntoraNavListPage_by_type <.. docs.usp_AntoraExport_ObjectNavigation
docs.AntoraNavListRepoObject_by_schema <.. docs.usp_AntoraExport_ObjectNavigation
docs.AntoraNavListRepoObject_by_schema <.. docs.AntoraPage_ObjectBySchema
docs.AntoraNavListRepoObject_by_schema_type <.. docs.usp_AntoraExport_ObjectNavigation
docs.AntoraNavListRepoObject_by_type <.. docs.usp_AntoraExport_ObjectNavigation
docs.AntoraNavListRepoObject_by_type <.. docs.AntoraPage_ObjectByType
docs.ftv_RepoObject_Reference_PlantUml_EntityRefList <.. docs.RepoObject_Plantuml
docs.IndexSemanticgroup <.. docs.AntoraPage_IndexSemanticGroup
docs.IndexSemanticgroupPatterndatatype <.. docs.IndexSemanticgroup
docs.ObjectRefCyclic_EntityList <.. docs.ObjectRefCyclic
docs.ObjectRefCyclic_ObjectRefList <.. docs.ObjectRefCyclic
docs.RepoObject_Adoc <.. docs.RepoObject_Adoc_T
docs.RepoObject_Adoc <.. docs.usp_PERSIST_RepoObject_Adoc_T
docs.REpoObject_Adoc_T <.. docs.usp_PERSIST_RepoObject_Adoc_T
docs.RepoObject_AntoraXrefCulturesList <.. docs.RepoObject_Adoc
docs.RepoObject_ColumnList <.. docs.RepoObject_ColumnList_T
docs.RepoObject_ColumnList <.. docs.usp_PERSIST_RepoObject_ColumnList_T
docs.RepoObject_ColumnList_T <.. docs.RepoObject_Adoc
docs.RepoObject_ColumnList_T <.. docs.usp_PERSIST_RepoObject_ColumnList_T
docs.RepoObject_ColumnList_T <.. docs.RepoObject_Plantuml_Entity
docs.RepoObject_IndexList <.. docs.usp_PERSIST_RepoObject_IndexList_T
docs.RepoObject_IndexList <.. docs.RepoObject_IndexList_T
docs.RepoObject_IndexList_T <.. docs.usp_PERSIST_RepoObject_IndexList_T
docs.RepoObject_IndexList_T <.. docs.RepoObject_Plantuml_Entity
docs.RepoObject_IndexList_T <.. docs.RepoObject_Adoc
docs.RepoObject_MeasureDescriptionList <.. docs.RepoObject_Adoc
docs.RepoObject_MeasureList <.. docs.RepoObject_Plantuml_Entity
docs.RepoObject_MeasureList <.. docs.RepoObject_Adoc
docs.RepoObject_OutputFilter <.. docs.usp_PERSIST_RepoObject_OutputFilter_T
docs.RepoObject_OutputFilter <.. docs.RepoObject_OutputFilter_T
docs.RepoObject_OutputFilter_T <.. docs.RepoObject_OutputFilter_T_gross
docs.RepoObject_OutputFilter_T <.. docs.usp_AntoraExport_ObjectPartialsContent
docs.RepoObject_OutputFilter_T <.. docs.RepoObject_AntoraXrefCulturesList
docs.RepoObject_OutputFilter_T <.. docs.usp_PERSIST_RepoObject_OutputFilter_T
docs.RepoObject_OutputFilter_T <.. docs.Unit_1_union
docs.RepoObject_OutputFilter_T <.. docs.Schema_SsasRelationList
docs.RepoObject_OutputFilter_T <.. docs.Schema_puml
docs.RepoObject_OutputFilter_T <.. docs.RepoObject_Plantuml_ColRefList_1_1
docs.RepoObject_OutputFilter_T <.. docs.AntoraNavListPage_by_schema
docs.RepoObject_OutputFilter_T <.. docs.IndexSemanticgroupPatterndatatype
docs.RepoObject_OutputFilter_T <.. docs.AntoraNavListPage_by_type
docs.RepoObject_OutputFilter_T <.. docs.RepoObject_IndexList
docs.RepoObject_OutputFilter_T <.. docs.RepoObject_Plantuml
docs.RepoObject_OutputFilter_T <.. docs.RepoObject_Plantuml_Entity
docs.RepoObject_OutputFilter_T <.. docs.RepoObject_ColumnList
docs.RepoObject_OutputFilter_T <.. docs.AntoraNavListRepoObject_by_schema_type
docs.RepoObject_OutputFilter_T <.. docs.AntoraNavListRepoObject_by_schema
docs.RepoObject_OutputFilter_T <.. docs.AntoraNavListRepoObject_by_type
docs.RepoObject_OutputFilter_T <.. docs.usp_AntoraExport_ObjectPage
docs.RepoObject_OutputFilter_T_gross <.. docs.RepoObject_MeasureList
docs.RepoObject_OutputFilter_T_gross <.. docs.RepoObject_Adoc
docs.RepoObject_OutputFilter_T_gross <.. docs.RepoObject_MeasureDescriptionList
docs.RepoObject_Plantuml <.. docs.usp_PERSIST_RepoObject_Plantuml_T
docs.RepoObject_Plantuml <.. docs.RepoObject_Plantuml_T
docs.RepoObject_Plantuml_ColRefList_1_1 <.. docs.RepoObject_Plantuml
docs.RepoObject_Plantuml_Entity <.. docs.RepoObject_Plantuml_Entity_T
docs.RepoObject_Plantuml_Entity <.. docs.usp_PERSIST_RepoObject_Plantuml_Entity_T
docs.RepoObject_Plantuml_Entity_T <.. docs.RepoObject_Adoc
docs.RepoObject_Plantuml_Entity_T <.. docs.ObjectRefCyclic_EntityList
docs.RepoObject_Plantuml_Entity_T <.. docs.RepoObject_PlantUml_PumlEntityFkList
docs.RepoObject_Plantuml_Entity_T <.. docs.ftv_RepoObject_Reference_PlantUml_EntityRefList
docs.RepoObject_Plantuml_Entity_T <.. docs.usp_PERSIST_RepoObject_Plantuml_Entity_T
docs.RepoObject_Plantuml_Entity_T <.. docs.Schema_EntityList
docs.RepoObject_PlantUml_FkRefList <.. docs.RepoObject_Plantuml
docs.RepoObject_Plantuml_ObjectRefList_0_30 <.. docs.RepoObject_Plantuml
docs.RepoObject_Plantuml_ObjectRefList_1_1 <.. docs.RepoObject_Plantuml
docs.RepoObject_Plantuml_ObjectRefList_30_0 <.. docs.RepoObject_Plantuml
docs.RepoObject_PlantUml_PumlEntityFkList <.. docs.RepoObject_Plantuml
docs.RepoObject_Plantuml_T <.. docs.RepoObject_Adoc
docs.RepoObject_Plantuml_T <.. docs.usp_PERSIST_RepoObject_Plantuml_T
docs.Schema_EntityList <.. docs.Schema_puml
docs.Schema_puml <.. docs.AntoraNavListPage_by_schema
docs.Schema_PumlPartial_FkRefList <.. docs.Schema_puml
docs.Schema_SsasRelationList <.. docs.Schema_puml
docs.Unit_1_union <.. docs.Unit_2
docs.Unit_2 <.. docs.Unit_3
docs.Unit_3 <.. dmdocs.unit
docs.usp_AntoraExport_ObjectNavigation <.. docs.usp_AntoraExport
docs.usp_AntoraExport_ObjectPage <.. docs.usp_AntoraExport
docs.usp_AntoraExport_ObjectPartialsContent <.. docs.usp_AntoraExport
docs.usp_AntoraExport_ObjectPuml <.. docs.usp_AntoraExport
docs.usp_PERSIST_RepoObject_Adoc_T <.. docs.usp_AntoraExport_ObjectPartialsContent
docs.usp_PERSIST_RepoObject_ColumnList_T <.. docs.usp_AntoraExport_ObjectPartialsContent
docs.usp_PERSIST_RepoObject_IndexList_T <.. docs.usp_AntoraExport_ObjectPartialsContent
docs.usp_PERSIST_RepoObject_OutputFilter_T <.. docs.usp_AntoraExport
docs.usp_PERSIST_RepoObject_Plantuml_Entity_T <.. docs.usp_AntoraExport_ObjectPuml
docs.usp_PERSIST_RepoObject_Plantuml_T <.. docs.usp_AntoraExport_ObjectPuml
property.RepoObjectProperty_Collect_source_ROGross <.. property.usp_RepoObjectProperty_collect
property.usp_RepoObject_Inheritance <.. repo.usp_main
property.usp_RepoObjectProperty_collect <.. property.usp_RepoObject_Inheritance
property.usp_RepoObjectProperty_collect <.. repo.usp_main
reference.ftv_RepoObject_ReferenceTree <.. reference.RepoObject_ReferenceTree_30_0
reference.ftv_RepoObject_ReferenceTree <.. reference.RepoObject_ReferenceTree_0_30
reference.ftv_RepoObject_ReferenceTree_referenced <.. reference.RepoObject_ReferenceTree_referenced_30_0
reference.ftv_RepoObject_ReferenceTree_referenced <.. reference.RepoObject_ReferenceTree_referenced
reference.ftv_RepoObject_ReferenceTree_referencing <.. reference.RepoObject_ReferenceTree_referencing_0_30
reference.ftv_RepoObject_ReferenceTree_referencing <.. reference.RepoObject_ReferenceTree_referencing
reference.ftv_RepoObjectColumn_ReferenceTree <.. reference.RepoObjectColumn_ReferenceTree
reference.Persistence <.. workflow.ProcedureDependency_PersistenceDependency_src
reference.Persistence <.. reference.Persistence_bidirectional
reference.Persistence <.. workflow.ProcedureDependency_input_PersistenceDependency_S
reference.ReferenceTree_cyclic_ref_PersistenceUsp <.. reference.ReferenceTree_cyclic_union
reference.ReferenceTree_cyclic_union <.. docs.ObjectRefCyclic_EntityList
reference.ReferenceTree_cyclic_union <.. docs.ObjectRefCyclic_ObjectRefList
reference.RepoObject_reference <.. reference.RepoObject_reference_T
reference.RepoObject_reference <.. reference.usp_PERSIST_RepoObject_reference_T
reference.RepoObject_reference_persistence_target_as_source <.. reference.RepoObject_reference_union
reference.RepoObject_reference_persistence_target_as_source <.. repo.usp_main
reference.RepoObject_reference_persistence_target_as_source <.. reference.RepoObject_reference
reference.RepoObject_reference_persistence_target_as_source_explicit <.. reference.RepoObject_reference
reference.RepoObject_reference_persistence_target_as_source_explicit <.. reference.RepoObject_reference_union
reference.RepoObject_reference_SqlExpressionDependencies <.. reference.RepoObject_reference_union
reference.RepoObject_reference_SqlExpressionDependencies <.. reference.RepoObject_reference_persistence_target_as_source_explicit
reference.RepoObject_reference_SqlExpressionDependencies <.. reference.RepoObject_reference_persistence_target_as_source
reference.RepoObject_reference_T <.. reference.RepoObjectColumn_reference_additional
reference.RepoObject_reference_T <.. reference.RepoObjectColumn_reference_additional_internal
reference.RepoObject_reference_T <.. repo.RepoObject_wo_referencing
reference.RepoObject_reference_T <.. reference.ReferenceTree_cyclic_ref_PersistenceUsp
reference.RepoObject_reference_T <.. reference.RepoObject_reference_T_bidirectional
reference.RepoObject_reference_T <.. docs.RepoObject_Plantuml_ObjectRefList_1_1
reference.RepoObject_reference_T <.. reference.usp_PERSIST_RepoObject_reference_T
reference.RepoObject_reference_T <.. reference.RepoObjectColumn_reference_virtual
reference.RepoObject_reference_T <.. docs.RepoObject_Plantuml_ObjectRefList_30_0
reference.RepoObject_reference_T <.. docs.RepoObject_Plantuml_ObjectRefList_0_30
reference.RepoObject_reference_T <.. reference.RepoObject_ReferencedReferencing
reference.RepoObject_reference_T <.. repo.usp_main
reference.RepoObject_reference_T <.. reference.RepoObjectColumn_reference_BySamePredecessors
reference.RepoObject_reference_T <.. reference.RepoObjectColumn_reference_QueryPlan
reference.RepoObject_reference_T <.. reference.RepoObjectColumn_reference_SqlExpressionDependencies
reference.RepoObject_reference_T <.. reference.RepoObjectColumn_reference_FirstResultSet
reference.RepoObject_reference_T <.. repo.IndexReferencedReferencing
reference.RepoObject_reference_union <.. reference.RepoObject_reference
reference.RepoObject_ReferencedList <.. repo.RepoObject_sat2
reference.RepoObject_ReferencedList <.. repo.RepoObject_gross2
reference.RepoObject_ReferencedReferencing <.. reference.usp_RepoObject_ReferenceTree_insert
reference.RepoObject_ReferencedReferencing <.. reference.ftv_RepoObject_ReferenceTree_referencing
reference.RepoObject_ReferencedReferencing <.. reference.ftv_RepoObject_ReferenceTree_via_fullname
reference.RepoObject_ReferencedReferencing <.. repo.RepoObject_gross
reference.RepoObject_ReferencedReferencing <.. reference.ftv_RepoObject_ReferenceTree_referenced
reference.RepoObject_ReferencedReferencing <.. reference.RepoObject_ReferencingList
reference.RepoObject_ReferencedReferencing <.. reference.RepoObject_ReferencedList
reference.RepoObject_ReferencedReferencing <.. reference.ftv_RepoObject_ReferenceTree
reference.RepoObject_ReferenceTree_0_30 <.. reference.RepoObject_ReferenceTree_0_30_T
reference.RepoObject_ReferenceTree_0_30 <.. reference.usp_PERSIST_RepoObject_ReferenceTree_0_30_T
reference.RepoObject_ReferenceTree_0_30_T <.. reference.usp_PERSIST_RepoObject_ReferenceTree_0_30_T
reference.RepoObject_ReferenceTree_30_0 <.. reference.usp_PERSIST_RepoObject_ReferenceTree_30_0_T
reference.RepoObject_ReferenceTree_30_0 <.. reference.RepoObject_ReferenceTree_30_0_T
reference.RepoObject_ReferenceTree_30_0_T <.. reference.usp_PERSIST_RepoObject_ReferenceTree_30_0_T
reference.RepoObject_ReferencingList <.. repo.RepoObject_sat2
reference.RepoObject_ReferencingList <.. repo.RepoObject_gross2
reference.RepoObjectColumn_reference <.. reference.usp_PERSIST_RepoObjectColumn_reference_T
reference.RepoObjectColumn_reference <.. reference.RepoObjectColumn_reference_T
reference.RepoObjectColumn_reference_additional <.. reference.RepoObjectColumn_reference_union
reference.RepoObjectColumn_reference_FirstResultSet <.. reference.RepoObjectColumn_reference_BySamePredecessors
reference.RepoObjectColumn_reference_QueryPlan <.. reference.SysObjectColumn_QueryPlanExpression
reference.RepoObjectColumn_reference_SqlExpressionDependencies <.. reference.RepoObjectColumn_reference_union
reference.RepoObjectColumn_reference_T <.. docs.RepoObject_Plantuml_ColRefList_1_1
reference.RepoObjectColumn_reference_T <.. reference.usp_PERSIST_RepoObjectColumn_reference_T
reference.RepoObjectColumn_reference_T <.. reference.RepoObjectColumn_ReferencedReferencing
reference.RepoObjectColumn_reference_T <.. reference.RepoObjectColumn_RelationScript
reference.RepoObjectColumn_reference_T <.. repo.RepoObjectColumn_MissingSource_TypeV
reference.RepoObjectColumn_reference_T <.. repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing
reference.RepoObjectColumn_reference_union <.. reference.RepoObjectColumn_reference
reference.RepoObjectColumn_reference_virtual <.. reference.RepoObjectColumn_reference_union
reference.RepoObjectColumn_ReferencedList <.. repo.RepoObjectColumn_gross2
reference.RepoObjectColumn_ReferencedReferencing <.. reference.RepoObjectColumn_ReferencingList
reference.RepoObjectColumn_ReferencedReferencing <.. reference.ftv_RepoObjectColumn_ReferenceTree
reference.RepoObjectColumn_ReferencedReferencing <.. reference.RepoObjectColumn_ReferencedList
reference.RepoObjectColumn_ReferencedReferencing <.. reference.ftv_RepoObject_DbmlColumnRelation
reference.RepoObjectColumn_ReferenceTree <.. reference.ftv_RepoObject_ColumReferenceRepoObject
reference.RepoObjectColumn_ReferencingList <.. repo.RepoObjectColumn_gross2
reference.RepoObjectColumn_RelationScript <.. reference.ftv_RepoObject_ColumReferenceRepoObject
reference.SysObjectColumn_QueryPlanExpression <.. reference.usp_RepoObjectSource_QueryPlan
reference.usp_PERSIST_RepoObject_reference_T <.. repo.usp_main
reference.usp_PERSIST_RepoObject_ReferenceTree_0_30_T <.. reference.usp_RepoObject_ReferenceTree
reference.usp_PERSIST_RepoObject_ReferenceTree_30_0_T <.. reference.usp_RepoObject_ReferenceTree
reference.usp_PERSIST_RepoObjectColumn_reference_T <.. repo.usp_main
reference.usp_RepoObject_ReferenceTree_insert <.. repo.usp_main
reference.usp_RepoObject_update_SysObjectQueryPlan <.. repo.usp_main
reference.usp_RepoObjectSource_FirstResultSet <.. repo.usp_main
reference.usp_RepoObjectSource_QueryPlan <.. repo.usp_main
repo.ForeignKey_gross <.. docs.RepoObject_IndexList
repo.ForeignKey_Indexes <.. repo.ForeignKey_Indexes_union
repo.ForeignKey_Indexes <.. repo.usp_Index_ForeignKey
repo.ForeignKey_Indexes_union <.. repo.usp_PERSIST_ForeignKey_Indexes_union_T
repo.ForeignKey_Indexes_union <.. repo.ForeignKey_Indexes_union_T
repo.ForeignKey_Indexes_union_T <.. repo.usp_Index_finish
repo.ForeignKey_Indexes_union_T <.. docs.Schema_PumlPartial_FkRefList
repo.ForeignKey_Indexes_union_T <.. repo.usp_PERSIST_ForeignKey_Indexes_union_T
repo.ForeignKey_Indexes_union_T <.. docs.RepoObject_PlantUml_FkRefList
repo.ForeignKey_Indexes_union_T <.. repo.RepoObject_related_FK_union
repo.ForeignKey_Indexes_union_T <.. repo.ForeignKey_gross
repo.ForeignKey_Indexes_union_T <.. docs.ForeignKey_RelationScript
repo.ForeignKey_IndexPattern <.. repo.ForeignKey_Indexes
repo.ForeignKey_virtual_Indexes <.. repo.ForeignKey_Indexes_union
repo.Index_ColumList <.. repo.Index_ColumList_T
repo.Index_ColumList <.. repo.usp_PERSIST_Index_ColumList_T
repo.Index_ColumList_T <.. repo.Index_SqlConstraint_PkUq
repo.Index_ColumList_T <.. uspgenerator.GeneratorUspStep_Persistence_src
repo.Index_ColumList_T <.. repo.Index_gross
repo.Index_ColumList_T <.. repo.usp_PERSIST_Index_ColumList_T
repo.Index_gross <.. repo.ForeignKey_gross
repo.Index_gross <.. docs.IndexSemanticgroupPatterndatatype
repo.Index_gross <.. docs.RepoObject_IndexList
repo.Index_gross <.. repo.usp_Index_finish
repo.Index_gross <.. repo.RepoObject_SqlCreateTable
repo.Index_gross <.. repo.ForeignKey_virtual_Indexes
repo.Index_gross <.. repo.ForeignKey_Indexes
repo.Index_gross <.. repo.usp_Index_virtual_set
repo.Index_gross <.. repo.usp_index_inheritance
repo.Index_IndexPattern <.. repo.usp_Index_Settings
repo.Index_referencing_IndexPatternColumnGuid <.. repo.IndexReferencedReferencing_HasFullColumnsInReferencing
repo.Index_SqlConstraint_PkUq <.. repo.RepoObject_SqlCreateTable
repo.Index_union <.. repo.Index_SqlConstraint_PkUq
repo.Index_union <.. repo.IndexReferencedReferencing
repo.Index_union <.. repo.Index_Settings_ForUpdate
repo.Index_union <.. repo.usp_Index_finish
repo.Index_union <.. repo.Index_gross
repo.Index_unique_IndexPatternColumnGuid <.. repo.Index_union
repo.Index_virtual_ForUpdate <.. repo.usp_index_inheritance
repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing <.. repo.usp_PERSIST_IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T
repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing <.. repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T
repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T <.. repo.IndexColumn_virtual_referenced_setpoint
repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T <.. repo.Index_referencing_IndexPatternColumnGuid
repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T <.. repo.IndexReferencedReferencing_HasFullColumnsInReferencing
repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T <.. repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_check
repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T <.. repo.usp_PERSIST_IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T
repo.IndexColumn_union <.. repo.usp_PERSIST_IndexColumn_union_T
repo.IndexColumn_union <.. repo.IndexColumn_union_T
repo.IndexColumn_union_T <.. repo.Index_ColumList
repo.IndexColumn_union_T <.. repo.Index_IndexPattern
repo.IndexColumn_union_T <.. repo.usp_PERSIST_IndexColumn_union_T
repo.IndexColumn_union_T <.. repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing
repo.IndexColumn_union_T <.. repo.RepoObjectColumn_gross2
repo.IndexColumn_virtual_referenced_setpoint <.. repo.check_IndexColumn_virtual_referenced_setpoint
repo.IndexColumn_virtual_referenced_setpoint <.. repo.usp_index_inheritance
repo.IndexReferencedReferencing <.. repo.IndexReferencedReferencing_HasFullColumnsInReferencing
repo.IndexReferencedReferencing_HasFullColumnsInReferencing <.. repo.usp_index_inheritance
repo.RepoObject_ColumnList <.. repo.RepoObject_SqlCreateTable
repo.RepoObject_ColumnList <.. repo.RepoObject_sat2
repo.RepoObject_ColumnList <.. repo.RepoObject_gross2
repo.RepoObject_gross <.. repo.Index_gross
repo.RepoObject_gross <.. uspgenerator.GeneratorUspStep_Persistence_src
repo.RepoObject_gross <.. uspgenerator.GeneratorUspStep_Persistence_IsInactive_setpoint
repo.RepoObject_gross <.. repo.RepoObject_SqlCreateTable
repo.RepoObject_gross <.. repo.Index_virtual_ForUpdate
repo.RepoObject_gross <.. docs.RepoObject_Plantuml
repo.RepoObject_gross <.. docs.RepoObject_OutputFilter
repo.RepoObject_gross <.. docs.RepoObject_Adoc
repo.RepoObject_gross <.. uspgenerator.usp_GeneratorUsp_insert_update_persistence
repo.RepoObject_gross <.. reference.usp_RepoObject_update_SysObjectQueryPlan
repo.RepoObject_gross <.. reference.usp_RepoObjectSource_FirstResultSet
repo.RepoObject_gross <.. reference.usp_RepoObjectSource_QueryPlan
repo.RepoObject_gross <.. repo.RepoObject_sat2
repo.RepoObject_gross <.. docs.Unit_1_union
repo.RepoObject_gross <.. repo.RepoObject_gross2
repo.RepoObject_gross <.. workflow.WorkflowStep_src
repo.RepoObject_gross <.. reference.Persistence
repo.RepoObject_gross <.. reference.RepoObject_ReferenceTree_30_0
repo.RepoObject_gross <.. reference.RepoObject_ReferenceTree_0_30
repo.RepoObject_gross <.. reference.RepoObject_ReferenceTree_referencing_0_30
repo.RepoObject_gross <.. reference.RepoObject_ReferenceTree_referenced_30_0
repo.RepoObject_gross <.. property.RepoObjectProperty_Collect_source_ROGross
repo.RepoObject_gross <.. reference.RepoObject_ReferenceTree_referencing
repo.RepoObject_gross <.. reference.RepoObject_ReferenceTree_referenced
repo.RepoObject_gross2 <.. uspgenerator.GeneratorUspStep_Persistence_src
repo.RepoObject_related_FK_union <.. docs.RepoObject_PlantUml_PumlEntityFkList
repo.RepoObject_related_FK_union <.. docs.RepoObject_PlantUml_FkRefList
repo.RepoObject_sat2 <.. repo.RepoObject_sat2_T
repo.RepoObject_sat2 <.. repo.usp_PERSIST_RepoObject_sat2_T
repo.RepoObject_sat2_T <.. repo.usp_PERSIST_RepoObject_sat2_T
repo.RepoObject_sat2_T <.. docs.RepoObject_Adoc
repo.RepoObject_sat2_T <.. property.RepoObjectProperty_Collect_source_ROGross
repo.RepoObject_SqlCreateTable <.. reference.ftv_RepoObject_ColumReferenceRepoObject
repo.RepoObjectColumn_gross2 <.. uspgenerator.usp_GeneratorUsp_insert_update_persistence
repo.RepoObjectColumn_gross2 <.. repo.RepoObject_ColumnList
repo.RepoObjectColumn_gross2 <.. docs.RepoObject_ColumnList
repo.SysColumn_RepoObjectColumn_via_guid <.. repo.usp_sync_guid_RepoObjectColumn
repo.SysColumn_RepoObjectColumn_via_name <.. repo.usp_sync_guid_RepoObjectColumn
repo.SysColumn_RepoObjectColumn_via_name <.. repo_sys.sql_expression_dependencies
repo.SysColumn_RepoObjectColumn_via_name <.. repo_sys.IndexColumn_unique
repo.usp_Index_finish <.. repo.usp_index_inheritance
repo.usp_Index_finish <.. repo.usp_Index_ForeignKey
repo.usp_Index_ForeignKey <.. repo.usp_main
repo.usp_index_inheritance <.. repo.usp_main
repo.usp_Index_Settings <.. repo.usp_Index_finish
repo.usp_Index_virtual_set <.. repo.usp_Index_ForeignKey
repo.usp_PERSIST_ForeignKey_Indexes_union_T <.. repo.usp_Index_ForeignKey
repo.usp_PERSIST_Index_ColumList_T <.. repo.usp_Index_finish
repo.usp_PERSIST_IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T <.. repo.usp_index_inheritance
repo.usp_PERSIST_IndexColumn_union_T <.. repo.usp_Index_finish
repo.usp_PERSIST_RepoObject_sat2_T <.. repo.usp_main
repo.usp_sync_guid <.. repo.usp_main
repo.usp_sync_guid <.. repo.usp_persistence_set
repo.usp_sync_guid_RepoObjectColumn <.. repo.usp_sync_guid
repo_sys.ForeignKeyColumn <.. repo.ForeignKey_IndexPattern
repo_sys.IndexColumn_unique <.. repo.IndexColumn_union
repo_sys.IndexColumn_unique <.. repo.Index_unique_IndexPatternColumnGuid
repo_sys.sql_expression_dependencies <.. reference.RepoObject_reference_SqlExpressionDependencies
repo_sys.sql_expression_dependencies <.. reference.RepoObjectColumn_reference_SqlExpressionDependencies
repo_sys.SysColumn <.. repo_sys.ForeignKeyColumn
repo_sys.SysColumn <.. repo.usp_sync_guid_RepoObjectColumn
repo_sys.SysColumn <.. repo.SysColumn_RepoObjectColumn_via_name
repo_sys.SysColumn <.. repo.SysColumn_RepoObjectColumn_via_guid
uspgenerator.GeneratorUspStep_Persistence_IsInactive_setpoint <.. uspgenerator.usp_GeneratorUsp_insert_update_persistence
uspgenerator.GeneratorUspStep_Persistence_src <.. uspgenerator.usp_GeneratorUsp_insert_update_persistence
uspgenerator.usp_GeneratorUsp_insert_update_persistence <.. repo.usp_main
workflow.Biml_Package <.. workflow.Biml_Project
workflow.Biml_PrecedenceConstraints <.. workflow.Biml_Task
workflow.Biml_Task <.. workflow.Biml_Package
workflow.ProcedureDependency <.. workflow.Workflow_ProcedureDependency
workflow.ProcedureDependency <.. workflow.Workflow_ProcedureDependency_all
workflow.ProcedureDependency <.. workflow.ProcedureDependency_input_PersistenceDependency
workflow.ProcedureDependency <.. workflow.ProcedureDependency_gross
workflow.ProcedureDependency_PersistenceDependency_src <.. workflow.usp_PERSIST_ProcedureDependency_PersistenceDependency_tgt
workflow.ProcedureDependency_PersistenceDependency_src <.. workflow.ProcedureDependency_PersistenceDependency_tgt
workflow.ProcedureDependency_PersistenceDependency_tgt <.. workflow.usp_PERSIST_ProcedureDependency_PersistenceDependency_tgt
workflow.ProcedureDependency_PersistenceDependency_tgt <.. workflow.ProcedureDependency
workflow.usp_PERSIST_ProcedureDependency_PersistenceDependency_tgt <.. workflow.usp_workflow
workflow.usp_PERSIST_Workflow_ProcedureDependency_T <.. workflow.usp_workflow
workflow.usp_PERSIST_WorkflowStep <.. workflow.usp_workflow
workflow.Workflow_ProcedureDependency <.. workflow.Workflow_ProcedureDependency_T
workflow.Workflow_ProcedureDependency <.. workflow.usp_PERSIST_Workflow_ProcedureDependency_T
workflow.Workflow_ProcedureDependency_all <.. workflow.Workflow_ProcedureDependency_wo_redundant
workflow.Workflow_ProcedureDependency_T <.. workflow.usp_workflow
workflow.Workflow_ProcedureDependency_T <.. workflow.Workflow_ProcedureDependency_T_bidirectional
workflow.Workflow_ProcedureDependency_T <.. workflow.Workflow_ProcedureDependency_T_active
workflow.Workflow_ProcedureDependency_T <.. workflow.usp_PERSIST_Workflow_ProcedureDependency_T
workflow.Workflow_ProcedureDependency_T_active <.. workflow.Workflow_ProcedureDependency_T_NotInSortorder
workflow.Workflow_ProcedureDependency_T_active <.. workflow.Workflow_ProcedureDependency_T_TaskName
workflow.Workflow_ProcedureDependency_T_active <.. workflow.Workflow_ProcedureDependency_T_redundant
workflow.Workflow_ProcedureDependency_T_bidirectional <.. workflow.usp_workflow
workflow.Workflow_ProcedureDependency_T_bidirectional <.. workflow.Workflow_ProcedureDependency_T_bidirectional_T
workflow.Workflow_ProcedureDependency_T_NotInSortorder <.. workflow.usp_workflow
workflow.Workflow_ProcedureDependency_T_NotInSortorder <.. workflow.Workflow_ProcedureDependency_T_NotInSortorder_check
workflow.Workflow_ProcedureDependency_T_NotInSortorder_check <.. workflow.usp_workflow
workflow.Workflow_ProcedureDependency_T_redundant <.. workflow.Workflow_ProcedureDependency_wo_redundant
workflow.Workflow_ProcedureDependency_T_redundant <.. workflow.usp_workflow
workflow.Workflow_ProcedureDependency_T_TaskName <.. workflow.Biml_PrecedenceConstraints
workflow.WorkflowStep <.. workflow.usp_PERSIST_WorkflowStep
workflow.WorkflowStep <.. workflow.WorkflowStep_active
workflow.WorkflowStep <.. workflow.WorkflowStep_ForUpdate
workflow.WorkflowStep_active <.. workflow.Workflow_ProcedureDependency_T_active
workflow.WorkflowStep_active <.. workflow.Workflow_ProcedureDependency
workflow.WorkflowStep_active <.. workflow.Biml_Task
workflow.WorkflowStep_active <.. workflow.Workflow_ProcedureDependency_all
workflow.WorkflowStep_active <.. workflow.usp_workflow
workflow.WorkflowStep_src <.. workflow.WorkflowStep
workflow.WorkflowStep_src <.. workflow.usp_PERSIST_WorkflowStep

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_0_30_objectref[]

=== PlantUML 1 1 ColumnRef

// tag::puml_entity_1_1_colref[]
[plantuml, entity_1_1_colref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:config.ftv_dwh_database.adoc[]" as config.ftv_dwh_database << IF >> {
  dwh_database_id : (smallint)
  dwh_database_name : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:repo.syscolumn_repoobjectcolumn_via_guid.adoc[]" as repo.SysColumn_RepoObjectColumn_via_guid << V >> {
  default_definition : (nvarchar(max))
  default_is_system_named : (bit)
  default_name : (sysname)
  definition : (nvarchar(max))
  generated_always_type : (tinyint)
  graph_type : (int)
  has_different_sys_names : (bit)
  increment_value : (sql_variant)
  - is_computed : (bit)
  - is_identity : (bit)
  is_nullable : (bit)
  is_persisted : (bit)
  is_query_plan_expression : (bit)
  is_repo_managed : (bit)
  is_RepoObjectColumn_name_uniqueidentifier : (int)
  is_SysObjectColumn_missing : (bit)
  is_SysObjectColumn_name_uniqueidentifier : (int)
  persistence_source_RepoObjectColumn_guid : (uniqueidentifier)
  Referencing_Count : (int)
  Repo_default_definition : (nvarchar(max))
  Repo_default_is_system_named : (bit)
  Repo_default_name : (nvarchar(128))
  Repo_definition : (nvarchar(max))
  Repo_generated_always_type : (tinyint)
  Repo_graph_type : (int)
  Repo_increment_value : (sql_variant)
  Repo_is_computed : (bit)
  Repo_is_identity : (bit)
  Repo_is_nullable : (bit)
  Repo_is_persisted : (bit)
  Repo_seed_value : (sql_variant)
  Repo_user_type_fullname : (nvarchar(128))
  Repo_user_type_name : (nvarchar(128))
  Repo_uses_database_collation : (bit)
  - RepoObject_fullname : (nvarchar(261))
  RepoObject_guid : (uniqueidentifier)
  RepoObjectColumn_guid : (uniqueidentifier)
  RepoObjectColumn_name : (nvarchar(128))
  RowNumberOverName : (bigint)
  seed_value : (sql_variant)
  - SysObject_column_id : (int)
  SysObject_column_name : (sysname)
  - SysObject_fullname : (nvarchar(261))
  - SysObject_id : (int)
  SysObject_name : (nvarchar(128))
  SysObject_RepoObject_guid : (uniqueidentifier)
  SysObject_RepoObjectColumn_guid : (uniqueidentifier)
  SysObject_schema_name : (nvarchar(128))
  SysObject_type : (char(2))
  SysObjectColumn_column_id : (int)
  SysObjectColumn_name : (nvarchar(128))
  user_type_fullname : (nvarchar(182))
  user_type_name : (sysname)
  uses_database_collation : (bit)
  --
}

entity "puml-link:dhw:sqldb:repo.syscolumn_repoobjectcolumn_via_name.adoc[]" as repo.SysColumn_RepoObjectColumn_via_name << V >> {
  default_definition : (nvarchar(max))
  default_is_system_named : (bit)
  default_name : (sysname)
  definition : (nvarchar(max))
  generated_always_type : (tinyint)
  graph_type : (int)
  has_different_sys_names : (bit)
  increment_value : (sql_variant)
  - is_computed : (bit)
  - is_identity : (bit)
  is_nullable : (bit)
  is_persisted : (bit)
  is_query_plan_expression : (bit)
  is_repo_managed : (bit)
  is_RepoObjectColumn_name_uniqueidentifier : (int)
  is_SysObjectColumn_missing : (bit)
  is_SysObjectColumn_name_uniqueidentifier : (int)
  persistence_source_RepoObjectColumn_guid : (uniqueidentifier)
  Referencing_Count : (int)
  Repo_default_definition : (nvarchar(max))
  Repo_default_is_system_named : (bit)
  Repo_default_name : (nvarchar(128))
  Repo_definition : (nvarchar(max))
  Repo_generated_always_type : (tinyint)
  Repo_graph_type : (int)
  Repo_increment_value : (sql_variant)
  Repo_is_computed : (bit)
  Repo_is_identity : (bit)
  Repo_is_nullable : (bit)
  Repo_is_persisted : (bit)
  Repo_seed_value : (sql_variant)
  Repo_user_type_fullname : (nvarchar(128))
  Repo_user_type_name : (nvarchar(128))
  Repo_uses_database_collation : (bit)
  RepoObject_fullname : (nvarchar(261))
  RepoObject_guid : (uniqueidentifier)
  RepoObjectColumn_guid : (uniqueidentifier)
  RepoObjectColumn_name : (nvarchar(128))
  RowNumberOverName : (bigint)
  seed_value : (sql_variant)
  - SysObject_column_id : (int)
  SysObject_column_name : (sysname)
  SysObject_fullname : (nvarchar(261))
  - SysObject_id : (int)
  SysObject_name : (nvarchar(128))
  SysObject_RepoObject_guid : (uniqueidentifier)
  SysObject_RepoObjectColumn_guid : (uniqueidentifier)
  SysObject_schema_name : (nvarchar(128))
  SysObject_type : (char(2))
  SysObjectColumn_column_id : (int)
  SysObjectColumn_name : (nvarchar(128))
  user_type_fullname : (nvarchar(182))
  user_type_name : (sysname)
  uses_database_collation : (bit)
  --
}

entity "puml-link:dhw:sqldb:repo.usp_sync_guid_repoobjectcolumn.adoc[]" as repo.usp_sync_guid_RepoObjectColumn << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo_sys.extendedproperties.adoc[]" as repo_sys.ExtendedProperties << V >> {
  - class : (tinyint)
  class_desc : (nvarchar(60))
  entity_column_name : (nvarchar(128))
  entity_index_name : (nvarchar(128))
  entity_parameter_name : (nvarchar(128))
  level2type : (varchar(9))
  - major_id : (int)
  - minor_id : (int)
  minor_name : (nvarchar(128))
  parent_name : (sysname)
  parent_object_id : (int)
  parent_type : (char(2))
  property_basetype : (sql_variant)
  - property_name : (sysname)
  property_nvarchar : (nvarchar(4000))
  property_value : (sql_variant)
  SysObject_name : (nvarchar(128))
  SysObject_schema_name : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:repo_sys.foreignkeycolumn.adoc[]" as repo_sys.ForeignKeyColumn << V >> {
  - constraint_column_id : (int)
  - constraint_object_id : (int)
  ForeignKey_fullname : (nvarchar(261))
  ForeignKey_guid : (uniqueidentifier)
  ForeignKey_name : (sysname)
  - parent_column_id : (int)
  - parent_object_id : (int)
  - referenced_column_id : (int)
  referenced_column_name : (sysname)
  referenced_name : (nvarchar(128))
  - referenced_object_id : (int)
  referenced_RepoObject_guid : (uniqueidentifier)
  referenced_RepoObjectColumn_guid : (uniqueidentifier)
  referenced_schema_name : (nvarchar(128))
  referencing_column_name : (sysname)
  referencing_name : (nvarchar(128))
  referencing_RepoObject_fullname : (nvarchar(261))
  referencing_RepoObject_guid : (uniqueidentifier)
  referencing_RepoObjectColumn_guid : (uniqueidentifier)
  referencing_schema_name : (nvarchar(128))
  referencing_SysObject_fullname : (nvarchar(261))
  --
}

entity "puml-link:dhw:sqldb:repo_sys.syscolumn.adoc[]" as repo_sys.SysColumn << V >> {
  collation_name : (sysname)
  column_encryption_key_database_name : (sysname)
  column_encryption_key_id : (int)
  default_definition : (nvarchar(max))
  default_is_system_named : (bit)
  default_name : (sysname)
  - default_object_id : (int)
  default_parent_column_id : (int)
  definition : (nvarchar(max))
  encryption_algorithm_name : (sysname)
  encryption_type : (int)
  encryption_type_desc : (nvarchar(64))
  generated_always_type : (tinyint)
  generated_always_type_desc : (nvarchar(60))
  graph_type : (int)
  graph_type_desc : (nvarchar(60))
  increment_value : (sql_variant)
  - is_ansi_padded : (bit)
  is_column_set : (bit)
  - is_computed : (bit)
  is_dts_replicated : (bit)
  - is_filestream : (bit)
  is_hidden : (bit)
  - is_identity : (bit)
  - is_masked : (bit)
  is_merge_published : (bit)
  is_non_sql_subscribed : (bit)
  is_nullable : (bit)
  is_persisted : (bit)
  is_replicated : (bit)
  - is_rowguidcol : (bit)
  is_sparse : (bit)
  - is_xml_document : (bit)
  last_value : (sql_variant)
  - max_length : (smallint)
  - precision : (tinyint)
  - rule_object_id : (int)
  - scale : (tinyint)
  seed_value : (sql_variant)
  - SysObject_column_id : (int)
  SysObject_column_name : (sysname)
  SysObject_fullname : (nvarchar(517))
  SysObject_fullname2 : (nvarchar(257))
  - SysObject_id : (int)
  SysObject_name : (nvarchar(128))
  SysObject_RepoObject_guid : (uniqueidentifier)
  SysObject_RepoObjectColumn_guid : (uniqueidentifier)
  SysObject_schema_name : (nvarchar(128))
  SysObject_type : (char(2))
  SysObject_type_desc : (nvarchar(60))
  - system_type_id : (tinyint)
  user_type_fullname : (nvarchar(182))
  - user_type_id : (int)
  user_type_name : (sysname)
  uses_database_collation : (bit)
  - xml_collection_id : (int)
  --
}

entity "puml-link:dhw:sqldb:repo_sys.sysobject.adoc[]" as repo_sys.SysObject << V >> {
  - create_date : (datetime)
  history_table_id : (int)
  - is_ms_shipped : (bit)
  - is_published : (bit)
  - is_schema_published : (bit)
  max_column_id_used : (int)
  - modify_date : (datetime)
  - parent_object_id : (int)
  principal_id : (int)
  - schema_id : (int)
  sql_modules_definition : (nvarchar(max))
  - SysObject_fullname : (nvarchar(517))
  - SysObject_fullname2 : (nvarchar(257))
  - SysObject_id : (int)
  - SysObject_name : (sysname)
  SysObject_RepoObject_guid : (uniqueidentifier)
  SysObject_schema_name : (sysname)
  temporal_type : (tinyint)
  temporal_type_desc : (nvarchar(60))
  type : (char(2))
  type_desc : (nvarchar(60))
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.columns.adoc[]" as sys_dwh.columns << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.computed_columns.adoc[]" as sys_dwh.computed_columns << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.default_constraints.adoc[]" as sys_dwh.default_constraints << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.identity_columns.adoc[]" as sys_dwh.identity_columns << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.types.adoc[]" as sys_dwh.types << SN >> {
  --
}

config.ftv_dwh_database <.. repo_sys.SysColumn
repo_sys.ExtendedProperties <.. repo_sys.SysColumn
repo_sys.SysColumn <.. repo.SysColumn_RepoObjectColumn_via_guid
repo_sys.SysColumn <.. repo.SysColumn_RepoObjectColumn_via_name
repo_sys.SysColumn <.. repo.usp_sync_guid_RepoObjectColumn
repo_sys.SysColumn <.. repo_sys.ForeignKeyColumn
repo_sys.SysObject <.. repo_sys.SysColumn
sys_dwh.columns <.. repo_sys.SysColumn
sys_dwh.computed_columns <.. repo_sys.SysColumn
sys_dwh.default_constraints <.. repo_sys.SysColumn
sys_dwh.identity_columns <.. repo_sys.SysColumn
sys_dwh.types <.. repo_sys.SysColumn
"repo_sys.SysColumn::default_definition" <-- "repo.SysColumn_RepoObjectColumn_via_guid::default_definition"
"repo_sys.SysColumn::default_definition" <-- "repo.SysColumn_RepoObjectColumn_via_name::default_definition"
"repo_sys.SysColumn::default_is_system_named" <-- "repo.SysColumn_RepoObjectColumn_via_name::default_is_system_named"
"repo_sys.SysColumn::default_is_system_named" <-- "repo.SysColumn_RepoObjectColumn_via_guid::default_is_system_named"
"repo_sys.SysColumn::default_name" <-- "repo.SysColumn_RepoObjectColumn_via_guid::default_name"
"repo_sys.SysColumn::default_name" <-- "repo.SysColumn_RepoObjectColumn_via_name::default_name"
"repo_sys.SysColumn::definition" <-- "repo.SysColumn_RepoObjectColumn_via_name::definition"
"repo_sys.SysColumn::definition" <-- "repo.SysColumn_RepoObjectColumn_via_guid::definition"
"repo_sys.SysColumn::generated_always_type" <-- "repo.SysColumn_RepoObjectColumn_via_guid::generated_always_type"
"repo_sys.SysColumn::generated_always_type" <-- "repo.SysColumn_RepoObjectColumn_via_name::generated_always_type"
"repo_sys.SysColumn::graph_type" <-- "repo.SysColumn_RepoObjectColumn_via_name::graph_type"
"repo_sys.SysColumn::graph_type" <-- "repo.SysColumn_RepoObjectColumn_via_guid::graph_type"
"repo_sys.SysColumn::increment_value" <-- "repo.SysColumn_RepoObjectColumn_via_name::increment_value"
"repo_sys.SysColumn::increment_value" <-- "repo.SysColumn_RepoObjectColumn_via_guid::increment_value"
"repo_sys.SysColumn::is_computed" <-- "repo.SysColumn_RepoObjectColumn_via_name::is_computed"
"repo_sys.SysColumn::is_computed" <-- "repo.SysColumn_RepoObjectColumn_via_guid::is_computed"
"repo_sys.SysColumn::is_identity" <-- "repo.SysColumn_RepoObjectColumn_via_guid::is_identity"
"repo_sys.SysColumn::is_identity" <-- "repo.SysColumn_RepoObjectColumn_via_name::is_identity"
"repo_sys.SysColumn::is_nullable" <-- "repo.SysColumn_RepoObjectColumn_via_name::is_nullable"
"repo_sys.SysColumn::is_nullable" <-- "repo.SysColumn_RepoObjectColumn_via_guid::is_nullable"
"repo_sys.SysColumn::is_persisted" <-- "repo.SysColumn_RepoObjectColumn_via_guid::is_persisted"
"repo_sys.SysColumn::is_persisted" <-- "repo.SysColumn_RepoObjectColumn_via_name::is_persisted"
"repo_sys.SysColumn::seed_value" <-- "repo.SysColumn_RepoObjectColumn_via_name::seed_value"
"repo_sys.SysColumn::seed_value" <-- "repo.SysColumn_RepoObjectColumn_via_guid::seed_value"
"repo_sys.SysColumn::SysObject_column_id" <-- "repo.SysColumn_RepoObjectColumn_via_name::SysObject_column_id"
"repo_sys.SysColumn::SysObject_column_id" <-- "repo.SysColumn_RepoObjectColumn_via_guid::SysObject_column_id"
"repo_sys.SysColumn::SysObject_column_name" <-- "repo.SysColumn_RepoObjectColumn_via_guid::SysObject_column_name"
"repo_sys.SysColumn::SysObject_column_name" <-- "repo.SysColumn_RepoObjectColumn_via_name::SysObject_column_name"
"repo_sys.SysColumn::SysObject_column_name" <-- "repo_sys.ForeignKeyColumn::referencing_column_name"
"repo_sys.SysColumn::SysObject_column_name" <-- "repo_sys.ForeignKeyColumn::referenced_column_name"
"repo_sys.SysColumn::SysObject_id" <-- "repo.SysColumn_RepoObjectColumn_via_name::SysObject_id"
"repo_sys.SysColumn::SysObject_id" <-- "repo.SysColumn_RepoObjectColumn_via_guid::SysObject_id"
"repo_sys.SysColumn::SysObject_name" <-- "repo.SysColumn_RepoObjectColumn_via_guid::SysObject_name"
"repo_sys.SysColumn::SysObject_name" <-- "repo.SysColumn_RepoObjectColumn_via_name::SysObject_name"
"repo_sys.SysColumn::SysObject_name" <-- "repo_sys.ForeignKeyColumn::referenced_name"
"repo_sys.SysColumn::SysObject_name" <-- "repo_sys.ForeignKeyColumn::referencing_name"
"repo_sys.SysColumn::SysObject_RepoObject_guid" <-- "repo_sys.ForeignKeyColumn::referencing_RepoObject_guid"
"repo_sys.SysColumn::SysObject_RepoObject_guid" <-- "repo_sys.ForeignKeyColumn::referenced_RepoObject_guid"
"repo_sys.SysColumn::SysObject_RepoObject_guid" <-- "repo.SysColumn_RepoObjectColumn_via_name::SysObject_RepoObject_guid"
"repo_sys.SysColumn::SysObject_RepoObject_guid" <-- "repo.SysColumn_RepoObjectColumn_via_guid::SysObject_RepoObject_guid"
"repo_sys.SysColumn::SysObject_RepoObjectColumn_guid" <-- "repo.SysColumn_RepoObjectColumn_via_guid::SysObject_RepoObjectColumn_guid"
"repo_sys.SysColumn::SysObject_RepoObjectColumn_guid" <-- "repo.SysColumn_RepoObjectColumn_via_name::SysObject_RepoObjectColumn_guid"
"repo_sys.SysColumn::SysObject_RepoObjectColumn_guid" <-- "repo_sys.ForeignKeyColumn::referenced_RepoObjectColumn_guid"
"repo_sys.SysColumn::SysObject_RepoObjectColumn_guid" <-- "repo_sys.ForeignKeyColumn::referencing_RepoObjectColumn_guid"
"repo_sys.SysColumn::SysObject_schema_name" <-- "repo_sys.ForeignKeyColumn::referencing_schema_name"
"repo_sys.SysColumn::SysObject_schema_name" <-- "repo_sys.ForeignKeyColumn::referenced_schema_name"
"repo_sys.SysColumn::SysObject_schema_name" <-- "repo.SysColumn_RepoObjectColumn_via_name::SysObject_schema_name"
"repo_sys.SysColumn::SysObject_schema_name" <-- "repo.SysColumn_RepoObjectColumn_via_guid::SysObject_schema_name"
"repo_sys.SysColumn::SysObject_type" <-- "repo.SysColumn_RepoObjectColumn_via_guid::SysObject_type"
"repo_sys.SysColumn::SysObject_type" <-- "repo.SysColumn_RepoObjectColumn_via_name::SysObject_type"
"repo_sys.SysColumn::user_type_fullname" <-- "repo.SysColumn_RepoObjectColumn_via_name::user_type_fullname"
"repo_sys.SysColumn::user_type_fullname" <-- "repo.SysColumn_RepoObjectColumn_via_guid::user_type_fullname"
"repo_sys.SysColumn::user_type_name" <-- "repo.SysColumn_RepoObjectColumn_via_guid::user_type_name"
"repo_sys.SysColumn::user_type_name" <-- "repo.SysColumn_RepoObjectColumn_via_name::user_type_name"
"repo_sys.SysColumn::uses_database_collation" <-- "repo.SysColumn_RepoObjectColumn_via_name::uses_database_collation"
"repo_sys.SysColumn::uses_database_collation" <-- "repo.SysColumn_RepoObjectColumn_via_guid::uses_database_collation"
"repo_sys.SysObject::type" <-- "repo_sys.SysColumn::SysObject_type"
"repo_sys.SysObject::type_desc" <-- "repo_sys.SysColumn::SysObject_type_desc"

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_colref[]


== sql_modules_definition

// tag::sql_modules_definition[]
[%collapsible]
=======
[source,sql,numbered,indent=0]
----


CREATE View repo_sys.SysColumn
As
--
Select
    SysObject_id                    = sc.object_id
  , SysObject_schema_name           = Object_Schema_Name ( sc.object_id, db.dwh_database_id )
  , SysObject_name                  = Object_Name ( sc.object_id, db.dwh_database_id )
  , SysObject_fullname              =
  --
  QuoteName ( Object_Schema_Name ( sc.object_id, db.dwh_database_id )) + '.'
  + QuoteName ( Object_Name ( sc.object_id, db.dwh_database_id ))
  , SysObject_fullname2             =
  --
  Object_Schema_Name ( sc.object_id, db.dwh_database_id ) + '.' + Object_Name ( sc.object_id, db.dwh_database_id )
  , SysObject_column_id             = sc.column_id
  , SysObject_column_name           = sc.name Collate Database_Default
  , SysObject_type                  = so.type
  , SysObject_type_desc             = so.type_desc
  , SysObject_RepoObject_guid       = Try_Cast(ep.property_value As UniqueIdentifier)
  , SysObject_RepoObjectColumn_guid = Try_Cast(ep2.property_value As UniqueIdentifier)
  , sc.system_type_id
  , sc.user_type_id
  -- code for [user_type_name]: https://stackoverflow.com/questions/9179990/where-do-i-find-sql-server-metadata-for-column-datatypes
  , user_type_name                  = tp.name Collate Database_Default
  , user_type_fullname              =
  --
  Case
      When tp.name In
      ( 'varchar', 'char', 'varbinary', 'binary' )
          Then
          tp.name + '(' + Iif(sc.max_length = -1, 'max', Cast(sc.max_length As Varchar(25))) + ')'
      When tp.name In
      ( 'nvarchar', 'nchar' )
          Then
          tp.name + '(' + Iif(sc.max_length = -1, 'max', Cast(sc.max_length / 2 As Varchar(25))) + ')'
      When tp.name In
      ( 'decimal', 'numeric' )
          Then
          tp.name + '(' + Cast(sc.precision As Varchar(25)) + ', ' + Cast(sc.scale As Varchar(25)) + ')'
      When tp.name In
      ( 'datetime2' )
          Then
          tp.name + '(' + Cast(sc.scale As Varchar(25)) + ')'
      Else
          tp.name
  End Collate Database_Default
  , sc.max_length
  , sc.precision
  , sc.scale
  , sc.collation_name
  , sc.is_nullable
  , sc.is_ansi_padded
  , sc.is_rowguidcol
  , sc.is_identity
  , sc.is_computed
  , sc.is_filestream
  , sc.is_replicated
  , sc.is_non_sql_subscribed
  , sc.is_merge_published
  , sc.is_dts_replicated
  , sc.is_xml_document
  , sc.xml_collection_id
  , sc.default_object_id
  , sc.rule_object_id
  , sc.is_sparse
  , sc.is_column_set
  , sc.generated_always_type
  , sc.generated_always_type_desc
  , sc.encryption_type
  , sc.encryption_type_desc
  , sc.encryption_algorithm_name
  , sc.column_encryption_key_id
  , sc.column_encryption_key_database_name
  , sc.is_hidden
  , sc.is_masked
  , sc.graph_type
  , sc.graph_type_desc
  , definition                      = scc.definition Collate Database_Default
  , scc.is_persisted
  , scc.uses_database_collation
  , default_definition              = sdc.definition Collate Database_Default
  , default_is_system_named         = sdc.is_system_named
  , default_name                    = sdc.name Collate Database_Default
  , default_parent_column_id        = sdc.parent_column_id
  , sic.seed_value
  , sic.increment_value
  , sic.last_value
--, [sic].[is_not_for_replication]
--, CAST(CASE
--           WHEN [sc].[name] = 'SysStartTime'
--                AND [tp].[name] = 'datetime2'
--           THEN 1
--           WHEN [sc].[name] = 'SysEndTime'
--                AND [tp].[name] = 'datetime2'
--           THEN 2
--       END AS TINYINT) AS                                        [temporal_column_type]
From
    sys_dwh.columns                        As sc
    Left Outer Join
        repo_sys.ExtendedProperties        As ep
            On
            ep.major_id = sc.object_id
            And ep.minor_id = 0
            And ep.property_name = N'RepoObject_guid'

    Left Outer Join
        repo_sys.ExtendedProperties        As ep2
            On
            ep2.major_id = sc.object_id
            And ep2.minor_id = sc.column_id
            And ep2.property_name = N'RepoObjectColumn_guid'

    Left Outer Join
        repo_sys.SysObject                 As so
            On
            so.SysObject_id = sc.object_id

    Left Outer Join
        sys_dwh.types                      As tp
            On
            sc.user_type_id = tp.user_type_id

    Left Outer Join
        sys_dwh.computed_columns           As scc
            On
            scc.object_id = sc.object_id
            And scc.column_id = sc.column_id

    Left Outer Join
        sys_dwh.default_constraints        As sdc
            On
            sc.default_object_id = sdc.object_id

    Left Outer Join
        sys_dwh.identity_columns           As sic
            On
            sic.object_id = sc.object_id
            And sic.column_id = sc.column_id
    --
    Cross Apply config.ftv_dwh_database () As db
Where
    Object_Schema_Name ( sc.object_id, db.dwh_database_id ) <> 'sys'

----
=======
// end::sql_modules_definition[]


