// tag::HeaderFullDisplayName[]
= repo.RepoObjectColumn_SSAS_tgt - V
// end::HeaderFullDisplayName[]

== existing_properties

// tag::existing_properties[]

:ExistsProperty--antorareferencedlist:
:ExistsProperty--antorareferencinglist:
:ExistsProperty--has_history:
:ExistsProperty--has_history_columns:
:ExistsProperty--is_persistence:
:ExistsProperty--is_persistence_check_duplicate_per_pk:
:ExistsProperty--is_persistence_check_for_empty_source:
:ExistsProperty--is_persistence_delete_changed:
:ExistsProperty--is_persistence_delete_missing:
:ExistsProperty--is_persistence_insert:
:ExistsProperty--is_persistence_truncate:
:ExistsProperty--is_persistence_update_changed:
:ExistsProperty--is_repo_managed:
:ExistsProperty--is_ssas:
:ExistsProperty--persistence_source_repoobject_fullname:
:ExistsProperty--persistence_source_repoobject_fullname2:
:ExistsProperty--persistence_source_repoobject_guid:
:ExistsProperty--persistence_source_repoobject_xref:
:ExistsProperty--pk_index_guid:
:ExistsProperty--pk_indexpatterncolumndatatype:
:ExistsProperty--pk_indexpatterncolumnname:
:ExistsProperty--referencedobjectlist:
:ExistsProperty--usp_persistence_repoobject_guid:
:ExistsProperty--sql_modules_definition:
:ExistsProperty--FK:
:ExistsProperty--AntoraIndexList:
:ExistsProperty--Columns:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
144559F6-0807-EC11-8515-A81E8446D5B0
// end::RepoObject_guid[]

== RepoObject_FullDisplayName2

// tag::RepoObject_FullDisplayName2[]
repo.RepoObjectColumn_SSAS_tgt
// end::RepoObject_FullDisplayName2[]

== SysObject_type

// tag::SysObject_type[]
V 
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
view
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
1130487106
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2022-01-05 18:36:54
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]
[discrete]
== _


[#column-repoobjectcolumnunderlineguid]
=== RepoObjectColumn_guid

[cols="d,8a,m,m,m"]
|===
|1
|*RepoObjectColumn_guid*
|uniqueidentifier
|NOT NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobjectcolumn.adoc#column-repoobjectcolumnunderlineguid[+repo.RepoObjectColumn.RepoObjectColumn_guid+]
* xref:repo.repoobjectcolumn_ssas_src.adoc#column-repoobjectcolumnunderlineguid[+repo.RepoObjectColumn_SSAS_src.RepoObjectColumn_guid+]
--


[#column-inheritanceunderlinestringaggseparatorsql]
=== Inheritance_StringAggSeparatorSql

[cols="d,8a,m,m,m"]
|===
|
|Inheritance_StringAggSeparatorSql
|nvarchar(4000)
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobjectcolumn.adoc#column-inheritanceunderlinestringaggseparatorsql[+repo.RepoObjectColumn.Inheritance_StringAggSeparatorSql+]
--


[#column-inheritancedefinition]
=== InheritanceDefinition

[cols="d,8a,m,m,m"]
|===
|
|InheritanceDefinition
|nvarchar(4000)
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobjectcolumn.adoc#column-inheritancedefinition[+repo.RepoObjectColumn.InheritanceDefinition+]
--


[#column-inheritancetype]
=== InheritanceType

[cols="d,8a,m,m,m"]
|===
|
|InheritanceType
|tinyint
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobjectcolumn.adoc#column-inheritancetype[+repo.RepoObjectColumn.InheritanceType+]
--


[#column-isunderlinepersistenceunderlineignore]
=== is_persistence_Ignore

[cols="d,8a,m,m,m"]
|===
|
|is_persistence_Ignore
|bit
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobjectcolumn.adoc#column-isunderlinepersistenceunderlineignore[+repo.RepoObjectColumn.is_persistence_Ignore+]
--


[#column-isunderlinepersistenceunderlinenocomparebutupdate]
=== is_persistence_NoCompareButUpdate

[cols="d,8a,m,m,m"]
|===
|
|is_persistence_NoCompareButUpdate
|bit
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobjectcolumn.adoc#column-isunderlinepersistenceunderlinenocomparebutupdate[+repo.RepoObjectColumn.is_persistence_NoCompareButUpdate+]
--


[#column-isunderlinepersistenceunderlinenocomparenoupdate]
=== is_persistence_NoCompareNoUpdate

[cols="d,8a,m,m,m"]
|===
|
|is_persistence_NoCompareNoUpdate
|bit
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobjectcolumn.adoc#column-isunderlinepersistenceunderlinenocomparenoupdate[+repo.RepoObjectColumn.is_persistence_NoCompareNoUpdate+]
--


[#column-isunderlinequeryunderlineplanunderlineexpression]
=== is_query_plan_expression

[cols="d,8a,m,m,m"]
|===
|
|is_query_plan_expression
|bit
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobjectcolumn.adoc#column-isunderlinequeryunderlineplanunderlineexpression[+repo.RepoObjectColumn.is_query_plan_expression+]
--


[#column-isunderlinerequiredunderlinecolumnmerge]
=== is_required_ColumnMerge

[cols="d,8a,m,m,m"]
|===
|
|is_required_ColumnMerge
|bit
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobjectcolumn.adoc#column-isunderlinerequiredunderlinecolumnmerge[+repo.RepoObjectColumn.is_required_ColumnMerge+]
--


[#column-isunderlinesysobjectcolumnunderlinemissing]
=== is_SysObjectColumn_missing

[cols="d,8a,m,m,m"]
|===
|
|is_SysObjectColumn_missing
|bit
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobjectcolumn.adoc#column-isunderlinesysobjectcolumnunderlinemissing[+repo.RepoObjectColumn.is_SysObjectColumn_missing+]
* xref:repo.repoobjectcolumn_ssas_src.adoc#column-isunderlinesysobjectcolumnunderlinemissing[+repo.RepoObjectColumn_SSAS_src.is_SysObjectColumn_missing+]
--


[#column-persistenceunderlinesourceunderlinerepoobjectcolumnunderlineguid]
=== persistence_source_RepoObjectColumn_guid

[cols="d,8a,m,m,m"]
|===
|
|persistence_source_RepoObjectColumn_guid
|uniqueidentifier
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobjectcolumn.adoc#column-persistenceunderlinesourceunderlinerepoobjectcolumnunderlineguid[+repo.RepoObjectColumn.persistence_source_RepoObjectColumn_guid+]
--


[#column-referencingunderlinecount]
=== Referencing_Count

[cols="d,8a,m,m,m"]
|===
|
|Referencing_Count
|int
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobjectcolumn.adoc#column-referencingunderlinecount[+repo.RepoObjectColumn.Referencing_Count+]
--


[#column-repounderlinedefaultunderlinedefinition]
=== Repo_default_definition

[cols="d,8a,m,m,m"]
|===
|
|Repo_default_definition
|nvarchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobjectcolumn.adoc#column-repounderlinedefaultunderlinedefinition[+repo.RepoObjectColumn.Repo_default_definition+]
--


[#column-repounderlinedefaultunderlineisunderlinesystemunderlinenamed]
=== Repo_default_is_system_named

[cols="d,8a,m,m,m"]
|===
|
|Repo_default_is_system_named
|bit
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobjectcolumn.adoc#column-repounderlinedefaultunderlineisunderlinesystemunderlinenamed[+repo.RepoObjectColumn.Repo_default_is_system_named+]
--


[#column-repounderlinedefaultunderlinename]
=== Repo_default_name

[cols="d,8a,m,m,m"]
|===
|
|Repo_default_name
|nvarchar(128)
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobjectcolumn.adoc#column-repounderlinedefaultunderlinename[+repo.RepoObjectColumn.Repo_default_name+]
--


[#column-repounderlinedefinition]
=== Repo_definition

[cols="d,8a,m,m,m"]
|===
|
|Repo_definition
|nvarchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobjectcolumn.adoc#column-repounderlinedefinition[+repo.RepoObjectColumn.Repo_definition+]
--


[#column-repounderlinegeneratedunderlinealwaysunderlinetype]
=== Repo_generated_always_type

[cols="d,8a,m,m,m"]
|===
|
|Repo_generated_always_type
|tinyint
|NOT NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobjectcolumn.adoc#column-repounderlinegeneratedunderlinealwaysunderlinetype[+repo.RepoObjectColumn.Repo_generated_always_type+]
--


[#column-repounderlinegraphunderlinetype]
=== Repo_graph_type

[cols="d,8a,m,m,m"]
|===
|
|Repo_graph_type
|int
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobjectcolumn.adoc#column-repounderlinegraphunderlinetype[+repo.RepoObjectColumn.Repo_graph_type+]
--


[#column-repounderlineincrementunderlinevalue]
=== Repo_increment_value

[cols="d,8a,m,m,m"]
|===
|
|Repo_increment_value
|sql_variant
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobjectcolumn.adoc#column-repounderlineincrementunderlinevalue[+repo.RepoObjectColumn.Repo_increment_value+]
--


[#column-repounderlineisunderlinecomputed]
=== Repo_is_computed

[cols="d,8a,m,m,m"]
|===
|
|Repo_is_computed
|bit
|NOT NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobjectcolumn.adoc#column-repounderlineisunderlinecomputed[+repo.RepoObjectColumn.Repo_is_computed+]
--


[#column-repounderlineisunderlineidentity]
=== Repo_is_identity

[cols="d,8a,m,m,m"]
|===
|
|Repo_is_identity
|bit
|NOT NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobjectcolumn.adoc#column-repounderlineisunderlineidentity[+repo.RepoObjectColumn.Repo_is_identity+]
--


[#column-repounderlineisunderlinenullable]
=== Repo_is_nullable

[cols="d,8a,m,m,m"]
|===
|
|Repo_is_nullable
|bit
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobjectcolumn.adoc#column-repounderlineisunderlinenullable[+repo.RepoObjectColumn.Repo_is_nullable+]
* xref:repo.repoobjectcolumn_ssas_src.adoc#column-repounderlineisunderlinenullable[+repo.RepoObjectColumn_SSAS_src.Repo_is_nullable+]
--


[#column-repounderlineisunderlinepersisted]
=== Repo_is_persisted

[cols="d,8a,m,m,m"]
|===
|
|Repo_is_persisted
|bit
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobjectcolumn.adoc#column-repounderlineisunderlinepersisted[+repo.RepoObjectColumn.Repo_is_persisted+]
--


[#column-repounderlineseedunderlinevalue]
=== Repo_seed_value

[cols="d,8a,m,m,m"]
|===
|
|Repo_seed_value
|sql_variant
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobjectcolumn.adoc#column-repounderlineseedunderlinevalue[+repo.RepoObjectColumn.Repo_seed_value+]
--


[#column-repounderlineuserunderlinetypeunderlinefullname]
=== Repo_user_type_fullname

[cols="d,8a,m,m,m"]
|===
|
|Repo_user_type_fullname
|nvarchar(128)
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobjectcolumn.adoc#column-repounderlineuserunderlinetypeunderlinefullname[+repo.RepoObjectColumn.Repo_user_type_fullname+]
* xref:repo.repoobjectcolumn_ssas_src.adoc#column-repounderlineuserunderlinetypeunderlinefullname[+repo.RepoObjectColumn_SSAS_src.Repo_user_type_fullname+]
--


[#column-repounderlineuserunderlinetypeunderlinename]
=== Repo_user_type_name

[cols="d,8a,m,m,m"]
|===
|
|Repo_user_type_name
|nvarchar(128)
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobjectcolumn.adoc#column-repounderlineuserunderlinetypeunderlinename[+repo.RepoObjectColumn.Repo_user_type_name+]
* xref:repo.repoobjectcolumn_ssas_src.adoc#column-repounderlineuserunderlinetypeunderlinename[+repo.RepoObjectColumn_SSAS_src.Repo_user_type_name+]
--


[#column-repounderlineusesunderlinedatabaseunderlinecollation]
=== Repo_uses_database_collation

[cols="d,8a,m,m,m"]
|===
|
|Repo_uses_database_collation
|bit
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobjectcolumn.adoc#column-repounderlineusesunderlinedatabaseunderlinecollation[+repo.RepoObjectColumn.Repo_uses_database_collation+]
--


[#column-repoobjectunderlineguid]
=== RepoObject_guid

[cols="d,8a,m,m,m"]
|===
|
|RepoObject_guid
|uniqueidentifier
|NOT NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobjectcolumn.adoc#column-repoobjectunderlineguid[+repo.RepoObjectColumn.RepoObject_guid+]
* xref:repo.repoobjectcolumn_ssas_src.adoc#column-repoobjectunderlineguid[+repo.RepoObjectColumn_SSAS_src.RepoObject_guid+]
--


[#column-repoobjectcolumnunderlinecolumnunderlineid]
=== RepoObjectColumn_column_id

[cols="d,8a,m,m,m"]
|===
|
|RepoObjectColumn_column_id
|int
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobjectcolumn.adoc#column-repoobjectcolumnunderlinecolumnunderlineid[+repo.RepoObjectColumn.RepoObjectColumn_column_id+]
--


[#column-repoobjectcolumnunderlinename]
=== RepoObjectColumn_name

[cols="d,8a,m,m,m"]
|===
|
|RepoObjectColumn_name
|nvarchar(128)
|NOT NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobjectcolumn.adoc#column-repoobjectcolumnunderlinename[+repo.RepoObjectColumn.RepoObjectColumn_name+]
* xref:repo.repoobjectcolumn_ssas_src.adoc#column-repoobjectcolumnunderlinename[+repo.RepoObjectColumn_SSAS_src.RepoObjectColumn_name+]
--


[#column-sysobjectcolumnunderlinecolumnunderlineid]
=== SysObjectColumn_column_id

[cols="d,8a,m,m,m"]
|===
|
|SysObjectColumn_column_id
|int
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobjectcolumn.adoc#column-sysobjectcolumnunderlinecolumnunderlineid[+repo.RepoObjectColumn.SysObjectColumn_column_id+]
--


[#column-sysobjectcolumnunderlinename]
=== SysObjectColumn_name

[cols="d,8a,m,m,m"]
|===
|
|SysObjectColumn_name
|nvarchar(128)
|NOT NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobjectcolumn.adoc#column-sysobjectcolumnunderlinename[+repo.RepoObjectColumn.SysObjectColumn_name+]
* xref:repo.repoobjectcolumn_ssas_src.adoc#column-sysobjectcolumnunderlinename[+repo.RepoObjectColumn_SSAS_src.SysObjectColumn_name+]
--


// end::AntoraColumnDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]
|1
|*<<column-repoobjectcolumnunderlineguid>>*
|uniqueidentifier
|NOT NULL
|
































// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]

|
|<<column-inheritanceunderlinestringaggseparatorsql>>
|nvarchar(4000)
|NULL
|

|
|<<column-inheritancedefinition>>
|nvarchar(4000)
|NULL
|

|
|<<column-inheritancetype>>
|tinyint
|NULL
|

|
|<<column-isunderlinepersistenceunderlineignore>>
|bit
|NULL
|

|
|<<column-isunderlinepersistenceunderlinenocomparebutupdate>>
|bit
|NULL
|

|
|<<column-isunderlinepersistenceunderlinenocomparenoupdate>>
|bit
|NULL
|

|
|<<column-isunderlinequeryunderlineplanunderlineexpression>>
|bit
|NULL
|

|
|<<column-isunderlinerequiredunderlinecolumnmerge>>
|bit
|NULL
|

|
|<<column-isunderlinesysobjectcolumnunderlinemissing>>
|bit
|NULL
|

|
|<<column-persistenceunderlinesourceunderlinerepoobjectcolumnunderlineguid>>
|uniqueidentifier
|NULL
|

|
|<<column-referencingunderlinecount>>
|int
|NULL
|

|
|<<column-repounderlinedefaultunderlinedefinition>>
|nvarchar(max)
|NULL
|

|
|<<column-repounderlinedefaultunderlineisunderlinesystemunderlinenamed>>
|bit
|NULL
|

|
|<<column-repounderlinedefaultunderlinename>>
|nvarchar(128)
|NULL
|

|
|<<column-repounderlinedefinition>>
|nvarchar(max)
|NULL
|

|
|<<column-repounderlinegeneratedunderlinealwaysunderlinetype>>
|tinyint
|NOT NULL
|

|
|<<column-repounderlinegraphunderlinetype>>
|int
|NULL
|

|
|<<column-repounderlineincrementunderlinevalue>>
|sql_variant
|NULL
|

|
|<<column-repounderlineisunderlinecomputed>>
|bit
|NOT NULL
|

|
|<<column-repounderlineisunderlineidentity>>
|bit
|NOT NULL
|

|
|<<column-repounderlineisunderlinenullable>>
|bit
|NULL
|

|
|<<column-repounderlineisunderlinepersisted>>
|bit
|NULL
|

|
|<<column-repounderlineseedunderlinevalue>>
|sql_variant
|NULL
|

|
|<<column-repounderlineuserunderlinetypeunderlinefullname>>
|nvarchar(128)
|NULL
|

|
|<<column-repounderlineuserunderlinetypeunderlinename>>
|nvarchar(128)
|NULL
|

|
|<<column-repounderlineusesunderlinedatabaseunderlinecollation>>
|bit
|NULL
|

|
|<<column-repoobjectunderlineguid>>
|uniqueidentifier
|NOT NULL
|

|
|<<column-repoobjectcolumnunderlinecolumnunderlineid>>
|int
|NULL
|

|
|<<column-repoobjectcolumnunderlinename>>
|nvarchar(128)
|NOT NULL
|

|
|<<column-sysobjectcolumnunderlinecolumnunderlineid>>
|int
|NULL
|

|
|<<column-sysobjectcolumnunderlinename>>
|nvarchar(128)
|NOT NULL
|

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

[#index-pkunderlinerepoobjectcolumnunderlinessasunderlinetgt]
=== PK_RepoObjectColumn_SSAS_tgt

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-RepoObjectColumn_guid>>; uniqueidentifier
--
* PK, Unique, Real: 1, 1, 0


[#index-ukunderlinerepoobjectcolumnunderlinessasunderlinetgtunderlineunderline2]
=== UK_RepoObjectColumn_SSAS_tgt++__++2

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-RepoObjectColumn_guid>>; uniqueidentifier
* <<column-SysObjectColumn_name>>; nvarchar(128)
--
* PK, Unique, Real: 0, 1, 0


[#index-ukunderlinerepoobjectcolumnunderlinessasunderlinetgtunderlineunderline3]
=== UK_RepoObjectColumn_SSAS_tgt++__++3

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-RepoObject_guid>>; uniqueidentifier
* <<column-RepoObjectColumn_name>>; nvarchar(128)
--
* PK, Unique, Real: 0, 1, 0


[#index-idxunderlinerepoobjectcolumnunderlinessasunderlinetgtunderlineunderline4]
=== idx_RepoObjectColumn_SSAS_tgt++__++4

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-RepoObject_guid>>; uniqueidentifier
--
* PK, Unique, Real: 0, 0, 0
* is disabled


[#index-idxunderlinerepoobjectcolumnunderlinessasunderlinetgtunderlineunderline5]
=== idx_RepoObjectColumn_SSAS_tgt++__++5

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-SysObjectColumn_name>>; nvarchar(128)
--
* PK, Unique, Real: 0, 0, 0


[#index-idxunderlinerepoobjectcolumnunderlinessasunderlinetgtunderlineunderline6]
=== idx_RepoObjectColumn_SSAS_tgt++__++6

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-RepoObjectColumn_name>>; nvarchar(128)
--
* PK, Unique, Real: 0, 0, 0

// end::AntoraIndexList[]

== AntoraMeasureDetails

// tag::AntoraMeasureDetails[]

// end::AntoraMeasureDetails[]

== AntoraMeasureDescriptions



== AntoraParameterList

// tag::AntoraParameterList[]

// end::AntoraParameterList[]

== AntoraXrefCulturesList

// tag::AntoraXrefCulturesList[]
* xref:dhw:sqldb:repo.repoobjectcolumn_ssas_tgt.adoc[] - 
// end::AntoraXrefCulturesList[]

== cultures_count

// tag::cultures_count[]
1
// end::cultures_count[]

== Other tags

source: property.RepoObjectProperty_cross As rop_cross


=== additional_reference_csv

// tag::additional_reference_csv[]

// end::additional_reference_csv[]


=== AdocUspSteps

// tag::adocuspsteps[]

// end::adocuspsteps[]


=== AntoraReferencedList

// tag::antorareferencedlist[]
* xref:dhw:sqldb:repo.repoobject_ssas_tgt.adoc[]
* xref:dhw:sqldb:repo.repoobjectcolumn_ssas_src.adoc[]
// end::antorareferencedlist[]


=== AntoraReferencingList

// tag::antorareferencinglist[]
* xref:dhw:sqldb:repo.repoobjectcolumn.adoc[]
* xref:dhw:sqldb:repo.usp_persist_repoobjectcolumn_ssas_tgt.adoc[]
// end::antorareferencinglist[]


=== Description

// tag::description[]

// end::description[]


=== exampleUsage

// tag::exampleusage[]

// end::exampleusage[]


=== exampleUsage_2

// tag::exampleusage_2[]

// end::exampleusage_2[]


=== exampleUsage_3

// tag::exampleusage_3[]

// end::exampleusage_3[]


=== exampleUsage_4

// tag::exampleusage_4[]

// end::exampleusage_4[]


=== exampleUsage_5

// tag::exampleusage_5[]

// end::exampleusage_5[]


=== exampleWrong_Usage

// tag::examplewrong_usage[]

// end::examplewrong_usage[]


=== has_execution_plan_issue

// tag::has_execution_plan_issue[]

// end::has_execution_plan_issue[]


=== has_get_referenced_issue

// tag::has_get_referenced_issue[]

// end::has_get_referenced_issue[]


=== has_history

// tag::has_history[]
0
// end::has_history[]


=== has_history_columns

// tag::has_history_columns[]
0
// end::has_history_columns[]


=== InheritanceType

// tag::inheritancetype[]

// end::inheritancetype[]


=== is_persistence

// tag::is_persistence[]
1
// end::is_persistence[]


=== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]
0
// end::is_persistence_check_duplicate_per_pk[]


=== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]
0
// end::is_persistence_check_for_empty_source[]


=== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]
0
// end::is_persistence_delete_changed[]


=== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]
1
// end::is_persistence_delete_missing[]


=== is_persistence_insert

// tag::is_persistence_insert[]
1
// end::is_persistence_insert[]


=== is_persistence_truncate

// tag::is_persistence_truncate[]
0
// end::is_persistence_truncate[]


=== is_persistence_update_changed

// tag::is_persistence_update_changed[]
1
// end::is_persistence_update_changed[]


=== is_repo_managed

// tag::is_repo_managed[]
0
// end::is_repo_managed[]


=== is_ssas

// tag::is_ssas[]
0
// end::is_ssas[]


=== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


=== MS_Description

// tag::ms_description[]

// end::ms_description[]


=== persistence_source_RepoObject_fullname

// tag::persistence_source_repoobject_fullname[]
[repo].[RepoObjectColumn_SSAS_src]
// end::persistence_source_repoobject_fullname[]


=== persistence_source_RepoObject_fullname2

// tag::persistence_source_repoobject_fullname2[]
repo.RepoObjectColumn_SSAS_src
// end::persistence_source_repoobject_fullname2[]


=== persistence_source_RepoObject_guid

// tag::persistence_source_repoobject_guid[]
124559F6-0807-EC11-8515-A81E8446D5B0
// end::persistence_source_repoobject_guid[]


=== persistence_source_RepoObject_xref

// tag::persistence_source_repoobject_xref[]
xref:repo.repoobjectcolumn_ssas_src.adoc[]
// end::persistence_source_repoobject_xref[]


=== pk_index_guid

// tag::pk_index_guid[]
D004BF8F-471C-EC11-8521-A81E8446D5B0
// end::pk_index_guid[]


=== pk_IndexPatternColumnDatatype

// tag::pk_indexpatterncolumndatatype[]
uniqueidentifier
// end::pk_indexpatterncolumndatatype[]


=== pk_IndexPatternColumnName

// tag::pk_indexpatterncolumnname[]
RepoObjectColumn_guid
// end::pk_indexpatterncolumnname[]


=== pk_IndexSemanticGroup

// tag::pk_indexsemanticgroup[]

// end::pk_indexsemanticgroup[]


=== ReferencedObjectList

// tag::referencedobjectlist[]
* [repo].[RepoObject_SSAS_tgt]
* [repo].[RepoObjectColumn]
* [repo].[RepoObjectColumn_SSAS_src]
// end::referencedobjectlist[]


=== usp_persistence_RepoObject_guid

// tag::usp_persistence_repoobject_guid[]
4FCA43F5-1F07-EC11-8515-A81E8446D5B0
// end::usp_persistence_repoobject_guid[]


=== UspExamples

// tag::uspexamples[]

// end::uspexamples[]


=== uspgenerator_usp_id

// tag::uspgenerator_usp_id[]

// end::uspgenerator_usp_id[]


=== UspParameters

// tag::uspparameters[]

// end::uspparameters[]

== Boolean Attributes

source: property.RepoObjectProperty WHERE property_int = 1

// tag::boolean_attributes[]

:is_persistence:
:is_persistence_delete_missing:
:is_persistence_insert:
:is_persistence_update_changed:

// end::boolean_attributes[]

== PlantUML diagrams

=== PlantUML Entity

// tag::puml_entity[]
[plantuml, entity-{docname}, svg, subs=macros]
....
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:repo.repoobjectcolumn_ssas_tgt.adoc[]" as repo.RepoObjectColumn_SSAS_tgt << V >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  Inheritance_StringAggSeparatorSql : (nvarchar(4000))
  InheritanceDefinition : (nvarchar(4000))
  InheritanceType : (tinyint)
  is_persistence_Ignore : (bit)
  is_persistence_NoCompareButUpdate : (bit)
  is_persistence_NoCompareNoUpdate : (bit)
  is_query_plan_expression : (bit)
  is_required_ColumnMerge : (bit)
  is_SysObjectColumn_missing : (bit)
  persistence_source_RepoObjectColumn_guid : (uniqueidentifier)
  Referencing_Count : (int)
  Repo_default_definition : (nvarchar(max))
  Repo_default_is_system_named : (bit)
  Repo_default_name : (nvarchar(128))
  Repo_definition : (nvarchar(max))
  - Repo_generated_always_type : (tinyint)
  Repo_graph_type : (int)
  Repo_increment_value : (sql_variant)
  - Repo_is_computed : (bit)
  - Repo_is_identity : (bit)
  Repo_is_nullable : (bit)
  Repo_is_persisted : (bit)
  Repo_seed_value : (sql_variant)
  Repo_user_type_fullname : (nvarchar(128))
  Repo_user_type_name : (nvarchar(128))
  Repo_uses_database_collation : (bit)
  - RepoObject_guid : (uniqueidentifier)
  RepoObjectColumn_column_id : (int)
  - RepoObjectColumn_name : (nvarchar(128))
  SysObjectColumn_column_id : (int)
  - SysObjectColumn_name : (nvarchar(128))
  --
}
....

// end::puml_entity[]

=== PlantUML Entity 1 1 FK

// tag::puml_entity_1_1_fk[]
[plantuml, entity_1_1_fk-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:repo.repoobjectcolumn_ssas_tgt.adoc[]" as repo.RepoObjectColumn_SSAS_tgt << V >> {
- **PK_RepoObjectColumn_SSAS_tgt**

..
RepoObjectColumn_guid; uniqueidentifier
--
- UK_RepoObjectColumn_SSAS_tgt__2

..
RepoObjectColumn_guid; uniqueidentifier
SysObjectColumn_name; nvarchar(128)
--
- UK_RepoObjectColumn_SSAS_tgt__3

..
RepoObject_guid; uniqueidentifier
RepoObjectColumn_name; nvarchar(128)
--
- idx_RepoObjectColumn_SSAS_tgt__4

..
RepoObject_guid; uniqueidentifier
--
- idx_RepoObjectColumn_SSAS_tgt__5

..
SysObjectColumn_name; nvarchar(128)
--
- idx_RepoObjectColumn_SSAS_tgt__6

..
RepoObjectColumn_name; nvarchar(128)
}



footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_fk[]

=== PlantUML 1 1 ObjectRef

// tag::puml_entity_1_1_objectref[]
[plantuml, entity_1_1_objectref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:repo.repoobject_ssas_tgt.adoc[]" as repo.RepoObject_SSAS_tgt << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn.adoc[]" as repo.RepoObjectColumn << U >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn_ssas_src.adoc[]" as repo.RepoObjectColumn_SSAS_src << V >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn_ssas_tgt.adoc[]" as repo.RepoObjectColumn_SSAS_tgt << V >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.usp_persist_repoobjectcolumn_ssas_tgt.adoc[]" as repo.usp_PERSIST_RepoObjectColumn_SSAS_tgt << P >> {
  --
}

repo.RepoObject_SSAS_tgt <.. repo.RepoObjectColumn_SSAS_tgt
repo.RepoObjectColumn_SSAS_src <.. repo.RepoObjectColumn_SSAS_tgt
repo.RepoObjectColumn_SSAS_tgt <.. repo.RepoObjectColumn
repo.RepoObjectColumn_SSAS_tgt <.. repo.usp_PERSIST_RepoObjectColumn_SSAS_tgt

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_objectref[]

=== PlantUML 30 0 ObjectRef

// tag::puml_entity_30_0_objectref[]
[plantuml, entity_30_0_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:repo.repoobject_ssas_src.adoc[]" as repo.RepoObject_SSAS_src << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_ssas_tgt.adoc[]" as repo.RepoObject_SSAS_tgt << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn_ssas_src.adoc[]" as repo.RepoObjectColumn_SSAS_src << V >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn_ssas_tgt.adoc[]" as repo.RepoObjectColumn_SSAS_tgt << V >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.reposchema.adoc[]" as repo.RepoSchema << U >> {
  - **RepoSchema_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.reposchema_ssas_src.adoc[]" as repo.RepoSchema_ssas_src << V >> {
  - **RepoSchema_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:repo.reposchema_ssas_tgt.adoc[]" as repo.RepoSchema_ssas_tgt << V >> {
  - **RepoSchema_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json.adoc[]" as ssas.model_json << U >> {
  - **databasename** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_10.adoc[]" as ssas.model_json_10 << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_20.adoc[]" as ssas.model_json_20 << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_201_descriptions_multiline.adoc[]" as ssas.model_json_201_descriptions_multiline << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_2011_descriptions_stragg.adoc[]" as ssas.model_json_2011_descriptions_StrAgg << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31_tables.adoc[]" as ssas.model_json_31_tables << V >> {
  - **databasename** : (nvarchar(128))
  **tables_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31_tables_t.adoc[]" as ssas.model_json_31_tables_T << U >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_311_tables_columns.adoc[]" as ssas.model_json_311_tables_columns << V >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  **tables_columns_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_311_tables_columns_t.adoc[]" as ssas.model_json_311_tables_columns_T << U >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  - **tables_columns_name** : (nvarchar(128))
  --
}

repo.RepoObject_SSAS_src <.. repo.RepoObject_SSAS_tgt
repo.RepoObject_SSAS_tgt <.. repo.RepoObjectColumn_SSAS_tgt
repo.RepoObjectColumn_SSAS_src <.. repo.RepoObjectColumn_SSAS_tgt
repo.RepoSchema <.. repo.RepoObject_SSAS_src
repo.RepoSchema_ssas_src <.. repo.RepoSchema_ssas_tgt
repo.RepoSchema_ssas_tgt <.. repo.RepoSchema
ssas.model_json <.. ssas.model_json_10
ssas.model_json_10 <.. ssas.model_json_20
ssas.model_json_20 <.. repo.RepoSchema_ssas_src
ssas.model_json_20 <.. ssas.model_json_31_tables
ssas.model_json_20 <.. ssas.model_json_201_descriptions_multiline
ssas.model_json_201_descriptions_multiline <.. ssas.model_json_2011_descriptions_StrAgg
ssas.model_json_2011_descriptions_StrAgg <.. repo.RepoSchema_ssas_src
ssas.model_json_31_tables <.. ssas.model_json_31_tables_T
ssas.model_json_31_tables_T <.. repo.RepoObject_SSAS_src
ssas.model_json_31_tables_T <.. ssas.model_json_311_tables_columns
ssas.model_json_311_tables_columns <.. ssas.model_json_311_tables_columns_T
ssas.model_json_311_tables_columns_T <.. repo.RepoObjectColumn_SSAS_src

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_30_0_objectref[]

=== PlantUML 0 30 ObjectRef

// tag::puml_entity_0_30_objectref[]
[plantuml, entity_0_30_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:dmdocs.unit.adoc[]" as dmdocs.unit << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.antoranavlistpage_by_schema.adoc[]" as docs.AntoraNavListPage_by_schema << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.antoranavlistpage_by_type.adoc[]" as docs.AntoraNavListPage_by_type << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.antoranavlistrepoobject_by_schema.adoc[]" as docs.AntoraNavListRepoObject_by_schema << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.antoranavlistrepoobject_by_schema_type.adoc[]" as docs.AntoraNavListRepoObject_by_schema_type << V >> {
  - **RepoObject_schema_name** : (nvarchar(128))
  **type** : (char(2))
  --
}

entity "puml-link:dhw:sqldb:docs.antoranavlistrepoobject_by_type.adoc[]" as docs.AntoraNavListRepoObject_by_type << V >> {
  **type** : (char(2))
  --
}

entity "puml-link:dhw:sqldb:docs.antorapage_indexsemanticgroup.adoc[]" as docs.AntoraPage_IndexSemanticGroup << V >> {
  - **page_content** : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:docs.antorapage_objectbyschema.adoc[]" as docs.AntoraPage_ObjectBySchema << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.antorapage_objectbytype.adoc[]" as docs.AntoraPage_ObjectByType << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.foreignkey_relationscript.adoc[]" as docs.ForeignKey_RelationScript << V >> {
  **referenced_RepoObject_guid** : (uniqueidentifier)
  **referencing_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:docs.ftv_repoobject_reference_plantuml_entityreflist.adoc[]" as docs.ftv_RepoObject_Reference_PlantUml_EntityRefList << IF >> {
  --
}

entity "puml-link:dhw:sqldb:docs.indexsemanticgroup.adoc[]" as docs.IndexSemanticgroup << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.indexsemanticgrouppatterndatatype.adoc[]" as docs.IndexSemanticgroupPatterndatatype << V >> {
  **IndexSemanticGroup** : (nvarchar(512))
  **IndexPatternColumnDatatype** : (nvarchar(4000))
  --
}

entity "puml-link:dhw:sqldb:docs.objectrefcyclic.adoc[]" as docs.ObjectRefCyclic << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.objectrefcyclic_entitylist.adoc[]" as docs.ObjectRefCyclic_EntityList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.objectrefcyclic_objectreflist.adoc[]" as docs.ObjectRefCyclic_ObjectRefList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_adoc.adoc[]" as docs.RepoObject_Adoc << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_adoc_t.adoc[]" as docs.RepoObject_Adoc_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_antoraxrefcultureslist.adoc[]" as docs.RepoObject_AntoraXrefCulturesList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_columnlist.adoc[]" as docs.RepoObject_ColumnList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_columnlist_t.adoc[]" as docs.RepoObject_ColumnList_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_indexlist.adoc[]" as docs.RepoObject_IndexList << V >> {
  **RepoObject_guid** : (uniqueidentifier)
  **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_indexlist_t.adoc[]" as docs.RepoObject_IndexList_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_measuredescriptionlist.adoc[]" as docs.RepoObject_MeasureDescriptionList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_measurelist.adoc[]" as docs.RepoObject_MeasureList << V >> {
  **RepoObject_guid** : (uniqueidentifier)
  **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_outputfilter.adoc[]" as docs.RepoObject_OutputFilter << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_outputfilter_t.adoc[]" as docs.RepoObject_OutputFilter_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_outputfilter_t_gross.adoc[]" as docs.RepoObject_OutputFilter_T_gross << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml.adoc[]" as docs.RepoObject_Plantuml << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_colreflist_1_1.adoc[]" as docs.RepoObject_Plantuml_ColRefList_1_1 << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_entity.adoc[]" as docs.RepoObject_Plantuml_Entity << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_entity_t.adoc[]" as docs.RepoObject_Plantuml_Entity_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_fkreflist.adoc[]" as docs.RepoObject_PlantUml_FkRefList << V >> {
  **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_objectreflist_0_30.adoc[]" as docs.RepoObject_Plantuml_ObjectRefList_0_30 << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_objectreflist_1_1.adoc[]" as docs.RepoObject_Plantuml_ObjectRefList_1_1 << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_objectreflist_30_0.adoc[]" as docs.RepoObject_Plantuml_ObjectRefList_30_0 << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_pumlentityfklist.adoc[]" as docs.RepoObject_PlantUml_PumlEntityFkList << V >> {
  **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_t.adoc[]" as docs.RepoObject_Plantuml_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.schema_entitylist.adoc[]" as docs.Schema_EntityList << V >> {
  - **RepoObject_schema_name** : (nvarchar(128))
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.schema_puml.adoc[]" as docs.Schema_puml << V >> {
  - **RepoSchema_guid** : (uniqueidentifier)
  **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.schema_pumlpartial_fkreflist.adoc[]" as docs.Schema_PumlPartial_FkRefList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.schema_ssasrelationlist.adoc[]" as docs.Schema_SsasRelationList << V >> {
  - **SchemaName** : (nvarchar(128))
  **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.unit_1_union.adoc[]" as docs.Unit_1_union << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.unit_2.adoc[]" as docs.Unit_2 << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.unit_3.adoc[]" as docs.Unit_3 << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport.adoc[]" as docs.usp_AntoraExport << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_objectnavigation.adoc[]" as docs.usp_AntoraExport_ObjectNavigation << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_objectpage.adoc[]" as docs.usp_AntoraExport_ObjectPage << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_objectpartialscontent.adoc[]" as docs.usp_AntoraExport_ObjectPartialsContent << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_objectpuml.adoc[]" as docs.usp_AntoraExport_ObjectPuml << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_repoobject_adoc_t.adoc[]" as docs.usp_PERSIST_RepoObject_Adoc_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_repoobject_columnlist_t.adoc[]" as docs.usp_PERSIST_RepoObject_ColumnList_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_repoobject_indexlist_t.adoc[]" as docs.usp_PERSIST_RepoObject_IndexList_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_repoobject_outputfilter_t.adoc[]" as docs.usp_PERSIST_RepoObject_OutputFilter_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_repoobject_plantuml_entity_t.adoc[]" as docs.usp_PERSIST_RepoObject_Plantuml_Entity_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_repoobject_plantuml_t.adoc[]" as docs.usp_PERSIST_RepoObject_Plantuml_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:graph.repoobjectcolumn_s.adoc[]" as graph.RepoObjectColumn_S << V >> {
  --
}

entity "puml-link:dhw:sqldb:property.extendedproperty_repo2sys_level2_repoobjectcolumn.adoc[]" as property.ExtendedProperty_Repo2Sys_level2_RepoObjectColumn << V >> {
  - **level0type** : (nvarchar(6))
  - **level0name** : (nvarchar(128))
  **level1type** : (varchar(9))
  - **level1name** : (nvarchar(128))
  - **level2type** : (nvarchar(6))
  - **level2name** : (nvarchar(128))
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.extendedproperty_repo2sys_level2_union.adoc[]" as property.ExtendedProperty_Repo2Sys_level2_Union << V >> {
  - **level0type** : (nvarchar(6))
  - **level0name** : (nvarchar(128))
  **level1type** : (varchar(9))
  - **level1name** : (nvarchar(128))
  **level2type** : (nvarchar(10))
  - **level2name** : (nvarchar(128))
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.fs_get_repoobjectcolumnproperty_nvarchar.adoc[]" as property.fs_get_RepoObjectColumnProperty_nvarchar << FN >> {
  --
}

entity "puml-link:dhw:sqldb:property.propertyname_repoobjectcolumn.adoc[]" as property.PropertyName_RepoObjectColumn << V >> {
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.propertyname_repoobjectcolumn_t.adoc[]" as property.PropertyName_RepoObjectColumn_T << U >> {
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectcolumnproperty.adoc[]" as property.RepoObjectColumnProperty << U >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectcolumnproperty_external_tgt.adoc[]" as property.RepoObjectColumnProperty_external_tgt << V >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectcolumnproperty_forupdate.adoc[]" as property.RepoObjectColumnProperty_ForUpdate << V >> {
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectcolumnproperty_inheritancetype_inheritancedefinition.adoc[]" as property.RepoObjectColumnProperty_InheritanceType_InheritanceDefinition << V >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectcolumnproperty_inheritancetype_resulting_inheritancedefinition.adoc[]" as property.RepoObjectColumnProperty_InheritanceType_resulting_InheritanceDefinition << V >> {
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectcolumnproperty_sys_repo.adoc[]" as property.RepoObjectColumnProperty_sys_repo << V >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  - **property_name** : (sysname)
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty_collect_source_rogross.adoc[]" as property.RepoObjectProperty_Collect_source_ROGross << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **property_name** : (varchar(39))
  --
}

entity "puml-link:dhw:sqldb:property.usp_external_property_import.adoc[]" as property.usp_external_property_import << P >> {
  --
}

entity "puml-link:dhw:sqldb:property.usp_external_repoobjectproperty.adoc[]" as property.usp_external_RepoObjectProperty << P >> {
  --
}

entity "puml-link:dhw:sqldb:property.usp_persist_propertyname_repoobjectcolumn_t.adoc[]" as property.usp_PERSIST_PropertyName_RepoObjectColumn_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:property.usp_persist_repoobjectcolumnproperty_external_tgt.adoc[]" as property.usp_PERSIST_RepoObjectColumnProperty_external_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:property.usp_repoobject_inheritance.adoc[]" as property.usp_RepoObject_Inheritance << P >> {
  --
}

entity "puml-link:dhw:sqldb:property.usp_repoobjectcolumn_inheritance.adoc[]" as property.usp_RepoObjectColumn_Inheritance << P >> {
  --
}

entity "puml-link:dhw:sqldb:property.usp_repoobjectcolumnproperty_set.adoc[]" as property.usp_RepoObjectColumnProperty_set << P >> {
  --
}

entity "puml-link:dhw:sqldb:property.usp_repoobjectproperty_collect.adoc[]" as property.usp_RepoObjectProperty_collect << P >> {
  --
}

entity "puml-link:dhw:sqldb:property.usp_sync_extendedproperties_repo2sys_delete.adoc[]" as property.usp_sync_ExtendedProperties_Repo2Sys_Delete << P >> {
  --
}

entity "puml-link:dhw:sqldb:property.usp_sync_extendedproperties_repo2sys_insertupdate.adoc[]" as property.usp_sync_ExtendedProperties_Repo2Sys_InsertUpdate << P >> {
  --
}

entity "puml-link:dhw:sqldb:property.usp_sync_extendedproperties_sys2repo_insertupdate.adoc[]" as property.usp_sync_ExtendedProperties_Sys2Repo_InsertUpdate << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_guid.adoc[]" as reference.additional_Reference_guid << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.ftv_repoobject_columreferencerepoobject.adoc[]" as reference.ftv_RepoObject_ColumReferenceRepoObject << IF >> {
  --
}

entity "puml-link:dhw:sqldb:reference.ftv_repoobject_dbmlcolumnrelation.adoc[]" as reference.ftv_RepoObject_DbmlColumnRelation << IF >> {
  --
}

entity "puml-link:dhw:sqldb:reference.ftv_repoobject_referencetree.adoc[]" as reference.ftv_RepoObject_ReferenceTree << IF >> {
  --
}

entity "puml-link:dhw:sqldb:reference.ftv_repoobject_referencetree_referenced.adoc[]" as reference.ftv_RepoObject_ReferenceTree_referenced << IF >> {
  --
}

entity "puml-link:dhw:sqldb:reference.ftv_repoobject_referencetree_referencing.adoc[]" as reference.ftv_RepoObject_ReferenceTree_referencing << IF >> {
  --
}

entity "puml-link:dhw:sqldb:reference.ftv_repoobject_referencetree_via_fullname.adoc[]" as reference.ftv_RepoObject_ReferenceTree_via_fullname << IF >> {
  --
}

entity "puml-link:dhw:sqldb:reference.ftv_repoobjectcolumn_referencetree.adoc[]" as reference.ftv_RepoObjectColumn_ReferenceTree << IF >> {
  --
}

entity "puml-link:dhw:sqldb:reference.persistence.adoc[]" as reference.Persistence << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.persistence_bidirectional.adoc[]" as reference.Persistence_bidirectional << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.referencetree_cyclic_ref_persistenceusp.adoc[]" as reference.ReferenceTree_cyclic_ref_PersistenceUsp << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.referencetree_cyclic_union.adoc[]" as reference.ReferenceTree_cyclic_union << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_reference.adoc[]" as reference.RepoObject_reference << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_reference_additional.adoc[]" as reference.RepoObject_reference_additional << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_reference_additional_internal.adoc[]" as reference.RepoObject_reference_additional_internal << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_reference_persistence_target_as_source.adoc[]" as reference.RepoObject_reference_persistence_target_as_source << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_reference_persistence_target_as_source_explicit.adoc[]" as reference.RepoObject_reference_persistence_target_as_source_explicit << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_reference_sqlexpressiondependencies.adoc[]" as reference.RepoObject_reference_SqlExpressionDependencies << V >> {
  **referenced_RepoObject_guid** : (uniqueidentifier)
  **referencing_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_reference_t.adoc[]" as reference.RepoObject_reference_T << U >> {
  - **referenced_RepoObject_guid** : (uniqueidentifier)
  - **referencing_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_reference_t_bidirectional.adoc[]" as reference.RepoObject_reference_T_bidirectional << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_reference_union.adoc[]" as reference.RepoObject_reference_union << V >> {
  **referenced_RepoObject_guid** : (uniqueidentifier)
  **referencing_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_referencedlist.adoc[]" as reference.RepoObject_ReferencedList << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_referencedreferencing.adoc[]" as reference.RepoObject_ReferencedReferencing << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_referencetree_0_30.adoc[]" as reference.RepoObject_ReferenceTree_0_30 << V >> {
  **RepoObject_guid** : (uniqueidentifier)
  **Referencing_guid** : (uniqueidentifier)
  **Referenced_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_referencetree_0_30_t.adoc[]" as reference.RepoObject_ReferenceTree_0_30_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **Referencing_guid** : (uniqueidentifier)
  - **Referenced_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_referencetree_30_0.adoc[]" as reference.RepoObject_ReferenceTree_30_0 << V >> {
  **RepoObject_guid** : (uniqueidentifier)
  **Referencing_guid** : (uniqueidentifier)
  **Referenced_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_referencetree_30_0_t.adoc[]" as reference.RepoObject_ReferenceTree_30_0_T << U >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_referencetree_referenced.adoc[]" as reference.RepoObject_ReferenceTree_referenced << V >> {
  **RepoObject_guid** : (uniqueidentifier)
  **Referenced_Depth** : (int)
  **Referencing_Depth** : (int)
  **Referenced_guid** : (uniqueidentifier)
  **Referencing_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_referencetree_referenced_30_0.adoc[]" as reference.RepoObject_ReferenceTree_referenced_30_0 << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  **Referenced_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_referencetree_referencing.adoc[]" as reference.RepoObject_ReferenceTree_referencing << V >> {
  **RepoObject_guid** : (uniqueidentifier)
  **Referenced_Depth** : (int)
  **Referencing_Depth** : (int)
  **Referenced_guid** : (uniqueidentifier)
  **Referencing_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_referencetree_referencing_0_30.adoc[]" as reference.RepoObject_ReferenceTree_referencing_0_30 << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  **Referencing_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_referencinglist.adoc[]" as reference.RepoObject_ReferencingList << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_reference.adoc[]" as reference.RepoObjectColumn_reference << V >> {
  **referenced_RepoObjectColumn_guid** : (uniqueidentifier)
  **referencing_RepoObjectColumn_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_reference_additional.adoc[]" as reference.RepoObjectColumn_reference_additional << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_reference_additional_internal.adoc[]" as reference.RepoObjectColumn_reference_additional_internal << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_reference_bysamepredecessors.adoc[]" as reference.RepoObjectColumn_reference_BySamePredecessors << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_reference_firstresultset.adoc[]" as reference.RepoObjectColumn_reference_FirstResultSet << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_reference_persistence.adoc[]" as reference.RepoObjectColumn_reference_Persistence << V >> {
  **referencing_id** : (int)
  **referencing_minor_id** : (int)
  **referenced_id** : (int)
  **referenced_minor_id** : (int)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_reference_queryplan.adoc[]" as reference.RepoObjectColumn_reference_QueryPlan << V >> {
  **referencing_id** : (int)
  **referencing_minor_id** : (int)
  **referenced_id** : (int)
  **referenced_minor_id** : (int)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_reference_sqlexpressiondependencies.adoc[]" as reference.RepoObjectColumn_reference_SqlExpressionDependencies << V >> {
  - **referencing_id** : (int)
  - **referencing_minor_id** : (int)
  **referenced_id** : (int)
  - **referenced_minor_id** : (int)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_reference_sqlmodules.adoc[]" as reference.RepoObjectColumn_reference_SqlModules << V >> {
  **referencing_id** : (int)
  **referencing_minor_id** : (int)
  **referenced_id** : (int)
  **referenced_minor_id** : (int)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_reference_t.adoc[]" as reference.RepoObjectColumn_reference_T << U >> {
  - **referenced_RepoObjectColumn_guid** : (uniqueidentifier)
  - **referencing_RepoObjectColumn_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_reference_union.adoc[]" as reference.RepoObjectColumn_reference_union << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_reference_virtual.adoc[]" as reference.RepoObjectColumn_reference_virtual << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_referencedlist.adoc[]" as reference.RepoObjectColumn_ReferencedList << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_referencedreferencing.adoc[]" as reference.RepoObjectColumn_ReferencedReferencing << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_referencetree.adoc[]" as reference.RepoObjectColumn_ReferenceTree << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_referencinglist.adoc[]" as reference.RepoObjectColumn_ReferencingList << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_relationscript.adoc[]" as reference.RepoObjectColumn_RelationScript << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.sysobjectcolumn_queryplanexpression.adoc[]" as reference.SysObjectColumn_QueryPlanExpression << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_persist_repoobject_reference_t.adoc[]" as reference.usp_PERSIST_RepoObject_reference_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_persist_repoobject_referencetree_0_30_t.adoc[]" as reference.usp_PERSIST_RepoObject_ReferenceTree_0_30_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_persist_repoobject_referencetree_30_0_t.adoc[]" as reference.usp_PERSIST_RepoObject_ReferenceTree_30_0_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_persist_repoobjectcolumn_reference_t.adoc[]" as reference.usp_PERSIST_RepoObjectColumn_reference_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_repoobject_referencetree.adoc[]" as reference.usp_RepoObject_ReferenceTree << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_repoobject_referencetree_insert.adoc[]" as reference.usp_RepoObject_ReferenceTree_insert << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_repoobject_update_sysobjectqueryplan.adoc[]" as reference.usp_RepoObject_update_SysObjectQueryPlan << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_repoobjectcolumnsource_virtual_set.adoc[]" as reference.usp_RepoObjectColumnSource_virtual_set << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_repoobjectsource_firstresultset.adoc[]" as reference.usp_RepoObjectSource_FirstResultSet << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_repoobjectsource_queryplan.adoc[]" as reference.usp_RepoObjectSource_QueryPlan << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_update_referencing_count.adoc[]" as reference.usp_update_Referencing_Count << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.check_indexcolumn_virtual_referenced_setpoint.adoc[]" as repo.check_IndexColumn_virtual_referenced_setpoint << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.foreignkey_gross.adoc[]" as repo.ForeignKey_gross << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.foreignkey_indexes.adoc[]" as repo.ForeignKey_Indexes << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.foreignkey_indexes_union.adoc[]" as repo.ForeignKey_Indexes_union << V >> {
  **ForeignKey_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.foreignkey_indexes_union_t.adoc[]" as repo.ForeignKey_Indexes_union_T << U >> {
  **ForeignKey_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.foreignkey_virtual_indexes.adoc[]" as repo.ForeignKey_virtual_Indexes << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.index_columlist.adoc[]" as repo.Index_ColumList << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.index_columlist_t.adoc[]" as repo.Index_ColumList_T << U >> {
  - **index_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.index_gross.adoc[]" as repo.Index_gross << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.index_indexpattern.adoc[]" as repo.Index_IndexPattern << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.index_referencing_indexpatterncolumnguid.adoc[]" as repo.Index_referencing_IndexPatternColumnGuid << V >> {
  **source_index_guid** : (uniqueidentifier)
  **referencing_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.index_settings_forupdate.adoc[]" as repo.Index_Settings_ForUpdate << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.index_sqlconstraint_pkuq.adoc[]" as repo.Index_SqlConstraint_PkUq << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.index_union.adoc[]" as repo.Index_union << V >> {
  **index_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.index_unique_indexpatterncolumnguid.adoc[]" as repo.Index_unique_IndexPatternColumnGuid << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.index_virtual_forupdate.adoc[]" as repo.Index_virtual_ForUpdate << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.indexcolumn_referencedreferencing_hasfullcolumnsinreferencing.adoc[]" as repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing << V >> {
  - **index_guid** : (uniqueidentifier)
  - **index_column_id** : (int)
  **RowNumberInReferencing** : (bigint)
  --
}

entity "puml-link:dhw:sqldb:repo.indexcolumn_referencedreferencing_hasfullcolumnsinreferencing_check.adoc[]" as repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_check << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.indexcolumn_referencedreferencing_hasfullcolumnsinreferencing_t.adoc[]" as repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T << U >> {
  **index_guid** : (uniqueidentifier)
  - **index_column_id** : (int)
  **RowNumberInReferencing** : (bigint)
  --
}

entity "puml-link:dhw:sqldb:repo.indexcolumn_ssas_gross.adoc[]" as repo.IndexColumn_ssas_gross << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.indexcolumn_union.adoc[]" as repo.IndexColumn_union << V >> {
  **index_guid** : (uniqueidentifier)
  - **index_column_id** : (int)
  --
}

entity "puml-link:dhw:sqldb:repo.indexcolumn_union_t.adoc[]" as repo.IndexColumn_union_T << U >> {
  - **index_guid** : (uniqueidentifier)
  - **index_column_id** : (int)
  --
}

entity "puml-link:dhw:sqldb:repo.indexcolumn_virtual_gross.adoc[]" as repo.IndexColumn_virtual_gross << V >> {
  - **index_column_id** : (int)
  --
}

entity "puml-link:dhw:sqldb:repo.indexcolumn_virtual_referenced_setpoint.adoc[]" as repo.IndexColumn_virtual_referenced_setpoint << V >> {
  - **index_guid** : (uniqueidentifier)
  - **index_column_id** : (int)
  --
}

entity "puml-link:dhw:sqldb:repo.indexreferencedreferencing.adoc[]" as repo.IndexReferencedReferencing << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.indexreferencedreferencing_hasfullcolumnsinreferencing.adoc[]" as repo.IndexReferencedReferencing_HasFullColumnsInReferencing << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_columnlist.adoc[]" as repo.RepoObject_ColumnList << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_gross.adoc[]" as repo.RepoObject_gross << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_gross2.adoc[]" as repo.RepoObject_gross2 << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_persistence_column.adoc[]" as repo.RepoObject_persistence_column << V >> {
  - **target_RepoObject_guid** : (uniqueidentifier)
  **RepoObjectColumn_guid_s** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_persistence_nocomparebutupdate.adoc[]" as repo.RepoObject_persistence_NoCompareButUpdate << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_persistence_nocomparenoupdate.adoc[]" as repo.RepoObject_persistence_NoCompareNoUpdate << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_persistence_source_ignore.adoc[]" as repo.RepoObject_persistence_source_Ignore << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_persistence_target_ignore.adoc[]" as repo.RepoObject_persistence_target_Ignore << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_related_fk_union.adoc[]" as repo.RepoObject_related_FK_union << V >> {
  **RepoObject_guid** : (uniqueidentifier)
  **included_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_sat2.adoc[]" as repo.RepoObject_sat2 << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_sat2_t.adoc[]" as repo.RepoObject_sat2_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_sqlcreatetable.adoc[]" as repo.RepoObject_SqlCreateTable << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_wo_referencing.adoc[]" as repo.RepoObject_wo_referencing << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn.adoc[]" as repo.RepoObjectColumn << U >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn_gross.adoc[]" as repo.RepoObjectColumn_gross << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn_gross2.adoc[]" as repo.RepoObjectColumn_gross2 << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn_missingsource_typev.adoc[]" as repo.RepoObjectColumn_MissingSource_TypeV << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn_requiredrepoobjectcolumnmerge.adoc[]" as repo.RepoObjectColumn_RequiredRepoObjectColumnMerge << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn_ssas_tgt.adoc[]" as repo.RepoObjectColumn_SSAS_tgt << V >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.syscolumn_repoobjectcolumn_via_guid.adoc[]" as repo.SysColumn_RepoObjectColumn_via_guid << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.syscolumn_repoobjectcolumn_via_name.adoc[]" as repo.SysColumn_RepoObjectColumn_via_name << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_index_finish.adoc[]" as repo.usp_Index_finish << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_index_foreignkey.adoc[]" as repo.usp_Index_ForeignKey << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_index_inheritance.adoc[]" as repo.usp_index_inheritance << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_index_settings.adoc[]" as repo.usp_Index_Settings << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_index_virtual_set.adoc[]" as repo.usp_Index_virtual_set << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_main.adoc[]" as repo.usp_main << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_persist_foreignkey_indexes_union_t.adoc[]" as repo.usp_PERSIST_ForeignKey_Indexes_union_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_persist_index_columlist_t.adoc[]" as repo.usp_PERSIST_Index_ColumList_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_persist_indexcolumn_referencedreferencing_hasfullcolumnsinreferencing_t.adoc[]" as repo.usp_PERSIST_IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_persist_indexcolumn_union_t.adoc[]" as repo.usp_PERSIST_IndexColumn_union_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_persist_repoobject_sat2_t.adoc[]" as repo.usp_PERSIST_RepoObject_sat2_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_persist_repoobjectcolumn_ssas_tgt.adoc[]" as repo.usp_PERSIST_RepoObjectColumn_SSAS_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_persistence_set.adoc[]" as repo.usp_persistence_set << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_sync_guid.adoc[]" as repo.usp_sync_guid << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_sync_guid_repoobjectcolumn.adoc[]" as repo.usp_sync_guid_RepoObjectColumn << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_sync_guid_ssas.adoc[]" as repo.usp_sync_guid_ssas << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_update_referencing_count.adoc[]" as repo.usp_update_Referencing_Count << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo_sys.indexcolumn_unique.adoc[]" as repo_sys.IndexColumn_unique << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo_sys.sql_expression_dependencies.adoc[]" as repo_sys.sql_expression_dependencies << V >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_71_reference_explicitetablealias.adoc[]" as sqlparse.RepoObject_SqlModules_71_reference_ExpliciteTableAlias << V >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_72_reference_notablealias.adoc[]" as sqlparse.RepoObject_SqlModules_72_reference_NoTableAlias << V >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_79_reference_union.adoc[]" as sqlparse.RepoObject_SqlModules_79_reference_union << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.repoobjectcolumn_translation.adoc[]" as ssas.RepoObjectColumn_translation << V >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:ssas.repoobjectcolumn_translation_displayfolder_union.adoc[]" as ssas.RepoObjectColumn_translation_displayfolder_union << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.repoobjectcolumn_translation_t.adoc[]" as ssas.RepoObjectColumn_translation_T << U >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:ssas.usp_persist_repoobjectcolumn_translation_t.adoc[]" as ssas.usp_PERSIST_RepoObjectColumn_translation_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.generatoruspstep_persistence_isinactive_setpoint.adoc[]" as uspgenerator.GeneratorUspStep_Persistence_IsInactive_setpoint << V >> {
  - **usp_id** : (int)
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.generatoruspstep_persistence_src.adoc[]" as uspgenerator.GeneratorUspStep_Persistence_src << V >> {
  - **usp_id** : (int)
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.usp_generatorusp_insert_update_persistence.adoc[]" as uspgenerator.usp_GeneratorUsp_insert_update_persistence << P >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.biml_package.adoc[]" as workflow.Biml_Package << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.biml_precedenceconstraints.adoc[]" as workflow.Biml_PrecedenceConstraints << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.biml_project.adoc[]" as workflow.Biml_Project << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.biml_task.adoc[]" as workflow.Biml_Task << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.proceduredependency.adoc[]" as workflow.ProcedureDependency << U >> {
  - **id** : (int)
  --
}

entity "puml-link:dhw:sqldb:workflow.proceduredependency_gross.adoc[]" as workflow.ProcedureDependency_gross << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.proceduredependency_input_persistencedependency.adoc[]" as workflow.ProcedureDependency_input_PersistenceDependency << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.proceduredependency_input_persistencedependency_s.adoc[]" as workflow.ProcedureDependency_input_PersistenceDependency_S << V >> {
  **referenced_Procedure_RepoObject_guid** : (uniqueidentifier)
  **referencing_Procedure_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:workflow.proceduredependency_persistencedependency_src.adoc[]" as workflow.ProcedureDependency_PersistenceDependency_src << V >> {
  **referenced_Procedure_RepoObject_guid** : (uniqueidentifier)
  **referencing_Procedure_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:workflow.proceduredependency_persistencedependency_tgt.adoc[]" as workflow.ProcedureDependency_PersistenceDependency_tgt << V >> {
  - **referenced_Procedure_RepoObject_guid** : (uniqueidentifier)
  - **referencing_Procedure_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:workflow.usp_persist_proceduredependency_persistencedependency_tgt.adoc[]" as workflow.usp_PERSIST_ProcedureDependency_PersistenceDependency_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.usp_persist_workflow_proceduredependency_t.adoc[]" as workflow.usp_PERSIST_Workflow_ProcedureDependency_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.usp_persist_workflowstep.adoc[]" as workflow.usp_PERSIST_WorkflowStep << P >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.usp_workflow.adoc[]" as workflow.usp_workflow << P >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.workflow_proceduredependency.adoc[]" as workflow.Workflow_ProcedureDependency << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.workflow_proceduredependency_all.adoc[]" as workflow.Workflow_ProcedureDependency_all << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.workflow_proceduredependency_t.adoc[]" as workflow.Workflow_ProcedureDependency_T << U >> {
  - **Workflow_id** : (int)
  - **referenced_Procedure_RepoObject_guid** : (uniqueidentifier)
  - **referencing_Procedure_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:workflow.workflow_proceduredependency_t_active.adoc[]" as workflow.Workflow_ProcedureDependency_T_active << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.workflow_proceduredependency_t_bidirectional.adoc[]" as workflow.Workflow_ProcedureDependency_T_bidirectional << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.workflow_proceduredependency_t_bidirectional_t.adoc[]" as workflow.Workflow_ProcedureDependency_T_bidirectional_T << U >> {
  - **Workflow_id** : (int)
  - **referenced_Procedure_RepoObject_guid** : (uniqueidentifier)
  - **referencing_Procedure_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:workflow.workflow_proceduredependency_t_notinsortorder.adoc[]" as workflow.Workflow_ProcedureDependency_T_NotInSortorder << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.workflow_proceduredependency_t_notinsortorder_check.adoc[]" as workflow.Workflow_ProcedureDependency_T_NotInSortorder_check << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.workflow_proceduredependency_t_redundant.adoc[]" as workflow.Workflow_ProcedureDependency_T_redundant << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.workflow_proceduredependency_t_taskname.adoc[]" as workflow.Workflow_ProcedureDependency_T_TaskName << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.workflow_proceduredependency_wo_redundant.adoc[]" as workflow.Workflow_ProcedureDependency_wo_redundant << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.workflowstep.adoc[]" as workflow.WorkflowStep << U >> {
  - **id** : (int)
  --
}

entity "puml-link:dhw:sqldb:workflow.workflowstep_active.adoc[]" as workflow.WorkflowStep_active << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.workflowstep_forupdate.adoc[]" as workflow.WorkflowStep_ForUpdate << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.workflowstep_src.adoc[]" as workflow.WorkflowStep_src << V >> {
  - **Workflow_id** : (int)
  **Procedure_RepoObject_guid** : (uniqueidentifier)
  --
}

docs.AntoraNavListPage_by_type <.. docs.usp_AntoraExport_ObjectNavigation
docs.AntoraNavListRepoObject_by_schema <.. docs.AntoraPage_ObjectBySchema
docs.AntoraNavListRepoObject_by_schema <.. docs.usp_AntoraExport_ObjectNavigation
docs.AntoraNavListRepoObject_by_schema_type <.. docs.usp_AntoraExport_ObjectNavigation
docs.AntoraNavListRepoObject_by_type <.. docs.AntoraPage_ObjectByType
docs.AntoraNavListRepoObject_by_type <.. docs.usp_AntoraExport_ObjectNavigation
docs.ftv_RepoObject_Reference_PlantUml_EntityRefList <.. docs.RepoObject_Plantuml
docs.IndexSemanticgroup <.. docs.AntoraPage_IndexSemanticGroup
docs.IndexSemanticgroupPatterndatatype <.. docs.IndexSemanticgroup
docs.ObjectRefCyclic_EntityList <.. docs.ObjectRefCyclic
docs.ObjectRefCyclic_ObjectRefList <.. docs.ObjectRefCyclic
docs.RepoObject_Adoc <.. docs.RepoObject_Adoc_T
docs.RepoObject_Adoc <.. docs.usp_PERSIST_RepoObject_Adoc_T
docs.REpoObject_Adoc_T <.. docs.usp_PERSIST_RepoObject_Adoc_T
docs.RepoObject_AntoraXrefCulturesList <.. docs.RepoObject_Adoc
docs.RepoObject_ColumnList <.. docs.RepoObject_ColumnList_T
docs.RepoObject_ColumnList <.. docs.usp_PERSIST_RepoObject_ColumnList_T
docs.RepoObject_ColumnList_T <.. docs.usp_PERSIST_RepoObject_ColumnList_T
docs.RepoObject_ColumnList_T <.. docs.RepoObject_Plantuml_Entity
docs.RepoObject_ColumnList_T <.. docs.RepoObject_Adoc
docs.RepoObject_IndexList <.. docs.RepoObject_IndexList_T
docs.RepoObject_IndexList <.. docs.usp_PERSIST_RepoObject_IndexList_T
docs.RepoObject_IndexList_T <.. docs.usp_PERSIST_RepoObject_IndexList_T
docs.RepoObject_IndexList_T <.. docs.RepoObject_Plantuml_Entity
docs.RepoObject_IndexList_T <.. docs.RepoObject_Adoc
docs.RepoObject_MeasureDescriptionList <.. docs.RepoObject_Adoc
docs.RepoObject_MeasureList <.. docs.RepoObject_Plantuml_Entity
docs.RepoObject_MeasureList <.. docs.RepoObject_Adoc
docs.RepoObject_OutputFilter <.. docs.usp_PERSIST_RepoObject_OutputFilter_T
docs.RepoObject_OutputFilter <.. docs.RepoObject_OutputFilter_T
docs.RepoObject_OutputFilter_T <.. docs.RepoObject_OutputFilter_T_gross
docs.RepoObject_OutputFilter_T <.. docs.usp_AntoraExport_ObjectPartialsContent
docs.RepoObject_OutputFilter_T <.. docs.RepoObject_AntoraXrefCulturesList
docs.RepoObject_OutputFilter_T <.. docs.usp_PERSIST_RepoObject_OutputFilter_T
docs.RepoObject_OutputFilter_T <.. docs.Unit_1_union
docs.RepoObject_OutputFilter_T <.. docs.Schema_SsasRelationList
docs.RepoObject_OutputFilter_T <.. docs.Schema_puml
docs.RepoObject_OutputFilter_T <.. docs.RepoObject_Plantuml_ColRefList_1_1
docs.RepoObject_OutputFilter_T <.. docs.AntoraNavListPage_by_schema
docs.RepoObject_OutputFilter_T <.. docs.IndexSemanticgroupPatterndatatype
docs.RepoObject_OutputFilter_T <.. docs.AntoraNavListPage_by_type
docs.RepoObject_OutputFilter_T <.. docs.RepoObject_IndexList
docs.RepoObject_OutputFilter_T <.. docs.RepoObject_Plantuml
docs.RepoObject_OutputFilter_T <.. docs.RepoObject_Plantuml_Entity
docs.RepoObject_OutputFilter_T <.. docs.RepoObject_ColumnList
docs.RepoObject_OutputFilter_T <.. docs.AntoraNavListRepoObject_by_schema_type
docs.RepoObject_OutputFilter_T <.. docs.AntoraNavListRepoObject_by_schema
docs.RepoObject_OutputFilter_T <.. docs.AntoraNavListRepoObject_by_type
docs.RepoObject_OutputFilter_T <.. docs.usp_AntoraExport_ObjectPage
docs.RepoObject_OutputFilter_T_gross <.. docs.RepoObject_MeasureDescriptionList
docs.RepoObject_OutputFilter_T_gross <.. docs.RepoObject_MeasureList
docs.RepoObject_OutputFilter_T_gross <.. docs.RepoObject_Adoc
docs.RepoObject_Plantuml <.. docs.usp_PERSIST_RepoObject_Plantuml_T
docs.RepoObject_Plantuml <.. docs.RepoObject_Plantuml_T
docs.RepoObject_Plantuml_ColRefList_1_1 <.. docs.RepoObject_Plantuml
docs.RepoObject_Plantuml_Entity <.. docs.RepoObject_Plantuml_Entity_T
docs.RepoObject_Plantuml_Entity <.. docs.usp_PERSIST_RepoObject_Plantuml_Entity_T
docs.RepoObject_Plantuml_Entity_T <.. docs.RepoObject_Adoc
docs.RepoObject_Plantuml_Entity_T <.. docs.usp_PERSIST_RepoObject_Plantuml_Entity_T
docs.RepoObject_Plantuml_Entity_T <.. docs.ftv_RepoObject_Reference_PlantUml_EntityRefList
docs.RepoObject_Plantuml_Entity_T <.. docs.RepoObject_PlantUml_PumlEntityFkList
docs.RepoObject_Plantuml_Entity_T <.. docs.ObjectRefCyclic_EntityList
docs.RepoObject_Plantuml_Entity_T <.. docs.Schema_EntityList
docs.RepoObject_PlantUml_FkRefList <.. docs.RepoObject_Plantuml
docs.RepoObject_Plantuml_ObjectRefList_0_30 <.. docs.RepoObject_Plantuml
docs.RepoObject_Plantuml_ObjectRefList_1_1 <.. docs.RepoObject_Plantuml
docs.RepoObject_Plantuml_ObjectRefList_30_0 <.. docs.RepoObject_Plantuml
docs.RepoObject_PlantUml_PumlEntityFkList <.. docs.RepoObject_Plantuml
docs.RepoObject_Plantuml_T <.. docs.RepoObject_Adoc
docs.RepoObject_Plantuml_T <.. docs.usp_PERSIST_RepoObject_Plantuml_T
docs.Schema_EntityList <.. docs.Schema_puml
docs.Schema_puml <.. docs.AntoraNavListPage_by_schema
docs.Schema_PumlPartial_FkRefList <.. docs.Schema_puml
docs.Schema_SsasRelationList <.. docs.Schema_puml
docs.Unit_1_union <.. docs.Unit_2
docs.Unit_2 <.. docs.Unit_3
docs.Unit_3 <.. dmdocs.unit
docs.usp_AntoraExport_ObjectNavigation <.. docs.usp_AntoraExport
docs.usp_AntoraExport_ObjectPage <.. docs.usp_AntoraExport
docs.usp_AntoraExport_ObjectPartialsContent <.. docs.usp_AntoraExport
docs.usp_AntoraExport_ObjectPuml <.. docs.usp_AntoraExport
docs.usp_PERSIST_RepoObject_Adoc_T <.. docs.usp_AntoraExport_ObjectPartialsContent
docs.usp_PERSIST_RepoObject_ColumnList_T <.. docs.usp_AntoraExport_ObjectPartialsContent
docs.usp_PERSIST_RepoObject_IndexList_T <.. docs.usp_AntoraExport_ObjectPartialsContent
docs.usp_PERSIST_RepoObject_OutputFilter_T <.. docs.usp_AntoraExport
docs.usp_PERSIST_RepoObject_Plantuml_Entity_T <.. docs.usp_AntoraExport_ObjectPuml
docs.usp_PERSIST_RepoObject_Plantuml_T <.. docs.usp_AntoraExport_ObjectPuml
property.ExtendedProperty_Repo2Sys_level2_RepoObjectColumn <.. property.ExtendedProperty_Repo2Sys_level2_Union
property.ExtendedProperty_Repo2Sys_level2_Union <.. property.usp_sync_ExtendedProperties_Repo2Sys_InsertUpdate
property.ExtendedProperty_Repo2Sys_level2_Union <.. property.usp_sync_ExtendedProperties_Repo2Sys_Delete
property.fs_get_RepoObjectColumnProperty_nvarchar <.. repo.RepoObjectColumn_gross
property.PropertyName_RepoObjectColumn <.. property.usp_PERSIST_PropertyName_RepoObjectColumn_T
property.PropertyName_RepoObjectColumn <.. property.PropertyName_RepoObjectColumn_T
property.PropertyName_RepoObjectColumn_T <.. property.RepoObjectColumnProperty_InheritanceType_InheritanceDefinition
property.PropertyName_RepoObjectColumn_T <.. property.usp_PERSIST_PropertyName_RepoObjectColumn_T
property.RepoObjectColumnProperty <.. property.RepoObjectColumnProperty_ForUpdate
property.RepoObjectColumnProperty <.. property.usp_RepoObjectColumnProperty_set
property.RepoObjectColumnProperty <.. property.fs_get_RepoObjectColumnProperty_nvarchar
property.RepoObjectColumnProperty <.. property.RepoObjectColumnProperty_InheritanceType_InheritanceDefinition
property.RepoObjectColumnProperty <.. property.RepoObjectColumnProperty_sys_repo
property.RepoObjectColumnProperty <.. property.usp_RepoObjectColumn_Inheritance
property.RepoObjectColumnProperty <.. property.PropertyName_RepoObjectColumn
property.RepoObjectColumnProperty <.. property.usp_sync_ExtendedProperties_Sys2Repo_InsertUpdate
property.RepoObjectColumnProperty <.. property.ExtendedProperty_Repo2Sys_level2_RepoObjectColumn
property.RepoObjectColumnProperty_external_tgt <.. property.RepoObjectColumnProperty
property.RepoObjectColumnProperty_external_tgt <.. property.usp_PERSIST_RepoObjectColumnProperty_external_tgt
property.RepoObjectColumnProperty_InheritanceType_InheritanceDefinition <.. property.RepoObjectColumnProperty_InheritanceType_resulting_InheritanceDefinition
property.RepoObjectColumnProperty_InheritanceType_resulting_InheritanceDefinition <.. property.usp_RepoObjectColumn_Inheritance
property.RepoObjectColumnProperty_sys_repo <.. property.usp_sync_ExtendedProperties_Sys2Repo_InsertUpdate
property.RepoObjectProperty_Collect_source_ROGross <.. property.usp_RepoObjectProperty_collect
property.usp_external_property_import <.. repo.usp_main
property.usp_PERSIST_PropertyName_RepoObjectColumn_T <.. property.usp_RepoObjectColumn_Inheritance
property.usp_PERSIST_RepoObjectColumnProperty_external_tgt <.. property.usp_external_RepoObjectProperty
property.usp_PERSIST_RepoObjectColumnProperty_external_tgt <.. property.usp_external_property_import
property.usp_RepoObject_Inheritance <.. repo.usp_main
property.usp_RepoObjectColumn_Inheritance <.. repo.usp_main
property.usp_RepoObjectProperty_collect <.. property.usp_RepoObject_Inheritance
property.usp_RepoObjectProperty_collect <.. repo.usp_main
reference.additional_Reference_guid <.. reference.RepoObjectColumn_reference_additional
reference.additional_Reference_guid <.. reference.RepoObject_reference_additional
reference.additional_Reference_guid <.. reference.RepoObjectColumn_reference_additional_internal
reference.additional_Reference_guid <.. reference.RepoObject_reference_additional_internal
reference.ftv_RepoObject_ReferenceTree <.. reference.RepoObject_ReferenceTree_0_30
reference.ftv_RepoObject_ReferenceTree <.. reference.RepoObject_ReferenceTree_30_0
reference.ftv_RepoObject_ReferenceTree_referenced <.. reference.RepoObject_ReferenceTree_referenced
reference.ftv_RepoObject_ReferenceTree_referenced <.. reference.RepoObject_ReferenceTree_referenced_30_0
reference.ftv_RepoObject_ReferenceTree_referencing <.. reference.RepoObject_ReferenceTree_referencing
reference.ftv_RepoObject_ReferenceTree_referencing <.. reference.RepoObject_ReferenceTree_referencing_0_30
reference.ftv_RepoObjectColumn_ReferenceTree <.. reference.RepoObjectColumn_ReferenceTree
reference.Persistence <.. workflow.ProcedureDependency_PersistenceDependency_src
reference.Persistence <.. workflow.ProcedureDependency_input_PersistenceDependency_S
reference.Persistence <.. reference.Persistence_bidirectional
reference.ReferenceTree_cyclic_ref_PersistenceUsp <.. reference.ReferenceTree_cyclic_union
reference.ReferenceTree_cyclic_union <.. docs.ObjectRefCyclic_EntityList
reference.ReferenceTree_cyclic_union <.. docs.ObjectRefCyclic_ObjectRefList
reference.RepoObject_reference <.. reference.RepoObject_reference_T
reference.RepoObject_reference <.. reference.usp_PERSIST_RepoObject_reference_T
reference.RepoObject_reference_additional <.. reference.RepoObject_reference_union
reference.RepoObject_reference_persistence_target_as_source <.. reference.RepoObject_reference_union
reference.RepoObject_reference_persistence_target_as_source <.. reference.RepoObject_reference
reference.RepoObject_reference_persistence_target_as_source <.. repo.usp_main
reference.RepoObject_reference_persistence_target_as_source_explicit <.. reference.RepoObject_reference_union
reference.RepoObject_reference_persistence_target_as_source_explicit <.. reference.RepoObject_reference
reference.RepoObject_reference_SqlExpressionDependencies <.. reference.RepoObject_reference_union
reference.RepoObject_reference_SqlExpressionDependencies <.. reference.RepoObject_reference_persistence_target_as_source_explicit
reference.RepoObject_reference_SqlExpressionDependencies <.. reference.RepoObject_reference_persistence_target_as_source
reference.RepoObject_reference_T <.. reference.RepoObjectColumn_reference_additional_internal
reference.RepoObject_reference_T <.. reference.RepoObjectColumn_reference_additional
reference.RepoObject_reference_T <.. docs.RepoObject_Plantuml_ObjectRefList_1_1
reference.RepoObject_reference_T <.. reference.RepoObject_reference_T_bidirectional
reference.RepoObject_reference_T <.. reference.ReferenceTree_cyclic_ref_PersistenceUsp
reference.RepoObject_reference_T <.. repo.RepoObject_wo_referencing
reference.RepoObject_reference_T <.. reference.RepoObjectColumn_reference_QueryPlan
reference.RepoObject_reference_T <.. reference.RepoObjectColumn_reference_BySamePredecessors
reference.RepoObject_reference_T <.. repo.usp_main
reference.RepoObject_reference_T <.. reference.RepoObject_ReferencedReferencing
reference.RepoObject_reference_T <.. docs.RepoObject_Plantuml_ObjectRefList_0_30
reference.RepoObject_reference_T <.. docs.RepoObject_Plantuml_ObjectRefList_30_0
reference.RepoObject_reference_T <.. reference.RepoObjectColumn_reference_virtual
reference.RepoObject_reference_T <.. reference.usp_PERSIST_RepoObject_reference_T
reference.RepoObject_reference_T <.. reference.RepoObjectColumn_reference_SqlExpressionDependencies
reference.RepoObject_reference_T <.. repo.IndexReferencedReferencing
reference.RepoObject_reference_T <.. reference.RepoObjectColumn_reference_FirstResultSet
reference.RepoObject_reference_union <.. reference.RepoObject_reference
reference.RepoObject_ReferencedList <.. repo.RepoObject_gross2
reference.RepoObject_ReferencedList <.. repo.RepoObject_sat2
reference.RepoObject_ReferencedReferencing <.. reference.usp_RepoObject_ReferenceTree_insert
reference.RepoObject_ReferencedReferencing <.. reference.ftv_RepoObject_ReferenceTree_referencing
reference.RepoObject_ReferencedReferencing <.. reference.ftv_RepoObject_ReferenceTree_via_fullname
reference.RepoObject_ReferencedReferencing <.. repo.RepoObject_gross
reference.RepoObject_ReferencedReferencing <.. reference.ftv_RepoObject_ReferenceTree_referenced
reference.RepoObject_ReferencedReferencing <.. reference.RepoObject_ReferencingList
reference.RepoObject_ReferencedReferencing <.. reference.RepoObject_ReferencedList
reference.RepoObject_ReferencedReferencing <.. reference.ftv_RepoObject_ReferenceTree
reference.RepoObject_ReferenceTree_0_30 <.. reference.RepoObject_ReferenceTree_0_30_T
reference.RepoObject_ReferenceTree_0_30 <.. reference.usp_PERSIST_RepoObject_ReferenceTree_0_30_T
reference.RepoObject_ReferenceTree_0_30_T <.. reference.usp_PERSIST_RepoObject_ReferenceTree_0_30_T
reference.RepoObject_ReferenceTree_30_0 <.. reference.usp_PERSIST_RepoObject_ReferenceTree_30_0_T
reference.RepoObject_ReferenceTree_30_0 <.. reference.RepoObject_ReferenceTree_30_0_T
reference.RepoObject_ReferenceTree_30_0_T <.. reference.usp_PERSIST_RepoObject_ReferenceTree_30_0_T
reference.RepoObject_ReferencingList <.. repo.RepoObject_gross2
reference.RepoObject_ReferencingList <.. repo.RepoObject_sat2
reference.RepoObjectColumn_reference <.. reference.RepoObjectColumn_reference_T
reference.RepoObjectColumn_reference <.. reference.usp_PERSIST_RepoObjectColumn_reference_T
reference.RepoObjectColumn_reference_additional <.. reference.RepoObjectColumn_reference_union
reference.RepoObjectColumn_reference_FirstResultSet <.. reference.RepoObjectColumn_reference_BySamePredecessors
reference.RepoObjectColumn_reference_Persistence <.. reference.RepoObjectColumn_reference_union
reference.RepoObjectColumn_reference_QueryPlan <.. reference.SysObjectColumn_QueryPlanExpression
reference.RepoObjectColumn_reference_SqlExpressionDependencies <.. reference.RepoObjectColumn_reference_union
reference.RepoObjectColumn_reference_SqlModules <.. reference.RepoObjectColumn_reference_union
reference.RepoObjectColumn_reference_T <.. docs.RepoObject_Plantuml_ColRefList_1_1
reference.RepoObjectColumn_reference_T <.. reference.usp_PERSIST_RepoObjectColumn_reference_T
reference.RepoObjectColumn_reference_T <.. reference.RepoObjectColumn_ReferencedReferencing
reference.RepoObjectColumn_reference_T <.. reference.RepoObjectColumn_RelationScript
reference.RepoObjectColumn_reference_T <.. repo.RepoObjectColumn_MissingSource_TypeV
reference.RepoObjectColumn_reference_T <.. repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing
reference.RepoObjectColumn_reference_union <.. reference.RepoObjectColumn_reference
reference.RepoObjectColumn_reference_virtual <.. reference.RepoObjectColumn_reference_union
reference.RepoObjectColumn_ReferencedList <.. repo.RepoObjectColumn_gross2
reference.RepoObjectColumn_ReferencedReferencing <.. reference.RepoObjectColumn_ReferencingList
reference.RepoObjectColumn_ReferencedReferencing <.. reference.ftv_RepoObjectColumn_ReferenceTree
reference.RepoObjectColumn_ReferencedReferencing <.. reference.RepoObjectColumn_ReferencedList
reference.RepoObjectColumn_ReferencedReferencing <.. reference.ftv_RepoObject_DbmlColumnRelation
reference.RepoObjectColumn_ReferenceTree <.. reference.ftv_RepoObject_ColumReferenceRepoObject
reference.RepoObjectColumn_ReferencingList <.. repo.RepoObjectColumn_gross2
reference.RepoObjectColumn_RelationScript <.. reference.ftv_RepoObject_ColumReferenceRepoObject
reference.SysObjectColumn_QueryPlanExpression <.. reference.usp_RepoObjectSource_QueryPlan
reference.usp_PERSIST_RepoObject_reference_T <.. repo.usp_main
reference.usp_PERSIST_RepoObject_ReferenceTree_0_30_T <.. reference.usp_RepoObject_ReferenceTree
reference.usp_PERSIST_RepoObject_ReferenceTree_30_0_T <.. reference.usp_RepoObject_ReferenceTree
reference.usp_PERSIST_RepoObjectColumn_reference_T <.. repo.usp_main
reference.usp_RepoObject_ReferenceTree_insert <.. repo.usp_main
reference.usp_RepoObject_update_SysObjectQueryPlan <.. repo.usp_main
reference.usp_RepoObjectSource_FirstResultSet <.. repo.usp_main
reference.usp_RepoObjectSource_QueryPlan <.. repo.usp_main
reference.usp_update_Referencing_Count <.. repo.usp_main
repo.ForeignKey_gross <.. docs.RepoObject_IndexList
repo.ForeignKey_Indexes <.. repo.ForeignKey_Indexes_union
repo.ForeignKey_Indexes <.. repo.usp_Index_ForeignKey
repo.ForeignKey_Indexes_union <.. repo.usp_PERSIST_ForeignKey_Indexes_union_T
repo.ForeignKey_Indexes_union <.. repo.ForeignKey_Indexes_union_T
repo.ForeignKey_Indexes_union_T <.. repo.usp_Index_finish
repo.ForeignKey_Indexes_union_T <.. repo.usp_PERSIST_ForeignKey_Indexes_union_T
repo.ForeignKey_Indexes_union_T <.. docs.Schema_PumlPartial_FkRefList
repo.ForeignKey_Indexes_union_T <.. docs.ForeignKey_RelationScript
repo.ForeignKey_Indexes_union_T <.. repo.ForeignKey_gross
repo.ForeignKey_Indexes_union_T <.. repo.RepoObject_related_FK_union
repo.ForeignKey_Indexes_union_T <.. docs.RepoObject_PlantUml_FkRefList
repo.ForeignKey_virtual_Indexes <.. repo.ForeignKey_Indexes_union
repo.Index_ColumList <.. repo.usp_PERSIST_Index_ColumList_T
repo.Index_ColumList <.. repo.Index_ColumList_T
repo.Index_ColumList_T <.. uspgenerator.GeneratorUspStep_Persistence_src
repo.Index_ColumList_T <.. repo.Index_SqlConstraint_PkUq
repo.Index_ColumList_T <.. repo.usp_PERSIST_Index_ColumList_T
repo.Index_ColumList_T <.. repo.Index_gross
repo.Index_gross <.. repo.usp_Index_finish
repo.Index_gross <.. docs.RepoObject_IndexList
repo.Index_gross <.. docs.IndexSemanticgroupPatterndatatype
repo.Index_gross <.. repo.ForeignKey_gross
repo.Index_gross <.. repo.RepoObject_SqlCreateTable
repo.Index_gross <.. repo.usp_index_inheritance
repo.Index_gross <.. repo.usp_Index_virtual_set
repo.Index_gross <.. repo.ForeignKey_Indexes
repo.Index_gross <.. repo.ForeignKey_virtual_Indexes
repo.Index_IndexPattern <.. repo.usp_Index_Settings
repo.Index_referencing_IndexPatternColumnGuid <.. repo.IndexReferencedReferencing_HasFullColumnsInReferencing
repo.Index_SqlConstraint_PkUq <.. repo.RepoObject_SqlCreateTable
repo.Index_union <.. repo.IndexReferencedReferencing
repo.Index_union <.. repo.Index_SqlConstraint_PkUq
repo.Index_union <.. repo.Index_gross
repo.Index_union <.. repo.usp_Index_finish
repo.Index_union <.. repo.Index_Settings_ForUpdate
repo.Index_unique_IndexPatternColumnGuid <.. repo.Index_union
repo.Index_virtual_ForUpdate <.. repo.usp_index_inheritance
repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing <.. repo.usp_PERSIST_IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T
repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing <.. repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T
repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T <.. repo.IndexColumn_virtual_referenced_setpoint
repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T <.. repo.Index_referencing_IndexPatternColumnGuid
repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T <.. repo.IndexReferencedReferencing_HasFullColumnsInReferencing
repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T <.. repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_check
repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T <.. repo.usp_PERSIST_IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T
repo.IndexColumn_ssas_gross <.. repo.IndexColumn_union
repo.IndexColumn_union <.. repo.usp_PERSIST_IndexColumn_union_T
repo.IndexColumn_union <.. repo.IndexColumn_union_T
repo.IndexColumn_union_T <.. repo.Index_ColumList
repo.IndexColumn_union_T <.. repo.Index_IndexPattern
repo.IndexColumn_union_T <.. repo.usp_PERSIST_IndexColumn_union_T
repo.IndexColumn_union_T <.. repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing
repo.IndexColumn_union_T <.. repo.RepoObjectColumn_gross2
repo.IndexColumn_virtual_gross <.. repo.IndexColumn_union
repo.IndexColumn_virtual_referenced_setpoint <.. repo.check_IndexColumn_virtual_referenced_setpoint
repo.IndexColumn_virtual_referenced_setpoint <.. repo.usp_index_inheritance
repo.IndexReferencedReferencing <.. repo.IndexReferencedReferencing_HasFullColumnsInReferencing
repo.IndexReferencedReferencing_HasFullColumnsInReferencing <.. repo.usp_index_inheritance
repo.RepoObject_ColumnList <.. repo.RepoObject_SqlCreateTable
repo.RepoObject_ColumnList <.. repo.RepoObject_gross2
repo.RepoObject_ColumnList <.. repo.RepoObject_sat2
repo.RepoObject_gross <.. repo.RepoObject_SqlCreateTable
repo.RepoObject_gross <.. uspgenerator.GeneratorUspStep_Persistence_IsInactive_setpoint
repo.RepoObject_gross <.. uspgenerator.GeneratorUspStep_Persistence_src
repo.RepoObject_gross <.. repo.Index_gross
repo.RepoObject_gross <.. reference.usp_RepoObjectSource_QueryPlan
repo.RepoObject_gross <.. reference.usp_RepoObjectSource_FirstResultSet
repo.RepoObject_gross <.. reference.usp_RepoObject_update_SysObjectQueryPlan
repo.RepoObject_gross <.. uspgenerator.usp_GeneratorUsp_insert_update_persistence
repo.RepoObject_gross <.. docs.RepoObject_Adoc
repo.RepoObject_gross <.. docs.RepoObject_OutputFilter
repo.RepoObject_gross <.. docs.RepoObject_Plantuml
repo.RepoObject_gross <.. repo.Index_virtual_ForUpdate
repo.RepoObject_gross <.. workflow.WorkflowStep_src
repo.RepoObject_gross <.. repo.RepoObject_gross2
repo.RepoObject_gross <.. docs.Unit_1_union
repo.RepoObject_gross <.. repo.RepoObject_sat2
repo.RepoObject_gross <.. reference.RepoObject_ReferenceTree_referenced
repo.RepoObject_gross <.. reference.RepoObject_ReferenceTree_referencing
repo.RepoObject_gross <.. property.RepoObjectProperty_Collect_source_ROGross
repo.RepoObject_gross <.. reference.RepoObject_ReferenceTree_referenced_30_0
repo.RepoObject_gross <.. reference.RepoObject_ReferenceTree_referencing_0_30
repo.RepoObject_gross <.. reference.RepoObject_ReferenceTree_0_30
repo.RepoObject_gross <.. reference.RepoObject_ReferenceTree_30_0
repo.RepoObject_gross <.. reference.Persistence
repo.RepoObject_gross2 <.. uspgenerator.GeneratorUspStep_Persistence_src
repo.RepoObject_persistence_NoCompareButUpdate <.. repo.usp_sync_guid_RepoObjectColumn
repo.RepoObject_persistence_NoCompareNoUpdate <.. repo.usp_sync_guid_RepoObjectColumn
repo.RepoObject_persistence_source_Ignore <.. repo.usp_sync_guid_RepoObjectColumn
repo.RepoObject_persistence_target_Ignore <.. repo.usp_sync_guid_RepoObjectColumn
repo.RepoObject_related_FK_union <.. docs.RepoObject_PlantUml_PumlEntityFkList
repo.RepoObject_related_FK_union <.. docs.RepoObject_PlantUml_FkRefList
repo.RepoObject_sat2 <.. repo.usp_PERSIST_RepoObject_sat2_T
repo.RepoObject_sat2 <.. repo.RepoObject_sat2_T
repo.RepoObject_sat2_T <.. repo.usp_PERSIST_RepoObject_sat2_T
repo.RepoObject_sat2_T <.. property.RepoObjectProperty_Collect_source_ROGross
repo.RepoObject_sat2_T <.. docs.RepoObject_Adoc
repo.RepoObject_SqlCreateTable <.. reference.ftv_RepoObject_ColumReferenceRepoObject
repo.RepoObjectColumn <.. reference.RepoObjectColumn_reference_Persistence
repo.RepoObjectColumn <.. repo.RepoObject_persistence_column
repo.RepoObjectColumn <.. repo.IndexColumn_virtual_gross
repo.RepoObjectColumn <.. property.RepoObjectColumnProperty_sys_repo
repo.RepoObjectColumn <.. repo.SysColumn_RepoObjectColumn_via_guid
repo.RepoObjectColumn <.. repo.SysColumn_RepoObjectColumn_via_name
repo.RepoObjectColumn <.. repo.RepoObjectColumn_gross
repo.RepoObjectColumn <.. repo.RepoObject_SqlCreateTable
repo.RepoObjectColumn <.. repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing
repo.RepoObjectColumn <.. repo.RepoObjectColumn_MissingSource_TypeV
repo.RepoObjectColumn <.. repo.check_IndexColumn_virtual_referenced_setpoint
repo.RepoObjectColumn <.. reference.usp_RepoObjectSource_QueryPlan
repo.RepoObjectColumn <.. reference.usp_update_Referencing_Count
repo.RepoObjectColumn <.. repo.usp_Index_virtual_set
repo.RepoObjectColumn <.. repo.usp_sync_guid_RepoObjectColumn
repo.RepoObjectColumn <.. sqlparse.RepoObject_SqlModules_71_reference_ExpliciteTableAlias
repo.RepoObjectColumn <.. sqlparse.RepoObject_SqlModules_72_reference_NoTableAlias
repo.RepoObjectColumn <.. reference.RepoObjectColumn_reference_SqlModules
repo.RepoObjectColumn <.. property.ExtendedProperty_Repo2Sys_level2_RepoObjectColumn
repo.RepoObjectColumn <.. property.RepoObjectColumnProperty_InheritanceType_InheritanceDefinition
repo.RepoObjectColumn <.. reference.RepoObjectColumn_RelationScript
repo.RepoObjectColumn <.. reference.RepoObjectColumn_ReferenceTree
repo.RepoObjectColumn <.. repo.RepoObjectColumn_RequiredRepoObjectColumnMerge
repo.RepoObjectColumn <.. property.usp_RepoObjectColumnProperty_set
repo.RepoObjectColumn <.. repo.usp_update_Referencing_Count
repo.RepoObjectColumn <.. reference.usp_RepoObjectColumnSource_virtual_set
repo.RepoObjectColumn <.. repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_check
repo.RepoObjectColumn <.. reference.additional_Reference_guid
repo.RepoObjectColumn <.. repo.IndexColumn_ssas_gross
repo.RepoObjectColumn <.. repo.RepoObjectColumn_gross2
repo.RepoObjectColumn <.. property.RepoObjectColumnProperty_external_tgt
repo.RepoObjectColumn <.. repo.RepoObject_persistence_NoCompareButUpdate
repo.RepoObjectColumn <.. repo.RepoObject_persistence_NoCompareNoUpdate
repo.RepoObjectColumn <.. repo.RepoObject_persistence_target_Ignore
repo.RepoObjectColumn <.. repo.RepoObject_persistence_source_Ignore
repo.RepoObjectColumn_gross <.. reference.RepoObjectColumn_reference_FirstResultSet
repo.RepoObjectColumn_gross <.. reference.RepoObjectColumn_reference_QueryPlan
repo.RepoObjectColumn_gross <.. repo.usp_sync_guid_RepoObjectColumn
repo.RepoObjectColumn_gross <.. ssas.RepoObjectColumn_translation
repo.RepoObjectColumn_gross <.. repo.RepoObjectColumn_gross2
repo.RepoObjectColumn_gross <.. docs.Unit_1_union
repo.RepoObjectColumn_gross <.. graph.RepoObjectColumn_S
repo.RepoObjectColumn_gross <.. property.RepoObjectColumnProperty_ForUpdate
repo.RepoObjectColumn_gross <.. reference.RepoObjectColumn_reference_virtual
repo.RepoObjectColumn_gross <.. reference.usp_RepoObjectColumnSource_virtual_set
repo.RepoObjectColumn_gross2 <.. uspgenerator.usp_GeneratorUsp_insert_update_persistence
repo.RepoObjectColumn_gross2 <.. repo.RepoObject_ColumnList
repo.RepoObjectColumn_gross2 <.. docs.RepoObject_ColumnList
repo.RepoObjectColumn_RequiredRepoObjectColumnMerge <.. repo.usp_sync_guid_RepoObjectColumn
repo.RepoObjectColumn_SSAS_tgt <.. repo.RepoObjectColumn
repo.RepoObjectColumn_SSAS_tgt <.. repo.usp_PERSIST_RepoObjectColumn_SSAS_tgt
repo.SysColumn_RepoObjectColumn_via_guid <.. repo.usp_sync_guid_RepoObjectColumn
repo.SysColumn_RepoObjectColumn_via_name <.. repo.usp_sync_guid_RepoObjectColumn
repo.SysColumn_RepoObjectColumn_via_name <.. repo_sys.sql_expression_dependencies
repo.SysColumn_RepoObjectColumn_via_name <.. repo_sys.IndexColumn_unique
repo.usp_Index_finish <.. repo.usp_Index_ForeignKey
repo.usp_Index_finish <.. repo.usp_index_inheritance
repo.usp_Index_ForeignKey <.. repo.usp_main
repo.usp_index_inheritance <.. repo.usp_main
repo.usp_Index_Settings <.. repo.usp_Index_finish
repo.usp_Index_virtual_set <.. repo.usp_Index_ForeignKey
repo.usp_PERSIST_ForeignKey_Indexes_union_T <.. repo.usp_Index_ForeignKey
repo.usp_PERSIST_Index_ColumList_T <.. repo.usp_Index_finish
repo.usp_PERSIST_IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T <.. repo.usp_index_inheritance
repo.usp_PERSIST_IndexColumn_union_T <.. repo.usp_Index_finish
repo.usp_PERSIST_RepoObject_sat2_T <.. repo.usp_main
repo.usp_PERSIST_RepoObjectColumn_SSAS_tgt <.. repo.usp_sync_guid_ssas
repo.usp_sync_guid <.. repo.usp_persistence_set
repo.usp_sync_guid <.. repo.usp_main
repo.usp_sync_guid_RepoObjectColumn <.. repo.usp_sync_guid
repo.usp_sync_guid_ssas <.. repo.usp_main
repo_sys.IndexColumn_unique <.. repo.IndexColumn_union
repo_sys.IndexColumn_unique <.. repo.Index_unique_IndexPatternColumnGuid
repo_sys.sql_expression_dependencies <.. reference.RepoObject_reference_SqlExpressionDependencies
repo_sys.sql_expression_dependencies <.. reference.RepoObjectColumn_reference_SqlExpressionDependencies
sqlparse.RepoObject_SqlModules_71_reference_ExpliciteTableAlias <.. sqlparse.RepoObject_SqlModules_79_reference_union
sqlparse.RepoObject_SqlModules_72_reference_NoTableAlias <.. sqlparse.RepoObject_SqlModules_79_reference_union
sqlparse.RepoObject_SqlModules_79_reference_union <.. reference.RepoObjectColumn_reference_SqlModules
ssas.RepoObjectColumn_translation <.. ssas.RepoObjectColumn_translation_T
ssas.RepoObjectColumn_translation <.. ssas.usp_PERSIST_RepoObjectColumn_translation_T
ssas.RepoObjectColumn_translation_displayfolder_union <.. docs.RepoObject_ColumnList
ssas.RepoObjectColumn_translation_T <.. ssas.RepoObjectColumn_translation_displayfolder_union
ssas.RepoObjectColumn_translation_T <.. docs.RepoObject_Plantuml_ColRefList_1_1
ssas.RepoObjectColumn_translation_T <.. ssas.usp_PERSIST_RepoObjectColumn_translation_T
ssas.usp_PERSIST_RepoObjectColumn_translation_T <.. repo.usp_main
uspgenerator.GeneratorUspStep_Persistence_IsInactive_setpoint <.. uspgenerator.usp_GeneratorUsp_insert_update_persistence
uspgenerator.GeneratorUspStep_Persistence_src <.. uspgenerator.usp_GeneratorUsp_insert_update_persistence
uspgenerator.usp_GeneratorUsp_insert_update_persistence <.. repo.usp_main
workflow.Biml_Package <.. workflow.Biml_Project
workflow.Biml_PrecedenceConstraints <.. workflow.Biml_Task
workflow.Biml_Task <.. workflow.Biml_Package
workflow.ProcedureDependency <.. workflow.Workflow_ProcedureDependency
workflow.ProcedureDependency <.. workflow.Workflow_ProcedureDependency_all
workflow.ProcedureDependency <.. workflow.ProcedureDependency_input_PersistenceDependency
workflow.ProcedureDependency <.. workflow.ProcedureDependency_gross
workflow.ProcedureDependency_PersistenceDependency_src <.. workflow.ProcedureDependency_PersistenceDependency_tgt
workflow.ProcedureDependency_PersistenceDependency_src <.. workflow.usp_PERSIST_ProcedureDependency_PersistenceDependency_tgt
workflow.ProcedureDependency_PersistenceDependency_tgt <.. workflow.ProcedureDependency
workflow.ProcedureDependency_PersistenceDependency_tgt <.. workflow.usp_PERSIST_ProcedureDependency_PersistenceDependency_tgt
workflow.usp_PERSIST_ProcedureDependency_PersistenceDependency_tgt <.. workflow.usp_workflow
workflow.usp_PERSIST_Workflow_ProcedureDependency_T <.. workflow.usp_workflow
workflow.usp_PERSIST_WorkflowStep <.. workflow.usp_workflow
workflow.Workflow_ProcedureDependency <.. workflow.Workflow_ProcedureDependency_T
workflow.Workflow_ProcedureDependency <.. workflow.usp_PERSIST_Workflow_ProcedureDependency_T
workflow.Workflow_ProcedureDependency_all <.. workflow.Workflow_ProcedureDependency_wo_redundant
workflow.Workflow_ProcedureDependency_T <.. workflow.usp_workflow
workflow.Workflow_ProcedureDependency_T <.. workflow.Workflow_ProcedureDependency_T_bidirectional
workflow.Workflow_ProcedureDependency_T <.. workflow.Workflow_ProcedureDependency_T_active
workflow.Workflow_ProcedureDependency_T <.. workflow.usp_PERSIST_Workflow_ProcedureDependency_T
workflow.Workflow_ProcedureDependency_T_active <.. workflow.Workflow_ProcedureDependency_T_NotInSortorder
workflow.Workflow_ProcedureDependency_T_active <.. workflow.Workflow_ProcedureDependency_T_redundant
workflow.Workflow_ProcedureDependency_T_active <.. workflow.Workflow_ProcedureDependency_T_TaskName
workflow.Workflow_ProcedureDependency_T_bidirectional <.. workflow.usp_workflow
workflow.Workflow_ProcedureDependency_T_bidirectional <.. workflow.Workflow_ProcedureDependency_T_bidirectional_T
workflow.Workflow_ProcedureDependency_T_NotInSortorder <.. workflow.usp_workflow
workflow.Workflow_ProcedureDependency_T_NotInSortorder <.. workflow.Workflow_ProcedureDependency_T_NotInSortorder_check
workflow.Workflow_ProcedureDependency_T_NotInSortorder_check <.. workflow.usp_workflow
workflow.Workflow_ProcedureDependency_T_redundant <.. workflow.Workflow_ProcedureDependency_wo_redundant
workflow.Workflow_ProcedureDependency_T_redundant <.. workflow.usp_workflow
workflow.Workflow_ProcedureDependency_T_TaskName <.. workflow.Biml_PrecedenceConstraints
workflow.WorkflowStep <.. workflow.usp_PERSIST_WorkflowStep
workflow.WorkflowStep <.. workflow.WorkflowStep_active
workflow.WorkflowStep <.. workflow.WorkflowStep_ForUpdate
workflow.WorkflowStep_active <.. workflow.Workflow_ProcedureDependency_T_active
workflow.WorkflowStep_active <.. workflow.Biml_Task
workflow.WorkflowStep_active <.. workflow.Workflow_ProcedureDependency
workflow.WorkflowStep_active <.. workflow.usp_workflow
workflow.WorkflowStep_active <.. workflow.Workflow_ProcedureDependency_all
workflow.WorkflowStep_src <.. workflow.WorkflowStep
workflow.WorkflowStep_src <.. workflow.usp_PERSIST_WorkflowStep

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_0_30_objectref[]

=== PlantUML 1 1 ColumnRef

// tag::puml_entity_1_1_colref[]
[plantuml, entity_1_1_colref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:repo.repoobject_ssas_tgt.adoc[]" as repo.RepoObject_SSAS_tgt << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  external_AntoraComponent : (nvarchar(128))
  external_AntoraModule : (nvarchar(128))
  has_execution_plan_issue : (bit)
  has_get_referenced_issue : (bit)
  Inheritance_StringAggSeparatorSql : (nvarchar(4000))
  InheritanceDefinition : (nvarchar(4000))
  InheritanceType : (tinyint)
  is_external : (bit)
  is_repo_managed : (bit)
  is_required_ObjectMerge : (bit)
  - is_ssas : (bit)
  is_SysObject_missing : (bit)
  - modify_dt : (datetime)
  pk_index_guid : (uniqueidentifier)
  pk_IndexPatternColumnName_new : (nvarchar(4000))
  Repo_history_table_guid : (uniqueidentifier)
  Repo_temporal_type : (tinyint)
  - RepoObject_name : (nvarchar(128))
  RepoObject_Referencing_Count : (int)
  - RepoObject_schema_name : (nvarchar(128))
  - RepoObject_type : (char(2))
  SysObject_id : (int)
  SysObject_modify_date : (datetime)
  - SysObject_name : (nvarchar(128))
  - SysObject_parent_object_id : (int)
  - SysObject_schema_name : (nvarchar(128))
  SysObject_type : (char(2))
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn.adoc[]" as repo.RepoObjectColumn << U >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  Inheritance_StringAggSeparatorSql : (nvarchar(4000))
  InheritanceDefinition : (nvarchar(4000))
  InheritanceType : (tinyint)
  is_persistence_Ignore : (bit)
  is_persistence_NoCompareButUpdate : (bit)
  is_persistence_NoCompareNoUpdate : (bit)
  is_query_plan_expression : (bit)
  is_required_ColumnMerge : (bit)
  is_SysObjectColumn_missing : (bit)
  persistence_source_RepoObjectColumn_guid : (uniqueidentifier)
  Referencing_Count : (int)
  Repo_default_definition : (nvarchar(max))
  Repo_default_is_system_named : (bit)
  Repo_default_name : (nvarchar(128))
  Repo_definition : (nvarchar(max))
  - Repo_generated_always_type : (tinyint)
  Repo_graph_type : (int)
  Repo_increment_value : (sql_variant)
  - Repo_is_computed : (bit)
  - Repo_is_identity : (bit)
  Repo_is_nullable : (bit)
  Repo_is_persisted : (bit)
  Repo_seed_value : (sql_variant)
  Repo_user_type_fullname : (nvarchar(128))
  Repo_user_type_name : (nvarchar(128))
  Repo_uses_database_collation : (bit)
  - RepoObject_guid : (uniqueidentifier)
  RepoObjectColumn_column_id : (int)
  - RepoObjectColumn_name : (nvarchar(128))
  SysObjectColumn_column_id : (int)
  - SysObjectColumn_name : (nvarchar(128))
  # Column_name : (nvarchar(128))
  ~ has_different_sys_names : (bit)
  # is_RepoObjectColumn_name_uniqueidentifier : (int)
  # is_SysObjectColumn_name_uniqueidentifier : (int)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn_ssas_src.adoc[]" as repo.RepoObjectColumn_SSAS_src << V >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  - is_SysObjectColumn_missing : (int)
  - Repo_is_nullable : (bit)
  Repo_user_type_fullname : (nvarchar(500))
  Repo_user_type_name : (nvarchar(500))
  - RepoObject_guid : (uniqueidentifier)
  - RepoObjectColumn_name : (nvarchar(128))
  - SysObjectColumn_name : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn_ssas_tgt.adoc[]" as repo.RepoObjectColumn_SSAS_tgt << V >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  Inheritance_StringAggSeparatorSql : (nvarchar(4000))
  InheritanceDefinition : (nvarchar(4000))
  InheritanceType : (tinyint)
  is_persistence_Ignore : (bit)
  is_persistence_NoCompareButUpdate : (bit)
  is_persistence_NoCompareNoUpdate : (bit)
  is_query_plan_expression : (bit)
  is_required_ColumnMerge : (bit)
  is_SysObjectColumn_missing : (bit)
  persistence_source_RepoObjectColumn_guid : (uniqueidentifier)
  Referencing_Count : (int)
  Repo_default_definition : (nvarchar(max))
  Repo_default_is_system_named : (bit)
  Repo_default_name : (nvarchar(128))
  Repo_definition : (nvarchar(max))
  - Repo_generated_always_type : (tinyint)
  Repo_graph_type : (int)
  Repo_increment_value : (sql_variant)
  - Repo_is_computed : (bit)
  - Repo_is_identity : (bit)
  Repo_is_nullable : (bit)
  Repo_is_persisted : (bit)
  Repo_seed_value : (sql_variant)
  Repo_user_type_fullname : (nvarchar(128))
  Repo_user_type_name : (nvarchar(128))
  Repo_uses_database_collation : (bit)
  - RepoObject_guid : (uniqueidentifier)
  RepoObjectColumn_column_id : (int)
  - RepoObjectColumn_name : (nvarchar(128))
  SysObjectColumn_column_id : (int)
  - SysObjectColumn_name : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:repo.usp_persist_repoobjectcolumn_ssas_tgt.adoc[]" as repo.usp_PERSIST_RepoObjectColumn_SSAS_tgt << P >> {
  --
}

repo.RepoObject_SSAS_tgt <.. repo.RepoObjectColumn_SSAS_tgt
repo.RepoObjectColumn_SSAS_src <.. repo.RepoObjectColumn_SSAS_tgt
repo.RepoObjectColumn_SSAS_tgt <.. repo.RepoObjectColumn
repo.RepoObjectColumn_SSAS_tgt <.. repo.usp_PERSIST_RepoObjectColumn_SSAS_tgt
"repo.RepoObjectColumn::Inheritance_StringAggSeparatorSql" <-- "repo.RepoObjectColumn_SSAS_tgt::Inheritance_StringAggSeparatorSql"
"repo.RepoObjectColumn::InheritanceDefinition" <-- "repo.RepoObjectColumn_SSAS_tgt::InheritanceDefinition"
"repo.RepoObjectColumn::InheritanceType" <-- "repo.RepoObjectColumn_SSAS_tgt::InheritanceType"
"repo.RepoObjectColumn::is_persistence_Ignore" <-- "repo.RepoObjectColumn_SSAS_tgt::is_persistence_Ignore"
"repo.RepoObjectColumn::is_persistence_NoCompareButUpdate" <-- "repo.RepoObjectColumn_SSAS_tgt::is_persistence_NoCompareButUpdate"
"repo.RepoObjectColumn::is_persistence_NoCompareNoUpdate" <-- "repo.RepoObjectColumn_SSAS_tgt::is_persistence_NoCompareNoUpdate"
"repo.RepoObjectColumn::is_query_plan_expression" <-- "repo.RepoObjectColumn_SSAS_tgt::is_query_plan_expression"
"repo.RepoObjectColumn::is_required_ColumnMerge" <-- "repo.RepoObjectColumn_SSAS_tgt::is_required_ColumnMerge"
"repo.RepoObjectColumn::is_SysObjectColumn_missing" <-- "repo.RepoObjectColumn_SSAS_tgt::is_SysObjectColumn_missing"
"repo.RepoObjectColumn::persistence_source_RepoObjectColumn_guid" <-- "repo.RepoObjectColumn_SSAS_tgt::persistence_source_RepoObjectColumn_guid"
"repo.RepoObjectColumn::Referencing_Count" <-- "repo.RepoObjectColumn_SSAS_tgt::Referencing_Count"
"repo.RepoObjectColumn::Repo_default_definition" <-- "repo.RepoObjectColumn_SSAS_tgt::Repo_default_definition"
"repo.RepoObjectColumn::Repo_default_is_system_named" <-- "repo.RepoObjectColumn_SSAS_tgt::Repo_default_is_system_named"
"repo.RepoObjectColumn::Repo_default_name" <-- "repo.RepoObjectColumn_SSAS_tgt::Repo_default_name"
"repo.RepoObjectColumn::Repo_definition" <-- "repo.RepoObjectColumn_SSAS_tgt::Repo_definition"
"repo.RepoObjectColumn::Repo_generated_always_type" <-- "repo.RepoObjectColumn_SSAS_tgt::Repo_generated_always_type"
"repo.RepoObjectColumn::Repo_graph_type" <-- "repo.RepoObjectColumn_SSAS_tgt::Repo_graph_type"
"repo.RepoObjectColumn::Repo_increment_value" <-- "repo.RepoObjectColumn_SSAS_tgt::Repo_increment_value"
"repo.RepoObjectColumn::Repo_is_computed" <-- "repo.RepoObjectColumn_SSAS_tgt::Repo_is_computed"
"repo.RepoObjectColumn::Repo_is_identity" <-- "repo.RepoObjectColumn_SSAS_tgt::Repo_is_identity"
"repo.RepoObjectColumn::Repo_is_nullable" <-- "repo.RepoObjectColumn_SSAS_tgt::Repo_is_nullable"
"repo.RepoObjectColumn::Repo_is_persisted" <-- "repo.RepoObjectColumn_SSAS_tgt::Repo_is_persisted"
"repo.RepoObjectColumn::Repo_seed_value" <-- "repo.RepoObjectColumn_SSAS_tgt::Repo_seed_value"
"repo.RepoObjectColumn::Repo_user_type_fullname" <-- "repo.RepoObjectColumn_SSAS_tgt::Repo_user_type_fullname"
"repo.RepoObjectColumn::Repo_user_type_name" <-- "repo.RepoObjectColumn_SSAS_tgt::Repo_user_type_name"
"repo.RepoObjectColumn::Repo_uses_database_collation" <-- "repo.RepoObjectColumn_SSAS_tgt::Repo_uses_database_collation"
"repo.RepoObjectColumn::RepoObject_guid" <-- "repo.RepoObjectColumn_SSAS_tgt::RepoObject_guid"
"repo.RepoObjectColumn::RepoObjectColumn_column_id" <-- "repo.RepoObjectColumn_SSAS_tgt::RepoObjectColumn_column_id"
"repo.RepoObjectColumn::RepoObjectColumn_guid" <-- "repo.RepoObjectColumn_SSAS_tgt::RepoObjectColumn_guid"
"repo.RepoObjectColumn::RepoObjectColumn_name" <-- "repo.RepoObjectColumn_SSAS_tgt::RepoObjectColumn_name"
"repo.RepoObjectColumn::SysObjectColumn_column_id" <-- "repo.RepoObjectColumn_SSAS_tgt::SysObjectColumn_column_id"
"repo.RepoObjectColumn::SysObjectColumn_name" <-- "repo.RepoObjectColumn_SSAS_tgt::SysObjectColumn_name"
"repo.RepoObjectColumn_SSAS_src::is_SysObjectColumn_missing" <-- "repo.RepoObjectColumn_SSAS_tgt::is_SysObjectColumn_missing"
"repo.RepoObjectColumn_SSAS_src::Repo_is_nullable" <-- "repo.RepoObjectColumn_SSAS_tgt::Repo_is_nullable"
"repo.RepoObjectColumn_SSAS_src::Repo_user_type_fullname" <-- "repo.RepoObjectColumn_SSAS_tgt::Repo_user_type_fullname"
"repo.RepoObjectColumn_SSAS_src::Repo_user_type_name" <-- "repo.RepoObjectColumn_SSAS_tgt::Repo_user_type_name"
"repo.RepoObjectColumn_SSAS_src::RepoObject_guid" <-- "repo.RepoObjectColumn_SSAS_tgt::RepoObject_guid"
"repo.RepoObjectColumn_SSAS_src::RepoObjectColumn_guid" <-- "repo.RepoObjectColumn_SSAS_tgt::RepoObjectColumn_guid"
"repo.RepoObjectColumn_SSAS_src::RepoObjectColumn_name" <-- "repo.RepoObjectColumn_SSAS_tgt::RepoObjectColumn_name"
"repo.RepoObjectColumn_SSAS_src::SysObjectColumn_name" <-- "repo.RepoObjectColumn_SSAS_tgt::SysObjectColumn_name"

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_colref[]


== sql_modules_definition

// tag::sql_modules_definition[]
[%collapsible]
=======
[source,sql,numbered,indent=0]
----

CREATE View repo.RepoObjectColumn_SSAS_tgt
As
Select
    T1.RepoObjectColumn_guid
  , T1.Inheritance_StringAggSeparatorSql
  , T1.InheritanceDefinition
  , T1.InheritanceType
  , T1.is_persistence_NoCompareNoUpdate
  , T1.is_persistence_Ignore
  , T1.is_persistence_NoCompareButUpdate
  , T1.is_query_plan_expression
  , T1.is_required_ColumnMerge
  , T1.is_SysObjectColumn_missing
  , T1.persistence_source_RepoObjectColumn_guid
  , T1.Referencing_Count
  , T1.Repo_default_definition
  , T1.Repo_default_is_system_named
  , T1.Repo_default_name
  , T1.Repo_definition
  , T1.Repo_generated_always_type
  , T1.Repo_graph_type
  , T1.Repo_is_computed
  , T1.Repo_is_identity
  , T1.Repo_is_nullable
  , T1.Repo_is_persisted
  , T1.Repo_seed_value
  , T1.Repo_increment_value
  , T1.Repo_user_type_name
  , T1.Repo_user_type_fullname
  , T1.Repo_uses_database_collation
  , T1.RepoObjectColumn_column_id
  , T1.RepoObjectColumn_name
  , T1.RepoObject_guid
  , T1.SysObjectColumn_column_id
  , T1.SysObjectColumn_name
From
    repo.RepoObjectColumn As T1
Where
    Exists
(
    Select
        1
    From
        repo.RepoObject_SSAS_tgt As T2
    Where
        T2.RepoObject_guid = T1.RepoObject_guid
)

----
=======
// end::sql_modules_definition[]


