// tag::HeaderFullDisplayName[]
= repo.RepoObjectColumn_RequiredRepoObjectColumnMerge - V
// end::HeaderFullDisplayName[]

== existing_properties

// tag::existing_properties[]

:ExistsProperty--antorareferencedlist:
:ExistsProperty--antorareferencinglist:
:ExistsProperty--description:
:ExistsProperty--is_repo_managed:
:ExistsProperty--is_ssas:
:ExistsProperty--referencedobjectlist:
:ExistsProperty--sql_modules_definition:
:ExistsProperty--FK:
:ExistsProperty--AntoraIndexList:
:ExistsProperty--Columns:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
861AAE52-A19B-EB11-84F6-A81E8446D5B0
// end::RepoObject_guid[]

== RepoObject_FullDisplayName2

// tag::RepoObject_FullDisplayName2[]
repo.RepoObjectColumn_RequiredRepoObjectColumnMerge
// end::RepoObject_FullDisplayName2[]

== SysObject_type

// tag::SysObject_type[]
V 
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
view
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
1533248517
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2022-01-05 18:06:34
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]
[discrete]
== _


[#column-isunderlinerepoobjectcolumnunderlinenameunderlineuniqueidentifier]
=== is_RepoObjectColumn_name_uniqueidentifier

[cols="d,8a,m,m,m"]
|===
|
|is_RepoObjectColumn_name_uniqueidentifier
|int
|NOT NULL
|
|===

.Description
--
(case when TRY_CAST([RepoObjectColumn_name] AS [uniqueidentifier]) IS NULL then (0) else (1) end)
--
{empty} +

.Referenced Columns
--
* xref:repo.repoobjectcolumn.adoc#column-isunderlinerepoobjectcolumnunderlinenameunderlineuniqueidentifier[+repo.RepoObjectColumn.is_RepoObjectColumn_name_uniqueidentifier+]
--


[#column-isunderlinesysobjectcolumnunderlinenameunderlineuniqueidentifier]
=== is_SysObjectColumn_name_uniqueidentifier

[cols="d,8a,m,m,m"]
|===
|
|is_SysObjectColumn_name_uniqueidentifier
|int
|NOT NULL
|
|===

.Description
--
(case when TRY_CAST([SysObjectColumn_name] AS [uniqueidentifier]) IS NULL then (0) else (1) end)
--
{empty} +

.Referenced Columns
--
* xref:repo.repoobjectcolumn.adoc#column-isunderlinesysobjectcolumnunderlinenameunderlineuniqueidentifier[+repo.RepoObjectColumn.is_SysObjectColumn_name_uniqueidentifier+]
--


[#column-persistenceunderlinesourceunderlinerepoobjectcolumnunderlineguid]
=== persistence_source_RepoObjectColumn_guid

[cols="d,8a,m,m,m"]
|===
|
|persistence_source_RepoObjectColumn_guid
|uniqueidentifier
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobjectcolumn.adoc#column-persistenceunderlinesourceunderlinerepoobjectcolumnunderlineguid[+repo.RepoObjectColumn.persistence_source_RepoObjectColumn_guid+]
--


[#column-repoobjectunderlineguid]
=== RepoObject_guid

[cols="d,8a,m,m,m"]
|===
|
|RepoObject_guid
|uniqueidentifier
|NOT NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobjectcolumn.adoc#column-repoobjectunderlineguid[+repo.RepoObjectColumn.RepoObject_guid+]
--


[#column-repoobjectcolumnunderlineguid]
=== RepoObjectColumn_guid

[cols="d,8a,m,m,m"]
|===
|
|RepoObjectColumn_guid
|uniqueidentifier
|NOT NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobjectcolumn.adoc#column-repoobjectcolumnunderlineguid[+repo.RepoObjectColumn.RepoObjectColumn_guid+]
--


[#column-repoobjectcolumnunderlinename]
=== RepoObjectColumn_name

[cols="d,8a,m,m,m"]
|===
|
|RepoObjectColumn_name
|nvarchar(128)
|NOT NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobjectcolumn.adoc#column-repoobjectcolumnunderlinename[+repo.RepoObjectColumn.RepoObjectColumn_name+]
--


[#column-roc2underlinepersistenceunderlinesourceunderlinerepoobjectcolumnunderlineguid]
=== roc2_persistence_source_RepoObjectColumn_guid

[cols="d,8a,m,m,m"]
|===
|
|roc2_persistence_source_RepoObjectColumn_guid
|uniqueidentifier
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobjectcolumn.adoc#column-persistenceunderlinesourceunderlinerepoobjectcolumnunderlineguid[+repo.RepoObjectColumn.persistence_source_RepoObjectColumn_guid+]
--


[#column-roc2underlinerepoobjectcolumnunderlineguid]
=== roc2_RepoObjectColumn_guid

[cols="d,8a,m,m,m"]
|===
|
|roc2_RepoObjectColumn_guid
|uniqueidentifier
|NOT NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobjectcolumn.adoc#column-repoobjectcolumnunderlineguid[+repo.RepoObjectColumn.RepoObjectColumn_guid+]
--


[#column-roc2underlinerepoobjectcolumnunderlinename]
=== roc2_RepoObjectColumn_name

[cols="d,8a,m,m,m"]
|===
|
|roc2_RepoObjectColumn_name
|nvarchar(128)
|NOT NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobjectcolumn.adoc#column-repoobjectcolumnunderlinename[+repo.RepoObjectColumn.RepoObjectColumn_name+]
--


[#column-roc2underlinesysobjectcolumnunderlinename]
=== roc2_SysObjectColumn_name

[cols="d,8a,m,m,m"]
|===
|
|roc2_SysObjectColumn_name
|nvarchar(128)
|NOT NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobjectcolumn.adoc#column-sysobjectcolumnunderlinename[+repo.RepoObjectColumn.SysObjectColumn_name+]
--


[#column-sysobjectcolumnunderlinename]
=== SysObjectColumn_name

[cols="d,8a,m,m,m"]
|===
|
|SysObjectColumn_name
|nvarchar(128)
|NOT NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobjectcolumn.adoc#column-sysobjectcolumnunderlinename[+repo.RepoObjectColumn.SysObjectColumn_name+]
--


// end::AntoraColumnDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]











// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]
|
|<<column-isunderlinerepoobjectcolumnunderlinenameunderlineuniqueidentifier>>
|int
|NOT NULL
|

|
|<<column-isunderlinesysobjectcolumnunderlinenameunderlineuniqueidentifier>>
|int
|NOT NULL
|

|
|<<column-persistenceunderlinesourceunderlinerepoobjectcolumnunderlineguid>>
|uniqueidentifier
|NULL
|

|
|<<column-repoobjectunderlineguid>>
|uniqueidentifier
|NOT NULL
|

|
|<<column-repoobjectcolumnunderlineguid>>
|uniqueidentifier
|NOT NULL
|

|
|<<column-repoobjectcolumnunderlinename>>
|nvarchar(128)
|NOT NULL
|

|
|<<column-roc2underlinepersistenceunderlinesourceunderlinerepoobjectcolumnunderlineguid>>
|uniqueidentifier
|NULL
|

|
|<<column-roc2underlinerepoobjectcolumnunderlineguid>>
|uniqueidentifier
|NOT NULL
|

|
|<<column-roc2underlinerepoobjectcolumnunderlinename>>
|nvarchar(128)
|NOT NULL
|

|
|<<column-roc2underlinesysobjectcolumnunderlinename>>
|nvarchar(128)
|NOT NULL
|

|
|<<column-sysobjectcolumnunderlinename>>
|nvarchar(128)
|NOT NULL
|

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

[#index-idxunderlinerepoobjectcolumnunderlinerequiredrepoobjectcolumnmergeunderlineunderline1]
=== idx_RepoObjectColumn_RequiredRepoObjectColumnMerge++__++1

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-roc2_RepoObjectColumn_guid>>; uniqueidentifier
--
* PK, Unique, Real: 0, 0, 0


[#index-idxunderlinerepoobjectcolumnunderlinerequiredrepoobjectcolumnmergeunderlineunderline2]
=== idx_RepoObjectColumn_RequiredRepoObjectColumnMerge++__++2

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-RepoObjectColumn_guid>>; uniqueidentifier
--
* PK, Unique, Real: 0, 0, 0


[#index-idxunderlinerepoobjectcolumnunderlinerequiredrepoobjectcolumnmergeunderlineunderline3]
=== idx_RepoObjectColumn_RequiredRepoObjectColumnMerge++__++3

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-roc2_RepoObjectColumn_guid>>; uniqueidentifier
* <<column-roc2_SysObjectColumn_name>>; nvarchar(128)
--
* PK, Unique, Real: 0, 0, 0


[#index-idxunderlinerepoobjectcolumnunderlinerequiredrepoobjectcolumnmergeunderlineunderline4]
=== idx_RepoObjectColumn_RequiredRepoObjectColumnMerge++__++4

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-RepoObjectColumn_guid>>; uniqueidentifier
* <<column-SysObjectColumn_name>>; nvarchar(128)
--
* PK, Unique, Real: 0, 0, 0


[#index-idxunderlinerepoobjectcolumnunderlinerequiredrepoobjectcolumnmergeunderlineunderline5]
=== idx_RepoObjectColumn_RequiredRepoObjectColumnMerge++__++5

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-RepoObject_guid>>; uniqueidentifier
* <<column-roc2_RepoObjectColumn_name>>; nvarchar(128)
--
* PK, Unique, Real: 0, 0, 0


[#index-idxunderlinerepoobjectcolumnunderlinerequiredrepoobjectcolumnmergeunderlineunderline6]
=== idx_RepoObjectColumn_RequiredRepoObjectColumnMerge++__++6

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-RepoObjectColumn_name>>; nvarchar(128)
--
* PK, Unique, Real: 0, 0, 0


[#index-idxunderlinerepoobjectcolumnunderlinerequiredrepoobjectcolumnmergeunderlineunderline7]
=== idx_RepoObjectColumn_RequiredRepoObjectColumnMerge++__++7

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-RepoObject_guid>>; uniqueidentifier
--
* PK, Unique, Real: 0, 0, 0

// end::AntoraIndexList[]

== AntoraMeasureDetails

// tag::AntoraMeasureDetails[]

// end::AntoraMeasureDetails[]

== AntoraMeasureDescriptions



== AntoraParameterList

// tag::AntoraParameterList[]

// end::AntoraParameterList[]

== AntoraXrefCulturesList

// tag::AntoraXrefCulturesList[]
* xref:dhw:sqldb:repo.repoobjectcolumn_requiredrepoobjectcolumnmerge.adoc[] - 
// end::AntoraXrefCulturesList[]

== cultures_count

// tag::cultures_count[]
1
// end::cultures_count[]

== Other tags

source: property.RepoObjectProperty_cross As rop_cross


=== additional_reference_csv

// tag::additional_reference_csv[]

// end::additional_reference_csv[]


=== AdocUspSteps

// tag::adocuspsteps[]

// end::adocuspsteps[]


=== AntoraReferencedList

// tag::antorareferencedlist[]
* xref:dhw:sqldb:repo.repoobjectcolumn.adoc[]
// end::antorareferencedlist[]


=== AntoraReferencingList

// tag::antorareferencinglist[]
* xref:dhw:sqldb:repo.usp_sync_guid_repoobjectcolumn.adoc[]
// end::antorareferencinglist[]


=== Description

// tag::description[]

list of conflicting entries which needs to be merged

mismatch of RepoObjectColumn_guid can create 2 entries per one RepoObjectColumn +
this can happen, if the guid exists in the database extended properties and a new guid will be created in the repo

* roc1 has the right RepoObjectColumn_fullname, but the guid was new created
* roc2 got the "right" guid from database, but roc2 can't propagate the fullname into RepoObjectColumn because the RepoObjectColumn_fullname is occupied
now we have 2 entries, but we need to merge them

what we need to do in xref:sqldb:repo.usp_sync_guid_repoobjectcolumn.adoc[]

* keep roc1 (which has the right RepoObjectColumn_name)
** mark them set is_required_ColumnMerge = 1
* delete columns with RepoObjectColumn_guid in roc2_RepoObjectColumn_guid
* set SysObjectColumn_name = RepoObjectColumn_name (for roc1, for marked columns)
* remove marker where SysObjectColumn_name = RepoObjectColumn_name

// end::description[]


=== exampleUsage

// tag::exampleusage[]

// end::exampleusage[]


=== exampleUsage_2

// tag::exampleusage_2[]

// end::exampleusage_2[]


=== exampleUsage_3

// tag::exampleusage_3[]

// end::exampleusage_3[]


=== exampleUsage_4

// tag::exampleusage_4[]

// end::exampleusage_4[]


=== exampleUsage_5

// tag::exampleusage_5[]

// end::exampleusage_5[]


=== exampleWrong_Usage

// tag::examplewrong_usage[]

// end::examplewrong_usage[]


=== has_execution_plan_issue

// tag::has_execution_plan_issue[]

// end::has_execution_plan_issue[]


=== has_get_referenced_issue

// tag::has_get_referenced_issue[]

// end::has_get_referenced_issue[]


=== has_history

// tag::has_history[]

// end::has_history[]


=== has_history_columns

// tag::has_history_columns[]

// end::has_history_columns[]


=== InheritanceType

// tag::inheritancetype[]

// end::inheritancetype[]


=== is_persistence

// tag::is_persistence[]

// end::is_persistence[]


=== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]

// end::is_persistence_check_duplicate_per_pk[]


=== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]

// end::is_persistence_check_for_empty_source[]


=== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]

// end::is_persistence_delete_changed[]


=== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]

// end::is_persistence_delete_missing[]


=== is_persistence_insert

// tag::is_persistence_insert[]

// end::is_persistence_insert[]


=== is_persistence_truncate

// tag::is_persistence_truncate[]

// end::is_persistence_truncate[]


=== is_persistence_update_changed

// tag::is_persistence_update_changed[]

// end::is_persistence_update_changed[]


=== is_repo_managed

// tag::is_repo_managed[]
0
// end::is_repo_managed[]


=== is_ssas

// tag::is_ssas[]
0
// end::is_ssas[]


=== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


=== MS_Description

// tag::ms_description[]

// end::ms_description[]


=== persistence_source_RepoObject_fullname

// tag::persistence_source_repoobject_fullname[]

// end::persistence_source_repoobject_fullname[]


=== persistence_source_RepoObject_fullname2

// tag::persistence_source_repoobject_fullname2[]

// end::persistence_source_repoobject_fullname2[]


=== persistence_source_RepoObject_guid

// tag::persistence_source_repoobject_guid[]

// end::persistence_source_repoobject_guid[]


=== persistence_source_RepoObject_xref

// tag::persistence_source_repoobject_xref[]

// end::persistence_source_repoobject_xref[]


=== pk_index_guid

// tag::pk_index_guid[]

// end::pk_index_guid[]


=== pk_IndexPatternColumnDatatype

// tag::pk_indexpatterncolumndatatype[]

// end::pk_indexpatterncolumndatatype[]


=== pk_IndexPatternColumnName

// tag::pk_indexpatterncolumnname[]

// end::pk_indexpatterncolumnname[]


=== pk_IndexSemanticGroup

// tag::pk_indexsemanticgroup[]

// end::pk_indexsemanticgroup[]


=== ReferencedObjectList

// tag::referencedobjectlist[]
* [repo].[RepoObjectColumn]
// end::referencedobjectlist[]


=== usp_persistence_RepoObject_guid

// tag::usp_persistence_repoobject_guid[]

// end::usp_persistence_repoobject_guid[]


=== UspExamples

// tag::uspexamples[]

// end::uspexamples[]


=== uspgenerator_usp_id

// tag::uspgenerator_usp_id[]

// end::uspgenerator_usp_id[]


=== UspParameters

// tag::uspparameters[]

// end::uspparameters[]

== Boolean Attributes

source: property.RepoObjectProperty WHERE property_int = 1

// tag::boolean_attributes[]


// end::boolean_attributes[]

== PlantUML diagrams

=== PlantUML Entity

// tag::puml_entity[]
[plantuml, entity-{docname}, svg, subs=macros]
....
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:repo.repoobjectcolumn_requiredrepoobjectcolumnmerge.adoc[]" as repo.RepoObjectColumn_RequiredRepoObjectColumnMerge << V >> {
  - is_RepoObjectColumn_name_uniqueidentifier : (int)
  - is_SysObjectColumn_name_uniqueidentifier : (int)
  persistence_source_RepoObjectColumn_guid : (uniqueidentifier)
  - RepoObject_guid : (uniqueidentifier)
  - RepoObjectColumn_guid : (uniqueidentifier)
  - RepoObjectColumn_name : (nvarchar(128))
  roc2_persistence_source_RepoObjectColumn_guid : (uniqueidentifier)
  - roc2_RepoObjectColumn_guid : (uniqueidentifier)
  - roc2_RepoObjectColumn_name : (nvarchar(128))
  - roc2_SysObjectColumn_name : (nvarchar(128))
  - SysObjectColumn_name : (nvarchar(128))
  --
}
....

// end::puml_entity[]

=== PlantUML Entity 1 1 FK

// tag::puml_entity_1_1_fk[]
[plantuml, entity_1_1_fk-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:repo.repoobjectcolumn_requiredrepoobjectcolumnmerge.adoc[]" as repo.RepoObjectColumn_RequiredRepoObjectColumnMerge << V >> {
- idx_RepoObjectColumn_RequiredRepoObjectColumnMerge__1

..
roc2_RepoObjectColumn_guid; uniqueidentifier
--
- idx_RepoObjectColumn_RequiredRepoObjectColumnMerge__2

..
RepoObjectColumn_guid; uniqueidentifier
--
- idx_RepoObjectColumn_RequiredRepoObjectColumnMerge__3

..
roc2_RepoObjectColumn_guid; uniqueidentifier
roc2_SysObjectColumn_name; nvarchar(128)
--
- idx_RepoObjectColumn_RequiredRepoObjectColumnMerge__4

..
RepoObjectColumn_guid; uniqueidentifier
SysObjectColumn_name; nvarchar(128)
--
- idx_RepoObjectColumn_RequiredRepoObjectColumnMerge__5

..
RepoObject_guid; uniqueidentifier
roc2_RepoObjectColumn_name; nvarchar(128)
--
- idx_RepoObjectColumn_RequiredRepoObjectColumnMerge__6

..
RepoObjectColumn_name; nvarchar(128)
--
- idx_RepoObjectColumn_RequiredRepoObjectColumnMerge__7

..
RepoObject_guid; uniqueidentifier
}



footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_fk[]

=== PlantUML 1 1 ObjectRef

// tag::puml_entity_1_1_objectref[]
[plantuml, entity_1_1_objectref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:repo.repoobjectcolumn.adoc[]" as repo.RepoObjectColumn << U >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn_requiredrepoobjectcolumnmerge.adoc[]" as repo.RepoObjectColumn_RequiredRepoObjectColumnMerge << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_sync_guid_repoobjectcolumn.adoc[]" as repo.usp_sync_guid_RepoObjectColumn << P >> {
  --
}

repo.RepoObjectColumn <.. repo.RepoObjectColumn_RequiredRepoObjectColumnMerge
repo.RepoObjectColumn_RequiredRepoObjectColumnMerge <.. repo.usp_sync_guid_RepoObjectColumn

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_objectref[]

=== PlantUML 30 0 ObjectRef

// tag::puml_entity_30_0_objectref[]
[plantuml, entity_30_0_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:config.ftv_get_parameter_value.adoc[]" as config.ftv_get_parameter_value << IF >> {
  --
}

entity "puml-link:dhw:sqldb:config.parameter.adoc[]" as config.Parameter << U >> {
  - **Parameter_name** : (varchar(100))
  - **sub_Parameter** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:configt.parameter_default.adoc[]" as configT.Parameter_default << V >> {
  - **Parameter_name** : (varchar(52))
  - **sub_Parameter** : (nvarchar(26))
  --
}

entity "puml-link:dhw:sqldb:property.external_repoobjectproperty.adoc[]" as property.external_RepoObjectProperty << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.propertyname_repoobject.adoc[]" as property.PropertyName_RepoObject << V >> {
  **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.propertyname_repoobject_t.adoc[]" as property.PropertyName_RepoObject_T << U >> {
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty.adoc[]" as property.RepoObjectProperty << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty_external_src.adoc[]" as property.RepoObjectProperty_external_src << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty_external_tgt.adoc[]" as property.RepoObjectProperty_external_tgt << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty_selectedpropertyname_split.adoc[]" as property.RepoObjectProperty_SelectedPropertyName_split << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference.adoc[]" as reference.additional_Reference << U >> {
  # **tik_hash_c** : (nvarchar(32))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_from_properties_src.adoc[]" as reference.additional_Reference_from_properties_src << V >> {
  **referenced_AntoraComponent** : (nvarchar(max))
  **referenced_AntoraModule** : (nvarchar(max))
  **referenced_Schema** : (nvarchar(max))
  **referenced_Object** : (nvarchar(max))
  **referenced_Column** : (nvarchar(max))
  **referencing_AntoraComponent** : (nvarchar(max))
  **referencing_AntoraModule** : (nvarchar(max))
  **referencing_Schema** : (nvarchar(max))
  **referencing_Object** : (nvarchar(max))
  **referencing_Column** : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_from_properties_tgt.adoc[]" as reference.additional_Reference_from_properties_tgt << V >> {
  - **referenced_AntoraComponent** : (nvarchar(128))
  - **referenced_AntoraModule** : (nvarchar(128))
  - **referenced_Schema** : (nvarchar(128))
  - **referenced_Object** : (nvarchar(128))
  **referenced_Column** : (nvarchar(128))
  - **referencing_AntoraComponent** : (nvarchar(128))
  - **referencing_AntoraModule** : (nvarchar(128))
  - **referencing_Schema** : (nvarchar(128))
  - **referencing_Object** : (nvarchar(128))
  **referencing_Column** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_from_ssas_src.adoc[]" as reference.additional_Reference_from_ssas_src << V >> {
  **referenced_AntoraComponent** : (nvarchar(128))
  **referenced_AntoraModule** : (nvarchar(128))
  **referenced_Schema** : (nvarchar(max))
  **referenced_Object** : (nvarchar(max))
  **referenced_Column** : (nvarchar(500))
  **referencing_AntoraComponent** : (nvarchar(max))
  **referencing_AntoraModule** : (nvarchar(max))
  - **referencing_Schema** : (nvarchar(128))
  - **referencing_Object** : (nvarchar(128))
  **referencing_Column** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_from_ssas_tgt.adoc[]" as reference.additional_Reference_from_ssas_tgt << V >> {
  - **referenced_AntoraComponent** : (nvarchar(128))
  - **referenced_AntoraModule** : (nvarchar(128))
  - **referenced_Schema** : (nvarchar(128))
  - **referenced_Object** : (nvarchar(128))
  **referenced_Column** : (nvarchar(128))
  - **referencing_AntoraComponent** : (nvarchar(128))
  - **referencing_AntoraModule** : (nvarchar(128))
  - **referencing_Schema** : (nvarchar(128))
  - **referencing_Object** : (nvarchar(128))
  **referencing_Column** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_is_external.adoc[]" as reference.additional_Reference_is_external << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_object.adoc[]" as reference.additional_Reference_Object << V >> {
  - **AntoraComponent** : (nvarchar(128))
  - **AntoraModule** : (nvarchar(128))
  - **SchemaName** : (nvarchar(128))
  - **ObjectName** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_object_t.adoc[]" as reference.additional_Reference_Object_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_objectcolumn.adoc[]" as reference.additional_Reference_ObjectColumn << V >> {
  - **AntoraComponent** : (nvarchar(128))
  - **AntoraModule** : (nvarchar(128))
  - **SchemaName** : (nvarchar(128))
  - **ObjectName** : (nvarchar(128))
  **ColumnName** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_objectcolumn_t.adoc[]" as reference.additional_Reference_ObjectColumn_T << U >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_wo_columns_from_properties_src.adoc[]" as reference.additional_Reference_wo_columns_from_properties_src << V >> {
  **referenced_AntoraComponent** : (nvarchar(max))
  **referenced_AntoraModule** : (nvarchar(max))
  **referenced_Schema** : (nvarchar(max))
  **referenced_Object** : (nvarchar(max))
  **referencing_AntoraComponent** : (nvarchar(max))
  **referencing_AntoraModule** : (nvarchar(max))
  **referencing_Schema** : (nvarchar(max))
  **referencing_Object** : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_wo_columns_from_properties_tgt.adoc[]" as reference.additional_Reference_wo_columns_from_properties_tgt << V >> {
  - **referenced_AntoraComponent** : (nvarchar(128))
  - **referenced_AntoraModule** : (nvarchar(128))
  - **referenced_Schema** : (nvarchar(128))
  - **referenced_Object** : (nvarchar(128))
  - **referencing_AntoraComponent** : (nvarchar(128))
  - **referencing_AntoraModule** : (nvarchar(128))
  - **referencing_Schema** : (nvarchar(128))
  - **referencing_Object** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject.adoc[]" as repo.RepoObject << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_external_src.adoc[]" as repo.RepoObject_external_src << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_external_tgt.adoc[]" as repo.RepoObject_external_tgt << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_ssas_src.adoc[]" as repo.RepoObject_SSAS_src << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_ssas_tgt.adoc[]" as repo.RepoObject_SSAS_tgt << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn.adoc[]" as repo.RepoObjectColumn << U >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn_external_src.adoc[]" as repo.RepoObjectColumn_external_src << V >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn_external_tgt.adoc[]" as repo.RepoObjectColumn_external_tgt << V >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn_requiredrepoobjectcolumnmerge.adoc[]" as repo.RepoObjectColumn_RequiredRepoObjectColumnMerge << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn_ssas_src.adoc[]" as repo.RepoObjectColumn_SSAS_src << V >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn_ssas_tgt.adoc[]" as repo.RepoObjectColumn_SSAS_tgt << V >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.reposchema.adoc[]" as repo.RepoSchema << U >> {
  - **RepoSchema_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.reposchema_ssas_src.adoc[]" as repo.RepoSchema_ssas_src << V >> {
  - **RepoSchema_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:repo.reposchema_ssas_tgt.adoc[]" as repo.RepoSchema_ssas_tgt << V >> {
  - **RepoSchema_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:ssas.additional_reference_step1.adoc[]" as ssas.additional_Reference_step1 << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json.adoc[]" as ssas.model_json << U >> {
  - **databasename** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_10.adoc[]" as ssas.model_json_10 << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_20.adoc[]" as ssas.model_json_20 << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_201_descriptions_multiline.adoc[]" as ssas.model_json_201_descriptions_multiline << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_2011_descriptions_stragg.adoc[]" as ssas.model_json_2011_descriptions_StrAgg << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31_tables.adoc[]" as ssas.model_json_31_tables << V >> {
  - **databasename** : (nvarchar(128))
  **tables_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31_tables_t.adoc[]" as ssas.model_json_31_tables_T << U >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_311_tables_columns.adoc[]" as ssas.model_json_311_tables_columns << V >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  **tables_columns_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_311_tables_columns_t.adoc[]" as ssas.model_json_311_tables_columns_T << U >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  - **tables_columns_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_313_tables_partitions.adoc[]" as ssas.model_json_313_tables_partitions << V >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  **tables_partitions_name** : (nvarchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_3131_tables_partitions_source.adoc[]" as ssas.model_json_3131_tables_partitions_source << V >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  **tables_partitions_name** : (nvarchar(500))
  **tables_partitions_source_name** : (nvarchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31311_tables_partitions_source_posfrom.adoc[]" as ssas.model_json_31311_tables_partitions_source_PosFrom << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_313111_tables_partitions_source_stringfrom.adoc[]" as ssas.model_json_313111_tables_partitions_source_StringFrom << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_3131111_tables_partitions_source_posdot.adoc[]" as ssas.model_json_3131111_tables_partitions_source_PosDot << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31311111_tables_partitions_source_part123.adoc[]" as ssas.model_json_31311111_tables_partitions_source_Part123 << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_33_datasources.adoc[]" as ssas.model_json_33_dataSources << V >> {
  - **databasename** : (nvarchar(128))
  **dataSources_name** : (nvarchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_33_datasources_t.adoc[]" as ssas.model_json_33_dataSources_T << U >> {
  - **databasename** : (nvarchar(128))
  - **dataSources_name** : (nvarchar(500))
  --
}

config.ftv_get_parameter_value <.. reference.additional_Reference_is_external
config.ftv_get_parameter_value <.. repo.RepoObject_external_src
config.ftv_get_parameter_value <.. ssas.additional_Reference_step1
config.Parameter <.. config.ftv_get_parameter_value
config.Parameter <.. property.PropertyName_RepoObject
configT.Parameter_default <.. config.Parameter
property.external_RepoObjectProperty <.. property.RepoObjectProperty_external_src
property.PropertyName_RepoObject <.. property.PropertyName_RepoObject_T
property.PropertyName_RepoObject_T <.. property.RepoObjectProperty_external_tgt
property.RepoObjectProperty <.. property.PropertyName_RepoObject
property.RepoObjectProperty <.. property.RepoObjectProperty_SelectedPropertyName_split
property.RepoObjectProperty_external_src <.. property.RepoObjectProperty_external_tgt
property.RepoObjectProperty_external_tgt <.. property.RepoObjectProperty
property.RepoObjectProperty_SelectedPropertyName_split <.. reference.additional_Reference_from_properties_src
property.RepoObjectProperty_SelectedPropertyName_split <.. reference.additional_Reference_wo_columns_from_properties_src
reference.additional_Reference <.. reference.additional_Reference_is_external
reference.additional_Reference_from_properties_src <.. reference.additional_Reference_from_properties_tgt
reference.additional_Reference_from_properties_tgt <.. reference.additional_Reference
reference.additional_Reference_from_ssas_src <.. reference.additional_Reference_from_ssas_tgt
reference.additional_Reference_from_ssas_tgt <.. reference.additional_Reference
reference.additional_Reference_is_external <.. reference.additional_Reference_Object
reference.additional_Reference_is_external <.. reference.additional_Reference_ObjectColumn
reference.additional_Reference_Object <.. reference.additional_Reference_Object_T
reference.additional_Reference_Object_T <.. repo.RepoObject_external_src
reference.additional_Reference_Object_T <.. repo.RepoObjectColumn_external_src
reference.additional_Reference_ObjectColumn <.. reference.additional_Reference_ObjectColumn_T
reference.additional_Reference_ObjectColumn_T <.. repo.RepoObjectColumn_external_src
reference.additional_Reference_wo_columns_from_properties_src <.. reference.additional_Reference_wo_columns_from_properties_tgt
reference.additional_Reference_wo_columns_from_properties_tgt <.. reference.additional_Reference
repo.RepoObject <.. property.RepoObjectProperty_external_tgt
repo.RepoObject <.. repo.RepoObject_external_src
repo.RepoObject <.. repo.RepoObjectColumn_external_src
repo.RepoObject_external_src <.. repo.RepoObject_external_tgt
repo.RepoObject_external_tgt <.. repo.RepoObject
repo.RepoObject_external_tgt <.. repo.RepoObjectColumn_external_tgt
repo.RepoObject_SSAS_src <.. repo.RepoObject_SSAS_tgt
repo.RepoObject_SSAS_tgt <.. repo.RepoObject
repo.RepoObject_SSAS_tgt <.. repo.RepoObjectColumn_SSAS_tgt
repo.RepoObjectColumn <.. repo.RepoObjectColumn_RequiredRepoObjectColumnMerge
repo.RepoObjectColumn_external_src <.. repo.RepoObjectColumn_external_tgt
repo.RepoObjectColumn_external_tgt <.. repo.RepoObjectColumn
repo.RepoObjectColumn_SSAS_src <.. repo.RepoObjectColumn_SSAS_tgt
repo.RepoObjectColumn_SSAS_tgt <.. repo.RepoObjectColumn
repo.RepoSchema <.. repo.RepoObject_SSAS_src
repo.RepoSchema_ssas_src <.. repo.RepoSchema_ssas_tgt
repo.RepoSchema_ssas_tgt <.. repo.RepoSchema
ssas.additional_Reference_step1 <.. reference.additional_Reference_from_ssas_src
ssas.model_json <.. ssas.model_json_10
ssas.model_json_10 <.. ssas.model_json_20
ssas.model_json_20 <.. repo.RepoSchema_ssas_src
ssas.model_json_20 <.. ssas.model_json_201_descriptions_multiline
ssas.model_json_20 <.. ssas.model_json_31_tables
ssas.model_json_20 <.. ssas.model_json_33_dataSources
ssas.model_json_201_descriptions_multiline <.. ssas.model_json_2011_descriptions_StrAgg
ssas.model_json_2011_descriptions_StrAgg <.. repo.RepoSchema_ssas_src
ssas.model_json_31_tables <.. ssas.model_json_31_tables_T
ssas.model_json_31_tables_T <.. repo.RepoObject_SSAS_src
ssas.model_json_31_tables_T <.. ssas.model_json_311_tables_columns
ssas.model_json_31_tables_T <.. ssas.model_json_313_tables_partitions
ssas.model_json_311_tables_columns <.. ssas.model_json_311_tables_columns_T
ssas.model_json_311_tables_columns_T <.. repo.RepoObjectColumn_SSAS_src
ssas.model_json_311_tables_columns_T <.. ssas.additional_Reference_step1
ssas.model_json_313_tables_partitions <.. ssas.model_json_3131_tables_partitions_source
ssas.model_json_3131_tables_partitions_source <.. ssas.model_json_31311_tables_partitions_source_PosFrom
ssas.model_json_31311_tables_partitions_source_PosFrom <.. ssas.model_json_313111_tables_partitions_source_StringFrom
ssas.model_json_313111_tables_partitions_source_StringFrom <.. ssas.model_json_3131111_tables_partitions_source_PosDot
ssas.model_json_3131111_tables_partitions_source_PosDot <.. ssas.model_json_31311111_tables_partitions_source_Part123
ssas.model_json_31311111_tables_partitions_source_Part123 <.. ssas.additional_Reference_step1
ssas.model_json_33_dataSources <.. ssas.model_json_33_dataSources_T
ssas.model_json_33_dataSources_T <.. ssas.additional_Reference_step1

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_30_0_objectref[]

=== PlantUML 0 30 ObjectRef

// tag::puml_entity_0_30_objectref[]
[plantuml, entity_0_30_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:repo.repoobjectcolumn_requiredrepoobjectcolumnmerge.adoc[]" as repo.RepoObjectColumn_RequiredRepoObjectColumnMerge << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_main.adoc[]" as repo.usp_main << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_persistence_set.adoc[]" as repo.usp_persistence_set << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_sync_guid.adoc[]" as repo.usp_sync_guid << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_sync_guid_repoobjectcolumn.adoc[]" as repo.usp_sync_guid_RepoObjectColumn << P >> {
  --
}

repo.RepoObjectColumn_RequiredRepoObjectColumnMerge <.. repo.usp_sync_guid_RepoObjectColumn
repo.usp_sync_guid <.. repo.usp_main
repo.usp_sync_guid <.. repo.usp_persistence_set
repo.usp_sync_guid_RepoObjectColumn <.. repo.usp_sync_guid

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_0_30_objectref[]

=== PlantUML 1 1 ColumnRef

// tag::puml_entity_1_1_colref[]
[plantuml, entity_1_1_colref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:repo.repoobjectcolumn.adoc[]" as repo.RepoObjectColumn << U >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  Inheritance_StringAggSeparatorSql : (nvarchar(4000))
  InheritanceDefinition : (nvarchar(4000))
  InheritanceType : (tinyint)
  is_persistence_Ignore : (bit)
  is_persistence_NoCompareButUpdate : (bit)
  is_persistence_NoCompareNoUpdate : (bit)
  is_persistence_NoInsert : (bit)
  is_query_plan_expression : (bit)
  is_required_ColumnMerge : (bit)
  is_SysObjectColumn_missing : (bit)
  persistence_source_RepoObjectColumn_guid : (uniqueidentifier)
  Referencing_Count : (int)
  Repo_default_definition : (nvarchar(max))
  Repo_default_is_system_named : (bit)
  Repo_default_name : (nvarchar(128))
  Repo_definition : (nvarchar(max))
  - Repo_generated_always_type : (tinyint)
  Repo_graph_type : (int)
  Repo_increment_value : (sql_variant)
  - Repo_is_computed : (bit)
  - Repo_is_identity : (bit)
  Repo_is_nullable : (bit)
  Repo_is_persisted : (bit)
  Repo_seed_value : (sql_variant)
  Repo_user_type_fullname : (nvarchar(128))
  Repo_user_type_name : (nvarchar(128))
  Repo_uses_database_collation : (bit)
  - RepoObject_guid : (uniqueidentifier)
  RepoObjectColumn_column_id : (int)
  - RepoObjectColumn_name : (nvarchar(128))
  SysObjectColumn_column_id : (int)
  - SysObjectColumn_name : (nvarchar(128))
  # Column_name : (nvarchar(128))
  ~ has_different_sys_names : (bit)
  # is_RepoObjectColumn_name_uniqueidentifier : (int)
  # is_SysObjectColumn_name_uniqueidentifier : (int)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn_requiredrepoobjectcolumnmerge.adoc[]" as repo.RepoObjectColumn_RequiredRepoObjectColumnMerge << V >> {
  - is_RepoObjectColumn_name_uniqueidentifier : (int)
  - is_SysObjectColumn_name_uniqueidentifier : (int)
  persistence_source_RepoObjectColumn_guid : (uniqueidentifier)
  - RepoObject_guid : (uniqueidentifier)
  - RepoObjectColumn_guid : (uniqueidentifier)
  - RepoObjectColumn_name : (nvarchar(128))
  roc2_persistence_source_RepoObjectColumn_guid : (uniqueidentifier)
  - roc2_RepoObjectColumn_guid : (uniqueidentifier)
  - roc2_RepoObjectColumn_name : (nvarchar(128))
  - roc2_SysObjectColumn_name : (nvarchar(128))
  - SysObjectColumn_name : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:repo.usp_sync_guid_repoobjectcolumn.adoc[]" as repo.usp_sync_guid_RepoObjectColumn << P >> {
  --
}

repo.RepoObjectColumn <.. repo.RepoObjectColumn_RequiredRepoObjectColumnMerge
repo.RepoObjectColumn_RequiredRepoObjectColumnMerge <.. repo.usp_sync_guid_RepoObjectColumn
"repo.RepoObjectColumn::is_RepoObjectColumn_name_uniqueidentifier" <-- "repo.RepoObjectColumn_RequiredRepoObjectColumnMerge::is_RepoObjectColumn_name_uniqueidentifier"
"repo.RepoObjectColumn::is_SysObjectColumn_name_uniqueidentifier" <-- "repo.RepoObjectColumn_RequiredRepoObjectColumnMerge::is_SysObjectColumn_name_uniqueidentifier"
"repo.RepoObjectColumn::persistence_source_RepoObjectColumn_guid" <-- "repo.RepoObjectColumn_RequiredRepoObjectColumnMerge::persistence_source_RepoObjectColumn_guid"
"repo.RepoObjectColumn::persistence_source_RepoObjectColumn_guid" <-- "repo.RepoObjectColumn_RequiredRepoObjectColumnMerge::roc2_persistence_source_RepoObjectColumn_guid"
"repo.RepoObjectColumn::RepoObject_guid" <-- "repo.RepoObjectColumn_RequiredRepoObjectColumnMerge::RepoObject_guid"
"repo.RepoObjectColumn::RepoObjectColumn_guid" <-- "repo.RepoObjectColumn_RequiredRepoObjectColumnMerge::RepoObjectColumn_guid"
"repo.RepoObjectColumn::RepoObjectColumn_guid" <-- "repo.RepoObjectColumn_RequiredRepoObjectColumnMerge::roc2_RepoObjectColumn_guid"
"repo.RepoObjectColumn::RepoObjectColumn_name" <-- "repo.RepoObjectColumn_RequiredRepoObjectColumnMerge::RepoObjectColumn_name"
"repo.RepoObjectColumn::RepoObjectColumn_name" <-- "repo.RepoObjectColumn_RequiredRepoObjectColumnMerge::roc2_RepoObjectColumn_name"
"repo.RepoObjectColumn::SysObjectColumn_name" <-- "repo.RepoObjectColumn_RequiredRepoObjectColumnMerge::roc2_SysObjectColumn_name"
"repo.RepoObjectColumn::SysObjectColumn_name" <-- "repo.RepoObjectColumn_RequiredRepoObjectColumnMerge::SysObjectColumn_name"

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_colref[]


== sql_modules_definition

// tag::sql_modules_definition[]
[%collapsible]
=======
[source,sql,numbered,indent=0]
----





/*
<<property_start>>Description
list of conflicting entries which needs to be merged

mismatch of RepoObjectColumn_guid can create 2 entries per one RepoObjectColumn +
this can happen, if the guid exists in the database extended properties and a new guid will be created in the repo

* roc1 has the right RepoObjectColumn_fullname, but the guid was new created
* roc2 got the "right" guid from database, but roc2 can't propagate the fullname into RepoObjectColumn because the RepoObjectColumn_fullname is occupied
now we have 2 entries, but we need to merge them

what we need to do in xref:sqldb:repo.usp_sync_guid_repoobjectcolumn.adoc[]

* keep roc1 (which has the right RepoObjectColumn_name)
** mark them set is_required_ColumnMerge = 1
* delete columns with RepoObjectColumn_guid in roc2_RepoObjectColumn_guid
* set SysObjectColumn_name = RepoObjectColumn_name (for roc1, for marked columns)
* remove marker where SysObjectColumn_name = RepoObjectColumn_name

<<property_end>>
*/
CREATE View [repo].[RepoObjectColumn_RequiredRepoObjectColumnMerge]
As
Select
    --
    roc1.RepoObject_guid
  , roc1.RepoObjectColumn_guid
  , roc1.is_RepoObjectColumn_name_uniqueidentifier
  , roc1.is_SysObjectColumn_name_uniqueidentifier
  , roc1.persistence_source_RepoObjectColumn_guid
  , roc1.RepoObjectColumn_name
  , roc1.SysObjectColumn_name
  , roc2_persistence_source_RepoObjectColumn_guid = roc2.persistence_source_RepoObjectColumn_guid
  , roc2_RepoObjectColumn_guid                    = roc2.RepoObjectColumn_guid
  , roc2_RepoObjectColumn_name                    = roc2.RepoObjectColumn_name
  , roc2_SysObjectColumn_name                     = roc2.SysObjectColumn_name
From
    repo.RepoObjectColumn     As roc1
    Inner Join
        repo.RepoObjectColumn As roc2
            On
            roc2.RepoObject_guid           = roc1.RepoObject_guid
            And roc2.SysObjectColumn_name  = roc1.RepoObjectColumn_name
            And roc2.RepoObjectColumn_guid <> roc1.RepoObjectColumn_guid
----
=======
// end::sql_modules_definition[]


