// tag::HeaderFullDisplayName[]
= repo.Index_virtual - U
// end::HeaderFullDisplayName[]

== existing_properties

// tag::existing_properties[]

:ExistsProperty--antorareferencinglist:
:ExistsProperty--is_repo_managed:
:ExistsProperty--is_ssas:
:ExistsProperty--pk_index_guid:
:ExistsProperty--pk_indexpatterncolumndatatype:
:ExistsProperty--pk_indexpatterncolumnname:
:ExistsProperty--FK:
:ExistsProperty--AntoraIndexList:
:ExistsProperty--Columns:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
3490291C-9D61-EB11-84DC-A81E8446D5B0
// end::RepoObject_guid[]

== RepoObject_FullDisplayName2

// tag::RepoObject_FullDisplayName2[]
repo.Index_virtual
// end::RepoObject_FullDisplayName2[]

== SysObject_type

// tag::SysObject_type[]
U 
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
user table
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
1991678143
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2022-01-23 14:10:17
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]
[discrete]
== _


[#column-indexunderlineguid]
=== index_guid

[cols="d,8a,m,m,m"]
|===
|1
|*index_guid*

.Default: DF__Index_vir__index__12FDD1B2
[source,sql]
----
(newsequentialid())
----


|uniqueidentifier
|NOT NULL
|
|===

.Referencing Columns
--
* xref:repo.index_virtual_forupdate.adoc#column-indexunderlineguid[+repo.Index_virtual_ForUpdate.index_guid+]
* xref:repo.index_virtual_indexpatterncolumnguid.adoc#column-indexunderlineguid[+repo.Index_virtual_IndexPatternColumnGuid.index_guid+]
* xref:repo.index_virtual_sysobject.adoc#column-indexunderlineguid[+repo.Index_virtual_SysObject.index_guid+]
* xref:repo.indexcolumn_virtual_referenced_setpoint.adoc#column-indexunderlineguid[+repo.IndexColumn_virtual_referenced_setpoint.index_guid+]
--


[#column-hasunderlinemanagedname]
=== has_managedName

[cols="d,8a,m,m,m"]
|===
|
|has_managedName

.Default: DF_Index_virtual_has_managedName
[source,sql]
----
((1))
----


|bit
|NOT NULL
|
|===

.Referencing Columns
--
* xref:repo.index_virtual_forupdate.adoc#column-hasunderlinemanagedname[+repo.Index_virtual_ForUpdate.has_managedName+]
--


[#column-indexunderlinename]
=== index_name

[cols="d,8a,m,m,m"]
|===
|
|index_name
|nvarchar(128)
|NULL
|
|===

.Referencing Columns
--
* xref:repo.index_virtual_forupdate.adoc#column-indexunderlinename[+repo.Index_virtual_ForUpdate.index_name+]
* xref:repo.index_virtual_sysobject.adoc#column-indexunderlinename[+repo.Index_virtual_SysObject.index_name+]
* xref:repo.indexcolumn_virtual_gross.adoc#column-indexunderlinename[+repo.IndexColumn_virtual_gross.index_name+]
--


[#column-indexunderlinetype]
=== index_type

[cols="d,8a,m,m,m"]
|===
|
|index_type

.Default: DF__Index_vir__index__13F1F5EB
[source,sql]
----
((0))
----


|tinyint
|NOT NULL
|
|===

.Referencing Columns
--
* xref:repo.index_virtual_forupdate.adoc#column-indexunderlinetype[+repo.Index_virtual_ForUpdate.index_type+]
--


[#column-isunderlineindexunderlinedisabled]
=== is_index_disabled

[cols="d,8a,m,m,m"]
|===
|
|is_index_disabled

.Default: DF__Index_vir__is_in__14E61A24
[source,sql]
----
((0))
----


|bit
|NOT NULL
|
|===

.Referencing Columns
--
* xref:repo.index_virtual_forupdate.adoc#column-isunderlineindexunderlinedisabled[+repo.Index_virtual_ForUpdate.is_index_disabled+]
* xref:repo.index_virtual_sysobject.adoc#column-isunderlineindexunderlinedisabled[+repo.Index_virtual_SysObject.is_index_disabled+]
--


[#column-isunderlineindexunderlineprimaryunderlinekey]
=== is_index_primary_key

[cols="d,8a,m,m,m"]
|===
|
|is_index_primary_key

.Default: DF__Index_vir__is_in__15DA3E5D
[source,sql]
----
((0))
----


|bit
|NOT NULL
|
|===

.Referencing Columns
--
* xref:repo.index_virtual_forupdate.adoc#column-isunderlineindexunderlineprimaryunderlinekey[+repo.Index_virtual_ForUpdate.is_index_primary_key+]
* xref:repo.index_virtual_sysobject.adoc#column-isunderlineindexunderlineprimaryunderlinekey[+repo.Index_virtual_SysObject.is_index_primary_key+]
* xref:repo.indexcolumn_virtual_gross.adoc#column-isunderlineindexunderlineprimaryunderlinekey[+repo.IndexColumn_virtual_gross.is_index_primary_key+]
--


[#column-isunderlineindexunderlineunique]
=== is_index_unique

[cols="d,8a,m,m,m"]
|===
|
|is_index_unique

.Default: DF__Index_vir__is_in__16CE6296
[source,sql]
----
((0))
----


|bit
|NOT NULL
|
|===

.Referencing Columns
--
* xref:repo.index_virtual_forupdate.adoc#column-isunderlineindexunderlineunique[+repo.Index_virtual_ForUpdate.is_index_unique+]
* xref:repo.index_virtual_sysobject.adoc#column-isunderlineindexunderlineunique[+repo.Index_virtual_SysObject.is_index_unique+]
* xref:repo.indexcolumn_virtual_gross.adoc#column-isunderlineindexunderlineunique[+repo.IndexColumn_virtual_gross.is_index_unique+]
--


[#column-parentunderlinerepoobjectunderlineguid]
=== parent_RepoObject_guid

[cols="d,8a,m,m,m"]
|===
|
|parent_RepoObject_guid
|uniqueidentifier
|NOT NULL
|
|===

.Referencing Columns
--
* xref:repo.index_virtual_forupdate.adoc#column-parentunderlinerepoobjectunderlineguid[+repo.Index_virtual_ForUpdate.parent_RepoObject_guid+]
* xref:repo.index_virtual_indexpatterncolumnguid.adoc#column-parentunderlinerepoobjectunderlineguid[+repo.Index_virtual_IndexPatternColumnGuid.parent_RepoObject_guid+]
* xref:repo.index_virtual_sysobject.adoc#column-parentunderlinerepoobjectunderlineguid[+repo.Index_virtual_SysObject.parent_RepoObject_guid+]
* xref:repo.indexcolumn_virtual_gross.adoc#column-parentunderlinerepoobjectunderlineguid[+repo.IndexColumn_virtual_gross.parent_RepoObject_guid+]
--


[#column-referencedunderlineindexunderlineguid]
=== referenced_index_guid

[cols="d,8a,m,m,m"]
|===
|
|referenced_index_guid
|uniqueidentifier
|NULL
|
|===

.Referencing Columns
--
* xref:repo.index_virtual_forupdate.adoc#column-referencedunderlineindexunderlineguid[+repo.Index_virtual_ForUpdate.referenced_index_guid+]
* xref:repo.index_virtual_sysobject.adoc#column-referencedunderlineindexunderlineguid[+repo.Index_virtual_SysObject.referenced_index_guid+]
* xref:repo.indexcolumn_virtual_referenced_setpoint.adoc#column-referencedunderlineindexunderlineguid[+repo.IndexColumn_virtual_referenced_setpoint.referenced_index_guid+]
* xref:repo.indexreferencedreferencing.adoc#column-referencedunderlineindexunderlineguid[+repo.IndexReferencedReferencing.referenced_index_guid+]
--


[#column-rownumberinreferencing]
=== RowNumberInReferencing

[cols="d,8a,m,m,m"]
|===
|
|RowNumberInReferencing
|int
|NULL
|
|===

.Referencing Columns
--
* xref:repo.index_virtual_forupdate.adoc#column-rownumberinreferencing[+repo.Index_virtual_ForUpdate.RowNumberInReferencing+]
* xref:repo.indexcolumn_virtual_referenced_setpoint.adoc#column-rownumberinreferencing[+repo.IndexColumn_virtual_referenced_setpoint.RowNumberInReferencing+]
* xref:repo.indexreferencedreferencing.adoc#column-rownumberinreferencingunderlinetarget[+repo.IndexReferencedReferencing.RowNumberInReferencing_Target+]
--


// end::AntoraColumnDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]
|1
|*<<column-indexunderlineguid>>*

.Default: DF__Index_vir__index__12FDD1B2
[source,sql]
----
(newsequentialid())
----


|uniqueidentifier
|NOT NULL
|










// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]

|
|<<column-hasunderlinemanagedname>>

.Default: DF_Index_virtual_has_managedName
[source,sql]
----
((1))
----


|bit
|NOT NULL
|

|
|<<column-indexunderlinename>>
|nvarchar(128)
|NULL
|

|
|<<column-indexunderlinetype>>

.Default: DF__Index_vir__index__13F1F5EB
[source,sql]
----
((0))
----


|tinyint
|NOT NULL
|

|
|<<column-isunderlineindexunderlinedisabled>>

.Default: DF__Index_vir__is_in__14E61A24
[source,sql]
----
((0))
----


|bit
|NOT NULL
|

|
|<<column-isunderlineindexunderlineprimaryunderlinekey>>

.Default: DF__Index_vir__is_in__15DA3E5D
[source,sql]
----
((0))
----


|bit
|NOT NULL
|

|
|<<column-isunderlineindexunderlineunique>>

.Default: DF__Index_vir__is_in__16CE6296
[source,sql]
----
((0))
----


|bit
|NOT NULL
|

|
|<<column-parentunderlinerepoobjectunderlineguid>>
|uniqueidentifier
|NOT NULL
|

|
|<<column-referencedunderlineindexunderlineguid>>
|uniqueidentifier
|NULL
|

|
|<<column-rownumberinreferencing>>
|int
|NULL
|

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

[#index-pkunderlineindexunderlinevirtual]
=== PK_Index_virtual

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-index_guid>>; uniqueidentifier
--
* PK, Unique, Real: 1, 1, 1


[#index-idxunderlineindexunderlinevirtualunderlineunderline1]
=== idx_Index_virtual++__++1

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-parent_RepoObject_guid>>; uniqueidentifier
--
* PK, Unique, Real: 0, 0, 0
* ++FK_Index_virtual__RepoObject++ +
referenced: xref:repo.repoobject.adoc[], xref:repo.repoobject.adoc#index-pkunderlinerepoobject[+PK_RepoObject+]
* is disabled

// end::AntoraIndexList[]

== AntoraMeasureDetails

// tag::AntoraMeasureDetails[]

// end::AntoraMeasureDetails[]

== AntoraMeasureDescriptions



== AntoraParameterList

// tag::AntoraParameterList[]

// end::AntoraParameterList[]

== AntoraXrefCulturesList

// tag::AntoraXrefCulturesList[]
* xref:dhw:sqldb:repo.index_virtual.adoc[] - 
// end::AntoraXrefCulturesList[]

== cultures_count

// tag::cultures_count[]
1
// end::cultures_count[]

== Other tags

source: property.RepoObjectProperty_cross As rop_cross


=== additional_reference_csv

// tag::additional_reference_csv[]

// end::additional_reference_csv[]


=== AdocUspSteps

// tag::adocuspsteps[]

// end::adocuspsteps[]


=== AntoraReferencedList

// tag::antorareferencedlist[]

// end::antorareferencedlist[]


=== AntoraReferencingList

// tag::antorareferencinglist[]
* xref:dhw:sqldb:repo.index_union.adoc[]
* xref:dhw:sqldb:repo.index_virtual_forupdate.adoc[]
* xref:dhw:sqldb:repo.index_virtual_indexpatterncolumnguid.adoc[]
* xref:dhw:sqldb:repo.index_virtual_sysobject.adoc[]
* xref:dhw:sqldb:repo.indexcolumn_virtual_gross.adoc[]
* xref:dhw:sqldb:repo.indexcolumn_virtual_referenced_setpoint.adoc[]
* xref:dhw:sqldb:repo.indexreferencedreferencing.adoc[]
* xref:dhw:sqldb:repo.usp_index_finish.adoc[]
* xref:dhw:sqldb:repo.usp_index_inheritance.adoc[]
* xref:dhw:sqldb:repo.usp_index_virtual_set.adoc[]
// end::antorareferencinglist[]


=== Description

// tag::description[]

// end::description[]


=== exampleUsage

// tag::exampleusage[]

// end::exampleusage[]


=== exampleUsage_2

// tag::exampleusage_2[]

// end::exampleusage_2[]


=== exampleUsage_3

// tag::exampleusage_3[]

// end::exampleusage_3[]


=== exampleUsage_4

// tag::exampleusage_4[]

// end::exampleusage_4[]


=== exampleUsage_5

// tag::exampleusage_5[]

// end::exampleusage_5[]


=== exampleWrong_Usage

// tag::examplewrong_usage[]

// end::examplewrong_usage[]


=== has_execution_plan_issue

// tag::has_execution_plan_issue[]

// end::has_execution_plan_issue[]


=== has_get_referenced_issue

// tag::has_get_referenced_issue[]

// end::has_get_referenced_issue[]


=== has_history

// tag::has_history[]

// end::has_history[]


=== has_history_columns

// tag::has_history_columns[]

// end::has_history_columns[]


=== InheritanceType

// tag::inheritancetype[]

// end::inheritancetype[]


=== is_persistence

// tag::is_persistence[]

// end::is_persistence[]


=== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]

// end::is_persistence_check_duplicate_per_pk[]


=== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]

// end::is_persistence_check_for_empty_source[]


=== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]

// end::is_persistence_delete_changed[]


=== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]

// end::is_persistence_delete_missing[]


=== is_persistence_insert

// tag::is_persistence_insert[]

// end::is_persistence_insert[]


=== is_persistence_truncate

// tag::is_persistence_truncate[]

// end::is_persistence_truncate[]


=== is_persistence_update_changed

// tag::is_persistence_update_changed[]

// end::is_persistence_update_changed[]


=== is_repo_managed

// tag::is_repo_managed[]
0
// end::is_repo_managed[]


=== is_ssas

// tag::is_ssas[]
0
// end::is_ssas[]


=== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


=== MS_Description

// tag::ms_description[]

// end::ms_description[]


=== persistence_source_RepoObject_fullname

// tag::persistence_source_repoobject_fullname[]

// end::persistence_source_repoobject_fullname[]


=== persistence_source_RepoObject_fullname2

// tag::persistence_source_repoobject_fullname2[]

// end::persistence_source_repoobject_fullname2[]


=== persistence_source_RepoObject_guid

// tag::persistence_source_repoobject_guid[]

// end::persistence_source_repoobject_guid[]


=== persistence_source_RepoObject_xref

// tag::persistence_source_repoobject_xref[]

// end::persistence_source_repoobject_xref[]


=== pk_index_guid

// tag::pk_index_guid[]
3690291C-9D61-EB11-84DC-A81E8446D5B0
// end::pk_index_guid[]


=== pk_IndexPatternColumnDatatype

// tag::pk_indexpatterncolumndatatype[]
uniqueidentifier
// end::pk_indexpatterncolumndatatype[]


=== pk_IndexPatternColumnName

// tag::pk_indexpatterncolumnname[]
index_guid
// end::pk_indexpatterncolumnname[]


=== pk_IndexSemanticGroup

// tag::pk_indexsemanticgroup[]

// end::pk_indexsemanticgroup[]


=== ReferencedObjectList

// tag::referencedobjectlist[]

// end::referencedobjectlist[]


=== usp_persistence_RepoObject_guid

// tag::usp_persistence_repoobject_guid[]

// end::usp_persistence_repoobject_guid[]


=== UspExamples

// tag::uspexamples[]

// end::uspexamples[]


=== uspgenerator_usp_id

// tag::uspgenerator_usp_id[]

// end::uspgenerator_usp_id[]


=== UspParameters

// tag::uspparameters[]

// end::uspparameters[]

== Boolean Attributes

source: property.RepoObjectProperty WHERE property_int = 1

// tag::boolean_attributes[]


// end::boolean_attributes[]

== PlantUML diagrams

=== PlantUML Entity

// tag::puml_entity[]
[plantuml, entity-{docname}, svg, subs=macros]
....
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:repo.index_virtual.adoc[]" as repo.Index_virtual << U >> {
  - **index_guid** : (uniqueidentifier)
  - has_managedName : (bit)
  index_name : (nvarchar(128))
  - index_type : (tinyint)
  - is_index_disabled : (bit)
  - is_index_primary_key : (bit)
  - is_index_unique : (bit)
  - parent_RepoObject_guid : (uniqueidentifier)
  referenced_index_guid : (uniqueidentifier)
  RowNumberInReferencing : (int)
  --
}
....

// end::puml_entity[]

=== PlantUML Entity 1 1 FK

// tag::puml_entity_1_1_fk[]
[plantuml, entity_1_1_fk-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:repo.index_virtual.adoc[]" as repo.Index_virtual << U >> {
**PK_Index_virtual**

..
index_guid; uniqueidentifier
--
- idx_Index_virtual__1

..
parent_RepoObject_guid; uniqueidentifier
}

entity "puml-link:dhw:sqldb:repo.indexcolumn_virtual.adoc[]" as repo.IndexColumn_virtual << U >> {
**PK_IndexColumn_unique**

..
index_guid; uniqueidentifier
index_column_id; int
--
- idx_IndexColumn_virtual__1

..
index_guid; uniqueidentifier
--
- idx_IndexColumn_virtual__2

..
RepoObjectColumn_guid; uniqueidentifier
}

entity "puml-link:dhw:sqldb:repo.repoobject.adoc[]" as repo.RepoObject << U >> {
**PK_RepoObject**

..
RepoObject_guid; uniqueidentifier
--
UK_RepoObject__RepoNames

..
RepoObject_schema_name; nvarchar(128)
RepoObject_name; nvarchar(128)
--
UK_RepoObject__SysNames

..
SysObject_schema_name; nvarchar(128)
SysObject_name; nvarchar(128)
--
- idx_RepoObject__1

..
pk_index_guid; uniqueidentifier
}

"repo.Index_virtual::PK_Index_virtual" <-- "repo.IndexColumn_virtual::idx_IndexColumn_virtual__1"
"repo.RepoObject::PK_RepoObject" <-- "repo.Index_virtual::idx_Index_virtual__1"

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_fk[]

=== PlantUML 1 1 ObjectRef

// tag::puml_entity_1_1_objectref[]
[plantuml, entity_1_1_objectref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:repo.index_union.adoc[]" as repo.Index_union << V >> {
  **index_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.index_virtual.adoc[]" as repo.Index_virtual << U >> {
  - **index_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.index_virtual_forupdate.adoc[]" as repo.Index_virtual_ForUpdate << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.index_virtual_indexpatterncolumnguid.adoc[]" as repo.Index_virtual_IndexPatternColumnGuid << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.index_virtual_sysobject.adoc[]" as repo.Index_virtual_SysObject << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.indexcolumn_virtual_gross.adoc[]" as repo.IndexColumn_virtual_gross << V >> {
  - **index_column_id** : (int)
  --
}

entity "puml-link:dhw:sqldb:repo.indexcolumn_virtual_referenced_setpoint.adoc[]" as repo.IndexColumn_virtual_referenced_setpoint << V >> {
  - **index_guid** : (uniqueidentifier)
  - **index_column_id** : (int)
  --
}

entity "puml-link:dhw:sqldb:repo.indexreferencedreferencing.adoc[]" as repo.IndexReferencedReferencing << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_index_finish.adoc[]" as repo.usp_Index_finish << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_index_inheritance.adoc[]" as repo.usp_index_inheritance << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_index_virtual_set.adoc[]" as repo.usp_Index_virtual_set << P >> {
  --
}

repo.Index_virtual <.. repo.Index_union
repo.Index_virtual <.. repo.IndexReferencedReferencing
repo.Index_virtual <.. repo.Index_virtual_SysObject
repo.Index_virtual <.. repo.IndexColumn_virtual_gross
repo.Index_virtual <.. repo.IndexColumn_virtual_referenced_setpoint
repo.Index_virtual <.. repo.usp_index_inheritance
repo.Index_virtual <.. repo.usp_Index_virtual_set
repo.Index_virtual <.. repo.Index_virtual_IndexPatternColumnGuid
repo.Index_virtual <.. repo.usp_Index_finish
repo.Index_virtual <.. repo.Index_virtual_ForUpdate

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_objectref[]

=== PlantUML 30 0 ObjectRef

// tag::puml_entity_30_0_objectref[]
[plantuml, entity_30_0_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:repo.index_virtual.adoc[]" as repo.Index_virtual << U >> {
  - **index_guid** : (uniqueidentifier)
  --
}



footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_30_0_objectref[]

=== PlantUML 0 30 ObjectRef

// tag::puml_entity_0_30_objectref[]
[plantuml, entity_0_30_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:docs.antoranavlistpage_by_schema.adoc[]" as docs.AntoraNavListPage_by_schema << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.antorapage_indexsemanticgroup.adoc[]" as docs.AntoraPage_IndexSemanticGroup << V >> {
  - **page_content** : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:docs.foreignkey_relationscript.adoc[]" as docs.ForeignKey_RelationScript << V >> {
  **referenced_RepoObject_guid** : (uniqueidentifier)
  **referencing_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:docs.ftv_repoobject_reference_plantuml_entityreflist.adoc[]" as docs.ftv_RepoObject_Reference_PlantUml_EntityRefList << IF >> {
  --
}

entity "puml-link:dhw:sqldb:docs.indexsemanticgroup.adoc[]" as docs.IndexSemanticgroup << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.indexsemanticgrouppatterndatatype.adoc[]" as docs.IndexSemanticgroupPatterndatatype << V >> {
  **IndexSemanticGroup** : (nvarchar(512))
  **IndexPatternColumnDatatype** : (nvarchar(4000))
  --
}

entity "puml-link:dhw:sqldb:docs.objectrefcyclic.adoc[]" as docs.ObjectRefCyclic << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.objectrefcyclic_entitylist.adoc[]" as docs.ObjectRefCyclic_EntityList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_adoc.adoc[]" as docs.RepoObject_Adoc << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_adoc_t.adoc[]" as docs.RepoObject_Adoc_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_columnlist.adoc[]" as docs.RepoObject_ColumnList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_columnlist_t.adoc[]" as docs.RepoObject_ColumnList_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_indexlist.adoc[]" as docs.RepoObject_IndexList << V >> {
  **RepoObject_guid** : (uniqueidentifier)
  **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_indexlist_t.adoc[]" as docs.RepoObject_IndexList_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml.adoc[]" as docs.RepoObject_Plantuml << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_entity.adoc[]" as docs.RepoObject_Plantuml_Entity << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_entity_t.adoc[]" as docs.RepoObject_Plantuml_Entity_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_fkreflist.adoc[]" as docs.RepoObject_PlantUml_FkRefList << V >> {
  **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_pumlentityfklist.adoc[]" as docs.RepoObject_PlantUml_PumlEntityFkList << V >> {
  **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_t.adoc[]" as docs.RepoObject_Plantuml_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.schema_entitylist.adoc[]" as docs.Schema_EntityList << V >> {
  - **RepoObject_schema_name** : (nvarchar(128))
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.schema_puml.adoc[]" as docs.Schema_puml << V >> {
  - **RepoSchema_guid** : (uniqueidentifier)
  **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.schema_pumlpartial_fkreflist.adoc[]" as docs.Schema_PumlPartial_FkRefList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport.adoc[]" as docs.usp_AntoraExport << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_objectpartialscontent.adoc[]" as docs.usp_AntoraExport_ObjectPartialsContent << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_objectpuml.adoc[]" as docs.usp_AntoraExport_ObjectPuml << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_repoobject_adoc_t.adoc[]" as docs.usp_PERSIST_RepoObject_Adoc_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_repoobject_columnlist_t.adoc[]" as docs.usp_PERSIST_RepoObject_ColumnList_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_repoobject_indexlist_t.adoc[]" as docs.usp_PERSIST_RepoObject_IndexList_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_repoobject_plantuml_entity_t.adoc[]" as docs.usp_PERSIST_RepoObject_Plantuml_Entity_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_repoobject_plantuml_t.adoc[]" as docs.usp_PERSIST_RepoObject_Plantuml_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty_collect_source_rogross.adoc[]" as property.RepoObjectProperty_Collect_source_ROGross << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **property_name** : (varchar(39))
  --
}

entity "puml-link:dhw:sqldb:property.usp_repoobject_inheritance.adoc[]" as property.usp_RepoObject_Inheritance << P >> {
  --
}

entity "puml-link:dhw:sqldb:property.usp_repoobjectproperty_collect.adoc[]" as property.usp_RepoObjectProperty_collect << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.ftv_repoobject_columreferencerepoobject.adoc[]" as reference.ftv_RepoObject_ColumReferenceRepoObject << IF >> {
  --
}

entity "puml-link:dhw:sqldb:repo.check_indexcolumn_virtual_referenced_setpoint.adoc[]" as repo.check_IndexColumn_virtual_referenced_setpoint << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.foreignkey_gross.adoc[]" as repo.ForeignKey_gross << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.foreignkey_indexes.adoc[]" as repo.ForeignKey_Indexes << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.foreignkey_indexes_union.adoc[]" as repo.ForeignKey_Indexes_union << V >> {
  **ForeignKey_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.foreignkey_indexes_union_t.adoc[]" as repo.ForeignKey_Indexes_union_T << U >> {
  **ForeignKey_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.foreignkey_virtual_indexes.adoc[]" as repo.ForeignKey_virtual_Indexes << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.index_columlist.adoc[]" as repo.Index_ColumList << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.index_columlist_t.adoc[]" as repo.Index_ColumList_T << U >> {
  - **index_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.index_gross.adoc[]" as repo.Index_gross << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.index_indexpattern.adoc[]" as repo.Index_IndexPattern << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.index_referencing_indexpatterncolumnguid.adoc[]" as repo.Index_referencing_IndexPatternColumnGuid << V >> {
  **source_index_guid** : (uniqueidentifier)
  **referencing_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.index_settings_forupdate.adoc[]" as repo.Index_Settings_ForUpdate << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.index_sqlconstraint_pkuq.adoc[]" as repo.Index_SqlConstraint_PkUq << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.index_union.adoc[]" as repo.Index_union << V >> {
  **index_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.index_virtual.adoc[]" as repo.Index_virtual << U >> {
  - **index_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.index_virtual_forupdate.adoc[]" as repo.Index_virtual_ForUpdate << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.index_virtual_indexpatterncolumnguid.adoc[]" as repo.Index_virtual_IndexPatternColumnGuid << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.index_virtual_sysobject.adoc[]" as repo.Index_virtual_SysObject << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.indexcolumn_referencedreferencing_hasfullcolumnsinreferencing.adoc[]" as repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing << V >> {
  - **index_guid** : (uniqueidentifier)
  - **index_column_id** : (int)
  **RowNumberInReferencing** : (bigint)
  --
}

entity "puml-link:dhw:sqldb:repo.indexcolumn_referencedreferencing_hasfullcolumnsinreferencing_check.adoc[]" as repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_check << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.indexcolumn_referencedreferencing_hasfullcolumnsinreferencing_t.adoc[]" as repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T << U >> {
  **index_guid** : (uniqueidentifier)
  - **index_column_id** : (int)
  **RowNumberInReferencing** : (bigint)
  --
}

entity "puml-link:dhw:sqldb:repo.indexcolumn_union.adoc[]" as repo.IndexColumn_union << V >> {
  **index_guid** : (uniqueidentifier)
  - **index_column_id** : (int)
  --
}

entity "puml-link:dhw:sqldb:repo.indexcolumn_union_t.adoc[]" as repo.IndexColumn_union_T << U >> {
  - **index_guid** : (uniqueidentifier)
  - **index_column_id** : (int)
  --
}

entity "puml-link:dhw:sqldb:repo.indexcolumn_virtual_gross.adoc[]" as repo.IndexColumn_virtual_gross << V >> {
  - **index_column_id** : (int)
  --
}

entity "puml-link:dhw:sqldb:repo.indexcolumn_virtual_referenced_setpoint.adoc[]" as repo.IndexColumn_virtual_referenced_setpoint << V >> {
  - **index_guid** : (uniqueidentifier)
  - **index_column_id** : (int)
  --
}

entity "puml-link:dhw:sqldb:repo.indexreferencedreferencing.adoc[]" as repo.IndexReferencedReferencing << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.indexreferencedreferencing_hasfullcolumnsinreferencing.adoc[]" as repo.IndexReferencedReferencing_HasFullColumnsInReferencing << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_columnlist.adoc[]" as repo.RepoObject_ColumnList << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_gross2.adoc[]" as repo.RepoObject_gross2 << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_related_fk_union.adoc[]" as repo.RepoObject_related_FK_union << V >> {
  **RepoObject_guid** : (uniqueidentifier)
  **included_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_sat2.adoc[]" as repo.RepoObject_sat2 << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_sat2_t.adoc[]" as repo.RepoObject_sat2_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_sqlcreatetable.adoc[]" as repo.RepoObject_SqlCreateTable << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn_gross2.adoc[]" as repo.RepoObjectColumn_gross2 << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_index_finish.adoc[]" as repo.usp_Index_finish << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_index_foreignkey.adoc[]" as repo.usp_Index_ForeignKey << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_index_inheritance.adoc[]" as repo.usp_index_inheritance << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_index_settings.adoc[]" as repo.usp_Index_Settings << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_index_virtual_set.adoc[]" as repo.usp_Index_virtual_set << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_main.adoc[]" as repo.usp_main << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_persist_foreignkey_indexes_union_t.adoc[]" as repo.usp_PERSIST_ForeignKey_Indexes_union_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_persist_index_columlist_t.adoc[]" as repo.usp_PERSIST_Index_ColumList_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_persist_indexcolumn_referencedreferencing_hasfullcolumnsinreferencing_t.adoc[]" as repo.usp_PERSIST_IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_persist_indexcolumn_union_t.adoc[]" as repo.usp_PERSIST_IndexColumn_union_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_persist_repoobject_sat2_t.adoc[]" as repo.usp_PERSIST_RepoObject_sat2_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.generatoruspstep_persistence_src.adoc[]" as uspgenerator.GeneratorUspStep_Persistence_src << V >> {
  - **usp_id** : (int)
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.usp_generatorusp_insert_update_persistence.adoc[]" as uspgenerator.usp_GeneratorUsp_insert_update_persistence << P >> {
  --
}

docs.ftv_RepoObject_Reference_PlantUml_EntityRefList <.. docs.RepoObject_Plantuml
docs.IndexSemanticgroup <.. docs.AntoraPage_IndexSemanticGroup
docs.IndexSemanticgroupPatterndatatype <.. docs.IndexSemanticgroup
docs.ObjectRefCyclic_EntityList <.. docs.ObjectRefCyclic
docs.RepoObject_Adoc <.. docs.RepoObject_Adoc_T
docs.RepoObject_Adoc <.. docs.usp_PERSIST_RepoObject_Adoc_T
docs.REpoObject_Adoc_T <.. docs.usp_PERSIST_RepoObject_Adoc_T
docs.RepoObject_ColumnList <.. docs.usp_PERSIST_RepoObject_ColumnList_T
docs.RepoObject_ColumnList <.. docs.RepoObject_ColumnList_T
docs.RepoObject_ColumnList_T <.. docs.RepoObject_Plantuml_Entity
docs.RepoObject_ColumnList_T <.. docs.usp_PERSIST_RepoObject_ColumnList_T
docs.RepoObject_ColumnList_T <.. docs.RepoObject_Adoc
docs.RepoObject_IndexList <.. docs.usp_PERSIST_RepoObject_IndexList_T
docs.RepoObject_IndexList <.. docs.RepoObject_IndexList_T
docs.RepoObject_IndexList_T <.. docs.usp_PERSIST_RepoObject_IndexList_T
docs.RepoObject_IndexList_T <.. docs.RepoObject_Plantuml_Entity
docs.RepoObject_IndexList_T <.. docs.RepoObject_Adoc
docs.RepoObject_Plantuml <.. docs.usp_PERSIST_RepoObject_Plantuml_T
docs.RepoObject_Plantuml <.. docs.RepoObject_Plantuml_T
docs.RepoObject_Plantuml_Entity <.. docs.RepoObject_Plantuml_Entity_T
docs.RepoObject_Plantuml_Entity <.. docs.usp_PERSIST_RepoObject_Plantuml_Entity_T
docs.RepoObject_Plantuml_Entity_T <.. docs.RepoObject_Adoc
docs.RepoObject_Plantuml_Entity_T <.. docs.usp_PERSIST_RepoObject_Plantuml_Entity_T
docs.RepoObject_Plantuml_Entity_T <.. docs.ftv_RepoObject_Reference_PlantUml_EntityRefList
docs.RepoObject_Plantuml_Entity_T <.. docs.RepoObject_PlantUml_PumlEntityFkList
docs.RepoObject_Plantuml_Entity_T <.. docs.ObjectRefCyclic_EntityList
docs.RepoObject_Plantuml_Entity_T <.. docs.Schema_EntityList
docs.RepoObject_PlantUml_FkRefList <.. docs.RepoObject_Plantuml
docs.RepoObject_PlantUml_PumlEntityFkList <.. docs.RepoObject_Plantuml
docs.RepoObject_Plantuml_T <.. docs.RepoObject_Adoc
docs.RepoObject_Plantuml_T <.. docs.usp_PERSIST_RepoObject_Plantuml_T
docs.Schema_EntityList <.. docs.Schema_puml
docs.Schema_puml <.. docs.AntoraNavListPage_by_schema
docs.Schema_PumlPartial_FkRefList <.. docs.Schema_puml
docs.usp_AntoraExport_ObjectPartialsContent <.. docs.usp_AntoraExport
docs.usp_AntoraExport_ObjectPuml <.. docs.usp_AntoraExport
docs.usp_PERSIST_RepoObject_Adoc_T <.. docs.usp_AntoraExport_ObjectPartialsContent
docs.usp_PERSIST_RepoObject_ColumnList_T <.. docs.usp_AntoraExport_ObjectPartialsContent
docs.usp_PERSIST_RepoObject_IndexList_T <.. docs.usp_AntoraExport_ObjectPartialsContent
docs.usp_PERSIST_RepoObject_Plantuml_Entity_T <.. docs.usp_AntoraExport_ObjectPuml
docs.usp_PERSIST_RepoObject_Plantuml_T <.. docs.usp_AntoraExport_ObjectPuml
property.RepoObjectProperty_Collect_source_ROGross <.. property.usp_RepoObjectProperty_collect
property.usp_RepoObject_Inheritance <.. repo.usp_main
property.usp_RepoObjectProperty_collect <.. repo.usp_main
property.usp_RepoObjectProperty_collect <.. property.usp_RepoObject_Inheritance
repo.ForeignKey_gross <.. docs.RepoObject_IndexList
repo.ForeignKey_Indexes <.. repo.ForeignKey_Indexes_union
repo.ForeignKey_Indexes <.. repo.usp_Index_ForeignKey
repo.ForeignKey_Indexes_union <.. repo.usp_PERSIST_ForeignKey_Indexes_union_T
repo.ForeignKey_Indexes_union <.. repo.ForeignKey_Indexes_union_T
repo.ForeignKey_Indexes_union_T <.. repo.usp_Index_finish
repo.ForeignKey_Indexes_union_T <.. docs.Schema_PumlPartial_FkRefList
repo.ForeignKey_Indexes_union_T <.. repo.usp_PERSIST_ForeignKey_Indexes_union_T
repo.ForeignKey_Indexes_union_T <.. docs.RepoObject_PlantUml_FkRefList
repo.ForeignKey_Indexes_union_T <.. repo.RepoObject_related_FK_union
repo.ForeignKey_Indexes_union_T <.. repo.ForeignKey_gross
repo.ForeignKey_Indexes_union_T <.. docs.ForeignKey_RelationScript
repo.ForeignKey_virtual_Indexes <.. repo.ForeignKey_Indexes_union
repo.Index_ColumList <.. repo.usp_PERSIST_Index_ColumList_T
repo.Index_ColumList <.. repo.Index_ColumList_T
repo.Index_ColumList_T <.. repo.Index_gross
repo.Index_ColumList_T <.. repo.usp_PERSIST_Index_ColumList_T
repo.Index_ColumList_T <.. repo.Index_SqlConstraint_PkUq
repo.Index_ColumList_T <.. uspgenerator.GeneratorUspStep_Persistence_src
repo.Index_gross <.. repo.ForeignKey_gross
repo.Index_gross <.. docs.IndexSemanticgroupPatterndatatype
repo.Index_gross <.. docs.RepoObject_IndexList
repo.Index_gross <.. repo.usp_Index_finish
repo.Index_gross <.. repo.RepoObject_SqlCreateTable
repo.Index_gross <.. repo.ForeignKey_virtual_Indexes
repo.Index_gross <.. repo.ForeignKey_Indexes
repo.Index_gross <.. repo.usp_Index_virtual_set
repo.Index_gross <.. repo.usp_index_inheritance
repo.Index_IndexPattern <.. repo.usp_Index_Settings
repo.Index_referencing_IndexPatternColumnGuid <.. repo.IndexReferencedReferencing_HasFullColumnsInReferencing
repo.Index_SqlConstraint_PkUq <.. repo.RepoObject_SqlCreateTable
repo.Index_union <.. repo.Index_Settings_ForUpdate
repo.Index_union <.. repo.usp_Index_finish
repo.Index_union <.. repo.Index_gross
repo.Index_union <.. repo.Index_SqlConstraint_PkUq
repo.Index_union <.. repo.IndexReferencedReferencing
repo.Index_virtual <.. repo.IndexColumn_virtual_gross
repo.Index_virtual <.. repo.Index_virtual_SysObject
repo.Index_virtual <.. repo.Index_union
repo.Index_virtual <.. repo.IndexReferencedReferencing
repo.Index_virtual <.. repo.IndexColumn_virtual_referenced_setpoint
repo.Index_virtual <.. repo.usp_index_inheritance
repo.Index_virtual <.. repo.usp_Index_virtual_set
repo.Index_virtual <.. repo.Index_virtual_IndexPatternColumnGuid
repo.Index_virtual <.. repo.usp_Index_finish
repo.Index_virtual <.. repo.Index_virtual_ForUpdate
repo.Index_virtual_ForUpdate <.. repo.usp_index_inheritance
repo.Index_virtual_IndexPatternColumnGuid <.. repo.Index_union
repo.Index_virtual_IndexPatternColumnGuid <.. repo.usp_index_inheritance
repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing <.. repo.usp_PERSIST_IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T
repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing <.. repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T
repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T <.. repo.IndexColumn_virtual_referenced_setpoint
repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T <.. repo.Index_referencing_IndexPatternColumnGuid
repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T <.. repo.IndexReferencedReferencing_HasFullColumnsInReferencing
repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T <.. repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_check
repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T <.. repo.usp_PERSIST_IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T
repo.IndexColumn_union <.. repo.usp_PERSIST_IndexColumn_union_T
repo.IndexColumn_union <.. repo.IndexColumn_union_T
repo.IndexColumn_union_T <.. repo.Index_ColumList
repo.IndexColumn_union_T <.. repo.Index_IndexPattern
repo.IndexColumn_union_T <.. repo.usp_PERSIST_IndexColumn_union_T
repo.IndexColumn_union_T <.. repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing
repo.IndexColumn_union_T <.. repo.RepoObjectColumn_gross2
repo.IndexColumn_virtual_gross <.. repo.IndexColumn_union
repo.IndexColumn_virtual_referenced_setpoint <.. repo.check_IndexColumn_virtual_referenced_setpoint
repo.IndexColumn_virtual_referenced_setpoint <.. repo.usp_index_inheritance
repo.IndexReferencedReferencing <.. repo.IndexReferencedReferencing_HasFullColumnsInReferencing
repo.IndexReferencedReferencing_HasFullColumnsInReferencing <.. repo.usp_index_inheritance
repo.RepoObject_ColumnList <.. repo.RepoObject_SqlCreateTable
repo.RepoObject_ColumnList <.. repo.RepoObject_sat2
repo.RepoObject_ColumnList <.. repo.RepoObject_gross2
repo.RepoObject_gross2 <.. uspgenerator.GeneratorUspStep_Persistence_src
repo.RepoObject_related_FK_union <.. docs.RepoObject_PlantUml_PumlEntityFkList
repo.RepoObject_related_FK_union <.. docs.RepoObject_PlantUml_FkRefList
repo.RepoObject_sat2 <.. repo.RepoObject_sat2_T
repo.RepoObject_sat2 <.. repo.usp_PERSIST_RepoObject_sat2_T
repo.RepoObject_sat2_T <.. repo.usp_PERSIST_RepoObject_sat2_T
repo.RepoObject_sat2_T <.. docs.RepoObject_Adoc
repo.RepoObject_sat2_T <.. property.RepoObjectProperty_Collect_source_ROGross
repo.RepoObject_SqlCreateTable <.. reference.ftv_RepoObject_ColumReferenceRepoObject
repo.RepoObjectColumn_gross2 <.. uspgenerator.usp_GeneratorUsp_insert_update_persistence
repo.RepoObjectColumn_gross2 <.. repo.RepoObject_ColumnList
repo.RepoObjectColumn_gross2 <.. docs.RepoObject_ColumnList
repo.usp_Index_finish <.. repo.usp_index_inheritance
repo.usp_Index_finish <.. repo.usp_Index_ForeignKey
repo.usp_Index_ForeignKey <.. repo.usp_main
repo.usp_index_inheritance <.. repo.usp_main
repo.usp_Index_Settings <.. repo.usp_Index_finish
repo.usp_Index_virtual_set <.. repo.usp_Index_ForeignKey
repo.usp_PERSIST_ForeignKey_Indexes_union_T <.. repo.usp_Index_ForeignKey
repo.usp_PERSIST_Index_ColumList_T <.. repo.usp_Index_finish
repo.usp_PERSIST_IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T <.. repo.usp_index_inheritance
repo.usp_PERSIST_IndexColumn_union_T <.. repo.usp_Index_finish
repo.usp_PERSIST_RepoObject_sat2_T <.. repo.usp_main
uspgenerator.GeneratorUspStep_Persistence_src <.. uspgenerator.usp_GeneratorUsp_insert_update_persistence
uspgenerator.usp_GeneratorUsp_insert_update_persistence <.. repo.usp_main

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_0_30_objectref[]

=== PlantUML 1 1 ColumnRef

// tag::puml_entity_1_1_colref[]
[plantuml, entity_1_1_colref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:repo.index_union.adoc[]" as repo.Index_union << V >> {
  **index_guid** : (uniqueidentifier)
  index_name : (nvarchar(450))
  index_type : (tinyint)
  IndexPatternColumnGuid : (varchar(8000))
  is_index_disabled : (bit)
  is_index_primary_key : (bit)
  is_index_real : (bit)
  is_index_unique : (bit)
  parent_RepoObject_guid : (uniqueidentifier)
  referenced_index_guid : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.index_virtual.adoc[]" as repo.Index_virtual << U >> {
  - **index_guid** : (uniqueidentifier)
  - has_managedName : (bit)
  index_name : (nvarchar(128))
  - index_type : (tinyint)
  - is_index_disabled : (bit)
  - is_index_primary_key : (bit)
  - is_index_unique : (bit)
  - parent_RepoObject_guid : (uniqueidentifier)
  referenced_index_guid : (uniqueidentifier)
  RowNumberInReferencing : (int)
  --
}

entity "puml-link:dhw:sqldb:repo.index_virtual_forupdate.adoc[]" as repo.Index_virtual_ForUpdate << V >> {
  - has_managedName : (bit)
  - index_guid : (uniqueidentifier)
  index_name : (nvarchar(128))
  - index_type : (tinyint)
  IndexPatternColumnDatatype : (nvarchar(4000))
  IndexPatternColumnName : (nvarchar(4000))
  IndexSemanticGroup : (nvarchar(512))
  - is_index_disabled : (bit)
  - is_index_primary_key : (bit)
  - is_index_unique : (bit)
  is_persistence : (bit)
  is_repo_managed : (bit)
  - parent_RepoObject_guid : (uniqueidentifier)
  referenced_index_guid : (uniqueidentifier)
  - RepoObject_fullname : (nvarchar(261))
  - RepoObject_fullname2 : (nvarchar(257))
  RowNumberInReferencing : (int)
  - SysObject_fullname : (nvarchar(261))
  - SysObject_fullname2 : (nvarchar(257))
  --
}

entity "puml-link:dhw:sqldb:repo.index_virtual_indexpatterncolumnguid.adoc[]" as repo.Index_virtual_IndexPatternColumnGuid << V >> {
  ColumnsPerIndex : (int)
  - index_guid : (uniqueidentifier)
  IndexPatternColumnGuid : (varchar(8000))
  parent_RepoObject_guid : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.index_virtual_sysobject.adoc[]" as repo.Index_virtual_SysObject << V >> {
  - index_guid : (uniqueidentifier)
  index_name : (nvarchar(128))
  IndexPatternColumnDatatype : (nvarchar(4000))
  IndexPatternColumnName : (nvarchar(4000))
  IndexSemanticGroup : (nvarchar(512))
  - is_index_disabled : (bit)
  - is_index_primary_key : (bit)
  - is_index_unique : (bit)
  - parent_RepoObject_guid : (uniqueidentifier)
  pk_index_guid : (uniqueidentifier)
  referenced_index_guid : (uniqueidentifier)
  SysObject_id : (int)
  - SysObject_name : (nvarchar(128))
  - SysObject_schema_name : (nvarchar(128))
  SysObject_type : (char(2))
  --
}

entity "puml-link:dhw:sqldb:repo.indexcolumn_virtual_gross.adoc[]" as repo.IndexColumn_virtual_gross << V >> {
  - **index_column_id** : (int)
  column_user_type_fullname : (nvarchar(128))
  - index_guid : (uniqueidentifier)
  index_name : (nvarchar(128))
  - is_descending_key : (bit)
  - is_index_primary_key : (bit)
  is_index_real : (bit)
  - is_index_unique : (bit)
  - Object_column_name : (nvarchar(128))
  parent_Object_fullname : (nvarchar(261))
  parent_Object_name : (nvarchar(128))
  - parent_RepoObject_guid : (uniqueidentifier)
  parent_schema_name : (nvarchar(128))
  - RepoObjectColumn_guid : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.indexcolumn_virtual_referenced_setpoint.adoc[]" as repo.IndexColumn_virtual_referenced_setpoint << V >> {
  - **index_guid** : (uniqueidentifier)
  - **index_column_id** : (int)
  is_descending_key : (bit)
  referenced_index_guid : (uniqueidentifier)
  referenced_RepoObject_guid : (uniqueidentifier)
  referenced_RepoObjectColumn_guid : (uniqueidentifier)
  referencing_RepoObject_guid : (uniqueidentifier)
  referencing_RepoObjectColumn_guid : (uniqueidentifier)
  RowNumberInReferencing : (int)
  --
}

entity "puml-link:dhw:sqldb:repo.indexreferencedreferencing.adoc[]" as repo.IndexReferencedReferencing << V >> {
  referenced_index_guid : (uniqueidentifier)
  - referenced_RepoObject_guid : (uniqueidentifier)
  - referencing_RepoObject_guid : (uniqueidentifier)
  RowNumberInReferencing_Target : (int)
  source_index_guid : (uniqueidentifier)
  source_index_type : (tinyint)
  --
}

entity "puml-link:dhw:sqldb:repo.usp_index_finish.adoc[]" as repo.usp_Index_finish << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_index_inheritance.adoc[]" as repo.usp_index_inheritance << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_index_virtual_set.adoc[]" as repo.usp_Index_virtual_set << P >> {
  --
}

repo.Index_virtual <.. repo.Index_union
repo.Index_virtual <.. repo.IndexReferencedReferencing
repo.Index_virtual <.. repo.Index_virtual_SysObject
repo.Index_virtual <.. repo.IndexColumn_virtual_gross
repo.Index_virtual <.. repo.IndexColumn_virtual_referenced_setpoint
repo.Index_virtual <.. repo.usp_index_inheritance
repo.Index_virtual <.. repo.usp_Index_virtual_set
repo.Index_virtual <.. repo.Index_virtual_IndexPatternColumnGuid
repo.Index_virtual <.. repo.usp_Index_finish
repo.Index_virtual <.. repo.Index_virtual_ForUpdate
"repo.Index_virtual::has_managedName" <-- "repo.Index_virtual_ForUpdate::has_managedName"
"repo.Index_virtual::index_guid" <-- "repo.Index_virtual_ForUpdate::index_guid"
"repo.Index_virtual::index_guid" <-- "repo.Index_virtual_SysObject::index_guid"
"repo.Index_virtual::index_guid" <-- "repo.IndexColumn_virtual_referenced_setpoint::index_guid"
"repo.Index_virtual::index_guid" <-- "repo.Index_virtual_IndexPatternColumnGuid::index_guid"
"repo.Index_virtual::index_name" <-- "repo.Index_virtual_SysObject::index_name"
"repo.Index_virtual::index_name" <-- "repo.IndexColumn_virtual_gross::index_name"
"repo.Index_virtual::index_name" <-- "repo.Index_virtual_ForUpdate::index_name"
"repo.Index_virtual::index_type" <-- "repo.Index_virtual_ForUpdate::index_type"
"repo.Index_virtual::is_index_disabled" <-- "repo.Index_virtual_ForUpdate::is_index_disabled"
"repo.Index_virtual::is_index_disabled" <-- "repo.Index_virtual_SysObject::is_index_disabled"
"repo.Index_virtual::is_index_primary_key" <-- "repo.IndexColumn_virtual_gross::is_index_primary_key"
"repo.Index_virtual::is_index_primary_key" <-- "repo.Index_virtual_SysObject::is_index_primary_key"
"repo.Index_virtual::is_index_primary_key" <-- "repo.Index_virtual_ForUpdate::is_index_primary_key"
"repo.Index_virtual::is_index_unique" <-- "repo.Index_virtual_ForUpdate::is_index_unique"
"repo.Index_virtual::is_index_unique" <-- "repo.IndexColumn_virtual_gross::is_index_unique"
"repo.Index_virtual::is_index_unique" <-- "repo.Index_virtual_SysObject::is_index_unique"
"repo.Index_virtual::parent_RepoObject_guid" <-- "repo.Index_virtual_SysObject::parent_RepoObject_guid"
"repo.Index_virtual::parent_RepoObject_guid" <-- "repo.IndexColumn_virtual_gross::parent_RepoObject_guid"
"repo.Index_virtual::parent_RepoObject_guid" <-- "repo.Index_virtual_IndexPatternColumnGuid::parent_RepoObject_guid"
"repo.Index_virtual::parent_RepoObject_guid" <-- "repo.Index_virtual_ForUpdate::parent_RepoObject_guid"
"repo.Index_virtual::referenced_index_guid" <-- "repo.Index_virtual_ForUpdate::referenced_index_guid"
"repo.Index_virtual::referenced_index_guid" <-- "repo.IndexColumn_virtual_referenced_setpoint::referenced_index_guid"
"repo.Index_virtual::referenced_index_guid" <-- "repo.Index_virtual_SysObject::referenced_index_guid"
"repo.Index_virtual::referenced_index_guid" <-- "repo.IndexReferencedReferencing::referenced_index_guid"
"repo.Index_virtual::RowNumberInReferencing" <-- "repo.IndexReferencedReferencing::RowNumberInReferencing_Target"
"repo.Index_virtual::RowNumberInReferencing" <-- "repo.IndexColumn_virtual_referenced_setpoint::RowNumberInReferencing"
"repo.Index_virtual::RowNumberInReferencing" <-- "repo.Index_virtual_ForUpdate::RowNumberInReferencing"

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_colref[]


== sql_modules_definition

// tag::sql_modules_definition[]
[%collapsible]
=======
[source,sql,numbered,indent=0]
----

----
=======
// end::sql_modules_definition[]


