// tag::HeaderFullDisplayName[]
= repo_sys.ColumnReference - V
// end::HeaderFullDisplayName[]

== existing_properties

// tag::existing_properties[]

:ExistsProperty--antorareferencedlist:
:ExistsProperty--has_execution_plan_issue:
:ExistsProperty--is_repo_managed:
:ExistsProperty--is_ssas:
:ExistsProperty--referencedobjectlist:
:ExistsProperty--sql_modules_definition:
:ExistsProperty--FK:
:ExistsProperty--Columns:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
5C90291C-9D61-EB11-84DC-A81E8446D5B0
// end::RepoObject_guid[]

== RepoObject_FullDisplayName2

// tag::RepoObject_FullDisplayName2[]
repo_sys.ColumnReference
// end::RepoObject_FullDisplayName2[]

== SysObject_type

// tag::SysObject_type[]
V 
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
view
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
724913654
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2021-08-17 19:58:22
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]
[discrete]
== _


[#column-isunderlineallunderlinecolumnsunderlinefound]
=== is_all_columns_found

[cols="d,8a,m,m,m"]
|===
|
|is_all_columns_found
|bit
|NOT NULL
|
|===


[#column-isunderlineambiguous]
=== is_ambiguous

[cols="d,8a,m,m,m"]
|===
|
|is_ambiguous
|bit
|NOT NULL
|
|===


[#column-isunderlinecallerunderlinedependent]
=== is_caller_dependent

[cols="d,8a,m,m,m"]
|===
|
|is_caller_dependent
|bit
|NOT NULL
|
|===


[#column-isunderlineincomplete]
=== is_incomplete

[cols="d,8a,m,m,m"]
|===
|
|is_incomplete
|bit
|NOT NULL
|
|===


[#column-isunderlineinsertunderlineall]
=== is_insert_all

[cols="d,8a,m,m,m"]
|===
|
|is_insert_all
|bit
|NOT NULL
|
|===


[#column-isunderlineselectunderlineall]
=== is_select_all

[cols="d,8a,m,m,m"]
|===
|
|is_select_all
|bit
|NOT NULL
|
|===


[#column-isunderlineselected]
=== is_selected

[cols="d,8a,m,m,m"]
|===
|
|is_selected
|bit
|NOT NULL
|
|===


[#column-isunderlineupdated]
=== is_updated

[cols="d,8a,m,m,m"]
|===
|
|is_updated
|bit
|NOT NULL
|
|===


[#column-referencedunderlineclass]
=== referenced_class

[cols="d,8a,m,m,m"]
|===
|
|referenced_class
|tinyint
|NULL
|
|===


[#column-referencedunderlineclassunderlinedesc]
=== referenced_class_desc

[cols="d,8a,m,m,m"]
|===
|
|referenced_class_desc
|nvarchar(60)
|NULL
|
|===


[#column-referencedunderlinedatabaseunderlinename]
=== referenced_database_name

[cols="d,8a,m,m,m"]
|===
|
|referenced_database_name
|nvarchar(128)
|NULL
|
|===


[#column-referencedunderlineentityunderlinename]
=== referenced_entity_name

[cols="d,8a,m,m,m"]
|===
|
|referenced_entity_name
|nvarchar(128)
|NULL
|
|===


[#column-referencedunderlineid]
=== referenced_id

[cols="d,8a,m,m,m"]
|===
|
|referenced_id
|int
|NULL
|
|===


[#column-referencedunderlineminorunderlineid]
=== referenced_minor_id

[cols="d,8a,m,m,m"]
|===
|
|referenced_minor_id
|int
|NULL
|
|===


[#column-referencedunderlineminorunderlinename]
=== referenced_minor_name

[cols="d,8a,m,m,m"]
|===
|
|referenced_minor_name
|nvarchar(128)
|NULL
|
|===


[#column-referencedunderlineschemaunderlinename]
=== referenced_schema_name

[cols="d,8a,m,m,m"]
|===
|
|referenced_schema_name
|nvarchar(128)
|NULL
|
|===


[#column-referencedunderlineserverunderlinename]
=== referenced_server_name

[cols="d,8a,m,m,m"]
|===
|
|referenced_server_name
|nvarchar(128)
|NULL
|
|===


[#column-referencingunderlineminorunderlineid]
=== referencing_minor_id

[cols="d,8a,m,m,m"]
|===
|
|referencing_minor_id
|int
|NULL
|
|===


[#column-sysobjectunderlinefullunderlinename]
=== SysObject_full_name

[cols="d,8a,m,m,m"]
|===
|
|SysObject_full_name
|nvarchar(517)
|NOT NULL
|
|===

.Referenced Columns
--
* xref:repo_sys.sysobject.adoc#column-sysobjectunderlinefullname[+repo_sys.SysObject.SysObject_fullname+]
--


// end::AntoraColumnDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]



















// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]
|
|<<column-isunderlineallunderlinecolumnsunderlinefound>>
|bit
|NOT NULL
|

|
|<<column-isunderlineambiguous>>
|bit
|NOT NULL
|

|
|<<column-isunderlinecallerunderlinedependent>>
|bit
|NOT NULL
|

|
|<<column-isunderlineincomplete>>
|bit
|NOT NULL
|

|
|<<column-isunderlineinsertunderlineall>>
|bit
|NOT NULL
|

|
|<<column-isunderlineselectunderlineall>>
|bit
|NOT NULL
|

|
|<<column-isunderlineselected>>
|bit
|NOT NULL
|

|
|<<column-isunderlineupdated>>
|bit
|NOT NULL
|

|
|<<column-referencedunderlineclass>>
|tinyint
|NULL
|

|
|<<column-referencedunderlineclassunderlinedesc>>
|nvarchar(60)
|NULL
|

|
|<<column-referencedunderlinedatabaseunderlinename>>
|nvarchar(128)
|NULL
|

|
|<<column-referencedunderlineentityunderlinename>>
|nvarchar(128)
|NULL
|

|
|<<column-referencedunderlineid>>
|int
|NULL
|

|
|<<column-referencedunderlineminorunderlineid>>
|int
|NULL
|

|
|<<column-referencedunderlineminorunderlinename>>
|nvarchar(128)
|NULL
|

|
|<<column-referencedunderlineschemaunderlinename>>
|nvarchar(128)
|NULL
|

|
|<<column-referencedunderlineserverunderlinename>>
|nvarchar(128)
|NULL
|

|
|<<column-referencingunderlineminorunderlineid>>
|int
|NULL
|

|
|<<column-sysobjectunderlinefullunderlinename>>
|nvarchar(517)
|NOT NULL
|

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

// end::AntoraIndexList[]

== AntoraMeasureDetails

// tag::AntoraMeasureDetails[]

// end::AntoraMeasureDetails[]

== AntoraMeasureDescriptions



== AntoraParameterList

// tag::AntoraParameterList[]

// end::AntoraParameterList[]

== AntoraXrefCulturesList

// tag::AntoraXrefCulturesList[]
* xref:dhw:sqldb:repo_sys.columnreference.adoc[] - 
// end::AntoraXrefCulturesList[]

== cultures_count

// tag::cultures_count[]
1
// end::cultures_count[]

== Other tags

source: property.RepoObjectProperty_cross As rop_cross


=== additional_reference_csv

// tag::additional_reference_csv[]

// end::additional_reference_csv[]


=== AdocUspSteps

// tag::adocuspsteps[]

// end::adocuspsteps[]


=== AntoraReferencedList

// tag::antorareferencedlist[]
* xref:dhw:sqldb:repo_sys.sysobject.adoc[]
* xref:dhw:sqldb:sys_dwh.dm_sql_referenced_entities.adoc[]
// end::antorareferencedlist[]


=== AntoraReferencingList

// tag::antorareferencinglist[]

// end::antorareferencinglist[]


=== Description

// tag::description[]

// end::description[]


=== exampleUsage

// tag::exampleusage[]

// end::exampleusage[]


=== exampleUsage_2

// tag::exampleusage_2[]

// end::exampleusage_2[]


=== exampleUsage_3

// tag::exampleusage_3[]

// end::exampleusage_3[]


=== exampleUsage_4

// tag::exampleusage_4[]

// end::exampleusage_4[]


=== exampleUsage_5

// tag::exampleusage_5[]

// end::exampleusage_5[]


=== exampleWrong_Usage

// tag::examplewrong_usage[]

// end::examplewrong_usage[]


=== has_execution_plan_issue

// tag::has_execution_plan_issue[]
1
// end::has_execution_plan_issue[]


=== has_get_referenced_issue

// tag::has_get_referenced_issue[]

// end::has_get_referenced_issue[]


=== has_history

// tag::has_history[]

// end::has_history[]


=== has_history_columns

// tag::has_history_columns[]

// end::has_history_columns[]


=== InheritanceType

// tag::inheritancetype[]

// end::inheritancetype[]


=== is_persistence

// tag::is_persistence[]

// end::is_persistence[]


=== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]

// end::is_persistence_check_duplicate_per_pk[]


=== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]

// end::is_persistence_check_for_empty_source[]


=== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]

// end::is_persistence_delete_changed[]


=== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]

// end::is_persistence_delete_missing[]


=== is_persistence_insert

// tag::is_persistence_insert[]

// end::is_persistence_insert[]


=== is_persistence_truncate

// tag::is_persistence_truncate[]

// end::is_persistence_truncate[]


=== is_persistence_update_changed

// tag::is_persistence_update_changed[]

// end::is_persistence_update_changed[]


=== is_repo_managed

// tag::is_repo_managed[]
0
// end::is_repo_managed[]


=== is_ssas

// tag::is_ssas[]
0
// end::is_ssas[]


=== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


=== MS_Description

// tag::ms_description[]

// end::ms_description[]


=== persistence_source_RepoObject_fullname

// tag::persistence_source_repoobject_fullname[]

// end::persistence_source_repoobject_fullname[]


=== persistence_source_RepoObject_fullname2

// tag::persistence_source_repoobject_fullname2[]

// end::persistence_source_repoobject_fullname2[]


=== persistence_source_RepoObject_guid

// tag::persistence_source_repoobject_guid[]

// end::persistence_source_repoobject_guid[]


=== persistence_source_RepoObject_xref

// tag::persistence_source_repoobject_xref[]

// end::persistence_source_repoobject_xref[]


=== pk_index_guid

// tag::pk_index_guid[]

// end::pk_index_guid[]


=== pk_IndexPatternColumnDatatype

// tag::pk_indexpatterncolumndatatype[]

// end::pk_indexpatterncolumndatatype[]


=== pk_IndexPatternColumnName

// tag::pk_indexpatterncolumnname[]

// end::pk_indexpatterncolumnname[]


=== pk_IndexSemanticGroup

// tag::pk_indexsemanticgroup[]

// end::pk_indexsemanticgroup[]


=== ReferencedObjectList

// tag::referencedobjectlist[]
* [repo_sys].[SysObject]
* [sys_dwh].[dm_sql_referenced_entities]
// end::referencedobjectlist[]


=== usp_persistence_RepoObject_guid

// tag::usp_persistence_repoobject_guid[]

// end::usp_persistence_repoobject_guid[]


=== UspExamples

// tag::uspexamples[]

// end::uspexamples[]


=== uspgenerator_usp_id

// tag::uspgenerator_usp_id[]

// end::uspgenerator_usp_id[]


=== UspParameters

// tag::uspparameters[]

// end::uspparameters[]

== Boolean Attributes

source: property.RepoObjectProperty WHERE property_int = 1

// tag::boolean_attributes[]

:has_execution_plan_issue:

// end::boolean_attributes[]

== PlantUML diagrams

=== PlantUML Entity

// tag::puml_entity[]
[plantuml, entity-{docname}, svg, subs=macros]
....
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:repo_sys.columnreference.adoc[]" as repo_sys.ColumnReference << V >> {
  - is_all_columns_found : (bit)
  - is_ambiguous : (bit)
  - is_caller_dependent : (bit)
  - is_incomplete : (bit)
  - is_insert_all : (bit)
  - is_select_all : (bit)
  - is_selected : (bit)
  - is_updated : (bit)
  referenced_class : (tinyint)
  referenced_class_desc : (nvarchar(60))
  referenced_database_name : (nvarchar(128))
  referenced_entity_name : (nvarchar(128))
  referenced_id : (int)
  referenced_minor_id : (int)
  referenced_minor_name : (nvarchar(128))
  referenced_schema_name : (nvarchar(128))
  referenced_server_name : (nvarchar(128))
  referencing_minor_id : (int)
  - SysObject_full_name : (nvarchar(517))
  --
}
....

// end::puml_entity[]

=== PlantUML Entity 1 1 FK

// tag::puml_entity_1_1_fk[]
[plantuml, entity_1_1_fk-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:repo_sys.columnreference.adoc[]" as repo_sys.ColumnReference << V >> {

}



footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_fk[]

=== PlantUML 1 1 ObjectRef

// tag::puml_entity_1_1_objectref[]
[plantuml, entity_1_1_objectref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:repo_sys.columnreference.adoc[]" as repo_sys.ColumnReference << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo_sys.sysobject.adoc[]" as repo_sys.SysObject << V >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.dm_sql_referenced_entities.adoc[]" as sys_dwh.dm_sql_referenced_entities << SN >> {
  --
}

repo_sys.SysObject <.. repo_sys.ColumnReference
sys_dwh.dm_sql_referenced_entities <.. repo_sys.ColumnReference

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_objectref[]

=== PlantUML 30 0 ObjectRef

// tag::puml_entity_30_0_objectref[]
[plantuml, entity_30_0_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:config.ftv_dwh_database.adoc[]" as config.ftv_dwh_database << IF >> {
  --
}

entity "puml-link:dhw:sqldb:config.parameter.adoc[]" as config.Parameter << U >> {
  - **Parameter_name** : (varchar(100))
  - **sub_Parameter** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:configt.parameter_default.adoc[]" as configT.Parameter_default << V >> {
  - **Parameter_name** : (varchar(52))
  - **sub_Parameter** : (nvarchar(26))
  --
}

entity "puml-link:dhw:sqldb:repo_sys.columnreference.adoc[]" as repo_sys.ColumnReference << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo_sys.extendedproperties.adoc[]" as repo_sys.ExtendedProperties << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo_sys.sysobject.adoc[]" as repo_sys.SysObject << V >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.columns.adoc[]" as sys_dwh.columns << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.dm_sql_referenced_entities.adoc[]" as sys_dwh.dm_sql_referenced_entities << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.extended_properties.adoc[]" as sys_dwh.extended_properties << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.indexes.adoc[]" as sys_dwh.indexes << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.objects.adoc[]" as sys_dwh.objects << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.parameters.adoc[]" as sys_dwh.parameters << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.schemas.adoc[]" as sys_dwh.schemas << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.sql_modules.adoc[]" as sys_dwh.sql_modules << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.tables.adoc[]" as sys_dwh.tables << SN >> {
  --
}

config.ftv_dwh_database <.. repo_sys.ExtendedProperties
config.Parameter <.. config.ftv_dwh_database
configT.Parameter_default <.. config.Parameter
repo_sys.ExtendedProperties <.. repo_sys.SysObject
repo_sys.SysObject <.. repo_sys.ColumnReference
sys_dwh.columns <.. repo_sys.ExtendedProperties
sys_dwh.dm_sql_referenced_entities <.. repo_sys.ColumnReference
sys_dwh.extended_properties <.. repo_sys.ExtendedProperties
sys_dwh.indexes <.. repo_sys.ExtendedProperties
sys_dwh.objects <.. repo_sys.ExtendedProperties
sys_dwh.objects <.. repo_sys.SysObject
sys_dwh.parameters <.. repo_sys.ExtendedProperties
sys_dwh.schemas <.. repo_sys.ExtendedProperties
sys_dwh.schemas <.. repo_sys.SysObject
sys_dwh.sql_modules <.. repo_sys.SysObject
sys_dwh.tables <.. repo_sys.SysObject

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_30_0_objectref[]

=== PlantUML 0 30 ObjectRef

// tag::puml_entity_0_30_objectref[]
[plantuml, entity_0_30_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:repo_sys.columnreference.adoc[]" as repo_sys.ColumnReference << V >> {
  --
}



footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_0_30_objectref[]

=== PlantUML 1 1 ColumnRef

// tag::puml_entity_1_1_colref[]
[plantuml, entity_1_1_colref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:repo_sys.columnreference.adoc[]" as repo_sys.ColumnReference << V >> {
  - is_all_columns_found : (bit)
  - is_ambiguous : (bit)
  - is_caller_dependent : (bit)
  - is_incomplete : (bit)
  - is_insert_all : (bit)
  - is_select_all : (bit)
  - is_selected : (bit)
  - is_updated : (bit)
  referenced_class : (tinyint)
  referenced_class_desc : (nvarchar(60))
  referenced_database_name : (nvarchar(128))
  referenced_entity_name : (nvarchar(128))
  referenced_id : (int)
  referenced_minor_id : (int)
  referenced_minor_name : (nvarchar(128))
  referenced_schema_name : (nvarchar(128))
  referenced_server_name : (nvarchar(128))
  referencing_minor_id : (int)
  - SysObject_full_name : (nvarchar(517))
  --
}

entity "puml-link:dhw:sqldb:repo_sys.sysobject.adoc[]" as repo_sys.SysObject << V >> {
  - create_date : (datetime)
  history_table_id : (int)
  - is_ms_shipped : (bit)
  - is_published : (bit)
  - is_schema_published : (bit)
  max_column_id_used : (int)
  - modify_date : (datetime)
  - parent_object_id : (int)
  principal_id : (int)
  - schema_id : (int)
  sql_modules_definition : (nvarchar(max))
  - SysObject_fullname : (nvarchar(517))
  - SysObject_fullname2 : (nvarchar(257))
  - SysObject_id : (int)
  - SysObject_name : (sysname)
  SysObject_RepoObject_guid : (uniqueidentifier)
  SysObject_schema_name : (sysname)
  temporal_type : (tinyint)
  temporal_type_desc : (nvarchar(60))
  type : (char(2))
  type_desc : (nvarchar(60))
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.dm_sql_referenced_entities.adoc[]" as sys_dwh.dm_sql_referenced_entities << SN >> {
  --
}

repo_sys.SysObject <.. repo_sys.ColumnReference
sys_dwh.dm_sql_referenced_entities <.. repo_sys.ColumnReference
"repo_sys.SysObject::SysObject_fullname" <-- "repo_sys.ColumnReference::SysObject_full_name"

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_colref[]


== sql_modules_definition

// tag::sql_modules_definition[]
[%collapsible]
=======
[source,sql,numbered,indent=0]
----

CREATE View repo_sys.ColumnReference
As
--
--muss / kann noch angereichert werden
Select
    SysObject_full_name = so.SysObject_fullname
  , sdsre.referencing_minor_id
  , sdsre.referenced_server_name
  , sdsre.referenced_database_name
  , sdsre.referenced_schema_name
  , sdsre.referenced_entity_name
  , sdsre.referenced_minor_name
  , sdsre.referenced_id
  , sdsre.referenced_minor_id
  , sdsre.referenced_class
  , sdsre.referenced_class_desc
  , sdsre.is_caller_dependent
  , sdsre.is_ambiguous
  , sdsre.is_selected
  , sdsre.is_updated
  , sdsre.is_select_all
  , sdsre.is_all_columns_found
  , sdsre.is_insert_all
  , sdsre.is_incomplete
From
    repo_sys.SysObject                                                                 As so
    Cross Apply sys_dwh.dm_sql_referenced_entities ( so.SysObject_fullname, 'OBJECT' ) As sdsre
Where
    so.type In
    ( 'U', 'V' )

----
=======
// end::sql_modules_definition[]


