// tag::HeaderFullDisplayName[]
= repo.RepoObject_gross2 - V
// end::HeaderFullDisplayName[]

== existing_properties

// tag::existing_properties[]

:ExistsProperty--antorareferencedlist:
:ExistsProperty--antorareferencinglist:
:ExistsProperty--is_repo_managed:
:ExistsProperty--is_ssas:
:ExistsProperty--referencedobjectlist:
:ExistsProperty--sql_modules_definition:
:ExistsProperty--FK:
:ExistsProperty--AntoraIndexList:
:ExistsProperty--Columns:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
42BBCCE5-AD08-EC11-8515-A81E8446D5B0
// end::RepoObject_guid[]

== RepoObject_FullDisplayName2

// tag::RepoObject_FullDisplayName2[]
repo.RepoObject_gross2
// end::RepoObject_FullDisplayName2[]

== SysObject_type

// tag::SysObject_type[]
V 
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
view
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
663009443
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2021-12-16 11:43:40
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]
[discrete]
== _


[#column-antoracomponent]
=== AntoraComponent

[cols="d,8a,m,m,m"]
|===
|
|AntoraComponent
|nvarchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_gross.adoc#column-antoracomponent[+repo.RepoObject_gross.AntoraComponent+]
--


[#column-antoramodule]
=== AntoraModule

[cols="d,8a,m,m,m"]
|===
|
|AntoraModule
|nvarchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_gross.adoc#column-antoramodule[+repo.RepoObject_gross.AntoraModule+]
--


[#column-antorareferencedlist]
=== AntoraReferencedList

[cols="d,8a,m,m,m"]
|===
|
|AntoraReferencedList
|nvarchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:reference.repoobject_referencedlist.adoc#column-antorareferencedlist[+reference.RepoObject_ReferencedList.AntoraReferencedList+]
--


[#column-antorareferencinglist]
=== AntoraReferencingList

[cols="d,8a,m,m,m"]
|===
|
|AntoraReferencingList
|nvarchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:reference.repoobject_referencinglist.adoc#column-antorareferencinglist[+reference.RepoObject_ReferencingList.AntoraReferencingList+]
--


[#column-createcolumnlist]
=== CreateColumnList

[cols="d,8a,m,m,m"]
|===
|
|CreateColumnList
|nvarchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_columnlist.adoc#column-createcolumnlist[+repo.RepoObject_ColumnList.CreateColumnList+]
--


[#column-dbmlcolumnlist]
=== DbmlColumnList

[cols="d,8a,m,m,m"]
|===
|
|DbmlColumnList
|nvarchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_columnlist.adoc#column-dbmlcolumnlist[+repo.RepoObject_ColumnList.DbmlColumnList+]
--


[#column-description]
=== Description

[cols="d,8a,m,m,m"]
|===
|
|Description
|nvarchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_gross.adoc#column-description[+repo.RepoObject_gross.Description+]
--


[#column-externalunderlineantoracomponent]
=== external_AntoraComponent

[cols="d,8a,m,m,m"]
|===
|
|external_AntoraComponent
|nvarchar(128)
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_gross.adoc#column-externalunderlineantoracomponent[+repo.RepoObject_gross.external_AntoraComponent+]
--


[#column-externalunderlineantoramodule]
=== external_AntoraModule

[cols="d,8a,m,m,m"]
|===
|
|external_AntoraModule
|nvarchar(128)
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_gross.adoc#column-externalunderlineantoramodule[+repo.RepoObject_gross.external_AntoraModule+]
--


[#column-externalunderlinedatabasename]
=== external_DatabaseName

[cols="d,8a,m,m,m"]
|===
|
|external_DatabaseName
|nvarchar(128)
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_gross.adoc#column-externalunderlinedatabasename[+repo.RepoObject_gross.external_DatabaseName+]
--


[#column-externalunderlinerepodatabasename]
=== external_RepoDatabaseName

[cols="d,8a,m,m,m"]
|===
|
|external_RepoDatabaseName
|nvarchar(128)
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_gross.adoc#column-externalunderlinerepodatabasename[+repo.RepoObject_gross.external_RepoDatabaseName+]
--


[#column-hasunderlinedifferentunderlinesysunderlinenames]
=== has_different_sys_names

[cols="d,8a,m,m,m"]
|===
|
|has_different_sys_names
|bit
|NULL
|
|===

.Description
--
(CONVERT([bit],case when [RepoObject_schema_name]<>[SysObject_schema_name] OR [RepoObject_name]<>[SysObject_name] OR [RepoObject_type]<>[SysObject_type] then (1) else (0) end))
--
{empty} +

.Referenced Columns
--
* xref:repo.repoobject_gross.adoc#column-hasunderlinedifferentunderlinesysunderlinenames[+repo.RepoObject_gross.has_different_sys_names+]
--


[#column-hasunderlineexecutionunderlineplanunderlineissue]
=== has_execution_plan_issue

[cols="d,8a,m,m,m"]
|===
|
|has_execution_plan_issue
|bit
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_gross.adoc#column-hasunderlineexecutionunderlineplanunderlineissue[+repo.RepoObject_gross.has_execution_plan_issue+]
--


[#column-hasunderlinegetunderlinereferencedunderlineissue]
=== has_get_referenced_issue

[cols="d,8a,m,m,m"]
|===
|
|has_get_referenced_issue
|bit
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_gross.adoc#column-hasunderlinegetunderlinereferencedunderlineissue[+repo.RepoObject_gross.has_get_referenced_issue+]
--


[#column-hasunderlinehistory]
=== has_history

[cols="d,8a,m,m,m"]
|===
|
|has_history
|bit
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_gross.adoc#column-hasunderlinehistory[+repo.RepoObject_gross.has_history+]
--


[#column-hasunderlinehistoryunderlinecolumns]
=== has_history_columns

[cols="d,8a,m,m,m"]
|===
|
|has_history_columns
|bit
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_gross.adoc#column-hasunderlinehistoryunderlinecolumns[+repo.RepoObject_gross.has_history_columns+]
--


[#column-historyunderlineschemaunderlinename]
=== history_schema_name

[cols="d,8a,m,m,m"]
|===
|
|history_schema_name
|nvarchar(128)
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_gross.adoc#column-historyunderlineschemaunderlinename[+repo.RepoObject_gross.history_schema_name+]
--


[#column-historyunderlinetableunderlinename]
=== history_table_name

[cols="d,8a,m,m,m"]
|===
|
|history_table_name
|nvarchar(128)
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_gross.adoc#column-historyunderlinetableunderlinename[+repo.RepoObject_gross.history_table_name+]
--


[#column-indentunderlinesqlunderlinemodulesunderlinedefinition]
=== indent_sql_modules_definition

[cols="d,8a,m,m,m"]
|===
|
|indent_sql_modules_definition
|tinyint
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_gross.adoc#column-indentunderlinesqlunderlinemodulesunderlinedefinition[+repo.RepoObject_gross.indent_sql_modules_definition+]
--


[#column-inheritanceunderlinestringaggseparatorsql]
=== Inheritance_StringAggSeparatorSql

[cols="d,8a,m,m,m"]
|===
|
|Inheritance_StringAggSeparatorSql
|nvarchar(4000)
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_gross.adoc#column-inheritanceunderlinestringaggseparatorsql[+repo.RepoObject_gross.Inheritance_StringAggSeparatorSql+]
--


[#column-inheritancedefinition]
=== InheritanceDefinition

[cols="d,8a,m,m,m"]
|===
|
|InheritanceDefinition
|nvarchar(4000)
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_gross.adoc#column-inheritancedefinition[+repo.RepoObject_gross.InheritanceDefinition+]
--


[#column-inheritancetype]
=== InheritanceType

[cols="d,8a,m,m,m"]
|===
|
|InheritanceType
|tinyint
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_gross.adoc#column-inheritancetype[+repo.RepoObject_gross.InheritanceType+]
--


[#column-isunderlinedocsexclude]
=== is_DocsExclude

[cols="d,8a,m,m,m"]
|===
|
|is_DocsExclude
|bit
|NOT NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_gross.adoc#column-isunderlinedocsexclude[+repo.RepoObject_gross.is_DocsExclude+]
--


[#column-isunderlinedocsoutput]
=== is_DocsOutput

[cols="d,8a,m,m,m"]
|===
|
|is_DocsOutput
|int
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_gross.adoc#column-isunderlinedocsoutput[+repo.RepoObject_gross.is_DocsOutput+]
--


[#column-isunderlineexternal]
=== is_external

[cols="d,8a,m,m,m"]
|===
|
|is_external
|bit
|NOT NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_gross.adoc#column-isunderlineexternal[+repo.RepoObject_gross.is_external+]
--


[#column-isunderlineinunderlinereference]
=== is_in_reference

[cols="d,8a,m,m,m"]
|===
|
|is_in_reference
|int
|NOT NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_gross.adoc#column-isunderlineinunderlinereference[+repo.RepoObject_gross.is_in_reference+]
--


[#column-isunderlinepersistence]
=== is_persistence

[cols="d,8a,m,m,m"]
|===
|
|is_persistence
|bit
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_gross.adoc#column-isunderlinepersistence[+repo.RepoObject_gross.is_persistence+]
--


[#column-isunderlinepersistenceunderlinecheckunderlineduplicateunderlineperunderlinepk]
=== is_persistence_check_duplicate_per_pk

[cols="d,8a,m,m,m"]
|===
|
|is_persistence_check_duplicate_per_pk
|bit
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_gross.adoc#column-isunderlinepersistenceunderlinecheckunderlineduplicateunderlineperunderlinepk[+repo.RepoObject_gross.is_persistence_check_duplicate_per_pk+]
--


[#column-isunderlinepersistenceunderlinecheckunderlineforunderlineemptyunderlinesource]
=== is_persistence_check_for_empty_source

[cols="d,8a,m,m,m"]
|===
|
|is_persistence_check_for_empty_source
|bit
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_gross.adoc#column-isunderlinepersistenceunderlinecheckunderlineforunderlineemptyunderlinesource[+repo.RepoObject_gross.is_persistence_check_for_empty_source+]
--


[#column-isunderlinepersistenceunderlinedeleteunderlinechanged]
=== is_persistence_delete_changed

[cols="d,8a,m,m,m"]
|===
|
|is_persistence_delete_changed
|bit
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_gross.adoc#column-isunderlinepersistenceunderlinedeleteunderlinechanged[+repo.RepoObject_gross.is_persistence_delete_changed+]
--


[#column-isunderlinepersistenceunderlinedeleteunderlinemissing]
=== is_persistence_delete_missing

[cols="d,8a,m,m,m"]
|===
|
|is_persistence_delete_missing
|bit
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_gross.adoc#column-isunderlinepersistenceunderlinedeleteunderlinemissing[+repo.RepoObject_gross.is_persistence_delete_missing+]
--


[#column-isunderlinepersistenceunderlineinsert]
=== is_persistence_insert

[cols="d,8a,m,m,m"]
|===
|
|is_persistence_insert
|bit
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_gross.adoc#column-isunderlinepersistenceunderlineinsert[+repo.RepoObject_gross.is_persistence_insert+]
--


[#column-isunderlinepersistenceunderlinemergeunderlinedeleteunderlinemissing]
=== is_persistence_merge_delete_missing

[cols="d,8a,m,m,m"]
|===
|
|is_persistence_merge_delete_missing
|bit
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_gross.adoc#column-isunderlinepersistenceunderlinemergeunderlinedeleteunderlinemissing[+repo.RepoObject_gross.is_persistence_merge_delete_missing+]
--


[#column-isunderlinepersistenceunderlinemergeunderlineinsert]
=== is_persistence_merge_insert

[cols="d,8a,m,m,m"]
|===
|
|is_persistence_merge_insert
|bit
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_gross.adoc#column-isunderlinepersistenceunderlinemergeunderlineinsert[+repo.RepoObject_gross.is_persistence_merge_insert+]
--


[#column-isunderlinepersistenceunderlinemergeunderlineupdateunderlinechanged]
=== is_persistence_merge_update_changed

[cols="d,8a,m,m,m"]
|===
|
|is_persistence_merge_update_changed
|bit
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_gross.adoc#column-isunderlinepersistenceunderlinemergeunderlineupdateunderlinechanged[+repo.RepoObject_gross.is_persistence_merge_update_changed+]
--


[#column-isunderlinepersistenceunderlinepersistunderlinesource]
=== is_persistence_persist_source

[cols="d,8a,m,m,m"]
|===
|
|is_persistence_persist_source
|bit
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_gross.adoc#column-isunderlinepersistenceunderlinepersistunderlinesource[+repo.RepoObject_gross.is_persistence_persist_source+]
--


[#column-isunderlinepersistenceunderlinetruncate]
=== is_persistence_truncate

[cols="d,8a,m,m,m"]
|===
|
|is_persistence_truncate
|bit
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_gross.adoc#column-isunderlinepersistenceunderlinetruncate[+repo.RepoObject_gross.is_persistence_truncate+]
--


[#column-isunderlinepersistenceunderlineupdateunderlinechanged]
=== is_persistence_update_changed

[cols="d,8a,m,m,m"]
|===
|
|is_persistence_update_changed
|bit
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_gross.adoc#column-isunderlinepersistenceunderlineupdateunderlinechanged[+repo.RepoObject_gross.is_persistence_update_changed+]
--


[#column-isunderlinerepounderlinemanaged]
=== is_repo_managed

[cols="d,8a,m,m,m"]
|===
|
|is_repo_managed
|bit
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_gross.adoc#column-isunderlinerepounderlinemanaged[+repo.RepoObject_gross.is_repo_managed+]
--


[#column-isunderlinerepoobjectunderlinenameunderlineuniqueidentifier]
=== is_RepoObject_name_uniqueidentifier

[cols="d,8a,m,m,m"]
|===
|
|is_RepoObject_name_uniqueidentifier
|int
|NOT NULL
|
|===

.Description
--
(case when TRY_CAST([RepoObject_name] AS [uniqueidentifier]) IS NULL then (0) else (1) end)
--
{empty} +

.Referenced Columns
--
* xref:repo.repoobject_gross.adoc#column-isunderlinerepoobjectunderlinenameunderlineuniqueidentifier[+repo.RepoObject_gross.is_RepoObject_name_uniqueidentifier+]
--


[#column-isunderlinerequiredunderlineobjectmerge]
=== is_required_ObjectMerge

[cols="d,8a,m,m,m"]
|===
|
|is_required_ObjectMerge
|bit
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_gross.adoc#column-isunderlinerequiredunderlineobjectmerge[+repo.RepoObject_gross.is_required_ObjectMerge+]
--


[#column-isunderlinessas]
=== is_ssas

[cols="d,8a,m,m,m"]
|===
|
|is_ssas
|bit
|NOT NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_gross.adoc#column-isunderlinessas[+repo.RepoObject_gross.is_ssas+]
--


[#column-isunderlinesysobjectunderlinemissing]
=== is_SysObject_missing

[cols="d,8a,m,m,m"]
|===
|
|is_SysObject_missing
|bit
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_gross.adoc#column-isunderlinesysobjectunderlinemissing[+repo.RepoObject_gross.is_SysObject_missing+]
--


[#column-isunderlinesysobjectunderlinenameunderlineuniqueidentifier]
=== is_SysObject_name_uniqueidentifier

[cols="d,8a,m,m,m"]
|===
|
|is_SysObject_name_uniqueidentifier
|int
|NOT NULL
|
|===

.Description
--
(case when TRY_CAST([SysObject_name] AS [uniqueidentifier]) IS NULL then (0) else (1) end)
--
{empty} +

.Referenced Columns
--
* xref:repo.repoobject_gross.adoc#column-isunderlinesysobjectunderlinenameunderlineuniqueidentifier[+repo.RepoObject_gross.is_SysObject_name_uniqueidentifier+]
--


[#column-modifyunderlinedt]
=== modify_dt

[cols="d,8a,m,m,m"]
|===
|
|modify_dt
|datetime
|NOT NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_gross.adoc#column-modifyunderlinedt[+repo.RepoObject_gross.modify_dt+]
--


[#column-nodeunderlineid]
=== node_id

[cols="d,8a,m,m,m"]
|===
|
|node_id
|bigint
|NULL
|
|===

.Description
--
(CONVERT([bigint],[SysObject_id])*(10000))
--
{empty} +

.Referenced Columns
--
* xref:repo.repoobject_gross.adoc#column-nodeunderlineid[+repo.RepoObject_gross.node_id+]
--


[#column-persistenceunderlinesourceunderlinerepoobjectunderlinefullname]
=== persistence_source_RepoObject_fullname

[cols="d,8a,m,m,m"]
|===
|
|persistence_source_RepoObject_fullname
|nvarchar(261)
|NULL
|
|===

.Description
--
(concat('[',[RepoObject_schema_name],'].[',[RepoObject_name],']'))
--
{empty} +

.Referenced Columns
--
* xref:repo.repoobject_gross.adoc#column-persistenceunderlinesourceunderlinerepoobjectunderlinefullname[+repo.RepoObject_gross.persistence_source_RepoObject_fullname+]
--


[#column-persistenceunderlinesourceunderlinerepoobjectunderlinefullname2]
=== persistence_source_RepoObject_fullname2

[cols="d,8a,m,m,m"]
|===
|
|persistence_source_RepoObject_fullname2
|nvarchar(257)
|NULL
|
|===

.Description
--
(concat([RepoObject_schema_name],'.',[RepoObject_name]))
--
{empty} +

.Referenced Columns
--
* xref:repo.repoobject_gross.adoc#column-persistenceunderlinesourceunderlinerepoobjectunderlinefullname2[+repo.RepoObject_gross.persistence_source_RepoObject_fullname2+]
--


[#column-persistenceunderlinesourceunderlinerepoobjectunderlineguid]
=== persistence_source_RepoObject_guid

[cols="d,8a,m,m,m"]
|===
|
|persistence_source_RepoObject_guid
|uniqueidentifier
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_gross.adoc#column-persistenceunderlinesourceunderlinerepoobjectunderlineguid[+repo.RepoObject_gross.persistence_source_RepoObject_guid+]
--


[#column-persistenceunderlinesourceunderlinerepoobjectunderlinexref]
=== persistence_source_RepoObject_xref

[cols="d,8a,m,m,m"]
|===
|
|persistence_source_RepoObject_xref
|nvarchar(4000)
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_gross.adoc#column-persistenceunderlinesourceunderlinerepoobjectunderlinexref[+repo.RepoObject_gross.persistence_source_RepoObject_xref+]
--


[#column-persistenceunderlinesourceunderlinesysobjectunderlinefullname]
=== persistence_source_SysObject_fullname

[cols="d,8a,m,m,m"]
|===
|
|persistence_source_SysObject_fullname
|nvarchar(261)
|NULL
|
|===

.Description
--
(concat('[',[SysObject_schema_name],'].[',[SysObject_name],']'))
--
{empty} +

.Referenced Columns
--
* xref:repo.repoobject_gross.adoc#column-persistenceunderlinesourceunderlinesysobjectunderlinefullname[+repo.RepoObject_gross.persistence_source_SysObject_fullname+]
--


[#column-persistenceunderlinesourceunderlinesysobjectunderlinefullnameunderlineorunderlinetempsource]
=== persistence_source_SysObject_fullname_or_tempsource

[cols="d,8a,m,m,m"]
|===
|
|persistence_source_SysObject_fullname_or_tempsource
|nvarchar(261)
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_gross.adoc#column-persistenceunderlinesourceunderlinesysobjectunderlinefullnameunderlineorunderlinetempsource[+repo.RepoObject_gross.persistence_source_SysObject_fullname_or_tempsource+]
--


[#column-persistenceunderlinesourceunderlinesysobjectunderlinefullname2]
=== persistence_source_SysObject_fullname2

[cols="d,8a,m,m,m"]
|===
|
|persistence_source_SysObject_fullname2
|nvarchar(257)
|NULL
|
|===

.Description
--
(concat([SysObject_schema_name],'.',[SysObject_name]))
--
{empty} +

.Referenced Columns
--
* xref:repo.repoobject_gross.adoc#column-persistenceunderlinesourceunderlinesysobjectunderlinefullname2[+repo.RepoObject_gross.persistence_source_SysObject_fullname2+]
--


[#column-persistenceunderlinesourceunderlinesysobjectunderlinexref]
=== persistence_source_SysObject_xref

[cols="d,8a,m,m,m"]
|===
|
|persistence_source_SysObject_xref
|nvarchar(4000)
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_gross.adoc#column-persistenceunderlinesourceunderlinesysobjectunderlinexref[+repo.RepoObject_gross.persistence_source_SysObject_xref+]
--


[#column-persistencecomparecolumnlist]
=== PersistenceCompareColumnList

[cols="d,8a,m,m,m"]
|===
|
|PersistenceCompareColumnList
|nvarchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_columnlist.adoc#column-persistencecomparecolumnlist[+repo.RepoObject_ColumnList.PersistenceCompareColumnList+]
--


[#column-persistenceinsertcolumnlist]
=== PersistenceInsertColumnList

[cols="d,8a,m,m,m"]
|===
|
|PersistenceInsertColumnList
|nvarchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_columnlist.adoc#column-persistenceinsertcolumnlist[+repo.RepoObject_ColumnList.PersistenceInsertColumnList+]
--


[#column-persistenceupdatecolumnlist]
=== PersistenceUpdateColumnList

[cols="d,8a,m,m,m"]
|===
|
|PersistenceUpdateColumnList
|nvarchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_columnlist.adoc#column-persistenceupdatecolumnlist[+repo.RepoObject_ColumnList.PersistenceUpdateColumnList+]
--


[#column-pkunderlineindexunderlineguid]
=== pk_index_guid

[cols="d,8a,m,m,m"]
|===
|
|pk_index_guid
|uniqueidentifier
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_gross.adoc#column-pkunderlineindexunderlineguid[+repo.RepoObject_gross.pk_index_guid+]
--


[#column-pkunderlineindexpatterncolumndatatype]
=== pk_IndexPatternColumnDatatype

[cols="d,8a,m,m,m"]
|===
|
|pk_IndexPatternColumnDatatype
|nvarchar(4000)
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_gross.adoc#column-pkunderlineindexpatterncolumndatatype[+repo.RepoObject_gross.pk_IndexPatternColumnDatatype+]
--


[#column-pkunderlineindexpatterncolumnname]
=== pk_IndexPatternColumnName

[cols="d,8a,m,m,m"]
|===
|
|pk_IndexPatternColumnName
|nvarchar(4000)
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_gross.adoc#column-pkunderlineindexpatterncolumnname[+repo.RepoObject_gross.pk_IndexPatternColumnName+]
--


[#column-pkunderlineindexpatterncolumnnameunderlinenew]
=== pk_IndexPatternColumnName_new

[cols="d,8a,m,m,m"]
|===
|
|pk_IndexPatternColumnName_new
|nvarchar(4000)
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_gross.adoc#column-pkunderlineindexpatterncolumnnameunderlinenew[+repo.RepoObject_gross.pk_IndexPatternColumnName_new+]
--


[#column-pkunderlineindexsemanticgroup]
=== pk_IndexSemanticGroup

[cols="d,8a,m,m,m"]
|===
|
|pk_IndexSemanticGroup
|nvarchar(512)
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_gross.adoc#column-pkunderlineindexsemanticgroup[+repo.RepoObject_gross.pk_IndexSemanticGroup+]
--


[#column-postscript]
=== postscript

[cols="d,8a,m,m,m"]
|===
|
|postscript
|nvarchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_gross.adoc#column-postscript[+repo.RepoObject_gross.postscript+]
--


[#column-prescript]
=== prescript

[cols="d,8a,m,m,m"]
|===
|
|prescript
|nvarchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_gross.adoc#column-prescript[+repo.RepoObject_gross.prescript+]
--


[#column-propertyunderlinemsunderlinedescription]
=== Property_ms_description

[cols="d,8a,m,m,m"]
|===
|
|Property_ms_description
|nvarchar(4000)
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_gross.adoc#column-propertyunderlinemsunderlinedescription[+repo.RepoObject_gross.Property_ms_description+]
--


[#column-repounderlinehistoryunderlinetableunderlineguid]
=== Repo_history_table_guid

[cols="d,8a,m,m,m"]
|===
|
|Repo_history_table_guid
|uniqueidentifier
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_gross.adoc#column-repounderlinehistoryunderlinetableunderlineguid[+repo.RepoObject_gross.Repo_history_table_guid+]
--


[#column-repounderlinetemporalunderlinetype]
=== Repo_temporal_type

[cols="d,8a,m,m,m"]
|===
|
|Repo_temporal_type
|tinyint
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_gross.adoc#column-repounderlinetemporalunderlinetype[+repo.RepoObject_gross.Repo_temporal_type+]
--


[#column-repoobjectunderlinefullname]
=== RepoObject_fullname

[cols="d,8a,m,m,m"]
|===
|
|RepoObject_fullname
|nvarchar(261)
|NOT NULL
|
|===

.Description
--
(concat('[',[RepoObject_schema_name],'].[',[RepoObject_name],']'))
--
{empty} +

.Referenced Columns
--
* xref:repo.repoobject_gross.adoc#column-repoobjectunderlinefullname[+repo.RepoObject_gross.RepoObject_fullname+]
--


[#column-repoobjectunderlinefullname2]
=== RepoObject_fullname2

[cols="d,8a,m,m,m"]
|===
|
|RepoObject_fullname2
|nvarchar(257)
|NOT NULL
|
|===

.Description
--
(concat([RepoObject_schema_name],'.',[RepoObject_name]))
--
{empty} +

.Referenced Columns
--
* xref:repo.repoobject_gross.adoc#column-repoobjectunderlinefullname2[+repo.RepoObject_gross.RepoObject_fullname2+]
--


[#column-repoobjectunderlineguid]
=== RepoObject_guid

[cols="d,8a,m,m,m"]
|===
|
|RepoObject_guid
|uniqueidentifier
|NOT NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_gross.adoc#column-repoobjectunderlineguid[+repo.RepoObject_gross.RepoObject_guid+]
--


[#column-repoobjectunderlinename]
=== RepoObject_name

[cols="d,8a,m,m,m"]
|===
|
|RepoObject_name
|nvarchar(128)
|NOT NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_gross.adoc#column-repoobjectunderlinename[+repo.RepoObject_gross.RepoObject_name+]
--


[#column-repoobjectunderlinereferencingunderlinecount]
=== RepoObject_Referencing_Count

[cols="d,8a,m,m,m"]
|===
|
|RepoObject_Referencing_Count
|int
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_gross.adoc#column-repoobjectunderlinereferencingunderlinecount[+repo.RepoObject_gross.RepoObject_Referencing_Count+]
--


[#column-repoobjectunderlineschemaunderlinename]
=== RepoObject_schema_name

[cols="d,8a,m,m,m"]
|===
|
|RepoObject_schema_name
|nvarchar(128)
|NOT NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_gross.adoc#column-repoobjectunderlineschemaunderlinename[+repo.RepoObject_gross.RepoObject_schema_name+]
--


[#column-repoobjectunderlinetype]
=== RepoObject_type

[cols="d,8a,m,m,m"]
|===
|
|RepoObject_type
|char(2)
|NOT NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_gross.adoc#column-repoobjectunderlinetype[+repo.RepoObject_gross.RepoObject_type+]
--


[#column-repoobjectunderlinetypeunderlinename]
=== RepoObject_type_name

[cols="d,8a,m,m,m"]
|===
|
|RepoObject_type_name
|nvarchar(128)
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_gross.adoc#column-repoobjectunderlinetypeunderlinename[+repo.RepoObject_gross.RepoObject_type_name+]
--


[#column-sqlunderlinemodulesunderlineantora]
=== sql_modules_antora

[cols="d,8a,m,m,m"]
|===
|
|sql_modules_antora
|nvarchar(max)
|NULL
|
|===


[#column-sqlunderlinemodulesunderlinedefinition]
=== sql_modules_definition

[cols="d,8a,m,m,m"]
|===
|
|sql_modules_definition
|nvarchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:sqlparse.repoobject_sqlmodules_repo_sys.adoc#column-sqlunderlinemodulesunderlinedefinition[+sqlparse.RepoObject_SqlModules_Repo_Sys.sql_modules_definition+]
--


[#column-sqlunderlinemodulesunderlineformatted]
=== sql_modules_formatted

[cols="d,8a,m,m,m"]
|===
|
|sql_modules_formatted
|nvarchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:sqlparse.repoobject_sqlmodules_repo_sys.adoc#column-sqlunderlinemodulesunderlineformatted[+sqlparse.RepoObject_SqlModules_Repo_Sys.sql_modules_formatted+]
--


[#column-sqlunderlinemodulesunderlineformatted2]
=== sql_modules_formatted2

[cols="d,8a,m,m,m"]
|===
|
|sql_modules_formatted2
|nvarchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:sqlparse.repoobject_sqlmodules_repo_sys.adoc#column-sqlunderlinemodulesunderlineformatted2[+sqlparse.RepoObject_SqlModules_Repo_Sys.sql_modules_formatted2+]
--


[#column-sysobjectunderlinefullname]
=== SysObject_fullname

[cols="d,8a,m,m,m"]
|===
|
|SysObject_fullname
|nvarchar(261)
|NOT NULL
|
|===

.Description
--
(concat('[',[SysObject_schema_name],'].[',[SysObject_name],']'))
--
{empty} +

.Referenced Columns
--
* xref:repo.repoobject_gross.adoc#column-sysobjectunderlinefullname[+repo.RepoObject_gross.SysObject_fullname+]
--


[#column-sysobjectunderlinefullname2]
=== SysObject_fullname2

[cols="d,8a,m,m,m"]
|===
|
|SysObject_fullname2
|nvarchar(257)
|NOT NULL
|
|===

.Description
--
(concat([SysObject_schema_name],'.',[SysObject_name]))
--
{empty} +

.Referenced Columns
--
* xref:repo.repoobject_gross.adoc#column-sysobjectunderlinefullname2[+repo.RepoObject_gross.SysObject_fullname2+]
--


[#column-sysobjectunderlineid]
=== SysObject_id

[cols="d,8a,m,m,m"]
|===
|
|SysObject_id
|int
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_gross.adoc#column-sysobjectunderlineid[+repo.RepoObject_gross.SysObject_id+]
--


[#column-sysobjectunderlinemodifyunderlinedate]
=== SysObject_modify_date

[cols="d,8a,m,m,m"]
|===
|
|SysObject_modify_date
|datetime
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_gross.adoc#column-sysobjectunderlinemodifyunderlinedate[+repo.RepoObject_gross.SysObject_modify_date+]
--


[#column-sysobjectunderlinename]
=== SysObject_name

[cols="d,8a,m,m,m"]
|===
|
|SysObject_name
|nvarchar(128)
|NOT NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_gross.adoc#column-sysobjectunderlinename[+repo.RepoObject_gross.SysObject_name+]
--


[#column-sysobjectunderlineparentunderlineobjectunderlineid]
=== SysObject_parent_object_id

[cols="d,8a,m,m,m"]
|===
|
|SysObject_parent_object_id
|int
|NOT NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_gross.adoc#column-sysobjectunderlineparentunderlineobjectunderlineid[+repo.RepoObject_gross.SysObject_parent_object_id+]
--


[#column-sysobjectunderlinequeryunderlineexecutedunderlinedt]
=== SysObject_query_executed_dt

[cols="d,8a,m,m,m"]
|===
|
|SysObject_query_executed_dt
|datetime
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_gross.adoc#column-sysobjectunderlinequeryunderlineexecutedunderlinedt[+repo.RepoObject_gross.SysObject_query_executed_dt+]
--


[#column-sysobjectunderlinequeryunderlineplan]
=== SysObject_query_plan

[cols="d,8a,m,m,m"]
|===
|
|SysObject_query_plan
|xml
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_gross.adoc#column-sysobjectunderlinequeryunderlineplan[+repo.RepoObject_gross.SysObject_query_plan+]
--


[#column-sysobjectunderlinequeryunderlinesql]
=== SysObject_query_sql

[cols="d,8a,m,m,m"]
|===
|
|SysObject_query_sql
|nvarchar(406)
|NOT NULL
|
|===

.Description
--
(concat('SELECT * FROM [',[config].[fs_dwh_database_name](),'].[',[SysObject_schema_name],'].[',[SysObject_name],']'))
--
{empty} +

.Referenced Columns
--
* xref:repo.repoobject_gross.adoc#column-sysobjectunderlinequeryunderlinesql[+repo.RepoObject_gross.SysObject_query_sql+]
--


[#column-sysobjectunderlineschemaunderlinename]
=== SysObject_schema_name

[cols="d,8a,m,m,m"]
|===
|
|SysObject_schema_name
|nvarchar(128)
|NOT NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_gross.adoc#column-sysobjectunderlineschemaunderlinename[+repo.RepoObject_gross.SysObject_schema_name+]
--


[#column-sysobjectunderlinetype]
=== SysObject_type

[cols="d,8a,m,m,m"]
|===
|
|SysObject_type
|char(2)
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_gross.adoc#column-sysobjectunderlinetype[+repo.RepoObject_gross.SysObject_type+]
--


[#column-sysobjectunderlinetypeunderlinename]
=== SysObject_type_name

[cols="d,8a,m,m,m"]
|===
|
|SysObject_type_name
|nvarchar(128)
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_gross.adoc#column-sysobjectunderlinetypeunderlinename[+repo.RepoObject_gross.SysObject_type_name+]
--


[#column-tablesunderlinedatacategory]
=== tables_dataCategory

[cols="d,8a,m,m,m"]
|===
|
|tables_dataCategory
|nvarchar(500)
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_gross.adoc#column-tablesunderlinedatacategory[+repo.RepoObject_gross.tables_dataCategory+]
--


[#column-tablesunderlinedescription]
=== tables_description

[cols="d,8a,m,m,m"]
|===
|
|tables_description
|nvarchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_gross.adoc#column-tablesunderlinedescription[+repo.RepoObject_gross.tables_description+]
--


[#column-tablesunderlineishidden]
=== tables_isHidden

[cols="d,8a,m,m,m"]
|===
|
|tables_isHidden
|bit
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_gross.adoc#column-tablesunderlineishidden[+repo.RepoObject_gross.tables_isHidden+]
--


[#column-temporalunderlinetype]
=== temporal_type

[cols="d,8a,m,m,m"]
|===
|
|temporal_type
|tinyint
|NULL
|
|===

.Description
--
(CONVERT([tinyint],case [has_history] when (1) then (2) else (0) end))
--
{empty} +

.Referenced Columns
--
* xref:repo.repoobject_gross.adoc#column-temporalunderlinetype[+repo.RepoObject_gross.temporal_type+]
--


[#column-uspunderlinepersistenceunderlinename]
=== usp_persistence_name

[cols="d,8a,m,m,m"]
|===
|
|usp_persistence_name
|nvarchar(140)
|NOT NULL
|
|===

.Description
--
('usp_PERSIST_'+[RepoObject_name])
--
{empty} +

.Referenced Columns
--
* xref:repo.repoobject_gross.adoc#column-uspunderlinepersistenceunderlinename[+repo.RepoObject_gross.usp_persistence_name+]
--


[#column-uspunderlinepersistenceunderlinerepoobjectunderlineguid]
=== usp_persistence_RepoObject_guid

[cols="d,8a,m,m,m"]
|===
|
|usp_persistence_RepoObject_guid
|uniqueidentifier
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_gross.adoc#column-uspunderlinepersistenceunderlinerepoobjectunderlineguid[+repo.RepoObject_gross.usp_persistence_RepoObject_guid+]
--


[#column-uspgeneratorunderlineuspunderlineid]
=== uspgenerator_usp_id

[cols="d,8a,m,m,m"]
|===
|
|uspgenerator_usp_id
|int
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_gross.adoc#column-uspgeneratorunderlineuspunderlineid[+repo.RepoObject_gross.uspgenerator_usp_id+]
--


// end::AntoraColumnDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]


































































































// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]
|
|<<column-antoracomponent>>
|nvarchar(max)
|NULL
|

|
|<<column-antoramodule>>
|nvarchar(max)
|NULL
|

|
|<<column-antorareferencedlist>>
|nvarchar(max)
|NULL
|

|
|<<column-antorareferencinglist>>
|nvarchar(max)
|NULL
|

|
|<<column-createcolumnlist>>
|nvarchar(max)
|NULL
|

|
|<<column-dbmlcolumnlist>>
|nvarchar(max)
|NULL
|

|
|<<column-description>>
|nvarchar(max)
|NULL
|

|
|<<column-externalunderlineantoracomponent>>
|nvarchar(128)
|NULL
|

|
|<<column-externalunderlineantoramodule>>
|nvarchar(128)
|NULL
|

|
|<<column-externalunderlinedatabasename>>
|nvarchar(128)
|NULL
|

|
|<<column-externalunderlinerepodatabasename>>
|nvarchar(128)
|NULL
|

|
|<<column-hasunderlinedifferentunderlinesysunderlinenames>>
|bit
|NULL
|

|
|<<column-hasunderlineexecutionunderlineplanunderlineissue>>
|bit
|NULL
|

|
|<<column-hasunderlinegetunderlinereferencedunderlineissue>>
|bit
|NULL
|

|
|<<column-hasunderlinehistory>>
|bit
|NULL
|

|
|<<column-hasunderlinehistoryunderlinecolumns>>
|bit
|NULL
|

|
|<<column-historyunderlineschemaunderlinename>>
|nvarchar(128)
|NULL
|

|
|<<column-historyunderlinetableunderlinename>>
|nvarchar(128)
|NULL
|

|
|<<column-indentunderlinesqlunderlinemodulesunderlinedefinition>>
|tinyint
|NULL
|

|
|<<column-inheritanceunderlinestringaggseparatorsql>>
|nvarchar(4000)
|NULL
|

|
|<<column-inheritancedefinition>>
|nvarchar(4000)
|NULL
|

|
|<<column-inheritancetype>>
|tinyint
|NULL
|

|
|<<column-isunderlinedocsexclude>>
|bit
|NOT NULL
|

|
|<<column-isunderlinedocsoutput>>
|int
|NULL
|

|
|<<column-isunderlineexternal>>
|bit
|NOT NULL
|

|
|<<column-isunderlineinunderlinereference>>
|int
|NOT NULL
|

|
|<<column-isunderlinepersistence>>
|bit
|NULL
|

|
|<<column-isunderlinepersistenceunderlinecheckunderlineduplicateunderlineperunderlinepk>>
|bit
|NULL
|

|
|<<column-isunderlinepersistenceunderlinecheckunderlineforunderlineemptyunderlinesource>>
|bit
|NULL
|

|
|<<column-isunderlinepersistenceunderlinedeleteunderlinechanged>>
|bit
|NULL
|

|
|<<column-isunderlinepersistenceunderlinedeleteunderlinemissing>>
|bit
|NULL
|

|
|<<column-isunderlinepersistenceunderlineinsert>>
|bit
|NULL
|

|
|<<column-isunderlinepersistenceunderlinemergeunderlinedeleteunderlinemissing>>
|bit
|NULL
|

|
|<<column-isunderlinepersistenceunderlinemergeunderlineinsert>>
|bit
|NULL
|

|
|<<column-isunderlinepersistenceunderlinemergeunderlineupdateunderlinechanged>>
|bit
|NULL
|

|
|<<column-isunderlinepersistenceunderlinepersistunderlinesource>>
|bit
|NULL
|

|
|<<column-isunderlinepersistenceunderlinetruncate>>
|bit
|NULL
|

|
|<<column-isunderlinepersistenceunderlineupdateunderlinechanged>>
|bit
|NULL
|

|
|<<column-isunderlinerepounderlinemanaged>>
|bit
|NULL
|

|
|<<column-isunderlinerepoobjectunderlinenameunderlineuniqueidentifier>>
|int
|NOT NULL
|

|
|<<column-isunderlinerequiredunderlineobjectmerge>>
|bit
|NULL
|

|
|<<column-isunderlinessas>>
|bit
|NOT NULL
|

|
|<<column-isunderlinesysobjectunderlinemissing>>
|bit
|NULL
|

|
|<<column-isunderlinesysobjectunderlinenameunderlineuniqueidentifier>>
|int
|NOT NULL
|

|
|<<column-modifyunderlinedt>>
|datetime
|NOT NULL
|

|
|<<column-nodeunderlineid>>
|bigint
|NULL
|

|
|<<column-persistenceunderlinesourceunderlinerepoobjectunderlinefullname>>
|nvarchar(261)
|NULL
|

|
|<<column-persistenceunderlinesourceunderlinerepoobjectunderlinefullname2>>
|nvarchar(257)
|NULL
|

|
|<<column-persistenceunderlinesourceunderlinerepoobjectunderlineguid>>
|uniqueidentifier
|NULL
|

|
|<<column-persistenceunderlinesourceunderlinerepoobjectunderlinexref>>
|nvarchar(4000)
|NULL
|

|
|<<column-persistenceunderlinesourceunderlinesysobjectunderlinefullname>>
|nvarchar(261)
|NULL
|

|
|<<column-persistenceunderlinesourceunderlinesysobjectunderlinefullnameunderlineorunderlinetempsource>>
|nvarchar(261)
|NULL
|

|
|<<column-persistenceunderlinesourceunderlinesysobjectunderlinefullname2>>
|nvarchar(257)
|NULL
|

|
|<<column-persistenceunderlinesourceunderlinesysobjectunderlinexref>>
|nvarchar(4000)
|NULL
|

|
|<<column-persistencecomparecolumnlist>>
|nvarchar(max)
|NULL
|

|
|<<column-persistenceinsertcolumnlist>>
|nvarchar(max)
|NULL
|

|
|<<column-persistenceupdatecolumnlist>>
|nvarchar(max)
|NULL
|

|
|<<column-pkunderlineindexunderlineguid>>
|uniqueidentifier
|NULL
|

|
|<<column-pkunderlineindexpatterncolumndatatype>>
|nvarchar(4000)
|NULL
|

|
|<<column-pkunderlineindexpatterncolumnname>>
|nvarchar(4000)
|NULL
|

|
|<<column-pkunderlineindexpatterncolumnnameunderlinenew>>
|nvarchar(4000)
|NULL
|

|
|<<column-pkunderlineindexsemanticgroup>>
|nvarchar(512)
|NULL
|

|
|<<column-postscript>>
|nvarchar(max)
|NULL
|

|
|<<column-prescript>>
|nvarchar(max)
|NULL
|

|
|<<column-propertyunderlinemsunderlinedescription>>
|nvarchar(4000)
|NULL
|

|
|<<column-repounderlinehistoryunderlinetableunderlineguid>>
|uniqueidentifier
|NULL
|

|
|<<column-repounderlinetemporalunderlinetype>>
|tinyint
|NULL
|

|
|<<column-repoobjectunderlinefullname>>
|nvarchar(261)
|NOT NULL
|

|
|<<column-repoobjectunderlinefullname2>>
|nvarchar(257)
|NOT NULL
|

|
|<<column-repoobjectunderlineguid>>
|uniqueidentifier
|NOT NULL
|

|
|<<column-repoobjectunderlinename>>
|nvarchar(128)
|NOT NULL
|

|
|<<column-repoobjectunderlinereferencingunderlinecount>>
|int
|NULL
|

|
|<<column-repoobjectunderlineschemaunderlinename>>
|nvarchar(128)
|NOT NULL
|

|
|<<column-repoobjectunderlinetype>>
|char(2)
|NOT NULL
|

|
|<<column-repoobjectunderlinetypeunderlinename>>
|nvarchar(128)
|NULL
|

|
|<<column-sqlunderlinemodulesunderlineantora>>
|nvarchar(max)
|NULL
|

|
|<<column-sqlunderlinemodulesunderlinedefinition>>
|nvarchar(max)
|NULL
|

|
|<<column-sqlunderlinemodulesunderlineformatted>>
|nvarchar(max)
|NULL
|

|
|<<column-sqlunderlinemodulesunderlineformatted2>>
|nvarchar(max)
|NULL
|

|
|<<column-sysobjectunderlinefullname>>
|nvarchar(261)
|NOT NULL
|

|
|<<column-sysobjectunderlinefullname2>>
|nvarchar(257)
|NOT NULL
|

|
|<<column-sysobjectunderlineid>>
|int
|NULL
|

|
|<<column-sysobjectunderlinemodifyunderlinedate>>
|datetime
|NULL
|

|
|<<column-sysobjectunderlinename>>
|nvarchar(128)
|NOT NULL
|

|
|<<column-sysobjectunderlineparentunderlineobjectunderlineid>>
|int
|NOT NULL
|

|
|<<column-sysobjectunderlinequeryunderlineexecutedunderlinedt>>
|datetime
|NULL
|

|
|<<column-sysobjectunderlinequeryunderlineplan>>
|xml
|NULL
|

|
|<<column-sysobjectunderlinequeryunderlinesql>>
|nvarchar(406)
|NOT NULL
|

|
|<<column-sysobjectunderlineschemaunderlinename>>
|nvarchar(128)
|NOT NULL
|

|
|<<column-sysobjectunderlinetype>>
|char(2)
|NULL
|

|
|<<column-sysobjectunderlinetypeunderlinename>>
|nvarchar(128)
|NULL
|

|
|<<column-tablesunderlinedatacategory>>
|nvarchar(500)
|NULL
|

|
|<<column-tablesunderlinedescription>>
|nvarchar(max)
|NULL
|

|
|<<column-tablesunderlineishidden>>
|bit
|NULL
|

|
|<<column-temporalunderlinetype>>
|tinyint
|NULL
|

|
|<<column-uspunderlinepersistenceunderlinename>>
|nvarchar(140)
|NOT NULL
|

|
|<<column-uspunderlinepersistenceunderlinerepoobjectunderlineguid>>
|uniqueidentifier
|NULL
|

|
|<<column-uspgeneratorunderlineuspunderlineid>>
|int
|NULL
|

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

[#index-idxunderlinerepoobjectunderlinegross2underlineunderline1]
=== idx_RepoObject_gross2++__++1

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-RepoObject_guid>>; uniqueidentifier
--
* PK, Unique, Real: 0, 0, 0


[#index-idxunderlinerepoobjectunderlinegross2underlineunderline2]
=== idx_RepoObject_gross2++__++2

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-usp_persistence_RepoObject_guid>>; uniqueidentifier
--
* PK, Unique, Real: 0, 0, 0


[#index-idxunderlinerepoobjectunderlinegross2underlineunderline3]
=== idx_RepoObject_gross2++__++3

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-SysObject_schema_name>>; nvarchar(128)
* <<column-SysObject_name>>; nvarchar(128)
--
* PK, Unique, Real: 0, 0, 0


[#index-idxunderlinerepoobjectunderlinegross2underlineunderline4]
=== idx_RepoObject_gross2++__++4

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-RepoObject_schema_name>>; nvarchar(128)
* <<column-RepoObject_name>>; nvarchar(128)
--
* PK, Unique, Real: 0, 0, 0


[#index-idxunderlinerepoobjectunderlinegross2underlineunderline5]
=== idx_RepoObject_gross2++__++5

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-uspgenerator_usp_id>>; int
--
* PK, Unique, Real: 0, 0, 0


[#index-idxunderlinerepoobjectunderlinegross2underlineunderline6]
=== idx_RepoObject_gross2++__++6

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-pk_index_guid>>; uniqueidentifier
--
* PK, Unique, Real: 0, 0, 0


[#index-idxunderlinerepoobjectunderlinegross2underlineunderline7]
=== idx_RepoObject_gross2++__++7

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-AntoraComponent>>; nvarchar(max)
--
* PK, Unique, Real: 0, 0, 0

// end::AntoraIndexList[]

== AntoraMeasureDetails

// tag::AntoraMeasureDetails[]

// end::AntoraMeasureDetails[]

== AntoraMeasureDescriptions



== AntoraParameterList

// tag::AntoraParameterList[]

// end::AntoraParameterList[]

== AntoraXrefCulturesList

// tag::AntoraXrefCulturesList[]
* xref:dhw:sqldb:repo.repoobject_gross2.adoc[] - 
// end::AntoraXrefCulturesList[]

== cultures_count

// tag::cultures_count[]
1
// end::cultures_count[]

== Other tags

source: property.RepoObjectProperty_cross As rop_cross


=== additional_reference_csv

// tag::additional_reference_csv[]

// end::additional_reference_csv[]


=== AdocUspSteps

// tag::adocuspsteps[]

// end::adocuspsteps[]


=== AntoraReferencedList

// tag::antorareferencedlist[]
* xref:dhw:sqldb:reference.repoobject_referencedlist.adoc[]
* xref:dhw:sqldb:reference.repoobject_referencinglist.adoc[]
* xref:dhw:sqldb:repo.repoobject_columnlist.adoc[]
* xref:dhw:sqldb:repo.repoobject_gross.adoc[]
* xref:dhw:sqldb:sqlparse.repoobject_sqlmodules_repo_sys.adoc[]
// end::antorareferencedlist[]


=== AntoraReferencingList

// tag::antorareferencinglist[]
* xref:dhw:sqldb:uspgenerator.generatoruspstep_persistence_src.adoc[]
// end::antorareferencinglist[]


=== Description

// tag::description[]

// end::description[]


=== exampleUsage

// tag::exampleusage[]

// end::exampleusage[]


=== exampleUsage_2

// tag::exampleusage_2[]

// end::exampleusage_2[]


=== exampleUsage_3

// tag::exampleusage_3[]

// end::exampleusage_3[]


=== exampleUsage_4

// tag::exampleusage_4[]

// end::exampleusage_4[]


=== exampleUsage_5

// tag::exampleusage_5[]

// end::exampleusage_5[]


=== exampleWrong_Usage

// tag::examplewrong_usage[]

// end::examplewrong_usage[]


=== has_execution_plan_issue

// tag::has_execution_plan_issue[]

// end::has_execution_plan_issue[]


=== has_get_referenced_issue

// tag::has_get_referenced_issue[]

// end::has_get_referenced_issue[]


=== has_history

// tag::has_history[]

// end::has_history[]


=== has_history_columns

// tag::has_history_columns[]

// end::has_history_columns[]


=== InheritanceType

// tag::inheritancetype[]

// end::inheritancetype[]


=== is_persistence

// tag::is_persistence[]

// end::is_persistence[]


=== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]

// end::is_persistence_check_duplicate_per_pk[]


=== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]

// end::is_persistence_check_for_empty_source[]


=== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]

// end::is_persistence_delete_changed[]


=== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]

// end::is_persistence_delete_missing[]


=== is_persistence_insert

// tag::is_persistence_insert[]

// end::is_persistence_insert[]


=== is_persistence_truncate

// tag::is_persistence_truncate[]

// end::is_persistence_truncate[]


=== is_persistence_update_changed

// tag::is_persistence_update_changed[]

// end::is_persistence_update_changed[]


=== is_repo_managed

// tag::is_repo_managed[]
0
// end::is_repo_managed[]


=== is_ssas

// tag::is_ssas[]
0
// end::is_ssas[]


=== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


=== MS_Description

// tag::ms_description[]

// end::ms_description[]


=== persistence_source_RepoObject_fullname

// tag::persistence_source_repoobject_fullname[]

// end::persistence_source_repoobject_fullname[]


=== persistence_source_RepoObject_fullname2

// tag::persistence_source_repoobject_fullname2[]

// end::persistence_source_repoobject_fullname2[]


=== persistence_source_RepoObject_guid

// tag::persistence_source_repoobject_guid[]

// end::persistence_source_repoobject_guid[]


=== persistence_source_RepoObject_xref

// tag::persistence_source_repoobject_xref[]

// end::persistence_source_repoobject_xref[]


=== pk_index_guid

// tag::pk_index_guid[]

// end::pk_index_guid[]


=== pk_IndexPatternColumnDatatype

// tag::pk_indexpatterncolumndatatype[]

// end::pk_indexpatterncolumndatatype[]


=== pk_IndexPatternColumnName

// tag::pk_indexpatterncolumnname[]

// end::pk_indexpatterncolumnname[]


=== pk_IndexSemanticGroup

// tag::pk_indexsemanticgroup[]

// end::pk_indexsemanticgroup[]


=== ReferencedObjectList

// tag::referencedobjectlist[]
* [reference].[RepoObject_ReferencedList]
* [reference].[RepoObject_ReferencingList]
* [repo].[RepoObject_ColumnList]
* [repo].[RepoObject_gross]
* [sqlparse].[RepoObject_SqlModules_Repo_Sys]
// end::referencedobjectlist[]


=== usp_persistence_RepoObject_guid

// tag::usp_persistence_repoobject_guid[]

// end::usp_persistence_repoobject_guid[]


=== UspExamples

// tag::uspexamples[]

// end::uspexamples[]


=== uspgenerator_usp_id

// tag::uspgenerator_usp_id[]

// end::uspgenerator_usp_id[]


=== UspParameters

// tag::uspparameters[]

// end::uspparameters[]

== Boolean Attributes

source: property.RepoObjectProperty WHERE property_int = 1

// tag::boolean_attributes[]


// end::boolean_attributes[]

== PlantUML diagrams

=== PlantUML Entity

// tag::puml_entity[]
[plantuml, entity-{docname}, svg, subs=macros]
....
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:repo.repoobject_gross2.adoc[]" as repo.RepoObject_gross2 << V >> {
  AntoraComponent : (nvarchar(max))
  AntoraModule : (nvarchar(max))
  AntoraReferencedList : (nvarchar(max))
  AntoraReferencingList : (nvarchar(max))
  CreateColumnList : (nvarchar(max))
  DbmlColumnList : (nvarchar(max))
  Description : (nvarchar(max))
  external_AntoraComponent : (nvarchar(128))
  external_AntoraModule : (nvarchar(128))
  external_DatabaseName : (nvarchar(128))
  external_RepoDatabaseName : (nvarchar(128))
  has_different_sys_names : (bit)
  has_execution_plan_issue : (bit)
  has_get_referenced_issue : (bit)
  has_history : (bit)
  has_history_columns : (bit)
  history_schema_name : (nvarchar(128))
  history_table_name : (nvarchar(128))
  indent_sql_modules_definition : (tinyint)
  Inheritance_StringAggSeparatorSql : (nvarchar(4000))
  InheritanceDefinition : (nvarchar(4000))
  InheritanceType : (tinyint)
  - is_DocsExclude : (bit)
  is_DocsOutput : (int)
  - is_external : (bit)
  - is_in_reference : (int)
  is_persistence : (bit)
  is_persistence_check_duplicate_per_pk : (bit)
  is_persistence_check_for_empty_source : (bit)
  is_persistence_delete_changed : (bit)
  is_persistence_delete_missing : (bit)
  is_persistence_insert : (bit)
  is_persistence_merge_delete_missing : (bit)
  is_persistence_merge_insert : (bit)
  is_persistence_merge_update_changed : (bit)
  is_persistence_persist_source : (bit)
  is_persistence_truncate : (bit)
  is_persistence_update_changed : (bit)
  is_repo_managed : (bit)
  - is_RepoObject_name_uniqueidentifier : (int)
  is_required_ObjectMerge : (bit)
  - is_ssas : (bit)
  is_SysObject_missing : (bit)
  - is_SysObject_name_uniqueidentifier : (int)
  - modify_dt : (datetime)
  node_id : (bigint)
  persistence_source_RepoObject_fullname : (nvarchar(261))
  persistence_source_RepoObject_fullname2 : (nvarchar(257))
  persistence_source_RepoObject_guid : (uniqueidentifier)
  persistence_source_RepoObject_xref : (nvarchar(4000))
  persistence_source_SysObject_fullname : (nvarchar(261))
  persistence_source_SysObject_fullname_or_tempsource : (nvarchar(261))
  persistence_source_SysObject_fullname2 : (nvarchar(257))
  persistence_source_SysObject_xref : (nvarchar(4000))
  PersistenceCompareColumnList : (nvarchar(max))
  PersistenceInsertColumnList : (nvarchar(max))
  PersistenceUpdateColumnList : (nvarchar(max))
  pk_index_guid : (uniqueidentifier)
  pk_IndexPatternColumnDatatype : (nvarchar(4000))
  pk_IndexPatternColumnName : (nvarchar(4000))
  pk_IndexPatternColumnName_new : (nvarchar(4000))
  pk_IndexSemanticGroup : (nvarchar(512))
  postscript : (nvarchar(max))
  prescript : (nvarchar(max))
  Property_ms_description : (nvarchar(4000))
  Repo_history_table_guid : (uniqueidentifier)
  Repo_temporal_type : (tinyint)
  - RepoObject_fullname : (nvarchar(261))
  - RepoObject_fullname2 : (nvarchar(257))
  - RepoObject_guid : (uniqueidentifier)
  - RepoObject_name : (nvarchar(128))
  RepoObject_Referencing_Count : (int)
  - RepoObject_schema_name : (nvarchar(128))
  - RepoObject_type : (char(2))
  RepoObject_type_name : (nvarchar(128))
  sql_modules_antora : (nvarchar(max))
  sql_modules_definition : (nvarchar(max))
  sql_modules_formatted : (nvarchar(max))
  sql_modules_formatted2 : (nvarchar(max))
  - SysObject_fullname : (nvarchar(261))
  - SysObject_fullname2 : (nvarchar(257))
  SysObject_id : (int)
  SysObject_modify_date : (datetime)
  - SysObject_name : (nvarchar(128))
  - SysObject_parent_object_id : (int)
  SysObject_query_executed_dt : (datetime)
  SysObject_query_plan : (xml)
  - SysObject_query_sql : (nvarchar(406))
  - SysObject_schema_name : (nvarchar(128))
  SysObject_type : (char(2))
  SysObject_type_name : (nvarchar(128))
  tables_dataCategory : (nvarchar(500))
  tables_description : (nvarchar(max))
  tables_isHidden : (bit)
  temporal_type : (tinyint)
  - usp_persistence_name : (nvarchar(140))
  usp_persistence_RepoObject_guid : (uniqueidentifier)
  uspgenerator_usp_id : (int)
  --
}
....

// end::puml_entity[]

=== PlantUML Entity 1 1 FK

// tag::puml_entity_1_1_fk[]
[plantuml, entity_1_1_fk-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:repo.repoobject_gross2.adoc[]" as repo.RepoObject_gross2 << V >> {
- idx_RepoObject_gross2__1

..
RepoObject_guid; uniqueidentifier
--
- idx_RepoObject_gross2__2

..
usp_persistence_RepoObject_guid; uniqueidentifier
--
- idx_RepoObject_gross2__3

..
SysObject_schema_name; nvarchar(128)
SysObject_name; nvarchar(128)
--
- idx_RepoObject_gross2__4

..
RepoObject_schema_name; nvarchar(128)
RepoObject_name; nvarchar(128)
--
- idx_RepoObject_gross2__5

..
uspgenerator_usp_id; int
--
- idx_RepoObject_gross2__6

..
pk_index_guid; uniqueidentifier
--
- idx_RepoObject_gross2__7

..
AntoraComponent; nvarchar(max)
}



footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_fk[]

=== PlantUML 1 1 ObjectRef

// tag::puml_entity_1_1_objectref[]
[plantuml, entity_1_1_objectref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:reference.repoobject_referencedlist.adoc[]" as reference.RepoObject_ReferencedList << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_referencinglist.adoc[]" as reference.RepoObject_ReferencingList << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_columnlist.adoc[]" as repo.RepoObject_ColumnList << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_gross.adoc[]" as repo.RepoObject_gross << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_gross2.adoc[]" as repo.RepoObject_gross2 << V >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_repo_sys.adoc[]" as sqlparse.RepoObject_SqlModules_Repo_Sys << V >> {
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.generatoruspstep_persistence_src.adoc[]" as uspgenerator.GeneratorUspStep_Persistence_src << V >> {
  - **usp_id** : (int)
  --
}

reference.RepoObject_ReferencedList <.. repo.RepoObject_gross2
reference.RepoObject_ReferencingList <.. repo.RepoObject_gross2
repo.RepoObject_ColumnList <.. repo.RepoObject_gross2
repo.RepoObject_gross <.. repo.RepoObject_gross2
repo.RepoObject_gross2 <.. uspgenerator.GeneratorUspStep_Persistence_src
sqlparse.RepoObject_SqlModules_Repo_Sys <.. repo.RepoObject_gross2

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_objectref[]

=== PlantUML 30 0 ObjectRef

// tag::puml_entity_30_0_objectref[]
[plantuml, entity_30_0_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:config.ftv_dwh_database.adoc[]" as config.ftv_dwh_database << IF >> {
  --
}

entity "puml-link:dhw:sqldb:config.ftv_get_parameter_value.adoc[]" as config.ftv_get_parameter_value << IF >> {
  --
}

entity "puml-link:dhw:sqldb:config.parameter.adoc[]" as config.Parameter << U >> {
  - **Parameter_name** : (varchar(100))
  - **sub_Parameter** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:configt.join_type.adoc[]" as configT.join_type << V >> {
  - **join_type** : (varchar(16))
  --
}

entity "puml-link:dhw:sqldb:configt.parameter_default.adoc[]" as configT.Parameter_default << V >> {
  - **Parameter_name** : (varchar(52))
  - **sub_Parameter** : (nvarchar(26))
  --
}

entity "puml-link:dhw:sqldb:configt.spt_values.adoc[]" as configT.spt_values << U >> {
  --
}

entity "puml-link:dhw:sqldb:configt.type.adoc[]" as configT.type << V >> {
  **type** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:docs.fs_cleanstringforanchorid.adoc[]" as docs.fs_cleanStringForAnchorId << FN >> {
  --
}

entity "puml-link:dhw:sqldb:docs.fs_cleanstringforfilename.adoc[]" as docs.fs_cleanStringForFilename << FN >> {
  --
}

entity "puml-link:dhw:sqldb:property.external_repoobjectcolumnproperty.adoc[]" as property.external_RepoObjectColumnProperty << U >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.external_repoobjectproperty.adoc[]" as property.external_RepoObjectProperty << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.fs_get_repoobjectcolumnproperty_nvarchar.adoc[]" as property.fs_get_RepoObjectColumnProperty_nvarchar << FN >> {
  --
}

entity "puml-link:dhw:sqldb:property.fs_get_repoobjectproperty_nvarchar.adoc[]" as property.fs_get_RepoObjectProperty_nvarchar << FN >> {
  --
}

entity "puml-link:dhw:sqldb:property.propertyname_repoobject.adoc[]" as property.PropertyName_RepoObject << V >> {
  **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.propertyname_repoobject_t.adoc[]" as property.PropertyName_RepoObject_T << U >> {
  **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectcolumnproperty.adoc[]" as property.RepoObjectColumnProperty << U >> {
  - **RepoObjectColumnProperty_id** : (int)
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectcolumnproperty_external_src.adoc[]" as property.RepoObjectColumnProperty_external_src << V >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectcolumnproperty_external_tgt.adoc[]" as property.RepoObjectColumnProperty_external_tgt << V >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty.adoc[]" as property.RepoObjectProperty << U >> {
  - **RepoObjectProperty_id** : (int)
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty_external_src.adoc[]" as property.RepoObjectProperty_external_src << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty_external_tgt.adoc[]" as property.RepoObjectProperty_external_tgt << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty_selectedpropertyname_split.adoc[]" as property.RepoObjectProperty_SelectedPropertyName_split << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference.adoc[]" as reference.additional_Reference << U >> {
  - **Id** : (int)
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_database.adoc[]" as reference.additional_Reference_database << V >> {
  - **AntoraComponent** : (nvarchar(128))
  - **AntoraModule** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_database_t.adoc[]" as reference.additional_Reference_database_T << U >> {
  - **AntoraComponent** : (nvarchar(128))
  - **AntoraModule** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_from_properties_src.adoc[]" as reference.additional_Reference_from_properties_src << V >> {
  **referenced_AntoraComponent** : (nvarchar(max))
  **referenced_AntoraModule** : (nvarchar(max))
  **referenced_Schema** : (nvarchar(max))
  **referenced_Object** : (nvarchar(max))
  **referenced_Column** : (nvarchar(max))
  **referencing_AntoraComponent** : (nvarchar(max))
  **referencing_AntoraModule** : (nvarchar(max))
  **referencing_Schema** : (nvarchar(max))
  **referencing_Object** : (nvarchar(max))
  **referencing_Column** : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_from_properties_tgt.adoc[]" as reference.additional_Reference_from_properties_tgt << V >> {
  **referenced_AntoraComponent** : (nvarchar(max))
  **referenced_AntoraModule** : (nvarchar(max))
  **referenced_Schema** : (nvarchar(max))
  **referenced_Object** : (nvarchar(max))
  **referenced_Column** : (nvarchar(max))
  **referencing_AntoraComponent** : (nvarchar(max))
  **referencing_AntoraModule** : (nvarchar(max))
  **referencing_Schema** : (nvarchar(max))
  **referencing_Object** : (nvarchar(max))
  **referencing_Column** : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_from_ssas_src.adoc[]" as reference.additional_Reference_from_ssas_src << V >> {
  **referenced_AntoraComponent** : (nvarchar(128))
  **referenced_AntoraModule** : (nvarchar(128))
  **referenced_Schema** : (nvarchar(max))
  **referenced_Object** : (nvarchar(max))
  **referenced_Column** : (nvarchar(500))
  **referencing_AntoraComponent** : (nvarchar(max))
  **referencing_AntoraModule** : (nvarchar(max))
  - **referencing_Schema** : (nvarchar(128))
  - **referencing_Object** : (nvarchar(128))
  **referencing_Column** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_from_ssas_tgt.adoc[]" as reference.additional_Reference_from_ssas_tgt << V >> {
  **referenced_AntoraComponent** : (nvarchar(128))
  **referenced_AntoraModule** : (nvarchar(128))
  **referenced_Schema** : (nvarchar(max))
  **referenced_Object** : (nvarchar(max))
  **referenced_Column** : (nvarchar(500))
  **referencing_AntoraComponent** : (nvarchar(max))
  **referencing_AntoraModule** : (nvarchar(max))
  - **referencing_Schema** : (nvarchar(128))
  - **referencing_Object** : (nvarchar(128))
  **referencing_Column** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_guid.adoc[]" as reference.additional_Reference_guid << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_is_external.adoc[]" as reference.additional_Reference_is_external << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_object.adoc[]" as reference.additional_Reference_Object << V >> {
  - **AntoraComponent** : (nvarchar(128))
  - **AntoraModule** : (nvarchar(128))
  - **SchemaName** : (nvarchar(128))
  - **ObjectName** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_object_t.adoc[]" as reference.additional_Reference_Object_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_objectcolumn.adoc[]" as reference.additional_Reference_ObjectColumn << V >> {
  - **AntoraComponent** : (nvarchar(128))
  - **AntoraModule** : (nvarchar(128))
  - **SchemaName** : (nvarchar(128))
  - **ObjectName** : (nvarchar(128))
  **ColumnName** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_objectcolumn_t.adoc[]" as reference.additional_Reference_ObjectColumn_T << U >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_wo_columns_from_properties_src.adoc[]" as reference.additional_Reference_wo_columns_from_properties_src << V >> {
  **referenced_AntoraComponent** : (nvarchar(max))
  **referenced_AntoraModule** : (nvarchar(max))
  **referenced_Schema** : (nvarchar(max))
  **referenced_Object** : (nvarchar(max))
  **referencing_AntoraComponent** : (nvarchar(max))
  **referencing_AntoraModule** : (nvarchar(max))
  **referencing_Schema** : (nvarchar(max))
  **referencing_Object** : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_wo_columns_from_properties_tgt.adoc[]" as reference.additional_Reference_wo_columns_from_properties_tgt << V >> {
  **referenced_AntoraComponent** : (nvarchar(max))
  **referenced_AntoraModule** : (nvarchar(max))
  **referenced_Schema** : (nvarchar(max))
  **referenced_Object** : (nvarchar(max))
  **referencing_AntoraComponent** : (nvarchar(max))
  **referencing_AntoraModule** : (nvarchar(max))
  **referencing_Schema** : (nvarchar(max))
  **referencing_Object** : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_queryplan.adoc[]" as reference.RepoObject_QueryPlan << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_reference.adoc[]" as reference.RepoObject_reference << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_reference_additional.adoc[]" as reference.RepoObject_reference_additional << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_reference_persistence.adoc[]" as reference.RepoObject_reference_persistence << V >> {
  **referenced_RepoObject_guid** : (uniqueidentifier)
  - **referencing_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_reference_persistence_target_as_source.adoc[]" as reference.RepoObject_reference_persistence_target_as_source << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_reference_sqlexpressiondependencies.adoc[]" as reference.RepoObject_reference_SqlExpressionDependencies << V >> {
  **referenced_RepoObject_guid** : (uniqueidentifier)
  **referencing_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_reference_t.adoc[]" as reference.RepoObject_reference_T << U >> {
  **referenced_RepoObject_guid** : (uniqueidentifier)
  **referencing_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_reference_union.adoc[]" as reference.RepoObject_reference_union << V >> {
  **referenced_RepoObject_guid** : (uniqueidentifier)
  **referencing_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_reference_virtual.adoc[]" as reference.RepoObject_reference_virtual << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_referencedlist.adoc[]" as reference.RepoObject_ReferencedList << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_referencedreferencing.adoc[]" as reference.RepoObject_ReferencedReferencing << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_referencinglist.adoc[]" as reference.RepoObject_ReferencingList << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_reference.adoc[]" as reference.RepoObjectColumn_reference << V >> {
  **referenced_RepoObjectColumn_guid** : (uniqueidentifier)
  **referencing_RepoObjectColumn_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_reference_additional.adoc[]" as reference.RepoObjectColumn_reference_additional << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_reference_persistence.adoc[]" as reference.RepoObjectColumn_reference_Persistence << V >> {
  **referencing_id** : (int)
  **referencing_minor_id** : (int)
  **referenced_id** : (int)
  **referenced_minor_id** : (int)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_reference_sqlexpressiondependencies.adoc[]" as reference.RepoObjectColumn_reference_SqlExpressionDependencies << V >> {
  - **referencing_id** : (int)
  - **referencing_minor_id** : (int)
  **referenced_id** : (int)
  - **referenced_minor_id** : (int)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_reference_sqlmodules.adoc[]" as reference.RepoObjectColumn_reference_SqlModules << V >> {
  **referencing_id** : (int)
  **referencing_minor_id** : (int)
  **referenced_id** : (int)
  **referenced_minor_id** : (int)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_reference_t.adoc[]" as reference.RepoObjectColumn_reference_T << U >> {
  **referenced_RepoObjectColumn_guid** : (uniqueidentifier)
  **referencing_RepoObjectColumn_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_reference_union.adoc[]" as reference.RepoObjectColumn_reference_union << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_reference_virtual.adoc[]" as reference.RepoObjectColumn_reference_virtual << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_referencedlist.adoc[]" as reference.RepoObjectColumn_ReferencedList << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_referencedreferencing.adoc[]" as reference.RepoObjectColumn_ReferencedReferencing << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_referencinglist.adoc[]" as reference.RepoObjectColumn_ReferencingList << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumnsource_virtual.adoc[]" as reference.RepoObjectColumnSource_virtual << U >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  - **Source_RepoObjectColumn_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectsource_virtual.adoc[]" as reference.RepoObjectSource_virtual << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **Source_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.index_settings.adoc[]" as repo.Index_Settings << U >> {
  - **index_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.index_ssas.adoc[]" as repo.Index_ssas << V >> {
  - **databasename** : (nvarchar(128))
  **index_name** : (nvarchar(450))
  --
}

entity "puml-link:dhw:sqldb:repo.index_ssas_t.adoc[]" as repo.Index_ssas_T << U >> {
  - **databasename** : (nvarchar(128))
  **index_name** : (nvarchar(450))
  --
}

entity "puml-link:dhw:sqldb:repo.index_virtual.adoc[]" as repo.Index_virtual << U >> {
  - **index_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.indexcolumn_ssas.adoc[]" as repo.IndexColumn_ssas << V >> {
  - **index_guid** : (uniqueidentifier)
  - **index_column_id** : (int)
  --
}

entity "puml-link:dhw:sqldb:repo.indexcolumn_ssas_gross.adoc[]" as repo.IndexColumn_ssas_gross << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.indexcolumn_ssas_t.adoc[]" as repo.IndexColumn_ssas_T << U >> {
  - **index_guid** : (uniqueidentifier)
  - **index_column_id** : (int)
  --
}

entity "puml-link:dhw:sqldb:repo.indexcolumn_union.adoc[]" as repo.IndexColumn_union << V >> {
  **index_guid** : (uniqueidentifier)
  - **index_column_id** : (int)
  --
}

entity "puml-link:dhw:sqldb:repo.indexcolumn_union_t.adoc[]" as repo.IndexColumn_union_T << U >> {
  **index_guid** : (uniqueidentifier)
  - **index_column_id** : (int)
  --
}

entity "puml-link:dhw:sqldb:repo.indexcolumn_virtual.adoc[]" as repo.IndexColumn_virtual << U >> {
  - **index_guid** : (uniqueidentifier)
  - **index_column_id** : (int)
  --
}

entity "puml-link:dhw:sqldb:repo.indexcolumn_virtual_gross.adoc[]" as repo.IndexColumn_virtual_gross << V >> {
  - **index_column_id** : (int)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject.adoc[]" as repo.RepoObject << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_columnlist.adoc[]" as repo.RepoObject_ColumnList << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_external_src.adoc[]" as repo.RepoObject_external_src << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_external_tgt.adoc[]" as repo.RepoObject_external_tgt << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_gross.adoc[]" as repo.RepoObject_gross << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_gross_persistence.adoc[]" as repo.RepoObject_gross_persistence << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_gross2.adoc[]" as repo.RepoObject_gross2 << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_persistence.adoc[]" as repo.RepoObject_persistence << U >> {
  - **target_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_ssas_src.adoc[]" as repo.RepoObject_SSAS_src << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_ssas_tgt.adoc[]" as repo.RepoObject_SSAS_tgt << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn.adoc[]" as repo.RepoObjectColumn << U >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn_external_src.adoc[]" as repo.RepoObjectColumn_external_src << V >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn_external_tgt.adoc[]" as repo.RepoObjectColumn_external_tgt << V >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn_gross.adoc[]" as repo.RepoObjectColumn_gross << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn_gross2.adoc[]" as repo.RepoObjectColumn_gross2 << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn_ssas_src.adoc[]" as repo.RepoObjectColumn_SSAS_src << V >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn_ssas_tgt.adoc[]" as repo.RepoObjectColumn_SSAS_tgt << V >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.reposchema.adoc[]" as repo.RepoSchema << U >> {
  - **RepoSchema_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.reposchema_ssas_src.adoc[]" as repo.RepoSchema_ssas_src << V >> {
  - **RepoSchema_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:repo.reposchema_ssas_tgt.adoc[]" as repo.RepoSchema_ssas_tgt << V >> {
  - **RepoSchema_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.syscolumn_repoobjectcolumn_via_name.adoc[]" as repo.SysColumn_RepoObjectColumn_via_name << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.sysobject_repoobject_via_name.adoc[]" as repo.SysObject_RepoObject_via_name << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo_sys.extendedproperties.adoc[]" as repo_sys.ExtendedProperties << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo_sys.indexcolumn_unique.adoc[]" as repo_sys.IndexColumn_unique << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo_sys.sql_expression_dependencies.adoc[]" as repo_sys.sql_expression_dependencies << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo_sys.syscolumn.adoc[]" as repo_sys.SysColumn << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo_sys.sysobject.adoc[]" as repo_sys.SysObject << V >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.ftv_sqlparse.adoc[]" as sqlparse.ftv_sqlparse << IF >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.ftv_sqlparse_children_pivot.adoc[]" as sqlparse.ftv_sqlparse_children_pivot << IF >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.ftv_sqlparse_with_some_children.adoc[]" as sqlparse.ftv_sqlparse_with_some_children << IF >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules.adoc[]" as sqlparse.RepoObject_SqlModules << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_10_statement.adoc[]" as sqlparse.RepoObject_SqlModules_10_statement << V >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_20_statement_children.adoc[]" as sqlparse.RepoObject_SqlModules_20_statement_children << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **json_key** : (nvarchar(4000))
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_21_statement_children_helper.adoc[]" as sqlparse.RepoObject_SqlModules_21_statement_children_helper << V >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_22_identifier_alias_as.adoc[]" as sqlparse.RepoObject_SqlModules_22_identifier_alias_AS << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **json_key** : (nvarchar(4000))
  **RowNumber** : (bigint)
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_24_identifierlist_children.adoc[]" as sqlparse.RepoObject_SqlModules_24_IdentifierList_children << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **json_key** : (nvarchar(4000))
  - **T2_json_key** : (nvarchar(4000))
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_25_identifierlist_children_identifiersplit.adoc[]" as sqlparse.RepoObject_SqlModules_25_IdentifierList_children_IdentifierSplit << V >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_26_identifierlist_children_identifiersplit_quotename.adoc[]" as sqlparse.RepoObject_SqlModules_26_IdentifierList_children_IdentifierSplit_QuoteName << V >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_29_1_object_is_union.adoc[]" as sqlparse.RepoObject_SqlModules_29_1_object_is_union << V >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_29_2_object_is_groupby.adoc[]" as sqlparse.RepoObject_SqlModules_29_2_object_is_GroupBy << V >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_31_object.adoc[]" as sqlparse.RepoObject_SqlModules_31_object << V >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_32_objectclass.adoc[]" as sqlparse.RepoObject_SqlModules_32_ObjectClass << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  **class** : (nvarchar(500))
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_33_objectnormalized.adoc[]" as sqlparse.RepoObject_SqlModules_33_ObjectNormalized << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  **normalized** : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_39_object.adoc[]" as sqlparse.RepoObject_SqlModules_39_object << V >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_41_from.adoc[]" as sqlparse.RepoObject_SqlModules_41_from << V >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_41_from_t.adoc[]" as sqlparse.RepoObject_SqlModules_41_from_T << U >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_42_from_identifier.adoc[]" as sqlparse.RepoObject_SqlModules_42_from_Identifier << V >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_43_from_identifier.adoc[]" as sqlparse.RepoObject_SqlModules_43_from_Identifier << V >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_44_from_identifier_quotename.adoc[]" as sqlparse.RepoObject_SqlModules_44_from_Identifier_QuoteName << V >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_51_identitfier.adoc[]" as sqlparse.RepoObject_SqlModules_51_Identitfier << V >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_52_identitfier_quotename.adoc[]" as sqlparse.RepoObject_SqlModules_52_Identitfier_QuoteName << V >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_61_selectidentifier_union.adoc[]" as sqlparse.RepoObject_SqlModules_61_SelectIdentifier_Union << V >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_61_selectidentifier_union_t.adoc[]" as sqlparse.RepoObject_SqlModules_61_SelectIdentifier_Union_T << U >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_71_reference_explicitetablealias.adoc[]" as sqlparse.RepoObject_SqlModules_71_reference_ExpliciteTableAlias << V >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_72_reference_notablealias.adoc[]" as sqlparse.RepoObject_SqlModules_72_reference_NoTableAlias << V >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_79_reference_union.adoc[]" as sqlparse.RepoObject_SqlModules_79_reference_union << V >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_repo_sys.adoc[]" as sqlparse.RepoObject_SqlModules_Repo_Sys << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.additional_reference_step1.adoc[]" as ssas.additional_Reference_step1 << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.indexcolumn_from_iskey.adoc[]" as ssas.IndexColumn_from_IsKey << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.indexcolumn_from_isunique.adoc[]" as ssas.IndexColumn_from_IsUnique << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.indexcolumn_from_relationship.adoc[]" as ssas.IndexColumn_from_Relationship << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.indexcolumn_union.adoc[]" as ssas.IndexColumn_union << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json.adoc[]" as ssas.model_json << U >> {
  - **databasename** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_10.adoc[]" as ssas.model_json_10 << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_20.adoc[]" as ssas.model_json_20 << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_201_descriptions_multiline.adoc[]" as ssas.model_json_201_descriptions_multiline << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_2011_descriptions_stragg.adoc[]" as ssas.model_json_2011_descriptions_StrAgg << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31_tables.adoc[]" as ssas.model_json_31_tables << V >> {
  - **databasename** : (nvarchar(128))
  **tables_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31_tables_t.adoc[]" as ssas.model_json_31_tables_T << U >> {
  - **databasename** : (nvarchar(128))
  **tables_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_311_tables_columns.adoc[]" as ssas.model_json_311_tables_columns << V >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  **tables_columns_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_311_tables_columns_t.adoc[]" as ssas.model_json_311_tables_columns_T << U >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  **tables_columns_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_3111_tables_columns_descriptions_multiline.adoc[]" as ssas.model_json_3111_tables_columns_descriptions_multiline << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31111_tables_columns_descriptions_stragg.adoc[]" as ssas.model_json_31111_tables_columns_descriptions_StrAgg << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_3112_tables_columns_expressions_multiline.adoc[]" as ssas.model_json_3112_tables_columns_expressions_multiline << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31121_tables_columns_expressions_stragg.adoc[]" as ssas.model_json_31121_tables_columns_expressions_StrAgg << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_313_tables_partitions.adoc[]" as ssas.model_json_313_tables_partitions << V >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  **tables_partitions_name** : (nvarchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_3131_tables_partitions_source.adoc[]" as ssas.model_json_3131_tables_partitions_source << V >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  **tables_partitions_name** : (nvarchar(500))
  **tables_partitions_source_name** : (nvarchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31311_tables_partitions_source_posfrom.adoc[]" as ssas.model_json_31311_tables_partitions_source_PosFrom << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_313111_tables_partitions_source_stringfrom.adoc[]" as ssas.model_json_313111_tables_partitions_source_StringFrom << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_3131111_tables_partitions_source_posdot.adoc[]" as ssas.model_json_3131111_tables_partitions_source_PosDot << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31311111_tables_partitions_source_part123.adoc[]" as ssas.model_json_31311111_tables_partitions_source_Part123 << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_316_tables_descriptions_multiline.adoc[]" as ssas.model_json_316_tables_descriptions_multiline << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_3161_tables_descriptions_stragg.adoc[]" as ssas.model_json_3161_tables_descriptions_StrAgg << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_32_relationships.adoc[]" as ssas.model_json_32_relationships << V >> {
  - **databasename** : (nvarchar(128))
  **relationships_name** : (nvarchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_32_relationships_t.adoc[]" as ssas.model_json_32_relationships_T << U >> {
  - **ForeignKey_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_33_datasources.adoc[]" as ssas.model_json_33_dataSources << V >> {
  - **databasename** : (nvarchar(128))
  **dataSources_name** : (nvarchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_33_datasources_t.adoc[]" as ssas.model_json_33_dataSources_T << U >> {
  - **databasename** : (nvarchar(128))
  **dataSources_name** : (nvarchar(500))
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.columns.adoc[]" as sys_dwh.columns << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.computed_columns.adoc[]" as sys_dwh.computed_columns << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.default_constraints.adoc[]" as sys_dwh.default_constraints << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.extended_properties.adoc[]" as sys_dwh.extended_properties << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.identity_columns.adoc[]" as sys_dwh.identity_columns << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.index_columns.adoc[]" as sys_dwh.index_columns << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.indexes.adoc[]" as sys_dwh.indexes << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.objects.adoc[]" as sys_dwh.objects << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.parameters.adoc[]" as sys_dwh.parameters << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.schemas.adoc[]" as sys_dwh.schemas << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.sql_expression_dependencies.adoc[]" as sys_dwh.sql_expression_dependencies << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.sql_modules.adoc[]" as sys_dwh.sql_modules << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.tables.adoc[]" as sys_dwh.tables << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.types.adoc[]" as sys_dwh.types << SN >> {
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.generatorusp.adoc[]" as uspgenerator.GeneratorUsp << U >> {
  - **id** : (int)
  --
}

config.ftv_dwh_database <.. repo_sys.sql_expression_dependencies
config.ftv_dwh_database <.. repo_sys.ExtendedProperties
config.ftv_dwh_database <.. repo_sys.SysColumn
config.ftv_get_parameter_value <.. repo.RepoObject_external_src
config.ftv_get_parameter_value <.. ssas.additional_Reference_step1
config.ftv_get_parameter_value <.. reference.additional_Reference_is_external
config.ftv_get_parameter_value <.. repo.RepoObject_gross
config.Parameter <.. property.PropertyName_RepoObject
config.Parameter <.. config.ftv_get_parameter_value
config.Parameter <.. config.ftv_dwh_database
configT.join_type <.. sqlparse.RepoObject_SqlModules_41_from
configT.Parameter_default <.. config.Parameter
configT.spt_values <.. configT.type
configT.type <.. repo.RepoObject_gross_persistence
configT.type <.. reference.RepoObject_ReferencedReferencing
configT.type <.. repo.RepoObject_gross
docs.fs_cleanStringForAnchorId <.. reference.RepoObjectColumn_ReferencedReferencing
docs.fs_cleanStringForFilename <.. repo.RepoObject_gross_persistence
docs.fs_cleanStringForFilename <.. reference.RepoObject_ReferencedReferencing
docs.fs_cleanStringForFilename <.. repo.RepoObject_gross
docs.fs_cleanStringForFilename <.. reference.RepoObjectColumn_ReferencedReferencing
property.external_RepoObjectColumnProperty <.. property.RepoObjectColumnProperty_external_src
property.external_RepoObjectProperty <.. property.RepoObjectProperty_external_src
property.fs_get_RepoObjectColumnProperty_nvarchar <.. repo.RepoObjectColumn_gross
property.fs_get_RepoObjectProperty_nvarchar <.. repo.RepoObject_gross
property.PropertyName_RepoObject <.. property.PropertyName_RepoObject_T
property.PropertyName_RepoObject_T <.. property.RepoObjectProperty_external_tgt
property.PropertyName_RepoObject_T <.. property.RepoObjectColumnProperty_external_tgt
property.RepoObjectColumnProperty <.. property.fs_get_RepoObjectColumnProperty_nvarchar
property.RepoObjectColumnProperty_external_src <.. property.RepoObjectColumnProperty_external_tgt
property.RepoObjectColumnProperty_external_tgt <.. property.RepoObjectColumnProperty
property.RepoObjectProperty <.. property.fs_get_RepoObjectProperty_nvarchar
property.RepoObjectProperty <.. property.RepoObjectProperty_SelectedPropertyName_split
property.RepoObjectProperty <.. property.PropertyName_RepoObject
property.RepoObjectProperty_external_src <.. property.RepoObjectProperty_external_tgt
property.RepoObjectProperty_external_tgt <.. property.RepoObjectProperty
property.RepoObjectProperty_SelectedPropertyName_split <.. reference.additional_Reference_from_properties_src
property.RepoObjectProperty_SelectedPropertyName_split <.. reference.additional_Reference_wo_columns_from_properties_src
reference.additional_Reference <.. reference.additional_Reference_guid
reference.additional_Reference <.. reference.additional_Reference_is_external
reference.additional_Reference_database <.. reference.additional_Reference_database_T
reference.additional_Reference_database_T <.. repo.RepoObject_gross
reference.additional_Reference_from_properties_src <.. reference.additional_Reference_from_properties_tgt
reference.additional_Reference_from_properties_tgt <.. reference.additional_Reference
reference.additional_Reference_from_ssas_src <.. reference.additional_Reference_from_ssas_tgt
reference.additional_Reference_from_ssas_tgt <.. reference.additional_Reference
reference.additional_Reference_guid <.. reference.RepoObject_reference_additional
reference.additional_Reference_guid <.. reference.RepoObjectColumn_reference_additional
reference.additional_Reference_is_external <.. reference.additional_Reference_ObjectColumn
reference.additional_Reference_is_external <.. reference.additional_Reference_database
reference.additional_Reference_is_external <.. reference.additional_Reference_Object
reference.additional_Reference_Object <.. reference.additional_Reference_Object_T
reference.additional_Reference_Object_T <.. repo.RepoObject_external_src
reference.additional_Reference_Object_T <.. repo.RepoObjectColumn_external_src
reference.additional_Reference_ObjectColumn <.. reference.additional_Reference_ObjectColumn_T
reference.additional_Reference_ObjectColumn_T <.. repo.RepoObjectColumn_external_src
reference.additional_Reference_wo_columns_from_properties_src <.. reference.additional_Reference_wo_columns_from_properties_tgt
reference.additional_Reference_wo_columns_from_properties_tgt <.. reference.additional_Reference
reference.RepoObject_QueryPlan <.. repo.RepoObject_gross
reference.RepoObject_reference <.. reference.RepoObject_reference_T
reference.RepoObject_reference_additional <.. reference.RepoObject_reference_union
reference.RepoObject_reference_persistence <.. reference.RepoObject_reference_union
reference.RepoObject_reference_persistence_target_as_source <.. reference.RepoObject_reference_union
reference.RepoObject_reference_persistence_target_as_source <.. reference.RepoObject_reference
reference.RepoObject_reference_SqlExpressionDependencies <.. reference.RepoObject_reference_persistence_target_as_source
reference.RepoObject_reference_SqlExpressionDependencies <.. reference.RepoObject_reference_union
reference.RepoObject_reference_T <.. reference.RepoObjectColumn_reference_virtual
reference.RepoObject_reference_T <.. reference.RepoObjectColumn_reference_additional
reference.RepoObject_reference_T <.. reference.RepoObject_ReferencedReferencing
reference.RepoObject_reference_T <.. reference.RepoObjectColumn_reference_SqlExpressionDependencies
reference.RepoObject_reference_union <.. reference.RepoObject_reference
reference.RepoObject_reference_virtual <.. reference.RepoObject_reference_union
reference.RepoObject_ReferencedList <.. repo.RepoObject_gross2
reference.RepoObject_ReferencedReferencing <.. reference.RepoObject_ReferencedList
reference.RepoObject_ReferencedReferencing <.. reference.RepoObject_ReferencingList
reference.RepoObject_ReferencedReferencing <.. repo.RepoObject_gross
reference.RepoObject_ReferencingList <.. repo.RepoObject_gross2
reference.RepoObjectColumn_reference <.. reference.RepoObjectColumn_reference_T
reference.RepoObjectColumn_reference_additional <.. reference.RepoObjectColumn_reference_union
reference.RepoObjectColumn_reference_Persistence <.. reference.RepoObjectColumn_reference_union
reference.RepoObjectColumn_reference_SqlExpressionDependencies <.. reference.RepoObjectColumn_reference_union
reference.RepoObjectColumn_reference_SqlModules <.. reference.RepoObjectColumn_reference_union
reference.RepoObjectColumn_reference_T <.. reference.RepoObjectColumn_ReferencedReferencing
reference.RepoObjectColumn_reference_union <.. reference.RepoObjectColumn_reference
reference.RepoObjectColumn_reference_virtual <.. reference.RepoObjectColumn_reference_union
reference.RepoObjectColumn_ReferencedList <.. repo.RepoObjectColumn_gross2
reference.RepoObjectColumn_ReferencedReferencing <.. reference.RepoObjectColumn_ReferencingList
reference.RepoObjectColumn_ReferencedReferencing <.. reference.RepoObjectColumn_ReferencedList
reference.RepoObjectColumn_ReferencingList <.. repo.RepoObjectColumn_gross2
reference.RepoObjectColumnSource_virtual <.. reference.RepoObjectColumn_reference_virtual
reference.RepoObjectSource_virtual <.. reference.RepoObject_reference_virtual
repo.Index_Settings <.. repo.RepoObject_gross
repo.Index_ssas <.. repo.Index_ssas_T
repo.Index_ssas_T <.. repo.IndexColumn_ssas
repo.Index_ssas_T <.. repo.IndexColumn_ssas_gross
repo.Index_virtual <.. repo.IndexColumn_virtual_gross
repo.IndexColumn_ssas <.. repo.IndexColumn_ssas_T
repo.IndexColumn_ssas_gross <.. repo.IndexColumn_union
repo.IndexColumn_ssas_T <.. repo.IndexColumn_ssas_gross
repo.IndexColumn_union <.. repo.IndexColumn_union_T
repo.IndexColumn_union_T <.. repo.RepoObjectColumn_gross2
repo.IndexColumn_virtual <.. repo.IndexColumn_virtual_gross
repo.IndexColumn_virtual_gross <.. repo.IndexColumn_union
repo.RepoObject <.. reference.RepoObject_reference_persistence
repo.RepoObject <.. repo.SysObject_RepoObject_via_name
repo.RepoObject <.. repo.SysColumn_RepoObjectColumn_via_name
repo.RepoObject <.. sqlparse.RepoObject_SqlModules_39_object
repo.RepoObject <.. sqlparse.RepoObject_SqlModules_10_statement
repo.RepoObject <.. reference.RepoObjectColumn_reference_Persistence
repo.RepoObject <.. repo.IndexColumn_virtual_gross
repo.RepoObject <.. repo.RepoObject_external_src
repo.RepoObject <.. reference.RepoObject_reference_virtual
repo.RepoObject <.. reference.additional_Reference_guid
repo.RepoObject <.. reference.RepoObject_reference_SqlExpressionDependencies
repo.RepoObject <.. sqlparse.RepoObject_SqlModules_Repo_Sys
repo.RepoObject <.. repo.RepoObjectColumn_gross
repo.RepoObject <.. repo.RepoObject_gross
repo.RepoObject <.. sqlparse.RepoObject_SqlModules_71_reference_ExpliciteTableAlias
repo.RepoObject <.. sqlparse.RepoObject_SqlModules_72_reference_NoTableAlias
repo.RepoObject <.. reference.RepoObjectColumn_reference_SqlModules
repo.RepoObject <.. property.RepoObjectProperty_external_tgt
repo.RepoObject <.. repo.IndexColumn_ssas_gross
repo.RepoObject <.. property.RepoObjectColumnProperty_external_tgt
repo.RepoObject <.. repo.RepoObjectColumn_external_src
repo.RepoObject <.. repo.RepoObject_gross_persistence
repo.RepoObject_ColumnList <.. repo.RepoObject_gross2
repo.RepoObject_external_src <.. repo.RepoObject_external_tgt
repo.RepoObject_external_tgt <.. repo.RepoObject
repo.RepoObject_external_tgt <.. repo.RepoObjectColumn_external_tgt
repo.RepoObject_gross <.. repo.RepoObject_gross2
repo.RepoObject_gross_persistence <.. reference.RepoObject_reference_persistence_target_as_source
repo.RepoObject_persistence <.. repo.RepoObject_gross_persistence
repo.RepoObject_persistence <.. repo.RepoObject_gross
repo.RepoObject_persistence <.. repo.RepoObjectColumn_gross
repo.RepoObject_persistence <.. reference.RepoObject_reference_persistence
repo.RepoObject_persistence <.. reference.RepoObjectColumn_reference_Persistence
repo.RepoObject_SSAS_src <.. repo.RepoObject_SSAS_tgt
repo.RepoObject_SSAS_tgt <.. repo.RepoObjectColumn_SSAS_tgt
repo.RepoObject_SSAS_tgt <.. repo.RepoObject
repo.RepoObjectColumn <.. repo.RepoObjectColumn_gross2
repo.RepoObjectColumn <.. repo.IndexColumn_ssas_gross
repo.RepoObjectColumn <.. sqlparse.RepoObject_SqlModules_72_reference_NoTableAlias
repo.RepoObjectColumn <.. reference.RepoObjectColumn_reference_SqlModules
repo.RepoObjectColumn <.. property.RepoObjectColumnProperty_external_tgt
repo.RepoObjectColumn <.. repo.SysColumn_RepoObjectColumn_via_name
repo.RepoObjectColumn <.. reference.RepoObjectColumn_reference_Persistence
repo.RepoObjectColumn <.. repo.IndexColumn_virtual_gross
repo.RepoObjectColumn <.. reference.additional_Reference_guid
repo.RepoObjectColumn <.. sqlparse.RepoObject_SqlModules_71_reference_ExpliciteTableAlias
repo.RepoObjectColumn <.. repo.RepoObjectColumn_gross
repo.RepoObjectColumn_external_src <.. repo.RepoObjectColumn_external_tgt
repo.RepoObjectColumn_external_tgt <.. repo.RepoObjectColumn
repo.RepoObjectColumn_gross <.. reference.RepoObjectColumn_reference_virtual
repo.RepoObjectColumn_gross <.. repo.RepoObjectColumn_gross2
repo.RepoObjectColumn_gross2 <.. repo.RepoObject_ColumnList
repo.RepoObjectColumn_SSAS_src <.. repo.RepoObjectColumn_SSAS_tgt
repo.RepoObjectColumn_SSAS_tgt <.. repo.RepoObjectColumn
repo.RepoSchema <.. repo.RepoObject_SSAS_src
repo.RepoSchema_ssas_src <.. repo.RepoSchema_ssas_tgt
repo.RepoSchema_ssas_tgt <.. repo.RepoSchema
repo.SysColumn_RepoObjectColumn_via_name <.. repo_sys.sql_expression_dependencies
repo.SysColumn_RepoObjectColumn_via_name <.. repo_sys.IndexColumn_unique
repo.SysObject_RepoObject_via_name <.. repo_sys.IndexColumn_unique
repo.SysObject_RepoObject_via_name <.. repo_sys.sql_expression_dependencies
repo_sys.ExtendedProperties <.. repo_sys.SysObject
repo_sys.ExtendedProperties <.. repo_sys.SysColumn
repo_sys.IndexColumn_unique <.. repo.IndexColumn_union
repo_sys.sql_expression_dependencies <.. reference.RepoObject_reference_SqlExpressionDependencies
repo_sys.sql_expression_dependencies <.. reference.RepoObjectColumn_reference_SqlExpressionDependencies
repo_sys.SysColumn <.. repo.SysColumn_RepoObjectColumn_via_name
repo_sys.SysObject <.. repo.SysObject_RepoObject_via_name
repo_sys.SysObject <.. repo_sys.SysColumn
repo_sys.SysObject <.. sqlparse.RepoObject_SqlModules_Repo_Sys
sqlparse.ftv_sqlparse <.. sqlparse.RepoObject_SqlModules_22_identifier_alias_AS
sqlparse.ftv_sqlparse_children_pivot <.. sqlparse.RepoObject_SqlModules_25_IdentifierList_children_IdentifierSplit
sqlparse.ftv_sqlparse_with_some_children <.. sqlparse.RepoObject_SqlModules_20_statement_children
sqlparse.ftv_sqlparse_with_some_children <.. sqlparse.RepoObject_SqlModules_24_IdentifierList_children
sqlparse.RepoObject_SqlModules <.. sqlparse.RepoObject_SqlModules_Repo_Sys
sqlparse.RepoObject_SqlModules <.. sqlparse.RepoObject_SqlModules_39_object
sqlparse.RepoObject_SqlModules <.. sqlparse.RepoObject_SqlModules_10_statement
sqlparse.RepoObject_SqlModules_10_statement <.. sqlparse.RepoObject_SqlModules_20_statement_children
sqlparse.RepoObject_SqlModules_20_statement_children <.. sqlparse.RepoObject_SqlModules_29_1_object_is_union
sqlparse.RepoObject_SqlModules_20_statement_children <.. sqlparse.RepoObject_SqlModules_21_statement_children_helper
sqlparse.RepoObject_SqlModules_20_statement_children <.. sqlparse.RepoObject_SqlModules_22_identifier_alias_AS
sqlparse.RepoObject_SqlModules_20_statement_children <.. sqlparse.RepoObject_SqlModules_33_ObjectNormalized
sqlparse.RepoObject_SqlModules_20_statement_children <.. sqlparse.RepoObject_SqlModules_29_2_object_is_GroupBy
sqlparse.RepoObject_SqlModules_20_statement_children <.. sqlparse.RepoObject_SqlModules_32_ObjectClass
sqlparse.RepoObject_SqlModules_20_statement_children <.. sqlparse.RepoObject_SqlModules_51_Identitfier
sqlparse.RepoObject_SqlModules_20_statement_children <.. sqlparse.RepoObject_SqlModules_41_from
sqlparse.RepoObject_SqlModules_20_statement_children <.. sqlparse.RepoObject_SqlModules_24_IdentifierList_children
sqlparse.RepoObject_SqlModules_21_statement_children_helper <.. sqlparse.RepoObject_SqlModules_31_object
sqlparse.RepoObject_SqlModules_22_identifier_alias_AS <.. sqlparse.RepoObject_SqlModules_41_from
sqlparse.RepoObject_SqlModules_24_IdentifierList_children <.. sqlparse.RepoObject_SqlModules_25_IdentifierList_children_IdentifierSplit
sqlparse.RepoObject_SqlModules_25_IdentifierList_children_IdentifierSplit <.. sqlparse.RepoObject_SqlModules_26_IdentifierList_children_IdentifierSplit_QuoteName
sqlparse.RepoObject_SqlModules_26_IdentifierList_children_IdentifierSplit_QuoteName <.. sqlparse.RepoObject_SqlModules_61_SelectIdentifier_Union
sqlparse.RepoObject_SqlModules_29_1_object_is_union <.. sqlparse.RepoObject_SqlModules_39_object
sqlparse.RepoObject_SqlModules_29_1_object_is_union <.. sqlparse.RepoObject_SqlModules_42_from_Identifier
sqlparse.RepoObject_SqlModules_29_2_object_is_GroupBy <.. sqlparse.RepoObject_SqlModules_39_object
sqlparse.RepoObject_SqlModules_31_object <.. sqlparse.RepoObject_SqlModules_39_object
sqlparse.RepoObject_SqlModules_32_ObjectClass <.. sqlparse.RepoObject_SqlModules_39_object
sqlparse.RepoObject_SqlModules_33_ObjectNormalized <.. sqlparse.RepoObject_SqlModules_39_object
sqlparse.RepoObject_SqlModules_39_object <.. sqlparse.RepoObject_SqlModules_41_from
sqlparse.RepoObject_SqlModules_39_object <.. sqlparse.RepoObject_SqlModules_61_SelectIdentifier_Union
sqlparse.RepoObject_SqlModules_41_from <.. sqlparse.RepoObject_SqlModules_41_from_T
sqlparse.RepoObject_SqlModules_41_from_T <.. sqlparse.RepoObject_SqlModules_42_from_Identifier
sqlparse.RepoObject_SqlModules_42_from_Identifier <.. sqlparse.RepoObject_SqlModules_43_from_Identifier
sqlparse.RepoObject_SqlModules_43_from_Identifier <.. sqlparse.RepoObject_SqlModules_44_from_Identifier_QuoteName
sqlparse.RepoObject_SqlModules_44_from_Identifier_QuoteName <.. sqlparse.RepoObject_SqlModules_71_reference_ExpliciteTableAlias
sqlparse.RepoObject_SqlModules_44_from_Identifier_QuoteName <.. sqlparse.RepoObject_SqlModules_72_reference_NoTableAlias
sqlparse.RepoObject_SqlModules_51_Identitfier <.. sqlparse.RepoObject_SqlModules_52_Identitfier_QuoteName
sqlparse.RepoObject_SqlModules_52_Identitfier_QuoteName <.. sqlparse.RepoObject_SqlModules_61_SelectIdentifier_Union
sqlparse.RepoObject_SqlModules_61_SelectIdentifier_Union <.. sqlparse.RepoObject_SqlModules_61_SelectIdentifier_Union_T
sqlparse.RepoObject_SqlModules_61_SelectIdentifier_Union_T <.. sqlparse.RepoObject_SqlModules_71_reference_ExpliciteTableAlias
sqlparse.RepoObject_SqlModules_61_SelectIdentifier_Union_T <.. sqlparse.RepoObject_SqlModules_72_reference_NoTableAlias
sqlparse.RepoObject_SqlModules_71_reference_ExpliciteTableAlias <.. sqlparse.RepoObject_SqlModules_79_reference_union
sqlparse.RepoObject_SqlModules_72_reference_NoTableAlias <.. sqlparse.RepoObject_SqlModules_79_reference_union
sqlparse.RepoObject_SqlModules_79_reference_union <.. reference.RepoObjectColumn_reference_SqlModules
sqlparse.RepoObject_SqlModules_Repo_Sys <.. repo.RepoObject_gross2
ssas.additional_Reference_step1 <.. reference.additional_Reference_from_ssas_src
ssas.IndexColumn_from_IsKey <.. ssas.IndexColumn_union
ssas.IndexColumn_from_IsUnique <.. ssas.IndexColumn_union
ssas.IndexColumn_from_Relationship <.. ssas.IndexColumn_union
ssas.IndexColumn_union <.. repo.IndexColumn_ssas
ssas.IndexColumn_union <.. repo.Index_ssas
ssas.model_json <.. ssas.model_json_10
ssas.model_json_10 <.. ssas.model_json_20
ssas.model_json_20 <.. repo.RepoSchema_ssas_src
ssas.model_json_20 <.. ssas.model_json_32_relationships
ssas.model_json_20 <.. ssas.model_json_201_descriptions_multiline
ssas.model_json_20 <.. ssas.model_json_31_tables
ssas.model_json_20 <.. ssas.model_json_33_dataSources
ssas.model_json_201_descriptions_multiline <.. ssas.model_json_2011_descriptions_StrAgg
ssas.model_json_2011_descriptions_StrAgg <.. repo.RepoSchema_ssas_src
ssas.model_json_31_tables <.. ssas.model_json_31_tables_T
ssas.model_json_31_tables_T <.. ssas.model_json_311_tables_columns
ssas.model_json_31_tables_T <.. repo.RepoObject_SSAS_src
ssas.model_json_31_tables_T <.. repo.RepoObject_gross
ssas.model_json_31_tables_T <.. ssas.model_json_316_tables_descriptions_multiline
ssas.model_json_31_tables_T <.. ssas.model_json_313_tables_partitions
ssas.model_json_311_tables_columns <.. ssas.model_json_311_tables_columns_T
ssas.model_json_311_tables_columns_T <.. repo.RepoObjectColumn_gross
ssas.model_json_311_tables_columns_T <.. ssas.IndexColumn_from_IsKey
ssas.model_json_311_tables_columns_T <.. ssas.model_json_3112_tables_columns_expressions_multiline
ssas.model_json_311_tables_columns_T <.. ssas.model_json_3111_tables_columns_descriptions_multiline
ssas.model_json_311_tables_columns_T <.. repo.RepoObjectColumn_SSAS_src
ssas.model_json_311_tables_columns_T <.. ssas.IndexColumn_from_IsUnique
ssas.model_json_311_tables_columns_T <.. ssas.IndexColumn_from_Relationship
ssas.model_json_311_tables_columns_T <.. ssas.additional_Reference_step1
ssas.model_json_3111_tables_columns_descriptions_multiline <.. ssas.model_json_31111_tables_columns_descriptions_StrAgg
ssas.model_json_31111_tables_columns_descriptions_StrAgg <.. repo.RepoObjectColumn_gross
ssas.model_json_3112_tables_columns_expressions_multiline <.. ssas.model_json_31121_tables_columns_expressions_StrAgg
ssas.model_json_31121_tables_columns_expressions_StrAgg <.. repo.RepoObjectColumn_gross
ssas.model_json_313_tables_partitions <.. ssas.model_json_3131_tables_partitions_source
ssas.model_json_3131_tables_partitions_source <.. ssas.model_json_31311_tables_partitions_source_PosFrom
ssas.model_json_31311_tables_partitions_source_PosFrom <.. ssas.model_json_313111_tables_partitions_source_StringFrom
ssas.model_json_313111_tables_partitions_source_StringFrom <.. ssas.model_json_3131111_tables_partitions_source_PosDot
ssas.model_json_3131111_tables_partitions_source_PosDot <.. ssas.model_json_31311111_tables_partitions_source_Part123
ssas.model_json_31311111_tables_partitions_source_Part123 <.. ssas.additional_Reference_step1
ssas.model_json_316_tables_descriptions_multiline <.. ssas.model_json_3161_tables_descriptions_StrAgg
ssas.model_json_3161_tables_descriptions_StrAgg <.. repo.RepoObject_gross
ssas.model_json_32_relationships <.. ssas.model_json_32_relationships_T
ssas.model_json_32_relationships_T <.. ssas.IndexColumn_from_Relationship
ssas.model_json_33_dataSources <.. ssas.model_json_33_dataSources_T
ssas.model_json_33_dataSources_T <.. ssas.additional_Reference_step1
sys_dwh.columns <.. repo_sys.ExtendedProperties
sys_dwh.columns <.. repo_sys.SysColumn
sys_dwh.computed_columns <.. repo_sys.SysColumn
sys_dwh.default_constraints <.. repo_sys.SysColumn
sys_dwh.extended_properties <.. repo_sys.ExtendedProperties
sys_dwh.identity_columns <.. repo_sys.SysColumn
sys_dwh.index_columns <.. repo_sys.IndexColumn_unique
sys_dwh.indexes <.. repo_sys.ExtendedProperties
sys_dwh.indexes <.. repo_sys.IndexColumn_unique
sys_dwh.objects <.. repo_sys.ExtendedProperties
sys_dwh.objects <.. repo_sys.SysObject
sys_dwh.parameters <.. repo_sys.ExtendedProperties
sys_dwh.schemas <.. repo_sys.ExtendedProperties
sys_dwh.schemas <.. repo_sys.SysObject
sys_dwh.sql_expression_dependencies <.. repo_sys.sql_expression_dependencies
sys_dwh.sql_modules <.. repo_sys.SysObject
sys_dwh.tables <.. repo_sys.SysObject
sys_dwh.types <.. repo_sys.SysColumn
uspgenerator.GeneratorUsp <.. repo.RepoObject_gross

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_30_0_objectref[]

=== PlantUML 0 30 ObjectRef

// tag::puml_entity_0_30_objectref[]
[plantuml, entity_0_30_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:repo.repoobject_gross2.adoc[]" as repo.RepoObject_gross2 << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_main.adoc[]" as repo.usp_main << P >> {
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.generatoruspstep_persistence_src.adoc[]" as uspgenerator.GeneratorUspStep_Persistence_src << V >> {
  - **usp_id** : (int)
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.usp_generatorusp_insert_update_persistence.adoc[]" as uspgenerator.usp_GeneratorUsp_insert_update_persistence << P >> {
  --
}

repo.RepoObject_gross2 <.. uspgenerator.GeneratorUspStep_Persistence_src
uspgenerator.GeneratorUspStep_Persistence_src <.. uspgenerator.usp_GeneratorUsp_insert_update_persistence
uspgenerator.usp_GeneratorUsp_insert_update_persistence <.. repo.usp_main

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_0_30_objectref[]

=== PlantUML 1 1 ColumnRef

// tag::puml_entity_1_1_colref[]
[plantuml, entity_1_1_colref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:reference.repoobject_referencedlist.adoc[]" as reference.RepoObject_ReferencedList << V >> {
  AntoraReferencedList : (nvarchar(max))
  Referencing_fullname : (nvarchar(261))
  Referencing_fullname2 : (nvarchar(257))
  - Referencing_guid : (uniqueidentifier)
  Referencing_type : (varchar(2))
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_referencinglist.adoc[]" as reference.RepoObject_ReferencingList << V >> {
  AntoraReferencingList : (nvarchar(max))
  Referenced_fullname : (nvarchar(261))
  Referenced_fullname2 : (nvarchar(257))
  - Referenced_guid : (uniqueidentifier)
  Referenced_type : (char(2))
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_columnlist.adoc[]" as repo.RepoObject_ColumnList << V >> {
  CreateColumnList : (nvarchar(max))
  DbmlColumnList : (nvarchar(max))
  PersistenceCompareColumnList : (nvarchar(max))
  PersistenceInsertColumnList : (nvarchar(max))
  PersistenceUpdateColumnList : (nvarchar(max))
  - RepoObject_guid : (uniqueidentifier)
  RepoObjectColumn_fullname : (nvarchar(520))
  TemporalTableColumnList : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_gross.adoc[]" as repo.RepoObject_gross << V >> {
  AntoraComponent : (nvarchar(max))
  AntoraModule : (nvarchar(max))
  Description : (nvarchar(max))
  external_AntoraComponent : (nvarchar(128))
  external_AntoraModule : (nvarchar(128))
  external_DatabaseName : (nvarchar(128))
  external_RepoDatabaseName : (nvarchar(128))
  has_different_sys_names : (bit)
  has_execution_plan_issue : (bit)
  has_get_referenced_issue : (bit)
  has_history : (bit)
  has_history_columns : (bit)
  history_schema_name : (nvarchar(128))
  history_table_name : (nvarchar(128))
  indent_sql_modules_definition : (tinyint)
  Inheritance_StringAggSeparatorSql : (nvarchar(4000))
  InheritanceDefinition : (nvarchar(4000))
  InheritanceType : (tinyint)
  - is_DocsExclude : (bit)
  is_DocsOutput : (int)
  - is_external : (bit)
  - is_in_reference : (int)
  is_persistence : (bit)
  is_persistence_check_duplicate_per_pk : (bit)
  is_persistence_check_for_empty_source : (bit)
  is_persistence_delete_changed : (bit)
  is_persistence_delete_missing : (bit)
  is_persistence_insert : (bit)
  is_persistence_merge_delete_missing : (bit)
  is_persistence_merge_insert : (bit)
  is_persistence_merge_update_changed : (bit)
  is_persistence_persist_source : (bit)
  is_persistence_truncate : (bit)
  is_persistence_update_changed : (bit)
  is_repo_managed : (bit)
  - is_RepoObject_name_uniqueidentifier : (int)
  is_required_ObjectMerge : (bit)
  - is_ssas : (bit)
  is_SysObject_missing : (bit)
  - is_SysObject_name_uniqueidentifier : (int)
  - modify_dt : (datetime)
  node_id : (bigint)
  persistence_source_RepoObject_fullname : (nvarchar(261))
  persistence_source_RepoObject_fullname2 : (nvarchar(257))
  persistence_source_RepoObject_guid : (uniqueidentifier)
  persistence_source_RepoObject_xref : (nvarchar(4000))
  persistence_source_SysObject_fullname : (nvarchar(261))
  persistence_source_SysObject_fullname_or_tempsource : (nvarchar(261))
  persistence_source_SysObject_fullname2 : (nvarchar(257))
  persistence_source_SysObject_xref : (nvarchar(4000))
  pk_index_guid : (uniqueidentifier)
  pk_IndexPatternColumnDatatype : (nvarchar(4000))
  pk_IndexPatternColumnName : (nvarchar(4000))
  pk_IndexPatternColumnName_new : (nvarchar(4000))
  pk_IndexSemanticGroup : (nvarchar(512))
  postscript : (nvarchar(max))
  prescript : (nvarchar(max))
  Property_ms_description : (nvarchar(4000))
  Repo_history_table_guid : (uniqueidentifier)
  Repo_temporal_type : (tinyint)
  - RepoObject_fullname : (nvarchar(261))
  - RepoObject_fullname2 : (nvarchar(257))
  - RepoObject_guid : (uniqueidentifier)
  - RepoObject_name : (nvarchar(128))
  RepoObject_Referencing_Count : (int)
  - RepoObject_schema_name : (nvarchar(128))
  - RepoObject_type : (char(2))
  RepoObject_type_name : (nvarchar(128))
  - SysObject_fullname : (nvarchar(261))
  - SysObject_fullname2 : (nvarchar(257))
  SysObject_id : (int)
  SysObject_modify_date : (datetime)
  - SysObject_name : (nvarchar(128))
  - SysObject_parent_object_id : (int)
  SysObject_query_executed_dt : (datetime)
  SysObject_query_plan : (xml)
  - SysObject_query_sql : (nvarchar(406))
  - SysObject_schema_name : (nvarchar(128))
  SysObject_type : (char(2))
  SysObject_type_name : (nvarchar(128))
  tables_dataCategory : (nvarchar(500))
  tables_description : (nvarchar(max))
  tables_isHidden : (bit)
  temporal_type : (tinyint)
  - usp_persistence_name : (nvarchar(140))
  usp_persistence_RepoObject_guid : (uniqueidentifier)
  uspgenerator_usp_id : (int)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_gross2.adoc[]" as repo.RepoObject_gross2 << V >> {
  AntoraComponent : (nvarchar(max))
  AntoraModule : (nvarchar(max))
  AntoraReferencedList : (nvarchar(max))
  AntoraReferencingList : (nvarchar(max))
  CreateColumnList : (nvarchar(max))
  DbmlColumnList : (nvarchar(max))
  Description : (nvarchar(max))
  external_AntoraComponent : (nvarchar(128))
  external_AntoraModule : (nvarchar(128))
  external_DatabaseName : (nvarchar(128))
  external_RepoDatabaseName : (nvarchar(128))
  has_different_sys_names : (bit)
  has_execution_plan_issue : (bit)
  has_get_referenced_issue : (bit)
  has_history : (bit)
  has_history_columns : (bit)
  history_schema_name : (nvarchar(128))
  history_table_name : (nvarchar(128))
  indent_sql_modules_definition : (tinyint)
  Inheritance_StringAggSeparatorSql : (nvarchar(4000))
  InheritanceDefinition : (nvarchar(4000))
  InheritanceType : (tinyint)
  - is_DocsExclude : (bit)
  is_DocsOutput : (int)
  - is_external : (bit)
  - is_in_reference : (int)
  is_persistence : (bit)
  is_persistence_check_duplicate_per_pk : (bit)
  is_persistence_check_for_empty_source : (bit)
  is_persistence_delete_changed : (bit)
  is_persistence_delete_missing : (bit)
  is_persistence_insert : (bit)
  is_persistence_merge_delete_missing : (bit)
  is_persistence_merge_insert : (bit)
  is_persistence_merge_update_changed : (bit)
  is_persistence_persist_source : (bit)
  is_persistence_truncate : (bit)
  is_persistence_update_changed : (bit)
  is_repo_managed : (bit)
  - is_RepoObject_name_uniqueidentifier : (int)
  is_required_ObjectMerge : (bit)
  - is_ssas : (bit)
  is_SysObject_missing : (bit)
  - is_SysObject_name_uniqueidentifier : (int)
  - modify_dt : (datetime)
  node_id : (bigint)
  persistence_source_RepoObject_fullname : (nvarchar(261))
  persistence_source_RepoObject_fullname2 : (nvarchar(257))
  persistence_source_RepoObject_guid : (uniqueidentifier)
  persistence_source_RepoObject_xref : (nvarchar(4000))
  persistence_source_SysObject_fullname : (nvarchar(261))
  persistence_source_SysObject_fullname_or_tempsource : (nvarchar(261))
  persistence_source_SysObject_fullname2 : (nvarchar(257))
  persistence_source_SysObject_xref : (nvarchar(4000))
  PersistenceCompareColumnList : (nvarchar(max))
  PersistenceInsertColumnList : (nvarchar(max))
  PersistenceUpdateColumnList : (nvarchar(max))
  pk_index_guid : (uniqueidentifier)
  pk_IndexPatternColumnDatatype : (nvarchar(4000))
  pk_IndexPatternColumnName : (nvarchar(4000))
  pk_IndexPatternColumnName_new : (nvarchar(4000))
  pk_IndexSemanticGroup : (nvarchar(512))
  postscript : (nvarchar(max))
  prescript : (nvarchar(max))
  Property_ms_description : (nvarchar(4000))
  Repo_history_table_guid : (uniqueidentifier)
  Repo_temporal_type : (tinyint)
  - RepoObject_fullname : (nvarchar(261))
  - RepoObject_fullname2 : (nvarchar(257))
  - RepoObject_guid : (uniqueidentifier)
  - RepoObject_name : (nvarchar(128))
  RepoObject_Referencing_Count : (int)
  - RepoObject_schema_name : (nvarchar(128))
  - RepoObject_type : (char(2))
  RepoObject_type_name : (nvarchar(128))
  sql_modules_antora : (nvarchar(max))
  sql_modules_definition : (nvarchar(max))
  sql_modules_formatted : (nvarchar(max))
  sql_modules_formatted2 : (nvarchar(max))
  - SysObject_fullname : (nvarchar(261))
  - SysObject_fullname2 : (nvarchar(257))
  SysObject_id : (int)
  SysObject_modify_date : (datetime)
  - SysObject_name : (nvarchar(128))
  - SysObject_parent_object_id : (int)
  SysObject_query_executed_dt : (datetime)
  SysObject_query_plan : (xml)
  - SysObject_query_sql : (nvarchar(406))
  - SysObject_schema_name : (nvarchar(128))
  SysObject_type : (char(2))
  SysObject_type_name : (nvarchar(128))
  tables_dataCategory : (nvarchar(500))
  tables_description : (nvarchar(max))
  tables_isHidden : (bit)
  temporal_type : (tinyint)
  - usp_persistence_name : (nvarchar(140))
  usp_persistence_RepoObject_guid : (uniqueidentifier)
  uspgenerator_usp_id : (int)
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_repo_sys.adoc[]" as sqlparse.RepoObject_SqlModules_Repo_Sys << V >> {
  is_json_sql_modules_json : (int)
  is_outdated : (bit)
  - modify_date : (datetime)
  - RepoObject_guid : (uniqueidentifier)
  sql_modules_definition : (nvarchar(max))
  sql_modules_dt : (datetime)
  sql_modules_formatted : (nvarchar(max))
  sql_modules_formatted2 : (nvarchar(max))
  sql_modules_json : (nvarchar(max))
  SysObject_type : (char(2))
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.generatoruspstep_persistence_src.adoc[]" as uspgenerator.GeneratorUspStep_Persistence_src << V >> {
  - **usp_id** : (int)
  - has_logging : (int)
  - is_condition : (int)
  - is_inactive : (int)
  - is_SubProcedure : (int)
  log_flag_InsertUpdateDelete : (varchar(1))
  log_source_object : (nvarchar(261))
  log_target_object : (nvarchar(261))
  - Name : (varchar(45))
  - Number : (int)
  Parent_Number : (int)
  - RepoObject_guid : (uniqueidentifier)
  Statement : (nvarchar(max))
  - usp_fullname : (nvarchar(261))
  --
}

reference.RepoObject_ReferencedList <.. repo.RepoObject_gross2
reference.RepoObject_ReferencingList <.. repo.RepoObject_gross2
repo.RepoObject_ColumnList <.. repo.RepoObject_gross2
repo.RepoObject_gross <.. repo.RepoObject_gross2
repo.RepoObject_gross2 <.. uspgenerator.GeneratorUspStep_Persistence_src
sqlparse.RepoObject_SqlModules_Repo_Sys <.. repo.RepoObject_gross2
"reference.RepoObject_ReferencedList::AntoraReferencedList" <-- "repo.RepoObject_gross2::AntoraReferencedList"
"reference.RepoObject_ReferencingList::AntoraReferencingList" <-- "repo.RepoObject_gross2::AntoraReferencingList"
"repo.RepoObject_ColumnList::CreateColumnList" <-- "repo.RepoObject_gross2::CreateColumnList"
"repo.RepoObject_ColumnList::DbmlColumnList" <-- "repo.RepoObject_gross2::DbmlColumnList"
"repo.RepoObject_ColumnList::PersistenceCompareColumnList" <-- "repo.RepoObject_gross2::PersistenceCompareColumnList"
"repo.RepoObject_ColumnList::PersistenceInsertColumnList" <-- "repo.RepoObject_gross2::PersistenceInsertColumnList"
"repo.RepoObject_ColumnList::PersistenceUpdateColumnList" <-- "repo.RepoObject_gross2::PersistenceUpdateColumnList"
"repo.RepoObject_gross::AntoraComponent" <-- "repo.RepoObject_gross2::AntoraComponent"
"repo.RepoObject_gross::AntoraModule" <-- "repo.RepoObject_gross2::AntoraModule"
"repo.RepoObject_gross::Description" <-- "repo.RepoObject_gross2::Description"
"repo.RepoObject_gross::external_AntoraComponent" <-- "repo.RepoObject_gross2::external_AntoraComponent"
"repo.RepoObject_gross::external_AntoraModule" <-- "repo.RepoObject_gross2::external_AntoraModule"
"repo.RepoObject_gross::external_DatabaseName" <-- "repo.RepoObject_gross2::external_DatabaseName"
"repo.RepoObject_gross::external_RepoDatabaseName" <-- "repo.RepoObject_gross2::external_RepoDatabaseName"
"repo.RepoObject_gross::has_different_sys_names" <-- "repo.RepoObject_gross2::has_different_sys_names"
"repo.RepoObject_gross::has_execution_plan_issue" <-- "repo.RepoObject_gross2::has_execution_plan_issue"
"repo.RepoObject_gross::has_get_referenced_issue" <-- "repo.RepoObject_gross2::has_get_referenced_issue"
"repo.RepoObject_gross::has_history" <-- "repo.RepoObject_gross2::has_history"
"repo.RepoObject_gross::has_history_columns" <-- "repo.RepoObject_gross2::has_history_columns"
"repo.RepoObject_gross::history_schema_name" <-- "repo.RepoObject_gross2::history_schema_name"
"repo.RepoObject_gross::history_table_name" <-- "repo.RepoObject_gross2::history_table_name"
"repo.RepoObject_gross::indent_sql_modules_definition" <-- "repo.RepoObject_gross2::indent_sql_modules_definition"
"repo.RepoObject_gross::Inheritance_StringAggSeparatorSql" <-- "repo.RepoObject_gross2::Inheritance_StringAggSeparatorSql"
"repo.RepoObject_gross::InheritanceDefinition" <-- "repo.RepoObject_gross2::InheritanceDefinition"
"repo.RepoObject_gross::InheritanceType" <-- "repo.RepoObject_gross2::InheritanceType"
"repo.RepoObject_gross::is_DocsExclude" <-- "repo.RepoObject_gross2::is_DocsExclude"
"repo.RepoObject_gross::is_DocsOutput" <-- "repo.RepoObject_gross2::is_DocsOutput"
"repo.RepoObject_gross::is_external" <-- "repo.RepoObject_gross2::is_external"
"repo.RepoObject_gross::is_in_reference" <-- "repo.RepoObject_gross2::is_in_reference"
"repo.RepoObject_gross::is_persistence" <-- "repo.RepoObject_gross2::is_persistence"
"repo.RepoObject_gross::is_persistence_check_duplicate_per_pk" <-- "repo.RepoObject_gross2::is_persistence_check_duplicate_per_pk"
"repo.RepoObject_gross::is_persistence_check_for_empty_source" <-- "repo.RepoObject_gross2::is_persistence_check_for_empty_source"
"repo.RepoObject_gross::is_persistence_delete_changed" <-- "repo.RepoObject_gross2::is_persistence_delete_changed"
"repo.RepoObject_gross::is_persistence_delete_missing" <-- "repo.RepoObject_gross2::is_persistence_delete_missing"
"repo.RepoObject_gross::is_persistence_insert" <-- "repo.RepoObject_gross2::is_persistence_insert"
"repo.RepoObject_gross::is_persistence_merge_delete_missing" <-- "repo.RepoObject_gross2::is_persistence_merge_delete_missing"
"repo.RepoObject_gross::is_persistence_merge_insert" <-- "repo.RepoObject_gross2::is_persistence_merge_insert"
"repo.RepoObject_gross::is_persistence_merge_update_changed" <-- "repo.RepoObject_gross2::is_persistence_merge_update_changed"
"repo.RepoObject_gross::is_persistence_persist_source" <-- "repo.RepoObject_gross2::is_persistence_persist_source"
"repo.RepoObject_gross::is_persistence_truncate" <-- "repo.RepoObject_gross2::is_persistence_truncate"
"repo.RepoObject_gross::is_persistence_update_changed" <-- "repo.RepoObject_gross2::is_persistence_update_changed"
"repo.RepoObject_gross::is_repo_managed" <-- "repo.RepoObject_gross2::is_repo_managed"
"repo.RepoObject_gross::is_RepoObject_name_uniqueidentifier" <-- "repo.RepoObject_gross2::is_RepoObject_name_uniqueidentifier"
"repo.RepoObject_gross::is_required_ObjectMerge" <-- "repo.RepoObject_gross2::is_required_ObjectMerge"
"repo.RepoObject_gross::is_ssas" <-- "repo.RepoObject_gross2::is_ssas"
"repo.RepoObject_gross::is_SysObject_missing" <-- "repo.RepoObject_gross2::is_SysObject_missing"
"repo.RepoObject_gross::is_SysObject_name_uniqueidentifier" <-- "repo.RepoObject_gross2::is_SysObject_name_uniqueidentifier"
"repo.RepoObject_gross::modify_dt" <-- "repo.RepoObject_gross2::modify_dt"
"repo.RepoObject_gross::node_id" <-- "repo.RepoObject_gross2::node_id"
"repo.RepoObject_gross::persistence_source_RepoObject_fullname" <-- "repo.RepoObject_gross2::persistence_source_RepoObject_fullname"
"repo.RepoObject_gross::persistence_source_RepoObject_fullname2" <-- "repo.RepoObject_gross2::persistence_source_RepoObject_fullname2"
"repo.RepoObject_gross::persistence_source_RepoObject_guid" <-- "repo.RepoObject_gross2::persistence_source_RepoObject_guid"
"repo.RepoObject_gross::persistence_source_RepoObject_xref" <-- "repo.RepoObject_gross2::persistence_source_RepoObject_xref"
"repo.RepoObject_gross::persistence_source_SysObject_fullname" <-- "repo.RepoObject_gross2::persistence_source_SysObject_fullname"
"repo.RepoObject_gross::persistence_source_SysObject_fullname_or_tempsource" <-- "repo.RepoObject_gross2::persistence_source_SysObject_fullname_or_tempsource"
"repo.RepoObject_gross::persistence_source_SysObject_fullname2" <-- "repo.RepoObject_gross2::persistence_source_SysObject_fullname2"
"repo.RepoObject_gross::persistence_source_SysObject_xref" <-- "repo.RepoObject_gross2::persistence_source_SysObject_xref"
"repo.RepoObject_gross::pk_index_guid" <-- "repo.RepoObject_gross2::pk_index_guid"
"repo.RepoObject_gross::pk_IndexPatternColumnDatatype" <-- "repo.RepoObject_gross2::pk_IndexPatternColumnDatatype"
"repo.RepoObject_gross::pk_IndexPatternColumnName" <-- "repo.RepoObject_gross2::pk_IndexPatternColumnName"
"repo.RepoObject_gross::pk_IndexPatternColumnName_new" <-- "repo.RepoObject_gross2::pk_IndexPatternColumnName_new"
"repo.RepoObject_gross::pk_IndexSemanticGroup" <-- "repo.RepoObject_gross2::pk_IndexSemanticGroup"
"repo.RepoObject_gross::postscript" <-- "repo.RepoObject_gross2::postscript"
"repo.RepoObject_gross::prescript" <-- "repo.RepoObject_gross2::prescript"
"repo.RepoObject_gross::Property_ms_description" <-- "repo.RepoObject_gross2::Property_ms_description"
"repo.RepoObject_gross::Repo_history_table_guid" <-- "repo.RepoObject_gross2::Repo_history_table_guid"
"repo.RepoObject_gross::Repo_temporal_type" <-- "repo.RepoObject_gross2::Repo_temporal_type"
"repo.RepoObject_gross::RepoObject_fullname" <-- "repo.RepoObject_gross2::RepoObject_fullname"
"repo.RepoObject_gross::RepoObject_fullname2" <-- "repo.RepoObject_gross2::RepoObject_fullname2"
"repo.RepoObject_gross::RepoObject_guid" <-- "repo.RepoObject_gross2::RepoObject_guid"
"repo.RepoObject_gross::RepoObject_name" <-- "repo.RepoObject_gross2::RepoObject_name"
"repo.RepoObject_gross::RepoObject_Referencing_Count" <-- "repo.RepoObject_gross2::RepoObject_Referencing_Count"
"repo.RepoObject_gross::RepoObject_schema_name" <-- "repo.RepoObject_gross2::RepoObject_schema_name"
"repo.RepoObject_gross::RepoObject_type" <-- "repo.RepoObject_gross2::RepoObject_type"
"repo.RepoObject_gross::RepoObject_type_name" <-- "repo.RepoObject_gross2::RepoObject_type_name"
"repo.RepoObject_gross::SysObject_fullname" <-- "repo.RepoObject_gross2::SysObject_fullname"
"repo.RepoObject_gross::SysObject_fullname2" <-- "repo.RepoObject_gross2::SysObject_fullname2"
"repo.RepoObject_gross::SysObject_id" <-- "repo.RepoObject_gross2::SysObject_id"
"repo.RepoObject_gross::SysObject_modify_date" <-- "repo.RepoObject_gross2::SysObject_modify_date"
"repo.RepoObject_gross::SysObject_name" <-- "repo.RepoObject_gross2::SysObject_name"
"repo.RepoObject_gross::SysObject_parent_object_id" <-- "repo.RepoObject_gross2::SysObject_parent_object_id"
"repo.RepoObject_gross::SysObject_query_executed_dt" <-- "repo.RepoObject_gross2::SysObject_query_executed_dt"
"repo.RepoObject_gross::SysObject_query_plan" <-- "repo.RepoObject_gross2::SysObject_query_plan"
"repo.RepoObject_gross::SysObject_query_sql" <-- "repo.RepoObject_gross2::SysObject_query_sql"
"repo.RepoObject_gross::SysObject_schema_name" <-- "repo.RepoObject_gross2::SysObject_schema_name"
"repo.RepoObject_gross::SysObject_type" <-- "repo.RepoObject_gross2::SysObject_type"
"repo.RepoObject_gross::SysObject_type_name" <-- "repo.RepoObject_gross2::SysObject_type_name"
"repo.RepoObject_gross::tables_dataCategory" <-- "repo.RepoObject_gross2::tables_dataCategory"
"repo.RepoObject_gross::tables_description" <-- "repo.RepoObject_gross2::tables_description"
"repo.RepoObject_gross::tables_isHidden" <-- "repo.RepoObject_gross2::tables_isHidden"
"repo.RepoObject_gross::temporal_type" <-- "repo.RepoObject_gross2::temporal_type"
"repo.RepoObject_gross::usp_persistence_name" <-- "repo.RepoObject_gross2::usp_persistence_name"
"repo.RepoObject_gross::usp_persistence_RepoObject_guid" <-- "repo.RepoObject_gross2::usp_persistence_RepoObject_guid"
"repo.RepoObject_gross::uspgenerator_usp_id" <-- "repo.RepoObject_gross2::uspgenerator_usp_id"
"sqlparse.RepoObject_SqlModules_Repo_Sys::sql_modules_definition" <-- "repo.RepoObject_gross2::sql_modules_definition"
"sqlparse.RepoObject_SqlModules_Repo_Sys::sql_modules_formatted" <-- "repo.RepoObject_gross2::sql_modules_formatted"
"sqlparse.RepoObject_SqlModules_Repo_Sys::sql_modules_formatted2" <-- "repo.RepoObject_gross2::sql_modules_formatted2"

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_colref[]


== sql_modules_definition

// tag::sql_modules_definition[]
[%collapsible]
=======
[source,sql,numbered,indent=0]
----

CREATE View repo.RepoObject_gross2
As
Select
    ro.RepoObject_guid
  , ro.RepoObject_schema_name
  , ro.RepoObject_name
  , ro.RepoObject_type
  , ro.RepoObject_type_name
  , ro.has_different_sys_names
  , ro.has_execution_plan_issue
  , ro.has_get_referenced_issue
  , ro.indent_sql_modules_definition
  , ro.Inheritance_StringAggSeparatorSql
  , ro.InheritanceDefinition
  , ro.InheritanceType
  , ro.is_DocsExclude
  , ro.is_DocsOutput
  , ro.is_in_reference
  , ro.is_repo_managed
  , ro.is_ssas
  , ro.is_required_ObjectMerge
  , ro.is_RepoObject_name_uniqueidentifier
  , ro.is_SysObject_missing
  , ro.is_SysObject_name_uniqueidentifier
  , ro.modify_dt
  , ro.node_id
  , ro.pk_index_guid
  , ro.pk_IndexPatternColumnDatatype
  , ro.pk_IndexPatternColumnName
  , ro.pk_IndexPatternColumnName_new
  , ro.pk_IndexSemanticGroup
  , ro.Repo_history_table_guid
  , ro.Repo_temporal_type
  , ro.RepoObject_fullname
  , ro.RepoObject_fullname2
  , ro.RepoObject_Referencing_Count
  , ro.SysObject_fullname
  , ro.SysObject_fullname2
  , ro.SysObject_id
  , ro.SysObject_modify_date
  , ro.SysObject_name
  , ro.SysObject_parent_object_id
  , ro.SysObject_query_executed_dt
  , ro.SysObject_query_plan
  , ro.SysObject_query_sql
  , ro.SysObject_schema_name
  , ro.SysObject_type
  , ro.SysObject_type_name
  , ro.external_AntoraComponent
  , ro.external_AntoraModule
  , ro.external_DatabaseName
  , ro.external_RepoDatabaseName
  , ro.is_external
  , ro.AntoraComponent
  , ro.AntoraModule
  , ro.usp_persistence_name
  , ro.usp_persistence_RepoObject_guid
  , ro.persistence_source_RepoObject_guid
  , ro.persistence_source_RepoObject_fullname
  , ro.persistence_source_RepoObject_fullname2
  , ro.persistence_source_RepoObject_xref
  , ro.persistence_source_SysObject_fullname
  , ro.persistence_source_SysObject_fullname_or_tempsource
  , ro.persistence_source_SysObject_fullname2
  , ro.persistence_source_SysObject_xref
  , ro.uspgenerator_usp_id
  , ro.has_history
  , ro.has_history_columns
  , ro.is_persistence
  , ro.is_persistence_check_duplicate_per_pk
  , ro.is_persistence_check_for_empty_source
  , ro.is_persistence_delete_missing
  , ro.is_persistence_delete_changed
  , ro.is_persistence_insert
  , ro.is_persistence_truncate
  , ro.is_persistence_update_changed
  , ro.is_persistence_merge_delete_missing
  , ro.is_persistence_merge_insert
  , ro.is_persistence_merge_update_changed
  , ro.is_persistence_persist_source
  , ro.history_schema_name
  , ro.history_table_name
  , prescript          = ro.prescript
  , postscript         = ro.postscript
  , ro.temporal_type
  , ro.Description
  , ro.Property_ms_description
  , ro.tables_dataCategory
  , ro.tables_isHidden
  , ro.tables_description
  , ColumnList.CreateColumnList
  , ColumnList.DbmlColumnList
  , ColumnList.PersistenceCompareColumnList
  , ColumnList.PersistenceInsertColumnList
  , ColumnList.PersistenceUpdateColumnList
  , SqlModules.sql_modules_definition
  , sql_modules_antora = Replace (
                                     Replace (
                                                 Replace ( SqlModules.sql_modules_definition, '\include::', '\\include::' )
                                               , '\ifdef::'
                                               , '\\ifdef::'
                                             )
                                   , '\endif::'
                                   , '\\endif::'
                                 )
  , SqlModules.sql_modules_formatted
  , SqlModules.sql_modules_formatted2
  , ro_referenced.AntoraReferencedList
  , ro_referencing.AntoraReferencingList
--, ext_referenced.AntoraExternalReferencedList
--, ext_referencing.AntoraExternalReferencingList
--, AntoraModule       = AntoraModule.Parameter_value_result
--, AntoraComponent    = AntoraComponent.Parameter_value_result
From
    repo.RepoObject_gross                       As ro
    Left Outer Join
        repo.RepoObject_ColumnList              As ColumnList
            On
            ColumnList.RepoObject_guid     = ro.RepoObject_guid

    Left Outer Join
        sqlparse.RepoObject_SqlModules_Repo_Sys As SqlModules
            On
            SqlModules.RepoObject_guid     = ro.RepoObject_guid

    Left Join
        reference.RepoObject_ReferencedList     As ro_referenced
            On
            ro_referenced.Referencing_guid = ro.RepoObject_guid

    Left Join
        reference.RepoObject_ReferencingList    As ro_referencing
            On
            ro_referencing.Referenced_guid = ro.RepoObject_guid

--Left Join
--    reference.RepoObject_ExternalReferencedList  As ext_referenced
--        On
--        ext_referenced.RepoObject_guid  = ro.RepoObject_guid

--Left Join
--    reference.RepoObject_ExternalReferencingList As ext_referencing
--        On
--        ext_referencing.RepoObject_guid = ro.RepoObject_guid
--Cross Join config.ftv_get_parameter_value ( 'AntoraComponent', '' ) As AntoraComponent
--Cross Join config.ftv_get_parameter_value ( 'AntoraModule', '' ) As AntoraModule

----
=======
// end::sql_modules_definition[]


