// tag::HeaderFullDisplayName[]
= repo_sys.ForeignKey - V
// end::HeaderFullDisplayName[]

== existing_properties

// tag::existing_properties[]

:ExistsProperty--antorareferencedlist:
:ExistsProperty--antorareferencinglist:
:ExistsProperty--is_repo_managed:
:ExistsProperty--is_ssas:
:ExistsProperty--referencedobjectlist:
:ExistsProperty--sql_modules_definition:
:ExistsProperty--FK:
:ExistsProperty--AntoraIndexList:
:ExistsProperty--Columns:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
A356741B-6373-EB11-84E3-A81E8446D5B0
// end::RepoObject_guid[]

== RepoObject_FullDisplayName2

// tag::RepoObject_FullDisplayName2[]
repo_sys.ForeignKey
// end::RepoObject_FullDisplayName2[]

== SysObject_type

// tag::SysObject_type[]
V 
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
view
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
1960394053
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2021-08-17 19:59:47
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]
[discrete]
== _


[#column-createunderlinedate]
=== create_date

[cols="d,8a,m,m,m"]
|===
|
|create_date
|datetime
|NOT NULL
|
|===


[#column-deleteunderlinereferentialunderlineaction]
=== delete_referential_action

[cols="d,8a,m,m,m"]
|===
|
|delete_referential_action
|tinyint
|NULL
|
|===

.Referencing Columns
--
* xref:repo.foreignkey_indexpattern.adoc#column-deleteunderlinereferentialunderlineaction[+repo.ForeignKey_IndexPattern.delete_referential_action+]
--


[#column-deleteunderlinereferentialunderlineactionunderlinedesc]
=== delete_referential_action_desc

[cols="d,8a,m,m,m"]
|===
|
|delete_referential_action_desc
|nvarchar(60)
|NULL
|
|===


[#column-foreignkeyunderlinefullname]
=== ForeignKey_fullname

[cols="d,8a,m,m,m"]
|===
|
|ForeignKey_fullname
|nvarchar(261)
|NULL
|
|===

.Description
--
(concat('[',[RepoObject_schema_name],'].[',[RepoObject_name],']'))
--
{empty} +

.Referenced Columns
--
* xref:repo.repoobject.adoc#column-repoobjectunderlinefullname[+repo.RepoObject.RepoObject_fullname+]
--

.Referencing Columns
--
* xref:repo_sys.foreignkeycolumn.adoc#column-foreignkeyunderlinefullname[+repo_sys.ForeignKeyColumn.ForeignKey_fullname+]
--


[#column-foreignkeyunderlineguid]
=== ForeignKey_guid

[cols="d,8a,m,m,m"]
|===
|
|ForeignKey_guid
|uniqueidentifier
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject.adoc#column-repoobjectunderlineguid[+repo.RepoObject.RepoObject_guid+]
--

.Referencing Columns
--
* xref:repo.foreignkey_indexpattern.adoc#column-foreignkeyunderlineguid[+repo.ForeignKey_IndexPattern.ForeignKey_guid+]
* xref:repo_sys.foreignkeycolumn.adoc#column-foreignkeyunderlineguid[+repo_sys.ForeignKeyColumn.ForeignKey_guid+]
--


[#column-isunderlinedisabled]
=== is_disabled

[cols="d,8a,m,m,m"]
|===
|
|is_disabled
|bit
|NOT NULL
|
|===


[#column-isunderlinemsunderlineshipped]
=== is_ms_shipped

[cols="d,8a,m,m,m"]
|===
|
|is_ms_shipped
|bit
|NOT NULL
|
|===


[#column-isunderlinenotunderlineforunderlinereplication]
=== is_not_for_replication

[cols="d,8a,m,m,m"]
|===
|
|is_not_for_replication
|bit
|NOT NULL
|
|===


[#column-isunderlinenotunderlinetrusted]
=== is_not_trusted

[cols="d,8a,m,m,m"]
|===
|
|is_not_trusted
|bit
|NOT NULL
|
|===


[#column-isunderlinepublished]
=== is_published

[cols="d,8a,m,m,m"]
|===
|
|is_published
|bit
|NOT NULL
|
|===


[#column-isunderlineschemaunderlinepublished]
=== is_schema_published

[cols="d,8a,m,m,m"]
|===
|
|is_schema_published
|bit
|NOT NULL
|
|===


[#column-isunderlinesystemunderlinenamed]
=== is_system_named

[cols="d,8a,m,m,m"]
|===
|
|is_system_named
|bit
|NOT NULL
|
|===


[#column-keyunderlineindexunderlineid]
=== key_index_id

[cols="d,8a,m,m,m"]
|===
|
|key_index_id
|int
|NULL
|
|===


[#column-modifyunderlinedate]
=== modify_date

[cols="d,8a,m,m,m"]
|===
|
|modify_date
|datetime
|NOT NULL
|
|===


[#column-name]
=== name

[cols="d,8a,m,m,m"]
|===
|
|name
|sysname
|NOT NULL
|
|===

.Referencing Columns
--
* xref:repo_sys.foreignkeycolumn.adoc#column-foreignkeyunderlinename[+repo_sys.ForeignKeyColumn.ForeignKey_name+]
--


[#column-objectunderlineid]
=== object_id

[cols="d,8a,m,m,m"]
|===
|
|object_id
|int
|NOT NULL
|
|===

.Referencing Columns
--
* xref:repo.foreignkey_indexpattern.adoc#column-constraintunderlineobjectunderlineid[+repo.ForeignKey_IndexPattern.constraint_object_id+]
--


[#column-parentunderlineobjectunderlineid]
=== parent_object_id

[cols="d,8a,m,m,m"]
|===
|
|parent_object_id
|int
|NOT NULL
|
|===


[#column-parentunderlinerepoobjectunderlinefullname]
=== parent_RepoObject_fullname

[cols="d,8a,m,m,m"]
|===
|
|parent_RepoObject_fullname
|nvarchar(261)
|NULL
|
|===

.Description
--
(concat('[',[RepoObject_schema_name],'].[',[RepoObject_name],']'))
--
{empty} +

.Referenced Columns
--
* xref:repo.repoobject.adoc#column-repoobjectunderlinefullname[+repo.RepoObject.RepoObject_fullname+]
--

.Referencing Columns
--
* xref:repo_sys.foreignkeycolumn.adoc#column-referencingunderlinerepoobjectunderlinefullname[+repo_sys.ForeignKeyColumn.referencing_RepoObject_fullname+]
--


[#column-parentunderlinerepoobjectunderlineguid]
=== parent_RepoObject_guid

[cols="d,8a,m,m,m"]
|===
|
|parent_RepoObject_guid
|uniqueidentifier
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject.adoc#column-repoobjectunderlineguid[+repo.RepoObject.RepoObject_guid+]
--


[#column-parentunderlinesysobjectunderlinefullname]
=== parent_SysObject_fullname

[cols="d,8a,m,m,m"]
|===
|
|parent_SysObject_fullname
|nvarchar(261)
|NULL
|
|===

.Description
--
(concat('[',[SysObject_schema_name],'].[',[SysObject_name],']'))
--
{empty} +

.Referenced Columns
--
* xref:repo.repoobject.adoc#column-sysobjectunderlinefullname[+repo.RepoObject.SysObject_fullname+]
--

.Referencing Columns
--
* xref:repo_sys.foreignkeycolumn.adoc#column-referencingunderlinesysobjectunderlinefullname[+repo_sys.ForeignKeyColumn.referencing_SysObject_fullname+]
--


[#column-principalunderlineid]
=== principal_id

[cols="d,8a,m,m,m"]
|===
|
|principal_id
|int
|NULL
|
|===


[#column-referencedunderlineobjectunderlineid]
=== referenced_object_id

[cols="d,8a,m,m,m"]
|===
|
|referenced_object_id
|int
|NULL
|
|===


[#column-schemaunderlineid]
=== schema_id

[cols="d,8a,m,m,m"]
|===
|
|schema_id
|int
|NOT NULL
|
|===


[#column-type]
=== type

[cols="d,8a,m,m,m"]
|===
|
|type
|char(2)
|NULL
|
|===


[#column-typeunderlinedesc]
=== type_desc

[cols="d,8a,m,m,m"]
|===
|
|type_desc
|nvarchar(60)
|NULL
|
|===


[#column-updateunderlinereferentialunderlineaction]
=== update_referential_action

[cols="d,8a,m,m,m"]
|===
|
|update_referential_action
|tinyint
|NULL
|
|===


[#column-updateunderlinereferentialunderlineactionunderlinedesc]
=== update_referential_action_desc

[cols="d,8a,m,m,m"]
|===
|
|update_referential_action_desc
|nvarchar(60)
|NULL
|
|===


// end::AntoraColumnDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]



























// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]
|
|<<column-createunderlinedate>>
|datetime
|NOT NULL
|

|
|<<column-deleteunderlinereferentialunderlineaction>>
|tinyint
|NULL
|

|
|<<column-deleteunderlinereferentialunderlineactionunderlinedesc>>
|nvarchar(60)
|NULL
|

|
|<<column-foreignkeyunderlinefullname>>
|nvarchar(261)
|NULL
|

|
|<<column-foreignkeyunderlineguid>>
|uniqueidentifier
|NULL
|

|
|<<column-isunderlinedisabled>>
|bit
|NOT NULL
|

|
|<<column-isunderlinemsunderlineshipped>>
|bit
|NOT NULL
|

|
|<<column-isunderlinenotunderlineforunderlinereplication>>
|bit
|NOT NULL
|

|
|<<column-isunderlinenotunderlinetrusted>>
|bit
|NOT NULL
|

|
|<<column-isunderlinepublished>>
|bit
|NOT NULL
|

|
|<<column-isunderlineschemaunderlinepublished>>
|bit
|NOT NULL
|

|
|<<column-isunderlinesystemunderlinenamed>>
|bit
|NOT NULL
|

|
|<<column-keyunderlineindexunderlineid>>
|int
|NULL
|

|
|<<column-modifyunderlinedate>>
|datetime
|NOT NULL
|

|
|<<column-name>>
|sysname
|NOT NULL
|

|
|<<column-objectunderlineid>>
|int
|NOT NULL
|

|
|<<column-parentunderlineobjectunderlineid>>
|int
|NOT NULL
|

|
|<<column-parentunderlinerepoobjectunderlinefullname>>
|nvarchar(261)
|NULL
|

|
|<<column-parentunderlinerepoobjectunderlineguid>>
|uniqueidentifier
|NULL
|

|
|<<column-parentunderlinesysobjectunderlinefullname>>
|nvarchar(261)
|NULL
|

|
|<<column-principalunderlineid>>
|int
|NULL
|

|
|<<column-referencedunderlineobjectunderlineid>>
|int
|NULL
|

|
|<<column-schemaunderlineid>>
|int
|NOT NULL
|

|
|<<column-type>>
|char(2)
|NULL
|

|
|<<column-typeunderlinedesc>>
|nvarchar(60)
|NULL
|

|
|<<column-updateunderlinereferentialunderlineaction>>
|tinyint
|NULL
|

|
|<<column-updateunderlinereferentialunderlineactionunderlinedesc>>
|nvarchar(60)
|NULL
|

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

[#index-idxunderlineforeignkeyunderlineunderline1]
=== idx_ForeignKey++__++1

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-ForeignKey_guid>>; uniqueidentifier
--
* PK, Unique, Real: 0, 0, 0


[#index-idxunderlineforeignkeyunderlineunderline2]
=== idx_ForeignKey++__++2

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-parent_RepoObject_guid>>; uniqueidentifier
--
* PK, Unique, Real: 0, 0, 0

// end::AntoraIndexList[]

== AntoraMeasureDetails

// tag::AntoraMeasureDetails[]

// end::AntoraMeasureDetails[]

== AntoraMeasureDescriptions



== AntoraParameterList

// tag::AntoraParameterList[]

// end::AntoraParameterList[]

== AntoraXrefCulturesList

// tag::AntoraXrefCulturesList[]
* xref:dhw:sqldb:repo_sys.foreignkey.adoc[] - 
// end::AntoraXrefCulturesList[]

== cultures_count

// tag::cultures_count[]
1
// end::cultures_count[]

== Other tags

source: property.RepoObjectProperty_cross As rop_cross


=== additional_reference_csv

// tag::additional_reference_csv[]

// end::additional_reference_csv[]


=== AdocUspSteps

// tag::adocuspsteps[]

// end::adocuspsteps[]


=== AntoraReferencedList

// tag::antorareferencedlist[]
* xref:dhw:sqldb:repo.repoobject.adoc[]
* xref:dhw:sqldb:sys_dwh.foreign_keys.adoc[]
// end::antorareferencedlist[]


=== AntoraReferencingList

// tag::antorareferencinglist[]
* xref:dhw:sqldb:repo.foreignkey_indexpattern.adoc[]
* xref:dhw:sqldb:repo_sys.foreignkeycolumn.adoc[]
// end::antorareferencinglist[]


=== Description

// tag::description[]

// end::description[]


=== exampleUsage

// tag::exampleusage[]

// end::exampleusage[]


=== exampleUsage_2

// tag::exampleusage_2[]

// end::exampleusage_2[]


=== exampleUsage_3

// tag::exampleusage_3[]

// end::exampleusage_3[]


=== exampleUsage_4

// tag::exampleusage_4[]

// end::exampleusage_4[]


=== exampleUsage_5

// tag::exampleusage_5[]

// end::exampleusage_5[]


=== exampleWrong_Usage

// tag::examplewrong_usage[]

// end::examplewrong_usage[]


=== has_execution_plan_issue

// tag::has_execution_plan_issue[]

// end::has_execution_plan_issue[]


=== has_get_referenced_issue

// tag::has_get_referenced_issue[]

// end::has_get_referenced_issue[]


=== has_history

// tag::has_history[]

// end::has_history[]


=== has_history_columns

// tag::has_history_columns[]

// end::has_history_columns[]


=== InheritanceType

// tag::inheritancetype[]

// end::inheritancetype[]


=== is_persistence

// tag::is_persistence[]

// end::is_persistence[]


=== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]

// end::is_persistence_check_duplicate_per_pk[]


=== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]

// end::is_persistence_check_for_empty_source[]


=== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]

// end::is_persistence_delete_changed[]


=== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]

// end::is_persistence_delete_missing[]


=== is_persistence_insert

// tag::is_persistence_insert[]

// end::is_persistence_insert[]


=== is_persistence_truncate

// tag::is_persistence_truncate[]

// end::is_persistence_truncate[]


=== is_persistence_update_changed

// tag::is_persistence_update_changed[]

// end::is_persistence_update_changed[]


=== is_repo_managed

// tag::is_repo_managed[]
0
// end::is_repo_managed[]


=== is_ssas

// tag::is_ssas[]
0
// end::is_ssas[]


=== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


=== MS_Description

// tag::ms_description[]

// end::ms_description[]


=== persistence_source_RepoObject_fullname

// tag::persistence_source_repoobject_fullname[]

// end::persistence_source_repoobject_fullname[]


=== persistence_source_RepoObject_fullname2

// tag::persistence_source_repoobject_fullname2[]

// end::persistence_source_repoobject_fullname2[]


=== persistence_source_RepoObject_guid

// tag::persistence_source_repoobject_guid[]

// end::persistence_source_repoobject_guid[]


=== persistence_source_RepoObject_xref

// tag::persistence_source_repoobject_xref[]

// end::persistence_source_repoobject_xref[]


=== pk_index_guid

// tag::pk_index_guid[]

// end::pk_index_guid[]


=== pk_IndexPatternColumnDatatype

// tag::pk_indexpatterncolumndatatype[]

// end::pk_indexpatterncolumndatatype[]


=== pk_IndexPatternColumnName

// tag::pk_indexpatterncolumnname[]

// end::pk_indexpatterncolumnname[]


=== pk_IndexSemanticGroup

// tag::pk_indexsemanticgroup[]

// end::pk_indexsemanticgroup[]


=== ReferencedObjectList

// tag::referencedobjectlist[]
* [repo].[RepoObject]
* [sys_dwh].[foreign_keys]
// end::referencedobjectlist[]


=== usp_persistence_RepoObject_guid

// tag::usp_persistence_repoobject_guid[]

// end::usp_persistence_repoobject_guid[]


=== UspExamples

// tag::uspexamples[]

// end::uspexamples[]


=== uspgenerator_usp_id

// tag::uspgenerator_usp_id[]

// end::uspgenerator_usp_id[]


=== UspParameters

// tag::uspparameters[]

// end::uspparameters[]

== Boolean Attributes

source: property.RepoObjectProperty WHERE property_int = 1

// tag::boolean_attributes[]


// end::boolean_attributes[]

== PlantUML diagrams

=== PlantUML Entity

// tag::puml_entity[]
[plantuml, entity-{docname}, svg, subs=macros]
....
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:repo_sys.foreignkey.adoc[]" as repo_sys.ForeignKey << V >> {
  - create_date : (datetime)
  delete_referential_action : (tinyint)
  delete_referential_action_desc : (nvarchar(60))
  ForeignKey_fullname : (nvarchar(261))
  ForeignKey_guid : (uniqueidentifier)
  - is_disabled : (bit)
  - is_ms_shipped : (bit)
  - is_not_for_replication : (bit)
  - is_not_trusted : (bit)
  - is_published : (bit)
  - is_schema_published : (bit)
  - is_system_named : (bit)
  key_index_id : (int)
  - modify_date : (datetime)
  - name : (sysname)
  - object_id : (int)
  - parent_object_id : (int)
  parent_RepoObject_fullname : (nvarchar(261))
  parent_RepoObject_guid : (uniqueidentifier)
  parent_SysObject_fullname : (nvarchar(261))
  principal_id : (int)
  referenced_object_id : (int)
  - schema_id : (int)
  type : (char(2))
  type_desc : (nvarchar(60))
  update_referential_action : (tinyint)
  update_referential_action_desc : (nvarchar(60))
  --
}
....

// end::puml_entity[]

=== PlantUML Entity 1 1 FK

// tag::puml_entity_1_1_fk[]
[plantuml, entity_1_1_fk-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:repo_sys.foreignkey.adoc[]" as repo_sys.ForeignKey << V >> {
- idx_ForeignKey__1

..
ForeignKey_guid; uniqueidentifier
--
- idx_ForeignKey__2

..
parent_RepoObject_guid; uniqueidentifier
}



footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_fk[]

=== PlantUML 1 1 ObjectRef

// tag::puml_entity_1_1_objectref[]
[plantuml, entity_1_1_objectref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:repo.foreignkey_indexpattern.adoc[]" as repo.ForeignKey_IndexPattern << V >> {
  - **constraint_object_id** : (int)
  **ForeignKey_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject.adoc[]" as repo.RepoObject << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo_sys.foreignkey.adoc[]" as repo_sys.ForeignKey << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo_sys.foreignkeycolumn.adoc[]" as repo_sys.ForeignKeyColumn << V >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.foreign_keys.adoc[]" as sys_dwh.foreign_keys << SN >> {
  --
}

repo.RepoObject <.. repo_sys.ForeignKey
repo_sys.ForeignKey <.. repo.ForeignKey_IndexPattern
repo_sys.ForeignKey <.. repo_sys.ForeignKeyColumn
sys_dwh.foreign_keys <.. repo_sys.ForeignKey

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_objectref[]

=== PlantUML 30 0 ObjectRef

// tag::puml_entity_30_0_objectref[]
[plantuml, entity_30_0_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:config.ftv_get_parameter_value.adoc[]" as config.ftv_get_parameter_value << IF >> {
  --
}

entity "puml-link:dhw:sqldb:config.parameter.adoc[]" as config.Parameter << U >> {
  - **Parameter_name** : (varchar(100))
  - **sub_Parameter** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:configt.parameter_default.adoc[]" as configT.Parameter_default << V >> {
  - **Parameter_name** : (varchar(52))
  - **sub_Parameter** : (nvarchar(26))
  --
}

entity "puml-link:dhw:sqldb:property.external_repoobjectproperty.adoc[]" as property.external_RepoObjectProperty << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.propertyname_repoobject.adoc[]" as property.PropertyName_RepoObject << V >> {
  **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.propertyname_repoobject_t.adoc[]" as property.PropertyName_RepoObject_T << U >> {
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty.adoc[]" as property.RepoObjectProperty << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty_external_src.adoc[]" as property.RepoObjectProperty_external_src << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty_external_tgt.adoc[]" as property.RepoObjectProperty_external_tgt << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty_selectedpropertyname_split.adoc[]" as property.RepoObjectProperty_SelectedPropertyName_split << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference.adoc[]" as reference.additional_Reference << U >> {
  # **tik_hash_c** : (nvarchar(32))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_from_properties_src.adoc[]" as reference.additional_Reference_from_properties_src << V >> {
  **referenced_AntoraComponent** : (nvarchar(max))
  **referenced_AntoraModule** : (nvarchar(max))
  **referenced_Schema** : (nvarchar(max))
  **referenced_Object** : (nvarchar(max))
  **referenced_Column** : (nvarchar(max))
  **referencing_AntoraComponent** : (nvarchar(max))
  **referencing_AntoraModule** : (nvarchar(max))
  **referencing_Schema** : (nvarchar(max))
  **referencing_Object** : (nvarchar(max))
  **referencing_Column** : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_from_properties_tgt.adoc[]" as reference.additional_Reference_from_properties_tgt << V >> {
  - **referenced_AntoraComponent** : (nvarchar(128))
  - **referenced_AntoraModule** : (nvarchar(128))
  - **referenced_Schema** : (nvarchar(128))
  - **referenced_Object** : (nvarchar(128))
  **referenced_Column** : (nvarchar(128))
  - **referencing_AntoraComponent** : (nvarchar(128))
  - **referencing_AntoraModule** : (nvarchar(128))
  - **referencing_Schema** : (nvarchar(128))
  - **referencing_Object** : (nvarchar(128))
  **referencing_Column** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_from_ssas_src.adoc[]" as reference.additional_Reference_from_ssas_src << V >> {
  **referenced_AntoraComponent** : (nvarchar(128))
  **referenced_AntoraModule** : (nvarchar(128))
  **referenced_Schema** : (nvarchar(max))
  **referenced_Object** : (nvarchar(max))
  **referenced_Column** : (nvarchar(500))
  **referencing_AntoraComponent** : (nvarchar(max))
  **referencing_AntoraModule** : (nvarchar(max))
  - **referencing_Schema** : (nvarchar(128))
  - **referencing_Object** : (nvarchar(128))
  **referencing_Column** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_from_ssas_tgt.adoc[]" as reference.additional_Reference_from_ssas_tgt << V >> {
  - **referenced_AntoraComponent** : (nvarchar(128))
  - **referenced_AntoraModule** : (nvarchar(128))
  - **referenced_Schema** : (nvarchar(128))
  - **referenced_Object** : (nvarchar(128))
  **referenced_Column** : (nvarchar(128))
  - **referencing_AntoraComponent** : (nvarchar(128))
  - **referencing_AntoraModule** : (nvarchar(128))
  - **referencing_Schema** : (nvarchar(128))
  - **referencing_Object** : (nvarchar(128))
  **referencing_Column** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_is_external.adoc[]" as reference.additional_Reference_is_external << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_object.adoc[]" as reference.additional_Reference_Object << V >> {
  - **AntoraComponent** : (nvarchar(128))
  - **AntoraModule** : (nvarchar(128))
  - **SchemaName** : (nvarchar(128))
  - **ObjectName** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_object_t.adoc[]" as reference.additional_Reference_Object_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_wo_columns_from_properties_src.adoc[]" as reference.additional_Reference_wo_columns_from_properties_src << V >> {
  **referenced_AntoraComponent** : (nvarchar(max))
  **referenced_AntoraModule** : (nvarchar(max))
  **referenced_Schema** : (nvarchar(max))
  **referenced_Object** : (nvarchar(max))
  **referencing_AntoraComponent** : (nvarchar(max))
  **referencing_AntoraModule** : (nvarchar(max))
  **referencing_Schema** : (nvarchar(max))
  **referencing_Object** : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_wo_columns_from_properties_tgt.adoc[]" as reference.additional_Reference_wo_columns_from_properties_tgt << V >> {
  - **referenced_AntoraComponent** : (nvarchar(128))
  - **referenced_AntoraModule** : (nvarchar(128))
  - **referenced_Schema** : (nvarchar(128))
  - **referenced_Object** : (nvarchar(128))
  - **referencing_AntoraComponent** : (nvarchar(128))
  - **referencing_AntoraModule** : (nvarchar(128))
  - **referencing_Schema** : (nvarchar(128))
  - **referencing_Object** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject.adoc[]" as repo.RepoObject << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_external_src.adoc[]" as repo.RepoObject_external_src << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_external_tgt.adoc[]" as repo.RepoObject_external_tgt << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_ssas_src.adoc[]" as repo.RepoObject_SSAS_src << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_ssas_tgt.adoc[]" as repo.RepoObject_SSAS_tgt << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.reposchema.adoc[]" as repo.RepoSchema << U >> {
  - **RepoSchema_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.reposchema_ssas_src.adoc[]" as repo.RepoSchema_ssas_src << V >> {
  - **RepoSchema_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:repo.reposchema_ssas_tgt.adoc[]" as repo.RepoSchema_ssas_tgt << V >> {
  - **RepoSchema_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo_sys.foreignkey.adoc[]" as repo_sys.ForeignKey << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.additional_reference_step1.adoc[]" as ssas.additional_Reference_step1 << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json.adoc[]" as ssas.model_json << U >> {
  - **databasename** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_10.adoc[]" as ssas.model_json_10 << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_20.adoc[]" as ssas.model_json_20 << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_201_descriptions_multiline.adoc[]" as ssas.model_json_201_descriptions_multiline << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_2011_descriptions_stragg.adoc[]" as ssas.model_json_2011_descriptions_StrAgg << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31_tables.adoc[]" as ssas.model_json_31_tables << V >> {
  - **databasename** : (nvarchar(128))
  **tables_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31_tables_t.adoc[]" as ssas.model_json_31_tables_T << U >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_311_tables_columns.adoc[]" as ssas.model_json_311_tables_columns << V >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  **tables_columns_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_311_tables_columns_t.adoc[]" as ssas.model_json_311_tables_columns_T << U >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  - **tables_columns_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_313_tables_partitions.adoc[]" as ssas.model_json_313_tables_partitions << V >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  **tables_partitions_name** : (nvarchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_3131_tables_partitions_source.adoc[]" as ssas.model_json_3131_tables_partitions_source << V >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  **tables_partitions_name** : (nvarchar(500))
  **tables_partitions_source_name** : (nvarchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31311_tables_partitions_source_posfrom.adoc[]" as ssas.model_json_31311_tables_partitions_source_PosFrom << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_313111_tables_partitions_source_stringfrom.adoc[]" as ssas.model_json_313111_tables_partitions_source_StringFrom << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_3131111_tables_partitions_source_posdot.adoc[]" as ssas.model_json_3131111_tables_partitions_source_PosDot << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31311111_tables_partitions_source_part123.adoc[]" as ssas.model_json_31311111_tables_partitions_source_Part123 << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_33_datasources.adoc[]" as ssas.model_json_33_dataSources << V >> {
  - **databasename** : (nvarchar(128))
  **dataSources_name** : (nvarchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_33_datasources_t.adoc[]" as ssas.model_json_33_dataSources_T << U >> {
  - **databasename** : (nvarchar(128))
  - **dataSources_name** : (nvarchar(500))
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.foreign_keys.adoc[]" as sys_dwh.foreign_keys << SN >> {
  --
}

config.ftv_get_parameter_value <.. reference.additional_Reference_is_external
config.ftv_get_parameter_value <.. repo.RepoObject_external_src
config.ftv_get_parameter_value <.. ssas.additional_Reference_step1
config.Parameter <.. config.ftv_get_parameter_value
config.Parameter <.. property.PropertyName_RepoObject
configT.Parameter_default <.. config.Parameter
property.external_RepoObjectProperty <.. property.RepoObjectProperty_external_src
property.PropertyName_RepoObject <.. property.PropertyName_RepoObject_T
property.PropertyName_RepoObject_T <.. property.RepoObjectProperty_external_tgt
property.RepoObjectProperty <.. property.PropertyName_RepoObject
property.RepoObjectProperty <.. property.RepoObjectProperty_SelectedPropertyName_split
property.RepoObjectProperty_external_src <.. property.RepoObjectProperty_external_tgt
property.RepoObjectProperty_external_tgt <.. property.RepoObjectProperty
property.RepoObjectProperty_SelectedPropertyName_split <.. reference.additional_Reference_from_properties_src
property.RepoObjectProperty_SelectedPropertyName_split <.. reference.additional_Reference_wo_columns_from_properties_src
reference.additional_Reference <.. reference.additional_Reference_is_external
reference.additional_Reference_from_properties_src <.. reference.additional_Reference_from_properties_tgt
reference.additional_Reference_from_properties_tgt <.. reference.additional_Reference
reference.additional_Reference_from_ssas_src <.. reference.additional_Reference_from_ssas_tgt
reference.additional_Reference_from_ssas_tgt <.. reference.additional_Reference
reference.additional_Reference_is_external <.. reference.additional_Reference_Object
reference.additional_Reference_Object <.. reference.additional_Reference_Object_T
reference.additional_Reference_Object_T <.. repo.RepoObject_external_src
reference.additional_Reference_wo_columns_from_properties_src <.. reference.additional_Reference_wo_columns_from_properties_tgt
reference.additional_Reference_wo_columns_from_properties_tgt <.. reference.additional_Reference
repo.RepoObject <.. property.RepoObjectProperty_external_tgt
repo.RepoObject <.. repo.RepoObject_external_src
repo.RepoObject <.. repo_sys.ForeignKey
repo.RepoObject_external_src <.. repo.RepoObject_external_tgt
repo.RepoObject_external_tgt <.. repo.RepoObject
repo.RepoObject_SSAS_src <.. repo.RepoObject_SSAS_tgt
repo.RepoObject_SSAS_tgt <.. repo.RepoObject
repo.RepoSchema <.. repo.RepoObject_SSAS_src
repo.RepoSchema_ssas_src <.. repo.RepoSchema_ssas_tgt
repo.RepoSchema_ssas_tgt <.. repo.RepoSchema
ssas.additional_Reference_step1 <.. reference.additional_Reference_from_ssas_src
ssas.model_json <.. ssas.model_json_10
ssas.model_json_10 <.. ssas.model_json_20
ssas.model_json_20 <.. repo.RepoSchema_ssas_src
ssas.model_json_20 <.. ssas.model_json_201_descriptions_multiline
ssas.model_json_20 <.. ssas.model_json_31_tables
ssas.model_json_20 <.. ssas.model_json_33_dataSources
ssas.model_json_201_descriptions_multiline <.. ssas.model_json_2011_descriptions_StrAgg
ssas.model_json_2011_descriptions_StrAgg <.. repo.RepoSchema_ssas_src
ssas.model_json_31_tables <.. ssas.model_json_31_tables_T
ssas.model_json_31_tables_T <.. repo.RepoObject_SSAS_src
ssas.model_json_31_tables_T <.. ssas.model_json_311_tables_columns
ssas.model_json_31_tables_T <.. ssas.model_json_313_tables_partitions
ssas.model_json_311_tables_columns <.. ssas.model_json_311_tables_columns_T
ssas.model_json_311_tables_columns_T <.. ssas.additional_Reference_step1
ssas.model_json_313_tables_partitions <.. ssas.model_json_3131_tables_partitions_source
ssas.model_json_3131_tables_partitions_source <.. ssas.model_json_31311_tables_partitions_source_PosFrom
ssas.model_json_31311_tables_partitions_source_PosFrom <.. ssas.model_json_313111_tables_partitions_source_StringFrom
ssas.model_json_313111_tables_partitions_source_StringFrom <.. ssas.model_json_3131111_tables_partitions_source_PosDot
ssas.model_json_3131111_tables_partitions_source_PosDot <.. ssas.model_json_31311111_tables_partitions_source_Part123
ssas.model_json_31311111_tables_partitions_source_Part123 <.. ssas.additional_Reference_step1
ssas.model_json_33_dataSources <.. ssas.model_json_33_dataSources_T
ssas.model_json_33_dataSources_T <.. ssas.additional_Reference_step1
sys_dwh.foreign_keys <.. repo_sys.ForeignKey

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_30_0_objectref[]

=== PlantUML 0 30 ObjectRef

// tag::puml_entity_0_30_objectref[]
[plantuml, entity_0_30_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:docs.antoranavlistpage_by_schema.adoc[]" as docs.AntoraNavListPage_by_schema << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.foreignkey_relationscript.adoc[]" as docs.ForeignKey_RelationScript << V >> {
  **referenced_RepoObject_guid** : (uniqueidentifier)
  **referencing_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:docs.ftv_repoobject_reference_plantuml_entityreflist.adoc[]" as docs.ftv_RepoObject_Reference_PlantUml_EntityRefList << IF >> {
  --
}

entity "puml-link:dhw:sqldb:docs.objectrefcyclic.adoc[]" as docs.ObjectRefCyclic << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.objectrefcyclic_entitylist.adoc[]" as docs.ObjectRefCyclic_EntityList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_adoc.adoc[]" as docs.RepoObject_Adoc << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_adoc_t.adoc[]" as docs.RepoObject_Adoc_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_indexlist.adoc[]" as docs.RepoObject_IndexList << V >> {
  **RepoObject_guid** : (uniqueidentifier)
  **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_indexlist_t.adoc[]" as docs.RepoObject_IndexList_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml.adoc[]" as docs.RepoObject_Plantuml << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_entity.adoc[]" as docs.RepoObject_Plantuml_Entity << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_entity_t.adoc[]" as docs.RepoObject_Plantuml_Entity_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_fkreflist.adoc[]" as docs.RepoObject_PlantUml_FkRefList << V >> {
  **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_pumlentityfklist.adoc[]" as docs.RepoObject_PlantUml_PumlEntityFkList << V >> {
  **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_t.adoc[]" as docs.RepoObject_Plantuml_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.schema_entitylist.adoc[]" as docs.Schema_EntityList << V >> {
  - **RepoObject_schema_name** : (nvarchar(128))
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.schema_puml.adoc[]" as docs.Schema_puml << V >> {
  - **RepoSchema_guid** : (uniqueidentifier)
  **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.schema_pumlpartial_fkreflist.adoc[]" as docs.Schema_PumlPartial_FkRefList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport.adoc[]" as docs.usp_AntoraExport << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_objectpartialscontent.adoc[]" as docs.usp_AntoraExport_ObjectPartialsContent << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_objectpuml.adoc[]" as docs.usp_AntoraExport_ObjectPuml << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_repoobject_adoc_t.adoc[]" as docs.usp_PERSIST_RepoObject_Adoc_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_repoobject_indexlist_t.adoc[]" as docs.usp_PERSIST_RepoObject_IndexList_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_repoobject_plantuml_entity_t.adoc[]" as docs.usp_PERSIST_RepoObject_Plantuml_Entity_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_repoobject_plantuml_t.adoc[]" as docs.usp_PERSIST_RepoObject_Plantuml_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.foreignkey_gross.adoc[]" as repo.ForeignKey_gross << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.foreignkey_indexes.adoc[]" as repo.ForeignKey_Indexes << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.foreignkey_indexes_union.adoc[]" as repo.ForeignKey_Indexes_union << V >> {
  **ForeignKey_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.foreignkey_indexes_union_t.adoc[]" as repo.ForeignKey_Indexes_union_T << U >> {
  **ForeignKey_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.foreignkey_indexpattern.adoc[]" as repo.ForeignKey_IndexPattern << V >> {
  - **constraint_object_id** : (int)
  **ForeignKey_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_related_fk_union.adoc[]" as repo.RepoObject_related_FK_union << V >> {
  **RepoObject_guid** : (uniqueidentifier)
  **included_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.usp_index_finish.adoc[]" as repo.usp_Index_finish << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_index_foreignkey.adoc[]" as repo.usp_Index_ForeignKey << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_index_inheritance.adoc[]" as repo.usp_index_inheritance << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_main.adoc[]" as repo.usp_main << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_persist_foreignkey_indexes_union_t.adoc[]" as repo.usp_PERSIST_ForeignKey_Indexes_union_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo_sys.foreignkey.adoc[]" as repo_sys.ForeignKey << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo_sys.foreignkeycolumn.adoc[]" as repo_sys.ForeignKeyColumn << V >> {
  --
}

docs.ftv_RepoObject_Reference_PlantUml_EntityRefList <.. docs.RepoObject_Plantuml
docs.ObjectRefCyclic_EntityList <.. docs.ObjectRefCyclic
docs.RepoObject_Adoc <.. docs.RepoObject_Adoc_T
docs.RepoObject_Adoc <.. docs.usp_PERSIST_RepoObject_Adoc_T
docs.REpoObject_Adoc_T <.. docs.usp_PERSIST_RepoObject_Adoc_T
docs.RepoObject_IndexList <.. docs.RepoObject_IndexList_T
docs.RepoObject_IndexList <.. docs.usp_PERSIST_RepoObject_IndexList_T
docs.RepoObject_IndexList_T <.. docs.RepoObject_Adoc
docs.RepoObject_IndexList_T <.. docs.RepoObject_Plantuml_Entity
docs.RepoObject_IndexList_T <.. docs.usp_PERSIST_RepoObject_IndexList_T
docs.RepoObject_Plantuml <.. docs.RepoObject_Plantuml_T
docs.RepoObject_Plantuml <.. docs.usp_PERSIST_RepoObject_Plantuml_T
docs.RepoObject_Plantuml_Entity <.. docs.RepoObject_Plantuml_Entity_T
docs.RepoObject_Plantuml_Entity <.. docs.usp_PERSIST_RepoObject_Plantuml_Entity_T
docs.RepoObject_Plantuml_Entity_T <.. docs.ftv_RepoObject_Reference_PlantUml_EntityRefList
docs.RepoObject_Plantuml_Entity_T <.. docs.ObjectRefCyclic_EntityList
docs.RepoObject_Plantuml_Entity_T <.. docs.RepoObject_Adoc
docs.RepoObject_Plantuml_Entity_T <.. docs.RepoObject_PlantUml_PumlEntityFkList
docs.RepoObject_Plantuml_Entity_T <.. docs.Schema_EntityList
docs.RepoObject_Plantuml_Entity_T <.. docs.usp_PERSIST_RepoObject_Plantuml_Entity_T
docs.RepoObject_PlantUml_FkRefList <.. docs.RepoObject_Plantuml
docs.RepoObject_PlantUml_PumlEntityFkList <.. docs.RepoObject_Plantuml
docs.RepoObject_Plantuml_T <.. docs.RepoObject_Adoc
docs.RepoObject_Plantuml_T <.. docs.usp_PERSIST_RepoObject_Plantuml_T
docs.Schema_EntityList <.. docs.Schema_puml
docs.Schema_puml <.. docs.AntoraNavListPage_by_schema
docs.Schema_PumlPartial_FkRefList <.. docs.Schema_puml
docs.usp_AntoraExport_ObjectPartialsContent <.. docs.usp_AntoraExport
docs.usp_AntoraExport_ObjectPuml <.. docs.usp_AntoraExport
docs.usp_PERSIST_RepoObject_Adoc_T <.. docs.usp_AntoraExport_ObjectPartialsContent
docs.usp_PERSIST_RepoObject_IndexList_T <.. docs.usp_AntoraExport_ObjectPartialsContent
docs.usp_PERSIST_RepoObject_Plantuml_Entity_T <.. docs.usp_AntoraExport_ObjectPuml
docs.usp_PERSIST_RepoObject_Plantuml_T <.. docs.usp_AntoraExport_ObjectPuml
repo.ForeignKey_gross <.. docs.RepoObject_IndexList
repo.ForeignKey_Indexes <.. repo.ForeignKey_Indexes_union
repo.ForeignKey_Indexes <.. repo.usp_Index_ForeignKey
repo.ForeignKey_Indexes_union <.. repo.ForeignKey_Indexes_union_T
repo.ForeignKey_Indexes_union <.. repo.usp_PERSIST_ForeignKey_Indexes_union_T
repo.ForeignKey_Indexes_union_T <.. docs.ForeignKey_RelationScript
repo.ForeignKey_Indexes_union_T <.. docs.RepoObject_PlantUml_FkRefList
repo.ForeignKey_Indexes_union_T <.. docs.Schema_PumlPartial_FkRefList
repo.ForeignKey_Indexes_union_T <.. repo.ForeignKey_gross
repo.ForeignKey_Indexes_union_T <.. repo.RepoObject_related_FK_union
repo.ForeignKey_Indexes_union_T <.. repo.usp_Index_finish
repo.ForeignKey_Indexes_union_T <.. repo.usp_PERSIST_ForeignKey_Indexes_union_T
repo.ForeignKey_IndexPattern <.. repo.ForeignKey_Indexes
repo.RepoObject_related_FK_union <.. docs.RepoObject_PlantUml_FkRefList
repo.RepoObject_related_FK_union <.. docs.RepoObject_PlantUml_PumlEntityFkList
repo.usp_Index_finish <.. repo.usp_Index_ForeignKey
repo.usp_Index_finish <.. repo.usp_index_inheritance
repo.usp_Index_ForeignKey <.. repo.usp_main
repo.usp_index_inheritance <.. repo.usp_main
repo.usp_PERSIST_ForeignKey_Indexes_union_T <.. repo.usp_Index_ForeignKey
repo_sys.ForeignKey <.. repo.ForeignKey_IndexPattern
repo_sys.ForeignKey <.. repo_sys.ForeignKeyColumn
repo_sys.ForeignKeyColumn <.. repo.ForeignKey_IndexPattern

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_0_30_objectref[]

=== PlantUML 1 1 ColumnRef

// tag::puml_entity_1_1_colref[]
[plantuml, entity_1_1_colref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:repo.foreignkey_indexpattern.adoc[]" as repo.ForeignKey_IndexPattern << V >> {
  - **constraint_object_id** : (int)
  **ForeignKey_guid** : (uniqueidentifier)
  delete_referential_action : (tinyint)
  ForeignKey_fullname : (nvarchar(261))
  ForeignKey_name : (sysname)
  referenced_IndexPatternColumnName : (nvarchar(max))
  referenced_RepoObject_guid : (uniqueidentifier)
  referencing_IndexPatternColumnName : (nvarchar(max))
  referencing_RepoObject_guid : (uniqueidentifier)
  update_referential_action : (tinyint)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject.adoc[]" as repo.RepoObject << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  external_AntoraComponent : (nvarchar(128))
  external_AntoraModule : (nvarchar(128))
  has_execution_plan_issue : (bit)
  has_get_referenced_issue : (bit)
  indent_sql_modules_definition : (tinyint)
  Inheritance_Source_fullname : (nvarchar(261))
  Inheritance_StringAggSeparatorSql : (nvarchar(4000))
  InheritanceDefinition : (nvarchar(4000))
  InheritanceType : (tinyint)
  - is_DocsExclude : (bit)
  - is_external : (bit)
  is_repo_managed : (bit)
  is_required_ObjectMerge : (bit)
  - is_ssas : (bit)
  is_SysObject_missing : (bit)
  - modify_dt : (datetime)
  pk_index_guid : (uniqueidentifier)
  pk_IndexPatternColumnName_new : (nvarchar(4000))
  Repo_history_table_guid : (uniqueidentifier)
  Repo_temporal_type : (tinyint)
  - RepoObject_name : (nvarchar(128))
  RepoObject_Referencing_Count : (int)
  - RepoObject_schema_name : (nvarchar(128))
  - RepoObject_type : (char(2))
  SysObject_id : (int)
  SysObject_modify_date : (datetime)
  - SysObject_name : (nvarchar(128))
  - SysObject_parent_object_id : (int)
  - SysObject_schema_name : (nvarchar(128))
  SysObject_type : (char(2))
  ~ has_different_sys_names : (bit)
  # is_RepoObject_name_uniqueidentifier : (int)
  # is_SysObject_name_uniqueidentifier : (int)
  ~ node_id : (bigint)
  # RepoObject_fullname : (nvarchar(261))
  # RepoObject_fullname2 : (nvarchar(257))
  # SysObject_fullname : (nvarchar(261))
  # SysObject_fullname2 : (nvarchar(257))
  ~ SysObject_query_sql : (nvarchar(406))
  ~ usp_persistence_fullname : (nvarchar(273))
  # usp_persistence_fullname2 : (nvarchar(269))
  # usp_persistence_name : (nvarchar(140))
  --
}

entity "puml-link:dhw:sqldb:repo_sys.foreignkey.adoc[]" as repo_sys.ForeignKey << V >> {
  - create_date : (datetime)
  delete_referential_action : (tinyint)
  delete_referential_action_desc : (nvarchar(60))
  ForeignKey_fullname : (nvarchar(261))
  ForeignKey_guid : (uniqueidentifier)
  - is_disabled : (bit)
  - is_ms_shipped : (bit)
  - is_not_for_replication : (bit)
  - is_not_trusted : (bit)
  - is_published : (bit)
  - is_schema_published : (bit)
  - is_system_named : (bit)
  key_index_id : (int)
  - modify_date : (datetime)
  - name : (sysname)
  - object_id : (int)
  - parent_object_id : (int)
  parent_RepoObject_fullname : (nvarchar(261))
  parent_RepoObject_guid : (uniqueidentifier)
  parent_SysObject_fullname : (nvarchar(261))
  principal_id : (int)
  referenced_object_id : (int)
  - schema_id : (int)
  type : (char(2))
  type_desc : (nvarchar(60))
  update_referential_action : (tinyint)
  update_referential_action_desc : (nvarchar(60))
  --
}

entity "puml-link:dhw:sqldb:repo_sys.foreignkeycolumn.adoc[]" as repo_sys.ForeignKeyColumn << V >> {
  - constraint_column_id : (int)
  - constraint_object_id : (int)
  ForeignKey_fullname : (nvarchar(261))
  ForeignKey_guid : (uniqueidentifier)
  ForeignKey_name : (sysname)
  - parent_column_id : (int)
  - parent_object_id : (int)
  - referenced_column_id : (int)
  referenced_column_name : (sysname)
  referenced_name : (nvarchar(128))
  - referenced_object_id : (int)
  referenced_RepoObject_guid : (uniqueidentifier)
  referenced_RepoObjectColumn_guid : (uniqueidentifier)
  referenced_schema_name : (nvarchar(128))
  referencing_column_name : (sysname)
  referencing_name : (nvarchar(128))
  referencing_RepoObject_fullname : (nvarchar(261))
  referencing_RepoObject_guid : (uniqueidentifier)
  referencing_RepoObjectColumn_guid : (uniqueidentifier)
  referencing_schema_name : (nvarchar(128))
  referencing_SysObject_fullname : (nvarchar(261))
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.foreign_keys.adoc[]" as sys_dwh.foreign_keys << SN >> {
  --
}

repo.RepoObject <.. repo_sys.ForeignKey
repo_sys.ForeignKey <.. repo.ForeignKey_IndexPattern
repo_sys.ForeignKey <.. repo_sys.ForeignKeyColumn
sys_dwh.foreign_keys <.. repo_sys.ForeignKey
"repo.RepoObject::RepoObject_fullname" <-- "repo_sys.ForeignKey::ForeignKey_fullname"
"repo.RepoObject::RepoObject_fullname" <-- "repo_sys.ForeignKey::parent_RepoObject_fullname"
"repo.RepoObject::RepoObject_guid" <-- "repo_sys.ForeignKey::ForeignKey_guid"
"repo.RepoObject::RepoObject_guid" <-- "repo_sys.ForeignKey::parent_RepoObject_guid"
"repo.RepoObject::SysObject_fullname" <-- "repo_sys.ForeignKey::parent_SysObject_fullname"
"repo_sys.ForeignKey::delete_referential_action" <-- "repo.ForeignKey_IndexPattern::delete_referential_action"
"repo_sys.ForeignKey::ForeignKey_fullname" <-- "repo_sys.ForeignKeyColumn::ForeignKey_fullname"
"repo_sys.ForeignKey::ForeignKey_guid" <-- "repo.ForeignKey_IndexPattern::ForeignKey_guid"
"repo_sys.ForeignKey::ForeignKey_guid" <-- "repo_sys.ForeignKeyColumn::ForeignKey_guid"
"repo_sys.ForeignKey::name" <-- "repo_sys.ForeignKeyColumn::ForeignKey_name"
"repo_sys.ForeignKey::object_id" <-- "repo.ForeignKey_IndexPattern::constraint_object_id"
"repo_sys.ForeignKey::parent_RepoObject_fullname" <-- "repo_sys.ForeignKeyColumn::referencing_RepoObject_fullname"
"repo_sys.ForeignKey::parent_SysObject_fullname" <-- "repo_sys.ForeignKeyColumn::referencing_SysObject_fullname"

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_colref[]


== sql_modules_definition

// tag::sql_modules_definition[]
[%collapsible]
=======
[source,sql,numbered,indent=0]
----



CREATE View repo_sys.ForeignKey
As
Select
    fk.name
  , fk.object_id
  , fk.principal_id
  , fk.schema_id
  , fk.parent_object_id
  , fk.type
  , fk.type_desc
  , fk.create_date
  , fk.modify_date
  , fk.is_ms_shipped
  , fk.is_published
  , fk.is_schema_published
  , fk.referenced_object_id
  , fk.key_index_id
  , fk.is_disabled
  , fk.is_not_for_replication
  , fk.is_not_trusted
  , fk.delete_referential_action
  , fk.delete_referential_action_desc
  , fk.update_referential_action
  , fk.update_referential_action_desc
  , fk.is_system_named
  , ForeignKey_guid            = ro.RepoObject_guid
  , ForeignKey_fullname        = ro.RepoObject_fullname
  , parent_RepoObject_guid     = parent_ro.RepoObject_guid
  , parent_RepoObject_fullname = parent_ro.RepoObject_fullname
  , parent_SysObject_fullname  = parent_ro.SysObject_fullname
From
    sys_dwh.foreign_keys As fk
    Left Join
        repo.RepoObject  As ro
            On
            ro.SysObject_id        = fk.object_id

    Left Join
        repo.RepoObject  As parent_ro
            On
            parent_ro.SysObject_id = fk.parent_object_id

----
=======
// end::sql_modules_definition[]


