// tag::HeaderFullDisplayName[]
= repo.RepoObject_persistence_ForUpdate - V
// end::HeaderFullDisplayName[]

== existing_properties

// tag::existing_properties[]

:ExistsProperty--antorareferencedlist:
:ExistsProperty--antorareferencinglist:
:ExistsProperty--is_repo_managed:
:ExistsProperty--is_ssas:
:ExistsProperty--referencedobjectlist:
:ExistsProperty--sql_modules_definition:
:ExistsProperty--FK:
:ExistsProperty--AntoraIndexList:
:ExistsProperty--Columns:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
88813D1C-6662-EB11-84DC-A81E8446D5B0
// end::RepoObject_guid[]

== RepoObject_FullDisplayName2

// tag::RepoObject_FullDisplayName2[]
repo.RepoObject_persistence_ForUpdate
// end::RepoObject_FullDisplayName2[]

== SysObject_type

// tag::SysObject_type[]
V 
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
view
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
1880393768
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2022-01-05 18:57:33
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]
[discrete]
== _


[#column-columnlistignore]
=== ColumnListIgnore

[cols="d,8a,m,m,m"]
|===
|
|ColumnListIgnore
|nvarchar(4000)
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_persistence.adoc#column-columnlistignore[+repo.RepoObject_persistence.ColumnListIgnore+]
--


[#column-columnlistnocomparebutupdate]
=== ColumnListNoCompareButUpdate

[cols="d,8a,m,m,m"]
|===
|
|ColumnListNoCompareButUpdate
|nvarchar(4000)
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_persistence.adoc#column-columnlistnocomparebutupdate[+repo.RepoObject_persistence.ColumnListNoCompareButUpdate+]
--


[#column-columnlistnocomparenoupdate]
=== ColumnListNoCompareNoUpdate

[cols="d,8a,m,m,m"]
|===
|
|ColumnListNoCompareNoUpdate
|nvarchar(4000)
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_persistence.adoc#column-columnlistnocomparenoupdate[+repo.RepoObject_persistence.ColumnListNoCompareNoUpdate+]
--


[#column-defaultunderlinesourceunderlinerepoobjectunderlinename]
=== default_source_RepoObject_name

[cols="d,8a,m,m,m"]
|===
|
|default_source_RepoObject_name
|nvarchar(128)
|NULL
|
|===

.Referencing Columns
--
* xref:repo.repoobject_persistence_sourcemismatch.adoc#column-defaultunderlinesourceunderlinerepoobjectunderlinename[+repo.RepoObject_persistence_SourceMismatch.default_source_RepoObject_name+]
--


[#column-hasunderlinehistory]
=== has_history

[cols="d,8a,m,m,m"]
|===
|
|has_history
|bit
|NOT NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_persistence.adoc#column-hasunderlinehistory[+repo.RepoObject_persistence.has_history+]
--


[#column-hasunderlinehistoryunderlinecolumns]
=== has_history_columns

[cols="d,8a,m,m,m"]
|===
|
|has_history_columns
|bit
|NOT NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_persistence.adoc#column-hasunderlinehistoryunderlinecolumns[+repo.RepoObject_persistence.has_history_columns+]
--


[#column-historyunderlineschemaunderlinename]
=== history_schema_name

[cols="d,8a,m,m,m"]
|===
|
|history_schema_name
|nvarchar(128)
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_persistence.adoc#column-historyunderlineschemaunderlinename[+repo.RepoObject_persistence.history_schema_name+]
--


[#column-historyunderlinetableunderlinename]
=== history_table_name

[cols="d,8a,m,m,m"]
|===
|
|history_table_name
|nvarchar(128)
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_persistence.adoc#column-historyunderlinetableunderlinename[+repo.RepoObject_persistence.history_table_name+]
--


[#column-isunderlinepersistenceunderlinecheckunderlineduplicateunderlineperunderlinepk]
=== is_persistence_check_duplicate_per_pk

[cols="d,8a,m,m,m"]
|===
|
|is_persistence_check_duplicate_per_pk
|bit
|NOT NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_persistence.adoc#column-isunderlinepersistenceunderlinecheckunderlineduplicateunderlineperunderlinepk[+repo.RepoObject_persistence.is_persistence_check_duplicate_per_pk+]
--


[#column-isunderlinepersistenceunderlinecheckunderlineforunderlineemptyunderlinesource]
=== is_persistence_check_for_empty_source

[cols="d,8a,m,m,m"]
|===
|
|is_persistence_check_for_empty_source
|bit
|NOT NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_persistence.adoc#column-isunderlinepersistenceunderlinecheckunderlineforunderlineemptyunderlinesource[+repo.RepoObject_persistence.is_persistence_check_for_empty_source+]
--


[#column-isunderlinepersistenceunderlinedeleteunderlinechanged]
=== is_persistence_delete_changed

[cols="d,8a,m,m,m"]
|===
|
|is_persistence_delete_changed
|bit
|NOT NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_persistence.adoc#column-isunderlinepersistenceunderlinedeleteunderlinechanged[+repo.RepoObject_persistence.is_persistence_delete_changed+]
--


[#column-isunderlinepersistenceunderlinedeleteunderlinemissing]
=== is_persistence_delete_missing

[cols="d,8a,m,m,m"]
|===
|
|is_persistence_delete_missing
|bit
|NOT NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_persistence.adoc#column-isunderlinepersistenceunderlinedeleteunderlinemissing[+repo.RepoObject_persistence.is_persistence_delete_missing+]
--


[#column-isunderlinepersistenceunderlineinsert]
=== is_persistence_insert

[cols="d,8a,m,m,m"]
|===
|
|is_persistence_insert
|bit
|NOT NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_persistence.adoc#column-isunderlinepersistenceunderlineinsert[+repo.RepoObject_persistence.is_persistence_insert+]
--


[#column-isunderlinepersistenceunderlinepersistunderlinesource]
=== is_persistence_persist_source

[cols="d,8a,m,m,m"]
|===
|
|is_persistence_persist_source
|bit
|NOT NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_persistence.adoc#column-isunderlinepersistenceunderlinepersistunderlinesource[+repo.RepoObject_persistence.is_persistence_persist_source+]
--


[#column-isunderlinepersistenceunderlinetruncate]
=== is_persistence_truncate

[cols="d,8a,m,m,m"]
|===
|
|is_persistence_truncate
|bit
|NOT NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_persistence.adoc#column-isunderlinepersistenceunderlinetruncate[+repo.RepoObject_persistence.is_persistence_truncate+]
--


[#column-isunderlinepersistenceunderlineupdateunderlinechanged]
=== is_persistence_update_changed

[cols="d,8a,m,m,m"]
|===
|
|is_persistence_update_changed
|bit
|NOT NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_persistence.adoc#column-isunderlinepersistenceunderlineupdateunderlinechanged[+repo.RepoObject_persistence.is_persistence_update_changed+]
--


[#column-postscript]
=== postscript

[cols="d,8a,m,m,m"]
|===
|
|postscript
|nvarchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_persistence.adoc#column-postscript[+repo.RepoObject_persistence.postscript+]
--


[#column-prescript]
=== prescript

[cols="d,8a,m,m,m"]
|===
|
|prescript
|nvarchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_persistence.adoc#column-prescript[+repo.RepoObject_persistence.prescript+]
--


[#column-sourceunderlinerepoobjectunderlineguid]
=== source_RepoObject_guid

[cols="d,8a,m,m,m"]
|===
|
|source_RepoObject_guid
|uniqueidentifier
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_persistence.adoc#column-sourceunderlinerepoobjectunderlineguid[+repo.RepoObject_persistence.source_RepoObject_guid+]
--

.Referencing Columns
--
* xref:repo.repoobject_persistence_sourcemismatch.adoc#column-sourceunderlinerepoobjectunderlineguid[+repo.RepoObject_persistence_SourceMismatch.source_RepoObject_guid+]
--


[#column-sourceunderlinerepoobjectunderlinename]
=== source_RepoObject_name

[cols="d,8a,m,m,m"]
|===
|
|source_RepoObject_name
|nvarchar(128)
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_persistence.adoc#column-sourceunderlinerepoobjectunderlinename[+repo.RepoObject_persistence.source_RepoObject_name+]
--

.Referencing Columns
--
* xref:repo.repoobject_persistence_sourcemismatch.adoc#column-sourceunderlinerepoobjectunderlinename[+repo.RepoObject_persistence_SourceMismatch.source_RepoObject_name+]
--


[#column-targetunderlinename]
=== target_name

[cols="d,8a,m,m,m"]
|===
|
|target_name
|nvarchar(128)
|NOT NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject.adoc#column-repoobjectunderlinename[+repo.RepoObject.RepoObject_name+]
--

.Referencing Columns
--
* xref:repo.repoobject_persistence_sourcemismatch.adoc#column-targetunderlinename[+repo.RepoObject_persistence_SourceMismatch.target_name+]
--


[#column-targetunderlinerepoobjectunderlinefullname]
=== target_RepoObject_fullname

[cols="d,8a,m,m,m"]
|===
|
|target_RepoObject_fullname
|nvarchar(261)
|NOT NULL
|
|===

.Description
--
(concat('[',[RepoObject_schema_name],'].[',[RepoObject_name],']'))
--
{empty} +

.Referenced Columns
--
* xref:repo.repoobject.adoc#column-repoobjectunderlinefullname[+repo.RepoObject.RepoObject_fullname+]
--


[#column-targetunderlinerepoobjectunderlinefullname2]
=== target_RepoObject_fullname2

[cols="d,8a,m,m,m"]
|===
|
|target_RepoObject_fullname2
|nvarchar(257)
|NOT NULL
|
|===

.Description
--
(concat([RepoObject_schema_name],'.',[RepoObject_name]))
--
{empty} +

.Referenced Columns
--
* xref:repo.repoobject.adoc#column-repoobjectunderlinefullname2[+repo.RepoObject.RepoObject_fullname2+]
--

.Referencing Columns
--
* xref:repo.repoobject_persistence_sourcemismatch.adoc#column-targetunderlinerepoobjectunderlinefullname2[+repo.RepoObject_persistence_SourceMismatch.target_RepoObject_fullname2+]
--


[#column-targetunderlinerepoobjectunderlineguid]
=== target_RepoObject_guid

[cols="d,8a,m,m,m"]
|===
|
|target_RepoObject_guid
|uniqueidentifier
|NOT NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_persistence.adoc#column-targetunderlinerepoobjectunderlineguid[+repo.RepoObject_persistence.target_RepoObject_guid+]
--

.Referencing Columns
--
* xref:repo.repoobject_persistence_sourcemismatch.adoc#column-targetunderlinerepoobjectunderlineguid[+repo.RepoObject_persistence_SourceMismatch.target_RepoObject_guid+]
--


[#column-targetunderlineschema]
=== target_schema

[cols="d,8a,m,m,m"]
|===
|
|target_schema
|nvarchar(128)
|NOT NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject.adoc#column-repoobjectunderlineschemaunderlinename[+repo.RepoObject.RepoObject_schema_name+]
--

.Referencing Columns
--
* xref:repo.repoobject_persistence_sourcemismatch.adoc#column-targetunderlineschema[+repo.RepoObject_persistence_SourceMismatch.target_schema+]
--


// end::AntoraColumnDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]

























// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]
|
|<<column-columnlistignore>>
|nvarchar(4000)
|NULL
|

|
|<<column-columnlistnocomparebutupdate>>
|nvarchar(4000)
|NULL
|

|
|<<column-columnlistnocomparenoupdate>>
|nvarchar(4000)
|NULL
|

|
|<<column-defaultunderlinesourceunderlinerepoobjectunderlinename>>
|nvarchar(128)
|NULL
|

|
|<<column-hasunderlinehistory>>
|bit
|NOT NULL
|

|
|<<column-hasunderlinehistoryunderlinecolumns>>
|bit
|NOT NULL
|

|
|<<column-historyunderlineschemaunderlinename>>
|nvarchar(128)
|NULL
|

|
|<<column-historyunderlinetableunderlinename>>
|nvarchar(128)
|NULL
|

|
|<<column-isunderlinepersistenceunderlinecheckunderlineduplicateunderlineperunderlinepk>>
|bit
|NOT NULL
|

|
|<<column-isunderlinepersistenceunderlinecheckunderlineforunderlineemptyunderlinesource>>
|bit
|NOT NULL
|

|
|<<column-isunderlinepersistenceunderlinedeleteunderlinechanged>>
|bit
|NOT NULL
|

|
|<<column-isunderlinepersistenceunderlinedeleteunderlinemissing>>
|bit
|NOT NULL
|

|
|<<column-isunderlinepersistenceunderlineinsert>>
|bit
|NOT NULL
|

|
|<<column-isunderlinepersistenceunderlinepersistunderlinesource>>
|bit
|NOT NULL
|

|
|<<column-isunderlinepersistenceunderlinetruncate>>
|bit
|NOT NULL
|

|
|<<column-isunderlinepersistenceunderlineupdateunderlinechanged>>
|bit
|NOT NULL
|

|
|<<column-postscript>>
|nvarchar(max)
|NULL
|

|
|<<column-prescript>>
|nvarchar(max)
|NULL
|

|
|<<column-sourceunderlinerepoobjectunderlineguid>>
|uniqueidentifier
|NULL
|

|
|<<column-sourceunderlinerepoobjectunderlinename>>
|nvarchar(128)
|NULL
|

|
|<<column-targetunderlinename>>
|nvarchar(128)
|NOT NULL
|

|
|<<column-targetunderlinerepoobjectunderlinefullname>>
|nvarchar(261)
|NOT NULL
|

|
|<<column-targetunderlinerepoobjectunderlinefullname2>>
|nvarchar(257)
|NOT NULL
|

|
|<<column-targetunderlinerepoobjectunderlineguid>>
|uniqueidentifier
|NOT NULL
|

|
|<<column-targetunderlineschema>>
|nvarchar(128)
|NOT NULL
|

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

[#index-idxunderlinerepoobjectunderlinepersistenceunderlineforupdateunderlineunderline1]
=== idx_RepoObject_persistence_ForUpdate++__++1

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-target_schema>>; nvarchar(128)
* <<column-target_name>>; nvarchar(128)
--
* PK, Unique, Real: 0, 0, 0


[#index-idxunderlinerepoobjectunderlinepersistenceunderlineforupdateunderlineunderline2]
=== idx_RepoObject_persistence_ForUpdate++__++2

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-target_RepoObject_guid>>; uniqueidentifier
--
* PK, Unique, Real: 0, 0, 0

// end::AntoraIndexList[]

== AntoraMeasureDetails

// tag::AntoraMeasureDetails[]

// end::AntoraMeasureDetails[]

== AntoraMeasureDescriptions



== AntoraParameterList

// tag::AntoraParameterList[]

// end::AntoraParameterList[]

== AntoraXrefCulturesList

// tag::AntoraXrefCulturesList[]
* xref:dhw:sqldb:repo.repoobject_persistence_forupdate.adoc[] - 
// end::AntoraXrefCulturesList[]

== cultures_count

// tag::cultures_count[]
1
// end::cultures_count[]

== Other tags

source: property.RepoObjectProperty_cross As rop_cross


=== additional_reference_csv

// tag::additional_reference_csv[]

// end::additional_reference_csv[]


=== AdocUspSteps

// tag::adocuspsteps[]

// end::adocuspsteps[]


=== AntoraReferencedList

// tag::antorareferencedlist[]
* xref:dhw:sqldb:repo.repoobject.adoc[]
* xref:dhw:sqldb:repo.repoobject_persistence.adoc[]
// end::antorareferencedlist[]


=== AntoraReferencingList

// tag::antorareferencinglist[]
* xref:dhw:sqldb:repo.repoobject_persistence_sourcemismatch.adoc[]
// end::antorareferencinglist[]


=== Description

// tag::description[]

// end::description[]


=== exampleUsage

// tag::exampleusage[]

// end::exampleusage[]


=== exampleUsage_2

// tag::exampleusage_2[]

// end::exampleusage_2[]


=== exampleUsage_3

// tag::exampleusage_3[]

// end::exampleusage_3[]


=== exampleUsage_4

// tag::exampleusage_4[]

// end::exampleusage_4[]


=== exampleUsage_5

// tag::exampleusage_5[]

// end::exampleusage_5[]


=== exampleWrong_Usage

// tag::examplewrong_usage[]

// end::examplewrong_usage[]


=== has_execution_plan_issue

// tag::has_execution_plan_issue[]

// end::has_execution_plan_issue[]


=== has_get_referenced_issue

// tag::has_get_referenced_issue[]

// end::has_get_referenced_issue[]


=== has_history

// tag::has_history[]

// end::has_history[]


=== has_history_columns

// tag::has_history_columns[]

// end::has_history_columns[]


=== InheritanceType

// tag::inheritancetype[]

// end::inheritancetype[]


=== is_persistence

// tag::is_persistence[]

// end::is_persistence[]


=== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]

// end::is_persistence_check_duplicate_per_pk[]


=== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]

// end::is_persistence_check_for_empty_source[]


=== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]

// end::is_persistence_delete_changed[]


=== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]

// end::is_persistence_delete_missing[]


=== is_persistence_insert

// tag::is_persistence_insert[]

// end::is_persistence_insert[]


=== is_persistence_truncate

// tag::is_persistence_truncate[]

// end::is_persistence_truncate[]


=== is_persistence_update_changed

// tag::is_persistence_update_changed[]

// end::is_persistence_update_changed[]


=== is_repo_managed

// tag::is_repo_managed[]
0
// end::is_repo_managed[]


=== is_ssas

// tag::is_ssas[]
0
// end::is_ssas[]


=== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


=== MS_Description

// tag::ms_description[]

// end::ms_description[]


=== persistence_source_RepoObject_fullname

// tag::persistence_source_repoobject_fullname[]

// end::persistence_source_repoobject_fullname[]


=== persistence_source_RepoObject_fullname2

// tag::persistence_source_repoobject_fullname2[]

// end::persistence_source_repoobject_fullname2[]


=== persistence_source_RepoObject_guid

// tag::persistence_source_repoobject_guid[]

// end::persistence_source_repoobject_guid[]


=== persistence_source_RepoObject_xref

// tag::persistence_source_repoobject_xref[]

// end::persistence_source_repoobject_xref[]


=== pk_index_guid

// tag::pk_index_guid[]

// end::pk_index_guid[]


=== pk_IndexPatternColumnDatatype

// tag::pk_indexpatterncolumndatatype[]

// end::pk_indexpatterncolumndatatype[]


=== pk_IndexPatternColumnName

// tag::pk_indexpatterncolumnname[]

// end::pk_indexpatterncolumnname[]


=== pk_IndexSemanticGroup

// tag::pk_indexsemanticgroup[]

// end::pk_indexsemanticgroup[]


=== ReferencedObjectList

// tag::referencedobjectlist[]
* [repo].[RepoObject]
* [repo].[RepoObject_persistence]
// end::referencedobjectlist[]


=== usp_persistence_RepoObject_guid

// tag::usp_persistence_repoobject_guid[]

// end::usp_persistence_repoobject_guid[]


=== UspExamples

// tag::uspexamples[]

// end::uspexamples[]


=== uspgenerator_usp_id

// tag::uspgenerator_usp_id[]

// end::uspgenerator_usp_id[]


=== UspParameters

// tag::uspparameters[]

// end::uspparameters[]

== Boolean Attributes

source: property.RepoObjectProperty WHERE property_int = 1

// tag::boolean_attributes[]


// end::boolean_attributes[]

== PlantUML diagrams

=== PlantUML Entity

// tag::puml_entity[]
[plantuml, entity-{docname}, svg, subs=macros]
....
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:repo.repoobject_persistence_forupdate.adoc[]" as repo.RepoObject_persistence_ForUpdate << V >> {
  ColumnListIgnore : (nvarchar(4000))
  ColumnListNoCompareButUpdate : (nvarchar(4000))
  ColumnListNoCompareNoUpdate : (nvarchar(4000))
  default_source_RepoObject_name : (nvarchar(128))
  - has_history : (bit)
  - has_history_columns : (bit)
  history_schema_name : (nvarchar(128))
  history_table_name : (nvarchar(128))
  - is_persistence_check_duplicate_per_pk : (bit)
  - is_persistence_check_for_empty_source : (bit)
  - is_persistence_delete_changed : (bit)
  - is_persistence_delete_missing : (bit)
  - is_persistence_insert : (bit)
  - is_persistence_persist_source : (bit)
  - is_persistence_truncate : (bit)
  - is_persistence_update_changed : (bit)
  postscript : (nvarchar(max))
  prescript : (nvarchar(max))
  source_RepoObject_guid : (uniqueidentifier)
  source_RepoObject_name : (nvarchar(128))
  - target_name : (nvarchar(128))
  - target_RepoObject_fullname : (nvarchar(261))
  - target_RepoObject_fullname2 : (nvarchar(257))
  - target_RepoObject_guid : (uniqueidentifier)
  - target_schema : (nvarchar(128))
  --
}
....

// end::puml_entity[]

=== PlantUML Entity 1 1 FK

// tag::puml_entity_1_1_fk[]
[plantuml, entity_1_1_fk-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:repo.repoobject_persistence_forupdate.adoc[]" as repo.RepoObject_persistence_ForUpdate << V >> {
- idx_RepoObject_persistence_ForUpdate__1

..
target_schema; nvarchar(128)
target_name; nvarchar(128)
--
- idx_RepoObject_persistence_ForUpdate__2

..
target_RepoObject_guid; uniqueidentifier
}



footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_fk[]

=== PlantUML 1 1 ObjectRef

// tag::puml_entity_1_1_objectref[]
[plantuml, entity_1_1_objectref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:repo.repoobject.adoc[]" as repo.RepoObject << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_persistence.adoc[]" as repo.RepoObject_persistence << U >> {
  - **target_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_persistence_forupdate.adoc[]" as repo.RepoObject_persistence_ForUpdate << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_persistence_sourcemismatch.adoc[]" as repo.RepoObject_persistence_SourceMismatch << V >> {
  --
}

repo.RepoObject <.. repo.RepoObject_persistence_ForUpdate
repo.RepoObject_persistence <.. repo.RepoObject_persistence_ForUpdate
repo.RepoObject_persistence_ForUpdate <.. repo.RepoObject_persistence_SourceMismatch

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_objectref[]

=== PlantUML 30 0 ObjectRef

// tag::puml_entity_30_0_objectref[]
[plantuml, entity_30_0_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:config.ftv_get_parameter_value.adoc[]" as config.ftv_get_parameter_value << IF >> {
  --
}

entity "puml-link:dhw:sqldb:config.parameter.adoc[]" as config.Parameter << U >> {
  - **Parameter_name** : (varchar(100))
  - **sub_Parameter** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:configt.parameter_default.adoc[]" as configT.Parameter_default << V >> {
  - **Parameter_name** : (varchar(52))
  - **sub_Parameter** : (nvarchar(26))
  --
}

entity "puml-link:dhw:sqldb:property.external_repoobjectproperty.adoc[]" as property.external_RepoObjectProperty << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.propertyname_repoobject.adoc[]" as property.PropertyName_RepoObject << V >> {
  **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.propertyname_repoobject_t.adoc[]" as property.PropertyName_RepoObject_T << U >> {
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty.adoc[]" as property.RepoObjectProperty << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty_external_src.adoc[]" as property.RepoObjectProperty_external_src << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty_external_tgt.adoc[]" as property.RepoObjectProperty_external_tgt << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty_selectedpropertyname_split.adoc[]" as property.RepoObjectProperty_SelectedPropertyName_split << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference.adoc[]" as reference.additional_Reference << U >> {
  # **tik_hash_c** : (nvarchar(32))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_from_properties_src.adoc[]" as reference.additional_Reference_from_properties_src << V >> {
  **referenced_AntoraComponent** : (nvarchar(max))
  **referenced_AntoraModule** : (nvarchar(max))
  **referenced_Schema** : (nvarchar(max))
  **referenced_Object** : (nvarchar(max))
  **referenced_Column** : (nvarchar(max))
  **referencing_AntoraComponent** : (nvarchar(max))
  **referencing_AntoraModule** : (nvarchar(max))
  **referencing_Schema** : (nvarchar(max))
  **referencing_Object** : (nvarchar(max))
  **referencing_Column** : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_from_properties_tgt.adoc[]" as reference.additional_Reference_from_properties_tgt << V >> {
  - **referenced_AntoraComponent** : (nvarchar(128))
  - **referenced_AntoraModule** : (nvarchar(128))
  - **referenced_Schema** : (nvarchar(128))
  - **referenced_Object** : (nvarchar(128))
  **referenced_Column** : (nvarchar(128))
  - **referencing_AntoraComponent** : (nvarchar(128))
  - **referencing_AntoraModule** : (nvarchar(128))
  - **referencing_Schema** : (nvarchar(128))
  - **referencing_Object** : (nvarchar(128))
  **referencing_Column** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_from_ssas_src.adoc[]" as reference.additional_Reference_from_ssas_src << V >> {
  **referenced_AntoraComponent** : (nvarchar(128))
  **referenced_AntoraModule** : (nvarchar(128))
  **referenced_Schema** : (nvarchar(max))
  **referenced_Object** : (nvarchar(max))
  **referenced_Column** : (nvarchar(500))
  **referencing_AntoraComponent** : (nvarchar(max))
  **referencing_AntoraModule** : (nvarchar(max))
  - **referencing_Schema** : (nvarchar(128))
  - **referencing_Object** : (nvarchar(128))
  **referencing_Column** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_from_ssas_tgt.adoc[]" as reference.additional_Reference_from_ssas_tgt << V >> {
  - **referenced_AntoraComponent** : (nvarchar(128))
  - **referenced_AntoraModule** : (nvarchar(128))
  - **referenced_Schema** : (nvarchar(128))
  - **referenced_Object** : (nvarchar(128))
  **referenced_Column** : (nvarchar(128))
  - **referencing_AntoraComponent** : (nvarchar(128))
  - **referencing_AntoraModule** : (nvarchar(128))
  - **referencing_Schema** : (nvarchar(128))
  - **referencing_Object** : (nvarchar(128))
  **referencing_Column** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_is_external.adoc[]" as reference.additional_Reference_is_external << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_object.adoc[]" as reference.additional_Reference_Object << V >> {
  - **AntoraComponent** : (nvarchar(128))
  - **AntoraModule** : (nvarchar(128))
  - **SchemaName** : (nvarchar(128))
  - **ObjectName** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_object_t.adoc[]" as reference.additional_Reference_Object_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_wo_columns_from_properties_src.adoc[]" as reference.additional_Reference_wo_columns_from_properties_src << V >> {
  **referenced_AntoraComponent** : (nvarchar(max))
  **referenced_AntoraModule** : (nvarchar(max))
  **referenced_Schema** : (nvarchar(max))
  **referenced_Object** : (nvarchar(max))
  **referencing_AntoraComponent** : (nvarchar(max))
  **referencing_AntoraModule** : (nvarchar(max))
  **referencing_Schema** : (nvarchar(max))
  **referencing_Object** : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_wo_columns_from_properties_tgt.adoc[]" as reference.additional_Reference_wo_columns_from_properties_tgt << V >> {
  - **referenced_AntoraComponent** : (nvarchar(128))
  - **referenced_AntoraModule** : (nvarchar(128))
  - **referenced_Schema** : (nvarchar(128))
  - **referenced_Object** : (nvarchar(128))
  - **referencing_AntoraComponent** : (nvarchar(128))
  - **referencing_AntoraModule** : (nvarchar(128))
  - **referencing_Schema** : (nvarchar(128))
  - **referencing_Object** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject.adoc[]" as repo.RepoObject << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_external_src.adoc[]" as repo.RepoObject_external_src << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_external_tgt.adoc[]" as repo.RepoObject_external_tgt << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_persistence.adoc[]" as repo.RepoObject_persistence << U >> {
  - **target_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_persistence_forupdate.adoc[]" as repo.RepoObject_persistence_ForUpdate << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_ssas_src.adoc[]" as repo.RepoObject_SSAS_src << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_ssas_tgt.adoc[]" as repo.RepoObject_SSAS_tgt << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.reposchema.adoc[]" as repo.RepoSchema << U >> {
  - **RepoSchema_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.reposchema_ssas_src.adoc[]" as repo.RepoSchema_ssas_src << V >> {
  - **RepoSchema_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:repo.reposchema_ssas_tgt.adoc[]" as repo.RepoSchema_ssas_tgt << V >> {
  - **RepoSchema_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:ssas.additional_reference_step1.adoc[]" as ssas.additional_Reference_step1 << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json.adoc[]" as ssas.model_json << U >> {
  - **databasename** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_10.adoc[]" as ssas.model_json_10 << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_20.adoc[]" as ssas.model_json_20 << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_201_descriptions_multiline.adoc[]" as ssas.model_json_201_descriptions_multiline << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_2011_descriptions_stragg.adoc[]" as ssas.model_json_2011_descriptions_StrAgg << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31_tables.adoc[]" as ssas.model_json_31_tables << V >> {
  - **databasename** : (nvarchar(128))
  **tables_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31_tables_t.adoc[]" as ssas.model_json_31_tables_T << U >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_311_tables_columns.adoc[]" as ssas.model_json_311_tables_columns << V >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  **tables_columns_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_311_tables_columns_t.adoc[]" as ssas.model_json_311_tables_columns_T << U >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  - **tables_columns_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_313_tables_partitions.adoc[]" as ssas.model_json_313_tables_partitions << V >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  **tables_partitions_name** : (nvarchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_3131_tables_partitions_source.adoc[]" as ssas.model_json_3131_tables_partitions_source << V >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  **tables_partitions_name** : (nvarchar(500))
  **tables_partitions_source_name** : (nvarchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31311_tables_partitions_source_posfrom.adoc[]" as ssas.model_json_31311_tables_partitions_source_PosFrom << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_313111_tables_partitions_source_stringfrom.adoc[]" as ssas.model_json_313111_tables_partitions_source_StringFrom << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_3131111_tables_partitions_source_posdot.adoc[]" as ssas.model_json_3131111_tables_partitions_source_PosDot << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31311111_tables_partitions_source_part123.adoc[]" as ssas.model_json_31311111_tables_partitions_source_Part123 << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_33_datasources.adoc[]" as ssas.model_json_33_dataSources << V >> {
  - **databasename** : (nvarchar(128))
  **dataSources_name** : (nvarchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_33_datasources_t.adoc[]" as ssas.model_json_33_dataSources_T << U >> {
  - **databasename** : (nvarchar(128))
  - **dataSources_name** : (nvarchar(500))
  --
}

config.ftv_get_parameter_value <.. ssas.additional_Reference_step1
config.ftv_get_parameter_value <.. reference.additional_Reference_is_external
config.ftv_get_parameter_value <.. repo.RepoObject_external_src
config.Parameter <.. config.ftv_get_parameter_value
config.Parameter <.. property.PropertyName_RepoObject
configT.Parameter_default <.. config.Parameter
property.external_RepoObjectProperty <.. property.RepoObjectProperty_external_src
property.PropertyName_RepoObject <.. property.PropertyName_RepoObject_T
property.PropertyName_RepoObject_T <.. property.RepoObjectProperty_external_tgt
property.RepoObjectProperty <.. property.RepoObjectProperty_SelectedPropertyName_split
property.RepoObjectProperty <.. property.PropertyName_RepoObject
property.RepoObjectProperty_external_src <.. property.RepoObjectProperty_external_tgt
property.RepoObjectProperty_external_tgt <.. property.RepoObjectProperty
property.RepoObjectProperty_SelectedPropertyName_split <.. reference.additional_Reference_wo_columns_from_properties_src
property.RepoObjectProperty_SelectedPropertyName_split <.. reference.additional_Reference_from_properties_src
reference.additional_Reference <.. reference.additional_Reference_is_external
reference.additional_Reference_from_properties_src <.. reference.additional_Reference_from_properties_tgt
reference.additional_Reference_from_properties_tgt <.. reference.additional_Reference
reference.additional_Reference_from_ssas_src <.. reference.additional_Reference_from_ssas_tgt
reference.additional_Reference_from_ssas_tgt <.. reference.additional_Reference
reference.additional_Reference_is_external <.. reference.additional_Reference_Object
reference.additional_Reference_Object <.. reference.additional_Reference_Object_T
reference.additional_Reference_Object_T <.. repo.RepoObject_external_src
reference.additional_Reference_wo_columns_from_properties_src <.. reference.additional_Reference_wo_columns_from_properties_tgt
reference.additional_Reference_wo_columns_from_properties_tgt <.. reference.additional_Reference
repo.RepoObject <.. property.RepoObjectProperty_external_tgt
repo.RepoObject <.. repo.RepoObject_external_src
repo.RepoObject <.. repo.RepoObject_persistence_ForUpdate
repo.RepoObject_external_src <.. repo.RepoObject_external_tgt
repo.RepoObject_external_tgt <.. repo.RepoObject
repo.RepoObject_persistence <.. repo.RepoObject_persistence_ForUpdate
repo.RepoObject_SSAS_src <.. repo.RepoObject_SSAS_tgt
repo.RepoObject_SSAS_tgt <.. repo.RepoObject
repo.RepoSchema <.. repo.RepoObject_SSAS_src
repo.RepoSchema_ssas_src <.. repo.RepoSchema_ssas_tgt
repo.RepoSchema_ssas_tgt <.. repo.RepoSchema
ssas.additional_Reference_step1 <.. reference.additional_Reference_from_ssas_src
ssas.model_json <.. ssas.model_json_10
ssas.model_json_10 <.. ssas.model_json_20
ssas.model_json_20 <.. repo.RepoSchema_ssas_src
ssas.model_json_20 <.. ssas.model_json_33_dataSources
ssas.model_json_20 <.. ssas.model_json_31_tables
ssas.model_json_20 <.. ssas.model_json_201_descriptions_multiline
ssas.model_json_201_descriptions_multiline <.. ssas.model_json_2011_descriptions_StrAgg
ssas.model_json_2011_descriptions_StrAgg <.. repo.RepoSchema_ssas_src
ssas.model_json_31_tables <.. ssas.model_json_31_tables_T
ssas.model_json_31_tables_T <.. ssas.model_json_313_tables_partitions
ssas.model_json_31_tables_T <.. ssas.model_json_311_tables_columns
ssas.model_json_31_tables_T <.. repo.RepoObject_SSAS_src
ssas.model_json_311_tables_columns <.. ssas.model_json_311_tables_columns_T
ssas.model_json_311_tables_columns_T <.. ssas.additional_Reference_step1
ssas.model_json_313_tables_partitions <.. ssas.model_json_3131_tables_partitions_source
ssas.model_json_3131_tables_partitions_source <.. ssas.model_json_31311_tables_partitions_source_PosFrom
ssas.model_json_31311_tables_partitions_source_PosFrom <.. ssas.model_json_313111_tables_partitions_source_StringFrom
ssas.model_json_313111_tables_partitions_source_StringFrom <.. ssas.model_json_3131111_tables_partitions_source_PosDot
ssas.model_json_3131111_tables_partitions_source_PosDot <.. ssas.model_json_31311111_tables_partitions_source_Part123
ssas.model_json_31311111_tables_partitions_source_Part123 <.. ssas.additional_Reference_step1
ssas.model_json_33_dataSources <.. ssas.model_json_33_dataSources_T
ssas.model_json_33_dataSources_T <.. ssas.additional_Reference_step1

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_30_0_objectref[]

=== PlantUML 0 30 ObjectRef

// tag::puml_entity_0_30_objectref[]
[plantuml, entity_0_30_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:repo.repoobject_persistence_forupdate.adoc[]" as repo.RepoObject_persistence_ForUpdate << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_persistence_sourcemismatch.adoc[]" as repo.RepoObject_persistence_SourceMismatch << V >> {
  --
}

repo.RepoObject_persistence_ForUpdate <.. repo.RepoObject_persistence_SourceMismatch

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_0_30_objectref[]

=== PlantUML 1 1 ColumnRef

// tag::puml_entity_1_1_colref[]
[plantuml, entity_1_1_colref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:repo.repoobject.adoc[]" as repo.RepoObject << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  external_AntoraComponent : (nvarchar(128))
  external_AntoraModule : (nvarchar(128))
  has_execution_plan_issue : (bit)
  has_get_referenced_issue : (bit)
  indent_sql_modules_definition : (tinyint)
  Inheritance_Source_fullname : (nvarchar(261))
  Inheritance_StringAggSeparatorSql : (nvarchar(4000))
  InheritanceDefinition : (nvarchar(4000))
  InheritanceType : (tinyint)
  - is_DocsExclude : (bit)
  - is_external : (bit)
  is_repo_managed : (bit)
  is_required_ObjectMerge : (bit)
  - is_ssas : (bit)
  is_SysObject_missing : (bit)
  - modify_dt : (datetime)
  pk_index_guid : (uniqueidentifier)
  pk_IndexPatternColumnName_new : (nvarchar(4000))
  Repo_history_table_guid : (uniqueidentifier)
  Repo_temporal_type : (tinyint)
  - RepoObject_name : (nvarchar(128))
  RepoObject_Referencing_Count : (int)
  - RepoObject_schema_name : (nvarchar(128))
  - RepoObject_type : (char(2))
  SysObject_id : (int)
  SysObject_modify_date : (datetime)
  - SysObject_name : (nvarchar(128))
  - SysObject_parent_object_id : (int)
  - SysObject_schema_name : (nvarchar(128))
  SysObject_type : (char(2))
  ~ has_different_sys_names : (bit)
  # is_RepoObject_name_uniqueidentifier : (int)
  # is_SysObject_name_uniqueidentifier : (int)
  ~ node_id : (bigint)
  # RepoObject_fullname : (nvarchar(261))
  # RepoObject_fullname2 : (nvarchar(257))
  # SysObject_fullname : (nvarchar(261))
  # SysObject_fullname2 : (nvarchar(257))
  ~ SysObject_query_sql : (nvarchar(406))
  ~ usp_persistence_fullname : (nvarchar(273))
  # usp_persistence_fullname2 : (nvarchar(269))
  # usp_persistence_name : (nvarchar(140))
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_persistence.adoc[]" as repo.RepoObject_persistence << U >> {
  - **target_RepoObject_guid** : (uniqueidentifier)
  ColumnListIgnore : (nvarchar(4000))
  ColumnListNoCompareButUpdate : (nvarchar(4000))
  ColumnListNoCompareNoUpdate : (nvarchar(4000))
  ExecutionLogId_action : (char(1))
  final_target_RepoObject_name : (nvarchar(128))
  - has_history : (bit)
  - has_history_columns : (bit)
  history_schema_name : (nvarchar(128))
  history_table_name : (nvarchar(128))
  - is_persistence_check_duplicate_per_pk : (bit)
  - is_persistence_check_for_empty_source : (bit)
  - is_persistence_delete_changed : (bit)
  - is_persistence_delete_missing : (bit)
  - is_persistence_insert : (bit)
  - is_persistence_persist_source : (bit)
  - is_persistence_truncate : (bit)
  - is_persistence_update_changed : (bit)
  postscript : (nvarchar(max))
  prescript : (nvarchar(max))
  source_RepoObject_guid : (uniqueidentifier)
  source_RepoObject_name : (nvarchar(128))
  ~ is_persistence : (bit)
  ~ temporal_type : (tinyint)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_persistence_forupdate.adoc[]" as repo.RepoObject_persistence_ForUpdate << V >> {
  ColumnListIgnore : (nvarchar(4000))
  ColumnListNoCompareButUpdate : (nvarchar(4000))
  ColumnListNoCompareNoUpdate : (nvarchar(4000))
  default_source_RepoObject_name : (nvarchar(128))
  - has_history : (bit)
  - has_history_columns : (bit)
  history_schema_name : (nvarchar(128))
  history_table_name : (nvarchar(128))
  - is_persistence_check_duplicate_per_pk : (bit)
  - is_persistence_check_for_empty_source : (bit)
  - is_persistence_delete_changed : (bit)
  - is_persistence_delete_missing : (bit)
  - is_persistence_insert : (bit)
  - is_persistence_persist_source : (bit)
  - is_persistence_truncate : (bit)
  - is_persistence_update_changed : (bit)
  postscript : (nvarchar(max))
  prescript : (nvarchar(max))
  source_RepoObject_guid : (uniqueidentifier)
  source_RepoObject_name : (nvarchar(128))
  - target_name : (nvarchar(128))
  - target_RepoObject_fullname : (nvarchar(261))
  - target_RepoObject_fullname2 : (nvarchar(257))
  - target_RepoObject_guid : (uniqueidentifier)
  - target_schema : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_persistence_sourcemismatch.adoc[]" as repo.RepoObject_persistence_SourceMismatch << V >> {
  default_source_RepoObject_name : (nvarchar(128))
  - is_guid_mismatch_via_name : (int)
  - is_mismatch : (int)
  - is_name_mismatch_via_guid : (int)
  source_RepoObject_guid : (uniqueidentifier)
  source_RepoObject_guid_via_default_name : (uniqueidentifier)
  source_RepoObject_guid_via_name : (uniqueidentifier)
  source_RepoObject_name : (nvarchar(128))
  source_RepoObject_name_via_guid : (nvarchar(128))
  - target_name : (nvarchar(128))
  - target_RepoObject_fullname2 : (nvarchar(257))
  - target_RepoObject_guid : (uniqueidentifier)
  - target_schema : (nvarchar(128))
  --
}

repo.RepoObject <.. repo.RepoObject_persistence_ForUpdate
repo.RepoObject_persistence <.. repo.RepoObject_persistence_ForUpdate
repo.RepoObject_persistence_ForUpdate <.. repo.RepoObject_persistence_SourceMismatch
"repo.RepoObject::RepoObject_fullname" <-- "repo.RepoObject_persistence_ForUpdate::target_RepoObject_fullname"
"repo.RepoObject::RepoObject_fullname2" <-- "repo.RepoObject_persistence_ForUpdate::target_RepoObject_fullname2"
"repo.RepoObject::RepoObject_name" <-- "repo.RepoObject_persistence_ForUpdate::target_name"
"repo.RepoObject::RepoObject_schema_name" <-- "repo.RepoObject_persistence_ForUpdate::target_schema"
"repo.RepoObject_persistence::ColumnListIgnore" <-- "repo.RepoObject_persistence_ForUpdate::ColumnListIgnore"
"repo.RepoObject_persistence::ColumnListNoCompareButUpdate" <-- "repo.RepoObject_persistence_ForUpdate::ColumnListNoCompareButUpdate"
"repo.RepoObject_persistence::ColumnListNoCompareNoUpdate" <-- "repo.RepoObject_persistence_ForUpdate::ColumnListNoCompareNoUpdate"
"repo.RepoObject_persistence::has_history" <-- "repo.RepoObject_persistence_ForUpdate::has_history"
"repo.RepoObject_persistence::has_history_columns" <-- "repo.RepoObject_persistence_ForUpdate::has_history_columns"
"repo.RepoObject_persistence::history_schema_name" <-- "repo.RepoObject_persistence_ForUpdate::history_schema_name"
"repo.RepoObject_persistence::history_table_name" <-- "repo.RepoObject_persistence_ForUpdate::history_table_name"
"repo.RepoObject_persistence::is_persistence_check_duplicate_per_pk" <-- "repo.RepoObject_persistence_ForUpdate::is_persistence_check_duplicate_per_pk"
"repo.RepoObject_persistence::is_persistence_check_for_empty_source" <-- "repo.RepoObject_persistence_ForUpdate::is_persistence_check_for_empty_source"
"repo.RepoObject_persistence::is_persistence_delete_changed" <-- "repo.RepoObject_persistence_ForUpdate::is_persistence_delete_changed"
"repo.RepoObject_persistence::is_persistence_delete_missing" <-- "repo.RepoObject_persistence_ForUpdate::is_persistence_delete_missing"
"repo.RepoObject_persistence::is_persistence_insert" <-- "repo.RepoObject_persistence_ForUpdate::is_persistence_insert"
"repo.RepoObject_persistence::is_persistence_persist_source" <-- "repo.RepoObject_persistence_ForUpdate::is_persistence_persist_source"
"repo.RepoObject_persistence::is_persistence_truncate" <-- "repo.RepoObject_persistence_ForUpdate::is_persistence_truncate"
"repo.RepoObject_persistence::is_persistence_update_changed" <-- "repo.RepoObject_persistence_ForUpdate::is_persistence_update_changed"
"repo.RepoObject_persistence::postscript" <-- "repo.RepoObject_persistence_ForUpdate::postscript"
"repo.RepoObject_persistence::prescript" <-- "repo.RepoObject_persistence_ForUpdate::prescript"
"repo.RepoObject_persistence::source_RepoObject_guid" <-- "repo.RepoObject_persistence_ForUpdate::source_RepoObject_guid"
"repo.RepoObject_persistence::source_RepoObject_name" <-- "repo.RepoObject_persistence_ForUpdate::source_RepoObject_name"
"repo.RepoObject_persistence::target_RepoObject_guid" <-- "repo.RepoObject_persistence_ForUpdate::target_RepoObject_guid"
"repo.RepoObject_persistence_ForUpdate::default_source_RepoObject_name" <-- "repo.RepoObject_persistence_SourceMismatch::default_source_RepoObject_name"
"repo.RepoObject_persistence_ForUpdate::source_RepoObject_guid" <-- "repo.RepoObject_persistence_SourceMismatch::source_RepoObject_guid"
"repo.RepoObject_persistence_ForUpdate::source_RepoObject_name" <-- "repo.RepoObject_persistence_SourceMismatch::source_RepoObject_name"
"repo.RepoObject_persistence_ForUpdate::target_name" <-- "repo.RepoObject_persistence_SourceMismatch::target_name"
"repo.RepoObject_persistence_ForUpdate::target_RepoObject_fullname2" <-- "repo.RepoObject_persistence_SourceMismatch::target_RepoObject_fullname2"
"repo.RepoObject_persistence_ForUpdate::target_RepoObject_guid" <-- "repo.RepoObject_persistence_SourceMismatch::target_RepoObject_guid"
"repo.RepoObject_persistence_ForUpdate::target_schema" <-- "repo.RepoObject_persistence_SourceMismatch::target_schema"

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_colref[]


== sql_modules_definition

// tag::sql_modules_definition[]
[%collapsible]
=======
[source,sql,numbered,indent=0]
----

/*
Added some lookup columns [repo].[RepoObject_persistence]
to simplify data entry in the frontend
*/
CREATE View repo.RepoObject_persistence_ForUpdate
As
Select
    ro_p.target_RepoObject_guid
  , target_RepoObject_fullname     = ro.RepoObject_fullname
  , target_RepoObject_fullname2    = ro.RepoObject_fullname2
  , target_name                    = ro.RepoObject_name
  , target_schema                  = ro.RepoObject_schema_name
  , ro_p.has_history
  , ro_p.has_history_columns
  , ro_p.history_schema_name
  , ro_p.history_table_name
  , ro_p.is_persistence_check_duplicate_per_pk
  , ro_p.is_persistence_check_for_empty_source
  , ro_p.is_persistence_delete_changed
  , ro_p.is_persistence_delete_missing
  , ro_p.is_persistence_insert
  , ro_p.is_persistence_truncate
  , ro_p.is_persistence_update_changed
  , ro_p.is_persistence_persist_source
  , ro_p.ColumnListIgnore
  , ro_p.ColumnListNoCompareButUpdate
  , ro_p.ColumnListNoCompareNoUpdate
  , ro_p.source_RepoObject_guid
  , ro_p.prescript
  , ro_p.postscript
  --, ro_p.is_persistence
  --, ro_p.temporal_type
  , ro_p.source_RepoObject_name
  , default_source_RepoObject_name = Iif(Right(ro.RepoObject_name, 2) = '_T'
                                         , Left(ro.RepoObject_name, Len ( ro.RepoObject_name ) - 2)
                                         , Null)
From
    repo.RepoObject_persistence As ro_p
    Inner Join
        repo.RepoObject         As ro
            On
            ro.RepoObject_guid = ro_p.target_RepoObject_guid

----
=======
// end::sql_modules_definition[]


