// tag::HeaderFullDisplayName[]
= repo.SysObject_RepoObject_via_guid - V
// end::HeaderFullDisplayName[]

== existing_properties

// tag::existing_properties[]

:ExistsProperty--antorareferencedlist:
:ExistsProperty--antorareferencinglist:
:ExistsProperty--is_repo_managed:
:ExistsProperty--is_ssas:
:ExistsProperty--referencedobjectlist:
:ExistsProperty--sql_modules_definition:
:ExistsProperty--FK:
:ExistsProperty--AntoraIndexList:
:ExistsProperty--Columns:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
5B90291C-9D61-EB11-84DC-A81E8446D5B0
// end::RepoObject_guid[]

== RepoObject_FullDisplayName2

// tag::RepoObject_FullDisplayName2[]
repo.SysObject_RepoObject_via_guid
// end::RepoObject_FullDisplayName2[]

== SysObject_type

// tag::SysObject_type[]
V 
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
view
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
676913483
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2021-09-21 18:26:12
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]
[discrete]
== _


[#column-historyunderlinetableunderlineguid]
=== history_table_guid

[cols="d,8a,m,m,m"]
|===
|
|history_table_guid
|uniqueidentifier
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject.adoc#column-repoobjectunderlineguid[+repo.RepoObject.RepoObject_guid+]
--


[#column-historyunderlinetableunderlineid]
=== history_table_id

[cols="d,8a,m,m,m"]
|===
|
|history_table_id
|int
|NULL
|
|===

.Referenced Columns
--
* xref:repo_sys.sysobject.adoc#column-historyunderlinetableunderlineid[+repo_sys.SysObject.history_table_id+]
--


[#column-isunderlineexternal]
=== is_external

[cols="d,8a,m,m,m"]
|===
|
|is_external
|bit
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject.adoc#column-isunderlineexternal[+repo.RepoObject.is_external+]
--


[#column-isunderlinerepounderlinemanaged]
=== is_repo_managed

[cols="d,8a,m,m,m"]
|===
|
|is_repo_managed
|bit
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject.adoc#column-isunderlinerepounderlinemanaged[+repo.RepoObject.is_repo_managed+]
--


[#column-isunderlinerepoobjectunderlinenameunderlineuniqueidentifier]
=== is_RepoObject_name_uniqueidentifier

[cols="d,8a,m,m,m"]
|===
|
|is_RepoObject_name_uniqueidentifier
|int
|NULL
|
|===

.Description
--
(case when TRY_CAST([RepoObject_name] AS [uniqueidentifier]) IS NULL then (0) else (1) end)
--
{empty} +

.Referenced Columns
--
* xref:repo.repoobject.adoc#column-isunderlinerepoobjectunderlinenameunderlineuniqueidentifier[+repo.RepoObject.is_RepoObject_name_uniqueidentifier+]
--


[#column-isunderlinessas]
=== is_ssas

[cols="d,8a,m,m,m"]
|===
|
|is_ssas
|bit
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject.adoc#column-isunderlinessas[+repo.RepoObject.is_ssas+]
--


[#column-isunderlinesysobjectunderlinenameunderlineuniqueidentifier]
=== is_SysObject_name_uniqueidentifier

[cols="d,8a,m,m,m"]
|===
|
|is_SysObject_name_uniqueidentifier
|int
|NULL
|
|===

.Description
--
(case when TRY_CAST([SysObject_name] AS [uniqueidentifier]) IS NULL then (0) else (1) end)
--
{empty} +

.Referenced Columns
--
* xref:repo.repoobject.adoc#column-isunderlinesysobjectunderlinenameunderlineuniqueidentifier[+repo.RepoObject.is_SysObject_name_uniqueidentifier+]
--


[#column-modifyunderlinedate]
=== modify_date

[cols="d,8a,m,m,m"]
|===
|
|modify_date
|datetime
|NOT NULL
|
|===

.Referenced Columns
--
* xref:repo_sys.sysobject.adoc#column-modifyunderlinedate[+repo_sys.SysObject.modify_date+]
--


[#column-parentunderlineobjectunderlineid]
=== parent_object_id

[cols="d,8a,m,m,m"]
|===
|
|parent_object_id
|int
|NOT NULL
|
|===

.Referenced Columns
--
* xref:repo_sys.sysobject.adoc#column-parentunderlineobjectunderlineid[+repo_sys.SysObject.parent_object_id+]
--


[#column-repounderlinehistoryunderlinetableunderlineguid]
=== Repo_history_table_guid

[cols="d,8a,m,m,m"]
|===
|
|Repo_history_table_guid
|uniqueidentifier
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject.adoc#column-repounderlinehistoryunderlinetableunderlineguid[+repo.RepoObject.Repo_history_table_guid+]
--


[#column-repounderlinetemporalunderlinetype]
=== Repo_temporal_type

[cols="d,8a,m,m,m"]
|===
|
|Repo_temporal_type
|tinyint
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject.adoc#column-repounderlinetemporalunderlinetype[+repo.RepoObject.Repo_temporal_type+]
--


[#column-repoobjectunderlineguid]
=== RepoObject_guid

[cols="d,8a,m,m,m"]
|===
|
|RepoObject_guid
|uniqueidentifier
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject.adoc#column-repoobjectunderlineguid[+repo.RepoObject.RepoObject_guid+]
--


[#column-repoobjectunderlineisunderlinesysobjectunderlinemissing]
=== RepoObject_is_SysObject_missing

[cols="d,8a,m,m,m"]
|===
|
|RepoObject_is_SysObject_missing
|bit
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject.adoc#column-isunderlinesysobjectunderlinemissing[+repo.RepoObject.is_SysObject_missing+]
--


[#column-repoobjectunderlinename]
=== RepoObject_name

[cols="d,8a,m,m,m"]
|===
|
|RepoObject_name
|nvarchar(128)
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject.adoc#column-repoobjectunderlinename[+repo.RepoObject.RepoObject_name+]
--


[#column-repoobjectunderlineschemaunderlinename]
=== RepoObject_schema_name

[cols="d,8a,m,m,m"]
|===
|
|RepoObject_schema_name
|nvarchar(128)
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject.adoc#column-repoobjectunderlineschemaunderlinename[+repo.RepoObject.RepoObject_schema_name+]
--


[#column-repoobjectunderlinesysobjectunderlineid]
=== RepoObject_SysObject_id

[cols="d,8a,m,m,m"]
|===
|
|RepoObject_SysObject_id
|int
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject.adoc#column-sysobjectunderlineid[+repo.RepoObject.SysObject_id+]
--


[#column-repoobjectunderlinesysobjectunderlinemodifyunderlinedate]
=== RepoObject_SysObject_modify_date

[cols="d,8a,m,m,m"]
|===
|
|RepoObject_SysObject_modify_date
|datetime
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject.adoc#column-sysobjectunderlinemodifyunderlinedate[+repo.RepoObject.SysObject_modify_date+]
--


[#column-repoobjectunderlinesysobjectunderlinename]
=== RepoObject_SysObject_name

[cols="d,8a,m,m,m"]
|===
|
|RepoObject_SysObject_name
|nvarchar(128)
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject.adoc#column-sysobjectunderlinename[+repo.RepoObject.SysObject_name+]
--


[#column-repoobjectunderlinesysobjectunderlineparentunderlineobjectunderlineid]
=== RepoObject_SysObject_parent_object_id

[cols="d,8a,m,m,m"]
|===
|
|RepoObject_SysObject_parent_object_id
|int
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject.adoc#column-sysobjectunderlineparentunderlineobjectunderlineid[+repo.RepoObject.SysObject_parent_object_id+]
--


[#column-repoobjectunderlinesysobjectunderlineschemaunderlinename]
=== RepoObject_SysObject_schema_name

[cols="d,8a,m,m,m"]
|===
|
|RepoObject_SysObject_schema_name
|nvarchar(128)
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject.adoc#column-sysobjectunderlineschemaunderlinename[+repo.RepoObject.SysObject_schema_name+]
--


[#column-repoobjectunderlinesysobjectunderlinetype]
=== RepoObject_SysObject_type

[cols="d,8a,m,m,m"]
|===
|
|RepoObject_SysObject_type
|char(2)
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject.adoc#column-sysobjectunderlinetype[+repo.RepoObject.SysObject_type+]
--


[#column-repoobjectunderlinetype]
=== RepoObject_type

[cols="d,8a,m,m,m"]
|===
|
|RepoObject_type
|char(2)
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject.adoc#column-repoobjectunderlinetype[+repo.RepoObject.RepoObject_type+]
--


[#column-sysobjectunderlineid]
=== SysObject_id

[cols="d,8a,m,m,m"]
|===
|
|SysObject_id
|int
|NOT NULL
|
|===

.Referenced Columns
--
* xref:repo_sys.sysobject.adoc#column-sysobjectunderlineid[+repo_sys.SysObject.SysObject_id+]
--


[#column-sysobjectunderlinename]
=== SysObject_name

[cols="d,8a,m,m,m"]
|===
|
|SysObject_name
|sysname
|NOT NULL
|
|===

.Referenced Columns
--
* xref:repo_sys.sysobject.adoc#column-sysobjectunderlinename[+repo_sys.SysObject.SysObject_name+]
--


[#column-sysobjectunderlinerepoobjectunderlineguid]
=== SysObject_RepoObject_guid

[cols="d,8a,m,m,m"]
|===
|
|SysObject_RepoObject_guid
|uniqueidentifier
|NULL
|
|===

.Referenced Columns
--
* xref:repo_sys.sysobject.adoc#column-sysobjectunderlinerepoobjectunderlineguid[+repo_sys.SysObject.SysObject_RepoObject_guid+]
--


[#column-sysobjectunderlineschemaunderlinename]
=== SysObject_schema_name

[cols="d,8a,m,m,m"]
|===
|
|SysObject_schema_name
|sysname
|NULL
|
|===

.Referenced Columns
--
* xref:repo_sys.sysobject.adoc#column-sysobjectunderlineschemaunderlinename[+repo_sys.SysObject.SysObject_schema_name+]
--


[#column-sysobjectunderlinetype]
=== SysObject_type

[cols="d,8a,m,m,m"]
|===
|
|SysObject_type
|char(2)
|NULL
|
|===

.Referenced Columns
--
* xref:repo_sys.sysobject.adoc#column-type[+repo_sys.SysObject.type+]
--


[#column-sysobjectunderlinetypeunderlinedesc]
=== SysObject_type_desc

[cols="d,8a,m,m,m"]
|===
|
|SysObject_type_desc
|nvarchar(60)
|NULL
|
|===

.Referenced Columns
--
* xref:repo_sys.sysobject.adoc#column-typeunderlinedesc[+repo_sys.SysObject.type_desc+]
--


[#column-temporalunderlinetype]
=== temporal_type

[cols="d,8a,m,m,m"]
|===
|
|temporal_type
|tinyint
|NULL
|
|===

.Referenced Columns
--
* xref:repo_sys.sysobject.adoc#column-temporalunderlinetype[+repo_sys.SysObject.temporal_type+]
--


// end::AntoraColumnDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]





























// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]
|
|<<column-historyunderlinetableunderlineguid>>
|uniqueidentifier
|NULL
|

|
|<<column-historyunderlinetableunderlineid>>
|int
|NULL
|

|
|<<column-isunderlineexternal>>
|bit
|NULL
|

|
|<<column-isunderlinerepounderlinemanaged>>
|bit
|NULL
|

|
|<<column-isunderlinerepoobjectunderlinenameunderlineuniqueidentifier>>
|int
|NULL
|

|
|<<column-isunderlinessas>>
|bit
|NULL
|

|
|<<column-isunderlinesysobjectunderlinenameunderlineuniqueidentifier>>
|int
|NULL
|

|
|<<column-modifyunderlinedate>>
|datetime
|NOT NULL
|

|
|<<column-parentunderlineobjectunderlineid>>
|int
|NOT NULL
|

|
|<<column-repounderlinehistoryunderlinetableunderlineguid>>
|uniqueidentifier
|NULL
|

|
|<<column-repounderlinetemporalunderlinetype>>
|tinyint
|NULL
|

|
|<<column-repoobjectunderlineguid>>
|uniqueidentifier
|NULL
|

|
|<<column-repoobjectunderlineisunderlinesysobjectunderlinemissing>>
|bit
|NULL
|

|
|<<column-repoobjectunderlinename>>
|nvarchar(128)
|NULL
|

|
|<<column-repoobjectunderlineschemaunderlinename>>
|nvarchar(128)
|NULL
|

|
|<<column-repoobjectunderlinesysobjectunderlineid>>
|int
|NULL
|

|
|<<column-repoobjectunderlinesysobjectunderlinemodifyunderlinedate>>
|datetime
|NULL
|

|
|<<column-repoobjectunderlinesysobjectunderlinename>>
|nvarchar(128)
|NULL
|

|
|<<column-repoobjectunderlinesysobjectunderlineparentunderlineobjectunderlineid>>
|int
|NULL
|

|
|<<column-repoobjectunderlinesysobjectunderlineschemaunderlinename>>
|nvarchar(128)
|NULL
|

|
|<<column-repoobjectunderlinesysobjectunderlinetype>>
|char(2)
|NULL
|

|
|<<column-repoobjectunderlinetype>>
|char(2)
|NULL
|

|
|<<column-sysobjectunderlineid>>
|int
|NOT NULL
|

|
|<<column-sysobjectunderlinename>>
|sysname
|NOT NULL
|

|
|<<column-sysobjectunderlinerepoobjectunderlineguid>>
|uniqueidentifier
|NULL
|

|
|<<column-sysobjectunderlineschemaunderlinename>>
|sysname
|NULL
|

|
|<<column-sysobjectunderlinetype>>
|char(2)
|NULL
|

|
|<<column-sysobjectunderlinetypeunderlinedesc>>
|nvarchar(60)
|NULL
|

|
|<<column-temporalunderlinetype>>
|tinyint
|NULL
|

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

[#index-idxunderlinesysobjectunderlinerepoobjectunderlineviaunderlineguidunderlineunderline1]
=== idx_SysObject_RepoObject_via_guid++__++1

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-history_table_guid>>; uniqueidentifier
--
* PK, Unique, Real: 0, 0, 0


[#index-idxunderlinesysobjectunderlinerepoobjectunderlineviaunderlineguidunderlineunderline2]
=== idx_SysObject_RepoObject_via_guid++__++2

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-RepoObject_guid>>; uniqueidentifier
--
* PK, Unique, Real: 0, 0, 0


[#index-idxunderlinesysobjectunderlinerepoobjectunderlineviaunderlineguidunderlineunderline3]
=== idx_SysObject_RepoObject_via_guid++__++3

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-RepoObject_SysObject_schema_name>>; nvarchar(128)
* <<column-RepoObject_SysObject_name>>; nvarchar(128)
--
* PK, Unique, Real: 0, 0, 0


[#index-idxunderlinesysobjectunderlinerepoobjectunderlineviaunderlineguidunderlineunderline4]
=== idx_SysObject_RepoObject_via_guid++__++4

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-RepoObject_schema_name>>; nvarchar(128)
* <<column-RepoObject_name>>; nvarchar(128)
--
* PK, Unique, Real: 0, 0, 0

// end::AntoraIndexList[]

== AntoraMeasureDetails

// tag::AntoraMeasureDetails[]

// end::AntoraMeasureDetails[]

== AntoraMeasureDescriptions



== AntoraParameterList

// tag::AntoraParameterList[]

// end::AntoraParameterList[]

== AntoraXrefCulturesList

// tag::AntoraXrefCulturesList[]
* xref:dhw:sqldb:repo.sysobject_repoobject_via_guid.adoc[] - 
// end::AntoraXrefCulturesList[]

== cultures_count

// tag::cultures_count[]
1
// end::cultures_count[]

== Other tags

source: property.RepoObjectProperty_cross As rop_cross


=== additional_reference_csv

// tag::additional_reference_csv[]

// end::additional_reference_csv[]


=== AdocUspSteps

// tag::adocuspsteps[]

// end::adocuspsteps[]


=== AntoraReferencedList

// tag::antorareferencedlist[]
* xref:dhw:sqldb:repo.repoobject.adoc[]
* xref:dhw:sqldb:repo_sys.sysobject.adoc[]
// end::antorareferencedlist[]


=== AntoraReferencingList

// tag::antorareferencinglist[]
* xref:dhw:sqldb:repo.usp_sync_guid_repoobject.adoc[]
// end::antorareferencinglist[]


=== Description

// tag::description[]

// end::description[]


=== exampleUsage

// tag::exampleusage[]

// end::exampleusage[]


=== exampleUsage_2

// tag::exampleusage_2[]

// end::exampleusage_2[]


=== exampleUsage_3

// tag::exampleusage_3[]

// end::exampleusage_3[]


=== exampleUsage_4

// tag::exampleusage_4[]

// end::exampleusage_4[]


=== exampleUsage_5

// tag::exampleusage_5[]

// end::exampleusage_5[]


=== exampleWrong_Usage

// tag::examplewrong_usage[]

// end::examplewrong_usage[]


=== has_execution_plan_issue

// tag::has_execution_plan_issue[]

// end::has_execution_plan_issue[]


=== has_get_referenced_issue

// tag::has_get_referenced_issue[]

// end::has_get_referenced_issue[]


=== has_history

// tag::has_history[]

// end::has_history[]


=== has_history_columns

// tag::has_history_columns[]

// end::has_history_columns[]


=== InheritanceType

// tag::inheritancetype[]

// end::inheritancetype[]


=== is_persistence

// tag::is_persistence[]

// end::is_persistence[]


=== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]

// end::is_persistence_check_duplicate_per_pk[]


=== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]

// end::is_persistence_check_for_empty_source[]


=== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]

// end::is_persistence_delete_changed[]


=== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]

// end::is_persistence_delete_missing[]


=== is_persistence_insert

// tag::is_persistence_insert[]

// end::is_persistence_insert[]


=== is_persistence_truncate

// tag::is_persistence_truncate[]

// end::is_persistence_truncate[]


=== is_persistence_update_changed

// tag::is_persistence_update_changed[]

// end::is_persistence_update_changed[]


=== is_repo_managed

// tag::is_repo_managed[]
0
// end::is_repo_managed[]


=== is_ssas

// tag::is_ssas[]
0
// end::is_ssas[]


=== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


=== MS_Description

// tag::ms_description[]

// end::ms_description[]


=== persistence_source_RepoObject_fullname

// tag::persistence_source_repoobject_fullname[]

// end::persistence_source_repoobject_fullname[]


=== persistence_source_RepoObject_fullname2

// tag::persistence_source_repoobject_fullname2[]

// end::persistence_source_repoobject_fullname2[]


=== persistence_source_RepoObject_guid

// tag::persistence_source_repoobject_guid[]

// end::persistence_source_repoobject_guid[]


=== persistence_source_RepoObject_xref

// tag::persistence_source_repoobject_xref[]

// end::persistence_source_repoobject_xref[]


=== pk_index_guid

// tag::pk_index_guid[]

// end::pk_index_guid[]


=== pk_IndexPatternColumnDatatype

// tag::pk_indexpatterncolumndatatype[]

// end::pk_indexpatterncolumndatatype[]


=== pk_IndexPatternColumnName

// tag::pk_indexpatterncolumnname[]

// end::pk_indexpatterncolumnname[]


=== pk_IndexSemanticGroup

// tag::pk_indexsemanticgroup[]

// end::pk_indexsemanticgroup[]


=== ReferencedObjectList

// tag::referencedobjectlist[]
* [repo].[RepoObject]
* [repo_sys].[SysObject]
// end::referencedobjectlist[]


=== usp_persistence_RepoObject_guid

// tag::usp_persistence_repoobject_guid[]

// end::usp_persistence_repoobject_guid[]


=== UspExamples

// tag::uspexamples[]

// end::uspexamples[]


=== uspgenerator_usp_id

// tag::uspgenerator_usp_id[]

// end::uspgenerator_usp_id[]


=== UspParameters

// tag::uspparameters[]

// end::uspparameters[]

== Boolean Attributes

source: property.RepoObjectProperty WHERE property_int = 1

// tag::boolean_attributes[]


// end::boolean_attributes[]

== PlantUML diagrams

=== PlantUML Entity

// tag::puml_entity[]
[plantuml, entity-{docname}, svg, subs=macros]
....
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:repo.sysobject_repoobject_via_guid.adoc[]" as repo.SysObject_RepoObject_via_guid << V >> {
  history_table_guid : (uniqueidentifier)
  history_table_id : (int)
  is_external : (bit)
  is_repo_managed : (bit)
  is_RepoObject_name_uniqueidentifier : (int)
  is_ssas : (bit)
  is_SysObject_name_uniqueidentifier : (int)
  - modify_date : (datetime)
  - parent_object_id : (int)
  Repo_history_table_guid : (uniqueidentifier)
  Repo_temporal_type : (tinyint)
  RepoObject_guid : (uniqueidentifier)
  RepoObject_is_SysObject_missing : (bit)
  RepoObject_name : (nvarchar(128))
  RepoObject_schema_name : (nvarchar(128))
  RepoObject_SysObject_id : (int)
  RepoObject_SysObject_modify_date : (datetime)
  RepoObject_SysObject_name : (nvarchar(128))
  RepoObject_SysObject_parent_object_id : (int)
  RepoObject_SysObject_schema_name : (nvarchar(128))
  RepoObject_SysObject_type : (char(2))
  RepoObject_type : (char(2))
  - SysObject_id : (int)
  - SysObject_name : (sysname)
  SysObject_RepoObject_guid : (uniqueidentifier)
  SysObject_schema_name : (sysname)
  SysObject_type : (char(2))
  SysObject_type_desc : (nvarchar(60))
  temporal_type : (tinyint)
  --
}
....

// end::puml_entity[]

=== PlantUML Entity 1 1 FK

// tag::puml_entity_1_1_fk[]
[plantuml, entity_1_1_fk-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:repo.sysobject_repoobject_via_guid.adoc[]" as repo.SysObject_RepoObject_via_guid << V >> {
- idx_SysObject_RepoObject_via_guid__1

..
history_table_guid; uniqueidentifier
--
- idx_SysObject_RepoObject_via_guid__2

..
RepoObject_guid; uniqueidentifier
--
- idx_SysObject_RepoObject_via_guid__3

..
RepoObject_SysObject_schema_name; nvarchar(128)
RepoObject_SysObject_name; nvarchar(128)
--
- idx_SysObject_RepoObject_via_guid__4

..
RepoObject_schema_name; nvarchar(128)
RepoObject_name; nvarchar(128)
}



footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_fk[]

=== PlantUML 1 1 ObjectRef

// tag::puml_entity_1_1_objectref[]
[plantuml, entity_1_1_objectref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:repo.repoobject.adoc[]" as repo.RepoObject << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.sysobject_repoobject_via_guid.adoc[]" as repo.SysObject_RepoObject_via_guid << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_sync_guid_repoobject.adoc[]" as repo.usp_sync_guid_RepoObject << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo_sys.sysobject.adoc[]" as repo_sys.SysObject << V >> {
  --
}

repo.RepoObject <.. repo.SysObject_RepoObject_via_guid
repo.SysObject_RepoObject_via_guid <.. repo.usp_sync_guid_RepoObject
repo_sys.SysObject <.. repo.SysObject_RepoObject_via_guid

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_objectref[]

=== PlantUML 30 0 ObjectRef

// tag::puml_entity_30_0_objectref[]
[plantuml, entity_30_0_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:config.ftv_dwh_database.adoc[]" as config.ftv_dwh_database << IF >> {
  --
}

entity "puml-link:dhw:sqldb:config.ftv_get_parameter_value.adoc[]" as config.ftv_get_parameter_value << IF >> {
  --
}

entity "puml-link:dhw:sqldb:config.parameter.adoc[]" as config.Parameter << U >> {
  - **Parameter_name** : (varchar(100))
  - **sub_Parameter** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:configt.parameter_default.adoc[]" as configT.Parameter_default << V >> {
  - **Parameter_name** : (varchar(52))
  - **sub_Parameter** : (nvarchar(26))
  --
}

entity "puml-link:dhw:sqldb:property.external_repoobjectproperty.adoc[]" as property.external_RepoObjectProperty << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.propertyname_repoobject.adoc[]" as property.PropertyName_RepoObject << V >> {
  **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.propertyname_repoobject_t.adoc[]" as property.PropertyName_RepoObject_T << U >> {
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty.adoc[]" as property.RepoObjectProperty << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty_external_src.adoc[]" as property.RepoObjectProperty_external_src << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty_external_tgt.adoc[]" as property.RepoObjectProperty_external_tgt << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty_selectedpropertyname_split.adoc[]" as property.RepoObjectProperty_SelectedPropertyName_split << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference.adoc[]" as reference.additional_Reference << U >> {
  # **tik_hash_c** : (nvarchar(32))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_from_properties_src.adoc[]" as reference.additional_Reference_from_properties_src << V >> {
  **referenced_AntoraComponent** : (nvarchar(max))
  **referenced_AntoraModule** : (nvarchar(max))
  **referenced_Schema** : (nvarchar(max))
  **referenced_Object** : (nvarchar(max))
  **referenced_Column** : (nvarchar(max))
  **referencing_AntoraComponent** : (nvarchar(max))
  **referencing_AntoraModule** : (nvarchar(max))
  **referencing_Schema** : (nvarchar(max))
  **referencing_Object** : (nvarchar(max))
  **referencing_Column** : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_from_properties_tgt.adoc[]" as reference.additional_Reference_from_properties_tgt << V >> {
  - **referenced_AntoraComponent** : (nvarchar(128))
  - **referenced_AntoraModule** : (nvarchar(128))
  - **referenced_Schema** : (nvarchar(128))
  - **referenced_Object** : (nvarchar(128))
  **referenced_Column** : (nvarchar(128))
  - **referencing_AntoraComponent** : (nvarchar(128))
  - **referencing_AntoraModule** : (nvarchar(128))
  - **referencing_Schema** : (nvarchar(128))
  - **referencing_Object** : (nvarchar(128))
  **referencing_Column** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_from_ssas_src.adoc[]" as reference.additional_Reference_from_ssas_src << V >> {
  **referenced_AntoraComponent** : (nvarchar(128))
  **referenced_AntoraModule** : (nvarchar(128))
  **referenced_Schema** : (nvarchar(max))
  **referenced_Object** : (nvarchar(max))
  **referenced_Column** : (nvarchar(500))
  **referencing_AntoraComponent** : (nvarchar(max))
  **referencing_AntoraModule** : (nvarchar(max))
  - **referencing_Schema** : (nvarchar(128))
  - **referencing_Object** : (nvarchar(128))
  **referencing_Column** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_from_ssas_tgt.adoc[]" as reference.additional_Reference_from_ssas_tgt << V >> {
  - **referenced_AntoraComponent** : (nvarchar(128))
  - **referenced_AntoraModule** : (nvarchar(128))
  - **referenced_Schema** : (nvarchar(128))
  - **referenced_Object** : (nvarchar(128))
  **referenced_Column** : (nvarchar(128))
  - **referencing_AntoraComponent** : (nvarchar(128))
  - **referencing_AntoraModule** : (nvarchar(128))
  - **referencing_Schema** : (nvarchar(128))
  - **referencing_Object** : (nvarchar(128))
  **referencing_Column** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_is_external.adoc[]" as reference.additional_Reference_is_external << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_object.adoc[]" as reference.additional_Reference_Object << V >> {
  - **AntoraComponent** : (nvarchar(128))
  - **AntoraModule** : (nvarchar(128))
  - **SchemaName** : (nvarchar(128))
  - **ObjectName** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_object_t.adoc[]" as reference.additional_Reference_Object_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_wo_columns_from_properties_src.adoc[]" as reference.additional_Reference_wo_columns_from_properties_src << V >> {
  **referenced_AntoraComponent** : (nvarchar(max))
  **referenced_AntoraModule** : (nvarchar(max))
  **referenced_Schema** : (nvarchar(max))
  **referenced_Object** : (nvarchar(max))
  **referencing_AntoraComponent** : (nvarchar(max))
  **referencing_AntoraModule** : (nvarchar(max))
  **referencing_Schema** : (nvarchar(max))
  **referencing_Object** : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_wo_columns_from_properties_tgt.adoc[]" as reference.additional_Reference_wo_columns_from_properties_tgt << V >> {
  - **referenced_AntoraComponent** : (nvarchar(128))
  - **referenced_AntoraModule** : (nvarchar(128))
  - **referenced_Schema** : (nvarchar(128))
  - **referenced_Object** : (nvarchar(128))
  - **referencing_AntoraComponent** : (nvarchar(128))
  - **referencing_AntoraModule** : (nvarchar(128))
  - **referencing_Schema** : (nvarchar(128))
  - **referencing_Object** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject.adoc[]" as repo.RepoObject << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_external_src.adoc[]" as repo.RepoObject_external_src << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_external_tgt.adoc[]" as repo.RepoObject_external_tgt << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_ssas_src.adoc[]" as repo.RepoObject_SSAS_src << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_ssas_tgt.adoc[]" as repo.RepoObject_SSAS_tgt << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.reposchema.adoc[]" as repo.RepoSchema << U >> {
  - **RepoSchema_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.reposchema_ssas_src.adoc[]" as repo.RepoSchema_ssas_src << V >> {
  - **RepoSchema_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:repo.reposchema_ssas_tgt.adoc[]" as repo.RepoSchema_ssas_tgt << V >> {
  - **RepoSchema_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.sysobject_repoobject_via_guid.adoc[]" as repo.SysObject_RepoObject_via_guid << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo_sys.extendedproperties.adoc[]" as repo_sys.ExtendedProperties << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo_sys.sysobject.adoc[]" as repo_sys.SysObject << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.additional_reference_step1.adoc[]" as ssas.additional_Reference_step1 << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json.adoc[]" as ssas.model_json << U >> {
  - **databasename** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_10.adoc[]" as ssas.model_json_10 << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_20.adoc[]" as ssas.model_json_20 << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_201_descriptions_multiline.adoc[]" as ssas.model_json_201_descriptions_multiline << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_2011_descriptions_stragg.adoc[]" as ssas.model_json_2011_descriptions_StrAgg << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31_tables.adoc[]" as ssas.model_json_31_tables << V >> {
  - **databasename** : (nvarchar(128))
  **tables_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31_tables_t.adoc[]" as ssas.model_json_31_tables_T << U >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_311_tables_columns.adoc[]" as ssas.model_json_311_tables_columns << V >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  **tables_columns_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_311_tables_columns_t.adoc[]" as ssas.model_json_311_tables_columns_T << U >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  - **tables_columns_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_313_tables_partitions.adoc[]" as ssas.model_json_313_tables_partitions << V >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  **tables_partitions_name** : (nvarchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_3131_tables_partitions_source.adoc[]" as ssas.model_json_3131_tables_partitions_source << V >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  **tables_partitions_name** : (nvarchar(500))
  **tables_partitions_source_name** : (nvarchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31311_tables_partitions_source_posfrom.adoc[]" as ssas.model_json_31311_tables_partitions_source_PosFrom << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_313111_tables_partitions_source_stringfrom.adoc[]" as ssas.model_json_313111_tables_partitions_source_StringFrom << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_3131111_tables_partitions_source_posdot.adoc[]" as ssas.model_json_3131111_tables_partitions_source_PosDot << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31311111_tables_partitions_source_part123.adoc[]" as ssas.model_json_31311111_tables_partitions_source_Part123 << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_33_datasources.adoc[]" as ssas.model_json_33_dataSources << V >> {
  - **databasename** : (nvarchar(128))
  **dataSources_name** : (nvarchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_33_datasources_t.adoc[]" as ssas.model_json_33_dataSources_T << U >> {
  - **databasename** : (nvarchar(128))
  - **dataSources_name** : (nvarchar(500))
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.columns.adoc[]" as sys_dwh.columns << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.extended_properties.adoc[]" as sys_dwh.extended_properties << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.indexes.adoc[]" as sys_dwh.indexes << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.objects.adoc[]" as sys_dwh.objects << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.parameters.adoc[]" as sys_dwh.parameters << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.schemas.adoc[]" as sys_dwh.schemas << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.sql_modules.adoc[]" as sys_dwh.sql_modules << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.tables.adoc[]" as sys_dwh.tables << SN >> {
  --
}

config.ftv_dwh_database <.. repo_sys.ExtendedProperties
config.ftv_get_parameter_value <.. reference.additional_Reference_is_external
config.ftv_get_parameter_value <.. repo.RepoObject_external_src
config.ftv_get_parameter_value <.. ssas.additional_Reference_step1
config.Parameter <.. config.ftv_dwh_database
config.Parameter <.. config.ftv_get_parameter_value
config.Parameter <.. property.PropertyName_RepoObject
configT.Parameter_default <.. config.Parameter
property.external_RepoObjectProperty <.. property.RepoObjectProperty_external_src
property.PropertyName_RepoObject <.. property.PropertyName_RepoObject_T
property.PropertyName_RepoObject_T <.. property.RepoObjectProperty_external_tgt
property.RepoObjectProperty <.. property.PropertyName_RepoObject
property.RepoObjectProperty <.. property.RepoObjectProperty_SelectedPropertyName_split
property.RepoObjectProperty_external_src <.. property.RepoObjectProperty_external_tgt
property.RepoObjectProperty_external_tgt <.. property.RepoObjectProperty
property.RepoObjectProperty_SelectedPropertyName_split <.. reference.additional_Reference_from_properties_src
property.RepoObjectProperty_SelectedPropertyName_split <.. reference.additional_Reference_wo_columns_from_properties_src
reference.additional_Reference <.. reference.additional_Reference_is_external
reference.additional_Reference_from_properties_src <.. reference.additional_Reference_from_properties_tgt
reference.additional_Reference_from_properties_tgt <.. reference.additional_Reference
reference.additional_Reference_from_ssas_src <.. reference.additional_Reference_from_ssas_tgt
reference.additional_Reference_from_ssas_tgt <.. reference.additional_Reference
reference.additional_Reference_is_external <.. reference.additional_Reference_Object
reference.additional_Reference_Object <.. reference.additional_Reference_Object_T
reference.additional_Reference_Object_T <.. repo.RepoObject_external_src
reference.additional_Reference_wo_columns_from_properties_src <.. reference.additional_Reference_wo_columns_from_properties_tgt
reference.additional_Reference_wo_columns_from_properties_tgt <.. reference.additional_Reference
repo.RepoObject <.. property.RepoObjectProperty_external_tgt
repo.RepoObject <.. repo.RepoObject_external_src
repo.RepoObject <.. repo.SysObject_RepoObject_via_guid
repo.RepoObject_external_src <.. repo.RepoObject_external_tgt
repo.RepoObject_external_tgt <.. repo.RepoObject
repo.RepoObject_SSAS_src <.. repo.RepoObject_SSAS_tgt
repo.RepoObject_SSAS_tgt <.. repo.RepoObject
repo.RepoSchema <.. repo.RepoObject_SSAS_src
repo.RepoSchema_ssas_src <.. repo.RepoSchema_ssas_tgt
repo.RepoSchema_ssas_tgt <.. repo.RepoSchema
repo_sys.ExtendedProperties <.. repo_sys.SysObject
repo_sys.SysObject <.. repo.SysObject_RepoObject_via_guid
ssas.additional_Reference_step1 <.. reference.additional_Reference_from_ssas_src
ssas.model_json <.. ssas.model_json_10
ssas.model_json_10 <.. ssas.model_json_20
ssas.model_json_20 <.. repo.RepoSchema_ssas_src
ssas.model_json_20 <.. ssas.model_json_201_descriptions_multiline
ssas.model_json_20 <.. ssas.model_json_31_tables
ssas.model_json_20 <.. ssas.model_json_33_dataSources
ssas.model_json_201_descriptions_multiline <.. ssas.model_json_2011_descriptions_StrAgg
ssas.model_json_2011_descriptions_StrAgg <.. repo.RepoSchema_ssas_src
ssas.model_json_31_tables <.. ssas.model_json_31_tables_T
ssas.model_json_31_tables_T <.. repo.RepoObject_SSAS_src
ssas.model_json_31_tables_T <.. ssas.model_json_311_tables_columns
ssas.model_json_31_tables_T <.. ssas.model_json_313_tables_partitions
ssas.model_json_311_tables_columns <.. ssas.model_json_311_tables_columns_T
ssas.model_json_311_tables_columns_T <.. ssas.additional_Reference_step1
ssas.model_json_313_tables_partitions <.. ssas.model_json_3131_tables_partitions_source
ssas.model_json_3131_tables_partitions_source <.. ssas.model_json_31311_tables_partitions_source_PosFrom
ssas.model_json_31311_tables_partitions_source_PosFrom <.. ssas.model_json_313111_tables_partitions_source_StringFrom
ssas.model_json_313111_tables_partitions_source_StringFrom <.. ssas.model_json_3131111_tables_partitions_source_PosDot
ssas.model_json_3131111_tables_partitions_source_PosDot <.. ssas.model_json_31311111_tables_partitions_source_Part123
ssas.model_json_31311111_tables_partitions_source_Part123 <.. ssas.additional_Reference_step1
ssas.model_json_33_dataSources <.. ssas.model_json_33_dataSources_T
ssas.model_json_33_dataSources_T <.. ssas.additional_Reference_step1
sys_dwh.columns <.. repo_sys.ExtendedProperties
sys_dwh.extended_properties <.. repo_sys.ExtendedProperties
sys_dwh.indexes <.. repo_sys.ExtendedProperties
sys_dwh.objects <.. repo_sys.ExtendedProperties
sys_dwh.objects <.. repo_sys.SysObject
sys_dwh.parameters <.. repo_sys.ExtendedProperties
sys_dwh.schemas <.. repo_sys.ExtendedProperties
sys_dwh.schemas <.. repo_sys.SysObject
sys_dwh.sql_modules <.. repo_sys.SysObject
sys_dwh.tables <.. repo_sys.SysObject

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_30_0_objectref[]

=== PlantUML 0 30 ObjectRef

// tag::puml_entity_0_30_objectref[]
[plantuml, entity_0_30_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:repo.sysobject_repoobject_via_guid.adoc[]" as repo.SysObject_RepoObject_via_guid << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_main.adoc[]" as repo.usp_main << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_persistence_set.adoc[]" as repo.usp_persistence_set << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_sync_guid.adoc[]" as repo.usp_sync_guid << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_sync_guid_repoobject.adoc[]" as repo.usp_sync_guid_RepoObject << P >> {
  --
}

repo.SysObject_RepoObject_via_guid <.. repo.usp_sync_guid_RepoObject
repo.usp_sync_guid <.. repo.usp_main
repo.usp_sync_guid <.. repo.usp_persistence_set
repo.usp_sync_guid_RepoObject <.. repo.usp_sync_guid

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_0_30_objectref[]

=== PlantUML 1 1 ColumnRef

// tag::puml_entity_1_1_colref[]
[plantuml, entity_1_1_colref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:repo.repoobject.adoc[]" as repo.RepoObject << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  external_AntoraComponent : (nvarchar(128))
  external_AntoraModule : (nvarchar(128))
  has_execution_plan_issue : (bit)
  has_get_referenced_issue : (bit)
  indent_sql_modules_definition : (tinyint)
  Inheritance_Source_fullname : (nvarchar(261))
  Inheritance_StringAggSeparatorSql : (nvarchar(4000))
  InheritanceDefinition : (nvarchar(4000))
  InheritanceType : (tinyint)
  - is_DocsExclude : (bit)
  - is_external : (bit)
  is_repo_managed : (bit)
  is_required_ObjectMerge : (bit)
  - is_ssas : (bit)
  is_SysObject_missing : (bit)
  - modify_dt : (datetime)
  pk_index_guid : (uniqueidentifier)
  pk_IndexPatternColumnName_new : (nvarchar(4000))
  Repo_history_table_guid : (uniqueidentifier)
  Repo_temporal_type : (tinyint)
  - RepoObject_name : (nvarchar(128))
  RepoObject_Referencing_Count : (int)
  - RepoObject_schema_name : (nvarchar(128))
  - RepoObject_type : (char(2))
  SysObject_id : (int)
  SysObject_modify_date : (datetime)
  - SysObject_name : (nvarchar(128))
  - SysObject_parent_object_id : (int)
  - SysObject_schema_name : (nvarchar(128))
  SysObject_type : (char(2))
  ~ has_different_sys_names : (bit)
  # is_RepoObject_name_uniqueidentifier : (int)
  # is_SysObject_name_uniqueidentifier : (int)
  ~ node_id : (bigint)
  # RepoObject_fullname : (nvarchar(261))
  # RepoObject_fullname2 : (nvarchar(257))
  # SysObject_fullname : (nvarchar(261))
  # SysObject_fullname2 : (nvarchar(257))
  ~ SysObject_query_sql : (nvarchar(406))
  ~ usp_persistence_fullname : (nvarchar(273))
  # usp_persistence_fullname2 : (nvarchar(269))
  # usp_persistence_name : (nvarchar(140))
  --
}

entity "puml-link:dhw:sqldb:repo.sysobject_repoobject_via_guid.adoc[]" as repo.SysObject_RepoObject_via_guid << V >> {
  history_table_guid : (uniqueidentifier)
  history_table_id : (int)
  is_external : (bit)
  is_repo_managed : (bit)
  is_RepoObject_name_uniqueidentifier : (int)
  is_ssas : (bit)
  is_SysObject_name_uniqueidentifier : (int)
  - modify_date : (datetime)
  - parent_object_id : (int)
  Repo_history_table_guid : (uniqueidentifier)
  Repo_temporal_type : (tinyint)
  RepoObject_guid : (uniqueidentifier)
  RepoObject_is_SysObject_missing : (bit)
  RepoObject_name : (nvarchar(128))
  RepoObject_schema_name : (nvarchar(128))
  RepoObject_SysObject_id : (int)
  RepoObject_SysObject_modify_date : (datetime)
  RepoObject_SysObject_name : (nvarchar(128))
  RepoObject_SysObject_parent_object_id : (int)
  RepoObject_SysObject_schema_name : (nvarchar(128))
  RepoObject_SysObject_type : (char(2))
  RepoObject_type : (char(2))
  - SysObject_id : (int)
  - SysObject_name : (sysname)
  SysObject_RepoObject_guid : (uniqueidentifier)
  SysObject_schema_name : (sysname)
  SysObject_type : (char(2))
  SysObject_type_desc : (nvarchar(60))
  temporal_type : (tinyint)
  --
}

entity "puml-link:dhw:sqldb:repo.usp_sync_guid_repoobject.adoc[]" as repo.usp_sync_guid_RepoObject << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo_sys.sysobject.adoc[]" as repo_sys.SysObject << V >> {
  - create_date : (datetime)
  history_table_id : (int)
  - is_ms_shipped : (bit)
  - is_published : (bit)
  - is_schema_published : (bit)
  max_column_id_used : (int)
  - modify_date : (datetime)
  - parent_object_id : (int)
  principal_id : (int)
  - schema_id : (int)
  sql_modules_definition : (nvarchar(max))
  - SysObject_fullname : (nvarchar(517))
  - SysObject_fullname2 : (nvarchar(257))
  - SysObject_id : (int)
  - SysObject_name : (sysname)
  SysObject_RepoObject_guid : (uniqueidentifier)
  SysObject_schema_name : (sysname)
  temporal_type : (tinyint)
  temporal_type_desc : (nvarchar(60))
  type : (char(2))
  type_desc : (nvarchar(60))
  --
}

repo.RepoObject <.. repo.SysObject_RepoObject_via_guid
repo.SysObject_RepoObject_via_guid <.. repo.usp_sync_guid_RepoObject
repo_sys.SysObject <.. repo.SysObject_RepoObject_via_guid
"repo.RepoObject::is_external" <-- "repo.SysObject_RepoObject_via_guid::is_external"
"repo.RepoObject::is_repo_managed" <-- "repo.SysObject_RepoObject_via_guid::is_repo_managed"
"repo.RepoObject::is_RepoObject_name_uniqueidentifier" <-- "repo.SysObject_RepoObject_via_guid::is_RepoObject_name_uniqueidentifier"
"repo.RepoObject::is_ssas" <-- "repo.SysObject_RepoObject_via_guid::is_ssas"
"repo.RepoObject::is_SysObject_missing" <-- "repo.SysObject_RepoObject_via_guid::RepoObject_is_SysObject_missing"
"repo.RepoObject::is_SysObject_name_uniqueidentifier" <-- "repo.SysObject_RepoObject_via_guid::is_SysObject_name_uniqueidentifier"
"repo.RepoObject::Repo_history_table_guid" <-- "repo.SysObject_RepoObject_via_guid::Repo_history_table_guid"
"repo.RepoObject::Repo_temporal_type" <-- "repo.SysObject_RepoObject_via_guid::Repo_temporal_type"
"repo.RepoObject::RepoObject_guid" <-- "repo.SysObject_RepoObject_via_guid::history_table_guid"
"repo.RepoObject::RepoObject_guid" <-- "repo.SysObject_RepoObject_via_guid::RepoObject_guid"
"repo.RepoObject::RepoObject_name" <-- "repo.SysObject_RepoObject_via_guid::RepoObject_name"
"repo.RepoObject::RepoObject_schema_name" <-- "repo.SysObject_RepoObject_via_guid::RepoObject_schema_name"
"repo.RepoObject::RepoObject_type" <-- "repo.SysObject_RepoObject_via_guid::RepoObject_type"
"repo.RepoObject::SysObject_id" <-- "repo.SysObject_RepoObject_via_guid::RepoObject_SysObject_id"
"repo.RepoObject::SysObject_modify_date" <-- "repo.SysObject_RepoObject_via_guid::RepoObject_SysObject_modify_date"
"repo.RepoObject::SysObject_name" <-- "repo.SysObject_RepoObject_via_guid::RepoObject_SysObject_name"
"repo.RepoObject::SysObject_parent_object_id" <-- "repo.SysObject_RepoObject_via_guid::RepoObject_SysObject_parent_object_id"
"repo.RepoObject::SysObject_schema_name" <-- "repo.SysObject_RepoObject_via_guid::RepoObject_SysObject_schema_name"
"repo.RepoObject::SysObject_type" <-- "repo.SysObject_RepoObject_via_guid::RepoObject_SysObject_type"
"repo_sys.SysObject::history_table_id" <-- "repo.SysObject_RepoObject_via_guid::history_table_id"
"repo_sys.SysObject::modify_date" <-- "repo.SysObject_RepoObject_via_guid::modify_date"
"repo_sys.SysObject::parent_object_id" <-- "repo.SysObject_RepoObject_via_guid::parent_object_id"
"repo_sys.SysObject::SysObject_id" <-- "repo.SysObject_RepoObject_via_guid::SysObject_id"
"repo_sys.SysObject::SysObject_name" <-- "repo.SysObject_RepoObject_via_guid::SysObject_name"
"repo_sys.SysObject::SysObject_RepoObject_guid" <-- "repo.SysObject_RepoObject_via_guid::SysObject_RepoObject_guid"
"repo_sys.SysObject::SysObject_schema_name" <-- "repo.SysObject_RepoObject_via_guid::SysObject_schema_name"
"repo_sys.SysObject::temporal_type" <-- "repo.SysObject_RepoObject_via_guid::temporal_type"
"repo_sys.SysObject::type" <-- "repo.SysObject_RepoObject_via_guid::SysObject_type"
"repo_sys.SysObject::type_desc" <-- "repo.SysObject_RepoObject_via_guid::SysObject_type_desc"

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_colref[]


== sql_modules_definition

// tag::sql_modules_definition[]
[%collapsible]
=======
[source,sql,numbered,indent=0]
----

CREATE View repo.SysObject_RepoObject_via_guid
As
--
Select
    so.SysObject_id
  , ro.is_repo_managed
  , so.SysObject_schema_name
  , so.SysObject_name
  , SysObject_type                        = so.type
  , SysObject_type_desc                   = so.type_desc
  , modify_date                           = so.modify_date
  , parent_object_id                      = so.parent_object_id
  , SysObject_RepoObject_guid             = so.SysObject_RepoObject_guid
  , history_table_guid                    = ro_hist.RepoObject_guid
  , so.history_table_id
  , so.temporal_type
  --, [so].[max_column_id_used] AS         [SysObject_max_column_id_used]
  , ro.Repo_history_table_guid
  , ro.Repo_temporal_type
  , RepoObject_guid                       = ro.RepoObject_guid
  , ro.RepoObject_schema_name
  , ro.RepoObject_name
  , ro.RepoObject_type
  , RepoObject_SysObject_id               = ro.SysObject_id
  , RepoObject_SysObject_schema_name      = ro.SysObject_schema_name
  , RepoObject_SysObject_name             = ro.SysObject_name
  , RepoObject_SysObject_type             = ro.SysObject_type
  , RepoObject_SysObject_modify_date      = ro.SysObject_modify_date
  , RepoObject_SysObject_parent_object_id = ro.SysObject_parent_object_id
  , RepoObject_is_SysObject_missing       = ro.is_SysObject_missing
  , ro.is_RepoObject_name_uniqueidentifier
  , ro.is_SysObject_name_uniqueidentifier
  , ro.is_ssas
  , ro.is_external
--, [ro].SysObject_parent_object_id AS          [RepoObject_parent_SysObject_id]
--, [ro].[SysObject_temporal_type] AS      [RepoObject_SysObject_temporal_type]
--, [ro].[SysObject_history_table_id] AS   [RepoObject_SysObject_history_table_id]
--, [ro].[SysObject_max_column_id_used] AS [RepoObject_SysObject_max_column_id_used]
From
    repo_sys.SysObject  As so
    Left Outer Join
        repo.RepoObject As ro
            On
            ro.RepoObject_guid      = so.SysObject_RepoObject_guid
            And ro.is_ssas          = 0
            And ro.is_external      = 0

    Left Outer Join
        repo.RepoObject As ro_hist
            On
            ro_hist.SysObject_id    = so.history_table_id
            And ro_hist.is_ssas     = 0
            And ro_hist.is_external = 0

----
=======
// end::sql_modules_definition[]


