// tag::HeaderFullDisplayName[]
= repo.ForeignKey_ssas_IndexPattern - V
// end::HeaderFullDisplayName[]

== existing_properties

// tag::existing_properties[]

:ExistsProperty--antorareferencedlist:
:ExistsProperty--antorareferencinglist:
:ExistsProperty--is_repo_managed:
:ExistsProperty--is_ssas:
:ExistsProperty--referencedobjectlist:
:ExistsProperty--sql_modules_definition:
:ExistsProperty--FK:
:ExistsProperty--AntoraIndexList:
:ExistsProperty--Columns:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
676E8DEE-3D08-EC11-8515-A81E8446D5B0
// end::RepoObject_guid[]

== RepoObject_FullDisplayName2

// tag::RepoObject_FullDisplayName2[]
repo.ForeignKey_ssas_IndexPattern
// end::RepoObject_FullDisplayName2[]

== SysObject_type

// tag::SysObject_type[]
V 
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
view
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
375008417
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2021-09-01 14:55:47
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]
[discrete]
== _


[#column-databasename]
=== databasename

[cols="d,8a,m,m,m"]
|===
|
|databasename
|nvarchar(128)
|NOT NULL
|
|===

.Referenced Columns
--
* xref:ssas.model_json_32_relationships_t.adoc#column-databasename[+ssas.model_json_32_relationships_T.databasename+]
--

.Referencing Columns
--
* xref:docs.ssas_pumlrelation.adoc#column-schemaname[+docs.ssas_PumlRelation.SchemaName+]
* xref:repo.foreignkey_ssas_indexes.adoc#column-referencedunderlinesysobjectunderlineschemaunderlinename[+repo.ForeignKey_ssas_Indexes.referenced_SysObject_schema_name+]
* xref:repo.foreignkey_ssas_indexes.adoc#column-referencingunderlinesysobjectunderlineschemaunderlinename[+repo.ForeignKey_ssas_Indexes.referencing_SysObject_schema_name+]
--


[#column-deleteunderlinereferentialunderlineaction]
=== delete_referential_action

[cols="d,8a,m,m,m"]
|===
|
|delete_referential_action
|tinyint
|NULL
|
|===

.Referencing Columns
--
* xref:docs.ssas_pumlrelation.adoc#column-deleteunderlinereferentialunderlineaction[+docs.ssas_PumlRelation.delete_referential_action+]
* xref:repo.foreignkey_ssas_indexes.adoc#column-deleteunderlinereferentialunderlineaction[+repo.ForeignKey_ssas_Indexes.delete_referential_action+]
--


[#column-foreignkeyunderlinefullname]
=== ForeignKey_fullname

[cols="d,8a,m,m,m"]
|===
|
|ForeignKey_fullname
|nvarchar(517)
|NULL
|
|===

.Referencing Columns
--
* xref:docs.ssas_pumlrelation.adoc#column-foreignkeyunderlinefullname[+docs.ssas_PumlRelation.ForeignKey_fullname+]
* xref:repo.foreignkey_ssas_indexes.adoc#column-foreignkeyunderlinefullname[+repo.ForeignKey_ssas_Indexes.ForeignKey_fullname+]
--


[#column-foreignkeyunderlineguid]
=== ForeignKey_guid

[cols="d,8a,m,m,m"]
|===
|
|ForeignKey_guid
|uniqueidentifier
|NOT NULL
|
|===

.Referenced Columns
--
* xref:ssas.model_json_32_relationships_t.adoc#column-foreignkeyunderlineguid[+ssas.model_json_32_relationships_T.ForeignKey_guid+]
--

.Referencing Columns
--
* xref:docs.ssas_pumlrelation.adoc#column-foreignkeyunderlineguid[+docs.ssas_PumlRelation.ForeignKey_guid+]
* xref:repo.foreignkey_ssas_indexes.adoc#column-foreignkeyunderlineguid[+repo.ForeignKey_ssas_Indexes.ForeignKey_guid+]
--


[#column-foreignkeyunderlinename]
=== ForeignKey_name

[cols="d,8a,m,m,m"]
|===
|
|ForeignKey_name
|nvarchar(263)
|NULL
|
|===

.Referencing Columns
--
* xref:docs.ssas_pumlrelation.adoc#column-foreignkeyunderlinename[+docs.ssas_PumlRelation.ForeignKey_name+]
* xref:repo.foreignkey_ssas_indexes.adoc#column-foreignkeyunderlinename[+repo.ForeignKey_ssas_Indexes.ForeignKey_name+]
--


[#column-referencedunderlinecolumnname]
=== referenced_ColumnName

[cols="d,8a,m,m,m"]
|===
|
|referenced_ColumnName
|nvarchar(128)
|NULL
|
|===

.Referenced Columns
--
* xref:ssas.model_json_311_tables_columns_t.adoc#column-tablesunderlinecolumnsunderlinename[+ssas.model_json_311_tables_columns_T.tables_columns_name+]
--

.Referencing Columns
--
* xref:docs.ssas_pumlrelation.adoc#column-referencedunderlinecolumnname[+docs.ssas_PumlRelation.referenced_ColumnName+]
--


[#column-referencedunderlineindexpatterncolumndatatype]
=== referenced_IndexPatternColumnDatatype

[cols="d,8a,m,m,m"]
|===
|
|referenced_IndexPatternColumnDatatype
|nvarchar(500)
|NULL
|
|===

.Referenced Columns
--
* xref:ssas.model_json_311_tables_columns_t.adoc#column-tablesunderlinecolumnsunderlinedatatype[+ssas.model_json_311_tables_columns_T.tables_columns_dataType+]
--

.Referencing Columns
--
* xref:docs.ssas_pumlrelation.adoc#column-referencedunderlineindexpatterncolumndatatype[+docs.ssas_PumlRelation.referenced_IndexPatternColumnDatatype+]
* xref:repo.foreignkey_ssas_indexes.adoc#column-referencedunderlineindexpatterncolumndatatype[+repo.ForeignKey_ssas_Indexes.referenced_IndexPatternColumnDatatype+]
--


[#column-referencedunderlineindexpatterncolumnguid]
=== referenced_IndexPatternColumnGuid

[cols="d,8a,m,m,m"]
|===
|
|referenced_IndexPatternColumnGuid
|varchar(36)
|NULL
|
|===

.Referencing Columns
--
* xref:docs.ssas_pumlrelation.adoc#column-referencedunderlineindexpatterncolumnguid[+docs.ssas_PumlRelation.referenced_IndexPatternColumnGuid+]
--


[#column-referencedunderlineindexpatterncolumnname]
=== referenced_IndexPatternColumnName

[cols="d,8a,m,m,m"]
|===
|
|referenced_IndexPatternColumnName
|nvarchar(128)
|NULL
|
|===

.Referenced Columns
--
* xref:ssas.model_json_311_tables_columns_t.adoc#column-tablesunderlinecolumnsunderlinename[+ssas.model_json_311_tables_columns_T.tables_columns_name+]
--

.Referencing Columns
--
* xref:docs.ssas_pumlrelation.adoc#column-referencedunderlineindexpatterncolumnname[+docs.ssas_PumlRelation.referenced_IndexPatternColumnName+]
* xref:repo.foreignkey_ssas_indexes.adoc#column-referencedunderlineindexpatterncolumnname[+repo.ForeignKey_ssas_Indexes.referenced_IndexPatternColumnName+]
--


[#column-referencedunderlineiskey]
=== referenced_IsKey

[cols="d,8a,m,m,m"]
|===
|
|referenced_IsKey
|bit
|NOT NULL
|
|===


[#column-referencedunderlineisnullable]
=== referenced_IsNullable

[cols="d,8a,m,m,m"]
|===
|
|referenced_IsNullable
|bit
|NOT NULL
|
|===


[#column-referencedunderlineobjectname]
=== referenced_ObjectName

[cols="d,8a,m,m,m"]
|===
|
|referenced_ObjectName
|nvarchar(128)
|NULL
|
|===

.Referenced Columns
--
* xref:ssas.model_json_31_tables_t.adoc#column-tablesunderlinename[+ssas.model_json_31_tables_T.tables_name+]
--

.Referencing Columns
--
* xref:docs.ssas_pumlrelation.adoc#column-referencedunderlineobjectname[+docs.ssas_PumlRelation.referenced_ObjectName+]
* xref:repo.foreignkey_ssas_indexes.adoc#column-referencedunderlinesysobjectunderlinename[+repo.ForeignKey_ssas_Indexes.referenced_SysObject_name+]
--


[#column-referencedunderlinerepoobjectunderlinefullname]
=== referenced_RepoObject_fullname

[cols="d,8a,m,m,m"]
|===
|
|referenced_RepoObject_fullname
|nvarchar(517)
|NULL
|
|===

.Referencing Columns
--
* xref:docs.ssas_pumlrelation.adoc#column-referencedunderlinerepoobjectunderlinefullname[+docs.ssas_PumlRelation.referenced_RepoObject_fullname+]
* xref:repo.foreignkey_ssas_indexes.adoc#column-referencedunderlinerepoobjectunderlinefullname[+repo.ForeignKey_ssas_Indexes.referenced_RepoObject_fullname+]
--


[#column-referencedunderlinerepoobjectunderlinefullname2]
=== referenced_RepoObject_fullname2

[cols="d,8a,m,m,m"]
|===
|
|referenced_RepoObject_fullname2
|nvarchar(257)
|NULL
|
|===

.Referencing Columns
--
* xref:docs.ssas_pumlrelation.adoc#column-referencedunderlinerepoobjectunderlinefullname2[+docs.ssas_PumlRelation.referenced_RepoObject_fullname2+]
* xref:repo.foreignkey_ssas_indexes.adoc#column-referencedunderlinerepoobjectunderlinefullname2[+repo.ForeignKey_ssas_Indexes.referenced_RepoObject_fullname2+]
--


[#column-referencedunderlinerepoobjectunderlineguid]
=== referenced_RepoObject_guid

[cols="d,8a,m,m,m"]
|===
|
|referenced_RepoObject_guid
|uniqueidentifier
|NULL
|
|===

.Referenced Columns
--
* xref:ssas.model_json_31_tables_t.adoc#column-repoobjectunderlineguid[+ssas.model_json_31_tables_T.RepoObject_guid+]
--

.Referencing Columns
--
* xref:docs.ssas_pumlrelation.adoc#column-referencedunderlinerepoobjectunderlineguid[+docs.ssas_PumlRelation.referenced_RepoObject_guid+]
* xref:repo.foreignkey_ssas_indexes.adoc#column-referencedunderlinerepoobjectunderlineguid[+repo.ForeignKey_ssas_Indexes.referenced_RepoObject_guid+]
--


[#column-referencingunderlinecolumnname]
=== referencing_ColumnName

[cols="d,8a,m,m,m"]
|===
|
|referencing_ColumnName
|nvarchar(128)
|NULL
|
|===

.Referenced Columns
--
* xref:ssas.model_json_311_tables_columns_t.adoc#column-tablesunderlinecolumnsunderlinename[+ssas.model_json_311_tables_columns_T.tables_columns_name+]
--

.Referencing Columns
--
* xref:docs.ssas_pumlrelation.adoc#column-referencingunderlinecolumnname[+docs.ssas_PumlRelation.referencing_ColumnName+]
--


[#column-referencingunderlineindexpatterncolumndatatype]
=== referencing_IndexPatternColumnDatatype

[cols="d,8a,m,m,m"]
|===
|
|referencing_IndexPatternColumnDatatype
|nvarchar(500)
|NULL
|
|===

.Referenced Columns
--
* xref:ssas.model_json_311_tables_columns_t.adoc#column-tablesunderlinecolumnsunderlinedatatype[+ssas.model_json_311_tables_columns_T.tables_columns_dataType+]
--

.Referencing Columns
--
* xref:docs.ssas_pumlrelation.adoc#column-referencingunderlineindexpatterncolumndatatype[+docs.ssas_PumlRelation.referencing_IndexPatternColumnDatatype+]
* xref:repo.foreignkey_ssas_indexes.adoc#column-referencingunderlineindexpatterncolumndatatype[+repo.ForeignKey_ssas_Indexes.referencing_IndexPatternColumnDatatype+]
--


[#column-referencingunderlineindexpatterncolumnguid]
=== referencing_IndexPatternColumnGuid

[cols="d,8a,m,m,m"]
|===
|
|referencing_IndexPatternColumnGuid
|varchar(36)
|NULL
|
|===

.Referencing Columns
--
* xref:docs.ssas_pumlrelation.adoc#column-referencingunderlineindexpatterncolumnguid[+docs.ssas_PumlRelation.referencing_IndexPatternColumnGuid+]
--


[#column-referencingunderlineindexpatterncolumnname]
=== referencing_IndexPatternColumnName

[cols="d,8a,m,m,m"]
|===
|
|referencing_IndexPatternColumnName
|nvarchar(128)
|NULL
|
|===

.Referenced Columns
--
* xref:ssas.model_json_311_tables_columns_t.adoc#column-tablesunderlinecolumnsunderlinename[+ssas.model_json_311_tables_columns_T.tables_columns_name+]
--

.Referencing Columns
--
* xref:docs.ssas_pumlrelation.adoc#column-referencingunderlineindexpatterncolumnname[+docs.ssas_PumlRelation.referencing_IndexPatternColumnName+]
* xref:repo.foreignkey_ssas_indexes.adoc#column-referencingunderlineindexpatterncolumnname[+repo.ForeignKey_ssas_Indexes.referencing_IndexPatternColumnName+]
--


[#column-referencingunderlineiskey]
=== referencing_IsKey

[cols="d,8a,m,m,m"]
|===
|
|referencing_IsKey
|bit
|NOT NULL
|
|===


[#column-referencingunderlineisnullable]
=== referencing_IsNullable

[cols="d,8a,m,m,m"]
|===
|
|referencing_IsNullable
|bit
|NOT NULL
|
|===


[#column-referencingunderlineobjectname]
=== referencing_ObjectName

[cols="d,8a,m,m,m"]
|===
|
|referencing_ObjectName
|nvarchar(128)
|NULL
|
|===

.Referenced Columns
--
* xref:ssas.model_json_31_tables_t.adoc#column-tablesunderlinename[+ssas.model_json_31_tables_T.tables_name+]
--

.Referencing Columns
--
* xref:docs.ssas_pumlrelation.adoc#column-referencingunderlineobjectname[+docs.ssas_PumlRelation.referencing_ObjectName+]
* xref:repo.foreignkey_ssas_indexes.adoc#column-referencingunderlinesysobjectunderlinename[+repo.ForeignKey_ssas_Indexes.referencing_SysObject_name+]
--


[#column-referencingunderlinerepoobjectunderlinefullname]
=== referencing_RepoObject_fullname

[cols="d,8a,m,m,m"]
|===
|
|referencing_RepoObject_fullname
|nvarchar(517)
|NULL
|
|===

.Referencing Columns
--
* xref:docs.ssas_pumlrelation.adoc#column-referencingunderlinerepoobjectunderlinefullname[+docs.ssas_PumlRelation.referencing_RepoObject_fullname+]
* xref:repo.foreignkey_ssas_indexes.adoc#column-referencingunderlinerepoobjectunderlinefullname[+repo.ForeignKey_ssas_Indexes.referencing_RepoObject_fullname+]
--


[#column-referencingunderlinerepoobjectunderlinefullname2]
=== referencing_RepoObject_fullname2

[cols="d,8a,m,m,m"]
|===
|
|referencing_RepoObject_fullname2
|nvarchar(257)
|NULL
|
|===

.Referencing Columns
--
* xref:docs.ssas_pumlrelation.adoc#column-referencingunderlinerepoobjectunderlinefullname2[+docs.ssas_PumlRelation.referencing_RepoObject_fullname2+]
* xref:repo.foreignkey_ssas_indexes.adoc#column-referencingunderlinerepoobjectunderlinefullname2[+repo.ForeignKey_ssas_Indexes.referencing_RepoObject_fullname2+]
--


[#column-referencingunderlinerepoobjectunderlineguid]
=== referencing_RepoObject_guid

[cols="d,8a,m,m,m"]
|===
|
|referencing_RepoObject_guid
|uniqueidentifier
|NULL
|
|===

.Referenced Columns
--
* xref:ssas.model_json_31_tables_t.adoc#column-repoobjectunderlineguid[+ssas.model_json_31_tables_T.RepoObject_guid+]
--

.Referencing Columns
--
* xref:docs.ssas_pumlrelation.adoc#column-referencingunderlinerepoobjectunderlineguid[+docs.ssas_PumlRelation.referencing_RepoObject_guid+]
* xref:repo.foreignkey_ssas_indexes.adoc#column-referencingunderlinerepoobjectunderlineguid[+repo.ForeignKey_ssas_Indexes.referencing_RepoObject_guid+]
--


[#column-relationshipsunderlinecrossfilteringbehavior]
=== relationships_crossFilteringBehavior

[cols="d,8a,m,m,m"]
|===
|
|relationships_crossFilteringBehavior
|nvarchar(500)
|NULL
|
|===

.Referenced Columns
--
* xref:ssas.model_json_32_relationships_t.adoc#column-relationshipsunderlinecrossfilteringbehavior[+ssas.model_json_32_relationships_T.relationships_crossFilteringBehavior+]
--

.Referencing Columns
--
* xref:docs.ssas_pumlrelation.adoc#column-relationshipsunderlinecrossfilteringbehavior[+docs.ssas_PumlRelation.relationships_crossFilteringBehavior+]
--


[#column-relationshipsunderlinefromcardinality]
=== relationships_fromCardinality

[cols="d,8a,m,m,m"]
|===
|
|relationships_fromCardinality
|nvarchar(500)
|NULL
|
|===

.Referenced Columns
--
* xref:ssas.model_json_32_relationships_t.adoc#column-relationshipsunderlinefromcardinality[+ssas.model_json_32_relationships_T.relationships_fromCardinality+]
--

.Referencing Columns
--
* xref:docs.ssas_pumlrelation.adoc#column-relationshipsunderlinefromcardinality[+docs.ssas_PumlRelation.relationships_fromCardinality+]
--


[#column-relationshipsunderlineisactive]
=== relationships_isActive

[cols="d,8a,m,m,m"]
|===
|
|relationships_isActive
|bit
|NOT NULL
|
|===

.Referenced Columns
--
* xref:ssas.model_json_32_relationships_t.adoc#column-relationshipsunderlineisactive[+ssas.model_json_32_relationships_T.relationships_isActive+]
--

.Referencing Columns
--
* xref:docs.ssas_pumlrelation.adoc#column-relationshipsunderlineisactive[+docs.ssas_PumlRelation.relationships_isActive+]
--


[#column-relationshipsunderlinename]
=== relationships_name

[cols="d,8a,m,m,m"]
|===
|
|relationships_name
|nvarchar(500)
|NULL
|
|===

.Referenced Columns
--
* xref:ssas.model_json_32_relationships_t.adoc#column-relationshipsunderlinename[+ssas.model_json_32_relationships_T.relationships_name+]
--

.Referencing Columns
--
* xref:docs.ssas_pumlrelation.adoc#column-relationshipsunderlinename[+docs.ssas_PumlRelation.relationships_name+]
--


[#column-relationshipsunderlinetocardinality]
=== relationships_toCardinality

[cols="d,8a,m,m,m"]
|===
|
|relationships_toCardinality
|nvarchar(500)
|NULL
|
|===

.Referenced Columns
--
* xref:ssas.model_json_32_relationships_t.adoc#column-relationshipsunderlinetocardinality[+ssas.model_json_32_relationships_T.relationships_toCardinality+]
--

.Referencing Columns
--
* xref:docs.ssas_pumlrelation.adoc#column-relationshipsunderlinetocardinality[+docs.ssas_PumlRelation.relationships_toCardinality+]
--


[#column-updateunderlinereferentialunderlineaction]
=== update_referential_action

[cols="d,8a,m,m,m"]
|===
|
|update_referential_action
|tinyint
|NULL
|
|===

.Referencing Columns
--
* xref:docs.ssas_pumlrelation.adoc#column-updateunderlinereferentialunderlineaction[+docs.ssas_PumlRelation.update_referential_action+]
* xref:repo.foreignkey_ssas_indexes.adoc#column-updateunderlinereferentialunderlineaction[+repo.ForeignKey_ssas_Indexes.update_referential_action+]
--


// end::AntoraColumnDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]































// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]
|
|<<column-databasename>>
|nvarchar(128)
|NOT NULL
|

|
|<<column-deleteunderlinereferentialunderlineaction>>
|tinyint
|NULL
|

|
|<<column-foreignkeyunderlinefullname>>
|nvarchar(517)
|NULL
|

|
|<<column-foreignkeyunderlineguid>>
|uniqueidentifier
|NOT NULL
|

|
|<<column-foreignkeyunderlinename>>
|nvarchar(263)
|NULL
|

|
|<<column-referencedunderlinecolumnname>>
|nvarchar(128)
|NULL
|

|
|<<column-referencedunderlineindexpatterncolumndatatype>>
|nvarchar(500)
|NULL
|

|
|<<column-referencedunderlineindexpatterncolumnguid>>
|varchar(36)
|NULL
|

|
|<<column-referencedunderlineindexpatterncolumnname>>
|nvarchar(128)
|NULL
|

|
|<<column-referencedunderlineiskey>>
|bit
|NOT NULL
|

|
|<<column-referencedunderlineisnullable>>
|bit
|NOT NULL
|

|
|<<column-referencedunderlineobjectname>>
|nvarchar(128)
|NULL
|

|
|<<column-referencedunderlinerepoobjectunderlinefullname>>
|nvarchar(517)
|NULL
|

|
|<<column-referencedunderlinerepoobjectunderlinefullname2>>
|nvarchar(257)
|NULL
|

|
|<<column-referencedunderlinerepoobjectunderlineguid>>
|uniqueidentifier
|NULL
|

|
|<<column-referencingunderlinecolumnname>>
|nvarchar(128)
|NULL
|

|
|<<column-referencingunderlineindexpatterncolumndatatype>>
|nvarchar(500)
|NULL
|

|
|<<column-referencingunderlineindexpatterncolumnguid>>
|varchar(36)
|NULL
|

|
|<<column-referencingunderlineindexpatterncolumnname>>
|nvarchar(128)
|NULL
|

|
|<<column-referencingunderlineiskey>>
|bit
|NOT NULL
|

|
|<<column-referencingunderlineisnullable>>
|bit
|NOT NULL
|

|
|<<column-referencingunderlineobjectname>>
|nvarchar(128)
|NULL
|

|
|<<column-referencingunderlinerepoobjectunderlinefullname>>
|nvarchar(517)
|NULL
|

|
|<<column-referencingunderlinerepoobjectunderlinefullname2>>
|nvarchar(257)
|NULL
|

|
|<<column-referencingunderlinerepoobjectunderlineguid>>
|uniqueidentifier
|NULL
|

|
|<<column-relationshipsunderlinecrossfilteringbehavior>>
|nvarchar(500)
|NULL
|

|
|<<column-relationshipsunderlinefromcardinality>>
|nvarchar(500)
|NULL
|

|
|<<column-relationshipsunderlineisactive>>
|bit
|NOT NULL
|

|
|<<column-relationshipsunderlinename>>
|nvarchar(500)
|NULL
|

|
|<<column-relationshipsunderlinetocardinality>>
|nvarchar(500)
|NULL
|

|
|<<column-updateunderlinereferentialunderlineaction>>
|tinyint
|NULL
|

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

[#index-idxunderlineforeignkeyunderlinessasunderlineindexpatternunderlineunderline1]
=== idx_ForeignKey_ssas_IndexPattern++__++1

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-referencing_ObjectName>>; nvarchar(128)
--
* PK, Unique, Real: 0, 0, 0


[#index-idxunderlineforeignkeyunderlinessasunderlineindexpatternunderlineunderline2]
=== idx_ForeignKey_ssas_IndexPattern++__++2

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-referenced_ObjectName>>; nvarchar(128)
--
* PK, Unique, Real: 0, 0, 0


[#index-idxunderlineforeignkeyunderlinessasunderlineindexpatternunderlineunderline3]
=== idx_ForeignKey_ssas_IndexPattern++__++3

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-referencing_ColumnName>>; nvarchar(128)
--
* PK, Unique, Real: 0, 0, 0


[#index-idxunderlineforeignkeyunderlinessasunderlineindexpatternunderlineunderline4]
=== idx_ForeignKey_ssas_IndexPattern++__++4

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-referenced_ColumnName>>; nvarchar(128)
--
* PK, Unique, Real: 0, 0, 0


[#index-idxunderlineforeignkeyunderlinessasunderlineindexpatternunderlineunderline5]
=== idx_ForeignKey_ssas_IndexPattern++__++5

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-referencing_IndexPatternColumnName>>; nvarchar(128)
--
* PK, Unique, Real: 0, 0, 0


[#index-idxunderlineforeignkeyunderlinessasunderlineindexpatternunderlineunderline6]
=== idx_ForeignKey_ssas_IndexPattern++__++6

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-referenced_IndexPatternColumnName>>; nvarchar(128)
--
* PK, Unique, Real: 0, 0, 0


[#index-idxunderlineforeignkeyunderlinessasunderlineindexpatternunderlineunderline7]
=== idx_ForeignKey_ssas_IndexPattern++__++7

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-ForeignKey_guid>>; uniqueidentifier
--
* PK, Unique, Real: 0, 0, 0


[#index-idxunderlineforeignkeyunderlinessasunderlineindexpatternunderlineunderline8]
=== idx_ForeignKey_ssas_IndexPattern++__++8

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-databasename>>; nvarchar(128)
* <<column-relationships_name>>; nvarchar(500)
--
* PK, Unique, Real: 0, 0, 0


[#index-idxunderlineforeignkeyunderlinessasunderlineindexpatternunderlineunderline9]
=== idx_ForeignKey_ssas_IndexPattern++__++9

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-databasename>>; nvarchar(128)
--
* PK, Unique, Real: 0, 0, 0

// end::AntoraIndexList[]

== AntoraMeasureDetails

// tag::AntoraMeasureDetails[]

// end::AntoraMeasureDetails[]

== AntoraMeasureDescriptions



== AntoraParameterList

// tag::AntoraParameterList[]

// end::AntoraParameterList[]

== AntoraXrefCulturesList

// tag::AntoraXrefCulturesList[]
* xref:dhw:sqldb:repo.foreignkey_ssas_indexpattern.adoc[] - 
// end::AntoraXrefCulturesList[]

== cultures_count

// tag::cultures_count[]
1
// end::cultures_count[]

== Other tags

source: property.RepoObjectProperty_cross As rop_cross


=== additional_reference_csv

// tag::additional_reference_csv[]

// end::additional_reference_csv[]


=== AdocUspSteps

// tag::adocuspsteps[]

// end::adocuspsteps[]


=== AntoraReferencedList

// tag::antorareferencedlist[]
* xref:dhw:sqldb:ssas.model_json_31_tables_t.adoc[]
* xref:dhw:sqldb:ssas.model_json_311_tables_columns_t.adoc[]
* xref:dhw:sqldb:ssas.model_json_32_relationships_t.adoc[]
// end::antorareferencedlist[]


=== AntoraReferencingList

// tag::antorareferencinglist[]
* xref:dhw:sqldb:docs.ssas_pumlrelation.adoc[]
* xref:dhw:sqldb:repo.foreignkey_ssas_indexes.adoc[]
// end::antorareferencinglist[]


=== Description

// tag::description[]

// end::description[]


=== exampleUsage

// tag::exampleusage[]

// end::exampleusage[]


=== exampleUsage_2

// tag::exampleusage_2[]

// end::exampleusage_2[]


=== exampleUsage_3

// tag::exampleusage_3[]

// end::exampleusage_3[]


=== exampleUsage_4

// tag::exampleusage_4[]

// end::exampleusage_4[]


=== exampleUsage_5

// tag::exampleusage_5[]

// end::exampleusage_5[]


=== exampleWrong_Usage

// tag::examplewrong_usage[]

// end::examplewrong_usage[]


=== has_execution_plan_issue

// tag::has_execution_plan_issue[]

// end::has_execution_plan_issue[]


=== has_get_referenced_issue

// tag::has_get_referenced_issue[]

// end::has_get_referenced_issue[]


=== has_history

// tag::has_history[]

// end::has_history[]


=== has_history_columns

// tag::has_history_columns[]

// end::has_history_columns[]


=== InheritanceType

// tag::inheritancetype[]

// end::inheritancetype[]


=== is_persistence

// tag::is_persistence[]

// end::is_persistence[]


=== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]

// end::is_persistence_check_duplicate_per_pk[]


=== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]

// end::is_persistence_check_for_empty_source[]


=== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]

// end::is_persistence_delete_changed[]


=== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]

// end::is_persistence_delete_missing[]


=== is_persistence_insert

// tag::is_persistence_insert[]

// end::is_persistence_insert[]


=== is_persistence_truncate

// tag::is_persistence_truncate[]

// end::is_persistence_truncate[]


=== is_persistence_update_changed

// tag::is_persistence_update_changed[]

// end::is_persistence_update_changed[]


=== is_repo_managed

// tag::is_repo_managed[]
0
// end::is_repo_managed[]


=== is_ssas

// tag::is_ssas[]
0
// end::is_ssas[]


=== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


=== MS_Description

// tag::ms_description[]

// end::ms_description[]


=== persistence_source_RepoObject_fullname

// tag::persistence_source_repoobject_fullname[]

// end::persistence_source_repoobject_fullname[]


=== persistence_source_RepoObject_fullname2

// tag::persistence_source_repoobject_fullname2[]

// end::persistence_source_repoobject_fullname2[]


=== persistence_source_RepoObject_guid

// tag::persistence_source_repoobject_guid[]

// end::persistence_source_repoobject_guid[]


=== persistence_source_RepoObject_xref

// tag::persistence_source_repoobject_xref[]

// end::persistence_source_repoobject_xref[]


=== pk_index_guid

// tag::pk_index_guid[]

// end::pk_index_guid[]


=== pk_IndexPatternColumnDatatype

// tag::pk_indexpatterncolumndatatype[]

// end::pk_indexpatterncolumndatatype[]


=== pk_IndexPatternColumnName

// tag::pk_indexpatterncolumnname[]

// end::pk_indexpatterncolumnname[]


=== pk_IndexSemanticGroup

// tag::pk_indexsemanticgroup[]

// end::pk_indexsemanticgroup[]


=== ReferencedObjectList

// tag::referencedobjectlist[]
* [ssas].[model_json_31_tables_T]
* [ssas].[model_json_311_tables_columns_T]
* [ssas].[model_json_32_relationships_T]
// end::referencedobjectlist[]


=== usp_persistence_RepoObject_guid

// tag::usp_persistence_repoobject_guid[]

// end::usp_persistence_repoobject_guid[]


=== UspExamples

// tag::uspexamples[]

// end::uspexamples[]


=== uspgenerator_usp_id

// tag::uspgenerator_usp_id[]

// end::uspgenerator_usp_id[]


=== UspParameters

// tag::uspparameters[]

// end::uspparameters[]

== Boolean Attributes

source: property.RepoObjectProperty WHERE property_int = 1

// tag::boolean_attributes[]


// end::boolean_attributes[]

== PlantUML diagrams

=== PlantUML Entity

// tag::puml_entity[]
[plantuml, entity-{docname}, svg, subs=macros]
....
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:repo.foreignkey_ssas_indexpattern.adoc[]" as repo.ForeignKey_ssas_IndexPattern << V >> {
  - databasename : (nvarchar(128))
  delete_referential_action : (tinyint)
  ForeignKey_fullname : (nvarchar(517))
  - ForeignKey_guid : (uniqueidentifier)
  ForeignKey_name : (nvarchar(263))
  referenced_ColumnName : (nvarchar(128))
  referenced_IndexPatternColumnDatatype : (nvarchar(500))
  referenced_IndexPatternColumnGuid : (varchar(36))
  referenced_IndexPatternColumnName : (nvarchar(128))
  - referenced_IsKey : (bit)
  - referenced_IsNullable : (bit)
  referenced_ObjectName : (nvarchar(128))
  referenced_RepoObject_fullname : (nvarchar(517))
  referenced_RepoObject_fullname2 : (nvarchar(257))
  referenced_RepoObject_guid : (uniqueidentifier)
  referencing_ColumnName : (nvarchar(128))
  referencing_IndexPatternColumnDatatype : (nvarchar(500))
  referencing_IndexPatternColumnGuid : (varchar(36))
  referencing_IndexPatternColumnName : (nvarchar(128))
  - referencing_IsKey : (bit)
  - referencing_IsNullable : (bit)
  referencing_ObjectName : (nvarchar(128))
  referencing_RepoObject_fullname : (nvarchar(517))
  referencing_RepoObject_fullname2 : (nvarchar(257))
  referencing_RepoObject_guid : (uniqueidentifier)
  relationships_crossFilteringBehavior : (nvarchar(500))
  relationships_fromCardinality : (nvarchar(500))
  - relationships_isActive : (bit)
  relationships_name : (nvarchar(500))
  relationships_toCardinality : (nvarchar(500))
  update_referential_action : (tinyint)
  --
}
....

// end::puml_entity[]

=== PlantUML Entity 1 1 FK

// tag::puml_entity_1_1_fk[]
[plantuml, entity_1_1_fk-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:repo.foreignkey_ssas_indexpattern.adoc[]" as repo.ForeignKey_ssas_IndexPattern << V >> {
- idx_ForeignKey_ssas_IndexPattern__1

..
referencing_ObjectName; nvarchar(128)
--
- idx_ForeignKey_ssas_IndexPattern__2

..
referenced_ObjectName; nvarchar(128)
--
- idx_ForeignKey_ssas_IndexPattern__3

..
referencing_ColumnName; nvarchar(128)
--
- idx_ForeignKey_ssas_IndexPattern__4

..
referenced_ColumnName; nvarchar(128)
--
- idx_ForeignKey_ssas_IndexPattern__5

..
referencing_IndexPatternColumnName; nvarchar(128)
--
- idx_ForeignKey_ssas_IndexPattern__6

..
referenced_IndexPatternColumnName; nvarchar(128)
--
- idx_ForeignKey_ssas_IndexPattern__7

..
ForeignKey_guid; uniqueidentifier
--
- idx_ForeignKey_ssas_IndexPattern__8

..
databasename; nvarchar(128)
relationships_name; nvarchar(500)
--
- idx_ForeignKey_ssas_IndexPattern__9

..
databasename; nvarchar(128)
}



footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_fk[]

=== PlantUML 1 1 ObjectRef

// tag::puml_entity_1_1_objectref[]
[plantuml, entity_1_1_objectref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:docs.ssas_pumlrelation.adoc[]" as docs.ssas_PumlRelation << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.foreignkey_ssas_indexes.adoc[]" as repo.ForeignKey_ssas_Indexes << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.foreignkey_ssas_indexpattern.adoc[]" as repo.ForeignKey_ssas_IndexPattern << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31_tables_t.adoc[]" as ssas.model_json_31_tables_T << U >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_311_tables_columns_t.adoc[]" as ssas.model_json_311_tables_columns_T << U >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  - **tables_columns_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_32_relationships_t.adoc[]" as ssas.model_json_32_relationships_T << U >> {
  - **ForeignKey_guid** : (uniqueidentifier)
  --
}

repo.ForeignKey_ssas_IndexPattern <.. repo.ForeignKey_ssas_Indexes
repo.ForeignKey_ssas_IndexPattern <.. docs.ssas_PumlRelation
ssas.model_json_31_tables_T <.. repo.ForeignKey_ssas_IndexPattern
ssas.model_json_311_tables_columns_T <.. repo.ForeignKey_ssas_IndexPattern
ssas.model_json_32_relationships_T <.. repo.ForeignKey_ssas_IndexPattern

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_objectref[]

=== PlantUML 30 0 ObjectRef

// tag::puml_entity_30_0_objectref[]
[plantuml, entity_30_0_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:repo.foreignkey_ssas_indexpattern.adoc[]" as repo.ForeignKey_ssas_IndexPattern << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json.adoc[]" as ssas.model_json << U >> {
  - **databasename** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_10.adoc[]" as ssas.model_json_10 << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_20.adoc[]" as ssas.model_json_20 << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31_tables.adoc[]" as ssas.model_json_31_tables << V >> {
  - **databasename** : (nvarchar(128))
  **tables_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31_tables_t.adoc[]" as ssas.model_json_31_tables_T << U >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_311_tables_columns.adoc[]" as ssas.model_json_311_tables_columns << V >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  **tables_columns_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_311_tables_columns_t.adoc[]" as ssas.model_json_311_tables_columns_T << U >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  - **tables_columns_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_32_relationships.adoc[]" as ssas.model_json_32_relationships << V >> {
  - **databasename** : (nvarchar(128))
  **relationships_name** : (nvarchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_32_relationships_t.adoc[]" as ssas.model_json_32_relationships_T << U >> {
  - **ForeignKey_guid** : (uniqueidentifier)
  --
}

ssas.model_json <.. ssas.model_json_10
ssas.model_json_10 <.. ssas.model_json_20
ssas.model_json_20 <.. ssas.model_json_31_tables
ssas.model_json_20 <.. ssas.model_json_32_relationships
ssas.model_json_31_tables <.. ssas.model_json_31_tables_T
ssas.model_json_31_tables_T <.. ssas.model_json_311_tables_columns
ssas.model_json_31_tables_T <.. repo.ForeignKey_ssas_IndexPattern
ssas.model_json_311_tables_columns <.. ssas.model_json_311_tables_columns_T
ssas.model_json_311_tables_columns_T <.. repo.ForeignKey_ssas_IndexPattern
ssas.model_json_32_relationships <.. ssas.model_json_32_relationships_T
ssas.model_json_32_relationships_T <.. repo.ForeignKey_ssas_IndexPattern

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_30_0_objectref[]

=== PlantUML 0 30 ObjectRef

// tag::puml_entity_0_30_objectref[]
[plantuml, entity_0_30_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:docs.antoranavlistpage_by_schema.adoc[]" as docs.AntoraNavListPage_by_schema << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.foreignkey_relationscript.adoc[]" as docs.ForeignKey_RelationScript << V >> {
  **referenced_RepoObject_guid** : (uniqueidentifier)
  **referencing_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:docs.ftv_repoobject_reference_plantuml_entityreflist.adoc[]" as docs.ftv_RepoObject_Reference_PlantUml_EntityRefList << IF >> {
  --
}

entity "puml-link:dhw:sqldb:docs.objectrefcyclic.adoc[]" as docs.ObjectRefCyclic << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.objectrefcyclic_entitylist.adoc[]" as docs.ObjectRefCyclic_EntityList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_adoc.adoc[]" as docs.RepoObject_Adoc << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_adoc_t.adoc[]" as docs.RepoObject_Adoc_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_indexlist.adoc[]" as docs.RepoObject_IndexList << V >> {
  **RepoObject_guid** : (uniqueidentifier)
  **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_indexlist_t.adoc[]" as docs.RepoObject_IndexList_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml.adoc[]" as docs.RepoObject_Plantuml << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_entity.adoc[]" as docs.RepoObject_Plantuml_Entity << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_entity_t.adoc[]" as docs.RepoObject_Plantuml_Entity_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_fkreflist.adoc[]" as docs.RepoObject_PlantUml_FkRefList << V >> {
  **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_pumlentityfklist.adoc[]" as docs.RepoObject_PlantUml_PumlEntityFkList << V >> {
  **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_t.adoc[]" as docs.RepoObject_Plantuml_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.schema_entitylist.adoc[]" as docs.Schema_EntityList << V >> {
  - **RepoObject_schema_name** : (nvarchar(128))
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.schema_puml.adoc[]" as docs.Schema_puml << V >> {
  - **RepoSchema_guid** : (uniqueidentifier)
  **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.schema_pumlpartial_fkreflist.adoc[]" as docs.Schema_PumlPartial_FkRefList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.schema_ssasrelationlist.adoc[]" as docs.Schema_SsasRelationList << V >> {
  - **SchemaName** : (nvarchar(128))
  **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.ssas_pumlrelation.adoc[]" as docs.ssas_PumlRelation << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport.adoc[]" as docs.usp_AntoraExport << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_objectpartialscontent.adoc[]" as docs.usp_AntoraExport_ObjectPartialsContent << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_objectpuml.adoc[]" as docs.usp_AntoraExport_ObjectPuml << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_repoobject_adoc_t.adoc[]" as docs.usp_PERSIST_RepoObject_Adoc_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_repoobject_indexlist_t.adoc[]" as docs.usp_PERSIST_RepoObject_IndexList_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_repoobject_plantuml_entity_t.adoc[]" as docs.usp_PERSIST_RepoObject_Plantuml_Entity_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_repoobject_plantuml_t.adoc[]" as docs.usp_PERSIST_RepoObject_Plantuml_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.foreignkey_gross.adoc[]" as repo.ForeignKey_gross << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.foreignkey_indexes_union.adoc[]" as repo.ForeignKey_Indexes_union << V >> {
  **ForeignKey_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.foreignkey_indexes_union_t.adoc[]" as repo.ForeignKey_Indexes_union_T << U >> {
  **ForeignKey_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.foreignkey_ssas_indexes.adoc[]" as repo.ForeignKey_ssas_Indexes << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.foreignkey_ssas_indexpattern.adoc[]" as repo.ForeignKey_ssas_IndexPattern << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_related_fk_union.adoc[]" as repo.RepoObject_related_FK_union << V >> {
  **RepoObject_guid** : (uniqueidentifier)
  **included_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.usp_index_finish.adoc[]" as repo.usp_Index_finish << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_index_foreignkey.adoc[]" as repo.usp_Index_ForeignKey << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_index_inheritance.adoc[]" as repo.usp_index_inheritance << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_main.adoc[]" as repo.usp_main << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_persist_foreignkey_indexes_union_t.adoc[]" as repo.usp_PERSIST_ForeignKey_Indexes_union_T << P >> {
  --
}

docs.ftv_RepoObject_Reference_PlantUml_EntityRefList <.. docs.RepoObject_Plantuml
docs.ObjectRefCyclic_EntityList <.. docs.ObjectRefCyclic
docs.RepoObject_Adoc <.. docs.usp_PERSIST_RepoObject_Adoc_T
docs.RepoObject_Adoc <.. docs.RepoObject_Adoc_T
docs.REpoObject_Adoc_T <.. docs.usp_PERSIST_RepoObject_Adoc_T
docs.RepoObject_IndexList <.. docs.RepoObject_IndexList_T
docs.RepoObject_IndexList <.. docs.usp_PERSIST_RepoObject_IndexList_T
docs.RepoObject_IndexList_T <.. docs.usp_PERSIST_RepoObject_IndexList_T
docs.RepoObject_IndexList_T <.. docs.RepoObject_Plantuml_Entity
docs.RepoObject_IndexList_T <.. docs.RepoObject_Adoc
docs.RepoObject_Plantuml <.. docs.usp_PERSIST_RepoObject_Plantuml_T
docs.RepoObject_Plantuml <.. docs.RepoObject_Plantuml_T
docs.RepoObject_Plantuml_Entity <.. docs.usp_PERSIST_RepoObject_Plantuml_Entity_T
docs.RepoObject_Plantuml_Entity <.. docs.RepoObject_Plantuml_Entity_T
docs.RepoObject_Plantuml_Entity_T <.. docs.RepoObject_Adoc
docs.RepoObject_Plantuml_Entity_T <.. docs.usp_PERSIST_RepoObject_Plantuml_Entity_T
docs.RepoObject_Plantuml_Entity_T <.. docs.ftv_RepoObject_Reference_PlantUml_EntityRefList
docs.RepoObject_Plantuml_Entity_T <.. docs.RepoObject_PlantUml_PumlEntityFkList
docs.RepoObject_Plantuml_Entity_T <.. docs.ObjectRefCyclic_EntityList
docs.RepoObject_Plantuml_Entity_T <.. docs.Schema_EntityList
docs.RepoObject_PlantUml_FkRefList <.. docs.RepoObject_Plantuml
docs.RepoObject_PlantUml_PumlEntityFkList <.. docs.RepoObject_Plantuml
docs.RepoObject_Plantuml_T <.. docs.RepoObject_Adoc
docs.RepoObject_Plantuml_T <.. docs.usp_PERSIST_RepoObject_Plantuml_T
docs.Schema_EntityList <.. docs.Schema_puml
docs.Schema_puml <.. docs.AntoraNavListPage_by_schema
docs.Schema_PumlPartial_FkRefList <.. docs.Schema_puml
docs.Schema_SsasRelationList <.. docs.Schema_puml
docs.ssas_PumlRelation <.. docs.Schema_SsasRelationList
docs.usp_AntoraExport_ObjectPartialsContent <.. docs.usp_AntoraExport
docs.usp_AntoraExport_ObjectPuml <.. docs.usp_AntoraExport
docs.usp_PERSIST_RepoObject_Adoc_T <.. docs.usp_AntoraExport_ObjectPartialsContent
docs.usp_PERSIST_RepoObject_IndexList_T <.. docs.usp_AntoraExport_ObjectPartialsContent
docs.usp_PERSIST_RepoObject_Plantuml_Entity_T <.. docs.usp_AntoraExport_ObjectPuml
docs.usp_PERSIST_RepoObject_Plantuml_T <.. docs.usp_AntoraExport_ObjectPuml
repo.ForeignKey_gross <.. docs.RepoObject_IndexList
repo.ForeignKey_Indexes_union <.. repo.usp_PERSIST_ForeignKey_Indexes_union_T
repo.ForeignKey_Indexes_union <.. repo.ForeignKey_Indexes_union_T
repo.ForeignKey_Indexes_union_T <.. repo.usp_PERSIST_ForeignKey_Indexes_union_T
repo.ForeignKey_Indexes_union_T <.. docs.Schema_PumlPartial_FkRefList
repo.ForeignKey_Indexes_union_T <.. docs.ForeignKey_RelationScript
repo.ForeignKey_Indexes_union_T <.. repo.ForeignKey_gross
repo.ForeignKey_Indexes_union_T <.. repo.RepoObject_related_FK_union
repo.ForeignKey_Indexes_union_T <.. docs.RepoObject_PlantUml_FkRefList
repo.ForeignKey_Indexes_union_T <.. repo.usp_Index_finish
repo.ForeignKey_ssas_Indexes <.. repo.ForeignKey_Indexes_union
repo.ForeignKey_ssas_IndexPattern <.. docs.ssas_PumlRelation
repo.ForeignKey_ssas_IndexPattern <.. repo.ForeignKey_ssas_Indexes
repo.RepoObject_related_FK_union <.. docs.RepoObject_PlantUml_FkRefList
repo.RepoObject_related_FK_union <.. docs.RepoObject_PlantUml_PumlEntityFkList
repo.usp_Index_finish <.. repo.usp_Index_ForeignKey
repo.usp_Index_finish <.. repo.usp_index_inheritance
repo.usp_Index_ForeignKey <.. repo.usp_main
repo.usp_index_inheritance <.. repo.usp_main
repo.usp_PERSIST_ForeignKey_Indexes_union_T <.. repo.usp_Index_ForeignKey

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_0_30_objectref[]

=== PlantUML 1 1 ColumnRef

// tag::puml_entity_1_1_colref[]
[plantuml, entity_1_1_colref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:docs.ssas_pumlrelation.adoc[]" as docs.ssas_PumlRelation << V >> {
  delete_referential_action : (tinyint)
  ForeignKey_fullname : (nvarchar(517))
  - ForeignKey_guid : (uniqueidentifier)
  ForeignKey_name : (nvarchar(263))
  - PumlRelation : (nvarchar(max))
  referenced_ColumnName : (nvarchar(128))
  referenced_IndexPatternColumnDatatype : (nvarchar(500))
  referenced_IndexPatternColumnGuid : (varchar(36))
  referenced_IndexPatternColumnName : (nvarchar(128))
  referenced_ObjectName : (nvarchar(128))
  referenced_RepoObject_fullname : (nvarchar(517))
  referenced_RepoObject_fullname2 : (nvarchar(257))
  referenced_RepoObject_guid : (uniqueidentifier)
  referencing_ColumnName : (nvarchar(128))
  referencing_IndexPatternColumnDatatype : (nvarchar(500))
  referencing_IndexPatternColumnGuid : (varchar(36))
  referencing_IndexPatternColumnName : (nvarchar(128))
  referencing_ObjectName : (nvarchar(128))
  referencing_RepoObject_fullname : (nvarchar(517))
  referencing_RepoObject_fullname2 : (nvarchar(257))
  referencing_RepoObject_guid : (uniqueidentifier)
  relationships_crossFilteringBehavior : (nvarchar(500))
  relationships_fromCardinality : (nvarchar(500))
  - relationships_isActive : (bit)
  relationships_name : (nvarchar(500))
  relationships_toCardinality : (nvarchar(500))
  - SchemaName : (nvarchar(128))
  update_referential_action : (tinyint)
  --
}

entity "puml-link:dhw:sqldb:repo.foreignkey_ssas_indexes.adoc[]" as repo.ForeignKey_ssas_Indexes << V >> {
  delete_referential_action : (tinyint)
  ForeignKey_fullname : (nvarchar(517))
  - ForeignKey_guid : (uniqueidentifier)
  ForeignKey_name : (nvarchar(263))
  - is_MatchingDatatypePattern : (int)
  referenced_index_guid : (uniqueidentifier)
  referenced_index_name : (nvarchar(450))
  referenced_IndexPatternColumnDatatype : (nvarchar(500))
  referenced_IndexPatternColumnName : (nvarchar(128))
  referenced_RepoObject_fullname : (nvarchar(517))
  referenced_RepoObject_fullname2 : (nvarchar(257))
  referenced_RepoObject_guid : (uniqueidentifier)
  referenced_SysObject_name : (nvarchar(128))
  - referenced_SysObject_schema_name : (nvarchar(128))
  referencing_index_guid : (uniqueidentifier)
  referencing_index_name : (nvarchar(450))
  referencing_IndexPatternColumnDatatype : (nvarchar(500))
  referencing_IndexPatternColumnName : (nvarchar(128))
  referencing_RepoObject_fullname : (nvarchar(517))
  referencing_RepoObject_fullname2 : (nvarchar(257))
  referencing_RepoObject_guid : (uniqueidentifier)
  referencing_SysObject_name : (nvarchar(128))
  - referencing_SysObject_schema_name : (nvarchar(128))
  update_referential_action : (tinyint)
  --
}

entity "puml-link:dhw:sqldb:repo.foreignkey_ssas_indexpattern.adoc[]" as repo.ForeignKey_ssas_IndexPattern << V >> {
  - databasename : (nvarchar(128))
  delete_referential_action : (tinyint)
  ForeignKey_fullname : (nvarchar(517))
  - ForeignKey_guid : (uniqueidentifier)
  ForeignKey_name : (nvarchar(263))
  referenced_ColumnName : (nvarchar(128))
  referenced_IndexPatternColumnDatatype : (nvarchar(500))
  referenced_IndexPatternColumnGuid : (varchar(36))
  referenced_IndexPatternColumnName : (nvarchar(128))
  - referenced_IsKey : (bit)
  - referenced_IsNullable : (bit)
  referenced_ObjectName : (nvarchar(128))
  referenced_RepoObject_fullname : (nvarchar(517))
  referenced_RepoObject_fullname2 : (nvarchar(257))
  referenced_RepoObject_guid : (uniqueidentifier)
  referencing_ColumnName : (nvarchar(128))
  referencing_IndexPatternColumnDatatype : (nvarchar(500))
  referencing_IndexPatternColumnGuid : (varchar(36))
  referencing_IndexPatternColumnName : (nvarchar(128))
  - referencing_IsKey : (bit)
  - referencing_IsNullable : (bit)
  referencing_ObjectName : (nvarchar(128))
  referencing_RepoObject_fullname : (nvarchar(517))
  referencing_RepoObject_fullname2 : (nvarchar(257))
  referencing_RepoObject_guid : (uniqueidentifier)
  relationships_crossFilteringBehavior : (nvarchar(500))
  relationships_fromCardinality : (nvarchar(500))
  - relationships_isActive : (bit)
  relationships_name : (nvarchar(500))
  relationships_toCardinality : (nvarchar(500))
  update_referential_action : (tinyint)
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31_tables_t.adoc[]" as ssas.model_json_31_tables_T << U >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  - RepoObject_guid : (uniqueidentifier)
  tables_annotations_ja : (nvarchar(max))
  tables_columns_ja : (nvarchar(max))
  tables_dataCategory : (nvarchar(500))
  tables_description : (nvarchar(max))
  tables_description_ja : (nvarchar(max))
  tables_hierarchies_ja : (nvarchar(max))
  tables_isHidden : (bit)
  tables_measures_ja : (nvarchar(max))
  tables_partitions_ja : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_311_tables_columns_t.adoc[]" as ssas.model_json_311_tables_columns_T << U >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  - **tables_columns_name** : (nvarchar(128))
  - RepoObject_guid : (uniqueidentifier)
  - RepoObjectColumn_guid : (uniqueidentifier)
  tables_columns_dataType : (nvarchar(500))
  tables_columns_description : (nvarchar(max))
  tables_columns_description_ja : (nvarchar(max))
  tables_columns_displayFolder : (nvarchar(500))
  tables_columns_expression : (nvarchar(max))
  tables_columns_expression_ja : (nvarchar(max))
  tables_columns_formatString : (nvarchar(500))
  tables_columns_isDataTypeInferred : (bit)
  tables_columns_isHidden : (bit)
  tables_columns_isKey : (bit)
  tables_columns_isNameInferred : (bit)
  tables_columns_isNullable : (bit)
  tables_columns_isUnique : (bit)
  tables_columns_keepUniqueRows : (bit)
  tables_columns_sortByColumn : (nvarchar(500))
  tables_columns_sourceColumn : (nvarchar(500))
  tables_columns_sourceProviderType : (nvarchar(500))
  tables_columns_summarizeBy : (nvarchar(500))
  tables_columns_type : (nvarchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_32_relationships_t.adoc[]" as ssas.model_json_32_relationships_T << U >> {
  - **ForeignKey_guid** : (uniqueidentifier)
  - databasename : (nvarchar(128))
  relationships_crossFilteringBehavior : (nvarchar(500))
  relationships_fromCardinality : (nvarchar(500))
  relationships_fromColumn : (nvarchar(500))
  relationships_fromTable : (nvarchar(500))
  relationships_isActive : (bit)
  relationships_name : (nvarchar(500))
  relationships_toCardinality : (nvarchar(500))
  relationships_toColumn : (nvarchar(500))
  relationships_toTable : (nvarchar(500))
  --
}

repo.ForeignKey_ssas_IndexPattern <.. repo.ForeignKey_ssas_Indexes
repo.ForeignKey_ssas_IndexPattern <.. docs.ssas_PumlRelation
ssas.model_json_31_tables_T <.. repo.ForeignKey_ssas_IndexPattern
ssas.model_json_311_tables_columns_T <.. repo.ForeignKey_ssas_IndexPattern
ssas.model_json_32_relationships_T <.. repo.ForeignKey_ssas_IndexPattern
"repo.ForeignKey_ssas_IndexPattern::databasename" <-- "repo.ForeignKey_ssas_Indexes::referenced_SysObject_schema_name"
"repo.ForeignKey_ssas_IndexPattern::databasename" <-- "repo.ForeignKey_ssas_Indexes::referencing_SysObject_schema_name"
"repo.ForeignKey_ssas_IndexPattern::databasename" <-- "docs.ssas_PumlRelation::SchemaName"
"repo.ForeignKey_ssas_IndexPattern::delete_referential_action" <-- "docs.ssas_PumlRelation::delete_referential_action"
"repo.ForeignKey_ssas_IndexPattern::delete_referential_action" <-- "repo.ForeignKey_ssas_Indexes::delete_referential_action"
"repo.ForeignKey_ssas_IndexPattern::ForeignKey_fullname" <-- "docs.ssas_PumlRelation::ForeignKey_fullname"
"repo.ForeignKey_ssas_IndexPattern::ForeignKey_fullname" <-- "repo.ForeignKey_ssas_Indexes::ForeignKey_fullname"
"repo.ForeignKey_ssas_IndexPattern::ForeignKey_guid" <-- "repo.ForeignKey_ssas_Indexes::ForeignKey_guid"
"repo.ForeignKey_ssas_IndexPattern::ForeignKey_guid" <-- "docs.ssas_PumlRelation::ForeignKey_guid"
"repo.ForeignKey_ssas_IndexPattern::ForeignKey_name" <-- "docs.ssas_PumlRelation::ForeignKey_name"
"repo.ForeignKey_ssas_IndexPattern::ForeignKey_name" <-- "repo.ForeignKey_ssas_Indexes::ForeignKey_name"
"repo.ForeignKey_ssas_IndexPattern::referenced_ColumnName" <-- "docs.ssas_PumlRelation::referenced_ColumnName"
"repo.ForeignKey_ssas_IndexPattern::referenced_IndexPatternColumnDatatype" <-- "docs.ssas_PumlRelation::referenced_IndexPatternColumnDatatype"
"repo.ForeignKey_ssas_IndexPattern::referenced_IndexPatternColumnDatatype" <-- "repo.ForeignKey_ssas_Indexes::referenced_IndexPatternColumnDatatype"
"repo.ForeignKey_ssas_IndexPattern::referenced_IndexPatternColumnGuid" <-- "docs.ssas_PumlRelation::referenced_IndexPatternColumnGuid"
"repo.ForeignKey_ssas_IndexPattern::referenced_IndexPatternColumnName" <-- "docs.ssas_PumlRelation::referenced_IndexPatternColumnName"
"repo.ForeignKey_ssas_IndexPattern::referenced_IndexPatternColumnName" <-- "repo.ForeignKey_ssas_Indexes::referenced_IndexPatternColumnName"
"repo.ForeignKey_ssas_IndexPattern::referenced_ObjectName" <-- "repo.ForeignKey_ssas_Indexes::referenced_SysObject_name"
"repo.ForeignKey_ssas_IndexPattern::referenced_ObjectName" <-- "docs.ssas_PumlRelation::referenced_ObjectName"
"repo.ForeignKey_ssas_IndexPattern::referenced_RepoObject_fullname" <-- "docs.ssas_PumlRelation::referenced_RepoObject_fullname"
"repo.ForeignKey_ssas_IndexPattern::referenced_RepoObject_fullname" <-- "repo.ForeignKey_ssas_Indexes::referenced_RepoObject_fullname"
"repo.ForeignKey_ssas_IndexPattern::referenced_RepoObject_fullname2" <-- "repo.ForeignKey_ssas_Indexes::referenced_RepoObject_fullname2"
"repo.ForeignKey_ssas_IndexPattern::referenced_RepoObject_fullname2" <-- "docs.ssas_PumlRelation::referenced_RepoObject_fullname2"
"repo.ForeignKey_ssas_IndexPattern::referenced_RepoObject_guid" <-- "docs.ssas_PumlRelation::referenced_RepoObject_guid"
"repo.ForeignKey_ssas_IndexPattern::referenced_RepoObject_guid" <-- "repo.ForeignKey_ssas_Indexes::referenced_RepoObject_guid"
"repo.ForeignKey_ssas_IndexPattern::referencing_ColumnName" <-- "docs.ssas_PumlRelation::referencing_ColumnName"
"repo.ForeignKey_ssas_IndexPattern::referencing_IndexPatternColumnDatatype" <-- "docs.ssas_PumlRelation::referencing_IndexPatternColumnDatatype"
"repo.ForeignKey_ssas_IndexPattern::referencing_IndexPatternColumnDatatype" <-- "repo.ForeignKey_ssas_Indexes::referencing_IndexPatternColumnDatatype"
"repo.ForeignKey_ssas_IndexPattern::referencing_IndexPatternColumnGuid" <-- "docs.ssas_PumlRelation::referencing_IndexPatternColumnGuid"
"repo.ForeignKey_ssas_IndexPattern::referencing_IndexPatternColumnName" <-- "docs.ssas_PumlRelation::referencing_IndexPatternColumnName"
"repo.ForeignKey_ssas_IndexPattern::referencing_IndexPatternColumnName" <-- "repo.ForeignKey_ssas_Indexes::referencing_IndexPatternColumnName"
"repo.ForeignKey_ssas_IndexPattern::referencing_ObjectName" <-- "repo.ForeignKey_ssas_Indexes::referencing_SysObject_name"
"repo.ForeignKey_ssas_IndexPattern::referencing_ObjectName" <-- "docs.ssas_PumlRelation::referencing_ObjectName"
"repo.ForeignKey_ssas_IndexPattern::referencing_RepoObject_fullname" <-- "docs.ssas_PumlRelation::referencing_RepoObject_fullname"
"repo.ForeignKey_ssas_IndexPattern::referencing_RepoObject_fullname" <-- "repo.ForeignKey_ssas_Indexes::referencing_RepoObject_fullname"
"repo.ForeignKey_ssas_IndexPattern::referencing_RepoObject_fullname2" <-- "repo.ForeignKey_ssas_Indexes::referencing_RepoObject_fullname2"
"repo.ForeignKey_ssas_IndexPattern::referencing_RepoObject_fullname2" <-- "docs.ssas_PumlRelation::referencing_RepoObject_fullname2"
"repo.ForeignKey_ssas_IndexPattern::referencing_RepoObject_guid" <-- "repo.ForeignKey_ssas_Indexes::referencing_RepoObject_guid"
"repo.ForeignKey_ssas_IndexPattern::referencing_RepoObject_guid" <-- "docs.ssas_PumlRelation::referencing_RepoObject_guid"
"repo.ForeignKey_ssas_IndexPattern::relationships_crossFilteringBehavior" <-- "docs.ssas_PumlRelation::relationships_crossFilteringBehavior"
"repo.ForeignKey_ssas_IndexPattern::relationships_fromCardinality" <-- "docs.ssas_PumlRelation::relationships_fromCardinality"
"repo.ForeignKey_ssas_IndexPattern::relationships_isActive" <-- "docs.ssas_PumlRelation::relationships_isActive"
"repo.ForeignKey_ssas_IndexPattern::relationships_name" <-- "docs.ssas_PumlRelation::relationships_name"
"repo.ForeignKey_ssas_IndexPattern::relationships_toCardinality" <-- "docs.ssas_PumlRelation::relationships_toCardinality"
"repo.ForeignKey_ssas_IndexPattern::update_referential_action" <-- "repo.ForeignKey_ssas_Indexes::update_referential_action"
"repo.ForeignKey_ssas_IndexPattern::update_referential_action" <-- "docs.ssas_PumlRelation::update_referential_action"
"ssas.model_json_31_tables_T::RepoObject_guid" <-- "repo.ForeignKey_ssas_IndexPattern::referenced_RepoObject_guid"
"ssas.model_json_31_tables_T::RepoObject_guid" <-- "repo.ForeignKey_ssas_IndexPattern::referencing_RepoObject_guid"
"ssas.model_json_31_tables_T::tables_name" <-- "repo.ForeignKey_ssas_IndexPattern::referenced_ObjectName"
"ssas.model_json_31_tables_T::tables_name" <-- "repo.ForeignKey_ssas_IndexPattern::referencing_ObjectName"
"ssas.model_json_311_tables_columns_T::tables_columns_dataType" <-- "repo.ForeignKey_ssas_IndexPattern::referencing_IndexPatternColumnDatatype"
"ssas.model_json_311_tables_columns_T::tables_columns_dataType" <-- "repo.ForeignKey_ssas_IndexPattern::referenced_IndexPatternColumnDatatype"
"ssas.model_json_311_tables_columns_T::tables_columns_name" <-- "repo.ForeignKey_ssas_IndexPattern::referenced_ColumnName"
"ssas.model_json_311_tables_columns_T::tables_columns_name" <-- "repo.ForeignKey_ssas_IndexPattern::referencing_ColumnName"
"ssas.model_json_311_tables_columns_T::tables_columns_name" <-- "repo.ForeignKey_ssas_IndexPattern::referencing_IndexPatternColumnName"
"ssas.model_json_311_tables_columns_T::tables_columns_name" <-- "repo.ForeignKey_ssas_IndexPattern::referenced_IndexPatternColumnName"
"ssas.model_json_32_relationships_T::databasename" <-- "repo.ForeignKey_ssas_IndexPattern::databasename"
"ssas.model_json_32_relationships_T::ForeignKey_guid" <-- "repo.ForeignKey_ssas_IndexPattern::ForeignKey_guid"
"ssas.model_json_32_relationships_T::relationships_crossFilteringBehavior" <-- "repo.ForeignKey_ssas_IndexPattern::relationships_crossFilteringBehavior"
"ssas.model_json_32_relationships_T::relationships_fromCardinality" <-- "repo.ForeignKey_ssas_IndexPattern::relationships_fromCardinality"
"ssas.model_json_32_relationships_T::relationships_isActive" <-- "repo.ForeignKey_ssas_IndexPattern::relationships_isActive"
"ssas.model_json_32_relationships_T::relationships_name" <-- "repo.ForeignKey_ssas_IndexPattern::relationships_name"
"ssas.model_json_32_relationships_T::relationships_toCardinality" <-- "repo.ForeignKey_ssas_IndexPattern::relationships_toCardinality"

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_colref[]


== sql_modules_definition

// tag::sql_modules_definition[]
[%collapsible]
=======
[source,sql,numbered,indent=0]
----

CREATE View repo.ForeignKey_ssas_IndexPattern
As
Select
    fk.ForeignKey_guid
  , ForeignKey_name                        = 'FK_' + tFrom.tables_name + '_TO_' + tTo.tables_name
  , ForeignKey_fullname                    = QuoteName ( fk.databasename ) + '.'
                                             + QuoteName ( 'FK_' + tFrom.tables_name + '_TO_' + tTo.tables_name )
  , referenced_IndexPatternColumnName      = colTo.tables_columns_name
  , referenced_IndexPatternColumnGuid      = Cast(colTo.RepoObjectColumn_guid As Varchar(36))
  , referenced_RepoObject_guid             = tTo.RepoObject_guid
  , referencing_IndexPatternColumnName     = colFrom.tables_columns_name
  , referencing_IndexPatternColumnGuid     = Cast(colFrom.RepoObjectColumn_guid As Varchar(36))
  , referencing_RepoObject_guid            = tFrom.RepoObject_guid
  , delete_referential_action              = Cast(Null As TinyInt)
  , update_referential_action              = Cast(Null As TinyInt)
  --extra columns only in ssas
  , fk.databasename
  , fk.relationships_name
  , relationships_isActive                 = IsNull ( fk.relationships_isActive, 1 )
  --, fk.Type
  , fk.relationships_crossFilteringBehavior
  --, fk.JoinOnDateBehavior
  --, fk.RelyOnReferentialIntegrity
  , fk.relationships_fromCardinality
  , fk.relationships_toCardinality
  --, fk.SecurityFilteringBehavior
  , referenced_ObjectName                  = tTo.tables_name
  , referenced_ColumnName                  = colTo.tables_columns_name
  , referenced_IndexPatternColumnDatatype  = colTo.tables_columns_dataType
  , referenced_RepoObject_fullname         = QuoteName ( fk.databasename ) + '.' + QuoteName ( tTo.tables_name )
  , referenced_RepoObject_fullname2        = fk.databasename + '.' + tTo.tables_name
  , referenced_IsKey                       = IsNull ( colTo.tables_columns_isKey, 0 )
  , referenced_IsNullable                  = IsNull ( colTo.tables_columns_isNullable, 1 )
  , referencing_ObjectName                 = tFrom.tables_name
  , referencing_ColumnName                 = colFrom.tables_columns_name
  , referencing_IndexPatternColumnDatatype = colFrom.tables_columns_dataType
  , referencing_RepoObject_fullname        = QuoteName ( fk.databasename ) + '.' + QuoteName ( tFrom.tables_name )
  , referencing_RepoObject_fullname2       = fk.databasename + '.' + tFrom.tables_name
  , referencing_IsKey                      = IsNull ( colFrom.tables_columns_isKey, 0 )
  , referencing_IsNullable                 = IsNull ( colFrom.tables_columns_isNullable, 1 )
From
    ssas.model_json_32_relationships_T       As fk
    Left Join
        ssas.model_json_311_tables_columns_T As colFrom
            On
            colFrom.databasename            = fk.databasename
            And colFrom.tables_name         = fk.relationships_fromTable
            And colFrom.tables_columns_name = fk.relationships_fromColumn

    Left Join
        ssas.model_json_31_tables_T          As tFrom
            On
            tFrom.databasename              = colFrom.databasename
            And tFrom.tables_name           = colFrom.tables_name

    --Left Join
    --    configT.SsasDmv_ExplicitDataType As dtFrom
    --        On
    --        dtFrom.ExplicitDataType = colFrom.ExplicitDataType

    Left Join
        ssas.model_json_311_tables_columns_T As colTo
            On
            colTo.databasename              = fk.databasename
            And colTo.tables_name           = fk.relationships_toTable
            And colTo.tables_columns_name   = fk.relationships_toColumn

    Left Join
        ssas.model_json_31_tables_T          As tTo
            On
            tTo.databasename                = colTo.databasename
            And tTo.tables_name             = colTo.tables_name

--Left Join
--    configT.SsasDmv_ExplicitDataType As dtTo
--        On
--        dtTo.ExplicitDataType   = colTo.ExplicitDataType

----
=======
// end::sql_modules_definition[]


