// tag::HeaderFullDisplayName[]
= repo.usp_main - P
// end::HeaderFullDisplayName[]

== existing_properties

// tag::existing_properties[]

:ExistsProperty--adocuspsteps:
:ExistsProperty--antorareferencedlist:
:ExistsProperty--description:
:ExistsProperty--exampleusage:
:ExistsProperty--is_repo_managed:
:ExistsProperty--is_ssas:
:ExistsProperty--ms_description:
:ExistsProperty--referencedobjectlist:
:ExistsProperty--uspexamples:
:ExistsProperty--uspgenerator_usp_id:
:ExistsProperty--sql_modules_definition:
:ExistsProperty--AntoraParameterList:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
6BCBC49C-3862-EB11-84DC-A81E8446D5B0
// end::RepoObject_guid[]

== RepoObject_FullDisplayName2

// tag::RepoObject_FullDisplayName2[]
repo.usp_main
// end::RepoObject_FullDisplayName2[]

== SysObject_type

// tag::SysObject_type[]
P 
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
stored procedure
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
462624691
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2022-01-23 17:32:30
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]

// end::AntoraColumnDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]

// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

// end::AntoraIndexList[]

== AntoraMeasureDetails

// tag::AntoraMeasureDetails[]

// end::AntoraMeasureDetails[]

== AntoraMeasureDescriptions



== AntoraParameterList

// tag::AntoraParameterList[]
* @execution_instance_guid (uniqueidentifier)
* @ssis_execution_id (bigint)
* @sub_execution_id (int)
* @parent_execution_log_id (bigint)
// end::AntoraParameterList[]

== AntoraXrefCulturesList

// tag::AntoraXrefCulturesList[]
* xref:dhw:sqldb:repo.usp_main.adoc[] - 
// end::AntoraXrefCulturesList[]

== cultures_count

// tag::cultures_count[]
1
// end::cultures_count[]

== Other tags

source: property.RepoObjectProperty_cross As rop_cross


=== additional_reference_csv

// tag::additional_reference_csv[]

// end::additional_reference_csv[]


=== AdocUspSteps

// tag::adocuspsteps[]
.Steps in [repo].[usp_main]
[cols="d,15a,d"]
|===
|Number|Name (Action, Source, Target)|Parent

|150
|
*EXEC [config].[usp_init_parameter]*



.Statement
[%collapsible]
=====
[source,sql,numbered]
----
EXEC [config].[usp_init_parameter]
----
=====

|


|210
|
*(select config.fs_get_parameter_value ( 'sync enable', 'dwh' )) = 1*

* `IF (select config.fs_get_parameter_value ( 'sync enable', 'dwh' )) = 1`


.Statement
[%collapsible]
=====
[source,sql,numbered]
----
(select config.fs_get_parameter_value ( 'sync enable', 'dwh' )) = 1
----
=====

|


|211
|
*[repo].[usp_sync_guid]*

* `EXEC [repo].[usp_sync_guid]`


.Statement
[%collapsible]
=====
[source,sql,numbered]
----
[repo].[usp_sync_guid]
----
=====

|210


|220
|
*(select config.fs_get_parameter_value ( 'sync enable', 'ssas' )) = 1*

* `IF (select config.fs_get_parameter_value ( 'sync enable', 'ssas' )) = 1`


.Statement
[%collapsible]
=====
[source,sql,numbered]
----
(select config.fs_get_parameter_value ( 'sync enable', 'ssas' )) = 1
----
=====

|


|221
|
*[repo].[usp_sync_guid_ssas]*

* `EXEC [repo].[usp_sync_guid_ssas]`


.Statement
[%collapsible]
=====
[source,sql,numbered]
----
[repo].[usp_sync_guid_ssas]
----
=====

|220


|230
|
*(select config.fs_get_parameter_value ( 'sync enable', 'ssas' )) = 1 AND ( 'sync enable', 'dwh' )) = 0 *

* `IF (select config.fs_get_parameter_value ( 'sync enable', 'ssas' )) = 1
AND
(select config.fs_get_parameter_value ( 'sync enable', 'dwh' )) = 0`


.Statement
[%collapsible]
=====
[source,sql,numbered]
----
(select config.fs_get_parameter_value ( 'sync enable', 'ssas' )) = 1
AND
(select config.fs_get_parameter_value ( 'sync enable', 'dwh' )) = 0
----
=====

|


|231
|
*delete where is_ssas = 0 and is_external = 0*

* d
* [repo].[RepoObject]
* [repo].[RepoObject]


.Statement
[%collapsible]
=====
[source,sql,numbered]
----
Delete From
repo.RepoObject
Where
    is_ssas         = 0
    And is_external = 0
----
=====

|230


|235
|
*[ssas].[usp_PERSIST_RepoObjectColumn_translation_T]*

* `EXEC [ssas].[usp_PERSIST_RepoObjectColumn_translation_T]`


it is required in [docs].[RepoObject_ColumnList]

.Statement
[%collapsible]
=====
[source,sql,numbered]
----
[ssas].[usp_PERSIST_RepoObjectColumn_translation_T]
----
=====

|


|240
|
*[reference].[usp_additional_Reference]*

* `EXEC [reference].[usp_additional_Reference]`


.Statement
[%collapsible]
=====
[source,sql,numbered]
----
[reference].[usp_additional_Reference]
----
=====

|


|250
|
*[reference].[usp_PERSIST_RepoObject_reference_T]*

* `EXEC [reference].[usp_PERSIST_RepoObject_reference_T]`


.Statement
[%collapsible]
=====
[source,sql,numbered]
----
[reference].[usp_PERSIST_RepoObject_reference_T]
----
=====

|


|261
|
*[reference].[RepoObject_reference_T] set referenced_is_PersistenceSource, referencing_is_PersistenceTarget from [reference].[RepoObject_reference_persistence] *

* [reference].[RepoObject_reference_persistence]
* [reference].[RepoObject_reference_T]


.Statement
[%collapsible]
=====
[source,sql,numbered]
----
Update
    T1
Set
    referenced_is_PersistenceSource = 1
  , referencing_is_PersistenceTarget = 1
From
    reference.RepoObject_reference_T               As T1
    Inner Join
        reference.RepoObject_reference_persistence As T2
            On
            T1.referenced_RepoObject_guid      = T2.referenced_RepoObject_guid
            And T1.referencing_RepoObject_guid = T2.referencing_RepoObject_guid;
----
=====

|


|262
|
*[reference].[RepoObject_reference_T] set referenced_is_PersistenceSource, referencing_is_PersistenceTarget, is_ReversePersistenceViaView from [reference].[RepoObject_reference_persistence_target_as_source]*

* [reference].[RepoObject_reference_persistence_target_as_source]
* [reference].[RepoObject_reference_T]


.Statement
[%collapsible]
=====
[source,sql,numbered]
----
Update
    T1
Set
    referenced_is_PersistenceSource = 1
  , referencing_is_PersistenceTarget = 1
  , is_ReversePersistenceViaView = 1
From
    reference.RepoObject_reference_T                                    As T1
    Inner Join
        [reference].[RepoObject_reference_persistence_target_as_source] As T2
            On
            T1.referenced_RepoObject_guid      = T2.referenced_RepoObject_guid
            And T1.referencing_RepoObject_guid = T2.referencing_RepoObject_guid;
----
=====

|


|263
|
*[reference].[RepoObject_reference_T] set referenced_is_PersistenceTarget, referencing_is_PersistenceUspTargetRef*

* [repo].[RepoObject]
* [reference].[RepoObject_reference_T]


.Statement
[%collapsible]
=====
[source,sql,numbered]
----
Update
    T1
Set
    referenced_is_PersistenceTarget = 1
  , referencing_is_PersistenceUspTargetRef = 1
From
    reference.RepoObject_reference_T As T1
    Inner Join
        repo.RepoObject              As T2
            On
            T1.referenced_RepoObject_guid = T2.RepoObject_guid
            And T1.referencing_fullname2  = T2.usp_persistence_fullname2;
----
=====

|


|280
|
*[reference].[usp_RepoObject_ReferenceTree_insert]*

* `EXEC [reference].[usp_RepoObject_ReferenceTree_insert]`


.Statement
[%collapsible]
=====
[source,sql,numbered]
----
[reference].[usp_RepoObject_ReferenceTree_insert]
----
=====

|


|290
|
*[reference].[usp_PERSIST_RepoObjectColumn_reference_T]*

* `EXEC [reference].[usp_PERSIST_RepoObjectColumn_reference_T]`


.Statement
[%collapsible]
=====
[source,sql,numbered]
----
[reference].[usp_PERSIST_RepoObjectColumn_reference_T]
----
=====

|


|292
|
*[repo].[usp_PERSIST_RepoObject_sat2_T]*

* `EXEC [repo].[usp_PERSIST_RepoObject_sat2_T]`


.Statement
[%collapsible]
=====
[source,sql,numbered]
----
[repo].[usp_PERSIST_RepoObject_sat2_T]
----
=====

|


|300
|
*(select [config].[fs_get_parameter_value]('main enable usp_RepoObjectSource_FirstResultSet', DEFAULT)) = 1*

* `IF (select [config].[fs_get_parameter_value]('main enable usp_RepoObjectSource_FirstResultSet', DEFAULT)) = 1`


.Statement
[%collapsible]
=====
[source,sql,numbered]
----
(select [config].[fs_get_parameter_value]('main enable usp_RepoObjectSource_FirstResultSet', DEFAULT)) = 1
----
=====

|


|310
|
*[reference].[usp_RepoObjectSource_FirstResultSet]*

* `EXEC [reference].[usp_RepoObjectSource_FirstResultSet]
--This can take a very long time`


.Statement
[%collapsible]
=====
[source,sql,numbered]
----
[reference].[usp_RepoObjectSource_FirstResultSet]
--This can take a very long time
----
=====

|300


|400
|
*(select [config].[fs_get_parameter_value]('main enable usp_RepoObject_update_SysObjectQueryPlan', DEFAULT)) = 1*

* `IF (select [config].[fs_get_parameter_value]('main enable usp_RepoObject_update_SysObjectQueryPlan', DEFAULT)) = 1`


.Statement
[%collapsible]
=====
[source,sql,numbered]
----
(select [config].[fs_get_parameter_value]('main enable usp_RepoObject_update_SysObjectQueryPlan', DEFAULT)) = 1
----
=====

|


|410
|
*[reference].[usp_RepoObject_update_SysObjectQueryPlan]*

* `EXEC [reference].[usp_RepoObject_update_SysObjectQueryPlan]`


This can take a very long time

.Statement
[%collapsible]
=====
[source,sql,numbered]
----
[reference].[usp_RepoObject_update_SysObjectQueryPlan]
----
=====

|400


|500
|
*(select [config].[fs_get_parameter_value]('main enable usp_RepoObjectSource_QueryPlan', DEFAULT)) = 1*

* `IF (select [config].[fs_get_parameter_value]('main enable usp_RepoObjectSource_QueryPlan', DEFAULT)) = 1`


.Statement
[%collapsible]
=====
[source,sql,numbered]
----
(select [config].[fs_get_parameter_value]('main enable usp_RepoObjectSource_QueryPlan', DEFAULT)) = 1
----
=====

|


|510
|
*[reference].[usp_RepoObjectSource_QueryPlan]
--This can take a very long time*

* `EXEC [reference].[usp_RepoObjectSource_QueryPlan]`


This can take a very long time

.Statement
[%collapsible]
=====
[source,sql,numbered]
----
[reference].[usp_RepoObjectSource_QueryPlan]
----
=====

|500


|610
|
*[reference].[usp_update_Referencing_Count]*

* `EXEC [reference].[usp_update_Referencing_Count]`


.Statement
[%collapsible]
=====
[source,sql,numbered]
----
[reference].[usp_update_Referencing_Count]
----
=====

|


|710
|
*[repo].[usp_index_inheritance]*

* `EXEC [repo].[usp_index_inheritance]`


todo:

should or could be executed several times until no new indexes are inherited

.Statement
[%collapsible]
=====
[source,sql,numbered]
----
[repo].[usp_index_inheritance]
----
=====

|


|720
|
*[repo].[usp_Index_ForeignKey]*

* `EXEC [repo].[usp_Index_ForeignKey]`


.Statement
[%collapsible]
=====
[source,sql,numbered]
----
[repo].[usp_Index_ForeignKey]
----
=====

|


|730
|
*[property].[usp_PERSIST_PropertyName_Measure_T]*

* `EXEC [property].[usp_PERSIST_PropertyName_Measure_T]`


.Statement
[%collapsible]
=====
[source,sql,numbered]
----
[property].[usp_PERSIST_PropertyName_Measure_T]
----
=====

|


|810
|
*[repo].[usp_RepoObjectColumn_update_RepoObjectColumn_column_id]*

* `EXEC [repo].[usp_RepoObjectColumn_update_RepoObjectColumn_column_id]`


This must happen later than the index logic, because the PK can change there. And this affects the order of the columns.

.Statement
[%collapsible]
=====
[source,sql,numbered]
----
[repo].[usp_RepoObjectColumn_update_RepoObjectColumn_column_id]
----
=====

|


|910
|
*[repo].[usp_GeneratorUsp_insert_update_persistence]*

* `EXEC [uspgenerator].[usp_GeneratorUsp_insert_update_persistence]`


RepoObjectColumn_column_id is required and should be updated before

.Statement
[%collapsible]
=====
[source,sql,numbered]
----
[uspgenerator].[usp_GeneratorUsp_insert_update_persistence]
----
=====

|


|920
|
*Persistence Target: update repo.RepoObject set InheritanceType = 13 (if NULL)*

* u
* [repo].[RepoObject_persistence]
* [repo].[RepoObject]


.Statement
[%collapsible]
=====
[source,sql,numbered]
----
Update
    repo.RepoObject
Set
    InheritanceType = 13
Where
    ( RepoObject_type = 'U' )
    And ( InheritanceType Is Null )
    And Exists
(
    Select
        1
    From
        repo.RepoObject_persistence As rop
    Where
        rop.target_RepoObject_guid = repo.RepoObject.RepoObject_guid
)
----
=====

|


|3200
|
*[property].[usp_RepoObjectProperty_collect]*

* `EXEC [property].[usp_RepoObjectProperty_collect]`


.Statement
[%collapsible]
=====
[source,sql,numbered]
----
[property].[usp_RepoObjectProperty_collect]
----
=====

|


|3310
|
*[reference].[usp_PERSIST_additional_Reference_from_properties_tgt]*

* `EXEC [reference].[usp_PERSIST_additional_Reference_from_properties_tgt]`


.Statement
[%collapsible]
=====
[source,sql,numbered]
----
[reference].[usp_PERSIST_additional_Reference_from_properties_tgt]
----
=====

|


|3320
|
*[reference].[usp_PERSIST_additional_Reference_wo_columns_from_properties_tgt]*

* `EXEC [reference].[usp_PERSIST_additional_Reference_wo_columns_from_properties_tgt]`


.Statement
[%collapsible]
=====
[source,sql,numbered]
----
[reference].[usp_PERSIST_additional_Reference_wo_columns_from_properties_tgt]
----
=====

|


|3330
|
*[reference].[usp_PERSIST_additional_Reference_from_ssas_tgt]*

* `EXEC [reference].[usp_PERSIST_additional_Reference_from_ssas_tgt]`


.Statement
[%collapsible]
=====
[source,sql,numbered]
----
[reference].[usp_PERSIST_additional_Reference_from_ssas_tgt]
----
=====

|


|3400
|
*[property].[usp_external_property_import]*

* `EXEC [property].[usp_external_property_import]`


.Statement
[%collapsible]
=====
[source,sql,numbered]
----
[property].[usp_external_property_import]
----
=====

|


|4110
|
*[property].[usp_RepoObject_Inheritance]*

* `EXEC [property].[usp_RepoObject_Inheritance]`


.Statement
[%collapsible]
=====
[source,sql,numbered]
----
[property].[usp_RepoObject_Inheritance]
----
=====

|


|4120
|
*[property].[usp_RepoObjectColumn_Inheritance]*

* `EXEC [property].[usp_RepoObjectColumn_Inheritance]`


.Statement
[%collapsible]
=====
[source,sql,numbered]
----
[property].[usp_RepoObjectColumn_Inheritance]
----
=====

|

|===

// end::adocuspsteps[]


=== AntoraReferencedList

// tag::antorareferencedlist[]
* xref:dhw:sqldb:config.fs_get_parameter_value.adoc[]
* xref:dhw:sqldb:config.usp_init_parameter.adoc[]
* xref:dhw:sqldb:logs.usp_executionlog_insert.adoc[]
* xref:dhw:sqldb:property.usp_external_property_import.adoc[]
* xref:dhw:sqldb:property.usp_persist_propertyname_measure_t.adoc[]
* xref:dhw:sqldb:property.usp_repoobject_inheritance.adoc[]
* xref:dhw:sqldb:property.usp_repoobjectcolumn_inheritance.adoc[]
* xref:dhw:sqldb:property.usp_repoobjectproperty_collect.adoc[]
* xref:dhw:sqldb:reference.repoobject_reference_persistence.adoc[]
* xref:dhw:sqldb:reference.repoobject_reference_persistence_target_as_source.adoc[]
* xref:dhw:sqldb:reference.repoobject_reference_t.adoc[]
* xref:dhw:sqldb:reference.usp_additional_reference.adoc[]
* xref:dhw:sqldb:reference.usp_persist_additional_reference_from_properties_tgt.adoc[]
* xref:dhw:sqldb:reference.usp_persist_additional_reference_from_ssas_tgt.adoc[]
* xref:dhw:sqldb:reference.usp_persist_additional_reference_wo_columns_from_properties_tgt.adoc[]
* xref:dhw:sqldb:reference.usp_persist_repoobject_reference_t.adoc[]
* xref:dhw:sqldb:reference.usp_persist_repoobjectcolumn_reference_t.adoc[]
* xref:dhw:sqldb:reference.usp_repoobject_referencetree_insert.adoc[]
* xref:dhw:sqldb:reference.usp_repoobject_update_sysobjectqueryplan.adoc[]
* xref:dhw:sqldb:reference.usp_repoobjectsource_firstresultset.adoc[]
* xref:dhw:sqldb:reference.usp_repoobjectsource_queryplan.adoc[]
* xref:dhw:sqldb:reference.usp_update_referencing_count.adoc[]
* xref:dhw:sqldb:repo.repoobject.adoc[]
* xref:dhw:sqldb:repo.repoobject_persistence.adoc[]
* xref:dhw:sqldb:repo.usp_index_foreignkey.adoc[]
* xref:dhw:sqldb:repo.usp_index_inheritance.adoc[]
* xref:dhw:sqldb:repo.usp_persist_repoobject_sat2_t.adoc[]
* xref:dhw:sqldb:repo.usp_repoobjectcolumn_update_repoobjectcolumn_column_id.adoc[]
* xref:dhw:sqldb:repo.usp_sync_guid.adoc[]
* xref:dhw:sqldb:repo.usp_sync_guid_ssas.adoc[]
* xref:dhw:sqldb:ssas.usp_persist_repoobjectcolumn_translation_t.adoc[]
* xref:dhw:sqldb:uspgenerator.usp_generatorusp_insert_update_persistence.adoc[]
// end::antorareferencedlist[]


=== AntoraReferencingList

// tag::antorareferencinglist[]

// end::antorareferencinglist[]


=== Description

// tag::description[]
main procedure

this central procedure must be executed regularly, try to get e feeling, when it is required +
It does:

* `EXEC repo.usp_sync_guid` to synchronize repository database and dwh database
** some dwh database extended properties (ep) are synchronized with repository database
*** ep RepoObject_guid for each database object
*** ep RepoObjectColumn_guid for each database object column
* index processing
** combination of real and virtual indexes
** virtual and real foreign key
** code generation and updates for persistence procedures
* process references and data lineage
* inheritance of properties

see xref:sqldb:repo.usp_main.adoc#_procdure_steps[Procedure steps] for details.

use links in xref:sqldb:repo.usp_main.adoc#_referenced_objects[Referenced objects] to get details of called sub procedures
// end::description[]


=== exampleUsage

// tag::exampleusage[]
EXEC [repo].[usp_main]
// end::exampleusage[]


=== exampleUsage_2

// tag::exampleusage_2[]

// end::exampleusage_2[]


=== exampleUsage_3

// tag::exampleusage_3[]

// end::exampleusage_3[]


=== exampleUsage_4

// tag::exampleusage_4[]

// end::exampleusage_4[]


=== exampleUsage_5

// tag::exampleusage_5[]

// end::exampleusage_5[]


=== exampleWrong_Usage

// tag::examplewrong_usage[]

// end::examplewrong_usage[]


=== has_execution_plan_issue

// tag::has_execution_plan_issue[]

// end::has_execution_plan_issue[]


=== has_get_referenced_issue

// tag::has_get_referenced_issue[]

// end::has_get_referenced_issue[]


=== has_history

// tag::has_history[]

// end::has_history[]


=== has_history_columns

// tag::has_history_columns[]

// end::has_history_columns[]


=== InheritanceType

// tag::inheritancetype[]

// end::inheritancetype[]


=== is_persistence

// tag::is_persistence[]

// end::is_persistence[]


=== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]

// end::is_persistence_check_duplicate_per_pk[]


=== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]

// end::is_persistence_check_for_empty_source[]


=== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]

// end::is_persistence_delete_changed[]


=== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]

// end::is_persistence_delete_missing[]


=== is_persistence_insert

// tag::is_persistence_insert[]

// end::is_persistence_insert[]


=== is_persistence_truncate

// tag::is_persistence_truncate[]

// end::is_persistence_truncate[]


=== is_persistence_update_changed

// tag::is_persistence_update_changed[]

// end::is_persistence_update_changed[]


=== is_repo_managed

// tag::is_repo_managed[]
0
// end::is_repo_managed[]


=== is_ssas

// tag::is_ssas[]
0
// end::is_ssas[]


=== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


=== MS_Description

// tag::ms_description[]
main procedure

this central procedure must be executed regularly, try to get e feeling, when it is required +
It does:

* `EXEC repo.usp_sync_guid` to synchronize repository database and dwh database
** some dwh database extended properties (ep) are synchronized with repository database
*** ep RepoObject_guid for each database object
*** ep RepoObjectColumn_guid for each database object column
* index processing
** combination of real and virtual indexes
** virtual and real foreign key
** code generation and updates for persistence procedures
* process references and data lineage
* inheritance of properties

see xref:sqldb:repo.usp_main.adoc#_procdure_steps[Procedure steps] for details.

use links in xref:sqldb:repo.usp_main.adoc#_referenced_objects[Referenced objects] to get details of called sub procedures
// end::ms_description[]


=== persistence_source_RepoObject_fullname

// tag::persistence_source_repoobject_fullname[]

// end::persistence_source_repoobject_fullname[]


=== persistence_source_RepoObject_fullname2

// tag::persistence_source_repoobject_fullname2[]

// end::persistence_source_repoobject_fullname2[]


=== persistence_source_RepoObject_guid

// tag::persistence_source_repoobject_guid[]

// end::persistence_source_repoobject_guid[]


=== persistence_source_RepoObject_xref

// tag::persistence_source_repoobject_xref[]

// end::persistence_source_repoobject_xref[]


=== pk_index_guid

// tag::pk_index_guid[]

// end::pk_index_guid[]


=== pk_IndexPatternColumnDatatype

// tag::pk_indexpatterncolumndatatype[]

// end::pk_indexpatterncolumndatatype[]


=== pk_IndexPatternColumnName

// tag::pk_indexpatterncolumnname[]

// end::pk_indexpatterncolumnname[]


=== pk_IndexSemanticGroup

// tag::pk_indexsemanticgroup[]

// end::pk_indexsemanticgroup[]


=== ReferencedObjectList

// tag::referencedobjectlist[]
* [config].[fs_get_parameter_value]
* [config].[usp_init_parameter]
* [logs].[usp_ExecutionLog_insert]
* [property].[usp_external_property_import]
* [property].[usp_PERSIST_PropertyName_Measure_T]
* [property].[usp_RepoObject_Inheritance]
* [property].[usp_RepoObjectColumn_Inheritance]
* [property].[usp_RepoObjectProperty_collect]
* [reference].[RepoObject_reference_persistence]
* [reference].[RepoObject_reference_persistence_target_as_source]
* [reference].[RepoObject_reference_T]
* [reference].[usp_additional_Reference]
* [reference].[usp_PERSIST_additional_Reference_from_properties_tgt]
* [reference].[usp_PERSIST_additional_Reference_from_ssas_tgt]
* [reference].[usp_PERSIST_additional_Reference_wo_columns_from_properties_tgt]
* [reference].[usp_PERSIST_RepoObject_reference_T]
* [reference].[usp_PERSIST_RepoObjectColumn_reference_T]
* [reference].[usp_RepoObject_ReferenceTree_insert]
* [reference].[usp_RepoObject_update_SysObjectQueryPlan]
* [reference].[usp_RepoObjectSource_FirstResultSet]
* [reference].[usp_RepoObjectSource_QueryPlan]
* [reference].[usp_update_Referencing_Count]
* [repo].[RepoObject]
* [repo].[RepoObject_persistence]
* [repo].[usp_Index_ForeignKey]
* [repo].[usp_index_inheritance]
* [repo].[usp_PERSIST_RepoObject_sat2_T]
* [repo].[usp_RepoObjectColumn_update_RepoObjectColumn_column_id]
* [repo].[usp_sync_guid]
* [repo].[usp_sync_guid_ssas]
* [ssas].[usp_PERSIST_RepoObjectColumn_translation_T]
* [uspgenerator].[usp_GeneratorUsp_insert_update_persistence]
// end::referencedobjectlist[]


=== usp_persistence_RepoObject_guid

// tag::usp_persistence_repoobject_guid[]

// end::usp_persistence_repoobject_guid[]


=== UspExamples

// tag::uspexamples[]
EXEC = [repo].[usp_main]
// end::uspexamples[]


=== uspgenerator_usp_id

// tag::uspgenerator_usp_id[]
2
// end::uspgenerator_usp_id[]


=== UspParameters

// tag::uspparameters[]

// end::uspparameters[]

== Boolean Attributes

source: property.RepoObjectProperty WHERE property_int = 1

// tag::boolean_attributes[]


// end::boolean_attributes[]

== PlantUML diagrams

=== PlantUML Entity

// tag::puml_entity[]
[plantuml, entity-{docname}, svg, subs=macros]
....
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:repo.usp_main.adoc[]" as repo.usp_main << P >> {
  --
}
....

// end::puml_entity[]

=== PlantUML Entity 1 1 FK

// tag::puml_entity_1_1_fk[]
[plantuml, entity_1_1_fk-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}





footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_fk[]

=== PlantUML 1 1 ObjectRef

// tag::puml_entity_1_1_objectref[]
[plantuml, entity_1_1_objectref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:config.fs_get_parameter_value.adoc[]" as config.fs_get_parameter_value << FN >> {
  --
}

entity "puml-link:dhw:sqldb:config.usp_init_parameter.adoc[]" as config.usp_init_parameter << P >> {
  --
}

entity "puml-link:dhw:sqldb:logs.usp_executionlog_insert.adoc[]" as logs.usp_ExecutionLog_insert << P >> {
  --
}

entity "puml-link:dhw:sqldb:property.usp_external_property_import.adoc[]" as property.usp_external_property_import << P >> {
  --
}

entity "puml-link:dhw:sqldb:property.usp_persist_propertyname_measure_t.adoc[]" as property.usp_PERSIST_PropertyName_Measure_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:property.usp_repoobject_inheritance.adoc[]" as property.usp_RepoObject_Inheritance << P >> {
  --
}

entity "puml-link:dhw:sqldb:property.usp_repoobjectcolumn_inheritance.adoc[]" as property.usp_RepoObjectColumn_Inheritance << P >> {
  --
}

entity "puml-link:dhw:sqldb:property.usp_repoobjectproperty_collect.adoc[]" as property.usp_RepoObjectProperty_collect << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_reference_persistence.adoc[]" as reference.RepoObject_reference_persistence << V >> {
  **referenced_RepoObject_guid** : (uniqueidentifier)
  - **referencing_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_reference_persistence_target_as_source.adoc[]" as reference.RepoObject_reference_persistence_target_as_source << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_reference_t.adoc[]" as reference.RepoObject_reference_T << U >> {
  - **referenced_RepoObject_guid** : (uniqueidentifier)
  - **referencing_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.usp_additional_reference.adoc[]" as reference.usp_additional_Reference << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_persist_additional_reference_from_properties_tgt.adoc[]" as reference.usp_PERSIST_additional_Reference_from_properties_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_persist_additional_reference_from_ssas_tgt.adoc[]" as reference.usp_PERSIST_additional_Reference_from_ssas_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_persist_additional_reference_wo_columns_from_properties_tgt.adoc[]" as reference.usp_PERSIST_additional_Reference_wo_columns_from_properties_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_persist_repoobject_reference_t.adoc[]" as reference.usp_PERSIST_RepoObject_reference_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_persist_repoobjectcolumn_reference_t.adoc[]" as reference.usp_PERSIST_RepoObjectColumn_reference_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_repoobject_referencetree_insert.adoc[]" as reference.usp_RepoObject_ReferenceTree_insert << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_repoobject_update_sysobjectqueryplan.adoc[]" as reference.usp_RepoObject_update_SysObjectQueryPlan << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_repoobjectsource_firstresultset.adoc[]" as reference.usp_RepoObjectSource_FirstResultSet << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_repoobjectsource_queryplan.adoc[]" as reference.usp_RepoObjectSource_QueryPlan << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_update_referencing_count.adoc[]" as reference.usp_update_Referencing_Count << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject.adoc[]" as repo.RepoObject << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_persistence.adoc[]" as repo.RepoObject_persistence << U >> {
  - **target_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.usp_index_foreignkey.adoc[]" as repo.usp_Index_ForeignKey << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_index_inheritance.adoc[]" as repo.usp_index_inheritance << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_main.adoc[]" as repo.usp_main << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_persist_repoobject_sat2_t.adoc[]" as repo.usp_PERSIST_RepoObject_sat2_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_repoobjectcolumn_update_repoobjectcolumn_column_id.adoc[]" as repo.usp_RepoObjectColumn_update_RepoObjectColumn_column_id << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_sync_guid.adoc[]" as repo.usp_sync_guid << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_sync_guid_ssas.adoc[]" as repo.usp_sync_guid_ssas << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.usp_persist_repoobjectcolumn_translation_t.adoc[]" as ssas.usp_PERSIST_RepoObjectColumn_translation_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.usp_generatorusp_insert_update_persistence.adoc[]" as uspgenerator.usp_GeneratorUsp_insert_update_persistence << P >> {
  --
}

config.fs_get_parameter_value <.. repo.usp_main
config.usp_init_parameter <.. repo.usp_main
logs.usp_ExecutionLog_insert <.. repo.usp_main
property.usp_external_property_import <.. repo.usp_main
property.usp_PERSIST_PropertyName_Measure_T <.. repo.usp_main
property.usp_RepoObject_Inheritance <.. repo.usp_main
property.usp_RepoObjectColumn_Inheritance <.. repo.usp_main
property.usp_RepoObjectProperty_collect <.. repo.usp_main
reference.RepoObject_reference_persistence <.. repo.usp_main
reference.RepoObject_reference_persistence_target_as_source <.. repo.usp_main
reference.RepoObject_reference_T <.. repo.usp_main
reference.usp_additional_Reference <.. repo.usp_main
reference.usp_PERSIST_additional_Reference_from_properties_tgt <.. repo.usp_main
reference.usp_PERSIST_additional_Reference_from_ssas_tgt <.. repo.usp_main
reference.usp_PERSIST_additional_Reference_wo_columns_from_properties_tgt <.. repo.usp_main
reference.usp_PERSIST_RepoObject_reference_T <.. repo.usp_main
reference.usp_PERSIST_RepoObjectColumn_reference_T <.. repo.usp_main
reference.usp_RepoObject_ReferenceTree_insert <.. repo.usp_main
reference.usp_RepoObject_update_SysObjectQueryPlan <.. repo.usp_main
reference.usp_RepoObjectSource_FirstResultSet <.. repo.usp_main
reference.usp_RepoObjectSource_QueryPlan <.. repo.usp_main
reference.usp_update_Referencing_Count <.. repo.usp_main
repo.RepoObject <.. repo.usp_main
repo.RepoObject_persistence <.. repo.usp_main
repo.usp_Index_ForeignKey <.. repo.usp_main
repo.usp_index_inheritance <.. repo.usp_main
repo.usp_PERSIST_RepoObject_sat2_T <.. repo.usp_main
repo.usp_RepoObjectColumn_update_RepoObjectColumn_column_id <.. repo.usp_main
repo.usp_sync_guid <.. repo.usp_main
repo.usp_sync_guid_ssas <.. repo.usp_main
ssas.usp_PERSIST_RepoObjectColumn_translation_T <.. repo.usp_main
uspgenerator.usp_GeneratorUsp_insert_update_persistence <.. repo.usp_main

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_objectref[]

=== PlantUML 30 0 ObjectRef

// tag::puml_entity_30_0_objectref[]
[plantuml, entity_30_0_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:config.fs_dwh_database_name.adoc[]" as config.fs_dwh_database_name << FN >> {
  --
}

entity "puml-link:dhw:sqldb:config.fs_get_parameter_value.adoc[]" as config.fs_get_parameter_value << FN >> {
  --
}

entity "puml-link:dhw:sqldb:config.ftv_dwh_database.adoc[]" as config.ftv_dwh_database << IF >> {
  --
}

entity "puml-link:dhw:sqldb:config.ftv_get_parameter_value.adoc[]" as config.ftv_get_parameter_value << IF >> {
  --
}

entity "puml-link:dhw:sqldb:config.parameter.adoc[]" as config.Parameter << U >> {
  - **Parameter_name** : (varchar(100))
  - **sub_Parameter** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:config.usp_init_parameter.adoc[]" as config.usp_init_parameter << P >> {
  --
}

entity "puml-link:dhw:sqldb:configt.join_type.adoc[]" as configT.join_type << V >> {
  - **join_type** : (varchar(16))
  --
}

entity "puml-link:dhw:sqldb:configt.parameter_default.adoc[]" as configT.Parameter_default << V >> {
  - **Parameter_name** : (varchar(52))
  - **sub_Parameter** : (nvarchar(26))
  --
}

entity "puml-link:dhw:sqldb:configt.spt_values.adoc[]" as configT.spt_values << U >> {
  --
}

entity "puml-link:dhw:sqldb:configt.type.adoc[]" as configT.type << V >> {
  **type** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:configt.type_level1type_level2type.adoc[]" as configT.type_level1type_level2type << V >> {
  **type** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:docs.culture.adoc[]" as docs.Culture << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.fs_cleanstringforanchorid.adoc[]" as docs.fs_cleanStringForAnchorId << FN >> {
  --
}

entity "puml-link:dhw:sqldb:docs.fs_cleanstringforfilename.adoc[]" as docs.fs_cleanStringForFilename << FN >> {
  --
}

entity "puml-link:dhw:sqldb:logs.executionlog.adoc[]" as logs.ExecutionLog << U >> {
  - **id** : (bigint)
  --
}

entity "puml-link:dhw:sqldb:logs.usp_executionlog_insert.adoc[]" as logs.usp_ExecutionLog_insert << P >> {
  --
}

entity "puml-link:dhw:sqldb:property.external_repoobjectcolumnproperty.adoc[]" as property.external_RepoObjectColumnProperty << U >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.external_repoobjectproperty.adoc[]" as property.external_RepoObjectProperty << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.fs_get_repoobjectcolumnproperty_nvarchar.adoc[]" as property.fs_get_RepoObjectColumnProperty_nvarchar << FN >> {
  --
}

entity "puml-link:dhw:sqldb:property.fs_get_repoobjectproperty_nvarchar.adoc[]" as property.fs_get_RepoObjectProperty_nvarchar << FN >> {
  --
}

entity "puml-link:dhw:sqldb:property.measureproperty.adoc[]" as property.MeasureProperty << U >> {
  - **Measure_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.propertyname_measure.adoc[]" as property.PropertyName_Measure << V >> {
  **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.propertyname_measure_t.adoc[]" as property.PropertyName_Measure_T << U >> {
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.propertyname_repoobject.adoc[]" as property.PropertyName_RepoObject << V >> {
  **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.propertyname_repoobject_t.adoc[]" as property.PropertyName_RepoObject_T << U >> {
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.propertyname_repoobjectcolumn.adoc[]" as property.PropertyName_RepoObjectColumn << V >> {
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.propertyname_repoobjectcolumn_t.adoc[]" as property.PropertyName_RepoObjectColumn_T << U >> {
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.repoobject_inheritance_temp.adoc[]" as property.RepoObject_Inheritance_temp << U >> {
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectcolumn_inheritance_temp.adoc[]" as property.RepoObjectColumn_Inheritance_temp << U >> {
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectcolumnproperty.adoc[]" as property.RepoObjectColumnProperty << U >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectcolumnproperty_external_src.adoc[]" as property.RepoObjectColumnProperty_external_src << V >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectcolumnproperty_external_tgt.adoc[]" as property.RepoObjectColumnProperty_external_tgt << V >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectcolumnproperty_inheritancetype_inheritancedefinition.adoc[]" as property.RepoObjectColumnProperty_InheritanceType_InheritanceDefinition << V >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectcolumnproperty_inheritancetype_resulting_inheritancedefinition.adoc[]" as property.RepoObjectColumnProperty_InheritanceType_resulting_InheritanceDefinition << V >> {
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty.adoc[]" as property.RepoObjectProperty << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty_collect_source_rogross.adoc[]" as property.RepoObjectProperty_Collect_source_ROGross << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **property_name** : (varchar(39))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty_collect_source_sql_modules_definition.adoc[]" as property.RepoObjectProperty_Collect_source_sql_modules_definition << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty_collect_source_uspgenerator.adoc[]" as property.RepoObjectProperty_Collect_source_uspgenerator << V >> {
  **RepoObject_guid** : (uniqueidentifier)
  - **property_name** : (varchar(14))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty_external_src.adoc[]" as property.RepoObjectProperty_external_src << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty_external_tgt.adoc[]" as property.RepoObjectProperty_external_tgt << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty_inheritancetype_inheritancedefinition.adoc[]" as property.RepoObjectProperty_InheritanceType_InheritanceDefinition << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty_inheritancetype_resulting_inheritancedefinition.adoc[]" as property.RepoObjectProperty_InheritanceType_resulting_InheritanceDefinition << V >> {
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty_selectedpropertyname_split.adoc[]" as property.RepoObjectProperty_SelectedPropertyName_split << V >> {
  --
}

entity "puml-link:dhw:sqldb:property.usp_external_property_import.adoc[]" as property.usp_external_property_import << P >> {
  --
}

entity "puml-link:dhw:sqldb:property.usp_persist_propertyname_measure_t.adoc[]" as property.usp_PERSIST_PropertyName_Measure_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:property.usp_persist_propertyname_repoobject_t.adoc[]" as property.usp_PERSIST_PropertyName_RepoObject_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:property.usp_persist_propertyname_repoobjectcolumn_t.adoc[]" as property.usp_PERSIST_PropertyName_RepoObjectColumn_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:property.usp_persist_repoobjectcolumnproperty_external_tgt.adoc[]" as property.usp_PERSIST_RepoObjectColumnProperty_external_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:property.usp_persist_repoobjectproperty_external_tgt.adoc[]" as property.usp_PERSIST_RepoObjectProperty_external_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:property.usp_repoobject_inheritance.adoc[]" as property.usp_RepoObject_Inheritance << P >> {
  --
}

entity "puml-link:dhw:sqldb:property.usp_repoobjectcolumn_inheritance.adoc[]" as property.usp_RepoObjectColumn_Inheritance << P >> {
  --
}

entity "puml-link:dhw:sqldb:property.usp_repoobjectproperty_collect.adoc[]" as property.usp_RepoObjectProperty_collect << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference.adoc[]" as reference.additional_Reference << U >> {
  # **tik_hash_c** : (nvarchar(32))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_database.adoc[]" as reference.additional_Reference_database << V >> {
  - **AntoraComponent** : (nvarchar(128))
  - **AntoraModule** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_database_t.adoc[]" as reference.additional_Reference_database_T << U >> {
  - **AntoraComponent** : (nvarchar(128))
  - **AntoraModule** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_from_properties_src.adoc[]" as reference.additional_Reference_from_properties_src << V >> {
  **referenced_AntoraComponent** : (nvarchar(max))
  **referenced_AntoraModule** : (nvarchar(max))
  **referenced_Schema** : (nvarchar(max))
  **referenced_Object** : (nvarchar(max))
  **referenced_Column** : (nvarchar(max))
  **referencing_AntoraComponent** : (nvarchar(max))
  **referencing_AntoraModule** : (nvarchar(max))
  **referencing_Schema** : (nvarchar(max))
  **referencing_Object** : (nvarchar(max))
  **referencing_Column** : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_from_properties_tgt.adoc[]" as reference.additional_Reference_from_properties_tgt << V >> {
  - **referenced_AntoraComponent** : (nvarchar(128))
  - **referenced_AntoraModule** : (nvarchar(128))
  - **referenced_Schema** : (nvarchar(128))
  - **referenced_Object** : (nvarchar(128))
  **referenced_Column** : (nvarchar(128))
  - **referencing_AntoraComponent** : (nvarchar(128))
  - **referencing_AntoraModule** : (nvarchar(128))
  - **referencing_Schema** : (nvarchar(128))
  - **referencing_Object** : (nvarchar(128))
  **referencing_Column** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_from_ssas_src.adoc[]" as reference.additional_Reference_from_ssas_src << V >> {
  **referenced_AntoraComponent** : (nvarchar(128))
  **referenced_AntoraModule** : (nvarchar(128))
  **referenced_Schema** : (nvarchar(max))
  **referenced_Object** : (nvarchar(max))
  **referenced_Column** : (nvarchar(500))
  **referencing_AntoraComponent** : (nvarchar(max))
  **referencing_AntoraModule** : (nvarchar(max))
  - **referencing_Schema** : (nvarchar(128))
  - **referencing_Object** : (nvarchar(128))
  **referencing_Column** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_from_ssas_tgt.adoc[]" as reference.additional_Reference_from_ssas_tgt << V >> {
  - **referenced_AntoraComponent** : (nvarchar(128))
  - **referenced_AntoraModule** : (nvarchar(128))
  - **referenced_Schema** : (nvarchar(128))
  - **referenced_Object** : (nvarchar(128))
  **referenced_Column** : (nvarchar(128))
  - **referencing_AntoraComponent** : (nvarchar(128))
  - **referencing_AntoraModule** : (nvarchar(128))
  - **referencing_Schema** : (nvarchar(128))
  - **referencing_Object** : (nvarchar(128))
  **referencing_Column** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_guid.adoc[]" as reference.additional_Reference_guid << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_is_external.adoc[]" as reference.additional_Reference_is_external << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_object.adoc[]" as reference.additional_Reference_Object << V >> {
  - **AntoraComponent** : (nvarchar(128))
  - **AntoraModule** : (nvarchar(128))
  - **SchemaName** : (nvarchar(128))
  - **ObjectName** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_object_t.adoc[]" as reference.additional_Reference_Object_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_objectcolumn.adoc[]" as reference.additional_Reference_ObjectColumn << V >> {
  - **AntoraComponent** : (nvarchar(128))
  - **AntoraModule** : (nvarchar(128))
  - **SchemaName** : (nvarchar(128))
  - **ObjectName** : (nvarchar(128))
  **ColumnName** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_objectcolumn_t.adoc[]" as reference.additional_Reference_ObjectColumn_T << U >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_wo_columns_from_properties_src.adoc[]" as reference.additional_Reference_wo_columns_from_properties_src << V >> {
  **referenced_AntoraComponent** : (nvarchar(max))
  **referenced_AntoraModule** : (nvarchar(max))
  **referenced_Schema** : (nvarchar(max))
  **referenced_Object** : (nvarchar(max))
  **referencing_AntoraComponent** : (nvarchar(max))
  **referencing_AntoraModule** : (nvarchar(max))
  **referencing_Schema** : (nvarchar(max))
  **referencing_Object** : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_wo_columns_from_properties_tgt.adoc[]" as reference.additional_Reference_wo_columns_from_properties_tgt << V >> {
  - **referenced_AntoraComponent** : (nvarchar(128))
  - **referenced_AntoraModule** : (nvarchar(128))
  - **referenced_Schema** : (nvarchar(128))
  - **referenced_Object** : (nvarchar(128))
  - **referencing_AntoraComponent** : (nvarchar(128))
  - **referencing_AntoraModule** : (nvarchar(128))
  - **referencing_Schema** : (nvarchar(128))
  - **referencing_Object** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:reference.ftv_query_plan_extract_source.adoc[]" as reference.ftv_query_plan_extract_source << IF >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_queryplan.adoc[]" as reference.RepoObject_QueryPlan << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_reference.adoc[]" as reference.RepoObject_reference << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_reference_additional.adoc[]" as reference.RepoObject_reference_additional << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_reference_persistence.adoc[]" as reference.RepoObject_reference_persistence << V >> {
  **referenced_RepoObject_guid** : (uniqueidentifier)
  - **referencing_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_reference_persistence_target_as_source.adoc[]" as reference.RepoObject_reference_persistence_target_as_source << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_reference_persistence_target_as_source_explicit.adoc[]" as reference.RepoObject_reference_persistence_target_as_source_explicit << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_reference_sqlexpressiondependencies.adoc[]" as reference.RepoObject_reference_SqlExpressionDependencies << V >> {
  **referenced_RepoObject_guid** : (uniqueidentifier)
  **referencing_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_reference_t.adoc[]" as reference.RepoObject_reference_T << U >> {
  - **referenced_RepoObject_guid** : (uniqueidentifier)
  - **referencing_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_reference_union.adoc[]" as reference.RepoObject_reference_union << V >> {
  **referenced_RepoObject_guid** : (uniqueidentifier)
  **referencing_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_reference_virtual.adoc[]" as reference.RepoObject_reference_virtual << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_referencedlist.adoc[]" as reference.RepoObject_ReferencedList << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_referencedreferencing.adoc[]" as reference.RepoObject_ReferencedReferencing << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_referencetree.adoc[]" as reference.RepoObject_ReferenceTree << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  **Referenced_Depth** : (int)
  **Referencing_Depth** : (int)
  - **Referenced_guid** : (uniqueidentifier)
  - **Referencing_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_referencinglist.adoc[]" as reference.RepoObject_ReferencingList << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_reference.adoc[]" as reference.RepoObjectColumn_reference << V >> {
  **referenced_RepoObjectColumn_guid** : (uniqueidentifier)
  **referencing_RepoObjectColumn_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_reference_additional.adoc[]" as reference.RepoObjectColumn_reference_additional << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_reference_persistence.adoc[]" as reference.RepoObjectColumn_reference_Persistence << V >> {
  **referencing_id** : (int)
  **referencing_minor_id** : (int)
  **referenced_id** : (int)
  **referenced_minor_id** : (int)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_reference_queryplan.adoc[]" as reference.RepoObjectColumn_reference_QueryPlan << V >> {
  **referencing_id** : (int)
  **referencing_minor_id** : (int)
  **referenced_id** : (int)
  **referenced_minor_id** : (int)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_reference_sqlexpressiondependencies.adoc[]" as reference.RepoObjectColumn_reference_SqlExpressionDependencies << V >> {
  - **referencing_id** : (int)
  - **referencing_minor_id** : (int)
  **referenced_id** : (int)
  - **referenced_minor_id** : (int)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_reference_sqlmodules.adoc[]" as reference.RepoObjectColumn_reference_SqlModules << V >> {
  **referencing_id** : (int)
  **referencing_minor_id** : (int)
  **referenced_id** : (int)
  **referenced_minor_id** : (int)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_reference_t.adoc[]" as reference.RepoObjectColumn_reference_T << U >> {
  - **referenced_RepoObjectColumn_guid** : (uniqueidentifier)
  - **referencing_RepoObjectColumn_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_reference_union.adoc[]" as reference.RepoObjectColumn_reference_union << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_reference_virtual.adoc[]" as reference.RepoObjectColumn_reference_virtual << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_referencedlist.adoc[]" as reference.RepoObjectColumn_ReferencedList << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_referencedreferencing.adoc[]" as reference.RepoObjectColumn_ReferencedReferencing << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_referencinglist.adoc[]" as reference.RepoObjectColumn_ReferencingList << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumnsource_virtual.adoc[]" as reference.RepoObjectColumnSource_virtual << U >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  - **Source_RepoObjectColumn_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectsource_firstresultset.adoc[]" as reference.RepoObjectSource_FirstResultSet << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **column_ordinal** : (int)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectsource_queryplan.adoc[]" as reference.RepoObjectSource_QueryPlan << U >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectsource_virtual.adoc[]" as reference.RepoObjectSource_virtual << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **Source_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.sysobjectcolumn_queryplanexpression.adoc[]" as reference.SysObjectColumn_QueryPlanExpression << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_additional_reference.adoc[]" as reference.usp_additional_Reference << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_persist_additional_reference_database_t.adoc[]" as reference.usp_PERSIST_additional_Reference_database_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_persist_additional_reference_from_properties_tgt.adoc[]" as reference.usp_PERSIST_additional_Reference_from_properties_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_persist_additional_reference_from_ssas_tgt.adoc[]" as reference.usp_PERSIST_additional_Reference_from_ssas_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_persist_additional_reference_object_t.adoc[]" as reference.usp_PERSIST_additional_Reference_Object_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_persist_additional_reference_objectcolumn_t.adoc[]" as reference.usp_PERSIST_additional_Reference_ObjectColumn_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_persist_additional_reference_wo_columns_from_properties_tgt.adoc[]" as reference.usp_PERSIST_additional_Reference_wo_columns_from_properties_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_persist_repoobject_reference_t.adoc[]" as reference.usp_PERSIST_RepoObject_reference_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_persist_repoobjectcolumn_reference_t.adoc[]" as reference.usp_PERSIST_RepoObjectColumn_reference_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_repoobject_referencetree_insert.adoc[]" as reference.usp_RepoObject_ReferenceTree_insert << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_repoobject_update_sysobjectqueryplan.adoc[]" as reference.usp_RepoObject_update_SysObjectQueryPlan << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_repoobjectsource_firstresultset.adoc[]" as reference.usp_RepoObjectSource_FirstResultSet << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_repoobjectsource_queryplan.adoc[]" as reference.usp_RepoObjectSource_QueryPlan << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_update_referencing_count.adoc[]" as reference.usp_update_Referencing_Count << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.foreignkey_indexes.adoc[]" as repo.ForeignKey_Indexes << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.foreignkey_indexes_union.adoc[]" as repo.ForeignKey_Indexes_union << V >> {
  **ForeignKey_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.foreignkey_indexes_union_t.adoc[]" as repo.ForeignKey_Indexes_union_T << U >> {
  **ForeignKey_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.foreignkey_indexpattern.adoc[]" as repo.ForeignKey_IndexPattern << V >> {
  - **constraint_object_id** : (int)
  **ForeignKey_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.foreignkey_ssas_indexes.adoc[]" as repo.ForeignKey_ssas_Indexes << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.foreignkey_ssas_indexpattern.adoc[]" as repo.ForeignKey_ssas_IndexPattern << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.foreignkey_virtual.adoc[]" as repo.ForeignKey_virtual << U >> {
  - **ForeignKey_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.foreignkey_virtual_indexes.adoc[]" as repo.ForeignKey_virtual_Indexes << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.index_columlist.adoc[]" as repo.Index_ColumList << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.index_columlist_t.adoc[]" as repo.Index_ColumList_T << U >> {
  - **index_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.index_gross.adoc[]" as repo.Index_gross << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.index_indexpattern.adoc[]" as repo.Index_IndexPattern << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.index_referencing_indexpatterncolumnguid.adoc[]" as repo.Index_referencing_IndexPatternColumnGuid << V >> {
  **source_index_guid** : (uniqueidentifier)
  **referencing_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.index_settings.adoc[]" as repo.Index_Settings << U >> {
  - **index_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.index_ssas.adoc[]" as repo.Index_ssas << V >> {
  - **databasename** : (nvarchar(128))
  **index_name** : (nvarchar(450))
  --
}

entity "puml-link:dhw:sqldb:repo.index_ssas_indexpatterncolumnguid.adoc[]" as repo.Index_ssas_IndexPatternColumnGuid << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.index_ssas_t.adoc[]" as repo.Index_ssas_T << U >> {
  - **databasename** : (nvarchar(128))
  - **index_name** : (nvarchar(450))
  --
}

entity "puml-link:dhw:sqldb:repo.index_union.adoc[]" as repo.Index_union << V >> {
  **index_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.index_unique_indexpatterncolumnguid.adoc[]" as repo.Index_unique_IndexPatternColumnGuid << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.index_virtual.adoc[]" as repo.Index_virtual << U >> {
  - **index_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.index_virtual_forupdate.adoc[]" as repo.Index_virtual_ForUpdate << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.index_virtual_indexpatterncolumnguid.adoc[]" as repo.Index_virtual_IndexPatternColumnGuid << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.indexcolumn_referencedreferencing_hasfullcolumnsinreferencing.adoc[]" as repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing << V >> {
  - **index_guid** : (uniqueidentifier)
  - **index_column_id** : (int)
  **RowNumberInReferencing** : (bigint)
  --
}

entity "puml-link:dhw:sqldb:repo.indexcolumn_referencedreferencing_hasfullcolumnsinreferencing_t.adoc[]" as repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T << U >> {
  **index_guid** : (uniqueidentifier)
  - **index_column_id** : (int)
  **RowNumberInReferencing** : (bigint)
  --
}

entity "puml-link:dhw:sqldb:repo.indexcolumn_ssas.adoc[]" as repo.IndexColumn_ssas << V >> {
  - **index_guid** : (uniqueidentifier)
  - **index_column_id** : (int)
  --
}

entity "puml-link:dhw:sqldb:repo.indexcolumn_ssas_gross.adoc[]" as repo.IndexColumn_ssas_gross << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.indexcolumn_ssas_t.adoc[]" as repo.IndexColumn_ssas_T << U >> {
  - **index_guid** : (uniqueidentifier)
  - **index_column_id** : (int)
  --
}

entity "puml-link:dhw:sqldb:repo.indexcolumn_union.adoc[]" as repo.IndexColumn_union << V >> {
  **index_guid** : (uniqueidentifier)
  - **index_column_id** : (int)
  --
}

entity "puml-link:dhw:sqldb:repo.indexcolumn_union_t.adoc[]" as repo.IndexColumn_union_T << U >> {
  - **index_guid** : (uniqueidentifier)
  - **index_column_id** : (int)
  --
}

entity "puml-link:dhw:sqldb:repo.indexcolumn_virtual.adoc[]" as repo.IndexColumn_virtual << U >> {
  - **index_guid** : (uniqueidentifier)
  - **index_column_id** : (int)
  --
}

entity "puml-link:dhw:sqldb:repo.indexcolumn_virtual_gross.adoc[]" as repo.IndexColumn_virtual_gross << V >> {
  - **index_column_id** : (int)
  --
}

entity "puml-link:dhw:sqldb:repo.indexcolumn_virtual_referenced_setpoint.adoc[]" as repo.IndexColumn_virtual_referenced_setpoint << V >> {
  - **index_guid** : (uniqueidentifier)
  - **index_column_id** : (int)
  --
}

entity "puml-link:dhw:sqldb:repo.indexreferencedreferencing.adoc[]" as repo.IndexReferencedReferencing << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.indexreferencedreferencing_hasfullcolumnsinreferencing.adoc[]" as repo.IndexReferencedReferencing_HasFullColumnsInReferencing << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.measure.adoc[]" as repo.Measure << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.measure_union.adoc[]" as repo.Measure_union << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject.adoc[]" as repo.RepoObject << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_columnlist.adoc[]" as repo.RepoObject_ColumnList << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_external_src.adoc[]" as repo.RepoObject_external_src << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_external_tgt.adoc[]" as repo.RepoObject_external_tgt << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_gross.adoc[]" as repo.RepoObject_gross << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_gross_persistence.adoc[]" as repo.RepoObject_gross_persistence << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_gross2.adoc[]" as repo.RepoObject_gross2 << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_persistence.adoc[]" as repo.RepoObject_persistence << U >> {
  - **target_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_persistence_nocomparebutupdate.adoc[]" as repo.RepoObject_persistence_NoCompareButUpdate << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_persistence_nocomparenoupdate.adoc[]" as repo.RepoObject_persistence_NoCompareNoUpdate << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_persistence_source_ignore.adoc[]" as repo.RepoObject_persistence_source_Ignore << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_persistence_target_ignore.adoc[]" as repo.RepoObject_persistence_target_Ignore << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_requiredrepoobjectmerge.adoc[]" as repo.RepoObject_RequiredRepoObjectMerge << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_sat2.adoc[]" as repo.RepoObject_sat2 << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_sat2_t.adoc[]" as repo.RepoObject_sat2_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_ssas_src.adoc[]" as repo.RepoObject_SSAS_src << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_ssas_tgt.adoc[]" as repo.RepoObject_SSAS_tgt << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn.adoc[]" as repo.RepoObjectColumn << U >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn_external_src.adoc[]" as repo.RepoObjectColumn_external_src << V >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn_external_tgt.adoc[]" as repo.RepoObjectColumn_external_tgt << V >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn_gross.adoc[]" as repo.RepoObjectColumn_gross << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn_gross2.adoc[]" as repo.RepoObjectColumn_gross2 << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn_histvalidcolums_setpoint.adoc[]" as repo.RepoObjectColumn_HistValidColums_setpoint << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  **RepoObjectColumn_name** : (sysname)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn_requiredrepoobjectcolumnmerge.adoc[]" as repo.RepoObjectColumn_RequiredRepoObjectColumnMerge << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn_ssas_src.adoc[]" as repo.RepoObjectColumn_SSAS_src << V >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn_ssas_tgt.adoc[]" as repo.RepoObjectColumn_SSAS_tgt << V >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.reposchema.adoc[]" as repo.RepoSchema << U >> {
  - **RepoSchema_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.reposchema_ssas_src.adoc[]" as repo.RepoSchema_ssas_src << V >> {
  - **RepoSchema_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:repo.reposchema_ssas_tgt.adoc[]" as repo.RepoSchema_ssas_tgt << V >> {
  - **RepoSchema_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.syscolumn_repoobjectcolumn_via_guid.adoc[]" as repo.SysColumn_RepoObjectColumn_via_guid << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.syscolumn_repoobjectcolumn_via_name.adoc[]" as repo.SysColumn_RepoObjectColumn_via_name << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.sysobject_repoobject_via_guid.adoc[]" as repo.SysObject_RepoObject_via_guid << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.sysobject_repoobject_via_name.adoc[]" as repo.SysObject_RepoObject_via_name << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.sysschema_reposchema_via_guid.adoc[]" as repo.SysSchema_RepoSchema_via_guid << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.sysschema_reposchema_via_name.adoc[]" as repo.SysSchema_RepoSchema_via_name << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_index_finish.adoc[]" as repo.usp_Index_finish << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_index_foreignkey.adoc[]" as repo.usp_Index_ForeignKey << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_index_inheritance.adoc[]" as repo.usp_index_inheritance << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_index_settings.adoc[]" as repo.usp_Index_Settings << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_index_virtual_set.adoc[]" as repo.usp_Index_virtual_set << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_main.adoc[]" as repo.usp_main << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_persist_foreignkey_indexes_union_t.adoc[]" as repo.usp_PERSIST_ForeignKey_Indexes_union_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_persist_index_columlist_t.adoc[]" as repo.usp_PERSIST_Index_ColumList_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_persist_index_ssas_t.adoc[]" as repo.usp_PERSIST_Index_ssas_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_persist_indexcolumn_referencedreferencing_hasfullcolumnsinreferencing_t.adoc[]" as repo.usp_PERSIST_IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_persist_indexcolumn_ssas_t.adoc[]" as repo.usp_PERSIST_IndexColumn_ssas_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_persist_indexcolumn_union_t.adoc[]" as repo.usp_PERSIST_IndexColumn_union_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_persist_repoobject_external_tgt.adoc[]" as repo.usp_PERSIST_RepoObject_external_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_persist_repoobject_sat2_t.adoc[]" as repo.usp_PERSIST_RepoObject_sat2_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_persist_repoobject_ssas_tgt.adoc[]" as repo.usp_PERSIST_RepoObject_SSAS_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_persist_repoobjectcolumn_external_tgt.adoc[]" as repo.usp_PERSIST_RepoObjectColumn_external_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_persist_repoobjectcolumn_ssas_tgt.adoc[]" as repo.usp_PERSIST_RepoObjectColumn_SSAS_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_persist_reposchema_ssas_tgt.adoc[]" as repo.usp_PERSIST_RepoSchema_ssas_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_repoobjectcolumn_update_repoobjectcolumn_column_id.adoc[]" as repo.usp_RepoObjectColumn_update_RepoObjectColumn_column_id << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_sync_guid.adoc[]" as repo.usp_sync_guid << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_sync_guid_repoobject.adoc[]" as repo.usp_sync_guid_RepoObject << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_sync_guid_repoobjectcolumn.adoc[]" as repo.usp_sync_guid_RepoObjectColumn << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_sync_guid_reposchema.adoc[]" as repo.usp_sync_guid_RepoSchema << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_sync_guid_ssas.adoc[]" as repo.usp_sync_guid_ssas << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo_sys.extendedproperties.adoc[]" as repo_sys.ExtendedProperties << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo_sys.foreignkey.adoc[]" as repo_sys.ForeignKey << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo_sys.foreignkeycolumn.adoc[]" as repo_sys.ForeignKeyColumn << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo_sys.index_unique.adoc[]" as repo_sys.Index_unique << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo_sys.indexcolumn_unique.adoc[]" as repo_sys.IndexColumn_unique << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo_sys.repoobjectreferenced.adoc[]" as repo_sys.RepoObjectReferenced << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo_sys.repoobjectreferencing.adoc[]" as repo_sys.RepoObjectReferencing << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo_sys.sql_expression_dependencies.adoc[]" as repo_sys.sql_expression_dependencies << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo_sys.syscolumn.adoc[]" as repo_sys.SysColumn << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo_sys.sysobject.adoc[]" as repo_sys.SysObject << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo_sys.sysschema.adoc[]" as repo_sys.SysSchema << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo_sys.usp_addorupdateextendedproperty.adoc[]" as repo_sys.usp_AddOrUpdateExtendedProperty << P >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.ftv_sqlparse.adoc[]" as sqlparse.ftv_sqlparse << IF >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.ftv_sqlparse_children_pivot.adoc[]" as sqlparse.ftv_sqlparse_children_pivot << IF >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.ftv_sqlparse_with_some_children.adoc[]" as sqlparse.ftv_sqlparse_with_some_children << IF >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules.adoc[]" as sqlparse.RepoObject_SqlModules << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_10_statement.adoc[]" as sqlparse.RepoObject_SqlModules_10_statement << V >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_20_statement_children.adoc[]" as sqlparse.RepoObject_SqlModules_20_statement_children << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **json_key** : (nvarchar(4000))
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_21_statement_children_helper.adoc[]" as sqlparse.RepoObject_SqlModules_21_statement_children_helper << V >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_22_identifier_alias_as.adoc[]" as sqlparse.RepoObject_SqlModules_22_identifier_alias_AS << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **json_key** : (nvarchar(4000))
  **RowNumber** : (bigint)
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_24_identifierlist_children.adoc[]" as sqlparse.RepoObject_SqlModules_24_IdentifierList_children << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **json_key** : (nvarchar(4000))
  - **T2_json_key** : (nvarchar(4000))
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_25_identifierlist_children_identifiersplit.adoc[]" as sqlparse.RepoObject_SqlModules_25_IdentifierList_children_IdentifierSplit << V >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_26_identifierlist_children_identifiersplit_quotename.adoc[]" as sqlparse.RepoObject_SqlModules_26_IdentifierList_children_IdentifierSplit_QuoteName << V >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_29_1_object_is_union.adoc[]" as sqlparse.RepoObject_SqlModules_29_1_object_is_union << V >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_29_2_object_is_groupby.adoc[]" as sqlparse.RepoObject_SqlModules_29_2_object_is_GroupBy << V >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_31_object.adoc[]" as sqlparse.RepoObject_SqlModules_31_object << V >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_32_objectclass.adoc[]" as sqlparse.RepoObject_SqlModules_32_ObjectClass << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  **class** : (nvarchar(500))
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_33_objectnormalized.adoc[]" as sqlparse.RepoObject_SqlModules_33_ObjectNormalized << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  **normalized** : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_39_object.adoc[]" as sqlparse.RepoObject_SqlModules_39_object << V >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_41_from.adoc[]" as sqlparse.RepoObject_SqlModules_41_from << V >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_41_from_t.adoc[]" as sqlparse.RepoObject_SqlModules_41_from_T << U >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_42_from_identifier.adoc[]" as sqlparse.RepoObject_SqlModules_42_from_Identifier << V >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_43_from_identifier.adoc[]" as sqlparse.RepoObject_SqlModules_43_from_Identifier << V >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_44_from_identifier_quotename.adoc[]" as sqlparse.RepoObject_SqlModules_44_from_Identifier_QuoteName << V >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_51_identitfier.adoc[]" as sqlparse.RepoObject_SqlModules_51_Identitfier << V >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_52_identitfier_quotename.adoc[]" as sqlparse.RepoObject_SqlModules_52_Identitfier_QuoteName << V >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_61_selectidentifier_union.adoc[]" as sqlparse.RepoObject_SqlModules_61_SelectIdentifier_Union << V >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_61_selectidentifier_union_t.adoc[]" as sqlparse.RepoObject_SqlModules_61_SelectIdentifier_Union_T << U >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_71_reference_explicitetablealias.adoc[]" as sqlparse.RepoObject_SqlModules_71_reference_ExpliciteTableAlias << V >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_72_reference_notablealias.adoc[]" as sqlparse.RepoObject_SqlModules_72_reference_NoTableAlias << V >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_79_reference_union.adoc[]" as sqlparse.RepoObject_SqlModules_79_reference_union << V >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_repo_sys.adoc[]" as sqlparse.RepoObject_SqlModules_Repo_Sys << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.additional_reference_step1.adoc[]" as ssas.additional_Reference_step1 << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.indexcolumn_from_iskey.adoc[]" as ssas.IndexColumn_from_IsKey << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.indexcolumn_from_isunique.adoc[]" as ssas.IndexColumn_from_IsUnique << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.indexcolumn_from_relationship.adoc[]" as ssas.IndexColumn_from_Relationship << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.indexcolumn_union.adoc[]" as ssas.IndexColumn_union << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.measure_translation.adoc[]" as ssas.Measure_translation << V >> {
  - **Measure_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  **RepoObject_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.measure_translation_t.adoc[]" as ssas.Measure_translation_T << U >> {
  - **Measure_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  - **RepoObject_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json.adoc[]" as ssas.model_json << U >> {
  - **databasename** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_10.adoc[]" as ssas.model_json_10 << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_20.adoc[]" as ssas.model_json_20 << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_201_descriptions_multiline.adoc[]" as ssas.model_json_201_descriptions_multiline << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_2011_descriptions_stragg.adoc[]" as ssas.model_json_2011_descriptions_StrAgg << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31_tables.adoc[]" as ssas.model_json_31_tables << V >> {
  - **databasename** : (nvarchar(128))
  **tables_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31_tables_t.adoc[]" as ssas.model_json_31_tables_T << U >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_311_tables_columns.adoc[]" as ssas.model_json_311_tables_columns << V >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  **tables_columns_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_311_tables_columns_t.adoc[]" as ssas.model_json_311_tables_columns_T << U >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  - **tables_columns_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_3111_tables_columns_descriptions_multiline.adoc[]" as ssas.model_json_3111_tables_columns_descriptions_multiline << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31111_tables_columns_descriptions_stragg.adoc[]" as ssas.model_json_31111_tables_columns_descriptions_StrAgg << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_3112_tables_columns_expressions_multiline.adoc[]" as ssas.model_json_3112_tables_columns_expressions_multiline << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31121_tables_columns_expressions_stragg.adoc[]" as ssas.model_json_31121_tables_columns_expressions_StrAgg << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_312_tables_measures.adoc[]" as ssas.model_json_312_tables_measures << V >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  **tables_measures_name** : (nvarchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_312_tables_measures_t.adoc[]" as ssas.model_json_312_tables_measures_T << U >> {
  - **Measure_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_3121_tables_columns_descriptions_multiline.adoc[]" as ssas.model_json_3121_tables_columns_descriptions_multiline << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31211_tables_columns_descriptions_stragg.adoc[]" as ssas.model_json_31211_tables_columns_descriptions_StrAgg << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_3122_tables_measures_expressions_multiline.adoc[]" as ssas.model_json_3122_tables_measures_expressions_multiline << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31221_tables_measures_expressions_stragg.adoc[]" as ssas.model_json_31221_tables_measures_expressions_StrAgg << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_313_tables_partitions.adoc[]" as ssas.model_json_313_tables_partitions << V >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  **tables_partitions_name** : (nvarchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_3131_tables_partitions_source.adoc[]" as ssas.model_json_3131_tables_partitions_source << V >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  **tables_partitions_name** : (nvarchar(500))
  **tables_partitions_source_name** : (nvarchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31311_tables_partitions_source_posfrom.adoc[]" as ssas.model_json_31311_tables_partitions_source_PosFrom << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_313111_tables_partitions_source_stringfrom.adoc[]" as ssas.model_json_313111_tables_partitions_source_StringFrom << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_3131111_tables_partitions_source_posdot.adoc[]" as ssas.model_json_3131111_tables_partitions_source_PosDot << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31311111_tables_partitions_source_part123.adoc[]" as ssas.model_json_31311111_tables_partitions_source_Part123 << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_316_tables_descriptions_multiline.adoc[]" as ssas.model_json_316_tables_descriptions_multiline << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_3161_tables_descriptions_stragg.adoc[]" as ssas.model_json_3161_tables_descriptions_StrAgg << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_32_relationships.adoc[]" as ssas.model_json_32_relationships << V >> {
  - **databasename** : (nvarchar(128))
  **relationships_name** : (nvarchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_32_relationships_t.adoc[]" as ssas.model_json_32_relationships_T << U >> {
  - **ForeignKey_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_33_datasources.adoc[]" as ssas.model_json_33_dataSources << V >> {
  - **databasename** : (nvarchar(128))
  **dataSources_name** : (nvarchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_33_datasources_t.adoc[]" as ssas.model_json_33_dataSources_T << U >> {
  - **databasename** : (nvarchar(128))
  - **dataSources_name** : (nvarchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_34_cultures.adoc[]" as ssas.model_json_34_cultures << V >> {
  - **databasename** : (nvarchar(128))
  **cultures_name** : (nvarchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_341_cultures_translations.adoc[]" as ssas.model_json_341_cultures_translations << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_3411_cultures_translations_model.adoc[]" as ssas.model_json_3411_cultures_translations_model << V >> {
  - **databasename** : (nvarchar(128))
  **cultures_name** : (nvarchar(500))
  **cultures_translations_model_name** : (nvarchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_3411_cultures_translations_model_t.adoc[]" as ssas.model_json_3411_cultures_translations_model_T << U >> {
  - **databasename** : (nvarchar(128))
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_34111_cultures_translations_model_tables.adoc[]" as ssas.model_json_34111_cultures_translations_model_tables << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_341111_cultures_translations_model_tables_columns.adoc[]" as ssas.model_json_341111_cultures_translations_model_tables_columns << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_341113_cultures_translations_model_tables_measures.adoc[]" as ssas.model_json_341113_cultures_translations_model_tables_measures << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.repoobjectcolumn_translation.adoc[]" as ssas.RepoObjectColumn_translation << V >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:ssas.repoobjectcolumn_translation_t.adoc[]" as ssas.RepoObjectColumn_translation_T << U >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:ssas.usp_persist_measure_translation_t.adoc[]" as ssas.usp_PERSIST_Measure_translation_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.usp_persist_model_json_31_tables_t.adoc[]" as ssas.usp_PERSIST_model_json_31_tables_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.usp_persist_model_json_311_tables_columns_t.adoc[]" as ssas.usp_PERSIST_model_json_311_tables_columns_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.usp_persist_model_json_312_tables_measures_t.adoc[]" as ssas.usp_PERSIST_model_json_312_tables_measures_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.usp_persist_model_json_32_relationships_t.adoc[]" as ssas.usp_PERSIST_model_json_32_relationships_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.usp_persist_model_json_33_datasources_t.adoc[]" as ssas.usp_PERSIST_model_json_33_dataSources_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.usp_persist_model_json_3411_cultures_translations_model_t.adoc[]" as ssas.usp_PERSIST_model_json_3411_cultures_translations_model_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.usp_persist_repoobjectcolumn_translation_t.adoc[]" as ssas.usp_PERSIST_RepoObjectColumn_translation_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.columns.adoc[]" as sys_dwh.columns << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.computed_columns.adoc[]" as sys_dwh.computed_columns << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.default_constraints.adoc[]" as sys_dwh.default_constraints << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.dm_sql_referenced_entities.adoc[]" as sys_dwh.dm_sql_referenced_entities << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.extended_properties.adoc[]" as sys_dwh.extended_properties << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.foreign_key_columns.adoc[]" as sys_dwh.foreign_key_columns << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.foreign_keys.adoc[]" as sys_dwh.foreign_keys << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.identity_columns.adoc[]" as sys_dwh.identity_columns << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.index_columns.adoc[]" as sys_dwh.index_columns << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.indexes.adoc[]" as sys_dwh.indexes << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.objects.adoc[]" as sys_dwh.objects << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.parameters.adoc[]" as sys_dwh.parameters << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.schemas.adoc[]" as sys_dwh.schemas << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.sql_expression_dependencies.adoc[]" as sys_dwh.sql_expression_dependencies << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.sql_modules.adoc[]" as sys_dwh.sql_modules << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.tables.adoc[]" as sys_dwh.tables << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.types.adoc[]" as sys_dwh.types << SN >> {
  --
}

entity "puml-link:dhw:sqldb:tool.ftv_extract_substrings.adoc[]" as tool.ftv_extract_substrings << IF >> {
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.ftv_generatoruspstep_sql.adoc[]" as uspgenerator.ftv_GeneratorUspStep_sql << IF >> {
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.ftv_generatoruspstep_tree.adoc[]" as uspgenerator.ftv_GeneratorUspStep_tree << IF >> {
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.generatorusp.adoc[]" as uspgenerator.GeneratorUsp << U >> {
  - **id** : (int)
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.generatorusp_parameterlist.adoc[]" as uspgenerator.GeneratorUsp_ParameterList << V >> {
  - **usp_id** : (int)
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.generatorusp_sqlusp.adoc[]" as uspgenerator.GeneratorUsp_SqlUsp << V >> {
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.generatorusp_steplist.adoc[]" as uspgenerator.GeneratorUsp_StepList << V >> {
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.generatoruspparameter.adoc[]" as uspgenerator.GeneratorUspParameter << U >> {
  - **id** : (int)
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.generatoruspstep.adoc[]" as uspgenerator.GeneratorUspStep << U >> {
  - **id** : (int)
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.generatoruspstep_persistence_isinactive_setpoint.adoc[]" as uspgenerator.GeneratorUspStep_Persistence_IsInactive_setpoint << V >> {
  - **usp_id** : (int)
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.generatoruspstep_persistence_src.adoc[]" as uspgenerator.GeneratorUspStep_Persistence_src << V >> {
  - **usp_id** : (int)
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.generatoruspstep_sql.adoc[]" as uspgenerator.GeneratorUspStep_Sql << V >> {
  - **usp_id** : (int)
  **Number** : (int)
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.usp_generatorusp_insert_update_persistence.adoc[]" as uspgenerator.usp_GeneratorUsp_insert_update_persistence << P >> {
  --
}

config.fs_dwh_database_name <.. repo_sys.usp_AddOrUpdateExtendedProperty
config.fs_get_parameter_value <.. repo.usp_sync_guid_RepoObjectColumn
config.fs_get_parameter_value <.. repo.usp_main
config.fs_get_parameter_value <.. repo.usp_sync_guid_RepoObject
config.fs_get_parameter_value <.. repo.usp_sync_guid_RepoSchema
config.fs_get_parameter_value <.. repo.usp_RepoObjectColumn_update_RepoObjectColumn_column_id
config.ftv_dwh_database <.. repo_sys.ExtendedProperties
config.ftv_dwh_database <.. repo_sys.SysColumn
config.ftv_dwh_database <.. repo_sys.sql_expression_dependencies
config.ftv_dwh_database <.. uspgenerator.GeneratorUsp_SqlUsp
config.ftv_dwh_database <.. reference.usp_update_Referencing_Count
config.ftv_dwh_database <.. reference.RepoObjectColumn_reference_QueryPlan
config.ftv_get_parameter_value <.. repo.RepoObject_external_src
config.ftv_get_parameter_value <.. repo.RepoObjectColumn_HistValidColums_setpoint
config.ftv_get_parameter_value <.. repo.RepoObject_ColumnList
config.ftv_get_parameter_value <.. repo.RepoObject_gross
config.ftv_get_parameter_value <.. ssas.additional_Reference_step1
config.ftv_get_parameter_value <.. reference.additional_Reference_is_external
config.Parameter <.. property.PropertyName_RepoObjectColumn
config.Parameter <.. property.RepoObjectProperty_InheritanceType_InheritanceDefinition
config.Parameter <.. property.RepoObjectColumnProperty_InheritanceType_InheritanceDefinition
config.Parameter <.. config.fs_dwh_database_name
config.Parameter <.. config.usp_init_parameter
config.Parameter <.. config.ftv_dwh_database
config.Parameter <.. property.PropertyName_RepoObject
config.Parameter <.. config.fs_get_parameter_value
config.Parameter <.. config.ftv_get_parameter_value
config.usp_init_parameter <.. repo.usp_sync_guid
config.usp_init_parameter <.. repo.usp_main
configT.join_type <.. sqlparse.RepoObject_SqlModules_41_from
configT.Parameter_default <.. config.usp_init_parameter
configT.Parameter_default <.. config.Parameter
configT.spt_values <.. configT.type
configT.type <.. repo.RepoObject_gross_persistence
configT.type <.. reference.RepoObject_ReferencedReferencing
configT.type <.. configT.type_level1type_level2type
configT.type <.. repo.RepoObject_gross
configT.type_level1type_level2type <.. repo.usp_sync_guid_RepoObject
configT.type_level1type_level2type <.. repo.usp_sync_guid_RepoObjectColumn
docs.Culture <.. ssas.RepoObjectColumn_translation
docs.Culture <.. ssas.Measure_translation
docs.fs_cleanStringForAnchorId <.. reference.RepoObjectColumn_ReferencedReferencing
docs.fs_cleanStringForFilename <.. repo.RepoObject_gross
docs.fs_cleanStringForFilename <.. repo.RepoObject_gross_persistence
docs.fs_cleanStringForFilename <.. reference.RepoObjectColumn_ReferencedReferencing
docs.fs_cleanStringForFilename <.. reference.RepoObject_ReferencedReferencing
logs.ExecutionLog <.. logs.usp_ExecutionLog_insert
logs.usp_ExecutionLog_insert <.. property.usp_PERSIST_PropertyName_Measure_T
logs.usp_ExecutionLog_insert <.. repo.usp_PERSIST_IndexColumn_union_T
logs.usp_ExecutionLog_insert <.. repo.usp_PERSIST_Index_ColumList_T
logs.usp_ExecutionLog_insert <.. ssas.usp_PERSIST_model_json_311_tables_columns_T
logs.usp_ExecutionLog_insert <.. ssas.usp_PERSIST_model_json_32_relationships_T
logs.usp_ExecutionLog_insert <.. reference.usp_RepoObject_ReferenceTree_insert
logs.usp_ExecutionLog_insert <.. ssas.usp_PERSIST_model_json_312_tables_measures_T
logs.usp_ExecutionLog_insert <.. property.usp_PERSIST_PropertyName_RepoObject_T
logs.usp_ExecutionLog_insert <.. reference.usp_PERSIST_additional_Reference_database_T
logs.usp_ExecutionLog_insert <.. reference.usp_PERSIST_additional_Reference_Object_T
logs.usp_ExecutionLog_insert <.. reference.usp_PERSIST_additional_Reference_ObjectColumn_T
logs.usp_ExecutionLog_insert <.. reference.usp_PERSIST_RepoObjectColumn_reference_T
logs.usp_ExecutionLog_insert <.. repo.usp_PERSIST_RepoObject_SSAS_tgt
logs.usp_ExecutionLog_insert <.. repo.usp_PERSIST_RepoObjectColumn_SSAS_tgt
logs.usp_ExecutionLog_insert <.. repo.usp_sync_guid_ssas
logs.usp_ExecutionLog_insert <.. repo.usp_PERSIST_RepoSchema_ssas_tgt
logs.usp_ExecutionLog_insert <.. repo.usp_PERSIST_IndexColumn_ssas_T
logs.usp_ExecutionLog_insert <.. repo.usp_PERSIST_Index_ssas_T
logs.usp_ExecutionLog_insert <.. ssas.usp_PERSIST_model_json_31_tables_T
logs.usp_ExecutionLog_insert <.. repo.usp_PERSIST_RepoObject_external_tgt
logs.usp_ExecutionLog_insert <.. property.usp_PERSIST_PropertyName_RepoObjectColumn_T
logs.usp_ExecutionLog_insert <.. reference.usp_additional_Reference
logs.usp_ExecutionLog_insert <.. repo.usp_PERSIST_RepoObjectColumn_external_tgt
logs.usp_ExecutionLog_insert <.. property.usp_PERSIST_RepoObjectColumnProperty_external_tgt
logs.usp_ExecutionLog_insert <.. property.usp_PERSIST_RepoObjectProperty_external_tgt
logs.usp_ExecutionLog_insert <.. property.usp_external_property_import
logs.usp_ExecutionLog_insert <.. reference.usp_PERSIST_additional_Reference_from_properties_tgt
logs.usp_ExecutionLog_insert <.. reference.usp_PERSIST_additional_Reference_wo_columns_from_properties_tgt
logs.usp_ExecutionLog_insert <.. ssas.usp_PERSIST_model_json_33_dataSources_T
logs.usp_ExecutionLog_insert <.. reference.usp_PERSIST_additional_Reference_from_ssas_tgt
logs.usp_ExecutionLog_insert <.. ssas.usp_PERSIST_model_json_3411_cultures_translations_model_T
logs.usp_ExecutionLog_insert <.. ssas.usp_PERSIST_Measure_translation_T
logs.usp_ExecutionLog_insert <.. ssas.usp_PERSIST_RepoObjectColumn_translation_T
logs.usp_ExecutionLog_insert <.. repo.usp_PERSIST_RepoObject_sat2_T
logs.usp_ExecutionLog_insert <.. repo.usp_main
logs.usp_ExecutionLog_insert <.. property.usp_RepoObjectColumn_Inheritance
logs.usp_ExecutionLog_insert <.. repo.usp_PERSIST_IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T
logs.usp_ExecutionLog_insert <.. repo.usp_Index_finish
logs.usp_ExecutionLog_insert <.. repo.usp_Index_ForeignKey
logs.usp_ExecutionLog_insert <.. repo.usp_sync_guid_RepoObjectColumn
logs.usp_ExecutionLog_insert <.. repo.usp_sync_guid
logs.usp_ExecutionLog_insert <.. uspgenerator.usp_GeneratorUsp_insert_update_persistence
logs.usp_ExecutionLog_insert <.. repo.usp_sync_guid_RepoObject
logs.usp_ExecutionLog_insert <.. repo.usp_Index_virtual_set
logs.usp_ExecutionLog_insert <.. repo.usp_index_inheritance
logs.usp_ExecutionLog_insert <.. repo.usp_sync_guid_RepoSchema
logs.usp_ExecutionLog_insert <.. reference.usp_PERSIST_RepoObject_reference_T
logs.usp_ExecutionLog_insert <.. repo.usp_PERSIST_ForeignKey_Indexes_union_T
logs.usp_ExecutionLog_insert <.. property.usp_RepoObject_Inheritance
logs.usp_ExecutionLog_insert <.. property.usp_RepoObjectProperty_collect
logs.usp_ExecutionLog_insert <.. repo.usp_Index_Settings
logs.usp_ExecutionLog_insert <.. reference.usp_RepoObject_update_SysObjectQueryPlan
logs.usp_ExecutionLog_insert <.. repo.usp_RepoObjectColumn_update_RepoObjectColumn_column_id
logs.usp_ExecutionLog_insert <.. reference.usp_RepoObjectSource_FirstResultSet
logs.usp_ExecutionLog_insert <.. reference.usp_update_Referencing_Count
logs.usp_ExecutionLog_insert <.. reference.usp_RepoObjectSource_QueryPlan
property.external_RepoObjectColumnProperty <.. property.RepoObjectColumnProperty_external_src
property.external_RepoObjectColumnProperty <.. property.usp_external_property_import
property.external_RepoObjectProperty <.. property.usp_external_property_import
property.external_RepoObjectProperty <.. property.RepoObjectProperty_external_src
property.fs_get_RepoObjectColumnProperty_nvarchar <.. repo.RepoObjectColumn_gross
property.fs_get_RepoObjectProperty_nvarchar <.. repo.RepoObject_gross
property.MeasureProperty <.. property.PropertyName_Measure
property.PropertyName_Measure <.. property.PropertyName_Measure_T
property.PropertyName_Measure <.. property.usp_PERSIST_PropertyName_Measure_T
property.PropertyName_Measure_T <.. property.usp_PERSIST_PropertyName_Measure_T
property.PropertyName_RepoObject <.. property.PropertyName_RepoObject_T
property.PropertyName_RepoObject <.. property.usp_PERSIST_PropertyName_RepoObject_T
property.PropertyName_RepoObject_T <.. property.usp_PERSIST_PropertyName_RepoObject_T
property.PropertyName_RepoObject_T <.. property.RepoObjectProperty_InheritanceType_InheritanceDefinition
property.PropertyName_RepoObject_T <.. property.RepoObjectColumnProperty_external_tgt
property.PropertyName_RepoObject_T <.. property.RepoObjectProperty_external_tgt
property.PropertyName_RepoObjectColumn <.. property.usp_PERSIST_PropertyName_RepoObjectColumn_T
property.PropertyName_RepoObjectColumn <.. property.PropertyName_RepoObjectColumn_T
property.PropertyName_RepoObjectColumn_T <.. property.RepoObjectColumnProperty_InheritanceType_InheritanceDefinition
property.PropertyName_RepoObjectColumn_T <.. property.usp_PERSIST_PropertyName_RepoObjectColumn_T
property.RepoObject_Inheritance_temp <.. property.usp_RepoObject_Inheritance
property.RepoObjectColumn_Inheritance_temp <.. property.usp_RepoObjectColumn_Inheritance
property.RepoObjectColumnProperty <.. property.RepoObjectColumnProperty_InheritanceType_InheritanceDefinition
property.RepoObjectColumnProperty <.. property.usp_RepoObjectColumn_Inheritance
property.RepoObjectColumnProperty <.. property.PropertyName_RepoObjectColumn
property.RepoObjectColumnProperty <.. property.fs_get_RepoObjectColumnProperty_nvarchar
property.RepoObjectColumnProperty_external_src <.. property.RepoObjectColumnProperty_external_tgt
property.RepoObjectColumnProperty_external_src <.. property.usp_PERSIST_RepoObjectColumnProperty_external_tgt
property.RepoObjectColumnProperty_external_tgt <.. property.usp_PERSIST_RepoObjectColumnProperty_external_tgt
property.RepoObjectColumnProperty_external_tgt <.. property.RepoObjectColumnProperty
property.RepoObjectColumnProperty_InheritanceType_InheritanceDefinition <.. property.RepoObjectColumnProperty_InheritanceType_resulting_InheritanceDefinition
property.RepoObjectColumnProperty_InheritanceType_resulting_InheritanceDefinition <.. property.usp_RepoObjectColumn_Inheritance
property.RepoObjectProperty <.. property.fs_get_RepoObjectProperty_nvarchar
property.RepoObjectProperty <.. property.RepoObjectProperty_SelectedPropertyName_split
property.RepoObjectProperty <.. property.PropertyName_RepoObject
property.RepoObjectProperty <.. property.usp_RepoObjectProperty_collect
property.RepoObjectProperty <.. property.RepoObjectProperty_InheritanceType_InheritanceDefinition
property.RepoObjectProperty <.. property.usp_RepoObject_Inheritance
property.RepoObjectProperty_Collect_source_ROGross <.. property.usp_RepoObjectProperty_collect
property.RepoObjectProperty_Collect_source_sql_modules_definition <.. property.usp_RepoObjectProperty_collect
property.RepoObjectProperty_Collect_source_uspgenerator <.. property.usp_RepoObjectProperty_collect
property.RepoObjectProperty_external_src <.. property.usp_PERSIST_RepoObjectProperty_external_tgt
property.RepoObjectProperty_external_src <.. property.RepoObjectProperty_external_tgt
property.RepoObjectProperty_external_tgt <.. property.usp_PERSIST_RepoObjectProperty_external_tgt
property.RepoObjectProperty_external_tgt <.. property.RepoObjectProperty
property.RepoObjectProperty_InheritanceType_InheritanceDefinition <.. property.RepoObjectProperty_InheritanceType_resulting_InheritanceDefinition
property.RepoObjectProperty_InheritanceType_resulting_InheritanceDefinition <.. property.usp_RepoObject_Inheritance
property.RepoObjectProperty_SelectedPropertyName_split <.. reference.additional_Reference_wo_columns_from_properties_src
property.RepoObjectProperty_SelectedPropertyName_split <.. reference.additional_Reference_from_properties_src
property.usp_external_property_import <.. repo.usp_main
property.usp_PERSIST_PropertyName_Measure_T <.. repo.usp_main
property.usp_PERSIST_PropertyName_RepoObject_T <.. property.usp_RepoObject_Inheritance
property.usp_PERSIST_PropertyName_RepoObjectColumn_T <.. property.usp_RepoObjectColumn_Inheritance
property.usp_PERSIST_RepoObjectColumnProperty_external_tgt <.. property.usp_external_property_import
property.usp_PERSIST_RepoObjectProperty_external_tgt <.. property.usp_external_property_import
property.usp_RepoObject_Inheritance <.. repo.usp_main
property.usp_RepoObjectColumn_Inheritance <.. repo.usp_main
property.usp_RepoObjectProperty_collect <.. repo.usp_main
property.usp_RepoObjectProperty_collect <.. property.usp_RepoObject_Inheritance
reference.additional_Reference <.. reference.additional_Reference_guid
reference.additional_Reference <.. reference.additional_Reference_is_external
reference.additional_Reference_database <.. reference.usp_PERSIST_additional_Reference_database_T
reference.additional_Reference_database <.. reference.additional_Reference_database_T
reference.additional_Reference_database_T <.. reference.usp_PERSIST_additional_Reference_database_T
reference.additional_Reference_database_T <.. repo.RepoObject_gross
reference.additional_Reference_database_T <.. property.usp_external_property_import
reference.additional_Reference_from_properties_src <.. reference.usp_PERSIST_additional_Reference_from_properties_tgt
reference.additional_Reference_from_properties_src <.. reference.additional_Reference_from_properties_tgt
reference.additional_Reference_from_properties_tgt <.. reference.additional_Reference
reference.additional_Reference_from_properties_tgt <.. reference.usp_PERSIST_additional_Reference_from_properties_tgt
reference.additional_Reference_from_ssas_src <.. reference.usp_PERSIST_additional_Reference_from_ssas_tgt
reference.additional_Reference_from_ssas_src <.. reference.additional_Reference_from_ssas_tgt
reference.additional_Reference_from_ssas_tgt <.. reference.additional_Reference
reference.additional_Reference_from_ssas_tgt <.. reference.usp_PERSIST_additional_Reference_from_ssas_tgt
reference.additional_Reference_guid <.. reference.RepoObject_reference_additional
reference.additional_Reference_guid <.. reference.RepoObjectColumn_reference_additional
reference.additional_Reference_is_external <.. reference.additional_Reference_ObjectColumn
reference.additional_Reference_is_external <.. reference.additional_Reference_database
reference.additional_Reference_is_external <.. reference.additional_Reference_Object
reference.additional_Reference_Object <.. reference.usp_PERSIST_additional_Reference_Object_T
reference.additional_Reference_Object <.. reference.additional_Reference_Object_T
reference.additional_Reference_Object_T <.. repo.RepoObject_external_src
reference.additional_Reference_Object_T <.. repo.RepoObjectColumn_external_src
reference.additional_Reference_Object_T <.. reference.usp_PERSIST_additional_Reference_Object_T
reference.additional_Reference_ObjectColumn <.. reference.usp_PERSIST_additional_Reference_ObjectColumn_T
reference.additional_Reference_ObjectColumn <.. reference.additional_Reference_ObjectColumn_T
reference.additional_Reference_ObjectColumn_T <.. repo.RepoObjectColumn_external_src
reference.additional_Reference_ObjectColumn_T <.. reference.usp_PERSIST_additional_Reference_ObjectColumn_T
reference.additional_Reference_wo_columns_from_properties_src <.. reference.usp_PERSIST_additional_Reference_wo_columns_from_properties_tgt
reference.additional_Reference_wo_columns_from_properties_src <.. reference.additional_Reference_wo_columns_from_properties_tgt
reference.additional_Reference_wo_columns_from_properties_tgt <.. reference.additional_Reference
reference.additional_Reference_wo_columns_from_properties_tgt <.. reference.usp_PERSIST_additional_Reference_wo_columns_from_properties_tgt
reference.ftv_query_plan_extract_source <.. reference.usp_RepoObjectSource_QueryPlan
reference.RepoObject_QueryPlan <.. reference.usp_RepoObject_update_SysObjectQueryPlan
reference.RepoObject_QueryPlan <.. repo.RepoObject_gross
reference.RepoObject_reference <.. reference.RepoObject_reference_T
reference.RepoObject_reference <.. reference.usp_PERSIST_RepoObject_reference_T
reference.RepoObject_reference_additional <.. reference.RepoObject_reference_union
reference.RepoObject_reference_persistence <.. repo.usp_main
reference.RepoObject_reference_persistence <.. reference.RepoObject_reference_union
reference.RepoObject_reference_persistence_target_as_source <.. reference.RepoObject_reference_union
reference.RepoObject_reference_persistence_target_as_source <.. reference.RepoObject_reference
reference.RepoObject_reference_persistence_target_as_source <.. repo.usp_main
reference.RepoObject_reference_persistence_target_as_source_explicit <.. reference.RepoObject_reference_union
reference.RepoObject_reference_persistence_target_as_source_explicit <.. reference.RepoObject_reference
reference.RepoObject_reference_SqlExpressionDependencies <.. reference.RepoObject_reference_persistence_target_as_source_explicit
reference.RepoObject_reference_SqlExpressionDependencies <.. reference.RepoObject_reference_persistence_target_as_source
reference.RepoObject_reference_SqlExpressionDependencies <.. reference.RepoObject_reference_union
reference.RepoObject_reference_T <.. reference.usp_PERSIST_RepoObject_reference_T
reference.RepoObject_reference_T <.. repo.usp_main
reference.RepoObject_reference_T <.. repo.IndexReferencedReferencing
reference.RepoObject_reference_T <.. reference.RepoObjectColumn_reference_QueryPlan
reference.RepoObject_reference_T <.. reference.RepoObjectColumn_reference_SqlExpressionDependencies
reference.RepoObject_reference_T <.. reference.RepoObjectColumn_reference_additional
reference.RepoObject_reference_T <.. reference.RepoObjectColumn_reference_virtual
reference.RepoObject_reference_T <.. reference.RepoObject_ReferencedReferencing
reference.RepoObject_reference_union <.. reference.RepoObject_reference
reference.RepoObject_reference_virtual <.. reference.RepoObject_reference_union
reference.RepoObject_ReferencedList <.. repo.RepoObject_gross2
reference.RepoObject_ReferencedList <.. repo.RepoObject_sat2
reference.RepoObject_ReferencedReferencing <.. reference.usp_RepoObject_ReferenceTree_insert
reference.RepoObject_ReferencedReferencing <.. reference.RepoObject_ReferencingList
reference.RepoObject_ReferencedReferencing <.. reference.RepoObject_ReferencedList
reference.RepoObject_ReferencedReferencing <.. repo.RepoObject_gross
reference.RepoObject_ReferenceTree <.. reference.usp_RepoObject_ReferenceTree_insert
reference.RepoObject_ReferencingList <.. repo.RepoObject_sat2
reference.RepoObject_ReferencingList <.. repo.RepoObject_gross2
reference.RepoObjectColumn_reference <.. reference.RepoObjectColumn_reference_T
reference.RepoObjectColumn_reference <.. reference.usp_PERSIST_RepoObjectColumn_reference_T
reference.RepoObjectColumn_reference_additional <.. reference.RepoObjectColumn_reference_union
reference.RepoObjectColumn_reference_Persistence <.. reference.RepoObjectColumn_reference_union
reference.RepoObjectColumn_reference_QueryPlan <.. reference.SysObjectColumn_QueryPlanExpression
reference.RepoObjectColumn_reference_SqlExpressionDependencies <.. reference.RepoObjectColumn_reference_union
reference.RepoObjectColumn_reference_SqlModules <.. reference.RepoObjectColumn_reference_union
reference.RepoObjectColumn_reference_T <.. reference.usp_PERSIST_RepoObjectColumn_reference_T
reference.RepoObjectColumn_reference_T <.. reference.RepoObjectColumn_ReferencedReferencing
reference.RepoObjectColumn_reference_T <.. repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing
reference.RepoObjectColumn_reference_union <.. reference.RepoObjectColumn_reference
reference.RepoObjectColumn_reference_virtual <.. reference.RepoObjectColumn_reference_union
reference.RepoObjectColumn_ReferencedList <.. repo.RepoObjectColumn_gross2
reference.RepoObjectColumn_ReferencedReferencing <.. reference.RepoObjectColumn_ReferencingList
reference.RepoObjectColumn_ReferencedReferencing <.. reference.RepoObjectColumn_ReferencedList
reference.RepoObjectColumn_ReferencingList <.. repo.RepoObjectColumn_gross2
reference.RepoObjectColumnSource_virtual <.. repo.usp_sync_guid_RepoObjectColumn
reference.RepoObjectColumnSource_virtual <.. reference.RepoObjectColumn_reference_virtual
reference.RepoObjectSource_FirstResultSet <.. reference.usp_RepoObjectSource_FirstResultSet
reference.RepoObjectSource_QueryPlan <.. reference.usp_RepoObjectSource_QueryPlan
reference.RepoObjectSource_QueryPlan <.. reference.RepoObjectColumn_reference_QueryPlan
reference.RepoObjectSource_virtual <.. reference.RepoObject_reference_virtual
reference.RepoObjectSource_virtual <.. repo.usp_sync_guid_RepoObject
reference.SysObjectColumn_QueryPlanExpression <.. reference.usp_RepoObjectSource_QueryPlan
reference.usp_additional_Reference <.. repo.usp_main
reference.usp_additional_Reference <.. property.usp_external_property_import
reference.usp_PERSIST_additional_Reference_database_T <.. reference.usp_additional_Reference
reference.usp_PERSIST_additional_Reference_from_properties_tgt <.. repo.usp_main
reference.usp_PERSIST_additional_Reference_from_ssas_tgt <.. repo.usp_main
reference.usp_PERSIST_additional_Reference_Object_T <.. reference.usp_additional_Reference
reference.usp_PERSIST_additional_Reference_ObjectColumn_T <.. reference.usp_additional_Reference
reference.usp_PERSIST_additional_Reference_wo_columns_from_properties_tgt <.. repo.usp_main
reference.usp_PERSIST_RepoObject_reference_T <.. repo.usp_main
reference.usp_PERSIST_RepoObjectColumn_reference_T <.. repo.usp_main
reference.usp_RepoObject_ReferenceTree_insert <.. repo.usp_main
reference.usp_RepoObject_update_SysObjectQueryPlan <.. repo.usp_main
reference.usp_RepoObjectSource_FirstResultSet <.. repo.usp_main
reference.usp_RepoObjectSource_QueryPlan <.. repo.usp_main
reference.usp_update_Referencing_Count <.. repo.usp_main
repo.ForeignKey_Indexes <.. repo.usp_Index_ForeignKey
repo.ForeignKey_Indexes <.. repo.ForeignKey_Indexes_union
repo.ForeignKey_Indexes_union <.. repo.usp_PERSIST_ForeignKey_Indexes_union_T
repo.ForeignKey_Indexes_union <.. repo.ForeignKey_Indexes_union_T
repo.ForeignKey_Indexes_union_T <.. repo.usp_Index_finish
repo.ForeignKey_Indexes_union_T <.. repo.usp_PERSIST_ForeignKey_Indexes_union_T
repo.ForeignKey_IndexPattern <.. repo.ForeignKey_Indexes
repo.ForeignKey_ssas_Indexes <.. repo.ForeignKey_Indexes_union
repo.ForeignKey_ssas_IndexPattern <.. repo.ForeignKey_ssas_Indexes
repo.ForeignKey_virtual <.. repo.ForeignKey_virtual_Indexes
repo.ForeignKey_virtual_Indexes <.. repo.ForeignKey_Indexes_union
repo.Index_ColumList <.. repo.usp_PERSIST_Index_ColumList_T
repo.Index_ColumList <.. repo.Index_ColumList_T
repo.Index_ColumList_T <.. repo.Index_gross
repo.Index_ColumList_T <.. uspgenerator.GeneratorUspStep_Persistence_src
repo.Index_ColumList_T <.. repo.usp_PERSIST_Index_ColumList_T
repo.Index_gross <.. repo.usp_Index_virtual_set
repo.Index_gross <.. repo.usp_index_inheritance
repo.Index_gross <.. repo.usp_Index_finish
repo.Index_gross <.. repo.ForeignKey_virtual_Indexes
repo.Index_gross <.. repo.ForeignKey_Indexes
repo.Index_IndexPattern <.. repo.usp_Index_Settings
repo.Index_referencing_IndexPatternColumnGuid <.. repo.IndexReferencedReferencing_HasFullColumnsInReferencing
repo.Index_Settings <.. repo.usp_Index_virtual_set
repo.Index_Settings <.. repo.Index_virtual_ForUpdate
repo.Index_Settings <.. repo.usp_Index_finish
repo.Index_Settings <.. repo.usp_Index_Settings
repo.Index_Settings <.. repo.Index_gross
repo.Index_Settings <.. repo.RepoObject_gross
repo.Index_ssas <.. repo.usp_PERSIST_Index_ssas_T
repo.Index_ssas <.. repo.Index_ssas_T
repo.Index_ssas_IndexPatternColumnGuid <.. repo.Index_union
repo.Index_ssas_T <.. repo.usp_PERSIST_Index_ssas_T
repo.Index_ssas_T <.. repo.Index_union
repo.Index_ssas_T <.. repo.IndexColumn_ssas
repo.Index_ssas_T <.. repo.IndexColumn_ssas_gross
repo.Index_ssas_T <.. repo.Index_ssas_IndexPatternColumnGuid
repo.Index_ssas_T <.. repo.ForeignKey_ssas_Indexes
repo.Index_union <.. repo.Index_gross
repo.Index_union <.. repo.usp_Index_finish
repo.Index_union <.. repo.IndexReferencedReferencing
repo.Index_unique_IndexPatternColumnGuid <.. repo.Index_union
repo.Index_virtual <.. repo.IndexColumn_virtual_gross
repo.Index_virtual <.. repo.Index_union
repo.Index_virtual <.. repo.Index_virtual_IndexPatternColumnGuid
repo.Index_virtual <.. repo.IndexReferencedReferencing
repo.Index_virtual <.. repo.IndexColumn_virtual_referenced_setpoint
repo.Index_virtual <.. repo.usp_index_inheritance
repo.Index_virtual <.. repo.usp_Index_finish
repo.Index_virtual <.. repo.usp_Index_virtual_set
repo.Index_virtual <.. repo.Index_virtual_ForUpdate
repo.Index_virtual_ForUpdate <.. repo.usp_index_inheritance
repo.Index_virtual_IndexPatternColumnGuid <.. repo.Index_union
repo.Index_virtual_IndexPatternColumnGuid <.. repo.usp_index_inheritance
repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing <.. repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T
repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing <.. repo.usp_PERSIST_IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T
repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T <.. repo.IndexColumn_virtual_referenced_setpoint
repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T <.. repo.IndexReferencedReferencing_HasFullColumnsInReferencing
repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T <.. repo.usp_PERSIST_IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T
repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T <.. repo.Index_referencing_IndexPatternColumnGuid
repo.IndexColumn_ssas <.. repo.usp_PERSIST_IndexColumn_ssas_T
repo.IndexColumn_ssas <.. repo.IndexColumn_ssas_T
repo.IndexColumn_ssas_gross <.. repo.IndexColumn_union
repo.IndexColumn_ssas_T <.. repo.usp_PERSIST_IndexColumn_ssas_T
repo.IndexColumn_ssas_T <.. repo.Index_ssas_IndexPatternColumnGuid
repo.IndexColumn_ssas_T <.. repo.IndexColumn_ssas_gross
repo.IndexColumn_union <.. repo.usp_PERSIST_IndexColumn_union_T
repo.IndexColumn_union <.. repo.IndexColumn_union_T
repo.IndexColumn_union_T <.. repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing
repo.IndexColumn_union_T <.. repo.usp_PERSIST_IndexColumn_union_T
repo.IndexColumn_union_T <.. repo.Index_IndexPattern
repo.IndexColumn_union_T <.. repo.RepoObjectColumn_gross2
repo.IndexColumn_union_T <.. repo.Index_ColumList
repo.IndexColumn_virtual <.. repo.IndexColumn_virtual_gross
repo.IndexColumn_virtual <.. repo.usp_sync_guid_RepoObjectColumn
repo.IndexColumn_virtual <.. repo.usp_Index_finish
repo.IndexColumn_virtual <.. repo.usp_Index_virtual_set
repo.IndexColumn_virtual <.. repo.Index_virtual_IndexPatternColumnGuid
repo.IndexColumn_virtual <.. repo.usp_index_inheritance
repo.IndexColumn_virtual_gross <.. repo.IndexColumn_union
repo.IndexColumn_virtual_referenced_setpoint <.. repo.usp_index_inheritance
repo.IndexReferencedReferencing <.. repo.IndexReferencedReferencing_HasFullColumnsInReferencing
repo.IndexReferencedReferencing_HasFullColumnsInReferencing <.. repo.usp_index_inheritance
repo.Measure <.. repo.Measure_union
repo.Measure_union <.. ssas.Measure_translation
repo.RepoObject <.. repo.Index_virtual_ForUpdate
repo.RepoObject <.. reference.RepoObject_reference_persistence
repo.RepoObject <.. repo.SysColumn_RepoObjectColumn_via_name
repo.RepoObject <.. repo.SysObject_RepoObject_via_name
repo.RepoObject <.. sqlparse.RepoObject_SqlModules_39_object
repo.RepoObject <.. sqlparse.RepoObject_SqlModules_10_statement
repo.RepoObject <.. reference.RepoObjectColumn_reference_Persistence
repo.RepoObject <.. repo_sys.Index_unique
repo.RepoObject <.. repo.IndexColumn_virtual_gross
repo.RepoObject <.. reference.RepoObject_reference_persistence_target_as_source_explicit
repo.RepoObject <.. repo.RepoObject_gross_persistence
repo.RepoObject <.. repo.RepoObjectColumn_external_src
repo.RepoObject <.. property.RepoObjectColumnProperty_external_tgt
repo.RepoObject <.. repo.IndexColumn_ssas_gross
repo.RepoObject <.. property.RepoObjectProperty_external_tgt
repo.RepoObject <.. repo.RepoObject_external_src
repo.RepoObject <.. reference.additional_Reference_guid
repo.RepoObject <.. reference.RepoObject_reference_virtual
repo.RepoObject <.. repo.RepoObjectColumn_gross
repo.RepoObject <.. repo.SysColumn_RepoObjectColumn_via_guid
repo.RepoObject <.. reference.RepoObjectColumn_reference_QueryPlan
repo.RepoObject <.. repo.SysObject_RepoObject_via_guid
repo.RepoObject <.. sqlparse.RepoObject_SqlModules_Repo_Sys
repo.RepoObject <.. repo_sys.RepoObjectReferenced
repo.RepoObject <.. repo_sys.RepoObjectReferencing
repo.RepoObject <.. uspgenerator.GeneratorUsp_SqlUsp
repo.RepoObject <.. reference.RepoObject_reference_SqlExpressionDependencies
repo.RepoObject <.. repo.usp_main
repo.RepoObject <.. property.RepoObjectProperty_InheritanceType_InheritanceDefinition
repo.RepoObject <.. repo.usp_Index_finish
repo.RepoObject <.. repo_sys.ForeignKey
repo.RepoObject <.. repo.usp_sync_guid_RepoObjectColumn
repo.RepoObject <.. repo.usp_sync_guid_RepoObject
repo.RepoObject <.. repo.RepoObject_RequiredRepoObjectMerge
repo.RepoObject <.. repo.usp_Index_virtual_set
repo.RepoObject <.. reference.usp_RepoObject_update_SysObjectQueryPlan
repo.RepoObject <.. reference.usp_RepoObjectSource_FirstResultSet
repo.RepoObject <.. reference.usp_update_Referencing_Count
repo.RepoObject <.. reference.usp_RepoObjectSource_QueryPlan
repo.RepoObject <.. reference.RepoObjectColumn_reference_SqlModules
repo.RepoObject <.. sqlparse.RepoObject_SqlModules_72_reference_NoTableAlias
repo.RepoObject <.. sqlparse.RepoObject_SqlModules_71_reference_ExpliciteTableAlias
repo.RepoObject <.. repo.RepoObject_gross
repo.RepoObject_ColumnList <.. repo.RepoObject_gross2
repo.RepoObject_ColumnList <.. repo.RepoObject_sat2
repo.RepoObject_external_src <.. repo.usp_PERSIST_RepoObject_external_tgt
repo.RepoObject_external_src <.. repo.RepoObject_external_tgt
repo.RepoObject_external_tgt <.. repo.RepoObject
repo.RepoObject_external_tgt <.. repo.usp_PERSIST_RepoObject_external_tgt
repo.RepoObject_external_tgt <.. repo.RepoObjectColumn_external_tgt
repo.RepoObject_gross <.. repo.Index_gross
repo.RepoObject_gross <.. uspgenerator.GeneratorUspStep_Persistence_IsInactive_setpoint
repo.RepoObject_gross <.. uspgenerator.GeneratorUspStep_Persistence_src
repo.RepoObject_gross <.. reference.usp_RepoObjectSource_FirstResultSet
repo.RepoObject_gross <.. reference.usp_RepoObjectSource_QueryPlan
repo.RepoObject_gross <.. uspgenerator.usp_GeneratorUsp_insert_update_persistence
repo.RepoObject_gross <.. repo.Index_virtual_ForUpdate
repo.RepoObject_gross <.. property.RepoObjectProperty_Collect_source_ROGross
repo.RepoObject_gross <.. reference.usp_RepoObject_update_SysObjectQueryPlan
repo.RepoObject_gross <.. repo.RepoObject_gross2
repo.RepoObject_gross <.. repo.RepoObject_sat2
repo.RepoObject_gross_persistence <.. reference.RepoObject_reference_persistence_target_as_source
repo.RepoObject_gross2 <.. uspgenerator.GeneratorUspStep_Persistence_src
repo.RepoObject_persistence <.. repo.RepoObject_persistence_source_Ignore
repo.RepoObject_persistence <.. repo.RepoObject_persistence_target_Ignore
repo.RepoObject_persistence <.. repo.RepoObject_persistence_NoCompareNoUpdate
repo.RepoObject_persistence <.. repo.RepoObject_persistence_NoCompareButUpdate
repo.RepoObject_persistence <.. repo.usp_Index_finish
repo.RepoObject_persistence <.. repo.usp_main
repo.RepoObject_persistence <.. repo.usp_sync_guid_RepoObjectColumn
repo.RepoObject_persistence <.. repo.usp_sync_guid_RepoObject
repo.RepoObject_persistence <.. repo.RepoObject_ColumnList
repo.RepoObject_persistence <.. repo.RepoObject_gross
repo.RepoObject_persistence <.. repo.RepoObjectColumn_HistValidColums_setpoint
repo.RepoObject_persistence <.. reference.RepoObjectColumn_reference_Persistence
repo.RepoObject_persistence <.. repo.RepoObjectColumn_gross
repo.RepoObject_persistence <.. reference.RepoObject_reference_persistence
repo.RepoObject_persistence <.. reference.RepoObject_reference_persistence_target_as_source_explicit
repo.RepoObject_persistence <.. repo.RepoObject_gross_persistence
repo.RepoObject_persistence_NoCompareButUpdate <.. repo.usp_sync_guid_RepoObjectColumn
repo.RepoObject_persistence_NoCompareNoUpdate <.. repo.usp_sync_guid_RepoObjectColumn
repo.RepoObject_persistence_source_Ignore <.. repo.usp_sync_guid_RepoObjectColumn
repo.RepoObject_persistence_target_Ignore <.. repo.usp_sync_guid_RepoObjectColumn
repo.RepoObject_RequiredRepoObjectMerge <.. repo.usp_sync_guid_RepoObject
repo.RepoObject_sat2 <.. repo.RepoObject_sat2_T
repo.RepoObject_sat2 <.. repo.usp_PERSIST_RepoObject_sat2_T
repo.RepoObject_sat2_T <.. property.RepoObjectProperty_Collect_source_ROGross
repo.RepoObject_sat2_T <.. repo.usp_PERSIST_RepoObject_sat2_T
repo.RepoObject_SSAS_src <.. repo.RepoObject_SSAS_tgt
repo.RepoObject_SSAS_src <.. repo.usp_PERSIST_RepoObject_SSAS_tgt
repo.RepoObject_SSAS_tgt <.. repo.usp_PERSIST_RepoObject_SSAS_tgt
repo.RepoObject_SSAS_tgt <.. repo.RepoObjectColumn_SSAS_tgt
repo.RepoObject_SSAS_tgt <.. repo.RepoObject
repo.RepoObjectColumn <.. repo.RepoObject_persistence_source_Ignore
repo.RepoObjectColumn <.. repo.RepoObject_persistence_target_Ignore
repo.RepoObjectColumn <.. repo.RepoObject_persistence_NoCompareNoUpdate
repo.RepoObjectColumn <.. repo.RepoObject_persistence_NoCompareButUpdate
repo.RepoObjectColumn <.. reference.RepoObjectColumn_reference_Persistence
repo.RepoObjectColumn <.. repo.IndexColumn_virtual_gross
repo.RepoObjectColumn <.. repo.SysColumn_RepoObjectColumn_via_name
repo.RepoObjectColumn <.. repo.RepoObjectColumn_gross
repo.RepoObjectColumn <.. repo.SysColumn_RepoObjectColumn_via_guid
repo.RepoObjectColumn <.. repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing
repo.RepoObjectColumn <.. sqlparse.RepoObject_SqlModules_71_reference_ExpliciteTableAlias
repo.RepoObjectColumn <.. repo.RepoObjectColumn_RequiredRepoObjectColumnMerge
repo.RepoObjectColumn <.. property.RepoObjectColumnProperty_InheritanceType_InheritanceDefinition
repo.RepoObjectColumn <.. repo.usp_sync_guid_RepoObjectColumn
repo.RepoObjectColumn <.. repo.usp_Index_virtual_set
repo.RepoObjectColumn <.. reference.usp_update_Referencing_Count
repo.RepoObjectColumn <.. reference.usp_RepoObjectSource_QueryPlan
repo.RepoObjectColumn <.. repo.RepoObjectColumn_gross2
repo.RepoObjectColumn <.. property.RepoObjectColumnProperty_external_tgt
repo.RepoObjectColumn <.. reference.RepoObjectColumn_reference_SqlModules
repo.RepoObjectColumn <.. sqlparse.RepoObject_SqlModules_72_reference_NoTableAlias
repo.RepoObjectColumn <.. repo.IndexColumn_ssas_gross
repo.RepoObjectColumn <.. reference.additional_Reference_guid
repo.RepoObjectColumn_external_src <.. repo.RepoObjectColumn_external_tgt
repo.RepoObjectColumn_external_src <.. repo.usp_PERSIST_RepoObjectColumn_external_tgt
repo.RepoObjectColumn_external_tgt <.. repo.usp_PERSIST_RepoObjectColumn_external_tgt
repo.RepoObjectColumn_external_tgt <.. repo.RepoObjectColumn
repo.RepoObjectColumn_gross <.. repo.usp_sync_guid_RepoObjectColumn
repo.RepoObjectColumn_gross <.. reference.RepoObjectColumn_reference_QueryPlan
repo.RepoObjectColumn_gross <.. ssas.RepoObjectColumn_translation
repo.RepoObjectColumn_gross <.. repo.RepoObjectColumn_gross2
repo.RepoObjectColumn_gross <.. reference.RepoObjectColumn_reference_virtual
repo.RepoObjectColumn_gross2 <.. uspgenerator.usp_GeneratorUsp_insert_update_persistence
repo.RepoObjectColumn_gross2 <.. repo.RepoObject_ColumnList
repo.RepoObjectColumn_HistValidColums_setpoint <.. repo.usp_sync_guid_RepoObjectColumn
repo.RepoObjectColumn_RequiredRepoObjectColumnMerge <.. repo.usp_sync_guid_RepoObjectColumn
repo.RepoObjectColumn_SSAS_src <.. repo.RepoObjectColumn_SSAS_tgt
repo.RepoObjectColumn_SSAS_src <.. repo.usp_PERSIST_RepoObjectColumn_SSAS_tgt
repo.RepoObjectColumn_SSAS_tgt <.. repo.usp_PERSIST_RepoObjectColumn_SSAS_tgt
repo.RepoObjectColumn_SSAS_tgt <.. repo.RepoObjectColumn
repo.RepoSchema <.. repo.usp_sync_guid_RepoSchema
repo.RepoSchema <.. repo.SysSchema_RepoSchema_via_guid
repo.RepoSchema <.. repo.SysSchema_RepoSchema_via_name
repo.RepoSchema <.. repo.Measure
repo.RepoSchema <.. repo.RepoObject_SSAS_src
repo.RepoSchema_ssas_src <.. repo.RepoSchema_ssas_tgt
repo.RepoSchema_ssas_src <.. repo.usp_PERSIST_RepoSchema_ssas_tgt
repo.RepoSchema_ssas_tgt <.. repo.usp_PERSIST_RepoSchema_ssas_tgt
repo.RepoSchema_ssas_tgt <.. repo.RepoSchema
repo.SysColumn_RepoObjectColumn_via_guid <.. repo.usp_sync_guid_RepoObjectColumn
repo.SysColumn_RepoObjectColumn_via_name <.. repo.usp_sync_guid_RepoObjectColumn
repo.SysColumn_RepoObjectColumn_via_name <.. repo_sys.sql_expression_dependencies
repo.SysColumn_RepoObjectColumn_via_name <.. repo_sys.IndexColumn_unique
repo.SysObject_RepoObject_via_guid <.. repo.usp_sync_guid_RepoObject
repo.SysObject_RepoObject_via_name <.. repo.usp_sync_guid_RepoObject
repo.SysObject_RepoObject_via_name <.. repo_sys.IndexColumn_unique
repo.SysObject_RepoObject_via_name <.. repo_sys.sql_expression_dependencies
repo.SysSchema_RepoSchema_via_guid <.. repo.usp_sync_guid_RepoSchema
repo.SysSchema_RepoSchema_via_name <.. repo.usp_sync_guid_RepoSchema
repo.usp_Index_finish <.. repo.usp_index_inheritance
repo.usp_Index_finish <.. repo.usp_Index_ForeignKey
repo.usp_Index_ForeignKey <.. repo.usp_main
repo.usp_index_inheritance <.. repo.usp_main
repo.usp_Index_Settings <.. repo.usp_Index_finish
repo.usp_Index_virtual_set <.. repo.usp_Index_ForeignKey
repo.usp_PERSIST_ForeignKey_Indexes_union_T <.. repo.usp_Index_ForeignKey
repo.usp_PERSIST_Index_ColumList_T <.. repo.usp_Index_finish
repo.usp_PERSIST_Index_ssas_T <.. repo.usp_sync_guid_ssas
repo.usp_PERSIST_IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T <.. repo.usp_index_inheritance
repo.usp_PERSIST_IndexColumn_ssas_T <.. repo.usp_sync_guid_ssas
repo.usp_PERSIST_IndexColumn_union_T <.. repo.usp_Index_finish
repo.usp_PERSIST_RepoObject_external_tgt <.. reference.usp_additional_Reference
repo.usp_PERSIST_RepoObject_sat2_T <.. repo.usp_main
repo.usp_PERSIST_RepoObject_SSAS_tgt <.. repo.usp_sync_guid_ssas
repo.usp_PERSIST_RepoObjectColumn_external_tgt <.. reference.usp_additional_Reference
repo.usp_PERSIST_RepoObjectColumn_SSAS_tgt <.. repo.usp_sync_guid_ssas
repo.usp_PERSIST_RepoSchema_ssas_tgt <.. repo.usp_sync_guid_ssas
repo.usp_RepoObjectColumn_update_RepoObjectColumn_column_id <.. repo.usp_main
repo.usp_sync_guid <.. repo.usp_main
repo.usp_sync_guid_RepoObject <.. repo.usp_sync_guid
repo.usp_sync_guid_RepoObjectColumn <.. repo.usp_sync_guid
repo.usp_sync_guid_RepoSchema <.. repo.usp_sync_guid
repo.usp_sync_guid_ssas <.. repo.usp_main
repo_sys.ExtendedProperties <.. repo_sys.SysObject
repo_sys.ExtendedProperties <.. repo_sys.SysSchema
repo_sys.ExtendedProperties <.. repo_sys.SysColumn
repo_sys.ForeignKey <.. repo.ForeignKey_IndexPattern
repo_sys.ForeignKey <.. repo_sys.ForeignKeyColumn
repo_sys.ForeignKeyColumn <.. repo.ForeignKey_IndexPattern
repo_sys.Index_unique <.. repo.Index_union
repo_sys.IndexColumn_unique <.. repo.IndexColumn_union
repo_sys.IndexColumn_unique <.. repo.Index_unique_IndexPatternColumnGuid
repo_sys.RepoObjectReferenced <.. reference.usp_update_Referencing_Count
repo_sys.RepoObjectReferencing <.. reference.usp_update_Referencing_Count
repo_sys.sql_expression_dependencies <.. reference.RepoObjectColumn_reference_SqlExpressionDependencies
repo_sys.sql_expression_dependencies <.. reference.RepoObject_reference_SqlExpressionDependencies
repo_sys.SysColumn <.. repo.SysColumn_RepoObjectColumn_via_name
repo_sys.SysColumn <.. repo_sys.ForeignKeyColumn
repo_sys.SysColumn <.. repo.SysColumn_RepoObjectColumn_via_guid
repo_sys.SysColumn <.. repo.usp_sync_guid_RepoObjectColumn
repo_sys.SysObject <.. repo.usp_sync_guid_RepoObject
repo_sys.SysObject <.. repo.SysObject_RepoObject_via_guid
repo_sys.SysObject <.. sqlparse.RepoObject_SqlModules_Repo_Sys
repo_sys.SysObject <.. repo_sys.SysColumn
repo_sys.SysObject <.. repo.SysObject_RepoObject_via_name
repo_sys.SysSchema <.. repo.usp_sync_guid_RepoSchema
repo_sys.SysSchema <.. repo.SysSchema_RepoSchema_via_guid
repo_sys.SysSchema <.. repo.SysSchema_RepoSchema_via_name
repo_sys.usp_AddOrUpdateExtendedProperty <.. repo.usp_sync_guid_RepoSchema
repo_sys.usp_AddOrUpdateExtendedProperty <.. repo.usp_sync_guid_RepoObjectColumn
repo_sys.usp_AddOrUpdateExtendedProperty <.. repo.usp_sync_guid_RepoObject
sqlparse.ftv_sqlparse <.. sqlparse.RepoObject_SqlModules_22_identifier_alias_AS
sqlparse.ftv_sqlparse_children_pivot <.. sqlparse.RepoObject_SqlModules_25_IdentifierList_children_IdentifierSplit
sqlparse.ftv_sqlparse_with_some_children <.. sqlparse.RepoObject_SqlModules_24_IdentifierList_children
sqlparse.ftv_sqlparse_with_some_children <.. sqlparse.RepoObject_SqlModules_20_statement_children
sqlparse.RepoObject_SqlModules <.. sqlparse.RepoObject_SqlModules_Repo_Sys
sqlparse.RepoObject_SqlModules <.. sqlparse.RepoObject_SqlModules_39_object
sqlparse.RepoObject_SqlModules <.. sqlparse.RepoObject_SqlModules_10_statement
sqlparse.RepoObject_SqlModules_10_statement <.. sqlparse.RepoObject_SqlModules_20_statement_children
sqlparse.RepoObject_SqlModules_20_statement_children <.. sqlparse.RepoObject_SqlModules_32_ObjectClass
sqlparse.RepoObject_SqlModules_20_statement_children <.. sqlparse.RepoObject_SqlModules_29_2_object_is_GroupBy
sqlparse.RepoObject_SqlModules_20_statement_children <.. sqlparse.RepoObject_SqlModules_21_statement_children_helper
sqlparse.RepoObject_SqlModules_20_statement_children <.. sqlparse.RepoObject_SqlModules_29_1_object_is_union
sqlparse.RepoObject_SqlModules_20_statement_children <.. sqlparse.RepoObject_SqlModules_51_Identitfier
sqlparse.RepoObject_SqlModules_20_statement_children <.. sqlparse.RepoObject_SqlModules_33_ObjectNormalized
sqlparse.RepoObject_SqlModules_20_statement_children <.. sqlparse.RepoObject_SqlModules_22_identifier_alias_AS
sqlparse.RepoObject_SqlModules_20_statement_children <.. sqlparse.RepoObject_SqlModules_24_IdentifierList_children
sqlparse.RepoObject_SqlModules_20_statement_children <.. sqlparse.RepoObject_SqlModules_41_from
sqlparse.RepoObject_SqlModules_21_statement_children_helper <.. sqlparse.RepoObject_SqlModules_31_object
sqlparse.RepoObject_SqlModules_22_identifier_alias_AS <.. sqlparse.RepoObject_SqlModules_41_from
sqlparse.RepoObject_SqlModules_24_IdentifierList_children <.. sqlparse.RepoObject_SqlModules_25_IdentifierList_children_IdentifierSplit
sqlparse.RepoObject_SqlModules_25_IdentifierList_children_IdentifierSplit <.. sqlparse.RepoObject_SqlModules_26_IdentifierList_children_IdentifierSplit_QuoteName
sqlparse.RepoObject_SqlModules_26_IdentifierList_children_IdentifierSplit_QuoteName <.. sqlparse.RepoObject_SqlModules_61_SelectIdentifier_Union
sqlparse.RepoObject_SqlModules_29_1_object_is_union <.. sqlparse.RepoObject_SqlModules_39_object
sqlparse.RepoObject_SqlModules_29_1_object_is_union <.. sqlparse.RepoObject_SqlModules_42_from_Identifier
sqlparse.RepoObject_SqlModules_29_2_object_is_GroupBy <.. sqlparse.RepoObject_SqlModules_39_object
sqlparse.RepoObject_SqlModules_31_object <.. sqlparse.RepoObject_SqlModules_39_object
sqlparse.RepoObject_SqlModules_32_ObjectClass <.. sqlparse.RepoObject_SqlModules_39_object
sqlparse.RepoObject_SqlModules_33_ObjectNormalized <.. sqlparse.RepoObject_SqlModules_39_object
sqlparse.RepoObject_SqlModules_39_object <.. sqlparse.RepoObject_SqlModules_61_SelectIdentifier_Union
sqlparse.RepoObject_SqlModules_39_object <.. sqlparse.RepoObject_SqlModules_41_from
sqlparse.RepoObject_SqlModules_41_from <.. sqlparse.RepoObject_SqlModules_41_from_T
sqlparse.RepoObject_SqlModules_41_from_T <.. sqlparse.RepoObject_SqlModules_42_from_Identifier
sqlparse.RepoObject_SqlModules_42_from_Identifier <.. sqlparse.RepoObject_SqlModules_43_from_Identifier
sqlparse.RepoObject_SqlModules_43_from_Identifier <.. sqlparse.RepoObject_SqlModules_44_from_Identifier_QuoteName
sqlparse.RepoObject_SqlModules_44_from_Identifier_QuoteName <.. sqlparse.RepoObject_SqlModules_71_reference_ExpliciteTableAlias
sqlparse.RepoObject_SqlModules_44_from_Identifier_QuoteName <.. sqlparse.RepoObject_SqlModules_72_reference_NoTableAlias
sqlparse.RepoObject_SqlModules_51_Identitfier <.. sqlparse.RepoObject_SqlModules_52_Identitfier_QuoteName
sqlparse.RepoObject_SqlModules_52_Identitfier_QuoteName <.. sqlparse.RepoObject_SqlModules_61_SelectIdentifier_Union
sqlparse.RepoObject_SqlModules_61_SelectIdentifier_Union <.. sqlparse.RepoObject_SqlModules_61_SelectIdentifier_Union_T
sqlparse.RepoObject_SqlModules_61_SelectIdentifier_Union_T <.. sqlparse.RepoObject_SqlModules_72_reference_NoTableAlias
sqlparse.RepoObject_SqlModules_61_SelectIdentifier_Union_T <.. sqlparse.RepoObject_SqlModules_71_reference_ExpliciteTableAlias
sqlparse.RepoObject_SqlModules_71_reference_ExpliciteTableAlias <.. sqlparse.RepoObject_SqlModules_79_reference_union
sqlparse.RepoObject_SqlModules_72_reference_NoTableAlias <.. sqlparse.RepoObject_SqlModules_79_reference_union
sqlparse.RepoObject_SqlModules_79_reference_union <.. reference.RepoObjectColumn_reference_SqlModules
sqlparse.RepoObject_SqlModules_Repo_Sys <.. property.RepoObjectProperty_Collect_source_sql_modules_definition
sqlparse.RepoObject_SqlModules_Repo_Sys <.. repo.RepoObject_gross2
sqlparse.RepoObject_SqlModules_Repo_Sys <.. repo.RepoObject_sat2
ssas.additional_Reference_step1 <.. reference.additional_Reference_from_ssas_src
ssas.IndexColumn_from_IsKey <.. ssas.IndexColumn_union
ssas.IndexColumn_from_IsUnique <.. ssas.IndexColumn_union
ssas.IndexColumn_from_Relationship <.. ssas.IndexColumn_union
ssas.IndexColumn_union <.. repo.Index_ssas
ssas.IndexColumn_union <.. repo.IndexColumn_ssas
ssas.Measure_translation <.. ssas.Measure_translation_T
ssas.Measure_translation <.. ssas.usp_PERSIST_Measure_translation_T
ssas.Measure_translation_T <.. ssas.usp_PERSIST_Measure_translation_T
ssas.model_json <.. ssas.model_json_10
ssas.model_json_10 <.. ssas.model_json_20
ssas.model_json_20 <.. repo.RepoSchema_ssas_src
ssas.model_json_20 <.. ssas.model_json_33_dataSources
ssas.model_json_20 <.. ssas.model_json_31_tables
ssas.model_json_20 <.. ssas.model_json_201_descriptions_multiline
ssas.model_json_20 <.. ssas.model_json_32_relationships
ssas.model_json_20 <.. ssas.model_json_34_cultures
ssas.model_json_201_descriptions_multiline <.. ssas.model_json_2011_descriptions_StrAgg
ssas.model_json_2011_descriptions_StrAgg <.. repo.RepoSchema_ssas_src
ssas.model_json_31_tables <.. ssas.usp_PERSIST_model_json_31_tables_T
ssas.model_json_31_tables <.. ssas.model_json_31_tables_T
ssas.model_json_31_tables_T <.. repo.RepoObject_gross
ssas.model_json_31_tables_T <.. ssas.model_json_316_tables_descriptions_multiline
ssas.model_json_31_tables_T <.. repo.ForeignKey_ssas_IndexPattern
ssas.model_json_31_tables_T <.. ssas.model_json_312_tables_measures
ssas.model_json_31_tables_T <.. ssas.model_json_313_tables_partitions
ssas.model_json_31_tables_T <.. ssas.model_json_311_tables_columns
ssas.model_json_31_tables_T <.. repo.RepoObject_SSAS_src
ssas.model_json_31_tables_T <.. ssas.usp_PERSIST_model_json_31_tables_T
ssas.model_json_311_tables_columns <.. ssas.usp_PERSIST_model_json_311_tables_columns_T
ssas.model_json_311_tables_columns <.. ssas.model_json_311_tables_columns_T
ssas.model_json_311_tables_columns_T <.. repo.RepoObjectColumn_SSAS_src
ssas.model_json_311_tables_columns_T <.. ssas.usp_PERSIST_model_json_311_tables_columns_T
ssas.model_json_311_tables_columns_T <.. ssas.model_json_3111_tables_columns_descriptions_multiline
ssas.model_json_311_tables_columns_T <.. ssas.model_json_3112_tables_columns_expressions_multiline
ssas.model_json_311_tables_columns_T <.. repo.ForeignKey_ssas_IndexPattern
ssas.model_json_311_tables_columns_T <.. ssas.RepoObjectColumn_translation
ssas.model_json_311_tables_columns_T <.. repo.RepoObjectColumn_gross
ssas.model_json_311_tables_columns_T <.. ssas.IndexColumn_from_IsUnique
ssas.model_json_311_tables_columns_T <.. ssas.IndexColumn_from_Relationship
ssas.model_json_311_tables_columns_T <.. ssas.IndexColumn_from_IsKey
ssas.model_json_311_tables_columns_T <.. ssas.additional_Reference_step1
ssas.model_json_3111_tables_columns_descriptions_multiline <.. ssas.model_json_31111_tables_columns_descriptions_StrAgg
ssas.model_json_31111_tables_columns_descriptions_StrAgg <.. repo.RepoObjectColumn_gross
ssas.model_json_3112_tables_columns_expressions_multiline <.. ssas.model_json_31121_tables_columns_expressions_StrAgg
ssas.model_json_31121_tables_columns_expressions_StrAgg <.. repo.RepoObjectColumn_gross
ssas.model_json_312_tables_measures <.. ssas.usp_PERSIST_model_json_312_tables_measures_T
ssas.model_json_312_tables_measures <.. ssas.model_json_312_tables_measures_T
ssas.model_json_312_tables_measures_T <.. repo.Measure
ssas.model_json_312_tables_measures_T <.. ssas.model_json_3121_tables_columns_descriptions_multiline
ssas.model_json_312_tables_measures_T <.. ssas.usp_PERSIST_model_json_312_tables_measures_T
ssas.model_json_312_tables_measures_T <.. ssas.model_json_3122_tables_measures_expressions_multiline
ssas.model_json_3121_tables_columns_descriptions_multiline <.. ssas.model_json_31211_tables_columns_descriptions_StrAgg
ssas.model_json_31211_tables_columns_descriptions_StrAgg <.. repo.Measure
ssas.model_json_3122_tables_measures_expressions_multiline <.. ssas.model_json_31221_tables_measures_expressions_StrAgg
ssas.model_json_31221_tables_measures_expressions_StrAgg <.. repo.Measure
ssas.model_json_313_tables_partitions <.. ssas.model_json_3131_tables_partitions_source
ssas.model_json_3131_tables_partitions_source <.. ssas.model_json_31311_tables_partitions_source_PosFrom
ssas.model_json_31311_tables_partitions_source_PosFrom <.. ssas.model_json_313111_tables_partitions_source_StringFrom
ssas.model_json_313111_tables_partitions_source_StringFrom <.. ssas.model_json_3131111_tables_partitions_source_PosDot
ssas.model_json_3131111_tables_partitions_source_PosDot <.. ssas.model_json_31311111_tables_partitions_source_Part123
ssas.model_json_31311111_tables_partitions_source_Part123 <.. ssas.additional_Reference_step1
ssas.model_json_316_tables_descriptions_multiline <.. ssas.model_json_3161_tables_descriptions_StrAgg
ssas.model_json_3161_tables_descriptions_StrAgg <.. repo.RepoObject_gross
ssas.model_json_32_relationships <.. ssas.usp_PERSIST_model_json_32_relationships_T
ssas.model_json_32_relationships <.. ssas.model_json_32_relationships_T
ssas.model_json_32_relationships_T <.. ssas.IndexColumn_from_Relationship
ssas.model_json_32_relationships_T <.. ssas.usp_PERSIST_model_json_32_relationships_T
ssas.model_json_32_relationships_T <.. repo.ForeignKey_ssas_IndexPattern
ssas.model_json_33_dataSources <.. ssas.usp_PERSIST_model_json_33_dataSources_T
ssas.model_json_33_dataSources <.. ssas.model_json_33_dataSources_T
ssas.model_json_33_dataSources_T <.. ssas.usp_PERSIST_model_json_33_dataSources_T
ssas.model_json_33_dataSources_T <.. ssas.additional_Reference_step1
ssas.model_json_34_cultures <.. ssas.model_json_341_cultures_translations
ssas.model_json_341_cultures_translations <.. ssas.model_json_3411_cultures_translations_model
ssas.model_json_3411_cultures_translations_model <.. ssas.model_json_3411_cultures_translations_model_T
ssas.model_json_3411_cultures_translations_model <.. ssas.usp_PERSIST_model_json_3411_cultures_translations_model_T
ssas.model_json_3411_cultures_translations_model_T <.. docs.Culture
ssas.model_json_3411_cultures_translations_model_T <.. ssas.usp_PERSIST_model_json_3411_cultures_translations_model_T
ssas.model_json_3411_cultures_translations_model_T <.. ssas.model_json_34111_cultures_translations_model_tables
ssas.model_json_34111_cultures_translations_model_tables <.. ssas.model_json_341111_cultures_translations_model_tables_columns
ssas.model_json_34111_cultures_translations_model_tables <.. ssas.model_json_341113_cultures_translations_model_tables_measures
ssas.model_json_341111_cultures_translations_model_tables_columns <.. ssas.RepoObjectColumn_translation
ssas.model_json_341113_cultures_translations_model_tables_measures <.. ssas.Measure_translation
ssas.RepoObjectColumn_translation <.. ssas.usp_PERSIST_RepoObjectColumn_translation_T
ssas.RepoObjectColumn_translation <.. ssas.RepoObjectColumn_translation_T
ssas.RepoObjectColumn_translation_T <.. ssas.usp_PERSIST_RepoObjectColumn_translation_T
ssas.usp_PERSIST_Measure_translation_T <.. repo.usp_sync_guid_ssas
ssas.usp_PERSIST_model_json_31_tables_T <.. repo.usp_sync_guid_ssas
ssas.usp_PERSIST_model_json_311_tables_columns_T <.. repo.usp_sync_guid_ssas
ssas.usp_PERSIST_model_json_312_tables_measures_T <.. repo.usp_sync_guid_ssas
ssas.usp_PERSIST_model_json_32_relationships_T <.. repo.usp_sync_guid_ssas
ssas.usp_PERSIST_model_json_33_dataSources_T <.. repo.usp_sync_guid_ssas
ssas.usp_PERSIST_model_json_3411_cultures_translations_model_T <.. repo.usp_sync_guid_ssas
ssas.usp_PERSIST_RepoObjectColumn_translation_T <.. repo.usp_main
sys_dwh.columns <.. repo_sys.SysColumn
sys_dwh.columns <.. repo_sys.ExtendedProperties
sys_dwh.computed_columns <.. repo_sys.SysColumn
sys_dwh.default_constraints <.. repo_sys.SysColumn
sys_dwh.dm_sql_referenced_entities <.. repo_sys.RepoObjectReferenced
sys_dwh.extended_properties <.. repo_sys.ExtendedProperties
sys_dwh.foreign_key_columns <.. repo_sys.ForeignKeyColumn
sys_dwh.foreign_keys <.. repo_sys.ForeignKey
sys_dwh.identity_columns <.. repo_sys.SysColumn
sys_dwh.index_columns <.. repo_sys.IndexColumn_unique
sys_dwh.indexes <.. repo_sys.Index_unique
sys_dwh.indexes <.. repo_sys.IndexColumn_unique
sys_dwh.indexes <.. repo_sys.ExtendedProperties
sys_dwh.objects <.. repo_sys.ExtendedProperties
sys_dwh.objects <.. repo_sys.SysObject
sys_dwh.parameters <.. repo_sys.ExtendedProperties
sys_dwh.schemas <.. repo_sys.ExtendedProperties
sys_dwh.schemas <.. repo_sys.SysObject
sys_dwh.schemas <.. repo_sys.SysSchema
sys_dwh.sql_expression_dependencies <.. repo_sys.sql_expression_dependencies
sys_dwh.sql_modules <.. repo_sys.SysObject
sys_dwh.tables <.. repo_sys.SysObject
sys_dwh.types <.. repo_sys.SysColumn
tool.ftv_extract_substrings <.. property.RepoObjectProperty_Collect_source_sql_modules_definition
uspgenerator.ftv_GeneratorUspStep_sql <.. uspgenerator.GeneratorUspStep_Sql
uspgenerator.ftv_GeneratorUspStep_tree <.. uspgenerator.GeneratorUspStep_Sql
uspgenerator.GeneratorUsp <.. uspgenerator.usp_GeneratorUsp_insert_update_persistence
uspgenerator.GeneratorUsp <.. uspgenerator.GeneratorUspStep_Persistence_IsInactive_setpoint
uspgenerator.GeneratorUsp <.. uspgenerator.GeneratorUspStep_Persistence_src
uspgenerator.GeneratorUsp <.. uspgenerator.GeneratorUsp_SqlUsp
uspgenerator.GeneratorUsp <.. uspgenerator.GeneratorUspStep_Sql
uspgenerator.GeneratorUsp <.. repo.RepoObject_gross
uspgenerator.GeneratorUsp_ParameterList <.. uspgenerator.GeneratorUsp_SqlUsp
uspgenerator.GeneratorUsp_SqlUsp <.. property.RepoObjectProperty_Collect_source_uspgenerator
uspgenerator.GeneratorUsp_StepList <.. uspgenerator.GeneratorUsp_SqlUsp
uspgenerator.GeneratorUspParameter <.. uspgenerator.GeneratorUsp_ParameterList
uspgenerator.GeneratorUspStep <.. uspgenerator.ftv_GeneratorUspStep_tree
uspgenerator.GeneratorUspStep <.. uspgenerator.GeneratorUspStep_Sql
uspgenerator.GeneratorUspStep <.. uspgenerator.ftv_GeneratorUspStep_sql
uspgenerator.GeneratorUspStep <.. uspgenerator.usp_GeneratorUsp_insert_update_persistence
uspgenerator.GeneratorUspStep_Persistence_IsInactive_setpoint <.. uspgenerator.usp_GeneratorUsp_insert_update_persistence
uspgenerator.GeneratorUspStep_Persistence_src <.. uspgenerator.usp_GeneratorUsp_insert_update_persistence
uspgenerator.GeneratorUspStep_Sql <.. uspgenerator.GeneratorUsp_StepList
uspgenerator.usp_GeneratorUsp_insert_update_persistence <.. repo.usp_main

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_30_0_objectref[]

=== PlantUML 0 30 ObjectRef

// tag::puml_entity_0_30_objectref[]
[plantuml, entity_0_30_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:repo.usp_main.adoc[]" as repo.usp_main << P >> {
  --
}



footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_0_30_objectref[]

=== PlantUML 1 1 ColumnRef

// tag::puml_entity_1_1_colref[]
[plantuml, entity_1_1_colref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:config.fs_get_parameter_value.adoc[]" as config.fs_get_parameter_value << FN >> {
  --
}

entity "puml-link:dhw:sqldb:config.usp_init_parameter.adoc[]" as config.usp_init_parameter << P >> {
  --
}

entity "puml-link:dhw:sqldb:logs.usp_executionlog_insert.adoc[]" as logs.usp_ExecutionLog_insert << P >> {
  --
}

entity "puml-link:dhw:sqldb:property.usp_external_property_import.adoc[]" as property.usp_external_property_import << P >> {
  --
}

entity "puml-link:dhw:sqldb:property.usp_persist_propertyname_measure_t.adoc[]" as property.usp_PERSIST_PropertyName_Measure_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:property.usp_repoobject_inheritance.adoc[]" as property.usp_RepoObject_Inheritance << P >> {
  --
}

entity "puml-link:dhw:sqldb:property.usp_repoobjectcolumn_inheritance.adoc[]" as property.usp_RepoObjectColumn_Inheritance << P >> {
  --
}

entity "puml-link:dhw:sqldb:property.usp_repoobjectproperty_collect.adoc[]" as property.usp_RepoObjectProperty_collect << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_reference_persistence.adoc[]" as reference.RepoObject_reference_persistence << V >> {
  **referenced_RepoObject_guid** : (uniqueidentifier)
  - **referencing_RepoObject_guid** : (uniqueidentifier)
  - InformationSource : (varchar(27))
  - referenced_entity_name : (nvarchar(128))
  - referenced_fullname : (nvarchar(261))
  referenced_id : (int)
  - referenced_schema_name : (nvarchar(128))
  referenced_type : (char(2))
  - referencing_entity_name : (nvarchar(128))
  - referencing_fullname : (nvarchar(261))
  referencing_id : (int)
  - referencing_schema_name : (nvarchar(128))
  referencing_type : (varchar(2))
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_reference_persistence_target_as_source.adoc[]" as reference.RepoObject_reference_persistence_target_as_source << V >> {
  - has_match_left_and_suffix_tgt : (int)
  - InformationSource : (varchar(28))
  referenced_entity_name : (nvarchar(128))
  referenced_fullname : (nvarchar(517))
  - referenced_id : (int)
  referenced_RepoObject_guid : (uniqueidentifier)
  referenced_schema_name : (nvarchar(128))
  referenced_type : (char(2))
  referencing_entity_name : (nvarchar(128))
  referencing_fullname : (nvarchar(517))
  referencing_id : (int)
  referencing_RepoObject_guid : (uniqueidentifier)
  referencing_schema_name : (nvarchar(128))
  referencing_type : (char(2))
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_reference_t.adoc[]" as reference.RepoObject_reference_T << U >> {
  - **referenced_RepoObject_guid** : (uniqueidentifier)
  - **referencing_RepoObject_guid** : (uniqueidentifier)
  - is_ReversePersistenceViaView : (bit)
  referenced_entity_name : (nvarchar(128))
  referenced_external_AntoraComponent : (nvarchar(128))
  referenced_external_AntoraModule : (nvarchar(128))
  - referenced_is_external : (bit)
  - referenced_is_PersistenceSource : (bit)
  - referenced_is_PersistenceTarget : (bit)
  referenced_schema_name : (nvarchar(128))
  referenced_type : (char(2))
  referencing_entity_name : (nvarchar(128))
  referencing_external_AntoraComponent : (nvarchar(128))
  referencing_external_AntoraModule : (nvarchar(128))
  - referencing_is_external : (bit)
  - referencing_is_PersistenceTarget : (bit)
  - referencing_is_PersistenceUspSourceRef : (bit)
  referencing_is_PersistenceUspTargetRef : (bit)
  referencing_schema_name : (nvarchar(128))
  referencing_type : (varchar(2))
  ~ referenced_AntoraComponent : (nvarchar(max))
  ~ referenced_AntoraModule : (nvarchar(max))
  # referenced_fullname : (nvarchar(261))
  # referenced_fullname2 : (nvarchar(257))
  ~ referenced_puml_entity : (nvarchar(4000))
  ~ referencing_AntoraComponent : (nvarchar(max))
  ~ referencing_AntoraModule : (nvarchar(max))
  # referencing_fullname : (nvarchar(261))
  # referencing_fullname2 : (nvarchar(257))
  ~ referencing_puml_entity : (nvarchar(4000))
  --
}

entity "puml-link:dhw:sqldb:reference.usp_additional_reference.adoc[]" as reference.usp_additional_Reference << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_persist_additional_reference_from_properties_tgt.adoc[]" as reference.usp_PERSIST_additional_Reference_from_properties_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_persist_additional_reference_from_ssas_tgt.adoc[]" as reference.usp_PERSIST_additional_Reference_from_ssas_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_persist_additional_reference_wo_columns_from_properties_tgt.adoc[]" as reference.usp_PERSIST_additional_Reference_wo_columns_from_properties_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_persist_repoobject_reference_t.adoc[]" as reference.usp_PERSIST_RepoObject_reference_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_persist_repoobjectcolumn_reference_t.adoc[]" as reference.usp_PERSIST_RepoObjectColumn_reference_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_repoobject_referencetree_insert.adoc[]" as reference.usp_RepoObject_ReferenceTree_insert << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_repoobject_update_sysobjectqueryplan.adoc[]" as reference.usp_RepoObject_update_SysObjectQueryPlan << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_repoobjectsource_firstresultset.adoc[]" as reference.usp_RepoObjectSource_FirstResultSet << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_repoobjectsource_queryplan.adoc[]" as reference.usp_RepoObjectSource_QueryPlan << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_update_referencing_count.adoc[]" as reference.usp_update_Referencing_Count << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject.adoc[]" as repo.RepoObject << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  external_AntoraComponent : (nvarchar(128))
  external_AntoraModule : (nvarchar(128))
  has_execution_plan_issue : (bit)
  has_get_referenced_issue : (bit)
  indent_sql_modules_definition : (tinyint)
  Inheritance_Source_fullname : (nvarchar(261))
  Inheritance_StringAggSeparatorSql : (nvarchar(4000))
  InheritanceDefinition : (nvarchar(4000))
  InheritanceType : (tinyint)
  - is_DocsExclude : (bit)
  - is_external : (bit)
  is_repo_managed : (bit)
  is_required_ObjectMerge : (bit)
  - is_ssas : (bit)
  is_SysObject_missing : (bit)
  - modify_dt : (datetime)
  pk_index_guid : (uniqueidentifier)
  pk_IndexPatternColumnName_new : (nvarchar(4000))
  Repo_history_table_guid : (uniqueidentifier)
  Repo_temporal_type : (tinyint)
  - RepoObject_name : (nvarchar(128))
  RepoObject_Referencing_Count : (int)
  - RepoObject_schema_name : (nvarchar(128))
  - RepoObject_type : (char(2))
  SysObject_id : (int)
  SysObject_modify_date : (datetime)
  - SysObject_name : (nvarchar(128))
  - SysObject_parent_object_id : (int)
  - SysObject_schema_name : (nvarchar(128))
  SysObject_type : (char(2))
  ~ has_different_sys_names : (bit)
  # is_RepoObject_name_uniqueidentifier : (int)
  # is_SysObject_name_uniqueidentifier : (int)
  ~ node_id : (bigint)
  # RepoObject_fullname : (nvarchar(261))
  # RepoObject_fullname2 : (nvarchar(257))
  # SysObject_fullname : (nvarchar(261))
  # SysObject_fullname2 : (nvarchar(257))
  ~ SysObject_query_sql : (nvarchar(406))
  ~ usp_persistence_fullname : (nvarchar(273))
  # usp_persistence_fullname2 : (nvarchar(269))
  # usp_persistence_name : (nvarchar(140))
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_persistence.adoc[]" as repo.RepoObject_persistence << U >> {
  - **target_RepoObject_guid** : (uniqueidentifier)
  ColumnListIgnore : (nvarchar(4000))
  ColumnListNoCompareButUpdate : (nvarchar(4000))
  ColumnListNoCompareNoUpdate : (nvarchar(4000))
  ExecutionLogId_action : (char(1))
  final_target_RepoObject_name : (nvarchar(128))
  - has_history : (bit)
  - has_history_columns : (bit)
  history_schema_name : (nvarchar(128))
  history_table_name : (nvarchar(128))
  - is_persistence_check_duplicate_per_pk : (bit)
  - is_persistence_check_for_empty_source : (bit)
  - is_persistence_delete_changed : (bit)
  - is_persistence_delete_missing : (bit)
  - is_persistence_insert : (bit)
  - is_persistence_persist_source : (bit)
  - is_persistence_truncate : (bit)
  - is_persistence_update_changed : (bit)
  postscript : (nvarchar(max))
  prescript : (nvarchar(max))
  source_RepoObject_guid : (uniqueidentifier)
  source_RepoObject_name : (nvarchar(128))
  ~ is_persistence : (bit)
  ~ temporal_type : (tinyint)
  --
}

entity "puml-link:dhw:sqldb:repo.usp_index_foreignkey.adoc[]" as repo.usp_Index_ForeignKey << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_index_inheritance.adoc[]" as repo.usp_index_inheritance << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_main.adoc[]" as repo.usp_main << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_persist_repoobject_sat2_t.adoc[]" as repo.usp_PERSIST_RepoObject_sat2_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_repoobjectcolumn_update_repoobjectcolumn_column_id.adoc[]" as repo.usp_RepoObjectColumn_update_RepoObjectColumn_column_id << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_sync_guid.adoc[]" as repo.usp_sync_guid << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_sync_guid_ssas.adoc[]" as repo.usp_sync_guid_ssas << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.usp_persist_repoobjectcolumn_translation_t.adoc[]" as ssas.usp_PERSIST_RepoObjectColumn_translation_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.usp_generatorusp_insert_update_persistence.adoc[]" as uspgenerator.usp_GeneratorUsp_insert_update_persistence << P >> {
  --
}

config.fs_get_parameter_value <.. repo.usp_main
config.usp_init_parameter <.. repo.usp_main
logs.usp_ExecutionLog_insert <.. repo.usp_main
property.usp_external_property_import <.. repo.usp_main
property.usp_PERSIST_PropertyName_Measure_T <.. repo.usp_main
property.usp_RepoObject_Inheritance <.. repo.usp_main
property.usp_RepoObjectColumn_Inheritance <.. repo.usp_main
property.usp_RepoObjectProperty_collect <.. repo.usp_main
reference.RepoObject_reference_persistence <.. repo.usp_main
reference.RepoObject_reference_persistence_target_as_source <.. repo.usp_main
reference.RepoObject_reference_T <.. repo.usp_main
reference.usp_additional_Reference <.. repo.usp_main
reference.usp_PERSIST_additional_Reference_from_properties_tgt <.. repo.usp_main
reference.usp_PERSIST_additional_Reference_from_ssas_tgt <.. repo.usp_main
reference.usp_PERSIST_additional_Reference_wo_columns_from_properties_tgt <.. repo.usp_main
reference.usp_PERSIST_RepoObject_reference_T <.. repo.usp_main
reference.usp_PERSIST_RepoObjectColumn_reference_T <.. repo.usp_main
reference.usp_RepoObject_ReferenceTree_insert <.. repo.usp_main
reference.usp_RepoObject_update_SysObjectQueryPlan <.. repo.usp_main
reference.usp_RepoObjectSource_FirstResultSet <.. repo.usp_main
reference.usp_RepoObjectSource_QueryPlan <.. repo.usp_main
reference.usp_update_Referencing_Count <.. repo.usp_main
repo.RepoObject <.. repo.usp_main
repo.RepoObject_persistence <.. repo.usp_main
repo.usp_Index_ForeignKey <.. repo.usp_main
repo.usp_index_inheritance <.. repo.usp_main
repo.usp_PERSIST_RepoObject_sat2_T <.. repo.usp_main
repo.usp_RepoObjectColumn_update_RepoObjectColumn_column_id <.. repo.usp_main
repo.usp_sync_guid <.. repo.usp_main
repo.usp_sync_guid_ssas <.. repo.usp_main
ssas.usp_PERSIST_RepoObjectColumn_translation_T <.. repo.usp_main
uspgenerator.usp_GeneratorUsp_insert_update_persistence <.. repo.usp_main


footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_colref[]


== sql_modules_definition

// tag::sql_modules_definition[]
[%collapsible]
=======
[source,sql,numbered,indent=0]
----
/*
code of this procedure is managed in the dhw repository. Do not modify manually.
Use [uspgenerator].[GeneratorUsp], [uspgenerator].[GeneratorUspParameter], [uspgenerator].[GeneratorUspStep], [uspgenerator].[GeneratorUsp_SqlUsp]
*/
CREATE   PROCEDURE [repo].[usp_main]
----keep the code between logging parameters and "START" unchanged!
---- parameters, used for logging; you don't need to care about them, but you can use them, wenn calling from SSIS or in your workflow to log the context of the procedure call
  @execution_instance_guid UNIQUEIDENTIFIER = NULL --SSIS system variable ExecutionInstanceGUID could be used, any other unique guid is also fine. If NULL, then NEWID() is used to create one
, @ssis_execution_id BIGINT = NULL --only SSIS system variable ServerExecutionID should be used, or any other consistent number system, do not mix different number systems
, @sub_execution_id INT = NULL --in case you log some sub_executions, for example in SSIS loops or sub packages
, @parent_execution_log_id BIGINT = NULL --in case a sup procedure is called, the @current_execution_log_id of the parent procedure should be propagated here. It allowes call stack analyzing

AS
BEGIN
DECLARE
 --
   @current_execution_log_id BIGINT --this variable should be filled only once per procedure call, it contains the first logging call for the step 'start'.
 , @current_execution_guid UNIQUEIDENTIFIER = NEWID() --a unique guid for any procedure call. It should be propagated to sub procedures using "@parent_execution_log_id = @current_execution_log_id"
 , @source_object NVARCHAR(261) = NULL --use it like '[schema].[object]', this allows data flow vizualizatiuon (include square brackets)
 , @target_object NVARCHAR(261) = NULL --use it like '[schema].[object]', this allows data flow vizualizatiuon (include square brackets)
 , @proc_id INT = @@procid
 , @proc_schema_name NVARCHAR(128) = OBJECT_SCHEMA_NAME(@@procid) --schema ande name of the current procedure should be automatically logged
 , @proc_name NVARCHAR(128) = OBJECT_NAME(@@procid)               --schema ande name of the current procedure should be automatically logged
 , @event_info NVARCHAR(MAX)
 , @step_id INT = 0
 , @step_name NVARCHAR(1000) = NULL
 , @rows INT

--[event_info] get's only the information about the "outer" calling process
--wenn the procedure calls sub procedures, the [event_info] will not change
SET @event_info = (
  SELECT TOP 1 [event_info]
  FROM sys.dm_exec_input_buffer(@@spid, CURRENT_REQUEST_ID())
  ORDER BY [event_info]
  )

IF @execution_instance_guid IS NULL
 SET @execution_instance_guid = NEWID();
--
--SET @rows = @@ROWCOUNT;
SET @step_id = @step_id + 1
SET @step_name = 'start'
SET @source_object = NULL
SET @target_object = NULL

EXEC logs.usp_ExecutionLog_insert
 --these parameters should be the same for all logging execution
   @execution_instance_guid = @execution_instance_guid
 , @ssis_execution_id = @ssis_execution_id
 , @sub_execution_id = @sub_execution_id
 , @parent_execution_log_id = @parent_execution_log_id
 , @current_execution_guid = @current_execution_guid
 , @proc_id = @proc_id
 , @proc_schema_name = @proc_schema_name
 , @proc_name = @proc_name
 , @event_info = @event_info
 --the following parameters are individual for each call
 , @step_id = @step_id --@step_id should be incremented before each call
 , @step_name = @step_name --assign individual step names for each call
 --only the "start" step should return the log id into @current_execution_log_id
 --all other calls should not overwrite @current_execution_log_id
 , @execution_log_id = @current_execution_log_id OUTPUT
----you can log the content of your own parameters, do this only in the start-step
----data type is sql_variant

--
PRINT '[repo].[usp_main]'
--keep the code between logging parameters and "START" unchanged!
--
----START
--
----- start here with your own code
--
/*{"ReportUspStep":[{"Number":150,"Name":"EXEC [config].[usp_init_parameter]","has_logging":1,"is_condition":0,"is_inactive":0,"is_SubProcedure":0}]}*/
PRINT CONCAT('usp_id;Number;Parent_Number: ',2,';',150,';',NULL);

EXEC [config].[usp_init_parameter]

-- Logging START --
SET @rows = @@ROWCOUNT
SET @step_id = @step_id + 1
SET @step_name = 'EXEC [config].[usp_init_parameter]'
SET @source_object = NULL
SET @target_object = NULL

EXEC logs.usp_ExecutionLog_insert 
 @execution_instance_guid = @execution_instance_guid
 , @ssis_execution_id = @ssis_execution_id
 , @sub_execution_id = @sub_execution_id
 , @parent_execution_log_id = @parent_execution_log_id
 , @current_execution_guid = @current_execution_guid
 , @proc_id = @proc_id
 , @proc_schema_name = @proc_schema_name
 , @proc_name = @proc_name
 , @event_info = @event_info
 , @step_id = @step_id
 , @step_name = @step_name
 , @source_object = @source_object
 , @target_object = @target_object

-- Logging END --

/*{"ReportUspStep":[{"Number":210,"Name":"(select config.fs_get_parameter_value ( 'sync enable', 'dwh' )) = 1","has_logging":0,"is_condition":1,"is_inactive":0,"is_SubProcedure":0}]}*/
IF (select config.fs_get_parameter_value ( 'sync enable', 'dwh' )) = 1

/*{"ReportUspStep":[{"Number":211,"Parent_Number":210,"Name":"[repo].[usp_sync_guid]","has_logging":0,"is_condition":0,"is_inactive":0,"is_SubProcedure":1}]}*/
BEGIN
EXEC [repo].[usp_sync_guid]
--add your own parameters
--logging parameters
 @execution_instance_guid = @execution_instance_guid
 , @ssis_execution_id = @ssis_execution_id
 , @sub_execution_id = @sub_execution_id
 , @parent_execution_log_id = @current_execution_log_id

END;

/*{"ReportUspStep":[{"Number":220,"Name":"(select config.fs_get_parameter_value ( 'sync enable', 'ssas' )) = 1","has_logging":0,"is_condition":1,"is_inactive":0,"is_SubProcedure":0}]}*/
IF (select config.fs_get_parameter_value ( 'sync enable', 'ssas' )) = 1

/*{"ReportUspStep":[{"Number":221,"Parent_Number":220,"Name":"[repo].[usp_sync_guid_ssas]","has_logging":0,"is_condition":0,"is_inactive":0,"is_SubProcedure":1}]}*/
BEGIN
EXEC [repo].[usp_sync_guid_ssas]
--add your own parameters
--logging parameters
 @execution_instance_guid = @execution_instance_guid
 , @ssis_execution_id = @ssis_execution_id
 , @sub_execution_id = @sub_execution_id
 , @parent_execution_log_id = @current_execution_log_id

END;

/*{"ReportUspStep":[{"Number":230,"Name":"(select config.fs_get_parameter_value ( 'sync enable', 'ssas' )) = 1 AND ( 'sync enable', 'dwh' )) = 0 ","has_logging":0,"is_condition":1,"is_inactive":0,"is_SubProcedure":0}]}*/
IF (select config.fs_get_parameter_value ( 'sync enable', 'ssas' )) = 1
AND
(select config.fs_get_parameter_value ( 'sync enable', 'dwh' )) = 0

/*{"ReportUspStep":[{"Number":231,"Parent_Number":230,"Name":"delete where is_ssas = 0 and is_external = 0","has_logging":1,"is_condition":0,"is_inactive":0,"is_SubProcedure":0,"log_source_object":"[repo].[RepoObject]","log_target_object":"[repo].[RepoObject]","log_flag_InsertUpdateDelete":"d"}]}*/
BEGIN
PRINT CONCAT('usp_id;Number;Parent_Number: ',2,';',231,';',230);

Delete From
repo.RepoObject
Where
    is_ssas         = 0
    And is_external = 0

-- Logging START --
SET @rows = @@ROWCOUNT
SET @step_id = @step_id + 1
SET @step_name = 'delete where is_ssas = 0 and is_external = 0'
SET @source_object = '[repo].[RepoObject]'
SET @target_object = '[repo].[RepoObject]'

EXEC logs.usp_ExecutionLog_insert 
 @execution_instance_guid = @execution_instance_guid
 , @ssis_execution_id = @ssis_execution_id
 , @sub_execution_id = @sub_execution_id
 , @parent_execution_log_id = @parent_execution_log_id
 , @current_execution_guid = @current_execution_guid
 , @proc_id = @proc_id
 , @proc_schema_name = @proc_schema_name
 , @proc_name = @proc_name
 , @event_info = @event_info
 , @step_id = @step_id
 , @step_name = @step_name
 , @source_object = @source_object
 , @target_object = @target_object
 , @deleted = @rows
-- Logging END --
END;

/*{"ReportUspStep":[{"Number":235,"Name":"[ssas].[usp_PERSIST_RepoObjectColumn_translation_T]","has_logging":0,"is_condition":0,"is_inactive":0,"is_SubProcedure":1}]}*/
EXEC [ssas].[usp_PERSIST_RepoObjectColumn_translation_T]
--add your own parameters
--logging parameters
 @execution_instance_guid = @execution_instance_guid
 , @ssis_execution_id = @ssis_execution_id
 , @sub_execution_id = @sub_execution_id
 , @parent_execution_log_id = @current_execution_log_id


/*{"ReportUspStep":[{"Number":240,"Name":"[reference].[usp_additional_Reference]","has_logging":0,"is_condition":0,"is_inactive":0,"is_SubProcedure":1}]}*/
EXEC [reference].[usp_additional_Reference]
--add your own parameters
--logging parameters
 @execution_instance_guid = @execution_instance_guid
 , @ssis_execution_id = @ssis_execution_id
 , @sub_execution_id = @sub_execution_id
 , @parent_execution_log_id = @current_execution_log_id


/*{"ReportUspStep":[{"Number":250,"Name":"[reference].[usp_PERSIST_RepoObject_reference_T]","has_logging":0,"is_condition":0,"is_inactive":0,"is_SubProcedure":1}]}*/
EXEC [reference].[usp_PERSIST_RepoObject_reference_T]
--add your own parameters
--logging parameters
 @execution_instance_guid = @execution_instance_guid
 , @ssis_execution_id = @ssis_execution_id
 , @sub_execution_id = @sub_execution_id
 , @parent_execution_log_id = @current_execution_log_id


/*{"ReportUspStep":[{"Number":261,"Name":"[reference].[RepoObject_reference_T] set referenced_is_PersistenceSource, referencing_is_PersistenceTarget from [reference].[RepoObject_reference_persistence] ","has_logging":1,"is_condition":0,"is_inactive":0,"is_SubProcedure":0,"log_source_object":"[reference].[RepoObject_reference_persistence]","log_target_object":"[reference].[RepoObject_reference_T]"}]}*/
PRINT CONCAT('usp_id;Number;Parent_Number: ',2,';',261,';',NULL);

Update
    T1
Set
    referenced_is_PersistenceSource = 1
  , referencing_is_PersistenceTarget = 1
From
    reference.RepoObject_reference_T               As T1
    Inner Join
        reference.RepoObject_reference_persistence As T2
            On
            T1.referenced_RepoObject_guid      = T2.referenced_RepoObject_guid
            And T1.referencing_RepoObject_guid = T2.referencing_RepoObject_guid;

-- Logging START --
SET @rows = @@ROWCOUNT
SET @step_id = @step_id + 1
SET @step_name = '[reference].[RepoObject_reference_T] set referenced_is_PersistenceSource, referencing_is_PersistenceTarget from [reference].[RepoObject_reference_persistence] '
SET @source_object = '[reference].[RepoObject_reference_persistence]'
SET @target_object = '[reference].[RepoObject_reference_T]'

EXEC logs.usp_ExecutionLog_insert 
 @execution_instance_guid = @execution_instance_guid
 , @ssis_execution_id = @ssis_execution_id
 , @sub_execution_id = @sub_execution_id
 , @parent_execution_log_id = @parent_execution_log_id
 , @current_execution_guid = @current_execution_guid
 , @proc_id = @proc_id
 , @proc_schema_name = @proc_schema_name
 , @proc_name = @proc_name
 , @event_info = @event_info
 , @step_id = @step_id
 , @step_name = @step_name
 , @source_object = @source_object
 , @target_object = @target_object

-- Logging END --

/*{"ReportUspStep":[{"Number":262,"Name":"[reference].[RepoObject_reference_T] set referenced_is_PersistenceSource, referencing_is_PersistenceTarget, is_ReversePersistenceViaView from [reference].[RepoObject_reference_persistence_target_as_source]","has_logging":1,"is_condition":0,"is_inactive":0,"is_SubProcedure":0,"log_source_object":"[reference].[RepoObject_reference_persistence_target_as_source]","log_target_object":"[reference].[RepoObject_reference_T]"}]}*/
PRINT CONCAT('usp_id;Number;Parent_Number: ',2,';',262,';',NULL);

Update
    T1
Set
    referenced_is_PersistenceSource = 1
  , referencing_is_PersistenceTarget = 1
  , is_ReversePersistenceViaView = 1
From
    reference.RepoObject_reference_T                                    As T1
    Inner Join
        [reference].[RepoObject_reference_persistence_target_as_source] As T2
            On
            T1.referenced_RepoObject_guid      = T2.referenced_RepoObject_guid
            And T1.referencing_RepoObject_guid = T2.referencing_RepoObject_guid;

-- Logging START --
SET @rows = @@ROWCOUNT
SET @step_id = @step_id + 1
SET @step_name = '[reference].[RepoObject_reference_T] set referenced_is_PersistenceSource, referencing_is_PersistenceTarget, is_ReversePersistenceViaView from [reference].[RepoObject_reference_persistence_target_as_source]'
SET @source_object = '[reference].[RepoObject_reference_persistence_target_as_source]'
SET @target_object = '[reference].[RepoObject_reference_T]'

EXEC logs.usp_ExecutionLog_insert 
 @execution_instance_guid = @execution_instance_guid
 , @ssis_execution_id = @ssis_execution_id
 , @sub_execution_id = @sub_execution_id
 , @parent_execution_log_id = @parent_execution_log_id
 , @current_execution_guid = @current_execution_guid
 , @proc_id = @proc_id
 , @proc_schema_name = @proc_schema_name
 , @proc_name = @proc_name
 , @event_info = @event_info
 , @step_id = @step_id
 , @step_name = @step_name
 , @source_object = @source_object
 , @target_object = @target_object

-- Logging END --

/*{"ReportUspStep":[{"Number":263,"Name":"[reference].[RepoObject_reference_T] set referenced_is_PersistenceTarget, referencing_is_PersistenceUspTargetRef","has_logging":1,"is_condition":0,"is_inactive":0,"is_SubProcedure":0,"log_source_object":"[repo].[RepoObject]","log_target_object":"[reference].[RepoObject_reference_T]"}]}*/
PRINT CONCAT('usp_id;Number;Parent_Number: ',2,';',263,';',NULL);

Update
    T1
Set
    referenced_is_PersistenceTarget = 1
  , referencing_is_PersistenceUspTargetRef = 1
From
    reference.RepoObject_reference_T As T1
    Inner Join
        repo.RepoObject              As T2
            On
            T1.referenced_RepoObject_guid = T2.RepoObject_guid
            And T1.referencing_fullname2  = T2.usp_persistence_fullname2;

-- Logging START --
SET @rows = @@ROWCOUNT
SET @step_id = @step_id + 1
SET @step_name = '[reference].[RepoObject_reference_T] set referenced_is_PersistenceTarget, referencing_is_PersistenceUspTargetRef'
SET @source_object = '[repo].[RepoObject]'
SET @target_object = '[reference].[RepoObject_reference_T]'

EXEC logs.usp_ExecutionLog_insert 
 @execution_instance_guid = @execution_instance_guid
 , @ssis_execution_id = @ssis_execution_id
 , @sub_execution_id = @sub_execution_id
 , @parent_execution_log_id = @parent_execution_log_id
 , @current_execution_guid = @current_execution_guid
 , @proc_id = @proc_id
 , @proc_schema_name = @proc_schema_name
 , @proc_name = @proc_name
 , @event_info = @event_info
 , @step_id = @step_id
 , @step_name = @step_name
 , @source_object = @source_object
 , @target_object = @target_object

-- Logging END --

/*{"ReportUspStep":[{"Number":280,"Name":"[reference].[usp_RepoObject_ReferenceTree_insert]","has_logging":0,"is_condition":0,"is_inactive":0,"is_SubProcedure":1}]}*/
EXEC [reference].[usp_RepoObject_ReferenceTree_insert]
--add your own parameters
--logging parameters
 @execution_instance_guid = @execution_instance_guid
 , @ssis_execution_id = @ssis_execution_id
 , @sub_execution_id = @sub_execution_id
 , @parent_execution_log_id = @current_execution_log_id


/*{"ReportUspStep":[{"Number":290,"Name":"[reference].[usp_PERSIST_RepoObjectColumn_reference_T]","has_logging":0,"is_condition":0,"is_inactive":0,"is_SubProcedure":1}]}*/
EXEC [reference].[usp_PERSIST_RepoObjectColumn_reference_T]
--add your own parameters
--logging parameters
 @execution_instance_guid = @execution_instance_guid
 , @ssis_execution_id = @ssis_execution_id
 , @sub_execution_id = @sub_execution_id
 , @parent_execution_log_id = @current_execution_log_id


/*{"ReportUspStep":[{"Number":292,"Name":"[repo].[usp_PERSIST_RepoObject_sat2_T]","has_logging":0,"is_condition":0,"is_inactive":0,"is_SubProcedure":1}]}*/
EXEC [repo].[usp_PERSIST_RepoObject_sat2_T]
--add your own parameters
--logging parameters
 @execution_instance_guid = @execution_instance_guid
 , @ssis_execution_id = @ssis_execution_id
 , @sub_execution_id = @sub_execution_id
 , @parent_execution_log_id = @current_execution_log_id


/*{"ReportUspStep":[{"Number":300,"Name":"(select [config].[fs_get_parameter_value]('main enable usp_RepoObjectSource_FirstResultSet', DEFAULT)) = 1","has_logging":0,"is_condition":1,"is_inactive":0,"is_SubProcedure":0}]}*/
IF (select [config].[fs_get_parameter_value]('main enable usp_RepoObjectSource_FirstResultSet', DEFAULT)) = 1

/*{"ReportUspStep":[{"Number":310,"Parent_Number":300,"Name":"[reference].[usp_RepoObjectSource_FirstResultSet]","has_logging":0,"is_condition":0,"is_inactive":0,"is_SubProcedure":1}]}*/
BEGIN
EXEC [reference].[usp_RepoObjectSource_FirstResultSet]
--This can take a very long time
--add your own parameters
--logging parameters
 @execution_instance_guid = @execution_instance_guid
 , @ssis_execution_id = @ssis_execution_id
 , @sub_execution_id = @sub_execution_id
 , @parent_execution_log_id = @current_execution_log_id

END;

/*{"ReportUspStep":[{"Number":400,"Name":"(select [config].[fs_get_parameter_value]('main enable usp_RepoObject_update_SysObjectQueryPlan', DEFAULT)) = 1","has_logging":0,"is_condition":1,"is_inactive":0,"is_SubProcedure":0}]}*/
IF (select [config].[fs_get_parameter_value]('main enable usp_RepoObject_update_SysObjectQueryPlan', DEFAULT)) = 1

/*{"ReportUspStep":[{"Number":410,"Parent_Number":400,"Name":"[reference].[usp_RepoObject_update_SysObjectQueryPlan]","has_logging":0,"is_condition":0,"is_inactive":0,"is_SubProcedure":1}]}*/
BEGIN
EXEC [reference].[usp_RepoObject_update_SysObjectQueryPlan]
--add your own parameters
--logging parameters
 @execution_instance_guid = @execution_instance_guid
 , @ssis_execution_id = @ssis_execution_id
 , @sub_execution_id = @sub_execution_id
 , @parent_execution_log_id = @current_execution_log_id

END;

/*{"ReportUspStep":[{"Number":500,"Name":"(select [config].[fs_get_parameter_value]('main enable usp_RepoObjectSource_QueryPlan', DEFAULT)) = 1","has_logging":0,"is_condition":1,"is_inactive":0,"is_SubProcedure":0}]}*/
IF (select [config].[fs_get_parameter_value]('main enable usp_RepoObjectSource_QueryPlan', DEFAULT)) = 1

/*{"ReportUspStep":[{"Number":510,"Parent_Number":500,"Name":"[reference].[usp_RepoObjectSource_QueryPlan]\r\n--This can take a very long time","has_logging":0,"is_condition":0,"is_inactive":0,"is_SubProcedure":1}]}*/
BEGIN
EXEC [reference].[usp_RepoObjectSource_QueryPlan]
--add your own parameters
--logging parameters
 @execution_instance_guid = @execution_instance_guid
 , @ssis_execution_id = @ssis_execution_id
 , @sub_execution_id = @sub_execution_id
 , @parent_execution_log_id = @current_execution_log_id

END;

/*{"ReportUspStep":[{"Number":610,"Name":"[reference].[usp_update_Referencing_Count]","has_logging":0,"is_condition":0,"is_inactive":0,"is_SubProcedure":1}]}*/
EXEC [reference].[usp_update_Referencing_Count]
--add your own parameters
--logging parameters
 @execution_instance_guid = @execution_instance_guid
 , @ssis_execution_id = @ssis_execution_id
 , @sub_execution_id = @sub_execution_id
 , @parent_execution_log_id = @current_execution_log_id


/*{"ReportUspStep":[{"Number":710,"Name":"[repo].[usp_index_inheritance]","has_logging":0,"is_condition":0,"is_inactive":0,"is_SubProcedure":1}]}*/
EXEC [repo].[usp_index_inheritance]
--add your own parameters
--logging parameters
 @execution_instance_guid = @execution_instance_guid
 , @ssis_execution_id = @ssis_execution_id
 , @sub_execution_id = @sub_execution_id
 , @parent_execution_log_id = @current_execution_log_id


/*{"ReportUspStep":[{"Number":720,"Name":"[repo].[usp_Index_ForeignKey]","has_logging":0,"is_condition":0,"is_inactive":0,"is_SubProcedure":1}]}*/
EXEC [repo].[usp_Index_ForeignKey]
--add your own parameters
--logging parameters
 @execution_instance_guid = @execution_instance_guid
 , @ssis_execution_id = @ssis_execution_id
 , @sub_execution_id = @sub_execution_id
 , @parent_execution_log_id = @current_execution_log_id


/*{"ReportUspStep":[{"Number":730,"Name":"[property].[usp_PERSIST_PropertyName_Measure_T]","has_logging":0,"is_condition":0,"is_inactive":0,"is_SubProcedure":1}]}*/
EXEC [property].[usp_PERSIST_PropertyName_Measure_T]
--add your own parameters
--logging parameters
 @execution_instance_guid = @execution_instance_guid
 , @ssis_execution_id = @ssis_execution_id
 , @sub_execution_id = @sub_execution_id
 , @parent_execution_log_id = @current_execution_log_id


/*{"ReportUspStep":[{"Number":810,"Name":"[repo].[usp_RepoObjectColumn_update_RepoObjectColumn_column_id]","has_logging":0,"is_condition":0,"is_inactive":0,"is_SubProcedure":1}]}*/
EXEC [repo].[usp_RepoObjectColumn_update_RepoObjectColumn_column_id]
--add your own parameters
--logging parameters
 @execution_instance_guid = @execution_instance_guid
 , @ssis_execution_id = @ssis_execution_id
 , @sub_execution_id = @sub_execution_id
 , @parent_execution_log_id = @current_execution_log_id


/*{"ReportUspStep":[{"Number":910,"Name":"[repo].[usp_GeneratorUsp_insert_update_persistence]","has_logging":0,"is_condition":0,"is_inactive":0,"is_SubProcedure":1}]}*/
EXEC [uspgenerator].[usp_GeneratorUsp_insert_update_persistence]
--add your own parameters
--logging parameters
 @execution_instance_guid = @execution_instance_guid
 , @ssis_execution_id = @ssis_execution_id
 , @sub_execution_id = @sub_execution_id
 , @parent_execution_log_id = @current_execution_log_id


/*{"ReportUspStep":[{"Number":920,"Name":"Persistence Target: update repo.RepoObject set InheritanceType = 13 (if NULL)","has_logging":1,"is_condition":0,"is_inactive":0,"is_SubProcedure":0,"log_source_object":"[repo].[RepoObject_persistence]","log_target_object":"[repo].[RepoObject]","log_flag_InsertUpdateDelete":"u"}]}*/
PRINT CONCAT('usp_id;Number;Parent_Number: ',2,';',920,';',NULL);

Update
    repo.RepoObject
Set
    InheritanceType = 13
Where
    ( RepoObject_type = 'U' )
    And ( InheritanceType Is Null )
    And Exists
(
    Select
        1
    From
        repo.RepoObject_persistence As rop
    Where
        rop.target_RepoObject_guid = repo.RepoObject.RepoObject_guid
)

-- Logging START --
SET @rows = @@ROWCOUNT
SET @step_id = @step_id + 1
SET @step_name = 'Persistence Target: update repo.RepoObject set InheritanceType = 13 (if NULL)'
SET @source_object = '[repo].[RepoObject_persistence]'
SET @target_object = '[repo].[RepoObject]'

EXEC logs.usp_ExecutionLog_insert 
 @execution_instance_guid = @execution_instance_guid
 , @ssis_execution_id = @ssis_execution_id
 , @sub_execution_id = @sub_execution_id
 , @parent_execution_log_id = @parent_execution_log_id
 , @current_execution_guid = @current_execution_guid
 , @proc_id = @proc_id
 , @proc_schema_name = @proc_schema_name
 , @proc_name = @proc_name
 , @event_info = @event_info
 , @step_id = @step_id
 , @step_name = @step_name
 , @source_object = @source_object
 , @target_object = @target_object
 , @updated = @rows
-- Logging END --

/*{"ReportUspStep":[{"Number":3200,"Name":"[property].[usp_RepoObjectProperty_collect]","has_logging":1,"is_condition":0,"is_inactive":0,"is_SubProcedure":1}]}*/
EXEC [property].[usp_RepoObjectProperty_collect]
--add your own parameters
--logging parameters
 @execution_instance_guid = @execution_instance_guid
 , @ssis_execution_id = @ssis_execution_id
 , @sub_execution_id = @sub_execution_id
 , @parent_execution_log_id = @current_execution_log_id


/*{"ReportUspStep":[{"Number":3310,"Name":"[reference].[usp_PERSIST_additional_Reference_from_properties_tgt]","has_logging":1,"is_condition":0,"is_inactive":0,"is_SubProcedure":1}]}*/
EXEC [reference].[usp_PERSIST_additional_Reference_from_properties_tgt]
--add your own parameters
--logging parameters
 @execution_instance_guid = @execution_instance_guid
 , @ssis_execution_id = @ssis_execution_id
 , @sub_execution_id = @sub_execution_id
 , @parent_execution_log_id = @current_execution_log_id


/*{"ReportUspStep":[{"Number":3320,"Name":"[reference].[usp_PERSIST_additional_Reference_wo_columns_from_properties_tgt]","has_logging":1,"is_condition":0,"is_inactive":0,"is_SubProcedure":1}]}*/
EXEC [reference].[usp_PERSIST_additional_Reference_wo_columns_from_properties_tgt]
--add your own parameters
--logging parameters
 @execution_instance_guid = @execution_instance_guid
 , @ssis_execution_id = @ssis_execution_id
 , @sub_execution_id = @sub_execution_id
 , @parent_execution_log_id = @current_execution_log_id


/*{"ReportUspStep":[{"Number":3330,"Name":"[reference].[usp_PERSIST_additional_Reference_from_ssas_tgt]","has_logging":1,"is_condition":0,"is_inactive":0,"is_SubProcedure":1}]}*/
EXEC [reference].[usp_PERSIST_additional_Reference_from_ssas_tgt]
--add your own parameters
--logging parameters
 @execution_instance_guid = @execution_instance_guid
 , @ssis_execution_id = @ssis_execution_id
 , @sub_execution_id = @sub_execution_id
 , @parent_execution_log_id = @current_execution_log_id


/*{"ReportUspStep":[{"Number":3400,"Name":"[property].[usp_external_property_import]","has_logging":1,"is_condition":0,"is_inactive":0,"is_SubProcedure":1}]}*/
EXEC [property].[usp_external_property_import]
--add your own parameters
--logging parameters
 @execution_instance_guid = @execution_instance_guid
 , @ssis_execution_id = @ssis_execution_id
 , @sub_execution_id = @sub_execution_id
 , @parent_execution_log_id = @current_execution_log_id


/*{"ReportUspStep":[{"Number":4110,"Name":"[property].[usp_RepoObject_Inheritance]","has_logging":0,"is_condition":0,"is_inactive":0,"is_SubProcedure":1}]}*/
EXEC [property].[usp_RepoObject_Inheritance]
--add your own parameters
--logging parameters
 @execution_instance_guid = @execution_instance_guid
 , @ssis_execution_id = @ssis_execution_id
 , @sub_execution_id = @sub_execution_id
 , @parent_execution_log_id = @current_execution_log_id


/*{"ReportUspStep":[{"Number":4120,"Name":"[property].[usp_RepoObjectColumn_Inheritance]","has_logging":0,"is_condition":0,"is_inactive":0,"is_SubProcedure":1}]}*/
EXEC [property].[usp_RepoObjectColumn_Inheritance]
--add your own parameters
--logging parameters
 @execution_instance_guid = @execution_instance_guid
 , @ssis_execution_id = @ssis_execution_id
 , @sub_execution_id = @sub_execution_id
 , @parent_execution_log_id = @current_execution_log_id


--
--finish your own code here
--keep the code between "END" and the end of the procedure unchanged!
--
--END
--
--SET @rows = @@ROWCOUNT
SET @step_id = @step_id + 1
SET @step_name = 'end'
SET @source_object = NULL
SET @target_object = NULL

EXEC logs.usp_ExecutionLog_insert
   @execution_instance_guid = @execution_instance_guid
 , @ssis_execution_id = @ssis_execution_id
 , @sub_execution_id = @sub_execution_id
 , @parent_execution_log_id = @parent_execution_log_id
 , @current_execution_guid = @current_execution_guid
 , @proc_id = @proc_id
 , @proc_schema_name = @proc_schema_name
 , @proc_name = @proc_name
 , @event_info = @event_info
 , @step_id = @step_id
 , @step_name = @step_name
 , @source_object = @source_object
 , @target_object = @target_object

END


----
=======
// end::sql_modules_definition[]


