// tag::HeaderFullDisplayName[]
= repo.IndexColumn_ssas_gross - V
// end::HeaderFullDisplayName[]

== existing_properties

// tag::existing_properties[]

:ExistsProperty--antorareferencedlist:
:ExistsProperty--antorareferencinglist:
:ExistsProperty--is_repo_managed:
:ExistsProperty--is_ssas:
:ExistsProperty--referencedobjectlist:
:ExistsProperty--sql_modules_definition:
:ExistsProperty--FK:
:ExistsProperty--AntoraIndexList:
:ExistsProperty--Columns:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
696E8DEE-3D08-EC11-8515-A81E8446D5B0
// end::RepoObject_guid[]

== RepoObject_FullDisplayName2

// tag::RepoObject_FullDisplayName2[]
repo.IndexColumn_ssas_gross
// end::RepoObject_FullDisplayName2[]

== SysObject_type

// tag::SysObject_type[]
V 
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
view
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
407008531
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2022-01-05 18:06:33
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]
[discrete]
== _


[#column-columnunderlineuserunderlinetypeunderlinefullname]
=== column_user_type_fullname

[cols="d,8a,m,m,m"]
|===
|
|column_user_type_fullname
|nvarchar(128)
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobjectcolumn.adoc#column-repounderlineuserunderlinetypeunderlinefullname[+repo.RepoObjectColumn.Repo_user_type_fullname+]
--


[#column-indexunderlinecolumnunderlineid]
=== index_column_id

[cols="d,8a,m,m,m"]
|===
|
|index_column_id
|int
|NOT NULL
|
|===

.Referenced Columns
--
* xref:repo.indexcolumn_ssas_t.adoc#column-indexunderlinecolumnunderlineid[+repo.IndexColumn_ssas_T.index_column_id+]
--


[#column-indexunderlineguid]
=== index_guid

[cols="d,8a,m,m,m"]
|===
|
|index_guid
|uniqueidentifier
|NOT NULL
|
|===

.Referenced Columns
--
* xref:repo.indexcolumn_ssas_t.adoc#column-indexunderlineguid[+repo.IndexColumn_ssas_T.index_guid+]
--


[#column-indexunderlinename]
=== index_name

[cols="d,8a,m,m,m"]
|===
|
|index_name
|nvarchar(450)
|NOT NULL
|
|===

.Referenced Columns
--
* xref:repo.index_ssas_t.adoc#column-indexunderlinename[+repo.Index_ssas_T.index_name+]
--


[#column-isunderlinedescendingunderlinekey]
=== is_descending_key

[cols="d,8a,m,m,m"]
|===
|
|is_descending_key
|bit
|NULL
|
|===

.Referenced Columns
--
* xref:repo.indexcolumn_ssas_t.adoc#column-isunderlinedescendingunderlinekey[+repo.IndexColumn_ssas_T.is_descending_key+]
--


[#column-isunderlineindexunderlineprimaryunderlinekey]
=== is_index_primary_key

[cols="d,8a,m,m,m"]
|===
|
|is_index_primary_key
|bit
|NOT NULL
|
|===

.Referenced Columns
--
* xref:repo.index_ssas_t.adoc#column-isunderlineindexunderlineprimaryunderlinekey[+repo.Index_ssas_T.is_index_primary_key+]
--


[#column-isunderlineindexunderlinereal]
=== is_index_real

[cols="d,8a,m,m,m"]
|===
|
|is_index_real
|bit
|NULL
|
|===


[#column-isunderlineindexunderlineunique]
=== is_index_unique

[cols="d,8a,m,m,m"]
|===
|
|is_index_unique
|bit
|NOT NULL
|
|===

.Referenced Columns
--
* xref:repo.index_ssas_t.adoc#column-isunderlineindexunderlineunique[+repo.Index_ssas_T.is_index_unique+]
--


[#column-objectunderlinecolumnunderlinename]
=== Object_column_name

[cols="d,8a,m,m,m"]
|===
|
|Object_column_name
|nvarchar(128)
|NOT NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobjectcolumn.adoc#column-repoobjectcolumnunderlinename[+repo.RepoObjectColumn.RepoObjectColumn_name+]
--


[#column-parentunderlineobjectunderlinefullname]
=== parent_Object_fullname

[cols="d,8a,m,m,m"]
|===
|
|parent_Object_fullname
|nvarchar(261)
|NULL
|
|===

.Description
--
(concat('[',[RepoObject_schema_name],'].[',[RepoObject_name],']'))
--
{empty} +

.Referenced Columns
--
* xref:repo.repoobject.adoc#column-repoobjectunderlinefullname[+repo.RepoObject.RepoObject_fullname+]
--


[#column-parentunderlineobjectunderlinename]
=== parent_Object_name

[cols="d,8a,m,m,m"]
|===
|
|parent_Object_name
|nvarchar(128)
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject.adoc#column-repoobjectunderlinename[+repo.RepoObject.RepoObject_name+]
--


[#column-parentunderlinerepoobjectunderlineguid]
=== parent_RepoObject_guid

[cols="d,8a,m,m,m"]
|===
|
|parent_RepoObject_guid
|uniqueidentifier
|NOT NULL
|
|===

.Referenced Columns
--
* xref:repo.index_ssas_t.adoc#column-repoobjectunderlineguid[+repo.Index_ssas_T.RepoObject_guid+]
--


[#column-parentunderlineschemaunderlinename]
=== parent_schema_name

[cols="d,8a,m,m,m"]
|===
|
|parent_schema_name
|nvarchar(128)
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject.adoc#column-repoobjectunderlineschemaunderlinename[+repo.RepoObject.RepoObject_schema_name+]
--


[#column-repoobjectcolumnunderlineguid]
=== RepoObjectColumn_guid

[cols="d,8a,m,m,m"]
|===
|
|RepoObjectColumn_guid
|uniqueidentifier
|NOT NULL
|
|===

.Referenced Columns
--
* xref:repo.indexcolumn_ssas_t.adoc#column-repoobjectcolumnunderlineguid[+repo.IndexColumn_ssas_T.RepoObjectColumn_guid+]
--


// end::AntoraColumnDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]














// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]
|
|<<column-columnunderlineuserunderlinetypeunderlinefullname>>
|nvarchar(128)
|NULL
|

|
|<<column-indexunderlinecolumnunderlineid>>
|int
|NOT NULL
|

|
|<<column-indexunderlineguid>>
|uniqueidentifier
|NOT NULL
|

|
|<<column-indexunderlinename>>
|nvarchar(450)
|NOT NULL
|

|
|<<column-isunderlinedescendingunderlinekey>>
|bit
|NULL
|

|
|<<column-isunderlineindexunderlineprimaryunderlinekey>>
|bit
|NOT NULL
|

|
|<<column-isunderlineindexunderlinereal>>
|bit
|NULL
|

|
|<<column-isunderlineindexunderlineunique>>
|bit
|NOT NULL
|

|
|<<column-objectunderlinecolumnunderlinename>>
|nvarchar(128)
|NOT NULL
|

|
|<<column-parentunderlineobjectunderlinefullname>>
|nvarchar(261)
|NULL
|

|
|<<column-parentunderlineobjectunderlinename>>
|nvarchar(128)
|NULL
|

|
|<<column-parentunderlinerepoobjectunderlineguid>>
|uniqueidentifier
|NOT NULL
|

|
|<<column-parentunderlineschemaunderlinename>>
|nvarchar(128)
|NULL
|

|
|<<column-repoobjectcolumnunderlineguid>>
|uniqueidentifier
|NOT NULL
|

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

[#index-idxunderlineindexcolumnunderlinessasunderlinegrossunderlineunderline1]
=== idx_IndexColumn_ssas_gross++__++1

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-parent_schema_name>>; nvarchar(128)
* <<column-parent_Object_name>>; nvarchar(128)
--
* PK, Unique, Real: 0, 0, 0


[#index-idxunderlineindexcolumnunderlinessasunderlinegrossunderlineunderline2]
=== idx_IndexColumn_ssas_gross++__++2

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-Object_column_name>>; nvarchar(128)
--
* PK, Unique, Real: 0, 0, 0


[#index-idxunderlineindexcolumnunderlinessasunderlinegrossunderlineunderline3]
=== idx_IndexColumn_ssas_gross++__++3

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-index_guid>>; uniqueidentifier
* <<column-index_column_id>>; int
--
* PK, Unique, Real: 0, 0, 0


[#index-idxunderlineindexcolumnunderlinessasunderlinegrossunderlineunderline4]
=== idx_IndexColumn_ssas_gross++__++4

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-index_guid>>; uniqueidentifier
--
* PK, Unique, Real: 0, 0, 0


[#index-idxunderlineindexcolumnunderlinessasunderlinegrossunderlineunderline5]
=== idx_IndexColumn_ssas_gross++__++5

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-index_name>>; nvarchar(450)
--
* PK, Unique, Real: 0, 0, 0

// end::AntoraIndexList[]

== AntoraMeasureDetails

// tag::AntoraMeasureDetails[]

// end::AntoraMeasureDetails[]

== AntoraMeasureDescriptions



== AntoraParameterList

// tag::AntoraParameterList[]

// end::AntoraParameterList[]

== AntoraXrefCulturesList

// tag::AntoraXrefCulturesList[]
* xref:dhw:sqldb:repo.indexcolumn_ssas_gross.adoc[] - 
// end::AntoraXrefCulturesList[]

== cultures_count

// tag::cultures_count[]
1
// end::cultures_count[]

== Other tags

source: property.RepoObjectProperty_cross As rop_cross


=== additional_reference_csv

// tag::additional_reference_csv[]

// end::additional_reference_csv[]


=== AdocUspSteps

// tag::adocuspsteps[]

// end::adocuspsteps[]


=== AntoraReferencedList

// tag::antorareferencedlist[]
* xref:dhw:sqldb:repo.index_ssas_t.adoc[]
* xref:dhw:sqldb:repo.indexcolumn_ssas_t.adoc[]
* xref:dhw:sqldb:repo.repoobject.adoc[]
* xref:dhw:sqldb:repo.repoobjectcolumn.adoc[]
// end::antorareferencedlist[]


=== AntoraReferencingList

// tag::antorareferencinglist[]
* xref:dhw:sqldb:repo.indexcolumn_union.adoc[]
// end::antorareferencinglist[]


=== Description

// tag::description[]

// end::description[]


=== exampleUsage

// tag::exampleusage[]

// end::exampleusage[]


=== exampleUsage_2

// tag::exampleusage_2[]

// end::exampleusage_2[]


=== exampleUsage_3

// tag::exampleusage_3[]

// end::exampleusage_3[]


=== exampleUsage_4

// tag::exampleusage_4[]

// end::exampleusage_4[]


=== exampleUsage_5

// tag::exampleusage_5[]

// end::exampleusage_5[]


=== exampleWrong_Usage

// tag::examplewrong_usage[]

// end::examplewrong_usage[]


=== has_execution_plan_issue

// tag::has_execution_plan_issue[]

// end::has_execution_plan_issue[]


=== has_get_referenced_issue

// tag::has_get_referenced_issue[]

// end::has_get_referenced_issue[]


=== has_history

// tag::has_history[]

// end::has_history[]


=== has_history_columns

// tag::has_history_columns[]

// end::has_history_columns[]


=== InheritanceType

// tag::inheritancetype[]

// end::inheritancetype[]


=== is_persistence

// tag::is_persistence[]

// end::is_persistence[]


=== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]

// end::is_persistence_check_duplicate_per_pk[]


=== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]

// end::is_persistence_check_for_empty_source[]


=== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]

// end::is_persistence_delete_changed[]


=== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]

// end::is_persistence_delete_missing[]


=== is_persistence_insert

// tag::is_persistence_insert[]

// end::is_persistence_insert[]


=== is_persistence_truncate

// tag::is_persistence_truncate[]

// end::is_persistence_truncate[]


=== is_persistence_update_changed

// tag::is_persistence_update_changed[]

// end::is_persistence_update_changed[]


=== is_repo_managed

// tag::is_repo_managed[]
0
// end::is_repo_managed[]


=== is_ssas

// tag::is_ssas[]
0
// end::is_ssas[]


=== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


=== MS_Description

// tag::ms_description[]

// end::ms_description[]


=== persistence_source_RepoObject_fullname

// tag::persistence_source_repoobject_fullname[]

// end::persistence_source_repoobject_fullname[]


=== persistence_source_RepoObject_fullname2

// tag::persistence_source_repoobject_fullname2[]

// end::persistence_source_repoobject_fullname2[]


=== persistence_source_RepoObject_guid

// tag::persistence_source_repoobject_guid[]

// end::persistence_source_repoobject_guid[]


=== persistence_source_RepoObject_xref

// tag::persistence_source_repoobject_xref[]

// end::persistence_source_repoobject_xref[]


=== pk_index_guid

// tag::pk_index_guid[]

// end::pk_index_guid[]


=== pk_IndexPatternColumnDatatype

// tag::pk_indexpatterncolumndatatype[]

// end::pk_indexpatterncolumndatatype[]


=== pk_IndexPatternColumnName

// tag::pk_indexpatterncolumnname[]

// end::pk_indexpatterncolumnname[]


=== pk_IndexSemanticGroup

// tag::pk_indexsemanticgroup[]

// end::pk_indexsemanticgroup[]


=== ReferencedObjectList

// tag::referencedobjectlist[]
* [repo].[Index_ssas_T]
* [repo].[IndexColumn_ssas_T]
* [repo].[RepoObject]
* [repo].[RepoObjectColumn]
// end::referencedobjectlist[]


=== usp_persistence_RepoObject_guid

// tag::usp_persistence_repoobject_guid[]

// end::usp_persistence_repoobject_guid[]


=== UspExamples

// tag::uspexamples[]

// end::uspexamples[]


=== uspgenerator_usp_id

// tag::uspgenerator_usp_id[]

// end::uspgenerator_usp_id[]


=== UspParameters

// tag::uspparameters[]

// end::uspparameters[]

== Boolean Attributes

source: property.RepoObjectProperty WHERE property_int = 1

// tag::boolean_attributes[]


// end::boolean_attributes[]

== PlantUML diagrams

=== PlantUML Entity

// tag::puml_entity[]
[plantuml, entity-{docname}, svg, subs=macros]
....
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:repo.indexcolumn_ssas_gross.adoc[]" as repo.IndexColumn_ssas_gross << V >> {
  column_user_type_fullname : (nvarchar(128))
  - index_column_id : (int)
  - index_guid : (uniqueidentifier)
  - index_name : (nvarchar(450))
  is_descending_key : (bit)
  - is_index_primary_key : (bit)
  is_index_real : (bit)
  - is_index_unique : (bit)
  - Object_column_name : (nvarchar(128))
  parent_Object_fullname : (nvarchar(261))
  parent_Object_name : (nvarchar(128))
  - parent_RepoObject_guid : (uniqueidentifier)
  parent_schema_name : (nvarchar(128))
  - RepoObjectColumn_guid : (uniqueidentifier)
  --
}
....

// end::puml_entity[]

=== PlantUML Entity 1 1 FK

// tag::puml_entity_1_1_fk[]
[plantuml, entity_1_1_fk-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:repo.indexcolumn_ssas_gross.adoc[]" as repo.IndexColumn_ssas_gross << V >> {
- idx_IndexColumn_ssas_gross__1

..
parent_schema_name; nvarchar(128)
parent_Object_name; nvarchar(128)
--
- idx_IndexColumn_ssas_gross__2

..
Object_column_name; nvarchar(128)
--
- idx_IndexColumn_ssas_gross__3

..
index_guid; uniqueidentifier
index_column_id; int
--
- idx_IndexColumn_ssas_gross__4

..
index_guid; uniqueidentifier
--
- idx_IndexColumn_ssas_gross__5

..
index_name; nvarchar(450)
}



footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_fk[]

=== PlantUML 1 1 ObjectRef

// tag::puml_entity_1_1_objectref[]
[plantuml, entity_1_1_objectref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:repo.index_ssas_t.adoc[]" as repo.Index_ssas_T << U >> {
  - **databasename** : (nvarchar(128))
  **index_name** : (nvarchar(450))
  --
}

entity "puml-link:dhw:sqldb:repo.indexcolumn_ssas_gross.adoc[]" as repo.IndexColumn_ssas_gross << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.indexcolumn_ssas_t.adoc[]" as repo.IndexColumn_ssas_T << U >> {
  - **index_guid** : (uniqueidentifier)
  - **index_column_id** : (int)
  --
}

entity "puml-link:dhw:sqldb:repo.indexcolumn_union.adoc[]" as repo.IndexColumn_union << V >> {
  **index_guid** : (uniqueidentifier)
  - **index_column_id** : (int)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject.adoc[]" as repo.RepoObject << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn.adoc[]" as repo.RepoObjectColumn << U >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  --
}

repo.Index_ssas_T <.. repo.IndexColumn_ssas_gross
repo.IndexColumn_ssas_gross <.. repo.IndexColumn_union
repo.IndexColumn_ssas_T <.. repo.IndexColumn_ssas_gross
repo.RepoObject <.. repo.IndexColumn_ssas_gross
repo.RepoObjectColumn <.. repo.IndexColumn_ssas_gross

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_objectref[]

=== PlantUML 30 0 ObjectRef

// tag::puml_entity_30_0_objectref[]
[plantuml, entity_30_0_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:config.ftv_get_parameter_value.adoc[]" as config.ftv_get_parameter_value << IF >> {
  --
}

entity "puml-link:dhw:sqldb:config.parameter.adoc[]" as config.Parameter << U >> {
  - **Parameter_name** : (varchar(100))
  - **sub_Parameter** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:configt.parameter_default.adoc[]" as configT.Parameter_default << V >> {
  - **Parameter_name** : (varchar(52))
  - **sub_Parameter** : (nvarchar(26))
  --
}

entity "puml-link:dhw:sqldb:property.external_repoobjectproperty.adoc[]" as property.external_RepoObjectProperty << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.propertyname_repoobject.adoc[]" as property.PropertyName_RepoObject << V >> {
  **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.propertyname_repoobject_t.adoc[]" as property.PropertyName_RepoObject_T << U >> {
  **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty.adoc[]" as property.RepoObjectProperty << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty_external_src.adoc[]" as property.RepoObjectProperty_external_src << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty_external_tgt.adoc[]" as property.RepoObjectProperty_external_tgt << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty_selectedpropertyname_split.adoc[]" as property.RepoObjectProperty_SelectedPropertyName_split << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference.adoc[]" as reference.additional_Reference << U >> {
  # **tik_hash_c** : (nvarchar(32))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_from_properties_src.adoc[]" as reference.additional_Reference_from_properties_src << V >> {
  **referenced_AntoraComponent** : (nvarchar(max))
  **referenced_AntoraModule** : (nvarchar(max))
  **referenced_Schema** : (nvarchar(max))
  **referenced_Object** : (nvarchar(max))
  **referenced_Column** : (nvarchar(max))
  **referencing_AntoraComponent** : (nvarchar(max))
  **referencing_AntoraModule** : (nvarchar(max))
  **referencing_Schema** : (nvarchar(max))
  **referencing_Object** : (nvarchar(max))
  **referencing_Column** : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_from_properties_tgt.adoc[]" as reference.additional_Reference_from_properties_tgt << V >> {
  **referenced_AntoraComponent** : (nvarchar(max))
  **referenced_AntoraModule** : (nvarchar(max))
  **referenced_Schema** : (nvarchar(max))
  **referenced_Object** : (nvarchar(max))
  **referenced_Column** : (nvarchar(max))
  **referencing_AntoraComponent** : (nvarchar(max))
  **referencing_AntoraModule** : (nvarchar(max))
  **referencing_Schema** : (nvarchar(max))
  **referencing_Object** : (nvarchar(max))
  **referencing_Column** : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_from_ssas_src.adoc[]" as reference.additional_Reference_from_ssas_src << V >> {
  **referenced_AntoraComponent** : (nvarchar(128))
  **referenced_AntoraModule** : (nvarchar(128))
  **referenced_Schema** : (nvarchar(max))
  **referenced_Object** : (nvarchar(max))
  **referenced_Column** : (nvarchar(500))
  **referencing_AntoraComponent** : (nvarchar(max))
  **referencing_AntoraModule** : (nvarchar(max))
  - **referencing_Schema** : (nvarchar(128))
  - **referencing_Object** : (nvarchar(128))
  **referencing_Column** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_from_ssas_tgt.adoc[]" as reference.additional_Reference_from_ssas_tgt << V >> {
  **referenced_AntoraComponent** : (nvarchar(128))
  **referenced_AntoraModule** : (nvarchar(128))
  **referenced_Schema** : (nvarchar(max))
  **referenced_Object** : (nvarchar(max))
  **referenced_Column** : (nvarchar(500))
  **referencing_AntoraComponent** : (nvarchar(max))
  **referencing_AntoraModule** : (nvarchar(max))
  - **referencing_Schema** : (nvarchar(128))
  - **referencing_Object** : (nvarchar(128))
  **referencing_Column** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_is_external.adoc[]" as reference.additional_Reference_is_external << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_object.adoc[]" as reference.additional_Reference_Object << V >> {
  - **AntoraComponent** : (nvarchar(128))
  - **AntoraModule** : (nvarchar(128))
  - **SchemaName** : (nvarchar(128))
  - **ObjectName** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_object_t.adoc[]" as reference.additional_Reference_Object_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_objectcolumn.adoc[]" as reference.additional_Reference_ObjectColumn << V >> {
  - **AntoraComponent** : (nvarchar(128))
  - **AntoraModule** : (nvarchar(128))
  - **SchemaName** : (nvarchar(128))
  - **ObjectName** : (nvarchar(128))
  **ColumnName** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_objectcolumn_t.adoc[]" as reference.additional_Reference_ObjectColumn_T << U >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_wo_columns_from_properties_src.adoc[]" as reference.additional_Reference_wo_columns_from_properties_src << V >> {
  **referenced_AntoraComponent** : (nvarchar(max))
  **referenced_AntoraModule** : (nvarchar(max))
  **referenced_Schema** : (nvarchar(max))
  **referenced_Object** : (nvarchar(max))
  **referencing_AntoraComponent** : (nvarchar(max))
  **referencing_AntoraModule** : (nvarchar(max))
  **referencing_Schema** : (nvarchar(max))
  **referencing_Object** : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_wo_columns_from_properties_tgt.adoc[]" as reference.additional_Reference_wo_columns_from_properties_tgt << V >> {
  **referenced_AntoraComponent** : (nvarchar(max))
  **referenced_AntoraModule** : (nvarchar(max))
  **referenced_Schema** : (nvarchar(max))
  **referenced_Object** : (nvarchar(max))
  **referencing_AntoraComponent** : (nvarchar(max))
  **referencing_AntoraModule** : (nvarchar(max))
  **referencing_Schema** : (nvarchar(max))
  **referencing_Object** : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:repo.index_ssas.adoc[]" as repo.Index_ssas << V >> {
  - **databasename** : (nvarchar(128))
  **index_name** : (nvarchar(450))
  --
}

entity "puml-link:dhw:sqldb:repo.index_ssas_t.adoc[]" as repo.Index_ssas_T << U >> {
  - **databasename** : (nvarchar(128))
  **index_name** : (nvarchar(450))
  --
}

entity "puml-link:dhw:sqldb:repo.indexcolumn_ssas.adoc[]" as repo.IndexColumn_ssas << V >> {
  - **index_guid** : (uniqueidentifier)
  - **index_column_id** : (int)
  --
}

entity "puml-link:dhw:sqldb:repo.indexcolumn_ssas_gross.adoc[]" as repo.IndexColumn_ssas_gross << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.indexcolumn_ssas_t.adoc[]" as repo.IndexColumn_ssas_T << U >> {
  - **index_guid** : (uniqueidentifier)
  - **index_column_id** : (int)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject.adoc[]" as repo.RepoObject << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_external_src.adoc[]" as repo.RepoObject_external_src << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_external_tgt.adoc[]" as repo.RepoObject_external_tgt << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_ssas_src.adoc[]" as repo.RepoObject_SSAS_src << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_ssas_tgt.adoc[]" as repo.RepoObject_SSAS_tgt << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn.adoc[]" as repo.RepoObjectColumn << U >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn_external_src.adoc[]" as repo.RepoObjectColumn_external_src << V >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn_external_tgt.adoc[]" as repo.RepoObjectColumn_external_tgt << V >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn_ssas_src.adoc[]" as repo.RepoObjectColumn_SSAS_src << V >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn_ssas_tgt.adoc[]" as repo.RepoObjectColumn_SSAS_tgt << V >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.reposchema.adoc[]" as repo.RepoSchema << U >> {
  - **RepoSchema_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.reposchema_ssas_src.adoc[]" as repo.RepoSchema_ssas_src << V >> {
  - **RepoSchema_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:repo.reposchema_ssas_tgt.adoc[]" as repo.RepoSchema_ssas_tgt << V >> {
  - **RepoSchema_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:ssas.additional_reference_step1.adoc[]" as ssas.additional_Reference_step1 << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.indexcolumn_from_iskey.adoc[]" as ssas.IndexColumn_from_IsKey << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.indexcolumn_from_isunique.adoc[]" as ssas.IndexColumn_from_IsUnique << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.indexcolumn_from_relationship.adoc[]" as ssas.IndexColumn_from_Relationship << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.indexcolumn_union.adoc[]" as ssas.IndexColumn_union << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json.adoc[]" as ssas.model_json << U >> {
  - **databasename** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_10.adoc[]" as ssas.model_json_10 << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_20.adoc[]" as ssas.model_json_20 << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_201_descriptions_multiline.adoc[]" as ssas.model_json_201_descriptions_multiline << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_2011_descriptions_stragg.adoc[]" as ssas.model_json_2011_descriptions_StrAgg << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31_tables.adoc[]" as ssas.model_json_31_tables << V >> {
  - **databasename** : (nvarchar(128))
  **tables_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31_tables_t.adoc[]" as ssas.model_json_31_tables_T << U >> {
  - **databasename** : (nvarchar(128))
  **tables_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_311_tables_columns.adoc[]" as ssas.model_json_311_tables_columns << V >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  **tables_columns_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_311_tables_columns_t.adoc[]" as ssas.model_json_311_tables_columns_T << U >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  **tables_columns_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_313_tables_partitions.adoc[]" as ssas.model_json_313_tables_partitions << V >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  **tables_partitions_name** : (nvarchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_3131_tables_partitions_source.adoc[]" as ssas.model_json_3131_tables_partitions_source << V >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  **tables_partitions_name** : (nvarchar(500))
  **tables_partitions_source_name** : (nvarchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31311_tables_partitions_source_posfrom.adoc[]" as ssas.model_json_31311_tables_partitions_source_PosFrom << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_313111_tables_partitions_source_stringfrom.adoc[]" as ssas.model_json_313111_tables_partitions_source_StringFrom << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_3131111_tables_partitions_source_posdot.adoc[]" as ssas.model_json_3131111_tables_partitions_source_PosDot << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31311111_tables_partitions_source_part123.adoc[]" as ssas.model_json_31311111_tables_partitions_source_Part123 << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_32_relationships.adoc[]" as ssas.model_json_32_relationships << V >> {
  - **databasename** : (nvarchar(128))
  **relationships_name** : (nvarchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_32_relationships_t.adoc[]" as ssas.model_json_32_relationships_T << U >> {
  - **ForeignKey_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_33_datasources.adoc[]" as ssas.model_json_33_dataSources << V >> {
  - **databasename** : (nvarchar(128))
  **dataSources_name** : (nvarchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_33_datasources_t.adoc[]" as ssas.model_json_33_dataSources_T << U >> {
  - **databasename** : (nvarchar(128))
  **dataSources_name** : (nvarchar(500))
  --
}

config.ftv_get_parameter_value <.. reference.additional_Reference_is_external
config.ftv_get_parameter_value <.. ssas.additional_Reference_step1
config.ftv_get_parameter_value <.. repo.RepoObject_external_src
config.Parameter <.. config.ftv_get_parameter_value
config.Parameter <.. property.PropertyName_RepoObject
configT.Parameter_default <.. config.Parameter
property.external_RepoObjectProperty <.. property.RepoObjectProperty_external_src
property.PropertyName_RepoObject <.. property.PropertyName_RepoObject_T
property.PropertyName_RepoObject_T <.. property.RepoObjectProperty_external_tgt
property.RepoObjectProperty <.. property.PropertyName_RepoObject
property.RepoObjectProperty <.. property.RepoObjectProperty_SelectedPropertyName_split
property.RepoObjectProperty_external_src <.. property.RepoObjectProperty_external_tgt
property.RepoObjectProperty_external_tgt <.. property.RepoObjectProperty
property.RepoObjectProperty_SelectedPropertyName_split <.. reference.additional_Reference_wo_columns_from_properties_src
property.RepoObjectProperty_SelectedPropertyName_split <.. reference.additional_Reference_from_properties_src
reference.additional_Reference <.. reference.additional_Reference_is_external
reference.additional_Reference_from_properties_src <.. reference.additional_Reference_from_properties_tgt
reference.additional_Reference_from_properties_tgt <.. reference.additional_Reference
reference.additional_Reference_from_ssas_src <.. reference.additional_Reference_from_ssas_tgt
reference.additional_Reference_from_ssas_tgt <.. reference.additional_Reference
reference.additional_Reference_is_external <.. reference.additional_Reference_ObjectColumn
reference.additional_Reference_is_external <.. reference.additional_Reference_Object
reference.additional_Reference_Object <.. reference.additional_Reference_Object_T
reference.additional_Reference_Object_T <.. repo.RepoObject_external_src
reference.additional_Reference_Object_T <.. repo.RepoObjectColumn_external_src
reference.additional_Reference_ObjectColumn <.. reference.additional_Reference_ObjectColumn_T
reference.additional_Reference_ObjectColumn_T <.. repo.RepoObjectColumn_external_src
reference.additional_Reference_wo_columns_from_properties_src <.. reference.additional_Reference_wo_columns_from_properties_tgt
reference.additional_Reference_wo_columns_from_properties_tgt <.. reference.additional_Reference
repo.Index_ssas <.. repo.Index_ssas_T
repo.Index_ssas_T <.. repo.IndexColumn_ssas_gross
repo.Index_ssas_T <.. repo.IndexColumn_ssas
repo.IndexColumn_ssas <.. repo.IndexColumn_ssas_T
repo.IndexColumn_ssas_T <.. repo.IndexColumn_ssas_gross
repo.RepoObject <.. repo.RepoObjectColumn_external_src
repo.RepoObject <.. repo.IndexColumn_ssas_gross
repo.RepoObject <.. property.RepoObjectProperty_external_tgt
repo.RepoObject <.. repo.RepoObject_external_src
repo.RepoObject_external_src <.. repo.RepoObject_external_tgt
repo.RepoObject_external_tgt <.. repo.RepoObject
repo.RepoObject_external_tgt <.. repo.RepoObjectColumn_external_tgt
repo.RepoObject_SSAS_src <.. repo.RepoObject_SSAS_tgt
repo.RepoObject_SSAS_tgt <.. repo.RepoObjectColumn_SSAS_tgt
repo.RepoObject_SSAS_tgt <.. repo.RepoObject
repo.RepoObjectColumn <.. repo.IndexColumn_ssas_gross
repo.RepoObjectColumn_external_src <.. repo.RepoObjectColumn_external_tgt
repo.RepoObjectColumn_external_tgt <.. repo.RepoObjectColumn
repo.RepoObjectColumn_SSAS_src <.. repo.RepoObjectColumn_SSAS_tgt
repo.RepoObjectColumn_SSAS_tgt <.. repo.RepoObjectColumn
repo.RepoSchema <.. repo.RepoObject_SSAS_src
repo.RepoSchema_ssas_src <.. repo.RepoSchema_ssas_tgt
repo.RepoSchema_ssas_tgt <.. repo.RepoSchema
ssas.additional_Reference_step1 <.. reference.additional_Reference_from_ssas_src
ssas.IndexColumn_from_IsKey <.. ssas.IndexColumn_union
ssas.IndexColumn_from_IsUnique <.. ssas.IndexColumn_union
ssas.IndexColumn_from_Relationship <.. ssas.IndexColumn_union
ssas.IndexColumn_union <.. repo.Index_ssas
ssas.IndexColumn_union <.. repo.IndexColumn_ssas
ssas.model_json <.. ssas.model_json_10
ssas.model_json_10 <.. ssas.model_json_20
ssas.model_json_20 <.. repo.RepoSchema_ssas_src
ssas.model_json_20 <.. ssas.model_json_31_tables
ssas.model_json_20 <.. ssas.model_json_33_dataSources
ssas.model_json_20 <.. ssas.model_json_201_descriptions_multiline
ssas.model_json_20 <.. ssas.model_json_32_relationships
ssas.model_json_201_descriptions_multiline <.. ssas.model_json_2011_descriptions_StrAgg
ssas.model_json_2011_descriptions_StrAgg <.. repo.RepoSchema_ssas_src
ssas.model_json_31_tables <.. ssas.model_json_31_tables_T
ssas.model_json_31_tables_T <.. ssas.model_json_311_tables_columns
ssas.model_json_31_tables_T <.. repo.RepoObject_SSAS_src
ssas.model_json_31_tables_T <.. ssas.model_json_313_tables_partitions
ssas.model_json_311_tables_columns <.. ssas.model_json_311_tables_columns_T
ssas.model_json_311_tables_columns_T <.. repo.RepoObjectColumn_SSAS_src
ssas.model_json_311_tables_columns_T <.. ssas.IndexColumn_from_IsKey
ssas.model_json_311_tables_columns_T <.. ssas.IndexColumn_from_Relationship
ssas.model_json_311_tables_columns_T <.. ssas.IndexColumn_from_IsUnique
ssas.model_json_311_tables_columns_T <.. ssas.additional_Reference_step1
ssas.model_json_313_tables_partitions <.. ssas.model_json_3131_tables_partitions_source
ssas.model_json_3131_tables_partitions_source <.. ssas.model_json_31311_tables_partitions_source_PosFrom
ssas.model_json_31311_tables_partitions_source_PosFrom <.. ssas.model_json_313111_tables_partitions_source_StringFrom
ssas.model_json_313111_tables_partitions_source_StringFrom <.. ssas.model_json_3131111_tables_partitions_source_PosDot
ssas.model_json_3131111_tables_partitions_source_PosDot <.. ssas.model_json_31311111_tables_partitions_source_Part123
ssas.model_json_31311111_tables_partitions_source_Part123 <.. ssas.additional_Reference_step1
ssas.model_json_32_relationships <.. ssas.model_json_32_relationships_T
ssas.model_json_32_relationships_T <.. ssas.IndexColumn_from_Relationship
ssas.model_json_33_dataSources <.. ssas.model_json_33_dataSources_T
ssas.model_json_33_dataSources_T <.. ssas.additional_Reference_step1

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_30_0_objectref[]

=== PlantUML 0 30 ObjectRef

// tag::puml_entity_0_30_objectref[]
[plantuml, entity_0_30_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:docs.antoranavlistpage_by_schema.adoc[]" as docs.AntoraNavListPage_by_schema << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.antorapage_indexsemanticgroup.adoc[]" as docs.AntoraPage_IndexSemanticGroup << V >> {
  - **page_content** : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:docs.foreignkey_relationscript.adoc[]" as docs.ForeignKey_RelationScript << V >> {
  **referenced_RepoObject_guid** : (uniqueidentifier)
  **referencing_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:docs.ftv_repoobject_reference_plantuml_entityreflist.adoc[]" as docs.ftv_RepoObject_Reference_PlantUml_EntityRefList << IF >> {
  --
}

entity "puml-link:dhw:sqldb:docs.indexsemanticgroup.adoc[]" as docs.IndexSemanticgroup << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.indexsemanticgrouppatterndatatype.adoc[]" as docs.IndexSemanticgroupPatterndatatype << V >> {
  **IndexSemanticGroup** : (nvarchar(512))
  **IndexPatternColumnDatatype** : (nvarchar(4000))
  --
}

entity "puml-link:dhw:sqldb:docs.objectrefcyclic.adoc[]" as docs.ObjectRefCyclic << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.objectrefcyclic_entitylist.adoc[]" as docs.ObjectRefCyclic_EntityList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_adoc.adoc[]" as docs.RepoObject_Adoc << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_adoc_t.adoc[]" as docs.RepoObject_Adoc_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_columnlist.adoc[]" as docs.RepoObject_ColumnList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_columnlist_t.adoc[]" as docs.RepoObject_ColumnList_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_indexlist.adoc[]" as docs.RepoObject_IndexList << V >> {
  **RepoObject_guid** : (uniqueidentifier)
  **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_indexlist_t.adoc[]" as docs.RepoObject_IndexList_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml.adoc[]" as docs.RepoObject_Plantuml << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_entity.adoc[]" as docs.RepoObject_Plantuml_Entity << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_entity_t.adoc[]" as docs.RepoObject_Plantuml_Entity_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_fkreflist.adoc[]" as docs.RepoObject_PlantUml_FkRefList << V >> {
  **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_pumlentityfklist.adoc[]" as docs.RepoObject_PlantUml_PumlEntityFkList << V >> {
  **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_t.adoc[]" as docs.RepoObject_Plantuml_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.schema_entitylist.adoc[]" as docs.Schema_EntityList << V >> {
  - **RepoObject_schema_name** : (nvarchar(128))
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.schema_puml.adoc[]" as docs.Schema_puml << V >> {
  - **RepoSchema_guid** : (uniqueidentifier)
  **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.schema_pumlpartial_fkreflist.adoc[]" as docs.Schema_PumlPartial_FkRefList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport.adoc[]" as docs.usp_AntoraExport << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_objectpartialscontent.adoc[]" as docs.usp_AntoraExport_ObjectPartialsContent << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_objectpuml.adoc[]" as docs.usp_AntoraExport_ObjectPuml << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_repoobject_adoc_t.adoc[]" as docs.usp_PERSIST_RepoObject_Adoc_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_repoobject_columnlist_t.adoc[]" as docs.usp_PERSIST_RepoObject_ColumnList_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_repoobject_indexlist_t.adoc[]" as docs.usp_PERSIST_RepoObject_IndexList_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_repoobject_plantuml_entity_t.adoc[]" as docs.usp_PERSIST_RepoObject_Plantuml_Entity_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_repoobject_plantuml_t.adoc[]" as docs.usp_PERSIST_RepoObject_Plantuml_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty_collect_source_rogross.adoc[]" as property.RepoObjectProperty_Collect_source_ROGross << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **property_name** : (varchar(39))
  --
}

entity "puml-link:dhw:sqldb:property.usp_repoobject_inheritance.adoc[]" as property.usp_RepoObject_Inheritance << P >> {
  --
}

entity "puml-link:dhw:sqldb:property.usp_repoobjectproperty_collect.adoc[]" as property.usp_RepoObjectProperty_collect << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.ftv_repoobject_columreferencerepoobject.adoc[]" as reference.ftv_RepoObject_ColumReferenceRepoObject << IF >> {
  --
}

entity "puml-link:dhw:sqldb:repo.check_indexcolumn_virtual_referenced_setpoint.adoc[]" as repo.check_IndexColumn_virtual_referenced_setpoint << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.foreignkey_gross.adoc[]" as repo.ForeignKey_gross << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.foreignkey_indexes.adoc[]" as repo.ForeignKey_Indexes << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.foreignkey_indexes_union.adoc[]" as repo.ForeignKey_Indexes_union << V >> {
  **ForeignKey_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.foreignkey_indexes_union_t.adoc[]" as repo.ForeignKey_Indexes_union_T << U >> {
  **ForeignKey_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.foreignkey_virtual_indexes.adoc[]" as repo.ForeignKey_virtual_Indexes << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.index_columlist.adoc[]" as repo.Index_ColumList << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.index_columlist_t.adoc[]" as repo.Index_ColumList_T << U >> {
  - **index_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.index_gross.adoc[]" as repo.Index_gross << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.index_indexpattern.adoc[]" as repo.Index_IndexPattern << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.index_referencing_indexpatterncolumnguid.adoc[]" as repo.Index_referencing_IndexPatternColumnGuid << V >> {
  **source_index_guid** : (uniqueidentifier)
  **referencing_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.index_sqlconstraint_pkuq.adoc[]" as repo.Index_SqlConstraint_PkUq << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.indexcolumn_referencedreferencing_hasfullcolumnsinreferencing.adoc[]" as repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing << V >> {
  - **index_guid** : (uniqueidentifier)
  - **index_column_id** : (int)
  **RowNumberInReferencing** : (bigint)
  --
}

entity "puml-link:dhw:sqldb:repo.indexcolumn_referencedreferencing_hasfullcolumnsinreferencing_check.adoc[]" as repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_check << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.indexcolumn_referencedreferencing_hasfullcolumnsinreferencing_t.adoc[]" as repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T << U >> {
  **index_guid** : (uniqueidentifier)
  - **index_column_id** : (int)
  **RowNumberInReferencing** : (bigint)
  --
}

entity "puml-link:dhw:sqldb:repo.indexcolumn_ssas_gross.adoc[]" as repo.IndexColumn_ssas_gross << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.indexcolumn_union.adoc[]" as repo.IndexColumn_union << V >> {
  **index_guid** : (uniqueidentifier)
  - **index_column_id** : (int)
  --
}

entity "puml-link:dhw:sqldb:repo.indexcolumn_union_t.adoc[]" as repo.IndexColumn_union_T << U >> {
  **index_guid** : (uniqueidentifier)
  - **index_column_id** : (int)
  --
}

entity "puml-link:dhw:sqldb:repo.indexcolumn_virtual_referenced_setpoint.adoc[]" as repo.IndexColumn_virtual_referenced_setpoint << V >> {
  - **index_guid** : (uniqueidentifier)
  - **index_column_id** : (int)
  --
}

entity "puml-link:dhw:sqldb:repo.indexreferencedreferencing_hasfullcolumnsinreferencing.adoc[]" as repo.IndexReferencedReferencing_HasFullColumnsInReferencing << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_columnlist.adoc[]" as repo.RepoObject_ColumnList << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_gross2.adoc[]" as repo.RepoObject_gross2 << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_related_fk_union.adoc[]" as repo.RepoObject_related_FK_union << V >> {
  **RepoObject_guid** : (uniqueidentifier)
  **included_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_sat2.adoc[]" as repo.RepoObject_sat2 << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_sat2_t.adoc[]" as repo.RepoObject_sat2_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_sqlcreatetable.adoc[]" as repo.RepoObject_SqlCreateTable << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn_gross2.adoc[]" as repo.RepoObjectColumn_gross2 << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_index_finish.adoc[]" as repo.usp_Index_finish << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_index_foreignkey.adoc[]" as repo.usp_Index_ForeignKey << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_index_inheritance.adoc[]" as repo.usp_index_inheritance << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_index_settings.adoc[]" as repo.usp_Index_Settings << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_index_virtual_set.adoc[]" as repo.usp_Index_virtual_set << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_main.adoc[]" as repo.usp_main << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_persist_foreignkey_indexes_union_t.adoc[]" as repo.usp_PERSIST_ForeignKey_Indexes_union_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_persist_index_columlist_t.adoc[]" as repo.usp_PERSIST_Index_ColumList_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_persist_indexcolumn_referencedreferencing_hasfullcolumnsinreferencing_t.adoc[]" as repo.usp_PERSIST_IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_persist_indexcolumn_union_t.adoc[]" as repo.usp_PERSIST_IndexColumn_union_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_persist_repoobject_sat2_t.adoc[]" as repo.usp_PERSIST_RepoObject_sat2_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.generatoruspstep_persistence_src.adoc[]" as uspgenerator.GeneratorUspStep_Persistence_src << V >> {
  - **usp_id** : (int)
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.usp_generatorusp_insert_update_persistence.adoc[]" as uspgenerator.usp_GeneratorUsp_insert_update_persistence << P >> {
  --
}

docs.ftv_RepoObject_Reference_PlantUml_EntityRefList <.. docs.RepoObject_Plantuml
docs.IndexSemanticgroup <.. docs.AntoraPage_IndexSemanticGroup
docs.IndexSemanticgroupPatterndatatype <.. docs.IndexSemanticgroup
docs.ObjectRefCyclic_EntityList <.. docs.ObjectRefCyclic
docs.RepoObject_Adoc <.. docs.usp_PERSIST_RepoObject_Adoc_T
docs.RepoObject_Adoc <.. docs.RepoObject_Adoc_T
docs.REpoObject_Adoc_T <.. docs.usp_PERSIST_RepoObject_Adoc_T
docs.RepoObject_ColumnList <.. docs.usp_PERSIST_RepoObject_ColumnList_T
docs.RepoObject_ColumnList <.. docs.RepoObject_ColumnList_T
docs.RepoObject_ColumnList_T <.. docs.RepoObject_Adoc
docs.RepoObject_ColumnList_T <.. docs.RepoObject_Plantuml_Entity
docs.RepoObject_ColumnList_T <.. docs.usp_PERSIST_RepoObject_ColumnList_T
docs.RepoObject_IndexList <.. docs.RepoObject_IndexList_T
docs.RepoObject_IndexList <.. docs.usp_PERSIST_RepoObject_IndexList_T
docs.RepoObject_IndexList_T <.. docs.usp_PERSIST_RepoObject_IndexList_T
docs.RepoObject_IndexList_T <.. docs.RepoObject_Plantuml_Entity
docs.RepoObject_IndexList_T <.. docs.RepoObject_Adoc
docs.RepoObject_Plantuml <.. docs.usp_PERSIST_RepoObject_Plantuml_T
docs.RepoObject_Plantuml <.. docs.RepoObject_Plantuml_T
docs.RepoObject_Plantuml_Entity <.. docs.usp_PERSIST_RepoObject_Plantuml_Entity_T
docs.RepoObject_Plantuml_Entity <.. docs.RepoObject_Plantuml_Entity_T
docs.RepoObject_Plantuml_Entity_T <.. docs.RepoObject_Adoc
docs.RepoObject_Plantuml_Entity_T <.. docs.usp_PERSIST_RepoObject_Plantuml_Entity_T
docs.RepoObject_Plantuml_Entity_T <.. docs.ftv_RepoObject_Reference_PlantUml_EntityRefList
docs.RepoObject_Plantuml_Entity_T <.. docs.RepoObject_PlantUml_PumlEntityFkList
docs.RepoObject_Plantuml_Entity_T <.. docs.ObjectRefCyclic_EntityList
docs.RepoObject_Plantuml_Entity_T <.. docs.Schema_EntityList
docs.RepoObject_PlantUml_FkRefList <.. docs.RepoObject_Plantuml
docs.RepoObject_PlantUml_PumlEntityFkList <.. docs.RepoObject_Plantuml
docs.RepoObject_Plantuml_T <.. docs.RepoObject_Adoc
docs.RepoObject_Plantuml_T <.. docs.usp_PERSIST_RepoObject_Plantuml_T
docs.Schema_EntityList <.. docs.Schema_puml
docs.Schema_puml <.. docs.AntoraNavListPage_by_schema
docs.Schema_PumlPartial_FkRefList <.. docs.Schema_puml
docs.usp_AntoraExport_ObjectPartialsContent <.. docs.usp_AntoraExport
docs.usp_AntoraExport_ObjectPuml <.. docs.usp_AntoraExport
docs.usp_PERSIST_RepoObject_Adoc_T <.. docs.usp_AntoraExport_ObjectPartialsContent
docs.usp_PERSIST_RepoObject_ColumnList_T <.. docs.usp_AntoraExport_ObjectPartialsContent
docs.usp_PERSIST_RepoObject_IndexList_T <.. docs.usp_AntoraExport_ObjectPartialsContent
docs.usp_PERSIST_RepoObject_Plantuml_Entity_T <.. docs.usp_AntoraExport_ObjectPuml
docs.usp_PERSIST_RepoObject_Plantuml_T <.. docs.usp_AntoraExport_ObjectPuml
property.RepoObjectProperty_Collect_source_ROGross <.. property.usp_RepoObjectProperty_collect
property.usp_RepoObject_Inheritance <.. repo.usp_main
property.usp_RepoObjectProperty_collect <.. property.usp_RepoObject_Inheritance
property.usp_RepoObjectProperty_collect <.. repo.usp_main
repo.ForeignKey_gross <.. docs.RepoObject_IndexList
repo.ForeignKey_Indexes <.. repo.ForeignKey_Indexes_union
repo.ForeignKey_Indexes <.. repo.usp_Index_ForeignKey
repo.ForeignKey_Indexes_union <.. repo.usp_PERSIST_ForeignKey_Indexes_union_T
repo.ForeignKey_Indexes_union <.. repo.ForeignKey_Indexes_union_T
repo.ForeignKey_Indexes_union_T <.. repo.usp_Index_finish
repo.ForeignKey_Indexes_union_T <.. repo.usp_PERSIST_ForeignKey_Indexes_union_T
repo.ForeignKey_Indexes_union_T <.. docs.Schema_PumlPartial_FkRefList
repo.ForeignKey_Indexes_union_T <.. docs.ForeignKey_RelationScript
repo.ForeignKey_Indexes_union_T <.. repo.ForeignKey_gross
repo.ForeignKey_Indexes_union_T <.. repo.RepoObject_related_FK_union
repo.ForeignKey_Indexes_union_T <.. docs.RepoObject_PlantUml_FkRefList
repo.ForeignKey_virtual_Indexes <.. repo.ForeignKey_Indexes_union
repo.Index_ColumList <.. repo.Index_ColumList_T
repo.Index_ColumList <.. repo.usp_PERSIST_Index_ColumList_T
repo.Index_ColumList_T <.. repo.Index_gross
repo.Index_ColumList_T <.. repo.usp_PERSIST_Index_ColumList_T
repo.Index_ColumList_T <.. repo.Index_SqlConstraint_PkUq
repo.Index_ColumList_T <.. uspgenerator.GeneratorUspStep_Persistence_src
repo.Index_gross <.. repo.usp_Index_finish
repo.Index_gross <.. docs.RepoObject_IndexList
repo.Index_gross <.. docs.IndexSemanticgroupPatterndatatype
repo.Index_gross <.. repo.ForeignKey_gross
repo.Index_gross <.. repo.RepoObject_SqlCreateTable
repo.Index_gross <.. repo.usp_index_inheritance
repo.Index_gross <.. repo.usp_Index_virtual_set
repo.Index_gross <.. repo.ForeignKey_Indexes
repo.Index_gross <.. repo.ForeignKey_virtual_Indexes
repo.Index_IndexPattern <.. repo.usp_Index_Settings
repo.Index_referencing_IndexPatternColumnGuid <.. repo.IndexReferencedReferencing_HasFullColumnsInReferencing
repo.Index_SqlConstraint_PkUq <.. repo.RepoObject_SqlCreateTable
repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing <.. repo.usp_PERSIST_IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T
repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing <.. repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T
repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T <.. repo.IndexColumn_virtual_referenced_setpoint
repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T <.. repo.IndexReferencedReferencing_HasFullColumnsInReferencing
repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T <.. repo.Index_referencing_IndexPatternColumnGuid
repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T <.. repo.usp_PERSIST_IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T
repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T <.. repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_check
repo.IndexColumn_ssas_gross <.. repo.IndexColumn_union
repo.IndexColumn_union <.. repo.usp_PERSIST_IndexColumn_union_T
repo.IndexColumn_union <.. repo.IndexColumn_union_T
repo.IndexColumn_union_T <.. repo.Index_IndexPattern
repo.IndexColumn_union_T <.. repo.Index_ColumList
repo.IndexColumn_union_T <.. repo.usp_PERSIST_IndexColumn_union_T
repo.IndexColumn_union_T <.. repo.RepoObjectColumn_gross2
repo.IndexColumn_union_T <.. repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing
repo.IndexColumn_virtual_referenced_setpoint <.. repo.check_IndexColumn_virtual_referenced_setpoint
repo.IndexColumn_virtual_referenced_setpoint <.. repo.usp_index_inheritance
repo.IndexReferencedReferencing_HasFullColumnsInReferencing <.. repo.usp_index_inheritance
repo.RepoObject_ColumnList <.. repo.RepoObject_sat2
repo.RepoObject_ColumnList <.. repo.RepoObject_gross2
repo.RepoObject_ColumnList <.. repo.RepoObject_SqlCreateTable
repo.RepoObject_gross2 <.. uspgenerator.GeneratorUspStep_Persistence_src
repo.RepoObject_related_FK_union <.. docs.RepoObject_PlantUml_FkRefList
repo.RepoObject_related_FK_union <.. docs.RepoObject_PlantUml_PumlEntityFkList
repo.RepoObject_sat2 <.. repo.RepoObject_sat2_T
repo.RepoObject_sat2 <.. repo.usp_PERSIST_RepoObject_sat2_T
repo.RepoObject_sat2_T <.. repo.usp_PERSIST_RepoObject_sat2_T
repo.RepoObject_sat2_T <.. docs.RepoObject_Adoc
repo.RepoObject_sat2_T <.. property.RepoObjectProperty_Collect_source_ROGross
repo.RepoObject_SqlCreateTable <.. reference.ftv_RepoObject_ColumReferenceRepoObject
repo.RepoObjectColumn_gross2 <.. docs.RepoObject_ColumnList
repo.RepoObjectColumn_gross2 <.. repo.RepoObject_ColumnList
repo.RepoObjectColumn_gross2 <.. uspgenerator.usp_GeneratorUsp_insert_update_persistence
repo.usp_Index_finish <.. repo.usp_Index_ForeignKey
repo.usp_Index_finish <.. repo.usp_index_inheritance
repo.usp_Index_ForeignKey <.. repo.usp_main
repo.usp_index_inheritance <.. repo.usp_main
repo.usp_Index_Settings <.. repo.usp_Index_finish
repo.usp_Index_virtual_set <.. repo.usp_Index_ForeignKey
repo.usp_PERSIST_ForeignKey_Indexes_union_T <.. repo.usp_Index_ForeignKey
repo.usp_PERSIST_Index_ColumList_T <.. repo.usp_Index_finish
repo.usp_PERSIST_IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T <.. repo.usp_index_inheritance
repo.usp_PERSIST_IndexColumn_union_T <.. repo.usp_Index_finish
repo.usp_PERSIST_RepoObject_sat2_T <.. repo.usp_main
uspgenerator.GeneratorUspStep_Persistence_src <.. uspgenerator.usp_GeneratorUsp_insert_update_persistence
uspgenerator.usp_GeneratorUsp_insert_update_persistence <.. repo.usp_main

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_0_30_objectref[]

=== PlantUML 1 1 ColumnRef

// tag::puml_entity_1_1_colref[]
[plantuml, entity_1_1_colref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:repo.index_ssas_t.adoc[]" as repo.Index_ssas_T << U >> {
  - **databasename** : (nvarchar(128))
  **index_name** : (nvarchar(450))
  - ColumnName : (nvarchar(128))
  - index_guid : (uniqueidentifier)
  - is_index_primary_key : (bit)
  - is_index_unique : (bit)
  - RepoObject_guid : (uniqueidentifier)
  - TableID : (numeric(20, 0))
  - TableName : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:repo.indexcolumn_ssas_gross.adoc[]" as repo.IndexColumn_ssas_gross << V >> {
  column_user_type_fullname : (nvarchar(128))
  - index_column_id : (int)
  - index_guid : (uniqueidentifier)
  - index_name : (nvarchar(450))
  is_descending_key : (bit)
  - is_index_primary_key : (bit)
  is_index_real : (bit)
  - is_index_unique : (bit)
  - Object_column_name : (nvarchar(128))
  parent_Object_fullname : (nvarchar(261))
  parent_Object_name : (nvarchar(128))
  - parent_RepoObject_guid : (uniqueidentifier)
  parent_schema_name : (nvarchar(128))
  - RepoObjectColumn_guid : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.indexcolumn_ssas_t.adoc[]" as repo.IndexColumn_ssas_T << U >> {
  - **index_guid** : (uniqueidentifier)
  - **index_column_id** : (int)
  - ColumnName : (nvarchar(128))
  - ColumnType : (bigint)
  - databasename : (nvarchar(128))
  - RepoObjectColumn_guid : (uniqueidentifier)
  - TableID : (numeric(20, 0))
  - TableName : (nvarchar(max))
  ~ is_descending_key : (bit)
  --
}

entity "puml-link:dhw:sqldb:repo.indexcolumn_union.adoc[]" as repo.IndexColumn_union << V >> {
  **index_guid** : (uniqueidentifier)
  - **index_column_id** : (int)
  ColumnsPerIndex : (int)
  index_name : (nvarchar(450))
  is_descending_key : (bit)
  is_index_primary_key : (bit)
  is_index_real : (bit)
  is_index_unique : (bit)
  parent_RepoObject_guid : (uniqueidentifier)
  parent_schema_name : (nvarchar(128))
  parent_SysObject_fullname : (nvarchar(261))
  parent_SysObject_name : (nvarchar(128))
  RepoObjectColumn_guid : (uniqueidentifier)
  SysObject_column_name : (nvarchar(128))
  SysObject_column_user_type_fullname : (nvarchar(182))
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject.adoc[]" as repo.RepoObject << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  external_AntoraComponent : (nvarchar(128))
  external_AntoraModule : (nvarchar(128))
  has_execution_plan_issue : (bit)
  has_get_referenced_issue : (bit)
  indent_sql_modules_definition : (tinyint)
  Inheritance_Source_fullname : (nvarchar(261))
  Inheritance_StringAggSeparatorSql : (nvarchar(4000))
  InheritanceDefinition : (nvarchar(4000))
  InheritanceType : (tinyint)
  - is_DocsExclude : (bit)
  - is_external : (bit)
  is_repo_managed : (bit)
  is_required_ObjectMerge : (bit)
  - is_ssas : (bit)
  is_SysObject_missing : (bit)
  - modify_dt : (datetime)
  pk_index_guid : (uniqueidentifier)
  pk_IndexPatternColumnName_new : (nvarchar(4000))
  Repo_history_table_guid : (uniqueidentifier)
  Repo_temporal_type : (tinyint)
  - RepoObject_name : (nvarchar(128))
  RepoObject_Referencing_Count : (int)
  - RepoObject_schema_name : (nvarchar(128))
  - RepoObject_type : (char(2))
  SysObject_id : (int)
  SysObject_modify_date : (datetime)
  - SysObject_name : (nvarchar(128))
  - SysObject_parent_object_id : (int)
  - SysObject_schema_name : (nvarchar(128))
  SysObject_type : (char(2))
  ~ has_different_sys_names : (bit)
  # is_RepoObject_name_uniqueidentifier : (int)
  # is_SysObject_name_uniqueidentifier : (int)
  ~ node_id : (bigint)
  # RepoObject_fullname : (nvarchar(261))
  # RepoObject_fullname2 : (nvarchar(257))
  # SysObject_fullname : (nvarchar(261))
  # SysObject_fullname2 : (nvarchar(257))
  ~ SysObject_query_sql : (nvarchar(406))
  ~ usp_persistence_fullname : (nvarchar(273))
  # usp_persistence_fullname2 : (nvarchar(269))
  # usp_persistence_name : (nvarchar(140))
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn.adoc[]" as repo.RepoObjectColumn << U >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  Inheritance_StringAggSeparatorSql : (nvarchar(4000))
  InheritanceDefinition : (nvarchar(4000))
  InheritanceType : (tinyint)
  is_persistence_Ignore : (bit)
  is_persistence_NoCompareButUpdate : (bit)
  is_persistence_NoCompareNoUpdate : (bit)
  is_query_plan_expression : (bit)
  is_required_ColumnMerge : (bit)
  is_SysObjectColumn_missing : (bit)
  persistence_source_RepoObjectColumn_guid : (uniqueidentifier)
  Referencing_Count : (int)
  Repo_default_definition : (nvarchar(max))
  Repo_default_is_system_named : (bit)
  Repo_default_name : (nvarchar(128))
  Repo_definition : (nvarchar(max))
  - Repo_generated_always_type : (tinyint)
  Repo_graph_type : (int)
  Repo_increment_value : (sql_variant)
  - Repo_is_computed : (bit)
  - Repo_is_identity : (bit)
  Repo_is_nullable : (bit)
  Repo_is_persisted : (bit)
  Repo_seed_value : (sql_variant)
  Repo_user_type_fullname : (nvarchar(128))
  Repo_user_type_name : (nvarchar(128))
  Repo_uses_database_collation : (bit)
  - RepoObject_guid : (uniqueidentifier)
  RepoObjectColumn_column_id : (int)
  - RepoObjectColumn_name : (nvarchar(128))
  SysObjectColumn_column_id : (int)
  - SysObjectColumn_name : (nvarchar(128))
  # Column_name : (nvarchar(128))
  ~ has_different_sys_names : (bit)
  # is_RepoObjectColumn_name_uniqueidentifier : (int)
  # is_SysObjectColumn_name_uniqueidentifier : (int)
  --
}

repo.Index_ssas_T <.. repo.IndexColumn_ssas_gross
repo.IndexColumn_ssas_gross <.. repo.IndexColumn_union
repo.IndexColumn_ssas_T <.. repo.IndexColumn_ssas_gross
repo.RepoObject <.. repo.IndexColumn_ssas_gross
repo.RepoObjectColumn <.. repo.IndexColumn_ssas_gross
"repo.Index_ssas_T::index_name" <-- "repo.IndexColumn_ssas_gross::index_name"
"repo.Index_ssas_T::is_index_primary_key" <-- "repo.IndexColumn_ssas_gross::is_index_primary_key"
"repo.Index_ssas_T::is_index_unique" <-- "repo.IndexColumn_ssas_gross::is_index_unique"
"repo.Index_ssas_T::RepoObject_guid" <-- "repo.IndexColumn_ssas_gross::parent_RepoObject_guid"
"repo.IndexColumn_ssas_T::index_column_id" <-- "repo.IndexColumn_ssas_gross::index_column_id"
"repo.IndexColumn_ssas_T::index_guid" <-- "repo.IndexColumn_ssas_gross::index_guid"
"repo.IndexColumn_ssas_T::is_descending_key" <-- "repo.IndexColumn_ssas_gross::is_descending_key"
"repo.IndexColumn_ssas_T::RepoObjectColumn_guid" <-- "repo.IndexColumn_ssas_gross::RepoObjectColumn_guid"
"repo.RepoObject::RepoObject_fullname" <-- "repo.IndexColumn_ssas_gross::parent_Object_fullname"
"repo.RepoObject::RepoObject_name" <-- "repo.IndexColumn_ssas_gross::parent_Object_name"
"repo.RepoObject::RepoObject_schema_name" <-- "repo.IndexColumn_ssas_gross::parent_schema_name"
"repo.RepoObjectColumn::Repo_user_type_fullname" <-- "repo.IndexColumn_ssas_gross::column_user_type_fullname"
"repo.RepoObjectColumn::RepoObjectColumn_name" <-- "repo.IndexColumn_ssas_gross::Object_column_name"

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_colref[]


== sql_modules_definition

// tag::sql_modules_definition[]
[%collapsible]
=======
[source,sql,numbered,indent=0]
----

Create View repo.IndexColumn_ssas_gross
As
Select
    icv.index_guid
  , icv.index_column_id
  , icv.is_descending_key
  , icv.RepoObjectColumn_guid
  , parent_RepoObject_guid    = iv.RepoObject_guid
  , iv.index_name
  , parent_schema_name        = ro.RepoObject_schema_name
  , parent_Object_name        = ro.RepoObject_name
  , Object_column_name        = roc.RepoObjectColumn_name
  , column_user_type_fullname = roc.Repo_user_type_fullname
  , iv.is_index_unique
  , iv.is_index_primary_key
  , parent_Object_fullname    = ro.RepoObject_fullname
  , is_index_real             = Cast(1 As Bit)
From
    repo.IndexColumn_ssas_T   As icv
    Inner Join
        repo.Index_ssas_T     As iv
            On
            icv.index_guid            = iv.index_guid

    Inner Join
        repo.RepoObjectColumn As roc
            On
            roc.RepoObjectColumn_guid = icv.RepoObjectColumn_guid

    Left Join
        repo.RepoObject       As ro
            On
            ro.RepoObject_guid        = iv.RepoObject_guid

----
=======
// end::sql_modules_definition[]


