// tag::HeaderFullDisplayName[]
= repo_sys.ExtendedProperties_ParameterForAddUpdateDrop - V
// end::HeaderFullDisplayName[]

== existing_properties

// tag::existing_properties[]

:ExistsProperty--antorareferencedlist:
:ExistsProperty--antorareferencinglist:
:ExistsProperty--is_repo_managed:
:ExistsProperty--is_ssas:
:ExistsProperty--referencedobjectlist:
:ExistsProperty--sql_modules_definition:
:ExistsProperty--FK:
:ExistsProperty--Columns:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
4D90291C-9D61-EB11-84DC-A81E8446D5B0
// end::RepoObject_guid[]

== RepoObject_FullDisplayName2

// tag::RepoObject_FullDisplayName2[]
repo_sys.ExtendedProperties_ParameterForAddUpdateDrop
// end::RepoObject_FullDisplayName2[]

== SysObject_type

// tag::SysObject_type[]
V 
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
view
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
596913198
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2021-10-02 13:23:34
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]
[discrete]
== _


[#column-class]
=== class

[cols="d,8a,m,m,m"]
|===
|
|class
|tinyint
|NOT NULL
|
|===

.Referenced Columns
--
* xref:repo_sys.extendedproperties.adoc#column-class[+repo_sys.ExtendedProperties.class+]
--


[#column-classunderlinedesc]
=== class_desc

[cols="d,8a,m,m,m"]
|===
|
|class_desc
|nvarchar(60)
|NULL
|
|===

.Referenced Columns
--
* xref:repo_sys.extendedproperties.adoc#column-classunderlinedesc[+repo_sys.ExtendedProperties.class_desc+]
--


[#column-level0name]
=== level0name

[cols="d,8a,m,m,m"]
|===
|
|level0name
|nvarchar(128)
|NULL
|
|===

.Referenced Columns
--
* xref:repo_sys.extendedproperties.adoc#column-sysobjectunderlineschemaunderlinename[+repo_sys.ExtendedProperties.SysObject_schema_name+]
--


[#column-level0type]
=== level0type

[cols="d,8a,m,m,m"]
|===
|
|level0type
|varchar(6)
|NOT NULL
|
|===


[#column-level1name]
=== level1name

[cols="d,8a,m,m,m"]
|===
|
|level1name
|nvarchar(128)
|NULL
|
|===


[#column-level1type]
=== level1type

[cols="d,8a,m,m,m"]
|===
|
|level1type
|varchar(9)
|NULL
|
|===


[#column-level2name]
=== level2name

[cols="d,8a,m,m,m"]
|===
|
|level2name
|nvarchar(128)
|NULL
|
|===


[#column-level2type]
=== level2type

[cols="d,8a,m,m,m"]
|===
|
|level2type
|varchar(10)
|NULL
|
|===


[#column-minorunderlineid]
=== minor_id

[cols="d,8a,m,m,m"]
|===
|
|minor_id
|int
|NOT NULL
|
|===

.Referenced Columns
--
* xref:repo_sys.extendedproperties.adoc#column-minorunderlineid[+repo_sys.ExtendedProperties.minor_id+]
--


[#column-propertyunderlinename]
=== property_name

[cols="d,8a,m,m,m"]
|===
|
|property_name
|sysname
|NOT NULL
|
|===

.Referenced Columns
--
* xref:repo_sys.extendedproperties.adoc#column-propertyunderlinename[+repo_sys.ExtendedProperties.property_name+]
--


[#column-propertyunderlinevalue]
=== property_value

[cols="d,8a,m,m,m"]
|===
|
|property_value
|sql_variant
|NULL
|
|===

.Referenced Columns
--
* xref:repo_sys.extendedproperties.adoc#column-propertyunderlinevalue[+repo_sys.ExtendedProperties.property_value+]
--


[#column-type]
=== type

[cols="d,8a,m,m,m"]
|===
|
|type
|char(2)
|NULL
|
|===


[#column-typeunderlinelevel1type]
=== type_level1type

[cols="d,8a,m,m,m"]
|===
|
|type_level1type
|varchar(9)
|NULL
|
|===

.Referenced Columns
--
* xref:configt.type_level1type_level2type.adoc#column-level1type[+configT.type_level1type_level2type.level1type+]
--


[#column-typeunderlinelevel2type]
=== type_level2type

[cols="d,8a,m,m,m"]
|===
|
|type_level2type
|varchar(10)
|NULL
|
|===

.Referenced Columns
--
* xref:configt.type_level1type_level2type.adoc#column-level2type[+configT.type_level1type_level2type.level2type+]
--


// end::AntoraColumnDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]














// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]
|
|<<column-class>>
|tinyint
|NOT NULL
|

|
|<<column-classunderlinedesc>>
|nvarchar(60)
|NULL
|

|
|<<column-level0name>>
|nvarchar(128)
|NULL
|

|
|<<column-level0type>>
|varchar(6)
|NOT NULL
|

|
|<<column-level1name>>
|nvarchar(128)
|NULL
|

|
|<<column-level1type>>
|varchar(9)
|NULL
|

|
|<<column-level2name>>
|nvarchar(128)
|NULL
|

|
|<<column-level2type>>
|varchar(10)
|NULL
|

|
|<<column-minorunderlineid>>
|int
|NOT NULL
|

|
|<<column-propertyunderlinename>>
|sysname
|NOT NULL
|

|
|<<column-propertyunderlinevalue>>
|sql_variant
|NULL
|

|
|<<column-type>>
|char(2)
|NULL
|

|
|<<column-typeunderlinelevel1type>>
|varchar(9)
|NULL
|

|
|<<column-typeunderlinelevel2type>>
|varchar(10)
|NULL
|

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

// end::AntoraIndexList[]

== AntoraMeasureDetails

// tag::AntoraMeasureDetails[]

// end::AntoraMeasureDetails[]

== AntoraMeasureDescriptions



== AntoraParameterList

// tag::AntoraParameterList[]

// end::AntoraParameterList[]

== AntoraXrefCulturesList

// tag::AntoraXrefCulturesList[]
* xref:dhw:sqldb:repo_sys.extendedproperties_parameterforaddupdatedrop.adoc[] - 
// end::AntoraXrefCulturesList[]

== cultures_count

// tag::cultures_count[]
1
// end::cultures_count[]

== Other tags

source: property.RepoObjectProperty_cross As rop_cross


=== additional_reference_csv

// tag::additional_reference_csv[]

// end::additional_reference_csv[]


=== AdocUspSteps

// tag::adocuspsteps[]

// end::adocuspsteps[]


=== AntoraReferencedList

// tag::antorareferencedlist[]
* xref:dhw:sqldb:configt.type_level1type_level2type.adoc[]
* xref:dhw:sqldb:repo_sys.extendedproperties.adoc[]
* xref:dhw:sqldb:sys_dwh.objects.adoc[]
// end::antorareferencedlist[]


=== AntoraReferencingList

// tag::antorareferencinglist[]
* xref:dhw:sqldb:property.usp_sync_extendedproperties_repo2sys_delete.adoc[]
* xref:dhw:sqldb:property.usp_sync_extendedproperties_repo2sys_insertupdate.adoc[]
* xref:dhw:sqldb:repo_sys.usp_dropextendedproperty_level_0.adoc[]
* xref:dhw:sqldb:repo_sys.usp_dropextendedproperty_level_1.adoc[]
// end::antorareferencinglist[]


=== Description

// tag::description[]

// end::description[]


=== exampleUsage

// tag::exampleusage[]

// end::exampleusage[]


=== exampleUsage_2

// tag::exampleusage_2[]

// end::exampleusage_2[]


=== exampleUsage_3

// tag::exampleusage_3[]

// end::exampleusage_3[]


=== exampleUsage_4

// tag::exampleusage_4[]

// end::exampleusage_4[]


=== exampleUsage_5

// tag::exampleusage_5[]

// end::exampleusage_5[]


=== exampleWrong_Usage

// tag::examplewrong_usage[]

// end::examplewrong_usage[]


=== has_execution_plan_issue

// tag::has_execution_plan_issue[]

// end::has_execution_plan_issue[]


=== has_get_referenced_issue

// tag::has_get_referenced_issue[]

// end::has_get_referenced_issue[]


=== has_history

// tag::has_history[]

// end::has_history[]


=== has_history_columns

// tag::has_history_columns[]

// end::has_history_columns[]


=== InheritanceType

// tag::inheritancetype[]

// end::inheritancetype[]


=== is_persistence

// tag::is_persistence[]

// end::is_persistence[]


=== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]

// end::is_persistence_check_duplicate_per_pk[]


=== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]

// end::is_persistence_check_for_empty_source[]


=== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]

// end::is_persistence_delete_changed[]


=== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]

// end::is_persistence_delete_missing[]


=== is_persistence_insert

// tag::is_persistence_insert[]

// end::is_persistence_insert[]


=== is_persistence_truncate

// tag::is_persistence_truncate[]

// end::is_persistence_truncate[]


=== is_persistence_update_changed

// tag::is_persistence_update_changed[]

// end::is_persistence_update_changed[]


=== is_repo_managed

// tag::is_repo_managed[]
0
// end::is_repo_managed[]


=== is_ssas

// tag::is_ssas[]
0
// end::is_ssas[]


=== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


=== MS_Description

// tag::ms_description[]

// end::ms_description[]


=== persistence_source_RepoObject_fullname

// tag::persistence_source_repoobject_fullname[]

// end::persistence_source_repoobject_fullname[]


=== persistence_source_RepoObject_fullname2

// tag::persistence_source_repoobject_fullname2[]

// end::persistence_source_repoobject_fullname2[]


=== persistence_source_RepoObject_guid

// tag::persistence_source_repoobject_guid[]

// end::persistence_source_repoobject_guid[]


=== persistence_source_RepoObject_xref

// tag::persistence_source_repoobject_xref[]

// end::persistence_source_repoobject_xref[]


=== pk_index_guid

// tag::pk_index_guid[]

// end::pk_index_guid[]


=== pk_IndexPatternColumnDatatype

// tag::pk_indexpatterncolumndatatype[]

// end::pk_indexpatterncolumndatatype[]


=== pk_IndexPatternColumnName

// tag::pk_indexpatterncolumnname[]

// end::pk_indexpatterncolumnname[]


=== pk_IndexSemanticGroup

// tag::pk_indexsemanticgroup[]

// end::pk_indexsemanticgroup[]


=== ReferencedObjectList

// tag::referencedobjectlist[]
* [configT].[type_level1type_level2type]
* [repo_sys].[ExtendedProperties]
* [sys_dwh].[objects]
// end::referencedobjectlist[]


=== usp_persistence_RepoObject_guid

// tag::usp_persistence_repoobject_guid[]

// end::usp_persistence_repoobject_guid[]


=== UspExamples

// tag::uspexamples[]

// end::uspexamples[]


=== uspgenerator_usp_id

// tag::uspgenerator_usp_id[]

// end::uspgenerator_usp_id[]


=== UspParameters

// tag::uspparameters[]

// end::uspparameters[]

== Boolean Attributes

source: property.RepoObjectProperty WHERE property_int = 1

// tag::boolean_attributes[]


// end::boolean_attributes[]

== PlantUML diagrams

=== PlantUML Entity

// tag::puml_entity[]
[plantuml, entity-{docname}, svg, subs=macros]
....
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:repo_sys.extendedproperties_parameterforaddupdatedrop.adoc[]" as repo_sys.ExtendedProperties_ParameterForAddUpdateDrop << V >> {
  - class : (tinyint)
  class_desc : (nvarchar(60))
  level0name : (nvarchar(128))
  - level0type : (varchar(6))
  level1name : (nvarchar(128))
  level1type : (varchar(9))
  level2name : (nvarchar(128))
  level2type : (varchar(10))
  - minor_id : (int)
  - property_name : (sysname)
  property_value : (sql_variant)
  type : (char(2))
  type_level1type : (varchar(9))
  type_level2type : (varchar(10))
  --
}
....

// end::puml_entity[]

=== PlantUML Entity 1 1 FK

// tag::puml_entity_1_1_fk[]
[plantuml, entity_1_1_fk-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:repo_sys.extendedproperties_parameterforaddupdatedrop.adoc[]" as repo_sys.ExtendedProperties_ParameterForAddUpdateDrop << V >> {

}



footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_fk[]

=== PlantUML 1 1 ObjectRef

// tag::puml_entity_1_1_objectref[]
[plantuml, entity_1_1_objectref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:configt.type_level1type_level2type.adoc[]" as configT.type_level1type_level2type << V >> {
  **type** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.usp_sync_extendedproperties_repo2sys_delete.adoc[]" as property.usp_sync_ExtendedProperties_Repo2Sys_Delete << P >> {
  --
}

entity "puml-link:dhw:sqldb:property.usp_sync_extendedproperties_repo2sys_insertupdate.adoc[]" as property.usp_sync_ExtendedProperties_Repo2Sys_InsertUpdate << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo_sys.extendedproperties.adoc[]" as repo_sys.ExtendedProperties << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo_sys.extendedproperties_parameterforaddupdatedrop.adoc[]" as repo_sys.ExtendedProperties_ParameterForAddUpdateDrop << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo_sys.usp_dropextendedproperty_level_0.adoc[]" as repo_sys.usp_dropextendedproperty_level_0 << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo_sys.usp_dropextendedproperty_level_1.adoc[]" as repo_sys.usp_dropextendedproperty_level_1 << P >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.objects.adoc[]" as sys_dwh.objects << SN >> {
  --
}

configT.type_level1type_level2type <.. repo_sys.ExtendedProperties_ParameterForAddUpdateDrop
repo_sys.ExtendedProperties <.. repo_sys.ExtendedProperties_ParameterForAddUpdateDrop
repo_sys.ExtendedProperties_ParameterForAddUpdateDrop <.. repo_sys.usp_dropextendedproperty_level_1
repo_sys.ExtendedProperties_ParameterForAddUpdateDrop <.. property.usp_sync_ExtendedProperties_Repo2Sys_InsertUpdate
repo_sys.ExtendedProperties_ParameterForAddUpdateDrop <.. property.usp_sync_ExtendedProperties_Repo2Sys_Delete
repo_sys.ExtendedProperties_ParameterForAddUpdateDrop <.. repo_sys.usp_dropextendedproperty_level_0
sys_dwh.objects <.. repo_sys.ExtendedProperties_ParameterForAddUpdateDrop

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_objectref[]

=== PlantUML 30 0 ObjectRef

// tag::puml_entity_30_0_objectref[]
[plantuml, entity_30_0_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:config.ftv_dwh_database.adoc[]" as config.ftv_dwh_database << IF >> {
  --
}

entity "puml-link:dhw:sqldb:config.parameter.adoc[]" as config.Parameter << U >> {
  - **Parameter_name** : (varchar(100))
  - **sub_Parameter** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:configt.parameter_default.adoc[]" as configT.Parameter_default << V >> {
  - **Parameter_name** : (varchar(52))
  - **sub_Parameter** : (nvarchar(26))
  --
}

entity "puml-link:dhw:sqldb:configt.spt_values.adoc[]" as configT.spt_values << U >> {
  --
}

entity "puml-link:dhw:sqldb:configt.type.adoc[]" as configT.type << V >> {
  **type** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:configt.type_level1type_level2type.adoc[]" as configT.type_level1type_level2type << V >> {
  **type** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:repo_sys.extendedproperties.adoc[]" as repo_sys.ExtendedProperties << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo_sys.extendedproperties_parameterforaddupdatedrop.adoc[]" as repo_sys.ExtendedProperties_ParameterForAddUpdateDrop << V >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.columns.adoc[]" as sys_dwh.columns << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.extended_properties.adoc[]" as sys_dwh.extended_properties << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.indexes.adoc[]" as sys_dwh.indexes << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.objects.adoc[]" as sys_dwh.objects << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.parameters.adoc[]" as sys_dwh.parameters << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.schemas.adoc[]" as sys_dwh.schemas << SN >> {
  --
}

config.ftv_dwh_database <.. repo_sys.ExtendedProperties
config.Parameter <.. config.ftv_dwh_database
configT.Parameter_default <.. config.Parameter
configT.spt_values <.. configT.type
configT.type <.. configT.type_level1type_level2type
configT.type_level1type_level2type <.. repo_sys.ExtendedProperties_ParameterForAddUpdateDrop
repo_sys.ExtendedProperties <.. repo_sys.ExtendedProperties_ParameterForAddUpdateDrop
sys_dwh.columns <.. repo_sys.ExtendedProperties
sys_dwh.extended_properties <.. repo_sys.ExtendedProperties
sys_dwh.indexes <.. repo_sys.ExtendedProperties
sys_dwh.objects <.. repo_sys.ExtendedProperties
sys_dwh.objects <.. repo_sys.ExtendedProperties_ParameterForAddUpdateDrop
sys_dwh.parameters <.. repo_sys.ExtendedProperties
sys_dwh.schemas <.. repo_sys.ExtendedProperties

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_30_0_objectref[]

=== PlantUML 0 30 ObjectRef

// tag::puml_entity_0_30_objectref[]
[plantuml, entity_0_30_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:property.usp_sync_extendedproperties_repo2sys_delete.adoc[]" as property.usp_sync_ExtendedProperties_Repo2Sys_Delete << P >> {
  --
}

entity "puml-link:dhw:sqldb:property.usp_sync_extendedproperties_repo2sys_insertupdate.adoc[]" as property.usp_sync_ExtendedProperties_Repo2Sys_InsertUpdate << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo_sys.extendedproperties_parameterforaddupdatedrop.adoc[]" as repo_sys.ExtendedProperties_ParameterForAddUpdateDrop << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo_sys.usp_dropextendedproperty_level_0.adoc[]" as repo_sys.usp_dropextendedproperty_level_0 << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo_sys.usp_dropextendedproperty_level_1.adoc[]" as repo_sys.usp_dropextendedproperty_level_1 << P >> {
  --
}

repo_sys.ExtendedProperties_ParameterForAddUpdateDrop <.. repo_sys.usp_dropextendedproperty_level_1
repo_sys.ExtendedProperties_ParameterForAddUpdateDrop <.. property.usp_sync_ExtendedProperties_Repo2Sys_InsertUpdate
repo_sys.ExtendedProperties_ParameterForAddUpdateDrop <.. property.usp_sync_ExtendedProperties_Repo2Sys_Delete
repo_sys.ExtendedProperties_ParameterForAddUpdateDrop <.. repo_sys.usp_dropextendedproperty_level_0

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_0_30_objectref[]

=== PlantUML 1 1 ColumnRef

// tag::puml_entity_1_1_colref[]
[plantuml, entity_1_1_colref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:configt.type_level1type_level2type.adoc[]" as configT.type_level1type_level2type << V >> {
  **type** : (nvarchar(128))
  level1type : (varchar(9))
  level2type : (varchar(10))
  type_desc : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.usp_sync_extendedproperties_repo2sys_delete.adoc[]" as property.usp_sync_ExtendedProperties_Repo2Sys_Delete << P >> {
  --
}

entity "puml-link:dhw:sqldb:property.usp_sync_extendedproperties_repo2sys_insertupdate.adoc[]" as property.usp_sync_ExtendedProperties_Repo2Sys_InsertUpdate << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo_sys.extendedproperties.adoc[]" as repo_sys.ExtendedProperties << V >> {
  - class : (tinyint)
  class_desc : (nvarchar(60))
  entity_column_name : (nvarchar(128))
  entity_index_name : (nvarchar(128))
  entity_parameter_name : (nvarchar(128))
  level2type : (varchar(9))
  - major_id : (int)
  - minor_id : (int)
  minor_name : (nvarchar(128))
  parent_name : (sysname)
  parent_object_id : (int)
  parent_type : (char(2))
  property_basetype : (sql_variant)
  - property_name : (sysname)
  property_nvarchar : (nvarchar(4000))
  property_value : (sql_variant)
  SysObject_name : (nvarchar(128))
  SysObject_schema_name : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:repo_sys.extendedproperties_parameterforaddupdatedrop.adoc[]" as repo_sys.ExtendedProperties_ParameterForAddUpdateDrop << V >> {
  - class : (tinyint)
  class_desc : (nvarchar(60))
  level0name : (nvarchar(128))
  - level0type : (varchar(6))
  level1name : (nvarchar(128))
  level1type : (varchar(9))
  level2name : (nvarchar(128))
  level2type : (varchar(10))
  - minor_id : (int)
  - property_name : (sysname)
  property_value : (sql_variant)
  type : (char(2))
  type_level1type : (varchar(9))
  type_level2type : (varchar(10))
  --
}

entity "puml-link:dhw:sqldb:repo_sys.usp_dropextendedproperty_level_0.adoc[]" as repo_sys.usp_dropextendedproperty_level_0 << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo_sys.usp_dropextendedproperty_level_1.adoc[]" as repo_sys.usp_dropextendedproperty_level_1 << P >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.objects.adoc[]" as sys_dwh.objects << SN >> {
  --
}

configT.type_level1type_level2type <.. repo_sys.ExtendedProperties_ParameterForAddUpdateDrop
repo_sys.ExtendedProperties <.. repo_sys.ExtendedProperties_ParameterForAddUpdateDrop
repo_sys.ExtendedProperties_ParameterForAddUpdateDrop <.. repo_sys.usp_dropextendedproperty_level_1
repo_sys.ExtendedProperties_ParameterForAddUpdateDrop <.. property.usp_sync_ExtendedProperties_Repo2Sys_InsertUpdate
repo_sys.ExtendedProperties_ParameterForAddUpdateDrop <.. property.usp_sync_ExtendedProperties_Repo2Sys_Delete
repo_sys.ExtendedProperties_ParameterForAddUpdateDrop <.. repo_sys.usp_dropextendedproperty_level_0
sys_dwh.objects <.. repo_sys.ExtendedProperties_ParameterForAddUpdateDrop
"configT.type_level1type_level2type::level1type" <-- "repo_sys.ExtendedProperties_ParameterForAddUpdateDrop::type_level1type"
"configT.type_level1type_level2type::level2type" <-- "repo_sys.ExtendedProperties_ParameterForAddUpdateDrop::type_level2type"
"repo_sys.ExtendedProperties::class" <-- "repo_sys.ExtendedProperties_ParameterForAddUpdateDrop::class"
"repo_sys.ExtendedProperties::class_desc" <-- "repo_sys.ExtendedProperties_ParameterForAddUpdateDrop::class_desc"
"repo_sys.ExtendedProperties::minor_id" <-- "repo_sys.ExtendedProperties_ParameterForAddUpdateDrop::minor_id"
"repo_sys.ExtendedProperties::property_name" <-- "repo_sys.ExtendedProperties_ParameterForAddUpdateDrop::property_name"
"repo_sys.ExtendedProperties::property_value" <-- "repo_sys.ExtendedProperties_ParameterForAddUpdateDrop::property_value"
"repo_sys.ExtendedProperties::SysObject_schema_name" <-- "repo_sys.ExtendedProperties_ParameterForAddUpdateDrop::level0name"

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_colref[]


== sql_modules_definition

// tag::sql_modules_definition[]
[%collapsible]
=======
[source,sql,numbered,indent=0]
----


CREATE View repo_sys.ExtendedProperties_ParameterForAddUpdateDrop
As
--
Select
    sep.property_name
  , sep.property_value
  , level0type      = 'SCHEMA'
  , level0name      = sep.SysObject_schema_name
  , level1type      = Iif(stl.level2type = 'CONSTRAINT', 'TABLE', stl.level1type)
  , level1name      = Iif(stl.level2type = 'CONSTRAINT'
                        , sep.parent_name Collate Database_Default
                        , sep.SysObject_name Collate Database_Default)
  , level2type      = Iif(stl.level2type = 'CONSTRAINT', stl.level2type, sep.level2type Collate Database_Default)
  , level2name      = Iif(stl.level2type = 'CONSTRAINT', sep.SysObject_name, sep.minor_name)
  , sep.minor_id
  , sep.class
  , sep.class_desc
  , so.type
  , type_level1type = stl.level1type
  , type_level2type = stl.level2type
From
    repo_sys.ExtendedProperties            As sep
    Inner Join
        sys_dwh.objects                    As so
            On
            sep.major_id                     = so.object_id

    Inner Join
        configT.type_level1type_level2type As stl
            On
            so.type Collate Database_Default = stl.type

----
=======
// end::sql_modules_definition[]


