// tag::HeaderFullDisplayName[]
= repo_sys.parameters - V
// end::HeaderFullDisplayName[]

== existing_properties

// tag::existing_properties[]

:ExistsProperty--antorareferencedlist:
:ExistsProperty--antorareferencinglist:
:ExistsProperty--is_repo_managed:
:ExistsProperty--is_ssas:
:ExistsProperty--referencedobjectlist:
:ExistsProperty--sql_modules_definition:
:ExistsProperty--FK:
:ExistsProperty--Columns:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
9CDFBE88-CA97-EB11-84F4-A81E8446D5B0
// end::RepoObject_guid[]

== RepoObject_FullDisplayName2

// tag::RepoObject_FullDisplayName2[]
repo_sys.parameters
// end::RepoObject_FullDisplayName2[]

== SysObject_type

// tag::SysObject_type[]
V 
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
view
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
740913711
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2021-08-17 20:01:47
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]
[discrete]
== _


[#column-columnunderlineencryptionunderlinekeyunderlinedatabaseunderlinename]
=== column_encryption_key_database_name

[cols="d,8a,m,m,m"]
|===
|
|column_encryption_key_database_name
|sysname
|NULL
|
|===


[#column-columnunderlineencryptionunderlinekeyunderlineid]
=== column_encryption_key_id

[cols="d,8a,m,m,m"]
|===
|
|column_encryption_key_id
|int
|NULL
|
|===


[#column-defaultunderlinevalue]
=== default_value

[cols="d,8a,m,m,m"]
|===
|
|default_value
|sql_variant
|NULL
|
|===


[#column-encryptionunderlinealgorithmunderlinename]
=== encryption_algorithm_name

[cols="d,8a,m,m,m"]
|===
|
|encryption_algorithm_name
|sysname
|NULL
|
|===


[#column-encryptionunderlinetype]
=== encryption_type

[cols="d,8a,m,m,m"]
|===
|
|encryption_type
|int
|NULL
|
|===


[#column-encryptionunderlinetypeunderlinedesc]
=== encryption_type_desc

[cols="d,8a,m,m,m"]
|===
|
|encryption_type_desc
|nvarchar(64)
|NULL
|
|===


[#column-hasunderlinedefaultunderlinevalue]
=== has_default_value

[cols="d,8a,m,m,m"]
|===
|
|has_default_value
|bit
|NOT NULL
|
|===


[#column-isunderlinecursorunderlineref]
=== is_cursor_ref

[cols="d,8a,m,m,m"]
|===
|
|is_cursor_ref
|bit
|NOT NULL
|
|===


[#column-isunderlinenullable]
=== is_nullable

[cols="d,8a,m,m,m"]
|===
|
|is_nullable
|bit
|NULL
|
|===


[#column-isunderlineoutput]
=== is_output

[cols="d,8a,m,m,m"]
|===
|
|is_output
|bit
|NOT NULL
|
|===


[#column-isunderlinereadonly]
=== is_readonly

[cols="d,8a,m,m,m"]
|===
|
|is_readonly
|bit
|NOT NULL
|
|===


[#column-isunderlinexmlunderlinedocument]
=== is_xml_document

[cols="d,8a,m,m,m"]
|===
|
|is_xml_document
|bit
|NOT NULL
|
|===


[#column-maxunderlinelength]
=== max_length

[cols="d,8a,m,m,m"]
|===
|
|max_length
|smallint
|NOT NULL
|
|===


[#column-name]
=== name

[cols="d,8a,m,m,m"]
|===
|
|name
|sysname
|NULL
|
|===


[#column-objectunderlineid]
=== object_id

[cols="d,8a,m,m,m"]
|===
|
|object_id
|int
|NOT NULL
|
|===


[#column-parameterunderlineid]
=== parameter_id

[cols="d,8a,m,m,m"]
|===
|
|parameter_id
|int
|NOT NULL
|
|===


[#column-precision]
=== precision

[cols="d,8a,m,m,m"]
|===
|
|precision
|tinyint
|NOT NULL
|
|===


[#column-scale]
=== scale

[cols="d,8a,m,m,m"]
|===
|
|scale
|tinyint
|NOT NULL
|
|===


[#column-sysobjectunderlinefullname]
=== SysObject_fullname

[cols="d,8a,m,m,m"]
|===
|
|SysObject_fullname
|nvarchar(517)
|NULL
|
|===

.Referenced Columns
--
* xref:repo_sys.sysobject.adoc#column-sysobjectunderlinefullname[+repo_sys.SysObject.SysObject_fullname+]
--


[#column-sysobjectunderlinefullname2]
=== SysObject_fullname2

[cols="d,8a,m,m,m"]
|===
|
|SysObject_fullname2
|nvarchar(257)
|NULL
|
|===

.Referenced Columns
--
* xref:repo_sys.sysobject.adoc#column-sysobjectunderlinefullname2[+repo_sys.SysObject.SysObject_fullname2+]
--


[#column-sysobjectunderlinename]
=== SysObject_name

[cols="d,8a,m,m,m"]
|===
|
|SysObject_name
|sysname
|NULL
|
|===

.Referenced Columns
--
* xref:repo_sys.sysobject.adoc#column-sysobjectunderlinename[+repo_sys.SysObject.SysObject_name+]
--


[#column-sysobjectunderlinerepoobjectunderlineguid]
=== SysObject_RepoObject_guid

[cols="d,8a,m,m,m"]
|===
|
|SysObject_RepoObject_guid
|uniqueidentifier
|NULL
|
|===

.Referenced Columns
--
* xref:repo_sys.sysobject.adoc#column-sysobjectunderlinerepoobjectunderlineguid[+repo_sys.SysObject.SysObject_RepoObject_guid+]
--

.Referencing Columns
--
* xref:docs.repoobject_parameterlist.adoc#column-repoobjectunderlineguid[+docs.RepoObject_ParameterList.RepoObject_guid+]
--


[#column-sysobjectunderlineschemaunderlinename]
=== SysObject_schema_name

[cols="d,8a,m,m,m"]
|===
|
|SysObject_schema_name
|sysname
|NULL
|
|===

.Referenced Columns
--
* xref:repo_sys.sysobject.adoc#column-sysobjectunderlineschemaunderlinename[+repo_sys.SysObject.SysObject_schema_name+]
--


[#column-sysobjectunderlinetype]
=== SysObject_type

[cols="d,8a,m,m,m"]
|===
|
|SysObject_type
|char(2)
|NULL
|
|===

.Referenced Columns
--
* xref:repo_sys.sysobject.adoc#column-type[+repo_sys.SysObject.type+]
--


[#column-systemunderlinetypeunderlineid]
=== system_type_id

[cols="d,8a,m,m,m"]
|===
|
|system_type_id
|tinyint
|NOT NULL
|
|===


[#column-userunderlinetypeunderlinefullname]
=== user_type_fullname

[cols="d,8a,m,m,m"]
|===
|
|user_type_fullname
|nvarchar(182)
|NULL
|
|===


[#column-userunderlinetypeunderlineid]
=== user_type_id

[cols="d,8a,m,m,m"]
|===
|
|user_type_id
|int
|NOT NULL
|
|===


[#column-userunderlinetypeunderlinename]
=== user_type_name

[cols="d,8a,m,m,m"]
|===
|
|user_type_name
|sysname
|NULL
|
|===


[#column-xmlunderlinecollectionunderlineid]
=== xml_collection_id

[cols="d,8a,m,m,m"]
|===
|
|xml_collection_id
|int
|NOT NULL
|
|===


// end::AntoraColumnDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]





























// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]
|
|<<column-columnunderlineencryptionunderlinekeyunderlinedatabaseunderlinename>>
|sysname
|NULL
|

|
|<<column-columnunderlineencryptionunderlinekeyunderlineid>>
|int
|NULL
|

|
|<<column-defaultunderlinevalue>>
|sql_variant
|NULL
|

|
|<<column-encryptionunderlinealgorithmunderlinename>>
|sysname
|NULL
|

|
|<<column-encryptionunderlinetype>>
|int
|NULL
|

|
|<<column-encryptionunderlinetypeunderlinedesc>>
|nvarchar(64)
|NULL
|

|
|<<column-hasunderlinedefaultunderlinevalue>>
|bit
|NOT NULL
|

|
|<<column-isunderlinecursorunderlineref>>
|bit
|NOT NULL
|

|
|<<column-isunderlinenullable>>
|bit
|NULL
|

|
|<<column-isunderlineoutput>>
|bit
|NOT NULL
|

|
|<<column-isunderlinereadonly>>
|bit
|NOT NULL
|

|
|<<column-isunderlinexmlunderlinedocument>>
|bit
|NOT NULL
|

|
|<<column-maxunderlinelength>>
|smallint
|NOT NULL
|

|
|<<column-name>>
|sysname
|NULL
|

|
|<<column-objectunderlineid>>
|int
|NOT NULL
|

|
|<<column-parameterunderlineid>>
|int
|NOT NULL
|

|
|<<column-precision>>
|tinyint
|NOT NULL
|

|
|<<column-scale>>
|tinyint
|NOT NULL
|

|
|<<column-sysobjectunderlinefullname>>
|nvarchar(517)
|NULL
|

|
|<<column-sysobjectunderlinefullname2>>
|nvarchar(257)
|NULL
|

|
|<<column-sysobjectunderlinename>>
|sysname
|NULL
|

|
|<<column-sysobjectunderlinerepoobjectunderlineguid>>
|uniqueidentifier
|NULL
|

|
|<<column-sysobjectunderlineschemaunderlinename>>
|sysname
|NULL
|

|
|<<column-sysobjectunderlinetype>>
|char(2)
|NULL
|

|
|<<column-systemunderlinetypeunderlineid>>
|tinyint
|NOT NULL
|

|
|<<column-userunderlinetypeunderlinefullname>>
|nvarchar(182)
|NULL
|

|
|<<column-userunderlinetypeunderlineid>>
|int
|NOT NULL
|

|
|<<column-userunderlinetypeunderlinename>>
|sysname
|NULL
|

|
|<<column-xmlunderlinecollectionunderlineid>>
|int
|NOT NULL
|

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

// end::AntoraIndexList[]

== AntoraMeasureDetails

// tag::AntoraMeasureDetails[]

// end::AntoraMeasureDetails[]

== AntoraMeasureDescriptions



== AntoraParameterList

// tag::AntoraParameterList[]

// end::AntoraParameterList[]

== AntoraXrefCulturesList

// tag::AntoraXrefCulturesList[]
* xref:dhw:sqldb:repo_sys.parameters.adoc[] - 
// end::AntoraXrefCulturesList[]

== cultures_count

// tag::cultures_count[]
1
// end::cultures_count[]

== Other tags

source: property.RepoObjectProperty_cross As rop_cross


=== additional_reference_csv

// tag::additional_reference_csv[]

// end::additional_reference_csv[]


=== AdocUspSteps

// tag::adocuspsteps[]

// end::adocuspsteps[]


=== AntoraReferencedList

// tag::antorareferencedlist[]
* xref:dhw:sqldb:repo_sys.sysobject.adoc[]
* xref:dhw:sqldb:sys_dwh.parameters.adoc[]
* xref:dhw:sqldb:sys_dwh.types.adoc[]
// end::antorareferencedlist[]


=== AntoraReferencingList

// tag::antorareferencinglist[]
* xref:dhw:sqldb:docs.repoobject_parameterlist.adoc[]
// end::antorareferencinglist[]


=== Description

// tag::description[]

// end::description[]


=== exampleUsage

// tag::exampleusage[]

// end::exampleusage[]


=== exampleUsage_2

// tag::exampleusage_2[]

// end::exampleusage_2[]


=== exampleUsage_3

// tag::exampleusage_3[]

// end::exampleusage_3[]


=== exampleUsage_4

// tag::exampleusage_4[]

// end::exampleusage_4[]


=== exampleUsage_5

// tag::exampleusage_5[]

// end::exampleusage_5[]


=== exampleWrong_Usage

// tag::examplewrong_usage[]

// end::examplewrong_usage[]


=== has_execution_plan_issue

// tag::has_execution_plan_issue[]

// end::has_execution_plan_issue[]


=== has_get_referenced_issue

// tag::has_get_referenced_issue[]

// end::has_get_referenced_issue[]


=== has_history

// tag::has_history[]

// end::has_history[]


=== has_history_columns

// tag::has_history_columns[]

// end::has_history_columns[]


=== InheritanceType

// tag::inheritancetype[]

// end::inheritancetype[]


=== is_persistence

// tag::is_persistence[]

// end::is_persistence[]


=== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]

// end::is_persistence_check_duplicate_per_pk[]


=== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]

// end::is_persistence_check_for_empty_source[]


=== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]

// end::is_persistence_delete_changed[]


=== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]

// end::is_persistence_delete_missing[]


=== is_persistence_insert

// tag::is_persistence_insert[]

// end::is_persistence_insert[]


=== is_persistence_truncate

// tag::is_persistence_truncate[]

// end::is_persistence_truncate[]


=== is_persistence_update_changed

// tag::is_persistence_update_changed[]

// end::is_persistence_update_changed[]


=== is_repo_managed

// tag::is_repo_managed[]
0
// end::is_repo_managed[]


=== is_ssas

// tag::is_ssas[]
0
// end::is_ssas[]


=== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


=== MS_Description

// tag::ms_description[]

// end::ms_description[]


=== persistence_source_RepoObject_fullname

// tag::persistence_source_repoobject_fullname[]

// end::persistence_source_repoobject_fullname[]


=== persistence_source_RepoObject_fullname2

// tag::persistence_source_repoobject_fullname2[]

// end::persistence_source_repoobject_fullname2[]


=== persistence_source_RepoObject_guid

// tag::persistence_source_repoobject_guid[]

// end::persistence_source_repoobject_guid[]


=== persistence_source_RepoObject_xref

// tag::persistence_source_repoobject_xref[]

// end::persistence_source_repoobject_xref[]


=== pk_index_guid

// tag::pk_index_guid[]

// end::pk_index_guid[]


=== pk_IndexPatternColumnDatatype

// tag::pk_indexpatterncolumndatatype[]

// end::pk_indexpatterncolumndatatype[]


=== pk_IndexPatternColumnName

// tag::pk_indexpatterncolumnname[]

// end::pk_indexpatterncolumnname[]


=== pk_IndexSemanticGroup

// tag::pk_indexsemanticgroup[]

// end::pk_indexsemanticgroup[]


=== ReferencedObjectList

// tag::referencedobjectlist[]
* [repo_sys].[SysObject]
* [sys_dwh].[parameters]
* [sys_dwh].[types]
// end::referencedobjectlist[]


=== usp_persistence_RepoObject_guid

// tag::usp_persistence_repoobject_guid[]

// end::usp_persistence_repoobject_guid[]


=== UspExamples

// tag::uspexamples[]

// end::uspexamples[]


=== uspgenerator_usp_id

// tag::uspgenerator_usp_id[]

// end::uspgenerator_usp_id[]


=== UspParameters

// tag::uspparameters[]

// end::uspparameters[]

== Boolean Attributes

source: property.RepoObjectProperty WHERE property_int = 1

// tag::boolean_attributes[]


// end::boolean_attributes[]

== PlantUML diagrams

=== PlantUML Entity

// tag::puml_entity[]
[plantuml, entity-{docname}, svg, subs=macros]
....
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:repo_sys.parameters.adoc[]" as repo_sys.parameters << V >> {
  column_encryption_key_database_name : (sysname)
  column_encryption_key_id : (int)
  default_value : (sql_variant)
  encryption_algorithm_name : (sysname)
  encryption_type : (int)
  encryption_type_desc : (nvarchar(64))
  - has_default_value : (bit)
  - is_cursor_ref : (bit)
  is_nullable : (bit)
  - is_output : (bit)
  - is_readonly : (bit)
  - is_xml_document : (bit)
  - max_length : (smallint)
  name : (sysname)
  - object_id : (int)
  - parameter_id : (int)
  - precision : (tinyint)
  - scale : (tinyint)
  SysObject_fullname : (nvarchar(517))
  SysObject_fullname2 : (nvarchar(257))
  SysObject_name : (sysname)
  SysObject_RepoObject_guid : (uniqueidentifier)
  SysObject_schema_name : (sysname)
  SysObject_type : (char(2))
  - system_type_id : (tinyint)
  user_type_fullname : (nvarchar(182))
  - user_type_id : (int)
  user_type_name : (sysname)
  - xml_collection_id : (int)
  --
}
....

// end::puml_entity[]

=== PlantUML Entity 1 1 FK

// tag::puml_entity_1_1_fk[]
[plantuml, entity_1_1_fk-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:repo_sys.parameters.adoc[]" as repo_sys.parameters << V >> {

}



footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_fk[]

=== PlantUML 1 1 ObjectRef

// tag::puml_entity_1_1_objectref[]
[plantuml, entity_1_1_objectref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:docs.repoobject_parameterlist.adoc[]" as docs.RepoObject_ParameterList << V >> {
  **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo_sys.parameters.adoc[]" as repo_sys.parameters << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo_sys.sysobject.adoc[]" as repo_sys.SysObject << V >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.parameters.adoc[]" as sys_dwh.parameters << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.types.adoc[]" as sys_dwh.types << SN >> {
  --
}

repo_sys.parameters <.. docs.RepoObject_ParameterList
repo_sys.SysObject <.. repo_sys.parameters
sys_dwh.parameters <.. repo_sys.parameters
sys_dwh.types <.. repo_sys.parameters

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_objectref[]

=== PlantUML 30 0 ObjectRef

// tag::puml_entity_30_0_objectref[]
[plantuml, entity_30_0_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:config.ftv_dwh_database.adoc[]" as config.ftv_dwh_database << IF >> {
  --
}

entity "puml-link:dhw:sqldb:config.parameter.adoc[]" as config.Parameter << U >> {
  - **Parameter_name** : (varchar(100))
  - **sub_Parameter** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:configt.parameter_default.adoc[]" as configT.Parameter_default << V >> {
  - **Parameter_name** : (varchar(52))
  - **sub_Parameter** : (nvarchar(26))
  --
}

entity "puml-link:dhw:sqldb:repo_sys.extendedproperties.adoc[]" as repo_sys.ExtendedProperties << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo_sys.parameters.adoc[]" as repo_sys.parameters << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo_sys.sysobject.adoc[]" as repo_sys.SysObject << V >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.columns.adoc[]" as sys_dwh.columns << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.extended_properties.adoc[]" as sys_dwh.extended_properties << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.indexes.adoc[]" as sys_dwh.indexes << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.objects.adoc[]" as sys_dwh.objects << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.parameters.adoc[]" as sys_dwh.parameters << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.schemas.adoc[]" as sys_dwh.schemas << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.sql_modules.adoc[]" as sys_dwh.sql_modules << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.tables.adoc[]" as sys_dwh.tables << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.types.adoc[]" as sys_dwh.types << SN >> {
  --
}

config.ftv_dwh_database <.. repo_sys.ExtendedProperties
config.Parameter <.. config.ftv_dwh_database
configT.Parameter_default <.. config.Parameter
repo_sys.ExtendedProperties <.. repo_sys.SysObject
repo_sys.SysObject <.. repo_sys.parameters
sys_dwh.columns <.. repo_sys.ExtendedProperties
sys_dwh.extended_properties <.. repo_sys.ExtendedProperties
sys_dwh.indexes <.. repo_sys.ExtendedProperties
sys_dwh.objects <.. repo_sys.SysObject
sys_dwh.objects <.. repo_sys.ExtendedProperties
sys_dwh.parameters <.. repo_sys.parameters
sys_dwh.parameters <.. repo_sys.ExtendedProperties
sys_dwh.schemas <.. repo_sys.ExtendedProperties
sys_dwh.schemas <.. repo_sys.SysObject
sys_dwh.sql_modules <.. repo_sys.SysObject
sys_dwh.tables <.. repo_sys.SysObject
sys_dwh.types <.. repo_sys.parameters

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_30_0_objectref[]

=== PlantUML 0 30 ObjectRef

// tag::puml_entity_0_30_objectref[]
[plantuml, entity_0_30_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:docs.repoobject_adoc.adoc[]" as docs.RepoObject_Adoc << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_adoc_t.adoc[]" as docs.RepoObject_Adoc_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_parameterlist.adoc[]" as docs.RepoObject_ParameterList << V >> {
  **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport.adoc[]" as docs.usp_AntoraExport << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_objectpartialscontent.adoc[]" as docs.usp_AntoraExport_ObjectPartialsContent << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_repoobject_adoc_t.adoc[]" as docs.usp_PERSIST_RepoObject_Adoc_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo_sys.parameters.adoc[]" as repo_sys.parameters << V >> {
  --
}

docs.RepoObject_Adoc <.. docs.usp_PERSIST_RepoObject_Adoc_T
docs.RepoObject_Adoc <.. docs.RepoObject_Adoc_T
docs.REpoObject_Adoc_T <.. docs.usp_PERSIST_RepoObject_Adoc_T
docs.RepoObject_ParameterList <.. docs.RepoObject_Adoc
docs.usp_AntoraExport_ObjectPartialsContent <.. docs.usp_AntoraExport
docs.usp_PERSIST_RepoObject_Adoc_T <.. docs.usp_AntoraExport_ObjectPartialsContent
repo_sys.parameters <.. docs.RepoObject_ParameterList

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_0_30_objectref[]

=== PlantUML 1 1 ColumnRef

// tag::puml_entity_1_1_colref[]
[plantuml, entity_1_1_colref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:docs.repoobject_parameterlist.adoc[]" as docs.RepoObject_ParameterList << V >> {
  **RepoObject_guid** : (uniqueidentifier)
  AntoraParameterList : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:repo_sys.parameters.adoc[]" as repo_sys.parameters << V >> {
  column_encryption_key_database_name : (sysname)
  column_encryption_key_id : (int)
  default_value : (sql_variant)
  encryption_algorithm_name : (sysname)
  encryption_type : (int)
  encryption_type_desc : (nvarchar(64))
  - has_default_value : (bit)
  - is_cursor_ref : (bit)
  is_nullable : (bit)
  - is_output : (bit)
  - is_readonly : (bit)
  - is_xml_document : (bit)
  - max_length : (smallint)
  name : (sysname)
  - object_id : (int)
  - parameter_id : (int)
  - precision : (tinyint)
  - scale : (tinyint)
  SysObject_fullname : (nvarchar(517))
  SysObject_fullname2 : (nvarchar(257))
  SysObject_name : (sysname)
  SysObject_RepoObject_guid : (uniqueidentifier)
  SysObject_schema_name : (sysname)
  SysObject_type : (char(2))
  - system_type_id : (tinyint)
  user_type_fullname : (nvarchar(182))
  - user_type_id : (int)
  user_type_name : (sysname)
  - xml_collection_id : (int)
  --
}

entity "puml-link:dhw:sqldb:repo_sys.sysobject.adoc[]" as repo_sys.SysObject << V >> {
  - create_date : (datetime)
  history_table_id : (int)
  - is_ms_shipped : (bit)
  - is_published : (bit)
  - is_schema_published : (bit)
  max_column_id_used : (int)
  - modify_date : (datetime)
  - parent_object_id : (int)
  principal_id : (int)
  - schema_id : (int)
  sql_modules_definition : (nvarchar(max))
  - SysObject_fullname : (nvarchar(517))
  - SysObject_fullname2 : (nvarchar(257))
  - SysObject_id : (int)
  - SysObject_name : (sysname)
  SysObject_RepoObject_guid : (uniqueidentifier)
  SysObject_schema_name : (sysname)
  temporal_type : (tinyint)
  temporal_type_desc : (nvarchar(60))
  type : (char(2))
  type_desc : (nvarchar(60))
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.parameters.adoc[]" as sys_dwh.parameters << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.types.adoc[]" as sys_dwh.types << SN >> {
  --
}

repo_sys.parameters <.. docs.RepoObject_ParameterList
repo_sys.SysObject <.. repo_sys.parameters
sys_dwh.parameters <.. repo_sys.parameters
sys_dwh.types <.. repo_sys.parameters
"repo_sys.parameters::SysObject_RepoObject_guid" <-- "docs.RepoObject_ParameterList::RepoObject_guid"
"repo_sys.SysObject::SysObject_fullname" <-- "repo_sys.parameters::SysObject_fullname"
"repo_sys.SysObject::SysObject_fullname2" <-- "repo_sys.parameters::SysObject_fullname2"
"repo_sys.SysObject::SysObject_name" <-- "repo_sys.parameters::SysObject_name"
"repo_sys.SysObject::SysObject_RepoObject_guid" <-- "repo_sys.parameters::SysObject_RepoObject_guid"
"repo_sys.SysObject::SysObject_schema_name" <-- "repo_sys.parameters::SysObject_schema_name"
"repo_sys.SysObject::type" <-- "repo_sys.parameters::SysObject_type"

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_colref[]


== sql_modules_definition

// tag::sql_modules_definition[]
[%collapsible]
=======
[source,sql,numbered,indent=0]
----

CREATE View repo_sys.parameters
As
Select
    par.object_id
  , par.name
  , par.parameter_id
  , par.system_type_id
  , par.user_type_id
  , par.max_length
  , par.precision
  , par.scale
  , par.is_output
  , par.is_cursor_ref
  , par.has_default_value
  , par.is_xml_document
  , par.default_value
  , par.xml_collection_id
  , par.is_readonly
  , par.is_nullable
  , par.encryption_type
  , par.encryption_type_desc
  , par.encryption_algorithm_name
  , par.column_encryption_key_id
  , par.column_encryption_key_database_name
  -- code for [user_type_name]: https://stackoverflow.com/questions/9179990/where-do-i-find-sql-server-metadata-for-column-datatypes
  , user_type_name     = tp.name Collate Database_Default
  , user_type_fullname = Case
                             When tp.name In
                             ( 'varchar', 'char', 'varbinary', 'binary' )
                                 Then
                                 tp.name + '(' + Iif(par.max_length = -1, 'max', Cast(par.max_length As Varchar(25)))
                                 + ')'
                             When tp.name In
                             ( 'nvarchar', 'nchar' )
                                 Then
                                 tp.name + '('
                                 + Iif(par.max_length = -1, 'max', Cast(par.max_length / 2 As Varchar(25))) + ')'
                             When tp.name In
                             ( 'decimal', 'numeric' )
                                 Then
                                 tp.name + '(' + Cast(par.precision As Varchar(25)) + ', '
                                 + Cast(par.scale As Varchar(25)) + ')'
                             When tp.name In
                             ( 'datetime2' )
                                 Then
                                 tp.name + '(' + Cast(par.scale As Varchar(25)) + ')'
                             Else
                                 tp.name
                         End Collate Database_Default
  , so.SysObject_fullname
  , so.SysObject_fullname2
  , so.SysObject_name
  , so.SysObject_RepoObject_guid
  , so.SysObject_schema_name
  , SysObject_type     = so.type
From
    sys_dwh.parameters     As par
    Left Outer Join
        sys_dwh.types      As tp
            On
            tp.user_type_id = par.user_type_id

    Left Outer Join
        repo_sys.SysObject As so
            On
            so.SysObject_id = par.object_id

----
=======
// end::sql_modules_definition[]


