// tag::HeaderFullDisplayName[]
= repo.Measure - V
// end::HeaderFullDisplayName[]

== existing_properties

// tag::existing_properties[]

:ExistsProperty--antorareferencedlist:
:ExistsProperty--antorareferencinglist:
:ExistsProperty--is_repo_managed:
:ExistsProperty--is_ssas:
:ExistsProperty--referencedobjectlist:
:ExistsProperty--sql_modules_definition:
:ExistsProperty--FK:
:ExistsProperty--AntoraIndexList:
:ExistsProperty--Columns:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
DFF27B65-9D0F-EC11-8518-A81E8446D5B0
// end::RepoObject_guid[]

== RepoObject_FullDisplayName2

// tag::RepoObject_FullDisplayName2[]
repo.Measure
// end::RepoObject_FullDisplayName2[]

== SysObject_type

// tag::SysObject_type[]
V 
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
view
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
1707205182
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2021-11-28 10:57:13
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]
[discrete]
== _


[#column-description]
=== Description

[cols="d,8a,m,m,m"]
|===
|
|Description
|nvarchar(max)
|NULL
|
|===


[#column-expression]
=== Expression

[cols="d,8a,m,m,m"]
|===
|
|Expression
|nvarchar(max)
|NULL
|
|===


[#column-isunderlinessas]
=== is_ssas

[cols="d,8a,m,m,m"]
|===
|
|is_ssas
|bit
|NULL
|
|===


[#column-measureunderlinefullname]
=== Measure_fullname

[cols="d,8a,m,m,m"]
|===
|
|Measure_fullname
|nvarchar(517)
|NULL
|
|===

.Description
--
((quotename([databasename])+'.')+quotename([tables_measures_name]))
--
{empty} +

.Referenced Columns
--
* xref:ssas.model_json_312_tables_measures_t.adoc#column-measureunderlinefullname[+ssas.model_json_312_tables_measures_T.Measure_fullname+]
--


[#column-measureunderlinefullname2]
=== Measure_fullname2

[cols="d,8a,m,m,m"]
|===
|
|Measure_fullname2
|nvarchar(638)
|NOT NULL
|
|===

.Description
--
(([databasename]+'.measures.')+[tables_measures_name])
--
{empty} +

.Referenced Columns
--
* xref:ssas.model_json_312_tables_measures_t.adoc#column-measureunderlinefullname2[+ssas.model_json_312_tables_measures_T.Measure_fullname2+]
--


[#column-measureunderlineguid]
=== Measure_guid

[cols="d,8a,m,m,m"]
|===
|
|Measure_guid
|uniqueidentifier
|NOT NULL
|
|===

.Referenced Columns
--
* xref:ssas.model_json_312_tables_measures_t.adoc#column-measureunderlineguid[+ssas.model_json_312_tables_measures_T.Measure_guid+]
--

.Referencing Columns
--
* xref:docs.measure_measurepropertylist.adoc#column-measureunderlineguid[+docs.Measure_MeasurePropertyList.Measure_guid+]
--


[#column-measuresunderlinedescription]
=== measures_description

[cols="d,8a,m,m,m"]
|===
|
|measures_description
|nvarchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:ssas.model_json_312_tables_measures_t.adoc#column-tablesunderlinemeasuresunderlinedescription[+ssas.model_json_312_tables_measures_T.tables_measures_description+]
--


[#column-measuresunderlinedescriptionunderlineja]
=== measures_description_ja

[cols="d,8a,m,m,m"]
|===
|
|measures_description_ja
|nvarchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:ssas.model_json_312_tables_measures_t.adoc#column-tablesunderlinemeasuresunderlinedescriptionunderlineja[+ssas.model_json_312_tables_measures_T.tables_measures_description_ja+]
--


[#column-measuresunderlinedisplayfolder]
=== measures_displayFolder

[cols="d,8a,m,m,m"]
|===
|
|measures_displayFolder
|nvarchar(500)
|NULL
|
|===

.Referenced Columns
--
* xref:ssas.model_json_312_tables_measures_t.adoc#column-tablesunderlinemeasuresunderlinedisplayfolder[+ssas.model_json_312_tables_measures_T.tables_measures_displayFolder+]
--


[#column-measuresunderlineexpression]
=== measures_expression

[cols="d,8a,m,m,m"]
|===
|
|measures_expression
|nvarchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:ssas.model_json_312_tables_measures_t.adoc#column-tablesunderlinemeasuresunderlineexpression[+ssas.model_json_312_tables_measures_T.tables_measures_expression+]
--


[#column-measuresunderlineexpressionunderlineja]
=== measures_expression_ja

[cols="d,8a,m,m,m"]
|===
|
|measures_expression_ja
|nvarchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:ssas.model_json_312_tables_measures_t.adoc#column-tablesunderlinemeasuresunderlineexpressionunderlineja[+ssas.model_json_312_tables_measures_T.tables_measures_expression_ja+]
--


[#column-measuresunderlineformatstring]
=== measures_formatString

[cols="d,8a,m,m,m"]
|===
|
|measures_formatString
|nvarchar(500)
|NULL
|
|===

.Referenced Columns
--
* xref:ssas.model_json_312_tables_measures_t.adoc#column-tablesunderlinemeasuresunderlineformatstring[+ssas.model_json_312_tables_measures_T.tables_measures_formatString+]
--


[#column-measuresunderlineishidden]
=== measures_isHidden

[cols="d,8a,m,m,m"]
|===
|
|measures_isHidden
|bit
|NULL
|
|===

.Referenced Columns
--
* xref:ssas.model_json_312_tables_measures_t.adoc#column-tablesunderlinemeasuresunderlineishidden[+ssas.model_json_312_tables_measures_T.tables_measures_isHidden+]
--


[#column-measuresunderlinename]
=== measures_name

[cols="d,8a,m,m,m"]
|===
|
|measures_name
|nvarchar(500)
|NOT NULL
|
|===

.Referenced Columns
--
* xref:ssas.model_json_312_tables_measures_t.adoc#column-tablesunderlinemeasuresunderlinename[+ssas.model_json_312_tables_measures_T.tables_measures_name+]
--


[#column-measuresrepoobjektunderlineguid]
=== MeasuresRepoObjekt_guid

[cols="d,8a,m,m,m"]
|===
|
|MeasuresRepoObjekt_guid
|uniqueidentifier
|NULL
|
|===

.Referenced Columns
--
* xref:repo.reposchema.adoc#column-measuresrepoobjektunderlineguid[+repo.RepoSchema.MeasuresRepoObjekt_guid+]
--


[#column-measuresrepoobjektunderlinename]
=== MeasuresRepoObjekt_name

[cols="d,8a,m,m,m"]
|===
|
|MeasuresRepoObjekt_name
|varchar(9)
|NULL
|
|===

.Referenced Columns
--
* xref:repo.reposchema.adoc#column-measuresrepoobjektunderlinename[+repo.RepoSchema.MeasuresRepoObjekt_name+]
--


[#column-repoobjectunderlinefullname2]
=== RepoObject_fullname2

[cols="d,8a,m,m,m"]
|===
|
|RepoObject_fullname2
|nvarchar(257)
|NOT NULL
|
|===

.Description
--
(([databasename]+'.')+[tables_name])
--
{empty} +

.Referenced Columns
--
* xref:ssas.model_json_312_tables_measures_t.adoc#column-repoobjectunderlinefullname2[+ssas.model_json_312_tables_measures_T.RepoObject_fullname2+]
--


[#column-repoobjectunderlineguid]
=== RepoObject_guid

[cols="d,8a,m,m,m"]
|===
|
|RepoObject_guid
|uniqueidentifier
|NOT NULL
|
|===

.Referenced Columns
--
* xref:ssas.model_json_312_tables_measures_t.adoc#column-repoobjectunderlineguid[+ssas.model_json_312_tables_measures_T.RepoObject_guid+]
--


[#column-repoobjectunderlinename]
=== RepoObject_name

[cols="d,8a,m,m,m"]
|===
|
|RepoObject_name
|nvarchar(128)
|NOT NULL
|
|===

.Referenced Columns
--
* xref:ssas.model_json_312_tables_measures_t.adoc#column-tablesunderlinename[+ssas.model_json_312_tables_measures_T.tables_name+]
--


[#column-reposchemaunderlinename]
=== RepoSchema_name

[cols="d,8a,m,m,m"]
|===
|
|RepoSchema_name
|nvarchar(128)
|NOT NULL
|
|===

.Referenced Columns
--
* xref:ssas.model_json_312_tables_measures_t.adoc#column-databasename[+ssas.model_json_312_tables_measures_T.databasename+]
--


// end::AntoraColumnDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]




















// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]
|
|<<column-description>>
|nvarchar(max)
|NULL
|

|
|<<column-expression>>
|nvarchar(max)
|NULL
|

|
|<<column-isunderlinessas>>
|bit
|NULL
|

|
|<<column-measureunderlinefullname>>
|nvarchar(517)
|NULL
|

|
|<<column-measureunderlinefullname2>>
|nvarchar(638)
|NOT NULL
|

|
|<<column-measureunderlineguid>>
|uniqueidentifier
|NOT NULL
|

|
|<<column-measuresunderlinedescription>>
|nvarchar(max)
|NULL
|

|
|<<column-measuresunderlinedescriptionunderlineja>>
|nvarchar(max)
|NULL
|

|
|<<column-measuresunderlinedisplayfolder>>
|nvarchar(500)
|NULL
|

|
|<<column-measuresunderlineexpression>>
|nvarchar(max)
|NULL
|

|
|<<column-measuresunderlineexpressionunderlineja>>
|nvarchar(max)
|NULL
|

|
|<<column-measuresunderlineformatstring>>
|nvarchar(500)
|NULL
|

|
|<<column-measuresunderlineishidden>>
|bit
|NULL
|

|
|<<column-measuresunderlinename>>
|nvarchar(500)
|NOT NULL
|

|
|<<column-measuresrepoobjektunderlineguid>>
|uniqueidentifier
|NULL
|

|
|<<column-measuresrepoobjektunderlinename>>
|varchar(9)
|NULL
|

|
|<<column-repoobjectunderlinefullname2>>
|nvarchar(257)
|NOT NULL
|

|
|<<column-repoobjectunderlineguid>>
|uniqueidentifier
|NOT NULL
|

|
|<<column-repoobjectunderlinename>>
|nvarchar(128)
|NOT NULL
|

|
|<<column-reposchemaunderlinename>>
|nvarchar(128)
|NOT NULL
|

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

[#index-idxunderlinemeasureunderlineunderline1]
=== idx_Measure++__++1

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-Measure_guid>>; uniqueidentifier
--
* PK, Unique, Real: 0, 0, 0


[#index-idxunderlinemeasureunderlineunderline2]
=== idx_Measure++__++2

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#ssasunderlinetableunderlinemeasure[ssas_table_measure]
+
--
* <<column-RepoSchema_name>>; nvarchar(128)
* <<column-RepoObject_name>>; nvarchar(128)
* <<column-measures_name>>; nvarchar(500)
--
* PK, Unique, Real: 0, 0, 0


[#index-idxunderlinemeasureunderlineunderline3]
=== idx_Measure++__++3

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-RepoSchema_name>>; nvarchar(128)
* <<column-RepoObject_name>>; nvarchar(128)
--
* PK, Unique, Real: 0, 0, 0


[#index-idxunderlinemeasureunderlineunderline4]
=== idx_Measure++__++4

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-RepoSchema_name>>; nvarchar(128)
--
* PK, Unique, Real: 0, 0, 0

// end::AntoraIndexList[]

== AntoraMeasureDetails

// tag::AntoraMeasureDetails[]

// end::AntoraMeasureDetails[]

== AntoraMeasureDescriptions



== AntoraParameterList

// tag::AntoraParameterList[]

// end::AntoraParameterList[]

== AntoraXrefCulturesList

// tag::AntoraXrefCulturesList[]
* xref:dhw:sqldb:repo.measure.adoc[] - 
// end::AntoraXrefCulturesList[]

== cultures_count

// tag::cultures_count[]
1
// end::cultures_count[]

== Other tags

source: property.RepoObjectProperty_cross As rop_cross


=== additional_reference_csv

// tag::additional_reference_csv[]

// end::additional_reference_csv[]


=== AdocUspSteps

// tag::adocuspsteps[]

// end::adocuspsteps[]


=== AntoraReferencedList

// tag::antorareferencedlist[]
* xref:dhw:sqldb:repo.reposchema.adoc[]
* xref:dhw:sqldb:ssas.model_json_312_tables_measures_t.adoc[]
* xref:dhw:sqldb:ssas.model_json_31211_tables_columns_descriptions_stragg.adoc[]
* xref:dhw:sqldb:ssas.model_json_31221_tables_measures_expressions_stragg.adoc[]
// end::antorareferencedlist[]


=== AntoraReferencingList

// tag::antorareferencinglist[]
* xref:dhw:sqldb:docs.measure_measurepropertylist.adoc[]
* xref:dhw:sqldb:docs.unit_1_union.adoc[]
* xref:dhw:sqldb:property.usp_measureproperty_set.adoc[]
* xref:dhw:sqldb:repo.measure_union.adoc[]
// end::antorareferencinglist[]


=== Description

// tag::description[]

// end::description[]


=== exampleUsage

// tag::exampleusage[]

// end::exampleusage[]


=== exampleUsage_2

// tag::exampleusage_2[]

// end::exampleusage_2[]


=== exampleUsage_3

// tag::exampleusage_3[]

// end::exampleusage_3[]


=== exampleUsage_4

// tag::exampleusage_4[]

// end::exampleusage_4[]


=== exampleUsage_5

// tag::exampleusage_5[]

// end::exampleusage_5[]


=== exampleWrong_Usage

// tag::examplewrong_usage[]

// end::examplewrong_usage[]


=== has_execution_plan_issue

// tag::has_execution_plan_issue[]

// end::has_execution_plan_issue[]


=== has_get_referenced_issue

// tag::has_get_referenced_issue[]

// end::has_get_referenced_issue[]


=== has_history

// tag::has_history[]

// end::has_history[]


=== has_history_columns

// tag::has_history_columns[]

// end::has_history_columns[]


=== InheritanceType

// tag::inheritancetype[]

// end::inheritancetype[]


=== is_persistence

// tag::is_persistence[]

// end::is_persistence[]


=== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]

// end::is_persistence_check_duplicate_per_pk[]


=== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]

// end::is_persistence_check_for_empty_source[]


=== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]

// end::is_persistence_delete_changed[]


=== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]

// end::is_persistence_delete_missing[]


=== is_persistence_insert

// tag::is_persistence_insert[]

// end::is_persistence_insert[]


=== is_persistence_truncate

// tag::is_persistence_truncate[]

// end::is_persistence_truncate[]


=== is_persistence_update_changed

// tag::is_persistence_update_changed[]

// end::is_persistence_update_changed[]


=== is_repo_managed

// tag::is_repo_managed[]
0
// end::is_repo_managed[]


=== is_ssas

// tag::is_ssas[]
0
// end::is_ssas[]


=== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


=== MS_Description

// tag::ms_description[]

// end::ms_description[]


=== persistence_source_RepoObject_fullname

// tag::persistence_source_repoobject_fullname[]

// end::persistence_source_repoobject_fullname[]


=== persistence_source_RepoObject_fullname2

// tag::persistence_source_repoobject_fullname2[]

// end::persistence_source_repoobject_fullname2[]


=== persistence_source_RepoObject_guid

// tag::persistence_source_repoobject_guid[]

// end::persistence_source_repoobject_guid[]


=== persistence_source_RepoObject_xref

// tag::persistence_source_repoobject_xref[]

// end::persistence_source_repoobject_xref[]


=== pk_index_guid

// tag::pk_index_guid[]

// end::pk_index_guid[]


=== pk_IndexPatternColumnDatatype

// tag::pk_indexpatterncolumndatatype[]

// end::pk_indexpatterncolumndatatype[]


=== pk_IndexPatternColumnName

// tag::pk_indexpatterncolumnname[]

// end::pk_indexpatterncolumnname[]


=== pk_IndexSemanticGroup

// tag::pk_indexsemanticgroup[]

// end::pk_indexsemanticgroup[]


=== ReferencedObjectList

// tag::referencedobjectlist[]
* [repo].[RepoSchema]
* [ssas].[model_json_312_tables_measures_T]
* [ssas].[model_json_31211_tables_columns_descriptions_StrAgg]
* [ssas].[model_json_31221_tables_measures_expressions_StrAgg]
// end::referencedobjectlist[]


=== usp_persistence_RepoObject_guid

// tag::usp_persistence_repoobject_guid[]

// end::usp_persistence_repoobject_guid[]


=== UspExamples

// tag::uspexamples[]

// end::uspexamples[]


=== uspgenerator_usp_id

// tag::uspgenerator_usp_id[]

// end::uspgenerator_usp_id[]


=== UspParameters

// tag::uspparameters[]

// end::uspparameters[]

== Boolean Attributes

source: property.RepoObjectProperty WHERE property_int = 1

// tag::boolean_attributes[]


// end::boolean_attributes[]

== PlantUML diagrams

=== PlantUML Entity

// tag::puml_entity[]
[plantuml, entity-{docname}, svg, subs=macros]
....
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:repo.measure.adoc[]" as repo.Measure << V >> {
  Description : (nvarchar(max))
  Expression : (nvarchar(max))
  is_ssas : (bit)
  Measure_fullname : (nvarchar(517))
  - Measure_fullname2 : (nvarchar(638))
  - Measure_guid : (uniqueidentifier)
  measures_description : (nvarchar(max))
  measures_description_ja : (nvarchar(max))
  measures_displayFolder : (nvarchar(500))
  measures_expression : (nvarchar(max))
  measures_expression_ja : (nvarchar(max))
  measures_formatString : (nvarchar(500))
  measures_isHidden : (bit)
  - measures_name : (nvarchar(500))
  MeasuresRepoObjekt_guid : (uniqueidentifier)
  MeasuresRepoObjekt_name : (varchar(9))
  - RepoObject_fullname2 : (nvarchar(257))
  - RepoObject_guid : (uniqueidentifier)
  - RepoObject_name : (nvarchar(128))
  - RepoSchema_name : (nvarchar(128))
  --
}
....

// end::puml_entity[]

=== PlantUML Entity 1 1 FK

// tag::puml_entity_1_1_fk[]
[plantuml, entity_1_1_fk-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:repo.measure.adoc[]" as repo.Measure << V >> {
- idx_Measure__1

..
Measure_guid; uniqueidentifier
--
- idx_Measure__2
"ssas_table_measure"
..
RepoSchema_name; nvarchar(128)
RepoObject_name; nvarchar(128)
measures_name; nvarchar(500)
--
- idx_Measure__3

..
RepoSchema_name; nvarchar(128)
RepoObject_name; nvarchar(128)
--
- idx_Measure__4

..
RepoSchema_name; nvarchar(128)
}



footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_fk[]

=== PlantUML 1 1 ObjectRef

// tag::puml_entity_1_1_objectref[]
[plantuml, entity_1_1_objectref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:docs.measure_measurepropertylist.adoc[]" as docs.Measure_MeasurePropertyList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.unit_1_union.adoc[]" as docs.Unit_1_union << V >> {
  --
}

entity "puml-link:dhw:sqldb:property.usp_measureproperty_set.adoc[]" as property.usp_MeasureProperty_set << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.measure.adoc[]" as repo.Measure << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.measure_union.adoc[]" as repo.Measure_union << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.reposchema.adoc[]" as repo.RepoSchema << U >> {
  - **RepoSchema_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_312_tables_measures_t.adoc[]" as ssas.model_json_312_tables_measures_T << U >> {
  - **Measure_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31211_tables_columns_descriptions_stragg.adoc[]" as ssas.model_json_31211_tables_columns_descriptions_StrAgg << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31221_tables_measures_expressions_stragg.adoc[]" as ssas.model_json_31221_tables_measures_expressions_StrAgg << V >> {
  --
}

repo.Measure <.. docs.Unit_1_union
repo.Measure <.. repo.Measure_union
repo.Measure <.. docs.Measure_MeasurePropertyList
repo.Measure <.. property.usp_MeasureProperty_set
repo.RepoSchema <.. repo.Measure
ssas.model_json_312_tables_measures_T <.. repo.Measure
ssas.model_json_31211_tables_columns_descriptions_StrAgg <.. repo.Measure
ssas.model_json_31221_tables_measures_expressions_StrAgg <.. repo.Measure

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_objectref[]

=== PlantUML 30 0 ObjectRef

// tag::puml_entity_30_0_objectref[]
[plantuml, entity_30_0_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:repo.measure.adoc[]" as repo.Measure << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.reposchema.adoc[]" as repo.RepoSchema << U >> {
  - **RepoSchema_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.reposchema_ssas_src.adoc[]" as repo.RepoSchema_ssas_src << V >> {
  - **RepoSchema_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:repo.reposchema_ssas_tgt.adoc[]" as repo.RepoSchema_ssas_tgt << V >> {
  - **RepoSchema_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json.adoc[]" as ssas.model_json << U >> {
  - **databasename** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_10.adoc[]" as ssas.model_json_10 << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_20.adoc[]" as ssas.model_json_20 << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_201_descriptions_multiline.adoc[]" as ssas.model_json_201_descriptions_multiline << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_2011_descriptions_stragg.adoc[]" as ssas.model_json_2011_descriptions_StrAgg << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31_tables.adoc[]" as ssas.model_json_31_tables << V >> {
  - **databasename** : (nvarchar(128))
  **tables_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31_tables_t.adoc[]" as ssas.model_json_31_tables_T << U >> {
  - **databasename** : (nvarchar(128))
  **tables_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_312_tables_measures.adoc[]" as ssas.model_json_312_tables_measures << V >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  **tables_measures_name** : (nvarchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_312_tables_measures_t.adoc[]" as ssas.model_json_312_tables_measures_T << U >> {
  - **Measure_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_3121_tables_columns_descriptions_multiline.adoc[]" as ssas.model_json_3121_tables_columns_descriptions_multiline << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31211_tables_columns_descriptions_stragg.adoc[]" as ssas.model_json_31211_tables_columns_descriptions_StrAgg << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_3122_tables_measures_expressions_multiline.adoc[]" as ssas.model_json_3122_tables_measures_expressions_multiline << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31221_tables_measures_expressions_stragg.adoc[]" as ssas.model_json_31221_tables_measures_expressions_StrAgg << V >> {
  --
}

repo.RepoSchema <.. repo.Measure
repo.RepoSchema_ssas_src <.. repo.RepoSchema_ssas_tgt
repo.RepoSchema_ssas_tgt <.. repo.RepoSchema
ssas.model_json <.. ssas.model_json_10
ssas.model_json_10 <.. ssas.model_json_20
ssas.model_json_20 <.. repo.RepoSchema_ssas_src
ssas.model_json_20 <.. ssas.model_json_201_descriptions_multiline
ssas.model_json_20 <.. ssas.model_json_31_tables
ssas.model_json_201_descriptions_multiline <.. ssas.model_json_2011_descriptions_StrAgg
ssas.model_json_2011_descriptions_StrAgg <.. repo.RepoSchema_ssas_src
ssas.model_json_31_tables <.. ssas.model_json_31_tables_T
ssas.model_json_31_tables_T <.. ssas.model_json_312_tables_measures
ssas.model_json_312_tables_measures <.. ssas.model_json_312_tables_measures_T
ssas.model_json_312_tables_measures_T <.. ssas.model_json_3121_tables_columns_descriptions_multiline
ssas.model_json_312_tables_measures_T <.. repo.Measure
ssas.model_json_312_tables_measures_T <.. ssas.model_json_3122_tables_measures_expressions_multiline
ssas.model_json_3121_tables_columns_descriptions_multiline <.. ssas.model_json_31211_tables_columns_descriptions_StrAgg
ssas.model_json_31211_tables_columns_descriptions_StrAgg <.. repo.Measure
ssas.model_json_3122_tables_measures_expressions_multiline <.. ssas.model_json_31221_tables_measures_expressions_StrAgg
ssas.model_json_31221_tables_measures_expressions_StrAgg <.. repo.Measure

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_30_0_objectref[]

=== PlantUML 0 30 ObjectRef

// tag::puml_entity_0_30_objectref[]
[plantuml, entity_0_30_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:dmdocs.unit.adoc[]" as dmdocs.unit << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.antoranavlistpage_by_schema.adoc[]" as docs.AntoraNavListPage_by_schema << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ftv_repoobject_reference_plantuml_entityreflist.adoc[]" as docs.ftv_RepoObject_Reference_PlantUml_EntityRefList << IF >> {
  --
}

entity "puml-link:dhw:sqldb:docs.measure_measurepropertylist.adoc[]" as docs.Measure_MeasurePropertyList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.objectrefcyclic.adoc[]" as docs.ObjectRefCyclic << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.objectrefcyclic_entitylist.adoc[]" as docs.ObjectRefCyclic_EntityList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_adoc.adoc[]" as docs.RepoObject_Adoc << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_adoc_t.adoc[]" as docs.RepoObject_Adoc_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_measuredescriptionlist.adoc[]" as docs.RepoObject_MeasureDescriptionList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_measurelist.adoc[]" as docs.RepoObject_MeasureList << V >> {
  **RepoObject_guid** : (uniqueidentifier)
  **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml.adoc[]" as docs.RepoObject_Plantuml << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_entity.adoc[]" as docs.RepoObject_Plantuml_Entity << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_entity_t.adoc[]" as docs.RepoObject_Plantuml_Entity_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_pumlentityfklist.adoc[]" as docs.RepoObject_PlantUml_PumlEntityFkList << V >> {
  **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_t.adoc[]" as docs.RepoObject_Plantuml_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.schema_entitylist.adoc[]" as docs.Schema_EntityList << V >> {
  - **RepoObject_schema_name** : (nvarchar(128))
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.schema_puml.adoc[]" as docs.Schema_puml << V >> {
  - **RepoSchema_guid** : (uniqueidentifier)
  **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.unit_1_union.adoc[]" as docs.Unit_1_union << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.unit_2.adoc[]" as docs.Unit_2 << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.unit_3.adoc[]" as docs.Unit_3 << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport.adoc[]" as docs.usp_AntoraExport << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_objectpartialscontent.adoc[]" as docs.usp_AntoraExport_ObjectPartialsContent << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_objectpuml.adoc[]" as docs.usp_AntoraExport_ObjectPuml << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_repoobject_adoc_t.adoc[]" as docs.usp_PERSIST_RepoObject_Adoc_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_repoobject_plantuml_entity_t.adoc[]" as docs.usp_PERSIST_RepoObject_Plantuml_Entity_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_repoobject_plantuml_t.adoc[]" as docs.usp_PERSIST_RepoObject_Plantuml_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:property.usp_measureproperty_set.adoc[]" as property.usp_MeasureProperty_set << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.measure.adoc[]" as repo.Measure << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.measure_union.adoc[]" as repo.Measure_union << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_main.adoc[]" as repo.usp_main << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_sync_guid_ssas.adoc[]" as repo.usp_sync_guid_ssas << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.measure_translation.adoc[]" as ssas.Measure_translation << V >> {
  - **Measure_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  **RepoObject_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.measure_translation_displayfolder_union.adoc[]" as ssas.Measure_translation_displayfolder_union << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.measure_translation_t.adoc[]" as ssas.Measure_translation_T << U >> {
  - **Measure_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  **RepoObject_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.usp_persist_measure_translation_t.adoc[]" as ssas.usp_PERSIST_Measure_translation_T << P >> {
  --
}

docs.ftv_RepoObject_Reference_PlantUml_EntityRefList <.. docs.RepoObject_Plantuml
docs.Measure_MeasurePropertyList <.. docs.RepoObject_MeasureList
docs.ObjectRefCyclic_EntityList <.. docs.ObjectRefCyclic
docs.RepoObject_Adoc <.. docs.usp_PERSIST_RepoObject_Adoc_T
docs.RepoObject_Adoc <.. docs.RepoObject_Adoc_T
docs.REpoObject_Adoc_T <.. docs.usp_PERSIST_RepoObject_Adoc_T
docs.RepoObject_MeasureDescriptionList <.. docs.RepoObject_Adoc
docs.RepoObject_MeasureList <.. docs.RepoObject_Adoc
docs.RepoObject_MeasureList <.. docs.RepoObject_Plantuml_Entity
docs.RepoObject_Plantuml <.. docs.RepoObject_Plantuml_T
docs.RepoObject_Plantuml <.. docs.usp_PERSIST_RepoObject_Plantuml_T
docs.RepoObject_Plantuml_Entity <.. docs.usp_PERSIST_RepoObject_Plantuml_Entity_T
docs.RepoObject_Plantuml_Entity <.. docs.RepoObject_Plantuml_Entity_T
docs.RepoObject_Plantuml_Entity_T <.. docs.RepoObject_Adoc
docs.RepoObject_Plantuml_Entity_T <.. docs.ftv_RepoObject_Reference_PlantUml_EntityRefList
docs.RepoObject_Plantuml_Entity_T <.. docs.usp_PERSIST_RepoObject_Plantuml_Entity_T
docs.RepoObject_Plantuml_Entity_T <.. docs.Schema_EntityList
docs.RepoObject_Plantuml_Entity_T <.. docs.ObjectRefCyclic_EntityList
docs.RepoObject_Plantuml_Entity_T <.. docs.RepoObject_PlantUml_PumlEntityFkList
docs.RepoObject_PlantUml_PumlEntityFkList <.. docs.RepoObject_Plantuml
docs.RepoObject_Plantuml_T <.. docs.RepoObject_Adoc
docs.RepoObject_Plantuml_T <.. docs.usp_PERSIST_RepoObject_Plantuml_T
docs.Schema_EntityList <.. docs.Schema_puml
docs.Schema_puml <.. docs.AntoraNavListPage_by_schema
docs.Unit_1_union <.. docs.Unit_2
docs.Unit_2 <.. docs.Unit_3
docs.Unit_3 <.. dmdocs.unit
docs.usp_AntoraExport_ObjectPartialsContent <.. docs.usp_AntoraExport
docs.usp_AntoraExport_ObjectPuml <.. docs.usp_AntoraExport
docs.usp_PERSIST_RepoObject_Adoc_T <.. docs.usp_AntoraExport_ObjectPartialsContent
docs.usp_PERSIST_RepoObject_Plantuml_Entity_T <.. docs.usp_AntoraExport_ObjectPuml
docs.usp_PERSIST_RepoObject_Plantuml_T <.. docs.usp_AntoraExport_ObjectPuml
repo.Measure <.. docs.Measure_MeasurePropertyList
repo.Measure <.. property.usp_MeasureProperty_set
repo.Measure <.. docs.Unit_1_union
repo.Measure <.. repo.Measure_union
repo.Measure_union <.. docs.RepoObject_MeasureDescriptionList
repo.Measure_union <.. docs.RepoObject_MeasureList
repo.Measure_union <.. ssas.Measure_translation
repo.usp_sync_guid_ssas <.. repo.usp_main
ssas.Measure_translation <.. ssas.Measure_translation_T
ssas.Measure_translation <.. ssas.usp_PERSIST_Measure_translation_T
ssas.Measure_translation_displayfolder_union <.. docs.RepoObject_MeasureList
ssas.Measure_translation_T <.. ssas.usp_PERSIST_Measure_translation_T
ssas.Measure_translation_T <.. docs.RepoObject_MeasureDescriptionList
ssas.Measure_translation_T <.. ssas.Measure_translation_displayfolder_union
ssas.usp_PERSIST_Measure_translation_T <.. repo.usp_sync_guid_ssas

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_0_30_objectref[]

=== PlantUML 1 1 ColumnRef

// tag::puml_entity_1_1_colref[]
[plantuml, entity_1_1_colref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:docs.measure_measurepropertylist.adoc[]" as docs.Measure_MeasurePropertyList << V >> {
  - Measure_guid : (uniqueidentifier)
  MeasurePropertyList : (nvarchar(max))
  - MeasurePropertyTable : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:docs.unit_1_union.adoc[]" as docs.Unit_1_union << V >> {
  Object_fullname2 : (nvarchar(257))
  Object_Type : (varchar(2))
  Unit_ColummName : (nvarchar(128))
  Unit_Description : (nvarchar(max))
  Unit_DisplayFolder : (nvarchar(500))
  Unit_Expression : (nvarchar(max))
  Unit_FormatString : (nvarchar(500))
  - Unit_fullname2 : (nvarchar(638))
  - Unit_guid : (uniqueidentifier)
  Unit_isHidden : (bit)
  Unit_IsKey : (bit)
  Unit_IsSsas : (bit)
  Unit_IsUnique : (bit)
  - Unit_Metatype : (varchar(7))
  - Unit_Name : (nvarchar(500))
  Unit_ObjectName : (nvarchar(128))
  - Unit_Schema : (nvarchar(128))
  Unit_SummarizeBy : (nvarchar(500))
  Unit_TypeName : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.usp_measureproperty_set.adoc[]" as property.usp_MeasureProperty_set << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.measure.adoc[]" as repo.Measure << V >> {
  Description : (nvarchar(max))
  Expression : (nvarchar(max))
  is_ssas : (bit)
  Measure_fullname : (nvarchar(517))
  - Measure_fullname2 : (nvarchar(638))
  - Measure_guid : (uniqueidentifier)
  measures_description : (nvarchar(max))
  measures_description_ja : (nvarchar(max))
  measures_displayFolder : (nvarchar(500))
  measures_expression : (nvarchar(max))
  measures_expression_ja : (nvarchar(max))
  measures_formatString : (nvarchar(500))
  measures_isHidden : (bit)
  - measures_name : (nvarchar(500))
  MeasuresRepoObjekt_guid : (uniqueidentifier)
  MeasuresRepoObjekt_name : (varchar(9))
  - RepoObject_fullname2 : (nvarchar(257))
  - RepoObject_guid : (uniqueidentifier)
  - RepoObject_name : (nvarchar(128))
  - RepoSchema_name : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:repo.measure_union.adoc[]" as repo.Measure_union << V >> {
  Description : (nvarchar(max))
  Expression : (nvarchar(max))
  is_ssas : (bit)
  Measure_fullname : (nvarchar(517))
  - Measure_fullname2 : (nvarchar(638))
  - Measure_guid : (uniqueidentifier)
  measures_description : (nvarchar(max))
  measures_description_ja : (nvarchar(max))
  measures_displayFolder : (nvarchar(500))
  measures_expression : (nvarchar(max))
  measures_expression_ja : (nvarchar(max))
  measures_formatString : (nvarchar(500))
  measures_isHidden : (bit)
  - measures_name : (nvarchar(500))
  - RepoObject_fullname2 : (nvarchar(257))
  RepoObject_guid : (uniqueidentifier)
  RepoObject_name : (nvarchar(128))
  - RepoSchema_name : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:repo.reposchema.adoc[]" as repo.RepoSchema << U >> {
  - **RepoSchema_guid** : (uniqueidentifier)
  - is_ssas : (bit)
  is_SysSchema_missing : (bit)
  - MeasuresRepoObjekt_guid : (uniqueidentifier)
  RepoSchema_description : (nvarchar(4000))
  - RepoSchema_name : (nvarchar(128))
  SysSchema_id : (int)
  - SysSchema_name : (nvarchar(128))
  ~ has_different_sys_names : (bit)
  # is_RepoSchema_name_uniqueidentifier : (int)
  # is_SysSchema_name_uniqueidentifier : (int)
  # MeasuresRepoObjekt_name : (varchar(9))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_312_tables_measures_t.adoc[]" as ssas.model_json_312_tables_measures_T << U >> {
  - **Measure_guid** : (uniqueidentifier)
  - databasename : (nvarchar(128))
  - RepoObject_guid : (uniqueidentifier)
  tables_measures_description : (nvarchar(max))
  tables_measures_description_ja : (nvarchar(max))
  tables_measures_displayFolder : (nvarchar(500))
  tables_measures_expression : (nvarchar(max))
  tables_measures_expression_ja : (nvarchar(max))
  tables_measures_formatString : (nvarchar(500))
  tables_measures_isHidden : (bit)
  tables_measures_name : (nvarchar(500))
  - tables_name : (nvarchar(128))
  # Measure_fullname : (nvarchar(517))
  # Measure_fullname2 : (nvarchar(638))
  # RepoObject_fullname2 : (nvarchar(257))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31211_tables_columns_descriptions_stragg.adoc[]" as ssas.model_json_31211_tables_columns_descriptions_StrAgg << V >> {
  - databasename : (nvarchar(128))
  descriptions_StrAgg : (nvarchar(max))
  - Measure_guid : (uniqueidentifier)
  - RepoObject_guid : (uniqueidentifier)
  - tables_measures_name : (nvarchar(500))
  - tables_name : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31221_tables_measures_expressions_stragg.adoc[]" as ssas.model_json_31221_tables_measures_expressions_StrAgg << V >> {
  - databasename : (nvarchar(128))
  expressions_StrAgg : (nvarchar(max))
  - Measure_guid : (uniqueidentifier)
  - RepoObject_guid : (uniqueidentifier)
  - tables_measures_name : (nvarchar(500))
  - tables_name : (nvarchar(128))
  --
}

repo.Measure <.. docs.Unit_1_union
repo.Measure <.. repo.Measure_union
repo.Measure <.. docs.Measure_MeasurePropertyList
repo.Measure <.. property.usp_MeasureProperty_set
repo.RepoSchema <.. repo.Measure
ssas.model_json_312_tables_measures_T <.. repo.Measure
ssas.model_json_31211_tables_columns_descriptions_StrAgg <.. repo.Measure
ssas.model_json_31221_tables_measures_expressions_StrAgg <.. repo.Measure
"repo.Measure::Measure_guid" <-- "docs.Measure_MeasurePropertyList::Measure_guid"
"repo.RepoSchema::MeasuresRepoObjekt_guid" <-- "repo.Measure::MeasuresRepoObjekt_guid"
"repo.RepoSchema::MeasuresRepoObjekt_name" <-- "repo.Measure::MeasuresRepoObjekt_name"
"ssas.model_json_312_tables_measures_T::databasename" <-- "repo.Measure::RepoSchema_name"
"ssas.model_json_312_tables_measures_T::Measure_fullname" <-- "repo.Measure::Measure_fullname"
"ssas.model_json_312_tables_measures_T::Measure_fullname2" <-- "repo.Measure::Measure_fullname2"
"ssas.model_json_312_tables_measures_T::Measure_guid" <-- "repo.Measure::Measure_guid"
"ssas.model_json_312_tables_measures_T::RepoObject_fullname2" <-- "repo.Measure::RepoObject_fullname2"
"ssas.model_json_312_tables_measures_T::RepoObject_guid" <-- "repo.Measure::RepoObject_guid"
"ssas.model_json_312_tables_measures_T::tables_measures_description" <-- "repo.Measure::measures_description"
"ssas.model_json_312_tables_measures_T::tables_measures_description_ja" <-- "repo.Measure::measures_description_ja"
"ssas.model_json_312_tables_measures_T::tables_measures_displayFolder" <-- "repo.Measure::measures_displayFolder"
"ssas.model_json_312_tables_measures_T::tables_measures_expression" <-- "repo.Measure::measures_expression"
"ssas.model_json_312_tables_measures_T::tables_measures_expression_ja" <-- "repo.Measure::measures_expression_ja"
"ssas.model_json_312_tables_measures_T::tables_measures_formatString" <-- "repo.Measure::measures_formatString"
"ssas.model_json_312_tables_measures_T::tables_measures_isHidden" <-- "repo.Measure::measures_isHidden"
"ssas.model_json_312_tables_measures_T::tables_measures_name" <-- "repo.Measure::measures_name"
"ssas.model_json_312_tables_measures_T::tables_name" <-- "repo.Measure::RepoObject_name"

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_colref[]


== sql_modules_definition

// tag::sql_modules_definition[]
[%collapsible]
=======
[source,sql,numbered,indent=0]
----

CREATE View repo.Measure
As
Select
    T1.Measure_guid
  , RepoSchema_name         = T1.databasename
  , Description             = Coalesce ( T1.tables_measures_description, T2.descriptions_StrAgg )
  , Expression              = Coalesce ( T1.tables_measures_expression, T3.expressions_StrAgg )
  , is_ssas                 = Cast(1 As Bit)
  , measures_name           = T1.tables_measures_name
  , measures_description    = T1.tables_measures_description
  , measures_description_ja = T1.tables_measures_description_ja
  , measures_displayFolder  = T1.tables_measures_displayFolder
  , measures_expression     = T1.tables_measures_expression
  , measures_expression_ja  = T1.tables_measures_expression_ja
  , measures_formatString   = T1.tables_measures_formatString
  , measures_isHidden       = T1.tables_measures_isHidden
  , T1.Measure_fullname2
  , T1.Measure_fullname
  , T1.RepoObject_fullname2
  , T1.RepoObject_guid
  , RepoObject_name         = T1.tables_name
  --one RepoObjekt_guid per schema, because we create one virtual table '_measures' per schema
  --schema = ssas model
  , T4.MeasuresRepoObjekt_guid
  , T4.MeasuresRepoObjekt_name
From
    ssas.model_json_312_tables_measures_T                        As T1
    Left Outer Join
        ssas.model_json_31211_tables_columns_descriptions_StrAgg As T2
            On
            T2.Measure_guid    = T1.Measure_guid

    Left Outer Join
        ssas.model_json_31221_tables_measures_expressions_StrAgg As T3
            On
            T3.Measure_guid    = T1.Measure_guid

    Left Outer Join
        repo.RepoSchema                                          As T4
            On
            T4.RepoSchema_name = T1.databasename

----
=======
// end::sql_modules_definition[]


