// tag::HeaderFullDisplayName[]
= repo_sys.SysSchema - V
// end::HeaderFullDisplayName[]

== existing_properties

// tag::existing_properties[]

:ExistsProperty--antorareferencedlist:
:ExistsProperty--antorareferencinglist:
:ExistsProperty--is_repo_managed:
:ExistsProperty--is_ssas:
:ExistsProperty--referencedobjectlist:
:ExistsProperty--sql_modules_definition:
:ExistsProperty--FK:
:ExistsProperty--Columns:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
AF0747EC-8CA3-EB11-84FA-A81E8446D5B0
// end::RepoObject_guid[]

== RepoObject_FullDisplayName2

// tag::RepoObject_FullDisplayName2[]
repo_sys.SysSchema
// end::RepoObject_FullDisplayName2[]

== SysObject_type

// tag::SysObject_type[]
V 
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
view
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
628913312
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2021-08-17 20:04:28
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]
[discrete]
== _


[#column-sysschemaunderlineid]
=== SysSchema_id

[cols="d,8a,m,m,m"]
|===
|
|SysSchema_id
|int
|NOT NULL
|
|===

.Referencing Columns
--
* xref:repo.sysschema_reposchema_via_guid.adoc#column-sysschemaunderlineid[+repo.SysSchema_RepoSchema_via_guid.SysSchema_id+]
* xref:repo.sysschema_reposchema_via_name.adoc#column-sysschemaunderlineid[+repo.SysSchema_RepoSchema_via_name.SysSchema_id+]
--


[#column-sysschemaunderlinename]
=== SysSchema_name

[cols="d,8a,m,m,m"]
|===
|
|SysSchema_name
|sysname
|NOT NULL
|
|===

.Referencing Columns
--
* xref:repo.sysschema_reposchema_via_guid.adoc#column-sysschemaunderlinename[+repo.SysSchema_RepoSchema_via_guid.SysSchema_name+]
* xref:repo.sysschema_reposchema_via_name.adoc#column-sysschemaunderlinename[+repo.SysSchema_RepoSchema_via_name.SysSchema_name+]
--


[#column-sysschemaunderlineprincipalunderlineid]
=== SysSchema_principal_id

[cols="d,8a,m,m,m"]
|===
|
|SysSchema_principal_id
|int
|NULL
|
|===


[#column-sysschemaunderlinereposchemaunderlineguid]
=== SysSchema_RepoSchema_guid

[cols="d,8a,m,m,m"]
|===
|
|SysSchema_RepoSchema_guid
|uniqueidentifier
|NULL
|
|===

.Referencing Columns
--
* xref:repo.sysschema_reposchema_via_guid.adoc#column-sysschemaunderlinereposchemaunderlineguid[+repo.SysSchema_RepoSchema_via_guid.SysSchema_RepoSchema_guid+]
* xref:repo.sysschema_reposchema_via_name.adoc#column-sysschemaunderlinereposchemaunderlineguid[+repo.SysSchema_RepoSchema_via_name.SysSchema_RepoSchema_guid+]
--


// end::AntoraColumnDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]




// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]
|
|<<column-sysschemaunderlineid>>
|int
|NOT NULL
|

|
|<<column-sysschemaunderlinename>>
|sysname
|NOT NULL
|

|
|<<column-sysschemaunderlineprincipalunderlineid>>
|int
|NULL
|

|
|<<column-sysschemaunderlinereposchemaunderlineguid>>
|uniqueidentifier
|NULL
|

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

// end::AntoraIndexList[]

== AntoraMeasureDetails

// tag::AntoraMeasureDetails[]

// end::AntoraMeasureDetails[]

== AntoraMeasureDescriptions



== AntoraParameterList

// tag::AntoraParameterList[]

// end::AntoraParameterList[]

== AntoraXrefCulturesList

// tag::AntoraXrefCulturesList[]
* xref:dhw:sqldb:repo_sys.sysschema.adoc[] - 
// end::AntoraXrefCulturesList[]

== cultures_count

// tag::cultures_count[]
1
// end::cultures_count[]

== Other tags

source: property.RepoObjectProperty_cross As rop_cross


=== additional_reference_csv

// tag::additional_reference_csv[]

// end::additional_reference_csv[]


=== AdocUspSteps

// tag::adocuspsteps[]

// end::adocuspsteps[]


=== AntoraReferencedList

// tag::antorareferencedlist[]
* xref:dhw:sqldb:repo_sys.extendedproperties.adoc[]
* xref:dhw:sqldb:sys_dwh.schemas.adoc[]
// end::antorareferencedlist[]


=== AntoraReferencingList

// tag::antorareferencinglist[]
* xref:dhw:sqldb:repo.sysschema_reposchema_via_guid.adoc[]
* xref:dhw:sqldb:repo.sysschema_reposchema_via_name.adoc[]
* xref:dhw:sqldb:repo.usp_sync_guid_reposchema.adoc[]
// end::antorareferencinglist[]


=== Description

// tag::description[]

// end::description[]


=== exampleUsage

// tag::exampleusage[]

// end::exampleusage[]


=== exampleUsage_2

// tag::exampleusage_2[]

// end::exampleusage_2[]


=== exampleUsage_3

// tag::exampleusage_3[]

// end::exampleusage_3[]


=== exampleUsage_4

// tag::exampleusage_4[]

// end::exampleusage_4[]


=== exampleUsage_5

// tag::exampleusage_5[]

// end::exampleusage_5[]


=== exampleWrong_Usage

// tag::examplewrong_usage[]

// end::examplewrong_usage[]


=== has_execution_plan_issue

// tag::has_execution_plan_issue[]

// end::has_execution_plan_issue[]


=== has_get_referenced_issue

// tag::has_get_referenced_issue[]

// end::has_get_referenced_issue[]


=== has_history

// tag::has_history[]

// end::has_history[]


=== has_history_columns

// tag::has_history_columns[]

// end::has_history_columns[]


=== InheritanceType

// tag::inheritancetype[]

// end::inheritancetype[]


=== is_persistence

// tag::is_persistence[]

// end::is_persistence[]


=== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]

// end::is_persistence_check_duplicate_per_pk[]


=== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]

// end::is_persistence_check_for_empty_source[]


=== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]

// end::is_persistence_delete_changed[]


=== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]

// end::is_persistence_delete_missing[]


=== is_persistence_insert

// tag::is_persistence_insert[]

// end::is_persistence_insert[]


=== is_persistence_truncate

// tag::is_persistence_truncate[]

// end::is_persistence_truncate[]


=== is_persistence_update_changed

// tag::is_persistence_update_changed[]

// end::is_persistence_update_changed[]


=== is_repo_managed

// tag::is_repo_managed[]
0
// end::is_repo_managed[]


=== is_ssas

// tag::is_ssas[]
0
// end::is_ssas[]


=== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


=== MS_Description

// tag::ms_description[]

// end::ms_description[]


=== persistence_source_RepoObject_fullname

// tag::persistence_source_repoobject_fullname[]

// end::persistence_source_repoobject_fullname[]


=== persistence_source_RepoObject_fullname2

// tag::persistence_source_repoobject_fullname2[]

// end::persistence_source_repoobject_fullname2[]


=== persistence_source_RepoObject_guid

// tag::persistence_source_repoobject_guid[]

// end::persistence_source_repoobject_guid[]


=== persistence_source_RepoObject_xref

// tag::persistence_source_repoobject_xref[]

// end::persistence_source_repoobject_xref[]


=== pk_index_guid

// tag::pk_index_guid[]

// end::pk_index_guid[]


=== pk_IndexPatternColumnDatatype

// tag::pk_indexpatterncolumndatatype[]

// end::pk_indexpatterncolumndatatype[]


=== pk_IndexPatternColumnName

// tag::pk_indexpatterncolumnname[]

// end::pk_indexpatterncolumnname[]


=== pk_IndexSemanticGroup

// tag::pk_indexsemanticgroup[]

// end::pk_indexsemanticgroup[]


=== ReferencedObjectList

// tag::referencedobjectlist[]
* [repo_sys].[ExtendedProperties]
* [sys_dwh].[schemas]
// end::referencedobjectlist[]


=== usp_persistence_RepoObject_guid

// tag::usp_persistence_repoobject_guid[]

// end::usp_persistence_repoobject_guid[]


=== UspExamples

// tag::uspexamples[]

// end::uspexamples[]


=== uspgenerator_usp_id

// tag::uspgenerator_usp_id[]

// end::uspgenerator_usp_id[]


=== UspParameters

// tag::uspparameters[]

// end::uspparameters[]

== Boolean Attributes

source: property.RepoObjectProperty WHERE property_int = 1

// tag::boolean_attributes[]


// end::boolean_attributes[]

== PlantUML diagrams

=== PlantUML Entity

// tag::puml_entity[]
[plantuml, entity-{docname}, svg, subs=macros]
....
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:repo_sys.sysschema.adoc[]" as repo_sys.SysSchema << V >> {
  - SysSchema_id : (int)
  - SysSchema_name : (sysname)
  SysSchema_principal_id : (int)
  SysSchema_RepoSchema_guid : (uniqueidentifier)
  --
}
....

// end::puml_entity[]

=== PlantUML Entity 1 1 FK

// tag::puml_entity_1_1_fk[]
[plantuml, entity_1_1_fk-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:repo_sys.sysschema.adoc[]" as repo_sys.SysSchema << V >> {

}



footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_fk[]

=== PlantUML 1 1 ObjectRef

// tag::puml_entity_1_1_objectref[]
[plantuml, entity_1_1_objectref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:repo.sysschema_reposchema_via_guid.adoc[]" as repo.SysSchema_RepoSchema_via_guid << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.sysschema_reposchema_via_name.adoc[]" as repo.SysSchema_RepoSchema_via_name << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_sync_guid_reposchema.adoc[]" as repo.usp_sync_guid_RepoSchema << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo_sys.extendedproperties.adoc[]" as repo_sys.ExtendedProperties << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo_sys.sysschema.adoc[]" as repo_sys.SysSchema << V >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.schemas.adoc[]" as sys_dwh.schemas << SN >> {
  --
}

repo_sys.ExtendedProperties <.. repo_sys.SysSchema
repo_sys.SysSchema <.. repo.SysSchema_RepoSchema_via_guid
repo_sys.SysSchema <.. repo.SysSchema_RepoSchema_via_name
repo_sys.SysSchema <.. repo.usp_sync_guid_RepoSchema
sys_dwh.schemas <.. repo_sys.SysSchema

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_objectref[]

=== PlantUML 30 0 ObjectRef

// tag::puml_entity_30_0_objectref[]
[plantuml, entity_30_0_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:config.ftv_dwh_database.adoc[]" as config.ftv_dwh_database << IF >> {
  --
}

entity "puml-link:dhw:sqldb:config.parameter.adoc[]" as config.Parameter << U >> {
  - **Parameter_name** : (varchar(100))
  - **sub_Parameter** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:configt.parameter_default.adoc[]" as configT.Parameter_default << V >> {
  - **Parameter_name** : (varchar(52))
  - **sub_Parameter** : (nvarchar(26))
  --
}

entity "puml-link:dhw:sqldb:repo_sys.extendedproperties.adoc[]" as repo_sys.ExtendedProperties << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo_sys.sysschema.adoc[]" as repo_sys.SysSchema << V >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.columns.adoc[]" as sys_dwh.columns << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.extended_properties.adoc[]" as sys_dwh.extended_properties << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.indexes.adoc[]" as sys_dwh.indexes << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.objects.adoc[]" as sys_dwh.objects << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.parameters.adoc[]" as sys_dwh.parameters << SN >> {
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.schemas.adoc[]" as sys_dwh.schemas << SN >> {
  --
}

config.ftv_dwh_database <.. repo_sys.ExtendedProperties
config.Parameter <.. config.ftv_dwh_database
configT.Parameter_default <.. config.Parameter
repo_sys.ExtendedProperties <.. repo_sys.SysSchema
sys_dwh.columns <.. repo_sys.ExtendedProperties
sys_dwh.extended_properties <.. repo_sys.ExtendedProperties
sys_dwh.indexes <.. repo_sys.ExtendedProperties
sys_dwh.objects <.. repo_sys.ExtendedProperties
sys_dwh.parameters <.. repo_sys.ExtendedProperties
sys_dwh.schemas <.. repo_sys.SysSchema
sys_dwh.schemas <.. repo_sys.ExtendedProperties

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_30_0_objectref[]

=== PlantUML 0 30 ObjectRef

// tag::puml_entity_0_30_objectref[]
[plantuml, entity_0_30_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:repo.sysschema_reposchema_via_guid.adoc[]" as repo.SysSchema_RepoSchema_via_guid << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.sysschema_reposchema_via_name.adoc[]" as repo.SysSchema_RepoSchema_via_name << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_main.adoc[]" as repo.usp_main << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_persistence_set.adoc[]" as repo.usp_persistence_set << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_sync_guid.adoc[]" as repo.usp_sync_guid << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_sync_guid_reposchema.adoc[]" as repo.usp_sync_guid_RepoSchema << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo_sys.sysschema.adoc[]" as repo_sys.SysSchema << V >> {
  --
}

repo.SysSchema_RepoSchema_via_guid <.. repo.usp_sync_guid_RepoSchema
repo.SysSchema_RepoSchema_via_name <.. repo.usp_sync_guid_RepoSchema
repo.usp_sync_guid <.. repo.usp_persistence_set
repo.usp_sync_guid <.. repo.usp_main
repo.usp_sync_guid_RepoSchema <.. repo.usp_sync_guid
repo_sys.SysSchema <.. repo.SysSchema_RepoSchema_via_guid
repo_sys.SysSchema <.. repo.SysSchema_RepoSchema_via_name
repo_sys.SysSchema <.. repo.usp_sync_guid_RepoSchema

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_0_30_objectref[]

=== PlantUML 1 1 ColumnRef

// tag::puml_entity_1_1_colref[]
[plantuml, entity_1_1_colref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:repo.sysschema_reposchema_via_guid.adoc[]" as repo.SysSchema_RepoSchema_via_guid << V >> {
  is_RepoSchema_name_uniqueidentifier : (int)
  is_SysSchema_name_uniqueidentifier : (int)
  RepoSchema_guid : (uniqueidentifier)
  RepoSchema_is_SysSchema_missing : (bit)
  RepoSchema_name : (nvarchar(128))
  RepoSchema_SysSchema_id : (int)
  RepoSchema_SysSchema_name : (nvarchar(128))
  - SysSchema_id : (int)
  - SysSchema_name : (sysname)
  SysSchema_RepoSchema_guid : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.sysschema_reposchema_via_name.adoc[]" as repo.SysSchema_RepoSchema_via_name << V >> {
  is_RepoSchema_name_uniqueidentifier : (int)
  is_SysSchema_name_uniqueidentifier : (int)
  RepoSchema_guid : (uniqueidentifier)
  RepoSchema_is_SysSchema_missing : (bit)
  RepoSchema_name : (nvarchar(128))
  RepoSchema_SysSchema_id : (int)
  RepoSchema_SysSchema_name : (nvarchar(128))
  - SysSchema_id : (int)
  - SysSchema_name : (sysname)
  SysSchema_RepoSchema_guid : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.usp_sync_guid_reposchema.adoc[]" as repo.usp_sync_guid_RepoSchema << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo_sys.extendedproperties.adoc[]" as repo_sys.ExtendedProperties << V >> {
  - class : (tinyint)
  class_desc : (nvarchar(60))
  entity_column_name : (nvarchar(128))
  entity_index_name : (nvarchar(128))
  entity_parameter_name : (nvarchar(128))
  level2type : (varchar(9))
  - major_id : (int)
  - minor_id : (int)
  minor_name : (nvarchar(128))
  parent_name : (sysname)
  parent_object_id : (int)
  parent_type : (char(2))
  property_basetype : (sql_variant)
  - property_name : (sysname)
  property_nvarchar : (nvarchar(4000))
  property_value : (sql_variant)
  SysObject_name : (nvarchar(128))
  SysObject_schema_name : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:repo_sys.sysschema.adoc[]" as repo_sys.SysSchema << V >> {
  - SysSchema_id : (int)
  - SysSchema_name : (sysname)
  SysSchema_principal_id : (int)
  SysSchema_RepoSchema_guid : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:sys_dwh.schemas.adoc[]" as sys_dwh.schemas << SN >> {
  --
}

repo_sys.ExtendedProperties <.. repo_sys.SysSchema
repo_sys.SysSchema <.. repo.SysSchema_RepoSchema_via_guid
repo_sys.SysSchema <.. repo.SysSchema_RepoSchema_via_name
repo_sys.SysSchema <.. repo.usp_sync_guid_RepoSchema
sys_dwh.schemas <.. repo_sys.SysSchema
"repo_sys.SysSchema::SysSchema_id" <-- "repo.SysSchema_RepoSchema_via_guid::SysSchema_id"
"repo_sys.SysSchema::SysSchema_id" <-- "repo.SysSchema_RepoSchema_via_name::SysSchema_id"
"repo_sys.SysSchema::SysSchema_name" <-- "repo.SysSchema_RepoSchema_via_name::SysSchema_name"
"repo_sys.SysSchema::SysSchema_name" <-- "repo.SysSchema_RepoSchema_via_guid::SysSchema_name"
"repo_sys.SysSchema::SysSchema_RepoSchema_guid" <-- "repo.SysSchema_RepoSchema_via_guid::SysSchema_RepoSchema_guid"
"repo_sys.SysSchema::SysSchema_RepoSchema_guid" <-- "repo.SysSchema_RepoSchema_via_name::SysSchema_RepoSchema_guid"

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_colref[]


== sql_modules_definition

// tag::sql_modules_definition[]
[%collapsible]
=======
[source,sql,numbered,indent=0]
----


CREATE View repo_sys.SysSchema
As
--
Select
    SysSchema_id              = sch.schema_id
  , SysSchema_name            = sch.name Collate Database_Default
  , SysSchema_principal_id    = sch.principal_id
  , SysSchema_RepoSchema_guid = Try_Cast(ep.property_value As UniqueIdentifier)
From
    sys_dwh.schemas                 As sch
    Left Outer Join
        repo_sys.ExtendedProperties As ep
            On
            ep.major_id          = sch.schema_id
            And ep.minor_id      = 0
            And ep.class         = 3 /*class 3 - Schema*/
            And ep.property_name = N'RepoSchema_guid';

-- Where [sch].[name] <> 'sys'

----
=======
// end::sql_modules_definition[]


