// tag::HeaderFullDisplayName[]
= sqlparse.RepoObject_SqlModules_51_Identitfier - V
// end::HeaderFullDisplayName[]

== existing_properties

// tag::existing_properties[]

:ExistsProperty--antorareferencedlist:
:ExistsProperty--antorareferencinglist:
:ExistsProperty--is_repo_managed:
:ExistsProperty--is_ssas:
:ExistsProperty--referencedobjectlist:
:ExistsProperty--sql_modules_definition:
:ExistsProperty--FK:
:ExistsProperty--AntoraIndexList:
:ExistsProperty--Columns:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
0E813EBD-7764-EB11-84DD-A81E8446D5B0
// end::RepoObject_guid[]

== RepoObject_FullDisplayName2

// tag::RepoObject_FullDisplayName2[]
sqlparse.RepoObject_SqlModules_51_Identitfier
// end::RepoObject_FullDisplayName2[]

== SysObject_type

// tag::SysObject_type[]
V 
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
view
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
148911602
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2021-08-17 20:14:37
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]
[discrete]
== _


[#column-child0underlineclass]
=== child0_class

[cols="d,8a,m,m,m"]
|===
|
|child0_class
|nvarchar(500)
|NULL
|
|===

.Referenced Columns
--
* xref:sqlparse.repoobject_sqlmodules_20_statement_children.adoc#column-child0underlineclass[+sqlparse.RepoObject_SqlModules_20_statement_children.child0_class+]
--

.Referencing Columns
--
* xref:sqlparse.repoobject_sqlmodules_52_identitfier_quotename.adoc#column-child0underlineclass[+sqlparse.RepoObject_SqlModules_52_Identitfier_QuoteName.child0_class+]
--


[#column-children]
=== children

[cols="d,8a,m,m,m"]
|===
|
|children
|nvarchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:sqlparse.repoobject_sqlmodules_20_statement_children.adoc#column-children[+sqlparse.RepoObject_SqlModules_20_statement_children.children+]
--

.Referencing Columns
--
* xref:sqlparse.repoobject_sqlmodules_52_identitfier_quotename.adoc#column-children[+sqlparse.RepoObject_SqlModules_52_Identitfier_QuoteName.children+]
--


[#column-class]
=== class

[cols="d,8a,m,m,m"]
|===
|
|class
|nvarchar(500)
|NULL
|
|===

.Referenced Columns
--
* xref:sqlparse.repoobject_sqlmodules_20_statement_children.adoc#column-class[+sqlparse.RepoObject_SqlModules_20_statement_children.class+]
--


[#column-isunderlinegroup]
=== is_group

[cols="d,8a,m,m,m"]
|===
|
|is_group
|bit
|NULL
|
|===

.Referenced Columns
--
* xref:sqlparse.repoobject_sqlmodules_20_statement_children.adoc#column-isunderlinegroup[+sqlparse.RepoObject_SqlModules_20_statement_children.is_group+]
--

.Referencing Columns
--
* xref:sqlparse.repoobject_sqlmodules_52_identitfier_quotename.adoc#column-isunderlinegroup[+sqlparse.RepoObject_SqlModules_52_Identitfier_QuoteName.is_group+]
--


[#column-isunderlinekeyword]
=== is_keyword

[cols="d,8a,m,m,m"]
|===
|
|is_keyword
|bit
|NULL
|
|===

.Referenced Columns
--
* xref:sqlparse.repoobject_sqlmodules_20_statement_children.adoc#column-isunderlinekeyword[+sqlparse.RepoObject_SqlModules_20_statement_children.is_keyword+]
--

.Referencing Columns
--
* xref:sqlparse.repoobject_sqlmodules_52_identitfier_quotename.adoc#column-isunderlinekeyword[+sqlparse.RepoObject_SqlModules_52_Identitfier_QuoteName.is_keyword+]
--


[#column-isunderlinewhitespace]
=== is_whitespace

[cols="d,8a,m,m,m"]
|===
|
|is_whitespace
|bit
|NULL
|
|===

.Referenced Columns
--
* xref:sqlparse.repoobject_sqlmodules_20_statement_children.adoc#column-isunderlinewhitespace[+sqlparse.RepoObject_SqlModules_20_statement_children.is_whitespace+]
--

.Referencing Columns
--
* xref:sqlparse.repoobject_sqlmodules_52_identitfier_quotename.adoc#column-isunderlinewhitespace[+sqlparse.RepoObject_SqlModules_52_Identitfier_QuoteName.is_whitespace+]
--


[#column-jsonunderlinekey]
=== json_key

[cols="d,8a,m,m,m"]
|===
|
|json_key
|nvarchar(4000)
|NOT NULL
|
|===

.Referenced Columns
--
* xref:sqlparse.repoobject_sqlmodules_20_statement_children.adoc#column-jsonunderlinekey[+sqlparse.RepoObject_SqlModules_20_statement_children.json_key+]
--

.Referencing Columns
--
* xref:sqlparse.repoobject_sqlmodules_52_identitfier_quotename.adoc#column-jsonunderlinekey[+sqlparse.RepoObject_SqlModules_52_Identitfier_QuoteName.json_key+]
--


[#column-normalized]
=== normalized

[cols="d,8a,m,m,m"]
|===
|
|normalized
|nvarchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:sqlparse.repoobject_sqlmodules_20_statement_children.adoc#column-normalized[+sqlparse.RepoObject_SqlModules_20_statement_children.normalized+]
--

.Referencing Columns
--
* xref:sqlparse.repoobject_sqlmodules_52_identitfier_quotename.adoc#column-normalized[+sqlparse.RepoObject_SqlModules_52_Identitfier_QuoteName.normalized+]
--


[#column-repoobjectunderlineguid]
=== RepoObject_guid

[cols="d,8a,m,m,m"]
|===
|
|RepoObject_guid
|uniqueidentifier
|NOT NULL
|
|===

.Referenced Columns
--
* xref:sqlparse.repoobject_sqlmodules_20_statement_children.adoc#column-repoobjectunderlineguid[+sqlparse.RepoObject_SqlModules_20_statement_children.RepoObject_guid+]
--

.Referencing Columns
--
* xref:sqlparse.repoobject_sqlmodules_52_identitfier_quotename.adoc#column-repoobjectunderlineguid[+sqlparse.RepoObject_SqlModules_52_Identitfier_QuoteName.RepoObject_guid+]
--


[#column-rownumberunderlineperunderlineobject]
=== RowNumber_per_Object

[cols="d,8a,m,m,m"]
|===
|
|RowNumber_per_Object
|bigint
|NULL
|
|===

.Referenced Columns
--
* xref:sqlparse.repoobject_sqlmodules_20_statement_children.adoc#column-rownumberunderlineperunderlineobject[+sqlparse.RepoObject_SqlModules_20_statement_children.RowNumber_per_Object+]
--

.Referencing Columns
--
* xref:sqlparse.repoobject_sqlmodules_52_identitfier_quotename.adoc#column-rownumberunderlineperunderlineobject[+sqlparse.RepoObject_SqlModules_52_Identitfier_QuoteName.RowNumber_per_Object+]
--


[#column-sourceunderlinecolumn]
=== source_column

[cols="d,8a,m,m,m"]
|===
|
|source_column
|nvarchar(max)
|NULL
|
|===

.Referencing Columns
--
* xref:sqlparse.repoobject_sqlmodules_52_identitfier_quotename.adoc#column-sourceunderlinecolumn[+sqlparse.RepoObject_SqlModules_52_Identitfier_QuoteName.source_column+]
--


[#column-sourceunderlinetable]
=== source_table

[cols="d,8a,m,m,m"]
|===
|
|source_table
|nvarchar(max)
|NULL
|
|===

.Referencing Columns
--
* xref:sqlparse.repoobject_sqlmodules_52_identitfier_quotename.adoc#column-sourceunderlinetable[+sqlparse.RepoObject_SqlModules_52_Identitfier_QuoteName.source_table+]
--


[#column-sysobjectunderlinefullname]
=== SysObject_fullname

[cols="d,8a,m,m,m"]
|===
|
|SysObject_fullname
|nvarchar(261)
|NULL
|
|===

.Description
--
(concat('[',[SysObject_schema_name],'].[',[SysObject_name],']'))
--
{empty} +

.Referenced Columns
--
* xref:sqlparse.repoobject_sqlmodules_20_statement_children.adoc#column-sysobjectunderlinefullname[+sqlparse.RepoObject_SqlModules_20_statement_children.SysObject_fullname+]
--

.Referencing Columns
--
* xref:sqlparse.repoobject_sqlmodules_52_identitfier_quotename.adoc#column-sysobjectunderlinefullname[+sqlparse.RepoObject_SqlModules_52_Identitfier_QuoteName.SysObject_fullname+]
--


// end::AntoraColumnDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]













// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]
|
|<<column-child0underlineclass>>
|nvarchar(500)
|NULL
|

|
|<<column-children>>
|nvarchar(max)
|NULL
|

|
|<<column-class>>
|nvarchar(500)
|NULL
|

|
|<<column-isunderlinegroup>>
|bit
|NULL
|

|
|<<column-isunderlinekeyword>>
|bit
|NULL
|

|
|<<column-isunderlinewhitespace>>
|bit
|NULL
|

|
|<<column-jsonunderlinekey>>
|nvarchar(4000)
|NOT NULL
|

|
|<<column-normalized>>
|nvarchar(max)
|NULL
|

|
|<<column-repoobjectunderlineguid>>
|uniqueidentifier
|NOT NULL
|

|
|<<column-rownumberunderlineperunderlineobject>>
|bigint
|NULL
|

|
|<<column-sourceunderlinecolumn>>
|nvarchar(max)
|NULL
|

|
|<<column-sourceunderlinetable>>
|nvarchar(max)
|NULL
|

|
|<<column-sysobjectunderlinefullname>>
|nvarchar(261)
|NULL
|

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

[#index-idxunderlinerepoobjectunderlinesqlmodulesunderline51underlineidentitfierunderlineunderline1]
=== idx_RepoObject_SqlModules_51_Identitfier++__++1

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-RepoObject_guid>>; uniqueidentifier
* <<column-json_key>>; nvarchar(4000)
--
* PK, Unique, Real: 0, 0, 0


[#index-idxunderlinerepoobjectunderlinesqlmodulesunderline51underlineidentitfierunderlineunderline2]
=== idx_RepoObject_SqlModules_51_Identitfier++__++2

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-RepoObject_guid>>; uniqueidentifier
--
* PK, Unique, Real: 0, 0, 0

// end::AntoraIndexList[]

== AntoraMeasureDetails

// tag::AntoraMeasureDetails[]

// end::AntoraMeasureDetails[]

== AntoraMeasureDescriptions



== AntoraParameterList

// tag::AntoraParameterList[]

// end::AntoraParameterList[]

== AntoraXrefCulturesList

// tag::AntoraXrefCulturesList[]
* xref:dhw:sqldb:sqlparse.repoobject_sqlmodules_51_identitfier.adoc[] - 
// end::AntoraXrefCulturesList[]

== cultures_count

// tag::cultures_count[]
1
// end::cultures_count[]

== Other tags

source: property.RepoObjectProperty_cross As rop_cross


=== additional_reference_csv

// tag::additional_reference_csv[]

// end::additional_reference_csv[]


=== AdocUspSteps

// tag::adocuspsteps[]

// end::adocuspsteps[]


=== AntoraReferencedList

// tag::antorareferencedlist[]
* xref:dhw:sqldb:sqlparse.repoobject_sqlmodules_20_statement_children.adoc[]
// end::antorareferencedlist[]


=== AntoraReferencingList

// tag::antorareferencinglist[]
* xref:dhw:sqldb:sqlparse.repoobject_sqlmodules_52_identitfier_quotename.adoc[]
// end::antorareferencinglist[]


=== Description

// tag::description[]

// end::description[]


=== exampleUsage

// tag::exampleusage[]

// end::exampleusage[]


=== exampleUsage_2

// tag::exampleusage_2[]

// end::exampleusage_2[]


=== exampleUsage_3

// tag::exampleusage_3[]

// end::exampleusage_3[]


=== exampleUsage_4

// tag::exampleusage_4[]

// end::exampleusage_4[]


=== exampleUsage_5

// tag::exampleusage_5[]

// end::exampleusage_5[]


=== exampleWrong_Usage

// tag::examplewrong_usage[]

// end::examplewrong_usage[]


=== has_execution_plan_issue

// tag::has_execution_plan_issue[]

// end::has_execution_plan_issue[]


=== has_get_referenced_issue

// tag::has_get_referenced_issue[]

// end::has_get_referenced_issue[]


=== has_history

// tag::has_history[]

// end::has_history[]


=== has_history_columns

// tag::has_history_columns[]

// end::has_history_columns[]


=== InheritanceType

// tag::inheritancetype[]

// end::inheritancetype[]


=== is_persistence

// tag::is_persistence[]

// end::is_persistence[]


=== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]

// end::is_persistence_check_duplicate_per_pk[]


=== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]

// end::is_persistence_check_for_empty_source[]


=== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]

// end::is_persistence_delete_changed[]


=== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]

// end::is_persistence_delete_missing[]


=== is_persistence_insert

// tag::is_persistence_insert[]

// end::is_persistence_insert[]


=== is_persistence_truncate

// tag::is_persistence_truncate[]

// end::is_persistence_truncate[]


=== is_persistence_update_changed

// tag::is_persistence_update_changed[]

// end::is_persistence_update_changed[]


=== is_repo_managed

// tag::is_repo_managed[]
0
// end::is_repo_managed[]


=== is_ssas

// tag::is_ssas[]
0
// end::is_ssas[]


=== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


=== MS_Description

// tag::ms_description[]

// end::ms_description[]


=== persistence_source_RepoObject_fullname

// tag::persistence_source_repoobject_fullname[]

// end::persistence_source_repoobject_fullname[]


=== persistence_source_RepoObject_fullname2

// tag::persistence_source_repoobject_fullname2[]

// end::persistence_source_repoobject_fullname2[]


=== persistence_source_RepoObject_guid

// tag::persistence_source_repoobject_guid[]

// end::persistence_source_repoobject_guid[]


=== persistence_source_RepoObject_xref

// tag::persistence_source_repoobject_xref[]

// end::persistence_source_repoobject_xref[]


=== pk_index_guid

// tag::pk_index_guid[]

// end::pk_index_guid[]


=== pk_IndexPatternColumnDatatype

// tag::pk_indexpatterncolumndatatype[]

// end::pk_indexpatterncolumndatatype[]


=== pk_IndexPatternColumnName

// tag::pk_indexpatterncolumnname[]

// end::pk_indexpatterncolumnname[]


=== pk_IndexSemanticGroup

// tag::pk_indexsemanticgroup[]

// end::pk_indexsemanticgroup[]


=== ReferencedObjectList

// tag::referencedobjectlist[]
* [sqlparse].[RepoObject_SqlModules_20_statement_children]
// end::referencedobjectlist[]


=== usp_persistence_RepoObject_guid

// tag::usp_persistence_repoobject_guid[]

// end::usp_persistence_repoobject_guid[]


=== UspExamples

// tag::uspexamples[]

// end::uspexamples[]


=== uspgenerator_usp_id

// tag::uspgenerator_usp_id[]

// end::uspgenerator_usp_id[]


=== UspParameters

// tag::uspparameters[]

// end::uspparameters[]

== Boolean Attributes

source: property.RepoObjectProperty WHERE property_int = 1

// tag::boolean_attributes[]


// end::boolean_attributes[]

== PlantUML diagrams

=== PlantUML Entity

// tag::puml_entity[]
[plantuml, entity-{docname}, svg, subs=macros]
....
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_51_identitfier.adoc[]" as sqlparse.RepoObject_SqlModules_51_Identitfier << V >> {
  child0_class : (nvarchar(500))
  children : (nvarchar(max))
  class : (nvarchar(500))
  is_group : (bit)
  is_keyword : (bit)
  is_whitespace : (bit)
  - json_key : (nvarchar(4000))
  normalized : (nvarchar(max))
  - RepoObject_guid : (uniqueidentifier)
  RowNumber_per_Object : (bigint)
  source_column : (nvarchar(max))
  source_table : (nvarchar(max))
  SysObject_fullname : (nvarchar(261))
  --
}
....

// end::puml_entity[]

=== PlantUML Entity 1 1 FK

// tag::puml_entity_1_1_fk[]
[plantuml, entity_1_1_fk-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_51_identitfier.adoc[]" as sqlparse.RepoObject_SqlModules_51_Identitfier << V >> {
- idx_RepoObject_SqlModules_51_Identitfier__1

..
RepoObject_guid; uniqueidentifier
json_key; nvarchar(4000)
--
- idx_RepoObject_SqlModules_51_Identitfier__2

..
RepoObject_guid; uniqueidentifier
}



footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_fk[]

=== PlantUML 1 1 ObjectRef

// tag::puml_entity_1_1_objectref[]
[plantuml, entity_1_1_objectref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_20_statement_children.adoc[]" as sqlparse.RepoObject_SqlModules_20_statement_children << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **json_key** : (nvarchar(4000))
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_51_identitfier.adoc[]" as sqlparse.RepoObject_SqlModules_51_Identitfier << V >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_52_identitfier_quotename.adoc[]" as sqlparse.RepoObject_SqlModules_52_Identitfier_QuoteName << V >> {
  --
}

sqlparse.RepoObject_SqlModules_20_statement_children <.. sqlparse.RepoObject_SqlModules_51_Identitfier
sqlparse.RepoObject_SqlModules_51_Identitfier <.. sqlparse.RepoObject_SqlModules_52_Identitfier_QuoteName

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_objectref[]

=== PlantUML 30 0 ObjectRef

// tag::puml_entity_30_0_objectref[]
[plantuml, entity_30_0_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:config.ftv_get_parameter_value.adoc[]" as config.ftv_get_parameter_value << IF >> {
  --
}

entity "puml-link:dhw:sqldb:config.parameter.adoc[]" as config.Parameter << U >> {
  - **Parameter_name** : (varchar(100))
  - **sub_Parameter** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:configt.parameter_default.adoc[]" as configT.Parameter_default << V >> {
  - **Parameter_name** : (varchar(52))
  - **sub_Parameter** : (nvarchar(26))
  --
}

entity "puml-link:dhw:sqldb:property.external_repoobjectproperty.adoc[]" as property.external_RepoObjectProperty << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.propertyname_repoobject.adoc[]" as property.PropertyName_RepoObject << V >> {
  **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.propertyname_repoobject_t.adoc[]" as property.PropertyName_RepoObject_T << U >> {
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty.adoc[]" as property.RepoObjectProperty << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty_external_src.adoc[]" as property.RepoObjectProperty_external_src << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty_external_tgt.adoc[]" as property.RepoObjectProperty_external_tgt << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty_selectedpropertyname_split.adoc[]" as property.RepoObjectProperty_SelectedPropertyName_split << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference.adoc[]" as reference.additional_Reference << U >> {
  # **tik_hash_c** : (nvarchar(32))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_from_properties_src.adoc[]" as reference.additional_Reference_from_properties_src << V >> {
  **referenced_AntoraComponent** : (nvarchar(max))
  **referenced_AntoraModule** : (nvarchar(max))
  **referenced_Schema** : (nvarchar(max))
  **referenced_Object** : (nvarchar(max))
  **referenced_Column** : (nvarchar(max))
  **referencing_AntoraComponent** : (nvarchar(max))
  **referencing_AntoraModule** : (nvarchar(max))
  **referencing_Schema** : (nvarchar(max))
  **referencing_Object** : (nvarchar(max))
  **referencing_Column** : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_from_properties_tgt.adoc[]" as reference.additional_Reference_from_properties_tgt << V >> {
  - **referenced_AntoraComponent** : (nvarchar(128))
  - **referenced_AntoraModule** : (nvarchar(128))
  - **referenced_Schema** : (nvarchar(128))
  - **referenced_Object** : (nvarchar(128))
  **referenced_Column** : (nvarchar(128))
  - **referencing_AntoraComponent** : (nvarchar(128))
  - **referencing_AntoraModule** : (nvarchar(128))
  - **referencing_Schema** : (nvarchar(128))
  - **referencing_Object** : (nvarchar(128))
  **referencing_Column** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_from_ssas_src.adoc[]" as reference.additional_Reference_from_ssas_src << V >> {
  **referenced_AntoraComponent** : (nvarchar(128))
  **referenced_AntoraModule** : (nvarchar(128))
  **referenced_Schema** : (nvarchar(max))
  **referenced_Object** : (nvarchar(max))
  **referenced_Column** : (nvarchar(500))
  **referencing_AntoraComponent** : (nvarchar(max))
  **referencing_AntoraModule** : (nvarchar(max))
  - **referencing_Schema** : (nvarchar(128))
  - **referencing_Object** : (nvarchar(128))
  **referencing_Column** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_from_ssas_tgt.adoc[]" as reference.additional_Reference_from_ssas_tgt << V >> {
  - **referenced_AntoraComponent** : (nvarchar(128))
  - **referenced_AntoraModule** : (nvarchar(128))
  - **referenced_Schema** : (nvarchar(128))
  - **referenced_Object** : (nvarchar(128))
  **referenced_Column** : (nvarchar(128))
  - **referencing_AntoraComponent** : (nvarchar(128))
  - **referencing_AntoraModule** : (nvarchar(128))
  - **referencing_Schema** : (nvarchar(128))
  - **referencing_Object** : (nvarchar(128))
  **referencing_Column** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_is_external.adoc[]" as reference.additional_Reference_is_external << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_object.adoc[]" as reference.additional_Reference_Object << V >> {
  - **AntoraComponent** : (nvarchar(128))
  - **AntoraModule** : (nvarchar(128))
  - **SchemaName** : (nvarchar(128))
  - **ObjectName** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_object_t.adoc[]" as reference.additional_Reference_Object_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_wo_columns_from_properties_src.adoc[]" as reference.additional_Reference_wo_columns_from_properties_src << V >> {
  **referenced_AntoraComponent** : (nvarchar(max))
  **referenced_AntoraModule** : (nvarchar(max))
  **referenced_Schema** : (nvarchar(max))
  **referenced_Object** : (nvarchar(max))
  **referencing_AntoraComponent** : (nvarchar(max))
  **referencing_AntoraModule** : (nvarchar(max))
  **referencing_Schema** : (nvarchar(max))
  **referencing_Object** : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_wo_columns_from_properties_tgt.adoc[]" as reference.additional_Reference_wo_columns_from_properties_tgt << V >> {
  - **referenced_AntoraComponent** : (nvarchar(128))
  - **referenced_AntoraModule** : (nvarchar(128))
  - **referenced_Schema** : (nvarchar(128))
  - **referenced_Object** : (nvarchar(128))
  - **referencing_AntoraComponent** : (nvarchar(128))
  - **referencing_AntoraModule** : (nvarchar(128))
  - **referencing_Schema** : (nvarchar(128))
  - **referencing_Object** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject.adoc[]" as repo.RepoObject << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_external_src.adoc[]" as repo.RepoObject_external_src << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_external_tgt.adoc[]" as repo.RepoObject_external_tgt << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_ssas_src.adoc[]" as repo.RepoObject_SSAS_src << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_ssas_tgt.adoc[]" as repo.RepoObject_SSAS_tgt << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.reposchema.adoc[]" as repo.RepoSchema << U >> {
  - **RepoSchema_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.reposchema_ssas_src.adoc[]" as repo.RepoSchema_ssas_src << V >> {
  - **RepoSchema_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:repo.reposchema_ssas_tgt.adoc[]" as repo.RepoSchema_ssas_tgt << V >> {
  - **RepoSchema_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:sqlparse.ftv_sqlparse_with_some_children.adoc[]" as sqlparse.ftv_sqlparse_with_some_children << IF >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules.adoc[]" as sqlparse.RepoObject_SqlModules << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_10_statement.adoc[]" as sqlparse.RepoObject_SqlModules_10_statement << V >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_20_statement_children.adoc[]" as sqlparse.RepoObject_SqlModules_20_statement_children << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **json_key** : (nvarchar(4000))
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_51_identitfier.adoc[]" as sqlparse.RepoObject_SqlModules_51_Identitfier << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.additional_reference_step1.adoc[]" as ssas.additional_Reference_step1 << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json.adoc[]" as ssas.model_json << U >> {
  - **databasename** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_10.adoc[]" as ssas.model_json_10 << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_20.adoc[]" as ssas.model_json_20 << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_201_descriptions_multiline.adoc[]" as ssas.model_json_201_descriptions_multiline << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_2011_descriptions_stragg.adoc[]" as ssas.model_json_2011_descriptions_StrAgg << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31_tables.adoc[]" as ssas.model_json_31_tables << V >> {
  - **databasename** : (nvarchar(128))
  **tables_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31_tables_t.adoc[]" as ssas.model_json_31_tables_T << U >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_311_tables_columns.adoc[]" as ssas.model_json_311_tables_columns << V >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  **tables_columns_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_311_tables_columns_t.adoc[]" as ssas.model_json_311_tables_columns_T << U >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  - **tables_columns_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_313_tables_partitions.adoc[]" as ssas.model_json_313_tables_partitions << V >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  **tables_partitions_name** : (nvarchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_3131_tables_partitions_source.adoc[]" as ssas.model_json_3131_tables_partitions_source << V >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  **tables_partitions_name** : (nvarchar(500))
  **tables_partitions_source_name** : (nvarchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31311_tables_partitions_source_posfrom.adoc[]" as ssas.model_json_31311_tables_partitions_source_PosFrom << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_313111_tables_partitions_source_stringfrom.adoc[]" as ssas.model_json_313111_tables_partitions_source_StringFrom << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_3131111_tables_partitions_source_posdot.adoc[]" as ssas.model_json_3131111_tables_partitions_source_PosDot << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31311111_tables_partitions_source_part123.adoc[]" as ssas.model_json_31311111_tables_partitions_source_Part123 << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_33_datasources.adoc[]" as ssas.model_json_33_dataSources << V >> {
  - **databasename** : (nvarchar(128))
  **dataSources_name** : (nvarchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_33_datasources_t.adoc[]" as ssas.model_json_33_dataSources_T << U >> {
  - **databasename** : (nvarchar(128))
  - **dataSources_name** : (nvarchar(500))
  --
}

config.ftv_get_parameter_value <.. reference.additional_Reference_is_external
config.ftv_get_parameter_value <.. ssas.additional_Reference_step1
config.ftv_get_parameter_value <.. repo.RepoObject_external_src
config.Parameter <.. config.ftv_get_parameter_value
config.Parameter <.. property.PropertyName_RepoObject
configT.Parameter_default <.. config.Parameter
property.external_RepoObjectProperty <.. property.RepoObjectProperty_external_src
property.PropertyName_RepoObject <.. property.PropertyName_RepoObject_T
property.PropertyName_RepoObject_T <.. property.RepoObjectProperty_external_tgt
property.RepoObjectProperty <.. property.PropertyName_RepoObject
property.RepoObjectProperty <.. property.RepoObjectProperty_SelectedPropertyName_split
property.RepoObjectProperty_external_src <.. property.RepoObjectProperty_external_tgt
property.RepoObjectProperty_external_tgt <.. property.RepoObjectProperty
property.RepoObjectProperty_SelectedPropertyName_split <.. reference.additional_Reference_wo_columns_from_properties_src
property.RepoObjectProperty_SelectedPropertyName_split <.. reference.additional_Reference_from_properties_src
reference.additional_Reference <.. reference.additional_Reference_is_external
reference.additional_Reference_from_properties_src <.. reference.additional_Reference_from_properties_tgt
reference.additional_Reference_from_properties_tgt <.. reference.additional_Reference
reference.additional_Reference_from_ssas_src <.. reference.additional_Reference_from_ssas_tgt
reference.additional_Reference_from_ssas_tgt <.. reference.additional_Reference
reference.additional_Reference_is_external <.. reference.additional_Reference_Object
reference.additional_Reference_Object <.. reference.additional_Reference_Object_T
reference.additional_Reference_Object_T <.. repo.RepoObject_external_src
reference.additional_Reference_wo_columns_from_properties_src <.. reference.additional_Reference_wo_columns_from_properties_tgt
reference.additional_Reference_wo_columns_from_properties_tgt <.. reference.additional_Reference
repo.RepoObject <.. sqlparse.RepoObject_SqlModules_10_statement
repo.RepoObject <.. property.RepoObjectProperty_external_tgt
repo.RepoObject <.. repo.RepoObject_external_src
repo.RepoObject_external_src <.. repo.RepoObject_external_tgt
repo.RepoObject_external_tgt <.. repo.RepoObject
repo.RepoObject_SSAS_src <.. repo.RepoObject_SSAS_tgt
repo.RepoObject_SSAS_tgt <.. repo.RepoObject
repo.RepoSchema <.. repo.RepoObject_SSAS_src
repo.RepoSchema_ssas_src <.. repo.RepoSchema_ssas_tgt
repo.RepoSchema_ssas_tgt <.. repo.RepoSchema
sqlparse.ftv_sqlparse_with_some_children <.. sqlparse.RepoObject_SqlModules_20_statement_children
sqlparse.RepoObject_SqlModules <.. sqlparse.RepoObject_SqlModules_10_statement
sqlparse.RepoObject_SqlModules_10_statement <.. sqlparse.RepoObject_SqlModules_20_statement_children
sqlparse.RepoObject_SqlModules_20_statement_children <.. sqlparse.RepoObject_SqlModules_51_Identitfier
ssas.additional_Reference_step1 <.. reference.additional_Reference_from_ssas_src
ssas.model_json <.. ssas.model_json_10
ssas.model_json_10 <.. ssas.model_json_20
ssas.model_json_20 <.. repo.RepoSchema_ssas_src
ssas.model_json_20 <.. ssas.model_json_31_tables
ssas.model_json_20 <.. ssas.model_json_33_dataSources
ssas.model_json_20 <.. ssas.model_json_201_descriptions_multiline
ssas.model_json_201_descriptions_multiline <.. ssas.model_json_2011_descriptions_StrAgg
ssas.model_json_2011_descriptions_StrAgg <.. repo.RepoSchema_ssas_src
ssas.model_json_31_tables <.. ssas.model_json_31_tables_T
ssas.model_json_31_tables_T <.. ssas.model_json_313_tables_partitions
ssas.model_json_31_tables_T <.. repo.RepoObject_SSAS_src
ssas.model_json_31_tables_T <.. ssas.model_json_311_tables_columns
ssas.model_json_311_tables_columns <.. ssas.model_json_311_tables_columns_T
ssas.model_json_311_tables_columns_T <.. ssas.additional_Reference_step1
ssas.model_json_313_tables_partitions <.. ssas.model_json_3131_tables_partitions_source
ssas.model_json_3131_tables_partitions_source <.. ssas.model_json_31311_tables_partitions_source_PosFrom
ssas.model_json_31311_tables_partitions_source_PosFrom <.. ssas.model_json_313111_tables_partitions_source_StringFrom
ssas.model_json_313111_tables_partitions_source_StringFrom <.. ssas.model_json_3131111_tables_partitions_source_PosDot
ssas.model_json_3131111_tables_partitions_source_PosDot <.. ssas.model_json_31311111_tables_partitions_source_Part123
ssas.model_json_31311111_tables_partitions_source_Part123 <.. ssas.additional_Reference_step1
ssas.model_json_33_dataSources <.. ssas.model_json_33_dataSources_T
ssas.model_json_33_dataSources_T <.. ssas.additional_Reference_step1

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_30_0_objectref[]

=== PlantUML 0 30 ObjectRef

// tag::puml_entity_0_30_objectref[]
[plantuml, entity_0_30_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:docs.antoranavlistpage_by_schema.adoc[]" as docs.AntoraNavListPage_by_schema << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ftv_repoobject_reference_plantuml_entityreflist.adoc[]" as docs.ftv_RepoObject_Reference_PlantUml_EntityRefList << IF >> {
  --
}

entity "puml-link:dhw:sqldb:docs.objectrefcyclic.adoc[]" as docs.ObjectRefCyclic << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.objectrefcyclic_entitylist.adoc[]" as docs.ObjectRefCyclic_EntityList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_adoc.adoc[]" as docs.RepoObject_Adoc << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_adoc_t.adoc[]" as docs.RepoObject_Adoc_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_columnlist.adoc[]" as docs.RepoObject_ColumnList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_columnlist_t.adoc[]" as docs.RepoObject_ColumnList_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml.adoc[]" as docs.RepoObject_Plantuml << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_colreflist_1_1.adoc[]" as docs.RepoObject_Plantuml_ColRefList_1_1 << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_entity.adoc[]" as docs.RepoObject_Plantuml_Entity << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_entity_t.adoc[]" as docs.RepoObject_Plantuml_Entity_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_pumlentityfklist.adoc[]" as docs.RepoObject_PlantUml_PumlEntityFkList << V >> {
  **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_t.adoc[]" as docs.RepoObject_Plantuml_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.schema_entitylist.adoc[]" as docs.Schema_EntityList << V >> {
  - **RepoObject_schema_name** : (nvarchar(128))
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.schema_puml.adoc[]" as docs.Schema_puml << V >> {
  - **RepoSchema_guid** : (uniqueidentifier)
  **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport.adoc[]" as docs.usp_AntoraExport << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_objectpartialscontent.adoc[]" as docs.usp_AntoraExport_ObjectPartialsContent << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_objectpuml.adoc[]" as docs.usp_AntoraExport_ObjectPuml << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_repoobject_adoc_t.adoc[]" as docs.usp_PERSIST_RepoObject_Adoc_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_repoobject_columnlist_t.adoc[]" as docs.usp_PERSIST_RepoObject_ColumnList_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_repoobject_plantuml_entity_t.adoc[]" as docs.usp_PERSIST_RepoObject_Plantuml_Entity_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_repoobject_plantuml_t.adoc[]" as docs.usp_PERSIST_RepoObject_Plantuml_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty_collect_source_rogross.adoc[]" as property.RepoObjectProperty_Collect_source_ROGross << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **property_name** : (varchar(39))
  --
}

entity "puml-link:dhw:sqldb:property.usp_repoobject_inheritance.adoc[]" as property.usp_RepoObject_Inheritance << P >> {
  --
}

entity "puml-link:dhw:sqldb:property.usp_repoobjectproperty_collect.adoc[]" as property.usp_RepoObjectProperty_collect << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.ftv_repoobject_columreferencerepoobject.adoc[]" as reference.ftv_RepoObject_ColumReferenceRepoObject << IF >> {
  --
}

entity "puml-link:dhw:sqldb:reference.ftv_repoobject_dbmlcolumnrelation.adoc[]" as reference.ftv_RepoObject_DbmlColumnRelation << IF >> {
  --
}

entity "puml-link:dhw:sqldb:reference.ftv_repoobjectcolumn_referencetree.adoc[]" as reference.ftv_RepoObjectColumn_ReferenceTree << IF >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_reference.adoc[]" as reference.RepoObjectColumn_reference << V >> {
  **referenced_RepoObjectColumn_guid** : (uniqueidentifier)
  **referencing_RepoObjectColumn_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_reference_sqlmodules.adoc[]" as reference.RepoObjectColumn_reference_SqlModules << V >> {
  **referencing_id** : (int)
  **referencing_minor_id** : (int)
  **referenced_id** : (int)
  **referenced_minor_id** : (int)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_reference_t.adoc[]" as reference.RepoObjectColumn_reference_T << U >> {
  - **referenced_RepoObjectColumn_guid** : (uniqueidentifier)
  - **referencing_RepoObjectColumn_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_reference_union.adoc[]" as reference.RepoObjectColumn_reference_union << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_referencedlist.adoc[]" as reference.RepoObjectColumn_ReferencedList << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_referencedreferencing.adoc[]" as reference.RepoObjectColumn_ReferencedReferencing << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_referencetree.adoc[]" as reference.RepoObjectColumn_ReferenceTree << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_referencinglist.adoc[]" as reference.RepoObjectColumn_ReferencingList << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_relationscript.adoc[]" as reference.RepoObjectColumn_RelationScript << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_persist_repoobjectcolumn_reference_t.adoc[]" as reference.usp_PERSIST_RepoObjectColumn_reference_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.check_indexcolumn_virtual_referenced_setpoint.adoc[]" as repo.check_IndexColumn_virtual_referenced_setpoint << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.index_referencing_indexpatterncolumnguid.adoc[]" as repo.Index_referencing_IndexPatternColumnGuid << V >> {
  **source_index_guid** : (uniqueidentifier)
  **referencing_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.indexcolumn_referencedreferencing_hasfullcolumnsinreferencing.adoc[]" as repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing << V >> {
  - **index_guid** : (uniqueidentifier)
  - **index_column_id** : (int)
  **RowNumberInReferencing** : (bigint)
  --
}

entity "puml-link:dhw:sqldb:repo.indexcolumn_referencedreferencing_hasfullcolumnsinreferencing_check.adoc[]" as repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_check << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.indexcolumn_referencedreferencing_hasfullcolumnsinreferencing_t.adoc[]" as repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T << U >> {
  **index_guid** : (uniqueidentifier)
  - **index_column_id** : (int)
  **RowNumberInReferencing** : (bigint)
  --
}

entity "puml-link:dhw:sqldb:repo.indexcolumn_virtual_referenced_setpoint.adoc[]" as repo.IndexColumn_virtual_referenced_setpoint << V >> {
  - **index_guid** : (uniqueidentifier)
  - **index_column_id** : (int)
  --
}

entity "puml-link:dhw:sqldb:repo.indexreferencedreferencing_hasfullcolumnsinreferencing.adoc[]" as repo.IndexReferencedReferencing_HasFullColumnsInReferencing << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_columnlist.adoc[]" as repo.RepoObject_ColumnList << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_gross2.adoc[]" as repo.RepoObject_gross2 << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_sat2.adoc[]" as repo.RepoObject_sat2 << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_sat2_t.adoc[]" as repo.RepoObject_sat2_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_sqlcreatetable.adoc[]" as repo.RepoObject_SqlCreateTable << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn_gross2.adoc[]" as repo.RepoObjectColumn_gross2 << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn_missingsource_typev.adoc[]" as repo.RepoObjectColumn_MissingSource_TypeV << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_index_inheritance.adoc[]" as repo.usp_index_inheritance << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_main.adoc[]" as repo.usp_main << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_persist_indexcolumn_referencedreferencing_hasfullcolumnsinreferencing_t.adoc[]" as repo.usp_PERSIST_IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_persist_repoobject_sat2_t.adoc[]" as repo.usp_PERSIST_RepoObject_sat2_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_51_identitfier.adoc[]" as sqlparse.RepoObject_SqlModules_51_Identitfier << V >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_52_identitfier_quotename.adoc[]" as sqlparse.RepoObject_SqlModules_52_Identitfier_QuoteName << V >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_61_selectidentifier_union.adoc[]" as sqlparse.RepoObject_SqlModules_61_SelectIdentifier_Union << V >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_61_selectidentifier_union_t.adoc[]" as sqlparse.RepoObject_SqlModules_61_SelectIdentifier_Union_T << U >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_71_reference_explicitetablealias.adoc[]" as sqlparse.RepoObject_SqlModules_71_reference_ExpliciteTableAlias << V >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_72_reference_notablealias.adoc[]" as sqlparse.RepoObject_SqlModules_72_reference_NoTableAlias << V >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_79_reference_union.adoc[]" as sqlparse.RepoObject_SqlModules_79_reference_union << V >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.usp_persist_repoobject_sqlmodules_61_selectidentifier_union_t.adoc[]" as sqlparse.usp_PERSIST_RepoObject_SqlModules_61_SelectIdentifier_Union_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.usp_sqlparse.adoc[]" as sqlparse.usp_sqlparse << P >> {
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.generatoruspstep_persistence_src.adoc[]" as uspgenerator.GeneratorUspStep_Persistence_src << V >> {
  - **usp_id** : (int)
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.usp_generatorusp_insert_update_persistence.adoc[]" as uspgenerator.usp_GeneratorUsp_insert_update_persistence << P >> {
  --
}

docs.ftv_RepoObject_Reference_PlantUml_EntityRefList <.. docs.RepoObject_Plantuml
docs.ObjectRefCyclic_EntityList <.. docs.ObjectRefCyclic
docs.RepoObject_Adoc <.. docs.RepoObject_Adoc_T
docs.RepoObject_Adoc <.. docs.usp_PERSIST_RepoObject_Adoc_T
docs.REpoObject_Adoc_T <.. docs.usp_PERSIST_RepoObject_Adoc_T
docs.RepoObject_ColumnList <.. docs.usp_PERSIST_RepoObject_ColumnList_T
docs.RepoObject_ColumnList <.. docs.RepoObject_ColumnList_T
docs.RepoObject_ColumnList_T <.. docs.RepoObject_Adoc
docs.RepoObject_ColumnList_T <.. docs.RepoObject_Plantuml_Entity
docs.RepoObject_ColumnList_T <.. docs.usp_PERSIST_RepoObject_ColumnList_T
docs.RepoObject_Plantuml <.. docs.RepoObject_Plantuml_T
docs.RepoObject_Plantuml <.. docs.usp_PERSIST_RepoObject_Plantuml_T
docs.RepoObject_Plantuml_ColRefList_1_1 <.. docs.RepoObject_Plantuml
docs.RepoObject_Plantuml_Entity <.. docs.RepoObject_Plantuml_Entity_T
docs.RepoObject_Plantuml_Entity <.. docs.usp_PERSIST_RepoObject_Plantuml_Entity_T
docs.RepoObject_Plantuml_Entity_T <.. docs.RepoObject_Adoc
docs.RepoObject_Plantuml_Entity_T <.. docs.usp_PERSIST_RepoObject_Plantuml_Entity_T
docs.RepoObject_Plantuml_Entity_T <.. docs.ftv_RepoObject_Reference_PlantUml_EntityRefList
docs.RepoObject_Plantuml_Entity_T <.. docs.RepoObject_PlantUml_PumlEntityFkList
docs.RepoObject_Plantuml_Entity_T <.. docs.ObjectRefCyclic_EntityList
docs.RepoObject_Plantuml_Entity_T <.. docs.Schema_EntityList
docs.RepoObject_PlantUml_PumlEntityFkList <.. docs.RepoObject_Plantuml
docs.RepoObject_Plantuml_T <.. docs.RepoObject_Adoc
docs.RepoObject_Plantuml_T <.. docs.usp_PERSIST_RepoObject_Plantuml_T
docs.Schema_EntityList <.. docs.Schema_puml
docs.Schema_puml <.. docs.AntoraNavListPage_by_schema
docs.usp_AntoraExport_ObjectPartialsContent <.. docs.usp_AntoraExport
docs.usp_AntoraExport_ObjectPuml <.. docs.usp_AntoraExport
docs.usp_PERSIST_RepoObject_Adoc_T <.. docs.usp_AntoraExport_ObjectPartialsContent
docs.usp_PERSIST_RepoObject_ColumnList_T <.. docs.usp_AntoraExport_ObjectPartialsContent
docs.usp_PERSIST_RepoObject_Plantuml_Entity_T <.. docs.usp_AntoraExport_ObjectPuml
docs.usp_PERSIST_RepoObject_Plantuml_T <.. docs.usp_AntoraExport_ObjectPuml
property.RepoObjectProperty_Collect_source_ROGross <.. property.usp_RepoObjectProperty_collect
property.usp_RepoObject_Inheritance <.. repo.usp_main
property.usp_RepoObjectProperty_collect <.. property.usp_RepoObject_Inheritance
property.usp_RepoObjectProperty_collect <.. repo.usp_main
reference.ftv_RepoObjectColumn_ReferenceTree <.. reference.RepoObjectColumn_ReferenceTree
reference.RepoObjectColumn_reference <.. reference.usp_PERSIST_RepoObjectColumn_reference_T
reference.RepoObjectColumn_reference <.. reference.RepoObjectColumn_reference_T
reference.RepoObjectColumn_reference_SqlModules <.. reference.RepoObjectColumn_reference_union
reference.RepoObjectColumn_reference_T <.. docs.RepoObject_Plantuml_ColRefList_1_1
reference.RepoObjectColumn_reference_T <.. reference.usp_PERSIST_RepoObjectColumn_reference_T
reference.RepoObjectColumn_reference_T <.. reference.RepoObjectColumn_ReferencedReferencing
reference.RepoObjectColumn_reference_T <.. reference.RepoObjectColumn_RelationScript
reference.RepoObjectColumn_reference_T <.. repo.RepoObjectColumn_MissingSource_TypeV
reference.RepoObjectColumn_reference_T <.. repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing
reference.RepoObjectColumn_reference_union <.. reference.RepoObjectColumn_reference
reference.RepoObjectColumn_ReferencedList <.. repo.RepoObjectColumn_gross2
reference.RepoObjectColumn_ReferencedReferencing <.. reference.RepoObjectColumn_ReferencingList
reference.RepoObjectColumn_ReferencedReferencing <.. reference.ftv_RepoObjectColumn_ReferenceTree
reference.RepoObjectColumn_ReferencedReferencing <.. reference.RepoObjectColumn_ReferencedList
reference.RepoObjectColumn_ReferencedReferencing <.. reference.ftv_RepoObject_DbmlColumnRelation
reference.RepoObjectColumn_ReferenceTree <.. reference.ftv_RepoObject_ColumReferenceRepoObject
reference.RepoObjectColumn_ReferencingList <.. repo.RepoObjectColumn_gross2
reference.RepoObjectColumn_RelationScript <.. reference.ftv_RepoObject_ColumReferenceRepoObject
reference.usp_PERSIST_RepoObjectColumn_reference_T <.. repo.usp_main
repo.Index_referencing_IndexPatternColumnGuid <.. repo.IndexReferencedReferencing_HasFullColumnsInReferencing
repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing <.. repo.usp_PERSIST_IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T
repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing <.. repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T
repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T <.. repo.Index_referencing_IndexPatternColumnGuid
repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T <.. repo.IndexReferencedReferencing_HasFullColumnsInReferencing
repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T <.. repo.IndexColumn_virtual_referenced_setpoint
repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T <.. repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_check
repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T <.. repo.usp_PERSIST_IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T
repo.IndexColumn_virtual_referenced_setpoint <.. repo.check_IndexColumn_virtual_referenced_setpoint
repo.IndexColumn_virtual_referenced_setpoint <.. repo.usp_index_inheritance
repo.IndexReferencedReferencing_HasFullColumnsInReferencing <.. repo.usp_index_inheritance
repo.RepoObject_ColumnList <.. repo.RepoObject_SqlCreateTable
repo.RepoObject_ColumnList <.. repo.RepoObject_gross2
repo.RepoObject_ColumnList <.. repo.RepoObject_sat2
repo.RepoObject_gross2 <.. uspgenerator.GeneratorUspStep_Persistence_src
repo.RepoObject_sat2 <.. repo.RepoObject_sat2_T
repo.RepoObject_sat2 <.. repo.usp_PERSIST_RepoObject_sat2_T
repo.RepoObject_sat2_T <.. repo.usp_PERSIST_RepoObject_sat2_T
repo.RepoObject_sat2_T <.. docs.RepoObject_Adoc
repo.RepoObject_sat2_T <.. property.RepoObjectProperty_Collect_source_ROGross
repo.RepoObject_SqlCreateTable <.. reference.ftv_RepoObject_ColumReferenceRepoObject
repo.RepoObjectColumn_gross2 <.. docs.RepoObject_ColumnList
repo.RepoObjectColumn_gross2 <.. uspgenerator.usp_GeneratorUsp_insert_update_persistence
repo.RepoObjectColumn_gross2 <.. repo.RepoObject_ColumnList
repo.usp_index_inheritance <.. repo.usp_main
repo.usp_PERSIST_IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T <.. repo.usp_index_inheritance
repo.usp_PERSIST_RepoObject_sat2_T <.. repo.usp_main
sqlparse.RepoObject_SqlModules_51_Identitfier <.. sqlparse.RepoObject_SqlModules_52_Identitfier_QuoteName
sqlparse.RepoObject_SqlModules_52_Identitfier_QuoteName <.. sqlparse.RepoObject_SqlModules_61_SelectIdentifier_Union
sqlparse.RepoObject_SqlModules_61_SelectIdentifier_Union <.. sqlparse.RepoObject_SqlModules_61_SelectIdentifier_Union_T
sqlparse.RepoObject_SqlModules_61_SelectIdentifier_Union <.. sqlparse.usp_PERSIST_RepoObject_SqlModules_61_SelectIdentifier_Union_T
sqlparse.RepoObject_SqlModules_61_SelectIdentifier_Union_T <.. sqlparse.RepoObject_SqlModules_71_reference_ExpliciteTableAlias
sqlparse.RepoObject_SqlModules_61_SelectIdentifier_Union_T <.. sqlparse.RepoObject_SqlModules_72_reference_NoTableAlias
sqlparse.RepoObject_SqlModules_61_SelectIdentifier_Union_T <.. sqlparse.usp_PERSIST_RepoObject_SqlModules_61_SelectIdentifier_Union_T
sqlparse.RepoObject_SqlModules_71_reference_ExpliciteTableAlias <.. sqlparse.RepoObject_SqlModules_79_reference_union
sqlparse.RepoObject_SqlModules_72_reference_NoTableAlias <.. sqlparse.RepoObject_SqlModules_79_reference_union
sqlparse.RepoObject_SqlModules_79_reference_union <.. reference.RepoObjectColumn_reference_SqlModules
sqlparse.usp_PERSIST_RepoObject_SqlModules_61_SelectIdentifier_Union_T <.. sqlparse.usp_sqlparse
uspgenerator.GeneratorUspStep_Persistence_src <.. uspgenerator.usp_GeneratorUsp_insert_update_persistence
uspgenerator.usp_GeneratorUsp_insert_update_persistence <.. repo.usp_main

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_0_30_objectref[]

=== PlantUML 1 1 ColumnRef

// tag::puml_entity_1_1_colref[]
[plantuml, entity_1_1_colref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_20_statement_children.adoc[]" as sqlparse.RepoObject_SqlModules_20_statement_children << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **json_key** : (nvarchar(4000))
  child0_children : (nvarchar(max))
  child0_class : (nvarchar(500))
  child0_is_group : (bit)
  child0_is_keyword : (bit)
  child0_is_whitespace : (bit)
  child0_normalized : (nvarchar(max))
  child1_children : (nvarchar(max))
  child1_class : (nvarchar(500))
  child1_is_group : (bit)
  child1_is_keyword : (bit)
  child1_is_whitespace : (bit)
  child1_normalized : (nvarchar(max))
  child2_children : (nvarchar(max))
  child2_class : (nvarchar(500))
  child2_is_group : (bit)
  child2_is_keyword : (bit)
  child2_is_whitespace : (bit)
  child2_normalized : (nvarchar(max))
  child3_children : (nvarchar(max))
  child3_class : (nvarchar(500))
  child3_is_group : (bit)
  child3_is_keyword : (bit)
  child3_is_whitespace : (bit)
  child3_normalized : (nvarchar(max))
  child4_children : (nvarchar(max))
  child4_class : (nvarchar(500))
  child4_is_group : (bit)
  child4_is_keyword : (bit)
  child4_is_whitespace : (bit)
  child4_normalized : (nvarchar(max))
  children : (nvarchar(max))
  class : (nvarchar(500))
  is_group : (bit)
  is_keyword : (bit)
  is_whitespace : (bit)
  normalized : (nvarchar(max))
  RowNumber_per_Object : (bigint)
  SysObject_fullname : (nvarchar(261))
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_51_identitfier.adoc[]" as sqlparse.RepoObject_SqlModules_51_Identitfier << V >> {
  child0_class : (nvarchar(500))
  children : (nvarchar(max))
  class : (nvarchar(500))
  is_group : (bit)
  is_keyword : (bit)
  is_whitespace : (bit)
  - json_key : (nvarchar(4000))
  normalized : (nvarchar(max))
  - RepoObject_guid : (uniqueidentifier)
  RowNumber_per_Object : (bigint)
  source_column : (nvarchar(max))
  source_table : (nvarchar(max))
  SysObject_fullname : (nvarchar(261))
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_52_identitfier_quotename.adoc[]" as sqlparse.RepoObject_SqlModules_52_Identitfier_QuoteName << V >> {
  child0_class : (nvarchar(500))
  children : (nvarchar(max))
  class : (nvarchar(500))
  is_group : (bit)
  is_keyword : (bit)
  is_whitespace : (bit)
  - json_key : (nvarchar(4000))
  normalized : (nvarchar(max))
  - RepoObject_guid : (uniqueidentifier)
  RowNumber_per_Object : (bigint)
  source_column : (nvarchar(max))
  source_column_QuoteName : (nvarchar(max))
  source_table : (nvarchar(max))
  source_table_QuoteName : (nvarchar(max))
  SysObject_fullname : (nvarchar(261))
  --
}

sqlparse.RepoObject_SqlModules_20_statement_children <.. sqlparse.RepoObject_SqlModules_51_Identitfier
sqlparse.RepoObject_SqlModules_51_Identitfier <.. sqlparse.RepoObject_SqlModules_52_Identitfier_QuoteName
"sqlparse.RepoObject_SqlModules_20_statement_children::child0_class" <-- "sqlparse.RepoObject_SqlModules_51_Identitfier::child0_class"
"sqlparse.RepoObject_SqlModules_20_statement_children::children" <-- "sqlparse.RepoObject_SqlModules_51_Identitfier::children"
"sqlparse.RepoObject_SqlModules_20_statement_children::class" <-- "sqlparse.RepoObject_SqlModules_51_Identitfier::class"
"sqlparse.RepoObject_SqlModules_20_statement_children::is_group" <-- "sqlparse.RepoObject_SqlModules_51_Identitfier::is_group"
"sqlparse.RepoObject_SqlModules_20_statement_children::is_keyword" <-- "sqlparse.RepoObject_SqlModules_51_Identitfier::is_keyword"
"sqlparse.RepoObject_SqlModules_20_statement_children::is_whitespace" <-- "sqlparse.RepoObject_SqlModules_51_Identitfier::is_whitespace"
"sqlparse.RepoObject_SqlModules_20_statement_children::json_key" <-- "sqlparse.RepoObject_SqlModules_51_Identitfier::json_key"
"sqlparse.RepoObject_SqlModules_20_statement_children::normalized" <-- "sqlparse.RepoObject_SqlModules_51_Identitfier::normalized"
"sqlparse.RepoObject_SqlModules_20_statement_children::RepoObject_guid" <-- "sqlparse.RepoObject_SqlModules_51_Identitfier::RepoObject_guid"
"sqlparse.RepoObject_SqlModules_20_statement_children::RowNumber_per_Object" <-- "sqlparse.RepoObject_SqlModules_51_Identitfier::RowNumber_per_Object"
"sqlparse.RepoObject_SqlModules_20_statement_children::SysObject_fullname" <-- "sqlparse.RepoObject_SqlModules_51_Identitfier::SysObject_fullname"
"sqlparse.RepoObject_SqlModules_51_Identitfier::child0_class" <-- "sqlparse.RepoObject_SqlModules_52_Identitfier_QuoteName::child0_class"
"sqlparse.RepoObject_SqlModules_51_Identitfier::children" <-- "sqlparse.RepoObject_SqlModules_52_Identitfier_QuoteName::children"
"sqlparse.RepoObject_SqlModules_51_Identitfier::is_group" <-- "sqlparse.RepoObject_SqlModules_52_Identitfier_QuoteName::is_group"
"sqlparse.RepoObject_SqlModules_51_Identitfier::is_keyword" <-- "sqlparse.RepoObject_SqlModules_52_Identitfier_QuoteName::is_keyword"
"sqlparse.RepoObject_SqlModules_51_Identitfier::is_whitespace" <-- "sqlparse.RepoObject_SqlModules_52_Identitfier_QuoteName::is_whitespace"
"sqlparse.RepoObject_SqlModules_51_Identitfier::json_key" <-- "sqlparse.RepoObject_SqlModules_52_Identitfier_QuoteName::json_key"
"sqlparse.RepoObject_SqlModules_51_Identitfier::normalized" <-- "sqlparse.RepoObject_SqlModules_52_Identitfier_QuoteName::normalized"
"sqlparse.RepoObject_SqlModules_51_Identitfier::RepoObject_guid" <-- "sqlparse.RepoObject_SqlModules_52_Identitfier_QuoteName::RepoObject_guid"
"sqlparse.RepoObject_SqlModules_51_Identitfier::RowNumber_per_Object" <-- "sqlparse.RepoObject_SqlModules_52_Identitfier_QuoteName::RowNumber_per_Object"
"sqlparse.RepoObject_SqlModules_51_Identitfier::source_column" <-- "sqlparse.RepoObject_SqlModules_52_Identitfier_QuoteName::source_column"
"sqlparse.RepoObject_SqlModules_51_Identitfier::source_table" <-- "sqlparse.RepoObject_SqlModules_52_Identitfier_QuoteName::source_table"
"sqlparse.RepoObject_SqlModules_51_Identitfier::SysObject_fullname" <-- "sqlparse.RepoObject_SqlModules_52_Identitfier_QuoteName::SysObject_fullname"

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_colref[]


== sql_modules_definition

// tag::sql_modules_definition[]
[%collapsible]
=======
[source,sql,numbered,indent=0]
----


/*

--only SELECT Identifier (before FROM)
SELECT
T1.*
FROM repo.RepoObject_SqlModules_51_Identitfier T1
   INNER JOIN
   repo.RepoObject_SqlModules_39_object AS T39
   ON T39.RepoObject_guid = T1.RepoObject_guid
      AND T39.Min_RowNumber_From = T1.RowNumber_per_Object + 1


*/
CREATE View sqlparse.RepoObject_SqlModules_51_Identitfier
As
Select
    --
    T1.RepoObject_guid
  , T1.json_key
  , T1.SysObject_fullname
  , T1.RowNumber_per_Object
  , T1.class
  , T1.normalized
  , T1.is_group
  , T1.is_keyword
  , T1.is_whitespace
  --same logic: [repo].[RepoObject_SqlModules_25_IdentifierList_children_IdentifierSplit]
  --in case of an simple identifier like [T1].[aaa] get the table part (before dot) and the column part (after dot)
  , source_table  = Case
                        When T1.child1_normalized = '.'
                             And Not T1.child2_normalized Is Null
                            Then
                            T1.child0_normalized
                        When T1.child1_normalized Is Null
                            Then
                            Null
                    End
  , source_column = Case
                        When T1.child1_normalized = '.'
                             And Not T1.child2_normalized Is Null
                            Then
                            T1.child2_normalized
                        When T1.child1_normalized Is Null
                            Then
                            T1.child0_normalized
                    End
  , T1.children
  , T1.child0_class
--what happens in case of aa.bb as c or c = aa.bb?
--, [T1].[RepoObject_guid]
--, [T1].[json_key]
--, [T1].[SysObject_fullname]
--, [T1].[RowNumber_per_Object]
--, [T1].[class]
--, [T1].[is_group]
--, [T1].[is_keyword]
--, [T1].[is_whitespace]
--, [T1].[normalized]
--, [T1].[children]
--, [T1].[child0_class]
--, [T1].[child0_is_group]
--, [T1].[child0_is_keyword]
--, [T1].[child0_is_whitespace]
--, [T1].[child0_normalized]
--, [T1].[child0_children]
--, [T1].[child1_class]
--, [T1].[child1_is_group]
--, [T1].[child1_is_keyword]
--, [T1].[child1_is_whitespace]
--, [T1].[child1_normalized]
--, [T1].[child1_children]
--, [T1].[child2_class]
--, [T1].[child2_is_group]
--, [T1].[child2_is_keyword]
--, [T1].[child2_is_whitespace]
--, [T1].[child2_normalized]
--, [T1].[child2_children]
--, [T1].[child3_class]
--, [T1].[child3_is_group]
--, [T1].[child3_is_keyword]
--, [T1].[child3_is_whitespace]
--, [T1].[child3_normalized]
--, [T1].[child3_children]
--, [T1].[child4_class]
--, [T1].[child4_is_group]
--, [T1].[child4_is_keyword]
--, [T1].[child4_is_whitespace]
--, [T1].[child4_normalized]
--, [T1].[child4_children]
From
    sqlparse.RepoObject_SqlModules_20_statement_children As T1
Where
    T1.class = 'Identifier'

----
=======
// end::sql_modules_definition[]


