// tag::HeaderFullDisplayName[]
= ssas.TMSCHEMA_RELATIONSHIPS - U
// end::HeaderFullDisplayName[]

== existing_properties

// tag::existing_properties[]

:ExistsProperty--antorareferencinglist:
:ExistsProperty--is_repo_managed:
:ExistsProperty--is_ssas:
:ExistsProperty--pk_index_guid:
:ExistsProperty--pk_indexpatterncolumndatatype:
:ExistsProperty--pk_indexpatterncolumnname:
:ExistsProperty--FK:
:ExistsProperty--AntoraIndexList:
:ExistsProperty--Columns:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
E4E6A70A-8A06-EC11-8515-A81E8446D5B0
// end::RepoObject_guid[]

== RepoObject_FullDisplayName2

// tag::RepoObject_FullDisplayName2[]
ssas.TMSCHEMA_RELATIONSHIPS
// end::RepoObject_FullDisplayName2[]

== SysObject_type

// tag::SysObject_type[]
U 
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
user table
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
74483344
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2021-11-25 19:14:05
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]
[discrete]
== _


[#column-databasename]
=== databasename

[cols="d,8a,m,m,m"]
|===
|1
|*databasename*

.Default: DF_TMSCHEMA_RELATIONSHIPS_databasename
[source,sql]
----
(N'mydatabase')
----


|nvarchar(128)
|NOT NULL
|
|===

.Referencing Columns
--
* xref:ssas.tmschema_relationships_t.adoc#column-databasename[+ssas.TMSCHEMA_RELATIONSHIPS_T.databasename+]
--


[#column-id]
=== ID

[cols="d,8a,m,m,m"]
|===
|2
|*ID*
|numeric(20, 0)
|NOT NULL
|
|===

.Referencing Columns
--
* xref:ssas.tmschema_relationships_t.adoc#column-id[+ssas.TMSCHEMA_RELATIONSHIPS_T.ID+]
--


[#column-crossfilteringbehavior]
=== CrossFilteringBehavior

[cols="d,8a,m,m,m"]
|===
|
|CrossFilteringBehavior
|bigint
|NOT NULL
|
|===

.Referencing Columns
--
* xref:ssas.tmschema_relationships_t.adoc#column-crossfilteringbehavior[+ssas.TMSCHEMA_RELATIONSHIPS_T.CrossFilteringBehavior+]
--


[#column-fromcardinality]
=== FromCardinality

[cols="d,8a,m,m,m"]
|===
|
|FromCardinality
|bigint
|NOT NULL
|
|===

.Referencing Columns
--
* xref:ssas.tmschema_relationships_t.adoc#column-fromcardinality[+ssas.TMSCHEMA_RELATIONSHIPS_T.FromCardinality+]
--


[#column-fromcolumnid]
=== FromColumnID

[cols="d,8a,m,m,m"]
|===
|
|FromColumnID
|numeric(20, 0)
|NOT NULL
|
|===

.Referencing Columns
--
* xref:ssas.tmschema_relationships_t.adoc#column-fromcolumnid[+ssas.TMSCHEMA_RELATIONSHIPS_T.FromColumnID+]
--


[#column-fromtableid]
=== FromTableID

[cols="d,8a,m,m,m"]
|===
|
|FromTableID
|numeric(20, 0)
|NOT NULL
|
|===

.Referencing Columns
--
* xref:ssas.tmschema_relationships_t.adoc#column-fromtableid[+ssas.TMSCHEMA_RELATIONSHIPS_T.FromTableID+]
--


[#column-isactive]
=== IsActive

[cols="d,8a,m,m,m"]
|===
|
|IsActive
|bit
|NOT NULL
|
|===

.Referencing Columns
--
* xref:ssas.tmschema_relationships_t.adoc#column-isactive[+ssas.TMSCHEMA_RELATIONSHIPS_T.IsActive+]
--


[#column-joinondatebehavior]
=== JoinOnDateBehavior

[cols="d,8a,m,m,m"]
|===
|
|JoinOnDateBehavior
|bigint
|NOT NULL
|
|===

.Referencing Columns
--
* xref:ssas.tmschema_relationships_t.adoc#column-joinondatebehavior[+ssas.TMSCHEMA_RELATIONSHIPS_T.JoinOnDateBehavior+]
--


[#column-modelid]
=== ModelID

[cols="d,8a,m,m,m"]
|===
|
|ModelID
|numeric(20, 0)
|NOT NULL
|
|===

.Referencing Columns
--
* xref:ssas.tmschema_relationships_t.adoc#column-modelid[+ssas.TMSCHEMA_RELATIONSHIPS_T.ModelID+]
--


[#column-modifiedtime]
=== ModifiedTime

[cols="d,8a,m,m,m"]
|===
|
|ModifiedTime
|datetime
|NOT NULL
|
|===

.Referencing Columns
--
* xref:ssas.tmschema_relationships_t.adoc#column-modifiedtime[+ssas.TMSCHEMA_RELATIONSHIPS_T.ModifiedTime+]
--


[#column-name]
=== Name

[cols="d,8a,m,m,m"]
|===
|
|Name
|nvarchar(max)
|NOT NULL
|
|===

.Referencing Columns
--
* xref:ssas.tmschema_relationships_t.adoc#column-name[+ssas.TMSCHEMA_RELATIONSHIPS_T.Name+]
--


[#column-refreshedtime]
=== RefreshedTime

[cols="d,8a,m,m,m"]
|===
|
|RefreshedTime
|datetime
|NULL
|
|===

.Referencing Columns
--
* xref:ssas.tmschema_relationships_t.adoc#column-refreshedtime[+ssas.TMSCHEMA_RELATIONSHIPS_T.RefreshedTime+]
--


[#column-relationshipstorage2id]
=== RelationshipStorage2ID

[cols="d,8a,m,m,m"]
|===
|
|RelationshipStorage2ID
|numeric(20, 0)
|NULL
|
|===

.Referencing Columns
--
* xref:ssas.tmschema_relationships_t.adoc#column-relationshipstorage2id[+ssas.TMSCHEMA_RELATIONSHIPS_T.RelationshipStorage2ID+]
--


[#column-relationshipstorageid]
=== RelationshipStorageID

[cols="d,8a,m,m,m"]
|===
|
|RelationshipStorageID
|numeric(20, 0)
|NULL
|
|===

.Referencing Columns
--
* xref:ssas.tmschema_relationships_t.adoc#column-relationshipstorageid[+ssas.TMSCHEMA_RELATIONSHIPS_T.RelationshipStorageID+]
--


[#column-relyonreferentialintegrity]
=== RelyOnReferentialIntegrity

[cols="d,8a,m,m,m"]
|===
|
|RelyOnReferentialIntegrity
|bit
|NOT NULL
|
|===

.Referencing Columns
--
* xref:ssas.tmschema_relationships_t.adoc#column-relyonreferentialintegrity[+ssas.TMSCHEMA_RELATIONSHIPS_T.RelyOnReferentialIntegrity+]
--


[#column-securityfilteringbehavior]
=== SecurityFilteringBehavior

[cols="d,8a,m,m,m"]
|===
|
|SecurityFilteringBehavior
|bigint
|NOT NULL
|
|===

.Referencing Columns
--
* xref:ssas.tmschema_relationships_t.adoc#column-securityfilteringbehavior[+ssas.TMSCHEMA_RELATIONSHIPS_T.SecurityFilteringBehavior+]
--


[#column-state]
=== State

[cols="d,8a,m,m,m"]
|===
|
|State
|bigint
|NOT NULL
|
|===

.Referencing Columns
--
* xref:ssas.tmschema_relationships_t.adoc#column-state[+ssas.TMSCHEMA_RELATIONSHIPS_T.State+]
--


[#column-tocardinality]
=== ToCardinality

[cols="d,8a,m,m,m"]
|===
|
|ToCardinality
|bigint
|NOT NULL
|
|===

.Referencing Columns
--
* xref:ssas.tmschema_relationships_t.adoc#column-tocardinality[+ssas.TMSCHEMA_RELATIONSHIPS_T.ToCardinality+]
--


[#column-tocolumnid]
=== ToColumnID

[cols="d,8a,m,m,m"]
|===
|
|ToColumnID
|numeric(20, 0)
|NOT NULL
|
|===

.Referencing Columns
--
* xref:ssas.tmschema_relationships_t.adoc#column-tocolumnid[+ssas.TMSCHEMA_RELATIONSHIPS_T.ToColumnID+]
--


[#column-totableid]
=== ToTableID

[cols="d,8a,m,m,m"]
|===
|
|ToTableID
|numeric(20, 0)
|NOT NULL
|
|===

.Referencing Columns
--
* xref:ssas.tmschema_relationships_t.adoc#column-totableid[+ssas.TMSCHEMA_RELATIONSHIPS_T.ToTableID+]
--


[#column-type]
=== Type

[cols="d,8a,m,m,m"]
|===
|
|Type
|bigint
|NOT NULL
|
|===

.Referencing Columns
--
* xref:ssas.tmschema_relationships_t.adoc#column-type[+ssas.TMSCHEMA_RELATIONSHIPS_T.Type+]
--


// end::AntoraColumnDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]
|1
|*<<column-databasename>>*

.Default: DF_TMSCHEMA_RELATIONSHIPS_databasename
[source,sql]
----
(N'mydatabase')
----


|nvarchar(128)
|NOT NULL
|

|2
|*<<column-id>>*
|numeric(20, 0)
|NOT NULL
|




















// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]


|
|<<column-crossfilteringbehavior>>
|bigint
|NOT NULL
|

|
|<<column-fromcardinality>>
|bigint
|NOT NULL
|

|
|<<column-fromcolumnid>>
|numeric(20, 0)
|NOT NULL
|

|
|<<column-fromtableid>>
|numeric(20, 0)
|NOT NULL
|

|
|<<column-isactive>>
|bit
|NOT NULL
|

|
|<<column-joinondatebehavior>>
|bigint
|NOT NULL
|

|
|<<column-modelid>>
|numeric(20, 0)
|NOT NULL
|

|
|<<column-modifiedtime>>
|datetime
|NOT NULL
|

|
|<<column-name>>
|nvarchar(max)
|NOT NULL
|

|
|<<column-refreshedtime>>
|datetime
|NULL
|

|
|<<column-relationshipstorage2id>>
|numeric(20, 0)
|NULL
|

|
|<<column-relationshipstorageid>>
|numeric(20, 0)
|NULL
|

|
|<<column-relyonreferentialintegrity>>
|bit
|NOT NULL
|

|
|<<column-securityfilteringbehavior>>
|bigint
|NOT NULL
|

|
|<<column-state>>
|bigint
|NOT NULL
|

|
|<<column-tocardinality>>
|bigint
|NOT NULL
|

|
|<<column-tocolumnid>>
|numeric(20, 0)
|NOT NULL
|

|
|<<column-totableid>>
|numeric(20, 0)
|NOT NULL
|

|
|<<column-type>>
|bigint
|NOT NULL
|

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

[#index-pkunderlinetmschemaunderlinerelationships]
=== PK_TMSCHEMA_RELATIONSHIPS

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-databasename>>; nvarchar(128)
* <<column-ID>>; numeric(20, 0)
--
* PK, Unique, Real: 1, 1, 1

// end::AntoraIndexList[]

== AntoraMeasureDetails

// tag::AntoraMeasureDetails[]

// end::AntoraMeasureDetails[]

== AntoraMeasureDescriptions



== AntoraParameterList

// tag::AntoraParameterList[]

// end::AntoraParameterList[]

== AntoraXrefCulturesList

// tag::AntoraXrefCulturesList[]
* xref:dhw:sqldb:ssas.tmschema_relationships.adoc[] - 
// end::AntoraXrefCulturesList[]

== cultures_count

// tag::cultures_count[]
1
// end::cultures_count[]

== Other tags

source: property.RepoObjectProperty_cross As rop_cross


=== additional_reference_csv

// tag::additional_reference_csv[]

// end::additional_reference_csv[]


=== AdocUspSteps

// tag::adocuspsteps[]

// end::adocuspsteps[]


=== AntoraReferencedList

// tag::antorareferencedlist[]

// end::antorareferencedlist[]


=== AntoraReferencingList

// tag::antorareferencinglist[]
* xref:dhw:sqldb:ssas.tmschema_relationships_t.adoc[]
* xref:dhw:sqldb:ssas.usp_persist_tmschema_relationships_t.adoc[]
// end::antorareferencinglist[]


=== Description

// tag::description[]

// end::description[]


=== exampleUsage

// tag::exampleusage[]

// end::exampleusage[]


=== exampleUsage_2

// tag::exampleusage_2[]

// end::exampleusage_2[]


=== exampleUsage_3

// tag::exampleusage_3[]

// end::exampleusage_3[]


=== exampleUsage_4

// tag::exampleusage_4[]

// end::exampleusage_4[]


=== exampleUsage_5

// tag::exampleusage_5[]

// end::exampleusage_5[]


=== exampleWrong_Usage

// tag::examplewrong_usage[]

// end::examplewrong_usage[]


=== has_execution_plan_issue

// tag::has_execution_plan_issue[]

// end::has_execution_plan_issue[]


=== has_get_referenced_issue

// tag::has_get_referenced_issue[]

// end::has_get_referenced_issue[]


=== has_history

// tag::has_history[]

// end::has_history[]


=== has_history_columns

// tag::has_history_columns[]

// end::has_history_columns[]


=== InheritanceType

// tag::inheritancetype[]

// end::inheritancetype[]


=== is_persistence

// tag::is_persistence[]

// end::is_persistence[]


=== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]

// end::is_persistence_check_duplicate_per_pk[]


=== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]

// end::is_persistence_check_for_empty_source[]


=== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]

// end::is_persistence_delete_changed[]


=== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]

// end::is_persistence_delete_missing[]


=== is_persistence_insert

// tag::is_persistence_insert[]

// end::is_persistence_insert[]


=== is_persistence_truncate

// tag::is_persistence_truncate[]

// end::is_persistence_truncate[]


=== is_persistence_update_changed

// tag::is_persistence_update_changed[]

// end::is_persistence_update_changed[]


=== is_repo_managed

// tag::is_repo_managed[]
0
// end::is_repo_managed[]


=== is_ssas

// tag::is_ssas[]
0
// end::is_ssas[]


=== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


=== MS_Description

// tag::ms_description[]

// end::ms_description[]


=== persistence_source_RepoObject_fullname

// tag::persistence_source_repoobject_fullname[]

// end::persistence_source_repoobject_fullname[]


=== persistence_source_RepoObject_fullname2

// tag::persistence_source_repoobject_fullname2[]

// end::persistence_source_repoobject_fullname2[]


=== persistence_source_RepoObject_guid

// tag::persistence_source_repoobject_guid[]

// end::persistence_source_repoobject_guid[]


=== persistence_source_RepoObject_xref

// tag::persistence_source_repoobject_xref[]

// end::persistence_source_repoobject_xref[]


=== pk_index_guid

// tag::pk_index_guid[]
E6E6A70A-8A06-EC11-8515-A81E8446D5B0
// end::pk_index_guid[]


=== pk_IndexPatternColumnDatatype

// tag::pk_indexpatterncolumndatatype[]
nvarchar(128),numeric(20, 0)
// end::pk_indexpatterncolumndatatype[]


=== pk_IndexPatternColumnName

// tag::pk_indexpatterncolumnname[]
databasename,ID
// end::pk_indexpatterncolumnname[]


=== pk_IndexSemanticGroup

// tag::pk_indexsemanticgroup[]

// end::pk_indexsemanticgroup[]


=== ReferencedObjectList

// tag::referencedobjectlist[]

// end::referencedobjectlist[]


=== usp_persistence_RepoObject_guid

// tag::usp_persistence_repoobject_guid[]

// end::usp_persistence_repoobject_guid[]


=== UspExamples

// tag::uspexamples[]

// end::uspexamples[]


=== uspgenerator_usp_id

// tag::uspgenerator_usp_id[]

// end::uspgenerator_usp_id[]


=== UspParameters

// tag::uspparameters[]

// end::uspparameters[]

== Boolean Attributes

source: property.RepoObjectProperty WHERE property_int = 1

// tag::boolean_attributes[]


// end::boolean_attributes[]

== PlantUML diagrams

=== PlantUML Entity

// tag::puml_entity[]
[plantuml, entity-{docname}, svg, subs=macros]
....
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssas.tmschema_relationships.adoc[]" as ssas.TMSCHEMA_RELATIONSHIPS << U >> {
  - **databasename** : (nvarchar(128))
  - **ID** : (numeric(20, 0))
  - CrossFilteringBehavior : (bigint)
  - FromCardinality : (bigint)
  - FromColumnID : (numeric(20, 0))
  - FromTableID : (numeric(20, 0))
  - IsActive : (bit)
  - JoinOnDateBehavior : (bigint)
  - ModelID : (numeric(20, 0))
  - ModifiedTime : (datetime)
  - Name : (nvarchar(max))
  RefreshedTime : (datetime)
  RelationshipStorage2ID : (numeric(20, 0))
  RelationshipStorageID : (numeric(20, 0))
  - RelyOnReferentialIntegrity : (bit)
  - SecurityFilteringBehavior : (bigint)
  - State : (bigint)
  - ToCardinality : (bigint)
  - ToColumnID : (numeric(20, 0))
  - ToTableID : (numeric(20, 0))
  - Type : (bigint)
  --
}
....

// end::puml_entity[]

=== PlantUML Entity 1 1 FK

// tag::puml_entity_1_1_fk[]
[plantuml, entity_1_1_fk-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssas.tmschema_relationships.adoc[]" as ssas.TMSCHEMA_RELATIONSHIPS << U >> {
**PK_TMSCHEMA_RELATIONSHIPS**

..
databasename; nvarchar(128)
ID; numeric(20, 0)
}



footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_fk[]

=== PlantUML 1 1 ObjectRef

// tag::puml_entity_1_1_objectref[]
[plantuml, entity_1_1_objectref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssas.tmschema_relationships.adoc[]" as ssas.TMSCHEMA_RELATIONSHIPS << U >> {
  - **databasename** : (nvarchar(128))
  - **ID** : (numeric(20, 0))
  --
}

entity "puml-link:dhw:sqldb:ssas.tmschema_relationships_t.adoc[]" as ssas.TMSCHEMA_RELATIONSHIPS_T << U >> {
  - **databasename** : (nvarchar(128))
  - **ID** : (numeric(20, 0))
  --
}

entity "puml-link:dhw:sqldb:ssas.usp_persist_tmschema_relationships_t.adoc[]" as ssas.usp_PERSIST_TMSCHEMA_RELATIONSHIPS_T << P >> {
  --
}

ssas.TMSCHEMA_RELATIONSHIPS <.. ssas.TMSCHEMA_RELATIONSHIPS_T
ssas.TMSCHEMA_RELATIONSHIPS <.. ssas.usp_PERSIST_TMSCHEMA_RELATIONSHIPS_T

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_objectref[]

=== PlantUML 30 0 ObjectRef

// tag::puml_entity_30_0_objectref[]
[plantuml, entity_30_0_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssas.tmschema_relationships.adoc[]" as ssas.TMSCHEMA_RELATIONSHIPS << U >> {
  - **databasename** : (nvarchar(128))
  - **ID** : (numeric(20, 0))
  --
}



footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_30_0_objectref[]

=== PlantUML 0 30 ObjectRef

// tag::puml_entity_0_30_objectref[]
[plantuml, entity_0_30_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssas.tmschema_relationships.adoc[]" as ssas.TMSCHEMA_RELATIONSHIPS << U >> {
  - **databasename** : (nvarchar(128))
  - **ID** : (numeric(20, 0))
  --
}

entity "puml-link:dhw:sqldb:ssas.tmschema_relationships_t.adoc[]" as ssas.TMSCHEMA_RELATIONSHIPS_T << U >> {
  - **databasename** : (nvarchar(128))
  - **ID** : (numeric(20, 0))
  --
}

entity "puml-link:dhw:sqldb:ssas.usp_persist_tmschema_relationships_t.adoc[]" as ssas.usp_PERSIST_TMSCHEMA_RELATIONSHIPS_T << P >> {
  --
}

ssas.TMSCHEMA_RELATIONSHIPS <.. ssas.TMSCHEMA_RELATIONSHIPS_T
ssas.TMSCHEMA_RELATIONSHIPS <.. ssas.usp_PERSIST_TMSCHEMA_RELATIONSHIPS_T
ssas.TMSCHEMA_RELATIONSHIPS_T <.. ssas.usp_PERSIST_TMSCHEMA_RELATIONSHIPS_T

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_0_30_objectref[]

=== PlantUML 1 1 ColumnRef

// tag::puml_entity_1_1_colref[]
[plantuml, entity_1_1_colref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssas.tmschema_relationships.adoc[]" as ssas.TMSCHEMA_RELATIONSHIPS << U >> {
  - **databasename** : (nvarchar(128))
  - **ID** : (numeric(20, 0))
  - CrossFilteringBehavior : (bigint)
  - FromCardinality : (bigint)
  - FromColumnID : (numeric(20, 0))
  - FromTableID : (numeric(20, 0))
  - IsActive : (bit)
  - JoinOnDateBehavior : (bigint)
  - ModelID : (numeric(20, 0))
  - ModifiedTime : (datetime)
  - Name : (nvarchar(max))
  RefreshedTime : (datetime)
  RelationshipStorage2ID : (numeric(20, 0))
  RelationshipStorageID : (numeric(20, 0))
  - RelyOnReferentialIntegrity : (bit)
  - SecurityFilteringBehavior : (bigint)
  - State : (bigint)
  - ToCardinality : (bigint)
  - ToColumnID : (numeric(20, 0))
  - ToTableID : (numeric(20, 0))
  - Type : (bigint)
  --
}

entity "puml-link:dhw:sqldb:ssas.tmschema_relationships_t.adoc[]" as ssas.TMSCHEMA_RELATIONSHIPS_T << U >> {
  - **databasename** : (nvarchar(128))
  - **ID** : (numeric(20, 0))
  - CrossFilteringBehavior : (bigint)
  - ForeignKey_guid : (uniqueidentifier)
  - FromCardinality : (bigint)
  - FromColumnID : (numeric(20, 0))
  - FromTableID : (numeric(20, 0))
  - IsActive : (bit)
  - JoinOnDateBehavior : (bigint)
  - ModelID : (numeric(20, 0))
  - ModifiedTime : (datetime)
  - Name : (nvarchar(max))
  RefreshedTime : (datetime)
  RelationshipStorage2ID : (numeric(20, 0))
  RelationshipStorageID : (numeric(20, 0))
  - RelyOnReferentialIntegrity : (bit)
  - SecurityFilteringBehavior : (bigint)
  - State : (bigint)
  - ToCardinality : (bigint)
  - ToColumnID : (numeric(20, 0))
  - ToTableID : (numeric(20, 0))
  - Type : (bigint)
  --
}

entity "puml-link:dhw:sqldb:ssas.usp_persist_tmschema_relationships_t.adoc[]" as ssas.usp_PERSIST_TMSCHEMA_RELATIONSHIPS_T << P >> {
  --
}

ssas.TMSCHEMA_RELATIONSHIPS <.. ssas.TMSCHEMA_RELATIONSHIPS_T
ssas.TMSCHEMA_RELATIONSHIPS <.. ssas.usp_PERSIST_TMSCHEMA_RELATIONSHIPS_T
"ssas.TMSCHEMA_RELATIONSHIPS::CrossFilteringBehavior" <-- "ssas.TMSCHEMA_RELATIONSHIPS_T::CrossFilteringBehavior"
"ssas.TMSCHEMA_RELATIONSHIPS::databasename" <-- "ssas.TMSCHEMA_RELATIONSHIPS_T::databasename"
"ssas.TMSCHEMA_RELATIONSHIPS::FromCardinality" <-- "ssas.TMSCHEMA_RELATIONSHIPS_T::FromCardinality"
"ssas.TMSCHEMA_RELATIONSHIPS::FromColumnID" <-- "ssas.TMSCHEMA_RELATIONSHIPS_T::FromColumnID"
"ssas.TMSCHEMA_RELATIONSHIPS::FromTableID" <-- "ssas.TMSCHEMA_RELATIONSHIPS_T::FromTableID"
"ssas.TMSCHEMA_RELATIONSHIPS::ID" <-- "ssas.TMSCHEMA_RELATIONSHIPS_T::ID"
"ssas.TMSCHEMA_RELATIONSHIPS::IsActive" <-- "ssas.TMSCHEMA_RELATIONSHIPS_T::IsActive"
"ssas.TMSCHEMA_RELATIONSHIPS::JoinOnDateBehavior" <-- "ssas.TMSCHEMA_RELATIONSHIPS_T::JoinOnDateBehavior"
"ssas.TMSCHEMA_RELATIONSHIPS::ModelID" <-- "ssas.TMSCHEMA_RELATIONSHIPS_T::ModelID"
"ssas.TMSCHEMA_RELATIONSHIPS::ModifiedTime" <-- "ssas.TMSCHEMA_RELATIONSHIPS_T::ModifiedTime"
"ssas.TMSCHEMA_RELATIONSHIPS::Name" <-- "ssas.TMSCHEMA_RELATIONSHIPS_T::Name"
"ssas.TMSCHEMA_RELATIONSHIPS::RefreshedTime" <-- "ssas.TMSCHEMA_RELATIONSHIPS_T::RefreshedTime"
"ssas.TMSCHEMA_RELATIONSHIPS::RelationshipStorage2ID" <-- "ssas.TMSCHEMA_RELATIONSHIPS_T::RelationshipStorage2ID"
"ssas.TMSCHEMA_RELATIONSHIPS::RelationshipStorageID" <-- "ssas.TMSCHEMA_RELATIONSHIPS_T::RelationshipStorageID"
"ssas.TMSCHEMA_RELATIONSHIPS::RelyOnReferentialIntegrity" <-- "ssas.TMSCHEMA_RELATIONSHIPS_T::RelyOnReferentialIntegrity"
"ssas.TMSCHEMA_RELATIONSHIPS::SecurityFilteringBehavior" <-- "ssas.TMSCHEMA_RELATIONSHIPS_T::SecurityFilteringBehavior"
"ssas.TMSCHEMA_RELATIONSHIPS::State" <-- "ssas.TMSCHEMA_RELATIONSHIPS_T::State"
"ssas.TMSCHEMA_RELATIONSHIPS::ToCardinality" <-- "ssas.TMSCHEMA_RELATIONSHIPS_T::ToCardinality"
"ssas.TMSCHEMA_RELATIONSHIPS::ToColumnID" <-- "ssas.TMSCHEMA_RELATIONSHIPS_T::ToColumnID"
"ssas.TMSCHEMA_RELATIONSHIPS::ToTableID" <-- "ssas.TMSCHEMA_RELATIONSHIPS_T::ToTableID"
"ssas.TMSCHEMA_RELATIONSHIPS::Type" <-- "ssas.TMSCHEMA_RELATIONSHIPS_T::Type"

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_colref[]


== sql_modules_definition

// tag::sql_modules_definition[]
[%collapsible]
=======
[source,sql,numbered,indent=0]
----

----
=======
// end::sql_modules_definition[]


