// tag::HeaderFullDisplayName[]
= ssas.model_json_3122_tables_measures_expressions_multiline - V
// end::HeaderFullDisplayName[]

== existing_properties

// tag::existing_properties[]

:ExistsProperty--antorareferencedlist:
:ExistsProperty--antorareferencinglist:
:ExistsProperty--is_repo_managed:
:ExistsProperty--is_ssas:
:ExistsProperty--referencedobjectlist:
:ExistsProperty--sql_modules_definition:
:ExistsProperty--FK:
:ExistsProperty--AntoraIndexList:
:ExistsProperty--Columns:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
E2F27B65-9D0F-EC11-8518-A81E8446D5B0
// end::RepoObject_guid[]

== RepoObject_FullDisplayName2

// tag::RepoObject_FullDisplayName2[]
ssas.model_json_3122_tables_measures_expressions_multiline
// end::RepoObject_FullDisplayName2[]

== SysObject_type

// tag::SysObject_type[]
V 
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
view
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
947534459
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2021-11-24 17:34:41
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]
[discrete]
== _


[#column-databasename]
=== databasename

[cols="d,8a,m,m,m"]
|===
|
|databasename
|nvarchar(128)
|NOT NULL
|
|===

.Referenced Columns
--
* xref:ssas.model_json_312_tables_measures_t.adoc#column-databasename[+ssas.model_json_312_tables_measures_T.databasename+]
--

.Referencing Columns
--
* xref:ssas.model_json_31221_tables_measures_expressions_stragg.adoc#column-databasename[+ssas.model_json_31221_tables_measures_expressions_StrAgg.databasename+]
--


[#column-key]
=== Key

[cols="d,8a,m,m,m"]
|===
|
|Key
|nvarchar(4000)
|NOT NULL
|
|===


[#column-measureunderlineguid]
=== Measure_guid

[cols="d,8a,m,m,m"]
|===
|
|Measure_guid
|uniqueidentifier
|NOT NULL
|
|===

.Referenced Columns
--
* xref:ssas.model_json_312_tables_measures_t.adoc#column-measureunderlineguid[+ssas.model_json_312_tables_measures_T.Measure_guid+]
--

.Referencing Columns
--
* xref:ssas.model_json_31221_tables_measures_expressions_stragg.adoc#column-measureunderlineguid[+ssas.model_json_31221_tables_measures_expressions_StrAgg.Measure_guid+]
--


[#column-repoobjectunderlineguid]
=== RepoObject_guid

[cols="d,8a,m,m,m"]
|===
|
|RepoObject_guid
|uniqueidentifier
|NOT NULL
|
|===

.Referenced Columns
--
* xref:ssas.model_json_312_tables_measures_t.adoc#column-repoobjectunderlineguid[+ssas.model_json_312_tables_measures_T.RepoObject_guid+]
--

.Referencing Columns
--
* xref:ssas.model_json_31221_tables_measures_expressions_stragg.adoc#column-repoobjectunderlineguid[+ssas.model_json_31221_tables_measures_expressions_StrAgg.RepoObject_guid+]
--


[#column-tablesunderlinemeasuresunderlinename]
=== tables_measures_name

[cols="d,8a,m,m,m"]
|===
|
|tables_measures_name
|nvarchar(500)
|NOT NULL
|
|===

.Referenced Columns
--
* xref:ssas.model_json_312_tables_measures_t.adoc#column-tablesunderlinemeasuresunderlinename[+ssas.model_json_312_tables_measures_T.tables_measures_name+]
--

.Referencing Columns
--
* xref:ssas.model_json_31221_tables_measures_expressions_stragg.adoc#column-tablesunderlinemeasuresunderlinename[+ssas.model_json_31221_tables_measures_expressions_StrAgg.tables_measures_name+]
--


[#column-tablesunderlinename]
=== tables_name

[cols="d,8a,m,m,m"]
|===
|
|tables_name
|nvarchar(128)
|NOT NULL
|
|===

.Referenced Columns
--
* xref:ssas.model_json_312_tables_measures_t.adoc#column-tablesunderlinename[+ssas.model_json_312_tables_measures_T.tables_name+]
--

.Referencing Columns
--
* xref:ssas.model_json_31221_tables_measures_expressions_stragg.adoc#column-tablesunderlinename[+ssas.model_json_31221_tables_measures_expressions_StrAgg.tables_name+]
--


[#column-type]
=== Type

[cols="d,8a,m,m,m"]
|===
|
|Type
|tinyint
|NOT NULL
|
|===


[#column-value]
=== Value

[cols="d,8a,m,m,m"]
|===
|
|Value
|nvarchar(max)
|NULL
|
|===


// end::AntoraColumnDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]








// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]
|
|<<column-databasename>>
|nvarchar(128)
|NOT NULL
|

|
|<<column-key>>
|nvarchar(4000)
|NOT NULL
|

|
|<<column-measureunderlineguid>>
|uniqueidentifier
|NOT NULL
|

|
|<<column-repoobjectunderlineguid>>
|uniqueidentifier
|NOT NULL
|

|
|<<column-tablesunderlinemeasuresunderlinename>>
|nvarchar(500)
|NOT NULL
|

|
|<<column-tablesunderlinename>>
|nvarchar(128)
|NOT NULL
|

|
|<<column-type>>
|tinyint
|NOT NULL
|

|
|<<column-value>>
|nvarchar(max)
|NULL
|

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

[#index-idxunderlinemodelunderlinejsonunderline3122underlinetablesunderlinemeasuresunderlineexpressionsunderlinemultilineunderlineunderline1]
=== idx_model_json_3122_tables_measures_expressions_multiline++__++1

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-Measure_guid>>; uniqueidentifier
--
* PK, Unique, Real: 0, 0, 0


[#index-idxunderlinemodelunderlinejsonunderline3122underlinetablesunderlinemeasuresunderlineexpressionsunderlinemultilineunderlineunderline2]
=== idx_model_json_3122_tables_measures_expressions_multiline++__++2

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#ssasunderlinetableunderlinemeasure[ssas_table_measure]
+
--
* <<column-databasename>>; nvarchar(128)
* <<column-tables_name>>; nvarchar(128)
* <<column-tables_measures_name>>; nvarchar(500)
--
* PK, Unique, Real: 0, 0, 0


[#index-idxunderlinemodelunderlinejsonunderline3122underlinetablesunderlinemeasuresunderlineexpressionsunderlinemultilineunderlineunderline3]
=== idx_model_json_3122_tables_measures_expressions_multiline++__++3

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-databasename>>; nvarchar(128)
* <<column-tables_name>>; nvarchar(128)
--
* PK, Unique, Real: 0, 0, 0


[#index-idxunderlinemodelunderlinejsonunderline3122underlinetablesunderlinemeasuresunderlineexpressionsunderlinemultilineunderlineunderline4]
=== idx_model_json_3122_tables_measures_expressions_multiline++__++4

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-databasename>>; nvarchar(128)
--
* PK, Unique, Real: 0, 0, 0

// end::AntoraIndexList[]

== AntoraMeasureDetails

// tag::AntoraMeasureDetails[]

// end::AntoraMeasureDetails[]

== AntoraMeasureDescriptions



== AntoraParameterList

// tag::AntoraParameterList[]

// end::AntoraParameterList[]

== AntoraXrefCulturesList

// tag::AntoraXrefCulturesList[]
* xref:dhw:sqldb:ssas.model_json_3122_tables_measures_expressions_multiline.adoc[] - 
// end::AntoraXrefCulturesList[]

== cultures_count

// tag::cultures_count[]
1
// end::cultures_count[]

== Other tags

source: property.RepoObjectProperty_cross As rop_cross


=== additional_reference_csv

// tag::additional_reference_csv[]

// end::additional_reference_csv[]


=== AdocUspSteps

// tag::adocuspsteps[]

// end::adocuspsteps[]


=== AntoraReferencedList

// tag::antorareferencedlist[]
* xref:dhw:sqldb:ssas.model_json_312_tables_measures_t.adoc[]
// end::antorareferencedlist[]


=== AntoraReferencingList

// tag::antorareferencinglist[]
* xref:dhw:sqldb:ssas.model_json_31221_tables_measures_expressions_stragg.adoc[]
// end::antorareferencinglist[]


=== Description

// tag::description[]

// end::description[]


=== exampleUsage

// tag::exampleusage[]

// end::exampleusage[]


=== exampleUsage_2

// tag::exampleusage_2[]

// end::exampleusage_2[]


=== exampleUsage_3

// tag::exampleusage_3[]

// end::exampleusage_3[]


=== exampleUsage_4

// tag::exampleusage_4[]

// end::exampleusage_4[]


=== exampleUsage_5

// tag::exampleusage_5[]

// end::exampleusage_5[]


=== exampleWrong_Usage

// tag::examplewrong_usage[]

// end::examplewrong_usage[]


=== has_execution_plan_issue

// tag::has_execution_plan_issue[]

// end::has_execution_plan_issue[]


=== has_get_referenced_issue

// tag::has_get_referenced_issue[]

// end::has_get_referenced_issue[]


=== has_history

// tag::has_history[]

// end::has_history[]


=== has_history_columns

// tag::has_history_columns[]

// end::has_history_columns[]


=== InheritanceType

// tag::inheritancetype[]

// end::inheritancetype[]


=== is_persistence

// tag::is_persistence[]

// end::is_persistence[]


=== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]

// end::is_persistence_check_duplicate_per_pk[]


=== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]

// end::is_persistence_check_for_empty_source[]


=== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]

// end::is_persistence_delete_changed[]


=== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]

// end::is_persistence_delete_missing[]


=== is_persistence_insert

// tag::is_persistence_insert[]

// end::is_persistence_insert[]


=== is_persistence_truncate

// tag::is_persistence_truncate[]

// end::is_persistence_truncate[]


=== is_persistence_update_changed

// tag::is_persistence_update_changed[]

// end::is_persistence_update_changed[]


=== is_repo_managed

// tag::is_repo_managed[]
0
// end::is_repo_managed[]


=== is_ssas

// tag::is_ssas[]
0
// end::is_ssas[]


=== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


=== MS_Description

// tag::ms_description[]

// end::ms_description[]


=== persistence_source_RepoObject_fullname

// tag::persistence_source_repoobject_fullname[]

// end::persistence_source_repoobject_fullname[]


=== persistence_source_RepoObject_fullname2

// tag::persistence_source_repoobject_fullname2[]

// end::persistence_source_repoobject_fullname2[]


=== persistence_source_RepoObject_guid

// tag::persistence_source_repoobject_guid[]

// end::persistence_source_repoobject_guid[]


=== persistence_source_RepoObject_xref

// tag::persistence_source_repoobject_xref[]

// end::persistence_source_repoobject_xref[]


=== pk_index_guid

// tag::pk_index_guid[]

// end::pk_index_guid[]


=== pk_IndexPatternColumnDatatype

// tag::pk_indexpatterncolumndatatype[]

// end::pk_indexpatterncolumndatatype[]


=== pk_IndexPatternColumnName

// tag::pk_indexpatterncolumnname[]

// end::pk_indexpatterncolumnname[]


=== pk_IndexSemanticGroup

// tag::pk_indexsemanticgroup[]

// end::pk_indexsemanticgroup[]


=== ReferencedObjectList

// tag::referencedobjectlist[]
* [ssas].[model_json_312_tables_measures_T]
// end::referencedobjectlist[]


=== usp_persistence_RepoObject_guid

// tag::usp_persistence_repoobject_guid[]

// end::usp_persistence_repoobject_guid[]


=== UspExamples

// tag::uspexamples[]

// end::uspexamples[]


=== uspgenerator_usp_id

// tag::uspgenerator_usp_id[]

// end::uspgenerator_usp_id[]


=== UspParameters

// tag::uspparameters[]

// end::uspparameters[]

== Boolean Attributes

source: property.RepoObjectProperty WHERE property_int = 1

// tag::boolean_attributes[]


// end::boolean_attributes[]

== PlantUML diagrams

=== PlantUML Entity

// tag::puml_entity[]
[plantuml, entity-{docname}, svg, subs=macros]
....
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssas.model_json_3122_tables_measures_expressions_multiline.adoc[]" as ssas.model_json_3122_tables_measures_expressions_multiline << V >> {
  - databasename : (nvarchar(128))
  - Key : (nvarchar(4000))
  - Measure_guid : (uniqueidentifier)
  - RepoObject_guid : (uniqueidentifier)
  - tables_measures_name : (nvarchar(500))
  - tables_name : (nvarchar(128))
  - Type : (tinyint)
  Value : (nvarchar(max))
  --
}
....

// end::puml_entity[]

=== PlantUML Entity 1 1 FK

// tag::puml_entity_1_1_fk[]
[plantuml, entity_1_1_fk-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssas.model_json_3122_tables_measures_expressions_multiline.adoc[]" as ssas.model_json_3122_tables_measures_expressions_multiline << V >> {
- idx_model_json_3122_tables_measures_expressions_multiline__1

..
Measure_guid; uniqueidentifier
--
- idx_model_json_3122_tables_measures_expressions_multiline__2
"ssas_table_measure"
..
databasename; nvarchar(128)
tables_name; nvarchar(128)
tables_measures_name; nvarchar(500)
--
- idx_model_json_3122_tables_measures_expressions_multiline__3

..
databasename; nvarchar(128)
tables_name; nvarchar(128)
--
- idx_model_json_3122_tables_measures_expressions_multiline__4

..
databasename; nvarchar(128)
}



footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_fk[]

=== PlantUML 1 1 ObjectRef

// tag::puml_entity_1_1_objectref[]
[plantuml, entity_1_1_objectref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssas.model_json_312_tables_measures_t.adoc[]" as ssas.model_json_312_tables_measures_T << U >> {
  - **Measure_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_3122_tables_measures_expressions_multiline.adoc[]" as ssas.model_json_3122_tables_measures_expressions_multiline << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31221_tables_measures_expressions_stragg.adoc[]" as ssas.model_json_31221_tables_measures_expressions_StrAgg << V >> {
  --
}

ssas.model_json_312_tables_measures_T <.. ssas.model_json_3122_tables_measures_expressions_multiline
ssas.model_json_3122_tables_measures_expressions_multiline <.. ssas.model_json_31221_tables_measures_expressions_StrAgg

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_objectref[]

=== PlantUML 30 0 ObjectRef

// tag::puml_entity_30_0_objectref[]
[plantuml, entity_30_0_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssas.model_json.adoc[]" as ssas.model_json << U >> {
  - **databasename** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_10.adoc[]" as ssas.model_json_10 << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_20.adoc[]" as ssas.model_json_20 << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31_tables.adoc[]" as ssas.model_json_31_tables << V >> {
  - **databasename** : (nvarchar(128))
  **tables_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31_tables_t.adoc[]" as ssas.model_json_31_tables_T << U >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_312_tables_measures.adoc[]" as ssas.model_json_312_tables_measures << V >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  **tables_measures_name** : (nvarchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_312_tables_measures_t.adoc[]" as ssas.model_json_312_tables_measures_T << U >> {
  - **Measure_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_3122_tables_measures_expressions_multiline.adoc[]" as ssas.model_json_3122_tables_measures_expressions_multiline << V >> {
  --
}

ssas.model_json <.. ssas.model_json_10
ssas.model_json_10 <.. ssas.model_json_20
ssas.model_json_20 <.. ssas.model_json_31_tables
ssas.model_json_31_tables <.. ssas.model_json_31_tables_T
ssas.model_json_31_tables_T <.. ssas.model_json_312_tables_measures
ssas.model_json_312_tables_measures <.. ssas.model_json_312_tables_measures_T
ssas.model_json_312_tables_measures_T <.. ssas.model_json_3122_tables_measures_expressions_multiline

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_30_0_objectref[]

=== PlantUML 0 30 ObjectRef

// tag::puml_entity_0_30_objectref[]
[plantuml, entity_0_30_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:dmdocs.unit.adoc[]" as dmdocs.unit << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.antoranavlistpage_by_schema.adoc[]" as docs.AntoraNavListPage_by_schema << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ftv_repoobject_reference_plantuml_entityreflist.adoc[]" as docs.ftv_RepoObject_Reference_PlantUml_EntityRefList << IF >> {
  --
}

entity "puml-link:dhw:sqldb:docs.measure_measurepropertylist.adoc[]" as docs.Measure_MeasurePropertyList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.objectrefcyclic.adoc[]" as docs.ObjectRefCyclic << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.objectrefcyclic_entitylist.adoc[]" as docs.ObjectRefCyclic_EntityList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_adoc.adoc[]" as docs.RepoObject_Adoc << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_adoc_t.adoc[]" as docs.RepoObject_Adoc_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_measuredescriptionlist.adoc[]" as docs.RepoObject_MeasureDescriptionList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_measurelist.adoc[]" as docs.RepoObject_MeasureList << V >> {
  **RepoObject_guid** : (uniqueidentifier)
  **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml.adoc[]" as docs.RepoObject_Plantuml << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_entity.adoc[]" as docs.RepoObject_Plantuml_Entity << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_entity_t.adoc[]" as docs.RepoObject_Plantuml_Entity_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_pumlentityfklist.adoc[]" as docs.RepoObject_PlantUml_PumlEntityFkList << V >> {
  **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_t.adoc[]" as docs.RepoObject_Plantuml_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.schema_entitylist.adoc[]" as docs.Schema_EntityList << V >> {
  - **RepoObject_schema_name** : (nvarchar(128))
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.schema_puml.adoc[]" as docs.Schema_puml << V >> {
  - **RepoSchema_guid** : (uniqueidentifier)
  **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.unit_1_union.adoc[]" as docs.Unit_1_union << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.unit_2.adoc[]" as docs.Unit_2 << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.unit_3.adoc[]" as docs.Unit_3 << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport.adoc[]" as docs.usp_AntoraExport << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_objectpartialscontent.adoc[]" as docs.usp_AntoraExport_ObjectPartialsContent << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_objectpuml.adoc[]" as docs.usp_AntoraExport_ObjectPuml << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_repoobject_adoc_t.adoc[]" as docs.usp_PERSIST_RepoObject_Adoc_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_repoobject_plantuml_entity_t.adoc[]" as docs.usp_PERSIST_RepoObject_Plantuml_Entity_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_repoobject_plantuml_t.adoc[]" as docs.usp_PERSIST_RepoObject_Plantuml_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:property.usp_measureproperty_set.adoc[]" as property.usp_MeasureProperty_set << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.measure.adoc[]" as repo.Measure << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.measure_union.adoc[]" as repo.Measure_union << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_main.adoc[]" as repo.usp_main << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_sync_guid_ssas.adoc[]" as repo.usp_sync_guid_ssas << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.measure_translation.adoc[]" as ssas.Measure_translation << V >> {
  - **Measure_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  **RepoObject_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.measure_translation_displayfolder_union.adoc[]" as ssas.Measure_translation_displayfolder_union << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.measure_translation_t.adoc[]" as ssas.Measure_translation_T << U >> {
  - **Measure_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  - **RepoObject_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_3122_tables_measures_expressions_multiline.adoc[]" as ssas.model_json_3122_tables_measures_expressions_multiline << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31221_tables_measures_expressions_stragg.adoc[]" as ssas.model_json_31221_tables_measures_expressions_StrAgg << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.usp_persist_measure_translation_t.adoc[]" as ssas.usp_PERSIST_Measure_translation_T << P >> {
  --
}

docs.ftv_RepoObject_Reference_PlantUml_EntityRefList <.. docs.RepoObject_Plantuml
docs.Measure_MeasurePropertyList <.. docs.RepoObject_MeasureList
docs.ObjectRefCyclic_EntityList <.. docs.ObjectRefCyclic
docs.RepoObject_Adoc <.. docs.usp_PERSIST_RepoObject_Adoc_T
docs.RepoObject_Adoc <.. docs.RepoObject_Adoc_T
docs.REpoObject_Adoc_T <.. docs.usp_PERSIST_RepoObject_Adoc_T
docs.RepoObject_MeasureDescriptionList <.. docs.RepoObject_Adoc
docs.RepoObject_MeasureList <.. docs.RepoObject_Adoc
docs.RepoObject_MeasureList <.. docs.RepoObject_Plantuml_Entity
docs.RepoObject_Plantuml <.. docs.RepoObject_Plantuml_T
docs.RepoObject_Plantuml <.. docs.usp_PERSIST_RepoObject_Plantuml_T
docs.RepoObject_Plantuml_Entity <.. docs.usp_PERSIST_RepoObject_Plantuml_Entity_T
docs.RepoObject_Plantuml_Entity <.. docs.RepoObject_Plantuml_Entity_T
docs.RepoObject_Plantuml_Entity_T <.. docs.RepoObject_Adoc
docs.RepoObject_Plantuml_Entity_T <.. docs.usp_PERSIST_RepoObject_Plantuml_Entity_T
docs.RepoObject_Plantuml_Entity_T <.. docs.ftv_RepoObject_Reference_PlantUml_EntityRefList
docs.RepoObject_Plantuml_Entity_T <.. docs.RepoObject_PlantUml_PumlEntityFkList
docs.RepoObject_Plantuml_Entity_T <.. docs.ObjectRefCyclic_EntityList
docs.RepoObject_Plantuml_Entity_T <.. docs.Schema_EntityList
docs.RepoObject_PlantUml_PumlEntityFkList <.. docs.RepoObject_Plantuml
docs.RepoObject_Plantuml_T <.. docs.RepoObject_Adoc
docs.RepoObject_Plantuml_T <.. docs.usp_PERSIST_RepoObject_Plantuml_T
docs.Schema_EntityList <.. docs.Schema_puml
docs.Schema_puml <.. docs.AntoraNavListPage_by_schema
docs.Unit_1_union <.. docs.Unit_2
docs.Unit_2 <.. docs.Unit_3
docs.Unit_3 <.. dmdocs.unit
docs.usp_AntoraExport_ObjectPartialsContent <.. docs.usp_AntoraExport
docs.usp_AntoraExport_ObjectPuml <.. docs.usp_AntoraExport
docs.usp_PERSIST_RepoObject_Adoc_T <.. docs.usp_AntoraExport_ObjectPartialsContent
docs.usp_PERSIST_RepoObject_Plantuml_Entity_T <.. docs.usp_AntoraExport_ObjectPuml
docs.usp_PERSIST_RepoObject_Plantuml_T <.. docs.usp_AntoraExport_ObjectPuml
repo.Measure <.. property.usp_MeasureProperty_set
repo.Measure <.. docs.Measure_MeasurePropertyList
repo.Measure <.. repo.Measure_union
repo.Measure <.. docs.Unit_1_union
repo.Measure_union <.. docs.RepoObject_MeasureDescriptionList
repo.Measure_union <.. ssas.Measure_translation
repo.Measure_union <.. docs.RepoObject_MeasureList
repo.usp_sync_guid_ssas <.. repo.usp_main
ssas.Measure_translation <.. ssas.usp_PERSIST_Measure_translation_T
ssas.Measure_translation <.. ssas.Measure_translation_T
ssas.Measure_translation_displayfolder_union <.. docs.RepoObject_MeasureList
ssas.Measure_translation_T <.. ssas.usp_PERSIST_Measure_translation_T
ssas.Measure_translation_T <.. ssas.Measure_translation_displayfolder_union
ssas.Measure_translation_T <.. docs.RepoObject_MeasureDescriptionList
ssas.model_json_3122_tables_measures_expressions_multiline <.. ssas.model_json_31221_tables_measures_expressions_StrAgg
ssas.model_json_31221_tables_measures_expressions_StrAgg <.. repo.Measure
ssas.usp_PERSIST_Measure_translation_T <.. repo.usp_sync_guid_ssas

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_0_30_objectref[]

=== PlantUML 1 1 ColumnRef

// tag::puml_entity_1_1_colref[]
[plantuml, entity_1_1_colref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssas.model_json_312_tables_measures_t.adoc[]" as ssas.model_json_312_tables_measures_T << U >> {
  - **Measure_guid** : (uniqueidentifier)
  - databasename : (nvarchar(128))
  - RepoObject_guid : (uniqueidentifier)
  tables_measures_description : (nvarchar(max))
  tables_measures_description_ja : (nvarchar(max))
  tables_measures_displayFolder : (nvarchar(500))
  tables_measures_expression : (nvarchar(max))
  tables_measures_expression_ja : (nvarchar(max))
  tables_measures_formatString : (nvarchar(500))
  tables_measures_isHidden : (bit)
  - tables_measures_name : (nvarchar(500))
  - tables_name : (nvarchar(128))
  # Measure_fullname : (nvarchar(517))
  # Measure_fullname2 : (nvarchar(638))
  # RepoObject_fullname2 : (nvarchar(257))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_3122_tables_measures_expressions_multiline.adoc[]" as ssas.model_json_3122_tables_measures_expressions_multiline << V >> {
  - databasename : (nvarchar(128))
  - Key : (nvarchar(4000))
  - Measure_guid : (uniqueidentifier)
  - RepoObject_guid : (uniqueidentifier)
  - tables_measures_name : (nvarchar(500))
  - tables_name : (nvarchar(128))
  - Type : (tinyint)
  Value : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31221_tables_measures_expressions_stragg.adoc[]" as ssas.model_json_31221_tables_measures_expressions_StrAgg << V >> {
  - databasename : (nvarchar(128))
  expressions_StrAgg : (nvarchar(max))
  - Measure_guid : (uniqueidentifier)
  - RepoObject_guid : (uniqueidentifier)
  - tables_measures_name : (nvarchar(500))
  - tables_name : (nvarchar(128))
  --
}

ssas.model_json_312_tables_measures_T <.. ssas.model_json_3122_tables_measures_expressions_multiline
ssas.model_json_3122_tables_measures_expressions_multiline <.. ssas.model_json_31221_tables_measures_expressions_StrAgg
"ssas.model_json_312_tables_measures_T::databasename" <-- "ssas.model_json_3122_tables_measures_expressions_multiline::databasename"
"ssas.model_json_312_tables_measures_T::Measure_guid" <-- "ssas.model_json_3122_tables_measures_expressions_multiline::Measure_guid"
"ssas.model_json_312_tables_measures_T::RepoObject_guid" <-- "ssas.model_json_3122_tables_measures_expressions_multiline::RepoObject_guid"
"ssas.model_json_312_tables_measures_T::tables_measures_name" <-- "ssas.model_json_3122_tables_measures_expressions_multiline::tables_measures_name"
"ssas.model_json_312_tables_measures_T::tables_name" <-- "ssas.model_json_3122_tables_measures_expressions_multiline::tables_name"
"ssas.model_json_3122_tables_measures_expressions_multiline::databasename" <-- "ssas.model_json_31221_tables_measures_expressions_StrAgg::databasename"
"ssas.model_json_3122_tables_measures_expressions_multiline::Measure_guid" <-- "ssas.model_json_31221_tables_measures_expressions_StrAgg::Measure_guid"
"ssas.model_json_3122_tables_measures_expressions_multiline::RepoObject_guid" <-- "ssas.model_json_31221_tables_measures_expressions_StrAgg::RepoObject_guid"
"ssas.model_json_3122_tables_measures_expressions_multiline::tables_measures_name" <-- "ssas.model_json_31221_tables_measures_expressions_StrAgg::tables_measures_name"
"ssas.model_json_3122_tables_measures_expressions_multiline::tables_name" <-- "ssas.model_json_31221_tables_measures_expressions_StrAgg::tables_name"

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_colref[]


== sql_modules_definition

// tag::sql_modules_definition[]
[%collapsible]
=======
[source,sql,numbered,indent=0]
----

/*
Select
    Distinct
    j2.[Key]
  , j2.[value]
  , j2.Type
From
    ssas.[model_json_312_tables_measures_T] As T1
    Cross Apply OpenJson ( T1.tables_measures_expression_ja )
                --As j1
                --Cross Apply OpenJson ( j1.Value )
                                           As j2
order by
    j2.[Key]
Go
*/

create View ssas.model_json_3122_tables_measures_expressions_multiline
As
Select
    T1.databasename
  , T1.tables_name
  , T1.tables_measures_name
  , T1.RepoObject_guid
  , T1.Measure_guid
  , j2.[Key]
  , j2.Value
  , j2.Type
From
    ssas.model_json_312_tables_measures_T As T1
    Cross Apply OpenJson ( T1.tables_measures_expression_ja )
                --As j1
                --Cross Apply OpenJson ( j1.Value )
                                          As j2

----
=======
// end::sql_modules_definition[]


