// tag::HeaderFullDisplayName[]
= ssas.model_json_3132_tables_partitions_PosFrom - V
// end::HeaderFullDisplayName[]

== existing_properties

// tag::existing_properties[]

:ExistsProperty--antorareferencedlist:
:ExistsProperty--antorareferencinglist:
:ExistsProperty--is_repo_managed:
:ExistsProperty--is_ssas:
:ExistsProperty--referencedobjectlist:
:ExistsProperty--sql_modules_definition:
:ExistsProperty--FK:
:ExistsProperty--AntoraIndexList:
:ExistsProperty--Columns:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
B508A66B-7A20-EC11-8524-A81E8446D5B0
// end::RepoObject_guid[]

== RepoObject_FullDisplayName2

// tag::RepoObject_FullDisplayName2[]
ssas.model_json_3132_tables_partitions_PosFrom
// end::RepoObject_FullDisplayName2[]

== SysObject_type

// tag::SysObject_type[]
V 
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
view
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
361104377
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2021-09-28 17:42:24
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]
[discrete]
== _


[#column-databasename]
=== databasename

[cols="d,8a,m,m,m"]
|===
|
|databasename
|nvarchar(128)
|NOT NULL
|
|===

.Referenced Columns
--
* xref:ssas.model_json_313_tables_partitions.adoc#column-databasename[+ssas.model_json_313_tables_partitions.databasename+]
--

.Referencing Columns
--
* xref:ssas.model_json_31321_tables_partitions_stringfrom.adoc#column-databasename[+ssas.model_json_31321_tables_partitions_StringFrom.databasename+]
--


[#column-posfrom]
=== PosFrom

[cols="d,8a,m,m,m"]
|===
|
|PosFrom
|bigint
|NULL
|
|===

.Referencing Columns
--
* xref:ssas.model_json_31321_tables_partitions_stringfrom.adoc#column-posfrom[+ssas.model_json_31321_tables_partitions_StringFrom.PosFrom+]
--


[#column-posfromdoublequota]
=== PosFromDoublequota

[cols="d,8a,m,m,m"]
|===
|
|PosFromDoublequota
|bigint
|NULL
|
|===

.Referencing Columns
--
* xref:ssas.model_json_31321_tables_partitions_stringfrom.adoc#column-posfromdoublequota[+ssas.model_json_31321_tables_partitions_StringFrom.PosFromDoublequota+]
--


[#column-posfromwhere]
=== PosFromWhere

[cols="d,8a,m,m,m"]
|===
|
|PosFromWhere
|bigint
|NULL
|
|===

.Referencing Columns
--
* xref:ssas.model_json_31321_tables_partitions_stringfrom.adoc#column-posfromwhere[+ssas.model_json_31321_tables_partitions_StringFrom.PosFromWhere+]
--


[#column-repoobjectunderlineguid]
=== RepoObject_guid

[cols="d,8a,m,m,m"]
|===
|
|RepoObject_guid
|uniqueidentifier
|NOT NULL
|
|===

.Referenced Columns
--
* xref:ssas.model_json_313_tables_partitions.adoc#column-repoobjectunderlineguid[+ssas.model_json_313_tables_partitions.RepoObject_guid+]
--

.Referencing Columns
--
* xref:ssas.model_json_31321_tables_partitions_stringfrom.adoc#column-repoobjectunderlineguid[+ssas.model_json_31321_tables_partitions_StringFrom.RepoObject_guid+]
--


[#column-tablesunderlinename]
=== tables_name

[cols="d,8a,m,m,m"]
|===
|
|tables_name
|nvarchar(128)
|NOT NULL
|
|===

.Referenced Columns
--
* xref:ssas.model_json_313_tables_partitions.adoc#column-tablesunderlinename[+ssas.model_json_313_tables_partitions.tables_name+]
--

.Referencing Columns
--
* xref:ssas.model_json_31321_tables_partitions_stringfrom.adoc#column-tablesunderlinename[+ssas.model_json_31321_tables_partitions_StringFrom.tables_name+]
--


[#column-tablesunderlinepartitionsunderlineannotationsunderlineja]
=== tables_partitions_annotations_ja

[cols="d,8a,m,m,m"]
|===
|
|tables_partitions_annotations_ja
|nvarchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:ssas.model_json_313_tables_partitions.adoc#column-tablesunderlinepartitionsunderlineannotationsunderlineja[+ssas.model_json_313_tables_partitions.tables_partitions_annotations_ja+]
--

.Referencing Columns
--
* xref:ssas.model_json_31321_tables_partitions_stringfrom.adoc#column-tablesunderlinepartitionsunderlineannotationsunderlineja[+ssas.model_json_31321_tables_partitions_StringFrom.tables_partitions_annotations_ja+]
--


[#column-tablesunderlinepartitionsunderlinedataview]
=== tables_partitions_dataView

[cols="d,8a,m,m,m"]
|===
|
|tables_partitions_dataView
|nvarchar(500)
|NULL
|
|===

.Referenced Columns
--
* xref:ssas.model_json_313_tables_partitions.adoc#column-tablesunderlinepartitionsunderlinedataview[+ssas.model_json_313_tables_partitions.tables_partitions_dataView+]
--

.Referencing Columns
--
* xref:ssas.model_json_31321_tables_partitions_stringfrom.adoc#column-tablesunderlinepartitionsunderlinedataview[+ssas.model_json_31321_tables_partitions_StringFrom.tables_partitions_dataView+]
--


[#column-tablesunderlinepartitionsunderlinemode]
=== tables_partitions_mode

[cols="d,8a,m,m,m"]
|===
|
|tables_partitions_mode
|nvarchar(500)
|NULL
|
|===

.Referenced Columns
--
* xref:ssas.model_json_313_tables_partitions.adoc#column-tablesunderlinepartitionsunderlinemode[+ssas.model_json_313_tables_partitions.tables_partitions_mode+]
--

.Referencing Columns
--
* xref:ssas.model_json_31321_tables_partitions_stringfrom.adoc#column-tablesunderlinepartitionsunderlinemode[+ssas.model_json_31321_tables_partitions_StringFrom.tables_partitions_mode+]
--


[#column-tablesunderlinepartitionsunderlinename]
=== tables_partitions_name

[cols="d,8a,m,m,m"]
|===
|
|tables_partitions_name
|nvarchar(500)
|NULL
|
|===

.Referenced Columns
--
* xref:ssas.model_json_313_tables_partitions.adoc#column-tablesunderlinepartitionsunderlinename[+ssas.model_json_313_tables_partitions.tables_partitions_name+]
--

.Referencing Columns
--
* xref:ssas.model_json_31321_tables_partitions_stringfrom.adoc#column-tablesunderlinepartitionsunderlinename[+ssas.model_json_31321_tables_partitions_StringFrom.tables_partitions_name+]
--


[#column-tablesunderlinepartitionsunderlinesourceunderlinej]
=== tables_partitions_source_j

[cols="d,8a,m,m,m"]
|===
|
|tables_partitions_source_j
|nvarchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:ssas.model_json_313_tables_partitions.adoc#column-tablesunderlinepartitionsunderlinesourceunderlinej[+ssas.model_json_313_tables_partitions.tables_partitions_source_j+]
--

.Referencing Columns
--
* xref:ssas.model_json_31321_tables_partitions_stringfrom.adoc#column-tablesunderlinepartitionsunderlinesourceunderlinej[+ssas.model_json_31321_tables_partitions_StringFrom.tables_partitions_source_j+]
--


// end::AntoraColumnDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]











// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]
|
|<<column-databasename>>
|nvarchar(128)
|NOT NULL
|

|
|<<column-posfrom>>
|bigint
|NULL
|

|
|<<column-posfromdoublequota>>
|bigint
|NULL
|

|
|<<column-posfromwhere>>
|bigint
|NULL
|

|
|<<column-repoobjectunderlineguid>>
|uniqueidentifier
|NOT NULL
|

|
|<<column-tablesunderlinename>>
|nvarchar(128)
|NOT NULL
|

|
|<<column-tablesunderlinepartitionsunderlineannotationsunderlineja>>
|nvarchar(max)
|NULL
|

|
|<<column-tablesunderlinepartitionsunderlinedataview>>
|nvarchar(500)
|NULL
|

|
|<<column-tablesunderlinepartitionsunderlinemode>>
|nvarchar(500)
|NULL
|

|
|<<column-tablesunderlinepartitionsunderlinename>>
|nvarchar(500)
|NULL
|

|
|<<column-tablesunderlinepartitionsunderlinesourceunderlinej>>
|nvarchar(max)
|NULL
|

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

[#index-idxunderlinemodelunderlinejsonunderline3132underlinetablesunderlinepartitionsunderlineposfromunderlineunderline1]
=== idx_model_json_3132_tables_partitions_PosFrom++__++1

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-databasename>>; nvarchar(128)
* <<column-tables_name>>; nvarchar(128)
* <<column-tables_partitions_name>>; nvarchar(500)
--
* PK, Unique, Real: 0, 0, 0


[#index-idxunderlinemodelunderlinejsonunderline3132underlinetablesunderlinepartitionsunderlineposfromunderlineunderline2]
=== idx_model_json_3132_tables_partitions_PosFrom++__++2

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-databasename>>; nvarchar(128)
* <<column-tables_name>>; nvarchar(128)
--
* PK, Unique, Real: 0, 0, 0


[#index-idxunderlinemodelunderlinejsonunderline3132underlinetablesunderlinepartitionsunderlineposfromunderlineunderline3]
=== idx_model_json_3132_tables_partitions_PosFrom++__++3

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-databasename>>; nvarchar(128)
--
* PK, Unique, Real: 0, 0, 0

// end::AntoraIndexList[]

== AntoraMeasureDetails

// tag::AntoraMeasureDetails[]

// end::AntoraMeasureDetails[]

== AntoraMeasureDescriptions



== AntoraParameterList

// tag::AntoraParameterList[]

// end::AntoraParameterList[]

== AntoraXrefCulturesList

// tag::AntoraXrefCulturesList[]
* xref:dhw:sqldb:ssas.model_json_3132_tables_partitions_posfrom.adoc[] - 
// end::AntoraXrefCulturesList[]

== cultures_count

// tag::cultures_count[]
1
// end::cultures_count[]

== Other tags

source: property.RepoObjectProperty_cross As rop_cross


=== additional_reference_csv

// tag::additional_reference_csv[]

// end::additional_reference_csv[]


=== AdocUspSteps

// tag::adocuspsteps[]

// end::adocuspsteps[]


=== AntoraReferencedList

// tag::antorareferencedlist[]
* xref:dhw:sqldb:ssas.model_json_313_tables_partitions.adoc[]
// end::antorareferencedlist[]


=== AntoraReferencingList

// tag::antorareferencinglist[]
* xref:dhw:sqldb:ssas.model_json_31321_tables_partitions_stringfrom.adoc[]
// end::antorareferencinglist[]


=== Description

// tag::description[]

// end::description[]


=== exampleUsage

// tag::exampleusage[]

// end::exampleusage[]


=== exampleUsage_2

// tag::exampleusage_2[]

// end::exampleusage_2[]


=== exampleUsage_3

// tag::exampleusage_3[]

// end::exampleusage_3[]


=== exampleUsage_4

// tag::exampleusage_4[]

// end::exampleusage_4[]


=== exampleUsage_5

// tag::exampleusage_5[]

// end::exampleusage_5[]


=== exampleWrong_Usage

// tag::examplewrong_usage[]

// end::examplewrong_usage[]


=== has_execution_plan_issue

// tag::has_execution_plan_issue[]

// end::has_execution_plan_issue[]


=== has_get_referenced_issue

// tag::has_get_referenced_issue[]

// end::has_get_referenced_issue[]


=== has_history

// tag::has_history[]

// end::has_history[]


=== has_history_columns

// tag::has_history_columns[]

// end::has_history_columns[]


=== InheritanceType

// tag::inheritancetype[]

// end::inheritancetype[]


=== is_persistence

// tag::is_persistence[]

// end::is_persistence[]


=== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]

// end::is_persistence_check_duplicate_per_pk[]


=== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]

// end::is_persistence_check_for_empty_source[]


=== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]

// end::is_persistence_delete_changed[]


=== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]

// end::is_persistence_delete_missing[]


=== is_persistence_insert

// tag::is_persistence_insert[]

// end::is_persistence_insert[]


=== is_persistence_truncate

// tag::is_persistence_truncate[]

// end::is_persistence_truncate[]


=== is_persistence_update_changed

// tag::is_persistence_update_changed[]

// end::is_persistence_update_changed[]


=== is_repo_managed

// tag::is_repo_managed[]
0
// end::is_repo_managed[]


=== is_ssas

// tag::is_ssas[]
0
// end::is_ssas[]


=== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


=== MS_Description

// tag::ms_description[]

// end::ms_description[]


=== persistence_source_RepoObject_fullname

// tag::persistence_source_repoobject_fullname[]

// end::persistence_source_repoobject_fullname[]


=== persistence_source_RepoObject_fullname2

// tag::persistence_source_repoobject_fullname2[]

// end::persistence_source_repoobject_fullname2[]


=== persistence_source_RepoObject_guid

// tag::persistence_source_repoobject_guid[]

// end::persistence_source_repoobject_guid[]


=== persistence_source_RepoObject_xref

// tag::persistence_source_repoobject_xref[]

// end::persistence_source_repoobject_xref[]


=== pk_index_guid

// tag::pk_index_guid[]

// end::pk_index_guid[]


=== pk_IndexPatternColumnDatatype

// tag::pk_indexpatterncolumndatatype[]

// end::pk_indexpatterncolumndatatype[]


=== pk_IndexPatternColumnName

// tag::pk_indexpatterncolumnname[]

// end::pk_indexpatterncolumnname[]


=== pk_IndexSemanticGroup

// tag::pk_indexsemanticgroup[]

// end::pk_indexsemanticgroup[]


=== ReferencedObjectList

// tag::referencedobjectlist[]
* [ssas].[model_json_313_tables_partitions]
// end::referencedobjectlist[]


=== usp_persistence_RepoObject_guid

// tag::usp_persistence_repoobject_guid[]

// end::usp_persistence_repoobject_guid[]


=== UspExamples

// tag::uspexamples[]

// end::uspexamples[]


=== uspgenerator_usp_id

// tag::uspgenerator_usp_id[]

// end::uspgenerator_usp_id[]


=== UspParameters

// tag::uspparameters[]

// end::uspparameters[]

== Boolean Attributes

source: property.RepoObjectProperty WHERE property_int = 1

// tag::boolean_attributes[]


// end::boolean_attributes[]

== PlantUML diagrams

=== PlantUML Entity

// tag::puml_entity[]
[plantuml, entity-{docname}, svg, subs=macros]
....
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssas.model_json_3132_tables_partitions_posfrom.adoc[]" as ssas.model_json_3132_tables_partitions_PosFrom << V >> {
  - databasename : (nvarchar(128))
  PosFrom : (bigint)
  PosFromDoublequota : (bigint)
  PosFromWhere : (bigint)
  - RepoObject_guid : (uniqueidentifier)
  - tables_name : (nvarchar(128))
  tables_partitions_annotations_ja : (nvarchar(max))
  tables_partitions_dataView : (nvarchar(500))
  tables_partitions_mode : (nvarchar(500))
  tables_partitions_name : (nvarchar(500))
  tables_partitions_source_j : (nvarchar(max))
  --
}
....

// end::puml_entity[]

=== PlantUML Entity 1 1 FK

// tag::puml_entity_1_1_fk[]
[plantuml, entity_1_1_fk-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssas.model_json_3132_tables_partitions_posfrom.adoc[]" as ssas.model_json_3132_tables_partitions_PosFrom << V >> {
- idx_model_json_3132_tables_partitions_PosFrom__1

..
databasename; nvarchar(128)
tables_name; nvarchar(128)
tables_partitions_name; nvarchar(500)
--
- idx_model_json_3132_tables_partitions_PosFrom__2

..
databasename; nvarchar(128)
tables_name; nvarchar(128)
--
- idx_model_json_3132_tables_partitions_PosFrom__3

..
databasename; nvarchar(128)
}



footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_fk[]

=== PlantUML 1 1 ObjectRef

// tag::puml_entity_1_1_objectref[]
[plantuml, entity_1_1_objectref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssas.model_json_313_tables_partitions.adoc[]" as ssas.model_json_313_tables_partitions << V >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  **tables_partitions_name** : (nvarchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_3132_tables_partitions_posfrom.adoc[]" as ssas.model_json_3132_tables_partitions_PosFrom << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31321_tables_partitions_stringfrom.adoc[]" as ssas.model_json_31321_tables_partitions_StringFrom << V >> {
  --
}

ssas.model_json_313_tables_partitions <.. ssas.model_json_3132_tables_partitions_PosFrom
ssas.model_json_3132_tables_partitions_PosFrom <.. ssas.model_json_31321_tables_partitions_StringFrom

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_objectref[]

=== PlantUML 30 0 ObjectRef

// tag::puml_entity_30_0_objectref[]
[plantuml, entity_30_0_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssas.model_json.adoc[]" as ssas.model_json << U >> {
  - **databasename** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_10.adoc[]" as ssas.model_json_10 << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_20.adoc[]" as ssas.model_json_20 << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31_tables.adoc[]" as ssas.model_json_31_tables << V >> {
  - **databasename** : (nvarchar(128))
  **tables_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31_tables_t.adoc[]" as ssas.model_json_31_tables_T << U >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_313_tables_partitions.adoc[]" as ssas.model_json_313_tables_partitions << V >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  **tables_partitions_name** : (nvarchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_3132_tables_partitions_posfrom.adoc[]" as ssas.model_json_3132_tables_partitions_PosFrom << V >> {
  --
}

ssas.model_json <.. ssas.model_json_10
ssas.model_json_10 <.. ssas.model_json_20
ssas.model_json_20 <.. ssas.model_json_31_tables
ssas.model_json_31_tables <.. ssas.model_json_31_tables_T
ssas.model_json_31_tables_T <.. ssas.model_json_313_tables_partitions
ssas.model_json_313_tables_partitions <.. ssas.model_json_3132_tables_partitions_PosFrom

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_30_0_objectref[]

=== PlantUML 0 30 ObjectRef

// tag::puml_entity_0_30_objectref[]
[plantuml, entity_0_30_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssas.model_json_3132_tables_partitions_posfrom.adoc[]" as ssas.model_json_3132_tables_partitions_PosFrom << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31321_tables_partitions_stringfrom.adoc[]" as ssas.model_json_31321_tables_partitions_StringFrom << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_313211_tables_partitions_posdot.adoc[]" as ssas.model_json_313211_tables_partitions_PosDot << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_3132111_tables_partitions_part123.adoc[]" as ssas.model_json_3132111_tables_partitions_Part123 << V >> {
  --
}

ssas.model_json_3132_tables_partitions_PosFrom <.. ssas.model_json_31321_tables_partitions_StringFrom
ssas.model_json_31321_tables_partitions_StringFrom <.. ssas.model_json_313211_tables_partitions_PosDot
ssas.model_json_313211_tables_partitions_PosDot <.. ssas.model_json_3132111_tables_partitions_Part123

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_0_30_objectref[]

=== PlantUML 1 1 ColumnRef

// tag::puml_entity_1_1_colref[]
[plantuml, entity_1_1_colref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssas.model_json_313_tables_partitions.adoc[]" as ssas.model_json_313_tables_partitions << V >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  **tables_partitions_name** : (nvarchar(500))
  - RepoObject_guid : (uniqueidentifier)
  tables_partitions_annotations_ja : (nvarchar(max))
  tables_partitions_dataView : (nvarchar(500))
  tables_partitions_mode : (nvarchar(500))
  tables_partitions_source_j : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_3132_tables_partitions_posfrom.adoc[]" as ssas.model_json_3132_tables_partitions_PosFrom << V >> {
  - databasename : (nvarchar(128))
  PosFrom : (bigint)
  PosFromDoublequota : (bigint)
  PosFromWhere : (bigint)
  - RepoObject_guid : (uniqueidentifier)
  - tables_name : (nvarchar(128))
  tables_partitions_annotations_ja : (nvarchar(max))
  tables_partitions_dataView : (nvarchar(500))
  tables_partitions_mode : (nvarchar(500))
  tables_partitions_name : (nvarchar(500))
  tables_partitions_source_j : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31321_tables_partitions_stringfrom.adoc[]" as ssas.model_json_31321_tables_partitions_StringFrom << V >> {
  - databasename : (nvarchar(128))
  PosFrom : (bigint)
  PosFromDoublequota : (bigint)
  PosFromWhere : (bigint)
  - RepoObject_guid : (uniqueidentifier)
  StringFrom : (nvarchar(max))
  - tables_name : (nvarchar(128))
  tables_partitions_annotations_ja : (nvarchar(max))
  tables_partitions_dataView : (nvarchar(500))
  tables_partitions_mode : (nvarchar(500))
  tables_partitions_name : (nvarchar(500))
  tables_partitions_source_j : (nvarchar(max))
  --
}

ssas.model_json_313_tables_partitions <.. ssas.model_json_3132_tables_partitions_PosFrom
ssas.model_json_3132_tables_partitions_PosFrom <.. ssas.model_json_31321_tables_partitions_StringFrom
"ssas.model_json_313_tables_partitions::databasename" <-- "ssas.model_json_3132_tables_partitions_PosFrom::databasename"
"ssas.model_json_313_tables_partitions::RepoObject_guid" <-- "ssas.model_json_3132_tables_partitions_PosFrom::RepoObject_guid"
"ssas.model_json_313_tables_partitions::tables_name" <-- "ssas.model_json_3132_tables_partitions_PosFrom::tables_name"
"ssas.model_json_313_tables_partitions::tables_partitions_annotations_ja" <-- "ssas.model_json_3132_tables_partitions_PosFrom::tables_partitions_annotations_ja"
"ssas.model_json_313_tables_partitions::tables_partitions_dataView" <-- "ssas.model_json_3132_tables_partitions_PosFrom::tables_partitions_dataView"
"ssas.model_json_313_tables_partitions::tables_partitions_mode" <-- "ssas.model_json_3132_tables_partitions_PosFrom::tables_partitions_mode"
"ssas.model_json_313_tables_partitions::tables_partitions_name" <-- "ssas.model_json_3132_tables_partitions_PosFrom::tables_partitions_name"
"ssas.model_json_313_tables_partitions::tables_partitions_source_j" <-- "ssas.model_json_3132_tables_partitions_PosFrom::tables_partitions_source_j"
"ssas.model_json_3132_tables_partitions_PosFrom::databasename" <-- "ssas.model_json_31321_tables_partitions_StringFrom::databasename"
"ssas.model_json_3132_tables_partitions_PosFrom::PosFrom" <-- "ssas.model_json_31321_tables_partitions_StringFrom::PosFrom"
"ssas.model_json_3132_tables_partitions_PosFrom::PosFromDoublequota" <-- "ssas.model_json_31321_tables_partitions_StringFrom::PosFromDoublequota"
"ssas.model_json_3132_tables_partitions_PosFrom::PosFromWhere" <-- "ssas.model_json_31321_tables_partitions_StringFrom::PosFromWhere"
"ssas.model_json_3132_tables_partitions_PosFrom::RepoObject_guid" <-- "ssas.model_json_31321_tables_partitions_StringFrom::RepoObject_guid"
"ssas.model_json_3132_tables_partitions_PosFrom::tables_name" <-- "ssas.model_json_31321_tables_partitions_StringFrom::tables_name"
"ssas.model_json_3132_tables_partitions_PosFrom::tables_partitions_annotations_ja" <-- "ssas.model_json_31321_tables_partitions_StringFrom::tables_partitions_annotations_ja"
"ssas.model_json_3132_tables_partitions_PosFrom::tables_partitions_dataView" <-- "ssas.model_json_31321_tables_partitions_StringFrom::tables_partitions_dataView"
"ssas.model_json_3132_tables_partitions_PosFrom::tables_partitions_mode" <-- "ssas.model_json_31321_tables_partitions_StringFrom::tables_partitions_mode"
"ssas.model_json_3132_tables_partitions_PosFrom::tables_partitions_name" <-- "ssas.model_json_31321_tables_partitions_StringFrom::tables_partitions_name"
"ssas.model_json_3132_tables_partitions_PosFrom::tables_partitions_source_j" <-- "ssas.model_json_31321_tables_partitions_StringFrom::tables_partitions_source_j"

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_colref[]


== sql_modules_definition

// tag::sql_modules_definition[]
[%collapsible]
=======
[source,sql,numbered,indent=0]
----

CREATE VIEW [ssas].[model_json_3132_tables_partitions_PosFrom]
As
Select
    databasename
  , tables_name
  , RepoObject_guid
  , tables_partitions_name
  , tables_partitions_annotations_ja
  , tables_partitions_dataView
  , tables_partitions_mode
  , tables_partitions_source_j
  , PosFrom            = CharIndex ( ' from ', tables_partitions_source_j )
  , PosFromDoublequota = CharIndex (
                                       '"'
                                     , tables_partitions_source_j
                                     , CharIndex ( ' from ', tables_partitions_source_j ) + 6
                                   )
  , PosFromWhere       = CharIndex (
                                       ' where '
                                     , tables_partitions_source_j
                                     , CharIndex ( ' from ', tables_partitions_source_j ) + 6
                                   )
From
    ssas.model_json_313_tables_partitions
----
=======
// end::sql_modules_definition[]


