// tag::HeaderFullDisplayName[]
= ssas.TMSCHEMA_COLUMNS_T - U
// end::HeaderFullDisplayName[]

== existing_properties

// tag::existing_properties[]

:ExistsProperty--antorareferencedlist:
:ExistsProperty--antorareferencinglist:
:ExistsProperty--has_history:
:ExistsProperty--has_history_columns:
:ExistsProperty--inheritancetype:
:ExistsProperty--is_persistence:
:ExistsProperty--is_persistence_check_duplicate_per_pk:
:ExistsProperty--is_persistence_check_for_empty_source:
:ExistsProperty--is_persistence_delete_changed:
:ExistsProperty--is_persistence_delete_missing:
:ExistsProperty--is_persistence_insert:
:ExistsProperty--is_persistence_truncate:
:ExistsProperty--is_persistence_update_changed:
:ExistsProperty--is_repo_managed:
:ExistsProperty--is_ssas:
:ExistsProperty--persistence_source_repoobject_fullname:
:ExistsProperty--persistence_source_repoobject_fullname2:
:ExistsProperty--persistence_source_repoobject_guid:
:ExistsProperty--persistence_source_repoobject_xref:
:ExistsProperty--pk_index_guid:
:ExistsProperty--pk_indexpatterncolumndatatype:
:ExistsProperty--pk_indexpatterncolumnname:
:ExistsProperty--referencedobjectlist:
:ExistsProperty--usp_persistence_repoobject_guid:
:ExistsProperty--FK:
:ExistsProperty--AntoraIndexList:
:ExistsProperty--Columns:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
9348865D-8A06-EC11-8515-A81E8446D5B0
// end::RepoObject_guid[]

== RepoObject_FullDisplayName2

// tag::RepoObject_FullDisplayName2[]
ssas.TMSCHEMA_COLUMNS_T
// end::RepoObject_FullDisplayName2[]

== SysObject_type

// tag::SysObject_type[]
U 
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
user table
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
1527012521
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2021-11-25 19:14:03
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]
[discrete]
== _


[#column-databasename]
=== databasename

[cols="d,8a,m,m,m"]
|===
|1
|*databasename*

.Default: 
[source,sql]
----
(N'mydatabase')
----


|nvarchar(128)
|NOT NULL
|
|===

.Referenced Columns
--
* xref:ssas.tmschema_columns.adoc#column-databasename[+ssas.TMSCHEMA_COLUMNS.databasename+]
--


[#column-id]
=== ID

[cols="d,8a,m,m,m"]
|===
|2
|*ID*
|numeric(20, 0)
|NOT NULL
|
|===

.Referenced Columns
--
* xref:ssas.tmschema_columns.adoc#column-id[+ssas.TMSCHEMA_COLUMNS.ID+]
--


[#column-alignment]
=== Alignment

[cols="d,8a,m,m,m"]
|===
|
|Alignment
|bigint
|NOT NULL
|
|===

.Referenced Columns
--
* xref:ssas.tmschema_columns.adoc#column-alignment[+ssas.TMSCHEMA_COLUMNS.Alignment+]
--


[#column-attributehierarchyid]
=== AttributeHierarchyID

[cols="d,8a,m,m,m"]
|===
|
|AttributeHierarchyID
|numeric(20, 0)
|NOT NULL
|
|===

.Referenced Columns
--
* xref:ssas.tmschema_columns.adoc#column-attributehierarchyid[+ssas.TMSCHEMA_COLUMNS.AttributeHierarchyID+]
--


[#column-columnoriginid]
=== ColumnOriginID

[cols="d,8a,m,m,m"]
|===
|
|ColumnOriginID
|numeric(20, 0)
|NULL
|
|===

.Referenced Columns
--
* xref:ssas.tmschema_columns.adoc#column-columnoriginid[+ssas.TMSCHEMA_COLUMNS.ColumnOriginID+]
--


[#column-columnstorageid]
=== ColumnStorageID

[cols="d,8a,m,m,m"]
|===
|
|ColumnStorageID
|numeric(20, 0)
|NOT NULL
|
|===

.Referenced Columns
--
* xref:ssas.tmschema_columns.adoc#column-columnstorageid[+ssas.TMSCHEMA_COLUMNS.ColumnStorageID+]
--


[#column-datacategory]
=== DataCategory

[cols="d,8a,m,m,m"]
|===
|
|DataCategory
|nvarchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:ssas.tmschema_columns.adoc#column-datacategory[+ssas.TMSCHEMA_COLUMNS.DataCategory+]
--


[#column-description]
=== Description

[cols="d,8a,m,m,m"]
|===
|
|Description
|nvarchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:ssas.tmschema_columns.adoc#column-description[+ssas.TMSCHEMA_COLUMNS.Description+]
--


[#column-displayfolder]
=== DisplayFolder

[cols="d,8a,m,m,m"]
|===
|
|DisplayFolder
|nvarchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:ssas.tmschema_columns.adoc#column-displayfolder[+ssas.TMSCHEMA_COLUMNS.DisplayFolder+]
--


[#column-displayordinal]
=== DisplayOrdinal

[cols="d,8a,m,m,m"]
|===
|
|DisplayOrdinal
|int
|NOT NULL
|
|===

.Referenced Columns
--
* xref:ssas.tmschema_columns.adoc#column-displayordinal[+ssas.TMSCHEMA_COLUMNS.DisplayOrdinal+]
--


[#column-errormessage]
=== ErrorMessage

[cols="d,8a,m,m,m"]
|===
|
|ErrorMessage
|nvarchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:ssas.tmschema_columns.adoc#column-errormessage[+ssas.TMSCHEMA_COLUMNS.ErrorMessage+]
--


[#column-explicitdatatype]
=== ExplicitDataType

[cols="d,8a,m,m,m"]
|===
|
|ExplicitDataType
|bigint
|NOT NULL
|
|===

.Referenced Columns
--
* xref:ssas.tmschema_columns.adoc#column-explicitdatatype[+ssas.TMSCHEMA_COLUMNS.ExplicitDataType+]
--


[#column-explicitname]
=== ExplicitName

[cols="d,8a,m,m,m"]
|===
|
|ExplicitName
|nvarchar(max)
|NOT NULL
|
|===

.Referenced Columns
--
* xref:ssas.tmschema_columns.adoc#column-explicitname[+ssas.TMSCHEMA_COLUMNS.ExplicitName+]
--


[#column-expression]
=== Expression

[cols="d,8a,m,m,m"]
|===
|
|Expression
|nvarchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:ssas.tmschema_columns.adoc#column-expression[+ssas.TMSCHEMA_COLUMNS.Expression+]
--


[#column-formatstring]
=== FormatString

[cols="d,8a,m,m,m"]
|===
|
|FormatString
|nvarchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:ssas.tmschema_columns.adoc#column-formatstring[+ssas.TMSCHEMA_COLUMNS.FormatString+]
--


[#column-inferreddatatype]
=== InferredDataType

[cols="d,8a,m,m,m"]
|===
|
|InferredDataType
|bigint
|NOT NULL
|
|===

.Referenced Columns
--
* xref:ssas.tmschema_columns.adoc#column-inferreddatatype[+ssas.TMSCHEMA_COLUMNS.InferredDataType+]
--


[#column-inferredname]
=== InferredName

[cols="d,8a,m,m,m"]
|===
|
|InferredName
|nvarchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:ssas.tmschema_columns.adoc#column-inferredname[+ssas.TMSCHEMA_COLUMNS.InferredName+]
--


[#column-isavailableinmdx]
=== IsAvailableInMDX

[cols="d,8a,m,m,m"]
|===
|
|IsAvailableInMDX
|bit
|NOT NULL
|
|===

.Referenced Columns
--
* xref:ssas.tmschema_columns.adoc#column-isavailableinmdx[+ssas.TMSCHEMA_COLUMNS.IsAvailableInMDX+]
--


[#column-isdefaultimage]
=== IsDefaultImage

[cols="d,8a,m,m,m"]
|===
|
|IsDefaultImage
|bit
|NOT NULL
|
|===

.Referenced Columns
--
* xref:ssas.tmschema_columns.adoc#column-isdefaultimage[+ssas.TMSCHEMA_COLUMNS.IsDefaultImage+]
--


[#column-isdefaultlabel]
=== IsDefaultLabel

[cols="d,8a,m,m,m"]
|===
|
|IsDefaultLabel
|bit
|NOT NULL
|
|===

.Referenced Columns
--
* xref:ssas.tmschema_columns.adoc#column-isdefaultlabel[+ssas.TMSCHEMA_COLUMNS.IsDefaultLabel+]
--


[#column-ishidden]
=== IsHidden

[cols="d,8a,m,m,m"]
|===
|
|IsHidden
|bit
|NOT NULL
|
|===

.Referenced Columns
--
* xref:ssas.tmschema_columns.adoc#column-ishidden[+ssas.TMSCHEMA_COLUMNS.IsHidden+]
--


[#column-iskey]
=== IsKey

[cols="d,8a,m,m,m"]
|===
|
|IsKey
|bit
|NOT NULL
|
|===

.Referenced Columns
--
* xref:ssas.tmschema_columns.adoc#column-iskey[+ssas.TMSCHEMA_COLUMNS.IsKey+]
--


[#column-isnullable]
=== IsNullable

[cols="d,8a,m,m,m"]
|===
|
|IsNullable
|bit
|NOT NULL
|
|===

.Referenced Columns
--
* xref:ssas.tmschema_columns.adoc#column-isnullable[+ssas.TMSCHEMA_COLUMNS.IsNullable+]
--


[#column-isunique]
=== IsUnique

[cols="d,8a,m,m,m"]
|===
|
|IsUnique
|bit
|NOT NULL
|
|===

.Referenced Columns
--
* xref:ssas.tmschema_columns.adoc#column-isunique[+ssas.TMSCHEMA_COLUMNS.IsUnique+]
--


[#column-keepuniquerows]
=== KeepUniqueRows

[cols="d,8a,m,m,m"]
|===
|
|KeepUniqueRows
|bit
|NOT NULL
|
|===

.Referenced Columns
--
* xref:ssas.tmschema_columns.adoc#column-keepuniquerows[+ssas.TMSCHEMA_COLUMNS.KeepUniqueRows+]
--


[#column-modifiedtime]
=== ModifiedTime

[cols="d,8a,m,m,m"]
|===
|
|ModifiedTime
|datetime
|NOT NULL
|
|===

.Referenced Columns
--
* xref:ssas.tmschema_columns.adoc#column-modifiedtime[+ssas.TMSCHEMA_COLUMNS.ModifiedTime+]
--


[#column-refreshedtime]
=== RefreshedTime

[cols="d,8a,m,m,m"]
|===
|
|RefreshedTime
|nvarchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:ssas.tmschema_columns.adoc#column-refreshedtime[+ssas.TMSCHEMA_COLUMNS.RefreshedTime+]
--


[#column-repoobjectcolumnunderlineguid]
=== RepoObjectColumn_guid

[cols="d,8a,m,m,m"]
|===
|
|RepoObjectColumn_guid

.Default: DF_TMSCHEMA_COLUMNS_T_RepoObjectColumn_guid
[source,sql]
----
(newsequentialid())
----


|uniqueidentifier
|NOT NULL
|
|===


[#column-sortbycolumnid]
=== SortByColumnID

[cols="d,8a,m,m,m"]
|===
|
|SortByColumnID
|numeric(20, 0)
|NULL
|
|===

.Referenced Columns
--
* xref:ssas.tmschema_columns.adoc#column-sortbycolumnid[+ssas.TMSCHEMA_COLUMNS.SortByColumnID+]
--


[#column-sourcecolumn]
=== SourceColumn

[cols="d,8a,m,m,m"]
|===
|
|SourceColumn
|nvarchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:ssas.tmschema_columns.adoc#column-sourcecolumn[+ssas.TMSCHEMA_COLUMNS.SourceColumn+]
--


[#column-sourceprovidertype]
=== SourceProviderType

[cols="d,8a,m,m,m"]
|===
|
|SourceProviderType
|nvarchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:ssas.tmschema_columns.adoc#column-sourceprovidertype[+ssas.TMSCHEMA_COLUMNS.SourceProviderType+]
--


[#column-state]
=== State

[cols="d,8a,m,m,m"]
|===
|
|State
|bigint
|NOT NULL
|
|===

.Referenced Columns
--
* xref:ssas.tmschema_columns.adoc#column-state[+ssas.TMSCHEMA_COLUMNS.State+]
--


[#column-structuremodifiedtime]
=== StructureModifiedTime

[cols="d,8a,m,m,m"]
|===
|
|StructureModifiedTime
|datetime
|NOT NULL
|
|===

.Referenced Columns
--
* xref:ssas.tmschema_columns.adoc#column-structuremodifiedtime[+ssas.TMSCHEMA_COLUMNS.StructureModifiedTime+]
--


[#column-summarizeby]
=== SummarizeBy

[cols="d,8a,m,m,m"]
|===
|
|SummarizeBy
|bigint
|NOT NULL
|
|===

.Referenced Columns
--
* xref:ssas.tmschema_columns.adoc#column-summarizeby[+ssas.TMSCHEMA_COLUMNS.SummarizeBy+]
--


[#column-systemflags]
=== SystemFlags

[cols="d,8a,m,m,m"]
|===
|
|SystemFlags
|bigint
|NOT NULL
|
|===

.Referenced Columns
--
* xref:ssas.tmschema_columns.adoc#column-systemflags[+ssas.TMSCHEMA_COLUMNS.SystemFlags+]
--


[#column-tabledetailposition]
=== TableDetailPosition

[cols="d,8a,m,m,m"]
|===
|
|TableDetailPosition
|int
|NOT NULL
|
|===

.Referenced Columns
--
* xref:ssas.tmschema_columns.adoc#column-tabledetailposition[+ssas.TMSCHEMA_COLUMNS.TableDetailPosition+]
--


[#column-tableid]
=== TableID

[cols="d,8a,m,m,m"]
|===
|
|TableID
|numeric(20, 0)
|NOT NULL
|
|===

.Referenced Columns
--
* xref:ssas.tmschema_columns.adoc#column-tableid[+ssas.TMSCHEMA_COLUMNS.TableID+]
--


[#column-type]
=== Type

[cols="d,8a,m,m,m"]
|===
|
|Type
|bigint
|NOT NULL
|
|===

.Referenced Columns
--
* xref:ssas.tmschema_columns.adoc#column-type[+ssas.TMSCHEMA_COLUMNS.Type+]
--


// end::AntoraColumnDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]
|1
|*<<column-databasename>>*

.Default: 
[source,sql]
----
(N'mydatabase')
----


|nvarchar(128)
|NOT NULL
|

|2
|*<<column-id>>*
|numeric(20, 0)
|NOT NULL
|





































// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]


|
|<<column-alignment>>
|bigint
|NOT NULL
|

|
|<<column-attributehierarchyid>>
|numeric(20, 0)
|NOT NULL
|

|
|<<column-columnoriginid>>
|numeric(20, 0)
|NULL
|

|
|<<column-columnstorageid>>
|numeric(20, 0)
|NOT NULL
|

|
|<<column-datacategory>>
|nvarchar(max)
|NULL
|

|
|<<column-description>>
|nvarchar(max)
|NULL
|

|
|<<column-displayfolder>>
|nvarchar(max)
|NULL
|

|
|<<column-displayordinal>>
|int
|NOT NULL
|

|
|<<column-errormessage>>
|nvarchar(max)
|NULL
|

|
|<<column-explicitdatatype>>
|bigint
|NOT NULL
|

|
|<<column-explicitname>>
|nvarchar(max)
|NOT NULL
|

|
|<<column-expression>>
|nvarchar(max)
|NULL
|

|
|<<column-formatstring>>
|nvarchar(max)
|NULL
|

|
|<<column-inferreddatatype>>
|bigint
|NOT NULL
|

|
|<<column-inferredname>>
|nvarchar(max)
|NULL
|

|
|<<column-isavailableinmdx>>
|bit
|NOT NULL
|

|
|<<column-isdefaultimage>>
|bit
|NOT NULL
|

|
|<<column-isdefaultlabel>>
|bit
|NOT NULL
|

|
|<<column-ishidden>>
|bit
|NOT NULL
|

|
|<<column-iskey>>
|bit
|NOT NULL
|

|
|<<column-isnullable>>
|bit
|NOT NULL
|

|
|<<column-isunique>>
|bit
|NOT NULL
|

|
|<<column-keepuniquerows>>
|bit
|NOT NULL
|

|
|<<column-modifiedtime>>
|datetime
|NOT NULL
|

|
|<<column-refreshedtime>>
|nvarchar(max)
|NULL
|

|
|<<column-repoobjectcolumnunderlineguid>>

.Default: DF_TMSCHEMA_COLUMNS_T_RepoObjectColumn_guid
[source,sql]
----
(newsequentialid())
----


|uniqueidentifier
|NOT NULL
|

|
|<<column-sortbycolumnid>>
|numeric(20, 0)
|NULL
|

|
|<<column-sourcecolumn>>
|nvarchar(max)
|NULL
|

|
|<<column-sourceprovidertype>>
|nvarchar(max)
|NULL
|

|
|<<column-state>>
|bigint
|NOT NULL
|

|
|<<column-structuremodifiedtime>>
|datetime
|NOT NULL
|

|
|<<column-summarizeby>>
|bigint
|NOT NULL
|

|
|<<column-systemflags>>
|bigint
|NOT NULL
|

|
|<<column-tabledetailposition>>
|int
|NOT NULL
|

|
|<<column-tableid>>
|numeric(20, 0)
|NOT NULL
|

|
|<<column-type>>
|bigint
|NOT NULL
|

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

[#index-pkunderlinetmschemaunderlinecolumnsunderlinet]
=== PK_TMSCHEMA_COLUMNS_T

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-databasename>>; nvarchar(128)
* <<column-ID>>; numeric(20, 0)
--
* PK, Unique, Real: 1, 1, 1

// end::AntoraIndexList[]

== AntoraMeasureDetails

// tag::AntoraMeasureDetails[]

// end::AntoraMeasureDetails[]

== AntoraMeasureDescriptions



== AntoraParameterList

// tag::AntoraParameterList[]

// end::AntoraParameterList[]

== AntoraXrefCulturesList

// tag::AntoraXrefCulturesList[]
* xref:dhw:sqldb:ssas.tmschema_columns_t.adoc[] - 
// end::AntoraXrefCulturesList[]

== cultures_count

// tag::cultures_count[]
1
// end::cultures_count[]

== Other tags

source: property.RepoObjectProperty_cross As rop_cross


=== additional_reference_csv

// tag::additional_reference_csv[]

// end::additional_reference_csv[]


=== AdocUspSteps

// tag::adocuspsteps[]

// end::adocuspsteps[]


=== AntoraReferencedList

// tag::antorareferencedlist[]
* xref:dhw:sqldb:ssas.tmschema_columns.adoc[]
// end::antorareferencedlist[]


=== AntoraReferencingList

// tag::antorareferencinglist[]
* xref:dhw:sqldb:ssas.usp_persist_tmschema_columns_t.adoc[]
// end::antorareferencinglist[]


=== Description

// tag::description[]

// end::description[]


=== exampleUsage

// tag::exampleusage[]

// end::exampleusage[]


=== exampleUsage_2

// tag::exampleusage_2[]

// end::exampleusage_2[]


=== exampleUsage_3

// tag::exampleusage_3[]

// end::exampleusage_3[]


=== exampleUsage_4

// tag::exampleusage_4[]

// end::exampleusage_4[]


=== exampleUsage_5

// tag::exampleusage_5[]

// end::exampleusage_5[]


=== exampleWrong_Usage

// tag::examplewrong_usage[]

// end::examplewrong_usage[]


=== has_execution_plan_issue

// tag::has_execution_plan_issue[]

// end::has_execution_plan_issue[]


=== has_get_referenced_issue

// tag::has_get_referenced_issue[]

// end::has_get_referenced_issue[]


=== has_history

// tag::has_history[]
0
// end::has_history[]


=== has_history_columns

// tag::has_history_columns[]
0
// end::has_history_columns[]


=== InheritanceType

// tag::inheritancetype[]
13
// end::inheritancetype[]


=== is_persistence

// tag::is_persistence[]
1
// end::is_persistence[]


=== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]
0
// end::is_persistence_check_duplicate_per_pk[]


=== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]
0
// end::is_persistence_check_for_empty_source[]


=== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]
0
// end::is_persistence_delete_changed[]


=== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]
1
// end::is_persistence_delete_missing[]


=== is_persistence_insert

// tag::is_persistence_insert[]
1
// end::is_persistence_insert[]


=== is_persistence_truncate

// tag::is_persistence_truncate[]
0
// end::is_persistence_truncate[]


=== is_persistence_update_changed

// tag::is_persistence_update_changed[]
1
// end::is_persistence_update_changed[]


=== is_repo_managed

// tag::is_repo_managed[]
1
// end::is_repo_managed[]


=== is_ssas

// tag::is_ssas[]
0
// end::is_ssas[]


=== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


=== MS_Description

// tag::ms_description[]

// end::ms_description[]


=== persistence_source_RepoObject_fullname

// tag::persistence_source_repoobject_fullname[]
[ssas].[TMSCHEMA_COLUMNS]
// end::persistence_source_repoobject_fullname[]


=== persistence_source_RepoObject_fullname2

// tag::persistence_source_repoobject_fullname2[]
ssas.TMSCHEMA_COLUMNS
// end::persistence_source_repoobject_fullname2[]


=== persistence_source_RepoObject_guid

// tag::persistence_source_repoobject_guid[]
D1E6A70A-8A06-EC11-8515-A81E8446D5B0
// end::persistence_source_repoobject_guid[]


=== persistence_source_RepoObject_xref

// tag::persistence_source_repoobject_xref[]
xref:ssas.tmschema_columns.adoc[]
// end::persistence_source_repoobject_xref[]


=== pk_index_guid

// tag::pk_index_guid[]
0A4559F6-0807-EC11-8515-A81E8446D5B0
// end::pk_index_guid[]


=== pk_IndexPatternColumnDatatype

// tag::pk_indexpatterncolumndatatype[]
nvarchar(128),numeric(20, 0)
// end::pk_indexpatterncolumndatatype[]


=== pk_IndexPatternColumnName

// tag::pk_indexpatterncolumnname[]
databasename,ID
// end::pk_indexpatterncolumnname[]


=== pk_IndexSemanticGroup

// tag::pk_indexsemanticgroup[]

// end::pk_indexsemanticgroup[]


=== ReferencedObjectList

// tag::referencedobjectlist[]
* [ssas].[TMSCHEMA_COLUMNS]
// end::referencedobjectlist[]


=== usp_persistence_RepoObject_guid

// tag::usp_persistence_repoobject_guid[]
0B4559F6-0807-EC11-8515-A81E8446D5B0
// end::usp_persistence_repoobject_guid[]


=== UspExamples

// tag::uspexamples[]

// end::uspexamples[]


=== uspgenerator_usp_id

// tag::uspgenerator_usp_id[]

// end::uspgenerator_usp_id[]


=== UspParameters

// tag::uspparameters[]

// end::uspparameters[]

== Boolean Attributes

source: property.RepoObjectProperty WHERE property_int = 1

// tag::boolean_attributes[]

:is_persistence:
:is_persistence_delete_missing:
:is_persistence_insert:
:is_persistence_update_changed:
:is_repo_managed:

// end::boolean_attributes[]

== PlantUML diagrams

=== PlantUML Entity

// tag::puml_entity[]
[plantuml, entity-{docname}, svg, subs=macros]
....
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssas.tmschema_columns_t.adoc[]" as ssas.TMSCHEMA_COLUMNS_T << U >> {
  - **databasename** : (nvarchar(128))
  - **ID** : (numeric(20, 0))
  - Alignment : (bigint)
  - AttributeHierarchyID : (numeric(20, 0))
  ColumnOriginID : (numeric(20, 0))
  - ColumnStorageID : (numeric(20, 0))
  DataCategory : (nvarchar(max))
  Description : (nvarchar(max))
  DisplayFolder : (nvarchar(max))
  - DisplayOrdinal : (int)
  ErrorMessage : (nvarchar(max))
  - ExplicitDataType : (bigint)
  - ExplicitName : (nvarchar(max))
  Expression : (nvarchar(max))
  FormatString : (nvarchar(max))
  - InferredDataType : (bigint)
  InferredName : (nvarchar(max))
  - IsAvailableInMDX : (bit)
  - IsDefaultImage : (bit)
  - IsDefaultLabel : (bit)
  - IsHidden : (bit)
  - IsKey : (bit)
  - IsNullable : (bit)
  - IsUnique : (bit)
  - KeepUniqueRows : (bit)
  - ModifiedTime : (datetime)
  RefreshedTime : (nvarchar(max))
  - RepoObjectColumn_guid : (uniqueidentifier)
  SortByColumnID : (numeric(20, 0))
  SourceColumn : (nvarchar(max))
  SourceProviderType : (nvarchar(max))
  - State : (bigint)
  - StructureModifiedTime : (datetime)
  - SummarizeBy : (bigint)
  - SystemFlags : (bigint)
  - TableDetailPosition : (int)
  - TableID : (numeric(20, 0))
  - Type : (bigint)
  --
}
....

// end::puml_entity[]

=== PlantUML Entity 1 1 FK

// tag::puml_entity_1_1_fk[]
[plantuml, entity_1_1_fk-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssas.tmschema_columns_t.adoc[]" as ssas.TMSCHEMA_COLUMNS_T << U >> {
**PK_TMSCHEMA_COLUMNS_T**

..
databasename; nvarchar(128)
ID; numeric(20, 0)
}



footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_fk[]

=== PlantUML 1 1 ObjectRef

// tag::puml_entity_1_1_objectref[]
[plantuml, entity_1_1_objectref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssas.tmschema_columns.adoc[]" as ssas.TMSCHEMA_COLUMNS << U >> {
  - **databasename** : (nvarchar(128))
  - **ID** : (numeric(20, 0))
  --
}

entity "puml-link:dhw:sqldb:ssas.tmschema_columns_t.adoc[]" as ssas.TMSCHEMA_COLUMNS_T << U >> {
  - **databasename** : (nvarchar(128))
  - **ID** : (numeric(20, 0))
  --
}

entity "puml-link:dhw:sqldb:ssas.usp_persist_tmschema_columns_t.adoc[]" as ssas.usp_PERSIST_TMSCHEMA_COLUMNS_T << P >> {
  --
}

ssas.TMSCHEMA_COLUMNS <.. ssas.TMSCHEMA_COLUMNS_T
ssas.TMSCHEMA_COLUMNS_T <.. ssas.usp_PERSIST_TMSCHEMA_COLUMNS_T

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_objectref[]

=== PlantUML 30 0 ObjectRef

// tag::puml_entity_30_0_objectref[]
[plantuml, entity_30_0_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssas.tmschema_columns.adoc[]" as ssas.TMSCHEMA_COLUMNS << U >> {
  - **databasename** : (nvarchar(128))
  - **ID** : (numeric(20, 0))
  --
}

entity "puml-link:dhw:sqldb:ssas.tmschema_columns_t.adoc[]" as ssas.TMSCHEMA_COLUMNS_T << U >> {
  - **databasename** : (nvarchar(128))
  - **ID** : (numeric(20, 0))
  --
}

ssas.TMSCHEMA_COLUMNS <.. ssas.TMSCHEMA_COLUMNS_T

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_30_0_objectref[]

=== PlantUML 0 30 ObjectRef

// tag::puml_entity_0_30_objectref[]
[plantuml, entity_0_30_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssas.tmschema_columns_t.adoc[]" as ssas.TMSCHEMA_COLUMNS_T << U >> {
  - **databasename** : (nvarchar(128))
  - **ID** : (numeric(20, 0))
  --
}

entity "puml-link:dhw:sqldb:ssas.usp_persist_tmschema_columns_t.adoc[]" as ssas.usp_PERSIST_TMSCHEMA_COLUMNS_T << P >> {
  --
}

ssas.TMSCHEMA_COLUMNS_T <.. ssas.usp_PERSIST_TMSCHEMA_COLUMNS_T

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_0_30_objectref[]

=== PlantUML 1 1 ColumnRef

// tag::puml_entity_1_1_colref[]
[plantuml, entity_1_1_colref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssas.tmschema_columns.adoc[]" as ssas.TMSCHEMA_COLUMNS << U >> {
  - **databasename** : (nvarchar(128))
  - **ID** : (numeric(20, 0))
  - Alignment : (bigint)
  - AttributeHierarchyID : (numeric(20, 0))
  ColumnOriginID : (numeric(20, 0))
  - ColumnStorageID : (numeric(20, 0))
  DataCategory : (nvarchar(max))
  Description : (nvarchar(max))
  DisplayFolder : (nvarchar(max))
  - DisplayOrdinal : (int)
  ErrorMessage : (nvarchar(max))
  - ExplicitDataType : (bigint)
  - ExplicitName : (nvarchar(max))
  Expression : (nvarchar(max))
  FormatString : (nvarchar(max))
  - InferredDataType : (bigint)
  InferredName : (nvarchar(max))
  - IsAvailableInMDX : (bit)
  - IsDefaultImage : (bit)
  - IsDefaultLabel : (bit)
  - IsHidden : (bit)
  - IsKey : (bit)
  - IsNullable : (bit)
  - IsUnique : (bit)
  - KeepUniqueRows : (bit)
  - ModifiedTime : (datetime)
  RefreshedTime : (nvarchar(max))
  SortByColumnID : (numeric(20, 0))
  SourceColumn : (nvarchar(max))
  SourceProviderType : (nvarchar(max))
  - State : (bigint)
  - StructureModifiedTime : (datetime)
  - SummarizeBy : (bigint)
  - SystemFlags : (bigint)
  - TableDetailPosition : (int)
  - TableID : (numeric(20, 0))
  - Type : (bigint)
  --
}

entity "puml-link:dhw:sqldb:ssas.tmschema_columns_t.adoc[]" as ssas.TMSCHEMA_COLUMNS_T << U >> {
  - **databasename** : (nvarchar(128))
  - **ID** : (numeric(20, 0))
  - Alignment : (bigint)
  - AttributeHierarchyID : (numeric(20, 0))
  ColumnOriginID : (numeric(20, 0))
  - ColumnStorageID : (numeric(20, 0))
  DataCategory : (nvarchar(max))
  Description : (nvarchar(max))
  DisplayFolder : (nvarchar(max))
  - DisplayOrdinal : (int)
  ErrorMessage : (nvarchar(max))
  - ExplicitDataType : (bigint)
  - ExplicitName : (nvarchar(max))
  Expression : (nvarchar(max))
  FormatString : (nvarchar(max))
  - InferredDataType : (bigint)
  InferredName : (nvarchar(max))
  - IsAvailableInMDX : (bit)
  - IsDefaultImage : (bit)
  - IsDefaultLabel : (bit)
  - IsHidden : (bit)
  - IsKey : (bit)
  - IsNullable : (bit)
  - IsUnique : (bit)
  - KeepUniqueRows : (bit)
  - ModifiedTime : (datetime)
  RefreshedTime : (nvarchar(max))
  - RepoObjectColumn_guid : (uniqueidentifier)
  SortByColumnID : (numeric(20, 0))
  SourceColumn : (nvarchar(max))
  SourceProviderType : (nvarchar(max))
  - State : (bigint)
  - StructureModifiedTime : (datetime)
  - SummarizeBy : (bigint)
  - SystemFlags : (bigint)
  - TableDetailPosition : (int)
  - TableID : (numeric(20, 0))
  - Type : (bigint)
  --
}

entity "puml-link:dhw:sqldb:ssas.usp_persist_tmschema_columns_t.adoc[]" as ssas.usp_PERSIST_TMSCHEMA_COLUMNS_T << P >> {
  --
}

ssas.TMSCHEMA_COLUMNS <.. ssas.TMSCHEMA_COLUMNS_T
ssas.TMSCHEMA_COLUMNS_T <.. ssas.usp_PERSIST_TMSCHEMA_COLUMNS_T
"ssas.TMSCHEMA_COLUMNS::Alignment" <-- "ssas.TMSCHEMA_COLUMNS_T::Alignment"
"ssas.TMSCHEMA_COLUMNS::AttributeHierarchyID" <-- "ssas.TMSCHEMA_COLUMNS_T::AttributeHierarchyID"
"ssas.TMSCHEMA_COLUMNS::ColumnOriginID" <-- "ssas.TMSCHEMA_COLUMNS_T::ColumnOriginID"
"ssas.TMSCHEMA_COLUMNS::ColumnStorageID" <-- "ssas.TMSCHEMA_COLUMNS_T::ColumnStorageID"
"ssas.TMSCHEMA_COLUMNS::databasename" <-- "ssas.TMSCHEMA_COLUMNS_T::databasename"
"ssas.TMSCHEMA_COLUMNS::DataCategory" <-- "ssas.TMSCHEMA_COLUMNS_T::DataCategory"
"ssas.TMSCHEMA_COLUMNS::Description" <-- "ssas.TMSCHEMA_COLUMNS_T::Description"
"ssas.TMSCHEMA_COLUMNS::DisplayFolder" <-- "ssas.TMSCHEMA_COLUMNS_T::DisplayFolder"
"ssas.TMSCHEMA_COLUMNS::DisplayOrdinal" <-- "ssas.TMSCHEMA_COLUMNS_T::DisplayOrdinal"
"ssas.TMSCHEMA_COLUMNS::ErrorMessage" <-- "ssas.TMSCHEMA_COLUMNS_T::ErrorMessage"
"ssas.TMSCHEMA_COLUMNS::ExplicitDataType" <-- "ssas.TMSCHEMA_COLUMNS_T::ExplicitDataType"
"ssas.TMSCHEMA_COLUMNS::ExplicitName" <-- "ssas.TMSCHEMA_COLUMNS_T::ExplicitName"
"ssas.TMSCHEMA_COLUMNS::Expression" <-- "ssas.TMSCHEMA_COLUMNS_T::Expression"
"ssas.TMSCHEMA_COLUMNS::FormatString" <-- "ssas.TMSCHEMA_COLUMNS_T::FormatString"
"ssas.TMSCHEMA_COLUMNS::ID" <-- "ssas.TMSCHEMA_COLUMNS_T::ID"
"ssas.TMSCHEMA_COLUMNS::InferredDataType" <-- "ssas.TMSCHEMA_COLUMNS_T::InferredDataType"
"ssas.TMSCHEMA_COLUMNS::InferredName" <-- "ssas.TMSCHEMA_COLUMNS_T::InferredName"
"ssas.TMSCHEMA_COLUMNS::IsAvailableInMDX" <-- "ssas.TMSCHEMA_COLUMNS_T::IsAvailableInMDX"
"ssas.TMSCHEMA_COLUMNS::IsDefaultImage" <-- "ssas.TMSCHEMA_COLUMNS_T::IsDefaultImage"
"ssas.TMSCHEMA_COLUMNS::IsDefaultLabel" <-- "ssas.TMSCHEMA_COLUMNS_T::IsDefaultLabel"
"ssas.TMSCHEMA_COLUMNS::IsHidden" <-- "ssas.TMSCHEMA_COLUMNS_T::IsHidden"
"ssas.TMSCHEMA_COLUMNS::IsKey" <-- "ssas.TMSCHEMA_COLUMNS_T::IsKey"
"ssas.TMSCHEMA_COLUMNS::IsNullable" <-- "ssas.TMSCHEMA_COLUMNS_T::IsNullable"
"ssas.TMSCHEMA_COLUMNS::IsUnique" <-- "ssas.TMSCHEMA_COLUMNS_T::IsUnique"
"ssas.TMSCHEMA_COLUMNS::KeepUniqueRows" <-- "ssas.TMSCHEMA_COLUMNS_T::KeepUniqueRows"
"ssas.TMSCHEMA_COLUMNS::ModifiedTime" <-- "ssas.TMSCHEMA_COLUMNS_T::ModifiedTime"
"ssas.TMSCHEMA_COLUMNS::RefreshedTime" <-- "ssas.TMSCHEMA_COLUMNS_T::RefreshedTime"
"ssas.TMSCHEMA_COLUMNS::SortByColumnID" <-- "ssas.TMSCHEMA_COLUMNS_T::SortByColumnID"
"ssas.TMSCHEMA_COLUMNS::SourceColumn" <-- "ssas.TMSCHEMA_COLUMNS_T::SourceColumn"
"ssas.TMSCHEMA_COLUMNS::SourceProviderType" <-- "ssas.TMSCHEMA_COLUMNS_T::SourceProviderType"
"ssas.TMSCHEMA_COLUMNS::State" <-- "ssas.TMSCHEMA_COLUMNS_T::State"
"ssas.TMSCHEMA_COLUMNS::StructureModifiedTime" <-- "ssas.TMSCHEMA_COLUMNS_T::StructureModifiedTime"
"ssas.TMSCHEMA_COLUMNS::SummarizeBy" <-- "ssas.TMSCHEMA_COLUMNS_T::SummarizeBy"
"ssas.TMSCHEMA_COLUMNS::SystemFlags" <-- "ssas.TMSCHEMA_COLUMNS_T::SystemFlags"
"ssas.TMSCHEMA_COLUMNS::TableDetailPosition" <-- "ssas.TMSCHEMA_COLUMNS_T::TableDetailPosition"
"ssas.TMSCHEMA_COLUMNS::TableID" <-- "ssas.TMSCHEMA_COLUMNS_T::TableID"
"ssas.TMSCHEMA_COLUMNS::Type" <-- "ssas.TMSCHEMA_COLUMNS_T::Type"

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_colref[]


== sql_modules_definition

// tag::sql_modules_definition[]
[%collapsible]
=======
[source,sql,numbered,indent=0]
----

----
=======
// end::sql_modules_definition[]


