// tag::HeaderFullDisplayName[]
= ssas.TMSCHEMA_RELATIONSHIPS_T - U
// end::HeaderFullDisplayName[]

== existing_properties

// tag::existing_properties[]

:ExistsProperty--antorareferencedlist:
:ExistsProperty--antorareferencinglist:
:ExistsProperty--has_history:
:ExistsProperty--has_history_columns:
:ExistsProperty--inheritancetype:
:ExistsProperty--is_persistence:
:ExistsProperty--is_persistence_check_duplicate_per_pk:
:ExistsProperty--is_persistence_check_for_empty_source:
:ExistsProperty--is_persistence_delete_changed:
:ExistsProperty--is_persistence_delete_missing:
:ExistsProperty--is_persistence_insert:
:ExistsProperty--is_persistence_truncate:
:ExistsProperty--is_persistence_update_changed:
:ExistsProperty--is_repo_managed:
:ExistsProperty--is_ssas:
:ExistsProperty--persistence_source_repoobject_fullname:
:ExistsProperty--persistence_source_repoobject_fullname2:
:ExistsProperty--persistence_source_repoobject_guid:
:ExistsProperty--persistence_source_repoobject_xref:
:ExistsProperty--pk_index_guid:
:ExistsProperty--pk_indexpatterncolumndatatype:
:ExistsProperty--pk_indexpatterncolumnname:
:ExistsProperty--referencedobjectlist:
:ExistsProperty--usp_persistence_repoobject_guid:
:ExistsProperty--FK:
:ExistsProperty--AntoraIndexList:
:ExistsProperty--Columns:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
40ECD625-1608-EC11-8515-A81E8446D5B0
// end::RepoObject_guid[]

== RepoObject_FullDisplayName2

// tag::RepoObject_FullDisplayName2[]
ssas.TMSCHEMA_RELATIONSHIPS_T
// end::RepoObject_FullDisplayName2[]

== SysObject_type

// tag::SysObject_type[]
U 
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
user table
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
311008189
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2021-11-25 19:14:05
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]
[discrete]
== _


[#column-databasename]
=== databasename

[cols="d,8a,m,m,m"]
|===
|1
|*databasename*

.Default: 
[source,sql]
----
(N'mydatabase')
----


|nvarchar(128)
|NOT NULL
|
|===

.Referenced Columns
--
* xref:ssas.tmschema_relationships.adoc#column-databasename[+ssas.TMSCHEMA_RELATIONSHIPS.databasename+]
--


[#column-id]
=== ID

[cols="d,8a,m,m,m"]
|===
|2
|*ID*
|numeric(20, 0)
|NOT NULL
|
|===

.Referenced Columns
--
* xref:ssas.tmschema_relationships.adoc#column-id[+ssas.TMSCHEMA_RELATIONSHIPS.ID+]
--


[#column-crossfilteringbehavior]
=== CrossFilteringBehavior

[cols="d,8a,m,m,m"]
|===
|
|CrossFilteringBehavior
|bigint
|NOT NULL
|
|===

.Referenced Columns
--
* xref:ssas.tmschema_relationships.adoc#column-crossfilteringbehavior[+ssas.TMSCHEMA_RELATIONSHIPS.CrossFilteringBehavior+]
--


[#column-foreignkeyunderlineguid]
=== ForeignKey_guid

[cols="d,8a,m,m,m"]
|===
|
|ForeignKey_guid

.Default: DF_TMSCHEMA_RELATIONSHIPS_T_RepoObject_guid
[source,sql]
----
(newsequentialid())
----


|uniqueidentifier
|NOT NULL
|
|===


[#column-fromcardinality]
=== FromCardinality

[cols="d,8a,m,m,m"]
|===
|
|FromCardinality
|bigint
|NOT NULL
|
|===

.Referenced Columns
--
* xref:ssas.tmschema_relationships.adoc#column-fromcardinality[+ssas.TMSCHEMA_RELATIONSHIPS.FromCardinality+]
--


[#column-fromcolumnid]
=== FromColumnID

[cols="d,8a,m,m,m"]
|===
|
|FromColumnID
|numeric(20, 0)
|NOT NULL
|
|===

.Referenced Columns
--
* xref:ssas.tmschema_relationships.adoc#column-fromcolumnid[+ssas.TMSCHEMA_RELATIONSHIPS.FromColumnID+]
--


[#column-fromtableid]
=== FromTableID

[cols="d,8a,m,m,m"]
|===
|
|FromTableID
|numeric(20, 0)
|NOT NULL
|
|===

.Referenced Columns
--
* xref:ssas.tmschema_relationships.adoc#column-fromtableid[+ssas.TMSCHEMA_RELATIONSHIPS.FromTableID+]
--


[#column-isactive]
=== IsActive

[cols="d,8a,m,m,m"]
|===
|
|IsActive
|bit
|NOT NULL
|
|===

.Referenced Columns
--
* xref:ssas.tmschema_relationships.adoc#column-isactive[+ssas.TMSCHEMA_RELATIONSHIPS.IsActive+]
--


[#column-joinondatebehavior]
=== JoinOnDateBehavior

[cols="d,8a,m,m,m"]
|===
|
|JoinOnDateBehavior
|bigint
|NOT NULL
|
|===

.Referenced Columns
--
* xref:ssas.tmschema_relationships.adoc#column-joinondatebehavior[+ssas.TMSCHEMA_RELATIONSHIPS.JoinOnDateBehavior+]
--


[#column-modelid]
=== ModelID

[cols="d,8a,m,m,m"]
|===
|
|ModelID
|numeric(20, 0)
|NOT NULL
|
|===

.Referenced Columns
--
* xref:ssas.tmschema_relationships.adoc#column-modelid[+ssas.TMSCHEMA_RELATIONSHIPS.ModelID+]
--


[#column-modifiedtime]
=== ModifiedTime

[cols="d,8a,m,m,m"]
|===
|
|ModifiedTime
|datetime
|NOT NULL
|
|===

.Referenced Columns
--
* xref:ssas.tmschema_relationships.adoc#column-modifiedtime[+ssas.TMSCHEMA_RELATIONSHIPS.ModifiedTime+]
--


[#column-name]
=== Name

[cols="d,8a,m,m,m"]
|===
|
|Name
|nvarchar(max)
|NOT NULL
|
|===

.Referenced Columns
--
* xref:ssas.tmschema_relationships.adoc#column-name[+ssas.TMSCHEMA_RELATIONSHIPS.Name+]
--


[#column-refreshedtime]
=== RefreshedTime

[cols="d,8a,m,m,m"]
|===
|
|RefreshedTime
|datetime
|NULL
|
|===

.Referenced Columns
--
* xref:ssas.tmschema_relationships.adoc#column-refreshedtime[+ssas.TMSCHEMA_RELATIONSHIPS.RefreshedTime+]
--


[#column-relationshipstorage2id]
=== RelationshipStorage2ID

[cols="d,8a,m,m,m"]
|===
|
|RelationshipStorage2ID
|numeric(20, 0)
|NULL
|
|===

.Referenced Columns
--
* xref:ssas.tmschema_relationships.adoc#column-relationshipstorage2id[+ssas.TMSCHEMA_RELATIONSHIPS.RelationshipStorage2ID+]
--


[#column-relationshipstorageid]
=== RelationshipStorageID

[cols="d,8a,m,m,m"]
|===
|
|RelationshipStorageID
|numeric(20, 0)
|NULL
|
|===

.Referenced Columns
--
* xref:ssas.tmschema_relationships.adoc#column-relationshipstorageid[+ssas.TMSCHEMA_RELATIONSHIPS.RelationshipStorageID+]
--


[#column-relyonreferentialintegrity]
=== RelyOnReferentialIntegrity

[cols="d,8a,m,m,m"]
|===
|
|RelyOnReferentialIntegrity
|bit
|NOT NULL
|
|===

.Referenced Columns
--
* xref:ssas.tmschema_relationships.adoc#column-relyonreferentialintegrity[+ssas.TMSCHEMA_RELATIONSHIPS.RelyOnReferentialIntegrity+]
--


[#column-securityfilteringbehavior]
=== SecurityFilteringBehavior

[cols="d,8a,m,m,m"]
|===
|
|SecurityFilteringBehavior
|bigint
|NOT NULL
|
|===

.Referenced Columns
--
* xref:ssas.tmschema_relationships.adoc#column-securityfilteringbehavior[+ssas.TMSCHEMA_RELATIONSHIPS.SecurityFilteringBehavior+]
--


[#column-state]
=== State

[cols="d,8a,m,m,m"]
|===
|
|State
|bigint
|NOT NULL
|
|===

.Referenced Columns
--
* xref:ssas.tmschema_relationships.adoc#column-state[+ssas.TMSCHEMA_RELATIONSHIPS.State+]
--


[#column-tocardinality]
=== ToCardinality

[cols="d,8a,m,m,m"]
|===
|
|ToCardinality
|bigint
|NOT NULL
|
|===

.Referenced Columns
--
* xref:ssas.tmschema_relationships.adoc#column-tocardinality[+ssas.TMSCHEMA_RELATIONSHIPS.ToCardinality+]
--


[#column-tocolumnid]
=== ToColumnID

[cols="d,8a,m,m,m"]
|===
|
|ToColumnID
|numeric(20, 0)
|NOT NULL
|
|===

.Referenced Columns
--
* xref:ssas.tmschema_relationships.adoc#column-tocolumnid[+ssas.TMSCHEMA_RELATIONSHIPS.ToColumnID+]
--


[#column-totableid]
=== ToTableID

[cols="d,8a,m,m,m"]
|===
|
|ToTableID
|numeric(20, 0)
|NOT NULL
|
|===

.Referenced Columns
--
* xref:ssas.tmschema_relationships.adoc#column-totableid[+ssas.TMSCHEMA_RELATIONSHIPS.ToTableID+]
--


[#column-type]
=== Type

[cols="d,8a,m,m,m"]
|===
|
|Type
|bigint
|NOT NULL
|
|===

.Referenced Columns
--
* xref:ssas.tmschema_relationships.adoc#column-type[+ssas.TMSCHEMA_RELATIONSHIPS.Type+]
--


// end::AntoraColumnDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]
|1
|*<<column-databasename>>*

.Default: 
[source,sql]
----
(N'mydatabase')
----


|nvarchar(128)
|NOT NULL
|

|2
|*<<column-id>>*
|numeric(20, 0)
|NOT NULL
|





















// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]


|
|<<column-crossfilteringbehavior>>
|bigint
|NOT NULL
|

|
|<<column-foreignkeyunderlineguid>>

.Default: DF_TMSCHEMA_RELATIONSHIPS_T_RepoObject_guid
[source,sql]
----
(newsequentialid())
----


|uniqueidentifier
|NOT NULL
|

|
|<<column-fromcardinality>>
|bigint
|NOT NULL
|

|
|<<column-fromcolumnid>>
|numeric(20, 0)
|NOT NULL
|

|
|<<column-fromtableid>>
|numeric(20, 0)
|NOT NULL
|

|
|<<column-isactive>>
|bit
|NOT NULL
|

|
|<<column-joinondatebehavior>>
|bigint
|NOT NULL
|

|
|<<column-modelid>>
|numeric(20, 0)
|NOT NULL
|

|
|<<column-modifiedtime>>
|datetime
|NOT NULL
|

|
|<<column-name>>
|nvarchar(max)
|NOT NULL
|

|
|<<column-refreshedtime>>
|datetime
|NULL
|

|
|<<column-relationshipstorage2id>>
|numeric(20, 0)
|NULL
|

|
|<<column-relationshipstorageid>>
|numeric(20, 0)
|NULL
|

|
|<<column-relyonreferentialintegrity>>
|bit
|NOT NULL
|

|
|<<column-securityfilteringbehavior>>
|bigint
|NOT NULL
|

|
|<<column-state>>
|bigint
|NOT NULL
|

|
|<<column-tocardinality>>
|bigint
|NOT NULL
|

|
|<<column-tocolumnid>>
|numeric(20, 0)
|NOT NULL
|

|
|<<column-totableid>>
|numeric(20, 0)
|NOT NULL
|

|
|<<column-type>>
|bigint
|NOT NULL
|

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

[#index-pkunderlinetmschemaunderlinerelationshipsunderlinet]
=== PK_TMSCHEMA_RELATIONSHIPS_T

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-databasename>>; nvarchar(128)
* <<column-ID>>; numeric(20, 0)
--
* PK, Unique, Real: 1, 1, 1

// end::AntoraIndexList[]

== AntoraMeasureDetails

// tag::AntoraMeasureDetails[]

// end::AntoraMeasureDetails[]

== AntoraMeasureDescriptions



== AntoraParameterList

// tag::AntoraParameterList[]

// end::AntoraParameterList[]

== AntoraXrefCulturesList

// tag::AntoraXrefCulturesList[]
* xref:dhw:sqldb:ssas.tmschema_relationships_t.adoc[] - 
// end::AntoraXrefCulturesList[]

== cultures_count

// tag::cultures_count[]
1
// end::cultures_count[]

== Other tags

source: property.RepoObjectProperty_cross As rop_cross


=== additional_reference_csv

// tag::additional_reference_csv[]

// end::additional_reference_csv[]


=== AdocUspSteps

// tag::adocuspsteps[]

// end::adocuspsteps[]


=== AntoraReferencedList

// tag::antorareferencedlist[]
* xref:dhw:sqldb:ssas.tmschema_relationships.adoc[]
// end::antorareferencedlist[]


=== AntoraReferencingList

// tag::antorareferencinglist[]
* xref:dhw:sqldb:ssas.usp_persist_tmschema_relationships_t.adoc[]
// end::antorareferencinglist[]


=== Description

// tag::description[]

// end::description[]


=== exampleUsage

// tag::exampleusage[]

// end::exampleusage[]


=== exampleUsage_2

// tag::exampleusage_2[]

// end::exampleusage_2[]


=== exampleUsage_3

// tag::exampleusage_3[]

// end::exampleusage_3[]


=== exampleUsage_4

// tag::exampleusage_4[]

// end::exampleusage_4[]


=== exampleUsage_5

// tag::exampleusage_5[]

// end::exampleusage_5[]


=== exampleWrong_Usage

// tag::examplewrong_usage[]

// end::examplewrong_usage[]


=== has_execution_plan_issue

// tag::has_execution_plan_issue[]

// end::has_execution_plan_issue[]


=== has_get_referenced_issue

// tag::has_get_referenced_issue[]

// end::has_get_referenced_issue[]


=== has_history

// tag::has_history[]
0
// end::has_history[]


=== has_history_columns

// tag::has_history_columns[]
0
// end::has_history_columns[]


=== InheritanceType

// tag::inheritancetype[]
13
// end::inheritancetype[]


=== is_persistence

// tag::is_persistence[]
1
// end::is_persistence[]


=== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]
0
// end::is_persistence_check_duplicate_per_pk[]


=== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]
0
// end::is_persistence_check_for_empty_source[]


=== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]
0
// end::is_persistence_delete_changed[]


=== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]
1
// end::is_persistence_delete_missing[]


=== is_persistence_insert

// tag::is_persistence_insert[]
1
// end::is_persistence_insert[]


=== is_persistence_truncate

// tag::is_persistence_truncate[]
0
// end::is_persistence_truncate[]


=== is_persistence_update_changed

// tag::is_persistence_update_changed[]
1
// end::is_persistence_update_changed[]


=== is_repo_managed

// tag::is_repo_managed[]
1
// end::is_repo_managed[]


=== is_ssas

// tag::is_ssas[]
0
// end::is_ssas[]


=== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


=== MS_Description

// tag::ms_description[]

// end::ms_description[]


=== persistence_source_RepoObject_fullname

// tag::persistence_source_repoobject_fullname[]
[ssas].[TMSCHEMA_RELATIONSHIPS]
// end::persistence_source_repoobject_fullname[]


=== persistence_source_RepoObject_fullname2

// tag::persistence_source_repoobject_fullname2[]
ssas.TMSCHEMA_RELATIONSHIPS
// end::persistence_source_repoobject_fullname2[]


=== persistence_source_RepoObject_guid

// tag::persistence_source_repoobject_guid[]
E4E6A70A-8A06-EC11-8515-A81E8446D5B0
// end::persistence_source_repoobject_guid[]


=== persistence_source_RepoObject_xref

// tag::persistence_source_repoobject_xref[]
xref:ssas.tmschema_relationships.adoc[]
// end::persistence_source_repoobject_xref[]


=== pk_index_guid

// tag::pk_index_guid[]
863ADABD-1608-EC11-8515-A81E8446D5B0
// end::pk_index_guid[]


=== pk_IndexPatternColumnDatatype

// tag::pk_indexpatterncolumndatatype[]
nvarchar(128),numeric(20, 0)
// end::pk_indexpatterncolumndatatype[]


=== pk_IndexPatternColumnName

// tag::pk_indexpatterncolumnname[]
databasename,ID
// end::pk_indexpatterncolumnname[]


=== pk_IndexSemanticGroup

// tag::pk_indexsemanticgroup[]

// end::pk_indexsemanticgroup[]


=== ReferencedObjectList

// tag::referencedobjectlist[]
* [ssas].[TMSCHEMA_RELATIONSHIPS]
// end::referencedobjectlist[]


=== usp_persistence_RepoObject_guid

// tag::usp_persistence_repoobject_guid[]
666E8DEE-3D08-EC11-8515-A81E8446D5B0
// end::usp_persistence_repoobject_guid[]


=== UspExamples

// tag::uspexamples[]

// end::uspexamples[]


=== uspgenerator_usp_id

// tag::uspgenerator_usp_id[]

// end::uspgenerator_usp_id[]


=== UspParameters

// tag::uspparameters[]

// end::uspparameters[]

== Boolean Attributes

source: property.RepoObjectProperty WHERE property_int = 1

// tag::boolean_attributes[]

:is_persistence:
:is_persistence_delete_missing:
:is_persistence_insert:
:is_persistence_update_changed:
:is_repo_managed:

// end::boolean_attributes[]

== PlantUML diagrams

=== PlantUML Entity

// tag::puml_entity[]
[plantuml, entity-{docname}, svg, subs=macros]
....
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssas.tmschema_relationships_t.adoc[]" as ssas.TMSCHEMA_RELATIONSHIPS_T << U >> {
  - **databasename** : (nvarchar(128))
  - **ID** : (numeric(20, 0))
  - CrossFilteringBehavior : (bigint)
  - ForeignKey_guid : (uniqueidentifier)
  - FromCardinality : (bigint)
  - FromColumnID : (numeric(20, 0))
  - FromTableID : (numeric(20, 0))
  - IsActive : (bit)
  - JoinOnDateBehavior : (bigint)
  - ModelID : (numeric(20, 0))
  - ModifiedTime : (datetime)
  - Name : (nvarchar(max))
  RefreshedTime : (datetime)
  RelationshipStorage2ID : (numeric(20, 0))
  RelationshipStorageID : (numeric(20, 0))
  - RelyOnReferentialIntegrity : (bit)
  - SecurityFilteringBehavior : (bigint)
  - State : (bigint)
  - ToCardinality : (bigint)
  - ToColumnID : (numeric(20, 0))
  - ToTableID : (numeric(20, 0))
  - Type : (bigint)
  --
}
....

// end::puml_entity[]

=== PlantUML Entity 1 1 FK

// tag::puml_entity_1_1_fk[]
[plantuml, entity_1_1_fk-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssas.tmschema_relationships_t.adoc[]" as ssas.TMSCHEMA_RELATIONSHIPS_T << U >> {
**PK_TMSCHEMA_RELATIONSHIPS_T**

..
databasename; nvarchar(128)
ID; numeric(20, 0)
}



footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_fk[]

=== PlantUML 1 1 ObjectRef

// tag::puml_entity_1_1_objectref[]
[plantuml, entity_1_1_objectref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssas.tmschema_relationships.adoc[]" as ssas.TMSCHEMA_RELATIONSHIPS << U >> {
  - **databasename** : (nvarchar(128))
  - **ID** : (numeric(20, 0))
  --
}

entity "puml-link:dhw:sqldb:ssas.tmschema_relationships_t.adoc[]" as ssas.TMSCHEMA_RELATIONSHIPS_T << U >> {
  - **databasename** : (nvarchar(128))
  - **ID** : (numeric(20, 0))
  --
}

entity "puml-link:dhw:sqldb:ssas.usp_persist_tmschema_relationships_t.adoc[]" as ssas.usp_PERSIST_TMSCHEMA_RELATIONSHIPS_T << P >> {
  --
}

ssas.TMSCHEMA_RELATIONSHIPS <.. ssas.TMSCHEMA_RELATIONSHIPS_T
ssas.TMSCHEMA_RELATIONSHIPS_T <.. ssas.usp_PERSIST_TMSCHEMA_RELATIONSHIPS_T

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_objectref[]

=== PlantUML 30 0 ObjectRef

// tag::puml_entity_30_0_objectref[]
[plantuml, entity_30_0_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssas.tmschema_relationships.adoc[]" as ssas.TMSCHEMA_RELATIONSHIPS << U >> {
  - **databasename** : (nvarchar(128))
  - **ID** : (numeric(20, 0))
  --
}

entity "puml-link:dhw:sqldb:ssas.tmschema_relationships_t.adoc[]" as ssas.TMSCHEMA_RELATIONSHIPS_T << U >> {
  - **databasename** : (nvarchar(128))
  - **ID** : (numeric(20, 0))
  --
}

ssas.TMSCHEMA_RELATIONSHIPS <.. ssas.TMSCHEMA_RELATIONSHIPS_T

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_30_0_objectref[]

=== PlantUML 0 30 ObjectRef

// tag::puml_entity_0_30_objectref[]
[plantuml, entity_0_30_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssas.tmschema_relationships_t.adoc[]" as ssas.TMSCHEMA_RELATIONSHIPS_T << U >> {
  - **databasename** : (nvarchar(128))
  - **ID** : (numeric(20, 0))
  --
}

entity "puml-link:dhw:sqldb:ssas.usp_persist_tmschema_relationships_t.adoc[]" as ssas.usp_PERSIST_TMSCHEMA_RELATIONSHIPS_T << P >> {
  --
}

ssas.TMSCHEMA_RELATIONSHIPS_T <.. ssas.usp_PERSIST_TMSCHEMA_RELATIONSHIPS_T

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_0_30_objectref[]

=== PlantUML 1 1 ColumnRef

// tag::puml_entity_1_1_colref[]
[plantuml, entity_1_1_colref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssas.tmschema_relationships.adoc[]" as ssas.TMSCHEMA_RELATIONSHIPS << U >> {
  - **databasename** : (nvarchar(128))
  - **ID** : (numeric(20, 0))
  - CrossFilteringBehavior : (bigint)
  - FromCardinality : (bigint)
  - FromColumnID : (numeric(20, 0))
  - FromTableID : (numeric(20, 0))
  - IsActive : (bit)
  - JoinOnDateBehavior : (bigint)
  - ModelID : (numeric(20, 0))
  - ModifiedTime : (datetime)
  - Name : (nvarchar(max))
  RefreshedTime : (datetime)
  RelationshipStorage2ID : (numeric(20, 0))
  RelationshipStorageID : (numeric(20, 0))
  - RelyOnReferentialIntegrity : (bit)
  - SecurityFilteringBehavior : (bigint)
  - State : (bigint)
  - ToCardinality : (bigint)
  - ToColumnID : (numeric(20, 0))
  - ToTableID : (numeric(20, 0))
  - Type : (bigint)
  --
}

entity "puml-link:dhw:sqldb:ssas.tmschema_relationships_t.adoc[]" as ssas.TMSCHEMA_RELATIONSHIPS_T << U >> {
  - **databasename** : (nvarchar(128))
  - **ID** : (numeric(20, 0))
  - CrossFilteringBehavior : (bigint)
  - ForeignKey_guid : (uniqueidentifier)
  - FromCardinality : (bigint)
  - FromColumnID : (numeric(20, 0))
  - FromTableID : (numeric(20, 0))
  - IsActive : (bit)
  - JoinOnDateBehavior : (bigint)
  - ModelID : (numeric(20, 0))
  - ModifiedTime : (datetime)
  - Name : (nvarchar(max))
  RefreshedTime : (datetime)
  RelationshipStorage2ID : (numeric(20, 0))
  RelationshipStorageID : (numeric(20, 0))
  - RelyOnReferentialIntegrity : (bit)
  - SecurityFilteringBehavior : (bigint)
  - State : (bigint)
  - ToCardinality : (bigint)
  - ToColumnID : (numeric(20, 0))
  - ToTableID : (numeric(20, 0))
  - Type : (bigint)
  --
}

entity "puml-link:dhw:sqldb:ssas.usp_persist_tmschema_relationships_t.adoc[]" as ssas.usp_PERSIST_TMSCHEMA_RELATIONSHIPS_T << P >> {
  --
}

ssas.TMSCHEMA_RELATIONSHIPS <.. ssas.TMSCHEMA_RELATIONSHIPS_T
ssas.TMSCHEMA_RELATIONSHIPS_T <.. ssas.usp_PERSIST_TMSCHEMA_RELATIONSHIPS_T
"ssas.TMSCHEMA_RELATIONSHIPS::CrossFilteringBehavior" <-- "ssas.TMSCHEMA_RELATIONSHIPS_T::CrossFilteringBehavior"
"ssas.TMSCHEMA_RELATIONSHIPS::databasename" <-- "ssas.TMSCHEMA_RELATIONSHIPS_T::databasename"
"ssas.TMSCHEMA_RELATIONSHIPS::FromCardinality" <-- "ssas.TMSCHEMA_RELATIONSHIPS_T::FromCardinality"
"ssas.TMSCHEMA_RELATIONSHIPS::FromColumnID" <-- "ssas.TMSCHEMA_RELATIONSHIPS_T::FromColumnID"
"ssas.TMSCHEMA_RELATIONSHIPS::FromTableID" <-- "ssas.TMSCHEMA_RELATIONSHIPS_T::FromTableID"
"ssas.TMSCHEMA_RELATIONSHIPS::ID" <-- "ssas.TMSCHEMA_RELATIONSHIPS_T::ID"
"ssas.TMSCHEMA_RELATIONSHIPS::IsActive" <-- "ssas.TMSCHEMA_RELATIONSHIPS_T::IsActive"
"ssas.TMSCHEMA_RELATIONSHIPS::JoinOnDateBehavior" <-- "ssas.TMSCHEMA_RELATIONSHIPS_T::JoinOnDateBehavior"
"ssas.TMSCHEMA_RELATIONSHIPS::ModelID" <-- "ssas.TMSCHEMA_RELATIONSHIPS_T::ModelID"
"ssas.TMSCHEMA_RELATIONSHIPS::ModifiedTime" <-- "ssas.TMSCHEMA_RELATIONSHIPS_T::ModifiedTime"
"ssas.TMSCHEMA_RELATIONSHIPS::Name" <-- "ssas.TMSCHEMA_RELATIONSHIPS_T::Name"
"ssas.TMSCHEMA_RELATIONSHIPS::RefreshedTime" <-- "ssas.TMSCHEMA_RELATIONSHIPS_T::RefreshedTime"
"ssas.TMSCHEMA_RELATIONSHIPS::RelationshipStorage2ID" <-- "ssas.TMSCHEMA_RELATIONSHIPS_T::RelationshipStorage2ID"
"ssas.TMSCHEMA_RELATIONSHIPS::RelationshipStorageID" <-- "ssas.TMSCHEMA_RELATIONSHIPS_T::RelationshipStorageID"
"ssas.TMSCHEMA_RELATIONSHIPS::RelyOnReferentialIntegrity" <-- "ssas.TMSCHEMA_RELATIONSHIPS_T::RelyOnReferentialIntegrity"
"ssas.TMSCHEMA_RELATIONSHIPS::SecurityFilteringBehavior" <-- "ssas.TMSCHEMA_RELATIONSHIPS_T::SecurityFilteringBehavior"
"ssas.TMSCHEMA_RELATIONSHIPS::State" <-- "ssas.TMSCHEMA_RELATIONSHIPS_T::State"
"ssas.TMSCHEMA_RELATIONSHIPS::ToCardinality" <-- "ssas.TMSCHEMA_RELATIONSHIPS_T::ToCardinality"
"ssas.TMSCHEMA_RELATIONSHIPS::ToColumnID" <-- "ssas.TMSCHEMA_RELATIONSHIPS_T::ToColumnID"
"ssas.TMSCHEMA_RELATIONSHIPS::ToTableID" <-- "ssas.TMSCHEMA_RELATIONSHIPS_T::ToTableID"
"ssas.TMSCHEMA_RELATIONSHIPS::Type" <-- "ssas.TMSCHEMA_RELATIONSHIPS_T::Type"

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_colref[]


== sql_modules_definition

// tag::sql_modules_definition[]
[%collapsible]
=======
[source,sql,numbered,indent=0]
----

----
=======
// end::sql_modules_definition[]


