// tag::HeaderFullDisplayName[]
= ssas.model_json_201_descriptions_multiline - V
// end::HeaderFullDisplayName[]

== existing_properties

// tag::existing_properties[]

:ExistsProperty--antorareferencedlist:
:ExistsProperty--antorareferencinglist:
:ExistsProperty--is_repo_managed:
:ExistsProperty--is_ssas:
:ExistsProperty--referencedobjectlist:
:ExistsProperty--sql_modules_definition:
:ExistsProperty--FK:
:ExistsProperty--AntoraIndexList:
:ExistsProperty--Columns:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
24064FC7-110B-EC11-8516-A81E8446D5B0
// end::RepoObject_guid[]

== RepoObject_FullDisplayName2

// tag::RepoObject_FullDisplayName2[]
ssas.model_json_201_descriptions_multiline
// end::RepoObject_FullDisplayName2[]

== SysObject_type

// tag::SysObject_type[]
V 
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
view
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
1959014060
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2021-09-01 16:16:03
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]
[discrete]
== _


[#column-databasename]
=== databasename

[cols="d,8a,m,m,m"]
|===
|
|databasename
|nvarchar(128)
|NOT NULL
|
|===

.Referenced Columns
--
* xref:ssas.model_json_20.adoc#column-databasename[+ssas.model_json_20.databasename+]
--

.Referencing Columns
--
* xref:ssas.model_json_2011_descriptions_stragg.adoc#column-databasename[+ssas.model_json_2011_descriptions_StrAgg.databasename+]
--


[#column-key]
=== Key

[cols="d,8a,m,m,m"]
|===
|
|Key
|nvarchar(4000)
|NOT NULL
|
|===


[#column-type]
=== Type

[cols="d,8a,m,m,m"]
|===
|
|Type
|tinyint
|NOT NULL
|
|===


[#column-value]
=== Value

[cols="d,8a,m,m,m"]
|===
|
|Value
|nvarchar(max)
|NULL
|
|===


// end::AntoraColumnDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]




// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]
|
|<<column-databasename>>
|nvarchar(128)
|NOT NULL
|

|
|<<column-key>>
|nvarchar(4000)
|NOT NULL
|

|
|<<column-type>>
|tinyint
|NOT NULL
|

|
|<<column-value>>
|nvarchar(max)
|NULL
|

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

[#index-idxunderlinemodelunderlinejsonunderline201underlinedescriptionsunderlinemultilineunderlineunderline1]
=== idx_model_json_201_descriptions_multiline++__++1

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-databasename>>; nvarchar(128)
--
* PK, Unique, Real: 0, 0, 0

// end::AntoraIndexList[]

== AntoraMeasureDetails

// tag::AntoraMeasureDetails[]

// end::AntoraMeasureDetails[]

== AntoraMeasureDescriptions



== AntoraParameterList

// tag::AntoraParameterList[]

// end::AntoraParameterList[]

== AntoraXrefCulturesList

// tag::AntoraXrefCulturesList[]
* xref:dhw:sqldb:ssas.model_json_201_descriptions_multiline.adoc[] - 
// end::AntoraXrefCulturesList[]

== cultures_count

// tag::cultures_count[]
1
// end::cultures_count[]

== Other tags

source: property.RepoObjectProperty_cross As rop_cross


=== additional_reference_csv

// tag::additional_reference_csv[]

// end::additional_reference_csv[]


=== AdocUspSteps

// tag::adocuspsteps[]

// end::adocuspsteps[]


=== AntoraReferencedList

// tag::antorareferencedlist[]
* xref:dhw:sqldb:ssas.model_json_20.adoc[]
// end::antorareferencedlist[]


=== AntoraReferencingList

// tag::antorareferencinglist[]
* xref:dhw:sqldb:ssas.model_json_2011_descriptions_stragg.adoc[]
// end::antorareferencinglist[]


=== Description

// tag::description[]

// end::description[]


=== exampleUsage

// tag::exampleusage[]

// end::exampleusage[]


=== exampleUsage_2

// tag::exampleusage_2[]

// end::exampleusage_2[]


=== exampleUsage_3

// tag::exampleusage_3[]

// end::exampleusage_3[]


=== exampleUsage_4

// tag::exampleusage_4[]

// end::exampleusage_4[]


=== exampleUsage_5

// tag::exampleusage_5[]

// end::exampleusage_5[]


=== exampleWrong_Usage

// tag::examplewrong_usage[]

// end::examplewrong_usage[]


=== has_execution_plan_issue

// tag::has_execution_plan_issue[]

// end::has_execution_plan_issue[]


=== has_get_referenced_issue

// tag::has_get_referenced_issue[]

// end::has_get_referenced_issue[]


=== has_history

// tag::has_history[]

// end::has_history[]


=== has_history_columns

// tag::has_history_columns[]

// end::has_history_columns[]


=== InheritanceType

// tag::inheritancetype[]

// end::inheritancetype[]


=== is_persistence

// tag::is_persistence[]

// end::is_persistence[]


=== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]

// end::is_persistence_check_duplicate_per_pk[]


=== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]

// end::is_persistence_check_for_empty_source[]


=== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]

// end::is_persistence_delete_changed[]


=== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]

// end::is_persistence_delete_missing[]


=== is_persistence_insert

// tag::is_persistence_insert[]

// end::is_persistence_insert[]


=== is_persistence_truncate

// tag::is_persistence_truncate[]

// end::is_persistence_truncate[]


=== is_persistence_update_changed

// tag::is_persistence_update_changed[]

// end::is_persistence_update_changed[]


=== is_repo_managed

// tag::is_repo_managed[]
0
// end::is_repo_managed[]


=== is_ssas

// tag::is_ssas[]
0
// end::is_ssas[]


=== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


=== MS_Description

// tag::ms_description[]

// end::ms_description[]


=== persistence_source_RepoObject_fullname

// tag::persistence_source_repoobject_fullname[]

// end::persistence_source_repoobject_fullname[]


=== persistence_source_RepoObject_fullname2

// tag::persistence_source_repoobject_fullname2[]

// end::persistence_source_repoobject_fullname2[]


=== persistence_source_RepoObject_guid

// tag::persistence_source_repoobject_guid[]

// end::persistence_source_repoobject_guid[]


=== persistence_source_RepoObject_xref

// tag::persistence_source_repoobject_xref[]

// end::persistence_source_repoobject_xref[]


=== pk_index_guid

// tag::pk_index_guid[]

// end::pk_index_guid[]


=== pk_IndexPatternColumnDatatype

// tag::pk_indexpatterncolumndatatype[]

// end::pk_indexpatterncolumndatatype[]


=== pk_IndexPatternColumnName

// tag::pk_indexpatterncolumnname[]

// end::pk_indexpatterncolumnname[]


=== pk_IndexSemanticGroup

// tag::pk_indexsemanticgroup[]

// end::pk_indexsemanticgroup[]


=== ReferencedObjectList

// tag::referencedobjectlist[]
* [ssas].[model_json_20]
// end::referencedobjectlist[]


=== usp_persistence_RepoObject_guid

// tag::usp_persistence_repoobject_guid[]

// end::usp_persistence_repoobject_guid[]


=== UspExamples

// tag::uspexamples[]

// end::uspexamples[]


=== uspgenerator_usp_id

// tag::uspgenerator_usp_id[]

// end::uspgenerator_usp_id[]


=== UspParameters

// tag::uspparameters[]

// end::uspparameters[]

== Boolean Attributes

source: property.RepoObjectProperty WHERE property_int = 1

// tag::boolean_attributes[]


// end::boolean_attributes[]

== PlantUML diagrams

=== PlantUML Entity

// tag::puml_entity[]
[plantuml, entity-{docname}, svg, subs=macros]
....
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssas.model_json_201_descriptions_multiline.adoc[]" as ssas.model_json_201_descriptions_multiline << V >> {
  - databasename : (nvarchar(128))
  - Key : (nvarchar(4000))
  - Type : (tinyint)
  Value : (nvarchar(max))
  --
}
....

// end::puml_entity[]

=== PlantUML Entity 1 1 FK

// tag::puml_entity_1_1_fk[]
[plantuml, entity_1_1_fk-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssas.model_json_201_descriptions_multiline.adoc[]" as ssas.model_json_201_descriptions_multiline << V >> {
- idx_model_json_201_descriptions_multiline__1

..
databasename; nvarchar(128)
}



footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_fk[]

=== PlantUML 1 1 ObjectRef

// tag::puml_entity_1_1_objectref[]
[plantuml, entity_1_1_objectref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssas.model_json_20.adoc[]" as ssas.model_json_20 << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_201_descriptions_multiline.adoc[]" as ssas.model_json_201_descriptions_multiline << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_2011_descriptions_stragg.adoc[]" as ssas.model_json_2011_descriptions_StrAgg << V >> {
  --
}

ssas.model_json_20 <.. ssas.model_json_201_descriptions_multiline
ssas.model_json_201_descriptions_multiline <.. ssas.model_json_2011_descriptions_StrAgg

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_objectref[]

=== PlantUML 30 0 ObjectRef

// tag::puml_entity_30_0_objectref[]
[plantuml, entity_30_0_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssas.model_json.adoc[]" as ssas.model_json << U >> {
  - **databasename** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_10.adoc[]" as ssas.model_json_10 << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_20.adoc[]" as ssas.model_json_20 << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_201_descriptions_multiline.adoc[]" as ssas.model_json_201_descriptions_multiline << V >> {
  --
}

ssas.model_json <.. ssas.model_json_10
ssas.model_json_10 <.. ssas.model_json_20
ssas.model_json_20 <.. ssas.model_json_201_descriptions_multiline

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_30_0_objectref[]

=== PlantUML 0 30 ObjectRef

// tag::puml_entity_0_30_objectref[]
[plantuml, entity_0_30_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:dmdocs.unit.adoc[]" as dmdocs.unit << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.antoranavlistpage_by_schema.adoc[]" as docs.AntoraNavListPage_by_schema << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.antoranavlistpage_by_type.adoc[]" as docs.AntoraNavListPage_by_type << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.antoranavlistrepoobject_by_schema.adoc[]" as docs.AntoraNavListRepoObject_by_schema << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.antoranavlistrepoobject_by_schema_type.adoc[]" as docs.AntoraNavListRepoObject_by_schema_type << V >> {
  - **RepoObject_schema_name** : (nvarchar(128))
  **type** : (char(2))
  --
}

entity "puml-link:dhw:sqldb:docs.antoranavlistrepoobject_by_type.adoc[]" as docs.AntoraNavListRepoObject_by_type << V >> {
  **type** : (char(2))
  --
}

entity "puml-link:dhw:sqldb:docs.antorapage_indexsemanticgroup.adoc[]" as docs.AntoraPage_IndexSemanticGroup << V >> {
  - **page_content** : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:docs.antorapage_objectbyschema.adoc[]" as docs.AntoraPage_ObjectBySchema << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.antorapage_objectbytype.adoc[]" as docs.AntoraPage_ObjectByType << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.antoratemplate_examples.adoc[]" as docs.AntoraTemplate_examples << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.foreignkey_relationscript.adoc[]" as docs.ForeignKey_RelationScript << V >> {
  **referenced_RepoObject_guid** : (uniqueidentifier)
  **referencing_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:docs.ftv_repoobject_antoraxref.adoc[]" as docs.ftv_RepoObject_AntoraXref << IF >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ftv_repoobject_reference_plantuml_entityreflist.adoc[]" as docs.ftv_RepoObject_Reference_PlantUml_EntityRefList << IF >> {
  --
}

entity "puml-link:dhw:sqldb:docs.indexsemanticgroup.adoc[]" as docs.IndexSemanticgroup << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.indexsemanticgrouppatterndatatype.adoc[]" as docs.IndexSemanticgroupPatterndatatype << V >> {
  **IndexSemanticGroup** : (nvarchar(512))
  **IndexPatternColumnDatatype** : (nvarchar(4000))
  --
}

entity "puml-link:dhw:sqldb:docs.measure_measurepropertylist.adoc[]" as docs.Measure_MeasurePropertyList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.objectrefcyclic.adoc[]" as docs.ObjectRefCyclic << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.objectrefcyclic_entitylist.adoc[]" as docs.ObjectRefCyclic_EntityList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.objectrefcyclic_objectreflist.adoc[]" as docs.ObjectRefCyclic_ObjectRefList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_adoc.adoc[]" as docs.RepoObject_Adoc << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_adoc_t.adoc[]" as docs.RepoObject_Adoc_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_antoraxrefcultureslist.adoc[]" as docs.RepoObject_AntoraXrefCulturesList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_columnlist.adoc[]" as docs.RepoObject_ColumnList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_columnlist_t.adoc[]" as docs.RepoObject_ColumnList_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_indexlist.adoc[]" as docs.RepoObject_IndexList << V >> {
  **RepoObject_guid** : (uniqueidentifier)
  **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_indexlist_t.adoc[]" as docs.RepoObject_IndexList_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_measuredescriptionlist.adoc[]" as docs.RepoObject_MeasureDescriptionList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_measurelist.adoc[]" as docs.RepoObject_MeasureList << V >> {
  **RepoObject_guid** : (uniqueidentifier)
  **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_outputfilter.adoc[]" as docs.RepoObject_OutputFilter << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_outputfilter_t.adoc[]" as docs.RepoObject_OutputFilter_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_outputfilter_t_gross.adoc[]" as docs.RepoObject_OutputFilter_T_gross << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml.adoc[]" as docs.RepoObject_Plantuml << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_colreflist_1_1.adoc[]" as docs.RepoObject_Plantuml_ColRefList_1_1 << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_entity.adoc[]" as docs.RepoObject_Plantuml_Entity << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_entity_t.adoc[]" as docs.RepoObject_Plantuml_Entity_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_fkreflist.adoc[]" as docs.RepoObject_PlantUml_FkRefList << V >> {
  **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_objectreflist_0_30.adoc[]" as docs.RepoObject_Plantuml_ObjectRefList_0_30 << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_objectreflist_1_1.adoc[]" as docs.RepoObject_Plantuml_ObjectRefList_1_1 << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_objectreflist_30_0.adoc[]" as docs.RepoObject_Plantuml_ObjectRefList_30_0 << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_pumlentityfklist.adoc[]" as docs.RepoObject_PlantUml_PumlEntityFkList << V >> {
  **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_t.adoc[]" as docs.RepoObject_Plantuml_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.schema_entitylist.adoc[]" as docs.Schema_EntityList << V >> {
  - **RepoObject_schema_name** : (nvarchar(128))
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.schema_puml.adoc[]" as docs.Schema_puml << V >> {
  - **RepoSchema_guid** : (uniqueidentifier)
  **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.schema_pumlpartial_fkreflist.adoc[]" as docs.Schema_PumlPartial_FkRefList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.schema_ssasrelationlist.adoc[]" as docs.Schema_SsasRelationList << V >> {
  - **SchemaName** : (nvarchar(128))
  **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.unit_1_union.adoc[]" as docs.Unit_1_union << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.unit_2.adoc[]" as docs.Unit_2 << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.unit_3.adoc[]" as docs.Unit_3 << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport.adoc[]" as docs.usp_AntoraExport << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_objectnavigation.adoc[]" as docs.usp_AntoraExport_ObjectNavigation << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_objectpage.adoc[]" as docs.usp_AntoraExport_ObjectPage << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_objectpartialscontent.adoc[]" as docs.usp_AntoraExport_ObjectPartialsContent << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_objectpuml.adoc[]" as docs.usp_AntoraExport_ObjectPuml << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_repoobject_adoc_t.adoc[]" as docs.usp_PERSIST_RepoObject_Adoc_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_repoobject_columnlist_t.adoc[]" as docs.usp_PERSIST_RepoObject_ColumnList_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_repoobject_indexlist_t.adoc[]" as docs.usp_PERSIST_RepoObject_IndexList_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_repoobject_outputfilter_t.adoc[]" as docs.usp_PERSIST_RepoObject_OutputFilter_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_repoobject_plantuml_entity_t.adoc[]" as docs.usp_PERSIST_RepoObject_Plantuml_Entity_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_repoobject_plantuml_t.adoc[]" as docs.usp_PERSIST_RepoObject_Plantuml_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:graph.repoobject_s.adoc[]" as graph.RepoObject_S << V >> {
  --
}

entity "puml-link:dhw:sqldb:graph.repoobjectcolumn_s.adoc[]" as graph.RepoObjectColumn_S << V >> {
  --
}

entity "puml-link:dhw:sqldb:property.extendedproperty_repo2sys_level0.adoc[]" as property.ExtendedProperty_Repo2Sys_level0 << V >> {
  --
}

entity "puml-link:dhw:sqldb:property.extendedproperty_repo2sys_level1.adoc[]" as property.ExtendedProperty_Repo2Sys_level1 << V >> {
  - **level0type** : (nvarchar(6))
  - **level0name** : (nvarchar(128))
  **level1type** : (varchar(9))
  - **level1name** : (nvarchar(128))
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.extendedproperty_repo2sys_level2_repoobject.adoc[]" as property.ExtendedProperty_Repo2Sys_level2_RepoObject << V >> {
  - **level0type** : (nvarchar(6))
  - **level0name** : (nvarchar(128))
  **level1type** : (varchar(9))
  - **level1name** : (nvarchar(128))
  **level2type** : (varchar(10))
  - **level2name** : (nvarchar(128))
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.extendedproperty_repo2sys_level2_repoobjectcolumn.adoc[]" as property.ExtendedProperty_Repo2Sys_level2_RepoObjectColumn << V >> {
  - **level0type** : (nvarchar(6))
  - **level0name** : (nvarchar(128))
  **level1type** : (varchar(9))
  - **level1name** : (nvarchar(128))
  - **level2type** : (nvarchar(6))
  - **level2name** : (nvarchar(128))
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.extendedproperty_repo2sys_level2_union.adoc[]" as property.ExtendedProperty_Repo2Sys_level2_Union << V >> {
  - **level0type** : (nvarchar(6))
  - **level0name** : (nvarchar(128))
  **level1type** : (varchar(9))
  - **level1name** : (nvarchar(128))
  **level2type** : (nvarchar(10))
  - **level2name** : (nvarchar(128))
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.fs_get_repoobjectcolumnproperty_nvarchar.adoc[]" as property.fs_get_RepoObjectColumnProperty_nvarchar << FN >> {
  --
}

entity "puml-link:dhw:sqldb:property.fs_get_repoobjectproperty_nvarchar.adoc[]" as property.fs_get_RepoObjectProperty_nvarchar << FN >> {
  --
}

entity "puml-link:dhw:sqldb:property.propertyname_repoobject.adoc[]" as property.PropertyName_RepoObject << V >> {
  **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.propertyname_repoobject_t.adoc[]" as property.PropertyName_RepoObject_T << U >> {
  **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.propertyname_repoobjectcolumn.adoc[]" as property.PropertyName_RepoObjectColumn << V >> {
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.propertyname_repoobjectcolumn_t.adoc[]" as property.PropertyName_RepoObjectColumn_T << U >> {
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectcolumnproperty.adoc[]" as property.RepoObjectColumnProperty << U >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectcolumnproperty_external_tgt.adoc[]" as property.RepoObjectColumnProperty_external_tgt << V >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectcolumnproperty_forupdate.adoc[]" as property.RepoObjectColumnProperty_ForUpdate << V >> {
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectcolumnproperty_inheritancetype_inheritancedefinition.adoc[]" as property.RepoObjectColumnProperty_InheritanceType_InheritanceDefinition << V >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectcolumnproperty_inheritancetype_resulting_inheritancedefinition.adoc[]" as property.RepoObjectColumnProperty_InheritanceType_resulting_InheritanceDefinition << V >> {
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectcolumnproperty_sys_repo.adoc[]" as property.RepoObjectColumnProperty_sys_repo << V >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  - **property_name** : (sysname)
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty.adoc[]" as property.RepoObjectProperty << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty_collect_source_rogross.adoc[]" as property.RepoObjectProperty_Collect_source_ROGross << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **property_name** : (varchar(39))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty_collect_source_sql_modules_definition.adoc[]" as property.RepoObjectProperty_Collect_source_sql_modules_definition << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty_collect_source_uspgenerator.adoc[]" as property.RepoObjectProperty_Collect_source_uspgenerator << V >> {
  **RepoObject_guid** : (uniqueidentifier)
  - **property_name** : (varchar(14))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty_cross.adoc[]" as property.RepoObjectProperty_cross << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty_external_tgt.adoc[]" as property.RepoObjectProperty_external_tgt << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty_forupdate.adoc[]" as property.RepoObjectProperty_ForUpdate << V >> {
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty_inheritancetype_inheritancedefinition.adoc[]" as property.RepoObjectProperty_InheritanceType_InheritanceDefinition << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty_inheritancetype_resulting_inheritancedefinition.adoc[]" as property.RepoObjectProperty_InheritanceType_resulting_InheritanceDefinition << V >> {
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty_selectedpropertyname_split.adoc[]" as property.RepoObjectProperty_SelectedPropertyName_split << V >> {
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty_sys_repo.adoc[]" as property.RepoObjectProperty_sys_repo << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **property_name** : (sysname)
  --
}

entity "puml-link:dhw:sqldb:property.usp_external_property_import.adoc[]" as property.usp_external_property_import << P >> {
  --
}

entity "puml-link:dhw:sqldb:property.usp_external_repoobjectproperty.adoc[]" as property.usp_external_RepoObjectProperty << P >> {
  --
}

entity "puml-link:dhw:sqldb:property.usp_measureproperty_set.adoc[]" as property.usp_MeasureProperty_set << P >> {
  --
}

entity "puml-link:dhw:sqldb:property.usp_persist_propertyname_repoobject_t.adoc[]" as property.usp_PERSIST_PropertyName_RepoObject_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:property.usp_persist_propertyname_repoobjectcolumn_t.adoc[]" as property.usp_PERSIST_PropertyName_RepoObjectColumn_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:property.usp_persist_repoobjectcolumnproperty_external_tgt.adoc[]" as property.usp_PERSIST_RepoObjectColumnProperty_external_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:property.usp_persist_repoobjectproperty_external_tgt.adoc[]" as property.usp_PERSIST_RepoObjectProperty_external_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:property.usp_repoobject_inheritance.adoc[]" as property.usp_RepoObject_Inheritance << P >> {
  --
}

entity "puml-link:dhw:sqldb:property.usp_repoobjectcolumn_inheritance.adoc[]" as property.usp_RepoObjectColumn_Inheritance << P >> {
  --
}

entity "puml-link:dhw:sqldb:property.usp_repoobjectcolumnproperty_set.adoc[]" as property.usp_RepoObjectColumnProperty_set << P >> {
  --
}

entity "puml-link:dhw:sqldb:property.usp_repoobjectproperty_collect.adoc[]" as property.usp_RepoObjectProperty_collect << P >> {
  --
}

entity "puml-link:dhw:sqldb:property.usp_repoobjectproperty_set.adoc[]" as property.usp_RepoObjectProperty_set << P >> {
  --
}

entity "puml-link:dhw:sqldb:property.usp_reposchemaproperty_set.adoc[]" as property.usp_RepoSchemaProperty_set << P >> {
  --
}

entity "puml-link:dhw:sqldb:property.usp_sync_extendedproperties_repo2sys_delete.adoc[]" as property.usp_sync_ExtendedProperties_Repo2Sys_Delete << P >> {
  --
}

entity "puml-link:dhw:sqldb:property.usp_sync_extendedproperties_repo2sys_insertupdate.adoc[]" as property.usp_sync_ExtendedProperties_Repo2Sys_InsertUpdate << P >> {
  --
}

entity "puml-link:dhw:sqldb:property.usp_sync_extendedproperties_sys2repo_insertupdate.adoc[]" as property.usp_sync_ExtendedProperties_Sys2Repo_InsertUpdate << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference.adoc[]" as reference.additional_Reference << U >> {
  # **tik_hash_c** : (nvarchar(32))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_database.adoc[]" as reference.additional_Reference_database << V >> {
  - **AntoraComponent** : (nvarchar(128))
  - **AntoraModule** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_database_t.adoc[]" as reference.additional_Reference_database_T << U >> {
  - **AntoraComponent** : (nvarchar(128))
  - **AntoraModule** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_from_properties_src.adoc[]" as reference.additional_Reference_from_properties_src << V >> {
  **referenced_AntoraComponent** : (nvarchar(max))
  **referenced_AntoraModule** : (nvarchar(max))
  **referenced_Schema** : (nvarchar(max))
  **referenced_Object** : (nvarchar(max))
  **referenced_Column** : (nvarchar(max))
  **referencing_AntoraComponent** : (nvarchar(max))
  **referencing_AntoraModule** : (nvarchar(max))
  **referencing_Schema** : (nvarchar(max))
  **referencing_Object** : (nvarchar(max))
  **referencing_Column** : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_from_properties_tgt.adoc[]" as reference.additional_Reference_from_properties_tgt << V >> {
  **referenced_AntoraComponent** : (nvarchar(max))
  **referenced_AntoraModule** : (nvarchar(max))
  **referenced_Schema** : (nvarchar(max))
  **referenced_Object** : (nvarchar(max))
  **referenced_Column** : (nvarchar(max))
  **referencing_AntoraComponent** : (nvarchar(max))
  **referencing_AntoraModule** : (nvarchar(max))
  **referencing_Schema** : (nvarchar(max))
  **referencing_Object** : (nvarchar(max))
  **referencing_Column** : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_guid.adoc[]" as reference.additional_Reference_guid << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_is_external.adoc[]" as reference.additional_Reference_is_external << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_object.adoc[]" as reference.additional_Reference_Object << V >> {
  - **AntoraComponent** : (nvarchar(128))
  - **AntoraModule** : (nvarchar(128))
  - **SchemaName** : (nvarchar(128))
  - **ObjectName** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_object_t.adoc[]" as reference.additional_Reference_Object_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_objectcolumn.adoc[]" as reference.additional_Reference_ObjectColumn << V >> {
  - **AntoraComponent** : (nvarchar(128))
  - **AntoraModule** : (nvarchar(128))
  - **SchemaName** : (nvarchar(128))
  - **ObjectName** : (nvarchar(128))
  **ColumnName** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_objectcolumn_t.adoc[]" as reference.additional_Reference_ObjectColumn_T << U >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_wo_columns_from_properties_src.adoc[]" as reference.additional_Reference_wo_columns_from_properties_src << V >> {
  **referenced_AntoraComponent** : (nvarchar(max))
  **referenced_AntoraModule** : (nvarchar(max))
  **referenced_Schema** : (nvarchar(max))
  **referenced_Object** : (nvarchar(max))
  **referencing_AntoraComponent** : (nvarchar(max))
  **referencing_AntoraModule** : (nvarchar(max))
  **referencing_Schema** : (nvarchar(max))
  **referencing_Object** : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_wo_columns_from_properties_tgt.adoc[]" as reference.additional_Reference_wo_columns_from_properties_tgt << V >> {
  **referenced_AntoraComponent** : (nvarchar(max))
  **referenced_AntoraModule** : (nvarchar(max))
  **referenced_Schema** : (nvarchar(max))
  **referenced_Object** : (nvarchar(max))
  **referencing_AntoraComponent** : (nvarchar(max))
  **referencing_AntoraModule** : (nvarchar(max))
  **referencing_Schema** : (nvarchar(max))
  **referencing_Object** : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:reference.ftv_repoobject_columreferencerepoobject.adoc[]" as reference.ftv_RepoObject_ColumReferenceRepoObject << IF >> {
  --
}

entity "puml-link:dhw:sqldb:reference.ftv_repoobject_dbmlcolumnrelation.adoc[]" as reference.ftv_RepoObject_DbmlColumnRelation << IF >> {
  --
}

entity "puml-link:dhw:sqldb:reference.ftv_repoobject_referencetree.adoc[]" as reference.ftv_RepoObject_ReferenceTree << IF >> {
  --
}

entity "puml-link:dhw:sqldb:reference.ftv_repoobject_referencetree_referenced.adoc[]" as reference.ftv_RepoObject_ReferenceTree_referenced << IF >> {
  --
}

entity "puml-link:dhw:sqldb:reference.ftv_repoobject_referencetree_referencing.adoc[]" as reference.ftv_RepoObject_ReferenceTree_referencing << IF >> {
  --
}

entity "puml-link:dhw:sqldb:reference.ftv_repoobject_referencetree_via_fullname.adoc[]" as reference.ftv_RepoObject_ReferenceTree_via_fullname << IF >> {
  --
}

entity "puml-link:dhw:sqldb:reference.ftv_repoobjectcolumn_referencetree.adoc[]" as reference.ftv_RepoObjectColumn_ReferenceTree << IF >> {
  --
}

entity "puml-link:dhw:sqldb:reference.persistence.adoc[]" as reference.Persistence << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.persistence_bidirectional.adoc[]" as reference.Persistence_bidirectional << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.referencetree_cyclic_ref_persistenceusp.adoc[]" as reference.ReferenceTree_cyclic_ref_PersistenceUsp << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.referencetree_cyclic_union.adoc[]" as reference.ReferenceTree_cyclic_union << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_reference.adoc[]" as reference.RepoObject_reference << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_reference_additional.adoc[]" as reference.RepoObject_reference_additional << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_reference_additional_internal.adoc[]" as reference.RepoObject_reference_additional_internal << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_reference_persistence.adoc[]" as reference.RepoObject_reference_persistence << V >> {
  **referenced_RepoObject_guid** : (uniqueidentifier)
  - **referencing_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_reference_persistence_target_as_source.adoc[]" as reference.RepoObject_reference_persistence_target_as_source << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_reference_persistence_target_as_source_explicit.adoc[]" as reference.RepoObject_reference_persistence_target_as_source_explicit << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_reference_sqlexpressiondependencies.adoc[]" as reference.RepoObject_reference_SqlExpressionDependencies << V >> {
  **referenced_RepoObject_guid** : (uniqueidentifier)
  **referencing_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_reference_t.adoc[]" as reference.RepoObject_reference_T << U >> {
  **referenced_RepoObject_guid** : (uniqueidentifier)
  **referencing_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_reference_t_bidirectional.adoc[]" as reference.RepoObject_reference_T_bidirectional << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_reference_union.adoc[]" as reference.RepoObject_reference_union << V >> {
  **referenced_RepoObject_guid** : (uniqueidentifier)
  **referencing_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_reference_virtual.adoc[]" as reference.RepoObject_reference_virtual << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_referencedlist.adoc[]" as reference.RepoObject_ReferencedList << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_referencedreferencing.adoc[]" as reference.RepoObject_ReferencedReferencing << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_referencetree_0_30.adoc[]" as reference.RepoObject_ReferenceTree_0_30 << V >> {
  **RepoObject_guid** : (uniqueidentifier)
  **Referencing_guid** : (uniqueidentifier)
  **Referenced_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_referencetree_0_30_t.adoc[]" as reference.RepoObject_ReferenceTree_0_30_T << U >> {
  **RepoObject_guid** : (uniqueidentifier)
  **Referencing_guid** : (uniqueidentifier)
  **Referenced_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_referencetree_30_0.adoc[]" as reference.RepoObject_ReferenceTree_30_0 << V >> {
  **RepoObject_guid** : (uniqueidentifier)
  **Referencing_guid** : (uniqueidentifier)
  **Referenced_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_referencetree_30_0_t.adoc[]" as reference.RepoObject_ReferenceTree_30_0_T << U >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_referencetree_referenced.adoc[]" as reference.RepoObject_ReferenceTree_referenced << V >> {
  **RepoObject_guid** : (uniqueidentifier)
  **Referenced_Depth** : (int)
  **Referencing_Depth** : (int)
  **Referenced_guid** : (uniqueidentifier)
  **Referencing_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_referencetree_referenced_30_0.adoc[]" as reference.RepoObject_ReferenceTree_referenced_30_0 << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  **Referenced_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_referencetree_referencing.adoc[]" as reference.RepoObject_ReferenceTree_referencing << V >> {
  **RepoObject_guid** : (uniqueidentifier)
  **Referenced_Depth** : (int)
  **Referencing_Depth** : (int)
  **Referenced_guid** : (uniqueidentifier)
  **Referencing_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_referencetree_referencing_0_30.adoc[]" as reference.RepoObject_ReferenceTree_referencing_0_30 << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  **Referencing_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_referencinglist.adoc[]" as reference.RepoObject_ReferencingList << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_reference.adoc[]" as reference.RepoObjectColumn_reference << V >> {
  **referenced_RepoObjectColumn_guid** : (uniqueidentifier)
  **referencing_RepoObjectColumn_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_reference_additional.adoc[]" as reference.RepoObjectColumn_reference_additional << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_reference_additional_internal.adoc[]" as reference.RepoObjectColumn_reference_additional_internal << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_reference_bysamepredecessors.adoc[]" as reference.RepoObjectColumn_reference_BySamePredecessors << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_reference_firstresultset.adoc[]" as reference.RepoObjectColumn_reference_FirstResultSet << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_reference_persistence.adoc[]" as reference.RepoObjectColumn_reference_Persistence << V >> {
  **referencing_id** : (int)
  **referencing_minor_id** : (int)
  **referenced_id** : (int)
  **referenced_minor_id** : (int)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_reference_queryplan.adoc[]" as reference.RepoObjectColumn_reference_QueryPlan << V >> {
  **referencing_id** : (int)
  **referencing_minor_id** : (int)
  **referenced_id** : (int)
  **referenced_minor_id** : (int)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_reference_sqlexpressiondependencies.adoc[]" as reference.RepoObjectColumn_reference_SqlExpressionDependencies << V >> {
  - **referencing_id** : (int)
  - **referencing_minor_id** : (int)
  **referenced_id** : (int)
  - **referenced_minor_id** : (int)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_reference_sqlmodules.adoc[]" as reference.RepoObjectColumn_reference_SqlModules << V >> {
  **referencing_id** : (int)
  **referencing_minor_id** : (int)
  **referenced_id** : (int)
  **referenced_minor_id** : (int)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_reference_t.adoc[]" as reference.RepoObjectColumn_reference_T << U >> {
  **referenced_RepoObjectColumn_guid** : (uniqueidentifier)
  **referencing_RepoObjectColumn_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_reference_union.adoc[]" as reference.RepoObjectColumn_reference_union << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_reference_virtual.adoc[]" as reference.RepoObjectColumn_reference_virtual << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_referencedlist.adoc[]" as reference.RepoObjectColumn_ReferencedList << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_referencedreferencing.adoc[]" as reference.RepoObjectColumn_ReferencedReferencing << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_referencetree.adoc[]" as reference.RepoObjectColumn_ReferenceTree << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_referencinglist.adoc[]" as reference.RepoObjectColumn_ReferencingList << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_relationscript.adoc[]" as reference.RepoObjectColumn_RelationScript << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.sysobjectcolumn_queryplanexpression.adoc[]" as reference.SysObjectColumn_QueryPlanExpression << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_additional_reference.adoc[]" as reference.usp_additional_Reference << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_persist_additional_reference_database_t.adoc[]" as reference.usp_PERSIST_additional_Reference_database_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_persist_additional_reference_from_properties_tgt.adoc[]" as reference.usp_PERSIST_additional_Reference_from_properties_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_persist_additional_reference_object_t.adoc[]" as reference.usp_PERSIST_additional_Reference_Object_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_persist_additional_reference_objectcolumn_t.adoc[]" as reference.usp_PERSIST_additional_Reference_ObjectColumn_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_persist_additional_reference_wo_columns_from_properties_tgt.adoc[]" as reference.usp_PERSIST_additional_Reference_wo_columns_from_properties_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_persist_repoobject_reference_t.adoc[]" as reference.usp_PERSIST_RepoObject_reference_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_persist_repoobject_referencetree_0_30_t.adoc[]" as reference.usp_PERSIST_RepoObject_ReferenceTree_0_30_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_persist_repoobject_referencetree_30_0_t.adoc[]" as reference.usp_PERSIST_RepoObject_ReferenceTree_30_0_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_persist_repoobjectcolumn_reference_t.adoc[]" as reference.usp_PERSIST_RepoObjectColumn_reference_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_repoobject_referencetree.adoc[]" as reference.usp_RepoObject_ReferenceTree << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_repoobject_referencetree_insert.adoc[]" as reference.usp_RepoObject_ReferenceTree_insert << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_repoobject_update_sysobjectqueryplan.adoc[]" as reference.usp_RepoObject_update_SysObjectQueryPlan << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_repoobjectcolumnsource_virtual_set.adoc[]" as reference.usp_RepoObjectColumnSource_virtual_set << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_repoobjectsource_firstresultset.adoc[]" as reference.usp_RepoObjectSource_FirstResultSet << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_repoobjectsource_queryplan.adoc[]" as reference.usp_RepoObjectSource_QueryPlan << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_repoobjectsource_virtual_set.adoc[]" as reference.usp_RepoObjectSource_virtual_set << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_update_referencing_count.adoc[]" as reference.usp_update_Referencing_Count << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.check_indexcolumn_virtual_referenced_setpoint.adoc[]" as repo.check_IndexColumn_virtual_referenced_setpoint << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.foreignkey_gross.adoc[]" as repo.ForeignKey_gross << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.foreignkey_indexes.adoc[]" as repo.ForeignKey_Indexes << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.foreignkey_indexes_union.adoc[]" as repo.ForeignKey_Indexes_union << V >> {
  **ForeignKey_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.foreignkey_indexes_union_t.adoc[]" as repo.ForeignKey_Indexes_union_T << U >> {
  **ForeignKey_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.foreignkey_indexpattern.adoc[]" as repo.ForeignKey_IndexPattern << V >> {
  - **constraint_object_id** : (int)
  **ForeignKey_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.foreignkey_virtual_indexes.adoc[]" as repo.ForeignKey_virtual_Indexes << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.fs_repoobject_fullname2.adoc[]" as repo.fs_RepoObject_fullname2 << FN >> {
  --
}

entity "puml-link:dhw:sqldb:repo.index_columlist.adoc[]" as repo.Index_ColumList << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.index_columlist_t.adoc[]" as repo.Index_ColumList_T << U >> {
  - **index_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.index_gross.adoc[]" as repo.Index_gross << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.index_indexpattern.adoc[]" as repo.Index_IndexPattern << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.index_referencing_indexpatterncolumnguid.adoc[]" as repo.Index_referencing_IndexPatternColumnGuid << V >> {
  **source_index_guid** : (uniqueidentifier)
  **referencing_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.index_settings_forupdate.adoc[]" as repo.Index_Settings_ForUpdate << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.index_sqlconstraint_pkuq.adoc[]" as repo.Index_SqlConstraint_PkUq << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.index_union.adoc[]" as repo.Index_union << V >> {
  **index_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.index_unique_indexpatterncolumnguid.adoc[]" as repo.Index_unique_IndexPatternColumnGuid << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.index_virtual_forupdate.adoc[]" as repo.Index_virtual_ForUpdate << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.index_virtual_sysobject.adoc[]" as repo.Index_virtual_SysObject << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.indexcolumn_referencedreferencing_hasfullcolumnsinreferencing.adoc[]" as repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing << V >> {
  - **index_guid** : (uniqueidentifier)
  - **index_column_id** : (int)
  **RowNumberInReferencing** : (bigint)
  --
}

entity "puml-link:dhw:sqldb:repo.indexcolumn_referencedreferencing_hasfullcolumnsinreferencing_check.adoc[]" as repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_check << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.indexcolumn_referencedreferencing_hasfullcolumnsinreferencing_t.adoc[]" as repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T << U >> {
  **index_guid** : (uniqueidentifier)
  - **index_column_id** : (int)
  **RowNumberInReferencing** : (bigint)
  --
}

entity "puml-link:dhw:sqldb:repo.indexcolumn_ssas_gross.adoc[]" as repo.IndexColumn_ssas_gross << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.indexcolumn_union.adoc[]" as repo.IndexColumn_union << V >> {
  **index_guid** : (uniqueidentifier)
  - **index_column_id** : (int)
  --
}

entity "puml-link:dhw:sqldb:repo.indexcolumn_union_t.adoc[]" as repo.IndexColumn_union_T << U >> {
  **index_guid** : (uniqueidentifier)
  - **index_column_id** : (int)
  --
}

entity "puml-link:dhw:sqldb:repo.indexcolumn_virtual_gross.adoc[]" as repo.IndexColumn_virtual_gross << V >> {
  - **index_column_id** : (int)
  --
}

entity "puml-link:dhw:sqldb:repo.indexcolumn_virtual_referenced_setpoint.adoc[]" as repo.IndexColumn_virtual_referenced_setpoint << V >> {
  - **index_guid** : (uniqueidentifier)
  - **index_column_id** : (int)
  --
}

entity "puml-link:dhw:sqldb:repo.indexreferencedreferencing.adoc[]" as repo.IndexReferencedReferencing << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.indexreferencedreferencing_hasfullcolumnsinreferencing.adoc[]" as repo.IndexReferencedReferencing_HasFullColumnsInReferencing << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.measure.adoc[]" as repo.Measure << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.measure_union.adoc[]" as repo.Measure_union << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject.adoc[]" as repo.RepoObject << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject__after_update.adoc[]" as repo.RepoObject__after_update << TR >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_columnlist.adoc[]" as repo.RepoObject_ColumnList << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_external_src.adoc[]" as repo.RepoObject_external_src << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_external_tgt.adoc[]" as repo.RepoObject_external_tgt << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_fullname_u_v.adoc[]" as repo.RepoObject_fullname_u_v << V >> {
  - **RepoObject_fullname** : (nvarchar(261))
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_gross.adoc[]" as repo.RepoObject_gross << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_gross_persistence.adoc[]" as repo.RepoObject_gross_persistence << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_gross2.adoc[]" as repo.RepoObject_gross2 << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_persistence_column.adoc[]" as repo.RepoObject_persistence_column << V >> {
  - **target_RepoObject_guid** : (uniqueidentifier)
  **RepoObjectColumn_guid_s** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_persistence_forupdate.adoc[]" as repo.RepoObject_persistence_ForUpdate << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_persistence_nocomparebutupdate.adoc[]" as repo.RepoObject_persistence_NoCompareButUpdate << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_persistence_nocomparenoupdate.adoc[]" as repo.RepoObject_persistence_NoCompareNoUpdate << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_persistence_objectnames.adoc[]" as repo.RepoObject_persistence_ObjectNames << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_persistence_source_ignore.adoc[]" as repo.RepoObject_persistence_source_Ignore << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_persistence_sourcemismatch.adoc[]" as repo.RepoObject_persistence_SourceMismatch << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_persistence_target_ignore.adoc[]" as repo.RepoObject_persistence_target_Ignore << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_related_fk_union.adoc[]" as repo.RepoObject_related_FK_union << V >> {
  **RepoObject_guid** : (uniqueidentifier)
  **included_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_requiredrepoobjectmerge.adoc[]" as repo.RepoObject_RequiredRepoObjectMerge << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_sat2.adoc[]" as repo.RepoObject_sat2 << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_sat2_t.adoc[]" as repo.RepoObject_sat2_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_sqlcreatetable.adoc[]" as repo.RepoObject_SqlCreateTable << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_ssas_src.adoc[]" as repo.RepoObject_SSAS_src << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_ssas_tgt.adoc[]" as repo.RepoObject_SSAS_tgt << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_wo_referencing.adoc[]" as repo.RepoObject_wo_referencing << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn.adoc[]" as repo.RepoObjectColumn << U >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn_external_src.adoc[]" as repo.RepoObjectColumn_external_src << V >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn_external_tgt.adoc[]" as repo.RepoObjectColumn_external_tgt << V >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn_gross.adoc[]" as repo.RepoObjectColumn_gross << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn_gross2.adoc[]" as repo.RepoObjectColumn_gross2 << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn_missingsource_typev.adoc[]" as repo.RepoObjectColumn_MissingSource_TypeV << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn_requiredrepoobjectcolumnmerge.adoc[]" as repo.RepoObjectColumn_RequiredRepoObjectColumnMerge << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn_ssas_tgt.adoc[]" as repo.RepoObjectColumn_SSAS_tgt << V >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.reposchema.adoc[]" as repo.RepoSchema << U >> {
  - **RepoSchema_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.reposchema_ssas_src.adoc[]" as repo.RepoSchema_ssas_src << V >> {
  - **RepoSchema_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:repo.reposchema_ssas_tgt.adoc[]" as repo.RepoSchema_ssas_tgt << V >> {
  - **RepoSchema_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.syscolumn_repoobjectcolumn_via_guid.adoc[]" as repo.SysColumn_RepoObjectColumn_via_guid << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.syscolumn_repoobjectcolumn_via_name.adoc[]" as repo.SysColumn_RepoObjectColumn_via_name << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.sysobject_repoobject_via_guid.adoc[]" as repo.SysObject_RepoObject_via_guid << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.sysobject_repoobject_via_name.adoc[]" as repo.SysObject_RepoObject_via_name << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.sysschema_reposchema_via_guid.adoc[]" as repo.SysSchema_RepoSchema_via_guid << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.sysschema_reposchema_via_name.adoc[]" as repo.SysSchema_RepoSchema_via_name << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_index_finish.adoc[]" as repo.usp_Index_finish << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_index_foreignkey.adoc[]" as repo.usp_Index_ForeignKey << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_index_inheritance.adoc[]" as repo.usp_index_inheritance << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_index_settings.adoc[]" as repo.usp_Index_Settings << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_index_virtual_set.adoc[]" as repo.usp_Index_virtual_set << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_main.adoc[]" as repo.usp_main << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_persist_foreignkey_indexes_union_t.adoc[]" as repo.usp_PERSIST_ForeignKey_Indexes_union_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_persist_index_columlist_t.adoc[]" as repo.usp_PERSIST_Index_ColumList_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_persist_indexcolumn_referencedreferencing_hasfullcolumnsinreferencing_t.adoc[]" as repo.usp_PERSIST_IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_persist_indexcolumn_union_t.adoc[]" as repo.usp_PERSIST_IndexColumn_union_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_persist_repoobject_external_tgt.adoc[]" as repo.usp_PERSIST_RepoObject_external_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_persist_repoobject_sat2_t.adoc[]" as repo.usp_PERSIST_RepoObject_sat2_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_persist_repoobject_ssas_tgt.adoc[]" as repo.usp_PERSIST_RepoObject_SSAS_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_persist_repoobjectcolumn_external_tgt.adoc[]" as repo.usp_PERSIST_RepoObjectColumn_external_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_persist_repoobjectcolumn_ssas_tgt.adoc[]" as repo.usp_PERSIST_RepoObjectColumn_SSAS_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_persist_reposchema_ssas_tgt.adoc[]" as repo.usp_PERSIST_RepoSchema_ssas_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_persistence_delete.adoc[]" as repo.usp_persistence_delete << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_persistence_set.adoc[]" as repo.usp_persistence_set << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_sync_guid.adoc[]" as repo.usp_sync_guid << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_sync_guid_repoobject.adoc[]" as repo.usp_sync_guid_RepoObject << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_sync_guid_repoobjectcolumn.adoc[]" as repo.usp_sync_guid_RepoObjectColumn << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_sync_guid_reposchema.adoc[]" as repo.usp_sync_guid_RepoSchema << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_sync_guid_ssas.adoc[]" as repo.usp_sync_guid_ssas << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_update_referencing_count.adoc[]" as repo.usp_update_Referencing_Count << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo_sys.foreignkey.adoc[]" as repo_sys.ForeignKey << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo_sys.foreignkeycolumn.adoc[]" as repo_sys.ForeignKeyColumn << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo_sys.index_unique.adoc[]" as repo_sys.Index_unique << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo_sys.indexcolumn_unique.adoc[]" as repo_sys.IndexColumn_unique << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo_sys.repoobjectreferenced.adoc[]" as repo_sys.RepoObjectReferenced << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo_sys.repoobjectreferencing.adoc[]" as repo_sys.RepoObjectReferencing << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo_sys.sql_expression_dependencies.adoc[]" as repo_sys.sql_expression_dependencies << V >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_10_statement.adoc[]" as sqlparse.RepoObject_SqlModules_10_statement << V >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_20_statement_children.adoc[]" as sqlparse.RepoObject_SqlModules_20_statement_children << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **json_key** : (nvarchar(4000))
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_21_statement_children_helper.adoc[]" as sqlparse.RepoObject_SqlModules_21_statement_children_helper << V >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_22_identifier_alias_as.adoc[]" as sqlparse.RepoObject_SqlModules_22_identifier_alias_AS << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **json_key** : (nvarchar(4000))
  **RowNumber** : (bigint)
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_23_normalized_wo_nolock.adoc[]" as sqlparse.RepoObject_SqlModules_23_normalized_wo_nolock << V >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_24_identifierlist_children.adoc[]" as sqlparse.RepoObject_SqlModules_24_IdentifierList_children << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **json_key** : (nvarchar(4000))
  - **T2_json_key** : (nvarchar(4000))
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_25_identifierlist_children_identifiersplit.adoc[]" as sqlparse.RepoObject_SqlModules_25_IdentifierList_children_IdentifierSplit << V >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_26_identifierlist_children_identifiersplit_quotename.adoc[]" as sqlparse.RepoObject_SqlModules_26_IdentifierList_children_IdentifierSplit_QuoteName << V >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_29_1_object_is_union.adoc[]" as sqlparse.RepoObject_SqlModules_29_1_object_is_union << V >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_29_2_object_is_groupby.adoc[]" as sqlparse.RepoObject_SqlModules_29_2_object_is_GroupBy << V >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_31_object.adoc[]" as sqlparse.RepoObject_SqlModules_31_object << V >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_32_objectclass.adoc[]" as sqlparse.RepoObject_SqlModules_32_ObjectClass << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  **class** : (nvarchar(500))
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_33_objectnormalized.adoc[]" as sqlparse.RepoObject_SqlModules_33_ObjectNormalized << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  **normalized** : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_39_object.adoc[]" as sqlparse.RepoObject_SqlModules_39_object << V >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_41_from.adoc[]" as sqlparse.RepoObject_SqlModules_41_from << V >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_41_from_t.adoc[]" as sqlparse.RepoObject_SqlModules_41_from_T << U >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_42_from_identifier.adoc[]" as sqlparse.RepoObject_SqlModules_42_from_Identifier << V >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_43_from_identifier.adoc[]" as sqlparse.RepoObject_SqlModules_43_from_Identifier << V >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_44_from_identifier_quotename.adoc[]" as sqlparse.RepoObject_SqlModules_44_from_Identifier_QuoteName << V >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_51_identitfier.adoc[]" as sqlparse.RepoObject_SqlModules_51_Identitfier << V >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_52_identitfier_quotename.adoc[]" as sqlparse.RepoObject_SqlModules_52_Identitfier_QuoteName << V >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_61_selectidentifier_union.adoc[]" as sqlparse.RepoObject_SqlModules_61_SelectIdentifier_Union << V >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_61_selectidentifier_union_t.adoc[]" as sqlparse.RepoObject_SqlModules_61_SelectIdentifier_Union_T << U >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_71_reference_explicitetablealias.adoc[]" as sqlparse.RepoObject_SqlModules_71_reference_ExpliciteTableAlias << V >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_72_reference_notablealias.adoc[]" as sqlparse.RepoObject_SqlModules_72_reference_NoTableAlias << V >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_79_reference_union.adoc[]" as sqlparse.RepoObject_SqlModules_79_reference_union << V >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_identitfier.adoc[]" as sqlparse.RepoObject_SqlModules_Identitfier << V >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.repoobject_sqlmodules_repo_sys.adoc[]" as sqlparse.RepoObject_SqlModules_Repo_Sys << V >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.usp_persist_repoobject_sqlmodules_41_from_t.adoc[]" as sqlparse.usp_PERSIST_RepoObject_SqlModules_41_from_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.usp_persist_repoobject_sqlmodules_61_selectidentifier_union_t.adoc[]" as sqlparse.usp_PERSIST_RepoObject_SqlModules_61_SelectIdentifier_Union_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:sqlparse.usp_sqlparse.adoc[]" as sqlparse.usp_sqlparse << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.measure_translation.adoc[]" as ssas.Measure_translation << V >> {
  - **Measure_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  **RepoObject_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.measure_translation_displayfolder_union.adoc[]" as ssas.Measure_translation_displayfolder_union << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.measure_translation_t.adoc[]" as ssas.Measure_translation_T << U >> {
  - **Measure_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  **RepoObject_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_201_descriptions_multiline.adoc[]" as ssas.model_json_201_descriptions_multiline << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_2011_descriptions_stragg.adoc[]" as ssas.model_json_2011_descriptions_StrAgg << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.repoobjectcolumn_translation.adoc[]" as ssas.RepoObjectColumn_translation << V >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:ssas.repoobjectcolumn_translation_displayfolder_union.adoc[]" as ssas.RepoObjectColumn_translation_displayfolder_union << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.repoobjectcolumn_translation_t.adoc[]" as ssas.RepoObjectColumn_translation_T << U >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:ssas.usp_persist_measure_translation_t.adoc[]" as ssas.usp_PERSIST_Measure_translation_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.usp_persist_repoobjectcolumn_translation_t.adoc[]" as ssas.usp_PERSIST_RepoObjectColumn_translation_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.generatorusp_check_persistence.adoc[]" as uspgenerator.GeneratorUsp_check_persistence << V >> {
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.generatorusp_sqlusp.adoc[]" as uspgenerator.GeneratorUsp_SqlUsp << V >> {
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.generatoruspstep_persistence_isinactive_setpoint.adoc[]" as uspgenerator.GeneratorUspStep_Persistence_IsInactive_setpoint << V >> {
  - **usp_id** : (int)
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.generatoruspstep_persistence_src.adoc[]" as uspgenerator.GeneratorUspStep_Persistence_src << V >> {
  - **usp_id** : (int)
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.usp_generatorusp_insert_update_persistence.adoc[]" as uspgenerator.usp_GeneratorUsp_insert_update_persistence << P >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.biml_package.adoc[]" as workflow.Biml_Package << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.biml_precedenceconstraints.adoc[]" as workflow.Biml_PrecedenceConstraints << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.biml_project.adoc[]" as workflow.Biml_Project << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.biml_task.adoc[]" as workflow.Biml_Task << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.proceduredependency.adoc[]" as workflow.ProcedureDependency << U >> {
  - **id** : (int)
  --
}

entity "puml-link:dhw:sqldb:workflow.proceduredependency_gross.adoc[]" as workflow.ProcedureDependency_gross << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.proceduredependency_input_persistencedependency.adoc[]" as workflow.ProcedureDependency_input_PersistenceDependency << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.proceduredependency_input_persistencedependency_s.adoc[]" as workflow.ProcedureDependency_input_PersistenceDependency_S << V >> {
  **referenced_Procedure_RepoObject_guid** : (uniqueidentifier)
  **referencing_Procedure_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:workflow.proceduredependency_persistencedependency_src.adoc[]" as workflow.ProcedureDependency_PersistenceDependency_src << V >> {
  **referenced_Procedure_RepoObject_guid** : (uniqueidentifier)
  **referencing_Procedure_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:workflow.proceduredependency_persistencedependency_tgt.adoc[]" as workflow.ProcedureDependency_PersistenceDependency_tgt << V >> {
  **referenced_Procedure_RepoObject_guid** : (uniqueidentifier)
  **referencing_Procedure_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:workflow.usp_persist_proceduredependency_persistencedependency_tgt.adoc[]" as workflow.usp_PERSIST_ProcedureDependency_PersistenceDependency_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.usp_persist_workflow_proceduredependency_t.adoc[]" as workflow.usp_PERSIST_Workflow_ProcedureDependency_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.usp_persist_workflowstep.adoc[]" as workflow.usp_PERSIST_WorkflowStep << P >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.usp_workflow.adoc[]" as workflow.usp_workflow << P >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.workflow_proceduredependency.adoc[]" as workflow.Workflow_ProcedureDependency << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.workflow_proceduredependency_all.adoc[]" as workflow.Workflow_ProcedureDependency_all << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.workflow_proceduredependency_t.adoc[]" as workflow.Workflow_ProcedureDependency_T << U >> {
  - **Workflow_id** : (int)
  - **referenced_Procedure_RepoObject_guid** : (uniqueidentifier)
  - **referencing_Procedure_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:workflow.workflow_proceduredependency_t_active.adoc[]" as workflow.Workflow_ProcedureDependency_T_active << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.workflow_proceduredependency_t_bidirectional.adoc[]" as workflow.Workflow_ProcedureDependency_T_bidirectional << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.workflow_proceduredependency_t_bidirectional_t.adoc[]" as workflow.Workflow_ProcedureDependency_T_bidirectional_T << U >> {
  - **Workflow_id** : (int)
  - **referenced_Procedure_RepoObject_guid** : (uniqueidentifier)
  - **referencing_Procedure_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:workflow.workflow_proceduredependency_t_notinsortorder.adoc[]" as workflow.Workflow_ProcedureDependency_T_NotInSortorder << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.workflow_proceduredependency_t_notinsortorder_check.adoc[]" as workflow.Workflow_ProcedureDependency_T_NotInSortorder_check << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.workflow_proceduredependency_t_redundant.adoc[]" as workflow.Workflow_ProcedureDependency_T_redundant << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.workflow_proceduredependency_t_taskname.adoc[]" as workflow.Workflow_ProcedureDependency_T_TaskName << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.workflow_proceduredependency_wo_redundant.adoc[]" as workflow.Workflow_ProcedureDependency_wo_redundant << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.workflow_sqlusp.adoc[]" as workflow.Workflow_SqlUsp << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.workflow_usplist.adoc[]" as workflow.Workflow_UspList << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.workflowstep.adoc[]" as workflow.WorkflowStep << U >> {
  - **id** : (int)
  --
}

entity "puml-link:dhw:sqldb:workflow.workflowstep_active.adoc[]" as workflow.WorkflowStep_active << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.workflowstep_forupdate.adoc[]" as workflow.WorkflowStep_ForUpdate << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.workflowstep_src.adoc[]" as workflow.WorkflowStep_src << V >> {
  - **Workflow_id** : (int)
  **Procedure_RepoObject_guid** : (uniqueidentifier)
  --
}

docs.AntoraNavListPage_by_type <.. docs.usp_AntoraExport_ObjectNavigation
docs.AntoraNavListRepoObject_by_schema <.. docs.usp_AntoraExport_ObjectNavigation
docs.AntoraNavListRepoObject_by_schema <.. docs.AntoraPage_ObjectBySchema
docs.AntoraNavListRepoObject_by_schema_type <.. docs.usp_AntoraExport_ObjectNavigation
docs.AntoraNavListRepoObject_by_type <.. docs.usp_AntoraExport_ObjectNavigation
docs.AntoraNavListRepoObject_by_type <.. docs.AntoraPage_ObjectByType
docs.ftv_RepoObject_AntoraXref <.. docs.RepoObject_AntoraXrefCulturesList
docs.ftv_RepoObject_Reference_PlantUml_EntityRefList <.. docs.RepoObject_Plantuml
docs.IndexSemanticgroup <.. docs.AntoraPage_IndexSemanticGroup
docs.IndexSemanticgroupPatterndatatype <.. docs.IndexSemanticgroup
docs.Measure_MeasurePropertyList <.. docs.RepoObject_MeasureList
docs.ObjectRefCyclic_EntityList <.. docs.ObjectRefCyclic
docs.ObjectRefCyclic_ObjectRefList <.. docs.ObjectRefCyclic
docs.RepoObject_Adoc <.. docs.usp_PERSIST_RepoObject_Adoc_T
docs.RepoObject_Adoc <.. docs.RepoObject_Adoc_T
docs.REpoObject_Adoc_T <.. docs.usp_PERSIST_RepoObject_Adoc_T
docs.RepoObject_AntoraXrefCulturesList <.. docs.RepoObject_Adoc
docs.RepoObject_ColumnList <.. docs.RepoObject_ColumnList_T
docs.RepoObject_ColumnList <.. docs.usp_PERSIST_RepoObject_ColumnList_T
docs.RepoObject_ColumnList_T <.. docs.RepoObject_Adoc
docs.RepoObject_ColumnList_T <.. docs.RepoObject_Plantuml_Entity
docs.RepoObject_ColumnList_T <.. docs.usp_PERSIST_RepoObject_ColumnList_T
docs.RepoObject_IndexList <.. docs.usp_PERSIST_RepoObject_IndexList_T
docs.RepoObject_IndexList <.. docs.RepoObject_IndexList_T
docs.RepoObject_IndexList_T <.. docs.usp_PERSIST_RepoObject_IndexList_T
docs.RepoObject_IndexList_T <.. docs.RepoObject_Adoc
docs.RepoObject_IndexList_T <.. docs.RepoObject_Plantuml_Entity
docs.RepoObject_MeasureDescriptionList <.. docs.RepoObject_Adoc
docs.RepoObject_MeasureList <.. docs.RepoObject_Plantuml_Entity
docs.RepoObject_MeasureList <.. docs.RepoObject_Adoc
docs.RepoObject_OutputFilter <.. docs.RepoObject_OutputFilter_T
docs.RepoObject_OutputFilter <.. docs.usp_PERSIST_RepoObject_OutputFilter_T
docs.RepoObject_OutputFilter_T <.. docs.RepoObject_OutputFilter_T_gross
docs.RepoObject_OutputFilter_T <.. docs.RepoObject_AntoraXrefCulturesList
docs.RepoObject_OutputFilter_T <.. docs.usp_AntoraExport_ObjectPartialsContent
docs.RepoObject_OutputFilter_T <.. docs.usp_AntoraExport_ObjectPage
docs.RepoObject_OutputFilter_T <.. docs.AntoraNavListRepoObject_by_type
docs.RepoObject_OutputFilter_T <.. docs.AntoraNavListRepoObject_by_schema
docs.RepoObject_OutputFilter_T <.. docs.AntoraNavListRepoObject_by_schema_type
docs.RepoObject_OutputFilter_T <.. docs.RepoObject_ColumnList
docs.RepoObject_OutputFilter_T <.. docs.RepoObject_Plantuml_Entity
docs.RepoObject_OutputFilter_T <.. docs.RepoObject_Plantuml
docs.RepoObject_OutputFilter_T <.. docs.RepoObject_IndexList
docs.RepoObject_OutputFilter_T <.. docs.AntoraNavListPage_by_type
docs.RepoObject_OutputFilter_T <.. docs.IndexSemanticgroupPatterndatatype
docs.RepoObject_OutputFilter_T <.. docs.AntoraNavListPage_by_schema
docs.RepoObject_OutputFilter_T <.. docs.RepoObject_Plantuml_ColRefList_1_1
docs.RepoObject_OutputFilter_T <.. docs.Schema_puml
docs.RepoObject_OutputFilter_T <.. docs.Schema_SsasRelationList
docs.RepoObject_OutputFilter_T <.. docs.Unit_1_union
docs.RepoObject_OutputFilter_T <.. docs.usp_PERSIST_RepoObject_OutputFilter_T
docs.RepoObject_OutputFilter_T_gross <.. docs.RepoObject_MeasureDescriptionList
docs.RepoObject_OutputFilter_T_gross <.. docs.RepoObject_Adoc
docs.RepoObject_OutputFilter_T_gross <.. docs.RepoObject_MeasureList
docs.RepoObject_Plantuml <.. docs.usp_PERSIST_RepoObject_Plantuml_T
docs.RepoObject_Plantuml <.. docs.RepoObject_Plantuml_T
docs.RepoObject_Plantuml_ColRefList_1_1 <.. docs.RepoObject_Plantuml
docs.RepoObject_Plantuml_Entity <.. docs.usp_PERSIST_RepoObject_Plantuml_Entity_T
docs.RepoObject_Plantuml_Entity <.. docs.RepoObject_Plantuml_Entity_T
docs.RepoObject_Plantuml_Entity_T <.. docs.RepoObject_Adoc
docs.RepoObject_Plantuml_Entity_T <.. docs.ObjectRefCyclic_EntityList
docs.RepoObject_Plantuml_Entity_T <.. docs.RepoObject_PlantUml_PumlEntityFkList
docs.RepoObject_Plantuml_Entity_T <.. docs.ftv_RepoObject_Reference_PlantUml_EntityRefList
docs.RepoObject_Plantuml_Entity_T <.. docs.usp_PERSIST_RepoObject_Plantuml_Entity_T
docs.RepoObject_Plantuml_Entity_T <.. docs.Schema_EntityList
docs.RepoObject_PlantUml_FkRefList <.. docs.RepoObject_Plantuml
docs.RepoObject_Plantuml_ObjectRefList_0_30 <.. docs.RepoObject_Plantuml
docs.RepoObject_Plantuml_ObjectRefList_1_1 <.. docs.RepoObject_Plantuml
docs.RepoObject_Plantuml_ObjectRefList_30_0 <.. docs.RepoObject_Plantuml
docs.RepoObject_PlantUml_PumlEntityFkList <.. docs.RepoObject_Plantuml
docs.RepoObject_Plantuml_T <.. docs.RepoObject_Adoc
docs.RepoObject_Plantuml_T <.. docs.usp_PERSIST_RepoObject_Plantuml_T
docs.Schema_EntityList <.. docs.Schema_puml
docs.Schema_puml <.. docs.AntoraNavListPage_by_schema
docs.Schema_PumlPartial_FkRefList <.. docs.Schema_puml
docs.Schema_SsasRelationList <.. docs.Schema_puml
docs.Unit_1_union <.. docs.Unit_2
docs.Unit_2 <.. docs.Unit_3
docs.Unit_3 <.. dmdocs.unit
docs.usp_AntoraExport_ObjectNavigation <.. docs.usp_AntoraExport
docs.usp_AntoraExport_ObjectPage <.. docs.usp_AntoraExport
docs.usp_AntoraExport_ObjectPartialsContent <.. docs.usp_AntoraExport
docs.usp_AntoraExport_ObjectPuml <.. docs.usp_AntoraExport
docs.usp_PERSIST_RepoObject_Adoc_T <.. docs.usp_AntoraExport_ObjectPartialsContent
docs.usp_PERSIST_RepoObject_ColumnList_T <.. docs.usp_AntoraExport_ObjectPartialsContent
docs.usp_PERSIST_RepoObject_IndexList_T <.. docs.usp_AntoraExport_ObjectPartialsContent
docs.usp_PERSIST_RepoObject_OutputFilter_T <.. docs.usp_AntoraExport
docs.usp_PERSIST_RepoObject_Plantuml_Entity_T <.. docs.usp_AntoraExport_ObjectPuml
docs.usp_PERSIST_RepoObject_Plantuml_T <.. docs.usp_AntoraExport_ObjectPuml
property.ExtendedProperty_Repo2Sys_level0 <.. property.usp_sync_ExtendedProperties_Repo2Sys_Delete
property.ExtendedProperty_Repo2Sys_level0 <.. property.usp_sync_ExtendedProperties_Repo2Sys_InsertUpdate
property.ExtendedProperty_Repo2Sys_level1 <.. property.usp_sync_ExtendedProperties_Repo2Sys_InsertUpdate
property.ExtendedProperty_Repo2Sys_level1 <.. property.usp_sync_ExtendedProperties_Repo2Sys_Delete
property.ExtendedProperty_Repo2Sys_level2_RepoObject <.. property.ExtendedProperty_Repo2Sys_level2_Union
property.ExtendedProperty_Repo2Sys_level2_RepoObjectColumn <.. property.ExtendedProperty_Repo2Sys_level2_Union
property.ExtendedProperty_Repo2Sys_level2_Union <.. property.usp_sync_ExtendedProperties_Repo2Sys_InsertUpdate
property.ExtendedProperty_Repo2Sys_level2_Union <.. property.usp_sync_ExtendedProperties_Repo2Sys_Delete
property.fs_get_RepoObjectColumnProperty_nvarchar <.. repo.RepoObjectColumn_gross
property.fs_get_RepoObjectProperty_nvarchar <.. repo.RepoObject_gross
property.PropertyName_RepoObject <.. property.RepoObjectProperty_cross
property.PropertyName_RepoObject <.. property.usp_PERSIST_PropertyName_RepoObject_T
property.PropertyName_RepoObject <.. docs.AntoraTemplate_examples
property.PropertyName_RepoObject <.. property.PropertyName_RepoObject_T
property.PropertyName_RepoObject_T <.. property.RepoObjectProperty_InheritanceType_InheritanceDefinition
property.PropertyName_RepoObject_T <.. property.RepoObjectColumnProperty_external_tgt
property.PropertyName_RepoObject_T <.. property.usp_PERSIST_PropertyName_RepoObject_T
property.PropertyName_RepoObject_T <.. property.RepoObjectProperty_external_tgt
property.PropertyName_RepoObjectColumn <.. property.PropertyName_RepoObjectColumn_T
property.PropertyName_RepoObjectColumn <.. property.usp_PERSIST_PropertyName_RepoObjectColumn_T
property.PropertyName_RepoObjectColumn_T <.. property.RepoObjectColumnProperty_InheritanceType_InheritanceDefinition
property.PropertyName_RepoObjectColumn_T <.. property.usp_PERSIST_PropertyName_RepoObjectColumn_T
property.RepoObjectColumnProperty <.. property.RepoObjectColumnProperty_InheritanceType_InheritanceDefinition
property.RepoObjectColumnProperty <.. property.fs_get_RepoObjectColumnProperty_nvarchar
property.RepoObjectColumnProperty <.. property.usp_RepoObjectColumnProperty_set
property.RepoObjectColumnProperty <.. property.RepoObjectColumnProperty_ForUpdate
property.RepoObjectColumnProperty <.. property.RepoObjectColumnProperty_sys_repo
property.RepoObjectColumnProperty <.. property.ExtendedProperty_Repo2Sys_level2_RepoObjectColumn
property.RepoObjectColumnProperty <.. property.usp_sync_ExtendedProperties_Sys2Repo_InsertUpdate
property.RepoObjectColumnProperty <.. property.PropertyName_RepoObjectColumn
property.RepoObjectColumnProperty <.. property.usp_RepoObjectColumn_Inheritance
property.RepoObjectColumnProperty_external_tgt <.. property.usp_PERSIST_RepoObjectColumnProperty_external_tgt
property.RepoObjectColumnProperty_external_tgt <.. property.RepoObjectColumnProperty
property.RepoObjectColumnProperty_InheritanceType_InheritanceDefinition <.. property.RepoObjectColumnProperty_InheritanceType_resulting_InheritanceDefinition
property.RepoObjectColumnProperty_InheritanceType_resulting_InheritanceDefinition <.. property.usp_RepoObjectColumn_Inheritance
property.RepoObjectColumnProperty_sys_repo <.. property.usp_sync_ExtendedProperties_Sys2Repo_InsertUpdate
property.RepoObjectProperty <.. property.RepoObjectProperty_SelectedPropertyName_split
property.RepoObjectProperty <.. property.usp_RepoObjectProperty_collect
property.RepoObjectProperty <.. property.RepoObjectProperty_ForUpdate
property.RepoObjectProperty <.. property.RepoObjectProperty_sys_repo
property.RepoObjectProperty <.. property.ExtendedProperty_Repo2Sys_level1
property.RepoObjectProperty <.. property.ExtendedProperty_Repo2Sys_level2_RepoObject
property.RepoObjectProperty <.. property.usp_sync_ExtendedProperties_Sys2Repo_InsertUpdate
property.RepoObjectProperty <.. property.PropertyName_RepoObject
property.RepoObjectProperty <.. property.usp_RepoObject_Inheritance
property.RepoObjectProperty <.. property.RepoObjectProperty_InheritanceType_InheritanceDefinition
property.RepoObjectProperty <.. property.fs_get_RepoObjectProperty_nvarchar
property.RepoObjectProperty <.. docs.RepoObject_Adoc
property.RepoObjectProperty <.. property.usp_RepoObjectProperty_set
property.RepoObjectProperty_Collect_source_ROGross <.. property.usp_RepoObjectProperty_collect
property.RepoObjectProperty_Collect_source_sql_modules_definition <.. property.usp_RepoObjectProperty_collect
property.RepoObjectProperty_Collect_source_uspgenerator <.. property.usp_RepoObjectProperty_collect
property.RepoObjectProperty_cross <.. docs.RepoObject_Adoc
property.RepoObjectProperty_external_tgt <.. property.RepoObjectProperty
property.RepoObjectProperty_external_tgt <.. property.usp_PERSIST_RepoObjectProperty_external_tgt
property.RepoObjectProperty_InheritanceType_InheritanceDefinition <.. property.RepoObjectProperty_InheritanceType_resulting_InheritanceDefinition
property.RepoObjectProperty_InheritanceType_resulting_InheritanceDefinition <.. property.usp_RepoObject_Inheritance
property.RepoObjectProperty_SelectedPropertyName_split <.. reference.additional_Reference_from_properties_src
property.RepoObjectProperty_SelectedPropertyName_split <.. reference.additional_Reference_wo_columns_from_properties_src
property.RepoObjectProperty_sys_repo <.. property.usp_sync_ExtendedProperties_Sys2Repo_InsertUpdate
property.usp_external_property_import <.. repo.usp_main
property.usp_PERSIST_PropertyName_RepoObject_T <.. property.usp_RepoObject_Inheritance
property.usp_PERSIST_PropertyName_RepoObjectColumn_T <.. property.usp_RepoObjectColumn_Inheritance
property.usp_PERSIST_RepoObjectColumnProperty_external_tgt <.. property.usp_external_property_import
property.usp_PERSIST_RepoObjectColumnProperty_external_tgt <.. property.usp_external_RepoObjectProperty
property.usp_PERSIST_RepoObjectProperty_external_tgt <.. property.usp_external_RepoObjectProperty
property.usp_PERSIST_RepoObjectProperty_external_tgt <.. property.usp_external_property_import
property.usp_RepoObject_Inheritance <.. repo.usp_main
property.usp_RepoObjectColumn_Inheritance <.. repo.usp_main
property.usp_RepoObjectProperty_collect <.. repo.usp_main
property.usp_RepoObjectProperty_collect <.. property.usp_RepoObject_Inheritance
reference.additional_Reference <.. reference.additional_Reference_guid
reference.additional_Reference <.. reference.additional_Reference_is_external
reference.additional_Reference_database <.. reference.additional_Reference_database_T
reference.additional_Reference_database <.. reference.usp_PERSIST_additional_Reference_database_T
reference.additional_Reference_database_T <.. repo.RepoObject_gross
reference.additional_Reference_database_T <.. reference.usp_PERSIST_additional_Reference_database_T
reference.additional_Reference_database_T <.. property.usp_external_RepoObjectProperty
reference.additional_Reference_database_T <.. property.usp_external_property_import
reference.additional_Reference_from_properties_src <.. reference.additional_Reference_from_properties_tgt
reference.additional_Reference_from_properties_src <.. reference.usp_PERSIST_additional_Reference_from_properties_tgt
reference.additional_Reference_from_properties_tgt <.. reference.additional_Reference
reference.additional_Reference_from_properties_tgt <.. reference.usp_PERSIST_additional_Reference_from_properties_tgt
reference.additional_Reference_guid <.. reference.RepoObject_reference_additional_internal
reference.additional_Reference_guid <.. reference.RepoObjectColumn_reference_additional_internal
reference.additional_Reference_guid <.. reference.RepoObject_reference_additional
reference.additional_Reference_guid <.. reference.RepoObjectColumn_reference_additional
reference.additional_Reference_is_external <.. reference.additional_Reference_Object
reference.additional_Reference_is_external <.. reference.additional_Reference_ObjectColumn
reference.additional_Reference_is_external <.. reference.additional_Reference_database
reference.additional_Reference_Object <.. reference.additional_Reference_Object_T
reference.additional_Reference_Object <.. reference.usp_PERSIST_additional_Reference_Object_T
reference.additional_Reference_Object_T <.. reference.usp_PERSIST_additional_Reference_Object_T
reference.additional_Reference_Object_T <.. repo.RepoObject_external_src
reference.additional_Reference_Object_T <.. repo.RepoObjectColumn_external_src
reference.additional_Reference_ObjectColumn <.. reference.additional_Reference_ObjectColumn_T
reference.additional_Reference_ObjectColumn <.. reference.usp_PERSIST_additional_Reference_ObjectColumn_T
reference.additional_Reference_ObjectColumn_T <.. reference.usp_PERSIST_additional_Reference_ObjectColumn_T
reference.additional_Reference_ObjectColumn_T <.. repo.RepoObjectColumn_external_src
reference.additional_Reference_wo_columns_from_properties_src <.. reference.additional_Reference_wo_columns_from_properties_tgt
reference.additional_Reference_wo_columns_from_properties_src <.. reference.usp_PERSIST_additional_Reference_wo_columns_from_properties_tgt
reference.additional_Reference_wo_columns_from_properties_tgt <.. reference.additional_Reference
reference.additional_Reference_wo_columns_from_properties_tgt <.. reference.usp_PERSIST_additional_Reference_wo_columns_from_properties_tgt
reference.ftv_RepoObject_ReferenceTree <.. reference.RepoObject_ReferenceTree_30_0
reference.ftv_RepoObject_ReferenceTree <.. reference.RepoObject_ReferenceTree_0_30
reference.ftv_RepoObject_ReferenceTree_referenced <.. reference.RepoObject_ReferenceTree_referenced_30_0
reference.ftv_RepoObject_ReferenceTree_referenced <.. reference.RepoObject_ReferenceTree_referenced
reference.ftv_RepoObject_ReferenceTree_referencing <.. reference.RepoObject_ReferenceTree_referencing_0_30
reference.ftv_RepoObject_ReferenceTree_referencing <.. reference.RepoObject_ReferenceTree_referencing
reference.ftv_RepoObjectColumn_ReferenceTree <.. reference.RepoObjectColumn_ReferenceTree
reference.Persistence <.. workflow.ProcedureDependency_PersistenceDependency_src
reference.Persistence <.. reference.Persistence_bidirectional
reference.Persistence <.. workflow.ProcedureDependency_input_PersistenceDependency_S
reference.ReferenceTree_cyclic_ref_PersistenceUsp <.. reference.ReferenceTree_cyclic_union
reference.ReferenceTree_cyclic_union <.. docs.ObjectRefCyclic_EntityList
reference.ReferenceTree_cyclic_union <.. docs.ObjectRefCyclic_ObjectRefList
reference.RepoObject_reference <.. reference.RepoObject_reference_T
reference.RepoObject_reference <.. reference.usp_PERSIST_RepoObject_reference_T
reference.RepoObject_reference_additional <.. reference.RepoObject_reference_union
reference.RepoObject_reference_persistence <.. reference.RepoObject_reference_union
reference.RepoObject_reference_persistence <.. repo.usp_main
reference.RepoObject_reference_persistence_target_as_source <.. reference.RepoObject_reference_union
reference.RepoObject_reference_persistence_target_as_source <.. repo.usp_main
reference.RepoObject_reference_persistence_target_as_source <.. reference.RepoObject_reference
reference.RepoObject_reference_persistence_target_as_source_explicit <.. reference.RepoObject_reference_union
reference.RepoObject_reference_persistence_target_as_source_explicit <.. reference.RepoObject_reference
reference.RepoObject_reference_SqlExpressionDependencies <.. reference.RepoObject_reference_union
reference.RepoObject_reference_SqlExpressionDependencies <.. reference.RepoObject_reference_persistence_target_as_source
reference.RepoObject_reference_SqlExpressionDependencies <.. reference.RepoObject_reference_persistence_target_as_source_explicit
reference.RepoObject_reference_T <.. reference.RepoObjectColumn_reference_additional
reference.RepoObject_reference_T <.. reference.RepoObjectColumn_reference_additional_internal
reference.RepoObject_reference_T <.. repo.RepoObject_wo_referencing
reference.RepoObject_reference_T <.. reference.ReferenceTree_cyclic_ref_PersistenceUsp
reference.RepoObject_reference_T <.. reference.RepoObject_reference_T_bidirectional
reference.RepoObject_reference_T <.. docs.RepoObject_Plantuml_ObjectRefList_1_1
reference.RepoObject_reference_T <.. reference.usp_PERSIST_RepoObject_reference_T
reference.RepoObject_reference_T <.. reference.RepoObjectColumn_reference_virtual
reference.RepoObject_reference_T <.. docs.RepoObject_Plantuml_ObjectRefList_30_0
reference.RepoObject_reference_T <.. docs.RepoObject_Plantuml_ObjectRefList_0_30
reference.RepoObject_reference_T <.. reference.RepoObject_ReferencedReferencing
reference.RepoObject_reference_T <.. repo.usp_main
reference.RepoObject_reference_T <.. reference.RepoObjectColumn_reference_BySamePredecessors
reference.RepoObject_reference_T <.. reference.RepoObjectColumn_reference_QueryPlan
reference.RepoObject_reference_T <.. reference.RepoObjectColumn_reference_SqlExpressionDependencies
reference.RepoObject_reference_T <.. reference.RepoObjectColumn_reference_FirstResultSet
reference.RepoObject_reference_T <.. repo.IndexReferencedReferencing
reference.RepoObject_reference_union <.. reference.RepoObject_reference
reference.RepoObject_reference_virtual <.. reference.RepoObject_reference_union
reference.RepoObject_ReferencedList <.. repo.RepoObject_sat2
reference.RepoObject_ReferencedList <.. repo.RepoObject_gross2
reference.RepoObject_ReferencedReferencing <.. reference.ftv_RepoObject_ReferenceTree_referencing
reference.RepoObject_ReferencedReferencing <.. reference.usp_RepoObject_ReferenceTree_insert
reference.RepoObject_ReferencedReferencing <.. repo.RepoObject_gross
reference.RepoObject_ReferencedReferencing <.. reference.ftv_RepoObject_ReferenceTree_via_fullname
reference.RepoObject_ReferencedReferencing <.. reference.ftv_RepoObject_ReferenceTree
reference.RepoObject_ReferencedReferencing <.. reference.RepoObject_ReferencedList
reference.RepoObject_ReferencedReferencing <.. reference.RepoObject_ReferencingList
reference.RepoObject_ReferencedReferencing <.. reference.ftv_RepoObject_ReferenceTree_referenced
reference.RepoObject_ReferenceTree_0_30 <.. reference.RepoObject_ReferenceTree_0_30_T
reference.RepoObject_ReferenceTree_0_30 <.. reference.usp_PERSIST_RepoObject_ReferenceTree_0_30_T
reference.RepoObject_ReferenceTree_0_30_T <.. reference.usp_PERSIST_RepoObject_ReferenceTree_0_30_T
reference.RepoObject_ReferenceTree_30_0 <.. reference.usp_PERSIST_RepoObject_ReferenceTree_30_0_T
reference.RepoObject_ReferenceTree_30_0 <.. reference.RepoObject_ReferenceTree_30_0_T
reference.RepoObject_ReferenceTree_30_0_T <.. reference.usp_PERSIST_RepoObject_ReferenceTree_30_0_T
reference.RepoObject_ReferencingList <.. repo.RepoObject_sat2
reference.RepoObject_ReferencingList <.. repo.RepoObject_gross2
reference.RepoObjectColumn_reference <.. reference.usp_PERSIST_RepoObjectColumn_reference_T
reference.RepoObjectColumn_reference <.. reference.RepoObjectColumn_reference_T
reference.RepoObjectColumn_reference_additional <.. reference.RepoObjectColumn_reference_union
reference.RepoObjectColumn_reference_FirstResultSet <.. reference.RepoObjectColumn_reference_BySamePredecessors
reference.RepoObjectColumn_reference_Persistence <.. reference.RepoObjectColumn_reference_union
reference.RepoObjectColumn_reference_QueryPlan <.. reference.SysObjectColumn_QueryPlanExpression
reference.RepoObjectColumn_reference_SqlExpressionDependencies <.. reference.RepoObjectColumn_reference_union
reference.RepoObjectColumn_reference_SqlModules <.. reference.RepoObjectColumn_reference_union
reference.RepoObjectColumn_reference_T <.. docs.RepoObject_Plantuml_ColRefList_1_1
reference.RepoObjectColumn_reference_T <.. repo.RepoObjectColumn_MissingSource_TypeV
reference.RepoObjectColumn_reference_T <.. reference.RepoObjectColumn_RelationScript
reference.RepoObjectColumn_reference_T <.. reference.RepoObjectColumn_ReferencedReferencing
reference.RepoObjectColumn_reference_T <.. reference.usp_PERSIST_RepoObjectColumn_reference_T
reference.RepoObjectColumn_reference_T <.. repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing
reference.RepoObjectColumn_reference_union <.. reference.RepoObjectColumn_reference
reference.RepoObjectColumn_reference_virtual <.. reference.RepoObjectColumn_reference_union
reference.RepoObjectColumn_ReferencedList <.. repo.RepoObjectColumn_gross2
reference.RepoObjectColumn_ReferencedReferencing <.. reference.RepoObjectColumn_ReferencingList
reference.RepoObjectColumn_ReferencedReferencing <.. reference.ftv_RepoObjectColumn_ReferenceTree
reference.RepoObjectColumn_ReferencedReferencing <.. reference.ftv_RepoObject_DbmlColumnRelation
reference.RepoObjectColumn_ReferencedReferencing <.. reference.RepoObjectColumn_ReferencedList
reference.RepoObjectColumn_ReferenceTree <.. reference.ftv_RepoObject_ColumReferenceRepoObject
reference.RepoObjectColumn_ReferencingList <.. repo.RepoObjectColumn_gross2
reference.RepoObjectColumn_RelationScript <.. reference.ftv_RepoObject_ColumReferenceRepoObject
reference.SysObjectColumn_QueryPlanExpression <.. reference.usp_RepoObjectSource_QueryPlan
reference.usp_additional_Reference <.. repo.usp_main
reference.usp_additional_Reference <.. property.usp_external_property_import
reference.usp_PERSIST_additional_Reference_database_T <.. reference.usp_additional_Reference
reference.usp_PERSIST_additional_Reference_from_properties_tgt <.. repo.usp_main
reference.usp_PERSIST_additional_Reference_Object_T <.. reference.usp_additional_Reference
reference.usp_PERSIST_additional_Reference_ObjectColumn_T <.. reference.usp_additional_Reference
reference.usp_PERSIST_additional_Reference_wo_columns_from_properties_tgt <.. repo.usp_main
reference.usp_PERSIST_RepoObject_reference_T <.. repo.usp_main
reference.usp_PERSIST_RepoObject_ReferenceTree_0_30_T <.. reference.usp_RepoObject_ReferenceTree
reference.usp_PERSIST_RepoObject_ReferenceTree_30_0_T <.. reference.usp_RepoObject_ReferenceTree
reference.usp_PERSIST_RepoObjectColumn_reference_T <.. repo.usp_main
reference.usp_RepoObject_ReferenceTree_insert <.. repo.usp_main
reference.usp_RepoObject_update_SysObjectQueryPlan <.. repo.usp_main
reference.usp_RepoObjectSource_FirstResultSet <.. repo.usp_main
reference.usp_RepoObjectSource_QueryPlan <.. repo.usp_main
reference.usp_update_Referencing_Count <.. repo.usp_main
repo.ForeignKey_gross <.. docs.RepoObject_IndexList
repo.ForeignKey_Indexes <.. repo.ForeignKey_Indexes_union
repo.ForeignKey_Indexes <.. repo.usp_Index_ForeignKey
repo.ForeignKey_Indexes_union <.. repo.ForeignKey_Indexes_union_T
repo.ForeignKey_Indexes_union <.. repo.usp_PERSIST_ForeignKey_Indexes_union_T
repo.ForeignKey_Indexes_union_T <.. repo.usp_Index_finish
repo.ForeignKey_Indexes_union_T <.. docs.Schema_PumlPartial_FkRefList
repo.ForeignKey_Indexes_union_T <.. repo.usp_PERSIST_ForeignKey_Indexes_union_T
repo.ForeignKey_Indexes_union_T <.. docs.RepoObject_PlantUml_FkRefList
repo.ForeignKey_Indexes_union_T <.. repo.RepoObject_related_FK_union
repo.ForeignKey_Indexes_union_T <.. repo.ForeignKey_gross
repo.ForeignKey_Indexes_union_T <.. docs.ForeignKey_RelationScript
repo.ForeignKey_IndexPattern <.. repo.ForeignKey_Indexes
repo.ForeignKey_virtual_Indexes <.. repo.ForeignKey_Indexes_union
repo.Index_ColumList <.. repo.Index_ColumList_T
repo.Index_ColumList <.. repo.usp_PERSIST_Index_ColumList_T
repo.Index_ColumList_T <.. uspgenerator.GeneratorUspStep_Persistence_src
repo.Index_ColumList_T <.. repo.Index_SqlConstraint_PkUq
repo.Index_ColumList_T <.. repo.usp_PERSIST_Index_ColumList_T
repo.Index_ColumList_T <.. repo.Index_gross
repo.Index_gross <.. repo.ForeignKey_gross
repo.Index_gross <.. docs.IndexSemanticgroupPatterndatatype
repo.Index_gross <.. docs.RepoObject_IndexList
repo.Index_gross <.. repo.usp_Index_finish
repo.Index_gross <.. repo.RepoObject_SqlCreateTable
repo.Index_gross <.. repo.ForeignKey_virtual_Indexes
repo.Index_gross <.. repo.ForeignKey_Indexes
repo.Index_gross <.. repo.usp_Index_virtual_set
repo.Index_gross <.. repo.usp_index_inheritance
repo.Index_IndexPattern <.. repo.usp_Index_Settings
repo.Index_referencing_IndexPatternColumnGuid <.. repo.IndexReferencedReferencing_HasFullColumnsInReferencing
repo.Index_SqlConstraint_PkUq <.. repo.RepoObject_SqlCreateTable
repo.Index_union <.. repo.IndexReferencedReferencing
repo.Index_union <.. repo.Index_SqlConstraint_PkUq
repo.Index_union <.. repo.Index_gross
repo.Index_union <.. repo.usp_Index_finish
repo.Index_union <.. repo.Index_Settings_ForUpdate
repo.Index_unique_IndexPatternColumnGuid <.. repo.Index_union
repo.Index_virtual_ForUpdate <.. repo.usp_index_inheritance
repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing <.. repo.usp_PERSIST_IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T
repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing <.. repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T
repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T <.. repo.IndexColumn_virtual_referenced_setpoint
repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T <.. repo.Index_referencing_IndexPatternColumnGuid
repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T <.. repo.IndexReferencedReferencing_HasFullColumnsInReferencing
repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T <.. repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_check
repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T <.. repo.usp_PERSIST_IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T
repo.IndexColumn_ssas_gross <.. repo.IndexColumn_union
repo.IndexColumn_union <.. repo.usp_PERSIST_IndexColumn_union_T
repo.IndexColumn_union <.. repo.IndexColumn_union_T
repo.IndexColumn_union_T <.. repo.Index_ColumList
repo.IndexColumn_union_T <.. repo.Index_IndexPattern
repo.IndexColumn_union_T <.. repo.usp_PERSIST_IndexColumn_union_T
repo.IndexColumn_union_T <.. repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing
repo.IndexColumn_union_T <.. repo.RepoObjectColumn_gross2
repo.IndexColumn_virtual_gross <.. repo.IndexColumn_union
repo.IndexColumn_virtual_referenced_setpoint <.. repo.check_IndexColumn_virtual_referenced_setpoint
repo.IndexColumn_virtual_referenced_setpoint <.. repo.usp_index_inheritance
repo.IndexReferencedReferencing <.. repo.IndexReferencedReferencing_HasFullColumnsInReferencing
repo.IndexReferencedReferencing_HasFullColumnsInReferencing <.. repo.usp_index_inheritance
repo.Measure <.. docs.Unit_1_union
repo.Measure <.. property.usp_MeasureProperty_set
repo.Measure <.. docs.Measure_MeasurePropertyList
repo.Measure <.. repo.Measure_union
repo.Measure_union <.. ssas.Measure_translation
repo.Measure_union <.. docs.RepoObject_MeasureList
repo.Measure_union <.. docs.RepoObject_MeasureDescriptionList
repo.RepoObject <.. property.RepoObjectProperty_external_tgt
repo.RepoObject <.. property.RepoObjectColumnProperty_external_tgt
repo.RepoObject <.. docs.ftv_RepoObject_AntoraXref
repo.RepoObject <.. repo.fs_RepoObject_fullname2
repo.RepoObject <.. repo.RepoObject_gross_persistence
repo.RepoObject <.. repo.usp_persistence_delete
repo.RepoObject <.. uspgenerator.GeneratorUsp_check_persistence
repo.RepoObject <.. reference.RepoObject_reference_persistence_target_as_source_explicit
repo.RepoObject <.. repo.Index_Settings_ForUpdate
repo.RepoObject <.. property.RepoObjectProperty_ForUpdate
repo.RepoObject <.. repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_check
repo.RepoObject <.. docs.RepoObject_Plantuml_ObjectRefList_1_1
repo.RepoObject <.. workflow.WorkflowStep_ForUpdate
repo.RepoObject <.. workflow.Workflow_ProcedureDependency_T_TaskName
repo.RepoObject <.. workflow.Biml_Task
repo.RepoObject <.. workflow.Workflow_ProcedureDependency_T_bidirectional
repo.RepoObject <.. repo.RepoObject_wo_referencing
repo.RepoObject <.. workflow.Workflow_ProcedureDependency_T_NotInSortorder_check
repo.RepoObject <.. workflow.Workflow_UspList
repo.RepoObject <.. reference.additional_Reference_guid
repo.RepoObject <.. repo.IndexColumn_ssas_gross
repo.RepoObject <.. repo.RepoObject_persistence_SourceMismatch
repo.RepoObject <.. repo.RepoObject_external_src
repo.RepoObject <.. repo.RepoObjectColumn_external_src
repo.RepoObject <.. reference.usp_update_Referencing_Count
repo.RepoObject <.. reference.usp_RepoObjectSource_FirstResultSet
repo.RepoObject <.. reference.usp_RepoObject_update_SysObjectQueryPlan
repo.RepoObject <.. repo.usp_Index_virtual_set
repo.RepoObject <.. repo.usp_sync_guid_RepoObject
repo.RepoObject <.. repo.usp_sync_guid_RepoObjectColumn
repo.RepoObject <.. repo.usp_persistence_set
repo.RepoObject <.. repo.usp_main
repo.RepoObject <.. repo.RepoObject_persistence_ForUpdate
repo.RepoObject <.. sqlparse.RepoObject_SqlModules_71_reference_ExpliciteTableAlias
repo.RepoObject <.. sqlparse.RepoObject_SqlModules_72_reference_NoTableAlias
repo.RepoObject <.. graph.RepoObject_S
repo.RepoObject <.. reference.RepoObjectColumn_reference_SqlModules
repo.RepoObject <.. repo.RepoObject_RequiredRepoObjectMerge
repo.RepoObject <.. property.ExtendedProperty_Repo2Sys_level1
repo.RepoObject <.. property.ExtendedProperty_Repo2Sys_level2_RepoObject
repo.RepoObject <.. property.ExtendedProperty_Repo2Sys_level2_RepoObjectColumn
repo.RepoObject <.. property.RepoObjectProperty_InheritanceType_InheritanceDefinition
repo.RepoObject <.. repo_sys.ForeignKey
repo.RepoObject <.. repo.usp_Index_finish
repo.RepoObject <.. repo.RepoObject_fullname_u_v
repo.RepoObject <.. property.RepoObjectProperty_cross
repo.RepoObject <.. docs.ftv_RepoObject_Reference_PlantUml_EntityRefList
repo.RepoObject <.. property.usp_RepoObjectProperty_set
repo.RepoObject <.. repo.Index_virtual_ForUpdate
repo.RepoObject <.. docs.AntoraNavListPage_by_schema
repo.RepoObject <.. repo.RepoObject_related_FK_union
repo.RepoObject <.. property.usp_RepoObjectColumnProperty_set
repo.RepoObject <.. workflow.ProcedureDependency_gross
repo.RepoObject <.. repo.usp_update_Referencing_Count
repo.RepoObject <.. reference.RepoObject_reference_virtual
repo.RepoObject <.. reference.usp_RepoObjectSource_virtual_set
repo.RepoObject <.. sqlparse.RepoObject_SqlModules_Repo_Sys
repo.RepoObject <.. property.RepoObjectColumnProperty_sys_repo
repo.RepoObject <.. property.RepoObjectProperty_sys_repo
repo.RepoObject <.. repo.SysObject_RepoObject_via_name
repo.RepoObject <.. repo.SysObject_RepoObject_via_guid
repo.RepoObject <.. repo.SysColumn_RepoObjectColumn_via_guid
repo.RepoObject <.. repo.SysColumn_RepoObjectColumn_via_name
repo.RepoObject <.. reference.RepoObject_reference_SqlExpressionDependencies
repo.RepoObject <.. repo.RepoObjectColumn_gross
repo.RepoObject <.. reference.RepoObjectColumn_reference_FirstResultSet
repo.RepoObject <.. reference.RepoObjectColumn_reference_QueryPlan
repo.RepoObject <.. repo.RepoObject_gross
repo.RepoObject <.. repo.RepoObject_SqlCreateTable
repo.RepoObject <.. repo.RepoObjectColumn_MissingSource_TypeV
repo.RepoObject <.. repo.check_IndexColumn_virtual_referenced_setpoint
repo.RepoObject <.. reference.usp_RepoObjectSource_QueryPlan
repo.RepoObject <.. repo.RepoObject_persistence_ObjectNames
repo.RepoObject <.. repo.IndexColumn_virtual_gross
repo.RepoObject <.. repo.Index_virtual_SysObject
repo.RepoObject <.. repo_sys.Index_unique
repo.RepoObject <.. repo_sys.RepoObjectReferenced
repo.RepoObject <.. repo_sys.RepoObjectReferencing
repo.RepoObject <.. repo.RepoObject__after_update
repo.RepoObject <.. uspgenerator.GeneratorUsp_SqlUsp
repo.RepoObject <.. sqlparse.RepoObject_SqlModules_10_statement
repo.RepoObject <.. sqlparse.RepoObject_SqlModules_39_object
repo.RepoObject <.. reference.RepoObjectColumn_reference_Persistence
repo.RepoObject <.. repo.RepoObject_persistence_column
repo.RepoObject <.. reference.RepoObject_reference_persistence
repo.RepoObject_ColumnList <.. repo.RepoObject_SqlCreateTable
repo.RepoObject_ColumnList <.. repo.RepoObject_sat2
repo.RepoObject_ColumnList <.. repo.RepoObject_gross2
repo.RepoObject_external_src <.. repo.RepoObject_external_tgt
repo.RepoObject_external_src <.. repo.usp_PERSIST_RepoObject_external_tgt
repo.RepoObject_external_tgt <.. repo.usp_PERSIST_RepoObject_external_tgt
repo.RepoObject_external_tgt <.. repo.RepoObject
repo.RepoObject_external_tgt <.. repo.RepoObjectColumn_external_tgt
repo.RepoObject_gross <.. repo.Index_gross
repo.RepoObject_gross <.. uspgenerator.GeneratorUspStep_Persistence_src
repo.RepoObject_gross <.. uspgenerator.GeneratorUspStep_Persistence_IsInactive_setpoint
repo.RepoObject_gross <.. repo.RepoObject_SqlCreateTable
repo.RepoObject_gross <.. repo.Index_virtual_ForUpdate
repo.RepoObject_gross <.. docs.RepoObject_Plantuml
repo.RepoObject_gross <.. docs.RepoObject_OutputFilter
repo.RepoObject_gross <.. docs.RepoObject_Adoc
repo.RepoObject_gross <.. uspgenerator.usp_GeneratorUsp_insert_update_persistence
repo.RepoObject_gross <.. reference.usp_RepoObject_update_SysObjectQueryPlan
repo.RepoObject_gross <.. reference.usp_RepoObjectSource_FirstResultSet
repo.RepoObject_gross <.. reference.usp_RepoObjectSource_QueryPlan
repo.RepoObject_gross <.. repo.RepoObject_sat2
repo.RepoObject_gross <.. docs.Unit_1_union
repo.RepoObject_gross <.. repo.RepoObject_gross2
repo.RepoObject_gross <.. workflow.WorkflowStep_src
repo.RepoObject_gross <.. reference.Persistence
repo.RepoObject_gross <.. reference.RepoObject_ReferenceTree_30_0
repo.RepoObject_gross <.. reference.RepoObject_ReferenceTree_0_30
repo.RepoObject_gross <.. reference.RepoObject_ReferenceTree_referencing_0_30
repo.RepoObject_gross <.. reference.RepoObject_ReferenceTree_referenced_30_0
repo.RepoObject_gross <.. property.RepoObjectProperty_Collect_source_ROGross
repo.RepoObject_gross <.. reference.RepoObject_ReferenceTree_referencing
repo.RepoObject_gross <.. reference.RepoObject_ReferenceTree_referenced
repo.RepoObject_gross_persistence <.. reference.RepoObject_reference_persistence_target_as_source
repo.RepoObject_gross2 <.. uspgenerator.GeneratorUspStep_Persistence_src
repo.RepoObject_persistence_ForUpdate <.. repo.RepoObject_persistence_SourceMismatch
repo.RepoObject_persistence_NoCompareButUpdate <.. repo.usp_sync_guid_RepoObjectColumn
repo.RepoObject_persistence_NoCompareNoUpdate <.. repo.usp_sync_guid_RepoObjectColumn
repo.RepoObject_persistence_source_Ignore <.. repo.usp_sync_guid_RepoObjectColumn
repo.RepoObject_persistence_target_Ignore <.. repo.usp_sync_guid_RepoObjectColumn
repo.RepoObject_related_FK_union <.. docs.RepoObject_PlantUml_PumlEntityFkList
repo.RepoObject_related_FK_union <.. docs.RepoObject_PlantUml_FkRefList
repo.RepoObject_RequiredRepoObjectMerge <.. repo.usp_sync_guid_RepoObject
repo.RepoObject_sat2 <.. repo.RepoObject_sat2_T
repo.RepoObject_sat2 <.. repo.usp_PERSIST_RepoObject_sat2_T
repo.RepoObject_sat2_T <.. repo.usp_PERSIST_RepoObject_sat2_T
repo.RepoObject_sat2_T <.. docs.RepoObject_Adoc
repo.RepoObject_sat2_T <.. property.RepoObjectProperty_Collect_source_ROGross
repo.RepoObject_SqlCreateTable <.. reference.ftv_RepoObject_ColumReferenceRepoObject
repo.RepoObject_SSAS_src <.. repo.usp_PERSIST_RepoObject_SSAS_tgt
repo.RepoObject_SSAS_src <.. repo.RepoObject_SSAS_tgt
repo.RepoObject_SSAS_tgt <.. repo.RepoObject
repo.RepoObject_SSAS_tgt <.. repo.RepoObjectColumn_SSAS_tgt
repo.RepoObject_SSAS_tgt <.. repo.usp_PERSIST_RepoObject_SSAS_tgt
repo.RepoObjectColumn <.. reference.RepoObjectColumn_reference_Persistence
repo.RepoObjectColumn <.. repo.IndexColumn_virtual_gross
repo.RepoObjectColumn <.. repo.RepoObject_persistence_column
repo.RepoObjectColumn <.. repo.RepoObject_persistence_source_Ignore
repo.RepoObjectColumn <.. repo.RepoObject_persistence_target_Ignore
repo.RepoObjectColumn <.. repo.RepoObject_persistence_NoCompareNoUpdate
repo.RepoObjectColumn <.. repo.RepoObject_persistence_NoCompareButUpdate
repo.RepoObjectColumn <.. property.RepoObjectColumnProperty_external_tgt
repo.RepoObjectColumn <.. repo.RepoObjectColumn_gross2
repo.RepoObjectColumn <.. repo.IndexColumn_ssas_gross
repo.RepoObjectColumn <.. reference.additional_Reference_guid
repo.RepoObjectColumn <.. repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_check
repo.RepoObjectColumn <.. reference.usp_RepoObjectColumnSource_virtual_set
repo.RepoObjectColumn <.. repo.usp_update_Referencing_Count
repo.RepoObjectColumn <.. property.usp_RepoObjectColumnProperty_set
repo.RepoObjectColumn <.. repo.RepoObjectColumn_RequiredRepoObjectColumnMerge
repo.RepoObjectColumn <.. reference.RepoObjectColumn_ReferenceTree
repo.RepoObjectColumn <.. reference.RepoObjectColumn_RelationScript
repo.RepoObjectColumn <.. property.RepoObjectColumnProperty_InheritanceType_InheritanceDefinition
repo.RepoObjectColumn <.. property.ExtendedProperty_Repo2Sys_level2_RepoObjectColumn
repo.RepoObjectColumn <.. reference.RepoObjectColumn_reference_SqlModules
repo.RepoObjectColumn <.. sqlparse.RepoObject_SqlModules_72_reference_NoTableAlias
repo.RepoObjectColumn <.. sqlparse.RepoObject_SqlModules_71_reference_ExpliciteTableAlias
repo.RepoObjectColumn <.. repo.usp_sync_guid_RepoObjectColumn
repo.RepoObjectColumn <.. repo.usp_Index_virtual_set
repo.RepoObjectColumn <.. reference.usp_update_Referencing_Count
repo.RepoObjectColumn <.. reference.usp_RepoObjectSource_QueryPlan
repo.RepoObjectColumn <.. repo.check_IndexColumn_virtual_referenced_setpoint
repo.RepoObjectColumn <.. repo.RepoObjectColumn_MissingSource_TypeV
repo.RepoObjectColumn <.. repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing
repo.RepoObjectColumn <.. repo.RepoObject_SqlCreateTable
repo.RepoObjectColumn <.. repo.RepoObjectColumn_gross
repo.RepoObjectColumn <.. repo.SysColumn_RepoObjectColumn_via_name
repo.RepoObjectColumn <.. repo.SysColumn_RepoObjectColumn_via_guid
repo.RepoObjectColumn <.. property.RepoObjectColumnProperty_sys_repo
repo.RepoObjectColumn_external_src <.. repo.RepoObjectColumn_external_tgt
repo.RepoObjectColumn_external_src <.. repo.usp_PERSIST_RepoObjectColumn_external_tgt
repo.RepoObjectColumn_external_tgt <.. repo.RepoObjectColumn
repo.RepoObjectColumn_external_tgt <.. repo.usp_PERSIST_RepoObjectColumn_external_tgt
repo.RepoObjectColumn_gross <.. reference.RepoObjectColumn_reference_FirstResultSet
repo.RepoObjectColumn_gross <.. repo.usp_sync_guid_RepoObjectColumn
repo.RepoObjectColumn_gross <.. reference.RepoObjectColumn_reference_QueryPlan
repo.RepoObjectColumn_gross <.. ssas.RepoObjectColumn_translation
repo.RepoObjectColumn_gross <.. docs.Unit_1_union
repo.RepoObjectColumn_gross <.. repo.RepoObjectColumn_gross2
repo.RepoObjectColumn_gross <.. reference.usp_RepoObjectColumnSource_virtual_set
repo.RepoObjectColumn_gross <.. reference.RepoObjectColumn_reference_virtual
repo.RepoObjectColumn_gross <.. property.RepoObjectColumnProperty_ForUpdate
repo.RepoObjectColumn_gross <.. graph.RepoObjectColumn_S
repo.RepoObjectColumn_gross2 <.. repo.RepoObject_ColumnList
repo.RepoObjectColumn_gross2 <.. uspgenerator.usp_GeneratorUsp_insert_update_persistence
repo.RepoObjectColumn_gross2 <.. docs.RepoObject_ColumnList
repo.RepoObjectColumn_RequiredRepoObjectColumnMerge <.. repo.usp_sync_guid_RepoObjectColumn
repo.RepoObjectColumn_SSAS_tgt <.. repo.RepoObjectColumn
repo.RepoObjectColumn_SSAS_tgt <.. repo.usp_PERSIST_RepoObjectColumn_SSAS_tgt
repo.RepoSchema <.. property.usp_sync_ExtendedProperties_Sys2Repo_InsertUpdate
repo.RepoSchema <.. docs.AntoraNavListPage_by_schema
repo.RepoSchema <.. repo.SysSchema_RepoSchema_via_guid
repo.RepoSchema <.. repo.SysSchema_RepoSchema_via_name
repo.RepoSchema <.. repo.usp_sync_guid_RepoSchema
repo.RepoSchema <.. property.ExtendedProperty_Repo2Sys_level0
repo.RepoSchema <.. repo.RepoObject_SSAS_src
repo.RepoSchema <.. docs.Schema_puml
repo.RepoSchema <.. docs.Unit_1_union
repo.RepoSchema <.. repo.Measure
repo.RepoSchema <.. property.usp_RepoSchemaProperty_set
repo.RepoSchema_ssas_src <.. repo.usp_PERSIST_RepoSchema_ssas_tgt
repo.RepoSchema_ssas_src <.. repo.RepoSchema_ssas_tgt
repo.RepoSchema_ssas_tgt <.. repo.RepoSchema
repo.RepoSchema_ssas_tgt <.. repo.usp_PERSIST_RepoSchema_ssas_tgt
repo.SysColumn_RepoObjectColumn_via_guid <.. repo.usp_sync_guid_RepoObjectColumn
repo.SysColumn_RepoObjectColumn_via_name <.. repo.usp_sync_guid_RepoObjectColumn
repo.SysColumn_RepoObjectColumn_via_name <.. repo_sys.IndexColumn_unique
repo.SysColumn_RepoObjectColumn_via_name <.. repo_sys.sql_expression_dependencies
repo.SysObject_RepoObject_via_guid <.. repo.usp_sync_guid_RepoObject
repo.SysObject_RepoObject_via_name <.. repo.usp_sync_guid_RepoObject
repo.SysObject_RepoObject_via_name <.. repo_sys.IndexColumn_unique
repo.SysObject_RepoObject_via_name <.. repo_sys.sql_expression_dependencies
repo.SysSchema_RepoSchema_via_guid <.. repo.usp_sync_guid_RepoSchema
repo.SysSchema_RepoSchema_via_name <.. repo.usp_sync_guid_RepoSchema
repo.usp_Index_finish <.. repo.usp_index_inheritance
repo.usp_Index_finish <.. repo.usp_Index_ForeignKey
repo.usp_Index_ForeignKey <.. repo.usp_main
repo.usp_index_inheritance <.. repo.usp_main
repo.usp_Index_Settings <.. repo.usp_Index_finish
repo.usp_Index_virtual_set <.. repo.usp_Index_ForeignKey
repo.usp_PERSIST_ForeignKey_Indexes_union_T <.. repo.usp_Index_ForeignKey
repo.usp_PERSIST_Index_ColumList_T <.. repo.usp_Index_finish
repo.usp_PERSIST_IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T <.. repo.usp_index_inheritance
repo.usp_PERSIST_IndexColumn_union_T <.. repo.usp_Index_finish
repo.usp_PERSIST_RepoObject_external_tgt <.. reference.usp_additional_Reference
repo.usp_PERSIST_RepoObject_sat2_T <.. repo.usp_main
repo.usp_PERSIST_RepoObject_SSAS_tgt <.. repo.usp_sync_guid_ssas
repo.usp_PERSIST_RepoObjectColumn_external_tgt <.. reference.usp_additional_Reference
repo.usp_PERSIST_RepoObjectColumn_SSAS_tgt <.. repo.usp_sync_guid_ssas
repo.usp_PERSIST_RepoSchema_ssas_tgt <.. repo.usp_sync_guid_ssas
repo.usp_sync_guid <.. repo.usp_main
repo.usp_sync_guid <.. repo.usp_persistence_set
repo.usp_sync_guid_RepoObject <.. repo.usp_sync_guid
repo.usp_sync_guid_RepoObjectColumn <.. repo.usp_sync_guid
repo.usp_sync_guid_RepoSchema <.. repo.usp_sync_guid
repo.usp_sync_guid_ssas <.. repo.usp_main
repo_sys.ForeignKey <.. repo_sys.ForeignKeyColumn
repo_sys.ForeignKey <.. repo.ForeignKey_IndexPattern
repo_sys.ForeignKeyColumn <.. repo.ForeignKey_IndexPattern
repo_sys.Index_unique <.. repo.Index_union
repo_sys.IndexColumn_unique <.. repo.IndexColumn_union
repo_sys.IndexColumn_unique <.. repo.Index_unique_IndexPatternColumnGuid
repo_sys.RepoObjectReferenced <.. reference.usp_update_Referencing_Count
repo_sys.RepoObjectReferenced <.. repo.usp_update_Referencing_Count
repo_sys.RepoObjectReferencing <.. repo.usp_update_Referencing_Count
repo_sys.RepoObjectReferencing <.. reference.usp_update_Referencing_Count
repo_sys.sql_expression_dependencies <.. reference.RepoObject_reference_SqlExpressionDependencies
repo_sys.sql_expression_dependencies <.. reference.RepoObjectColumn_reference_SqlExpressionDependencies
sqlparse.RepoObject_SqlModules_10_statement <.. sqlparse.RepoObject_SqlModules_20_statement_children
sqlparse.RepoObject_SqlModules_20_statement_children <.. sqlparse.RepoObject_SqlModules_21_statement_children_helper
sqlparse.RepoObject_SqlModules_20_statement_children <.. sqlparse.RepoObject_SqlModules_29_1_object_is_union
sqlparse.RepoObject_SqlModules_20_statement_children <.. sqlparse.RepoObject_SqlModules_29_2_object_is_GroupBy
sqlparse.RepoObject_SqlModules_20_statement_children <.. sqlparse.RepoObject_SqlModules_32_ObjectClass
sqlparse.RepoObject_SqlModules_20_statement_children <.. sqlparse.RepoObject_SqlModules_33_ObjectNormalized
sqlparse.RepoObject_SqlModules_20_statement_children <.. sqlparse.RepoObject_SqlModules_51_Identitfier
sqlparse.RepoObject_SqlModules_20_statement_children <.. sqlparse.RepoObject_SqlModules_Identitfier
sqlparse.RepoObject_SqlModules_20_statement_children <.. sqlparse.RepoObject_SqlModules_22_identifier_alias_AS
sqlparse.RepoObject_SqlModules_20_statement_children <.. sqlparse.RepoObject_SqlModules_23_normalized_wo_nolock
sqlparse.RepoObject_SqlModules_20_statement_children <.. sqlparse.RepoObject_SqlModules_24_IdentifierList_children
sqlparse.RepoObject_SqlModules_20_statement_children <.. sqlparse.RepoObject_SqlModules_41_from
sqlparse.RepoObject_SqlModules_21_statement_children_helper <.. sqlparse.RepoObject_SqlModules_31_object
sqlparse.RepoObject_SqlModules_22_identifier_alias_AS <.. sqlparse.RepoObject_SqlModules_41_from
sqlparse.RepoObject_SqlModules_24_IdentifierList_children <.. sqlparse.RepoObject_SqlModules_25_IdentifierList_children_IdentifierSplit
sqlparse.RepoObject_SqlModules_25_IdentifierList_children_IdentifierSplit <.. sqlparse.RepoObject_SqlModules_26_IdentifierList_children_IdentifierSplit_QuoteName
sqlparse.RepoObject_SqlModules_26_IdentifierList_children_IdentifierSplit_QuoteName <.. sqlparse.RepoObject_SqlModules_61_SelectIdentifier_Union
sqlparse.RepoObject_SqlModules_29_1_object_is_union <.. sqlparse.RepoObject_SqlModules_39_object
sqlparse.RepoObject_SqlModules_29_1_object_is_union <.. sqlparse.RepoObject_SqlModules_42_from_Identifier
sqlparse.RepoObject_SqlModules_29_2_object_is_GroupBy <.. sqlparse.RepoObject_SqlModules_39_object
sqlparse.RepoObject_SqlModules_31_object <.. sqlparse.RepoObject_SqlModules_39_object
sqlparse.RepoObject_SqlModules_32_ObjectClass <.. sqlparse.RepoObject_SqlModules_39_object
sqlparse.RepoObject_SqlModules_33_ObjectNormalized <.. sqlparse.RepoObject_SqlModules_39_object
sqlparse.RepoObject_SqlModules_39_object <.. sqlparse.RepoObject_SqlModules_41_from
sqlparse.RepoObject_SqlModules_39_object <.. sqlparse.RepoObject_SqlModules_61_SelectIdentifier_Union
sqlparse.RepoObject_SqlModules_41_from <.. sqlparse.usp_PERSIST_RepoObject_SqlModules_41_from_T
sqlparse.RepoObject_SqlModules_41_from <.. sqlparse.RepoObject_SqlModules_41_from_T
sqlparse.RepoObject_SqlModules_41_from_T <.. sqlparse.usp_PERSIST_RepoObject_SqlModules_41_from_T
sqlparse.RepoObject_SqlModules_41_from_T <.. sqlparse.RepoObject_SqlModules_42_from_Identifier
sqlparse.RepoObject_SqlModules_42_from_Identifier <.. sqlparse.RepoObject_SqlModules_43_from_Identifier
sqlparse.RepoObject_SqlModules_43_from_Identifier <.. sqlparse.RepoObject_SqlModules_44_from_Identifier_QuoteName
sqlparse.RepoObject_SqlModules_44_from_Identifier_QuoteName <.. sqlparse.RepoObject_SqlModules_72_reference_NoTableAlias
sqlparse.RepoObject_SqlModules_44_from_Identifier_QuoteName <.. sqlparse.RepoObject_SqlModules_71_reference_ExpliciteTableAlias
sqlparse.RepoObject_SqlModules_51_Identitfier <.. sqlparse.RepoObject_SqlModules_52_Identitfier_QuoteName
sqlparse.RepoObject_SqlModules_52_Identitfier_QuoteName <.. sqlparse.RepoObject_SqlModules_61_SelectIdentifier_Union
sqlparse.RepoObject_SqlModules_61_SelectIdentifier_Union <.. sqlparse.RepoObject_SqlModules_61_SelectIdentifier_Union_T
sqlparse.RepoObject_SqlModules_61_SelectIdentifier_Union <.. sqlparse.usp_PERSIST_RepoObject_SqlModules_61_SelectIdentifier_Union_T
sqlparse.RepoObject_SqlModules_61_SelectIdentifier_Union_T <.. sqlparse.RepoObject_SqlModules_71_reference_ExpliciteTableAlias
sqlparse.RepoObject_SqlModules_61_SelectIdentifier_Union_T <.. sqlparse.usp_PERSIST_RepoObject_SqlModules_61_SelectIdentifier_Union_T
sqlparse.RepoObject_SqlModules_61_SelectIdentifier_Union_T <.. sqlparse.RepoObject_SqlModules_72_reference_NoTableAlias
sqlparse.RepoObject_SqlModules_71_reference_ExpliciteTableAlias <.. sqlparse.RepoObject_SqlModules_79_reference_union
sqlparse.RepoObject_SqlModules_72_reference_NoTableAlias <.. sqlparse.RepoObject_SqlModules_79_reference_union
sqlparse.RepoObject_SqlModules_79_reference_union <.. reference.RepoObjectColumn_reference_SqlModules
sqlparse.RepoObject_SqlModules_Repo_Sys <.. property.RepoObjectProperty_Collect_source_sql_modules_definition
sqlparse.RepoObject_SqlModules_Repo_Sys <.. repo.RepoObject_sat2
sqlparse.RepoObject_SqlModules_Repo_Sys <.. repo.RepoObject_gross2
sqlparse.usp_PERSIST_RepoObject_SqlModules_41_from_T <.. sqlparse.usp_sqlparse
sqlparse.usp_PERSIST_RepoObject_SqlModules_61_SelectIdentifier_Union_T <.. sqlparse.usp_sqlparse
ssas.Measure_translation <.. ssas.usp_PERSIST_Measure_translation_T
ssas.Measure_translation <.. ssas.Measure_translation_T
ssas.Measure_translation_displayfolder_union <.. docs.RepoObject_MeasureList
ssas.Measure_translation_T <.. docs.RepoObject_MeasureDescriptionList
ssas.Measure_translation_T <.. ssas.usp_PERSIST_Measure_translation_T
ssas.Measure_translation_T <.. ssas.Measure_translation_displayfolder_union
ssas.model_json_201_descriptions_multiline <.. ssas.model_json_2011_descriptions_StrAgg
ssas.model_json_2011_descriptions_StrAgg <.. repo.RepoSchema_ssas_src
ssas.RepoObjectColumn_translation <.. ssas.usp_PERSIST_RepoObjectColumn_translation_T
ssas.RepoObjectColumn_translation <.. ssas.RepoObjectColumn_translation_T
ssas.RepoObjectColumn_translation_displayfolder_union <.. docs.RepoObject_ColumnList
ssas.RepoObjectColumn_translation_T <.. ssas.RepoObjectColumn_translation_displayfolder_union
ssas.RepoObjectColumn_translation_T <.. docs.RepoObject_Plantuml_ColRefList_1_1
ssas.RepoObjectColumn_translation_T <.. ssas.usp_PERSIST_RepoObjectColumn_translation_T
ssas.usp_PERSIST_Measure_translation_T <.. repo.usp_sync_guid_ssas
ssas.usp_PERSIST_RepoObjectColumn_translation_T <.. repo.usp_main
uspgenerator.GeneratorUsp_SqlUsp <.. property.RepoObjectProperty_Collect_source_uspgenerator
uspgenerator.GeneratorUspStep_Persistence_IsInactive_setpoint <.. uspgenerator.usp_GeneratorUsp_insert_update_persistence
uspgenerator.GeneratorUspStep_Persistence_src <.. uspgenerator.usp_GeneratorUsp_insert_update_persistence
uspgenerator.usp_GeneratorUsp_insert_update_persistence <.. repo.usp_main
workflow.Biml_Package <.. workflow.Biml_Project
workflow.Biml_PrecedenceConstraints <.. workflow.Biml_Task
workflow.Biml_Task <.. workflow.Biml_Package
workflow.ProcedureDependency <.. workflow.ProcedureDependency_gross
workflow.ProcedureDependency <.. workflow.ProcedureDependency_input_PersistenceDependency
workflow.ProcedureDependency <.. workflow.Workflow_ProcedureDependency_all
workflow.ProcedureDependency <.. workflow.Workflow_ProcedureDependency
workflow.ProcedureDependency_PersistenceDependency_src <.. workflow.usp_PERSIST_ProcedureDependency_PersistenceDependency_tgt
workflow.ProcedureDependency_PersistenceDependency_src <.. workflow.ProcedureDependency_PersistenceDependency_tgt
workflow.ProcedureDependency_PersistenceDependency_tgt <.. workflow.usp_PERSIST_ProcedureDependency_PersistenceDependency_tgt
workflow.ProcedureDependency_PersistenceDependency_tgt <.. workflow.ProcedureDependency
workflow.usp_PERSIST_ProcedureDependency_PersistenceDependency_tgt <.. workflow.usp_workflow
workflow.usp_PERSIST_Workflow_ProcedureDependency_T <.. workflow.usp_workflow
workflow.usp_PERSIST_WorkflowStep <.. workflow.usp_workflow
workflow.Workflow_ProcedureDependency <.. workflow.Workflow_ProcedureDependency_T
workflow.Workflow_ProcedureDependency <.. workflow.usp_PERSIST_Workflow_ProcedureDependency_T
workflow.Workflow_ProcedureDependency_all <.. workflow.Workflow_ProcedureDependency_wo_redundant
workflow.Workflow_ProcedureDependency_T <.. workflow.usp_workflow
workflow.Workflow_ProcedureDependency_T <.. workflow.Workflow_ProcedureDependency_T_bidirectional
workflow.Workflow_ProcedureDependency_T <.. workflow.usp_PERSIST_Workflow_ProcedureDependency_T
workflow.Workflow_ProcedureDependency_T <.. workflow.Workflow_ProcedureDependency_T_active
workflow.Workflow_ProcedureDependency_T_active <.. workflow.Workflow_ProcedureDependency_T_redundant
workflow.Workflow_ProcedureDependency_T_active <.. workflow.Workflow_ProcedureDependency_T_NotInSortorder
workflow.Workflow_ProcedureDependency_T_active <.. workflow.Workflow_ProcedureDependency_T_TaskName
workflow.Workflow_ProcedureDependency_T_bidirectional <.. workflow.Workflow_ProcedureDependency_T_bidirectional_T
workflow.Workflow_ProcedureDependency_T_bidirectional <.. workflow.usp_workflow
workflow.Workflow_ProcedureDependency_T_NotInSortorder <.. workflow.Workflow_ProcedureDependency_T_NotInSortorder_check
workflow.Workflow_ProcedureDependency_T_NotInSortorder <.. workflow.usp_workflow
workflow.Workflow_ProcedureDependency_T_NotInSortorder_check <.. workflow.usp_workflow
workflow.Workflow_ProcedureDependency_T_redundant <.. workflow.Workflow_ProcedureDependency_wo_redundant
workflow.Workflow_ProcedureDependency_T_redundant <.. workflow.usp_workflow
workflow.Workflow_ProcedureDependency_T_TaskName <.. workflow.Biml_PrecedenceConstraints
workflow.Workflow_UspList <.. workflow.Workflow_SqlUsp
workflow.WorkflowStep <.. workflow.WorkflowStep_ForUpdate
workflow.WorkflowStep <.. workflow.WorkflowStep_active
workflow.WorkflowStep <.. workflow.usp_PERSIST_WorkflowStep
workflow.WorkflowStep_active <.. workflow.Workflow_ProcedureDependency_T_active
workflow.WorkflowStep_active <.. workflow.Workflow_ProcedureDependency
workflow.WorkflowStep_active <.. workflow.Biml_Task
workflow.WorkflowStep_active <.. workflow.Workflow_ProcedureDependency_all
workflow.WorkflowStep_active <.. workflow.usp_workflow
workflow.WorkflowStep_src <.. workflow.WorkflowStep
workflow.WorkflowStep_src <.. workflow.usp_PERSIST_WorkflowStep

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_0_30_objectref[]

=== PlantUML 1 1 ColumnRef

// tag::puml_entity_1_1_colref[]
[plantuml, entity_1_1_colref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssas.model_json_20.adoc[]" as ssas.model_json_20 << V >> {
  - databasename : (nvarchar(128))
  l1_compatibilityLevel : (int)
  l1_id : (nvarchar(500))
  l1_name : (nvarchar(500))
  l2_annotations_ja : (nvarchar(max))
  l2_culture : (nvarchar(500))
  l2_cultures_ja : (nvarchar(max))
  l2_dataSources_ja : (nvarchar(max))
  l2_description : (nvarchar(max))
  l2_description_ja : (nvarchar(max))
  l2_name : (nvarchar(500))
  l2_perspectives_ja : (nvarchar(max))
  l2_relationships_ja : (nvarchar(max))
  l2_roles_ja : (nvarchar(max))
  l2_tables_ja : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_201_descriptions_multiline.adoc[]" as ssas.model_json_201_descriptions_multiline << V >> {
  - databasename : (nvarchar(128))
  - Key : (nvarchar(4000))
  - Type : (tinyint)
  Value : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_2011_descriptions_stragg.adoc[]" as ssas.model_json_2011_descriptions_StrAgg << V >> {
  - databasename : (nvarchar(128))
  descriptions_StrAgg : (nvarchar(max))
  --
}

ssas.model_json_20 <.. ssas.model_json_201_descriptions_multiline
ssas.model_json_201_descriptions_multiline <.. ssas.model_json_2011_descriptions_StrAgg
"ssas.model_json_20::databasename" <-- "ssas.model_json_201_descriptions_multiline::databasename"
"ssas.model_json_201_descriptions_multiline::databasename" <-- "ssas.model_json_2011_descriptions_StrAgg::databasename"

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_colref[]


== sql_modules_definition

// tag::sql_modules_definition[]
[%collapsible]
=======
[source,sql,numbered,indent=0]
----

/*
Select
    Distinct
    j2.[Key]
  , j2.[value]
  , j2.Type
From
    ssas.model_json_20 As T1
    Cross Apply OpenJson ( T1.l2_description_ja )
                --As j1
                --Cross Apply OpenJson ( j1.Value )
                       As j2
order by
    j2.[Key]
Go
*/

CREATE View ssas.model_json_201_descriptions_multiline
As
Select
    T1.databasename
  , j2.[Key]
  , j2.Value
  , j2.Type
From
    ssas.model_json_20 As T1
    Cross Apply OpenJson ( T1.l2_description_ja )
                --As j1
                --Cross Apply OpenJson ( j1.Value )
                       As j2

----
=======
// end::sql_modules_definition[]


