// tag::HeaderFullDisplayName[]
= ssas.model_json_3411121_cultures_translations_model_tables_hierarchies_levels - V
// end::HeaderFullDisplayName[]

== existing_properties

// tag::existing_properties[]

:ExistsProperty--antorareferencedlist:
:ExistsProperty--is_repo_managed:
:ExistsProperty--is_ssas:
:ExistsProperty--referencedobjectlist:
:ExistsProperty--sql_modules_definition:
:ExistsProperty--FK:
:ExistsProperty--AntoraIndexList:
:ExistsProperty--Columns:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
1009DA81-C322-EC11-8524-A81E8446D5B0
// end::RepoObject_guid[]

== RepoObject_FullDisplayName2

// tag::RepoObject_FullDisplayName2[]
ssas.model_json_3411121_cultures_translations_model_tables_hierarchies_levels
// end::RepoObject_FullDisplayName2[]

== SysObject_type

// tag::SysObject_type[]
V 
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
view
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
1497108424
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2021-10-01 15:27:22
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]
[discrete]
== _


[#column-culturesunderlinename]
=== cultures_name

[cols="d,8a,m,m,m"]
|===
|
|cultures_name
|nvarchar(10)
|NOT NULL
|
|===

.Referenced Columns
--
* xref:ssas.model_json_341112_cultures_translations_model_tables_hierarchies.adoc#column-culturesunderlinename[+ssas.model_json_341112_cultures_translations_model_tables_hierarchies.cultures_name+]
--


[#column-culturesunderlinetranslationsunderlinemodelunderlinename]
=== cultures_translations_model_name

[cols="d,8a,m,m,m"]
|===
|
|cultures_translations_model_name
|nvarchar(500)
|NOT NULL
|
|===

.Referenced Columns
--
* xref:ssas.model_json_341112_cultures_translations_model_tables_hierarchies.adoc#column-culturesunderlinetranslationsunderlinemodelunderlinename[+ssas.model_json_341112_cultures_translations_model_tables_hierarchies.cultures_translations_model_name+]
--


[#column-culturesunderlinetranslationsunderlinemodelunderlinetablesunderlinehierarchiesunderlinelevelsunderlinename]
=== cultures_translations_model_tables_hierarchies_levels_name

[cols="d,8a,m,m,m"]
|===
|
|cultures_translations_model_tables_hierarchies_levels_name
|nvarchar(128)
|NULL
|
|===


[#column-culturesunderlinetranslationsunderlinemodelunderlinetablesunderlinehierarchiesunderlinelevelsunderlinetranslatedcaption]
=== cultures_translations_model_tables_hierarchies_levels_translatedCaption

[cols="d,8a,m,m,m"]
|===
|
|cultures_translations_model_tables_hierarchies_levels_translatedCaption
|nvarchar(128)
|NULL
|
|===


[#column-culturesunderlinetranslationsunderlinemodelunderlinetablesunderlinehierarchiesunderlinename]
=== cultures_translations_model_tables_hierarchies_name

[cols="d,8a,m,m,m"]
|===
|
|cultures_translations_model_tables_hierarchies_name
|nvarchar(128)
|NULL
|
|===

.Referenced Columns
--
* xref:ssas.model_json_341112_cultures_translations_model_tables_hierarchies.adoc#column-culturesunderlinetranslationsunderlinemodelunderlinetablesunderlinehierarchiesunderlinename[+ssas.model_json_341112_cultures_translations_model_tables_hierarchies.cultures_translations_model_tables_hierarchies_name+]
--


[#column-culturesunderlinetranslationsunderlinemodelunderlinetablesunderlinename]
=== cultures_translations_model_tables_name

[cols="d,8a,m,m,m"]
|===
|
|cultures_translations_model_tables_name
|nvarchar(128)
|NULL
|
|===

.Referenced Columns
--
* xref:ssas.model_json_341112_cultures_translations_model_tables_hierarchies.adoc#column-culturesunderlinetranslationsunderlinemodelunderlinetablesunderlinename[+ssas.model_json_341112_cultures_translations_model_tables_hierarchies.cultures_translations_model_tables_name+]
--


[#column-databasename]
=== databasename

[cols="d,8a,m,m,m"]
|===
|
|databasename
|nvarchar(128)
|NOT NULL
|
|===

.Referenced Columns
--
* xref:ssas.model_json_341112_cultures_translations_model_tables_hierarchies.adoc#column-databasename[+ssas.model_json_341112_cultures_translations_model_tables_hierarchies.databasename+]
--


// end::AntoraColumnDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]







// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]
|
|<<column-culturesunderlinename>>
|nvarchar(10)
|NOT NULL
|

|
|<<column-culturesunderlinetranslationsunderlinemodelunderlinename>>
|nvarchar(500)
|NOT NULL
|

|
|<<column-culturesunderlinetranslationsunderlinemodelunderlinetablesunderlinehierarchiesunderlinelevelsunderlinename>>
|nvarchar(128)
|NULL
|

|
|<<column-culturesunderlinetranslationsunderlinemodelunderlinetablesunderlinehierarchiesunderlinelevelsunderlinetranslatedcaption>>
|nvarchar(128)
|NULL
|

|
|<<column-culturesunderlinetranslationsunderlinemodelunderlinetablesunderlinehierarchiesunderlinename>>
|nvarchar(128)
|NULL
|

|
|<<column-culturesunderlinetranslationsunderlinemodelunderlinetablesunderlinename>>
|nvarchar(128)
|NULL
|

|
|<<column-databasename>>
|nvarchar(128)
|NOT NULL
|

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

[#index-idxunderlinemodelunderlinejsonunderline3411121underlineculturesunderlinetranslationsunderlinemodelunderlinetablesunderlinehierarchiesunderlinelevelsunderlineunderline1]
=== idx_model_json_3411121_cultures_translations_model_tables_hierarchies_levels++__++1

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-databasename>>; nvarchar(128)
* <<column-cultures_name>>; nvarchar(10)
--
* PK, Unique, Real: 0, 0, 0


[#index-idxunderlinemodelunderlinejsonunderline3411121underlineculturesunderlinetranslationsunderlinemodelunderlinetablesunderlinehierarchiesunderlinelevelsunderlineunderline2]
=== idx_model_json_3411121_cultures_translations_model_tables_hierarchies_levels++__++2

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-databasename>>; nvarchar(128)
* <<column-cultures_name>>; nvarchar(10)
* <<column-cultures_translations_model_name>>; nvarchar(500)
--
* PK, Unique, Real: 0, 0, 0


[#index-idxunderlinemodelunderlinejsonunderline3411121underlineculturesunderlinetranslationsunderlinemodelunderlinetablesunderlinehierarchiesunderlinelevelsunderlineunderline3]
=== idx_model_json_3411121_cultures_translations_model_tables_hierarchies_levels++__++3

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-databasename>>; nvarchar(128)
--
* PK, Unique, Real: 0, 0, 0

// end::AntoraIndexList[]

== AntoraMeasureDetails

// tag::AntoraMeasureDetails[]

// end::AntoraMeasureDetails[]

== AntoraMeasureDescriptions



== AntoraParameterList

// tag::AntoraParameterList[]

// end::AntoraParameterList[]

== AntoraXrefCulturesList

// tag::AntoraXrefCulturesList[]
* xref:dhw:sqldb:ssas.model_json_3411121_cultures_translations_model_tables_hierarchies_levels.adoc[] - 
// end::AntoraXrefCulturesList[]

== cultures_count

// tag::cultures_count[]
1
// end::cultures_count[]

== Other tags

source: property.RepoObjectProperty_cross As rop_cross


=== additional_reference_csv

// tag::additional_reference_csv[]

// end::additional_reference_csv[]


=== AdocUspSteps

// tag::adocuspsteps[]

// end::adocuspsteps[]


=== AntoraReferencedList

// tag::antorareferencedlist[]
* xref:dhw:sqldb:ssas.model_json_341112_cultures_translations_model_tables_hierarchies.adoc[]
// end::antorareferencedlist[]


=== AntoraReferencingList

// tag::antorareferencinglist[]

// end::antorareferencinglist[]


=== Description

// tag::description[]

// end::description[]


=== exampleUsage

// tag::exampleusage[]

// end::exampleusage[]


=== exampleUsage_2

// tag::exampleusage_2[]

// end::exampleusage_2[]


=== exampleUsage_3

// tag::exampleusage_3[]

// end::exampleusage_3[]


=== exampleUsage_4

// tag::exampleusage_4[]

// end::exampleusage_4[]


=== exampleUsage_5

// tag::exampleusage_5[]

// end::exampleusage_5[]


=== exampleWrong_Usage

// tag::examplewrong_usage[]

// end::examplewrong_usage[]


=== has_execution_plan_issue

// tag::has_execution_plan_issue[]

// end::has_execution_plan_issue[]


=== has_get_referenced_issue

// tag::has_get_referenced_issue[]

// end::has_get_referenced_issue[]


=== has_history

// tag::has_history[]

// end::has_history[]


=== has_history_columns

// tag::has_history_columns[]

// end::has_history_columns[]


=== InheritanceType

// tag::inheritancetype[]

// end::inheritancetype[]


=== is_persistence

// tag::is_persistence[]

// end::is_persistence[]


=== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]

// end::is_persistence_check_duplicate_per_pk[]


=== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]

// end::is_persistence_check_for_empty_source[]


=== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]

// end::is_persistence_delete_changed[]


=== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]

// end::is_persistence_delete_missing[]


=== is_persistence_insert

// tag::is_persistence_insert[]

// end::is_persistence_insert[]


=== is_persistence_truncate

// tag::is_persistence_truncate[]

// end::is_persistence_truncate[]


=== is_persistence_update_changed

// tag::is_persistence_update_changed[]

// end::is_persistence_update_changed[]


=== is_repo_managed

// tag::is_repo_managed[]
0
// end::is_repo_managed[]


=== is_ssas

// tag::is_ssas[]
0
// end::is_ssas[]


=== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


=== MS_Description

// tag::ms_description[]

// end::ms_description[]


=== persistence_source_RepoObject_fullname

// tag::persistence_source_repoobject_fullname[]

// end::persistence_source_repoobject_fullname[]


=== persistence_source_RepoObject_fullname2

// tag::persistence_source_repoobject_fullname2[]

// end::persistence_source_repoobject_fullname2[]


=== persistence_source_RepoObject_guid

// tag::persistence_source_repoobject_guid[]

// end::persistence_source_repoobject_guid[]


=== persistence_source_RepoObject_xref

// tag::persistence_source_repoobject_xref[]

// end::persistence_source_repoobject_xref[]


=== pk_index_guid

// tag::pk_index_guid[]

// end::pk_index_guid[]


=== pk_IndexPatternColumnDatatype

// tag::pk_indexpatterncolumndatatype[]

// end::pk_indexpatterncolumndatatype[]


=== pk_IndexPatternColumnName

// tag::pk_indexpatterncolumnname[]

// end::pk_indexpatterncolumnname[]


=== pk_IndexSemanticGroup

// tag::pk_indexsemanticgroup[]

// end::pk_indexsemanticgroup[]


=== ReferencedObjectList

// tag::referencedobjectlist[]
* [ssas].[model_json_341112_cultures_translations_model_tables_hierarchies]
// end::referencedobjectlist[]


=== usp_persistence_RepoObject_guid

// tag::usp_persistence_repoobject_guid[]

// end::usp_persistence_repoobject_guid[]


=== UspExamples

// tag::uspexamples[]

// end::uspexamples[]


=== uspgenerator_usp_id

// tag::uspgenerator_usp_id[]

// end::uspgenerator_usp_id[]


=== UspParameters

// tag::uspparameters[]

// end::uspparameters[]

== Boolean Attributes

source: property.RepoObjectProperty WHERE property_int = 1

// tag::boolean_attributes[]


// end::boolean_attributes[]

== PlantUML diagrams

=== PlantUML Entity

// tag::puml_entity[]
[plantuml, entity-{docname}, svg, subs=macros]
....
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssas.model_json_3411121_cultures_translations_model_tables_hierarchies_levels.adoc[]" as ssas.model_json_3411121_cultures_translations_model_tables_hierarchies_levels << V >> {
  - cultures_name : (nvarchar(10))
  - cultures_translations_model_name : (nvarchar(500))
  cultures_translations_model_tables_hierarchies_levels_name : (nvarchar(128))
  cultures_translations_model_tables_hierarchies_levels_translatedCaption : (nvarchar(128))
  cultures_translations_model_tables_hierarchies_name : (nvarchar(128))
  cultures_translations_model_tables_name : (nvarchar(128))
  - databasename : (nvarchar(128))
  --
}
....

// end::puml_entity[]

=== PlantUML Entity 1 1 FK

// tag::puml_entity_1_1_fk[]
[plantuml, entity_1_1_fk-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssas.model_json_3411121_cultures_translations_model_tables_hierarchies_levels.adoc[]" as ssas.model_json_3411121_cultures_translations_model_tables_hierarchies_levels << V >> {
- idx_model_json_3411121_cultures_translations_model_tables_hierarchies_levels__1

..
databasename; nvarchar(128)
cultures_name; nvarchar(10)
--
- idx_model_json_3411121_cultures_translations_model_tables_hierarchies_levels__2

..
databasename; nvarchar(128)
cultures_name; nvarchar(10)
cultures_translations_model_name; nvarchar(500)
--
- idx_model_json_3411121_cultures_translations_model_tables_hierarchies_levels__3

..
databasename; nvarchar(128)
}



footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_fk[]

=== PlantUML 1 1 ObjectRef

// tag::puml_entity_1_1_objectref[]
[plantuml, entity_1_1_objectref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssas.model_json_341112_cultures_translations_model_tables_hierarchies.adoc[]" as ssas.model_json_341112_cultures_translations_model_tables_hierarchies << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_3411121_cultures_translations_model_tables_hierarchies_levels.adoc[]" as ssas.model_json_3411121_cultures_translations_model_tables_hierarchies_levels << V >> {
  --
}

ssas.model_json_341112_cultures_translations_model_tables_hierarchies <.. ssas.model_json_3411121_cultures_translations_model_tables_hierarchies_levels

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_objectref[]

=== PlantUML 30 0 ObjectRef

// tag::puml_entity_30_0_objectref[]
[plantuml, entity_30_0_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssas.model_json.adoc[]" as ssas.model_json << U >> {
  - **databasename** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_10.adoc[]" as ssas.model_json_10 << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_20.adoc[]" as ssas.model_json_20 << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_34_cultures.adoc[]" as ssas.model_json_34_cultures << V >> {
  - **databasename** : (nvarchar(128))
  **cultures_name** : (nvarchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_341_cultures_translations.adoc[]" as ssas.model_json_341_cultures_translations << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_3411_cultures_translations_model.adoc[]" as ssas.model_json_3411_cultures_translations_model << V >> {
  - **databasename** : (nvarchar(128))
  **cultures_name** : (nvarchar(500))
  **cultures_translations_model_name** : (nvarchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_3411_cultures_translations_model_t.adoc[]" as ssas.model_json_3411_cultures_translations_model_T << U >> {
  - **databasename** : (nvarchar(128))
  **cultures_name** : (nvarchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_34111_cultures_translations_model_tables.adoc[]" as ssas.model_json_34111_cultures_translations_model_tables << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_341112_cultures_translations_model_tables_hierarchies.adoc[]" as ssas.model_json_341112_cultures_translations_model_tables_hierarchies << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_3411121_cultures_translations_model_tables_hierarchies_levels.adoc[]" as ssas.model_json_3411121_cultures_translations_model_tables_hierarchies_levels << V >> {
  --
}

ssas.model_json <.. ssas.model_json_10
ssas.model_json_10 <.. ssas.model_json_20
ssas.model_json_20 <.. ssas.model_json_34_cultures
ssas.model_json_34_cultures <.. ssas.model_json_341_cultures_translations
ssas.model_json_341_cultures_translations <.. ssas.model_json_3411_cultures_translations_model
ssas.model_json_3411_cultures_translations_model <.. ssas.model_json_3411_cultures_translations_model_T
ssas.model_json_3411_cultures_translations_model_T <.. ssas.model_json_34111_cultures_translations_model_tables
ssas.model_json_34111_cultures_translations_model_tables <.. ssas.model_json_341112_cultures_translations_model_tables_hierarchies
ssas.model_json_341112_cultures_translations_model_tables_hierarchies <.. ssas.model_json_3411121_cultures_translations_model_tables_hierarchies_levels

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_30_0_objectref[]

=== PlantUML 0 30 ObjectRef

// tag::puml_entity_0_30_objectref[]
[plantuml, entity_0_30_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssas.model_json_3411121_cultures_translations_model_tables_hierarchies_levels.adoc[]" as ssas.model_json_3411121_cultures_translations_model_tables_hierarchies_levels << V >> {
  --
}



footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_0_30_objectref[]

=== PlantUML 1 1 ColumnRef

// tag::puml_entity_1_1_colref[]
[plantuml, entity_1_1_colref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssas.model_json_341112_cultures_translations_model_tables_hierarchies.adoc[]" as ssas.model_json_341112_cultures_translations_model_tables_hierarchies << V >> {
  - cultures_name : (nvarchar(10))
  - cultures_translations_model_name : (nvarchar(500))
  cultures_translations_model_tables_hierarchies_levels_ja : (nvarchar(max))
  cultures_translations_model_tables_hierarchies_name : (nvarchar(128))
  cultures_translations_model_tables_hierarchies_translatedCaption : (nvarchar(128))
  cultures_translations_model_tables_name : (nvarchar(128))
  - databasename : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_3411121_cultures_translations_model_tables_hierarchies_levels.adoc[]" as ssas.model_json_3411121_cultures_translations_model_tables_hierarchies_levels << V >> {
  - cultures_name : (nvarchar(10))
  - cultures_translations_model_name : (nvarchar(500))
  cultures_translations_model_tables_hierarchies_levels_name : (nvarchar(128))
  cultures_translations_model_tables_hierarchies_levels_translatedCaption : (nvarchar(128))
  cultures_translations_model_tables_hierarchies_name : (nvarchar(128))
  cultures_translations_model_tables_name : (nvarchar(128))
  - databasename : (nvarchar(128))
  --
}

ssas.model_json_341112_cultures_translations_model_tables_hierarchies <.. ssas.model_json_3411121_cultures_translations_model_tables_hierarchies_levels
"ssas.model_json_341112_cultures_translations_model_tables_hierarchies::cultures_name" <-- "ssas.model_json_3411121_cultures_translations_model_tables_hierarchies_levels::cultures_name"
"ssas.model_json_341112_cultures_translations_model_tables_hierarchies::cultures_translations_model_name" <-- "ssas.model_json_3411121_cultures_translations_model_tables_hierarchies_levels::cultures_translations_model_name"
"ssas.model_json_341112_cultures_translations_model_tables_hierarchies::cultures_translations_model_tables_hierarchies_name" <-- "ssas.model_json_3411121_cultures_translations_model_tables_hierarchies_levels::cultures_translations_model_tables_hierarchies_name"
"ssas.model_json_341112_cultures_translations_model_tables_hierarchies::cultures_translations_model_tables_name" <-- "ssas.model_json_3411121_cultures_translations_model_tables_hierarchies_levels::cultures_translations_model_tables_name"
"ssas.model_json_341112_cultures_translations_model_tables_hierarchies::databasename" <-- "ssas.model_json_3411121_cultures_translations_model_tables_hierarchies_levels::databasename"

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_colref[]


== sql_modules_definition

// tag::sql_modules_definition[]
[%collapsible]
=======
[source,sql,numbered,indent=0]
----

/*
--get and check existing values

Select
    Distinct
    j2.[Key]
  , j2.Type
From
    ssas.model_json_341112_cultures_translations_model_tables_hierarchies                      As T1
    Cross Apply OpenJson ( T1.cultures_translations_model_tables_hierarchies_levels_ja ) As j1
    Cross Apply OpenJson ( j1.Value ) As j2
Order by
    j2.[Key]
  , j2.Type
Go

Select
    T1.*
  , j2.*
From
    ssas.model_json_341112_cultures_translations_model_tables_hierarchies                      As T1
    Cross Apply OpenJson ( T1.cultures_translations_model_tables_hierarchies_levels_ja ) As j1
    Cross Apply OpenJson ( j1.Value ) As j2
Go

Select
    j2.*
From
    ssas.model_json_341112_cultures_translations_model_tables_hierarchies                      As T1
    Cross Apply OpenJson ( T1.cultures_translations_model_tables_hierarchies_levels_ja ) As j1
    Cross Apply OpenJson ( j1.Value ) As j2
Where
    j2.[Key] = 'columns'

Select
    j2.*
From
    ssas.model_json_341112_cultures_translations_model_tables_hierarchies                      As T1
    Cross Apply OpenJson ( T1.cultures_translations_model_tables_hierarchies_levels_ja ) As j1
    Cross Apply OpenJson ( j1.Value ) As j2
Where
    j2.[Key] = 'measures'
Go

*/
create View ssas.model_json_3411121_cultures_translations_model_tables_hierarchies_levels
As
Select
    T1.databasename
  , T1.cultures_name
  , T1.cultures_translations_model_name
  , T1.cultures_translations_model_tables_name
  , T1.cultures_translations_model_tables_hierarchies_name
  , j2.cultures_translations_model_tables_hierarchies_levels_name
  , j2.cultures_translations_model_tables_hierarchies_levels_translatedCaption
From
    ssas.model_json_341112_cultures_translations_model_tables_hierarchies                As T1
    Cross Apply OpenJson ( T1.cultures_translations_model_tables_hierarchies_levels_ja ) As j1
    Cross Apply
    OpenJson ( j1.Value )
    With
    (
        cultures_translations_model_tables_hierarchies_levels_name NVarchar ( 128 ) N'$.name'
      , cultures_translations_model_tables_hierarchies_levels_translatedCaption NVarchar ( 128 ) N'$.translatedCaption'
    ) As j2

----
=======
// end::sql_modules_definition[]


