// tag::HeaderFullDisplayName[]
= ssas.model_json_312_tables_measures_T - U
// end::HeaderFullDisplayName[]

== existing_properties

// tag::existing_properties[]

:ExistsProperty--antorareferencedlist:
:ExistsProperty--antorareferencinglist:
:ExistsProperty--has_history:
:ExistsProperty--has_history_columns:
:ExistsProperty--inheritancetype:
:ExistsProperty--is_persistence:
:ExistsProperty--is_persistence_check_duplicate_per_pk:
:ExistsProperty--is_persistence_check_for_empty_source:
:ExistsProperty--is_persistence_delete_changed:
:ExistsProperty--is_persistence_delete_missing:
:ExistsProperty--is_persistence_insert:
:ExistsProperty--is_persistence_truncate:
:ExistsProperty--is_persistence_update_changed:
:ExistsProperty--is_repo_managed:
:ExistsProperty--is_ssas:
:ExistsProperty--persistence_source_repoobject_fullname:
:ExistsProperty--persistence_source_repoobject_fullname2:
:ExistsProperty--persistence_source_repoobject_guid:
:ExistsProperty--persistence_source_repoobject_xref:
:ExistsProperty--pk_index_guid:
:ExistsProperty--pk_indexpatterncolumndatatype:
:ExistsProperty--pk_indexpatterncolumnname:
:ExistsProperty--referencedobjectlist:
:ExistsProperty--usp_persistence_repoobject_guid:
:ExistsProperty--FK:
:ExistsProperty--AntoraIndexList:
:ExistsProperty--Columns:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
B2051757-370F-EC11-8518-A81E8446D5B0
// end::RepoObject_guid[]

== RepoObject_FullDisplayName2

// tag::RepoObject_FullDisplayName2[]
ssas.model_json_312_tables_measures_T
// end::RepoObject_FullDisplayName2[]

== SysObject_type

// tag::SysObject_type[]
U 
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
user table
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
1004582667
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2022-01-23 14:10:30
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]
[discrete]
== _


[#column-measureunderlineguid]
=== Measure_guid

[cols="d,8a,m,m,m"]
|===
|1
|*Measure_guid*

.Default: DF_model_json_312_tables_measures_T_RepoObjectColumn_guid
[source,sql]
----
(newsequentialid())
----


|uniqueidentifier
|NOT NULL
|
|===

.Referencing Columns
--
* xref:repo.measure.adoc#column-measureunderlineguid[+repo.Measure.Measure_guid+]
* xref:ssas.model_json_3121_tables_columns_descriptions_multiline.adoc#column-measureunderlineguid[+ssas.model_json_3121_tables_columns_descriptions_multiline.Measure_guid+]
* xref:ssas.model_json_3122_tables_measures_expressions_multiline.adoc#column-measureunderlineguid[+ssas.model_json_3122_tables_measures_expressions_multiline.Measure_guid+]
--


[#column-databasename]
=== databasename

[cols="d,8a,m,m,m"]
|===
|
|databasename
|nvarchar(128)
|NOT NULL
|
|===

.Referenced Columns
--
* xref:ssas.model_json_312_tables_measures.adoc#column-databasename[+ssas.model_json_312_tables_measures.databasename+]
--

.Referencing Columns
--
* xref:repo.measure.adoc#column-reposchemaunderlinename[+repo.Measure.RepoSchema_name+]
* xref:ssas.model_json_312_tables_measures_t.adoc#column-repoobjectunderlinefullname2[+ssas.model_json_312_tables_measures_T.RepoObject_fullname2+]
* xref:ssas.model_json_312_tables_measures_t.adoc#column-measureunderlinefullname[+ssas.model_json_312_tables_measures_T.Measure_fullname+]
* xref:ssas.model_json_312_tables_measures_t.adoc#column-measureunderlinefullname2[+ssas.model_json_312_tables_measures_T.Measure_fullname2+]
* xref:ssas.model_json_3121_tables_columns_descriptions_multiline.adoc#column-databasename[+ssas.model_json_3121_tables_columns_descriptions_multiline.databasename+]
* xref:ssas.model_json_3122_tables_measures_expressions_multiline.adoc#column-databasename[+ssas.model_json_3122_tables_measures_expressions_multiline.databasename+]
--


[#column-repoobjectunderlineguid]
=== RepoObject_guid

[cols="d,8a,m,m,m"]
|===
|
|RepoObject_guid
|uniqueidentifier
|NOT NULL
|
|===

.Referenced Columns
--
* xref:ssas.model_json_312_tables_measures.adoc#column-repoobjectunderlineguid[+ssas.model_json_312_tables_measures.RepoObject_guid+]
--

.Referencing Columns
--
* xref:repo.measure.adoc#column-repoobjectunderlineguid[+repo.Measure.RepoObject_guid+]
* xref:ssas.model_json_3121_tables_columns_descriptions_multiline.adoc#column-repoobjectunderlineguid[+ssas.model_json_3121_tables_columns_descriptions_multiline.RepoObject_guid+]
* xref:ssas.model_json_3122_tables_measures_expressions_multiline.adoc#column-repoobjectunderlineguid[+ssas.model_json_3122_tables_measures_expressions_multiline.RepoObject_guid+]
--


[#column-tablesunderlinemeasuresunderlinedescription]
=== tables_measures_description

[cols="d,8a,m,m,m"]
|===
|
|tables_measures_description
|nvarchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:ssas.model_json_312_tables_measures.adoc#column-tablesunderlinemeasuresunderlinedescription[+ssas.model_json_312_tables_measures.tables_measures_description+]
--

.Referencing Columns
--
* xref:repo.measure.adoc#column-measuresunderlinedescription[+repo.Measure.measures_description+]
--


[#column-tablesunderlinemeasuresunderlinedescriptionunderlineja]
=== tables_measures_description_ja

[cols="d,8a,m,m,m"]
|===
|
|tables_measures_description_ja
|nvarchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:ssas.model_json_312_tables_measures.adoc#column-tablesunderlinemeasuresunderlinedescriptionunderlineja[+ssas.model_json_312_tables_measures.tables_measures_description_ja+]
--

.Referencing Columns
--
* xref:repo.measure.adoc#column-measuresunderlinedescriptionunderlineja[+repo.Measure.measures_description_ja+]
--


[#column-tablesunderlinemeasuresunderlinedisplayfolder]
=== tables_measures_displayFolder

[cols="d,8a,m,m,m"]
|===
|
|tables_measures_displayFolder
|nvarchar(500)
|NULL
|
|===

.Referenced Columns
--
* xref:ssas.model_json_312_tables_measures.adoc#column-tablesunderlinemeasuresunderlinedisplayfolder[+ssas.model_json_312_tables_measures.tables_measures_displayFolder+]
--

.Referencing Columns
--
* xref:repo.measure.adoc#column-measuresunderlinedisplayfolder[+repo.Measure.measures_displayFolder+]
--


[#column-tablesunderlinemeasuresunderlineexpression]
=== tables_measures_expression

[cols="d,8a,m,m,m"]
|===
|
|tables_measures_expression
|nvarchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:ssas.model_json_312_tables_measures.adoc#column-tablesunderlinemeasuresunderlineexpression[+ssas.model_json_312_tables_measures.tables_measures_expression+]
--

.Referencing Columns
--
* xref:repo.measure.adoc#column-measuresunderlineexpression[+repo.Measure.measures_expression+]
--


[#column-tablesunderlinemeasuresunderlineexpressionunderlineja]
=== tables_measures_expression_ja

[cols="d,8a,m,m,m"]
|===
|
|tables_measures_expression_ja
|nvarchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:ssas.model_json_312_tables_measures.adoc#column-tablesunderlinemeasuresunderlineexpressionunderlineja[+ssas.model_json_312_tables_measures.tables_measures_expression_ja+]
--

.Referencing Columns
--
* xref:repo.measure.adoc#column-measuresunderlineexpressionunderlineja[+repo.Measure.measures_expression_ja+]
--


[#column-tablesunderlinemeasuresunderlineformatstring]
=== tables_measures_formatString

[cols="d,8a,m,m,m"]
|===
|
|tables_measures_formatString
|nvarchar(500)
|NULL
|
|===

.Referenced Columns
--
* xref:ssas.model_json_312_tables_measures.adoc#column-tablesunderlinemeasuresunderlineformatstring[+ssas.model_json_312_tables_measures.tables_measures_formatString+]
--

.Referencing Columns
--
* xref:repo.measure.adoc#column-measuresunderlineformatstring[+repo.Measure.measures_formatString+]
--


[#column-tablesunderlinemeasuresunderlineishidden]
=== tables_measures_isHidden

[cols="d,8a,m,m,m"]
|===
|
|tables_measures_isHidden
|bit
|NULL
|
|===

.Referenced Columns
--
* xref:ssas.model_json_312_tables_measures.adoc#column-tablesunderlinemeasuresunderlineishidden[+ssas.model_json_312_tables_measures.tables_measures_isHidden+]
--

.Referencing Columns
--
* xref:repo.measure.adoc#column-measuresunderlineishidden[+repo.Measure.measures_isHidden+]
--


[#column-tablesunderlinemeasuresunderlinename]
=== tables_measures_name

[cols="d,8a,m,m,m"]
|===
|
|tables_measures_name
|nvarchar(500)
|NOT NULL
|
|===

.Referenced Columns
--
* xref:ssas.model_json_312_tables_measures.adoc#column-tablesunderlinemeasuresunderlinename[+ssas.model_json_312_tables_measures.tables_measures_name+]
--

.Referencing Columns
--
* xref:repo.measure.adoc#column-measuresunderlinename[+repo.Measure.measures_name+]
* xref:ssas.model_json_312_tables_measures_t.adoc#column-measureunderlinefullname[+ssas.model_json_312_tables_measures_T.Measure_fullname+]
* xref:ssas.model_json_312_tables_measures_t.adoc#column-measureunderlinefullname2[+ssas.model_json_312_tables_measures_T.Measure_fullname2+]
* xref:ssas.model_json_3121_tables_columns_descriptions_multiline.adoc#column-tablesunderlinemeasuresunderlinename[+ssas.model_json_3121_tables_columns_descriptions_multiline.tables_measures_name+]
* xref:ssas.model_json_3122_tables_measures_expressions_multiline.adoc#column-tablesunderlinemeasuresunderlinename[+ssas.model_json_3122_tables_measures_expressions_multiline.tables_measures_name+]
--


[#column-tablesunderlinename]
=== tables_name

[cols="d,8a,m,m,m"]
|===
|
|tables_name
|nvarchar(128)
|NOT NULL
|
|===

.Referenced Columns
--
* xref:ssas.model_json_312_tables_measures.adoc#column-tablesunderlinename[+ssas.model_json_312_tables_measures.tables_name+]
--

.Referencing Columns
--
* xref:repo.measure.adoc#column-repoobjectunderlinename[+repo.Measure.RepoObject_name+]
* xref:ssas.model_json_312_tables_measures_t.adoc#column-repoobjectunderlinefullname2[+ssas.model_json_312_tables_measures_T.RepoObject_fullname2+]
* xref:ssas.model_json_3121_tables_columns_descriptions_multiline.adoc#column-tablesunderlinename[+ssas.model_json_3121_tables_columns_descriptions_multiline.tables_name+]
* xref:ssas.model_json_3122_tables_measures_expressions_multiline.adoc#column-tablesunderlinename[+ssas.model_json_3122_tables_measures_expressions_multiline.tables_name+]
--


[#column-measureunderlinefullname]
=== Measure_fullname

[cols="d,8a,m,m,m"]
|===
|
|Measure_fullname

.Definition (PERSISTED)
[source,sql]
----
((quotename([databasename])+'.')+quotename([tables_measures_name]))
----


|nvarchar(517)
|NULL
|
|===

.Description
--
((quotename([databasename])+'.')+quotename([tables_measures_name]))
--
{empty} +

.Referenced Columns
--
* xref:ssas.model_json_312_tables_measures_t.adoc#column-tablesunderlinemeasuresunderlinename[+ssas.model_json_312_tables_measures_T.tables_measures_name+]
* xref:ssas.model_json_312_tables_measures_t.adoc#column-databasename[+ssas.model_json_312_tables_measures_T.databasename+]
--

.Referencing Columns
--
* xref:repo.measure.adoc#column-measureunderlinefullname[+repo.Measure.Measure_fullname+]
--


[#column-measureunderlinefullname2]
=== Measure_fullname2

[cols="d,8a,m,m,m"]
|===
|
|Measure_fullname2

.Definition (PERSISTED)
[source,sql]
----
(([databasename]+'.measures.')+[tables_measures_name])
----


|nvarchar(638)
|NOT NULL
|
|===

.Description
--
(([databasename]+'.measures.')+[tables_measures_name])
--
{empty} +

.Referenced Columns
--
* xref:ssas.model_json_312_tables_measures_t.adoc#column-databasename[+ssas.model_json_312_tables_measures_T.databasename+]
* xref:ssas.model_json_312_tables_measures_t.adoc#column-tablesunderlinemeasuresunderlinename[+ssas.model_json_312_tables_measures_T.tables_measures_name+]
--

.Referencing Columns
--
* xref:repo.measure.adoc#column-measureunderlinefullname2[+repo.Measure.Measure_fullname2+]
--


[#column-repoobjectunderlinefullname2]
=== RepoObject_fullname2

[cols="d,8a,m,m,m"]
|===
|
|RepoObject_fullname2

.Definition (PERSISTED)
[source,sql]
----
(([databasename]+'.')+[tables_name])
----


|nvarchar(257)
|NOT NULL
|
|===

.Description
--
(([databasename]+'.')+[tables_name])
--
{empty} +

.Referenced Columns
--
* xref:ssas.model_json_312_tables_measures_t.adoc#column-databasename[+ssas.model_json_312_tables_measures_T.databasename+]
* xref:ssas.model_json_312_tables_measures_t.adoc#column-tablesunderlinename[+ssas.model_json_312_tables_measures_T.tables_name+]
--

.Referencing Columns
--
* xref:repo.measure.adoc#column-repoobjectunderlinefullname2[+repo.Measure.RepoObject_fullname2+]
--


// end::AntoraColumnDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]
|1
|*<<column-measureunderlineguid>>*

.Default: DF_model_json_312_tables_measures_T_RepoObjectColumn_guid
[source,sql]
----
(newsequentialid())
----


|uniqueidentifier
|NOT NULL
|















// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]

|
|<<column-databasename>>
|nvarchar(128)
|NOT NULL
|

|
|<<column-repoobjectunderlineguid>>
|uniqueidentifier
|NOT NULL
|

|
|<<column-tablesunderlinemeasuresunderlinedescription>>
|nvarchar(max)
|NULL
|

|
|<<column-tablesunderlinemeasuresunderlinedescriptionunderlineja>>
|nvarchar(max)
|NULL
|

|
|<<column-tablesunderlinemeasuresunderlinedisplayfolder>>
|nvarchar(500)
|NULL
|

|
|<<column-tablesunderlinemeasuresunderlineexpression>>
|nvarchar(max)
|NULL
|

|
|<<column-tablesunderlinemeasuresunderlineexpressionunderlineja>>
|nvarchar(max)
|NULL
|

|
|<<column-tablesunderlinemeasuresunderlineformatstring>>
|nvarchar(500)
|NULL
|

|
|<<column-tablesunderlinemeasuresunderlineishidden>>
|bit
|NULL
|

|
|<<column-tablesunderlinemeasuresunderlinename>>
|nvarchar(500)
|NOT NULL
|

|
|<<column-tablesunderlinename>>
|nvarchar(128)
|NOT NULL
|

|
|<<column-measureunderlinefullname>>

.Definition (PERSISTED)
[source,sql]
----
((quotename([databasename])+'.')+quotename([tables_measures_name]))
----


|nvarchar(517)
|NULL
|

|
|<<column-measureunderlinefullname2>>

.Definition (PERSISTED)
[source,sql]
----
(([databasename]+'.measures.')+[tables_measures_name])
----


|nvarchar(638)
|NOT NULL
|

|
|<<column-repoobjectunderlinefullname2>>

.Definition (PERSISTED)
[source,sql]
----
(([databasename]+'.')+[tables_name])
----


|nvarchar(257)
|NOT NULL
|

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

[#index-pkunderlinemodelunderlinejsonunderline312underlinetablesunderlinemeasuresunderlinet]
=== PK_model_json_312_tables_measures_T

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-Measure_guid>>; uniqueidentifier
--
* PK, Unique, Real: 1, 1, 1


[#index-ukunderlinemodelunderlinejsonunderline312underlinetablesunderlinemeasuresunderlinetunderlineunderline1]
=== UK_model_json_312_tables_measures_T++__++1

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#ssasunderlinetableunderlinemeasure[ssas_table_measure]
+
--
* <<column-databasename>>; nvarchar(128)
* <<column-tables_name>>; nvarchar(128)
* <<column-tables_measures_name>>; nvarchar(500)
--
* PK, Unique, Real: 0, 1, 0


[#index-idxunderlinemodelunderlinejsonunderline312underlinetablesunderlinemeasuresunderlinetunderlineunderline2]
=== idx_model_json_312_tables_measures_T++__++2

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-databasename>>; nvarchar(128)
* <<column-tables_name>>; nvarchar(128)
--
* PK, Unique, Real: 0, 0, 0


[#index-idxunderlinemodelunderlinejsonunderline312underlinetablesunderlinemeasuresunderlinetunderlineunderline3]
=== idx_model_json_312_tables_measures_T++__++3

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-databasename>>; nvarchar(128)
--
* PK, Unique, Real: 0, 0, 0

// end::AntoraIndexList[]

== AntoraMeasureDetails

// tag::AntoraMeasureDetails[]

// end::AntoraMeasureDetails[]

== AntoraMeasureDescriptions



== AntoraParameterList

// tag::AntoraParameterList[]

// end::AntoraParameterList[]

== AntoraXrefCulturesList

// tag::AntoraXrefCulturesList[]
* xref:dhw:sqldb:ssas.model_json_312_tables_measures_t.adoc[] - 
// end::AntoraXrefCulturesList[]

== cultures_count

// tag::cultures_count[]
1
// end::cultures_count[]

== Other tags

source: property.RepoObjectProperty_cross As rop_cross


=== additional_reference_csv

// tag::additional_reference_csv[]

// end::additional_reference_csv[]


=== AdocUspSteps

// tag::adocuspsteps[]

// end::adocuspsteps[]


=== AntoraReferencedList

// tag::antorareferencedlist[]
* xref:dhw:sqldb:ssas.model_json_312_tables_measures.adoc[]
// end::antorareferencedlist[]


=== AntoraReferencingList

// tag::antorareferencinglist[]
* xref:dhw:sqldb:repo.fs_measure_fullname2.adoc[]
* xref:dhw:sqldb:repo.measure.adoc[]
* xref:dhw:sqldb:ssas.model_json_3121_tables_columns_descriptions_multiline.adoc[]
* xref:dhw:sqldb:ssas.model_json_3122_tables_measures_expressions_multiline.adoc[]
* xref:dhw:sqldb:ssas.usp_persist_model_json_312_tables_measures_t.adoc[]
// end::antorareferencinglist[]


=== Description

// tag::description[]

// end::description[]


=== exampleUsage

// tag::exampleusage[]

// end::exampleusage[]


=== exampleUsage_2

// tag::exampleusage_2[]

// end::exampleusage_2[]


=== exampleUsage_3

// tag::exampleusage_3[]

// end::exampleusage_3[]


=== exampleUsage_4

// tag::exampleusage_4[]

// end::exampleusage_4[]


=== exampleUsage_5

// tag::exampleusage_5[]

// end::exampleusage_5[]


=== exampleWrong_Usage

// tag::examplewrong_usage[]

// end::examplewrong_usage[]


=== has_execution_plan_issue

// tag::has_execution_plan_issue[]

// end::has_execution_plan_issue[]


=== has_get_referenced_issue

// tag::has_get_referenced_issue[]

// end::has_get_referenced_issue[]


=== has_history

// tag::has_history[]
0
// end::has_history[]


=== has_history_columns

// tag::has_history_columns[]
0
// end::has_history_columns[]


=== InheritanceType

// tag::inheritancetype[]
13
// end::inheritancetype[]


=== is_persistence

// tag::is_persistence[]
1
// end::is_persistence[]


=== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]
0
// end::is_persistence_check_duplicate_per_pk[]


=== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]
0
// end::is_persistence_check_for_empty_source[]


=== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]
0
// end::is_persistence_delete_changed[]


=== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]
1
// end::is_persistence_delete_missing[]


=== is_persistence_insert

// tag::is_persistence_insert[]
1
// end::is_persistence_insert[]


=== is_persistence_truncate

// tag::is_persistence_truncate[]
0
// end::is_persistence_truncate[]


=== is_persistence_update_changed

// tag::is_persistence_update_changed[]
1
// end::is_persistence_update_changed[]


=== is_repo_managed

// tag::is_repo_managed[]
0
// end::is_repo_managed[]


=== is_ssas

// tag::is_ssas[]
0
// end::is_ssas[]


=== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


=== MS_Description

// tag::ms_description[]

// end::ms_description[]


=== persistence_source_RepoObject_fullname

// tag::persistence_source_repoobject_fullname[]
[ssas].[model_json_312_tables_measures]
// end::persistence_source_repoobject_fullname[]


=== persistence_source_RepoObject_fullname2

// tag::persistence_source_repoobject_fullname2[]
ssas.model_json_312_tables_measures
// end::persistence_source_repoobject_fullname2[]


=== persistence_source_RepoObject_guid

// tag::persistence_source_repoobject_guid[]
F35FD8EE-E90A-EC11-8516-A81E8446D5B0
// end::persistence_source_repoobject_guid[]


=== persistence_source_RepoObject_xref

// tag::persistence_source_repoobject_xref[]
xref:ssas.model_json_312_tables_measures.adoc[]
// end::persistence_source_repoobject_xref[]


=== pk_index_guid

// tag::pk_index_guid[]
C530C78C-161B-EC11-8520-A81E8446D5B0
// end::pk_index_guid[]


=== pk_IndexPatternColumnDatatype

// tag::pk_indexpatterncolumndatatype[]
uniqueidentifier
// end::pk_indexpatterncolumndatatype[]


=== pk_IndexPatternColumnName

// tag::pk_indexpatterncolumnname[]
Measure_guid
// end::pk_indexpatterncolumnname[]


=== pk_IndexSemanticGroup

// tag::pk_indexsemanticgroup[]

// end::pk_indexsemanticgroup[]


=== ReferencedObjectList

// tag::referencedobjectlist[]
* [ssas].[model_json_312_tables_measures]
// end::referencedobjectlist[]


=== usp_persistence_RepoObject_guid

// tag::usp_persistence_repoobject_guid[]
E6F27B65-9D0F-EC11-8518-A81E8446D5B0
// end::usp_persistence_repoobject_guid[]


=== UspExamples

// tag::uspexamples[]

// end::uspexamples[]


=== uspgenerator_usp_id

// tag::uspgenerator_usp_id[]

// end::uspgenerator_usp_id[]


=== UspParameters

// tag::uspparameters[]

// end::uspparameters[]

== Boolean Attributes

source: property.RepoObjectProperty WHERE property_int = 1

// tag::boolean_attributes[]

:is_persistence:
:is_persistence_delete_missing:
:is_persistence_insert:
:is_persistence_update_changed:

// end::boolean_attributes[]

== PlantUML diagrams

=== PlantUML Entity

// tag::puml_entity[]
[plantuml, entity-{docname}, svg, subs=macros]
....
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssas.model_json_312_tables_measures_t.adoc[]" as ssas.model_json_312_tables_measures_T << U >> {
  - **Measure_guid** : (uniqueidentifier)
  - databasename : (nvarchar(128))
  - RepoObject_guid : (uniqueidentifier)
  tables_measures_description : (nvarchar(max))
  tables_measures_description_ja : (nvarchar(max))
  tables_measures_displayFolder : (nvarchar(500))
  tables_measures_expression : (nvarchar(max))
  tables_measures_expression_ja : (nvarchar(max))
  tables_measures_formatString : (nvarchar(500))
  tables_measures_isHidden : (bit)
  tables_measures_name : (nvarchar(500))
  - tables_name : (nvarchar(128))
  # Measure_fullname : (nvarchar(517))
  # Measure_fullname2 : (nvarchar(638))
  # RepoObject_fullname2 : (nvarchar(257))
  --
}
....

// end::puml_entity[]

=== PlantUML Entity 1 1 FK

// tag::puml_entity_1_1_fk[]
[plantuml, entity_1_1_fk-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:property.measureproperty.adoc[]" as property.MeasureProperty << U >> {
**PK_MeasureProperty**

..
Measure_guid; uniqueidentifier
property_name; nvarchar(128)
--
UK_MeasureProperty

..
Measure_guid; uniqueidentifier
property_name; nvarchar(128)
--
- idx_MeasureProperty__1

..
Measure_guid; uniqueidentifier
}

entity "puml-link:dhw:sqldb:ssas.model_json_312_tables_measures_t.adoc[]" as ssas.model_json_312_tables_measures_T << U >> {
**PK_model_json_312_tables_measures_T**

..
Measure_guid; uniqueidentifier
--
- UK_model_json_312_tables_measures_T__1
"ssas_table_measure"
..
databasename; nvarchar(128)
tables_name; nvarchar(128)
tables_measures_name; nvarchar(500)
--
- idx_model_json_312_tables_measures_T__2

..
databasename; nvarchar(128)
tables_name; nvarchar(128)
--
- idx_model_json_312_tables_measures_T__3

..
databasename; nvarchar(128)
}

"ssas.model_json_312_tables_measures_T::PK_model_json_312_tables_measures_T" <-- "property.MeasureProperty::idx_MeasureProperty__1"

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_fk[]

=== PlantUML 1 1 ObjectRef

// tag::puml_entity_1_1_objectref[]
[plantuml, entity_1_1_objectref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:repo.fs_measure_fullname2.adoc[]" as repo.fs_Measure_fullname2 << FN >> {
  --
}

entity "puml-link:dhw:sqldb:repo.measure.adoc[]" as repo.Measure << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_312_tables_measures.adoc[]" as ssas.model_json_312_tables_measures << V >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  **tables_measures_name** : (nvarchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_312_tables_measures_t.adoc[]" as ssas.model_json_312_tables_measures_T << U >> {
  - **Measure_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_3121_tables_columns_descriptions_multiline.adoc[]" as ssas.model_json_3121_tables_columns_descriptions_multiline << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_3122_tables_measures_expressions_multiline.adoc[]" as ssas.model_json_3122_tables_measures_expressions_multiline << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.usp_persist_model_json_312_tables_measures_t.adoc[]" as ssas.usp_PERSIST_model_json_312_tables_measures_T << P >> {
  --
}

ssas.model_json_312_tables_measures <.. ssas.model_json_312_tables_measures_T
ssas.model_json_312_tables_measures_T <.. repo.Measure
ssas.model_json_312_tables_measures_T <.. ssas.model_json_3121_tables_columns_descriptions_multiline
ssas.model_json_312_tables_measures_T <.. ssas.model_json_3122_tables_measures_expressions_multiline
ssas.model_json_312_tables_measures_T <.. ssas.usp_PERSIST_model_json_312_tables_measures_T
ssas.model_json_312_tables_measures_T <.. repo.fs_Measure_fullname2

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_objectref[]

=== PlantUML 30 0 ObjectRef

// tag::puml_entity_30_0_objectref[]
[plantuml, entity_30_0_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssas.model_json.adoc[]" as ssas.model_json << U >> {
  - **databasename** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_10.adoc[]" as ssas.model_json_10 << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_20.adoc[]" as ssas.model_json_20 << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31_tables.adoc[]" as ssas.model_json_31_tables << V >> {
  - **databasename** : (nvarchar(128))
  **tables_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31_tables_t.adoc[]" as ssas.model_json_31_tables_T << U >> {
  - **databasename** : (nvarchar(128))
  **tables_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_312_tables_measures.adoc[]" as ssas.model_json_312_tables_measures << V >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  **tables_measures_name** : (nvarchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_312_tables_measures_t.adoc[]" as ssas.model_json_312_tables_measures_T << U >> {
  - **Measure_guid** : (uniqueidentifier)
  --
}

ssas.model_json <.. ssas.model_json_10
ssas.model_json_10 <.. ssas.model_json_20
ssas.model_json_20 <.. ssas.model_json_31_tables
ssas.model_json_31_tables <.. ssas.model_json_31_tables_T
ssas.model_json_31_tables_T <.. ssas.model_json_312_tables_measures
ssas.model_json_312_tables_measures <.. ssas.model_json_312_tables_measures_T

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_30_0_objectref[]

=== PlantUML 0 30 ObjectRef

// tag::puml_entity_0_30_objectref[]
[plantuml, entity_0_30_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:dmdocs.unit.adoc[]" as dmdocs.unit << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.antoranavlistpage_by_schema.adoc[]" as docs.AntoraNavListPage_by_schema << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ftv_repoobject_reference_plantuml_entityreflist.adoc[]" as docs.ftv_RepoObject_Reference_PlantUml_EntityRefList << IF >> {
  --
}

entity "puml-link:dhw:sqldb:docs.measure_measurepropertylist.adoc[]" as docs.Measure_MeasurePropertyList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.objectrefcyclic.adoc[]" as docs.ObjectRefCyclic << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.objectrefcyclic_entitylist.adoc[]" as docs.ObjectRefCyclic_EntityList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_adoc.adoc[]" as docs.RepoObject_Adoc << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_adoc_t.adoc[]" as docs.RepoObject_Adoc_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_measuredescriptionlist.adoc[]" as docs.RepoObject_MeasureDescriptionList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_measurelist.adoc[]" as docs.RepoObject_MeasureList << V >> {
  **RepoObject_guid** : (uniqueidentifier)
  **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml.adoc[]" as docs.RepoObject_Plantuml << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_entity.adoc[]" as docs.RepoObject_Plantuml_Entity << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_entity_t.adoc[]" as docs.RepoObject_Plantuml_Entity_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_pumlentityfklist.adoc[]" as docs.RepoObject_PlantUml_PumlEntityFkList << V >> {
  **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_t.adoc[]" as docs.RepoObject_Plantuml_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.schema_entitylist.adoc[]" as docs.Schema_EntityList << V >> {
  - **RepoObject_schema_name** : (nvarchar(128))
  - **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.schema_puml.adoc[]" as docs.Schema_puml << V >> {
  - **RepoSchema_guid** : (uniqueidentifier)
  **cultures_name** : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.unit_1_union.adoc[]" as docs.Unit_1_union << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.unit_2.adoc[]" as docs.Unit_2 << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.unit_3.adoc[]" as docs.Unit_3 << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport.adoc[]" as docs.usp_AntoraExport << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_objectpartialscontent.adoc[]" as docs.usp_AntoraExport_ObjectPartialsContent << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_objectpuml.adoc[]" as docs.usp_AntoraExport_ObjectPuml << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_repoobject_adoc_t.adoc[]" as docs.usp_PERSIST_RepoObject_Adoc_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_repoobject_plantuml_entity_t.adoc[]" as docs.usp_PERSIST_RepoObject_Plantuml_Entity_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_repoobject_plantuml_t.adoc[]" as docs.usp_PERSIST_RepoObject_Plantuml_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:property.usp_measureproperty_set.adoc[]" as property.usp_MeasureProperty_set << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.fs_measure_fullname2.adoc[]" as repo.fs_Measure_fullname2 << FN >> {
  --
}

entity "puml-link:dhw:sqldb:repo.measure.adoc[]" as repo.Measure << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.measure_union.adoc[]" as repo.Measure_union << V >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_main.adoc[]" as repo.usp_main << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_sync_guid_ssas.adoc[]" as repo.usp_sync_guid_ssas << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.measure_translation.adoc[]" as ssas.Measure_translation << V >> {
  - **Measure_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  **RepoObject_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.measure_translation_displayfolder_union.adoc[]" as ssas.Measure_translation_displayfolder_union << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.measure_translation_t.adoc[]" as ssas.Measure_translation_T << U >> {
  - **Measure_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  **RepoObject_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_312_tables_measures_t.adoc[]" as ssas.model_json_312_tables_measures_T << U >> {
  - **Measure_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_3121_tables_columns_descriptions_multiline.adoc[]" as ssas.model_json_3121_tables_columns_descriptions_multiline << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31211_tables_columns_descriptions_stragg.adoc[]" as ssas.model_json_31211_tables_columns_descriptions_StrAgg << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_3122_tables_measures_expressions_multiline.adoc[]" as ssas.model_json_3122_tables_measures_expressions_multiline << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31221_tables_measures_expressions_stragg.adoc[]" as ssas.model_json_31221_tables_measures_expressions_StrAgg << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.usp_persist_measure_translation_t.adoc[]" as ssas.usp_PERSIST_Measure_translation_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.usp_persist_model_json_312_tables_measures_t.adoc[]" as ssas.usp_PERSIST_model_json_312_tables_measures_T << P >> {
  --
}

docs.ftv_RepoObject_Reference_PlantUml_EntityRefList <.. docs.RepoObject_Plantuml
docs.Measure_MeasurePropertyList <.. docs.RepoObject_MeasureList
docs.ObjectRefCyclic_EntityList <.. docs.ObjectRefCyclic
docs.RepoObject_Adoc <.. docs.usp_PERSIST_RepoObject_Adoc_T
docs.RepoObject_Adoc <.. docs.RepoObject_Adoc_T
docs.REpoObject_Adoc_T <.. docs.usp_PERSIST_RepoObject_Adoc_T
docs.RepoObject_MeasureDescriptionList <.. docs.RepoObject_Adoc
docs.RepoObject_MeasureList <.. docs.RepoObject_Adoc
docs.RepoObject_MeasureList <.. docs.RepoObject_Plantuml_Entity
docs.RepoObject_Plantuml <.. docs.RepoObject_Plantuml_T
docs.RepoObject_Plantuml <.. docs.usp_PERSIST_RepoObject_Plantuml_T
docs.RepoObject_Plantuml_Entity <.. docs.usp_PERSIST_RepoObject_Plantuml_Entity_T
docs.RepoObject_Plantuml_Entity <.. docs.RepoObject_Plantuml_Entity_T
docs.RepoObject_Plantuml_Entity_T <.. docs.RepoObject_Adoc
docs.RepoObject_Plantuml_Entity_T <.. docs.usp_PERSIST_RepoObject_Plantuml_Entity_T
docs.RepoObject_Plantuml_Entity_T <.. docs.ftv_RepoObject_Reference_PlantUml_EntityRefList
docs.RepoObject_Plantuml_Entity_T <.. docs.RepoObject_PlantUml_PumlEntityFkList
docs.RepoObject_Plantuml_Entity_T <.. docs.ObjectRefCyclic_EntityList
docs.RepoObject_Plantuml_Entity_T <.. docs.Schema_EntityList
docs.RepoObject_PlantUml_PumlEntityFkList <.. docs.RepoObject_Plantuml
docs.RepoObject_Plantuml_T <.. docs.RepoObject_Adoc
docs.RepoObject_Plantuml_T <.. docs.usp_PERSIST_RepoObject_Plantuml_T
docs.Schema_EntityList <.. docs.Schema_puml
docs.Schema_puml <.. docs.AntoraNavListPage_by_schema
docs.Unit_1_union <.. docs.Unit_2
docs.Unit_2 <.. docs.Unit_3
docs.Unit_3 <.. dmdocs.unit
docs.usp_AntoraExport_ObjectPartialsContent <.. docs.usp_AntoraExport
docs.usp_AntoraExport_ObjectPuml <.. docs.usp_AntoraExport
docs.usp_PERSIST_RepoObject_Adoc_T <.. docs.usp_AntoraExport_ObjectPartialsContent
docs.usp_PERSIST_RepoObject_Plantuml_Entity_T <.. docs.usp_AntoraExport_ObjectPuml
docs.usp_PERSIST_RepoObject_Plantuml_T <.. docs.usp_AntoraExport_ObjectPuml
repo.Measure <.. docs.Unit_1_union
repo.Measure <.. property.usp_MeasureProperty_set
repo.Measure <.. docs.Measure_MeasurePropertyList
repo.Measure <.. repo.Measure_union
repo.Measure_union <.. ssas.Measure_translation
repo.Measure_union <.. docs.RepoObject_MeasureList
repo.Measure_union <.. docs.RepoObject_MeasureDescriptionList
repo.usp_sync_guid_ssas <.. repo.usp_main
ssas.Measure_translation <.. ssas.usp_PERSIST_Measure_translation_T
ssas.Measure_translation <.. ssas.Measure_translation_T
ssas.Measure_translation_displayfolder_union <.. docs.RepoObject_MeasureList
ssas.Measure_translation_T <.. ssas.usp_PERSIST_Measure_translation_T
ssas.Measure_translation_T <.. ssas.Measure_translation_displayfolder_union
ssas.Measure_translation_T <.. docs.RepoObject_MeasureDescriptionList
ssas.model_json_312_tables_measures_T <.. repo.fs_Measure_fullname2
ssas.model_json_312_tables_measures_T <.. ssas.model_json_3122_tables_measures_expressions_multiline
ssas.model_json_312_tables_measures_T <.. ssas.usp_PERSIST_model_json_312_tables_measures_T
ssas.model_json_312_tables_measures_T <.. repo.Measure
ssas.model_json_312_tables_measures_T <.. ssas.model_json_3121_tables_columns_descriptions_multiline
ssas.model_json_3121_tables_columns_descriptions_multiline <.. ssas.model_json_31211_tables_columns_descriptions_StrAgg
ssas.model_json_31211_tables_columns_descriptions_StrAgg <.. repo.Measure
ssas.model_json_3122_tables_measures_expressions_multiline <.. ssas.model_json_31221_tables_measures_expressions_StrAgg
ssas.model_json_31221_tables_measures_expressions_StrAgg <.. repo.Measure
ssas.usp_PERSIST_Measure_translation_T <.. repo.usp_sync_guid_ssas
ssas.usp_PERSIST_model_json_312_tables_measures_T <.. repo.usp_sync_guid_ssas

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_0_30_objectref[]

=== PlantUML 1 1 ColumnRef

// tag::puml_entity_1_1_colref[]
[plantuml, entity_1_1_colref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:repo.fs_measure_fullname2.adoc[]" as repo.fs_Measure_fullname2 << FN >> {
  --
}

entity "puml-link:dhw:sqldb:repo.measure.adoc[]" as repo.Measure << V >> {
  Description : (nvarchar(max))
  Expression : (nvarchar(max))
  is_ssas : (bit)
  Measure_fullname : (nvarchar(517))
  - Measure_fullname2 : (nvarchar(638))
  - Measure_guid : (uniqueidentifier)
  measures_description : (nvarchar(max))
  measures_description_ja : (nvarchar(max))
  measures_displayFolder : (nvarchar(500))
  measures_expression : (nvarchar(max))
  measures_expression_ja : (nvarchar(max))
  measures_formatString : (nvarchar(500))
  measures_isHidden : (bit)
  - measures_name : (nvarchar(500))
  MeasuresRepoObjekt_guid : (uniqueidentifier)
  MeasuresRepoObjekt_name : (varchar(9))
  - RepoObject_fullname2 : (nvarchar(257))
  - RepoObject_guid : (uniqueidentifier)
  - RepoObject_name : (nvarchar(128))
  - RepoSchema_name : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_312_tables_measures.adoc[]" as ssas.model_json_312_tables_measures << V >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  **tables_measures_name** : (nvarchar(500))
  - RepoObject_guid : (uniqueidentifier)
  tables_measures_description : (nvarchar(max))
  tables_measures_description_ja : (nvarchar(max))
  tables_measures_displayFolder : (nvarchar(500))
  tables_measures_expression : (nvarchar(max))
  tables_measures_expression_ja : (nvarchar(max))
  tables_measures_formatString : (nvarchar(500))
  tables_measures_isHidden : (bit)
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_312_tables_measures_t.adoc[]" as ssas.model_json_312_tables_measures_T << U >> {
  - **Measure_guid** : (uniqueidentifier)
  - databasename : (nvarchar(128))
  - RepoObject_guid : (uniqueidentifier)
  tables_measures_description : (nvarchar(max))
  tables_measures_description_ja : (nvarchar(max))
  tables_measures_displayFolder : (nvarchar(500))
  tables_measures_expression : (nvarchar(max))
  tables_measures_expression_ja : (nvarchar(max))
  tables_measures_formatString : (nvarchar(500))
  tables_measures_isHidden : (bit)
  tables_measures_name : (nvarchar(500))
  - tables_name : (nvarchar(128))
  # Measure_fullname : (nvarchar(517))
  # Measure_fullname2 : (nvarchar(638))
  # RepoObject_fullname2 : (nvarchar(257))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_3121_tables_columns_descriptions_multiline.adoc[]" as ssas.model_json_3121_tables_columns_descriptions_multiline << V >> {
  - databasename : (nvarchar(128))
  - Key : (nvarchar(4000))
  - Measure_guid : (uniqueidentifier)
  - RepoObject_guid : (uniqueidentifier)
  - tables_measures_name : (nvarchar(500))
  - tables_name : (nvarchar(128))
  - Type : (tinyint)
  Value : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_3122_tables_measures_expressions_multiline.adoc[]" as ssas.model_json_3122_tables_measures_expressions_multiline << V >> {
  - databasename : (nvarchar(128))
  - Key : (nvarchar(4000))
  - Measure_guid : (uniqueidentifier)
  - RepoObject_guid : (uniqueidentifier)
  - tables_measures_name : (nvarchar(500))
  - tables_name : (nvarchar(128))
  - Type : (tinyint)
  Value : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssas.usp_persist_model_json_312_tables_measures_t.adoc[]" as ssas.usp_PERSIST_model_json_312_tables_measures_T << P >> {
  --
}

ssas.model_json_312_tables_measures <.. ssas.model_json_312_tables_measures_T
ssas.model_json_312_tables_measures_T <.. repo.Measure
ssas.model_json_312_tables_measures_T <.. ssas.model_json_3121_tables_columns_descriptions_multiline
ssas.model_json_312_tables_measures_T <.. ssas.model_json_3122_tables_measures_expressions_multiline
ssas.model_json_312_tables_measures_T <.. ssas.usp_PERSIST_model_json_312_tables_measures_T
ssas.model_json_312_tables_measures_T <.. repo.fs_Measure_fullname2
"ssas.model_json_312_tables_measures::databasename" <-- "ssas.model_json_312_tables_measures_T::databasename"
"ssas.model_json_312_tables_measures::RepoObject_guid" <-- "ssas.model_json_312_tables_measures_T::RepoObject_guid"
"ssas.model_json_312_tables_measures::tables_measures_description" <-- "ssas.model_json_312_tables_measures_T::tables_measures_description"
"ssas.model_json_312_tables_measures::tables_measures_description_ja" <-- "ssas.model_json_312_tables_measures_T::tables_measures_description_ja"
"ssas.model_json_312_tables_measures::tables_measures_displayFolder" <-- "ssas.model_json_312_tables_measures_T::tables_measures_displayFolder"
"ssas.model_json_312_tables_measures::tables_measures_expression" <-- "ssas.model_json_312_tables_measures_T::tables_measures_expression"
"ssas.model_json_312_tables_measures::tables_measures_expression_ja" <-- "ssas.model_json_312_tables_measures_T::tables_measures_expression_ja"
"ssas.model_json_312_tables_measures::tables_measures_formatString" <-- "ssas.model_json_312_tables_measures_T::tables_measures_formatString"
"ssas.model_json_312_tables_measures::tables_measures_isHidden" <-- "ssas.model_json_312_tables_measures_T::tables_measures_isHidden"
"ssas.model_json_312_tables_measures::tables_measures_name" <-- "ssas.model_json_312_tables_measures_T::tables_measures_name"
"ssas.model_json_312_tables_measures::tables_name" <-- "ssas.model_json_312_tables_measures_T::tables_name"
"ssas.model_json_312_tables_measures_T::databasename" <-- "ssas.model_json_3121_tables_columns_descriptions_multiline::databasename"
"ssas.model_json_312_tables_measures_T::databasename" <-- "repo.Measure::RepoSchema_name"
"ssas.model_json_312_tables_measures_T::databasename" <-- "ssas.model_json_3122_tables_measures_expressions_multiline::databasename"
"ssas.model_json_312_tables_measures_T::databasename" <-- "ssas.model_json_312_tables_measures_T::RepoObject_fullname2"
"ssas.model_json_312_tables_measures_T::databasename" <-- "ssas.model_json_312_tables_measures_T::Measure_fullname"
"ssas.model_json_312_tables_measures_T::databasename" <-- "ssas.model_json_312_tables_measures_T::Measure_fullname2"
"ssas.model_json_312_tables_measures_T::Measure_fullname" <-- "repo.Measure::Measure_fullname"
"ssas.model_json_312_tables_measures_T::Measure_fullname2" <-- "repo.Measure::Measure_fullname2"
"ssas.model_json_312_tables_measures_T::Measure_guid" <-- "ssas.model_json_3122_tables_measures_expressions_multiline::Measure_guid"
"ssas.model_json_312_tables_measures_T::Measure_guid" <-- "repo.Measure::Measure_guid"
"ssas.model_json_312_tables_measures_T::Measure_guid" <-- "ssas.model_json_3121_tables_columns_descriptions_multiline::Measure_guid"
"ssas.model_json_312_tables_measures_T::RepoObject_fullname2" <-- "repo.Measure::RepoObject_fullname2"
"ssas.model_json_312_tables_measures_T::RepoObject_guid" <-- "ssas.model_json_3122_tables_measures_expressions_multiline::RepoObject_guid"
"ssas.model_json_312_tables_measures_T::RepoObject_guid" <-- "repo.Measure::RepoObject_guid"
"ssas.model_json_312_tables_measures_T::RepoObject_guid" <-- "ssas.model_json_3121_tables_columns_descriptions_multiline::RepoObject_guid"
"ssas.model_json_312_tables_measures_T::tables_measures_description" <-- "repo.Measure::measures_description"
"ssas.model_json_312_tables_measures_T::tables_measures_description_ja" <-- "repo.Measure::measures_description_ja"
"ssas.model_json_312_tables_measures_T::tables_measures_displayFolder" <-- "repo.Measure::measures_displayFolder"
"ssas.model_json_312_tables_measures_T::tables_measures_expression" <-- "repo.Measure::measures_expression"
"ssas.model_json_312_tables_measures_T::tables_measures_expression_ja" <-- "repo.Measure::measures_expression_ja"
"ssas.model_json_312_tables_measures_T::tables_measures_formatString" <-- "repo.Measure::measures_formatString"
"ssas.model_json_312_tables_measures_T::tables_measures_isHidden" <-- "repo.Measure::measures_isHidden"
"ssas.model_json_312_tables_measures_T::tables_measures_name" <-- "repo.Measure::measures_name"
"ssas.model_json_312_tables_measures_T::tables_measures_name" <-- "ssas.model_json_3122_tables_measures_expressions_multiline::tables_measures_name"
"ssas.model_json_312_tables_measures_T::tables_measures_name" <-- "ssas.model_json_3121_tables_columns_descriptions_multiline::tables_measures_name"
"ssas.model_json_312_tables_measures_T::tables_measures_name" <-- "ssas.model_json_312_tables_measures_T::Measure_fullname2"
"ssas.model_json_312_tables_measures_T::tables_measures_name" <-- "ssas.model_json_312_tables_measures_T::Measure_fullname"
"ssas.model_json_312_tables_measures_T::tables_name" <-- "ssas.model_json_312_tables_measures_T::RepoObject_fullname2"
"ssas.model_json_312_tables_measures_T::tables_name" <-- "ssas.model_json_3121_tables_columns_descriptions_multiline::tables_name"
"ssas.model_json_312_tables_measures_T::tables_name" <-- "repo.Measure::RepoObject_name"
"ssas.model_json_312_tables_measures_T::tables_name" <-- "ssas.model_json_3122_tables_measures_expressions_multiline::tables_name"

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_colref[]


== sql_modules_definition

// tag::sql_modules_definition[]
[%collapsible]
=======
[source,sql,numbered,indent=0]
----

----
=======
// end::sql_modules_definition[]


