// tag::HeaderFullDisplayName[]
= ssis.Package - U
// end::HeaderFullDisplayName[]

== existing_properties

// tag::existing_properties[]

:ExistsProperty--antorareferencedlist:
:ExistsProperty--antorareferencinglist:
:ExistsProperty--is_repo_managed:
:ExistsProperty--is_ssas:
:ExistsProperty--pk_index_guid:
:ExistsProperty--pk_indexpatterncolumndatatype:
:ExistsProperty--pk_indexpatterncolumnname:
:ExistsProperty--referencedobjectlist:
:ExistsProperty--FK:
:ExistsProperty--AntoraIndexList:
:ExistsProperty--Columns:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
5464FBE4-113B-EC11-852C-A81E8446D5B0
// end::RepoObject_guid[]

== RepoObject_FullDisplayName2

// tag::RepoObject_FullDisplayName2[]
ssis.Package
// end::RepoObject_FullDisplayName2[]

== SysObject_type

// tag::SysObject_type[]
U 
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
user table
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
498152870
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2021-11-25 19:14:05
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]
[discrete]
== _


[#column-antoramodule]
=== AntoraModule

[cols="d,8a,m,m,m"]
|===
|1
|*AntoraModule*
|varchar(50)
|NOT NULL
|
|===

.Referencing Columns
--
* xref:docs.ssis_adoc.adoc#column-antoramodule[+docs.ssis_Adoc.AntoraModule+]
* xref:docs.ssis_generallist.adoc#column-antoramodule[+docs.ssis_GeneralList.AntoraModule+]
* xref:docs.ssis_navlist_package.adoc#column-antoramodule[+docs.ssis_navlist_package.AntoraModule+]
* xref:ssis.package_tgt.adoc#column-antoramodule[+ssis.Package_tgt.AntoraModule+]
--


[#column-packagename]
=== PackageName

[cols="d,8a,m,m,m"]
|===
|2
|*PackageName*
|varchar(200)
|NOT NULL
|
|===

.Referencing Columns
--
* xref:docs.ssis_generallist.adoc#column-packagename[+docs.ssis_GeneralList.PackageName+]
* xref:ssis.package.adoc#column-packagebasename[+ssis.Package.PackageBasename+]
* xref:ssis.package_tgt.adoc#column-packagename[+ssis.Package_tgt.PackageName+]
--


[#column-packagecreationdate]
=== PackageCreationDate

[cols="d,8a,m,m,m"]
|===
|
|PackageCreationDate
|datetime
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.package_tgt.adoc#column-packagecreationdate[+ssis.Package_tgt.PackageCreationDate+]
--


[#column-packagecreatorcomputername]
=== PackageCreatorComputerName

[cols="d,8a,m,m,m"]
|===
|
|PackageCreatorComputerName
|nvarchar(500)
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.package_tgt.adoc#column-packagecreatorcomputername[+ssis.Package_tgt.PackageCreatorComputerName+]
--


[#column-packagecreatorname]
=== PackageCreatorName

[cols="d,8a,m,m,m"]
|===
|
|PackageCreatorName
|varchar(1000)
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.package_tgt.adoc#column-packagecreatorname[+ssis.Package_tgt.PackageCreatorName+]
--


[#column-packagedescription]
=== PackageDescription

[cols="d,8a,m,m,m"]
|===
|
|PackageDescription
|nvarchar(max)
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.package_tgt.adoc#column-packagedescription[+ssis.Package_tgt.PackageDescription+]
--


[#column-packagedtsid]
=== PackageDTSID

[cols="d,8a,m,m,m"]
|===
|
|PackageDTSID
|uniqueidentifier
|NOT NULL
|
|===

.Referencing Columns
--
* xref:ssis.package_tgt.adoc#column-packagedtsid[+ssis.Package_tgt.PackageDTSID+]
--


[#column-packagelastmodifiedproductversion]
=== PackageLastModifiedProductVersion

[cols="d,8a,m,m,m"]
|===
|
|PackageLastModifiedProductVersion
|nvarchar(500)
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.package_tgt.adoc#column-packagelastmodifiedproductversion[+ssis.Package_tgt.PackageLastModifiedProductVersion+]
--


[#column-packagelocaleid]
=== PackageLocaleID

[cols="d,8a,m,m,m"]
|===
|
|PackageLocaleID
|int
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.package_tgt.adoc#column-packagelocaleid[+ssis.Package_tgt.PackageLocaleID+]
--


[#column-packageobjectname]
=== PackageObjectName

[cols="d,8a,m,m,m"]
|===
|
|PackageObjectName
|nvarchar(500)
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.package_tgt.adoc#column-packageobjectname[+ssis.Package_tgt.PackageObjectName+]
--


[#column-packagepath]
=== PackagePath

[cols="d,8a,m,m,m"]
|===
|
|PackagePath
|varchar(8000)
|NOT NULL
|
|===

.Referencing Columns
--
* xref:ssis.package_tgt.adoc#column-packagepath[+ssis.Package_tgt.PackagePath+]
--


[#column-packageprotectionlevel]
=== PackageProtectionLevel

[cols="d,8a,m,m,m"]
|===
|
|PackageProtectionLevel
|varchar(100)
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.package_tgt.adoc#column-packageprotectionlevel[+ssis.Package_tgt.PackageProtectionLevel+]
--


[#column-packageprotectionlevelname]
=== PackageProtectionLevelName

[cols="d,8a,m,m,m"]
|===
|
|PackageProtectionLevelName
|varchar(28)
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.package_tgt.adoc#column-packageprotectionlevelname[+ssis.Package_tgt.PackageProtectionLevelName+]
--


[#column-packageversionguid]
=== PackageVersionGUID

[cols="d,8a,m,m,m"]
|===
|
|PackageVersionGUID
|uniqueidentifier
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.package_tgt.adoc#column-packageversionguid[+ssis.Package_tgt.PackageVersionGUID+]
--


[#column-projectpath]
=== ProjectPath

[cols="d,8a,m,m,m"]
|===
|
|ProjectPath
|varchar(8000)
|NOT NULL
|
|===

.Referencing Columns
--
* xref:ssis.package_tgt.adoc#column-projectpath[+ssis.Package_tgt.ProjectPath+]
--


[#column-rowid]
=== RowID

[cols="d,8a,m,m,m"]
|===
|
|RowID
|int
|NOT NULL
|
|===

.Referencing Columns
--
* xref:ssis.package_tgt.adoc#column-rowid[+ssis.Package_tgt.RowID+]
--


[#column-packagebasename]
=== PackageBasename

[cols="d,8a,m,m,m"]
|===
|
|PackageBasename

.Definition (PERSISTED)
[source,sql]
----
(replace([PackageName],'.dtsx',''))
----


|varchar(8000)
|NULL
|
|===

.Description
--
(replace([PackageName],'.dtsx',''))
--
{empty} +

.Referenced Columns
--
* xref:ssis.package.adoc#column-packagename[+ssis.Package.PackageName+]
--

.Referencing Columns
--
* xref:docs.ssis_adoc.adoc#column-packagebasename[+docs.ssis_Adoc.PackageBasename+]
--


// end::AntoraColumnDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]
|1
|*<<column-antoramodule>>*
|varchar(50)
|NOT NULL
|

|2
|*<<column-packagename>>*
|varchar(200)
|NOT NULL
|
















// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]


|
|<<column-packagecreationdate>>
|datetime
|NULL
|

|
|<<column-packagecreatorcomputername>>
|nvarchar(500)
|NULL
|

|
|<<column-packagecreatorname>>
|varchar(1000)
|NULL
|

|
|<<column-packagedescription>>
|nvarchar(max)
|NULL
|

|
|<<column-packagedtsid>>
|uniqueidentifier
|NOT NULL
|

|
|<<column-packagelastmodifiedproductversion>>
|nvarchar(500)
|NULL
|

|
|<<column-packagelocaleid>>
|int
|NULL
|

|
|<<column-packageobjectname>>
|nvarchar(500)
|NULL
|

|
|<<column-packagepath>>
|varchar(8000)
|NOT NULL
|

|
|<<column-packageprotectionlevel>>
|varchar(100)
|NULL
|

|
|<<column-packageprotectionlevelname>>
|varchar(28)
|NULL
|

|
|<<column-packageversionguid>>
|uniqueidentifier
|NULL
|

|
|<<column-projectpath>>
|varchar(8000)
|NOT NULL
|

|
|<<column-rowid>>
|int
|NOT NULL
|

|
|<<column-packagebasename>>

.Definition (PERSISTED)
[source,sql]
----
(replace([PackageName],'.dtsx',''))
----


|varchar(8000)
|NULL
|

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

[#index-pkunderlinepackage]
=== PK_Package

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-AntoraModule>>; varchar(50)
* <<column-PackageName>>; varchar(200)
--
* PK, Unique, Real: 1, 1, 1

// end::AntoraIndexList[]

== AntoraMeasureDetails

// tag::AntoraMeasureDetails[]

// end::AntoraMeasureDetails[]

== AntoraMeasureDescriptions



== AntoraParameterList

// tag::AntoraParameterList[]

// end::AntoraParameterList[]

== AntoraXrefCulturesList

// tag::AntoraXrefCulturesList[]
* xref:dhw:sqldb:ssis.package.adoc[] - 
// end::AntoraXrefCulturesList[]

== cultures_count

// tag::cultures_count[]
1
// end::cultures_count[]

== Other tags

source: property.RepoObjectProperty_cross As rop_cross


=== additional_reference_csv

// tag::additional_reference_csv[]

// end::additional_reference_csv[]


=== AdocUspSteps

// tag::adocuspsteps[]

// end::adocuspsteps[]


=== AntoraReferencedList

// tag::antorareferencedlist[]
* xref:dhw:sqldb:ssis.package_tgt.adoc[]
// end::antorareferencedlist[]


=== AntoraReferencingList

// tag::antorareferencinglist[]
* xref:dhw:sqldb:docs.ssis_adoc.adoc[]
* xref:dhw:sqldb:docs.ssis_generallist.adoc[]
* xref:dhw:sqldb:docs.ssis_navlist_package.adoc[]
* xref:dhw:sqldb:docs.usp_antoraexport_ssispage.adoc[]
// end::antorareferencinglist[]


=== Description

// tag::description[]

// end::description[]


=== exampleUsage

// tag::exampleusage[]

// end::exampleusage[]


=== exampleUsage_2

// tag::exampleusage_2[]

// end::exampleusage_2[]


=== exampleUsage_3

// tag::exampleusage_3[]

// end::exampleusage_3[]


=== exampleUsage_4

// tag::exampleusage_4[]

// end::exampleusage_4[]


=== exampleUsage_5

// tag::exampleusage_5[]

// end::exampleusage_5[]


=== exampleWrong_Usage

// tag::examplewrong_usage[]

// end::examplewrong_usage[]


=== has_execution_plan_issue

// tag::has_execution_plan_issue[]

// end::has_execution_plan_issue[]


=== has_get_referenced_issue

// tag::has_get_referenced_issue[]

// end::has_get_referenced_issue[]


=== has_history

// tag::has_history[]

// end::has_history[]


=== has_history_columns

// tag::has_history_columns[]

// end::has_history_columns[]


=== InheritanceType

// tag::inheritancetype[]

// end::inheritancetype[]


=== is_persistence

// tag::is_persistence[]

// end::is_persistence[]


=== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]

// end::is_persistence_check_duplicate_per_pk[]


=== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]

// end::is_persistence_check_for_empty_source[]


=== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]

// end::is_persistence_delete_changed[]


=== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]

// end::is_persistence_delete_missing[]


=== is_persistence_insert

// tag::is_persistence_insert[]

// end::is_persistence_insert[]


=== is_persistence_truncate

// tag::is_persistence_truncate[]

// end::is_persistence_truncate[]


=== is_persistence_update_changed

// tag::is_persistence_update_changed[]

// end::is_persistence_update_changed[]


=== is_repo_managed

// tag::is_repo_managed[]
0
// end::is_repo_managed[]


=== is_ssas

// tag::is_ssas[]
0
// end::is_ssas[]


=== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


=== MS_Description

// tag::ms_description[]

// end::ms_description[]


=== persistence_source_RepoObject_fullname

// tag::persistence_source_repoobject_fullname[]

// end::persistence_source_repoobject_fullname[]


=== persistence_source_RepoObject_fullname2

// tag::persistence_source_repoobject_fullname2[]

// end::persistence_source_repoobject_fullname2[]


=== persistence_source_RepoObject_guid

// tag::persistence_source_repoobject_guid[]

// end::persistence_source_repoobject_guid[]


=== persistence_source_RepoObject_xref

// tag::persistence_source_repoobject_xref[]

// end::persistence_source_repoobject_xref[]


=== pk_index_guid

// tag::pk_index_guid[]
D1453D12-183B-EC11-852C-A81E8446D5B0
// end::pk_index_guid[]


=== pk_IndexPatternColumnDatatype

// tag::pk_indexpatterncolumndatatype[]
varchar(50),varchar(200)
// end::pk_indexpatterncolumndatatype[]


=== pk_IndexPatternColumnName

// tag::pk_indexpatterncolumnname[]
AntoraModule,PackageName
// end::pk_indexpatterncolumnname[]


=== pk_IndexSemanticGroup

// tag::pk_indexsemanticgroup[]

// end::pk_indexsemanticgroup[]


=== ReferencedObjectList

// tag::referencedobjectlist[]
* [ssis].[Package_tgt]
// end::referencedobjectlist[]


=== usp_persistence_RepoObject_guid

// tag::usp_persistence_repoobject_guid[]

// end::usp_persistence_repoobject_guid[]


=== UspExamples

// tag::uspexamples[]

// end::uspexamples[]


=== uspgenerator_usp_id

// tag::uspgenerator_usp_id[]

// end::uspgenerator_usp_id[]


=== UspParameters

// tag::uspparameters[]

// end::uspparameters[]

== Boolean Attributes

source: property.RepoObjectProperty WHERE property_int = 1

// tag::boolean_attributes[]


// end::boolean_attributes[]

== PlantUML diagrams

=== PlantUML Entity

// tag::puml_entity[]
[plantuml, entity-{docname}, svg, subs=macros]
....
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis.package.adoc[]" as ssis.Package << U >> {
  - **AntoraModule** : (varchar(50))
  - **PackageName** : (varchar(200))
  PackageCreationDate : (datetime)
  PackageCreatorComputerName : (nvarchar(500))
  PackageCreatorName : (varchar(1000))
  PackageDescription : (nvarchar(max))
  - PackageDTSID : (uniqueidentifier)
  PackageLastModifiedProductVersion : (nvarchar(500))
  PackageLocaleID : (int)
  PackageObjectName : (nvarchar(500))
  - PackagePath : (varchar(8000))
  PackageProtectionLevel : (varchar(100))
  PackageProtectionLevelName : (varchar(28))
  PackageVersionGUID : (uniqueidentifier)
  - ProjectPath : (varchar(8000))
  - RowID : (int)
  # PackageBasename : (varchar(8000))
  --
}
....

// end::puml_entity[]

=== PlantUML Entity 1 1 FK

// tag::puml_entity_1_1_fk[]
[plantuml, entity_1_1_fk-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis.package.adoc[]" as ssis.Package << U >> {
**PK_Package**

..
AntoraModule; varchar(50)
PackageName; varchar(200)
}



footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_fk[]

=== PlantUML 1 1 ObjectRef

// tag::puml_entity_1_1_objectref[]
[plantuml, entity_1_1_objectref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:docs.ssis_adoc.adoc[]" as docs.ssis_Adoc << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageBasename** : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_generallist.adoc[]" as docs.ssis_GeneralList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_navlist_package.adoc[]" as docs.ssis_navlist_package << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_ssispage.adoc[]" as docs.usp_AntoraExport_SsisPage << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.package.adoc[]" as ssis.Package << U >> {
  - **AntoraModule** : (varchar(50))
  - **PackageName** : (varchar(200))
  --
}

entity "puml-link:dhw:sqldb:ssis.package_tgt.adoc[]" as ssis.Package_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  --
}

ssis.Package <.. docs.ssis_Adoc
ssis.Package <.. docs.usp_AntoraExport_SsisPage
ssis.Package <.. docs.ssis_GeneralList
ssis.Package <.. docs.ssis_navlist_package
ssis.Package_tgt <.. ssis.Package

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_objectref[]

=== PlantUML 30 0 ObjectRef

// tag::puml_entity_30_0_objectref[]
[plantuml, entity_30_0_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis.antoramodule_tgt_filter.adoc[]" as ssis.AntoraModule_tgt_filter << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.package.adoc[]" as ssis.Package << U >> {
  - **AntoraModule** : (varchar(50))
  - **PackageName** : (varchar(200))
  --
}

entity "puml-link:dhw:sqldb:ssis.package_src.adoc[]" as ssis.Package_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  --
}

entity "puml-link:dhw:sqldb:ssis.package_tgt.adoc[]" as ssis.Package_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  --
}

entity "puml-link:dhw:sqldb:ssis.project.adoc[]" as ssis.Project << U >> {
  - **AntoraModule** : (varchar(50))
  --
}

entity "puml-link:dhw:sqldb:ssis_t.pkgstats.adoc[]" as ssis_t.pkgStats << U >> {
  - **RowID** : (int)
  --
}

ssis.AntoraModule_tgt_filter <.. ssis.Package_tgt
ssis.Package_src <.. ssis.Package_tgt
ssis.Package_src <.. ssis.AntoraModule_tgt_filter
ssis.Package_tgt <.. ssis.Package
ssis.Project <.. ssis.Package_src
ssis_t.pkgStats <.. ssis.Package_src

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_30_0_objectref[]

=== PlantUML 0 30 ObjectRef

// tag::puml_entity_0_30_objectref[]
[plantuml, entity_0_30_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:docs.ssis_adoc.adoc[]" as docs.ssis_Adoc << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageBasename** : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_adoc_t.adoc[]" as docs.ssis_Adoc_T << U >> {
  - **AntoraModule** : (varchar(50))
  **PackageBasename** : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_generallist.adoc[]" as docs.ssis_GeneralList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_navlist_package.adoc[]" as docs.ssis_navlist_package << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport.adoc[]" as docs.usp_AntoraExport << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_ssisnavigation.adoc[]" as docs.usp_AntoraExport_SsisNavigation << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_ssispage.adoc[]" as docs.usp_AntoraExport_SsisPage << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_ssispartialscontent.adoc[]" as docs.usp_AntoraExport_SsisPartialsContent << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_ssis_adoc_t.adoc[]" as docs.usp_PERSIST_ssis_Adoc_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.package.adoc[]" as ssis.Package << U >> {
  - **AntoraModule** : (varchar(50))
  - **PackageName** : (varchar(200))
  --
}

docs.ssis_Adoc <.. docs.ssis_Adoc_T
docs.ssis_Adoc <.. docs.usp_PERSIST_ssis_Adoc_T
docs.ssis_Adoc_T <.. docs.usp_PERSIST_ssis_Adoc_T
docs.ssis_Adoc_T <.. docs.usp_AntoraExport_SsisPartialsContent
docs.ssis_GeneralList <.. docs.ssis_Adoc
docs.ssis_navlist_package <.. docs.usp_AntoraExport_SsisNavigation
docs.usp_AntoraExport_SsisNavigation <.. docs.usp_AntoraExport
docs.usp_AntoraExport_SsisPage <.. docs.usp_AntoraExport
docs.usp_AntoraExport_SsisPartialsContent <.. docs.usp_AntoraExport
docs.usp_PERSIST_ssis_Adoc_T <.. docs.usp_AntoraExport_SsisPartialsContent
ssis.Package <.. docs.ssis_navlist_package
ssis.Package <.. docs.ssis_GeneralList
ssis.Package <.. docs.usp_AntoraExport_SsisPage
ssis.Package <.. docs.ssis_Adoc

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_0_30_objectref[]

=== PlantUML 1 1 ColumnRef

// tag::puml_entity_1_1_colref[]
[plantuml, entity_1_1_colref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:docs.ssis_adoc.adoc[]" as docs.ssis_Adoc << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageBasename** : (varchar(8000))
  - AdocContent : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_generallist.adoc[]" as docs.ssis_GeneralList << V >> {
  - AntoraModule : (varchar(50))
  - GeneralList : (nvarchar(max))
  - PackageName : (varchar(200))
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_navlist_package.adoc[]" as docs.ssis_navlist_package << V >> {
  - AntoraModule : (varchar(50))
  nav_list : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_ssispage.adoc[]" as docs.usp_AntoraExport_SsisPage << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.package.adoc[]" as ssis.Package << U >> {
  - **AntoraModule** : (varchar(50))
  - **PackageName** : (varchar(200))
  PackageCreationDate : (datetime)
  PackageCreatorComputerName : (nvarchar(500))
  PackageCreatorName : (varchar(1000))
  PackageDescription : (nvarchar(max))
  - PackageDTSID : (uniqueidentifier)
  PackageLastModifiedProductVersion : (nvarchar(500))
  PackageLocaleID : (int)
  PackageObjectName : (nvarchar(500))
  - PackagePath : (varchar(8000))
  PackageProtectionLevel : (varchar(100))
  PackageProtectionLevelName : (varchar(28))
  PackageVersionGUID : (uniqueidentifier)
  - ProjectPath : (varchar(8000))
  - RowID : (int)
  # PackageBasename : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:ssis.package_tgt.adoc[]" as ssis.Package_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  PackageCreationDate : (datetime)
  PackageCreatorComputerName : (nvarchar(500))
  PackageCreatorName : (varchar(1000))
  PackageDescription : (nvarchar(max))
  PackageDTSID : (uniqueidentifier)
  PackageLastModifiedProductVersion : (nvarchar(500))
  PackageLocaleID : (int)
  PackageObjectName : (nvarchar(500))
  - PackagePath : (varchar(8000))
  PackageProtectionLevel : (varchar(100))
  PackageProtectionLevelName : (varchar(28))
  PackageVersionGUID : (uniqueidentifier)
  - PackageXML : (xml)
  - ProjectPath : (varchar(8000))
  - RowID : (int)
  --
}

ssis.Package <.. docs.ssis_Adoc
ssis.Package <.. docs.usp_AntoraExport_SsisPage
ssis.Package <.. docs.ssis_GeneralList
ssis.Package <.. docs.ssis_navlist_package
ssis.Package_tgt <.. ssis.Package
"ssis.Package::AntoraModule" <-- "ssis.Package_tgt::AntoraModule"
"ssis.Package::AntoraModule" <-- "docs.ssis_Adoc::AntoraModule"
"ssis.Package::AntoraModule" <-- "docs.ssis_GeneralList::AntoraModule"
"ssis.Package::AntoraModule" <-- "docs.ssis_navlist_package::AntoraModule"
"ssis.Package::PackageBasename" <-- "docs.ssis_Adoc::PackageBasename"
"ssis.Package::PackageCreationDate" <-- "ssis.Package_tgt::PackageCreationDate"
"ssis.Package::PackageCreatorComputerName" <-- "ssis.Package_tgt::PackageCreatorComputerName"
"ssis.Package::PackageCreatorName" <-- "ssis.Package_tgt::PackageCreatorName"
"ssis.Package::PackageDescription" <-- "ssis.Package_tgt::PackageDescription"
"ssis.Package::PackageDTSID" <-- "ssis.Package_tgt::PackageDTSID"
"ssis.Package::PackageLastModifiedProductVersion" <-- "ssis.Package_tgt::PackageLastModifiedProductVersion"
"ssis.Package::PackageLocaleID" <-- "ssis.Package_tgt::PackageLocaleID"
"ssis.Package::PackageName" <-- "ssis.Package_tgt::PackageName"
"ssis.Package::PackageName" <-- "ssis.Package::PackageBasename"
"ssis.Package::PackageName" <-- "docs.ssis_GeneralList::PackageName"
"ssis.Package::PackageObjectName" <-- "ssis.Package_tgt::PackageObjectName"
"ssis.Package::PackagePath" <-- "ssis.Package_tgt::PackagePath"
"ssis.Package::PackageProtectionLevel" <-- "ssis.Package_tgt::PackageProtectionLevel"
"ssis.Package::PackageProtectionLevelName" <-- "ssis.Package_tgt::PackageProtectionLevelName"
"ssis.Package::PackageVersionGUID" <-- "ssis.Package_tgt::PackageVersionGUID"
"ssis.Package::ProjectPath" <-- "ssis.Package_tgt::ProjectPath"
"ssis.Package::RowID" <-- "ssis.Package_tgt::RowID"

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_colref[]


== sql_modules_definition

// tag::sql_modules_definition[]
[%collapsible]
=======
[source,sql,numbered,indent=0]
----

----
=======
// end::sql_modules_definition[]


