// tag::HeaderFullDisplayName[]
= ssis.PackageFlow_src - V
// end::HeaderFullDisplayName[]

== existing_properties

// tag::existing_properties[]

:ExistsProperty--antorareferencedlist:
:ExistsProperty--antorareferencinglist:
:ExistsProperty--is_repo_managed:
:ExistsProperty--is_ssas:
:ExistsProperty--pk_index_guid:
:ExistsProperty--pk_indexpatterncolumndatatype:
:ExistsProperty--pk_indexpatterncolumnname:
:ExistsProperty--referencedobjectlist:
:ExistsProperty--sql_modules_definition:
:ExistsProperty--FK:
:ExistsProperty--AntoraIndexList:
:ExistsProperty--Columns:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
5D64FBE4-113B-EC11-852C-A81E8446D5B0
// end::RepoObject_guid[]

== RepoObject_FullDisplayName2

// tag::RepoObject_FullDisplayName2[]
ssis.PackageFlow_src
// end::RepoObject_FullDisplayName2[]

== SysObject_type

// tag::SysObject_type[]
V 
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
view
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
18151160
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2021-11-01 14:35:28
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]
[discrete]
== _


[#column-antoramodule]
=== AntoraModule

[cols="d,8a,m,m,m"]
|===
|1
|*AntoraModule*
|varchar(50)
|NOT NULL
|
|===

.Referenced Columns
--
* xref:ssis.package_src.adoc#column-antoramodule[+ssis.Package_src.AntoraModule+]
--

.Referencing Columns
--
* xref:ssis.packageflow_tgt.adoc#column-antoramodule[+ssis.PackageFlow_tgt.AntoraModule+]
--


[#column-packagename]
=== PackageName

[cols="d,8a,m,m,m"]
|===
|2
|*PackageName*
|varchar(200)
|NULL
|
|===

.Description
--
(left(replace([PackagePath],[ProjectPath]+'\',''),(200)))
--
{empty} +

.Referenced Columns
--
* xref:ssis.package_src.adoc#column-packagename[+ssis.Package_src.PackageName+]
--

.Referencing Columns
--
* xref:ssis.packageflow_tgt.adoc#column-packagename[+ssis.PackageFlow_tgt.PackageName+]
--


[#column-taskfrom]
=== TaskFrom

[cols="d,8a,m,m,m"]
|===
|3
|*TaskFrom*
|varchar(2000)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis_t.tblprecedenceconstraint.adoc#column-taskfrom[+ssis_t.TblPrecedenceConstraint.TaskFrom+]
--

.Referencing Columns
--
* xref:ssis.packageflow_tgt.adoc#column-taskfrom[+ssis.PackageFlow_tgt.TaskFrom+]
--


[#column-taskto]
=== Taskto

[cols="d,8a,m,m,m"]
|===
|4
|*Taskto*
|varchar(2000)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis_t.tblprecedenceconstraint.adoc#column-taskto[+ssis_t.TblPrecedenceConstraint.Taskto+]
--

.Referencing Columns
--
* xref:ssis.packageflow_tgt.adoc#column-taskto[+ssis.PackageFlow_tgt.Taskto+]
--


[#column-creationname]
=== CreationName

[cols="d,8a,m,m,m"]
|===
|
|CreationName
|nvarchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis_t.tblprecedenceconstraint.adoc#column-creationname[+ssis_t.TblPrecedenceConstraint.CreationName+]
--

.Referencing Columns
--
* xref:ssis.packageflow_tgt.adoc#column-creationname[+ssis.PackageFlow_tgt.CreationName+]
--


[#column-dtsid]
=== DTSID

[cols="d,8a,m,m,m"]
|===
|
|DTSID
|uniqueidentifier
|NULL
|
|===

.Referenced Columns
--
* xref:ssis_t.tblprecedenceconstraint.adoc#column-dtsid[+ssis_t.TblPrecedenceConstraint.DTSID+]
--

.Referencing Columns
--
* xref:ssis.packageflow_tgt.adoc#column-dtsid[+ssis.PackageFlow_tgt.DTSID+]
--


[#column-evalop]
=== EvalOp

[cols="d,8a,m,m,m"]
|===
|
|EvalOp
|int
|NULL
|
|===

.Referenced Columns
--
* xref:ssis_t.tblprecedenceconstraint.adoc#column-evalop[+ssis_t.TblPrecedenceConstraint.EvalOp+]
--

.Referencing Columns
--
* xref:ssis.packageflow_tgt.adoc#column-evalop[+ssis.PackageFlow_tgt.EvalOp+]
--


[#column-expression]
=== Expression

[cols="d,8a,m,m,m"]
|===
|
|Expression
|nvarchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis_t.tblprecedenceconstraint.adoc#column-expression[+ssis_t.TblPrecedenceConstraint.Expression+]
--

.Referencing Columns
--
* xref:ssis.packageflow_tgt.adoc#column-expression[+ssis.PackageFlow_tgt.Expression+]
--


[#column-flowtype]
=== FlowType

[cols="d,8a,m,m,m"]
|===
|
|FlowType
|varchar(1000)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis_t.tblprecedenceconstraint.adoc#column-flowtype[+ssis_t.TblPrecedenceConstraint.FlowType+]
--

.Referencing Columns
--
* xref:ssis.packageflow_tgt.adoc#column-flowtype[+ssis.PackageFlow_tgt.FlowType+]
--


[#column-logicaland]
=== LogicalAnd

[cols="d,8a,m,m,m"]
|===
|
|LogicalAnd
|bit
|NULL
|
|===

.Referenced Columns
--
* xref:ssis_t.tblprecedenceconstraint.adoc#column-logicaland[+ssis_t.TblPrecedenceConstraint.LogicalAnd+]
--

.Referencing Columns
--
* xref:ssis.packageflow_tgt.adoc#column-logicaland[+ssis.PackageFlow_tgt.LogicalAnd+]
--


[#column-objectname]
=== ObjectName

[cols="d,8a,m,m,m"]
|===
|
|ObjectName
|nvarchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis_t.tblprecedenceconstraint.adoc#column-objectname[+ssis_t.TblPrecedenceConstraint.ObjectName+]
--

.Referencing Columns
--
* xref:ssis.packageflow_tgt.adoc#column-objectname[+ssis.PackageFlow_tgt.ObjectName+]
--


// end::AntoraColumnDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]
|1
|*<<column-antoramodule>>*
|varchar(50)
|NOT NULL
|

|2
|*<<column-packagename>>*
|varchar(200)
|NULL
|

|3
|*<<column-taskfrom>>*
|varchar(2000)
|NULL
|

|4
|*<<column-taskto>>*
|varchar(2000)
|NULL
|








// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]




|
|<<column-creationname>>
|nvarchar(max)
|NULL
|

|
|<<column-dtsid>>
|uniqueidentifier
|NULL
|

|
|<<column-evalop>>
|int
|NULL
|

|
|<<column-expression>>
|nvarchar(max)
|NULL
|

|
|<<column-flowtype>>
|varchar(1000)
|NULL
|

|
|<<column-logicaland>>
|bit
|NULL
|

|
|<<column-objectname>>
|nvarchar(max)
|NULL
|

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

[#index-pkunderlinepackageflowunderlinesrc]
=== PK_PackageFlow_src

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-AntoraModule>>; varchar(50)
* <<column-PackageName>>; varchar(200)
* <<column-TaskFrom>>; varchar(2000)
* <<column-Taskto>>; varchar(2000)
--
* PK, Unique, Real: 1, 1, 0


[#index-idxunderlinepackageflowunderlinesrcunderlineunderline2]
=== idx_PackageFlow_src++__++2

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-AntoraModule>>; varchar(50)
* <<column-PackageName>>; varchar(200)
--
* PK, Unique, Real: 0, 0, 0


[#index-idxunderlinepackageflowunderlinesrcunderlineunderline3]
=== idx_PackageFlow_src++__++3

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-AntoraModule>>; varchar(50)
--
* PK, Unique, Real: 0, 0, 0

// end::AntoraIndexList[]

== AntoraMeasureDetails

// tag::AntoraMeasureDetails[]

// end::AntoraMeasureDetails[]

== AntoraMeasureDescriptions



== AntoraParameterList

// tag::AntoraParameterList[]

// end::AntoraParameterList[]

== AntoraXrefCulturesList

// tag::AntoraXrefCulturesList[]
* xref:dhw:sqldb:ssis.packageflow_src.adoc[] - 
// end::AntoraXrefCulturesList[]

== cultures_count

// tag::cultures_count[]
1
// end::cultures_count[]

== Other tags

source: property.RepoObjectProperty_cross As rop_cross


=== additional_reference_csv

// tag::additional_reference_csv[]

// end::additional_reference_csv[]


=== AdocUspSteps

// tag::adocuspsteps[]

// end::adocuspsteps[]


=== AntoraReferencedList

// tag::antorareferencedlist[]
* xref:dhw:sqldb:ssis.package_src.adoc[]
* xref:dhw:sqldb:ssis_t.tblprecedenceconstraint.adoc[]
// end::antorareferencedlist[]


=== AntoraReferencingList

// tag::antorareferencinglist[]
* xref:dhw:sqldb:ssis.packageflow_tgt.adoc[]
* xref:dhw:sqldb:ssis.usp_persist_packageflow_tgt.adoc[]
// end::antorareferencinglist[]


=== Description

// tag::description[]

// end::description[]


=== exampleUsage

// tag::exampleusage[]

// end::exampleusage[]


=== exampleUsage_2

// tag::exampleusage_2[]

// end::exampleusage_2[]


=== exampleUsage_3

// tag::exampleusage_3[]

// end::exampleusage_3[]


=== exampleUsage_4

// tag::exampleusage_4[]

// end::exampleusage_4[]


=== exampleUsage_5

// tag::exampleusage_5[]

// end::exampleusage_5[]


=== exampleWrong_Usage

// tag::examplewrong_usage[]

// end::examplewrong_usage[]


=== has_execution_plan_issue

// tag::has_execution_plan_issue[]

// end::has_execution_plan_issue[]


=== has_get_referenced_issue

// tag::has_get_referenced_issue[]

// end::has_get_referenced_issue[]


=== has_history

// tag::has_history[]

// end::has_history[]


=== has_history_columns

// tag::has_history_columns[]

// end::has_history_columns[]


=== InheritanceType

// tag::inheritancetype[]

// end::inheritancetype[]


=== is_persistence

// tag::is_persistence[]

// end::is_persistence[]


=== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]

// end::is_persistence_check_duplicate_per_pk[]


=== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]

// end::is_persistence_check_for_empty_source[]


=== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]

// end::is_persistence_delete_changed[]


=== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]

// end::is_persistence_delete_missing[]


=== is_persistence_insert

// tag::is_persistence_insert[]

// end::is_persistence_insert[]


=== is_persistence_truncate

// tag::is_persistence_truncate[]

// end::is_persistence_truncate[]


=== is_persistence_update_changed

// tag::is_persistence_update_changed[]

// end::is_persistence_update_changed[]


=== is_repo_managed

// tag::is_repo_managed[]
0
// end::is_repo_managed[]


=== is_ssas

// tag::is_ssas[]
0
// end::is_ssas[]


=== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


=== MS_Description

// tag::ms_description[]

// end::ms_description[]


=== persistence_source_RepoObject_fullname

// tag::persistence_source_repoobject_fullname[]

// end::persistence_source_repoobject_fullname[]


=== persistence_source_RepoObject_fullname2

// tag::persistence_source_repoobject_fullname2[]

// end::persistence_source_repoobject_fullname2[]


=== persistence_source_RepoObject_guid

// tag::persistence_source_repoobject_guid[]

// end::persistence_source_repoobject_guid[]


=== persistence_source_RepoObject_xref

// tag::persistence_source_repoobject_xref[]

// end::persistence_source_repoobject_xref[]


=== pk_index_guid

// tag::pk_index_guid[]
F101BE14-1C3B-EC11-852C-A81E8446D5B0
// end::pk_index_guid[]


=== pk_IndexPatternColumnDatatype

// tag::pk_indexpatterncolumndatatype[]
varchar(50),varchar(200),varchar(2000),varchar(2000)
// end::pk_indexpatterncolumndatatype[]


=== pk_IndexPatternColumnName

// tag::pk_indexpatterncolumnname[]
AntoraModule,PackageName,TaskFrom,Taskto
// end::pk_indexpatterncolumnname[]


=== pk_IndexSemanticGroup

// tag::pk_indexsemanticgroup[]

// end::pk_indexsemanticgroup[]


=== ReferencedObjectList

// tag::referencedobjectlist[]
* [ssis].[Package_src]
* [ssis_t].[TblPrecedenceConstraint]
// end::referencedobjectlist[]


=== usp_persistence_RepoObject_guid

// tag::usp_persistence_repoobject_guid[]

// end::usp_persistence_repoobject_guid[]


=== UspExamples

// tag::uspexamples[]

// end::uspexamples[]


=== uspgenerator_usp_id

// tag::uspgenerator_usp_id[]

// end::uspgenerator_usp_id[]


=== UspParameters

// tag::uspparameters[]

// end::uspparameters[]

== Boolean Attributes

source: property.RepoObjectProperty WHERE property_int = 1

// tag::boolean_attributes[]


// end::boolean_attributes[]

== PlantUML diagrams

=== PlantUML Entity

// tag::puml_entity[]
[plantuml, entity-{docname}, svg, subs=macros]
....
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis.packageflow_src.adoc[]" as ssis.PackageFlow_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **TaskFrom** : (varchar(2000))
  **Taskto** : (varchar(2000))
  CreationName : (nvarchar(max))
  DTSID : (uniqueidentifier)
  EvalOp : (int)
  Expression : (nvarchar(max))
  FlowType : (varchar(1000))
  LogicalAnd : (bit)
  ObjectName : (nvarchar(max))
  --
}
....

// end::puml_entity[]

=== PlantUML Entity 1 1 FK

// tag::puml_entity_1_1_fk[]
[plantuml, entity_1_1_fk-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis.packageflow_src.adoc[]" as ssis.PackageFlow_src << V >> {
- **PK_PackageFlow_src**

..
AntoraModule; varchar(50)
PackageName; varchar(200)
TaskFrom; varchar(2000)
Taskto; varchar(2000)
--
- idx_PackageFlow_src__2

..
AntoraModule; varchar(50)
PackageName; varchar(200)
--
- idx_PackageFlow_src__3

..
AntoraModule; varchar(50)
}



footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_fk[]

=== PlantUML 1 1 ObjectRef

// tag::puml_entity_1_1_objectref[]
[plantuml, entity_1_1_objectref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis.package_src.adoc[]" as ssis.Package_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  --
}

entity "puml-link:dhw:sqldb:ssis.packageflow_src.adoc[]" as ssis.PackageFlow_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **TaskFrom** : (varchar(2000))
  **Taskto** : (varchar(2000))
  --
}

entity "puml-link:dhw:sqldb:ssis.packageflow_tgt.adoc[]" as ssis.PackageFlow_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **TaskFrom** : (varchar(2000))
  **Taskto** : (varchar(2000))
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packageflow_tgt.adoc[]" as ssis.usp_PERSIST_PackageFlow_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tblprecedenceconstraint.adoc[]" as ssis_t.TblPrecedenceConstraint << U >> {
  --
}

ssis.Package_src <.. ssis.PackageFlow_src
ssis.PackageFlow_src <.. ssis.PackageFlow_tgt
ssis.PackageFlow_src <.. ssis.usp_PERSIST_PackageFlow_tgt
ssis_t.TblPrecedenceConstraint <.. ssis.PackageFlow_src

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_objectref[]

=== PlantUML 30 0 ObjectRef

// tag::puml_entity_30_0_objectref[]
[plantuml, entity_30_0_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis.package_src.adoc[]" as ssis.Package_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  --
}

entity "puml-link:dhw:sqldb:ssis.packageflow_src.adoc[]" as ssis.PackageFlow_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **TaskFrom** : (varchar(2000))
  **Taskto** : (varchar(2000))
  --
}

entity "puml-link:dhw:sqldb:ssis.project.adoc[]" as ssis.Project << U >> {
  - **AntoraModule** : (varchar(50))
  --
}

entity "puml-link:dhw:sqldb:ssis_t.pkgstats.adoc[]" as ssis_t.pkgStats << U >> {
  - **RowID** : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tblprecedenceconstraint.adoc[]" as ssis_t.TblPrecedenceConstraint << U >> {
  --
}

ssis.Package_src <.. ssis.PackageFlow_src
ssis.Project <.. ssis.Package_src
ssis_t.pkgStats <.. ssis.Package_src
ssis_t.TblPrecedenceConstraint <.. ssis.PackageFlow_src

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_30_0_objectref[]

=== PlantUML 0 30 ObjectRef

// tag::puml_entity_0_30_objectref[]
[plantuml, entity_0_30_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:docs.ssis_adoc.adoc[]" as docs.ssis_Adoc << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageBasename** : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_adoc_t.adoc[]" as docs.ssis_Adoc_T << U >> {
  - **AntoraModule** : (varchar(50))
  **PackageBasename** : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_pumldfttask.adoc[]" as docs.ssis_PumlDftTask << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_pumlpackage.adoc[]" as docs.ssis_PumlPackage << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_pumlpartialcontrolflows.adoc[]" as docs.ssis_PumlPartialControlFlows << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_pumlpartialdataflow.adoc[]" as docs.ssis_PumlPartialDataFlow << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_task.adoc[]" as docs.ssis_Task << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_tasklist.adoc[]" as docs.ssis_TaskList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport.adoc[]" as docs.usp_AntoraExport << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_ssispartialscontent.adoc[]" as docs.usp_AntoraExport_SsisPartialsContent << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_ssis_adoc_t.adoc[]" as docs.usp_PERSIST_ssis_Adoc_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.packageflow.adoc[]" as ssis.PackageFlow << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.packageflow_src.adoc[]" as ssis.PackageFlow_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **TaskFrom** : (varchar(2000))
  **Taskto** : (varchar(2000))
  --
}

entity "puml-link:dhw:sqldb:ssis.packageflow_tgt.adoc[]" as ssis.PackageFlow_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **TaskFrom** : (varchar(2000))
  **Taskto** : (varchar(2000))
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_import.adoc[]" as ssis.usp_import << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packageflow_tgt.adoc[]" as ssis.usp_PERSIST_PackageFlow_tgt << P >> {
  --
}

docs.ssis_Adoc <.. docs.usp_PERSIST_ssis_Adoc_T
docs.ssis_Adoc <.. docs.ssis_Adoc_T
docs.ssis_Adoc_T <.. docs.usp_AntoraExport_SsisPartialsContent
docs.ssis_Adoc_T <.. docs.usp_PERSIST_ssis_Adoc_T
docs.ssis_PumlDftTask <.. docs.ssis_TaskList
docs.ssis_PumlDftTask <.. docs.ssis_Task
docs.ssis_PumlPackage <.. docs.ssis_Adoc
docs.ssis_PumlPartialControlFlows <.. docs.ssis_PumlPackage
docs.ssis_PumlPartialDataFlow <.. docs.ssis_PumlDftTask
docs.ssis_TaskList <.. docs.ssis_Adoc
docs.usp_AntoraExport_SsisPartialsContent <.. docs.usp_AntoraExport
docs.usp_PERSIST_ssis_Adoc_T <.. docs.usp_AntoraExport_SsisPartialsContent
ssis.PackageFlow <.. docs.ssis_PumlPartialDataFlow
ssis.PackageFlow <.. docs.ssis_PumlPartialControlFlows
ssis.PackageFlow_src <.. ssis.PackageFlow_tgt
ssis.PackageFlow_src <.. ssis.usp_PERSIST_PackageFlow_tgt
ssis.PackageFlow_tgt <.. ssis.PackageFlow
ssis.PackageFlow_tgt <.. ssis.usp_PERSIST_PackageFlow_tgt
ssis.usp_PERSIST_PackageFlow_tgt <.. ssis.usp_import

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_0_30_objectref[]

=== PlantUML 1 1 ColumnRef

// tag::puml_entity_1_1_colref[]
[plantuml, entity_1_1_colref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis.package_src.adoc[]" as ssis.Package_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  PackageCreationDate : (datetime)
  PackageCreatorComputerName : (nvarchar(500))
  PackageCreatorName : (varchar(1000))
  PackageDescription : (nvarchar(max))
  PackageDTSID : (uniqueidentifier)
  PackageLastModifiedProductVersion : (nvarchar(500))
  PackageLocaleID : (int)
  PackageObjectName : (nvarchar(500))
  - PackagePath : (varchar(8000))
  PackageProtectionLevel : (varchar(100))
  PackageProtectionLevelName : (varchar(28))
  PackageVersionGUID : (uniqueidentifier)
  - ProjectPath : (varchar(8000))
  - RowID : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis.packageflow_src.adoc[]" as ssis.PackageFlow_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **TaskFrom** : (varchar(2000))
  **Taskto** : (varchar(2000))
  CreationName : (nvarchar(max))
  DTSID : (uniqueidentifier)
  EvalOp : (int)
  Expression : (nvarchar(max))
  FlowType : (varchar(1000))
  LogicalAnd : (bit)
  ObjectName : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packageflow_tgt.adoc[]" as ssis.PackageFlow_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **TaskFrom** : (varchar(2000))
  **Taskto** : (varchar(2000))
  CreationName : (nvarchar(max))
  DTSID : (uniqueidentifier)
  EvalOp : (int)
  Expression : (nvarchar(max))
  FlowType : (varchar(1000))
  LogicalAnd : (bit)
  ObjectName : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packageflow_tgt.adoc[]" as ssis.usp_PERSIST_PackageFlow_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tblprecedenceconstraint.adoc[]" as ssis_t.TblPrecedenceConstraint << U >> {
  CreationName : (nvarchar(max))
  DTSID : (uniqueidentifier)
  EvalOp : (int)
  Expression : (nvarchar(max))
  FlowType : (varchar(1000))
  LogicalAnd : (bit)
  ObjectName : (nvarchar(max))
  PackagePath : (varchar(2000))
  RowID : (int)
  TaskFrom : (varchar(2000))
  Taskto : (varchar(2000))
  --
}

ssis.Package_src <.. ssis.PackageFlow_src
ssis.PackageFlow_src <.. ssis.PackageFlow_tgt
ssis.PackageFlow_src <.. ssis.usp_PERSIST_PackageFlow_tgt
ssis_t.TblPrecedenceConstraint <.. ssis.PackageFlow_src
"ssis.Package_src::AntoraModule" <-- "ssis.PackageFlow_src::AntoraModule"
"ssis.Package_src::PackageName" <-- "ssis.PackageFlow_src::PackageName"
"ssis.PackageFlow_src::AntoraModule" <-- "ssis.PackageFlow_tgt::AntoraModule"
"ssis.PackageFlow_src::CreationName" <-- "ssis.PackageFlow_tgt::CreationName"
"ssis.PackageFlow_src::DTSID" <-- "ssis.PackageFlow_tgt::DTSID"
"ssis.PackageFlow_src::EvalOp" <-- "ssis.PackageFlow_tgt::EvalOp"
"ssis.PackageFlow_src::Expression" <-- "ssis.PackageFlow_tgt::Expression"
"ssis.PackageFlow_src::FlowType" <-- "ssis.PackageFlow_tgt::FlowType"
"ssis.PackageFlow_src::LogicalAnd" <-- "ssis.PackageFlow_tgt::LogicalAnd"
"ssis.PackageFlow_src::ObjectName" <-- "ssis.PackageFlow_tgt::ObjectName"
"ssis.PackageFlow_src::PackageName" <-- "ssis.PackageFlow_tgt::PackageName"
"ssis.PackageFlow_src::TaskFrom" <-- "ssis.PackageFlow_tgt::TaskFrom"
"ssis.PackageFlow_src::Taskto" <-- "ssis.PackageFlow_tgt::Taskto"
"ssis_t.TblPrecedenceConstraint::CreationName" <-- "ssis.PackageFlow_src::CreationName"
"ssis_t.TblPrecedenceConstraint::DTSID" <-- "ssis.PackageFlow_src::DTSID"
"ssis_t.TblPrecedenceConstraint::EvalOp" <-- "ssis.PackageFlow_src::EvalOp"
"ssis_t.TblPrecedenceConstraint::Expression" <-- "ssis.PackageFlow_src::Expression"
"ssis_t.TblPrecedenceConstraint::FlowType" <-- "ssis.PackageFlow_src::FlowType"
"ssis_t.TblPrecedenceConstraint::LogicalAnd" <-- "ssis.PackageFlow_src::LogicalAnd"
"ssis_t.TblPrecedenceConstraint::ObjectName" <-- "ssis.PackageFlow_src::ObjectName"
"ssis_t.TblPrecedenceConstraint::TaskFrom" <-- "ssis.PackageFlow_src::TaskFrom"
"ssis_t.TblPrecedenceConstraint::Taskto" <-- "ssis.PackageFlow_src::Taskto"

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_colref[]


== sql_modules_definition

// tag::sql_modules_definition[]
[%collapsible]
=======
[source,sql,numbered,indent=0]
----




CREATE View [ssis].[PackageFlow_src]
As
Select
    p.AntoraModule
  , p.PackageName
  , T2.TaskFrom
  , T2.TaskTo
  , T2.FlowType
  , T2.LogicalAnd
  , T2.ObjectName
  , T2.CreationName
  , T2.DTSID
  , T2.EvalOp
  , T2.Expression
From
    ssis.Package_src                   As p
    Inner Join
        ssis_t.TblPrecedenceConstraint As T2
            On
            p.RowID = T2.RowID

----
=======
// end::sql_modules_definition[]


