// tag::HeaderFullDisplayName[]
= ssis.PackageTask_Dft_Component_src - V
// end::HeaderFullDisplayName[]

== existing_properties

// tag::existing_properties[]

:ExistsProperty--antorareferencedlist:
:ExistsProperty--antorareferencinglist:
:ExistsProperty--is_repo_managed:
:ExistsProperty--is_ssas:
:ExistsProperty--pk_index_guid:
:ExistsProperty--pk_indexpatterncolumndatatype:
:ExistsProperty--pk_indexpatterncolumnname:
:ExistsProperty--referencedobjectlist:
:ExistsProperty--sql_modules_definition:
:ExistsProperty--FK:
:ExistsProperty--AntoraIndexList:
:ExistsProperty--Columns:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
B7DCAD7F-F73E-EC11-852D-A81E8446D5B0
// end::RepoObject_guid[]

== RepoObject_FullDisplayName2

// tag::RepoObject_FullDisplayName2[]
ssis.PackageTask_Dft_Component_src
// end::RepoObject_FullDisplayName2[]

== SysObject_type

// tag::SysObject_type[]
V 
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
view
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
222675891
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2021-11-06 12:44:33
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]
[discrete]
== _


[#column-antoramodule]
=== AntoraModule

[cols="d,8a,m,m,m"]
|===
|1
|*AntoraModule*
|varchar(50)
|NOT NULL
|
|===

.Referenced Columns
--
* xref:ssis.package_src.adoc#column-antoramodule[+ssis.Package_src.AntoraModule+]
--

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_tgt.adoc#column-antoramodule[+ssis.PackageTask_Dft_Component_tgt.AntoraModule+]
--


[#column-packagename]
=== PackageName

[cols="d,8a,m,m,m"]
|===
|2
|*PackageName*
|varchar(200)
|NULL
|
|===

.Description
--
(left(replace([PackagePath],[ProjectPath]+'\',''),(200)))
--
{empty} +

.Referenced Columns
--
* xref:ssis.package_src.adoc#column-packagename[+ssis.Package_src.PackageName+]
--

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_tgt.adoc#column-packagename[+ssis.PackageTask_Dft_Component_tgt.PackageName+]
--


[#column-componentunderlinerefid]
=== Component_refId

[cols="d,8a,m,m,m"]
|===
|3
|*Component_refId*
|varchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis_t.tbltask_dft_component.adoc#column-refid[+ssis_t.TblTask_Dft_Component.refId+]
--

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_tgt.adoc#column-componentunderlinerefid[+ssis.PackageTask_Dft_Component_tgt.Component_refId+]
--


[#column-componentunderlineaccessmode]
=== Component_AccessMode

[cols="d,8a,m,m,m"]
|===
|
|Component_AccessMode
|varchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis_t.tbltask_dft_component.adoc#column-accessmode[+ssis_t.TblTask_Dft_Component.AccessMode+]
--

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_tgt.adoc#column-componentunderlineaccessmode[+ssis.PackageTask_Dft_Component_tgt.Component_AccessMode+]
--


[#column-componentunderlinealwaysusedefaultcodepage]
=== Component_AlwaysUseDefaultCodePage

[cols="d,8a,m,m,m"]
|===
|
|Component_AlwaysUseDefaultCodePage
|varchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis_t.tbltask_dft_component.adoc#column-alwaysusedefaultcodepage[+ssis_t.TblTask_Dft_Component.AlwaysUseDefaultCodePage+]
--

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_tgt.adoc#column-componentunderlinealwaysusedefaultcodepage[+ssis.PackageTask_Dft_Component_tgt.Component_AlwaysUseDefaultCodePage+]
--


[#column-componentunderlinecommandtimeout]
=== Component_CommandTimeout

[cols="d,8a,m,m,m"]
|===
|
|Component_CommandTimeout
|int
|NULL
|
|===

.Referenced Columns
--
* xref:ssis_t.tbltask_dft_component.adoc#column-commandtimeout[+ssis_t.TblTask_Dft_Component.CommandTimeout+]
--

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_tgt.adoc#column-componentunderlinecommandtimeout[+ssis.PackageTask_Dft_Component_tgt.Component_CommandTimeout+]
--


[#column-componentunderlinecomponentclassid]
=== Component_componentClassID

[cols="d,8a,m,m,m"]
|===
|
|Component_componentClassID
|varchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis_t.tbltask_dft_component.adoc#column-componentclassid[+ssis_t.TblTask_Dft_Component.componentClassID+]
--

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_tgt.adoc#column-componentunderlinecomponentclassid[+ssis.PackageTask_Dft_Component_tgt.Component_componentClassID+]
--


[#column-componentunderlineconnectionunderlinedescription]
=== Component_Connection_description

[cols="d,8a,m,m,m"]
|===
|
|Component_Connection_description
|varchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis_t.tbltask_dft_component.adoc#column-connectionunderlinedescription[+ssis_t.TblTask_Dft_Component.Connection_description+]
--

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_tgt.adoc#column-componentunderlineconnectionunderlinedescription[+ssis.PackageTask_Dft_Component_tgt.Component_Connection_description+]
--


[#column-componentunderlineconnectionunderlinename]
=== Component_Connection_name

[cols="d,8a,m,m,m"]
|===
|
|Component_Connection_name
|varchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis_t.tbltask_dft_component.adoc#column-connectionunderlinename[+ssis_t.TblTask_Dft_Component.Connection_name+]
--

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_tgt.adoc#column-componentunderlineconnectionunderlinename[+ssis.PackageTask_Dft_Component_tgt.Component_Connection_name+]
--


[#column-componentunderlineconnectionunderlinerefid]
=== Component_Connection_refId

[cols="d,8a,m,m,m"]
|===
|
|Component_Connection_refId
|varchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis_t.tbltask_dft_component.adoc#column-connectionunderlinerefid[+ssis_t.TblTask_Dft_Component.Connection_refId+]
--

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_tgt.adoc#column-componentunderlineconnectionunderlinerefid[+ssis.PackageTask_Dft_Component_tgt.Component_Connection_refId+]
--


[#column-componentunderlineconnectionmanagerid]
=== Component_connectionManagerID

[cols="d,8a,m,m,m"]
|===
|
|Component_connectionManagerID
|varchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis_t.tbltask_dft_component.adoc#column-connectionmanagerid[+ssis_t.TblTask_Dft_Component.connectionManagerID+]
--

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_tgt.adoc#column-componentunderlineconnectionmanagerid[+ssis.PackageTask_Dft_Component_tgt.Component_connectionManagerID+]
--


[#column-componentunderlineconnectionmanagerrefid]
=== Component_connectionManagerRefId

[cols="d,8a,m,m,m"]
|===
|
|Component_connectionManagerRefId
|varchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis_t.tbltask_dft_component.adoc#column-connectionmanagerrefid[+ssis_t.TblTask_Dft_Component.connectionManagerRefId+]
--

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_tgt.adoc#column-componentunderlineconnectionmanagerrefid[+ssis.PackageTask_Dft_Component_tgt.Component_connectionManagerRefId+]
--


[#column-componentunderlinecontactinfo]
=== Component_ContactInfo

[cols="d,8a,m,m,m"]
|===
|
|Component_ContactInfo
|varchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis_t.tbltask_dft_component.adoc#column-contactinfo[+ssis_t.TblTask_Dft_Component.ContactInfo+]
--

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_tgt.adoc#column-componentunderlinecontactinfo[+ssis.PackageTask_Dft_Component_tgt.Component_ContactInfo+]
--


[#column-componentunderlinedefaultcodepage]
=== Component_DefaultCodePage

[cols="d,8a,m,m,m"]
|===
|
|Component_DefaultCodePage
|int
|NULL
|
|===

.Referenced Columns
--
* xref:ssis_t.tbltask_dft_component.adoc#column-defaultcodepage[+ssis_t.TblTask_Dft_Component.DefaultCodePage+]
--

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_tgt.adoc#column-componentunderlinedefaultcodepage[+ssis.PackageTask_Dft_Component_tgt.Component_DefaultCodePage+]
--


[#column-componentunderlinedescription]
=== Component_description

[cols="d,8a,m,m,m"]
|===
|
|Component_description
|varchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis_t.tbltask_dft_component.adoc#column-description[+ssis_t.TblTask_Dft_Component.description+]
--

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_tgt.adoc#column-componentunderlinedescription[+ssis.PackageTask_Dft_Component_tgt.Component_description+]
--


[#column-componentunderlinefastloadkeepidentity]
=== Component_FastLoadKeepIdentity

[cols="d,8a,m,m,m"]
|===
|
|Component_FastLoadKeepIdentity
|bit
|NULL
|
|===

.Referenced Columns
--
* xref:ssis_t.tbltask_dft_component.adoc#column-fastloadkeepidentity[+ssis_t.TblTask_Dft_Component.FastLoadKeepIdentity+]
--

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_tgt.adoc#column-componentunderlinefastloadkeepidentity[+ssis.PackageTask_Dft_Component_tgt.Component_FastLoadKeepIdentity+]
--


[#column-componentunderlinefastloadkeepnulls]
=== Component_FastLoadKeepNulls

[cols="d,8a,m,m,m"]
|===
|
|Component_FastLoadKeepNulls
|bit
|NULL
|
|===

.Referenced Columns
--
* xref:ssis_t.tbltask_dft_component.adoc#column-fastloadkeepnulls[+ssis_t.TblTask_Dft_Component.FastLoadKeepNulls+]
--

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_tgt.adoc#column-componentunderlinefastloadkeepnulls[+ssis.PackageTask_Dft_Component_tgt.Component_FastLoadKeepNulls+]
--


[#column-componentunderlinefastloadmaxinsertcommitsize]
=== Component_FastLoadMaxInsertCommitSize

[cols="d,8a,m,m,m"]
|===
|
|Component_FastLoadMaxInsertCommitSize
|int
|NULL
|
|===

.Referenced Columns
--
* xref:ssis_t.tbltask_dft_component.adoc#column-fastloadmaxinsertcommitsize[+ssis_t.TblTask_Dft_Component.FastLoadMaxInsertCommitSize+]
--

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_tgt.adoc#column-componentunderlinefastloadmaxinsertcommitsize[+ssis.PackageTask_Dft_Component_tgt.Component_FastLoadMaxInsertCommitSize+]
--


[#column-componentunderlinefastloadoptions]
=== Component_FastLoadOptions

[cols="d,8a,m,m,m"]
|===
|
|Component_FastLoadOptions
|varchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis_t.tbltask_dft_component.adoc#column-fastloadoptions[+ssis_t.TblTask_Dft_Component.FastLoadOptions+]
--

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_tgt.adoc#column-componentunderlinefastloadoptions[+ssis.PackageTask_Dft_Component_tgt.Component_FastLoadOptions+]
--


[#column-componentunderlineissortedproperty]
=== Component_IsSortedProperty

[cols="d,8a,m,m,m"]
|===
|
|Component_IsSortedProperty
|varchar(10)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis_t.tbltask_dft_component.adoc#column-issortedproperty[+ssis_t.TblTask_Dft_Component.IsSortedProperty+]
--

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_tgt.adoc#column-componentunderlineissortedproperty[+ssis.PackageTask_Dft_Component_tgt.Component_IsSortedProperty+]
--


[#column-componentunderlinename]
=== Component_name

[cols="d,8a,m,m,m"]
|===
|
|Component_name
|varchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis_t.tbltask_dft_component.adoc#column-name[+ssis_t.TblTask_Dft_Component.name+]
--

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_tgt.adoc#column-componentunderlinename[+ssis.PackageTask_Dft_Component_tgt.Component_name+]
--


[#column-componentunderlineopenrowset]
=== Component_OpenRowset

[cols="d,8a,m,m,m"]
|===
|
|Component_OpenRowset
|varchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis_t.tbltask_dft_component.adoc#column-openrowset[+ssis_t.TblTask_Dft_Component.OpenRowset+]
--

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_tgt.adoc#column-componentunderlineopenrowset[+ssis.PackageTask_Dft_Component_tgt.Component_OpenRowset+]
--


[#column-componentunderlineopenrowsetvariable]
=== Component_OpenRowsetVariable

[cols="d,8a,m,m,m"]
|===
|
|Component_OpenRowsetVariable
|varchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis_t.tbltask_dft_component.adoc#column-openrowsetvariable[+ssis_t.TblTask_Dft_Component.OpenRowsetVariable+]
--

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_tgt.adoc#column-componentunderlineopenrowsetvariable[+ssis.PackageTask_Dft_Component_tgt.Component_OpenRowsetVariable+]
--


[#column-componentunderlineparametermapping]
=== Component_ParameterMapping

[cols="d,8a,m,m,m"]
|===
|
|Component_ParameterMapping
|varchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis_t.tbltask_dft_component.adoc#column-parametermapping[+ssis_t.TblTask_Dft_Component.ParameterMapping+]
--

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_tgt.adoc#column-componentunderlineparametermapping[+ssis.PackageTask_Dft_Component_tgt.Component_ParameterMapping+]
--


[#column-componentunderlinesqlcommand]
=== Component_SqlCommand

[cols="d,8a,m,m,m"]
|===
|
|Component_SqlCommand
|varchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis_t.tbltask_dft_component.adoc#column-sqlcommand[+ssis_t.TblTask_Dft_Component.SqlCommand+]
--

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_tgt.adoc#column-componentunderlinesqlcommand[+ssis.PackageTask_Dft_Component_tgt.Component_SqlCommand+]
--


[#column-componentunderlinesqlcommandvariable]
=== Component_SqlCommandVariable

[cols="d,8a,m,m,m"]
|===
|
|Component_SqlCommandVariable
|varchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis_t.tbltask_dft_component.adoc#column-sqlcommandvariable[+ssis_t.TblTask_Dft_Component.SqlCommandVariable+]
--

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_tgt.adoc#column-componentunderlinesqlcommandvariable[+ssis.PackageTask_Dft_Component_tgt.Component_SqlCommandVariable+]
--


[#column-componentunderlinevariablename]
=== Component_VariableName

[cols="d,8a,m,m,m"]
|===
|
|Component_VariableName
|varchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis_t.tbltask_dft_component.adoc#column-variablename[+ssis_t.TblTask_Dft_Component.VariableName+]
--

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_tgt.adoc#column-componentunderlinevariablename[+ssis.PackageTask_Dft_Component_tgt.Component_VariableName+]
--


[#column-controlflowdetailsrowid]
=== ControlFlowDetailsRowID

[cols="d,8a,m,m,m"]
|===
|
|ControlFlowDetailsRowID
|int
|NOT NULL
|
|===

.Referenced Columns
--
* xref:ssis_t.tblcontrolflow.adoc#column-controlflowdetailsrowid[+ssis_t.TblControlFlow.ControlFlowDetailsRowID+]
--

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_tgt.adoc#column-controlflowdetailsrowid[+ssis.PackageTask_Dft_Component_tgt.ControlFlowDetailsRowID+]
--


[#column-taskpath]
=== TaskPath

[cols="d,8a,m,m,m"]
|===
|
|TaskPath
|varchar(8000)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis_t.tblcontrolflow.adoc#column-taskpath[+ssis_t.TblControlFlow.TaskPath+]
--

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_tgt.adoc#column-taskpath[+ssis.PackageTask_Dft_Component_tgt.TaskPath+]
--


// end::AntoraColumnDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]
|1
|*<<column-antoramodule>>*
|varchar(50)
|NOT NULL
|

|2
|*<<column-packagename>>*
|varchar(200)
|NULL
|

|3
|*<<column-componentunderlinerefid>>*
|varchar(max)
|NULL
|



























// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]



|
|<<column-componentunderlineaccessmode>>
|varchar(max)
|NULL
|

|
|<<column-componentunderlinealwaysusedefaultcodepage>>
|varchar(max)
|NULL
|

|
|<<column-componentunderlinecommandtimeout>>
|int
|NULL
|

|
|<<column-componentunderlinecomponentclassid>>
|varchar(max)
|NULL
|

|
|<<column-componentunderlineconnectionunderlinedescription>>
|varchar(max)
|NULL
|

|
|<<column-componentunderlineconnectionunderlinename>>
|varchar(max)
|NULL
|

|
|<<column-componentunderlineconnectionunderlinerefid>>
|varchar(max)
|NULL
|

|
|<<column-componentunderlineconnectionmanagerid>>
|varchar(max)
|NULL
|

|
|<<column-componentunderlineconnectionmanagerrefid>>
|varchar(max)
|NULL
|

|
|<<column-componentunderlinecontactinfo>>
|varchar(max)
|NULL
|

|
|<<column-componentunderlinedefaultcodepage>>
|int
|NULL
|

|
|<<column-componentunderlinedescription>>
|varchar(max)
|NULL
|

|
|<<column-componentunderlinefastloadkeepidentity>>
|bit
|NULL
|

|
|<<column-componentunderlinefastloadkeepnulls>>
|bit
|NULL
|

|
|<<column-componentunderlinefastloadmaxinsertcommitsize>>
|int
|NULL
|

|
|<<column-componentunderlinefastloadoptions>>
|varchar(max)
|NULL
|

|
|<<column-componentunderlineissortedproperty>>
|varchar(10)
|NULL
|

|
|<<column-componentunderlinename>>
|varchar(max)
|NULL
|

|
|<<column-componentunderlineopenrowset>>
|varchar(max)
|NULL
|

|
|<<column-componentunderlineopenrowsetvariable>>
|varchar(max)
|NULL
|

|
|<<column-componentunderlineparametermapping>>
|varchar(max)
|NULL
|

|
|<<column-componentunderlinesqlcommand>>
|varchar(max)
|NULL
|

|
|<<column-componentunderlinesqlcommandvariable>>
|varchar(max)
|NULL
|

|
|<<column-componentunderlinevariablename>>
|varchar(max)
|NULL
|

|
|<<column-controlflowdetailsrowid>>
|int
|NOT NULL
|

|
|<<column-taskpath>>
|varchar(8000)
|NULL
|

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

[#index-pkunderlinepackagetaskunderlinedftunderlinecomponentunderlinesrc]
=== PK_PackageTask_Dft_Component_src

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-AntoraModule>>; varchar(50)
* <<column-PackageName>>; varchar(200)
* <<column-Component_refId>>; varchar(max)
--
* PK, Unique, Real: 1, 1, 0


[#index-idxunderlinepackagetaskunderlinedftunderlinecomponentunderlinesrcunderlineunderline2]
=== idx_PackageTask_Dft_Component_src++__++2

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-ControlFlowDetailsRowID>>; int
--
* PK, Unique, Real: 0, 0, 0


[#index-idxunderlinepackagetaskunderlinedftunderlinecomponentunderlinesrcunderlineunderline3]
=== idx_PackageTask_Dft_Component_src++__++3

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-AntoraModule>>; varchar(50)
* <<column-PackageName>>; varchar(200)
--
* PK, Unique, Real: 0, 0, 0


[#index-idxunderlinepackagetaskunderlinedftunderlinecomponentunderlinesrcunderlineunderline4]
=== idx_PackageTask_Dft_Component_src++__++4

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-AntoraModule>>; varchar(50)
--
* PK, Unique, Real: 0, 0, 0

// end::AntoraIndexList[]

== AntoraMeasureDetails

// tag::AntoraMeasureDetails[]

// end::AntoraMeasureDetails[]

== AntoraMeasureDescriptions



== AntoraParameterList

// tag::AntoraParameterList[]

// end::AntoraParameterList[]

== AntoraXrefCulturesList

// tag::AntoraXrefCulturesList[]
* xref:dhw:sqldb:ssis.packagetask_dft_component_src.adoc[] - 
// end::AntoraXrefCulturesList[]

== cultures_count

// tag::cultures_count[]
1
// end::cultures_count[]

== Other tags

source: property.RepoObjectProperty_cross As rop_cross


=== additional_reference_csv

// tag::additional_reference_csv[]

// end::additional_reference_csv[]


=== AdocUspSteps

// tag::adocuspsteps[]

// end::adocuspsteps[]


=== AntoraReferencedList

// tag::antorareferencedlist[]
* xref:dhw:sqldb:ssis.package_src.adoc[]
* xref:dhw:sqldb:ssis_t.tblcontrolflow.adoc[]
* xref:dhw:sqldb:ssis_t.tbltask_dft_component.adoc[]
// end::antorareferencedlist[]


=== AntoraReferencingList

// tag::antorareferencinglist[]
* xref:dhw:sqldb:ssis.packagetask_dft_component_tgt.adoc[]
* xref:dhw:sqldb:ssis.usp_persist_packagetask_dft_component_tgt.adoc[]
// end::antorareferencinglist[]


=== Description

// tag::description[]

// end::description[]


=== exampleUsage

// tag::exampleusage[]

// end::exampleusage[]


=== exampleUsage_2

// tag::exampleusage_2[]

// end::exampleusage_2[]


=== exampleUsage_3

// tag::exampleusage_3[]

// end::exampleusage_3[]


=== exampleUsage_4

// tag::exampleusage_4[]

// end::exampleusage_4[]


=== exampleUsage_5

// tag::exampleusage_5[]

// end::exampleusage_5[]


=== exampleWrong_Usage

// tag::examplewrong_usage[]

// end::examplewrong_usage[]


=== has_execution_plan_issue

// tag::has_execution_plan_issue[]

// end::has_execution_plan_issue[]


=== has_get_referenced_issue

// tag::has_get_referenced_issue[]

// end::has_get_referenced_issue[]


=== has_history

// tag::has_history[]

// end::has_history[]


=== has_history_columns

// tag::has_history_columns[]

// end::has_history_columns[]


=== InheritanceType

// tag::inheritancetype[]

// end::inheritancetype[]


=== is_persistence

// tag::is_persistence[]

// end::is_persistence[]


=== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]

// end::is_persistence_check_duplicate_per_pk[]


=== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]

// end::is_persistence_check_for_empty_source[]


=== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]

// end::is_persistence_delete_changed[]


=== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]

// end::is_persistence_delete_missing[]


=== is_persistence_insert

// tag::is_persistence_insert[]

// end::is_persistence_insert[]


=== is_persistence_truncate

// tag::is_persistence_truncate[]

// end::is_persistence_truncate[]


=== is_persistence_update_changed

// tag::is_persistence_update_changed[]

// end::is_persistence_update_changed[]


=== is_repo_managed

// tag::is_repo_managed[]
0
// end::is_repo_managed[]


=== is_ssas

// tag::is_ssas[]
0
// end::is_ssas[]


=== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


=== MS_Description

// tag::ms_description[]

// end::ms_description[]


=== persistence_source_RepoObject_fullname

// tag::persistence_source_repoobject_fullname[]

// end::persistence_source_repoobject_fullname[]


=== persistence_source_RepoObject_fullname2

// tag::persistence_source_repoobject_fullname2[]

// end::persistence_source_repoobject_fullname2[]


=== persistence_source_RepoObject_guid

// tag::persistence_source_repoobject_guid[]

// end::persistence_source_repoobject_guid[]


=== persistence_source_RepoObject_xref

// tag::persistence_source_repoobject_xref[]

// end::persistence_source_repoobject_xref[]


=== pk_index_guid

// tag::pk_index_guid[]
EF18F399-F73E-EC11-852D-A81E8446D5B0
// end::pk_index_guid[]


=== pk_IndexPatternColumnDatatype

// tag::pk_indexpatterncolumndatatype[]
varchar(50),varchar(200),varchar(max)
// end::pk_indexpatterncolumndatatype[]


=== pk_IndexPatternColumnName

// tag::pk_indexpatterncolumnname[]
AntoraModule,PackageName,Component_refId
// end::pk_indexpatterncolumnname[]


=== pk_IndexSemanticGroup

// tag::pk_indexsemanticgroup[]

// end::pk_indexsemanticgroup[]


=== ReferencedObjectList

// tag::referencedobjectlist[]
* [ssis].[Package_src]
* [ssis_t].[TblControlFlow]
* [ssis_t].[TblTask_Dft_Component]
// end::referencedobjectlist[]


=== usp_persistence_RepoObject_guid

// tag::usp_persistence_repoobject_guid[]

// end::usp_persistence_repoobject_guid[]


=== UspExamples

// tag::uspexamples[]

// end::uspexamples[]


=== uspgenerator_usp_id

// tag::uspgenerator_usp_id[]

// end::uspgenerator_usp_id[]


=== UspParameters

// tag::uspparameters[]

// end::uspparameters[]

== Boolean Attributes

source: property.RepoObjectProperty WHERE property_int = 1

// tag::boolean_attributes[]


// end::boolean_attributes[]

== PlantUML diagrams

=== PlantUML Entity

// tag::puml_entity[]
[plantuml, entity-{docname}, svg, subs=macros]
....
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_src.adoc[]" as ssis.PackageTask_Dft_Component_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Component_refId** : (varchar(max))
  Component_AccessMode : (varchar(max))
  Component_AlwaysUseDefaultCodePage : (varchar(max))
  Component_CommandTimeout : (int)
  Component_componentClassID : (varchar(max))
  Component_Connection_description : (varchar(max))
  Component_Connection_name : (varchar(max))
  Component_Connection_refId : (varchar(max))
  Component_connectionManagerID : (varchar(max))
  Component_connectionManagerRefId : (varchar(max))
  Component_ContactInfo : (varchar(max))
  Component_DefaultCodePage : (int)
  Component_description : (varchar(max))
  Component_FastLoadKeepIdentity : (bit)
  Component_FastLoadKeepNulls : (bit)
  Component_FastLoadMaxInsertCommitSize : (int)
  Component_FastLoadOptions : (varchar(max))
  Component_IsSortedProperty : (varchar(10))
  Component_name : (varchar(max))
  Component_OpenRowset : (varchar(max))
  Component_OpenRowsetVariable : (varchar(max))
  Component_ParameterMapping : (varchar(max))
  Component_SqlCommand : (varchar(max))
  Component_SqlCommandVariable : (varchar(max))
  Component_VariableName : (varchar(max))
  - ControlFlowDetailsRowID : (int)
  TaskPath : (varchar(8000))
  --
}
....

// end::puml_entity[]

=== PlantUML Entity 1 1 FK

// tag::puml_entity_1_1_fk[]
[plantuml, entity_1_1_fk-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_src.adoc[]" as ssis.PackageTask_Dft_Component_src << V >> {
- **PK_PackageTask_Dft_Component_src**

..
AntoraModule; varchar(50)
PackageName; varchar(200)
Component_refId; varchar(max)
--
- idx_PackageTask_Dft_Component_src__2

..
ControlFlowDetailsRowID; int
--
- idx_PackageTask_Dft_Component_src__3

..
AntoraModule; varchar(50)
PackageName; varchar(200)
--
- idx_PackageTask_Dft_Component_src__4

..
AntoraModule; varchar(50)
}



footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_fk[]

=== PlantUML 1 1 ObjectRef

// tag::puml_entity_1_1_objectref[]
[plantuml, entity_1_1_objectref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis.package_src.adoc[]" as ssis.Package_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_src.adoc[]" as ssis.PackageTask_Dft_Component_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Component_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_tgt.adoc[]" as ssis.PackageTask_Dft_Component_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Component_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packagetask_dft_component_tgt.adoc[]" as ssis.usp_PERSIST_PackageTask_Dft_Component_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tblcontrolflow.adoc[]" as ssis_t.TblControlFlow << U >> {
  - **ControlFlowDetailsRowID** : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_dft_component.adoc[]" as ssis_t.TblTask_Dft_Component << U >> {
  - **DftComponentId** : (int)
  --
}

ssis.Package_src <.. ssis.PackageTask_Dft_Component_src
ssis.PackageTask_Dft_Component_src <.. ssis.PackageTask_Dft_Component_tgt
ssis.PackageTask_Dft_Component_src <.. ssis.usp_PERSIST_PackageTask_Dft_Component_tgt
ssis_t.TblControlFlow <.. ssis.PackageTask_Dft_Component_src
ssis_t.TblTask_Dft_Component <.. ssis.PackageTask_Dft_Component_src

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_objectref[]

=== PlantUML 30 0 ObjectRef

// tag::puml_entity_30_0_objectref[]
[plantuml, entity_30_0_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis.package_src.adoc[]" as ssis.Package_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_src.adoc[]" as ssis.PackageTask_Dft_Component_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Component_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.project.adoc[]" as ssis.Project << U >> {
  - **AntoraModule** : (varchar(50))
  --
}

entity "puml-link:dhw:sqldb:ssis_t.pkgstats.adoc[]" as ssis_t.pkgStats << U >> {
  - **RowID** : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tblcontrolflow.adoc[]" as ssis_t.TblControlFlow << U >> {
  - **ControlFlowDetailsRowID** : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_dft_component.adoc[]" as ssis_t.TblTask_Dft_Component << U >> {
  - **DftComponentId** : (int)
  --
}

ssis.Package_src <.. ssis.PackageTask_Dft_Component_src
ssis.Project <.. ssis.Package_src
ssis_t.pkgStats <.. ssis.Package_src
ssis_t.TblControlFlow <.. ssis.PackageTask_Dft_Component_src
ssis_t.TblTask_Dft_Component <.. ssis.PackageTask_Dft_Component_src

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_30_0_objectref[]

=== PlantUML 0 30 ObjectRef

// tag::puml_entity_0_30_objectref[]
[plantuml, entity_0_30_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:docs.ssis_adoc.adoc[]" as docs.ssis_Adoc << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageBasename** : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_adoc_t.adoc[]" as docs.ssis_Adoc_T << U >> {
  - **AntoraModule** : (varchar(50))
  **PackageBasename** : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_dfttaskcomponentlist.adoc[]" as docs.ssis_DftTaskComponentList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_pumldfttask.adoc[]" as docs.ssis_PumlDftTask << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_pumlpartialdftcomponent.adoc[]" as docs.ssis_PumlPartialDftComponent << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_task.adoc[]" as docs.ssis_Task << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_tasklist.adoc[]" as docs.ssis_TaskList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport.adoc[]" as docs.usp_AntoraExport << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_ssispartialscontent.adoc[]" as docs.usp_AntoraExport_SsisPartialsContent << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_ssis_adoc_t.adoc[]" as docs.usp_PERSIST_ssis_Adoc_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component.adoc[]" as ssis.PackageTask_Dft_Component << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_src.adoc[]" as ssis.PackageTask_Dft_Component_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Component_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_tgt.adoc[]" as ssis.PackageTask_Dft_Component_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Component_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_import.adoc[]" as ssis.usp_import << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packagetask_dft_component_tgt.adoc[]" as ssis.usp_PERSIST_PackageTask_Dft_Component_tgt << P >> {
  --
}

docs.ssis_Adoc <.. docs.ssis_Adoc_T
docs.ssis_Adoc <.. docs.usp_PERSIST_ssis_Adoc_T
docs.ssis_Adoc_T <.. docs.usp_PERSIST_ssis_Adoc_T
docs.ssis_Adoc_T <.. docs.usp_AntoraExport_SsisPartialsContent
docs.ssis_DftTaskComponentList <.. docs.ssis_TaskList
docs.ssis_DftTaskComponentList <.. docs.ssis_Task
docs.ssis_PumlDftTask <.. docs.ssis_TaskList
docs.ssis_PumlDftTask <.. docs.ssis_Task
docs.ssis_PumlPartialDftComponent <.. docs.ssis_PumlDftTask
docs.ssis_PumlPartialDftComponent <.. docs.ssis_DftTaskComponentList
docs.ssis_TaskList <.. docs.ssis_Adoc
docs.usp_AntoraExport_SsisPartialsContent <.. docs.usp_AntoraExport
docs.usp_PERSIST_ssis_Adoc_T <.. docs.usp_AntoraExport_SsisPartialsContent
ssis.PackageTask_Dft_Component <.. docs.ssis_PumlPartialDftComponent
ssis.PackageTask_Dft_Component <.. docs.ssis_DftTaskComponentList
ssis.PackageTask_Dft_Component <.. docs.ssis_PumlDftTask
ssis.PackageTask_Dft_Component_src <.. ssis.usp_PERSIST_PackageTask_Dft_Component_tgt
ssis.PackageTask_Dft_Component_src <.. ssis.PackageTask_Dft_Component_tgt
ssis.PackageTask_Dft_Component_tgt <.. ssis.PackageTask_Dft_Component
ssis.PackageTask_Dft_Component_tgt <.. ssis.usp_PERSIST_PackageTask_Dft_Component_tgt
ssis.usp_PERSIST_PackageTask_Dft_Component_tgt <.. ssis.usp_import

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_0_30_objectref[]

=== PlantUML 1 1 ColumnRef

// tag::puml_entity_1_1_colref[]
[plantuml, entity_1_1_colref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis.package_src.adoc[]" as ssis.Package_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  PackageCreationDate : (datetime)
  PackageCreatorComputerName : (nvarchar(500))
  PackageCreatorName : (varchar(1000))
  PackageDescription : (nvarchar(max))
  PackageDTSID : (uniqueidentifier)
  PackageLastModifiedProductVersion : (nvarchar(500))
  PackageLocaleID : (int)
  PackageObjectName : (nvarchar(500))
  - PackagePath : (varchar(8000))
  PackageProtectionLevel : (varchar(100))
  PackageProtectionLevelName : (varchar(28))
  PackageVersionGUID : (uniqueidentifier)
  - ProjectPath : (varchar(8000))
  - RowID : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_src.adoc[]" as ssis.PackageTask_Dft_Component_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Component_refId** : (varchar(max))
  Component_AccessMode : (varchar(max))
  Component_AlwaysUseDefaultCodePage : (varchar(max))
  Component_CommandTimeout : (int)
  Component_componentClassID : (varchar(max))
  Component_Connection_description : (varchar(max))
  Component_Connection_name : (varchar(max))
  Component_Connection_refId : (varchar(max))
  Component_connectionManagerID : (varchar(max))
  Component_connectionManagerRefId : (varchar(max))
  Component_ContactInfo : (varchar(max))
  Component_DefaultCodePage : (int)
  Component_description : (varchar(max))
  Component_FastLoadKeepIdentity : (bit)
  Component_FastLoadKeepNulls : (bit)
  Component_FastLoadMaxInsertCommitSize : (int)
  Component_FastLoadOptions : (varchar(max))
  Component_IsSortedProperty : (varchar(10))
  Component_name : (varchar(max))
  Component_OpenRowset : (varchar(max))
  Component_OpenRowsetVariable : (varchar(max))
  Component_ParameterMapping : (varchar(max))
  Component_SqlCommand : (varchar(max))
  Component_SqlCommandVariable : (varchar(max))
  Component_VariableName : (varchar(max))
  - ControlFlowDetailsRowID : (int)
  TaskPath : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_tgt.adoc[]" as ssis.PackageTask_Dft_Component_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Component_refId** : (varchar(max))
  Component_AccessMode : (varchar(max))
  Component_AlwaysUseDefaultCodePage : (varchar(max))
  Component_CommandTimeout : (int)
  Component_componentClassID : (varchar(max))
  Component_Connection_description : (varchar(max))
  Component_Connection_name : (varchar(max))
  Component_Connection_refId : (varchar(max))
  Component_connectionManagerID : (varchar(max))
  Component_connectionManagerRefId : (varchar(max))
  Component_ContactInfo : (varchar(max))
  Component_DefaultCodePage : (int)
  Component_description : (varchar(max))
  Component_FastLoadKeepIdentity : (bit)
  Component_FastLoadKeepNulls : (bit)
  Component_FastLoadMaxInsertCommitSize : (int)
  Component_FastLoadOptions : (varchar(max))
  Component_IsSortedProperty : (varchar(10))
  Component_name : (varchar(max))
  Component_OpenRowset : (varchar(max))
  Component_OpenRowsetVariable : (varchar(max))
  Component_ParameterMapping : (varchar(max))
  Component_SqlCommand : (varchar(max))
  Component_SqlCommandVariable : (varchar(max))
  Component_VariableName : (varchar(max))
  - ControlFlowDetailsRowID : (int)
  TaskPath : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packagetask_dft_component_tgt.adoc[]" as ssis.usp_PERSIST_PackageTask_Dft_Component_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tblcontrolflow.adoc[]" as ssis_t.TblControlFlow << U >> {
  - **ControlFlowDetailsRowID** : (int)
  DelayValidationPropertyValue : (varchar(100))
  DFTQuery : (xml)
  ExecPkgTaskQry : (xml)
  ExpressionValue : (varchar(5000))
  IsDisabled : (varchar(10))
  RowID : (int)
  ScriptTaskQry : (xml)
  SqlTaskQry : (xml)
  TaskDescription : (varchar(max))
  TaskName : (varchar(2000))
  TaskPath : (varchar(8000))
  TaskType : (varchar(5000))
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_dft_component.adoc[]" as ssis_t.TblTask_Dft_Component << U >> {
  - **DftComponentId** : (int)
  AccessMode : (varchar(max))
  AlwaysUseDefaultCodePage : (varchar(max))
  CommandTimeout : (int)
  componentClassID : (varchar(max))
  Connection_description : (varchar(max))
  Connection_name : (varchar(max))
  Connection_refId : (varchar(max))
  connectionManagerID : (varchar(max))
  connectionManagerRefId : (varchar(max))
  ContactInfo : (varchar(max))
  - ControlFlowDetailsRowID : (int)
  DefaultCodePage : (int)
  description : (varchar(max))
  FastLoadKeepIdentity : (bit)
  FastLoadKeepNulls : (bit)
  FastLoadMaxInsertCommitSize : (int)
  FastLoadOptions : (varchar(max))
  inputsQry : (xml)
  IsSortedProperty : (varchar(10))
  name : (varchar(max))
  OpenRowset : (varchar(max))
  OpenRowsetVariable : (varchar(max))
  outputsQry : (xml)
  ParameterMapping : (varchar(max))
  refId : (varchar(max))
  RowID : (int)
  SqlCommand : (varchar(max))
  SqlCommandVariable : (varchar(max))
  VariableName : (varchar(max))
  --
}

ssis.Package_src <.. ssis.PackageTask_Dft_Component_src
ssis.PackageTask_Dft_Component_src <.. ssis.PackageTask_Dft_Component_tgt
ssis.PackageTask_Dft_Component_src <.. ssis.usp_PERSIST_PackageTask_Dft_Component_tgt
ssis_t.TblControlFlow <.. ssis.PackageTask_Dft_Component_src
ssis_t.TblTask_Dft_Component <.. ssis.PackageTask_Dft_Component_src
"ssis.Package_src::AntoraModule" <-- "ssis.PackageTask_Dft_Component_src::AntoraModule"
"ssis.Package_src::PackageName" <-- "ssis.PackageTask_Dft_Component_src::PackageName"
"ssis.PackageTask_Dft_Component_src::AntoraModule" <-- "ssis.PackageTask_Dft_Component_tgt::AntoraModule"
"ssis.PackageTask_Dft_Component_src::Component_AccessMode" <-- "ssis.PackageTask_Dft_Component_tgt::Component_AccessMode"
"ssis.PackageTask_Dft_Component_src::Component_AlwaysUseDefaultCodePage" <-- "ssis.PackageTask_Dft_Component_tgt::Component_AlwaysUseDefaultCodePage"
"ssis.PackageTask_Dft_Component_src::Component_CommandTimeout" <-- "ssis.PackageTask_Dft_Component_tgt::Component_CommandTimeout"
"ssis.PackageTask_Dft_Component_src::Component_componentClassID" <-- "ssis.PackageTask_Dft_Component_tgt::Component_componentClassID"
"ssis.PackageTask_Dft_Component_src::Component_Connection_description" <-- "ssis.PackageTask_Dft_Component_tgt::Component_Connection_description"
"ssis.PackageTask_Dft_Component_src::Component_Connection_name" <-- "ssis.PackageTask_Dft_Component_tgt::Component_Connection_name"
"ssis.PackageTask_Dft_Component_src::Component_Connection_refId" <-- "ssis.PackageTask_Dft_Component_tgt::Component_Connection_refId"
"ssis.PackageTask_Dft_Component_src::Component_connectionManagerID" <-- "ssis.PackageTask_Dft_Component_tgt::Component_connectionManagerID"
"ssis.PackageTask_Dft_Component_src::Component_connectionManagerRefId" <-- "ssis.PackageTask_Dft_Component_tgt::Component_connectionManagerRefId"
"ssis.PackageTask_Dft_Component_src::Component_ContactInfo" <-- "ssis.PackageTask_Dft_Component_tgt::Component_ContactInfo"
"ssis.PackageTask_Dft_Component_src::Component_DefaultCodePage" <-- "ssis.PackageTask_Dft_Component_tgt::Component_DefaultCodePage"
"ssis.PackageTask_Dft_Component_src::Component_description" <-- "ssis.PackageTask_Dft_Component_tgt::Component_description"
"ssis.PackageTask_Dft_Component_src::Component_FastLoadKeepIdentity" <-- "ssis.PackageTask_Dft_Component_tgt::Component_FastLoadKeepIdentity"
"ssis.PackageTask_Dft_Component_src::Component_FastLoadKeepNulls" <-- "ssis.PackageTask_Dft_Component_tgt::Component_FastLoadKeepNulls"
"ssis.PackageTask_Dft_Component_src::Component_FastLoadMaxInsertCommitSize" <-- "ssis.PackageTask_Dft_Component_tgt::Component_FastLoadMaxInsertCommitSize"
"ssis.PackageTask_Dft_Component_src::Component_FastLoadOptions" <-- "ssis.PackageTask_Dft_Component_tgt::Component_FastLoadOptions"
"ssis.PackageTask_Dft_Component_src::Component_IsSortedProperty" <-- "ssis.PackageTask_Dft_Component_tgt::Component_IsSortedProperty"
"ssis.PackageTask_Dft_Component_src::Component_name" <-- "ssis.PackageTask_Dft_Component_tgt::Component_name"
"ssis.PackageTask_Dft_Component_src::Component_OpenRowset" <-- "ssis.PackageTask_Dft_Component_tgt::Component_OpenRowset"
"ssis.PackageTask_Dft_Component_src::Component_OpenRowsetVariable" <-- "ssis.PackageTask_Dft_Component_tgt::Component_OpenRowsetVariable"
"ssis.PackageTask_Dft_Component_src::Component_ParameterMapping" <-- "ssis.PackageTask_Dft_Component_tgt::Component_ParameterMapping"
"ssis.PackageTask_Dft_Component_src::Component_refId" <-- "ssis.PackageTask_Dft_Component_tgt::Component_refId"
"ssis.PackageTask_Dft_Component_src::Component_SqlCommand" <-- "ssis.PackageTask_Dft_Component_tgt::Component_SqlCommand"
"ssis.PackageTask_Dft_Component_src::Component_SqlCommandVariable" <-- "ssis.PackageTask_Dft_Component_tgt::Component_SqlCommandVariable"
"ssis.PackageTask_Dft_Component_src::Component_VariableName" <-- "ssis.PackageTask_Dft_Component_tgt::Component_VariableName"
"ssis.PackageTask_Dft_Component_src::ControlFlowDetailsRowID" <-- "ssis.PackageTask_Dft_Component_tgt::ControlFlowDetailsRowID"
"ssis.PackageTask_Dft_Component_src::PackageName" <-- "ssis.PackageTask_Dft_Component_tgt::PackageName"
"ssis.PackageTask_Dft_Component_src::TaskPath" <-- "ssis.PackageTask_Dft_Component_tgt::TaskPath"
"ssis_t.TblControlFlow::ControlFlowDetailsRowID" <-- "ssis.PackageTask_Dft_Component_src::ControlFlowDetailsRowID"
"ssis_t.TblControlFlow::TaskPath" <-- "ssis.PackageTask_Dft_Component_src::TaskPath"
"ssis_t.TblTask_Dft_Component::AccessMode" <-- "ssis.PackageTask_Dft_Component_src::Component_AccessMode"
"ssis_t.TblTask_Dft_Component::AlwaysUseDefaultCodePage" <-- "ssis.PackageTask_Dft_Component_src::Component_AlwaysUseDefaultCodePage"
"ssis_t.TblTask_Dft_Component::CommandTimeout" <-- "ssis.PackageTask_Dft_Component_src::Component_CommandTimeout"
"ssis_t.TblTask_Dft_Component::componentClassID" <-- "ssis.PackageTask_Dft_Component_src::Component_componentClassID"
"ssis_t.TblTask_Dft_Component::Connection_description" <-- "ssis.PackageTask_Dft_Component_src::Component_Connection_description"
"ssis_t.TblTask_Dft_Component::Connection_name" <-- "ssis.PackageTask_Dft_Component_src::Component_Connection_name"
"ssis_t.TblTask_Dft_Component::Connection_refId" <-- "ssis.PackageTask_Dft_Component_src::Component_Connection_refId"
"ssis_t.TblTask_Dft_Component::connectionManagerID" <-- "ssis.PackageTask_Dft_Component_src::Component_connectionManagerID"
"ssis_t.TblTask_Dft_Component::connectionManagerRefId" <-- "ssis.PackageTask_Dft_Component_src::Component_connectionManagerRefId"
"ssis_t.TblTask_Dft_Component::ContactInfo" <-- "ssis.PackageTask_Dft_Component_src::Component_ContactInfo"
"ssis_t.TblTask_Dft_Component::DefaultCodePage" <-- "ssis.PackageTask_Dft_Component_src::Component_DefaultCodePage"
"ssis_t.TblTask_Dft_Component::description" <-- "ssis.PackageTask_Dft_Component_src::Component_description"
"ssis_t.TblTask_Dft_Component::FastLoadKeepIdentity" <-- "ssis.PackageTask_Dft_Component_src::Component_FastLoadKeepIdentity"
"ssis_t.TblTask_Dft_Component::FastLoadKeepNulls" <-- "ssis.PackageTask_Dft_Component_src::Component_FastLoadKeepNulls"
"ssis_t.TblTask_Dft_Component::FastLoadMaxInsertCommitSize" <-- "ssis.PackageTask_Dft_Component_src::Component_FastLoadMaxInsertCommitSize"
"ssis_t.TblTask_Dft_Component::FastLoadOptions" <-- "ssis.PackageTask_Dft_Component_src::Component_FastLoadOptions"
"ssis_t.TblTask_Dft_Component::IsSortedProperty" <-- "ssis.PackageTask_Dft_Component_src::Component_IsSortedProperty"
"ssis_t.TblTask_Dft_Component::name" <-- "ssis.PackageTask_Dft_Component_src::Component_name"
"ssis_t.TblTask_Dft_Component::OpenRowset" <-- "ssis.PackageTask_Dft_Component_src::Component_OpenRowset"
"ssis_t.TblTask_Dft_Component::OpenRowsetVariable" <-- "ssis.PackageTask_Dft_Component_src::Component_OpenRowsetVariable"
"ssis_t.TblTask_Dft_Component::ParameterMapping" <-- "ssis.PackageTask_Dft_Component_src::Component_ParameterMapping"
"ssis_t.TblTask_Dft_Component::refId" <-- "ssis.PackageTask_Dft_Component_src::Component_refId"
"ssis_t.TblTask_Dft_Component::SqlCommand" <-- "ssis.PackageTask_Dft_Component_src::Component_SqlCommand"
"ssis_t.TblTask_Dft_Component::SqlCommandVariable" <-- "ssis.PackageTask_Dft_Component_src::Component_SqlCommandVariable"
"ssis_t.TblTask_Dft_Component::VariableName" <-- "ssis.PackageTask_Dft_Component_src::Component_VariableName"

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_colref[]


== sql_modules_definition

// tag::sql_modules_definition[]
[%collapsible]
=======
[source,sql,numbered,indent=0]
----

CREATE View [ssis].[PackageTask_Dft_Component_src]
As
Select
    p.AntoraModule
  , p.PackageName
  , Component_refId                       = T3.refId
  , Component_name                        = T3.name
  , Component_componentClassID            = T3.componentClassID
  , Component_description                 = T3.description
  , Component_ContactInfo                 = T3.ContactInfo
  , Component_CommandTimeout              = T3.CommandTimeout
  , Component_OpenRowset                  = T3.[OpenRowset]
  , Component_OpenRowsetVariable          = T3.OpenRowsetVariable
  , Component_SqlCommand                  = T3.SqlCommand
  , Component_SqlCommandVariable          = T3.SqlCommandVariable
  , Component_DefaultCodePage             = T3.DefaultCodePage
  , Component_AlwaysUseDefaultCodePage    = T3.AlwaysUseDefaultCodePage
  , Component_AccessMode                  = T3.AccessMode
  , Component_ParameterMapping            = T3.ParameterMapping
  , Component_FastLoadKeepIdentity        = T3.FastLoadKeepIdentity
  , Component_FastLoadKeepNulls           = T3.FastLoadKeepNulls
  , Component_FastLoadOptions             = T3.FastLoadOptions
  , Component_FastLoadMaxInsertCommitSize = T3.FastLoadMaxInsertCommitSize
  , Component_VariableName                = T3.VariableName
  , Component_Connection_refId            = T3.Connection_refId
  , Component_connectionManagerID         = T3.connectionManagerID
  , Component_connectionManagerRefId      = T3.connectionManagerRefId
  , Component_Connection_description      = T3.Connection_description
  , Component_Connection_name             = T3.Connection_name
  , Component_IsSortedProperty            = T3.IsSortedProperty
  , T2.TaskPath
  , T2.ControlFlowDetailsRowID
From
    ssis.Package_src                 As p
    Inner Join
        ssis_t.TblControlFlow        As T2
            On
            p.RowID                    = T2.RowID

    Inner Join
        ssis_t.TblTask_Dft_Component As T3
            On
            T3.ControlFlowDetailsRowID = T2.ControlFlowDetailsRowID

----
=======
// end::sql_modules_definition[]


