// tag::HeaderFullDisplayName[]
= ssis.Package_src - V
// end::HeaderFullDisplayName[]

== existing_properties

// tag::existing_properties[]

:ExistsProperty--antorareferencedlist:
:ExistsProperty--antorareferencinglist:
:ExistsProperty--is_repo_managed:
:ExistsProperty--is_ssas:
:ExistsProperty--pk_index_guid:
:ExistsProperty--pk_indexpatterncolumndatatype:
:ExistsProperty--pk_indexpatterncolumnname:
:ExistsProperty--referencedobjectlist:
:ExistsProperty--sql_modules_definition:
:ExistsProperty--FK:
:ExistsProperty--AntoraIndexList:
:ExistsProperty--Columns:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
5564FBE4-113B-EC11-852C-A81E8446D5B0
// end::RepoObject_guid[]

== RepoObject_FullDisplayName2

// tag::RepoObject_FullDisplayName2[]
ssis.Package_src
// end::RepoObject_FullDisplayName2[]

== SysObject_type

// tag::SysObject_type[]
V 
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
view
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
2085634523
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2021-11-22 17:33:49
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]
[discrete]
== _


[#column-antoramodule]
=== AntoraModule

[cols="d,8a,m,m,m"]
|===
|1
|*AntoraModule*
|varchar(50)
|NOT NULL
|
|===

.Referenced Columns
--
* xref:ssis.project.adoc#column-antoramodule[+ssis.Project.AntoraModule+]
--

.Referencing Columns
--
* xref:ssis.antoramodule_tgt_filter.adoc#column-antoramodule[+ssis.AntoraModule_tgt_filter.AntoraModule+]
* xref:ssis.package_tgt.adoc#column-antoramodule[+ssis.Package_tgt.AntoraModule+]
* xref:ssis.packageconnection_src.adoc#column-antoramodule[+ssis.PackageConnection_src.AntoraModule+]
* xref:ssis.packageflow_src.adoc#column-antoramodule[+ssis.PackageFlow_src.AntoraModule+]
* xref:ssis.packageparameter_src.adoc#column-antoramodule[+ssis.PackageParameter_src.AntoraModule+]
* xref:ssis.packagetask_dft_component_input_externalmetadatacolumn_src.adoc#column-antoramodule[+ssis.PackageTask_Dft_Component_input_externalMetadataColumn_src.AntoraModule+]
* xref:ssis.packagetask_dft_component_input_inputcolumn_src.adoc#column-antoramodule[+ssis.PackageTask_Dft_Component_input_inputColumn_src.AntoraModule+]
* xref:ssis.packagetask_dft_component_input_src.adoc#column-antoramodule[+ssis.PackageTask_Dft_Component_input_src.AntoraModule+]
* xref:ssis.packagetask_dft_component_output_externalmetadatacolumn_src.adoc#column-antoramodule[+ssis.PackageTask_Dft_Component_output_externalMetadataColumn_src.AntoraModule+]
* xref:ssis.packagetask_dft_component_output_outputcolumn_src.adoc#column-antoramodule[+ssis.PackageTask_Dft_Component_output_outputcolumn_src.AntoraModule+]
* xref:ssis.packagetask_dft_component_output_src.adoc#column-antoramodule[+ssis.PackageTask_Dft_Component_output_src.AntoraModule+]
* xref:ssis.packagetask_dft_component_src.adoc#column-antoramodule[+ssis.PackageTask_Dft_Component_src.AntoraModule+]
* xref:ssis.packagetask_sql_parameter_src.adoc#column-antoramodule[+ssis.PackageTask_Sql_Parameter_src.AntoraModule+]
* xref:ssis.packagetask_src.adoc#column-antoramodule[+ssis.PackageTask_src.AntoraModule+]
* xref:ssis.packagevariable_src.adoc#column-antoramodule[+ssis.PackageVariable_src.AntoraModule+]
--


[#column-packagename]
=== PackageName

[cols="d,8a,m,m,m"]
|===
|2
|*PackageName*
|varchar(200)
|NULL
|
|===

.Description
--
(left(replace([PackagePath],[ProjectPath]+'\',''),(200)))
--
{empty} +

.Referenced Columns
--
* xref:ssis_t.pkgstats.adoc#column-packagename[+ssis_t.pkgStats.PackageName+]
--

.Referencing Columns
--
* xref:ssis.package_tgt.adoc#column-packagename[+ssis.Package_tgt.PackageName+]
* xref:ssis.packageconnection_src.adoc#column-packagename[+ssis.PackageConnection_src.PackageName+]
* xref:ssis.packageflow_src.adoc#column-packagename[+ssis.PackageFlow_src.PackageName+]
* xref:ssis.packageparameter_src.adoc#column-packagename[+ssis.PackageParameter_src.PackageName+]
* xref:ssis.packagetask_dft_component_input_externalmetadatacolumn_src.adoc#column-packagename[+ssis.PackageTask_Dft_Component_input_externalMetadataColumn_src.PackageName+]
* xref:ssis.packagetask_dft_component_input_inputcolumn_src.adoc#column-packagename[+ssis.PackageTask_Dft_Component_input_inputColumn_src.PackageName+]
* xref:ssis.packagetask_dft_component_input_src.adoc#column-packagename[+ssis.PackageTask_Dft_Component_input_src.PackageName+]
* xref:ssis.packagetask_dft_component_output_externalmetadatacolumn_src.adoc#column-packagename[+ssis.PackageTask_Dft_Component_output_externalMetadataColumn_src.PackageName+]
* xref:ssis.packagetask_dft_component_output_outputcolumn_src.adoc#column-packagename[+ssis.PackageTask_Dft_Component_output_outputcolumn_src.PackageName+]
* xref:ssis.packagetask_dft_component_output_src.adoc#column-packagename[+ssis.PackageTask_Dft_Component_output_src.PackageName+]
* xref:ssis.packagetask_dft_component_src.adoc#column-packagename[+ssis.PackageTask_Dft_Component_src.PackageName+]
* xref:ssis.packagetask_sql_parameter_src.adoc#column-packagename[+ssis.PackageTask_Sql_Parameter_src.PackageName+]
* xref:ssis.packagetask_src.adoc#column-packagename[+ssis.PackageTask_src.PackageName+]
* xref:ssis.packagevariable_src.adoc#column-packagename[+ssis.PackageVariable_src.PackageName+]
--


[#column-packagecreationdate]
=== PackageCreationDate

[cols="d,8a,m,m,m"]
|===
|
|PackageCreationDate
|datetime
|NULL
|
|===

.Referenced Columns
--
* xref:ssis_t.pkgstats.adoc#column-packagecreationdate[+ssis_t.pkgStats.PackageCreationDate+]
--

.Referencing Columns
--
* xref:ssis.package_tgt.adoc#column-packagecreationdate[+ssis.Package_tgt.PackageCreationDate+]
--


[#column-packagecreatorcomputername]
=== PackageCreatorComputerName

[cols="d,8a,m,m,m"]
|===
|
|PackageCreatorComputerName
|nvarchar(500)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis_t.pkgstats.adoc#column-packagecreatorcomputername[+ssis_t.pkgStats.PackageCreatorComputerName+]
--

.Referencing Columns
--
* xref:ssis.package_tgt.adoc#column-packagecreatorcomputername[+ssis.Package_tgt.PackageCreatorComputerName+]
--


[#column-packagecreatorname]
=== PackageCreatorName

[cols="d,8a,m,m,m"]
|===
|
|PackageCreatorName
|varchar(1000)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis_t.pkgstats.adoc#column-packagecreatorname[+ssis_t.pkgStats.PackageCreatorName+]
--

.Referencing Columns
--
* xref:ssis.package_tgt.adoc#column-packagecreatorname[+ssis.Package_tgt.PackageCreatorName+]
--


[#column-packagedescription]
=== PackageDescription

[cols="d,8a,m,m,m"]
|===
|
|PackageDescription
|nvarchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis_t.pkgstats.adoc#column-packagedescription[+ssis_t.pkgStats.PackageDescription+]
--

.Referencing Columns
--
* xref:ssis.package_tgt.adoc#column-packagedescription[+ssis.Package_tgt.PackageDescription+]
--


[#column-packagedtsid]
=== PackageDTSID

[cols="d,8a,m,m,m"]
|===
|
|PackageDTSID
|uniqueidentifier
|NULL
|
|===

.Referenced Columns
--
* xref:ssis_t.pkgstats.adoc#column-packagedtsid[+ssis_t.pkgStats.PackageDTSID+]
--

.Referencing Columns
--
* xref:ssis.package_tgt.adoc#column-packagedtsid[+ssis.Package_tgt.PackageDTSID+]
--


[#column-packagelastmodifiedproductversion]
=== PackageLastModifiedProductVersion

[cols="d,8a,m,m,m"]
|===
|
|PackageLastModifiedProductVersion
|nvarchar(500)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis_t.pkgstats.adoc#column-packagelastmodifiedproductversion[+ssis_t.pkgStats.PackageLastModifiedProductVersion+]
--

.Referencing Columns
--
* xref:ssis.package_tgt.adoc#column-packagelastmodifiedproductversion[+ssis.Package_tgt.PackageLastModifiedProductVersion+]
--


[#column-packagelocaleid]
=== PackageLocaleID

[cols="d,8a,m,m,m"]
|===
|
|PackageLocaleID
|int
|NULL
|
|===

.Referenced Columns
--
* xref:ssis_t.pkgstats.adoc#column-packagelocaleid[+ssis_t.pkgStats.PackageLocaleID+]
--

.Referencing Columns
--
* xref:ssis.package_tgt.adoc#column-packagelocaleid[+ssis.Package_tgt.PackageLocaleID+]
--


[#column-packageobjectname]
=== PackageObjectName

[cols="d,8a,m,m,m"]
|===
|
|PackageObjectName
|nvarchar(500)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis_t.pkgstats.adoc#column-packageobjectname[+ssis_t.pkgStats.PackageObjectName+]
--

.Referencing Columns
--
* xref:ssis.package_tgt.adoc#column-packageobjectname[+ssis.Package_tgt.PackageObjectName+]
--


[#column-packagepath]
=== PackagePath

[cols="d,8a,m,m,m"]
|===
|
|PackagePath
|varchar(8000)
|NOT NULL
|
|===

.Referenced Columns
--
* xref:ssis_t.pkgstats.adoc#column-packagepath[+ssis_t.pkgStats.PackagePath+]
--

.Referencing Columns
--
* xref:ssis.package_tgt.adoc#column-packagepath[+ssis.Package_tgt.PackagePath+]
--


[#column-packageprotectionlevel]
=== PackageProtectionLevel

[cols="d,8a,m,m,m"]
|===
|
|PackageProtectionLevel
|varchar(100)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis_t.pkgstats.adoc#column-packageprotectionlevel[+ssis_t.pkgStats.PackageProtectionLevel+]
--

.Referencing Columns
--
* xref:ssis.package_tgt.adoc#column-packageprotectionlevel[+ssis.Package_tgt.PackageProtectionLevel+]
--


[#column-packageprotectionlevelname]
=== PackageProtectionLevelName

[cols="d,8a,m,m,m"]
|===
|
|PackageProtectionLevelName
|varchar(28)
|NULL
|
|===

.Description
--
(case [PackageProtectionLevel] when '0' then 'DontSaveSensitive' when '1' then 'EncryptSensitiveWithUserKey' when '2' then 'EncryptSensitiveWithPassword' when '3' then 'EncryptAllWithPassword' when '4' then 'EncryptAllWithUserKey' when '5' then 'ServerStorage'  end)
--
{empty} +

.Referenced Columns
--
* xref:ssis_t.pkgstats.adoc#column-packageprotectionlevelname[+ssis_t.pkgStats.PackageProtectionLevelName+]
--

.Referencing Columns
--
* xref:ssis.package_tgt.adoc#column-packageprotectionlevelname[+ssis.Package_tgt.PackageProtectionLevelName+]
--


[#column-packageversionguid]
=== PackageVersionGUID

[cols="d,8a,m,m,m"]
|===
|
|PackageVersionGUID
|uniqueidentifier
|NULL
|
|===

.Referenced Columns
--
* xref:ssis_t.pkgstats.adoc#column-packageversionguid[+ssis_t.pkgStats.PackageVersionGUID+]
--

.Referencing Columns
--
* xref:ssis.package_tgt.adoc#column-packageversionguid[+ssis.Package_tgt.PackageVersionGUID+]
--


[#column-projectpath]
=== ProjectPath

[cols="d,8a,m,m,m"]
|===
|
|ProjectPath
|varchar(8000)
|NOT NULL
|
|===

.Referenced Columns
--
* xref:ssis_t.pkgstats.adoc#column-projectpath[+ssis_t.pkgStats.ProjectPath+]
--

.Referencing Columns
--
* xref:ssis.package_tgt.adoc#column-projectpath[+ssis.Package_tgt.ProjectPath+]
--


[#column-rowid]
=== RowID

[cols="d,8a,m,m,m"]
|===
|
|RowID
|int
|NOT NULL
|
|===

.Referenced Columns
--
* xref:ssis_t.pkgstats.adoc#column-rowid[+ssis_t.pkgStats.RowID+]
--

.Referencing Columns
--
* xref:ssis.package_tgt.adoc#column-rowid[+ssis.Package_tgt.RowID+]
--


// end::AntoraColumnDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]
|1
|*<<column-antoramodule>>*
|varchar(50)
|NOT NULL
|

|2
|*<<column-packagename>>*
|varchar(200)
|NULL
|















// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]


|
|<<column-packagecreationdate>>
|datetime
|NULL
|

|
|<<column-packagecreatorcomputername>>
|nvarchar(500)
|NULL
|

|
|<<column-packagecreatorname>>
|varchar(1000)
|NULL
|

|
|<<column-packagedescription>>
|nvarchar(max)
|NULL
|

|
|<<column-packagedtsid>>
|uniqueidentifier
|NULL
|

|
|<<column-packagelastmodifiedproductversion>>
|nvarchar(500)
|NULL
|

|
|<<column-packagelocaleid>>
|int
|NULL
|

|
|<<column-packageobjectname>>
|nvarchar(500)
|NULL
|

|
|<<column-packagepath>>
|varchar(8000)
|NOT NULL
|

|
|<<column-packageprotectionlevel>>
|varchar(100)
|NULL
|

|
|<<column-packageprotectionlevelname>>
|varchar(28)
|NULL
|

|
|<<column-packageversionguid>>
|uniqueidentifier
|NULL
|

|
|<<column-projectpath>>
|varchar(8000)
|NOT NULL
|

|
|<<column-rowid>>
|int
|NOT NULL
|

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

[#index-pkunderlinepackageunderlinesrc]
=== PK_Package_src

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-AntoraModule>>; varchar(50)
* <<column-PackageName>>; varchar(200)
--
* PK, Unique, Real: 1, 1, 0


[#index-idxunderlinepackageunderlinesrcunderlineunderline2]
=== idx_Package_src++__++2

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-RowID>>; int
--
* PK, Unique, Real: 0, 0, 0


[#index-idxunderlinepackageunderlinesrcunderlineunderline3]
=== idx_Package_src++__++3

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-AntoraModule>>; varchar(50)
--
* PK, Unique, Real: 0, 0, 0

// end::AntoraIndexList[]

== AntoraMeasureDetails

// tag::AntoraMeasureDetails[]

// end::AntoraMeasureDetails[]

== AntoraMeasureDescriptions



== AntoraParameterList

// tag::AntoraParameterList[]

// end::AntoraParameterList[]

== AntoraXrefCulturesList

// tag::AntoraXrefCulturesList[]
* xref:dhw:sqldb:ssis.package_src.adoc[] - 
// end::AntoraXrefCulturesList[]

== cultures_count

// tag::cultures_count[]
1
// end::cultures_count[]

== Other tags

source: property.RepoObjectProperty_cross As rop_cross


=== additional_reference_csv

// tag::additional_reference_csv[]

// end::additional_reference_csv[]


=== AdocUspSteps

// tag::adocuspsteps[]

// end::adocuspsteps[]


=== AntoraReferencedList

// tag::antorareferencedlist[]
* xref:dhw:sqldb:ssis.project.adoc[]
* xref:dhw:sqldb:ssis_t.pkgstats.adoc[]
// end::antorareferencedlist[]


=== AntoraReferencingList

// tag::antorareferencinglist[]
* xref:dhw:sqldb:ssis.antoramodule_tgt_filter.adoc[]
* xref:dhw:sqldb:ssis.package_tgt.adoc[]
* xref:dhw:sqldb:ssis.packageconnection_src.adoc[]
* xref:dhw:sqldb:ssis.packageflow_src.adoc[]
* xref:dhw:sqldb:ssis.packageparameter_src.adoc[]
* xref:dhw:sqldb:ssis.packagetask_dft_component_input_externalmetadatacolumn_src.adoc[]
* xref:dhw:sqldb:ssis.packagetask_dft_component_input_inputcolumn_src.adoc[]
* xref:dhw:sqldb:ssis.packagetask_dft_component_input_src.adoc[]
* xref:dhw:sqldb:ssis.packagetask_dft_component_output_externalmetadatacolumn_src.adoc[]
* xref:dhw:sqldb:ssis.packagetask_dft_component_output_outputcolumn_src.adoc[]
* xref:dhw:sqldb:ssis.packagetask_dft_component_output_src.adoc[]
* xref:dhw:sqldb:ssis.packagetask_dft_component_src.adoc[]
* xref:dhw:sqldb:ssis.packagetask_sql_parameter_src.adoc[]
* xref:dhw:sqldb:ssis.packagetask_src.adoc[]
* xref:dhw:sqldb:ssis.packagevariable_src.adoc[]
* xref:dhw:sqldb:ssis.usp_persist_package_tgt.adoc[]
// end::antorareferencinglist[]


=== Description

// tag::description[]

// end::description[]


=== exampleUsage

// tag::exampleusage[]

// end::exampleusage[]


=== exampleUsage_2

// tag::exampleusage_2[]

// end::exampleusage_2[]


=== exampleUsage_3

// tag::exampleusage_3[]

// end::exampleusage_3[]


=== exampleUsage_4

// tag::exampleusage_4[]

// end::exampleusage_4[]


=== exampleUsage_5

// tag::exampleusage_5[]

// end::exampleusage_5[]


=== exampleWrong_Usage

// tag::examplewrong_usage[]

// end::examplewrong_usage[]


=== has_execution_plan_issue

// tag::has_execution_plan_issue[]

// end::has_execution_plan_issue[]


=== has_get_referenced_issue

// tag::has_get_referenced_issue[]

// end::has_get_referenced_issue[]


=== has_history

// tag::has_history[]

// end::has_history[]


=== has_history_columns

// tag::has_history_columns[]

// end::has_history_columns[]


=== InheritanceType

// tag::inheritancetype[]

// end::inheritancetype[]


=== is_persistence

// tag::is_persistence[]

// end::is_persistence[]


=== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]

// end::is_persistence_check_duplicate_per_pk[]


=== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]

// end::is_persistence_check_for_empty_source[]


=== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]

// end::is_persistence_delete_changed[]


=== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]

// end::is_persistence_delete_missing[]


=== is_persistence_insert

// tag::is_persistence_insert[]

// end::is_persistence_insert[]


=== is_persistence_truncate

// tag::is_persistence_truncate[]

// end::is_persistence_truncate[]


=== is_persistence_update_changed

// tag::is_persistence_update_changed[]

// end::is_persistence_update_changed[]


=== is_repo_managed

// tag::is_repo_managed[]
0
// end::is_repo_managed[]


=== is_ssas

// tag::is_ssas[]
0
// end::is_ssas[]


=== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


=== MS_Description

// tag::ms_description[]

// end::ms_description[]


=== persistence_source_RepoObject_fullname

// tag::persistence_source_repoobject_fullname[]

// end::persistence_source_repoobject_fullname[]


=== persistence_source_RepoObject_fullname2

// tag::persistence_source_repoobject_fullname2[]

// end::persistence_source_repoobject_fullname2[]


=== persistence_source_RepoObject_guid

// tag::persistence_source_repoobject_guid[]

// end::persistence_source_repoobject_guid[]


=== persistence_source_RepoObject_xref

// tag::persistence_source_repoobject_xref[]

// end::persistence_source_repoobject_xref[]


=== pk_index_guid

// tag::pk_index_guid[]
EF01BE14-1C3B-EC11-852C-A81E8446D5B0
// end::pk_index_guid[]


=== pk_IndexPatternColumnDatatype

// tag::pk_indexpatterncolumndatatype[]
varchar(50),varchar(200)
// end::pk_indexpatterncolumndatatype[]


=== pk_IndexPatternColumnName

// tag::pk_indexpatterncolumnname[]
AntoraModule,PackageName
// end::pk_indexpatterncolumnname[]


=== pk_IndexSemanticGroup

// tag::pk_indexsemanticgroup[]

// end::pk_indexsemanticgroup[]


=== ReferencedObjectList

// tag::referencedobjectlist[]
* [ssis].[Project]
* [ssis_t].[pkgStats]
// end::referencedobjectlist[]


=== usp_persistence_RepoObject_guid

// tag::usp_persistence_repoobject_guid[]

// end::usp_persistence_repoobject_guid[]


=== UspExamples

// tag::uspexamples[]

// end::uspexamples[]


=== uspgenerator_usp_id

// tag::uspgenerator_usp_id[]

// end::uspgenerator_usp_id[]


=== UspParameters

// tag::uspparameters[]

// end::uspparameters[]

== Boolean Attributes

source: property.RepoObjectProperty WHERE property_int = 1

// tag::boolean_attributes[]


// end::boolean_attributes[]

== PlantUML diagrams

=== PlantUML Entity

// tag::puml_entity[]
[plantuml, entity-{docname}, svg, subs=macros]
....
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis.package_src.adoc[]" as ssis.Package_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  PackageCreationDate : (datetime)
  PackageCreatorComputerName : (nvarchar(500))
  PackageCreatorName : (varchar(1000))
  PackageDescription : (nvarchar(max))
  PackageDTSID : (uniqueidentifier)
  PackageLastModifiedProductVersion : (nvarchar(500))
  PackageLocaleID : (int)
  PackageObjectName : (nvarchar(500))
  - PackagePath : (varchar(8000))
  PackageProtectionLevel : (varchar(100))
  PackageProtectionLevelName : (varchar(28))
  PackageVersionGUID : (uniqueidentifier)
  - ProjectPath : (varchar(8000))
  - RowID : (int)
  --
}
....

// end::puml_entity[]

=== PlantUML Entity 1 1 FK

// tag::puml_entity_1_1_fk[]
[plantuml, entity_1_1_fk-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis.package_src.adoc[]" as ssis.Package_src << V >> {
- **PK_Package_src**

..
AntoraModule; varchar(50)
PackageName; varchar(200)
--
- idx_Package_src__2

..
RowID; int
--
- idx_Package_src__3

..
AntoraModule; varchar(50)
}



footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_fk[]

=== PlantUML 1 1 ObjectRef

// tag::puml_entity_1_1_objectref[]
[plantuml, entity_1_1_objectref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis.antoramodule_tgt_filter.adoc[]" as ssis.AntoraModule_tgt_filter << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.package_src.adoc[]" as ssis.Package_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  --
}

entity "puml-link:dhw:sqldb:ssis.package_tgt.adoc[]" as ssis.Package_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  - **PackageName** : (varchar(200))
  --
}

entity "puml-link:dhw:sqldb:ssis.packageconnection_src.adoc[]" as ssis.PackageConnection_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **ConnectionManagerID** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:ssis.packageflow_src.adoc[]" as ssis.PackageFlow_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **TaskFrom** : (varchar(2000))
  **Taskto** : (varchar(2000))
  --
}

entity "puml-link:dhw:sqldb:ssis.packageparameter_src.adoc[]" as ssis.PackageParameter_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **ParameterName** : (varchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_input_externalmetadatacolumn_src.adoc[]" as ssis.PackageTask_Dft_Component_input_externalMetadataColumn_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Column_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_input_inputcolumn_src.adoc[]" as ssis.PackageTask_Dft_Component_input_inputColumn_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Column_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_input_src.adoc[]" as ssis.PackageTask_Dft_Component_input_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **input_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_output_externalmetadatacolumn_src.adoc[]" as ssis.PackageTask_Dft_Component_output_externalMetadataColumn_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Column_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_output_outputcolumn_src.adoc[]" as ssis.PackageTask_Dft_Component_output_outputcolumn_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Column_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_output_src.adoc[]" as ssis.PackageTask_Dft_Component_output_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **output_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_src.adoc[]" as ssis.PackageTask_Dft_Component_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Component_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_sql_parameter_src.adoc[]" as ssis.PackageTask_Sql_Parameter_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **TaskPath** : (varchar(8000))
  **ParameterBindingSequence** : (varchar(1000))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_src.adoc[]" as ssis.PackageTask_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **TaskPath** : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagevariable_src.adoc[]" as ssis.PackageVariable_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **VariableName** : (varchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssis.project.adoc[]" as ssis.Project << U >> {
  - **AntoraModule** : (varchar(50))
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_package_tgt.adoc[]" as ssis.usp_PERSIST_Package_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.pkgstats.adoc[]" as ssis_t.pkgStats << U >> {
  - **RowID** : (int)
  --
}

ssis.Package_src <.. ssis.PackageTask_Dft_Component_input_inputColumn_src
ssis.Package_src <.. ssis.PackageTask_Dft_Component_input_externalMetadataColumn_src
ssis.Package_src <.. ssis.PackageTask_Dft_Component_input_src
ssis.Package_src <.. ssis.PackageTask_Dft_Component_output_src
ssis.Package_src <.. ssis.PackageTask_Dft_Component_output_outputcolumn_src
ssis.Package_src <.. ssis.PackageTask_Dft_Component_output_externalMetadataColumn_src
ssis.Package_src <.. ssis.PackageConnection_src
ssis.Package_src <.. ssis.PackageFlow_src
ssis.Package_src <.. ssis.PackageParameter_src
ssis.Package_src <.. ssis.PackageTask_Sql_Parameter_src
ssis.Package_src <.. ssis.PackageTask_src
ssis.Package_src <.. ssis.PackageVariable_src
ssis.Package_src <.. ssis.usp_PERSIST_Package_tgt
ssis.Package_src <.. ssis.PackageTask_Dft_Component_src
ssis.Package_src <.. ssis.AntoraModule_tgt_filter
ssis.Package_src <.. ssis.Package_tgt
ssis.Project <.. ssis.Package_src
ssis_t.pkgStats <.. ssis.Package_src

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_objectref[]

=== PlantUML 30 0 ObjectRef

// tag::puml_entity_30_0_objectref[]
[plantuml, entity_30_0_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis.package_src.adoc[]" as ssis.Package_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  --
}

entity "puml-link:dhw:sqldb:ssis.project.adoc[]" as ssis.Project << U >> {
  - **AntoraModule** : (varchar(50))
  --
}

entity "puml-link:dhw:sqldb:ssis_t.pkgstats.adoc[]" as ssis_t.pkgStats << U >> {
  - **RowID** : (int)
  --
}

ssis.Project <.. ssis.Package_src
ssis_t.pkgStats <.. ssis.Package_src

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_30_0_objectref[]

=== PlantUML 0 30 ObjectRef

// tag::puml_entity_0_30_objectref[]
[plantuml, entity_0_30_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:docs.ssis_adoc.adoc[]" as docs.ssis_Adoc << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageBasename** : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_adoc_t.adoc[]" as docs.ssis_Adoc_T << U >> {
  - **AntoraModule** : (varchar(50))
  - **PackageBasename** : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_dfttaskcomponentinputcolumnlist.adoc[]" as docs.ssis_DftTaskComponentInputColumnList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_dfttaskcomponentinputlist.adoc[]" as docs.ssis_DftTaskComponentInputList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_dfttaskcomponentlist.adoc[]" as docs.ssis_DftTaskComponentList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_dfttaskcomponentoutputcolumnlist.adoc[]" as docs.ssis_DftTaskComponentOutputColumnList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_dfttaskcomponentoutputlist.adoc[]" as docs.ssis_DftTaskComponentOutputList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_generallist.adoc[]" as docs.ssis_GeneralList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_navlist_package.adoc[]" as docs.ssis_navlist_package << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_packageconnectionlist.adoc[]" as docs.ssis_PackageConnectionList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_parameterlist.adoc[]" as docs.ssis_ParameterList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_projectconnectionlist.adoc[]" as docs.ssis_ProjectConnectionList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_pumldfttask.adoc[]" as docs.ssis_PumlDftTask << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_pumlpackage.adoc[]" as docs.ssis_PumlPackage << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_pumlpartialcontrolflows.adoc[]" as docs.ssis_PumlPartialControlFlows << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_pumlpartialdataflow.adoc[]" as docs.ssis_PumlPartialDataFlow << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_pumlpartialdftcomponent.adoc[]" as docs.ssis_PumlPartialDftComponent << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_pumlpartialtaskcomponent.adoc[]" as docs.ssis_PumlPartialTaskComponent << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_sqltaskparameterinnertable.adoc[]" as docs.ssis_SqlTaskParameterInnerTable << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_task.adoc[]" as docs.ssis_Task << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_tasklist.adoc[]" as docs.ssis_TaskList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_variablelist.adoc[]" as docs.ssis_VariableList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport.adoc[]" as docs.usp_AntoraExport << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_ssisnavigation.adoc[]" as docs.usp_AntoraExport_SsisNavigation << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_ssispage.adoc[]" as docs.usp_AntoraExport_SsisPage << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_ssispartialscontent.adoc[]" as docs.usp_AntoraExport_SsisPartialsContent << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_ssis_adoc_t.adoc[]" as docs.usp_PERSIST_ssis_Adoc_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.antoramodule_tgt_filter.adoc[]" as ssis.AntoraModule_tgt_filter << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.package.adoc[]" as ssis.Package << U >> {
  - **AntoraModule** : (varchar(50))
  - **PackageName** : (varchar(200))
  --
}

entity "puml-link:dhw:sqldb:ssis.package_src.adoc[]" as ssis.Package_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  --
}

entity "puml-link:dhw:sqldb:ssis.package_tgt.adoc[]" as ssis.Package_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  - **PackageName** : (varchar(200))
  --
}

entity "puml-link:dhw:sqldb:ssis.packageconnection.adoc[]" as ssis.PackageConnection << U >> {
  - **AntoraModule** : (varchar(50))
  - **PackageName** : (varchar(200))
  - **ConnectionManagerID** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:ssis.packageconnection_src.adoc[]" as ssis.PackageConnection_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **ConnectionManagerID** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:ssis.packageconnection_tgt.adoc[]" as ssis.PackageConnection_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  - **PackageName** : (varchar(200))
  - **ConnectionManagerID** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:ssis.packageflow.adoc[]" as ssis.PackageFlow << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.packageflow_src.adoc[]" as ssis.PackageFlow_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **TaskFrom** : (varchar(2000))
  **Taskto** : (varchar(2000))
  --
}

entity "puml-link:dhw:sqldb:ssis.packageflow_tgt.adoc[]" as ssis.PackageFlow_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  - **PackageName** : (varchar(200))
  - **TaskFrom** : (varchar(2000))
  - **Taskto** : (varchar(2000))
  --
}

entity "puml-link:dhw:sqldb:ssis.packageparameter.adoc[]" as ssis.PackageParameter << U >> {
  - **AntoraModule** : (varchar(50))
  - **PackageName** : (varchar(200))
  - **ParameterName** : (varchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssis.packageparameter_src.adoc[]" as ssis.PackageParameter_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **ParameterName** : (varchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssis.packageparameter_tgt.adoc[]" as ssis.PackageParameter_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  - **PackageName** : (varchar(200))
  - **ParameterName** : (varchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask.adoc[]" as ssis.PackageTask << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component.adoc[]" as ssis.PackageTask_Dft_Component << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_input.adoc[]" as ssis.PackageTask_Dft_Component_input << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_input_externalmetadatacolumn.adoc[]" as ssis.PackageTask_Dft_Component_input_externalMetadataColumn << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_input_externalmetadatacolumn_src.adoc[]" as ssis.PackageTask_Dft_Component_input_externalMetadataColumn_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Column_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_input_externalmetadatacolumn_tgt.adoc[]" as ssis.PackageTask_Dft_Component_input_externalMetadataColumn_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Column_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_input_inputcolumn.adoc[]" as ssis.PackageTask_Dft_Component_input_inputColumn << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_input_inputcolumn_src.adoc[]" as ssis.PackageTask_Dft_Component_input_inputColumn_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Column_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_input_inputcolumn_tgt.adoc[]" as ssis.PackageTask_Dft_Component_input_inputColumn_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Column_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_input_src.adoc[]" as ssis.PackageTask_Dft_Component_input_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **input_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_input_tgt.adoc[]" as ssis.PackageTask_Dft_Component_input_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **input_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_output.adoc[]" as ssis.PackageTask_Dft_Component_output << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_output_externalmetadatacolumn.adoc[]" as ssis.PackageTask_Dft_Component_output_externalMetadataColumn << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_output_externalmetadatacolumn_src.adoc[]" as ssis.PackageTask_Dft_Component_output_externalMetadataColumn_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Column_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_output_externalmetadatacolumn_tgt.adoc[]" as ssis.PackageTask_Dft_Component_output_externalMetadataColumn_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Column_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_output_outputcolumn.adoc[]" as ssis.PackageTask_Dft_Component_output_outputcolumn << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_output_outputcolumn_src.adoc[]" as ssis.PackageTask_Dft_Component_output_outputcolumn_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Column_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_output_outputcolumn_tgt.adoc[]" as ssis.PackageTask_Dft_Component_output_outputColumn_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Column_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_output_src.adoc[]" as ssis.PackageTask_Dft_Component_output_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **output_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_output_tgt.adoc[]" as ssis.PackageTask_Dft_Component_output_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **output_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_src.adoc[]" as ssis.PackageTask_Dft_Component_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Component_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_tgt.adoc[]" as ssis.PackageTask_Dft_Component_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Component_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_levellaglead.adoc[]" as ssis.PackageTask_LevelLagLead << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_sql_parameter.adoc[]" as ssis.PackageTask_Sql_Parameter << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_sql_parameter_src.adoc[]" as ssis.PackageTask_Sql_Parameter_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **TaskPath** : (varchar(8000))
  **ParameterBindingSequence** : (varchar(1000))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_sql_parameter_tgt.adoc[]" as ssis.PackageTask_Sql_Parameter_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  - **PackageName** : (varchar(200))
  - **TaskPath** : (varchar(8000))
  - **ParameterBindingSequence** : (varchar(1000))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_src.adoc[]" as ssis.PackageTask_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **TaskPath** : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_tgt.adoc[]" as ssis.PackageTask_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  - **PackageName** : (varchar(200))
  - **TaskPath** : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagevariable.adoc[]" as ssis.PackageVariable << U >> {
  - **AntoraModule** : (varchar(50))
  - **PackageName** : (varchar(200))
  - **VariableName** : (varchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagevariable_src.adoc[]" as ssis.PackageVariable_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **VariableName** : (varchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagevariable_tgt.adoc[]" as ssis.PackageVariable_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  - **PackageName** : (varchar(200))
  - **VariableName** : (varchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssis.projectconnection.adoc[]" as ssis.ProjectConnection << U >> {
  - **AntoraModule** : (varchar(50))
  - **ConnectionManagerID** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:ssis.projectconnection_tgt.adoc[]" as ssis.ProjectConnection_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  - **ConnectionManagerID** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_import.adoc[]" as ssis.usp_import << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_package_tgt.adoc[]" as ssis.usp_PERSIST_Package_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packageconnection_tgt.adoc[]" as ssis.usp_PERSIST_PackageConnection_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packageflow_tgt.adoc[]" as ssis.usp_PERSIST_PackageFlow_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packageparameter_tgt.adoc[]" as ssis.usp_PERSIST_PackageParameter_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packagetask_dft_component_input_externalmetadatacolumn_tgt.adoc[]" as ssis.usp_PERSIST_PackageTask_Dft_Component_input_externalMetadataColumn_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packagetask_dft_component_input_inputcolumn_tgt.adoc[]" as ssis.usp_PERSIST_PackageTask_Dft_Component_input_inputColumn_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packagetask_dft_component_input_tgt.adoc[]" as ssis.usp_PERSIST_PackageTask_Dft_Component_input_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packagetask_dft_component_output_externalmetadatacolumn_tgt.adoc[]" as ssis.usp_PERSIST_PackageTask_Dft_Component_output_externalMetadataColumn_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packagetask_dft_component_output_outputcolumn_tgt.adoc[]" as ssis.usp_PERSIST_PackageTask_Dft_Component_output_outputColumn_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packagetask_dft_component_output_tgt.adoc[]" as ssis.usp_PERSIST_PackageTask_Dft_Component_output_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packagetask_dft_component_tgt.adoc[]" as ssis.usp_PERSIST_PackageTask_Dft_Component_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packagetask_sql_parameter_tgt.adoc[]" as ssis.usp_PERSIST_PackageTask_Sql_Parameter_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packagetask_tgt.adoc[]" as ssis.usp_PERSIST_PackageTask_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packagevariable_tgt.adoc[]" as ssis.usp_PERSIST_PackageVariable_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_projectconnection_tgt.adoc[]" as ssis.usp_PERSIST_ProjectConnection_tgt << P >> {
  --
}

docs.ssis_Adoc <.. docs.usp_PERSIST_ssis_Adoc_T
docs.ssis_Adoc <.. docs.ssis_Adoc_T
docs.ssis_Adoc_T <.. docs.usp_AntoraExport_SsisPartialsContent
docs.ssis_Adoc_T <.. docs.usp_PERSIST_ssis_Adoc_T
docs.ssis_DftTaskComponentInputColumnList <.. docs.ssis_DftTaskComponentInputList
docs.ssis_DftTaskComponentInputList <.. docs.ssis_DftTaskComponentList
docs.ssis_DftTaskComponentList <.. docs.ssis_TaskList
docs.ssis_DftTaskComponentList <.. docs.ssis_Task
docs.ssis_DftTaskComponentOutputColumnList <.. docs.ssis_DftTaskComponentOutputList
docs.ssis_DftTaskComponentOutputList <.. docs.ssis_DftTaskComponentList
docs.ssis_GeneralList <.. docs.ssis_Adoc
docs.ssis_navlist_package <.. docs.usp_AntoraExport_SsisNavigation
docs.ssis_PackageConnectionList <.. docs.ssis_Adoc
docs.ssis_ParameterList <.. docs.ssis_Adoc
docs.ssis_ProjectConnectionList <.. docs.ssis_Adoc
docs.ssis_PumlDftTask <.. docs.ssis_TaskList
docs.ssis_PumlDftTask <.. docs.ssis_Task
docs.ssis_PumlPackage <.. docs.ssis_Adoc
docs.ssis_PumlPartialControlFlows <.. docs.ssis_PumlPackage
docs.ssis_PumlPartialDataFlow <.. docs.ssis_PumlDftTask
docs.ssis_PumlPartialDftComponent <.. docs.ssis_PumlDftTask
docs.ssis_PumlPartialDftComponent <.. docs.ssis_DftTaskComponentList
docs.ssis_PumlPartialTaskComponent <.. docs.ssis_PumlPackage
docs.ssis_SqlTaskParameterInnerTable <.. docs.ssis_Task
docs.ssis_SqlTaskParameterInnerTable <.. docs.ssis_TaskList
docs.ssis_TaskList <.. docs.ssis_Adoc
docs.ssis_VariableList <.. docs.ssis_Adoc
docs.usp_AntoraExport_SsisNavigation <.. docs.usp_AntoraExport
docs.usp_AntoraExport_SsisPage <.. docs.usp_AntoraExport
docs.usp_AntoraExport_SsisPartialsContent <.. docs.usp_AntoraExport
docs.usp_PERSIST_ssis_Adoc_T <.. docs.usp_AntoraExport_SsisPartialsContent
ssis.AntoraModule_tgt_filter <.. ssis.PackageTask_Dft_Component_output_tgt
ssis.AntoraModule_tgt_filter <.. ssis.PackageTask_Dft_Component_input_tgt
ssis.AntoraModule_tgt_filter <.. ssis.PackageTask_Dft_Component_output_outputcolumn_tgt
ssis.AntoraModule_tgt_filter <.. ssis.PackageTask_Dft_Component_output_externalMetadataColumn_tgt
ssis.AntoraModule_tgt_filter <.. ssis.PackageTask_Dft_Component_input_inputColumn_tgt
ssis.AntoraModule_tgt_filter <.. ssis.PackageTask_Dft_Component_input_externalMetadataColumn_tgt
ssis.AntoraModule_tgt_filter <.. ssis.PackageTask_Dft_Component_tgt
ssis.AntoraModule_tgt_filter <.. ssis.ProjectConnection_tgt
ssis.AntoraModule_tgt_filter <.. ssis.PackageVariable_tgt
ssis.AntoraModule_tgt_filter <.. ssis.PackageTask_tgt
ssis.AntoraModule_tgt_filter <.. ssis.PackageTask_Sql_Parameter_tgt
ssis.AntoraModule_tgt_filter <.. ssis.PackageParameter_tgt
ssis.AntoraModule_tgt_filter <.. ssis.PackageFlow_tgt
ssis.AntoraModule_tgt_filter <.. ssis.PackageConnection_tgt
ssis.AntoraModule_tgt_filter <.. ssis.Package_tgt
ssis.Package <.. docs.ssis_Adoc
ssis.Package <.. docs.usp_AntoraExport_SsisPage
ssis.Package <.. docs.ssis_GeneralList
ssis.Package <.. docs.ssis_navlist_package
ssis.Package_src <.. ssis.AntoraModule_tgt_filter
ssis.Package_src <.. ssis.Package_tgt
ssis.Package_src <.. ssis.PackageConnection_src
ssis.Package_src <.. ssis.PackageFlow_src
ssis.Package_src <.. ssis.PackageParameter_src
ssis.Package_src <.. ssis.PackageTask_Sql_Parameter_src
ssis.Package_src <.. ssis.PackageTask_src
ssis.Package_src <.. ssis.PackageVariable_src
ssis.Package_src <.. ssis.usp_PERSIST_Package_tgt
ssis.Package_src <.. ssis.PackageTask_Dft_Component_src
ssis.Package_src <.. ssis.PackageTask_Dft_Component_input_src
ssis.Package_src <.. ssis.PackageTask_Dft_Component_output_src
ssis.Package_src <.. ssis.PackageTask_Dft_Component_output_outputcolumn_src
ssis.Package_src <.. ssis.PackageTask_Dft_Component_output_externalMetadataColumn_src
ssis.Package_src <.. ssis.PackageTask_Dft_Component_input_inputColumn_src
ssis.Package_src <.. ssis.PackageTask_Dft_Component_input_externalMetadataColumn_src
ssis.Package_tgt <.. ssis.usp_PERSIST_Package_tgt
ssis.Package_tgt <.. ssis.Package
ssis.PackageConnection <.. docs.ssis_PackageConnectionList
ssis.PackageConnection <.. docs.ssis_Task
ssis.PackageConnection <.. docs.ssis_TaskList
ssis.PackageConnection_src <.. ssis.PackageConnection_tgt
ssis.PackageConnection_src <.. ssis.usp_PERSIST_PackageConnection_tgt
ssis.PackageConnection_tgt <.. ssis.usp_PERSIST_PackageConnection_tgt
ssis.PackageConnection_tgt <.. ssis.PackageConnection
ssis.PackageFlow <.. docs.ssis_PumlPartialDataFlow
ssis.PackageFlow <.. docs.ssis_PumlPartialControlFlows
ssis.PackageFlow_src <.. ssis.PackageFlow_tgt
ssis.PackageFlow_src <.. ssis.usp_PERSIST_PackageFlow_tgt
ssis.PackageFlow_tgt <.. ssis.usp_PERSIST_PackageFlow_tgt
ssis.PackageFlow_tgt <.. ssis.PackageFlow
ssis.PackageParameter <.. docs.ssis_ParameterList
ssis.PackageParameter_src <.. ssis.PackageParameter_tgt
ssis.PackageParameter_src <.. ssis.usp_PERSIST_PackageParameter_tgt
ssis.PackageParameter_tgt <.. ssis.usp_PERSIST_PackageParameter_tgt
ssis.PackageParameter_tgt <.. ssis.PackageParameter
ssis.PackageTask <.. docs.ssis_TaskList
ssis.PackageTask <.. docs.ssis_Task
ssis.PackageTask <.. ssis.PackageTask_LevelLagLead
ssis.PackageTask_Dft_Component <.. docs.ssis_PumlDftTask
ssis.PackageTask_Dft_Component <.. docs.ssis_DftTaskComponentList
ssis.PackageTask_Dft_Component <.. docs.ssis_PumlPartialDftComponent
ssis.PackageTask_Dft_Component_input <.. docs.ssis_DftTaskComponentInputList
ssis.PackageTask_Dft_Component_input_externalMetadataColumn <.. docs.ssis_DftTaskComponentOutputColumnList
ssis.PackageTask_Dft_Component_input_externalMetadataColumn <.. docs.ssis_DftTaskComponentInputColumnList
ssis.PackageTask_Dft_Component_input_externalMetadataColumn_src <.. ssis.PackageTask_Dft_Component_input_externalMetadataColumn_tgt
ssis.PackageTask_Dft_Component_input_externalMetadataColumn_src <.. ssis.usp_PERSIST_PackageTask_Dft_Component_input_externalMetadataColumn_tgt
ssis.PackageTask_Dft_Component_input_externalMetadataColumn_tgt <.. ssis.PackageTask_Dft_Component_input_externalMetadataColumn
ssis.PackageTask_Dft_Component_input_externalMetadataColumn_tgt <.. ssis.usp_PERSIST_PackageTask_Dft_Component_input_externalMetadataColumn_tgt
ssis.PackageTask_Dft_Component_input_inputColumn <.. docs.ssis_DftTaskComponentInputColumnList
ssis.PackageTask_Dft_Component_input_inputColumn_src <.. ssis.PackageTask_Dft_Component_input_inputColumn_tgt
ssis.PackageTask_Dft_Component_input_inputColumn_src <.. ssis.usp_PERSIST_PackageTask_Dft_Component_input_inputColumn_tgt
ssis.PackageTask_Dft_Component_input_inputColumn_tgt <.. ssis.usp_PERSIST_PackageTask_Dft_Component_input_inputColumn_tgt
ssis.PackageTask_Dft_Component_input_inputColumn_tgt <.. ssis.PackageTask_Dft_Component_input_inputColumn
ssis.PackageTask_Dft_Component_input_src <.. ssis.PackageTask_Dft_Component_input_tgt
ssis.PackageTask_Dft_Component_input_src <.. ssis.usp_PERSIST_PackageTask_Dft_Component_input_tgt
ssis.PackageTask_Dft_Component_input_tgt <.. ssis.PackageTask_Dft_Component_input
ssis.PackageTask_Dft_Component_input_tgt <.. ssis.usp_PERSIST_PackageTask_Dft_Component_input_tgt
ssis.PackageTask_Dft_Component_output <.. docs.ssis_DftTaskComponentOutputList
ssis.PackageTask_Dft_Component_output_externalMetadataColumn_src <.. ssis.PackageTask_Dft_Component_output_externalMetadataColumn_tgt
ssis.PackageTask_Dft_Component_output_externalMetadataColumn_src <.. ssis.usp_PERSIST_PackageTask_Dft_Component_output_externalMetadataColumn_tgt
ssis.PackageTask_Dft_Component_output_externalMetadataColumn_tgt <.. ssis.PackageTask_Dft_Component_output_externalMetadataColumn
ssis.PackageTask_Dft_Component_output_externalMetadataColumn_tgt <.. ssis.usp_PERSIST_PackageTask_Dft_Component_output_externalMetadataColumn_tgt
ssis.PackageTask_Dft_Component_output_outputcolumn <.. docs.ssis_DftTaskComponentOutputColumnList
ssis.PackageTask_Dft_Component_output_outputcolumn_src <.. ssis.PackageTask_Dft_Component_output_outputcolumn_tgt
ssis.PackageTask_Dft_Component_output_outputcolumn_src <.. ssis.usp_PERSIST_PackageTask_Dft_Component_output_outputColumn_tgt
ssis.PackageTask_Dft_Component_output_outputcolumn_tgt <.. ssis.PackageTask_Dft_Component_output_outputcolumn
ssis.PackageTask_Dft_Component_output_outputColumn_tgt <.. ssis.usp_PERSIST_PackageTask_Dft_Component_output_outputColumn_tgt
ssis.PackageTask_Dft_Component_output_src <.. ssis.PackageTask_Dft_Component_output_tgt
ssis.PackageTask_Dft_Component_output_src <.. ssis.usp_PERSIST_PackageTask_Dft_Component_output_tgt
ssis.PackageTask_Dft_Component_output_tgt <.. ssis.PackageTask_Dft_Component_output
ssis.PackageTask_Dft_Component_output_tgt <.. ssis.usp_PERSIST_PackageTask_Dft_Component_output_tgt
ssis.PackageTask_Dft_Component_src <.. ssis.usp_PERSIST_PackageTask_Dft_Component_tgt
ssis.PackageTask_Dft_Component_src <.. ssis.PackageTask_Dft_Component_tgt
ssis.PackageTask_Dft_Component_tgt <.. ssis.usp_PERSIST_PackageTask_Dft_Component_tgt
ssis.PackageTask_Dft_Component_tgt <.. ssis.PackageTask_Dft_Component
ssis.PackageTask_LevelLagLead <.. docs.ssis_PumlPartialTaskComponent
ssis.PackageTask_Sql_Parameter <.. docs.ssis_SqlTaskParameterInnerTable
ssis.PackageTask_Sql_Parameter_src <.. ssis.PackageTask_Sql_Parameter_tgt
ssis.PackageTask_Sql_Parameter_src <.. ssis.usp_PERSIST_PackageTask_Sql_Parameter_tgt
ssis.PackageTask_Sql_Parameter_tgt <.. ssis.usp_PERSIST_PackageTask_Sql_Parameter_tgt
ssis.PackageTask_Sql_Parameter_tgt <.. ssis.PackageTask_Sql_Parameter
ssis.PackageTask_src <.. ssis.PackageTask_tgt
ssis.PackageTask_src <.. ssis.usp_PERSIST_PackageTask_tgt
ssis.PackageTask_tgt <.. ssis.usp_PERSIST_PackageTask_tgt
ssis.PackageTask_tgt <.. ssis.PackageTask
ssis.PackageVariable <.. docs.ssis_VariableList
ssis.PackageVariable_src <.. ssis.PackageVariable_tgt
ssis.PackageVariable_src <.. ssis.usp_PERSIST_PackageVariable_tgt
ssis.PackageVariable_tgt <.. ssis.usp_PERSIST_PackageVariable_tgt
ssis.PackageVariable_tgt <.. ssis.PackageVariable
ssis.ProjectConnection <.. docs.ssis_Task
ssis.ProjectConnection <.. docs.ssis_ProjectConnectionList
ssis.ProjectConnection <.. docs.ssis_TaskList
ssis.ProjectConnection_tgt <.. ssis.usp_PERSIST_ProjectConnection_tgt
ssis.ProjectConnection_tgt <.. ssis.ProjectConnection
ssis.usp_PERSIST_Package_tgt <.. ssis.usp_import
ssis.usp_PERSIST_PackageConnection_tgt <.. ssis.usp_import
ssis.usp_PERSIST_PackageFlow_tgt <.. ssis.usp_import
ssis.usp_PERSIST_PackageParameter_tgt <.. ssis.usp_import
ssis.usp_PERSIST_PackageTask_Dft_Component_input_externalMetadataColumn_tgt <.. ssis.usp_import
ssis.usp_PERSIST_PackageTask_Dft_Component_input_inputColumn_tgt <.. ssis.usp_import
ssis.usp_PERSIST_PackageTask_Dft_Component_input_tgt <.. ssis.usp_import
ssis.usp_PERSIST_PackageTask_Dft_Component_output_externalMetadataColumn_tgt <.. ssis.usp_import
ssis.usp_PERSIST_PackageTask_Dft_Component_output_outputColumn_tgt <.. ssis.usp_import
ssis.usp_PERSIST_PackageTask_Dft_Component_output_tgt <.. ssis.usp_import
ssis.usp_PERSIST_PackageTask_Dft_Component_tgt <.. ssis.usp_import
ssis.usp_PERSIST_PackageTask_Sql_Parameter_tgt <.. ssis.usp_import
ssis.usp_PERSIST_PackageTask_tgt <.. ssis.usp_import
ssis.usp_PERSIST_PackageVariable_tgt <.. ssis.usp_import
ssis.usp_PERSIST_ProjectConnection_tgt <.. ssis.usp_import

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_0_30_objectref[]

=== PlantUML 1 1 ColumnRef

// tag::puml_entity_1_1_colref[]
[plantuml, entity_1_1_colref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis.antoramodule_tgt_filter.adoc[]" as ssis.AntoraModule_tgt_filter << V >> {
  - AntoraModule : (varchar(50))
  --
}

entity "puml-link:dhw:sqldb:ssis.package_src.adoc[]" as ssis.Package_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  PackageCreationDate : (datetime)
  PackageCreatorComputerName : (nvarchar(500))
  PackageCreatorName : (varchar(1000))
  PackageDescription : (nvarchar(max))
  PackageDTSID : (uniqueidentifier)
  PackageLastModifiedProductVersion : (nvarchar(500))
  PackageLocaleID : (int)
  PackageObjectName : (nvarchar(500))
  - PackagePath : (varchar(8000))
  PackageProtectionLevel : (varchar(100))
  PackageProtectionLevelName : (varchar(28))
  PackageVersionGUID : (uniqueidentifier)
  - ProjectPath : (varchar(8000))
  - RowID : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis.package_tgt.adoc[]" as ssis.Package_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  - **PackageName** : (varchar(200))
  PackageCreationDate : (datetime)
  PackageCreatorComputerName : (nvarchar(500))
  PackageCreatorName : (varchar(1000))
  PackageDescription : (nvarchar(max))
  - PackageDTSID : (uniqueidentifier)
  PackageLastModifiedProductVersion : (nvarchar(500))
  PackageLocaleID : (int)
  PackageObjectName : (nvarchar(500))
  - PackagePath : (varchar(8000))
  PackageProtectionLevel : (varchar(100))
  PackageProtectionLevelName : (varchar(28))
  PackageVersionGUID : (uniqueidentifier)
  - ProjectPath : (varchar(8000))
  - RowID : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis.packageconnection_src.adoc[]" as ssis.PackageConnection_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **ConnectionManagerID** : (uniqueidentifier)
  ConnectionManagerName : (varchar(max))
  ConnectionManagerType : (varchar(max))
  ConnectionString : (varchar(max))
  ExpressionValue : (varchar(max))
  RetainSameConnectionProperty : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packageflow_src.adoc[]" as ssis.PackageFlow_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **TaskFrom** : (varchar(2000))
  **Taskto** : (varchar(2000))
  CreationName : (nvarchar(max))
  DTSID : (uniqueidentifier)
  EvalOp : (int)
  Expression : (nvarchar(max))
  FlowType : (varchar(1000))
  LogicalAnd : (bit)
  ObjectName : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packageparameter_src.adoc[]" as ssis.PackageParameter_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **ParameterName** : (varchar(500))
  ExpressionValue : (varchar(5000))
  ParameterDataType : (varchar(max))
  ParameterHexValue : (varchar(1000))
  ParameterValue : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_input_externalmetadatacolumn_src.adoc[]" as ssis.PackageTask_Dft_Component_input_externalMetadataColumn_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Column_refId** : (varchar(max))
  Column_dataType : (varchar(100))
  Column_length : (int)
  Column_name : (varchar(max))
  Column_precision : (int)
  Column_scale : (int)
  Component_refId : (varchar(max))
  - ControlFlowDetailsRowID : (int)
  externalMetadataColumns_isused : (bit)
  input_errorOrTruncationOperation : (varchar(100))
  input_errorRowDisposition : (varchar(100))
  input_hasSideEffects : (bit)
  input_name : (varchar(500))
  input_refId : (varchar(max))
  TaskPath : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_input_inputcolumn_src.adoc[]" as ssis.PackageTask_Dft_Component_input_inputColumn_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Column_refId** : (varchar(max))
  Column_cachedDataType : (varchar(100))
  Column_cachedName : (varchar(max))
  Column_externalMetadataColumnId : (varchar(max))
  Column_lineageId : (varchar(max))
  Component_refId : (varchar(max))
  - ControlFlowDetailsRowID : (int)
  input_errorOrTruncationOperation : (varchar(100))
  input_errorRowDisposition : (varchar(100))
  input_hasSideEffects : (bit)
  input_name : (varchar(500))
  input_refId : (varchar(max))
  TaskPath : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_input_src.adoc[]" as ssis.PackageTask_Dft_Component_input_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **input_refId** : (varchar(max))
  Component_refId : (varchar(max))
  - ControlFlowDetailsRowID : (int)
  input_errorOrTruncationOperation : (varchar(100))
  input_errorRowDisposition : (varchar(100))
  input_hasSideEffects : (bit)
  input_name : (varchar(500))
  TaskPath : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_output_externalmetadatacolumn_src.adoc[]" as ssis.PackageTask_Dft_Component_output_externalMetadataColumn_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Column_refId** : (varchar(max))
  Column_dataType : (varchar(100))
  Column_length : (int)
  Column_name : (varchar(max))
  Column_precision : (int)
  Column_scale : (int)
  Component_refId : (varchar(max))
  - ControlFlowDetailsRowID : (int)
  externalMetadataColumns_isused : (bit)
  output_name : (varchar(500))
  output_refId : (varchar(max))
  TaskPath : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_output_outputcolumn_src.adoc[]" as ssis.PackageTask_Dft_Component_output_outputcolumn_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Column_refId** : (varchar(max))
  Column_dataType : (varchar(100))
  Column_errorOrTruncationOperation : (varchar(100))
  Column_errorRowDisposition : (varchar(100))
  Column_externalMetadataColumnId : (varchar(max))
  Column_length : (int)
  Column_lineageId : (varchar(max))
  Column_name : (varchar(max))
  Column_precision : (int)
  Column_scale : (int)
  Column_truncationRowDisposition : (varchar(max))
  Component_refId : (varchar(max))
  - ControlFlowDetailsRowID : (int)
  output_isErrorOut : (bit)
  output_name : (varchar(500))
  output_refId : (varchar(max))
  TaskPath : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_output_src.adoc[]" as ssis.PackageTask_Dft_Component_output_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **output_refId** : (varchar(max))
  Component_refId : (varchar(max))
  - ControlFlowDetailsRowID : (int)
  output_isErrorOut : (bit)
  output_name : (varchar(500))
  TaskPath : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_src.adoc[]" as ssis.PackageTask_Dft_Component_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Component_refId** : (varchar(max))
  Component_AccessMode : (varchar(max))
  Component_AlwaysUseDefaultCodePage : (varchar(max))
  Component_CommandTimeout : (int)
  Component_componentClassID : (varchar(max))
  Component_Connection_description : (varchar(max))
  Component_Connection_name : (varchar(max))
  Component_Connection_refId : (varchar(max))
  Component_connectionManagerID : (varchar(max))
  Component_connectionManagerRefId : (varchar(max))
  Component_ContactInfo : (varchar(max))
  Component_DefaultCodePage : (int)
  Component_description : (varchar(max))
  Component_FastLoadKeepIdentity : (bit)
  Component_FastLoadKeepNulls : (bit)
  Component_FastLoadMaxInsertCommitSize : (int)
  Component_FastLoadOptions : (varchar(max))
  Component_IsSortedProperty : (varchar(10))
  Component_name : (varchar(max))
  Component_OpenRowset : (varchar(max))
  Component_OpenRowsetVariable : (varchar(max))
  Component_ParameterMapping : (varchar(max))
  Component_SqlCommand : (varchar(max))
  Component_SqlCommandVariable : (varchar(max))
  Component_VariableName : (varchar(max))
  - ControlFlowDetailsRowID : (int)
  TaskPath : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_sql_parameter_src.adoc[]" as ssis.PackageTask_Sql_Parameter_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **TaskPath** : (varchar(8000))
  **ParameterBindingSequence** : (varchar(1000))
  - ControlFlowDetailsRowID : (int)
  ParameterBindingParameterName : (varchar(1000))
  ResultSetParameterName : (varchar(1000))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_src.adoc[]" as ssis.PackageTask_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **TaskPath** : (varchar(8000))
  - ControlFlowDetailsRowID : (int)
  DelayValidationPropertyValue : (varchar(100))
  ExecutedPackageName : (varchar(1000))
  ExecutePackageConnection : (varchar(1000))
  ExecutePackageExpression : (varchar(1000))
  ExpressionValue : (varchar(5000))
  IsDisabled : (varchar(10))
  Script : (varchar(max))
  SqlConnection : (uniqueidentifier)
  SqlStatementSource : (nvarchar(max))
  TaskDescription : (varchar(max))
  TaskName : (varchar(2000))
  TaskType : (varchar(5000))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagevariable_src.adoc[]" as ssis.PackageVariable_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **VariableName** : (varchar(500))
  ExpressionValue : (varchar(5000))
  VariableDataType : (varchar(max))
  VariableHexValue : (varchar(1000))
  VariableValue : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.project.adoc[]" as ssis.Project << U >> {
  - **AntoraModule** : (varchar(50))
  ProjectPath : (varchar(8000))
  ~ sql_import : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_package_tgt.adoc[]" as ssis.usp_PERSIST_Package_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.pkgstats.adoc[]" as ssis_t.pkgStats << U >> {
  - **RowID** : (int)
  PackageCreationDate : (datetime)
  PackageCreatorComputerName : (nvarchar(500))
  PackageCreatorName : (varchar(1000))
  PackageDescription : (nvarchar(max))
  PackageDTSID : (uniqueidentifier)
  PackageLastModifiedProductVersion : (nvarchar(500))
  PackageLocaleID : (int)
  PackageObjectName : (nvarchar(500))
  - PackagePath : (varchar(8000))
  PackageProtectionLevel : (varchar(100))
  PackageVersionGUID : (uniqueidentifier)
  - PackageXML : (xml)
  - ProjectPath : (varchar(8000))
  # PackageName : (varchar(200))
  ~ PackageProtectionLevelName : (varchar(28))
  --
}

ssis.Package_src <.. ssis.PackageTask_Dft_Component_input_inputColumn_src
ssis.Package_src <.. ssis.PackageTask_Dft_Component_input_externalMetadataColumn_src
ssis.Package_src <.. ssis.PackageTask_Dft_Component_input_src
ssis.Package_src <.. ssis.PackageTask_Dft_Component_output_src
ssis.Package_src <.. ssis.PackageTask_Dft_Component_output_outputcolumn_src
ssis.Package_src <.. ssis.PackageTask_Dft_Component_output_externalMetadataColumn_src
ssis.Package_src <.. ssis.PackageConnection_src
ssis.Package_src <.. ssis.PackageFlow_src
ssis.Package_src <.. ssis.PackageParameter_src
ssis.Package_src <.. ssis.PackageTask_Sql_Parameter_src
ssis.Package_src <.. ssis.PackageTask_src
ssis.Package_src <.. ssis.PackageVariable_src
ssis.Package_src <.. ssis.usp_PERSIST_Package_tgt
ssis.Package_src <.. ssis.PackageTask_Dft_Component_src
ssis.Package_src <.. ssis.AntoraModule_tgt_filter
ssis.Package_src <.. ssis.Package_tgt
ssis.Project <.. ssis.Package_src
ssis_t.pkgStats <.. ssis.Package_src
"ssis.Package_src::AntoraModule" <-- "ssis.PackageConnection_src::AntoraModule"
"ssis.Package_src::AntoraModule" <-- "ssis.Package_tgt::AntoraModule"
"ssis.Package_src::AntoraModule" <-- "ssis.AntoraModule_tgt_filter::AntoraModule"
"ssis.Package_src::AntoraModule" <-- "ssis.PackageVariable_src::AntoraModule"
"ssis.Package_src::AntoraModule" <-- "ssis.PackageTask_Dft_Component_src::AntoraModule"
"ssis.Package_src::AntoraModule" <-- "ssis.PackageFlow_src::AntoraModule"
"ssis.Package_src::AntoraModule" <-- "ssis.PackageParameter_src::AntoraModule"
"ssis.Package_src::AntoraModule" <-- "ssis.PackageTask_Sql_Parameter_src::AntoraModule"
"ssis.Package_src::AntoraModule" <-- "ssis.PackageTask_src::AntoraModule"
"ssis.Package_src::AntoraModule" <-- "ssis.PackageTask_Dft_Component_input_src::AntoraModule"
"ssis.Package_src::AntoraModule" <-- "ssis.PackageTask_Dft_Component_output_src::AntoraModule"
"ssis.Package_src::AntoraModule" <-- "ssis.PackageTask_Dft_Component_output_outputcolumn_src::AntoraModule"
"ssis.Package_src::AntoraModule" <-- "ssis.PackageTask_Dft_Component_output_externalMetadataColumn_src::AntoraModule"
"ssis.Package_src::AntoraModule" <-- "ssis.PackageTask_Dft_Component_input_inputColumn_src::AntoraModule"
"ssis.Package_src::AntoraModule" <-- "ssis.PackageTask_Dft_Component_input_externalMetadataColumn_src::AntoraModule"
"ssis.Package_src::PackageCreationDate" <-- "ssis.Package_tgt::PackageCreationDate"
"ssis.Package_src::PackageCreatorComputerName" <-- "ssis.Package_tgt::PackageCreatorComputerName"
"ssis.Package_src::PackageCreatorName" <-- "ssis.Package_tgt::PackageCreatorName"
"ssis.Package_src::PackageDescription" <-- "ssis.Package_tgt::PackageDescription"
"ssis.Package_src::PackageDTSID" <-- "ssis.Package_tgt::PackageDTSID"
"ssis.Package_src::PackageLastModifiedProductVersion" <-- "ssis.Package_tgt::PackageLastModifiedProductVersion"
"ssis.Package_src::PackageLocaleID" <-- "ssis.Package_tgt::PackageLocaleID"
"ssis.Package_src::PackageName" <-- "ssis.Package_tgt::PackageName"
"ssis.Package_src::PackageName" <-- "ssis.PackageFlow_src::PackageName"
"ssis.Package_src::PackageName" <-- "ssis.PackageParameter_src::PackageName"
"ssis.Package_src::PackageName" <-- "ssis.PackageTask_Sql_Parameter_src::PackageName"
"ssis.Package_src::PackageName" <-- "ssis.PackageConnection_src::PackageName"
"ssis.Package_src::PackageName" <-- "ssis.PackageTask_src::PackageName"
"ssis.Package_src::PackageName" <-- "ssis.PackageVariable_src::PackageName"
"ssis.Package_src::PackageName" <-- "ssis.PackageTask_Dft_Component_src::PackageName"
"ssis.Package_src::PackageName" <-- "ssis.PackageTask_Dft_Component_input_externalMetadataColumn_src::PackageName"
"ssis.Package_src::PackageName" <-- "ssis.PackageTask_Dft_Component_input_inputColumn_src::PackageName"
"ssis.Package_src::PackageName" <-- "ssis.PackageTask_Dft_Component_output_externalMetadataColumn_src::PackageName"
"ssis.Package_src::PackageName" <-- "ssis.PackageTask_Dft_Component_output_outputcolumn_src::PackageName"
"ssis.Package_src::PackageName" <-- "ssis.PackageTask_Dft_Component_output_src::PackageName"
"ssis.Package_src::PackageName" <-- "ssis.PackageTask_Dft_Component_input_src::PackageName"
"ssis.Package_src::PackageObjectName" <-- "ssis.Package_tgt::PackageObjectName"
"ssis.Package_src::PackagePath" <-- "ssis.Package_tgt::PackagePath"
"ssis.Package_src::PackageProtectionLevel" <-- "ssis.Package_tgt::PackageProtectionLevel"
"ssis.Package_src::PackageProtectionLevelName" <-- "ssis.Package_tgt::PackageProtectionLevelName"
"ssis.Package_src::PackageVersionGUID" <-- "ssis.Package_tgt::PackageVersionGUID"
"ssis.Package_src::ProjectPath" <-- "ssis.Package_tgt::ProjectPath"
"ssis.Package_src::RowID" <-- "ssis.Package_tgt::RowID"
"ssis.Project::AntoraModule" <-- "ssis.Package_src::AntoraModule"
"ssis_t.pkgStats::PackageCreationDate" <-- "ssis.Package_src::PackageCreationDate"
"ssis_t.pkgStats::PackageCreatorComputerName" <-- "ssis.Package_src::PackageCreatorComputerName"
"ssis_t.pkgStats::PackageCreatorName" <-- "ssis.Package_src::PackageCreatorName"
"ssis_t.pkgStats::PackageDescription" <-- "ssis.Package_src::PackageDescription"
"ssis_t.pkgStats::PackageDTSID" <-- "ssis.Package_src::PackageDTSID"
"ssis_t.pkgStats::PackageLastModifiedProductVersion" <-- "ssis.Package_src::PackageLastModifiedProductVersion"
"ssis_t.pkgStats::PackageLocaleID" <-- "ssis.Package_src::PackageLocaleID"
"ssis_t.pkgStats::PackageName" <-- "ssis.Package_src::PackageName"
"ssis_t.pkgStats::PackageObjectName" <-- "ssis.Package_src::PackageObjectName"
"ssis_t.pkgStats::PackagePath" <-- "ssis.Package_src::PackagePath"
"ssis_t.pkgStats::PackageProtectionLevel" <-- "ssis.Package_src::PackageProtectionLevel"
"ssis_t.pkgStats::PackageProtectionLevelName" <-- "ssis.Package_src::PackageProtectionLevelName"
"ssis_t.pkgStats::PackageVersionGUID" <-- "ssis.Package_src::PackageVersionGUID"
"ssis_t.pkgStats::ProjectPath" <-- "ssis.Package_src::ProjectPath"
"ssis_t.pkgStats::RowID" <-- "ssis.Package_src::RowID"

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_colref[]


== sql_modules_definition

// tag::sql_modules_definition[]
[%collapsible]
=======
[source,sql,numbered,indent=0]
----

CREATE View ssis.Package_src
As
Select
    proj.AntoraModule
  , p.PackageName
  , p.PackageCreationDate
  , p.PackageCreatorComputerName
  , p.PackageCreatorName
  , p.PackageDescription
  , p.PackageDTSID
  , p.PackageLastModifiedProductVersion
  , p.PackageLocaleID
  , p.PackageObjectName
  , p.PackagePath
  , p.PackageProtectionLevel
  , p.PackageProtectionLevelName
  , p.PackageVersionGUID
  ----The XML data type cannot be compared or sorted, except when using the IS NULL operator.
  --, p.PackageXML
  , p.ProjectPath
  , p.RowID

--, PackageProtectionLevelName =
---- https://docs.microsoft.com/en-us/dotnet/api/microsoft.sqlserver.dts.runtime.dtsprotectionlevel?view=sqlserver-2019
----DontSaveSensitive	0	
----Sensitive information is not saved in the package. The sensitive information is removed and replaced with blanks.

----EncryptAllWithPassword	3	
----Encrypts the entire package by using a password.

----EncryptAllWithUserKey	4	
----Encrypts the entire package by using keys based on the user profile. Only the same user using the same profile can load the package.

----EncryptSensitiveWithPassword	2	
----Encrypts only sensitive information contained in the package by using a password. DPAPI is used for this encryption.

----EncryptSensitiveWithUserKey	1	
----Encrypts sensitive properties only by using keys based on the current user. Only the same user using the same profile can load the package. If a different user opens the package, the sensitive information is replaced with blanks. DPAPI is used for this encryption.

----ServerStorage	5	
----Encrypts the package within a SQL Server msdb database. This option is supported only when a package is saved to SQL Server. It is not supported when a package is saved to the File System. The access control of who can decrypt the package is controlled by SQL Server database roles. For more information, see Database-Level Roles and sysssispackages (Transact-SQL).
--Case p.PackageProtectionLevel
--    When '0'
--        Then
--        'DontSaveSensitive'
--    When '1'
--        Then
--        'EncryptSensitiveWithUserKey'
--    When '2'
--        Then
--        'EncryptSensitiveWithPassword'
--    When '3'
--        Then
--        'EncryptAllWithPassword'
--    When '4'
--        Then
--        'EncryptAllWithUserKey'
--    When '5'
--        Then
--        'ServerStorage'
--End
From
    ssis_t.pkgStats  As p
    Inner Join
        ssis.Project As proj
            On
            p.ProjectPath = proj.ProjectPath
Where
    Not Left(p.PackageName, 4) = 'obj\'
----
=======
// end::sql_modules_definition[]


