// tag::HeaderFullDisplayName[]
= ssis_t.PackageDetails - V
// end::HeaderFullDisplayName[]

== existing_properties

// tag::existing_properties[]

:ExistsProperty--antorareferencedlist:
:ExistsProperty--antorareferencinglist:
:ExistsProperty--is_repo_managed:
:ExistsProperty--is_ssas:
:ExistsProperty--referencedobjectlist:
:ExistsProperty--sql_modules_definition:
:ExistsProperty--FK:
:ExistsProperty--AntoraIndexList:
:ExistsProperty--Columns:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
5B64FBE4-113B-EC11-852C-A81E8446D5B0
// end::RepoObject_guid[]

== RepoObject_FullDisplayName2

// tag::RepoObject_FullDisplayName2[]
ssis_t.PackageDetails
// end::RepoObject_FullDisplayName2[]

== SysObject_type

// tag::SysObject_type[]
V 
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
view
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
258152015
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2021-11-01 13:46:40
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]
[discrete]
== _


[#column-packagecreationdate]
=== PackageCreationDate

[cols="d,8a,m,m,m"]
|===
|
|PackageCreationDate
|datetime
|NULL
|
|===

.Referenced Columns
--
* xref:ssis_t.pkgstats.adoc#column-packagexml[+ssis_t.pkgStats.PackageXML+]
--


[#column-packagecreatorcomputername]
=== PackageCreatorComputerName

[cols="d,8a,m,m,m"]
|===
|
|PackageCreatorComputerName
|nvarchar(500)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis_t.pkgstats.adoc#column-packagexml[+ssis_t.pkgStats.PackageXML+]
--


[#column-packagecreatorname]
=== PackageCreatorName

[cols="d,8a,m,m,m"]
|===
|
|PackageCreatorName
|nvarchar(500)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis_t.pkgstats.adoc#column-packagexml[+ssis_t.pkgStats.PackageXML+]
--


[#column-packagedescription]
=== PackageDescription

[cols="d,8a,m,m,m"]
|===
|
|PackageDescription
|nvarchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis_t.pkgstats.adoc#column-packagexml[+ssis_t.pkgStats.PackageXML+]
--


[#column-packagedtsid]
=== PackageDTSID

[cols="d,8a,m,m,m"]
|===
|
|PackageDTSID
|uniqueidentifier
|NULL
|
|===

.Referenced Columns
--
* xref:ssis_t.pkgstats.adoc#column-packagexml[+ssis_t.pkgStats.PackageXML+]
--


[#column-packagelastmodifiedproductversion]
=== PackageLastModifiedProductVersion

[cols="d,8a,m,m,m"]
|===
|
|PackageLastModifiedProductVersion
|nvarchar(500)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis_t.pkgstats.adoc#column-packagexml[+ssis_t.pkgStats.PackageXML+]
--


[#column-packagelocaleid]
=== PackageLocaleID

[cols="d,8a,m,m,m"]
|===
|
|PackageLocaleID
|int
|NULL
|
|===

.Referenced Columns
--
* xref:ssis_t.pkgstats.adoc#column-packagexml[+ssis_t.pkgStats.PackageXML+]
--


[#column-packageobjectname]
=== PackageObjectName

[cols="d,8a,m,m,m"]
|===
|
|PackageObjectName
|nvarchar(500)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis_t.pkgstats.adoc#column-packagexml[+ssis_t.pkgStats.PackageXML+]
--


[#column-packagepath]
=== PackagePath

[cols="d,8a,m,m,m"]
|===
|
|PackagePath
|varchar(8000)
|NOT NULL
|
|===

.Referenced Columns
--
* xref:ssis_t.pkgstats.adoc#column-packagepath[+ssis_t.pkgStats.PackagePath+]
--


[#column-packageprotectionlevel]
=== PackageProtectionLevel

[cols="d,8a,m,m,m"]
|===
|
|PackageProtectionLevel
|nvarchar(500)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis_t.pkgstats.adoc#column-packagexml[+ssis_t.pkgStats.PackageXML+]
--


[#column-packageversionguid]
=== PackageVersionGUID

[cols="d,8a,m,m,m"]
|===
|
|PackageVersionGUID
|uniqueidentifier
|NULL
|
|===

.Referenced Columns
--
* xref:ssis_t.pkgstats.adoc#column-packagexml[+ssis_t.pkgStats.PackageXML+]
--


[#column-rowid]
=== RowID

[cols="d,8a,m,m,m"]
|===
|
|RowID
|int
|NOT NULL
|
|===

.Referenced Columns
--
* xref:ssis_t.pkgstats.adoc#column-rowid[+ssis_t.pkgStats.RowID+]
--


// end::AntoraColumnDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]












// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]
|
|<<column-packagecreationdate>>
|datetime
|NULL
|

|
|<<column-packagecreatorcomputername>>
|nvarchar(500)
|NULL
|

|
|<<column-packagecreatorname>>
|nvarchar(500)
|NULL
|

|
|<<column-packagedescription>>
|nvarchar(max)
|NULL
|

|
|<<column-packagedtsid>>
|uniqueidentifier
|NULL
|

|
|<<column-packagelastmodifiedproductversion>>
|nvarchar(500)
|NULL
|

|
|<<column-packagelocaleid>>
|int
|NULL
|

|
|<<column-packageobjectname>>
|nvarchar(500)
|NULL
|

|
|<<column-packagepath>>
|varchar(8000)
|NOT NULL
|

|
|<<column-packageprotectionlevel>>
|nvarchar(500)
|NULL
|

|
|<<column-packageversionguid>>
|uniqueidentifier
|NULL
|

|
|<<column-rowid>>
|int
|NOT NULL
|

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

[#index-idxunderlinepackagedetailsunderlineunderline1]
=== idx_PackageDetails++__++1

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-RowID>>; int
--
* PK, Unique, Real: 0, 0, 0

// end::AntoraIndexList[]

== AntoraMeasureDetails

// tag::AntoraMeasureDetails[]

// end::AntoraMeasureDetails[]

== AntoraMeasureDescriptions



== AntoraParameterList

// tag::AntoraParameterList[]

// end::AntoraParameterList[]

== AntoraXrefCulturesList

// tag::AntoraXrefCulturesList[]
* xref:dhw:sqldb:ssis_t.packagedetails.adoc[] - 
// end::AntoraXrefCulturesList[]

== cultures_count

// tag::cultures_count[]
1
// end::cultures_count[]

== Other tags

source: property.RepoObjectProperty_cross As rop_cross


=== additional_reference_csv

// tag::additional_reference_csv[]

// end::additional_reference_csv[]


=== AdocUspSteps

// tag::adocuspsteps[]

// end::adocuspsteps[]


=== AntoraReferencedList

// tag::antorareferencedlist[]
* xref:dhw:sqldb:ssis_t.pkgstats.adoc[]
// end::antorareferencedlist[]


=== AntoraReferencingList

// tag::antorareferencinglist[]
* xref:dhw:sqldb:ssis_t.usp_getpackagedetails.adoc[]
// end::antorareferencinglist[]


=== Description

// tag::description[]

// end::description[]


=== exampleUsage

// tag::exampleusage[]

// end::exampleusage[]


=== exampleUsage_2

// tag::exampleusage_2[]

// end::exampleusage_2[]


=== exampleUsage_3

// tag::exampleusage_3[]

// end::exampleusage_3[]


=== exampleUsage_4

// tag::exampleusage_4[]

// end::exampleusage_4[]


=== exampleUsage_5

// tag::exampleusage_5[]

// end::exampleusage_5[]


=== exampleWrong_Usage

// tag::examplewrong_usage[]

// end::examplewrong_usage[]


=== has_execution_plan_issue

// tag::has_execution_plan_issue[]

// end::has_execution_plan_issue[]


=== has_get_referenced_issue

// tag::has_get_referenced_issue[]

// end::has_get_referenced_issue[]


=== has_history

// tag::has_history[]

// end::has_history[]


=== has_history_columns

// tag::has_history_columns[]

// end::has_history_columns[]


=== InheritanceType

// tag::inheritancetype[]

// end::inheritancetype[]


=== is_persistence

// tag::is_persistence[]

// end::is_persistence[]


=== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]

// end::is_persistence_check_duplicate_per_pk[]


=== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]

// end::is_persistence_check_for_empty_source[]


=== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]

// end::is_persistence_delete_changed[]


=== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]

// end::is_persistence_delete_missing[]


=== is_persistence_insert

// tag::is_persistence_insert[]

// end::is_persistence_insert[]


=== is_persistence_truncate

// tag::is_persistence_truncate[]

// end::is_persistence_truncate[]


=== is_persistence_update_changed

// tag::is_persistence_update_changed[]

// end::is_persistence_update_changed[]


=== is_repo_managed

// tag::is_repo_managed[]
0
// end::is_repo_managed[]


=== is_ssas

// tag::is_ssas[]
0
// end::is_ssas[]


=== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


=== MS_Description

// tag::ms_description[]

// end::ms_description[]


=== persistence_source_RepoObject_fullname

// tag::persistence_source_repoobject_fullname[]

// end::persistence_source_repoobject_fullname[]


=== persistence_source_RepoObject_fullname2

// tag::persistence_source_repoobject_fullname2[]

// end::persistence_source_repoobject_fullname2[]


=== persistence_source_RepoObject_guid

// tag::persistence_source_repoobject_guid[]

// end::persistence_source_repoobject_guid[]


=== persistence_source_RepoObject_xref

// tag::persistence_source_repoobject_xref[]

// end::persistence_source_repoobject_xref[]


=== pk_index_guid

// tag::pk_index_guid[]

// end::pk_index_guid[]


=== pk_IndexPatternColumnDatatype

// tag::pk_indexpatterncolumndatatype[]

// end::pk_indexpatterncolumndatatype[]


=== pk_IndexPatternColumnName

// tag::pk_indexpatterncolumnname[]

// end::pk_indexpatterncolumnname[]


=== pk_IndexSemanticGroup

// tag::pk_indexsemanticgroup[]

// end::pk_indexsemanticgroup[]


=== ReferencedObjectList

// tag::referencedobjectlist[]
* [ssis_t].[pkgStats]
// end::referencedobjectlist[]


=== usp_persistence_RepoObject_guid

// tag::usp_persistence_repoobject_guid[]

// end::usp_persistence_repoobject_guid[]


=== UspExamples

// tag::uspexamples[]

// end::uspexamples[]


=== uspgenerator_usp_id

// tag::uspgenerator_usp_id[]

// end::uspgenerator_usp_id[]


=== UspParameters

// tag::uspparameters[]

// end::uspparameters[]

== Boolean Attributes

source: property.RepoObjectProperty WHERE property_int = 1

// tag::boolean_attributes[]


// end::boolean_attributes[]

== PlantUML diagrams

=== PlantUML Entity

// tag::puml_entity[]
[plantuml, entity-{docname}, svg, subs=macros]
....
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis_t.packagedetails.adoc[]" as ssis_t.PackageDetails << V >> {
  PackageCreationDate : (datetime)
  PackageCreatorComputerName : (nvarchar(500))
  PackageCreatorName : (nvarchar(500))
  PackageDescription : (nvarchar(max))
  PackageDTSID : (uniqueidentifier)
  PackageLastModifiedProductVersion : (nvarchar(500))
  PackageLocaleID : (int)
  PackageObjectName : (nvarchar(500))
  - PackagePath : (varchar(8000))
  PackageProtectionLevel : (nvarchar(500))
  PackageVersionGUID : (uniqueidentifier)
  - RowID : (int)
  --
}
....

// end::puml_entity[]

=== PlantUML Entity 1 1 FK

// tag::puml_entity_1_1_fk[]
[plantuml, entity_1_1_fk-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis_t.packagedetails.adoc[]" as ssis_t.PackageDetails << V >> {
- idx_PackageDetails__1

..
RowID; int
}



footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_fk[]

=== PlantUML 1 1 ObjectRef

// tag::puml_entity_1_1_objectref[]
[plantuml, entity_1_1_objectref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis_t.packagedetails.adoc[]" as ssis_t.PackageDetails << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.pkgstats.adoc[]" as ssis_t.pkgStats << U >> {
  - **RowID** : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.usp_getpackagedetails.adoc[]" as ssis_t.usp_GetPackageDetails << P >> {
  --
}

ssis_t.PackageDetails <.. ssis_t.usp_GetPackageDetails
ssis_t.pkgStats <.. ssis_t.PackageDetails

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_objectref[]

=== PlantUML 30 0 ObjectRef

// tag::puml_entity_30_0_objectref[]
[plantuml, entity_30_0_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis_t.packagedetails.adoc[]" as ssis_t.PackageDetails << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.pkgstats.adoc[]" as ssis_t.pkgStats << U >> {
  - **RowID** : (int)
  --
}

ssis_t.pkgStats <.. ssis_t.PackageDetails

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_30_0_objectref[]

=== PlantUML 0 30 ObjectRef

// tag::puml_entity_0_30_objectref[]
[plantuml, entity_0_30_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis_t.packagedetails.adoc[]" as ssis_t.PackageDetails << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.usp_getpackagedetails.adoc[]" as ssis_t.usp_GetPackageDetails << P >> {
  --
}

ssis_t.PackageDetails <.. ssis_t.usp_GetPackageDetails

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_0_30_objectref[]

=== PlantUML 1 1 ColumnRef

// tag::puml_entity_1_1_colref[]
[plantuml, entity_1_1_colref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis_t.packagedetails.adoc[]" as ssis_t.PackageDetails << V >> {
  PackageCreationDate : (datetime)
  PackageCreatorComputerName : (nvarchar(500))
  PackageCreatorName : (nvarchar(500))
  PackageDescription : (nvarchar(max))
  PackageDTSID : (uniqueidentifier)
  PackageLastModifiedProductVersion : (nvarchar(500))
  PackageLocaleID : (int)
  PackageObjectName : (nvarchar(500))
  - PackagePath : (varchar(8000))
  PackageProtectionLevel : (nvarchar(500))
  PackageVersionGUID : (uniqueidentifier)
  - RowID : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.pkgstats.adoc[]" as ssis_t.pkgStats << U >> {
  - **RowID** : (int)
  PackageCreationDate : (datetime)
  PackageCreatorComputerName : (nvarchar(500))
  PackageCreatorName : (varchar(1000))
  PackageDescription : (nvarchar(max))
  PackageDTSID : (uniqueidentifier)
  PackageLastModifiedProductVersion : (nvarchar(500))
  PackageLocaleID : (int)
  PackageObjectName : (nvarchar(500))
  - PackagePath : (varchar(8000))
  PackageProtectionLevel : (varchar(100))
  PackageVersionGUID : (uniqueidentifier)
  - PackageXML : (xml)
  - ProjectPath : (varchar(8000))
  # PackageName : (varchar(200))
  ~ PackageProtectionLevelName : (varchar(28))
  --
}

entity "puml-link:dhw:sqldb:ssis_t.usp_getpackagedetails.adoc[]" as ssis_t.usp_GetPackageDetails << P >> {
  --
}

ssis_t.PackageDetails <.. ssis_t.usp_GetPackageDetails
ssis_t.pkgStats <.. ssis_t.PackageDetails
"ssis_t.pkgStats::PackagePath" <-- "ssis_t.PackageDetails::PackagePath"
"ssis_t.pkgStats::PackageXML" <-- "ssis_t.PackageDetails::PackageCreationDate"
"ssis_t.pkgStats::PackageXML" <-- "ssis_t.PackageDetails::PackageCreatorComputerName"
"ssis_t.pkgStats::PackageXML" <-- "ssis_t.PackageDetails::PackageCreatorName"
"ssis_t.pkgStats::PackageXML" <-- "ssis_t.PackageDetails::PackageDescription"
"ssis_t.pkgStats::PackageXML" <-- "ssis_t.PackageDetails::PackageDTSID"
"ssis_t.pkgStats::PackageXML" <-- "ssis_t.PackageDetails::PackageLastModifiedProductVersion"
"ssis_t.pkgStats::PackageXML" <-- "ssis_t.PackageDetails::PackageLocaleID"
"ssis_t.pkgStats::PackageXML" <-- "ssis_t.PackageDetails::PackageObjectName"
"ssis_t.pkgStats::PackageXML" <-- "ssis_t.PackageDetails::PackageProtectionLevel"
"ssis_t.pkgStats::PackageXML" <-- "ssis_t.PackageDetails::PackageVersionGUID"
"ssis_t.pkgStats::RowID" <-- "ssis_t.PackageDetails::RowID"

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_colref[]


== sql_modules_definition

// tag::sql_modules_definition[]
[%collapsible]
=======
[source,sql,numbered,indent=0]
----

CREATE VIEW [ssis_t].[PackageDetails]
As
Select
    pkg.RowID
  , pkg.PackagePath
  , PackageObjectName                 = pkg.PackageXML.value (
                                                                 'declare namespace DTS="www.microsoft.com/SqlServer/Dts";
					/DTS:Executable[1]/@DTS:ObjectName'
                                                               , 'nvarchar(500)'
                                                             )
  , PackageCreationDate               = pkg.PackageXML.value (
                                                                 'declare namespace DTS="www.microsoft.com/SqlServer/Dts";
					/DTS:Executable[1]/@DTS:CreationDate'
                                                               , 'datetime'
                                                             )
  , PackageCreatorComputerName        = pkg.PackageXML.value (
                                                                 'declare namespace DTS="www.microsoft.com/SqlServer/Dts";
					/DTS:Executable[1]/@DTS:CreatorComputerName'
                                                               , 'nvarchar(500)'
                                                             )
  , PackageCreatorName                = pkg.PackageXML.value (
                                                                 'declare namespace DTS="www.microsoft.com/SqlServer/Dts";
					/DTS:Executable[1]/@DTS:CreatorName'
                                                               , 'nvarchar(500)'
                                                             )
  , PackageDescription                = pkg.PackageXML.value (
                                                                 'declare namespace DTS="www.microsoft.com/SqlServer/Dts";
					/DTS:Executable[1]/@DTS:Description'
                                                               , 'nvarchar(max)'
                                                             )
  , PackageDTSID                      = pkg.PackageXML.value (
                                                                 'declare namespace DTS="www.microsoft.com/SqlServer/Dts";
					/DTS:Executable[1]/@DTS:DTSID'
                                                               , 'uniqueidentifier'
                                                             )
  , PackageProtectionLevel            = pkg.PackageXML.value (
                                                                 'declare namespace DTS="www.microsoft.com/SqlServer/Dts";
					/DTS:Executable[1]/@DTS:ProtectionLevel'
                                                               , 'nvarchar(500)'
                                                             )
  , PackageVersionGUID                = pkg.PackageXML.value (
                                                                 'declare namespace DTS="www.microsoft.com/SqlServer/Dts";
					/DTS:Executable[1]/@DTS:VersionGUID'
                                                               , 'uniqueidentifier'
                                                             )
  , PackageLocaleID                   = pkg.PackageXML.value (
                                                                 'declare namespace DTS="www.microsoft.com/SqlServer/Dts";
					/DTS:Executable[1]/@DTS:LocaleID'
                                                               , 'int'
                                                             )
  , PackageLastModifiedProductVersion = pkg.PackageXML.value (
                                                                 'declare namespace DTS="www.microsoft.com/SqlServer/Dts";
					/DTS:Executable[1]/@DTS:LastModifiedProductVersion'
                                                               , 'nvarchar(500)'
                                                             )
From
    ssis_t.pkgStats As pkg
----
=======
// end::sql_modules_definition[]


