// tag::HeaderFullDisplayName[]
= ssis.ProjectConnection - U
// end::HeaderFullDisplayName[]

== existing_properties

// tag::existing_properties[]

:ExistsProperty--antorareferencedlist:
:ExistsProperty--antorareferencinglist:
:ExistsProperty--is_repo_managed:
:ExistsProperty--is_ssas:
:ExistsProperty--pk_index_guid:
:ExistsProperty--pk_indexpatterncolumndatatype:
:ExistsProperty--pk_indexpatterncolumnname:
:ExistsProperty--referencedobjectlist:
:ExistsProperty--FK:
:ExistsProperty--AntoraIndexList:
:ExistsProperty--Columns:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
809A07F7-C23C-EC11-852D-A81E8446D5B0
// end::RepoObject_guid[]

== RepoObject_FullDisplayName2

// tag::RepoObject_FullDisplayName2[]
ssis.ProjectConnection
// end::RepoObject_FullDisplayName2[]

== SysObject_type

// tag::SysObject_type[]
U 
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
user table
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
1922157943
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2022-09-05 18:18:08
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]
[discrete]
== _


[#column-antoramodule]
=== AntoraModule

[cols="d,8a,m,m,m"]
|===
|1
|*AntoraModule*
|varchar(50)
|NOT NULL
|
|===

.Referencing Columns
--
* xref:docs.ssis_projectconnectionlist.adoc#column-antoramodule[+docs.ssis_ProjectConnectionList.AntoraModule+]
* xref:ssis.projectconnection_tgt.adoc#column-antoramodule[+ssis.ProjectConnection_tgt.AntoraModule+]
--


[#column-connectionmanagerid]
=== ConnectionManagerID

[cols="d,8a,m,m,m"]
|===
|2
|*ConnectionManagerID*
|uniqueidentifier
|NOT NULL
|
|===

.Referencing Columns
--
* xref:ssis.projectconnection_tgt.adoc#column-connectionmanagerid[+ssis.ProjectConnection_tgt.ConnectionManagerID+]
--


[#column-connectionmanagername]
=== ConnectionManagerName

[cols="d,8a,m,m,m"]
|===
|
|ConnectionManagerName
|varchar(max)
|NOT NULL
|
|===

.Referencing Columns
--
* xref:ssis.projectconnection_tgt.adoc#column-connectionmanagername[+ssis.ProjectConnection_tgt.ConnectionManagerName+]
--


[#column-connectionmanagertype]
=== ConnectionManagerType

[cols="d,8a,m,m,m"]
|===
|
|ConnectionManagerType
|varchar(max)
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.projectconnection_tgt.adoc#column-connectionmanagertype[+ssis.ProjectConnection_tgt.ConnectionManagerType+]
--


[#column-connectionpath]
=== ConnectionPath

[cols="d,8a,m,m,m"]
|===
|
|ConnectionPath
|varchar(8000)
|NOT NULL
|
|===

.Referencing Columns
--
* xref:ssis.projectconnection_tgt.adoc#column-connectionpath[+ssis.ProjectConnection_tgt.ConnectionPath+]
--


[#column-connectionstring]
=== ConnectionString

[cols="d,8a,m,m,m"]
|===
|
|ConnectionString
|nvarchar(max)
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.projectconnection_tgt.adoc#column-connectionstring[+ssis.ProjectConnection_tgt.ConnectionString+]
--


[#column-expressionvalue]
=== ExpressionValue

[cols="d,8a,m,m,m"]
|===
|
|ExpressionValue
|nvarchar(max)
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.projectconnection_tgt.adoc#column-expressionvalue[+ssis.ProjectConnection_tgt.ExpressionValue+]
--


// end::AntoraColumnDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]
|1
|*<<column-antoramodule>>*
|varchar(50)
|NOT NULL
|

|2
|*<<column-connectionmanagerid>>*
|uniqueidentifier
|NOT NULL
|






// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]


|
|<<column-connectionmanagername>>
|varchar(max)
|NOT NULL
|

|
|<<column-connectionmanagertype>>
|varchar(max)
|NULL
|

|
|<<column-connectionpath>>
|varchar(8000)
|NOT NULL
|

|
|<<column-connectionstring>>
|nvarchar(max)
|NULL
|

|
|<<column-expressionvalue>>
|nvarchar(max)
|NULL
|

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

[#index-pkunderlineprojectconnectionunderline1]
=== PK_ProjectConnection_1

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-AntoraModule>>; varchar(50)
* <<column-ConnectionManagerID>>; uniqueidentifier
--
* PK, Unique, Real: 1, 1, 1

// end::AntoraIndexList[]

== AntoraMeasureDetails

// tag::AntoraMeasureDetails[]

// end::AntoraMeasureDetails[]

== AntoraMeasureDescriptions



== AntoraParameterList

// tag::AntoraParameterList[]

// end::AntoraParameterList[]

== AntoraXrefCulturesList

// tag::AntoraXrefCulturesList[]
* xref:dhw:sqldb:ssis.projectconnection.adoc[] - 
// end::AntoraXrefCulturesList[]

== cultures_count

// tag::cultures_count[]
1
// end::cultures_count[]

== Other tags

source: property.RepoObjectProperty_cross As rop_cross


=== additional_reference_csv

// tag::additional_reference_csv[]

// end::additional_reference_csv[]


=== AdocUspSteps

// tag::adocuspsteps[]

// end::adocuspsteps[]


=== AntoraReferencedList

// tag::antorareferencedlist[]
* xref:dhw:sqldb:ssis.projectconnection_tgt.adoc[]
// end::antorareferencedlist[]


=== AntoraReferencingList

// tag::antorareferencinglist[]
* xref:dhw:sqldb:docs.ssis_projectconnectionlist.adoc[]
* xref:dhw:sqldb:docs.ssis_task.adoc[]
* xref:dhw:sqldb:docs.ssis_tasklist.adoc[]
// end::antorareferencinglist[]


=== Description

// tag::description[]

// end::description[]


=== exampleUsage

// tag::exampleusage[]

// end::exampleusage[]


=== exampleUsage_2

// tag::exampleusage_2[]

// end::exampleusage_2[]


=== exampleUsage_3

// tag::exampleusage_3[]

// end::exampleusage_3[]


=== exampleUsage_4

// tag::exampleusage_4[]

// end::exampleusage_4[]


=== exampleUsage_5

// tag::exampleusage_5[]

// end::exampleusage_5[]


=== exampleWrong_Usage

// tag::examplewrong_usage[]

// end::examplewrong_usage[]


=== has_execution_plan_issue

// tag::has_execution_plan_issue[]

// end::has_execution_plan_issue[]


=== has_get_referenced_issue

// tag::has_get_referenced_issue[]

// end::has_get_referenced_issue[]


=== has_history

// tag::has_history[]

// end::has_history[]


=== has_history_columns

// tag::has_history_columns[]

// end::has_history_columns[]


=== InheritanceType

// tag::inheritancetype[]

// end::inheritancetype[]


=== is_persistence

// tag::is_persistence[]

// end::is_persistence[]


=== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]

// end::is_persistence_check_duplicate_per_pk[]


=== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]

// end::is_persistence_check_for_empty_source[]


=== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]

// end::is_persistence_delete_changed[]


=== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]

// end::is_persistence_delete_missing[]


=== is_persistence_insert

// tag::is_persistence_insert[]

// end::is_persistence_insert[]


=== is_persistence_truncate

// tag::is_persistence_truncate[]

// end::is_persistence_truncate[]


=== is_persistence_update_changed

// tag::is_persistence_update_changed[]

// end::is_persistence_update_changed[]


=== is_repo_managed

// tag::is_repo_managed[]
0
// end::is_repo_managed[]


=== is_ssas

// tag::is_ssas[]
0
// end::is_ssas[]


=== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


=== MS_Description

// tag::ms_description[]

// end::ms_description[]


=== persistence_source_RepoObject_fullname

// tag::persistence_source_repoobject_fullname[]

// end::persistence_source_repoobject_fullname[]


=== persistence_source_RepoObject_fullname2

// tag::persistence_source_repoobject_fullname2[]

// end::persistence_source_repoobject_fullname2[]


=== persistence_source_RepoObject_guid

// tag::persistence_source_repoobject_guid[]

// end::persistence_source_repoobject_guid[]


=== persistence_source_RepoObject_xref

// tag::persistence_source_repoobject_xref[]

// end::persistence_source_repoobject_xref[]


=== pk_index_guid

// tag::pk_index_guid[]
9B2381CD-C33C-EC11-852D-A81E8446D5B0
// end::pk_index_guid[]


=== pk_IndexPatternColumnDatatype

// tag::pk_indexpatterncolumndatatype[]
varchar(50),uniqueidentifier
// end::pk_indexpatterncolumndatatype[]


=== pk_IndexPatternColumnName

// tag::pk_indexpatterncolumnname[]
AntoraModule,ConnectionManagerID
// end::pk_indexpatterncolumnname[]


=== pk_IndexSemanticGroup

// tag::pk_indexsemanticgroup[]

// end::pk_indexsemanticgroup[]


=== ReferencedObjectList

// tag::referencedobjectlist[]
* [ssis].[ProjectConnection_tgt]
// end::referencedobjectlist[]


=== usp_persistence_RepoObject_guid

// tag::usp_persistence_repoobject_guid[]

// end::usp_persistence_repoobject_guid[]


=== UspExamples

// tag::uspexamples[]

// end::uspexamples[]


=== uspgenerator_usp_id

// tag::uspgenerator_usp_id[]

// end::uspgenerator_usp_id[]


=== UspParameters

// tag::uspparameters[]

// end::uspparameters[]

== Boolean Attributes

source: property.RepoObjectProperty WHERE property_int = 1

// tag::boolean_attributes[]


// end::boolean_attributes[]

== PlantUML diagrams

=== PlantUML Entity

// tag::puml_entity[]
[plantuml, entity-{docname}, svg, subs=macros]
....
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis.projectconnection.adoc[]" as ssis.ProjectConnection << U >> {
  - **AntoraModule** : (varchar(50))
  - **ConnectionManagerID** : (uniqueidentifier)
  - ConnectionManagerName : (varchar(max))
  ConnectionManagerType : (varchar(max))
  - ConnectionPath : (varchar(8000))
  ConnectionString : (nvarchar(max))
  ExpressionValue : (nvarchar(max))
  --
}
....

// end::puml_entity[]

=== PlantUML Entity 1 1 FK

// tag::puml_entity_1_1_fk[]
[plantuml, entity_1_1_fk-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis.projectconnection.adoc[]" as ssis.ProjectConnection << U >> {
**PK_ProjectConnection_1**

..
AntoraModule; varchar(50)
ConnectionManagerID; uniqueidentifier
}



footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_fk[]

=== PlantUML 1 1 ObjectRef

// tag::puml_entity_1_1_objectref[]
[plantuml, entity_1_1_objectref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:docs.ssis_projectconnectionlist.adoc[]" as docs.ssis_ProjectConnectionList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_task.adoc[]" as docs.ssis_Task << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_tasklist.adoc[]" as docs.ssis_TaskList << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.projectconnection.adoc[]" as ssis.ProjectConnection << U >> {
  - **AntoraModule** : (varchar(50))
  - **ConnectionManagerID** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:ssis.projectconnection_tgt.adoc[]" as ssis.ProjectConnection_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  - **ConnectionManagerID** : (uniqueidentifier)
  --
}

ssis.ProjectConnection <.. docs.ssis_ProjectConnectionList
ssis.ProjectConnection <.. docs.ssis_Task
ssis.ProjectConnection <.. docs.ssis_TaskList
ssis.ProjectConnection_tgt <.. ssis.ProjectConnection

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_objectref[]

=== PlantUML 30 0 ObjectRef

// tag::puml_entity_30_0_objectref[]
[plantuml, entity_30_0_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis.antoramodule_tgt_filter.adoc[]" as ssis.AntoraModule_tgt_filter << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.package_src.adoc[]" as ssis.Package_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  --
}

entity "puml-link:dhw:sqldb:ssis.project.adoc[]" as ssis.Project << U >> {
  - **AntoraModule** : (varchar(50))
  --
}

entity "puml-link:dhw:sqldb:ssis.projectconnection.adoc[]" as ssis.ProjectConnection << U >> {
  - **AntoraModule** : (varchar(50))
  - **ConnectionManagerID** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:ssis.projectconnection_src.adoc[]" as ssis.ProjectConnection_src << V >> {
  - **AntoraModule** : (varchar(50))
  **ConnectionManagerID** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:ssis.projectconnection_tgt.adoc[]" as ssis.ProjectConnection_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  - **ConnectionManagerID** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.pkgstats.adoc[]" as ssis_t.pkgStats << U >> {
  - **RowID** : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.projectconnection.adoc[]" as ssis_t.ProjectConnection << U >> {
  - **RowID** : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tblprojectconnection.adoc[]" as ssis_t.TblProjectConnection << U >> {
  --
}

ssis.AntoraModule_tgt_filter <.. ssis.ProjectConnection_tgt
ssis.Package_src <.. ssis.AntoraModule_tgt_filter
ssis.Project <.. ssis.Package_src
ssis.Project <.. ssis.ProjectConnection_src
ssis.ProjectConnection_src <.. ssis.ProjectConnection_tgt
ssis.ProjectConnection_tgt <.. ssis.ProjectConnection
ssis_t.pkgStats <.. ssis.Package_src
ssis_t.ProjectConnection <.. ssis.ProjectConnection_src
ssis_t.TblProjectConnection <.. ssis.ProjectConnection_src

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_30_0_objectref[]

=== PlantUML 0 30 ObjectRef

// tag::puml_entity_0_30_objectref[]
[plantuml, entity_0_30_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:docs.ssis_adoc.adoc[]" as docs.ssis_Adoc << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageBasename** : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_adoc_t.adoc[]" as docs.ssis_Adoc_T << U >> {
  - **AntoraModule** : (varchar(50))
  - **PackageBasename** : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_projectconnectionlist.adoc[]" as docs.ssis_ProjectConnectionList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_task.adoc[]" as docs.ssis_Task << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_tasklist.adoc[]" as docs.ssis_TaskList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport.adoc[]" as docs.usp_AntoraExport << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_ssispartialscontent.adoc[]" as docs.usp_AntoraExport_SsisPartialsContent << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_ssis_adoc_t.adoc[]" as docs.usp_PERSIST_ssis_Adoc_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.projectconnection.adoc[]" as ssis.ProjectConnection << U >> {
  - **AntoraModule** : (varchar(50))
  - **ConnectionManagerID** : (uniqueidentifier)
  --
}

docs.ssis_Adoc <.. docs.ssis_Adoc_T
docs.ssis_Adoc <.. docs.usp_PERSIST_ssis_Adoc_T
docs.ssis_Adoc_T <.. docs.usp_AntoraExport_SsisPartialsContent
docs.ssis_Adoc_T <.. docs.usp_PERSIST_ssis_Adoc_T
docs.ssis_ProjectConnectionList <.. docs.ssis_Adoc
docs.ssis_TaskList <.. docs.ssis_Adoc
docs.usp_AntoraExport_SsisPartialsContent <.. docs.usp_AntoraExport
docs.usp_PERSIST_ssis_Adoc_T <.. docs.usp_AntoraExport_SsisPartialsContent
ssis.ProjectConnection <.. docs.ssis_ProjectConnectionList
ssis.ProjectConnection <.. docs.ssis_Task
ssis.ProjectConnection <.. docs.ssis_TaskList

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_0_30_objectref[]

=== PlantUML 1 1 ColumnRef

// tag::puml_entity_1_1_colref[]
[plantuml, entity_1_1_colref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:docs.ssis_projectconnectionlist.adoc[]" as docs.ssis_ProjectConnectionList << V >> {
  - AntoraModule : (varchar(50))
  ProjectConnectionList : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_task.adoc[]" as docs.ssis_Task << V >> {
  AdocFilename : (nvarchar(4000))
  - AntoraModule : (varchar(50))
  - PackageName : (varchar(200))
  - TaskContent : (nvarchar(max))
  - TaskPath : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_tasklist.adoc[]" as docs.ssis_TaskList << V >> {
  - AntoraModule : (varchar(50))
  - PackageName : (varchar(200))
  TaskList : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.projectconnection.adoc[]" as ssis.ProjectConnection << U >> {
  - **AntoraModule** : (varchar(50))
  - **ConnectionManagerID** : (uniqueidentifier)
  - ConnectionManagerName : (varchar(max))
  ConnectionManagerType : (varchar(max))
  - ConnectionPath : (varchar(8000))
  ConnectionString : (nvarchar(max))
  ExpressionValue : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.projectconnection_tgt.adoc[]" as ssis.ProjectConnection_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  - **ConnectionManagerID** : (uniqueidentifier)
  - ConnectionManagerName : (varchar(max))
  ConnectionManagerType : (varchar(max))
  - ConnectionPath : (varchar(8000))
  ConnectionString : (nvarchar(max))
  ExpressionValue : (nvarchar(max))
  --
}

ssis.ProjectConnection <.. docs.ssis_ProjectConnectionList
ssis.ProjectConnection <.. docs.ssis_Task
ssis.ProjectConnection <.. docs.ssis_TaskList
ssis.ProjectConnection_tgt <.. ssis.ProjectConnection
"ssis.ProjectConnection::AntoraModule" <-- "docs.ssis_ProjectConnectionList::AntoraModule"
"ssis.ProjectConnection::AntoraModule" <-- "ssis.ProjectConnection_tgt::AntoraModule"
"ssis.ProjectConnection::ConnectionManagerID" <-- "ssis.ProjectConnection_tgt::ConnectionManagerID"
"ssis.ProjectConnection::ConnectionManagerName" <-- "ssis.ProjectConnection_tgt::ConnectionManagerName"
"ssis.ProjectConnection::ConnectionManagerType" <-- "ssis.ProjectConnection_tgt::ConnectionManagerType"
"ssis.ProjectConnection::ConnectionPath" <-- "ssis.ProjectConnection_tgt::ConnectionPath"
"ssis.ProjectConnection::ConnectionString" <-- "ssis.ProjectConnection_tgt::ConnectionString"
"ssis.ProjectConnection::ExpressionValue" <-- "ssis.ProjectConnection_tgt::ExpressionValue"

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_colref[]


== sql_modules_definition

// tag::sql_modules_definition[]
[%collapsible]
=======
[source,sql,numbered,indent=0]
----

----
=======
// end::sql_modules_definition[]


