// tag::HeaderFullDisplayName[]
= ssis.PackageTask_Dft_Component_output_outputcolumn_src - V
// end::HeaderFullDisplayName[]

== existing_properties

// tag::existing_properties[]

:ExistsProperty--antorareferencedlist:
:ExistsProperty--antorareferencinglist:
:ExistsProperty--is_repo_managed:
:ExistsProperty--is_ssas:
:ExistsProperty--pk_index_guid:
:ExistsProperty--pk_indexpatterncolumndatatype:
:ExistsProperty--pk_indexpatterncolumnname:
:ExistsProperty--referencedobjectlist:
:ExistsProperty--sql_modules_definition:
:ExistsProperty--FK:
:ExistsProperty--AntoraIndexList:
:ExistsProperty--Columns:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
78CC7FC6-CF3F-EC11-852D-A81E8446D5B0
// end::RepoObject_guid[]

== RepoObject_FullDisplayName2

// tag::RepoObject_FullDisplayName2[]
ssis.PackageTask_Dft_Component_output_outputcolumn_src
// end::RepoObject_FullDisplayName2[]

== SysObject_type

// tag::SysObject_type[]
V 
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
view
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
606677259
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2021-11-07 14:28:41
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]
[discrete]
== _


[#column-antoramodule]
=== AntoraModule

[cols="d,8a,m,m,m"]
|===
|1
|*AntoraModule*
|varchar(50)
|NOT NULL
|
|===

.Referenced Columns
--
* xref:ssis.package_src.adoc#column-antoramodule[+ssis.Package_src.AntoraModule+]
--

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_output_outputcolumn_tgt.adoc#column-antoramodule[+ssis.PackageTask_Dft_Component_output_outputcolumn_tgt.AntoraModule+]
--


[#column-packagename]
=== PackageName

[cols="d,8a,m,m,m"]
|===
|2
|*PackageName*
|varchar(200)
|NULL
|
|===

.Description
--
(left(replace([PackagePath],[ProjectPath]+'\',''),(200)))
--
{empty} +

.Referenced Columns
--
* xref:ssis.package_src.adoc#column-packagename[+ssis.Package_src.PackageName+]
--

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_output_outputcolumn_tgt.adoc#column-packagename[+ssis.PackageTask_Dft_Component_output_outputcolumn_tgt.PackageName+]
--


[#column-columnunderlinerefid]
=== Column_refId

[cols="d,8a,m,m,m"]
|===
|3
|*Column_refId*
|varchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis_t.tbltask_dft_component_outputs_outputcolumn_src.adoc#column-columnunderlinerefid[+ssis_t.TblTask_Dft_Component_outputs_outputColumn_src.Column_refId+]
--

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_output_outputcolumn_tgt.adoc#column-columnunderlinerefid[+ssis.PackageTask_Dft_Component_output_outputcolumn_tgt.Column_refId+]
--


[#column-columnunderlinedatatype]
=== Column_dataType

[cols="d,8a,m,m,m"]
|===
|
|Column_dataType
|varchar(100)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis_t.tbltask_dft_component_outputs_outputcolumn_src.adoc#column-columnunderlinedatatype[+ssis_t.TblTask_Dft_Component_outputs_outputColumn_src.Column_dataType+]
--

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_output_outputcolumn_tgt.adoc#column-columnunderlinedatatype[+ssis.PackageTask_Dft_Component_output_outputcolumn_tgt.Column_dataType+]
--


[#column-columnunderlineerrorortruncationoperation]
=== Column_errorOrTruncationOperation

[cols="d,8a,m,m,m"]
|===
|
|Column_errorOrTruncationOperation
|varchar(100)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis_t.tbltask_dft_component_outputs_outputcolumn_src.adoc#column-columnunderlineerrorortruncationoperation[+ssis_t.TblTask_Dft_Component_outputs_outputColumn_src.Column_errorOrTruncationOperation+]
--

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_output_outputcolumn_tgt.adoc#column-columnunderlineerrorortruncationoperation[+ssis.PackageTask_Dft_Component_output_outputcolumn_tgt.Column_errorOrTruncationOperation+]
--


[#column-columnunderlineerrorrowdisposition]
=== Column_errorRowDisposition

[cols="d,8a,m,m,m"]
|===
|
|Column_errorRowDisposition
|varchar(100)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis_t.tbltask_dft_component_outputs_outputcolumn_src.adoc#column-columnunderlineerrorrowdisposition[+ssis_t.TblTask_Dft_Component_outputs_outputColumn_src.Column_errorRowDisposition+]
--

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_output_outputcolumn_tgt.adoc#column-columnunderlineerrorrowdisposition[+ssis.PackageTask_Dft_Component_output_outputcolumn_tgt.Column_errorRowDisposition+]
--


[#column-columnunderlineexternalmetadatacolumnid]
=== Column_externalMetadataColumnId

[cols="d,8a,m,m,m"]
|===
|
|Column_externalMetadataColumnId
|varchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis_t.tbltask_dft_component_outputs_outputcolumn_src.adoc#column-columnunderlineexternalmetadatacolumnid[+ssis_t.TblTask_Dft_Component_outputs_outputColumn_src.Column_externalMetadataColumnId+]
--

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_output_outputcolumn_tgt.adoc#column-columnunderlineexternalmetadatacolumnid[+ssis.PackageTask_Dft_Component_output_outputcolumn_tgt.Column_externalMetadataColumnId+]
--


[#column-columnunderlinelength]
=== Column_length

[cols="d,8a,m,m,m"]
|===
|
|Column_length
|int
|NULL
|
|===

.Referenced Columns
--
* xref:ssis_t.tbltask_dft_component_outputs_outputcolumn_src.adoc#column-columnunderlinelength[+ssis_t.TblTask_Dft_Component_outputs_outputColumn_src.Column_length+]
--

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_output_outputcolumn_tgt.adoc#column-columnunderlinelength[+ssis.PackageTask_Dft_Component_output_outputcolumn_tgt.Column_length+]
--


[#column-columnunderlinelineageid]
=== Column_lineageId

[cols="d,8a,m,m,m"]
|===
|
|Column_lineageId
|varchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis_t.tbltask_dft_component_outputs_outputcolumn_src.adoc#column-columnunderlinelineageid[+ssis_t.TblTask_Dft_Component_outputs_outputColumn_src.Column_lineageId+]
--

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_output_outputcolumn_tgt.adoc#column-columnunderlinelineageid[+ssis.PackageTask_Dft_Component_output_outputcolumn_tgt.Column_lineageId+]
--


[#column-columnunderlinename]
=== Column_name

[cols="d,8a,m,m,m"]
|===
|
|Column_name
|varchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis_t.tbltask_dft_component_outputs_outputcolumn_src.adoc#column-columnunderlinename[+ssis_t.TblTask_Dft_Component_outputs_outputColumn_src.Column_name+]
--

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_output_outputcolumn_tgt.adoc#column-columnunderlinename[+ssis.PackageTask_Dft_Component_output_outputcolumn_tgt.Column_name+]
--


[#column-columnunderlineprecision]
=== Column_precision

[cols="d,8a,m,m,m"]
|===
|
|Column_precision
|int
|NULL
|
|===

.Referenced Columns
--
* xref:ssis_t.tbltask_dft_component_outputs_outputcolumn_src.adoc#column-columnunderlineprecision[+ssis_t.TblTask_Dft_Component_outputs_outputColumn_src.Column_precision+]
--

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_output_outputcolumn_tgt.adoc#column-columnunderlineprecision[+ssis.PackageTask_Dft_Component_output_outputcolumn_tgt.Column_precision+]
--


[#column-columnunderlinescale]
=== Column_scale

[cols="d,8a,m,m,m"]
|===
|
|Column_scale
|int
|NULL
|
|===

.Referenced Columns
--
* xref:ssis_t.tbltask_dft_component_outputs_outputcolumn_src.adoc#column-columnunderlinescale[+ssis_t.TblTask_Dft_Component_outputs_outputColumn_src.Column_scale+]
--

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_output_outputcolumn_tgt.adoc#column-columnunderlinescale[+ssis.PackageTask_Dft_Component_output_outputcolumn_tgt.Column_scale+]
--


[#column-columnunderlinetruncationrowdisposition]
=== Column_truncationRowDisposition

[cols="d,8a,m,m,m"]
|===
|
|Column_truncationRowDisposition
|varchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis_t.tbltask_dft_component_outputs_outputcolumn_src.adoc#column-columnunderlinetruncationrowdisposition[+ssis_t.TblTask_Dft_Component_outputs_outputColumn_src.Column_truncationRowDisposition+]
--

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_output_outputcolumn_tgt.adoc#column-columnunderlinetruncationrowdisposition[+ssis.PackageTask_Dft_Component_output_outputcolumn_tgt.Column_truncationRowDisposition+]
--


[#column-componentunderlinerefid]
=== Component_refId

[cols="d,8a,m,m,m"]
|===
|
|Component_refId
|varchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis_t.tbltask_dft_component_outputs_outputcolumn_src.adoc#column-refid[+ssis_t.TblTask_Dft_Component_outputs_outputColumn_src.refId+]
--

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_output_outputcolumn_tgt.adoc#column-componentunderlinerefid[+ssis.PackageTask_Dft_Component_output_outputcolumn_tgt.Component_refId+]
--


[#column-controlflowdetailsrowid]
=== ControlFlowDetailsRowID

[cols="d,8a,m,m,m"]
|===
|
|ControlFlowDetailsRowID
|int
|NOT NULL
|
|===

.Referenced Columns
--
* xref:ssis_t.tbltask_dft_component_outputs_outputcolumn_src.adoc#column-controlflowdetailsrowid[+ssis_t.TblTask_Dft_Component_outputs_outputColumn_src.ControlFlowDetailsRowID+]
--

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_output_outputcolumn_tgt.adoc#column-controlflowdetailsrowid[+ssis.PackageTask_Dft_Component_output_outputcolumn_tgt.ControlFlowDetailsRowID+]
--


[#column-outputunderlineiserrorout]
=== output_isErrorOut

[cols="d,8a,m,m,m"]
|===
|
|output_isErrorOut
|bit
|NULL
|
|===

.Referenced Columns
--
* xref:ssis_t.tbltask_dft_component_outputs_outputcolumn_src.adoc#column-outputunderlineiserrorout[+ssis_t.TblTask_Dft_Component_outputs_outputColumn_src.output_isErrorOut+]
--

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_output_outputcolumn_tgt.adoc#column-outputunderlineiserrorout[+ssis.PackageTask_Dft_Component_output_outputcolumn_tgt.output_isErrorOut+]
--


[#column-outputunderlinename]
=== output_name

[cols="d,8a,m,m,m"]
|===
|
|output_name
|varchar(500)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis_t.tbltask_dft_component_outputs_outputcolumn_src.adoc#column-outputunderlinename[+ssis_t.TblTask_Dft_Component_outputs_outputColumn_src.output_name+]
--

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_output_outputcolumn_tgt.adoc#column-outputunderlinename[+ssis.PackageTask_Dft_Component_output_outputcolumn_tgt.output_name+]
--


[#column-outputunderlinerefid]
=== output_refId

[cols="d,8a,m,m,m"]
|===
|
|output_refId
|varchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis_t.tbltask_dft_component_outputs_outputcolumn_src.adoc#column-outputunderlinerefid[+ssis_t.TblTask_Dft_Component_outputs_outputColumn_src.output_refId+]
--

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_output_outputcolumn_tgt.adoc#column-outputunderlinerefid[+ssis.PackageTask_Dft_Component_output_outputcolumn_tgt.output_refId+]
--


[#column-taskpath]
=== TaskPath

[cols="d,8a,m,m,m"]
|===
|
|TaskPath
|varchar(8000)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis_t.tblcontrolflow.adoc#column-taskpath[+ssis_t.TblControlFlow.TaskPath+]
--

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_output_outputcolumn_tgt.adoc#column-taskpath[+ssis.PackageTask_Dft_Component_output_outputcolumn_tgt.TaskPath+]
--


// end::AntoraColumnDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]
|1
|*<<column-antoramodule>>*
|varchar(50)
|NOT NULL
|

|2
|*<<column-packagename>>*
|varchar(200)
|NULL
|

|3
|*<<column-columnunderlinerefid>>*
|varchar(max)
|NULL
|

















// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]



|
|<<column-columnunderlinedatatype>>
|varchar(100)
|NULL
|

|
|<<column-columnunderlineerrorortruncationoperation>>
|varchar(100)
|NULL
|

|
|<<column-columnunderlineerrorrowdisposition>>
|varchar(100)
|NULL
|

|
|<<column-columnunderlineexternalmetadatacolumnid>>
|varchar(max)
|NULL
|

|
|<<column-columnunderlinelength>>
|int
|NULL
|

|
|<<column-columnunderlinelineageid>>
|varchar(max)
|NULL
|

|
|<<column-columnunderlinename>>
|varchar(max)
|NULL
|

|
|<<column-columnunderlineprecision>>
|int
|NULL
|

|
|<<column-columnunderlinescale>>
|int
|NULL
|

|
|<<column-columnunderlinetruncationrowdisposition>>
|varchar(max)
|NULL
|

|
|<<column-componentunderlinerefid>>
|varchar(max)
|NULL
|

|
|<<column-controlflowdetailsrowid>>
|int
|NOT NULL
|

|
|<<column-outputunderlineiserrorout>>
|bit
|NULL
|

|
|<<column-outputunderlinename>>
|varchar(500)
|NULL
|

|
|<<column-outputunderlinerefid>>
|varchar(max)
|NULL
|

|
|<<column-taskpath>>
|varchar(8000)
|NULL
|

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

[#index-pkunderlinepackagetaskunderlinedftunderlinecomponentunderlineoutputunderlineoutputcolumnunderlinesrc]
=== PK_PackageTask_Dft_Component_output_outputcolumn_src

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-AntoraModule>>; varchar(50)
* <<column-PackageName>>; varchar(200)
* <<column-Column_refId>>; varchar(max)
--
* PK, Unique, Real: 1, 1, 0


[#index-idxunderlinepackagetaskunderlinedftunderlinecomponentunderlineoutputunderlineoutputcolumnunderlinesrcunderlineunderline2]
=== idx_PackageTask_Dft_Component_output_outputcolumn_src++__++2

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-AntoraModule>>; varchar(50)
* <<column-PackageName>>; varchar(200)
--
* PK, Unique, Real: 0, 0, 0


[#index-idxunderlinepackagetaskunderlinedftunderlinecomponentunderlineoutputunderlineoutputcolumnunderlinesrcunderlineunderline3]
=== idx_PackageTask_Dft_Component_output_outputcolumn_src++__++3

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-AntoraModule>>; varchar(50)
--
* PK, Unique, Real: 0, 0, 0

// end::AntoraIndexList[]

== AntoraMeasureDetails

// tag::AntoraMeasureDetails[]

// end::AntoraMeasureDetails[]

== AntoraMeasureDescriptions



== AntoraParameterList

// tag::AntoraParameterList[]

// end::AntoraParameterList[]

== AntoraXrefCulturesList

// tag::AntoraXrefCulturesList[]
* xref:dhw:sqldb:ssis.packagetask_dft_component_output_outputcolumn_src.adoc[] - 
// end::AntoraXrefCulturesList[]

== cultures_count

// tag::cultures_count[]
1
// end::cultures_count[]

== Other tags

source: property.RepoObjectProperty_cross As rop_cross


=== additional_reference_csv

// tag::additional_reference_csv[]

// end::additional_reference_csv[]


=== AdocUspSteps

// tag::adocuspsteps[]

// end::adocuspsteps[]


=== AntoraReferencedList

// tag::antorareferencedlist[]
* xref:dhw:sqldb:ssis.package_src.adoc[]
* xref:dhw:sqldb:ssis_t.tblcontrolflow.adoc[]
* xref:dhw:sqldb:ssis_t.tbltask_dft_component_outputs_outputcolumn_src.adoc[]
// end::antorareferencedlist[]


=== AntoraReferencingList

// tag::antorareferencinglist[]
* xref:dhw:sqldb:ssis.packagetask_dft_component_output_outputcolumn_tgt.adoc[]
* xref:dhw:sqldb:ssis.usp_persist_packagetask_dft_component_output_outputcolumn_tgt.adoc[]
// end::antorareferencinglist[]


=== Description

// tag::description[]

// end::description[]


=== exampleUsage

// tag::exampleusage[]

// end::exampleusage[]


=== exampleUsage_2

// tag::exampleusage_2[]

// end::exampleusage_2[]


=== exampleUsage_3

// tag::exampleusage_3[]

// end::exampleusage_3[]


=== exampleUsage_4

// tag::exampleusage_4[]

// end::exampleusage_4[]


=== exampleUsage_5

// tag::exampleusage_5[]

// end::exampleusage_5[]


=== exampleWrong_Usage

// tag::examplewrong_usage[]

// end::examplewrong_usage[]


=== has_execution_plan_issue

// tag::has_execution_plan_issue[]

// end::has_execution_plan_issue[]


=== has_get_referenced_issue

// tag::has_get_referenced_issue[]

// end::has_get_referenced_issue[]


=== has_history

// tag::has_history[]

// end::has_history[]


=== has_history_columns

// tag::has_history_columns[]

// end::has_history_columns[]


=== InheritanceType

// tag::inheritancetype[]

// end::inheritancetype[]


=== is_persistence

// tag::is_persistence[]

// end::is_persistence[]


=== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]

// end::is_persistence_check_duplicate_per_pk[]


=== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]

// end::is_persistence_check_for_empty_source[]


=== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]

// end::is_persistence_delete_changed[]


=== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]

// end::is_persistence_delete_missing[]


=== is_persistence_insert

// tag::is_persistence_insert[]

// end::is_persistence_insert[]


=== is_persistence_truncate

// tag::is_persistence_truncate[]

// end::is_persistence_truncate[]


=== is_persistence_update_changed

// tag::is_persistence_update_changed[]

// end::is_persistence_update_changed[]


=== is_repo_managed

// tag::is_repo_managed[]
0
// end::is_repo_managed[]


=== is_ssas

// tag::is_ssas[]
0
// end::is_ssas[]


=== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


=== MS_Description

// tag::ms_description[]

// end::ms_description[]


=== persistence_source_RepoObject_fullname

// tag::persistence_source_repoobject_fullname[]

// end::persistence_source_repoobject_fullname[]


=== persistence_source_RepoObject_fullname2

// tag::persistence_source_repoobject_fullname2[]

// end::persistence_source_repoobject_fullname2[]


=== persistence_source_RepoObject_guid

// tag::persistence_source_repoobject_guid[]

// end::persistence_source_repoobject_guid[]


=== persistence_source_RepoObject_xref

// tag::persistence_source_repoobject_xref[]

// end::persistence_source_repoobject_xref[]


=== pk_index_guid

// tag::pk_index_guid[]
EBC1C789-D13F-EC11-852D-A81E8446D5B0
// end::pk_index_guid[]


=== pk_IndexPatternColumnDatatype

// tag::pk_indexpatterncolumndatatype[]
varchar(50),varchar(200),varchar(max)
// end::pk_indexpatterncolumndatatype[]


=== pk_IndexPatternColumnName

// tag::pk_indexpatterncolumnname[]
AntoraModule,PackageName,Column_refId
// end::pk_indexpatterncolumnname[]


=== pk_IndexSemanticGroup

// tag::pk_indexsemanticgroup[]

// end::pk_indexsemanticgroup[]


=== ReferencedObjectList

// tag::referencedobjectlist[]
* [ssis].[Package_src]
* [ssis_t].[TblControlFlow]
* [ssis_t].[TblTask_Dft_Component_outputs_outputColumn_src]
// end::referencedobjectlist[]


=== usp_persistence_RepoObject_guid

// tag::usp_persistence_repoobject_guid[]

// end::usp_persistence_repoobject_guid[]


=== UspExamples

// tag::uspexamples[]

// end::uspexamples[]


=== uspgenerator_usp_id

// tag::uspgenerator_usp_id[]

// end::uspgenerator_usp_id[]


=== UspParameters

// tag::uspparameters[]

// end::uspparameters[]

== Boolean Attributes

source: property.RepoObjectProperty WHERE property_int = 1

// tag::boolean_attributes[]


// end::boolean_attributes[]

== PlantUML diagrams

=== PlantUML Entity

// tag::puml_entity[]
[plantuml, entity-{docname}, svg, subs=macros]
....
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_output_outputcolumn_src.adoc[]" as ssis.PackageTask_Dft_Component_output_outputcolumn_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Column_refId** : (varchar(max))
  Column_dataType : (varchar(100))
  Column_errorOrTruncationOperation : (varchar(100))
  Column_errorRowDisposition : (varchar(100))
  Column_externalMetadataColumnId : (varchar(max))
  Column_length : (int)
  Column_lineageId : (varchar(max))
  Column_name : (varchar(max))
  Column_precision : (int)
  Column_scale : (int)
  Column_truncationRowDisposition : (varchar(max))
  Component_refId : (varchar(max))
  - ControlFlowDetailsRowID : (int)
  output_isErrorOut : (bit)
  output_name : (varchar(500))
  output_refId : (varchar(max))
  TaskPath : (varchar(8000))
  --
}
....

// end::puml_entity[]

=== PlantUML Entity 1 1 FK

// tag::puml_entity_1_1_fk[]
[plantuml, entity_1_1_fk-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_output_outputcolumn_src.adoc[]" as ssis.PackageTask_Dft_Component_output_outputcolumn_src << V >> {
- **PK_PackageTask_Dft_Component_output_outputcolumn_src**

..
AntoraModule; varchar(50)
PackageName; varchar(200)
Column_refId; varchar(max)
--
- idx_PackageTask_Dft_Component_output_outputcolumn_src__2

..
AntoraModule; varchar(50)
PackageName; varchar(200)
--
- idx_PackageTask_Dft_Component_output_outputcolumn_src__3

..
AntoraModule; varchar(50)
}



footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_fk[]

=== PlantUML 1 1 ObjectRef

// tag::puml_entity_1_1_objectref[]
[plantuml, entity_1_1_objectref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis.package_src.adoc[]" as ssis.Package_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_output_outputcolumn_src.adoc[]" as ssis.PackageTask_Dft_Component_output_outputcolumn_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Column_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_output_outputcolumn_tgt.adoc[]" as ssis.PackageTask_Dft_Component_output_outputColumn_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Column_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packagetask_dft_component_output_outputcolumn_tgt.adoc[]" as ssis.usp_PERSIST_PackageTask_Dft_Component_output_outputColumn_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tblcontrolflow.adoc[]" as ssis_t.TblControlFlow << U >> {
  - **ControlFlowDetailsRowID** : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_dft_component_outputs_outputcolumn_src.adoc[]" as ssis_t.TblTask_Dft_Component_outputs_outputColumn_src << V >> {
  --
}

ssis.Package_src <.. ssis.PackageTask_Dft_Component_output_outputcolumn_src
ssis.PackageTask_Dft_Component_output_outputcolumn_src <.. ssis.PackageTask_Dft_Component_output_outputcolumn_tgt
ssis.PackageTask_Dft_Component_output_outputcolumn_src <.. ssis.usp_PERSIST_PackageTask_Dft_Component_output_outputColumn_tgt
ssis_t.TblControlFlow <.. ssis.PackageTask_Dft_Component_output_outputcolumn_src
ssis_t.TblTask_Dft_Component_outputs_outputColumn_src <.. ssis.PackageTask_Dft_Component_output_outputcolumn_src

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_objectref[]

=== PlantUML 30 0 ObjectRef

// tag::puml_entity_30_0_objectref[]
[plantuml, entity_30_0_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis.package_src.adoc[]" as ssis.Package_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_output_outputcolumn_src.adoc[]" as ssis.PackageTask_Dft_Component_output_outputcolumn_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Column_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.project.adoc[]" as ssis.Project << U >> {
  - **AntoraModule** : (varchar(50))
  --
}

entity "puml-link:dhw:sqldb:ssis_t.pkgstats.adoc[]" as ssis_t.pkgStats << U >> {
  - **RowID** : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tblcontrolflow.adoc[]" as ssis_t.TblControlFlow << U >> {
  - **ControlFlowDetailsRowID** : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_dft_component.adoc[]" as ssis_t.TblTask_Dft_Component << U >> {
  - **DftComponentId** : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_dft_component_outputs_outputcolumn_src.adoc[]" as ssis_t.TblTask_Dft_Component_outputs_outputColumn_src << V >> {
  --
}

ssis.Package_src <.. ssis.PackageTask_Dft_Component_output_outputcolumn_src
ssis.Project <.. ssis.Package_src
ssis_t.pkgStats <.. ssis.Package_src
ssis_t.TblControlFlow <.. ssis.PackageTask_Dft_Component_output_outputcolumn_src
ssis_t.TblTask_Dft_Component <.. ssis_t.TblTask_Dft_Component_outputs_outputColumn_src
ssis_t.TblTask_Dft_Component_outputs_outputColumn_src <.. ssis.PackageTask_Dft_Component_output_outputcolumn_src

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_30_0_objectref[]

=== PlantUML 0 30 ObjectRef

// tag::puml_entity_0_30_objectref[]
[plantuml, entity_0_30_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:docs.ssis_adoc.adoc[]" as docs.ssis_Adoc << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageBasename** : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_adoc_t.adoc[]" as docs.ssis_Adoc_T << U >> {
  - **AntoraModule** : (varchar(50))
  **PackageBasename** : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_dfttaskcomponentlist.adoc[]" as docs.ssis_DftTaskComponentList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_dfttaskcomponentoutputcolumnlist.adoc[]" as docs.ssis_DftTaskComponentOutputColumnList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_dfttaskcomponentoutputlist.adoc[]" as docs.ssis_DftTaskComponentOutputList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_task.adoc[]" as docs.ssis_Task << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_tasklist.adoc[]" as docs.ssis_TaskList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport.adoc[]" as docs.usp_AntoraExport << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_ssispartialscontent.adoc[]" as docs.usp_AntoraExport_SsisPartialsContent << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_ssis_adoc_t.adoc[]" as docs.usp_PERSIST_ssis_Adoc_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_output_outputcolumn.adoc[]" as ssis.PackageTask_Dft_Component_output_outputcolumn << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_output_outputcolumn_src.adoc[]" as ssis.PackageTask_Dft_Component_output_outputcolumn_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Column_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_output_outputcolumn_tgt.adoc[]" as ssis.PackageTask_Dft_Component_output_outputColumn_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Column_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_import.adoc[]" as ssis.usp_import << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packagetask_dft_component_output_outputcolumn_tgt.adoc[]" as ssis.usp_PERSIST_PackageTask_Dft_Component_output_outputColumn_tgt << P >> {
  --
}

docs.ssis_Adoc <.. docs.usp_PERSIST_ssis_Adoc_T
docs.ssis_Adoc <.. docs.ssis_Adoc_T
docs.ssis_Adoc_T <.. docs.usp_AntoraExport_SsisPartialsContent
docs.ssis_Adoc_T <.. docs.usp_PERSIST_ssis_Adoc_T
docs.ssis_DftTaskComponentList <.. docs.ssis_TaskList
docs.ssis_DftTaskComponentList <.. docs.ssis_Task
docs.ssis_DftTaskComponentOutputColumnList <.. docs.ssis_DftTaskComponentOutputList
docs.ssis_DftTaskComponentOutputList <.. docs.ssis_DftTaskComponentList
docs.ssis_TaskList <.. docs.ssis_Adoc
docs.usp_AntoraExport_SsisPartialsContent <.. docs.usp_AntoraExport
docs.usp_PERSIST_ssis_Adoc_T <.. docs.usp_AntoraExport_SsisPartialsContent
ssis.PackageTask_Dft_Component_output_outputcolumn <.. docs.ssis_DftTaskComponentOutputColumnList
ssis.PackageTask_Dft_Component_output_outputcolumn_src <.. ssis.PackageTask_Dft_Component_output_outputcolumn_tgt
ssis.PackageTask_Dft_Component_output_outputcolumn_src <.. ssis.usp_PERSIST_PackageTask_Dft_Component_output_outputColumn_tgt
ssis.PackageTask_Dft_Component_output_outputColumn_tgt <.. ssis.usp_PERSIST_PackageTask_Dft_Component_output_outputColumn_tgt
ssis.PackageTask_Dft_Component_output_outputcolumn_tgt <.. ssis.PackageTask_Dft_Component_output_outputcolumn
ssis.usp_PERSIST_PackageTask_Dft_Component_output_outputColumn_tgt <.. ssis.usp_import

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_0_30_objectref[]

=== PlantUML 1 1 ColumnRef

// tag::puml_entity_1_1_colref[]
[plantuml, entity_1_1_colref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis.package_src.adoc[]" as ssis.Package_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  PackageCreationDate : (datetime)
  PackageCreatorComputerName : (nvarchar(500))
  PackageCreatorName : (varchar(1000))
  PackageDescription : (nvarchar(max))
  PackageDTSID : (uniqueidentifier)
  PackageLastModifiedProductVersion : (nvarchar(500))
  PackageLocaleID : (int)
  PackageObjectName : (nvarchar(500))
  - PackagePath : (varchar(8000))
  PackageProtectionLevel : (varchar(100))
  PackageProtectionLevelName : (varchar(28))
  PackageVersionGUID : (uniqueidentifier)
  - ProjectPath : (varchar(8000))
  - RowID : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_output_outputcolumn_src.adoc[]" as ssis.PackageTask_Dft_Component_output_outputcolumn_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Column_refId** : (varchar(max))
  Column_dataType : (varchar(100))
  Column_errorOrTruncationOperation : (varchar(100))
  Column_errorRowDisposition : (varchar(100))
  Column_externalMetadataColumnId : (varchar(max))
  Column_length : (int)
  Column_lineageId : (varchar(max))
  Column_name : (varchar(max))
  Column_precision : (int)
  Column_scale : (int)
  Column_truncationRowDisposition : (varchar(max))
  Component_refId : (varchar(max))
  - ControlFlowDetailsRowID : (int)
  output_isErrorOut : (bit)
  output_name : (varchar(500))
  output_refId : (varchar(max))
  TaskPath : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_output_outputcolumn_tgt.adoc[]" as ssis.PackageTask_Dft_Component_output_outputColumn_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Column_refId** : (varchar(max))
  Column_dataType : (varchar(100))
  Column_errorOrTruncationOperation : (varchar(100))
  Column_errorRowDisposition : (varchar(100))
  Column_externalMetadataColumnId : (varchar(max))
  Column_length : (int)
  Column_lineageId : (varchar(max))
  Column_name : (varchar(max))
  Column_precision : (int)
  Column_scale : (int)
  Column_truncationRowDisposition : (varchar(max))
  Component_refId : (varchar(max))
  - ControlFlowDetailsRowID : (int)
  output_isErrorOut : (bit)
  output_name : (varchar(500))
  output_refId : (varchar(max))
  TaskPath : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packagetask_dft_component_output_outputcolumn_tgt.adoc[]" as ssis.usp_PERSIST_PackageTask_Dft_Component_output_outputColumn_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tblcontrolflow.adoc[]" as ssis_t.TblControlFlow << U >> {
  - **ControlFlowDetailsRowID** : (int)
  DelayValidationPropertyValue : (varchar(100))
  DFTQuery : (xml)
  ExecPkgTaskQry : (xml)
  ExpressionValue : (varchar(5000))
  IsDisabled : (varchar(10))
  RowID : (int)
  ScriptTaskQry : (xml)
  SqlTaskQry : (xml)
  TaskDescription : (varchar(max))
  TaskName : (varchar(2000))
  TaskPath : (varchar(8000))
  TaskType : (varchar(5000))
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_dft_component_outputs_outputcolumn_src.adoc[]" as ssis_t.TblTask_Dft_Component_outputs_outputColumn_src << V >> {
  Column_dataType : (varchar(100))
  Column_errorOrTruncationOperation : (varchar(100))
  Column_errorRowDisposition : (varchar(100))
  Column_externalMetadataColumnId : (varchar(max))
  Column_length : (int)
  Column_lineageId : (varchar(max))
  Column_name : (varchar(max))
  Column_precision : (int)
  Column_refId : (varchar(max))
  Column_scale : (int)
  Column_truncationRowDisposition : (varchar(max))
  columnscontent : (xml)
  - ControlFlowDetailsRowID : (int)
  - DftComponentId : (int)
  nodescontent : (xml)
  output_isErrorOut : (bit)
  output_name : (varchar(500))
  output_refId : (varchar(max))
  refId : (varchar(max))
  RowID : (int)
  --
}

ssis.Package_src <.. ssis.PackageTask_Dft_Component_output_outputcolumn_src
ssis.PackageTask_Dft_Component_output_outputcolumn_src <.. ssis.PackageTask_Dft_Component_output_outputcolumn_tgt
ssis.PackageTask_Dft_Component_output_outputcolumn_src <.. ssis.usp_PERSIST_PackageTask_Dft_Component_output_outputColumn_tgt
ssis_t.TblControlFlow <.. ssis.PackageTask_Dft_Component_output_outputcolumn_src
ssis_t.TblTask_Dft_Component_outputs_outputColumn_src <.. ssis.PackageTask_Dft_Component_output_outputcolumn_src
"ssis.Package_src::AntoraModule" <-- "ssis.PackageTask_Dft_Component_output_outputcolumn_src::AntoraModule"
"ssis.Package_src::PackageName" <-- "ssis.PackageTask_Dft_Component_output_outputcolumn_src::PackageName"
"ssis.PackageTask_Dft_Component_output_outputcolumn_src::AntoraModule" <-- "ssis.PackageTask_Dft_Component_output_outputcolumn_tgt::AntoraModule"
"ssis.PackageTask_Dft_Component_output_outputcolumn_src::Column_dataType" <-- "ssis.PackageTask_Dft_Component_output_outputcolumn_tgt::Column_dataType"
"ssis.PackageTask_Dft_Component_output_outputcolumn_src::Column_errorOrTruncationOperation" <-- "ssis.PackageTask_Dft_Component_output_outputcolumn_tgt::Column_errorOrTruncationOperation"
"ssis.PackageTask_Dft_Component_output_outputcolumn_src::Column_errorRowDisposition" <-- "ssis.PackageTask_Dft_Component_output_outputcolumn_tgt::Column_errorRowDisposition"
"ssis.PackageTask_Dft_Component_output_outputcolumn_src::Column_externalMetadataColumnId" <-- "ssis.PackageTask_Dft_Component_output_outputcolumn_tgt::Column_externalMetadataColumnId"
"ssis.PackageTask_Dft_Component_output_outputcolumn_src::Column_length" <-- "ssis.PackageTask_Dft_Component_output_outputcolumn_tgt::Column_length"
"ssis.PackageTask_Dft_Component_output_outputcolumn_src::Column_lineageId" <-- "ssis.PackageTask_Dft_Component_output_outputcolumn_tgt::Column_lineageId"
"ssis.PackageTask_Dft_Component_output_outputcolumn_src::Column_name" <-- "ssis.PackageTask_Dft_Component_output_outputcolumn_tgt::Column_name"
"ssis.PackageTask_Dft_Component_output_outputcolumn_src::Column_precision" <-- "ssis.PackageTask_Dft_Component_output_outputcolumn_tgt::Column_precision"
"ssis.PackageTask_Dft_Component_output_outputcolumn_src::Column_refId" <-- "ssis.PackageTask_Dft_Component_output_outputcolumn_tgt::Column_refId"
"ssis.PackageTask_Dft_Component_output_outputcolumn_src::Column_scale" <-- "ssis.PackageTask_Dft_Component_output_outputcolumn_tgt::Column_scale"
"ssis.PackageTask_Dft_Component_output_outputcolumn_src::Column_truncationRowDisposition" <-- "ssis.PackageTask_Dft_Component_output_outputcolumn_tgt::Column_truncationRowDisposition"
"ssis.PackageTask_Dft_Component_output_outputcolumn_src::Component_refId" <-- "ssis.PackageTask_Dft_Component_output_outputcolumn_tgt::Component_refId"
"ssis.PackageTask_Dft_Component_output_outputcolumn_src::ControlFlowDetailsRowID" <-- "ssis.PackageTask_Dft_Component_output_outputcolumn_tgt::ControlFlowDetailsRowID"
"ssis.PackageTask_Dft_Component_output_outputcolumn_src::output_isErrorOut" <-- "ssis.PackageTask_Dft_Component_output_outputcolumn_tgt::output_isErrorOut"
"ssis.PackageTask_Dft_Component_output_outputcolumn_src::output_name" <-- "ssis.PackageTask_Dft_Component_output_outputcolumn_tgt::output_name"
"ssis.PackageTask_Dft_Component_output_outputcolumn_src::output_refId" <-- "ssis.PackageTask_Dft_Component_output_outputcolumn_tgt::output_refId"
"ssis.PackageTask_Dft_Component_output_outputcolumn_src::PackageName" <-- "ssis.PackageTask_Dft_Component_output_outputcolumn_tgt::PackageName"
"ssis.PackageTask_Dft_Component_output_outputcolumn_src::TaskPath" <-- "ssis.PackageTask_Dft_Component_output_outputcolumn_tgt::TaskPath"
"ssis_t.TblControlFlow::TaskPath" <-- "ssis.PackageTask_Dft_Component_output_outputcolumn_src::TaskPath"
"ssis_t.TblTask_Dft_Component_outputs_outputColumn_src::Column_dataType" <-- "ssis.PackageTask_Dft_Component_output_outputcolumn_src::Column_dataType"
"ssis_t.TblTask_Dft_Component_outputs_outputColumn_src::Column_errorOrTruncationOperation" <-- "ssis.PackageTask_Dft_Component_output_outputcolumn_src::Column_errorOrTruncationOperation"
"ssis_t.TblTask_Dft_Component_outputs_outputColumn_src::Column_errorRowDisposition" <-- "ssis.PackageTask_Dft_Component_output_outputcolumn_src::Column_errorRowDisposition"
"ssis_t.TblTask_Dft_Component_outputs_outputColumn_src::Column_externalMetadataColumnId" <-- "ssis.PackageTask_Dft_Component_output_outputcolumn_src::Column_externalMetadataColumnId"
"ssis_t.TblTask_Dft_Component_outputs_outputColumn_src::Column_length" <-- "ssis.PackageTask_Dft_Component_output_outputcolumn_src::Column_length"
"ssis_t.TblTask_Dft_Component_outputs_outputColumn_src::Column_lineageId" <-- "ssis.PackageTask_Dft_Component_output_outputcolumn_src::Column_lineageId"
"ssis_t.TblTask_Dft_Component_outputs_outputColumn_src::Column_name" <-- "ssis.PackageTask_Dft_Component_output_outputcolumn_src::Column_name"
"ssis_t.TblTask_Dft_Component_outputs_outputColumn_src::Column_precision" <-- "ssis.PackageTask_Dft_Component_output_outputcolumn_src::Column_precision"
"ssis_t.TblTask_Dft_Component_outputs_outputColumn_src::Column_refId" <-- "ssis.PackageTask_Dft_Component_output_outputcolumn_src::Column_refId"
"ssis_t.TblTask_Dft_Component_outputs_outputColumn_src::Column_scale" <-- "ssis.PackageTask_Dft_Component_output_outputcolumn_src::Column_scale"
"ssis_t.TblTask_Dft_Component_outputs_outputColumn_src::Column_truncationRowDisposition" <-- "ssis.PackageTask_Dft_Component_output_outputcolumn_src::Column_truncationRowDisposition"
"ssis_t.TblTask_Dft_Component_outputs_outputColumn_src::ControlFlowDetailsRowID" <-- "ssis.PackageTask_Dft_Component_output_outputcolumn_src::ControlFlowDetailsRowID"
"ssis_t.TblTask_Dft_Component_outputs_outputColumn_src::output_isErrorOut" <-- "ssis.PackageTask_Dft_Component_output_outputcolumn_src::output_isErrorOut"
"ssis_t.TblTask_Dft_Component_outputs_outputColumn_src::output_name" <-- "ssis.PackageTask_Dft_Component_output_outputcolumn_src::output_name"
"ssis_t.TblTask_Dft_Component_outputs_outputColumn_src::output_refId" <-- "ssis.PackageTask_Dft_Component_output_outputcolumn_src::output_refId"
"ssis_t.TblTask_Dft_Component_outputs_outputColumn_src::refId" <-- "ssis.PackageTask_Dft_Component_output_outputcolumn_src::Component_refId"

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_colref[]


== sql_modules_definition

// tag::sql_modules_definition[]
[%collapsible]
=======
[source,sql,numbered,indent=0]
----
CREATE View [ssis].[PackageTask_Dft_Component_output_outputColumn_src]
As
Select
    p.AntoraModule
  , p.PackageName
  , Component_refId = T3.refId
  , T3.output_refId
  , T3.output_name
  , T3.output_isErrorOut
  , T3.Column_refId
  , T3.Column_name
  , T3.Column_dataType
  , T3.Column_length
  , T3.Column_precision
  , T3.Column_scale
  , T3.Column_errorOrTruncationOperation
  , T3.Column_errorRowDisposition
  , T3.Column_externalMetadataColumnId
  , T3.Column_lineageId
  , T3.Column_truncationRowDisposition
  , T2.TaskPath
  , T3.ControlFlowDetailsRowID
From
    ssis.Package_src                                          As p
    Inner Join
        ssis_t.TblControlFlow                                 As T2
            On
            p.RowID                    = T2.RowID

    Inner Join
        ssis_t.TblTask_Dft_Component_outputs_outputColumn_src As T3
            On
            T3.ControlFlowDetailsRowID = T2.ControlFlowDetailsRowID
----
=======
// end::sql_modules_definition[]


