// tag::HeaderFullDisplayName[]
= ssis.PackageFlow - U
// end::HeaderFullDisplayName[]

== existing_properties

// tag::existing_properties[]

:ExistsProperty--antorareferencedlist:
:ExistsProperty--antorareferencinglist:
:ExistsProperty--is_repo_managed:
:ExistsProperty--is_ssas:
:ExistsProperty--referencedobjectlist:
:ExistsProperty--FK:
:ExistsProperty--Columns:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
5C64FBE4-113B-EC11-852C-A81E8446D5B0
// end::RepoObject_guid[]

== RepoObject_FullDisplayName2

// tag::RepoObject_FullDisplayName2[]
ssis.PackageFlow
// end::RepoObject_FullDisplayName2[]

== SysObject_type

// tag::SysObject_type[]
U 
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
user table
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
562153098
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2022-01-23 14:10:32
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]
[discrete]
== _


[#column-antoramodule]
=== AntoraModule

[cols="d,8a,m,m,m"]
|===
|
|AntoraModule
|varchar(50)
|NOT NULL
|
|===

.Referencing Columns
--
* xref:docs.ssis_pumlpartialcontrolflows.adoc#column-antoramodule[+docs.ssis_PumlPartialControlFlows.AntoraModule+]
* xref:docs.ssis_pumlpartialdataflow.adoc#column-antoramodule[+docs.ssis_PumlPartialDataFlow.AntoraModule+]
* xref:ssis.packageflow_tgt.adoc#column-antoramodule[+ssis.PackageFlow_tgt.AntoraModule+]
--


[#column-creationname]
=== CreationName

[cols="d,8a,m,m,m"]
|===
|
|CreationName
|nvarchar(max)
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packageflow_tgt.adoc#column-creationname[+ssis.PackageFlow_tgt.CreationName+]
--


[#column-dtsid]
=== DTSID

[cols="d,8a,m,m,m"]
|===
|
|DTSID
|uniqueidentifier
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packageflow_tgt.adoc#column-dtsid[+ssis.PackageFlow_tgt.DTSID+]
--


[#column-evalop]
=== EvalOp

[cols="d,8a,m,m,m"]
|===
|
|EvalOp
|int
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packageflow_tgt.adoc#column-evalop[+ssis.PackageFlow_tgt.EvalOp+]
--


[#column-expression]
=== Expression

[cols="d,8a,m,m,m"]
|===
|
|Expression
|nvarchar(max)
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packageflow_tgt.adoc#column-expression[+ssis.PackageFlow_tgt.Expression+]
--


[#column-flowtype]
=== FlowType

[cols="d,8a,m,m,m"]
|===
|
|FlowType
|varchar(1000)
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packageflow_tgt.adoc#column-flowtype[+ssis.PackageFlow_tgt.FlowType+]
--


[#column-logicaland]
=== LogicalAnd

[cols="d,8a,m,m,m"]
|===
|
|LogicalAnd
|bit
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packageflow_tgt.adoc#column-logicaland[+ssis.PackageFlow_tgt.LogicalAnd+]
--


[#column-objectname]
=== ObjectName

[cols="d,8a,m,m,m"]
|===
|
|ObjectName
|nvarchar(max)
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packageflow_tgt.adoc#column-objectname[+ssis.PackageFlow_tgt.ObjectName+]
--


[#column-packagename]
=== PackageName

[cols="d,8a,m,m,m"]
|===
|
|PackageName
|varchar(200)
|NOT NULL
|
|===

.Referencing Columns
--
* xref:docs.ssis_pumlpartialcontrolflows.adoc#column-packagename[+docs.ssis_PumlPartialControlFlows.PackageName+]
* xref:docs.ssis_pumlpartialdataflow.adoc#column-packagename[+docs.ssis_PumlPartialDataFlow.PackageName+]
* xref:ssis.packageflow_tgt.adoc#column-packagename[+ssis.PackageFlow_tgt.PackageName+]
--


[#column-taskfrom]
=== TaskFrom

[cols="d,8a,m,m,m"]
|===
|
|TaskFrom
|varchar(2000)
|NOT NULL
|
|===

.Referencing Columns
--
* xref:ssis.packageflow.adoc#column-taskfromlevel[+ssis.PackageFlow.TaskFromLevel+]
* xref:ssis.packageflow.adoc#column-taskfromparent[+ssis.PackageFlow.TaskFromParent+]
* xref:ssis.packageflow_tgt.adoc#column-taskfrom[+ssis.PackageFlow_tgt.TaskFrom+]
--


[#column-taskto]
=== Taskto

[cols="d,8a,m,m,m"]
|===
|
|Taskto
|varchar(2000)
|NOT NULL
|
|===

.Referencing Columns
--
* xref:ssis.packageflow.adoc#column-tasktolevel[+ssis.PackageFlow.TaskToLevel+]
* xref:ssis.packageflow.adoc#column-tasktoparent[+ssis.PackageFlow.TaskToParent+]
* xref:ssis.packageflow_tgt.adoc#column-taskto[+ssis.PackageFlow_tgt.Taskto+]
--


[#column-taskfromlevel]
=== TaskFromLevel

[cols="d,8a,m,m,m"]
|===
|
|TaskFromLevel

.Definition (PERSISTED)
[source,sql]
----
(len([TaskFrom])-len(replace([TaskFrom],'\','')))
----


|int
|NULL
|
|===

.Description
--
(len([TaskFrom])-len(replace([TaskFrom],'\','')))
--
{empty} +

.Referenced Columns
--
* xref:ssis.packageflow.adoc#column-taskfrom[+ssis.PackageFlow.TaskFrom+]
--


[#column-taskfromparent]
=== TaskFromParent

[cols="d,8a,m,m,m"]
|===
|
|TaskFromParent

.Definition (PERSISTED)
[source,sql]
----
(substring([TaskFrom],(1),len([TaskFrom])-charindex('\',reverse([TaskFrom]))))
----


|varchar(2000)
|NULL
|
|===

.Description
--
(substring([TaskFrom],(1),len([TaskFrom])-charindex('\',reverse([TaskFrom]))))
--
{empty} +

.Referenced Columns
--
* xref:ssis.packageflow.adoc#column-taskfrom[+ssis.PackageFlow.TaskFrom+]
--

.Referencing Columns
--
* xref:docs.ssis_pumlpartialdataflow.adoc#column-taskfromparent[+docs.ssis_PumlPartialDataFlow.TaskFromParent+]
--


[#column-tasktolevel]
=== TaskToLevel

[cols="d,8a,m,m,m"]
|===
|
|TaskToLevel

.Definition (PERSISTED)
[source,sql]
----
(len([TaskTo])-len(replace([TaskTo],'\','')))
----


|int
|NULL
|
|===

.Description
--
(len([TaskTo])-len(replace([TaskTo],'\','')))
--
{empty} +

.Referenced Columns
--
* xref:ssis.packageflow.adoc#column-taskto[+ssis.PackageFlow.Taskto+]
--


[#column-tasktoparent]
=== TaskToParent

[cols="d,8a,m,m,m"]
|===
|
|TaskToParent

.Definition (PERSISTED)
[source,sql]
----
(substring([TaskTo],(1),len([TaskTo])-charindex('\',reverse([TaskTo]))))
----


|varchar(2000)
|NULL
|
|===

.Description
--
(substring([TaskTo],(1),len([TaskTo])-charindex('\',reverse([TaskTo]))))
--
{empty} +

.Referenced Columns
--
* xref:ssis.packageflow.adoc#column-taskto[+ssis.PackageFlow.Taskto+]
--


// end::AntoraColumnDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]















// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]
|
|<<column-antoramodule>>
|varchar(50)
|NOT NULL
|

|
|<<column-creationname>>
|nvarchar(max)
|NULL
|

|
|<<column-dtsid>>
|uniqueidentifier
|NULL
|

|
|<<column-evalop>>
|int
|NULL
|

|
|<<column-expression>>
|nvarchar(max)
|NULL
|

|
|<<column-flowtype>>
|varchar(1000)
|NULL
|

|
|<<column-logicaland>>
|bit
|NULL
|

|
|<<column-objectname>>
|nvarchar(max)
|NULL
|

|
|<<column-packagename>>
|varchar(200)
|NOT NULL
|

|
|<<column-taskfrom>>
|varchar(2000)
|NOT NULL
|

|
|<<column-taskto>>
|varchar(2000)
|NOT NULL
|

|
|<<column-taskfromlevel>>

.Definition (PERSISTED)
[source,sql]
----
(len([TaskFrom])-len(replace([TaskFrom],'\','')))
----


|int
|NULL
|

|
|<<column-taskfromparent>>

.Definition (PERSISTED)
[source,sql]
----
(substring([TaskFrom],(1),len([TaskFrom])-charindex('\',reverse([TaskFrom]))))
----


|varchar(2000)
|NULL
|

|
|<<column-tasktolevel>>

.Definition (PERSISTED)
[source,sql]
----
(len([TaskTo])-len(replace([TaskTo],'\','')))
----


|int
|NULL
|

|
|<<column-tasktoparent>>

.Definition (PERSISTED)
[source,sql]
----
(substring([TaskTo],(1),len([TaskTo])-charindex('\',reverse([TaskTo]))))
----


|varchar(2000)
|NULL
|

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

// end::AntoraIndexList[]

== AntoraMeasureDetails

// tag::AntoraMeasureDetails[]

// end::AntoraMeasureDetails[]

== AntoraMeasureDescriptions



== AntoraParameterList

// tag::AntoraParameterList[]

// end::AntoraParameterList[]

== AntoraXrefCulturesList

// tag::AntoraXrefCulturesList[]
* xref:dhw:sqldb:ssis.packageflow.adoc[] - 
// end::AntoraXrefCulturesList[]

== cultures_count

// tag::cultures_count[]
1
// end::cultures_count[]

== Other tags

source: property.RepoObjectProperty_cross As rop_cross


=== additional_reference_csv

// tag::additional_reference_csv[]

// end::additional_reference_csv[]


=== AdocUspSteps

// tag::adocuspsteps[]

// end::adocuspsteps[]


=== AntoraReferencedList

// tag::antorareferencedlist[]
* xref:dhw:sqldb:ssis.packageflow_tgt.adoc[]
// end::antorareferencedlist[]


=== AntoraReferencingList

// tag::antorareferencinglist[]
* xref:dhw:sqldb:docs.ssis_pumlpartialcontrolflows.adoc[]
* xref:dhw:sqldb:docs.ssis_pumlpartialdataflow.adoc[]
// end::antorareferencinglist[]


=== Description

// tag::description[]

// end::description[]


=== exampleUsage

// tag::exampleusage[]

// end::exampleusage[]


=== exampleUsage_2

// tag::exampleusage_2[]

// end::exampleusage_2[]


=== exampleUsage_3

// tag::exampleusage_3[]

// end::exampleusage_3[]


=== exampleUsage_4

// tag::exampleusage_4[]

// end::exampleusage_4[]


=== exampleUsage_5

// tag::exampleusage_5[]

// end::exampleusage_5[]


=== exampleWrong_Usage

// tag::examplewrong_usage[]

// end::examplewrong_usage[]


=== has_execution_plan_issue

// tag::has_execution_plan_issue[]

// end::has_execution_plan_issue[]


=== has_get_referenced_issue

// tag::has_get_referenced_issue[]

// end::has_get_referenced_issue[]


=== has_history

// tag::has_history[]

// end::has_history[]


=== has_history_columns

// tag::has_history_columns[]

// end::has_history_columns[]


=== InheritanceType

// tag::inheritancetype[]

// end::inheritancetype[]


=== is_persistence

// tag::is_persistence[]

// end::is_persistence[]


=== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]

// end::is_persistence_check_duplicate_per_pk[]


=== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]

// end::is_persistence_check_for_empty_source[]


=== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]

// end::is_persistence_delete_changed[]


=== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]

// end::is_persistence_delete_missing[]


=== is_persistence_insert

// tag::is_persistence_insert[]

// end::is_persistence_insert[]


=== is_persistence_truncate

// tag::is_persistence_truncate[]

// end::is_persistence_truncate[]


=== is_persistence_update_changed

// tag::is_persistence_update_changed[]

// end::is_persistence_update_changed[]


=== is_repo_managed

// tag::is_repo_managed[]
0
// end::is_repo_managed[]


=== is_ssas

// tag::is_ssas[]
0
// end::is_ssas[]


=== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


=== MS_Description

// tag::ms_description[]

// end::ms_description[]


=== persistence_source_RepoObject_fullname

// tag::persistence_source_repoobject_fullname[]

// end::persistence_source_repoobject_fullname[]


=== persistence_source_RepoObject_fullname2

// tag::persistence_source_repoobject_fullname2[]

// end::persistence_source_repoobject_fullname2[]


=== persistence_source_RepoObject_guid

// tag::persistence_source_repoobject_guid[]

// end::persistence_source_repoobject_guid[]


=== persistence_source_RepoObject_xref

// tag::persistence_source_repoobject_xref[]

// end::persistence_source_repoobject_xref[]


=== pk_index_guid

// tag::pk_index_guid[]

// end::pk_index_guid[]


=== pk_IndexPatternColumnDatatype

// tag::pk_indexpatterncolumndatatype[]

// end::pk_indexpatterncolumndatatype[]


=== pk_IndexPatternColumnName

// tag::pk_indexpatterncolumnname[]

// end::pk_indexpatterncolumnname[]


=== pk_IndexSemanticGroup

// tag::pk_indexsemanticgroup[]

// end::pk_indexsemanticgroup[]


=== ReferencedObjectList

// tag::referencedobjectlist[]
* [ssis].[PackageFlow_tgt]
// end::referencedobjectlist[]


=== usp_persistence_RepoObject_guid

// tag::usp_persistence_repoobject_guid[]

// end::usp_persistence_repoobject_guid[]


=== UspExamples

// tag::uspexamples[]

// end::uspexamples[]


=== uspgenerator_usp_id

// tag::uspgenerator_usp_id[]

// end::uspgenerator_usp_id[]


=== UspParameters

// tag::uspparameters[]

// end::uspparameters[]

== Boolean Attributes

source: property.RepoObjectProperty WHERE property_int = 1

// tag::boolean_attributes[]


// end::boolean_attributes[]

== PlantUML diagrams

=== PlantUML Entity

// tag::puml_entity[]
[plantuml, entity-{docname}, svg, subs=macros]
....
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis.packageflow.adoc[]" as ssis.PackageFlow << U >> {
  - AntoraModule : (varchar(50))
  CreationName : (nvarchar(max))
  DTSID : (uniqueidentifier)
  EvalOp : (int)
  Expression : (nvarchar(max))
  FlowType : (varchar(1000))
  LogicalAnd : (bit)
  ObjectName : (nvarchar(max))
  - PackageName : (varchar(200))
  - TaskFrom : (varchar(2000))
  - Taskto : (varchar(2000))
  # TaskFromLevel : (int)
  # TaskFromParent : (varchar(2000))
  # TaskToLevel : (int)
  # TaskToParent : (varchar(2000))
  --
}
....

// end::puml_entity[]

=== PlantUML Entity 1 1 FK

// tag::puml_entity_1_1_fk[]
[plantuml, entity_1_1_fk-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis.packageflow.adoc[]" as ssis.PackageFlow << U >> {

}



footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_fk[]

=== PlantUML 1 1 ObjectRef

// tag::puml_entity_1_1_objectref[]
[plantuml, entity_1_1_objectref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:docs.ssis_pumlpartialcontrolflows.adoc[]" as docs.ssis_PumlPartialControlFlows << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_pumlpartialdataflow.adoc[]" as docs.ssis_PumlPartialDataFlow << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.packageflow.adoc[]" as ssis.PackageFlow << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.packageflow_tgt.adoc[]" as ssis.PackageFlow_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  - **PackageName** : (varchar(200))
  - **TaskFrom** : (varchar(2000))
  - **Taskto** : (varchar(2000))
  --
}

ssis.PackageFlow <.. docs.ssis_PumlPartialControlFlows
ssis.PackageFlow <.. docs.ssis_PumlPartialDataFlow
ssis.PackageFlow_tgt <.. ssis.PackageFlow

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_objectref[]

=== PlantUML 30 0 ObjectRef

// tag::puml_entity_30_0_objectref[]
[plantuml, entity_30_0_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis.antoramodule_tgt_filter.adoc[]" as ssis.AntoraModule_tgt_filter << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.package_src.adoc[]" as ssis.Package_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  --
}

entity "puml-link:dhw:sqldb:ssis.packageflow.adoc[]" as ssis.PackageFlow << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.packageflow_src.adoc[]" as ssis.PackageFlow_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **TaskFrom** : (varchar(2000))
  **Taskto** : (varchar(2000))
  --
}

entity "puml-link:dhw:sqldb:ssis.packageflow_tgt.adoc[]" as ssis.PackageFlow_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  - **PackageName** : (varchar(200))
  - **TaskFrom** : (varchar(2000))
  - **Taskto** : (varchar(2000))
  --
}

entity "puml-link:dhw:sqldb:ssis.project.adoc[]" as ssis.Project << U >> {
  - **AntoraModule** : (varchar(50))
  --
}

entity "puml-link:dhw:sqldb:ssis_t.pkgstats.adoc[]" as ssis_t.pkgStats << U >> {
  - **RowID** : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tblprecedenceconstraint.adoc[]" as ssis_t.TblPrecedenceConstraint << U >> {
  --
}

ssis.AntoraModule_tgt_filter <.. ssis.PackageFlow_tgt
ssis.Package_src <.. ssis.AntoraModule_tgt_filter
ssis.Package_src <.. ssis.PackageFlow_src
ssis.PackageFlow_src <.. ssis.PackageFlow_tgt
ssis.PackageFlow_tgt <.. ssis.PackageFlow
ssis.Project <.. ssis.Package_src
ssis_t.pkgStats <.. ssis.Package_src
ssis_t.TblPrecedenceConstraint <.. ssis.PackageFlow_src

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_30_0_objectref[]

=== PlantUML 0 30 ObjectRef

// tag::puml_entity_0_30_objectref[]
[plantuml, entity_0_30_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:docs.ssis_adoc.adoc[]" as docs.ssis_Adoc << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageBasename** : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_adoc_t.adoc[]" as docs.ssis_Adoc_T << U >> {
  - **AntoraModule** : (varchar(50))
  - **PackageBasename** : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_pumldfttask.adoc[]" as docs.ssis_PumlDftTask << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_pumlpackage.adoc[]" as docs.ssis_PumlPackage << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_pumlpartialcontrolflows.adoc[]" as docs.ssis_PumlPartialControlFlows << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_pumlpartialdataflow.adoc[]" as docs.ssis_PumlPartialDataFlow << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_task.adoc[]" as docs.ssis_Task << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_tasklist.adoc[]" as docs.ssis_TaskList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport.adoc[]" as docs.usp_AntoraExport << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_ssispartialscontent.adoc[]" as docs.usp_AntoraExport_SsisPartialsContent << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_ssis_adoc_t.adoc[]" as docs.usp_PERSIST_ssis_Adoc_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.packageflow.adoc[]" as ssis.PackageFlow << U >> {
  --
}

docs.ssis_Adoc <.. docs.ssis_Adoc_T
docs.ssis_Adoc <.. docs.usp_PERSIST_ssis_Adoc_T
docs.ssis_Adoc_T <.. docs.usp_AntoraExport_SsisPartialsContent
docs.ssis_Adoc_T <.. docs.usp_PERSIST_ssis_Adoc_T
docs.ssis_PumlDftTask <.. docs.ssis_TaskList
docs.ssis_PumlDftTask <.. docs.ssis_Task
docs.ssis_PumlPackage <.. docs.ssis_Adoc
docs.ssis_PumlPartialControlFlows <.. docs.ssis_PumlPackage
docs.ssis_PumlPartialDataFlow <.. docs.ssis_PumlDftTask
docs.ssis_TaskList <.. docs.ssis_Adoc
docs.usp_AntoraExport_SsisPartialsContent <.. docs.usp_AntoraExport
docs.usp_PERSIST_ssis_Adoc_T <.. docs.usp_AntoraExport_SsisPartialsContent
ssis.PackageFlow <.. docs.ssis_PumlPartialControlFlows
ssis.PackageFlow <.. docs.ssis_PumlPartialDataFlow

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_0_30_objectref[]

=== PlantUML 1 1 ColumnRef

// tag::puml_entity_1_1_colref[]
[plantuml, entity_1_1_colref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:docs.ssis_pumlpartialcontrolflows.adoc[]" as docs.ssis_PumlPartialControlFlows << V >> {
  - AntoraModule : (varchar(50))
  - PackageName : (varchar(200))
  PumlPartialControlFlows : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_pumlpartialdataflow.adoc[]" as docs.ssis_PumlPartialDataFlow << V >> {
  - AntoraModule : (varchar(50))
  - PackageName : (varchar(200))
  PumlPartialDataFlow : (nvarchar(max))
  TaskFromParent : (varchar(2000))
  --
}

entity "puml-link:dhw:sqldb:ssis.packageflow.adoc[]" as ssis.PackageFlow << U >> {
  - AntoraModule : (varchar(50))
  CreationName : (nvarchar(max))
  DTSID : (uniqueidentifier)
  EvalOp : (int)
  Expression : (nvarchar(max))
  FlowType : (varchar(1000))
  LogicalAnd : (bit)
  ObjectName : (nvarchar(max))
  - PackageName : (varchar(200))
  - TaskFrom : (varchar(2000))
  - Taskto : (varchar(2000))
  # TaskFromLevel : (int)
  # TaskFromParent : (varchar(2000))
  # TaskToLevel : (int)
  # TaskToParent : (varchar(2000))
  --
}

entity "puml-link:dhw:sqldb:ssis.packageflow_tgt.adoc[]" as ssis.PackageFlow_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  - **PackageName** : (varchar(200))
  - **TaskFrom** : (varchar(2000))
  - **Taskto** : (varchar(2000))
  CreationName : (nvarchar(max))
  DTSID : (uniqueidentifier)
  EvalOp : (int)
  Expression : (nvarchar(max))
  FlowType : (varchar(1000))
  LogicalAnd : (bit)
  ObjectName : (nvarchar(max))
  --
}

ssis.PackageFlow <.. docs.ssis_PumlPartialControlFlows
ssis.PackageFlow <.. docs.ssis_PumlPartialDataFlow
ssis.PackageFlow_tgt <.. ssis.PackageFlow
"ssis.PackageFlow::AntoraModule" <-- "docs.ssis_PumlPartialControlFlows::AntoraModule"
"ssis.PackageFlow::AntoraModule" <-- "docs.ssis_PumlPartialDataFlow::AntoraModule"
"ssis.PackageFlow::AntoraModule" <-- "ssis.PackageFlow_tgt::AntoraModule"
"ssis.PackageFlow::CreationName" <-- "ssis.PackageFlow_tgt::CreationName"
"ssis.PackageFlow::DTSID" <-- "ssis.PackageFlow_tgt::DTSID"
"ssis.PackageFlow::EvalOp" <-- "ssis.PackageFlow_tgt::EvalOp"
"ssis.PackageFlow::Expression" <-- "ssis.PackageFlow_tgt::Expression"
"ssis.PackageFlow::FlowType" <-- "ssis.PackageFlow_tgt::FlowType"
"ssis.PackageFlow::LogicalAnd" <-- "ssis.PackageFlow_tgt::LogicalAnd"
"ssis.PackageFlow::ObjectName" <-- "ssis.PackageFlow_tgt::ObjectName"
"ssis.PackageFlow::PackageName" <-- "docs.ssis_PumlPartialDataFlow::PackageName"
"ssis.PackageFlow::PackageName" <-- "docs.ssis_PumlPartialControlFlows::PackageName"
"ssis.PackageFlow::PackageName" <-- "ssis.PackageFlow_tgt::PackageName"
"ssis.PackageFlow::TaskFrom" <-- "ssis.PackageFlow::TaskFromLevel"
"ssis.PackageFlow::TaskFrom" <-- "ssis.PackageFlow::TaskFromParent"
"ssis.PackageFlow::TaskFrom" <-- "ssis.PackageFlow_tgt::TaskFrom"
"ssis.PackageFlow::TaskFromParent" <-- "docs.ssis_PumlPartialDataFlow::TaskFromParent"
"ssis.PackageFlow::Taskto" <-- "ssis.PackageFlow::TaskToLevel"
"ssis.PackageFlow::Taskto" <-- "ssis.PackageFlow::TaskToParent"
"ssis.PackageFlow::Taskto" <-- "ssis.PackageFlow_tgt::Taskto"

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_colref[]


== sql_modules_definition

// tag::sql_modules_definition[]
[%collapsible]
=======
[source,sql,numbered,indent=0]
----

----
=======
// end::sql_modules_definition[]


