// tag::HeaderFullDisplayName[]
= ssis_t.TblControlFlow - U
// end::HeaderFullDisplayName[]

== existing_properties

// tag::existing_properties[]

:ExistsProperty--antorareferencinglist:
:ExistsProperty--is_repo_managed:
:ExistsProperty--is_ssas:
:ExistsProperty--pk_index_guid:
:ExistsProperty--pk_indexpatterncolumndatatype:
:ExistsProperty--pk_indexpatterncolumnname:
:ExistsProperty--FK:
:ExistsProperty--AntoraIndexList:
:ExistsProperty--Columns:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
7E64FBE4-113B-EC11-852C-A81E8446D5B0
// end::RepoObject_guid[]

== RepoObject_FullDisplayName2

// tag::RepoObject_FullDisplayName2[]
ssis_t.TblControlFlow
// end::RepoObject_FullDisplayName2[]

== SysObject_type

// tag::SysObject_type[]
U 
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
user table
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
1717633212
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2021-11-06 12:38:30
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]
[discrete]
== _


[#column-controlflowdetailsrowid]
=== ControlFlowDetailsRowID

[cols="d,8a,m,m,m"]
|===
|1
|*ControlFlowDetailsRowID*
|int
|NOT NULL
|(1,1)
|===

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_src.adoc#column-controlflowdetailsrowid[+ssis.PackageTask_Dft_Component_src.ControlFlowDetailsRowID+]
* xref:ssis.packagetask_sql_parameter_src.adoc#column-controlflowdetailsrowid[+ssis.PackageTask_Sql_Parameter_src.ControlFlowDetailsRowID+]
* xref:ssis.packagetask_src.adoc#column-controlflowdetailsrowid[+ssis.PackageTask_src.ControlFlowDetailsRowID+]
* xref:ssis_t.tbltask_dft_component_src.adoc#column-controlflowdetailsrowid[+ssis_t.TblTask_Dft_Component_src.ControlFlowDetailsRowID+]
* xref:ssis_t.tbltask_dft_details_src.adoc#column-controlflowdetailsrowid[+ssis_t.TblTask_Dft_Details_src.ControlFlowDetailsRowID+]
* xref:ssis_t.tbltask_script_src.adoc#column-controlflowdetailsrowid[+ssis_t.TblTask_Script_src.ControlFlowDetailsRowID+]
* xref:ssis_t.tbltask_sql_src.adoc#column-controlflowdetailsrowid[+ssis_t.TblTask_Sql_src.ControlFlowDetailsRowID+]
--


[#column-delayvalidationpropertyvalue]
=== DelayValidationPropertyValue

[cols="d,8a,m,m,m"]
|===
|
|DelayValidationPropertyValue
|varchar(100)
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packagetask_src.adoc#column-delayvalidationpropertyvalue[+ssis.PackageTask_src.DelayValidationPropertyValue+]
--


[#column-dftquery]
=== DFTQuery

[cols="d,8a,m,m,m"]
|===
|
|DFTQuery
|xml
|NULL
|
|===


[#column-execpkgtaskqry]
=== ExecPkgTaskQry

[cols="d,8a,m,m,m"]
|===
|
|ExecPkgTaskQry
|xml
|NULL
|
|===


[#column-expressionvalue]
=== ExpressionValue

[cols="d,8a,m,m,m"]
|===
|
|ExpressionValue
|varchar(5000)
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packagetask_src.adoc#column-expressionvalue[+ssis.PackageTask_src.ExpressionValue+]
--


[#column-isdisabled]
=== IsDisabled

[cols="d,8a,m,m,m"]
|===
|
|IsDisabled
|varchar(10)
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packagetask_src.adoc#column-isdisabled[+ssis.PackageTask_src.IsDisabled+]
--


[#column-rowid]
=== RowID

[cols="d,8a,m,m,m"]
|===
|
|RowID
|int
|NULL
|
|===

.Referencing Columns
--
* xref:ssis_t.tbltask_dft_component_src.adoc#column-rowid[+ssis_t.TblTask_Dft_Component_src.RowID+]
* xref:ssis_t.tbltask_dft_details_src.adoc#column-rowid[+ssis_t.TblTask_Dft_Details_src.RowID+]
* xref:ssis_t.tbltask_script_src.adoc#column-rowid[+ssis_t.TblTask_Script_src.RowID+]
* xref:ssis_t.tbltask_sql_src.adoc#column-rowid[+ssis_t.TblTask_Sql_src.RowID+]
--


[#column-scripttaskqry]
=== ScriptTaskQry

[cols="d,8a,m,m,m"]
|===
|
|ScriptTaskQry
|xml
|NULL
|
|===


[#column-sqltaskqry]
=== SqlTaskQry

[cols="d,8a,m,m,m"]
|===
|
|SqlTaskQry
|xml
|NULL
|
|===


[#column-taskdescription]
=== TaskDescription

[cols="d,8a,m,m,m"]
|===
|
|TaskDescription
|varchar(max)
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packagetask_src.adoc#column-taskdescription[+ssis.PackageTask_src.TaskDescription+]
--


[#column-taskname]
=== TaskName

[cols="d,8a,m,m,m"]
|===
|
|TaskName
|varchar(2000)
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packagetask_src.adoc#column-taskname[+ssis.PackageTask_src.TaskName+]
--


[#column-taskpath]
=== TaskPath

[cols="d,8a,m,m,m"]
|===
|
|TaskPath
|varchar(8000)
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_input_externalmetadatacolumn_src.adoc#column-taskpath[+ssis.PackageTask_Dft_Component_input_externalMetadataColumn_src.TaskPath+]
* xref:ssis.packagetask_dft_component_input_inputcolumn_src.adoc#column-taskpath[+ssis.PackageTask_Dft_Component_input_inputColumn_src.TaskPath+]
* xref:ssis.packagetask_dft_component_input_src.adoc#column-taskpath[+ssis.PackageTask_Dft_Component_input_src.TaskPath+]
* xref:ssis.packagetask_dft_component_output_externalmetadatacolumn_src.adoc#column-taskpath[+ssis.PackageTask_Dft_Component_output_externalMetadataColumn_src.TaskPath+]
* xref:ssis.packagetask_dft_component_output_outputcolumn_src.adoc#column-taskpath[+ssis.PackageTask_Dft_Component_output_outputcolumn_src.TaskPath+]
* xref:ssis.packagetask_dft_component_output_src.adoc#column-taskpath[+ssis.PackageTask_Dft_Component_output_src.TaskPath+]
* xref:ssis.packagetask_dft_component_src.adoc#column-taskpath[+ssis.PackageTask_Dft_Component_src.TaskPath+]
* xref:ssis.packagetask_sql_parameter_src.adoc#column-taskpath[+ssis.PackageTask_Sql_Parameter_src.TaskPath+]
* xref:ssis.packagetask_src.adoc#column-taskpath[+ssis.PackageTask_src.TaskPath+]
--


[#column-tasktype]
=== TaskType

[cols="d,8a,m,m,m"]
|===
|
|TaskType
|varchar(5000)
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packagetask_src.adoc#column-tasktype[+ssis.PackageTask_src.TaskType+]
--


// end::AntoraColumnDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]
|1
|*<<column-controlflowdetailsrowid>>*
|int
|NOT NULL
|(1,1)













// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]

|
|<<column-delayvalidationpropertyvalue>>
|varchar(100)
|NULL
|

|
|<<column-dftquery>>
|xml
|NULL
|

|
|<<column-execpkgtaskqry>>
|xml
|NULL
|

|
|<<column-expressionvalue>>
|varchar(5000)
|NULL
|

|
|<<column-isdisabled>>
|varchar(10)
|NULL
|

|
|<<column-rowid>>
|int
|NULL
|

|
|<<column-scripttaskqry>>
|xml
|NULL
|

|
|<<column-sqltaskqry>>
|xml
|NULL
|

|
|<<column-taskdescription>>
|varchar(max)
|NULL
|

|
|<<column-taskname>>
|varchar(2000)
|NULL
|

|
|<<column-taskpath>>
|varchar(8000)
|NULL
|

|
|<<column-tasktype>>
|varchar(5000)
|NULL
|

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

[#index-pkunderlinetblcontrolflow]
=== PK_TblControlFlow

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-ControlFlowDetailsRowID>>; int
--
* PK, Unique, Real: 1, 1, 1

// end::AntoraIndexList[]

== AntoraMeasureDetails

// tag::AntoraMeasureDetails[]

// end::AntoraMeasureDetails[]

== AntoraMeasureDescriptions



== AntoraParameterList

// tag::AntoraParameterList[]

// end::AntoraParameterList[]

== AntoraXrefCulturesList

// tag::AntoraXrefCulturesList[]
* xref:dhw:sqldb:ssis_t.tblcontrolflow.adoc[] - 
// end::AntoraXrefCulturesList[]

== cultures_count

// tag::cultures_count[]
1
// end::cultures_count[]

== Other tags

source: property.RepoObjectProperty_cross As rop_cross


=== additional_reference_csv

// tag::additional_reference_csv[]

// end::additional_reference_csv[]


=== AdocUspSteps

// tag::adocuspsteps[]

// end::adocuspsteps[]


=== AntoraReferencedList

// tag::antorareferencedlist[]

// end::antorareferencedlist[]


=== AntoraReferencingList

// tag::antorareferencinglist[]
* xref:dhw:sqldb:ssis.packagetask_dft_component_input_externalmetadatacolumn_src.adoc[]
* xref:dhw:sqldb:ssis.packagetask_dft_component_input_inputcolumn_src.adoc[]
* xref:dhw:sqldb:ssis.packagetask_dft_component_input_src.adoc[]
* xref:dhw:sqldb:ssis.packagetask_dft_component_output_externalmetadatacolumn_src.adoc[]
* xref:dhw:sqldb:ssis.packagetask_dft_component_output_outputcolumn_src.adoc[]
* xref:dhw:sqldb:ssis.packagetask_dft_component_output_src.adoc[]
* xref:dhw:sqldb:ssis.packagetask_dft_component_src.adoc[]
* xref:dhw:sqldb:ssis.packagetask_sql_parameter_src.adoc[]
* xref:dhw:sqldb:ssis.packagetask_src.adoc[]
* xref:dhw:sqldb:ssis_t.tbltask_dft_component_src.adoc[]
* xref:dhw:sqldb:ssis_t.tbltask_dft_details_src.adoc[]
* xref:dhw:sqldb:ssis_t.tbltask_script_src.adoc[]
* xref:dhw:sqldb:ssis_t.tbltask_sql_src.adoc[]
* xref:dhw:sqldb:ssis_t.usp_getpackagedetails.adoc[]
* xref:dhw:sqldb:ssis_t.usp_packageanalysis.adoc[]
// end::antorareferencinglist[]


=== Description

// tag::description[]

// end::description[]


=== exampleUsage

// tag::exampleusage[]

// end::exampleusage[]


=== exampleUsage_2

// tag::exampleusage_2[]

// end::exampleusage_2[]


=== exampleUsage_3

// tag::exampleusage_3[]

// end::exampleusage_3[]


=== exampleUsage_4

// tag::exampleusage_4[]

// end::exampleusage_4[]


=== exampleUsage_5

// tag::exampleusage_5[]

// end::exampleusage_5[]


=== exampleWrong_Usage

// tag::examplewrong_usage[]

// end::examplewrong_usage[]


=== has_execution_plan_issue

// tag::has_execution_plan_issue[]

// end::has_execution_plan_issue[]


=== has_get_referenced_issue

// tag::has_get_referenced_issue[]

// end::has_get_referenced_issue[]


=== has_history

// tag::has_history[]

// end::has_history[]


=== has_history_columns

// tag::has_history_columns[]

// end::has_history_columns[]


=== InheritanceType

// tag::inheritancetype[]

// end::inheritancetype[]


=== is_persistence

// tag::is_persistence[]

// end::is_persistence[]


=== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]

// end::is_persistence_check_duplicate_per_pk[]


=== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]

// end::is_persistence_check_for_empty_source[]


=== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]

// end::is_persistence_delete_changed[]


=== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]

// end::is_persistence_delete_missing[]


=== is_persistence_insert

// tag::is_persistence_insert[]

// end::is_persistence_insert[]


=== is_persistence_truncate

// tag::is_persistence_truncate[]

// end::is_persistence_truncate[]


=== is_persistence_update_changed

// tag::is_persistence_update_changed[]

// end::is_persistence_update_changed[]


=== is_repo_managed

// tag::is_repo_managed[]
0
// end::is_repo_managed[]


=== is_ssas

// tag::is_ssas[]
0
// end::is_ssas[]


=== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


=== MS_Description

// tag::ms_description[]

// end::ms_description[]


=== persistence_source_RepoObject_fullname

// tag::persistence_source_repoobject_fullname[]

// end::persistence_source_repoobject_fullname[]


=== persistence_source_RepoObject_fullname2

// tag::persistence_source_repoobject_fullname2[]

// end::persistence_source_repoobject_fullname2[]


=== persistence_source_RepoObject_guid

// tag::persistence_source_repoobject_guid[]

// end::persistence_source_repoobject_guid[]


=== persistence_source_RepoObject_xref

// tag::persistence_source_repoobject_xref[]

// end::persistence_source_repoobject_xref[]


=== pk_index_guid

// tag::pk_index_guid[]
7664FBE4-113B-EC11-852C-A81E8446D5B0
// end::pk_index_guid[]


=== pk_IndexPatternColumnDatatype

// tag::pk_indexpatterncolumndatatype[]
int
// end::pk_indexpatterncolumndatatype[]


=== pk_IndexPatternColumnName

// tag::pk_indexpatterncolumnname[]
ControlFlowDetailsRowID
// end::pk_indexpatterncolumnname[]


=== pk_IndexSemanticGroup

// tag::pk_indexsemanticgroup[]

// end::pk_indexsemanticgroup[]


=== ReferencedObjectList

// tag::referencedobjectlist[]

// end::referencedobjectlist[]


=== usp_persistence_RepoObject_guid

// tag::usp_persistence_repoobject_guid[]

// end::usp_persistence_repoobject_guid[]


=== UspExamples

// tag::uspexamples[]

// end::uspexamples[]


=== uspgenerator_usp_id

// tag::uspgenerator_usp_id[]

// end::uspgenerator_usp_id[]


=== UspParameters

// tag::uspparameters[]

// end::uspparameters[]

== Boolean Attributes

source: property.RepoObjectProperty WHERE property_int = 1

// tag::boolean_attributes[]


// end::boolean_attributes[]

== PlantUML diagrams

=== PlantUML Entity

// tag::puml_entity[]
[plantuml, entity-{docname}, svg, subs=macros]
....
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis_t.tblcontrolflow.adoc[]" as ssis_t.TblControlFlow << U >> {
  - **ControlFlowDetailsRowID** : (int)
  DelayValidationPropertyValue : (varchar(100))
  DFTQuery : (xml)
  ExecPkgTaskQry : (xml)
  ExpressionValue : (varchar(5000))
  IsDisabled : (varchar(10))
  RowID : (int)
  ScriptTaskQry : (xml)
  SqlTaskQry : (xml)
  TaskDescription : (varchar(max))
  TaskName : (varchar(2000))
  TaskPath : (varchar(8000))
  TaskType : (varchar(5000))
  --
}
....

// end::puml_entity[]

=== PlantUML Entity 1 1 FK

// tag::puml_entity_1_1_fk[]
[plantuml, entity_1_1_fk-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis_t.tblcontrolflow.adoc[]" as ssis_t.TblControlFlow << U >> {
**PK_TblControlFlow**

..
ControlFlowDetailsRowID; int
}



footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_fk[]

=== PlantUML 1 1 ObjectRef

// tag::puml_entity_1_1_objectref[]
[plantuml, entity_1_1_objectref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_input_externalmetadatacolumn_src.adoc[]" as ssis.PackageTask_Dft_Component_input_externalMetadataColumn_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Column_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_input_inputcolumn_src.adoc[]" as ssis.PackageTask_Dft_Component_input_inputColumn_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Column_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_input_src.adoc[]" as ssis.PackageTask_Dft_Component_input_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **input_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_output_externalmetadatacolumn_src.adoc[]" as ssis.PackageTask_Dft_Component_output_externalMetadataColumn_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Column_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_output_outputcolumn_src.adoc[]" as ssis.PackageTask_Dft_Component_output_outputcolumn_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Column_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_output_src.adoc[]" as ssis.PackageTask_Dft_Component_output_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **output_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_src.adoc[]" as ssis.PackageTask_Dft_Component_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Component_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_sql_parameter_src.adoc[]" as ssis.PackageTask_Sql_Parameter_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **TaskPath** : (varchar(8000))
  **ParameterBindingSequence** : (varchar(1000))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_src.adoc[]" as ssis.PackageTask_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **TaskPath** : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tblcontrolflow.adoc[]" as ssis_t.TblControlFlow << U >> {
  - **ControlFlowDetailsRowID** : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_dft_component_src.adoc[]" as ssis_t.TblTask_Dft_Component_src << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_dft_details_src.adoc[]" as ssis_t.TblTask_Dft_Details_src << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_script_src.adoc[]" as ssis_t.TblTask_Script_src << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_sql_src.adoc[]" as ssis_t.TblTask_Sql_src << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.usp_getpackagedetails.adoc[]" as ssis_t.usp_GetPackageDetails << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.usp_packageanalysis.adoc[]" as ssis_t.usp_PackageAnalysis << P >> {
  --
}

ssis_t.TblControlFlow <.. ssis_t.usp_GetPackageDetails
ssis_t.TblControlFlow <.. ssis.PackageTask_src
ssis_t.TblControlFlow <.. ssis_t.TblTask_Dft_Details_src
ssis_t.TblControlFlow <.. ssis.PackageTask_Sql_Parameter_src
ssis_t.TblControlFlow <.. ssis_t.TblTask_Script_src
ssis_t.TblControlFlow <.. ssis_t.TblTask_Sql_src
ssis_t.TblControlFlow <.. ssis_t.usp_PackageAnalysis
ssis_t.TblControlFlow <.. ssis_t.TblTask_Dft_Component_src
ssis_t.TblControlFlow <.. ssis.PackageTask_Dft_Component_src
ssis_t.TblControlFlow <.. ssis.PackageTask_Dft_Component_input_inputColumn_src
ssis_t.TblControlFlow <.. ssis.PackageTask_Dft_Component_input_externalMetadataColumn_src
ssis_t.TblControlFlow <.. ssis.PackageTask_Dft_Component_input_src
ssis_t.TblControlFlow <.. ssis.PackageTask_Dft_Component_output_src
ssis_t.TblControlFlow <.. ssis.PackageTask_Dft_Component_output_outputcolumn_src
ssis_t.TblControlFlow <.. ssis.PackageTask_Dft_Component_output_externalMetadataColumn_src

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_objectref[]

=== PlantUML 30 0 ObjectRef

// tag::puml_entity_30_0_objectref[]
[plantuml, entity_30_0_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis_t.tblcontrolflow.adoc[]" as ssis_t.TblControlFlow << U >> {
  - **ControlFlowDetailsRowID** : (int)
  --
}



footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_30_0_objectref[]

=== PlantUML 0 30 ObjectRef

// tag::puml_entity_0_30_objectref[]
[plantuml, entity_0_30_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:docs.ssis_adoc.adoc[]" as docs.ssis_Adoc << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageBasename** : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_adoc_t.adoc[]" as docs.ssis_Adoc_T << U >> {
  - **AntoraModule** : (varchar(50))
  **PackageBasename** : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_dfttaskcomponentinputcolumnlist.adoc[]" as docs.ssis_DftTaskComponentInputColumnList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_dfttaskcomponentinputlist.adoc[]" as docs.ssis_DftTaskComponentInputList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_dfttaskcomponentlist.adoc[]" as docs.ssis_DftTaskComponentList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_dfttaskcomponentoutputcolumnlist.adoc[]" as docs.ssis_DftTaskComponentOutputColumnList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_dfttaskcomponentoutputlist.adoc[]" as docs.ssis_DftTaskComponentOutputList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_pumldfttask.adoc[]" as docs.ssis_PumlDftTask << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_pumlpackage.adoc[]" as docs.ssis_PumlPackage << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_pumlpartialdftcomponent.adoc[]" as docs.ssis_PumlPartialDftComponent << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_pumlpartialtaskcomponent.adoc[]" as docs.ssis_PumlPartialTaskComponent << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_sqltaskparameterinnertable.adoc[]" as docs.ssis_SqlTaskParameterInnerTable << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_task.adoc[]" as docs.ssis_Task << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_tasklist.adoc[]" as docs.ssis_TaskList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport.adoc[]" as docs.usp_AntoraExport << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_ssispartialscontent.adoc[]" as docs.usp_AntoraExport_SsisPartialsContent << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_ssis_adoc_t.adoc[]" as docs.usp_PERSIST_ssis_Adoc_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask.adoc[]" as ssis.PackageTask << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component.adoc[]" as ssis.PackageTask_Dft_Component << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_input.adoc[]" as ssis.PackageTask_Dft_Component_input << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_input_externalmetadatacolumn.adoc[]" as ssis.PackageTask_Dft_Component_input_externalMetadataColumn << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_input_externalmetadatacolumn_src.adoc[]" as ssis.PackageTask_Dft_Component_input_externalMetadataColumn_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Column_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_input_externalmetadatacolumn_tgt.adoc[]" as ssis.PackageTask_Dft_Component_input_externalMetadataColumn_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Column_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_input_inputcolumn.adoc[]" as ssis.PackageTask_Dft_Component_input_inputColumn << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_input_inputcolumn_src.adoc[]" as ssis.PackageTask_Dft_Component_input_inputColumn_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Column_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_input_inputcolumn_tgt.adoc[]" as ssis.PackageTask_Dft_Component_input_inputColumn_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Column_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_input_src.adoc[]" as ssis.PackageTask_Dft_Component_input_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **input_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_input_tgt.adoc[]" as ssis.PackageTask_Dft_Component_input_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **input_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_output.adoc[]" as ssis.PackageTask_Dft_Component_output << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_output_externalmetadatacolumn.adoc[]" as ssis.PackageTask_Dft_Component_output_externalMetadataColumn << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_output_externalmetadatacolumn_src.adoc[]" as ssis.PackageTask_Dft_Component_output_externalMetadataColumn_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Column_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_output_externalmetadatacolumn_tgt.adoc[]" as ssis.PackageTask_Dft_Component_output_externalMetadataColumn_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Column_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_output_outputcolumn.adoc[]" as ssis.PackageTask_Dft_Component_output_outputcolumn << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_output_outputcolumn_src.adoc[]" as ssis.PackageTask_Dft_Component_output_outputcolumn_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Column_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_output_outputcolumn_tgt.adoc[]" as ssis.PackageTask_Dft_Component_output_outputColumn_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Column_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_output_src.adoc[]" as ssis.PackageTask_Dft_Component_output_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **output_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_output_tgt.adoc[]" as ssis.PackageTask_Dft_Component_output_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **output_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_src.adoc[]" as ssis.PackageTask_Dft_Component_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Component_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_tgt.adoc[]" as ssis.PackageTask_Dft_Component_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Component_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_levellaglead.adoc[]" as ssis.PackageTask_LevelLagLead << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_sql_parameter.adoc[]" as ssis.PackageTask_Sql_Parameter << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_sql_parameter_src.adoc[]" as ssis.PackageTask_Sql_Parameter_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **TaskPath** : (varchar(8000))
  **ParameterBindingSequence** : (varchar(1000))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_sql_parameter_tgt.adoc[]" as ssis.PackageTask_Sql_Parameter_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **TaskPath** : (varchar(8000))
  **ParameterBindingSequence** : (varchar(1000))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_src.adoc[]" as ssis.PackageTask_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **TaskPath** : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_tgt.adoc[]" as ssis.PackageTask_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **TaskPath** : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_import.adoc[]" as ssis.usp_import << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packagetask_dft_component_input_externalmetadatacolumn_tgt.adoc[]" as ssis.usp_PERSIST_PackageTask_Dft_Component_input_externalMetadataColumn_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packagetask_dft_component_input_inputcolumn_tgt.adoc[]" as ssis.usp_PERSIST_PackageTask_Dft_Component_input_inputColumn_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packagetask_dft_component_input_tgt.adoc[]" as ssis.usp_PERSIST_PackageTask_Dft_Component_input_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packagetask_dft_component_output_externalmetadatacolumn_tgt.adoc[]" as ssis.usp_PERSIST_PackageTask_Dft_Component_output_externalMetadataColumn_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packagetask_dft_component_output_outputcolumn_tgt.adoc[]" as ssis.usp_PERSIST_PackageTask_Dft_Component_output_outputColumn_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packagetask_dft_component_output_tgt.adoc[]" as ssis.usp_PERSIST_PackageTask_Dft_Component_output_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packagetask_dft_component_tgt.adoc[]" as ssis.usp_PERSIST_PackageTask_Dft_Component_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packagetask_sql_parameter_tgt.adoc[]" as ssis.usp_PERSIST_PackageTask_Sql_Parameter_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packagetask_tgt.adoc[]" as ssis.usp_PERSIST_PackageTask_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tblcontrolflow.adoc[]" as ssis_t.TblControlFlow << U >> {
  - **ControlFlowDetailsRowID** : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_dft_component_src.adoc[]" as ssis_t.TblTask_Dft_Component_src << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_dft_details_src.adoc[]" as ssis_t.TblTask_Dft_Details_src << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_script_src.adoc[]" as ssis_t.TblTask_Script_src << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_sql_src.adoc[]" as ssis_t.TblTask_Sql_src << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.usp_getpackagedetails.adoc[]" as ssis_t.usp_GetPackageDetails << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.usp_packageanalysis.adoc[]" as ssis_t.usp_PackageAnalysis << P >> {
  --
}

docs.ssis_Adoc <.. docs.ssis_Adoc_T
docs.ssis_Adoc <.. docs.usp_PERSIST_ssis_Adoc_T
docs.ssis_Adoc_T <.. docs.usp_PERSIST_ssis_Adoc_T
docs.ssis_Adoc_T <.. docs.usp_AntoraExport_SsisPartialsContent
docs.ssis_DftTaskComponentInputColumnList <.. docs.ssis_DftTaskComponentInputList
docs.ssis_DftTaskComponentInputList <.. docs.ssis_DftTaskComponentList
docs.ssis_DftTaskComponentList <.. docs.ssis_TaskList
docs.ssis_DftTaskComponentList <.. docs.ssis_Task
docs.ssis_DftTaskComponentOutputColumnList <.. docs.ssis_DftTaskComponentOutputList
docs.ssis_DftTaskComponentOutputList <.. docs.ssis_DftTaskComponentList
docs.ssis_PumlDftTask <.. docs.ssis_TaskList
docs.ssis_PumlDftTask <.. docs.ssis_Task
docs.ssis_PumlPackage <.. docs.ssis_Adoc
docs.ssis_PumlPartialDftComponent <.. docs.ssis_PumlDftTask
docs.ssis_PumlPartialDftComponent <.. docs.ssis_DftTaskComponentList
docs.ssis_PumlPartialTaskComponent <.. docs.ssis_PumlPackage
docs.ssis_SqlTaskParameterInnerTable <.. docs.ssis_Task
docs.ssis_SqlTaskParameterInnerTable <.. docs.ssis_TaskList
docs.ssis_TaskList <.. docs.ssis_Adoc
docs.usp_AntoraExport_SsisPartialsContent <.. docs.usp_AntoraExport
docs.usp_PERSIST_ssis_Adoc_T <.. docs.usp_AntoraExport_SsisPartialsContent
ssis.PackageTask <.. docs.ssis_Task
ssis.PackageTask <.. ssis.PackageTask_LevelLagLead
ssis.PackageTask <.. docs.ssis_TaskList
ssis.PackageTask_Dft_Component <.. docs.ssis_PumlPartialDftComponent
ssis.PackageTask_Dft_Component <.. docs.ssis_DftTaskComponentList
ssis.PackageTask_Dft_Component <.. docs.ssis_PumlDftTask
ssis.PackageTask_Dft_Component_input <.. docs.ssis_DftTaskComponentInputList
ssis.PackageTask_Dft_Component_input_externalMetadataColumn <.. docs.ssis_DftTaskComponentOutputColumnList
ssis.PackageTask_Dft_Component_input_externalMetadataColumn <.. docs.ssis_DftTaskComponentInputColumnList
ssis.PackageTask_Dft_Component_input_externalMetadataColumn_src <.. ssis.PackageTask_Dft_Component_input_externalMetadataColumn_tgt
ssis.PackageTask_Dft_Component_input_externalMetadataColumn_src <.. ssis.usp_PERSIST_PackageTask_Dft_Component_input_externalMetadataColumn_tgt
ssis.PackageTask_Dft_Component_input_externalMetadataColumn_tgt <.. ssis.PackageTask_Dft_Component_input_externalMetadataColumn
ssis.PackageTask_Dft_Component_input_externalMetadataColumn_tgt <.. ssis.usp_PERSIST_PackageTask_Dft_Component_input_externalMetadataColumn_tgt
ssis.PackageTask_Dft_Component_input_inputColumn <.. docs.ssis_DftTaskComponentInputColumnList
ssis.PackageTask_Dft_Component_input_inputColumn_src <.. ssis.usp_PERSIST_PackageTask_Dft_Component_input_inputColumn_tgt
ssis.PackageTask_Dft_Component_input_inputColumn_src <.. ssis.PackageTask_Dft_Component_input_inputColumn_tgt
ssis.PackageTask_Dft_Component_input_inputColumn_tgt <.. ssis.PackageTask_Dft_Component_input_inputColumn
ssis.PackageTask_Dft_Component_input_inputColumn_tgt <.. ssis.usp_PERSIST_PackageTask_Dft_Component_input_inputColumn_tgt
ssis.PackageTask_Dft_Component_input_src <.. ssis.usp_PERSIST_PackageTask_Dft_Component_input_tgt
ssis.PackageTask_Dft_Component_input_src <.. ssis.PackageTask_Dft_Component_input_tgt
ssis.PackageTask_Dft_Component_input_tgt <.. ssis.usp_PERSIST_PackageTask_Dft_Component_input_tgt
ssis.PackageTask_Dft_Component_input_tgt <.. ssis.PackageTask_Dft_Component_input
ssis.PackageTask_Dft_Component_output <.. docs.ssis_DftTaskComponentOutputList
ssis.PackageTask_Dft_Component_output_externalMetadataColumn_src <.. ssis.usp_PERSIST_PackageTask_Dft_Component_output_externalMetadataColumn_tgt
ssis.PackageTask_Dft_Component_output_externalMetadataColumn_src <.. ssis.PackageTask_Dft_Component_output_externalMetadataColumn_tgt
ssis.PackageTask_Dft_Component_output_externalMetadataColumn_tgt <.. ssis.PackageTask_Dft_Component_output_externalMetadataColumn
ssis.PackageTask_Dft_Component_output_externalMetadataColumn_tgt <.. ssis.usp_PERSIST_PackageTask_Dft_Component_output_externalMetadataColumn_tgt
ssis.PackageTask_Dft_Component_output_outputcolumn <.. docs.ssis_DftTaskComponentOutputColumnList
ssis.PackageTask_Dft_Component_output_outputcolumn_src <.. ssis.usp_PERSIST_PackageTask_Dft_Component_output_outputColumn_tgt
ssis.PackageTask_Dft_Component_output_outputcolumn_src <.. ssis.PackageTask_Dft_Component_output_outputcolumn_tgt
ssis.PackageTask_Dft_Component_output_outputcolumn_tgt <.. ssis.PackageTask_Dft_Component_output_outputcolumn
ssis.PackageTask_Dft_Component_output_outputColumn_tgt <.. ssis.usp_PERSIST_PackageTask_Dft_Component_output_outputColumn_tgt
ssis.PackageTask_Dft_Component_output_src <.. ssis.usp_PERSIST_PackageTask_Dft_Component_output_tgt
ssis.PackageTask_Dft_Component_output_src <.. ssis.PackageTask_Dft_Component_output_tgt
ssis.PackageTask_Dft_Component_output_tgt <.. ssis.PackageTask_Dft_Component_output
ssis.PackageTask_Dft_Component_output_tgt <.. ssis.usp_PERSIST_PackageTask_Dft_Component_output_tgt
ssis.PackageTask_Dft_Component_src <.. ssis.usp_PERSIST_PackageTask_Dft_Component_tgt
ssis.PackageTask_Dft_Component_src <.. ssis.PackageTask_Dft_Component_tgt
ssis.PackageTask_Dft_Component_tgt <.. ssis.PackageTask_Dft_Component
ssis.PackageTask_Dft_Component_tgt <.. ssis.usp_PERSIST_PackageTask_Dft_Component_tgt
ssis.PackageTask_LevelLagLead <.. docs.ssis_PumlPartialTaskComponent
ssis.PackageTask_Sql_Parameter <.. docs.ssis_SqlTaskParameterInnerTable
ssis.PackageTask_Sql_Parameter_src <.. ssis.PackageTask_Sql_Parameter_tgt
ssis.PackageTask_Sql_Parameter_src <.. ssis.usp_PERSIST_PackageTask_Sql_Parameter_tgt
ssis.PackageTask_Sql_Parameter_tgt <.. ssis.PackageTask_Sql_Parameter
ssis.PackageTask_Sql_Parameter_tgt <.. ssis.usp_PERSIST_PackageTask_Sql_Parameter_tgt
ssis.PackageTask_src <.. ssis.PackageTask_tgt
ssis.PackageTask_src <.. ssis.usp_PERSIST_PackageTask_tgt
ssis.PackageTask_tgt <.. ssis.PackageTask
ssis.PackageTask_tgt <.. ssis.usp_PERSIST_PackageTask_tgt
ssis.usp_PERSIST_PackageTask_Dft_Component_input_externalMetadataColumn_tgt <.. ssis.usp_import
ssis.usp_PERSIST_PackageTask_Dft_Component_input_inputColumn_tgt <.. ssis.usp_import
ssis.usp_PERSIST_PackageTask_Dft_Component_input_tgt <.. ssis.usp_import
ssis.usp_PERSIST_PackageTask_Dft_Component_output_externalMetadataColumn_tgt <.. ssis.usp_import
ssis.usp_PERSIST_PackageTask_Dft_Component_output_outputColumn_tgt <.. ssis.usp_import
ssis.usp_PERSIST_PackageTask_Dft_Component_output_tgt <.. ssis.usp_import
ssis.usp_PERSIST_PackageTask_Dft_Component_tgt <.. ssis.usp_import
ssis.usp_PERSIST_PackageTask_Sql_Parameter_tgt <.. ssis.usp_import
ssis.usp_PERSIST_PackageTask_tgt <.. ssis.usp_import
ssis_t.TblControlFlow <.. ssis_t.usp_GetPackageDetails
ssis_t.TblControlFlow <.. ssis.PackageTask_Sql_Parameter_src
ssis_t.TblControlFlow <.. ssis.PackageTask_src
ssis_t.TblControlFlow <.. ssis_t.TblTask_Dft_Details_src
ssis_t.TblControlFlow <.. ssis_t.TblTask_Script_src
ssis_t.TblControlFlow <.. ssis_t.TblTask_Sql_src
ssis_t.TblControlFlow <.. ssis_t.usp_PackageAnalysis
ssis_t.TblControlFlow <.. ssis_t.TblTask_Dft_Component_src
ssis_t.TblControlFlow <.. ssis.PackageTask_Dft_Component_src
ssis_t.TblControlFlow <.. ssis.PackageTask_Dft_Component_input_src
ssis_t.TblControlFlow <.. ssis.PackageTask_Dft_Component_output_src
ssis_t.TblControlFlow <.. ssis.PackageTask_Dft_Component_output_outputcolumn_src
ssis_t.TblControlFlow <.. ssis.PackageTask_Dft_Component_output_externalMetadataColumn_src
ssis_t.TblControlFlow <.. ssis.PackageTask_Dft_Component_input_inputColumn_src
ssis_t.TblControlFlow <.. ssis.PackageTask_Dft_Component_input_externalMetadataColumn_src
ssis_t.TblTask_Dft_Component_src <.. ssis_t.usp_GetPackageDetails
ssis_t.TblTask_Script_src <.. ssis_t.usp_GetPackageDetails
ssis_t.TblTask_Sql_src <.. ssis_t.usp_GetPackageDetails

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_0_30_objectref[]

=== PlantUML 1 1 ColumnRef

// tag::puml_entity_1_1_colref[]
[plantuml, entity_1_1_colref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_input_externalmetadatacolumn_src.adoc[]" as ssis.PackageTask_Dft_Component_input_externalMetadataColumn_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Column_refId** : (varchar(max))
  Column_dataType : (varchar(100))
  Column_length : (int)
  Column_name : (varchar(max))
  Column_precision : (int)
  Column_scale : (int)
  Component_refId : (varchar(max))
  - ControlFlowDetailsRowID : (int)
  externalMetadataColumns_isused : (bit)
  input_errorOrTruncationOperation : (varchar(100))
  input_errorRowDisposition : (varchar(100))
  input_hasSideEffects : (bit)
  input_name : (varchar(500))
  input_refId : (varchar(max))
  TaskPath : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_input_inputcolumn_src.adoc[]" as ssis.PackageTask_Dft_Component_input_inputColumn_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Column_refId** : (varchar(max))
  Column_cachedDataType : (varchar(100))
  Column_cachedName : (varchar(max))
  Column_externalMetadataColumnId : (varchar(max))
  Column_lineageId : (varchar(max))
  Component_refId : (varchar(max))
  - ControlFlowDetailsRowID : (int)
  input_errorOrTruncationOperation : (varchar(100))
  input_errorRowDisposition : (varchar(100))
  input_hasSideEffects : (bit)
  input_name : (varchar(500))
  input_refId : (varchar(max))
  TaskPath : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_input_src.adoc[]" as ssis.PackageTask_Dft_Component_input_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **input_refId** : (varchar(max))
  Component_refId : (varchar(max))
  - ControlFlowDetailsRowID : (int)
  input_errorOrTruncationOperation : (varchar(100))
  input_errorRowDisposition : (varchar(100))
  input_hasSideEffects : (bit)
  input_name : (varchar(500))
  TaskPath : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_output_externalmetadatacolumn_src.adoc[]" as ssis.PackageTask_Dft_Component_output_externalMetadataColumn_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Column_refId** : (varchar(max))
  Column_dataType : (varchar(100))
  Column_length : (int)
  Column_name : (varchar(max))
  Column_precision : (int)
  Column_scale : (int)
  Component_refId : (varchar(max))
  - ControlFlowDetailsRowID : (int)
  externalMetadataColumns_isused : (bit)
  output_name : (varchar(500))
  output_refId : (varchar(max))
  TaskPath : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_output_outputcolumn_src.adoc[]" as ssis.PackageTask_Dft_Component_output_outputcolumn_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Column_refId** : (varchar(max))
  Column_dataType : (varchar(100))
  Column_errorOrTruncationOperation : (varchar(100))
  Column_errorRowDisposition : (varchar(100))
  Column_externalMetadataColumnId : (varchar(max))
  Column_length : (int)
  Column_lineageId : (varchar(max))
  Column_name : (varchar(max))
  Column_precision : (int)
  Column_scale : (int)
  Column_truncationRowDisposition : (varchar(max))
  Component_refId : (varchar(max))
  - ControlFlowDetailsRowID : (int)
  output_isErrorOut : (bit)
  output_name : (varchar(500))
  output_refId : (varchar(max))
  TaskPath : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_output_src.adoc[]" as ssis.PackageTask_Dft_Component_output_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **output_refId** : (varchar(max))
  Component_refId : (varchar(max))
  - ControlFlowDetailsRowID : (int)
  output_isErrorOut : (bit)
  output_name : (varchar(500))
  TaskPath : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_src.adoc[]" as ssis.PackageTask_Dft_Component_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Component_refId** : (varchar(max))
  Component_AccessMode : (varchar(max))
  Component_AlwaysUseDefaultCodePage : (varchar(max))
  Component_CommandTimeout : (int)
  Component_componentClassID : (varchar(max))
  Component_Connection_description : (varchar(max))
  Component_Connection_name : (varchar(max))
  Component_Connection_refId : (varchar(max))
  Component_connectionManagerID : (varchar(max))
  Component_connectionManagerRefId : (varchar(max))
  Component_ContactInfo : (varchar(max))
  Component_DefaultCodePage : (int)
  Component_description : (varchar(max))
  Component_FastLoadKeepIdentity : (bit)
  Component_FastLoadKeepNulls : (bit)
  Component_FastLoadMaxInsertCommitSize : (int)
  Component_FastLoadOptions : (varchar(max))
  Component_IsSortedProperty : (varchar(10))
  Component_name : (varchar(max))
  Component_OpenRowset : (varchar(max))
  Component_OpenRowsetVariable : (varchar(max))
  Component_ParameterMapping : (varchar(max))
  Component_SqlCommand : (varchar(max))
  Component_SqlCommandVariable : (varchar(max))
  Component_VariableName : (varchar(max))
  - ControlFlowDetailsRowID : (int)
  TaskPath : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_sql_parameter_src.adoc[]" as ssis.PackageTask_Sql_Parameter_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **TaskPath** : (varchar(8000))
  **ParameterBindingSequence** : (varchar(1000))
  - ControlFlowDetailsRowID : (int)
  ParameterBindingParameterName : (varchar(1000))
  ResultSetParameterName : (varchar(1000))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_src.adoc[]" as ssis.PackageTask_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **TaskPath** : (varchar(8000))
  - ControlFlowDetailsRowID : (int)
  DelayValidationPropertyValue : (varchar(100))
  ExecutedPackageName : (varchar(1000))
  ExecutePackageConnection : (varchar(1000))
  ExecutePackageExpression : (varchar(1000))
  ExpressionValue : (varchar(5000))
  IsDisabled : (varchar(10))
  Script : (varchar(max))
  SqlConnection : (uniqueidentifier)
  SqlStatementSource : (nvarchar(max))
  TaskDescription : (varchar(max))
  TaskName : (varchar(2000))
  TaskType : (varchar(5000))
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tblcontrolflow.adoc[]" as ssis_t.TblControlFlow << U >> {
  - **ControlFlowDetailsRowID** : (int)
  DelayValidationPropertyValue : (varchar(100))
  DFTQuery : (xml)
  ExecPkgTaskQry : (xml)
  ExpressionValue : (varchar(5000))
  IsDisabled : (varchar(10))
  RowID : (int)
  ScriptTaskQry : (xml)
  SqlTaskQry : (xml)
  TaskDescription : (varchar(max))
  TaskName : (varchar(2000))
  TaskPath : (varchar(8000))
  TaskType : (varchar(5000))
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_dft_component_src.adoc[]" as ssis_t.TblTask_Dft_Component_src << V >> {
  AccessMode : (varchar(max))
  AlwaysUseDefaultCodePage : (varchar(max))
  CommandTimeout : (int)
  componentClassID : (varchar(max))
  Connection_description : (varchar(max))
  Connection_name : (varchar(max))
  Connection_refId : (varchar(max))
  connectionManagerID : (varchar(max))
  connectionManagerRefId : (varchar(max))
  ContactInfo : (varchar(max))
  - ControlFlowDetailsRowID : (int)
  DefaultCodePage : (int)
  description : (varchar(max))
  FastLoadKeepIdentity : (bit)
  FastLoadKeepNulls : (bit)
  FastLoadMaxInsertCommitSize : (int)
  FastLoadOptions : (varchar(max))
  inputsQry : (xml)
  IsSortedProperty : (varchar(10))
  name : (varchar(max))
  OpenRowset : (varchar(max))
  OpenRowsetVariable : (varchar(max))
  outputsQry : (xml)
  ParameterMapping : (varchar(max))
  refId : (varchar(max))
  RowID : (int)
  SqlCommand : (varchar(max))
  SqlCommandVariable : (varchar(max))
  VariableName : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_dft_details_src.adoc[]" as ssis_t.TblTask_Dft_Details_src << V >> {
  - ControlFlowDetailsRowID : (int)
  DFTConnectionManager : (varchar(max))
  DFTRowSet : (varchar(max))
  - DFTSQLCommand : (varchar(max))
  DFTTaskName : (varchar(max))
  DFTTasksPath : (varchar(max))
  DFTTaskType : (varchar(max))
  DFTTaskType1 : (varchar(max))
  InputQry : (xml)
  IsSortedProperty : (varchar(10))
  MultihashcolumnSortPosition : (varchar(max))
  OutputQry : (xml)
  ParameterBindingParameterName : (varchar(max))
  RowID : (int)
  Variable : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_script_src.adoc[]" as ssis_t.TblTask_Script_src << V >> {
  - ControlFlowDetailsRowID : (int)
  RowID : (int)
  Script : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_sql_src.adoc[]" as ssis_t.TblTask_Sql_src << V >> {
  - ControlFlowDetailsRowID : (int)
  RowID : (int)
  SqlConnection : (uniqueidentifier)
  SqlStatementSource : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis_t.usp_getpackagedetails.adoc[]" as ssis_t.usp_GetPackageDetails << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.usp_packageanalysis.adoc[]" as ssis_t.usp_PackageAnalysis << P >> {
  --
}

ssis_t.TblControlFlow <.. ssis_t.usp_GetPackageDetails
ssis_t.TblControlFlow <.. ssis.PackageTask_src
ssis_t.TblControlFlow <.. ssis_t.TblTask_Dft_Details_src
ssis_t.TblControlFlow <.. ssis.PackageTask_Sql_Parameter_src
ssis_t.TblControlFlow <.. ssis_t.TblTask_Script_src
ssis_t.TblControlFlow <.. ssis_t.TblTask_Sql_src
ssis_t.TblControlFlow <.. ssis_t.usp_PackageAnalysis
ssis_t.TblControlFlow <.. ssis_t.TblTask_Dft_Component_src
ssis_t.TblControlFlow <.. ssis.PackageTask_Dft_Component_src
ssis_t.TblControlFlow <.. ssis.PackageTask_Dft_Component_input_inputColumn_src
ssis_t.TblControlFlow <.. ssis.PackageTask_Dft_Component_input_externalMetadataColumn_src
ssis_t.TblControlFlow <.. ssis.PackageTask_Dft_Component_input_src
ssis_t.TblControlFlow <.. ssis.PackageTask_Dft_Component_output_src
ssis_t.TblControlFlow <.. ssis.PackageTask_Dft_Component_output_outputcolumn_src
ssis_t.TblControlFlow <.. ssis.PackageTask_Dft_Component_output_externalMetadataColumn_src
"ssis_t.TblControlFlow::ControlFlowDetailsRowID" <-- "ssis_t.TblTask_Dft_Component_src::ControlFlowDetailsRowID"
"ssis_t.TblControlFlow::ControlFlowDetailsRowID" <-- "ssis_t.TblTask_Script_src::ControlFlowDetailsRowID"
"ssis_t.TblControlFlow::ControlFlowDetailsRowID" <-- "ssis_t.TblTask_Sql_src::ControlFlowDetailsRowID"
"ssis_t.TblControlFlow::ControlFlowDetailsRowID" <-- "ssis_t.TblTask_Dft_Details_src::ControlFlowDetailsRowID"
"ssis_t.TblControlFlow::ControlFlowDetailsRowID" <-- "ssis.PackageTask_src::ControlFlowDetailsRowID"
"ssis_t.TblControlFlow::ControlFlowDetailsRowID" <-- "ssis.PackageTask_Sql_Parameter_src::ControlFlowDetailsRowID"
"ssis_t.TblControlFlow::ControlFlowDetailsRowID" <-- "ssis.PackageTask_Dft_Component_src::ControlFlowDetailsRowID"
"ssis_t.TblControlFlow::DelayValidationPropertyValue" <-- "ssis.PackageTask_src::DelayValidationPropertyValue"
"ssis_t.TblControlFlow::ExpressionValue" <-- "ssis.PackageTask_src::ExpressionValue"
"ssis_t.TblControlFlow::IsDisabled" <-- "ssis.PackageTask_src::IsDisabled"
"ssis_t.TblControlFlow::RowID" <-- "ssis_t.TblTask_Dft_Details_src::RowID"
"ssis_t.TblControlFlow::RowID" <-- "ssis_t.TblTask_Script_src::RowID"
"ssis_t.TblControlFlow::RowID" <-- "ssis_t.TblTask_Sql_src::RowID"
"ssis_t.TblControlFlow::RowID" <-- "ssis_t.TblTask_Dft_Component_src::RowID"
"ssis_t.TblControlFlow::TaskDescription" <-- "ssis.PackageTask_src::TaskDescription"
"ssis_t.TblControlFlow::TaskName" <-- "ssis.PackageTask_src::TaskName"
"ssis_t.TblControlFlow::TaskPath" <-- "ssis.PackageTask_src::TaskPath"
"ssis_t.TblControlFlow::TaskPath" <-- "ssis.PackageTask_Sql_Parameter_src::TaskPath"
"ssis_t.TblControlFlow::TaskPath" <-- "ssis.PackageTask_Dft_Component_src::TaskPath"
"ssis_t.TblControlFlow::TaskPath" <-- "ssis.PackageTask_Dft_Component_input_src::TaskPath"
"ssis_t.TblControlFlow::TaskPath" <-- "ssis.PackageTask_Dft_Component_output_src::TaskPath"
"ssis_t.TblControlFlow::TaskPath" <-- "ssis.PackageTask_Dft_Component_output_outputcolumn_src::TaskPath"
"ssis_t.TblControlFlow::TaskPath" <-- "ssis.PackageTask_Dft_Component_output_externalMetadataColumn_src::TaskPath"
"ssis_t.TblControlFlow::TaskPath" <-- "ssis.PackageTask_Dft_Component_input_inputColumn_src::TaskPath"
"ssis_t.TblControlFlow::TaskPath" <-- "ssis.PackageTask_Dft_Component_input_externalMetadataColumn_src::TaskPath"
"ssis_t.TblControlFlow::TaskType" <-- "ssis.PackageTask_src::TaskType"

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_colref[]


== sql_modules_definition

// tag::sql_modules_definition[]
[%collapsible]
=======
[source,sql,numbered,indent=0]
----

----
=======
// end::sql_modules_definition[]


