// tag::HeaderFullDisplayName[]
= ssis_t.TblPrecedenceConstraint_src - V
// end::HeaderFullDisplayName[]

== existing_properties

// tag::existing_properties[]

:ExistsProperty--antorareferencedlist:
:ExistsProperty--antorareferencinglist:
:ExistsProperty--is_repo_managed:
:ExistsProperty--is_ssas:
:ExistsProperty--referencedobjectlist:
:ExistsProperty--sql_modules_definition:
:ExistsProperty--FK:
:ExistsProperty--Columns:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
8364FBE4-113B-EC11-852C-A81E8446D5B0
// end::RepoObject_guid[]

== RepoObject_FullDisplayName2

// tag::RepoObject_FullDisplayName2[]
ssis_t.TblPrecedenceConstraint_src
// end::RepoObject_FullDisplayName2[]

== SysObject_type

// tag::SysObject_type[]
V 
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
view
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
322152243
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2021-11-01 13:46:40
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]
[discrete]
== _


[#column-creationname]
=== CreationName

[cols="d,8a,m,m,m"]
|===
|
|CreationName
|nvarchar(max)
|NULL
|
|===


[#column-dtsid]
=== DTSID

[cols="d,8a,m,m,m"]
|===
|
|DTSID
|uniqueidentifier
|NULL
|
|===


[#column-evalop]
=== EvalOp

[cols="d,8a,m,m,m"]
|===
|
|EvalOp
|int
|NULL
|
|===


[#column-expression]
=== Expression

[cols="d,8a,m,m,m"]
|===
|
|Expression
|nvarchar(max)
|NULL
|
|===


[#column-flowtype]
=== FlowType

[cols="d,8a,m,m,m"]
|===
|
|FlowType
|varchar(12)
|NOT NULL
|
|===


[#column-logicaland]
=== LogicalAnd

[cols="d,8a,m,m,m"]
|===
|
|LogicalAnd
|bit
|NULL
|
|===


[#column-objectname]
=== ObjectName

[cols="d,8a,m,m,m"]
|===
|
|ObjectName
|nvarchar(max)
|NULL
|
|===


[#column-packagepath]
=== PackagePath

[cols="d,8a,m,m,m"]
|===
|
|PackagePath
|varchar(8000)
|NOT NULL
|
|===


[#column-rowid]
=== RowID

[cols="d,8a,m,m,m"]
|===
|
|RowID
|int
|NOT NULL
|
|===


[#column-taskfrom]
=== TaskFrom

[cols="d,8a,m,m,m"]
|===
|
|TaskFrom
|nvarchar(max)
|NULL
|
|===


[#column-taskto]
=== TaskTo

[cols="d,8a,m,m,m"]
|===
|
|TaskTo
|nvarchar(max)
|NULL
|
|===


// end::AntoraColumnDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]











// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]
|
|<<column-creationname>>
|nvarchar(max)
|NULL
|

|
|<<column-dtsid>>
|uniqueidentifier
|NULL
|

|
|<<column-evalop>>
|int
|NULL
|

|
|<<column-expression>>
|nvarchar(max)
|NULL
|

|
|<<column-flowtype>>
|varchar(12)
|NOT NULL
|

|
|<<column-logicaland>>
|bit
|NULL
|

|
|<<column-objectname>>
|nvarchar(max)
|NULL
|

|
|<<column-packagepath>>
|varchar(8000)
|NOT NULL
|

|
|<<column-rowid>>
|int
|NOT NULL
|

|
|<<column-taskfrom>>
|nvarchar(max)
|NULL
|

|
|<<column-taskto>>
|nvarchar(max)
|NULL
|

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

// end::AntoraIndexList[]

== AntoraMeasureDetails

// tag::AntoraMeasureDetails[]

// end::AntoraMeasureDetails[]

== AntoraMeasureDescriptions



== AntoraParameterList

// tag::AntoraParameterList[]

// end::AntoraParameterList[]

== AntoraXrefCulturesList

// tag::AntoraXrefCulturesList[]
* xref:dhw:sqldb:ssis_t.tblprecedenceconstraint_src.adoc[] - 
// end::AntoraXrefCulturesList[]

== cultures_count

// tag::cultures_count[]
1
// end::cultures_count[]

== Other tags

source: property.RepoObjectProperty_cross As rop_cross


=== additional_reference_csv

// tag::additional_reference_csv[]

// end::additional_reference_csv[]


=== AdocUspSteps

// tag::adocuspsteps[]

// end::adocuspsteps[]


=== AntoraReferencedList

// tag::antorareferencedlist[]
* xref:dhw:sqldb:ssis_t.pkgstats.adoc[]
// end::antorareferencedlist[]


=== AntoraReferencingList

// tag::antorareferencinglist[]
* xref:dhw:sqldb:ssis_t.usp_getpackagedetails.adoc[]
// end::antorareferencinglist[]


=== Description

// tag::description[]

// end::description[]


=== exampleUsage

// tag::exampleusage[]

// end::exampleusage[]


=== exampleUsage_2

// tag::exampleusage_2[]

// end::exampleusage_2[]


=== exampleUsage_3

// tag::exampleusage_3[]

// end::exampleusage_3[]


=== exampleUsage_4

// tag::exampleusage_4[]

// end::exampleusage_4[]


=== exampleUsage_5

// tag::exampleusage_5[]

// end::exampleusage_5[]


=== exampleWrong_Usage

// tag::examplewrong_usage[]

// end::examplewrong_usage[]


=== has_execution_plan_issue

// tag::has_execution_plan_issue[]

// end::has_execution_plan_issue[]


=== has_get_referenced_issue

// tag::has_get_referenced_issue[]

// end::has_get_referenced_issue[]


=== has_history

// tag::has_history[]

// end::has_history[]


=== has_history_columns

// tag::has_history_columns[]

// end::has_history_columns[]


=== InheritanceType

// tag::inheritancetype[]

// end::inheritancetype[]


=== is_persistence

// tag::is_persistence[]

// end::is_persistence[]


=== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]

// end::is_persistence_check_duplicate_per_pk[]


=== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]

// end::is_persistence_check_for_empty_source[]


=== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]

// end::is_persistence_delete_changed[]


=== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]

// end::is_persistence_delete_missing[]


=== is_persistence_insert

// tag::is_persistence_insert[]

// end::is_persistence_insert[]


=== is_persistence_truncate

// tag::is_persistence_truncate[]

// end::is_persistence_truncate[]


=== is_persistence_update_changed

// tag::is_persistence_update_changed[]

// end::is_persistence_update_changed[]


=== is_repo_managed

// tag::is_repo_managed[]
0
// end::is_repo_managed[]


=== is_ssas

// tag::is_ssas[]
0
// end::is_ssas[]


=== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


=== MS_Description

// tag::ms_description[]

// end::ms_description[]


=== persistence_source_RepoObject_fullname

// tag::persistence_source_repoobject_fullname[]

// end::persistence_source_repoobject_fullname[]


=== persistence_source_RepoObject_fullname2

// tag::persistence_source_repoobject_fullname2[]

// end::persistence_source_repoobject_fullname2[]


=== persistence_source_RepoObject_guid

// tag::persistence_source_repoobject_guid[]

// end::persistence_source_repoobject_guid[]


=== persistence_source_RepoObject_xref

// tag::persistence_source_repoobject_xref[]

// end::persistence_source_repoobject_xref[]


=== pk_index_guid

// tag::pk_index_guid[]

// end::pk_index_guid[]


=== pk_IndexPatternColumnDatatype

// tag::pk_indexpatterncolumndatatype[]

// end::pk_indexpatterncolumndatatype[]


=== pk_IndexPatternColumnName

// tag::pk_indexpatterncolumnname[]

// end::pk_indexpatterncolumnname[]


=== pk_IndexSemanticGroup

// tag::pk_indexsemanticgroup[]

// end::pk_indexsemanticgroup[]


=== ReferencedObjectList

// tag::referencedobjectlist[]
* [ssis_t].[pkgStats]
// end::referencedobjectlist[]


=== usp_persistence_RepoObject_guid

// tag::usp_persistence_repoobject_guid[]

// end::usp_persistence_repoobject_guid[]


=== UspExamples

// tag::uspexamples[]

// end::uspexamples[]


=== uspgenerator_usp_id

// tag::uspgenerator_usp_id[]

// end::uspgenerator_usp_id[]


=== UspParameters

// tag::uspparameters[]

// end::uspparameters[]

== Boolean Attributes

source: property.RepoObjectProperty WHERE property_int = 1

// tag::boolean_attributes[]


// end::boolean_attributes[]

== PlantUML diagrams

=== PlantUML Entity

// tag::puml_entity[]
[plantuml, entity-{docname}, svg, subs=macros]
....
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis_t.tblprecedenceconstraint_src.adoc[]" as ssis_t.TblPrecedenceConstraint_src << V >> {
  CreationName : (nvarchar(max))
  DTSID : (uniqueidentifier)
  EvalOp : (int)
  Expression : (nvarchar(max))
  - FlowType : (varchar(12))
  LogicalAnd : (bit)
  ObjectName : (nvarchar(max))
  - PackagePath : (varchar(8000))
  - RowID : (int)
  TaskFrom : (nvarchar(max))
  TaskTo : (nvarchar(max))
  --
}
....

// end::puml_entity[]

=== PlantUML Entity 1 1 FK

// tag::puml_entity_1_1_fk[]
[plantuml, entity_1_1_fk-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis_t.tblprecedenceconstraint_src.adoc[]" as ssis_t.TblPrecedenceConstraint_src << V >> {

}



footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_fk[]

=== PlantUML 1 1 ObjectRef

// tag::puml_entity_1_1_objectref[]
[plantuml, entity_1_1_objectref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis_t.pkgstats.adoc[]" as ssis_t.pkgStats << U >> {
  - **RowID** : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tblprecedenceconstraint_src.adoc[]" as ssis_t.TblPrecedenceConstraint_src << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.usp_getpackagedetails.adoc[]" as ssis_t.usp_GetPackageDetails << P >> {
  --
}

ssis_t.pkgStats <.. ssis_t.TblPrecedenceConstraint_src
ssis_t.TblPrecedenceConstraint_src <.. ssis_t.usp_GetPackageDetails

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_objectref[]

=== PlantUML 30 0 ObjectRef

// tag::puml_entity_30_0_objectref[]
[plantuml, entity_30_0_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis_t.pkgstats.adoc[]" as ssis_t.pkgStats << U >> {
  - **RowID** : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tblprecedenceconstraint_src.adoc[]" as ssis_t.TblPrecedenceConstraint_src << V >> {
  --
}

ssis_t.pkgStats <.. ssis_t.TblPrecedenceConstraint_src

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_30_0_objectref[]

=== PlantUML 0 30 ObjectRef

// tag::puml_entity_0_30_objectref[]
[plantuml, entity_0_30_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis_t.tblprecedenceconstraint_src.adoc[]" as ssis_t.TblPrecedenceConstraint_src << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.usp_getpackagedetails.adoc[]" as ssis_t.usp_GetPackageDetails << P >> {
  --
}

ssis_t.TblPrecedenceConstraint_src <.. ssis_t.usp_GetPackageDetails

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_0_30_objectref[]

=== PlantUML 1 1 ColumnRef

// tag::puml_entity_1_1_colref[]
[plantuml, entity_1_1_colref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis_t.pkgstats.adoc[]" as ssis_t.pkgStats << U >> {
  - **RowID** : (int)
  PackageCreationDate : (datetime)
  PackageCreatorComputerName : (nvarchar(500))
  PackageCreatorName : (varchar(1000))
  PackageDescription : (nvarchar(max))
  PackageDTSID : (uniqueidentifier)
  PackageLastModifiedProductVersion : (nvarchar(500))
  PackageLocaleID : (int)
  PackageObjectName : (nvarchar(500))
  - PackagePath : (varchar(8000))
  PackageProtectionLevel : (varchar(100))
  PackageVersionGUID : (uniqueidentifier)
  - PackageXML : (xml)
  - ProjectPath : (varchar(8000))
  # PackageName : (varchar(200))
  ~ PackageProtectionLevelName : (varchar(28))
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tblprecedenceconstraint_src.adoc[]" as ssis_t.TblPrecedenceConstraint_src << V >> {
  CreationName : (nvarchar(max))
  DTSID : (uniqueidentifier)
  EvalOp : (int)
  Expression : (nvarchar(max))
  - FlowType : (varchar(12))
  LogicalAnd : (bit)
  ObjectName : (nvarchar(max))
  - PackagePath : (varchar(8000))
  - RowID : (int)
  TaskFrom : (nvarchar(max))
  TaskTo : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis_t.usp_getpackagedetails.adoc[]" as ssis_t.usp_GetPackageDetails << P >> {
  --
}

ssis_t.pkgStats <.. ssis_t.TblPrecedenceConstraint_src
ssis_t.TblPrecedenceConstraint_src <.. ssis_t.usp_GetPackageDetails


footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_colref[]


== sql_modules_definition

// tag::sql_modules_definition[]
[%collapsible]
=======
[source,sql,numbered,indent=0]
----

CREATE VIEW [ssis_t].[TblPrecedenceConstraint_src]
As
With
CTE_CFPrec
As
    (
    Select
        pkg.RowID
      , pkg.PackagePath
      , TaskFrom     = cfnodes.x.value (
                                           'declare namespace p1="www.microsoft.com/SqlServer/Dts";./@p1:From[1]'
                                         , 'nvarchar(max)'
                                       )
      , TaskTo       = cfnodes.x.value (
                                           'declare namespace p1="www.microsoft.com/SqlServer/Dts";./@p1:To[1]'
                                         , 'nvarchar(max)'
                                       )
      , LogicalAnd   = cfnodes.x.value (
                                           'declare namespace p1="www.microsoft.com/SqlServer/Dts";./@p1:LogicalAnd[1]'
                                         , 'bit'
                                       )
      , ObjectName   = cfnodes.x.value (
                                           'declare namespace p1="www.microsoft.com/SqlServer/Dts";./@p1:ObjectName[1]'
                                         , 'nvarchar(max)'
                                       )
      , CreationName = cfnodes.x.value (
                                           'declare namespace p1="www.microsoft.com/SqlServer/Dts";./@p1:CreationName[1]'
                                         , 'nvarchar(max)'
                                       )
      , DTSID        = cfnodes.x.value (
                                           'declare namespace p1="www.microsoft.com/SqlServer/Dts";./@p1:DTSID[1]'
                                         , 'uniqueidentifier'
                                       )
      , EvalOp       = cfnodes.x.value ( 'declare namespace p1="www.microsoft.com/SqlServer/Dts";./@p1:EvalOp[1]', 'int' )
      --https://docs.microsoft.com/de-de/dotnet/api/microsoft.sqlserver.dts.runtime.dtsprecedenceevalop?view=sqlserver-2019
      /*
Constraint	2	
Gibt an, dass das Ausführungsergebnis bestimmt, ob der eingeschränkte Container oder Task ausgeführt wird. Legen Sie für die Value-Eigenschaft von PrecedenceConstraint den gewünschten Wert aus der DTSExecResult-Enumeration fest.

Expression	1	
Gibt an, dass der Wert eines Ausdrucks bestimmt, ob der eingeschränkte Container oder Task ausgeführt wird. Legen Sie die Expression-Eigenschaft von PrecedenceConstraint fest.

ExpressionAndConstraint	3	
Gibt an, dass das Einschränkungsergebnis auftreten und der Ausdruck ausgewertet werden muss, damit der eingeschränkte Container oder Task ausgeführt wird. Legen Sie die Value -Eigenschaft und die- Expression Eigenschaft des fest PrecedenceConstraint , und legen Sie die- LogicalAnd Eigenschaft auf true fest.

ExpressionOrConstraint	4	
Gibt an, dass entweder das Einschränkungsergebnis auftreten oder der Ausdruck ausgewertet werden muss, damit der eingeschränkte Container oder Task ausgeführt wird. Legen Sie die Value -Eigenschaft und die- Expression Eigenschaft des fest PrecedenceConstraint , und legen Sie die- LogicalAnd Eigenschaft auf false fest.
*/
      , Expression   = cfnodes.x.value (
                                           'declare namespace p1="www.microsoft.com/SqlServer/Dts";./@p1:Expression[1]'
                                         , 'nvarchar(max)'
                                       )
    --,dft.x.value('@refId[1]','varchar(max)')
    From
        ssis_t.pkgStats                                                                                                                             As pkg
        Cross Apply pkg.PackageXML.nodes ( 'declare namespace DTS="www.microsoft.com/SqlServer/Dts";//DTS:Executable/DTS:PrecedenceConstraints/*' ) As cfnodes(x)
    )
,
CTE_DFTPrec
As
    (
    Select
        pkg.RowID
      , pkg.PackagePath
      , TaskFrom = cfnodes.x.value ( './@startId[1]', 'nvarchar(max)' )
      , TaskTo   = cfnodes.x.value ( './@endId[1]', 'nvarchar(max)' )
      , name   = cfnodes.x.value ( './@name[1]', 'nvarchar(max)' )
    --,dft.x.value('@refId[1]','varchar(max)')
    From
        ssis_t.pkgStats                                                                                                                                 As pkg
        Cross Apply pkg.PackageXML.nodes ( 'declare namespace DTS="www.microsoft.com/SqlServer/Dts";//DTS:Executable/DTS:ObjectData/pipeline/paths/*' ) As cfnodes(x)
    )


Select
    t.RowID
  , t.PackagePath
  , t.TaskFrom
  , t.TaskTo
  , t.LogicalAnd
  , t.ObjectName
  , t.CreationName
  , t.DTSID
  , t.EvalOp
  , t.Expression
  , t.FlowType
From
(
    Select
        CTE_CFPrec.RowID
      , CTE_CFPrec.PackagePath
      , CTE_CFPrec.TaskFrom
      , CTE_CFPrec.TaskTo
      , CTE_CFPrec.LogicalAnd
      , CTE_CFPrec.ObjectName
      , CTE_CFPrec.CreationName
      , CTE_CFPrec.DTSID
      , CTE_CFPrec.EvalOp
      , CTE_CFPrec.Expression
      , FlowType = 'Control Flow'
    From
        CTE_CFPrec
    Union All
    Select
        CTE_DFTPrec.RowID
      , CTE_DFTPrec.PackagePath
      , TaskFrom   = Substring ( CTE_DFTPrec.TaskFrom, 1, CharIndex ( '.', CTE_DFTPrec.TaskFrom ) - 1 )
      , TaskTo = Substring ( CTE_DFTPrec.TaskTo, 1, CharIndex ( '.', CTE_DFTPrec.TaskTo ) - 1 )
      , LogicalAnd = Null
      , ObjectName = CTE_DFTPrec.name
      , Null
      , Null
      , Null
      , Null
      , 'Data Flow'
    From
        CTE_DFTPrec

/*
for CTE_DFTPrec (Datenflusstask, dataflowtask) we have much more information in the package:

* variables
* ObjectData
** pipeline
*** components
**** compontent
***** connections
***** inputs
***** outputs

*/
) As t
----
=======
// end::sql_modules_definition[]


