// tag::HeaderFullDisplayName[]
= ssis.PackageTask_Dft_Component_output_outputcolumn - U
// end::HeaderFullDisplayName[]

== existing_properties

// tag::existing_properties[]

:ExistsProperty--antorareferencedlist:
:ExistsProperty--antorareferencinglist:
:ExistsProperty--is_repo_managed:
:ExistsProperty--is_ssas:
:ExistsProperty--referencedobjectlist:
:ExistsProperty--FK:
:ExistsProperty--Columns:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
1032C7D6-D13F-EC11-852D-A81E8446D5B0
// end::RepoObject_guid[]

== RepoObject_FullDisplayName2

// tag::RepoObject_FullDisplayName2[]
ssis.PackageTask_Dft_Component_output_outputcolumn
// end::RepoObject_FullDisplayName2[]

== SysObject_type

// tag::SysObject_type[]
U 
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
user table
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
830678057
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2022-01-23 14:10:33
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]
[discrete]
== _


[#column-antoramodule]
=== AntoraModule

[cols="d,8a,m,m,m"]
|===
|
|AntoraModule
|varchar(50)
|NOT NULL
|
|===

.Referencing Columns
--
* xref:docs.ssis_dfttaskcomponentoutputcolumnlist.adoc#column-antoramodule[+docs.ssis_DftTaskComponentOutputColumnList.AntoraModule+]
* xref:ssis.packagetask_dft_component_output_outputcolumn_tgt.adoc#column-antoramodule[+ssis.PackageTask_Dft_Component_output_outputcolumn_tgt.AntoraModule+]
--


[#column-columnunderlinedatatype]
=== Column_dataType

[cols="d,8a,m,m,m"]
|===
|
|Column_dataType
|varchar(100)
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_output_outputcolumn_tgt.adoc#column-columnunderlinedatatype[+ssis.PackageTask_Dft_Component_output_outputcolumn_tgt.Column_dataType+]
--


[#column-columnunderlineerrorortruncationoperation]
=== Column_errorOrTruncationOperation

[cols="d,8a,m,m,m"]
|===
|
|Column_errorOrTruncationOperation
|varchar(100)
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_output_outputcolumn_tgt.adoc#column-columnunderlineerrorortruncationoperation[+ssis.PackageTask_Dft_Component_output_outputcolumn_tgt.Column_errorOrTruncationOperation+]
--


[#column-columnunderlineerrorrowdisposition]
=== Column_errorRowDisposition

[cols="d,8a,m,m,m"]
|===
|
|Column_errorRowDisposition
|varchar(100)
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_output_outputcolumn_tgt.adoc#column-columnunderlineerrorrowdisposition[+ssis.PackageTask_Dft_Component_output_outputcolumn_tgt.Column_errorRowDisposition+]
--


[#column-columnunderlineexternalmetadatacolumnid]
=== Column_externalMetadataColumnId

[cols="d,8a,m,m,m"]
|===
|
|Column_externalMetadataColumnId
|varchar(max)
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_output_outputcolumn_tgt.adoc#column-columnunderlineexternalmetadatacolumnid[+ssis.PackageTask_Dft_Component_output_outputcolumn_tgt.Column_externalMetadataColumnId+]
--


[#column-columnunderlinelength]
=== Column_length

[cols="d,8a,m,m,m"]
|===
|
|Column_length
|int
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_output_outputcolumn_tgt.adoc#column-columnunderlinelength[+ssis.PackageTask_Dft_Component_output_outputcolumn_tgt.Column_length+]
--


[#column-columnunderlinelineageid]
=== Column_lineageId

[cols="d,8a,m,m,m"]
|===
|
|Column_lineageId
|varchar(max)
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_output_outputcolumn_tgt.adoc#column-columnunderlinelineageid[+ssis.PackageTask_Dft_Component_output_outputcolumn_tgt.Column_lineageId+]
--


[#column-columnunderlinename]
=== Column_name

[cols="d,8a,m,m,m"]
|===
|
|Column_name
|varchar(max)
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_output_outputcolumn_tgt.adoc#column-columnunderlinename[+ssis.PackageTask_Dft_Component_output_outputcolumn_tgt.Column_name+]
--


[#column-columnunderlineprecision]
=== Column_precision

[cols="d,8a,m,m,m"]
|===
|
|Column_precision
|int
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_output_outputcolumn_tgt.adoc#column-columnunderlineprecision[+ssis.PackageTask_Dft_Component_output_outputcolumn_tgt.Column_precision+]
--


[#column-columnunderlinerefid]
=== Column_refId

[cols="d,8a,m,m,m"]
|===
|
|Column_refId
|varchar(max)
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_output_outputcolumn_tgt.adoc#column-columnunderlinerefid[+ssis.PackageTask_Dft_Component_output_outputcolumn_tgt.Column_refId+]
--


[#column-columnunderlinescale]
=== Column_scale

[cols="d,8a,m,m,m"]
|===
|
|Column_scale
|int
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_output_outputcolumn_tgt.adoc#column-columnunderlinescale[+ssis.PackageTask_Dft_Component_output_outputcolumn_tgt.Column_scale+]
--


[#column-columnunderlinetruncationrowdisposition]
=== Column_truncationRowDisposition

[cols="d,8a,m,m,m"]
|===
|
|Column_truncationRowDisposition
|varchar(max)
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_output_outputcolumn_tgt.adoc#column-columnunderlinetruncationrowdisposition[+ssis.PackageTask_Dft_Component_output_outputcolumn_tgt.Column_truncationRowDisposition+]
--


[#column-componentunderlinerefid]
=== Component_refId

[cols="d,8a,m,m,m"]
|===
|
|Component_refId
|varchar(max)
|NULL
|
|===

.Referencing Columns
--
* xref:docs.ssis_dfttaskcomponentoutputcolumnlist.adoc#column-componentunderlinerefid[+docs.ssis_DftTaskComponentOutputColumnList.Component_refId+]
* xref:ssis.packagetask_dft_component_output_outputcolumn_tgt.adoc#column-componentunderlinerefid[+ssis.PackageTask_Dft_Component_output_outputcolumn_tgt.Component_refId+]
--


[#column-controlflowdetailsrowid]
=== ControlFlowDetailsRowID

[cols="d,8a,m,m,m"]
|===
|
|ControlFlowDetailsRowID
|int
|NOT NULL
|
|===

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_output_outputcolumn_tgt.adoc#column-controlflowdetailsrowid[+ssis.PackageTask_Dft_Component_output_outputcolumn_tgt.ControlFlowDetailsRowID+]
--


[#column-outputunderlineiserrorout]
=== output_isErrorOut

[cols="d,8a,m,m,m"]
|===
|
|output_isErrorOut
|bit
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_output_outputcolumn_tgt.adoc#column-outputunderlineiserrorout[+ssis.PackageTask_Dft_Component_output_outputcolumn_tgt.output_isErrorOut+]
--


[#column-outputunderlinename]
=== output_name

[cols="d,8a,m,m,m"]
|===
|
|output_name
|varchar(500)
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_output_outputcolumn_tgt.adoc#column-outputunderlinename[+ssis.PackageTask_Dft_Component_output_outputcolumn_tgt.output_name+]
--


[#column-outputunderlinerefid]
=== output_refId

[cols="d,8a,m,m,m"]
|===
|
|output_refId
|varchar(max)
|NULL
|
|===

.Referencing Columns
--
* xref:docs.ssis_dfttaskcomponentoutputcolumnlist.adoc#column-outputunderlinerefid[+docs.ssis_DftTaskComponentOutputColumnList.output_refId+]
* xref:ssis.packagetask_dft_component_output_outputcolumn_tgt.adoc#column-outputunderlinerefid[+ssis.PackageTask_Dft_Component_output_outputcolumn_tgt.output_refId+]
--


[#column-packagename]
=== PackageName

[cols="d,8a,m,m,m"]
|===
|
|PackageName
|varchar(200)
|NULL
|
|===

.Referencing Columns
--
* xref:docs.ssis_dfttaskcomponentoutputcolumnlist.adoc#column-packagename[+docs.ssis_DftTaskComponentOutputColumnList.PackageName+]
* xref:ssis.packagetask_dft_component_output_outputcolumn_tgt.adoc#column-packagename[+ssis.PackageTask_Dft_Component_output_outputcolumn_tgt.PackageName+]
--


[#column-taskpath]
=== TaskPath

[cols="d,8a,m,m,m"]
|===
|
|TaskPath
|varchar(8000)
|NULL
|
|===

.Referencing Columns
--
* xref:docs.ssis_dfttaskcomponentoutputcolumnlist.adoc#column-taskpath[+docs.ssis_DftTaskComponentOutputColumnList.TaskPath+]
* xref:ssis.packagetask_dft_component_output_outputcolumn_tgt.adoc#column-taskpath[+ssis.PackageTask_Dft_Component_output_outputcolumn_tgt.TaskPath+]
--


// end::AntoraColumnDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]



















// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]
|
|<<column-antoramodule>>
|varchar(50)
|NOT NULL
|

|
|<<column-columnunderlinedatatype>>
|varchar(100)
|NULL
|

|
|<<column-columnunderlineerrorortruncationoperation>>
|varchar(100)
|NULL
|

|
|<<column-columnunderlineerrorrowdisposition>>
|varchar(100)
|NULL
|

|
|<<column-columnunderlineexternalmetadatacolumnid>>
|varchar(max)
|NULL
|

|
|<<column-columnunderlinelength>>
|int
|NULL
|

|
|<<column-columnunderlinelineageid>>
|varchar(max)
|NULL
|

|
|<<column-columnunderlinename>>
|varchar(max)
|NULL
|

|
|<<column-columnunderlineprecision>>
|int
|NULL
|

|
|<<column-columnunderlinerefid>>
|varchar(max)
|NULL
|

|
|<<column-columnunderlinescale>>
|int
|NULL
|

|
|<<column-columnunderlinetruncationrowdisposition>>
|varchar(max)
|NULL
|

|
|<<column-componentunderlinerefid>>
|varchar(max)
|NULL
|

|
|<<column-controlflowdetailsrowid>>
|int
|NOT NULL
|

|
|<<column-outputunderlineiserrorout>>
|bit
|NULL
|

|
|<<column-outputunderlinename>>
|varchar(500)
|NULL
|

|
|<<column-outputunderlinerefid>>
|varchar(max)
|NULL
|

|
|<<column-packagename>>
|varchar(200)
|NULL
|

|
|<<column-taskpath>>
|varchar(8000)
|NULL
|

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

// end::AntoraIndexList[]

== AntoraMeasureDetails

// tag::AntoraMeasureDetails[]

// end::AntoraMeasureDetails[]

== AntoraMeasureDescriptions



== AntoraParameterList

// tag::AntoraParameterList[]

// end::AntoraParameterList[]

== AntoraXrefCulturesList

// tag::AntoraXrefCulturesList[]
* xref:dhw:sqldb:ssis.packagetask_dft_component_output_outputcolumn.adoc[] - 
// end::AntoraXrefCulturesList[]

== cultures_count

// tag::cultures_count[]
1
// end::cultures_count[]

== Other tags

source: property.RepoObjectProperty_cross As rop_cross


=== additional_reference_csv

// tag::additional_reference_csv[]

// end::additional_reference_csv[]


=== AdocUspSteps

// tag::adocuspsteps[]

// end::adocuspsteps[]


=== AntoraReferencedList

// tag::antorareferencedlist[]
* xref:dhw:sqldb:ssis.packagetask_dft_component_output_outputcolumn_tgt.adoc[]
// end::antorareferencedlist[]


=== AntoraReferencingList

// tag::antorareferencinglist[]
* xref:dhw:sqldb:docs.ssis_dfttaskcomponentoutputcolumnlist.adoc[]
// end::antorareferencinglist[]


=== Description

// tag::description[]

// end::description[]


=== exampleUsage

// tag::exampleusage[]

// end::exampleusage[]


=== exampleUsage_2

// tag::exampleusage_2[]

// end::exampleusage_2[]


=== exampleUsage_3

// tag::exampleusage_3[]

// end::exampleusage_3[]


=== exampleUsage_4

// tag::exampleusage_4[]

// end::exampleusage_4[]


=== exampleUsage_5

// tag::exampleusage_5[]

// end::exampleusage_5[]


=== exampleWrong_Usage

// tag::examplewrong_usage[]

// end::examplewrong_usage[]


=== has_execution_plan_issue

// tag::has_execution_plan_issue[]

// end::has_execution_plan_issue[]


=== has_get_referenced_issue

// tag::has_get_referenced_issue[]

// end::has_get_referenced_issue[]


=== has_history

// tag::has_history[]

// end::has_history[]


=== has_history_columns

// tag::has_history_columns[]

// end::has_history_columns[]


=== InheritanceType

// tag::inheritancetype[]

// end::inheritancetype[]


=== is_persistence

// tag::is_persistence[]

// end::is_persistence[]


=== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]

// end::is_persistence_check_duplicate_per_pk[]


=== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]

// end::is_persistence_check_for_empty_source[]


=== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]

// end::is_persistence_delete_changed[]


=== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]

// end::is_persistence_delete_missing[]


=== is_persistence_insert

// tag::is_persistence_insert[]

// end::is_persistence_insert[]


=== is_persistence_truncate

// tag::is_persistence_truncate[]

// end::is_persistence_truncate[]


=== is_persistence_update_changed

// tag::is_persistence_update_changed[]

// end::is_persistence_update_changed[]


=== is_repo_managed

// tag::is_repo_managed[]
0
// end::is_repo_managed[]


=== is_ssas

// tag::is_ssas[]
0
// end::is_ssas[]


=== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


=== MS_Description

// tag::ms_description[]

// end::ms_description[]


=== persistence_source_RepoObject_fullname

// tag::persistence_source_repoobject_fullname[]

// end::persistence_source_repoobject_fullname[]


=== persistence_source_RepoObject_fullname2

// tag::persistence_source_repoobject_fullname2[]

// end::persistence_source_repoobject_fullname2[]


=== persistence_source_RepoObject_guid

// tag::persistence_source_repoobject_guid[]

// end::persistence_source_repoobject_guid[]


=== persistence_source_RepoObject_xref

// tag::persistence_source_repoobject_xref[]

// end::persistence_source_repoobject_xref[]


=== pk_index_guid

// tag::pk_index_guid[]

// end::pk_index_guid[]


=== pk_IndexPatternColumnDatatype

// tag::pk_indexpatterncolumndatatype[]

// end::pk_indexpatterncolumndatatype[]


=== pk_IndexPatternColumnName

// tag::pk_indexpatterncolumnname[]

// end::pk_indexpatterncolumnname[]


=== pk_IndexSemanticGroup

// tag::pk_indexsemanticgroup[]

// end::pk_indexsemanticgroup[]


=== ReferencedObjectList

// tag::referencedobjectlist[]
* [ssis].[PackageTask_Dft_Component_output_outputColumn_tgt]
// end::referencedobjectlist[]


=== usp_persistence_RepoObject_guid

// tag::usp_persistence_repoobject_guid[]

// end::usp_persistence_repoobject_guid[]


=== UspExamples

// tag::uspexamples[]

// end::uspexamples[]


=== uspgenerator_usp_id

// tag::uspgenerator_usp_id[]

// end::uspgenerator_usp_id[]


=== UspParameters

// tag::uspparameters[]

// end::uspparameters[]

== Boolean Attributes

source: property.RepoObjectProperty WHERE property_int = 1

// tag::boolean_attributes[]


// end::boolean_attributes[]

== PlantUML diagrams

=== PlantUML Entity

// tag::puml_entity[]
[plantuml, entity-{docname}, svg, subs=macros]
....
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_output_outputcolumn.adoc[]" as ssis.PackageTask_Dft_Component_output_outputcolumn << U >> {
  - AntoraModule : (varchar(50))
  Column_dataType : (varchar(100))
  Column_errorOrTruncationOperation : (varchar(100))
  Column_errorRowDisposition : (varchar(100))
  Column_externalMetadataColumnId : (varchar(max))
  Column_length : (int)
  Column_lineageId : (varchar(max))
  Column_name : (varchar(max))
  Column_precision : (int)
  Column_refId : (varchar(max))
  Column_scale : (int)
  Column_truncationRowDisposition : (varchar(max))
  Component_refId : (varchar(max))
  - ControlFlowDetailsRowID : (int)
  output_isErrorOut : (bit)
  output_name : (varchar(500))
  output_refId : (varchar(max))
  PackageName : (varchar(200))
  TaskPath : (varchar(8000))
  --
}
....

// end::puml_entity[]

=== PlantUML Entity 1 1 FK

// tag::puml_entity_1_1_fk[]
[plantuml, entity_1_1_fk-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_output_outputcolumn.adoc[]" as ssis.PackageTask_Dft_Component_output_outputcolumn << U >> {

}



footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_fk[]

=== PlantUML 1 1 ObjectRef

// tag::puml_entity_1_1_objectref[]
[plantuml, entity_1_1_objectref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:docs.ssis_dfttaskcomponentoutputcolumnlist.adoc[]" as docs.ssis_DftTaskComponentOutputColumnList << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_output_outputcolumn.adoc[]" as ssis.PackageTask_Dft_Component_output_outputcolumn << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_output_outputcolumn_tgt.adoc[]" as ssis.PackageTask_Dft_Component_output_outputColumn_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Column_refId** : (varchar(max))
  --
}

ssis.PackageTask_Dft_Component_output_outputcolumn <.. docs.ssis_DftTaskComponentOutputColumnList
ssis.PackageTask_Dft_Component_output_outputcolumn_tgt <.. ssis.PackageTask_Dft_Component_output_outputcolumn

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_objectref[]

=== PlantUML 30 0 ObjectRef

// tag::puml_entity_30_0_objectref[]
[plantuml, entity_30_0_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis.antoramodule_tgt_filter.adoc[]" as ssis.AntoraModule_tgt_filter << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.package_src.adoc[]" as ssis.Package_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_output_outputcolumn.adoc[]" as ssis.PackageTask_Dft_Component_output_outputcolumn << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_output_outputcolumn_src.adoc[]" as ssis.PackageTask_Dft_Component_output_outputcolumn_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Column_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_output_outputcolumn_tgt.adoc[]" as ssis.PackageTask_Dft_Component_output_outputColumn_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Column_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.project.adoc[]" as ssis.Project << U >> {
  - **AntoraModule** : (varchar(50))
  --
}

entity "puml-link:dhw:sqldb:ssis_t.pkgstats.adoc[]" as ssis_t.pkgStats << U >> {
  - **RowID** : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tblcontrolflow.adoc[]" as ssis_t.TblControlFlow << U >> {
  - **ControlFlowDetailsRowID** : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_dft_component.adoc[]" as ssis_t.TblTask_Dft_Component << U >> {
  - **DftComponentId** : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_dft_component_outputs_outputcolumn_src.adoc[]" as ssis_t.TblTask_Dft_Component_outputs_outputColumn_src << V >> {
  --
}

ssis.AntoraModule_tgt_filter <.. ssis.PackageTask_Dft_Component_output_outputcolumn_tgt
ssis.Package_src <.. ssis.AntoraModule_tgt_filter
ssis.Package_src <.. ssis.PackageTask_Dft_Component_output_outputcolumn_src
ssis.PackageTask_Dft_Component_output_outputcolumn_src <.. ssis.PackageTask_Dft_Component_output_outputcolumn_tgt
ssis.PackageTask_Dft_Component_output_outputcolumn_tgt <.. ssis.PackageTask_Dft_Component_output_outputcolumn
ssis.Project <.. ssis.Package_src
ssis_t.pkgStats <.. ssis.Package_src
ssis_t.TblControlFlow <.. ssis.PackageTask_Dft_Component_output_outputcolumn_src
ssis_t.TblTask_Dft_Component <.. ssis_t.TblTask_Dft_Component_outputs_outputColumn_src
ssis_t.TblTask_Dft_Component_outputs_outputColumn_src <.. ssis.PackageTask_Dft_Component_output_outputcolumn_src

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_30_0_objectref[]

=== PlantUML 0 30 ObjectRef

// tag::puml_entity_0_30_objectref[]
[plantuml, entity_0_30_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:docs.ssis_adoc.adoc[]" as docs.ssis_Adoc << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageBasename** : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_adoc_t.adoc[]" as docs.ssis_Adoc_T << U >> {
  - **AntoraModule** : (varchar(50))
  - **PackageBasename** : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_dfttaskcomponentlist.adoc[]" as docs.ssis_DftTaskComponentList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_dfttaskcomponentoutputcolumnlist.adoc[]" as docs.ssis_DftTaskComponentOutputColumnList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_dfttaskcomponentoutputlist.adoc[]" as docs.ssis_DftTaskComponentOutputList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_task.adoc[]" as docs.ssis_Task << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_tasklist.adoc[]" as docs.ssis_TaskList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport.adoc[]" as docs.usp_AntoraExport << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_ssispartialscontent.adoc[]" as docs.usp_AntoraExport_SsisPartialsContent << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_ssis_adoc_t.adoc[]" as docs.usp_PERSIST_ssis_Adoc_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_output_outputcolumn.adoc[]" as ssis.PackageTask_Dft_Component_output_outputcolumn << U >> {
  --
}

docs.ssis_Adoc <.. docs.usp_PERSIST_ssis_Adoc_T
docs.ssis_Adoc <.. docs.ssis_Adoc_T
docs.ssis_Adoc_T <.. docs.usp_AntoraExport_SsisPartialsContent
docs.ssis_Adoc_T <.. docs.usp_PERSIST_ssis_Adoc_T
docs.ssis_DftTaskComponentList <.. docs.ssis_TaskList
docs.ssis_DftTaskComponentList <.. docs.ssis_Task
docs.ssis_DftTaskComponentOutputColumnList <.. docs.ssis_DftTaskComponentOutputList
docs.ssis_DftTaskComponentOutputList <.. docs.ssis_DftTaskComponentList
docs.ssis_TaskList <.. docs.ssis_Adoc
docs.usp_AntoraExport_SsisPartialsContent <.. docs.usp_AntoraExport
docs.usp_PERSIST_ssis_Adoc_T <.. docs.usp_AntoraExport_SsisPartialsContent
ssis.PackageTask_Dft_Component_output_outputcolumn <.. docs.ssis_DftTaskComponentOutputColumnList

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_0_30_objectref[]

=== PlantUML 1 1 ColumnRef

// tag::puml_entity_1_1_colref[]
[plantuml, entity_1_1_colref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:docs.ssis_dfttaskcomponentoutputcolumnlist.adoc[]" as docs.ssis_DftTaskComponentOutputColumnList << V >> {
  - AntoraModule : (varchar(50))
  Component_refId : (varchar(max))
  - DftTaskComponentOutputColumnList : (nvarchar(max))
  output_refId : (varchar(max))
  PackageName : (varchar(200))
  TaskPath : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_output_outputcolumn.adoc[]" as ssis.PackageTask_Dft_Component_output_outputcolumn << U >> {
  - AntoraModule : (varchar(50))
  Column_dataType : (varchar(100))
  Column_errorOrTruncationOperation : (varchar(100))
  Column_errorRowDisposition : (varchar(100))
  Column_externalMetadataColumnId : (varchar(max))
  Column_length : (int)
  Column_lineageId : (varchar(max))
  Column_name : (varchar(max))
  Column_precision : (int)
  Column_refId : (varchar(max))
  Column_scale : (int)
  Column_truncationRowDisposition : (varchar(max))
  Component_refId : (varchar(max))
  - ControlFlowDetailsRowID : (int)
  output_isErrorOut : (bit)
  output_name : (varchar(500))
  output_refId : (varchar(max))
  PackageName : (varchar(200))
  TaskPath : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_output_outputcolumn_tgt.adoc[]" as ssis.PackageTask_Dft_Component_output_outputColumn_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Column_refId** : (varchar(max))
  Column_dataType : (varchar(100))
  Column_errorOrTruncationOperation : (varchar(100))
  Column_errorRowDisposition : (varchar(100))
  Column_externalMetadataColumnId : (varchar(max))
  Column_length : (int)
  Column_lineageId : (varchar(max))
  Column_name : (varchar(max))
  Column_precision : (int)
  Column_scale : (int)
  Column_truncationRowDisposition : (varchar(max))
  Component_refId : (varchar(max))
  - ControlFlowDetailsRowID : (int)
  output_isErrorOut : (bit)
  output_name : (varchar(500))
  output_refId : (varchar(max))
  TaskPath : (varchar(8000))
  --
}

ssis.PackageTask_Dft_Component_output_outputcolumn <.. docs.ssis_DftTaskComponentOutputColumnList
ssis.PackageTask_Dft_Component_output_outputcolumn_tgt <.. ssis.PackageTask_Dft_Component_output_outputcolumn
"ssis.PackageTask_Dft_Component_output_outputcolumn::AntoraModule" <-- "ssis.PackageTask_Dft_Component_output_outputcolumn_tgt::AntoraModule"
"ssis.PackageTask_Dft_Component_output_outputcolumn::AntoraModule" <-- "docs.ssis_DftTaskComponentOutputColumnList::AntoraModule"
"ssis.PackageTask_Dft_Component_output_outputcolumn::Column_dataType" <-- "ssis.PackageTask_Dft_Component_output_outputcolumn_tgt::Column_dataType"
"ssis.PackageTask_Dft_Component_output_outputcolumn::Column_errorOrTruncationOperation" <-- "ssis.PackageTask_Dft_Component_output_outputcolumn_tgt::Column_errorOrTruncationOperation"
"ssis.PackageTask_Dft_Component_output_outputcolumn::Column_errorRowDisposition" <-- "ssis.PackageTask_Dft_Component_output_outputcolumn_tgt::Column_errorRowDisposition"
"ssis.PackageTask_Dft_Component_output_outputcolumn::Column_externalMetadataColumnId" <-- "ssis.PackageTask_Dft_Component_output_outputcolumn_tgt::Column_externalMetadataColumnId"
"ssis.PackageTask_Dft_Component_output_outputcolumn::Column_length" <-- "ssis.PackageTask_Dft_Component_output_outputcolumn_tgt::Column_length"
"ssis.PackageTask_Dft_Component_output_outputcolumn::Column_lineageId" <-- "ssis.PackageTask_Dft_Component_output_outputcolumn_tgt::Column_lineageId"
"ssis.PackageTask_Dft_Component_output_outputcolumn::Column_name" <-- "ssis.PackageTask_Dft_Component_output_outputcolumn_tgt::Column_name"
"ssis.PackageTask_Dft_Component_output_outputcolumn::Column_precision" <-- "ssis.PackageTask_Dft_Component_output_outputcolumn_tgt::Column_precision"
"ssis.PackageTask_Dft_Component_output_outputcolumn::Column_refId" <-- "ssis.PackageTask_Dft_Component_output_outputcolumn_tgt::Column_refId"
"ssis.PackageTask_Dft_Component_output_outputcolumn::Column_scale" <-- "ssis.PackageTask_Dft_Component_output_outputcolumn_tgt::Column_scale"
"ssis.PackageTask_Dft_Component_output_outputcolumn::Column_truncationRowDisposition" <-- "ssis.PackageTask_Dft_Component_output_outputcolumn_tgt::Column_truncationRowDisposition"
"ssis.PackageTask_Dft_Component_output_outputcolumn::Component_refId" <-- "ssis.PackageTask_Dft_Component_output_outputcolumn_tgt::Component_refId"
"ssis.PackageTask_Dft_Component_output_outputcolumn::Component_refId" <-- "docs.ssis_DftTaskComponentOutputColumnList::Component_refId"
"ssis.PackageTask_Dft_Component_output_outputcolumn::ControlFlowDetailsRowID" <-- "ssis.PackageTask_Dft_Component_output_outputcolumn_tgt::ControlFlowDetailsRowID"
"ssis.PackageTask_Dft_Component_output_outputcolumn::output_isErrorOut" <-- "ssis.PackageTask_Dft_Component_output_outputcolumn_tgt::output_isErrorOut"
"ssis.PackageTask_Dft_Component_output_outputcolumn::output_name" <-- "ssis.PackageTask_Dft_Component_output_outputcolumn_tgt::output_name"
"ssis.PackageTask_Dft_Component_output_outputcolumn::output_refId" <-- "ssis.PackageTask_Dft_Component_output_outputcolumn_tgt::output_refId"
"ssis.PackageTask_Dft_Component_output_outputcolumn::output_refId" <-- "docs.ssis_DftTaskComponentOutputColumnList::output_refId"
"ssis.PackageTask_Dft_Component_output_outputcolumn::PackageName" <-- "docs.ssis_DftTaskComponentOutputColumnList::PackageName"
"ssis.PackageTask_Dft_Component_output_outputcolumn::PackageName" <-- "ssis.PackageTask_Dft_Component_output_outputcolumn_tgt::PackageName"
"ssis.PackageTask_Dft_Component_output_outputcolumn::TaskPath" <-- "ssis.PackageTask_Dft_Component_output_outputcolumn_tgt::TaskPath"
"ssis.PackageTask_Dft_Component_output_outputcolumn::TaskPath" <-- "docs.ssis_DftTaskComponentOutputColumnList::TaskPath"

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_colref[]


== sql_modules_definition

// tag::sql_modules_definition[]
[%collapsible]
=======
[source,sql,numbered,indent=0]
----

----
=======
// end::sql_modules_definition[]


