// tag::HeaderFullDisplayName[]
= ssis.PackageTask_Dft_Component_tgt - V
// end::HeaderFullDisplayName[]

== existing_properties

// tag::existing_properties[]

:ExistsProperty--antorareferencedlist:
:ExistsProperty--antorareferencinglist:
:ExistsProperty--has_history:
:ExistsProperty--has_history_columns:
:ExistsProperty--is_persistence:
:ExistsProperty--is_persistence_check_duplicate_per_pk:
:ExistsProperty--is_persistence_check_for_empty_source:
:ExistsProperty--is_persistence_delete_changed:
:ExistsProperty--is_persistence_delete_missing:
:ExistsProperty--is_persistence_insert:
:ExistsProperty--is_persistence_truncate:
:ExistsProperty--is_persistence_update_changed:
:ExistsProperty--is_repo_managed:
:ExistsProperty--is_ssas:
:ExistsProperty--persistence_source_repoobject_fullname:
:ExistsProperty--persistence_source_repoobject_fullname2:
:ExistsProperty--persistence_source_repoobject_guid:
:ExistsProperty--persistence_source_repoobject_xref:
:ExistsProperty--pk_index_guid:
:ExistsProperty--pk_indexpatterncolumndatatype:
:ExistsProperty--pk_indexpatterncolumnname:
:ExistsProperty--referencedobjectlist:
:ExistsProperty--usp_persistence_repoobject_guid:
:ExistsProperty--sql_modules_definition:
:ExistsProperty--FK:
:ExistsProperty--AntoraIndexList:
:ExistsProperty--Columns:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
B8DCAD7F-F73E-EC11-852D-A81E8446D5B0
// end::RepoObject_guid[]

== RepoObject_FullDisplayName2

// tag::RepoObject_FullDisplayName2[]
ssis.PackageTask_Dft_Component_tgt
// end::RepoObject_FullDisplayName2[]

== SysObject_type

// tag::SysObject_type[]
V 
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
view
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
254676005
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2021-11-06 12:45:34
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]
[discrete]
== _


[#column-antoramodule]
=== AntoraModule

[cols="d,8a,m,m,m"]
|===
|1
|*AntoraModule*
|varchar(50)
|NOT NULL
|
|===

.Referenced Columns
--
* xref:ssis.packagetask_dft_component.adoc#column-antoramodule[+ssis.PackageTask_Dft_Component.AntoraModule+]
* xref:ssis.packagetask_dft_component_src.adoc#column-antoramodule[+ssis.PackageTask_Dft_Component_src.AntoraModule+]
--


[#column-packagename]
=== PackageName

[cols="d,8a,m,m,m"]
|===
|2
|*PackageName*
|varchar(200)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis.packagetask_dft_component.adoc#column-packagename[+ssis.PackageTask_Dft_Component.PackageName+]
* xref:ssis.packagetask_dft_component_src.adoc#column-packagename[+ssis.PackageTask_Dft_Component_src.PackageName+]
--


[#column-componentunderlinerefid]
=== Component_refId

[cols="d,8a,m,m,m"]
|===
|3
|*Component_refId*
|varchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis.packagetask_dft_component.adoc#column-componentunderlinerefid[+ssis.PackageTask_Dft_Component.Component_refId+]
* xref:ssis.packagetask_dft_component_src.adoc#column-componentunderlinerefid[+ssis.PackageTask_Dft_Component_src.Component_refId+]
--


[#column-componentunderlineaccessmode]
=== Component_AccessMode

[cols="d,8a,m,m,m"]
|===
|
|Component_AccessMode
|varchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis.packagetask_dft_component.adoc#column-componentunderlineaccessmode[+ssis.PackageTask_Dft_Component.Component_AccessMode+]
* xref:ssis.packagetask_dft_component_src.adoc#column-componentunderlineaccessmode[+ssis.PackageTask_Dft_Component_src.Component_AccessMode+]
--


[#column-componentunderlinealwaysusedefaultcodepage]
=== Component_AlwaysUseDefaultCodePage

[cols="d,8a,m,m,m"]
|===
|
|Component_AlwaysUseDefaultCodePage
|varchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis.packagetask_dft_component.adoc#column-componentunderlinealwaysusedefaultcodepage[+ssis.PackageTask_Dft_Component.Component_AlwaysUseDefaultCodePage+]
* xref:ssis.packagetask_dft_component_src.adoc#column-componentunderlinealwaysusedefaultcodepage[+ssis.PackageTask_Dft_Component_src.Component_AlwaysUseDefaultCodePage+]
--


[#column-componentunderlinecommandtimeout]
=== Component_CommandTimeout

[cols="d,8a,m,m,m"]
|===
|
|Component_CommandTimeout
|int
|NULL
|
|===

.Referenced Columns
--
* xref:ssis.packagetask_dft_component.adoc#column-componentunderlinecommandtimeout[+ssis.PackageTask_Dft_Component.Component_CommandTimeout+]
* xref:ssis.packagetask_dft_component_src.adoc#column-componentunderlinecommandtimeout[+ssis.PackageTask_Dft_Component_src.Component_CommandTimeout+]
--


[#column-componentunderlinecomponentclassid]
=== Component_componentClassID

[cols="d,8a,m,m,m"]
|===
|
|Component_componentClassID
|varchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis.packagetask_dft_component.adoc#column-componentunderlinecomponentclassid[+ssis.PackageTask_Dft_Component.Component_componentClassID+]
* xref:ssis.packagetask_dft_component_src.adoc#column-componentunderlinecomponentclassid[+ssis.PackageTask_Dft_Component_src.Component_componentClassID+]
--


[#column-componentunderlineconnectionunderlinedescription]
=== Component_Connection_description

[cols="d,8a,m,m,m"]
|===
|
|Component_Connection_description
|varchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis.packagetask_dft_component.adoc#column-componentunderlineconnectionunderlinedescription[+ssis.PackageTask_Dft_Component.Component_Connection_description+]
* xref:ssis.packagetask_dft_component_src.adoc#column-componentunderlineconnectionunderlinedescription[+ssis.PackageTask_Dft_Component_src.Component_Connection_description+]
--


[#column-componentunderlineconnectionunderlinename]
=== Component_Connection_name

[cols="d,8a,m,m,m"]
|===
|
|Component_Connection_name
|varchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis.packagetask_dft_component.adoc#column-componentunderlineconnectionunderlinename[+ssis.PackageTask_Dft_Component.Component_Connection_name+]
* xref:ssis.packagetask_dft_component_src.adoc#column-componentunderlineconnectionunderlinename[+ssis.PackageTask_Dft_Component_src.Component_Connection_name+]
--


[#column-componentunderlineconnectionunderlinerefid]
=== Component_Connection_refId

[cols="d,8a,m,m,m"]
|===
|
|Component_Connection_refId
|varchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis.packagetask_dft_component.adoc#column-componentunderlineconnectionunderlinerefid[+ssis.PackageTask_Dft_Component.Component_Connection_refId+]
* xref:ssis.packagetask_dft_component_src.adoc#column-componentunderlineconnectionunderlinerefid[+ssis.PackageTask_Dft_Component_src.Component_Connection_refId+]
--


[#column-componentunderlineconnectionmanagerid]
=== Component_connectionManagerID

[cols="d,8a,m,m,m"]
|===
|
|Component_connectionManagerID
|varchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis.packagetask_dft_component.adoc#column-componentunderlineconnectionmanagerid[+ssis.PackageTask_Dft_Component.Component_connectionManagerID+]
* xref:ssis.packagetask_dft_component_src.adoc#column-componentunderlineconnectionmanagerid[+ssis.PackageTask_Dft_Component_src.Component_connectionManagerID+]
--


[#column-componentunderlineconnectionmanagerrefid]
=== Component_connectionManagerRefId

[cols="d,8a,m,m,m"]
|===
|
|Component_connectionManagerRefId
|varchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis.packagetask_dft_component.adoc#column-componentunderlineconnectionmanagerrefid[+ssis.PackageTask_Dft_Component.Component_connectionManagerRefId+]
* xref:ssis.packagetask_dft_component_src.adoc#column-componentunderlineconnectionmanagerrefid[+ssis.PackageTask_Dft_Component_src.Component_connectionManagerRefId+]
--


[#column-componentunderlinecontactinfo]
=== Component_ContactInfo

[cols="d,8a,m,m,m"]
|===
|
|Component_ContactInfo
|varchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis.packagetask_dft_component.adoc#column-componentunderlinecontactinfo[+ssis.PackageTask_Dft_Component.Component_ContactInfo+]
* xref:ssis.packagetask_dft_component_src.adoc#column-componentunderlinecontactinfo[+ssis.PackageTask_Dft_Component_src.Component_ContactInfo+]
--


[#column-componentunderlinedefaultcodepage]
=== Component_DefaultCodePage

[cols="d,8a,m,m,m"]
|===
|
|Component_DefaultCodePage
|int
|NULL
|
|===

.Referenced Columns
--
* xref:ssis.packagetask_dft_component.adoc#column-componentunderlinedefaultcodepage[+ssis.PackageTask_Dft_Component.Component_DefaultCodePage+]
* xref:ssis.packagetask_dft_component_src.adoc#column-componentunderlinedefaultcodepage[+ssis.PackageTask_Dft_Component_src.Component_DefaultCodePage+]
--


[#column-componentunderlinedescription]
=== Component_description

[cols="d,8a,m,m,m"]
|===
|
|Component_description
|varchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis.packagetask_dft_component.adoc#column-componentunderlinedescription[+ssis.PackageTask_Dft_Component.Component_description+]
* xref:ssis.packagetask_dft_component_src.adoc#column-componentunderlinedescription[+ssis.PackageTask_Dft_Component_src.Component_description+]
--


[#column-componentunderlinefastloadkeepidentity]
=== Component_FastLoadKeepIdentity

[cols="d,8a,m,m,m"]
|===
|
|Component_FastLoadKeepIdentity
|bit
|NULL
|
|===

.Referenced Columns
--
* xref:ssis.packagetask_dft_component.adoc#column-componentunderlinefastloadkeepidentity[+ssis.PackageTask_Dft_Component.Component_FastLoadKeepIdentity+]
* xref:ssis.packagetask_dft_component_src.adoc#column-componentunderlinefastloadkeepidentity[+ssis.PackageTask_Dft_Component_src.Component_FastLoadKeepIdentity+]
--


[#column-componentunderlinefastloadkeepnulls]
=== Component_FastLoadKeepNulls

[cols="d,8a,m,m,m"]
|===
|
|Component_FastLoadKeepNulls
|bit
|NULL
|
|===

.Referenced Columns
--
* xref:ssis.packagetask_dft_component.adoc#column-componentunderlinefastloadkeepnulls[+ssis.PackageTask_Dft_Component.Component_FastLoadKeepNulls+]
* xref:ssis.packagetask_dft_component_src.adoc#column-componentunderlinefastloadkeepnulls[+ssis.PackageTask_Dft_Component_src.Component_FastLoadKeepNulls+]
--


[#column-componentunderlinefastloadmaxinsertcommitsize]
=== Component_FastLoadMaxInsertCommitSize

[cols="d,8a,m,m,m"]
|===
|
|Component_FastLoadMaxInsertCommitSize
|int
|NULL
|
|===

.Referenced Columns
--
* xref:ssis.packagetask_dft_component.adoc#column-componentunderlinefastloadmaxinsertcommitsize[+ssis.PackageTask_Dft_Component.Component_FastLoadMaxInsertCommitSize+]
* xref:ssis.packagetask_dft_component_src.adoc#column-componentunderlinefastloadmaxinsertcommitsize[+ssis.PackageTask_Dft_Component_src.Component_FastLoadMaxInsertCommitSize+]
--


[#column-componentunderlinefastloadoptions]
=== Component_FastLoadOptions

[cols="d,8a,m,m,m"]
|===
|
|Component_FastLoadOptions
|varchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis.packagetask_dft_component.adoc#column-componentunderlinefastloadoptions[+ssis.PackageTask_Dft_Component.Component_FastLoadOptions+]
* xref:ssis.packagetask_dft_component_src.adoc#column-componentunderlinefastloadoptions[+ssis.PackageTask_Dft_Component_src.Component_FastLoadOptions+]
--


[#column-componentunderlineissortedproperty]
=== Component_IsSortedProperty

[cols="d,8a,m,m,m"]
|===
|
|Component_IsSortedProperty
|varchar(10)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis.packagetask_dft_component.adoc#column-componentunderlineissortedproperty[+ssis.PackageTask_Dft_Component.Component_IsSortedProperty+]
* xref:ssis.packagetask_dft_component_src.adoc#column-componentunderlineissortedproperty[+ssis.PackageTask_Dft_Component_src.Component_IsSortedProperty+]
--


[#column-componentunderlinename]
=== Component_name

[cols="d,8a,m,m,m"]
|===
|
|Component_name
|varchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis.packagetask_dft_component.adoc#column-componentunderlinename[+ssis.PackageTask_Dft_Component.Component_name+]
* xref:ssis.packagetask_dft_component_src.adoc#column-componentunderlinename[+ssis.PackageTask_Dft_Component_src.Component_name+]
--


[#column-componentunderlineopenrowset]
=== Component_OpenRowset

[cols="d,8a,m,m,m"]
|===
|
|Component_OpenRowset
|varchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis.packagetask_dft_component.adoc#column-componentunderlineopenrowset[+ssis.PackageTask_Dft_Component.Component_OpenRowset+]
* xref:ssis.packagetask_dft_component_src.adoc#column-componentunderlineopenrowset[+ssis.PackageTask_Dft_Component_src.Component_OpenRowset+]
--


[#column-componentunderlineopenrowsetvariable]
=== Component_OpenRowsetVariable

[cols="d,8a,m,m,m"]
|===
|
|Component_OpenRowsetVariable
|varchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis.packagetask_dft_component.adoc#column-componentunderlineopenrowsetvariable[+ssis.PackageTask_Dft_Component.Component_OpenRowsetVariable+]
* xref:ssis.packagetask_dft_component_src.adoc#column-componentunderlineopenrowsetvariable[+ssis.PackageTask_Dft_Component_src.Component_OpenRowsetVariable+]
--


[#column-componentunderlineparametermapping]
=== Component_ParameterMapping

[cols="d,8a,m,m,m"]
|===
|
|Component_ParameterMapping
|varchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis.packagetask_dft_component.adoc#column-componentunderlineparametermapping[+ssis.PackageTask_Dft_Component.Component_ParameterMapping+]
* xref:ssis.packagetask_dft_component_src.adoc#column-componentunderlineparametermapping[+ssis.PackageTask_Dft_Component_src.Component_ParameterMapping+]
--


[#column-componentunderlinesqlcommand]
=== Component_SqlCommand

[cols="d,8a,m,m,m"]
|===
|
|Component_SqlCommand
|varchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis.packagetask_dft_component.adoc#column-componentunderlinesqlcommand[+ssis.PackageTask_Dft_Component.Component_SqlCommand+]
* xref:ssis.packagetask_dft_component_src.adoc#column-componentunderlinesqlcommand[+ssis.PackageTask_Dft_Component_src.Component_SqlCommand+]
--


[#column-componentunderlinesqlcommandvariable]
=== Component_SqlCommandVariable

[cols="d,8a,m,m,m"]
|===
|
|Component_SqlCommandVariable
|varchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis.packagetask_dft_component.adoc#column-componentunderlinesqlcommandvariable[+ssis.PackageTask_Dft_Component.Component_SqlCommandVariable+]
* xref:ssis.packagetask_dft_component_src.adoc#column-componentunderlinesqlcommandvariable[+ssis.PackageTask_Dft_Component_src.Component_SqlCommandVariable+]
--


[#column-componentunderlinevariablename]
=== Component_VariableName

[cols="d,8a,m,m,m"]
|===
|
|Component_VariableName
|varchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis.packagetask_dft_component.adoc#column-componentunderlinevariablename[+ssis.PackageTask_Dft_Component.Component_VariableName+]
* xref:ssis.packagetask_dft_component_src.adoc#column-componentunderlinevariablename[+ssis.PackageTask_Dft_Component_src.Component_VariableName+]
--


[#column-controlflowdetailsrowid]
=== ControlFlowDetailsRowID

[cols="d,8a,m,m,m"]
|===
|
|ControlFlowDetailsRowID
|int
|NOT NULL
|
|===

.Referenced Columns
--
* xref:ssis.packagetask_dft_component.adoc#column-controlflowdetailsrowid[+ssis.PackageTask_Dft_Component.ControlFlowDetailsRowID+]
* xref:ssis.packagetask_dft_component_src.adoc#column-controlflowdetailsrowid[+ssis.PackageTask_Dft_Component_src.ControlFlowDetailsRowID+]
--


[#column-taskpath]
=== TaskPath

[cols="d,8a,m,m,m"]
|===
|
|TaskPath
|varchar(8000)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis.packagetask_dft_component.adoc#column-taskpath[+ssis.PackageTask_Dft_Component.TaskPath+]
* xref:ssis.packagetask_dft_component_src.adoc#column-taskpath[+ssis.PackageTask_Dft_Component_src.TaskPath+]
--


// end::AntoraColumnDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]
|1
|*<<column-antoramodule>>*
|varchar(50)
|NOT NULL
|

|2
|*<<column-packagename>>*
|varchar(200)
|NULL
|

|3
|*<<column-componentunderlinerefid>>*
|varchar(max)
|NULL
|



























// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]



|
|<<column-componentunderlineaccessmode>>
|varchar(max)
|NULL
|

|
|<<column-componentunderlinealwaysusedefaultcodepage>>
|varchar(max)
|NULL
|

|
|<<column-componentunderlinecommandtimeout>>
|int
|NULL
|

|
|<<column-componentunderlinecomponentclassid>>
|varchar(max)
|NULL
|

|
|<<column-componentunderlineconnectionunderlinedescription>>
|varchar(max)
|NULL
|

|
|<<column-componentunderlineconnectionunderlinename>>
|varchar(max)
|NULL
|

|
|<<column-componentunderlineconnectionunderlinerefid>>
|varchar(max)
|NULL
|

|
|<<column-componentunderlineconnectionmanagerid>>
|varchar(max)
|NULL
|

|
|<<column-componentunderlineconnectionmanagerrefid>>
|varchar(max)
|NULL
|

|
|<<column-componentunderlinecontactinfo>>
|varchar(max)
|NULL
|

|
|<<column-componentunderlinedefaultcodepage>>
|int
|NULL
|

|
|<<column-componentunderlinedescription>>
|varchar(max)
|NULL
|

|
|<<column-componentunderlinefastloadkeepidentity>>
|bit
|NULL
|

|
|<<column-componentunderlinefastloadkeepnulls>>
|bit
|NULL
|

|
|<<column-componentunderlinefastloadmaxinsertcommitsize>>
|int
|NULL
|

|
|<<column-componentunderlinefastloadoptions>>
|varchar(max)
|NULL
|

|
|<<column-componentunderlineissortedproperty>>
|varchar(10)
|NULL
|

|
|<<column-componentunderlinename>>
|varchar(max)
|NULL
|

|
|<<column-componentunderlineopenrowset>>
|varchar(max)
|NULL
|

|
|<<column-componentunderlineopenrowsetvariable>>
|varchar(max)
|NULL
|

|
|<<column-componentunderlineparametermapping>>
|varchar(max)
|NULL
|

|
|<<column-componentunderlinesqlcommand>>
|varchar(max)
|NULL
|

|
|<<column-componentunderlinesqlcommandvariable>>
|varchar(max)
|NULL
|

|
|<<column-componentunderlinevariablename>>
|varchar(max)
|NULL
|

|
|<<column-controlflowdetailsrowid>>
|int
|NOT NULL
|

|
|<<column-taskpath>>
|varchar(8000)
|NULL
|

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

[#index-pkunderlinepackagetaskunderlinedftunderlinecomponentunderlinetgt]
=== PK_PackageTask_Dft_Component_tgt

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-AntoraModule>>; varchar(50)
* <<column-PackageName>>; varchar(200)
* <<column-Component_refId>>; varchar(max)
--
* PK, Unique, Real: 1, 1, 0


[#index-idxunderlinepackagetaskunderlinedftunderlinecomponentunderlinetgtunderlineunderline2]
=== idx_PackageTask_Dft_Component_tgt++__++2

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-ControlFlowDetailsRowID>>; int
--
* PK, Unique, Real: 0, 0, 0


[#index-idxunderlinepackagetaskunderlinedftunderlinecomponentunderlinetgtunderlineunderline3]
=== idx_PackageTask_Dft_Component_tgt++__++3

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-AntoraModule>>; varchar(50)
* <<column-PackageName>>; varchar(200)
--
* PK, Unique, Real: 0, 0, 0


[#index-idxunderlinepackagetaskunderlinedftunderlinecomponentunderlinetgtunderlineunderline4]
=== idx_PackageTask_Dft_Component_tgt++__++4

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-AntoraModule>>; varchar(50)
--
* PK, Unique, Real: 0, 0, 0

// end::AntoraIndexList[]

== AntoraMeasureDetails

// tag::AntoraMeasureDetails[]

// end::AntoraMeasureDetails[]

== AntoraMeasureDescriptions



== AntoraParameterList

// tag::AntoraParameterList[]

// end::AntoraParameterList[]

== AntoraXrefCulturesList

// tag::AntoraXrefCulturesList[]
* xref:dhw:sqldb:ssis.packagetask_dft_component_tgt.adoc[] - 
// end::AntoraXrefCulturesList[]

== cultures_count

// tag::cultures_count[]
1
// end::cultures_count[]

== Other tags

source: property.RepoObjectProperty_cross As rop_cross


=== additional_reference_csv

// tag::additional_reference_csv[]

// end::additional_reference_csv[]


=== AdocUspSteps

// tag::adocuspsteps[]

// end::adocuspsteps[]


=== AntoraReferencedList

// tag::antorareferencedlist[]
* xref:dhw:sqldb:ssis.antoramodule_tgt_filter.adoc[]
* xref:dhw:sqldb:ssis.packagetask_dft_component_src.adoc[]
// end::antorareferencedlist[]


=== AntoraReferencingList

// tag::antorareferencinglist[]
* xref:dhw:sqldb:ssis.packagetask_dft_component.adoc[]
* xref:dhw:sqldb:ssis.usp_persist_packagetask_dft_component_tgt.adoc[]
// end::antorareferencinglist[]


=== Description

// tag::description[]

// end::description[]


=== exampleUsage

// tag::exampleusage[]

// end::exampleusage[]


=== exampleUsage_2

// tag::exampleusage_2[]

// end::exampleusage_2[]


=== exampleUsage_3

// tag::exampleusage_3[]

// end::exampleusage_3[]


=== exampleUsage_4

// tag::exampleusage_4[]

// end::exampleusage_4[]


=== exampleUsage_5

// tag::exampleusage_5[]

// end::exampleusage_5[]


=== exampleWrong_Usage

// tag::examplewrong_usage[]

// end::examplewrong_usage[]


=== has_execution_plan_issue

// tag::has_execution_plan_issue[]

// end::has_execution_plan_issue[]


=== has_get_referenced_issue

// tag::has_get_referenced_issue[]

// end::has_get_referenced_issue[]


=== has_history

// tag::has_history[]
0
// end::has_history[]


=== has_history_columns

// tag::has_history_columns[]
0
// end::has_history_columns[]


=== InheritanceType

// tag::inheritancetype[]

// end::inheritancetype[]


=== is_persistence

// tag::is_persistence[]
1
// end::is_persistence[]


=== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]
0
// end::is_persistence_check_duplicate_per_pk[]


=== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]
0
// end::is_persistence_check_for_empty_source[]


=== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]
0
// end::is_persistence_delete_changed[]


=== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]
1
// end::is_persistence_delete_missing[]


=== is_persistence_insert

// tag::is_persistence_insert[]
1
// end::is_persistence_insert[]


=== is_persistence_truncate

// tag::is_persistence_truncate[]
0
// end::is_persistence_truncate[]


=== is_persistence_update_changed

// tag::is_persistence_update_changed[]
1
// end::is_persistence_update_changed[]


=== is_repo_managed

// tag::is_repo_managed[]
0
// end::is_repo_managed[]


=== is_ssas

// tag::is_ssas[]
0
// end::is_ssas[]


=== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


=== MS_Description

// tag::ms_description[]

// end::ms_description[]


=== persistence_source_RepoObject_fullname

// tag::persistence_source_repoobject_fullname[]
[ssis].[PackageTask_Dft_Component_src]
// end::persistence_source_repoobject_fullname[]


=== persistence_source_RepoObject_fullname2

// tag::persistence_source_repoobject_fullname2[]
ssis.PackageTask_Dft_Component_src
// end::persistence_source_repoobject_fullname2[]


=== persistence_source_RepoObject_guid

// tag::persistence_source_repoobject_guid[]
B7DCAD7F-F73E-EC11-852D-A81E8446D5B0
// end::persistence_source_repoobject_guid[]


=== persistence_source_RepoObject_xref

// tag::persistence_source_repoobject_xref[]
xref:ssis.packagetask_dft_component_src.adoc[]
// end::persistence_source_repoobject_xref[]


=== pk_index_guid

// tag::pk_index_guid[]
00397997-FC3E-EC11-852D-A81E8446D5B0
// end::pk_index_guid[]


=== pk_IndexPatternColumnDatatype

// tag::pk_indexpatterncolumndatatype[]
varchar(50),varchar(200),varchar(max)
// end::pk_indexpatterncolumndatatype[]


=== pk_IndexPatternColumnName

// tag::pk_indexpatterncolumnname[]
AntoraModule,PackageName,Component_refId
// end::pk_indexpatterncolumnname[]


=== pk_IndexSemanticGroup

// tag::pk_indexsemanticgroup[]

// end::pk_indexsemanticgroup[]


=== ReferencedObjectList

// tag::referencedobjectlist[]
* [ssis].[AntoraModule_tgt_filter]
* [ssis].[PackageTask_Dft_Component]
* [ssis].[PackageTask_Dft_Component_src]
// end::referencedobjectlist[]


=== usp_persistence_RepoObject_guid

// tag::usp_persistence_repoobject_guid[]
252FAAB3-533F-EC11-852D-A81E8446D5B0
// end::usp_persistence_repoobject_guid[]


=== UspExamples

// tag::uspexamples[]

// end::uspexamples[]


=== uspgenerator_usp_id

// tag::uspgenerator_usp_id[]

// end::uspgenerator_usp_id[]


=== UspParameters

// tag::uspparameters[]

// end::uspparameters[]

== Boolean Attributes

source: property.RepoObjectProperty WHERE property_int = 1

// tag::boolean_attributes[]

:is_persistence:
:is_persistence_delete_missing:
:is_persistence_insert:
:is_persistence_update_changed:

// end::boolean_attributes[]

== PlantUML diagrams

=== PlantUML Entity

// tag::puml_entity[]
[plantuml, entity-{docname}, svg, subs=macros]
....
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_tgt.adoc[]" as ssis.PackageTask_Dft_Component_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Component_refId** : (varchar(max))
  Component_AccessMode : (varchar(max))
  Component_AlwaysUseDefaultCodePage : (varchar(max))
  Component_CommandTimeout : (int)
  Component_componentClassID : (varchar(max))
  Component_Connection_description : (varchar(max))
  Component_Connection_name : (varchar(max))
  Component_Connection_refId : (varchar(max))
  Component_connectionManagerID : (varchar(max))
  Component_connectionManagerRefId : (varchar(max))
  Component_ContactInfo : (varchar(max))
  Component_DefaultCodePage : (int)
  Component_description : (varchar(max))
  Component_FastLoadKeepIdentity : (bit)
  Component_FastLoadKeepNulls : (bit)
  Component_FastLoadMaxInsertCommitSize : (int)
  Component_FastLoadOptions : (varchar(max))
  Component_IsSortedProperty : (varchar(10))
  Component_name : (varchar(max))
  Component_OpenRowset : (varchar(max))
  Component_OpenRowsetVariable : (varchar(max))
  Component_ParameterMapping : (varchar(max))
  Component_SqlCommand : (varchar(max))
  Component_SqlCommandVariable : (varchar(max))
  Component_VariableName : (varchar(max))
  - ControlFlowDetailsRowID : (int)
  TaskPath : (varchar(8000))
  --
}
....

// end::puml_entity[]

=== PlantUML Entity 1 1 FK

// tag::puml_entity_1_1_fk[]
[plantuml, entity_1_1_fk-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_tgt.adoc[]" as ssis.PackageTask_Dft_Component_tgt << V >> {
- **PK_PackageTask_Dft_Component_tgt**

..
AntoraModule; varchar(50)
PackageName; varchar(200)
Component_refId; varchar(max)
--
- idx_PackageTask_Dft_Component_tgt__2

..
ControlFlowDetailsRowID; int
--
- idx_PackageTask_Dft_Component_tgt__3

..
AntoraModule; varchar(50)
PackageName; varchar(200)
--
- idx_PackageTask_Dft_Component_tgt__4

..
AntoraModule; varchar(50)
}



footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_fk[]

=== PlantUML 1 1 ObjectRef

// tag::puml_entity_1_1_objectref[]
[plantuml, entity_1_1_objectref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis.antoramodule_tgt_filter.adoc[]" as ssis.AntoraModule_tgt_filter << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component.adoc[]" as ssis.PackageTask_Dft_Component << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_src.adoc[]" as ssis.PackageTask_Dft_Component_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Component_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_tgt.adoc[]" as ssis.PackageTask_Dft_Component_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Component_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packagetask_dft_component_tgt.adoc[]" as ssis.usp_PERSIST_PackageTask_Dft_Component_tgt << P >> {
  --
}

ssis.AntoraModule_tgt_filter <.. ssis.PackageTask_Dft_Component_tgt
ssis.PackageTask_Dft_Component_src <.. ssis.PackageTask_Dft_Component_tgt
ssis.PackageTask_Dft_Component_tgt <.. ssis.PackageTask_Dft_Component
ssis.PackageTask_Dft_Component_tgt <.. ssis.usp_PERSIST_PackageTask_Dft_Component_tgt

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_objectref[]

=== PlantUML 30 0 ObjectRef

// tag::puml_entity_30_0_objectref[]
[plantuml, entity_30_0_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis.antoramodule_tgt_filter.adoc[]" as ssis.AntoraModule_tgt_filter << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.package_src.adoc[]" as ssis.Package_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_src.adoc[]" as ssis.PackageTask_Dft_Component_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Component_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_tgt.adoc[]" as ssis.PackageTask_Dft_Component_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Component_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.project.adoc[]" as ssis.Project << U >> {
  - **AntoraModule** : (varchar(50))
  --
}

entity "puml-link:dhw:sqldb:ssis_t.pkgstats.adoc[]" as ssis_t.pkgStats << U >> {
  - **RowID** : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tblcontrolflow.adoc[]" as ssis_t.TblControlFlow << U >> {
  - **ControlFlowDetailsRowID** : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_dft_component.adoc[]" as ssis_t.TblTask_Dft_Component << U >> {
  - **DftComponentId** : (int)
  --
}

ssis.AntoraModule_tgt_filter <.. ssis.PackageTask_Dft_Component_tgt
ssis.Package_src <.. ssis.PackageTask_Dft_Component_src
ssis.Package_src <.. ssis.AntoraModule_tgt_filter
ssis.PackageTask_Dft_Component_src <.. ssis.PackageTask_Dft_Component_tgt
ssis.Project <.. ssis.Package_src
ssis_t.pkgStats <.. ssis.Package_src
ssis_t.TblControlFlow <.. ssis.PackageTask_Dft_Component_src
ssis_t.TblTask_Dft_Component <.. ssis.PackageTask_Dft_Component_src

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_30_0_objectref[]

=== PlantUML 0 30 ObjectRef

// tag::puml_entity_0_30_objectref[]
[plantuml, entity_0_30_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:docs.ssis_adoc.adoc[]" as docs.ssis_Adoc << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageBasename** : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_adoc_t.adoc[]" as docs.ssis_Adoc_T << U >> {
  - **AntoraModule** : (varchar(50))
  - **PackageBasename** : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_dfttaskcomponentlist.adoc[]" as docs.ssis_DftTaskComponentList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_pumldfttask.adoc[]" as docs.ssis_PumlDftTask << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_pumlpartialdftcomponent.adoc[]" as docs.ssis_PumlPartialDftComponent << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_task.adoc[]" as docs.ssis_Task << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_tasklist.adoc[]" as docs.ssis_TaskList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport.adoc[]" as docs.usp_AntoraExport << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_ssispartialscontent.adoc[]" as docs.usp_AntoraExport_SsisPartialsContent << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_ssis_adoc_t.adoc[]" as docs.usp_PERSIST_ssis_Adoc_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component.adoc[]" as ssis.PackageTask_Dft_Component << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_tgt.adoc[]" as ssis.PackageTask_Dft_Component_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Component_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_import.adoc[]" as ssis.usp_import << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packagetask_dft_component_tgt.adoc[]" as ssis.usp_PERSIST_PackageTask_Dft_Component_tgt << P >> {
  --
}

docs.ssis_Adoc <.. docs.usp_PERSIST_ssis_Adoc_T
docs.ssis_Adoc <.. docs.ssis_Adoc_T
docs.ssis_Adoc_T <.. docs.usp_AntoraExport_SsisPartialsContent
docs.ssis_Adoc_T <.. docs.usp_PERSIST_ssis_Adoc_T
docs.ssis_DftTaskComponentList <.. docs.ssis_TaskList
docs.ssis_DftTaskComponentList <.. docs.ssis_Task
docs.ssis_PumlDftTask <.. docs.ssis_TaskList
docs.ssis_PumlDftTask <.. docs.ssis_Task
docs.ssis_PumlPartialDftComponent <.. docs.ssis_PumlDftTask
docs.ssis_PumlPartialDftComponent <.. docs.ssis_DftTaskComponentList
docs.ssis_TaskList <.. docs.ssis_Adoc
docs.usp_AntoraExport_SsisPartialsContent <.. docs.usp_AntoraExport
docs.usp_PERSIST_ssis_Adoc_T <.. docs.usp_AntoraExport_SsisPartialsContent
ssis.PackageTask_Dft_Component <.. docs.ssis_DftTaskComponentList
ssis.PackageTask_Dft_Component <.. docs.ssis_PumlPartialDftComponent
ssis.PackageTask_Dft_Component <.. docs.ssis_PumlDftTask
ssis.PackageTask_Dft_Component_tgt <.. ssis.usp_PERSIST_PackageTask_Dft_Component_tgt
ssis.PackageTask_Dft_Component_tgt <.. ssis.PackageTask_Dft_Component
ssis.usp_PERSIST_PackageTask_Dft_Component_tgt <.. ssis.usp_import

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_0_30_objectref[]

=== PlantUML 1 1 ColumnRef

// tag::puml_entity_1_1_colref[]
[plantuml, entity_1_1_colref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis.antoramodule_tgt_filter.adoc[]" as ssis.AntoraModule_tgt_filter << V >> {
  - AntoraModule : (varchar(50))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component.adoc[]" as ssis.PackageTask_Dft_Component << U >> {
  - AntoraModule : (varchar(50))
  Component_AccessMode : (varchar(max))
  Component_AlwaysUseDefaultCodePage : (varchar(max))
  Component_CommandTimeout : (int)
  Component_componentClassID : (varchar(max))
  Component_Connection_description : (varchar(max))
  Component_Connection_name : (varchar(max))
  Component_Connection_refId : (varchar(max))
  Component_connectionManagerID : (varchar(max))
  Component_connectionManagerRefId : (varchar(max))
  Component_ContactInfo : (varchar(max))
  Component_DefaultCodePage : (int)
  Component_description : (varchar(max))
  Component_FastLoadKeepIdentity : (bit)
  Component_FastLoadKeepNulls : (bit)
  Component_FastLoadMaxInsertCommitSize : (int)
  Component_FastLoadOptions : (varchar(max))
  Component_IsSortedProperty : (varchar(10))
  - Component_name : (varchar(max))
  Component_OpenRowset : (varchar(max))
  Component_OpenRowsetVariable : (varchar(max))
  Component_ParameterMapping : (varchar(max))
  - Component_refId : (varchar(max))
  Component_SqlCommand : (varchar(max))
  Component_SqlCommandVariable : (varchar(max))
  Component_VariableName : (varchar(max))
  - ControlFlowDetailsRowID : (int)
  - PackageName : (varchar(200))
  - TaskPath : (varchar(8000))
  ~ Component_ConnectionManagerName : (varchar(max))
  # PackageBasename : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_src.adoc[]" as ssis.PackageTask_Dft_Component_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Component_refId** : (varchar(max))
  Component_AccessMode : (varchar(max))
  Component_AlwaysUseDefaultCodePage : (varchar(max))
  Component_CommandTimeout : (int)
  Component_componentClassID : (varchar(max))
  Component_Connection_description : (varchar(max))
  Component_Connection_name : (varchar(max))
  Component_Connection_refId : (varchar(max))
  Component_connectionManagerID : (varchar(max))
  Component_connectionManagerRefId : (varchar(max))
  Component_ContactInfo : (varchar(max))
  Component_DefaultCodePage : (int)
  Component_description : (varchar(max))
  Component_FastLoadKeepIdentity : (bit)
  Component_FastLoadKeepNulls : (bit)
  Component_FastLoadMaxInsertCommitSize : (int)
  Component_FastLoadOptions : (varchar(max))
  Component_IsSortedProperty : (varchar(10))
  Component_name : (varchar(max))
  Component_OpenRowset : (varchar(max))
  Component_OpenRowsetVariable : (varchar(max))
  Component_ParameterMapping : (varchar(max))
  Component_SqlCommand : (varchar(max))
  Component_SqlCommandVariable : (varchar(max))
  Component_VariableName : (varchar(max))
  - ControlFlowDetailsRowID : (int)
  TaskPath : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_tgt.adoc[]" as ssis.PackageTask_Dft_Component_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Component_refId** : (varchar(max))
  Component_AccessMode : (varchar(max))
  Component_AlwaysUseDefaultCodePage : (varchar(max))
  Component_CommandTimeout : (int)
  Component_componentClassID : (varchar(max))
  Component_Connection_description : (varchar(max))
  Component_Connection_name : (varchar(max))
  Component_Connection_refId : (varchar(max))
  Component_connectionManagerID : (varchar(max))
  Component_connectionManagerRefId : (varchar(max))
  Component_ContactInfo : (varchar(max))
  Component_DefaultCodePage : (int)
  Component_description : (varchar(max))
  Component_FastLoadKeepIdentity : (bit)
  Component_FastLoadKeepNulls : (bit)
  Component_FastLoadMaxInsertCommitSize : (int)
  Component_FastLoadOptions : (varchar(max))
  Component_IsSortedProperty : (varchar(10))
  Component_name : (varchar(max))
  Component_OpenRowset : (varchar(max))
  Component_OpenRowsetVariable : (varchar(max))
  Component_ParameterMapping : (varchar(max))
  Component_SqlCommand : (varchar(max))
  Component_SqlCommandVariable : (varchar(max))
  Component_VariableName : (varchar(max))
  - ControlFlowDetailsRowID : (int)
  TaskPath : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packagetask_dft_component_tgt.adoc[]" as ssis.usp_PERSIST_PackageTask_Dft_Component_tgt << P >> {
  --
}

ssis.AntoraModule_tgt_filter <.. ssis.PackageTask_Dft_Component_tgt
ssis.PackageTask_Dft_Component_src <.. ssis.PackageTask_Dft_Component_tgt
ssis.PackageTask_Dft_Component_tgt <.. ssis.PackageTask_Dft_Component
ssis.PackageTask_Dft_Component_tgt <.. ssis.usp_PERSIST_PackageTask_Dft_Component_tgt
"ssis.PackageTask_Dft_Component::AntoraModule" <-- "ssis.PackageTask_Dft_Component_tgt::AntoraModule"
"ssis.PackageTask_Dft_Component::Component_AccessMode" <-- "ssis.PackageTask_Dft_Component_tgt::Component_AccessMode"
"ssis.PackageTask_Dft_Component::Component_AlwaysUseDefaultCodePage" <-- "ssis.PackageTask_Dft_Component_tgt::Component_AlwaysUseDefaultCodePage"
"ssis.PackageTask_Dft_Component::Component_CommandTimeout" <-- "ssis.PackageTask_Dft_Component_tgt::Component_CommandTimeout"
"ssis.PackageTask_Dft_Component::Component_componentClassID" <-- "ssis.PackageTask_Dft_Component_tgt::Component_componentClassID"
"ssis.PackageTask_Dft_Component::Component_Connection_description" <-- "ssis.PackageTask_Dft_Component_tgt::Component_Connection_description"
"ssis.PackageTask_Dft_Component::Component_Connection_name" <-- "ssis.PackageTask_Dft_Component_tgt::Component_Connection_name"
"ssis.PackageTask_Dft_Component::Component_Connection_refId" <-- "ssis.PackageTask_Dft_Component_tgt::Component_Connection_refId"
"ssis.PackageTask_Dft_Component::Component_connectionManagerID" <-- "ssis.PackageTask_Dft_Component_tgt::Component_connectionManagerID"
"ssis.PackageTask_Dft_Component::Component_connectionManagerRefId" <-- "ssis.PackageTask_Dft_Component_tgt::Component_connectionManagerRefId"
"ssis.PackageTask_Dft_Component::Component_ContactInfo" <-- "ssis.PackageTask_Dft_Component_tgt::Component_ContactInfo"
"ssis.PackageTask_Dft_Component::Component_DefaultCodePage" <-- "ssis.PackageTask_Dft_Component_tgt::Component_DefaultCodePage"
"ssis.PackageTask_Dft_Component::Component_description" <-- "ssis.PackageTask_Dft_Component_tgt::Component_description"
"ssis.PackageTask_Dft_Component::Component_FastLoadKeepIdentity" <-- "ssis.PackageTask_Dft_Component_tgt::Component_FastLoadKeepIdentity"
"ssis.PackageTask_Dft_Component::Component_FastLoadKeepNulls" <-- "ssis.PackageTask_Dft_Component_tgt::Component_FastLoadKeepNulls"
"ssis.PackageTask_Dft_Component::Component_FastLoadMaxInsertCommitSize" <-- "ssis.PackageTask_Dft_Component_tgt::Component_FastLoadMaxInsertCommitSize"
"ssis.PackageTask_Dft_Component::Component_FastLoadOptions" <-- "ssis.PackageTask_Dft_Component_tgt::Component_FastLoadOptions"
"ssis.PackageTask_Dft_Component::Component_IsSortedProperty" <-- "ssis.PackageTask_Dft_Component_tgt::Component_IsSortedProperty"
"ssis.PackageTask_Dft_Component::Component_name" <-- "ssis.PackageTask_Dft_Component_tgt::Component_name"
"ssis.PackageTask_Dft_Component::Component_OpenRowset" <-- "ssis.PackageTask_Dft_Component_tgt::Component_OpenRowset"
"ssis.PackageTask_Dft_Component::Component_OpenRowsetVariable" <-- "ssis.PackageTask_Dft_Component_tgt::Component_OpenRowsetVariable"
"ssis.PackageTask_Dft_Component::Component_ParameterMapping" <-- "ssis.PackageTask_Dft_Component_tgt::Component_ParameterMapping"
"ssis.PackageTask_Dft_Component::Component_refId" <-- "ssis.PackageTask_Dft_Component_tgt::Component_refId"
"ssis.PackageTask_Dft_Component::Component_SqlCommand" <-- "ssis.PackageTask_Dft_Component_tgt::Component_SqlCommand"
"ssis.PackageTask_Dft_Component::Component_SqlCommandVariable" <-- "ssis.PackageTask_Dft_Component_tgt::Component_SqlCommandVariable"
"ssis.PackageTask_Dft_Component::Component_VariableName" <-- "ssis.PackageTask_Dft_Component_tgt::Component_VariableName"
"ssis.PackageTask_Dft_Component::ControlFlowDetailsRowID" <-- "ssis.PackageTask_Dft_Component_tgt::ControlFlowDetailsRowID"
"ssis.PackageTask_Dft_Component::PackageName" <-- "ssis.PackageTask_Dft_Component_tgt::PackageName"
"ssis.PackageTask_Dft_Component::TaskPath" <-- "ssis.PackageTask_Dft_Component_tgt::TaskPath"
"ssis.PackageTask_Dft_Component_src::AntoraModule" <-- "ssis.PackageTask_Dft_Component_tgt::AntoraModule"
"ssis.PackageTask_Dft_Component_src::Component_AccessMode" <-- "ssis.PackageTask_Dft_Component_tgt::Component_AccessMode"
"ssis.PackageTask_Dft_Component_src::Component_AlwaysUseDefaultCodePage" <-- "ssis.PackageTask_Dft_Component_tgt::Component_AlwaysUseDefaultCodePage"
"ssis.PackageTask_Dft_Component_src::Component_CommandTimeout" <-- "ssis.PackageTask_Dft_Component_tgt::Component_CommandTimeout"
"ssis.PackageTask_Dft_Component_src::Component_componentClassID" <-- "ssis.PackageTask_Dft_Component_tgt::Component_componentClassID"
"ssis.PackageTask_Dft_Component_src::Component_Connection_description" <-- "ssis.PackageTask_Dft_Component_tgt::Component_Connection_description"
"ssis.PackageTask_Dft_Component_src::Component_Connection_name" <-- "ssis.PackageTask_Dft_Component_tgt::Component_Connection_name"
"ssis.PackageTask_Dft_Component_src::Component_Connection_refId" <-- "ssis.PackageTask_Dft_Component_tgt::Component_Connection_refId"
"ssis.PackageTask_Dft_Component_src::Component_connectionManagerID" <-- "ssis.PackageTask_Dft_Component_tgt::Component_connectionManagerID"
"ssis.PackageTask_Dft_Component_src::Component_connectionManagerRefId" <-- "ssis.PackageTask_Dft_Component_tgt::Component_connectionManagerRefId"
"ssis.PackageTask_Dft_Component_src::Component_ContactInfo" <-- "ssis.PackageTask_Dft_Component_tgt::Component_ContactInfo"
"ssis.PackageTask_Dft_Component_src::Component_DefaultCodePage" <-- "ssis.PackageTask_Dft_Component_tgt::Component_DefaultCodePage"
"ssis.PackageTask_Dft_Component_src::Component_description" <-- "ssis.PackageTask_Dft_Component_tgt::Component_description"
"ssis.PackageTask_Dft_Component_src::Component_FastLoadKeepIdentity" <-- "ssis.PackageTask_Dft_Component_tgt::Component_FastLoadKeepIdentity"
"ssis.PackageTask_Dft_Component_src::Component_FastLoadKeepNulls" <-- "ssis.PackageTask_Dft_Component_tgt::Component_FastLoadKeepNulls"
"ssis.PackageTask_Dft_Component_src::Component_FastLoadMaxInsertCommitSize" <-- "ssis.PackageTask_Dft_Component_tgt::Component_FastLoadMaxInsertCommitSize"
"ssis.PackageTask_Dft_Component_src::Component_FastLoadOptions" <-- "ssis.PackageTask_Dft_Component_tgt::Component_FastLoadOptions"
"ssis.PackageTask_Dft_Component_src::Component_IsSortedProperty" <-- "ssis.PackageTask_Dft_Component_tgt::Component_IsSortedProperty"
"ssis.PackageTask_Dft_Component_src::Component_name" <-- "ssis.PackageTask_Dft_Component_tgt::Component_name"
"ssis.PackageTask_Dft_Component_src::Component_OpenRowset" <-- "ssis.PackageTask_Dft_Component_tgt::Component_OpenRowset"
"ssis.PackageTask_Dft_Component_src::Component_OpenRowsetVariable" <-- "ssis.PackageTask_Dft_Component_tgt::Component_OpenRowsetVariable"
"ssis.PackageTask_Dft_Component_src::Component_ParameterMapping" <-- "ssis.PackageTask_Dft_Component_tgt::Component_ParameterMapping"
"ssis.PackageTask_Dft_Component_src::Component_refId" <-- "ssis.PackageTask_Dft_Component_tgt::Component_refId"
"ssis.PackageTask_Dft_Component_src::Component_SqlCommand" <-- "ssis.PackageTask_Dft_Component_tgt::Component_SqlCommand"
"ssis.PackageTask_Dft_Component_src::Component_SqlCommandVariable" <-- "ssis.PackageTask_Dft_Component_tgt::Component_SqlCommandVariable"
"ssis.PackageTask_Dft_Component_src::Component_VariableName" <-- "ssis.PackageTask_Dft_Component_tgt::Component_VariableName"
"ssis.PackageTask_Dft_Component_src::ControlFlowDetailsRowID" <-- "ssis.PackageTask_Dft_Component_tgt::ControlFlowDetailsRowID"
"ssis.PackageTask_Dft_Component_src::PackageName" <-- "ssis.PackageTask_Dft_Component_tgt::PackageName"
"ssis.PackageTask_Dft_Component_src::TaskPath" <-- "ssis.PackageTask_Dft_Component_tgt::TaskPath"

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_colref[]


== sql_modules_definition

// tag::sql_modules_definition[]
[%collapsible]
=======
[source,sql,numbered,indent=0]
----

CREATE View [ssis].[PackageTask_Dft_Component_tgt]
As
Select
    tgt.AntoraModule
  , tgt.PackageName
  , tgt.Component_refId
  , tgt.Component_name
  , tgt.Component_componentClassID
  , tgt.Component_description
  , tgt.Component_ContactInfo
  , tgt.Component_CommandTimeout
  , tgt.Component_OpenRowset
  , tgt.Component_OpenRowsetVariable
  , tgt.Component_SqlCommand
  , tgt.Component_SqlCommandVariable
  , tgt.Component_DefaultCodePage
  , tgt.Component_AlwaysUseDefaultCodePage
  , tgt.Component_AccessMode
  , tgt.Component_ParameterMapping
  , tgt.Component_FastLoadKeepIdentity
  , tgt.Component_FastLoadKeepNulls
  , tgt.Component_FastLoadOptions
  , tgt.Component_FastLoadMaxInsertCommitSize
  , tgt.Component_VariableName
  , tgt.Component_Connection_refId
  , tgt.Component_connectionManagerID
  , tgt.Component_connectionManagerRefId
  , tgt.Component_Connection_description
  , tgt.Component_Connection_name
  , tgt.Component_IsSortedProperty
  , tgt.TaskPath
  , tgt.ControlFlowDetailsRowID
From
    ssis.PackageTask_Dft_Component As tgt
Where
    Exists
(
    Select
        1
    From
        ssis.AntoraModule_tgt_filter As f
    Where
        tgt.AntoraModule = f.AntoraModule
)

----
=======
// end::sql_modules_definition[]


