// tag::HeaderFullDisplayName[]
= ssis_t.TblConnection - U
// end::HeaderFullDisplayName[]

== existing_properties

// tag::existing_properties[]

:ExistsProperty--antorareferencinglist:
:ExistsProperty--is_repo_managed:
:ExistsProperty--is_ssas:
:ExistsProperty--FK:
:ExistsProperty--Columns:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
7C64FBE4-113B-EC11-852C-A81E8446D5B0
// end::RepoObject_guid[]

== RepoObject_FullDisplayName2

// tag::RepoObject_FullDisplayName2[]
ssis_t.TblConnection
// end::RepoObject_FullDisplayName2[]

== SysObject_type

// tag::SysObject_type[]
U 
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
user table
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
1701633155
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2022-09-05 18:18:08
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]
[discrete]
== _


[#column-category]
=== Category

[cols="d,8a,m,m,m"]
|===
|
|Category
|varchar(10)
|NOT NULL
|
|===


[#column-connectionmanagerid]
=== ConnectionManagerID

[cols="d,8a,m,m,m"]
|===
|
|ConnectionManagerID
|uniqueidentifier
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packageconnection_src.adoc#column-connectionmanagerid[+ssis.PackageConnection_src.ConnectionManagerID+]
--


[#column-connectionmanagername]
=== ConnectionManagerName

[cols="d,8a,m,m,m"]
|===
|
|ConnectionManagerName
|varchar(max)
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packageconnection_src.adoc#column-connectionmanagername[+ssis.PackageConnection_src.ConnectionManagerName+]
--


[#column-connectionmanagertype]
=== ConnectionManagerType

[cols="d,8a,m,m,m"]
|===
|
|ConnectionManagerType
|varchar(max)
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packageconnection_src.adoc#column-connectionmanagertype[+ssis.PackageConnection_src.ConnectionManagerType+]
--


[#column-connectionstring]
=== ConnectionString

[cols="d,8a,m,m,m"]
|===
|
|ConnectionString
|varchar(max)
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packageconnection_src.adoc#column-connectionstring[+ssis.PackageConnection_src.ConnectionString+]
--


[#column-delayvalidationpropertyvalue]
=== DelayValidationPropertyValue

[cols="d,8a,m,m,m"]
|===
|
|DelayValidationPropertyValue
|varchar(2)
|NOT NULL
|
|===


[#column-expressionvalue]
=== ExpressionValue

[cols="d,8a,m,m,m"]
|===
|
|ExpressionValue
|varchar(max)
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packageconnection_src.adoc#column-expressionvalue[+ssis.PackageConnection_src.ExpressionValue+]
--


[#column-packagecreatorname]
=== PackageCreatorName

[cols="d,8a,m,m,m"]
|===
|
|PackageCreatorName
|varchar(1000)
|NULL
|
|===


[#column-packagename]
=== PackageName

[cols="d,8a,m,m,m"]
|===
|
|PackageName
|varchar(8000)
|NULL
|
|===


[#column-packagepath]
=== PackagePath

[cols="d,8a,m,m,m"]
|===
|
|PackagePath
|varchar(8000)
|NOT NULL
|
|===


[#column-retainsameconnectionproperty]
=== RetainSameConnectionProperty

[cols="d,8a,m,m,m"]
|===
|
|RetainSameConnectionProperty
|nvarchar(max)
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packageconnection_src.adoc#column-retainsameconnectionproperty[+ssis.PackageConnection_src.RetainSameConnectionProperty+]
--


[#column-rowid]
=== RowID

[cols="d,8a,m,m,m"]
|===
|
|RowID
|int
|NOT NULL
|
|===


// end::AntoraColumnDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]












// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]
|
|<<column-category>>
|varchar(10)
|NOT NULL
|

|
|<<column-connectionmanagerid>>
|uniqueidentifier
|NULL
|

|
|<<column-connectionmanagername>>
|varchar(max)
|NULL
|

|
|<<column-connectionmanagertype>>
|varchar(max)
|NULL
|

|
|<<column-connectionstring>>
|varchar(max)
|NULL
|

|
|<<column-delayvalidationpropertyvalue>>
|varchar(2)
|NOT NULL
|

|
|<<column-expressionvalue>>
|varchar(max)
|NULL
|

|
|<<column-packagecreatorname>>
|varchar(1000)
|NULL
|

|
|<<column-packagename>>
|varchar(8000)
|NULL
|

|
|<<column-packagepath>>
|varchar(8000)
|NOT NULL
|

|
|<<column-retainsameconnectionproperty>>
|nvarchar(max)
|NULL
|

|
|<<column-rowid>>
|int
|NOT NULL
|

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

// end::AntoraIndexList[]

== AntoraMeasureDetails

// tag::AntoraMeasureDetails[]

// end::AntoraMeasureDetails[]

== AntoraMeasureDescriptions



== AntoraParameterList

// tag::AntoraParameterList[]

// end::AntoraParameterList[]

== AntoraXrefCulturesList

// tag::AntoraXrefCulturesList[]
* xref:dhw:sqldb:ssis_t.tblconnection.adoc[] - 
// end::AntoraXrefCulturesList[]

== cultures_count

// tag::cultures_count[]
1
// end::cultures_count[]

== Other tags

source: property.RepoObjectProperty_cross As rop_cross


=== additional_reference_csv

// tag::additional_reference_csv[]

// end::additional_reference_csv[]


=== AdocUspSteps

// tag::adocuspsteps[]

// end::adocuspsteps[]


=== AntoraReferencedList

// tag::antorareferencedlist[]

// end::antorareferencedlist[]


=== AntoraReferencingList

// tag::antorareferencinglist[]
* xref:dhw:sqldb:ssis.packageconnection_src.adoc[]
* xref:dhw:sqldb:ssis_t.usp_getpackagedetails.adoc[]
* xref:dhw:sqldb:ssis_t.usp_packageanalysis.adoc[]
// end::antorareferencinglist[]


=== Description

// tag::description[]

// end::description[]


=== exampleUsage

// tag::exampleusage[]

// end::exampleusage[]


=== exampleUsage_2

// tag::exampleusage_2[]

// end::exampleusage_2[]


=== exampleUsage_3

// tag::exampleusage_3[]

// end::exampleusage_3[]


=== exampleUsage_4

// tag::exampleusage_4[]

// end::exampleusage_4[]


=== exampleUsage_5

// tag::exampleusage_5[]

// end::exampleusage_5[]


=== exampleWrong_Usage

// tag::examplewrong_usage[]

// end::examplewrong_usage[]


=== has_execution_plan_issue

// tag::has_execution_plan_issue[]

// end::has_execution_plan_issue[]


=== has_get_referenced_issue

// tag::has_get_referenced_issue[]

// end::has_get_referenced_issue[]


=== has_history

// tag::has_history[]

// end::has_history[]


=== has_history_columns

// tag::has_history_columns[]

// end::has_history_columns[]


=== InheritanceType

// tag::inheritancetype[]

// end::inheritancetype[]


=== is_persistence

// tag::is_persistence[]

// end::is_persistence[]


=== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]

// end::is_persistence_check_duplicate_per_pk[]


=== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]

// end::is_persistence_check_for_empty_source[]


=== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]

// end::is_persistence_delete_changed[]


=== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]

// end::is_persistence_delete_missing[]


=== is_persistence_insert

// tag::is_persistence_insert[]

// end::is_persistence_insert[]


=== is_persistence_truncate

// tag::is_persistence_truncate[]

// end::is_persistence_truncate[]


=== is_persistence_update_changed

// tag::is_persistence_update_changed[]

// end::is_persistence_update_changed[]


=== is_repo_managed

// tag::is_repo_managed[]
0
// end::is_repo_managed[]


=== is_ssas

// tag::is_ssas[]
0
// end::is_ssas[]


=== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


=== MS_Description

// tag::ms_description[]

// end::ms_description[]


=== persistence_source_RepoObject_fullname

// tag::persistence_source_repoobject_fullname[]

// end::persistence_source_repoobject_fullname[]


=== persistence_source_RepoObject_fullname2

// tag::persistence_source_repoobject_fullname2[]

// end::persistence_source_repoobject_fullname2[]


=== persistence_source_RepoObject_guid

// tag::persistence_source_repoobject_guid[]

// end::persistence_source_repoobject_guid[]


=== persistence_source_RepoObject_xref

// tag::persistence_source_repoobject_xref[]

// end::persistence_source_repoobject_xref[]


=== pk_index_guid

// tag::pk_index_guid[]

// end::pk_index_guid[]


=== pk_IndexPatternColumnDatatype

// tag::pk_indexpatterncolumndatatype[]

// end::pk_indexpatterncolumndatatype[]


=== pk_IndexPatternColumnName

// tag::pk_indexpatterncolumnname[]

// end::pk_indexpatterncolumnname[]


=== pk_IndexSemanticGroup

// tag::pk_indexsemanticgroup[]

// end::pk_indexsemanticgroup[]


=== ReferencedObjectList

// tag::referencedobjectlist[]

// end::referencedobjectlist[]


=== usp_persistence_RepoObject_guid

// tag::usp_persistence_repoobject_guid[]

// end::usp_persistence_repoobject_guid[]


=== UspExamples

// tag::uspexamples[]

// end::uspexamples[]


=== uspgenerator_usp_id

// tag::uspgenerator_usp_id[]

// end::uspgenerator_usp_id[]


=== UspParameters

// tag::uspparameters[]

// end::uspparameters[]

== Boolean Attributes

source: property.RepoObjectProperty WHERE property_int = 1

// tag::boolean_attributes[]


// end::boolean_attributes[]

== PlantUML diagrams

=== PlantUML Entity

// tag::puml_entity[]
[plantuml, entity-{docname}, svg, subs=macros]
....
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis_t.tblconnection.adoc[]" as ssis_t.TblConnection << U >> {
  - Category : (varchar(10))
  ConnectionManagerID : (uniqueidentifier)
  ConnectionManagerName : (varchar(max))
  ConnectionManagerType : (varchar(max))
  ConnectionString : (varchar(max))
  - DelayValidationPropertyValue : (varchar(2))
  ExpressionValue : (varchar(max))
  PackageCreatorName : (varchar(1000))
  PackageName : (varchar(8000))
  - PackagePath : (varchar(8000))
  RetainSameConnectionProperty : (nvarchar(max))
  - RowID : (int)
  --
}
....

// end::puml_entity[]

=== PlantUML Entity 1 1 FK

// tag::puml_entity_1_1_fk[]
[plantuml, entity_1_1_fk-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis_t.tblconnection.adoc[]" as ssis_t.TblConnection << U >> {

}



footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_fk[]

=== PlantUML 1 1 ObjectRef

// tag::puml_entity_1_1_objectref[]
[plantuml, entity_1_1_objectref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis.packageconnection_src.adoc[]" as ssis.PackageConnection_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **ConnectionManagerID** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tblconnection.adoc[]" as ssis_t.TblConnection << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.usp_getpackagedetails.adoc[]" as ssis_t.usp_GetPackageDetails << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.usp_packageanalysis.adoc[]" as ssis_t.usp_PackageAnalysis << P >> {
  --
}

ssis_t.TblConnection <.. ssis.PackageConnection_src
ssis_t.TblConnection <.. ssis_t.usp_GetPackageDetails
ssis_t.TblConnection <.. ssis_t.usp_PackageAnalysis

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_objectref[]

=== PlantUML 30 0 ObjectRef

// tag::puml_entity_30_0_objectref[]
[plantuml, entity_30_0_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis_t.tblconnection.adoc[]" as ssis_t.TblConnection << U >> {
  --
}



footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_30_0_objectref[]

=== PlantUML 0 30 ObjectRef

// tag::puml_entity_0_30_objectref[]
[plantuml, entity_0_30_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:docs.ssis_adoc.adoc[]" as docs.ssis_Adoc << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageBasename** : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_adoc_t.adoc[]" as docs.ssis_Adoc_T << U >> {
  - **AntoraModule** : (varchar(50))
  - **PackageBasename** : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_packageconnectionlist.adoc[]" as docs.ssis_PackageConnectionList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_task.adoc[]" as docs.ssis_Task << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_tasklist.adoc[]" as docs.ssis_TaskList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport.adoc[]" as docs.usp_AntoraExport << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_ssispartialscontent.adoc[]" as docs.usp_AntoraExport_SsisPartialsContent << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_ssis_adoc_t.adoc[]" as docs.usp_PERSIST_ssis_Adoc_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.packageconnection.adoc[]" as ssis.PackageConnection << U >> {
  - **AntoraModule** : (varchar(50))
  - **PackageName** : (varchar(200))
  - **ConnectionManagerID** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:ssis.packageconnection_src.adoc[]" as ssis.PackageConnection_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **ConnectionManagerID** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:ssis.packageconnection_tgt.adoc[]" as ssis.PackageConnection_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  - **PackageName** : (varchar(200))
  - **ConnectionManagerID** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_import.adoc[]" as ssis.usp_import << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packageconnection_tgt.adoc[]" as ssis.usp_PERSIST_PackageConnection_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tblconnection.adoc[]" as ssis_t.TblConnection << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.usp_getpackagedetails.adoc[]" as ssis_t.usp_GetPackageDetails << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.usp_packageanalysis.adoc[]" as ssis_t.usp_PackageAnalysis << P >> {
  --
}

docs.ssis_Adoc <.. docs.ssis_Adoc_T
docs.ssis_Adoc <.. docs.usp_PERSIST_ssis_Adoc_T
docs.ssis_Adoc_T <.. docs.usp_AntoraExport_SsisPartialsContent
docs.ssis_Adoc_T <.. docs.usp_PERSIST_ssis_Adoc_T
docs.ssis_PackageConnectionList <.. docs.ssis_Adoc
docs.ssis_TaskList <.. docs.ssis_Adoc
docs.usp_AntoraExport_SsisPartialsContent <.. docs.usp_AntoraExport
docs.usp_PERSIST_ssis_Adoc_T <.. docs.usp_AntoraExport_SsisPartialsContent
ssis.PackageConnection <.. docs.ssis_PackageConnectionList
ssis.PackageConnection <.. docs.ssis_Task
ssis.PackageConnection <.. docs.ssis_TaskList
ssis.PackageConnection_src <.. ssis.PackageConnection_tgt
ssis.PackageConnection_src <.. ssis.usp_PERSIST_PackageConnection_tgt
ssis.PackageConnection_tgt <.. ssis.PackageConnection
ssis.PackageConnection_tgt <.. ssis.usp_PERSIST_PackageConnection_tgt
ssis.usp_PERSIST_PackageConnection_tgt <.. ssis.usp_import
ssis_t.TblConnection <.. ssis.PackageConnection_src
ssis_t.TblConnection <.. ssis_t.usp_GetPackageDetails
ssis_t.TblConnection <.. ssis_t.usp_PackageAnalysis

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_0_30_objectref[]

=== PlantUML 1 1 ColumnRef

// tag::puml_entity_1_1_colref[]
[plantuml, entity_1_1_colref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis.packageconnection_src.adoc[]" as ssis.PackageConnection_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **ConnectionManagerID** : (uniqueidentifier)
  ConnectionManagerName : (varchar(max))
  ConnectionManagerType : (varchar(max))
  ConnectionString : (varchar(max))
  ExpressionValue : (varchar(max))
  RetainSameConnectionProperty : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tblconnection.adoc[]" as ssis_t.TblConnection << U >> {
  - Category : (varchar(10))
  ConnectionManagerID : (uniqueidentifier)
  ConnectionManagerName : (varchar(max))
  ConnectionManagerType : (varchar(max))
  ConnectionString : (varchar(max))
  - DelayValidationPropertyValue : (varchar(2))
  ExpressionValue : (varchar(max))
  PackageCreatorName : (varchar(1000))
  PackageName : (varchar(8000))
  - PackagePath : (varchar(8000))
  RetainSameConnectionProperty : (nvarchar(max))
  - RowID : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.usp_getpackagedetails.adoc[]" as ssis_t.usp_GetPackageDetails << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.usp_packageanalysis.adoc[]" as ssis_t.usp_PackageAnalysis << P >> {
  --
}

ssis_t.TblConnection <.. ssis.PackageConnection_src
ssis_t.TblConnection <.. ssis_t.usp_GetPackageDetails
ssis_t.TblConnection <.. ssis_t.usp_PackageAnalysis
"ssis_t.TblConnection::ConnectionManagerID" <-- "ssis.PackageConnection_src::ConnectionManagerID"
"ssis_t.TblConnection::ConnectionManagerName" <-- "ssis.PackageConnection_src::ConnectionManagerName"
"ssis_t.TblConnection::ConnectionManagerType" <-- "ssis.PackageConnection_src::ConnectionManagerType"
"ssis_t.TblConnection::ConnectionString" <-- "ssis.PackageConnection_src::ConnectionString"
"ssis_t.TblConnection::ExpressionValue" <-- "ssis.PackageConnection_src::ExpressionValue"
"ssis_t.TblConnection::RetainSameConnectionProperty" <-- "ssis.PackageConnection_src::RetainSameConnectionProperty"

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_colref[]


== sql_modules_definition

// tag::sql_modules_definition[]
[%collapsible]
=======
[source,sql,numbered,indent=0]
----

----
=======
// end::sql_modules_definition[]


