// tag::HeaderFullDisplayName[]
= ssis_t.usp_GetPackageDetails - P
// end::HeaderFullDisplayName[]

== existing_properties

// tag::existing_properties[]

:ExistsProperty--antorareferencedlist:
:ExistsProperty--is_repo_managed:
:ExistsProperty--is_ssas:
:ExistsProperty--referencedobjectlist:
:ExistsProperty--sql_modules_definition:
:ExistsProperty--AntoraParameterList:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
5364FBE4-113B-EC11-852C-A81E8446D5B0
// end::RepoObject_guid[]

== RepoObject_FullDisplayName2

// tag::RepoObject_FullDisplayName2[]
ssis_t.usp_GetPackageDetails
// end::RepoObject_FullDisplayName2[]

== SysObject_type

// tag::SysObject_type[]
P 
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
stored procedure
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
418152585
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2021-11-22 17:00:20
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]

// end::AntoraColumnDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]

// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

// end::AntoraIndexList[]

== AntoraMeasureDetails

// tag::AntoraMeasureDetails[]

// end::AntoraMeasureDetails[]

== AntoraMeasureDescriptions



== AntoraParameterList

// tag::AntoraParameterList[]
* @ProjectPath (varchar(8000))
// end::AntoraParameterList[]

== AntoraXrefCulturesList

// tag::AntoraXrefCulturesList[]
* xref:dhw:sqldb:ssis_t.usp_getpackagedetails.adoc[] - 
// end::AntoraXrefCulturesList[]

== cultures_count

// tag::cultures_count[]
1
// end::cultures_count[]

== Other tags

source: property.RepoObjectProperty_cross As rop_cross


=== additional_reference_csv

// tag::additional_reference_csv[]

// end::additional_reference_csv[]


=== AdocUspSteps

// tag::adocuspsteps[]

// end::adocuspsteps[]


=== AntoraReferencedList

// tag::antorareferencedlist[]
* xref:dhw:sqldb:ssis_t.connection.adoc[]
* xref:dhw:sqldb:ssis_t.packagedetails.adoc[]
* xref:dhw:sqldb:ssis_t.pkgstats.adoc[]
* xref:dhw:sqldb:ssis_t.tblconnection.adoc[]
* xref:dhw:sqldb:ssis_t.tblconnection_src.adoc[]
* xref:dhw:sqldb:ssis_t.tblcontrolflow.adoc[]
* xref:dhw:sqldb:ssis_t.tblcontrolflow_src.adoc[]
* xref:dhw:sqldb:ssis_t.tblparameter.adoc[]
* xref:dhw:sqldb:ssis_t.tblparameter_src.adoc[]
* xref:dhw:sqldb:ssis_t.tblprecedenceconstraint.adoc[]
* xref:dhw:sqldb:ssis_t.tblprecedenceconstraint_src.adoc[]
* xref:dhw:sqldb:ssis_t.tbltask_dft_component.adoc[]
* xref:dhw:sqldb:ssis_t.tbltask_dft_component_src.adoc[]
* xref:dhw:sqldb:ssis_t.tbltask_dft_derived.adoc[]
* xref:dhw:sqldb:ssis_t.tbltask_dft_details.adoc[]
* xref:dhw:sqldb:ssis_t.tbltask_dft_srcdest.adoc[]
* xref:dhw:sqldb:ssis_t.tbltask_executepackage.adoc[]
* xref:dhw:sqldb:ssis_t.tbltask_lookup.adoc[]
* xref:dhw:sqldb:ssis_t.tbltask_script.adoc[]
* xref:dhw:sqldb:ssis_t.tbltask_script_src.adoc[]
* xref:dhw:sqldb:ssis_t.tbltask_sql.adoc[]
* xref:dhw:sqldb:ssis_t.tbltask_sql_parameter.adoc[]
* xref:dhw:sqldb:ssis_t.tbltask_sql_src.adoc[]
* xref:dhw:sqldb:ssis_t.tblvariable.adoc[]
* xref:dhw:sqldb:ssis_t.tblvariable_src.adoc[]
* xref:dhw:sqldb:ssis_t.tempprecedence1.adoc[]
* xref:dhw:sqldb:ssis_t.tempprecedence2.adoc[]
* xref:dhw:sqldb:ssis_t.tempprecedence3.adoc[]
* xref:dhw:sqldb:ssis_t.tempprecedence4.adoc[]
* xref:dhw:sqldb:ssis_t.tempprecedence5.adoc[]
* xref:dhw:sqldb:ssis_t.tempprecedence5_hierarchy.adoc[]
* xref:dhw:sqldb:ssis_t.tempprecedence6.adoc[]
// end::antorareferencedlist[]


=== AntoraReferencingList

// tag::antorareferencinglist[]

// end::antorareferencinglist[]


=== Description

// tag::description[]

// end::description[]


=== exampleUsage

// tag::exampleusage[]

// end::exampleusage[]


=== exampleUsage_2

// tag::exampleusage_2[]

// end::exampleusage_2[]


=== exampleUsage_3

// tag::exampleusage_3[]

// end::exampleusage_3[]


=== exampleUsage_4

// tag::exampleusage_4[]

// end::exampleusage_4[]


=== exampleUsage_5

// tag::exampleusage_5[]

// end::exampleusage_5[]


=== exampleWrong_Usage

// tag::examplewrong_usage[]

// end::examplewrong_usage[]


=== has_execution_plan_issue

// tag::has_execution_plan_issue[]

// end::has_execution_plan_issue[]


=== has_get_referenced_issue

// tag::has_get_referenced_issue[]

// end::has_get_referenced_issue[]


=== has_history

// tag::has_history[]

// end::has_history[]


=== has_history_columns

// tag::has_history_columns[]

// end::has_history_columns[]


=== InheritanceType

// tag::inheritancetype[]

// end::inheritancetype[]


=== is_persistence

// tag::is_persistence[]

// end::is_persistence[]


=== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]

// end::is_persistence_check_duplicate_per_pk[]


=== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]

// end::is_persistence_check_for_empty_source[]


=== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]

// end::is_persistence_delete_changed[]


=== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]

// end::is_persistence_delete_missing[]


=== is_persistence_insert

// tag::is_persistence_insert[]

// end::is_persistence_insert[]


=== is_persistence_truncate

// tag::is_persistence_truncate[]

// end::is_persistence_truncate[]


=== is_persistence_update_changed

// tag::is_persistence_update_changed[]

// end::is_persistence_update_changed[]


=== is_repo_managed

// tag::is_repo_managed[]
0
// end::is_repo_managed[]


=== is_ssas

// tag::is_ssas[]
0
// end::is_ssas[]


=== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


=== MS_Description

// tag::ms_description[]

// end::ms_description[]


=== persistence_source_RepoObject_fullname

// tag::persistence_source_repoobject_fullname[]

// end::persistence_source_repoobject_fullname[]


=== persistence_source_RepoObject_fullname2

// tag::persistence_source_repoobject_fullname2[]

// end::persistence_source_repoobject_fullname2[]


=== persistence_source_RepoObject_guid

// tag::persistence_source_repoobject_guid[]

// end::persistence_source_repoobject_guid[]


=== persistence_source_RepoObject_xref

// tag::persistence_source_repoobject_xref[]

// end::persistence_source_repoobject_xref[]


=== pk_index_guid

// tag::pk_index_guid[]

// end::pk_index_guid[]


=== pk_IndexPatternColumnDatatype

// tag::pk_indexpatterncolumndatatype[]

// end::pk_indexpatterncolumndatatype[]


=== pk_IndexPatternColumnName

// tag::pk_indexpatterncolumnname[]

// end::pk_indexpatterncolumnname[]


=== pk_IndexSemanticGroup

// tag::pk_indexsemanticgroup[]

// end::pk_indexsemanticgroup[]


=== ReferencedObjectList

// tag::referencedobjectlist[]
* [ssis_t].[Connection]
* [ssis_t].[PackageDetails]
* [ssis_t].[pkgStats]
* [ssis_t].[TblConnection]
* [ssis_t].[TblConnection_src]
* [ssis_t].[TblControlFlow]
* [ssis_t].[TblControlFlow_src]
* [ssis_t].[TblParameter]
* [ssis_t].[TblParameter_src]
* [ssis_t].[TblPrecedenceConstraint]
* [ssis_t].[TblPrecedenceConstraint_src]
* [ssis_t].[TblTask_Dft_Component]
* [ssis_t].[TblTask_Dft_Component_src]
* [ssis_t].[TblTask_Dft_Derived]
* [ssis_t].[TblTask_Dft_Details]
* [ssis_t].[TblTask_Dft_SrcDest]
* [ssis_t].[TblTask_ExecutePackage]
* [ssis_t].[TblTask_Lookup]
* [ssis_t].[TblTask_Script]
* [ssis_t].[TblTask_Script_src]
* [ssis_t].[TblTask_Sql]
* [ssis_t].[TblTask_Sql_Parameter]
* [ssis_t].[TblTask_Sql_src]
* [ssis_t].[TblVariable]
* [ssis_t].[TblVariable_src]
* [ssis_t].[tempprecedence1]
* [ssis_t].[tempprecedence2]
* [ssis_t].[tempprecedence3]
* [ssis_t].[tempprecedence4]
* [ssis_t].[tempprecedence5]
* [ssis_t].[tempprecedence5_Hierarchy]
* [ssis_t].[tempprecedence6]
// end::referencedobjectlist[]


=== usp_persistence_RepoObject_guid

// tag::usp_persistence_repoobject_guid[]

// end::usp_persistence_repoobject_guid[]


=== UspExamples

// tag::uspexamples[]

// end::uspexamples[]


=== uspgenerator_usp_id

// tag::uspgenerator_usp_id[]

// end::uspgenerator_usp_id[]


=== UspParameters

// tag::uspparameters[]

// end::uspparameters[]

== Boolean Attributes

source: property.RepoObjectProperty WHERE property_int = 1

// tag::boolean_attributes[]


// end::boolean_attributes[]

== PlantUML diagrams

=== PlantUML Entity

// tag::puml_entity[]
[plantuml, entity-{docname}, svg, subs=macros]
....
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis_t.usp_getpackagedetails.adoc[]" as ssis_t.usp_GetPackageDetails << P >> {
  --
}
....

// end::puml_entity[]

=== PlantUML Entity 1 1 FK

// tag::puml_entity_1_1_fk[]
[plantuml, entity_1_1_fk-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}





footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_fk[]

=== PlantUML 1 1 ObjectRef

// tag::puml_entity_1_1_objectref[]
[plantuml, entity_1_1_objectref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis_t.connection.adoc[]" as ssis_t.Connection << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.packagedetails.adoc[]" as ssis_t.PackageDetails << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.pkgstats.adoc[]" as ssis_t.pkgStats << U >> {
  - **RowID** : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tblconnection.adoc[]" as ssis_t.TblConnection << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tblconnection_src.adoc[]" as ssis_t.TblConnection_src << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tblcontrolflow.adoc[]" as ssis_t.TblControlFlow << U >> {
  - **ControlFlowDetailsRowID** : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tblcontrolflow_src.adoc[]" as ssis_t.TblControlFlow_src << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tblparameter.adoc[]" as ssis_t.TblParameter << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tblparameter_src.adoc[]" as ssis_t.TblParameter_src << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tblprecedenceconstraint.adoc[]" as ssis_t.TblPrecedenceConstraint << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tblprecedenceconstraint_src.adoc[]" as ssis_t.TblPrecedenceConstraint_src << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_dft_component.adoc[]" as ssis_t.TblTask_Dft_Component << U >> {
  - **DftComponentId** : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_dft_component_src.adoc[]" as ssis_t.TblTask_Dft_Component_src << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_dft_derived.adoc[]" as ssis_t.TblTask_Dft_Derived << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_dft_details.adoc[]" as ssis_t.TblTask_Dft_Details << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_dft_srcdest.adoc[]" as ssis_t.TblTask_Dft_SrcDest << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_executepackage.adoc[]" as ssis_t.TblTask_ExecutePackage << U >> {
  - **ControlFlowDetailsRowID** : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_lookup.adoc[]" as ssis_t.TblTask_Lookup << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_script.adoc[]" as ssis_t.TblTask_Script << U >> {
  - **ControlFlowDetailsRowID** : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_script_src.adoc[]" as ssis_t.TblTask_Script_src << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_sql.adoc[]" as ssis_t.TblTask_Sql << U >> {
  - **ControlFlowDetailsRowID** : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_sql_parameter.adoc[]" as ssis_t.TblTask_Sql_Parameter << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_sql_src.adoc[]" as ssis_t.TblTask_Sql_src << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tblvariable.adoc[]" as ssis_t.TblVariable << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tblvariable_src.adoc[]" as ssis_t.TblVariable_src << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tempprecedence1.adoc[]" as ssis_t.tempprecedence1 << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tempprecedence2.adoc[]" as ssis_t.tempprecedence2 << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tempprecedence3.adoc[]" as ssis_t.tempprecedence3 << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tempprecedence4.adoc[]" as ssis_t.tempprecedence4 << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tempprecedence5.adoc[]" as ssis_t.tempprecedence5 << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tempprecedence5_hierarchy.adoc[]" as ssis_t.tempprecedence5_Hierarchy << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tempprecedence6.adoc[]" as ssis_t.tempprecedence6 << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.usp_getpackagedetails.adoc[]" as ssis_t.usp_GetPackageDetails << P >> {
  --
}

ssis_t.Connection <.. ssis_t.usp_GetPackageDetails
ssis_t.PackageDetails <.. ssis_t.usp_GetPackageDetails
ssis_t.pkgStats <.. ssis_t.usp_GetPackageDetails
ssis_t.TblConnection <.. ssis_t.usp_GetPackageDetails
ssis_t.TblConnection_src <.. ssis_t.usp_GetPackageDetails
ssis_t.TblControlFlow <.. ssis_t.usp_GetPackageDetails
ssis_t.TblControlFlow_src <.. ssis_t.usp_GetPackageDetails
ssis_t.TblParameter <.. ssis_t.usp_GetPackageDetails
ssis_t.TblParameter_src <.. ssis_t.usp_GetPackageDetails
ssis_t.TblPrecedenceConstraint <.. ssis_t.usp_GetPackageDetails
ssis_t.TblPrecedenceConstraint_src <.. ssis_t.usp_GetPackageDetails
ssis_t.TblTask_Dft_Component <.. ssis_t.usp_GetPackageDetails
ssis_t.TblTask_Dft_Component_src <.. ssis_t.usp_GetPackageDetails
ssis_t.TblTask_Dft_Derived <.. ssis_t.usp_GetPackageDetails
ssis_t.TblTask_Dft_Details <.. ssis_t.usp_GetPackageDetails
ssis_t.TblTask_Dft_SrcDest <.. ssis_t.usp_GetPackageDetails
ssis_t.TblTask_ExecutePackage <.. ssis_t.usp_GetPackageDetails
ssis_t.TblTask_Lookup <.. ssis_t.usp_GetPackageDetails
ssis_t.TblTask_Script <.. ssis_t.usp_GetPackageDetails
ssis_t.TblTask_Script_src <.. ssis_t.usp_GetPackageDetails
ssis_t.TblTask_Sql <.. ssis_t.usp_GetPackageDetails
ssis_t.TblTask_Sql_Parameter <.. ssis_t.usp_GetPackageDetails
ssis_t.TblTask_Sql_src <.. ssis_t.usp_GetPackageDetails
ssis_t.TblVariable <.. ssis_t.usp_GetPackageDetails
ssis_t.TblVariable_src <.. ssis_t.usp_GetPackageDetails
ssis_t.tempprecedence1 <.. ssis_t.usp_GetPackageDetails
ssis_t.tempprecedence2 <.. ssis_t.usp_GetPackageDetails
ssis_t.tempprecedence3 <.. ssis_t.usp_GetPackageDetails
ssis_t.tempprecedence4 <.. ssis_t.usp_GetPackageDetails
ssis_t.tempprecedence5 <.. ssis_t.usp_GetPackageDetails
ssis_t.tempprecedence5_Hierarchy <.. ssis_t.usp_GetPackageDetails
ssis_t.tempprecedence6 <.. ssis_t.usp_GetPackageDetails

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_objectref[]

=== PlantUML 30 0 ObjectRef

// tag::puml_entity_30_0_objectref[]
[plantuml, entity_30_0_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis_t.connection.adoc[]" as ssis_t.Connection << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.packagedetails.adoc[]" as ssis_t.PackageDetails << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.pkgstats.adoc[]" as ssis_t.pkgStats << U >> {
  - **RowID** : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tblconnection.adoc[]" as ssis_t.TblConnection << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tblconnection_src.adoc[]" as ssis_t.TblConnection_src << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tblcontrolflow.adoc[]" as ssis_t.TblControlFlow << U >> {
  - **ControlFlowDetailsRowID** : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tblcontrolflow_src.adoc[]" as ssis_t.TblControlFlow_src << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tblparameter.adoc[]" as ssis_t.TblParameter << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tblparameter_src.adoc[]" as ssis_t.TblParameter_src << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tblprecedenceconstraint.adoc[]" as ssis_t.TblPrecedenceConstraint << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tblprecedenceconstraint_src.adoc[]" as ssis_t.TblPrecedenceConstraint_src << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_dft_component.adoc[]" as ssis_t.TblTask_Dft_Component << U >> {
  - **DftComponentId** : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_dft_component_src.adoc[]" as ssis_t.TblTask_Dft_Component_src << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_dft_derived.adoc[]" as ssis_t.TblTask_Dft_Derived << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_dft_details.adoc[]" as ssis_t.TblTask_Dft_Details << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_dft_srcdest.adoc[]" as ssis_t.TblTask_Dft_SrcDest << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_executepackage.adoc[]" as ssis_t.TblTask_ExecutePackage << U >> {
  - **ControlFlowDetailsRowID** : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_lookup.adoc[]" as ssis_t.TblTask_Lookup << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_script.adoc[]" as ssis_t.TblTask_Script << U >> {
  - **ControlFlowDetailsRowID** : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_script_src.adoc[]" as ssis_t.TblTask_Script_src << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_sql.adoc[]" as ssis_t.TblTask_Sql << U >> {
  - **ControlFlowDetailsRowID** : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_sql_parameter.adoc[]" as ssis_t.TblTask_Sql_Parameter << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_sql_src.adoc[]" as ssis_t.TblTask_Sql_src << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tblvariable.adoc[]" as ssis_t.TblVariable << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tblvariable_src.adoc[]" as ssis_t.TblVariable_src << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tempprecedence1.adoc[]" as ssis_t.tempprecedence1 << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tempprecedence2.adoc[]" as ssis_t.tempprecedence2 << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tempprecedence3.adoc[]" as ssis_t.tempprecedence3 << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tempprecedence4.adoc[]" as ssis_t.tempprecedence4 << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tempprecedence5.adoc[]" as ssis_t.tempprecedence5 << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tempprecedence5_hierarchy.adoc[]" as ssis_t.tempprecedence5_Hierarchy << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tempprecedence6.adoc[]" as ssis_t.tempprecedence6 << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.usp_getpackagedetails.adoc[]" as ssis_t.usp_GetPackageDetails << P >> {
  --
}

ssis_t.Connection <.. ssis_t.usp_GetPackageDetails
ssis_t.PackageDetails <.. ssis_t.usp_GetPackageDetails
ssis_t.pkgStats <.. ssis_t.PackageDetails
ssis_t.pkgStats <.. ssis_t.TblConnection_src
ssis_t.pkgStats <.. ssis_t.TblControlFlow_src
ssis_t.pkgStats <.. ssis_t.TblParameter_src
ssis_t.pkgStats <.. ssis_t.TblPrecedenceConstraint_src
ssis_t.pkgStats <.. ssis_t.TblVariable_src
ssis_t.pkgStats <.. ssis_t.usp_GetPackageDetails
ssis_t.TblConnection <.. ssis_t.usp_GetPackageDetails
ssis_t.TblConnection_src <.. ssis_t.usp_GetPackageDetails
ssis_t.TblControlFlow <.. ssis_t.TblTask_Dft_Component_src
ssis_t.TblControlFlow <.. ssis_t.TblTask_Script_src
ssis_t.TblControlFlow <.. ssis_t.TblTask_Sql_src
ssis_t.TblControlFlow <.. ssis_t.usp_GetPackageDetails
ssis_t.TblControlFlow_src <.. ssis_t.usp_GetPackageDetails
ssis_t.TblParameter <.. ssis_t.usp_GetPackageDetails
ssis_t.TblParameter_src <.. ssis_t.usp_GetPackageDetails
ssis_t.TblPrecedenceConstraint <.. ssis_t.usp_GetPackageDetails
ssis_t.TblPrecedenceConstraint_src <.. ssis_t.usp_GetPackageDetails
ssis_t.TblTask_Dft_Component <.. ssis_t.usp_GetPackageDetails
ssis_t.TblTask_Dft_Component_src <.. ssis_t.usp_GetPackageDetails
ssis_t.TblTask_Dft_Derived <.. ssis_t.usp_GetPackageDetails
ssis_t.TblTask_Dft_Details <.. ssis_t.usp_GetPackageDetails
ssis_t.TblTask_Dft_SrcDest <.. ssis_t.usp_GetPackageDetails
ssis_t.TblTask_ExecutePackage <.. ssis_t.usp_GetPackageDetails
ssis_t.TblTask_Lookup <.. ssis_t.usp_GetPackageDetails
ssis_t.TblTask_Script <.. ssis_t.usp_GetPackageDetails
ssis_t.TblTask_Script_src <.. ssis_t.usp_GetPackageDetails
ssis_t.TblTask_Sql <.. ssis_t.usp_GetPackageDetails
ssis_t.TblTask_Sql_Parameter <.. ssis_t.usp_GetPackageDetails
ssis_t.TblTask_Sql_src <.. ssis_t.usp_GetPackageDetails
ssis_t.TblVariable <.. ssis_t.usp_GetPackageDetails
ssis_t.TblVariable_src <.. ssis_t.usp_GetPackageDetails
ssis_t.tempprecedence1 <.. ssis_t.usp_GetPackageDetails
ssis_t.tempprecedence2 <.. ssis_t.usp_GetPackageDetails
ssis_t.tempprecedence3 <.. ssis_t.usp_GetPackageDetails
ssis_t.tempprecedence4 <.. ssis_t.usp_GetPackageDetails
ssis_t.tempprecedence5 <.. ssis_t.usp_GetPackageDetails
ssis_t.tempprecedence5_Hierarchy <.. ssis_t.usp_GetPackageDetails
ssis_t.tempprecedence6 <.. ssis_t.usp_GetPackageDetails

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_30_0_objectref[]

=== PlantUML 0 30 ObjectRef

// tag::puml_entity_0_30_objectref[]
[plantuml, entity_0_30_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis_t.usp_getpackagedetails.adoc[]" as ssis_t.usp_GetPackageDetails << P >> {
  --
}



footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_0_30_objectref[]

=== PlantUML 1 1 ColumnRef

// tag::puml_entity_1_1_colref[]
[plantuml, entity_1_1_colref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis_t.connection.adoc[]" as ssis_t.Connection << U >> {
  ConnectionManager : (varchar(5000))
  ConnectionManagerID : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.packagedetails.adoc[]" as ssis_t.PackageDetails << V >> {
  PackageCreationDate : (datetime)
  PackageCreatorComputerName : (nvarchar(500))
  PackageCreatorName : (nvarchar(500))
  PackageDescription : (nvarchar(max))
  PackageDTSID : (uniqueidentifier)
  PackageLastModifiedProductVersion : (nvarchar(500))
  PackageLocaleID : (int)
  PackageObjectName : (nvarchar(500))
  - PackagePath : (varchar(8000))
  PackageProtectionLevel : (nvarchar(500))
  PackageVersionGUID : (uniqueidentifier)
  - RowID : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.pkgstats.adoc[]" as ssis_t.pkgStats << U >> {
  - **RowID** : (int)
  PackageCreationDate : (datetime)
  PackageCreatorComputerName : (nvarchar(500))
  PackageCreatorName : (varchar(1000))
  PackageDescription : (nvarchar(max))
  PackageDTSID : (uniqueidentifier)
  PackageLastModifiedProductVersion : (nvarchar(500))
  PackageLocaleID : (int)
  PackageObjectName : (nvarchar(500))
  - PackagePath : (varchar(8000))
  PackageProtectionLevel : (varchar(100))
  PackageVersionGUID : (uniqueidentifier)
  - PackageXML : (xml)
  - ProjectPath : (varchar(8000))
  # PackageName : (varchar(200))
  ~ PackageProtectionLevelName : (varchar(28))
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tblconnection.adoc[]" as ssis_t.TblConnection << U >> {
  - Category : (varchar(10))
  ConnectionManagerID : (uniqueidentifier)
  ConnectionManagerName : (varchar(max))
  ConnectionManagerType : (varchar(max))
  ConnectionString : (varchar(max))
  - DelayValidationPropertyValue : (varchar(2))
  ExpressionValue : (varchar(max))
  PackageCreatorName : (varchar(1000))
  PackageName : (varchar(8000))
  - PackagePath : (varchar(8000))
  RetainSameConnectionProperty : (nvarchar(max))
  - RowID : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tblconnection_src.adoc[]" as ssis_t.TblConnection_src << V >> {
  - Category : (varchar(10))
  ConnectionManagerID : (uniqueidentifier)
  ConnectionManagerName : (varchar(max))
  ConnectionManagerType : (varchar(max))
  ConnectionString : (varchar(max))
  - DelayValidationPropertyValue : (varchar(2))
  ExpressionValue : (varchar(max))
  PackageCreatorName : (varchar(1000))
  PackageName : (varchar(8000))
  - PackagePath : (varchar(8000))
  RetainSameConnectionProperty : (nvarchar(max))
  - RowID : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tblcontrolflow.adoc[]" as ssis_t.TblControlFlow << U >> {
  - **ControlFlowDetailsRowID** : (int)
  DelayValidationPropertyValue : (varchar(100))
  DFTQuery : (xml)
  ExecPkgTaskQry : (xml)
  ExpressionValue : (varchar(5000))
  IsDisabled : (varchar(10))
  RowID : (int)
  ScriptTaskQry : (xml)
  SqlTaskQry : (xml)
  TaskDescription : (varchar(max))
  TaskName : (varchar(2000))
  TaskPath : (varchar(8000))
  TaskType : (varchar(5000))
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tblcontrolflow_src.adoc[]" as ssis_t.TblControlFlow_src << V >> {
  DelayValidationPropertyValue : (nvarchar(max))
  DFTQuery : (xml)
  ExecPkgTaskQry : (xml)
  ExpressionValue : (nvarchar(max))
  - IsDisabled : (nvarchar(max))
  - RowID : (int)
  ScriptTaskQry : (xml)
  SqlTaskQry : (xml)
  TaskDescription : (nvarchar(max))
  TaskName : (nvarchar(max))
  TaskPath : (varchar(max))
  TaskType : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tblparameter.adoc[]" as ssis_t.TblParameter << U >> {
  Category : (varchar(1000))
  ExpressionValue : (varchar(5000))
  PackageCreatorName : (varchar(1000))
  PackageName : (varchar(max))
  PackagePath : (varchar(5000))
  ParameterDataType : (varchar(max))
  ParameterHexValue : (varchar(1000))
  ParameterName : (varchar(500))
  - ParameterRowID : (int)
  ParameterValue : (varchar(max))
  RowID : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tblparameter_src.adoc[]" as ssis_t.TblParameter_src << V >> {
  - Category : (varchar(8))
  - ExpressionValue : (varchar(max))
  PackageCreatorName : (varchar(1000))
  PackageName : (varchar(8000))
  - PackagePath : (varchar(8000))
  ParameterDataType : (varchar(max))
  ParameterHexValue : (varchar(max))
  ParameterName : (varchar(max))
  - ParameterValue : (varchar(max))
  - RowID : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tblprecedenceconstraint.adoc[]" as ssis_t.TblPrecedenceConstraint << U >> {
  CreationName : (nvarchar(max))
  DTSID : (uniqueidentifier)
  EvalOp : (int)
  Expression : (nvarchar(max))
  FlowType : (varchar(1000))
  LogicalAnd : (bit)
  ObjectName : (nvarchar(max))
  PackagePath : (varchar(2000))
  RowID : (int)
  TaskFrom : (varchar(2000))
  Taskto : (varchar(2000))
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tblprecedenceconstraint_src.adoc[]" as ssis_t.TblPrecedenceConstraint_src << V >> {
  CreationName : (nvarchar(max))
  DTSID : (uniqueidentifier)
  EvalOp : (int)
  Expression : (nvarchar(max))
  - FlowType : (varchar(12))
  LogicalAnd : (bit)
  ObjectName : (nvarchar(max))
  - PackagePath : (varchar(8000))
  - RowID : (int)
  TaskFrom : (nvarchar(max))
  TaskTo : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_dft_component.adoc[]" as ssis_t.TblTask_Dft_Component << U >> {
  - **DftComponentId** : (int)
  AccessMode : (varchar(max))
  AlwaysUseDefaultCodePage : (varchar(max))
  CommandTimeout : (int)
  componentClassID : (varchar(max))
  Connection_description : (varchar(max))
  Connection_name : (varchar(max))
  Connection_refId : (varchar(max))
  connectionManagerID : (varchar(max))
  connectionManagerRefId : (varchar(max))
  ContactInfo : (varchar(max))
  - ControlFlowDetailsRowID : (int)
  DefaultCodePage : (int)
  description : (varchar(max))
  FastLoadKeepIdentity : (bit)
  FastLoadKeepNulls : (bit)
  FastLoadMaxInsertCommitSize : (int)
  FastLoadOptions : (varchar(max))
  inputsQry : (xml)
  IsSortedProperty : (varchar(10))
  name : (varchar(max))
  OpenRowset : (varchar(max))
  OpenRowsetVariable : (varchar(max))
  outputsQry : (xml)
  ParameterMapping : (varchar(max))
  refId : (varchar(max))
  RowID : (int)
  SqlCommand : (varchar(max))
  SqlCommandVariable : (varchar(max))
  VariableName : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_dft_component_src.adoc[]" as ssis_t.TblTask_Dft_Component_src << V >> {
  AccessMode : (varchar(max))
  AlwaysUseDefaultCodePage : (varchar(max))
  CommandTimeout : (int)
  componentClassID : (varchar(max))
  Connection_description : (varchar(max))
  Connection_name : (varchar(max))
  Connection_refId : (varchar(max))
  connectionManagerID : (varchar(max))
  connectionManagerRefId : (varchar(max))
  ContactInfo : (varchar(max))
  - ControlFlowDetailsRowID : (int)
  DefaultCodePage : (int)
  description : (varchar(max))
  FastLoadKeepIdentity : (bit)
  FastLoadKeepNulls : (bit)
  FastLoadMaxInsertCommitSize : (int)
  FastLoadOptions : (varchar(max))
  inputsQry : (xml)
  IsSortedProperty : (varchar(10))
  name : (varchar(max))
  OpenRowset : (varchar(max))
  OpenRowsetVariable : (varchar(max))
  outputsQry : (xml)
  ParameterMapping : (varchar(max))
  refId : (varchar(max))
  RowID : (int)
  SqlCommand : (varchar(max))
  SqlCommandVariable : (varchar(max))
  VariableName : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_dft_derived.adoc[]" as ssis_t.TblTask_Dft_Derived << U >> {
  DataFlowDetailsRowID : (int)
  DerivedValue : (varchar(8000))
  DestinationColumn : (varchar(8000))
  RowID : (int)
  SourceColumn : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_dft_details.adoc[]" as ssis_t.TblTask_Dft_Details << U >> {
  ControlFlowDetailsRowID : (int)
  - DataFlowDetailsRowID : (int)
  DFTConnectionManager : (varchar(max))
  DFTRowSet : (varchar(max))
  DFTSQLCommand : (varchar(max))
  DFTTaskName : (varchar(max))
  DFTTasksPath : (varchar(max))
  DFTTaskType : (varchar(max))
  DFTTaskType1 : (varchar(max))
  InputQry : (xml)
  IsSortedProperty : (varchar(10))
  MultihashcolumnSortPosition : (varchar(max))
  OutputQry : (xml)
  ParameterBindingParameterName : (varchar(2000))
  RowID : (int)
  Variable : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_dft_srcdest.adoc[]" as ssis_t.TblTask_Dft_SrcDest << U >> {
  DataFlowDetailsRowID : (int)
  DataSource : (varchar(50))
  DestinationColumn : (varchar(8000))
  RowID : (int)
  SortKeyPosition : (varchar(10))
  SourceColumn : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_executepackage.adoc[]" as ssis_t.TblTask_ExecutePackage << U >> {
  - **ControlFlowDetailsRowID** : (int)
  ExecutedPackageName : (varchar(1000))
  ExecutePackageConnection : (varchar(1000))
  ExecutePackageExpression : (varchar(1000))
  RowID : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_lookup.adoc[]" as ssis_t.TblTask_Lookup << U >> {
  DataFlowDetailsRowID : (int)
  DestinationColumn : (varchar(8000))
  LookupJoins : (varchar(8000))
  RowID : (int)
  SourceColumn : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_script.adoc[]" as ssis_t.TblTask_Script << U >> {
  - **ControlFlowDetailsRowID** : (int)
  RowID : (int)
  Script : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_script_src.adoc[]" as ssis_t.TblTask_Script_src << V >> {
  - ControlFlowDetailsRowID : (int)
  RowID : (int)
  Script : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_sql.adoc[]" as ssis_t.TblTask_Sql << U >> {
  - **ControlFlowDetailsRowID** : (int)
  - RowID : (int)
  SqlConnection : (uniqueidentifier)
  SqlStatementSource : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_sql_parameter.adoc[]" as ssis_t.TblTask_Sql_Parameter << U >> {
  ControlFlowDetailsRowID : (int)
  ParameterBindingParameterName : (varchar(1000))
  ParameterBindingSequence : (varchar(1000))
  ResultSetParameterName : (varchar(1000))
  RowID : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_sql_src.adoc[]" as ssis_t.TblTask_Sql_src << V >> {
  - ControlFlowDetailsRowID : (int)
  RowID : (int)
  SqlConnection : (uniqueidentifier)
  SqlStatementSource : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tblvariable.adoc[]" as ssis_t.TblVariable << U >> {
  Category : (varchar(1000))
  ExpressionValue : (varchar(5000))
  PackageCreatorName : (varchar(1000))
  PackageName : (varchar(max))
  PackagePath : (varchar(5000))
  RowID : (int)
  VariableDataType : (varchar(max))
  VariableHexValue : (varchar(1000))
  VariableName : (varchar(500))
  - VariableRowID : (int)
  VariableValue : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tblvariable_src.adoc[]" as ssis_t.TblVariable_src << V >> {
  - Category : (varchar(8))
  - ExpressionValue : (varchar(max))
  PackageCreatorName : (varchar(1000))
  PackageName : (varchar(8000))
  - PackagePath : (varchar(8000))
  - RowID : (int)
  VariableDataType : (varchar(max))
  VariableHexValue : (varchar(max))
  VariableName : (varchar(max))
  - VariableValue : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tempprecedence1.adoc[]" as ssis_t.tempprecedence1 << U >> {
  - isparentlevel : (int)
  level : (bigint)
  RowID : (int)
  TaskFrom : (varchar(2000))
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tempprecedence2.adoc[]" as ssis_t.tempprecedence2 << U >> {
  LEVEL : (int)
  parentlevel : (int)
  ROWID : (int)
  task : (varchar(2000))
  TaskFrom : (varchar(2000))
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tempprecedence3.adoc[]" as ssis_t.tempprecedence3 << U >> {
  LEVEL : (int)
  parentlevel : (int)
  ROWID : (int)
  task : (varchar(2000))
  trank : (bigint)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tempprecedence4.adoc[]" as ssis_t.tempprecedence4 << U >> {
  level : (int)
  ROWID : (int)
  task : (varchar(2000))
  tlevel : (int)
  trank : (bigint)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tempprecedence5.adoc[]" as ssis_t.tempprecedence5 << U >> {
  ROWID : (int)
  sequenceno : (nvarchar(max))
  task : (varchar(2000))
  trank : (bigint)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tempprecedence5_hierarchy.adoc[]" as ssis_t.tempprecedence5_Hierarchy << U >> {
  rid : (hierarchyid)
  ROWID : (int)
  sequenceno : (nvarchar(max))
  task : (varchar(2000))
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tempprecedence6.adoc[]" as ssis_t.tempprecedence6 << U >> {
  ROWID : (int)
  sequenceno : (bigint)
  task : (varchar(2000))
  --
}

entity "puml-link:dhw:sqldb:ssis_t.usp_getpackagedetails.adoc[]" as ssis_t.usp_GetPackageDetails << P >> {
  --
}

ssis_t.Connection <.. ssis_t.usp_GetPackageDetails
ssis_t.PackageDetails <.. ssis_t.usp_GetPackageDetails
ssis_t.pkgStats <.. ssis_t.usp_GetPackageDetails
ssis_t.TblConnection <.. ssis_t.usp_GetPackageDetails
ssis_t.TblConnection_src <.. ssis_t.usp_GetPackageDetails
ssis_t.TblControlFlow <.. ssis_t.usp_GetPackageDetails
ssis_t.TblControlFlow_src <.. ssis_t.usp_GetPackageDetails
ssis_t.TblParameter <.. ssis_t.usp_GetPackageDetails
ssis_t.TblParameter_src <.. ssis_t.usp_GetPackageDetails
ssis_t.TblPrecedenceConstraint <.. ssis_t.usp_GetPackageDetails
ssis_t.TblPrecedenceConstraint_src <.. ssis_t.usp_GetPackageDetails
ssis_t.TblTask_Dft_Component <.. ssis_t.usp_GetPackageDetails
ssis_t.TblTask_Dft_Component_src <.. ssis_t.usp_GetPackageDetails
ssis_t.TblTask_Dft_Derived <.. ssis_t.usp_GetPackageDetails
ssis_t.TblTask_Dft_Details <.. ssis_t.usp_GetPackageDetails
ssis_t.TblTask_Dft_SrcDest <.. ssis_t.usp_GetPackageDetails
ssis_t.TblTask_ExecutePackage <.. ssis_t.usp_GetPackageDetails
ssis_t.TblTask_Lookup <.. ssis_t.usp_GetPackageDetails
ssis_t.TblTask_Script <.. ssis_t.usp_GetPackageDetails
ssis_t.TblTask_Script_src <.. ssis_t.usp_GetPackageDetails
ssis_t.TblTask_Sql <.. ssis_t.usp_GetPackageDetails
ssis_t.TblTask_Sql_Parameter <.. ssis_t.usp_GetPackageDetails
ssis_t.TblTask_Sql_src <.. ssis_t.usp_GetPackageDetails
ssis_t.TblVariable <.. ssis_t.usp_GetPackageDetails
ssis_t.TblVariable_src <.. ssis_t.usp_GetPackageDetails
ssis_t.tempprecedence1 <.. ssis_t.usp_GetPackageDetails
ssis_t.tempprecedence2 <.. ssis_t.usp_GetPackageDetails
ssis_t.tempprecedence3 <.. ssis_t.usp_GetPackageDetails
ssis_t.tempprecedence4 <.. ssis_t.usp_GetPackageDetails
ssis_t.tempprecedence5 <.. ssis_t.usp_GetPackageDetails
ssis_t.tempprecedence5_Hierarchy <.. ssis_t.usp_GetPackageDetails
ssis_t.tempprecedence6 <.. ssis_t.usp_GetPackageDetails


footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_colref[]


== sql_modules_definition

// tag::sql_modules_definition[]
[%collapsible]
=======
[source,sql,numbered,indent=0]
----
/*
logic and implementation is based on this blog article https://www.sqlservercentral.com/articles/ssis-package-documentor[SSIS Package documentor] +
from 2016-11-04 (first published: 2015-09-01) +
author: https://www.sqlservercentral.com/author/Divya-Agrawal

the article explains how does it work and provides a link for a procedure script: 
https://www.sqlservercentral.com/wp-content/uploads/2019/05/CodeReviewAcceleratior_v10.sql


* empty columns in ssis.TblControlFlowDetails
** [ ] TaskTypeDescription
** [ ] DelayValidationPropertyValue
** [x] DFTQuery
+
[NOTE]
--
the issue is related to the original detection, using only 
....
./DTS:Executable[@DTS:ExecutableType=''SSIS.Pipeline.3'']
....
but documentation https://docs.microsoft.com/en-us/openspecs/sql_data_portability/ms-dtsx2/bdf1b5fe-d2e2-4fb9-892c-02c50b865e40[2.6.1 ExecutableType Instance for Pipeline Task]

lists 4 ExecutionType:

* SSIS.Pipeline
* SSIS.Pipeline.3 (for DTSX2 2012/01)
* STOCK:SSIS.Pipeline
* Microsoft.Pipeline (for DTSX2 2014/01)
--
+
** [ ] SqlTaskQry
** [x] ExecPkgTaskQry
** [ ] ScriptTaskQry
** [ ] ExpressionValue

not all tasks are implemented

* https://docs.microsoft.com/en-us/openspecs/sql_data_portability/ms-dtsx2/f8badd15-7e54-4cc5-a8e2-a15c15dce8fe[2.6.3 Executable Task Types]
** [ ] https://docs.microsoft.com/en-us/openspecs/sql_data_portability/ms-dtsx2/43d08ee2-cffe-41e9-a140-181f65814ed0[2.6.3.1 ExecutableType Instance for CDC Control Task]
** [ ] https://docs.microsoft.com/en-us/openspecs/sql_data_portability/ms-dtsx2/14ea1253-ecfd-408d-9a2e-490cc2fed784[2.6.3.2 ExecutableType Instance for ActiveX Script Task] 
** [ ] https://docs.microsoft.com/en-us/openspecs/sql_data_portability/ms-dtsx2/1294dbe4-41e9-4c0f-b1d9-a4c34da7dde0[2.6.3.3 ExecutableType Instance for AS Execute DDL Task] 
** [ ] https://docs.microsoft.com/en-us/openspecs/sql_data_portability/ms-dtsx2/8c3e3f5e-2795-41ba-9258-ffe9a48eb6a8[2.6.3.4 ExecutableType Instance for AS Processing Task]
** [ ] https://docs.microsoft.com/en-us/openspecs/sql_data_portability/ms-dtsx2/9dbf8b6c-714c-4c4d-830f-bcb8fbb7f8b5[2.6.3.5 ExecutableType Instance for Bulk Insert Task]
** [ ] https://docs.microsoft.com/en-us/openspecs/sql_data_portability/ms-dtsx2/da10af7f-8ac1-47e0-be52-ec05bddc1ae1[2.6.3.6 ExecutableType Instance for Data Mining Query Task]
** [ ] https://docs.microsoft.com/en-us/openspecs/sql_data_portability/ms-dtsx2/8f607e36-98fa-40f7-a0ca-92dcd015287e[2.6.3.7 ExecutableType Instance for Data Profiling Task]
** [ ] https://docs.microsoft.com/en-us/openspecs/sql_data_portability/ms-dtsx2/9696d1ec-baa7-48d7-a52d-3c87beac5e83[2.6.3.8 ExecutableType Instance for Execute DTS 2000 Package Task]
** [ ] https://docs.microsoft.com/en-us/openspecs/sql_data_portability/ms-dtsx2/f71e8e17-aa69-4ce8-8fc6-d2e0fef99059[2.6.3.9 ExecutableType Instance for Execute Package Task]
** [x] https://docs.microsoft.com/en-us/openspecs/sql_data_portability/ms-dtsx2/221cbe95-b7b4-4adb-b5e9-8e632f9f2168[2.6.3.10 ExecutableType Instance for Execute Process Task]
** [ ] https://docs.microsoft.com/en-us/openspecs/sql_data_portability/ms-dtsx2/80af8760-5b6d-4dfd-8a63-cf14bb090fbd[2.6.3.11 ExecutableType Instance for Execute SQL Task]
*** todo test with examples
** [ ] https://docs.microsoft.com/en-us/openspecs/sql_data_portability/ms-dtsx2/09edb4c6-ffeb-41f6-9d56-eeafecc14e77[2.6.3.12 ExecutableType Instance for Expression Task]
** [ ] https://docs.microsoft.com/en-us/openspecs/sql_data_portability/ms-dtsx2/05cc0ef5-663b-4980-8710-7fa3712392af[2.6.3.13 ExecutableType Instance for File System Task]
** [ ] https://docs.microsoft.com/en-us/openspecs/sql_data_portability/ms-dtsx2/216f743a-f4ef-46bc-995e-9b02b74a35ac[2.6.3.14 ExecutableType Instance for FTP Task]
** [ ] https://docs.microsoft.com/en-us/openspecs/sql_data_portability/ms-dtsx2/3f7c7677-917e-43a3-b9db-f6963513791e[2.6.3.15 ExecutableType Instance for Message Queue Task]
** [x] https://docs.microsoft.com/en-us/openspecs/sql_data_portability/ms-dtsx2/93ef6e19-9c22-4dd1-b6b1-ae7d9c43a490[2.6.3.16 ExecutableType Instance for Script Task]
** [ ] https://docs.microsoft.com/en-us/openspecs/sql_data_portability/ms-dtsx2/98a05bb3-e159-44d0-b6b4-edbe921bb542[2.6.3.17 ExecutableType Instance for Send Mail Task]
** [ ] https://docs.microsoft.com/en-us/openspecs/sql_data_portability/ms-dtsx2/76e8dc38-1511-499f-a52e-c80c412049ed[2.6.3.18 ExecutableType Instance for Transfer Database Task]
** [ ] https://docs.microsoft.com/en-us/openspecs/sql_data_portability/ms-dtsx2/8a0fcdf9-ee5c-4859-93dc-e669c559b4b5[2.6.3.19 ExecutableType Instance for Transfer Error Messages Task]
** [ ] https://docs.microsoft.com/en-us/openspecs/sql_data_portability/ms-dtsx2/2e4e51cc-ffab-4482-b720-0d6dc07c8313[2.6.3.20 ExecutableType Instance for Transfer Jobs Task]
** [ ] https://docs.microsoft.com/en-us/openspecs/sql_data_portability/ms-dtsx2/3731eaf1-006c-4d54-ad65-b45751f0400c[2.6.3.21 ExecutableType Instance for Transfer Logins Task]
** [ ] https://docs.microsoft.com/en-us/openspecs/sql_data_portability/ms-dtsx2/851d2a4b-139b-489d-98c2-00b1815d95e4[2.6.3.22 ExecutableType Instance for Transfer SQL Server Objects Task]
** [ ] https://docs.microsoft.com/en-us/openspecs/sql_data_portability/ms-dtsx2/36b45bc0-a377-499f-882a-58b12a0c211d[2.6.3.23 ExecutableType Instance for Transfer Stored Procedures Task]
** [ ] https://docs.microsoft.com/en-us/openspecs/sql_data_portability/ms-dtsx2/fa55878d-8c52-4faf-86a4-2f0b74d8e3fb[2.6.3.24 ExecutableType Instance for Web Service Task]
** [ ] https://docs.microsoft.com/en-us/openspecs/sql_data_portability/ms-dtsx2/2f9f3fb7-e594-4792-a09a-374548b71772[2.6.3.25 ExecutableType Instance for WMI Data Reader Task]
** [ ] https://docs.microsoft.com/en-us/openspecs/sql_data_portability/ms-dtsx2/b1a77cfa-20ad-4b82-8969-d15d7f58bbd6[2.6.3.26 ExecutableType Instance for WMI Event Watcher Task]
** [ ] https://docs.microsoft.com/en-us/openspecs/sql_data_portability/ms-dtsx2/2c88dd23-f29b-48d2-ad9d-f58c1e83a9d9[2.6.3.27 ExecutableType Instance for XML Task]


Exec ssis_t.usp_GetPackageDetails 'C:\Packages1'

Exec sys.sp_configure 'show advanced options', 1

Reconfigure With Override
Go

Exec sys.sp_configure 'xp_cmdshell', 1

Reconfigure With Override

*/
CREATE Procedure [ssis_t].[usp_GetPackageDetails] @ProjectPath Varchar(8000) = 'C:\Packages1'
As
Begin
    Set NoCount On;

    --------------------truncate tables------------------------------------
    Truncate Table ssis_t.pkgStats;

    Truncate Table ssis_t.Connection;

    Truncate Table ssis_t.TblPrecedenceConstraint;

    Truncate Table ssis_t.TblConnection;

    Truncate Table ssis_t.TblControlFlow;

    Truncate Table ssis_t.TblTask_Dft_Component;

    Truncate Table ssis_t.TblTask_Dft_Details;

    Truncate Table ssis_t.TblTask_Dft_SrcDest;

    Truncate Table ssis_t.TblTask_Dft_Derived;

    Truncate Table ssis_t.TblTask_ExecutePackage;

    Truncate Table ssis_t.TblTask_Lookup;

    Truncate Table ssis_t.TblTask_Script;

    Truncate Table ssis_t.TblTask_Sql;

    Truncate Table ssis_t.TblTask_Sql_Parameter;

    Truncate Table ssis_t.TblVariable;

    Truncate Table ssis_t.TblParameter;

    Truncate Table ssis_t.tempprecedence1;

    Truncate Table ssis_t.tempprecedence2;

    Truncate Table ssis_t.tempprecedence3;

    Truncate Table ssis_t.tempprecedence4;

    Truncate Table ssis_t.tempprecedence5;

    Truncate Table ssis_t.tempprecedence5_Hierarchy;

    Truncate Table ssis_t.tempprecedence6;

    -------------------truncate tables------------------------------------

    -------------------Iterate over all dtsx files from folder------------------------------
    Declare @Path Varchar(8000) = @ProjectPath + '\*.dtsx';

    Declare @MyFiles Table
    (
        MyID     Int Identity(1, 1) Primary Key
      , FullPath Varchar(8000)
    );

    Declare @CommandLine Varchar(8000);

    Select
        @CommandLine = Left('dir "' + @Path + '" /A-D /B /S', 8000);

    Insert Into @MyFiles
    (
        FullPath
    )
    Execute sys.xp_cmdshell @CommandLine;

    Delete From
    @MyFiles
    Where
        FullPath Is Null
        Or FullPath = 'File Not Found'
        Or FullPath = 'Datei nicht gefunden'
        Or FullPath = 'The system cannot find the path specified.'
        Or FullPath = 'The system cannot find the file specified.'
        Or FullPath = 'Das System kann die angegebene Datei nicht finden.'

    --select * from @MyFiles
    Declare @FullPath Varchar(2000);
    Declare
        @counter       Int = 0
      , @totalpkgcount Int;

    Select
        @totalpkgcount = Count ( * )
    From
        @MyFiles;

    While @counter <= @totalpkgcount
    Begin
        Select
            @FullPath = FullPath
        From
            @MyFiles
        Where
            MyID = @counter;

        Declare @sql NVarchar(Max);

        Set @sql
            = N'
Insert Into ssis_t.pkgStats
(
    ProjectPath
  , PackagePath
  , PackageXML
)
Select
    ProjectPath = ''@ProjectPath''
  , PackagePath = ''@FullPath''
  , PackageXML  = Cast(BulkColumn As Xml)
From
    OpenRowset ( Bulk ''@FullPath'', Single_Blob )
    As pkgColumn
'

        Select
            @sql = Replace ( Replace ( @sql, '@FullPath', @FullPath ), '@ProjectPath', @ProjectPath )

        Exec sys.sp_executesql @sql;

        Set @counter = @counter + 1;
    End

    -------------------Iterate over all dtsx files from folder------------------------------		
    Update
        P
    Set
        P.PackageCreationDate = C.PackageCreationDate
      , P.PackageCreatorComputerName = C.PackageCreatorComputerName
      , P.PackageCreatorName = C.PackageCreatorName
      , P.PackageDescription = C.PackageDescription
      , P.PackageDTSID = C.PackageDTSID
      , P.PackageLastModifiedProductVersion = C.PackageLastModifiedProductVersion
      , P.PackageLocaleID = C.PackageLocaleID
      , P.PackageObjectName = C.PackageObjectName
      , P.PackageProtectionLevel = C.PackageProtectionLevel
      , P.PackageVersionGUID = C.PackageVersionGUID
    From
        ssis_t.pkgStats           As P
        Inner Join
            ssis_t.PackageDetails As C
                On
                P.RowID = C.RowID;

    ------------add package creator name---------------------------
    Print '---------------Get all connections-----------------------------------';

    Insert Into ssis_t.TblConnection
    (
        RowID
      , PackagePath
      , PackageName
      , Category
      , PackageCreatorName
      , ConnectionManagerName
      , ConnectionManagerType
      , DelayValidationPropertyValue
      , ConnectionString
      , ExpressionValue
      , ConnectionManagerID
      , RetainSameConnectionProperty
    )
    Select
        RowID
      , PackagePath
      , PackageName
      , Category
      , PackageCreatorName
      , ConnectionManagerName
      , ConnectionManagerType
      , DelayValidationPropertyValue
      , ConnectionString
      , ExpressionValue
      , ConnectionManagerID
      , RetainSameConnectionProperty
    From
        ssis_t.TblConnection_src

    Print '-------------Insert Connection details in  table----------';

    Insert Into ssis_t.Connection
    (
        ConnectionManager
      , ConnectionManagerID
    )
    Select
        Distinct
        ConnectionManagerName
      , ConnectionManagerID
    From
        ssis_t.TblConnection

    Print '-------------Insert Connection  details in  table----------';
    Print '---------------Get all connections-----------------------------------';
    Print '------------------------Get all variable details-------------------------------------';

    Insert Into ssis_t.TblVariable
    (
        RowID
      , PackagePath
      , PackageName
      , Category
      , PackageCreatorName
      , VariableName
      , VariableDataType
      , VariableValue
      , ExpressionValue
      , VariableHexValue
    )
    Select
        RowID
      , PackagePath
      , PackageName
      , Category
      , PackageCreatorName
      , VariableName
      , VariableDataType
      , VariableValue
      , ExpressionValue
      , VariableHexValue
    From
        ssis_t.TblVariable_src

    Print '------------------------Get all variable details-------------------------------------';
    Print '------------------------Get all parameter details-------------------------------------';

    Insert Into ssis_t.TblParameter
    (
        RowID
      , PackagePath
      , PackageName
      , Category
      , PackageCreatorName
      , ParameterName
      , ParameterDataType
      , ParameterValue
      , ExpressionValue
      , ParameterHexValue
    )
    Select
        RowID
      , PackagePath
      , PackageName
      , Category
      , PackageCreatorName
      , ParameterName
      , ParameterDataType
      , ParameterValue
      , ExpressionValue
      , ParameterHexValue
    From
        ssis_t.TblParameter_src

    Print '------------------------Get all parameter details-------------------------------------';
    Print '----------------Get  precedence constraint details------------------------------';

    Insert Into ssis_t.TblPrecedenceConstraint
    (
        RowID
      , PackagePath
      , TaskFrom
      , TaskTo
      , LogicalAnd
      , ObjectName
      , CreationName
      , DTSID
      , EvalOp
      , Expression
      , FlowType
    )
    Select
        t.RowID
      , t.PackagePath
      , t.TaskFrom
      , t.TaskTo
      , t.LogicalAnd
      , t.ObjectName
      , t.CreationName
      , t.DTSID
      , t.EvalOp
      , t.Expression
      , t.FlowType
    From
        ssis_t.TblPrecedenceConstraint_src As t

    --Insert Into ssis_t.tempprecedence1
    --(
    --    RowID
    --  , TaskFrom
    --  , isparentlevel
    --  , level
    --)
    --Select
    --    Distinct
    --    T.RowID
    --  , T.TaskFrom
    --  , T.isparentlevel
    --  , level = Row_Number () Over ( Partition By T.RowID Order By T.level )
    --From
    --(
    --    Select
    --        Distinct
    --        t1.RowID
    --      , t1.TaskFrom
    --      , isparentlevel = 1
    --      , level         = Len ( t1.TaskFrom ) - Len ( Replace ( t1.TaskFrom, '\', '' ))
    --    From
    --        ssis_t.TblPrecedenceConstraint     As t1
    --        Left Join
    --            ssis_t.TblPrecedenceConstraint As t2
    --                On
    --                t1.RowID        = t2.RowID
    --                And t1.TaskFrom = t2.TaskTo
    --    Where
    --        t2.TaskTo Is Null
    --) As T

    --  Declare
    --      @cntlevel Int
    --    , @cnt      Int = 1;

    --  Select
    --      @cntlevel = Count ( * )
    --  From
    --      ssis_t.tempprecedence1;

    --  While @cnt <= @cntlevel
    --  Begin
    --      ;
    --      With
    --      cte
    --      As
    --          (
    --          Select
    --              RowID
    --            , TaskFrom
    --            , task    = TaskFrom
    --            , level
    --            , cnt     = 1
    --          From
    --              ssis_t.tempprecedence1
    --          Where
    --              level = @cnt
    --          Union All
    --          Select
    --              c.RowID
    --            , c.TaskFrom
    --            , t.TaskTo
    --            , c.level
    --            , c.cnt + 1
    --          From
    --              ssis_t.TblPrecedenceConstraint As t
    --              Inner Join
    --                  cte                        As c
    --                      On
    --                      t.RowID    = c.RowID
    --                      And c.task = t.TaskFrom
    --          )
    --      Insert Into ssis_t.tempprecedence2
    --      (
    --          ROWID
    --        , TaskFrom
    --        , task
    --        , parentlevel
    --        , LEVEL
    --      )
    --      Select
    --          cte.RowID
    --        , cte.TaskFrom
    --        , cte.task
    --        , @cnt
    --        , cte.cnt
    --      From
    --          cte;

    --      Select
    --          @cnt = @cnt + 1;
    --  End

    --  Insert Into ssis_t.tempprecedence3
    --  (
    --      ROWID
    --    , task
    --    , parentlevel
    --    , LEVEL
    --    , trank
    --  )
    --  Select
    --      ROWID
    --    , task
    --    , parentlevel
    --    , LEVEL
    --    , trank = Row_Number () Over ( Partition By ROWID Order By parentlevel, LEVEL )
    --  From
    --      ssis_t.tempprecedence2;

    --  Insert Into ssis_t.tempprecedence4
    --  (
    --      ROWID
    --    , task
    --    , tlevel
    --    , level
    --    , trank
    --  )
    --  Select
    --      t.ROWID
    --    , task   = IsNull ( t1.task, t.task )
    --    , tlevel = t.LEVEL
    --    , level  = IsNull ( Max ( t1.LEVEL ), Max ( t.LEVEL ))
    --    , trank  = IsNull ( Max ( t1.trank ), Max ( t.trank ))
    --  From
    --      ssis_t.tempprecedence3     As t
    --      Left Join
    --          ssis_t.tempprecedence3 As t1
    --              On
    --              t.ROWID = t1.ROWID
    --              And t1.task Like '%' + t.task + '\%'
    --  Group By
    --      t.ROWID
    --    , t1.task
    --    , t.task
    --    , t.LEVEL
    --  --,t1.LEVEL
    --  Order By
    --      level
    --    , trank;

    --  --select t.rowid,t1.task,t.level tlevel,t1.level, (t1.trank) trank into ssis.tempprecedence4
    --  --from ssis.tempprecedence3 t
    --  --join ssis.tempprecedence3 t1
    --  --on t.rowid = t1.rowid
    --  --and t1.task like '%'+t.task+'%'
    --  -- order by trank
    --  Insert Into ssis_t.tempprecedence5
    --  (
    --      ROWID
    --    , task
    --    , sequenceno
    --    , trank
    --  )
    --  Select
    --      t.ROWID
    --    , t.task
    --    , sequenceno = Replace (
    --                               Replace (
    --                                           Replace ((
    --                                                        Select
    --                                                            t1.tlevel
    --                                                        From
    --                                                            ssis_t.tempprecedence4 As t1
    --                                                        Where
    --                                                            t1.ROWID    = t.ROWID
    --                                                            And t1.task = t.task
    --                                                        For Xml Path ( '' )
    --                                                    )
    --                                                  , '</tlevel><tlevel>'
    --                                                  , '/'
    --                                                   )
    --                                         , '</tlevel>'
    --                                         , '/'
    --                                       )
    --                             , '<tlevel>'
    --                             , ''
    --                           )
    --    , t.trank
    --  From
    --      ssis_t.tempprecedence4 As t
    --  Group By
    --      t.ROWID
    --    , t.task
    --    , t.trank
    --  Order By
    --      t.ROWID
    --    , t.trank;

    --  Insert Into ssis_t.tempprecedence5_Hierarchy
    --  (
    --      ROWID
    --    , task
    --    , sequenceno
    --    , rid
    --  )
    --  Select
    --      ROWID
    --    , task
    --    , sequenceno
    --    , rid = Cast('/1/' + sequenceno + Cast(trank As Varchar) + '/' As HierarchyId)
    --  From
    --      ssis_t.tempprecedence5

    --  Insert Into ssis_t.tempprecedence6
    --  (
    --      ROWID
    --    , task
    --    , sequenceno
    --  )
    --  Select
    --      ROWID
    --    , task
    --    , sequenceno = Row_Number () Over ( Partition By ROWID Order By rid )
    --  From
    --      ssis_t.tempprecedence5_Hierarchy;

    --  /*

    -- select t1.task,t1.parentlevel,t.task as t1,row_number() over(partition by t1.rowid order by t.level) level,t.rowid into ssis.tempprecedence3
    --from ssis.tempprecedence2 t
    --join ssis.tempprecedence2 t1
    --on charindex(t.task, t1.taskFrom)>0  
    --and t1.parentlevel >1 and t.parentlevel =1
    --and t.rowid =t1.rowid
    --  order by t.rowid, t1.parentlevel ,t.level 

    --   select  rowid, task,row_number() over(partition by rowid order by max(sequenceno)) sequenceno into ssis.tempprecedence4
    --from(
    --  select distinct t1.rowid,isnull(t2.task,t1.task) Task,row_number() over(partition by t1.rowid order by t1.parentlevel,t1.level,isnull(t2.level,1)) sequenceno  
    --from ssis.tempprecedence2 t1
    --left join ssis.tempprecedence3 t2
    --on t1.rowid = t2.rowid
    --and t1.task = t2.t1
    -- where t1.parentlevel =1  )t
    -- group by rowid,task 
    --*/
    Print '----------------Get  precedence constraint details------------------------------';
    Print '----------------Get all Control flow tasks details------------------------------';
    Print '----------------Get all  data flow tasks details------------------------------';

    Insert Into ssis_t.TblControlFlow
    (
        RowID
      , TaskPath
      , TaskName
      , TaskDescription
      , TaskType
      , DelayValidationPropertyValue
      , DFTQuery
      , SqlTaskQry
      , ExecPkgTaskQry
      , ScriptTaskQry
      , IsDisabled
      , ExpressionValue
    )
    Select
        RowID
      , TaskPath
      , TaskName
      , TaskTypeDescription         = TaskDescription
      , TaskType
      , DelayValidationPropertyValue
      , DFTQuery
      , SqlTaskQry
      , ExecPkgTaskQry
      , ScriptTaskQry
      , IsDisabled
      , ExpressionValue
    From
        ssis_t.TblControlFlow_src

    Print '---------- Insert Script task details-----------------------';

    Insert Into ssis_t.TblTask_Script
    (
        RowID
      , ControlFlowDetailsRowID
      , Script
    )
    Select
        RowID
      , ControlFlowDetailsRowID
      , Script
    From
        ssis_t.TblTask_Script_src

    Print '---------- Insert Sql task details-----------------------';

    Insert Into ssis_t.TblTask_Sql
    (
        RowID
      , ControlFlowDetailsRowID
      , SqlConnection
      , SqlStatementSource
    )
    Select
        RowID
      , ControlFlowDetailsRowID
      , Connection             = SqlConnection
      , SqlStatementSource
    From
        ssis_t.TblTask_Sql_src

    Print '---------- Insert Execute package task details-----------------------';

    Insert Into ssis_t.TblTask_ExecutePackage
    (
        RowID
      , ControlFlowDetailsRowID
      , ExecutePackageExpression
      , ExecutedPackageName
      , ExecutePackageConnection
    )
    Select
        cf.RowID
      , cf.ControlFlowDetailsRowID
      , ExecutePackageExpression = cfnodes1.x.value (
                                                        'declare namespace DTS="www.microsoft.com/SqlServer/Dts";
                    ./DTS:PropertyExpression[1]'
                                                      , 'varchar(1000)'
                                                    )
      , ExecutedPackageName      = cfnodes1.x.value (
                                                        'declare namespace DTS="www.microsoft.com/SqlServer/Dts";
            (./DTS:ObjectData/ExecutePackageTask/PackageName)[1]'
                                                      , 'varchar(1000)'
                                                    )
      , ExecutePackageConnection = cfnodes1.x.value (
                                                        'declare namespace DTS="www.microsoft.com/SqlServer/Dts";
            (./DTS:ObjectData/ExecutePackageTask/Connection)[1]'
                                                      , 'varchar(1000)'
                                                    )
    From
        ssis_t.TblControlFlow                       As cf
        Cross Apply Cf.ExecPkgTaskQry.nodes ( '.' ) As cfnodes1(x);

    --Update
    --    execpkg
    --Set
    --    execpkg.ExecutePackageConnection = pkg.ObjectValue
    --From
    --    ssis_t.TblTask_ExecutePackage As execpkg
    --    Inner Join
    --        ssis_t.PackageAnalysis    As pkg
    --            On
    --            execpkg.RowID               = pkg.RowID
    --            And pkg.Category            = 'Connection'
    --            And pkg.ConnectionManagerID = execpkg.ExecutePackageConnection;

    /*
maybe we can analyse example packages and then join with

the folowing is wrong, it makes no sense to join via ExecutePackageConnection and to update ExecutePackageConnection
one of them is wrong?

or it this a replacement? Then it would be better not to replace but to use an additional column

Update
    execpkg
Set
    execpkg.ExecutePackageConnection = con.?
From
    ssis_t.TblTask_ExecutePackage As execpkg
    Inner Join
        ssis_t.TblConnection      As con
            On
            con.RowID                   = execpkg.RowID
            And con.ConnectionManagerID = execpkg.ExecutePackageConnection;

*/
    Print '---------- Insert Execute SQL task details-----------------------';

    Insert Into ssis_t.TblTask_Sql_Parameter
    (
        RowID
      , ControlFlowDetailsRowID
      , ParameterBindingSequence
      , ParameterBindingParameterName
    )
    Select
        Distinct
        cf.RowID
      , cf.ControlFlowDetailsRowID
      --,cfnodes1.x.value('declare namespace SQLTask="www.microsoft.com/sqlserver/dts/tasks/sqltask"; (./@SQLTask:DtsVariableName)','varchar(1000)') as ResultSetParameterName
      , ParameterBindingSequence      = cfnodes.x.value (
                                                            'declare namespace SQLTask="www.microsoft.com/sqlserver/dts/tasks/sqltask"; (./@SQLTask:ParameterName)'
                                                          , 'varchar(1000)'
                                                        )
      , ParameterBindingParameterName = cfnodes.x.value (
                                                            'declare namespace SQLTask="www.microsoft.com/sqlserver/dts/tasks/sqltask"; (./@SQLTask:DtsVariableName)'
                                                          , 'varchar(1000)'
                                                        )
    From
        ssis_t.TblControlFlow                                                                                                                                          As cf
        Outer Apply Cf.SqlTaskQry.nodes ( 'declare namespace SQLTask="www.microsoft.com/sqlserver/dts/tasks/sqltask";./SQLTask:SqlTaskData/SQLTask:ParameterBinding' ) As cfnodes(x)
    Order By
        1
      , 2
      , 3;

    Update
        sqltsk
    Set
        sqltsk.ResultSetParameterName = CF.ResultSetParameterName
    From
        ssis_t.TblTask_Sql_Parameter As sqltsk
        Inner Join
        (
            Select
                Distinct
                cf.RowID
              , cf.ControlFlowDetailsRowID
              , rid                    = Cast(Row_Number () Over ( Partition By cf.ControlFlowDetailsRowID Order By ( Select 1 )) - 1 As Varchar)
              , ResultSetParameterName = cfnodes1.x.value (
                                                              'declare namespace SQLTask="www.microsoft.com/sqlserver/dts/tasks/sqltask"; (./@SQLTask:DtsVariableName)'
                                                            , 'varchar(1000)'
                                                          )
            From
                ssis_t.TblControlFlow                                                                                                                                       As cf
                Outer Apply Cf.SqlTaskQry.nodes ( 'declare namespace SQLTask="www.microsoft.com/sqlserver/dts/tasks/sqltask";./SQLTask:SqlTaskData/SQLTask:ResultBinding' ) As cfnodes1(x)
        )                            As CF
            On
            sqltsk.ControlFlowDetailsRowID = CF.ControlFlowDetailsRowID
            And CF.rid                     = IsNull ( sqltsk.ParameterBindingSequence, 0 )

    Print '---------- ssis_t.TblTask_Dft_Component -----------------------';

    Insert Into ssis_t.TblTask_Dft_Component
    (
        ControlFlowDetailsRowID
      , RowID
      , refId
      , name
      , componentClassID
      , description
      , ContactInfo
      , CommandTimeout
      , [OpenRowset]
      , OpenRowsetVariable
      , SqlCommand
      , SqlCommandVariable
      , DefaultCodePage
      , AlwaysUseDefaultCodePage
      , AccessMode
      , ParameterMapping
      , FastLoadKeepIdentity
      , FastLoadKeepNulls
      , FastLoadOptions
      , FastLoadMaxInsertCommitSize
      , VariableName
      , Connection_refId
      , connectionManagerID
      , connectionManagerRefId
      , Connection_description
      , Connection_name
      , IsSortedProperty
      , outputsQry
      , inputsQry
    )
    Select
        ControlFlowDetailsRowID
      , RowID
      , refId
      , name
      , componentClassID
      , description
      , ContactInfo
      , CommandTimeout
      , [OpenRowset]
      , OpenRowsetVariable
      , SqlCommand
      , SqlCommandVariable
      , DefaultCodePage
      , AlwaysUseDefaultCodePage
      , AccessMode
      , ParameterMapping
      , FastLoadKeepIdentity
      , FastLoadKeepNulls
      , FastLoadOptions
      , FastLoadMaxInsertCommitSize
      , VariableName
      , Connection_refId
      , connectionManagerID
      , connectionManagerRefId
      , Connection_description
      , Connection_name
      , IsSortedProperty
      , outputsQry
      , inputsQry
    From
        ssis_t.TblTask_Dft_Component_src

    Print '---------- ssis_t.TblTask_Dft_Component -----------------------';
--Print '---------- Insert DFT details-----------------------';

--Insert Into ssis_t.TblTask_Dft_Details
--(
--    ControlFlowDetailsRowID
--  , RowID
--  , DFTTasksPath
--  , DFTTaskName
--  , DFTTaskType
--  , DFTTaskType1
--  , DFTRowSet
--  , ParameterBindingParameterName
--  , DFTSQLCommand
--  , DFTConnectionManager
--  , Variable
--  , IsSortedProperty
--  , InputQry
--  , OutputQry
--  , MultihashcolumnSortPosition
--)
--Select
--    ControlFlowDetailsRowID
--  , RowID
--  , DFTTasksPath
--  , DFTTaskName
--  , DFTTaskType
--  , DFTTaskType1
--  , DFTRowSet
--  , ParameterBindingParameterName
--  , DFTSQLCommand
--  , DFTConnectionManager
--  , Variable
--  , IsSortedProperty
--  , InputQry
--  , OutputQry
--  , MultihashcolumnSortPosition
--From
--    ssis_t.TblTask_Dft_Details_src

--Print '---------- Insert DFT details-----------------------';
----Print '---------- Insert DFT Source and destination details-----------------------';

----Insert Into ssis_t.TblTask_Dft_SrcDest
----(
----    RowID
----  , DataFlowDetailsRowID
----  , SourceColumn
----  , DestinationColumn
----  , SortKeyPosition
----  , DataSource
----)
------from pkglvl.InputQry.nodes
----Select
----    RowID
----  , DataFlowDetailsRowID
----  , SourceColumn
----  , DestinationColumn
----  , SortKeyPosition
----  , DataSource
----From
----    ssis_t.TblTask_Dft_SrcDest_src

----Print '---------- Insert DFT Source and destination details-----------------------';
--Print '---------- Insert DFT Derived task  details-----------------------';

--Insert Into ssis_t.TblTask_Dft_Derived
--(
--    RowID
--  , DataFlowDetailsRowID
--  , DerivedValue
--  , SourceColumn
--  , DestinationColumn
--)
--Select
--    Distinct
--    pkglvl.RowID
--  , pkglvl.DataFlowDetailsRowID
--  , DerivedValue      = IsNull (
--                                   inputvalue.x.value (
--                                                          'data(./properties/property[@description =''Derived Column Friendly Expression''])[1]'
--                                                        , 'varchar(max)'
--                                                      )
--                                 , inputvalue.x.value (
--                                                          'data(./properties/property[@name =''FriendlyExpression''])[1]'
--                                                        , 'varchar(max)'
--                                                      )
--                               )
--  , SourceColumn      = inputvalue.x.value ( './@lineageId[1]', 'varchar(max)' )
--  , DestinationColumn = inputvalue.x.value ( './@refId[1]', 'varchar(max)' )
--From
--    ssis_t.TblTask_Dft_Details                  As pkglvl
--    Cross Apply pkglvl.InputQry.nodes ( './*' ) As inputvalue(x)
--Union All
--Select
--    Distinct
--    pkglvl.RowID
--  , pkglvl.DataFlowDetailsRowID
--  , DerivedValue      = IsNull (
--                                   outputvalue.x1.value (
--                                                            'data(./properties/property[@description =''Derived Column Friendly Expression''])[1]'
--                                                          , 'varchar(max)'
--                                                        )
--                                 , outputvalue.x1.value (
--                                                            'data(./properties/property[@name =''FriendlyExpression''])[1]'
--                                                          , 'varchar(max)'
--                                                        )
--                               )
--  , SourceColumn      = outputvalue.x1.value ( './@lineageId[1]', 'varchar(max)' )
--  , DestinationColumn = outputvalue.x1.value ( './@refId[1]', 'varchar(max)' )
--From
--    ssis_t.TblTask_Dft_Details                   As pkglvl
--    Cross Apply pkglvl.OutputQry.nodes ( './*' ) As outputvalue(x1)
--Where
--    pkglvl.DFTTaskType1 Like '%DERIVED%';

--Print '---------- Insert DFT Derived task  details-----------------------';
--Print '---------- Insert DFT lookup task  details-----------------------';

--Insert Into ssis_t.TblTask_Lookup
--(
--    RowID
--  , DataFlowDetailsRowID
--  , LookupJoins
--  , SourceColumn
--  , DestinationColumn
--)
--Select
--    pkglvl.RowID
--  , pkglvl.DataFlowDetailsRowID
--  , LookupJoins       = outputvalue.x.value ( './@lineageId[1]', 'varchar(max)' ) + '----->'
--                        + outputvalue.x.value (
--                                                  'data(./properties/property[@name =''JoinToReferenceColumn''])[1]'
--                                                , 'varchar(max)'
--                                              )
--  , SourceColumn      = outputvalue1.x.value (
--                                                 'data(./properties/property[@name =''CopyFromReferenceColumn''])[1]'
--                                               , 'varchar(max)'
--                                             )
--  , DestinationColumn = outputvalue1.x.value ( './@refId[1]', 'varchar(max)' )
--From
--    ssis_t.TblTask_Dft_Details                  As pkglvl
--    Cross Apply pkglvl.InputQry.nodes ( './*' ) As outputvalue(x)
--    Cross Apply pkglvl.OutputQry.nodes ( './*' ) As outputvalue1(x)
--Where
--    pkglvl.DFTTaskType = 'Lookup'
--    Or pkglvl.DFTTaskType1 Like '%Lookup%';

--Delete From
--ssis_t.TblTask_Lookup
--Where
--    DestinationColumn Like '%Lookup Error Output%';

--Print '---------- Insert DFT lookup task  details-----------------------';
End
----
=======
// end::sql_modules_definition[]


