// tag::HeaderFullDisplayName[]
= ssis.usp_import - P
// end::HeaderFullDisplayName[]

== existing_properties

// tag::existing_properties[]

:ExistsProperty--antorareferencedlist:
:ExistsProperty--is_repo_managed:
:ExistsProperty--is_ssas:
:ExistsProperty--referencedobjectlist:
:ExistsProperty--sql_modules_definition:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
929A07F7-C23C-EC11-852D-A81E8446D5B0
// end::RepoObject_guid[]

== RepoObject_FullDisplayName2

// tag::RepoObject_FullDisplayName2[]
ssis.usp_import
// end::RepoObject_FullDisplayName2[]

== SysObject_type

// tag::SysObject_type[]
P 
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
stored procedure
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
1458156290
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2021-11-07 15:43:59
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]

// end::AntoraColumnDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]

// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

// end::AntoraIndexList[]

== AntoraMeasureDetails

// tag::AntoraMeasureDetails[]

// end::AntoraMeasureDetails[]

== AntoraMeasureDescriptions



== AntoraParameterList

// tag::AntoraParameterList[]

// end::AntoraParameterList[]

== AntoraXrefCulturesList

// tag::AntoraXrefCulturesList[]
* xref:dhw:sqldb:ssis.usp_import.adoc[] - 
// end::AntoraXrefCulturesList[]

== cultures_count

// tag::cultures_count[]
1
// end::cultures_count[]

== Other tags

source: property.RepoObjectProperty_cross As rop_cross


=== additional_reference_csv

// tag::additional_reference_csv[]

// end::additional_reference_csv[]


=== AdocUspSteps

// tag::adocuspsteps[]

// end::adocuspsteps[]


=== AntoraReferencedList

// tag::antorareferencedlist[]
* xref:dhw:sqldb:ssis.usp_persist_package_tgt.adoc[]
* xref:dhw:sqldb:ssis.usp_persist_packageconnection_tgt.adoc[]
* xref:dhw:sqldb:ssis.usp_persist_packageflow_tgt.adoc[]
* xref:dhw:sqldb:ssis.usp_persist_packageparameter_tgt.adoc[]
* xref:dhw:sqldb:ssis.usp_persist_packagetask_dft_component_input_externalmetadatacolumn_tgt.adoc[]
* xref:dhw:sqldb:ssis.usp_persist_packagetask_dft_component_input_inputcolumn_tgt.adoc[]
* xref:dhw:sqldb:ssis.usp_persist_packagetask_dft_component_input_tgt.adoc[]
* xref:dhw:sqldb:ssis.usp_persist_packagetask_dft_component_output_externalmetadatacolumn_tgt.adoc[]
* xref:dhw:sqldb:ssis.usp_persist_packagetask_dft_component_output_outputcolumn_tgt.adoc[]
* xref:dhw:sqldb:ssis.usp_persist_packagetask_dft_component_output_tgt.adoc[]
* xref:dhw:sqldb:ssis.usp_persist_packagetask_dft_component_tgt.adoc[]
* xref:dhw:sqldb:ssis.usp_persist_packagetask_sql_parameter_tgt.adoc[]
* xref:dhw:sqldb:ssis.usp_persist_packagetask_tgt.adoc[]
* xref:dhw:sqldb:ssis.usp_persist_packagevariable_tgt.adoc[]
* xref:dhw:sqldb:ssis.usp_persist_projectconnection_tgt.adoc[]
// end::antorareferencedlist[]


=== AntoraReferencingList

// tag::antorareferencinglist[]

// end::antorareferencinglist[]


=== Description

// tag::description[]

// end::description[]


=== exampleUsage

// tag::exampleusage[]

// end::exampleusage[]


=== exampleUsage_2

// tag::exampleusage_2[]

// end::exampleusage_2[]


=== exampleUsage_3

// tag::exampleusage_3[]

// end::exampleusage_3[]


=== exampleUsage_4

// tag::exampleusage_4[]

// end::exampleusage_4[]


=== exampleUsage_5

// tag::exampleusage_5[]

// end::exampleusage_5[]


=== exampleWrong_Usage

// tag::examplewrong_usage[]

// end::examplewrong_usage[]


=== has_execution_plan_issue

// tag::has_execution_plan_issue[]

// end::has_execution_plan_issue[]


=== has_get_referenced_issue

// tag::has_get_referenced_issue[]

// end::has_get_referenced_issue[]


=== has_history

// tag::has_history[]

// end::has_history[]


=== has_history_columns

// tag::has_history_columns[]

// end::has_history_columns[]


=== InheritanceType

// tag::inheritancetype[]

// end::inheritancetype[]


=== is_persistence

// tag::is_persistence[]

// end::is_persistence[]


=== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]

// end::is_persistence_check_duplicate_per_pk[]


=== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]

// end::is_persistence_check_for_empty_source[]


=== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]

// end::is_persistence_delete_changed[]


=== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]

// end::is_persistence_delete_missing[]


=== is_persistence_insert

// tag::is_persistence_insert[]

// end::is_persistence_insert[]


=== is_persistence_truncate

// tag::is_persistence_truncate[]

// end::is_persistence_truncate[]


=== is_persistence_update_changed

// tag::is_persistence_update_changed[]

// end::is_persistence_update_changed[]


=== is_repo_managed

// tag::is_repo_managed[]
0
// end::is_repo_managed[]


=== is_ssas

// tag::is_ssas[]
0
// end::is_ssas[]


=== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


=== MS_Description

// tag::ms_description[]

// end::ms_description[]


=== persistence_source_RepoObject_fullname

// tag::persistence_source_repoobject_fullname[]

// end::persistence_source_repoobject_fullname[]


=== persistence_source_RepoObject_fullname2

// tag::persistence_source_repoobject_fullname2[]

// end::persistence_source_repoobject_fullname2[]


=== persistence_source_RepoObject_guid

// tag::persistence_source_repoobject_guid[]

// end::persistence_source_repoobject_guid[]


=== persistence_source_RepoObject_xref

// tag::persistence_source_repoobject_xref[]

// end::persistence_source_repoobject_xref[]


=== pk_index_guid

// tag::pk_index_guid[]

// end::pk_index_guid[]


=== pk_IndexPatternColumnDatatype

// tag::pk_indexpatterncolumndatatype[]

// end::pk_indexpatterncolumndatatype[]


=== pk_IndexPatternColumnName

// tag::pk_indexpatterncolumnname[]

// end::pk_indexpatterncolumnname[]


=== pk_IndexSemanticGroup

// tag::pk_indexsemanticgroup[]

// end::pk_indexsemanticgroup[]


=== ReferencedObjectList

// tag::referencedobjectlist[]
* [ssis].[usp_PERSIST_Package_tgt]
* [ssis].[usp_PERSIST_PackageConnection_tgt]
* [ssis].[usp_PERSIST_PackageFlow_tgt]
* [ssis].[usp_PERSIST_PackageParameter_tgt]
* [ssis].[usp_PERSIST_PackageTask_Dft_Component_input_externalMetadataColumn_tgt]
* [ssis].[usp_PERSIST_PackageTask_Dft_Component_input_inputColumn_tgt]
* [ssis].[usp_PERSIST_PackageTask_Dft_Component_input_tgt]
* [ssis].[usp_PERSIST_PackageTask_Dft_Component_output_externalMetadataColumn_tgt]
* [ssis].[usp_PERSIST_PackageTask_Dft_Component_output_outputColumn_tgt]
* [ssis].[usp_PERSIST_PackageTask_Dft_Component_output_tgt]
* [ssis].[usp_PERSIST_PackageTask_Dft_Component_tgt]
* [ssis].[usp_PERSIST_PackageTask_Sql_Parameter_tgt]
* [ssis].[usp_PERSIST_PackageTask_tgt]
* [ssis].[usp_PERSIST_PackageVariable_tgt]
* [ssis].[usp_PERSIST_ProjectConnection_tgt]
// end::referencedobjectlist[]


=== usp_persistence_RepoObject_guid

// tag::usp_persistence_repoobject_guid[]

// end::usp_persistence_repoobject_guid[]


=== UspExamples

// tag::uspexamples[]

// end::uspexamples[]


=== uspgenerator_usp_id

// tag::uspgenerator_usp_id[]

// end::uspgenerator_usp_id[]


=== UspParameters

// tag::uspparameters[]

// end::uspparameters[]

== Boolean Attributes

source: property.RepoObjectProperty WHERE property_int = 1

// tag::boolean_attributes[]


// end::boolean_attributes[]

== PlantUML diagrams

=== PlantUML Entity

// tag::puml_entity[]
[plantuml, entity-{docname}, svg, subs=macros]
....
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis.usp_import.adoc[]" as ssis.usp_import << P >> {
  --
}
....

// end::puml_entity[]

=== PlantUML Entity 1 1 FK

// tag::puml_entity_1_1_fk[]
[plantuml, entity_1_1_fk-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}





footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_fk[]

=== PlantUML 1 1 ObjectRef

// tag::puml_entity_1_1_objectref[]
[plantuml, entity_1_1_objectref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis.usp_import.adoc[]" as ssis.usp_import << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_package_tgt.adoc[]" as ssis.usp_PERSIST_Package_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packageconnection_tgt.adoc[]" as ssis.usp_PERSIST_PackageConnection_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packageflow_tgt.adoc[]" as ssis.usp_PERSIST_PackageFlow_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packageparameter_tgt.adoc[]" as ssis.usp_PERSIST_PackageParameter_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packagetask_dft_component_input_externalmetadatacolumn_tgt.adoc[]" as ssis.usp_PERSIST_PackageTask_Dft_Component_input_externalMetadataColumn_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packagetask_dft_component_input_inputcolumn_tgt.adoc[]" as ssis.usp_PERSIST_PackageTask_Dft_Component_input_inputColumn_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packagetask_dft_component_input_tgt.adoc[]" as ssis.usp_PERSIST_PackageTask_Dft_Component_input_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packagetask_dft_component_output_externalmetadatacolumn_tgt.adoc[]" as ssis.usp_PERSIST_PackageTask_Dft_Component_output_externalMetadataColumn_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packagetask_dft_component_output_outputcolumn_tgt.adoc[]" as ssis.usp_PERSIST_PackageTask_Dft_Component_output_outputColumn_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packagetask_dft_component_output_tgt.adoc[]" as ssis.usp_PERSIST_PackageTask_Dft_Component_output_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packagetask_dft_component_tgt.adoc[]" as ssis.usp_PERSIST_PackageTask_Dft_Component_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packagetask_sql_parameter_tgt.adoc[]" as ssis.usp_PERSIST_PackageTask_Sql_Parameter_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packagetask_tgt.adoc[]" as ssis.usp_PERSIST_PackageTask_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packagevariable_tgt.adoc[]" as ssis.usp_PERSIST_PackageVariable_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_projectconnection_tgt.adoc[]" as ssis.usp_PERSIST_ProjectConnection_tgt << P >> {
  --
}

ssis.usp_PERSIST_Package_tgt <.. ssis.usp_import
ssis.usp_PERSIST_PackageConnection_tgt <.. ssis.usp_import
ssis.usp_PERSIST_PackageFlow_tgt <.. ssis.usp_import
ssis.usp_PERSIST_PackageParameter_tgt <.. ssis.usp_import
ssis.usp_PERSIST_PackageTask_Dft_Component_input_externalMetadataColumn_tgt <.. ssis.usp_import
ssis.usp_PERSIST_PackageTask_Dft_Component_input_inputColumn_tgt <.. ssis.usp_import
ssis.usp_PERSIST_PackageTask_Dft_Component_input_tgt <.. ssis.usp_import
ssis.usp_PERSIST_PackageTask_Dft_Component_output_externalMetadataColumn_tgt <.. ssis.usp_import
ssis.usp_PERSIST_PackageTask_Dft_Component_output_outputColumn_tgt <.. ssis.usp_import
ssis.usp_PERSIST_PackageTask_Dft_Component_output_tgt <.. ssis.usp_import
ssis.usp_PERSIST_PackageTask_Dft_Component_tgt <.. ssis.usp_import
ssis.usp_PERSIST_PackageTask_Sql_Parameter_tgt <.. ssis.usp_import
ssis.usp_PERSIST_PackageTask_tgt <.. ssis.usp_import
ssis.usp_PERSIST_PackageVariable_tgt <.. ssis.usp_import
ssis.usp_PERSIST_ProjectConnection_tgt <.. ssis.usp_import

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_objectref[]

=== PlantUML 30 0 ObjectRef

// tag::puml_entity_30_0_objectref[]
[plantuml, entity_30_0_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:logs.executionlog.adoc[]" as logs.ExecutionLog << U >> {
  - **id** : (bigint)
  --
}

entity "puml-link:dhw:sqldb:logs.usp_executionlog_insert.adoc[]" as logs.usp_ExecutionLog_insert << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.antoramodule_tgt_filter.adoc[]" as ssis.AntoraModule_tgt_filter << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.package_src.adoc[]" as ssis.Package_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  --
}

entity "puml-link:dhw:sqldb:ssis.package_tgt.adoc[]" as ssis.Package_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  --
}

entity "puml-link:dhw:sqldb:ssis.packageconnection_src.adoc[]" as ssis.PackageConnection_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **ConnectionManagerID** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:ssis.packageconnection_tgt.adoc[]" as ssis.PackageConnection_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **ConnectionManagerID** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:ssis.packageflow_src.adoc[]" as ssis.PackageFlow_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **TaskFrom** : (varchar(2000))
  **Taskto** : (varchar(2000))
  --
}

entity "puml-link:dhw:sqldb:ssis.packageflow_tgt.adoc[]" as ssis.PackageFlow_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **TaskFrom** : (varchar(2000))
  **Taskto** : (varchar(2000))
  --
}

entity "puml-link:dhw:sqldb:ssis.packageparameter_src.adoc[]" as ssis.PackageParameter_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **ParameterName** : (varchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssis.packageparameter_tgt.adoc[]" as ssis.PackageParameter_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **ParameterName** : (varchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_input_externalmetadatacolumn_src.adoc[]" as ssis.PackageTask_Dft_Component_input_externalMetadataColumn_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Column_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_input_externalmetadatacolumn_tgt.adoc[]" as ssis.PackageTask_Dft_Component_input_externalMetadataColumn_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Column_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_input_inputcolumn_src.adoc[]" as ssis.PackageTask_Dft_Component_input_inputColumn_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Column_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_input_inputcolumn_tgt.adoc[]" as ssis.PackageTask_Dft_Component_input_inputColumn_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Column_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_input_src.adoc[]" as ssis.PackageTask_Dft_Component_input_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **input_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_input_tgt.adoc[]" as ssis.PackageTask_Dft_Component_input_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **input_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_output_externalmetadatacolumn_src.adoc[]" as ssis.PackageTask_Dft_Component_output_externalMetadataColumn_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Column_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_output_externalmetadatacolumn_tgt.adoc[]" as ssis.PackageTask_Dft_Component_output_externalMetadataColumn_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Column_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_output_outputcolumn_src.adoc[]" as ssis.PackageTask_Dft_Component_output_outputcolumn_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Column_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_output_outputcolumn_tgt.adoc[]" as ssis.PackageTask_Dft_Component_output_outputColumn_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Column_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_output_src.adoc[]" as ssis.PackageTask_Dft_Component_output_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **output_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_output_tgt.adoc[]" as ssis.PackageTask_Dft_Component_output_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **output_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_src.adoc[]" as ssis.PackageTask_Dft_Component_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Component_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_tgt.adoc[]" as ssis.PackageTask_Dft_Component_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Component_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_sql_parameter_src.adoc[]" as ssis.PackageTask_Sql_Parameter_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **TaskPath** : (varchar(8000))
  **ParameterBindingSequence** : (varchar(1000))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_sql_parameter_tgt.adoc[]" as ssis.PackageTask_Sql_Parameter_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **TaskPath** : (varchar(8000))
  **ParameterBindingSequence** : (varchar(1000))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_src.adoc[]" as ssis.PackageTask_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **TaskPath** : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_tgt.adoc[]" as ssis.PackageTask_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **TaskPath** : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagevariable_src.adoc[]" as ssis.PackageVariable_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **VariableName** : (varchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagevariable_tgt.adoc[]" as ssis.PackageVariable_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **VariableName** : (varchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssis.project.adoc[]" as ssis.Project << U >> {
  - **AntoraModule** : (varchar(50))
  --
}

entity "puml-link:dhw:sqldb:ssis.projectconnection_src.adoc[]" as ssis.ProjectConnection_src << V >> {
  - **AntoraModule** : (varchar(50))
  **ConnectionManagerID** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:ssis.projectconnection_tgt.adoc[]" as ssis.ProjectConnection_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  **ConnectionManagerID** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_import.adoc[]" as ssis.usp_import << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_package_tgt.adoc[]" as ssis.usp_PERSIST_Package_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packageconnection_tgt.adoc[]" as ssis.usp_PERSIST_PackageConnection_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packageflow_tgt.adoc[]" as ssis.usp_PERSIST_PackageFlow_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packageparameter_tgt.adoc[]" as ssis.usp_PERSIST_PackageParameter_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packagetask_dft_component_input_externalmetadatacolumn_tgt.adoc[]" as ssis.usp_PERSIST_PackageTask_Dft_Component_input_externalMetadataColumn_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packagetask_dft_component_input_inputcolumn_tgt.adoc[]" as ssis.usp_PERSIST_PackageTask_Dft_Component_input_inputColumn_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packagetask_dft_component_input_tgt.adoc[]" as ssis.usp_PERSIST_PackageTask_Dft_Component_input_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packagetask_dft_component_output_externalmetadatacolumn_tgt.adoc[]" as ssis.usp_PERSIST_PackageTask_Dft_Component_output_externalMetadataColumn_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packagetask_dft_component_output_outputcolumn_tgt.adoc[]" as ssis.usp_PERSIST_PackageTask_Dft_Component_output_outputColumn_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packagetask_dft_component_output_tgt.adoc[]" as ssis.usp_PERSIST_PackageTask_Dft_Component_output_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packagetask_dft_component_tgt.adoc[]" as ssis.usp_PERSIST_PackageTask_Dft_Component_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packagetask_sql_parameter_tgt.adoc[]" as ssis.usp_PERSIST_PackageTask_Sql_Parameter_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packagetask_tgt.adoc[]" as ssis.usp_PERSIST_PackageTask_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packagevariable_tgt.adoc[]" as ssis.usp_PERSIST_PackageVariable_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_projectconnection_tgt.adoc[]" as ssis.usp_PERSIST_ProjectConnection_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.pkgstats.adoc[]" as ssis_t.pkgStats << U >> {
  - **RowID** : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.projectconnection.adoc[]" as ssis_t.ProjectConnection << U >> {
  - **RowID** : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tblconnection.adoc[]" as ssis_t.TblConnection << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tblcontrolflow.adoc[]" as ssis_t.TblControlFlow << U >> {
  - **ControlFlowDetailsRowID** : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tblparameter.adoc[]" as ssis_t.TblParameter << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tblprecedenceconstraint.adoc[]" as ssis_t.TblPrecedenceConstraint << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tblprojectconnection.adoc[]" as ssis_t.TblProjectConnection << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_dft_component.adoc[]" as ssis_t.TblTask_Dft_Component << U >> {
  - **DftComponentId** : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_dft_component_inputs_externalmetadatacolumn_src.adoc[]" as ssis_t.TblTask_Dft_Component_inputs_externalMetadataColumn_src << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_dft_component_inputs_inputcolumn_src.adoc[]" as ssis_t.TblTask_Dft_Component_inputs_inputColumn_src << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_dft_component_inputs_src.adoc[]" as ssis_t.TblTask_Dft_Component_inputs_src << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_dft_component_outputs_externalmetadatacolumn_src.adoc[]" as ssis_t.TblTask_Dft_Component_outputs_externalMetadataColumn_src << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_dft_component_outputs_outputcolumn_src.adoc[]" as ssis_t.TblTask_Dft_Component_outputs_outputColumn_src << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_dft_component_outputs_src.adoc[]" as ssis_t.TblTask_Dft_Component_outputs_src << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_executepackage.adoc[]" as ssis_t.TblTask_ExecutePackage << U >> {
  - **ControlFlowDetailsRowID** : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_script.adoc[]" as ssis_t.TblTask_Script << U >> {
  - **ControlFlowDetailsRowID** : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_sql.adoc[]" as ssis_t.TblTask_Sql << U >> {
  - **ControlFlowDetailsRowID** : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_sql_parameter.adoc[]" as ssis_t.TblTask_Sql_Parameter << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tblvariable.adoc[]" as ssis_t.TblVariable << U >> {
  --
}

logs.ExecutionLog <.. logs.usp_ExecutionLog_insert
logs.usp_ExecutionLog_insert <.. ssis.usp_PERSIST_ProjectConnection_tgt
logs.usp_ExecutionLog_insert <.. ssis.usp_PERSIST_PackageTask_Dft_Component_tgt
logs.usp_ExecutionLog_insert <.. ssis.usp_PERSIST_PackageTask_Dft_Component_input_externalMetadataColumn_tgt
logs.usp_ExecutionLog_insert <.. ssis.usp_PERSIST_PackageTask_Dft_Component_input_inputColumn_tgt
logs.usp_ExecutionLog_insert <.. ssis.usp_PERSIST_PackageTask_Dft_Component_input_tgt
logs.usp_ExecutionLog_insert <.. ssis.usp_PERSIST_PackageTask_Dft_Component_output_tgt
logs.usp_ExecutionLog_insert <.. ssis.usp_PERSIST_PackageTask_Dft_Component_output_externalMetadataColumn_tgt
logs.usp_ExecutionLog_insert <.. ssis.usp_PERSIST_PackageTask_Dft_Component_output_outputColumn_tgt
logs.usp_ExecutionLog_insert <.. ssis.usp_PERSIST_PackageTask_tgt
logs.usp_ExecutionLog_insert <.. ssis.usp_PERSIST_Package_tgt
logs.usp_ExecutionLog_insert <.. ssis.usp_PERSIST_PackageVariable_tgt
logs.usp_ExecutionLog_insert <.. ssis.usp_PERSIST_PackageTask_Sql_Parameter_tgt
logs.usp_ExecutionLog_insert <.. ssis.usp_PERSIST_PackageParameter_tgt
logs.usp_ExecutionLog_insert <.. ssis.usp_PERSIST_PackageFlow_tgt
logs.usp_ExecutionLog_insert <.. ssis.usp_PERSIST_PackageConnection_tgt
ssis.AntoraModule_tgt_filter <.. ssis.PackageVariable_tgt
ssis.AntoraModule_tgt_filter <.. ssis.ProjectConnection_tgt
ssis.AntoraModule_tgt_filter <.. ssis.PackageTask_tgt
ssis.AntoraModule_tgt_filter <.. ssis.PackageTask_Sql_Parameter_tgt
ssis.AntoraModule_tgt_filter <.. ssis.PackageTask_Dft_Component_input_inputColumn_tgt
ssis.AntoraModule_tgt_filter <.. ssis.PackageTask_Dft_Component_tgt
ssis.AntoraModule_tgt_filter <.. ssis.PackageTask_Dft_Component_input_externalMetadataColumn_tgt
ssis.AntoraModule_tgt_filter <.. ssis.PackageTask_Dft_Component_input_tgt
ssis.AntoraModule_tgt_filter <.. ssis.PackageTask_Dft_Component_output_outputcolumn_tgt
ssis.AntoraModule_tgt_filter <.. ssis.PackageTask_Dft_Component_output_tgt
ssis.AntoraModule_tgt_filter <.. ssis.PackageTask_Dft_Component_output_externalMetadataColumn_tgt
ssis.AntoraModule_tgt_filter <.. ssis.Package_tgt
ssis.AntoraModule_tgt_filter <.. ssis.PackageConnection_tgt
ssis.AntoraModule_tgt_filter <.. ssis.PackageFlow_tgt
ssis.AntoraModule_tgt_filter <.. ssis.PackageParameter_tgt
ssis.Package_src <.. ssis.Package_tgt
ssis.Package_src <.. ssis.PackageFlow_src
ssis.Package_src <.. ssis.PackageVariable_src
ssis.Package_src <.. ssis.PackageTask_Dft_Component_src
ssis.Package_src <.. ssis.PackageTask_Dft_Component_output_src
ssis.Package_src <.. ssis.PackageTask_Dft_Component_input_src
ssis.Package_src <.. ssis.PackageTask_src
ssis.Package_src <.. ssis.PackageTask_Sql_Parameter_src
ssis.Package_src <.. ssis.PackageConnection_src
ssis.Package_src <.. ssis.PackageParameter_src
ssis.Package_src <.. ssis.AntoraModule_tgt_filter
ssis.Package_src <.. ssis.PackageTask_Dft_Component_input_inputColumn_src
ssis.Package_src <.. ssis.usp_PERSIST_Package_tgt
ssis.Package_src <.. ssis.PackageTask_Dft_Component_output_externalMetadataColumn_src
ssis.Package_src <.. ssis.PackageTask_Dft_Component_output_outputcolumn_src
ssis.Package_src <.. ssis.PackageTask_Dft_Component_input_externalMetadataColumn_src
ssis.Package_tgt <.. ssis.usp_PERSIST_Package_tgt
ssis.PackageConnection_src <.. ssis.usp_PERSIST_PackageConnection_tgt
ssis.PackageConnection_src <.. ssis.PackageConnection_tgt
ssis.PackageConnection_tgt <.. ssis.usp_PERSIST_PackageConnection_tgt
ssis.PackageFlow_src <.. ssis.PackageFlow_tgt
ssis.PackageFlow_src <.. ssis.usp_PERSIST_PackageFlow_tgt
ssis.PackageFlow_tgt <.. ssis.usp_PERSIST_PackageFlow_tgt
ssis.PackageParameter_src <.. ssis.PackageParameter_tgt
ssis.PackageParameter_src <.. ssis.usp_PERSIST_PackageParameter_tgt
ssis.PackageParameter_tgt <.. ssis.usp_PERSIST_PackageParameter_tgt
ssis.PackageTask_Dft_Component_input_externalMetadataColumn_src <.. ssis.usp_PERSIST_PackageTask_Dft_Component_input_externalMetadataColumn_tgt
ssis.PackageTask_Dft_Component_input_externalMetadataColumn_src <.. ssis.PackageTask_Dft_Component_input_externalMetadataColumn_tgt
ssis.PackageTask_Dft_Component_input_externalMetadataColumn_tgt <.. ssis.usp_PERSIST_PackageTask_Dft_Component_input_externalMetadataColumn_tgt
ssis.PackageTask_Dft_Component_input_inputColumn_src <.. ssis.usp_PERSIST_PackageTask_Dft_Component_input_inputColumn_tgt
ssis.PackageTask_Dft_Component_input_inputColumn_src <.. ssis.PackageTask_Dft_Component_input_inputColumn_tgt
ssis.PackageTask_Dft_Component_input_inputColumn_tgt <.. ssis.usp_PERSIST_PackageTask_Dft_Component_input_inputColumn_tgt
ssis.PackageTask_Dft_Component_input_src <.. ssis.PackageTask_Dft_Component_input_tgt
ssis.PackageTask_Dft_Component_input_src <.. ssis.usp_PERSIST_PackageTask_Dft_Component_input_tgt
ssis.PackageTask_Dft_Component_input_tgt <.. ssis.usp_PERSIST_PackageTask_Dft_Component_input_tgt
ssis.PackageTask_Dft_Component_output_externalMetadataColumn_src <.. ssis.PackageTask_Dft_Component_output_externalMetadataColumn_tgt
ssis.PackageTask_Dft_Component_output_externalMetadataColumn_src <.. ssis.usp_PERSIST_PackageTask_Dft_Component_output_externalMetadataColumn_tgt
ssis.PackageTask_Dft_Component_output_externalMetadataColumn_tgt <.. ssis.usp_PERSIST_PackageTask_Dft_Component_output_externalMetadataColumn_tgt
ssis.PackageTask_Dft_Component_output_outputcolumn_src <.. ssis.usp_PERSIST_PackageTask_Dft_Component_output_outputColumn_tgt
ssis.PackageTask_Dft_Component_output_outputcolumn_src <.. ssis.PackageTask_Dft_Component_output_outputcolumn_tgt
ssis.PackageTask_Dft_Component_output_outputColumn_tgt <.. ssis.usp_PERSIST_PackageTask_Dft_Component_output_outputColumn_tgt
ssis.PackageTask_Dft_Component_output_src <.. ssis.usp_PERSIST_PackageTask_Dft_Component_output_tgt
ssis.PackageTask_Dft_Component_output_src <.. ssis.PackageTask_Dft_Component_output_tgt
ssis.PackageTask_Dft_Component_output_tgt <.. ssis.usp_PERSIST_PackageTask_Dft_Component_output_tgt
ssis.PackageTask_Dft_Component_src <.. ssis.usp_PERSIST_PackageTask_Dft_Component_tgt
ssis.PackageTask_Dft_Component_src <.. ssis.PackageTask_Dft_Component_tgt
ssis.PackageTask_Dft_Component_tgt <.. ssis.usp_PERSIST_PackageTask_Dft_Component_tgt
ssis.PackageTask_Sql_Parameter_src <.. ssis.PackageTask_Sql_Parameter_tgt
ssis.PackageTask_Sql_Parameter_src <.. ssis.usp_PERSIST_PackageTask_Sql_Parameter_tgt
ssis.PackageTask_Sql_Parameter_tgt <.. ssis.usp_PERSIST_PackageTask_Sql_Parameter_tgt
ssis.PackageTask_src <.. ssis.usp_PERSIST_PackageTask_tgt
ssis.PackageTask_src <.. ssis.PackageTask_tgt
ssis.PackageTask_tgt <.. ssis.usp_PERSIST_PackageTask_tgt
ssis.PackageVariable_src <.. ssis.usp_PERSIST_PackageVariable_tgt
ssis.PackageVariable_src <.. ssis.PackageVariable_tgt
ssis.PackageVariable_tgt <.. ssis.usp_PERSIST_PackageVariable_tgt
ssis.Project <.. ssis.ProjectConnection_src
ssis.Project <.. ssis.Package_src
ssis.ProjectConnection_src <.. ssis.usp_PERSIST_ProjectConnection_tgt
ssis.ProjectConnection_src <.. ssis.ProjectConnection_tgt
ssis.ProjectConnection_tgt <.. ssis.usp_PERSIST_ProjectConnection_tgt
ssis.usp_PERSIST_Package_tgt <.. ssis.usp_import
ssis.usp_PERSIST_PackageConnection_tgt <.. ssis.usp_import
ssis.usp_PERSIST_PackageFlow_tgt <.. ssis.usp_import
ssis.usp_PERSIST_PackageParameter_tgt <.. ssis.usp_import
ssis.usp_PERSIST_PackageTask_Dft_Component_input_externalMetadataColumn_tgt <.. ssis.usp_import
ssis.usp_PERSIST_PackageTask_Dft_Component_input_inputColumn_tgt <.. ssis.usp_import
ssis.usp_PERSIST_PackageTask_Dft_Component_input_tgt <.. ssis.usp_import
ssis.usp_PERSIST_PackageTask_Dft_Component_output_externalMetadataColumn_tgt <.. ssis.usp_import
ssis.usp_PERSIST_PackageTask_Dft_Component_output_outputColumn_tgt <.. ssis.usp_import
ssis.usp_PERSIST_PackageTask_Dft_Component_output_tgt <.. ssis.usp_import
ssis.usp_PERSIST_PackageTask_Dft_Component_tgt <.. ssis.usp_import
ssis.usp_PERSIST_PackageTask_Sql_Parameter_tgt <.. ssis.usp_import
ssis.usp_PERSIST_PackageTask_tgt <.. ssis.usp_import
ssis.usp_PERSIST_PackageVariable_tgt <.. ssis.usp_import
ssis.usp_PERSIST_ProjectConnection_tgt <.. ssis.usp_import
ssis_t.pkgStats <.. ssis.Package_src
ssis_t.ProjectConnection <.. ssis.ProjectConnection_src
ssis_t.TblConnection <.. ssis.PackageConnection_src
ssis_t.TblControlFlow <.. ssis.PackageTask_Sql_Parameter_src
ssis_t.TblControlFlow <.. ssis.PackageTask_Dft_Component_output_externalMetadataColumn_src
ssis_t.TblControlFlow <.. ssis.PackageTask_Dft_Component_input_inputColumn_src
ssis_t.TblControlFlow <.. ssis.PackageTask_src
ssis_t.TblControlFlow <.. ssis.PackageTask_Dft_Component_input_src
ssis_t.TblControlFlow <.. ssis.PackageTask_Dft_Component_src
ssis_t.TblControlFlow <.. ssis.PackageTask_Dft_Component_input_externalMetadataColumn_src
ssis_t.TblControlFlow <.. ssis.PackageTask_Dft_Component_output_outputcolumn_src
ssis_t.TblControlFlow <.. ssis.PackageTask_Dft_Component_output_src
ssis_t.TblParameter <.. ssis.PackageParameter_src
ssis_t.TblPrecedenceConstraint <.. ssis.PackageFlow_src
ssis_t.TblProjectConnection <.. ssis.ProjectConnection_src
ssis_t.TblTask_Dft_Component <.. ssis_t.TblTask_Dft_Component_outputs_externalMetadataColumn_src
ssis_t.TblTask_Dft_Component <.. ssis_t.TblTask_Dft_Component_inputs_src
ssis_t.TblTask_Dft_Component <.. ssis_t.TblTask_Dft_Component_outputs_src
ssis_t.TblTask_Dft_Component <.. ssis.PackageTask_Dft_Component_src
ssis_t.TblTask_Dft_Component <.. ssis_t.TblTask_Dft_Component_inputs_externalMetadataColumn_src
ssis_t.TblTask_Dft_Component <.. ssis_t.TblTask_Dft_Component_inputs_inputColumn_src
ssis_t.TblTask_Dft_Component <.. ssis_t.TblTask_Dft_Component_outputs_outputColumn_src
ssis_t.TblTask_Dft_Component_inputs_externalMetadataColumn_src <.. ssis.PackageTask_Dft_Component_input_externalMetadataColumn_src
ssis_t.TblTask_Dft_Component_inputs_inputColumn_src <.. ssis.PackageTask_Dft_Component_input_inputColumn_src
ssis_t.TblTask_Dft_Component_inputs_src <.. ssis.PackageTask_Dft_Component_input_src
ssis_t.TblTask_Dft_Component_outputs_externalMetadataColumn_src <.. ssis.PackageTask_Dft_Component_output_externalMetadataColumn_src
ssis_t.TblTask_Dft_Component_outputs_outputColumn_src <.. ssis.PackageTask_Dft_Component_output_outputcolumn_src
ssis_t.TblTask_Dft_Component_outputs_src <.. ssis.PackageTask_Dft_Component_output_src
ssis_t.TblTask_ExecutePackage <.. ssis.PackageTask_src
ssis_t.TblTask_Script <.. ssis.PackageTask_src
ssis_t.TblTask_Sql <.. ssis.PackageTask_src
ssis_t.TblTask_Sql_Parameter <.. ssis.PackageTask_Sql_Parameter_src
ssis_t.TblVariable <.. ssis.PackageVariable_src

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_30_0_objectref[]

=== PlantUML 0 30 ObjectRef

// tag::puml_entity_0_30_objectref[]
[plantuml, entity_0_30_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis.usp_import.adoc[]" as ssis.usp_import << P >> {
  --
}



footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_0_30_objectref[]

=== PlantUML 1 1 ColumnRef

// tag::puml_entity_1_1_colref[]
[plantuml, entity_1_1_colref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis.usp_import.adoc[]" as ssis.usp_import << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_package_tgt.adoc[]" as ssis.usp_PERSIST_Package_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packageconnection_tgt.adoc[]" as ssis.usp_PERSIST_PackageConnection_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packageflow_tgt.adoc[]" as ssis.usp_PERSIST_PackageFlow_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packageparameter_tgt.adoc[]" as ssis.usp_PERSIST_PackageParameter_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packagetask_dft_component_input_externalmetadatacolumn_tgt.adoc[]" as ssis.usp_PERSIST_PackageTask_Dft_Component_input_externalMetadataColumn_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packagetask_dft_component_input_inputcolumn_tgt.adoc[]" as ssis.usp_PERSIST_PackageTask_Dft_Component_input_inputColumn_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packagetask_dft_component_input_tgt.adoc[]" as ssis.usp_PERSIST_PackageTask_Dft_Component_input_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packagetask_dft_component_output_externalmetadatacolumn_tgt.adoc[]" as ssis.usp_PERSIST_PackageTask_Dft_Component_output_externalMetadataColumn_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packagetask_dft_component_output_outputcolumn_tgt.adoc[]" as ssis.usp_PERSIST_PackageTask_Dft_Component_output_outputColumn_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packagetask_dft_component_output_tgt.adoc[]" as ssis.usp_PERSIST_PackageTask_Dft_Component_output_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packagetask_dft_component_tgt.adoc[]" as ssis.usp_PERSIST_PackageTask_Dft_Component_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packagetask_sql_parameter_tgt.adoc[]" as ssis.usp_PERSIST_PackageTask_Sql_Parameter_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packagetask_tgt.adoc[]" as ssis.usp_PERSIST_PackageTask_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packagevariable_tgt.adoc[]" as ssis.usp_PERSIST_PackageVariable_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_projectconnection_tgt.adoc[]" as ssis.usp_PERSIST_ProjectConnection_tgt << P >> {
  --
}

ssis.usp_PERSIST_Package_tgt <.. ssis.usp_import
ssis.usp_PERSIST_PackageConnection_tgt <.. ssis.usp_import
ssis.usp_PERSIST_PackageFlow_tgt <.. ssis.usp_import
ssis.usp_PERSIST_PackageParameter_tgt <.. ssis.usp_import
ssis.usp_PERSIST_PackageTask_Dft_Component_input_externalMetadataColumn_tgt <.. ssis.usp_import
ssis.usp_PERSIST_PackageTask_Dft_Component_input_inputColumn_tgt <.. ssis.usp_import
ssis.usp_PERSIST_PackageTask_Dft_Component_input_tgt <.. ssis.usp_import
ssis.usp_PERSIST_PackageTask_Dft_Component_output_externalMetadataColumn_tgt <.. ssis.usp_import
ssis.usp_PERSIST_PackageTask_Dft_Component_output_outputColumn_tgt <.. ssis.usp_import
ssis.usp_PERSIST_PackageTask_Dft_Component_output_tgt <.. ssis.usp_import
ssis.usp_PERSIST_PackageTask_Dft_Component_tgt <.. ssis.usp_import
ssis.usp_PERSIST_PackageTask_Sql_Parameter_tgt <.. ssis.usp_import
ssis.usp_PERSIST_PackageTask_tgt <.. ssis.usp_import
ssis.usp_PERSIST_PackageVariable_tgt <.. ssis.usp_import
ssis.usp_PERSIST_ProjectConnection_tgt <.. ssis.usp_import


footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_colref[]


== sql_modules_definition

// tag::sql_modules_definition[]
[%collapsible]
=======
[source,sql,numbered,indent=0]
----

CREATE Procedure ssis.usp_import
As
Exec ssis.usp_PERSIST_Package_tgt

Exec ssis.usp_PERSIST_PackageConnection_tgt

Exec ssis.usp_PERSIST_PackageFlow_tgt

Exec ssis.usp_PERSIST_PackageParameter_tgt

Exec ssis.usp_PERSIST_PackageTask_Dft_Component_tgt

--Exec ssis.usp_PERSIST_PackageTask_Dft_SrcDest_tgt
Exec ssis.usp_PERSIST_PackageTask_Dft_Component_input_tgt

Exec ssis.usp_PERSIST_PackageTask_Dft_Component_input_externalMetadataColumn_tgt

Exec ssis.usp_PERSIST_PackageTask_Dft_Component_input_inputColumn_tgt

Exec ssis.usp_PERSIST_PackageTask_Dft_Component_output_tgt

Exec ssis.usp_PERSIST_PackageTask_Dft_Component_output_externalMetadataColumn_tgt

Exec ssis.usp_PERSIST_PackageTask_Dft_Component_output_outputColumn_tgt

Exec ssis.usp_PERSIST_PackageTask_Sql_Parameter_tgt

Exec ssis.usp_PERSIST_PackageTask_tgt

Exec ssis.usp_PERSIST_PackageVariable_tgt

Exec ssis.usp_PERSIST_ProjectConnection_tgt
----
=======
// end::sql_modules_definition[]


