// tag::HeaderFullDisplayName[]
= ssis.PackageTask_tgt - V
// end::HeaderFullDisplayName[]

== existing_properties

// tag::existing_properties[]

:ExistsProperty--antorareferencedlist:
:ExistsProperty--antorareferencinglist:
:ExistsProperty--has_history:
:ExistsProperty--has_history_columns:
:ExistsProperty--is_persistence:
:ExistsProperty--is_persistence_check_duplicate_per_pk:
:ExistsProperty--is_persistence_check_for_empty_source:
:ExistsProperty--is_persistence_delete_changed:
:ExistsProperty--is_persistence_delete_missing:
:ExistsProperty--is_persistence_insert:
:ExistsProperty--is_persistence_truncate:
:ExistsProperty--is_persistence_update_changed:
:ExistsProperty--is_repo_managed:
:ExistsProperty--is_ssas:
:ExistsProperty--persistence_source_repoobject_fullname:
:ExistsProperty--persistence_source_repoobject_fullname2:
:ExistsProperty--persistence_source_repoobject_guid:
:ExistsProperty--persistence_source_repoobject_xref:
:ExistsProperty--pk_index_guid:
:ExistsProperty--pk_indexpatterncolumndatatype:
:ExistsProperty--pk_indexpatterncolumnname:
:ExistsProperty--referencedobjectlist:
:ExistsProperty--usp_persistence_repoobject_guid:
:ExistsProperty--sql_modules_definition:
:ExistsProperty--FK:
:ExistsProperty--AntoraIndexList:
:ExistsProperty--Columns:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
6D64FBE4-113B-EC11-852C-A81E8446D5B0
// end::RepoObject_guid[]

== RepoObject_FullDisplayName2

// tag::RepoObject_FullDisplayName2[]
ssis.PackageTask_tgt
// end::RepoObject_FullDisplayName2[]

== SysObject_type

// tag::SysObject_type[]
V 
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
view
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
210151844
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2021-11-01 16:53:53
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]
[discrete]
== _


[#column-antoramodule]
=== AntoraModule

[cols="d,8a,m,m,m"]
|===
|1
|*AntoraModule*
|varchar(50)
|NOT NULL
|
|===

.Referenced Columns
--
* xref:ssis.packagetask.adoc#column-antoramodule[+ssis.PackageTask.AntoraModule+]
* xref:ssis.packagetask_src.adoc#column-antoramodule[+ssis.PackageTask_src.AntoraModule+]
--


[#column-packagename]
=== PackageName

[cols="d,8a,m,m,m"]
|===
|2
|*PackageName*
|varchar(200)
|NOT NULL
|
|===

.Referenced Columns
--
* xref:ssis.packagetask.adoc#column-packagename[+ssis.PackageTask.PackageName+]
* xref:ssis.packagetask_src.adoc#column-packagename[+ssis.PackageTask_src.PackageName+]
--


[#column-taskpath]
=== TaskPath

[cols="d,8a,m,m,m"]
|===
|3
|*TaskPath*
|varchar(8000)
|NOT NULL
|
|===

.Referenced Columns
--
* xref:ssis.packagetask.adoc#column-taskpath[+ssis.PackageTask.TaskPath+]
* xref:ssis.packagetask_src.adoc#column-taskpath[+ssis.PackageTask_src.TaskPath+]
--


[#column-controlflowdetailsrowid]
=== ControlFlowDetailsRowID

[cols="d,8a,m,m,m"]
|===
|
|ControlFlowDetailsRowID
|int
|NOT NULL
|
|===

.Referenced Columns
--
* xref:ssis.packagetask.adoc#column-controlflowdetailsrowid[+ssis.PackageTask.ControlFlowDetailsRowID+]
* xref:ssis.packagetask_src.adoc#column-controlflowdetailsrowid[+ssis.PackageTask_src.ControlFlowDetailsRowID+]
--


[#column-delayvalidationpropertyvalue]
=== DelayValidationPropertyValue

[cols="d,8a,m,m,m"]
|===
|
|DelayValidationPropertyValue
|varchar(100)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis.packagetask.adoc#column-delayvalidationpropertyvalue[+ssis.PackageTask.DelayValidationPropertyValue+]
* xref:ssis.packagetask_src.adoc#column-delayvalidationpropertyvalue[+ssis.PackageTask_src.DelayValidationPropertyValue+]
--


[#column-executedpackagename]
=== ExecutedPackageName

[cols="d,8a,m,m,m"]
|===
|
|ExecutedPackageName
|varchar(1000)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis.packagetask.adoc#column-executedpackagename[+ssis.PackageTask.ExecutedPackageName+]
* xref:ssis.packagetask_src.adoc#column-executedpackagename[+ssis.PackageTask_src.ExecutedPackageName+]
--


[#column-executepackageconnection]
=== ExecutePackageConnection

[cols="d,8a,m,m,m"]
|===
|
|ExecutePackageConnection
|varchar(1000)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis.packagetask.adoc#column-executepackageconnection[+ssis.PackageTask.ExecutePackageConnection+]
* xref:ssis.packagetask_src.adoc#column-executepackageconnection[+ssis.PackageTask_src.ExecutePackageConnection+]
--


[#column-executepackageexpression]
=== ExecutePackageExpression

[cols="d,8a,m,m,m"]
|===
|
|ExecutePackageExpression
|varchar(1000)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis.packagetask.adoc#column-executepackageexpression[+ssis.PackageTask.ExecutePackageExpression+]
* xref:ssis.packagetask_src.adoc#column-executepackageexpression[+ssis.PackageTask_src.ExecutePackageExpression+]
--


[#column-expressionvalue]
=== ExpressionValue

[cols="d,8a,m,m,m"]
|===
|
|ExpressionValue
|varchar(5000)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis.packagetask.adoc#column-expressionvalue[+ssis.PackageTask.ExpressionValue+]
* xref:ssis.packagetask_src.adoc#column-expressionvalue[+ssis.PackageTask_src.ExpressionValue+]
--


[#column-isdisabled]
=== IsDisabled

[cols="d,8a,m,m,m"]
|===
|
|IsDisabled
|varchar(10)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis.packagetask.adoc#column-isdisabled[+ssis.PackageTask.IsDisabled+]
* xref:ssis.packagetask_src.adoc#column-isdisabled[+ssis.PackageTask_src.IsDisabled+]
--


[#column-script]
=== Script

[cols="d,8a,m,m,m"]
|===
|
|Script
|varchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis.packagetask.adoc#column-script[+ssis.PackageTask.Script+]
* xref:ssis.packagetask_src.adoc#column-script[+ssis.PackageTask_src.Script+]
--


[#column-sqlconnection]
=== SqlConnection

[cols="d,8a,m,m,m"]
|===
|
|SqlConnection
|uniqueidentifier
|NULL
|
|===

.Referenced Columns
--
* xref:ssis.packagetask.adoc#column-sqlconnection[+ssis.PackageTask.SqlConnection+]
* xref:ssis.packagetask_src.adoc#column-sqlconnection[+ssis.PackageTask_src.SqlConnection+]
--


[#column-sqlstatementsource]
=== SqlStatementSource

[cols="d,8a,m,m,m"]
|===
|
|SqlStatementSource
|nvarchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis.packagetask.adoc#column-sqlstatementsource[+ssis.PackageTask.SqlStatementSource+]
* xref:ssis.packagetask_src.adoc#column-sqlstatementsource[+ssis.PackageTask_src.SqlStatementSource+]
--


[#column-taskdescription]
=== TaskDescription

[cols="d,8a,m,m,m"]
|===
|
|TaskDescription
|varchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis.packagetask.adoc#column-taskdescription[+ssis.PackageTask.TaskDescription+]
* xref:ssis.packagetask_src.adoc#column-taskdescription[+ssis.PackageTask_src.TaskDescription+]
--


[#column-taskname]
=== TaskName

[cols="d,8a,m,m,m"]
|===
|
|TaskName
|varchar(2000)
|NOT NULL
|
|===

.Referenced Columns
--
* xref:ssis.packagetask.adoc#column-taskname[+ssis.PackageTask.TaskName+]
* xref:ssis.packagetask_src.adoc#column-taskname[+ssis.PackageTask_src.TaskName+]
--


[#column-tasktype]
=== TaskType

[cols="d,8a,m,m,m"]
|===
|
|TaskType
|varchar(5000)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis.packagetask.adoc#column-tasktype[+ssis.PackageTask.TaskType+]
* xref:ssis.packagetask_src.adoc#column-tasktype[+ssis.PackageTask_src.TaskType+]
--


// end::AntoraColumnDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]
|1
|*<<column-antoramodule>>*
|varchar(50)
|NOT NULL
|

|2
|*<<column-packagename>>*
|varchar(200)
|NOT NULL
|

|3
|*<<column-taskpath>>*
|varchar(8000)
|NOT NULL
|














// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]



|
|<<column-controlflowdetailsrowid>>
|int
|NOT NULL
|

|
|<<column-delayvalidationpropertyvalue>>
|varchar(100)
|NULL
|

|
|<<column-executedpackagename>>
|varchar(1000)
|NULL
|

|
|<<column-executepackageconnection>>
|varchar(1000)
|NULL
|

|
|<<column-executepackageexpression>>
|varchar(1000)
|NULL
|

|
|<<column-expressionvalue>>
|varchar(5000)
|NULL
|

|
|<<column-isdisabled>>
|varchar(10)
|NULL
|

|
|<<column-script>>
|varchar(max)
|NULL
|

|
|<<column-sqlconnection>>
|uniqueidentifier
|NULL
|

|
|<<column-sqlstatementsource>>
|nvarchar(max)
|NULL
|

|
|<<column-taskdescription>>
|varchar(max)
|NULL
|

|
|<<column-taskname>>
|varchar(2000)
|NOT NULL
|

|
|<<column-tasktype>>
|varchar(5000)
|NULL
|

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

[#index-pkunderlinepackagetaskunderlinetgt]
=== PK_PackageTask_tgt

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-AntoraModule>>; varchar(50)
* <<column-PackageName>>; varchar(200)
* <<column-TaskPath>>; varchar(8000)
--
* PK, Unique, Real: 1, 1, 0


[#index-idxunderlinepackagetaskunderlinetgtunderlineunderline2]
=== idx_PackageTask_tgt++__++2

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-ControlFlowDetailsRowID>>; int
--
* PK, Unique, Real: 0, 0, 0


[#index-idxunderlinepackagetaskunderlinetgtunderlineunderline3]
=== idx_PackageTask_tgt++__++3

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-AntoraModule>>; varchar(50)
* <<column-PackageName>>; varchar(200)
--
* PK, Unique, Real: 0, 0, 0


[#index-idxunderlinepackagetaskunderlinetgtunderlineunderline4]
=== idx_PackageTask_tgt++__++4

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-AntoraModule>>; varchar(50)
--
* PK, Unique, Real: 0, 0, 0

// end::AntoraIndexList[]

== AntoraMeasureDetails

// tag::AntoraMeasureDetails[]

// end::AntoraMeasureDetails[]

== AntoraMeasureDescriptions



== AntoraParameterList

// tag::AntoraParameterList[]

// end::AntoraParameterList[]

== AntoraXrefCulturesList

// tag::AntoraXrefCulturesList[]
* xref:dhw:sqldb:ssis.packagetask_tgt.adoc[] - 
// end::AntoraXrefCulturesList[]

== cultures_count

// tag::cultures_count[]
1
// end::cultures_count[]

== Other tags

source: property.RepoObjectProperty_cross As rop_cross


=== additional_reference_csv

// tag::additional_reference_csv[]

// end::additional_reference_csv[]


=== AdocUspSteps

// tag::adocuspsteps[]

// end::adocuspsteps[]


=== AntoraReferencedList

// tag::antorareferencedlist[]
* xref:dhw:sqldb:ssis.antoramodule_tgt_filter.adoc[]
* xref:dhw:sqldb:ssis.packagetask_src.adoc[]
// end::antorareferencedlist[]


=== AntoraReferencingList

// tag::antorareferencinglist[]
* xref:dhw:sqldb:ssis.packagetask.adoc[]
* xref:dhw:sqldb:ssis.usp_persist_packagetask_tgt.adoc[]
// end::antorareferencinglist[]


=== Description

// tag::description[]

// end::description[]


=== exampleUsage

// tag::exampleusage[]

// end::exampleusage[]


=== exampleUsage_2

// tag::exampleusage_2[]

// end::exampleusage_2[]


=== exampleUsage_3

// tag::exampleusage_3[]

// end::exampleusage_3[]


=== exampleUsage_4

// tag::exampleusage_4[]

// end::exampleusage_4[]


=== exampleUsage_5

// tag::exampleusage_5[]

// end::exampleusage_5[]


=== exampleWrong_Usage

// tag::examplewrong_usage[]

// end::examplewrong_usage[]


=== has_execution_plan_issue

// tag::has_execution_plan_issue[]

// end::has_execution_plan_issue[]


=== has_get_referenced_issue

// tag::has_get_referenced_issue[]

// end::has_get_referenced_issue[]


=== has_history

// tag::has_history[]
0
// end::has_history[]


=== has_history_columns

// tag::has_history_columns[]
0
// end::has_history_columns[]


=== InheritanceType

// tag::inheritancetype[]

// end::inheritancetype[]


=== is_persistence

// tag::is_persistence[]
1
// end::is_persistence[]


=== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]
0
// end::is_persistence_check_duplicate_per_pk[]


=== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]
0
// end::is_persistence_check_for_empty_source[]


=== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]
0
// end::is_persistence_delete_changed[]


=== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]
1
// end::is_persistence_delete_missing[]


=== is_persistence_insert

// tag::is_persistence_insert[]
1
// end::is_persistence_insert[]


=== is_persistence_truncate

// tag::is_persistence_truncate[]
0
// end::is_persistence_truncate[]


=== is_persistence_update_changed

// tag::is_persistence_update_changed[]
1
// end::is_persistence_update_changed[]


=== is_repo_managed

// tag::is_repo_managed[]
0
// end::is_repo_managed[]


=== is_ssas

// tag::is_ssas[]
0
// end::is_ssas[]


=== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


=== MS_Description

// tag::ms_description[]

// end::ms_description[]


=== persistence_source_RepoObject_fullname

// tag::persistence_source_repoobject_fullname[]
[ssis].[PackageTask_src]
// end::persistence_source_repoobject_fullname[]


=== persistence_source_RepoObject_fullname2

// tag::persistence_source_repoobject_fullname2[]
ssis.PackageTask_src
// end::persistence_source_repoobject_fullname2[]


=== persistence_source_RepoObject_guid

// tag::persistence_source_repoobject_guid[]
6C64FBE4-113B-EC11-852C-A81E8446D5B0
// end::persistence_source_repoobject_guid[]


=== persistence_source_RepoObject_xref

// tag::persistence_source_repoobject_xref[]
xref:ssis.packagetask_src.adoc[]
// end::persistence_source_repoobject_xref[]


=== pk_index_guid

// tag::pk_index_guid[]
9BE20570-1D3B-EC11-852C-A81E8446D5B0
// end::pk_index_guid[]


=== pk_IndexPatternColumnDatatype

// tag::pk_indexpatterncolumndatatype[]
varchar(50),varchar(200),varchar(8000)
// end::pk_indexpatterncolumndatatype[]


=== pk_IndexPatternColumnName

// tag::pk_indexpatterncolumnname[]
AntoraModule,PackageName,TaskPath
// end::pk_indexpatterncolumnname[]


=== pk_IndexSemanticGroup

// tag::pk_indexsemanticgroup[]

// end::pk_indexsemanticgroup[]


=== ReferencedObjectList

// tag::referencedobjectlist[]
* [ssis].[AntoraModule_tgt_filter]
* [ssis].[PackageTask]
* [ssis].[PackageTask_src]
// end::referencedobjectlist[]


=== usp_persistence_RepoObject_guid

// tag::usp_persistence_repoobject_guid[]
494AB625-2D3B-EC11-852C-A81E8446D5B0
// end::usp_persistence_repoobject_guid[]


=== UspExamples

// tag::uspexamples[]

// end::uspexamples[]


=== uspgenerator_usp_id

// tag::uspgenerator_usp_id[]

// end::uspgenerator_usp_id[]


=== UspParameters

// tag::uspparameters[]

// end::uspparameters[]

== Boolean Attributes

source: property.RepoObjectProperty WHERE property_int = 1

// tag::boolean_attributes[]

:is_persistence:
:is_persistence_delete_missing:
:is_persistence_insert:
:is_persistence_update_changed:

// end::boolean_attributes[]

== PlantUML diagrams

=== PlantUML Entity

// tag::puml_entity[]
[plantuml, entity-{docname}, svg, subs=macros]
....
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis.packagetask_tgt.adoc[]" as ssis.PackageTask_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  - **PackageName** : (varchar(200))
  - **TaskPath** : (varchar(8000))
  - ControlFlowDetailsRowID : (int)
  DelayValidationPropertyValue : (varchar(100))
  ExecutedPackageName : (varchar(1000))
  ExecutePackageConnection : (varchar(1000))
  ExecutePackageExpression : (varchar(1000))
  ExpressionValue : (varchar(5000))
  IsDisabled : (varchar(10))
  Script : (varchar(max))
  SqlConnection : (uniqueidentifier)
  SqlStatementSource : (nvarchar(max))
  TaskDescription : (varchar(max))
  - TaskName : (varchar(2000))
  TaskType : (varchar(5000))
  --
}
....

// end::puml_entity[]

=== PlantUML Entity 1 1 FK

// tag::puml_entity_1_1_fk[]
[plantuml, entity_1_1_fk-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis.packagetask_tgt.adoc[]" as ssis.PackageTask_tgt << V >> {
- **PK_PackageTask_tgt**

..
AntoraModule; varchar(50)
PackageName; varchar(200)
TaskPath; varchar(8000)
--
- idx_PackageTask_tgt__2

..
ControlFlowDetailsRowID; int
--
- idx_PackageTask_tgt__3

..
AntoraModule; varchar(50)
PackageName; varchar(200)
--
- idx_PackageTask_tgt__4

..
AntoraModule; varchar(50)
}



footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_fk[]

=== PlantUML 1 1 ObjectRef

// tag::puml_entity_1_1_objectref[]
[plantuml, entity_1_1_objectref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis.antoramodule_tgt_filter.adoc[]" as ssis.AntoraModule_tgt_filter << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask.adoc[]" as ssis.PackageTask << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_src.adoc[]" as ssis.PackageTask_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **TaskPath** : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_tgt.adoc[]" as ssis.PackageTask_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  - **PackageName** : (varchar(200))
  - **TaskPath** : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packagetask_tgt.adoc[]" as ssis.usp_PERSIST_PackageTask_tgt << P >> {
  --
}

ssis.AntoraModule_tgt_filter <.. ssis.PackageTask_tgt
ssis.PackageTask_src <.. ssis.PackageTask_tgt
ssis.PackageTask_tgt <.. ssis.PackageTask
ssis.PackageTask_tgt <.. ssis.usp_PERSIST_PackageTask_tgt

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_objectref[]

=== PlantUML 30 0 ObjectRef

// tag::puml_entity_30_0_objectref[]
[plantuml, entity_30_0_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis.antoramodule_tgt_filter.adoc[]" as ssis.AntoraModule_tgt_filter << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.package_src.adoc[]" as ssis.Package_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_src.adoc[]" as ssis.PackageTask_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **TaskPath** : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_tgt.adoc[]" as ssis.PackageTask_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  - **PackageName** : (varchar(200))
  - **TaskPath** : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:ssis.project.adoc[]" as ssis.Project << U >> {
  - **AntoraModule** : (varchar(50))
  --
}

entity "puml-link:dhw:sqldb:ssis_t.pkgstats.adoc[]" as ssis_t.pkgStats << U >> {
  - **RowID** : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tblcontrolflow.adoc[]" as ssis_t.TblControlFlow << U >> {
  - **ControlFlowDetailsRowID** : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_executepackage.adoc[]" as ssis_t.TblTask_ExecutePackage << U >> {
  - **ControlFlowDetailsRowID** : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_script.adoc[]" as ssis_t.TblTask_Script << U >> {
  - **ControlFlowDetailsRowID** : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_sql.adoc[]" as ssis_t.TblTask_Sql << U >> {
  - **ControlFlowDetailsRowID** : (int)
  --
}

ssis.AntoraModule_tgt_filter <.. ssis.PackageTask_tgt
ssis.Package_src <.. ssis.PackageTask_src
ssis.Package_src <.. ssis.AntoraModule_tgt_filter
ssis.PackageTask_src <.. ssis.PackageTask_tgt
ssis.Project <.. ssis.Package_src
ssis_t.pkgStats <.. ssis.Package_src
ssis_t.TblControlFlow <.. ssis.PackageTask_src
ssis_t.TblTask_ExecutePackage <.. ssis.PackageTask_src
ssis_t.TblTask_Script <.. ssis.PackageTask_src
ssis_t.TblTask_Sql <.. ssis.PackageTask_src

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_30_0_objectref[]

=== PlantUML 0 30 ObjectRef

// tag::puml_entity_0_30_objectref[]
[plantuml, entity_0_30_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:docs.ssis_adoc.adoc[]" as docs.ssis_Adoc << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageBasename** : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_adoc_t.adoc[]" as docs.ssis_Adoc_T << U >> {
  - **AntoraModule** : (varchar(50))
  - **PackageBasename** : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_pumlpackage.adoc[]" as docs.ssis_PumlPackage << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_pumlpartialtaskcomponent.adoc[]" as docs.ssis_PumlPartialTaskComponent << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_task.adoc[]" as docs.ssis_Task << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_tasklist.adoc[]" as docs.ssis_TaskList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport.adoc[]" as docs.usp_AntoraExport << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_ssispartialscontent.adoc[]" as docs.usp_AntoraExport_SsisPartialsContent << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_ssis_adoc_t.adoc[]" as docs.usp_PERSIST_ssis_Adoc_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask.adoc[]" as ssis.PackageTask << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_levellaglead.adoc[]" as ssis.PackageTask_LevelLagLead << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_tgt.adoc[]" as ssis.PackageTask_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  - **PackageName** : (varchar(200))
  - **TaskPath** : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_import.adoc[]" as ssis.usp_import << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packagetask_tgt.adoc[]" as ssis.usp_PERSIST_PackageTask_tgt << P >> {
  --
}

docs.ssis_Adoc <.. docs.ssis_Adoc_T
docs.ssis_Adoc <.. docs.usp_PERSIST_ssis_Adoc_T
docs.ssis_Adoc_T <.. docs.usp_PERSIST_ssis_Adoc_T
docs.ssis_Adoc_T <.. docs.usp_AntoraExport_SsisPartialsContent
docs.ssis_PumlPackage <.. docs.ssis_Adoc
docs.ssis_PumlPartialTaskComponent <.. docs.ssis_PumlPackage
docs.ssis_TaskList <.. docs.ssis_Adoc
docs.usp_AntoraExport_SsisPartialsContent <.. docs.usp_AntoraExport
docs.usp_PERSIST_ssis_Adoc_T <.. docs.usp_AntoraExport_SsisPartialsContent
ssis.PackageTask <.. docs.ssis_TaskList
ssis.PackageTask <.. ssis.PackageTask_LevelLagLead
ssis.PackageTask <.. docs.ssis_Task
ssis.PackageTask_LevelLagLead <.. docs.ssis_PumlPartialTaskComponent
ssis.PackageTask_tgt <.. ssis.usp_PERSIST_PackageTask_tgt
ssis.PackageTask_tgt <.. ssis.PackageTask
ssis.usp_PERSIST_PackageTask_tgt <.. ssis.usp_import

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_0_30_objectref[]

=== PlantUML 1 1 ColumnRef

// tag::puml_entity_1_1_colref[]
[plantuml, entity_1_1_colref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis.antoramodule_tgt_filter.adoc[]" as ssis.AntoraModule_tgt_filter << V >> {
  - AntoraModule : (varchar(50))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask.adoc[]" as ssis.PackageTask << U >> {
  - AntoraModule : (varchar(50))
  - ControlFlowDetailsRowID : (int)
  DelayValidationPropertyValue : (varchar(100))
  ExecutedPackageName : (varchar(1000))
  ExecutePackageConnection : (varchar(1000))
  ExecutePackageExpression : (varchar(1000))
  ExpressionValue : (varchar(5000))
  IsDisabled : (varchar(10))
  - PackageName : (varchar(200))
  Script : (varchar(max))
  SqlConnection : (uniqueidentifier)
  SqlStatementSource : (nvarchar(max))
  TaskDescription : (varchar(max))
  - TaskName : (varchar(2000))
  - TaskPath : (varchar(8000))
  TaskType : (varchar(5000))
  # PackageBasename : (varchar(8000))
  # TaskPathLevel : (int)
  # TaskPathParent : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_src.adoc[]" as ssis.PackageTask_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **TaskPath** : (varchar(8000))
  - ControlFlowDetailsRowID : (int)
  DelayValidationPropertyValue : (varchar(100))
  ExecutedPackageName : (varchar(1000))
  ExecutePackageConnection : (varchar(1000))
  ExecutePackageExpression : (varchar(1000))
  ExpressionValue : (varchar(5000))
  IsDisabled : (varchar(10))
  Script : (varchar(max))
  SqlConnection : (uniqueidentifier)
  SqlStatementSource : (nvarchar(max))
  TaskDescription : (varchar(max))
  TaskName : (varchar(2000))
  TaskType : (varchar(5000))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_tgt.adoc[]" as ssis.PackageTask_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  - **PackageName** : (varchar(200))
  - **TaskPath** : (varchar(8000))
  - ControlFlowDetailsRowID : (int)
  DelayValidationPropertyValue : (varchar(100))
  ExecutedPackageName : (varchar(1000))
  ExecutePackageConnection : (varchar(1000))
  ExecutePackageExpression : (varchar(1000))
  ExpressionValue : (varchar(5000))
  IsDisabled : (varchar(10))
  Script : (varchar(max))
  SqlConnection : (uniqueidentifier)
  SqlStatementSource : (nvarchar(max))
  TaskDescription : (varchar(max))
  - TaskName : (varchar(2000))
  TaskType : (varchar(5000))
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packagetask_tgt.adoc[]" as ssis.usp_PERSIST_PackageTask_tgt << P >> {
  --
}

ssis.AntoraModule_tgt_filter <.. ssis.PackageTask_tgt
ssis.PackageTask_src <.. ssis.PackageTask_tgt
ssis.PackageTask_tgt <.. ssis.PackageTask
ssis.PackageTask_tgt <.. ssis.usp_PERSIST_PackageTask_tgt
"ssis.PackageTask::AntoraModule" <-- "ssis.PackageTask_tgt::AntoraModule"
"ssis.PackageTask::ControlFlowDetailsRowID" <-- "ssis.PackageTask_tgt::ControlFlowDetailsRowID"
"ssis.PackageTask::DelayValidationPropertyValue" <-- "ssis.PackageTask_tgt::DelayValidationPropertyValue"
"ssis.PackageTask::ExecutedPackageName" <-- "ssis.PackageTask_tgt::ExecutedPackageName"
"ssis.PackageTask::ExecutePackageConnection" <-- "ssis.PackageTask_tgt::ExecutePackageConnection"
"ssis.PackageTask::ExecutePackageExpression" <-- "ssis.PackageTask_tgt::ExecutePackageExpression"
"ssis.PackageTask::ExpressionValue" <-- "ssis.PackageTask_tgt::ExpressionValue"
"ssis.PackageTask::IsDisabled" <-- "ssis.PackageTask_tgt::IsDisabled"
"ssis.PackageTask::PackageName" <-- "ssis.PackageTask_tgt::PackageName"
"ssis.PackageTask::Script" <-- "ssis.PackageTask_tgt::Script"
"ssis.PackageTask::SqlConnection" <-- "ssis.PackageTask_tgt::SqlConnection"
"ssis.PackageTask::SqlStatementSource" <-- "ssis.PackageTask_tgt::SqlStatementSource"
"ssis.PackageTask::TaskDescription" <-- "ssis.PackageTask_tgt::TaskDescription"
"ssis.PackageTask::TaskName" <-- "ssis.PackageTask_tgt::TaskName"
"ssis.PackageTask::TaskPath" <-- "ssis.PackageTask_tgt::TaskPath"
"ssis.PackageTask::TaskType" <-- "ssis.PackageTask_tgt::TaskType"
"ssis.PackageTask_src::AntoraModule" <-- "ssis.PackageTask_tgt::AntoraModule"
"ssis.PackageTask_src::ControlFlowDetailsRowID" <-- "ssis.PackageTask_tgt::ControlFlowDetailsRowID"
"ssis.PackageTask_src::DelayValidationPropertyValue" <-- "ssis.PackageTask_tgt::DelayValidationPropertyValue"
"ssis.PackageTask_src::ExecutedPackageName" <-- "ssis.PackageTask_tgt::ExecutedPackageName"
"ssis.PackageTask_src::ExecutePackageConnection" <-- "ssis.PackageTask_tgt::ExecutePackageConnection"
"ssis.PackageTask_src::ExecutePackageExpression" <-- "ssis.PackageTask_tgt::ExecutePackageExpression"
"ssis.PackageTask_src::ExpressionValue" <-- "ssis.PackageTask_tgt::ExpressionValue"
"ssis.PackageTask_src::IsDisabled" <-- "ssis.PackageTask_tgt::IsDisabled"
"ssis.PackageTask_src::PackageName" <-- "ssis.PackageTask_tgt::PackageName"
"ssis.PackageTask_src::Script" <-- "ssis.PackageTask_tgt::Script"
"ssis.PackageTask_src::SqlConnection" <-- "ssis.PackageTask_tgt::SqlConnection"
"ssis.PackageTask_src::SqlStatementSource" <-- "ssis.PackageTask_tgt::SqlStatementSource"
"ssis.PackageTask_src::TaskDescription" <-- "ssis.PackageTask_tgt::TaskDescription"
"ssis.PackageTask_src::TaskName" <-- "ssis.PackageTask_tgt::TaskName"
"ssis.PackageTask_src::TaskPath" <-- "ssis.PackageTask_tgt::TaskPath"
"ssis.PackageTask_src::TaskType" <-- "ssis.PackageTask_tgt::TaskType"

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_colref[]


== sql_modules_definition

// tag::sql_modules_definition[]
[%collapsible]
=======
[source,sql,numbered,indent=0]
----

CREATE VIEW [ssis].[PackageTask_tgt]
As
Select
    tgt.AntoraModule
  , tgt.PackageName
  , tgt.TaskPath
  , tgt.TaskName
  , tgt.ControlFlowDetailsRowID
  , tgt.TaskDescription
  , tgt.TaskType
  , tgt.IsDisabled
  , tgt.DelayValidationPropertyValue
  --, tgt.DFTQuery
  --, tgt.SqlTaskQry
  --, tgt.ExecPkgTaskQry
  --, tgt.ScriptTaskQry
  , tgt.ExpressionValue
  , tgt.Script
  , tgt.SqlConnection
  , tgt.SqlStatementSource
  , tgt.ExecutePackageExpression
  , tgt.ExecutedPackageName
  , tgt.ExecutePackageConnection
From
    ssis.PackageTask As tgt
Where
    Exists
(
    Select
        1
    From
        ssis.AntoraModule_tgt_filter As f
    Where
        tgt.AntoraModule = f.AntoraModule
)
----
=======
// end::sql_modules_definition[]


