// tag::HeaderFullDisplayName[]
= ssis.PackageTask_src - V
// end::HeaderFullDisplayName[]

== existing_properties

// tag::existing_properties[]

:ExistsProperty--antorareferencedlist:
:ExistsProperty--antorareferencinglist:
:ExistsProperty--is_repo_managed:
:ExistsProperty--is_ssas:
:ExistsProperty--pk_index_guid:
:ExistsProperty--pk_indexpatterncolumndatatype:
:ExistsProperty--pk_indexpatterncolumnname:
:ExistsProperty--referencedobjectlist:
:ExistsProperty--sql_modules_definition:
:ExistsProperty--FK:
:ExistsProperty--AntoraIndexList:
:ExistsProperty--Columns:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
6C64FBE4-113B-EC11-852C-A81E8446D5B0
// end::RepoObject_guid[]

== RepoObject_FullDisplayName2

// tag::RepoObject_FullDisplayName2[]
ssis.PackageTask_src
// end::RepoObject_FullDisplayName2[]

== SysObject_type

// tag::SysObject_type[]
V 
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
view
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
194151787
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2021-11-01 15:36:00
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]
[discrete]
== _


[#column-antoramodule]
=== AntoraModule

[cols="d,8a,m,m,m"]
|===
|1
|*AntoraModule*
|varchar(50)
|NOT NULL
|
|===

.Referenced Columns
--
* xref:ssis.package_src.adoc#column-antoramodule[+ssis.Package_src.AntoraModule+]
--

.Referencing Columns
--
* xref:ssis.packagetask_tgt.adoc#column-antoramodule[+ssis.PackageTask_tgt.AntoraModule+]
--


[#column-packagename]
=== PackageName

[cols="d,8a,m,m,m"]
|===
|2
|*PackageName*
|varchar(200)
|NULL
|
|===

.Description
--
(left(replace([PackagePath],[ProjectPath]+'\',''),(200)))
--
{empty} +

.Referenced Columns
--
* xref:ssis.package_src.adoc#column-packagename[+ssis.Package_src.PackageName+]
--

.Referencing Columns
--
* xref:ssis.packagetask_tgt.adoc#column-packagename[+ssis.PackageTask_tgt.PackageName+]
--


[#column-taskpath]
=== TaskPath

[cols="d,8a,m,m,m"]
|===
|3
|*TaskPath*
|varchar(8000)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis_t.tblcontrolflow.adoc#column-taskpath[+ssis_t.TblControlFlow.TaskPath+]
--

.Referencing Columns
--
* xref:ssis.packagetask_tgt.adoc#column-taskpath[+ssis.PackageTask_tgt.TaskPath+]
--


[#column-controlflowdetailsrowid]
=== ControlFlowDetailsRowID

[cols="d,8a,m,m,m"]
|===
|
|ControlFlowDetailsRowID
|int
|NOT NULL
|
|===

.Referenced Columns
--
* xref:ssis_t.tblcontrolflow.adoc#column-controlflowdetailsrowid[+ssis_t.TblControlFlow.ControlFlowDetailsRowID+]
--

.Referencing Columns
--
* xref:ssis.packagetask_tgt.adoc#column-controlflowdetailsrowid[+ssis.PackageTask_tgt.ControlFlowDetailsRowID+]
--


[#column-delayvalidationpropertyvalue]
=== DelayValidationPropertyValue

[cols="d,8a,m,m,m"]
|===
|
|DelayValidationPropertyValue
|varchar(100)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis_t.tblcontrolflow.adoc#column-delayvalidationpropertyvalue[+ssis_t.TblControlFlow.DelayValidationPropertyValue+]
--

.Referencing Columns
--
* xref:ssis.packagetask_tgt.adoc#column-delayvalidationpropertyvalue[+ssis.PackageTask_tgt.DelayValidationPropertyValue+]
--


[#column-executedpackagename]
=== ExecutedPackageName

[cols="d,8a,m,m,m"]
|===
|
|ExecutedPackageName
|varchar(1000)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis_t.tbltask_executepackage.adoc#column-executedpackagename[+ssis_t.TblTask_ExecutePackage.ExecutedPackageName+]
--

.Referencing Columns
--
* xref:ssis.packagetask_tgt.adoc#column-executedpackagename[+ssis.PackageTask_tgt.ExecutedPackageName+]
--


[#column-executepackageconnection]
=== ExecutePackageConnection

[cols="d,8a,m,m,m"]
|===
|
|ExecutePackageConnection
|varchar(1000)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis_t.tbltask_executepackage.adoc#column-executepackageconnection[+ssis_t.TblTask_ExecutePackage.ExecutePackageConnection+]
--

.Referencing Columns
--
* xref:ssis.packagetask_tgt.adoc#column-executepackageconnection[+ssis.PackageTask_tgt.ExecutePackageConnection+]
--


[#column-executepackageexpression]
=== ExecutePackageExpression

[cols="d,8a,m,m,m"]
|===
|
|ExecutePackageExpression
|varchar(1000)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis_t.tbltask_executepackage.adoc#column-executepackageexpression[+ssis_t.TblTask_ExecutePackage.ExecutePackageExpression+]
--

.Referencing Columns
--
* xref:ssis.packagetask_tgt.adoc#column-executepackageexpression[+ssis.PackageTask_tgt.ExecutePackageExpression+]
--


[#column-expressionvalue]
=== ExpressionValue

[cols="d,8a,m,m,m"]
|===
|
|ExpressionValue
|varchar(5000)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis_t.tblcontrolflow.adoc#column-expressionvalue[+ssis_t.TblControlFlow.ExpressionValue+]
--

.Referencing Columns
--
* xref:ssis.packagetask_tgt.adoc#column-expressionvalue[+ssis.PackageTask_tgt.ExpressionValue+]
--


[#column-isdisabled]
=== IsDisabled

[cols="d,8a,m,m,m"]
|===
|
|IsDisabled
|varchar(10)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis_t.tblcontrolflow.adoc#column-isdisabled[+ssis_t.TblControlFlow.IsDisabled+]
--

.Referencing Columns
--
* xref:ssis.packagetask_tgt.adoc#column-isdisabled[+ssis.PackageTask_tgt.IsDisabled+]
--


[#column-script]
=== Script

[cols="d,8a,m,m,m"]
|===
|
|Script
|varchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis_t.tbltask_script.adoc#column-script[+ssis_t.TblTask_Script.Script+]
--

.Referencing Columns
--
* xref:ssis.packagetask_tgt.adoc#column-script[+ssis.PackageTask_tgt.Script+]
--


[#column-sqlconnection]
=== SqlConnection

[cols="d,8a,m,m,m"]
|===
|
|SqlConnection
|uniqueidentifier
|NULL
|
|===

.Referenced Columns
--
* xref:ssis_t.tbltask_sql.adoc#column-sqlconnection[+ssis_t.TblTask_Sql.SqlConnection+]
--

.Referencing Columns
--
* xref:ssis.packagetask_tgt.adoc#column-sqlconnection[+ssis.PackageTask_tgt.SqlConnection+]
--


[#column-sqlstatementsource]
=== SqlStatementSource

[cols="d,8a,m,m,m"]
|===
|
|SqlStatementSource
|nvarchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis_t.tbltask_sql.adoc#column-sqlstatementsource[+ssis_t.TblTask_Sql.SqlStatementSource+]
--

.Referencing Columns
--
* xref:ssis.packagetask_tgt.adoc#column-sqlstatementsource[+ssis.PackageTask_tgt.SqlStatementSource+]
--


[#column-taskdescription]
=== TaskDescription

[cols="d,8a,m,m,m"]
|===
|
|TaskDescription
|varchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis_t.tblcontrolflow.adoc#column-taskdescription[+ssis_t.TblControlFlow.TaskDescription+]
--

.Referencing Columns
--
* xref:ssis.packagetask_tgt.adoc#column-taskdescription[+ssis.PackageTask_tgt.TaskDescription+]
--


[#column-taskname]
=== TaskName

[cols="d,8a,m,m,m"]
|===
|
|TaskName
|varchar(2000)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis_t.tblcontrolflow.adoc#column-taskname[+ssis_t.TblControlFlow.TaskName+]
--

.Referencing Columns
--
* xref:ssis.packagetask_tgt.adoc#column-taskname[+ssis.PackageTask_tgt.TaskName+]
--


[#column-tasktype]
=== TaskType

[cols="d,8a,m,m,m"]
|===
|
|TaskType
|varchar(5000)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis_t.tblcontrolflow.adoc#column-tasktype[+ssis_t.TblControlFlow.TaskType+]
--

.Referencing Columns
--
* xref:ssis.packagetask_tgt.adoc#column-tasktype[+ssis.PackageTask_tgt.TaskType+]
--


// end::AntoraColumnDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]
|1
|*<<column-antoramodule>>*
|varchar(50)
|NOT NULL
|

|2
|*<<column-packagename>>*
|varchar(200)
|NULL
|

|3
|*<<column-taskpath>>*
|varchar(8000)
|NULL
|














// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]



|
|<<column-controlflowdetailsrowid>>
|int
|NOT NULL
|

|
|<<column-delayvalidationpropertyvalue>>
|varchar(100)
|NULL
|

|
|<<column-executedpackagename>>
|varchar(1000)
|NULL
|

|
|<<column-executepackageconnection>>
|varchar(1000)
|NULL
|

|
|<<column-executepackageexpression>>
|varchar(1000)
|NULL
|

|
|<<column-expressionvalue>>
|varchar(5000)
|NULL
|

|
|<<column-isdisabled>>
|varchar(10)
|NULL
|

|
|<<column-script>>
|varchar(max)
|NULL
|

|
|<<column-sqlconnection>>
|uniqueidentifier
|NULL
|

|
|<<column-sqlstatementsource>>
|nvarchar(max)
|NULL
|

|
|<<column-taskdescription>>
|varchar(max)
|NULL
|

|
|<<column-taskname>>
|varchar(2000)
|NULL
|

|
|<<column-tasktype>>
|varchar(5000)
|NULL
|

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

[#index-pkunderlinepackagetaskunderlinesrc]
=== PK_PackageTask_src

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-AntoraModule>>; varchar(50)
* <<column-PackageName>>; varchar(200)
* <<column-TaskPath>>; varchar(8000)
--
* PK, Unique, Real: 1, 1, 0


[#index-idxunderlinepackagetaskunderlinesrcunderlineunderline2]
=== idx_PackageTask_src++__++2

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-ControlFlowDetailsRowID>>; int
--
* PK, Unique, Real: 0, 0, 0


[#index-idxunderlinepackagetaskunderlinesrcunderlineunderline3]
=== idx_PackageTask_src++__++3

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-AntoraModule>>; varchar(50)
* <<column-PackageName>>; varchar(200)
--
* PK, Unique, Real: 0, 0, 0


[#index-idxunderlinepackagetaskunderlinesrcunderlineunderline4]
=== idx_PackageTask_src++__++4

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-AntoraModule>>; varchar(50)
--
* PK, Unique, Real: 0, 0, 0

// end::AntoraIndexList[]

== AntoraMeasureDetails

// tag::AntoraMeasureDetails[]

// end::AntoraMeasureDetails[]

== AntoraMeasureDescriptions



== AntoraParameterList

// tag::AntoraParameterList[]

// end::AntoraParameterList[]

== AntoraXrefCulturesList

// tag::AntoraXrefCulturesList[]
* xref:dhw:sqldb:ssis.packagetask_src.adoc[] - 
// end::AntoraXrefCulturesList[]

== cultures_count

// tag::cultures_count[]
1
// end::cultures_count[]

== Other tags

source: property.RepoObjectProperty_cross As rop_cross


=== additional_reference_csv

// tag::additional_reference_csv[]

// end::additional_reference_csv[]


=== AdocUspSteps

// tag::adocuspsteps[]

// end::adocuspsteps[]


=== AntoraReferencedList

// tag::antorareferencedlist[]
* xref:dhw:sqldb:ssis.package_src.adoc[]
* xref:dhw:sqldb:ssis_t.tblcontrolflow.adoc[]
* xref:dhw:sqldb:ssis_t.tbltask_executepackage.adoc[]
* xref:dhw:sqldb:ssis_t.tbltask_script.adoc[]
* xref:dhw:sqldb:ssis_t.tbltask_sql.adoc[]
// end::antorareferencedlist[]


=== AntoraReferencingList

// tag::antorareferencinglist[]
* xref:dhw:sqldb:ssis.packagetask_tgt.adoc[]
* xref:dhw:sqldb:ssis.usp_persist_packagetask_tgt.adoc[]
// end::antorareferencinglist[]


=== Description

// tag::description[]

// end::description[]


=== exampleUsage

// tag::exampleusage[]

// end::exampleusage[]


=== exampleUsage_2

// tag::exampleusage_2[]

// end::exampleusage_2[]


=== exampleUsage_3

// tag::exampleusage_3[]

// end::exampleusage_3[]


=== exampleUsage_4

// tag::exampleusage_4[]

// end::exampleusage_4[]


=== exampleUsage_5

// tag::exampleusage_5[]

// end::exampleusage_5[]


=== exampleWrong_Usage

// tag::examplewrong_usage[]

// end::examplewrong_usage[]


=== has_execution_plan_issue

// tag::has_execution_plan_issue[]

// end::has_execution_plan_issue[]


=== has_get_referenced_issue

// tag::has_get_referenced_issue[]

// end::has_get_referenced_issue[]


=== has_history

// tag::has_history[]

// end::has_history[]


=== has_history_columns

// tag::has_history_columns[]

// end::has_history_columns[]


=== InheritanceType

// tag::inheritancetype[]

// end::inheritancetype[]


=== is_persistence

// tag::is_persistence[]

// end::is_persistence[]


=== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]

// end::is_persistence_check_duplicate_per_pk[]


=== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]

// end::is_persistence_check_for_empty_source[]


=== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]

// end::is_persistence_delete_changed[]


=== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]

// end::is_persistence_delete_missing[]


=== is_persistence_insert

// tag::is_persistence_insert[]

// end::is_persistence_insert[]


=== is_persistence_truncate

// tag::is_persistence_truncate[]

// end::is_persistence_truncate[]


=== is_persistence_update_changed

// tag::is_persistence_update_changed[]

// end::is_persistence_update_changed[]


=== is_repo_managed

// tag::is_repo_managed[]
0
// end::is_repo_managed[]


=== is_ssas

// tag::is_ssas[]
0
// end::is_ssas[]


=== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


=== MS_Description

// tag::ms_description[]

// end::ms_description[]


=== persistence_source_RepoObject_fullname

// tag::persistence_source_repoobject_fullname[]

// end::persistence_source_repoobject_fullname[]


=== persistence_source_RepoObject_fullname2

// tag::persistence_source_repoobject_fullname2[]

// end::persistence_source_repoobject_fullname2[]


=== persistence_source_RepoObject_guid

// tag::persistence_source_repoobject_guid[]

// end::persistence_source_repoobject_guid[]


=== persistence_source_RepoObject_xref

// tag::persistence_source_repoobject_xref[]

// end::persistence_source_repoobject_xref[]


=== pk_index_guid

// tag::pk_index_guid[]
F601BE14-1C3B-EC11-852C-A81E8446D5B0
// end::pk_index_guid[]


=== pk_IndexPatternColumnDatatype

// tag::pk_indexpatterncolumndatatype[]
varchar(50),varchar(200),varchar(8000)
// end::pk_indexpatterncolumndatatype[]


=== pk_IndexPatternColumnName

// tag::pk_indexpatterncolumnname[]
AntoraModule,PackageName,TaskPath
// end::pk_indexpatterncolumnname[]


=== pk_IndexSemanticGroup

// tag::pk_indexsemanticgroup[]

// end::pk_indexsemanticgroup[]


=== ReferencedObjectList

// tag::referencedobjectlist[]
* [ssis].[Package_src]
* [ssis_t].[TblControlFlow]
* [ssis_t].[TblTask_ExecutePackage]
* [ssis_t].[TblTask_Script]
* [ssis_t].[TblTask_Sql]
// end::referencedobjectlist[]


=== usp_persistence_RepoObject_guid

// tag::usp_persistence_repoobject_guid[]

// end::usp_persistence_repoobject_guid[]


=== UspExamples

// tag::uspexamples[]

// end::uspexamples[]


=== uspgenerator_usp_id

// tag::uspgenerator_usp_id[]

// end::uspgenerator_usp_id[]


=== UspParameters

// tag::uspparameters[]

// end::uspparameters[]

== Boolean Attributes

source: property.RepoObjectProperty WHERE property_int = 1

// tag::boolean_attributes[]


// end::boolean_attributes[]

== PlantUML diagrams

=== PlantUML Entity

// tag::puml_entity[]
[plantuml, entity-{docname}, svg, subs=macros]
....
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis.packagetask_src.adoc[]" as ssis.PackageTask_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **TaskPath** : (varchar(8000))
  - ControlFlowDetailsRowID : (int)
  DelayValidationPropertyValue : (varchar(100))
  ExecutedPackageName : (varchar(1000))
  ExecutePackageConnection : (varchar(1000))
  ExecutePackageExpression : (varchar(1000))
  ExpressionValue : (varchar(5000))
  IsDisabled : (varchar(10))
  Script : (varchar(max))
  SqlConnection : (uniqueidentifier)
  SqlStatementSource : (nvarchar(max))
  TaskDescription : (varchar(max))
  TaskName : (varchar(2000))
  TaskType : (varchar(5000))
  --
}
....

// end::puml_entity[]

=== PlantUML Entity 1 1 FK

// tag::puml_entity_1_1_fk[]
[plantuml, entity_1_1_fk-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis.packagetask_src.adoc[]" as ssis.PackageTask_src << V >> {
- **PK_PackageTask_src**

..
AntoraModule; varchar(50)
PackageName; varchar(200)
TaskPath; varchar(8000)
--
- idx_PackageTask_src__2

..
ControlFlowDetailsRowID; int
--
- idx_PackageTask_src__3

..
AntoraModule; varchar(50)
PackageName; varchar(200)
--
- idx_PackageTask_src__4

..
AntoraModule; varchar(50)
}



footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_fk[]

=== PlantUML 1 1 ObjectRef

// tag::puml_entity_1_1_objectref[]
[plantuml, entity_1_1_objectref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis.package_src.adoc[]" as ssis.Package_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_src.adoc[]" as ssis.PackageTask_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **TaskPath** : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_tgt.adoc[]" as ssis.PackageTask_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  - **PackageName** : (varchar(200))
  - **TaskPath** : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packagetask_tgt.adoc[]" as ssis.usp_PERSIST_PackageTask_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tblcontrolflow.adoc[]" as ssis_t.TblControlFlow << U >> {
  - **ControlFlowDetailsRowID** : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_executepackage.adoc[]" as ssis_t.TblTask_ExecutePackage << U >> {
  - **ControlFlowDetailsRowID** : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_script.adoc[]" as ssis_t.TblTask_Script << U >> {
  - **ControlFlowDetailsRowID** : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_sql.adoc[]" as ssis_t.TblTask_Sql << U >> {
  - **ControlFlowDetailsRowID** : (int)
  --
}

ssis.Package_src <.. ssis.PackageTask_src
ssis.PackageTask_src <.. ssis.PackageTask_tgt
ssis.PackageTask_src <.. ssis.usp_PERSIST_PackageTask_tgt
ssis_t.TblControlFlow <.. ssis.PackageTask_src
ssis_t.TblTask_ExecutePackage <.. ssis.PackageTask_src
ssis_t.TblTask_Script <.. ssis.PackageTask_src
ssis_t.TblTask_Sql <.. ssis.PackageTask_src

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_objectref[]

=== PlantUML 30 0 ObjectRef

// tag::puml_entity_30_0_objectref[]
[plantuml, entity_30_0_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis.package_src.adoc[]" as ssis.Package_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_src.adoc[]" as ssis.PackageTask_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **TaskPath** : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:ssis.project.adoc[]" as ssis.Project << U >> {
  - **AntoraModule** : (varchar(50))
  --
}

entity "puml-link:dhw:sqldb:ssis_t.pkgstats.adoc[]" as ssis_t.pkgStats << U >> {
  - **RowID** : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tblcontrolflow.adoc[]" as ssis_t.TblControlFlow << U >> {
  - **ControlFlowDetailsRowID** : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_executepackage.adoc[]" as ssis_t.TblTask_ExecutePackage << U >> {
  - **ControlFlowDetailsRowID** : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_script.adoc[]" as ssis_t.TblTask_Script << U >> {
  - **ControlFlowDetailsRowID** : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_sql.adoc[]" as ssis_t.TblTask_Sql << U >> {
  - **ControlFlowDetailsRowID** : (int)
  --
}

ssis.Package_src <.. ssis.PackageTask_src
ssis.Project <.. ssis.Package_src
ssis_t.pkgStats <.. ssis.Package_src
ssis_t.TblControlFlow <.. ssis.PackageTask_src
ssis_t.TblTask_ExecutePackage <.. ssis.PackageTask_src
ssis_t.TblTask_Script <.. ssis.PackageTask_src
ssis_t.TblTask_Sql <.. ssis.PackageTask_src

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_30_0_objectref[]

=== PlantUML 0 30 ObjectRef

// tag::puml_entity_0_30_objectref[]
[plantuml, entity_0_30_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:docs.ssis_adoc.adoc[]" as docs.ssis_Adoc << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageBasename** : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_adoc_t.adoc[]" as docs.ssis_Adoc_T << U >> {
  - **AntoraModule** : (varchar(50))
  - **PackageBasename** : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_pumlpackage.adoc[]" as docs.ssis_PumlPackage << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_pumlpartialtaskcomponent.adoc[]" as docs.ssis_PumlPartialTaskComponent << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_task.adoc[]" as docs.ssis_Task << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_tasklist.adoc[]" as docs.ssis_TaskList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport.adoc[]" as docs.usp_AntoraExport << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_ssispartialscontent.adoc[]" as docs.usp_AntoraExport_SsisPartialsContent << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_ssis_adoc_t.adoc[]" as docs.usp_PERSIST_ssis_Adoc_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask.adoc[]" as ssis.PackageTask << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_levellaglead.adoc[]" as ssis.PackageTask_LevelLagLead << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_src.adoc[]" as ssis.PackageTask_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **TaskPath** : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_tgt.adoc[]" as ssis.PackageTask_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  - **PackageName** : (varchar(200))
  - **TaskPath** : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_import.adoc[]" as ssis.usp_import << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packagetask_tgt.adoc[]" as ssis.usp_PERSIST_PackageTask_tgt << P >> {
  --
}

docs.ssis_Adoc <.. docs.ssis_Adoc_T
docs.ssis_Adoc <.. docs.usp_PERSIST_ssis_Adoc_T
docs.ssis_Adoc_T <.. docs.usp_AntoraExport_SsisPartialsContent
docs.ssis_Adoc_T <.. docs.usp_PERSIST_ssis_Adoc_T
docs.ssis_PumlPackage <.. docs.ssis_Adoc
docs.ssis_PumlPartialTaskComponent <.. docs.ssis_PumlPackage
docs.ssis_TaskList <.. docs.ssis_Adoc
docs.usp_AntoraExport_SsisPartialsContent <.. docs.usp_AntoraExport
docs.usp_PERSIST_ssis_Adoc_T <.. docs.usp_AntoraExport_SsisPartialsContent
ssis.PackageTask <.. docs.ssis_Task
ssis.PackageTask <.. docs.ssis_TaskList
ssis.PackageTask <.. ssis.PackageTask_LevelLagLead
ssis.PackageTask_LevelLagLead <.. docs.ssis_PumlPartialTaskComponent
ssis.PackageTask_src <.. ssis.PackageTask_tgt
ssis.PackageTask_src <.. ssis.usp_PERSIST_PackageTask_tgt
ssis.PackageTask_tgt <.. ssis.PackageTask
ssis.PackageTask_tgt <.. ssis.usp_PERSIST_PackageTask_tgt
ssis.usp_PERSIST_PackageTask_tgt <.. ssis.usp_import

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_0_30_objectref[]

=== PlantUML 1 1 ColumnRef

// tag::puml_entity_1_1_colref[]
[plantuml, entity_1_1_colref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis.package_src.adoc[]" as ssis.Package_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  PackageCreationDate : (datetime)
  PackageCreatorComputerName : (nvarchar(500))
  PackageCreatorName : (varchar(1000))
  PackageDescription : (nvarchar(max))
  PackageDTSID : (uniqueidentifier)
  PackageLastModifiedProductVersion : (nvarchar(500))
  PackageLocaleID : (int)
  PackageObjectName : (nvarchar(500))
  - PackagePath : (varchar(8000))
  PackageProtectionLevel : (varchar(100))
  PackageProtectionLevelName : (varchar(28))
  PackageVersionGUID : (uniqueidentifier)
  - ProjectPath : (varchar(8000))
  - RowID : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_src.adoc[]" as ssis.PackageTask_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **TaskPath** : (varchar(8000))
  - ControlFlowDetailsRowID : (int)
  DelayValidationPropertyValue : (varchar(100))
  ExecutedPackageName : (varchar(1000))
  ExecutePackageConnection : (varchar(1000))
  ExecutePackageExpression : (varchar(1000))
  ExpressionValue : (varchar(5000))
  IsDisabled : (varchar(10))
  Script : (varchar(max))
  SqlConnection : (uniqueidentifier)
  SqlStatementSource : (nvarchar(max))
  TaskDescription : (varchar(max))
  TaskName : (varchar(2000))
  TaskType : (varchar(5000))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_tgt.adoc[]" as ssis.PackageTask_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  - **PackageName** : (varchar(200))
  - **TaskPath** : (varchar(8000))
  - ControlFlowDetailsRowID : (int)
  DelayValidationPropertyValue : (varchar(100))
  ExecutedPackageName : (varchar(1000))
  ExecutePackageConnection : (varchar(1000))
  ExecutePackageExpression : (varchar(1000))
  ExpressionValue : (varchar(5000))
  IsDisabled : (varchar(10))
  Script : (varchar(max))
  SqlConnection : (uniqueidentifier)
  SqlStatementSource : (nvarchar(max))
  TaskDescription : (varchar(max))
  - TaskName : (varchar(2000))
  TaskType : (varchar(5000))
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packagetask_tgt.adoc[]" as ssis.usp_PERSIST_PackageTask_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tblcontrolflow.adoc[]" as ssis_t.TblControlFlow << U >> {
  - **ControlFlowDetailsRowID** : (int)
  DelayValidationPropertyValue : (varchar(100))
  DFTQuery : (xml)
  ExecPkgTaskQry : (xml)
  ExpressionValue : (varchar(5000))
  IsDisabled : (varchar(10))
  RowID : (int)
  ScriptTaskQry : (xml)
  SqlTaskQry : (xml)
  TaskDescription : (varchar(max))
  TaskName : (varchar(2000))
  TaskPath : (varchar(8000))
  TaskType : (varchar(5000))
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_executepackage.adoc[]" as ssis_t.TblTask_ExecutePackage << U >> {
  - **ControlFlowDetailsRowID** : (int)
  ExecutedPackageName : (varchar(1000))
  ExecutePackageConnection : (varchar(1000))
  ExecutePackageExpression : (varchar(1000))
  RowID : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_script.adoc[]" as ssis_t.TblTask_Script << U >> {
  - **ControlFlowDetailsRowID** : (int)
  RowID : (int)
  Script : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_sql.adoc[]" as ssis_t.TblTask_Sql << U >> {
  - **ControlFlowDetailsRowID** : (int)
  - RowID : (int)
  SqlConnection : (uniqueidentifier)
  SqlStatementSource : (nvarchar(max))
  --
}

ssis.Package_src <.. ssis.PackageTask_src
ssis.PackageTask_src <.. ssis.PackageTask_tgt
ssis.PackageTask_src <.. ssis.usp_PERSIST_PackageTask_tgt
ssis_t.TblControlFlow <.. ssis.PackageTask_src
ssis_t.TblTask_ExecutePackage <.. ssis.PackageTask_src
ssis_t.TblTask_Script <.. ssis.PackageTask_src
ssis_t.TblTask_Sql <.. ssis.PackageTask_src
"ssis.Package_src::AntoraModule" <-- "ssis.PackageTask_src::AntoraModule"
"ssis.Package_src::PackageName" <-- "ssis.PackageTask_src::PackageName"
"ssis.PackageTask_src::AntoraModule" <-- "ssis.PackageTask_tgt::AntoraModule"
"ssis.PackageTask_src::ControlFlowDetailsRowID" <-- "ssis.PackageTask_tgt::ControlFlowDetailsRowID"
"ssis.PackageTask_src::DelayValidationPropertyValue" <-- "ssis.PackageTask_tgt::DelayValidationPropertyValue"
"ssis.PackageTask_src::ExecutedPackageName" <-- "ssis.PackageTask_tgt::ExecutedPackageName"
"ssis.PackageTask_src::ExecutePackageConnection" <-- "ssis.PackageTask_tgt::ExecutePackageConnection"
"ssis.PackageTask_src::ExecutePackageExpression" <-- "ssis.PackageTask_tgt::ExecutePackageExpression"
"ssis.PackageTask_src::ExpressionValue" <-- "ssis.PackageTask_tgt::ExpressionValue"
"ssis.PackageTask_src::IsDisabled" <-- "ssis.PackageTask_tgt::IsDisabled"
"ssis.PackageTask_src::PackageName" <-- "ssis.PackageTask_tgt::PackageName"
"ssis.PackageTask_src::Script" <-- "ssis.PackageTask_tgt::Script"
"ssis.PackageTask_src::SqlConnection" <-- "ssis.PackageTask_tgt::SqlConnection"
"ssis.PackageTask_src::SqlStatementSource" <-- "ssis.PackageTask_tgt::SqlStatementSource"
"ssis.PackageTask_src::TaskDescription" <-- "ssis.PackageTask_tgt::TaskDescription"
"ssis.PackageTask_src::TaskName" <-- "ssis.PackageTask_tgt::TaskName"
"ssis.PackageTask_src::TaskPath" <-- "ssis.PackageTask_tgt::TaskPath"
"ssis.PackageTask_src::TaskType" <-- "ssis.PackageTask_tgt::TaskType"
"ssis_t.TblControlFlow::ControlFlowDetailsRowID" <-- "ssis.PackageTask_src::ControlFlowDetailsRowID"
"ssis_t.TblControlFlow::DelayValidationPropertyValue" <-- "ssis.PackageTask_src::DelayValidationPropertyValue"
"ssis_t.TblControlFlow::ExpressionValue" <-- "ssis.PackageTask_src::ExpressionValue"
"ssis_t.TblControlFlow::IsDisabled" <-- "ssis.PackageTask_src::IsDisabled"
"ssis_t.TblControlFlow::TaskDescription" <-- "ssis.PackageTask_src::TaskDescription"
"ssis_t.TblControlFlow::TaskName" <-- "ssis.PackageTask_src::TaskName"
"ssis_t.TblControlFlow::TaskPath" <-- "ssis.PackageTask_src::TaskPath"
"ssis_t.TblControlFlow::TaskType" <-- "ssis.PackageTask_src::TaskType"
"ssis_t.TblTask_ExecutePackage::ExecutedPackageName" <-- "ssis.PackageTask_src::ExecutedPackageName"
"ssis_t.TblTask_ExecutePackage::ExecutePackageConnection" <-- "ssis.PackageTask_src::ExecutePackageConnection"
"ssis_t.TblTask_ExecutePackage::ExecutePackageExpression" <-- "ssis.PackageTask_src::ExecutePackageExpression"
"ssis_t.TblTask_Script::Script" <-- "ssis.PackageTask_src::Script"
"ssis_t.TblTask_Sql::SqlConnection" <-- "ssis.PackageTask_src::SqlConnection"
"ssis_t.TblTask_Sql::SqlStatementSource" <-- "ssis.PackageTask_src::SqlStatementSource"

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_colref[]


== sql_modules_definition

// tag::sql_modules_definition[]
[%collapsible]
=======
[source,sql,numbered,indent=0]
----

CREATE View ssis.PackageTask_src
As
Select
    p.AntoraModule
  , p.PackageName
  , T2.TaskPath
  , T2.TaskName
  , T2.ControlFlowDetailsRowID
  , T2.TaskDescription
  , T2.TaskType
  , T2.IsDisabled
  , T2.DelayValidationPropertyValue
  ---- The XML data type cannot be compared or sorted, except when using the IS NULL operator.
  --, T2.DFTQuery
  --, T2.SqlTaskQry
  --, T2.ExecPkgTaskQry
  --, T2.ScriptTaskQry
  , T2.ExpressionValue
  , T3.Script
  , T4.SqlConnection
  , T4.SqlStatementSource
  , T5.ExecutePackageExpression
  , T5.ExecutedPackageName
  , T5.ExecutePackageConnection
From
    ssis.Package_src                  As p
    Inner Join
        ssis_t.TblControlFlow         As T2
            On
            p.RowID                    = T2.RowID

    Left Outer Join
        ssis_t.TblTask_Script         As T3
            On
            T3.ControlFlowDetailsRowID = T2.ControlFlowDetailsRowID

    Left Outer Join
        ssis_t.TblTask_Sql            As T4
            On
            T4.ControlFlowDetailsRowID = T2.ControlFlowDetailsRowID

    Left Outer Join
        ssis_t.TblTask_ExecutePackage As T5
            On
            T5.ControlFlowDetailsRowID = T2.ControlFlowDetailsRowID

----
=======
// end::sql_modules_definition[]


