// tag::HeaderFullDisplayName[]
= ssis.PackageConnection_src - V
// end::HeaderFullDisplayName[]

== existing_properties

// tag::existing_properties[]

:ExistsProperty--antorareferencedlist:
:ExistsProperty--antorareferencinglist:
:ExistsProperty--is_repo_managed:
:ExistsProperty--is_ssas:
:ExistsProperty--pk_index_guid:
:ExistsProperty--pk_indexpatterncolumndatatype:
:ExistsProperty--pk_indexpatterncolumnname:
:ExistsProperty--referencedobjectlist:
:ExistsProperty--sql_modules_definition:
:ExistsProperty--FK:
:ExistsProperty--AntoraIndexList:
:ExistsProperty--Columns:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
5964FBE4-113B-EC11-852C-A81E8446D5B0
// end::RepoObject_guid[]

== RepoObject_FullDisplayName2

// tag::RepoObject_FullDisplayName2[]
ssis.PackageConnection_src
// end::RepoObject_FullDisplayName2[]

== SysObject_type

// tag::SysObject_type[]
V 
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
view
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
2133634694
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2021-11-01 14:14:06
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]
[discrete]
== _


[#column-antoramodule]
=== AntoraModule

[cols="d,8a,m,m,m"]
|===
|1
|*AntoraModule*
|varchar(50)
|NOT NULL
|
|===

.Referenced Columns
--
* xref:ssis.package_src.adoc#column-antoramodule[+ssis.Package_src.AntoraModule+]
--

.Referencing Columns
--
* xref:ssis.packageconnection_tgt.adoc#column-antoramodule[+ssis.PackageConnection_tgt.AntoraModule+]
--


[#column-packagename]
=== PackageName

[cols="d,8a,m,m,m"]
|===
|2
|*PackageName*
|varchar(200)
|NULL
|
|===

.Description
--
(left(replace([PackagePath],[ProjectPath]+'\',''),(200)))
--
{empty} +

.Referenced Columns
--
* xref:ssis.package_src.adoc#column-packagename[+ssis.Package_src.PackageName+]
--

.Referencing Columns
--
* xref:ssis.packageconnection_tgt.adoc#column-packagename[+ssis.PackageConnection_tgt.PackageName+]
--


[#column-connectionmanagerid]
=== ConnectionManagerID

[cols="d,8a,m,m,m"]
|===
|3
|*ConnectionManagerID*
|uniqueidentifier
|NULL
|
|===

.Referenced Columns
--
* xref:ssis_t.tblconnection.adoc#column-connectionmanagerid[+ssis_t.TblConnection.ConnectionManagerID+]
--

.Referencing Columns
--
* xref:ssis.packageconnection_tgt.adoc#column-connectionmanagerid[+ssis.PackageConnection_tgt.ConnectionManagerID+]
--


[#column-connectionmanagername]
=== ConnectionManagerName

[cols="d,8a,m,m,m"]
|===
|
|ConnectionManagerName
|varchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis_t.tblconnection.adoc#column-connectionmanagername[+ssis_t.TblConnection.ConnectionManagerName+]
--

.Referencing Columns
--
* xref:ssis.packageconnection_tgt.adoc#column-connectionmanagername[+ssis.PackageConnection_tgt.ConnectionManagerName+]
--


[#column-connectionmanagertype]
=== ConnectionManagerType

[cols="d,8a,m,m,m"]
|===
|
|ConnectionManagerType
|varchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis_t.tblconnection.adoc#column-connectionmanagertype[+ssis_t.TblConnection.ConnectionManagerType+]
--

.Referencing Columns
--
* xref:ssis.packageconnection_tgt.adoc#column-connectionmanagertype[+ssis.PackageConnection_tgt.ConnectionManagerType+]
--


[#column-connectionstring]
=== ConnectionString

[cols="d,8a,m,m,m"]
|===
|
|ConnectionString
|varchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis_t.tblconnection.adoc#column-connectionstring[+ssis_t.TblConnection.ConnectionString+]
--

.Referencing Columns
--
* xref:ssis.packageconnection_tgt.adoc#column-connectionstring[+ssis.PackageConnection_tgt.ConnectionString+]
--


[#column-expressionvalue]
=== ExpressionValue

[cols="d,8a,m,m,m"]
|===
|
|ExpressionValue
|varchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis_t.tblconnection.adoc#column-expressionvalue[+ssis_t.TblConnection.ExpressionValue+]
--

.Referencing Columns
--
* xref:ssis.packageconnection_tgt.adoc#column-expressionvalue[+ssis.PackageConnection_tgt.ExpressionValue+]
--


[#column-retainsameconnectionproperty]
=== RetainSameConnectionProperty

[cols="d,8a,m,m,m"]
|===
|
|RetainSameConnectionProperty
|nvarchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis_t.tblconnection.adoc#column-retainsameconnectionproperty[+ssis_t.TblConnection.RetainSameConnectionProperty+]
--

.Referencing Columns
--
* xref:ssis.packageconnection_tgt.adoc#column-retainsameconnectionproperty[+ssis.PackageConnection_tgt.RetainSameConnectionProperty+]
--


// end::AntoraColumnDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]
|1
|*<<column-antoramodule>>*
|varchar(50)
|NOT NULL
|

|2
|*<<column-packagename>>*
|varchar(200)
|NULL
|

|3
|*<<column-connectionmanagerid>>*
|uniqueidentifier
|NULL
|






// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]



|
|<<column-connectionmanagername>>
|varchar(max)
|NULL
|

|
|<<column-connectionmanagertype>>
|varchar(max)
|NULL
|

|
|<<column-connectionstring>>
|varchar(max)
|NULL
|

|
|<<column-expressionvalue>>
|varchar(max)
|NULL
|

|
|<<column-retainsameconnectionproperty>>
|nvarchar(max)
|NULL
|

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

[#index-pkunderlinepackageconnectionunderlinesrc]
=== PK_PackageConnection_src

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-AntoraModule>>; varchar(50)
* <<column-PackageName>>; varchar(200)
* <<column-ConnectionManagerID>>; uniqueidentifier
--
* PK, Unique, Real: 1, 1, 0


[#index-idxunderlinepackageconnectionunderlinesrcunderlineunderline2]
=== idx_PackageConnection_src++__++2

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-AntoraModule>>; varchar(50)
* <<column-PackageName>>; varchar(200)
--
* PK, Unique, Real: 0, 0, 0


[#index-idxunderlinepackageconnectionunderlinesrcunderlineunderline3]
=== idx_PackageConnection_src++__++3

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-AntoraModule>>; varchar(50)
--
* PK, Unique, Real: 0, 0, 0

// end::AntoraIndexList[]

== AntoraMeasureDetails

// tag::AntoraMeasureDetails[]

// end::AntoraMeasureDetails[]

== AntoraMeasureDescriptions



== AntoraParameterList

// tag::AntoraParameterList[]

// end::AntoraParameterList[]

== AntoraXrefCulturesList

// tag::AntoraXrefCulturesList[]
* xref:dhw:sqldb:ssis.packageconnection_src.adoc[] - 
// end::AntoraXrefCulturesList[]

== cultures_count

// tag::cultures_count[]
1
// end::cultures_count[]

== Other tags

source: property.RepoObjectProperty_cross As rop_cross


=== additional_reference_csv

// tag::additional_reference_csv[]

// end::additional_reference_csv[]


=== AdocUspSteps

// tag::adocuspsteps[]

// end::adocuspsteps[]


=== AntoraReferencedList

// tag::antorareferencedlist[]
* xref:dhw:sqldb:ssis.package_src.adoc[]
* xref:dhw:sqldb:ssis_t.tblconnection.adoc[]
// end::antorareferencedlist[]


=== AntoraReferencingList

// tag::antorareferencinglist[]
* xref:dhw:sqldb:ssis.packageconnection_tgt.adoc[]
* xref:dhw:sqldb:ssis.usp_persist_packageconnection_tgt.adoc[]
// end::antorareferencinglist[]


=== Description

// tag::description[]

// end::description[]


=== exampleUsage

// tag::exampleusage[]

// end::exampleusage[]


=== exampleUsage_2

// tag::exampleusage_2[]

// end::exampleusage_2[]


=== exampleUsage_3

// tag::exampleusage_3[]

// end::exampleusage_3[]


=== exampleUsage_4

// tag::exampleusage_4[]

// end::exampleusage_4[]


=== exampleUsage_5

// tag::exampleusage_5[]

// end::exampleusage_5[]


=== exampleWrong_Usage

// tag::examplewrong_usage[]

// end::examplewrong_usage[]


=== has_execution_plan_issue

// tag::has_execution_plan_issue[]

// end::has_execution_plan_issue[]


=== has_get_referenced_issue

// tag::has_get_referenced_issue[]

// end::has_get_referenced_issue[]


=== has_history

// tag::has_history[]

// end::has_history[]


=== has_history_columns

// tag::has_history_columns[]

// end::has_history_columns[]


=== InheritanceType

// tag::inheritancetype[]

// end::inheritancetype[]


=== is_persistence

// tag::is_persistence[]

// end::is_persistence[]


=== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]

// end::is_persistence_check_duplicate_per_pk[]


=== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]

// end::is_persistence_check_for_empty_source[]


=== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]

// end::is_persistence_delete_changed[]


=== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]

// end::is_persistence_delete_missing[]


=== is_persistence_insert

// tag::is_persistence_insert[]

// end::is_persistence_insert[]


=== is_persistence_truncate

// tag::is_persistence_truncate[]

// end::is_persistence_truncate[]


=== is_persistence_update_changed

// tag::is_persistence_update_changed[]

// end::is_persistence_update_changed[]


=== is_repo_managed

// tag::is_repo_managed[]
0
// end::is_repo_managed[]


=== is_ssas

// tag::is_ssas[]
0
// end::is_ssas[]


=== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


=== MS_Description

// tag::ms_description[]

// end::ms_description[]


=== persistence_source_RepoObject_fullname

// tag::persistence_source_repoobject_fullname[]

// end::persistence_source_repoobject_fullname[]


=== persistence_source_RepoObject_fullname2

// tag::persistence_source_repoobject_fullname2[]

// end::persistence_source_repoobject_fullname2[]


=== persistence_source_RepoObject_guid

// tag::persistence_source_repoobject_guid[]

// end::persistence_source_repoobject_guid[]


=== persistence_source_RepoObject_xref

// tag::persistence_source_repoobject_xref[]

// end::persistence_source_repoobject_xref[]


=== pk_index_guid

// tag::pk_index_guid[]
F001BE14-1C3B-EC11-852C-A81E8446D5B0
// end::pk_index_guid[]


=== pk_IndexPatternColumnDatatype

// tag::pk_indexpatterncolumndatatype[]
varchar(50),varchar(200),uniqueidentifier
// end::pk_indexpatterncolumndatatype[]


=== pk_IndexPatternColumnName

// tag::pk_indexpatterncolumnname[]
AntoraModule,PackageName,ConnectionManagerID
// end::pk_indexpatterncolumnname[]


=== pk_IndexSemanticGroup

// tag::pk_indexsemanticgroup[]

// end::pk_indexsemanticgroup[]


=== ReferencedObjectList

// tag::referencedobjectlist[]
* [ssis].[Package_src]
* [ssis_t].[TblConnection]
// end::referencedobjectlist[]


=== usp_persistence_RepoObject_guid

// tag::usp_persistence_repoobject_guid[]

// end::usp_persistence_repoobject_guid[]


=== UspExamples

// tag::uspexamples[]

// end::uspexamples[]


=== uspgenerator_usp_id

// tag::uspgenerator_usp_id[]

// end::uspgenerator_usp_id[]


=== UspParameters

// tag::uspparameters[]

// end::uspparameters[]

== Boolean Attributes

source: property.RepoObjectProperty WHERE property_int = 1

// tag::boolean_attributes[]


// end::boolean_attributes[]

== PlantUML diagrams

=== PlantUML Entity

// tag::puml_entity[]
[plantuml, entity-{docname}, svg, subs=macros]
....
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis.packageconnection_src.adoc[]" as ssis.PackageConnection_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **ConnectionManagerID** : (uniqueidentifier)
  ConnectionManagerName : (varchar(max))
  ConnectionManagerType : (varchar(max))
  ConnectionString : (varchar(max))
  ExpressionValue : (varchar(max))
  RetainSameConnectionProperty : (nvarchar(max))
  --
}
....

// end::puml_entity[]

=== PlantUML Entity 1 1 FK

// tag::puml_entity_1_1_fk[]
[plantuml, entity_1_1_fk-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis.packageconnection_src.adoc[]" as ssis.PackageConnection_src << V >> {
- **PK_PackageConnection_src**

..
AntoraModule; varchar(50)
PackageName; varchar(200)
ConnectionManagerID; uniqueidentifier
--
- idx_PackageConnection_src__2

..
AntoraModule; varchar(50)
PackageName; varchar(200)
--
- idx_PackageConnection_src__3

..
AntoraModule; varchar(50)
}



footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_fk[]

=== PlantUML 1 1 ObjectRef

// tag::puml_entity_1_1_objectref[]
[plantuml, entity_1_1_objectref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis.package_src.adoc[]" as ssis.Package_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  --
}

entity "puml-link:dhw:sqldb:ssis.packageconnection_src.adoc[]" as ssis.PackageConnection_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **ConnectionManagerID** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:ssis.packageconnection_tgt.adoc[]" as ssis.PackageConnection_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  - **PackageName** : (varchar(200))
  - **ConnectionManagerID** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packageconnection_tgt.adoc[]" as ssis.usp_PERSIST_PackageConnection_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tblconnection.adoc[]" as ssis_t.TblConnection << U >> {
  --
}

ssis.Package_src <.. ssis.PackageConnection_src
ssis.PackageConnection_src <.. ssis.PackageConnection_tgt
ssis.PackageConnection_src <.. ssis.usp_PERSIST_PackageConnection_tgt
ssis_t.TblConnection <.. ssis.PackageConnection_src

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_objectref[]

=== PlantUML 30 0 ObjectRef

// tag::puml_entity_30_0_objectref[]
[plantuml, entity_30_0_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis.package_src.adoc[]" as ssis.Package_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  --
}

entity "puml-link:dhw:sqldb:ssis.packageconnection_src.adoc[]" as ssis.PackageConnection_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **ConnectionManagerID** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:ssis.project.adoc[]" as ssis.Project << U >> {
  - **AntoraModule** : (varchar(50))
  --
}

entity "puml-link:dhw:sqldb:ssis_t.pkgstats.adoc[]" as ssis_t.pkgStats << U >> {
  - **RowID** : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tblconnection.adoc[]" as ssis_t.TblConnection << U >> {
  --
}

ssis.Package_src <.. ssis.PackageConnection_src
ssis.Project <.. ssis.Package_src
ssis_t.pkgStats <.. ssis.Package_src
ssis_t.TblConnection <.. ssis.PackageConnection_src

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_30_0_objectref[]

=== PlantUML 0 30 ObjectRef

// tag::puml_entity_0_30_objectref[]
[plantuml, entity_0_30_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:docs.ssis_adoc.adoc[]" as docs.ssis_Adoc << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageBasename** : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_adoc_t.adoc[]" as docs.ssis_Adoc_T << U >> {
  - **AntoraModule** : (varchar(50))
  - **PackageBasename** : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_packageconnectionlist.adoc[]" as docs.ssis_PackageConnectionList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_task.adoc[]" as docs.ssis_Task << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_tasklist.adoc[]" as docs.ssis_TaskList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport.adoc[]" as docs.usp_AntoraExport << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_ssispartialscontent.adoc[]" as docs.usp_AntoraExport_SsisPartialsContent << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_ssis_adoc_t.adoc[]" as docs.usp_PERSIST_ssis_Adoc_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.packageconnection.adoc[]" as ssis.PackageConnection << U >> {
  - **AntoraModule** : (varchar(50))
  - **PackageName** : (varchar(200))
  - **ConnectionManagerID** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:ssis.packageconnection_src.adoc[]" as ssis.PackageConnection_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **ConnectionManagerID** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:ssis.packageconnection_tgt.adoc[]" as ssis.PackageConnection_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  - **PackageName** : (varchar(200))
  - **ConnectionManagerID** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_import.adoc[]" as ssis.usp_import << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packageconnection_tgt.adoc[]" as ssis.usp_PERSIST_PackageConnection_tgt << P >> {
  --
}

docs.ssis_Adoc <.. docs.ssis_Adoc_T
docs.ssis_Adoc <.. docs.usp_PERSIST_ssis_Adoc_T
docs.ssis_Adoc_T <.. docs.usp_AntoraExport_SsisPartialsContent
docs.ssis_Adoc_T <.. docs.usp_PERSIST_ssis_Adoc_T
docs.ssis_PackageConnectionList <.. docs.ssis_Adoc
docs.ssis_TaskList <.. docs.ssis_Adoc
docs.usp_AntoraExport_SsisPartialsContent <.. docs.usp_AntoraExport
docs.usp_PERSIST_ssis_Adoc_T <.. docs.usp_AntoraExport_SsisPartialsContent
ssis.PackageConnection <.. docs.ssis_PackageConnectionList
ssis.PackageConnection <.. docs.ssis_Task
ssis.PackageConnection <.. docs.ssis_TaskList
ssis.PackageConnection_src <.. ssis.PackageConnection_tgt
ssis.PackageConnection_src <.. ssis.usp_PERSIST_PackageConnection_tgt
ssis.PackageConnection_tgt <.. ssis.PackageConnection
ssis.PackageConnection_tgt <.. ssis.usp_PERSIST_PackageConnection_tgt
ssis.usp_PERSIST_PackageConnection_tgt <.. ssis.usp_import

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_0_30_objectref[]

=== PlantUML 1 1 ColumnRef

// tag::puml_entity_1_1_colref[]
[plantuml, entity_1_1_colref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis.package_src.adoc[]" as ssis.Package_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  PackageCreationDate : (datetime)
  PackageCreatorComputerName : (nvarchar(500))
  PackageCreatorName : (varchar(1000))
  PackageDescription : (nvarchar(max))
  PackageDTSID : (uniqueidentifier)
  PackageLastModifiedProductVersion : (nvarchar(500))
  PackageLocaleID : (int)
  PackageObjectName : (nvarchar(500))
  - PackagePath : (varchar(8000))
  PackageProtectionLevel : (varchar(100))
  PackageProtectionLevelName : (varchar(28))
  PackageVersionGUID : (uniqueidentifier)
  - ProjectPath : (varchar(8000))
  - RowID : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis.packageconnection_src.adoc[]" as ssis.PackageConnection_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **ConnectionManagerID** : (uniqueidentifier)
  ConnectionManagerName : (varchar(max))
  ConnectionManagerType : (varchar(max))
  ConnectionString : (varchar(max))
  ExpressionValue : (varchar(max))
  RetainSameConnectionProperty : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packageconnection_tgt.adoc[]" as ssis.PackageConnection_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  - **PackageName** : (varchar(200))
  - **ConnectionManagerID** : (uniqueidentifier)
  ConnectionManagerName : (varchar(max))
  ConnectionManagerType : (varchar(max))
  ConnectionString : (varchar(max))
  ExpressionValue : (varchar(max))
  RetainSameConnectionProperty : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packageconnection_tgt.adoc[]" as ssis.usp_PERSIST_PackageConnection_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tblconnection.adoc[]" as ssis_t.TblConnection << U >> {
  - Category : (varchar(10))
  ConnectionManagerID : (uniqueidentifier)
  ConnectionManagerName : (varchar(max))
  ConnectionManagerType : (varchar(max))
  ConnectionString : (varchar(max))
  - DelayValidationPropertyValue : (varchar(2))
  ExpressionValue : (varchar(max))
  PackageCreatorName : (varchar(1000))
  PackageName : (varchar(8000))
  - PackagePath : (varchar(8000))
  RetainSameConnectionProperty : (nvarchar(max))
  - RowID : (int)
  --
}

ssis.Package_src <.. ssis.PackageConnection_src
ssis.PackageConnection_src <.. ssis.PackageConnection_tgt
ssis.PackageConnection_src <.. ssis.usp_PERSIST_PackageConnection_tgt
ssis_t.TblConnection <.. ssis.PackageConnection_src
"ssis.Package_src::AntoraModule" <-- "ssis.PackageConnection_src::AntoraModule"
"ssis.Package_src::PackageName" <-- "ssis.PackageConnection_src::PackageName"
"ssis.PackageConnection_src::AntoraModule" <-- "ssis.PackageConnection_tgt::AntoraModule"
"ssis.PackageConnection_src::ConnectionManagerID" <-- "ssis.PackageConnection_tgt::ConnectionManagerID"
"ssis.PackageConnection_src::ConnectionManagerName" <-- "ssis.PackageConnection_tgt::ConnectionManagerName"
"ssis.PackageConnection_src::ConnectionManagerType" <-- "ssis.PackageConnection_tgt::ConnectionManagerType"
"ssis.PackageConnection_src::ConnectionString" <-- "ssis.PackageConnection_tgt::ConnectionString"
"ssis.PackageConnection_src::ExpressionValue" <-- "ssis.PackageConnection_tgt::ExpressionValue"
"ssis.PackageConnection_src::PackageName" <-- "ssis.PackageConnection_tgt::PackageName"
"ssis.PackageConnection_src::RetainSameConnectionProperty" <-- "ssis.PackageConnection_tgt::RetainSameConnectionProperty"
"ssis_t.TblConnection::ConnectionManagerID" <-- "ssis.PackageConnection_src::ConnectionManagerID"
"ssis_t.TblConnection::ConnectionManagerName" <-- "ssis.PackageConnection_src::ConnectionManagerName"
"ssis_t.TblConnection::ConnectionManagerType" <-- "ssis.PackageConnection_src::ConnectionManagerType"
"ssis_t.TblConnection::ConnectionString" <-- "ssis.PackageConnection_src::ConnectionString"
"ssis_t.TblConnection::ExpressionValue" <-- "ssis.PackageConnection_src::ExpressionValue"
"ssis_t.TblConnection::RetainSameConnectionProperty" <-- "ssis.PackageConnection_src::RetainSameConnectionProperty"

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_colref[]


== sql_modules_definition

// tag::sql_modules_definition[]
[%collapsible]
=======
[source,sql,numbered,indent=0]
----



CREATE View [ssis].[PackageConnection_src]
As
Select
    p.AntoraModule
  , p.PackageName
  , T2.ConnectionManagerID
  , T2.ConnectionManagerName
  , T2.ConnectionManagerType
  , T2.ConnectionString
  , T2.ExpressionValue
  , T2.RetainSameConnectionProperty
From
    ssis.Package_src         As p
    Inner Join
        ssis_t.TblConnection As T2
            On
            p.RowID = T2.RowID

----
=======
// end::sql_modules_definition[]


