// tag::HeaderFullDisplayName[]
= ssis.PackageTask - U
// end::HeaderFullDisplayName[]

== existing_properties

// tag::existing_properties[]

:ExistsProperty--antorareferencedlist:
:ExistsProperty--antorareferencinglist:
:ExistsProperty--is_repo_managed:
:ExistsProperty--is_ssas:
:ExistsProperty--referencedobjectlist:
:ExistsProperty--FK:
:ExistsProperty--Columns:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
6264FBE4-113B-EC11-852C-A81E8446D5B0
// end::RepoObject_guid[]

== RepoObject_FullDisplayName2

// tag::RepoObject_FullDisplayName2[]
ssis.PackageTask
// end::RepoObject_FullDisplayName2[]

== SysObject_type

// tag::SysObject_type[]
U 
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
user table
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
2082158513
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2022-01-23 14:10:32
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]
[discrete]
== _


[#column-antoramodule]
=== AntoraModule

[cols="d,8a,m,m,m"]
|===
|
|AntoraModule
|varchar(50)
|NOT NULL
|
|===

.Referencing Columns
--
* xref:docs.ssis_task.adoc#column-antoramodule[+docs.ssis_Task.AntoraModule+]
* xref:docs.ssis_tasklist.adoc#column-antoramodule[+docs.ssis_TaskList.AntoraModule+]
* xref:ssis.packagetask_levellaglead.adoc#column-antoramodule[+ssis.PackageTask_LevelLagLead.AntoraModule+]
* xref:ssis.packagetask_tgt.adoc#column-antoramodule[+ssis.PackageTask_tgt.AntoraModule+]
--


[#column-controlflowdetailsrowid]
=== ControlFlowDetailsRowID

[cols="d,8a,m,m,m"]
|===
|
|ControlFlowDetailsRowID
|int
|NOT NULL
|
|===

.Referencing Columns
--
* xref:ssis.packagetask_tgt.adoc#column-controlflowdetailsrowid[+ssis.PackageTask_tgt.ControlFlowDetailsRowID+]
--


[#column-delayvalidationpropertyvalue]
=== DelayValidationPropertyValue

[cols="d,8a,m,m,m"]
|===
|
|DelayValidationPropertyValue
|varchar(100)
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packagetask_tgt.adoc#column-delayvalidationpropertyvalue[+ssis.PackageTask_tgt.DelayValidationPropertyValue+]
--


[#column-executedpackagename]
=== ExecutedPackageName

[cols="d,8a,m,m,m"]
|===
|
|ExecutedPackageName
|varchar(1000)
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packagetask_tgt.adoc#column-executedpackagename[+ssis.PackageTask_tgt.ExecutedPackageName+]
--


[#column-executepackageconnection]
=== ExecutePackageConnection

[cols="d,8a,m,m,m"]
|===
|
|ExecutePackageConnection
|varchar(1000)
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packagetask_tgt.adoc#column-executepackageconnection[+ssis.PackageTask_tgt.ExecutePackageConnection+]
--


[#column-executepackageexpression]
=== ExecutePackageExpression

[cols="d,8a,m,m,m"]
|===
|
|ExecutePackageExpression
|varchar(1000)
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packagetask_tgt.adoc#column-executepackageexpression[+ssis.PackageTask_tgt.ExecutePackageExpression+]
--


[#column-expressionvalue]
=== ExpressionValue

[cols="d,8a,m,m,m"]
|===
|
|ExpressionValue
|varchar(5000)
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packagetask_tgt.adoc#column-expressionvalue[+ssis.PackageTask_tgt.ExpressionValue+]
--


[#column-isdisabled]
=== IsDisabled

[cols="d,8a,m,m,m"]
|===
|
|IsDisabled
|varchar(10)
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packagetask_tgt.adoc#column-isdisabled[+ssis.PackageTask_tgt.IsDisabled+]
--


[#column-packagename]
=== PackageName

[cols="d,8a,m,m,m"]
|===
|
|PackageName
|varchar(200)
|NOT NULL
|
|===

.Referencing Columns
--
* xref:docs.ssis_task.adoc#column-packagename[+docs.ssis_Task.PackageName+]
* xref:docs.ssis_tasklist.adoc#column-packagename[+docs.ssis_TaskList.PackageName+]
* xref:ssis.packagetask.adoc#column-packagebasename[+ssis.PackageTask.PackageBasename+]
* xref:ssis.packagetask_levellaglead.adoc#column-packagename[+ssis.PackageTask_LevelLagLead.PackageName+]
* xref:ssis.packagetask_tgt.adoc#column-packagename[+ssis.PackageTask_tgt.PackageName+]
--


[#column-script]
=== Script

[cols="d,8a,m,m,m"]
|===
|
|Script
|varchar(max)
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packagetask_tgt.adoc#column-script[+ssis.PackageTask_tgt.Script+]
--


[#column-sqlconnection]
=== SqlConnection

[cols="d,8a,m,m,m"]
|===
|
|SqlConnection
|uniqueidentifier
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packagetask_tgt.adoc#column-sqlconnection[+ssis.PackageTask_tgt.SqlConnection+]
--


[#column-sqlstatementsource]
=== SqlStatementSource

[cols="d,8a,m,m,m"]
|===
|
|SqlStatementSource
|nvarchar(max)
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packagetask_tgt.adoc#column-sqlstatementsource[+ssis.PackageTask_tgt.SqlStatementSource+]
--


[#column-taskdescription]
=== TaskDescription

[cols="d,8a,m,m,m"]
|===
|
|TaskDescription
|varchar(max)
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packagetask_tgt.adoc#column-taskdescription[+ssis.PackageTask_tgt.TaskDescription+]
--


[#column-taskname]
=== TaskName

[cols="d,8a,m,m,m"]
|===
|
|TaskName
|varchar(2000)
|NOT NULL
|
|===

.Referencing Columns
--
* xref:ssis.packagetask_levellaglead.adoc#column-taskname[+ssis.PackageTask_LevelLagLead.TaskName+]
* xref:ssis.packagetask_tgt.adoc#column-taskname[+ssis.PackageTask_tgt.TaskName+]
--


[#column-taskpath]
=== TaskPath

[cols="d,8a,m,m,m"]
|===
|
|TaskPath
|varchar(8000)
|NOT NULL
|
|===

.Referencing Columns
--
* xref:docs.ssis_task.adoc#column-taskpath[+docs.ssis_Task.TaskPath+]
* xref:ssis.packagetask.adoc#column-taskpathlevel[+ssis.PackageTask.TaskPathLevel+]
* xref:ssis.packagetask.adoc#column-taskpathparent[+ssis.PackageTask.TaskPathParent+]
* xref:ssis.packagetask_levellaglead.adoc#column-taskpath[+ssis.PackageTask_LevelLagLead.TaskPath+]
* xref:ssis.packagetask_tgt.adoc#column-taskpath[+ssis.PackageTask_tgt.TaskPath+]
--


[#column-tasktype]
=== TaskType

[cols="d,8a,m,m,m"]
|===
|
|TaskType
|varchar(5000)
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packagetask_levellaglead.adoc#column-tasktype[+ssis.PackageTask_LevelLagLead.TaskType+]
* xref:ssis.packagetask_tgt.adoc#column-tasktype[+ssis.PackageTask_tgt.TaskType+]
--


[#column-packagebasename]
=== PackageBasename

[cols="d,8a,m,m,m"]
|===
|
|PackageBasename

.Definition (PERSISTED)
[source,sql]
----
(replace([PackageName],'.dtsx',''))
----


|varchar(8000)
|NULL
|
|===

.Description
--
(replace([PackageName],'.dtsx',''))
--
{empty} +

.Referenced Columns
--
* xref:ssis.packagetask.adoc#column-packagename[+ssis.PackageTask.PackageName+]
--

.Referencing Columns
--
* xref:ssis.packagetask_levellaglead.adoc#column-packagebasename[+ssis.PackageTask_LevelLagLead.PackageBasename+]
--


[#column-taskpathlevel]
=== TaskPathLevel

[cols="d,8a,m,m,m"]
|===
|
|TaskPathLevel

.Definition (PERSISTED)
[source,sql]
----
(len([TaskPath])-len(replace([TaskPath],'\','')))
----


|int
|NULL
|
|===

.Description
--
(len([TaskPath])-len(replace([TaskPath],'\','')))
--
{empty} +

.Referenced Columns
--
* xref:ssis.packagetask.adoc#column-taskpath[+ssis.PackageTask.TaskPath+]
--

.Referencing Columns
--
* xref:ssis.packagetask_levellaglead.adoc#column-taskpathlevel[+ssis.PackageTask_LevelLagLead.TaskPathLevel+]
--


[#column-taskpathparent]
=== TaskPathParent

[cols="d,8a,m,m,m"]
|===
|
|TaskPathParent

.Definition (PERSISTED)
[source,sql]
----
(substring([TaskPath],(1),len([TaskPath])-charindex('\',reverse([TaskPath]))))
----


|varchar(8000)
|NULL
|
|===

.Description
--
(substring([TaskPath],(1),len([TaskPath])-charindex('\',reverse([TaskPath]))))
--
{empty} +

.Referenced Columns
--
* xref:ssis.packagetask.adoc#column-taskpath[+ssis.PackageTask.TaskPath+]
--

.Referencing Columns
--
* xref:ssis.packagetask_levellaglead.adoc#column-taskpathparent[+ssis.PackageTask_LevelLagLead.TaskPathParent+]
--


// end::AntoraColumnDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]



















// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]
|
|<<column-antoramodule>>
|varchar(50)
|NOT NULL
|

|
|<<column-controlflowdetailsrowid>>
|int
|NOT NULL
|

|
|<<column-delayvalidationpropertyvalue>>
|varchar(100)
|NULL
|

|
|<<column-executedpackagename>>
|varchar(1000)
|NULL
|

|
|<<column-executepackageconnection>>
|varchar(1000)
|NULL
|

|
|<<column-executepackageexpression>>
|varchar(1000)
|NULL
|

|
|<<column-expressionvalue>>
|varchar(5000)
|NULL
|

|
|<<column-isdisabled>>
|varchar(10)
|NULL
|

|
|<<column-packagename>>
|varchar(200)
|NOT NULL
|

|
|<<column-script>>
|varchar(max)
|NULL
|

|
|<<column-sqlconnection>>
|uniqueidentifier
|NULL
|

|
|<<column-sqlstatementsource>>
|nvarchar(max)
|NULL
|

|
|<<column-taskdescription>>
|varchar(max)
|NULL
|

|
|<<column-taskname>>
|varchar(2000)
|NOT NULL
|

|
|<<column-taskpath>>
|varchar(8000)
|NOT NULL
|

|
|<<column-tasktype>>
|varchar(5000)
|NULL
|

|
|<<column-packagebasename>>

.Definition (PERSISTED)
[source,sql]
----
(replace([PackageName],'.dtsx',''))
----


|varchar(8000)
|NULL
|

|
|<<column-taskpathlevel>>

.Definition (PERSISTED)
[source,sql]
----
(len([TaskPath])-len(replace([TaskPath],'\','')))
----


|int
|NULL
|

|
|<<column-taskpathparent>>

.Definition (PERSISTED)
[source,sql]
----
(substring([TaskPath],(1),len([TaskPath])-charindex('\',reverse([TaskPath]))))
----


|varchar(8000)
|NULL
|

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

// end::AntoraIndexList[]

== AntoraMeasureDetails

// tag::AntoraMeasureDetails[]

// end::AntoraMeasureDetails[]

== AntoraMeasureDescriptions



== AntoraParameterList

// tag::AntoraParameterList[]

// end::AntoraParameterList[]

== AntoraXrefCulturesList

// tag::AntoraXrefCulturesList[]
* xref:dhw:sqldb:ssis.packagetask.adoc[] - 
// end::AntoraXrefCulturesList[]

== cultures_count

// tag::cultures_count[]
1
// end::cultures_count[]

== Other tags

source: property.RepoObjectProperty_cross As rop_cross


=== additional_reference_csv

// tag::additional_reference_csv[]

// end::additional_reference_csv[]


=== AdocUspSteps

// tag::adocuspsteps[]

// end::adocuspsteps[]


=== AntoraReferencedList

// tag::antorareferencedlist[]
* xref:dhw:sqldb:ssis.packagetask_tgt.adoc[]
// end::antorareferencedlist[]


=== AntoraReferencingList

// tag::antorareferencinglist[]
* xref:dhw:sqldb:docs.ssis_task.adoc[]
* xref:dhw:sqldb:docs.ssis_tasklist.adoc[]
* xref:dhw:sqldb:ssis.packagetask_levellaglead.adoc[]
// end::antorareferencinglist[]


=== Description

// tag::description[]

// end::description[]


=== exampleUsage

// tag::exampleusage[]

// end::exampleusage[]


=== exampleUsage_2

// tag::exampleusage_2[]

// end::exampleusage_2[]


=== exampleUsage_3

// tag::exampleusage_3[]

// end::exampleusage_3[]


=== exampleUsage_4

// tag::exampleusage_4[]

// end::exampleusage_4[]


=== exampleUsage_5

// tag::exampleusage_5[]

// end::exampleusage_5[]


=== exampleWrong_Usage

// tag::examplewrong_usage[]

// end::examplewrong_usage[]


=== has_execution_plan_issue

// tag::has_execution_plan_issue[]

// end::has_execution_plan_issue[]


=== has_get_referenced_issue

// tag::has_get_referenced_issue[]

// end::has_get_referenced_issue[]


=== has_history

// tag::has_history[]

// end::has_history[]


=== has_history_columns

// tag::has_history_columns[]

// end::has_history_columns[]


=== InheritanceType

// tag::inheritancetype[]

// end::inheritancetype[]


=== is_persistence

// tag::is_persistence[]

// end::is_persistence[]


=== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]

// end::is_persistence_check_duplicate_per_pk[]


=== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]

// end::is_persistence_check_for_empty_source[]


=== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]

// end::is_persistence_delete_changed[]


=== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]

// end::is_persistence_delete_missing[]


=== is_persistence_insert

// tag::is_persistence_insert[]

// end::is_persistence_insert[]


=== is_persistence_truncate

// tag::is_persistence_truncate[]

// end::is_persistence_truncate[]


=== is_persistence_update_changed

// tag::is_persistence_update_changed[]

// end::is_persistence_update_changed[]


=== is_repo_managed

// tag::is_repo_managed[]
0
// end::is_repo_managed[]


=== is_ssas

// tag::is_ssas[]
0
// end::is_ssas[]


=== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


=== MS_Description

// tag::ms_description[]

// end::ms_description[]


=== persistence_source_RepoObject_fullname

// tag::persistence_source_repoobject_fullname[]

// end::persistence_source_repoobject_fullname[]


=== persistence_source_RepoObject_fullname2

// tag::persistence_source_repoobject_fullname2[]

// end::persistence_source_repoobject_fullname2[]


=== persistence_source_RepoObject_guid

// tag::persistence_source_repoobject_guid[]

// end::persistence_source_repoobject_guid[]


=== persistence_source_RepoObject_xref

// tag::persistence_source_repoobject_xref[]

// end::persistence_source_repoobject_xref[]


=== pk_index_guid

// tag::pk_index_guid[]

// end::pk_index_guid[]


=== pk_IndexPatternColumnDatatype

// tag::pk_indexpatterncolumndatatype[]

// end::pk_indexpatterncolumndatatype[]


=== pk_IndexPatternColumnName

// tag::pk_indexpatterncolumnname[]

// end::pk_indexpatterncolumnname[]


=== pk_IndexSemanticGroup

// tag::pk_indexsemanticgroup[]

// end::pk_indexsemanticgroup[]


=== ReferencedObjectList

// tag::referencedobjectlist[]
* [ssis].[PackageTask_tgt]
// end::referencedobjectlist[]


=== usp_persistence_RepoObject_guid

// tag::usp_persistence_repoobject_guid[]

// end::usp_persistence_repoobject_guid[]


=== UspExamples

// tag::uspexamples[]

// end::uspexamples[]


=== uspgenerator_usp_id

// tag::uspgenerator_usp_id[]

// end::uspgenerator_usp_id[]


=== UspParameters

// tag::uspparameters[]

// end::uspparameters[]

== Boolean Attributes

source: property.RepoObjectProperty WHERE property_int = 1

// tag::boolean_attributes[]


// end::boolean_attributes[]

== PlantUML diagrams

=== PlantUML Entity

// tag::puml_entity[]
[plantuml, entity-{docname}, svg, subs=macros]
....
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis.packagetask.adoc[]" as ssis.PackageTask << U >> {
  - AntoraModule : (varchar(50))
  - ControlFlowDetailsRowID : (int)
  DelayValidationPropertyValue : (varchar(100))
  ExecutedPackageName : (varchar(1000))
  ExecutePackageConnection : (varchar(1000))
  ExecutePackageExpression : (varchar(1000))
  ExpressionValue : (varchar(5000))
  IsDisabled : (varchar(10))
  - PackageName : (varchar(200))
  Script : (varchar(max))
  SqlConnection : (uniqueidentifier)
  SqlStatementSource : (nvarchar(max))
  TaskDescription : (varchar(max))
  - TaskName : (varchar(2000))
  - TaskPath : (varchar(8000))
  TaskType : (varchar(5000))
  # PackageBasename : (varchar(8000))
  # TaskPathLevel : (int)
  # TaskPathParent : (varchar(8000))
  --
}
....

// end::puml_entity[]

=== PlantUML Entity 1 1 FK

// tag::puml_entity_1_1_fk[]
[plantuml, entity_1_1_fk-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis.packagetask.adoc[]" as ssis.PackageTask << U >> {

}



footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_fk[]

=== PlantUML 1 1 ObjectRef

// tag::puml_entity_1_1_objectref[]
[plantuml, entity_1_1_objectref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:docs.ssis_task.adoc[]" as docs.ssis_Task << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_tasklist.adoc[]" as docs.ssis_TaskList << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask.adoc[]" as ssis.PackageTask << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_levellaglead.adoc[]" as ssis.PackageTask_LevelLagLead << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_tgt.adoc[]" as ssis.PackageTask_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  - **PackageName** : (varchar(200))
  - **TaskPath** : (varchar(8000))
  --
}

ssis.PackageTask <.. docs.ssis_TaskList
ssis.PackageTask <.. ssis.PackageTask_LevelLagLead
ssis.PackageTask <.. docs.ssis_Task
ssis.PackageTask_tgt <.. ssis.PackageTask

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_objectref[]

=== PlantUML 30 0 ObjectRef

// tag::puml_entity_30_0_objectref[]
[plantuml, entity_30_0_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis.antoramodule_tgt_filter.adoc[]" as ssis.AntoraModule_tgt_filter << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.package_src.adoc[]" as ssis.Package_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask.adoc[]" as ssis.PackageTask << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_src.adoc[]" as ssis.PackageTask_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **TaskPath** : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_tgt.adoc[]" as ssis.PackageTask_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  - **PackageName** : (varchar(200))
  - **TaskPath** : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:ssis.project.adoc[]" as ssis.Project << U >> {
  - **AntoraModule** : (varchar(50))
  --
}

entity "puml-link:dhw:sqldb:ssis_t.pkgstats.adoc[]" as ssis_t.pkgStats << U >> {
  - **RowID** : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tblcontrolflow.adoc[]" as ssis_t.TblControlFlow << U >> {
  - **ControlFlowDetailsRowID** : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_executepackage.adoc[]" as ssis_t.TblTask_ExecutePackage << U >> {
  - **ControlFlowDetailsRowID** : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_script.adoc[]" as ssis_t.TblTask_Script << U >> {
  - **ControlFlowDetailsRowID** : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_sql.adoc[]" as ssis_t.TblTask_Sql << U >> {
  - **ControlFlowDetailsRowID** : (int)
  --
}

ssis.AntoraModule_tgt_filter <.. ssis.PackageTask_tgt
ssis.Package_src <.. ssis.AntoraModule_tgt_filter
ssis.Package_src <.. ssis.PackageTask_src
ssis.PackageTask_src <.. ssis.PackageTask_tgt
ssis.PackageTask_tgt <.. ssis.PackageTask
ssis.Project <.. ssis.Package_src
ssis_t.pkgStats <.. ssis.Package_src
ssis_t.TblControlFlow <.. ssis.PackageTask_src
ssis_t.TblTask_ExecutePackage <.. ssis.PackageTask_src
ssis_t.TblTask_Script <.. ssis.PackageTask_src
ssis_t.TblTask_Sql <.. ssis.PackageTask_src

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_30_0_objectref[]

=== PlantUML 0 30 ObjectRef

// tag::puml_entity_0_30_objectref[]
[plantuml, entity_0_30_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:docs.ssis_adoc.adoc[]" as docs.ssis_Adoc << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageBasename** : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_adoc_t.adoc[]" as docs.ssis_Adoc_T << U >> {
  - **AntoraModule** : (varchar(50))
  - **PackageBasename** : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_pumlpackage.adoc[]" as docs.ssis_PumlPackage << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_pumlpartialtaskcomponent.adoc[]" as docs.ssis_PumlPartialTaskComponent << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_task.adoc[]" as docs.ssis_Task << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_tasklist.adoc[]" as docs.ssis_TaskList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport.adoc[]" as docs.usp_AntoraExport << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_ssispartialscontent.adoc[]" as docs.usp_AntoraExport_SsisPartialsContent << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_ssis_adoc_t.adoc[]" as docs.usp_PERSIST_ssis_Adoc_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask.adoc[]" as ssis.PackageTask << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_levellaglead.adoc[]" as ssis.PackageTask_LevelLagLead << V >> {
  --
}

docs.ssis_Adoc <.. docs.ssis_Adoc_T
docs.ssis_Adoc <.. docs.usp_PERSIST_ssis_Adoc_T
docs.ssis_Adoc_T <.. docs.usp_AntoraExport_SsisPartialsContent
docs.ssis_Adoc_T <.. docs.usp_PERSIST_ssis_Adoc_T
docs.ssis_PumlPackage <.. docs.ssis_Adoc
docs.ssis_PumlPartialTaskComponent <.. docs.ssis_PumlPackage
docs.ssis_TaskList <.. docs.ssis_Adoc
docs.usp_AntoraExport_SsisPartialsContent <.. docs.usp_AntoraExport
docs.usp_PERSIST_ssis_Adoc_T <.. docs.usp_AntoraExport_SsisPartialsContent
ssis.PackageTask <.. docs.ssis_TaskList
ssis.PackageTask <.. ssis.PackageTask_LevelLagLead
ssis.PackageTask <.. docs.ssis_Task
ssis.PackageTask_LevelLagLead <.. docs.ssis_PumlPartialTaskComponent

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_0_30_objectref[]

=== PlantUML 1 1 ColumnRef

// tag::puml_entity_1_1_colref[]
[plantuml, entity_1_1_colref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:docs.ssis_task.adoc[]" as docs.ssis_Task << V >> {
  AdocFilename : (nvarchar(4000))
  - AntoraModule : (varchar(50))
  - PackageName : (varchar(200))
  - TaskContent : (nvarchar(max))
  - TaskPath : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_tasklist.adoc[]" as docs.ssis_TaskList << V >> {
  - AntoraModule : (varchar(50))
  - PackageName : (varchar(200))
  TaskList : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask.adoc[]" as ssis.PackageTask << U >> {
  - AntoraModule : (varchar(50))
  - ControlFlowDetailsRowID : (int)
  DelayValidationPropertyValue : (varchar(100))
  ExecutedPackageName : (varchar(1000))
  ExecutePackageConnection : (varchar(1000))
  ExecutePackageExpression : (varchar(1000))
  ExpressionValue : (varchar(5000))
  IsDisabled : (varchar(10))
  - PackageName : (varchar(200))
  Script : (varchar(max))
  SqlConnection : (uniqueidentifier)
  SqlStatementSource : (nvarchar(max))
  TaskDescription : (varchar(max))
  - TaskName : (varchar(2000))
  - TaskPath : (varchar(8000))
  TaskType : (varchar(5000))
  # PackageBasename : (varchar(8000))
  # TaskPathLevel : (int)
  # TaskPathParent : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_levellaglead.adoc[]" as ssis.PackageTask_LevelLagLead << V >> {
  - AntoraModule : (varchar(50))
  PackageBasename : (varchar(8000))
  - PackageName : (varchar(200))
  - TaskName : (varchar(2000))
  - TaskPath : (varchar(8000))
  TaskPathLevel : (int)
  TaskPathLevelLag : (int)
  TaskPathLevelLead : (int)
  TaskPathParent : (varchar(8000))
  TaskType : (varchar(5000))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_tgt.adoc[]" as ssis.PackageTask_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  - **PackageName** : (varchar(200))
  - **TaskPath** : (varchar(8000))
  - ControlFlowDetailsRowID : (int)
  DelayValidationPropertyValue : (varchar(100))
  ExecutedPackageName : (varchar(1000))
  ExecutePackageConnection : (varchar(1000))
  ExecutePackageExpression : (varchar(1000))
  ExpressionValue : (varchar(5000))
  IsDisabled : (varchar(10))
  Script : (varchar(max))
  SqlConnection : (uniqueidentifier)
  SqlStatementSource : (nvarchar(max))
  TaskDescription : (varchar(max))
  - TaskName : (varchar(2000))
  TaskType : (varchar(5000))
  --
}

ssis.PackageTask <.. docs.ssis_TaskList
ssis.PackageTask <.. ssis.PackageTask_LevelLagLead
ssis.PackageTask <.. docs.ssis_Task
ssis.PackageTask_tgt <.. ssis.PackageTask
"ssis.PackageTask::AntoraModule" <-- "ssis.PackageTask_tgt::AntoraModule"
"ssis.PackageTask::AntoraModule" <-- "docs.ssis_TaskList::AntoraModule"
"ssis.PackageTask::AntoraModule" <-- "docs.ssis_Task::AntoraModule"
"ssis.PackageTask::AntoraModule" <-- "ssis.PackageTask_LevelLagLead::AntoraModule"
"ssis.PackageTask::ControlFlowDetailsRowID" <-- "ssis.PackageTask_tgt::ControlFlowDetailsRowID"
"ssis.PackageTask::DelayValidationPropertyValue" <-- "ssis.PackageTask_tgt::DelayValidationPropertyValue"
"ssis.PackageTask::ExecutedPackageName" <-- "ssis.PackageTask_tgt::ExecutedPackageName"
"ssis.PackageTask::ExecutePackageConnection" <-- "ssis.PackageTask_tgt::ExecutePackageConnection"
"ssis.PackageTask::ExecutePackageExpression" <-- "ssis.PackageTask_tgt::ExecutePackageExpression"
"ssis.PackageTask::ExpressionValue" <-- "ssis.PackageTask_tgt::ExpressionValue"
"ssis.PackageTask::IsDisabled" <-- "ssis.PackageTask_tgt::IsDisabled"
"ssis.PackageTask::PackageBasename" <-- "ssis.PackageTask_LevelLagLead::PackageBasename"
"ssis.PackageTask::PackageName" <-- "ssis.PackageTask::PackageBasename"
"ssis.PackageTask::PackageName" <-- "docs.ssis_Task::PackageName"
"ssis.PackageTask::PackageName" <-- "ssis.PackageTask_LevelLagLead::PackageName"
"ssis.PackageTask::PackageName" <-- "ssis.PackageTask_tgt::PackageName"
"ssis.PackageTask::PackageName" <-- "docs.ssis_TaskList::PackageName"
"ssis.PackageTask::Script" <-- "ssis.PackageTask_tgt::Script"
"ssis.PackageTask::SqlConnection" <-- "ssis.PackageTask_tgt::SqlConnection"
"ssis.PackageTask::SqlStatementSource" <-- "ssis.PackageTask_tgt::SqlStatementSource"
"ssis.PackageTask::TaskDescription" <-- "ssis.PackageTask_tgt::TaskDescription"
"ssis.PackageTask::TaskName" <-- "ssis.PackageTask_tgt::TaskName"
"ssis.PackageTask::TaskName" <-- "ssis.PackageTask_LevelLagLead::TaskName"
"ssis.PackageTask::TaskPath" <-- "ssis.PackageTask_LevelLagLead::TaskPath"
"ssis.PackageTask::TaskPath" <-- "ssis.PackageTask::TaskPathLevel"
"ssis.PackageTask::TaskPath" <-- "ssis.PackageTask::TaskPathParent"
"ssis.PackageTask::TaskPath" <-- "docs.ssis_Task::TaskPath"
"ssis.PackageTask::TaskPath" <-- "ssis.PackageTask_tgt::TaskPath"
"ssis.PackageTask::TaskPathLevel" <-- "ssis.PackageTask_LevelLagLead::TaskPathLevel"
"ssis.PackageTask::TaskPathParent" <-- "ssis.PackageTask_LevelLagLead::TaskPathParent"
"ssis.PackageTask::TaskType" <-- "ssis.PackageTask_LevelLagLead::TaskType"
"ssis.PackageTask::TaskType" <-- "ssis.PackageTask_tgt::TaskType"

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_colref[]


== sql_modules_definition

// tag::sql_modules_definition[]
[%collapsible]
=======
[source,sql,numbered,indent=0]
----

----
=======
// end::sql_modules_definition[]


