// tag::HeaderFullDisplayName[]
= ssis_t.TblTask_Dft_Component - U
// end::HeaderFullDisplayName[]

== existing_properties

// tag::existing_properties[]

:ExistsProperty--antorareferencinglist:
:ExistsProperty--is_repo_managed:
:ExistsProperty--is_ssas:
:ExistsProperty--pk_index_guid:
:ExistsProperty--pk_indexpatterncolumndatatype:
:ExistsProperty--pk_indexpatterncolumnname:
:ExistsProperty--FK:
:ExistsProperty--AntoraIndexList:
:ExistsProperty--Columns:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
B0DCAD7F-F73E-EC11-852D-A81E8446D5B0
// end::RepoObject_guid[]

== RepoObject_FullDisplayName2

// tag::RepoObject_FullDisplayName2[]
ssis_t.TblTask_Dft_Component
// end::RepoObject_FullDisplayName2[]

== SysObject_type

// tag::SysObject_type[]
U 
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
user table
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
110675492
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2021-11-06 12:38:30
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]
[discrete]
== _


[#column-dftcomponentid]
=== DftComponentId

[cols="d,8a,m,m,m"]
|===
|1
|*DftComponentId*
|int
|NOT NULL
|(1,1)
|===

.Referencing Columns
--
* xref:ssis_t.tbltask_dft_component_inputs_externalmetadatacolumn_src.adoc#column-dftcomponentid[+ssis_t.TblTask_Dft_Component_inputs_externalMetadataColumn_src.DftComponentId+]
* xref:ssis_t.tbltask_dft_component_inputs_inputcolumn_src.adoc#column-dftcomponentid[+ssis_t.TblTask_Dft_Component_inputs_inputColumn_src.DftComponentId+]
* xref:ssis_t.tbltask_dft_component_inputs_src.adoc#column-dftcomponentid[+ssis_t.TblTask_Dft_Component_inputs_src.DftComponentId+]
* xref:ssis_t.tbltask_dft_component_outputs_externalmetadatacolumn_src.adoc#column-dftcomponentid[+ssis_t.TblTask_Dft_Component_outputs_externalMetadataColumn_src.DftComponentId+]
* xref:ssis_t.tbltask_dft_component_outputs_outputcolumn_src.adoc#column-dftcomponentid[+ssis_t.TblTask_Dft_Component_outputs_outputColumn_src.DftComponentId+]
* xref:ssis_t.tbltask_dft_component_outputs_src.adoc#column-dftcomponentid[+ssis_t.TblTask_Dft_Component_outputs_src.DftComponentId+]
--


[#column-accessmode]
=== AccessMode

[cols="d,8a,m,m,m"]
|===
|
|AccessMode
|varchar(max)
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_src.adoc#column-componentunderlineaccessmode[+ssis.PackageTask_Dft_Component_src.Component_AccessMode+]
--


[#column-alwaysusedefaultcodepage]
=== AlwaysUseDefaultCodePage

[cols="d,8a,m,m,m"]
|===
|
|AlwaysUseDefaultCodePage
|varchar(max)
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_src.adoc#column-componentunderlinealwaysusedefaultcodepage[+ssis.PackageTask_Dft_Component_src.Component_AlwaysUseDefaultCodePage+]
--


[#column-commandtimeout]
=== CommandTimeout

[cols="d,8a,m,m,m"]
|===
|
|CommandTimeout
|int
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_src.adoc#column-componentunderlinecommandtimeout[+ssis.PackageTask_Dft_Component_src.Component_CommandTimeout+]
--


[#column-componentclassid]
=== componentClassID

[cols="d,8a,m,m,m"]
|===
|
|componentClassID
|varchar(max)
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_src.adoc#column-componentunderlinecomponentclassid[+ssis.PackageTask_Dft_Component_src.Component_componentClassID+]
--


[#column-connectionunderlinedescription]
=== Connection_description

[cols="d,8a,m,m,m"]
|===
|
|Connection_description
|varchar(max)
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_src.adoc#column-componentunderlineconnectionunderlinedescription[+ssis.PackageTask_Dft_Component_src.Component_Connection_description+]
--


[#column-connectionunderlinename]
=== Connection_name

[cols="d,8a,m,m,m"]
|===
|
|Connection_name
|varchar(max)
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_src.adoc#column-componentunderlineconnectionunderlinename[+ssis.PackageTask_Dft_Component_src.Component_Connection_name+]
--


[#column-connectionunderlinerefid]
=== Connection_refId

[cols="d,8a,m,m,m"]
|===
|
|Connection_refId
|varchar(max)
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_src.adoc#column-componentunderlineconnectionunderlinerefid[+ssis.PackageTask_Dft_Component_src.Component_Connection_refId+]
--


[#column-connectionmanagerid]
=== connectionManagerID

[cols="d,8a,m,m,m"]
|===
|
|connectionManagerID
|varchar(max)
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_src.adoc#column-componentunderlineconnectionmanagerid[+ssis.PackageTask_Dft_Component_src.Component_connectionManagerID+]
--


[#column-connectionmanagerrefid]
=== connectionManagerRefId

[cols="d,8a,m,m,m"]
|===
|
|connectionManagerRefId
|varchar(max)
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_src.adoc#column-componentunderlineconnectionmanagerrefid[+ssis.PackageTask_Dft_Component_src.Component_connectionManagerRefId+]
--


[#column-contactinfo]
=== ContactInfo

[cols="d,8a,m,m,m"]
|===
|
|ContactInfo
|varchar(max)
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_src.adoc#column-componentunderlinecontactinfo[+ssis.PackageTask_Dft_Component_src.Component_ContactInfo+]
--


[#column-controlflowdetailsrowid]
=== ControlFlowDetailsRowID

[cols="d,8a,m,m,m"]
|===
|
|ControlFlowDetailsRowID
|int
|NOT NULL
|
|===

.Referencing Columns
--
* xref:ssis_t.tbltask_dft_component_inputs_externalmetadatacolumn_src.adoc#column-controlflowdetailsrowid[+ssis_t.TblTask_Dft_Component_inputs_externalMetadataColumn_src.ControlFlowDetailsRowID+]
* xref:ssis_t.tbltask_dft_component_inputs_inputcolumn_src.adoc#column-controlflowdetailsrowid[+ssis_t.TblTask_Dft_Component_inputs_inputColumn_src.ControlFlowDetailsRowID+]
* xref:ssis_t.tbltask_dft_component_inputs_src.adoc#column-controlflowdetailsrowid[+ssis_t.TblTask_Dft_Component_inputs_src.ControlFlowDetailsRowID+]
* xref:ssis_t.tbltask_dft_component_outputs_externalmetadatacolumn_src.adoc#column-controlflowdetailsrowid[+ssis_t.TblTask_Dft_Component_outputs_externalMetadataColumn_src.ControlFlowDetailsRowID+]
* xref:ssis_t.tbltask_dft_component_outputs_outputcolumn_src.adoc#column-controlflowdetailsrowid[+ssis_t.TblTask_Dft_Component_outputs_outputColumn_src.ControlFlowDetailsRowID+]
* xref:ssis_t.tbltask_dft_component_outputs_src.adoc#column-controlflowdetailsrowid[+ssis_t.TblTask_Dft_Component_outputs_src.ControlFlowDetailsRowID+]
--


[#column-defaultcodepage]
=== DefaultCodePage

[cols="d,8a,m,m,m"]
|===
|
|DefaultCodePage
|int
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_src.adoc#column-componentunderlinedefaultcodepage[+ssis.PackageTask_Dft_Component_src.Component_DefaultCodePage+]
--


[#column-description]
=== description

[cols="d,8a,m,m,m"]
|===
|
|description
|varchar(max)
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_src.adoc#column-componentunderlinedescription[+ssis.PackageTask_Dft_Component_src.Component_description+]
--


[#column-fastloadkeepidentity]
=== FastLoadKeepIdentity

[cols="d,8a,m,m,m"]
|===
|
|FastLoadKeepIdentity
|bit
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_src.adoc#column-componentunderlinefastloadkeepidentity[+ssis.PackageTask_Dft_Component_src.Component_FastLoadKeepIdentity+]
--


[#column-fastloadkeepnulls]
=== FastLoadKeepNulls

[cols="d,8a,m,m,m"]
|===
|
|FastLoadKeepNulls
|bit
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_src.adoc#column-componentunderlinefastloadkeepnulls[+ssis.PackageTask_Dft_Component_src.Component_FastLoadKeepNulls+]
--


[#column-fastloadmaxinsertcommitsize]
=== FastLoadMaxInsertCommitSize

[cols="d,8a,m,m,m"]
|===
|
|FastLoadMaxInsertCommitSize
|int
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_src.adoc#column-componentunderlinefastloadmaxinsertcommitsize[+ssis.PackageTask_Dft_Component_src.Component_FastLoadMaxInsertCommitSize+]
--


[#column-fastloadoptions]
=== FastLoadOptions

[cols="d,8a,m,m,m"]
|===
|
|FastLoadOptions
|varchar(max)
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_src.adoc#column-componentunderlinefastloadoptions[+ssis.PackageTask_Dft_Component_src.Component_FastLoadOptions+]
--


[#column-inputsqry]
=== inputsQry

[cols="d,8a,m,m,m"]
|===
|
|inputsQry
|xml
|NULL
|
|===


[#column-issortedproperty]
=== IsSortedProperty

[cols="d,8a,m,m,m"]
|===
|
|IsSortedProperty
|varchar(10)
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_src.adoc#column-componentunderlineissortedproperty[+ssis.PackageTask_Dft_Component_src.Component_IsSortedProperty+]
--


[#column-name]
=== name

[cols="d,8a,m,m,m"]
|===
|
|name
|varchar(max)
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_src.adoc#column-componentunderlinename[+ssis.PackageTask_Dft_Component_src.Component_name+]
--


[#column-openrowset]
=== OpenRowset

[cols="d,8a,m,m,m"]
|===
|
|OpenRowset
|varchar(max)
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_src.adoc#column-componentunderlineopenrowset[+ssis.PackageTask_Dft_Component_src.Component_OpenRowset+]
--


[#column-openrowsetvariable]
=== OpenRowsetVariable

[cols="d,8a,m,m,m"]
|===
|
|OpenRowsetVariable
|varchar(max)
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_src.adoc#column-componentunderlineopenrowsetvariable[+ssis.PackageTask_Dft_Component_src.Component_OpenRowsetVariable+]
--


[#column-outputsqry]
=== outputsQry

[cols="d,8a,m,m,m"]
|===
|
|outputsQry
|xml
|NULL
|
|===


[#column-parametermapping]
=== ParameterMapping

[cols="d,8a,m,m,m"]
|===
|
|ParameterMapping
|varchar(max)
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_src.adoc#column-componentunderlineparametermapping[+ssis.PackageTask_Dft_Component_src.Component_ParameterMapping+]
--


[#column-refid]
=== refId

[cols="d,8a,m,m,m"]
|===
|
|refId
|varchar(max)
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_src.adoc#column-componentunderlinerefid[+ssis.PackageTask_Dft_Component_src.Component_refId+]
* xref:ssis_t.tbltask_dft_component_inputs_externalmetadatacolumn_src.adoc#column-refid[+ssis_t.TblTask_Dft_Component_inputs_externalMetadataColumn_src.refId+]
* xref:ssis_t.tbltask_dft_component_inputs_inputcolumn_src.adoc#column-refid[+ssis_t.TblTask_Dft_Component_inputs_inputColumn_src.refId+]
* xref:ssis_t.tbltask_dft_component_inputs_src.adoc#column-refid[+ssis_t.TblTask_Dft_Component_inputs_src.refId+]
* xref:ssis_t.tbltask_dft_component_outputs_externalmetadatacolumn_src.adoc#column-refid[+ssis_t.TblTask_Dft_Component_outputs_externalMetadataColumn_src.refId+]
* xref:ssis_t.tbltask_dft_component_outputs_outputcolumn_src.adoc#column-refid[+ssis_t.TblTask_Dft_Component_outputs_outputColumn_src.refId+]
* xref:ssis_t.tbltask_dft_component_outputs_src.adoc#column-refid[+ssis_t.TblTask_Dft_Component_outputs_src.refId+]
--


[#column-rowid]
=== RowID

[cols="d,8a,m,m,m"]
|===
|
|RowID
|int
|NULL
|
|===

.Referencing Columns
--
* xref:ssis_t.tbltask_dft_component_inputs_externalmetadatacolumn_src.adoc#column-rowid[+ssis_t.TblTask_Dft_Component_inputs_externalMetadataColumn_src.RowID+]
* xref:ssis_t.tbltask_dft_component_inputs_inputcolumn_src.adoc#column-rowid[+ssis_t.TblTask_Dft_Component_inputs_inputColumn_src.RowID+]
* xref:ssis_t.tbltask_dft_component_inputs_src.adoc#column-rowid[+ssis_t.TblTask_Dft_Component_inputs_src.RowID+]
* xref:ssis_t.tbltask_dft_component_outputs_externalmetadatacolumn_src.adoc#column-rowid[+ssis_t.TblTask_Dft_Component_outputs_externalMetadataColumn_src.RowID+]
* xref:ssis_t.tbltask_dft_component_outputs_outputcolumn_src.adoc#column-rowid[+ssis_t.TblTask_Dft_Component_outputs_outputColumn_src.RowID+]
* xref:ssis_t.tbltask_dft_component_outputs_src.adoc#column-rowid[+ssis_t.TblTask_Dft_Component_outputs_src.RowID+]
--


[#column-sqlcommand]
=== SqlCommand

[cols="d,8a,m,m,m"]
|===
|
|SqlCommand
|varchar(max)
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_src.adoc#column-componentunderlinesqlcommand[+ssis.PackageTask_Dft_Component_src.Component_SqlCommand+]
--


[#column-sqlcommandvariable]
=== SqlCommandVariable

[cols="d,8a,m,m,m"]
|===
|
|SqlCommandVariable
|varchar(max)
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_src.adoc#column-componentunderlinesqlcommandvariable[+ssis.PackageTask_Dft_Component_src.Component_SqlCommandVariable+]
--


[#column-variablename]
=== VariableName

[cols="d,8a,m,m,m"]
|===
|
|VariableName
|varchar(max)
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_src.adoc#column-componentunderlinevariablename[+ssis.PackageTask_Dft_Component_src.Component_VariableName+]
--


// end::AntoraColumnDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]
|1
|*<<column-dftcomponentid>>*
|int
|NOT NULL
|(1,1)






























// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]

|
|<<column-accessmode>>
|varchar(max)
|NULL
|

|
|<<column-alwaysusedefaultcodepage>>
|varchar(max)
|NULL
|

|
|<<column-commandtimeout>>
|int
|NULL
|

|
|<<column-componentclassid>>
|varchar(max)
|NULL
|

|
|<<column-connectionunderlinedescription>>
|varchar(max)
|NULL
|

|
|<<column-connectionunderlinename>>
|varchar(max)
|NULL
|

|
|<<column-connectionunderlinerefid>>
|varchar(max)
|NULL
|

|
|<<column-connectionmanagerid>>
|varchar(max)
|NULL
|

|
|<<column-connectionmanagerrefid>>
|varchar(max)
|NULL
|

|
|<<column-contactinfo>>
|varchar(max)
|NULL
|

|
|<<column-controlflowdetailsrowid>>
|int
|NOT NULL
|

|
|<<column-defaultcodepage>>
|int
|NULL
|

|
|<<column-description>>
|varchar(max)
|NULL
|

|
|<<column-fastloadkeepidentity>>
|bit
|NULL
|

|
|<<column-fastloadkeepnulls>>
|bit
|NULL
|

|
|<<column-fastloadmaxinsertcommitsize>>
|int
|NULL
|

|
|<<column-fastloadoptions>>
|varchar(max)
|NULL
|

|
|<<column-inputsqry>>
|xml
|NULL
|

|
|<<column-issortedproperty>>
|varchar(10)
|NULL
|

|
|<<column-name>>
|varchar(max)
|NULL
|

|
|<<column-openrowset>>
|varchar(max)
|NULL
|

|
|<<column-openrowsetvariable>>
|varchar(max)
|NULL
|

|
|<<column-outputsqry>>
|xml
|NULL
|

|
|<<column-parametermapping>>
|varchar(max)
|NULL
|

|
|<<column-refid>>
|varchar(max)
|NULL
|

|
|<<column-rowid>>
|int
|NULL
|

|
|<<column-sqlcommand>>
|varchar(max)
|NULL
|

|
|<<column-sqlcommandvariable>>
|varchar(max)
|NULL
|

|
|<<column-variablename>>
|varchar(max)
|NULL
|

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

[#index-pkunderlinetbltaskunderlinedftunderlinecomponent]
=== PK_TblTask_Dft_Component

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-DftComponentId>>; int
--
* PK, Unique, Real: 1, 1, 1

// end::AntoraIndexList[]

== AntoraMeasureDetails

// tag::AntoraMeasureDetails[]

// end::AntoraMeasureDetails[]

== AntoraMeasureDescriptions



== AntoraParameterList

// tag::AntoraParameterList[]

// end::AntoraParameterList[]

== AntoraXrefCulturesList

// tag::AntoraXrefCulturesList[]
* xref:dhw:sqldb:ssis_t.tbltask_dft_component.adoc[] - 
// end::AntoraXrefCulturesList[]

== cultures_count

// tag::cultures_count[]
1
// end::cultures_count[]

== Other tags

source: property.RepoObjectProperty_cross As rop_cross


=== additional_reference_csv

// tag::additional_reference_csv[]

// end::additional_reference_csv[]


=== AdocUspSteps

// tag::adocuspsteps[]

// end::adocuspsteps[]


=== AntoraReferencedList

// tag::antorareferencedlist[]

// end::antorareferencedlist[]


=== AntoraReferencingList

// tag::antorareferencinglist[]
* xref:dhw:sqldb:ssis.packagetask_dft_component_src.adoc[]
* xref:dhw:sqldb:ssis_t.tbltask_dft_component_inputs_externalmetadatacolumn_src.adoc[]
* xref:dhw:sqldb:ssis_t.tbltask_dft_component_inputs_inputcolumn_src.adoc[]
* xref:dhw:sqldb:ssis_t.tbltask_dft_component_inputs_src.adoc[]
* xref:dhw:sqldb:ssis_t.tbltask_dft_component_outputs_externalmetadatacolumn_src.adoc[]
* xref:dhw:sqldb:ssis_t.tbltask_dft_component_outputs_outputcolumn_src.adoc[]
* xref:dhw:sqldb:ssis_t.tbltask_dft_component_outputs_src.adoc[]
* xref:dhw:sqldb:ssis_t.usp_getpackagedetails.adoc[]
// end::antorareferencinglist[]


=== Description

// tag::description[]

// end::description[]


=== exampleUsage

// tag::exampleusage[]

// end::exampleusage[]


=== exampleUsage_2

// tag::exampleusage_2[]

// end::exampleusage_2[]


=== exampleUsage_3

// tag::exampleusage_3[]

// end::exampleusage_3[]


=== exampleUsage_4

// tag::exampleusage_4[]

// end::exampleusage_4[]


=== exampleUsage_5

// tag::exampleusage_5[]

// end::exampleusage_5[]


=== exampleWrong_Usage

// tag::examplewrong_usage[]

// end::examplewrong_usage[]


=== has_execution_plan_issue

// tag::has_execution_plan_issue[]

// end::has_execution_plan_issue[]


=== has_get_referenced_issue

// tag::has_get_referenced_issue[]

// end::has_get_referenced_issue[]


=== has_history

// tag::has_history[]

// end::has_history[]


=== has_history_columns

// tag::has_history_columns[]

// end::has_history_columns[]


=== InheritanceType

// tag::inheritancetype[]

// end::inheritancetype[]


=== is_persistence

// tag::is_persistence[]

// end::is_persistence[]


=== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]

// end::is_persistence_check_duplicate_per_pk[]


=== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]

// end::is_persistence_check_for_empty_source[]


=== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]

// end::is_persistence_delete_changed[]


=== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]

// end::is_persistence_delete_missing[]


=== is_persistence_insert

// tag::is_persistence_insert[]

// end::is_persistence_insert[]


=== is_persistence_truncate

// tag::is_persistence_truncate[]

// end::is_persistence_truncate[]


=== is_persistence_update_changed

// tag::is_persistence_update_changed[]

// end::is_persistence_update_changed[]


=== is_repo_managed

// tag::is_repo_managed[]
0
// end::is_repo_managed[]


=== is_ssas

// tag::is_ssas[]
0
// end::is_ssas[]


=== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


=== MS_Description

// tag::ms_description[]

// end::ms_description[]


=== persistence_source_RepoObject_fullname

// tag::persistence_source_repoobject_fullname[]

// end::persistence_source_repoobject_fullname[]


=== persistence_source_RepoObject_fullname2

// tag::persistence_source_repoobject_fullname2[]

// end::persistence_source_repoobject_fullname2[]


=== persistence_source_RepoObject_guid

// tag::persistence_source_repoobject_guid[]

// end::persistence_source_repoobject_guid[]


=== persistence_source_RepoObject_xref

// tag::persistence_source_repoobject_xref[]

// end::persistence_source_repoobject_xref[]


=== pk_index_guid

// tag::pk_index_guid[]
B1DCAD7F-F73E-EC11-852D-A81E8446D5B0
// end::pk_index_guid[]


=== pk_IndexPatternColumnDatatype

// tag::pk_indexpatterncolumndatatype[]
int
// end::pk_indexpatterncolumndatatype[]


=== pk_IndexPatternColumnName

// tag::pk_indexpatterncolumnname[]
DftComponentId
// end::pk_indexpatterncolumnname[]


=== pk_IndexSemanticGroup

// tag::pk_indexsemanticgroup[]

// end::pk_indexsemanticgroup[]


=== ReferencedObjectList

// tag::referencedobjectlist[]

// end::referencedobjectlist[]


=== usp_persistence_RepoObject_guid

// tag::usp_persistence_repoobject_guid[]

// end::usp_persistence_repoobject_guid[]


=== UspExamples

// tag::uspexamples[]

// end::uspexamples[]


=== uspgenerator_usp_id

// tag::uspgenerator_usp_id[]

// end::uspgenerator_usp_id[]


=== UspParameters

// tag::uspparameters[]

// end::uspparameters[]

== Boolean Attributes

source: property.RepoObjectProperty WHERE property_int = 1

// tag::boolean_attributes[]


// end::boolean_attributes[]

== PlantUML diagrams

=== PlantUML Entity

// tag::puml_entity[]
[plantuml, entity-{docname}, svg, subs=macros]
....
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis_t.tbltask_dft_component.adoc[]" as ssis_t.TblTask_Dft_Component << U >> {
  - **DftComponentId** : (int)
  AccessMode : (varchar(max))
  AlwaysUseDefaultCodePage : (varchar(max))
  CommandTimeout : (int)
  componentClassID : (varchar(max))
  Connection_description : (varchar(max))
  Connection_name : (varchar(max))
  Connection_refId : (varchar(max))
  connectionManagerID : (varchar(max))
  connectionManagerRefId : (varchar(max))
  ContactInfo : (varchar(max))
  - ControlFlowDetailsRowID : (int)
  DefaultCodePage : (int)
  description : (varchar(max))
  FastLoadKeepIdentity : (bit)
  FastLoadKeepNulls : (bit)
  FastLoadMaxInsertCommitSize : (int)
  FastLoadOptions : (varchar(max))
  inputsQry : (xml)
  IsSortedProperty : (varchar(10))
  name : (varchar(max))
  OpenRowset : (varchar(max))
  OpenRowsetVariable : (varchar(max))
  outputsQry : (xml)
  ParameterMapping : (varchar(max))
  refId : (varchar(max))
  RowID : (int)
  SqlCommand : (varchar(max))
  SqlCommandVariable : (varchar(max))
  VariableName : (varchar(max))
  --
}
....

// end::puml_entity[]

=== PlantUML Entity 1 1 FK

// tag::puml_entity_1_1_fk[]
[plantuml, entity_1_1_fk-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis_t.tbltask_dft_component.adoc[]" as ssis_t.TblTask_Dft_Component << U >> {
**PK_TblTask_Dft_Component**

..
DftComponentId; int
}



footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_fk[]

=== PlantUML 1 1 ObjectRef

// tag::puml_entity_1_1_objectref[]
[plantuml, entity_1_1_objectref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_src.adoc[]" as ssis.PackageTask_Dft_Component_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Component_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_dft_component.adoc[]" as ssis_t.TblTask_Dft_Component << U >> {
  - **DftComponentId** : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_dft_component_inputs_externalmetadatacolumn_src.adoc[]" as ssis_t.TblTask_Dft_Component_inputs_externalMetadataColumn_src << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_dft_component_inputs_inputcolumn_src.adoc[]" as ssis_t.TblTask_Dft_Component_inputs_inputColumn_src << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_dft_component_inputs_src.adoc[]" as ssis_t.TblTask_Dft_Component_inputs_src << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_dft_component_outputs_externalmetadatacolumn_src.adoc[]" as ssis_t.TblTask_Dft_Component_outputs_externalMetadataColumn_src << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_dft_component_outputs_outputcolumn_src.adoc[]" as ssis_t.TblTask_Dft_Component_outputs_outputColumn_src << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_dft_component_outputs_src.adoc[]" as ssis_t.TblTask_Dft_Component_outputs_src << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.usp_getpackagedetails.adoc[]" as ssis_t.usp_GetPackageDetails << P >> {
  --
}

ssis_t.TblTask_Dft_Component <.. ssis_t.usp_GetPackageDetails
ssis_t.TblTask_Dft_Component <.. ssis_t.TblTask_Dft_Component_outputs_outputColumn_src
ssis_t.TblTask_Dft_Component <.. ssis_t.TblTask_Dft_Component_outputs_externalMetadataColumn_src
ssis_t.TblTask_Dft_Component <.. ssis_t.TblTask_Dft_Component_inputs_inputColumn_src
ssis_t.TblTask_Dft_Component <.. ssis_t.TblTask_Dft_Component_inputs_externalMetadataColumn_src
ssis_t.TblTask_Dft_Component <.. ssis.PackageTask_Dft_Component_src
ssis_t.TblTask_Dft_Component <.. ssis_t.TblTask_Dft_Component_outputs_src
ssis_t.TblTask_Dft_Component <.. ssis_t.TblTask_Dft_Component_inputs_src

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_objectref[]

=== PlantUML 30 0 ObjectRef

// tag::puml_entity_30_0_objectref[]
[plantuml, entity_30_0_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis_t.tbltask_dft_component.adoc[]" as ssis_t.TblTask_Dft_Component << U >> {
  - **DftComponentId** : (int)
  --
}



footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_30_0_objectref[]

=== PlantUML 0 30 ObjectRef

// tag::puml_entity_0_30_objectref[]
[plantuml, entity_0_30_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:docs.ssis_adoc.adoc[]" as docs.ssis_Adoc << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageBasename** : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_adoc_t.adoc[]" as docs.ssis_Adoc_T << U >> {
  - **AntoraModule** : (varchar(50))
  - **PackageBasename** : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_dfttaskcomponentinputcolumnlist.adoc[]" as docs.ssis_DftTaskComponentInputColumnList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_dfttaskcomponentinputlist.adoc[]" as docs.ssis_DftTaskComponentInputList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_dfttaskcomponentlist.adoc[]" as docs.ssis_DftTaskComponentList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_dfttaskcomponentoutputcolumnlist.adoc[]" as docs.ssis_DftTaskComponentOutputColumnList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_dfttaskcomponentoutputlist.adoc[]" as docs.ssis_DftTaskComponentOutputList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_pumldfttask.adoc[]" as docs.ssis_PumlDftTask << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_pumlpartialdftcomponent.adoc[]" as docs.ssis_PumlPartialDftComponent << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_task.adoc[]" as docs.ssis_Task << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_tasklist.adoc[]" as docs.ssis_TaskList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport.adoc[]" as docs.usp_AntoraExport << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_ssispartialscontent.adoc[]" as docs.usp_AntoraExport_SsisPartialsContent << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_ssis_adoc_t.adoc[]" as docs.usp_PERSIST_ssis_Adoc_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component.adoc[]" as ssis.PackageTask_Dft_Component << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_input.adoc[]" as ssis.PackageTask_Dft_Component_input << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_input_externalmetadatacolumn.adoc[]" as ssis.PackageTask_Dft_Component_input_externalMetadataColumn << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_input_externalmetadatacolumn_src.adoc[]" as ssis.PackageTask_Dft_Component_input_externalMetadataColumn_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Column_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_input_externalmetadatacolumn_tgt.adoc[]" as ssis.PackageTask_Dft_Component_input_externalMetadataColumn_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Column_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_input_inputcolumn.adoc[]" as ssis.PackageTask_Dft_Component_input_inputColumn << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_input_inputcolumn_src.adoc[]" as ssis.PackageTask_Dft_Component_input_inputColumn_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Column_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_input_inputcolumn_tgt.adoc[]" as ssis.PackageTask_Dft_Component_input_inputColumn_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Column_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_input_src.adoc[]" as ssis.PackageTask_Dft_Component_input_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **input_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_input_tgt.adoc[]" as ssis.PackageTask_Dft_Component_input_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **input_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_output.adoc[]" as ssis.PackageTask_Dft_Component_output << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_output_externalmetadatacolumn.adoc[]" as ssis.PackageTask_Dft_Component_output_externalMetadataColumn << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_output_externalmetadatacolumn_src.adoc[]" as ssis.PackageTask_Dft_Component_output_externalMetadataColumn_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Column_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_output_externalmetadatacolumn_tgt.adoc[]" as ssis.PackageTask_Dft_Component_output_externalMetadataColumn_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Column_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_output_outputcolumn.adoc[]" as ssis.PackageTask_Dft_Component_output_outputcolumn << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_output_outputcolumn_src.adoc[]" as ssis.PackageTask_Dft_Component_output_outputcolumn_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Column_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_output_outputcolumn_tgt.adoc[]" as ssis.PackageTask_Dft_Component_output_outputColumn_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Column_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_output_src.adoc[]" as ssis.PackageTask_Dft_Component_output_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **output_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_output_tgt.adoc[]" as ssis.PackageTask_Dft_Component_output_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **output_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_src.adoc[]" as ssis.PackageTask_Dft_Component_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Component_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_tgt.adoc[]" as ssis.PackageTask_Dft_Component_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Component_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_import.adoc[]" as ssis.usp_import << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packagetask_dft_component_input_externalmetadatacolumn_tgt.adoc[]" as ssis.usp_PERSIST_PackageTask_Dft_Component_input_externalMetadataColumn_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packagetask_dft_component_input_inputcolumn_tgt.adoc[]" as ssis.usp_PERSIST_PackageTask_Dft_Component_input_inputColumn_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packagetask_dft_component_input_tgt.adoc[]" as ssis.usp_PERSIST_PackageTask_Dft_Component_input_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packagetask_dft_component_output_externalmetadatacolumn_tgt.adoc[]" as ssis.usp_PERSIST_PackageTask_Dft_Component_output_externalMetadataColumn_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packagetask_dft_component_output_outputcolumn_tgt.adoc[]" as ssis.usp_PERSIST_PackageTask_Dft_Component_output_outputColumn_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packagetask_dft_component_output_tgt.adoc[]" as ssis.usp_PERSIST_PackageTask_Dft_Component_output_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packagetask_dft_component_tgt.adoc[]" as ssis.usp_PERSIST_PackageTask_Dft_Component_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_dft_component.adoc[]" as ssis_t.TblTask_Dft_Component << U >> {
  - **DftComponentId** : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_dft_component_inputs_externalmetadatacolumn_src.adoc[]" as ssis_t.TblTask_Dft_Component_inputs_externalMetadataColumn_src << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_dft_component_inputs_inputcolumn_src.adoc[]" as ssis_t.TblTask_Dft_Component_inputs_inputColumn_src << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_dft_component_inputs_src.adoc[]" as ssis_t.TblTask_Dft_Component_inputs_src << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_dft_component_outputs_externalmetadatacolumn_src.adoc[]" as ssis_t.TblTask_Dft_Component_outputs_externalMetadataColumn_src << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_dft_component_outputs_outputcolumn_src.adoc[]" as ssis_t.TblTask_Dft_Component_outputs_outputColumn_src << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_dft_component_outputs_src.adoc[]" as ssis_t.TblTask_Dft_Component_outputs_src << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.usp_getpackagedetails.adoc[]" as ssis_t.usp_GetPackageDetails << P >> {
  --
}

docs.ssis_Adoc <.. docs.usp_PERSIST_ssis_Adoc_T
docs.ssis_Adoc <.. docs.ssis_Adoc_T
docs.ssis_Adoc_T <.. docs.usp_PERSIST_ssis_Adoc_T
docs.ssis_Adoc_T <.. docs.usp_AntoraExport_SsisPartialsContent
docs.ssis_DftTaskComponentInputColumnList <.. docs.ssis_DftTaskComponentInputList
docs.ssis_DftTaskComponentInputList <.. docs.ssis_DftTaskComponentList
docs.ssis_DftTaskComponentList <.. docs.ssis_Task
docs.ssis_DftTaskComponentList <.. docs.ssis_TaskList
docs.ssis_DftTaskComponentOutputColumnList <.. docs.ssis_DftTaskComponentOutputList
docs.ssis_DftTaskComponentOutputList <.. docs.ssis_DftTaskComponentList
docs.ssis_PumlDftTask <.. docs.ssis_TaskList
docs.ssis_PumlDftTask <.. docs.ssis_Task
docs.ssis_PumlPartialDftComponent <.. docs.ssis_PumlDftTask
docs.ssis_PumlPartialDftComponent <.. docs.ssis_DftTaskComponentList
docs.ssis_TaskList <.. docs.ssis_Adoc
docs.usp_AntoraExport_SsisPartialsContent <.. docs.usp_AntoraExport
docs.usp_PERSIST_ssis_Adoc_T <.. docs.usp_AntoraExport_SsisPartialsContent
ssis.PackageTask_Dft_Component <.. docs.ssis_PumlDftTask
ssis.PackageTask_Dft_Component <.. docs.ssis_DftTaskComponentList
ssis.PackageTask_Dft_Component <.. docs.ssis_PumlPartialDftComponent
ssis.PackageTask_Dft_Component_input <.. docs.ssis_DftTaskComponentInputList
ssis.PackageTask_Dft_Component_input_externalMetadataColumn <.. docs.ssis_DftTaskComponentOutputColumnList
ssis.PackageTask_Dft_Component_input_externalMetadataColumn <.. docs.ssis_DftTaskComponentInputColumnList
ssis.PackageTask_Dft_Component_input_externalMetadataColumn_src <.. ssis.PackageTask_Dft_Component_input_externalMetadataColumn_tgt
ssis.PackageTask_Dft_Component_input_externalMetadataColumn_src <.. ssis.usp_PERSIST_PackageTask_Dft_Component_input_externalMetadataColumn_tgt
ssis.PackageTask_Dft_Component_input_externalMetadataColumn_tgt <.. ssis.PackageTask_Dft_Component_input_externalMetadataColumn
ssis.PackageTask_Dft_Component_input_externalMetadataColumn_tgt <.. ssis.usp_PERSIST_PackageTask_Dft_Component_input_externalMetadataColumn_tgt
ssis.PackageTask_Dft_Component_input_inputColumn <.. docs.ssis_DftTaskComponentInputColumnList
ssis.PackageTask_Dft_Component_input_inputColumn_src <.. ssis.PackageTask_Dft_Component_input_inputColumn_tgt
ssis.PackageTask_Dft_Component_input_inputColumn_src <.. ssis.usp_PERSIST_PackageTask_Dft_Component_input_inputColumn_tgt
ssis.PackageTask_Dft_Component_input_inputColumn_tgt <.. ssis.usp_PERSIST_PackageTask_Dft_Component_input_inputColumn_tgt
ssis.PackageTask_Dft_Component_input_inputColumn_tgt <.. ssis.PackageTask_Dft_Component_input_inputColumn
ssis.PackageTask_Dft_Component_input_src <.. ssis.PackageTask_Dft_Component_input_tgt
ssis.PackageTask_Dft_Component_input_src <.. ssis.usp_PERSIST_PackageTask_Dft_Component_input_tgt
ssis.PackageTask_Dft_Component_input_tgt <.. ssis.PackageTask_Dft_Component_input
ssis.PackageTask_Dft_Component_input_tgt <.. ssis.usp_PERSIST_PackageTask_Dft_Component_input_tgt
ssis.PackageTask_Dft_Component_output <.. docs.ssis_DftTaskComponentOutputList
ssis.PackageTask_Dft_Component_output_externalMetadataColumn_src <.. ssis.PackageTask_Dft_Component_output_externalMetadataColumn_tgt
ssis.PackageTask_Dft_Component_output_externalMetadataColumn_src <.. ssis.usp_PERSIST_PackageTask_Dft_Component_output_externalMetadataColumn_tgt
ssis.PackageTask_Dft_Component_output_externalMetadataColumn_tgt <.. ssis.PackageTask_Dft_Component_output_externalMetadataColumn
ssis.PackageTask_Dft_Component_output_externalMetadataColumn_tgt <.. ssis.usp_PERSIST_PackageTask_Dft_Component_output_externalMetadataColumn_tgt
ssis.PackageTask_Dft_Component_output_outputcolumn <.. docs.ssis_DftTaskComponentOutputColumnList
ssis.PackageTask_Dft_Component_output_outputcolumn_src <.. ssis.PackageTask_Dft_Component_output_outputcolumn_tgt
ssis.PackageTask_Dft_Component_output_outputcolumn_src <.. ssis.usp_PERSIST_PackageTask_Dft_Component_output_outputColumn_tgt
ssis.PackageTask_Dft_Component_output_outputcolumn_tgt <.. ssis.PackageTask_Dft_Component_output_outputcolumn
ssis.PackageTask_Dft_Component_output_outputColumn_tgt <.. ssis.usp_PERSIST_PackageTask_Dft_Component_output_outputColumn_tgt
ssis.PackageTask_Dft_Component_output_src <.. ssis.PackageTask_Dft_Component_output_tgt
ssis.PackageTask_Dft_Component_output_src <.. ssis.usp_PERSIST_PackageTask_Dft_Component_output_tgt
ssis.PackageTask_Dft_Component_output_tgt <.. ssis.PackageTask_Dft_Component_output
ssis.PackageTask_Dft_Component_output_tgt <.. ssis.usp_PERSIST_PackageTask_Dft_Component_output_tgt
ssis.PackageTask_Dft_Component_src <.. ssis.usp_PERSIST_PackageTask_Dft_Component_tgt
ssis.PackageTask_Dft_Component_src <.. ssis.PackageTask_Dft_Component_tgt
ssis.PackageTask_Dft_Component_tgt <.. ssis.usp_PERSIST_PackageTask_Dft_Component_tgt
ssis.PackageTask_Dft_Component_tgt <.. ssis.PackageTask_Dft_Component
ssis.usp_PERSIST_PackageTask_Dft_Component_input_externalMetadataColumn_tgt <.. ssis.usp_import
ssis.usp_PERSIST_PackageTask_Dft_Component_input_inputColumn_tgt <.. ssis.usp_import
ssis.usp_PERSIST_PackageTask_Dft_Component_input_tgt <.. ssis.usp_import
ssis.usp_PERSIST_PackageTask_Dft_Component_output_externalMetadataColumn_tgt <.. ssis.usp_import
ssis.usp_PERSIST_PackageTask_Dft_Component_output_outputColumn_tgt <.. ssis.usp_import
ssis.usp_PERSIST_PackageTask_Dft_Component_output_tgt <.. ssis.usp_import
ssis.usp_PERSIST_PackageTask_Dft_Component_tgt <.. ssis.usp_import
ssis_t.TblTask_Dft_Component <.. ssis_t.usp_GetPackageDetails
ssis_t.TblTask_Dft_Component <.. ssis_t.TblTask_Dft_Component_outputs_outputColumn_src
ssis_t.TblTask_Dft_Component <.. ssis_t.TblTask_Dft_Component_outputs_externalMetadataColumn_src
ssis_t.TblTask_Dft_Component <.. ssis_t.TblTask_Dft_Component_inputs_inputColumn_src
ssis_t.TblTask_Dft_Component <.. ssis_t.TblTask_Dft_Component_inputs_externalMetadataColumn_src
ssis_t.TblTask_Dft_Component <.. ssis.PackageTask_Dft_Component_src
ssis_t.TblTask_Dft_Component <.. ssis_t.TblTask_Dft_Component_outputs_src
ssis_t.TblTask_Dft_Component <.. ssis_t.TblTask_Dft_Component_inputs_src
ssis_t.TblTask_Dft_Component_inputs_externalMetadataColumn_src <.. ssis.PackageTask_Dft_Component_input_externalMetadataColumn_src
ssis_t.TblTask_Dft_Component_inputs_inputColumn_src <.. ssis.PackageTask_Dft_Component_input_inputColumn_src
ssis_t.TblTask_Dft_Component_inputs_src <.. ssis.PackageTask_Dft_Component_input_src
ssis_t.TblTask_Dft_Component_outputs_externalMetadataColumn_src <.. ssis.PackageTask_Dft_Component_output_externalMetadataColumn_src
ssis_t.TblTask_Dft_Component_outputs_outputColumn_src <.. ssis.PackageTask_Dft_Component_output_outputcolumn_src
ssis_t.TblTask_Dft_Component_outputs_src <.. ssis.PackageTask_Dft_Component_output_src

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_0_30_objectref[]

=== PlantUML 1 1 ColumnRef

// tag::puml_entity_1_1_colref[]
[plantuml, entity_1_1_colref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_src.adoc[]" as ssis.PackageTask_Dft_Component_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Component_refId** : (varchar(max))
  Component_AccessMode : (varchar(max))
  Component_AlwaysUseDefaultCodePage : (varchar(max))
  Component_CommandTimeout : (int)
  Component_componentClassID : (varchar(max))
  Component_Connection_description : (varchar(max))
  Component_Connection_name : (varchar(max))
  Component_Connection_refId : (varchar(max))
  Component_connectionManagerID : (varchar(max))
  Component_connectionManagerRefId : (varchar(max))
  Component_ContactInfo : (varchar(max))
  Component_DefaultCodePage : (int)
  Component_description : (varchar(max))
  Component_FastLoadKeepIdentity : (bit)
  Component_FastLoadKeepNulls : (bit)
  Component_FastLoadMaxInsertCommitSize : (int)
  Component_FastLoadOptions : (varchar(max))
  Component_IsSortedProperty : (varchar(10))
  Component_name : (varchar(max))
  Component_OpenRowset : (varchar(max))
  Component_OpenRowsetVariable : (varchar(max))
  Component_ParameterMapping : (varchar(max))
  Component_SqlCommand : (varchar(max))
  Component_SqlCommandVariable : (varchar(max))
  Component_VariableName : (varchar(max))
  - ControlFlowDetailsRowID : (int)
  TaskPath : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_dft_component.adoc[]" as ssis_t.TblTask_Dft_Component << U >> {
  - **DftComponentId** : (int)
  AccessMode : (varchar(max))
  AlwaysUseDefaultCodePage : (varchar(max))
  CommandTimeout : (int)
  componentClassID : (varchar(max))
  Connection_description : (varchar(max))
  Connection_name : (varchar(max))
  Connection_refId : (varchar(max))
  connectionManagerID : (varchar(max))
  connectionManagerRefId : (varchar(max))
  ContactInfo : (varchar(max))
  - ControlFlowDetailsRowID : (int)
  DefaultCodePage : (int)
  description : (varchar(max))
  FastLoadKeepIdentity : (bit)
  FastLoadKeepNulls : (bit)
  FastLoadMaxInsertCommitSize : (int)
  FastLoadOptions : (varchar(max))
  inputsQry : (xml)
  IsSortedProperty : (varchar(10))
  name : (varchar(max))
  OpenRowset : (varchar(max))
  OpenRowsetVariable : (varchar(max))
  outputsQry : (xml)
  ParameterMapping : (varchar(max))
  refId : (varchar(max))
  RowID : (int)
  SqlCommand : (varchar(max))
  SqlCommandVariable : (varchar(max))
  VariableName : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_dft_component_inputs_externalmetadatacolumn_src.adoc[]" as ssis_t.TblTask_Dft_Component_inputs_externalMetadataColumn_src << V >> {
  Column_dataType : (varchar(100))
  Column_length : (int)
  Column_name : (varchar(max))
  Column_precision : (int)
  Column_refId : (varchar(max))
  Column_scale : (int)
  columnscontent : (xml)
  - ControlFlowDetailsRowID : (int)
  - DftComponentId : (int)
  externalMetadataColumns_isused : (bit)
  input_errorOrTruncationOperation : (varchar(100))
  input_errorRowDisposition : (varchar(100))
  input_hasSideEffects : (bit)
  input_name : (varchar(500))
  input_refId : (varchar(max))
  nodescontent : (xml)
  refId : (varchar(max))
  RowID : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_dft_component_inputs_inputcolumn_src.adoc[]" as ssis_t.TblTask_Dft_Component_inputs_inputColumn_src << V >> {
  Column_cachedDataType : (varchar(100))
  Column_cachedName : (varchar(max))
  Column_externalMetadataColumnId : (varchar(max))
  Column_lineageId : (varchar(max))
  Column_refId : (varchar(max))
  columnscontent : (xml)
  - ControlFlowDetailsRowID : (int)
  - DftComponentId : (int)
  input_errorOrTruncationOperation : (varchar(100))
  input_errorRowDisposition : (varchar(100))
  input_hasSideEffects : (bit)
  input_name : (varchar(500))
  input_refId : (varchar(max))
  nodescontent : (xml)
  refId : (varchar(max))
  RowID : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_dft_component_inputs_src.adoc[]" as ssis_t.TblTask_Dft_Component_inputs_src << V >> {
  - ControlFlowDetailsRowID : (int)
  - DftComponentId : (int)
  input_errorOrTruncationOperation : (varchar(100))
  input_errorRowDisposition : (varchar(100))
  input_hasSideEffects : (bit)
  input_name : (varchar(500))
  input_refId : (varchar(max))
  nodescontent : (xml)
  refId : (varchar(max))
  RowID : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_dft_component_outputs_externalmetadatacolumn_src.adoc[]" as ssis_t.TblTask_Dft_Component_outputs_externalMetadataColumn_src << V >> {
  Column_dataType : (varchar(100))
  Column_length : (int)
  Column_name : (varchar(max))
  Column_precision : (int)
  Column_refId : (varchar(max))
  Column_scale : (int)
  columnscontent : (xml)
  - ControlFlowDetailsRowID : (int)
  - DftComponentId : (int)
  externalMetadataColumns_isused : (bit)
  nodescontent : (xml)
  output_name : (varchar(500))
  output_refId : (varchar(max))
  refId : (varchar(max))
  RowID : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_dft_component_outputs_outputcolumn_src.adoc[]" as ssis_t.TblTask_Dft_Component_outputs_outputColumn_src << V >> {
  Column_dataType : (varchar(100))
  Column_errorOrTruncationOperation : (varchar(100))
  Column_errorRowDisposition : (varchar(100))
  Column_externalMetadataColumnId : (varchar(max))
  Column_length : (int)
  Column_lineageId : (varchar(max))
  Column_name : (varchar(max))
  Column_precision : (int)
  Column_refId : (varchar(max))
  Column_scale : (int)
  Column_truncationRowDisposition : (varchar(max))
  columnscontent : (xml)
  - ControlFlowDetailsRowID : (int)
  - DftComponentId : (int)
  nodescontent : (xml)
  output_isErrorOut : (bit)
  output_name : (varchar(500))
  output_refId : (varchar(max))
  refId : (varchar(max))
  RowID : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_dft_component_outputs_src.adoc[]" as ssis_t.TblTask_Dft_Component_outputs_src << V >> {
  - ControlFlowDetailsRowID : (int)
  - DftComponentId : (int)
  nodescontent : (xml)
  output_isErrorOut : (bit)
  output_name : (varchar(500))
  output_refId : (varchar(max))
  refId : (varchar(max))
  RowID : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.usp_getpackagedetails.adoc[]" as ssis_t.usp_GetPackageDetails << P >> {
  --
}

ssis_t.TblTask_Dft_Component <.. ssis_t.usp_GetPackageDetails
ssis_t.TblTask_Dft_Component <.. ssis_t.TblTask_Dft_Component_outputs_outputColumn_src
ssis_t.TblTask_Dft_Component <.. ssis_t.TblTask_Dft_Component_outputs_externalMetadataColumn_src
ssis_t.TblTask_Dft_Component <.. ssis_t.TblTask_Dft_Component_inputs_inputColumn_src
ssis_t.TblTask_Dft_Component <.. ssis_t.TblTask_Dft_Component_inputs_externalMetadataColumn_src
ssis_t.TblTask_Dft_Component <.. ssis.PackageTask_Dft_Component_src
ssis_t.TblTask_Dft_Component <.. ssis_t.TblTask_Dft_Component_outputs_src
ssis_t.TblTask_Dft_Component <.. ssis_t.TblTask_Dft_Component_inputs_src
"ssis_t.TblTask_Dft_Component::AccessMode" <-- "ssis.PackageTask_Dft_Component_src::Component_AccessMode"
"ssis_t.TblTask_Dft_Component::AlwaysUseDefaultCodePage" <-- "ssis.PackageTask_Dft_Component_src::Component_AlwaysUseDefaultCodePage"
"ssis_t.TblTask_Dft_Component::CommandTimeout" <-- "ssis.PackageTask_Dft_Component_src::Component_CommandTimeout"
"ssis_t.TblTask_Dft_Component::componentClassID" <-- "ssis.PackageTask_Dft_Component_src::Component_componentClassID"
"ssis_t.TblTask_Dft_Component::Connection_description" <-- "ssis.PackageTask_Dft_Component_src::Component_Connection_description"
"ssis_t.TblTask_Dft_Component::Connection_name" <-- "ssis.PackageTask_Dft_Component_src::Component_Connection_name"
"ssis_t.TblTask_Dft_Component::Connection_refId" <-- "ssis.PackageTask_Dft_Component_src::Component_Connection_refId"
"ssis_t.TblTask_Dft_Component::connectionManagerID" <-- "ssis.PackageTask_Dft_Component_src::Component_connectionManagerID"
"ssis_t.TblTask_Dft_Component::connectionManagerRefId" <-- "ssis.PackageTask_Dft_Component_src::Component_connectionManagerRefId"
"ssis_t.TblTask_Dft_Component::ContactInfo" <-- "ssis.PackageTask_Dft_Component_src::Component_ContactInfo"
"ssis_t.TblTask_Dft_Component::ControlFlowDetailsRowID" <-- "ssis_t.TblTask_Dft_Component_inputs_externalMetadataColumn_src::ControlFlowDetailsRowID"
"ssis_t.TblTask_Dft_Component::ControlFlowDetailsRowID" <-- "ssis_t.TblTask_Dft_Component_outputs_outputColumn_src::ControlFlowDetailsRowID"
"ssis_t.TblTask_Dft_Component::ControlFlowDetailsRowID" <-- "ssis_t.TblTask_Dft_Component_outputs_externalMetadataColumn_src::ControlFlowDetailsRowID"
"ssis_t.TblTask_Dft_Component::ControlFlowDetailsRowID" <-- "ssis_t.TblTask_Dft_Component_inputs_inputColumn_src::ControlFlowDetailsRowID"
"ssis_t.TblTask_Dft_Component::ControlFlowDetailsRowID" <-- "ssis_t.TblTask_Dft_Component_inputs_src::ControlFlowDetailsRowID"
"ssis_t.TblTask_Dft_Component::ControlFlowDetailsRowID" <-- "ssis_t.TblTask_Dft_Component_outputs_src::ControlFlowDetailsRowID"
"ssis_t.TblTask_Dft_Component::DefaultCodePage" <-- "ssis.PackageTask_Dft_Component_src::Component_DefaultCodePage"
"ssis_t.TblTask_Dft_Component::description" <-- "ssis.PackageTask_Dft_Component_src::Component_description"
"ssis_t.TblTask_Dft_Component::DftComponentId" <-- "ssis_t.TblTask_Dft_Component_inputs_inputColumn_src::DftComponentId"
"ssis_t.TblTask_Dft_Component::DftComponentId" <-- "ssis_t.TblTask_Dft_Component_inputs_externalMetadataColumn_src::DftComponentId"
"ssis_t.TblTask_Dft_Component::DftComponentId" <-- "ssis_t.TblTask_Dft_Component_outputs_externalMetadataColumn_src::DftComponentId"
"ssis_t.TblTask_Dft_Component::DftComponentId" <-- "ssis_t.TblTask_Dft_Component_outputs_outputColumn_src::DftComponentId"
"ssis_t.TblTask_Dft_Component::DftComponentId" <-- "ssis_t.TblTask_Dft_Component_outputs_src::DftComponentId"
"ssis_t.TblTask_Dft_Component::DftComponentId" <-- "ssis_t.TblTask_Dft_Component_inputs_src::DftComponentId"
"ssis_t.TblTask_Dft_Component::FastLoadKeepIdentity" <-- "ssis.PackageTask_Dft_Component_src::Component_FastLoadKeepIdentity"
"ssis_t.TblTask_Dft_Component::FastLoadKeepNulls" <-- "ssis.PackageTask_Dft_Component_src::Component_FastLoadKeepNulls"
"ssis_t.TblTask_Dft_Component::FastLoadMaxInsertCommitSize" <-- "ssis.PackageTask_Dft_Component_src::Component_FastLoadMaxInsertCommitSize"
"ssis_t.TblTask_Dft_Component::FastLoadOptions" <-- "ssis.PackageTask_Dft_Component_src::Component_FastLoadOptions"
"ssis_t.TblTask_Dft_Component::IsSortedProperty" <-- "ssis.PackageTask_Dft_Component_src::Component_IsSortedProperty"
"ssis_t.TblTask_Dft_Component::name" <-- "ssis.PackageTask_Dft_Component_src::Component_name"
"ssis_t.TblTask_Dft_Component::OpenRowset" <-- "ssis.PackageTask_Dft_Component_src::Component_OpenRowset"
"ssis_t.TblTask_Dft_Component::OpenRowsetVariable" <-- "ssis.PackageTask_Dft_Component_src::Component_OpenRowsetVariable"
"ssis_t.TblTask_Dft_Component::ParameterMapping" <-- "ssis.PackageTask_Dft_Component_src::Component_ParameterMapping"
"ssis_t.TblTask_Dft_Component::refId" <-- "ssis.PackageTask_Dft_Component_src::Component_refId"
"ssis_t.TblTask_Dft_Component::refId" <-- "ssis_t.TblTask_Dft_Component_inputs_externalMetadataColumn_src::refId"
"ssis_t.TblTask_Dft_Component::refId" <-- "ssis_t.TblTask_Dft_Component_inputs_inputColumn_src::refId"
"ssis_t.TblTask_Dft_Component::refId" <-- "ssis_t.TblTask_Dft_Component_outputs_outputColumn_src::refId"
"ssis_t.TblTask_Dft_Component::refId" <-- "ssis_t.TblTask_Dft_Component_outputs_externalMetadataColumn_src::refId"
"ssis_t.TblTask_Dft_Component::refId" <-- "ssis_t.TblTask_Dft_Component_inputs_src::refId"
"ssis_t.TblTask_Dft_Component::refId" <-- "ssis_t.TblTask_Dft_Component_outputs_src::refId"
"ssis_t.TblTask_Dft_Component::RowID" <-- "ssis_t.TblTask_Dft_Component_outputs_src::RowID"
"ssis_t.TblTask_Dft_Component::RowID" <-- "ssis_t.TblTask_Dft_Component_inputs_src::RowID"
"ssis_t.TblTask_Dft_Component::RowID" <-- "ssis_t.TblTask_Dft_Component_inputs_inputColumn_src::RowID"
"ssis_t.TblTask_Dft_Component::RowID" <-- "ssis_t.TblTask_Dft_Component_outputs_externalMetadataColumn_src::RowID"
"ssis_t.TblTask_Dft_Component::RowID" <-- "ssis_t.TblTask_Dft_Component_outputs_outputColumn_src::RowID"
"ssis_t.TblTask_Dft_Component::RowID" <-- "ssis_t.TblTask_Dft_Component_inputs_externalMetadataColumn_src::RowID"
"ssis_t.TblTask_Dft_Component::SqlCommand" <-- "ssis.PackageTask_Dft_Component_src::Component_SqlCommand"
"ssis_t.TblTask_Dft_Component::SqlCommandVariable" <-- "ssis.PackageTask_Dft_Component_src::Component_SqlCommandVariable"
"ssis_t.TblTask_Dft_Component::VariableName" <-- "ssis.PackageTask_Dft_Component_src::Component_VariableName"

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_colref[]


== sql_modules_definition

// tag::sql_modules_definition[]
[%collapsible]
=======
[source,sql,numbered,indent=0]
----

----
=======
// end::sql_modules_definition[]


