// tag::HeaderFullDisplayName[]
= ssis.PackageTask_Dft_Component_output_externalMetadataColumn - U
// end::HeaderFullDisplayName[]

== existing_properties

// tag::existing_properties[]

:ExistsProperty--antorareferencedlist:
:ExistsProperty--is_repo_managed:
:ExistsProperty--is_ssas:
:ExistsProperty--referencedobjectlist:
:ExistsProperty--FK:
:ExistsProperty--Columns:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
0F32C7D6-D13F-EC11-852D-A81E8446D5B0
// end::RepoObject_guid[]

== RepoObject_FullDisplayName2

// tag::RepoObject_FullDisplayName2[]
ssis.PackageTask_Dft_Component_output_externalMetadataColumn
// end::RepoObject_FullDisplayName2[]

== SysObject_type

// tag::SysObject_type[]
U 
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
user table
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
814678000
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2022-01-23 14:10:33
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]
[discrete]
== _


[#column-antoramodule]
=== AntoraModule

[cols="d,8a,m,m,m"]
|===
|
|AntoraModule
|varchar(50)
|NOT NULL
|
|===

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_output_externalmetadatacolumn_tgt.adoc#column-antoramodule[+ssis.PackageTask_Dft_Component_output_externalMetadataColumn_tgt.AntoraModule+]
--


[#column-columnunderlinedatatype]
=== Column_dataType

[cols="d,8a,m,m,m"]
|===
|
|Column_dataType
|varchar(100)
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_output_externalmetadatacolumn_tgt.adoc#column-columnunderlinedatatype[+ssis.PackageTask_Dft_Component_output_externalMetadataColumn_tgt.Column_dataType+]
--


[#column-columnunderlinelength]
=== Column_length

[cols="d,8a,m,m,m"]
|===
|
|Column_length
|int
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_output_externalmetadatacolumn_tgt.adoc#column-columnunderlinelength[+ssis.PackageTask_Dft_Component_output_externalMetadataColumn_tgt.Column_length+]
--


[#column-columnunderlinename]
=== Column_name

[cols="d,8a,m,m,m"]
|===
|
|Column_name
|varchar(max)
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_output_externalmetadatacolumn_tgt.adoc#column-columnunderlinename[+ssis.PackageTask_Dft_Component_output_externalMetadataColumn_tgt.Column_name+]
--


[#column-columnunderlineprecision]
=== Column_precision

[cols="d,8a,m,m,m"]
|===
|
|Column_precision
|int
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_output_externalmetadatacolumn_tgt.adoc#column-columnunderlineprecision[+ssis.PackageTask_Dft_Component_output_externalMetadataColumn_tgt.Column_precision+]
--


[#column-columnunderlinerefid]
=== Column_refId

[cols="d,8a,m,m,m"]
|===
|
|Column_refId
|varchar(max)
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_output_externalmetadatacolumn_tgt.adoc#column-columnunderlinerefid[+ssis.PackageTask_Dft_Component_output_externalMetadataColumn_tgt.Column_refId+]
--


[#column-columnunderlinescale]
=== Column_scale

[cols="d,8a,m,m,m"]
|===
|
|Column_scale
|int
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_output_externalmetadatacolumn_tgt.adoc#column-columnunderlinescale[+ssis.PackageTask_Dft_Component_output_externalMetadataColumn_tgt.Column_scale+]
--


[#column-componentunderlinerefid]
=== Component_refId

[cols="d,8a,m,m,m"]
|===
|
|Component_refId
|varchar(max)
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_output_externalmetadatacolumn_tgt.adoc#column-componentunderlinerefid[+ssis.PackageTask_Dft_Component_output_externalMetadataColumn_tgt.Component_refId+]
--


[#column-controlflowdetailsrowid]
=== ControlFlowDetailsRowID

[cols="d,8a,m,m,m"]
|===
|
|ControlFlowDetailsRowID
|int
|NOT NULL
|
|===

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_output_externalmetadatacolumn_tgt.adoc#column-controlflowdetailsrowid[+ssis.PackageTask_Dft_Component_output_externalMetadataColumn_tgt.ControlFlowDetailsRowID+]
--


[#column-externalmetadatacolumnsunderlineisused]
=== externalMetadataColumns_isused

[cols="d,8a,m,m,m"]
|===
|
|externalMetadataColumns_isused
|bit
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_output_externalmetadatacolumn_tgt.adoc#column-externalmetadatacolumnsunderlineisused[+ssis.PackageTask_Dft_Component_output_externalMetadataColumn_tgt.externalMetadataColumns_isused+]
--


[#column-outputunderlinename]
=== output_name

[cols="d,8a,m,m,m"]
|===
|
|output_name
|varchar(500)
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_output_externalmetadatacolumn_tgt.adoc#column-outputunderlinename[+ssis.PackageTask_Dft_Component_output_externalMetadataColumn_tgt.output_name+]
--


[#column-outputunderlinerefid]
=== output_refId

[cols="d,8a,m,m,m"]
|===
|
|output_refId
|varchar(max)
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_output_externalmetadatacolumn_tgt.adoc#column-outputunderlinerefid[+ssis.PackageTask_Dft_Component_output_externalMetadataColumn_tgt.output_refId+]
--


[#column-packagename]
=== PackageName

[cols="d,8a,m,m,m"]
|===
|
|PackageName
|varchar(200)
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_output_externalmetadatacolumn_tgt.adoc#column-packagename[+ssis.PackageTask_Dft_Component_output_externalMetadataColumn_tgt.PackageName+]
--


[#column-taskpath]
=== TaskPath

[cols="d,8a,m,m,m"]
|===
|
|TaskPath
|varchar(8000)
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_output_externalmetadatacolumn_tgt.adoc#column-taskpath[+ssis.PackageTask_Dft_Component_output_externalMetadataColumn_tgt.TaskPath+]
--


// end::AntoraColumnDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]














// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]
|
|<<column-antoramodule>>
|varchar(50)
|NOT NULL
|

|
|<<column-columnunderlinedatatype>>
|varchar(100)
|NULL
|

|
|<<column-columnunderlinelength>>
|int
|NULL
|

|
|<<column-columnunderlinename>>
|varchar(max)
|NULL
|

|
|<<column-columnunderlineprecision>>
|int
|NULL
|

|
|<<column-columnunderlinerefid>>
|varchar(max)
|NULL
|

|
|<<column-columnunderlinescale>>
|int
|NULL
|

|
|<<column-componentunderlinerefid>>
|varchar(max)
|NULL
|

|
|<<column-controlflowdetailsrowid>>
|int
|NOT NULL
|

|
|<<column-externalmetadatacolumnsunderlineisused>>
|bit
|NULL
|

|
|<<column-outputunderlinename>>
|varchar(500)
|NULL
|

|
|<<column-outputunderlinerefid>>
|varchar(max)
|NULL
|

|
|<<column-packagename>>
|varchar(200)
|NULL
|

|
|<<column-taskpath>>
|varchar(8000)
|NULL
|

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

// end::AntoraIndexList[]

== AntoraMeasureDetails

// tag::AntoraMeasureDetails[]

// end::AntoraMeasureDetails[]

== AntoraMeasureDescriptions



== AntoraParameterList

// tag::AntoraParameterList[]

// end::AntoraParameterList[]

== AntoraXrefCulturesList

// tag::AntoraXrefCulturesList[]
* xref:dhw:sqldb:ssis.packagetask_dft_component_output_externalmetadatacolumn.adoc[] - 
// end::AntoraXrefCulturesList[]

== cultures_count

// tag::cultures_count[]
1
// end::cultures_count[]

== Other tags

source: property.RepoObjectProperty_cross As rop_cross


=== additional_reference_csv

// tag::additional_reference_csv[]

// end::additional_reference_csv[]


=== AdocUspSteps

// tag::adocuspsteps[]

// end::adocuspsteps[]


=== AntoraReferencedList

// tag::antorareferencedlist[]
* xref:dhw:sqldb:ssis.packagetask_dft_component_output_externalmetadatacolumn_tgt.adoc[]
// end::antorareferencedlist[]


=== AntoraReferencingList

// tag::antorareferencinglist[]

// end::antorareferencinglist[]


=== Description

// tag::description[]

// end::description[]


=== exampleUsage

// tag::exampleusage[]

// end::exampleusage[]


=== exampleUsage_2

// tag::exampleusage_2[]

// end::exampleusage_2[]


=== exampleUsage_3

// tag::exampleusage_3[]

// end::exampleusage_3[]


=== exampleUsage_4

// tag::exampleusage_4[]

// end::exampleusage_4[]


=== exampleUsage_5

// tag::exampleusage_5[]

// end::exampleusage_5[]


=== exampleWrong_Usage

// tag::examplewrong_usage[]

// end::examplewrong_usage[]


=== has_execution_plan_issue

// tag::has_execution_plan_issue[]

// end::has_execution_plan_issue[]


=== has_get_referenced_issue

// tag::has_get_referenced_issue[]

// end::has_get_referenced_issue[]


=== has_history

// tag::has_history[]

// end::has_history[]


=== has_history_columns

// tag::has_history_columns[]

// end::has_history_columns[]


=== InheritanceType

// tag::inheritancetype[]

// end::inheritancetype[]


=== is_persistence

// tag::is_persistence[]

// end::is_persistence[]


=== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]

// end::is_persistence_check_duplicate_per_pk[]


=== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]

// end::is_persistence_check_for_empty_source[]


=== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]

// end::is_persistence_delete_changed[]


=== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]

// end::is_persistence_delete_missing[]


=== is_persistence_insert

// tag::is_persistence_insert[]

// end::is_persistence_insert[]


=== is_persistence_truncate

// tag::is_persistence_truncate[]

// end::is_persistence_truncate[]


=== is_persistence_update_changed

// tag::is_persistence_update_changed[]

// end::is_persistence_update_changed[]


=== is_repo_managed

// tag::is_repo_managed[]
0
// end::is_repo_managed[]


=== is_ssas

// tag::is_ssas[]
0
// end::is_ssas[]


=== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


=== MS_Description

// tag::ms_description[]

// end::ms_description[]


=== persistence_source_RepoObject_fullname

// tag::persistence_source_repoobject_fullname[]

// end::persistence_source_repoobject_fullname[]


=== persistence_source_RepoObject_fullname2

// tag::persistence_source_repoobject_fullname2[]

// end::persistence_source_repoobject_fullname2[]


=== persistence_source_RepoObject_guid

// tag::persistence_source_repoobject_guid[]

// end::persistence_source_repoobject_guid[]


=== persistence_source_RepoObject_xref

// tag::persistence_source_repoobject_xref[]

// end::persistence_source_repoobject_xref[]


=== pk_index_guid

// tag::pk_index_guid[]

// end::pk_index_guid[]


=== pk_IndexPatternColumnDatatype

// tag::pk_indexpatterncolumndatatype[]

// end::pk_indexpatterncolumndatatype[]


=== pk_IndexPatternColumnName

// tag::pk_indexpatterncolumnname[]

// end::pk_indexpatterncolumnname[]


=== pk_IndexSemanticGroup

// tag::pk_indexsemanticgroup[]

// end::pk_indexsemanticgroup[]


=== ReferencedObjectList

// tag::referencedobjectlist[]
* [ssis].[PackageTask_Dft_Component_output_externalMetadataColumn_tgt]
// end::referencedobjectlist[]


=== usp_persistence_RepoObject_guid

// tag::usp_persistence_repoobject_guid[]

// end::usp_persistence_repoobject_guid[]


=== UspExamples

// tag::uspexamples[]

// end::uspexamples[]


=== uspgenerator_usp_id

// tag::uspgenerator_usp_id[]

// end::uspgenerator_usp_id[]


=== UspParameters

// tag::uspparameters[]

// end::uspparameters[]

== Boolean Attributes

source: property.RepoObjectProperty WHERE property_int = 1

// tag::boolean_attributes[]


// end::boolean_attributes[]

== PlantUML diagrams

=== PlantUML Entity

// tag::puml_entity[]
[plantuml, entity-{docname}, svg, subs=macros]
....
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_output_externalmetadatacolumn.adoc[]" as ssis.PackageTask_Dft_Component_output_externalMetadataColumn << U >> {
  - AntoraModule : (varchar(50))
  Column_dataType : (varchar(100))
  Column_length : (int)
  Column_name : (varchar(max))
  Column_precision : (int)
  Column_refId : (varchar(max))
  Column_scale : (int)
  Component_refId : (varchar(max))
  - ControlFlowDetailsRowID : (int)
  externalMetadataColumns_isused : (bit)
  output_name : (varchar(500))
  output_refId : (varchar(max))
  PackageName : (varchar(200))
  TaskPath : (varchar(8000))
  --
}
....

// end::puml_entity[]

=== PlantUML Entity 1 1 FK

// tag::puml_entity_1_1_fk[]
[plantuml, entity_1_1_fk-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_output_externalmetadatacolumn.adoc[]" as ssis.PackageTask_Dft_Component_output_externalMetadataColumn << U >> {

}



footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_fk[]

=== PlantUML 1 1 ObjectRef

// tag::puml_entity_1_1_objectref[]
[plantuml, entity_1_1_objectref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_output_externalmetadatacolumn.adoc[]" as ssis.PackageTask_Dft_Component_output_externalMetadataColumn << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_output_externalmetadatacolumn_tgt.adoc[]" as ssis.PackageTask_Dft_Component_output_externalMetadataColumn_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Column_refId** : (varchar(max))
  --
}

ssis.PackageTask_Dft_Component_output_externalMetadataColumn_tgt <.. ssis.PackageTask_Dft_Component_output_externalMetadataColumn

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_objectref[]

=== PlantUML 30 0 ObjectRef

// tag::puml_entity_30_0_objectref[]
[plantuml, entity_30_0_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis.antoramodule_tgt_filter.adoc[]" as ssis.AntoraModule_tgt_filter << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.package_src.adoc[]" as ssis.Package_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_output_externalmetadatacolumn.adoc[]" as ssis.PackageTask_Dft_Component_output_externalMetadataColumn << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_output_externalmetadatacolumn_src.adoc[]" as ssis.PackageTask_Dft_Component_output_externalMetadataColumn_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Column_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_output_externalmetadatacolumn_tgt.adoc[]" as ssis.PackageTask_Dft_Component_output_externalMetadataColumn_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Column_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.project.adoc[]" as ssis.Project << U >> {
  - **AntoraModule** : (varchar(50))
  --
}

entity "puml-link:dhw:sqldb:ssis_t.pkgstats.adoc[]" as ssis_t.pkgStats << U >> {
  - **RowID** : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tblcontrolflow.adoc[]" as ssis_t.TblControlFlow << U >> {
  - **ControlFlowDetailsRowID** : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_dft_component.adoc[]" as ssis_t.TblTask_Dft_Component << U >> {
  - **DftComponentId** : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_dft_component_outputs_externalmetadatacolumn_src.adoc[]" as ssis_t.TblTask_Dft_Component_outputs_externalMetadataColumn_src << V >> {
  --
}

ssis.AntoraModule_tgt_filter <.. ssis.PackageTask_Dft_Component_output_externalMetadataColumn_tgt
ssis.Package_src <.. ssis.PackageTask_Dft_Component_output_externalMetadataColumn_src
ssis.Package_src <.. ssis.AntoraModule_tgt_filter
ssis.PackageTask_Dft_Component_output_externalMetadataColumn_src <.. ssis.PackageTask_Dft_Component_output_externalMetadataColumn_tgt
ssis.PackageTask_Dft_Component_output_externalMetadataColumn_tgt <.. ssis.PackageTask_Dft_Component_output_externalMetadataColumn
ssis.Project <.. ssis.Package_src
ssis_t.pkgStats <.. ssis.Package_src
ssis_t.TblControlFlow <.. ssis.PackageTask_Dft_Component_output_externalMetadataColumn_src
ssis_t.TblTask_Dft_Component <.. ssis_t.TblTask_Dft_Component_outputs_externalMetadataColumn_src
ssis_t.TblTask_Dft_Component_outputs_externalMetadataColumn_src <.. ssis.PackageTask_Dft_Component_output_externalMetadataColumn_src

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_30_0_objectref[]

=== PlantUML 0 30 ObjectRef

// tag::puml_entity_0_30_objectref[]
[plantuml, entity_0_30_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_output_externalmetadatacolumn.adoc[]" as ssis.PackageTask_Dft_Component_output_externalMetadataColumn << U >> {
  --
}



footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_0_30_objectref[]

=== PlantUML 1 1 ColumnRef

// tag::puml_entity_1_1_colref[]
[plantuml, entity_1_1_colref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_output_externalmetadatacolumn.adoc[]" as ssis.PackageTask_Dft_Component_output_externalMetadataColumn << U >> {
  - AntoraModule : (varchar(50))
  Column_dataType : (varchar(100))
  Column_length : (int)
  Column_name : (varchar(max))
  Column_precision : (int)
  Column_refId : (varchar(max))
  Column_scale : (int)
  Component_refId : (varchar(max))
  - ControlFlowDetailsRowID : (int)
  externalMetadataColumns_isused : (bit)
  output_name : (varchar(500))
  output_refId : (varchar(max))
  PackageName : (varchar(200))
  TaskPath : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_output_externalmetadatacolumn_tgt.adoc[]" as ssis.PackageTask_Dft_Component_output_externalMetadataColumn_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Column_refId** : (varchar(max))
  Column_dataType : (varchar(100))
  Column_length : (int)
  Column_name : (varchar(max))
  Column_precision : (int)
  Column_scale : (int)
  Component_refId : (varchar(max))
  - ControlFlowDetailsRowID : (int)
  externalMetadataColumns_isused : (bit)
  output_name : (varchar(500))
  output_refId : (varchar(max))
  TaskPath : (varchar(8000))
  --
}

ssis.PackageTask_Dft_Component_output_externalMetadataColumn_tgt <.. ssis.PackageTask_Dft_Component_output_externalMetadataColumn
"ssis.PackageTask_Dft_Component_output_externalMetadataColumn::AntoraModule" <-- "ssis.PackageTask_Dft_Component_output_externalMetadataColumn_tgt::AntoraModule"
"ssis.PackageTask_Dft_Component_output_externalMetadataColumn::Column_dataType" <-- "ssis.PackageTask_Dft_Component_output_externalMetadataColumn_tgt::Column_dataType"
"ssis.PackageTask_Dft_Component_output_externalMetadataColumn::Column_length" <-- "ssis.PackageTask_Dft_Component_output_externalMetadataColumn_tgt::Column_length"
"ssis.PackageTask_Dft_Component_output_externalMetadataColumn::Column_name" <-- "ssis.PackageTask_Dft_Component_output_externalMetadataColumn_tgt::Column_name"
"ssis.PackageTask_Dft_Component_output_externalMetadataColumn::Column_precision" <-- "ssis.PackageTask_Dft_Component_output_externalMetadataColumn_tgt::Column_precision"
"ssis.PackageTask_Dft_Component_output_externalMetadataColumn::Column_refId" <-- "ssis.PackageTask_Dft_Component_output_externalMetadataColumn_tgt::Column_refId"
"ssis.PackageTask_Dft_Component_output_externalMetadataColumn::Column_scale" <-- "ssis.PackageTask_Dft_Component_output_externalMetadataColumn_tgt::Column_scale"
"ssis.PackageTask_Dft_Component_output_externalMetadataColumn::Component_refId" <-- "ssis.PackageTask_Dft_Component_output_externalMetadataColumn_tgt::Component_refId"
"ssis.PackageTask_Dft_Component_output_externalMetadataColumn::ControlFlowDetailsRowID" <-- "ssis.PackageTask_Dft_Component_output_externalMetadataColumn_tgt::ControlFlowDetailsRowID"
"ssis.PackageTask_Dft_Component_output_externalMetadataColumn::externalMetadataColumns_isused" <-- "ssis.PackageTask_Dft_Component_output_externalMetadataColumn_tgt::externalMetadataColumns_isused"
"ssis.PackageTask_Dft_Component_output_externalMetadataColumn::output_name" <-- "ssis.PackageTask_Dft_Component_output_externalMetadataColumn_tgt::output_name"
"ssis.PackageTask_Dft_Component_output_externalMetadataColumn::output_refId" <-- "ssis.PackageTask_Dft_Component_output_externalMetadataColumn_tgt::output_refId"
"ssis.PackageTask_Dft_Component_output_externalMetadataColumn::PackageName" <-- "ssis.PackageTask_Dft_Component_output_externalMetadataColumn_tgt::PackageName"
"ssis.PackageTask_Dft_Component_output_externalMetadataColumn::TaskPath" <-- "ssis.PackageTask_Dft_Component_output_externalMetadataColumn_tgt::TaskPath"

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_colref[]


== sql_modules_definition

// tag::sql_modules_definition[]
[%collapsible]
=======
[source,sql,numbered,indent=0]
----

----
=======
// end::sql_modules_definition[]


