// tag::HeaderFullDisplayName[]
= ssis.PackageTask_Sql_Parameter_src - V
// end::HeaderFullDisplayName[]

== existing_properties

// tag::existing_properties[]

:ExistsProperty--antorareferencedlist:
:ExistsProperty--antorareferencinglist:
:ExistsProperty--is_repo_managed:
:ExistsProperty--is_ssas:
:ExistsProperty--pk_index_guid:
:ExistsProperty--pk_indexpatterncolumndatatype:
:ExistsProperty--pk_indexpatterncolumnname:
:ExistsProperty--referencedobjectlist:
:ExistsProperty--sql_modules_definition:
:ExistsProperty--FK:
:ExistsProperty--AntoraIndexList:
:ExistsProperty--Columns:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
6A64FBE4-113B-EC11-852C-A81E8446D5B0
// end::RepoObject_guid[]

== RepoObject_FullDisplayName2

// tag::RepoObject_FullDisplayName2[]
ssis.PackageTask_Sql_Parameter_src
// end::RepoObject_FullDisplayName2[]

== SysObject_type

// tag::SysObject_type[]
V 
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
view
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
162151673
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2021-11-01 14:44:38
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]
[discrete]
== _


[#column-antoramodule]
=== AntoraModule

[cols="d,8a,m,m,m"]
|===
|1
|*AntoraModule*
|varchar(50)
|NOT NULL
|
|===

.Referenced Columns
--
* xref:ssis.package_src.adoc#column-antoramodule[+ssis.Package_src.AntoraModule+]
--

.Referencing Columns
--
* xref:ssis.packagetask_sql_parameter_tgt.adoc#column-antoramodule[+ssis.PackageTask_Sql_Parameter_tgt.AntoraModule+]
--


[#column-packagename]
=== PackageName

[cols="d,8a,m,m,m"]
|===
|2
|*PackageName*
|varchar(200)
|NULL
|
|===

.Description
--
(left(replace([PackagePath],[ProjectPath]+'\',''),(200)))
--
{empty} +

.Referenced Columns
--
* xref:ssis.package_src.adoc#column-packagename[+ssis.Package_src.PackageName+]
--

.Referencing Columns
--
* xref:ssis.packagetask_sql_parameter_tgt.adoc#column-packagename[+ssis.PackageTask_Sql_Parameter_tgt.PackageName+]
--


[#column-taskpath]
=== TaskPath

[cols="d,8a,m,m,m"]
|===
|3
|*TaskPath*
|varchar(8000)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis_t.tblcontrolflow.adoc#column-taskpath[+ssis_t.TblControlFlow.TaskPath+]
--

.Referencing Columns
--
* xref:ssis.packagetask_sql_parameter_tgt.adoc#column-taskpath[+ssis.PackageTask_Sql_Parameter_tgt.TaskPath+]
--


[#column-parameterbindingsequence]
=== ParameterBindingSequence

[cols="d,8a,m,m,m"]
|===
|4
|*ParameterBindingSequence*
|varchar(1000)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis_t.tbltask_sql_parameter.adoc#column-parameterbindingsequence[+ssis_t.TblTask_Sql_Parameter.ParameterBindingSequence+]
--

.Referencing Columns
--
* xref:ssis.packagetask_sql_parameter_tgt.adoc#column-parameterbindingsequence[+ssis.PackageTask_Sql_Parameter_tgt.ParameterBindingSequence+]
--


[#column-controlflowdetailsrowid]
=== ControlFlowDetailsRowID

[cols="d,8a,m,m,m"]
|===
|
|ControlFlowDetailsRowID
|int
|NOT NULL
|
|===

.Referenced Columns
--
* xref:ssis_t.tblcontrolflow.adoc#column-controlflowdetailsrowid[+ssis_t.TblControlFlow.ControlFlowDetailsRowID+]
--

.Referencing Columns
--
* xref:ssis.packagetask_sql_parameter_tgt.adoc#column-controlflowdetailsrowid[+ssis.PackageTask_Sql_Parameter_tgt.ControlFlowDetailsRowID+]
--


[#column-parameterbindingparametername]
=== ParameterBindingParameterName

[cols="d,8a,m,m,m"]
|===
|
|ParameterBindingParameterName
|varchar(1000)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis_t.tbltask_sql_parameter.adoc#column-parameterbindingparametername[+ssis_t.TblTask_Sql_Parameter.ParameterBindingParameterName+]
--

.Referencing Columns
--
* xref:ssis.packagetask_sql_parameter_tgt.adoc#column-parameterbindingparametername[+ssis.PackageTask_Sql_Parameter_tgt.ParameterBindingParameterName+]
--


[#column-resultsetparametername]
=== ResultSetParameterName

[cols="d,8a,m,m,m"]
|===
|
|ResultSetParameterName
|varchar(1000)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis_t.tbltask_sql_parameter.adoc#column-resultsetparametername[+ssis_t.TblTask_Sql_Parameter.ResultSetParameterName+]
--

.Referencing Columns
--
* xref:ssis.packagetask_sql_parameter_tgt.adoc#column-resultsetparametername[+ssis.PackageTask_Sql_Parameter_tgt.ResultSetParameterName+]
--


// end::AntoraColumnDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]
|1
|*<<column-antoramodule>>*
|varchar(50)
|NOT NULL
|

|2
|*<<column-packagename>>*
|varchar(200)
|NULL
|

|3
|*<<column-taskpath>>*
|varchar(8000)
|NULL
|

|4
|*<<column-parameterbindingsequence>>*
|varchar(1000)
|NULL
|




// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]




|
|<<column-controlflowdetailsrowid>>
|int
|NOT NULL
|

|
|<<column-parameterbindingparametername>>
|varchar(1000)
|NULL
|

|
|<<column-resultsetparametername>>
|varchar(1000)
|NULL
|

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

[#index-pkunderlinepackagetaskunderlinesqlunderlineparameterunderlinesrc]
=== PK_PackageTask_Sql_Parameter_src

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-AntoraModule>>; varchar(50)
* <<column-PackageName>>; varchar(200)
* <<column-TaskPath>>; varchar(8000)
* <<column-ParameterBindingSequence>>; varchar(1000)
--
* PK, Unique, Real: 1, 1, 0


[#index-idxunderlinepackagetaskunderlinesqlunderlineparameterunderlinesrcunderlineunderline2]
=== idx_PackageTask_Sql_Parameter_src++__++2

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-ControlFlowDetailsRowID>>; int
--
* PK, Unique, Real: 0, 0, 0


[#index-idxunderlinepackagetaskunderlinesqlunderlineparameterunderlinesrcunderlineunderline3]
=== idx_PackageTask_Sql_Parameter_src++__++3

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-AntoraModule>>; varchar(50)
* <<column-PackageName>>; varchar(200)
--
* PK, Unique, Real: 0, 0, 0


[#index-idxunderlinepackagetaskunderlinesqlunderlineparameterunderlinesrcunderlineunderline4]
=== idx_PackageTask_Sql_Parameter_src++__++4

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-AntoraModule>>; varchar(50)
--
* PK, Unique, Real: 0, 0, 0

// end::AntoraIndexList[]

== AntoraMeasureDetails

// tag::AntoraMeasureDetails[]

// end::AntoraMeasureDetails[]

== AntoraMeasureDescriptions



== AntoraParameterList

// tag::AntoraParameterList[]

// end::AntoraParameterList[]

== AntoraXrefCulturesList

// tag::AntoraXrefCulturesList[]
* xref:dhw:sqldb:ssis.packagetask_sql_parameter_src.adoc[] - 
// end::AntoraXrefCulturesList[]

== cultures_count

// tag::cultures_count[]
1
// end::cultures_count[]

== Other tags

source: property.RepoObjectProperty_cross As rop_cross


=== additional_reference_csv

// tag::additional_reference_csv[]

// end::additional_reference_csv[]


=== AdocUspSteps

// tag::adocuspsteps[]

// end::adocuspsteps[]


=== AntoraReferencedList

// tag::antorareferencedlist[]
* xref:dhw:sqldb:ssis.package_src.adoc[]
* xref:dhw:sqldb:ssis_t.tblcontrolflow.adoc[]
* xref:dhw:sqldb:ssis_t.tbltask_sql_parameter.adoc[]
// end::antorareferencedlist[]


=== AntoraReferencingList

// tag::antorareferencinglist[]
* xref:dhw:sqldb:ssis.packagetask_sql_parameter_tgt.adoc[]
* xref:dhw:sqldb:ssis.usp_persist_packagetask_sql_parameter_tgt.adoc[]
// end::antorareferencinglist[]


=== Description

// tag::description[]

// end::description[]


=== exampleUsage

// tag::exampleusage[]

// end::exampleusage[]


=== exampleUsage_2

// tag::exampleusage_2[]

// end::exampleusage_2[]


=== exampleUsage_3

// tag::exampleusage_3[]

// end::exampleusage_3[]


=== exampleUsage_4

// tag::exampleusage_4[]

// end::exampleusage_4[]


=== exampleUsage_5

// tag::exampleusage_5[]

// end::exampleusage_5[]


=== exampleWrong_Usage

// tag::examplewrong_usage[]

// end::examplewrong_usage[]


=== has_execution_plan_issue

// tag::has_execution_plan_issue[]

// end::has_execution_plan_issue[]


=== has_get_referenced_issue

// tag::has_get_referenced_issue[]

// end::has_get_referenced_issue[]


=== has_history

// tag::has_history[]

// end::has_history[]


=== has_history_columns

// tag::has_history_columns[]

// end::has_history_columns[]


=== InheritanceType

// tag::inheritancetype[]

// end::inheritancetype[]


=== is_persistence

// tag::is_persistence[]

// end::is_persistence[]


=== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]

// end::is_persistence_check_duplicate_per_pk[]


=== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]

// end::is_persistence_check_for_empty_source[]


=== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]

// end::is_persistence_delete_changed[]


=== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]

// end::is_persistence_delete_missing[]


=== is_persistence_insert

// tag::is_persistence_insert[]

// end::is_persistence_insert[]


=== is_persistence_truncate

// tag::is_persistence_truncate[]

// end::is_persistence_truncate[]


=== is_persistence_update_changed

// tag::is_persistence_update_changed[]

// end::is_persistence_update_changed[]


=== is_repo_managed

// tag::is_repo_managed[]
0
// end::is_repo_managed[]


=== is_ssas

// tag::is_ssas[]
0
// end::is_ssas[]


=== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


=== MS_Description

// tag::ms_description[]

// end::ms_description[]


=== persistence_source_RepoObject_fullname

// tag::persistence_source_repoobject_fullname[]

// end::persistence_source_repoobject_fullname[]


=== persistence_source_RepoObject_fullname2

// tag::persistence_source_repoobject_fullname2[]

// end::persistence_source_repoobject_fullname2[]


=== persistence_source_RepoObject_guid

// tag::persistence_source_repoobject_guid[]

// end::persistence_source_repoobject_guid[]


=== persistence_source_RepoObject_xref

// tag::persistence_source_repoobject_xref[]

// end::persistence_source_repoobject_xref[]


=== pk_index_guid

// tag::pk_index_guid[]
F501BE14-1C3B-EC11-852C-A81E8446D5B0
// end::pk_index_guid[]


=== pk_IndexPatternColumnDatatype

// tag::pk_indexpatterncolumndatatype[]
varchar(50),varchar(200),varchar(8000),varchar(1000)
// end::pk_indexpatterncolumndatatype[]


=== pk_IndexPatternColumnName

// tag::pk_indexpatterncolumnname[]
AntoraModule,PackageName,TaskPath,ParameterBindingSequence
// end::pk_indexpatterncolumnname[]


=== pk_IndexSemanticGroup

// tag::pk_indexsemanticgroup[]

// end::pk_indexsemanticgroup[]


=== ReferencedObjectList

// tag::referencedobjectlist[]
* [ssis].[Package_src]
* [ssis_t].[TblControlFlow]
* [ssis_t].[TblTask_Sql_Parameter]
// end::referencedobjectlist[]


=== usp_persistence_RepoObject_guid

// tag::usp_persistence_repoobject_guid[]

// end::usp_persistence_repoobject_guid[]


=== UspExamples

// tag::uspexamples[]

// end::uspexamples[]


=== uspgenerator_usp_id

// tag::uspgenerator_usp_id[]

// end::uspgenerator_usp_id[]


=== UspParameters

// tag::uspparameters[]

// end::uspparameters[]

== Boolean Attributes

source: property.RepoObjectProperty WHERE property_int = 1

// tag::boolean_attributes[]


// end::boolean_attributes[]

== PlantUML diagrams

=== PlantUML Entity

// tag::puml_entity[]
[plantuml, entity-{docname}, svg, subs=macros]
....
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis.packagetask_sql_parameter_src.adoc[]" as ssis.PackageTask_Sql_Parameter_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **TaskPath** : (varchar(8000))
  **ParameterBindingSequence** : (varchar(1000))
  - ControlFlowDetailsRowID : (int)
  ParameterBindingParameterName : (varchar(1000))
  ResultSetParameterName : (varchar(1000))
  --
}
....

// end::puml_entity[]

=== PlantUML Entity 1 1 FK

// tag::puml_entity_1_1_fk[]
[plantuml, entity_1_1_fk-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis.packagetask_sql_parameter_src.adoc[]" as ssis.PackageTask_Sql_Parameter_src << V >> {
- **PK_PackageTask_Sql_Parameter_src**

..
AntoraModule; varchar(50)
PackageName; varchar(200)
TaskPath; varchar(8000)
ParameterBindingSequence; varchar(1000)
--
- idx_PackageTask_Sql_Parameter_src__2

..
ControlFlowDetailsRowID; int
--
- idx_PackageTask_Sql_Parameter_src__3

..
AntoraModule; varchar(50)
PackageName; varchar(200)
--
- idx_PackageTask_Sql_Parameter_src__4

..
AntoraModule; varchar(50)
}



footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_fk[]

=== PlantUML 1 1 ObjectRef

// tag::puml_entity_1_1_objectref[]
[plantuml, entity_1_1_objectref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis.package_src.adoc[]" as ssis.Package_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_sql_parameter_src.adoc[]" as ssis.PackageTask_Sql_Parameter_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **TaskPath** : (varchar(8000))
  **ParameterBindingSequence** : (varchar(1000))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_sql_parameter_tgt.adoc[]" as ssis.PackageTask_Sql_Parameter_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **TaskPath** : (varchar(8000))
  **ParameterBindingSequence** : (varchar(1000))
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packagetask_sql_parameter_tgt.adoc[]" as ssis.usp_PERSIST_PackageTask_Sql_Parameter_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tblcontrolflow.adoc[]" as ssis_t.TblControlFlow << U >> {
  - **ControlFlowDetailsRowID** : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_sql_parameter.adoc[]" as ssis_t.TblTask_Sql_Parameter << U >> {
  --
}

ssis.Package_src <.. ssis.PackageTask_Sql_Parameter_src
ssis.PackageTask_Sql_Parameter_src <.. ssis.PackageTask_Sql_Parameter_tgt
ssis.PackageTask_Sql_Parameter_src <.. ssis.usp_PERSIST_PackageTask_Sql_Parameter_tgt
ssis_t.TblControlFlow <.. ssis.PackageTask_Sql_Parameter_src
ssis_t.TblTask_Sql_Parameter <.. ssis.PackageTask_Sql_Parameter_src

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_objectref[]

=== PlantUML 30 0 ObjectRef

// tag::puml_entity_30_0_objectref[]
[plantuml, entity_30_0_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis.package_src.adoc[]" as ssis.Package_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_sql_parameter_src.adoc[]" as ssis.PackageTask_Sql_Parameter_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **TaskPath** : (varchar(8000))
  **ParameterBindingSequence** : (varchar(1000))
  --
}

entity "puml-link:dhw:sqldb:ssis.project.adoc[]" as ssis.Project << U >> {
  - **AntoraModule** : (varchar(50))
  --
}

entity "puml-link:dhw:sqldb:ssis_t.pkgstats.adoc[]" as ssis_t.pkgStats << U >> {
  - **RowID** : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tblcontrolflow.adoc[]" as ssis_t.TblControlFlow << U >> {
  - **ControlFlowDetailsRowID** : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_sql_parameter.adoc[]" as ssis_t.TblTask_Sql_Parameter << U >> {
  --
}

ssis.Package_src <.. ssis.PackageTask_Sql_Parameter_src
ssis.Project <.. ssis.Package_src
ssis_t.pkgStats <.. ssis.Package_src
ssis_t.TblControlFlow <.. ssis.PackageTask_Sql_Parameter_src
ssis_t.TblTask_Sql_Parameter <.. ssis.PackageTask_Sql_Parameter_src

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_30_0_objectref[]

=== PlantUML 0 30 ObjectRef

// tag::puml_entity_0_30_objectref[]
[plantuml, entity_0_30_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:docs.ssis_adoc.adoc[]" as docs.ssis_Adoc << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageBasename** : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_adoc_t.adoc[]" as docs.ssis_Adoc_T << U >> {
  - **AntoraModule** : (varchar(50))
  **PackageBasename** : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_sqltaskparameterinnertable.adoc[]" as docs.ssis_SqlTaskParameterInnerTable << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_task.adoc[]" as docs.ssis_Task << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_tasklist.adoc[]" as docs.ssis_TaskList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport.adoc[]" as docs.usp_AntoraExport << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_ssispartialscontent.adoc[]" as docs.usp_AntoraExport_SsisPartialsContent << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_ssis_adoc_t.adoc[]" as docs.usp_PERSIST_ssis_Adoc_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_sql_parameter.adoc[]" as ssis.PackageTask_Sql_Parameter << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_sql_parameter_src.adoc[]" as ssis.PackageTask_Sql_Parameter_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **TaskPath** : (varchar(8000))
  **ParameterBindingSequence** : (varchar(1000))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_sql_parameter_tgt.adoc[]" as ssis.PackageTask_Sql_Parameter_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **TaskPath** : (varchar(8000))
  **ParameterBindingSequence** : (varchar(1000))
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_import.adoc[]" as ssis.usp_import << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packagetask_sql_parameter_tgt.adoc[]" as ssis.usp_PERSIST_PackageTask_Sql_Parameter_tgt << P >> {
  --
}

docs.ssis_Adoc <.. docs.ssis_Adoc_T
docs.ssis_Adoc <.. docs.usp_PERSIST_ssis_Adoc_T
docs.ssis_Adoc_T <.. docs.usp_PERSIST_ssis_Adoc_T
docs.ssis_Adoc_T <.. docs.usp_AntoraExport_SsisPartialsContent
docs.ssis_SqlTaskParameterInnerTable <.. docs.ssis_Task
docs.ssis_SqlTaskParameterInnerTable <.. docs.ssis_TaskList
docs.ssis_TaskList <.. docs.ssis_Adoc
docs.usp_AntoraExport_SsisPartialsContent <.. docs.usp_AntoraExport
docs.usp_PERSIST_ssis_Adoc_T <.. docs.usp_AntoraExport_SsisPartialsContent
ssis.PackageTask_Sql_Parameter <.. docs.ssis_SqlTaskParameterInnerTable
ssis.PackageTask_Sql_Parameter_src <.. ssis.PackageTask_Sql_Parameter_tgt
ssis.PackageTask_Sql_Parameter_src <.. ssis.usp_PERSIST_PackageTask_Sql_Parameter_tgt
ssis.PackageTask_Sql_Parameter_tgt <.. ssis.PackageTask_Sql_Parameter
ssis.PackageTask_Sql_Parameter_tgt <.. ssis.usp_PERSIST_PackageTask_Sql_Parameter_tgt
ssis.usp_PERSIST_PackageTask_Sql_Parameter_tgt <.. ssis.usp_import

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_0_30_objectref[]

=== PlantUML 1 1 ColumnRef

// tag::puml_entity_1_1_colref[]
[plantuml, entity_1_1_colref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis.package_src.adoc[]" as ssis.Package_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  PackageCreationDate : (datetime)
  PackageCreatorComputerName : (nvarchar(500))
  PackageCreatorName : (varchar(1000))
  PackageDescription : (nvarchar(max))
  PackageDTSID : (uniqueidentifier)
  PackageLastModifiedProductVersion : (nvarchar(500))
  PackageLocaleID : (int)
  PackageObjectName : (nvarchar(500))
  - PackagePath : (varchar(8000))
  PackageProtectionLevel : (varchar(100))
  PackageProtectionLevelName : (varchar(28))
  PackageVersionGUID : (uniqueidentifier)
  - ProjectPath : (varchar(8000))
  - RowID : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_sql_parameter_src.adoc[]" as ssis.PackageTask_Sql_Parameter_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **TaskPath** : (varchar(8000))
  **ParameterBindingSequence** : (varchar(1000))
  - ControlFlowDetailsRowID : (int)
  ParameterBindingParameterName : (varchar(1000))
  ResultSetParameterName : (varchar(1000))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_sql_parameter_tgt.adoc[]" as ssis.PackageTask_Sql_Parameter_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **TaskPath** : (varchar(8000))
  **ParameterBindingSequence** : (varchar(1000))
  - ControlFlowDetailsRowID : (int)
  ParameterBindingParameterName : (varchar(1000))
  ResultSetParameterName : (varchar(1000))
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packagetask_sql_parameter_tgt.adoc[]" as ssis.usp_PERSIST_PackageTask_Sql_Parameter_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tblcontrolflow.adoc[]" as ssis_t.TblControlFlow << U >> {
  - **ControlFlowDetailsRowID** : (int)
  DelayValidationPropertyValue : (varchar(100))
  DFTQuery : (xml)
  ExecPkgTaskQry : (xml)
  ExpressionValue : (varchar(5000))
  IsDisabled : (varchar(10))
  RowID : (int)
  ScriptTaskQry : (xml)
  SqlTaskQry : (xml)
  TaskDescription : (varchar(max))
  TaskName : (varchar(2000))
  TaskPath : (varchar(8000))
  TaskType : (varchar(5000))
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_sql_parameter.adoc[]" as ssis_t.TblTask_Sql_Parameter << U >> {
  ControlFlowDetailsRowID : (int)
  ParameterBindingParameterName : (varchar(1000))
  ParameterBindingSequence : (varchar(1000))
  ResultSetParameterName : (varchar(1000))
  RowID : (int)
  --
}

ssis.Package_src <.. ssis.PackageTask_Sql_Parameter_src
ssis.PackageTask_Sql_Parameter_src <.. ssis.PackageTask_Sql_Parameter_tgt
ssis.PackageTask_Sql_Parameter_src <.. ssis.usp_PERSIST_PackageTask_Sql_Parameter_tgt
ssis_t.TblControlFlow <.. ssis.PackageTask_Sql_Parameter_src
ssis_t.TblTask_Sql_Parameter <.. ssis.PackageTask_Sql_Parameter_src
"ssis.Package_src::AntoraModule" <-- "ssis.PackageTask_Sql_Parameter_src::AntoraModule"
"ssis.Package_src::PackageName" <-- "ssis.PackageTask_Sql_Parameter_src::PackageName"
"ssis.PackageTask_Sql_Parameter_src::AntoraModule" <-- "ssis.PackageTask_Sql_Parameter_tgt::AntoraModule"
"ssis.PackageTask_Sql_Parameter_src::ControlFlowDetailsRowID" <-- "ssis.PackageTask_Sql_Parameter_tgt::ControlFlowDetailsRowID"
"ssis.PackageTask_Sql_Parameter_src::PackageName" <-- "ssis.PackageTask_Sql_Parameter_tgt::PackageName"
"ssis.PackageTask_Sql_Parameter_src::ParameterBindingParameterName" <-- "ssis.PackageTask_Sql_Parameter_tgt::ParameterBindingParameterName"
"ssis.PackageTask_Sql_Parameter_src::ParameterBindingSequence" <-- "ssis.PackageTask_Sql_Parameter_tgt::ParameterBindingSequence"
"ssis.PackageTask_Sql_Parameter_src::ResultSetParameterName" <-- "ssis.PackageTask_Sql_Parameter_tgt::ResultSetParameterName"
"ssis.PackageTask_Sql_Parameter_src::TaskPath" <-- "ssis.PackageTask_Sql_Parameter_tgt::TaskPath"
"ssis_t.TblControlFlow::ControlFlowDetailsRowID" <-- "ssis.PackageTask_Sql_Parameter_src::ControlFlowDetailsRowID"
"ssis_t.TblControlFlow::TaskPath" <-- "ssis.PackageTask_Sql_Parameter_src::TaskPath"
"ssis_t.TblTask_Sql_Parameter::ParameterBindingParameterName" <-- "ssis.PackageTask_Sql_Parameter_src::ParameterBindingParameterName"
"ssis_t.TblTask_Sql_Parameter::ParameterBindingSequence" <-- "ssis.PackageTask_Sql_Parameter_src::ParameterBindingSequence"
"ssis_t.TblTask_Sql_Parameter::ResultSetParameterName" <-- "ssis.PackageTask_Sql_Parameter_src::ResultSetParameterName"

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_colref[]


== sql_modules_definition

// tag::sql_modules_definition[]
[%collapsible]
=======
[source,sql,numbered,indent=0]
----



--todo:
--hier fehlt das eigentliche Skipt
--ssis_t.TblSQLTaskDetails enthält nur die n:1 Details wie ParameterBinding
--es gibt noch die Daten zum eigentlichen SQL Task XML [SqlTaskQry]
--das muss noch separat bestimmt werden
--entweder in der Granularität von ssis_t.TblControlFlowDetails
--oder als separate Sicht ssis.PackageTaskSql_src
CREATE View [ssis].[PackageTask_Sql_Parameter_src]
As
Select
    p.AntoraModule
  , p.PackageName
  , T2.TaskPath
  , T3.ParameterBindingSequence
  , T3.ResultSetParameterName
  , T3.ParameterBindingParameterName
  , T2.ControlFlowDetailsRowID
From
    ssis.Package_src                 As p
    Inner Join
        ssis_t.TblControlFlow        As T2
            On
            p.RowID                    = T2.RowID

    Inner Join
        ssis_t.TblTask_Sql_Parameter As T3
            On
            T3.ControlFlowDetailsRowID = T2.ControlFlowDetailsRowID
Where
    Not T3.ParameterBindingSequence Is Null

----
=======
// end::sql_modules_definition[]


