// tag::HeaderFullDisplayName[]
= ssis.PackageTask_Dft_Component_input_externalMetadataColumn_tgt - V
// end::HeaderFullDisplayName[]

== existing_properties

// tag::existing_properties[]

:ExistsProperty--antorareferencedlist:
:ExistsProperty--antorareferencinglist:
:ExistsProperty--has_history:
:ExistsProperty--has_history_columns:
:ExistsProperty--inheritancetype:
:ExistsProperty--is_persistence:
:ExistsProperty--is_persistence_check_duplicate_per_pk:
:ExistsProperty--is_persistence_check_for_empty_source:
:ExistsProperty--is_persistence_delete_changed:
:ExistsProperty--is_persistence_delete_missing:
:ExistsProperty--is_persistence_insert:
:ExistsProperty--is_persistence_truncate:
:ExistsProperty--is_persistence_update_changed:
:ExistsProperty--is_repo_managed:
:ExistsProperty--is_ssas:
:ExistsProperty--persistence_source_repoobject_fullname:
:ExistsProperty--persistence_source_repoobject_fullname2:
:ExistsProperty--persistence_source_repoobject_guid:
:ExistsProperty--persistence_source_repoobject_xref:
:ExistsProperty--pk_index_guid:
:ExistsProperty--pk_indexpatterncolumndatatype:
:ExistsProperty--pk_indexpatterncolumnname:
:ExistsProperty--referencedobjectlist:
:ExistsProperty--usp_persistence_repoobject_guid:
:ExistsProperty--sql_modules_definition:
:ExistsProperty--FK:
:ExistsProperty--AntoraIndexList:
:ExistsProperty--Columns:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
0B32C7D6-D13F-EC11-852D-A81E8446D5B0
// end::RepoObject_guid[]

== RepoObject_FullDisplayName2

// tag::RepoObject_FullDisplayName2[]
ssis.PackageTask_Dft_Component_input_externalMetadataColumn_tgt
// end::RepoObject_FullDisplayName2[]

== SysObject_type

// tag::SysObject_type[]
V 
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
view
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
862678171
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2021-11-07 14:57:11
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]
[discrete]
== _


[#column-antoramodule]
=== AntoraModule

[cols="d,8a,m,m,m"]
|===
|1
|*AntoraModule*
|varchar(50)
|NOT NULL
|
|===

.Referenced Columns
--
* xref:ssis.packagetask_dft_component_input_externalmetadatacolumn.adoc#column-antoramodule[+ssis.PackageTask_Dft_Component_input_externalMetadataColumn.AntoraModule+]
* xref:ssis.packagetask_dft_component_input_externalmetadatacolumn_src.adoc#column-antoramodule[+ssis.PackageTask_Dft_Component_input_externalMetadataColumn_src.AntoraModule+]
--


[#column-packagename]
=== PackageName

[cols="d,8a,m,m,m"]
|===
|2
|*PackageName*
|varchar(200)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis.packagetask_dft_component_input_externalmetadatacolumn.adoc#column-packagename[+ssis.PackageTask_Dft_Component_input_externalMetadataColumn.PackageName+]
* xref:ssis.packagetask_dft_component_input_externalmetadatacolumn_src.adoc#column-packagename[+ssis.PackageTask_Dft_Component_input_externalMetadataColumn_src.PackageName+]
--


[#column-columnunderlinerefid]
=== Column_refId

[cols="d,8a,m,m,m"]
|===
|3
|*Column_refId*
|varchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis.packagetask_dft_component_input_externalmetadatacolumn.adoc#column-columnunderlinerefid[+ssis.PackageTask_Dft_Component_input_externalMetadataColumn.Column_refId+]
* xref:ssis.packagetask_dft_component_input_externalmetadatacolumn_src.adoc#column-columnunderlinerefid[+ssis.PackageTask_Dft_Component_input_externalMetadataColumn_src.Column_refId+]
--


[#column-columnunderlinedatatype]
=== Column_dataType

[cols="d,8a,m,m,m"]
|===
|
|Column_dataType
|varchar(100)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis.packagetask_dft_component_input_externalmetadatacolumn.adoc#column-columnunderlinedatatype[+ssis.PackageTask_Dft_Component_input_externalMetadataColumn.Column_dataType+]
* xref:ssis.packagetask_dft_component_input_externalmetadatacolumn_src.adoc#column-columnunderlinedatatype[+ssis.PackageTask_Dft_Component_input_externalMetadataColumn_src.Column_dataType+]
--


[#column-columnunderlinelength]
=== Column_length

[cols="d,8a,m,m,m"]
|===
|
|Column_length
|int
|NULL
|
|===

.Referenced Columns
--
* xref:ssis.packagetask_dft_component_input_externalmetadatacolumn.adoc#column-columnunderlinelength[+ssis.PackageTask_Dft_Component_input_externalMetadataColumn.Column_length+]
* xref:ssis.packagetask_dft_component_input_externalmetadatacolumn_src.adoc#column-columnunderlinelength[+ssis.PackageTask_Dft_Component_input_externalMetadataColumn_src.Column_length+]
--


[#column-columnunderlinename]
=== Column_name

[cols="d,8a,m,m,m"]
|===
|
|Column_name
|varchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis.packagetask_dft_component_input_externalmetadatacolumn.adoc#column-columnunderlinename[+ssis.PackageTask_Dft_Component_input_externalMetadataColumn.Column_name+]
* xref:ssis.packagetask_dft_component_input_externalmetadatacolumn_src.adoc#column-columnunderlinename[+ssis.PackageTask_Dft_Component_input_externalMetadataColumn_src.Column_name+]
--


[#column-columnunderlineprecision]
=== Column_precision

[cols="d,8a,m,m,m"]
|===
|
|Column_precision
|int
|NULL
|
|===

.Referenced Columns
--
* xref:ssis.packagetask_dft_component_input_externalmetadatacolumn.adoc#column-columnunderlineprecision[+ssis.PackageTask_Dft_Component_input_externalMetadataColumn.Column_precision+]
* xref:ssis.packagetask_dft_component_input_externalmetadatacolumn_src.adoc#column-columnunderlineprecision[+ssis.PackageTask_Dft_Component_input_externalMetadataColumn_src.Column_precision+]
--


[#column-columnunderlinescale]
=== Column_scale

[cols="d,8a,m,m,m"]
|===
|
|Column_scale
|int
|NULL
|
|===

.Referenced Columns
--
* xref:ssis.packagetask_dft_component_input_externalmetadatacolumn.adoc#column-columnunderlinescale[+ssis.PackageTask_Dft_Component_input_externalMetadataColumn.Column_scale+]
* xref:ssis.packagetask_dft_component_input_externalmetadatacolumn_src.adoc#column-columnunderlinescale[+ssis.PackageTask_Dft_Component_input_externalMetadataColumn_src.Column_scale+]
--


[#column-componentunderlinerefid]
=== Component_refId

[cols="d,8a,m,m,m"]
|===
|
|Component_refId
|varchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis.packagetask_dft_component_input_externalmetadatacolumn.adoc#column-componentunderlinerefid[+ssis.PackageTask_Dft_Component_input_externalMetadataColumn.Component_refId+]
* xref:ssis.packagetask_dft_component_input_externalmetadatacolumn_src.adoc#column-componentunderlinerefid[+ssis.PackageTask_Dft_Component_input_externalMetadataColumn_src.Component_refId+]
--


[#column-controlflowdetailsrowid]
=== ControlFlowDetailsRowID

[cols="d,8a,m,m,m"]
|===
|
|ControlFlowDetailsRowID
|int
|NOT NULL
|
|===

.Referenced Columns
--
* xref:ssis.packagetask_dft_component_input_externalmetadatacolumn.adoc#column-controlflowdetailsrowid[+ssis.PackageTask_Dft_Component_input_externalMetadataColumn.ControlFlowDetailsRowID+]
* xref:ssis.packagetask_dft_component_input_externalmetadatacolumn_src.adoc#column-controlflowdetailsrowid[+ssis.PackageTask_Dft_Component_input_externalMetadataColumn_src.ControlFlowDetailsRowID+]
--


[#column-externalmetadatacolumnsunderlineisused]
=== externalMetadataColumns_isused

[cols="d,8a,m,m,m"]
|===
|
|externalMetadataColumns_isused
|bit
|NULL
|
|===

.Referenced Columns
--
* xref:ssis.packagetask_dft_component_input_externalmetadatacolumn.adoc#column-externalmetadatacolumnsunderlineisused[+ssis.PackageTask_Dft_Component_input_externalMetadataColumn.externalMetadataColumns_isused+]
* xref:ssis.packagetask_dft_component_input_externalmetadatacolumn_src.adoc#column-externalmetadatacolumnsunderlineisused[+ssis.PackageTask_Dft_Component_input_externalMetadataColumn_src.externalMetadataColumns_isused+]
--


[#column-inputunderlineerrorortruncationoperation]
=== input_errorOrTruncationOperation

[cols="d,8a,m,m,m"]
|===
|
|input_errorOrTruncationOperation
|varchar(100)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis.packagetask_dft_component_input_externalmetadatacolumn.adoc#column-inputunderlineerrorortruncationoperation[+ssis.PackageTask_Dft_Component_input_externalMetadataColumn.input_errorOrTruncationOperation+]
* xref:ssis.packagetask_dft_component_input_externalmetadatacolumn_src.adoc#column-inputunderlineerrorortruncationoperation[+ssis.PackageTask_Dft_Component_input_externalMetadataColumn_src.input_errorOrTruncationOperation+]
--


[#column-inputunderlineerrorrowdisposition]
=== input_errorRowDisposition

[cols="d,8a,m,m,m"]
|===
|
|input_errorRowDisposition
|varchar(100)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis.packagetask_dft_component_input_externalmetadatacolumn.adoc#column-inputunderlineerrorrowdisposition[+ssis.PackageTask_Dft_Component_input_externalMetadataColumn.input_errorRowDisposition+]
* xref:ssis.packagetask_dft_component_input_externalmetadatacolumn_src.adoc#column-inputunderlineerrorrowdisposition[+ssis.PackageTask_Dft_Component_input_externalMetadataColumn_src.input_errorRowDisposition+]
--


[#column-inputunderlinehassideeffects]
=== input_hasSideEffects

[cols="d,8a,m,m,m"]
|===
|
|input_hasSideEffects
|bit
|NULL
|
|===

.Referenced Columns
--
* xref:ssis.packagetask_dft_component_input_externalmetadatacolumn.adoc#column-inputunderlinehassideeffects[+ssis.PackageTask_Dft_Component_input_externalMetadataColumn.input_hasSideEffects+]
* xref:ssis.packagetask_dft_component_input_externalmetadatacolumn_src.adoc#column-inputunderlinehassideeffects[+ssis.PackageTask_Dft_Component_input_externalMetadataColumn_src.input_hasSideEffects+]
--


[#column-inputunderlinename]
=== input_name

[cols="d,8a,m,m,m"]
|===
|
|input_name
|varchar(500)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis.packagetask_dft_component_input_externalmetadatacolumn.adoc#column-inputunderlinename[+ssis.PackageTask_Dft_Component_input_externalMetadataColumn.input_name+]
* xref:ssis.packagetask_dft_component_input_externalmetadatacolumn_src.adoc#column-inputunderlinename[+ssis.PackageTask_Dft_Component_input_externalMetadataColumn_src.input_name+]
--


[#column-inputunderlinerefid]
=== input_refId

[cols="d,8a,m,m,m"]
|===
|
|input_refId
|varchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis.packagetask_dft_component_input_externalmetadatacolumn.adoc#column-inputunderlinerefid[+ssis.PackageTask_Dft_Component_input_externalMetadataColumn.input_refId+]
* xref:ssis.packagetask_dft_component_input_externalmetadatacolumn_src.adoc#column-inputunderlinerefid[+ssis.PackageTask_Dft_Component_input_externalMetadataColumn_src.input_refId+]
--


[#column-taskpath]
=== TaskPath

[cols="d,8a,m,m,m"]
|===
|
|TaskPath
|varchar(8000)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis.packagetask_dft_component_input_externalmetadatacolumn.adoc#column-taskpath[+ssis.PackageTask_Dft_Component_input_externalMetadataColumn.TaskPath+]
* xref:ssis.packagetask_dft_component_input_externalmetadatacolumn_src.adoc#column-taskpath[+ssis.PackageTask_Dft_Component_input_externalMetadataColumn_src.TaskPath+]
--


// end::AntoraColumnDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]
|1
|*<<column-antoramodule>>*
|varchar(50)
|NOT NULL
|

|2
|*<<column-packagename>>*
|varchar(200)
|NULL
|

|3
|*<<column-columnunderlinerefid>>*
|varchar(max)
|NULL
|















// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]



|
|<<column-columnunderlinedatatype>>
|varchar(100)
|NULL
|

|
|<<column-columnunderlinelength>>
|int
|NULL
|

|
|<<column-columnunderlinename>>
|varchar(max)
|NULL
|

|
|<<column-columnunderlineprecision>>
|int
|NULL
|

|
|<<column-columnunderlinescale>>
|int
|NULL
|

|
|<<column-componentunderlinerefid>>
|varchar(max)
|NULL
|

|
|<<column-controlflowdetailsrowid>>
|int
|NOT NULL
|

|
|<<column-externalmetadatacolumnsunderlineisused>>
|bit
|NULL
|

|
|<<column-inputunderlineerrorortruncationoperation>>
|varchar(100)
|NULL
|

|
|<<column-inputunderlineerrorrowdisposition>>
|varchar(100)
|NULL
|

|
|<<column-inputunderlinehassideeffects>>
|bit
|NULL
|

|
|<<column-inputunderlinename>>
|varchar(500)
|NULL
|

|
|<<column-inputunderlinerefid>>
|varchar(max)
|NULL
|

|
|<<column-taskpath>>
|varchar(8000)
|NULL
|

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

[#index-pkunderlinepackagetaskunderlinedftunderlinecomponentunderlineinputunderlineexternalmetadatacolumnunderlinetgt]
=== PK_PackageTask_Dft_Component_input_externalMetadataColumn_tgt

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-AntoraModule>>; varchar(50)
* <<column-PackageName>>; varchar(200)
* <<column-Column_refId>>; varchar(max)
--
* PK, Unique, Real: 1, 1, 0


[#index-idxunderlinepackagetaskunderlinedftunderlinecomponentunderlineinputunderlineexternalmetadatacolumnunderlinetgtunderlineunderline2]
=== idx_PackageTask_Dft_Component_input_externalMetadataColumn_tgt++__++2

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-AntoraModule>>; varchar(50)
* <<column-PackageName>>; varchar(200)
--
* PK, Unique, Real: 0, 0, 0


[#index-idxunderlinepackagetaskunderlinedftunderlinecomponentunderlineinputunderlineexternalmetadatacolumnunderlinetgtunderlineunderline3]
=== idx_PackageTask_Dft_Component_input_externalMetadataColumn_tgt++__++3

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-AntoraModule>>; varchar(50)
--
* PK, Unique, Real: 0, 0, 0

// end::AntoraIndexList[]

== AntoraMeasureDetails

// tag::AntoraMeasureDetails[]

// end::AntoraMeasureDetails[]

== AntoraMeasureDescriptions



== AntoraParameterList

// tag::AntoraParameterList[]

// end::AntoraParameterList[]

== AntoraXrefCulturesList

// tag::AntoraXrefCulturesList[]
* xref:dhw:sqldb:ssis.packagetask_dft_component_input_externalmetadatacolumn_tgt.adoc[] - 
// end::AntoraXrefCulturesList[]

== cultures_count

// tag::cultures_count[]
1
// end::cultures_count[]

== Other tags

source: property.RepoObjectProperty_cross As rop_cross


=== additional_reference_csv

// tag::additional_reference_csv[]

// end::additional_reference_csv[]


=== AdocUspSteps

// tag::adocuspsteps[]

// end::adocuspsteps[]


=== AntoraReferencedList

// tag::antorareferencedlist[]
* xref:dhw:sqldb:ssis.antoramodule_tgt_filter.adoc[]
* xref:dhw:sqldb:ssis.packagetask_dft_component_input_externalmetadatacolumn_src.adoc[]
// end::antorareferencedlist[]


=== AntoraReferencingList

// tag::antorareferencinglist[]
* xref:dhw:sqldb:ssis.packagetask_dft_component_input_externalmetadatacolumn.adoc[]
* xref:dhw:sqldb:ssis.usp_persist_packagetask_dft_component_input_externalmetadatacolumn_tgt.adoc[]
// end::antorareferencinglist[]


=== Description

// tag::description[]

// end::description[]


=== exampleUsage

// tag::exampleusage[]

// end::exampleusage[]


=== exampleUsage_2

// tag::exampleusage_2[]

// end::exampleusage_2[]


=== exampleUsage_3

// tag::exampleusage_3[]

// end::exampleusage_3[]


=== exampleUsage_4

// tag::exampleusage_4[]

// end::exampleusage_4[]


=== exampleUsage_5

// tag::exampleusage_5[]

// end::exampleusage_5[]


=== exampleWrong_Usage

// tag::examplewrong_usage[]

// end::examplewrong_usage[]


=== has_execution_plan_issue

// tag::has_execution_plan_issue[]

// end::has_execution_plan_issue[]


=== has_get_referenced_issue

// tag::has_get_referenced_issue[]

// end::has_get_referenced_issue[]


=== has_history

// tag::has_history[]
0
// end::has_history[]


=== has_history_columns

// tag::has_history_columns[]
0
// end::has_history_columns[]


=== InheritanceType

// tag::inheritancetype[]
13
// end::inheritancetype[]


=== is_persistence

// tag::is_persistence[]
1
// end::is_persistence[]


=== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]
0
// end::is_persistence_check_duplicate_per_pk[]


=== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]
0
// end::is_persistence_check_for_empty_source[]


=== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]
0
// end::is_persistence_delete_changed[]


=== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]
1
// end::is_persistence_delete_missing[]


=== is_persistence_insert

// tag::is_persistence_insert[]
1
// end::is_persistence_insert[]


=== is_persistence_truncate

// tag::is_persistence_truncate[]
0
// end::is_persistence_truncate[]


=== is_persistence_update_changed

// tag::is_persistence_update_changed[]
1
// end::is_persistence_update_changed[]


=== is_repo_managed

// tag::is_repo_managed[]
0
// end::is_repo_managed[]


=== is_ssas

// tag::is_ssas[]
0
// end::is_ssas[]


=== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


=== MS_Description

// tag::ms_description[]

// end::ms_description[]


=== persistence_source_RepoObject_fullname

// tag::persistence_source_repoobject_fullname[]
[ssis].[PackageTask_Dft_Component_input_externalMetadataColumn_src]
// end::persistence_source_repoobject_fullname[]


=== persistence_source_RepoObject_fullname2

// tag::persistence_source_repoobject_fullname2[]
ssis.PackageTask_Dft_Component_input_externalMetadataColumn_src
// end::persistence_source_repoobject_fullname2[]


=== persistence_source_RepoObject_guid

// tag::persistence_source_repoobject_guid[]
7BCC7FC6-CF3F-EC11-852D-A81E8446D5B0
// end::persistence_source_repoobject_guid[]


=== persistence_source_RepoObject_xref

// tag::persistence_source_repoobject_xref[]
xref:ssis.packagetask_dft_component_input_externalmetadatacolumn_src.adoc[]
// end::persistence_source_repoobject_xref[]


=== pk_index_guid

// tag::pk_index_guid[]
03346EB1-D73F-EC11-852D-A81E8446D5B0
// end::pk_index_guid[]


=== pk_IndexPatternColumnDatatype

// tag::pk_indexpatterncolumndatatype[]
varchar(50),varchar(200),varchar(max)
// end::pk_indexpatterncolumndatatype[]


=== pk_IndexPatternColumnName

// tag::pk_indexpatterncolumnname[]
AntoraModule,PackageName,Column_refId
// end::pk_indexpatterncolumnname[]


=== pk_IndexSemanticGroup

// tag::pk_indexsemanticgroup[]

// end::pk_indexsemanticgroup[]


=== ReferencedObjectList

// tag::referencedobjectlist[]
* [ssis].[AntoraModule_tgt_filter]
* [ssis].[PackageTask_Dft_Component_input_externalMetadataColumn]
* [ssis].[PackageTask_Dft_Component_input_externalMetadataColumn_src]
// end::referencedobjectlist[]


=== usp_persistence_RepoObject_guid

// tag::usp_persistence_repoobject_guid[]
23950354-DC3F-EC11-852D-A81E8446D5B0
// end::usp_persistence_repoobject_guid[]


=== UspExamples

// tag::uspexamples[]

// end::uspexamples[]


=== uspgenerator_usp_id

// tag::uspgenerator_usp_id[]

// end::uspgenerator_usp_id[]


=== UspParameters

// tag::uspparameters[]

// end::uspparameters[]

== Boolean Attributes

source: property.RepoObjectProperty WHERE property_int = 1

// tag::boolean_attributes[]

:is_persistence:
:is_persistence_delete_missing:
:is_persistence_insert:
:is_persistence_update_changed:

// end::boolean_attributes[]

== PlantUML diagrams

=== PlantUML Entity

// tag::puml_entity[]
[plantuml, entity-{docname}, svg, subs=macros]
....
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_input_externalmetadatacolumn_tgt.adoc[]" as ssis.PackageTask_Dft_Component_input_externalMetadataColumn_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Column_refId** : (varchar(max))
  Column_dataType : (varchar(100))
  Column_length : (int)
  Column_name : (varchar(max))
  Column_precision : (int)
  Column_scale : (int)
  Component_refId : (varchar(max))
  - ControlFlowDetailsRowID : (int)
  externalMetadataColumns_isused : (bit)
  input_errorOrTruncationOperation : (varchar(100))
  input_errorRowDisposition : (varchar(100))
  input_hasSideEffects : (bit)
  input_name : (varchar(500))
  input_refId : (varchar(max))
  TaskPath : (varchar(8000))
  --
}
....

// end::puml_entity[]

=== PlantUML Entity 1 1 FK

// tag::puml_entity_1_1_fk[]
[plantuml, entity_1_1_fk-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_input_externalmetadatacolumn_tgt.adoc[]" as ssis.PackageTask_Dft_Component_input_externalMetadataColumn_tgt << V >> {
- **PK_PackageTask_Dft_Component_input_externalMetadataColumn_tgt**

..
AntoraModule; varchar(50)
PackageName; varchar(200)
Column_refId; varchar(max)
--
- idx_PackageTask_Dft_Component_input_externalMetadataColumn_tgt__2

..
AntoraModule; varchar(50)
PackageName; varchar(200)
--
- idx_PackageTask_Dft_Component_input_externalMetadataColumn_tgt__3

..
AntoraModule; varchar(50)
}



footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_fk[]

=== PlantUML 1 1 ObjectRef

// tag::puml_entity_1_1_objectref[]
[plantuml, entity_1_1_objectref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis.antoramodule_tgt_filter.adoc[]" as ssis.AntoraModule_tgt_filter << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_input_externalmetadatacolumn.adoc[]" as ssis.PackageTask_Dft_Component_input_externalMetadataColumn << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_input_externalmetadatacolumn_src.adoc[]" as ssis.PackageTask_Dft_Component_input_externalMetadataColumn_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Column_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_input_externalmetadatacolumn_tgt.adoc[]" as ssis.PackageTask_Dft_Component_input_externalMetadataColumn_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Column_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packagetask_dft_component_input_externalmetadatacolumn_tgt.adoc[]" as ssis.usp_PERSIST_PackageTask_Dft_Component_input_externalMetadataColumn_tgt << P >> {
  --
}

ssis.AntoraModule_tgt_filter <.. ssis.PackageTask_Dft_Component_input_externalMetadataColumn_tgt
ssis.PackageTask_Dft_Component_input_externalMetadataColumn_src <.. ssis.PackageTask_Dft_Component_input_externalMetadataColumn_tgt
ssis.PackageTask_Dft_Component_input_externalMetadataColumn_tgt <.. ssis.PackageTask_Dft_Component_input_externalMetadataColumn
ssis.PackageTask_Dft_Component_input_externalMetadataColumn_tgt <.. ssis.usp_PERSIST_PackageTask_Dft_Component_input_externalMetadataColumn_tgt

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_objectref[]

=== PlantUML 30 0 ObjectRef

// tag::puml_entity_30_0_objectref[]
[plantuml, entity_30_0_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis.antoramodule_tgt_filter.adoc[]" as ssis.AntoraModule_tgt_filter << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.package_src.adoc[]" as ssis.Package_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_input_externalmetadatacolumn_src.adoc[]" as ssis.PackageTask_Dft_Component_input_externalMetadataColumn_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Column_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_input_externalmetadatacolumn_tgt.adoc[]" as ssis.PackageTask_Dft_Component_input_externalMetadataColumn_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Column_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.project.adoc[]" as ssis.Project << U >> {
  - **AntoraModule** : (varchar(50))
  --
}

entity "puml-link:dhw:sqldb:ssis_t.pkgstats.adoc[]" as ssis_t.pkgStats << U >> {
  - **RowID** : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tblcontrolflow.adoc[]" as ssis_t.TblControlFlow << U >> {
  - **ControlFlowDetailsRowID** : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_dft_component.adoc[]" as ssis_t.TblTask_Dft_Component << U >> {
  - **DftComponentId** : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_dft_component_inputs_externalmetadatacolumn_src.adoc[]" as ssis_t.TblTask_Dft_Component_inputs_externalMetadataColumn_src << V >> {
  --
}

ssis.AntoraModule_tgt_filter <.. ssis.PackageTask_Dft_Component_input_externalMetadataColumn_tgt
ssis.Package_src <.. ssis.PackageTask_Dft_Component_input_externalMetadataColumn_src
ssis.Package_src <.. ssis.AntoraModule_tgt_filter
ssis.PackageTask_Dft_Component_input_externalMetadataColumn_src <.. ssis.PackageTask_Dft_Component_input_externalMetadataColumn_tgt
ssis.Project <.. ssis.Package_src
ssis_t.pkgStats <.. ssis.Package_src
ssis_t.TblControlFlow <.. ssis.PackageTask_Dft_Component_input_externalMetadataColumn_src
ssis_t.TblTask_Dft_Component <.. ssis_t.TblTask_Dft_Component_inputs_externalMetadataColumn_src
ssis_t.TblTask_Dft_Component_inputs_externalMetadataColumn_src <.. ssis.PackageTask_Dft_Component_input_externalMetadataColumn_src

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_30_0_objectref[]

=== PlantUML 0 30 ObjectRef

// tag::puml_entity_0_30_objectref[]
[plantuml, entity_0_30_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:docs.ssis_adoc.adoc[]" as docs.ssis_Adoc << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageBasename** : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_adoc_t.adoc[]" as docs.ssis_Adoc_T << U >> {
  - **AntoraModule** : (varchar(50))
  **PackageBasename** : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_dfttaskcomponentinputcolumnlist.adoc[]" as docs.ssis_DftTaskComponentInputColumnList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_dfttaskcomponentinputlist.adoc[]" as docs.ssis_DftTaskComponentInputList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_dfttaskcomponentlist.adoc[]" as docs.ssis_DftTaskComponentList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_dfttaskcomponentoutputcolumnlist.adoc[]" as docs.ssis_DftTaskComponentOutputColumnList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_dfttaskcomponentoutputlist.adoc[]" as docs.ssis_DftTaskComponentOutputList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_task.adoc[]" as docs.ssis_Task << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_tasklist.adoc[]" as docs.ssis_TaskList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport.adoc[]" as docs.usp_AntoraExport << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_ssispartialscontent.adoc[]" as docs.usp_AntoraExport_SsisPartialsContent << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_ssis_adoc_t.adoc[]" as docs.usp_PERSIST_ssis_Adoc_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_input_externalmetadatacolumn.adoc[]" as ssis.PackageTask_Dft_Component_input_externalMetadataColumn << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_input_externalmetadatacolumn_tgt.adoc[]" as ssis.PackageTask_Dft_Component_input_externalMetadataColumn_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Column_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_import.adoc[]" as ssis.usp_import << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packagetask_dft_component_input_externalmetadatacolumn_tgt.adoc[]" as ssis.usp_PERSIST_PackageTask_Dft_Component_input_externalMetadataColumn_tgt << P >> {
  --
}

docs.ssis_Adoc <.. docs.usp_PERSIST_ssis_Adoc_T
docs.ssis_Adoc <.. docs.ssis_Adoc_T
docs.ssis_Adoc_T <.. docs.usp_AntoraExport_SsisPartialsContent
docs.ssis_Adoc_T <.. docs.usp_PERSIST_ssis_Adoc_T
docs.ssis_DftTaskComponentInputColumnList <.. docs.ssis_DftTaskComponentInputList
docs.ssis_DftTaskComponentInputList <.. docs.ssis_DftTaskComponentList
docs.ssis_DftTaskComponentList <.. docs.ssis_TaskList
docs.ssis_DftTaskComponentList <.. docs.ssis_Task
docs.ssis_DftTaskComponentOutputColumnList <.. docs.ssis_DftTaskComponentOutputList
docs.ssis_DftTaskComponentOutputList <.. docs.ssis_DftTaskComponentList
docs.ssis_TaskList <.. docs.ssis_Adoc
docs.usp_AntoraExport_SsisPartialsContent <.. docs.usp_AntoraExport
docs.usp_PERSIST_ssis_Adoc_T <.. docs.usp_AntoraExport_SsisPartialsContent
ssis.PackageTask_Dft_Component_input_externalMetadataColumn <.. docs.ssis_DftTaskComponentInputColumnList
ssis.PackageTask_Dft_Component_input_externalMetadataColumn <.. docs.ssis_DftTaskComponentOutputColumnList
ssis.PackageTask_Dft_Component_input_externalMetadataColumn_tgt <.. ssis.PackageTask_Dft_Component_input_externalMetadataColumn
ssis.PackageTask_Dft_Component_input_externalMetadataColumn_tgt <.. ssis.usp_PERSIST_PackageTask_Dft_Component_input_externalMetadataColumn_tgt
ssis.usp_PERSIST_PackageTask_Dft_Component_input_externalMetadataColumn_tgt <.. ssis.usp_import

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_0_30_objectref[]

=== PlantUML 1 1 ColumnRef

// tag::puml_entity_1_1_colref[]
[plantuml, entity_1_1_colref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis.antoramodule_tgt_filter.adoc[]" as ssis.AntoraModule_tgt_filter << V >> {
  - AntoraModule : (varchar(50))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_input_externalmetadatacolumn.adoc[]" as ssis.PackageTask_Dft_Component_input_externalMetadataColumn << U >> {
  - AntoraModule : (varchar(50))
  Column_dataType : (varchar(100))
  Column_length : (int)
  Column_name : (varchar(max))
  Column_precision : (int)
  Column_refId : (varchar(max))
  Column_scale : (int)
  Component_refId : (varchar(max))
  - ControlFlowDetailsRowID : (int)
  externalMetadataColumns_isused : (bit)
  input_errorOrTruncationOperation : (varchar(100))
  input_errorRowDisposition : (varchar(100))
  input_hasSideEffects : (bit)
  input_name : (varchar(500))
  input_refId : (varchar(max))
  PackageName : (varchar(200))
  TaskPath : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_input_externalmetadatacolumn_src.adoc[]" as ssis.PackageTask_Dft_Component_input_externalMetadataColumn_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Column_refId** : (varchar(max))
  Column_dataType : (varchar(100))
  Column_length : (int)
  Column_name : (varchar(max))
  Column_precision : (int)
  Column_scale : (int)
  Component_refId : (varchar(max))
  - ControlFlowDetailsRowID : (int)
  externalMetadataColumns_isused : (bit)
  input_errorOrTruncationOperation : (varchar(100))
  input_errorRowDisposition : (varchar(100))
  input_hasSideEffects : (bit)
  input_name : (varchar(500))
  input_refId : (varchar(max))
  TaskPath : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_input_externalmetadatacolumn_tgt.adoc[]" as ssis.PackageTask_Dft_Component_input_externalMetadataColumn_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Column_refId** : (varchar(max))
  Column_dataType : (varchar(100))
  Column_length : (int)
  Column_name : (varchar(max))
  Column_precision : (int)
  Column_scale : (int)
  Component_refId : (varchar(max))
  - ControlFlowDetailsRowID : (int)
  externalMetadataColumns_isused : (bit)
  input_errorOrTruncationOperation : (varchar(100))
  input_errorRowDisposition : (varchar(100))
  input_hasSideEffects : (bit)
  input_name : (varchar(500))
  input_refId : (varchar(max))
  TaskPath : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packagetask_dft_component_input_externalmetadatacolumn_tgt.adoc[]" as ssis.usp_PERSIST_PackageTask_Dft_Component_input_externalMetadataColumn_tgt << P >> {
  --
}

ssis.AntoraModule_tgt_filter <.. ssis.PackageTask_Dft_Component_input_externalMetadataColumn_tgt
ssis.PackageTask_Dft_Component_input_externalMetadataColumn_src <.. ssis.PackageTask_Dft_Component_input_externalMetadataColumn_tgt
ssis.PackageTask_Dft_Component_input_externalMetadataColumn_tgt <.. ssis.PackageTask_Dft_Component_input_externalMetadataColumn
ssis.PackageTask_Dft_Component_input_externalMetadataColumn_tgt <.. ssis.usp_PERSIST_PackageTask_Dft_Component_input_externalMetadataColumn_tgt
"ssis.PackageTask_Dft_Component_input_externalMetadataColumn::AntoraModule" <-- "ssis.PackageTask_Dft_Component_input_externalMetadataColumn_tgt::AntoraModule"
"ssis.PackageTask_Dft_Component_input_externalMetadataColumn::Column_dataType" <-- "ssis.PackageTask_Dft_Component_input_externalMetadataColumn_tgt::Column_dataType"
"ssis.PackageTask_Dft_Component_input_externalMetadataColumn::Column_length" <-- "ssis.PackageTask_Dft_Component_input_externalMetadataColumn_tgt::Column_length"
"ssis.PackageTask_Dft_Component_input_externalMetadataColumn::Column_name" <-- "ssis.PackageTask_Dft_Component_input_externalMetadataColumn_tgt::Column_name"
"ssis.PackageTask_Dft_Component_input_externalMetadataColumn::Column_precision" <-- "ssis.PackageTask_Dft_Component_input_externalMetadataColumn_tgt::Column_precision"
"ssis.PackageTask_Dft_Component_input_externalMetadataColumn::Column_refId" <-- "ssis.PackageTask_Dft_Component_input_externalMetadataColumn_tgt::Column_refId"
"ssis.PackageTask_Dft_Component_input_externalMetadataColumn::Column_scale" <-- "ssis.PackageTask_Dft_Component_input_externalMetadataColumn_tgt::Column_scale"
"ssis.PackageTask_Dft_Component_input_externalMetadataColumn::Component_refId" <-- "ssis.PackageTask_Dft_Component_input_externalMetadataColumn_tgt::Component_refId"
"ssis.PackageTask_Dft_Component_input_externalMetadataColumn::ControlFlowDetailsRowID" <-- "ssis.PackageTask_Dft_Component_input_externalMetadataColumn_tgt::ControlFlowDetailsRowID"
"ssis.PackageTask_Dft_Component_input_externalMetadataColumn::externalMetadataColumns_isused" <-- "ssis.PackageTask_Dft_Component_input_externalMetadataColumn_tgt::externalMetadataColumns_isused"
"ssis.PackageTask_Dft_Component_input_externalMetadataColumn::input_errorOrTruncationOperation" <-- "ssis.PackageTask_Dft_Component_input_externalMetadataColumn_tgt::input_errorOrTruncationOperation"
"ssis.PackageTask_Dft_Component_input_externalMetadataColumn::input_errorRowDisposition" <-- "ssis.PackageTask_Dft_Component_input_externalMetadataColumn_tgt::input_errorRowDisposition"
"ssis.PackageTask_Dft_Component_input_externalMetadataColumn::input_hasSideEffects" <-- "ssis.PackageTask_Dft_Component_input_externalMetadataColumn_tgt::input_hasSideEffects"
"ssis.PackageTask_Dft_Component_input_externalMetadataColumn::input_name" <-- "ssis.PackageTask_Dft_Component_input_externalMetadataColumn_tgt::input_name"
"ssis.PackageTask_Dft_Component_input_externalMetadataColumn::input_refId" <-- "ssis.PackageTask_Dft_Component_input_externalMetadataColumn_tgt::input_refId"
"ssis.PackageTask_Dft_Component_input_externalMetadataColumn::PackageName" <-- "ssis.PackageTask_Dft_Component_input_externalMetadataColumn_tgt::PackageName"
"ssis.PackageTask_Dft_Component_input_externalMetadataColumn::TaskPath" <-- "ssis.PackageTask_Dft_Component_input_externalMetadataColumn_tgt::TaskPath"
"ssis.PackageTask_Dft_Component_input_externalMetadataColumn_src::AntoraModule" <-- "ssis.PackageTask_Dft_Component_input_externalMetadataColumn_tgt::AntoraModule"
"ssis.PackageTask_Dft_Component_input_externalMetadataColumn_src::Column_dataType" <-- "ssis.PackageTask_Dft_Component_input_externalMetadataColumn_tgt::Column_dataType"
"ssis.PackageTask_Dft_Component_input_externalMetadataColumn_src::Column_length" <-- "ssis.PackageTask_Dft_Component_input_externalMetadataColumn_tgt::Column_length"
"ssis.PackageTask_Dft_Component_input_externalMetadataColumn_src::Column_name" <-- "ssis.PackageTask_Dft_Component_input_externalMetadataColumn_tgt::Column_name"
"ssis.PackageTask_Dft_Component_input_externalMetadataColumn_src::Column_precision" <-- "ssis.PackageTask_Dft_Component_input_externalMetadataColumn_tgt::Column_precision"
"ssis.PackageTask_Dft_Component_input_externalMetadataColumn_src::Column_refId" <-- "ssis.PackageTask_Dft_Component_input_externalMetadataColumn_tgt::Column_refId"
"ssis.PackageTask_Dft_Component_input_externalMetadataColumn_src::Column_scale" <-- "ssis.PackageTask_Dft_Component_input_externalMetadataColumn_tgt::Column_scale"
"ssis.PackageTask_Dft_Component_input_externalMetadataColumn_src::Component_refId" <-- "ssis.PackageTask_Dft_Component_input_externalMetadataColumn_tgt::Component_refId"
"ssis.PackageTask_Dft_Component_input_externalMetadataColumn_src::ControlFlowDetailsRowID" <-- "ssis.PackageTask_Dft_Component_input_externalMetadataColumn_tgt::ControlFlowDetailsRowID"
"ssis.PackageTask_Dft_Component_input_externalMetadataColumn_src::externalMetadataColumns_isused" <-- "ssis.PackageTask_Dft_Component_input_externalMetadataColumn_tgt::externalMetadataColumns_isused"
"ssis.PackageTask_Dft_Component_input_externalMetadataColumn_src::input_errorOrTruncationOperation" <-- "ssis.PackageTask_Dft_Component_input_externalMetadataColumn_tgt::input_errorOrTruncationOperation"
"ssis.PackageTask_Dft_Component_input_externalMetadataColumn_src::input_errorRowDisposition" <-- "ssis.PackageTask_Dft_Component_input_externalMetadataColumn_tgt::input_errorRowDisposition"
"ssis.PackageTask_Dft_Component_input_externalMetadataColumn_src::input_hasSideEffects" <-- "ssis.PackageTask_Dft_Component_input_externalMetadataColumn_tgt::input_hasSideEffects"
"ssis.PackageTask_Dft_Component_input_externalMetadataColumn_src::input_name" <-- "ssis.PackageTask_Dft_Component_input_externalMetadataColumn_tgt::input_name"
"ssis.PackageTask_Dft_Component_input_externalMetadataColumn_src::input_refId" <-- "ssis.PackageTask_Dft_Component_input_externalMetadataColumn_tgt::input_refId"
"ssis.PackageTask_Dft_Component_input_externalMetadataColumn_src::PackageName" <-- "ssis.PackageTask_Dft_Component_input_externalMetadataColumn_tgt::PackageName"
"ssis.PackageTask_Dft_Component_input_externalMetadataColumn_src::TaskPath" <-- "ssis.PackageTask_Dft_Component_input_externalMetadataColumn_tgt::TaskPath"

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_colref[]


== sql_modules_definition

// tag::sql_modules_definition[]
[%collapsible]
=======
[source,sql,numbered,indent=0]
----
create View [ssis].[PackageTask_Dft_Component_input_externalMetadataColumn_tgt]
As
Select
    tgt.AntoraModule
  , tgt.PackageName
  , tgt.Component_refId
  , tgt.input_refId
  , tgt.input_errorOrTruncationOperation
  , tgt.input_errorRowDisposition
  , tgt.input_hasSideEffects
  , tgt.input_name
  , tgt.externalMetadataColumns_isused
  , tgt.Column_refId
  , tgt.Column_name
  , tgt.Column_dataType
  , tgt.Column_length
  , tgt.Column_precision
  , tgt.Column_scale
  , tgt.TaskPath
  , tgt.ControlFlowDetailsRowID
From
    ssis.PackageTask_Dft_Component_input_externalMetadataColumn As tgt
Where
    Exists
(
    Select
        1
    From
        ssis.AntoraModule_tgt_filter As f
    Where
        tgt.AntoraModule = f.AntoraModule
)

----
=======
// end::sql_modules_definition[]


