// tag::HeaderFullDisplayName[]
= ssis_t.TblTask_Dft_Component_outputs_outputColumn_src - V
// end::HeaderFullDisplayName[]

== existing_properties

// tag::existing_properties[]

:ExistsProperty--antorareferencedlist:
:ExistsProperty--antorareferencinglist:
:ExistsProperty--is_repo_managed:
:ExistsProperty--is_ssas:
:ExistsProperty--referencedobjectlist:
:ExistsProperty--sql_modules_definition:
:ExistsProperty--FK:
:ExistsProperty--AntoraIndexList:
:ExistsProperty--Columns:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
B3DCAD7F-F73E-EC11-852D-A81E8446D5B0
// end::RepoObject_guid[]

== RepoObject_FullDisplayName2

// tag::RepoObject_FullDisplayName2[]
ssis_t.TblTask_Dft_Component_outputs_outputColumn_src
// end::RepoObject_FullDisplayName2[]

== SysObject_type

// tag::SysObject_type[]
V 
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
view
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
158675663
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2021-11-07 12:43:14
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]
[discrete]
== _


[#column-columnunderlinedatatype]
=== Column_dataType

[cols="d,8a,m,m,m"]
|===
|
|Column_dataType
|varchar(100)
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_output_outputcolumn_src.adoc#column-columnunderlinedatatype[+ssis.PackageTask_Dft_Component_output_outputcolumn_src.Column_dataType+]
--


[#column-columnunderlineerrorortruncationoperation]
=== Column_errorOrTruncationOperation

[cols="d,8a,m,m,m"]
|===
|
|Column_errorOrTruncationOperation
|varchar(100)
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_output_outputcolumn_src.adoc#column-columnunderlineerrorortruncationoperation[+ssis.PackageTask_Dft_Component_output_outputcolumn_src.Column_errorOrTruncationOperation+]
--


[#column-columnunderlineerrorrowdisposition]
=== Column_errorRowDisposition

[cols="d,8a,m,m,m"]
|===
|
|Column_errorRowDisposition
|varchar(100)
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_output_outputcolumn_src.adoc#column-columnunderlineerrorrowdisposition[+ssis.PackageTask_Dft_Component_output_outputcolumn_src.Column_errorRowDisposition+]
--


[#column-columnunderlineexternalmetadatacolumnid]
=== Column_externalMetadataColumnId

[cols="d,8a,m,m,m"]
|===
|
|Column_externalMetadataColumnId
|varchar(max)
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_output_outputcolumn_src.adoc#column-columnunderlineexternalmetadatacolumnid[+ssis.PackageTask_Dft_Component_output_outputcolumn_src.Column_externalMetadataColumnId+]
--


[#column-columnunderlinelength]
=== Column_length

[cols="d,8a,m,m,m"]
|===
|
|Column_length
|int
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_output_outputcolumn_src.adoc#column-columnunderlinelength[+ssis.PackageTask_Dft_Component_output_outputcolumn_src.Column_length+]
--


[#column-columnunderlinelineageid]
=== Column_lineageId

[cols="d,8a,m,m,m"]
|===
|
|Column_lineageId
|varchar(max)
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_output_outputcolumn_src.adoc#column-columnunderlinelineageid[+ssis.PackageTask_Dft_Component_output_outputcolumn_src.Column_lineageId+]
--


[#column-columnunderlinename]
=== Column_name

[cols="d,8a,m,m,m"]
|===
|
|Column_name
|varchar(max)
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_output_outputcolumn_src.adoc#column-columnunderlinename[+ssis.PackageTask_Dft_Component_output_outputcolumn_src.Column_name+]
--


[#column-columnunderlineprecision]
=== Column_precision

[cols="d,8a,m,m,m"]
|===
|
|Column_precision
|int
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_output_outputcolumn_src.adoc#column-columnunderlineprecision[+ssis.PackageTask_Dft_Component_output_outputcolumn_src.Column_precision+]
--


[#column-columnunderlinerefid]
=== Column_refId

[cols="d,8a,m,m,m"]
|===
|
|Column_refId
|varchar(max)
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_output_outputcolumn_src.adoc#column-columnunderlinerefid[+ssis.PackageTask_Dft_Component_output_outputcolumn_src.Column_refId+]
--


[#column-columnunderlinescale]
=== Column_scale

[cols="d,8a,m,m,m"]
|===
|
|Column_scale
|int
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_output_outputcolumn_src.adoc#column-columnunderlinescale[+ssis.PackageTask_Dft_Component_output_outputcolumn_src.Column_scale+]
--


[#column-columnunderlinetruncationrowdisposition]
=== Column_truncationRowDisposition

[cols="d,8a,m,m,m"]
|===
|
|Column_truncationRowDisposition
|varchar(max)
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_output_outputcolumn_src.adoc#column-columnunderlinetruncationrowdisposition[+ssis.PackageTask_Dft_Component_output_outputcolumn_src.Column_truncationRowDisposition+]
--


[#column-columnscontent]
=== columnscontent

[cols="d,8a,m,m,m"]
|===
|
|columnscontent
|xml
|NULL
|
|===


[#column-controlflowdetailsrowid]
=== ControlFlowDetailsRowID

[cols="d,8a,m,m,m"]
|===
|
|ControlFlowDetailsRowID
|int
|NOT NULL
|
|===

.Referenced Columns
--
* xref:ssis_t.tbltask_dft_component.adoc#column-controlflowdetailsrowid[+ssis_t.TblTask_Dft_Component.ControlFlowDetailsRowID+]
--

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_output_outputcolumn_src.adoc#column-controlflowdetailsrowid[+ssis.PackageTask_Dft_Component_output_outputcolumn_src.ControlFlowDetailsRowID+]
--


[#column-dftcomponentid]
=== DftComponentId

[cols="d,8a,m,m,m"]
|===
|
|DftComponentId
|int
|NOT NULL
|
|===

.Referenced Columns
--
* xref:ssis_t.tbltask_dft_component.adoc#column-dftcomponentid[+ssis_t.TblTask_Dft_Component.DftComponentId+]
--


[#column-nodescontent]
=== nodescontent

[cols="d,8a,m,m,m"]
|===
|
|nodescontent
|xml
|NULL
|
|===


[#column-outputunderlineiserrorout]
=== output_isErrorOut

[cols="d,8a,m,m,m"]
|===
|
|output_isErrorOut
|bit
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_output_outputcolumn_src.adoc#column-outputunderlineiserrorout[+ssis.PackageTask_Dft_Component_output_outputcolumn_src.output_isErrorOut+]
--


[#column-outputunderlinename]
=== output_name

[cols="d,8a,m,m,m"]
|===
|
|output_name
|varchar(500)
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_output_outputcolumn_src.adoc#column-outputunderlinename[+ssis.PackageTask_Dft_Component_output_outputcolumn_src.output_name+]
--


[#column-outputunderlinerefid]
=== output_refId

[cols="d,8a,m,m,m"]
|===
|
|output_refId
|varchar(max)
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_output_outputcolumn_src.adoc#column-outputunderlinerefid[+ssis.PackageTask_Dft_Component_output_outputcolumn_src.output_refId+]
--


[#column-refid]
=== refId

[cols="d,8a,m,m,m"]
|===
|
|refId
|varchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:ssis_t.tbltask_dft_component.adoc#column-refid[+ssis_t.TblTask_Dft_Component.refId+]
--

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_output_outputcolumn_src.adoc#column-componentunderlinerefid[+ssis.PackageTask_Dft_Component_output_outputcolumn_src.Component_refId+]
--


[#column-rowid]
=== RowID

[cols="d,8a,m,m,m"]
|===
|
|RowID
|int
|NULL
|
|===

.Referenced Columns
--
* xref:ssis_t.tbltask_dft_component.adoc#column-rowid[+ssis_t.TblTask_Dft_Component.RowID+]
--


// end::AntoraColumnDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]




















// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]
|
|<<column-columnunderlinedatatype>>
|varchar(100)
|NULL
|

|
|<<column-columnunderlineerrorortruncationoperation>>
|varchar(100)
|NULL
|

|
|<<column-columnunderlineerrorrowdisposition>>
|varchar(100)
|NULL
|

|
|<<column-columnunderlineexternalmetadatacolumnid>>
|varchar(max)
|NULL
|

|
|<<column-columnunderlinelength>>
|int
|NULL
|

|
|<<column-columnunderlinelineageid>>
|varchar(max)
|NULL
|

|
|<<column-columnunderlinename>>
|varchar(max)
|NULL
|

|
|<<column-columnunderlineprecision>>
|int
|NULL
|

|
|<<column-columnunderlinerefid>>
|varchar(max)
|NULL
|

|
|<<column-columnunderlinescale>>
|int
|NULL
|

|
|<<column-columnunderlinetruncationrowdisposition>>
|varchar(max)
|NULL
|

|
|<<column-columnscontent>>
|xml
|NULL
|

|
|<<column-controlflowdetailsrowid>>
|int
|NOT NULL
|

|
|<<column-dftcomponentid>>
|int
|NOT NULL
|

|
|<<column-nodescontent>>
|xml
|NULL
|

|
|<<column-outputunderlineiserrorout>>
|bit
|NULL
|

|
|<<column-outputunderlinename>>
|varchar(500)
|NULL
|

|
|<<column-outputunderlinerefid>>
|varchar(max)
|NULL
|

|
|<<column-refid>>
|varchar(max)
|NULL
|

|
|<<column-rowid>>
|int
|NULL
|

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

[#index-idxunderlinetbltaskunderlinedftunderlinecomponentunderlineoutputsunderlineoutputcolumnunderlinesrcunderlineunderline1]
=== idx_TblTask_Dft_Component_outputs_outputColumn_src++__++1

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-DftComponentId>>; int
--
* PK, Unique, Real: 0, 0, 0

// end::AntoraIndexList[]

== AntoraMeasureDetails

// tag::AntoraMeasureDetails[]

// end::AntoraMeasureDetails[]

== AntoraMeasureDescriptions



== AntoraParameterList

// tag::AntoraParameterList[]

// end::AntoraParameterList[]

== AntoraXrefCulturesList

// tag::AntoraXrefCulturesList[]
* xref:dhw:sqldb:ssis_t.tbltask_dft_component_outputs_outputcolumn_src.adoc[] - 
// end::AntoraXrefCulturesList[]

== cultures_count

// tag::cultures_count[]
1
// end::cultures_count[]

== Other tags

source: property.RepoObjectProperty_cross As rop_cross


=== additional_reference_csv

// tag::additional_reference_csv[]

// end::additional_reference_csv[]


=== AdocUspSteps

// tag::adocuspsteps[]

// end::adocuspsteps[]


=== AntoraReferencedList

// tag::antorareferencedlist[]
* xref:dhw:sqldb:ssis_t.tbltask_dft_component.adoc[]
// end::antorareferencedlist[]


=== AntoraReferencingList

// tag::antorareferencinglist[]
* xref:dhw:sqldb:ssis.packagetask_dft_component_output_outputcolumn_src.adoc[]
// end::antorareferencinglist[]


=== Description

// tag::description[]

// end::description[]


=== exampleUsage

// tag::exampleusage[]

// end::exampleusage[]


=== exampleUsage_2

// tag::exampleusage_2[]

// end::exampleusage_2[]


=== exampleUsage_3

// tag::exampleusage_3[]

// end::exampleusage_3[]


=== exampleUsage_4

// tag::exampleusage_4[]

// end::exampleusage_4[]


=== exampleUsage_5

// tag::exampleusage_5[]

// end::exampleusage_5[]


=== exampleWrong_Usage

// tag::examplewrong_usage[]

// end::examplewrong_usage[]


=== has_execution_plan_issue

// tag::has_execution_plan_issue[]

// end::has_execution_plan_issue[]


=== has_get_referenced_issue

// tag::has_get_referenced_issue[]

// end::has_get_referenced_issue[]


=== has_history

// tag::has_history[]

// end::has_history[]


=== has_history_columns

// tag::has_history_columns[]

// end::has_history_columns[]


=== InheritanceType

// tag::inheritancetype[]

// end::inheritancetype[]


=== is_persistence

// tag::is_persistence[]

// end::is_persistence[]


=== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]

// end::is_persistence_check_duplicate_per_pk[]


=== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]

// end::is_persistence_check_for_empty_source[]


=== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]

// end::is_persistence_delete_changed[]


=== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]

// end::is_persistence_delete_missing[]


=== is_persistence_insert

// tag::is_persistence_insert[]

// end::is_persistence_insert[]


=== is_persistence_truncate

// tag::is_persistence_truncate[]

// end::is_persistence_truncate[]


=== is_persistence_update_changed

// tag::is_persistence_update_changed[]

// end::is_persistence_update_changed[]


=== is_repo_managed

// tag::is_repo_managed[]
0
// end::is_repo_managed[]


=== is_ssas

// tag::is_ssas[]
0
// end::is_ssas[]


=== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


=== MS_Description

// tag::ms_description[]

// end::ms_description[]


=== persistence_source_RepoObject_fullname

// tag::persistence_source_repoobject_fullname[]

// end::persistence_source_repoobject_fullname[]


=== persistence_source_RepoObject_fullname2

// tag::persistence_source_repoobject_fullname2[]

// end::persistence_source_repoobject_fullname2[]


=== persistence_source_RepoObject_guid

// tag::persistence_source_repoobject_guid[]

// end::persistence_source_repoobject_guid[]


=== persistence_source_RepoObject_xref

// tag::persistence_source_repoobject_xref[]

// end::persistence_source_repoobject_xref[]


=== pk_index_guid

// tag::pk_index_guid[]

// end::pk_index_guid[]


=== pk_IndexPatternColumnDatatype

// tag::pk_indexpatterncolumndatatype[]

// end::pk_indexpatterncolumndatatype[]


=== pk_IndexPatternColumnName

// tag::pk_indexpatterncolumnname[]

// end::pk_indexpatterncolumnname[]


=== pk_IndexSemanticGroup

// tag::pk_indexsemanticgroup[]

// end::pk_indexsemanticgroup[]


=== ReferencedObjectList

// tag::referencedobjectlist[]
* [ssis_t].[TblTask_Dft_Component]
// end::referencedobjectlist[]


=== usp_persistence_RepoObject_guid

// tag::usp_persistence_repoobject_guid[]

// end::usp_persistence_repoobject_guid[]


=== UspExamples

// tag::uspexamples[]

// end::uspexamples[]


=== uspgenerator_usp_id

// tag::uspgenerator_usp_id[]

// end::uspgenerator_usp_id[]


=== UspParameters

// tag::uspparameters[]

// end::uspparameters[]

== Boolean Attributes

source: property.RepoObjectProperty WHERE property_int = 1

// tag::boolean_attributes[]


// end::boolean_attributes[]

== PlantUML diagrams

=== PlantUML Entity

// tag::puml_entity[]
[plantuml, entity-{docname}, svg, subs=macros]
....
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis_t.tbltask_dft_component_outputs_outputcolumn_src.adoc[]" as ssis_t.TblTask_Dft_Component_outputs_outputColumn_src << V >> {
  Column_dataType : (varchar(100))
  Column_errorOrTruncationOperation : (varchar(100))
  Column_errorRowDisposition : (varchar(100))
  Column_externalMetadataColumnId : (varchar(max))
  Column_length : (int)
  Column_lineageId : (varchar(max))
  Column_name : (varchar(max))
  Column_precision : (int)
  Column_refId : (varchar(max))
  Column_scale : (int)
  Column_truncationRowDisposition : (varchar(max))
  columnscontent : (xml)
  - ControlFlowDetailsRowID : (int)
  - DftComponentId : (int)
  nodescontent : (xml)
  output_isErrorOut : (bit)
  output_name : (varchar(500))
  output_refId : (varchar(max))
  refId : (varchar(max))
  RowID : (int)
  --
}
....

// end::puml_entity[]

=== PlantUML Entity 1 1 FK

// tag::puml_entity_1_1_fk[]
[plantuml, entity_1_1_fk-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis_t.tbltask_dft_component_outputs_outputcolumn_src.adoc[]" as ssis_t.TblTask_Dft_Component_outputs_outputColumn_src << V >> {
- idx_TblTask_Dft_Component_outputs_outputColumn_src__1

..
DftComponentId; int
}



footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_fk[]

=== PlantUML 1 1 ObjectRef

// tag::puml_entity_1_1_objectref[]
[plantuml, entity_1_1_objectref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_output_outputcolumn_src.adoc[]" as ssis.PackageTask_Dft_Component_output_outputcolumn_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Column_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_dft_component.adoc[]" as ssis_t.TblTask_Dft_Component << U >> {
  - **DftComponentId** : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_dft_component_outputs_outputcolumn_src.adoc[]" as ssis_t.TblTask_Dft_Component_outputs_outputColumn_src << V >> {
  --
}

ssis_t.TblTask_Dft_Component <.. ssis_t.TblTask_Dft_Component_outputs_outputColumn_src
ssis_t.TblTask_Dft_Component_outputs_outputColumn_src <.. ssis.PackageTask_Dft_Component_output_outputcolumn_src

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_objectref[]

=== PlantUML 30 0 ObjectRef

// tag::puml_entity_30_0_objectref[]
[plantuml, entity_30_0_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis_t.tbltask_dft_component.adoc[]" as ssis_t.TblTask_Dft_Component << U >> {
  - **DftComponentId** : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_dft_component_outputs_outputcolumn_src.adoc[]" as ssis_t.TblTask_Dft_Component_outputs_outputColumn_src << V >> {
  --
}

ssis_t.TblTask_Dft_Component <.. ssis_t.TblTask_Dft_Component_outputs_outputColumn_src

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_30_0_objectref[]

=== PlantUML 0 30 ObjectRef

// tag::puml_entity_0_30_objectref[]
[plantuml, entity_0_30_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:docs.ssis_adoc.adoc[]" as docs.ssis_Adoc << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageBasename** : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_adoc_t.adoc[]" as docs.ssis_Adoc_T << U >> {
  - **AntoraModule** : (varchar(50))
  - **PackageBasename** : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_dfttaskcomponentlist.adoc[]" as docs.ssis_DftTaskComponentList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_dfttaskcomponentoutputcolumnlist.adoc[]" as docs.ssis_DftTaskComponentOutputColumnList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_dfttaskcomponentoutputlist.adoc[]" as docs.ssis_DftTaskComponentOutputList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_task.adoc[]" as docs.ssis_Task << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_tasklist.adoc[]" as docs.ssis_TaskList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport.adoc[]" as docs.usp_AntoraExport << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_ssispartialscontent.adoc[]" as docs.usp_AntoraExport_SsisPartialsContent << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_ssis_adoc_t.adoc[]" as docs.usp_PERSIST_ssis_Adoc_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_output_outputcolumn.adoc[]" as ssis.PackageTask_Dft_Component_output_outputcolumn << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_output_outputcolumn_src.adoc[]" as ssis.PackageTask_Dft_Component_output_outputcolumn_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Column_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_output_outputcolumn_tgt.adoc[]" as ssis.PackageTask_Dft_Component_output_outputColumn_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Column_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_import.adoc[]" as ssis.usp_import << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packagetask_dft_component_output_outputcolumn_tgt.adoc[]" as ssis.usp_PERSIST_PackageTask_Dft_Component_output_outputColumn_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_dft_component_outputs_outputcolumn_src.adoc[]" as ssis_t.TblTask_Dft_Component_outputs_outputColumn_src << V >> {
  --
}

docs.ssis_Adoc <.. docs.ssis_Adoc_T
docs.ssis_Adoc <.. docs.usp_PERSIST_ssis_Adoc_T
docs.ssis_Adoc_T <.. docs.usp_AntoraExport_SsisPartialsContent
docs.ssis_Adoc_T <.. docs.usp_PERSIST_ssis_Adoc_T
docs.ssis_DftTaskComponentList <.. docs.ssis_Task
docs.ssis_DftTaskComponentList <.. docs.ssis_TaskList
docs.ssis_DftTaskComponentOutputColumnList <.. docs.ssis_DftTaskComponentOutputList
docs.ssis_DftTaskComponentOutputList <.. docs.ssis_DftTaskComponentList
docs.ssis_TaskList <.. docs.ssis_Adoc
docs.usp_AntoraExport_SsisPartialsContent <.. docs.usp_AntoraExport
docs.usp_PERSIST_ssis_Adoc_T <.. docs.usp_AntoraExport_SsisPartialsContent
ssis.PackageTask_Dft_Component_output_outputcolumn <.. docs.ssis_DftTaskComponentOutputColumnList
ssis.PackageTask_Dft_Component_output_outputcolumn_src <.. ssis.PackageTask_Dft_Component_output_outputcolumn_tgt
ssis.PackageTask_Dft_Component_output_outputcolumn_src <.. ssis.usp_PERSIST_PackageTask_Dft_Component_output_outputColumn_tgt
ssis.PackageTask_Dft_Component_output_outputcolumn_tgt <.. ssis.PackageTask_Dft_Component_output_outputcolumn
ssis.PackageTask_Dft_Component_output_outputColumn_tgt <.. ssis.usp_PERSIST_PackageTask_Dft_Component_output_outputColumn_tgt
ssis.usp_PERSIST_PackageTask_Dft_Component_output_outputColumn_tgt <.. ssis.usp_import
ssis_t.TblTask_Dft_Component_outputs_outputColumn_src <.. ssis.PackageTask_Dft_Component_output_outputcolumn_src

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_0_30_objectref[]

=== PlantUML 1 1 ColumnRef

// tag::puml_entity_1_1_colref[]
[plantuml, entity_1_1_colref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_output_outputcolumn_src.adoc[]" as ssis.PackageTask_Dft_Component_output_outputcolumn_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Column_refId** : (varchar(max))
  Column_dataType : (varchar(100))
  Column_errorOrTruncationOperation : (varchar(100))
  Column_errorRowDisposition : (varchar(100))
  Column_externalMetadataColumnId : (varchar(max))
  Column_length : (int)
  Column_lineageId : (varchar(max))
  Column_name : (varchar(max))
  Column_precision : (int)
  Column_scale : (int)
  Column_truncationRowDisposition : (varchar(max))
  Component_refId : (varchar(max))
  - ControlFlowDetailsRowID : (int)
  output_isErrorOut : (bit)
  output_name : (varchar(500))
  output_refId : (varchar(max))
  TaskPath : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_dft_component.adoc[]" as ssis_t.TblTask_Dft_Component << U >> {
  - **DftComponentId** : (int)
  AccessMode : (varchar(max))
  AlwaysUseDefaultCodePage : (varchar(max))
  CommandTimeout : (int)
  componentClassID : (varchar(max))
  Connection_description : (varchar(max))
  Connection_name : (varchar(max))
  Connection_refId : (varchar(max))
  connectionManagerID : (varchar(max))
  connectionManagerRefId : (varchar(max))
  ContactInfo : (varchar(max))
  - ControlFlowDetailsRowID : (int)
  DefaultCodePage : (int)
  description : (varchar(max))
  FastLoadKeepIdentity : (bit)
  FastLoadKeepNulls : (bit)
  FastLoadMaxInsertCommitSize : (int)
  FastLoadOptions : (varchar(max))
  inputsQry : (xml)
  IsSortedProperty : (varchar(10))
  name : (varchar(max))
  OpenRowset : (varchar(max))
  OpenRowsetVariable : (varchar(max))
  outputsQry : (xml)
  ParameterMapping : (varchar(max))
  refId : (varchar(max))
  RowID : (int)
  SqlCommand : (varchar(max))
  SqlCommandVariable : (varchar(max))
  VariableName : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_dft_component_outputs_outputcolumn_src.adoc[]" as ssis_t.TblTask_Dft_Component_outputs_outputColumn_src << V >> {
  Column_dataType : (varchar(100))
  Column_errorOrTruncationOperation : (varchar(100))
  Column_errorRowDisposition : (varchar(100))
  Column_externalMetadataColumnId : (varchar(max))
  Column_length : (int)
  Column_lineageId : (varchar(max))
  Column_name : (varchar(max))
  Column_precision : (int)
  Column_refId : (varchar(max))
  Column_scale : (int)
  Column_truncationRowDisposition : (varchar(max))
  columnscontent : (xml)
  - ControlFlowDetailsRowID : (int)
  - DftComponentId : (int)
  nodescontent : (xml)
  output_isErrorOut : (bit)
  output_name : (varchar(500))
  output_refId : (varchar(max))
  refId : (varchar(max))
  RowID : (int)
  --
}

ssis_t.TblTask_Dft_Component <.. ssis_t.TblTask_Dft_Component_outputs_outputColumn_src
ssis_t.TblTask_Dft_Component_outputs_outputColumn_src <.. ssis.PackageTask_Dft_Component_output_outputcolumn_src
"ssis_t.TblTask_Dft_Component::ControlFlowDetailsRowID" <-- "ssis_t.TblTask_Dft_Component_outputs_outputColumn_src::ControlFlowDetailsRowID"
"ssis_t.TblTask_Dft_Component::DftComponentId" <-- "ssis_t.TblTask_Dft_Component_outputs_outputColumn_src::DftComponentId"
"ssis_t.TblTask_Dft_Component::refId" <-- "ssis_t.TblTask_Dft_Component_outputs_outputColumn_src::refId"
"ssis_t.TblTask_Dft_Component::RowID" <-- "ssis_t.TblTask_Dft_Component_outputs_outputColumn_src::RowID"
"ssis_t.TblTask_Dft_Component_outputs_outputColumn_src::Column_dataType" <-- "ssis.PackageTask_Dft_Component_output_outputcolumn_src::Column_dataType"
"ssis_t.TblTask_Dft_Component_outputs_outputColumn_src::Column_errorOrTruncationOperation" <-- "ssis.PackageTask_Dft_Component_output_outputcolumn_src::Column_errorOrTruncationOperation"
"ssis_t.TblTask_Dft_Component_outputs_outputColumn_src::Column_errorRowDisposition" <-- "ssis.PackageTask_Dft_Component_output_outputcolumn_src::Column_errorRowDisposition"
"ssis_t.TblTask_Dft_Component_outputs_outputColumn_src::Column_externalMetadataColumnId" <-- "ssis.PackageTask_Dft_Component_output_outputcolumn_src::Column_externalMetadataColumnId"
"ssis_t.TblTask_Dft_Component_outputs_outputColumn_src::Column_length" <-- "ssis.PackageTask_Dft_Component_output_outputcolumn_src::Column_length"
"ssis_t.TblTask_Dft_Component_outputs_outputColumn_src::Column_lineageId" <-- "ssis.PackageTask_Dft_Component_output_outputcolumn_src::Column_lineageId"
"ssis_t.TblTask_Dft_Component_outputs_outputColumn_src::Column_name" <-- "ssis.PackageTask_Dft_Component_output_outputcolumn_src::Column_name"
"ssis_t.TblTask_Dft_Component_outputs_outputColumn_src::Column_precision" <-- "ssis.PackageTask_Dft_Component_output_outputcolumn_src::Column_precision"
"ssis_t.TblTask_Dft_Component_outputs_outputColumn_src::Column_refId" <-- "ssis.PackageTask_Dft_Component_output_outputcolumn_src::Column_refId"
"ssis_t.TblTask_Dft_Component_outputs_outputColumn_src::Column_scale" <-- "ssis.PackageTask_Dft_Component_output_outputcolumn_src::Column_scale"
"ssis_t.TblTask_Dft_Component_outputs_outputColumn_src::Column_truncationRowDisposition" <-- "ssis.PackageTask_Dft_Component_output_outputcolumn_src::Column_truncationRowDisposition"
"ssis_t.TblTask_Dft_Component_outputs_outputColumn_src::ControlFlowDetailsRowID" <-- "ssis.PackageTask_Dft_Component_output_outputcolumn_src::ControlFlowDetailsRowID"
"ssis_t.TblTask_Dft_Component_outputs_outputColumn_src::output_isErrorOut" <-- "ssis.PackageTask_Dft_Component_output_outputcolumn_src::output_isErrorOut"
"ssis_t.TblTask_Dft_Component_outputs_outputColumn_src::output_name" <-- "ssis.PackageTask_Dft_Component_output_outputcolumn_src::output_name"
"ssis_t.TblTask_Dft_Component_outputs_outputColumn_src::output_refId" <-- "ssis.PackageTask_Dft_Component_output_outputcolumn_src::output_refId"
"ssis_t.TblTask_Dft_Component_outputs_outputColumn_src::refId" <-- "ssis.PackageTask_Dft_Component_output_outputcolumn_src::Component_refId"

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_colref[]


== sql_modules_definition

// tag::sql_modules_definition[]
[%collapsible]
=======
[source,sql,numbered,indent=0]
----
CREATE View ssis_t.TblTask_Dft_Component_outputs_outputColumn_src
As
Select
    T1.ControlFlowDetailsRowID
  , T1.RowID
  , T1.DftComponentId
  , T1.refId
  , output_refId                      = outputnodes.x.value ( '@refId[1]', 'varchar(max)' )
  , output_name                       = outputnodes.x.value ( '@name[1]', 'varchar(500)' )
  , output_isErrorOut                 = outputnodes.x.value ( '@isErrorOut[1]', 'bit' )
  , Column_refId                      = columsnodes.x.value ( '@refId[1]', 'varchar(max)' )
  , Column_name                       = columsnodes.x.value ( '@name[1]', 'varchar(max)' )
  , Column_dataType                   = columsnodes.x.value ( '@dataType[1]', 'varchar(100)' )
  , Column_length                     = columsnodes.x.value ( '@length[1]', 'int' )
  , Column_precision                  = columsnodes.x.value ( '@precision[1]', 'int' )
  , Column_scale                      = columsnodes.x.value ( '@scale[1]', 'int' )
  , Column_errorOrTruncationOperation = columsnodes.x.value ( '@errorOrTruncationOperation[1]', 'varchar(100)' )
  , Column_errorRowDisposition        = columsnodes.x.value ( '@errorRowDisposition[1]', 'varchar(100)' )
  , Column_externalMetadataColumnId   = columsnodes.x.value ( '@externalMetadataColumnId[1]', 'varchar(max)' )
  , Column_lineageId                  = columsnodes.x.value ( '@lineageId[1]', 'varchar(max)' )
  , Column_truncationRowDisposition   = columsnodes.x.value ( '@truncationRowDisposition[1]', 'varchar(max)' )

  -- to check the nodes content:
  , nodescontent                      = outputnodes.x.query ( '.' )
  , columnscontent                    = columsnodes.x.query ( '.' )
From
    ssis_t.TblTask_Dft_Component                      As T1
    Cross Apply T1.outputsQry.nodes ( './outputs/*' ) As outputnodes(x)
    Outer Apply outputnodes.x.nodes ( './outputColumns/*' ) As columsnodes(x)
Where
    --some outputs are without outputColumns
    Not columsnodes.x.value ( '@refId[1]', 'varchar(max)' ) Is Null
----
=======
// end::sql_modules_definition[]


