// tag::HeaderFullDisplayName[]
= ssis.PackageTask_Dft_Component - U
// end::HeaderFullDisplayName[]

== existing_properties

// tag::existing_properties[]

:ExistsProperty--antorareferencedlist:
:ExistsProperty--antorareferencinglist:
:ExistsProperty--is_repo_managed:
:ExistsProperty--is_ssas:
:ExistsProperty--referencedobjectlist:
:ExistsProperty--FK:
:ExistsProperty--Columns:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
B9DCAD7F-F73E-EC11-852D-A81E8446D5B0
// end::RepoObject_guid[]

== RepoObject_FullDisplayName2

// tag::RepoObject_FullDisplayName2[]
ssis.PackageTask_Dft_Component
// end::RepoObject_FullDisplayName2[]

== SysObject_type

// tag::SysObject_type[]
U 
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
user table
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
270676062
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2022-09-05 18:18:08
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]
[discrete]
== _


[#column-antoramodule]
=== AntoraModule

[cols="d,8a,m,m,m"]
|===
|
|AntoraModule
|varchar(50)
|NOT NULL
|
|===

.Referencing Columns
--
* xref:docs.ssis_dfttaskcomponentlist.adoc#column-antoramodule[+docs.ssis_DftTaskComponentList.AntoraModule+]
* xref:docs.ssis_pumldfttask.adoc#column-antoramodule[+docs.ssis_PumlDftTask.AntoraModule+]
* xref:docs.ssis_pumlpartialdftcomponent.adoc#column-antoramodule[+docs.ssis_PumlPartialDftComponent.AntoraModule+]
* xref:ssis.packagetask_dft_component_tgt.adoc#column-antoramodule[+ssis.PackageTask_Dft_Component_tgt.AntoraModule+]
--


[#column-componentunderlineaccessmode]
=== Component_AccessMode

[cols="d,8a,m,m,m"]
|===
|
|Component_AccessMode
|varchar(max)
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_tgt.adoc#column-componentunderlineaccessmode[+ssis.PackageTask_Dft_Component_tgt.Component_AccessMode+]
--


[#column-componentunderlinealwaysusedefaultcodepage]
=== Component_AlwaysUseDefaultCodePage

[cols="d,8a,m,m,m"]
|===
|
|Component_AlwaysUseDefaultCodePage
|varchar(max)
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_tgt.adoc#column-componentunderlinealwaysusedefaultcodepage[+ssis.PackageTask_Dft_Component_tgt.Component_AlwaysUseDefaultCodePage+]
--


[#column-componentunderlinecommandtimeout]
=== Component_CommandTimeout

[cols="d,8a,m,m,m"]
|===
|
|Component_CommandTimeout
|int
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_tgt.adoc#column-componentunderlinecommandtimeout[+ssis.PackageTask_Dft_Component_tgt.Component_CommandTimeout+]
--


[#column-componentunderlinecomponentclassid]
=== Component_componentClassID

[cols="d,8a,m,m,m"]
|===
|
|Component_componentClassID
|varchar(max)
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_tgt.adoc#column-componentunderlinecomponentclassid[+ssis.PackageTask_Dft_Component_tgt.Component_componentClassID+]
--


[#column-componentunderlineconnectionunderlinedescription]
=== Component_Connection_description

[cols="d,8a,m,m,m"]
|===
|
|Component_Connection_description
|varchar(max)
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_tgt.adoc#column-componentunderlineconnectionunderlinedescription[+ssis.PackageTask_Dft_Component_tgt.Component_Connection_description+]
--


[#column-componentunderlineconnectionunderlinename]
=== Component_Connection_name

[cols="d,8a,m,m,m"]
|===
|
|Component_Connection_name
|varchar(max)
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_tgt.adoc#column-componentunderlineconnectionunderlinename[+ssis.PackageTask_Dft_Component_tgt.Component_Connection_name+]
--


[#column-componentunderlineconnectionunderlinerefid]
=== Component_Connection_refId

[cols="d,8a,m,m,m"]
|===
|
|Component_Connection_refId
|varchar(max)
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_tgt.adoc#column-componentunderlineconnectionunderlinerefid[+ssis.PackageTask_Dft_Component_tgt.Component_Connection_refId+]
--


[#column-componentunderlineconnectionmanagerid]
=== Component_connectionManagerID

[cols="d,8a,m,m,m"]
|===
|
|Component_connectionManagerID
|varchar(max)
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_tgt.adoc#column-componentunderlineconnectionmanagerid[+ssis.PackageTask_Dft_Component_tgt.Component_connectionManagerID+]
--


[#column-componentunderlineconnectionmanagerrefid]
=== Component_connectionManagerRefId

[cols="d,8a,m,m,m"]
|===
|
|Component_connectionManagerRefId
|varchar(max)
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packagetask_dft_component.adoc#column-componentunderlineconnectionmanagername[+ssis.PackageTask_Dft_Component.Component_ConnectionManagerName+]
* xref:ssis.packagetask_dft_component_tgt.adoc#column-componentunderlineconnectionmanagerrefid[+ssis.PackageTask_Dft_Component_tgt.Component_connectionManagerRefId+]
--


[#column-componentunderlinecontactinfo]
=== Component_ContactInfo

[cols="d,8a,m,m,m"]
|===
|
|Component_ContactInfo
|varchar(max)
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_tgt.adoc#column-componentunderlinecontactinfo[+ssis.PackageTask_Dft_Component_tgt.Component_ContactInfo+]
--


[#column-componentunderlinedefaultcodepage]
=== Component_DefaultCodePage

[cols="d,8a,m,m,m"]
|===
|
|Component_DefaultCodePage
|int
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_tgt.adoc#column-componentunderlinedefaultcodepage[+ssis.PackageTask_Dft_Component_tgt.Component_DefaultCodePage+]
--


[#column-componentunderlinedescription]
=== Component_description

[cols="d,8a,m,m,m"]
|===
|
|Component_description
|varchar(max)
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_tgt.adoc#column-componentunderlinedescription[+ssis.PackageTask_Dft_Component_tgt.Component_description+]
--


[#column-componentunderlinefastloadkeepidentity]
=== Component_FastLoadKeepIdentity

[cols="d,8a,m,m,m"]
|===
|
|Component_FastLoadKeepIdentity
|bit
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_tgt.adoc#column-componentunderlinefastloadkeepidentity[+ssis.PackageTask_Dft_Component_tgt.Component_FastLoadKeepIdentity+]
--


[#column-componentunderlinefastloadkeepnulls]
=== Component_FastLoadKeepNulls

[cols="d,8a,m,m,m"]
|===
|
|Component_FastLoadKeepNulls
|bit
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_tgt.adoc#column-componentunderlinefastloadkeepnulls[+ssis.PackageTask_Dft_Component_tgt.Component_FastLoadKeepNulls+]
--


[#column-componentunderlinefastloadmaxinsertcommitsize]
=== Component_FastLoadMaxInsertCommitSize

[cols="d,8a,m,m,m"]
|===
|
|Component_FastLoadMaxInsertCommitSize
|int
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_tgt.adoc#column-componentunderlinefastloadmaxinsertcommitsize[+ssis.PackageTask_Dft_Component_tgt.Component_FastLoadMaxInsertCommitSize+]
--


[#column-componentunderlinefastloadoptions]
=== Component_FastLoadOptions

[cols="d,8a,m,m,m"]
|===
|
|Component_FastLoadOptions
|varchar(max)
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_tgt.adoc#column-componentunderlinefastloadoptions[+ssis.PackageTask_Dft_Component_tgt.Component_FastLoadOptions+]
--


[#column-componentunderlineissortedproperty]
=== Component_IsSortedProperty

[cols="d,8a,m,m,m"]
|===
|
|Component_IsSortedProperty
|varchar(10)
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_tgt.adoc#column-componentunderlineissortedproperty[+ssis.PackageTask_Dft_Component_tgt.Component_IsSortedProperty+]
--


[#column-componentunderlinename]
=== Component_name

[cols="d,8a,m,m,m"]
|===
|
|Component_name
|varchar(max)
|NOT NULL
|
|===

.Referencing Columns
--
* xref:docs.ssis_pumlpartialdftcomponent.adoc#column-componentunderlinename[+docs.ssis_PumlPartialDftComponent.Component_name+]
* xref:ssis.packagetask_dft_component_tgt.adoc#column-componentunderlinename[+ssis.PackageTask_Dft_Component_tgt.Component_name+]
--


[#column-componentunderlineopenrowset]
=== Component_OpenRowset

[cols="d,8a,m,m,m"]
|===
|
|Component_OpenRowset
|varchar(max)
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_tgt.adoc#column-componentunderlineopenrowset[+ssis.PackageTask_Dft_Component_tgt.Component_OpenRowset+]
--


[#column-componentunderlineopenrowsetvariable]
=== Component_OpenRowsetVariable

[cols="d,8a,m,m,m"]
|===
|
|Component_OpenRowsetVariable
|varchar(max)
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_tgt.adoc#column-componentunderlineopenrowsetvariable[+ssis.PackageTask_Dft_Component_tgt.Component_OpenRowsetVariable+]
--


[#column-componentunderlineparametermapping]
=== Component_ParameterMapping

[cols="d,8a,m,m,m"]
|===
|
|Component_ParameterMapping
|varchar(max)
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_tgt.adoc#column-componentunderlineparametermapping[+ssis.PackageTask_Dft_Component_tgt.Component_ParameterMapping+]
--


[#column-componentunderlinerefid]
=== Component_refId

[cols="d,8a,m,m,m"]
|===
|
|Component_refId
|varchar(max)
|NOT NULL
|
|===

.Referencing Columns
--
* xref:docs.ssis_pumlpartialdftcomponent.adoc#column-componentunderlinerefid[+docs.ssis_PumlPartialDftComponent.Component_refId+]
* xref:ssis.packagetask_dft_component_tgt.adoc#column-componentunderlinerefid[+ssis.PackageTask_Dft_Component_tgt.Component_refId+]
--


[#column-componentunderlinesqlcommand]
=== Component_SqlCommand

[cols="d,8a,m,m,m"]
|===
|
|Component_SqlCommand
|varchar(max)
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_tgt.adoc#column-componentunderlinesqlcommand[+ssis.PackageTask_Dft_Component_tgt.Component_SqlCommand+]
--


[#column-componentunderlinesqlcommandvariable]
=== Component_SqlCommandVariable

[cols="d,8a,m,m,m"]
|===
|
|Component_SqlCommandVariable
|varchar(max)
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_tgt.adoc#column-componentunderlinesqlcommandvariable[+ssis.PackageTask_Dft_Component_tgt.Component_SqlCommandVariable+]
--


[#column-componentunderlinevariablename]
=== Component_VariableName

[cols="d,8a,m,m,m"]
|===
|
|Component_VariableName
|varchar(max)
|NULL
|
|===

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_tgt.adoc#column-componentunderlinevariablename[+ssis.PackageTask_Dft_Component_tgt.Component_VariableName+]
--


[#column-controlflowdetailsrowid]
=== ControlFlowDetailsRowID

[cols="d,8a,m,m,m"]
|===
|
|ControlFlowDetailsRowID
|int
|NOT NULL
|
|===

.Referencing Columns
--
* xref:ssis.packagetask_dft_component_tgt.adoc#column-controlflowdetailsrowid[+ssis.PackageTask_Dft_Component_tgt.ControlFlowDetailsRowID+]
--


[#column-packagename]
=== PackageName

[cols="d,8a,m,m,m"]
|===
|
|PackageName
|varchar(200)
|NOT NULL
|
|===

.Referencing Columns
--
* xref:docs.ssis_dfttaskcomponentlist.adoc#column-packagename[+docs.ssis_DftTaskComponentList.PackageName+]
* xref:docs.ssis_pumldfttask.adoc#column-packagename[+docs.ssis_PumlDftTask.PackageName+]
* xref:docs.ssis_pumlpartialdftcomponent.adoc#column-packagename[+docs.ssis_PumlPartialDftComponent.PackageName+]
* xref:ssis.packagetask_dft_component.adoc#column-packagebasename[+ssis.PackageTask_Dft_Component.PackageBasename+]
* xref:ssis.packagetask_dft_component_tgt.adoc#column-packagename[+ssis.PackageTask_Dft_Component_tgt.PackageName+]
--


[#column-taskpath]
=== TaskPath

[cols="d,8a,m,m,m"]
|===
|
|TaskPath
|varchar(8000)
|NOT NULL
|
|===

.Referencing Columns
--
* xref:docs.ssis_dfttaskcomponentlist.adoc#column-taskpath[+docs.ssis_DftTaskComponentList.TaskPath+]
* xref:docs.ssis_pumldfttask.adoc#column-taskpath[+docs.ssis_PumlDftTask.TaskPath+]
* xref:docs.ssis_pumlpartialdftcomponent.adoc#column-taskpath[+docs.ssis_PumlPartialDftComponent.TaskPath+]
* xref:ssis.packagetask_dft_component_tgt.adoc#column-taskpath[+ssis.PackageTask_Dft_Component_tgt.TaskPath+]
--


[#column-componentunderlineconnectionmanagername]
=== Component_ConnectionManagerName

[cols="d,8a,m,m,m"]
|===
|
|Component_ConnectionManagerName

.Definition
[source,sql]
----
(case when left([Component_connectionManagerRefId],(26))='Project.ConnectionManagers' OR left([Component_connectionManagerRefId],(26))='Package.ConnectionManagers' then substring([Component_connectionManagerRefId],(28),len([Component_connectionManagerRefId])-(28))  end)
----


|varchar(max)
|NULL
|
|===

.Description
--
(case when left([Component_connectionManagerRefId],(26))='Project.ConnectionManagers' OR left([Component_connectionManagerRefId],(26))='Package.ConnectionManagers' then substring([Component_connectionManagerRefId],(28),len([Component_connectionManagerRefId])-(28))  end)
--
{empty} +

.Referenced Columns
--
* xref:ssis.packagetask_dft_component.adoc#column-componentunderlineconnectionmanagerrefid[+ssis.PackageTask_Dft_Component.Component_connectionManagerRefId+]
--


[#column-packagebasename]
=== PackageBasename

[cols="d,8a,m,m,m"]
|===
|
|PackageBasename

.Definition (PERSISTED)
[source,sql]
----
(replace([PackageName],'.dtsx',''))
----


|varchar(8000)
|NULL
|
|===

.Description
--
(replace([PackageName],'.dtsx',''))
--
{empty} +

.Referenced Columns
--
* xref:ssis.packagetask_dft_component.adoc#column-packagename[+ssis.PackageTask_Dft_Component.PackageName+]
--


// end::AntoraColumnDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]































// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]
|
|<<column-antoramodule>>
|varchar(50)
|NOT NULL
|

|
|<<column-componentunderlineaccessmode>>
|varchar(max)
|NULL
|

|
|<<column-componentunderlinealwaysusedefaultcodepage>>
|varchar(max)
|NULL
|

|
|<<column-componentunderlinecommandtimeout>>
|int
|NULL
|

|
|<<column-componentunderlinecomponentclassid>>
|varchar(max)
|NULL
|

|
|<<column-componentunderlineconnectionunderlinedescription>>
|varchar(max)
|NULL
|

|
|<<column-componentunderlineconnectionunderlinename>>
|varchar(max)
|NULL
|

|
|<<column-componentunderlineconnectionunderlinerefid>>
|varchar(max)
|NULL
|

|
|<<column-componentunderlineconnectionmanagerid>>
|varchar(max)
|NULL
|

|
|<<column-componentunderlineconnectionmanagerrefid>>
|varchar(max)
|NULL
|

|
|<<column-componentunderlinecontactinfo>>
|varchar(max)
|NULL
|

|
|<<column-componentunderlinedefaultcodepage>>
|int
|NULL
|

|
|<<column-componentunderlinedescription>>
|varchar(max)
|NULL
|

|
|<<column-componentunderlinefastloadkeepidentity>>
|bit
|NULL
|

|
|<<column-componentunderlinefastloadkeepnulls>>
|bit
|NULL
|

|
|<<column-componentunderlinefastloadmaxinsertcommitsize>>
|int
|NULL
|

|
|<<column-componentunderlinefastloadoptions>>
|varchar(max)
|NULL
|

|
|<<column-componentunderlineissortedproperty>>
|varchar(10)
|NULL
|

|
|<<column-componentunderlinename>>
|varchar(max)
|NOT NULL
|

|
|<<column-componentunderlineopenrowset>>
|varchar(max)
|NULL
|

|
|<<column-componentunderlineopenrowsetvariable>>
|varchar(max)
|NULL
|

|
|<<column-componentunderlineparametermapping>>
|varchar(max)
|NULL
|

|
|<<column-componentunderlinerefid>>
|varchar(max)
|NOT NULL
|

|
|<<column-componentunderlinesqlcommand>>
|varchar(max)
|NULL
|

|
|<<column-componentunderlinesqlcommandvariable>>
|varchar(max)
|NULL
|

|
|<<column-componentunderlinevariablename>>
|varchar(max)
|NULL
|

|
|<<column-controlflowdetailsrowid>>
|int
|NOT NULL
|

|
|<<column-packagename>>
|varchar(200)
|NOT NULL
|

|
|<<column-taskpath>>
|varchar(8000)
|NOT NULL
|

|
|<<column-componentunderlineconnectionmanagername>>

.Definition
[source,sql]
----
(case when left([Component_connectionManagerRefId],(26))='Project.ConnectionManagers' OR left([Component_connectionManagerRefId],(26))='Package.ConnectionManagers' then substring([Component_connectionManagerRefId],(28),len([Component_connectionManagerRefId])-(28))  end)
----


|varchar(max)
|NULL
|

|
|<<column-packagebasename>>

.Definition (PERSISTED)
[source,sql]
----
(replace([PackageName],'.dtsx',''))
----


|varchar(8000)
|NULL
|

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

// end::AntoraIndexList[]

== AntoraMeasureDetails

// tag::AntoraMeasureDetails[]

// end::AntoraMeasureDetails[]

== AntoraMeasureDescriptions



== AntoraParameterList

// tag::AntoraParameterList[]

// end::AntoraParameterList[]

== AntoraXrefCulturesList

// tag::AntoraXrefCulturesList[]
* xref:dhw:sqldb:ssis.packagetask_dft_component.adoc[] - 
// end::AntoraXrefCulturesList[]

== cultures_count

// tag::cultures_count[]
1
// end::cultures_count[]

== Other tags

source: property.RepoObjectProperty_cross As rop_cross


=== additional_reference_csv

// tag::additional_reference_csv[]

// end::additional_reference_csv[]


=== AdocUspSteps

// tag::adocuspsteps[]

// end::adocuspsteps[]


=== AntoraReferencedList

// tag::antorareferencedlist[]
* xref:dhw:sqldb:ssis.packagetask_dft_component_tgt.adoc[]
// end::antorareferencedlist[]


=== AntoraReferencingList

// tag::antorareferencinglist[]
* xref:dhw:sqldb:docs.ssis_dfttaskcomponentlist.adoc[]
* xref:dhw:sqldb:docs.ssis_pumldfttask.adoc[]
* xref:dhw:sqldb:docs.ssis_pumlpartialdftcomponent.adoc[]
// end::antorareferencinglist[]


=== Description

// tag::description[]

// end::description[]


=== exampleUsage

// tag::exampleusage[]

// end::exampleusage[]


=== exampleUsage_2

// tag::exampleusage_2[]

// end::exampleusage_2[]


=== exampleUsage_3

// tag::exampleusage_3[]

// end::exampleusage_3[]


=== exampleUsage_4

// tag::exampleusage_4[]

// end::exampleusage_4[]


=== exampleUsage_5

// tag::exampleusage_5[]

// end::exampleusage_5[]


=== exampleWrong_Usage

// tag::examplewrong_usage[]

// end::examplewrong_usage[]


=== has_execution_plan_issue

// tag::has_execution_plan_issue[]

// end::has_execution_plan_issue[]


=== has_get_referenced_issue

// tag::has_get_referenced_issue[]

// end::has_get_referenced_issue[]


=== has_history

// tag::has_history[]

// end::has_history[]


=== has_history_columns

// tag::has_history_columns[]

// end::has_history_columns[]


=== InheritanceType

// tag::inheritancetype[]

// end::inheritancetype[]


=== is_persistence

// tag::is_persistence[]

// end::is_persistence[]


=== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]

// end::is_persistence_check_duplicate_per_pk[]


=== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]

// end::is_persistence_check_for_empty_source[]


=== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]

// end::is_persistence_delete_changed[]


=== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]

// end::is_persistence_delete_missing[]


=== is_persistence_insert

// tag::is_persistence_insert[]

// end::is_persistence_insert[]


=== is_persistence_truncate

// tag::is_persistence_truncate[]

// end::is_persistence_truncate[]


=== is_persistence_update_changed

// tag::is_persistence_update_changed[]

// end::is_persistence_update_changed[]


=== is_repo_managed

// tag::is_repo_managed[]
0
// end::is_repo_managed[]


=== is_ssas

// tag::is_ssas[]
0
// end::is_ssas[]


=== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


=== MS_Description

// tag::ms_description[]

// end::ms_description[]


=== persistence_source_RepoObject_fullname

// tag::persistence_source_repoobject_fullname[]

// end::persistence_source_repoobject_fullname[]


=== persistence_source_RepoObject_fullname2

// tag::persistence_source_repoobject_fullname2[]

// end::persistence_source_repoobject_fullname2[]


=== persistence_source_RepoObject_guid

// tag::persistence_source_repoobject_guid[]

// end::persistence_source_repoobject_guid[]


=== persistence_source_RepoObject_xref

// tag::persistence_source_repoobject_xref[]

// end::persistence_source_repoobject_xref[]


=== pk_index_guid

// tag::pk_index_guid[]

// end::pk_index_guid[]


=== pk_IndexPatternColumnDatatype

// tag::pk_indexpatterncolumndatatype[]

// end::pk_indexpatterncolumndatatype[]


=== pk_IndexPatternColumnName

// tag::pk_indexpatterncolumnname[]

// end::pk_indexpatterncolumnname[]


=== pk_IndexSemanticGroup

// tag::pk_indexsemanticgroup[]

// end::pk_indexsemanticgroup[]


=== ReferencedObjectList

// tag::referencedobjectlist[]
* [ssis].[PackageTask_Dft_Component_tgt]
// end::referencedobjectlist[]


=== usp_persistence_RepoObject_guid

// tag::usp_persistence_repoobject_guid[]

// end::usp_persistence_repoobject_guid[]


=== UspExamples

// tag::uspexamples[]

// end::uspexamples[]


=== uspgenerator_usp_id

// tag::uspgenerator_usp_id[]

// end::uspgenerator_usp_id[]


=== UspParameters

// tag::uspparameters[]

// end::uspparameters[]

== Boolean Attributes

source: property.RepoObjectProperty WHERE property_int = 1

// tag::boolean_attributes[]


// end::boolean_attributes[]

== PlantUML diagrams

=== PlantUML Entity

// tag::puml_entity[]
[plantuml, entity-{docname}, svg, subs=macros]
....
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component.adoc[]" as ssis.PackageTask_Dft_Component << U >> {
  - AntoraModule : (varchar(50))
  Component_AccessMode : (varchar(max))
  Component_AlwaysUseDefaultCodePage : (varchar(max))
  Component_CommandTimeout : (int)
  Component_componentClassID : (varchar(max))
  Component_Connection_description : (varchar(max))
  Component_Connection_name : (varchar(max))
  Component_Connection_refId : (varchar(max))
  Component_connectionManagerID : (varchar(max))
  Component_connectionManagerRefId : (varchar(max))
  Component_ContactInfo : (varchar(max))
  Component_DefaultCodePage : (int)
  Component_description : (varchar(max))
  Component_FastLoadKeepIdentity : (bit)
  Component_FastLoadKeepNulls : (bit)
  Component_FastLoadMaxInsertCommitSize : (int)
  Component_FastLoadOptions : (varchar(max))
  Component_IsSortedProperty : (varchar(10))
  - Component_name : (varchar(max))
  Component_OpenRowset : (varchar(max))
  Component_OpenRowsetVariable : (varchar(max))
  Component_ParameterMapping : (varchar(max))
  - Component_refId : (varchar(max))
  Component_SqlCommand : (varchar(max))
  Component_SqlCommandVariable : (varchar(max))
  Component_VariableName : (varchar(max))
  - ControlFlowDetailsRowID : (int)
  - PackageName : (varchar(200))
  - TaskPath : (varchar(8000))
  ~ Component_ConnectionManagerName : (varchar(max))
  # PackageBasename : (varchar(8000))
  --
}
....

// end::puml_entity[]

=== PlantUML Entity 1 1 FK

// tag::puml_entity_1_1_fk[]
[plantuml, entity_1_1_fk-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component.adoc[]" as ssis.PackageTask_Dft_Component << U >> {

}



footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_fk[]

=== PlantUML 1 1 ObjectRef

// tag::puml_entity_1_1_objectref[]
[plantuml, entity_1_1_objectref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:docs.ssis_dfttaskcomponentlist.adoc[]" as docs.ssis_DftTaskComponentList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_pumldfttask.adoc[]" as docs.ssis_PumlDftTask << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_pumlpartialdftcomponent.adoc[]" as docs.ssis_PumlPartialDftComponent << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component.adoc[]" as ssis.PackageTask_Dft_Component << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_tgt.adoc[]" as ssis.PackageTask_Dft_Component_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Component_refId** : (varchar(max))
  --
}

ssis.PackageTask_Dft_Component <.. docs.ssis_DftTaskComponentList
ssis.PackageTask_Dft_Component <.. docs.ssis_PumlDftTask
ssis.PackageTask_Dft_Component <.. docs.ssis_PumlPartialDftComponent
ssis.PackageTask_Dft_Component_tgt <.. ssis.PackageTask_Dft_Component

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_objectref[]

=== PlantUML 30 0 ObjectRef

// tag::puml_entity_30_0_objectref[]
[plantuml, entity_30_0_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis.antoramodule_tgt_filter.adoc[]" as ssis.AntoraModule_tgt_filter << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.package_src.adoc[]" as ssis.Package_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component.adoc[]" as ssis.PackageTask_Dft_Component << U >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_src.adoc[]" as ssis.PackageTask_Dft_Component_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Component_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_tgt.adoc[]" as ssis.PackageTask_Dft_Component_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Component_refId** : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.project.adoc[]" as ssis.Project << U >> {
  - **AntoraModule** : (varchar(50))
  --
}

entity "puml-link:dhw:sqldb:ssis_t.pkgstats.adoc[]" as ssis_t.pkgStats << U >> {
  - **RowID** : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tblcontrolflow.adoc[]" as ssis_t.TblControlFlow << U >> {
  - **ControlFlowDetailsRowID** : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_dft_component.adoc[]" as ssis_t.TblTask_Dft_Component << U >> {
  - **DftComponentId** : (int)
  --
}

ssis.AntoraModule_tgt_filter <.. ssis.PackageTask_Dft_Component_tgt
ssis.Package_src <.. ssis.AntoraModule_tgt_filter
ssis.Package_src <.. ssis.PackageTask_Dft_Component_src
ssis.PackageTask_Dft_Component_src <.. ssis.PackageTask_Dft_Component_tgt
ssis.PackageTask_Dft_Component_tgt <.. ssis.PackageTask_Dft_Component
ssis.Project <.. ssis.Package_src
ssis_t.pkgStats <.. ssis.Package_src
ssis_t.TblControlFlow <.. ssis.PackageTask_Dft_Component_src
ssis_t.TblTask_Dft_Component <.. ssis.PackageTask_Dft_Component_src

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_30_0_objectref[]

=== PlantUML 0 30 ObjectRef

// tag::puml_entity_0_30_objectref[]
[plantuml, entity_0_30_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:docs.ssis_adoc.adoc[]" as docs.ssis_Adoc << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageBasename** : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_adoc_t.adoc[]" as docs.ssis_Adoc_T << U >> {
  - **AntoraModule** : (varchar(50))
  - **PackageBasename** : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_dfttaskcomponentlist.adoc[]" as docs.ssis_DftTaskComponentList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_pumldfttask.adoc[]" as docs.ssis_PumlDftTask << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_pumlpartialdftcomponent.adoc[]" as docs.ssis_PumlPartialDftComponent << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_task.adoc[]" as docs.ssis_Task << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_tasklist.adoc[]" as docs.ssis_TaskList << V >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport.adoc[]" as docs.usp_AntoraExport << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_ssispartialscontent.adoc[]" as docs.usp_AntoraExport_SsisPartialsContent << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_ssis_adoc_t.adoc[]" as docs.usp_PERSIST_ssis_Adoc_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component.adoc[]" as ssis.PackageTask_Dft_Component << U >> {
  --
}

docs.ssis_Adoc <.. docs.ssis_Adoc_T
docs.ssis_Adoc <.. docs.usp_PERSIST_ssis_Adoc_T
docs.ssis_Adoc_T <.. docs.usp_AntoraExport_SsisPartialsContent
docs.ssis_Adoc_T <.. docs.usp_PERSIST_ssis_Adoc_T
docs.ssis_DftTaskComponentList <.. docs.ssis_Task
docs.ssis_DftTaskComponentList <.. docs.ssis_TaskList
docs.ssis_PumlDftTask <.. docs.ssis_Task
docs.ssis_PumlDftTask <.. docs.ssis_TaskList
docs.ssis_PumlPartialDftComponent <.. docs.ssis_DftTaskComponentList
docs.ssis_PumlPartialDftComponent <.. docs.ssis_PumlDftTask
docs.ssis_TaskList <.. docs.ssis_Adoc
docs.usp_AntoraExport_SsisPartialsContent <.. docs.usp_AntoraExport
docs.usp_PERSIST_ssis_Adoc_T <.. docs.usp_AntoraExport_SsisPartialsContent
ssis.PackageTask_Dft_Component <.. docs.ssis_DftTaskComponentList
ssis.PackageTask_Dft_Component <.. docs.ssis_PumlDftTask
ssis.PackageTask_Dft_Component <.. docs.ssis_PumlPartialDftComponent

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_0_30_objectref[]

=== PlantUML 1 1 ColumnRef

// tag::puml_entity_1_1_colref[]
[plantuml, entity_1_1_colref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:docs.ssis_dfttaskcomponentlist.adoc[]" as docs.ssis_DftTaskComponentList << V >> {
  - AntoraModule : (varchar(50))
  DftTaskComponentList : (nvarchar(max))
  - PackageName : (varchar(200))
  - TaskPath : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_pumldfttask.adoc[]" as docs.ssis_PumlDftTask << V >> {
  - AntoraModule : (varchar(50))
  - PackageName : (varchar(200))
  - PumlDftTask : (nvarchar(max))
  - TaskPath : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_pumlpartialdftcomponent.adoc[]" as docs.ssis_PumlPartialDftComponent << V >> {
  - AntoraModule : (varchar(50))
  - Component_name : (varchar(max))
  - Component_refId : (varchar(max))
  - PackageName : (varchar(200))
  PumlPartialDftComponent : (nvarchar(max))
  - TaskPath : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component.adoc[]" as ssis.PackageTask_Dft_Component << U >> {
  - AntoraModule : (varchar(50))
  Component_AccessMode : (varchar(max))
  Component_AlwaysUseDefaultCodePage : (varchar(max))
  Component_CommandTimeout : (int)
  Component_componentClassID : (varchar(max))
  Component_Connection_description : (varchar(max))
  Component_Connection_name : (varchar(max))
  Component_Connection_refId : (varchar(max))
  Component_connectionManagerID : (varchar(max))
  Component_connectionManagerRefId : (varchar(max))
  Component_ContactInfo : (varchar(max))
  Component_DefaultCodePage : (int)
  Component_description : (varchar(max))
  Component_FastLoadKeepIdentity : (bit)
  Component_FastLoadKeepNulls : (bit)
  Component_FastLoadMaxInsertCommitSize : (int)
  Component_FastLoadOptions : (varchar(max))
  Component_IsSortedProperty : (varchar(10))
  - Component_name : (varchar(max))
  Component_OpenRowset : (varchar(max))
  Component_OpenRowsetVariable : (varchar(max))
  Component_ParameterMapping : (varchar(max))
  - Component_refId : (varchar(max))
  Component_SqlCommand : (varchar(max))
  Component_SqlCommandVariable : (varchar(max))
  Component_VariableName : (varchar(max))
  - ControlFlowDetailsRowID : (int)
  - PackageName : (varchar(200))
  - TaskPath : (varchar(8000))
  ~ Component_ConnectionManagerName : (varchar(max))
  # PackageBasename : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_tgt.adoc[]" as ssis.PackageTask_Dft_Component_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Component_refId** : (varchar(max))
  Component_AccessMode : (varchar(max))
  Component_AlwaysUseDefaultCodePage : (varchar(max))
  Component_CommandTimeout : (int)
  Component_componentClassID : (varchar(max))
  Component_Connection_description : (varchar(max))
  Component_Connection_name : (varchar(max))
  Component_Connection_refId : (varchar(max))
  Component_connectionManagerID : (varchar(max))
  Component_connectionManagerRefId : (varchar(max))
  Component_ContactInfo : (varchar(max))
  Component_DefaultCodePage : (int)
  Component_description : (varchar(max))
  Component_FastLoadKeepIdentity : (bit)
  Component_FastLoadKeepNulls : (bit)
  Component_FastLoadMaxInsertCommitSize : (int)
  Component_FastLoadOptions : (varchar(max))
  Component_IsSortedProperty : (varchar(10))
  Component_name : (varchar(max))
  Component_OpenRowset : (varchar(max))
  Component_OpenRowsetVariable : (varchar(max))
  Component_ParameterMapping : (varchar(max))
  Component_SqlCommand : (varchar(max))
  Component_SqlCommandVariable : (varchar(max))
  Component_VariableName : (varchar(max))
  - ControlFlowDetailsRowID : (int)
  TaskPath : (varchar(8000))
  --
}

ssis.PackageTask_Dft_Component <.. docs.ssis_DftTaskComponentList
ssis.PackageTask_Dft_Component <.. docs.ssis_PumlDftTask
ssis.PackageTask_Dft_Component <.. docs.ssis_PumlPartialDftComponent
ssis.PackageTask_Dft_Component_tgt <.. ssis.PackageTask_Dft_Component
"ssis.PackageTask_Dft_Component::AntoraModule" <-- "docs.ssis_DftTaskComponentList::AntoraModule"
"ssis.PackageTask_Dft_Component::AntoraModule" <-- "docs.ssis_PumlDftTask::AntoraModule"
"ssis.PackageTask_Dft_Component::AntoraModule" <-- "docs.ssis_PumlPartialDftComponent::AntoraModule"
"ssis.PackageTask_Dft_Component::AntoraModule" <-- "ssis.PackageTask_Dft_Component_tgt::AntoraModule"
"ssis.PackageTask_Dft_Component::Component_AccessMode" <-- "ssis.PackageTask_Dft_Component_tgt::Component_AccessMode"
"ssis.PackageTask_Dft_Component::Component_AlwaysUseDefaultCodePage" <-- "ssis.PackageTask_Dft_Component_tgt::Component_AlwaysUseDefaultCodePage"
"ssis.PackageTask_Dft_Component::Component_CommandTimeout" <-- "ssis.PackageTask_Dft_Component_tgt::Component_CommandTimeout"
"ssis.PackageTask_Dft_Component::Component_componentClassID" <-- "ssis.PackageTask_Dft_Component_tgt::Component_componentClassID"
"ssis.PackageTask_Dft_Component::Component_Connection_description" <-- "ssis.PackageTask_Dft_Component_tgt::Component_Connection_description"
"ssis.PackageTask_Dft_Component::Component_Connection_name" <-- "ssis.PackageTask_Dft_Component_tgt::Component_Connection_name"
"ssis.PackageTask_Dft_Component::Component_Connection_refId" <-- "ssis.PackageTask_Dft_Component_tgt::Component_Connection_refId"
"ssis.PackageTask_Dft_Component::Component_connectionManagerID" <-- "ssis.PackageTask_Dft_Component_tgt::Component_connectionManagerID"
"ssis.PackageTask_Dft_Component::Component_connectionManagerRefId" <-- "ssis.PackageTask_Dft_Component::Component_ConnectionManagerName"
"ssis.PackageTask_Dft_Component::Component_connectionManagerRefId" <-- "ssis.PackageTask_Dft_Component_tgt::Component_connectionManagerRefId"
"ssis.PackageTask_Dft_Component::Component_ContactInfo" <-- "ssis.PackageTask_Dft_Component_tgt::Component_ContactInfo"
"ssis.PackageTask_Dft_Component::Component_DefaultCodePage" <-- "ssis.PackageTask_Dft_Component_tgt::Component_DefaultCodePage"
"ssis.PackageTask_Dft_Component::Component_description" <-- "ssis.PackageTask_Dft_Component_tgt::Component_description"
"ssis.PackageTask_Dft_Component::Component_FastLoadKeepIdentity" <-- "ssis.PackageTask_Dft_Component_tgt::Component_FastLoadKeepIdentity"
"ssis.PackageTask_Dft_Component::Component_FastLoadKeepNulls" <-- "ssis.PackageTask_Dft_Component_tgt::Component_FastLoadKeepNulls"
"ssis.PackageTask_Dft_Component::Component_FastLoadMaxInsertCommitSize" <-- "ssis.PackageTask_Dft_Component_tgt::Component_FastLoadMaxInsertCommitSize"
"ssis.PackageTask_Dft_Component::Component_FastLoadOptions" <-- "ssis.PackageTask_Dft_Component_tgt::Component_FastLoadOptions"
"ssis.PackageTask_Dft_Component::Component_IsSortedProperty" <-- "ssis.PackageTask_Dft_Component_tgt::Component_IsSortedProperty"
"ssis.PackageTask_Dft_Component::Component_name" <-- "docs.ssis_PumlPartialDftComponent::Component_name"
"ssis.PackageTask_Dft_Component::Component_name" <-- "ssis.PackageTask_Dft_Component_tgt::Component_name"
"ssis.PackageTask_Dft_Component::Component_OpenRowset" <-- "ssis.PackageTask_Dft_Component_tgt::Component_OpenRowset"
"ssis.PackageTask_Dft_Component::Component_OpenRowsetVariable" <-- "ssis.PackageTask_Dft_Component_tgt::Component_OpenRowsetVariable"
"ssis.PackageTask_Dft_Component::Component_ParameterMapping" <-- "ssis.PackageTask_Dft_Component_tgt::Component_ParameterMapping"
"ssis.PackageTask_Dft_Component::Component_refId" <-- "docs.ssis_PumlPartialDftComponent::Component_refId"
"ssis.PackageTask_Dft_Component::Component_refId" <-- "ssis.PackageTask_Dft_Component_tgt::Component_refId"
"ssis.PackageTask_Dft_Component::Component_SqlCommand" <-- "ssis.PackageTask_Dft_Component_tgt::Component_SqlCommand"
"ssis.PackageTask_Dft_Component::Component_SqlCommandVariable" <-- "ssis.PackageTask_Dft_Component_tgt::Component_SqlCommandVariable"
"ssis.PackageTask_Dft_Component::Component_VariableName" <-- "ssis.PackageTask_Dft_Component_tgt::Component_VariableName"
"ssis.PackageTask_Dft_Component::ControlFlowDetailsRowID" <-- "ssis.PackageTask_Dft_Component_tgt::ControlFlowDetailsRowID"
"ssis.PackageTask_Dft_Component::PackageName" <-- "docs.ssis_DftTaskComponentList::PackageName"
"ssis.PackageTask_Dft_Component::PackageName" <-- "docs.ssis_PumlDftTask::PackageName"
"ssis.PackageTask_Dft_Component::PackageName" <-- "docs.ssis_PumlPartialDftComponent::PackageName"
"ssis.PackageTask_Dft_Component::PackageName" <-- "ssis.PackageTask_Dft_Component::PackageBasename"
"ssis.PackageTask_Dft_Component::PackageName" <-- "ssis.PackageTask_Dft_Component_tgt::PackageName"
"ssis.PackageTask_Dft_Component::TaskPath" <-- "docs.ssis_DftTaskComponentList::TaskPath"
"ssis.PackageTask_Dft_Component::TaskPath" <-- "docs.ssis_PumlDftTask::TaskPath"
"ssis.PackageTask_Dft_Component::TaskPath" <-- "docs.ssis_PumlPartialDftComponent::TaskPath"
"ssis.PackageTask_Dft_Component::TaskPath" <-- "ssis.PackageTask_Dft_Component_tgt::TaskPath"

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_colref[]


== sql_modules_definition

// tag::sql_modules_definition[]
[%collapsible]
=======
[source,sql,numbered,indent=0]
----

----
=======
// end::sql_modules_definition[]


