// tag::HeaderFullDisplayName[]
= ssis_t.TblTask_Dft_Component_src - V
// end::HeaderFullDisplayName[]

== existing_properties

// tag::existing_properties[]

:ExistsProperty--antorareferencedlist:
:ExistsProperty--antorareferencinglist:
:ExistsProperty--is_repo_managed:
:ExistsProperty--is_ssas:
:ExistsProperty--referencedobjectlist:
:ExistsProperty--sql_modules_definition:
:ExistsProperty--FK:
:ExistsProperty--AntoraIndexList:
:ExistsProperty--Columns:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
AFDCAD7F-F73E-EC11-852D-A81E8446D5B0
// end::RepoObject_guid[]

== RepoObject_FullDisplayName2

// tag::RepoObject_FullDisplayName2[]
ssis_t.TblTask_Dft_Component_src
// end::RepoObject_FullDisplayName2[]

== SysObject_type

// tag::SysObject_type[]
V 
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
view
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
78675378
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2021-11-05 16:28:43
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]
[discrete]
== _


[#column-accessmode]
=== AccessMode

[cols="d,8a,m,m,m"]
|===
|
|AccessMode
|varchar(max)
|NULL
|
|===


[#column-alwaysusedefaultcodepage]
=== AlwaysUseDefaultCodePage

[cols="d,8a,m,m,m"]
|===
|
|AlwaysUseDefaultCodePage
|varchar(max)
|NULL
|
|===


[#column-commandtimeout]
=== CommandTimeout

[cols="d,8a,m,m,m"]
|===
|
|CommandTimeout
|int
|NULL
|
|===


[#column-componentclassid]
=== componentClassID

[cols="d,8a,m,m,m"]
|===
|
|componentClassID
|varchar(max)
|NULL
|
|===


[#column-connectionunderlinedescription]
=== Connection_description

[cols="d,8a,m,m,m"]
|===
|
|Connection_description
|varchar(max)
|NULL
|
|===


[#column-connectionunderlinename]
=== Connection_name

[cols="d,8a,m,m,m"]
|===
|
|Connection_name
|varchar(max)
|NULL
|
|===


[#column-connectionunderlinerefid]
=== Connection_refId

[cols="d,8a,m,m,m"]
|===
|
|Connection_refId
|varchar(max)
|NULL
|
|===


[#column-connectionmanagerid]
=== connectionManagerID

[cols="d,8a,m,m,m"]
|===
|
|connectionManagerID
|varchar(max)
|NULL
|
|===


[#column-connectionmanagerrefid]
=== connectionManagerRefId

[cols="d,8a,m,m,m"]
|===
|
|connectionManagerRefId
|varchar(max)
|NULL
|
|===


[#column-contactinfo]
=== ContactInfo

[cols="d,8a,m,m,m"]
|===
|
|ContactInfo
|varchar(max)
|NULL
|
|===


[#column-controlflowdetailsrowid]
=== ControlFlowDetailsRowID

[cols="d,8a,m,m,m"]
|===
|
|ControlFlowDetailsRowID
|int
|NOT NULL
|
|===

.Referenced Columns
--
* xref:ssis_t.tblcontrolflow.adoc#column-controlflowdetailsrowid[+ssis_t.TblControlFlow.ControlFlowDetailsRowID+]
--


[#column-defaultcodepage]
=== DefaultCodePage

[cols="d,8a,m,m,m"]
|===
|
|DefaultCodePage
|int
|NULL
|
|===


[#column-description]
=== description

[cols="d,8a,m,m,m"]
|===
|
|description
|varchar(max)
|NULL
|
|===


[#column-fastloadkeepidentity]
=== FastLoadKeepIdentity

[cols="d,8a,m,m,m"]
|===
|
|FastLoadKeepIdentity
|bit
|NULL
|
|===


[#column-fastloadkeepnulls]
=== FastLoadKeepNulls

[cols="d,8a,m,m,m"]
|===
|
|FastLoadKeepNulls
|bit
|NULL
|
|===


[#column-fastloadmaxinsertcommitsize]
=== FastLoadMaxInsertCommitSize

[cols="d,8a,m,m,m"]
|===
|
|FastLoadMaxInsertCommitSize
|int
|NULL
|
|===


[#column-fastloadoptions]
=== FastLoadOptions

[cols="d,8a,m,m,m"]
|===
|
|FastLoadOptions
|varchar(max)
|NULL
|
|===


[#column-inputsqry]
=== inputsQry

[cols="d,8a,m,m,m"]
|===
|
|inputsQry
|xml
|NULL
|
|===


[#column-issortedproperty]
=== IsSortedProperty

[cols="d,8a,m,m,m"]
|===
|
|IsSortedProperty
|varchar(10)
|NULL
|
|===


[#column-name]
=== name

[cols="d,8a,m,m,m"]
|===
|
|name
|varchar(max)
|NULL
|
|===


[#column-openrowset]
=== OpenRowset

[cols="d,8a,m,m,m"]
|===
|
|OpenRowset
|varchar(max)
|NULL
|
|===


[#column-openrowsetvariable]
=== OpenRowsetVariable

[cols="d,8a,m,m,m"]
|===
|
|OpenRowsetVariable
|varchar(max)
|NULL
|
|===


[#column-outputsqry]
=== outputsQry

[cols="d,8a,m,m,m"]
|===
|
|outputsQry
|xml
|NULL
|
|===


[#column-parametermapping]
=== ParameterMapping

[cols="d,8a,m,m,m"]
|===
|
|ParameterMapping
|varchar(max)
|NULL
|
|===


[#column-refid]
=== refId

[cols="d,8a,m,m,m"]
|===
|
|refId
|varchar(max)
|NULL
|
|===


[#column-rowid]
=== RowID

[cols="d,8a,m,m,m"]
|===
|
|RowID
|int
|NULL
|
|===

.Referenced Columns
--
* xref:ssis_t.tblcontrolflow.adoc#column-rowid[+ssis_t.TblControlFlow.RowID+]
--


[#column-sqlcommand]
=== SqlCommand

[cols="d,8a,m,m,m"]
|===
|
|SqlCommand
|varchar(max)
|NULL
|
|===


[#column-sqlcommandvariable]
=== SqlCommandVariable

[cols="d,8a,m,m,m"]
|===
|
|SqlCommandVariable
|varchar(max)
|NULL
|
|===


[#column-variablename]
=== VariableName

[cols="d,8a,m,m,m"]
|===
|
|VariableName
|varchar(max)
|NULL
|
|===


// end::AntoraColumnDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]





























// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]
|
|<<column-accessmode>>
|varchar(max)
|NULL
|

|
|<<column-alwaysusedefaultcodepage>>
|varchar(max)
|NULL
|

|
|<<column-commandtimeout>>
|int
|NULL
|

|
|<<column-componentclassid>>
|varchar(max)
|NULL
|

|
|<<column-connectionunderlinedescription>>
|varchar(max)
|NULL
|

|
|<<column-connectionunderlinename>>
|varchar(max)
|NULL
|

|
|<<column-connectionunderlinerefid>>
|varchar(max)
|NULL
|

|
|<<column-connectionmanagerid>>
|varchar(max)
|NULL
|

|
|<<column-connectionmanagerrefid>>
|varchar(max)
|NULL
|

|
|<<column-contactinfo>>
|varchar(max)
|NULL
|

|
|<<column-controlflowdetailsrowid>>
|int
|NOT NULL
|

|
|<<column-defaultcodepage>>
|int
|NULL
|

|
|<<column-description>>
|varchar(max)
|NULL
|

|
|<<column-fastloadkeepidentity>>
|bit
|NULL
|

|
|<<column-fastloadkeepnulls>>
|bit
|NULL
|

|
|<<column-fastloadmaxinsertcommitsize>>
|int
|NULL
|

|
|<<column-fastloadoptions>>
|varchar(max)
|NULL
|

|
|<<column-inputsqry>>
|xml
|NULL
|

|
|<<column-issortedproperty>>
|varchar(10)
|NULL
|

|
|<<column-name>>
|varchar(max)
|NULL
|

|
|<<column-openrowset>>
|varchar(max)
|NULL
|

|
|<<column-openrowsetvariable>>
|varchar(max)
|NULL
|

|
|<<column-outputsqry>>
|xml
|NULL
|

|
|<<column-parametermapping>>
|varchar(max)
|NULL
|

|
|<<column-refid>>
|varchar(max)
|NULL
|

|
|<<column-rowid>>
|int
|NULL
|

|
|<<column-sqlcommand>>
|varchar(max)
|NULL
|

|
|<<column-sqlcommandvariable>>
|varchar(max)
|NULL
|

|
|<<column-variablename>>
|varchar(max)
|NULL
|

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

[#index-idxunderlinetbltaskunderlinedftunderlinecomponentunderlinesrcunderlineunderline1]
=== idx_TblTask_Dft_Component_src++__++1

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-ControlFlowDetailsRowID>>; int
--
* PK, Unique, Real: 0, 0, 0

// end::AntoraIndexList[]

== AntoraMeasureDetails

// tag::AntoraMeasureDetails[]

// end::AntoraMeasureDetails[]

== AntoraMeasureDescriptions



== AntoraParameterList

// tag::AntoraParameterList[]

// end::AntoraParameterList[]

== AntoraXrefCulturesList

// tag::AntoraXrefCulturesList[]
* xref:dhw:sqldb:ssis_t.tbltask_dft_component_src.adoc[] - 
// end::AntoraXrefCulturesList[]

== cultures_count

// tag::cultures_count[]
1
// end::cultures_count[]

== Other tags

source: property.RepoObjectProperty_cross As rop_cross


=== additional_reference_csv

// tag::additional_reference_csv[]

// end::additional_reference_csv[]


=== AdocUspSteps

// tag::adocuspsteps[]

// end::adocuspsteps[]


=== AntoraReferencedList

// tag::antorareferencedlist[]
* xref:dhw:sqldb:ssis_t.tblcontrolflow.adoc[]
// end::antorareferencedlist[]


=== AntoraReferencingList

// tag::antorareferencinglist[]
* xref:dhw:sqldb:ssis_t.usp_getpackagedetails.adoc[]
// end::antorareferencinglist[]


=== Description

// tag::description[]

// end::description[]


=== exampleUsage

// tag::exampleusage[]

// end::exampleusage[]


=== exampleUsage_2

// tag::exampleusage_2[]

// end::exampleusage_2[]


=== exampleUsage_3

// tag::exampleusage_3[]

// end::exampleusage_3[]


=== exampleUsage_4

// tag::exampleusage_4[]

// end::exampleusage_4[]


=== exampleUsage_5

// tag::exampleusage_5[]

// end::exampleusage_5[]


=== exampleWrong_Usage

// tag::examplewrong_usage[]

// end::examplewrong_usage[]


=== has_execution_plan_issue

// tag::has_execution_plan_issue[]

// end::has_execution_plan_issue[]


=== has_get_referenced_issue

// tag::has_get_referenced_issue[]

// end::has_get_referenced_issue[]


=== has_history

// tag::has_history[]

// end::has_history[]


=== has_history_columns

// tag::has_history_columns[]

// end::has_history_columns[]


=== InheritanceType

// tag::inheritancetype[]

// end::inheritancetype[]


=== is_persistence

// tag::is_persistence[]

// end::is_persistence[]


=== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]

// end::is_persistence_check_duplicate_per_pk[]


=== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]

// end::is_persistence_check_for_empty_source[]


=== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]

// end::is_persistence_delete_changed[]


=== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]

// end::is_persistence_delete_missing[]


=== is_persistence_insert

// tag::is_persistence_insert[]

// end::is_persistence_insert[]


=== is_persistence_truncate

// tag::is_persistence_truncate[]

// end::is_persistence_truncate[]


=== is_persistence_update_changed

// tag::is_persistence_update_changed[]

// end::is_persistence_update_changed[]


=== is_repo_managed

// tag::is_repo_managed[]
0
// end::is_repo_managed[]


=== is_ssas

// tag::is_ssas[]
0
// end::is_ssas[]


=== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


=== MS_Description

// tag::ms_description[]

// end::ms_description[]


=== persistence_source_RepoObject_fullname

// tag::persistence_source_repoobject_fullname[]

// end::persistence_source_repoobject_fullname[]


=== persistence_source_RepoObject_fullname2

// tag::persistence_source_repoobject_fullname2[]

// end::persistence_source_repoobject_fullname2[]


=== persistence_source_RepoObject_guid

// tag::persistence_source_repoobject_guid[]

// end::persistence_source_repoobject_guid[]


=== persistence_source_RepoObject_xref

// tag::persistence_source_repoobject_xref[]

// end::persistence_source_repoobject_xref[]


=== pk_index_guid

// tag::pk_index_guid[]

// end::pk_index_guid[]


=== pk_IndexPatternColumnDatatype

// tag::pk_indexpatterncolumndatatype[]

// end::pk_indexpatterncolumndatatype[]


=== pk_IndexPatternColumnName

// tag::pk_indexpatterncolumnname[]

// end::pk_indexpatterncolumnname[]


=== pk_IndexSemanticGroup

// tag::pk_indexsemanticgroup[]

// end::pk_indexsemanticgroup[]


=== ReferencedObjectList

// tag::referencedobjectlist[]
* [ssis_t].[TblControlFlow]
// end::referencedobjectlist[]


=== usp_persistence_RepoObject_guid

// tag::usp_persistence_repoobject_guid[]

// end::usp_persistence_repoobject_guid[]


=== UspExamples

// tag::uspexamples[]

// end::uspexamples[]


=== uspgenerator_usp_id

// tag::uspgenerator_usp_id[]

// end::uspgenerator_usp_id[]


=== UspParameters

// tag::uspparameters[]

// end::uspparameters[]

== Boolean Attributes

source: property.RepoObjectProperty WHERE property_int = 1

// tag::boolean_attributes[]


// end::boolean_attributes[]

== PlantUML diagrams

=== PlantUML Entity

// tag::puml_entity[]
[plantuml, entity-{docname}, svg, subs=macros]
....
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis_t.tbltask_dft_component_src.adoc[]" as ssis_t.TblTask_Dft_Component_src << V >> {
  AccessMode : (varchar(max))
  AlwaysUseDefaultCodePage : (varchar(max))
  CommandTimeout : (int)
  componentClassID : (varchar(max))
  Connection_description : (varchar(max))
  Connection_name : (varchar(max))
  Connection_refId : (varchar(max))
  connectionManagerID : (varchar(max))
  connectionManagerRefId : (varchar(max))
  ContactInfo : (varchar(max))
  - ControlFlowDetailsRowID : (int)
  DefaultCodePage : (int)
  description : (varchar(max))
  FastLoadKeepIdentity : (bit)
  FastLoadKeepNulls : (bit)
  FastLoadMaxInsertCommitSize : (int)
  FastLoadOptions : (varchar(max))
  inputsQry : (xml)
  IsSortedProperty : (varchar(10))
  name : (varchar(max))
  OpenRowset : (varchar(max))
  OpenRowsetVariable : (varchar(max))
  outputsQry : (xml)
  ParameterMapping : (varchar(max))
  refId : (varchar(max))
  RowID : (int)
  SqlCommand : (varchar(max))
  SqlCommandVariable : (varchar(max))
  VariableName : (varchar(max))
  --
}
....

// end::puml_entity[]

=== PlantUML Entity 1 1 FK

// tag::puml_entity_1_1_fk[]
[plantuml, entity_1_1_fk-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis_t.tbltask_dft_component_src.adoc[]" as ssis_t.TblTask_Dft_Component_src << V >> {
- idx_TblTask_Dft_Component_src__1

..
ControlFlowDetailsRowID; int
}



footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_fk[]

=== PlantUML 1 1 ObjectRef

// tag::puml_entity_1_1_objectref[]
[plantuml, entity_1_1_objectref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis_t.tblcontrolflow.adoc[]" as ssis_t.TblControlFlow << U >> {
  - **ControlFlowDetailsRowID** : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_dft_component_src.adoc[]" as ssis_t.TblTask_Dft_Component_src << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.usp_getpackagedetails.adoc[]" as ssis_t.usp_GetPackageDetails << P >> {
  --
}

ssis_t.TblControlFlow <.. ssis_t.TblTask_Dft_Component_src
ssis_t.TblTask_Dft_Component_src <.. ssis_t.usp_GetPackageDetails

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_objectref[]

=== PlantUML 30 0 ObjectRef

// tag::puml_entity_30_0_objectref[]
[plantuml, entity_30_0_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis_t.tblcontrolflow.adoc[]" as ssis_t.TblControlFlow << U >> {
  - **ControlFlowDetailsRowID** : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_dft_component_src.adoc[]" as ssis_t.TblTask_Dft_Component_src << V >> {
  --
}

ssis_t.TblControlFlow <.. ssis_t.TblTask_Dft_Component_src

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_30_0_objectref[]

=== PlantUML 0 30 ObjectRef

// tag::puml_entity_0_30_objectref[]
[plantuml, entity_0_30_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis_t.tbltask_dft_component_src.adoc[]" as ssis_t.TblTask_Dft_Component_src << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.usp_getpackagedetails.adoc[]" as ssis_t.usp_GetPackageDetails << P >> {
  --
}

ssis_t.TblTask_Dft_Component_src <.. ssis_t.usp_GetPackageDetails

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_0_30_objectref[]

=== PlantUML 1 1 ColumnRef

// tag::puml_entity_1_1_colref[]
[plantuml, entity_1_1_colref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis_t.tblcontrolflow.adoc[]" as ssis_t.TblControlFlow << U >> {
  - **ControlFlowDetailsRowID** : (int)
  DelayValidationPropertyValue : (varchar(100))
  DFTQuery : (xml)
  ExecPkgTaskQry : (xml)
  ExpressionValue : (varchar(5000))
  IsDisabled : (varchar(10))
  RowID : (int)
  ScriptTaskQry : (xml)
  SqlTaskQry : (xml)
  TaskDescription : (varchar(max))
  TaskName : (varchar(2000))
  TaskPath : (varchar(8000))
  TaskType : (varchar(5000))
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_dft_component_src.adoc[]" as ssis_t.TblTask_Dft_Component_src << V >> {
  AccessMode : (varchar(max))
  AlwaysUseDefaultCodePage : (varchar(max))
  CommandTimeout : (int)
  componentClassID : (varchar(max))
  Connection_description : (varchar(max))
  Connection_name : (varchar(max))
  Connection_refId : (varchar(max))
  connectionManagerID : (varchar(max))
  connectionManagerRefId : (varchar(max))
  ContactInfo : (varchar(max))
  - ControlFlowDetailsRowID : (int)
  DefaultCodePage : (int)
  description : (varchar(max))
  FastLoadKeepIdentity : (bit)
  FastLoadKeepNulls : (bit)
  FastLoadMaxInsertCommitSize : (int)
  FastLoadOptions : (varchar(max))
  inputsQry : (xml)
  IsSortedProperty : (varchar(10))
  name : (varchar(max))
  OpenRowset : (varchar(max))
  OpenRowsetVariable : (varchar(max))
  outputsQry : (xml)
  ParameterMapping : (varchar(max))
  refId : (varchar(max))
  RowID : (int)
  SqlCommand : (varchar(max))
  SqlCommandVariable : (varchar(max))
  VariableName : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis_t.usp_getpackagedetails.adoc[]" as ssis_t.usp_GetPackageDetails << P >> {
  --
}

ssis_t.TblControlFlow <.. ssis_t.TblTask_Dft_Component_src
ssis_t.TblTask_Dft_Component_src <.. ssis_t.usp_GetPackageDetails
"ssis_t.TblControlFlow::ControlFlowDetailsRowID" <-- "ssis_t.TblTask_Dft_Component_src::ControlFlowDetailsRowID"
"ssis_t.TblControlFlow::RowID" <-- "ssis_t.TblTask_Dft_Component_src::RowID"

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_colref[]


== sql_modules_definition

// tag::sql_modules_definition[]
[%collapsible]
=======
[source,sql,numbered,indent=0]
----
Create   View ssis_t.TblTask_Dft_Component_src
As
Select
    pkglvl.ControlFlowDetailsRowID
  , pkglvl.RowID
  , refId                       = dftnodes.x.value ( '@refId[1]', 'varchar(max)' )
  , name                        = dftnodes.x.value ( '@name[1]', 'varchar(max)' )
  , componentClassID            = dftnodes.x.value ( '@componentClassID[1]', 'varchar(max)' )
  , description                 = dftnodes.x.value ( '@description[1]', 'varchar(max)' )
  , ContactInfo                 = dftnodes.x.value ( '@contactInfo[1]', 'varchar(max)' )
  --properties
  , CommandTimeout              = dftnodes.x.value ( 'data(./properties/property[@name=''CommandTimeout'']	)[1]' , 'int' )
  , [OpenRowset]                = dftnodes.x.value ( 'data(./properties/property[@name=''OpenRowset'']	)[1]', 'varchar(max)' )
  , OpenRowsetVariable          = dftnodes.x.value (
                                                       'data(./properties/property[@name=''OpenRowsetVariable'']	)[1]'
                                                     , 'varchar(max)'
                                                   )
  , SqlCommand                  = dftnodes.x.value ( 'data(./properties/property[@name=''SqlCommand'']	)[1]' , 'varchar(max)' )
  , SqlCommandVariable          = dftnodes.x.value (
                                                       'data(./properties/property[@name=''SqlCommandVariable'']	)[1]'
                                                     , 'varchar(max)'
                                                   )
  , DefaultCodePage             = dftnodes.x.value ( 'data(./properties/property[@name=''DefaultCodePage'']	)[1]', 'int' )
  , AlwaysUseDefaultCodePage    = dftnodes.x.value (
                                                       'data(./properties/property[@name=''AlwaysUseDefaultCodePage'']	)[1]'
                                                     , 'varchar(max)'
                                                   )
  , AccessMode                  = dftnodes.x.value ( 'data(./properties/property[@name=''AccessMode'']	)[1]' , 'varchar(max)' )
  , ParameterMapping            = dftnodes.x.value (
                                                       'data(./properties/property[@name=''ParameterMapping'']	)[1]'
                                                     , 'varchar(max)'
                                                   )
  , FastLoadKeepIdentity        = dftnodes.x.value (
                                                       'data(./properties/property[@name=''FastLoadKeepIdentity'']	)[1]'
                                                     , 'bit'
                                                   )
  , FastLoadKeepNulls           = dftnodes.x.value ( 'data(./properties/property[@name=''FastLoadKeepNulls'']	)[1]', 'bit' )
  , FastLoadOptions             = dftnodes.x.value ( 'data(./properties/property[@name=''FastLoadOptions'']	)[1]', 'varchar(max)' )
  , FastLoadMaxInsertCommitSize = dftnodes.x.value (
                                                       'data(./properties/property[@name=''FastLoadMaxInsertCommitSize'']	)[1]'
                                                     , 'int'
                                                   )
  , VariableName                = dftnodes.x.value ( 'data(./properties/property[@name=''VariableName'']	)[1]', 'varchar(max)' )
  , Connection_refId            = dftnodes.x.value ( 'data(./connections/connection/@refId)[1]', 'varchar(max)' )
  , connectionManagerID         = dftnodes.x.value ( 'data(./connections/connection/@connectionManagerID)[1]', 'varchar(max)' )
  , connectionManagerRefId      = dftnodes.x.value (
                                                       'data(./connections/connection/@connectionManagerRefId)[1]'
                                                     , 'varchar(max)'
                                                   )
  , Connection_description      = dftnodes.x.value ( 'data(./connections/connection/@description)[1]', 'varchar(max)' )
  , Connection_name             = dftnodes.x.value ( 'data(./connections/connection/@name)[1]', 'varchar(max)' )
  , IsSortedProperty            = dftnodes.x.value ( 'data(./outputs/output/@isSorted)[1]', 'varchar(10)' )
  , outputsQry                  = dftnodes.x.query ( './outputs' )
  , inputsQry                   = dftnodes.x.query ( './inputs' )
From
    ssis_t.TblControlFlow                       As pkglvl
    Cross Apply pkglvl.DFTQuery.nodes ( './*' ) As dftnodes(x)

----
=======
// end::sql_modules_definition[]


