// tag::HeaderFullDisplayName[]
= sys_self.ExtendedProperties - V
// end::HeaderFullDisplayName[]

== existing_properties

// tag::existing_properties[]

:ExistsProperty--antorareferencinglist:
:ExistsProperty--is_repo_managed:
:ExistsProperty--is_ssas:
:ExistsProperty--sql_modules_definition:
:ExistsProperty--FK:
:ExistsProperty--Columns:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
E38F291C-9D61-EB11-84DC-A81E8446D5B0
// end::RepoObject_guid[]

== RepoObject_FullDisplayName2

// tag::RepoObject_FullDisplayName2[]
sys_self.ExtendedProperties
// end::RepoObject_FullDisplayName2[]

== SysObject_type

// tag::SysObject_type[]
V 
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
view
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
82099333
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2021-09-05 13:25:45
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]
[discrete]
== _


[#column-class]
=== class

[cols="d,8a,m,m,m"]
|===
|
|class
|tinyint
|NOT NULL
|
|===

.Referencing Columns
--
* xref:sys_self.extendedproperties_parameterforaddupdatedrop.adoc#column-class[+sys_self.ExtendedProperties_ParameterForAddUpdateDrop.class+]
--


[#column-classunderlinedesc]
=== class_desc

[cols="d,8a,m,m,m"]
|===
|
|class_desc
|nvarchar(60)
|NULL
|
|===

.Referencing Columns
--
* xref:sys_self.extendedproperties_parameterforaddupdatedrop.adoc#column-classunderlinedesc[+sys_self.ExtendedProperties_ParameterForAddUpdateDrop.class_desc+]
--


[#column-entityunderlinecolumnunderlinename]
=== entity_column_name

[cols="d,8a,m,m,m"]
|===
|
|entity_column_name
|nvarchar(128)
|NULL
|
|===


[#column-entityunderlineindexunderlinename]
=== entity_index_name

[cols="d,8a,m,m,m"]
|===
|
|entity_index_name
|nvarchar(128)
|NULL
|
|===


[#column-entityunderlineparameterunderlinename]
=== entity_parameter_name

[cols="d,8a,m,m,m"]
|===
|
|entity_parameter_name
|nvarchar(128)
|NULL
|
|===


[#column-level2type]
=== level2type

[cols="d,8a,m,m,m"]
|===
|
|level2type
|varchar(9)
|NULL
|
|===


[#column-majorunderlineid]
=== major_id

[cols="d,8a,m,m,m"]
|===
|
|major_id
|int
|NOT NULL
|
|===


[#column-minorunderlineid]
=== minor_id

[cols="d,8a,m,m,m"]
|===
|
|minor_id
|int
|NOT NULL
|
|===

.Referencing Columns
--
* xref:sys_self.extendedproperties_parameterforaddupdatedrop.adoc#column-minorunderlineid[+sys_self.ExtendedProperties_ParameterForAddUpdateDrop.minor_id+]
--


[#column-minorunderlinename]
=== minor_name

[cols="d,8a,m,m,m"]
|===
|
|minor_name
|nvarchar(128)
|NULL
|
|===


[#column-parentunderlinename]
=== parent_name

[cols="d,8a,m,m,m"]
|===
|
|parent_name
|sysname
|NULL
|
|===


[#column-parentunderlineobjectunderlineid]
=== parent_object_id

[cols="d,8a,m,m,m"]
|===
|
|parent_object_id
|int
|NULL
|
|===


[#column-parentunderlinetype]
=== parent_type

[cols="d,8a,m,m,m"]
|===
|
|parent_type
|char(2)
|NULL
|
|===


[#column-propertyunderlinebasetype]
=== property_basetype

[cols="d,8a,m,m,m"]
|===
|
|property_basetype
|sql_variant
|NULL
|
|===


[#column-propertyunderlinename]
=== property_name

[cols="d,8a,m,m,m"]
|===
|
|property_name
|sysname
|NOT NULL
|
|===

.Referencing Columns
--
* xref:sys_self.extendedproperties_parameterforaddupdatedrop.adoc#column-propertyunderlinename[+sys_self.ExtendedProperties_ParameterForAddUpdateDrop.property_name+]
--


[#column-propertyunderlinenvarchar]
=== property_nvarchar

[cols="d,8a,m,m,m"]
|===
|
|property_nvarchar
|nvarchar(4000)
|NULL
|
|===


[#column-propertyunderlinevalue]
=== property_value

[cols="d,8a,m,m,m"]
|===
|
|property_value
|sql_variant
|NULL
|
|===

.Referencing Columns
--
* xref:sys_self.extendedproperties_parameterforaddupdatedrop.adoc#column-propertyunderlinevalue[+sys_self.ExtendedProperties_ParameterForAddUpdateDrop.property_value+]
--


[#column-sysobjectunderlinename]
=== SysObject_name

[cols="d,8a,m,m,m"]
|===
|
|SysObject_name
|nvarchar(128)
|NULL
|
|===


[#column-sysobjectunderlineschemaunderlinename]
=== SysObject_schema_name

[cols="d,8a,m,m,m"]
|===
|
|SysObject_schema_name
|nvarchar(128)
|NULL
|
|===

.Referencing Columns
--
* xref:sys_self.extendedproperties_parameterforaddupdatedrop.adoc#column-level0name[+sys_self.ExtendedProperties_ParameterForAddUpdateDrop.level0name+]
--


// end::AntoraColumnDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]


















// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]
|
|<<column-class>>
|tinyint
|NOT NULL
|

|
|<<column-classunderlinedesc>>
|nvarchar(60)
|NULL
|

|
|<<column-entityunderlinecolumnunderlinename>>
|nvarchar(128)
|NULL
|

|
|<<column-entityunderlineindexunderlinename>>
|nvarchar(128)
|NULL
|

|
|<<column-entityunderlineparameterunderlinename>>
|nvarchar(128)
|NULL
|

|
|<<column-level2type>>
|varchar(9)
|NULL
|

|
|<<column-majorunderlineid>>
|int
|NOT NULL
|

|
|<<column-minorunderlineid>>
|int
|NOT NULL
|

|
|<<column-minorunderlinename>>
|nvarchar(128)
|NULL
|

|
|<<column-parentunderlinename>>
|sysname
|NULL
|

|
|<<column-parentunderlineobjectunderlineid>>
|int
|NULL
|

|
|<<column-parentunderlinetype>>
|char(2)
|NULL
|

|
|<<column-propertyunderlinebasetype>>
|sql_variant
|NULL
|

|
|<<column-propertyunderlinename>>
|sysname
|NOT NULL
|

|
|<<column-propertyunderlinenvarchar>>
|nvarchar(4000)
|NULL
|

|
|<<column-propertyunderlinevalue>>
|sql_variant
|NULL
|

|
|<<column-sysobjectunderlinename>>
|nvarchar(128)
|NULL
|

|
|<<column-sysobjectunderlineschemaunderlinename>>
|nvarchar(128)
|NULL
|

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

// end::AntoraIndexList[]

== AntoraMeasureDetails

// tag::AntoraMeasureDetails[]

// end::AntoraMeasureDetails[]

== AntoraMeasureDescriptions



== AntoraParameterList

// tag::AntoraParameterList[]

// end::AntoraParameterList[]

== AntoraXrefCulturesList

// tag::AntoraXrefCulturesList[]
* xref:dhw:sqldb:sys_self.extendedproperties.adoc[] - 
// end::AntoraXrefCulturesList[]

== cultures_count

// tag::cultures_count[]
1
// end::cultures_count[]

== Other tags

source: property.RepoObjectProperty_cross As rop_cross


=== additional_reference_csv

// tag::additional_reference_csv[]

// end::additional_reference_csv[]


=== AdocUspSteps

// tag::adocuspsteps[]

// end::adocuspsteps[]


=== AntoraReferencedList

// tag::antorareferencedlist[]

// end::antorareferencedlist[]


=== AntoraReferencingList

// tag::antorareferencinglist[]
* xref:dhw:sqldb:sys_self.extendedproperties_parameterforaddupdatedrop.adoc[]
// end::antorareferencinglist[]


=== Description

// tag::description[]

// end::description[]


=== exampleUsage

// tag::exampleusage[]

// end::exampleusage[]


=== exampleUsage_2

// tag::exampleusage_2[]

// end::exampleusage_2[]


=== exampleUsage_3

// tag::exampleusage_3[]

// end::exampleusage_3[]


=== exampleUsage_4

// tag::exampleusage_4[]

// end::exampleusage_4[]


=== exampleUsage_5

// tag::exampleusage_5[]

// end::exampleusage_5[]


=== exampleWrong_Usage

// tag::examplewrong_usage[]

// end::examplewrong_usage[]


=== has_execution_plan_issue

// tag::has_execution_plan_issue[]

// end::has_execution_plan_issue[]


=== has_get_referenced_issue

// tag::has_get_referenced_issue[]

// end::has_get_referenced_issue[]


=== has_history

// tag::has_history[]

// end::has_history[]


=== has_history_columns

// tag::has_history_columns[]

// end::has_history_columns[]


=== InheritanceType

// tag::inheritancetype[]

// end::inheritancetype[]


=== is_persistence

// tag::is_persistence[]

// end::is_persistence[]


=== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]

// end::is_persistence_check_duplicate_per_pk[]


=== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]

// end::is_persistence_check_for_empty_source[]


=== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]

// end::is_persistence_delete_changed[]


=== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]

// end::is_persistence_delete_missing[]


=== is_persistence_insert

// tag::is_persistence_insert[]

// end::is_persistence_insert[]


=== is_persistence_truncate

// tag::is_persistence_truncate[]

// end::is_persistence_truncate[]


=== is_persistence_update_changed

// tag::is_persistence_update_changed[]

// end::is_persistence_update_changed[]


=== is_repo_managed

// tag::is_repo_managed[]
0
// end::is_repo_managed[]


=== is_ssas

// tag::is_ssas[]
0
// end::is_ssas[]


=== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


=== MS_Description

// tag::ms_description[]

// end::ms_description[]


=== persistence_source_RepoObject_fullname

// tag::persistence_source_repoobject_fullname[]

// end::persistence_source_repoobject_fullname[]


=== persistence_source_RepoObject_fullname2

// tag::persistence_source_repoobject_fullname2[]

// end::persistence_source_repoobject_fullname2[]


=== persistence_source_RepoObject_guid

// tag::persistence_source_repoobject_guid[]

// end::persistence_source_repoobject_guid[]


=== persistence_source_RepoObject_xref

// tag::persistence_source_repoobject_xref[]

// end::persistence_source_repoobject_xref[]


=== pk_index_guid

// tag::pk_index_guid[]

// end::pk_index_guid[]


=== pk_IndexPatternColumnDatatype

// tag::pk_indexpatterncolumndatatype[]

// end::pk_indexpatterncolumndatatype[]


=== pk_IndexPatternColumnName

// tag::pk_indexpatterncolumnname[]

// end::pk_indexpatterncolumnname[]


=== pk_IndexSemanticGroup

// tag::pk_indexsemanticgroup[]

// end::pk_indexsemanticgroup[]


=== ReferencedObjectList

// tag::referencedobjectlist[]

// end::referencedobjectlist[]


=== usp_persistence_RepoObject_guid

// tag::usp_persistence_repoobject_guid[]

// end::usp_persistence_repoobject_guid[]


=== UspExamples

// tag::uspexamples[]

// end::uspexamples[]


=== uspgenerator_usp_id

// tag::uspgenerator_usp_id[]

// end::uspgenerator_usp_id[]


=== UspParameters

// tag::uspparameters[]

// end::uspparameters[]

== Boolean Attributes

source: property.RepoObjectProperty WHERE property_int = 1

// tag::boolean_attributes[]


// end::boolean_attributes[]

== PlantUML diagrams

=== PlantUML Entity

// tag::puml_entity[]
[plantuml, entity-{docname}, svg, subs=macros]
....
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:sys_self.extendedproperties.adoc[]" as sys_self.ExtendedProperties << V >> {
  - class : (tinyint)
  class_desc : (nvarchar(60))
  entity_column_name : (nvarchar(128))
  entity_index_name : (nvarchar(128))
  entity_parameter_name : (nvarchar(128))
  level2type : (varchar(9))
  - major_id : (int)
  - minor_id : (int)
  minor_name : (nvarchar(128))
  parent_name : (sysname)
  parent_object_id : (int)
  parent_type : (char(2))
  property_basetype : (sql_variant)
  - property_name : (sysname)
  property_nvarchar : (nvarchar(4000))
  property_value : (sql_variant)
  SysObject_name : (nvarchar(128))
  SysObject_schema_name : (nvarchar(128))
  --
}
....

// end::puml_entity[]

=== PlantUML Entity 1 1 FK

// tag::puml_entity_1_1_fk[]
[plantuml, entity_1_1_fk-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:sys_self.extendedproperties.adoc[]" as sys_self.ExtendedProperties << V >> {

}



footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_fk[]

=== PlantUML 1 1 ObjectRef

// tag::puml_entity_1_1_objectref[]
[plantuml, entity_1_1_objectref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:sys_self.extendedproperties.adoc[]" as sys_self.ExtendedProperties << V >> {
  --
}

entity "puml-link:dhw:sqldb:sys_self.extendedproperties_parameterforaddupdatedrop.adoc[]" as sys_self.ExtendedProperties_ParameterForAddUpdateDrop << V >> {
  --
}

sys_self.ExtendedProperties <.. sys_self.ExtendedProperties_ParameterForAddUpdateDrop

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_objectref[]

=== PlantUML 30 0 ObjectRef

// tag::puml_entity_30_0_objectref[]
[plantuml, entity_30_0_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:sys_self.extendedproperties.adoc[]" as sys_self.ExtendedProperties << V >> {
  --
}



footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_30_0_objectref[]

=== PlantUML 0 30 ObjectRef

// tag::puml_entity_0_30_objectref[]
[plantuml, entity_0_30_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:repo_sys.usp_dropextendedproperty_level_2.adoc[]" as repo_sys.usp_dropextendedproperty_level_2 << P >> {
  --
}

entity "puml-link:dhw:sqldb:sys_self.extendedproperties.adoc[]" as sys_self.ExtendedProperties << V >> {
  --
}

entity "puml-link:dhw:sqldb:sys_self.extendedproperties_parameterforaddupdatedrop.adoc[]" as sys_self.ExtendedProperties_ParameterForAddUpdateDrop << V >> {
  --
}

entity "puml-link:dhw:sqldb:sys_self.usp_dropextendedproperty_level_1.adoc[]" as sys_self.usp_dropextendedproperty_level_1 << P >> {
  --
}

entity "puml-link:dhw:sqldb:sys_self.usp_dropextendedproperty_level_2.adoc[]" as sys_self.usp_dropextendedproperty_level_2 << P >> {
  --
}

sys_self.ExtendedProperties <.. sys_self.ExtendedProperties_ParameterForAddUpdateDrop
sys_self.ExtendedProperties_ParameterForAddUpdateDrop <.. sys_self.usp_dropextendedproperty_level_2
sys_self.ExtendedProperties_ParameterForAddUpdateDrop <.. repo_sys.usp_dropextendedproperty_level_2
sys_self.ExtendedProperties_ParameterForAddUpdateDrop <.. sys_self.usp_dropextendedproperty_level_1

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_0_30_objectref[]

=== PlantUML 1 1 ColumnRef

// tag::puml_entity_1_1_colref[]
[plantuml, entity_1_1_colref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:sys_self.extendedproperties.adoc[]" as sys_self.ExtendedProperties << V >> {
  - class : (tinyint)
  class_desc : (nvarchar(60))
  entity_column_name : (nvarchar(128))
  entity_index_name : (nvarchar(128))
  entity_parameter_name : (nvarchar(128))
  level2type : (varchar(9))
  - major_id : (int)
  - minor_id : (int)
  minor_name : (nvarchar(128))
  parent_name : (sysname)
  parent_object_id : (int)
  parent_type : (char(2))
  property_basetype : (sql_variant)
  - property_name : (sysname)
  property_nvarchar : (nvarchar(4000))
  property_value : (sql_variant)
  SysObject_name : (nvarchar(128))
  SysObject_schema_name : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:sys_self.extendedproperties_parameterforaddupdatedrop.adoc[]" as sys_self.ExtendedProperties_ParameterForAddUpdateDrop << V >> {
  - class : (tinyint)
  class_desc : (nvarchar(60))
  level0name : (nvarchar(128))
  - level0type : (varchar(6))
  level1name : (nvarchar(128))
  level1type : (varchar(9))
  level2name : (nvarchar(128))
  level2type : (varchar(10))
  - minor_id : (int)
  - property_name : (sysname)
  property_value : (sql_variant)
  type : (char(2))
  type_level1type : (varchar(9))
  type_level2type : (varchar(10))
  --
}

sys_self.ExtendedProperties <.. sys_self.ExtendedProperties_ParameterForAddUpdateDrop
"sys_self.ExtendedProperties::class" <-- "sys_self.ExtendedProperties_ParameterForAddUpdateDrop::class"
"sys_self.ExtendedProperties::class_desc" <-- "sys_self.ExtendedProperties_ParameterForAddUpdateDrop::class_desc"
"sys_self.ExtendedProperties::minor_id" <-- "sys_self.ExtendedProperties_ParameterForAddUpdateDrop::minor_id"
"sys_self.ExtendedProperties::property_name" <-- "sys_self.ExtendedProperties_ParameterForAddUpdateDrop::property_name"
"sys_self.ExtendedProperties::property_value" <-- "sys_self.ExtendedProperties_ParameterForAddUpdateDrop::property_value"
"sys_self.ExtendedProperties::SysObject_schema_name" <-- "sys_self.ExtendedProperties_ParameterForAddUpdateDrop::level0name"

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_colref[]


== sql_modules_definition

// tag::sql_modules_definition[]
[%collapsible]
=======
[source,sql,numbered,indent=0]
----

CREATE View sys_self.ExtendedProperties
As
Select
    sep.class
  , sep.major_id
  , sep.minor_id
  , property_name         = sep.name Collate Database_Default
  , sep.class_desc
  , property_value        = sep.value
  , SysObject_schema_name = Case
                                When sep.class In
                                ( 1, 2, 7 )
                                    Then
                                    Object_Schema_Name ( sep.major_id /*, [db].[dwh_database_id]*/ )
                            End
  , SysObject_name        = Case
                                When sep.class In
                                ( 1, 2, 7 )
                                    Then
                                    Object_Name ( sep.major_id /*, [db].[dwh_database_id]*/ )
                            End
  , minor_name            = Case sep.class
                                When 1
                                    Then
                                    sc.name
                                When 2
                                    Then
                                    sp.name
                                When 3
                                    Then
                                    si.name
                            End Collate Database_Default
  , entity_column_name    = Case
                                When sep.class = 1
                                    Then
                                    sc.name
                            End Collate Database_Default
  , entity_parameter_name = Case
                                When sep.class = 2
                                    Then
                                    sp.name
                            End Collate Database_Default
  , entity_index_name     = Case
                                When sep.class = 7
                                    Then
                                    si.name
                            End Collate Database_Default
  , level2type            = Case
                                When sep.class = 1
                                     And sep.minor_id > 0
                                    Then
                                    'COLUMN'
                                When sep.class = 2
                                     And sep.minor_id > 0
                                    Then
                                    'PARAMETER'
                                When sep.class = 7
                                     And sep.minor_id > 0
                                    Then
                                    'INDEX'
                            End
  , property_basetype     = Sql_Variant_Property ( sep.value, 'BaseType' )
  , property_nvarchar     = Try_Cast(sep.value As NVarchar(4000))
  , so.parent_object_id
  , parent_name           = parent.name
  , parent_type           = parent.type
-- Explicit conversion from data type int to uniqueidentifier is not allowed.
--, [property_value_uniqueidentifier] = TRY_CAST([sep].value As UniqueIdentifier)
From
    sys.extended_properties As sep
    Left Outer Join
        sys.columns         As sc
            On
            sep.major_id     = sc.object_id
            And sep.minor_id = sc.column_id

    Left Outer Join
        sys.parameters      As sp
            On
            sep.major_id     = sp.object_id
            And sep.minor_id = sp.parameter_id

    Left Outer Join
        sys.indexes         As si
            On
            sep.major_id     = si.object_id
            And sep.minor_id = si.index_id

    Left Outer Join
        sys.objects         As so
            On
            sep.major_id     = so.object_id

    Left Outer Join
        sys.objects         As parent
            On
            parent.object_id = so.parent_object_id
--CROSS APPLY
--repo.ftv_dwh_database() AS db

----
=======
// end::sql_modules_definition[]


