// tag::HeaderFullDisplayName[]
= uspgenerator.GeneratorUsp_check_persistence - V
// end::HeaderFullDisplayName[]

== existing_properties

// tag::existing_properties[]

:ExistsProperty--antorareferencedlist:
:ExistsProperty--description:
:ExistsProperty--is_repo_managed:
:ExistsProperty--is_ssas:
:ExistsProperty--referencedobjectlist:
:ExistsProperty--sql_modules_definition:
:ExistsProperty--FK:
:ExistsProperty--AntoraIndexList:
:ExistsProperty--Columns:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
F604F585-2055-EC11-8533-A81E8446D5B0
// end::RepoObject_guid[]

== RepoObject_FullDisplayName2

// tag::RepoObject_FullDisplayName2[]
uspgenerator.GeneratorUsp_check_persistence
// end::RepoObject_FullDisplayName2[]

== SysObject_type

// tag::SysObject_type[]
V 
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
view
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
231723928
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2022-01-05 18:06:35
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]
[discrete]
== _


[#column-columnlistignore]
=== ColumnListIgnore

[cols="d,8a,m,m,m"]
|===
|
|ColumnListIgnore
|nvarchar(4000)
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_persistence.adoc#column-columnlistignore[+repo.RepoObject_persistence.ColumnListIgnore+]
--


[#column-columnlistnocomparebutupdate]
=== ColumnListNoCompareButUpdate

[cols="d,8a,m,m,m"]
|===
|
|ColumnListNoCompareButUpdate
|nvarchar(4000)
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_persistence.adoc#column-columnlistnocomparebutupdate[+repo.RepoObject_persistence.ColumnListNoCompareButUpdate+]
--


[#column-columnlistnocomparenoupdate]
=== ColumnListNoCompareNoUpdate

[cols="d,8a,m,m,m"]
|===
|
|ColumnListNoCompareNoUpdate
|nvarchar(4000)
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_persistence.adoc#column-columnlistnocomparenoupdate[+repo.RepoObject_persistence.ColumnListNoCompareNoUpdate+]
--


[#column-hasunderlinehistory]
=== has_history

[cols="d,8a,m,m,m"]
|===
|
|has_history
|bit
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_persistence.adoc#column-hasunderlinehistory[+repo.RepoObject_persistence.has_history+]
--


[#column-hasunderlinehistoryunderlinecolumns]
=== has_history_columns

[cols="d,8a,m,m,m"]
|===
|
|has_history_columns
|bit
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_persistence.adoc#column-hasunderlinehistoryunderlinecolumns[+repo.RepoObject_persistence.has_history_columns+]
--


[#column-hasunderlinelogging]
=== has_logging

[cols="d,8a,m,m,m"]
|===
|
|has_logging
|tinyint
|NOT NULL
|
|===

.Referenced Columns
--
* xref:uspgenerator.generatorusp.adoc#column-hasunderlinelogging[+uspgenerator.GeneratorUsp.has_logging+]
--


[#column-historyunderlineschemaunderlinename]
=== history_schema_name

[cols="d,8a,m,m,m"]
|===
|
|history_schema_name
|nvarchar(128)
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_persistence.adoc#column-historyunderlineschemaunderlinename[+repo.RepoObject_persistence.history_schema_name+]
--


[#column-historyunderlinetableunderlinename]
=== history_table_name

[cols="d,8a,m,m,m"]
|===
|
|history_table_name
|nvarchar(128)
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_persistence.adoc#column-historyunderlinetableunderlinename[+repo.RepoObject_persistence.history_table_name+]
--


[#column-id]
=== id

[cols="d,8a,m,m,m"]
|===
|
|id
|int
|NOT NULL
|
|===

.Referenced Columns
--
* xref:uspgenerator.generatorusp.adoc#column-id[+uspgenerator.GeneratorUsp.id+]
--


[#column-isunderlinepersistence]
=== is_persistence

[cols="d,8a,m,m,m"]
|===
|
|is_persistence
|bit
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_persistence.adoc#column-isunderlinepersistence[+repo.RepoObject_persistence.is_persistence+]
--


[#column-isunderlinepersistenceunderlinecheckunderlineduplicateunderlineperunderlinepk]
=== is_persistence_check_duplicate_per_pk

[cols="d,8a,m,m,m"]
|===
|
|is_persistence_check_duplicate_per_pk
|bit
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_persistence.adoc#column-isunderlinepersistenceunderlinecheckunderlineduplicateunderlineperunderlinepk[+repo.RepoObject_persistence.is_persistence_check_duplicate_per_pk+]
--


[#column-isunderlinepersistenceunderlinecheckunderlineforunderlineemptyunderlinesource]
=== is_persistence_check_for_empty_source

[cols="d,8a,m,m,m"]
|===
|
|is_persistence_check_for_empty_source
|bit
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_persistence.adoc#column-isunderlinepersistenceunderlinecheckunderlineforunderlineemptyunderlinesource[+repo.RepoObject_persistence.is_persistence_check_for_empty_source+]
--


[#column-isunderlinepersistenceunderlinedeleteunderlinechanged]
=== is_persistence_delete_changed

[cols="d,8a,m,m,m"]
|===
|
|is_persistence_delete_changed
|bit
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_persistence.adoc#column-isunderlinepersistenceunderlinedeleteunderlinechanged[+repo.RepoObject_persistence.is_persistence_delete_changed+]
--


[#column-isunderlinepersistenceunderlinedeleteunderlinemissing]
=== is_persistence_delete_missing

[cols="d,8a,m,m,m"]
|===
|
|is_persistence_delete_missing
|bit
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_persistence.adoc#column-isunderlinepersistenceunderlinedeleteunderlinemissing[+repo.RepoObject_persistence.is_persistence_delete_missing+]
--


[#column-isunderlinepersistenceunderlineinsert]
=== is_persistence_insert

[cols="d,8a,m,m,m"]
|===
|
|is_persistence_insert
|bit
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_persistence.adoc#column-isunderlinepersistenceunderlineinsert[+repo.RepoObject_persistence.is_persistence_insert+]
--


[#column-isunderlinepersistenceunderlinepersistunderlinesource]
=== is_persistence_persist_source

[cols="d,8a,m,m,m"]
|===
|
|is_persistence_persist_source
|bit
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_persistence.adoc#column-isunderlinepersistenceunderlinepersistunderlinesource[+repo.RepoObject_persistence.is_persistence_persist_source+]
--


[#column-isunderlinepersistenceunderlinetruncate]
=== is_persistence_truncate

[cols="d,8a,m,m,m"]
|===
|
|is_persistence_truncate
|bit
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_persistence.adoc#column-isunderlinepersistenceunderlinetruncate[+repo.RepoObject_persistence.is_persistence_truncate+]
--


[#column-isunderlinepersistenceunderlineupdateunderlinechanged]
=== is_persistence_update_changed

[cols="d,8a,m,m,m"]
|===
|
|is_persistence_update_changed
|bit
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_persistence.adoc#column-isunderlinepersistenceunderlineupdateunderlinechanged[+repo.RepoObject_persistence.is_persistence_update_changed+]
--


[#column-postscript]
=== postscript

[cols="d,8a,m,m,m"]
|===
|
|postscript
|nvarchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_persistence.adoc#column-postscript[+repo.RepoObject_persistence.postscript+]
--


[#column-prescript]
=== prescript

[cols="d,8a,m,m,m"]
|===
|
|prescript
|nvarchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_persistence.adoc#column-prescript[+repo.RepoObject_persistence.prescript+]
--


[#column-repoobjectunderlinefullname]
=== RepoObject_fullname

[cols="d,8a,m,m,m"]
|===
|
|RepoObject_fullname
|nvarchar(261)
|NULL
|
|===

.Description
--
(concat('[',[RepoObject_schema_name],'].[',[RepoObject_name],']'))
--
{empty} +

.Referenced Columns
--
* xref:repo.repoobject.adoc#column-repoobjectunderlinefullname[+repo.RepoObject.RepoObject_fullname+]
--


[#column-repoobjectunderlineguid]
=== RepoObject_guid

[cols="d,8a,m,m,m"]
|===
|
|RepoObject_guid
|uniqueidentifier
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject.adoc#column-repoobjectunderlineguid[+repo.RepoObject.RepoObject_guid+]
--


[#column-sourceunderlinerepoobjectunderlineguid]
=== source_RepoObject_guid

[cols="d,8a,m,m,m"]
|===
|
|source_RepoObject_guid
|uniqueidentifier
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_persistence.adoc#column-sourceunderlinerepoobjectunderlineguid[+repo.RepoObject_persistence.source_RepoObject_guid+]
--


[#column-sourceunderlinerepoobjectunderlinename]
=== source_RepoObject_name

[cols="d,8a,m,m,m"]
|===
|
|source_RepoObject_name
|nvarchar(128)
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_persistence.adoc#column-sourceunderlinerepoobjectunderlinename[+repo.RepoObject_persistence.source_RepoObject_name+]
--


[#column-targetunderlinerepoobjectunderlineguid]
=== target_RepoObject_guid

[cols="d,8a,m,m,m"]
|===
|
|target_RepoObject_guid
|uniqueidentifier
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject_persistence.adoc#column-targetunderlinerepoobjectunderlineguid[+repo.RepoObject_persistence.target_RepoObject_guid+]
--


[#column-temporalunderlinetype]
=== temporal_type

[cols="d,8a,m,m,m"]
|===
|
|temporal_type
|tinyint
|NULL
|
|===

.Description
--
(CONVERT([tinyint],case [has_history] when (1) then (2) else (0) end))
--
{empty} +

.Referenced Columns
--
* xref:repo.repoobject_persistence.adoc#column-temporalunderlinetype[+repo.RepoObject_persistence.temporal_type+]
--


[#column-uspunderlinedescription]
=== usp_Description

[cols="d,8a,m,m,m"]
|===
|
|usp_Description
|nvarchar(4000)
|NULL
|
|===

.Referenced Columns
--
* xref:uspgenerator.generatorusp.adoc#column-uspunderlinedescription[+uspgenerator.GeneratorUsp.usp_Description+]
--


[#column-uspunderlineexamples]
=== usp_Examples

[cols="d,8a,m,m,m"]
|===
|
|usp_Examples
|nvarchar(4000)
|NULL
|
|===

.Referenced Columns
--
* xref:uspgenerator.generatorusp.adoc#column-uspunderlineexamples[+uspgenerator.GeneratorUsp.usp_Examples+]
--


[#column-uspunderlinefullname]
=== usp_fullname

[cols="d,8a,m,m,m"]
|===
|
|usp_fullname
|nvarchar(261)
|NOT NULL
|
|===

.Description
--
(concat('[',[usp_schema],'].[',[usp_name],']'))
--
{empty} +

.Referenced Columns
--
* xref:uspgenerator.generatorusp.adoc#column-uspunderlinefullname[+uspgenerator.GeneratorUsp.usp_fullname+]
--


[#column-uspunderlinename]
=== usp_name

[cols="d,8a,m,m,m"]
|===
|
|usp_name
|nvarchar(128)
|NOT NULL
|
|===

.Referenced Columns
--
* xref:uspgenerator.generatorusp.adoc#column-uspunderlinename[+uspgenerator.GeneratorUsp.usp_name+]
--


[#column-uspunderlineschema]
=== usp_schema

[cols="d,8a,m,m,m"]
|===
|
|usp_schema
|nvarchar(128)
|NOT NULL
|
|===

.Referenced Columns
--
* xref:uspgenerator.generatorusp.adoc#column-uspunderlineschema[+uspgenerator.GeneratorUsp.usp_schema+]
--


// end::AntoraColumnDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]































// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]
|
|<<column-columnlistignore>>
|nvarchar(4000)
|NULL
|

|
|<<column-columnlistnocomparebutupdate>>
|nvarchar(4000)
|NULL
|

|
|<<column-columnlistnocomparenoupdate>>
|nvarchar(4000)
|NULL
|

|
|<<column-hasunderlinehistory>>
|bit
|NULL
|

|
|<<column-hasunderlinehistoryunderlinecolumns>>
|bit
|NULL
|

|
|<<column-hasunderlinelogging>>
|tinyint
|NOT NULL
|

|
|<<column-historyunderlineschemaunderlinename>>
|nvarchar(128)
|NULL
|

|
|<<column-historyunderlinetableunderlinename>>
|nvarchar(128)
|NULL
|

|
|<<column-id>>
|int
|NOT NULL
|

|
|<<column-isunderlinepersistence>>
|bit
|NULL
|

|
|<<column-isunderlinepersistenceunderlinecheckunderlineduplicateunderlineperunderlinepk>>
|bit
|NULL
|

|
|<<column-isunderlinepersistenceunderlinecheckunderlineforunderlineemptyunderlinesource>>
|bit
|NULL
|

|
|<<column-isunderlinepersistenceunderlinedeleteunderlinechanged>>
|bit
|NULL
|

|
|<<column-isunderlinepersistenceunderlinedeleteunderlinemissing>>
|bit
|NULL
|

|
|<<column-isunderlinepersistenceunderlineinsert>>
|bit
|NULL
|

|
|<<column-isunderlinepersistenceunderlinepersistunderlinesource>>
|bit
|NULL
|

|
|<<column-isunderlinepersistenceunderlinetruncate>>
|bit
|NULL
|

|
|<<column-isunderlinepersistenceunderlineupdateunderlinechanged>>
|bit
|NULL
|

|
|<<column-postscript>>
|nvarchar(max)
|NULL
|

|
|<<column-prescript>>
|nvarchar(max)
|NULL
|

|
|<<column-repoobjectunderlinefullname>>
|nvarchar(261)
|NULL
|

|
|<<column-repoobjectunderlineguid>>
|uniqueidentifier
|NULL
|

|
|<<column-sourceunderlinerepoobjectunderlineguid>>
|uniqueidentifier
|NULL
|

|
|<<column-sourceunderlinerepoobjectunderlinename>>
|nvarchar(128)
|NULL
|

|
|<<column-targetunderlinerepoobjectunderlineguid>>
|uniqueidentifier
|NULL
|

|
|<<column-temporalunderlinetype>>
|tinyint
|NULL
|

|
|<<column-uspunderlinedescription>>
|nvarchar(4000)
|NULL
|

|
|<<column-uspunderlineexamples>>
|nvarchar(4000)
|NULL
|

|
|<<column-uspunderlinefullname>>
|nvarchar(261)
|NOT NULL
|

|
|<<column-uspunderlinename>>
|nvarchar(128)
|NOT NULL
|

|
|<<column-uspunderlineschema>>
|nvarchar(128)
|NOT NULL
|

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

[#index-idxunderlinegeneratoruspunderlinecheckunderlinepersistenceunderlineunderline1]
=== idx_GeneratorUsp_check_persistence++__++1

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-RepoObject_guid>>; uniqueidentifier
--
* PK, Unique, Real: 0, 0, 0


[#index-idxunderlinegeneratoruspunderlinecheckunderlinepersistenceunderlineunderline2]
=== idx_GeneratorUsp_check_persistence++__++2

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-id>>; int
--
* PK, Unique, Real: 0, 0, 0


[#index-idxunderlinegeneratoruspunderlinecheckunderlinepersistenceunderlineunderline3]
=== idx_GeneratorUsp_check_persistence++__++3

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-usp_schema>>; nvarchar(128)
* <<column-usp_name>>; nvarchar(128)
--
* PK, Unique, Real: 0, 0, 0


[#index-idxunderlinegeneratoruspunderlinecheckunderlinepersistenceunderlineunderline4]
=== idx_GeneratorUsp_check_persistence++__++4

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-target_RepoObject_guid>>; uniqueidentifier
--
* PK, Unique, Real: 0, 0, 0

// end::AntoraIndexList[]

== AntoraMeasureDetails

// tag::AntoraMeasureDetails[]

// end::AntoraMeasureDetails[]

== AntoraMeasureDescriptions



== AntoraParameterList

// tag::AntoraParameterList[]

// end::AntoraParameterList[]

== AntoraXrefCulturesList

// tag::AntoraXrefCulturesList[]
* xref:dhw:sqldb:uspgenerator.generatorusp_check_persistence.adoc[] - 
// end::AntoraXrefCulturesList[]

== cultures_count

// tag::cultures_count[]
1
// end::cultures_count[]

== Other tags

source: property.RepoObjectProperty_cross As rop_cross


=== additional_reference_csv

// tag::additional_reference_csv[]

// end::additional_reference_csv[]


=== AdocUspSteps

// tag::adocuspsteps[]

// end::adocuspsteps[]


=== AntoraReferencedList

// tag::antorareferencedlist[]
* xref:dhw:sqldb:repo.repoobject.adoc[]
* xref:dhw:sqldb:repo.repoobject_persistence.adoc[]
* xref:dhw:sqldb:uspgenerator.generatorusp.adoc[]
// end::antorareferencedlist[]


=== AntoraReferencingList

// tag::antorareferencinglist[]

// end::antorareferencinglist[]


=== Description

// tag::description[]

Sometimes it can happen that a persistence was created with the Persistence Generator and still exists in xref:sqldb:uspgenerator.generatorusp.adoc[], 
although the persistence has already been removed from xref:sqldb:repo.repoobject_persistence.adoc[].

This view helps to identify such entries and then remove such legacy entries from xref:sqldb:uspgenerator.generatorusp.adoc[]

If the last columns of the xref:sqldb:uspgenerator.generatorusp_check_persistence.adoc[] view have the value NULL, then there is no persistence anymore. The corresponding entries can then be removed from xref:sqldb:uspgenerator.generatorusp.adoc[] after careful checking.
// end::description[]


=== exampleUsage

// tag::exampleusage[]

// end::exampleusage[]


=== exampleUsage_2

// tag::exampleusage_2[]

// end::exampleusage_2[]


=== exampleUsage_3

// tag::exampleusage_3[]

// end::exampleusage_3[]


=== exampleUsage_4

// tag::exampleusage_4[]

// end::exampleusage_4[]


=== exampleUsage_5

// tag::exampleusage_5[]

// end::exampleusage_5[]


=== exampleWrong_Usage

// tag::examplewrong_usage[]

// end::examplewrong_usage[]


=== has_execution_plan_issue

// tag::has_execution_plan_issue[]

// end::has_execution_plan_issue[]


=== has_get_referenced_issue

// tag::has_get_referenced_issue[]

// end::has_get_referenced_issue[]


=== has_history

// tag::has_history[]

// end::has_history[]


=== has_history_columns

// tag::has_history_columns[]

// end::has_history_columns[]


=== InheritanceType

// tag::inheritancetype[]

// end::inheritancetype[]


=== is_persistence

// tag::is_persistence[]

// end::is_persistence[]


=== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]

// end::is_persistence_check_duplicate_per_pk[]


=== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]

// end::is_persistence_check_for_empty_source[]


=== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]

// end::is_persistence_delete_changed[]


=== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]

// end::is_persistence_delete_missing[]


=== is_persistence_insert

// tag::is_persistence_insert[]

// end::is_persistence_insert[]


=== is_persistence_truncate

// tag::is_persistence_truncate[]

// end::is_persistence_truncate[]


=== is_persistence_update_changed

// tag::is_persistence_update_changed[]

// end::is_persistence_update_changed[]


=== is_repo_managed

// tag::is_repo_managed[]
0
// end::is_repo_managed[]


=== is_ssas

// tag::is_ssas[]
0
// end::is_ssas[]


=== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


=== MS_Description

// tag::ms_description[]

// end::ms_description[]


=== persistence_source_RepoObject_fullname

// tag::persistence_source_repoobject_fullname[]

// end::persistence_source_repoobject_fullname[]


=== persistence_source_RepoObject_fullname2

// tag::persistence_source_repoobject_fullname2[]

// end::persistence_source_repoobject_fullname2[]


=== persistence_source_RepoObject_guid

// tag::persistence_source_repoobject_guid[]

// end::persistence_source_repoobject_guid[]


=== persistence_source_RepoObject_xref

// tag::persistence_source_repoobject_xref[]

// end::persistence_source_repoobject_xref[]


=== pk_index_guid

// tag::pk_index_guid[]

// end::pk_index_guid[]


=== pk_IndexPatternColumnDatatype

// tag::pk_indexpatterncolumndatatype[]

// end::pk_indexpatterncolumndatatype[]


=== pk_IndexPatternColumnName

// tag::pk_indexpatterncolumnname[]

// end::pk_indexpatterncolumnname[]


=== pk_IndexSemanticGroup

// tag::pk_indexsemanticgroup[]

// end::pk_indexsemanticgroup[]


=== ReferencedObjectList

// tag::referencedobjectlist[]
* [repo].[RepoObject]
* [repo].[RepoObject_persistence]
* [uspgenerator].[GeneratorUsp]
// end::referencedobjectlist[]


=== usp_persistence_RepoObject_guid

// tag::usp_persistence_repoobject_guid[]

// end::usp_persistence_repoobject_guid[]


=== UspExamples

// tag::uspexamples[]

// end::uspexamples[]


=== uspgenerator_usp_id

// tag::uspgenerator_usp_id[]

// end::uspgenerator_usp_id[]


=== UspParameters

// tag::uspparameters[]

// end::uspparameters[]

== Boolean Attributes

source: property.RepoObjectProperty WHERE property_int = 1

// tag::boolean_attributes[]


// end::boolean_attributes[]

== PlantUML diagrams

=== PlantUML Entity

// tag::puml_entity[]
[plantuml, entity-{docname}, svg, subs=macros]
....
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:uspgenerator.generatorusp_check_persistence.adoc[]" as uspgenerator.GeneratorUsp_check_persistence << V >> {
  ColumnListIgnore : (nvarchar(4000))
  ColumnListNoCompareButUpdate : (nvarchar(4000))
  ColumnListNoCompareNoUpdate : (nvarchar(4000))
  has_history : (bit)
  has_history_columns : (bit)
  - has_logging : (tinyint)
  history_schema_name : (nvarchar(128))
  history_table_name : (nvarchar(128))
  - id : (int)
  is_persistence : (bit)
  is_persistence_check_duplicate_per_pk : (bit)
  is_persistence_check_for_empty_source : (bit)
  is_persistence_delete_changed : (bit)
  is_persistence_delete_missing : (bit)
  is_persistence_insert : (bit)
  is_persistence_persist_source : (bit)
  is_persistence_truncate : (bit)
  is_persistence_update_changed : (bit)
  postscript : (nvarchar(max))
  prescript : (nvarchar(max))
  RepoObject_fullname : (nvarchar(261))
  RepoObject_guid : (uniqueidentifier)
  source_RepoObject_guid : (uniqueidentifier)
  source_RepoObject_name : (nvarchar(128))
  target_RepoObject_guid : (uniqueidentifier)
  temporal_type : (tinyint)
  usp_Description : (nvarchar(4000))
  usp_Examples : (nvarchar(4000))
  - usp_fullname : (nvarchar(261))
  - usp_name : (nvarchar(128))
  - usp_schema : (nvarchar(128))
  --
}
....

// end::puml_entity[]

=== PlantUML Entity 1 1 FK

// tag::puml_entity_1_1_fk[]
[plantuml, entity_1_1_fk-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:uspgenerator.generatorusp_check_persistence.adoc[]" as uspgenerator.GeneratorUsp_check_persistence << V >> {
- idx_GeneratorUsp_check_persistence__1

..
RepoObject_guid; uniqueidentifier
--
- idx_GeneratorUsp_check_persistence__2

..
id; int
--
- idx_GeneratorUsp_check_persistence__3

..
usp_schema; nvarchar(128)
usp_name; nvarchar(128)
--
- idx_GeneratorUsp_check_persistence__4

..
target_RepoObject_guid; uniqueidentifier
}



footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_fk[]

=== PlantUML 1 1 ObjectRef

// tag::puml_entity_1_1_objectref[]
[plantuml, entity_1_1_objectref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:repo.repoobject.adoc[]" as repo.RepoObject << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_persistence.adoc[]" as repo.RepoObject_persistence << U >> {
  - **target_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.generatorusp.adoc[]" as uspgenerator.GeneratorUsp << U >> {
  - **id** : (int)
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.generatorusp_check_persistence.adoc[]" as uspgenerator.GeneratorUsp_check_persistence << V >> {
  --
}

repo.RepoObject <.. uspgenerator.GeneratorUsp_check_persistence
repo.RepoObject_persistence <.. uspgenerator.GeneratorUsp_check_persistence
uspgenerator.GeneratorUsp <.. uspgenerator.GeneratorUsp_check_persistence

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_objectref[]

=== PlantUML 30 0 ObjectRef

// tag::puml_entity_30_0_objectref[]
[plantuml, entity_30_0_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:config.ftv_get_parameter_value.adoc[]" as config.ftv_get_parameter_value << IF >> {
  --
}

entity "puml-link:dhw:sqldb:config.parameter.adoc[]" as config.Parameter << U >> {
  - **Parameter_name** : (varchar(100))
  - **sub_Parameter** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:configt.parameter_default.adoc[]" as configT.Parameter_default << V >> {
  - **Parameter_name** : (varchar(52))
  - **sub_Parameter** : (nvarchar(26))
  --
}

entity "puml-link:dhw:sqldb:property.external_repoobjectproperty.adoc[]" as property.external_RepoObjectProperty << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.propertyname_repoobject.adoc[]" as property.PropertyName_RepoObject << V >> {
  **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.propertyname_repoobject_t.adoc[]" as property.PropertyName_RepoObject_T << U >> {
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty.adoc[]" as property.RepoObjectProperty << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty_external_src.adoc[]" as property.RepoObjectProperty_external_src << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty_external_tgt.adoc[]" as property.RepoObjectProperty_external_tgt << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty_selectedpropertyname_split.adoc[]" as property.RepoObjectProperty_SelectedPropertyName_split << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference.adoc[]" as reference.additional_Reference << U >> {
  # **tik_hash_c** : (nvarchar(32))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_from_properties_src.adoc[]" as reference.additional_Reference_from_properties_src << V >> {
  **referenced_AntoraComponent** : (nvarchar(max))
  **referenced_AntoraModule** : (nvarchar(max))
  **referenced_Schema** : (nvarchar(max))
  **referenced_Object** : (nvarchar(max))
  **referenced_Column** : (nvarchar(max))
  **referencing_AntoraComponent** : (nvarchar(max))
  **referencing_AntoraModule** : (nvarchar(max))
  **referencing_Schema** : (nvarchar(max))
  **referencing_Object** : (nvarchar(max))
  **referencing_Column** : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_from_properties_tgt.adoc[]" as reference.additional_Reference_from_properties_tgt << V >> {
  - **referenced_AntoraComponent** : (nvarchar(128))
  - **referenced_AntoraModule** : (nvarchar(128))
  - **referenced_Schema** : (nvarchar(128))
  - **referenced_Object** : (nvarchar(128))
  **referenced_Column** : (nvarchar(128))
  - **referencing_AntoraComponent** : (nvarchar(128))
  - **referencing_AntoraModule** : (nvarchar(128))
  - **referencing_Schema** : (nvarchar(128))
  - **referencing_Object** : (nvarchar(128))
  **referencing_Column** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_from_ssas_src.adoc[]" as reference.additional_Reference_from_ssas_src << V >> {
  **referenced_AntoraComponent** : (nvarchar(128))
  **referenced_AntoraModule** : (nvarchar(128))
  **referenced_Schema** : (nvarchar(max))
  **referenced_Object** : (nvarchar(max))
  **referenced_Column** : (nvarchar(500))
  **referencing_AntoraComponent** : (nvarchar(max))
  **referencing_AntoraModule** : (nvarchar(max))
  - **referencing_Schema** : (nvarchar(128))
  - **referencing_Object** : (nvarchar(128))
  **referencing_Column** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_from_ssas_tgt.adoc[]" as reference.additional_Reference_from_ssas_tgt << V >> {
  - **referenced_AntoraComponent** : (nvarchar(128))
  - **referenced_AntoraModule** : (nvarchar(128))
  - **referenced_Schema** : (nvarchar(128))
  - **referenced_Object** : (nvarchar(128))
  **referenced_Column** : (nvarchar(128))
  - **referencing_AntoraComponent** : (nvarchar(128))
  - **referencing_AntoraModule** : (nvarchar(128))
  - **referencing_Schema** : (nvarchar(128))
  - **referencing_Object** : (nvarchar(128))
  **referencing_Column** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_is_external.adoc[]" as reference.additional_Reference_is_external << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_object.adoc[]" as reference.additional_Reference_Object << V >> {
  - **AntoraComponent** : (nvarchar(128))
  - **AntoraModule** : (nvarchar(128))
  - **SchemaName** : (nvarchar(128))
  - **ObjectName** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_object_t.adoc[]" as reference.additional_Reference_Object_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_wo_columns_from_properties_src.adoc[]" as reference.additional_Reference_wo_columns_from_properties_src << V >> {
  **referenced_AntoraComponent** : (nvarchar(max))
  **referenced_AntoraModule** : (nvarchar(max))
  **referenced_Schema** : (nvarchar(max))
  **referenced_Object** : (nvarchar(max))
  **referencing_AntoraComponent** : (nvarchar(max))
  **referencing_AntoraModule** : (nvarchar(max))
  **referencing_Schema** : (nvarchar(max))
  **referencing_Object** : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_wo_columns_from_properties_tgt.adoc[]" as reference.additional_Reference_wo_columns_from_properties_tgt << V >> {
  - **referenced_AntoraComponent** : (nvarchar(128))
  - **referenced_AntoraModule** : (nvarchar(128))
  - **referenced_Schema** : (nvarchar(128))
  - **referenced_Object** : (nvarchar(128))
  - **referencing_AntoraComponent** : (nvarchar(128))
  - **referencing_AntoraModule** : (nvarchar(128))
  - **referencing_Schema** : (nvarchar(128))
  - **referencing_Object** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject.adoc[]" as repo.RepoObject << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_external_src.adoc[]" as repo.RepoObject_external_src << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_external_tgt.adoc[]" as repo.RepoObject_external_tgt << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_persistence.adoc[]" as repo.RepoObject_persistence << U >> {
  - **target_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_ssas_src.adoc[]" as repo.RepoObject_SSAS_src << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_ssas_tgt.adoc[]" as repo.RepoObject_SSAS_tgt << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.reposchema.adoc[]" as repo.RepoSchema << U >> {
  - **RepoSchema_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.reposchema_ssas_src.adoc[]" as repo.RepoSchema_ssas_src << V >> {
  - **RepoSchema_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:repo.reposchema_ssas_tgt.adoc[]" as repo.RepoSchema_ssas_tgt << V >> {
  - **RepoSchema_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:ssas.additional_reference_step1.adoc[]" as ssas.additional_Reference_step1 << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json.adoc[]" as ssas.model_json << U >> {
  - **databasename** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_10.adoc[]" as ssas.model_json_10 << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_20.adoc[]" as ssas.model_json_20 << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_201_descriptions_multiline.adoc[]" as ssas.model_json_201_descriptions_multiline << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_2011_descriptions_stragg.adoc[]" as ssas.model_json_2011_descriptions_StrAgg << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31_tables.adoc[]" as ssas.model_json_31_tables << V >> {
  - **databasename** : (nvarchar(128))
  **tables_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31_tables_t.adoc[]" as ssas.model_json_31_tables_T << U >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_311_tables_columns.adoc[]" as ssas.model_json_311_tables_columns << V >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  **tables_columns_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_311_tables_columns_t.adoc[]" as ssas.model_json_311_tables_columns_T << U >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  - **tables_columns_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_313_tables_partitions.adoc[]" as ssas.model_json_313_tables_partitions << V >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  **tables_partitions_name** : (nvarchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_3131_tables_partitions_source.adoc[]" as ssas.model_json_3131_tables_partitions_source << V >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  **tables_partitions_name** : (nvarchar(500))
  **tables_partitions_source_name** : (nvarchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31311_tables_partitions_source_posfrom.adoc[]" as ssas.model_json_31311_tables_partitions_source_PosFrom << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_313111_tables_partitions_source_stringfrom.adoc[]" as ssas.model_json_313111_tables_partitions_source_StringFrom << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_3131111_tables_partitions_source_posdot.adoc[]" as ssas.model_json_3131111_tables_partitions_source_PosDot << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31311111_tables_partitions_source_part123.adoc[]" as ssas.model_json_31311111_tables_partitions_source_Part123 << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_33_datasources.adoc[]" as ssas.model_json_33_dataSources << V >> {
  - **databasename** : (nvarchar(128))
  **dataSources_name** : (nvarchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_33_datasources_t.adoc[]" as ssas.model_json_33_dataSources_T << U >> {
  - **databasename** : (nvarchar(128))
  - **dataSources_name** : (nvarchar(500))
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.generatorusp.adoc[]" as uspgenerator.GeneratorUsp << U >> {
  - **id** : (int)
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.generatorusp_check_persistence.adoc[]" as uspgenerator.GeneratorUsp_check_persistence << V >> {
  --
}

config.ftv_get_parameter_value <.. reference.additional_Reference_is_external
config.ftv_get_parameter_value <.. ssas.additional_Reference_step1
config.ftv_get_parameter_value <.. repo.RepoObject_external_src
config.Parameter <.. config.ftv_get_parameter_value
config.Parameter <.. property.PropertyName_RepoObject
configT.Parameter_default <.. config.Parameter
property.external_RepoObjectProperty <.. property.RepoObjectProperty_external_src
property.PropertyName_RepoObject <.. property.PropertyName_RepoObject_T
property.PropertyName_RepoObject_T <.. property.RepoObjectProperty_external_tgt
property.RepoObjectProperty <.. property.RepoObjectProperty_SelectedPropertyName_split
property.RepoObjectProperty <.. property.PropertyName_RepoObject
property.RepoObjectProperty_external_src <.. property.RepoObjectProperty_external_tgt
property.RepoObjectProperty_external_tgt <.. property.RepoObjectProperty
property.RepoObjectProperty_SelectedPropertyName_split <.. reference.additional_Reference_wo_columns_from_properties_src
property.RepoObjectProperty_SelectedPropertyName_split <.. reference.additional_Reference_from_properties_src
reference.additional_Reference <.. reference.additional_Reference_is_external
reference.additional_Reference_from_properties_src <.. reference.additional_Reference_from_properties_tgt
reference.additional_Reference_from_properties_tgt <.. reference.additional_Reference
reference.additional_Reference_from_ssas_src <.. reference.additional_Reference_from_ssas_tgt
reference.additional_Reference_from_ssas_tgt <.. reference.additional_Reference
reference.additional_Reference_is_external <.. reference.additional_Reference_Object
reference.additional_Reference_Object <.. reference.additional_Reference_Object_T
reference.additional_Reference_Object_T <.. repo.RepoObject_external_src
reference.additional_Reference_wo_columns_from_properties_src <.. reference.additional_Reference_wo_columns_from_properties_tgt
reference.additional_Reference_wo_columns_from_properties_tgt <.. reference.additional_Reference
repo.RepoObject <.. uspgenerator.GeneratorUsp_check_persistence
repo.RepoObject <.. property.RepoObjectProperty_external_tgt
repo.RepoObject <.. repo.RepoObject_external_src
repo.RepoObject_external_src <.. repo.RepoObject_external_tgt
repo.RepoObject_external_tgt <.. repo.RepoObject
repo.RepoObject_persistence <.. uspgenerator.GeneratorUsp_check_persistence
repo.RepoObject_SSAS_src <.. repo.RepoObject_SSAS_tgt
repo.RepoObject_SSAS_tgt <.. repo.RepoObject
repo.RepoSchema <.. repo.RepoObject_SSAS_src
repo.RepoSchema_ssas_src <.. repo.RepoSchema_ssas_tgt
repo.RepoSchema_ssas_tgt <.. repo.RepoSchema
ssas.additional_Reference_step1 <.. reference.additional_Reference_from_ssas_src
ssas.model_json <.. ssas.model_json_10
ssas.model_json_10 <.. ssas.model_json_20
ssas.model_json_20 <.. repo.RepoSchema_ssas_src
ssas.model_json_20 <.. ssas.model_json_31_tables
ssas.model_json_20 <.. ssas.model_json_33_dataSources
ssas.model_json_20 <.. ssas.model_json_201_descriptions_multiline
ssas.model_json_201_descriptions_multiline <.. ssas.model_json_2011_descriptions_StrAgg
ssas.model_json_2011_descriptions_StrAgg <.. repo.RepoSchema_ssas_src
ssas.model_json_31_tables <.. ssas.model_json_31_tables_T
ssas.model_json_31_tables_T <.. ssas.model_json_313_tables_partitions
ssas.model_json_31_tables_T <.. repo.RepoObject_SSAS_src
ssas.model_json_31_tables_T <.. ssas.model_json_311_tables_columns
ssas.model_json_311_tables_columns <.. ssas.model_json_311_tables_columns_T
ssas.model_json_311_tables_columns_T <.. ssas.additional_Reference_step1
ssas.model_json_313_tables_partitions <.. ssas.model_json_3131_tables_partitions_source
ssas.model_json_3131_tables_partitions_source <.. ssas.model_json_31311_tables_partitions_source_PosFrom
ssas.model_json_31311_tables_partitions_source_PosFrom <.. ssas.model_json_313111_tables_partitions_source_StringFrom
ssas.model_json_313111_tables_partitions_source_StringFrom <.. ssas.model_json_3131111_tables_partitions_source_PosDot
ssas.model_json_3131111_tables_partitions_source_PosDot <.. ssas.model_json_31311111_tables_partitions_source_Part123
ssas.model_json_31311111_tables_partitions_source_Part123 <.. ssas.additional_Reference_step1
ssas.model_json_33_dataSources <.. ssas.model_json_33_dataSources_T
ssas.model_json_33_dataSources_T <.. ssas.additional_Reference_step1
uspgenerator.GeneratorUsp <.. uspgenerator.GeneratorUsp_check_persistence

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_30_0_objectref[]

=== PlantUML 0 30 ObjectRef

// tag::puml_entity_0_30_objectref[]
[plantuml, entity_0_30_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:uspgenerator.generatorusp_check_persistence.adoc[]" as uspgenerator.GeneratorUsp_check_persistence << V >> {
  --
}



footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_0_30_objectref[]

=== PlantUML 1 1 ColumnRef

// tag::puml_entity_1_1_colref[]
[plantuml, entity_1_1_colref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:repo.repoobject.adoc[]" as repo.RepoObject << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  external_AntoraComponent : (nvarchar(128))
  external_AntoraModule : (nvarchar(128))
  has_execution_plan_issue : (bit)
  has_get_referenced_issue : (bit)
  indent_sql_modules_definition : (tinyint)
  Inheritance_Source_fullname : (nvarchar(261))
  Inheritance_StringAggSeparatorSql : (nvarchar(4000))
  InheritanceDefinition : (nvarchar(4000))
  InheritanceType : (tinyint)
  - is_DocsExclude : (bit)
  - is_external : (bit)
  is_repo_managed : (bit)
  is_required_ObjectMerge : (bit)
  - is_ssas : (bit)
  is_SysObject_missing : (bit)
  - modify_dt : (datetime)
  pk_index_guid : (uniqueidentifier)
  pk_IndexPatternColumnName_new : (nvarchar(4000))
  Repo_history_table_guid : (uniqueidentifier)
  Repo_temporal_type : (tinyint)
  - RepoObject_name : (nvarchar(128))
  RepoObject_Referencing_Count : (int)
  - RepoObject_schema_name : (nvarchar(128))
  - RepoObject_type : (char(2))
  SysObject_id : (int)
  SysObject_modify_date : (datetime)
  - SysObject_name : (nvarchar(128))
  - SysObject_parent_object_id : (int)
  - SysObject_schema_name : (nvarchar(128))
  SysObject_type : (char(2))
  ~ has_different_sys_names : (bit)
  # is_RepoObject_name_uniqueidentifier : (int)
  # is_SysObject_name_uniqueidentifier : (int)
  ~ node_id : (bigint)
  # RepoObject_fullname : (nvarchar(261))
  # RepoObject_fullname2 : (nvarchar(257))
  # SysObject_fullname : (nvarchar(261))
  # SysObject_fullname2 : (nvarchar(257))
  ~ SysObject_query_sql : (nvarchar(406))
  ~ usp_persistence_fullname : (nvarchar(273))
  # usp_persistence_fullname2 : (nvarchar(269))
  # usp_persistence_name : (nvarchar(140))
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_persistence.adoc[]" as repo.RepoObject_persistence << U >> {
  - **target_RepoObject_guid** : (uniqueidentifier)
  ColumnListIgnore : (nvarchar(4000))
  ColumnListNoCompareButUpdate : (nvarchar(4000))
  ColumnListNoCompareNoUpdate : (nvarchar(4000))
  ExecutionLogId_action : (char(1))
  final_target_RepoObject_name : (nvarchar(128))
  - has_history : (bit)
  - has_history_columns : (bit)
  history_schema_name : (nvarchar(128))
  history_table_name : (nvarchar(128))
  - is_persistence_check_duplicate_per_pk : (bit)
  - is_persistence_check_for_empty_source : (bit)
  - is_persistence_delete_changed : (bit)
  - is_persistence_delete_missing : (bit)
  - is_persistence_insert : (bit)
  - is_persistence_persist_source : (bit)
  - is_persistence_truncate : (bit)
  - is_persistence_update_changed : (bit)
  postscript : (nvarchar(max))
  prescript : (nvarchar(max))
  source_RepoObject_guid : (uniqueidentifier)
  source_RepoObject_name : (nvarchar(128))
  ~ is_persistence : (bit)
  ~ temporal_type : (tinyint)
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.generatorusp.adoc[]" as uspgenerator.GeneratorUsp << U >> {
  - **id** : (int)
  - has_logging : (tinyint)
  usp_Description : (nvarchar(4000))
  usp_Examples : (nvarchar(4000))
  - usp_name : (nvarchar(128))
  - usp_schema : (nvarchar(128))
  # usp_fullname : (nvarchar(261))
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.generatorusp_check_persistence.adoc[]" as uspgenerator.GeneratorUsp_check_persistence << V >> {
  ColumnListIgnore : (nvarchar(4000))
  ColumnListNoCompareButUpdate : (nvarchar(4000))
  ColumnListNoCompareNoUpdate : (nvarchar(4000))
  has_history : (bit)
  has_history_columns : (bit)
  - has_logging : (tinyint)
  history_schema_name : (nvarchar(128))
  history_table_name : (nvarchar(128))
  - id : (int)
  is_persistence : (bit)
  is_persistence_check_duplicate_per_pk : (bit)
  is_persistence_check_for_empty_source : (bit)
  is_persistence_delete_changed : (bit)
  is_persistence_delete_missing : (bit)
  is_persistence_insert : (bit)
  is_persistence_persist_source : (bit)
  is_persistence_truncate : (bit)
  is_persistence_update_changed : (bit)
  postscript : (nvarchar(max))
  prescript : (nvarchar(max))
  RepoObject_fullname : (nvarchar(261))
  RepoObject_guid : (uniqueidentifier)
  source_RepoObject_guid : (uniqueidentifier)
  source_RepoObject_name : (nvarchar(128))
  target_RepoObject_guid : (uniqueidentifier)
  temporal_type : (tinyint)
  usp_Description : (nvarchar(4000))
  usp_Examples : (nvarchar(4000))
  - usp_fullname : (nvarchar(261))
  - usp_name : (nvarchar(128))
  - usp_schema : (nvarchar(128))
  --
}

repo.RepoObject <.. uspgenerator.GeneratorUsp_check_persistence
repo.RepoObject_persistence <.. uspgenerator.GeneratorUsp_check_persistence
uspgenerator.GeneratorUsp <.. uspgenerator.GeneratorUsp_check_persistence
"repo.RepoObject::RepoObject_fullname" <-- "uspgenerator.GeneratorUsp_check_persistence::RepoObject_fullname"
"repo.RepoObject::RepoObject_guid" <-- "uspgenerator.GeneratorUsp_check_persistence::RepoObject_guid"
"repo.RepoObject_persistence::ColumnListIgnore" <-- "uspgenerator.GeneratorUsp_check_persistence::ColumnListIgnore"
"repo.RepoObject_persistence::ColumnListNoCompareButUpdate" <-- "uspgenerator.GeneratorUsp_check_persistence::ColumnListNoCompareButUpdate"
"repo.RepoObject_persistence::ColumnListNoCompareNoUpdate" <-- "uspgenerator.GeneratorUsp_check_persistence::ColumnListNoCompareNoUpdate"
"repo.RepoObject_persistence::has_history" <-- "uspgenerator.GeneratorUsp_check_persistence::has_history"
"repo.RepoObject_persistence::has_history_columns" <-- "uspgenerator.GeneratorUsp_check_persistence::has_history_columns"
"repo.RepoObject_persistence::history_schema_name" <-- "uspgenerator.GeneratorUsp_check_persistence::history_schema_name"
"repo.RepoObject_persistence::history_table_name" <-- "uspgenerator.GeneratorUsp_check_persistence::history_table_name"
"repo.RepoObject_persistence::is_persistence" <-- "uspgenerator.GeneratorUsp_check_persistence::is_persistence"
"repo.RepoObject_persistence::is_persistence_check_duplicate_per_pk" <-- "uspgenerator.GeneratorUsp_check_persistence::is_persistence_check_duplicate_per_pk"
"repo.RepoObject_persistence::is_persistence_check_for_empty_source" <-- "uspgenerator.GeneratorUsp_check_persistence::is_persistence_check_for_empty_source"
"repo.RepoObject_persistence::is_persistence_delete_changed" <-- "uspgenerator.GeneratorUsp_check_persistence::is_persistence_delete_changed"
"repo.RepoObject_persistence::is_persistence_delete_missing" <-- "uspgenerator.GeneratorUsp_check_persistence::is_persistence_delete_missing"
"repo.RepoObject_persistence::is_persistence_insert" <-- "uspgenerator.GeneratorUsp_check_persistence::is_persistence_insert"
"repo.RepoObject_persistence::is_persistence_persist_source" <-- "uspgenerator.GeneratorUsp_check_persistence::is_persistence_persist_source"
"repo.RepoObject_persistence::is_persistence_truncate" <-- "uspgenerator.GeneratorUsp_check_persistence::is_persistence_truncate"
"repo.RepoObject_persistence::is_persistence_update_changed" <-- "uspgenerator.GeneratorUsp_check_persistence::is_persistence_update_changed"
"repo.RepoObject_persistence::postscript" <-- "uspgenerator.GeneratorUsp_check_persistence::postscript"
"repo.RepoObject_persistence::prescript" <-- "uspgenerator.GeneratorUsp_check_persistence::prescript"
"repo.RepoObject_persistence::source_RepoObject_guid" <-- "uspgenerator.GeneratorUsp_check_persistence::source_RepoObject_guid"
"repo.RepoObject_persistence::source_RepoObject_name" <-- "uspgenerator.GeneratorUsp_check_persistence::source_RepoObject_name"
"repo.RepoObject_persistence::target_RepoObject_guid" <-- "uspgenerator.GeneratorUsp_check_persistence::target_RepoObject_guid"
"repo.RepoObject_persistence::temporal_type" <-- "uspgenerator.GeneratorUsp_check_persistence::temporal_type"
"uspgenerator.GeneratorUsp::has_logging" <-- "uspgenerator.GeneratorUsp_check_persistence::has_logging"
"uspgenerator.GeneratorUsp::id" <-- "uspgenerator.GeneratorUsp_check_persistence::id"
"uspgenerator.GeneratorUsp::usp_Description" <-- "uspgenerator.GeneratorUsp_check_persistence::usp_Description"
"uspgenerator.GeneratorUsp::usp_Examples" <-- "uspgenerator.GeneratorUsp_check_persistence::usp_Examples"
"uspgenerator.GeneratorUsp::usp_fullname" <-- "uspgenerator.GeneratorUsp_check_persistence::usp_fullname"
"uspgenerator.GeneratorUsp::usp_name" <-- "uspgenerator.GeneratorUsp_check_persistence::usp_name"
"uspgenerator.GeneratorUsp::usp_schema" <-- "uspgenerator.GeneratorUsp_check_persistence::usp_schema"

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_colref[]


== sql_modules_definition

// tag::sql_modules_definition[]
[%collapsible]
=======
[source,sql,numbered,indent=0]
----

/*
<<property_start>>Description
Sometimes it can happen that a persistence was created with the Persistence Generator and still exists in xref:sqldb:uspgenerator.generatorusp.adoc[], 
although the persistence has already been removed from xref:sqldb:repo.repoobject_persistence.adoc[].

This view helps to identify such entries and then remove such legacy entries from xref:sqldb:uspgenerator.generatorusp.adoc[]

If the last columns of the xref:sqldb:uspgenerator.generatorusp_check_persistence.adoc[] view have the value NULL, then there is no persistence anymore. The corresponding entries can then be removed from xref:sqldb:uspgenerator.generatorusp.adoc[] after careful checking.
<<property_end>>
*/
CREATE View uspgenerator.GeneratorUsp_check_persistence
As
Select
    T1.id
  , T1.usp_schema
  , T1.usp_name
  , T1.has_logging
  , T1.usp_Description
  , T1.usp_Examples
  , T1.usp_fullname
  , T2.RepoObject_guid
  , T2.RepoObject_fullname
  , T3.target_RepoObject_guid
  , T3.has_history
  , T3.has_history_columns
  , T3.history_schema_name
  , T3.history_table_name
  , T3.is_persistence_check_duplicate_per_pk
  , T3.is_persistence_check_for_empty_source
  , T3.is_persistence_delete_changed
  , T3.is_persistence_delete_missing
  , T3.is_persistence_insert
  , T3.is_persistence_truncate
  , T3.is_persistence_update_changed
  , T3.is_persistence_persist_source
  --, T3.is_persistence_merge_delete_missing
  --, T3.is_persistence_merge_insert
  --, T3.is_persistence_merge_update_changed
  , T3.[ColumnListNoCompareButUpdate]
  , T3.[ColumnListNoCompareNoUpdate]
  , T3.ColumnListIgnore
  , T3.prescript
  , T3.postscript
  , T3.source_RepoObject_guid
  , T3.source_RepoObject_name
  , T3.is_persistence
  , T3.temporal_type
From
    uspgenerator.GeneratorUsp       As T1
    Left Outer Join
        repo.RepoObject             As T2
            On
            T2.usp_persistence_fullname = T1.usp_fullname

    Left Outer Join
        repo.RepoObject_persistence As T3
            On
            T3.target_RepoObject_guid   = T2.RepoObject_guid
Where
    ( Left(T1.usp_name, 12) = 'usp_PERSIST_' )
----
=======
// end::sql_modules_definition[]


