// tag::HeaderFullDisplayName[]
= uspgenerator.GeneratorUspStep - U
// end::HeaderFullDisplayName[]

== existing_properties

// tag::existing_properties[]

:ExistsProperty--antorareferencinglist:
:ExistsProperty--is_repo_managed:
:ExistsProperty--is_ssas:
:ExistsProperty--pk_index_guid:
:ExistsProperty--pk_indexpatterncolumndatatype:
:ExistsProperty--pk_indexpatterncolumnname:
:ExistsProperty--FK:
:ExistsProperty--AntoraIndexList:
:ExistsProperty--Columns:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
5690291C-9D61-EB11-84DC-A81E8446D5B0
// end::RepoObject_guid[]

== RepoObject_FullDisplayName2

// tag::RepoObject_FullDisplayName2[]
uspgenerator.GeneratorUspStep
// end::RepoObject_FullDisplayName2[]

== SysObject_type

// tag::SysObject_type[]
U 
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
user table
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
1355203928
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2022-06-30 17:32:52
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]
[discrete]
== _


[#column-id]
=== id

[cols="d,8a,m,m,m"]
|===
|1
|*id*
|int
|NOT NULL
|(1,1)
|===


[#column-description]
=== Description

[cols="d,8a,m,m,m"]
|===
|
|Description
|nvarchar(4000)
|NULL
|
|===


[#column-hasunderlinelogging]
=== has_logging

[cols="d,8a,m,m,m"]
|===
|
|has_logging

.Default: DF_GeneratorUspStep_has_logging
[source,sql]
----
((1))
----


|tinyint
|NOT NULL
|
|===


[#column-infounderline01]
=== info_01

[cols="d,8a,m,m,m"]
|===
|
|info_01
|nvarchar(max)
|NULL
|
|===


[#column-infounderline02]
=== info_02

[cols="d,8a,m,m,m"]
|===
|
|info_02
|nvarchar(max)
|NULL
|
|===


[#column-infounderline03]
=== info_03

[cols="d,8a,m,m,m"]
|===
|
|info_03
|nvarchar(max)
|NULL
|
|===


[#column-infounderline04]
=== info_04

[cols="d,8a,m,m,m"]
|===
|
|info_04
|nvarchar(max)
|NULL
|
|===


[#column-infounderline05]
=== info_05

[cols="d,8a,m,m,m"]
|===
|
|info_05
|nvarchar(max)
|NULL
|
|===


[#column-infounderline06]
=== info_06

[cols="d,8a,m,m,m"]
|===
|
|info_06
|nvarchar(max)
|NULL
|
|===


[#column-infounderline07]
=== info_07

[cols="d,8a,m,m,m"]
|===
|
|info_07
|nvarchar(max)
|NULL
|
|===


[#column-infounderline08]
=== info_08

[cols="d,8a,m,m,m"]
|===
|
|info_08
|nvarchar(max)
|NULL
|
|===


[#column-infounderline09]
=== info_09

[cols="d,8a,m,m,m"]
|===
|
|info_09
|nvarchar(max)
|NULL
|
|===


[#column-isunderlinecondition]
=== is_condition

[cols="d,8a,m,m,m"]
|===
|
|is_condition

.Default: DF_GeneratorUspStep_is_condition
[source,sql]
----
((0))
----


|tinyint
|NOT NULL
|
|===


[#column-isunderlineinactive]
=== is_inactive

[cols="d,8a,m,m,m"]
|===
|
|is_inactive

.Default: DF_GeneratorUspStep_is_inactive
[source,sql]
----
((0))
----


|tinyint
|NOT NULL
|
|===


[#column-isunderlinesubprocedure]
=== is_SubProcedure

[cols="d,8a,m,m,m"]
|===
|
|is_SubProcedure

.Default: DF_GeneratorUspStep_is_SubProcedure
[source,sql]
----
((0))
----


|tinyint
|NOT NULL
|
|===


[#column-logunderlineflagunderlineinsertupdatedelete]
=== log_flag_InsertUpdateDelete

[cols="d,8a,m,m,m"]
|===
|
|log_flag_InsertUpdateDelete
|char(1)
|NULL
|
|===


[#column-logunderlinesourceunderlineobject]
=== log_source_object

[cols="d,8a,m,m,m"]
|===
|
|log_source_object
|nvarchar(261)
|NULL
|
|===


[#column-logunderlinetargetunderlineobject]
=== log_target_object

[cols="d,8a,m,m,m"]
|===
|
|log_target_object
|nvarchar(261)
|NULL
|
|===


[#column-name]
=== Name

[cols="d,8a,m,m,m"]
|===
|
|Name
|nvarchar(1000)
|NULL
|
|===


[#column-number]
=== Number

[cols="d,8a,m,m,m"]
|===
|
|Number
|int
|NOT NULL
|
|===


[#column-parentunderlinenumber]
=== Parent_Number

[cols="d,8a,m,m,m"]
|===
|
|Parent_Number
|int
|NULL
|
|===


[#column-statement]
=== Statement

[cols="d,8a,m,m,m"]
|===
|
|Statement
|nvarchar(max)
|NULL
|
|===


[#column-uspunderlineid]
=== usp_id

[cols="d,8a,m,m,m"]
|===
|
|usp_id
|int
|NOT NULL
|
|===


// end::AntoraColumnDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]
|1
|*<<column-id>>*
|int
|NOT NULL
|(1,1)























// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]

|
|<<column-description>>
|nvarchar(4000)
|NULL
|

|
|<<column-hasunderlinelogging>>

.Default: DF_GeneratorUspStep_has_logging
[source,sql]
----
((1))
----


|tinyint
|NOT NULL
|

|
|<<column-infounderline01>>
|nvarchar(max)
|NULL
|

|
|<<column-infounderline02>>
|nvarchar(max)
|NULL
|

|
|<<column-infounderline03>>
|nvarchar(max)
|NULL
|

|
|<<column-infounderline04>>
|nvarchar(max)
|NULL
|

|
|<<column-infounderline05>>
|nvarchar(max)
|NULL
|

|
|<<column-infounderline06>>
|nvarchar(max)
|NULL
|

|
|<<column-infounderline07>>
|nvarchar(max)
|NULL
|

|
|<<column-infounderline08>>
|nvarchar(max)
|NULL
|

|
|<<column-infounderline09>>
|nvarchar(max)
|NULL
|

|
|<<column-isunderlinecondition>>

.Default: DF_GeneratorUspStep_is_condition
[source,sql]
----
((0))
----


|tinyint
|NOT NULL
|

|
|<<column-isunderlineinactive>>

.Default: DF_GeneratorUspStep_is_inactive
[source,sql]
----
((0))
----


|tinyint
|NOT NULL
|

|
|<<column-isunderlinesubprocedure>>

.Default: DF_GeneratorUspStep_is_SubProcedure
[source,sql]
----
((0))
----


|tinyint
|NOT NULL
|

|
|<<column-logunderlineflagunderlineinsertupdatedelete>>
|char(1)
|NULL
|

|
|<<column-logunderlinesourceunderlineobject>>
|nvarchar(261)
|NULL
|

|
|<<column-logunderlinetargetunderlineobject>>
|nvarchar(261)
|NULL
|

|
|<<column-name>>
|nvarchar(1000)
|NULL
|

|
|<<column-number>>
|int
|NOT NULL
|

|
|<<column-parentunderlinenumber>>
|int
|NULL
|

|
|<<column-statement>>
|nvarchar(max)
|NULL
|

|
|<<column-uspunderlineid>>
|int
|NOT NULL
|

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

[#index-pkunderlinegeneratoruspstep]
=== PK_GeneratorUspStep

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-id>>; int
--
* PK, Unique, Real: 1, 1, 1


[#index-ukunderlinegeneratoruspstepunderlinenumber]
=== UK_GeneratorUspStep_Number

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-usp_id>>; int
* <<column-Number>>; int
--
* PK, Unique, Real: 0, 1, 1


[#index-idxunderlinegeneratoruspstepunderlineunderline1]
=== idx_GeneratorUspStep++__++1

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-usp_id>>; int
--
* PK, Unique, Real: 0, 0, 0
* ++FK_GeneratorUspStep_GeneratorUsp++ +
referenced: xref:uspgenerator.generatorusp.adoc[], xref:uspgenerator.generatorusp.adoc#index-pkunderlinegeneratorusp[+PK_GeneratorUsp+]
* is disabled

// end::AntoraIndexList[]

== AntoraMeasureDetails

// tag::AntoraMeasureDetails[]

// end::AntoraMeasureDetails[]

== AntoraMeasureDescriptions



== AntoraParameterList

// tag::AntoraParameterList[]

// end::AntoraParameterList[]

== AntoraXrefCulturesList

// tag::AntoraXrefCulturesList[]
* xref:dhw:sqldb:uspgenerator.generatoruspstep.adoc[] - 
// end::AntoraXrefCulturesList[]

== cultures_count

// tag::cultures_count[]
1
// end::cultures_count[]

== Other tags

source: property.RepoObjectProperty_cross As rop_cross


=== additional_reference_csv

// tag::additional_reference_csv[]

// end::additional_reference_csv[]


=== AdocUspSteps

// tag::adocuspsteps[]

// end::adocuspsteps[]


=== AntoraReferencedList

// tag::antorareferencedlist[]

// end::antorareferencedlist[]


=== AntoraReferencingList

// tag::antorareferencinglist[]
* xref:dhw:sqldb:uspgenerator.ftv_generatoruspstep_sql.adoc[]
* xref:dhw:sqldb:uspgenerator.ftv_generatoruspstep_tree.adoc[]
* xref:dhw:sqldb:uspgenerator.generatoruspstep_sql.adoc[]
* xref:dhw:sqldb:uspgenerator.usp_copy_procedure.adoc[]
* xref:dhw:sqldb:uspgenerator.usp_generatorusp_insert_update_persistence.adoc[]
// end::antorareferencinglist[]


=== Description

// tag::description[]

// end::description[]


=== exampleUsage

// tag::exampleusage[]

// end::exampleusage[]


=== exampleUsage_2

// tag::exampleusage_2[]

// end::exampleusage_2[]


=== exampleUsage_3

// tag::exampleusage_3[]

// end::exampleusage_3[]


=== exampleUsage_4

// tag::exampleusage_4[]

// end::exampleusage_4[]


=== exampleUsage_5

// tag::exampleusage_5[]

// end::exampleusage_5[]


=== exampleWrong_Usage

// tag::examplewrong_usage[]

// end::examplewrong_usage[]


=== has_execution_plan_issue

// tag::has_execution_plan_issue[]

// end::has_execution_plan_issue[]


=== has_get_referenced_issue

// tag::has_get_referenced_issue[]

// end::has_get_referenced_issue[]


=== has_history

// tag::has_history[]

// end::has_history[]


=== has_history_columns

// tag::has_history_columns[]

// end::has_history_columns[]


=== InheritanceType

// tag::inheritancetype[]

// end::inheritancetype[]


=== is_persistence

// tag::is_persistence[]

// end::is_persistence[]


=== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]

// end::is_persistence_check_duplicate_per_pk[]


=== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]

// end::is_persistence_check_for_empty_source[]


=== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]

// end::is_persistence_delete_changed[]


=== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]

// end::is_persistence_delete_missing[]


=== is_persistence_insert

// tag::is_persistence_insert[]

// end::is_persistence_insert[]


=== is_persistence_truncate

// tag::is_persistence_truncate[]

// end::is_persistence_truncate[]


=== is_persistence_update_changed

// tag::is_persistence_update_changed[]

// end::is_persistence_update_changed[]


=== is_repo_managed

// tag::is_repo_managed[]
0
// end::is_repo_managed[]


=== is_ssas

// tag::is_ssas[]
0
// end::is_ssas[]


=== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


=== MS_Description

// tag::ms_description[]

// end::ms_description[]


=== persistence_source_RepoObject_fullname

// tag::persistence_source_repoobject_fullname[]

// end::persistence_source_repoobject_fullname[]


=== persistence_source_RepoObject_fullname2

// tag::persistence_source_repoobject_fullname2[]

// end::persistence_source_repoobject_fullname2[]


=== persistence_source_RepoObject_guid

// tag::persistence_source_repoobject_guid[]

// end::persistence_source_repoobject_guid[]


=== persistence_source_RepoObject_xref

// tag::persistence_source_repoobject_xref[]

// end::persistence_source_repoobject_xref[]


=== pk_index_guid

// tag::pk_index_guid[]
5890291C-9D61-EB11-84DC-A81E8446D5B0
// end::pk_index_guid[]


=== pk_IndexPatternColumnDatatype

// tag::pk_indexpatterncolumndatatype[]
int
// end::pk_indexpatterncolumndatatype[]


=== pk_IndexPatternColumnName

// tag::pk_indexpatterncolumnname[]
id
// end::pk_indexpatterncolumnname[]


=== pk_IndexSemanticGroup

// tag::pk_indexsemanticgroup[]

// end::pk_indexsemanticgroup[]


=== ReferencedObjectList

// tag::referencedobjectlist[]

// end::referencedobjectlist[]


=== usp_persistence_RepoObject_guid

// tag::usp_persistence_repoobject_guid[]

// end::usp_persistence_repoobject_guid[]


=== UspExamples

// tag::uspexamples[]

// end::uspexamples[]


=== uspgenerator_usp_id

// tag::uspgenerator_usp_id[]

// end::uspgenerator_usp_id[]


=== UspParameters

// tag::uspparameters[]

// end::uspparameters[]

== Boolean Attributes

source: property.RepoObjectProperty WHERE property_int = 1

// tag::boolean_attributes[]


// end::boolean_attributes[]

== PlantUML diagrams

=== PlantUML Entity

// tag::puml_entity[]
[plantuml, entity-{docname}, svg, subs=macros]
....
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:uspgenerator.generatoruspstep.adoc[]" as uspgenerator.GeneratorUspStep << U >> {
  - **id** : (int)
  Description : (nvarchar(4000))
  - has_logging : (tinyint)
  info_01 : (nvarchar(max))
  info_02 : (nvarchar(max))
  info_03 : (nvarchar(max))
  info_04 : (nvarchar(max))
  info_05 : (nvarchar(max))
  info_06 : (nvarchar(max))
  info_07 : (nvarchar(max))
  info_08 : (nvarchar(max))
  info_09 : (nvarchar(max))
  - is_condition : (tinyint)
  - is_inactive : (tinyint)
  - is_SubProcedure : (tinyint)
  log_flag_InsertUpdateDelete : (char(1))
  log_source_object : (nvarchar(261))
  log_target_object : (nvarchar(261))
  Name : (nvarchar(1000))
  - Number : (int)
  Parent_Number : (int)
  Statement : (nvarchar(max))
  - usp_id : (int)
  --
}
....

// end::puml_entity[]

=== PlantUML Entity 1 1 FK

// tag::puml_entity_1_1_fk[]
[plantuml, entity_1_1_fk-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:uspgenerator.generatorusp.adoc[]" as uspgenerator.GeneratorUsp << U >> {
**PK_GeneratorUsp**

..
id; int
--
UK_GeneratorUsp_Schema_Name

..
usp_schema; nvarchar(128)
usp_name; nvarchar(128)
}

entity "puml-link:dhw:sqldb:uspgenerator.generatoruspstep.adoc[]" as uspgenerator.GeneratorUspStep << U >> {
**PK_GeneratorUspStep**

..
id; int
--
UK_GeneratorUspStep_Number

..
usp_id; int
Number; int
--
- idx_GeneratorUspStep__1

..
usp_id; int
}

"uspgenerator.GeneratorUsp::PK_GeneratorUsp" <-- "uspgenerator.GeneratorUspStep::idx_GeneratorUspStep__1"

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_fk[]

=== PlantUML 1 1 ObjectRef

// tag::puml_entity_1_1_objectref[]
[plantuml, entity_1_1_objectref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:uspgenerator.ftv_generatoruspstep_sql.adoc[]" as uspgenerator.ftv_GeneratorUspStep_sql << IF >> {
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.ftv_generatoruspstep_tree.adoc[]" as uspgenerator.ftv_GeneratorUspStep_tree << IF >> {
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.generatoruspstep.adoc[]" as uspgenerator.GeneratorUspStep << U >> {
  - **id** : (int)
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.generatoruspstep_sql.adoc[]" as uspgenerator.GeneratorUspStep_Sql << V >> {
  - **usp_id** : (int)
  **Number** : (int)
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.usp_copy_procedure.adoc[]" as uspgenerator.usp_copy_procedure << P >> {
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.usp_generatorusp_insert_update_persistence.adoc[]" as uspgenerator.usp_GeneratorUsp_insert_update_persistence << P >> {
  --
}

uspgenerator.GeneratorUspStep <.. uspgenerator.ftv_GeneratorUspStep_sql
uspgenerator.GeneratorUspStep <.. uspgenerator.ftv_GeneratorUspStep_tree
uspgenerator.GeneratorUspStep <.. uspgenerator.GeneratorUspStep_Sql
uspgenerator.GeneratorUspStep <.. uspgenerator.usp_copy_procedure
uspgenerator.GeneratorUspStep <.. uspgenerator.usp_GeneratorUsp_insert_update_persistence

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_objectref[]

=== PlantUML 30 0 ObjectRef

// tag::puml_entity_30_0_objectref[]
[plantuml, entity_30_0_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:uspgenerator.generatoruspstep.adoc[]" as uspgenerator.GeneratorUspStep << U >> {
  - **id** : (int)
  --
}



footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_30_0_objectref[]

=== PlantUML 0 30 ObjectRef

// tag::puml_entity_0_30_objectref[]
[plantuml, entity_0_30_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:property.repoobjectproperty_collect_source_uspgenerator.adoc[]" as property.RepoObjectProperty_Collect_source_uspgenerator << V >> {
  **RepoObject_guid** : (uniqueidentifier)
  - **property_name** : (varchar(14))
  --
}

entity "puml-link:dhw:sqldb:property.usp_repoobject_inheritance.adoc[]" as property.usp_RepoObject_Inheritance << P >> {
  --
}

entity "puml-link:dhw:sqldb:property.usp_repoobjectproperty_collect.adoc[]" as property.usp_RepoObjectProperty_collect << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_main.adoc[]" as repo.usp_main << P >> {
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.ftv_generatoruspstep_sql.adoc[]" as uspgenerator.ftv_GeneratorUspStep_sql << IF >> {
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.ftv_generatoruspstep_tree.adoc[]" as uspgenerator.ftv_GeneratorUspStep_tree << IF >> {
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.generatorusp_sqlusp.adoc[]" as uspgenerator.GeneratorUsp_SqlUsp << V >> {
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.generatorusp_sqlusp_wo_go.adoc[]" as uspgenerator.GeneratorUsp_SqlUsp_wo_GO << V >> {
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.generatorusp_steplist.adoc[]" as uspgenerator.GeneratorUsp_StepList << V >> {
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.generatoruspstep.adoc[]" as uspgenerator.GeneratorUspStep << U >> {
  - **id** : (int)
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.generatoruspstep_sql.adoc[]" as uspgenerator.GeneratorUspStep_Sql << V >> {
  - **usp_id** : (int)
  **Number** : (int)
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.usp_copy_procedure.adoc[]" as uspgenerator.usp_copy_procedure << P >> {
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.usp_generatorusp_insert_update_persistence.adoc[]" as uspgenerator.usp_GeneratorUsp_insert_update_persistence << P >> {
  --
}

property.RepoObjectProperty_Collect_source_uspgenerator <.. property.usp_RepoObjectProperty_collect
property.usp_RepoObject_Inheritance <.. repo.usp_main
property.usp_RepoObjectProperty_collect <.. property.usp_RepoObject_Inheritance
property.usp_RepoObjectProperty_collect <.. repo.usp_main
uspgenerator.ftv_GeneratorUspStep_sql <.. uspgenerator.GeneratorUspStep_Sql
uspgenerator.ftv_GeneratorUspStep_tree <.. uspgenerator.GeneratorUspStep_Sql
uspgenerator.GeneratorUsp_SqlUsp <.. property.RepoObjectProperty_Collect_source_uspgenerator
uspgenerator.GeneratorUsp_StepList <.. uspgenerator.GeneratorUsp_SqlUsp
uspgenerator.GeneratorUsp_StepList <.. uspgenerator.GeneratorUsp_SqlUsp_wo_GO
uspgenerator.GeneratorUspStep <.. uspgenerator.ftv_GeneratorUspStep_sql
uspgenerator.GeneratorUspStep <.. uspgenerator.ftv_GeneratorUspStep_tree
uspgenerator.GeneratorUspStep <.. uspgenerator.GeneratorUspStep_Sql
uspgenerator.GeneratorUspStep <.. uspgenerator.usp_copy_procedure
uspgenerator.GeneratorUspStep <.. uspgenerator.usp_GeneratorUsp_insert_update_persistence
uspgenerator.GeneratorUspStep_Sql <.. uspgenerator.GeneratorUsp_StepList
uspgenerator.usp_GeneratorUsp_insert_update_persistence <.. repo.usp_main

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_0_30_objectref[]

=== PlantUML 1 1 ColumnRef

// tag::puml_entity_1_1_colref[]
[plantuml, entity_1_1_colref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:uspgenerator.ftv_generatoruspstep_sql.adoc[]" as uspgenerator.ftv_GeneratorUspStep_sql << IF >> {
  - Number : (int)
  - SqlStep : (nvarchar(max))
  Statement : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.ftv_generatoruspstep_tree.adoc[]" as uspgenerator.ftv_GeneratorUspStep_tree << IF >> {
  Asc_PerParentChild : (bigint)
  child_PerParent : (bigint)
  Depth : (int)
  Desc_PerParentChild : (bigint)
  is_condition : (tinyint)
  - is_required_ELSE : (int)
  Number : (int)
  Parent_Number : (int)
  Parent_Sort : (int)
  Root_Sort : (int)
  RowNumber_PerUsp : (bigint)
  Sort : (int)
  usp_id : (int)
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.generatoruspstep.adoc[]" as uspgenerator.GeneratorUspStep << U >> {
  - **id** : (int)
  Description : (nvarchar(4000))
  - has_logging : (tinyint)
  info_01 : (nvarchar(max))
  info_02 : (nvarchar(max))
  info_03 : (nvarchar(max))
  info_04 : (nvarchar(max))
  info_05 : (nvarchar(max))
  info_06 : (nvarchar(max))
  info_07 : (nvarchar(max))
  info_08 : (nvarchar(max))
  info_09 : (nvarchar(max))
  - is_condition : (tinyint)
  - is_inactive : (tinyint)
  - is_SubProcedure : (tinyint)
  log_flag_InsertUpdateDelete : (char(1))
  log_source_object : (nvarchar(261))
  log_target_object : (nvarchar(261))
  Name : (nvarchar(1000))
  - Number : (int)
  Parent_Number : (int)
  Statement : (nvarchar(max))
  - usp_id : (int)
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.generatoruspstep_sql.adoc[]" as uspgenerator.GeneratorUspStep_Sql << V >> {
  - **usp_id** : (int)
  **Number** : (int)
  - AdocStep : (nvarchar(max))
  - has_logging : (tinyint)
  is_required_ELSE : (int)
  required_Begin_count : (int)
  required_End_count : (int)
  RowNumber_PerUsp : (bigint)
  - SqlStep : (nvarchar(max))
  - usp_fullname : (nvarchar(261))
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.usp_copy_procedure.adoc[]" as uspgenerator.usp_copy_procedure << P >> {
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.usp_generatorusp_insert_update_persistence.adoc[]" as uspgenerator.usp_GeneratorUsp_insert_update_persistence << P >> {
  --
}

uspgenerator.GeneratorUspStep <.. uspgenerator.ftv_GeneratorUspStep_sql
uspgenerator.GeneratorUspStep <.. uspgenerator.ftv_GeneratorUspStep_tree
uspgenerator.GeneratorUspStep <.. uspgenerator.GeneratorUspStep_Sql
uspgenerator.GeneratorUspStep <.. uspgenerator.usp_copy_procedure
uspgenerator.GeneratorUspStep <.. uspgenerator.usp_GeneratorUsp_insert_update_persistence


footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_colref[]


== sql_modules_definition

// tag::sql_modules_definition[]
[%collapsible]
=======
[source,sql,numbered,indent=0]
----

----
=======
// end::sql_modules_definition[]


