// tag::HeaderFullDisplayName[]
= uspgenerator.GeneratorUspStep_Sql - V
// end::HeaderFullDisplayName[]

== existing_properties

// tag::existing_properties[]

:ExistsProperty--antorareferencedlist:
:ExistsProperty--antorareferencinglist:
:ExistsProperty--has_execution_plan_issue:
:ExistsProperty--is_repo_managed:
:ExistsProperty--is_ssas:
:ExistsProperty--pk_index_guid:
:ExistsProperty--pk_indexpatterncolumndatatype:
:ExistsProperty--pk_indexpatterncolumnname:
:ExistsProperty--referencedobjectlist:
:ExistsProperty--sql_modules_definition:
:ExistsProperty--FK:
:ExistsProperty--AntoraIndexList:
:ExistsProperty--Columns:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
4590291C-9D61-EB11-84DC-A81E8446D5B0
// end::RepoObject_guid[]

== RepoObject_FullDisplayName2

// tag::RepoObject_FullDisplayName2[]
uspgenerator.GeneratorUspStep_Sql
// end::RepoObject_FullDisplayName2[]

== SysObject_type

// tag::SysObject_type[]
V 
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
view
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
1010102639
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2021-11-03 19:26:04
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]
[discrete]
== _


[#column-uspunderlineid]
=== usp_id

[cols="d,8a,m,m,m"]
|===
|1
|*usp_id*
|int
|NOT NULL
|
|===

.Referenced Columns
--
* xref:uspgenerator.generatorusp.adoc#column-id[+uspgenerator.GeneratorUsp.id+]
--

.Referencing Columns
--
* xref:uspgenerator.generatorusp_steplist.adoc#column-uspunderlineid[+uspgenerator.GeneratorUsp_StepList.usp_id+]
--


[#column-number]
=== Number

[cols="d,8a,m,m,m"]
|===
|2
|*Number*
|int
|NULL
|
|===


[#column-adocstep]
=== AdocStep

[cols="d,8a,m,m,m"]
|===
|
|AdocStep
|nvarchar(max)
|NOT NULL
|
|===


[#column-hasunderlinelogging]
=== has_logging

[cols="d,8a,m,m,m"]
|===
|
|has_logging
|tinyint
|NOT NULL
|
|===

.Referenced Columns
--
* xref:uspgenerator.generatorusp.adoc#column-hasunderlinelogging[+uspgenerator.GeneratorUsp.has_logging+]
--


[#column-isunderlinerequiredunderlineelse]
=== is_required_ELSE

[cols="d,8a,m,m,m"]
|===
|
|is_required_ELSE
|int
|NULL
|
|===


[#column-requiredunderlinebeginunderlinecount]
=== required_Begin_count

[cols="d,8a,m,m,m"]
|===
|
|required_Begin_count
|int
|NULL
|
|===


[#column-requiredunderlineendunderlinecount]
=== required_End_count

[cols="d,8a,m,m,m"]
|===
|
|required_End_count
|int
|NULL
|
|===


[#column-rownumberunderlineperusp]
=== RowNumber_PerUsp

[cols="d,8a,m,m,m"]
|===
|
|RowNumber_PerUsp
|bigint
|NULL
|
|===


[#column-sqlstep]
=== SqlStep

[cols="d,8a,m,m,m"]
|===
|
|SqlStep
|nvarchar(max)
|NOT NULL
|
|===


[#column-uspunderlinefullname]
=== usp_fullname

[cols="d,8a,m,m,m"]
|===
|
|usp_fullname
|nvarchar(261)
|NOT NULL
|
|===

.Description
--
(concat('[',[usp_schema],'].[',[usp_name],']'))
--
{empty} +

.Referenced Columns
--
* xref:uspgenerator.generatorusp.adoc#column-uspunderlinefullname[+uspgenerator.GeneratorUsp.usp_fullname+]
--


// end::AntoraColumnDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]
|1
|*<<column-uspunderlineid>>*
|int
|NOT NULL
|

|2
|*<<column-number>>*
|int
|NULL
|









// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]


|
|<<column-adocstep>>
|nvarchar(max)
|NOT NULL
|

|
|<<column-hasunderlinelogging>>
|tinyint
|NOT NULL
|

|
|<<column-isunderlinerequiredunderlineelse>>
|int
|NULL
|

|
|<<column-requiredunderlinebeginunderlinecount>>
|int
|NULL
|

|
|<<column-requiredunderlineendunderlinecount>>
|int
|NULL
|

|
|<<column-rownumberunderlineperusp>>
|bigint
|NULL
|

|
|<<column-sqlstep>>
|nvarchar(max)
|NOT NULL
|

|
|<<column-uspunderlinefullname>>
|nvarchar(261)
|NOT NULL
|

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

[#index-pkunderlinegeneratoruspstepunderlinesql]
=== PK_GeneratorUspStep_Sql

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-usp_id>>; int
* <<column-Number>>; int
--
* PK, Unique, Real: 1, 1, 0


[#index-idxunderlinegeneratoruspstepunderlinesqlunderlineunderline2]
=== idx_GeneratorUspStep_Sql++__++2

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-usp_id>>; int
--
* PK, Unique, Real: 0, 0, 0

// end::AntoraIndexList[]

== AntoraMeasureDetails

// tag::AntoraMeasureDetails[]

// end::AntoraMeasureDetails[]

== AntoraMeasureDescriptions



== AntoraParameterList

// tag::AntoraParameterList[]

// end::AntoraParameterList[]

== AntoraXrefCulturesList

// tag::AntoraXrefCulturesList[]
* xref:dhw:sqldb:uspgenerator.generatoruspstep_sql.adoc[] - 
// end::AntoraXrefCulturesList[]

== cultures_count

// tag::cultures_count[]
1
// end::cultures_count[]

== Other tags

source: property.RepoObjectProperty_cross As rop_cross


=== additional_reference_csv

// tag::additional_reference_csv[]

// end::additional_reference_csv[]


=== AdocUspSteps

// tag::adocuspsteps[]

// end::adocuspsteps[]


=== AntoraReferencedList

// tag::antorareferencedlist[]
* xref:dhw:sqldb:uspgenerator.ftv_generatoruspstep_sql.adoc[]
* xref:dhw:sqldb:uspgenerator.ftv_generatoruspstep_tree.adoc[]
* xref:dhw:sqldb:uspgenerator.generatorusp.adoc[]
* xref:dhw:sqldb:uspgenerator.generatoruspstep.adoc[]
// end::antorareferencedlist[]


=== AntoraReferencingList

// tag::antorareferencinglist[]
* xref:dhw:sqldb:uspgenerator.generatorusp_steplist.adoc[]
// end::antorareferencinglist[]


=== Description

// tag::description[]

// end::description[]


=== exampleUsage

// tag::exampleusage[]

// end::exampleusage[]


=== exampleUsage_2

// tag::exampleusage_2[]

// end::exampleusage_2[]


=== exampleUsage_3

// tag::exampleusage_3[]

// end::exampleusage_3[]


=== exampleUsage_4

// tag::exampleusage_4[]

// end::exampleusage_4[]


=== exampleUsage_5

// tag::exampleusage_5[]

// end::exampleusage_5[]


=== exampleWrong_Usage

// tag::examplewrong_usage[]

// end::examplewrong_usage[]


=== has_execution_plan_issue

// tag::has_execution_plan_issue[]
1
// end::has_execution_plan_issue[]


=== has_get_referenced_issue

// tag::has_get_referenced_issue[]

// end::has_get_referenced_issue[]


=== has_history

// tag::has_history[]

// end::has_history[]


=== has_history_columns

// tag::has_history_columns[]

// end::has_history_columns[]


=== InheritanceType

// tag::inheritancetype[]

// end::inheritancetype[]


=== is_persistence

// tag::is_persistence[]

// end::is_persistence[]


=== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]

// end::is_persistence_check_duplicate_per_pk[]


=== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]

// end::is_persistence_check_for_empty_source[]


=== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]

// end::is_persistence_delete_changed[]


=== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]

// end::is_persistence_delete_missing[]


=== is_persistence_insert

// tag::is_persistence_insert[]

// end::is_persistence_insert[]


=== is_persistence_truncate

// tag::is_persistence_truncate[]

// end::is_persistence_truncate[]


=== is_persistence_update_changed

// tag::is_persistence_update_changed[]

// end::is_persistence_update_changed[]


=== is_repo_managed

// tag::is_repo_managed[]
0
// end::is_repo_managed[]


=== is_ssas

// tag::is_ssas[]
0
// end::is_ssas[]


=== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


=== MS_Description

// tag::ms_description[]

// end::ms_description[]


=== persistence_source_RepoObject_fullname

// tag::persistence_source_repoobject_fullname[]

// end::persistence_source_repoobject_fullname[]


=== persistence_source_RepoObject_fullname2

// tag::persistence_source_repoobject_fullname2[]

// end::persistence_source_repoobject_fullname2[]


=== persistence_source_RepoObject_guid

// tag::persistence_source_repoobject_guid[]

// end::persistence_source_repoobject_guid[]


=== persistence_source_RepoObject_xref

// tag::persistence_source_repoobject_xref[]

// end::persistence_source_repoobject_xref[]


=== pk_index_guid

// tag::pk_index_guid[]
053E549A-0796-EB11-84F4-A81E8446D5B0
// end::pk_index_guid[]


=== pk_IndexPatternColumnDatatype

// tag::pk_indexpatterncolumndatatype[]
int,int
// end::pk_indexpatterncolumndatatype[]


=== pk_IndexPatternColumnName

// tag::pk_indexpatterncolumnname[]
usp_id,Number
// end::pk_indexpatterncolumnname[]


=== pk_IndexSemanticGroup

// tag::pk_indexsemanticgroup[]

// end::pk_indexsemanticgroup[]


=== ReferencedObjectList

// tag::referencedobjectlist[]
* [uspgenerator].[ftv_GeneratorUspStep_sql]
* [uspgenerator].[ftv_GeneratorUspStep_tree]
* [uspgenerator].[GeneratorUsp]
* [uspgenerator].[GeneratorUspStep]
// end::referencedobjectlist[]


=== usp_persistence_RepoObject_guid

// tag::usp_persistence_repoobject_guid[]

// end::usp_persistence_repoobject_guid[]


=== UspExamples

// tag::uspexamples[]

// end::uspexamples[]


=== uspgenerator_usp_id

// tag::uspgenerator_usp_id[]

// end::uspgenerator_usp_id[]


=== UspParameters

// tag::uspparameters[]

// end::uspparameters[]

== Boolean Attributes

source: property.RepoObjectProperty WHERE property_int = 1

// tag::boolean_attributes[]

:has_execution_plan_issue:

// end::boolean_attributes[]

== PlantUML diagrams

=== PlantUML Entity

// tag::puml_entity[]
[plantuml, entity-{docname}, svg, subs=macros]
....
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:uspgenerator.generatoruspstep_sql.adoc[]" as uspgenerator.GeneratorUspStep_Sql << V >> {
  - **usp_id** : (int)
  **Number** : (int)
  - AdocStep : (nvarchar(max))
  - has_logging : (tinyint)
  is_required_ELSE : (int)
  required_Begin_count : (int)
  required_End_count : (int)
  RowNumber_PerUsp : (bigint)
  - SqlStep : (nvarchar(max))
  - usp_fullname : (nvarchar(261))
  --
}
....

// end::puml_entity[]

=== PlantUML Entity 1 1 FK

// tag::puml_entity_1_1_fk[]
[plantuml, entity_1_1_fk-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:uspgenerator.generatoruspstep_sql.adoc[]" as uspgenerator.GeneratorUspStep_Sql << V >> {
- **PK_GeneratorUspStep_Sql**

..
usp_id; int
Number; int
--
- idx_GeneratorUspStep_Sql__2

..
usp_id; int
}



footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_fk[]

=== PlantUML 1 1 ObjectRef

// tag::puml_entity_1_1_objectref[]
[plantuml, entity_1_1_objectref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:uspgenerator.ftv_generatoruspstep_sql.adoc[]" as uspgenerator.ftv_GeneratorUspStep_sql << IF >> {
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.ftv_generatoruspstep_tree.adoc[]" as uspgenerator.ftv_GeneratorUspStep_tree << IF >> {
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.generatorusp.adoc[]" as uspgenerator.GeneratorUsp << U >> {
  - **id** : (int)
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.generatorusp_steplist.adoc[]" as uspgenerator.GeneratorUsp_StepList << V >> {
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.generatoruspstep.adoc[]" as uspgenerator.GeneratorUspStep << U >> {
  - **id** : (int)
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.generatoruspstep_sql.adoc[]" as uspgenerator.GeneratorUspStep_Sql << V >> {
  - **usp_id** : (int)
  **Number** : (int)
  --
}

uspgenerator.ftv_GeneratorUspStep_sql <.. uspgenerator.GeneratorUspStep_Sql
uspgenerator.ftv_GeneratorUspStep_tree <.. uspgenerator.GeneratorUspStep_Sql
uspgenerator.GeneratorUsp <.. uspgenerator.GeneratorUspStep_Sql
uspgenerator.GeneratorUspStep <.. uspgenerator.GeneratorUspStep_Sql
uspgenerator.GeneratorUspStep_Sql <.. uspgenerator.GeneratorUsp_StepList

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_objectref[]

=== PlantUML 30 0 ObjectRef

// tag::puml_entity_30_0_objectref[]
[plantuml, entity_30_0_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:uspgenerator.ftv_generatoruspstep_sql.adoc[]" as uspgenerator.ftv_GeneratorUspStep_sql << IF >> {
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.ftv_generatoruspstep_tree.adoc[]" as uspgenerator.ftv_GeneratorUspStep_tree << IF >> {
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.generatorusp.adoc[]" as uspgenerator.GeneratorUsp << U >> {
  - **id** : (int)
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.generatoruspstep.adoc[]" as uspgenerator.GeneratorUspStep << U >> {
  - **id** : (int)
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.generatoruspstep_sql.adoc[]" as uspgenerator.GeneratorUspStep_Sql << V >> {
  - **usp_id** : (int)
  **Number** : (int)
  --
}

uspgenerator.ftv_GeneratorUspStep_sql <.. uspgenerator.GeneratorUspStep_Sql
uspgenerator.ftv_GeneratorUspStep_tree <.. uspgenerator.GeneratorUspStep_Sql
uspgenerator.GeneratorUsp <.. uspgenerator.GeneratorUspStep_Sql
uspgenerator.GeneratorUspStep <.. uspgenerator.ftv_GeneratorUspStep_sql
uspgenerator.GeneratorUspStep <.. uspgenerator.ftv_GeneratorUspStep_tree
uspgenerator.GeneratorUspStep <.. uspgenerator.GeneratorUspStep_Sql

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_30_0_objectref[]

=== PlantUML 0 30 ObjectRef

// tag::puml_entity_0_30_objectref[]
[plantuml, entity_0_30_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:property.repoobjectproperty_collect_source_uspgenerator.adoc[]" as property.RepoObjectProperty_Collect_source_uspgenerator << V >> {
  **RepoObject_guid** : (uniqueidentifier)
  - **property_name** : (varchar(14))
  --
}

entity "puml-link:dhw:sqldb:property.usp_repoobject_inheritance.adoc[]" as property.usp_RepoObject_Inheritance << P >> {
  --
}

entity "puml-link:dhw:sqldb:property.usp_repoobjectproperty_collect.adoc[]" as property.usp_RepoObjectProperty_collect << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_main.adoc[]" as repo.usp_main << P >> {
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.generatorusp_sqlusp.adoc[]" as uspgenerator.GeneratorUsp_SqlUsp << V >> {
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.generatorusp_sqlusp_wo_go.adoc[]" as uspgenerator.GeneratorUsp_SqlUsp_wo_GO << V >> {
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.generatorusp_steplist.adoc[]" as uspgenerator.GeneratorUsp_StepList << V >> {
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.generatoruspstep_sql.adoc[]" as uspgenerator.GeneratorUspStep_Sql << V >> {
  - **usp_id** : (int)
  **Number** : (int)
  --
}

property.RepoObjectProperty_Collect_source_uspgenerator <.. property.usp_RepoObjectProperty_collect
property.usp_RepoObject_Inheritance <.. repo.usp_main
property.usp_RepoObjectProperty_collect <.. property.usp_RepoObject_Inheritance
property.usp_RepoObjectProperty_collect <.. repo.usp_main
uspgenerator.GeneratorUsp_SqlUsp <.. property.RepoObjectProperty_Collect_source_uspgenerator
uspgenerator.GeneratorUsp_StepList <.. uspgenerator.GeneratorUsp_SqlUsp
uspgenerator.GeneratorUsp_StepList <.. uspgenerator.GeneratorUsp_SqlUsp_wo_GO
uspgenerator.GeneratorUspStep_Sql <.. uspgenerator.GeneratorUsp_StepList

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_0_30_objectref[]

=== PlantUML 1 1 ColumnRef

// tag::puml_entity_1_1_colref[]
[plantuml, entity_1_1_colref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:uspgenerator.ftv_generatoruspstep_sql.adoc[]" as uspgenerator.ftv_GeneratorUspStep_sql << IF >> {
  - Number : (int)
  - SqlStep : (nvarchar(max))
  Statement : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.ftv_generatoruspstep_tree.adoc[]" as uspgenerator.ftv_GeneratorUspStep_tree << IF >> {
  Asc_PerParentChild : (bigint)
  child_PerParent : (bigint)
  Depth : (int)
  Desc_PerParentChild : (bigint)
  is_condition : (tinyint)
  - is_required_ELSE : (int)
  Number : (int)
  Parent_Number : (int)
  Parent_Sort : (int)
  Root_Sort : (int)
  RowNumber_PerUsp : (bigint)
  Sort : (int)
  usp_id : (int)
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.generatorusp.adoc[]" as uspgenerator.GeneratorUsp << U >> {
  - **id** : (int)
  - has_logging : (tinyint)
  usp_Description : (nvarchar(4000))
  usp_Examples : (nvarchar(4000))
  - usp_name : (nvarchar(128))
  - usp_schema : (nvarchar(128))
  # usp_fullname : (nvarchar(261))
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.generatorusp_steplist.adoc[]" as uspgenerator.GeneratorUsp_StepList << V >> {
  AdocStepList : (nvarchar(max))
  StepList : (nvarchar(max))
  - usp_id : (int)
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.generatoruspstep.adoc[]" as uspgenerator.GeneratorUspStep << U >> {
  - **id** : (int)
  Description : (nvarchar(4000))
  - has_logging : (tinyint)
  info_01 : (nvarchar(max))
  info_02 : (nvarchar(max))
  info_03 : (nvarchar(max))
  info_04 : (nvarchar(max))
  info_05 : (nvarchar(max))
  info_06 : (nvarchar(max))
  info_07 : (nvarchar(max))
  info_08 : (nvarchar(max))
  info_09 : (nvarchar(max))
  - is_condition : (tinyint)
  - is_inactive : (tinyint)
  - is_SubProcedure : (tinyint)
  log_flag_InsertUpdateDelete : (char(1))
  log_source_object : (nvarchar(261))
  log_target_object : (nvarchar(261))
  Name : (nvarchar(1000))
  - Number : (int)
  Parent_Number : (int)
  Statement : (nvarchar(max))
  - usp_id : (int)
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.generatoruspstep_sql.adoc[]" as uspgenerator.GeneratorUspStep_Sql << V >> {
  - **usp_id** : (int)
  **Number** : (int)
  - AdocStep : (nvarchar(max))
  - has_logging : (tinyint)
  is_required_ELSE : (int)
  required_Begin_count : (int)
  required_End_count : (int)
  RowNumber_PerUsp : (bigint)
  - SqlStep : (nvarchar(max))
  - usp_fullname : (nvarchar(261))
  --
}

uspgenerator.ftv_GeneratorUspStep_sql <.. uspgenerator.GeneratorUspStep_Sql
uspgenerator.ftv_GeneratorUspStep_tree <.. uspgenerator.GeneratorUspStep_Sql
uspgenerator.GeneratorUsp <.. uspgenerator.GeneratorUspStep_Sql
uspgenerator.GeneratorUspStep <.. uspgenerator.GeneratorUspStep_Sql
uspgenerator.GeneratorUspStep_Sql <.. uspgenerator.GeneratorUsp_StepList
"uspgenerator.GeneratorUsp::has_logging" <-- "uspgenerator.GeneratorUspStep_Sql::has_logging"
"uspgenerator.GeneratorUsp::id" <-- "uspgenerator.GeneratorUspStep_Sql::usp_id"
"uspgenerator.GeneratorUsp::usp_fullname" <-- "uspgenerator.GeneratorUspStep_Sql::usp_fullname"
"uspgenerator.GeneratorUspStep_Sql::usp_id" <-- "uspgenerator.GeneratorUsp_StepList::usp_id"

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_colref[]


== sql_modules_definition

// tag::sql_modules_definition[]
[%collapsible]
=======
[source,sql,numbered,indent=0]
----


/*
--usage:

SELECT *
FROM [repo].[GeneratorUspStep_Sql]
ORDER BY [id]
 , [RowNumber_PerUsp]


*/
CREATE View [uspgenerator].[GeneratorUspStep_Sql]
As
Select
    usp_id   = u.id
  , t.Number
  , u.has_logging
  , BeginEnd.required_Begin_count
  , BeginEnd.required_End_count
  , BeginEnd.is_required_ELSE
  --only information
  , u.usp_fullname
  , t.RowNumber_PerUsp
  --, [t].[Depth]
  --, [t].[is_condition]
  --, [t].[Root_Sort]
  --, [t].[Parent_Number]
  --, [t].[Parent_Sort]
  --, [t].[Sort]
  --, [t].[child_PerParent]
  --, [t].[Asc_PerParentChild]
  --, [t].[Desc_PerParentChild]
  , sql.SqlStep
  ----this list is  too wide, we need a smaller list
  --, AdocStep = CONCAT (
  -- '|'
  -- , step.Number
  -- , CHAR(13)
  -- , CHAR(10)
  -- , '|'
  -- , step.[Name]
  -- , CHAR(13)
  -- , CHAR(10)
  -- , '|'
  -- , step.[is_condition]
  -- , CHAR(13)
  -- , CHAR(10)
  -- , '|'
  -- , step.[log_source_object]
  -- , CHAR(13)
  -- , CHAR(10)
  -- , '|'
  -- , step.[log_target_object]
  -- , CHAR(13)
  -- , CHAR(10)
  -- , '|'
  -- , step.[log_flag_InsertUpdateDelete]
  -- , CHAR(13)
  -- , CHAR(10)
  -- )
  , AdocStep = Concat (
                          '|'
                        , step.Number
                        , Char ( 13 ) + Char ( 10 )
                        , '|'
                        , Char ( 13 ) + Char ( 10 )
                        , '*'
                        , step.Name
                        , '*'
                        , Char ( 13 ) + Char ( 10 )
                        , Char ( 13 ) + Char ( 10 )
                        , Iif(step.is_SubProcedure = 1
                              , '* ' + '`EXEC ' + step.Statement + '`' + Char ( 13 ) + Char ( 10 )
                              , Null)
                        , Iif(step.is_condition = 1
                              , '* ' + '`IF ' + step.Statement + '`' + Char ( 13 ) + Char ( 10 )
                              , Null)
                        , Iif(step.log_flag_InsertUpdateDelete <> ''
                              , '* ' + step.log_flag_InsertUpdateDelete + Char ( 13 ) + Char ( 10 )
                              , Null)
                        , Iif(step.log_source_object <> ''
                              , '* ' + step.log_source_object + Char ( 13 ) + Char ( 10 )
                              , Null)
                        , Iif(step.log_target_object <> ''
                              , '* ' + step.log_target_object + Char ( 13 ) + Char ( 10 )
                              , Null)
                        , Char ( 13 ) + Char ( 10 )
                        , Char ( 13 ) + Char ( 10 ) + step.Description + Char ( 13 ) + Char ( 10 )
                        , Char ( 13 ) + Char ( 10 )
                        , '.Statement' + Char ( 13 ) + Char ( 10 )
                        , '[%collapsible]' + Char ( 13 ) + Char ( 10 )
                        , '=====' + Char ( 13 ) + Char ( 10 )
                        , '[source,sql,numbered]' + Char ( 13 ) + Char ( 10 )
                        , '----' + Char ( 13 ) + Char ( 10 )
                        , step.Statement + Char ( 13 ) + Char ( 10 )
                        , '----' + Char ( 13 ) + Char ( 10 )
                        , '=====' + Char ( 13 ) + Char ( 10 )
                        , Char ( 13 ) + Char ( 10 )
                        , '|'
                        , step.Parent_Number
                        , Char ( 13 ) + Char ( 10 )
                        , Char ( 13 ) + Char ( 10 )
                      )
From
    uspgenerator.GeneratorUsp                                       As u
    Cross Apply uspgenerator.ftv_GeneratorUspStep_tree ( id, Null ) As t
    Left Join
    (
        Select
            s.usp_id
          , t.Number
          , required_Begin_count = Sum ( Iif(t.Asc_PerParentChild = 1, 1, 0))
          , required_End_count   = Sum ( Iif(t.Desc_PerParentChild = 1, 1, 0))
          , is_required_ELSE     = Max ( t.is_required_ELSE )
        From
            uspgenerator.GeneratorUspStep                                         As s
            Cross Apply uspgenerator.ftv_GeneratorUspStep_tree ( usp_id, Number ) As t
        Where
            s.is_condition = 1
        Group By
            s.usp_id
          , t.Number
    )                                                   As BeginEnd
        On
        BeginEnd.usp_id = u.id
        And BeginEnd.Number = t.Number

    Left Join
        uspgenerator.GeneratorUspStep                   As step
            On
            step.usp_id = u.id
            And step.Number = t.Number
    Cross Apply uspgenerator.ftv_GeneratorUspStep_sql (
                                                          u.id
                                                        , t.Number
                                                        , u.has_logging
                                                        , BeginEnd.required_Begin_count
                                                        , BeginEnd.required_End_count
                                                        , BeginEnd.is_required_ELSE
                                                      ) As sql

----
=======
// end::sql_modules_definition[]


