// tag::HeaderFullDisplayName[]
= uspgenerator.ftv_GeneratorUspStep_tree - IF
// end::HeaderFullDisplayName[]

== existing_properties

// tag::existing_properties[]

:ExistsProperty--antorareferencedlist:
:ExistsProperty--antorareferencinglist:
:ExistsProperty--description:
:ExistsProperty--exampleusage:
:ExistsProperty--is_repo_managed:
:ExistsProperty--is_ssas:
:ExistsProperty--referencedobjectlist:
:ExistsProperty--sql_modules_definition:
:ExistsProperty--AntoraParameterList:
:ExistsProperty--Columns:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
3390291C-9D61-EB11-84DC-A81E8446D5B0
// end::RepoObject_guid[]

== RepoObject_FullDisplayName2

// tag::RepoObject_FullDisplayName2[]
uspgenerator.ftv_GeneratorUspStep_tree
// end::RepoObject_FullDisplayName2[]

== SysObject_type

// tag::SysObject_type[]
IF
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
inline function
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
866102126
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2021-10-02 13:23:34
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]
[discrete]
== _


[#column-ascunderlineperparentchild]
=== Asc_PerParentChild

[cols="d,8a,m,m,m"]
|===
|
|Asc_PerParentChild
|bigint
|NULL
|
|===


[#column-childunderlineperparent]
=== child_PerParent

[cols="d,8a,m,m,m"]
|===
|
|child_PerParent
|bigint
|NULL
|
|===


[#column-depth]
=== Depth

[cols="d,8a,m,m,m"]
|===
|
|Depth
|int
|NULL
|
|===


[#column-descunderlineperparentchild]
=== Desc_PerParentChild

[cols="d,8a,m,m,m"]
|===
|
|Desc_PerParentChild
|bigint
|NULL
|
|===


[#column-isunderlinecondition]
=== is_condition

[cols="d,8a,m,m,m"]
|===
|
|is_condition
|tinyint
|NULL
|
|===


[#column-isunderlinerequiredunderlineelse]
=== is_required_ELSE

[cols="d,8a,m,m,m"]
|===
|
|is_required_ELSE
|int
|NOT NULL
|
|===


[#column-number]
=== Number

[cols="d,8a,m,m,m"]
|===
|
|Number
|int
|NULL
|
|===


[#column-parentunderlinenumber]
=== Parent_Number

[cols="d,8a,m,m,m"]
|===
|
|Parent_Number
|int
|NULL
|
|===


[#column-parentunderlinesort]
=== Parent_Sort

[cols="d,8a,m,m,m"]
|===
|
|Parent_Sort
|int
|NULL
|
|===


[#column-rootunderlinesort]
=== Root_Sort

[cols="d,8a,m,m,m"]
|===
|
|Root_Sort
|int
|NULL
|
|===


[#column-rownumberunderlineperusp]
=== RowNumber_PerUsp

[cols="d,8a,m,m,m"]
|===
|
|RowNumber_PerUsp
|bigint
|NULL
|
|===


[#column-sort]
=== Sort

[cols="d,8a,m,m,m"]
|===
|
|Sort
|int
|NULL
|
|===


[#column-uspunderlineid]
=== usp_id

[cols="d,8a,m,m,m"]
|===
|
|usp_id
|int
|NULL
|
|===


// end::AntoraColumnDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]













// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]
|
|<<column-ascunderlineperparentchild>>
|bigint
|NULL
|

|
|<<column-childunderlineperparent>>
|bigint
|NULL
|

|
|<<column-depth>>
|int
|NULL
|

|
|<<column-descunderlineperparentchild>>
|bigint
|NULL
|

|
|<<column-isunderlinecondition>>
|tinyint
|NULL
|

|
|<<column-isunderlinerequiredunderlineelse>>
|int
|NOT NULL
|

|
|<<column-number>>
|int
|NULL
|

|
|<<column-parentunderlinenumber>>
|int
|NULL
|

|
|<<column-parentunderlinesort>>
|int
|NULL
|

|
|<<column-rootunderlinesort>>
|int
|NULL
|

|
|<<column-rownumberunderlineperusp>>
|bigint
|NULL
|

|
|<<column-sort>>
|int
|NULL
|

|
|<<column-uspunderlineid>>
|int
|NULL
|

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

// end::AntoraIndexList[]

== AntoraMeasureDetails

// tag::AntoraMeasureDetails[]

// end::AntoraMeasureDetails[]

== AntoraMeasureDescriptions



== AntoraParameterList

// tag::AntoraParameterList[]
* @usp_id (int)
* @Parent_Number (int)
// end::AntoraParameterList[]

== AntoraXrefCulturesList

// tag::AntoraXrefCulturesList[]
* xref:dhw:sqldb:uspgenerator.ftv_generatoruspstep_tree.adoc[] - 
// end::AntoraXrefCulturesList[]

== cultures_count

// tag::cultures_count[]
1
// end::cultures_count[]

== Other tags

source: property.RepoObjectProperty_cross As rop_cross


=== additional_reference_csv

// tag::additional_reference_csv[]

// end::additional_reference_csv[]


=== AdocUspSteps

// tag::adocuspsteps[]

// end::adocuspsteps[]


=== AntoraReferencedList

// tag::antorareferencedlist[]
* xref:dhw:sqldb:uspgenerator.generatoruspstep.adoc[]
// end::antorareferencedlist[]


=== AntoraReferencingList

// tag::antorareferencinglist[]
* xref:dhw:sqldb:uspgenerator.generatoruspstep_sql.adoc[]
// end::antorareferencinglist[]


=== Description

// tag::description[]

* xref:sqldb:uspgenerator.generatoruspstep.adoc[] has a parent child structure.
Here in this function we try to get the numbers in the right order.
* It is not perfect if the tree is to deep and some "deep" numbers are lower.
** check the result per [usp_id]
** and if it not fits try to use better sorted numbers
* one goal is to solve steps which are conditions
** is_condition = 1
** we need to encapsulate condition THEN and ELSE statement in BEGIN...END blocks
** and this should work recursively
** see the comment on top of the code for more details and testing
// end::description[]


=== exampleUsage

// tag::exampleusage[]

--get all steps per Usp, recursively:

SELECT u.*
 , t.*
FROM [uspgenerator].[GeneratorUsp] u
CROSS APPLY [uspgenerator].[ftv_GeneratorUspStep_tree]([id], NULL) t
ORDER BY [u].id
 , t.[RowNumber_PerUsp]
// end::exampleusage[]


=== exampleUsage_2

// tag::exampleusage_2[]

// end::exampleusage_2[]


=== exampleUsage_3

// tag::exampleusage_3[]

// end::exampleusage_3[]


=== exampleUsage_4

// tag::exampleusage_4[]

// end::exampleusage_4[]


=== exampleUsage_5

// tag::exampleusage_5[]

// end::exampleusage_5[]


=== exampleWrong_Usage

// tag::examplewrong_usage[]

// end::examplewrong_usage[]


=== has_execution_plan_issue

// tag::has_execution_plan_issue[]

// end::has_execution_plan_issue[]


=== has_get_referenced_issue

// tag::has_get_referenced_issue[]

// end::has_get_referenced_issue[]


=== has_history

// tag::has_history[]

// end::has_history[]


=== has_history_columns

// tag::has_history_columns[]

// end::has_history_columns[]


=== InheritanceType

// tag::inheritancetype[]

// end::inheritancetype[]


=== is_persistence

// tag::is_persistence[]

// end::is_persistence[]


=== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]

// end::is_persistence_check_duplicate_per_pk[]


=== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]

// end::is_persistence_check_for_empty_source[]


=== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]

// end::is_persistence_delete_changed[]


=== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]

// end::is_persistence_delete_missing[]


=== is_persistence_insert

// tag::is_persistence_insert[]

// end::is_persistence_insert[]


=== is_persistence_truncate

// tag::is_persistence_truncate[]

// end::is_persistence_truncate[]


=== is_persistence_update_changed

// tag::is_persistence_update_changed[]

// end::is_persistence_update_changed[]


=== is_repo_managed

// tag::is_repo_managed[]
0
// end::is_repo_managed[]


=== is_ssas

// tag::is_ssas[]
0
// end::is_ssas[]


=== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


=== MS_Description

// tag::ms_description[]

// end::ms_description[]


=== persistence_source_RepoObject_fullname

// tag::persistence_source_repoobject_fullname[]

// end::persistence_source_repoobject_fullname[]


=== persistence_source_RepoObject_fullname2

// tag::persistence_source_repoobject_fullname2[]

// end::persistence_source_repoobject_fullname2[]


=== persistence_source_RepoObject_guid

// tag::persistence_source_repoobject_guid[]

// end::persistence_source_repoobject_guid[]


=== persistence_source_RepoObject_xref

// tag::persistence_source_repoobject_xref[]

// end::persistence_source_repoobject_xref[]


=== pk_index_guid

// tag::pk_index_guid[]

// end::pk_index_guid[]


=== pk_IndexPatternColumnDatatype

// tag::pk_indexpatterncolumndatatype[]

// end::pk_indexpatterncolumndatatype[]


=== pk_IndexPatternColumnName

// tag::pk_indexpatterncolumnname[]

// end::pk_indexpatterncolumnname[]


=== pk_IndexSemanticGroup

// tag::pk_indexsemanticgroup[]

// end::pk_indexsemanticgroup[]


=== ReferencedObjectList

// tag::referencedobjectlist[]
* [uspgenerator].[GeneratorUspStep]
// end::referencedobjectlist[]


=== usp_persistence_RepoObject_guid

// tag::usp_persistence_repoobject_guid[]

// end::usp_persistence_repoobject_guid[]


=== UspExamples

// tag::uspexamples[]

// end::uspexamples[]


=== uspgenerator_usp_id

// tag::uspgenerator_usp_id[]

// end::uspgenerator_usp_id[]


=== UspParameters

// tag::uspparameters[]

// end::uspparameters[]

== Boolean Attributes

source: property.RepoObjectProperty WHERE property_int = 1

// tag::boolean_attributes[]


// end::boolean_attributes[]

== PlantUML diagrams

=== PlantUML Entity

// tag::puml_entity[]
[plantuml, entity-{docname}, svg, subs=macros]
....
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:uspgenerator.ftv_generatoruspstep_tree.adoc[]" as uspgenerator.ftv_GeneratorUspStep_tree << IF >> {
  Asc_PerParentChild : (bigint)
  child_PerParent : (bigint)
  Depth : (int)
  Desc_PerParentChild : (bigint)
  is_condition : (tinyint)
  - is_required_ELSE : (int)
  Number : (int)
  Parent_Number : (int)
  Parent_Sort : (int)
  Root_Sort : (int)
  RowNumber_PerUsp : (bigint)
  Sort : (int)
  usp_id : (int)
  --
}
....

// end::puml_entity[]

=== PlantUML Entity 1 1 FK

// tag::puml_entity_1_1_fk[]
[plantuml, entity_1_1_fk-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}





footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_fk[]

=== PlantUML 1 1 ObjectRef

// tag::puml_entity_1_1_objectref[]
[plantuml, entity_1_1_objectref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:uspgenerator.ftv_generatoruspstep_tree.adoc[]" as uspgenerator.ftv_GeneratorUspStep_tree << IF >> {
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.generatoruspstep.adoc[]" as uspgenerator.GeneratorUspStep << U >> {
  - **id** : (int)
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.generatoruspstep_sql.adoc[]" as uspgenerator.GeneratorUspStep_Sql << V >> {
  - **usp_id** : (int)
  **Number** : (int)
  --
}

uspgenerator.ftv_GeneratorUspStep_tree <.. uspgenerator.GeneratorUspStep_Sql
uspgenerator.GeneratorUspStep <.. uspgenerator.ftv_GeneratorUspStep_tree

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_objectref[]

=== PlantUML 30 0 ObjectRef

// tag::puml_entity_30_0_objectref[]
[plantuml, entity_30_0_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:uspgenerator.ftv_generatoruspstep_tree.adoc[]" as uspgenerator.ftv_GeneratorUspStep_tree << IF >> {
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.generatoruspstep.adoc[]" as uspgenerator.GeneratorUspStep << U >> {
  - **id** : (int)
  --
}

uspgenerator.GeneratorUspStep <.. uspgenerator.ftv_GeneratorUspStep_tree

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_30_0_objectref[]

=== PlantUML 0 30 ObjectRef

// tag::puml_entity_0_30_objectref[]
[plantuml, entity_0_30_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:property.repoobjectproperty_collect_source_uspgenerator.adoc[]" as property.RepoObjectProperty_Collect_source_uspgenerator << V >> {
  **RepoObject_guid** : (uniqueidentifier)
  - **property_name** : (varchar(14))
  --
}

entity "puml-link:dhw:sqldb:property.usp_repoobject_inheritance.adoc[]" as property.usp_RepoObject_Inheritance << P >> {
  --
}

entity "puml-link:dhw:sqldb:property.usp_repoobjectproperty_collect.adoc[]" as property.usp_RepoObjectProperty_collect << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.usp_main.adoc[]" as repo.usp_main << P >> {
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.ftv_generatoruspstep_tree.adoc[]" as uspgenerator.ftv_GeneratorUspStep_tree << IF >> {
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.generatorusp_sqlusp.adoc[]" as uspgenerator.GeneratorUsp_SqlUsp << V >> {
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.generatorusp_sqlusp_wo_go.adoc[]" as uspgenerator.GeneratorUsp_SqlUsp_wo_GO << V >> {
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.generatorusp_steplist.adoc[]" as uspgenerator.GeneratorUsp_StepList << V >> {
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.generatoruspstep_sql.adoc[]" as uspgenerator.GeneratorUspStep_Sql << V >> {
  - **usp_id** : (int)
  **Number** : (int)
  --
}

property.RepoObjectProperty_Collect_source_uspgenerator <.. property.usp_RepoObjectProperty_collect
property.usp_RepoObject_Inheritance <.. repo.usp_main
property.usp_RepoObjectProperty_collect <.. property.usp_RepoObject_Inheritance
property.usp_RepoObjectProperty_collect <.. repo.usp_main
uspgenerator.ftv_GeneratorUspStep_tree <.. uspgenerator.GeneratorUspStep_Sql
uspgenerator.GeneratorUsp_SqlUsp <.. property.RepoObjectProperty_Collect_source_uspgenerator
uspgenerator.GeneratorUsp_StepList <.. uspgenerator.GeneratorUsp_SqlUsp
uspgenerator.GeneratorUsp_StepList <.. uspgenerator.GeneratorUsp_SqlUsp_wo_GO
uspgenerator.GeneratorUspStep_Sql <.. uspgenerator.GeneratorUsp_StepList

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_0_30_objectref[]

=== PlantUML 1 1 ColumnRef

// tag::puml_entity_1_1_colref[]
[plantuml, entity_1_1_colref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:uspgenerator.ftv_generatoruspstep_tree.adoc[]" as uspgenerator.ftv_GeneratorUspStep_tree << IF >> {
  Asc_PerParentChild : (bigint)
  child_PerParent : (bigint)
  Depth : (int)
  Desc_PerParentChild : (bigint)
  is_condition : (tinyint)
  - is_required_ELSE : (int)
  Number : (int)
  Parent_Number : (int)
  Parent_Sort : (int)
  Root_Sort : (int)
  RowNumber_PerUsp : (bigint)
  Sort : (int)
  usp_id : (int)
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.generatoruspstep.adoc[]" as uspgenerator.GeneratorUspStep << U >> {
  - **id** : (int)
  Description : (nvarchar(4000))
  - has_logging : (tinyint)
  info_01 : (nvarchar(max))
  info_02 : (nvarchar(max))
  info_03 : (nvarchar(max))
  info_04 : (nvarchar(max))
  info_05 : (nvarchar(max))
  info_06 : (nvarchar(max))
  info_07 : (nvarchar(max))
  info_08 : (nvarchar(max))
  info_09 : (nvarchar(max))
  - is_condition : (tinyint)
  - is_inactive : (tinyint)
  - is_SubProcedure : (tinyint)
  log_flag_InsertUpdateDelete : (char(1))
  log_source_object : (nvarchar(261))
  log_target_object : (nvarchar(261))
  Name : (nvarchar(1000))
  - Number : (int)
  Parent_Number : (int)
  Statement : (nvarchar(max))
  - usp_id : (int)
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.generatoruspstep_sql.adoc[]" as uspgenerator.GeneratorUspStep_Sql << V >> {
  - **usp_id** : (int)
  **Number** : (int)
  - AdocStep : (nvarchar(max))
  - has_logging : (tinyint)
  is_required_ELSE : (int)
  required_Begin_count : (int)
  required_End_count : (int)
  RowNumber_PerUsp : (bigint)
  - SqlStep : (nvarchar(max))
  - usp_fullname : (nvarchar(261))
  --
}

uspgenerator.ftv_GeneratorUspStep_tree <.. uspgenerator.GeneratorUspStep_Sql
uspgenerator.GeneratorUspStep <.. uspgenerator.ftv_GeneratorUspStep_tree


footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_colref[]


== sql_modules_definition

// tag::sql_modules_definition[]
[%collapsible]
=======
[source,sql,numbered,indent=0]
----

/*
<<property_start>>Description
* xref:sqldb:uspgenerator.generatoruspstep.adoc[] has a parent child structure.
Here in this function we try to get the numbers in the right order.
* It is not perfect if the tree is to deep and some "deep" numbers are lower.
** check the result per [usp_id]
** and if it not fits try to use better sorted numbers
* one goal is to solve steps which are conditions
** is_condition = 1
** we need to encapsulate condition THEN and ELSE statement in BEGIN...END blocks
** and this should work recursively
** see the comment on top of the code for more details and testing
<<property_end>>

<<property_start>>exampleUsage
--get all steps per Usp, recursively:

SELECT u.*
 , t.*
FROM [uspgenerator].[GeneratorUsp] u
CROSS APPLY [uspgenerator].[ftv_GeneratorUspStep_tree]([id], NULL) t
ORDER BY [u].id
 , t.[RowNumber_PerUsp]
<<property_end>>

----and now about conditions
----all this is done because we need to encapsulate condition THEN and ELSE statement in BEGIN...END blocks
----but we need to explore the first and last step per condition THEN- or ELSE-block
--
--get all (is_condition = 1) statements and their recursive children
SELECT [s].[usp_id]
 , [s].[Number] AS [Condition_Number]
 --, [s].[Parent_Number]
 --, [s].[Name]
 --, [s].[has_logging]
 --, [s].[is_condition]
 --, [s].[is_inactive]
 --, [s].[is_SubProcedure]
 --, [s].[Statement]
 --, [s].[log_source_object]
 --, [s].[log_target_object]
 --, [s].[log_flag_InsertUpdateDelete]
 --, [s].[info_01]
 --, [s].[info_02]
 --, [s].[info_03]
 --, [s].[info_04]
 --, [s].[info_05]
 --, [s].[info_06]
 --, [s].[info_07]
 --, [s].[info_08]
 --, [s].[info_09]
 --, [t].[usp_id]
 , [t].[child_PerParent]
 , [t].[RowNumber_PerUsp] AS [RowNumber_PerUspAndCondition]
 , [t].[Number]
 , [t].[Asc_PerParentChild]
 , [t].[Desc_PerParentChild]
 , [t].[is_required_ELSE]
--, [t].[Depth]
--, [t].[is_condition]
--, [t].[Root_Sort]
--, [t].[Parent_Number]
--, [t].[Parent_Sort]
--, [t].[Sort]
FROM [uspgenerator].[GeneratorUspStep] AS s
CROSS APPLY [uspgenerator].[ftv_GeneratorUspStep_tree]([usp_id], [Number]) AS t
WHERE [s].[is_condition] = 1
ORDER BY [s].[usp_id]
 , [Condition_Number]
 , [t].[child_PerParent]
 , [RowNumber_PerUspAndCondition]


--evaluate the count and place of BEGIN and END for condition statements:
--t: all recursive children of any step which is a condition
--this should also work for recursive conditions, because ([s].[is_condition] = 1) will filter any conditions
--([t].[Asc_PerParentChild] = 1) indicates a required BEGIN, these are first children of conditions
--([t].[Desc_PerParentChild] = 1) indicates a required BEGIN, these are last children of condition steps

SELECT [s].[usp_id]
 , [t].[Number]
 , required_Begin_count = SUM(IIF([t].[Asc_PerParentChild] = 1, 1, 0))
 , required_End_count = sum(iif([t].[Desc_PerParentChild] = 1, 1, 0))
 , [is_required_ELSE] = MAX([t].[is_required_ELSE])
FROM [uspgenerator].[GeneratorUspStep] AS s
CROSS APPLY [uspgenerator].[ftv_GeneratorUspStep_tree]([usp_id], [Number]) AS t
WHERE [s].[is_condition] = 1
GROUP BY [s].[usp_id]
 , [t].[Number]


 --combine all active steps per usp with required_Begin_count and required_End_count:

SELECT [u].[id]
 --, [u].[usp_schema]
 --, [u].[usp_name]
 , [u].[has_logging]
 --, [u].[usp_Comment]
 , [u].[usp_fullname]
 --, [t].[usp_id]
 , [t].[Number]
 , [t].[RowNumber_PerUsp]
 , [t].[Depth]
 , [t].[is_condition]
 , [t].[Root_Sort]
 --, [t].[Parent_Number]
 --, [t].[Parent_Sort]
 --, [t].[Sort]
 --, [t].[child_PerParent]
 --, [t].[Asc_PerParentChild]
 --, [t].[Desc_PerParentChild]
 , [BeginEnd].[required_Begin_count]
 , [BeginEnd].[required_End_count]
 , [BeginEnd].[is_required_ELSE]
FROM [uspgenerator].[GeneratorUsp] AS u
CROSS APPLY [uspgenerator].[ftv_GeneratorUspStep_tree]([id], NULL) AS t
LEFT JOIN (
 SELECT [s].[usp_id]
  , [t].[Number]
  , [required_Begin_count] = SUM(IIF([t].[Asc_PerParentChild] = 1, 1, 0))
  , [required_End_count] = SUM(IIF([t].[Desc_PerParentChild] = 1, 1, 0))
  , [is_required_ELSE] = MAX([t].[is_required_ELSE])
 FROM [uspgenerator].[GeneratorUspStep] AS s
 CROSS APPLY [uspgenerator].[ftv_GeneratorUspStep_tree]([usp_id], [Number]) AS t
 WHERE [s].[is_condition] = 1
 GROUP BY [s].[usp_id]
  , [t].[Number]
 ) AS BeginEnd
 ON BeginEnd.usp_id = u.id
  AND BeginEnd.Number = t.Number
ORDER BY [u].[id]
 , [t].[RowNumber_PerUsp]

--and finaly use [uspgenerator].[ftv_GeneratorUspStep_sql] to create the statement per step

SELECT [u].[id]
 , [t].[Number]
 , [u].[has_logging]
 , [BeginEnd].[required_Begin_count]
 , [BeginEnd].[required_End_count]
 , [BeginEnd].[is_required_ELSE]
 --only information
 , [u].[usp_fullname]
 , [t].[RowNumber_PerUsp]
 --, [t].[Depth]
 --, [t].[is_condition]
 --, [t].[Root_Sort]
 --, [t].[Parent_Number]
 --, [t].[Parent_Sort]
 --, [t].[Sort]
 --, [t].[child_PerParent]
 --, [t].[Asc_PerParentChild]
 --, [t].[Desc_PerParentChild]
 , sql.SqlStep
FROM [uspgenerator].[GeneratorUsp] AS u
CROSS APPLY [uspgenerator].[ftv_GeneratorUspStep_tree]([id], NULL) AS t
LEFT JOIN (
 SELECT [s].[usp_id]
  , [t].[Number]
  , [required_Begin_count] = SUM(IIF([t].[Asc_PerParentChild] = 1, 1, 0))
  , [required_End_count] = SUM(IIF([t].[Desc_PerParentChild] = 1, 1, 0))
  , [is_required_ELSE] = MAX([t].[is_required_ELSE])
 FROM [uspgenerator].[GeneratorUspStep] AS s
 CROSS APPLY [uspgenerator].[ftv_GeneratorUspStep_tree]([usp_id], [Number]) AS t
 WHERE [s].[is_condition] = 1
 GROUP BY [s].[usp_id]
  , [t].[Number]
 ) AS BeginEnd
 ON BeginEnd.usp_id = u.id
  AND BeginEnd.Number = t.Number
CROSS APPLY [uspgenerator].[ftv_GeneratorUspStep_sql]([u].[id], [t].[Number], [u].[has_logging], [BeginEnd].[required_Begin_count], [BeginEnd].[required_End_count], [BeginEnd].[is_required_ELSE]) sql
ORDER BY [u].[id]
 , [t].[RowNumber_PerUsp]


*/
CREATE Function [uspgenerator].[ftv_GeneratorUspStep_tree]
(
    @usp_id        Int
  , @Parent_Number Int
--, @usp_has_logging TINYINT = 0
)
Returns Table
As
Return
(
    With
    tree
    As
        --tree is recursive to solve parent child hierarchies
        (
        Select
            usp_id
          , Number
          , Parent_Number
          , 0               As Depth
          , Number          As Sort
          , Number          As Parent_Sort
          , Number          As Root_Sort
          , is_condition
          , child_PerParent = Iif(Not Parent_Number Is Null
                                  , Row_Number () Over ( Partition By usp_id, Parent_Number Order By Number )
                                  , Null)
        --ROW_NUMBER() OVER(Partition by [usp_id], [Parent_Number] ORDER BY [Number])
        From
            [uspgenerator].GeneratorUspStep
        Where
            --
            usp_id            = @usp_id
            And is_inactive   = 0
            And
            (
                Parent_Number = @Parent_Number
                Or @Parent_Number Is Null
                   And Parent_Number Is Null
            )
        Union All
        Select
            child.usp_id
          , child.Number
          , child.Parent_Number
          , parent.Depth + 1
          , child.Parent_Number As sort
          , parent.Sort         As Parent_sort
          , parent.Root_Sort    As Root_Sort
          , child.is_condition
          , child_PerParent     = parent.child_PerParent
        From
            [uspgenerator].GeneratorUspStep As child
            Inner Join
                tree              As parent
                    On
                    child.Parent_Number = parent.Number
        Where
            --
            child.usp_id          = @usp_id
            And child.is_inactive = 0
        )
  ,
    tree_2
    As
        --tree_2 is required to calculate the correct step order: [RowNumber_PerUsp]
        (
        Select
            --
            tree.usp_id
          , tree.Number
          , RowNumber_PerUsp = Row_Number () Over ( Partition By
                                                        tree.usp_id
                                                    Order By
                                                        tree.Root_Sort
                                                      , tree.Parent_Number
                                                      , tree.Parent_Sort
                                                      , tree.Sort
                                                  )
          , tree.Depth
          , tree.is_condition
          , tree.Root_Sort
          , tree.Parent_Number
          , tree.Parent_Sort
          , tree.Sort
          , tree.child_PerParent
        From
            tree
        )
  ,
    tree_3
    As
        --final query is used to calculate Asc_PerParentChild and Desc_PerParentChild
        --Asc_PerParentChild is the first step per [child_PerParent]
        --if the @Parent_Number has [is_condition] = 1
        --then [child_PerParent] = 1 is the THEN block an [child_PerParent] = 2 is the ELSE block
        --to encapsulate THEN and ELSE block:
        --a 'BEGIN' is required before Asc_PerParentChild = 1
        --a 'END' is required after Desc_PerParentChild = 1
        (
        Select
            --
            *
          , Asc_PerParentChild  = Row_Number () Over ( Partition By usp_id, child_PerParent Order By RowNumber_PerUsp )
          , Desc_PerParentChild = Row_Number () Over ( Partition By usp_id, child_PerParent Order By RowNumber_PerUsp Desc )
        From
            tree_2
        )
    Select
        --
        *
      --[child_PerParent] = 2 is the ELSE-block, if the parent is a condition
      --in front of the ELSE block the 'ELSE' is required
      , is_required_ELSE = Iif(child_PerParent = 2 And Asc_PerParentChild = 1, 1, 0)
    From
        tree_3
);
----
=======
// end::sql_modules_definition[]


