// tag::HeaderFullDisplayName[]
= uspgenerator.GeneratorUsp_SqlUsp_wo_GO - V
// end::HeaderFullDisplayName[]

== existing_properties

// tag::existing_properties[]

:ExistsProperty--antorareferencedlist:
:ExistsProperty--is_repo_managed:
:ExistsProperty--is_ssas:
:ExistsProperty--referencedobjectlist:
:ExistsProperty--sql_modules_definition:
:ExistsProperty--FK:
:ExistsProperty--AntoraIndexList:
:ExistsProperty--Columns:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
71D4AE2C-C2EB-EC11-8568-A81E8446D5B0
// end::RepoObject_guid[]

== RepoObject_FullDisplayName2

// tag::RepoObject_FullDisplayName2[]
uspgenerator.GeneratorUsp_SqlUsp_wo_GO
// end::RepoObject_FullDisplayName2[]

== SysObject_type

// tag::SysObject_type[]
V 
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
view
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
1008774701
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2022-06-14 10:54:34
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]
[discrete]
== _


[#column-adocuspsteps]
=== AdocUspSteps

[cols="d,8a,m,m,m"]
|===
|
|AdocUspSteps
|nvarchar(max)
|NOT NULL
|
|===


[#column-hasunderlinelogging]
=== has_logging

[cols="d,8a,m,m,m"]
|===
|
|has_logging
|tinyint
|NOT NULL
|
|===

.Referenced Columns
--
* xref:uspgenerator.generatorusp.adoc#column-hasunderlinelogging[+uspgenerator.GeneratorUsp.has_logging+]
--


[#column-msunderlinedescription]
=== MS_Description

[cols="d,8a,m,m,m"]
|===
|
|MS_Description
|nvarchar(4000)
|NULL
|
|===

.Referenced Columns
--
* xref:uspgenerator.generatorusp.adoc#column-uspunderlinedescription[+uspgenerator.GeneratorUsp.usp_Description+]
--


[#column-repoobjectunderlineguid]
=== RepoObject_guid

[cols="d,8a,m,m,m"]
|===
|
|RepoObject_guid
|uniqueidentifier
|NULL
|
|===

.Referenced Columns
--
* xref:repo.repoobject.adoc#column-repoobjectunderlineguid[+repo.RepoObject.RepoObject_guid+]
--


[#column-sqlsteplist]
=== SqlStepList

[cols="d,8a,m,m,m"]
|===
|
|SqlStepList
|nvarchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:uspgenerator.generatorusp_steplist.adoc#column-steplist[+uspgenerator.GeneratorUsp_StepList.StepList+]
--


[#column-sqluspunderlinewounderlinego]
=== SqlUsp_wo_GO

[cols="d,8a,m,m,m"]
|===
|
|SqlUsp_wo_GO
|nvarchar(max)
|NOT NULL
|
|===


[#column-uspunderlinedescription]
=== usp_Description

[cols="d,8a,m,m,m"]
|===
|
|usp_Description
|nvarchar(4000)
|NULL
|
|===

.Referenced Columns
--
* xref:uspgenerator.generatorusp.adoc#column-uspunderlinedescription[+uspgenerator.GeneratorUsp.usp_Description+]
--


[#column-uspunderlinefullname]
=== usp_fullname

[cols="d,8a,m,m,m"]
|===
|
|usp_fullname
|nvarchar(261)
|NOT NULL
|
|===

.Description
--
(concat('[',[usp_schema],'].[',[usp_name],']'))
--
{empty} +

.Referenced Columns
--
* xref:uspgenerator.generatorusp.adoc#column-uspunderlinefullname[+uspgenerator.GeneratorUsp.usp_fullname+]
--


[#column-uspunderlineid]
=== usp_id

[cols="d,8a,m,m,m"]
|===
|
|usp_id
|int
|NOT NULL
|
|===

.Referenced Columns
--
* xref:uspgenerator.generatorusp.adoc#column-id[+uspgenerator.GeneratorUsp.id+]
--


[#column-uspunderlinename]
=== usp_name

[cols="d,8a,m,m,m"]
|===
|
|usp_name
|nvarchar(128)
|NOT NULL
|
|===

.Referenced Columns
--
* xref:uspgenerator.generatorusp.adoc#column-uspunderlinename[+uspgenerator.GeneratorUsp.usp_name+]
--


[#column-uspunderlineschema]
=== usp_schema

[cols="d,8a,m,m,m"]
|===
|
|usp_schema
|nvarchar(128)
|NOT NULL
|
|===

.Referenced Columns
--
* xref:uspgenerator.generatorusp.adoc#column-uspunderlineschema[+uspgenerator.GeneratorUsp.usp_schema+]
--


[#column-uspexamples]
=== UspExamples

[cols="d,8a,m,m,m"]
|===
|
|UspExamples
|nvarchar(4000)
|NOT NULL
|
|===


[#column-uspparameters]
=== UspParameters

[cols="d,8a,m,m,m"]
|===
|
|UspParameters
|nvarchar(max)
|NULL
|
|===

.Referenced Columns
--
* xref:uspgenerator.generatorusp_parameterlist.adoc#column-parameterlist[+uspgenerator.GeneratorUsp_ParameterList.ParameterList+]
--


// end::AntoraColumnDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]













// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]
|
|<<column-adocuspsteps>>
|nvarchar(max)
|NOT NULL
|

|
|<<column-hasunderlinelogging>>
|tinyint
|NOT NULL
|

|
|<<column-msunderlinedescription>>
|nvarchar(4000)
|NULL
|

|
|<<column-repoobjectunderlineguid>>
|uniqueidentifier
|NULL
|

|
|<<column-sqlsteplist>>
|nvarchar(max)
|NULL
|

|
|<<column-sqluspunderlinewounderlinego>>
|nvarchar(max)
|NOT NULL
|

|
|<<column-uspunderlinedescription>>
|nvarchar(4000)
|NULL
|

|
|<<column-uspunderlinefullname>>
|nvarchar(261)
|NOT NULL
|

|
|<<column-uspunderlineid>>
|int
|NOT NULL
|

|
|<<column-uspunderlinename>>
|nvarchar(128)
|NOT NULL
|

|
|<<column-uspunderlineschema>>
|nvarchar(128)
|NOT NULL
|

|
|<<column-uspexamples>>
|nvarchar(4000)
|NOT NULL
|

|
|<<column-uspparameters>>
|nvarchar(max)
|NULL
|

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

[#index-idxunderlinegeneratoruspunderlinesqluspunderlinewounderlinegounderlineunderline1]
=== idx_GeneratorUsp_SqlUsp_wo_GO++__++1

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-usp_schema>>; nvarchar(128)
* <<column-usp_name>>; nvarchar(128)
--
* PK, Unique, Real: 0, 0, 0


[#index-idxunderlinegeneratoruspunderlinesqluspunderlinewounderlinegounderlineunderline2]
=== idx_GeneratorUsp_SqlUsp_wo_GO++__++2

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-RepoObject_guid>>; uniqueidentifier
--
* PK, Unique, Real: 0, 0, 0


[#index-idxunderlinegeneratoruspunderlinesqluspunderlinewounderlinegounderlineunderline3]
=== idx_GeneratorUsp_SqlUsp_wo_GO++__++3

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-usp_id>>; int
--
* PK, Unique, Real: 0, 0, 0

// end::AntoraIndexList[]

== AntoraMeasureDetails

// tag::AntoraMeasureDetails[]

// end::AntoraMeasureDetails[]

== AntoraMeasureDescriptions



== AntoraParameterList

// tag::AntoraParameterList[]

// end::AntoraParameterList[]

== AntoraXrefCulturesList

// tag::AntoraXrefCulturesList[]
* xref:dhw:sqldb:uspgenerator.generatorusp_sqlusp_wo_go.adoc[] - 
// end::AntoraXrefCulturesList[]

== cultures_count

// tag::cultures_count[]
1
// end::cultures_count[]

== Other tags

source: property.RepoObjectProperty_cross As rop_cross


=== additional_reference_csv

// tag::additional_reference_csv[]

// end::additional_reference_csv[]


=== AdocUspSteps

// tag::adocuspsteps[]

// end::adocuspsteps[]


=== AntoraReferencedList

// tag::antorareferencedlist[]
* xref:dhw:sqldb:config.ftv_dwh_database.adoc[]
* xref:dhw:sqldb:repo.repoobject.adoc[]
* xref:dhw:sqldb:uspgenerator.generatorusp.adoc[]
* xref:dhw:sqldb:uspgenerator.generatorusp_parameterlist.adoc[]
* xref:dhw:sqldb:uspgenerator.generatorusp_steplist.adoc[]
// end::antorareferencedlist[]


=== AntoraReferencingList

// tag::antorareferencinglist[]

// end::antorareferencinglist[]


=== Description

// tag::description[]

// end::description[]


=== exampleUsage

// tag::exampleusage[]

// end::exampleusage[]


=== exampleUsage_2

// tag::exampleusage_2[]

// end::exampleusage_2[]


=== exampleUsage_3

// tag::exampleusage_3[]

// end::exampleusage_3[]


=== exampleUsage_4

// tag::exampleusage_4[]

// end::exampleusage_4[]


=== exampleUsage_5

// tag::exampleusage_5[]

// end::exampleusage_5[]


=== exampleWrong_Usage

// tag::examplewrong_usage[]

// end::examplewrong_usage[]


=== has_execution_plan_issue

// tag::has_execution_plan_issue[]

// end::has_execution_plan_issue[]


=== has_get_referenced_issue

// tag::has_get_referenced_issue[]

// end::has_get_referenced_issue[]


=== has_history

// tag::has_history[]

// end::has_history[]


=== has_history_columns

// tag::has_history_columns[]

// end::has_history_columns[]


=== InheritanceType

// tag::inheritancetype[]

// end::inheritancetype[]


=== is_persistence

// tag::is_persistence[]

// end::is_persistence[]


=== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]

// end::is_persistence_check_duplicate_per_pk[]


=== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]

// end::is_persistence_check_for_empty_source[]


=== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]

// end::is_persistence_delete_changed[]


=== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]

// end::is_persistence_delete_missing[]


=== is_persistence_insert

// tag::is_persistence_insert[]

// end::is_persistence_insert[]


=== is_persistence_truncate

// tag::is_persistence_truncate[]

// end::is_persistence_truncate[]


=== is_persistence_update_changed

// tag::is_persistence_update_changed[]

// end::is_persistence_update_changed[]


=== is_repo_managed

// tag::is_repo_managed[]
0
// end::is_repo_managed[]


=== is_ssas

// tag::is_ssas[]
0
// end::is_ssas[]


=== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


=== MS_Description

// tag::ms_description[]

// end::ms_description[]


=== persistence_source_RepoObject_fullname

// tag::persistence_source_repoobject_fullname[]

// end::persistence_source_repoobject_fullname[]


=== persistence_source_RepoObject_fullname2

// tag::persistence_source_repoobject_fullname2[]

// end::persistence_source_repoobject_fullname2[]


=== persistence_source_RepoObject_guid

// tag::persistence_source_repoobject_guid[]

// end::persistence_source_repoobject_guid[]


=== persistence_source_RepoObject_xref

// tag::persistence_source_repoobject_xref[]

// end::persistence_source_repoobject_xref[]


=== pk_index_guid

// tag::pk_index_guid[]

// end::pk_index_guid[]


=== pk_IndexPatternColumnDatatype

// tag::pk_indexpatterncolumndatatype[]

// end::pk_indexpatterncolumndatatype[]


=== pk_IndexPatternColumnName

// tag::pk_indexpatterncolumnname[]

// end::pk_indexpatterncolumnname[]


=== pk_IndexSemanticGroup

// tag::pk_indexsemanticgroup[]

// end::pk_indexsemanticgroup[]


=== ReferencedObjectList

// tag::referencedobjectlist[]
* [config].[ftv_dwh_database]
* [repo].[RepoObject]
* [uspgenerator].[GeneratorUsp]
* [uspgenerator].[GeneratorUsp_ParameterList]
* [uspgenerator].[GeneratorUsp_StepList]
// end::referencedobjectlist[]


=== usp_persistence_RepoObject_guid

// tag::usp_persistence_repoobject_guid[]

// end::usp_persistence_repoobject_guid[]


=== UspExamples

// tag::uspexamples[]

// end::uspexamples[]


=== uspgenerator_usp_id

// tag::uspgenerator_usp_id[]

// end::uspgenerator_usp_id[]


=== UspParameters

// tag::uspparameters[]

// end::uspparameters[]

== Boolean Attributes

source: property.RepoObjectProperty WHERE property_int = 1

// tag::boolean_attributes[]


// end::boolean_attributes[]

== PlantUML diagrams

=== PlantUML Entity

// tag::puml_entity[]
[plantuml, entity-{docname}, svg, subs=macros]
....
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:uspgenerator.generatorusp_sqlusp_wo_go.adoc[]" as uspgenerator.GeneratorUsp_SqlUsp_wo_GO << V >> {
  - AdocUspSteps : (nvarchar(max))
  - has_logging : (tinyint)
  MS_Description : (nvarchar(4000))
  RepoObject_guid : (uniqueidentifier)
  SqlStepList : (nvarchar(max))
  - SqlUsp_wo_GO : (nvarchar(max))
  usp_Description : (nvarchar(4000))
  - usp_fullname : (nvarchar(261))
  - usp_id : (int)
  - usp_name : (nvarchar(128))
  - usp_schema : (nvarchar(128))
  - UspExamples : (nvarchar(4000))
  UspParameters : (nvarchar(max))
  --
}
....

// end::puml_entity[]

=== PlantUML Entity 1 1 FK

// tag::puml_entity_1_1_fk[]
[plantuml, entity_1_1_fk-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:uspgenerator.generatorusp_sqlusp_wo_go.adoc[]" as uspgenerator.GeneratorUsp_SqlUsp_wo_GO << V >> {
- idx_GeneratorUsp_SqlUsp_wo_GO__1

..
usp_schema; nvarchar(128)
usp_name; nvarchar(128)
--
- idx_GeneratorUsp_SqlUsp_wo_GO__2

..
RepoObject_guid; uniqueidentifier
--
- idx_GeneratorUsp_SqlUsp_wo_GO__3

..
usp_id; int
}



footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_fk[]

=== PlantUML 1 1 ObjectRef

// tag::puml_entity_1_1_objectref[]
[plantuml, entity_1_1_objectref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:config.ftv_dwh_database.adoc[]" as config.ftv_dwh_database << IF >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject.adoc[]" as repo.RepoObject << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.generatorusp.adoc[]" as uspgenerator.GeneratorUsp << U >> {
  - **id** : (int)
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.generatorusp_parameterlist.adoc[]" as uspgenerator.GeneratorUsp_ParameterList << V >> {
  - **usp_id** : (int)
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.generatorusp_sqlusp_wo_go.adoc[]" as uspgenerator.GeneratorUsp_SqlUsp_wo_GO << V >> {
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.generatorusp_steplist.adoc[]" as uspgenerator.GeneratorUsp_StepList << V >> {
  --
}

config.ftv_dwh_database <.. uspgenerator.GeneratorUsp_SqlUsp_wo_GO
repo.RepoObject <.. uspgenerator.GeneratorUsp_SqlUsp_wo_GO
uspgenerator.GeneratorUsp <.. uspgenerator.GeneratorUsp_SqlUsp_wo_GO
uspgenerator.GeneratorUsp_ParameterList <.. uspgenerator.GeneratorUsp_SqlUsp_wo_GO
uspgenerator.GeneratorUsp_StepList <.. uspgenerator.GeneratorUsp_SqlUsp_wo_GO

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_objectref[]

=== PlantUML 30 0 ObjectRef

// tag::puml_entity_30_0_objectref[]
[plantuml, entity_30_0_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:config.ftv_dwh_database.adoc[]" as config.ftv_dwh_database << IF >> {
  --
}

entity "puml-link:dhw:sqldb:config.ftv_get_parameter_value.adoc[]" as config.ftv_get_parameter_value << IF >> {
  --
}

entity "puml-link:dhw:sqldb:config.parameter.adoc[]" as config.Parameter << U >> {
  - **Parameter_name** : (varchar(100))
  - **sub_Parameter** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:configt.parameter_default.adoc[]" as configT.Parameter_default << V >> {
  - **Parameter_name** : (varchar(52))
  - **sub_Parameter** : (nvarchar(26))
  --
}

entity "puml-link:dhw:sqldb:property.external_repoobjectproperty.adoc[]" as property.external_RepoObjectProperty << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.propertyname_repoobject.adoc[]" as property.PropertyName_RepoObject << V >> {
  **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.propertyname_repoobject_t.adoc[]" as property.PropertyName_RepoObject_T << U >> {
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty.adoc[]" as property.RepoObjectProperty << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty_external_src.adoc[]" as property.RepoObjectProperty_external_src << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty_external_tgt.adoc[]" as property.RepoObjectProperty_external_tgt << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty_selectedpropertyname_split.adoc[]" as property.RepoObjectProperty_SelectedPropertyName_split << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference.adoc[]" as reference.additional_Reference << U >> {
  # **tik_hash_c** : (nvarchar(32))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_from_properties_src.adoc[]" as reference.additional_Reference_from_properties_src << V >> {
  **referenced_AntoraComponent** : (nvarchar(max))
  **referenced_AntoraModule** : (nvarchar(max))
  **referenced_Schema** : (nvarchar(max))
  **referenced_Object** : (nvarchar(max))
  **referenced_Column** : (nvarchar(max))
  **referencing_AntoraComponent** : (nvarchar(max))
  **referencing_AntoraModule** : (nvarchar(max))
  **referencing_Schema** : (nvarchar(max))
  **referencing_Object** : (nvarchar(max))
  **referencing_Column** : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_from_properties_tgt.adoc[]" as reference.additional_Reference_from_properties_tgt << V >> {
  - **referenced_AntoraComponent** : (nvarchar(128))
  - **referenced_AntoraModule** : (nvarchar(128))
  - **referenced_Schema** : (nvarchar(128))
  - **referenced_Object** : (nvarchar(128))
  **referenced_Column** : (nvarchar(128))
  - **referencing_AntoraComponent** : (nvarchar(128))
  - **referencing_AntoraModule** : (nvarchar(128))
  - **referencing_Schema** : (nvarchar(128))
  - **referencing_Object** : (nvarchar(128))
  **referencing_Column** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_from_ssas_src.adoc[]" as reference.additional_Reference_from_ssas_src << V >> {
  **referenced_AntoraComponent** : (nvarchar(128))
  **referenced_AntoraModule** : (nvarchar(128))
  **referenced_Schema** : (nvarchar(max))
  **referenced_Object** : (nvarchar(max))
  **referenced_Column** : (nvarchar(500))
  **referencing_AntoraComponent** : (nvarchar(max))
  **referencing_AntoraModule** : (nvarchar(max))
  - **referencing_Schema** : (nvarchar(128))
  - **referencing_Object** : (nvarchar(128))
  **referencing_Column** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_from_ssas_tgt.adoc[]" as reference.additional_Reference_from_ssas_tgt << V >> {
  - **referenced_AntoraComponent** : (nvarchar(128))
  - **referenced_AntoraModule** : (nvarchar(128))
  - **referenced_Schema** : (nvarchar(128))
  - **referenced_Object** : (nvarchar(128))
  **referenced_Column** : (nvarchar(128))
  - **referencing_AntoraComponent** : (nvarchar(128))
  - **referencing_AntoraModule** : (nvarchar(128))
  - **referencing_Schema** : (nvarchar(128))
  - **referencing_Object** : (nvarchar(128))
  **referencing_Column** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_is_external.adoc[]" as reference.additional_Reference_is_external << V >> {
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_object.adoc[]" as reference.additional_Reference_Object << V >> {
  - **AntoraComponent** : (nvarchar(128))
  - **AntoraModule** : (nvarchar(128))
  - **SchemaName** : (nvarchar(128))
  - **ObjectName** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_object_t.adoc[]" as reference.additional_Reference_Object_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_wo_columns_from_properties_src.adoc[]" as reference.additional_Reference_wo_columns_from_properties_src << V >> {
  **referenced_AntoraComponent** : (nvarchar(max))
  **referenced_AntoraModule** : (nvarchar(max))
  **referenced_Schema** : (nvarchar(max))
  **referenced_Object** : (nvarchar(max))
  **referencing_AntoraComponent** : (nvarchar(max))
  **referencing_AntoraModule** : (nvarchar(max))
  **referencing_Schema** : (nvarchar(max))
  **referencing_Object** : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_wo_columns_from_properties_tgt.adoc[]" as reference.additional_Reference_wo_columns_from_properties_tgt << V >> {
  - **referenced_AntoraComponent** : (nvarchar(128))
  - **referenced_AntoraModule** : (nvarchar(128))
  - **referenced_Schema** : (nvarchar(128))
  - **referenced_Object** : (nvarchar(128))
  - **referencing_AntoraComponent** : (nvarchar(128))
  - **referencing_AntoraModule** : (nvarchar(128))
  - **referencing_Schema** : (nvarchar(128))
  - **referencing_Object** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject.adoc[]" as repo.RepoObject << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_external_src.adoc[]" as repo.RepoObject_external_src << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_external_tgt.adoc[]" as repo.RepoObject_external_tgt << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_ssas_src.adoc[]" as repo.RepoObject_SSAS_src << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_ssas_tgt.adoc[]" as repo.RepoObject_SSAS_tgt << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.reposchema.adoc[]" as repo.RepoSchema << U >> {
  - **RepoSchema_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:repo.reposchema_ssas_src.adoc[]" as repo.RepoSchema_ssas_src << V >> {
  - **RepoSchema_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:repo.reposchema_ssas_tgt.adoc[]" as repo.RepoSchema_ssas_tgt << V >> {
  - **RepoSchema_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:ssas.additional_reference_step1.adoc[]" as ssas.additional_Reference_step1 << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json.adoc[]" as ssas.model_json << U >> {
  - **databasename** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_10.adoc[]" as ssas.model_json_10 << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_20.adoc[]" as ssas.model_json_20 << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_201_descriptions_multiline.adoc[]" as ssas.model_json_201_descriptions_multiline << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_2011_descriptions_stragg.adoc[]" as ssas.model_json_2011_descriptions_StrAgg << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31_tables.adoc[]" as ssas.model_json_31_tables << V >> {
  - **databasename** : (nvarchar(128))
  **tables_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31_tables_t.adoc[]" as ssas.model_json_31_tables_T << U >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_311_tables_columns.adoc[]" as ssas.model_json_311_tables_columns << V >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  **tables_columns_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_311_tables_columns_t.adoc[]" as ssas.model_json_311_tables_columns_T << U >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  - **tables_columns_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_313_tables_partitions.adoc[]" as ssas.model_json_313_tables_partitions << V >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  **tables_partitions_name** : (nvarchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_3131_tables_partitions_source.adoc[]" as ssas.model_json_3131_tables_partitions_source << V >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  **tables_partitions_name** : (nvarchar(500))
  **tables_partitions_source_name** : (nvarchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31311_tables_partitions_source_posfrom.adoc[]" as ssas.model_json_31311_tables_partitions_source_PosFrom << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_313111_tables_partitions_source_stringfrom.adoc[]" as ssas.model_json_313111_tables_partitions_source_StringFrom << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_3131111_tables_partitions_source_posdot.adoc[]" as ssas.model_json_3131111_tables_partitions_source_PosDot << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31311111_tables_partitions_source_part123.adoc[]" as ssas.model_json_31311111_tables_partitions_source_Part123 << V >> {
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_33_datasources.adoc[]" as ssas.model_json_33_dataSources << V >> {
  - **databasename** : (nvarchar(128))
  **dataSources_name** : (nvarchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_33_datasources_t.adoc[]" as ssas.model_json_33_dataSources_T << U >> {
  - **databasename** : (nvarchar(128))
  - **dataSources_name** : (nvarchar(500))
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.ftv_generatoruspstep_sql.adoc[]" as uspgenerator.ftv_GeneratorUspStep_sql << IF >> {
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.ftv_generatoruspstep_tree.adoc[]" as uspgenerator.ftv_GeneratorUspStep_tree << IF >> {
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.generatorusp.adoc[]" as uspgenerator.GeneratorUsp << U >> {
  - **id** : (int)
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.generatorusp_parameterlist.adoc[]" as uspgenerator.GeneratorUsp_ParameterList << V >> {
  - **usp_id** : (int)
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.generatorusp_sqlusp_wo_go.adoc[]" as uspgenerator.GeneratorUsp_SqlUsp_wo_GO << V >> {
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.generatorusp_steplist.adoc[]" as uspgenerator.GeneratorUsp_StepList << V >> {
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.generatoruspparameter.adoc[]" as uspgenerator.GeneratorUspParameter << U >> {
  - **id** : (int)
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.generatoruspstep.adoc[]" as uspgenerator.GeneratorUspStep << U >> {
  - **id** : (int)
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.generatoruspstep_sql.adoc[]" as uspgenerator.GeneratorUspStep_Sql << V >> {
  - **usp_id** : (int)
  **Number** : (int)
  --
}

config.ftv_dwh_database <.. uspgenerator.GeneratorUsp_SqlUsp_wo_GO
config.ftv_get_parameter_value <.. reference.additional_Reference_is_external
config.ftv_get_parameter_value <.. repo.RepoObject_external_src
config.ftv_get_parameter_value <.. ssas.additional_Reference_step1
config.Parameter <.. config.ftv_dwh_database
config.Parameter <.. config.ftv_get_parameter_value
config.Parameter <.. property.PropertyName_RepoObject
configT.Parameter_default <.. config.Parameter
property.external_RepoObjectProperty <.. property.RepoObjectProperty_external_src
property.PropertyName_RepoObject <.. property.PropertyName_RepoObject_T
property.PropertyName_RepoObject_T <.. property.RepoObjectProperty_external_tgt
property.RepoObjectProperty <.. property.PropertyName_RepoObject
property.RepoObjectProperty <.. property.RepoObjectProperty_SelectedPropertyName_split
property.RepoObjectProperty_external_src <.. property.RepoObjectProperty_external_tgt
property.RepoObjectProperty_external_tgt <.. property.RepoObjectProperty
property.RepoObjectProperty_SelectedPropertyName_split <.. reference.additional_Reference_from_properties_src
property.RepoObjectProperty_SelectedPropertyName_split <.. reference.additional_Reference_wo_columns_from_properties_src
reference.additional_Reference <.. reference.additional_Reference_is_external
reference.additional_Reference_from_properties_src <.. reference.additional_Reference_from_properties_tgt
reference.additional_Reference_from_properties_tgt <.. reference.additional_Reference
reference.additional_Reference_from_ssas_src <.. reference.additional_Reference_from_ssas_tgt
reference.additional_Reference_from_ssas_tgt <.. reference.additional_Reference
reference.additional_Reference_is_external <.. reference.additional_Reference_Object
reference.additional_Reference_Object <.. reference.additional_Reference_Object_T
reference.additional_Reference_Object_T <.. repo.RepoObject_external_src
reference.additional_Reference_wo_columns_from_properties_src <.. reference.additional_Reference_wo_columns_from_properties_tgt
reference.additional_Reference_wo_columns_from_properties_tgt <.. reference.additional_Reference
repo.RepoObject <.. property.RepoObjectProperty_external_tgt
repo.RepoObject <.. repo.RepoObject_external_src
repo.RepoObject <.. uspgenerator.GeneratorUsp_SqlUsp_wo_GO
repo.RepoObject_external_src <.. repo.RepoObject_external_tgt
repo.RepoObject_external_tgt <.. repo.RepoObject
repo.RepoObject_SSAS_src <.. repo.RepoObject_SSAS_tgt
repo.RepoObject_SSAS_tgt <.. repo.RepoObject
repo.RepoSchema <.. repo.RepoObject_SSAS_src
repo.RepoSchema_ssas_src <.. repo.RepoSchema_ssas_tgt
repo.RepoSchema_ssas_tgt <.. repo.RepoSchema
ssas.additional_Reference_step1 <.. reference.additional_Reference_from_ssas_src
ssas.model_json <.. ssas.model_json_10
ssas.model_json_10 <.. ssas.model_json_20
ssas.model_json_20 <.. repo.RepoSchema_ssas_src
ssas.model_json_20 <.. ssas.model_json_201_descriptions_multiline
ssas.model_json_20 <.. ssas.model_json_31_tables
ssas.model_json_20 <.. ssas.model_json_33_dataSources
ssas.model_json_201_descriptions_multiline <.. ssas.model_json_2011_descriptions_StrAgg
ssas.model_json_2011_descriptions_StrAgg <.. repo.RepoSchema_ssas_src
ssas.model_json_31_tables <.. ssas.model_json_31_tables_T
ssas.model_json_31_tables_T <.. repo.RepoObject_SSAS_src
ssas.model_json_31_tables_T <.. ssas.model_json_311_tables_columns
ssas.model_json_31_tables_T <.. ssas.model_json_313_tables_partitions
ssas.model_json_311_tables_columns <.. ssas.model_json_311_tables_columns_T
ssas.model_json_311_tables_columns_T <.. ssas.additional_Reference_step1
ssas.model_json_313_tables_partitions <.. ssas.model_json_3131_tables_partitions_source
ssas.model_json_3131_tables_partitions_source <.. ssas.model_json_31311_tables_partitions_source_PosFrom
ssas.model_json_31311_tables_partitions_source_PosFrom <.. ssas.model_json_313111_tables_partitions_source_StringFrom
ssas.model_json_313111_tables_partitions_source_StringFrom <.. ssas.model_json_3131111_tables_partitions_source_PosDot
ssas.model_json_3131111_tables_partitions_source_PosDot <.. ssas.model_json_31311111_tables_partitions_source_Part123
ssas.model_json_31311111_tables_partitions_source_Part123 <.. ssas.additional_Reference_step1
ssas.model_json_33_dataSources <.. ssas.model_json_33_dataSources_T
ssas.model_json_33_dataSources_T <.. ssas.additional_Reference_step1
uspgenerator.ftv_GeneratorUspStep_sql <.. uspgenerator.GeneratorUspStep_Sql
uspgenerator.ftv_GeneratorUspStep_tree <.. uspgenerator.GeneratorUspStep_Sql
uspgenerator.GeneratorUsp <.. uspgenerator.GeneratorUsp_SqlUsp_wo_GO
uspgenerator.GeneratorUsp <.. uspgenerator.GeneratorUspStep_Sql
uspgenerator.GeneratorUsp_ParameterList <.. uspgenerator.GeneratorUsp_SqlUsp_wo_GO
uspgenerator.GeneratorUsp_StepList <.. uspgenerator.GeneratorUsp_SqlUsp_wo_GO
uspgenerator.GeneratorUspParameter <.. uspgenerator.GeneratorUsp_ParameterList
uspgenerator.GeneratorUspStep <.. uspgenerator.ftv_GeneratorUspStep_sql
uspgenerator.GeneratorUspStep <.. uspgenerator.ftv_GeneratorUspStep_tree
uspgenerator.GeneratorUspStep <.. uspgenerator.GeneratorUspStep_Sql
uspgenerator.GeneratorUspStep_Sql <.. uspgenerator.GeneratorUsp_StepList

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_30_0_objectref[]

=== PlantUML 0 30 ObjectRef

// tag::puml_entity_0_30_objectref[]
[plantuml, entity_0_30_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:uspgenerator.generatorusp_sqlusp_wo_go.adoc[]" as uspgenerator.GeneratorUsp_SqlUsp_wo_GO << V >> {
  --
}



footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_0_30_objectref[]

=== PlantUML 1 1 ColumnRef

// tag::puml_entity_1_1_colref[]
[plantuml, entity_1_1_colref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:config.ftv_dwh_database.adoc[]" as config.ftv_dwh_database << IF >> {
  dwh_database_id : (smallint)
  dwh_database_name : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject.adoc[]" as repo.RepoObject << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  external_AntoraComponent : (nvarchar(128))
  external_AntoraModule : (nvarchar(128))
  has_execution_plan_issue : (bit)
  has_get_referenced_issue : (bit)
  indent_sql_modules_definition : (tinyint)
  Inheritance_Source_fullname : (nvarchar(261))
  Inheritance_StringAggSeparatorSql : (nvarchar(4000))
  InheritanceDefinition : (nvarchar(4000))
  InheritanceType : (tinyint)
  - is_DocsExclude : (bit)
  - is_external : (bit)
  is_repo_managed : (bit)
  is_required_ObjectMerge : (bit)
  - is_ssas : (bit)
  is_SysObject_missing : (bit)
  - modify_dt : (datetime)
  pk_index_guid : (uniqueidentifier)
  pk_IndexPatternColumnName_new : (nvarchar(4000))
  Repo_history_table_guid : (uniqueidentifier)
  Repo_temporal_type : (tinyint)
  - RepoObject_name : (nvarchar(128))
  RepoObject_Referencing_Count : (int)
  - RepoObject_schema_name : (nvarchar(128))
  - RepoObject_type : (char(2))
  SysObject_id : (int)
  SysObject_modify_date : (datetime)
  - SysObject_name : (nvarchar(128))
  - SysObject_parent_object_id : (int)
  - SysObject_schema_name : (nvarchar(128))
  SysObject_type : (char(2))
  ~ has_different_sys_names : (bit)
  # is_RepoObject_name_uniqueidentifier : (int)
  # is_SysObject_name_uniqueidentifier : (int)
  ~ node_id : (bigint)
  # RepoObject_fullname : (nvarchar(261))
  # RepoObject_fullname2 : (nvarchar(257))
  # SysObject_fullname : (nvarchar(261))
  # SysObject_fullname2 : (nvarchar(257))
  ~ SysObject_query_sql : (nvarchar(406))
  ~ usp_persistence_fullname : (nvarchar(273))
  # usp_persistence_fullname2 : (nvarchar(269))
  # usp_persistence_name : (nvarchar(140))
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.generatorusp.adoc[]" as uspgenerator.GeneratorUsp << U >> {
  - **id** : (int)
  - has_logging : (tinyint)
  usp_Description : (nvarchar(4000))
  usp_Examples : (nvarchar(4000))
  - usp_name : (nvarchar(128))
  - usp_schema : (nvarchar(128))
  # usp_fullname : (nvarchar(261))
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.generatorusp_parameterlist.adoc[]" as uspgenerator.GeneratorUsp_ParameterList << V >> {
  - **usp_id** : (int)
  ParameterList : (nvarchar(max))
  ParameterListLogging : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.generatorusp_sqlusp_wo_go.adoc[]" as uspgenerator.GeneratorUsp_SqlUsp_wo_GO << V >> {
  - AdocUspSteps : (nvarchar(max))
  - has_logging : (tinyint)
  MS_Description : (nvarchar(4000))
  RepoObject_guid : (uniqueidentifier)
  SqlStepList : (nvarchar(max))
  - SqlUsp_wo_GO : (nvarchar(max))
  usp_Description : (nvarchar(4000))
  - usp_fullname : (nvarchar(261))
  - usp_id : (int)
  - usp_name : (nvarchar(128))
  - usp_schema : (nvarchar(128))
  - UspExamples : (nvarchar(4000))
  UspParameters : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.generatorusp_steplist.adoc[]" as uspgenerator.GeneratorUsp_StepList << V >> {
  AdocStepList : (nvarchar(max))
  StepList : (nvarchar(max))
  - usp_id : (int)
  --
}

config.ftv_dwh_database <.. uspgenerator.GeneratorUsp_SqlUsp_wo_GO
repo.RepoObject <.. uspgenerator.GeneratorUsp_SqlUsp_wo_GO
uspgenerator.GeneratorUsp <.. uspgenerator.GeneratorUsp_SqlUsp_wo_GO
uspgenerator.GeneratorUsp_ParameterList <.. uspgenerator.GeneratorUsp_SqlUsp_wo_GO
uspgenerator.GeneratorUsp_StepList <.. uspgenerator.GeneratorUsp_SqlUsp_wo_GO
"repo.RepoObject::RepoObject_guid" <-- "uspgenerator.GeneratorUsp_SqlUsp_wo_GO::RepoObject_guid"
"uspgenerator.GeneratorUsp::has_logging" <-- "uspgenerator.GeneratorUsp_SqlUsp_wo_GO::has_logging"
"uspgenerator.GeneratorUsp::id" <-- "uspgenerator.GeneratorUsp_SqlUsp_wo_GO::usp_id"
"uspgenerator.GeneratorUsp::usp_Description" <-- "uspgenerator.GeneratorUsp_SqlUsp_wo_GO::MS_Description"
"uspgenerator.GeneratorUsp::usp_Description" <-- "uspgenerator.GeneratorUsp_SqlUsp_wo_GO::usp_Description"
"uspgenerator.GeneratorUsp::usp_fullname" <-- "uspgenerator.GeneratorUsp_SqlUsp_wo_GO::usp_fullname"
"uspgenerator.GeneratorUsp::usp_name" <-- "uspgenerator.GeneratorUsp_SqlUsp_wo_GO::usp_name"
"uspgenerator.GeneratorUsp::usp_schema" <-- "uspgenerator.GeneratorUsp_SqlUsp_wo_GO::usp_schema"
"uspgenerator.GeneratorUsp_ParameterList::ParameterList" <-- "uspgenerator.GeneratorUsp_SqlUsp_wo_GO::UspParameters"
"uspgenerator.GeneratorUsp_StepList::StepList" <-- "uspgenerator.GeneratorUsp_SqlUsp_wo_GO::SqlStepList"

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_colref[]


== sql_modules_definition

// tag::sql_modules_definition[]
[%collapsible]
=======
[source,sql,numbered,indent=0]
----
/*
[SqlUsp] contains the final code for the usp, defined in
- [repo].[GeneratorUsp]
- [repo].[GeneratorUspParameter]
- [repo].[GeneratorUspStep]

USE [...] and GO are removed to be used by AnalyticsCreator in Post-Creation-Scripts
*/
create   View [uspgenerator].[GeneratorUsp_SqlUsp_wo_GO]
As
Select
    usp_id         = u.id
  , SqlUsp_wo_GO   = Concat (
                              --  'USE  ['
                              --, dwhdb.dwh_database_name
                              --, ']'
                              --, Char ( 13 ) + Char ( 10 )
                              --, 'GO'
                              --, Char ( 13 ) + Char ( 10 )
                              ''  
                              , '/*'
                              , Char ( 13 ) + Char ( 10 )
                              , 'code of this procedure is managed in the dhw repository. Do not modify manually.'
                              , Char ( 13 ) + Char ( 10 )
                              , 'Use [uspgenerator].[GeneratorUsp], [uspgenerator].[GeneratorUspParameter], [uspgenerator].[GeneratorUspStep], [uspgenerator].[GeneratorUsp_SqlUsp]'
                              , Char ( 13 ) + Char ( 10 )
                              , '*/'
                              , Char ( 13 ) + Char ( 10 )
                              , 'CREATE OR ALTER PROCEDURE '
                              , u.usp_fullname
                              , Char ( 13 ) + Char ( 10 )
                              , ParameterList.ParameterList
                              , Case u.has_logging
                                    When 1
                                        Then
                                        Concat (
                                                   Iif(ParameterList.ParameterList <> ''
                                               , Char ( 13 ) + Char ( 10 ) + ',' + Char ( 13 ) + Char ( 10 )
                                               , '')
                                                 , '----keep the code between logging parameters and "START" unchanged!
---- parameters, used for logging; you don''t need to care about them, but you can use them, wenn calling from SSIS or in your workflow to log the context of the procedure call
  @execution_instance_guid UNIQUEIDENTIFIER = NULL --SSIS system variable ExecutionInstanceGUID could be used, any other unique guid is also fine. If NULL, then NEWID() is used to create one
, @ssis_execution_id BIGINT = NULL --only SSIS system variable ServerExecutionID should be used, or any other consistent number system, do not mix different number systems
, @sub_execution_id INT = NULL --in case you log some sub_executions, for example in SSIS loops or sub packages
, @parent_execution_log_id BIGINT = NULL --in case a sup procedure is called, the @current_execution_log_id of the parent procedure should be propagated here. It allowes call stack analyzing
'
                                               )
                                End --[u].[has_logging]
                              , '
AS
BEGIN
'
                              , Case u.has_logging
                                    When 1
                                        Then
                                        Concat (
                                                   'DECLARE
 --
   @current_execution_log_id BIGINT --this variable should be filled only once per procedure call, it contains the first logging call for the step ''start''.
 , @current_execution_guid UNIQUEIDENTIFIER = NEWID() --a unique guid for any procedure call. It should be propagated to sub procedures using "@parent_execution_log_id = @current_execution_log_id"
 , @source_object NVARCHAR(261) = NULL --use it like ''[schema].[object]'', this allows data flow vizualizatiuon (include square brackets)
 , @target_object NVARCHAR(261) = NULL --use it like ''[schema].[object]'', this allows data flow vizualizatiuon (include square brackets)
 , @proc_id INT = @@procid
 , @proc_schema_name NVARCHAR(128) = OBJECT_SCHEMA_NAME(@@procid) --schema ande name of the current procedure should be automatically logged
 , @proc_name NVARCHAR(128) = OBJECT_NAME(@@procid)               --schema ande name of the current procedure should be automatically logged
 , @event_info NVARCHAR(MAX)
 , @step_id INT = 0
 , @step_name NVARCHAR(1000) = NULL
 , @rows INT

--[event_info] get''s only the information about the "outer" calling process
--wenn the procedure calls sub procedures, the [event_info] will not change
SET @event_info = (
  SELECT TOP 1 [event_info]
  FROM sys.dm_exec_input_buffer(@@spid, CURRENT_REQUEST_ID())
  ORDER BY [event_info]
  )

IF @execution_instance_guid IS NULL
 SET @execution_instance_guid = NEWID();
--
--SET @rows = @@ROWCOUNT;
SET @step_id = @step_id + 1
SET @step_name = ''start''
SET @source_object = NULL
SET @target_object = NULL

EXEC logs.usp_ExecutionLog_insert
 --these parameters should be the same for all logging execution
   @execution_instance_guid = @execution_instance_guid
 , @ssis_execution_id = @ssis_execution_id
 , @sub_execution_id = @sub_execution_id
 , @parent_execution_log_id = @parent_execution_log_id
 , @current_execution_guid = @current_execution_guid
 , @proc_id = @proc_id
 , @proc_schema_name = @proc_schema_name
 , @proc_name = @proc_name
 , @event_info = @event_info
 --the following parameters are individual for each call
 , @step_id = @step_id --@step_id should be incremented before each call
 , @step_name = @step_name --assign individual step names for each call
 --only the "start" step should return the log id into @current_execution_log_id
 --all other calls should not overwrite @current_execution_log_id
 , @execution_log_id = @current_execution_log_id OUTPUT
----you can log the content of your own parameters, do this only in the start-step
----data type is sql_variant
'
                                                 , ParameterList.ParameterListLogging
                                                 , '
--
PRINT '''
                                                 , u.usp_fullname
                                                 , '''
--keep the code between logging parameters and "START" unchanged!
--
----START
--
----- start here with your own code
--
'
                                               )
                                End --[u].[has_logging]
                              , StepList.StepList
                              , Case u.has_logging
                                    When 1
                                        Then
                                        '
--
--finish your own code here
--keep the code between "END" and the end of the procedure unchanged!
--
--END
--
--SET @rows = @@ROWCOUNT
SET @step_id = @step_id + 1
SET @step_name = ''end''
SET @source_object = NULL
SET @target_object = NULL

EXEC logs.usp_ExecutionLog_insert
   @execution_instance_guid = @execution_instance_guid
 , @ssis_execution_id = @ssis_execution_id
 , @sub_execution_id = @sub_execution_id
 , @parent_execution_log_id = @parent_execution_log_id
 , @current_execution_guid = @current_execution_guid
 , @proc_id = @proc_id
 , @proc_schema_name = @proc_schema_name
 , @proc_name = @proc_name
 , @event_info = @event_info
 , @step_id = @step_id
 , @step_name = @step_name
 , @source_object = @source_object
 , @target_object = @target_object
'
                                End --[u].[has_logging]
                              , '
END
'
                            )
  , AdocUspSteps   = Concat (
                                '.Steps in '
                              , u.usp_fullname
                              , Char ( 13 ) + Char ( 10 )
                              , '[cols="d,15a,d"]'
                              , Char ( 13 ) + Char ( 10 )
                              , '|==='
                              , Char ( 13 ) + Char ( 10 )
                              , '|'
                              , 'Number'
                              , '|'
                              , 'Name (Action, Source, Target)'
                              , '|'
                              , 'Parent'
                              , Char ( 13 ) + Char ( 10 )
                              , Char ( 13 ) + Char ( 10 )
                              , StepList.AdocStepList
                              , '|==='
                              , Char ( 13 ) + Char ( 10 )
                            )
  , MS_Description = u.usp_Description
  , u.has_logging
  , u.usp_Description
  , u.usp_fullname
  , u.usp_name
  , u.usp_schema
  , UspExamples    = IsNull ( u.usp_Examples, 'EXEC ' + u.usp_fullname )
  , UspParameters  = ParameterList.ParameterList
  , SqlStepList    = StepList.StepList
  , ro.RepoObject_guid
From
    uspgenerator.GeneratorUsp                   As u
    Left Join
        uspgenerator.GeneratorUsp_ParameterList As ParameterList
            On
            ParameterList.usp_id = u.id

    Left Join
        uspgenerator.GeneratorUsp_StepList      As StepList
            On
            StepList.usp_id = u.id

    Left Join
        repo.RepoObject                         As ro
            On
            ro.RepoObject_fullname = u.usp_fullname
    Cross Join config.ftv_dwh_database ()       As dwhdb

----
=======
// end::sql_modules_definition[]


