// tag::HeaderFullDisplayName[]
= uspgenerator.usp_copy_procedure - P
// end::HeaderFullDisplayName[]

== existing_properties

// tag::existing_properties[]

:ExistsProperty--adocuspsteps:
:ExistsProperty--antorareferencedlist:
:ExistsProperty--exampleusage:
:ExistsProperty--is_repo_managed:
:ExistsProperty--is_ssas:
:ExistsProperty--referencedobjectlist:
:ExistsProperty--uspgenerator_usp_id:
:ExistsProperty--uspparameters:
:ExistsProperty--sql_modules_definition:
:ExistsProperty--AntoraParameterList:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
F11EA651-464D-EC11-8531-A81E8446D5B0
// end::RepoObject_guid[]

== RepoObject_FullDisplayName2

// tag::RepoObject_FullDisplayName2[]
uspgenerator.usp_copy_procedure
// end::RepoObject_FullDisplayName2[]

== SysObject_type

// tag::SysObject_type[]
P 
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
stored procedure
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
891202275
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2022-09-05 18:23:37
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]

// end::AntoraColumnDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]

// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

// end::AntoraIndexList[]

== AntoraMeasureDetails

// tag::AntoraMeasureDetails[]

// end::AntoraMeasureDetails[]

== AntoraMeasureDescriptions



== AntoraParameterList

// tag::AntoraParameterList[]
* @source_usp_id (int)
* @target_usp_schema (nvarchar(128))
* @target_usp_name (nvarchar(128))
* @execution_instance_guid (uniqueidentifier)
* @ssis_execution_id (bigint)
* @sub_execution_id (int)
* @parent_execution_log_id (bigint)
// end::AntoraParameterList[]

== AntoraXrefCulturesList

// tag::AntoraXrefCulturesList[]
* xref:dhw:sqldb:uspgenerator.usp_copy_procedure.adoc[] - 
// end::AntoraXrefCulturesList[]

== cultures_count

// tag::cultures_count[]
1
// end::cultures_count[]

== Other tags

source: property.RepoObjectProperty_cross As rop_cross


=== additional_reference_csv

// tag::additional_reference_csv[]

// end::additional_reference_csv[]


=== AdocUspSteps

// tag::adocuspsteps[]
.Steps in [uspgenerator].[usp_copy_procedure]
[cols="d,15a,d"]
|===
|Number|Name (Action, Source, Target)|Parent

|300
|
*copy [uspgenerator].[GeneratorUsp]*

* i
* [repo].[GeneratorUsp]
* [repo].[GeneratorUsp]


.Statement
[%collapsible]
=====
[source,sql,numbered]
----
Declare @target_usp_id Int

Insert Into uspgenerator.GeneratorUsp
(
    usp_schema
  , usp_name
  , has_logging
  , usp_Description
  , usp_Examples
)
Select
    usp_schema = IsNull ( @target_usp_schema, usp_schema )
  , usp_name   = IsNull ( @target_usp_name, usp_name + '_copy' )
  , has_logging
  , usp_Description
  , usp_Examples
From
    uspgenerator.GeneratorUsp
Where
    ( id = @source_usp_id )

Select
    @target_usp_id = Scope_Identity ()
----
=====

|


|400
|
*check for inserted procedure*

* `IF @target_usp_id Is Null`
* [repo].[IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing]


.Statement
[%collapsible]
=====
[source,sql,numbered]
----
@target_usp_id Is Null
----
=====

|


|410
|
*ERROR 50110: @target_usp_id empty, nothing was inserted*



.Statement
[%collapsible]
=====
[source,sql,numbered]
----
 THROW 50110
  , '@target_usp_id empty, nothing was inserted'
  , 1;

----
=====

|400


|500
|
*copy [uspgenerator].[GeneratorUspParameter]*

* i
* [uspgenerator].[GeneratorUspParameter]
* [uspgenerator].[GeneratorUspParameter]


.Statement
[%collapsible]
=====
[source,sql,numbered]
----
Insert Into uspgenerator.GeneratorUspParameter
(
    usp_id
  , Number
  , Name
  , UserTypeFullname
  , is_inactive
  , is_out
  , has_DefaultValue
  , DefaultValue
  , Description
)
Select
    usp_id = @target_usp_id
  , S.Number
  , S.Name
  , S.UserTypeFullname
  , S.is_inactive
  , S.is_out
  , S.has_DefaultValue
  , S.DefaultValue
  , S.Description
From
    uspgenerator.GeneratorUspParameter As S
Where
    S.usp_id = @source_usp_id
----
=====

|


|600
|
*copy [uspgenerator].[GeneratorUspStep]*

* i
* [uspgenerator].[GeneratorUspStep]
* [uspgenerator].[GeneratorUspStep]


.Statement
[%collapsible]
=====
[source,sql,numbered]
----
Insert Into uspgenerator.GeneratorUspStep
(
    usp_id
  , Number
  , Parent_Number
  , Name
  , has_logging
  , is_condition
  , is_inactive
  , is_SubProcedure
  , Statement
  , log_source_object
  , log_target_object
  , log_flag_InsertUpdateDelete
  , Description
  , info_01
  , info_02
  , info_03
  , info_04
  , info_05
  , info_06
  , info_07
  , info_08
  , info_09
)
Select
    usp_id = @target_usp_id
  , S.Number
  , S.Parent_Number
  , S.Name
  , S.has_logging
  , S.is_condition
  , S.is_inactive
  , S.is_SubProcedure
  , S.Statement
  , S.log_source_object
  , S.log_target_object
  , S.log_flag_InsertUpdateDelete
  , S.Description
  , S.info_01
  , S.info_02
  , S.info_03
  , S.info_04
  , S.info_05
  , S.info_06
  , S.info_07
  , S.info_08
  , S.info_09
From
    uspgenerator.GeneratorUspStep As S
Where
    ( usp_id = @source_usp_id )
----
=====

|

|===

// end::adocuspsteps[]


=== AntoraReferencedList

// tag::antorareferencedlist[]
* xref:dhw:sqldb:logs.usp_executionlog_insert.adoc[]
* xref:dhw:sqldb:uspgenerator.generatorusp.adoc[]
* xref:dhw:sqldb:uspgenerator.generatoruspparameter.adoc[]
* xref:dhw:sqldb:uspgenerator.generatoruspstep.adoc[]
// end::antorareferencedlist[]


=== AntoraReferencingList

// tag::antorareferencinglist[]

// end::antorareferencinglist[]


=== Description

// tag::description[]

// end::description[]


=== exampleUsage

// tag::exampleusage[]
EXEC [uspgenerator].[usp_copy_procedure]
// end::exampleusage[]


=== exampleUsage_2

// tag::exampleusage_2[]

// end::exampleusage_2[]


=== exampleUsage_3

// tag::exampleusage_3[]

// end::exampleusage_3[]


=== exampleUsage_4

// tag::exampleusage_4[]

// end::exampleusage_4[]


=== exampleUsage_5

// tag::exampleusage_5[]

// end::exampleusage_5[]


=== exampleWrong_Usage

// tag::examplewrong_usage[]

// end::examplewrong_usage[]


=== has_execution_plan_issue

// tag::has_execution_plan_issue[]

// end::has_execution_plan_issue[]


=== has_get_referenced_issue

// tag::has_get_referenced_issue[]

// end::has_get_referenced_issue[]


=== has_history

// tag::has_history[]

// end::has_history[]


=== has_history_columns

// tag::has_history_columns[]

// end::has_history_columns[]


=== InheritanceType

// tag::inheritancetype[]

// end::inheritancetype[]


=== is_persistence

// tag::is_persistence[]

// end::is_persistence[]


=== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]

// end::is_persistence_check_duplicate_per_pk[]


=== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]

// end::is_persistence_check_for_empty_source[]


=== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]

// end::is_persistence_delete_changed[]


=== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]

// end::is_persistence_delete_missing[]


=== is_persistence_insert

// tag::is_persistence_insert[]

// end::is_persistence_insert[]


=== is_persistence_truncate

// tag::is_persistence_truncate[]

// end::is_persistence_truncate[]


=== is_persistence_update_changed

// tag::is_persistence_update_changed[]

// end::is_persistence_update_changed[]


=== is_repo_managed

// tag::is_repo_managed[]
0
// end::is_repo_managed[]


=== is_ssas

// tag::is_ssas[]
0
// end::is_ssas[]


=== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


=== MS_Description

// tag::ms_description[]

// end::ms_description[]


=== persistence_source_RepoObject_fullname

// tag::persistence_source_repoobject_fullname[]

// end::persistence_source_repoobject_fullname[]


=== persistence_source_RepoObject_fullname2

// tag::persistence_source_repoobject_fullname2[]

// end::persistence_source_repoobject_fullname2[]


=== persistence_source_RepoObject_guid

// tag::persistence_source_repoobject_guid[]

// end::persistence_source_repoobject_guid[]


=== persistence_source_RepoObject_xref

// tag::persistence_source_repoobject_xref[]

// end::persistence_source_repoobject_xref[]


=== pk_index_guid

// tag::pk_index_guid[]

// end::pk_index_guid[]


=== pk_IndexPatternColumnDatatype

// tag::pk_indexpatterncolumndatatype[]

// end::pk_indexpatterncolumndatatype[]


=== pk_IndexPatternColumnName

// tag::pk_indexpatterncolumnname[]

// end::pk_indexpatterncolumnname[]


=== pk_IndexSemanticGroup

// tag::pk_indexsemanticgroup[]

// end::pk_indexsemanticgroup[]


=== ReferencedObjectList

// tag::referencedobjectlist[]
* [logs].[usp_ExecutionLog_insert]
* [uspgenerator].[GeneratorUsp]
* [uspgenerator].[GeneratorUspParameter]
* [uspgenerator].[GeneratorUspStep]
// end::referencedobjectlist[]


=== usp_persistence_RepoObject_guid

// tag::usp_persistence_repoobject_guid[]

// end::usp_persistence_repoobject_guid[]


=== UspExamples

// tag::uspexamples[]

// end::uspexamples[]


=== uspgenerator_usp_id

// tag::uspgenerator_usp_id[]
139
// end::uspgenerator_usp_id[]


=== UspParameters

// tag::uspparameters[]
@source_usp_id int /* usp_id of the source procedure, you want to copy */
,@target_usp_schema NVARCHAR(128) = NULL /* usp_schema of the target procedure (the procedure to be created), if NULL, the source usp_schema will be used */
,@target_usp_name NVARCHAR(128) = NULL /* usp_schema of the target procedure (the procedure to be created), if NULL, the source usp_schema will be used with suffix _copy */
// end::uspparameters[]

== Boolean Attributes

source: property.RepoObjectProperty WHERE property_int = 1

// tag::boolean_attributes[]


// end::boolean_attributes[]

== PlantUML diagrams

=== PlantUML Entity

// tag::puml_entity[]
[plantuml, entity-{docname}, svg, subs=macros]
....
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:uspgenerator.usp_copy_procedure.adoc[]" as uspgenerator.usp_copy_procedure << P >> {
  --
}
....

// end::puml_entity[]

=== PlantUML Entity 1 1 FK

// tag::puml_entity_1_1_fk[]
[plantuml, entity_1_1_fk-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}





footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_fk[]

=== PlantUML 1 1 ObjectRef

// tag::puml_entity_1_1_objectref[]
[plantuml, entity_1_1_objectref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:logs.usp_executionlog_insert.adoc[]" as logs.usp_ExecutionLog_insert << P >> {
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.generatorusp.adoc[]" as uspgenerator.GeneratorUsp << U >> {
  - **id** : (int)
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.generatoruspparameter.adoc[]" as uspgenerator.GeneratorUspParameter << U >> {
  - **id** : (int)
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.generatoruspstep.adoc[]" as uspgenerator.GeneratorUspStep << U >> {
  - **id** : (int)
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.usp_copy_procedure.adoc[]" as uspgenerator.usp_copy_procedure << P >> {
  --
}

logs.usp_ExecutionLog_insert <.. uspgenerator.usp_copy_procedure
uspgenerator.GeneratorUsp <.. uspgenerator.usp_copy_procedure
uspgenerator.GeneratorUspParameter <.. uspgenerator.usp_copy_procedure
uspgenerator.GeneratorUspStep <.. uspgenerator.usp_copy_procedure

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_objectref[]

=== PlantUML 30 0 ObjectRef

// tag::puml_entity_30_0_objectref[]
[plantuml, entity_30_0_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:logs.executionlog.adoc[]" as logs.ExecutionLog << U >> {
  - **id** : (bigint)
  --
}

entity "puml-link:dhw:sqldb:logs.usp_executionlog_insert.adoc[]" as logs.usp_ExecutionLog_insert << P >> {
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.generatorusp.adoc[]" as uspgenerator.GeneratorUsp << U >> {
  - **id** : (int)
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.generatoruspparameter.adoc[]" as uspgenerator.GeneratorUspParameter << U >> {
  - **id** : (int)
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.generatoruspstep.adoc[]" as uspgenerator.GeneratorUspStep << U >> {
  - **id** : (int)
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.usp_copy_procedure.adoc[]" as uspgenerator.usp_copy_procedure << P >> {
  --
}

logs.ExecutionLog <.. logs.usp_ExecutionLog_insert
logs.usp_ExecutionLog_insert <.. uspgenerator.usp_copy_procedure
uspgenerator.GeneratorUsp <.. uspgenerator.usp_copy_procedure
uspgenerator.GeneratorUspParameter <.. uspgenerator.usp_copy_procedure
uspgenerator.GeneratorUspStep <.. uspgenerator.usp_copy_procedure

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_30_0_objectref[]

=== PlantUML 0 30 ObjectRef

// tag::puml_entity_0_30_objectref[]
[plantuml, entity_0_30_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:uspgenerator.usp_copy_procedure.adoc[]" as uspgenerator.usp_copy_procedure << P >> {
  --
}



footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_0_30_objectref[]

=== PlantUML 1 1 ColumnRef

// tag::puml_entity_1_1_colref[]
[plantuml, entity_1_1_colref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:logs.usp_executionlog_insert.adoc[]" as logs.usp_ExecutionLog_insert << P >> {
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.generatorusp.adoc[]" as uspgenerator.GeneratorUsp << U >> {
  - **id** : (int)
  - has_logging : (tinyint)
  usp_Description : (nvarchar(4000))
  usp_Examples : (nvarchar(4000))
  - usp_name : (nvarchar(128))
  - usp_schema : (nvarchar(128))
  # usp_fullname : (nvarchar(261))
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.generatoruspparameter.adoc[]" as uspgenerator.GeneratorUspParameter << U >> {
  - **id** : (int)
  DefaultValue : (nvarchar(max))
  Description : (nvarchar(4000))
  - has_DefaultValue : (tinyint)
  - is_inactive : (tinyint)
  - is_out : (tinyint)
  - Name : (nvarchar(128))
  - Number : (int)
  - UserTypeFullname : (nvarchar(128))
  - usp_id : (int)
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.generatoruspstep.adoc[]" as uspgenerator.GeneratorUspStep << U >> {
  - **id** : (int)
  Description : (nvarchar(4000))
  - has_logging : (tinyint)
  info_01 : (nvarchar(max))
  info_02 : (nvarchar(max))
  info_03 : (nvarchar(max))
  info_04 : (nvarchar(max))
  info_05 : (nvarchar(max))
  info_06 : (nvarchar(max))
  info_07 : (nvarchar(max))
  info_08 : (nvarchar(max))
  info_09 : (nvarchar(max))
  - is_condition : (tinyint)
  - is_inactive : (tinyint)
  - is_SubProcedure : (tinyint)
  log_flag_InsertUpdateDelete : (char(1))
  log_source_object : (nvarchar(261))
  log_target_object : (nvarchar(261))
  Name : (nvarchar(1000))
  - Number : (int)
  Parent_Number : (int)
  Statement : (nvarchar(max))
  - usp_id : (int)
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.usp_copy_procedure.adoc[]" as uspgenerator.usp_copy_procedure << P >> {
  --
}

logs.usp_ExecutionLog_insert <.. uspgenerator.usp_copy_procedure
uspgenerator.GeneratorUsp <.. uspgenerator.usp_copy_procedure
uspgenerator.GeneratorUspParameter <.. uspgenerator.usp_copy_procedure
uspgenerator.GeneratorUspStep <.. uspgenerator.usp_copy_procedure


footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_colref[]


== sql_modules_definition

// tag::sql_modules_definition[]
[%collapsible]
=======
[source,sql,numbered,indent=0]
----
/*
code of this procedure is managed in the dhw repository. Do not modify manually.
Use [uspgenerator].[GeneratorUsp], [uspgenerator].[GeneratorUspParameter], [uspgenerator].[GeneratorUspStep], [uspgenerator].[GeneratorUsp_SqlUsp]
*/
CREATE   PROCEDURE [uspgenerator].[usp_copy_procedure]
@source_usp_id int /* usp_id of the source procedure, you want to copy */
,@target_usp_schema NVARCHAR(128) = NULL /* usp_schema of the target procedure (the procedure to be created), if NULL, the source usp_schema will be used */
,@target_usp_name NVARCHAR(128) = NULL /* usp_schema of the target procedure (the procedure to be created), if NULL, the source usp_schema will be used with suffix _copy */
,
----keep the code between logging parameters and "START" unchanged!
---- parameters, used for logging; you don't need to care about them, but you can use them, wenn calling from SSIS or in your workflow to log the context of the procedure call
  @execution_instance_guid UNIQUEIDENTIFIER = NULL --SSIS system variable ExecutionInstanceGUID could be used, any other unique guid is also fine. If NULL, then NEWID() is used to create one
, @ssis_execution_id BIGINT = NULL --only SSIS system variable ServerExecutionID should be used, or any other consistent number system, do not mix different number systems
, @sub_execution_id INT = NULL --in case you log some sub_executions, for example in SSIS loops or sub packages
, @parent_execution_log_id BIGINT = NULL --in case a sup procedure is called, the @current_execution_log_id of the parent procedure should be propagated here. It allowes call stack analyzing

AS
BEGIN
DECLARE
 --
   @current_execution_log_id BIGINT --this variable should be filled only once per procedure call, it contains the first logging call for the step 'start'.
 , @current_execution_guid UNIQUEIDENTIFIER = NEWID() --a unique guid for any procedure call. It should be propagated to sub procedures using "@parent_execution_log_id = @current_execution_log_id"
 , @source_object NVARCHAR(261) = NULL --use it like '[schema].[object]', this allows data flow vizualizatiuon (include square brackets)
 , @target_object NVARCHAR(261) = NULL --use it like '[schema].[object]', this allows data flow vizualizatiuon (include square brackets)
 , @proc_id INT = @@procid
 , @proc_schema_name NVARCHAR(128) = OBJECT_SCHEMA_NAME(@@procid) --schema ande name of the current procedure should be automatically logged
 , @proc_name NVARCHAR(128) = OBJECT_NAME(@@procid)               --schema ande name of the current procedure should be automatically logged
 , @event_info NVARCHAR(MAX)
 , @step_id INT = 0
 , @step_name NVARCHAR(1000) = NULL
 , @rows INT

--[event_info] get's only the information about the "outer" calling process
--wenn the procedure calls sub procedures, the [event_info] will not change
SET @event_info = (
  SELECT TOP 1 [event_info]
  FROM sys.dm_exec_input_buffer(@@spid, CURRENT_REQUEST_ID())
  ORDER BY [event_info]
  )

IF @execution_instance_guid IS NULL
 SET @execution_instance_guid = NEWID();
--
--SET @rows = @@ROWCOUNT;
SET @step_id = @step_id + 1
SET @step_name = 'start'
SET @source_object = NULL
SET @target_object = NULL

EXEC logs.usp_ExecutionLog_insert
 --these parameters should be the same for all logging execution
   @execution_instance_guid = @execution_instance_guid
 , @ssis_execution_id = @ssis_execution_id
 , @sub_execution_id = @sub_execution_id
 , @parent_execution_log_id = @parent_execution_log_id
 , @current_execution_guid = @current_execution_guid
 , @proc_id = @proc_id
 , @proc_schema_name = @proc_schema_name
 , @proc_name = @proc_name
 , @event_info = @event_info
 --the following parameters are individual for each call
 , @step_id = @step_id --@step_id should be incremented before each call
 , @step_name = @step_name --assign individual step names for each call
 --only the "start" step should return the log id into @current_execution_log_id
 --all other calls should not overwrite @current_execution_log_id
 , @execution_log_id = @current_execution_log_id OUTPUT
----you can log the content of your own parameters, do this only in the start-step
----data type is sql_variant
 , @parameter_01 = @source_usp_id
 , @parameter_02 = @target_usp_schema
 , @parameter_03 = @target_usp_name
--
PRINT '[uspgenerator].[usp_copy_procedure]'
--keep the code between logging parameters and "START" unchanged!
--
----START
--
----- start here with your own code
--
/*{"ReportUspStep":[{"Number":300,"Name":"copy [uspgenerator].[GeneratorUsp]","has_logging":1,"is_condition":0,"is_inactive":0,"is_SubProcedure":0,"log_source_object":"[repo].[GeneratorUsp]","log_target_object":"[repo].[GeneratorUsp]","log_flag_InsertUpdateDelete":"i"}]}*/
PRINT CONCAT('usp_id;Number;Parent_Number: ',139,';',300,';',NULL);

Declare @target_usp_id Int

Insert Into uspgenerator.GeneratorUsp
(
    usp_schema
  , usp_name
  , has_logging
  , usp_Description
  , usp_Examples
)
Select
    usp_schema = IsNull ( @target_usp_schema, usp_schema )
  , usp_name   = IsNull ( @target_usp_name, usp_name + '_copy' )
  , has_logging
  , usp_Description
  , usp_Examples
From
    uspgenerator.GeneratorUsp
Where
    ( id = @source_usp_id )

Select
    @target_usp_id = Scope_Identity ()

-- Logging START --
SET @rows = @@ROWCOUNT
SET @step_id = @step_id + 1
SET @step_name = 'copy [uspgenerator].[GeneratorUsp]'
SET @source_object = '[repo].[GeneratorUsp]'
SET @target_object = '[repo].[GeneratorUsp]'

EXEC logs.usp_ExecutionLog_insert 
 @execution_instance_guid = @execution_instance_guid
 , @ssis_execution_id = @ssis_execution_id
 , @sub_execution_id = @sub_execution_id
 , @parent_execution_log_id = @parent_execution_log_id
 , @current_execution_guid = @current_execution_guid
 , @proc_id = @proc_id
 , @proc_schema_name = @proc_schema_name
 , @proc_name = @proc_name
 , @event_info = @event_info
 , @step_id = @step_id
 , @step_name = @step_name
 , @source_object = @source_object
 , @target_object = @target_object
 , @inserted = @rows
-- Logging END --

/*{"ReportUspStep":[{"Number":400,"Name":"check for inserted procedure","has_logging":0,"is_condition":1,"is_inactive":0,"is_SubProcedure":0,"log_source_object":"[repo].[IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing]"}]}*/
IF @target_usp_id Is Null

/*{"ReportUspStep":[{"Number":410,"Parent_Number":400,"Name":"ERROR 50110: @target_usp_id empty, nothing was inserted","has_logging":0,"is_condition":0,"is_inactive":0,"is_SubProcedure":0}]}*/
BEGIN
PRINT CONCAT('usp_id;Number;Parent_Number: ',139,';',410,';',400);

 THROW 50110
  , '@target_usp_id empty, nothing was inserted'
  , 1;

END;

/*{"ReportUspStep":[{"Number":500,"Name":"copy [uspgenerator].[GeneratorUspParameter]","has_logging":1,"is_condition":0,"is_inactive":0,"is_SubProcedure":0,"log_source_object":"[uspgenerator].[GeneratorUspParameter]","log_target_object":"[uspgenerator].[GeneratorUspParameter]","log_flag_InsertUpdateDelete":"i"}]}*/
PRINT CONCAT('usp_id;Number;Parent_Number: ',139,';',500,';',NULL);

Insert Into uspgenerator.GeneratorUspParameter
(
    usp_id
  , Number
  , Name
  , UserTypeFullname
  , is_inactive
  , is_out
  , has_DefaultValue
  , DefaultValue
  , Description
)
Select
    usp_id = @target_usp_id
  , S.Number
  , S.Name
  , S.UserTypeFullname
  , S.is_inactive
  , S.is_out
  , S.has_DefaultValue
  , S.DefaultValue
  , S.Description
From
    uspgenerator.GeneratorUspParameter As S
Where
    S.usp_id = @source_usp_id

-- Logging START --
SET @rows = @@ROWCOUNT
SET @step_id = @step_id + 1
SET @step_name = 'copy [uspgenerator].[GeneratorUspParameter]'
SET @source_object = '[uspgenerator].[GeneratorUspParameter]'
SET @target_object = '[uspgenerator].[GeneratorUspParameter]'

EXEC logs.usp_ExecutionLog_insert 
 @execution_instance_guid = @execution_instance_guid
 , @ssis_execution_id = @ssis_execution_id
 , @sub_execution_id = @sub_execution_id
 , @parent_execution_log_id = @parent_execution_log_id
 , @current_execution_guid = @current_execution_guid
 , @proc_id = @proc_id
 , @proc_schema_name = @proc_schema_name
 , @proc_name = @proc_name
 , @event_info = @event_info
 , @step_id = @step_id
 , @step_name = @step_name
 , @source_object = @source_object
 , @target_object = @target_object
 , @inserted = @rows
-- Logging END --

/*{"ReportUspStep":[{"Number":600,"Name":"copy [uspgenerator].[GeneratorUspStep]","has_logging":1,"is_condition":0,"is_inactive":0,"is_SubProcedure":0,"log_source_object":"[uspgenerator].[GeneratorUspStep]","log_target_object":"[uspgenerator].[GeneratorUspStep]","log_flag_InsertUpdateDelete":"i"}]}*/
PRINT CONCAT('usp_id;Number;Parent_Number: ',139,';',600,';',NULL);

Insert Into uspgenerator.GeneratorUspStep
(
    usp_id
  , Number
  , Parent_Number
  , Name
  , has_logging
  , is_condition
  , is_inactive
  , is_SubProcedure
  , Statement
  , log_source_object
  , log_target_object
  , log_flag_InsertUpdateDelete
  , Description
  , info_01
  , info_02
  , info_03
  , info_04
  , info_05
  , info_06
  , info_07
  , info_08
  , info_09
)
Select
    usp_id = @target_usp_id
  , S.Number
  , S.Parent_Number
  , S.Name
  , S.has_logging
  , S.is_condition
  , S.is_inactive
  , S.is_SubProcedure
  , S.Statement
  , S.log_source_object
  , S.log_target_object
  , S.log_flag_InsertUpdateDelete
  , S.Description
  , S.info_01
  , S.info_02
  , S.info_03
  , S.info_04
  , S.info_05
  , S.info_06
  , S.info_07
  , S.info_08
  , S.info_09
From
    uspgenerator.GeneratorUspStep As S
Where
    ( usp_id = @source_usp_id )

-- Logging START --
SET @rows = @@ROWCOUNT
SET @step_id = @step_id + 1
SET @step_name = 'copy [uspgenerator].[GeneratorUspStep]'
SET @source_object = '[uspgenerator].[GeneratorUspStep]'
SET @target_object = '[uspgenerator].[GeneratorUspStep]'

EXEC logs.usp_ExecutionLog_insert 
 @execution_instance_guid = @execution_instance_guid
 , @ssis_execution_id = @ssis_execution_id
 , @sub_execution_id = @sub_execution_id
 , @parent_execution_log_id = @parent_execution_log_id
 , @current_execution_guid = @current_execution_guid
 , @proc_id = @proc_id
 , @proc_schema_name = @proc_schema_name
 , @proc_name = @proc_name
 , @event_info = @event_info
 , @step_id = @step_id
 , @step_name = @step_name
 , @source_object = @source_object
 , @target_object = @target_object
 , @inserted = @rows
-- Logging END --

--
--finish your own code here
--keep the code between "END" and the end of the procedure unchanged!
--
--END
--
--SET @rows = @@ROWCOUNT
SET @step_id = @step_id + 1
SET @step_name = 'end'
SET @source_object = NULL
SET @target_object = NULL

EXEC logs.usp_ExecutionLog_insert
   @execution_instance_guid = @execution_instance_guid
 , @ssis_execution_id = @ssis_execution_id
 , @sub_execution_id = @sub_execution_id
 , @parent_execution_log_id = @parent_execution_log_id
 , @current_execution_guid = @current_execution_guid
 , @proc_id = @proc_id
 , @proc_schema_name = @proc_schema_name
 , @proc_name = @proc_name
 , @event_info = @event_info
 , @step_id = @step_id
 , @step_name = @step_name
 , @source_object = @source_object
 , @target_object = @target_object

END


----
=======
// end::sql_modules_definition[]


