// tag::HeaderFullDisplayName[]
= workflow.Workflow - U
// end::HeaderFullDisplayName[]

== existing_properties

// tag::existing_properties[]

:ExistsProperty--antorareferencinglist:
:ExistsProperty--is_repo_managed:
:ExistsProperty--is_ssas:
:ExistsProperty--pk_index_guid:
:ExistsProperty--pk_indexpatterncolumndatatype:
:ExistsProperty--pk_indexpatterncolumnname:
:ExistsProperty--FK:
:ExistsProperty--AntoraIndexList:
:ExistsProperty--Columns:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
7334CB25-1E66-EB11-84DD-A81E8446D5B0
// end::RepoObject_guid[]

== RepoObject_FullDisplayName2

// tag::RepoObject_FullDisplayName2[]
workflow.Workflow
// end::RepoObject_FullDisplayName2[]

== SysObject_type

// tag::SysObject_type[]
U 
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
user table
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
1886629764
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2022-01-23 14:10:34
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]
[discrete]
== _


[#column-id]
=== id

[cols="d,8a,m,m,m"]
|===
|1
|*id*
|int
|NOT NULL
|(1,1)
|===

.Referencing Columns
--
* xref:workflow.biml_package.adoc#column-id[+workflow.Biml_Package.id+]
* xref:workflow.workflow_proceduredependency.adoc#column-workflowunderlineid[+workflow.Workflow_ProcedureDependency.Workflow_id+]
* xref:workflow.workflow_proceduredependency_all.adoc#column-workflowunderlineid[+workflow.Workflow_ProcedureDependency_all.Workflow_id+]
--


[#column-description]
=== Description

[cols="d,8a,m,m,m"]
|===
|
|Description
|nvarchar(4000)
|NULL
|
|===


[#column-isunderlineactive]
=== is_active

[cols="d,8a,m,m,m"]
|===
|
|is_active

.Default: DF_Workflow_is_active
[source,sql]
----
((1))
----


|bit
|NOT NULL
|
|===


[#column-name]
=== Name

[cols="d,8a,m,m,m"]
|===
|
|Name
|nvarchar(500)
|NOT NULL
|
|===

.Referencing Columns
--
* xref:workflow.workflowstep_active.adoc#column-workflowunderlinename[+workflow.WorkflowStep_active.Workflow_Name+]
* xref:workflow.workflowstep_forupdate.adoc#column-workflowunderlinename[+workflow.WorkflowStep_ForUpdate.Workflow_Name+]
--


[#column-packageunderlinebiml]
=== Package_Biml

[cols="d,8a,m,m,m"]
|===
|
|Package_Biml
|nvarchar(max)
|NULL
|
|===


// end::AntoraColumnDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]
|1
|*<<column-id>>*
|int
|NOT NULL
|(1,1)





// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]

|
|<<column-description>>
|nvarchar(4000)
|NULL
|

|
|<<column-isunderlineactive>>

.Default: DF_Workflow_is_active
[source,sql]
----
((1))
----


|bit
|NOT NULL
|

|
|<<column-name>>
|nvarchar(500)
|NOT NULL
|

|
|<<column-packageunderlinebiml>>
|nvarchar(max)
|NULL
|

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

[#index-pkunderlineworkflow]
=== PK_Workflow

* IndexSemanticGroup: xref:other/indexsemanticgroup.adoc#startbnoblankgroupendb[no_group]
+
--
* <<column-id>>; int
--
* PK, Unique, Real: 1, 1, 1

// end::AntoraIndexList[]

== AntoraMeasureDetails

// tag::AntoraMeasureDetails[]

// end::AntoraMeasureDetails[]

== AntoraMeasureDescriptions



== AntoraParameterList

// tag::AntoraParameterList[]

// end::AntoraParameterList[]

== AntoraXrefCulturesList

// tag::AntoraXrefCulturesList[]
* xref:dhw:sqldb:workflow.workflow.adoc[] - 
// end::AntoraXrefCulturesList[]

== cultures_count

// tag::cultures_count[]
1
// end::cultures_count[]

== Other tags

source: property.RepoObjectProperty_cross As rop_cross


=== additional_reference_csv

// tag::additional_reference_csv[]

// end::additional_reference_csv[]


=== AdocUspSteps

// tag::adocuspsteps[]

// end::adocuspsteps[]


=== AntoraReferencedList

// tag::antorareferencedlist[]

// end::antorareferencedlist[]


=== AntoraReferencingList

// tag::antorareferencinglist[]
* xref:dhw:sqldb:workflow.biml_package.adoc[]
* xref:dhw:sqldb:workflow.workflow_proceduredependency.adoc[]
* xref:dhw:sqldb:workflow.workflow_proceduredependency_all.adoc[]
* xref:dhw:sqldb:workflow.workflow_usplist.adoc[]
* xref:dhw:sqldb:workflow.workflowstep_active.adoc[]
* xref:dhw:sqldb:workflow.workflowstep_forupdate.adoc[]
* xref:dhw:sqldb:workflow.workflowstep_src.adoc[]
// end::antorareferencinglist[]


=== Description

// tag::description[]

// end::description[]


=== exampleUsage

// tag::exampleusage[]

// end::exampleusage[]


=== exampleUsage_2

// tag::exampleusage_2[]

// end::exampleusage_2[]


=== exampleUsage_3

// tag::exampleusage_3[]

// end::exampleusage_3[]


=== exampleUsage_4

// tag::exampleusage_4[]

// end::exampleusage_4[]


=== exampleUsage_5

// tag::exampleusage_5[]

// end::exampleusage_5[]


=== exampleWrong_Usage

// tag::examplewrong_usage[]

// end::examplewrong_usage[]


=== has_execution_plan_issue

// tag::has_execution_plan_issue[]

// end::has_execution_plan_issue[]


=== has_get_referenced_issue

// tag::has_get_referenced_issue[]

// end::has_get_referenced_issue[]


=== has_history

// tag::has_history[]

// end::has_history[]


=== has_history_columns

// tag::has_history_columns[]

// end::has_history_columns[]


=== InheritanceType

// tag::inheritancetype[]

// end::inheritancetype[]


=== is_persistence

// tag::is_persistence[]

// end::is_persistence[]


=== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]

// end::is_persistence_check_duplicate_per_pk[]


=== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]

// end::is_persistence_check_for_empty_source[]


=== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]

// end::is_persistence_delete_changed[]


=== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]

// end::is_persistence_delete_missing[]


=== is_persistence_insert

// tag::is_persistence_insert[]

// end::is_persistence_insert[]


=== is_persistence_truncate

// tag::is_persistence_truncate[]

// end::is_persistence_truncate[]


=== is_persistence_update_changed

// tag::is_persistence_update_changed[]

// end::is_persistence_update_changed[]


=== is_repo_managed

// tag::is_repo_managed[]
0
// end::is_repo_managed[]


=== is_ssas

// tag::is_ssas[]
0
// end::is_ssas[]


=== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


=== MS_Description

// tag::ms_description[]

// end::ms_description[]


=== persistence_source_RepoObject_fullname

// tag::persistence_source_repoobject_fullname[]

// end::persistence_source_repoobject_fullname[]


=== persistence_source_RepoObject_fullname2

// tag::persistence_source_repoobject_fullname2[]

// end::persistence_source_repoobject_fullname2[]


=== persistence_source_RepoObject_guid

// tag::persistence_source_repoobject_guid[]

// end::persistence_source_repoobject_guid[]


=== persistence_source_RepoObject_xref

// tag::persistence_source_repoobject_xref[]

// end::persistence_source_repoobject_xref[]


=== pk_index_guid

// tag::pk_index_guid[]
7034CB25-1E66-EB11-84DD-A81E8446D5B0
// end::pk_index_guid[]


=== pk_IndexPatternColumnDatatype

// tag::pk_indexpatterncolumndatatype[]
int
// end::pk_indexpatterncolumndatatype[]


=== pk_IndexPatternColumnName

// tag::pk_indexpatterncolumnname[]
id
// end::pk_indexpatterncolumnname[]


=== pk_IndexSemanticGroup

// tag::pk_indexsemanticgroup[]

// end::pk_indexsemanticgroup[]


=== ReferencedObjectList

// tag::referencedobjectlist[]

// end::referencedobjectlist[]


=== usp_persistence_RepoObject_guid

// tag::usp_persistence_repoobject_guid[]

// end::usp_persistence_repoobject_guid[]


=== UspExamples

// tag::uspexamples[]

// end::uspexamples[]


=== uspgenerator_usp_id

// tag::uspgenerator_usp_id[]

// end::uspgenerator_usp_id[]


=== UspParameters

// tag::uspparameters[]

// end::uspparameters[]

== Boolean Attributes

source: property.RepoObjectProperty WHERE property_int = 1

// tag::boolean_attributes[]


// end::boolean_attributes[]

== PlantUML diagrams

=== PlantUML Entity

// tag::puml_entity[]
[plantuml, entity-{docname}, svg, subs=macros]
....
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:workflow.workflow.adoc[]" as workflow.Workflow << U >> {
  - **id** : (int)
  Description : (nvarchar(4000))
  - is_active : (bit)
  - Name : (nvarchar(500))
  Package_Biml : (nvarchar(max))
  --
}
....

// end::puml_entity[]

=== PlantUML Entity 1 1 FK

// tag::puml_entity_1_1_fk[]
[plantuml, entity_1_1_fk-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:workflow.workflow.adoc[]" as workflow.Workflow << U >> {
**PK_Workflow**

..
id; int
}

entity "puml-link:dhw:sqldb:workflow.workflowstep.adoc[]" as workflow.WorkflowStep << U >> {
**PK_WorkflowStep**

..
id; int
--
UK_WorkflowStep

..
Workflow_id; int
Procedure_RepoObject_guid; uniqueidentifier
--
- idx_WorkflowStep__1

..
Workflow_id; int
--
- idx_WorkflowStep__2

..
Procedure_RepoObject_guid; uniqueidentifier
}

"workflow.Workflow::PK_Workflow" <-- "workflow.WorkflowStep::idx_WorkflowStep__1"

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_fk[]

=== PlantUML 1 1 ObjectRef

// tag::puml_entity_1_1_objectref[]
[plantuml, entity_1_1_objectref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:workflow.biml_package.adoc[]" as workflow.Biml_Package << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.workflow.adoc[]" as workflow.Workflow << U >> {
  - **id** : (int)
  --
}

entity "puml-link:dhw:sqldb:workflow.workflow_proceduredependency.adoc[]" as workflow.Workflow_ProcedureDependency << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.workflow_proceduredependency_all.adoc[]" as workflow.Workflow_ProcedureDependency_all << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.workflow_usplist.adoc[]" as workflow.Workflow_UspList << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.workflowstep_active.adoc[]" as workflow.WorkflowStep_active << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.workflowstep_forupdate.adoc[]" as workflow.WorkflowStep_ForUpdate << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.workflowstep_src.adoc[]" as workflow.WorkflowStep_src << V >> {
  - **Workflow_id** : (int)
  **Procedure_RepoObject_guid** : (uniqueidentifier)
  --
}

workflow.Workflow <.. workflow.WorkflowStep_active
workflow.Workflow <.. workflow.WorkflowStep_src
workflow.Workflow <.. workflow.Workflow_UspList
workflow.Workflow <.. workflow.Workflow_ProcedureDependency_all
workflow.Workflow <.. workflow.WorkflowStep_ForUpdate
workflow.Workflow <.. workflow.Biml_Package
workflow.Workflow <.. workflow.Workflow_ProcedureDependency

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_objectref[]

=== PlantUML 30 0 ObjectRef

// tag::puml_entity_30_0_objectref[]
[plantuml, entity_30_0_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:workflow.workflow.adoc[]" as workflow.Workflow << U >> {
  - **id** : (int)
  --
}



footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_30_0_objectref[]

=== PlantUML 0 30 ObjectRef

// tag::puml_entity_0_30_objectref[]
[plantuml, entity_0_30_objectref-{docname}, svg, subs=macros]
....
@startuml
'Left to right direction
top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:workflow.biml_package.adoc[]" as workflow.Biml_Package << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.biml_precedenceconstraints.adoc[]" as workflow.Biml_PrecedenceConstraints << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.biml_project.adoc[]" as workflow.Biml_Project << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.biml_task.adoc[]" as workflow.Biml_Task << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.usp_persist_workflow_proceduredependency_t.adoc[]" as workflow.usp_PERSIST_Workflow_ProcedureDependency_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.usp_persist_workflowstep.adoc[]" as workflow.usp_PERSIST_WorkflowStep << P >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.usp_workflow.adoc[]" as workflow.usp_workflow << P >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.workflow.adoc[]" as workflow.Workflow << U >> {
  - **id** : (int)
  --
}

entity "puml-link:dhw:sqldb:workflow.workflow_proceduredependency.adoc[]" as workflow.Workflow_ProcedureDependency << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.workflow_proceduredependency_all.adoc[]" as workflow.Workflow_ProcedureDependency_all << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.workflow_proceduredependency_t.adoc[]" as workflow.Workflow_ProcedureDependency_T << U >> {
  - **Workflow_id** : (int)
  - **referenced_Procedure_RepoObject_guid** : (uniqueidentifier)
  - **referencing_Procedure_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:workflow.workflow_proceduredependency_t_active.adoc[]" as workflow.Workflow_ProcedureDependency_T_active << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.workflow_proceduredependency_t_bidirectional.adoc[]" as workflow.Workflow_ProcedureDependency_T_bidirectional << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.workflow_proceduredependency_t_bidirectional_t.adoc[]" as workflow.Workflow_ProcedureDependency_T_bidirectional_T << U >> {
  - **Workflow_id** : (int)
  - **referenced_Procedure_RepoObject_guid** : (uniqueidentifier)
  - **referencing_Procedure_RepoObject_guid** : (uniqueidentifier)
  --
}

entity "puml-link:dhw:sqldb:workflow.workflow_proceduredependency_t_notinsortorder.adoc[]" as workflow.Workflow_ProcedureDependency_T_NotInSortorder << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.workflow_proceduredependency_t_notinsortorder_check.adoc[]" as workflow.Workflow_ProcedureDependency_T_NotInSortorder_check << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.workflow_proceduredependency_t_redundant.adoc[]" as workflow.Workflow_ProcedureDependency_T_redundant << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.workflow_proceduredependency_t_taskname.adoc[]" as workflow.Workflow_ProcedureDependency_T_TaskName << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.workflow_proceduredependency_wo_redundant.adoc[]" as workflow.Workflow_ProcedureDependency_wo_redundant << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.workflow_sqlusp.adoc[]" as workflow.Workflow_SqlUsp << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.workflow_usplist.adoc[]" as workflow.Workflow_UspList << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.workflowstep.adoc[]" as workflow.WorkflowStep << U >> {
  - **id** : (int)
  --
}

entity "puml-link:dhw:sqldb:workflow.workflowstep_active.adoc[]" as workflow.WorkflowStep_active << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.workflowstep_forupdate.adoc[]" as workflow.WorkflowStep_ForUpdate << V >> {
  --
}

entity "puml-link:dhw:sqldb:workflow.workflowstep_src.adoc[]" as workflow.WorkflowStep_src << V >> {
  - **Workflow_id** : (int)
  **Procedure_RepoObject_guid** : (uniqueidentifier)
  --
}

workflow.Biml_Package <.. workflow.Biml_Project
workflow.Biml_PrecedenceConstraints <.. workflow.Biml_Task
workflow.Biml_Task <.. workflow.Biml_Package
workflow.usp_PERSIST_Workflow_ProcedureDependency_T <.. workflow.usp_workflow
workflow.usp_PERSIST_WorkflowStep <.. workflow.usp_workflow
workflow.Workflow <.. workflow.WorkflowStep_active
workflow.Workflow <.. workflow.WorkflowStep_src
workflow.Workflow <.. workflow.Workflow_ProcedureDependency_all
workflow.Workflow <.. workflow.WorkflowStep_ForUpdate
workflow.Workflow <.. workflow.Biml_Package
workflow.Workflow <.. workflow.Workflow_ProcedureDependency
workflow.Workflow <.. workflow.Workflow_UspList
workflow.Workflow_ProcedureDependency <.. workflow.Workflow_ProcedureDependency_T
workflow.Workflow_ProcedureDependency <.. workflow.usp_PERSIST_Workflow_ProcedureDependency_T
workflow.Workflow_ProcedureDependency_all <.. workflow.Workflow_ProcedureDependency_wo_redundant
workflow.Workflow_ProcedureDependency_T <.. workflow.usp_workflow
workflow.Workflow_ProcedureDependency_T <.. workflow.Workflow_ProcedureDependency_T_bidirectional
workflow.Workflow_ProcedureDependency_T <.. workflow.usp_PERSIST_Workflow_ProcedureDependency_T
workflow.Workflow_ProcedureDependency_T <.. workflow.Workflow_ProcedureDependency_T_active
workflow.Workflow_ProcedureDependency_T_active <.. workflow.Workflow_ProcedureDependency_T_redundant
workflow.Workflow_ProcedureDependency_T_active <.. workflow.Workflow_ProcedureDependency_T_TaskName
workflow.Workflow_ProcedureDependency_T_active <.. workflow.Workflow_ProcedureDependency_T_NotInSortorder
workflow.Workflow_ProcedureDependency_T_bidirectional <.. workflow.usp_workflow
workflow.Workflow_ProcedureDependency_T_bidirectional <.. workflow.Workflow_ProcedureDependency_T_bidirectional_T
workflow.Workflow_ProcedureDependency_T_NotInSortorder <.. workflow.usp_workflow
workflow.Workflow_ProcedureDependency_T_NotInSortorder <.. workflow.Workflow_ProcedureDependency_T_NotInSortorder_check
workflow.Workflow_ProcedureDependency_T_NotInSortorder_check <.. workflow.usp_workflow
workflow.Workflow_ProcedureDependency_T_redundant <.. workflow.Workflow_ProcedureDependency_wo_redundant
workflow.Workflow_ProcedureDependency_T_redundant <.. workflow.usp_workflow
workflow.Workflow_ProcedureDependency_T_TaskName <.. workflow.Biml_PrecedenceConstraints
workflow.Workflow_UspList <.. workflow.Workflow_SqlUsp
workflow.WorkflowStep <.. workflow.WorkflowStep_active
workflow.WorkflowStep <.. workflow.usp_PERSIST_WorkflowStep
workflow.WorkflowStep <.. workflow.WorkflowStep_ForUpdate
workflow.WorkflowStep_active <.. workflow.Biml_Task
workflow.WorkflowStep_active <.. workflow.Workflow_ProcedureDependency
workflow.WorkflowStep_active <.. workflow.Workflow_ProcedureDependency_T_active
workflow.WorkflowStep_active <.. workflow.usp_workflow
workflow.WorkflowStep_active <.. workflow.Workflow_ProcedureDependency_all
workflow.WorkflowStep_src <.. workflow.WorkflowStep
workflow.WorkflowStep_src <.. workflow.usp_PERSIST_WorkflowStep

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_0_30_objectref[]

=== PlantUML 1 1 ColumnRef

// tag::puml_entity_1_1_colref[]
[plantuml, entity_1_1_colref-{docname}, svg, subs=macros]
....
@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>>  Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>>  White
  BackgroundColor<<V>>  WhiteSmoke
  BackgroundColor<<X>>  Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:workflow.biml_package.adoc[]" as workflow.Biml_Package << V >> {
  - id : (int)
  Package_Biml : (nvarchar(max))
  Package_Description : (nvarchar(4000))
  Package_Name : (nvarchar(500))
  --
}

entity "puml-link:dhw:sqldb:workflow.workflow.adoc[]" as workflow.Workflow << U >> {
  - **id** : (int)
  Description : (nvarchar(4000))
  - is_active : (bit)
  - Name : (nvarchar(500))
  Package_Biml : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:workflow.workflow_proceduredependency.adoc[]" as workflow.Workflow_ProcedureDependency << V >> {
  - referenced_Procedure_RepoObject_guid : (uniqueidentifier)
  - referencing_Procedure_RepoObject_guid : (uniqueidentifier)
  - Workflow_id : (int)
  --
}

entity "puml-link:dhw:sqldb:workflow.workflow_proceduredependency_all.adoc[]" as workflow.Workflow_ProcedureDependency_all << V >> {
  - referenced_Procedure_RepoObject_guid : (uniqueidentifier)
  - referencing_Procedure_RepoObject_guid : (uniqueidentifier)
  - Workflow_id : (int)
  --
}

entity "puml-link:dhw:sqldb:workflow.workflow_usplist.adoc[]" as workflow.Workflow_UspList << V >> {
  UspList : (nvarchar(max))
  - Workflow_id : (int)
  Workflow_Name : (nvarchar(500))
  --
}

entity "puml-link:dhw:sqldb:workflow.workflowstep_active.adoc[]" as workflow.WorkflowStep_active << V >> {
  - is_PossibleReferenced : (bit)
  - Procedure_RepoObject_guid : (uniqueidentifier)
  - Workflow_id : (int)
  - Workflow_Name : (nvarchar(500))
  --
}

entity "puml-link:dhw:sqldb:workflow.workflowstep_forupdate.adoc[]" as workflow.WorkflowStep_ForUpdate << V >> {
  - id : (int)
  - is_active : (bit)
  - is_PossibleReferenced : (bit)
  - Procedure_RepoObject_guid : (uniqueidentifier)
  - RepoObject_fullname : (nvarchar(261))
  - Workflow_id : (int)
  - Workflow_Name : (nvarchar(500))
  --
}

entity "puml-link:dhw:sqldb:workflow.workflowstep_src.adoc[]" as workflow.WorkflowStep_src << V >> {
  - **Workflow_id** : (int)
  **Procedure_RepoObject_guid** : (uniqueidentifier)
  --
}

workflow.Workflow <.. workflow.WorkflowStep_active
workflow.Workflow <.. workflow.WorkflowStep_src
workflow.Workflow <.. workflow.Workflow_UspList
workflow.Workflow <.. workflow.Workflow_ProcedureDependency_all
workflow.Workflow <.. workflow.WorkflowStep_ForUpdate
workflow.Workflow <.. workflow.Biml_Package
workflow.Workflow <.. workflow.Workflow_ProcedureDependency
"workflow.Workflow::id" <-- "workflow.Biml_Package::id"
"workflow.Workflow::id" <-- "workflow.Workflow_ProcedureDependency_all::Workflow_id"
"workflow.Workflow::id" <-- "workflow.Workflow_ProcedureDependency::Workflow_id"
"workflow.Workflow::Name" <-- "workflow.WorkflowStep_ForUpdate::Workflow_Name"
"workflow.Workflow::Name" <-- "workflow.WorkflowStep_active::Workflow_Name"

footer The diagram is interactive and contains links.

@enduml
....

// end::puml_entity_1_1_colref[]


== sql_modules_definition

// tag::sql_modules_definition[]
[%collapsible]
=======
[source,sql,numbered,indent=0]
----

----
=======
// end::sql_modules_definition[]


