@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity "[[{site-url}/{page-component-name}/{page-component-version}/{page-module}/config.SsasDatabasename.html config.SsasDatabasename]]" as config.SsasDatabasename << U >> {
  - **databasename** : (nvarchar(128))
  --
  - isActive : (bit)
  - isCurrentImport : (bit)
  - LinkedServer : (nvarchar(128))
  --
  --
}

entity "[[{site-url}/{page-component-name}/{page-component-version}/{page-module}/configT.SsasDmvTableImport_DmvColumnList.html configT.SsasDmvTableImport_DmvColumnList]]" as configT.SsasDmvTableImport_DmvColumnList << V >> {
  --
  DmvColumnList : (nvarchar(4000))
  DmvTableName : (nvarchar(128))
  --
  --
}

entity "[[{site-url}/{page-component-name}/{page-component-version}/{page-module}/configT.SsasDmvTableImport_ImportSql.html configT.SsasDmvTableImport_ImportSql]]" as configT.SsasDmvTableImport_ImportSql << V >> {
  --
  - databasename : (nvarchar(128))
  - DeleteInsertSql : (nvarchar(4000))
  - ExecPersistSql : (nvarchar(161))
  - isActive : (bit)
  - isCurrentImport : (bit)
  - LinkedServer : (nvarchar(128))
  - truncateSql : (nvarchar(156))
  --
  --
}

config.SsasDatabasename <.. configT.SsasDmvTableImport_ImportSql
configT.SsasDmvTableImport_DmvColumnList <.. configT.SsasDmvTableImport_ImportSql
config.SsasDatabasename::databasename <-- configT.SsasDmvTableImport_ImportSql::databasename
config.SsasDatabasename::isActive <-- configT.SsasDmvTableImport_ImportSql::isActive
config.SsasDatabasename::isCurrentImport <-- configT.SsasDmvTableImport_ImportSql::isCurrentImport
config.SsasDatabasename::LinkedServer <-- configT.SsasDmvTableImport_ImportSql::LinkedServer
footer
to view a reduced diagram in original size and to be able to click on the links:
open the diagram in a new tab via the Context menu.
end footer

@enduml

