@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity "puml-link:config.fs_dwh_database_name.adoc[prefix=..]" as config.fs_dwh_database_name << FN >> {
  --
  --
  --
}

entity "puml-link:config.fs_get_parameter_value.adoc[prefix=..]" as config.fs_get_parameter_value << FN >> {
  --
  --
  --
}

entity "puml-link:config.ftv_dwh_database.adoc[prefix=..]" as config.ftv_dwh_database << IF >> {
  --
  dwh_database_id : (smallint)
  dwh_database_name : (nvarchar(128))
  --
  --
}

entity "puml-link:config.ftv_get_parameter_value.adoc[prefix=..]" as config.ftv_get_parameter_value << IF >> {
  --
  Parameter_value_result : (nvarchar(max))
  Parameter_value_result_date : (date)
  Parameter_value_result_datetime : (datetime)
  Parameter_value_result_int : (int)
  --
  --
}

entity "puml-link:config.Parameter.adoc[prefix=..]" as config.Parameter << U >> {
  - **Parameter_name** : (varchar(100))
  - **sub_Parameter** : (nvarchar(128))
  --
  Parameter_default_value : (nvarchar(max))
  Parameter_desciption : (nvarchar(1000))
  Parameter_value : (nvarchar(max))
  ~ Parameter_value_result : (nvarchar(max))
  ~ Parameter_value_result_date : (date)
  ~ Parameter_value_result_datetime : (datetime)
  ~ Parameter_value_result_int : (int)
  --
  --
}

entity "puml-link:config.usp_init_parameter.adoc[prefix=..]" as config.usp_init_parameter << P >> {
  --
  --
  --
}

entity "puml-link:config.usp_parameter_set.adoc[prefix=..]" as config.usp_parameter_set << P >> {
  --
  --
  --
}

entity "puml-link:docs.usp_AntoraExport_DocSnippet.adoc[prefix=..]" as docs.usp_AntoraExport_DocSnippet << P >> {
  --
  --
  --
}

entity "puml-link:docs.usp_AntoraExport_ObjectPageTemplate.adoc[prefix=..]" as docs.usp_AntoraExport_ObjectPageTemplate << P >> {
  --
  --
  --
}

entity "puml-link:property.PropertyName_RepoObject.adoc[prefix=..]" as property.PropertyName_RepoObject << V >> {
  **property_name** : (nvarchar(128))
  --
  --
  --
}

entity "puml-link:property.PropertyName_RepoObjectColumn.adoc[prefix=..]" as property.PropertyName_RepoObjectColumn << V >> {
  - **property_name** : (nvarchar(128))
  --
  --
  --
}

entity "puml-link:property.RepoObjectColumnProperty_InheritanceType_InheritanceDefinition.adoc[prefix=..]" as property.RepoObjectColumnProperty_InheritanceType_InheritanceDefinition << V >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  --
  Inheritance_StringAggSeparatorSql : (nvarchar(max))
  InheritanceDefinition : (nvarchar(max))
  InheritanceType : (int)
  par_Inheritance_StringAggSeparatorSql : (nvarchar(max))
  par_InheritanceDefinition : (nvarchar(max))
  par_InheritanceType : (int)
  property_value : (nvarchar(max))
  - RepoObjectColumn_name : (nvarchar(128))
  roc_Inheritance_StringAggSeparatorSql : (nvarchar(4000))
  roc_InheritanceDefinition : (nvarchar(4000))
  roc_InheritanceType : (tinyint)
  sub_Inheritance_StringAggSeparatorSql : (nvarchar(max))
  sub_InheritanceDefinition : (nvarchar(max))
  sub_InheritanceType : (int)
  --
  --
}

entity "puml-link:property.RepoObjectProperty_InheritanceType_InheritanceDefinition.adoc[prefix=..]" as property.RepoObjectProperty_InheritanceType_InheritanceDefinition << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  --
  Inheritance_StringAggSeparatorSql : (nvarchar(max))
  InheritanceDefinition : (nvarchar(max))
  InheritanceType : (int)
  par_Inheritance_StringAggSeparatorSql : (nvarchar(max))
  par_InheritanceDefintion : (nvarchar(max))
  par_InheritanceType : (int)
  property_value : (nvarchar(max))
  - RepoObject_fullname : (nvarchar(261))
  - RepoObject_type : (char(2))
  ro_Inheritance_StringAggSeparatorSql : (nvarchar(4000))
  ro_InheritanceDefinition : (nvarchar(4000))
  ro_InheritanceType : (tinyint)
  sub_Inheritance_StringAggSeparatorSql : (nvarchar(max))
  sub_InheritanceDefintion : (nvarchar(max))
  sub_InheritanceType : (int)
  --
  --
}

entity "puml-link:repo.usp_persistence_set.adoc[prefix=..]" as repo.usp_persistence_set << P >> {
  --
  --
  --
}

config.Parameter <.. config.fs_dwh_database_name
config.Parameter <.. config.fs_get_parameter_value
config.Parameter <.. config.ftv_dwh_database
config.Parameter <.. config.ftv_get_parameter_value
config.Parameter <.. config.usp_init_parameter
config.Parameter <.. config.usp_parameter_set
config.Parameter <.. repo.usp_persistence_set
config.Parameter <.. property.PropertyName_RepoObject
config.Parameter <.. property.PropertyName_RepoObjectColumn
config.Parameter <.. property.RepoObjectProperty_InheritanceType_InheritanceDefinition
config.Parameter <.. property.RepoObjectColumnProperty_InheritanceType_InheritanceDefinition
config.Parameter <.. docs.usp_AntoraExport_ObjectPageTemplate
config.Parameter <.. docs.usp_AntoraExport_DocSnippet
config.Parameter::Parameter_default_value <-- config.Parameter::Parameter_value_result
config.Parameter::Parameter_default_value <-- config.Parameter::Parameter_value_result_int
config.Parameter::Parameter_default_value <-- config.Parameter::Parameter_value_result_date
config.Parameter::Parameter_default_value <-- config.Parameter::Parameter_value_result_datetime
config.Parameter::Parameter_value <-- config.Parameter::Parameter_value_result
config.Parameter::Parameter_value <-- config.Parameter::Parameter_value_result_int
config.Parameter::Parameter_value <-- config.Parameter::Parameter_value_result_date
config.Parameter::Parameter_value <-- config.Parameter::Parameter_value_result_datetime
config.Parameter::Parameter_value_result <-- property.RepoObjectProperty_InheritanceType_InheritanceDefinition::sub_InheritanceDefintion
config.Parameter::Parameter_value_result <-- property.RepoObjectProperty_InheritanceType_InheritanceDefinition::par_InheritanceDefintion
config.Parameter::Parameter_value_result <-- property.RepoObjectProperty_InheritanceType_InheritanceDefinition::sub_Inheritance_StringAggSeparatorSql
config.Parameter::Parameter_value_result <-- property.RepoObjectProperty_InheritanceType_InheritanceDefinition::par_Inheritance_StringAggSeparatorSql
config.Parameter::Parameter_value_result <-- property.RepoObjectColumnProperty_InheritanceType_InheritanceDefinition::sub_InheritanceDefinition
config.Parameter::Parameter_value_result <-- property.RepoObjectColumnProperty_InheritanceType_InheritanceDefinition::par_InheritanceDefinition
config.Parameter::Parameter_value_result <-- property.RepoObjectColumnProperty_InheritanceType_InheritanceDefinition::sub_Inheritance_StringAggSeparatorSql
config.Parameter::Parameter_value_result <-- property.RepoObjectColumnProperty_InheritanceType_InheritanceDefinition::par_Inheritance_StringAggSeparatorSql
config.Parameter::Parameter_value_result_int <-- property.RepoObjectProperty_InheritanceType_InheritanceDefinition::sub_InheritanceType
config.Parameter::Parameter_value_result_int <-- property.RepoObjectProperty_InheritanceType_InheritanceDefinition::par_InheritanceType
config.Parameter::Parameter_value_result_int <-- property.RepoObjectColumnProperty_InheritanceType_InheritanceDefinition::sub_InheritanceType
config.Parameter::Parameter_value_result_int <-- property.RepoObjectColumnProperty_InheritanceType_InheritanceDefinition::par_InheritanceType
footer
to view a reduced diagram in original size and to be able to click on the links:
open the diagram in a new tab via the Context menu.
end footer

@enduml

