@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:config.fs_dwh_database_name.adoc[]" as config.fs_dwh_database_name << FN >> {
  --
}

entity "puml-link:dhw:sqldb:config.fs_get_parameter_value.adoc[]" as config.fs_get_parameter_value << FN >> {
  --
}

entity "puml-link:dhw:sqldb:config.ftv_dwh_database.adoc[]" as config.ftv_dwh_database << IF >> {
  dwh_database_id : (smallint)
  dwh_database_name : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:config.ftv_get_parameter_value.adoc[]" as config.ftv_get_parameter_value << IF >> {
  Parameter_value_result : (nvarchar(max))
  Parameter_value_result_date : (date)
  Parameter_value_result_datetime : (datetime)
  Parameter_value_result_int : (int)
  --
}

entity "puml-link:dhw:sqldb:config.parameter.adoc[]" as config.Parameter << U >> {
  - **Parameter_name** : (varchar(100))
  - **sub_Parameter** : (nvarchar(128))
  Parameter_default_value : (nvarchar(max))
  Parameter_desciption : (nvarchar(1000))
  Parameter_value : (nvarchar(max))
  ~ Parameter_value_result : (nvarchar(max))
  ~ Parameter_value_result_date : (date)
  ~ Parameter_value_result_datetime : (datetime)
  ~ Parameter_value_result_int : (int)
  --
}

entity "puml-link:dhw:sqldb:config.usp_init_parameter.adoc[]" as config.usp_init_parameter << P >> {
  --
}

entity "puml-link:dhw:sqldb:config.usp_parameter_set.adoc[]" as config.usp_parameter_set << P >> {
  --
}

entity "puml-link:dhw:sqldb:configt.parameter_default.adoc[]" as configT.Parameter_default << V >> {
  - **Parameter_name** : (varchar(52))
  - **sub_Parameter** : (nvarchar(27))
  Parameter_default_value : (nvarchar(max))
  - Parameter_desciption : (nvarchar(247))
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_docsnippet.adoc[]" as docs.usp_AntoraExport_DocSnippet << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_objectpagetemplate.adoc[]" as docs.usp_AntoraExport_ObjectPageTemplate << P >> {
  --
}

entity "puml-link:dhw:sqldb:docs.usp_antoraexport_ssispagetemplate.adoc[]" as docs.usp_AntoraExport_SsisPageTemplate << P >> {
  --
}

entity "puml-link:dhw:sqldb:property.propertyname_repoobject.adoc[]" as property.PropertyName_RepoObject << V >> {
  **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.propertyname_repoobjectcolumn.adoc[]" as property.PropertyName_RepoObjectColumn << V >> {
  - **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectcolumnproperty_inheritancetype_inheritancedefinition.adoc[]" as property.RepoObjectColumnProperty_InheritanceType_InheritanceDefinition << V >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  Inheritance_StringAggSeparatorSql : (nvarchar(max))
  InheritanceDefinition : (nvarchar(max))
  InheritanceType : (int)
  par_Inheritance_StringAggSeparatorSql : (nvarchar(max))
  par_InheritanceDefinition : (nvarchar(max))
  par_InheritanceType : (int)
  property_value : (nvarchar(max))
  - RepoObjectColumn_name : (nvarchar(128))
  roc_Inheritance_StringAggSeparatorSql : (nvarchar(4000))
  roc_InheritanceDefinition : (nvarchar(4000))
  roc_InheritanceType : (tinyint)
  sub_Inheritance_StringAggSeparatorSql : (nvarchar(max))
  sub_InheritanceDefinition : (nvarchar(max))
  sub_InheritanceType : (int)
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty_inheritancetype_inheritancedefinition.adoc[]" as property.RepoObjectProperty_InheritanceType_InheritanceDefinition << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  Inheritance_Source_fullname : (nvarchar(261))
  Inheritance_StringAggSeparatorSql : (nvarchar(max))
  InheritanceDefinition : (nvarchar(max))
  InheritanceType : (int)
  par_Inheritance_StringAggSeparatorSql : (nvarchar(max))
  par_InheritanceDefintion : (nvarchar(max))
  par_InheritanceType : (int)
  property_value : (nvarchar(max))
  - RepoObject_fullname : (nvarchar(261))
  - RepoObject_type : (char(2))
  ro_Inheritance_StringAggSeparatorSql : (nvarchar(4000))
  ro_InheritanceDefinition : (nvarchar(4000))
  ro_InheritanceType : (tinyint)
  sub_Inheritance_StringAggSeparatorSql : (nvarchar(max))
  sub_InheritanceDefintion : (nvarchar(max))
  sub_InheritanceType : (int)
  --
}

entity "puml-link:dhw:sqldb:repo.usp_persistence_set.adoc[]" as repo.usp_persistence_set << P >> {
  --
}

config.Parameter <.. config.fs_dwh_database_name
config.Parameter <.. config.fs_get_parameter_value
config.Parameter <.. config.ftv_dwh_database
config.Parameter <.. config.ftv_get_parameter_value
config.Parameter <.. config.usp_init_parameter
config.Parameter <.. config.usp_parameter_set
config.Parameter <.. repo.usp_persistence_set
config.Parameter <.. property.PropertyName_RepoObject
config.Parameter <.. property.PropertyName_RepoObjectColumn
config.Parameter <.. property.RepoObjectProperty_InheritanceType_InheritanceDefinition
config.Parameter <.. property.RepoObjectColumnProperty_InheritanceType_InheritanceDefinition
config.Parameter <.. docs.usp_AntoraExport_ObjectPageTemplate
config.Parameter <.. docs.usp_AntoraExport_DocSnippet
config.Parameter <.. docs.usp_AntoraExport_SsisPageTemplate
configT.Parameter_default <.. config.Parameter
"config.Parameter::Parameter_default_value" <-- "config.Parameter::Parameter_value_result_date"
"config.Parameter::Parameter_default_value" <-- "config.Parameter::Parameter_value_result_datetime"
"config.Parameter::Parameter_default_value" <-- "config.Parameter::Parameter_value_result"
"config.Parameter::Parameter_default_value" <-- "config.Parameter::Parameter_value_result_int"
"config.Parameter::Parameter_value" <-- "config.Parameter::Parameter_value_result_int"
"config.Parameter::Parameter_value" <-- "config.Parameter::Parameter_value_result"
"config.Parameter::Parameter_value" <-- "config.Parameter::Parameter_value_result_date"
"config.Parameter::Parameter_value" <-- "config.Parameter::Parameter_value_result_datetime"
"config.Parameter::Parameter_value_result" <-- "property.RepoObjectColumnProperty_InheritanceType_InheritanceDefinition::sub_InheritanceDefinition"
"config.Parameter::Parameter_value_result" <-- "property.RepoObjectColumnProperty_InheritanceType_InheritanceDefinition::par_InheritanceDefinition"
"config.Parameter::Parameter_value_result" <-- "property.RepoObjectColumnProperty_InheritanceType_InheritanceDefinition::sub_Inheritance_StringAggSeparatorSql"
"config.Parameter::Parameter_value_result" <-- "property.RepoObjectColumnProperty_InheritanceType_InheritanceDefinition::par_Inheritance_StringAggSeparatorSql"
"config.Parameter::Parameter_value_result" <-- "property.RepoObjectProperty_InheritanceType_InheritanceDefinition::par_InheritanceDefintion"
"config.Parameter::Parameter_value_result" <-- "property.RepoObjectProperty_InheritanceType_InheritanceDefinition::sub_Inheritance_StringAggSeparatorSql"
"config.Parameter::Parameter_value_result" <-- "property.RepoObjectProperty_InheritanceType_InheritanceDefinition::par_Inheritance_StringAggSeparatorSql"
"config.Parameter::Parameter_value_result" <-- "property.RepoObjectProperty_InheritanceType_InheritanceDefinition::sub_InheritanceDefintion"
"config.Parameter::Parameter_value_result_int" <-- "property.RepoObjectProperty_InheritanceType_InheritanceDefinition::sub_InheritanceType"
"config.Parameter::Parameter_value_result_int" <-- "property.RepoObjectProperty_InheritanceType_InheritanceDefinition::par_InheritanceType"
"config.Parameter::Parameter_value_result_int" <-- "property.RepoObjectColumnProperty_InheritanceType_InheritanceDefinition::sub_InheritanceType"
"config.Parameter::Parameter_value_result_int" <-- "property.RepoObjectColumnProperty_InheritanceType_InheritanceDefinition::par_InheritanceType"
"configT.Parameter_default::Parameter_default_value" <-- "config.Parameter::Parameter_default_value"footer The diagram is interactive and contains links.
@enduml

