@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:docs.repoobject_outputfilter_t.adoc[]" as docs.RepoObject_OutputFilter_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  AntoraComponent : (nvarchar(max))
  AntoraModule : (nvarchar(max))
  external_AntoraComponent : (nvarchar(128))
  external_AntoraModule : (nvarchar(128))
  external_DatabaseName : (nvarchar(128))
  is_DocsOutput : (int)
  - is_external : (bit)
  - is_ssas : (bit)
  - PumlEntityTopDefault : (nvarchar(max))
  - PumlEntityTopWorkaround : (nvarchar(max))
  RepoObject_DisplayName : (nvarchar(128))
  RepoObject_FullDisplayName2 : (nvarchar(257))
  - RepoObject_fullname : (nvarchar(261))
  - RepoObject_fullname2 : (nvarchar(257))
  - RepoObject_name : (nvarchar(128))
  - RepoObject_schema_name : (nvarchar(128))
  RepoObject_translation : (nvarchar(128))
  SysObject_type : (char(2))
  SysObject_type_name : (nvarchar(128))
  tables_isHidden : (bit)
  --
}

entity "puml-link:dhw:sqldb:docs.schema_puml.adoc[]" as docs.Schema_puml << V >> {
  - **RepoSchema_guid** : (uniqueidentifier)
  **cultures_name** : (nvarchar(10))
  - is_ssas : (bit)
  - PumlSchemaEr : (nvarchar(max))
  - PumlSchemaIndexEr : (nvarchar(max))
  PumlSchemaSsasEr : (nvarchar(max))
  - RepoSchema_name : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:docs.schema_ssasrelationlist.adoc[]" as docs.Schema_SsasRelationList << V >> {
  - **SchemaName** : (nvarchar(128))
  **cultures_name** : (nvarchar(10))
  SsasRelationList_PumlRelation : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:docs.ssas_pumlrelation.adoc[]" as docs.ssas_PumlRelation << V >> {
  delete_referential_action : (tinyint)
  ForeignKey_fullname : (nvarchar(517))
  - ForeignKey_guid : (uniqueidentifier)
  ForeignKey_name : (nvarchar(263))
  - PumlRelation : (nvarchar(max))
  referenced_ColumnName : (nvarchar(128))
  referenced_IndexPatternColumnDatatype : (nvarchar(500))
  referenced_IndexPatternColumnGuid : (varchar(36))
  referenced_IndexPatternColumnName : (nvarchar(128))
  referenced_ObjectName : (nvarchar(128))
  referenced_RepoObject_fullname : (nvarchar(517))
  referenced_RepoObject_fullname2 : (nvarchar(257))
  referenced_RepoObject_guid : (uniqueidentifier)
  referencing_ColumnName : (nvarchar(128))
  referencing_IndexPatternColumnDatatype : (nvarchar(500))
  referencing_IndexPatternColumnGuid : (varchar(36))
  referencing_IndexPatternColumnName : (nvarchar(128))
  referencing_ObjectName : (nvarchar(128))
  referencing_RepoObject_fullname : (nvarchar(517))
  referencing_RepoObject_fullname2 : (nvarchar(257))
  referencing_RepoObject_guid : (uniqueidentifier)
  relationships_crossFilteringBehavior : (nvarchar(500))
  relationships_fromCardinality : (nvarchar(500))
  - relationships_isActive : (bit)
  relationships_name : (nvarchar(500))
  relationships_toCardinality : (nvarchar(500))
  - SchemaName : (nvarchar(128))
  update_referential_action : (tinyint)
  --
}

docs.RepoObject_OutputFilter_T <.. docs.Schema_SsasRelationList
docs.Schema_SsasRelationList <.. docs.Schema_puml
docs.ssas_PumlRelation <.. docs.Schema_SsasRelationList
"docs.ssas_PumlRelation::SchemaName" <-- "docs.Schema_SsasRelationList::SchemaName"footer The diagram is interactive and contains links.
@enduml

