left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity config.ftv_get_parameter_value << IF >> {
  --
  Parameter_value_result : nvarchar(max)
  Parameter_value_result_date : date
  Parameter_value_result_datetime : datetime
  Parameter_value_result_int : int
  --
}

entity docs.fs_PumlHeaderLeftToRight << FN >> {
  --
  --
}

entity docs.Schema_EntityList << V >> {
  --
  EntityList_Puml : nvarchar(max)
  EntityList_PumlOnlyIndex : nvarchar(max)
  EntityList_PumlOnlyPK : nvarchar(max)
  EntityList_PumlOnlyPkOrIndex : nvarchar(max)
  EntityList_PumlOnlyPkOrNotHidden : nvarchar(max)
  * RepoObject_schema_name : nvarchar(128)
  --
}

entity docs.Schema_PlantUml_FkRefList << V >> {
  --
  FkRefList : nvarchar(max)
  SchemaName : nvarchar(128)
  --
}

entity docs.Schema_puml << V >> {
  --
  * PumlSchemaEr : nvarchar(max)
  * PumlSchemaIndexEr : nvarchar(max)
  PumlSchemaSsasEr : nvarchar(max)
  * RepoSchema_guid : uniqueidentifier
  * RepoSchema_name : nvarchar(128)
  --
}

entity docs.Schema_SsasRelationList << V >> {
  --
  * SchemaName : nvarchar(128)
  SsasRelationList_PumlRelation : nvarchar(max)
  --
}

entity repo.RepoSchema << U >> {
  * **RepoSchema_guid** : uniqueidentifier
  --
  * is_ssas : bit
  is_SysSchema_missing : bit
  RepoSchema_ms_description : nvarchar(4000)
  * RepoSchema_name : nvarchar(128)
  SysSchema_id : int
  * SysSchema_name : nvarchar(128)
  {abstract} has_different_sys_names : bit
  * {static} is_RepoSchema_name_uniqueidentifier : int
  * {static} is_SysSchema_name_uniqueidentifier : int
  --
}

config.ftv_get_parameter_value <.. docs.Schema_puml
docs.fs_PumlHeaderLeftToRight <.. docs.Schema_puml
docs.Schema_EntityList <.. docs.Schema_puml
docs.Schema_PlantUml_FkRefList <.. docs.Schema_puml
docs.Schema_SsasRelationList <.. docs.Schema_puml
repo.RepoSchema <.. docs.Schema_puml
repo.RepoSchema::RepoSchema_guid <-- docs.Schema_puml::RepoSchema_guid
repo.RepoSchema::RepoSchema_name <-- docs.Schema_puml::RepoSchema_name
