@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:docs.repoobject_columnlist_t.adoc[]" as docs.RepoObject_ColumnList_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  --
  AntoraColumnDetails : (nvarchar(max))
  AntoraNonPkColumnTableRows : (nvarchar(max))
  AntoraPkColumnTableRows : (nvarchar(max))
  is_external : (tinyint)
  PlantumlIndexColumns : (nvarchar(max))
  PlantumlNonPkEntityColumns : (nvarchar(max))
  PlantumlNonPkHiddenEntityColumns : (nvarchar(max))
  PlantumlNonPkIndexColumns : (nvarchar(max))
  PlantumlPkEntityColumns : (nvarchar(max))
  --
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_indexlist_t.adoc[]" as docs.RepoObject_IndexList_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  --
  AntoraIndexList : (nvarchar(max))
  PumlIndexList : (nvarchar(max))
  --
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_measurelist.adoc[]" as docs.RepoObject_MeasureList << V >> {
  **RepoObject_guid** : (uniqueidentifier)
  **cultures_name** : (nvarchar(10))
  --
  AntoraMeasureDetails : (nvarchar(max))
  is_external : (tinyint)
  PlantumlMeasures : (nvarchar(max))
  --
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_outputfilter_t.adoc[]" as docs.RepoObject_OutputFilter_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  --
  AntoraComponent : (nvarchar(max))
  AntoraModule : (nvarchar(max))
  external_AntoraComponent : (nvarchar(128))
  external_AntoraModule : (nvarchar(128))
  external_DatabaseName : (nvarchar(128))
  is_DocsOutput : (int)
  - is_external : (bit)
  - is_ssas : (bit)
  - PumlEntityTopDefault : (nvarchar(max))
  - PumlEntityTopWorkaround : (nvarchar(max))
  RepoObject_DisplayName : (nvarchar(128))
  RepoObject_FullDisplayName2 : (nvarchar(257))
  - RepoObject_fullname : (nvarchar(261))
  - RepoObject_fullname2 : (nvarchar(257))
  - RepoObject_name : (nvarchar(128))
  - RepoObject_schema_name : (nvarchar(128))
  RepoObject_translation : (nvarchar(128))
  SysObject_type : (char(2))
  SysObject_type_name : (nvarchar(128))
  tables_isHidden : (bit)
  --
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_entity.adoc[]" as docs.RepoObject_Plantuml_Entity << V >> {
  --
  - cultures_name : (nvarchar(10))
  - RepoObject_fullname2 : (nvarchar(257))
  - RepoObject_guid : (uniqueidentifier)
  - RepoObject_Puml : (nvarchar(max))
  - RepoObject_PumlOnlyIndex : (nvarchar(max))
  - RepoObject_PumlOnlyPK : (nvarchar(max))
  - RepoObject_PumlOnlyPkOrIndex : (nvarchar(max))
  - RepoObject_PumlOnlyPkOrIndexOrMeasure : (nvarchar(max))
  - RepoObject_PumlOnlyPkOrNotHidden : (nvarchar(max))
  - RepoObject_schema_name : (nvarchar(128))
  --
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_entity_t.adoc[]" as docs.RepoObject_Plantuml_Entity_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  --
  - RepoObject_fullname2 : (nvarchar(257))
  - RepoObject_Puml : (nvarchar(max))
  - RepoObject_PumlOnlyIndex : (nvarchar(max))
  - RepoObject_PumlOnlyPK : (nvarchar(max))
  - RepoObject_PumlOnlyPkOrIndex : (nvarchar(max))
  - RepoObject_PumlOnlyPkOrIndexOrMeasure : (nvarchar(max))
  - RepoObject_PumlOnlyPkOrNotHidden : (nvarchar(max))
  - RepoObject_schema_name : (nvarchar(128))
  --
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_repoobject_plantuml_entity_t.adoc[]" as docs.usp_PERSIST_RepoObject_Plantuml_Entity_T << P >> {
  --
  --
  --
}

docs.RepoObject_ColumnList_T <.. docs.RepoObject_Plantuml_Entity
docs.RepoObject_IndexList_T <.. docs.RepoObject_Plantuml_Entity
docs.RepoObject_MeasureList <.. docs.RepoObject_Plantuml_Entity
docs.RepoObject_OutputFilter_T <.. docs.RepoObject_Plantuml_Entity
docs.RepoObject_Plantuml_Entity <.. docs.RepoObject_Plantuml_Entity_T
docs.RepoObject_Plantuml_Entity <.. docs.usp_PERSIST_RepoObject_Plantuml_Entity_T
"docs.RepoObject_OutputFilter_T::cultures_name" <-- "docs.RepoObject_Plantuml_Entity::cultures_name"
"docs.RepoObject_OutputFilter_T::RepoObject_fullname2" <-- "docs.RepoObject_Plantuml_Entity::RepoObject_fullname2"
"docs.RepoObject_OutputFilter_T::RepoObject_guid" <-- "docs.RepoObject_Plantuml_Entity::RepoObject_guid"
"docs.RepoObject_OutputFilter_T::RepoObject_schema_name" <-- "docs.RepoObject_Plantuml_Entity::RepoObject_schema_name"
"docs.RepoObject_Plantuml_Entity::cultures_name" <-- "docs.RepoObject_Plantuml_Entity_T::cultures_name"
"docs.RepoObject_Plantuml_Entity::RepoObject_fullname2" <-- "docs.RepoObject_Plantuml_Entity_T::RepoObject_fullname2"
"docs.RepoObject_Plantuml_Entity::RepoObject_guid" <-- "docs.RepoObject_Plantuml_Entity_T::RepoObject_guid"
"docs.RepoObject_Plantuml_Entity::RepoObject_Puml" <-- "docs.RepoObject_Plantuml_Entity_T::RepoObject_Puml"
"docs.RepoObject_Plantuml_Entity::RepoObject_PumlOnlyIndex" <-- "docs.RepoObject_Plantuml_Entity_T::RepoObject_PumlOnlyIndex"
"docs.RepoObject_Plantuml_Entity::RepoObject_PumlOnlyPK" <-- "docs.RepoObject_Plantuml_Entity_T::RepoObject_PumlOnlyPK"
"docs.RepoObject_Plantuml_Entity::RepoObject_PumlOnlyPkOrIndex" <-- "docs.RepoObject_Plantuml_Entity_T::RepoObject_PumlOnlyPkOrIndex"
"docs.RepoObject_Plantuml_Entity::RepoObject_PumlOnlyPkOrIndexOrMeasure" <-- "docs.RepoObject_Plantuml_Entity_T::RepoObject_PumlOnlyPkOrIndexOrMeasure"
"docs.RepoObject_Plantuml_Entity::RepoObject_PumlOnlyPkOrNotHidden" <-- "docs.RepoObject_Plantuml_Entity_T::RepoObject_PumlOnlyPkOrNotHidden"
"docs.RepoObject_Plantuml_Entity::RepoObject_schema_name" <-- "docs.RepoObject_Plantuml_Entity_T::RepoObject_schema_name"
@enduml

