@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity "[[{site-url}/{page-component-name}/current/{page-module}/docs.fs_cleanStringForPuml.html docs.fs_cleanStringForPuml]]" as docs.fs_cleanStringForPuml << FN >> {
  --
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/docs.ObjectRefCyclic_ObjectRefList.html docs.ObjectRefCyclic_ObjectRefList]]" as docs.ObjectRefCyclic_ObjectRefList << V >> {
  --
  PumlObjectRefList : (nvarchar(max))
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/docs.RepoObject_ColumnList.html docs.RepoObject_ColumnList]]" as docs.RepoObject_ColumnList << V >> {
  --
  AntoraColumnDetails : (nvarchar(max))
  AntoraNonPkColumnTableRows : (nvarchar(max))
  AntoraPkColumnTableRows : (nvarchar(max))
  PlantumlIndexColumns : (nvarchar(max))
  PlantumlNonPkEntityColumns : (nvarchar(max))
  PlantumlNonPkHiddenEntityColumns : (nvarchar(max))
  PlantumlNonPkIndexColumns : (nvarchar(max))
  PlantumlPkEntityColumns : (nvarchar(max))
  - RepoObject_guid : (uniqueidentifier)
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/docs.RepoObject_IndexList.html docs.RepoObject_IndexList]]" as docs.RepoObject_IndexList << V >> {
  **RepoObject_guid** : (uniqueidentifier)
  --
  AntoraIndexList : (nvarchar(max))
  PumlIndexList : (nvarchar(max))
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/docs.RepoObject_MeasureList.html docs.RepoObject_MeasureList]]" as docs.RepoObject_MeasureList << V >> {
  --
  AntoraMeasureDetails : (nvarchar(max))
  PlantumlMeasures : (nvarchar(max))
  - RepoObject_guid : (uniqueidentifier)
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/docs.RepoObject_Plantuml_ColRefList_1_1.html docs.RepoObject_Plantuml_ColRefList_1_1]]" as docs.RepoObject_Plantuml_ColRefList_1_1 << V >> {
  --
  ColRefList : (nvarchar(max))
  - RepoObject_guid : (uniqueidentifier)
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/docs.RepoObject_Plantuml_Entity.html docs.RepoObject_Plantuml_Entity]]" as docs.RepoObject_Plantuml_Entity << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
  - RepoObject_fullname2 : (nvarchar(257))
  - RepoObject_Puml : (nvarchar(max))
  - RepoObject_PumlOnlyIndex : (nvarchar(max))
  - RepoObject_PumlOnlyPK : (nvarchar(max))
  - RepoObject_PumlOnlyPkOrIndex : (nvarchar(max))
  - RepoObject_PumlOnlyPkOrNotHidden : (nvarchar(max))
  - RepoObject_schema_name : (nvarchar(128))
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/docs.RepoObject_PlantUml_FkRefList.html docs.RepoObject_PlantUml_FkRefList]]" as docs.RepoObject_PlantUml_FkRefList << V >> {
  --
  FkRefList : (nvarchar(max))
  RepoObject_fullname2 : (nvarchar(257))
  RepoObject_guid : (uniqueidentifier)
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/docs.RepoObject_Plantuml_ObjectRefList_0_30.html docs.RepoObject_Plantuml_ObjectRefList_0_30]]" as docs.RepoObject_Plantuml_ObjectRefList_0_30 << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
  ObjectRefList : (nvarchar(max))
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/docs.RepoObject_Plantuml_ObjectRefList_1_1.html docs.RepoObject_Plantuml_ObjectRefList_1_1]]" as docs.RepoObject_Plantuml_ObjectRefList_1_1 << V >> {
  --
  ObjectRefList : (nvarchar(max))
  - RepoObject_guid : (uniqueidentifier)
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/docs.RepoObject_Plantuml_ObjectRefList_30_0.html docs.RepoObject_Plantuml_ObjectRefList_30_0]]" as docs.RepoObject_Plantuml_ObjectRefList_30_0 << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
  ObjectRefList : (nvarchar(max))
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/docs.Schema_PlantUml_FkRefList.html docs.Schema_PlantUml_FkRefList]]" as docs.Schema_PlantUml_FkRefList << V >> {
  --
  FkRefList : (nvarchar(max))
  SchemaName : (nvarchar(128))
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/docs.ssas_PumlRelation.html docs.ssas_PumlRelation]]" as docs.ssas_PumlRelation << V >> {
  --
  delete_referential_action : (tinyint)
  ForeignKey_fullname : (nvarchar(517))
  - ForeignKey_guid : (uniqueidentifier)
  ForeignKey_name : (nvarchar(263))
  - PumlRelation : (nvarchar(max))
  referenced_ColumnName : (nvarchar(128))
  referenced_IndexPatternColumnDatatype : (nvarchar(500))
  referenced_IndexPatternColumnGuid : (varchar(36))
  referenced_IndexPatternColumnName : (nvarchar(128))
  referenced_ObjectName : (nvarchar(128))
  referenced_RepoObject_fullname : (nvarchar(517))
  referenced_RepoObject_fullname2 : (nvarchar(257))
  referenced_RepoObject_guid : (uniqueidentifier)
  referencing_ColumnName : (nvarchar(128))
  referencing_IndexPatternColumnDatatype : (nvarchar(500))
  referencing_IndexPatternColumnGuid : (varchar(36))
  referencing_IndexPatternColumnName : (nvarchar(128))
  referencing_ObjectName : (nvarchar(128))
  referencing_RepoObject_fullname : (nvarchar(517))
  referencing_RepoObject_fullname2 : (nvarchar(257))
  referencing_RepoObject_guid : (uniqueidentifier)
  relationships_crossFilteringBehavior : (nvarchar(500))
  relationships_fromCardinality : (nvarchar(500))
  - relationships_isActive : (bit)
  relationships_name : (nvarchar(500))
  relationships_toCardinality : (nvarchar(500))
  - SchemaName : (nvarchar(128))
  update_referential_action : (tinyint)
  --
  --
}

docs.fs_cleanStringForPuml <.. docs.RepoObject_ColumnList
docs.fs_cleanStringForPuml <.. docs.RepoObject_IndexList
docs.fs_cleanStringForPuml <.. docs.RepoObject_Plantuml_Entity
docs.fs_cleanStringForPuml <.. docs.RepoObject_Plantuml_ObjectRefList_1_1
docs.fs_cleanStringForPuml <.. docs.RepoObject_Plantuml_ObjectRefList_30_0
docs.fs_cleanStringForPuml <.. docs.RepoObject_Plantuml_ObjectRefList_0_30
docs.fs_cleanStringForPuml <.. docs.RepoObject_PlantUml_FkRefList
docs.fs_cleanStringForPuml <.. docs.ssas_PumlRelation
docs.fs_cleanStringForPuml <.. docs.Schema_PlantUml_FkRefList
docs.fs_cleanStringForPuml <.. docs.ObjectRefCyclic_ObjectRefList
docs.fs_cleanStringForPuml <.. docs.RepoObject_Plantuml_ColRefList_1_1
docs.fs_cleanStringForPuml <.. docs.RepoObject_MeasureList

footer
to view a reduced diagram in original size and to be able to click on the links:
open the diagram in a new tab via the Context menu.
end footer

@enduml

