@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:docs.antoraindexsemanticgroup.adoc[]" as docs.AntoraIndexSemanticgroup << V >> {
  --
  AntoraIndexSemanticgroup : (nvarchar(max))
  cultures_name : (nvarchar(10))
  - fixvalue : (int)
  IndexSemanticGroup : (nvarchar(512))
  --
  --
}

entity "puml-link:dhw:sqldb:docs.antoraindexsemanticgrouppatterndatatype.adoc[]" as docs.AntoraIndexSemanticgroupPatterndatatype << V >> {
  **IndexSemanticGroup** : (nvarchar(512))
  **IndexPatternColumnDatatype** : (nvarchar(4000))
  --
  AntoraIndexSemanticgroupPatterndatatype : (nvarchar(max))
  cultures_name : (nvarchar(10))
  --
  --
}

entity "puml-link:dhw:sqldb:docs.fs_cleanstringforanchorid.adoc[]" as docs.fs_cleanStringForAnchorId << FN >> {
  --
  --
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_columnlist.adoc[]" as docs.RepoObject_ColumnList << V >> {
  --
  AntoraColumnDetails : (nvarchar(max))
  AntoraNonPkColumnTableRows : (nvarchar(max))
  AntoraPkColumnTableRows : (nvarchar(max))
  - cultures_name : (nvarchar(10))
  is_external : (tinyint)
  PlantumlIndexColumns : (nvarchar(max))
  PlantumlNonPkEntityColumns : (nvarchar(max))
  PlantumlNonPkHiddenEntityColumns : (nvarchar(max))
  PlantumlNonPkIndexColumns : (nvarchar(max))
  PlantumlPkEntityColumns : (nvarchar(max))
  - RepoObject_guid : (uniqueidentifier)
  --
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_indexlist.adoc[]" as docs.RepoObject_IndexList << V >> {
  **RepoObject_guid** : (uniqueidentifier)
  **cultures_name** : (nvarchar(10))
  --
  AntoraIndexList : (nvarchar(max))
  PumlIndexList : (nvarchar(max))
  --
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_measurelist.adoc[]" as docs.RepoObject_MeasureList << V >> {
  **RepoObject_guid** : (uniqueidentifier)
  **cultures_name** : (nvarchar(10))
  --
  AntoraMeasureDetails : (nvarchar(max))
  is_external : (tinyint)
  PlantumlMeasures : (nvarchar(max))
  --
  --
}

entity "puml-link:dhw:sqldb:docs.unit_2.adoc[]" as docs.Unit_2 << V >> {
  --
  AntoraComponent : (nvarchar(max))
  AntoraModule : (nvarchar(max))
  AntoraPage : (nvarchar(4000))
  AntoraSectionId : (nvarchar(4000))
  AntoraSiteUrl : (nvarchar(max))
  AntoraVersion : (nvarchar(max))
  Object_fullname2 : (nvarchar(257))
  Object_Type : (varchar(2))
  Unit_ColummName : (nvarchar(128))
  Unit_Description : (nvarchar(max))
  Unit_DisplayFolder : (nvarchar(500))
  Unit_Expression : (nvarchar(max))
  Unit_FormatString : (nvarchar(500))
  - Unit_fullname2 : (nvarchar(638))
  - Unit_guid : (uniqueidentifier)
  Unit_isHidden : (bit)
  Unit_IsKey : (bit)
  Unit_IsSsas : (bit)
  Unit_IsUnique : (bit)
  - Unit_Metatype : (varchar(7))
  - Unit_Name : (nvarchar(500))
  Unit_ObjectName : (nvarchar(128))
  - Unit_Schema : (nvarchar(128))
  Unit_SummarizeBy : (nvarchar(500))
  Unit_TypeName : (nvarchar(128))
  --
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_referencedreferencing.adoc[]" as reference.RepoObjectColumn_ReferencedReferencing << V >> {
  --
  - referenced_AntoraXref : (nvarchar(max))
  referenced_external_AntoraComponent : (nvarchar(128))
  referenced_external_AntoraModule : (nvarchar(128))
  - Referenced_fullname : (nvarchar(261))
  - Referenced_fullname2 : (nvarchar(257))
  - Referenced_guid : (uniqueidentifier)
  - referenced_is_external : (bit)
  Referenced_RepoObject_guid : (uniqueidentifier)
  Referenced_type : (char(2))
  - ReferencedColumn_fullname : (nvarchar(392))
  - ReferencedColumn_fullname2 : (nvarchar(386))
  ReferencedColumn_name : (nvarchar(128))
  - referencing_AntoraXref : (nvarchar(max))
  referencing_external_AntoraComponent : (nvarchar(128))
  referencing_external_AntoraModule : (nvarchar(128))
  - Referencing_fullname : (nvarchar(261))
  - Referencing_fullname2 : (nvarchar(257))
  - Referencing_guid : (uniqueidentifier)
  - referencing_is_external : (bit)
  Referencing_RepoObject_guid : (uniqueidentifier)
  Referencing_type : (char(2))
  - ReferencingColumn_fullname : (nvarchar(392))
  - ReferencingColumn_fullname2 : (nvarchar(386))
  ReferencingColumn_name : (nvarchar(128))
  --
  --
}

entity "puml-link:dhw:sqldb:repo.foreignkey_gross.adoc[]" as repo.ForeignKey_gross << V >> {
  --
  delete_referential_action : (tinyint)
  ForeignKey_fullname : (nvarchar(517))
  ForeignKey_guid : (uniqueidentifier)
  ForeignKey_name : (nvarchar(128))
  - is_MatchingDatatypePattern : (int)
  - referenced_AntoraXref : (nvarchar(4000))
  referenced_index_guid : (uniqueidentifier)
  referenced_index_name : (nvarchar(450))
  referenced_IndexPatternColumnDatatype : (nvarchar(4000))
  referenced_IndexPatternColumnName : (nvarchar(4000))
  referenced_RepoObject_fullname : (nvarchar(261))
  referenced_RepoObject_fullname2 : (nvarchar(257))
  referenced_RepoObject_guid : (uniqueidentifier)
  referenced_SysObject_name : (nvarchar(128))
  referenced_SysObject_schema_name : (nvarchar(128))
  referencing_index_guid : (uniqueidentifier)
  referencing_index_name : (nvarchar(450))
  referencing_IndexPatternColumnDatatype : (nvarchar(4000))
  referencing_IndexPatternColumnName : (nvarchar(4000))
  referencing_RepoObject_fullname : (nvarchar(261))
  referencing_RepoObject_fullname2 : (nvarchar(257))
  referencing_RepoObject_guid : (uniqueidentifier)
  referencing_SysObject_name : (nvarchar(128))
  referencing_SysObject_schema_name : (nvarchar(128))
  update_referential_action : (tinyint)
  --
  --
}

docs.fs_cleanStringForAnchorId <.. reference.RepoObjectColumn_ReferencedReferencing
docs.fs_cleanStringForAnchorId <.. docs.RepoObject_IndexList
docs.fs_cleanStringForAnchorId <.. docs.RepoObject_ColumnList
docs.fs_cleanStringForAnchorId <.. repo.ForeignKey_gross
docs.fs_cleanStringForAnchorId <.. docs.Unit_2
docs.fs_cleanStringForAnchorId <.. docs.AntoraIndexSemanticgroup
docs.fs_cleanStringForAnchorId <.. docs.AntoraIndexSemanticgroupPatterndatatype
docs.fs_cleanStringForAnchorId <.. docs.RepoObject_MeasureList

@enduml

