left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity docs.RepoObject_ColumnList << V >> {
  --
  AntoraColumnDetails : nvarchar(max)
  AntoraNonPkColumnTableRows : nvarchar(max)
  AntoraPkColumnTableRows : nvarchar(max)
  PlantumlIndexColumns : nvarchar(max)
  PlantumlNonPkEntityColumns : nvarchar(max)
  PlantumlNonPkHiddenEntityColumns : nvarchar(max)
  PlantumlNonPkIndexColumns : nvarchar(max)
  PlantumlPkEntityColumns : nvarchar(max)
  * RepoObject_guid : uniqueidentifier
  --
}

entity docs.RepoObject_ColumnList_T {
  * **RepoObject_guid** : uniqueidentifier
  --
  AntoraColumnDetails : nvarchar(max)
  AntoraNonPkColumnTableRows : nvarchar(max)
  AntoraPkColumnTableRows : nvarchar(max)
  PlantumlIndexColumns : nvarchar(max)
  PlantumlNonPkEntityColumns : nvarchar(max)
  PlantumlNonPkHiddenEntityColumns : nvarchar(max)
  PlantumlNonPkIndexColumns : nvarchar(max)
  PlantumlPkEntityColumns : nvarchar(max)
  --
}

docs.RepoObject_ColumnList <.. docs.85AC3586-9B83-4474-AF3D-ED54F04062CA
docs.RepoObject_ColumnList::AntoraColumnDetails <-- docs.85AC3586-9B83-4474-AF3D-ED54F04062CA::E40E81A4-06A5-4AF4-A494-3D70700A60A0
docs.RepoObject_ColumnList::AntoraNonPkColumnTableRows <-- docs.85AC3586-9B83-4474-AF3D-ED54F04062CA::962F4C7B-B0BD-40A8-BFAE-3058D01CA7E0
docs.RepoObject_ColumnList::AntoraPkColumnTableRows <-- docs.85AC3586-9B83-4474-AF3D-ED54F04062CA::36368006-72A8-4106-94E0-751F4847F150
docs.RepoObject_ColumnList::PlantumlIndexColumns <-- docs.85AC3586-9B83-4474-AF3D-ED54F04062CA::3886730C-EEE1-457F-A44F-B0074937E841
docs.RepoObject_ColumnList::PlantumlNonPkEntityColumns <-- docs.85AC3586-9B83-4474-AF3D-ED54F04062CA::EA78BD78-6B58-4F66-ADFC-4C1D76019330
docs.RepoObject_ColumnList::PlantumlNonPkHiddenEntityColumns <-- docs.85AC3586-9B83-4474-AF3D-ED54F04062CA::46F3ED84-DFD6-4E99-91ED-EA568453818E
docs.RepoObject_ColumnList::PlantumlNonPkIndexColumns <-- docs.85AC3586-9B83-4474-AF3D-ED54F04062CA::F66081A3-7C2D-42B8-AA42-99ADA2B2386F
docs.RepoObject_ColumnList::PlantumlPkEntityColumns <-- docs.85AC3586-9B83-4474-AF3D-ED54F04062CA::B1D4D7DC-9BEE-4967-816F-B3FE53924BC1
docs.RepoObject_ColumnList::RepoObject_guid <-- docs.85AC3586-9B83-4474-AF3D-ED54F04062CA::4899C752-73D6-4439-8429-38508ACC858F
