@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:dmdocs.unit.adoc[]" as dmdocs.unit << V >> {
  --
  AntoraComponent : (nvarchar(max))
  AntoraModule : (nvarchar(max))
  AntoraPage : (nvarchar(4000))
  AntoraSectionId : (nvarchar(4000))
  AntoraSiteUrl : (nvarchar(max))
  AntoraVersion : (nvarchar(max))
  Object_fullname2 : (nvarchar(257))
  Object_Type : (varchar(2))
  Unit_ColummName : (nvarchar(128))
  Unit_Description : (nvarchar(max))
  Unit_DisplayFolder : (nvarchar(500))
  Unit_Expression : (nvarchar(max))
  Unit_FormatString : (nvarchar(500))
  - Unit_fullname2 : (nvarchar(638))
  - Unit_guid : (uniqueidentifier)
  Unit_isHidden : (bit)
  Unit_IsKey : (bit)
  Unit_IsSsas : (bit)
  Unit_IsUnique : (bit)
  - Unit_Metatype : (varchar(7))
  - Unit_Name : (nvarchar(500))
  Unit_ObjectName : (nvarchar(128))
  - Unit_Schema : (nvarchar(128))
  Unit_SummarizeBy : (nvarchar(500))
  Unit_TypeName : (nvarchar(128))
  - Unit_Url : (nvarchar(max))
  --
  --
}

entity "puml-link:dhw:sqldb:docs.Unit_2.adoc[]" as docs.Unit_2 << V >> {
  --
  AntoraComponent : (nvarchar(max))
  AntoraModule : (nvarchar(max))
  AntoraPage : (nvarchar(4000))
  AntoraSectionId : (nvarchar(4000))
  AntoraSiteUrl : (nvarchar(max))
  AntoraVersion : (nvarchar(max))
  Object_fullname2 : (nvarchar(257))
  Object_Type : (varchar(2))
  Unit_ColummName : (nvarchar(128))
  Unit_Description : (nvarchar(max))
  Unit_DisplayFolder : (nvarchar(500))
  Unit_Expression : (nvarchar(max))
  Unit_FormatString : (nvarchar(500))
  - Unit_fullname2 : (nvarchar(638))
  - Unit_guid : (uniqueidentifier)
  Unit_isHidden : (bit)
  Unit_IsKey : (bit)
  Unit_IsSsas : (bit)
  Unit_IsUnique : (bit)
  - Unit_Metatype : (varchar(7))
  - Unit_Name : (nvarchar(500))
  Unit_ObjectName : (nvarchar(128))
  - Unit_Schema : (nvarchar(128))
  Unit_SummarizeBy : (nvarchar(500))
  Unit_TypeName : (nvarchar(128))
  --
  --
}

entity "puml-link:dhw:sqldb:docs.Unit_3.adoc[]" as docs.Unit_3 << V >> {
  --
  AntoraComponent : (nvarchar(max))
  AntoraModule : (nvarchar(max))
  AntoraPage : (nvarchar(4000))
  AntoraSectionId : (nvarchar(4000))
  AntoraSiteUrl : (nvarchar(max))
  AntoraVersion : (nvarchar(max))
  Object_fullname2 : (nvarchar(257))
  Object_Type : (varchar(2))
  Unit_ColummName : (nvarchar(128))
  Unit_Description : (nvarchar(max))
  Unit_DisplayFolder : (nvarchar(500))
  Unit_Expression : (nvarchar(max))
  Unit_FormatString : (nvarchar(500))
  - Unit_fullname2 : (nvarchar(638))
  - Unit_guid : (uniqueidentifier)
  Unit_isHidden : (bit)
  Unit_IsKey : (bit)
  Unit_IsSsas : (bit)
  Unit_IsUnique : (bit)
  - Unit_Metatype : (varchar(7))
  - Unit_Name : (nvarchar(500))
  Unit_ObjectName : (nvarchar(128))
  - Unit_Schema : (nvarchar(128))
  Unit_SummarizeBy : (nvarchar(500))
  Unit_TypeName : (nvarchar(128))
  - Unit_Url : (nvarchar(max))
  --
  --
}

docs.Unit_2 <.. docs.Unit_3
docs.Unit_3 <.. dmdocs.unit
"docs.Unit_2::AntoraComponent" <-- "docs.Unit_3::AntoraComponent"
"docs.Unit_2::AntoraModule" <-- "docs.Unit_3::AntoraModule"
"docs.Unit_2::AntoraPage" <-- "docs.Unit_3::AntoraPage"
"docs.Unit_2::AntoraSectionId" <-- "docs.Unit_3::AntoraSectionId"
"docs.Unit_2::AntoraSiteUrl" <-- "docs.Unit_3::AntoraSiteUrl"
"docs.Unit_2::AntoraVersion" <-- "docs.Unit_3::AntoraVersion"
"docs.Unit_2::Object_fullname2" <-- "docs.Unit_3::Object_fullname2"
"docs.Unit_2::Object_Type" <-- "docs.Unit_3::Object_Type"
"docs.Unit_2::Unit_ColummName" <-- "docs.Unit_3::Unit_ColummName"
"docs.Unit_2::Unit_Description" <-- "docs.Unit_3::Unit_Description"
"docs.Unit_2::Unit_DisplayFolder" <-- "docs.Unit_3::Unit_DisplayFolder"
"docs.Unit_2::Unit_Expression" <-- "docs.Unit_3::Unit_Expression"
"docs.Unit_2::Unit_FormatString" <-- "docs.Unit_3::Unit_FormatString"
"docs.Unit_2::Unit_fullname2" <-- "docs.Unit_3::Unit_fullname2"
"docs.Unit_2::Unit_guid" <-- "docs.Unit_3::Unit_guid"
"docs.Unit_2::Unit_isHidden" <-- "docs.Unit_3::Unit_isHidden"
"docs.Unit_2::Unit_IsKey" <-- "docs.Unit_3::Unit_IsKey"
"docs.Unit_2::Unit_IsSsas" <-- "docs.Unit_3::Unit_IsSsas"
"docs.Unit_2::Unit_IsUnique" <-- "docs.Unit_3::Unit_IsUnique"
"docs.Unit_2::Unit_Metatype" <-- "docs.Unit_3::Unit_Metatype"
"docs.Unit_2::Unit_Name" <-- "docs.Unit_3::Unit_Name"
"docs.Unit_2::Unit_ObjectName" <-- "docs.Unit_3::Unit_ObjectName"
"docs.Unit_2::Unit_Schema" <-- "docs.Unit_3::Unit_Schema"
"docs.Unit_2::Unit_SummarizeBy" <-- "docs.Unit_3::Unit_SummarizeBy"
"docs.Unit_2::Unit_TypeName" <-- "docs.Unit_3::Unit_TypeName"
"docs.Unit_3::AntoraComponent" <-- "dmdocs.unit::AntoraComponent"
"docs.Unit_3::AntoraModule" <-- "dmdocs.unit::AntoraModule"
"docs.Unit_3::AntoraPage" <-- "dmdocs.unit::AntoraPage"
"docs.Unit_3::AntoraSectionId" <-- "dmdocs.unit::AntoraSectionId"
"docs.Unit_3::AntoraSiteUrl" <-- "dmdocs.unit::AntoraSiteUrl"
"docs.Unit_3::AntoraVersion" <-- "dmdocs.unit::AntoraVersion"
"docs.Unit_3::Object_fullname2" <-- "dmdocs.unit::Object_fullname2"
"docs.Unit_3::Object_Type" <-- "dmdocs.unit::Object_Type"
"docs.Unit_3::Unit_ColummName" <-- "dmdocs.unit::Unit_ColummName"
"docs.Unit_3::Unit_Description" <-- "dmdocs.unit::Unit_Description"
"docs.Unit_3::Unit_DisplayFolder" <-- "dmdocs.unit::Unit_DisplayFolder"
"docs.Unit_3::Unit_Expression" <-- "dmdocs.unit::Unit_Expression"
"docs.Unit_3::Unit_FormatString" <-- "dmdocs.unit::Unit_FormatString"
"docs.Unit_3::Unit_fullname2" <-- "dmdocs.unit::Unit_fullname2"
"docs.Unit_3::Unit_guid" <-- "dmdocs.unit::Unit_guid"
"docs.Unit_3::Unit_isHidden" <-- "dmdocs.unit::Unit_isHidden"
"docs.Unit_3::Unit_IsKey" <-- "dmdocs.unit::Unit_IsKey"
"docs.Unit_3::Unit_IsSsas" <-- "dmdocs.unit::Unit_IsSsas"
"docs.Unit_3::Unit_IsUnique" <-- "dmdocs.unit::Unit_IsUnique"
"docs.Unit_3::Unit_Metatype" <-- "dmdocs.unit::Unit_Metatype"
"docs.Unit_3::Unit_Name" <-- "dmdocs.unit::Unit_Name"
"docs.Unit_3::Unit_ObjectName" <-- "dmdocs.unit::Unit_ObjectName"
"docs.Unit_3::Unit_Schema" <-- "dmdocs.unit::Unit_Schema"
"docs.Unit_3::Unit_SummarizeBy" <-- "dmdocs.unit::Unit_SummarizeBy"
"docs.Unit_3::Unit_TypeName" <-- "dmdocs.unit::Unit_TypeName"
"docs.Unit_3::Unit_Url" <-- "dmdocs.unit::Unit_Url"
@enduml

