@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity "puml-link:config.fs_get_parameter_value.adoc[prefix=..]" as config.fs_get_parameter_value << FN >> {
  --
  --
  --
}

entity "puml-link:docs.RepoObject_OutputFilter.adoc[prefix=..]" as docs.RepoObject_OutputFilter << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
  is_DocsOutput : (int)
  - is_ssas : (bit)
  - RepoObject_fullname : (nvarchar(261))
  - RepoObject_fullname2 : (nvarchar(257))
  - RepoObject_name : (nvarchar(128))
  - RepoObject_schema_name : (nvarchar(128))
  SysObject_type : (char(2))
  SysObject_type_name : (nvarchar(128))
  --
  --
}

entity "puml-link:docs.usp_AntoraExport.adoc[prefix=..]" as docs.usp_AntoraExport << P >> {
  --
  --
  --
}

entity "puml-link:docs.usp_AntoraExport_ObjectPuml.adoc[prefix=..]" as docs.usp_AntoraExport_ObjectPuml << P >> {
  --
  --
  --
}

entity "puml-link:docs.usp_PERSIST_RepoObject_Plantuml_Entity_T.adoc[prefix=..]" as docs.usp_PERSIST_RepoObject_Plantuml_Entity_T << P >> {
  --
  --
  --
}

entity "puml-link:docs.usp_PERSIST_RepoObject_Plantuml_T.adoc[prefix=..]" as docs.usp_PERSIST_RepoObject_Plantuml_T << P >> {
  --
  --
  --
}

entity "puml-link:logs.usp_ExecutionLog_insert.adoc[prefix=..]" as logs.usp_ExecutionLog_insert << P >> {
  --
  --
  --
}

entity "puml-link:repo.RepoSchema.adoc[prefix=..]" as repo.RepoSchema << U >> {
  - **RepoSchema_guid** : (uniqueidentifier)
  --
  - is_ssas : (bit)
  is_SysSchema_missing : (bit)
  RepoSchema_ms_description : (nvarchar(4000))
  - RepoSchema_name : (nvarchar(128))
  SysSchema_id : (int)
  - SysSchema_name : (nvarchar(128))
  ~ has_different_sys_names : (bit)
  # is_RepoSchema_name_uniqueidentifier : (int)
  # is_SysSchema_name_uniqueidentifier : (int)
  --
  --
}

config.fs_get_parameter_value <.. docs.usp_AntoraExport_ObjectPuml
docs.RepoObject_OutputFilter <.. docs.usp_AntoraExport_ObjectPuml
docs.usp_AntoraExport_ObjectPuml <.. docs.usp_AntoraExport
docs.usp_PERSIST_RepoObject_Plantuml_Entity_T <.. docs.usp_AntoraExport_ObjectPuml
docs.usp_PERSIST_RepoObject_Plantuml_T <.. docs.usp_AntoraExport_ObjectPuml
logs.usp_ExecutionLog_insert <.. docs.usp_AntoraExport_ObjectPuml
repo.RepoSchema <.. docs.usp_AntoraExport_ObjectPuml

footer
to view a reduced diagram in original size and to be able to click on the links:
open the diagram in a new tab via the Context menu.
end footer

@enduml

