@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:docs.antoraindexsemanticgroup.adoc[]" as docs.AntoraIndexSemanticgroup << V >> {
  AntoraIndexSemanticgroup : (nvarchar(max))
  cultures_name : (nvarchar(10))
  IndexSemanticGroup : (nvarchar(512))
  --
}

entity "puml-link:dhw:sqldb:docs.antoraindexsemanticgrouppatterndatatype.adoc[]" as docs.AntoraIndexSemanticgroupPatterndatatype << V >> {
  **IndexSemanticGroup** : (nvarchar(512))
  **IndexPatternColumnDatatype** : (nvarchar(4000))
  AntoraIndexSemanticgroupPatterndatatype : (nvarchar(max))
  cultures_name : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.fs_cleanstringforanchorid.adoc[]" as docs.fs_cleanStringForAnchorId << FN >> {
  --
}

entity "puml-link:dhw:sqldb:docs.fs_cleanstringforfilename.adoc[]" as docs.fs_cleanStringForFilename << FN >> {
  --
}

entity "puml-link:dhw:sqldb:docs.fs_cleanstringforheader.adoc[]" as docs.fs_cleanStringForHeader << FN >> {
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_outputfilter_t.adoc[]" as docs.RepoObject_OutputFilter_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  AntoraComponent : (nvarchar(max))
  AntoraModule : (nvarchar(max))
  external_AntoraComponent : (nvarchar(128))
  external_AntoraModule : (nvarchar(128))
  external_DatabaseName : (nvarchar(128))
  is_DocsOutput : (int)
  - is_external : (bit)
  - is_ssas : (bit)
  - PumlEntityTopDefault : (nvarchar(max))
  - PumlEntityTopWorkaround : (nvarchar(max))
  RepoObject_DisplayName : (nvarchar(128))
  RepoObject_FullDisplayName2 : (nvarchar(257))
  - RepoObject_fullname : (nvarchar(261))
  - RepoObject_fullname2 : (nvarchar(257))
  - RepoObject_name : (nvarchar(128))
  - RepoObject_schema_name : (nvarchar(128))
  RepoObject_translation : (nvarchar(128))
  SysObject_type : (char(2))
  SysObject_type_name : (nvarchar(128))
  tables_isHidden : (bit)
  --
}

entity "puml-link:dhw:sqldb:repo.index_gross.adoc[]" as repo.Index_gross << V >> {
  AntoraIndexColumnList : (nvarchar(max))
  ColumnList : (nvarchar(max))
  ConstraintColumnList : (nvarchar(max))
  DbmlIndexColumnList : (nvarchar(max))
  - index_guid : (uniqueidentifier)
  index_name : (nvarchar(450))
  index_type : (tinyint)
  IndexPatternColumnDatatype : (nvarchar(4000))
  IndexPatternColumnName : (nvarchar(4000))
  IndexSemanticGroup : (nvarchar(512))
  - is_DocsExclude : (bit)
  is_DocsOutput : (int)
  is_index_disabled : (bit)
  is_index_primary_key : (bit)
  is_index_real : (bit)
  is_index_unique : (bit)
  is_persistence : (bit)
  is_repo_managed : (bit)
  parent_RepoObject_guid : (uniqueidentifier)
  PersistenceWhereColumnList : (nvarchar(max))
  PumlIndexColumnList : (nvarchar(max))
  referenced_index_guid : (uniqueidentifier)
  - RepoObject_fullname : (nvarchar(261))
  - RepoObject_fullname2 : (nvarchar(257))
  RowNumber_PatternPerParentObject : (bigint)
  RowNumber_PkPerParentObject : (bigint)
  - SysObject_fullname : (nvarchar(261))
  - SysObject_fullname2 : (nvarchar(257))
  SysObject_id : (int)
  - SysObject_name : (nvarchar(128))
  - SysObject_schema_name : (nvarchar(128))
  SysObject_type : (char(2))
  --
}

docs.AntoraIndexSemanticgroupPatterndatatype <.. docs.AntoraIndexSemanticgroup
docs.fs_cleanStringForAnchorId <.. docs.AntoraIndexSemanticgroupPatterndatatype
docs.fs_cleanStringForFilename <.. docs.AntoraIndexSemanticgroupPatterndatatype
docs.fs_cleanStringForHeader <.. docs.AntoraIndexSemanticgroupPatterndatatype
docs.RepoObject_OutputFilter_T <.. docs.AntoraIndexSemanticgroupPatterndatatype
repo.Index_gross <.. docs.AntoraIndexSemanticgroupPatterndatatype
"docs.AntoraIndexSemanticgroupPatterndatatype::cultures_name" <-- "docs.AntoraIndexSemanticgroup::cultures_name"
"docs.AntoraIndexSemanticgroupPatterndatatype::IndexSemanticGroup" <-- "docs.AntoraIndexSemanticgroup::IndexSemanticGroup"
"docs.RepoObject_OutputFilter_T::cultures_name" <-- "docs.AntoraIndexSemanticgroupPatterndatatype::cultures_name"
"repo.Index_gross::IndexPatternColumnDatatype" <-- "docs.AntoraIndexSemanticgroupPatterndatatype::IndexPatternColumnDatatype"
"repo.Index_gross::IndexSemanticGroup" <-- "docs.AntoraIndexSemanticgroupPatterndatatype::IndexSemanticGroup"footer The diagram is interactive and contains links.
@enduml

