@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:docs.culture.adoc[]" as docs.Culture << V >> {
  - cultures_name : (nvarchar(10))
  --
}

entity "puml-link:dhw:sqldb:docs.fs_cleanstringforfilename.adoc[]" as docs.fs_cleanStringForFilename << FN >> {
  --
}

entity "puml-link:dhw:sqldb:docs.fs_cleanstringforpuml.adoc[]" as docs.fs_cleanStringForPuml << FN >> {
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_outputfilter.adoc[]" as docs.RepoObject_OutputFilter << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  AntoraComponent : (nvarchar(max))
  AntoraModule : (nvarchar(max))
  external_AntoraComponent : (nvarchar(128))
  external_AntoraModule : (nvarchar(128))
  external_DatabaseName : (nvarchar(128))
  is_DocsOutput : (int)
  - is_external : (bit)
  - is_ssas : (bit)
  - PumlEntityTopDefault : (nvarchar(max))
  - PumlEntityTopWorkaround : (nvarchar(max))
  RepoObject_DisplayName : (nvarchar(128))
  RepoObject_FullDisplayName2 : (nvarchar(257))
  - RepoObject_fullname : (nvarchar(261))
  - RepoObject_fullname2 : (nvarchar(257))
  - RepoObject_name : (nvarchar(128))
  - RepoObject_schema_name : (nvarchar(128))
  RepoObject_translation : (nvarchar(128))
  SysObject_type : (char(2))
  SysObject_type_name : (nvarchar(128))
  tables_isHidden : (bit)
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_outputfilter_t.adoc[]" as docs.RepoObject_OutputFilter_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  AntoraComponent : (nvarchar(max))
  AntoraModule : (nvarchar(max))
  external_AntoraComponent : (nvarchar(128))
  external_AntoraModule : (nvarchar(128))
  external_DatabaseName : (nvarchar(128))
  is_DocsOutput : (int)
  - is_external : (bit)
  - is_ssas : (bit)
  - PumlEntityTopDefault : (nvarchar(max))
  - PumlEntityTopWorkaround : (nvarchar(max))
  RepoObject_DisplayName : (nvarchar(128))
  RepoObject_FullDisplayName2 : (nvarchar(257))
  - RepoObject_fullname : (nvarchar(261))
  - RepoObject_fullname2 : (nvarchar(257))
  - RepoObject_name : (nvarchar(128))
  - RepoObject_schema_name : (nvarchar(128))
  RepoObject_translation : (nvarchar(128))
  SysObject_type : (char(2))
  SysObject_type_name : (nvarchar(128))
  tables_isHidden : (bit)
  --
}

entity "puml-link:dhw:sqldb:docs.usp_persist_repoobject_outputfilter_t.adoc[]" as docs.usp_PERSIST_RepoObject_OutputFilter_T << P >> {
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_gross.adoc[]" as repo.RepoObject_gross << V >> {
  AntoraComponent : (nvarchar(max))
  AntoraModule : (nvarchar(max))
  Description : (nvarchar(max))
  external_AntoraComponent : (nvarchar(128))
  external_AntoraModule : (nvarchar(128))
  external_DatabaseName : (nvarchar(128))
  external_RepoDatabaseName : (nvarchar(128))
  has_different_sys_names : (bit)
  has_execution_plan_issue : (bit)
  has_get_referenced_issue : (bit)
  has_history : (bit)
  has_history_columns : (bit)
  history_schema_name : (nvarchar(128))
  history_table_name : (nvarchar(128))
  Inheritance_StringAggSeparatorSql : (nvarchar(4000))
  InheritanceDefinition : (nvarchar(4000))
  InheritanceType : (tinyint)
  - is_DocsExclude : (bit)
  is_DocsOutput : (int)
  - is_external : (bit)
  - is_in_reference : (int)
  is_persistence : (bit)
  is_persistence_check_duplicate_per_pk : (bit)
  is_persistence_check_for_empty_source : (bit)
  is_persistence_delete_changed : (bit)
  is_persistence_delete_missing : (bit)
  is_persistence_insert : (bit)
  is_persistence_merge_delete_missing : (bit)
  is_persistence_merge_insert : (bit)
  is_persistence_merge_update_changed : (bit)
  is_persistence_persist_source : (bit)
  is_persistence_truncate : (bit)
  is_persistence_update_changed : (bit)
  is_repo_managed : (bit)
  - is_RepoObject_name_uniqueidentifier : (int)
  is_required_ObjectMerge : (bit)
  - is_ssas : (bit)
  is_SysObject_missing : (bit)
  - is_SysObject_name_uniqueidentifier : (int)
  - modify_dt : (datetime)
  node_id : (bigint)
  persistence_source_RepoObject_fullname : (nvarchar(261))
  persistence_source_RepoObject_fullname2 : (nvarchar(257))
  persistence_source_RepoObject_guid : (uniqueidentifier)
  persistence_source_RepoObject_xref : (nvarchar(4000))
  persistence_source_SysObject_fullname : (nvarchar(261))
  persistence_source_SysObject_fullname_or_tempsource : (nvarchar(261))
  persistence_source_SysObject_fullname2 : (nvarchar(257))
  persistence_source_SysObject_xref : (nvarchar(4000))
  pk_index_guid : (uniqueidentifier)
  pk_IndexPatternColumnDatatype : (nvarchar(4000))
  pk_IndexPatternColumnName : (nvarchar(4000))
  pk_IndexPatternColumnName_new : (nvarchar(4000))
  pk_IndexSemanticGroup : (nvarchar(512))
  Property_ms_description : (nvarchar(4000))
  Repo_history_table_guid : (uniqueidentifier)
  Repo_temporal_type : (tinyint)
  - RepoObject_fullname : (nvarchar(261))
  - RepoObject_fullname2 : (nvarchar(257))
  - RepoObject_guid : (uniqueidentifier)
  - RepoObject_name : (nvarchar(128))
  RepoObject_Referencing_Count : (int)
  - RepoObject_schema_name : (nvarchar(128))
  - RepoObject_type : (char(2))
  RepoObject_type_name : (nvarchar(128))
  source_filter : (nvarchar(4000))
  - SysObject_fullname : (nvarchar(261))
  - SysObject_fullname2 : (nvarchar(257))
  SysObject_id : (int)
  SysObject_modify_date : (datetime)
  - SysObject_name : (nvarchar(128))
  - SysObject_parent_object_id : (int)
  SysObject_query_executed_dt : (datetime)
  SysObject_query_plan : (xml)
  - SysObject_query_sql : (nvarchar(406))
  - SysObject_schema_name : (nvarchar(128))
  SysObject_type : (char(2))
  SysObject_type_name : (nvarchar(128))
  tables_dataCategory : (nvarchar(500))
  tables_description : (nvarchar(max))
  tables_isHidden : (bit)
  target_filter : (nvarchar(4000))
  temporal_type : (tinyint)
  - usp_persistence_name : (nvarchar(140))
  usp_persistence_RepoObject_guid : (uniqueidentifier)
  uspgenerator_usp_id : (int)
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_3411_cultures_translations_model_t.adoc[]" as ssas.model_json_3411_cultures_translations_model_T << U >> {
  - **databasename** : (nvarchar(128))
  **cultures_name** : (nvarchar(500))
  cultures_translations_model_name : (nvarchar(500))
  cultures_translations_model_perspectives_ja : (nvarchar(max))
  cultures_translations_model_tables_ja : (nvarchar(max))
  cultures_translations_model_translatedDescription : (nvarchar(max))
  - is_CultureDocsOutput : (bit)
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_34111_cultures_translations_model_tables.adoc[]" as ssas.model_json_34111_cultures_translations_model_tables << V >> {
  - cultures_name : (nvarchar(10))
  - cultures_translations_model_name : (nvarchar(500))
  cultures_translations_model_tables_columns_ja : (nvarchar(max))
  cultures_translations_model_tables_hierarchies_ja : (nvarchar(max))
  cultures_translations_model_tables_measures_ja : (nvarchar(max))
  cultures_translations_model_tables_name : (nvarchar(128))
  cultures_translations_model_tables_translatedCaption : (nvarchar(128))
  - databasename : (nvarchar(128))
  --
}

docs.Culture <.. docs.RepoObject_OutputFilter
docs.fs_cleanStringForFilename <.. docs.RepoObject_OutputFilter
docs.fs_cleanStringForPuml <.. docs.RepoObject_OutputFilter
docs.RepoObject_OutputFilter <.. docs.RepoObject_OutputFilter_T
docs.RepoObject_OutputFilter <.. docs.usp_PERSIST_RepoObject_OutputFilter_T
repo.RepoObject_gross <.. docs.RepoObject_OutputFilter
ssas.model_json_3411_cultures_translations_model_T <.. docs.RepoObject_OutputFilter
ssas.model_json_34111_cultures_translations_model_tables <.. docs.RepoObject_OutputFilter
"docs.Culture::cultures_name" <-- "docs.RepoObject_OutputFilter::cultures_name"
"docs.RepoObject_OutputFilter::AntoraComponent" <-- "docs.RepoObject_OutputFilter_T::AntoraComponent"
"docs.RepoObject_OutputFilter::AntoraModule" <-- "docs.RepoObject_OutputFilter_T::AntoraModule"
"docs.RepoObject_OutputFilter::cultures_name" <-- "docs.RepoObject_OutputFilter_T::cultures_name"
"docs.RepoObject_OutputFilter::external_AntoraComponent" <-- "docs.RepoObject_OutputFilter_T::external_AntoraComponent"
"docs.RepoObject_OutputFilter::external_AntoraModule" <-- "docs.RepoObject_OutputFilter_T::external_AntoraModule"
"docs.RepoObject_OutputFilter::external_DatabaseName" <-- "docs.RepoObject_OutputFilter_T::external_DatabaseName"
"docs.RepoObject_OutputFilter::is_DocsOutput" <-- "docs.RepoObject_OutputFilter_T::is_DocsOutput"
"docs.RepoObject_OutputFilter::is_external" <-- "docs.RepoObject_OutputFilter_T::is_external"
"docs.RepoObject_OutputFilter::is_ssas" <-- "docs.RepoObject_OutputFilter_T::is_ssas"
"docs.RepoObject_OutputFilter::PumlEntityTopDefault" <-- "docs.RepoObject_OutputFilter_T::PumlEntityTopDefault"
"docs.RepoObject_OutputFilter::PumlEntityTopWorkaround" <-- "docs.RepoObject_OutputFilter_T::PumlEntityTopWorkaround"
"docs.RepoObject_OutputFilter::RepoObject_DisplayName" <-- "docs.RepoObject_OutputFilter_T::RepoObject_DisplayName"
"docs.RepoObject_OutputFilter::RepoObject_FullDisplayName2" <-- "docs.RepoObject_OutputFilter_T::RepoObject_FullDisplayName2"
"docs.RepoObject_OutputFilter::RepoObject_fullname" <-- "docs.RepoObject_OutputFilter_T::RepoObject_fullname"
"docs.RepoObject_OutputFilter::RepoObject_fullname2" <-- "docs.RepoObject_OutputFilter_T::RepoObject_fullname2"
"docs.RepoObject_OutputFilter::RepoObject_guid" <-- "docs.RepoObject_OutputFilter_T::RepoObject_guid"
"docs.RepoObject_OutputFilter::RepoObject_name" <-- "docs.RepoObject_OutputFilter_T::RepoObject_name"
"docs.RepoObject_OutputFilter::RepoObject_schema_name" <-- "docs.RepoObject_OutputFilter_T::RepoObject_schema_name"
"docs.RepoObject_OutputFilter::RepoObject_translation" <-- "docs.RepoObject_OutputFilter_T::RepoObject_translation"
"docs.RepoObject_OutputFilter::SysObject_type" <-- "docs.RepoObject_OutputFilter_T::SysObject_type"
"docs.RepoObject_OutputFilter::SysObject_type_name" <-- "docs.RepoObject_OutputFilter_T::SysObject_type_name"
"docs.RepoObject_OutputFilter::tables_isHidden" <-- "docs.RepoObject_OutputFilter_T::tables_isHidden"
"repo.RepoObject_gross::AntoraComponent" <-- "docs.RepoObject_OutputFilter::AntoraComponent"
"repo.RepoObject_gross::AntoraModule" <-- "docs.RepoObject_OutputFilter::AntoraModule"
"repo.RepoObject_gross::external_AntoraComponent" <-- "docs.RepoObject_OutputFilter::external_AntoraComponent"
"repo.RepoObject_gross::external_AntoraModule" <-- "docs.RepoObject_OutputFilter::external_AntoraModule"
"repo.RepoObject_gross::external_DatabaseName" <-- "docs.RepoObject_OutputFilter::external_DatabaseName"
"repo.RepoObject_gross::is_DocsOutput" <-- "docs.RepoObject_OutputFilter::is_DocsOutput"
"repo.RepoObject_gross::is_external" <-- "docs.RepoObject_OutputFilter::is_external"
"repo.RepoObject_gross::is_ssas" <-- "docs.RepoObject_OutputFilter::is_ssas"
"repo.RepoObject_gross::RepoObject_fullname" <-- "docs.RepoObject_OutputFilter::RepoObject_fullname"
"repo.RepoObject_gross::RepoObject_fullname2" <-- "docs.RepoObject_OutputFilter::RepoObject_fullname2"
"repo.RepoObject_gross::RepoObject_guid" <-- "docs.RepoObject_OutputFilter::RepoObject_guid"
"repo.RepoObject_gross::RepoObject_name" <-- "docs.RepoObject_OutputFilter::RepoObject_name"
"repo.RepoObject_gross::RepoObject_schema_name" <-- "docs.RepoObject_OutputFilter::RepoObject_schema_name"
"repo.RepoObject_gross::SysObject_type" <-- "docs.RepoObject_OutputFilter::SysObject_type"
"repo.RepoObject_gross::SysObject_type_name" <-- "docs.RepoObject_OutputFilter::SysObject_type_name"
"repo.RepoObject_gross::tables_isHidden" <-- "docs.RepoObject_OutputFilter::tables_isHidden"
"ssas.model_json_34111_cultures_translations_model_tables::cultures_translations_model_tables_translatedCaption" <-- "docs.RepoObject_OutputFilter::RepoObject_translation"footer The diagram is interactive and contains links.
@enduml

