@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity "[[{site-url}/{page-component-name}/current/{page-module}/config.ftv_get_parameter_value.html config.ftv_get_parameter_value]]" as config.ftv_get_parameter_value << IF >> {
  --
  Parameter_value_result : (nvarchar(max))
  Parameter_value_result_date : (date)
  Parameter_value_result_datetime : (datetime)
  Parameter_value_result_int : (int)
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/docs.fs_cleanStringForAnchorId.html docs.fs_cleanStringForAnchorId]]" as docs.fs_cleanStringForAnchorId << FN >> {
  --
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/docs.Unit_1_union.html docs.Unit_1_union]]" as docs.Unit_1_union << V >> {
  --
  Object_fullname2 : (nvarchar(257))
  Object_Type : (varchar(2))
  Unit_Description : (nvarchar(max))
  Unit_DisplayFolder : (nvarchar(500))
  Unit_Expression : (nvarchar(max))
  Unit_FormatString : (nvarchar(500))
  - Unit_fullname2 : (nvarchar(638))
  - Unit_guid : (uniqueidentifier)
  Unit_isHidden : (bit)
  Unit_IsKey : (bit)
  Unit_IsSsas : (bit)
  Unit_IsUnique : (bit)
  - Unit_Metatype : (varchar(7))
  - Unit_Name : (nvarchar(500))
  - Unit_Schema : (nvarchar(128))
  Unit_SummarizeBy : (nvarchar(500))
  Unit_TypeName : (nvarchar(128))
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/docs.Unit_2.html docs.Unit_2]]" as docs.Unit_2 << V >> {
  --
  AntoraComponent : (nvarchar(max))
  AntoraModule : (nvarchar(max))
  AntoraPage : (nvarchar(4000))
  AntoraSectionId : (nvarchar(4000))
  AntoraSiteUrl : (nvarchar(max))
  AntoraVersion : (nvarchar(max))
  Object_fullname2 : (nvarchar(257))
  Object_Type : (varchar(2))
  Unit_Description : (nvarchar(max))
  Unit_DisplayFolder : (nvarchar(500))
  Unit_Expression : (nvarchar(max))
  Unit_FormatString : (nvarchar(500))
  - Unit_fullname2 : (nvarchar(638))
  - Unit_guid : (uniqueidentifier)
  Unit_isHidden : (bit)
  Unit_IsKey : (bit)
  Unit_IsSsas : (bit)
  Unit_IsUnique : (bit)
  - Unit_Metatype : (varchar(7))
  - Unit_Name : (nvarchar(500))
  - Unit_Schema : (nvarchar(128))
  Unit_SummarizeBy : (nvarchar(500))
  Unit_TypeName : (nvarchar(128))
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/docs.Unit_3.html docs.Unit_3]]" as docs.Unit_3 << V >> {
  --
  AntoraComponent : (nvarchar(max))
  AntoraModule : (nvarchar(max))
  AntoraPage : (nvarchar(4000))
  AntoraSectionId : (nvarchar(4000))
  AntoraSiteUrl : (nvarchar(max))
  AntoraVersion : (nvarchar(max))
  Object_fullname2 : (nvarchar(257))
  Object_Type : (varchar(2))
  Unit_Description : (nvarchar(max))
  Unit_DisplayFolder : (nvarchar(500))
  Unit_Expression : (nvarchar(max))
  Unit_FormatString : (nvarchar(500))
  - Unit_fullname2 : (nvarchar(638))
  - Unit_guid : (uniqueidentifier)
  Unit_isHidden : (bit)
  Unit_IsKey : (bit)
  Unit_IsSsas : (bit)
  Unit_IsUnique : (bit)
  - Unit_Metatype : (varchar(7))
  - Unit_Name : (nvarchar(500))
  - Unit_Schema : (nvarchar(128))
  Unit_SummarizeBy : (nvarchar(500))
  Unit_TypeName : (nvarchar(128))
  - Unit_Url : (nvarchar(max))
  --
  --
}

config.ftv_get_parameter_value <.. docs.Unit_2
docs.fs_cleanStringForAnchorId <.. docs.Unit_2
docs.Unit_1_union <.. docs.Unit_2
docs.Unit_2 <.. docs.Unit_3
docs.Unit_1_union::Object_fullname2 <-- docs.Unit_2::Object_fullname2
docs.Unit_1_union::Object_Type <-- docs.Unit_2::Object_Type
docs.Unit_1_union::Unit_Description <-- docs.Unit_2::Unit_Description
docs.Unit_1_union::Unit_DisplayFolder <-- docs.Unit_2::Unit_DisplayFolder
docs.Unit_1_union::Unit_Expression <-- docs.Unit_2::Unit_Expression
docs.Unit_1_union::Unit_FormatString <-- docs.Unit_2::Unit_FormatString
docs.Unit_1_union::Unit_fullname2 <-- docs.Unit_2::Unit_fullname2
docs.Unit_1_union::Unit_guid <-- docs.Unit_2::Unit_guid
docs.Unit_1_union::Unit_isHidden <-- docs.Unit_2::Unit_isHidden
docs.Unit_1_union::Unit_IsKey <-- docs.Unit_2::Unit_IsKey
docs.Unit_1_union::Unit_IsSsas <-- docs.Unit_2::Unit_IsSsas
docs.Unit_1_union::Unit_IsUnique <-- docs.Unit_2::Unit_IsUnique
docs.Unit_1_union::Unit_Metatype <-- docs.Unit_2::Unit_Metatype
docs.Unit_1_union::Unit_Name <-- docs.Unit_2::Unit_Name
docs.Unit_1_union::Unit_Schema <-- docs.Unit_2::Unit_Schema
docs.Unit_1_union::Unit_SummarizeBy <-- docs.Unit_2::Unit_SummarizeBy
docs.Unit_1_union::Unit_TypeName <-- docs.Unit_2::Unit_TypeName
docs.Unit_2::AntoraComponent <-- docs.Unit_3::AntoraComponent
docs.Unit_2::AntoraModule <-- docs.Unit_3::AntoraModule
docs.Unit_2::AntoraPage <-- docs.Unit_3::AntoraPage
docs.Unit_2::AntoraSectionId <-- docs.Unit_3::AntoraSectionId
docs.Unit_2::AntoraSiteUrl <-- docs.Unit_3::AntoraSiteUrl
docs.Unit_2::AntoraVersion <-- docs.Unit_3::AntoraVersion
docs.Unit_2::Object_fullname2 <-- docs.Unit_3::Object_fullname2
docs.Unit_2::Object_Type <-- docs.Unit_3::Object_Type
docs.Unit_2::Unit_Description <-- docs.Unit_3::Unit_Description
docs.Unit_2::Unit_DisplayFolder <-- docs.Unit_3::Unit_DisplayFolder
docs.Unit_2::Unit_Expression <-- docs.Unit_3::Unit_Expression
docs.Unit_2::Unit_FormatString <-- docs.Unit_3::Unit_FormatString
docs.Unit_2::Unit_fullname2 <-- docs.Unit_3::Unit_fullname2
docs.Unit_2::Unit_guid <-- docs.Unit_3::Unit_guid
docs.Unit_2::Unit_isHidden <-- docs.Unit_3::Unit_isHidden
docs.Unit_2::Unit_IsKey <-- docs.Unit_3::Unit_IsKey
docs.Unit_2::Unit_IsSsas <-- docs.Unit_3::Unit_IsSsas
docs.Unit_2::Unit_IsUnique <-- docs.Unit_3::Unit_IsUnique
docs.Unit_2::Unit_Metatype <-- docs.Unit_3::Unit_Metatype
docs.Unit_2::Unit_Name <-- docs.Unit_3::Unit_Name
docs.Unit_2::Unit_Schema <-- docs.Unit_3::Unit_Schema
docs.Unit_2::Unit_SummarizeBy <-- docs.Unit_3::Unit_SummarizeBy
docs.Unit_2::Unit_TypeName <-- docs.Unit_3::Unit_TypeName
footer
to view a reduced diagram in original size and to be able to click on the links:
open the diagram in a new tab via the Context menu.
end footer

@enduml

