@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:logs.ExecutionLog.adoc[]" as logs.ExecutionLog << U >> {
  --
  created_dt : (datetime)
  current_execution_guid : (uniqueidentifier)
  deleted : (int)
  event_info : (nvarchar(max))
  - execution_instance_guid : (uniqueidentifier)
  - id : (bigint)
  info_01 : (nvarchar(4000))
  info_02 : (nvarchar(4000))
  info_03 : (nvarchar(4000))
  info_04 : (nvarchar(4000))
  info_05 : (nvarchar(4000))
  info_06 : (nvarchar(4000))
  info_07 : (nvarchar(4000))
  info_08 : (nvarchar(4000))
  info_09 : (nvarchar(4000))
  inserted : (int)
  parameter_01 : (nvarchar(4000))
  parameter_02 : (nvarchar(4000))
  parameter_03 : (nvarchar(4000))
  parameter_04 : (nvarchar(4000))
  parameter_05 : (nvarchar(4000))
  parameter_06 : (nvarchar(4000))
  parameter_07 : (nvarchar(4000))
  parameter_08 : (nvarchar(4000))
  parameter_09 : (nvarchar(4000))
  parameter_10 : (nvarchar(4000))
  parameter_11 : (nvarchar(4000))
  parameter_12 : (nvarchar(4000))
  parameter_13 : (nvarchar(4000))
  parameter_14 : (nvarchar(4000))
  parameter_15 : (nvarchar(4000))
  parameter_16 : (nvarchar(4000))
  parameter_17 : (nvarchar(4000))
  parameter_18 : (nvarchar(4000))
  parameter_19 : (nvarchar(4000))
  parameter_20 : (nvarchar(4000))
  parent_execution_log_id : (bigint)
  proc_id : (int)
  proc_name : (nvarchar(128))
  proc_schema_name : (nvarchar(128))
  source_object : (nvarchar(261))
  ssis_execution_id : (bigint)
  step_id : (int)
  step_name : (nvarchar(1000))
  sub_execution_id : (int)
  target_object : (nvarchar(261))
  updated : (int)
  ~ proc_fullname : (nvarchar(517))
  --
  --
}

entity "puml-link:dhw:sqldb:logs.ExecutionLog_gross.adoc[]" as logs.ExecutionLog_gross << V >> {
  --
  created_dt : (datetime)
  created_dt_max_execution_instance_guid : (datetime)
  created_dt_min_execution_instance_guid : (datetime)
  current_execution_guid : (uniqueidentifier)
  deleted : (int)
  duration_current_execution_guid : (int)
  duration_execution_instance_guid : (int)
  duration_step : (int)
  event_info : (nvarchar(max))
  - execution_instance_guid : (uniqueidentifier)
  - id : (bigint)
  info_01 : (nvarchar(4000))
  info_02 : (nvarchar(4000))
  info_03 : (nvarchar(4000))
  info_04 : (nvarchar(4000))
  info_05 : (nvarchar(4000))
  info_06 : (nvarchar(4000))
  info_07 : (nvarchar(4000))
  info_08 : (nvarchar(4000))
  info_09 : (nvarchar(4000))
  inserted : (int)
  parameter_01 : (nvarchar(4000))
  parameter_02 : (nvarchar(4000))
  parameter_03 : (nvarchar(4000))
  parameter_04 : (nvarchar(4000))
  parameter_05 : (nvarchar(4000))
  parameter_06 : (nvarchar(4000))
  parameter_07 : (nvarchar(4000))
  parameter_08 : (nvarchar(4000))
  parameter_09 : (nvarchar(4000))
  parameter_10 : (nvarchar(4000))
  parameter_11 : (nvarchar(4000))
  parameter_12 : (nvarchar(4000))
  parameter_13 : (nvarchar(4000))
  parameter_14 : (nvarchar(4000))
  parameter_15 : (nvarchar(4000))
  parameter_16 : (nvarchar(4000))
  parameter_17 : (nvarchar(4000))
  parameter_18 : (nvarchar(4000))
  parameter_19 : (nvarchar(4000))
  parameter_20 : (nvarchar(4000))
  parent_execution_log_id : (bigint)
  proc_id : (int)
  proc_name : (nvarchar(128))
  proc_schema_name : (nvarchar(128))
  - puml_Sequence : (nvarchar(1550))
  source_object : (nvarchar(261))
  ssis_execution_id : (bigint)
  step_id : (int)
  step_name : (nvarchar(1000))
  sub_execution_id : (int)
  target_object : (nvarchar(261))
  updated : (int)
  --
  --
}

entity "puml-link:dhw:sqldb:logs.ExecutionLog_parent.adoc[]" as logs.ExecutionLog_parent << V >> {
  --
  - id : (bigint)
  parent_created_dt : (datetime)
  parent_current_execution_guid : (uniqueidentifier)
  parent_execution_log_id : (bigint)
  parent_parameter_01 : (nvarchar(4000))
  parent_parameter_02 : (nvarchar(4000))
  parent_parameter_03 : (nvarchar(4000))
  parent_parameter_04 : (nvarchar(4000))
  parent_parameter_05 : (nvarchar(4000))
  parent_parameter_06 : (nvarchar(4000))
  parent_parameter_07 : (nvarchar(4000))
  parent_parameter_08 : (nvarchar(4000))
  parent_parameter_09 : (nvarchar(4000))
  parent_parameter_10 : (nvarchar(4000))
  parent_parameter_11 : (nvarchar(4000))
  parent_parameter_12 : (nvarchar(4000))
  parent_parameter_13 : (nvarchar(4000))
  parent_parameter_14 : (nvarchar(4000))
  parent_parameter_15 : (nvarchar(4000))
  parent_parameter_16 : (nvarchar(4000))
  parent_parameter_17 : (nvarchar(4000))
  parent_parameter_18 : (nvarchar(4000))
  parent_parameter_19 : (nvarchar(4000))
  parent_parameter_20 : (nvarchar(4000))
  parent_proc_fullname : (nvarchar(517))
  parent_proc_id : (int)
  parent_proc_name : (nvarchar(128))
  parent_proc_schema_name : (nvarchar(128))
  parent_step_id : (int)
  parent_step_name : (nvarchar(1000))
  --
  --
}

entity "puml-link:dhw:sqldb:logs.ExecutionLog_puml_Sequence_start_stop.adoc[]" as logs.ExecutionLog_puml_Sequence_start_stop << V >> {
  --
  created_dt : (datetime)
  - execution_instance_guid : (uniqueidentifier)
  - id : (bigint)
  parent_proc_fullname : (nvarchar(517))
  - proc_fullname : (nvarchar(517))
  - puml_Sequence_start_stop : (nvarchar(1574))
  --
  --
}

entity "puml-link:dhw:sqldb:logs.usp_ExecutionLog_insert.adoc[]" as logs.usp_ExecutionLog_insert << P >> {
  --
  --
  --
}

logs.ExecutionLog <.. logs.usp_ExecutionLog_insert
logs.ExecutionLog <.. logs.ExecutionLog_gross
logs.ExecutionLog <.. logs.ExecutionLog_parent
logs.ExecutionLog <.. logs.ExecutionLog_puml_Sequence_start_stop
"logs.ExecutionLog::created_dt" <-- "logs.ExecutionLog_gross::created_dt"
"logs.ExecutionLog::created_dt" <-- "logs.ExecutionLog_parent::parent_created_dt"
"logs.ExecutionLog::created_dt" <-- "logs.ExecutionLog_puml_Sequence_start_stop::created_dt"
"logs.ExecutionLog::current_execution_guid" <-- "logs.ExecutionLog_gross::current_execution_guid"
"logs.ExecutionLog::current_execution_guid" <-- "logs.ExecutionLog_parent::parent_current_execution_guid"
"logs.ExecutionLog::deleted" <-- "logs.ExecutionLog_gross::deleted"
"logs.ExecutionLog::event_info" <-- "logs.ExecutionLog_gross::event_info"
"logs.ExecutionLog::execution_instance_guid" <-- "logs.ExecutionLog_gross::execution_instance_guid"
"logs.ExecutionLog::execution_instance_guid" <-- "logs.ExecutionLog_puml_Sequence_start_stop::execution_instance_guid"
"logs.ExecutionLog::id" <-- "logs.ExecutionLog_gross::id"
"logs.ExecutionLog::id" <-- "logs.ExecutionLog_parent::id"
"logs.ExecutionLog::id" <-- "logs.ExecutionLog_puml_Sequence_start_stop::id"
"logs.ExecutionLog::info_01" <-- "logs.ExecutionLog_gross::info_01"
"logs.ExecutionLog::info_02" <-- "logs.ExecutionLog_gross::info_02"
"logs.ExecutionLog::info_03" <-- "logs.ExecutionLog_gross::info_03"
"logs.ExecutionLog::info_04" <-- "logs.ExecutionLog_gross::info_04"
"logs.ExecutionLog::info_05" <-- "logs.ExecutionLog_gross::info_05"
"logs.ExecutionLog::info_06" <-- "logs.ExecutionLog_gross::info_06"
"logs.ExecutionLog::info_07" <-- "logs.ExecutionLog_gross::info_07"
"logs.ExecutionLog::info_08" <-- "logs.ExecutionLog_gross::info_08"
"logs.ExecutionLog::info_09" <-- "logs.ExecutionLog_gross::info_09"
"logs.ExecutionLog::inserted" <-- "logs.ExecutionLog_gross::inserted"
"logs.ExecutionLog::parameter_01" <-- "logs.ExecutionLog_gross::parameter_01"
"logs.ExecutionLog::parameter_01" <-- "logs.ExecutionLog_parent::parent_parameter_01"
"logs.ExecutionLog::parameter_02" <-- "logs.ExecutionLog_gross::parameter_02"
"logs.ExecutionLog::parameter_02" <-- "logs.ExecutionLog_parent::parent_parameter_02"
"logs.ExecutionLog::parameter_03" <-- "logs.ExecutionLog_gross::parameter_03"
"logs.ExecutionLog::parameter_03" <-- "logs.ExecutionLog_parent::parent_parameter_03"
"logs.ExecutionLog::parameter_04" <-- "logs.ExecutionLog_gross::parameter_04"
"logs.ExecutionLog::parameter_04" <-- "logs.ExecutionLog_parent::parent_parameter_04"
"logs.ExecutionLog::parameter_05" <-- "logs.ExecutionLog_gross::parameter_05"
"logs.ExecutionLog::parameter_05" <-- "logs.ExecutionLog_parent::parent_parameter_05"
"logs.ExecutionLog::parameter_06" <-- "logs.ExecutionLog_gross::parameter_06"
"logs.ExecutionLog::parameter_06" <-- "logs.ExecutionLog_parent::parent_parameter_06"
"logs.ExecutionLog::parameter_07" <-- "logs.ExecutionLog_gross::parameter_07"
"logs.ExecutionLog::parameter_07" <-- "logs.ExecutionLog_parent::parent_parameter_07"
"logs.ExecutionLog::parameter_08" <-- "logs.ExecutionLog_gross::parameter_08"
"logs.ExecutionLog::parameter_08" <-- "logs.ExecutionLog_parent::parent_parameter_08"
"logs.ExecutionLog::parameter_09" <-- "logs.ExecutionLog_gross::parameter_09"
"logs.ExecutionLog::parameter_09" <-- "logs.ExecutionLog_parent::parent_parameter_09"
"logs.ExecutionLog::parameter_10" <-- "logs.ExecutionLog_gross::parameter_10"
"logs.ExecutionLog::parameter_10" <-- "logs.ExecutionLog_parent::parent_parameter_10"
"logs.ExecutionLog::parameter_11" <-- "logs.ExecutionLog_gross::parameter_11"
"logs.ExecutionLog::parameter_11" <-- "logs.ExecutionLog_parent::parent_parameter_11"
"logs.ExecutionLog::parameter_12" <-- "logs.ExecutionLog_gross::parameter_12"
"logs.ExecutionLog::parameter_12" <-- "logs.ExecutionLog_parent::parent_parameter_12"
"logs.ExecutionLog::parameter_13" <-- "logs.ExecutionLog_gross::parameter_13"
"logs.ExecutionLog::parameter_13" <-- "logs.ExecutionLog_parent::parent_parameter_13"
"logs.ExecutionLog::parameter_14" <-- "logs.ExecutionLog_gross::parameter_14"
"logs.ExecutionLog::parameter_14" <-- "logs.ExecutionLog_parent::parent_parameter_14"
"logs.ExecutionLog::parameter_15" <-- "logs.ExecutionLog_gross::parameter_15"
"logs.ExecutionLog::parameter_15" <-- "logs.ExecutionLog_parent::parent_parameter_15"
"logs.ExecutionLog::parameter_16" <-- "logs.ExecutionLog_gross::parameter_16"
"logs.ExecutionLog::parameter_16" <-- "logs.ExecutionLog_parent::parent_parameter_16"
"logs.ExecutionLog::parameter_17" <-- "logs.ExecutionLog_gross::parameter_17"
"logs.ExecutionLog::parameter_17" <-- "logs.ExecutionLog_parent::parent_parameter_17"
"logs.ExecutionLog::parameter_18" <-- "logs.ExecutionLog_gross::parameter_18"
"logs.ExecutionLog::parameter_18" <-- "logs.ExecutionLog_parent::parent_parameter_18"
"logs.ExecutionLog::parameter_19" <-- "logs.ExecutionLog_gross::parameter_19"
"logs.ExecutionLog::parameter_19" <-- "logs.ExecutionLog_parent::parent_parameter_19"
"logs.ExecutionLog::parameter_20" <-- "logs.ExecutionLog_gross::parameter_20"
"logs.ExecutionLog::parameter_20" <-- "logs.ExecutionLog_parent::parent_parameter_20"
"logs.ExecutionLog::parent_execution_log_id" <-- "logs.ExecutionLog_gross::parent_execution_log_id"
"logs.ExecutionLog::parent_execution_log_id" <-- "logs.ExecutionLog_parent::parent_execution_log_id"
"logs.ExecutionLog::proc_fullname" <-- "logs.ExecutionLog_parent::parent_proc_fullname"
"logs.ExecutionLog::proc_fullname" <-- "logs.ExecutionLog_puml_Sequence_start_stop::proc_fullname"
"logs.ExecutionLog::proc_id" <-- "logs.ExecutionLog_gross::proc_id"
"logs.ExecutionLog::proc_id" <-- "logs.ExecutionLog_parent::parent_proc_id"
"logs.ExecutionLog::proc_name" <-- "logs.ExecutionLog::proc_fullname"
"logs.ExecutionLog::proc_name" <-- "logs.ExecutionLog_gross::proc_name"
"logs.ExecutionLog::proc_name" <-- "logs.ExecutionLog_parent::parent_proc_name"
"logs.ExecutionLog::proc_schema_name" <-- "logs.ExecutionLog::proc_fullname"
"logs.ExecutionLog::proc_schema_name" <-- "logs.ExecutionLog_gross::proc_schema_name"
"logs.ExecutionLog::proc_schema_name" <-- "logs.ExecutionLog_parent::parent_proc_schema_name"
"logs.ExecutionLog::source_object" <-- "logs.ExecutionLog_gross::source_object"
"logs.ExecutionLog::ssis_execution_id" <-- "logs.ExecutionLog_gross::ssis_execution_id"
"logs.ExecutionLog::step_id" <-- "logs.ExecutionLog_gross::step_id"
"logs.ExecutionLog::step_id" <-- "logs.ExecutionLog_parent::parent_step_id"
"logs.ExecutionLog::step_name" <-- "logs.ExecutionLog_gross::step_name"
"logs.ExecutionLog::step_name" <-- "logs.ExecutionLog_parent::parent_step_name"
"logs.ExecutionLog::sub_execution_id" <-- "logs.ExecutionLog_gross::sub_execution_id"
"logs.ExecutionLog::target_object" <-- "logs.ExecutionLog_gross::target_object"
"logs.ExecutionLog::updated" <-- "logs.ExecutionLog_gross::updated"
@enduml

