left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity docs.usp_AntoraExport << P >> {
  --
  --
}

entity docs.usp_AntoraExport_DocSnippet << P >> {
  --
  --
}

entity docs.usp_AntoraExport_navigation << P >> {
  --
  --
}

entity docs.usp_AntoraExport_ObjectPage << P >> {
  --
  --
}

entity docs.usp_AntoraExport_ObjectPageTemplate << P >> {
  --
  --
}

entity docs.usp_AntoraExport_ObjectPartialProperties << P >> {
  --
  --
}

entity docs.usp_AntoraExport_ObjectPuml << P >> {
  --
  --
}

entity docs.usp_AntoraExport_ObjectRefCyclic << P >> {
  --
  --
}

entity docs.usp_AntoraExport_Page_IndexSemanticGroup << P >> {
  --
  --
}

entity docs.usp_PERSIST_RepoObject_Adoc_T << P >> {
  --
  --
}

entity docs.usp_PERSIST_RepoObject_ColumnList_T << P >> {
  --
  --
}

entity docs.usp_PERSIST_RepoObject_IndexList_T << P >> {
  --
  --
}

entity docs.usp_PERSIST_RepoObject_Plantuml_Entity_T << P >> {
  --
  --
}

entity docs.usp_PERSIST_RepoObject_Plantuml_T << P >> {
  --
  --
}

entity logs.ExecutionLog << U >> {
  --
  created_dt : datetime
  current_execution_guid : uniqueidentifier
  deleted : int
  event_info : nvarchar(max)
  * execution_instance_guid : uniqueidentifier
  * id : bigint
  info_01 : nvarchar(4000)
  info_02 : nvarchar(4000)
  info_03 : nvarchar(4000)
  info_04 : nvarchar(4000)
  info_05 : nvarchar(4000)
  info_06 : nvarchar(4000)
  info_07 : nvarchar(4000)
  info_08 : nvarchar(4000)
  info_09 : nvarchar(4000)
  inserted : int
  parameter_01 : nvarchar(4000)
  parameter_02 : nvarchar(4000)
  parameter_03 : nvarchar(4000)
  parameter_04 : nvarchar(4000)
  parameter_05 : nvarchar(4000)
  parameter_06 : nvarchar(4000)
  parameter_07 : nvarchar(4000)
  parameter_08 : nvarchar(4000)
  parameter_09 : nvarchar(4000)
  parameter_10 : nvarchar(4000)
  parameter_11 : nvarchar(4000)
  parameter_12 : nvarchar(4000)
  parameter_13 : nvarchar(4000)
  parameter_14 : nvarchar(4000)
  parameter_15 : nvarchar(4000)
  parameter_16 : nvarchar(4000)
  parameter_17 : nvarchar(4000)
  parameter_18 : nvarchar(4000)
  parameter_19 : nvarchar(4000)
  parameter_20 : nvarchar(4000)
  parent_execution_log_id : bigint
  proc_id : int
  proc_name : nvarchar(128)
  proc_schema_name : nvarchar(128)
  source_object : nvarchar(261)
  ssis_execution_id : bigint
  step_id : int
  step_name : nvarchar(1000)
  sub_execution_id : int
  target_object : nvarchar(261)
  updated : int
  * {abstract} proc_fullname : nvarchar(517)
  --
}

entity logs.usp_ExecutionLog_insert << P >> {
  --
  --
}

entity property.usp_RepoObject_Inheritance << P >> {
  --
  --
}

entity property.usp_RepoObjectColumn_Inheritance << P >> {
  --
  --
}

entity property.usp_RepoObjectProperty_collect << P >> {
  --
  --
}

entity property.usp_sync_ExtendedProperties_Repo2Sys_Delete << P >> {
  --
  --
}

entity property.usp_sync_ExtendedProperties_Repo2Sys_InsertUpdate << P >> {
  --
  --
}

entity property.usp_sync_ExtendedProperties_Sys2Repo_InsertUpdate << P >> {
  --
  --
}

entity reference.usp_PERSIST_RepoObject_reference_T << P >> {
  --
  --
}

entity reference.usp_PERSIST_RepoObject_ReferenceTree_0_30_T << P >> {
  --
  --
}

entity reference.usp_PERSIST_RepoObject_ReferenceTree_30_0_T << P >> {
  --
  --
}

entity reference.usp_PERSIST_RepoObjectColumn_reference_T << P >> {
  --
  --
}

entity reference.usp_RepoObject_ReferenceTree << P >> {
  --
  --
}

entity reference.usp_RepoObject_ReferenceTree_insert << P >> {
  --
  --
}

entity reference.usp_RepoObject_update_SysObjectQueryPlan << P >> {
  --
  --
}

entity reference.usp_RepoObjectSource_FirstResultSet << P >> {
  --
  --
}

entity reference.usp_RepoObjectSource_QueryPlan << P >> {
  --
  --
}

entity reference.usp_update_Referencing_Count << P >> {
  --
  --
}

entity repo.usp_Index_finish << P >> {
  --
  --
}

entity repo.usp_Index_ForeignKey << P >> {
  --
  --
}

entity repo.usp_index_inheritance << P >> {
  --
  --
}

entity repo.usp_Index_Settings << P >> {
  --
  --
}

entity repo.usp_Index_virtual_set << P >> {
  --
  --
}

entity repo.usp_main << P >> {
  --
  --
}

entity repo.usp_PERSIST_ForeignKey_Indexes_union_T << P >> {
  --
  --
}

entity repo.usp_PERSIST_Index_ssas_T << P >> {
  --
  --
}

entity repo.usp_PERSIST_IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T << P >> {
  --
  --
}

entity repo.usp_PERSIST_IndexColumn_ssas_T << P >> {
  --
  --
}

entity repo.usp_PERSIST_RepoObject_SSAS_tgt << P >> {
  --
  --
}

entity repo.usp_PERSIST_RepoObjectColumn_SSAS_tgt << P >> {
  --
  --
}

entity repo.usp_PERSIST_RepoSchema_ssas_tgt << P >> {
  --
  --
}

entity repo.usp_persistence_set << P >> {
  --
  --
}

entity repo.usp_RepoObjectColumn_update_RepoObjectColumn_column_id << P >> {
  --
  --
}

entity repo.usp_sync_guid << P >> {
  --
  --
}

entity repo.usp_sync_guid_RepoObject << P >> {
  --
  --
}

entity repo.usp_sync_guid_RepoObject_ssas << P >> {
  --
  --
}

entity repo.usp_sync_guid_RepoObjectColumn << P >> {
  --
  --
}

entity repo.usp_sync_guid_RepoObjectColumn_ssas << P >> {
  --
  --
}

entity repo.usp_sync_guid_RepoSchema << P >> {
  --
  --
}

entity repo.usp_sync_guid_RepoSchema_ssas << P >> {
  --
  --
}

entity repo.usp_sync_guid_ssas << P >> {
  --
  --
}

entity repo.usp_update_Referencing_Count << P >> {
  --
  --
}

entity sqlparse.usp_PERSIST_RepoObject_SqlModules_41_from_T << P >> {
  --
  --
}

entity sqlparse.usp_PERSIST_RepoObject_SqlModules_61_SelectIdentifier_Union_T << P >> {
  --
  --
}

entity sqlparse.usp_sqlparse << P >> {
  --
  --
}

entity ssas.usp_PERSIST_model_json_31_tables_T << P >> {
  --
  --
}

entity ssas.usp_PERSIST_model_json_311_tables_columns_T << P >> {
  --
  --
}

entity ssas.usp_PERSIST_model_json_32_relationships_T << P >> {
  --
  --
}

entity ssas.usp_PERSIST_TMSCHEMA_COLUMNS_T << P >> {
  --
  --
}

entity ssas.usp_PERSIST_TMSCHEMA_RELATIONSHIPS_T << P >> {
  --
  --
}

entity ssas.usp_PERSIST_TMSCHEMA_TABLES_T << P >> {
  --
  --
}

entity uspgenerator.usp_GeneratorUsp_insert_update_persistence << P >> {
  --
  --
}

entity workflow.usp_PERSIST_ProcedureDependency_input_PersistenceDependency << P >> {
  --
  --
}

entity workflow.usp_PERSIST_Workflow_ProcedureDependency_T << P >> {
  --
  --
}

entity workflow.usp_PERSIST_Workflow_ProcedureDependency_T_bidirectional_T << P >> {
  --
  --
}

entity workflow.usp_PERSIST_WorkflowStep << P >> {
  --
  --
}

entity workflow.usp_workflow << P >> {
  --
  --
}

logs.ExecutionLog <.. logs.usp_ExecutionLog_insert
logs.usp_ExecutionLog_insert <.. reference.usp_RepoObjectSource_QueryPlan
logs.usp_ExecutionLog_insert <.. reference.usp_update_Referencing_Count
logs.usp_ExecutionLog_insert <.. reference.usp_RepoObjectSource_FirstResultSet
logs.usp_ExecutionLog_insert <.. repo.usp_Index_Settings
logs.usp_ExecutionLog_insert <.. repo.usp_RepoObjectColumn_update_RepoObjectColumn_column_id
logs.usp_ExecutionLog_insert <.. reference.usp_RepoObject_update_SysObjectQueryPlan
logs.usp_ExecutionLog_insert <.. repo.usp_index_inheritance
logs.usp_ExecutionLog_insert <.. repo.usp_Index_virtual_set
logs.usp_ExecutionLog_insert <.. uspgenerator.usp_GeneratorUsp_insert_update_persistence
logs.usp_ExecutionLog_insert <.. repo.usp_sync_guid_RepoObject
logs.usp_ExecutionLog_insert <.. repo.usp_sync_guid_RepoObjectColumn
logs.usp_ExecutionLog_insert <.. repo.usp_sync_guid
logs.usp_ExecutionLog_insert <.. repo.usp_persistence_set
logs.usp_ExecutionLog_insert <.. repo.usp_main
logs.usp_ExecutionLog_insert <.. repo.usp_PERSIST_IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T
logs.usp_ExecutionLog_insert <.. property.usp_sync_ExtendedProperties_Sys2Repo_InsertUpdate
logs.usp_ExecutionLog_insert <.. property.usp_sync_ExtendedProperties_Repo2Sys_InsertUpdate
logs.usp_ExecutionLog_insert <.. property.usp_sync_ExtendedProperties_Repo2Sys_Delete
logs.usp_ExecutionLog_insert <.. property.usp_RepoObjectColumn_Inheritance
logs.usp_ExecutionLog_insert <.. property.usp_RepoObject_Inheritance
logs.usp_ExecutionLog_insert <.. repo.usp_Index_finish
logs.usp_ExecutionLog_insert <.. repo.usp_Index_ForeignKey
logs.usp_ExecutionLog_insert <.. docs.usp_AntoraExport_ObjectPartialProperties
logs.usp_ExecutionLog_insert <.. docs.usp_AntoraExport_ObjectPage
logs.usp_ExecutionLog_insert <.. docs.usp_PERSIST_RepoObject_Adoc_T
logs.usp_ExecutionLog_insert <.. docs.usp_AntoraExport_navigation
logs.usp_ExecutionLog_insert <.. docs.usp_AntoraExport_ObjectPageTemplate
logs.usp_ExecutionLog_insert <.. docs.usp_PERSIST_RepoObject_Plantuml_Entity_T
logs.usp_ExecutionLog_insert <.. docs.usp_AntoraExport_ObjectPuml
logs.usp_ExecutionLog_insert <.. docs.usp_AntoraExport_Page_IndexSemanticGroup
logs.usp_ExecutionLog_insert <.. docs.usp_AntoraExport
logs.usp_ExecutionLog_insert <.. docs.usp_PERSIST_RepoObject_IndexList_T
logs.usp_ExecutionLog_insert <.. property.usp_RepoObjectProperty_collect
logs.usp_ExecutionLog_insert <.. repo.usp_PERSIST_ForeignKey_Indexes_union_T
logs.usp_ExecutionLog_insert <.. docs.usp_PERSIST_RepoObject_Plantuml_T
logs.usp_ExecutionLog_insert <.. sqlparse.usp_PERSIST_RepoObject_SqlModules_41_from_T
logs.usp_ExecutionLog_insert <.. sqlparse.usp_PERSIST_RepoObject_SqlModules_61_SelectIdentifier_Union_T
logs.usp_ExecutionLog_insert <.. repo.usp_update_Referencing_Count
logs.usp_ExecutionLog_insert <.. docs.usp_AntoraExport_DocSnippet
logs.usp_ExecutionLog_insert <.. repo.usp_sync_guid_RepoSchema
logs.usp_ExecutionLog_insert <.. reference.usp_PERSIST_RepoObject_reference_T
logs.usp_ExecutionLog_insert <.. reference.usp_PERSIST_RepoObjectColumn_reference_T
logs.usp_ExecutionLog_insert <.. reference.usp_PERSIST_RepoObject_ReferenceTree_0_30_T
logs.usp_ExecutionLog_insert <.. reference.usp_PERSIST_RepoObject_ReferenceTree_30_0_T
logs.usp_ExecutionLog_insert <.. workflow.usp_workflow
logs.usp_ExecutionLog_insert <.. workflow.usp_PERSIST_ProcedureDependency_input_PersistenceDependency
logs.usp_ExecutionLog_insert <.. workflow.usp_PERSIST_WorkflowStep
logs.usp_ExecutionLog_insert <.. sqlparse.usp_sqlparse
logs.usp_ExecutionLog_insert <.. reference.usp_RepoObject_ReferenceTree
logs.usp_ExecutionLog_insert <.. workflow.usp_PERSIST_Workflow_ProcedureDependency_T
logs.usp_ExecutionLog_insert <.. docs.usp_AntoraExport_ObjectRefCyclic
logs.usp_ExecutionLog_insert <.. workflow.usp_PERSIST_Workflow_ProcedureDependency_T_bidirectional_T
logs.usp_ExecutionLog_insert <.. ssas.usp_PERSIST_TMSCHEMA_COLUMNS_T
logs.usp_ExecutionLog_insert <.. ssas.usp_PERSIST_TMSCHEMA_TABLES_T
logs.usp_ExecutionLog_insert <.. repo.usp_PERSIST_RepoObject_SSAS_tgt
logs.usp_ExecutionLog_insert <.. repo.usp_PERSIST_RepoObjectColumn_SSAS_tgt
logs.usp_ExecutionLog_insert <.. repo.usp_PERSIST_RepoSchema_ssas_tgt
logs.usp_ExecutionLog_insert <.. repo.usp_sync_guid_ssas
logs.usp_ExecutionLog_insert <.. repo.usp_sync_guid_RepoSchema_ssas
logs.usp_ExecutionLog_insert <.. repo.usp_sync_guid_RepoObject_ssas
logs.usp_ExecutionLog_insert <.. repo.usp_sync_guid_RepoObjectColumn_ssas
logs.usp_ExecutionLog_insert <.. repo.usp_PERSIST_IndexColumn_ssas_T
logs.usp_ExecutionLog_insert <.. repo.usp_PERSIST_Index_ssas_T
logs.usp_ExecutionLog_insert <.. ssas.usp_PERSIST_TMSCHEMA_RELATIONSHIPS_T
logs.usp_ExecutionLog_insert <.. ssas.usp_PERSIST_model_json_31_tables_T
logs.usp_ExecutionLog_insert <.. ssas.usp_PERSIST_model_json_311_tables_columns_T
logs.usp_ExecutionLog_insert <.. ssas.usp_PERSIST_model_json_32_relationships_T
logs.usp_ExecutionLog_insert <.. reference.usp_RepoObject_ReferenceTree_insert
logs.usp_ExecutionLog_insert <.. docs.usp_PERSIST_RepoObject_ColumnList_T

