@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity "[[{site-url}/{page-component-name}/current/{page-module}/docs.usp_AntoraExport.html docs.usp_AntoraExport]]" as docs.usp_AntoraExport << P >> {
  --
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/docs.usp_AntoraExport_DocSnippet.html docs.usp_AntoraExport_DocSnippet]]" as docs.usp_AntoraExport_DocSnippet << P >> {
  --
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/docs.usp_AntoraExport_navigation.html docs.usp_AntoraExport_navigation]]" as docs.usp_AntoraExport_navigation << P >> {
  --
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/docs.usp_AntoraExport_ObjectPage.html docs.usp_AntoraExport_ObjectPage]]" as docs.usp_AntoraExport_ObjectPage << P >> {
  --
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/docs.usp_AntoraExport_ObjectPageTemplate.html docs.usp_AntoraExport_ObjectPageTemplate]]" as docs.usp_AntoraExport_ObjectPageTemplate << P >> {
  --
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/docs.usp_AntoraExport_ObjectPartialProperties.html docs.usp_AntoraExport_ObjectPartialProperties]]" as docs.usp_AntoraExport_ObjectPartialProperties << P >> {
  --
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/docs.usp_AntoraExport_ObjectPuml.html docs.usp_AntoraExport_ObjectPuml]]" as docs.usp_AntoraExport_ObjectPuml << P >> {
  --
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/docs.usp_AntoraExport_ObjectRefCyclic.html docs.usp_AntoraExport_ObjectRefCyclic]]" as docs.usp_AntoraExport_ObjectRefCyclic << P >> {
  --
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/docs.usp_AntoraExport_Page_IndexSemanticGroup.html docs.usp_AntoraExport_Page_IndexSemanticGroup]]" as docs.usp_AntoraExport_Page_IndexSemanticGroup << P >> {
  --
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/docs.usp_PERSIST_RepoObject_Adoc_T.html docs.usp_PERSIST_RepoObject_Adoc_T]]" as docs.usp_PERSIST_RepoObject_Adoc_T << P >> {
  --
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/docs.usp_PERSIST_RepoObject_ColumnList_T.html docs.usp_PERSIST_RepoObject_ColumnList_T]]" as docs.usp_PERSIST_RepoObject_ColumnList_T << P >> {
  --
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/docs.usp_PERSIST_RepoObject_IndexList_T.html docs.usp_PERSIST_RepoObject_IndexList_T]]" as docs.usp_PERSIST_RepoObject_IndexList_T << P >> {
  --
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/docs.usp_PERSIST_RepoObject_Plantuml_Entity_T.html docs.usp_PERSIST_RepoObject_Plantuml_Entity_T]]" as docs.usp_PERSIST_RepoObject_Plantuml_Entity_T << P >> {
  --
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/docs.usp_PERSIST_RepoObject_Plantuml_T.html docs.usp_PERSIST_RepoObject_Plantuml_T]]" as docs.usp_PERSIST_RepoObject_Plantuml_T << P >> {
  --
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/logs.ExecutionLog.html logs.ExecutionLog]]" as logs.ExecutionLog << U >> {
  --
  created_dt : (datetime)
  current_execution_guid : (uniqueidentifier)
  deleted : (int)
  event_info : (nvarchar(max))
  - execution_instance_guid : (uniqueidentifier)
  - id : (bigint)
  info_01 : (nvarchar(4000))
  info_02 : (nvarchar(4000))
  info_03 : (nvarchar(4000))
  info_04 : (nvarchar(4000))
  info_05 : (nvarchar(4000))
  info_06 : (nvarchar(4000))
  info_07 : (nvarchar(4000))
  info_08 : (nvarchar(4000))
  info_09 : (nvarchar(4000))
  inserted : (int)
  parameter_01 : (nvarchar(4000))
  parameter_02 : (nvarchar(4000))
  parameter_03 : (nvarchar(4000))
  parameter_04 : (nvarchar(4000))
  parameter_05 : (nvarchar(4000))
  parameter_06 : (nvarchar(4000))
  parameter_07 : (nvarchar(4000))
  parameter_08 : (nvarchar(4000))
  parameter_09 : (nvarchar(4000))
  parameter_10 : (nvarchar(4000))
  parameter_11 : (nvarchar(4000))
  parameter_12 : (nvarchar(4000))
  parameter_13 : (nvarchar(4000))
  parameter_14 : (nvarchar(4000))
  parameter_15 : (nvarchar(4000))
  parameter_16 : (nvarchar(4000))
  parameter_17 : (nvarchar(4000))
  parameter_18 : (nvarchar(4000))
  parameter_19 : (nvarchar(4000))
  parameter_20 : (nvarchar(4000))
  parent_execution_log_id : (bigint)
  proc_id : (int)
  proc_name : (nvarchar(128))
  proc_schema_name : (nvarchar(128))
  source_object : (nvarchar(261))
  ssis_execution_id : (bigint)
  step_id : (int)
  step_name : (nvarchar(1000))
  sub_execution_id : (int)
  target_object : (nvarchar(261))
  updated : (int)
  ~ proc_fullname : (nvarchar(517))
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/logs.usp_ExecutionLog_insert.html logs.usp_ExecutionLog_insert]]" as logs.usp_ExecutionLog_insert << P >> {
  --
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/property.usp_PERSIST_PropertyName_RepoObject_T.html property.usp_PERSIST_PropertyName_RepoObject_T]]" as property.usp_PERSIST_PropertyName_RepoObject_T << P >> {
  --
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/property.usp_PERSIST_PropertyName_RepoObjectColumn_T.html property.usp_PERSIST_PropertyName_RepoObjectColumn_T]]" as property.usp_PERSIST_PropertyName_RepoObjectColumn_T << P >> {
  --
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/property.usp_RepoObject_Inheritance.html property.usp_RepoObject_Inheritance]]" as property.usp_RepoObject_Inheritance << P >> {
  --
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/property.usp_RepoObjectColumn_Inheritance.html property.usp_RepoObjectColumn_Inheritance]]" as property.usp_RepoObjectColumn_Inheritance << P >> {
  --
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/property.usp_RepoObjectProperty_collect.html property.usp_RepoObjectProperty_collect]]" as property.usp_RepoObjectProperty_collect << P >> {
  --
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/property.usp_sync_ExtendedProperties_Repo2Sys_Delete.html property.usp_sync_ExtendedProperties_Repo2Sys_Delete]]" as property.usp_sync_ExtendedProperties_Repo2Sys_Delete << P >> {
  --
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/property.usp_sync_ExtendedProperties_Repo2Sys_InsertUpdate.html property.usp_sync_ExtendedProperties_Repo2Sys_InsertUpdate]]" as property.usp_sync_ExtendedProperties_Repo2Sys_InsertUpdate << P >> {
  --
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/property.usp_sync_ExtendedProperties_Sys2Repo_InsertUpdate.html property.usp_sync_ExtendedProperties_Sys2Repo_InsertUpdate]]" as property.usp_sync_ExtendedProperties_Sys2Repo_InsertUpdate << P >> {
  --
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/reference.usp_PERSIST_RepoObject_reference_T.html reference.usp_PERSIST_RepoObject_reference_T]]" as reference.usp_PERSIST_RepoObject_reference_T << P >> {
  --
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/reference.usp_PERSIST_RepoObject_ReferenceTree_0_30_T.html reference.usp_PERSIST_RepoObject_ReferenceTree_0_30_T]]" as reference.usp_PERSIST_RepoObject_ReferenceTree_0_30_T << P >> {
  --
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/reference.usp_PERSIST_RepoObject_ReferenceTree_30_0_T.html reference.usp_PERSIST_RepoObject_ReferenceTree_30_0_T]]" as reference.usp_PERSIST_RepoObject_ReferenceTree_30_0_T << P >> {
  --
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/reference.usp_PERSIST_RepoObjectColumn_reference_T.html reference.usp_PERSIST_RepoObjectColumn_reference_T]]" as reference.usp_PERSIST_RepoObjectColumn_reference_T << P >> {
  --
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/reference.usp_RepoObject_ReferenceTree.html reference.usp_RepoObject_ReferenceTree]]" as reference.usp_RepoObject_ReferenceTree << P >> {
  --
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/reference.usp_RepoObject_ReferenceTree_insert.html reference.usp_RepoObject_ReferenceTree_insert]]" as reference.usp_RepoObject_ReferenceTree_insert << P >> {
  --
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/reference.usp_RepoObject_update_SysObjectQueryPlan.html reference.usp_RepoObject_update_SysObjectQueryPlan]]" as reference.usp_RepoObject_update_SysObjectQueryPlan << P >> {
  --
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/reference.usp_RepoObjectSource_FirstResultSet.html reference.usp_RepoObjectSource_FirstResultSet]]" as reference.usp_RepoObjectSource_FirstResultSet << P >> {
  --
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/reference.usp_RepoObjectSource_QueryPlan.html reference.usp_RepoObjectSource_QueryPlan]]" as reference.usp_RepoObjectSource_QueryPlan << P >> {
  --
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/reference.usp_update_Referencing_Count.html reference.usp_update_Referencing_Count]]" as reference.usp_update_Referencing_Count << P >> {
  --
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/repo.usp_Index_finish.html repo.usp_Index_finish]]" as repo.usp_Index_finish << P >> {
  --
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/repo.usp_Index_ForeignKey.html repo.usp_Index_ForeignKey]]" as repo.usp_Index_ForeignKey << P >> {
  --
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/repo.usp_index_inheritance.html repo.usp_index_inheritance]]" as repo.usp_index_inheritance << P >> {
  --
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/repo.usp_Index_Settings.html repo.usp_Index_Settings]]" as repo.usp_Index_Settings << P >> {
  --
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/repo.usp_Index_virtual_set.html repo.usp_Index_virtual_set]]" as repo.usp_Index_virtual_set << P >> {
  --
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/repo.usp_main.html repo.usp_main]]" as repo.usp_main << P >> {
  --
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/repo.usp_PERSIST_ForeignKey_Indexes_union_T.html repo.usp_PERSIST_ForeignKey_Indexes_union_T]]" as repo.usp_PERSIST_ForeignKey_Indexes_union_T << P >> {
  --
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/repo.usp_PERSIST_Index_ColumList_T.html repo.usp_PERSIST_Index_ColumList_T]]" as repo.usp_PERSIST_Index_ColumList_T << P >> {
  --
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/repo.usp_PERSIST_Index_ssas_T.html repo.usp_PERSIST_Index_ssas_T]]" as repo.usp_PERSIST_Index_ssas_T << P >> {
  --
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/repo.usp_PERSIST_IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T.html repo.usp_PERSIST_IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T]]" as repo.usp_PERSIST_IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T << P >> {
  --
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/repo.usp_PERSIST_IndexColumn_ssas_T.html repo.usp_PERSIST_IndexColumn_ssas_T]]" as repo.usp_PERSIST_IndexColumn_ssas_T << P >> {
  --
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/repo.usp_PERSIST_IndexColumn_union_T.html repo.usp_PERSIST_IndexColumn_union_T]]" as repo.usp_PERSIST_IndexColumn_union_T << P >> {
  --
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/repo.usp_PERSIST_RepoObject_SSAS_tgt.html repo.usp_PERSIST_RepoObject_SSAS_tgt]]" as repo.usp_PERSIST_RepoObject_SSAS_tgt << P >> {
  --
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/repo.usp_PERSIST_RepoObjectColumn_SSAS_tgt.html repo.usp_PERSIST_RepoObjectColumn_SSAS_tgt]]" as repo.usp_PERSIST_RepoObjectColumn_SSAS_tgt << P >> {
  --
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/repo.usp_PERSIST_RepoSchema_ssas_tgt.html repo.usp_PERSIST_RepoSchema_ssas_tgt]]" as repo.usp_PERSIST_RepoSchema_ssas_tgt << P >> {
  --
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/repo.usp_persistence_set.html repo.usp_persistence_set]]" as repo.usp_persistence_set << P >> {
  --
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/repo.usp_RepoObjectColumn_update_RepoObjectColumn_column_id.html repo.usp_RepoObjectColumn_update_RepoObjectColumn_column_id]]" as repo.usp_RepoObjectColumn_update_RepoObjectColumn_column_id << P >> {
  --
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/repo.usp_sync_guid.html repo.usp_sync_guid]]" as repo.usp_sync_guid << P >> {
  --
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/repo.usp_sync_guid_RepoObject.html repo.usp_sync_guid_RepoObject]]" as repo.usp_sync_guid_RepoObject << P >> {
  --
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/repo.usp_sync_guid_RepoObject_ssas.html repo.usp_sync_guid_RepoObject_ssas]]" as repo.usp_sync_guid_RepoObject_ssas << P >> {
  --
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/repo.usp_sync_guid_RepoObjectColumn.html repo.usp_sync_guid_RepoObjectColumn]]" as repo.usp_sync_guid_RepoObjectColumn << P >> {
  --
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/repo.usp_sync_guid_RepoObjectColumn_ssas.html repo.usp_sync_guid_RepoObjectColumn_ssas]]" as repo.usp_sync_guid_RepoObjectColumn_ssas << P >> {
  --
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/repo.usp_sync_guid_RepoSchema.html repo.usp_sync_guid_RepoSchema]]" as repo.usp_sync_guid_RepoSchema << P >> {
  --
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/repo.usp_sync_guid_RepoSchema_ssas.html repo.usp_sync_guid_RepoSchema_ssas]]" as repo.usp_sync_guid_RepoSchema_ssas << P >> {
  --
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/repo.usp_sync_guid_ssas.html repo.usp_sync_guid_ssas]]" as repo.usp_sync_guid_ssas << P >> {
  --
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/repo.usp_update_Referencing_Count.html repo.usp_update_Referencing_Count]]" as repo.usp_update_Referencing_Count << P >> {
  --
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/sqlparse.usp_PERSIST_RepoObject_SqlModules_41_from_T.html sqlparse.usp_PERSIST_RepoObject_SqlModules_41_from_T]]" as sqlparse.usp_PERSIST_RepoObject_SqlModules_41_from_T << P >> {
  --
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/sqlparse.usp_PERSIST_RepoObject_SqlModules_61_SelectIdentifier_Union_T.html sqlparse.usp_PERSIST_RepoObject_SqlModules_61_SelectIdentifier_Union_T]]" as sqlparse.usp_PERSIST_RepoObject_SqlModules_61_SelectIdentifier_Union_T << P >> {
  --
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/sqlparse.usp_sqlparse.html sqlparse.usp_sqlparse]]" as sqlparse.usp_sqlparse << P >> {
  --
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/ssas.usp_PERSIST_model_json_31_tables_T.html ssas.usp_PERSIST_model_json_31_tables_T]]" as ssas.usp_PERSIST_model_json_31_tables_T << P >> {
  --
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/ssas.usp_PERSIST_model_json_311_tables_columns_T.html ssas.usp_PERSIST_model_json_311_tables_columns_T]]" as ssas.usp_PERSIST_model_json_311_tables_columns_T << P >> {
  --
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/ssas.usp_PERSIST_model_json_312_tables_measures_T.html ssas.usp_PERSIST_model_json_312_tables_measures_T]]" as ssas.usp_PERSIST_model_json_312_tables_measures_T << P >> {
  --
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/ssas.usp_PERSIST_model_json_32_relationships_T.html ssas.usp_PERSIST_model_json_32_relationships_T]]" as ssas.usp_PERSIST_model_json_32_relationships_T << P >> {
  --
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/ssas.usp_PERSIST_TMSCHEMA_COLUMNS_T.html ssas.usp_PERSIST_TMSCHEMA_COLUMNS_T]]" as ssas.usp_PERSIST_TMSCHEMA_COLUMNS_T << P >> {
  --
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/ssas.usp_PERSIST_TMSCHEMA_RELATIONSHIPS_T.html ssas.usp_PERSIST_TMSCHEMA_RELATIONSHIPS_T]]" as ssas.usp_PERSIST_TMSCHEMA_RELATIONSHIPS_T << P >> {
  --
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/ssas.usp_PERSIST_TMSCHEMA_TABLES_T.html ssas.usp_PERSIST_TMSCHEMA_TABLES_T]]" as ssas.usp_PERSIST_TMSCHEMA_TABLES_T << P >> {
  --
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/uspgenerator.usp_GeneratorUsp_insert_update_persistence.html uspgenerator.usp_GeneratorUsp_insert_update_persistence]]" as uspgenerator.usp_GeneratorUsp_insert_update_persistence << P >> {
  --
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/workflow.usp_PERSIST_ProcedureDependency_input_PersistenceDependency.html workflow.usp_PERSIST_ProcedureDependency_input_PersistenceDependency]]" as workflow.usp_PERSIST_ProcedureDependency_input_PersistenceDependency << P >> {
  --
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/workflow.usp_PERSIST_Workflow_ProcedureDependency_T.html workflow.usp_PERSIST_Workflow_ProcedureDependency_T]]" as workflow.usp_PERSIST_Workflow_ProcedureDependency_T << P >> {
  --
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/workflow.usp_PERSIST_Workflow_ProcedureDependency_T_bidirectional_T.html workflow.usp_PERSIST_Workflow_ProcedureDependency_T_bidirectional_T]]" as workflow.usp_PERSIST_Workflow_ProcedureDependency_T_bidirectional_T << P >> {
  --
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/workflow.usp_PERSIST_WorkflowStep.html workflow.usp_PERSIST_WorkflowStep]]" as workflow.usp_PERSIST_WorkflowStep << P >> {
  --
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/workflow.usp_workflow.html workflow.usp_workflow]]" as workflow.usp_workflow << P >> {
  --
  --
  --
}

logs.ExecutionLog <.. logs.usp_ExecutionLog_insert
logs.usp_ExecutionLog_insert <.. reference.usp_RepoObjectSource_QueryPlan
logs.usp_ExecutionLog_insert <.. reference.usp_update_Referencing_Count
logs.usp_ExecutionLog_insert <.. reference.usp_RepoObjectSource_FirstResultSet
logs.usp_ExecutionLog_insert <.. repo.usp_Index_Settings
logs.usp_ExecutionLog_insert <.. repo.usp_RepoObjectColumn_update_RepoObjectColumn_column_id
logs.usp_ExecutionLog_insert <.. reference.usp_RepoObject_update_SysObjectQueryPlan
logs.usp_ExecutionLog_insert <.. repo.usp_index_inheritance
logs.usp_ExecutionLog_insert <.. repo.usp_Index_virtual_set
logs.usp_ExecutionLog_insert <.. uspgenerator.usp_GeneratorUsp_insert_update_persistence
logs.usp_ExecutionLog_insert <.. repo.usp_sync_guid_RepoObject
logs.usp_ExecutionLog_insert <.. repo.usp_sync_guid_RepoObjectColumn
logs.usp_ExecutionLog_insert <.. repo.usp_sync_guid
logs.usp_ExecutionLog_insert <.. repo.usp_persistence_set
logs.usp_ExecutionLog_insert <.. repo.usp_main
logs.usp_ExecutionLog_insert <.. repo.usp_PERSIST_IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T
logs.usp_ExecutionLog_insert <.. property.usp_sync_ExtendedProperties_Sys2Repo_InsertUpdate
logs.usp_ExecutionLog_insert <.. property.usp_sync_ExtendedProperties_Repo2Sys_InsertUpdate
logs.usp_ExecutionLog_insert <.. property.usp_sync_ExtendedProperties_Repo2Sys_Delete
logs.usp_ExecutionLog_insert <.. property.usp_RepoObjectColumn_Inheritance
logs.usp_ExecutionLog_insert <.. property.usp_RepoObject_Inheritance
logs.usp_ExecutionLog_insert <.. repo.usp_Index_finish
logs.usp_ExecutionLog_insert <.. repo.usp_Index_ForeignKey
logs.usp_ExecutionLog_insert <.. docs.usp_AntoraExport_ObjectPartialProperties
logs.usp_ExecutionLog_insert <.. docs.usp_AntoraExport_ObjectPage
logs.usp_ExecutionLog_insert <.. docs.usp_PERSIST_RepoObject_Adoc_T
logs.usp_ExecutionLog_insert <.. docs.usp_AntoraExport_navigation
logs.usp_ExecutionLog_insert <.. docs.usp_AntoraExport_ObjectPageTemplate
logs.usp_ExecutionLog_insert <.. docs.usp_PERSIST_RepoObject_Plantuml_Entity_T
logs.usp_ExecutionLog_insert <.. docs.usp_AntoraExport_ObjectPuml
logs.usp_ExecutionLog_insert <.. docs.usp_AntoraExport_Page_IndexSemanticGroup
logs.usp_ExecutionLog_insert <.. docs.usp_AntoraExport
logs.usp_ExecutionLog_insert <.. docs.usp_PERSIST_RepoObject_IndexList_T
logs.usp_ExecutionLog_insert <.. property.usp_RepoObjectProperty_collect
logs.usp_ExecutionLog_insert <.. repo.usp_PERSIST_ForeignKey_Indexes_union_T
logs.usp_ExecutionLog_insert <.. docs.usp_PERSIST_RepoObject_Plantuml_T
logs.usp_ExecutionLog_insert <.. sqlparse.usp_PERSIST_RepoObject_SqlModules_41_from_T
logs.usp_ExecutionLog_insert <.. sqlparse.usp_PERSIST_RepoObject_SqlModules_61_SelectIdentifier_Union_T
logs.usp_ExecutionLog_insert <.. repo.usp_update_Referencing_Count
logs.usp_ExecutionLog_insert <.. docs.usp_AntoraExport_DocSnippet
logs.usp_ExecutionLog_insert <.. repo.usp_sync_guid_RepoSchema
logs.usp_ExecutionLog_insert <.. reference.usp_PERSIST_RepoObject_reference_T
logs.usp_ExecutionLog_insert <.. reference.usp_PERSIST_RepoObjectColumn_reference_T
logs.usp_ExecutionLog_insert <.. reference.usp_PERSIST_RepoObject_ReferenceTree_0_30_T
logs.usp_ExecutionLog_insert <.. reference.usp_PERSIST_RepoObject_ReferenceTree_30_0_T
logs.usp_ExecutionLog_insert <.. workflow.usp_workflow
logs.usp_ExecutionLog_insert <.. workflow.usp_PERSIST_ProcedureDependency_input_PersistenceDependency
logs.usp_ExecutionLog_insert <.. workflow.usp_PERSIST_WorkflowStep
logs.usp_ExecutionLog_insert <.. sqlparse.usp_sqlparse
logs.usp_ExecutionLog_insert <.. reference.usp_RepoObject_ReferenceTree
logs.usp_ExecutionLog_insert <.. workflow.usp_PERSIST_Workflow_ProcedureDependency_T
logs.usp_ExecutionLog_insert <.. docs.usp_AntoraExport_ObjectRefCyclic
logs.usp_ExecutionLog_insert <.. workflow.usp_PERSIST_Workflow_ProcedureDependency_T_bidirectional_T
logs.usp_ExecutionLog_insert <.. ssas.usp_PERSIST_TMSCHEMA_COLUMNS_T
logs.usp_ExecutionLog_insert <.. ssas.usp_PERSIST_TMSCHEMA_TABLES_T
logs.usp_ExecutionLog_insert <.. repo.usp_PERSIST_RepoObject_SSAS_tgt
logs.usp_ExecutionLog_insert <.. repo.usp_PERSIST_RepoObjectColumn_SSAS_tgt
logs.usp_ExecutionLog_insert <.. repo.usp_PERSIST_RepoSchema_ssas_tgt
logs.usp_ExecutionLog_insert <.. repo.usp_sync_guid_ssas
logs.usp_ExecutionLog_insert <.. repo.usp_sync_guid_RepoSchema_ssas
logs.usp_ExecutionLog_insert <.. repo.usp_sync_guid_RepoObject_ssas
logs.usp_ExecutionLog_insert <.. repo.usp_sync_guid_RepoObjectColumn_ssas
logs.usp_ExecutionLog_insert <.. repo.usp_PERSIST_IndexColumn_ssas_T
logs.usp_ExecutionLog_insert <.. repo.usp_PERSIST_Index_ssas_T
logs.usp_ExecutionLog_insert <.. ssas.usp_PERSIST_TMSCHEMA_RELATIONSHIPS_T
logs.usp_ExecutionLog_insert <.. ssas.usp_PERSIST_model_json_31_tables_T
logs.usp_ExecutionLog_insert <.. ssas.usp_PERSIST_model_json_311_tables_columns_T
logs.usp_ExecutionLog_insert <.. ssas.usp_PERSIST_model_json_32_relationships_T
logs.usp_ExecutionLog_insert <.. reference.usp_RepoObject_ReferenceTree_insert
logs.usp_ExecutionLog_insert <.. docs.usp_PERSIST_RepoObject_ColumnList_T
logs.usp_ExecutionLog_insert <.. ssas.usp_PERSIST_model_json_312_tables_measures_T
logs.usp_ExecutionLog_insert <.. repo.usp_PERSIST_Index_ColumList_T
logs.usp_ExecutionLog_insert <.. repo.usp_PERSIST_IndexColumn_union_T
logs.usp_ExecutionLog_insert <.. property.usp_PERSIST_PropertyName_RepoObject_T
logs.usp_ExecutionLog_insert <.. property.usp_PERSIST_PropertyName_RepoObjectColumn_T

footer
to view a reduced diagram in original size and to be able to click on the links:
open the diagram in a new tab via the Context menu.
end footer

@enduml

