@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity "[[{site-url}/{page-component-name}/current/{page-module}/logs.ExecutionLog.html logs.ExecutionLog]]" as logs.ExecutionLog << U >> {
  --
  created_dt : (datetime)
  current_execution_guid : (uniqueidentifier)
  deleted : (int)
  event_info : (nvarchar(max))
  - execution_instance_guid : (uniqueidentifier)
  - id : (bigint)
  info_01 : (nvarchar(4000))
  info_02 : (nvarchar(4000))
  info_03 : (nvarchar(4000))
  info_04 : (nvarchar(4000))
  info_05 : (nvarchar(4000))
  info_06 : (nvarchar(4000))
  info_07 : (nvarchar(4000))
  info_08 : (nvarchar(4000))
  info_09 : (nvarchar(4000))
  inserted : (int)
  parameter_01 : (nvarchar(4000))
  parameter_02 : (nvarchar(4000))
  parameter_03 : (nvarchar(4000))
  parameter_04 : (nvarchar(4000))
  parameter_05 : (nvarchar(4000))
  parameter_06 : (nvarchar(4000))
  parameter_07 : (nvarchar(4000))
  parameter_08 : (nvarchar(4000))
  parameter_09 : (nvarchar(4000))
  parameter_10 : (nvarchar(4000))
  parameter_11 : (nvarchar(4000))
  parameter_12 : (nvarchar(4000))
  parameter_13 : (nvarchar(4000))
  parameter_14 : (nvarchar(4000))
  parameter_15 : (nvarchar(4000))
  parameter_16 : (nvarchar(4000))
  parameter_17 : (nvarchar(4000))
  parameter_18 : (nvarchar(4000))
  parameter_19 : (nvarchar(4000))
  parameter_20 : (nvarchar(4000))
  parent_execution_log_id : (bigint)
  proc_id : (int)
  proc_name : (nvarchar(128))
  proc_schema_name : (nvarchar(128))
  source_object : (nvarchar(261))
  ssis_execution_id : (bigint)
  step_id : (int)
  step_name : (nvarchar(1000))
  sub_execution_id : (int)
  target_object : (nvarchar(261))
  updated : (int)
  ~ proc_fullname : (nvarchar(517))
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/logs.ExecutionLog_parent.html logs.ExecutionLog_parent]]" as logs.ExecutionLog_parent << V >> {
  --
  - id : (bigint)
  parent_created_dt : (datetime)
  parent_current_execution_guid : (uniqueidentifier)
  parent_execution_log_id : (bigint)
  parent_parameter_01 : (nvarchar(4000))
  parent_parameter_02 : (nvarchar(4000))
  parent_parameter_03 : (nvarchar(4000))
  parent_parameter_04 : (nvarchar(4000))
  parent_parameter_05 : (nvarchar(4000))
  parent_parameter_06 : (nvarchar(4000))
  parent_parameter_07 : (nvarchar(4000))
  parent_parameter_08 : (nvarchar(4000))
  parent_parameter_09 : (nvarchar(4000))
  parent_parameter_10 : (nvarchar(4000))
  parent_parameter_11 : (nvarchar(4000))
  parent_parameter_12 : (nvarchar(4000))
  parent_parameter_13 : (nvarchar(4000))
  parent_parameter_14 : (nvarchar(4000))
  parent_parameter_15 : (nvarchar(4000))
  parent_parameter_16 : (nvarchar(4000))
  parent_parameter_17 : (nvarchar(4000))
  parent_parameter_18 : (nvarchar(4000))
  parent_parameter_19 : (nvarchar(4000))
  parent_parameter_20 : (nvarchar(4000))
  parent_proc_fullname : (nvarchar(517))
  parent_proc_id : (int)
  parent_proc_name : (nvarchar(128))
  parent_proc_schema_name : (nvarchar(128))
  parent_step_id : (int)
  parent_step_name : (nvarchar(1000))
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/logs.ExecutionLog_puml_Sequence_start_stop.html logs.ExecutionLog_puml_Sequence_start_stop]]" as logs.ExecutionLog_puml_Sequence_start_stop << V >> {
  --
  created_dt : (datetime)
  - execution_instance_guid : (uniqueidentifier)
  - id : (bigint)
  parent_proc_fullname : (nvarchar(517))
  - proc_fullname : (nvarchar(517))
  - puml_Sequence_start_stop : (nvarchar(1574))
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/logs.ftv_ExecutionLog_puml_sequence_start_stop_per_execution.html logs.ftv_ExecutionLog_puml_sequence_start_stop_per_execution]]" as logs.ftv_ExecutionLog_puml_sequence_start_stop_per_execution << IF >> {
  --
  - puml_Sequence_start_stop : (nvarchar(max))
  --
  --
}

logs.ExecutionLog <.. logs.ExecutionLog_puml_Sequence_start_stop
logs.ExecutionLog_parent <.. logs.ExecutionLog_puml_Sequence_start_stop
logs.ExecutionLog_puml_Sequence_start_stop <.. logs.ftv_ExecutionLog_puml_sequence_start_stop_per_execution
logs.ExecutionLog::created_dt <-- logs.ExecutionLog_puml_Sequence_start_stop::created_dt
logs.ExecutionLog::execution_instance_guid <-- logs.ExecutionLog_puml_Sequence_start_stop::execution_instance_guid
logs.ExecutionLog::id <-- logs.ExecutionLog_puml_Sequence_start_stop::id
logs.ExecutionLog::proc_fullname <-- logs.ExecutionLog_puml_Sequence_start_stop::proc_fullname
logs.ExecutionLog_parent::parent_proc_fullname <-- logs.ExecutionLog_puml_Sequence_start_stop::parent_proc_fullname
footer
to view a reduced diagram in original size and to be able to click on the links:
open the diagram in a new tab via the Context menu.
end footer

@enduml

