left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity config.Parameter << U >> {
  * **Parameter_name** : varchar(100)
  * **sub_Parameter** : nvarchar(128)
  --
  Parameter_default_value : nvarchar(max)
  Parameter_desciption : nvarchar(1000)
  Parameter_value : nvarchar(max)
  {abstract} Parameter_value_result : nvarchar(max)
  {abstract} Parameter_value_result_date : date
  {abstract} Parameter_value_result_datetime : datetime
  {abstract} Parameter_value_result_int : int
  --
}

entity property.PropertyName_RepoObjectColumn << V >> {
  * **property_name** : nvarchar(128)
  --
  --
}

entity property.RepoObjectColumnProperty << U >> {
  * **RepoObjectColumnProperty_id** : int
  --
  inheritance : tinyint
  * property_name : nvarchar(128)
  * property_value : nvarchar(max)
  * RepoObjectColumn_guid : uniqueidentifier
  {abstract} property_bigint : bigint
  {abstract} property_float : float
  {abstract} property_int : int
  {abstract} property_money : money
  {abstract} property_real : real
  --
}

entity property.RepoObjectColumnProperty_InheritanceType_InheritanceDefinition << V >> {
  * **RepoObjectColumn_guid** : uniqueidentifier
  * **property_name** : nvarchar(128)
  --
  Inheritance_StringAggSeparatorSql : nvarchar(max)
  InheritanceDefinition : nvarchar(max)
  InheritanceType : int
  par_Inheritance_StringAggSeparatorSql : nvarchar(max)
  par_InheritanceDefinition : nvarchar(max)
  par_InheritanceType : int
  property_value : nvarchar(max)
  * RepoObjectColumn_name : nvarchar(128)
  roc_Inheritance_StringAggSeparatorSql : nvarchar(4000)
  roc_InheritanceDefinition : nvarchar(4000)
  roc_InheritanceType : tinyint
  sub_Inheritance_StringAggSeparatorSql : nvarchar(max)
  sub_InheritanceDefinition : nvarchar(max)
  sub_InheritanceType : int
  --
}

config.Parameter <.. property.PropertyName_RepoObjectColumn
property.PropertyName_RepoObjectColumn <.. property.RepoObjectColumnProperty_InheritanceType_InheritanceDefinition
property.RepoObjectColumnProperty <.. property.PropertyName_RepoObjectColumn
property.PropertyName_RepoObjectColumn::property_name <-- property.RepoObjectColumnProperty_InheritanceType_InheritanceDefinition::property_name
