@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:docs.repoobject_adoc.adoc[]" as docs.RepoObject_Adoc << V >> {
  - AdocContent : (nvarchar(max))
  - cultures_name : (nvarchar(10))
  is_DocsOutput : (int)
  PropertyCount : (int)
  RepoObject_DisplayName : (nvarchar(128))
  RepoObject_FullDisplayName2 : (nvarchar(257))
  RepoObject_fullname : (nvarchar(261))
  RepoObject_fullname2 : (nvarchar(257))
  - RepoObject_guid : (uniqueidentifier)
  RepoObject_schema_name : (nvarchar(128))
  RepoObject_translation : (nvarchar(128))
  SysObject_fullname : (nvarchar(261))
  SysObject_fullname2 : (nvarchar(257))
  SysObject_schema_name : (nvarchar(128))
  SysObject_type : (char(2))
  SysObject_type_name : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.extendedproperty_repo2sys_level1.adoc[]" as property.ExtendedProperty_Repo2Sys_level1 << V >> {
  - **level0type** : (nvarchar(6))
  - **level0name** : (nvarchar(128))
  **level1type** : (varchar(9))
  - **level1name** : (nvarchar(128))
  - **property_name** : (nvarchar(128))
  level2name : (varchar(128))
  level2type : (varchar(10))
  property_value : (nvarchar(4000))
  - RepoObject_guid : (uniqueidentifier)
  - RepoObject_type : (char(2))
  --
}

entity "puml-link:dhw:sqldb:property.extendedproperty_repo2sys_level2_repoobject.adoc[]" as property.ExtendedProperty_Repo2Sys_level2_RepoObject << V >> {
  - **level0type** : (nvarchar(6))
  - **level0name** : (nvarchar(128))
  **level1type** : (varchar(9))
  - **level1name** : (nvarchar(128))
  **level2type** : (varchar(10))
  - **level2name** : (nvarchar(128))
  - **property_name** : (nvarchar(128))
  - parent_RepoObject_guid : (uniqueidentifier)
  - parent_RepoObject_type : (char(2))
  property_value : (nvarchar(4000))
  - RepoObject_guid : (uniqueidentifier)
  - RepoObject_type : (char(2))
  --
}

entity "puml-link:dhw:sqldb:property.fs_get_repoobjectproperty_nvarchar.adoc[]" as property.fs_get_RepoObjectProperty_nvarchar << FN >> {
  --
}

entity "puml-link:dhw:sqldb:property.propertyname_repoobject.adoc[]" as property.PropertyName_RepoObject << V >> {
  **property_name** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty.adoc[]" as property.RepoObjectProperty << U >> {
  - **RepoObjectProperty_id** : (int)
  inheritance : (tinyint)
  - property_name : (nvarchar(128))
  property_value : (nvarchar(max))
  - RepoObject_guid : (uniqueidentifier)
  ~ property_bigint : (bigint)
  ~ property_float : (float)
  ~ property_int : (int)
  ~ property_money : (money)
  ~ property_real : (real)
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty_external_tgt.adoc[]" as property.RepoObjectProperty_external_tgt << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  inheritance : (tinyint)
  property_value : (nvarchar(max))
  - RepoObjectProperty_id : (int)
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty_forupdate.adoc[]" as property.RepoObjectProperty_ForUpdate << V >> {
  AntoraComponent : (nvarchar(max))
  AntoraModule : (nvarchar(max))
  dwh_database : (nvarchar(128))
  inheritance : (tinyint)
  - property_name : (nvarchar(128))
  property_value : (nvarchar(max))
  repo_database : (nvarchar(128))
  - RepoObject_fullname : (nvarchar(261))
  - RepoObject_fullname2 : (nvarchar(257))
  - RepoObject_guid : (uniqueidentifier)
  - RepoObject_name : (nvarchar(128))
  - RepoObject_schema_name : (nvarchar(128))
  - RepoObject_type : (char(2))
  - RepoObjectProperty_id : (int)
  - tsql_comment_tag : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty_inheritancetype_inheritancedefinition.adoc[]" as property.RepoObjectProperty_InheritanceType_InheritanceDefinition << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  Inheritance_Source_fullname : (nvarchar(261))
  Inheritance_StringAggSeparatorSql : (nvarchar(max))
  InheritanceDefinition : (nvarchar(max))
  InheritanceType : (int)
  par_Inheritance_StringAggSeparatorSql : (nvarchar(max))
  par_InheritanceDefintion : (nvarchar(max))
  par_InheritanceType : (int)
  property_value : (nvarchar(max))
  - RepoObject_fullname : (nvarchar(261))
  - RepoObject_type : (char(2))
  ro_Inheritance_StringAggSeparatorSql : (nvarchar(4000))
  ro_InheritanceDefinition : (nvarchar(4000))
  ro_InheritanceType : (tinyint)
  sub_Inheritance_StringAggSeparatorSql : (nvarchar(max))
  sub_InheritanceDefintion : (nvarchar(max))
  sub_InheritanceType : (int)
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty_selectedpropertyname_split.adoc[]" as property.RepoObjectProperty_SelectedPropertyName_split << V >> {
  LinePerGuidProperty : (bigint)
  - property_name : (nvarchar(128))
  property_value : (nvarchar(max))
  - RepoObject_guid : (uniqueidentifier)
  RowPerGuidPropertyLine : (bigint)
  value_line : (nvarchar(max))
  value_line_len : (bigint)
  value_line_row : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty_sys_repo.adoc[]" as property.RepoObjectProperty_sys_repo << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **property_name** : (sysname)
  property_value : (sql_variant)
  RepoObjectProperty_id : (int)
  RepoObjectProperty_property_value : (nvarchar(max))
  SysObject_name : (nvarchar(128))
  SysObject_schema_name : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.usp_repoobject_inheritance.adoc[]" as property.usp_RepoObject_Inheritance << P >> {
  --
}

entity "puml-link:dhw:sqldb:property.usp_repoobjectproperty_collect.adoc[]" as property.usp_RepoObjectProperty_collect << P >> {
  --
}

entity "puml-link:dhw:sqldb:property.usp_repoobjectproperty_set.adoc[]" as property.usp_RepoObjectProperty_set << P >> {
  --
}

entity "puml-link:dhw:sqldb:property.usp_sync_extendedproperties_sys2repo_insertupdate.adoc[]" as property.usp_sync_ExtendedProperties_Sys2Repo_InsertUpdate << P >> {
  --
}

property.RepoObjectProperty <.. property.RepoObjectProperty_sys_repo
property.RepoObjectProperty <.. property.ExtendedProperty_Repo2Sys_level1
property.RepoObjectProperty <.. property.ExtendedProperty_Repo2Sys_level2_RepoObject
property.RepoObjectProperty <.. property.usp_sync_ExtendedProperties_Sys2Repo_InsertUpdate
property.RepoObjectProperty <.. property.PropertyName_RepoObject
property.RepoObjectProperty <.. property.usp_RepoObject_Inheritance
property.RepoObjectProperty <.. property.RepoObjectProperty_InheritanceType_InheritanceDefinition
property.RepoObjectProperty <.. property.fs_get_RepoObjectProperty_nvarchar
property.RepoObjectProperty <.. docs.RepoObject_Adoc
property.RepoObjectProperty <.. property.usp_RepoObjectProperty_set
property.RepoObjectProperty <.. property.usp_RepoObjectProperty_collect
property.RepoObjectProperty <.. property.RepoObjectProperty_ForUpdate
property.RepoObjectProperty <.. property.RepoObjectProperty_external_tgt
property.RepoObjectProperty <.. property.RepoObjectProperty_SelectedPropertyName_split
property.RepoObjectProperty_external_tgt <.. property.RepoObjectProperty
"property.RepoObjectProperty::inheritance" <-- "property.RepoObjectProperty_ForUpdate::inheritance"
"property.RepoObjectProperty::inheritance" <-- "property.RepoObjectProperty_external_tgt::inheritance"
"property.RepoObjectProperty::property_name" <-- "property.RepoObjectProperty_external_tgt::property_name"
"property.RepoObjectProperty::property_name" <-- "property.RepoObjectProperty_SelectedPropertyName_split::property_name"
"property.RepoObjectProperty::property_name" <-- "property.RepoObjectProperty_ForUpdate::property_name"
"property.RepoObjectProperty::property_name" <-- "property.ExtendedProperty_Repo2Sys_level1::property_name"
"property.RepoObjectProperty::property_name" <-- "property.ExtendedProperty_Repo2Sys_level2_RepoObject::property_name"
"property.RepoObjectProperty::property_value" <-- "property.RepoObjectProperty_InheritanceType_InheritanceDefinition::property_value"
"property.RepoObjectProperty::property_value" <-- "property.RepoObjectProperty::property_int"
"property.RepoObjectProperty::property_value" <-- "property.RepoObjectProperty::property_bigint"
"property.RepoObjectProperty::property_value" <-- "property.RepoObjectProperty::property_real"
"property.RepoObjectProperty::property_value" <-- "property.RepoObjectProperty::property_float"
"property.RepoObjectProperty::property_value" <-- "property.RepoObjectProperty::property_money"
"property.RepoObjectProperty::property_value" <-- "property.RepoObjectProperty_ForUpdate::property_value"
"property.RepoObjectProperty::property_value" <-- "property.RepoObjectProperty_SelectedPropertyName_split::property_value"
"property.RepoObjectProperty::property_value" <-- "property.RepoObjectProperty_external_tgt::property_value"
"property.RepoObjectProperty::RepoObject_guid" <-- "property.RepoObjectProperty_external_tgt::RepoObject_guid"
"property.RepoObjectProperty::RepoObject_guid" <-- "property.RepoObjectProperty_SelectedPropertyName_split::RepoObject_guid"
"property.RepoObjectProperty::RepoObject_guid" <-- "property.RepoObjectProperty_ForUpdate::RepoObject_guid"
"property.RepoObjectProperty::RepoObject_guid" <-- "property.ExtendedProperty_Repo2Sys_level2_RepoObject::RepoObject_guid"
"property.RepoObjectProperty::RepoObject_guid" <-- "property.ExtendedProperty_Repo2Sys_level1::RepoObject_guid"
"property.RepoObjectProperty::RepoObjectProperty_id" <-- "property.RepoObjectProperty_ForUpdate::RepoObjectProperty_id"
"property.RepoObjectProperty::RepoObjectProperty_id" <-- "property.RepoObjectProperty_external_tgt::RepoObjectProperty_id"footer The diagram is interactive and contains links.
@enduml

