@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:property.repoobjectcolumnproperty_inheritancetype_inheritancedefinition.adoc[]" as property.RepoObjectColumnProperty_InheritanceType_InheritanceDefinition << V >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  Inheritance_StringAggSeparatorSql : (nvarchar(max))
  InheritanceDefinition : (nvarchar(max))
  InheritanceType : (int)
  par_Inheritance_StringAggSeparatorSql : (nvarchar(max))
  par_InheritanceDefinition : (nvarchar(max))
  par_InheritanceType : (int)
  property_value : (nvarchar(max))
  - RepoObjectColumn_name : (nvarchar(128))
  roc_Inheritance_StringAggSeparatorSql : (nvarchar(4000))
  roc_InheritanceDefinition : (nvarchar(4000))
  roc_InheritanceType : (tinyint)
  sub_Inheritance_StringAggSeparatorSql : (nvarchar(max))
  sub_InheritanceDefinition : (nvarchar(max))
  sub_InheritanceType : (int)
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectcolumnproperty_inheritancetype_resulting_inheritancedefinition.adoc[]" as property.RepoObjectColumnProperty_InheritanceType_resulting_InheritanceDefinition << V >> {
  Inheritance_StringAggSeparatorSql : (nvarchar(max))
  InheritanceDefinition : (nvarchar(max))
  InheritanceType : (int)
  - is_force_inherit_empty_source : (int)
  - is_StringAggAllSources : (int)
  - property_name : (nvarchar(128))
  property_value : (nvarchar(max))
  - RepoObjectColumn_guid : (uniqueidentifier)
  - RepoObjectColumn_name : (nvarchar(128))
  resulting_InheritanceDefinition : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:property.usp_repoobjectcolumn_inheritance.adoc[]" as property.usp_RepoObjectColumn_Inheritance << P >> {
  --
}

property.RepoObjectColumnProperty_InheritanceType_InheritanceDefinition <.. property.RepoObjectColumnProperty_InheritanceType_resulting_InheritanceDefinition
property.RepoObjectColumnProperty_InheritanceType_resulting_InheritanceDefinition <.. property.usp_RepoObjectColumn_Inheritance
"property.RepoObjectColumnProperty_InheritanceType_InheritanceDefinition::Inheritance_StringAggSeparatorSql" <-- "property.RepoObjectColumnProperty_InheritanceType_resulting_InheritanceDefinition::Inheritance_StringAggSeparatorSql"
"property.RepoObjectColumnProperty_InheritanceType_InheritanceDefinition::InheritanceDefinition" <-- "property.RepoObjectColumnProperty_InheritanceType_resulting_InheritanceDefinition::InheritanceDefinition"
"property.RepoObjectColumnProperty_InheritanceType_InheritanceDefinition::InheritanceType" <-- "property.RepoObjectColumnProperty_InheritanceType_resulting_InheritanceDefinition::InheritanceType"
"property.RepoObjectColumnProperty_InheritanceType_InheritanceDefinition::property_name" <-- "property.RepoObjectColumnProperty_InheritanceType_resulting_InheritanceDefinition::property_name"
"property.RepoObjectColumnProperty_InheritanceType_InheritanceDefinition::property_value" <-- "property.RepoObjectColumnProperty_InheritanceType_resulting_InheritanceDefinition::property_value"
"property.RepoObjectColumnProperty_InheritanceType_InheritanceDefinition::RepoObjectColumn_guid" <-- "property.RepoObjectColumnProperty_InheritanceType_resulting_InheritanceDefinition::RepoObjectColumn_guid"
"property.RepoObjectColumnProperty_InheritanceType_InheritanceDefinition::RepoObjectColumn_name" <-- "property.RepoObjectColumnProperty_InheritanceType_resulting_InheritanceDefinition::RepoObjectColumn_name"footer The diagram is interactive and contains links.
@enduml

