@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:property.external_repoobjectcolumnproperty.adoc[]" as property.external_RepoObjectColumnProperty << U >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  AntoraComponent : (nvarchar(max))
  AntoraModule : (nvarchar(max))
  dwh_database : (nvarchar(128))
  property_value : (nvarchar(max))
  repo_database : (nvarchar(128))
  - RepoObject_name : (nvarchar(128))
  - RepoObject_schema_name : (nvarchar(128))
  - RepoObjectColumn_name : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectcolumnproperty_external_src.adoc[]" as property.RepoObjectColumnProperty_external_src << V >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  property_value : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectcolumnproperty_external_tgt.adoc[]" as property.RepoObjectColumnProperty_external_tgt << V >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  inheritance : (tinyint)
  property_value : (nvarchar(max))
  - RepoObjectColumnProperty_id : (int)
  --
}

entity "puml-link:dhw:sqldb:property.usp_persist_repoobjectcolumnproperty_external_tgt.adoc[]" as property.usp_PERSIST_RepoObjectColumnProperty_external_tgt << P >> {
  --
}

property.external_RepoObjectColumnProperty <.. property.RepoObjectColumnProperty_external_src
property.RepoObjectColumnProperty_external_src <.. property.RepoObjectColumnProperty_external_tgt
property.RepoObjectColumnProperty_external_src <.. property.usp_PERSIST_RepoObjectColumnProperty_external_tgt
"property.external_RepoObjectColumnProperty::property_name" <-- "property.RepoObjectColumnProperty_external_src::property_name"
"property.external_RepoObjectColumnProperty::property_value" <-- "property.RepoObjectColumnProperty_external_src::property_value"
"property.external_RepoObjectColumnProperty::RepoObjectColumn_guid" <-- "property.RepoObjectColumnProperty_external_src::RepoObjectColumn_guid"
"property.RepoObjectColumnProperty_external_src::property_name" <-- "property.RepoObjectColumnProperty_external_tgt::property_name"
"property.RepoObjectColumnProperty_external_src::property_value" <-- "property.RepoObjectColumnProperty_external_tgt::property_value"
"property.RepoObjectColumnProperty_external_src::RepoObjectColumn_guid" <-- "property.RepoObjectColumnProperty_external_tgt::RepoObjectColumn_guid"footer The diagram is interactive and contains links.
@enduml

