left to right direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity docs.RepoObject_Adoc << V >> {
  * **RepoObject_guid** : uniqueidentifier
  --
  * AdocContent : nvarchar(max)
  is_DocsOutput : int
  PropertyCount : int
  RepoObject_fullname : nvarchar(261)
  RepoObject_fullname2 : nvarchar(257)
  RepoObject_schema_name : nvarchar(128)
  SysObject_fullname : nvarchar(261)
  SysObject_fullname2 : nvarchar(257)
  SysObject_schema_name : nvarchar(128)
  SysObject_type : char(2)
  SysObject_type_name : nvarchar(128)
}

entity property.ExtendedProperty_Repo2Sys_level1 << V >> {
  * **level0type** : nvarchar(6)
  * **level0name** : nvarchar(128)
  **level1type** : varchar(9)
  * **level1name** : nvarchar(128)
  * **property_name** : nvarchar(128)
  --
  level2name : varchar(128)
  level2type : varchar(10)
  property_value : sql_variant
  * RepoObject_guid : uniqueidentifier
  * RepoObject_type : char(2)
}

entity property.ExtendedProperty_Repo2Sys_level2_RepoObject << V >> {
  * **level0type** : nvarchar(6)
  * **level0name** : nvarchar(128)
  **level1type** : varchar(9)
  * **level1name** : nvarchar(128)
  **level2type** : varchar(10)
  * **level2name** : nvarchar(128)
  * **property_name** : nvarchar(128)
  --
  * parent_RepoObject_guid : uniqueidentifier
  * parent_RepoObject_type : char(2)
  property_value : sql_variant
  * RepoObject_guid : uniqueidentifier
  * RepoObject_type : char(2)
}

entity property.fs_get_RepoObjectProperty_nvarchar << FN >> {
  --
}

entity property.PropertyName_RepoObject << V >> {
  * **property_name** : nvarchar(128)
  --
}

entity property.RepoObjectProperty << U >> {
  * **RepoObjectProperty_id** : int
  --
  inheritance : tinyint
  * property_name : nvarchar(128)
  property_value : sql_variant
  * RepoObject_guid : uniqueidentifier
  {abstract} property_basetype : sql_variant
  {abstract} property_bigint : bigint
  {abstract} property_float : float
  {abstract} property_int : int
  {abstract} property_money : money
  {abstract} property_nvarchar : nvarchar(4000)
  {abstract} property_real : real
  {abstract} property_varchar : varchar(8000)
}

entity property.RepoObjectProperty_InheritanceType_InheritanceDefinition << V >> {
  * **RepoObject_guid** : uniqueidentifier
  * **property_name** : nvarchar(128)
  --
  Inheritance_StringAggSeparatorSql : nvarchar(4000)
  InheritanceDefinition : nvarchar(4000)
  InheritanceType : int
  par_Inheritance_StringAggSeparatorSql : nvarchar(4000)
  par_InheritanceDefintion : nvarchar(4000)
  par_InheritanceType : int
  property_value : sql_variant
  * RepoObject_fullname : nvarchar(261)
  * RepoObject_type : char(2)
  ro_Inheritance_StringAggSeparatorSql : nvarchar(4000)
  ro_InheritanceDefinition : nvarchar(4000)
  ro_InheritanceType : tinyint
  sub_Inheritance_StringAggSeparatorSql : nvarchar(4000)
  sub_InheritanceDefintion : nvarchar(4000)
  sub_InheritanceType : int
}

entity property.RepoObjectProperty_sys_repo << V >> {
  * **RepoObject_guid** : uniqueidentifier
  * **property_name** : sysname
  --
  property_value : sql_variant
  RepoObjectProperty_id : int
  RepoObjectProperty_property_value : sql_variant
  SysObject_name : nvarchar(128)
  SysObject_schema_name : nvarchar(128)
}

entity property.usp_RepoObject_Inheritance << P >> {
  --
}

entity property.usp_RepoObjectProperty_collect << P >> {
  --
}

entity property.usp_RepoObjectProperty_set << P >> {
  --
}

entity property.usp_sync_ExtendedProperties_Sys2Repo_InsertUpdate << P >> {
  --
}

property.PropertyName_RepoObject <.. property.RepoObjectProperty_InheritanceType_InheritanceDefinition
property.RepoObjectProperty <.. property.usp_RepoObject_Inheritance
property.RepoObjectProperty <.. property.fs_get_RepoObjectProperty_nvarchar
property.RepoObjectProperty <.. property.RepoObjectProperty_sys_repo
property.RepoObjectProperty <.. property.usp_RepoObjectProperty_collect
property.RepoObjectProperty <.. property.usp_RepoObjectProperty_set
property.RepoObjectProperty <.. docs.RepoObject_Adoc
property.RepoObjectProperty <.. property.ExtendedProperty_Repo2Sys_level1
property.RepoObjectProperty <.. property.ExtendedProperty_Repo2Sys_level2_RepoObject
property.RepoObjectProperty <.. property.usp_sync_ExtendedProperties_Sys2Repo_InsertUpdate
property.RepoObjectProperty <.. property.PropertyName_RepoObject
property.RepoObjectProperty <.. property.RepoObjectProperty_InheritanceType_InheritanceDefinition
property.RepoObjectProperty_sys_repo <.. property.usp_sync_ExtendedProperties_Sys2Repo_InsertUpdate
property.PropertyName_RepoObject::property_name <-- property.RepoObjectProperty_InheritanceType_InheritanceDefinition::property_name
property.RepoObjectProperty::property_name <-- property.ExtendedProperty_Repo2Sys_level1::property_name
property.RepoObjectProperty::property_name <-- property.ExtendedProperty_Repo2Sys_level2_RepoObject::property_name
property.RepoObjectProperty::property_value <-- property.ExtendedProperty_Repo2Sys_level2_RepoObject::property_value
property.RepoObjectProperty::property_value <-- property.ExtendedProperty_Repo2Sys_level1::property_value
property.RepoObjectProperty::property_value <-- property.RepoObjectProperty_InheritanceType_InheritanceDefinition::property_value
property.RepoObjectProperty::RepoObject_guid <-- property.ExtendedProperty_Repo2Sys_level2_RepoObject::RepoObject_guid
property.RepoObjectProperty::RepoObject_guid <-- property.ExtendedProperty_Repo2Sys_level1::RepoObject_guid
