@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity "puml-link:property.ExtendedProperty_Repo2Sys_level2_RepoObjectColumn.adoc[prefix=..]" as property.ExtendedProperty_Repo2Sys_level2_RepoObjectColumn << V >> {
  - **level0type** : (nvarchar(6))
  - **level0name** : (nvarchar(128))
  **level1type** : (varchar(9))
  - **level1name** : (nvarchar(128))
  - **level2type** : (nvarchar(6))
  - **level2name** : (nvarchar(128))
  - **property_name** : (nvarchar(128))
  --
  - parent_RepoObject_guid : (uniqueidentifier)
  - parent_RepoObject_type : (char(2))
  property_value : (nvarchar(4000))
  Repo_user_type_fullname : (nvarchar(128))
  - RepoObjectColumn_guid : (uniqueidentifier)
  --
  --
}

entity "puml-link:property.fs_get_RepoObjectColumnProperty_nvarchar.adoc[prefix=..]" as property.fs_get_RepoObjectColumnProperty_nvarchar << FN >> {
  --
  --
  --
}

entity "puml-link:property.PropertyName_RepoObjectColumn.adoc[prefix=..]" as property.PropertyName_RepoObjectColumn << V >> {
  - **property_name** : (nvarchar(128))
  --
  --
  --
}

entity "puml-link:property.RepoObjectColumnProperty.adoc[prefix=..]" as property.RepoObjectColumnProperty << U >> {
  - **RepoObjectColumnProperty_id** : (int)
  --
  inheritance : (tinyint)
  - property_name : (nvarchar(128))
  - property_value : (nvarchar(max))
  - RepoObjectColumn_guid : (uniqueidentifier)
  ~ property_bigint : (bigint)
  ~ property_float : (float)
  ~ property_int : (int)
  ~ property_money : (money)
  ~ property_real : (real)
  --
  --
}

entity "puml-link:property.RepoObjectColumnProperty_ForUpdate.adoc[prefix=..]" as property.RepoObjectColumnProperty_ForUpdate << V >> {
  - **RepoObjectColumnProperty_id** : (int)
  --
  inheritance : (tinyint)
  - property_name : (nvarchar(128))
  - property_value : (nvarchar(max))
  Repo_user_type_fullname : (nvarchar(128))
  - RepoObject_fullname : (nvarchar(261))
  - RepoObject_fullname2 : (nvarchar(257))
  - RepoObject_guid : (uniqueidentifier)
  - RepoObject_name : (nvarchar(128))
  - RepoObject_schema_name : (nvarchar(128))
  - RepoObject_type : (char(2))
  - RepoObjectColumn_fullname : (nvarchar(520))
  - RepoObjectColumn_fullname2 : (nvarchar(386))
  - RepoObjectColumn_guid : (uniqueidentifier)
  - RepoObjectColumn_name : (nvarchar(128))
  --
  --
}

entity "puml-link:property.RepoObjectColumnProperty_InheritanceType_InheritanceDefinition.adoc[prefix=..]" as property.RepoObjectColumnProperty_InheritanceType_InheritanceDefinition << V >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  - **property_name** : (nvarchar(128))
  --
  Inheritance_StringAggSeparatorSql : (nvarchar(max))
  InheritanceDefinition : (nvarchar(max))
  InheritanceType : (int)
  par_Inheritance_StringAggSeparatorSql : (nvarchar(max))
  par_InheritanceDefinition : (nvarchar(max))
  par_InheritanceType : (int)
  property_value : (nvarchar(max))
  - RepoObjectColumn_name : (nvarchar(128))
  roc_Inheritance_StringAggSeparatorSql : (nvarchar(4000))
  roc_InheritanceDefinition : (nvarchar(4000))
  roc_InheritanceType : (tinyint)
  sub_Inheritance_StringAggSeparatorSql : (nvarchar(max))
  sub_InheritanceDefinition : (nvarchar(max))
  sub_InheritanceType : (int)
  --
  --
}

entity "puml-link:property.RepoObjectColumnProperty_sys_repo.adoc[prefix=..]" as property.RepoObjectColumnProperty_sys_repo << V >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  - **property_name** : (sysname)
  --
  property_value : (sql_variant)
  RepoObjectColumnProperty_id : (int)
  RepoObjectColumnProperty_property_value : (nvarchar(max))
  SysObject_name : (nvarchar(128))
  SysObject_schema_name : (nvarchar(128))
  SysObjectColumn_name : (nvarchar(128))
  --
  --
}

entity "puml-link:property.usp_RepoObjectColumn_Inheritance.adoc[prefix=..]" as property.usp_RepoObjectColumn_Inheritance << P >> {
  --
  --
  --
}

entity "puml-link:property.usp_RepoObjectColumnProperty_set.adoc[prefix=..]" as property.usp_RepoObjectColumnProperty_set << P >> {
  --
  --
  --
}

entity "puml-link:property.usp_sync_ExtendedProperties_Sys2Repo_InsertUpdate.adoc[prefix=..]" as property.usp_sync_ExtendedProperties_Sys2Repo_InsertUpdate << P >> {
  --
  --
  --
}

property.RepoObjectColumnProperty <.. property.RepoObjectColumnProperty_sys_repo
property.RepoObjectColumnProperty <.. property.ExtendedProperty_Repo2Sys_level2_RepoObjectColumn
property.RepoObjectColumnProperty <.. property.usp_sync_ExtendedProperties_Sys2Repo_InsertUpdate
property.RepoObjectColumnProperty <.. property.PropertyName_RepoObjectColumn
property.RepoObjectColumnProperty <.. property.usp_RepoObjectColumn_Inheritance
property.RepoObjectColumnProperty <.. property.RepoObjectColumnProperty_InheritanceType_InheritanceDefinition
property.RepoObjectColumnProperty <.. property.fs_get_RepoObjectColumnProperty_nvarchar
property.RepoObjectColumnProperty <.. property.usp_RepoObjectColumnProperty_set
property.RepoObjectColumnProperty <.. property.RepoObjectColumnProperty_ForUpdate
property.RepoObjectColumnProperty::inheritance <-- property.RepoObjectColumnProperty_ForUpdate::inheritance
property.RepoObjectColumnProperty::property_name <-- property.ExtendedProperty_Repo2Sys_level2_RepoObjectColumn::property_name
property.RepoObjectColumnProperty::property_name <-- property.RepoObjectColumnProperty_ForUpdate::property_name
property.RepoObjectColumnProperty::property_value <-- property.RepoObjectColumnProperty::property_int
property.RepoObjectColumnProperty::property_value <-- property.RepoObjectColumnProperty::property_bigint
property.RepoObjectColumnProperty::property_value <-- property.RepoObjectColumnProperty::property_real
property.RepoObjectColumnProperty::property_value <-- property.RepoObjectColumnProperty::property_float
property.RepoObjectColumnProperty::property_value <-- property.RepoObjectColumnProperty::property_money
property.RepoObjectColumnProperty::property_value <-- property.RepoObjectColumnProperty_InheritanceType_InheritanceDefinition::property_value
property.RepoObjectColumnProperty::property_value <-- property.RepoObjectColumnProperty_ForUpdate::property_value
property.RepoObjectColumnProperty::RepoObjectColumn_guid <-- property.ExtendedProperty_Repo2Sys_level2_RepoObjectColumn::RepoObjectColumn_guid
property.RepoObjectColumnProperty::RepoObjectColumn_guid <-- property.RepoObjectColumnProperty_ForUpdate::RepoObjectColumn_guid
property.RepoObjectColumnProperty::RepoObjectColumnProperty_id <-- property.RepoObjectColumnProperty_ForUpdate::RepoObjectColumnProperty_id
footer
to view a reduced diagram in original size and to be able to click on the links:
open the diagram in a new tab via the Context menu.
end footer

@enduml

