@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity "puml-link:reference.RepoObject_reference_T.adoc[prefix=..]" as reference.RepoObject_reference_T << U >> {
  **referenced_RepoObject_guid** : (uniqueidentifier)
  **referencing_RepoObject_guid** : (uniqueidentifier)
  --
  - is_ReversePersistenceViaView : (bit)
  referenced_entity_name : (nvarchar(128))
  - referenced_is_PersistenceSource : (bit)
  - referenced_is_PersistenceTarget : (bit)
  referenced_schema_name : (nvarchar(128))
  referenced_type : (char(2))
  referencing_entity_name : (nvarchar(128))
  - referencing_is_PersistenceTarget : (bit)
  - referencing_is_PersistenceUspSourceRef : (bit)
  referencing_is_PersistenceUspTargetRef : (bit)
  referencing_schema_name : (nvarchar(128))
  referencing_type : (varchar(2))
  # referenced_fullname : (nvarchar(261))
  # referenced_fullname2 : (nvarchar(257))
  # referencing_fullname : (nvarchar(261))
  # referencing_fullname2 : (nvarchar(257))
  --
  --
}

entity "puml-link:reference.RepoObjectColumn_reference_BySamePredecessors.adoc[prefix=..]" as reference.RepoObjectColumn_reference_BySamePredecessors << V >> {
  --
  definition : (nvarchar(max))
  - InformationSource : (varchar(37))
  is_computed : (bit)
  is_hidden : (bit)
  is_referenced_object : (bit)
  is_referencing_object_equal_referenced_object : (bit)
  referenced_column_name : (nvarchar(128))
  referenced_entity_name : (nvarchar(128))
  referenced_id : (int)
  referenced_minor_id : (int)
  referenced_node_id : (bigint)
  - referenced_RepoObject_guid : (uniqueidentifier)
  referenced_RepoObjectColumn_guid : (uniqueidentifier)
  referenced_schema_name : (nvarchar(128))
  referenced_type : (char(2))
  referencing_column_name : (nvarchar(128))
  - referencing_entity_name : (nvarchar(128))
  referencing_id : (int)
  referencing_minor_id : (int)
  referencing_node_id : (bigint)
  - referencing_RepoObject_guid : (uniqueidentifier)
  referencing_RepoObjectColumn_guid : (uniqueidentifier)
  - referencing_schema_name : (nvarchar(128))
  referencing_type : (char(2))
  --
  --
}

entity "puml-link:reference.RepoObjectColumn_reference_FirstResultSet.adoc[prefix=..]" as reference.RepoObjectColumn_reference_FirstResultSet << V >> {
  --
  - InformationSource : (varchar(37))
  is_hidden : (bit)
  is_referenced_object : (bit)
  is_referencing_object_equal_referenced_object : (bit)
  referenced_column_name : (nvarchar(128))
  referenced_entity_name : (nvarchar(128))
  referenced_id : (int)
  referenced_minor_id : (int)
  referenced_node_id : (bigint)
  referenced_RepoObject_guid : (uniqueidentifier)
  referenced_RepoObjectColumn_guid : (uniqueidentifier)
  referenced_schema_name : (nvarchar(128))
  referenced_type : (char(2))
  referencing_column_name : (nvarchar(128))
  - referencing_entity_name : (nvarchar(128))
  referencing_id : (int)
  referencing_minor_id : (int)
  referencing_node_id : (bigint)
  - referencing_RepoObject_guid : (uniqueidentifier)
  referencing_RepoObjectColumn_guid : (uniqueidentifier)
  - referencing_schema_name : (nvarchar(128))
  referencing_type : (char(2))
  --
  --
}

reference.RepoObject_reference_T <.. reference.RepoObjectColumn_reference_BySamePredecessors
reference.RepoObjectColumn_reference_FirstResultSet <.. reference.RepoObjectColumn_reference_BySamePredecessors
reference.RepoObject_reference_T::referenced_entity_name <-- reference.RepoObjectColumn_reference_BySamePredecessors::referenced_entity_name
reference.RepoObject_reference_T::referenced_RepoObject_guid <-- reference.RepoObjectColumn_reference_BySamePredecessors::referenced_RepoObject_guid
reference.RepoObject_reference_T::referenced_schema_name <-- reference.RepoObjectColumn_reference_BySamePredecessors::referenced_schema_name
reference.RepoObject_reference_T::referenced_type <-- reference.RepoObjectColumn_reference_BySamePredecessors::referenced_type
reference.RepoObjectColumn_reference_FirstResultSet::InformationSource <-- reference.RepoObjectColumn_reference_BySamePredecessors::InformationSource
reference.RepoObjectColumn_reference_FirstResultSet::is_hidden <-- reference.RepoObjectColumn_reference_BySamePredecessors::is_hidden
reference.RepoObjectColumn_reference_FirstResultSet::referencing_column_name <-- reference.RepoObjectColumn_reference_BySamePredecessors::referencing_column_name
reference.RepoObjectColumn_reference_FirstResultSet::referencing_column_name <-- reference.RepoObjectColumn_reference_BySamePredecessors::referenced_column_name
reference.RepoObjectColumn_reference_FirstResultSet::referencing_entity_name <-- reference.RepoObjectColumn_reference_BySamePredecessors::referencing_entity_name
reference.RepoObjectColumn_reference_FirstResultSet::referencing_id <-- reference.RepoObjectColumn_reference_BySamePredecessors::referencing_id
reference.RepoObjectColumn_reference_FirstResultSet::referencing_id <-- reference.RepoObjectColumn_reference_BySamePredecessors::referenced_id
reference.RepoObjectColumn_reference_FirstResultSet::referencing_minor_id <-- reference.RepoObjectColumn_reference_BySamePredecessors::referencing_minor_id
reference.RepoObjectColumn_reference_FirstResultSet::referencing_minor_id <-- reference.RepoObjectColumn_reference_BySamePredecessors::referenced_minor_id
reference.RepoObjectColumn_reference_FirstResultSet::referencing_node_id <-- reference.RepoObjectColumn_reference_BySamePredecessors::referencing_node_id
reference.RepoObjectColumn_reference_FirstResultSet::referencing_node_id <-- reference.RepoObjectColumn_reference_BySamePredecessors::referenced_node_id
reference.RepoObjectColumn_reference_FirstResultSet::referencing_RepoObject_guid <-- reference.RepoObjectColumn_reference_BySamePredecessors::referencing_RepoObject_guid
reference.RepoObjectColumn_reference_FirstResultSet::referencing_RepoObjectColumn_guid <-- reference.RepoObjectColumn_reference_BySamePredecessors::referencing_RepoObjectColumn_guid
reference.RepoObjectColumn_reference_FirstResultSet::referencing_RepoObjectColumn_guid <-- reference.RepoObjectColumn_reference_BySamePredecessors::referenced_RepoObjectColumn_guid
reference.RepoObjectColumn_reference_FirstResultSet::referencing_schema_name <-- reference.RepoObjectColumn_reference_BySamePredecessors::referencing_schema_name
reference.RepoObjectColumn_reference_FirstResultSet::referencing_type <-- reference.RepoObjectColumn_reference_BySamePredecessors::referencing_type
footer
to view a reduced diagram in original size and to be able to click on the links:
open the diagram in a new tab via the Context menu.
end footer

@enduml

