@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:reference.ReferenceTree_cyclic_ref_PersistenceUsp.adoc[]" as reference.ReferenceTree_cyclic_ref_PersistenceUsp << V >> {
  --
  - referenced_fullname : (nvarchar(261))
  - referenced_fullname2 : (nvarchar(257))
  - Referenced_guid : (uniqueidentifier)
  referenced_type : (char(2))
  - referencing_fullname : (nvarchar(261))
  - referencing_fullname2 : (nvarchar(257))
  - Referencing_guid : (uniqueidentifier)
  referencing_type : (varchar(2))
  --
  --
}

entity "puml-link:dhw:sqldb:reference.ReferenceTree_cyclic_ref_primary.adoc[]" as reference.ReferenceTree_cyclic_ref_primary << V >> {
  --
  Referenced_fullname : (nvarchar(261))
  Referenced_fullname2 : (nvarchar(257))
  - Referenced_guid : (uniqueidentifier)
  Referenced_type : (char(2))
  Referencing_fullname : (nvarchar(261))
  Referencing_fullname2 : (nvarchar(257))
  - Referencing_guid : (uniqueidentifier)
  Referencing_type : (varchar(2))
  --
  --
}

entity "puml-link:dhw:sqldb:reference.ReferenceTree_cyclic_union.adoc[]" as reference.ReferenceTree_cyclic_union << V >> {
  --
  Referenced_fullname : (nvarchar(261))
  Referenced_fullname2 : (nvarchar(257))
  - Referenced_guid : (uniqueidentifier)
  Referenced_type : (char(2))
  Referencing_fullname : (nvarchar(261))
  Referencing_fullname2 : (nvarchar(257))
  - Referencing_guid : (uniqueidentifier)
  Referencing_type : (varchar(2))
  --
  --
}

entity "puml-link:dhw:sqldb:reference.RepoObject_reference_T.adoc[]" as reference.RepoObject_reference_T << U >> {
  **referenced_RepoObject_guid** : (uniqueidentifier)
  **referencing_RepoObject_guid** : (uniqueidentifier)
  --
  - is_ReversePersistenceViaView : (bit)
  referenced_entity_name : (nvarchar(128))
  referenced_external_AntoraComponent : (nvarchar(128))
  referenced_external_AntoraModule : (nvarchar(128))
  referenced_is_external : (int)
  - referenced_is_PersistenceSource : (bit)
  - referenced_is_PersistenceTarget : (bit)
  referenced_schema_name : (nvarchar(128))
  referenced_type : (char(2))
  referencing_entity_name : (nvarchar(128))
  referencing_external_AntoraComponent : (nvarchar(128))
  referencing_external_AntoraModule : (nvarchar(128))
  referencing_is_external : (int)
  - referencing_is_PersistenceTarget : (bit)
  - referencing_is_PersistenceUspSourceRef : (bit)
  referencing_is_PersistenceUspTargetRef : (bit)
  referencing_schema_name : (nvarchar(128))
  referencing_type : (varchar(2))
  # referenced_fullname : (nvarchar(261))
  # referenced_fullname2 : (nvarchar(257))
  ~ referenced_puml_entity : (nvarchar(4000))
  # referencing_fullname : (nvarchar(261))
  # referencing_fullname2 : (nvarchar(257))
  ~ referencing_puml_entity : (nvarchar(4000))
  --
  --
}

reference.ReferenceTree_cyclic_ref_PersistenceUsp <.. reference.ReferenceTree_cyclic_union
reference.ReferenceTree_cyclic_ref_primary <.. reference.ReferenceTree_cyclic_ref_PersistenceUsp
reference.RepoObject_reference_T <.. reference.ReferenceTree_cyclic_ref_PersistenceUsp
"reference.RepoObject_reference_T::referenced_fullname" <-- "reference.ReferenceTree_cyclic_ref_PersistenceUsp::referenced_fullname"
"reference.RepoObject_reference_T::referenced_fullname2" <-- "reference.ReferenceTree_cyclic_ref_PersistenceUsp::referenced_fullname2"
"reference.RepoObject_reference_T::referenced_RepoObject_guid" <-- "reference.ReferenceTree_cyclic_ref_PersistenceUsp::Referencing_guid"
"reference.RepoObject_reference_T::referenced_type" <-- "reference.ReferenceTree_cyclic_ref_PersistenceUsp::referenced_type"
"reference.RepoObject_reference_T::referencing_fullname" <-- "reference.ReferenceTree_cyclic_ref_PersistenceUsp::referencing_fullname"
"reference.RepoObject_reference_T::referencing_fullname2" <-- "reference.ReferenceTree_cyclic_ref_PersistenceUsp::referencing_fullname2"
"reference.RepoObject_reference_T::referencing_RepoObject_guid" <-- "reference.ReferenceTree_cyclic_ref_PersistenceUsp::Referenced_guid"
"reference.RepoObject_reference_T::referencing_type" <-- "reference.ReferenceTree_cyclic_ref_PersistenceUsp::referencing_type"
@enduml

