@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:reference.RepoObject_ReferenceTree_0_30.adoc[]" as reference.RepoObject_ReferenceTree_0_30 << V >> {
  **RepoObject_guid** : (uniqueidentifier)
  **Referencing_guid** : (uniqueidentifier)
  **Referenced_guid** : (uniqueidentifier)
  --
  Referenced_Depth : (int)
  Referenced_fullname : (nvarchar(261))
  Referenced_fullname2 : (nvarchar(257))
  Referenced_type : (char(2))
  Referencing_Depth : (int)
  Referencing_fullname : (nvarchar(261))
  Referencing_fullname2 : (nvarchar(257))
  Referencing_type : (varchar(2))
  --
  --
}

entity "puml-link:dhw:sqldb:reference.RepoObject_ReferenceTree_0_30_T.adoc[]" as reference.RepoObject_ReferenceTree_0_30_T << U >> {
  **RepoObject_guid** : (uniqueidentifier)
  **Referencing_guid** : (uniqueidentifier)
  **Referenced_guid** : (uniqueidentifier)
  --
  Referenced_Depth : (int)
  Referenced_fullname : (nvarchar(261))
  Referenced_fullname2 : (nvarchar(257))
  Referenced_type : (char(2))
  Referencing_Depth : (int)
  Referencing_fullname : (nvarchar(261))
  Referencing_fullname2 : (nvarchar(257))
  Referencing_type : (varchar(2))
  --
  --
}

entity "puml-link:dhw:sqldb:reference.usp_PERSIST_RepoObject_ReferenceTree_0_30_T.adoc[]" as reference.usp_PERSIST_RepoObject_ReferenceTree_0_30_T << P >> {
  --
  --
  --
}

reference.RepoObject_ReferenceTree_0_30 <.. reference.RepoObject_ReferenceTree_0_30_T
reference.RepoObject_ReferenceTree_0_30_T <.. reference.usp_PERSIST_RepoObject_ReferenceTree_0_30_T
"reference.RepoObject_ReferenceTree_0_30::Referenced_Depth" <-- "reference.RepoObject_ReferenceTree_0_30_T::Referenced_Depth"
"reference.RepoObject_ReferenceTree_0_30::Referenced_fullname" <-- "reference.RepoObject_ReferenceTree_0_30_T::Referenced_fullname"
"reference.RepoObject_ReferenceTree_0_30::Referenced_fullname2" <-- "reference.RepoObject_ReferenceTree_0_30_T::Referenced_fullname2"
"reference.RepoObject_ReferenceTree_0_30::Referenced_guid" <-- "reference.RepoObject_ReferenceTree_0_30_T::Referenced_guid"
"reference.RepoObject_ReferenceTree_0_30::Referenced_type" <-- "reference.RepoObject_ReferenceTree_0_30_T::Referenced_type"
"reference.RepoObject_ReferenceTree_0_30::Referencing_Depth" <-- "reference.RepoObject_ReferenceTree_0_30_T::Referencing_Depth"
"reference.RepoObject_ReferenceTree_0_30::Referencing_fullname" <-- "reference.RepoObject_ReferenceTree_0_30_T::Referencing_fullname"
"reference.RepoObject_ReferenceTree_0_30::Referencing_fullname2" <-- "reference.RepoObject_ReferenceTree_0_30_T::Referencing_fullname2"
"reference.RepoObject_ReferenceTree_0_30::Referencing_guid" <-- "reference.RepoObject_ReferenceTree_0_30_T::Referencing_guid"
"reference.RepoObject_ReferenceTree_0_30::Referencing_type" <-- "reference.RepoObject_ReferenceTree_0_30_T::Referencing_type"
"reference.RepoObject_ReferenceTree_0_30::RepoObject_guid" <-- "reference.RepoObject_ReferenceTree_0_30_T::RepoObject_guid"
@enduml

