@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity "[[{site-url}/{page-component-name}/current/{page-module}/reference.RepoObject_reference.html reference.RepoObject_reference]]" as reference.RepoObject_reference << V >> {
  **referenced_RepoObject_guid** : (uniqueidentifier)
  **referencing_RepoObject_guid** : (uniqueidentifier)
  --
  referenced_entity_name : (nvarchar(128))
  referenced_schema_name : (nvarchar(128))
  referenced_type : (char(2))
  referencing_entity_name : (nvarchar(128))
  referencing_schema_name : (nvarchar(128))
  referencing_type : (varchar(2))
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/reference.RepoObject_reference_additional_internal.html reference.RepoObject_reference_additional_internal]]" as reference.RepoObject_reference_additional_internal << V >> {
  --
  - InformationSource : (varchar(30))
  - referenced_entity_name : (nvarchar(128))
  referenced_fullname : (nvarchar(261))
  referenced_id : (int)
  referenced_RepoObject_guid : (uniqueidentifier)
  - referenced_schema_name : (nvarchar(128))
  referenced_type : (char(2))
  - referencing_entity_name : (nvarchar(128))
  referencing_fullname : (nvarchar(261))
  referencing_id : (int)
  referencing_RepoObject_guid : (uniqueidentifier)
  - referencing_schema_name : (nvarchar(128))
  referencing_type : (char(2))
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/reference.RepoObject_reference_persistence.html reference.RepoObject_reference_persistence]]" as reference.RepoObject_reference_persistence << V >> {
  **referenced_RepoObject_guid** : (uniqueidentifier)
  - **referencing_RepoObject_guid** : (uniqueidentifier)
  --
  - InformationSource : (varchar(27))
  - referenced_entity_name : (nvarchar(128))
  - referenced_fullname : (nvarchar(261))
  referenced_id : (int)
  - referenced_schema_name : (nvarchar(128))
  referenced_type : (char(2))
  - referencing_entity_name : (nvarchar(128))
  - referencing_fullname : (nvarchar(261))
  referencing_id : (int)
  - referencing_schema_name : (nvarchar(128))
  referencing_type : (varchar(2))
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/reference.RepoObject_reference_persistence_target_as_source.html reference.RepoObject_reference_persistence_target_as_source]]" as reference.RepoObject_reference_persistence_target_as_source << V >> {
  --
  - InformationSource : (varchar(28))
  referenced_entity_name : (nvarchar(128))
  - referenced_fullname : (nvarchar(517))
  - referenced_id : (int)
  referenced_RepoObject_guid : (uniqueidentifier)
  referenced_schema_name : (nvarchar(128))
  referenced_type : (char(2))
  referencing_entity_name : (nvarchar(128))
  - referencing_fullname : (nvarchar(517))
  referencing_id : (int)
  referencing_RepoObject_guid : (uniqueidentifier)
  referencing_schema_name : (nvarchar(128))
  referencing_type : (char(2))
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/reference.RepoObject_reference_SqlExpressionDependencies.html reference.RepoObject_reference_SqlExpressionDependencies]]" as reference.RepoObject_reference_SqlExpressionDependencies << V >> {
  **referenced_RepoObject_guid** : (uniqueidentifier)
  **referencing_RepoObject_guid** : (uniqueidentifier)
  --
  - InformationSource : (varchar(31))
  referenced_entity_name : (nvarchar(128))
  - referenced_fullname : (nvarchar(517))
  referenced_id : (int)
  referenced_schema_name : (nvarchar(128))
  referenced_type : (char(2))
  referencing_entity_name : (nvarchar(128))
  - referencing_fullname : (nvarchar(517))
  - referencing_id : (int)
  referencing_schema_name : (nvarchar(128))
  referencing_type : (char(2))
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/reference.RepoObject_reference_union.html reference.RepoObject_reference_union]]" as reference.RepoObject_reference_union << V >> {
  **referenced_RepoObject_guid** : (uniqueidentifier)
  **referencing_RepoObject_guid** : (uniqueidentifier)
  --
  - InformationSource : (varchar(34))
  - one : (int)
  referenced_entity_name : (nvarchar(128))
  referenced_fullname : (nvarchar(517))
  referenced_id : (int)
  referenced_schema_name : (nvarchar(128))
  referenced_type : (char(2))
  referencing_entity_name : (nvarchar(128))
  referencing_fullname : (nvarchar(517))
  referencing_id : (int)
  referencing_schema_name : (nvarchar(128))
  referencing_type : (varchar(2))
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/reference.RepoObject_reference_virtual.html reference.RepoObject_reference_virtual]]" as reference.RepoObject_reference_virtual << V >> {
  --
  - InformationSource : (varchar(34))
  - referenced_entity_name : (nvarchar(128))
  - referenced_fullname : (nvarchar(261))
  referenced_id : (int)
  - referenced_RepoObject_guid : (uniqueidentifier)
  - referenced_schema_name : (nvarchar(128))
  referenced_type : (char(2))
  - referencing_entity_name : (nvarchar(128))
  - referencing_fullname : (nvarchar(261))
  referencing_id : (int)
  - referencing_RepoObject_guid : (uniqueidentifier)
  - referencing_schema_name : (nvarchar(128))
  referencing_type : (varchar(2))
  --
  --
}

reference.RepoObject_reference_additional_internal <.. reference.RepoObject_reference_union
reference.RepoObject_reference_persistence <.. reference.RepoObject_reference_union
reference.RepoObject_reference_persistence_target_as_source <.. reference.RepoObject_reference_union
reference.RepoObject_reference_SqlExpressionDependencies <.. reference.RepoObject_reference_union
reference.RepoObject_reference_union <.. reference.RepoObject_reference
reference.RepoObject_reference_virtual <.. reference.RepoObject_reference_union
reference.RepoObject_reference_union::referenced_entity_name <-- reference.RepoObject_reference::referenced_entity_name
reference.RepoObject_reference_union::referenced_RepoObject_guid <-- reference.RepoObject_reference::referenced_RepoObject_guid
reference.RepoObject_reference_union::referencing_RepoObject_guid <-- reference.RepoObject_reference::referencing_RepoObject_guid
footer
to view a reduced diagram in original size and to be able to click on the links:
open the diagram in a new tab via the Context menu.
end footer

@enduml

