@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:logs.usp_executionlog_insert.adoc[]" as logs.usp_ExecutionLog_insert << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_object.adoc[]" as reference.additional_Reference_Object << V >> {
  - **AntoraComponent** : (nvarchar(128))
  - **AntoraModule** : (nvarchar(128))
  - **SchemaName** : (nvarchar(128))
  - **ObjectName** : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_object_t.adoc[]" as reference.additional_Reference_Object_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - AntoraComponent : (nvarchar(128))
  - AntoraModule : (nvarchar(128))
  Description : (nvarchar(max))
  - ObjectName : (nvarchar(128))
  - SchemaName : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:reference.usp_additional_reference.adoc[]" as reference.usp_additional_Reference << P >> {
  --
}

entity "puml-link:dhw:sqldb:reference.usp_persist_additional_reference_object_t.adoc[]" as reference.usp_PERSIST_additional_Reference_Object_T << P >> {
  --
}

logs.usp_ExecutionLog_insert <.. reference.usp_PERSIST_additional_Reference_Object_T
reference.additional_Reference_Object <.. reference.usp_PERSIST_additional_Reference_Object_T
reference.additional_Reference_Object_T <.. reference.usp_PERSIST_additional_Reference_Object_T
reference.usp_PERSIST_additional_Reference_Object_T <.. reference.usp_additional_Reference
footer The diagram is interactive and contains links.
@enduml

