@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:reference.additional_reference_guid.adoc[]" as reference.additional_Reference_guid << V >> {
  --
  - referenced_AntoraComponent : (nvarchar(128))
  - referenced_AntoraModule : (nvarchar(128))
  referenced_Column : (nvarchar(128))
  referenced_external_AntoraComponent : (nvarchar(128))
  referenced_external_AntoraModule : (nvarchar(128))
  referenced_fullname : (nvarchar(261))
  referenced_id : (int)
  referenced_is_external : (bit)
  - referenced_Object : (nvarchar(128))
  referenced_RepoObject_guid : (uniqueidentifier)
  referenced_RepoObjectColumn_guid : (uniqueidentifier)
  - referenced_Schema : (nvarchar(128))
  referenced_type : (char(2))
  - referencing_AntoraComponent : (nvarchar(128))
  - referencing_AntoraModule : (nvarchar(128))
  referencing_Column : (nvarchar(128))
  referencing_external_AntoraComponent : (nvarchar(128))
  referencing_external_AntoraModule : (nvarchar(128))
  referencing_fullname : (nvarchar(261))
  referencing_id : (int)
  referencing_is_external : (bit)
  - referencing_Object : (nvarchar(128))
  referencing_RepoObject_guid : (uniqueidentifier)
  referencing_RepoObjectColumn_guid : (uniqueidentifier)
  - referencing_Schema : (nvarchar(128))
  referencing_type : (char(2))
  --
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_reference_additional.adoc[]" as reference.RepoObject_reference_additional << V >> {
  --
  - InformationSource : (varchar(30))
  - referenced_entity_name : (nvarchar(128))
  referenced_external_AntoraComponent : (nvarchar(128))
  referenced_external_AntoraModule : (nvarchar(128))
  referenced_fullname : (nvarchar(261))
  referenced_id : (int)
  referenced_is_external : (bit)
  referenced_RepoObject_guid : (uniqueidentifier)
  - referenced_schema_name : (nvarchar(128))
  referenced_type : (char(2))
  - referencing_entity_name : (nvarchar(128))
  referencing_external_AntoraComponent : (nvarchar(128))
  referencing_external_AntoraModule : (nvarchar(128))
  referencing_fullname : (nvarchar(261))
  referencing_id : (int)
  referencing_is_external : (bit)
  referencing_RepoObject_guid : (uniqueidentifier)
  - referencing_schema_name : (nvarchar(128))
  referencing_type : (char(2))
  --
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_reference_union.adoc[]" as reference.RepoObject_reference_union << V >> {
  **referenced_RepoObject_guid** : (uniqueidentifier)
  **referencing_RepoObject_guid** : (uniqueidentifier)
  --
  - InformationSource : (varchar(34))
  - one : (int)
  referenced_entity_name : (nvarchar(128))
  referenced_external_AntoraComponent : (nvarchar(128))
  referenced_external_AntoraModule : (nvarchar(128))
  referenced_fullname : (nvarchar(517))
  referenced_id : (int)
  referenced_is_external : (int)
  referenced_schema_name : (nvarchar(128))
  referenced_type : (char(2))
  referencing_entity_name : (nvarchar(128))
  referencing_external_AntoraComponent : (nvarchar(128))
  referencing_external_AntoraModule : (nvarchar(128))
  referencing_fullname : (nvarchar(517))
  referencing_id : (int)
  referencing_is_external : (int)
  referencing_schema_name : (nvarchar(128))
  referencing_type : (varchar(2))
  --
  --
}

reference.additional_Reference_guid <.. reference.RepoObject_reference_additional
reference.RepoObject_reference_additional <.. reference.RepoObject_reference_union
"reference.additional_Reference_guid::referenced_external_AntoraComponent" <-- "reference.RepoObject_reference_additional::referenced_external_AntoraComponent"
"reference.additional_Reference_guid::referenced_external_AntoraModule" <-- "reference.RepoObject_reference_additional::referenced_external_AntoraModule"
"reference.additional_Reference_guid::referenced_fullname" <-- "reference.RepoObject_reference_additional::referenced_fullname"
"reference.additional_Reference_guid::referenced_id" <-- "reference.RepoObject_reference_additional::referenced_id"
"reference.additional_Reference_guid::referenced_is_external" <-- "reference.RepoObject_reference_additional::referenced_is_external"
"reference.additional_Reference_guid::referenced_Object" <-- "reference.RepoObject_reference_additional::referenced_entity_name"
"reference.additional_Reference_guid::referenced_RepoObject_guid" <-- "reference.RepoObject_reference_additional::referenced_RepoObject_guid"
"reference.additional_Reference_guid::referenced_Schema" <-- "reference.RepoObject_reference_additional::referenced_schema_name"
"reference.additional_Reference_guid::referenced_type" <-- "reference.RepoObject_reference_additional::referenced_type"
"reference.additional_Reference_guid::referencing_external_AntoraComponent" <-- "reference.RepoObject_reference_additional::referencing_external_AntoraComponent"
"reference.additional_Reference_guid::referencing_external_AntoraModule" <-- "reference.RepoObject_reference_additional::referencing_external_AntoraModule"
"reference.additional_Reference_guid::referencing_fullname" <-- "reference.RepoObject_reference_additional::referencing_fullname"
"reference.additional_Reference_guid::referencing_id" <-- "reference.RepoObject_reference_additional::referencing_id"
"reference.additional_Reference_guid::referencing_is_external" <-- "reference.RepoObject_reference_additional::referencing_is_external"
"reference.additional_Reference_guid::referencing_Object" <-- "reference.RepoObject_reference_additional::referencing_entity_name"
"reference.additional_Reference_guid::referencing_RepoObject_guid" <-- "reference.RepoObject_reference_additional::referencing_RepoObject_guid"
"reference.additional_Reference_guid::referencing_Schema" <-- "reference.RepoObject_reference_additional::referencing_schema_name"
"reference.additional_Reference_guid::referencing_type" <-- "reference.RepoObject_reference_additional::referencing_type"
@enduml

