@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:reference.additional_reference_guid.adoc[]" as reference.additional_Reference_guid << V >> {
  - referenced_AntoraComponent : (nvarchar(128))
  - referenced_AntoraModule : (nvarchar(128))
  referenced_Column : (nvarchar(128))
  referenced_external_AntoraComponent : (nvarchar(128))
  referenced_external_AntoraModule : (nvarchar(128))
  referenced_fullname : (nvarchar(261))
  referenced_id : (int)
  referenced_is_external : (bit)
  - referenced_Object : (nvarchar(128))
  referenced_RepoObject_guid : (uniqueidentifier)
  referenced_RepoObjectColumn_guid : (uniqueidentifier)
  - referenced_Schema : (nvarchar(128))
  referenced_type : (char(2))
  - referencing_AntoraComponent : (nvarchar(128))
  - referencing_AntoraModule : (nvarchar(128))
  referencing_Column : (nvarchar(128))
  referencing_external_AntoraComponent : (nvarchar(128))
  referencing_external_AntoraModule : (nvarchar(128))
  referencing_fullname : (nvarchar(261))
  referencing_id : (int)
  referencing_is_external : (bit)
  - referencing_Object : (nvarchar(128))
  referencing_RepoObject_guid : (uniqueidentifier)
  referencing_RepoObjectColumn_guid : (uniqueidentifier)
  - referencing_Schema : (nvarchar(128))
  referencing_type : (char(2))
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_reference_t.adoc[]" as reference.RepoObject_reference_T << U >> {
  **referenced_RepoObject_guid** : (uniqueidentifier)
  **referencing_RepoObject_guid** : (uniqueidentifier)
  - is_ReversePersistenceViaView : (bit)
  referenced_entity_name : (nvarchar(128))
  referenced_external_AntoraComponent : (nvarchar(128))
  referenced_external_AntoraModule : (nvarchar(128))
  referenced_is_external : (int)
  - referenced_is_PersistenceSource : (bit)
  - referenced_is_PersistenceTarget : (bit)
  referenced_schema_name : (nvarchar(128))
  referenced_type : (char(2))
  referencing_entity_name : (nvarchar(128))
  referencing_external_AntoraComponent : (nvarchar(128))
  referencing_external_AntoraModule : (nvarchar(128))
  referencing_is_external : (int)
  - referencing_is_PersistenceTarget : (bit)
  - referencing_is_PersistenceUspSourceRef : (bit)
  referencing_is_PersistenceUspTargetRef : (bit)
  referencing_schema_name : (nvarchar(128))
  referencing_type : (varchar(2))
  # referenced_fullname : (nvarchar(261))
  # referenced_fullname2 : (nvarchar(257))
  ~ referenced_puml_entity : (nvarchar(4000))
  # referencing_fullname : (nvarchar(261))
  # referencing_fullname2 : (nvarchar(257))
  ~ referencing_puml_entity : (nvarchar(4000))
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_reference_additional.adoc[]" as reference.RepoObjectColumn_reference_additional << V >> {
  definition : (nvarchar(max))
  - InformationSource : (varchar(30))
  is_computed : (bit)
  is_referenced_object : (bit)
  is_referencing_object_equal_referenced_object : (bit)
  referenced_column_name : (nvarchar(128))
  - referenced_entity_name : (nvarchar(128))
  referenced_external_AntoraComponent : (nvarchar(128))
  referenced_external_AntoraModule : (nvarchar(128))
  referenced_id : (int)
  referenced_is_external : (bit)
  referenced_RepoObject_guid : (uniqueidentifier)
  referenced_RepoObjectColumn_guid : (uniqueidentifier)
  - referenced_schema_name : (nvarchar(128))
  referenced_type : (char(2))
  referencing_column_name : (nvarchar(128))
  - referencing_entity_name : (nvarchar(128))
  referencing_external_AntoraComponent : (nvarchar(128))
  referencing_external_AntoraModule : (nvarchar(128))
  referencing_id : (int)
  referencing_is_external : (bit)
  referencing_RepoObject_guid : (uniqueidentifier)
  referencing_RepoObjectColumn_guid : (uniqueidentifier)
  - referencing_schema_name : (nvarchar(128))
  referencing_type : (char(2))
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_reference_union.adoc[]" as reference.RepoObjectColumn_reference_union << V >> {
  definition : (nvarchar(max))
  - InformationSource : (varchar(34))
  is_computed : (bit)
  is_referenced_object : (bit)
  is_referencing_object_equal_referenced_object : (bit)
  referenced_column_name : (nvarchar(128))
  referenced_entity_name : (nvarchar(128))
  referenced_external_AntoraComponent : (nvarchar(128))
  referenced_external_AntoraModule : (nvarchar(128))
  referenced_id : (int)
  referenced_is_external : (tinyint)
  referenced_RepoObject_guid : (uniqueidentifier)
  referenced_RepoObjectColumn_guid : (uniqueidentifier)
  referenced_schema_name : (nvarchar(128))
  referenced_type : (char(2))
  referencing_column_name : (nvarchar(128))
  referencing_entity_name : (nvarchar(128))
  referencing_external_AntoraComponent : (nvarchar(128))
  referencing_external_AntoraModule : (nvarchar(128))
  referencing_id : (int)
  referencing_is_external : (tinyint)
  referencing_RepoObject_guid : (uniqueidentifier)
  referencing_RepoObjectColumn_guid : (uniqueidentifier)
  referencing_schema_name : (nvarchar(128))
  referencing_type : (char(2))
  --
}

reference.additional_Reference_guid <.. reference.RepoObjectColumn_reference_additional
reference.RepoObject_reference_T <.. reference.RepoObjectColumn_reference_additional
reference.RepoObjectColumn_reference_additional <.. reference.RepoObjectColumn_reference_union
"reference.additional_Reference_guid::referenced_Column" <-- "reference.RepoObjectColumn_reference_additional::referenced_column_name"
"reference.additional_Reference_guid::referenced_external_AntoraComponent" <-- "reference.RepoObjectColumn_reference_additional::referenced_external_AntoraComponent"
"reference.additional_Reference_guid::referenced_external_AntoraModule" <-- "reference.RepoObjectColumn_reference_additional::referenced_external_AntoraModule"
"reference.additional_Reference_guid::referenced_id" <-- "reference.RepoObjectColumn_reference_additional::referenced_id"
"reference.additional_Reference_guid::referenced_is_external" <-- "reference.RepoObjectColumn_reference_additional::referenced_is_external"
"reference.additional_Reference_guid::referenced_Object" <-- "reference.RepoObjectColumn_reference_additional::referenced_entity_name"
"reference.additional_Reference_guid::referenced_RepoObject_guid" <-- "reference.RepoObjectColumn_reference_additional::referenced_RepoObject_guid"
"reference.additional_Reference_guid::referenced_RepoObjectColumn_guid" <-- "reference.RepoObjectColumn_reference_additional::referenced_RepoObjectColumn_guid"
"reference.additional_Reference_guid::referenced_Schema" <-- "reference.RepoObjectColumn_reference_additional::referenced_schema_name"
"reference.additional_Reference_guid::referenced_type" <-- "reference.RepoObjectColumn_reference_additional::referenced_type"
"reference.additional_Reference_guid::referencing_Column" <-- "reference.RepoObjectColumn_reference_additional::referencing_column_name"
"reference.additional_Reference_guid::referencing_external_AntoraComponent" <-- "reference.RepoObjectColumn_reference_additional::referencing_external_AntoraComponent"
"reference.additional_Reference_guid::referencing_external_AntoraModule" <-- "reference.RepoObjectColumn_reference_additional::referencing_external_AntoraModule"
"reference.additional_Reference_guid::referencing_id" <-- "reference.RepoObjectColumn_reference_additional::referencing_id"
"reference.additional_Reference_guid::referencing_is_external" <-- "reference.RepoObjectColumn_reference_additional::referencing_is_external"
"reference.additional_Reference_guid::referencing_Object" <-- "reference.RepoObjectColumn_reference_additional::referencing_entity_name"
"reference.additional_Reference_guid::referencing_RepoObject_guid" <-- "reference.RepoObjectColumn_reference_additional::referencing_RepoObject_guid"
"reference.additional_Reference_guid::referencing_RepoObjectColumn_guid" <-- "reference.RepoObjectColumn_reference_additional::referencing_RepoObjectColumn_guid"
"reference.additional_Reference_guid::referencing_Schema" <-- "reference.RepoObjectColumn_reference_additional::referencing_schema_name"
"reference.additional_Reference_guid::referencing_type" <-- "reference.RepoObjectColumn_reference_additional::referencing_type"footer The diagram is interactive and contains links.
@enduml

