@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:property.repoobjectproperty_selectedpropertyname_split.adoc[]" as property.RepoObjectProperty_SelectedPropertyName_split << V >> {
  --
  LinePerGuidProperty : (bigint)
  - property_name : (nvarchar(128))
  property_value : (nvarchar(max))
  - RepoObject_guid : (uniqueidentifier)
  RowPerGuidPropertyLine : (bigint)
  value_line : (nvarchar(max))
  value_line_len : (bigint)
  value_line_row : (nvarchar(max))
  --
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_from_properties_src.adoc[]" as reference.additional_Reference_from_properties_src << V >> {
  **referenced_AntoraComponent** : (nvarchar(max))
  **referenced_AntoraModule** : (nvarchar(max))
  **referenced_Schema** : (nvarchar(max))
  **referenced_Object** : (nvarchar(max))
  **referenced_Column** : (nvarchar(max))
  **referencing_AntoraComponent** : (nvarchar(max))
  **referencing_AntoraModule** : (nvarchar(max))
  **referencing_Schema** : (nvarchar(max))
  **referencing_Object** : (nvarchar(max))
  **referencing_Column** : (nvarchar(max))
  --
  --
  --
}

entity "puml-link:dhw:sqldb:reference.additional_reference_from_properties_tgt.adoc[]" as reference.additional_Reference_from_properties_tgt << V >> {
  - **Id** : (int)
  --
  referenced_AntoraComponent : (nvarchar(max))
  referenced_AntoraModule : (nvarchar(max))
  referenced_Column : (nvarchar(max))
  referenced_Object : (nvarchar(max))
  referenced_Schema : (nvarchar(max))
  referencing_AntoraComponent : (nvarchar(max))
  referencing_AntoraModule : (nvarchar(max))
  referencing_Column : (nvarchar(max))
  referencing_Object : (nvarchar(max))
  referencing_Schema : (nvarchar(max))
  - tik : (nvarchar(1311))
  tik_hash : (binary(16))
  --
  --
}

entity "puml-link:dhw:sqldb:reference.usp_persist_additional_reference_from_properties_tgt.adoc[]" as reference.usp_PERSIST_additional_Reference_from_properties_tgt << P >> {
  --
  --
  --
}

property.RepoObjectProperty_SelectedPropertyName_split <.. reference.additional_Reference_from_properties_src
reference.additional_Reference_from_properties_src <.. reference.additional_Reference_from_properties_tgt
reference.additional_Reference_from_properties_src <.. reference.usp_PERSIST_additional_Reference_from_properties_tgt
"reference.additional_Reference_from_properties_src::referenced_AntoraComponent" <-- "reference.additional_Reference_from_properties_tgt::referenced_AntoraComponent"
"reference.additional_Reference_from_properties_src::referenced_AntoraModule" <-- "reference.additional_Reference_from_properties_tgt::referenced_AntoraModule"
"reference.additional_Reference_from_properties_src::referenced_Column" <-- "reference.additional_Reference_from_properties_tgt::referenced_Column"
"reference.additional_Reference_from_properties_src::referenced_Object" <-- "reference.additional_Reference_from_properties_tgt::referenced_Object"
"reference.additional_Reference_from_properties_src::referenced_Schema" <-- "reference.additional_Reference_from_properties_tgt::referenced_Schema"
"reference.additional_Reference_from_properties_src::referencing_AntoraComponent" <-- "reference.additional_Reference_from_properties_tgt::referencing_AntoraComponent"
"reference.additional_Reference_from_properties_src::referencing_AntoraModule" <-- "reference.additional_Reference_from_properties_tgt::referencing_AntoraModule"
"reference.additional_Reference_from_properties_src::referencing_Column" <-- "reference.additional_Reference_from_properties_tgt::referencing_Column"
"reference.additional_Reference_from_properties_src::referencing_Object" <-- "reference.additional_Reference_from_properties_tgt::referencing_Object"
"reference.additional_Reference_from_properties_src::referencing_Schema" <-- "reference.additional_Reference_from_properties_tgt::referencing_Schema"
@enduml

