@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity "[[{site-url}/{page-component-name}/current/{page-module}/reference.RepoObject_reference_T.html reference.RepoObject_reference_T]]" as reference.RepoObject_reference_T << U >> {
  **referenced_RepoObject_guid** : (uniqueidentifier)
  **referencing_RepoObject_guid** : (uniqueidentifier)
  --
  - is_ReversePersistenceViaView : (bit)
  referenced_entity_name : (nvarchar(128))
  - referenced_is_PersistenceSource : (bit)
  - referenced_is_PersistenceTarget : (bit)
  referenced_schema_name : (nvarchar(128))
  referenced_type : (char(2))
  referencing_entity_name : (nvarchar(128))
  - referencing_is_PersistenceTarget : (bit)
  - referencing_is_PersistenceUspSourceRef : (bit)
  referencing_is_PersistenceUspTargetRef : (bit)
  referencing_schema_name : (nvarchar(128))
  referencing_type : (varchar(2))
  # referenced_fullname : (nvarchar(261))
  # referenced_fullname2 : (nvarchar(257))
  # referencing_fullname : (nvarchar(261))
  # referencing_fullname2 : (nvarchar(257))
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/reference.RepoObjectColumn_reference_BySamePredecessors.html reference.RepoObjectColumn_reference_BySamePredecessors]]" as reference.RepoObjectColumn_reference_BySamePredecessors << V >> {
  --
  definition : (nvarchar(max))
  - InformationSource : (varchar(37))
  is_computed : (bit)
  is_hidden : (bit)
  is_referenced_object : (bit)
  is_referencing_object_equal_referenced_object : (bit)
  referenced_column_name : (nvarchar(128))
  referenced_entity_name : (nvarchar(128))
  referenced_id : (int)
  referenced_minor_id : (int)
  referenced_node_id : (bigint)
  - referenced_RepoObject_guid : (uniqueidentifier)
  referenced_RepoObjectColumn_guid : (uniqueidentifier)
  referenced_schema_name : (nvarchar(128))
  referenced_type : (char(2))
  referencing_column_name : (nvarchar(128))
  - referencing_entity_name : (nvarchar(128))
  referencing_id : (int)
  referencing_minor_id : (int)
  referencing_node_id : (bigint)
  - referencing_RepoObject_guid : (uniqueidentifier)
  referencing_RepoObjectColumn_guid : (uniqueidentifier)
  - referencing_schema_name : (nvarchar(128))
  referencing_type : (char(2))
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/reference.RepoObjectColumn_reference_FirstResultSet.html reference.RepoObjectColumn_reference_FirstResultSet]]" as reference.RepoObjectColumn_reference_FirstResultSet << V >> {
  --
  - InformationSource : (varchar(37))
  is_hidden : (bit)
  is_referenced_object : (bit)
  is_referencing_object_equal_referenced_object : (bit)
  referenced_column_name : (nvarchar(128))
  referenced_entity_name : (nvarchar(128))
  referenced_id : (int)
  referenced_minor_id : (int)
  referenced_node_id : (bigint)
  referenced_RepoObject_guid : (uniqueidentifier)
  referenced_RepoObjectColumn_guid : (uniqueidentifier)
  referenced_schema_name : (nvarchar(128))
  referenced_type : (char(2))
  referencing_column_name : (nvarchar(128))
  - referencing_entity_name : (nvarchar(128))
  referencing_id : (int)
  referencing_minor_id : (int)
  referencing_node_id : (bigint)
  - referencing_RepoObject_guid : (uniqueidentifier)
  referencing_RepoObjectColumn_guid : (uniqueidentifier)
  - referencing_schema_name : (nvarchar(128))
  referencing_type : (char(2))
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/reference.RepoObjectSource_FirstResultSet.html reference.RepoObjectSource_FirstResultSet]]" as reference.RepoObjectSource_FirstResultSet << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **column_ordinal** : (int)
  --
  - created_dt : (datetime)
  is_hidden : (bit)
  source_column_name : (nvarchar(128))
  source_database_name : (nvarchar(128))
  source_schema_name : (nvarchar(128))
  source_server_name : (nvarchar(128))
  source_table_name : (nvarchar(128))
  system_type_id : (int)
  system_type_name : (nvarchar(128))
  target_column_name : (nvarchar(128))
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/repo.RepoObject.html repo.RepoObject]]" as repo.RepoObject << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
  has_execution_plan_issue : (bit)
  has_get_referenced_issue : (bit)
  Inheritance_StringAggSeparatorSql : (nvarchar(4000))
  InheritanceDefinition : (nvarchar(4000))
  InheritanceType : (tinyint)
  - is_DocsExclude : (bit)
  is_repo_managed : (bit)
  is_required_ObjectMerge : (bit)
  - is_ssas : (bit)
  is_SysObject_missing : (bit)
  - modify_dt : (datetime)
  pk_index_guid : (uniqueidentifier)
  pk_IndexPatternColumnName_new : (nvarchar(4000))
  Repo_history_table_guid : (uniqueidentifier)
  Repo_temporal_type : (tinyint)
  - RepoObject_name : (nvarchar(128))
  RepoObject_Referencing_Count : (int)
  - RepoObject_schema_name : (nvarchar(128))
  - RepoObject_type : (char(2))
  SysObject_id : (int)
  SysObject_modify_date : (datetime)
  - SysObject_name : (nvarchar(128))
  - SysObject_parent_object_id : (int)
  - SysObject_schema_name : (nvarchar(128))
  SysObject_type : (char(2))
  ~ has_different_sys_names : (bit)
  # is_RepoObject_name_uniqueidentifier : (int)
  # is_SysObject_name_uniqueidentifier : (int)
  ~ node_id : (bigint)
  # RepoObject_fullname : (nvarchar(261))
  # RepoObject_fullname2 : (nvarchar(257))
  # SysObject_fullname : (nvarchar(261))
  # SysObject_fullname2 : (nvarchar(257))
  ~ SysObject_query_sql : (nvarchar(406))
  # usp_persistence_fullname2 : (nvarchar(269))
  # usp_persistence_name : (nvarchar(140))
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/repo.RepoObjectColumn_gross.html repo.RepoObjectColumn_gross]]" as repo.RepoObjectColumn_gross << V >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  --
  - Column_name : (nvarchar(128))
  Description : (nvarchar(max))
  has_different_sys_names : (bit)
  has_get_referenced_issue : (bit)
  Inheritance_StringAggSeparatorSql : (nvarchar(4000))
  InheritanceDefinition : (nvarchar(4000))
  InheritanceType : (tinyint)
  is_persistence_no_check : (bit)
  is_persistence_no_include : (bit)
  is_persistence_no_update : (bit)
  is_query_plan_expression : (bit)
  is_repo_managed : (bit)
  - is_RepoObject_name_uniqueidentifier : (int)
  - is_RepoObjectColumn_name_uniqueidentifier : (int)
  is_required_ColumnMerge : (bit)
  - is_ssas : (bit)
  is_SysObject_missing : (bit)
  - is_SysObject_name_uniqueidentifier : (int)
  is_SysObjectColumn_missing : (bit)
  - is_SysObjectColumn_name_uniqueidentifier : (int)
  - modify_dt : (datetime)
  node_id : (bigint)
  persistence_source_RepoObject_guid : (uniqueidentifier)
  persistence_source_RepoObjectColumn_guid : (uniqueidentifier)
  pk_index_guid : (uniqueidentifier)
  Property_ms_description : (nvarchar(4000))
  Referencing_Count : (int)
  Repo_default_definition : (nvarchar(max))
  Repo_default_is_system_named : (bit)
  Repo_default_name : (nvarchar(128))
  Repo_definition : (nvarchar(max))
  - Repo_generated_always_type : (tinyint)
  Repo_graph_type : (int)
  Repo_increment_value : (sql_variant)
  - Repo_is_computed : (bit)
  - Repo_is_identity : (bit)
  Repo_is_nullable : (bit)
  Repo_is_persisted : (bit)
  Repo_seed_value : (sql_variant)
  Repo_user_type_fullname : (nvarchar(128))
  Repo_user_type_name : (nvarchar(128))
  Repo_uses_database_collation : (bit)
  - RepoObject_fullname : (nvarchar(261))
  - RepoObject_fullname2 : (nvarchar(257))
  - RepoObject_guid : (uniqueidentifier)
  - RepoObject_name : (nvarchar(128))
  RepoObject_Referencing_Count : (int)
  - RepoObject_schema_name : (nvarchar(128))
  - RepoObject_type : (char(2))
  RepoObjectColumn_column_id : (int)
  - RepoObjectColumn_fullname : (nvarchar(520))
  - RepoObjectColumn_fullname2 : (nvarchar(386))
  - RepoObjectColumn_name : (nvarchar(128))
  - SysObject_fullname : (nvarchar(261))
  - SysObject_fullname2 : (nvarchar(257))
  SysObject_id : (int)
  SysObject_modify_date : (datetime)
  - SysObject_name : (nvarchar(128))
  - SysObject_parent_object_id : (int)
  - SysObject_schema_name : (nvarchar(128))
  SysObject_type : (char(2))
  SysObjectColumn_column_id : (int)
  - SysObjectColumn_name : (nvarchar(128))
  tabcol_Description : (nvarchar(max))
  tabcol_DisplayFolder : (nvarchar(500))
  tabcol_Expression : (nvarchar(max))
  tabcol_FormatString : (nvarchar(500))
  - tabcol_IsHidden : (bit)
  - tabcol_IsKey : (bit)
  - tabcol_IsUnique : (bit)
  tabcol_SummarizeBy : (nvarchar(500))
  tabcol_Type : (nvarchar(500))
  --
  --
}

reference.RepoObject_reference_T <.. reference.RepoObjectColumn_reference_FirstResultSet
reference.RepoObjectColumn_reference_FirstResultSet <.. reference.RepoObjectColumn_reference_BySamePredecessors
reference.RepoObjectSource_FirstResultSet <.. reference.RepoObjectColumn_reference_FirstResultSet
repo.RepoObject <.. reference.RepoObjectColumn_reference_FirstResultSet
repo.RepoObjectColumn_gross <.. reference.RepoObjectColumn_reference_FirstResultSet
reference.RepoObjectColumn_reference_FirstResultSet::InformationSource <-- reference.RepoObjectColumn_reference_BySamePredecessors::InformationSource
reference.RepoObjectColumn_reference_FirstResultSet::is_hidden <-- reference.RepoObjectColumn_reference_BySamePredecessors::is_hidden
reference.RepoObjectColumn_reference_FirstResultSet::referencing_column_name <-- reference.RepoObjectColumn_reference_BySamePredecessors::referencing_column_name
reference.RepoObjectColumn_reference_FirstResultSet::referencing_column_name <-- reference.RepoObjectColumn_reference_BySamePredecessors::referenced_column_name
reference.RepoObjectColumn_reference_FirstResultSet::referencing_entity_name <-- reference.RepoObjectColumn_reference_BySamePredecessors::referencing_entity_name
reference.RepoObjectColumn_reference_FirstResultSet::referencing_id <-- reference.RepoObjectColumn_reference_BySamePredecessors::referencing_id
reference.RepoObjectColumn_reference_FirstResultSet::referencing_id <-- reference.RepoObjectColumn_reference_BySamePredecessors::referenced_id
reference.RepoObjectColumn_reference_FirstResultSet::referencing_minor_id <-- reference.RepoObjectColumn_reference_BySamePredecessors::referencing_minor_id
reference.RepoObjectColumn_reference_FirstResultSet::referencing_minor_id <-- reference.RepoObjectColumn_reference_BySamePredecessors::referenced_minor_id
reference.RepoObjectColumn_reference_FirstResultSet::referencing_node_id <-- reference.RepoObjectColumn_reference_BySamePredecessors::referencing_node_id
reference.RepoObjectColumn_reference_FirstResultSet::referencing_node_id <-- reference.RepoObjectColumn_reference_BySamePredecessors::referenced_node_id
reference.RepoObjectColumn_reference_FirstResultSet::referencing_RepoObject_guid <-- reference.RepoObjectColumn_reference_BySamePredecessors::referencing_RepoObject_guid
reference.RepoObjectColumn_reference_FirstResultSet::referencing_RepoObjectColumn_guid <-- reference.RepoObjectColumn_reference_BySamePredecessors::referencing_RepoObjectColumn_guid
reference.RepoObjectColumn_reference_FirstResultSet::referencing_RepoObjectColumn_guid <-- reference.RepoObjectColumn_reference_BySamePredecessors::referenced_RepoObjectColumn_guid
reference.RepoObjectColumn_reference_FirstResultSet::referencing_schema_name <-- reference.RepoObjectColumn_reference_BySamePredecessors::referencing_schema_name
reference.RepoObjectColumn_reference_FirstResultSet::referencing_type <-- reference.RepoObjectColumn_reference_BySamePredecessors::referencing_type
reference.RepoObjectSource_FirstResultSet::is_hidden <-- reference.RepoObjectColumn_reference_FirstResultSet::is_hidden
reference.RepoObjectSource_FirstResultSet::RepoObject_guid <-- reference.RepoObjectColumn_reference_FirstResultSet::referencing_RepoObject_guid
reference.RepoObjectSource_FirstResultSet::source_column_name <-- reference.RepoObjectColumn_reference_FirstResultSet::referenced_column_name
reference.RepoObjectSource_FirstResultSet::source_schema_name <-- reference.RepoObjectColumn_reference_FirstResultSet::referenced_schema_name
reference.RepoObjectSource_FirstResultSet::source_table_name <-- reference.RepoObjectColumn_reference_FirstResultSet::referenced_entity_name
reference.RepoObjectSource_FirstResultSet::target_column_name <-- reference.RepoObjectColumn_reference_FirstResultSet::referencing_column_name
repo.RepoObject::SysObject_id <-- reference.RepoObjectColumn_reference_FirstResultSet::referencing_id
repo.RepoObject::SysObject_name <-- reference.RepoObjectColumn_reference_FirstResultSet::referencing_entity_name
repo.RepoObject::SysObject_schema_name <-- reference.RepoObjectColumn_reference_FirstResultSet::referencing_schema_name
repo.RepoObject::SysObject_type <-- reference.RepoObjectColumn_reference_FirstResultSet::referencing_type
repo.RepoObjectColumn_gross::RepoObject_guid <-- reference.RepoObjectColumn_reference_FirstResultSet::referenced_RepoObject_guid
repo.RepoObjectColumn_gross::RepoObjectColumn_guid <-- reference.RepoObjectColumn_reference_FirstResultSet::referencing_RepoObjectColumn_guid
repo.RepoObjectColumn_gross::RepoObjectColumn_guid <-- reference.RepoObjectColumn_reference_FirstResultSet::referenced_RepoObjectColumn_guid
repo.RepoObjectColumn_gross::SysObject_id <-- reference.RepoObjectColumn_reference_FirstResultSet::referenced_id
repo.RepoObjectColumn_gross::SysObject_type <-- reference.RepoObjectColumn_reference_FirstResultSet::referenced_type
repo.RepoObjectColumn_gross::SysObjectColumn_column_id <-- reference.RepoObjectColumn_reference_FirstResultSet::referencing_minor_id
repo.RepoObjectColumn_gross::SysObjectColumn_column_id <-- reference.RepoObjectColumn_reference_FirstResultSet::referenced_minor_id
footer
to view a reduced diagram in original size and to be able to click on the links:
open the diagram in a new tab via the Context menu.
end footer

@enduml

