@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_reference_firstresultset.adoc[]" as reference.RepoObjectColumn_reference_FirstResultSet << V >> {
  - InformationSource : (varchar(37))
  is_hidden : (bit)
  is_referenced_object : (bit)
  is_referencing_object_equal_referenced_object : (bit)
  referenced_column_name : (nvarchar(128))
  referenced_entity_name : (nvarchar(128))
  referenced_id : (int)
  referenced_minor_id : (int)
  referenced_node_id : (bigint)
  referenced_RepoObject_guid : (uniqueidentifier)
  referenced_RepoObjectColumn_guid : (uniqueidentifier)
  referenced_schema_name : (nvarchar(128))
  referenced_type : (char(2))
  referencing_column_name : (nvarchar(128))
  - referencing_entity_name : (nvarchar(128))
  referencing_id : (int)
  referencing_minor_id : (int)
  referencing_node_id : (bigint)
  - referencing_RepoObject_guid : (uniqueidentifier)
  referencing_RepoObjectColumn_guid : (uniqueidentifier)
  - referencing_schema_name : (nvarchar(128))
  referencing_type : (char(2))
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectsource_firstresultset.adoc[]" as reference.RepoObjectSource_FirstResultSet << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  - **column_ordinal** : (int)
  - created_dt : (datetime)
  is_hidden : (bit)
  source_column_name : (nvarchar(128))
  source_database_name : (nvarchar(128))
  source_schema_name : (nvarchar(128))
  source_server_name : (nvarchar(128))
  source_table_name : (nvarchar(128))
  system_type_id : (int)
  system_type_name : (nvarchar(128))
  target_column_name : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:reference.usp_repoobjectsource_firstresultset.adoc[]" as reference.usp_RepoObjectSource_FirstResultSet << P >> {
  --
}

reference.RepoObjectSource_FirstResultSet <.. reference.RepoObjectColumn_reference_FirstResultSet
reference.RepoObjectSource_FirstResultSet <.. reference.usp_RepoObjectSource_FirstResultSet
"reference.RepoObjectSource_FirstResultSet::is_hidden" <-- "reference.RepoObjectColumn_reference_FirstResultSet::is_hidden"
"reference.RepoObjectSource_FirstResultSet::RepoObject_guid" <-- "reference.RepoObjectColumn_reference_FirstResultSet::referencing_RepoObject_guid"
"reference.RepoObjectSource_FirstResultSet::source_column_name" <-- "reference.RepoObjectColumn_reference_FirstResultSet::referenced_column_name"
"reference.RepoObjectSource_FirstResultSet::source_schema_name" <-- "reference.RepoObjectColumn_reference_FirstResultSet::referenced_schema_name"
"reference.RepoObjectSource_FirstResultSet::source_table_name" <-- "reference.RepoObjectColumn_reference_FirstResultSet::referenced_entity_name"
"reference.RepoObjectSource_FirstResultSet::target_column_name" <-- "reference.RepoObjectColumn_reference_FirstResultSet::referencing_column_name"footer The diagram is interactive and contains links.
@enduml

