@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity "puml-link:config.fs_get_parameter_value.adoc[prefix=..]" as config.fs_get_parameter_value << FN >> {
  --
  --
  --
}

entity "puml-link:reference.additional_Reference.adoc[prefix=..]" as reference.additional_Reference << U >> {
  - **Id** : (int)
  --
  - referenced_AntoraComponent : (nvarchar(128))
  - referenced_AntoraModule : (nvarchar(128))
  referenced_Column : (nvarchar(128))
  - referenced_Object : (nvarchar(128))
  - referenced_Schema : (nvarchar(128))
  - referencing_AntoraComponent : (nvarchar(128))
  - referencing_AntoraModule : (nvarchar(128))
  referencing_Column : (nvarchar(128))
  - referencing_Object : (nvarchar(128))
  - referencing_Schema : (nvarchar(128))
  # tik : (nvarchar(1311))
  # tik_hash : (binary(16))
  --
  --
}

entity "puml-link:reference.additional_Reference_guid.adoc[prefix=..]" as reference.additional_Reference_guid << V >> {
  --
  - is_internal : (int)
  - referenced_AntoraComponent : (nvarchar(128))
  - referenced_AntoraModule : (nvarchar(128))
  referenced_Column : (nvarchar(128))
  referenced_fullname : (nvarchar(261))
  referenced_id : (int)
  - referenced_Object : (nvarchar(128))
  referenced_RepoObject_guid : (uniqueidentifier)
  referenced_RepoObjectColumn_guid : (uniqueidentifier)
  - referenced_Schema : (nvarchar(128))
  referenced_type : (char(2))
  - referencing_AntoraComponent : (nvarchar(128))
  - referencing_AntoraModule : (nvarchar(128))
  referencing_Column : (nvarchar(128))
  referencing_fullname : (nvarchar(261))
  referencing_id : (int)
  - referencing_Object : (nvarchar(128))
  referencing_RepoObject_guid : (uniqueidentifier)
  referencing_RepoObjectColumn_guid : (uniqueidentifier)
  - referencing_Schema : (nvarchar(128))
  referencing_type : (char(2))
  --
  --
}

entity "puml-link:reference.RepoObject_ExternalReferencedList.adoc[prefix=..]" as reference.RepoObject_ExternalReferencedList << V >> {
  --
  AntoraExternalReferencedList : (nvarchar(max))
  RepoObject_guid : (uniqueidentifier)
  --
  --
}

entity "puml-link:reference.RepoObject_ExternalReferencingList.adoc[prefix=..]" as reference.RepoObject_ExternalReferencingList << V >> {
  --
  AntoraExternalReferencingList : (nvarchar(max))
  RepoObject_guid : (uniqueidentifier)
  --
  --
}

entity "puml-link:reference.RepoObject_reference_additional_internal.adoc[prefix=..]" as reference.RepoObject_reference_additional_internal << V >> {
  --
  - InformationSource : (varchar(30))
  - referenced_entity_name : (nvarchar(128))
  referenced_fullname : (nvarchar(261))
  referenced_id : (int)
  referenced_RepoObject_guid : (uniqueidentifier)
  - referenced_schema_name : (nvarchar(128))
  referenced_type : (char(2))
  - referencing_entity_name : (nvarchar(128))
  referencing_fullname : (nvarchar(261))
  referencing_id : (int)
  referencing_RepoObject_guid : (uniqueidentifier)
  - referencing_schema_name : (nvarchar(128))
  referencing_type : (char(2))
  --
  --
}

entity "puml-link:reference.RepoObjectColumn_reference_additional_internal.adoc[prefix=..]" as reference.RepoObjectColumn_reference_additional_internal << V >> {
  --
  definition : (nvarchar(max))
  - InformationSource : (varchar(30))
  is_computed : (bit)
  is_referenced_object : (bit)
  is_referencing_object_equal_referenced_object : (bit)
  referenced_column_name : (nvarchar(128))
  - referenced_entity_name : (nvarchar(128))
  referenced_id : (int)
  referenced_RepoObject_guid : (uniqueidentifier)
  referenced_RepoObjectColumn_guid : (uniqueidentifier)
  - referenced_schema_name : (nvarchar(128))
  referenced_type : (char(2))
  referencing_column_name : (nvarchar(128))
  - referencing_entity_name : (nvarchar(128))
  referencing_id : (int)
  referencing_RepoObject_guid : (uniqueidentifier)
  referencing_RepoObjectColumn_guid : (uniqueidentifier)
  - referencing_schema_name : (nvarchar(128))
  referencing_type : (char(2))
  --
  --
}

entity "puml-link:repo.RepoObject.adoc[prefix=..]" as repo.RepoObject << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
  has_execution_plan_issue : (bit)
  has_get_referenced_issue : (bit)
  Inheritance_StringAggSeparatorSql : (nvarchar(4000))
  InheritanceDefinition : (nvarchar(4000))
  InheritanceType : (tinyint)
  - is_DocsExclude : (bit)
  is_repo_managed : (bit)
  is_required_ObjectMerge : (bit)
  - is_ssas : (bit)
  is_SysObject_missing : (bit)
  - modify_dt : (datetime)
  pk_index_guid : (uniqueidentifier)
  pk_IndexPatternColumnName_new : (nvarchar(4000))
  Repo_history_table_guid : (uniqueidentifier)
  Repo_temporal_type : (tinyint)
  - RepoObject_name : (nvarchar(128))
  RepoObject_Referencing_Count : (int)
  - RepoObject_schema_name : (nvarchar(128))
  - RepoObject_type : (char(2))
  SysObject_id : (int)
  SysObject_modify_date : (datetime)
  - SysObject_name : (nvarchar(128))
  - SysObject_parent_object_id : (int)
  - SysObject_schema_name : (nvarchar(128))
  SysObject_type : (char(2))
  ~ has_different_sys_names : (bit)
  # is_RepoObject_name_uniqueidentifier : (int)
  # is_SysObject_name_uniqueidentifier : (int)
  ~ node_id : (bigint)
  # RepoObject_fullname : (nvarchar(261))
  # RepoObject_fullname2 : (nvarchar(257))
  # SysObject_fullname : (nvarchar(261))
  # SysObject_fullname2 : (nvarchar(257))
  ~ SysObject_query_sql : (nvarchar(406))
  # usp_persistence_fullname2 : (nvarchar(269))
  # usp_persistence_name : (nvarchar(140))
  --
  --
}

entity "puml-link:repo.RepoObjectColumn.adoc[prefix=..]" as repo.RepoObjectColumn << U >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  --
  Inheritance_StringAggSeparatorSql : (nvarchar(4000))
  InheritanceDefinition : (nvarchar(4000))
  InheritanceType : (tinyint)
  is_persistence_no_check : (bit)
  is_persistence_no_include : (bit)
  is_persistence_no_update : (bit)
  is_query_plan_expression : (bit)
  is_required_ColumnMerge : (bit)
  is_SysObjectColumn_missing : (bit)
  persistence_source_RepoObjectColumn_guid : (uniqueidentifier)
  Referencing_Count : (int)
  Repo_default_definition : (nvarchar(max))
  Repo_default_is_system_named : (bit)
  Repo_default_name : (nvarchar(128))
  Repo_definition : (nvarchar(max))
  - Repo_generated_always_type : (tinyint)
  Repo_graph_type : (int)
  Repo_increment_value : (sql_variant)
  - Repo_is_computed : (bit)
  - Repo_is_identity : (bit)
  Repo_is_nullable : (bit)
  Repo_is_persisted : (bit)
  Repo_seed_value : (sql_variant)
  Repo_user_type_fullname : (nvarchar(128))
  Repo_user_type_name : (nvarchar(128))
  Repo_uses_database_collation : (bit)
  - RepoObject_guid : (uniqueidentifier)
  RepoObjectColumn_column_id : (int)
  - RepoObjectColumn_name : (nvarchar(128))
  SysObjectColumn_column_id : (int)
  - SysObjectColumn_name : (nvarchar(128))
  # Column_name : (nvarchar(128))
  ~ has_different_sys_names : (bit)
  # is_RepoObjectColumn_name_uniqueidentifier : (int)
  # is_SysObjectColumn_name_uniqueidentifier : (int)
  --
  --
}

config.fs_get_parameter_value <.. reference.additional_Reference_guid
reference.additional_Reference <.. reference.additional_Reference_guid
reference.additional_Reference_guid <.. reference.RepoObject_ExternalReferencedList
reference.additional_Reference_guid <.. reference.RepoObject_ExternalReferencingList
reference.additional_Reference_guid <.. reference.RepoObject_reference_additional_internal
reference.additional_Reference_guid <.. reference.RepoObjectColumn_reference_additional_internal
repo.RepoObject <.. reference.additional_Reference_guid
repo.RepoObjectColumn <.. reference.additional_Reference_guid
reference.additional_Reference::referenced_AntoraComponent <-- reference.additional_Reference_guid::referenced_AntoraComponent
reference.additional_Reference::referenced_AntoraModule <-- reference.additional_Reference_guid::referenced_AntoraModule
reference.additional_Reference::referenced_Column <-- reference.additional_Reference_guid::referenced_Column
reference.additional_Reference::referenced_Object <-- reference.additional_Reference_guid::referenced_Object
reference.additional_Reference::referenced_Schema <-- reference.additional_Reference_guid::referenced_Schema
reference.additional_Reference::referencing_AntoraComponent <-- reference.additional_Reference_guid::referencing_AntoraComponent
reference.additional_Reference::referencing_AntoraModule <-- reference.additional_Reference_guid::referencing_AntoraModule
reference.additional_Reference::referencing_Column <-- reference.additional_Reference_guid::referencing_Column
reference.additional_Reference::referencing_Object <-- reference.additional_Reference_guid::referencing_Object
reference.additional_Reference::referencing_Schema <-- reference.additional_Reference_guid::referencing_Schema
reference.additional_Reference_guid::referenced_Column <-- reference.RepoObjectColumn_reference_additional_internal::referenced_column_name
reference.additional_Reference_guid::referenced_fullname <-- reference.RepoObject_reference_additional_internal::referenced_fullname
reference.additional_Reference_guid::referenced_id <-- reference.RepoObject_reference_additional_internal::referenced_id
reference.additional_Reference_guid::referenced_id <-- reference.RepoObjectColumn_reference_additional_internal::referenced_id
reference.additional_Reference_guid::referenced_Object <-- reference.RepoObject_reference_additional_internal::referenced_entity_name
reference.additional_Reference_guid::referenced_Object <-- reference.RepoObjectColumn_reference_additional_internal::referenced_entity_name
reference.additional_Reference_guid::referenced_RepoObject_guid <-- reference.RepoObject_reference_additional_internal::referenced_RepoObject_guid
reference.additional_Reference_guid::referenced_RepoObject_guid <-- reference.RepoObjectColumn_reference_additional_internal::referenced_RepoObject_guid
reference.additional_Reference_guid::referenced_RepoObjectColumn_guid <-- reference.RepoObjectColumn_reference_additional_internal::referenced_RepoObjectColumn_guid
reference.additional_Reference_guid::referenced_Schema <-- reference.RepoObject_reference_additional_internal::referenced_schema_name
reference.additional_Reference_guid::referenced_Schema <-- reference.RepoObjectColumn_reference_additional_internal::referenced_schema_name
reference.additional_Reference_guid::referenced_type <-- reference.RepoObject_reference_additional_internal::referenced_type
reference.additional_Reference_guid::referenced_type <-- reference.RepoObjectColumn_reference_additional_internal::referenced_type
reference.additional_Reference_guid::referencing_Column <-- reference.RepoObjectColumn_reference_additional_internal::referencing_column_name
reference.additional_Reference_guid::referencing_fullname <-- reference.RepoObject_reference_additional_internal::referencing_fullname
reference.additional_Reference_guid::referencing_id <-- reference.RepoObject_reference_additional_internal::referencing_id
reference.additional_Reference_guid::referencing_id <-- reference.RepoObjectColumn_reference_additional_internal::referencing_id
reference.additional_Reference_guid::referencing_Object <-- reference.RepoObject_reference_additional_internal::referencing_entity_name
reference.additional_Reference_guid::referencing_Object <-- reference.RepoObjectColumn_reference_additional_internal::referencing_entity_name
reference.additional_Reference_guid::referencing_RepoObject_guid <-- reference.RepoObject_reference_additional_internal::referencing_RepoObject_guid
reference.additional_Reference_guid::referencing_RepoObject_guid <-- reference.RepoObjectColumn_reference_additional_internal::referencing_RepoObject_guid
reference.additional_Reference_guid::referencing_RepoObjectColumn_guid <-- reference.RepoObjectColumn_reference_additional_internal::referencing_RepoObjectColumn_guid
reference.additional_Reference_guid::referencing_Schema <-- reference.RepoObject_reference_additional_internal::referencing_schema_name
reference.additional_Reference_guid::referencing_Schema <-- reference.RepoObjectColumn_reference_additional_internal::referencing_schema_name
reference.additional_Reference_guid::referencing_type <-- reference.RepoObject_reference_additional_internal::referencing_type
reference.additional_Reference_guid::referencing_type <-- reference.RepoObjectColumn_reference_additional_internal::referencing_type
repo.RepoObject::RepoObject_fullname <-- reference.additional_Reference_guid::referenced_fullname
repo.RepoObject::RepoObject_fullname <-- reference.additional_Reference_guid::referencing_fullname
repo.RepoObject::RepoObject_guid <-- reference.additional_Reference_guid::referenced_RepoObject_guid
repo.RepoObject::RepoObject_guid <-- reference.additional_Reference_guid::referencing_RepoObject_guid
repo.RepoObject::RepoObject_type <-- reference.additional_Reference_guid::referenced_type
repo.RepoObject::RepoObject_type <-- reference.additional_Reference_guid::referencing_type
repo.RepoObject::SysObject_id <-- reference.additional_Reference_guid::referenced_id
repo.RepoObject::SysObject_id <-- reference.additional_Reference_guid::referencing_id
repo.RepoObjectColumn::RepoObjectColumn_guid <-- reference.additional_Reference_guid::referenced_RepoObjectColumn_guid
repo.RepoObjectColumn::RepoObjectColumn_guid <-- reference.additional_Reference_guid::referencing_RepoObjectColumn_guid
footer
to view a reduced diagram in original size and to be able to click on the links:
open the diagram in a new tab via the Context menu.
end footer

@enduml

