@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:reference.additional_Reference_Object.adoc[]" as reference.additional_Reference_Object << V >> {
  - **AntoraComponent** : (nvarchar(128))
  - **AntoraModule** : (nvarchar(128))
  - **SchemaName** : (nvarchar(128))
  - **ObjectName** : (nvarchar(128))
  --
  --
  --
}

entity "puml-link:dhw:sqldb:reference.additional_Reference_Object_T.adoc[]" as reference.additional_Reference_Object_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
  - AntoraComponent : (nvarchar(128))
  - AntoraModule : (nvarchar(128))
  Description : (nvarchar(max))
  - ObjectName : (nvarchar(128))
  - SchemaName : (nvarchar(128))
  --
  --
}

entity "puml-link:dhw:sqldb:reference.usp_PERSIST_additional_Reference_Object_T.adoc[]" as reference.usp_PERSIST_additional_Reference_Object_T << P >> {
  --
  --
  --
}

entity "puml-link:dhw:sqldb:repo.RepoObject_external_src.adoc[]" as repo.RepoObject_external_src << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
  - external_AntoraComponent : (nvarchar(128))
  - external_AntoraModule : (nvarchar(128))
  - is_external : (int)
  - is_repo_managed : (int)
  - RepoObject_name : (nvarchar(128))
  - RepoObject_schema_name : (nvarchar(128))
  - RepoObject_type : (varchar(1))
  - SysObject_name : (nvarchar(128))
  - SysObject_schema_name : (nvarchar(128))
  - SysObject_type : (varchar(1))
  --
  --
}

entity "puml-link:dhw:sqldb:repo.RepoObjectColumn_external_src.adoc[]" as repo.RepoObjectColumn_external_src << V >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  --
  - is_SysObjectColumn_missing : (int)
  RepoObject_guid : (uniqueidentifier)
  - RepoObjectColumn_name : (nvarchar(128))
  - SysObjectColumn_name : (nvarchar(128))
  --
  --
}

reference.additional_Reference_Object <.. reference.additional_Reference_Object_T
reference.additional_Reference_Object_T <.. reference.usp_PERSIST_additional_Reference_Object_T
reference.additional_Reference_Object_T <.. repo.RepoObject_external_src
reference.additional_Reference_Object_T <.. repo.RepoObjectColumn_external_src
"reference.additional_Reference_Object::AntoraComponent" <-- "reference.additional_Reference_Object_T::AntoraComponent"
"reference.additional_Reference_Object::AntoraModule" <-- "reference.additional_Reference_Object_T::AntoraModule"
"reference.additional_Reference_Object::ObjectName" <-- "reference.additional_Reference_Object_T::ObjectName"
"reference.additional_Reference_Object::SchemaName" <-- "reference.additional_Reference_Object_T::SchemaName"
@enduml

