@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_objectreflist_0_30.adoc[]" as docs.RepoObject_Plantuml_ObjectRefList_0_30 << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
  ObjectRefList : (nvarchar(max))
  --
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_objectreflist_1_1.adoc[]" as docs.RepoObject_Plantuml_ObjectRefList_1_1 << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
  ObjectRefList : (nvarchar(max))
  --
  --
}

entity "puml-link:dhw:sqldb:docs.repoobject_plantuml_objectreflist_30_0.adoc[]" as docs.RepoObject_Plantuml_ObjectRefList_30_0 << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
  ObjectRefList : (nvarchar(max))
  --
  --
}

entity "puml-link:dhw:sqldb:reference.referencetree_cyclic_ref_persistenceusp.adoc[]" as reference.ReferenceTree_cyclic_ref_PersistenceUsp << V >> {
  --
  - referenced_fullname : (nvarchar(261))
  - referenced_fullname2 : (nvarchar(257))
  - Referenced_guid : (uniqueidentifier)
  referenced_type : (char(2))
  - referencing_fullname : (nvarchar(261))
  - referencing_fullname2 : (nvarchar(257))
  - Referencing_guid : (uniqueidentifier)
  referencing_type : (varchar(2))
  --
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_reference.adoc[]" as reference.RepoObject_reference << V >> {
  --
  referenced_entity_name : (nvarchar(128))
  referenced_external_AntoraComponent : (nvarchar(128))
  referenced_external_AntoraModule : (nvarchar(128))
  referenced_is_external : (int)
  referenced_RepoObject_guid : (uniqueidentifier)
  referenced_schema_name : (nvarchar(128))
  referenced_type : (char(2))
  referencing_entity_name : (nvarchar(128))
  referencing_external_AntoraComponent : (nvarchar(128))
  referencing_external_AntoraModule : (nvarchar(128))
  referencing_is_external : (int)
  referencing_RepoObject_guid : (uniqueidentifier)
  referencing_schema_name : (nvarchar(128))
  referencing_type : (varchar(2))
  --
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_reference_t.adoc[]" as reference.RepoObject_reference_T << U >> {
  **referenced_RepoObject_guid** : (uniqueidentifier)
  **referencing_RepoObject_guid** : (uniqueidentifier)
  --
  - is_ReversePersistenceViaView : (bit)
  referenced_entity_name : (nvarchar(128))
  referenced_external_AntoraComponent : (nvarchar(128))
  referenced_external_AntoraModule : (nvarchar(128))
  referenced_is_external : (int)
  - referenced_is_PersistenceSource : (bit)
  - referenced_is_PersistenceTarget : (bit)
  referenced_schema_name : (nvarchar(128))
  referenced_type : (char(2))
  referencing_entity_name : (nvarchar(128))
  referencing_external_AntoraComponent : (nvarchar(128))
  referencing_external_AntoraModule : (nvarchar(128))
  referencing_is_external : (int)
  - referencing_is_PersistenceTarget : (bit)
  - referencing_is_PersistenceUspSourceRef : (bit)
  referencing_is_PersistenceUspTargetRef : (bit)
  referencing_schema_name : (nvarchar(128))
  referencing_type : (varchar(2))
  # referenced_fullname : (nvarchar(261))
  # referenced_fullname2 : (nvarchar(257))
  ~ referenced_puml_entity : (nvarchar(4000))
  # referencing_fullname : (nvarchar(261))
  # referencing_fullname2 : (nvarchar(257))
  ~ referencing_puml_entity : (nvarchar(4000))
  --
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_reference_t_bidirectional.adoc[]" as reference.RepoObject_reference_T_bidirectional << V >> {
  --
  referenced_entity_name : (nvarchar(128))
  - referenced_fullname : (nvarchar(261))
  - referenced_fullname2 : (nvarchar(257))
  referenced_is_persistence : (bit)
  - referenced_RepoObject_guid : (uniqueidentifier)
  referenced_schema_name : (nvarchar(128))
  referenced_source_RepoObject_guid : (uniqueidentifier)
  referenced_type : (char(2))
  referencing_entity_name : (nvarchar(128))
  - referencing_fullname : (nvarchar(261))
  - referencing_fullname2 : (nvarchar(257))
  referencing_is_persistence : (bit)
  - referencing_RepoObject_guid : (uniqueidentifier)
  referencing_schema_name : (nvarchar(128))
  referencing_source_RepoObject_guid : (uniqueidentifier)
  referencing_type : (varchar(2))
  --
  --
}

entity "puml-link:dhw:sqldb:reference.repoobject_referencedreferencing.adoc[]" as reference.RepoObject_ReferencedReferencing << V >> {
  --
  - referenced_AntoraXref : (nvarchar(max))
  referenced_external_AntoraComponent : (nvarchar(128))
  referenced_external_AntoraModule : (nvarchar(128))
  - Referenced_fullname : (nvarchar(261))
  - Referenced_fullname2 : (nvarchar(257))
  - Referenced_guid : (uniqueidentifier)
  referenced_is_DocsOutput : (int)
  - referenced_is_external : (bit)
  Referenced_type : (char(2))
  - referencing_AntoraXref : (nvarchar(max))
  referencing_external_AntoraComponent : (nvarchar(128))
  referencing_external_AntoraModule : (nvarchar(128))
  - Referencing_fullname : (nvarchar(261))
  - Referencing_fullname2 : (nvarchar(257))
  - Referencing_guid : (uniqueidentifier)
  referencing_is_DocsOutput : (int)
  - referencing_is_external : (bit)
  Referencing_type : (varchar(2))
  --
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_reference_additional.adoc[]" as reference.RepoObjectColumn_reference_additional << V >> {
  --
  definition : (nvarchar(max))
  - InformationSource : (varchar(30))
  is_computed : (bit)
  is_referenced_object : (bit)
  is_referencing_object_equal_referenced_object : (bit)
  referenced_column_name : (nvarchar(128))
  - referenced_entity_name : (nvarchar(128))
  referenced_external_AntoraComponent : (nvarchar(128))
  referenced_external_AntoraModule : (nvarchar(128))
  referenced_id : (int)
  referenced_is_external : (bit)
  referenced_RepoObject_guid : (uniqueidentifier)
  referenced_RepoObjectColumn_guid : (uniqueidentifier)
  - referenced_schema_name : (nvarchar(128))
  referenced_type : (char(2))
  referencing_column_name : (nvarchar(128))
  - referencing_entity_name : (nvarchar(128))
  referencing_external_AntoraComponent : (nvarchar(128))
  referencing_external_AntoraModule : (nvarchar(128))
  referencing_id : (int)
  referencing_is_external : (bit)
  referencing_RepoObject_guid : (uniqueidentifier)
  referencing_RepoObjectColumn_guid : (uniqueidentifier)
  - referencing_schema_name : (nvarchar(128))
  referencing_type : (char(2))
  --
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_reference_additional_internal.adoc[]" as reference.RepoObjectColumn_reference_additional_internal << V >> {
  --
  definition : (nvarchar(max))
  - InformationSource : (varchar(30))
  is_computed : (bit)
  is_referenced_object : (bit)
  is_referencing_object_equal_referenced_object : (bit)
  referenced_column_name : (nvarchar(128))
  - referenced_entity_name : (nvarchar(128))
  referenced_id : (int)
  referenced_RepoObject_guid : (uniqueidentifier)
  referenced_RepoObjectColumn_guid : (uniqueidentifier)
  - referenced_schema_name : (nvarchar(128))
  referenced_type : (char(2))
  referencing_column_name : (nvarchar(128))
  - referencing_entity_name : (nvarchar(128))
  referencing_id : (int)
  referencing_RepoObject_guid : (uniqueidentifier)
  referencing_RepoObjectColumn_guid : (uniqueidentifier)
  - referencing_schema_name : (nvarchar(128))
  referencing_type : (char(2))
  --
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_reference_bysamepredecessors.adoc[]" as reference.RepoObjectColumn_reference_BySamePredecessors << V >> {
  --
  definition : (nvarchar(max))
  - InformationSource : (varchar(37))
  is_computed : (bit)
  is_hidden : (bit)
  is_referenced_object : (bit)
  is_referencing_object_equal_referenced_object : (bit)
  referenced_column_name : (nvarchar(128))
  referenced_entity_name : (nvarchar(128))
  referenced_id : (int)
  referenced_minor_id : (int)
  referenced_node_id : (bigint)
  - referenced_RepoObject_guid : (uniqueidentifier)
  referenced_RepoObjectColumn_guid : (uniqueidentifier)
  referenced_schema_name : (nvarchar(128))
  referenced_type : (char(2))
  referencing_column_name : (nvarchar(128))
  - referencing_entity_name : (nvarchar(128))
  referencing_id : (int)
  referencing_minor_id : (int)
  referencing_node_id : (bigint)
  - referencing_RepoObject_guid : (uniqueidentifier)
  referencing_RepoObjectColumn_guid : (uniqueidentifier)
  - referencing_schema_name : (nvarchar(128))
  referencing_type : (char(2))
  --
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_reference_firstresultset.adoc[]" as reference.RepoObjectColumn_reference_FirstResultSet << V >> {
  --
  - InformationSource : (varchar(37))
  is_hidden : (bit)
  is_referenced_object : (bit)
  is_referencing_object_equal_referenced_object : (bit)
  referenced_column_name : (nvarchar(128))
  referenced_entity_name : (nvarchar(128))
  referenced_id : (int)
  referenced_minor_id : (int)
  referenced_node_id : (bigint)
  referenced_RepoObject_guid : (uniqueidentifier)
  referenced_RepoObjectColumn_guid : (uniqueidentifier)
  referenced_schema_name : (nvarchar(128))
  referenced_type : (char(2))
  referencing_column_name : (nvarchar(128))
  - referencing_entity_name : (nvarchar(128))
  referencing_id : (int)
  referencing_minor_id : (int)
  referencing_node_id : (bigint)
  - referencing_RepoObject_guid : (uniqueidentifier)
  referencing_RepoObjectColumn_guid : (uniqueidentifier)
  - referencing_schema_name : (nvarchar(128))
  referencing_type : (char(2))
  --
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_reference_queryplan.adoc[]" as reference.RepoObjectColumn_reference_QueryPlan << V >> {
  **referencing_id** : (int)
  **referencing_minor_id** : (int)
  **referenced_id** : (int)
  **referenced_minor_id** : (int)
  --
  definition : (nvarchar(max))
  - InformationSource : (varchar(10))
  is_computed : (bit)
  is_referenced_object : (bit)
  is_referencing_object_equal_referenced_object : (bit)
  is_source_column_name_expression : (bit)
  is_target_column_name_expression : (bit)
  referenced_column_name : (nvarchar(128))
  referenced_entity_name : (nvarchar(128))
  referenced_node_id : (bigint)
  referenced_RepoObject_guid : (uniqueidentifier)
  referenced_RepoObjectColumn_guid : (uniqueidentifier)
  referenced_schema_name : (nvarchar(128))
  referenced_type : (char(2))
  referencing_column_name : (nvarchar(128))
  - referencing_entity_name : (nvarchar(128))
  referencing_node_id : (bigint)
  - referencing_RepoObject_guid : (uniqueidentifier)
  referencing_RepoObjectColumn_guid : (uniqueidentifier)
  - referencing_schema_name : (nvarchar(128))
  referencing_type : (char(2))
  source_schema_name_quoted : (nvarchar(128))
  source_table_name_quoted : (nvarchar(128))
  --
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_reference_sqlexpressiondependencies.adoc[]" as reference.RepoObjectColumn_reference_SqlExpressionDependencies << V >> {
  - **referencing_id** : (int)
  - **referencing_minor_id** : (int)
  **referenced_id** : (int)
  - **referenced_minor_id** : (int)
  --
  definition : (nvarchar(max))
  - InformationSource : (varchar(31))
  is_computed : (bit)
  is_referenced_object : (bit)
  is_referencing_object_equal_referenced_object : (bit)
  referenced_column_name : (sysname)
  referenced_entity_name : (nvarchar(128))
  referenced_node_id : (bigint)
  referenced_RepoObject_guid : (uniqueidentifier)
  referenced_RepoObjectColumn_guid : (uniqueidentifier)
  referenced_schema_name : (nvarchar(128))
  referenced_type : (char(2))
  referencing_column_name : (sysname)
  referencing_entity_name : (nvarchar(128))
  referencing_node_id : (bigint)
  referencing_RepoObject_guid : (uniqueidentifier)
  referencing_RepoObjectColumn_guid : (uniqueidentifier)
  referencing_schema_name : (nvarchar(128))
  referencing_type : (char(2))
  --
  --
}

entity "puml-link:dhw:sqldb:reference.repoobjectcolumn_reference_virtual.adoc[]" as reference.RepoObjectColumn_reference_virtual << V >> {
  --
  definition : (nvarchar(max))
  - InformationSource : (varchar(34))
  is_computed : (bit)
  is_referenced_object : (bit)
  is_referencing_object_equal_referenced_object : (bit)
  - referenced_column_name : (nvarchar(128))
  - referenced_entity_name : (nvarchar(128))
  referenced_id : (int)
  referenced_minor_id : (int)
  referenced_node_id : (bigint)
  - referenced_RepoObject_guid : (uniqueidentifier)
  - referenced_RepoObjectColumn_guid : (uniqueidentifier)
  - referenced_schema_name : (nvarchar(128))
  referenced_type : (char(2))
  - referencing_column_name : (nvarchar(128))
  - referencing_entity_name : (nvarchar(128))
  referencing_id : (int)
  referencing_minor_id : (int)
  referencing_node_id : (bigint)
  - referencing_RepoObject_guid : (uniqueidentifier)
  - referencing_RepoObjectColumn_guid : (uniqueidentifier)
  - referencing_schema_name : (nvarchar(128))
  referencing_type : (char(2))
  --
  --
}

entity "puml-link:dhw:sqldb:reference.usp_persist_repoobject_reference_t.adoc[]" as reference.usp_PERSIST_RepoObject_reference_T << P >> {
  --
  --
  --
}

entity "puml-link:dhw:sqldb:repo.indexreferencedreferencing.adoc[]" as repo.IndexReferencedReferencing << V >> {
  --
  referenced_index_guid : (uniqueidentifier)
  - referenced_RepoObject_guid : (uniqueidentifier)
  - referencing_RepoObject_guid : (uniqueidentifier)
  RowNumberInReferencing_Target : (int)
  source_index_guid : (uniqueidentifier)
  - source_index_type : (tinyint)
  --
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject_wo_referencing.adoc[]" as repo.RepoObject_wo_referencing << V >> {
  --
  is_repo_managed : (bit)
  - is_RepoObject_name_uniqueidentifier : (int)
  - RepoObject_fullname : (nvarchar(261))
  - RepoObject_fullname2 : (nvarchar(257))
  - RepoObject_guid : (uniqueidentifier)
  - RepoObject_name : (nvarchar(128))
  RepoObject_Referencing_Count : (int)
  - RepoObject_schema_name : (nvarchar(128))
  - RepoObject_type : (char(2))
  --
  --
}

entity "puml-link:dhw:sqldb:repo.usp_main.adoc[]" as repo.usp_main << P >> {
  --
  --
  --
}

reference.RepoObject_reference <.. reference.RepoObject_reference_T
reference.RepoObject_reference_T <.. reference.RepoObjectColumn_reference_SqlExpressionDependencies
reference.RepoObject_reference_T <.. reference.RepoObjectColumn_reference_FirstResultSet
reference.RepoObject_reference_T <.. repo.IndexReferencedReferencing
reference.RepoObject_reference_T <.. reference.RepoObjectColumn_reference_virtual
reference.RepoObject_reference_T <.. reference.usp_PERSIST_RepoObject_reference_T
reference.RepoObject_reference_T <.. docs.RepoObject_Plantuml_ObjectRefList_30_0
reference.RepoObject_reference_T <.. docs.RepoObject_Plantuml_ObjectRefList_0_30
reference.RepoObject_reference_T <.. reference.RepoObject_ReferencedReferencing
reference.RepoObject_reference_T <.. repo.usp_main
reference.RepoObject_reference_T <.. reference.RepoObjectColumn_reference_BySamePredecessors
reference.RepoObject_reference_T <.. reference.RepoObjectColumn_reference_QueryPlan
reference.RepoObject_reference_T <.. reference.RepoObjectColumn_reference_additional_internal
reference.RepoObject_reference_T <.. reference.RepoObjectColumn_reference_additional
reference.RepoObject_reference_T <.. docs.RepoObject_Plantuml_ObjectRefList_1_1
reference.RepoObject_reference_T <.. reference.RepoObject_reference_T_bidirectional
reference.RepoObject_reference_T <.. reference.ReferenceTree_cyclic_ref_PersistenceUsp
reference.RepoObject_reference_T <.. repo.RepoObject_wo_referencing
"reference.RepoObject_reference::referenced_entity_name" <-- "reference.RepoObject_reference_T::referenced_entity_name"
"reference.RepoObject_reference::referenced_external_AntoraComponent" <-- "reference.RepoObject_reference_T::referenced_external_AntoraComponent"
"reference.RepoObject_reference::referenced_external_AntoraModule" <-- "reference.RepoObject_reference_T::referenced_external_AntoraModule"
"reference.RepoObject_reference::referenced_is_external" <-- "reference.RepoObject_reference_T::referenced_is_external"
"reference.RepoObject_reference::referenced_RepoObject_guid" <-- "reference.RepoObject_reference_T::referenced_RepoObject_guid"
"reference.RepoObject_reference::referenced_schema_name" <-- "reference.RepoObject_reference_T::referenced_schema_name"
"reference.RepoObject_reference::referenced_type" <-- "reference.RepoObject_reference_T::referenced_type"
"reference.RepoObject_reference::referencing_entity_name" <-- "reference.RepoObject_reference_T::referencing_entity_name"
"reference.RepoObject_reference::referencing_external_AntoraComponent" <-- "reference.RepoObject_reference_T::referencing_external_AntoraComponent"
"reference.RepoObject_reference::referencing_external_AntoraModule" <-- "reference.RepoObject_reference_T::referencing_external_AntoraModule"
"reference.RepoObject_reference::referencing_is_external" <-- "reference.RepoObject_reference_T::referencing_is_external"
"reference.RepoObject_reference::referencing_RepoObject_guid" <-- "reference.RepoObject_reference_T::referencing_RepoObject_guid"
"reference.RepoObject_reference::referencing_schema_name" <-- "reference.RepoObject_reference_T::referencing_schema_name"
"reference.RepoObject_reference::referencing_type" <-- "reference.RepoObject_reference_T::referencing_type"
"reference.RepoObject_reference_T::referenced_entity_name" <-- "reference.RepoObjectColumn_reference_BySamePredecessors::referenced_entity_name"
"reference.RepoObject_reference_T::referenced_entity_name" <-- "reference.RepoObject_reference_T::referenced_fullname"
"reference.RepoObject_reference_T::referenced_entity_name" <-- "reference.RepoObject_reference_T::referenced_fullname2"
"reference.RepoObject_reference_T::referenced_entity_name" <-- "reference.RepoObject_reference_T_bidirectional::referenced_entity_name"
"reference.RepoObject_reference_T::referenced_entity_name" <-- "reference.RepoObject_reference_T::referenced_puml_entity"
"reference.RepoObject_reference_T::referenced_external_AntoraComponent" <-- "reference.RepoObject_reference_T::referenced_puml_entity"
"reference.RepoObject_reference_T::referenced_external_AntoraComponent" <-- "reference.RepoObject_ReferencedReferencing::referenced_external_AntoraComponent"
"reference.RepoObject_reference_T::referenced_external_AntoraModule" <-- "reference.RepoObject_reference_T::referenced_puml_entity"
"reference.RepoObject_reference_T::referenced_external_AntoraModule" <-- "reference.RepoObject_ReferencedReferencing::referenced_external_AntoraModule"
"reference.RepoObject_reference_T::referenced_fullname" <-- "reference.RepoObject_ReferencedReferencing::Referenced_fullname"
"reference.RepoObject_reference_T::referenced_fullname" <-- "reference.RepoObject_reference_T_bidirectional::referenced_fullname"
"reference.RepoObject_reference_T::referenced_fullname" <-- "reference.ReferenceTree_cyclic_ref_PersistenceUsp::referenced_fullname"
"reference.RepoObject_reference_T::referenced_fullname2" <-- "reference.RepoObject_ReferencedReferencing::Referenced_fullname2"
"reference.RepoObject_reference_T::referenced_fullname2" <-- "reference.RepoObject_reference_T_bidirectional::referenced_fullname2"
"reference.RepoObject_reference_T::referenced_fullname2" <-- "reference.ReferenceTree_cyclic_ref_PersistenceUsp::referenced_fullname2"
"reference.RepoObject_reference_T::referenced_is_external" <-- "reference.RepoObject_reference_T::referenced_puml_entity"
"reference.RepoObject_reference_T::referenced_is_external" <-- "reference.RepoObject_ReferencedReferencing::referenced_is_external"
"reference.RepoObject_reference_T::referenced_RepoObject_guid" <-- "repo.IndexReferencedReferencing::referenced_RepoObject_guid"
"reference.RepoObject_reference_T::referenced_RepoObject_guid" <-- "reference.RepoObjectColumn_reference_BySamePredecessors::referenced_RepoObject_guid"
"reference.RepoObject_reference_T::referenced_RepoObject_guid" <-- "reference.RepoObject_ReferencedReferencing::Referenced_guid"
"reference.RepoObject_reference_T::referenced_RepoObject_guid" <-- "reference.RepoObject_reference_T_bidirectional::referenced_RepoObject_guid"
"reference.RepoObject_reference_T::referenced_RepoObject_guid" <-- "reference.ReferenceTree_cyclic_ref_PersistenceUsp::Referencing_guid"
"reference.RepoObject_reference_T::referenced_schema_name" <-- "reference.RepoObjectColumn_reference_BySamePredecessors::referenced_schema_name"
"reference.RepoObject_reference_T::referenced_schema_name" <-- "reference.RepoObject_reference_T::referenced_fullname"
"reference.RepoObject_reference_T::referenced_schema_name" <-- "reference.RepoObject_reference_T::referenced_fullname2"
"reference.RepoObject_reference_T::referenced_schema_name" <-- "reference.RepoObject_reference_T_bidirectional::referenced_schema_name"
"reference.RepoObject_reference_T::referenced_schema_name" <-- "reference.RepoObject_reference_T::referenced_puml_entity"
"reference.RepoObject_reference_T::referenced_type" <-- "reference.RepoObjectColumn_reference_BySamePredecessors::referenced_type"
"reference.RepoObject_reference_T::referenced_type" <-- "reference.RepoObject_ReferencedReferencing::Referenced_type"
"reference.RepoObject_reference_T::referenced_type" <-- "reference.RepoObject_reference_T_bidirectional::referenced_type"
"reference.RepoObject_reference_T::referenced_type" <-- "reference.ReferenceTree_cyclic_ref_PersistenceUsp::referenced_type"
"reference.RepoObject_reference_T::referencing_entity_name" <-- "reference.RepoObject_reference_T::referencing_fullname"
"reference.RepoObject_reference_T::referencing_entity_name" <-- "reference.RepoObject_reference_T::referencing_fullname2"
"reference.RepoObject_reference_T::referencing_entity_name" <-- "reference.RepoObject_reference_T_bidirectional::referencing_entity_name"
"reference.RepoObject_reference_T::referencing_entity_name" <-- "reference.RepoObject_reference_T::referencing_puml_entity"
"reference.RepoObject_reference_T::referencing_external_AntoraComponent" <-- "reference.RepoObject_reference_T::referencing_puml_entity"
"reference.RepoObject_reference_T::referencing_external_AntoraComponent" <-- "reference.RepoObject_ReferencedReferencing::referencing_external_AntoraComponent"
"reference.RepoObject_reference_T::referencing_external_AntoraModule" <-- "reference.RepoObject_reference_T::referencing_puml_entity"
"reference.RepoObject_reference_T::referencing_external_AntoraModule" <-- "reference.RepoObject_ReferencedReferencing::referencing_external_AntoraModule"
"reference.RepoObject_reference_T::referencing_fullname" <-- "reference.RepoObject_ReferencedReferencing::Referencing_fullname"
"reference.RepoObject_reference_T::referencing_fullname" <-- "reference.RepoObject_reference_T_bidirectional::referencing_fullname"
"reference.RepoObject_reference_T::referencing_fullname" <-- "reference.ReferenceTree_cyclic_ref_PersistenceUsp::referencing_fullname"
"reference.RepoObject_reference_T::referencing_fullname2" <-- "reference.RepoObject_ReferencedReferencing::Referencing_fullname2"
"reference.RepoObject_reference_T::referencing_fullname2" <-- "reference.RepoObject_reference_T_bidirectional::referencing_fullname2"
"reference.RepoObject_reference_T::referencing_fullname2" <-- "reference.ReferenceTree_cyclic_ref_PersistenceUsp::referencing_fullname2"
"reference.RepoObject_reference_T::referencing_is_external" <-- "reference.RepoObject_reference_T::referencing_puml_entity"
"reference.RepoObject_reference_T::referencing_is_external" <-- "reference.RepoObject_ReferencedReferencing::referencing_is_external"
"reference.RepoObject_reference_T::referencing_RepoObject_guid" <-- "repo.IndexReferencedReferencing::referencing_RepoObject_guid"
"reference.RepoObject_reference_T::referencing_RepoObject_guid" <-- "reference.RepoObject_ReferencedReferencing::Referencing_guid"
"reference.RepoObject_reference_T::referencing_RepoObject_guid" <-- "reference.RepoObject_reference_T_bidirectional::referencing_RepoObject_guid"
"reference.RepoObject_reference_T::referencing_RepoObject_guid" <-- "reference.ReferenceTree_cyclic_ref_PersistenceUsp::Referenced_guid"
"reference.RepoObject_reference_T::referencing_schema_name" <-- "reference.RepoObject_reference_T::referencing_fullname"
"reference.RepoObject_reference_T::referencing_schema_name" <-- "reference.RepoObject_reference_T::referencing_fullname2"
"reference.RepoObject_reference_T::referencing_schema_name" <-- "reference.RepoObject_reference_T_bidirectional::referencing_schema_name"
"reference.RepoObject_reference_T::referencing_schema_name" <-- "reference.RepoObject_reference_T::referencing_puml_entity"
"reference.RepoObject_reference_T::referencing_type" <-- "reference.RepoObject_ReferencedReferencing::Referencing_type"
"reference.RepoObject_reference_T::referencing_type" <-- "reference.RepoObject_reference_T_bidirectional::referencing_type"
"reference.RepoObject_reference_T::referencing_type" <-- "reference.ReferenceTree_cyclic_ref_PersistenceUsp::referencing_type"
@enduml

