@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:config.fs_get_parameter_value.adoc[]" as config.fs_get_parameter_value << FN >> {
  --
  --
  --
}

entity "puml-link:dhw:sqldb:logs.usp_executionlog_insert.adoc[]" as logs.usp_ExecutionLog_insert << P >> {
  --
  --
  --
}

entity "puml-link:dhw:sqldb:repo.reposchema.adoc[]" as repo.RepoSchema << U >> {
  - **RepoSchema_guid** : (uniqueidentifier)
  --
  - is_ssas : (bit)
  is_SysSchema_missing : (bit)
  - MeasuresRepoObjekt_guid : (uniqueidentifier)
  RepoSchema_ms_description : (nvarchar(4000))
  - RepoSchema_name : (nvarchar(128))
  SysSchema_id : (int)
  - SysSchema_name : (nvarchar(128))
  ~ has_different_sys_names : (bit)
  # is_RepoSchema_name_uniqueidentifier : (int)
  # is_SysSchema_name_uniqueidentifier : (int)
  # MeasuresRepoObjekt_name : (varchar(9))
  --
  --
}

entity "puml-link:dhw:sqldb:repo.sysschema_reposchema_via_guid.adoc[]" as repo.SysSchema_RepoSchema_via_guid << V >> {
  --
  is_RepoSchema_name_uniqueidentifier : (int)
  is_SysSchema_name_uniqueidentifier : (int)
  RepoSchema_guid : (uniqueidentifier)
  RepoSchema_is_SysSchema_missing : (bit)
  RepoSchema_name : (nvarchar(128))
  RepoSchema_SysSchema_id : (int)
  RepoSchema_SysSchema_name : (nvarchar(128))
  - SysSchema_id : (int)
  - SysSchema_name : (sysname)
  SysSchema_RepoSchema_guid : (uniqueidentifier)
  --
  --
}

entity "puml-link:dhw:sqldb:repo.sysschema_reposchema_via_name.adoc[]" as repo.SysSchema_RepoSchema_via_name << V >> {
  --
  is_RepoSchema_name_uniqueidentifier : (int)
  is_SysSchema_name_uniqueidentifier : (int)
  RepoSchema_guid : (uniqueidentifier)
  RepoSchema_is_SysSchema_missing : (bit)
  RepoSchema_name : (nvarchar(128))
  RepoSchema_SysSchema_id : (int)
  RepoSchema_SysSchema_name : (nvarchar(128))
  - SysSchema_id : (int)
  - SysSchema_name : (sysname)
  SysSchema_RepoSchema_guid : (uniqueidentifier)
  --
  --
}

entity "puml-link:dhw:sqldb:repo.usp_sync_guid.adoc[]" as repo.usp_sync_guid << P >> {
  --
  --
  --
}

entity "puml-link:dhw:sqldb:repo.usp_sync_guid_reposchema.adoc[]" as repo.usp_sync_guid_RepoSchema << P >> {
  --
  --
  --
}

entity "puml-link:dhw:sqldb:repo_sys.sysschema.adoc[]" as repo_sys.SysSchema << V >> {
  --
  - SysSchema_id : (int)
  - SysSchema_name : (sysname)
  SysSchema_principal_id : (int)
  SysSchema_RepoSchema_guid : (uniqueidentifier)
  --
  --
}

entity "puml-link:dhw:sqldb:repo_sys.usp_addorupdateextendedproperty.adoc[]" as repo_sys.usp_AddOrUpdateExtendedProperty << P >> {
  --
  --
  --
}

config.fs_get_parameter_value <.. repo.usp_sync_guid_RepoSchema
logs.usp_ExecutionLog_insert <.. repo.usp_sync_guid_RepoSchema
repo.RepoSchema <.. repo.usp_sync_guid_RepoSchema
repo.SysSchema_RepoSchema_via_guid <.. repo.usp_sync_guid_RepoSchema
repo.SysSchema_RepoSchema_via_name <.. repo.usp_sync_guid_RepoSchema
repo.usp_sync_guid_RepoSchema <.. repo.usp_sync_guid
repo_sys.SysSchema <.. repo.usp_sync_guid_RepoSchema
repo_sys.usp_AddOrUpdateExtendedProperty <.. repo.usp_sync_guid_RepoSchema

@enduml

