@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:configT.SsasDmv_ExplicitDataType.adoc[]" as configT.SsasDmv_ExplicitDataType << V >> {
  --
  - ExplicitDataType : (int)
  - ExplicitDataTypeName : (varchar(34))
  --
  --
}

entity "puml-link:dhw:sqldb:repo.ForeignKey_ssas_Indexes_old.adoc[]" as repo.ForeignKey_ssas_Indexes_old << V >> {
  --
  delete_referential_action : (tinyint)
  ForeignKey_fullname : (nvarchar(517))
  - ForeignKey_guid : (uniqueidentifier)
  ForeignKey_name : (nvarchar(max))
  - is_MatchingDatatypePattern : (int)
  referenced_index_guid : (uniqueidentifier)
  referenced_index_name : (nvarchar(450))
  referenced_IndexPatternColumnDatatype : (varchar(34))
  referenced_IndexPatternColumnName : (nvarchar(max))
  referenced_RepoObject_fullname : (nvarchar(517))
  referenced_RepoObject_fullname2 : (nvarchar(max))
  referenced_RepoObject_guid : (uniqueidentifier)
  referenced_SysObject_name : (nvarchar(max))
  - referenced_SysObject_schema_name : (nvarchar(128))
  referencing_index_guid : (uniqueidentifier)
  referencing_index_name : (nvarchar(450))
  referencing_IndexPatternColumnDatatype : (varchar(34))
  referencing_IndexPatternColumnName : (nvarchar(max))
  referencing_RepoObject_fullname : (nvarchar(517))
  referencing_RepoObject_fullname2 : (nvarchar(max))
  referencing_RepoObject_guid : (uniqueidentifier)
  referencing_SysObject_name : (nvarchar(max))
  - referencing_SysObject_schema_name : (nvarchar(128))
  update_referential_action : (tinyint)
  --
  --
}

entity "puml-link:dhw:sqldb:repo.ForeignKey_ssas_IndexPattern_old.adoc[]" as repo.ForeignKey_ssas_IndexPattern_old << V >> {
  --
  - CrossFilteringBehavior : (bigint)
  - databasename : (nvarchar(128))
  delete_referential_action : (tinyint)
  ForeignKey_fullname : (nvarchar(517))
  - ForeignKey_guid : (uniqueidentifier)
  ForeignKey_name : (nvarchar(max))
  - ForeignKey_orignalName : (nvarchar(max))
  - FromCardinality : (bigint)
  - IsActive : (bit)
  - JoinOnDateBehavior : (bigint)
  referenced_ColumnName : (nvarchar(max))
  referenced_IndexPatternColumnDatatype : (varchar(34))
  referenced_IndexPatternColumnGuid : (varchar(36))
  referenced_IndexPatternColumnName : (nvarchar(max))
  referenced_IsKey : (bit)
  referenced_IsNullable : (bit)
  referenced_ObjectName : (nvarchar(max))
  referenced_RepoObject_fullname : (nvarchar(517))
  referenced_RepoObject_fullname2 : (nvarchar(max))
  referenced_RepoObject_guid : (uniqueidentifier)
  referencing_ColumnName : (nvarchar(max))
  referencing_IndexPatternColumnDatatype : (varchar(34))
  referencing_IndexPatternColumnGuid : (varchar(36))
  referencing_IndexPatternColumnName : (nvarchar(max))
  referencing_IsKey : (bit)
  referencing_IsNullable : (bit)
  referencing_ObjectName : (nvarchar(max))
  referencing_RepoObject_fullname : (nvarchar(517))
  referencing_RepoObject_fullname2 : (nvarchar(max))
  referencing_RepoObject_guid : (uniqueidentifier)
  - RelyOnReferentialIntegrity : (bit)
  - SecurityFilteringBehavior : (bigint)
  - ToCardinality : (bigint)
  - Type : (bigint)
  update_referential_action : (tinyint)
  --
  --
}

entity "puml-link:dhw:sqldb:ssas.TMSCHEMA_COLUMNS_T.adoc[]" as ssas.TMSCHEMA_COLUMNS_T << U >> {
  - **databasename** : (nvarchar(128))
  - **ID** : (numeric(20, 0))
  --
  - Alignment : (bigint)
  - AttributeHierarchyID : (numeric(20, 0))
  ColumnOriginID : (numeric(20, 0))
  - ColumnStorageID : (numeric(20, 0))
  DataCategory : (nvarchar(max))
  Description : (nvarchar(max))
  DisplayFolder : (nvarchar(max))
  - DisplayOrdinal : (int)
  ErrorMessage : (nvarchar(max))
  - ExplicitDataType : (bigint)
  - ExplicitName : (nvarchar(max))
  Expression : (nvarchar(max))
  FormatString : (nvarchar(max))
  - InferredDataType : (bigint)
  InferredName : (nvarchar(max))
  - IsAvailableInMDX : (bit)
  - IsDefaultImage : (bit)
  - IsDefaultLabel : (bit)
  - IsHidden : (bit)
  - IsKey : (bit)
  - IsNullable : (bit)
  - IsUnique : (bit)
  - KeepUniqueRows : (bit)
  - ModifiedTime : (datetime)
  RefreshedTime : (nvarchar(max))
  - RepoObjectColumn_guid : (uniqueidentifier)
  SortByColumnID : (numeric(20, 0))
  SourceColumn : (nvarchar(max))
  SourceProviderType : (nvarchar(max))
  - State : (bigint)
  - StructureModifiedTime : (datetime)
  - SummarizeBy : (bigint)
  - SystemFlags : (bigint)
  - TableDetailPosition : (int)
  - TableID : (numeric(20, 0))
  - Type : (bigint)
  --
  --
}

entity "puml-link:dhw:sqldb:ssas.TMSCHEMA_RELATIONSHIPS_T.adoc[]" as ssas.TMSCHEMA_RELATIONSHIPS_T << U >> {
  - **databasename** : (nvarchar(128))
  - **ID** : (numeric(20, 0))
  --
  - CrossFilteringBehavior : (bigint)
  - ForeignKey_guid : (uniqueidentifier)
  - FromCardinality : (bigint)
  - FromColumnID : (numeric(20, 0))
  - FromTableID : (numeric(20, 0))
  - IsActive : (bit)
  - JoinOnDateBehavior : (bigint)
  - ModelID : (numeric(20, 0))
  - ModifiedTime : (datetime)
  - Name : (nvarchar(max))
  RefreshedTime : (datetime)
  RelationshipStorage2ID : (numeric(20, 0))
  RelationshipStorageID : (numeric(20, 0))
  - RelyOnReferentialIntegrity : (bit)
  - SecurityFilteringBehavior : (bigint)
  - State : (bigint)
  - ToCardinality : (bigint)
  - ToColumnID : (numeric(20, 0))
  - ToTableID : (numeric(20, 0))
  - Type : (bigint)
  --
  --
}

entity "puml-link:dhw:sqldb:ssas.TMSCHEMA_TABLES_T.adoc[]" as ssas.TMSCHEMA_TABLES_T << U >> {
  - **databasename** : (nvarchar(128))
  - **ID** : (numeric(20, 0))
  --
  DataCategory : (nvarchar(max))
  DefaultDetailRowsDefinitionID : (numeric(20, 0))
  Description : (nvarchar(max))
  - IsHidden : (bit)
  - IsPrivate : (bit)
  - ModelID : (numeric(20, 0))
  - ModifiedTime : (datetime)
  - Name : (nvarchar(max))
  - RepoObject_guid : (uniqueidentifier)
  - ShowAsVariationsOnly : (bit)
  - StructureModifiedTime : (datetime)
  - SystemFlags : (bigint)
  - TableStorageID : (numeric(20, 0))
  --
  --
}

configT.SsasDmv_ExplicitDataType <.. repo.ForeignKey_ssas_IndexPattern_old
repo.ForeignKey_ssas_IndexPattern_old <.. repo.ForeignKey_ssas_Indexes_old
ssas.TMSCHEMA_COLUMNS_T <.. repo.ForeignKey_ssas_IndexPattern_old
ssas.TMSCHEMA_RELATIONSHIPS_T <.. repo.ForeignKey_ssas_IndexPattern_old
ssas.TMSCHEMA_TABLES_T <.. repo.ForeignKey_ssas_IndexPattern_old
"configT.SsasDmv_ExplicitDataType::ExplicitDataTypeName" <-- "repo.ForeignKey_ssas_IndexPattern_old::referenced_IndexPatternColumnDatatype"
"configT.SsasDmv_ExplicitDataType::ExplicitDataTypeName" <-- "repo.ForeignKey_ssas_IndexPattern_old::referencing_IndexPatternColumnDatatype"
"repo.ForeignKey_ssas_IndexPattern_old::databasename" <-- "repo.ForeignKey_ssas_Indexes_old::referenced_SysObject_schema_name"
"repo.ForeignKey_ssas_IndexPattern_old::databasename" <-- "repo.ForeignKey_ssas_Indexes_old::referencing_SysObject_schema_name"
"repo.ForeignKey_ssas_IndexPattern_old::delete_referential_action" <-- "repo.ForeignKey_ssas_Indexes_old::delete_referential_action"
"repo.ForeignKey_ssas_IndexPattern_old::ForeignKey_fullname" <-- "repo.ForeignKey_ssas_Indexes_old::ForeignKey_fullname"
"repo.ForeignKey_ssas_IndexPattern_old::ForeignKey_guid" <-- "repo.ForeignKey_ssas_Indexes_old::ForeignKey_guid"
"repo.ForeignKey_ssas_IndexPattern_old::ForeignKey_name" <-- "repo.ForeignKey_ssas_Indexes_old::ForeignKey_name"
"repo.ForeignKey_ssas_IndexPattern_old::referenced_IndexPatternColumnDatatype" <-- "repo.ForeignKey_ssas_Indexes_old::referenced_IndexPatternColumnDatatype"
"repo.ForeignKey_ssas_IndexPattern_old::referenced_IndexPatternColumnName" <-- "repo.ForeignKey_ssas_Indexes_old::referenced_IndexPatternColumnName"
"repo.ForeignKey_ssas_IndexPattern_old::referenced_ObjectName" <-- "repo.ForeignKey_ssas_Indexes_old::referenced_SysObject_name"
"repo.ForeignKey_ssas_IndexPattern_old::referenced_RepoObject_fullname" <-- "repo.ForeignKey_ssas_Indexes_old::referenced_RepoObject_fullname"
"repo.ForeignKey_ssas_IndexPattern_old::referenced_RepoObject_fullname2" <-- "repo.ForeignKey_ssas_Indexes_old::referenced_RepoObject_fullname2"
"repo.ForeignKey_ssas_IndexPattern_old::referenced_RepoObject_guid" <-- "repo.ForeignKey_ssas_Indexes_old::referenced_RepoObject_guid"
"repo.ForeignKey_ssas_IndexPattern_old::referencing_IndexPatternColumnDatatype" <-- "repo.ForeignKey_ssas_Indexes_old::referencing_IndexPatternColumnDatatype"
"repo.ForeignKey_ssas_IndexPattern_old::referencing_IndexPatternColumnName" <-- "repo.ForeignKey_ssas_Indexes_old::referencing_IndexPatternColumnName"
"repo.ForeignKey_ssas_IndexPattern_old::referencing_ObjectName" <-- "repo.ForeignKey_ssas_Indexes_old::referencing_SysObject_name"
"repo.ForeignKey_ssas_IndexPattern_old::referencing_RepoObject_fullname" <-- "repo.ForeignKey_ssas_Indexes_old::referencing_RepoObject_fullname"
"repo.ForeignKey_ssas_IndexPattern_old::referencing_RepoObject_fullname2" <-- "repo.ForeignKey_ssas_Indexes_old::referencing_RepoObject_fullname2"
"repo.ForeignKey_ssas_IndexPattern_old::referencing_RepoObject_guid" <-- "repo.ForeignKey_ssas_Indexes_old::referencing_RepoObject_guid"
"repo.ForeignKey_ssas_IndexPattern_old::update_referential_action" <-- "repo.ForeignKey_ssas_Indexes_old::update_referential_action"
"ssas.TMSCHEMA_COLUMNS_T::ExplicitName" <-- "repo.ForeignKey_ssas_IndexPattern_old::referenced_IndexPatternColumnName"
"ssas.TMSCHEMA_COLUMNS_T::ExplicitName" <-- "repo.ForeignKey_ssas_IndexPattern_old::referencing_IndexPatternColumnName"
"ssas.TMSCHEMA_COLUMNS_T::ExplicitName" <-- "repo.ForeignKey_ssas_IndexPattern_old::referenced_ColumnName"
"ssas.TMSCHEMA_COLUMNS_T::ExplicitName" <-- "repo.ForeignKey_ssas_IndexPattern_old::referencing_ColumnName"
"ssas.TMSCHEMA_COLUMNS_T::IsKey" <-- "repo.ForeignKey_ssas_IndexPattern_old::referenced_IsKey"
"ssas.TMSCHEMA_COLUMNS_T::IsKey" <-- "repo.ForeignKey_ssas_IndexPattern_old::referencing_IsKey"
"ssas.TMSCHEMA_COLUMNS_T::IsNullable" <-- "repo.ForeignKey_ssas_IndexPattern_old::referenced_IsNullable"
"ssas.TMSCHEMA_COLUMNS_T::IsNullable" <-- "repo.ForeignKey_ssas_IndexPattern_old::referencing_IsNullable"
"ssas.TMSCHEMA_RELATIONSHIPS_T::CrossFilteringBehavior" <-- "repo.ForeignKey_ssas_IndexPattern_old::CrossFilteringBehavior"
"ssas.TMSCHEMA_RELATIONSHIPS_T::databasename" <-- "repo.ForeignKey_ssas_IndexPattern_old::databasename"
"ssas.TMSCHEMA_RELATIONSHIPS_T::ForeignKey_guid" <-- "repo.ForeignKey_ssas_IndexPattern_old::ForeignKey_guid"
"ssas.TMSCHEMA_RELATIONSHIPS_T::FromCardinality" <-- "repo.ForeignKey_ssas_IndexPattern_old::FromCardinality"
"ssas.TMSCHEMA_RELATIONSHIPS_T::IsActive" <-- "repo.ForeignKey_ssas_IndexPattern_old::IsActive"
"ssas.TMSCHEMA_RELATIONSHIPS_T::JoinOnDateBehavior" <-- "repo.ForeignKey_ssas_IndexPattern_old::JoinOnDateBehavior"
"ssas.TMSCHEMA_RELATIONSHIPS_T::Name" <-- "repo.ForeignKey_ssas_IndexPattern_old::ForeignKey_orignalName"
"ssas.TMSCHEMA_RELATIONSHIPS_T::RelyOnReferentialIntegrity" <-- "repo.ForeignKey_ssas_IndexPattern_old::RelyOnReferentialIntegrity"
"ssas.TMSCHEMA_RELATIONSHIPS_T::SecurityFilteringBehavior" <-- "repo.ForeignKey_ssas_IndexPattern_old::SecurityFilteringBehavior"
"ssas.TMSCHEMA_RELATIONSHIPS_T::ToCardinality" <-- "repo.ForeignKey_ssas_IndexPattern_old::ToCardinality"
"ssas.TMSCHEMA_RELATIONSHIPS_T::Type" <-- "repo.ForeignKey_ssas_IndexPattern_old::Type"
"ssas.TMSCHEMA_TABLES_T::Name" <-- "repo.ForeignKey_ssas_IndexPattern_old::referenced_ObjectName"
"ssas.TMSCHEMA_TABLES_T::Name" <-- "repo.ForeignKey_ssas_IndexPattern_old::referencing_ObjectName"
"ssas.TMSCHEMA_TABLES_T::RepoObject_guid" <-- "repo.ForeignKey_ssas_IndexPattern_old::referenced_RepoObject_guid"
"ssas.TMSCHEMA_TABLES_T::RepoObject_guid" <-- "repo.ForeignKey_ssas_IndexPattern_old::referencing_RepoObject_guid"
@enduml

