@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity "puml-link:docs.AntoraIndexSemanticgroupPatterndatatype.adoc[prefix=..]" as docs.AntoraIndexSemanticgroupPatterndatatype << V >> {
  **IndexSemanticGroup** : (nvarchar(512))
  **IndexPatternColumnDatatype** : (nvarchar(4000))
  --
  AntoraIndexSemanticgroupPatterndatatype : (nvarchar(max))
  --
  --
}

entity "puml-link:docs.RepoObject_IndexList.adoc[prefix=..]" as docs.RepoObject_IndexList << V >> {
  **RepoObject_guid** : (uniqueidentifier)
  --
  AntoraIndexList : (nvarchar(max))
  PumlIndexList : (nvarchar(max))
  --
  --
}

entity "puml-link:repo.ForeignKey_gross.adoc[prefix=..]" as repo.ForeignKey_gross << V >> {
  **ForeignKey_guid** : (uniqueidentifier)
  --
  delete_referential_action : (tinyint)
  ForeignKey_fullname : (nvarchar(517))
  ForeignKey_name : (nvarchar(128))
  - is_MatchingDatatypePattern : (int)
  - referenced_AntoraXref : (nvarchar(4000))
  referenced_index_guid : (uniqueidentifier)
  referenced_index_name : (nvarchar(450))
  referenced_IndexPatternColumnDatatype : (nvarchar(4000))
  referenced_IndexPatternColumnName : (nvarchar(4000))
  referenced_RepoObject_fullname : (nvarchar(261))
  referenced_RepoObject_fullname2 : (nvarchar(257))
  referenced_RepoObject_guid : (uniqueidentifier)
  referenced_SysObject_name : (nvarchar(128))
  referenced_SysObject_schema_name : (nvarchar(128))
  referencing_index_guid : (uniqueidentifier)
  referencing_index_name : (nvarchar(450))
  referencing_IndexPatternColumnDatatype : (nvarchar(4000))
  referencing_IndexPatternColumnName : (nvarchar(4000))
  referencing_RepoObject_fullname : (nvarchar(261))
  referencing_RepoObject_fullname2 : (nvarchar(257))
  referencing_RepoObject_guid : (uniqueidentifier)
  referencing_SysObject_name : (nvarchar(128))
  referencing_SysObject_schema_name : (nvarchar(128))
  update_referential_action : (tinyint)
  --
  --
}

entity "puml-link:repo.ForeignKey_Indexes.adoc[prefix=..]" as repo.ForeignKey_Indexes << V >> {
  **ForeignKey_guid** : (uniqueidentifier)
  --
  delete_referential_action : (tinyint)
  ForeignKey_fullname : (nvarchar(261))
  ForeignKey_name : (sysname)
  - is_MatchingDatatypePattern : (int)
  referenced_index_guid : (uniqueidentifier)
  referenced_index_name : (nvarchar(450))
  referenced_IndexPatternColumnDatatype : (nvarchar(4000))
  referenced_IndexPatternColumnName : (nvarchar(4000))
  referenced_RepoObject_fullname : (nvarchar(261))
  referenced_RepoObject_fullname2 : (nvarchar(257))
  referenced_RepoObject_guid : (uniqueidentifier)
  referenced_SysObject_name : (nvarchar(128))
  referenced_SysObject_schema_name : (nvarchar(128))
  referencing_index_guid : (uniqueidentifier)
  referencing_index_name : (nvarchar(450))
  referencing_IndexPatternColumnDatatype : (nvarchar(4000))
  referencing_IndexPatternColumnName : (nvarchar(4000))
  referencing_RepoObject_fullname : (nvarchar(261))
  referencing_RepoObject_fullname2 : (nvarchar(257))
  referencing_RepoObject_guid : (uniqueidentifier)
  referencing_SysObject_name : (nvarchar(128))
  referencing_SysObject_schema_name : (nvarchar(128))
  update_referential_action : (tinyint)
  --
  --
}

entity "puml-link:repo.ForeignKey_virtual_Indexes.adoc[prefix=..]" as repo.ForeignKey_virtual_Indexes << V >> {
  - **ForeignKey_guid** : (uniqueidentifier)
  --
  - delete_referential_action : (tinyint)
  - ForeignKey_fullname : (nvarchar(517))
  ForeignKey_name : (nvarchar(128))
  - is_MatchingDatatypePattern : (int)
  referenced_index_guid : (uniqueidentifier)
  referenced_index_name : (nvarchar(450))
  referenced_IndexPatternColumnDatatype : (nvarchar(4000))
  referenced_IndexPatternColumnName : (nvarchar(4000))
  referenced_RepoObject_fullname : (nvarchar(261))
  referenced_RepoObject_fullname2 : (nvarchar(257))
  referenced_RepoObject_guid : (uniqueidentifier)
  referenced_SysObject_name : (nvarchar(128))
  referenced_SysObject_schema_name : (nvarchar(128))
  referencing_index_guid : (uniqueidentifier)
  referencing_index_name : (nvarchar(450))
  referencing_IndexPatternColumnDatatype : (nvarchar(4000))
  referencing_IndexPatternColumnName : (nvarchar(4000))
  referencing_RepoObject_fullname : (nvarchar(261))
  referencing_RepoObject_fullname2 : (nvarchar(257))
  referencing_RepoObject_guid : (uniqueidentifier)
  referencing_SysObject_name : (nvarchar(128))
  referencing_SysObject_schema_name : (nvarchar(128))
  - update_referential_action : (tinyint)
  --
  --
}

entity "puml-link:repo.Index_ColumList_T.adoc[prefix=..]" as repo.Index_ColumList_T << U >> {
  - **index_guid** : (uniqueidentifier)
  --
  AntoraIndexColumnList : (nvarchar(max))
  ColumnList : (nvarchar(max))
  ConstraintColumnList : (nvarchar(max))
  DbmlIndexColumnList : (nvarchar(max))
  PersistenceWhereColumnList : (nvarchar(max))
  PumlIndexColumnList : (nvarchar(max))
  --
  --
}

entity "puml-link:repo.Index_gross.adoc[prefix=..]" as repo.Index_gross << V >> {
  - **index_guid** : (uniqueidentifier)
  --
  AntoraIndexColumnList : (nvarchar(max))
  ColumnList : (nvarchar(max))
  ConstraintColumnList : (nvarchar(max))
  DbmlIndexColumnList : (nvarchar(max))
  index_name : (nvarchar(450))
  index_type : (tinyint)
  IndexPatternColumnDatatype : (nvarchar(4000))
  IndexPatternColumnName : (nvarchar(4000))
  IndexSemanticGroup : (nvarchar(512))
  is_index_disabled : (bit)
  is_index_primary_key : (bit)
  is_index_real : (bit)
  is_index_unique : (bit)
  is_persistence : (bit)
  is_repo_managed : (bit)
  parent_RepoObject_guid : (uniqueidentifier)
  PersistenceWhereColumnList : (nvarchar(max))
  PumlIndexColumnList : (nvarchar(max))
  referenced_index_guid : (uniqueidentifier)
  - RepoObject_fullname : (nvarchar(261))
  - RepoObject_fullname2 : (nvarchar(257))
  RowNumber_PatternPerParentObject : (bigint)
  RowNumber_PkPerParentObject : (bigint)
  - SysObject_fullname : (nvarchar(261))
  - SysObject_fullname2 : (nvarchar(257))
  SysObject_id : (int)
  - SysObject_name : (nvarchar(128))
  - SysObject_schema_name : (nvarchar(128))
  SysObject_type : (char(2))
  --
  --
}

entity "puml-link:repo.Index_Settings.adoc[prefix=..]" as repo.Index_Settings << U >> {
  - **index_guid** : (uniqueidentifier)
  --
  IndexPatternColumnDatatype : (nvarchar(4000))
  IndexPatternColumnName : (nvarchar(4000))
  IndexSemanticGroup : (nvarchar(512))
  - is_create_constraint : (bit)
  --
  --
}

entity "puml-link:repo.Index_union.adoc[prefix=..]" as repo.Index_union << V >> {
  **index_guid** : (uniqueidentifier)
  --
  index_name : (nvarchar(450))
  index_type : (tinyint)
  IndexPatternColumnGuid : (varchar(8000))
  is_index_disabled : (bit)
  is_index_primary_key : (bit)
  is_index_real : (bit)
  is_index_unique : (bit)
  parent_RepoObject_guid : (uniqueidentifier)
  referenced_index_guid : (uniqueidentifier)
  --
  --
}

entity "puml-link:repo.RepoObject_gross.adoc[prefix=..]" as repo.RepoObject_gross << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
  Description : (nvarchar(max))
  has_different_sys_names : (bit)
  has_execution_plan_issue : (bit)
  has_get_referenced_issue : (bit)
  has_history : (bit)
  has_history_columns : (bit)
  history_schema_name : (nvarchar(128))
  history_table_name : (nvarchar(128))
  Inheritance_StringAggSeparatorSql : (nvarchar(4000))
  InheritanceDefinition : (nvarchar(4000))
  InheritanceType : (tinyint)
  - is_DocsExclude : (bit)
  is_DocsOutput : (int)
  - is_in_reference : (int)
  is_persistence : (bit)
  is_persistence_check_duplicate_per_pk : (bit)
  is_persistence_check_for_empty_source : (bit)
  is_persistence_delete_changed : (bit)
  is_persistence_delete_missing : (bit)
  is_persistence_insert : (bit)
  is_persistence_merge_delete_missing : (bit)
  is_persistence_merge_insert : (bit)
  is_persistence_merge_update_changed : (bit)
  is_persistence_truncate : (bit)
  is_persistence_update_changed : (bit)
  is_repo_managed : (bit)
  - is_RepoObject_name_uniqueidentifier : (int)
  is_required_ObjectMerge : (bit)
  - is_ssas : (bit)
  is_SysObject_missing : (bit)
  - is_SysObject_name_uniqueidentifier : (int)
  - modify_dt : (datetime)
  node_id : (bigint)
  persistence_source_RepoObject_fullname : (nvarchar(261))
  persistence_source_RepoObject_fullname2 : (nvarchar(257))
  persistence_source_RepoObject_guid : (uniqueidentifier)
  persistence_source_RepoObject_xref : (nvarchar(269))
  persistence_source_SysObject_fullname : (nvarchar(261))
  persistence_source_SysObject_fullname2 : (nvarchar(257))
  persistence_source_SysObject_xref : (nvarchar(269))
  pk_index_guid : (uniqueidentifier)
  pk_IndexPatternColumnDatatype : (nvarchar(4000))
  pk_IndexPatternColumnName : (nvarchar(4000))
  pk_IndexPatternColumnName_new : (nvarchar(4000))
  pk_IndexSemanticGroup : (nvarchar(512))
  Property_ms_description : (nvarchar(4000))
  Repo_history_table_guid : (uniqueidentifier)
  Repo_temporal_type : (tinyint)
  - RepoObject_fullname : (nvarchar(261))
  - RepoObject_fullname2 : (nvarchar(257))
  - RepoObject_name : (nvarchar(128))
  RepoObject_Referencing_Count : (int)
  - RepoObject_schema_name : (nvarchar(128))
  - RepoObject_type : (char(2))
  RepoObject_type_name : (nvarchar(128))
  source_filter : (nvarchar(4000))
  - SysObject_fullname : (nvarchar(261))
  - SysObject_fullname2 : (nvarchar(257))
  SysObject_id : (int)
  SysObject_modify_date : (datetime)
  - SysObject_name : (nvarchar(128))
  - SysObject_parent_object_id : (int)
  SysObject_query_executed_dt : (datetime)
  SysObject_query_plan : (xml)
  - SysObject_query_sql : (nvarchar(406))
  - SysObject_schema_name : (nvarchar(128))
  SysObject_type : (char(2))
  SysObject_type_name : (nvarchar(128))
  tables_dataCategory : (nvarchar(500))
  tables_description : (nvarchar(max))
  tables_isHidden : (nvarchar(500))
  target_filter : (nvarchar(4000))
  temporal_type : (tinyint)
  - usp_persistence_name : (nvarchar(140))
  usp_persistence_RepoObject_guid : (uniqueidentifier)
  --
  --
}

entity "puml-link:repo.RepoObject_SqlCreateTable.adoc[prefix=..]" as repo.RepoObject_SqlCreateTable << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
  ConList : (nvarchar(max))
  - DbmlTable : (nvarchar(max))
  persistence_source_RepoObject_fullname : (nvarchar(261))
  persistence_source_RepoObject_guid : (uniqueidentifier)
  persistence_source_SysObject_fullname : (nvarchar(261))
  - RepoObject_fullname : (nvarchar(261))
  - SqlCreateTable : (nvarchar(max))
  --
  --
}

entity "puml-link:repo.usp_Index_finish.adoc[prefix=..]" as repo.usp_Index_finish << P >> {
  --
  --
  --
}

entity "puml-link:repo.usp_index_inheritance.adoc[prefix=..]" as repo.usp_index_inheritance << P >> {
  --
  --
  --
}

entity "puml-link:repo.usp_Index_virtual_set.adoc[prefix=..]" as repo.usp_Index_virtual_set << P >> {
  --
  --
  --
}

repo.Index_ColumList_T <.. repo.Index_gross
repo.Index_gross <.. repo.usp_Index_virtual_set
repo.Index_gross <.. repo.RepoObject_SqlCreateTable
repo.Index_gross <.. repo.usp_index_inheritance
repo.Index_gross <.. repo.ForeignKey_Indexes
repo.Index_gross <.. repo.ForeignKey_virtual_Indexes
repo.Index_gross <.. repo.usp_Index_finish
repo.Index_gross <.. docs.RepoObject_IndexList
repo.Index_gross <.. docs.AntoraIndexSemanticgroupPatterndatatype
repo.Index_gross <.. repo.ForeignKey_gross
repo.Index_Settings <.. repo.Index_gross
repo.Index_union <.. repo.Index_gross
repo.RepoObject_gross <.. repo.Index_gross
repo.Index_ColumList_T::AntoraIndexColumnList <-- repo.Index_gross::AntoraIndexColumnList
repo.Index_ColumList_T::ColumnList <-- repo.Index_gross::ColumnList
repo.Index_ColumList_T::ConstraintColumnList <-- repo.Index_gross::ConstraintColumnList
repo.Index_ColumList_T::DbmlIndexColumnList <-- repo.Index_gross::DbmlIndexColumnList
repo.Index_ColumList_T::PersistenceWhereColumnList <-- repo.Index_gross::PersistenceWhereColumnList
repo.Index_ColumList_T::PumlIndexColumnList <-- repo.Index_gross::PumlIndexColumnList
repo.Index_gross::index_guid <-- repo.ForeignKey_Indexes::referenced_index_guid
repo.Index_gross::index_guid <-- repo.ForeignKey_Indexes::referencing_index_guid
repo.Index_gross::index_name <-- repo.ForeignKey_gross::referenced_index_name
repo.Index_gross::index_name <-- repo.ForeignKey_gross::referencing_index_name
repo.Index_gross::index_name <-- repo.ForeignKey_Indexes::referenced_index_name
repo.Index_gross::index_name <-- repo.ForeignKey_Indexes::referencing_index_name
repo.Index_gross::index_name <-- repo.ForeignKey_virtual_Indexes::referenced_index_name
repo.Index_gross::index_name <-- repo.ForeignKey_virtual_Indexes::referencing_index_name
repo.Index_gross::IndexPatternColumnDatatype <-- repo.ForeignKey_Indexes::referenced_IndexPatternColumnDatatype
repo.Index_gross::IndexPatternColumnDatatype <-- repo.ForeignKey_Indexes::referencing_IndexPatternColumnDatatype
repo.Index_gross::IndexPatternColumnDatatype <-- repo.ForeignKey_virtual_Indexes::referenced_IndexPatternColumnDatatype
repo.Index_gross::IndexPatternColumnDatatype <-- repo.ForeignKey_virtual_Indexes::referencing_IndexPatternColumnDatatype
repo.Index_gross::IndexPatternColumnDatatype <-- docs.AntoraIndexSemanticgroupPatterndatatype::IndexPatternColumnDatatype
repo.Index_gross::IndexPatternColumnName <-- repo.ForeignKey_virtual_Indexes::referenced_IndexPatternColumnName
repo.Index_gross::IndexPatternColumnName <-- repo.ForeignKey_virtual_Indexes::referencing_IndexPatternColumnName
repo.Index_gross::IndexSemanticGroup <-- docs.AntoraIndexSemanticgroupPatterndatatype::IndexSemanticGroup
repo.Index_gross::parent_RepoObject_guid <-- repo.ForeignKey_virtual_Indexes::referenced_RepoObject_guid
repo.Index_gross::parent_RepoObject_guid <-- repo.ForeignKey_virtual_Indexes::referencing_RepoObject_guid
repo.Index_gross::parent_RepoObject_guid <-- docs.RepoObject_IndexList::RepoObject_guid
repo.Index_gross::RepoObject_fullname <-- repo.ForeignKey_Indexes::referenced_RepoObject_fullname
repo.Index_gross::RepoObject_fullname <-- repo.ForeignKey_Indexes::referencing_RepoObject_fullname
repo.Index_gross::RepoObject_fullname <-- repo.ForeignKey_virtual_Indexes::referenced_RepoObject_fullname
repo.Index_gross::RepoObject_fullname <-- repo.ForeignKey_virtual_Indexes::referencing_RepoObject_fullname
repo.Index_gross::RepoObject_fullname2 <-- repo.ForeignKey_Indexes::referenced_RepoObject_fullname2
repo.Index_gross::RepoObject_fullname2 <-- repo.ForeignKey_Indexes::referencing_RepoObject_fullname2
repo.Index_gross::RepoObject_fullname2 <-- repo.ForeignKey_virtual_Indexes::referenced_RepoObject_fullname2
repo.Index_gross::RepoObject_fullname2 <-- repo.ForeignKey_virtual_Indexes::referencing_RepoObject_fullname2
repo.Index_gross::SysObject_name <-- repo.ForeignKey_Indexes::referenced_SysObject_name
repo.Index_gross::SysObject_name <-- repo.ForeignKey_Indexes::referencing_SysObject_name
repo.Index_gross::SysObject_name <-- repo.ForeignKey_virtual_Indexes::referenced_SysObject_name
repo.Index_gross::SysObject_name <-- repo.ForeignKey_virtual_Indexes::referencing_SysObject_name
repo.Index_gross::SysObject_schema_name <-- repo.ForeignKey_Indexes::referenced_SysObject_schema_name
repo.Index_gross::SysObject_schema_name <-- repo.ForeignKey_Indexes::referencing_SysObject_schema_name
repo.Index_gross::SysObject_schema_name <-- repo.ForeignKey_virtual_Indexes::referenced_SysObject_schema_name
repo.Index_gross::SysObject_schema_name <-- repo.ForeignKey_virtual_Indexes::referencing_SysObject_schema_name
repo.Index_Settings::index_guid <-- repo.Index_gross::index_guid
repo.Index_Settings::IndexPatternColumnDatatype <-- repo.Index_gross::IndexPatternColumnDatatype
repo.Index_Settings::IndexPatternColumnName <-- repo.Index_gross::IndexPatternColumnName
repo.Index_Settings::IndexSemanticGroup <-- repo.Index_gross::IndexSemanticGroup
repo.Index_union::index_name <-- repo.Index_gross::index_name
repo.Index_union::index_type <-- repo.Index_gross::index_type
repo.Index_union::is_index_disabled <-- repo.Index_gross::is_index_disabled
repo.Index_union::is_index_primary_key <-- repo.Index_gross::is_index_primary_key
repo.Index_union::is_index_real <-- repo.Index_gross::is_index_real
repo.Index_union::is_index_unique <-- repo.Index_gross::is_index_unique
repo.Index_union::parent_RepoObject_guid <-- repo.Index_gross::parent_RepoObject_guid
repo.Index_union::referenced_index_guid <-- repo.Index_gross::referenced_index_guid
repo.RepoObject_gross::is_persistence <-- repo.Index_gross::is_persistence
repo.RepoObject_gross::is_repo_managed <-- repo.Index_gross::is_repo_managed
repo.RepoObject_gross::RepoObject_fullname <-- repo.Index_gross::RepoObject_fullname
repo.RepoObject_gross::RepoObject_fullname2 <-- repo.Index_gross::RepoObject_fullname2
repo.RepoObject_gross::SysObject_fullname <-- repo.Index_gross::SysObject_fullname
repo.RepoObject_gross::SysObject_fullname2 <-- repo.Index_gross::SysObject_fullname2
repo.RepoObject_gross::SysObject_id <-- repo.Index_gross::SysObject_id
repo.RepoObject_gross::SysObject_name <-- repo.Index_gross::SysObject_name
repo.RepoObject_gross::SysObject_schema_name <-- repo.Index_gross::SysObject_schema_name
repo.RepoObject_gross::SysObject_type <-- repo.Index_gross::SysObject_type
footer
to view a reduced diagram in original size and to be able to click on the links:
open the diagram in a new tab via the Context menu.
end footer

@enduml

