@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:repo.repoobject_ssas_tgt.adoc[]" as repo.RepoObject_SSAS_tgt << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  external_AntoraComponent : (nvarchar(128))
  external_AntoraModule : (nvarchar(128))
  has_execution_plan_issue : (bit)
  has_get_referenced_issue : (bit)
  Inheritance_StringAggSeparatorSql : (nvarchar(4000))
  InheritanceDefinition : (nvarchar(4000))
  InheritanceType : (tinyint)
  is_external : (bit)
  - is_repo_managed : (int)
  is_required_ObjectMerge : (bit)
  - is_ssas : (int)
  is_SysObject_missing : (bit)
  - modify_dt : (datetime)
  pk_index_guid : (uniqueidentifier)
  pk_IndexPatternColumnName_new : (nvarchar(4000))
  Repo_history_table_guid : (uniqueidentifier)
  Repo_temporal_type : (tinyint)
  - RepoObject_name : (nvarchar(128))
  RepoObject_Referencing_Count : (int)
  - RepoObject_schema_name : (nvarchar(128))
  - RepoObject_type : (varchar(1))
  SysObject_id : (int)
  - SysObject_modify_date : (datetime)
  - SysObject_name : (nvarchar(128))
  - SysObject_parent_object_id : (int)
  - SysObject_schema_name : (nvarchar(128))
  - SysObject_type : (varchar(1))
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn.adoc[]" as repo.RepoObjectColumn << U >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  Inheritance_StringAggSeparatorSql : (nvarchar(4000))
  InheritanceDefinition : (nvarchar(4000))
  InheritanceType : (tinyint)
  is_persistence_no_check : (bit)
  is_persistence_no_include : (bit)
  is_persistence_no_update : (bit)
  is_query_plan_expression : (bit)
  is_required_ColumnMerge : (bit)
  is_SysObjectColumn_missing : (bit)
  persistence_source_RepoObjectColumn_guid : (uniqueidentifier)
  Referencing_Count : (int)
  Repo_default_definition : (nvarchar(max))
  Repo_default_is_system_named : (bit)
  Repo_default_name : (nvarchar(128))
  Repo_definition : (nvarchar(max))
  - Repo_generated_always_type : (tinyint)
  Repo_graph_type : (int)
  Repo_increment_value : (sql_variant)
  - Repo_is_computed : (bit)
  - Repo_is_identity : (bit)
  Repo_is_nullable : (bit)
  Repo_is_persisted : (bit)
  Repo_seed_value : (sql_variant)
  Repo_user_type_fullname : (nvarchar(128))
  Repo_user_type_name : (nvarchar(128))
  Repo_uses_database_collation : (bit)
  - RepoObject_guid : (uniqueidentifier)
  RepoObjectColumn_column_id : (int)
  - RepoObjectColumn_name : (nvarchar(128))
  SysObjectColumn_column_id : (int)
  - SysObjectColumn_name : (nvarchar(128))
  # Column_name : (nvarchar(128))
  ~ has_different_sys_names : (bit)
  # is_RepoObjectColumn_name_uniqueidentifier : (int)
  # is_SysObjectColumn_name_uniqueidentifier : (int)
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn_ssas_src.adoc[]" as repo.RepoObjectColumn_SSAS_src << V >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  - is_SysObjectColumn_missing : (int)
  - Repo_is_nullable : (bit)
  Repo_user_type_fullname : (nvarchar(500))
  Repo_user_type_name : (nvarchar(500))
  - RepoObject_guid : (uniqueidentifier)
  - RepoObjectColumn_name : (nvarchar(128))
  - SysObjectColumn_name : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:repo.repoobjectcolumn_ssas_tgt.adoc[]" as repo.RepoObjectColumn_SSAS_tgt << V >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  Inheritance_StringAggSeparatorSql : (nvarchar(4000))
  InheritanceDefinition : (nvarchar(4000))
  InheritanceType : (tinyint)
  is_persistence_no_check : (bit)
  is_persistence_no_include : (bit)
  is_persistence_no_update : (bit)
  is_query_plan_expression : (bit)
  is_required_ColumnMerge : (bit)
  - is_SysObjectColumn_missing : (int)
  persistence_source_RepoObjectColumn_guid : (uniqueidentifier)
  Referencing_Count : (int)
  Repo_default_definition : (nvarchar(max))
  Repo_default_is_system_named : (bit)
  Repo_default_name : (nvarchar(128))
  Repo_definition : (nvarchar(max))
  - Repo_generated_always_type : (tinyint)
  Repo_graph_type : (int)
  Repo_increment_value : (sql_variant)
  - Repo_is_computed : (bit)
  - Repo_is_identity : (bit)
  - Repo_is_nullable : (bit)
  Repo_is_persisted : (bit)
  Repo_seed_value : (sql_variant)
  Repo_user_type_fullname : (nvarchar(500))
  Repo_user_type_name : (nvarchar(500))
  Repo_uses_database_collation : (bit)
  - RepoObject_guid : (uniqueidentifier)
  RepoObjectColumn_column_id : (int)
  - RepoObjectColumn_name : (nvarchar(128))
  SysObjectColumn_column_id : (int)
  - SysObjectColumn_name : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:repo.usp_persist_repoobjectcolumn_ssas_tgt.adoc[]" as repo.usp_PERSIST_RepoObjectColumn_SSAS_tgt << P >> {
  --
}

repo.RepoObject_SSAS_tgt <.. repo.RepoObjectColumn_SSAS_tgt
repo.RepoObjectColumn <.. repo.RepoObjectColumn_SSAS_tgt
repo.RepoObjectColumn_SSAS_src <.. repo.RepoObjectColumn_SSAS_tgt
repo.RepoObjectColumn_SSAS_tgt <.. repo.RepoObjectColumn
repo.RepoObjectColumn_SSAS_tgt <.. repo.RepoObject_SSAS_tgt
repo.RepoObjectColumn_SSAS_tgt <.. repo.usp_PERSIST_RepoObjectColumn_SSAS_tgt
"repo.RepoObjectColumn::Inheritance_StringAggSeparatorSql" <-- "repo.RepoObjectColumn_SSAS_tgt::Inheritance_StringAggSeparatorSql"
"repo.RepoObjectColumn::InheritanceDefinition" <-- "repo.RepoObjectColumn_SSAS_tgt::InheritanceDefinition"
"repo.RepoObjectColumn::InheritanceType" <-- "repo.RepoObjectColumn_SSAS_tgt::InheritanceType"
"repo.RepoObjectColumn::is_persistence_no_check" <-- "repo.RepoObjectColumn_SSAS_tgt::is_persistence_no_check"
"repo.RepoObjectColumn::is_persistence_no_include" <-- "repo.RepoObjectColumn_SSAS_tgt::is_persistence_no_include"
"repo.RepoObjectColumn::is_persistence_no_update" <-- "repo.RepoObjectColumn_SSAS_tgt::is_persistence_no_update"
"repo.RepoObjectColumn::is_query_plan_expression" <-- "repo.RepoObjectColumn_SSAS_tgt::is_query_plan_expression"
"repo.RepoObjectColumn::is_required_ColumnMerge" <-- "repo.RepoObjectColumn_SSAS_tgt::is_required_ColumnMerge"
"repo.RepoObjectColumn::is_SysObjectColumn_missing" <-- "repo.RepoObjectColumn_SSAS_tgt::is_SysObjectColumn_missing"
"repo.RepoObjectColumn::persistence_source_RepoObjectColumn_guid" <-- "repo.RepoObjectColumn_SSAS_tgt::persistence_source_RepoObjectColumn_guid"
"repo.RepoObjectColumn::Referencing_Count" <-- "repo.RepoObjectColumn_SSAS_tgt::Referencing_Count"
"repo.RepoObjectColumn::Repo_default_definition" <-- "repo.RepoObjectColumn_SSAS_tgt::Repo_default_definition"
"repo.RepoObjectColumn::Repo_default_is_system_named" <-- "repo.RepoObjectColumn_SSAS_tgt::Repo_default_is_system_named"
"repo.RepoObjectColumn::Repo_default_name" <-- "repo.RepoObjectColumn_SSAS_tgt::Repo_default_name"
"repo.RepoObjectColumn::Repo_definition" <-- "repo.RepoObjectColumn_SSAS_tgt::Repo_definition"
"repo.RepoObjectColumn::Repo_generated_always_type" <-- "repo.RepoObjectColumn_SSAS_tgt::Repo_generated_always_type"
"repo.RepoObjectColumn::Repo_graph_type" <-- "repo.RepoObjectColumn_SSAS_tgt::Repo_graph_type"
"repo.RepoObjectColumn::Repo_increment_value" <-- "repo.RepoObjectColumn_SSAS_tgt::Repo_increment_value"
"repo.RepoObjectColumn::Repo_is_computed" <-- "repo.RepoObjectColumn_SSAS_tgt::Repo_is_computed"
"repo.RepoObjectColumn::Repo_is_identity" <-- "repo.RepoObjectColumn_SSAS_tgt::Repo_is_identity"
"repo.RepoObjectColumn::Repo_is_nullable" <-- "repo.RepoObjectColumn_SSAS_tgt::Repo_is_nullable"
"repo.RepoObjectColumn::Repo_is_persisted" <-- "repo.RepoObjectColumn_SSAS_tgt::Repo_is_persisted"
"repo.RepoObjectColumn::Repo_seed_value" <-- "repo.RepoObjectColumn_SSAS_tgt::Repo_seed_value"
"repo.RepoObjectColumn::Repo_user_type_fullname" <-- "repo.RepoObjectColumn_SSAS_tgt::Repo_user_type_fullname"
"repo.RepoObjectColumn::Repo_user_type_name" <-- "repo.RepoObjectColumn_SSAS_tgt::Repo_user_type_name"
"repo.RepoObjectColumn::Repo_uses_database_collation" <-- "repo.RepoObjectColumn_SSAS_tgt::Repo_uses_database_collation"
"repo.RepoObjectColumn::RepoObject_guid" <-- "repo.RepoObjectColumn_SSAS_tgt::RepoObject_guid"
"repo.RepoObjectColumn::RepoObjectColumn_column_id" <-- "repo.RepoObjectColumn_SSAS_tgt::RepoObjectColumn_column_id"
"repo.RepoObjectColumn::RepoObjectColumn_guid" <-- "repo.RepoObjectColumn_SSAS_tgt::RepoObjectColumn_guid"
"repo.RepoObjectColumn::RepoObjectColumn_name" <-- "repo.RepoObjectColumn_SSAS_tgt::RepoObjectColumn_name"
"repo.RepoObjectColumn::SysObjectColumn_column_id" <-- "repo.RepoObjectColumn_SSAS_tgt::SysObjectColumn_column_id"
"repo.RepoObjectColumn::SysObjectColumn_name" <-- "repo.RepoObjectColumn_SSAS_tgt::SysObjectColumn_name"
"repo.RepoObjectColumn_SSAS_src::is_SysObjectColumn_missing" <-- "repo.RepoObjectColumn_SSAS_tgt::is_SysObjectColumn_missing"
"repo.RepoObjectColumn_SSAS_src::Repo_is_nullable" <-- "repo.RepoObjectColumn_SSAS_tgt::Repo_is_nullable"
"repo.RepoObjectColumn_SSAS_src::Repo_user_type_fullname" <-- "repo.RepoObjectColumn_SSAS_tgt::Repo_user_type_fullname"
"repo.RepoObjectColumn_SSAS_src::Repo_user_type_name" <-- "repo.RepoObjectColumn_SSAS_tgt::Repo_user_type_name"
"repo.RepoObjectColumn_SSAS_src::RepoObject_guid" <-- "repo.RepoObjectColumn_SSAS_tgt::RepoObject_guid"
"repo.RepoObjectColumn_SSAS_src::RepoObjectColumn_guid" <-- "repo.RepoObjectColumn_SSAS_tgt::RepoObjectColumn_guid"
"repo.RepoObjectColumn_SSAS_src::RepoObjectColumn_name" <-- "repo.RepoObjectColumn_SSAS_tgt::RepoObjectColumn_name"
"repo.RepoObjectColumn_SSAS_src::SysObjectColumn_name" <-- "repo.RepoObjectColumn_SSAS_tgt::SysObjectColumn_name"footer The diagram is interactive and contains links.
@enduml

