@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity "puml-link:docs.Unit_1_union.adoc[prefix=..]" as docs.Unit_1_union << V >> {
  --
  Object_fullname2 : (nvarchar(257))
  Object_Type : (varchar(2))
  Unit_Description : (nvarchar(max))
  Unit_DisplayFolder : (nvarchar(500))
  Unit_Expression : (nvarchar(max))
  Unit_FormatString : (nvarchar(500))
  - Unit_fullname2 : (nvarchar(638))
  - Unit_guid : (uniqueidentifier)
  Unit_isHidden : (bit)
  Unit_IsKey : (bit)
  Unit_IsSsas : (bit)
  Unit_IsUnique : (bit)
  - Unit_Metatype : (varchar(7))
  - Unit_Name : (nvarchar(500))
  - Unit_Schema : (nvarchar(128))
  Unit_SummarizeBy : (nvarchar(500))
  Unit_TypeName : (nvarchar(128))
  --
  --
}

entity "puml-link:graph.RepoObjectColumn_S.adoc[prefix=..]" as graph.RepoObjectColumn_S << V >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  --
  - RepoObject_fullname : (nvarchar(261))
  RepoObject_fullname2 : (nvarchar(257))
  - RepoObject_guid : (uniqueidentifier)
  - RepoObject_type : (char(2))
  - RepoObjectColumn_fullname : (nvarchar(520))
  RepoObjectColumn_fullname2 : (nvarchar(386))
  - RepoObjectColumn_name : (nvarchar(128))
  RepoObjectColumn_type : (nvarchar(128))
  --
  --
}

entity "puml-link:property.fs_get_RepoObjectColumnProperty_nvarchar.adoc[prefix=..]" as property.fs_get_RepoObjectColumnProperty_nvarchar << FN >> {
  --
  --
  --
}

entity "puml-link:property.RepoObjectColumnProperty_ForUpdate.adoc[prefix=..]" as property.RepoObjectColumnProperty_ForUpdate << V >> {
  - **RepoObjectColumnProperty_id** : (int)
  --
  inheritance : (tinyint)
  - property_name : (nvarchar(128))
  - property_value : (nvarchar(max))
  Repo_user_type_fullname : (nvarchar(128))
  - RepoObject_fullname : (nvarchar(261))
  - RepoObject_fullname2 : (nvarchar(257))
  - RepoObject_guid : (uniqueidentifier)
  - RepoObject_name : (nvarchar(128))
  - RepoObject_schema_name : (nvarchar(128))
  - RepoObject_type : (char(2))
  - RepoObjectColumn_fullname : (nvarchar(520))
  - RepoObjectColumn_fullname2 : (nvarchar(386))
  - RepoObjectColumn_guid : (uniqueidentifier)
  - RepoObjectColumn_name : (nvarchar(128))
  --
  --
}

entity "puml-link:reference.RepoObjectColumn_reference_FirstResultSet.adoc[prefix=..]" as reference.RepoObjectColumn_reference_FirstResultSet << V >> {
  --
  - InformationSource : (varchar(37))
  is_hidden : (bit)
  is_referenced_object : (bit)
  is_referencing_object_equal_referenced_object : (bit)
  referenced_column_name : (nvarchar(128))
  referenced_entity_name : (nvarchar(128))
  referenced_id : (int)
  referenced_minor_id : (int)
  referenced_node_id : (bigint)
  referenced_RepoObject_guid : (uniqueidentifier)
  referenced_RepoObjectColumn_guid : (uniqueidentifier)
  referenced_schema_name : (nvarchar(128))
  referenced_type : (char(2))
  referencing_column_name : (nvarchar(128))
  - referencing_entity_name : (nvarchar(128))
  referencing_id : (int)
  referencing_minor_id : (int)
  referencing_node_id : (bigint)
  - referencing_RepoObject_guid : (uniqueidentifier)
  referencing_RepoObjectColumn_guid : (uniqueidentifier)
  - referencing_schema_name : (nvarchar(128))
  referencing_type : (char(2))
  --
  --
}

entity "puml-link:reference.RepoObjectColumn_reference_QueryPlan.adoc[prefix=..]" as reference.RepoObjectColumn_reference_QueryPlan << V >> {
  **referencing_id** : (int)
  **referencing_minor_id** : (int)
  **referenced_id** : (int)
  **referenced_minor_id** : (int)
  --
  definition : (nvarchar(max))
  - InformationSource : (varchar(10))
  is_computed : (bit)
  is_referenced_object : (bit)
  is_referencing_object_equal_referenced_object : (bit)
  is_source_column_name_expression : (bit)
  is_target_column_name_expression : (bit)
  referenced_column_name : (nvarchar(128))
  referenced_entity_name : (nvarchar(128))
  referenced_node_id : (bigint)
  referenced_RepoObject_guid : (uniqueidentifier)
  referenced_RepoObjectColumn_guid : (uniqueidentifier)
  referenced_schema_name : (nvarchar(128))
  referenced_type : (char(2))
  referencing_column_name : (nvarchar(128))
  - referencing_entity_name : (nvarchar(128))
  referencing_node_id : (bigint)
  - referencing_RepoObject_guid : (uniqueidentifier)
  referencing_RepoObjectColumn_guid : (uniqueidentifier)
  - referencing_schema_name : (nvarchar(128))
  referencing_type : (char(2))
  source_schema_name_quoted : (nvarchar(128))
  source_table_name_quoted : (nvarchar(128))
  --
  --
}

entity "puml-link:reference.RepoObjectColumn_reference_virtual.adoc[prefix=..]" as reference.RepoObjectColumn_reference_virtual << V >> {
  --
  definition : (nvarchar(max))
  - InformationSource : (varchar(34))
  is_computed : (bit)
  is_referenced_object : (bit)
  is_referencing_object_equal_referenced_object : (bit)
  - referenced_column_name : (nvarchar(128))
  - referenced_entity_name : (nvarchar(128))
  referenced_id : (int)
  referenced_minor_id : (int)
  referenced_node_id : (bigint)
  - referenced_RepoObject_guid : (uniqueidentifier)
  - referenced_RepoObjectColumn_guid : (uniqueidentifier)
  - referenced_schema_name : (nvarchar(128))
  referenced_type : (char(2))
  - referencing_column_name : (nvarchar(128))
  - referencing_entity_name : (nvarchar(128))
  referencing_id : (int)
  referencing_minor_id : (int)
  referencing_node_id : (bigint)
  - referencing_RepoObject_guid : (uniqueidentifier)
  - referencing_RepoObjectColumn_guid : (uniqueidentifier)
  - referencing_schema_name : (nvarchar(128))
  referencing_type : (char(2))
  --
  --
}

entity "puml-link:reference.usp_RepoObjectColumnSource_virtual_set.adoc[prefix=..]" as reference.usp_RepoObjectColumnSource_virtual_set << P >> {
  --
  --
  --
}

entity "puml-link:repo.RepoObject.adoc[prefix=..]" as repo.RepoObject << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
  has_execution_plan_issue : (bit)
  has_get_referenced_issue : (bit)
  Inheritance_StringAggSeparatorSql : (nvarchar(4000))
  InheritanceDefinition : (nvarchar(4000))
  InheritanceType : (tinyint)
  - is_DocsExclude : (bit)
  is_repo_managed : (bit)
  is_required_ObjectMerge : (bit)
  - is_ssas : (bit)
  is_SysObject_missing : (bit)
  - modify_dt : (datetime)
  pk_index_guid : (uniqueidentifier)
  pk_IndexPatternColumnName_new : (nvarchar(4000))
  Repo_history_table_guid : (uniqueidentifier)
  Repo_temporal_type : (tinyint)
  - RepoObject_name : (nvarchar(128))
  RepoObject_Referencing_Count : (int)
  - RepoObject_schema_name : (nvarchar(128))
  - RepoObject_type : (char(2))
  SysObject_id : (int)
  SysObject_modify_date : (datetime)
  - SysObject_name : (nvarchar(128))
  - SysObject_parent_object_id : (int)
  - SysObject_schema_name : (nvarchar(128))
  SysObject_type : (char(2))
  ~ has_different_sys_names : (bit)
  # is_RepoObject_name_uniqueidentifier : (int)
  # is_SysObject_name_uniqueidentifier : (int)
  ~ node_id : (bigint)
  # RepoObject_fullname : (nvarchar(261))
  # RepoObject_fullname2 : (nvarchar(257))
  # SysObject_fullname : (nvarchar(261))
  # SysObject_fullname2 : (nvarchar(257))
  ~ SysObject_query_sql : (nvarchar(406))
  # usp_persistence_fullname2 : (nvarchar(269))
  # usp_persistence_name : (nvarchar(140))
  --
  --
}

entity "puml-link:repo.RepoObject_persistence.adoc[prefix=..]" as repo.RepoObject_persistence << U >> {
  - **target_RepoObject_guid** : (uniqueidentifier)
  --
  - has_history : (bit)
  - has_history_columns : (bit)
  history_schema_name : (nvarchar(128))
  history_table_name : (nvarchar(128))
  - is_persistence_check_duplicate_per_pk : (bit)
  - is_persistence_check_for_empty_source : (bit)
  - is_persistence_delete_changed : (bit)
  - is_persistence_delete_missing : (bit)
  - is_persistence_insert : (bit)
  - is_persistence_merge_delete_missing : (bit)
  - is_persistence_merge_insert : (bit)
  - is_persistence_merge_update_changed : (bit)
  - is_persistence_truncate : (bit)
  - is_persistence_update_changed : (bit)
  source_filter : (nvarchar(4000))
  source_RepoObject_guid : (uniqueidentifier)
  source_RepoObject_name : (nvarchar(128))
  target_filter : (nvarchar(4000))
  ~ is_persistence : (bit)
  ~ temporal_type : (tinyint)
  --
  --
}

entity "puml-link:repo.RepoObjectColumn.adoc[prefix=..]" as repo.RepoObjectColumn << U >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  --
  Inheritance_StringAggSeparatorSql : (nvarchar(4000))
  InheritanceDefinition : (nvarchar(4000))
  InheritanceType : (tinyint)
  is_persistence_no_check : (bit)
  is_persistence_no_include : (bit)
  is_persistence_no_update : (bit)
  is_query_plan_expression : (bit)
  is_required_ColumnMerge : (bit)
  is_SysObjectColumn_missing : (bit)
  persistence_source_RepoObjectColumn_guid : (uniqueidentifier)
  Referencing_Count : (int)
  Repo_default_definition : (nvarchar(max))
  Repo_default_is_system_named : (bit)
  Repo_default_name : (nvarchar(128))
  Repo_definition : (nvarchar(max))
  - Repo_generated_always_type : (tinyint)
  Repo_graph_type : (int)
  Repo_increment_value : (sql_variant)
  - Repo_is_computed : (bit)
  - Repo_is_identity : (bit)
  Repo_is_nullable : (bit)
  Repo_is_persisted : (bit)
  Repo_seed_value : (sql_variant)
  Repo_user_type_fullname : (nvarchar(128))
  Repo_user_type_name : (nvarchar(128))
  Repo_uses_database_collation : (bit)
  - RepoObject_guid : (uniqueidentifier)
  RepoObjectColumn_column_id : (int)
  - RepoObjectColumn_name : (nvarchar(128))
  SysObjectColumn_column_id : (int)
  - SysObjectColumn_name : (nvarchar(128))
  # Column_name : (nvarchar(128))
  ~ has_different_sys_names : (bit)
  # is_RepoObjectColumn_name_uniqueidentifier : (int)
  # is_SysObjectColumn_name_uniqueidentifier : (int)
  --
  --
}

entity "puml-link:repo.RepoObjectColumn_gross.adoc[prefix=..]" as repo.RepoObjectColumn_gross << V >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  --
  - Column_name : (nvarchar(128))
  Description : (nvarchar(max))
  has_different_sys_names : (bit)
  has_get_referenced_issue : (bit)
  Inheritance_StringAggSeparatorSql : (nvarchar(4000))
  InheritanceDefinition : (nvarchar(4000))
  InheritanceType : (tinyint)
  is_persistence_no_check : (bit)
  is_persistence_no_include : (bit)
  is_persistence_no_update : (bit)
  is_query_plan_expression : (bit)
  is_repo_managed : (bit)
  - is_RepoObject_name_uniqueidentifier : (int)
  - is_RepoObjectColumn_name_uniqueidentifier : (int)
  is_required_ColumnMerge : (bit)
  - is_ssas : (bit)
  is_SysObject_missing : (bit)
  - is_SysObject_name_uniqueidentifier : (int)
  is_SysObjectColumn_missing : (bit)
  - is_SysObjectColumn_name_uniqueidentifier : (int)
  - modify_dt : (datetime)
  node_id : (bigint)
  persistence_source_RepoObject_guid : (uniqueidentifier)
  persistence_source_RepoObjectColumn_guid : (uniqueidentifier)
  pk_index_guid : (uniqueidentifier)
  Property_ms_description : (nvarchar(4000))
  Referencing_Count : (int)
  Repo_default_definition : (nvarchar(max))
  Repo_default_is_system_named : (bit)
  Repo_default_name : (nvarchar(128))
  Repo_definition : (nvarchar(max))
  - Repo_generated_always_type : (tinyint)
  Repo_graph_type : (int)
  Repo_increment_value : (sql_variant)
  - Repo_is_computed : (bit)
  - Repo_is_identity : (bit)
  Repo_is_nullable : (bit)
  Repo_is_persisted : (bit)
  Repo_seed_value : (sql_variant)
  Repo_user_type_fullname : (nvarchar(128))
  Repo_user_type_name : (nvarchar(128))
  Repo_uses_database_collation : (bit)
  - RepoObject_fullname : (nvarchar(261))
  - RepoObject_fullname2 : (nvarchar(257))
  - RepoObject_guid : (uniqueidentifier)
  - RepoObject_name : (nvarchar(128))
  RepoObject_Referencing_Count : (int)
  - RepoObject_schema_name : (nvarchar(128))
  - RepoObject_type : (char(2))
  RepoObjectColumn_column_id : (int)
  - RepoObjectColumn_fullname : (nvarchar(520))
  - RepoObjectColumn_fullname2 : (nvarchar(386))
  - RepoObjectColumn_name : (nvarchar(128))
  - SysObject_fullname : (nvarchar(261))
  - SysObject_fullname2 : (nvarchar(257))
  SysObject_id : (int)
  SysObject_modify_date : (datetime)
  - SysObject_name : (nvarchar(128))
  - SysObject_parent_object_id : (int)
  - SysObject_schema_name : (nvarchar(128))
  SysObject_type : (char(2))
  SysObjectColumn_column_id : (int)
  - SysObjectColumn_name : (nvarchar(128))
  tabcol_Description : (nvarchar(max))
  tabcol_DisplayFolder : (nvarchar(500))
  tabcol_Expression : (nvarchar(max))
  tabcol_FormatString : (nvarchar(500))
  - tabcol_IsHidden : (bit)
  - tabcol_IsKey : (bit)
  - tabcol_IsUnique : (bit)
  tabcol_SummarizeBy : (nvarchar(500))
  tabcol_Type : (nvarchar(500))
  --
  --
}

entity "puml-link:repo.RepoObjectColumn_gross2.adoc[prefix=..]" as repo.RepoObjectColumn_gross2 << V >> {
  --
  AntoraReferencedColumnList : (nvarchar(max))
  AntoraReferencingColumnList : (nvarchar(max))
  - Column_name : (nvarchar(128))
  Description : (nvarchar(max))
  has_different_sys_names : (bit)
  has_get_referenced_issue : (bit)
  index_column_id : (int)
  index_name : (nvarchar(450))
  Inheritance_StringAggSeparatorSql : (nvarchar(4000))
  InheritanceDefinition : (nvarchar(4000))
  InheritanceType : (tinyint)
  is_index_primary_key : (bit)
  is_persistence_no_check : (bit)
  is_persistence_no_include : (bit)
  is_persistence_no_update : (bit)
  is_query_plan_expression : (bit)
  is_repo_managed : (bit)
  - is_RepoObject_name_uniqueidentifier : (int)
  - is_RepoObjectColumn_name_uniqueidentifier : (int)
  is_required_ColumnMerge : (bit)
  - is_ssas : (bit)
  is_SysObject_missing : (bit)
  - is_SysObject_name_uniqueidentifier : (int)
  is_SysObjectColumn_missing : (bit)
  - is_SysObjectColumn_name_uniqueidentifier : (int)
  isAnyIndexColumn : (int)
  - modify_dt : (datetime)
  node_id : (bigint)
  persistence_source_RepoObject_guid : (uniqueidentifier)
  persistence_source_RepoObject_guid_via_Column : (uniqueidentifier)
  persistence_source_RepoObjectColumn_guid : (uniqueidentifier)
  pk_index_guid : (uniqueidentifier)
  Property_ms_description : (nvarchar(4000))
  Referencing_Count : (int)
  Repo_default_definition : (nvarchar(max))
  Repo_default_is_system_named : (bit)
  Repo_default_name : (nvarchar(128))
  Repo_definition : (nvarchar(max))
  - Repo_generated_always_type : (tinyint)
  Repo_graph_type : (int)
  Repo_increment_value : (sql_variant)
  - Repo_is_computed : (bit)
  - Repo_is_identity : (bit)
  Repo_is_nullable : (bit)
  Repo_is_persisted : (bit)
  Repo_seed_value : (sql_variant)
  Repo_user_type_fullname : (nvarchar(128))
  Repo_user_type_name : (nvarchar(128))
  Repo_uses_database_collation : (bit)
  - RepoObject_fullname : (nvarchar(261))
  - RepoObject_fullname2 : (nvarchar(257))
  - RepoObject_guid : (uniqueidentifier)
  - RepoObject_name : (nvarchar(128))
  RepoObject_Referencing_Count : (int)
  - RepoObject_schema_name : (nvarchar(128))
  - RepoObject_type : (char(2))
  RepoObjectColumn_column_id : (int)
  - RepoObjectColumn_fullname : (nvarchar(520))
  - RepoObjectColumn_fullname2 : (nvarchar(386))
  - RepoObjectColumn_guid : (uniqueidentifier)
  - RepoObjectColumn_name : (nvarchar(128))
  - SysObject_fullname : (nvarchar(261))
  - SysObject_fullname2 : (nvarchar(257))
  SysObject_id : (int)
  SysObject_modify_date : (datetime)
  - SysObject_name : (nvarchar(128))
  - SysObject_parent_object_id : (int)
  - SysObject_schema_name : (nvarchar(128))
  SysObject_type : (char(2))
  SysObjectColumn_column_id : (int)
  - SysObjectColumn_name : (nvarchar(128))
  tabcol_Description : (nvarchar(max))
  tabcol_DisplayFolder : (nvarchar(500))
  tabcol_Expression : (nvarchar(max))
  tabcol_FormatString : (nvarchar(500))
  - tabcol_IsHidden : (bit)
  - tabcol_IsKey : (bit)
  - tabcol_IsUnique : (bit)
  tabcol_SummarizeBy : (nvarchar(500))
  tabcol_Type : (nvarchar(500))
  --
  --
}

entity "puml-link:repo.usp_sync_guid_RepoObjectColumn.adoc[prefix=..]" as repo.usp_sync_guid_RepoObjectColumn << P >> {
  --
  --
  --
}

entity "puml-link:ssas.model_json_311_tables_columns_T.adoc[prefix=..]" as ssas.model_json_311_tables_columns_T << U >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  **tables_columns_name** : (nvarchar(128))
  --
  - RepoObject_guid : (uniqueidentifier)
  - RepoObjectColumn_guid : (uniqueidentifier)
  tables_columns_dataType : (nvarchar(500))
  tables_columns_description : (nvarchar(max))
  tables_columns_description_ja : (nvarchar(max))
  tables_columns_displayFolder : (nvarchar(500))
  tables_columns_expression : (nvarchar(max))
  tables_columns_expression_ja : (nvarchar(max))
  tables_columns_formatString : (nvarchar(500))
  tables_columns_isDataTypeInferred : (bit)
  tables_columns_isHidden : (bit)
  tables_columns_isKey : (bit)
  tables_columns_isNameInferred : (bit)
  tables_columns_isNullable : (bit)
  tables_columns_isUnique : (bit)
  tables_columns_keepUniqueRows : (bit)
  tables_columns_sortByColumn : (nvarchar(500))
  tables_columns_sourceColumn : (nvarchar(500))
  tables_columns_sourceProviderType : (nvarchar(500))
  tables_columns_summarizeBy : (nvarchar(500))
  tables_columns_type : (nvarchar(500))
  --
  --
}

entity "puml-link:ssas.model_json_31111_tables_columns_descriptions_StrAgg.adoc[prefix=..]" as ssas.model_json_31111_tables_columns_descriptions_StrAgg << V >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  - **tables_columns_name** : (nvarchar(128))
  --
  descriptions_StrAgg : (nvarchar(max))
  - RepoObject_guid : (uniqueidentifier)
  - RepoObjectColumn_guid : (uniqueidentifier)
  --
  --
}

entity "puml-link:ssas.model_json_31121_tables_columns_expressions_StrAgg.adoc[prefix=..]" as ssas.model_json_31121_tables_columns_expressions_StrAgg << V >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  - **tables_columns_name** : (nvarchar(128))
  --
  expressions_StrAgg : (nvarchar(max))
  - RepoObject_guid : (uniqueidentifier)
  - RepoObjectColumn_guid : (uniqueidentifier)
  --
  --
}

property.fs_get_RepoObjectColumnProperty_nvarchar <.. repo.RepoObjectColumn_gross
repo.RepoObject <.. repo.RepoObjectColumn_gross
repo.RepoObject_persistence <.. repo.RepoObjectColumn_gross
repo.RepoObjectColumn <.. repo.RepoObjectColumn_gross
repo.RepoObjectColumn_gross <.. reference.RepoObjectColumn_reference_FirstResultSet
repo.RepoObjectColumn_gross <.. reference.RepoObjectColumn_reference_QueryPlan
repo.RepoObjectColumn_gross <.. repo.usp_sync_guid_RepoObjectColumn
repo.RepoObjectColumn_gross <.. graph.RepoObjectColumn_S
repo.RepoObjectColumn_gross <.. property.RepoObjectColumnProperty_ForUpdate
repo.RepoObjectColumn_gross <.. reference.RepoObjectColumn_reference_virtual
repo.RepoObjectColumn_gross <.. reference.usp_RepoObjectColumnSource_virtual_set
repo.RepoObjectColumn_gross <.. repo.RepoObjectColumn_gross2
repo.RepoObjectColumn_gross <.. docs.Unit_1_union
ssas.model_json_311_tables_columns_T <.. repo.RepoObjectColumn_gross
ssas.model_json_31111_tables_columns_descriptions_StrAgg <.. repo.RepoObjectColumn_gross
ssas.model_json_31121_tables_columns_expressions_StrAgg <.. repo.RepoObjectColumn_gross
repo.RepoObject::has_get_referenced_issue <-- repo.RepoObjectColumn_gross::has_get_referenced_issue
repo.RepoObject::is_repo_managed <-- repo.RepoObjectColumn_gross::is_repo_managed
repo.RepoObject::is_RepoObject_name_uniqueidentifier <-- repo.RepoObjectColumn_gross::is_RepoObject_name_uniqueidentifier
repo.RepoObject::is_ssas <-- repo.RepoObjectColumn_gross::is_ssas
repo.RepoObject::is_SysObject_missing <-- repo.RepoObjectColumn_gross::is_SysObject_missing
repo.RepoObject::is_SysObject_name_uniqueidentifier <-- repo.RepoObjectColumn_gross::is_SysObject_name_uniqueidentifier
repo.RepoObject::modify_dt <-- repo.RepoObjectColumn_gross::modify_dt
repo.RepoObject::node_id <-- repo.RepoObjectColumn_gross::node_id
repo.RepoObject::pk_index_guid <-- repo.RepoObjectColumn_gross::pk_index_guid
repo.RepoObject::RepoObject_fullname <-- repo.RepoObjectColumn_gross::RepoObject_fullname
repo.RepoObject::RepoObject_fullname2 <-- repo.RepoObjectColumn_gross::RepoObject_fullname2
repo.RepoObject::RepoObject_name <-- repo.RepoObjectColumn_gross::RepoObject_name
repo.RepoObject::RepoObject_Referencing_Count <-- repo.RepoObjectColumn_gross::RepoObject_Referencing_Count
repo.RepoObject::RepoObject_schema_name <-- repo.RepoObjectColumn_gross::RepoObject_schema_name
repo.RepoObject::RepoObject_type <-- repo.RepoObjectColumn_gross::RepoObject_type
repo.RepoObject::SysObject_fullname <-- repo.RepoObjectColumn_gross::SysObject_fullname
repo.RepoObject::SysObject_fullname2 <-- repo.RepoObjectColumn_gross::SysObject_fullname2
repo.RepoObject::SysObject_id <-- repo.RepoObjectColumn_gross::SysObject_id
repo.RepoObject::SysObject_modify_date <-- repo.RepoObjectColumn_gross::SysObject_modify_date
repo.RepoObject::SysObject_name <-- repo.RepoObjectColumn_gross::SysObject_name
repo.RepoObject::SysObject_parent_object_id <-- repo.RepoObjectColumn_gross::SysObject_parent_object_id
repo.RepoObject::SysObject_schema_name <-- repo.RepoObjectColumn_gross::SysObject_schema_name
repo.RepoObject::SysObject_type <-- repo.RepoObjectColumn_gross::SysObject_type
repo.RepoObject_persistence::source_RepoObject_guid <-- repo.RepoObjectColumn_gross::persistence_source_RepoObject_guid
repo.RepoObjectColumn::Column_name <-- repo.RepoObjectColumn_gross::Column_name
repo.RepoObjectColumn::has_different_sys_names <-- repo.RepoObjectColumn_gross::has_different_sys_names
repo.RepoObjectColumn::Inheritance_StringAggSeparatorSql <-- repo.RepoObjectColumn_gross::Inheritance_StringAggSeparatorSql
repo.RepoObjectColumn::InheritanceDefinition <-- repo.RepoObjectColumn_gross::InheritanceDefinition
repo.RepoObjectColumn::InheritanceType <-- repo.RepoObjectColumn_gross::InheritanceType
repo.RepoObjectColumn::is_persistence_no_check <-- repo.RepoObjectColumn_gross::is_persistence_no_check
repo.RepoObjectColumn::is_persistence_no_include <-- repo.RepoObjectColumn_gross::is_persistence_no_include
repo.RepoObjectColumn::is_persistence_no_update <-- repo.RepoObjectColumn_gross::is_persistence_no_update
repo.RepoObjectColumn::is_query_plan_expression <-- repo.RepoObjectColumn_gross::is_query_plan_expression
repo.RepoObjectColumn::is_RepoObjectColumn_name_uniqueidentifier <-- repo.RepoObjectColumn_gross::is_RepoObjectColumn_name_uniqueidentifier
repo.RepoObjectColumn::is_required_ColumnMerge <-- repo.RepoObjectColumn_gross::is_required_ColumnMerge
repo.RepoObjectColumn::is_SysObjectColumn_missing <-- repo.RepoObjectColumn_gross::is_SysObjectColumn_missing
repo.RepoObjectColumn::is_SysObjectColumn_name_uniqueidentifier <-- repo.RepoObjectColumn_gross::is_SysObjectColumn_name_uniqueidentifier
repo.RepoObjectColumn::persistence_source_RepoObjectColumn_guid <-- repo.RepoObjectColumn_gross::persistence_source_RepoObjectColumn_guid
repo.RepoObjectColumn::Referencing_Count <-- repo.RepoObjectColumn_gross::Referencing_Count
repo.RepoObjectColumn::Repo_default_definition <-- repo.RepoObjectColumn_gross::Repo_default_definition
repo.RepoObjectColumn::Repo_default_is_system_named <-- repo.RepoObjectColumn_gross::Repo_default_is_system_named
repo.RepoObjectColumn::Repo_default_name <-- repo.RepoObjectColumn_gross::Repo_default_name
repo.RepoObjectColumn::Repo_definition <-- repo.RepoObjectColumn_gross::Repo_definition
repo.RepoObjectColumn::Repo_generated_always_type <-- repo.RepoObjectColumn_gross::Repo_generated_always_type
repo.RepoObjectColumn::Repo_graph_type <-- repo.RepoObjectColumn_gross::Repo_graph_type
repo.RepoObjectColumn::Repo_increment_value <-- repo.RepoObjectColumn_gross::Repo_increment_value
repo.RepoObjectColumn::Repo_is_computed <-- repo.RepoObjectColumn_gross::Repo_is_computed
repo.RepoObjectColumn::Repo_is_identity <-- repo.RepoObjectColumn_gross::Repo_is_identity
repo.RepoObjectColumn::Repo_is_nullable <-- repo.RepoObjectColumn_gross::Repo_is_nullable
repo.RepoObjectColumn::Repo_is_persisted <-- repo.RepoObjectColumn_gross::Repo_is_persisted
repo.RepoObjectColumn::Repo_seed_value <-- repo.RepoObjectColumn_gross::Repo_seed_value
repo.RepoObjectColumn::Repo_user_type_fullname <-- repo.RepoObjectColumn_gross::Repo_user_type_fullname
repo.RepoObjectColumn::Repo_user_type_name <-- repo.RepoObjectColumn_gross::Repo_user_type_name
repo.RepoObjectColumn::Repo_uses_database_collation <-- repo.RepoObjectColumn_gross::Repo_uses_database_collation
repo.RepoObjectColumn::RepoObject_guid <-- repo.RepoObjectColumn_gross::RepoObject_guid
repo.RepoObjectColumn::RepoObjectColumn_column_id <-- repo.RepoObjectColumn_gross::RepoObjectColumn_column_id
repo.RepoObjectColumn::RepoObjectColumn_guid <-- repo.RepoObjectColumn_gross::RepoObjectColumn_guid
repo.RepoObjectColumn::RepoObjectColumn_name <-- repo.RepoObjectColumn_gross::RepoObjectColumn_name
repo.RepoObjectColumn::SysObjectColumn_column_id <-- repo.RepoObjectColumn_gross::SysObjectColumn_column_id
repo.RepoObjectColumn::SysObjectColumn_name <-- repo.RepoObjectColumn_gross::SysObjectColumn_name
repo.RepoObjectColumn_gross::Column_name <-- repo.RepoObjectColumn_gross2::Column_name
repo.RepoObjectColumn_gross::Description <-- repo.RepoObjectColumn_gross2::Description
repo.RepoObjectColumn_gross::has_different_sys_names <-- repo.RepoObjectColumn_gross2::has_different_sys_names
repo.RepoObjectColumn_gross::has_get_referenced_issue <-- repo.RepoObjectColumn_gross2::has_get_referenced_issue
repo.RepoObjectColumn_gross::Inheritance_StringAggSeparatorSql <-- repo.RepoObjectColumn_gross2::Inheritance_StringAggSeparatorSql
repo.RepoObjectColumn_gross::InheritanceDefinition <-- repo.RepoObjectColumn_gross2::InheritanceDefinition
repo.RepoObjectColumn_gross::InheritanceType <-- repo.RepoObjectColumn_gross2::InheritanceType
repo.RepoObjectColumn_gross::is_persistence_no_check <-- repo.RepoObjectColumn_gross2::is_persistence_no_check
repo.RepoObjectColumn_gross::is_persistence_no_include <-- repo.RepoObjectColumn_gross2::is_persistence_no_include
repo.RepoObjectColumn_gross::is_persistence_no_update <-- repo.RepoObjectColumn_gross2::is_persistence_no_update
repo.RepoObjectColumn_gross::is_query_plan_expression <-- repo.RepoObjectColumn_gross2::is_query_plan_expression
repo.RepoObjectColumn_gross::is_repo_managed <-- repo.RepoObjectColumn_gross2::is_repo_managed
repo.RepoObjectColumn_gross::is_RepoObject_name_uniqueidentifier <-- repo.RepoObjectColumn_gross2::is_RepoObject_name_uniqueidentifier
repo.RepoObjectColumn_gross::is_RepoObjectColumn_name_uniqueidentifier <-- repo.RepoObjectColumn_gross2::is_RepoObjectColumn_name_uniqueidentifier
repo.RepoObjectColumn_gross::is_required_ColumnMerge <-- repo.RepoObjectColumn_gross2::is_required_ColumnMerge
repo.RepoObjectColumn_gross::is_ssas <-- repo.RepoObjectColumn_gross2::is_ssas
repo.RepoObjectColumn_gross::is_SysObject_missing <-- repo.RepoObjectColumn_gross2::is_SysObject_missing
repo.RepoObjectColumn_gross::is_SysObject_name_uniqueidentifier <-- repo.RepoObjectColumn_gross2::is_SysObject_name_uniqueidentifier
repo.RepoObjectColumn_gross::is_SysObjectColumn_missing <-- repo.RepoObjectColumn_gross2::is_SysObjectColumn_missing
repo.RepoObjectColumn_gross::is_SysObjectColumn_name_uniqueidentifier <-- repo.RepoObjectColumn_gross2::is_SysObjectColumn_name_uniqueidentifier
repo.RepoObjectColumn_gross::modify_dt <-- repo.RepoObjectColumn_gross2::modify_dt
repo.RepoObjectColumn_gross::node_id <-- reference.RepoObjectColumn_reference_virtual::referencing_node_id
repo.RepoObjectColumn_gross::node_id <-- reference.RepoObjectColumn_reference_virtual::referenced_node_id
repo.RepoObjectColumn_gross::node_id <-- repo.RepoObjectColumn_gross2::node_id
repo.RepoObjectColumn_gross::persistence_source_RepoObject_guid <-- repo.RepoObjectColumn_gross2::persistence_source_RepoObject_guid
repo.RepoObjectColumn_gross::persistence_source_RepoObjectColumn_guid <-- repo.RepoObjectColumn_gross2::persistence_source_RepoObjectColumn_guid
repo.RepoObjectColumn_gross::pk_index_guid <-- repo.RepoObjectColumn_gross2::pk_index_guid
repo.RepoObjectColumn_gross::Property_ms_description <-- repo.RepoObjectColumn_gross2::Property_ms_description
repo.RepoObjectColumn_gross::Referencing_Count <-- repo.RepoObjectColumn_gross2::Referencing_Count
repo.RepoObjectColumn_gross::Repo_default_definition <-- repo.RepoObjectColumn_gross2::Repo_default_definition
repo.RepoObjectColumn_gross::Repo_default_is_system_named <-- repo.RepoObjectColumn_gross2::Repo_default_is_system_named
repo.RepoObjectColumn_gross::Repo_default_name <-- repo.RepoObjectColumn_gross2::Repo_default_name
repo.RepoObjectColumn_gross::Repo_definition <-- repo.RepoObjectColumn_gross2::Repo_definition
repo.RepoObjectColumn_gross::Repo_generated_always_type <-- repo.RepoObjectColumn_gross2::Repo_generated_always_type
repo.RepoObjectColumn_gross::Repo_graph_type <-- repo.RepoObjectColumn_gross2::Repo_graph_type
repo.RepoObjectColumn_gross::Repo_increment_value <-- repo.RepoObjectColumn_gross2::Repo_increment_value
repo.RepoObjectColumn_gross::Repo_is_computed <-- repo.RepoObjectColumn_gross2::Repo_is_computed
repo.RepoObjectColumn_gross::Repo_is_identity <-- repo.RepoObjectColumn_gross2::Repo_is_identity
repo.RepoObjectColumn_gross::Repo_is_nullable <-- repo.RepoObjectColumn_gross2::Repo_is_nullable
repo.RepoObjectColumn_gross::Repo_is_persisted <-- repo.RepoObjectColumn_gross2::Repo_is_persisted
repo.RepoObjectColumn_gross::Repo_seed_value <-- repo.RepoObjectColumn_gross2::Repo_seed_value
repo.RepoObjectColumn_gross::Repo_user_type_fullname <-- graph.RepoObjectColumn_S::RepoObjectColumn_type
repo.RepoObjectColumn_gross::Repo_user_type_fullname <-- repo.RepoObjectColumn_gross2::Repo_user_type_fullname
repo.RepoObjectColumn_gross::Repo_user_type_fullname <-- property.RepoObjectColumnProperty_ForUpdate::Repo_user_type_fullname
repo.RepoObjectColumn_gross::Repo_user_type_name <-- repo.RepoObjectColumn_gross2::Repo_user_type_name
repo.RepoObjectColumn_gross::Repo_uses_database_collation <-- repo.RepoObjectColumn_gross2::Repo_uses_database_collation
repo.RepoObjectColumn_gross::RepoObject_fullname <-- graph.RepoObjectColumn_S::RepoObject_fullname
repo.RepoObjectColumn_gross::RepoObject_fullname <-- property.RepoObjectColumnProperty_ForUpdate::RepoObject_fullname
repo.RepoObjectColumn_gross::RepoObject_fullname <-- repo.RepoObjectColumn_gross2::RepoObject_fullname
repo.RepoObjectColumn_gross::RepoObject_fullname2 <-- property.RepoObjectColumnProperty_ForUpdate::RepoObject_fullname2
repo.RepoObjectColumn_gross::RepoObject_fullname2 <-- repo.RepoObjectColumn_gross2::RepoObject_fullname2
repo.RepoObjectColumn_gross::RepoObject_guid <-- reference.RepoObjectColumn_reference_FirstResultSet::referenced_RepoObject_guid
repo.RepoObjectColumn_gross::RepoObject_guid <-- reference.RepoObjectColumn_reference_QueryPlan::referenced_RepoObject_guid
repo.RepoObjectColumn_gross::RepoObject_guid <-- graph.RepoObjectColumn_S::RepoObject_guid
repo.RepoObjectColumn_gross::RepoObject_guid <-- property.RepoObjectColumnProperty_ForUpdate::RepoObject_guid
repo.RepoObjectColumn_gross::RepoObject_guid <-- reference.RepoObjectColumn_reference_virtual::referencing_RepoObject_guid
repo.RepoObjectColumn_gross::RepoObject_guid <-- reference.RepoObjectColumn_reference_virtual::referenced_RepoObject_guid
repo.RepoObjectColumn_gross::RepoObject_guid <-- repo.RepoObjectColumn_gross2::RepoObject_guid
repo.RepoObjectColumn_gross::RepoObject_name <-- property.RepoObjectColumnProperty_ForUpdate::RepoObject_name
repo.RepoObjectColumn_gross::RepoObject_name <-- repo.RepoObjectColumn_gross2::RepoObject_name
repo.RepoObjectColumn_gross::RepoObject_Referencing_Count <-- repo.RepoObjectColumn_gross2::RepoObject_Referencing_Count
repo.RepoObjectColumn_gross::RepoObject_schema_name <-- property.RepoObjectColumnProperty_ForUpdate::RepoObject_schema_name
repo.RepoObjectColumn_gross::RepoObject_schema_name <-- repo.RepoObjectColumn_gross2::RepoObject_schema_name
repo.RepoObjectColumn_gross::RepoObject_type <-- graph.RepoObjectColumn_S::RepoObject_type
repo.RepoObjectColumn_gross::RepoObject_type <-- repo.RepoObjectColumn_gross2::RepoObject_type
repo.RepoObjectColumn_gross::RepoObject_type <-- property.RepoObjectColumnProperty_ForUpdate::RepoObject_type
repo.RepoObjectColumn_gross::RepoObjectColumn_column_id <-- repo.RepoObjectColumn_gross2::RepoObjectColumn_column_id
repo.RepoObjectColumn_gross::RepoObjectColumn_fullname <-- graph.RepoObjectColumn_S::RepoObjectColumn_fullname
repo.RepoObjectColumn_gross::RepoObjectColumn_fullname <-- property.RepoObjectColumnProperty_ForUpdate::RepoObjectColumn_fullname
repo.RepoObjectColumn_gross::RepoObjectColumn_fullname <-- repo.RepoObjectColumn_gross2::RepoObjectColumn_fullname
repo.RepoObjectColumn_gross::RepoObjectColumn_fullname2 <-- property.RepoObjectColumnProperty_ForUpdate::RepoObjectColumn_fullname2
repo.RepoObjectColumn_gross::RepoObjectColumn_fullname2 <-- repo.RepoObjectColumn_gross2::RepoObjectColumn_fullname2
repo.RepoObjectColumn_gross::RepoObjectColumn_guid <-- reference.RepoObjectColumn_reference_FirstResultSet::referencing_RepoObjectColumn_guid
repo.RepoObjectColumn_gross::RepoObjectColumn_guid <-- reference.RepoObjectColumn_reference_FirstResultSet::referenced_RepoObjectColumn_guid
repo.RepoObjectColumn_gross::RepoObjectColumn_guid <-- reference.RepoObjectColumn_reference_QueryPlan::referencing_RepoObjectColumn_guid
repo.RepoObjectColumn_gross::RepoObjectColumn_guid <-- reference.RepoObjectColumn_reference_QueryPlan::referenced_RepoObjectColumn_guid
repo.RepoObjectColumn_gross::RepoObjectColumn_guid <-- graph.RepoObjectColumn_S::RepoObjectColumn_guid
repo.RepoObjectColumn_gross::RepoObjectColumn_guid <-- reference.RepoObjectColumn_reference_virtual::referencing_RepoObjectColumn_guid
repo.RepoObjectColumn_gross::RepoObjectColumn_guid <-- reference.RepoObjectColumn_reference_virtual::referenced_RepoObjectColumn_guid
repo.RepoObjectColumn_gross::RepoObjectColumn_guid <-- repo.RepoObjectColumn_gross2::RepoObjectColumn_guid
repo.RepoObjectColumn_gross::RepoObjectColumn_name <-- graph.RepoObjectColumn_S::RepoObjectColumn_name
repo.RepoObjectColumn_gross::RepoObjectColumn_name <-- property.RepoObjectColumnProperty_ForUpdate::RepoObjectColumn_name
repo.RepoObjectColumn_gross::RepoObjectColumn_name <-- repo.RepoObjectColumn_gross2::RepoObjectColumn_name
repo.RepoObjectColumn_gross::SysObject_fullname <-- repo.RepoObjectColumn_gross2::SysObject_fullname
repo.RepoObjectColumn_gross::SysObject_fullname2 <-- repo.RepoObjectColumn_gross2::SysObject_fullname2
repo.RepoObjectColumn_gross::SysObject_id <-- reference.RepoObjectColumn_reference_FirstResultSet::referenced_id
repo.RepoObjectColumn_gross::SysObject_id <-- reference.RepoObjectColumn_reference_QueryPlan::referenced_id
repo.RepoObjectColumn_gross::SysObject_id <-- reference.RepoObjectColumn_reference_virtual::referencing_id
repo.RepoObjectColumn_gross::SysObject_id <-- reference.RepoObjectColumn_reference_virtual::referenced_id
repo.RepoObjectColumn_gross::SysObject_id <-- repo.RepoObjectColumn_gross2::SysObject_id
repo.RepoObjectColumn_gross::SysObject_modify_date <-- repo.RepoObjectColumn_gross2::SysObject_modify_date
repo.RepoObjectColumn_gross::SysObject_name <-- reference.RepoObjectColumn_reference_QueryPlan::referenced_entity_name
repo.RepoObjectColumn_gross::SysObject_name <-- reference.RepoObjectColumn_reference_virtual::referencing_entity_name
repo.RepoObjectColumn_gross::SysObject_name <-- reference.RepoObjectColumn_reference_virtual::referenced_entity_name
repo.RepoObjectColumn_gross::SysObject_name <-- repo.RepoObjectColumn_gross2::SysObject_name
repo.RepoObjectColumn_gross::SysObject_parent_object_id <-- repo.RepoObjectColumn_gross2::SysObject_parent_object_id
repo.RepoObjectColumn_gross::SysObject_schema_name <-- reference.RepoObjectColumn_reference_QueryPlan::referenced_schema_name
repo.RepoObjectColumn_gross::SysObject_schema_name <-- reference.RepoObjectColumn_reference_virtual::referencing_schema_name
repo.RepoObjectColumn_gross::SysObject_schema_name <-- reference.RepoObjectColumn_reference_virtual::referenced_schema_name
repo.RepoObjectColumn_gross::SysObject_schema_name <-- repo.RepoObjectColumn_gross2::SysObject_schema_name
repo.RepoObjectColumn_gross::SysObject_type <-- reference.RepoObjectColumn_reference_FirstResultSet::referenced_type
repo.RepoObjectColumn_gross::SysObject_type <-- reference.RepoObjectColumn_reference_QueryPlan::referenced_type
repo.RepoObjectColumn_gross::SysObject_type <-- reference.RepoObjectColumn_reference_virtual::referencing_type
repo.RepoObjectColumn_gross::SysObject_type <-- reference.RepoObjectColumn_reference_virtual::referenced_type
repo.RepoObjectColumn_gross::SysObject_type <-- repo.RepoObjectColumn_gross2::SysObject_type
repo.RepoObjectColumn_gross::SysObjectColumn_column_id <-- reference.RepoObjectColumn_reference_FirstResultSet::referencing_minor_id
repo.RepoObjectColumn_gross::SysObjectColumn_column_id <-- reference.RepoObjectColumn_reference_FirstResultSet::referenced_minor_id
repo.RepoObjectColumn_gross::SysObjectColumn_column_id <-- reference.RepoObjectColumn_reference_QueryPlan::referencing_minor_id
repo.RepoObjectColumn_gross::SysObjectColumn_column_id <-- reference.RepoObjectColumn_reference_QueryPlan::referenced_minor_id
repo.RepoObjectColumn_gross::SysObjectColumn_column_id <-- reference.RepoObjectColumn_reference_virtual::referencing_minor_id
repo.RepoObjectColumn_gross::SysObjectColumn_column_id <-- reference.RepoObjectColumn_reference_virtual::referenced_minor_id
repo.RepoObjectColumn_gross::SysObjectColumn_column_id <-- repo.RepoObjectColumn_gross2::SysObjectColumn_column_id
repo.RepoObjectColumn_gross::SysObjectColumn_name <-- reference.RepoObjectColumn_reference_virtual::referencing_column_name
repo.RepoObjectColumn_gross::SysObjectColumn_name <-- reference.RepoObjectColumn_reference_virtual::referenced_column_name
repo.RepoObjectColumn_gross::SysObjectColumn_name <-- repo.RepoObjectColumn_gross2::SysObjectColumn_name
repo.RepoObjectColumn_gross::tabcol_Description <-- repo.RepoObjectColumn_gross2::tabcol_Description
repo.RepoObjectColumn_gross::tabcol_DisplayFolder <-- repo.RepoObjectColumn_gross2::tabcol_DisplayFolder
repo.RepoObjectColumn_gross::tabcol_Expression <-- repo.RepoObjectColumn_gross2::tabcol_Expression
repo.RepoObjectColumn_gross::tabcol_FormatString <-- repo.RepoObjectColumn_gross2::tabcol_FormatString
repo.RepoObjectColumn_gross::tabcol_IsHidden <-- repo.RepoObjectColumn_gross2::tabcol_IsHidden
repo.RepoObjectColumn_gross::tabcol_IsKey <-- repo.RepoObjectColumn_gross2::tabcol_IsKey
repo.RepoObjectColumn_gross::tabcol_IsUnique <-- repo.RepoObjectColumn_gross2::tabcol_IsUnique
repo.RepoObjectColumn_gross::tabcol_SummarizeBy <-- repo.RepoObjectColumn_gross2::tabcol_SummarizeBy
repo.RepoObjectColumn_gross::tabcol_Type <-- repo.RepoObjectColumn_gross2::tabcol_Type
ssas.model_json_311_tables_columns_T::tables_columns_displayFolder <-- repo.RepoObjectColumn_gross::tabcol_DisplayFolder
ssas.model_json_311_tables_columns_T::tables_columns_formatString <-- repo.RepoObjectColumn_gross::tabcol_FormatString
ssas.model_json_311_tables_columns_T::tables_columns_summarizeBy <-- repo.RepoObjectColumn_gross::tabcol_SummarizeBy
ssas.model_json_311_tables_columns_T::tables_columns_type <-- repo.RepoObjectColumn_gross::tabcol_Type
footer
to view a reduced diagram in original size and to be able to click on the links:
open the diagram in a new tab via the Context menu.
end footer

@enduml

