left to right direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity repo.RepoSchema << U >> {
  * **RepoSchema_guid** : uniqueidentifier
  --
  is_SysSchema_missing : bit
  RepoSchema_ms_description : nvarchar(4000)
  * RepoSchema_name : nvarchar(128)
  SysSchema_id : int
  * SysSchema_name : nvarchar(128)
  {abstract} has_different_sys_names : bit
  * {static} is_RepoSchema_name_uniqueidentifier : int
  * {static} is_SysSchema_name_uniqueidentifier : int
}

entity repo.SysSchema_RepoSchema_via_name << V >> {
  --
  is_RepoSchema_name_uniqueidentifier : int
  is_SysSchema_name_uniqueidentifier : int
  RepoSchema_guid : uniqueidentifier
  RepoSchema_is_SysSchema_missing : bit
  RepoSchema_name : nvarchar(128)
  RepoSchema_SysSchema_id : int
  RepoSchema_SysSchema_name : nvarchar(128)
  * SysSchema_id : int
  * SysSchema_name : sysname
  SysSchema_RepoSchema_guid : uniqueidentifier
}

entity repo.usp_sync_guid_RepoSchema << P >> {
  --
}

entity repo_sys.SysSchema << V >> {
  --
  * SysSchema_id : int
  * SysSchema_name : sysname
  SysSchema_principal_id : int
  SysSchema_RepoSchema_guid : uniqueidentifier
}

repo.RepoSchema <.. repo.usp_sync_guid_RepoSchema
repo.RepoSchema <.. repo.SysSchema_RepoSchema_via_name
repo.SysSchema_RepoSchema_via_name <.. repo.usp_sync_guid_RepoSchema
repo_sys.SysSchema <.. repo.usp_sync_guid_RepoSchema
repo_sys.SysSchema <.. repo.SysSchema_RepoSchema_via_name
repo.RepoSchema::is_RepoSchema_name_uniqueidentifier <-- repo.SysSchema_RepoSchema_via_name::is_RepoSchema_name_uniqueidentifier
repo.RepoSchema::is_SysSchema_missing <-- repo.SysSchema_RepoSchema_via_name::RepoSchema_is_SysSchema_missing
repo.RepoSchema::is_SysSchema_name_uniqueidentifier <-- repo.SysSchema_RepoSchema_via_name::is_SysSchema_name_uniqueidentifier
repo.RepoSchema::RepoSchema_guid <-- repo.SysSchema_RepoSchema_via_name::RepoSchema_guid
repo.RepoSchema::RepoSchema_name <-- repo.SysSchema_RepoSchema_via_name::RepoSchema_name
repo.RepoSchema::SysSchema_id <-- repo.SysSchema_RepoSchema_via_name::RepoSchema_SysSchema_id
repo.RepoSchema::SysSchema_name <-- repo.SysSchema_RepoSchema_via_name::RepoSchema_SysSchema_name
repo_sys.SysSchema::SysSchema_id <-- repo.SysSchema_RepoSchema_via_name::SysSchema_id
repo_sys.SysSchema::SysSchema_name <-- repo.SysSchema_RepoSchema_via_name::SysSchema_name
repo_sys.SysSchema::SysSchema_RepoSchema_guid <-- repo.SysSchema_RepoSchema_via_name::SysSchema_RepoSchema_guid
