@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:config.ftv_get_parameter_value.adoc[]" as config.ftv_get_parameter_value << IF >> {
  --
  Parameter_value_result : (nvarchar(max))
  Parameter_value_result_date : (date)
  Parameter_value_result_datetime : (datetime)
  Parameter_value_result_int : (int)
  --
  --
}

entity "puml-link:dhw:sqldb:reference.additional_Reference_Object_T.adoc[]" as reference.additional_Reference_Object_T << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
  - AntoraComponent : (nvarchar(128))
  - AntoraModule : (nvarchar(128))
  Description : (nvarchar(max))
  - ObjectName : (nvarchar(128))
  - SchemaName : (nvarchar(128))
  --
  --
}

entity "puml-link:dhw:sqldb:repo.RepoObject_external_src.adoc[]" as repo.RepoObject_external_src << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
  - external_AntoraComponent : (nvarchar(128))
  - external_AntoraModule : (nvarchar(128))
  - is_external : (int)
  - is_repo_managed : (int)
  - RepoObject_name : (nvarchar(128))
  - RepoObject_schema_name : (nvarchar(128))
  - RepoObject_type : (varchar(1))
  - SysObject_name : (nvarchar(128))
  - SysObject_schema_name : (nvarchar(128))
  - SysObject_type : (varchar(1))
  --
  --
}

entity "puml-link:dhw:sqldb:repo.RepoObject_external_tgt.adoc[]" as repo.RepoObject_external_tgt << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
  - external_AntoraComponent : (nvarchar(128))
  - external_AntoraModule : (nvarchar(128))
  has_execution_plan_issue : (bit)
  has_get_referenced_issue : (bit)
  Inheritance_StringAggSeparatorSql : (nvarchar(4000))
  InheritanceDefinition : (nvarchar(4000))
  InheritanceType : (tinyint)
  - is_external : (int)
  - is_repo_managed : (int)
  is_required_ObjectMerge : (bit)
  - is_ssas : (bit)
  is_SysObject_missing : (bit)
  - modify_dt : (datetime)
  pk_index_guid : (uniqueidentifier)
  pk_IndexPatternColumnName_new : (nvarchar(4000))
  Repo_history_table_guid : (uniqueidentifier)
  Repo_temporal_type : (tinyint)
  - RepoObject_name : (nvarchar(128))
  RepoObject_Referencing_Count : (int)
  - RepoObject_schema_name : (nvarchar(128))
  - RepoObject_type : (varchar(1))
  SysObject_id : (int)
  SysObject_modify_date : (datetime)
  - SysObject_name : (nvarchar(128))
  - SysObject_parent_object_id : (int)
  - SysObject_schema_name : (nvarchar(128))
  - SysObject_type : (varchar(1))
  --
  --
}

entity "puml-link:dhw:sqldb:repo.usp_PERSIST_RepoObject_external_tgt.adoc[]" as repo.usp_PERSIST_RepoObject_external_tgt << P >> {
  --
  --
  --
}

config.ftv_get_parameter_value <.. repo.RepoObject_external_src
reference.additional_Reference_Object_T <.. repo.RepoObject_external_src
repo.RepoObject_external_src <.. repo.RepoObject_external_tgt
repo.RepoObject_external_src <.. repo.usp_PERSIST_RepoObject_external_tgt
"repo.RepoObject_external_src::external_AntoraComponent" <-- "repo.RepoObject_external_tgt::external_AntoraComponent"
"repo.RepoObject_external_src::external_AntoraModule" <-- "repo.RepoObject_external_tgt::external_AntoraModule"
"repo.RepoObject_external_src::is_external" <-- "repo.RepoObject_external_tgt::is_external"
"repo.RepoObject_external_src::is_repo_managed" <-- "repo.RepoObject_external_tgt::is_repo_managed"
"repo.RepoObject_external_src::RepoObject_guid" <-- "repo.RepoObject_external_tgt::RepoObject_guid"
"repo.RepoObject_external_src::RepoObject_name" <-- "repo.RepoObject_external_tgt::RepoObject_name"
"repo.RepoObject_external_src::RepoObject_schema_name" <-- "repo.RepoObject_external_tgt::RepoObject_schema_name"
"repo.RepoObject_external_src::RepoObject_type" <-- "repo.RepoObject_external_tgt::RepoObject_type"
"repo.RepoObject_external_src::SysObject_name" <-- "repo.RepoObject_external_tgt::SysObject_name"
"repo.RepoObject_external_src::SysObject_schema_name" <-- "repo.RepoObject_external_tgt::SysObject_schema_name"
"repo.RepoObject_external_src::SysObject_type" <-- "repo.RepoObject_external_tgt::SysObject_type"
@enduml

