@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:logs.usp_executionlog_insert.adoc[]" as logs.usp_ExecutionLog_insert << P >> {
  --
  --
  --
}

entity "puml-link:dhw:sqldb:repo.usp_main.adoc[]" as repo.usp_main << P >> {
  --
  --
  --
}

entity "puml-link:dhw:sqldb:repo.usp_persist_index_ssas_t.adoc[]" as repo.usp_PERSIST_Index_ssas_T << P >> {
  --
  --
  --
}

entity "puml-link:dhw:sqldb:repo.usp_persist_indexcolumn_ssas_t.adoc[]" as repo.usp_PERSIST_IndexColumn_ssas_T << P >> {
  --
  --
  --
}

entity "puml-link:dhw:sqldb:repo.usp_persist_repoobject_ssas_tgt.adoc[]" as repo.usp_PERSIST_RepoObject_SSAS_tgt << P >> {
  --
  --
  --
}

entity "puml-link:dhw:sqldb:repo.usp_persist_repoobjectcolumn_ssas_tgt.adoc[]" as repo.usp_PERSIST_RepoObjectColumn_SSAS_tgt << P >> {
  --
  --
  --
}

entity "puml-link:dhw:sqldb:repo.usp_persist_reposchema_ssas_tgt.adoc[]" as repo.usp_PERSIST_RepoSchema_ssas_tgt << P >> {
  --
  --
  --
}

entity "puml-link:dhw:sqldb:repo.usp_sync_guid_ssas.adoc[]" as repo.usp_sync_guid_ssas << P >> {
  --
  --
  --
}

entity "puml-link:dhw:sqldb:ssas.usp_persist_measures_translation_t.adoc[]" as ssas.usp_PERSIST_Measures_translation_T << P >> {
  --
  --
  --
}

entity "puml-link:dhw:sqldb:ssas.usp_persist_model_json_31_tables_t.adoc[]" as ssas.usp_PERSIST_model_json_31_tables_T << P >> {
  --
  --
  --
}

entity "puml-link:dhw:sqldb:ssas.usp_persist_model_json_311_tables_columns_t.adoc[]" as ssas.usp_PERSIST_model_json_311_tables_columns_T << P >> {
  --
  --
  --
}

entity "puml-link:dhw:sqldb:ssas.usp_persist_model_json_312_tables_measures_t.adoc[]" as ssas.usp_PERSIST_model_json_312_tables_measures_T << P >> {
  --
  --
  --
}

entity "puml-link:dhw:sqldb:ssas.usp_persist_model_json_32_relationships_t.adoc[]" as ssas.usp_PERSIST_model_json_32_relationships_T << P >> {
  --
  --
  --
}

entity "puml-link:dhw:sqldb:ssas.usp_persist_model_json_33_datasources_t.adoc[]" as ssas.usp_PERSIST_model_json_33_dataSources_T << P >> {
  --
  --
  --
}

entity "puml-link:dhw:sqldb:ssas.usp_persist_model_json_3411_cultures_translations_model_t.adoc[]" as ssas.usp_PERSIST_model_json_3411_cultures_translations_model_T << P >> {
  --
  --
  --
}

logs.usp_ExecutionLog_insert <.. repo.usp_sync_guid_ssas
repo.usp_PERSIST_Index_ssas_T <.. repo.usp_sync_guid_ssas
repo.usp_PERSIST_IndexColumn_ssas_T <.. repo.usp_sync_guid_ssas
repo.usp_PERSIST_RepoObject_SSAS_tgt <.. repo.usp_sync_guid_ssas
repo.usp_PERSIST_RepoObjectColumn_SSAS_tgt <.. repo.usp_sync_guid_ssas
repo.usp_PERSIST_RepoSchema_ssas_tgt <.. repo.usp_sync_guid_ssas
repo.usp_sync_guid_ssas <.. repo.usp_main
ssas.usp_PERSIST_Measures_translation_T <.. repo.usp_sync_guid_ssas
ssas.usp_PERSIST_model_json_31_tables_T <.. repo.usp_sync_guid_ssas
ssas.usp_PERSIST_model_json_311_tables_columns_T <.. repo.usp_sync_guid_ssas
ssas.usp_PERSIST_model_json_312_tables_measures_T <.. repo.usp_sync_guid_ssas
ssas.usp_PERSIST_model_json_32_relationships_T <.. repo.usp_sync_guid_ssas
ssas.usp_PERSIST_model_json_33_dataSources_T <.. repo.usp_sync_guid_ssas
ssas.usp_PERSIST_model_json_3411_cultures_translations_model_T <.. repo.usp_sync_guid_ssas

@enduml

