@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity "puml-link:logs.usp_ExecutionLog_insert.adoc[prefix=..]" as logs.usp_ExecutionLog_insert << P >> {
  --
  --
  --
}

entity "puml-link:sqlparse.RepoObject_SqlModules_61_SelectIdentifier_Union.adoc[prefix=..]" as sqlparse.RepoObject_SqlModules_61_SelectIdentifier_Union << V >> {
  --
  alias_QuoteName : (nvarchar(max))
  class : (nvarchar(500))
  normalized : (nvarchar(max))
  - RepoObject_guid : (uniqueidentifier)
  RowNumber_per_Object : (bigint)
  source_column_QuoteName : (nvarchar(max))
  source_table_QuoteName : (nvarchar(max))
  SysObject_fullname : (nvarchar(261))
  --
  --
}

entity "puml-link:sqlparse.RepoObject_SqlModules_61_SelectIdentifier_Union_T.adoc[prefix=..]" as sqlparse.RepoObject_SqlModules_61_SelectIdentifier_Union_T << U >> {
  --
  alias_QuoteName : (nvarchar(max))
  class : (nvarchar(500))
  normalized : (nvarchar(max))
  - RepoObject_guid : (uniqueidentifier)
  RowNumber_per_Object : (bigint)
  source_column_QuoteName : (nvarchar(max))
  source_table_QuoteName : (nvarchar(max))
  SysObject_fullname : (nvarchar(261))
  --
  --
}

entity "puml-link:sqlparse.usp_PERSIST_RepoObject_SqlModules_61_SelectIdentifier_Union_T.adoc[prefix=..]" as sqlparse.usp_PERSIST_RepoObject_SqlModules_61_SelectIdentifier_Union_T << P >> {
  --
  --
  --
}

entity "puml-link:sqlparse.usp_sqlparse.adoc[prefix=..]" as sqlparse.usp_sqlparse << P >> {
  --
  --
  --
}

logs.usp_ExecutionLog_insert <.. sqlparse.usp_PERSIST_RepoObject_SqlModules_61_SelectIdentifier_Union_T
sqlparse.RepoObject_SqlModules_61_SelectIdentifier_Union <.. sqlparse.usp_PERSIST_RepoObject_SqlModules_61_SelectIdentifier_Union_T
sqlparse.RepoObject_SqlModules_61_SelectIdentifier_Union_T <.. sqlparse.usp_PERSIST_RepoObject_SqlModules_61_SelectIdentifier_Union_T
sqlparse.usp_PERSIST_RepoObject_SqlModules_61_SelectIdentifier_Union_T <.. sqlparse.usp_sqlparse

footer
to view a reduced diagram in original size and to be able to click on the links:
open the diagram in a new tab via the Context menu.
end footer

@enduml

