@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssas.model_json_313211_tables_partitions_posdot.adoc[]" as ssas.model_json_313211_tables_partitions_PosDot << V >> {
  - databasename : (nvarchar(128))
  PosDot1 : (bigint)
  PosDot2 : (bigint)
  PosFrom : (bigint)
  PosFromDoublequota : (bigint)
  PosFromWhere : (bigint)
  - RepoObject_guid : (uniqueidentifier)
  StringFrom : (nvarchar(max))
  - tables_name : (nvarchar(128))
  tables_partitions_annotations_ja : (nvarchar(max))
  tables_partitions_dataView : (nvarchar(500))
  tables_partitions_mode : (nvarchar(500))
  tables_partitions_name : (nvarchar(500))
  tables_partitions_source_j : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_3132111_tables_partitions_part123.adoc[]" as ssas.model_json_3132111_tables_partitions_Part123 << V >> {
  - databasename : (nvarchar(128))
  Part1 : (nvarchar(max))
  Part2 : (nvarchar(max))
  Part3 : (nvarchar(max))
  PosDot1 : (bigint)
  PosDot2 : (bigint)
  PosFrom : (bigint)
  PosFromDoublequota : (bigint)
  PosFromWhere : (bigint)
  - RepoObject_guid : (uniqueidentifier)
  StringFrom : (nvarchar(max))
  - tables_name : (nvarchar(128))
  tables_partitions_annotations_ja : (nvarchar(max))
  tables_partitions_dataView : (nvarchar(500))
  tables_partitions_mode : (nvarchar(500))
  tables_partitions_name : (nvarchar(500))
  tables_partitions_source_j : (nvarchar(max))
  --
}

ssas.model_json_313211_tables_partitions_PosDot <.. ssas.model_json_3132111_tables_partitions_Part123
"ssas.model_json_313211_tables_partitions_PosDot::databasename" <-- "ssas.model_json_3132111_tables_partitions_Part123::databasename"
"ssas.model_json_313211_tables_partitions_PosDot::PosDot1" <-- "ssas.model_json_3132111_tables_partitions_Part123::PosDot1"
"ssas.model_json_313211_tables_partitions_PosDot::PosDot2" <-- "ssas.model_json_3132111_tables_partitions_Part123::PosDot2"
"ssas.model_json_313211_tables_partitions_PosDot::PosFrom" <-- "ssas.model_json_3132111_tables_partitions_Part123::PosFrom"
"ssas.model_json_313211_tables_partitions_PosDot::PosFromDoublequota" <-- "ssas.model_json_3132111_tables_partitions_Part123::PosFromDoublequota"
"ssas.model_json_313211_tables_partitions_PosDot::PosFromWhere" <-- "ssas.model_json_3132111_tables_partitions_Part123::PosFromWhere"
"ssas.model_json_313211_tables_partitions_PosDot::RepoObject_guid" <-- "ssas.model_json_3132111_tables_partitions_Part123::RepoObject_guid"
"ssas.model_json_313211_tables_partitions_PosDot::StringFrom" <-- "ssas.model_json_3132111_tables_partitions_Part123::StringFrom"
"ssas.model_json_313211_tables_partitions_PosDot::tables_name" <-- "ssas.model_json_3132111_tables_partitions_Part123::tables_name"
"ssas.model_json_313211_tables_partitions_PosDot::tables_partitions_annotations_ja" <-- "ssas.model_json_3132111_tables_partitions_Part123::tables_partitions_annotations_ja"
"ssas.model_json_313211_tables_partitions_PosDot::tables_partitions_dataView" <-- "ssas.model_json_3132111_tables_partitions_Part123::tables_partitions_dataView"
"ssas.model_json_313211_tables_partitions_PosDot::tables_partitions_mode" <-- "ssas.model_json_3132111_tables_partitions_Part123::tables_partitions_mode"
"ssas.model_json_313211_tables_partitions_PosDot::tables_partitions_name" <-- "ssas.model_json_3132111_tables_partitions_Part123::tables_partitions_name"
"ssas.model_json_313211_tables_partitions_PosDot::tables_partitions_source_j" <-- "ssas.model_json_3132111_tables_partitions_Part123::tables_partitions_source_j"footer The diagram is interactive and contains links.
@enduml

