@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:docs.repoobject_measurelist.adoc[]" as docs.RepoObject_MeasureList << V >> {
  **RepoObject_guid** : (uniqueidentifier)
  **cultures_name** : (nvarchar(10))
  AntoraMeasureDetails : (nvarchar(max))
  is_external : (tinyint)
  PlantumlMeasures : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssas.measures_translation_displayfolder_union.adoc[]" as ssas.Measures_translation_displayfolder_union << V >> {
  - cultures_name : (nvarchar(10))
  displayfolder_DisplayName : (nvarchar(512))
  displayfolder_translation : (nvarchar(512))
  - is_displayfolder : (int)
  Measure_DisplayName : (nvarchar(500))
  - Measure_guid : (uniqueidentifier)
  Measure_translation : (nvarchar(128))
  measures_displayFolder : (nvarchar(500))
  - measures_name : (nvarchar(500))
  - RepoObject_name : (nvarchar(128))
  - RepoSchema_name : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:ssas.measures_translation_t.adoc[]" as ssas.Measures_translation_T << U >> {
  - **Measure_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  **RepoObject_name** : (nvarchar(128))
  displayfolder_DisplayName : (nvarchar(512))
  displayfolder_translation : (nvarchar(512))
  Measure_DisplayName : (nvarchar(500))
  Measure_translation : (nvarchar(128))
  measures_displayFolder : (nvarchar(500))
  - measures_name : (nvarchar(500))
  - RepoSchema_name : (nvarchar(128))
  --
}

ssas.Measures_translation_displayfolder_union <.. docs.RepoObject_MeasureList
ssas.Measures_translation_T <.. ssas.Measures_translation_displayfolder_union
footer The diagram is interactive and contains links.
@enduml

