@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssas.model_json_312_tables_measures_T.adoc[]" as ssas.model_json_312_tables_measures_T << U >> {
  - **Measure_guid** : (uniqueidentifier)
  --
  - databasename : (nvarchar(128))
  - RepoObject_guid : (uniqueidentifier)
  tables_measures_description : (nvarchar(max))
  tables_measures_description_ja : (nvarchar(max))
  tables_measures_displayFolder : (nvarchar(500))
  tables_measures_expression : (nvarchar(max))
  tables_measures_expression_ja : (nvarchar(max))
  tables_measures_formatString : (nvarchar(500))
  tables_measures_isHidden : (bit)
  tables_measures_name : (nvarchar(500))
  - tables_name : (nvarchar(128))
  --
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_3121_tables_columns_descriptions_multiline.adoc[]" as ssas.model_json_3121_tables_columns_descriptions_multiline << V >> {
  --
  - databasename : (nvarchar(128))
  - Key : (nvarchar(4000))
  - Measure_guid : (uniqueidentifier)
  - RepoObject_guid : (uniqueidentifier)
  - tables_measures_name : (nvarchar(500))
  - tables_name : (nvarchar(128))
  - Type : (tinyint)
  Value : (nvarchar(max))
  --
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31211_tables_columns_descriptions_StrAgg.adoc[]" as ssas.model_json_31211_tables_columns_descriptions_StrAgg << V >> {
  --
  - databasename : (nvarchar(128))
  descriptions_StrAgg : (nvarchar(max))
  - Measure_guid : (uniqueidentifier)
  - RepoObject_guid : (uniqueidentifier)
  - tables_measures_name : (nvarchar(500))
  - tables_name : (nvarchar(128))
  --
  --
}

ssas.model_json_312_tables_measures_T <.. ssas.model_json_3121_tables_columns_descriptions_multiline
ssas.model_json_3121_tables_columns_descriptions_multiline <.. ssas.model_json_31211_tables_columns_descriptions_StrAgg
"ssas.model_json_312_tables_measures_T::databasename" <-- "ssas.model_json_3121_tables_columns_descriptions_multiline::databasename"
"ssas.model_json_312_tables_measures_T::Measure_guid" <-- "ssas.model_json_3121_tables_columns_descriptions_multiline::Measure_guid"
"ssas.model_json_312_tables_measures_T::RepoObject_guid" <-- "ssas.model_json_3121_tables_columns_descriptions_multiline::RepoObject_guid"
"ssas.model_json_312_tables_measures_T::tables_measures_name" <-- "ssas.model_json_3121_tables_columns_descriptions_multiline::tables_measures_name"
"ssas.model_json_312_tables_measures_T::tables_name" <-- "ssas.model_json_3121_tables_columns_descriptions_multiline::tables_name"
"ssas.model_json_3121_tables_columns_descriptions_multiline::databasename" <-- "ssas.model_json_31211_tables_columns_descriptions_StrAgg::databasename"
"ssas.model_json_3121_tables_columns_descriptions_multiline::Measure_guid" <-- "ssas.model_json_31211_tables_columns_descriptions_StrAgg::Measure_guid"
"ssas.model_json_3121_tables_columns_descriptions_multiline::RepoObject_guid" <-- "ssas.model_json_31211_tables_columns_descriptions_StrAgg::RepoObject_guid"
"ssas.model_json_3121_tables_columns_descriptions_multiline::tables_measures_name" <-- "ssas.model_json_31211_tables_columns_descriptions_StrAgg::tables_measures_name"
"ssas.model_json_3121_tables_columns_descriptions_multiline::tables_name" <-- "ssas.model_json_31211_tables_columns_descriptions_StrAgg::tables_name"
@enduml

