@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssas.model_json_31_tables_t.adoc[]" as ssas.model_json_31_tables_T << U >> {
  - **databasename** : (nvarchar(128))
  **tables_name** : (nvarchar(128))
  - RepoObject_guid : (uniqueidentifier)
  tables_annotations_ja : (nvarchar(max))
  tables_columns_ja : (nvarchar(max))
  tables_dataCategory : (nvarchar(500))
  tables_description : (nvarchar(max))
  tables_description_ja : (nvarchar(max))
  tables_hierarchies_ja : (nvarchar(max))
  tables_isHidden : (bit)
  tables_measures_ja : (nvarchar(max))
  tables_partitions_ja : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_313_tables_partitions.adoc[]" as ssas.model_json_313_tables_partitions << V >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  **tables_partitions_name** : (nvarchar(500))
  - RepoObject_guid : (uniqueidentifier)
  tables_partitions_annotations_ja : (nvarchar(max))
  tables_partitions_dataView : (nvarchar(500))
  tables_partitions_mode : (nvarchar(500))
  tables_partitions_source_j : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_3131_tables_partitions_source.adoc[]" as ssas.model_json_3131_tables_partitions_source << V >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  **tables_partitions_name** : (nvarchar(500))
  **tables_partitions_source_name** : (nvarchar(500))
  - RepoObject_guid : (uniqueidentifier)
  tables_partitions_source_dataSource : (nvarchar(500))
  tables_partitions_source_expression : (nvarchar(max))
  tables_partitions_source_query : (nvarchar(max))
  tables_partitions_source_query_ja : (nvarchar(max))
  tables_partitions_source_type : (nvarchar(500))
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_3132_tables_partitions_posfrom.adoc[]" as ssas.model_json_3132_tables_partitions_PosFrom << V >> {
  - databasename : (nvarchar(128))
  PosFrom : (bigint)
  PosFromDoublequota : (bigint)
  PosFromWhere : (bigint)
  - RepoObject_guid : (uniqueidentifier)
  - tables_name : (nvarchar(128))
  tables_partitions_annotations_ja : (nvarchar(max))
  tables_partitions_dataView : (nvarchar(500))
  tables_partitions_mode : (nvarchar(500))
  tables_partitions_name : (nvarchar(500))
  tables_partitions_source_j : (nvarchar(max))
  --
}

ssas.model_json_31_tables_T <.. ssas.model_json_313_tables_partitions
ssas.model_json_313_tables_partitions <.. ssas.model_json_3131_tables_partitions_source
ssas.model_json_313_tables_partitions <.. ssas.model_json_3132_tables_partitions_PosFrom
"ssas.model_json_31_tables_T::databasename" <-- "ssas.model_json_313_tables_partitions::databasename"
"ssas.model_json_31_tables_T::RepoObject_guid" <-- "ssas.model_json_313_tables_partitions::RepoObject_guid"
"ssas.model_json_31_tables_T::tables_name" <-- "ssas.model_json_313_tables_partitions::tables_name"
"ssas.model_json_313_tables_partitions::databasename" <-- "ssas.model_json_3131_tables_partitions_source::databasename"
"ssas.model_json_313_tables_partitions::databasename" <-- "ssas.model_json_3132_tables_partitions_PosFrom::databasename"
"ssas.model_json_313_tables_partitions::RepoObject_guid" <-- "ssas.model_json_3132_tables_partitions_PosFrom::RepoObject_guid"
"ssas.model_json_313_tables_partitions::RepoObject_guid" <-- "ssas.model_json_3131_tables_partitions_source::RepoObject_guid"
"ssas.model_json_313_tables_partitions::tables_name" <-- "ssas.model_json_3132_tables_partitions_PosFrom::tables_name"
"ssas.model_json_313_tables_partitions::tables_name" <-- "ssas.model_json_3131_tables_partitions_source::tables_name"
"ssas.model_json_313_tables_partitions::tables_partitions_annotations_ja" <-- "ssas.model_json_3132_tables_partitions_PosFrom::tables_partitions_annotations_ja"
"ssas.model_json_313_tables_partitions::tables_partitions_dataView" <-- "ssas.model_json_3132_tables_partitions_PosFrom::tables_partitions_dataView"
"ssas.model_json_313_tables_partitions::tables_partitions_mode" <-- "ssas.model_json_3132_tables_partitions_PosFrom::tables_partitions_mode"
"ssas.model_json_313_tables_partitions::tables_partitions_name" <-- "ssas.model_json_3132_tables_partitions_PosFrom::tables_partitions_name"
"ssas.model_json_313_tables_partitions::tables_partitions_name" <-- "ssas.model_json_3131_tables_partitions_source::tables_partitions_name"
"ssas.model_json_313_tables_partitions::tables_partitions_source_j" <-- "ssas.model_json_3132_tables_partitions_PosFrom::tables_partitions_source_j"footer The diagram is interactive and contains links.
@enduml

