@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:logs.usp_executionlog_insert.adoc[]" as logs.usp_ExecutionLog_insert << P >> {
  --
  --
  --
}

entity "puml-link:dhw:sqldb:repo.usp_sync_guid_ssas.adoc[]" as repo.usp_sync_guid_ssas << P >> {
  --
  --
  --
}

entity "puml-link:dhw:sqldb:ssas.measures_translation.adoc[]" as ssas.Measures_translation << V >> {
  - **Measure_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  **RepoObject_name** : (nvarchar(128))
  --
  Measure_DisplayName : (nvarchar(500))
  Measure_translation : (nvarchar(128))
  - measures_name : (nvarchar(500))
  - RepoSchema_name : (nvarchar(128))
  --
  --
}

entity "puml-link:dhw:sqldb:ssas.measures_translation_t.adoc[]" as ssas.Measures_translation_T << U >> {
  - **Measure_guid** : (uniqueidentifier)
  - **cultures_name** : (nvarchar(10))
  **RepoObject_name** : (nvarchar(128))
  --
  Measure_DisplayName : (nvarchar(500))
  Measure_translation : (nvarchar(128))
  - measures_name : (nvarchar(500))
  - RepoSchema_name : (nvarchar(128))
  --
  --
}

entity "puml-link:dhw:sqldb:ssas.usp_persist_measures_translation_t.adoc[]" as ssas.usp_PERSIST_Measures_translation_T << P >> {
  --
  --
  --
}

logs.usp_ExecutionLog_insert <.. ssas.usp_PERSIST_Measures_translation_T
ssas.Measures_translation <.. ssas.usp_PERSIST_Measures_translation_T
ssas.Measures_translation_T <.. ssas.usp_PERSIST_Measures_translation_T
ssas.usp_PERSIST_Measures_translation_T <.. repo.usp_sync_guid_ssas

@enduml

