@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity "[[{site-url}/{page-component-name}/current/{page-module}/ssas.model_json_34_cultures.html ssas.model_json_34_cultures]]" as ssas.model_json_34_cultures << V >> {
  - **databasename** : (nvarchar(128))
  **cultures_name** : (nvarchar(500))
  --
  cultures_translations_j : (nvarchar(max))
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/ssas.model_json_341_cultures_translations.html ssas.model_json_341_cultures_translations]]" as ssas.model_json_341_cultures_translations << V >> {
  --
  cultures_name : (nvarchar(500))
  cultures_translations_model_j : (nvarchar(max))
  - databasename : (nvarchar(128))
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/ssas.model_json_3411_cultures_translations_model.html ssas.model_json_3411_cultures_translations_model]]" as ssas.model_json_3411_cultures_translations_model << V >> {
  - **databasename** : (nvarchar(128))
  **cultures_name** : (nvarchar(500))
  **cultures_translations_model_name** : (nvarchar(500))
  --
  cultures_translations_model_perspectives_ja : (nvarchar(max))
  cultures_translations_model_tables_ja : (nvarchar(max))
  cultures_translations_model_translatedDescription : (nvarchar(max))
  --
  --
}

ssas.model_json_34_cultures <.. ssas.model_json_341_cultures_translations
ssas.model_json_341_cultures_translations <.. ssas.model_json_3411_cultures_translations_model
ssas.model_json_34_cultures::cultures_name <-- ssas.model_json_341_cultures_translations::cultures_name
ssas.model_json_34_cultures::databasename <-- ssas.model_json_341_cultures_translations::databasename
ssas.model_json_341_cultures_translations::cultures_name <-- ssas.model_json_3411_cultures_translations_model::cultures_name
ssas.model_json_341_cultures_translations::databasename <-- ssas.model_json_3411_cultures_translations_model::databasename
footer
to view a reduced diagram in original size and to be able to click on the links:
open the diagram in a new tab via the Context menu.
end footer

@enduml

