@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity "[[{site-url}/{page-component-name}/current/{page-module}/ssas.model_json_20.html ssas.model_json_20]]" as ssas.model_json_20 << V >> {
  - **databasename** : (nvarchar(128))
  --
  l1_compatibilityLevel : (int)
  l1_id : (nvarchar(500))
  l1_name : (nvarchar(500))
  l2_annotations_ja : (nvarchar(max))
  l2_culture : (nvarchar(500))
  l2_cultures_ja : (nvarchar(max))
  l2_dataSources_ja : (nvarchar(max))
  l2_description : (nvarchar(max))
  l2_description_ja : (nvarchar(max))
  l2_name : (nvarchar(500))
  l2_perspectives_ja : (nvarchar(max))
  l2_relationships_ja : (nvarchar(max))
  l2_roles_ja : (nvarchar(max))
  l2_tables_ja : (nvarchar(max))
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/ssas.model_json_32_relationships.html ssas.model_json_32_relationships]]" as ssas.model_json_32_relationships << V >> {
  - **databasename** : (nvarchar(128))
  **relationships_name** : (nvarchar(500))
  --
  relationships_crossFilteringBehavior : (nvarchar(500))
  relationships_fromCardinality : (nvarchar(500))
  relationships_fromColumn : (nvarchar(500))
  relationships_fromTable : (nvarchar(500))
  relationships_isActive : (bit)
  relationships_toCardinality : (nvarchar(500))
  relationships_toColumn : (nvarchar(500))
  relationships_toTable : (nvarchar(500))
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/ssas.model_json_32_relationships_T.html ssas.model_json_32_relationships_T]]" as ssas.model_json_32_relationships_T << U >> {
  - **ForeignKey_guid** : (uniqueidentifier)
  --
  - databasename : (nvarchar(128))
  relationships_crossFilteringBehavior : (nvarchar(500))
  relationships_fromCardinality : (nvarchar(500))
  relationships_fromColumn : (nvarchar(500))
  relationships_fromTable : (nvarchar(500))
  relationships_isActive : (bit)
  relationships_name : (nvarchar(500))
  relationships_toCardinality : (nvarchar(500))
  relationships_toColumn : (nvarchar(500))
  relationships_toTable : (nvarchar(500))
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/ssas.usp_PERSIST_model_json_32_relationships_T.html ssas.usp_PERSIST_model_json_32_relationships_T]]" as ssas.usp_PERSIST_model_json_32_relationships_T << P >> {
  --
  --
  --
}

ssas.model_json_20 <.. ssas.model_json_32_relationships
ssas.model_json_32_relationships <.. ssas.model_json_32_relationships_T
ssas.model_json_32_relationships <.. ssas.usp_PERSIST_model_json_32_relationships_T
ssas.model_json_20::databasename <-- ssas.model_json_32_relationships::databasename
ssas.model_json_32_relationships::databasename <-- ssas.model_json_32_relationships_T::databasename
ssas.model_json_32_relationships::relationships_crossFilteringBehavior <-- ssas.model_json_32_relationships_T::relationships_crossFilteringBehavior
ssas.model_json_32_relationships::relationships_fromCardinality <-- ssas.model_json_32_relationships_T::relationships_fromCardinality
ssas.model_json_32_relationships::relationships_fromColumn <-- ssas.model_json_32_relationships_T::relationships_fromColumn
ssas.model_json_32_relationships::relationships_fromTable <-- ssas.model_json_32_relationships_T::relationships_fromTable
ssas.model_json_32_relationships::relationships_isActive <-- ssas.model_json_32_relationships_T::relationships_isActive
ssas.model_json_32_relationships::relationships_name <-- ssas.model_json_32_relationships_T::relationships_name
ssas.model_json_32_relationships::relationships_toCardinality <-- ssas.model_json_32_relationships_T::relationships_toCardinality
ssas.model_json_32_relationships::relationships_toColumn <-- ssas.model_json_32_relationships_T::relationships_toColumn
ssas.model_json_32_relationships::relationships_toTable <-- ssas.model_json_32_relationships_T::relationships_toTable
footer
to view a reduced diagram in original size and to be able to click on the links:
open the diagram in a new tab via the Context menu.
end footer

@enduml

