@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity "[[{site-url}/{page-component-name}/current/{page-module}/ssas.model_json.html ssas.model_json]]" as ssas.model_json << U >> {
  - **databasename** : (nvarchar(128))
  --
  - model_filename : (nvarchar(4000))
  model_utf8 : (varchar(max))
  # isModelJson : (int)
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/ssas.model_json_10.html ssas.model_json_10]]" as ssas.model_json_10 << V >> {
  - **databasename** : (nvarchar(128))
  --
  l1_compatibilityLevel : (int)
  l1_id : (nvarchar(500))
  l1_model_j : (nvarchar(max))
  l1_name : (nvarchar(500))
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/ssas.model_json_ImportModelSql.html ssas.model_json_ImportModelSql]]" as ssas.model_json_ImportModelSql << V >> {
  --
  - databasename : (nvarchar(128))
  - ImportModelSql : (nvarchar(4000))
  isModelJson : (int)
  - model_filename : (nvarchar(4000))
  model_utf8 : (varchar(max))
  --
  --
}

ssas.model_json <.. ssas.model_json_10
ssas.model_json <.. ssas.model_json_ImportModelSql
ssas.model_json::databasename <-- ssas.model_json_ImportModelSql::databasename
ssas.model_json::databasename <-- ssas.model_json_10::databasename
ssas.model_json::isModelJson <-- ssas.model_json_ImportModelSql::isModelJson
ssas.model_json::model_filename <-- ssas.model_json_ImportModelSql::model_filename
ssas.model_json::model_utf8 <-- ssas.model_json::isModelJson
ssas.model_json::model_utf8 <-- ssas.model_json_ImportModelSql::model_utf8
footer
to view a reduced diagram in original size and to be able to click on the links:
open the diagram in a new tab via the Context menu.
end footer

@enduml

