@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity "puml-link:ssas.TMSCHEMA_RELATIONSHIPS.adoc[prefix=..]" as ssas.TMSCHEMA_RELATIONSHIPS << U >> {
  - **databasename** : (nvarchar(128))
  - **ID** : (numeric(20, 0))
  --
  - CrossFilteringBehavior : (bigint)
  - FromCardinality : (bigint)
  - FromColumnID : (numeric(20, 0))
  - FromTableID : (numeric(20, 0))
  - IsActive : (bit)
  - JoinOnDateBehavior : (bigint)
  - ModelID : (numeric(20, 0))
  - ModifiedTime : (datetime)
  - Name : (nvarchar(max))
  RefreshedTime : (datetime)
  RelationshipStorage2ID : (numeric(20, 0))
  RelationshipStorageID : (numeric(20, 0))
  - RelyOnReferentialIntegrity : (bit)
  - SecurityFilteringBehavior : (bigint)
  - State : (bigint)
  - ToCardinality : (bigint)
  - ToColumnID : (numeric(20, 0))
  - ToTableID : (numeric(20, 0))
  - Type : (bigint)
  --
  --
}

entity "puml-link:ssas.TMSCHEMA_RELATIONSHIPS_T.adoc[prefix=..]" as ssas.TMSCHEMA_RELATIONSHIPS_T << U >> {
  - **databasename** : (nvarchar(128))
  - **ID** : (numeric(20, 0))
  --
  - CrossFilteringBehavior : (bigint)
  - ForeignKey_guid : (uniqueidentifier)
  - FromCardinality : (bigint)
  - FromColumnID : (numeric(20, 0))
  - FromTableID : (numeric(20, 0))
  - IsActive : (bit)
  - JoinOnDateBehavior : (bigint)
  - ModelID : (numeric(20, 0))
  - ModifiedTime : (datetime)
  - Name : (nvarchar(max))
  RefreshedTime : (datetime)
  RelationshipStorage2ID : (numeric(20, 0))
  RelationshipStorageID : (numeric(20, 0))
  - RelyOnReferentialIntegrity : (bit)
  - SecurityFilteringBehavior : (bigint)
  - State : (bigint)
  - ToCardinality : (bigint)
  - ToColumnID : (numeric(20, 0))
  - ToTableID : (numeric(20, 0))
  - Type : (bigint)
  --
  --
}

entity "puml-link:ssas.usp_PERSIST_TMSCHEMA_RELATIONSHIPS_T.adoc[prefix=..]" as ssas.usp_PERSIST_TMSCHEMA_RELATIONSHIPS_T << P >> {
  --
  --
  --
}

ssas.TMSCHEMA_RELATIONSHIPS <.. ssas.TMSCHEMA_RELATIONSHIPS_T
ssas.TMSCHEMA_RELATIONSHIPS <.. ssas.usp_PERSIST_TMSCHEMA_RELATIONSHIPS_T
ssas.TMSCHEMA_RELATIONSHIPS::CrossFilteringBehavior <-- ssas.TMSCHEMA_RELATIONSHIPS_T::CrossFilteringBehavior
ssas.TMSCHEMA_RELATIONSHIPS::databasename <-- ssas.TMSCHEMA_RELATIONSHIPS_T::databasename
ssas.TMSCHEMA_RELATIONSHIPS::FromCardinality <-- ssas.TMSCHEMA_RELATIONSHIPS_T::FromCardinality
ssas.TMSCHEMA_RELATIONSHIPS::FromColumnID <-- ssas.TMSCHEMA_RELATIONSHIPS_T::FromColumnID
ssas.TMSCHEMA_RELATIONSHIPS::FromTableID <-- ssas.TMSCHEMA_RELATIONSHIPS_T::FromTableID
ssas.TMSCHEMA_RELATIONSHIPS::ID <-- ssas.TMSCHEMA_RELATIONSHIPS_T::ID
ssas.TMSCHEMA_RELATIONSHIPS::IsActive <-- ssas.TMSCHEMA_RELATIONSHIPS_T::IsActive
ssas.TMSCHEMA_RELATIONSHIPS::JoinOnDateBehavior <-- ssas.TMSCHEMA_RELATIONSHIPS_T::JoinOnDateBehavior
ssas.TMSCHEMA_RELATIONSHIPS::ModelID <-- ssas.TMSCHEMA_RELATIONSHIPS_T::ModelID
ssas.TMSCHEMA_RELATIONSHIPS::ModifiedTime <-- ssas.TMSCHEMA_RELATIONSHIPS_T::ModifiedTime
ssas.TMSCHEMA_RELATIONSHIPS::Name <-- ssas.TMSCHEMA_RELATIONSHIPS_T::Name
ssas.TMSCHEMA_RELATIONSHIPS::RefreshedTime <-- ssas.TMSCHEMA_RELATIONSHIPS_T::RefreshedTime
ssas.TMSCHEMA_RELATIONSHIPS::RelationshipStorage2ID <-- ssas.TMSCHEMA_RELATIONSHIPS_T::RelationshipStorage2ID
ssas.TMSCHEMA_RELATIONSHIPS::RelationshipStorageID <-- ssas.TMSCHEMA_RELATIONSHIPS_T::RelationshipStorageID
ssas.TMSCHEMA_RELATIONSHIPS::RelyOnReferentialIntegrity <-- ssas.TMSCHEMA_RELATIONSHIPS_T::RelyOnReferentialIntegrity
ssas.TMSCHEMA_RELATIONSHIPS::SecurityFilteringBehavior <-- ssas.TMSCHEMA_RELATIONSHIPS_T::SecurityFilteringBehavior
ssas.TMSCHEMA_RELATIONSHIPS::State <-- ssas.TMSCHEMA_RELATIONSHIPS_T::State
ssas.TMSCHEMA_RELATIONSHIPS::ToCardinality <-- ssas.TMSCHEMA_RELATIONSHIPS_T::ToCardinality
ssas.TMSCHEMA_RELATIONSHIPS::ToColumnID <-- ssas.TMSCHEMA_RELATIONSHIPS_T::ToColumnID
ssas.TMSCHEMA_RELATIONSHIPS::ToTableID <-- ssas.TMSCHEMA_RELATIONSHIPS_T::ToTableID
ssas.TMSCHEMA_RELATIONSHIPS::Type <-- ssas.TMSCHEMA_RELATIONSHIPS_T::Type
footer
to view a reduced diagram in original size and to be able to click on the links:
open the diagram in a new tab via the Context menu.
end footer

@enduml

