@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity "[[{site-url}/{page-component-name}/current/{page-module}/repo.ForeignKey_ssas_IndexPattern.html repo.ForeignKey_ssas_IndexPattern]]" as repo.ForeignKey_ssas_IndexPattern << V >> {
  --
  - databasename : (nvarchar(128))
  delete_referential_action : (tinyint)
  ForeignKey_fullname : (nvarchar(517))
  - ForeignKey_guid : (uniqueidentifier)
  ForeignKey_name : (nvarchar(263))
  referenced_ColumnName : (nvarchar(128))
  referenced_IndexPatternColumnDatatype : (nvarchar(500))
  referenced_IndexPatternColumnGuid : (varchar(36))
  referenced_IndexPatternColumnName : (nvarchar(128))
  - referenced_IsKey : (bit)
  - referenced_IsNullable : (bit)
  referenced_ObjectName : (nvarchar(128))
  referenced_RepoObject_fullname : (nvarchar(517))
  referenced_RepoObject_fullname2 : (nvarchar(257))
  referenced_RepoObject_guid : (uniqueidentifier)
  referencing_ColumnName : (nvarchar(128))
  referencing_IndexPatternColumnDatatype : (nvarchar(500))
  referencing_IndexPatternColumnGuid : (varchar(36))
  referencing_IndexPatternColumnName : (nvarchar(128))
  - referencing_IsKey : (bit)
  - referencing_IsNullable : (bit)
  referencing_ObjectName : (nvarchar(128))
  referencing_RepoObject_fullname : (nvarchar(517))
  referencing_RepoObject_fullname2 : (nvarchar(257))
  referencing_RepoObject_guid : (uniqueidentifier)
  relationships_crossFilteringBehavior : (nvarchar(500))
  relationships_fromCardinality : (nvarchar(500))
  - relationships_isActive : (bit)
  relationships_name : (nvarchar(500))
  relationships_toCardinality : (nvarchar(500))
  update_referential_action : (tinyint)
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/repo.RepoObject_gross.html repo.RepoObject_gross]]" as repo.RepoObject_gross << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
  Description : (nvarchar(max))
  has_different_sys_names : (bit)
  has_execution_plan_issue : (bit)
  has_get_referenced_issue : (bit)
  has_history : (bit)
  has_history_columns : (bit)
  history_schema_name : (nvarchar(128))
  history_table_name : (nvarchar(128))
  Inheritance_StringAggSeparatorSql : (nvarchar(4000))
  InheritanceDefinition : (nvarchar(4000))
  InheritanceType : (tinyint)
  - is_DocsExclude : (bit)
  is_DocsOutput : (int)
  - is_in_reference : (int)
  is_persistence : (bit)
  is_persistence_check_duplicate_per_pk : (bit)
  is_persistence_check_for_empty_source : (bit)
  is_persistence_delete_changed : (bit)
  is_persistence_delete_missing : (bit)
  is_persistence_insert : (bit)
  is_persistence_merge_delete_missing : (bit)
  is_persistence_merge_insert : (bit)
  is_persistence_merge_update_changed : (bit)
  is_persistence_truncate : (bit)
  is_persistence_update_changed : (bit)
  is_repo_managed : (bit)
  - is_RepoObject_name_uniqueidentifier : (int)
  is_required_ObjectMerge : (bit)
  - is_ssas : (bit)
  is_SysObject_missing : (bit)
  - is_SysObject_name_uniqueidentifier : (int)
  - modify_dt : (datetime)
  node_id : (bigint)
  persistence_source_RepoObject_fullname : (nvarchar(261))
  persistence_source_RepoObject_fullname2 : (nvarchar(257))
  persistence_source_RepoObject_guid : (uniqueidentifier)
  persistence_source_RepoObject_xref : (nvarchar(269))
  persistence_source_SysObject_fullname : (nvarchar(261))
  persistence_source_SysObject_fullname2 : (nvarchar(257))
  persistence_source_SysObject_xref : (nvarchar(269))
  pk_index_guid : (uniqueidentifier)
  pk_IndexPatternColumnDatatype : (nvarchar(4000))
  pk_IndexPatternColumnName : (nvarchar(4000))
  pk_IndexPatternColumnName_new : (nvarchar(4000))
  pk_IndexSemanticGroup : (nvarchar(512))
  Property_ms_description : (nvarchar(4000))
  Repo_history_table_guid : (uniqueidentifier)
  Repo_temporal_type : (tinyint)
  - RepoObject_fullname : (nvarchar(261))
  - RepoObject_fullname2 : (nvarchar(257))
  - RepoObject_name : (nvarchar(128))
  RepoObject_Referencing_Count : (int)
  - RepoObject_schema_name : (nvarchar(128))
  - RepoObject_type : (char(2))
  RepoObject_type_name : (nvarchar(128))
  source_filter : (nvarchar(4000))
  - SysObject_fullname : (nvarchar(261))
  - SysObject_fullname2 : (nvarchar(257))
  SysObject_id : (int)
  SysObject_modify_date : (datetime)
  - SysObject_name : (nvarchar(128))
  - SysObject_parent_object_id : (int)
  SysObject_query_executed_dt : (datetime)
  SysObject_query_plan : (xml)
  - SysObject_query_sql : (nvarchar(406))
  - SysObject_schema_name : (nvarchar(128))
  SysObject_type : (char(2))
  SysObject_type_name : (nvarchar(128))
  tables_dataCategory : (nvarchar(500))
  tables_description : (nvarchar(max))
  tables_isHidden : (nvarchar(500))
  target_filter : (nvarchar(4000))
  temporal_type : (tinyint)
  - usp_persistence_name : (nvarchar(140))
  usp_persistence_RepoObject_guid : (uniqueidentifier)
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/repo.RepoObject_SSAS_src.html repo.RepoObject_SSAS_src]]" as repo.RepoObject_SSAS_src << V >> {
  - **RepoObject_guid** : (uniqueidentifier)
  --
  - is_repo_managed : (int)
  - is_ssas : (int)
  - RepoObject_name : (nvarchar(128))
  - RepoObject_schema_name : (nvarchar(128))
  - RepoObject_type : (varchar(1))
  - SysObject_name : (nvarchar(128))
  - SysObject_schema_name : (nvarchar(128))
  - SysObject_type : (varchar(1))
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/ssas.model_json_31_tables.html ssas.model_json_31_tables]]" as ssas.model_json_31_tables << V >> {
  - **databasename** : (nvarchar(128))
  **tables_name** : (nvarchar(128))
  --
  tables_annotations_ja : (nvarchar(max))
  tables_columns_ja : (nvarchar(max))
  tables_dataCategory : (nvarchar(500))
  tables_description : (nvarchar(max))
  tables_description_ja : (nvarchar(max))
  tables_hierarchies_ja : (nvarchar(max))
  tables_isHidden : (nvarchar(500))
  tables_measures_ja : (nvarchar(max))
  tables_partitions_ja : (nvarchar(max))
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/ssas.model_json_31_tables_T.html ssas.model_json_31_tables_T]]" as ssas.model_json_31_tables_T << U >> {
  - **databasename** : (nvarchar(128))
  **tables_name** : (nvarchar(128))
  --
  - RepoObject_guid : (uniqueidentifier)
  tables_annotations_ja : (nvarchar(max))
  tables_columns_ja : (nvarchar(max))
  tables_dataCategory : (nvarchar(500))
  tables_description : (nvarchar(max))
  tables_description_ja : (nvarchar(max))
  tables_hierarchies_ja : (nvarchar(max))
  tables_isHidden : (nvarchar(500))
  tables_measures_ja : (nvarchar(max))
  tables_partitions_ja : (nvarchar(max))
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/ssas.model_json_311_tables_columns.html ssas.model_json_311_tables_columns]]" as ssas.model_json_311_tables_columns << V >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  **tables_columns_name** : (nvarchar(128))
  --
  - RepoObject_guid : (uniqueidentifier)
  tables_columns_dataType : (nvarchar(500))
  tables_columns_description : (nvarchar(max))
  tables_columns_description_ja : (nvarchar(max))
  tables_columns_displayFolder : (nvarchar(500))
  tables_columns_expression : (nvarchar(max))
  tables_columns_expression_ja : (nvarchar(max))
  tables_columns_formatString : (nvarchar(500))
  tables_columns_isDataTypeInferred : (bit)
  tables_columns_isHidden : (bit)
  tables_columns_isKey : (bit)
  tables_columns_isNameInferred : (bit)
  tables_columns_isNullable : (bit)
  tables_columns_isUnique : (bit)
  tables_columns_keepUniqueRows : (bit)
  tables_columns_sortByColumn : (nvarchar(500))
  tables_columns_sourceColumn : (nvarchar(500))
  tables_columns_sourceProviderType : (nvarchar(500))
  tables_columns_summarizeBy : (nvarchar(500))
  tables_columns_type : (nvarchar(500))
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/ssas.model_json_312_tables_measures.html ssas.model_json_312_tables_measures]]" as ssas.model_json_312_tables_measures << V >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  **tables_measures_name** : (nvarchar(500))
  --
  - RepoObject_guid : (uniqueidentifier)
  tables_measures_description : (nvarchar(max))
  tables_measures_description_ja : (nvarchar(max))
  tables_measures_displayFolder : (nvarchar(500))
  tables_measures_expression : (nvarchar(max))
  tables_measures_expression_ja : (nvarchar(max))
  tables_measures_formatString : (nvarchar(500))
  tables_measures_isHidden : (bit)
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/ssas.model_json_313_tables_partitions.html ssas.model_json_313_tables_partitions]]" as ssas.model_json_313_tables_partitions << V >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  **tables_partitions_name** : (nvarchar(500))
  --
  - RepoObject_guid : (uniqueidentifier)
  tables_partitions_annotations_ja : (nvarchar(max))
  tables_partitions_dataView : (nvarchar(500))
  tables_partitions_mode : (nvarchar(500))
  tables_partitions_source_j : (nvarchar(max))
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/ssas.model_json_314_tables_hierarchies.html ssas.model_json_314_tables_hierarchies]]" as ssas.model_json_314_tables_hierarchies << V >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  **tables_hierarchies_name** : (nvarchar(500))
  --
  - RepoObject_guid : (uniqueidentifier)
  tables_hierarchies_levels_ja : (nvarchar(max))
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/ssas.model_json_315_tables_annotations.html ssas.model_json_315_tables_annotations]]" as ssas.model_json_315_tables_annotations << V >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  **tables_annotations_name** : (nvarchar(500))
  --
  - RepoObject_guid : (uniqueidentifier)
  tables_annotations_value : (nvarchar(max))
  tables_annotations_value_ja : (nvarchar(max))
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/ssas.model_json_316_tables_descriptions_multiline.html ssas.model_json_316_tables_descriptions_multiline]]" as ssas.model_json_316_tables_descriptions_multiline << V >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  --
  - Key : (nvarchar(4000))
  - RepoObject_guid : (uniqueidentifier)
  - Type : (tinyint)
  Value : (nvarchar(max))
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/ssas.usp_PERSIST_model_json_31_tables_T.html ssas.usp_PERSIST_model_json_31_tables_T]]" as ssas.usp_PERSIST_model_json_31_tables_T << P >> {
  --
  --
  --
}

ssas.model_json_31_tables <.. ssas.model_json_31_tables_T
ssas.model_json_31_tables_T <.. repo.RepoObject_SSAS_src
ssas.model_json_31_tables_T <.. repo.RepoObject_gross
ssas.model_json_31_tables_T <.. ssas.model_json_315_tables_annotations
ssas.model_json_31_tables_T <.. ssas.usp_PERSIST_model_json_31_tables_T
ssas.model_json_31_tables_T <.. ssas.model_json_314_tables_hierarchies
ssas.model_json_31_tables_T <.. ssas.model_json_316_tables_descriptions_multiline
ssas.model_json_31_tables_T <.. ssas.model_json_313_tables_partitions
ssas.model_json_31_tables_T <.. ssas.model_json_312_tables_measures
ssas.model_json_31_tables_T <.. ssas.model_json_311_tables_columns
ssas.model_json_31_tables_T <.. repo.ForeignKey_ssas_IndexPattern
ssas.model_json_31_tables::databasename <-- ssas.model_json_31_tables_T::databasename
ssas.model_json_31_tables::tables_annotations_ja <-- ssas.model_json_31_tables_T::tables_annotations_ja
ssas.model_json_31_tables::tables_columns_ja <-- ssas.model_json_31_tables_T::tables_columns_ja
ssas.model_json_31_tables::tables_dataCategory <-- ssas.model_json_31_tables_T::tables_dataCategory
ssas.model_json_31_tables::tables_description <-- ssas.model_json_31_tables_T::tables_description
ssas.model_json_31_tables::tables_description_ja <-- ssas.model_json_31_tables_T::tables_description_ja
ssas.model_json_31_tables::tables_hierarchies_ja <-- ssas.model_json_31_tables_T::tables_hierarchies_ja
ssas.model_json_31_tables::tables_isHidden <-- ssas.model_json_31_tables_T::tables_isHidden
ssas.model_json_31_tables::tables_measures_ja <-- ssas.model_json_31_tables_T::tables_measures_ja
ssas.model_json_31_tables::tables_name <-- ssas.model_json_31_tables_T::tables_name
ssas.model_json_31_tables::tables_partitions_ja <-- ssas.model_json_31_tables_T::tables_partitions_ja
ssas.model_json_31_tables_T::databasename <-- repo.RepoObject_SSAS_src::RepoObject_schema_name
ssas.model_json_31_tables_T::databasename <-- repo.RepoObject_SSAS_src::SysObject_schema_name
ssas.model_json_31_tables_T::databasename <-- ssas.model_json_311_tables_columns::databasename
ssas.model_json_31_tables_T::databasename <-- ssas.model_json_312_tables_measures::databasename
ssas.model_json_31_tables_T::databasename <-- ssas.model_json_313_tables_partitions::databasename
ssas.model_json_31_tables_T::databasename <-- ssas.model_json_314_tables_hierarchies::databasename
ssas.model_json_31_tables_T::databasename <-- ssas.model_json_315_tables_annotations::databasename
ssas.model_json_31_tables_T::databasename <-- ssas.model_json_316_tables_descriptions_multiline::databasename
ssas.model_json_31_tables_T::RepoObject_guid <-- repo.RepoObject_SSAS_src::RepoObject_guid
ssas.model_json_31_tables_T::RepoObject_guid <-- repo.ForeignKey_ssas_IndexPattern::referenced_RepoObject_guid
ssas.model_json_31_tables_T::RepoObject_guid <-- repo.ForeignKey_ssas_IndexPattern::referencing_RepoObject_guid
ssas.model_json_31_tables_T::RepoObject_guid <-- ssas.model_json_311_tables_columns::RepoObject_guid
ssas.model_json_31_tables_T::RepoObject_guid <-- ssas.model_json_312_tables_measures::RepoObject_guid
ssas.model_json_31_tables_T::RepoObject_guid <-- ssas.model_json_313_tables_partitions::RepoObject_guid
ssas.model_json_31_tables_T::RepoObject_guid <-- ssas.model_json_314_tables_hierarchies::RepoObject_guid
ssas.model_json_31_tables_T::RepoObject_guid <-- ssas.model_json_315_tables_annotations::RepoObject_guid
ssas.model_json_31_tables_T::RepoObject_guid <-- ssas.model_json_316_tables_descriptions_multiline::RepoObject_guid
ssas.model_json_31_tables_T::tables_dataCategory <-- repo.RepoObject_gross::tables_dataCategory
ssas.model_json_31_tables_T::tables_description <-- repo.RepoObject_gross::tables_description
ssas.model_json_31_tables_T::tables_isHidden <-- repo.RepoObject_gross::tables_isHidden
ssas.model_json_31_tables_T::tables_name <-- repo.RepoObject_SSAS_src::RepoObject_name
ssas.model_json_31_tables_T::tables_name <-- repo.RepoObject_SSAS_src::SysObject_name
ssas.model_json_31_tables_T::tables_name <-- repo.ForeignKey_ssas_IndexPattern::referenced_ObjectName
ssas.model_json_31_tables_T::tables_name <-- repo.ForeignKey_ssas_IndexPattern::referencing_ObjectName
ssas.model_json_31_tables_T::tables_name <-- ssas.model_json_311_tables_columns::tables_name
ssas.model_json_31_tables_T::tables_name <-- ssas.model_json_312_tables_measures::tables_name
ssas.model_json_31_tables_T::tables_name <-- ssas.model_json_313_tables_partitions::tables_name
ssas.model_json_31_tables_T::tables_name <-- ssas.model_json_314_tables_hierarchies::tables_name
ssas.model_json_31_tables_T::tables_name <-- ssas.model_json_315_tables_annotations::tables_name
ssas.model_json_31_tables_T::tables_name <-- ssas.model_json_316_tables_descriptions_multiline::tables_name
footer
to view a reduced diagram in original size and to be able to click on the links:
open the diagram in a new tab via the Context menu.
end footer

@enduml

