@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity "puml-link:ssas.model_json_20.adoc[prefix=..]" as ssas.model_json_20 << V >> {
  - **databasename** : (nvarchar(128))
  --
  l1_compatibilityLevel : (int)
  l1_id : (nvarchar(500))
  l1_name : (nvarchar(500))
  l2_annotations_ja : (nvarchar(max))
  l2_culture : (nvarchar(500))
  l2_cultures_ja : (nvarchar(max))
  l2_dataSources_ja : (nvarchar(max))
  l2_description : (nvarchar(max))
  l2_description_ja : (nvarchar(max))
  l2_name : (nvarchar(500))
  l2_perspectives_ja : (nvarchar(max))
  l2_relationships_ja : (nvarchar(max))
  l2_roles_ja : (nvarchar(max))
  l2_tables_ja : (nvarchar(max))
  --
  --
}

entity "puml-link:ssas.model_json_31_tables.adoc[prefix=..]" as ssas.model_json_31_tables << V >> {
  - **databasename** : (nvarchar(128))
  **tables_name** : (nvarchar(128))
  --
  tables_annotations_ja : (nvarchar(max))
  tables_columns_ja : (nvarchar(max))
  tables_dataCategory : (nvarchar(500))
  tables_description : (nvarchar(max))
  tables_description_ja : (nvarchar(max))
  tables_hierarchies_ja : (nvarchar(max))
  tables_isHidden : (nvarchar(500))
  tables_measures_ja : (nvarchar(max))
  tables_partitions_ja : (nvarchar(max))
  --
  --
}

entity "puml-link:ssas.model_json_31_tables_T.adoc[prefix=..]" as ssas.model_json_31_tables_T << U >> {
  - **databasename** : (nvarchar(128))
  **tables_name** : (nvarchar(128))
  --
  - RepoObject_guid : (uniqueidentifier)
  tables_annotations_ja : (nvarchar(max))
  tables_columns_ja : (nvarchar(max))
  tables_dataCategory : (nvarchar(500))
  tables_description : (nvarchar(max))
  tables_description_ja : (nvarchar(max))
  tables_hierarchies_ja : (nvarchar(max))
  tables_isHidden : (nvarchar(500))
  tables_measures_ja : (nvarchar(max))
  tables_partitions_ja : (nvarchar(max))
  --
  --
}

entity "puml-link:ssas.usp_PERSIST_model_json_31_tables_T.adoc[prefix=..]" as ssas.usp_PERSIST_model_json_31_tables_T << P >> {
  --
  --
  --
}

ssas.model_json_20 <.. ssas.model_json_31_tables
ssas.model_json_31_tables <.. ssas.model_json_31_tables_T
ssas.model_json_31_tables <.. ssas.usp_PERSIST_model_json_31_tables_T
ssas.model_json_20::databasename <-- ssas.model_json_31_tables::databasename
ssas.model_json_31_tables::databasename <-- ssas.model_json_31_tables_T::databasename
ssas.model_json_31_tables::tables_annotations_ja <-- ssas.model_json_31_tables_T::tables_annotations_ja
ssas.model_json_31_tables::tables_columns_ja <-- ssas.model_json_31_tables_T::tables_columns_ja
ssas.model_json_31_tables::tables_dataCategory <-- ssas.model_json_31_tables_T::tables_dataCategory
ssas.model_json_31_tables::tables_description <-- ssas.model_json_31_tables_T::tables_description
ssas.model_json_31_tables::tables_description_ja <-- ssas.model_json_31_tables_T::tables_description_ja
ssas.model_json_31_tables::tables_hierarchies_ja <-- ssas.model_json_31_tables_T::tables_hierarchies_ja
ssas.model_json_31_tables::tables_isHidden <-- ssas.model_json_31_tables_T::tables_isHidden
ssas.model_json_31_tables::tables_measures_ja <-- ssas.model_json_31_tables_T::tables_measures_ja
ssas.model_json_31_tables::tables_name <-- ssas.model_json_31_tables_T::tables_name
ssas.model_json_31_tables::tables_partitions_ja <-- ssas.model_json_31_tables_T::tables_partitions_ja
footer
to view a reduced diagram in original size and to be able to click on the links:
open the diagram in a new tab via the Context menu.
end footer

@enduml

