@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssas.model_json_31311_tables_partitions_source_posfrom.adoc[]" as ssas.model_json_31311_tables_partitions_source_PosFrom << V >> {
  --
  - databasename : (nvarchar(128))
  PosFrom : (bigint)
  PosFromWhere : (bigint)
  - RepoObject_guid : (uniqueidentifier)
  - tables_name : (nvarchar(128))
  tables_partitions_name : (nvarchar(500))
  tables_partitions_source_dataSource : (nvarchar(500))
  tables_partitions_source_expression : (nvarchar(max))
  tables_partitions_source_name : (nvarchar(500))
  tables_partitions_source_query : (nvarchar(max))
  tables_partitions_source_query_ja : (nvarchar(max))
  tables_partitions_source_type : (nvarchar(500))
  --
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_313111_tables_partitions_source_stringfrom.adoc[]" as ssas.model_json_313111_tables_partitions_source_StringFrom << V >> {
  --
  - databasename : (nvarchar(128))
  PosFrom : (bigint)
  PosFromWhere : (bigint)
  - RepoObject_guid : (uniqueidentifier)
  StringFrom : (nvarchar(max))
  - tables_name : (nvarchar(128))
  tables_partitions_name : (nvarchar(500))
  tables_partitions_source_dataSource : (nvarchar(500))
  tables_partitions_source_expression : (nvarchar(max))
  tables_partitions_source_name : (nvarchar(500))
  tables_partitions_source_query : (nvarchar(max))
  tables_partitions_source_query_ja : (nvarchar(max))
  tables_partitions_source_type : (nvarchar(500))
  --
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_3131111_tables_partitions_source_posdot.adoc[]" as ssas.model_json_3131111_tables_partitions_source_PosDot << V >> {
  --
  - databasename : (nvarchar(128))
  PosDot1 : (bigint)
  PosDot2 : (bigint)
  PosFrom : (bigint)
  PosFromWhere : (bigint)
  - RepoObject_guid : (uniqueidentifier)
  StringFrom : (nvarchar(max))
  - tables_name : (nvarchar(128))
  tables_partitions_name : (nvarchar(500))
  tables_partitions_source_dataSource : (nvarchar(500))
  tables_partitions_source_expression : (nvarchar(max))
  tables_partitions_source_name : (nvarchar(500))
  tables_partitions_source_query : (nvarchar(max))
  tables_partitions_source_query_ja : (nvarchar(max))
  tables_partitions_source_type : (nvarchar(500))
  --
  --
}

ssas.model_json_31311_tables_partitions_source_PosFrom <.. ssas.model_json_313111_tables_partitions_source_StringFrom
ssas.model_json_313111_tables_partitions_source_StringFrom <.. ssas.model_json_3131111_tables_partitions_source_PosDot
"ssas.model_json_31311_tables_partitions_source_PosFrom::databasename" <-- "ssas.model_json_313111_tables_partitions_source_StringFrom::databasename"
"ssas.model_json_31311_tables_partitions_source_PosFrom::PosFrom" <-- "ssas.model_json_313111_tables_partitions_source_StringFrom::PosFrom"
"ssas.model_json_31311_tables_partitions_source_PosFrom::PosFromWhere" <-- "ssas.model_json_313111_tables_partitions_source_StringFrom::PosFromWhere"
"ssas.model_json_31311_tables_partitions_source_PosFrom::RepoObject_guid" <-- "ssas.model_json_313111_tables_partitions_source_StringFrom::RepoObject_guid"
"ssas.model_json_31311_tables_partitions_source_PosFrom::tables_name" <-- "ssas.model_json_313111_tables_partitions_source_StringFrom::tables_name"
"ssas.model_json_31311_tables_partitions_source_PosFrom::tables_partitions_name" <-- "ssas.model_json_313111_tables_partitions_source_StringFrom::tables_partitions_name"
"ssas.model_json_31311_tables_partitions_source_PosFrom::tables_partitions_source_dataSource" <-- "ssas.model_json_313111_tables_partitions_source_StringFrom::tables_partitions_source_dataSource"
"ssas.model_json_31311_tables_partitions_source_PosFrom::tables_partitions_source_expression" <-- "ssas.model_json_313111_tables_partitions_source_StringFrom::tables_partitions_source_expression"
"ssas.model_json_31311_tables_partitions_source_PosFrom::tables_partitions_source_name" <-- "ssas.model_json_313111_tables_partitions_source_StringFrom::tables_partitions_source_name"
"ssas.model_json_31311_tables_partitions_source_PosFrom::tables_partitions_source_query" <-- "ssas.model_json_313111_tables_partitions_source_StringFrom::tables_partitions_source_query"
"ssas.model_json_31311_tables_partitions_source_PosFrom::tables_partitions_source_query_ja" <-- "ssas.model_json_313111_tables_partitions_source_StringFrom::tables_partitions_source_query_ja"
"ssas.model_json_31311_tables_partitions_source_PosFrom::tables_partitions_source_type" <-- "ssas.model_json_313111_tables_partitions_source_StringFrom::tables_partitions_source_type"
"ssas.model_json_313111_tables_partitions_source_StringFrom::databasename" <-- "ssas.model_json_3131111_tables_partitions_source_PosDot::databasename"
"ssas.model_json_313111_tables_partitions_source_StringFrom::PosFrom" <-- "ssas.model_json_3131111_tables_partitions_source_PosDot::PosFrom"
"ssas.model_json_313111_tables_partitions_source_StringFrom::PosFromWhere" <-- "ssas.model_json_3131111_tables_partitions_source_PosDot::PosFromWhere"
"ssas.model_json_313111_tables_partitions_source_StringFrom::RepoObject_guid" <-- "ssas.model_json_3131111_tables_partitions_source_PosDot::RepoObject_guid"
"ssas.model_json_313111_tables_partitions_source_StringFrom::StringFrom" <-- "ssas.model_json_3131111_tables_partitions_source_PosDot::StringFrom"
"ssas.model_json_313111_tables_partitions_source_StringFrom::tables_name" <-- "ssas.model_json_3131111_tables_partitions_source_PosDot::tables_name"
"ssas.model_json_313111_tables_partitions_source_StringFrom::tables_partitions_name" <-- "ssas.model_json_3131111_tables_partitions_source_PosDot::tables_partitions_name"
"ssas.model_json_313111_tables_partitions_source_StringFrom::tables_partitions_source_dataSource" <-- "ssas.model_json_3131111_tables_partitions_source_PosDot::tables_partitions_source_dataSource"
"ssas.model_json_313111_tables_partitions_source_StringFrom::tables_partitions_source_expression" <-- "ssas.model_json_3131111_tables_partitions_source_PosDot::tables_partitions_source_expression"
"ssas.model_json_313111_tables_partitions_source_StringFrom::tables_partitions_source_name" <-- "ssas.model_json_3131111_tables_partitions_source_PosDot::tables_partitions_source_name"
"ssas.model_json_313111_tables_partitions_source_StringFrom::tables_partitions_source_query" <-- "ssas.model_json_3131111_tables_partitions_source_PosDot::tables_partitions_source_query"
"ssas.model_json_313111_tables_partitions_source_StringFrom::tables_partitions_source_query_ja" <-- "ssas.model_json_3131111_tables_partitions_source_PosDot::tables_partitions_source_query_ja"
"ssas.model_json_313111_tables_partitions_source_StringFrom::tables_partitions_source_type" <-- "ssas.model_json_3131111_tables_partitions_source_PosDot::tables_partitions_source_type"
@enduml

