@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssas.tmschema_columns.adoc[]" as ssas.TMSCHEMA_COLUMNS << U >> {
  - **databasename** : (nvarchar(128))
  - **ID** : (numeric(20, 0))
  --
  - Alignment : (bigint)
  - AttributeHierarchyID : (numeric(20, 0))
  ColumnOriginID : (numeric(20, 0))
  - ColumnStorageID : (numeric(20, 0))
  DataCategory : (nvarchar(max))
  Description : (nvarchar(max))
  DisplayFolder : (nvarchar(max))
  - DisplayOrdinal : (int)
  ErrorMessage : (nvarchar(max))
  - ExplicitDataType : (bigint)
  - ExplicitName : (nvarchar(max))
  Expression : (nvarchar(max))
  FormatString : (nvarchar(max))
  - InferredDataType : (bigint)
  InferredName : (nvarchar(max))
  - IsAvailableInMDX : (bit)
  - IsDefaultImage : (bit)
  - IsDefaultLabel : (bit)
  - IsHidden : (bit)
  - IsKey : (bit)
  - IsNullable : (bit)
  - IsUnique : (bit)
  - KeepUniqueRows : (bit)
  - ModifiedTime : (datetime)
  RefreshedTime : (nvarchar(max))
  SortByColumnID : (numeric(20, 0))
  SourceColumn : (nvarchar(max))
  SourceProviderType : (nvarchar(max))
  - State : (bigint)
  - StructureModifiedTime : (datetime)
  - SummarizeBy : (bigint)
  - SystemFlags : (bigint)
  - TableDetailPosition : (int)
  - TableID : (numeric(20, 0))
  - Type : (bigint)
  --
  --
}

entity "puml-link:dhw:sqldb:ssas.tmschema_columns_t.adoc[]" as ssas.TMSCHEMA_COLUMNS_T << U >> {
  - **databasename** : (nvarchar(128))
  - **ID** : (numeric(20, 0))
  --
  - Alignment : (bigint)
  - AttributeHierarchyID : (numeric(20, 0))
  ColumnOriginID : (numeric(20, 0))
  - ColumnStorageID : (numeric(20, 0))
  DataCategory : (nvarchar(max))
  Description : (nvarchar(max))
  DisplayFolder : (nvarchar(max))
  - DisplayOrdinal : (int)
  ErrorMessage : (nvarchar(max))
  - ExplicitDataType : (bigint)
  - ExplicitName : (nvarchar(max))
  Expression : (nvarchar(max))
  FormatString : (nvarchar(max))
  - InferredDataType : (bigint)
  InferredName : (nvarchar(max))
  - IsAvailableInMDX : (bit)
  - IsDefaultImage : (bit)
  - IsDefaultLabel : (bit)
  - IsHidden : (bit)
  - IsKey : (bit)
  - IsNullable : (bit)
  - IsUnique : (bit)
  - KeepUniqueRows : (bit)
  - ModifiedTime : (datetime)
  RefreshedTime : (nvarchar(max))
  - RepoObjectColumn_guid : (uniqueidentifier)
  SortByColumnID : (numeric(20, 0))
  SourceColumn : (nvarchar(max))
  SourceProviderType : (nvarchar(max))
  - State : (bigint)
  - StructureModifiedTime : (datetime)
  - SummarizeBy : (bigint)
  - SystemFlags : (bigint)
  - TableDetailPosition : (int)
  - TableID : (numeric(20, 0))
  - Type : (bigint)
  --
  --
}

entity "puml-link:dhw:sqldb:ssas.usp_persist_tmschema_columns_t.adoc[]" as ssas.usp_PERSIST_TMSCHEMA_COLUMNS_T << P >> {
  --
  --
  --
}

ssas.TMSCHEMA_COLUMNS <.. ssas.TMSCHEMA_COLUMNS_T
ssas.TMSCHEMA_COLUMNS <.. ssas.usp_PERSIST_TMSCHEMA_COLUMNS_T
"ssas.TMSCHEMA_COLUMNS::Alignment" <-- "ssas.TMSCHEMA_COLUMNS_T::Alignment"
"ssas.TMSCHEMA_COLUMNS::AttributeHierarchyID" <-- "ssas.TMSCHEMA_COLUMNS_T::AttributeHierarchyID"
"ssas.TMSCHEMA_COLUMNS::ColumnOriginID" <-- "ssas.TMSCHEMA_COLUMNS_T::ColumnOriginID"
"ssas.TMSCHEMA_COLUMNS::ColumnStorageID" <-- "ssas.TMSCHEMA_COLUMNS_T::ColumnStorageID"
"ssas.TMSCHEMA_COLUMNS::databasename" <-- "ssas.TMSCHEMA_COLUMNS_T::databasename"
"ssas.TMSCHEMA_COLUMNS::DataCategory" <-- "ssas.TMSCHEMA_COLUMNS_T::DataCategory"
"ssas.TMSCHEMA_COLUMNS::Description" <-- "ssas.TMSCHEMA_COLUMNS_T::Description"
"ssas.TMSCHEMA_COLUMNS::DisplayFolder" <-- "ssas.TMSCHEMA_COLUMNS_T::DisplayFolder"
"ssas.TMSCHEMA_COLUMNS::DisplayOrdinal" <-- "ssas.TMSCHEMA_COLUMNS_T::DisplayOrdinal"
"ssas.TMSCHEMA_COLUMNS::ErrorMessage" <-- "ssas.TMSCHEMA_COLUMNS_T::ErrorMessage"
"ssas.TMSCHEMA_COLUMNS::ExplicitDataType" <-- "ssas.TMSCHEMA_COLUMNS_T::ExplicitDataType"
"ssas.TMSCHEMA_COLUMNS::ExplicitName" <-- "ssas.TMSCHEMA_COLUMNS_T::ExplicitName"
"ssas.TMSCHEMA_COLUMNS::Expression" <-- "ssas.TMSCHEMA_COLUMNS_T::Expression"
"ssas.TMSCHEMA_COLUMNS::FormatString" <-- "ssas.TMSCHEMA_COLUMNS_T::FormatString"
"ssas.TMSCHEMA_COLUMNS::ID" <-- "ssas.TMSCHEMA_COLUMNS_T::ID"
"ssas.TMSCHEMA_COLUMNS::InferredDataType" <-- "ssas.TMSCHEMA_COLUMNS_T::InferredDataType"
"ssas.TMSCHEMA_COLUMNS::InferredName" <-- "ssas.TMSCHEMA_COLUMNS_T::InferredName"
"ssas.TMSCHEMA_COLUMNS::IsAvailableInMDX" <-- "ssas.TMSCHEMA_COLUMNS_T::IsAvailableInMDX"
"ssas.TMSCHEMA_COLUMNS::IsDefaultImage" <-- "ssas.TMSCHEMA_COLUMNS_T::IsDefaultImage"
"ssas.TMSCHEMA_COLUMNS::IsDefaultLabel" <-- "ssas.TMSCHEMA_COLUMNS_T::IsDefaultLabel"
"ssas.TMSCHEMA_COLUMNS::IsHidden" <-- "ssas.TMSCHEMA_COLUMNS_T::IsHidden"
"ssas.TMSCHEMA_COLUMNS::IsKey" <-- "ssas.TMSCHEMA_COLUMNS_T::IsKey"
"ssas.TMSCHEMA_COLUMNS::IsNullable" <-- "ssas.TMSCHEMA_COLUMNS_T::IsNullable"
"ssas.TMSCHEMA_COLUMNS::IsUnique" <-- "ssas.TMSCHEMA_COLUMNS_T::IsUnique"
"ssas.TMSCHEMA_COLUMNS::KeepUniqueRows" <-- "ssas.TMSCHEMA_COLUMNS_T::KeepUniqueRows"
"ssas.TMSCHEMA_COLUMNS::ModifiedTime" <-- "ssas.TMSCHEMA_COLUMNS_T::ModifiedTime"
"ssas.TMSCHEMA_COLUMNS::RefreshedTime" <-- "ssas.TMSCHEMA_COLUMNS_T::RefreshedTime"
"ssas.TMSCHEMA_COLUMNS::SortByColumnID" <-- "ssas.TMSCHEMA_COLUMNS_T::SortByColumnID"
"ssas.TMSCHEMA_COLUMNS::SourceColumn" <-- "ssas.TMSCHEMA_COLUMNS_T::SourceColumn"
"ssas.TMSCHEMA_COLUMNS::SourceProviderType" <-- "ssas.TMSCHEMA_COLUMNS_T::SourceProviderType"
"ssas.TMSCHEMA_COLUMNS::State" <-- "ssas.TMSCHEMA_COLUMNS_T::State"
"ssas.TMSCHEMA_COLUMNS::StructureModifiedTime" <-- "ssas.TMSCHEMA_COLUMNS_T::StructureModifiedTime"
"ssas.TMSCHEMA_COLUMNS::SummarizeBy" <-- "ssas.TMSCHEMA_COLUMNS_T::SummarizeBy"
"ssas.TMSCHEMA_COLUMNS::SystemFlags" <-- "ssas.TMSCHEMA_COLUMNS_T::SystemFlags"
"ssas.TMSCHEMA_COLUMNS::TableDetailPosition" <-- "ssas.TMSCHEMA_COLUMNS_T::TableDetailPosition"
"ssas.TMSCHEMA_COLUMNS::TableID" <-- "ssas.TMSCHEMA_COLUMNS_T::TableID"
"ssas.TMSCHEMA_COLUMNS::Type" <-- "ssas.TMSCHEMA_COLUMNS_T::Type"
@enduml

