@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:repo.ForeignKey_ssas_IndexPattern.adoc[]" as repo.ForeignKey_ssas_IndexPattern << V >> {
  --
  - databasename : (nvarchar(128))
  delete_referential_action : (tinyint)
  ForeignKey_fullname : (nvarchar(517))
  - ForeignKey_guid : (uniqueidentifier)
  ForeignKey_name : (nvarchar(263))
  referenced_ColumnName : (nvarchar(128))
  referenced_IndexPatternColumnDatatype : (nvarchar(500))
  referenced_IndexPatternColumnGuid : (varchar(36))
  referenced_IndexPatternColumnName : (nvarchar(128))
  - referenced_IsKey : (bit)
  - referenced_IsNullable : (bit)
  referenced_ObjectName : (nvarchar(128))
  referenced_RepoObject_fullname : (nvarchar(517))
  referenced_RepoObject_fullname2 : (nvarchar(257))
  referenced_RepoObject_guid : (uniqueidentifier)
  referencing_ColumnName : (nvarchar(128))
  referencing_IndexPatternColumnDatatype : (nvarchar(500))
  referencing_IndexPatternColumnGuid : (varchar(36))
  referencing_IndexPatternColumnName : (nvarchar(128))
  - referencing_IsKey : (bit)
  - referencing_IsNullable : (bit)
  referencing_ObjectName : (nvarchar(128))
  referencing_RepoObject_fullname : (nvarchar(517))
  referencing_RepoObject_fullname2 : (nvarchar(257))
  referencing_RepoObject_guid : (uniqueidentifier)
  relationships_crossFilteringBehavior : (nvarchar(500))
  relationships_fromCardinality : (nvarchar(500))
  - relationships_isActive : (bit)
  relationships_name : (nvarchar(500))
  relationships_toCardinality : (nvarchar(500))
  update_referential_action : (tinyint)
  --
  --
}

entity "puml-link:dhw:sqldb:repo.RepoObjectColumn_gross.adoc[]" as repo.RepoObjectColumn_gross << V >> {
  --
  - Column_name : (nvarchar(128))
  Description : (nvarchar(max))
  has_different_sys_names : (bit)
  has_get_referenced_issue : (bit)
  Inheritance_StringAggSeparatorSql : (nvarchar(4000))
  InheritanceDefinition : (nvarchar(4000))
  InheritanceType : (tinyint)
  - is_external : (bit)
  is_persistence_no_check : (bit)
  is_persistence_no_include : (bit)
  is_persistence_no_update : (bit)
  is_query_plan_expression : (bit)
  is_repo_managed : (bit)
  - is_RepoObject_name_uniqueidentifier : (int)
  - is_RepoObjectColumn_name_uniqueidentifier : (int)
  is_required_ColumnMerge : (bit)
  - is_ssas : (bit)
  is_SysObject_missing : (bit)
  - is_SysObject_name_uniqueidentifier : (int)
  is_SysObjectColumn_missing : (bit)
  - is_SysObjectColumn_name_uniqueidentifier : (int)
  - modify_dt : (datetime)
  node_id : (bigint)
  persistence_source_RepoObject_guid : (uniqueidentifier)
  persistence_source_RepoObjectColumn_guid : (uniqueidentifier)
  pk_index_guid : (uniqueidentifier)
  Property_ms_description : (nvarchar(4000))
  Referencing_Count : (int)
  Repo_default_definition : (nvarchar(max))
  Repo_default_is_system_named : (bit)
  Repo_default_name : (nvarchar(128))
  Repo_definition : (nvarchar(max))
  - Repo_generated_always_type : (tinyint)
  Repo_graph_type : (int)
  Repo_increment_value : (sql_variant)
  - Repo_is_computed : (bit)
  - Repo_is_identity : (bit)
  Repo_is_nullable : (bit)
  Repo_is_persisted : (bit)
  Repo_seed_value : (sql_variant)
  Repo_user_type_fullname : (nvarchar(128))
  Repo_user_type_name : (nvarchar(128))
  Repo_uses_database_collation : (bit)
  - RepoObject_fullname : (nvarchar(261))
  - RepoObject_fullname2 : (nvarchar(257))
  - RepoObject_guid : (uniqueidentifier)
  - RepoObject_name : (nvarchar(128))
  RepoObject_Referencing_Count : (int)
  - RepoObject_schema_name : (nvarchar(128))
  - RepoObject_type : (char(2))
  RepoObjectColumn_column_id : (int)
  - RepoObjectColumn_fullname : (nvarchar(520))
  - RepoObjectColumn_fullname2 : (nvarchar(386))
  - RepoObjectColumn_guid : (uniqueidentifier)
  - RepoObjectColumn_name : (nvarchar(128))
  - SysObject_fullname : (nvarchar(261))
  - SysObject_fullname2 : (nvarchar(257))
  SysObject_id : (int)
  SysObject_modify_date : (datetime)
  - SysObject_name : (nvarchar(128))
  - SysObject_parent_object_id : (int)
  - SysObject_schema_name : (nvarchar(128))
  SysObject_type : (char(2))
  SysObjectColumn_column_id : (int)
  - SysObjectColumn_name : (nvarchar(128))
  tabcol_Description : (nvarchar(max))
  tabcol_DisplayFolder : (nvarchar(500))
  tabcol_Expression : (nvarchar(max))
  tabcol_FormatString : (nvarchar(500))
  - tabcol_IsHidden : (bit)
  - tabcol_IsKey : (bit)
  - tabcol_IsUnique : (bit)
  tabcol_SummarizeBy : (nvarchar(500))
  tabcol_Type : (nvarchar(500))
  --
  --
}

entity "puml-link:dhw:sqldb:repo.RepoObjectColumn_SSAS_src.adoc[]" as repo.RepoObjectColumn_SSAS_src << V >> {
  - **RepoObjectColumn_guid** : (uniqueidentifier)
  --
  - is_SysObjectColumn_missing : (int)
  - Repo_is_nullable : (bit)
  Repo_user_type_fullname : (nvarchar(500))
  Repo_user_type_name : (nvarchar(500))
  - RepoObject_guid : (uniqueidentifier)
  - RepoObjectColumn_name : (nvarchar(128))
  - SysObjectColumn_name : (nvarchar(128))
  --
  --
}

entity "puml-link:dhw:sqldb:ssas.IndexColumn_from_IsKey.adoc[]" as ssas.IndexColumn_from_IsKey << V >> {
  --
  - databasename : (nvarchar(128))
  - index_column_id : (int)
  - index_name : (nvarchar(265))
  - is_descending_key : (int)
  - is_index_primary_key : (bit)
  - is_index_unique : (bit)
  - RepoObject_guid : (uniqueidentifier)
  - RepoObjectColumn_guid : (uniqueidentifier)
  - TableName : (nvarchar(128))
  - tables_columns_name : (nvarchar(128))
  tables_columns_type : (nvarchar(500))
  --
  --
}

entity "puml-link:dhw:sqldb:ssas.IndexColumn_from_IsUnique.adoc[]" as ssas.IndexColumn_from_IsUnique << V >> {
  --
  - databasename : (nvarchar(128))
  - index_column_id : (int)
  - index_name : (nvarchar(264))
  - is_descending_key : (int)
  - is_index_primary_key : (bit)
  - is_index_unique : (bit)
  - RepoObject_guid : (uniqueidentifier)
  - RepoObjectColumn_guid : (uniqueidentifier)
  - TableName : (nvarchar(128))
  - tables_columns_name : (nvarchar(128))
  tables_columns_type : (nvarchar(500))
  --
  --
}

entity "puml-link:dhw:sqldb:ssas.IndexColumn_from_Relationship.adoc[]" as ssas.IndexColumn_from_Relationship << V >> {
  --
  - databasename : (nvarchar(128))
  - index_column_id : (int)
  - index_name : (nvarchar(264))
  - is_descending_key : (int)
  - is_index_primary_key : (bit)
  - is_index_unique : (bit)
  - RepoObject_guid : (uniqueidentifier)
  - RepoObjectColumn_guid : (uniqueidentifier)
  - TableName : (nvarchar(128))
  - tables_columns_name : (nvarchar(128))
  tables_columns_type : (nvarchar(500))
  --
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_311_tables_columns.adoc[]" as ssas.model_json_311_tables_columns << V >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  **tables_columns_name** : (nvarchar(128))
  --
  - RepoObject_guid : (uniqueidentifier)
  tables_columns_dataType : (nvarchar(500))
  tables_columns_description : (nvarchar(max))
  tables_columns_description_ja : (nvarchar(max))
  tables_columns_displayFolder : (nvarchar(500))
  tables_columns_expression : (nvarchar(max))
  tables_columns_expression_ja : (nvarchar(max))
  tables_columns_formatString : (nvarchar(500))
  tables_columns_isDataTypeInferred : (bit)
  tables_columns_isHidden : (bit)
  tables_columns_isKey : (bit)
  tables_columns_isNameInferred : (bit)
  tables_columns_isNullable : (bit)
  tables_columns_isUnique : (bit)
  tables_columns_keepUniqueRows : (bit)
  tables_columns_sortByColumn : (nvarchar(500))
  tables_columns_sourceColumn : (nvarchar(500))
  tables_columns_sourceProviderType : (nvarchar(500))
  tables_columns_summarizeBy : (nvarchar(500))
  tables_columns_type : (nvarchar(500))
  --
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_311_tables_columns_T.adoc[]" as ssas.model_json_311_tables_columns_T << U >> {
  - **databasename** : (nvarchar(128))
  - **tables_name** : (nvarchar(128))
  **tables_columns_name** : (nvarchar(128))
  --
  - RepoObject_guid : (uniqueidentifier)
  - RepoObjectColumn_guid : (uniqueidentifier)
  tables_columns_dataType : (nvarchar(500))
  tables_columns_description : (nvarchar(max))
  tables_columns_description_ja : (nvarchar(max))
  tables_columns_displayFolder : (nvarchar(500))
  tables_columns_expression : (nvarchar(max))
  tables_columns_expression_ja : (nvarchar(max))
  tables_columns_formatString : (nvarchar(500))
  tables_columns_isDataTypeInferred : (bit)
  tables_columns_isHidden : (bit)
  tables_columns_isKey : (bit)
  tables_columns_isNameInferred : (bit)
  tables_columns_isNullable : (bit)
  tables_columns_isUnique : (bit)
  tables_columns_keepUniqueRows : (bit)
  tables_columns_sortByColumn : (nvarchar(500))
  tables_columns_sourceColumn : (nvarchar(500))
  tables_columns_sourceProviderType : (nvarchar(500))
  tables_columns_summarizeBy : (nvarchar(500))
  tables_columns_type : (nvarchar(500))
  --
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_3111_tables_columns_descriptions_multiline.adoc[]" as ssas.model_json_3111_tables_columns_descriptions_multiline << V >> {
  --
  - databasename : (nvarchar(128))
  - Key : (nvarchar(4000))
  - RepoObject_guid : (uniqueidentifier)
  - RepoObjectColumn_guid : (uniqueidentifier)
  - tables_columns_name : (nvarchar(128))
  - tables_name : (nvarchar(128))
  - Type : (tinyint)
  Value : (nvarchar(max))
  --
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_3112_tables_columns_expressions_multiline.adoc[]" as ssas.model_json_3112_tables_columns_expressions_multiline << V >> {
  --
  - databasename : (nvarchar(128))
  - Key : (nvarchar(4000))
  - RepoObject_guid : (uniqueidentifier)
  - RepoObjectColumn_guid : (uniqueidentifier)
  - tables_columns_name : (nvarchar(128))
  - tables_name : (nvarchar(128))
  - Type : (tinyint)
  Value : (nvarchar(max))
  --
  --
}

entity "puml-link:dhw:sqldb:ssas.usp_PERSIST_model_json_311_tables_columns_T.adoc[]" as ssas.usp_PERSIST_model_json_311_tables_columns_T << P >> {
  --
  --
  --
}

ssas.model_json_311_tables_columns <.. ssas.model_json_311_tables_columns_T
ssas.model_json_311_tables_columns_T <.. ssas.model_json_3112_tables_columns_expressions_multiline
ssas.model_json_311_tables_columns_T <.. repo.ForeignKey_ssas_IndexPattern
ssas.model_json_311_tables_columns_T <.. ssas.usp_PERSIST_model_json_311_tables_columns_T
ssas.model_json_311_tables_columns_T <.. ssas.IndexColumn_from_IsKey
ssas.model_json_311_tables_columns_T <.. ssas.model_json_3111_tables_columns_descriptions_multiline
ssas.model_json_311_tables_columns_T <.. ssas.IndexColumn_from_Relationship
ssas.model_json_311_tables_columns_T <.. ssas.IndexColumn_from_IsUnique
ssas.model_json_311_tables_columns_T <.. repo.RepoObjectColumn_SSAS_src
ssas.model_json_311_tables_columns_T <.. repo.RepoObjectColumn_gross
"ssas.model_json_311_tables_columns::databasename" <-- "ssas.model_json_311_tables_columns_T::databasename"
"ssas.model_json_311_tables_columns::RepoObject_guid" <-- "ssas.model_json_311_tables_columns_T::RepoObject_guid"
"ssas.model_json_311_tables_columns::tables_columns_dataType" <-- "ssas.model_json_311_tables_columns_T::tables_columns_dataType"
"ssas.model_json_311_tables_columns::tables_columns_description" <-- "ssas.model_json_311_tables_columns_T::tables_columns_description"
"ssas.model_json_311_tables_columns::tables_columns_description_ja" <-- "ssas.model_json_311_tables_columns_T::tables_columns_description_ja"
"ssas.model_json_311_tables_columns::tables_columns_displayFolder" <-- "ssas.model_json_311_tables_columns_T::tables_columns_displayFolder"
"ssas.model_json_311_tables_columns::tables_columns_expression" <-- "ssas.model_json_311_tables_columns_T::tables_columns_expression"
"ssas.model_json_311_tables_columns::tables_columns_expression_ja" <-- "ssas.model_json_311_tables_columns_T::tables_columns_expression_ja"
"ssas.model_json_311_tables_columns::tables_columns_formatString" <-- "ssas.model_json_311_tables_columns_T::tables_columns_formatString"
"ssas.model_json_311_tables_columns::tables_columns_isDataTypeInferred" <-- "ssas.model_json_311_tables_columns_T::tables_columns_isDataTypeInferred"
"ssas.model_json_311_tables_columns::tables_columns_isHidden" <-- "ssas.model_json_311_tables_columns_T::tables_columns_isHidden"
"ssas.model_json_311_tables_columns::tables_columns_isKey" <-- "ssas.model_json_311_tables_columns_T::tables_columns_isKey"
"ssas.model_json_311_tables_columns::tables_columns_isNameInferred" <-- "ssas.model_json_311_tables_columns_T::tables_columns_isNameInferred"
"ssas.model_json_311_tables_columns::tables_columns_isNullable" <-- "ssas.model_json_311_tables_columns_T::tables_columns_isNullable"
"ssas.model_json_311_tables_columns::tables_columns_isUnique" <-- "ssas.model_json_311_tables_columns_T::tables_columns_isUnique"
"ssas.model_json_311_tables_columns::tables_columns_keepUniqueRows" <-- "ssas.model_json_311_tables_columns_T::tables_columns_keepUniqueRows"
"ssas.model_json_311_tables_columns::tables_columns_name" <-- "ssas.model_json_311_tables_columns_T::tables_columns_name"
"ssas.model_json_311_tables_columns::tables_columns_sortByColumn" <-- "ssas.model_json_311_tables_columns_T::tables_columns_sortByColumn"
"ssas.model_json_311_tables_columns::tables_columns_sourceColumn" <-- "ssas.model_json_311_tables_columns_T::tables_columns_sourceColumn"
"ssas.model_json_311_tables_columns::tables_columns_sourceProviderType" <-- "ssas.model_json_311_tables_columns_T::tables_columns_sourceProviderType"
"ssas.model_json_311_tables_columns::tables_columns_summarizeBy" <-- "ssas.model_json_311_tables_columns_T::tables_columns_summarizeBy"
"ssas.model_json_311_tables_columns::tables_columns_type" <-- "ssas.model_json_311_tables_columns_T::tables_columns_type"
"ssas.model_json_311_tables_columns::tables_name" <-- "ssas.model_json_311_tables_columns_T::tables_name"
"ssas.model_json_311_tables_columns_T::databasename" <-- "ssas.IndexColumn_from_IsUnique::databasename"
"ssas.model_json_311_tables_columns_T::databasename" <-- "ssas.IndexColumn_from_Relationship::databasename"
"ssas.model_json_311_tables_columns_T::databasename" <-- "ssas.IndexColumn_from_IsKey::databasename"
"ssas.model_json_311_tables_columns_T::databasename" <-- "ssas.model_json_3111_tables_columns_descriptions_multiline::databasename"
"ssas.model_json_311_tables_columns_T::databasename" <-- "ssas.model_json_3112_tables_columns_expressions_multiline::databasename"
"ssas.model_json_311_tables_columns_T::RepoObject_guid" <-- "repo.RepoObjectColumn_SSAS_src::RepoObject_guid"
"ssas.model_json_311_tables_columns_T::RepoObject_guid" <-- "ssas.IndexColumn_from_IsUnique::RepoObject_guid"
"ssas.model_json_311_tables_columns_T::RepoObject_guid" <-- "ssas.IndexColumn_from_Relationship::RepoObject_guid"
"ssas.model_json_311_tables_columns_T::RepoObject_guid" <-- "ssas.IndexColumn_from_IsKey::RepoObject_guid"
"ssas.model_json_311_tables_columns_T::RepoObject_guid" <-- "ssas.model_json_3111_tables_columns_descriptions_multiline::RepoObject_guid"
"ssas.model_json_311_tables_columns_T::RepoObject_guid" <-- "ssas.model_json_3112_tables_columns_expressions_multiline::RepoObject_guid"
"ssas.model_json_311_tables_columns_T::RepoObjectColumn_guid" <-- "repo.RepoObjectColumn_SSAS_src::RepoObjectColumn_guid"
"ssas.model_json_311_tables_columns_T::RepoObjectColumn_guid" <-- "ssas.IndexColumn_from_IsUnique::RepoObjectColumn_guid"
"ssas.model_json_311_tables_columns_T::RepoObjectColumn_guid" <-- "ssas.IndexColumn_from_Relationship::RepoObjectColumn_guid"
"ssas.model_json_311_tables_columns_T::RepoObjectColumn_guid" <-- "ssas.IndexColumn_from_IsKey::RepoObjectColumn_guid"
"ssas.model_json_311_tables_columns_T::RepoObjectColumn_guid" <-- "ssas.model_json_3111_tables_columns_descriptions_multiline::RepoObjectColumn_guid"
"ssas.model_json_311_tables_columns_T::RepoObjectColumn_guid" <-- "ssas.model_json_3112_tables_columns_expressions_multiline::RepoObjectColumn_guid"
"ssas.model_json_311_tables_columns_T::tables_columns_dataType" <-- "repo.RepoObjectColumn_SSAS_src::Repo_user_type_name"
"ssas.model_json_311_tables_columns_T::tables_columns_dataType" <-- "repo.RepoObjectColumn_SSAS_src::Repo_user_type_fullname"
"ssas.model_json_311_tables_columns_T::tables_columns_dataType" <-- "repo.ForeignKey_ssas_IndexPattern::referenced_IndexPatternColumnDatatype"
"ssas.model_json_311_tables_columns_T::tables_columns_dataType" <-- "repo.ForeignKey_ssas_IndexPattern::referencing_IndexPatternColumnDatatype"
"ssas.model_json_311_tables_columns_T::tables_columns_displayFolder" <-- "repo.RepoObjectColumn_gross::tabcol_DisplayFolder"
"ssas.model_json_311_tables_columns_T::tables_columns_formatString" <-- "repo.RepoObjectColumn_gross::tabcol_FormatString"
"ssas.model_json_311_tables_columns_T::tables_columns_name" <-- "repo.RepoObjectColumn_SSAS_src::RepoObjectColumn_name"
"ssas.model_json_311_tables_columns_T::tables_columns_name" <-- "repo.RepoObjectColumn_SSAS_src::SysObjectColumn_name"
"ssas.model_json_311_tables_columns_T::tables_columns_name" <-- "repo.ForeignKey_ssas_IndexPattern::referenced_IndexPatternColumnName"
"ssas.model_json_311_tables_columns_T::tables_columns_name" <-- "repo.ForeignKey_ssas_IndexPattern::referencing_IndexPatternColumnName"
"ssas.model_json_311_tables_columns_T::tables_columns_name" <-- "repo.ForeignKey_ssas_IndexPattern::referenced_ColumnName"
"ssas.model_json_311_tables_columns_T::tables_columns_name" <-- "repo.ForeignKey_ssas_IndexPattern::referencing_ColumnName"
"ssas.model_json_311_tables_columns_T::tables_columns_name" <-- "ssas.IndexColumn_from_IsUnique::tables_columns_name"
"ssas.model_json_311_tables_columns_T::tables_columns_name" <-- "ssas.IndexColumn_from_Relationship::tables_columns_name"
"ssas.model_json_311_tables_columns_T::tables_columns_name" <-- "ssas.IndexColumn_from_IsKey::tables_columns_name"
"ssas.model_json_311_tables_columns_T::tables_columns_name" <-- "ssas.model_json_3111_tables_columns_descriptions_multiline::tables_columns_name"
"ssas.model_json_311_tables_columns_T::tables_columns_name" <-- "ssas.model_json_3112_tables_columns_expressions_multiline::tables_columns_name"
"ssas.model_json_311_tables_columns_T::tables_columns_summarizeBy" <-- "repo.RepoObjectColumn_gross::tabcol_SummarizeBy"
"ssas.model_json_311_tables_columns_T::tables_columns_type" <-- "ssas.IndexColumn_from_IsUnique::tables_columns_type"
"ssas.model_json_311_tables_columns_T::tables_columns_type" <-- "ssas.IndexColumn_from_Relationship::tables_columns_type"
"ssas.model_json_311_tables_columns_T::tables_columns_type" <-- "ssas.IndexColumn_from_IsKey::tables_columns_type"
"ssas.model_json_311_tables_columns_T::tables_columns_type" <-- "repo.RepoObjectColumn_gross::tabcol_Type"
"ssas.model_json_311_tables_columns_T::tables_name" <-- "ssas.IndexColumn_from_IsUnique::TableName"
"ssas.model_json_311_tables_columns_T::tables_name" <-- "ssas.IndexColumn_from_Relationship::TableName"
"ssas.model_json_311_tables_columns_T::tables_name" <-- "ssas.IndexColumn_from_IsKey::TableName"
"ssas.model_json_311_tables_columns_T::tables_name" <-- "ssas.model_json_3111_tables_columns_descriptions_multiline::tables_name"
"ssas.model_json_311_tables_columns_T::tables_name" <-- "ssas.model_json_3112_tables_columns_expressions_multiline::tables_name"
@enduml

