@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssas.model_json_3132_tables_partitions_posfrom.adoc[]" as ssas.model_json_3132_tables_partitions_PosFrom << V >> {
  --
  - databasename : (nvarchar(128))
  PosFrom : (bigint)
  PosFromDoublequota : (bigint)
  PosFromWhere : (bigint)
  - RepoObject_guid : (uniqueidentifier)
  - tables_name : (nvarchar(128))
  tables_partitions_annotations_ja : (nvarchar(max))
  tables_partitions_dataView : (nvarchar(500))
  tables_partitions_mode : (nvarchar(500))
  tables_partitions_name : (nvarchar(500))
  tables_partitions_source_j : (nvarchar(max))
  --
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_31321_tables_partitions_stringfrom.adoc[]" as ssas.model_json_31321_tables_partitions_StringFrom << V >> {
  --
  - databasename : (nvarchar(128))
  PosFrom : (bigint)
  PosFromDoublequota : (bigint)
  PosFromWhere : (bigint)
  - RepoObject_guid : (uniqueidentifier)
  StringFrom : (nvarchar(max))
  - tables_name : (nvarchar(128))
  tables_partitions_annotations_ja : (nvarchar(max))
  tables_partitions_dataView : (nvarchar(500))
  tables_partitions_mode : (nvarchar(500))
  tables_partitions_name : (nvarchar(500))
  tables_partitions_source_j : (nvarchar(max))
  --
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_313211_tables_partitions_posdot.adoc[]" as ssas.model_json_313211_tables_partitions_PosDot << V >> {
  --
  - databasename : (nvarchar(128))
  PosDot1 : (bigint)
  PosDot2 : (bigint)
  PosFrom : (bigint)
  PosFromDoublequota : (bigint)
  PosFromWhere : (bigint)
  - RepoObject_guid : (uniqueidentifier)
  StringFrom : (nvarchar(max))
  - tables_name : (nvarchar(128))
  tables_partitions_annotations_ja : (nvarchar(max))
  tables_partitions_dataView : (nvarchar(500))
  tables_partitions_mode : (nvarchar(500))
  tables_partitions_name : (nvarchar(500))
  tables_partitions_source_j : (nvarchar(max))
  --
  --
}

ssas.model_json_3132_tables_partitions_PosFrom <.. ssas.model_json_31321_tables_partitions_StringFrom
ssas.model_json_31321_tables_partitions_StringFrom <.. ssas.model_json_313211_tables_partitions_PosDot
"ssas.model_json_3132_tables_partitions_PosFrom::databasename" <-- "ssas.model_json_31321_tables_partitions_StringFrom::databasename"
"ssas.model_json_3132_tables_partitions_PosFrom::PosFrom" <-- "ssas.model_json_31321_tables_partitions_StringFrom::PosFrom"
"ssas.model_json_3132_tables_partitions_PosFrom::PosFromDoublequota" <-- "ssas.model_json_31321_tables_partitions_StringFrom::PosFromDoublequota"
"ssas.model_json_3132_tables_partitions_PosFrom::PosFromWhere" <-- "ssas.model_json_31321_tables_partitions_StringFrom::PosFromWhere"
"ssas.model_json_3132_tables_partitions_PosFrom::RepoObject_guid" <-- "ssas.model_json_31321_tables_partitions_StringFrom::RepoObject_guid"
"ssas.model_json_3132_tables_partitions_PosFrom::tables_name" <-- "ssas.model_json_31321_tables_partitions_StringFrom::tables_name"
"ssas.model_json_3132_tables_partitions_PosFrom::tables_partitions_annotations_ja" <-- "ssas.model_json_31321_tables_partitions_StringFrom::tables_partitions_annotations_ja"
"ssas.model_json_3132_tables_partitions_PosFrom::tables_partitions_dataView" <-- "ssas.model_json_31321_tables_partitions_StringFrom::tables_partitions_dataView"
"ssas.model_json_3132_tables_partitions_PosFrom::tables_partitions_mode" <-- "ssas.model_json_31321_tables_partitions_StringFrom::tables_partitions_mode"
"ssas.model_json_3132_tables_partitions_PosFrom::tables_partitions_name" <-- "ssas.model_json_31321_tables_partitions_StringFrom::tables_partitions_name"
"ssas.model_json_3132_tables_partitions_PosFrom::tables_partitions_source_j" <-- "ssas.model_json_31321_tables_partitions_StringFrom::tables_partitions_source_j"
"ssas.model_json_31321_tables_partitions_StringFrom::databasename" <-- "ssas.model_json_313211_tables_partitions_PosDot::databasename"
"ssas.model_json_31321_tables_partitions_StringFrom::PosFrom" <-- "ssas.model_json_313211_tables_partitions_PosDot::PosFrom"
"ssas.model_json_31321_tables_partitions_StringFrom::PosFromDoublequota" <-- "ssas.model_json_313211_tables_partitions_PosDot::PosFromDoublequota"
"ssas.model_json_31321_tables_partitions_StringFrom::PosFromWhere" <-- "ssas.model_json_313211_tables_partitions_PosDot::PosFromWhere"
"ssas.model_json_31321_tables_partitions_StringFrom::RepoObject_guid" <-- "ssas.model_json_313211_tables_partitions_PosDot::RepoObject_guid"
"ssas.model_json_31321_tables_partitions_StringFrom::StringFrom" <-- "ssas.model_json_313211_tables_partitions_PosDot::StringFrom"
"ssas.model_json_31321_tables_partitions_StringFrom::tables_name" <-- "ssas.model_json_313211_tables_partitions_PosDot::tables_name"
"ssas.model_json_31321_tables_partitions_StringFrom::tables_partitions_annotations_ja" <-- "ssas.model_json_313211_tables_partitions_PosDot::tables_partitions_annotations_ja"
"ssas.model_json_31321_tables_partitions_StringFrom::tables_partitions_dataView" <-- "ssas.model_json_313211_tables_partitions_PosDot::tables_partitions_dataView"
"ssas.model_json_31321_tables_partitions_StringFrom::tables_partitions_mode" <-- "ssas.model_json_313211_tables_partitions_PosDot::tables_partitions_mode"
"ssas.model_json_31321_tables_partitions_StringFrom::tables_partitions_name" <-- "ssas.model_json_313211_tables_partitions_PosDot::tables_partitions_name"
"ssas.model_json_31321_tables_partitions_StringFrom::tables_partitions_source_j" <-- "ssas.model_json_313211_tables_partitions_PosDot::tables_partitions_source_j"
@enduml

