@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssas.model_json_33_dataSources.adoc[]" as ssas.model_json_33_dataSources << V >> {
  - **databasename** : (nvarchar(128))
  **dataSources_name** : (nvarchar(500))
  --
  dataSources_account : (nvarchar(500))
  dataSources_annotations_ja : (nvarchar(max))
  dataSources_connectionString : (nvarchar(4000))
  dataSources_impersonationMode : (nvarchar(500))
  dataSources_provider : (nvarchar(500))
  --
  --
}

entity "puml-link:dhw:sqldb:ssas.model_json_331_dataSources_annotations.adoc[]" as ssas.model_json_331_dataSources_annotations << V >> {
  - **databasename** : (nvarchar(128))
  **dataSources_name** : (nvarchar(500))
  **dataSources_annotations_name** : (nvarchar(500))
  --
  dataSources_annotations_value : (nvarchar(max))
  dataSources_annotations_value_ja : (nvarchar(max))
  --
  --
}

ssas.model_json_33_dataSources <.. ssas.model_json_331_dataSources_annotations
"ssas.model_json_33_dataSources::databasename" <-- "ssas.model_json_331_dataSources_annotations::databasename"
"ssas.model_json_33_dataSources::dataSources_name" <-- "ssas.model_json_331_dataSources_annotations::dataSources_name"
@enduml

