@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis.project.adoc[]" as ssis.Project << U >> {
  - **AntoraModule** : (varchar(50))
  ProjectPath : (varchar(8000))
  ~ sql_import : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:ssis.projectconnection_src.adoc[]" as ssis.ProjectConnection_src << V >> {
  - **AntoraModule** : (varchar(50))
  **ConnectionManagerID** : (uniqueidentifier)
  ConnectionManagerName : (varchar(max))
  ConnectionManagerType : (varchar(max))
  - ConnectionPath : (varchar(8000))
  ConnectionString : (nvarchar(max))
  ExpressionValue : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.projectconnection_tgt.adoc[]" as ssis.ProjectConnection_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  **ConnectionManagerID** : (uniqueidentifier)
  ConnectionManagerName : (varchar(max))
  ConnectionManagerType : (varchar(max))
  - ConnectionPath : (varchar(8000))
  ConnectionString : (nvarchar(max))
  ExpressionValue : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_projectconnection_tgt.adoc[]" as ssis.usp_PERSIST_ProjectConnection_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.projectconnection.adoc[]" as ssis_t.ProjectConnection << U >> {
  - **RowID** : (int)
  - ConnectionPath : (varchar(8000))
  - ConnectionXML : (xml)
  - ProjectPath : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tblprojectconnection.adoc[]" as ssis_t.TblProjectConnection << U >> {
  ConnectionManagerID : (uniqueidentifier)
  ConnectionManagerName : (varchar(max))
  ConnectionManagerType : (varchar(max))
  - ConnectionPath : (varchar(8000))
  ConnectionString : (nvarchar(max))
  ExpressionValue : (nvarchar(max))
  - RowID : (int)
  --
}

ssis.Project <.. ssis.ProjectConnection_src
ssis.ProjectConnection_src <.. ssis.ProjectConnection_tgt
ssis.ProjectConnection_src <.. ssis.usp_PERSIST_ProjectConnection_tgt
ssis_t.ProjectConnection <.. ssis.ProjectConnection_src
ssis_t.TblProjectConnection <.. ssis.ProjectConnection_src
"ssis.Project::AntoraModule" <-- "ssis.ProjectConnection_src::AntoraModule"
"ssis.ProjectConnection_src::AntoraModule" <-- "ssis.ProjectConnection_tgt::AntoraModule"
"ssis.ProjectConnection_src::ConnectionManagerID" <-- "ssis.ProjectConnection_tgt::ConnectionManagerID"
"ssis.ProjectConnection_src::ConnectionManagerName" <-- "ssis.ProjectConnection_tgt::ConnectionManagerName"
"ssis.ProjectConnection_src::ConnectionManagerType" <-- "ssis.ProjectConnection_tgt::ConnectionManagerType"
"ssis.ProjectConnection_src::ConnectionPath" <-- "ssis.ProjectConnection_tgt::ConnectionPath"
"ssis.ProjectConnection_src::ConnectionString" <-- "ssis.ProjectConnection_tgt::ConnectionString"
"ssis.ProjectConnection_src::ExpressionValue" <-- "ssis.ProjectConnection_tgt::ExpressionValue"
"ssis_t.ProjectConnection::ConnectionPath" <-- "ssis.ProjectConnection_src::ConnectionPath"
"ssis_t.TblProjectConnection::ConnectionManagerID" <-- "ssis.ProjectConnection_src::ConnectionManagerID"
"ssis_t.TblProjectConnection::ConnectionManagerName" <-- "ssis.ProjectConnection_src::ConnectionManagerName"
"ssis_t.TblProjectConnection::ConnectionManagerType" <-- "ssis.ProjectConnection_src::ConnectionManagerType"
"ssis_t.TblProjectConnection::ConnectionString" <-- "ssis.ProjectConnection_src::ConnectionString"
"ssis_t.TblProjectConnection::ExpressionValue" <-- "ssis.ProjectConnection_src::ExpressionValue"footer The diagram is interactive and contains links.
@enduml

