@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis.antoramodule_tgt_filter.adoc[]" as ssis.AntoraModule_tgt_filter << V >> {
  - AntoraModule : (varchar(50))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagevariable.adoc[]" as ssis.PackageVariable << U >> {
  - **AntoraModule** : (varchar(50))
  - **PackageName** : (varchar(200))
  - **VariableName** : (varchar(500))
  ExpressionValue : (varchar(5000))
  VariableDataType : (varchar(max))
  VariableHexValue : (varchar(1000))
  VariableValue : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagevariable_src.adoc[]" as ssis.PackageVariable_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **VariableName** : (varchar(500))
  ExpressionValue : (varchar(5000))
  VariableDataType : (varchar(max))
  VariableHexValue : (varchar(1000))
  VariableValue : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagevariable_tgt.adoc[]" as ssis.PackageVariable_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **VariableName** : (varchar(500))
  ExpressionValue : (varchar(5000))
  VariableDataType : (varchar(max))
  VariableHexValue : (varchar(1000))
  VariableValue : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packagevariable_tgt.adoc[]" as ssis.usp_PERSIST_PackageVariable_tgt << P >> {
  --
}

ssis.AntoraModule_tgt_filter <.. ssis.PackageVariable_tgt
ssis.PackageVariable <.. ssis.PackageVariable_tgt
ssis.PackageVariable_src <.. ssis.PackageVariable_tgt
ssis.PackageVariable_tgt <.. ssis.AntoraModule_tgt_filter
ssis.PackageVariable_tgt <.. ssis.PackageVariable
ssis.PackageVariable_tgt <.. ssis.usp_PERSIST_PackageVariable_tgt
"ssis.PackageVariable::AntoraModule" <-- "ssis.PackageVariable_tgt::AntoraModule"
"ssis.PackageVariable::ExpressionValue" <-- "ssis.PackageVariable_tgt::ExpressionValue"
"ssis.PackageVariable::PackageName" <-- "ssis.PackageVariable_tgt::PackageName"
"ssis.PackageVariable::VariableDataType" <-- "ssis.PackageVariable_tgt::VariableDataType"
"ssis.PackageVariable::VariableHexValue" <-- "ssis.PackageVariable_tgt::VariableHexValue"
"ssis.PackageVariable::VariableName" <-- "ssis.PackageVariable_tgt::VariableName"
"ssis.PackageVariable::VariableValue" <-- "ssis.PackageVariable_tgt::VariableValue"
"ssis.PackageVariable_src::AntoraModule" <-- "ssis.PackageVariable_tgt::AntoraModule"
"ssis.PackageVariable_src::ExpressionValue" <-- "ssis.PackageVariable_tgt::ExpressionValue"
"ssis.PackageVariable_src::PackageName" <-- "ssis.PackageVariable_tgt::PackageName"
"ssis.PackageVariable_src::VariableDataType" <-- "ssis.PackageVariable_tgt::VariableDataType"
"ssis.PackageVariable_src::VariableHexValue" <-- "ssis.PackageVariable_tgt::VariableHexValue"
"ssis.PackageVariable_src::VariableName" <-- "ssis.PackageVariable_tgt::VariableName"
"ssis.PackageVariable_src::VariableValue" <-- "ssis.PackageVariable_tgt::VariableValue"footer The diagram is interactive and contains links.
@enduml

