@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis.package_src.adoc[]" as ssis.Package_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  PackageCreationDate : (datetime)
  PackageCreatorComputerName : (nvarchar(500))
  PackageCreatorName : (varchar(1000))
  PackageDescription : (nvarchar(max))
  PackageDTSID : (uniqueidentifier)
  PackageLastModifiedProductVersion : (nvarchar(500))
  PackageLocaleID : (int)
  PackageObjectName : (nvarchar(500))
  - PackagePath : (varchar(8000))
  PackageProtectionLevel : (varchar(100))
  PackageProtectionLevelName : (varchar(28))
  PackageVersionGUID : (uniqueidentifier)
  - ProjectPath : (varchar(8000))
  - RowID : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_sql_parameter_src.adoc[]" as ssis.PackageTask_Sql_Parameter_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **TaskPath** : (varchar(8000))
  **ParameterBindingSequence** : (varchar(1000))
  - ControlFlowDetailsRowID : (int)
  ParameterBindingParameterName : (varchar(1000))
  ResultSetParameterName : (varchar(1000))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_sql_parameter_tgt.adoc[]" as ssis.PackageTask_Sql_Parameter_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **TaskPath** : (varchar(8000))
  **ParameterBindingSequence** : (varchar(1000))
  - ControlFlowDetailsRowID : (int)
  ParameterBindingParameterName : (varchar(1000))
  ResultSetParameterName : (varchar(1000))
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packagetask_sql_parameter_tgt.adoc[]" as ssis.usp_PERSIST_PackageTask_Sql_Parameter_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tblcontrolflow.adoc[]" as ssis_t.TblControlFlow << U >> {
  - **ControlFlowDetailsRowID** : (int)
  DelayValidationPropertyValue : (varchar(100))
  DFTQuery : (xml)
  ExecPkgTaskQry : (xml)
  ExpressionValue : (varchar(5000))
  IsDisabled : (varchar(10))
  RowID : (int)
  ScriptTaskQry : (xml)
  SqlTaskQry : (xml)
  TaskDescription : (varchar(max))
  TaskName : (varchar(2000))
  TaskPath : (varchar(8000))
  TaskType : (varchar(5000))
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_sql_parameter.adoc[]" as ssis_t.TblTask_Sql_Parameter << U >> {
  ControlFlowDetailsRowID : (int)
  ParameterBindingParameterName : (varchar(1000))
  ParameterBindingSequence : (varchar(1000))
  ResultSetParameterName : (varchar(1000))
  RowID : (int)
  --
}

ssis.Package_src <.. ssis.PackageTask_Sql_Parameter_src
ssis.PackageTask_Sql_Parameter_src <.. ssis.PackageTask_Sql_Parameter_tgt
ssis.PackageTask_Sql_Parameter_src <.. ssis.usp_PERSIST_PackageTask_Sql_Parameter_tgt
ssis_t.TblControlFlow <.. ssis.PackageTask_Sql_Parameter_src
ssis_t.TblTask_Sql_Parameter <.. ssis.PackageTask_Sql_Parameter_src
"ssis.Package_src::AntoraModule" <-- "ssis.PackageTask_Sql_Parameter_src::AntoraModule"
"ssis.Package_src::PackageName" <-- "ssis.PackageTask_Sql_Parameter_src::PackageName"
"ssis.PackageTask_Sql_Parameter_src::AntoraModule" <-- "ssis.PackageTask_Sql_Parameter_tgt::AntoraModule"
"ssis.PackageTask_Sql_Parameter_src::ControlFlowDetailsRowID" <-- "ssis.PackageTask_Sql_Parameter_tgt::ControlFlowDetailsRowID"
"ssis.PackageTask_Sql_Parameter_src::PackageName" <-- "ssis.PackageTask_Sql_Parameter_tgt::PackageName"
"ssis.PackageTask_Sql_Parameter_src::ParameterBindingParameterName" <-- "ssis.PackageTask_Sql_Parameter_tgt::ParameterBindingParameterName"
"ssis.PackageTask_Sql_Parameter_src::ParameterBindingSequence" <-- "ssis.PackageTask_Sql_Parameter_tgt::ParameterBindingSequence"
"ssis.PackageTask_Sql_Parameter_src::ResultSetParameterName" <-- "ssis.PackageTask_Sql_Parameter_tgt::ResultSetParameterName"
"ssis.PackageTask_Sql_Parameter_src::TaskPath" <-- "ssis.PackageTask_Sql_Parameter_tgt::TaskPath"
"ssis_t.TblControlFlow::ControlFlowDetailsRowID" <-- "ssis.PackageTask_Sql_Parameter_src::ControlFlowDetailsRowID"
"ssis_t.TblControlFlow::TaskPath" <-- "ssis.PackageTask_Sql_Parameter_src::TaskPath"
"ssis_t.TblTask_Sql_Parameter::ParameterBindingParameterName" <-- "ssis.PackageTask_Sql_Parameter_src::ParameterBindingParameterName"
"ssis_t.TblTask_Sql_Parameter::ParameterBindingSequence" <-- "ssis.PackageTask_Sql_Parameter_src::ParameterBindingSequence"
"ssis_t.TblTask_Sql_Parameter::ResultSetParameterName" <-- "ssis.PackageTask_Sql_Parameter_src::ResultSetParameterName"footer The diagram is interactive and contains links.
@enduml

