@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:docs.ssis_pumlpartialtaskcomponent.adoc[]" as docs.ssis_PumlPartialTaskComponent << V >> {
  - AntoraModule : (varchar(50))
  - PackageName : (varchar(200))
  PumlPartialTaskComponent : (nvarchar(4000))
  - TaskName : (varchar(2000))
  - TaskPath : (varchar(8000))
  TaskPathLevel : (int)
  TaskPathLevelLag : (int)
  TaskPathLevelLead : (int)
  TaskPathParent : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask.adoc[]" as ssis.PackageTask << U >> {
  - AntoraModule : (varchar(50))
  - ControlFlowDetailsRowID : (int)
  DelayValidationPropertyValue : (varchar(100))
  ExecutedPackageName : (varchar(1000))
  ExecutePackageConnection : (varchar(1000))
  ExecutePackageExpression : (varchar(1000))
  ExpressionValue : (varchar(5000))
  IsDisabled : (varchar(10))
  - PackageName : (varchar(200))
  Script : (varchar(max))
  SqlConnection : (uniqueidentifier)
  SqlStatementSource : (nvarchar(max))
  TaskDescription : (varchar(max))
  - TaskName : (varchar(2000))
  - TaskPath : (varchar(8000))
  TaskType : (varchar(5000))
  # PackageBasename : (varchar(8000))
  # TaskPathLevel : (int)
  # TaskPathParent : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_levellaglead.adoc[]" as ssis.PackageTask_LevelLagLead << V >> {
  - AntoraModule : (varchar(50))
  PackageBasename : (varchar(8000))
  - PackageName : (varchar(200))
  - TaskName : (varchar(2000))
  - TaskPath : (varchar(8000))
  TaskPathLevel : (int)
  TaskPathLevelLag : (int)
  TaskPathLevelLead : (int)
  TaskPathParent : (varchar(8000))
  --
}

ssis.PackageTask <.. ssis.PackageTask_LevelLagLead
ssis.PackageTask_LevelLagLead <.. docs.ssis_PumlPartialTaskComponent
"ssis.PackageTask::AntoraModule" <-- "ssis.PackageTask_LevelLagLead::AntoraModule"
"ssis.PackageTask::PackageBasename" <-- "ssis.PackageTask_LevelLagLead::PackageBasename"
"ssis.PackageTask::PackageName" <-- "ssis.PackageTask_LevelLagLead::PackageName"
"ssis.PackageTask::TaskName" <-- "ssis.PackageTask_LevelLagLead::TaskName"
"ssis.PackageTask::TaskPath" <-- "ssis.PackageTask_LevelLagLead::TaskPath"
"ssis.PackageTask::TaskPathLevel" <-- "ssis.PackageTask_LevelLagLead::TaskPathLevel"
"ssis.PackageTask::TaskPathParent" <-- "ssis.PackageTask_LevelLagLead::TaskPathParent"
"ssis.PackageTask_LevelLagLead::AntoraModule" <-- "docs.ssis_PumlPartialTaskComponent::AntoraModule"
"ssis.PackageTask_LevelLagLead::PackageName" <-- "docs.ssis_PumlPartialTaskComponent::PackageName"
"ssis.PackageTask_LevelLagLead::TaskName" <-- "docs.ssis_PumlPartialTaskComponent::TaskName"
"ssis.PackageTask_LevelLagLead::TaskPath" <-- "docs.ssis_PumlPartialTaskComponent::TaskPath"
"ssis.PackageTask_LevelLagLead::TaskPathLevel" <-- "docs.ssis_PumlPartialTaskComponent::TaskPathLevel"
"ssis.PackageTask_LevelLagLead::TaskPathLevelLag" <-- "docs.ssis_PumlPartialTaskComponent::TaskPathLevelLag"
"ssis.PackageTask_LevelLagLead::TaskPathLevelLead" <-- "docs.ssis_PumlPartialTaskComponent::TaskPathLevelLead"
"ssis.PackageTask_LevelLagLead::TaskPathParent" <-- "docs.ssis_PumlPartialTaskComponent::TaskPathParent"footer The diagram is interactive and contains links.
@enduml

