@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis.antoramodule_tgt_filter.adoc[]" as ssis.AntoraModule_tgt_filter << V >> {
  - AntoraModule : (varchar(50))
  --
}

entity "puml-link:dhw:sqldb:ssis.packageflow.adoc[]" as ssis.PackageFlow << U >> {
  - AntoraModule : (varchar(50))
  CreationName : (nvarchar(max))
  DTSID : (uniqueidentifier)
  EvalOp : (int)
  Expression : (nvarchar(max))
  FlowType : (varchar(1000))
  LogicalAnd : (bit)
  ObjectName : (nvarchar(max))
  - PackageName : (varchar(200))
  - TaskFrom : (varchar(2000))
  - Taskto : (varchar(2000))
  # TaskFromLevel : (int)
  # TaskFromParent : (varchar(2000))
  # TaskToLevel : (int)
  # TaskToParent : (varchar(2000))
  --
}

entity "puml-link:dhw:sqldb:ssis.packageflow_src.adoc[]" as ssis.PackageFlow_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **TaskFrom** : (varchar(2000))
  **Taskto** : (varchar(2000))
  CreationName : (nvarchar(max))
  DTSID : (uniqueidentifier)
  EvalOp : (int)
  Expression : (nvarchar(max))
  FlowType : (varchar(1000))
  LogicalAnd : (bit)
  ObjectName : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packageflow_tgt.adoc[]" as ssis.PackageFlow_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **TaskFrom** : (varchar(2000))
  **Taskto** : (varchar(2000))
  CreationName : (nvarchar(max))
  DTSID : (uniqueidentifier)
  EvalOp : (int)
  Expression : (nvarchar(max))
  FlowType : (varchar(1000))
  LogicalAnd : (bit)
  ObjectName : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packageflow_tgt.adoc[]" as ssis.usp_PERSIST_PackageFlow_tgt << P >> {
  --
}

ssis.AntoraModule_tgt_filter <.. ssis.PackageFlow_tgt
ssis.PackageFlow <.. ssis.PackageFlow_tgt
ssis.PackageFlow_src <.. ssis.PackageFlow_tgt
ssis.PackageFlow_tgt <.. ssis.PackageFlow
ssis.PackageFlow_tgt <.. ssis.usp_PERSIST_PackageFlow_tgt
ssis.PackageFlow_tgt <.. ssis.AntoraModule_tgt_filter
"ssis.PackageFlow::AntoraModule" <-- "ssis.PackageFlow_tgt::AntoraModule"
"ssis.PackageFlow::CreationName" <-- "ssis.PackageFlow_tgt::CreationName"
"ssis.PackageFlow::DTSID" <-- "ssis.PackageFlow_tgt::DTSID"
"ssis.PackageFlow::EvalOp" <-- "ssis.PackageFlow_tgt::EvalOp"
"ssis.PackageFlow::Expression" <-- "ssis.PackageFlow_tgt::Expression"
"ssis.PackageFlow::FlowType" <-- "ssis.PackageFlow_tgt::FlowType"
"ssis.PackageFlow::LogicalAnd" <-- "ssis.PackageFlow_tgt::LogicalAnd"
"ssis.PackageFlow::ObjectName" <-- "ssis.PackageFlow_tgt::ObjectName"
"ssis.PackageFlow::PackageName" <-- "ssis.PackageFlow_tgt::PackageName"
"ssis.PackageFlow::TaskFrom" <-- "ssis.PackageFlow_tgt::TaskFrom"
"ssis.PackageFlow::Taskto" <-- "ssis.PackageFlow_tgt::Taskto"
"ssis.PackageFlow_src::AntoraModule" <-- "ssis.PackageFlow_tgt::AntoraModule"
"ssis.PackageFlow_src::CreationName" <-- "ssis.PackageFlow_tgt::CreationName"
"ssis.PackageFlow_src::DTSID" <-- "ssis.PackageFlow_tgt::DTSID"
"ssis.PackageFlow_src::EvalOp" <-- "ssis.PackageFlow_tgt::EvalOp"
"ssis.PackageFlow_src::Expression" <-- "ssis.PackageFlow_tgt::Expression"
"ssis.PackageFlow_src::FlowType" <-- "ssis.PackageFlow_tgt::FlowType"
"ssis.PackageFlow_src::LogicalAnd" <-- "ssis.PackageFlow_tgt::LogicalAnd"
"ssis.PackageFlow_src::ObjectName" <-- "ssis.PackageFlow_tgt::ObjectName"
"ssis.PackageFlow_src::PackageName" <-- "ssis.PackageFlow_tgt::PackageName"
"ssis.PackageFlow_src::TaskFrom" <-- "ssis.PackageFlow_tgt::TaskFrom"
"ssis.PackageFlow_src::Taskto" <-- "ssis.PackageFlow_tgt::Taskto"footer The diagram is interactive and contains links.
@enduml

