@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis.package_src.adoc[]" as ssis.Package_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  PackageCreationDate : (datetime)
  PackageCreatorComputerName : (nvarchar(500))
  PackageCreatorName : (varchar(1000))
  PackageDescription : (nvarchar(max))
  PackageDTSID : (uniqueidentifier)
  PackageLastModifiedProductVersion : (nvarchar(500))
  PackageLocaleID : (int)
  PackageObjectName : (nvarchar(500))
  - PackagePath : (varchar(8000))
  PackageProtectionLevel : (varchar(100))
  PackageProtectionLevelName : (varchar(28))
  PackageVersionGUID : (uniqueidentifier)
  - ProjectPath : (varchar(8000))
  - RowID : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_output_src.adoc[]" as ssis.PackageTask_Dft_Component_output_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **output_refId** : (varchar(max))
  Component_refId : (varchar(max))
  - ControlFlowDetailsRowID : (int)
  output_isErrorOut : (bit)
  output_name : (varchar(500))
  TaskPath : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_output_tgt.adoc[]" as ssis.PackageTask_Dft_Component_output_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **output_refId** : (varchar(max))
  Component_refId : (varchar(max))
  - ControlFlowDetailsRowID : (int)
  output_isErrorOut : (bit)
  output_name : (varchar(500))
  TaskPath : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packagetask_dft_component_output_tgt.adoc[]" as ssis.usp_PERSIST_PackageTask_Dft_Component_output_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tblcontrolflow.adoc[]" as ssis_t.TblControlFlow << U >> {
  - **ControlFlowDetailsRowID** : (int)
  DelayValidationPropertyValue : (varchar(100))
  DFTQuery : (xml)
  ExecPkgTaskQry : (xml)
  ExpressionValue : (varchar(5000))
  IsDisabled : (varchar(10))
  RowID : (int)
  ScriptTaskQry : (xml)
  SqlTaskQry : (xml)
  TaskDescription : (varchar(max))
  TaskName : (varchar(2000))
  TaskPath : (varchar(8000))
  TaskType : (varchar(5000))
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_dft_component_outputs_src.adoc[]" as ssis_t.TblTask_Dft_Component_outputs_src << V >> {
  - ControlFlowDetailsRowID : (int)
  - DftComponentId : (int)
  nodescontent : (xml)
  output_isErrorOut : (bit)
  output_name : (varchar(500))
  output_refId : (varchar(max))
  refId : (varchar(max))
  RowID : (int)
  --
}

ssis.Package_src <.. ssis.PackageTask_Dft_Component_output_src
ssis.PackageTask_Dft_Component_output_src <.. ssis.PackageTask_Dft_Component_output_tgt
ssis.PackageTask_Dft_Component_output_src <.. ssis.usp_PERSIST_PackageTask_Dft_Component_output_tgt
ssis_t.TblControlFlow <.. ssis.PackageTask_Dft_Component_output_src
ssis_t.TblTask_Dft_Component_outputs_src <.. ssis.PackageTask_Dft_Component_output_src
"ssis.Package_src::AntoraModule" <-- "ssis.PackageTask_Dft_Component_output_src::AntoraModule"
"ssis.Package_src::PackageName" <-- "ssis.PackageTask_Dft_Component_output_src::PackageName"
"ssis.PackageTask_Dft_Component_output_src::AntoraModule" <-- "ssis.PackageTask_Dft_Component_output_tgt::AntoraModule"
"ssis.PackageTask_Dft_Component_output_src::Component_refId" <-- "ssis.PackageTask_Dft_Component_output_tgt::Component_refId"
"ssis.PackageTask_Dft_Component_output_src::ControlFlowDetailsRowID" <-- "ssis.PackageTask_Dft_Component_output_tgt::ControlFlowDetailsRowID"
"ssis.PackageTask_Dft_Component_output_src::output_isErrorOut" <-- "ssis.PackageTask_Dft_Component_output_tgt::output_isErrorOut"
"ssis.PackageTask_Dft_Component_output_src::output_name" <-- "ssis.PackageTask_Dft_Component_output_tgt::output_name"
"ssis.PackageTask_Dft_Component_output_src::output_refId" <-- "ssis.PackageTask_Dft_Component_output_tgt::output_refId"
"ssis.PackageTask_Dft_Component_output_src::PackageName" <-- "ssis.PackageTask_Dft_Component_output_tgt::PackageName"
"ssis.PackageTask_Dft_Component_output_src::TaskPath" <-- "ssis.PackageTask_Dft_Component_output_tgt::TaskPath"
"ssis_t.TblControlFlow::TaskPath" <-- "ssis.PackageTask_Dft_Component_output_src::TaskPath"
"ssis_t.TblTask_Dft_Component_outputs_src::ControlFlowDetailsRowID" <-- "ssis.PackageTask_Dft_Component_output_src::ControlFlowDetailsRowID"
"ssis_t.TblTask_Dft_Component_outputs_src::output_isErrorOut" <-- "ssis.PackageTask_Dft_Component_output_src::output_isErrorOut"
"ssis_t.TblTask_Dft_Component_outputs_src::output_name" <-- "ssis.PackageTask_Dft_Component_output_src::output_name"
"ssis_t.TblTask_Dft_Component_outputs_src::output_refId" <-- "ssis.PackageTask_Dft_Component_output_src::output_refId"
"ssis_t.TblTask_Dft_Component_outputs_src::refId" <-- "ssis.PackageTask_Dft_Component_output_src::Component_refId"footer The diagram is interactive and contains links.
@enduml

