@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis.package_src.adoc[]" as ssis.Package_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  PackageCreationDate : (datetime)
  PackageCreatorComputerName : (nvarchar(500))
  PackageCreatorName : (varchar(1000))
  PackageDescription : (nvarchar(max))
  PackageDTSID : (uniqueidentifier)
  PackageLastModifiedProductVersion : (nvarchar(500))
  PackageLocaleID : (int)
  PackageObjectName : (nvarchar(500))
  - PackagePath : (varchar(8000))
  PackageProtectionLevel : (varchar(100))
  PackageProtectionLevelName : (varchar(28))
  PackageVersionGUID : (uniqueidentifier)
  - ProjectPath : (varchar(8000))
  - RowID : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis.packageconnection_src.adoc[]" as ssis.PackageConnection_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **ConnectionManagerID** : (uniqueidentifier)
  ConnectionManagerName : (varchar(max))
  ConnectionManagerType : (varchar(max))
  ConnectionString : (varchar(max))
  ExpressionValue : (varchar(max))
  RetainSameConnectionProperty : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.packageconnection_tgt.adoc[]" as ssis.PackageConnection_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **ConnectionManagerID** : (uniqueidentifier)
  ConnectionManagerName : (varchar(max))
  ConnectionManagerType : (varchar(max))
  ConnectionString : (varchar(max))
  ExpressionValue : (varchar(max))
  RetainSameConnectionProperty : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packageconnection_tgt.adoc[]" as ssis.usp_PERSIST_PackageConnection_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tblconnection.adoc[]" as ssis_t.TblConnection << U >> {
  - Category : (varchar(10))
  ConnectionManagerID : (uniqueidentifier)
  ConnectionManagerName : (varchar(max))
  ConnectionManagerType : (varchar(max))
  ConnectionString : (varchar(max))
  - DelayValidationPropertyValue : (varchar(2))
  ExpressionValue : (varchar(max))
  PackageCreatorName : (varchar(1000))
  PackageName : (varchar(8000))
  - PackagePath : (varchar(8000))
  RetainSameConnectionProperty : (nvarchar(max))
  - RowID : (int)
  --
}

ssis.Package_src <.. ssis.PackageConnection_src
ssis.PackageConnection_src <.. ssis.PackageConnection_tgt
ssis.PackageConnection_src <.. ssis.usp_PERSIST_PackageConnection_tgt
ssis_t.TblConnection <.. ssis.PackageConnection_src
"ssis.Package_src::AntoraModule" <-- "ssis.PackageConnection_src::AntoraModule"
"ssis.Package_src::PackageName" <-- "ssis.PackageConnection_src::PackageName"
"ssis.PackageConnection_src::AntoraModule" <-- "ssis.PackageConnection_tgt::AntoraModule"
"ssis.PackageConnection_src::ConnectionManagerID" <-- "ssis.PackageConnection_tgt::ConnectionManagerID"
"ssis.PackageConnection_src::ConnectionManagerName" <-- "ssis.PackageConnection_tgt::ConnectionManagerName"
"ssis.PackageConnection_src::ConnectionManagerType" <-- "ssis.PackageConnection_tgt::ConnectionManagerType"
"ssis.PackageConnection_src::ConnectionString" <-- "ssis.PackageConnection_tgt::ConnectionString"
"ssis.PackageConnection_src::ExpressionValue" <-- "ssis.PackageConnection_tgt::ExpressionValue"
"ssis.PackageConnection_src::PackageName" <-- "ssis.PackageConnection_tgt::PackageName"
"ssis.PackageConnection_src::RetainSameConnectionProperty" <-- "ssis.PackageConnection_tgt::RetainSameConnectionProperty"
"ssis_t.TblConnection::ConnectionManagerID" <-- "ssis.PackageConnection_src::ConnectionManagerID"
"ssis_t.TblConnection::ConnectionManagerName" <-- "ssis.PackageConnection_src::ConnectionManagerName"
"ssis_t.TblConnection::ConnectionManagerType" <-- "ssis.PackageConnection_src::ConnectionManagerType"
"ssis_t.TblConnection::ConnectionString" <-- "ssis.PackageConnection_src::ConnectionString"
"ssis_t.TblConnection::ExpressionValue" <-- "ssis.PackageConnection_src::ExpressionValue"
"ssis_t.TblConnection::RetainSameConnectionProperty" <-- "ssis.PackageConnection_src::RetainSameConnectionProperty"footer The diagram is interactive and contains links.
@enduml

