@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis.packagetask_sql_parameter_src.adoc[]" as ssis.PackageTask_Sql_Parameter_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **TaskPath** : (varchar(8000))
  **ParameterBindingSequence** : (varchar(1000))
  - ControlFlowDetailsRowID : (int)
  ParameterBindingParameterName : (varchar(1000))
  ResultSetParameterName : (varchar(1000))
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_sql_parameter.adoc[]" as ssis_t.TblTask_Sql_Parameter << U >> {
  ControlFlowDetailsRowID : (int)
  ParameterBindingParameterName : (varchar(1000))
  ParameterBindingSequence : (varchar(1000))
  ResultSetParameterName : (varchar(1000))
  RowID : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis_t.usp_getpackagedetails.adoc[]" as ssis_t.usp_GetPackageDetails << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.usp_packageanalysis.adoc[]" as ssis_t.usp_PackageAnalysis << P >> {
  --
}

ssis_t.TblTask_Sql_Parameter <.. ssis.PackageTask_Sql_Parameter_src
ssis_t.TblTask_Sql_Parameter <.. ssis_t.usp_PackageAnalysis
ssis_t.TblTask_Sql_Parameter <.. ssis_t.usp_GetPackageDetails
"ssis_t.TblTask_Sql_Parameter::ParameterBindingParameterName" <-- "ssis.PackageTask_Sql_Parameter_src::ParameterBindingParameterName"
"ssis_t.TblTask_Sql_Parameter::ParameterBindingSequence" <-- "ssis.PackageTask_Sql_Parameter_src::ParameterBindingSequence"
"ssis_t.TblTask_Sql_Parameter::ResultSetParameterName" <-- "ssis.PackageTask_Sql_Parameter_src::ResultSetParameterName"footer The diagram is interactive and contains links.
@enduml

