@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis.packageflow_src.adoc[]" as ssis.PackageFlow_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **TaskFrom** : (varchar(2000))
  **Taskto** : (varchar(2000))
  CreationName : (nvarchar(max))
  DTSID : (uniqueidentifier)
  EvalOp : (int)
  Expression : (nvarchar(max))
  FlowType : (varchar(1000))
  LogicalAnd : (bit)
  ObjectName : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tblprecedenceconstraint.adoc[]" as ssis_t.TblPrecedenceConstraint << U >> {
  CreationName : (nvarchar(max))
  DTSID : (uniqueidentifier)
  EvalOp : (int)
  Expression : (nvarchar(max))
  FlowType : (varchar(1000))
  LogicalAnd : (bit)
  ObjectName : (nvarchar(max))
  PackagePath : (varchar(2000))
  RowID : (int)
  TaskFrom : (varchar(2000))
  Taskto : (varchar(2000))
  --
}

entity "puml-link:dhw:sqldb:ssis_t.usp_getpackagedetails.adoc[]" as ssis_t.usp_GetPackageDetails << P >> {
  --
}

ssis_t.TblPrecedenceConstraint <.. ssis.PackageFlow_src
ssis_t.TblPrecedenceConstraint <.. ssis_t.usp_GetPackageDetails
"ssis_t.TblPrecedenceConstraint::CreationName" <-- "ssis.PackageFlow_src::CreationName"
"ssis_t.TblPrecedenceConstraint::DTSID" <-- "ssis.PackageFlow_src::DTSID"
"ssis_t.TblPrecedenceConstraint::EvalOp" <-- "ssis.PackageFlow_src::EvalOp"
"ssis_t.TblPrecedenceConstraint::Expression" <-- "ssis.PackageFlow_src::Expression"
"ssis_t.TblPrecedenceConstraint::FlowType" <-- "ssis.PackageFlow_src::FlowType"
"ssis_t.TblPrecedenceConstraint::LogicalAnd" <-- "ssis.PackageFlow_src::LogicalAnd"
"ssis_t.TblPrecedenceConstraint::ObjectName" <-- "ssis.PackageFlow_src::ObjectName"
"ssis_t.TblPrecedenceConstraint::TaskFrom" <-- "ssis.PackageFlow_src::TaskFrom"
"ssis_t.TblPrecedenceConstraint::Taskto" <-- "ssis.PackageFlow_src::Taskto"footer The diagram is interactive and contains links.
@enduml

