@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis.antoramodule_tgt_filter.adoc[]" as ssis.AntoraModule_tgt_filter << V >> {
  - AntoraModule : (varchar(50))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_input.adoc[]" as ssis.PackageTask_Dft_Component_input << U >> {
  - AntoraModule : (varchar(50))
  Component_refId : (varchar(max))
  - ControlFlowDetailsRowID : (int)
  input_errorOrTruncationOperation : (varchar(100))
  input_errorRowDisposition : (varchar(100))
  input_hasSideEffects : (bit)
  input_name : (varchar(500))
  input_refId : (varchar(max))
  PackageName : (varchar(200))
  TaskPath : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_input_src.adoc[]" as ssis.PackageTask_Dft_Component_input_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **input_refId** : (varchar(max))
  Component_refId : (varchar(max))
  - ControlFlowDetailsRowID : (int)
  input_errorOrTruncationOperation : (varchar(100))
  input_errorRowDisposition : (varchar(100))
  input_hasSideEffects : (bit)
  input_name : (varchar(500))
  TaskPath : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_input_tgt.adoc[]" as ssis.PackageTask_Dft_Component_input_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **input_refId** : (varchar(max))
  Component_refId : (varchar(max))
  - ControlFlowDetailsRowID : (int)
  input_errorOrTruncationOperation : (varchar(100))
  input_errorRowDisposition : (varchar(100))
  input_hasSideEffects : (bit)
  input_name : (varchar(500))
  nodescontent : (xml)
  TaskPath : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packagetask_dft_component_input_tgt.adoc[]" as ssis.usp_PERSIST_PackageTask_Dft_Component_input_tgt << P >> {
  --
}

ssis.AntoraModule_tgt_filter <.. ssis.PackageTask_Dft_Component_input_tgt
ssis.PackageTask_Dft_Component_input <.. ssis.PackageTask_Dft_Component_input_tgt
ssis.PackageTask_Dft_Component_input_src <.. ssis.PackageTask_Dft_Component_input_tgt
ssis.PackageTask_Dft_Component_input_tgt <.. ssis.PackageTask_Dft_Component_input
ssis.PackageTask_Dft_Component_input_tgt <.. ssis.usp_PERSIST_PackageTask_Dft_Component_input_tgt
ssis.PackageTask_Dft_Component_input_tgt <.. ssis.AntoraModule_tgt_filter
"ssis.PackageTask_Dft_Component_input::AntoraModule" <-- "ssis.PackageTask_Dft_Component_input_tgt::AntoraModule"
"ssis.PackageTask_Dft_Component_input::Component_refId" <-- "ssis.PackageTask_Dft_Component_input_tgt::Component_refId"
"ssis.PackageTask_Dft_Component_input::ControlFlowDetailsRowID" <-- "ssis.PackageTask_Dft_Component_input_tgt::ControlFlowDetailsRowID"
"ssis.PackageTask_Dft_Component_input::input_errorOrTruncationOperation" <-- "ssis.PackageTask_Dft_Component_input_tgt::input_errorOrTruncationOperation"
"ssis.PackageTask_Dft_Component_input::input_errorRowDisposition" <-- "ssis.PackageTask_Dft_Component_input_tgt::input_errorRowDisposition"
"ssis.PackageTask_Dft_Component_input::input_hasSideEffects" <-- "ssis.PackageTask_Dft_Component_input_tgt::input_hasSideEffects"
"ssis.PackageTask_Dft_Component_input::input_name" <-- "ssis.PackageTask_Dft_Component_input_tgt::input_name"
"ssis.PackageTask_Dft_Component_input::input_refId" <-- "ssis.PackageTask_Dft_Component_input_tgt::input_refId"
"ssis.PackageTask_Dft_Component_input::PackageName" <-- "ssis.PackageTask_Dft_Component_input_tgt::PackageName"
"ssis.PackageTask_Dft_Component_input::TaskPath" <-- "ssis.PackageTask_Dft_Component_input_tgt::TaskPath"
"ssis.PackageTask_Dft_Component_input_src::AntoraModule" <-- "ssis.PackageTask_Dft_Component_input_tgt::AntoraModule"
"ssis.PackageTask_Dft_Component_input_src::Component_refId" <-- "ssis.PackageTask_Dft_Component_input_tgt::Component_refId"
"ssis.PackageTask_Dft_Component_input_src::ControlFlowDetailsRowID" <-- "ssis.PackageTask_Dft_Component_input_tgt::ControlFlowDetailsRowID"
"ssis.PackageTask_Dft_Component_input_src::input_errorOrTruncationOperation" <-- "ssis.PackageTask_Dft_Component_input_tgt::input_errorOrTruncationOperation"
"ssis.PackageTask_Dft_Component_input_src::input_errorRowDisposition" <-- "ssis.PackageTask_Dft_Component_input_tgt::input_errorRowDisposition"
"ssis.PackageTask_Dft_Component_input_src::input_hasSideEffects" <-- "ssis.PackageTask_Dft_Component_input_tgt::input_hasSideEffects"
"ssis.PackageTask_Dft_Component_input_src::input_name" <-- "ssis.PackageTask_Dft_Component_input_tgt::input_name"
"ssis.PackageTask_Dft_Component_input_src::input_refId" <-- "ssis.PackageTask_Dft_Component_input_tgt::input_refId"
"ssis.PackageTask_Dft_Component_input_src::PackageName" <-- "ssis.PackageTask_Dft_Component_input_tgt::PackageName"
"ssis.PackageTask_Dft_Component_input_src::TaskPath" <-- "ssis.PackageTask_Dft_Component_input_tgt::TaskPath"footer The diagram is interactive and contains links.
@enduml

