@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis.antoramodule_tgt_filter.adoc[]" as ssis.AntoraModule_tgt_filter << V >> {
  - AntoraModule : (varchar(50))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask.adoc[]" as ssis.PackageTask << U >> {
  - AntoraModule : (varchar(50))
  - ControlFlowDetailsRowID : (int)
  DelayValidationPropertyValue : (varchar(100))
  ExecutedPackageName : (varchar(1000))
  ExecutePackageConnection : (varchar(1000))
  ExecutePackageExpression : (varchar(1000))
  ExpressionValue : (varchar(5000))
  IsDisabled : (varchar(10))
  - PackageName : (varchar(200))
  Script : (varchar(max))
  SqlConnection : (uniqueidentifier)
  SqlStatementSource : (nvarchar(max))
  TaskDescription : (varchar(max))
  - TaskName : (varchar(2000))
  - TaskPath : (varchar(8000))
  TaskType : (varchar(5000))
  # PackageBasename : (varchar(8000))
  # TaskPathLevel : (int)
  # TaskPathParent : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_src.adoc[]" as ssis.PackageTask_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **TaskPath** : (varchar(8000))
  - ControlFlowDetailsRowID : (int)
  DelayValidationPropertyValue : (varchar(100))
  ExecutedPackageName : (varchar(1000))
  ExecutePackageConnection : (varchar(1000))
  ExecutePackageExpression : (varchar(1000))
  ExpressionValue : (varchar(5000))
  IsDisabled : (varchar(10))
  Script : (varchar(max))
  SqlConnection : (uniqueidentifier)
  SqlStatementSource : (nvarchar(max))
  TaskDescription : (varchar(max))
  TaskName : (varchar(2000))
  TaskType : (varchar(5000))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_tgt.adoc[]" as ssis.PackageTask_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **TaskPath** : (varchar(8000))
  - ControlFlowDetailsRowID : (int)
  DelayValidationPropertyValue : (varchar(100))
  DFTQuery : (xml)
  ExecPkgTaskQry : (xml)
  ExecutedPackageName : (varchar(1000))
  ExecutePackageConnection : (varchar(1000))
  ExecutePackageExpression : (varchar(1000))
  ExpressionValue : (varchar(5000))
  IsDisabled : (varchar(10))
  Script : (varchar(max))
  ScriptTaskQry : (xml)
  SqlConnection : (uniqueidentifier)
  SqlStatementSource : (nvarchar(max))
  SqlTaskQry : (xml)
  TaskDescription : (varchar(max))
  TaskName : (varchar(2000))
  TaskType : (varchar(5000))
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packagetask_tgt.adoc[]" as ssis.usp_PERSIST_PackageTask_tgt << P >> {
  --
}

ssis.AntoraModule_tgt_filter <.. ssis.PackageTask_tgt
ssis.PackageTask <.. ssis.PackageTask_tgt
ssis.PackageTask_src <.. ssis.PackageTask_tgt
ssis.PackageTask_tgt <.. ssis.PackageTask
ssis.PackageTask_tgt <.. ssis.usp_PERSIST_PackageTask_tgt
ssis.PackageTask_tgt <.. ssis.AntoraModule_tgt_filter
"ssis.PackageTask::AntoraModule" <-- "ssis.PackageTask_tgt::AntoraModule"
"ssis.PackageTask::ControlFlowDetailsRowID" <-- "ssis.PackageTask_tgt::ControlFlowDetailsRowID"
"ssis.PackageTask::DelayValidationPropertyValue" <-- "ssis.PackageTask_tgt::DelayValidationPropertyValue"
"ssis.PackageTask::ExecutedPackageName" <-- "ssis.PackageTask_tgt::ExecutedPackageName"
"ssis.PackageTask::ExecutePackageConnection" <-- "ssis.PackageTask_tgt::ExecutePackageConnection"
"ssis.PackageTask::ExecutePackageExpression" <-- "ssis.PackageTask_tgt::ExecutePackageExpression"
"ssis.PackageTask::ExpressionValue" <-- "ssis.PackageTask_tgt::ExpressionValue"
"ssis.PackageTask::IsDisabled" <-- "ssis.PackageTask_tgt::IsDisabled"
"ssis.PackageTask::PackageName" <-- "ssis.PackageTask_tgt::PackageName"
"ssis.PackageTask::Script" <-- "ssis.PackageTask_tgt::Script"
"ssis.PackageTask::SqlConnection" <-- "ssis.PackageTask_tgt::SqlConnection"
"ssis.PackageTask::SqlStatementSource" <-- "ssis.PackageTask_tgt::SqlStatementSource"
"ssis.PackageTask::TaskDescription" <-- "ssis.PackageTask_tgt::TaskDescription"
"ssis.PackageTask::TaskName" <-- "ssis.PackageTask_tgt::TaskName"
"ssis.PackageTask::TaskPath" <-- "ssis.PackageTask_tgt::TaskPath"
"ssis.PackageTask::TaskType" <-- "ssis.PackageTask_tgt::TaskType"
"ssis.PackageTask_src::AntoraModule" <-- "ssis.PackageTask_tgt::AntoraModule"
"ssis.PackageTask_src::ControlFlowDetailsRowID" <-- "ssis.PackageTask_tgt::ControlFlowDetailsRowID"
"ssis.PackageTask_src::DelayValidationPropertyValue" <-- "ssis.PackageTask_tgt::DelayValidationPropertyValue"
"ssis.PackageTask_src::ExecutedPackageName" <-- "ssis.PackageTask_tgt::ExecutedPackageName"
"ssis.PackageTask_src::ExecutePackageConnection" <-- "ssis.PackageTask_tgt::ExecutePackageConnection"
"ssis.PackageTask_src::ExecutePackageExpression" <-- "ssis.PackageTask_tgt::ExecutePackageExpression"
"ssis.PackageTask_src::ExpressionValue" <-- "ssis.PackageTask_tgt::ExpressionValue"
"ssis.PackageTask_src::IsDisabled" <-- "ssis.PackageTask_tgt::IsDisabled"
"ssis.PackageTask_src::PackageName" <-- "ssis.PackageTask_tgt::PackageName"
"ssis.PackageTask_src::Script" <-- "ssis.PackageTask_tgt::Script"
"ssis.PackageTask_src::SqlConnection" <-- "ssis.PackageTask_tgt::SqlConnection"
"ssis.PackageTask_src::SqlStatementSource" <-- "ssis.PackageTask_tgt::SqlStatementSource"
"ssis.PackageTask_src::TaskDescription" <-- "ssis.PackageTask_tgt::TaskDescription"
"ssis.PackageTask_src::TaskName" <-- "ssis.PackageTask_tgt::TaskName"
"ssis.PackageTask_src::TaskPath" <-- "ssis.PackageTask_tgt::TaskPath"
"ssis.PackageTask_src::TaskType" <-- "ssis.PackageTask_tgt::TaskType"footer The diagram is interactive and contains links.
@enduml

