@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:docs.ssis_dfttaskcomponentinputcolumnlist.adoc[]" as docs.ssis_DftTaskComponentInputColumnList << V >> {
  - AntoraModule : (varchar(50))
  Component_refId : (varchar(max))
  - DftTaskComponentInputColumnList : (nvarchar(max))
  input_refId : (varchar(max))
  PackageName : (varchar(200))
  TaskPath : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:docs.ssis_dfttaskcomponentoutputcolumnlist.adoc[]" as docs.ssis_DftTaskComponentOutputColumnList << V >> {
  - AntoraModule : (varchar(50))
  Component_refId : (varchar(max))
  - DftTaskComponentOutputColumnList : (nvarchar(max))
  output_refId : (varchar(max))
  PackageName : (varchar(200))
  TaskPath : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_input_externalmetadatacolumn.adoc[]" as ssis.PackageTask_Dft_Component_input_externalMetadataColumn << U >> {
  - AntoraModule : (varchar(50))
  Column_dataType : (varchar(100))
  Column_length : (int)
  Column_name : (varchar(max))
  Column_precision : (int)
  Column_refId : (varchar(max))
  Column_scale : (int)
  Component_refId : (varchar(max))
  - ControlFlowDetailsRowID : (int)
  externalMetadataColumns_isused : (bit)
  input_errorOrTruncationOperation : (varchar(100))
  input_errorRowDisposition : (varchar(100))
  input_hasSideEffects : (bit)
  input_name : (varchar(500))
  input_refId : (varchar(max))
  PackageName : (varchar(200))
  TaskPath : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_input_externalmetadatacolumn_tgt.adoc[]" as ssis.PackageTask_Dft_Component_input_externalMetadataColumn_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Column_refId** : (varchar(max))
  Column_dataType : (varchar(100))
  Column_length : (int)
  Column_name : (varchar(max))
  Column_precision : (int)
  Column_scale : (int)
  Component_refId : (varchar(max))
  - ControlFlowDetailsRowID : (int)
  externalMetadataColumns_isused : (bit)
  input_errorOrTruncationOperation : (varchar(100))
  input_errorRowDisposition : (varchar(100))
  input_hasSideEffects : (bit)
  input_name : (varchar(500))
  input_refId : (varchar(max))
  TaskPath : (varchar(8000))
  --
}

ssis.PackageTask_Dft_Component_input_externalMetadataColumn <.. docs.ssis_DftTaskComponentOutputColumnList
ssis.PackageTask_Dft_Component_input_externalMetadataColumn <.. ssis.PackageTask_Dft_Component_input_externalMetadataColumn_tgt
ssis.PackageTask_Dft_Component_input_externalMetadataColumn <.. docs.ssis_DftTaskComponentInputColumnList
ssis.PackageTask_Dft_Component_input_externalMetadataColumn_tgt <.. ssis.PackageTask_Dft_Component_input_externalMetadataColumn
"ssis.PackageTask_Dft_Component_input_externalMetadataColumn::AntoraModule" <-- "ssis.PackageTask_Dft_Component_input_externalMetadataColumn_tgt::AntoraModule"
"ssis.PackageTask_Dft_Component_input_externalMetadataColumn::Column_dataType" <-- "ssis.PackageTask_Dft_Component_input_externalMetadataColumn_tgt::Column_dataType"
"ssis.PackageTask_Dft_Component_input_externalMetadataColumn::Column_length" <-- "ssis.PackageTask_Dft_Component_input_externalMetadataColumn_tgt::Column_length"
"ssis.PackageTask_Dft_Component_input_externalMetadataColumn::Column_name" <-- "ssis.PackageTask_Dft_Component_input_externalMetadataColumn_tgt::Column_name"
"ssis.PackageTask_Dft_Component_input_externalMetadataColumn::Column_precision" <-- "ssis.PackageTask_Dft_Component_input_externalMetadataColumn_tgt::Column_precision"
"ssis.PackageTask_Dft_Component_input_externalMetadataColumn::Column_refId" <-- "ssis.PackageTask_Dft_Component_input_externalMetadataColumn_tgt::Column_refId"
"ssis.PackageTask_Dft_Component_input_externalMetadataColumn::Column_scale" <-- "ssis.PackageTask_Dft_Component_input_externalMetadataColumn_tgt::Column_scale"
"ssis.PackageTask_Dft_Component_input_externalMetadataColumn::Component_refId" <-- "ssis.PackageTask_Dft_Component_input_externalMetadataColumn_tgt::Component_refId"
"ssis.PackageTask_Dft_Component_input_externalMetadataColumn::ControlFlowDetailsRowID" <-- "ssis.PackageTask_Dft_Component_input_externalMetadataColumn_tgt::ControlFlowDetailsRowID"
"ssis.PackageTask_Dft_Component_input_externalMetadataColumn::externalMetadataColumns_isused" <-- "ssis.PackageTask_Dft_Component_input_externalMetadataColumn_tgt::externalMetadataColumns_isused"
"ssis.PackageTask_Dft_Component_input_externalMetadataColumn::input_errorOrTruncationOperation" <-- "ssis.PackageTask_Dft_Component_input_externalMetadataColumn_tgt::input_errorOrTruncationOperation"
"ssis.PackageTask_Dft_Component_input_externalMetadataColumn::input_errorRowDisposition" <-- "ssis.PackageTask_Dft_Component_input_externalMetadataColumn_tgt::input_errorRowDisposition"
"ssis.PackageTask_Dft_Component_input_externalMetadataColumn::input_hasSideEffects" <-- "ssis.PackageTask_Dft_Component_input_externalMetadataColumn_tgt::input_hasSideEffects"
"ssis.PackageTask_Dft_Component_input_externalMetadataColumn::input_name" <-- "ssis.PackageTask_Dft_Component_input_externalMetadataColumn_tgt::input_name"
"ssis.PackageTask_Dft_Component_input_externalMetadataColumn::input_refId" <-- "ssis.PackageTask_Dft_Component_input_externalMetadataColumn_tgt::input_refId"
"ssis.PackageTask_Dft_Component_input_externalMetadataColumn::PackageName" <-- "ssis.PackageTask_Dft_Component_input_externalMetadataColumn_tgt::PackageName"
"ssis.PackageTask_Dft_Component_input_externalMetadataColumn::TaskPath" <-- "ssis.PackageTask_Dft_Component_input_externalMetadataColumn_tgt::TaskPath"footer The diagram is interactive and contains links.
@enduml

