@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis_t.packageanalysis.adoc[]" as ssis_t.PackageAnalysis << U >> {
  Category : (varchar(1000))
  ConnectionManager : (varchar(5000))
  ConnectionManagerID : (varchar(100))
  DelayValidationPropertyValue : (varchar(10))
  DerivedValue : (varchar(5000))
  DestinationColumn : (varchar(5000))
  ExecutedPackageName : (varchar(8000))
  ExecutePackageConnection : (varchar(8000))
  ExecutePackageExpression : (varchar(8000))
  ExpressionValue : (varchar(5000))
  IsDisabled : (varchar(10))
  IsSortedProperty : (varchar(10))
  LookupJoins : (varchar(8000))
  MultihashcolumnSortPosition : (varchar(max))
  ObjectName : (varchar(500))
  ObjectType : (varchar(max))
  ObjectTypeDescription : (varchar(max))
  ObjectValue : (varchar(max))
  PackageCreatorName : (varchar(1000))
  PackageName : (varchar(max))
  PackagePath : (varchar(5000))
  PackageProtectionLevel : (varchar(100))
  PackageSequenceNo : (int)
  ParameterBindingParameterName : (varchar(1000))
  ParameterBindingSequence : (varchar(1000))
  ResultSetParameterName : (varchar(1000))
  RetainSameConnectionProperty : (varchar(100))
  RowID : (int)
  Script : (varchar(max))
  SequenceNo : (int)
  SortKeyPosition : (varchar(10))
  SourceColumn : (varchar(5000))
  - TableRowID : (int)
  TaskPath : (varchar(max))
  Variable : (varchar(1000))
  --
}

entity "puml-link:dhw:sqldb:ssis_t.usp_packageanalysis.adoc[]" as ssis_t.usp_PackageAnalysis << P >> {
  --
}

ssis_t.PackageAnalysis <.. ssis_t.usp_PackageAnalysis
footer The diagram is interactive and contains links.
@enduml

