@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis.package_src.adoc[]" as ssis.Package_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  PackageCreationDate : (datetime)
  PackageCreatorComputerName : (nvarchar(500))
  PackageCreatorName : (varchar(1000))
  PackageDescription : (nvarchar(max))
  PackageDTSID : (uniqueidentifier)
  PackageLastModifiedProductVersion : (nvarchar(500))
  PackageLocaleID : (int)
  PackageObjectName : (nvarchar(500))
  - PackagePath : (varchar(8000))
  PackageProtectionLevel : (varchar(100))
  PackageProtectionLevelName : (varchar(28))
  PackageVersionGUID : (uniqueidentifier)
  - ProjectPath : (varchar(8000))
  - RowID : (int)
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_src.adoc[]" as ssis.PackageTask_Dft_Component_src << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Component_refId** : (varchar(max))
  Component_AccessMode : (varchar(max))
  Component_AlwaysUseDefaultCodePage : (varchar(max))
  Component_CommandTimeout : (int)
  Component_componentClassID : (varchar(max))
  Component_Connection_description : (varchar(max))
  Component_Connection_name : (varchar(max))
  Component_Connection_refId : (varchar(max))
  Component_connectionManagerID : (varchar(max))
  Component_connectionManagerRefId : (varchar(max))
  Component_ContactInfo : (varchar(max))
  Component_DefaultCodePage : (int)
  Component_description : (varchar(max))
  Component_FastLoadKeepIdentity : (bit)
  Component_FastLoadKeepNulls : (bit)
  Component_FastLoadMaxInsertCommitSize : (int)
  Component_FastLoadOptions : (varchar(max))
  Component_IsSortedProperty : (varchar(10))
  Component_name : (varchar(max))
  Component_OpenRowset : (varchar(max))
  Component_OpenRowsetVariable : (varchar(max))
  Component_ParameterMapping : (varchar(max))
  Component_SqlCommand : (varchar(max))
  Component_SqlCommandVariable : (varchar(max))
  Component_VariableName : (varchar(max))
  - ControlFlowDetailsRowID : (int)
  TaskPath : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:ssis.packagetask_dft_component_tgt.adoc[]" as ssis.PackageTask_Dft_Component_tgt << V >> {
  - **AntoraModule** : (varchar(50))
  **PackageName** : (varchar(200))
  **Component_refId** : (varchar(max))
  Component_AccessMode : (varchar(max))
  Component_AlwaysUseDefaultCodePage : (varchar(max))
  Component_CommandTimeout : (int)
  Component_componentClassID : (varchar(max))
  Component_Connection_description : (varchar(max))
  Component_Connection_name : (varchar(max))
  Component_Connection_refId : (varchar(max))
  Component_connectionManagerID : (varchar(max))
  Component_connectionManagerRefId : (varchar(max))
  Component_ContactInfo : (varchar(max))
  Component_DefaultCodePage : (int)
  Component_description : (varchar(max))
  Component_FastLoadKeepIdentity : (bit)
  Component_FastLoadKeepNulls : (bit)
  Component_FastLoadMaxInsertCommitSize : (int)
  Component_FastLoadOptions : (varchar(max))
  Component_IsSortedProperty : (varchar(10))
  Component_name : (varchar(max))
  Component_OpenRowset : (varchar(max))
  Component_OpenRowsetVariable : (varchar(max))
  Component_ParameterMapping : (varchar(max))
  Component_SqlCommand : (varchar(max))
  Component_SqlCommandVariable : (varchar(max))
  Component_VariableName : (varchar(max))
  - ControlFlowDetailsRowID : (int)
  TaskPath : (varchar(8000))
  --
}

entity "puml-link:dhw:sqldb:ssis.usp_persist_packagetask_dft_component_tgt.adoc[]" as ssis.usp_PERSIST_PackageTask_Dft_Component_tgt << P >> {
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tblcontrolflow.adoc[]" as ssis_t.TblControlFlow << U >> {
  - **ControlFlowDetailsRowID** : (int)
  DelayValidationPropertyValue : (varchar(100))
  DFTQuery : (xml)
  ExecPkgTaskQry : (xml)
  ExpressionValue : (varchar(5000))
  IsDisabled : (varchar(10))
  RowID : (int)
  ScriptTaskQry : (xml)
  SqlTaskQry : (xml)
  TaskDescription : (varchar(max))
  TaskName : (varchar(2000))
  TaskPath : (varchar(8000))
  TaskType : (varchar(5000))
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_dft_component.adoc[]" as ssis_t.TblTask_Dft_Component << U >> {
  - **DftComponentId** : (int)
  AccessMode : (varchar(max))
  AlwaysUseDefaultCodePage : (varchar(max))
  CommandTimeout : (int)
  componentClassID : (varchar(max))
  Connection_description : (varchar(max))
  Connection_name : (varchar(max))
  Connection_refId : (varchar(max))
  connectionManagerID : (varchar(max))
  connectionManagerRefId : (varchar(max))
  ContactInfo : (varchar(max))
  - ControlFlowDetailsRowID : (int)
  DefaultCodePage : (int)
  description : (varchar(max))
  FastLoadKeepIdentity : (bit)
  FastLoadKeepNulls : (bit)
  FastLoadMaxInsertCommitSize : (int)
  FastLoadOptions : (varchar(max))
  inputsQry : (xml)
  IsSortedProperty : (varchar(10))
  name : (varchar(max))
  OpenRowset : (varchar(max))
  OpenRowsetVariable : (varchar(max))
  outputsQry : (xml)
  ParameterMapping : (varchar(max))
  refId : (varchar(max))
  RowID : (int)
  SqlCommand : (varchar(max))
  SqlCommandVariable : (varchar(max))
  VariableName : (varchar(max))
  --
}

ssis.Package_src <.. ssis.PackageTask_Dft_Component_src
ssis.PackageTask_Dft_Component_src <.. ssis.PackageTask_Dft_Component_tgt
ssis.PackageTask_Dft_Component_src <.. ssis.usp_PERSIST_PackageTask_Dft_Component_tgt
ssis_t.TblControlFlow <.. ssis.PackageTask_Dft_Component_src
ssis_t.TblTask_Dft_Component <.. ssis.PackageTask_Dft_Component_src
"ssis.Package_src::AntoraModule" <-- "ssis.PackageTask_Dft_Component_src::AntoraModule"
"ssis.Package_src::PackageName" <-- "ssis.PackageTask_Dft_Component_src::PackageName"
"ssis.PackageTask_Dft_Component_src::AntoraModule" <-- "ssis.PackageTask_Dft_Component_tgt::AntoraModule"
"ssis.PackageTask_Dft_Component_src::Component_AccessMode" <-- "ssis.PackageTask_Dft_Component_tgt::Component_AccessMode"
"ssis.PackageTask_Dft_Component_src::Component_AlwaysUseDefaultCodePage" <-- "ssis.PackageTask_Dft_Component_tgt::Component_AlwaysUseDefaultCodePage"
"ssis.PackageTask_Dft_Component_src::Component_CommandTimeout" <-- "ssis.PackageTask_Dft_Component_tgt::Component_CommandTimeout"
"ssis.PackageTask_Dft_Component_src::Component_componentClassID" <-- "ssis.PackageTask_Dft_Component_tgt::Component_componentClassID"
"ssis.PackageTask_Dft_Component_src::Component_Connection_description" <-- "ssis.PackageTask_Dft_Component_tgt::Component_Connection_description"
"ssis.PackageTask_Dft_Component_src::Component_Connection_name" <-- "ssis.PackageTask_Dft_Component_tgt::Component_Connection_name"
"ssis.PackageTask_Dft_Component_src::Component_Connection_refId" <-- "ssis.PackageTask_Dft_Component_tgt::Component_Connection_refId"
"ssis.PackageTask_Dft_Component_src::Component_connectionManagerID" <-- "ssis.PackageTask_Dft_Component_tgt::Component_connectionManagerID"
"ssis.PackageTask_Dft_Component_src::Component_connectionManagerRefId" <-- "ssis.PackageTask_Dft_Component_tgt::Component_connectionManagerRefId"
"ssis.PackageTask_Dft_Component_src::Component_ContactInfo" <-- "ssis.PackageTask_Dft_Component_tgt::Component_ContactInfo"
"ssis.PackageTask_Dft_Component_src::Component_DefaultCodePage" <-- "ssis.PackageTask_Dft_Component_tgt::Component_DefaultCodePage"
"ssis.PackageTask_Dft_Component_src::Component_description" <-- "ssis.PackageTask_Dft_Component_tgt::Component_description"
"ssis.PackageTask_Dft_Component_src::Component_FastLoadKeepIdentity" <-- "ssis.PackageTask_Dft_Component_tgt::Component_FastLoadKeepIdentity"
"ssis.PackageTask_Dft_Component_src::Component_FastLoadKeepNulls" <-- "ssis.PackageTask_Dft_Component_tgt::Component_FastLoadKeepNulls"
"ssis.PackageTask_Dft_Component_src::Component_FastLoadMaxInsertCommitSize" <-- "ssis.PackageTask_Dft_Component_tgt::Component_FastLoadMaxInsertCommitSize"
"ssis.PackageTask_Dft_Component_src::Component_FastLoadOptions" <-- "ssis.PackageTask_Dft_Component_tgt::Component_FastLoadOptions"
"ssis.PackageTask_Dft_Component_src::Component_IsSortedProperty" <-- "ssis.PackageTask_Dft_Component_tgt::Component_IsSortedProperty"
"ssis.PackageTask_Dft_Component_src::Component_name" <-- "ssis.PackageTask_Dft_Component_tgt::Component_name"
"ssis.PackageTask_Dft_Component_src::Component_OpenRowset" <-- "ssis.PackageTask_Dft_Component_tgt::Component_OpenRowset"
"ssis.PackageTask_Dft_Component_src::Component_OpenRowsetVariable" <-- "ssis.PackageTask_Dft_Component_tgt::Component_OpenRowsetVariable"
"ssis.PackageTask_Dft_Component_src::Component_ParameterMapping" <-- "ssis.PackageTask_Dft_Component_tgt::Component_ParameterMapping"
"ssis.PackageTask_Dft_Component_src::Component_refId" <-- "ssis.PackageTask_Dft_Component_tgt::Component_refId"
"ssis.PackageTask_Dft_Component_src::Component_SqlCommand" <-- "ssis.PackageTask_Dft_Component_tgt::Component_SqlCommand"
"ssis.PackageTask_Dft_Component_src::Component_SqlCommandVariable" <-- "ssis.PackageTask_Dft_Component_tgt::Component_SqlCommandVariable"
"ssis.PackageTask_Dft_Component_src::Component_VariableName" <-- "ssis.PackageTask_Dft_Component_tgt::Component_VariableName"
"ssis.PackageTask_Dft_Component_src::ControlFlowDetailsRowID" <-- "ssis.PackageTask_Dft_Component_tgt::ControlFlowDetailsRowID"
"ssis.PackageTask_Dft_Component_src::PackageName" <-- "ssis.PackageTask_Dft_Component_tgt::PackageName"
"ssis.PackageTask_Dft_Component_src::TaskPath" <-- "ssis.PackageTask_Dft_Component_tgt::TaskPath"
"ssis_t.TblControlFlow::ControlFlowDetailsRowID" <-- "ssis.PackageTask_Dft_Component_src::ControlFlowDetailsRowID"
"ssis_t.TblControlFlow::TaskPath" <-- "ssis.PackageTask_Dft_Component_src::TaskPath"
"ssis_t.TblTask_Dft_Component::AccessMode" <-- "ssis.PackageTask_Dft_Component_src::Component_AccessMode"
"ssis_t.TblTask_Dft_Component::AlwaysUseDefaultCodePage" <-- "ssis.PackageTask_Dft_Component_src::Component_AlwaysUseDefaultCodePage"
"ssis_t.TblTask_Dft_Component::CommandTimeout" <-- "ssis.PackageTask_Dft_Component_src::Component_CommandTimeout"
"ssis_t.TblTask_Dft_Component::componentClassID" <-- "ssis.PackageTask_Dft_Component_src::Component_componentClassID"
"ssis_t.TblTask_Dft_Component::Connection_description" <-- "ssis.PackageTask_Dft_Component_src::Component_Connection_description"
"ssis_t.TblTask_Dft_Component::Connection_name" <-- "ssis.PackageTask_Dft_Component_src::Component_Connection_name"
"ssis_t.TblTask_Dft_Component::Connection_refId" <-- "ssis.PackageTask_Dft_Component_src::Component_Connection_refId"
"ssis_t.TblTask_Dft_Component::connectionManagerID" <-- "ssis.PackageTask_Dft_Component_src::Component_connectionManagerID"
"ssis_t.TblTask_Dft_Component::connectionManagerRefId" <-- "ssis.PackageTask_Dft_Component_src::Component_connectionManagerRefId"
"ssis_t.TblTask_Dft_Component::ContactInfo" <-- "ssis.PackageTask_Dft_Component_src::Component_ContactInfo"
"ssis_t.TblTask_Dft_Component::DefaultCodePage" <-- "ssis.PackageTask_Dft_Component_src::Component_DefaultCodePage"
"ssis_t.TblTask_Dft_Component::description" <-- "ssis.PackageTask_Dft_Component_src::Component_description"
"ssis_t.TblTask_Dft_Component::FastLoadKeepIdentity" <-- "ssis.PackageTask_Dft_Component_src::Component_FastLoadKeepIdentity"
"ssis_t.TblTask_Dft_Component::FastLoadKeepNulls" <-- "ssis.PackageTask_Dft_Component_src::Component_FastLoadKeepNulls"
"ssis_t.TblTask_Dft_Component::FastLoadMaxInsertCommitSize" <-- "ssis.PackageTask_Dft_Component_src::Component_FastLoadMaxInsertCommitSize"
"ssis_t.TblTask_Dft_Component::FastLoadOptions" <-- "ssis.PackageTask_Dft_Component_src::Component_FastLoadOptions"
"ssis_t.TblTask_Dft_Component::IsSortedProperty" <-- "ssis.PackageTask_Dft_Component_src::Component_IsSortedProperty"
"ssis_t.TblTask_Dft_Component::name" <-- "ssis.PackageTask_Dft_Component_src::Component_name"
"ssis_t.TblTask_Dft_Component::OpenRowset" <-- "ssis.PackageTask_Dft_Component_src::Component_OpenRowset"
"ssis_t.TblTask_Dft_Component::OpenRowsetVariable" <-- "ssis.PackageTask_Dft_Component_src::Component_OpenRowsetVariable"
"ssis_t.TblTask_Dft_Component::ParameterMapping" <-- "ssis.PackageTask_Dft_Component_src::Component_ParameterMapping"
"ssis_t.TblTask_Dft_Component::refId" <-- "ssis.PackageTask_Dft_Component_src::Component_refId"
"ssis_t.TblTask_Dft_Component::SqlCommand" <-- "ssis.PackageTask_Dft_Component_src::Component_SqlCommand"
"ssis_t.TblTask_Dft_Component::SqlCommandVariable" <-- "ssis.PackageTask_Dft_Component_src::Component_SqlCommandVariable"
"ssis_t.TblTask_Dft_Component::VariableName" <-- "ssis.PackageTask_Dft_Component_src::Component_VariableName"footer The diagram is interactive and contains links.
@enduml

