@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:ssis_t.tbltask_dft_details.adoc[]" as ssis_t.TblTask_Dft_Details << U >> {
  ControlFlowDetailsRowID : (int)
  - DataFlowDetailsRowID : (int)
  DFTConnectionManager : (varchar(max))
  DFTRowSet : (varchar(max))
  DFTSQLCommand : (varchar(max))
  DFTTaskName : (varchar(max))
  DFTTasksPath : (varchar(max))
  DFTTaskType : (varchar(max))
  DFTTaskType1 : (varchar(max))
  InputQry : (xml)
  IsSortedProperty : (varchar(10))
  MultihashcolumnSortPosition : (varchar(max))
  OutputQry : (xml)
  ParameterBindingParameterName : (varchar(2000))
  RowID : (int)
  Variable : (varchar(max))
  --
}

entity "puml-link:dhw:sqldb:ssis_t.tbltask_dft_step_src.adoc[]" as ssis_t.TblTask_Dft_Step_src << V >> {
  ControlFlowDetailsRowID : (int)
  DFTConnectionManager : (varchar(max))
  DFTRowSet : (varchar(max))
  DFTSQLCommand : (varchar(max))
  DFTTaskName : (varchar(max))
  DFTTasksPath : (varchar(max))
  DFTTaskType : (varchar(max))
  DFTTaskType1 : (varchar(max))
  IsSortedProperty : (varchar(10))
  ParameterBindingParameterName : (varchar(2000))
  RowID : (int)
  Variable : (varchar(max))
  --
}

ssis_t.TblTask_Dft_Details <.. ssis_t.TblTask_Dft_Step_src
"ssis_t.TblTask_Dft_Details::DFTConnectionManager" <-- "ssis_t.TblTask_Dft_Step_src::DFTConnectionManager"
"ssis_t.TblTask_Dft_Details::DFTRowSet" <-- "ssis_t.TblTask_Dft_Step_src::DFTRowSet"
"ssis_t.TblTask_Dft_Details::DFTSQLCommand" <-- "ssis_t.TblTask_Dft_Step_src::DFTSQLCommand"
"ssis_t.TblTask_Dft_Details::DFTTaskName" <-- "ssis_t.TblTask_Dft_Step_src::DFTTaskName"
"ssis_t.TblTask_Dft_Details::DFTTasksPath" <-- "ssis_t.TblTask_Dft_Step_src::DFTTasksPath"
"ssis_t.TblTask_Dft_Details::DFTTaskType" <-- "ssis_t.TblTask_Dft_Step_src::DFTTaskType"
"ssis_t.TblTask_Dft_Details::DFTTaskType1" <-- "ssis_t.TblTask_Dft_Step_src::DFTTaskType1"
"ssis_t.TblTask_Dft_Details::IsSortedProperty" <-- "ssis_t.TblTask_Dft_Step_src::IsSortedProperty"
"ssis_t.TblTask_Dft_Details::ParameterBindingParameterName" <-- "ssis_t.TblTask_Dft_Step_src::ParameterBindingParameterName"footer The diagram is interactive and contains links.
@enduml

