@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:config.ftv_dwh_database.adoc[]" as config.ftv_dwh_database << IF >> {
  dwh_database_id : (smallint)
  dwh_database_name : (nvarchar(128))
  --
}

entity "puml-link:dhw:sqldb:property.repoobjectproperty_collect_source_uspgenerator.adoc[]" as property.RepoObjectProperty_Collect_source_uspgenerator << V >> {
  **RepoObject_guid** : (uniqueidentifier)
  - **property_name** : (varchar(14))
  property_value : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:repo.repoobject.adoc[]" as repo.RepoObject << U >> {
  - **RepoObject_guid** : (uniqueidentifier)
  external_AntoraComponent : (nvarchar(128))
  external_AntoraModule : (nvarchar(128))
  has_execution_plan_issue : (bit)
  has_get_referenced_issue : (bit)
  Inheritance_Source_fullname : (nvarchar(261))
  Inheritance_StringAggSeparatorSql : (nvarchar(4000))
  InheritanceDefinition : (nvarchar(4000))
  InheritanceType : (tinyint)
  - is_DocsExclude : (bit)
  - is_external : (bit)
  is_repo_managed : (bit)
  is_required_ObjectMerge : (bit)
  - is_ssas : (bit)
  is_SysObject_missing : (bit)
  - modify_dt : (datetime)
  pk_index_guid : (uniqueidentifier)
  pk_IndexPatternColumnName_new : (nvarchar(4000))
  Repo_history_table_guid : (uniqueidentifier)
  Repo_temporal_type : (tinyint)
  - RepoObject_name : (nvarchar(128))
  RepoObject_Referencing_Count : (int)
  - RepoObject_schema_name : (nvarchar(128))
  - RepoObject_type : (char(2))
  SysObject_id : (int)
  SysObject_modify_date : (datetime)
  - SysObject_name : (nvarchar(128))
  - SysObject_parent_object_id : (int)
  - SysObject_schema_name : (nvarchar(128))
  SysObject_type : (char(2))
  ~ has_different_sys_names : (bit)
  # is_RepoObject_name_uniqueidentifier : (int)
  # is_SysObject_name_uniqueidentifier : (int)
  ~ node_id : (bigint)
  # RepoObject_fullname : (nvarchar(261))
  # RepoObject_fullname2 : (nvarchar(257))
  # SysObject_fullname : (nvarchar(261))
  # SysObject_fullname2 : (nvarchar(257))
  ~ SysObject_query_sql : (nvarchar(406))
  # usp_persistence_fullname2 : (nvarchar(269))
  # usp_persistence_name : (nvarchar(140))
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.generatorusp.adoc[]" as uspgenerator.GeneratorUsp << U >> {
  - **id** : (int)
  - has_logging : (tinyint)
  usp_Description : (nvarchar(4000))
  usp_Examples : (nvarchar(4000))
  - usp_name : (nvarchar(128))
  - usp_schema : (nvarchar(128))
  # usp_fullname : (nvarchar(261))
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.generatorusp_parameterlist.adoc[]" as uspgenerator.GeneratorUsp_ParameterList << V >> {
  - **usp_id** : (int)
  ParameterList : (nvarchar(max))
  ParameterListLogging : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.generatorusp_sqlusp.adoc[]" as uspgenerator.GeneratorUsp_SqlUsp << V >> {
  - AdocUspSteps : (nvarchar(max))
  - has_logging : (tinyint)
  MS_Description : (nvarchar(4000))
  RepoObject_guid : (uniqueidentifier)
  SqlStepList : (nvarchar(max))
  - SqlUsp : (nvarchar(max))
  usp_Description : (nvarchar(4000))
  - usp_fullname : (nvarchar(261))
  - usp_id : (int)
  - usp_name : (nvarchar(128))
  - usp_schema : (nvarchar(128))
  - UspExamples : (nvarchar(4000))
  UspParameters : (nvarchar(max))
  --
}

entity "puml-link:dhw:sqldb:uspgenerator.generatorusp_steplist.adoc[]" as uspgenerator.GeneratorUsp_StepList << V >> {
  AdocStepList : (nvarchar(max))
  StepList : (nvarchar(max))
  - usp_id : (int)
  --
}

config.ftv_dwh_database <.. uspgenerator.GeneratorUsp_SqlUsp
repo.RepoObject <.. uspgenerator.GeneratorUsp_SqlUsp
uspgenerator.GeneratorUsp <.. uspgenerator.GeneratorUsp_SqlUsp
uspgenerator.GeneratorUsp_ParameterList <.. uspgenerator.GeneratorUsp_SqlUsp
uspgenerator.GeneratorUsp_SqlUsp <.. property.RepoObjectProperty_Collect_source_uspgenerator
uspgenerator.GeneratorUsp_StepList <.. uspgenerator.GeneratorUsp_SqlUsp
"repo.RepoObject::RepoObject_guid" <-- "uspgenerator.GeneratorUsp_SqlUsp::RepoObject_guid"
"uspgenerator.GeneratorUsp::has_logging" <-- "uspgenerator.GeneratorUsp_SqlUsp::has_logging"
"uspgenerator.GeneratorUsp::id" <-- "uspgenerator.GeneratorUsp_SqlUsp::usp_id"
"uspgenerator.GeneratorUsp::usp_Description" <-- "uspgenerator.GeneratorUsp_SqlUsp::usp_Description"
"uspgenerator.GeneratorUsp::usp_Description" <-- "uspgenerator.GeneratorUsp_SqlUsp::MS_Description"
"uspgenerator.GeneratorUsp::usp_fullname" <-- "uspgenerator.GeneratorUsp_SqlUsp::usp_fullname"
"uspgenerator.GeneratorUsp::usp_name" <-- "uspgenerator.GeneratorUsp_SqlUsp::usp_name"
"uspgenerator.GeneratorUsp::usp_schema" <-- "uspgenerator.GeneratorUsp_SqlUsp::usp_schema"
"uspgenerator.GeneratorUsp_ParameterList::ParameterList" <-- "uspgenerator.GeneratorUsp_SqlUsp::UspParameters"
"uspgenerator.GeneratorUsp_SqlUsp::RepoObject_guid" <-- "property.RepoObjectProperty_Collect_source_uspgenerator::RepoObject_guid"
"uspgenerator.GeneratorUsp_StepList::StepList" <-- "uspgenerator.GeneratorUsp_SqlUsp::SqlStepList"footer The diagram is interactive and contains links.
@enduml

