@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
  BackgroundColor<<external>> AliceBlue
}


entity "puml-link:dhw:sqldb:reference.persistence.adoc[]" as reference.Persistence << V >> {
  --
  referenced_fullname : (nvarchar(261))
  referenced_RepoObject_guid : (uniqueidentifier)
  referenced_schema_name : (nvarchar(128))
  referenced_usp_persistence_name : (nvarchar(140))
  referenced_usp_persistence_RepoObject_guid : (uniqueidentifier)
  referencing_fullname : (nvarchar(261))
  referencing_RepoObject_guid : (uniqueidentifier)
  referencing_schema_name : (nvarchar(128))
  referencing_usp_persistence_name : (nvarchar(140))
  referencing_usp_persistence_RepoObject_guid : (uniqueidentifier)
  --
  --
}

entity "puml-link:dhw:sqldb:workflow.proceduredependency_input_persistencedependency.adoc[]" as workflow.ProcedureDependency_input_PersistenceDependency << V >> {
  **referenced_Procedure_RepoObject_guid** : (uniqueidentifier)
  **referencing_Procedure_RepoObject_guid** : (uniqueidentifier)
  --
  - is_PersistenceDependency : (int)
  referenced_RepoObject_guid : (uniqueidentifier)
  referencing_RepoObject_guid : (uniqueidentifier)
  --
  --
}

entity "puml-link:dhw:sqldb:workflow.proceduredependency_input_persistencedependency_s.adoc[]" as workflow.ProcedureDependency_input_PersistenceDependency_S << V >> {
  **referenced_Procedure_RepoObject_guid** : (uniqueidentifier)
  **referencing_Procedure_RepoObject_guid** : (uniqueidentifier)
  --
  - is_PersistenceDependency : (int)
  --
  --
}

entity "puml-link:dhw:sqldb:workflow.usp_persist_proceduredependency_input_persistencedependency.adoc[]" as workflow.usp_PERSIST_ProcedureDependency_input_PersistenceDependency << P >> {
  --
  --
  --
}

reference.Persistence <.. workflow.ProcedureDependency_input_PersistenceDependency_S
workflow.ProcedureDependency_input_PersistenceDependency_S <.. workflow.ProcedureDependency_input_PersistenceDependency
workflow.ProcedureDependency_input_PersistenceDependency_S <.. workflow.usp_PERSIST_ProcedureDependency_input_PersistenceDependency
"reference.Persistence::referenced_usp_persistence_RepoObject_guid" <-- "workflow.ProcedureDependency_input_PersistenceDependency_S::referenced_Procedure_RepoObject_guid"
"reference.Persistence::referencing_usp_persistence_RepoObject_guid" <-- "workflow.ProcedureDependency_input_PersistenceDependency_S::referencing_Procedure_RepoObject_guid"
"workflow.ProcedureDependency_input_PersistenceDependency_S::is_PersistenceDependency" <-- "workflow.ProcedureDependency_input_PersistenceDependency::is_PersistenceDependency"
"workflow.ProcedureDependency_input_PersistenceDependency_S::referenced_Procedure_RepoObject_guid" <-- "workflow.ProcedureDependency_input_PersistenceDependency::referenced_Procedure_RepoObject_guid"
"workflow.ProcedureDependency_input_PersistenceDependency_S::referencing_Procedure_RepoObject_guid" <-- "workflow.ProcedureDependency_input_PersistenceDependency::referencing_Procedure_RepoObject_guid"
@enduml

