left to right direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity workflow.B575429B-AC5E-43C2-9903-561A17C103CF << U >> {
  * **Workflow_id** : int
  * **referenced_Procedure_RepoObject_guid** : uniqueidentifier
  * **referencing_Procedure_RepoObject_guid** : uniqueidentifier
  --
  * is_redundant : bit
}

entity workflow.usp_PERSIST_Workflow_ProcedureDependency_T << P >> {
  --
}

entity workflow.usp_workflow << P >> {
  --
}

entity workflow.Workflow_ProcedureDependency_T_active << V >> {
  --
  * is_redundant : bit
  * referenced_Procedure_RepoObject_guid : uniqueidentifier
  * referencing_Procedure_RepoObject_guid : uniqueidentifier
  * Workflow_id : int
}

entity workflow.Workflow_ProcedureDependency_T_bidirectional << V >> {
  * **Workflow_id** : int
  * **referenced_Procedure_RepoObject_guid** : uniqueidentifier
  * **referencing_Procedure_RepoObject_guid** : uniqueidentifier
  --
  * referenced_RepoObject_fullname : nvarchar(261)
  * referencing_RepoObject_fullname : nvarchar(261)
}

workflow.Workflow_ProcedureDependency_T <.. workflow.Workflow_ProcedureDependency_T_active
workflow.Workflow_ProcedureDependency_T <.. workflow.usp_workflow
workflow.Workflow_ProcedureDependency_T <.. workflow.usp_PERSIST_Workflow_ProcedureDependency_T
workflow.Workflow_ProcedureDependency_T <.. workflow.Workflow_ProcedureDependency_T_bidirectional
workflow.Workflow_ProcedureDependency_T::is_redundant <-- workflow.Workflow_ProcedureDependency_T_active::is_redundant
workflow.Workflow_ProcedureDependency_T::referenced_Procedure_RepoObject_guid <-- workflow.Workflow_ProcedureDependency_T_active::referenced_Procedure_RepoObject_guid
workflow.Workflow_ProcedureDependency_T::referenced_Procedure_RepoObject_guid <-- workflow.Workflow_ProcedureDependency_T_bidirectional::referenced_Procedure_RepoObject_guid
workflow.Workflow_ProcedureDependency_T::referencing_Procedure_RepoObject_guid <-- workflow.Workflow_ProcedureDependency_T_active::referencing_Procedure_RepoObject_guid
workflow.Workflow_ProcedureDependency_T::referencing_Procedure_RepoObject_guid <-- workflow.Workflow_ProcedureDependency_T_bidirectional::referencing_Procedure_RepoObject_guid
workflow.Workflow_ProcedureDependency_T::Workflow_id <-- workflow.Workflow_ProcedureDependency_T_active::Workflow_id
workflow.Workflow_ProcedureDependency_T::Workflow_id <-- workflow.Workflow_ProcedureDependency_T_bidirectional::Workflow_id
