@startuml
left to right direction
'top to bottom direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity "[[{site-url}/{page-component-name}/current/{page-module}/workflow.ProcedureDependency.html workflow.ProcedureDependency]]" as workflow.ProcedureDependency << U >> {
  - **id** : (int)
  --
  Description : (nvarchar(4000))
  - is_active : (bit)
  - is_PersistenceDependency : (bit)
  - referenced_Procedure_RepoObject_guid : (uniqueidentifier)
  referenced_RepoObject_guid : (uniqueidentifier)
  - referencing_Procedure_RepoObject_guid : (uniqueidentifier)
  referencing_RepoObject_guid : (uniqueidentifier)
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/workflow.ProcedureDependency_gross.html workflow.ProcedureDependency_gross]]" as workflow.ProcedureDependency_gross << V >> {
  --
  Description : (nvarchar(4000))
  - id : (int)
  - is_active : (bit)
  - is_PersistenceDependency : (bit)
  - referenced_Procedure_RepoObject_guid : (uniqueidentifier)
  - referenced_RepoObject_fullname : (nvarchar(261))
  - referenced_RepoObject_fullname2 : (nvarchar(257))
  - referenced_RepoObject_schema_name : (nvarchar(128))
  - referencing_Procedure_RepoObject_guid : (uniqueidentifier)
  - referencing_RepoObject_fullname : (nvarchar(261))
  - referencing_RepoObject_fullname2 : (nvarchar(257))
  - referencing_RepoObject_schema_name : (nvarchar(128))
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/workflow.ProcedureDependency_input_PersistenceDependency.html workflow.ProcedureDependency_input_PersistenceDependency]]" as workflow.ProcedureDependency_input_PersistenceDependency << V >> {
  **referenced_Procedure_RepoObject_guid** : (uniqueidentifier)
  **referencing_Procedure_RepoObject_guid** : (uniqueidentifier)
  --
  - is_PersistenceDependency : (int)
  referenced_RepoObject_guid : (uniqueidentifier)
  referencing_RepoObject_guid : (uniqueidentifier)
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/workflow.Workflow_ProcedureDependency.html workflow.Workflow_ProcedureDependency]]" as workflow.Workflow_ProcedureDependency << V >> {
  --
  - referenced_Procedure_RepoObject_guid : (uniqueidentifier)
  - referencing_Procedure_RepoObject_guid : (uniqueidentifier)
  - Workflow_id : (int)
  --
  --
}

entity "[[{site-url}/{page-component-name}/current/{page-module}/workflow.Workflow_ProcedureDependency_all.html workflow.Workflow_ProcedureDependency_all]]" as workflow.Workflow_ProcedureDependency_all << V >> {
  --
  - referenced_Procedure_RepoObject_guid : (uniqueidentifier)
  - referencing_Procedure_RepoObject_guid : (uniqueidentifier)
  - Workflow_id : (int)
  --
  --
}

workflow.ProcedureDependency <.. workflow.ProcedureDependency_gross
workflow.ProcedureDependency <.. workflow.ProcedureDependency_input_PersistenceDependency
workflow.ProcedureDependency <.. workflow.Workflow_ProcedureDependency_all
workflow.ProcedureDependency <.. workflow.Workflow_ProcedureDependency
workflow.ProcedureDependency_input_PersistenceDependency <.. workflow.ProcedureDependency
workflow.ProcedureDependency::Description <-- workflow.ProcedureDependency_gross::Description
workflow.ProcedureDependency::id <-- workflow.ProcedureDependency_gross::id
workflow.ProcedureDependency::is_active <-- workflow.ProcedureDependency_gross::is_active
workflow.ProcedureDependency::is_PersistenceDependency <-- workflow.ProcedureDependency_gross::is_PersistenceDependency
workflow.ProcedureDependency::is_PersistenceDependency <-- workflow.ProcedureDependency_input_PersistenceDependency::is_PersistenceDependency
workflow.ProcedureDependency::referenced_Procedure_RepoObject_guid <-- workflow.ProcedureDependency_gross::referenced_Procedure_RepoObject_guid
workflow.ProcedureDependency::referenced_Procedure_RepoObject_guid <-- workflow.ProcedureDependency_input_PersistenceDependency::referenced_Procedure_RepoObject_guid
workflow.ProcedureDependency::referenced_Procedure_RepoObject_guid <-- workflow.Workflow_ProcedureDependency::referenced_Procedure_RepoObject_guid
workflow.ProcedureDependency::referenced_Procedure_RepoObject_guid <-- workflow.Workflow_ProcedureDependency_all::referenced_Procedure_RepoObject_guid
workflow.ProcedureDependency::referencing_Procedure_RepoObject_guid <-- workflow.ProcedureDependency_gross::referencing_Procedure_RepoObject_guid
workflow.ProcedureDependency::referencing_Procedure_RepoObject_guid <-- workflow.ProcedureDependency_input_PersistenceDependency::referencing_Procedure_RepoObject_guid
workflow.ProcedureDependency::referencing_Procedure_RepoObject_guid <-- workflow.Workflow_ProcedureDependency::referencing_Procedure_RepoObject_guid
workflow.ProcedureDependency::referencing_Procedure_RepoObject_guid <-- workflow.Workflow_ProcedureDependency_all::referencing_Procedure_RepoObject_guid
footer
to view a reduced diagram in original size and to be able to click on the links:
open the diagram in a new tab via the Context menu.
end footer

@enduml

